COPASI API: CCopasiDataModel Class Reference
CCopasiDataModel Class Reference
#include <CCopasiDataModel.h>
Classes
class CData
Public Member Functions
bool addDefaultReports ()
bool addDefaultTasks ()
CReportDefinition * addReport (const CCopasiTask::Type &taskType)
CCopasiTask * addTask (const CCopasiTask::Type &taskType)
bool appendDependentTasks (std::set< const CCopasiObject * > candidates, std::set< const CCopasiObject * > &dependentTasks) const
bool autoSave ()
CCopasiDataModel (const bool withGUI=false)
CCopasiDataModel (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", bool withGUI=false)
void changed (const bool &changed=true)
void deleteOldData ()
bool exportMathModel (const std::string &fileName, CProcessReport *pProcessReport, const std::string &filter, bool overwriteFile=false)
std::string exportMathModelToString (CProcessReport *pProcessReport, const std::string &filter)
bool exportSBML (const std::string &fileName, bool overwriteFile=false, int sbmlLevel=2, int sbmlVersion=1, bool exportIncomplete=false, bool exportCOPASIMIRIAM=true, CProcessReport *pExportHandler=NULL)
std::string exportSBMLToString (CProcessReport *pExportHandler, int sbmlLevel, int sbmlVersion)
std::map< CCopasiObject
*, SBase * > & getCopasi2SBMLMap ()
SBMLDocument * getCurrentSBMLDocument ()
CCopasiObject * getDataObject (const CCopasiObjectName &CN) const
const std::string & getFileName () const
SCopasiXMLGUI * getGUI ()
CListOfLayouts * getListOfLayouts ()
const CListOfLayouts * getListOfLayouts () const
CModel * getModel ()
const CModel * getModel () const
const COutputDefinitionVector * getPlotDefinitionList () const
COutputDefinitionVector * getPlotDefinitionList ()
const std::string & getReferenceDirectory () const
const CReportDefinitionVector * getReportDefinitionList () const
CReportDefinitionVector * getReportDefinitionList ()
const std::string & getSBMLFileName () const
CCopasiVectorN< CCopasiTask > * getTaskList ()
const CCopasiVectorN
< CCopasiTask > * getTaskList () const
bool importSBML (const std::string &fileName, CProcessReport *pImportHandler=NULL, const bool &deleteOldData=true)
bool importSBMLFromString (const std::string &sbmlDocumentText, CProcessReport *pImportHandler=NULL, const bool &deleteOldData=true)
bool isChanged () const
bool loadModel (std::istream &in, const std::string &pwd, CProcessReport *pProcessReport, const bool &deleteOldData=true)
bool loadModel (const std::string &fileName, CProcessReport *pProcessReport, const bool &deleteOldData=true)
bool newModel (CProcessReport *pProcessReport, const bool &deleteOldData)
CObjectInterface * ObjectFromCN (const std::vector< CCopasiContainer * > &listOfContainer, const CCopasiObjectName &objName) const
CCopasiObject * ObjectFromName (const std::vector< CCopasiContainer * > &listOfContainer, const CCopasiObjectName &CN) const
bool removeLayout (const std::string &key)
bool saveModel (const std::string &fileName, CProcessReport *pProcessReport, bool overwriteFile=false, const bool &autoSave=false)
bool setSBMLFileName (const std::string &fileName)
virtual ~CCopasiDataModel ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from COutputHandler
virtual void addInterface (COutputInterface *pInterface)
virtual bool compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel *pDataModel)
COutputHandler ()
COutputHandler (const COutputHandler &src)
virtual void finish ()
std::set< COutputInterface * > getInterfaces () const
bool isMaster () const
virtual void output (const Activity &activity)
virtual void removeInterface (COutputInterface *pInterface)
virtual void separate (const Activity &activity)
void setMaster (COutputHandler *pMaster)
virtual ~COutputHandler ()
Public Member Functions inherited from COutputInterface
virtual void close ()
COutputInterface ()
COutputInterface (const COutputInterface &src)
virtual const std::set< const
CCopasiObject * > & getObjects () const
virtual ~COutputInterface ()
Public Attributes
std::set< CCopasiObject * > mLastAddedObjects
CCopasiVectorS< CMetabOld > * pOldMetabolites
Protected Member Functions
void commonAfterLoad (CProcessReport *pProcessReport, const bool &deleteOldData)
void popData ()
void pushData ()
void removeSBMLIdFromFunctions ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Member Functions inherited from COutputHandler
bool compileRefresh (const std::vector< CCopasiContainer * > &listOfContainer, const CCopasiDataModel *pDataModel)
void refresh ()
Protected Attributes
CData mData
CData mOldData
CDataModelRenameHandler mRenameHandler
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from COutputHandler
std::set< COutputInterface * > mInterfaces
std::vector< Refresh * > mObjectRefreshes
COutputHandler * mpMaster
Protected Attributes inherited from COutputInterface
std::set< const CCopasiObject * > mObjects
Private Types
enum FileType {
CopasiML = 0, SBML, SEDML, Gepasi,
unset
}
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from COutputInterface
enum Activity { BEFORE = 0x01, DURING = 0x02, AFTER = 0x04 }
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 78 of file CCopasiDataModel.h.
Member Enumeration Documentation
enum CCopasiDataModel::FileType private
Enumerator
CopasiML
SBML
SEDML
Gepasi
unset
Definition at line 80 of file CCopasiDataModel.h.
   {
     CopasiML = 0,
     SBML,
     SEDML,
     Gepasi,
     unset
   };
Constructor & Destructor Documentation
CCopasiDataModel::CCopasiDataModel (const bool withGUI = false)
Definition at line 113 of file CCopasiDataModel.cpp.
References mRenameHandler, newModel(), CCopasiTimer::PROCESS, CCopasiObject::setRenameHandler(), and CCopasiTimer::WALL.
                                                     :
   CCopasiContainer("Root", NULL, "CN", CCopasiObject::DataModel),
   COutputHandler(),
   mData(withGUI),
   mOldData(withGUI),
   mRenameHandler(),
   pOldMetabolites(new CCopasiVectorS < CMetabOld >)
 {
   newModel(NULL, true);
   CCopasiObject::setRenameHandler(&mRenameHandler);
   new CCopasiTimer(CCopasiTimer::WALL, this);
   new CCopasiTimer(CCopasiTimer::PROCESS, this);
 }
CCopasiDataModel::CCopasiDataModel (const std::string & name, const CCopasiContainer * pParent = NULL, const std::string & type = "CN", bool withGUI = false)
Definition at line 127 of file CCopasiDataModel.cpp.
References mRenameHandler, newModel(), CCopasiTimer::PROCESS, CCopasiObject::setRenameHandler(), and CCopasiTimer::WALL.
                                                 :
   CCopasiContainer(name, pParent, type, CCopasiObject::DataModel),
   COutputHandler(),
   mData(withGUI),
   mOldData(withGUI),
   mRenameHandler(),
   pOldMetabolites(new CCopasiVectorS < CMetabOld >)
 {
   newModel(NULL, true);
   CCopasiObject::setRenameHandler(&mRenameHandler);
   new CCopasiTimer(CCopasiTimer::WALL, this);
   new CCopasiTimer(CCopasiTimer::PROCESS, this);
 }
CCopasiDataModel::~CCopasiDataModel () virtual
Definition at line 144 of file CCopasiDataModel.cpp.
References deleteOldData(), mData, mOldData, pdelete, pOldMetabolites, and CCopasiObject::setRenameHandler().
 {
   CCopasiObject::setRenameHandler(NULL);
   // Make sure that the old data is deleted
   deleteOldData();
   // Delete the current data
   mOldData = mData;
   deleteOldData();
   pdelete(pOldMetabolites);
 }
Member Function Documentation
bool CCopasiDataModel::addDefaultReports ()
Definition at line 1727 of file CCopasiDataModel.cpp.
References addReport(), C_INVALID_INDEX, CCopasiVectorN< CType >::getIndex(), CCopasiTask::getReport(), CReport::getReportDefinition(), mData, CCopasiDataModel::CData::pReportDefinitionList, pTask, CCopasiDataModel::CData::pTaskList, CReport::setReportDefinition(), and CCopasiTask::TypeName.
Referenced by commonAfterLoad().
 {
   size_t i;
   for (i = 0; CCopasiTask::TypeName[i] != ""; i++)
     {
       //try to create the report if it doesn't exist
       if (mData.pReportDefinitionList->getIndex(CCopasiTask::TypeName[i]) == C_INVALID_INDEX)
         {
           addReport((CCopasiTask::Type) i);
         }
       //see if the report exists now
       CReportDefinition* pReportDef = NULL;
       if (mData.pReportDefinitionList->getIndex(CCopasiTask::TypeName[i]) != C_INVALID_INDEX)
         pReportDef = (*mData.pReportDefinitionList)[CCopasiTask::TypeName[i]];
       //see if the task exists
       CCopasiTask* pTask = NULL;
       if (mData.pTaskList->getIndex(CCopasiTask::TypeName[i]) != C_INVALID_INDEX)
         pTask = (*mData.pTaskList)[CCopasiTask::TypeName[i]];
       if (pTask && pReportDef) //task and report definition exist
         {
           //if there is no report definition set the default
           if (!pTask->getReport().getReportDefinition())
             {
               pTask->getReport().setReportDefinition(pReportDef);
             }
           //TODO: also set the default report if no target file is set
           //even if a report is already set?
         }
     }
   return true;
 }
bool CCopasiDataModel::addDefaultTasks ()
Definition at line 1501 of file CCopasiDataModel.cpp.
References addTask(), C_INVALID_INDEX, CCopasiVectorN< CType >::getIndex(), mData, CCopasiDataModel::CData::pTaskList, and CCopasiTask::TypeName.
Referenced by commonAfterLoad().
 {
   size_t i;
   for (i = 0; CCopasiTask::TypeName[i] != ""; i++)
     if (mData.pTaskList->getIndex(CCopasiTask::TypeName[i]) == C_INVALID_INDEX)
       addTask((CCopasiTask::Type) i);
   return true;
 }
CReportDefinition * CCopasiDataModel::addReport (const CCopasiTask::Type & taskType)
Definition at line 1544 of file CCopasiDataModel.cpp.
References CCopasiVectorN< CType >::add(), CCopasiTask::fluxMode, CReportDefinition::getBodyAddr(), CReportDefinition::getFooterAddr(), CReportDefinition::getHeaderAddr(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, mData, CCopasiTask::optimization, CCopasiTask::parameterFitting, CCopasiDataModel::CData::pReportDefinitionList, CCopasiTask::scan, CCopasiTask::sens, CReportDefinition::setComment(), CReportDefinition::setIsTable(), CReportDefinition::setSeparator(), CReportDefinition::setTaskType(), CReportDefinition::setTitle(), CCopasiTask::steadyState, CCopasiTask::timeCourse, CCopasiTask::tssAnalysis, and CCopasiTask::TypeName.
Referenced by addDefaultReports().
 {
   CReportDefinition * pReport = NULL;
   switch (taskType)
     {
       case CCopasiTask::steadyState:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Steady-State]"));
         break;
       case CCopasiTask::timeCourse:
         // No default report available.
         break;
       case CCopasiTask::scan:
         // No default report available.
         break;
       case CCopasiTask::fluxMode:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Elementary Flux Modes],Object=Result"));
         break;
       case CCopasiTask::optimization:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Optimization],Object=Description"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("String=\\[Function Evaluations\\]"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("String=\\[Best Value\\]"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("String=\\[Best Parameters\\]"));
         // Body
         pReport->getBodyAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Optimization],Problem=Optimization,Reference=Function Evaluations"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Optimization],Problem=Optimization,Reference=Best Value"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Optimization],Problem=Optimization,Reference=Best Parameters"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Optimization],Object=Result"));
         break;
         //**************************************************************************
       case CCopasiTask::parameterFitting:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Parameter Estimation],Object=Description"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("String=\\[Function Evaluations\\]"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("String=\\[Best Value\\]"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("String=\\[Best Parameters\\]"));
         // Body
         pReport->getBodyAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Parameter Estimation],Problem=Parameter Estimation,Reference=Function Evaluations"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Parameter Estimation],Problem=Parameter Estimation,Reference=Best Value"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("Separator=\t"));
         pReport->getBodyAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Parameter Estimation],Problem=Parameter Estimation,Reference=Best Parameters"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Parameter Estimation],Object=Result"));
         break;
         //**************************************************************************
       case CCopasiTask::lyap:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Lyapunov Exponents],Object=Description"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Lyapunov Exponents],Object=Result"));
         break;
         //**************************************************************************
       case CCopasiTask::mca:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Metabolic Control Analysis],Object=Description"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Metabolic Control Analysis],Object=Result"));
         break;
         //**************************************************************************
       case CCopasiTask::lna:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Linear Noise Approximation],Object=Description"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Linear Noise Approximation],Object=Result"));
         break;
         //**************************************************************************
       case CCopasiTask::sens:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Sensitivities],Object=Description"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Sensitivities],Object=Result"));
         break;
         //**************************************************************************
       case CCopasiTask::tssAnalysis:
         pReport = new CReportDefinition(CCopasiTask::TypeName[taskType]);
         pReport->setTaskType(taskType);
         pReport->setComment("Automatically generated report.");
         pReport->setIsTable(false);
         pReport->setTitle(false);
         pReport->setSeparator(CCopasiReportSeparator("\t"));
         // Header
         pReport->getHeaderAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Time Scale Separation Analysis],Object=Description"));
         // Footer
         pReport->getFooterAddr()->push_back(CCopasiObjectName("String=\n"));
         pReport->getFooterAddr()->push_back(CCopasiObjectName("CN=Root,Vector=TaskList[Time Scale Separation Analysis],Object=Result"));
         break;
       default:
         return pReport;
     }
   if (pReport) mData.pReportDefinitionList->add(pReport, true);
   return pReport;
 }
CCopasiTask * CCopasiDataModel::addTask (const CCopasiTask::Type & taskType)
Definition at line 1431 of file CCopasiDataModel.cpp.
References CCopasiVectorN< CType >::add(), CCopasiTask::crosssection, CCopasiTask::fluxMode, CCopasiTask::getProblem(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, mData, CCopasiTask::moieties, CCopasiTask::optimization, CCopasiTask::parameterFitting, CCopasiDataModel::CData::pModel, pTask, CCopasiDataModel::CData::pTaskList, CCopasiTask::scan, CCopasiTask::sens, CCopasiProblem::setModel(), CCopasiTask::steadyState, CCopasiTask::timeCourse, and CCopasiTask::tssAnalysis.
Referenced by addDefaultTasks().
 {
   CCopasiTask * pTask = NULL;
   switch (taskType)
     {
       case CCopasiTask::steadyState:
         pTask = new CSteadyStateTask(mData.pTaskList);
         break;
       case CCopasiTask::timeCourse:
         pTask = new CTrajectoryTask(mData.pTaskList);
         break;
       case CCopasiTask::scan:
         pTask = new CScanTask(mData.pTaskList);
         break;
       case CCopasiTask::fluxMode:
         pTask = new CEFMTask(mData.pTaskList);
         break;
       case CCopasiTask::optimization:
         pTask = new COptTask(taskType, mData.pTaskList);
         break;
       case CCopasiTask::parameterFitting:
         pTask = new CFitTask(taskType, mData.pTaskList);
         break;
       case CCopasiTask::mca:
         pTask = new CMCATask(mData.pTaskList);
         static_cast< CMCAProblem * >(pTask->getProblem())->setSteadyStateRequested(true);
         break;
       case CCopasiTask::lna:
         pTask = new CLNATask(mData.pTaskList);
         static_cast< CLNAProblem * >(pTask->getProblem())->setSteadyStateRequested(true);
         break;
       case CCopasiTask::lyap:
         pTask = new CLyapTask(mData.pTaskList);
         break;
       case CCopasiTask::sens:
         pTask = new CSensTask(mData.pTaskList);
         break;
       case CCopasiTask::tssAnalysis:
         pTask = new CTSSATask(mData.pTaskList);
         break;
       case CCopasiTask::moieties:
         pTask = new CMoietiesTask(taskType, mData.pTaskList);
         break;
       case CCopasiTask::crosssection:
         pTask = new CCrossSectionTask(mData.pTaskList);
         break;
       default:
         return pTask;
     }
   pTask->getProblem()->setModel(mData.pModel);
   mData.pTaskList->add(pTask);
   return pTask;
 }
bool CCopasiDataModel::appendDependentTasks (std::set< const CCopasiObject * > candidates, std::set< const CCopasiObject * > & dependentTasks) const
Appends pointers to tasks, which are dependent on any of the candidates to the list dependentTasks.
Parameters
std::set< const CCopasiObject * > candidates
std::set< const CCopasiObject * > & dependentTasks
Returns
bool functionsAppended
Definition at line 1512 of file CCopasiDataModel.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), mData, and CCopasiDataModel::CData::pTaskList.
Referenced by CQReportDefinition::btnDeleteReportClicked(), CQMessageBox::confirmDelete(), and CQReportDM::removeRows().
 {
   size_t Size = dependentTasks.size();
   std::set< const CCopasiObject * >::const_iterator it = candidates.begin();
   std::set< const CCopasiObject * >::const_iterator end = candidates.end();
   CCopasiVectorN< CCopasiTask >::const_iterator itTask = mData.pTaskList->begin();
   CCopasiVectorN< CCopasiTask >::const_iterator endTask = mData.pTaskList->end();
   for (; it != end; ++it)
     {
       const CReportDefinition * pReportDefinition = dynamic_cast< const CReportDefinition * >(*it);
       if (pReportDefinition == NULL)
         continue;
       itTask = mData.pTaskList->begin();
       for (; itTask != endTask; ++itTask)
         {
           if ((*itTask)->getReport().getReportDefinition() == pReportDefinition)
             {
               dependentTasks.insert(*itTask);
             }
         }
     }
   return Size < dependentTasks.size();
 }
bool CCopasiDataModel::autoSave ()
Definition at line 482 of file CCopasiDataModel.cpp.
References CDirEntry::baseName(), COptions::getValue(), CCopasiDataModel::CData::mAutoSaveNeeded, mData, CCopasiDataModel::CData::mSaveFileName, saveModel(), and CDirEntry::Separator.
 {
   if (!mData.mAutoSaveNeeded) return true;
   std::string AutoSave;
   COptions::getValue("Tmp", AutoSave);
   if (AutoSave == "") return false;
   AutoSave += CDirEntry::Separator + "tmp_";
   if (mData.mSaveFileName != "")
     AutoSave += CDirEntry::baseName(mData.mSaveFileName);
   else
     AutoSave += "untitled";
   AutoSave += ".cps";
   try
     {
       if (!saveModel(AutoSave, NULL, true, true)) return false;
     }
   catch (...)
     {
       return false;
     }
   mData.mAutoSaveNeeded = false;
   return true;
 }
void CCopasiDataModel::changed (const bool & changed = true)
Definition at line 1829 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::mAutoSaveNeeded, CCopasiDataModel::CData::mChanged, and mData.
Referenced by commonAfterLoad(), CQTabWidget::save(), CQModelWidget::save(), CQSpeciesDetail::save(), CQNotes::save(), saveModel(), ScanWidget::saveTask(), SensitivitiesWidget::saveTask(), SteadyStateWidget::saveTask(), FunctionWidget1::saveToFunction(), and CQPlotSubwidget::saveToPlotSpec().
 {
   mData.mChanged = changed;
   mData.mAutoSaveNeeded = changed;
 }
void CCopasiDataModel::commonAfterLoad (CProcessReport * pProcessReport, const bool & deleteOldData) protected
Definition at line 2069 of file CCopasiDataModel.cpp.
References addDefaultReports(), addDefaultTasks(), CCopasiVector< T >::begin(), changed(), CModel::compileIfNecessary(), deleteOldData(), CCopasiVector< T >::end(), CCopasiMessage::getLastMessage(), CModel::getModelParameterSet(), mData, mOldData, CCopasiDataModel::CData::mWithGUI, CCopasiTask::NO_OUTPUT, CCopasiDataModel::CData::pCurrentSBMLDocument, CCopasiDataModel::CData::pGUI, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, CCopasiDataModel::CData::pPlotDefinitionList, CCopasiDataModel::CData::pReportDefinitionList, CCopasiDataModel::CData::pTaskList, CModelEntity::setObjectParent(), CCopasiObject::setObjectParent(), CCopasiMessage::size(), CModel::updateInitialValues(), and CModelParameterSet::updateModel().
Referenced by importSBML(), importSBMLFromString(), loadModel(), and newModel().
 {
   if (mData.pModel == NULL)
     {
       mData.pModel = new CModel(this);
     }
   if (mData.pListOfLayouts == NULL)
     {
       mData.pListOfLayouts = new CListOfLayouts("ListOflayouts", this);
     }
   if (mData.pTaskList == NULL)
     {
       mData.pTaskList = new CCopasiVectorN< CCopasiTask >("TaskList", this);
     }
   if (mData.pReportDefinitionList == NULL)
     {
       mData.pReportDefinitionList = new CReportDefinitionVector("ReportDefinitions", this);
     }
   if (mData.pPlotDefinitionList == NULL)
     {
       mData.pPlotDefinitionList = new COutputDefinitionVector("OutputDefinitions", this);
     }
   if (mData.mWithGUI && mData.pGUI == NULL)
     {
       mData.pGUI = new SCopasiXMLGUI("GUI", this);
     }
   // We have at least one task of every type
   addDefaultTasks();
   addDefaultReports();
   if (mOldData.pModel != NULL &&
       mOldData.pModel != mData.pModel)
     {
       mOldData.pModel->setObjectParent(NULL);
       remove(mOldData.pModel);
     }
   else
     mOldData.pModel = NULL;
   if (mOldData.pTaskList != NULL &&
       mOldData.pTaskList != mData.pTaskList)
     {
       mOldData.pTaskList->setObjectParent(NULL);
       remove(mOldData.pTaskList);
     }
   else
     mOldData.pTaskList = NULL;
   if (mOldData.pReportDefinitionList != NULL &&
       mOldData.pReportDefinitionList != mData.pReportDefinitionList)
     {
       mOldData.pReportDefinitionList->setObjectParent(NULL);
       remove(mOldData.pReportDefinitionList);
     }
   else
     mOldData.pReportDefinitionList = NULL;
   if (mOldData.pPlotDefinitionList != NULL &&
       mOldData.pPlotDefinitionList != mData.pPlotDefinitionList)
     {
       mOldData.pPlotDefinitionList->setObjectParent(NULL);
       remove(mOldData.pPlotDefinitionList);
     }
   else
     mOldData.pPlotDefinitionList = NULL;
   if (mOldData.pListOfLayouts != NULL &&
       mOldData.pListOfLayouts != mData.pListOfLayouts)
     {
       mOldData.pListOfLayouts->setObjectParent(NULL);
       remove(mOldData.pListOfLayouts);
     }
   else
     mOldData.pListOfLayouts = NULL;
   if (mOldData.pGUI != NULL &&
       mOldData.pGUI != mData.pGUI)
     {
       mOldData.pGUI->setObjectParent(NULL);
       remove(mOldData.pGUI);
     }
   else
     mOldData.pGUI = NULL;
   if (mOldData.pCurrentSBMLDocument == mData.pCurrentSBMLDocument)
     mOldData.pCurrentSBMLDocument = NULL;
 #ifdef COPASI_SEDML
   if (mOldData.pCurrentSEDMLDocument == mData.pCurrentSEDMLDocument)
     mOldData.pCurrentSEDMLDocument = NULL;
 #endif
   mData.pModel->getModelParameterSet().updateModel();
   // We need to initialize all the task so that results are available
   // We suppress all errors and warnings
   size_t Size = CCopasiMessage::size();
   CCopasiVectorN< CCopasiTask >::iterator it = mData.pTaskList->begin();
   CCopasiVectorN< CCopasiTask >::iterator end = mData.pTaskList->end();
   for (; it != end; ++it)
     {
       try
         {
           // need initialize, so that all objects are created for the
           // object browser
           (*it)->initialize(CCopasiTask::NO_OUTPUT, NULL, NULL);
           // but we should restore any possible changes made to the model
           // by the task, without updating the model
           bool update = (*it)->isUpdateModel();
           (*it)->setUpdateModel(false);
           (*it)->restore();
           (*it)->setUpdateModel(update);
         }
       catch (...) {}
     }
   // Remove error messages created by the task initialization as this may fail
   // due to incomplete task specification at this time.
   while (CCopasiMessage::size() > Size)
     CCopasiMessage::getLastMessage();
   if (mData.pModel)
     {
       mData.pModel->compileIfNecessary(pProcessReport);
       mData.pModel->updateInitialValues();
     }
   changed(false);
   if (deleteOldData)
     {
       CCopasiDataModel::deleteOldData();
     }
 }
void CCopasiDataModel::deleteOldData ()
Definition at line 1389 of file CCopasiDataModel.cpp.
References mOldData, CCopasiDataModel::CData::pCurrentSBMLDocument, pdelete, CCopasiDataModel::CData::pGUI, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, CCopasiDataModel::CData::pPlotDefinitionList, CCopasiDataModel::CData::pReportDefinitionList, and CCopasiDataModel::CData::pTaskList.
Referenced by commonAfterLoad(), DataModelGUI::linkDataModelToGUI(), and ~CCopasiDataModel().
 {
   pdelete(mOldData.pModel);
   pdelete(mOldData.pTaskList);
   pdelete(mOldData.pReportDefinitionList);
   pdelete(mOldData.pPlotDefinitionList);
   pdelete(mOldData.pListOfLayouts);
   pdelete(mOldData.pGUI);
   pdelete(mOldData.pCurrentSBMLDocument);
 #ifdef COPASI_SEDML
   pdelete(mOldData.pCurrentSEDMLDocument);
 #endif
 }
bool CCopasiDataModel::exportMathModel (const std::string & fileName, CProcessReport * pProcessReport, const std::string & filter, bool overwriteFile = false)
Definition at line 969 of file CCopasiDataModel.cpp.
References CCopasiVector< T >::begin(), CCopasiMessage::clearDeque(), CModel::compileIfNecessary(), CDirEntry::dirName(), CCopasiVector< T >::end(), CCopasiMessage::ERROR, CDirEntry::exist(), CODEExporter::exportToStream(), CLocaleString::fromUtf8(), CModel::getModelValues(), CDirEntry::isWritable(), MCDirEntry, MCODEExporter, mData, CCopasiDataModel::CData::pModel, and CCopasiMessage::WARNING.
Referenced by main().
 {
   CCopasiMessage::clearDeque();
   if (fileName == "") return false;
   if (CDirEntry::exist(fileName))
     {
       if (!overwriteFile)
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          MCDirEntry + 1,
                          fileName.c_str());
           return false;
         }
       if (!CDirEntry::isWritable(fileName))
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          MCDirEntry + 2,
                          fileName.c_str());
           return false;
         }
     }
   else if (!CDirEntry::isWritable(CDirEntry::dirName(fileName)))
     {
       CCopasiMessage(CCopasiMessage::ERROR,
                      MCDirEntry + 2,
                      fileName.c_str());
       return false;
     }
   try
     {
       if (!mData.pModel->compileIfNecessary(pProcessReport))
         return false;
     }
   catch (...)
     {
       return false;
     }
   CCopasiVector< CModelValue >::const_iterator it = mData.pModel->getModelValues().begin();
   CCopasiVector< CModelValue >::const_iterator end = mData.pModel->getModelValues().end();
   for (; it != end; ++it)
     if ((*it)->isUsed()) break;
   if (it != end)
     CCopasiMessage(CCopasiMessage::WARNING, MCODEExporter + 2);
   CODEExporter * pExporter = NULL;
   if (filter == "C Files (*.c)")
     {
       pExporter = new CODEExporterC;
     }
   else if (filter == "Berkeley Madonna Files (*.mmd)")
     {
       pExporter = new CODEExporterBM();
     }
   else if (filter == "XPPAUT (*.ode)")
     {
       pExporter = new CODEExporterXPPAUT;
     }
   if (pExporter == NULL)
     {
       return false;
     }
   std::ofstream os(CLocaleString::fromUtf8(fileName).c_str(), std::ios::out);
   if (!os.good())
     {
       CCopasiMessage(CCopasiMessage::ERROR,
                      MCDirEntry + 3,
                      fileName.c_str());
       return false;
     }
   return pExporter->exportToStream(this, os);
 }
std::string CCopasiDataModel::exportMathModelToString (CProcessReport * pProcessReport, const std::string & filter)
Definition at line 917 of file CCopasiDataModel.cpp.
References CCopasiVector< T >::begin(), CModel::compileIfNecessary(), CCopasiVector< T >::end(), CODEExporter::exportToStream(), CModel::getModelValues(), MCODEExporter, mData, CCopasiDataModel::CData::pModel, and CCopasiMessage::WARNING.
 {
   CODEExporter * pExporter = NULL;
   if (filter == "C Files (*.c)")
     {
       pExporter = new CODEExporterC;
     }
   else if (filter == "Berkeley Madonna Files (*.mmd)")
     {
       pExporter = new CODEExporterBM();
     }
   else if (filter == "XPPAUT (*.ode)")
     {
       pExporter = new CODEExporterXPPAUT;
     }
   if (pExporter == NULL)
     {
       return "";
     }
   try
     {
       if (!mData.pModel->compileIfNecessary(pProcessReport))
         return "";
     }
   catch (...)
     {
       return "";
     }
   CCopasiVector< CModelValue >::const_iterator it = mData.pModel->getModelValues().begin();
   CCopasiVector< CModelValue >::const_iterator end = mData.pModel->getModelValues().end();
   for (; it != end; ++it)
     if ((*it)->isUsed()) break;
   if (it != end)
     CCopasiMessage(CCopasiMessage::WARNING, MCODEExporter + 2);
   std::ostringstream os;
   if (!pExporter->exportToStream(this, os))
     {
       return "";
     }
   return os.str();
 }
bool CCopasiDataModel::exportSBML (const std::string & fileName, bool overwriteFile = false, int sbmlLevel = 2, int sbmlVersion = 1, bool exportIncomplete = false, bool exportCOPASIMIRIAM = true, CProcessReport * pExportHandler = NULL)
Definition at line 798 of file CCopasiDataModel.cpp.
References CCopasiMessage::clearDeque(), CModel::compileIfNecessary(), CSBMLExporter::disownSBMLDocument(), CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CDirEntry::exist(), CSBMLExporter::exportModel(), CDirEntry::fileName(), CCopasiMessage::getAllMessageText(), CSBMLExporter::getCOPASI2SBMLMap(), CSBMLExporter::getSBMLDocument(), COptions::getValue(), CDirEntry::isRelativePath(), CDirEntry::isWritable(), CDirEntry::makePathAbsolute(), MCDirEntry, CCopasiDataModel::CData::mCopasi2SBMLMap, mData, CCopasiDataModel::CData::mSBMLFileName, CCopasiDataModel::CData::pCurrentSBMLDocument, pdelete, CCopasiDataModel::CData::pModel, and CSBMLExporter::setExportCOPASIMIRIAM().
 {
   CCopasiMessage::clearDeque();
   if (fileName == "") return false;
   std::string PWD;
   COptions::getValue("PWD", PWD);
   std::string FileName = fileName;
   if (CDirEntry::isRelativePath(FileName) &&
       !CDirEntry::makePathAbsolute(FileName, PWD))
     FileName = CDirEntry::fileName(FileName);
   if (CDirEntry::exist(FileName))
     {
       if (!overwriteFile)
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          MCDirEntry + 1,
                          FileName.c_str());
           return false;
         }
       if (!CDirEntry::isWritable(FileName))
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          MCDirEntry + 2,
                          FileName.c_str());
           return false;
         }
     }
   CCopasiMessage::clearDeque();
   static std::string failedCompile("The model cannot be exported, as it failed to compile. \n%s");
   try
     {
       if (!mData.pModel->compileIfNecessary(pExportHandler))
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, failedCompile.c_str(), CCopasiMessage::getAllMessageText().c_str());
           return false;
         }
     }
   catch (CCopasiException&)
     {
       // don't add the exception twice
       throw;
     }
   catch (...)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, failedCompile.c_str(), CCopasiMessage::getAllMessageText().c_str());
       return false;
     }
   CSBMLExporter exporter;
   exporter.setExportCOPASIMIRIAM(exportCOPASIMIRIAM);
   SBMLDocument* pOrigSBMLDocument = NULL;
 #if LIBSBML_VERSION >= 40100
   // if we export an L2 model to L3 or vice versa, we have to throw away any prior information
   // about the current sbml document because libsbml does not support the conversion
   // so we need to make sure that all model elements are created from scratch from the corresponding COPASI elements
   if (this->mData.pCurrentSBMLDocument != NULL &&
       ((this->mData.pCurrentSBMLDocument->getLevel() > 2 && sbmlLevel < 3) ||
        (this->mData.pCurrentSBMLDocument->getLevel() < 3 && sbmlLevel > 2)
       )
      )
     {
       pOrigSBMLDocument = this->mData.pCurrentSBMLDocument;
       this->mData.pCurrentSBMLDocument = NULL;
     }
 #endif // LIBSBML_VERSION
   //exporter.setExportHandler(pExportHandler);
   if (!exporter.exportModel(*this, FileName, sbmlLevel, sbmlVersion, overwriteFile)) return false;
   // only get the new model if it is not a Level 1 model
   // During export to Level 1 the function definitions have been deleted and therefore
   // all information assiociated with the function definitions will be gone if the user exports
   // to Level 2 after having exported to Level 1
   // This is actual vital to get around Bug 1086 as well.
   // Once I have a Level 1 model, all calls to setName on an
   // SBML object in that model also resets the id, which does not work with the current exporter
   if ((sbmlLevel != 1 || mData.pCurrentSBMLDocument == NULL) && pOrigSBMLDocument == NULL)
     {
       if (mData.pCurrentSBMLDocument != exporter.getSBMLDocument())
         pdelete(mData.pCurrentSBMLDocument);
       // disown the SBML Document from the exporter so we don't have to copy it
       exporter.disownSBMLDocument();
       mData.pCurrentSBMLDocument = exporter.getSBMLDocument();
       // we also need to get the new copasi2sbml map otherwise it contains invalid pointers
       // since the objects
       mData.mCopasi2SBMLMap.clear();
       std::map<const CCopasiObject*, SBase*>::const_iterator it = exporter.getCOPASI2SBMLMap().begin();
       std::map<const CCopasiObject*, SBase*>::const_iterator endit = exporter.getCOPASI2SBMLMap().end();
       while (it != endit)
         {
           mData.mCopasi2SBMLMap.insert(std::pair<CCopasiObject*, SBase*>(const_cast<CCopasiObject*>(it->first), it->second));
           ++it;
         }
     }
   // if we have saved the original SBML model somewhere
   // we have to reset it
   else if (pOrigSBMLDocument != NULL)
     {
       this->mData.pCurrentSBMLDocument = pOrigSBMLDocument;
     }
   mData.mSBMLFileName = FileName;
   return true;
 }
std::string CCopasiDataModel::exportSBMLToString (CProcessReport * pExportHandler, int sbmlLevel, int sbmlVersion)
Definition at line 709 of file CCopasiDataModel.cpp.
References CCopasiMessage::clearDeque(), CModel::compileIfNecessary(), CSBMLExporter::disownSBMLDocument(), CCopasiMessage::EXCEPTION, CSBMLExporter::exportModelToString(), CCopasiMessage::getAllMessageText(), CSBMLExporter::getCOPASI2SBMLMap(), CSBMLExporter::getSBMLDocument(), CCopasiDataModel::CData::mCopasi2SBMLMap, mData, CCopasiDataModel::CData::pCurrentSBMLDocument, pdelete, CCopasiDataModel::CData::pModel, and CSBMLExporter::setExportCOPASIMIRIAM().
Referenced by test000054::test_bug1002(), test000055::test_bug1004(), test000057::test_bug1006(), test000058::test_bug1025_1(), test000058::test_bug1025_10(), test000058::test_bug1025_2(), test000058::test_bug1025_3(), test000058::test_bug1025_4(), test000058::test_bug1025_5(), test000058::test_bug1025_6(), test000058::test_bug1025_7(), test000058::test_bug1025_8(), test000058::test_bug1025_9(), test000076::test_bug1035_1(), test000076::test_bug1035_2(), test000076::test_bug1035_3(), test000067::test_bug1060(), test000068::test_bug1068(), test000069::test_bug1069(), test000070::test_bug1084(), test000071::test_bug1085(), test000072::test_bug1086(), test000074::test_bug1088(), test000081::test_bug1205(), test000089::test_bug1412(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000100::test_bug1692_1(), test000100::test_bug1692_2(), test000101::test_bug1740(), test000102::test_bug1741(), test000103::test_bug1743_l2(), test000103::test_bug1743_l3(), test000050::test_bug894(), test000049::test_bug894(), test000048::test_bug919(), test000051::test_bug988(), test000060::test_bug_1026(), test000061::test_bug_1044(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000082::test_export_delayAssignment_1(), test000082::test_export_delayAssignment_2(), test000082::test_export_delayAssignment_3(), test000082::test_export_delayAssignment_4(), test000082::test_export_delayAssignment_5(), test000082::test_export_delayAssignment_6(), test000077::test_export_dimensionless(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000097::test_export_global_render_information(), test000097::test_export_local_render_information(), test000098::test_export_notes(), test000087::test_export_reaction_flux_reference_1(), test000087::test_export_reaction_flux_reference_2(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_8(), test000097::test_importexport_global_render_information(), test000097::test_importexport_local_render_information(), test000092::test_miriam_export_1(), test000092::test_miriam_export_2(), test000092::test_miriam_export_3(), test000092::test_miriam_export_4(), test000092::test_miriam_export_5(), test000092::test_miriam_export_6(), test000092::test_miriam_export_7(), test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000097::test_readexport_global_render_information(), test000097::test_readexport_local_render_information(), test000059::test_unique_id_1(), test000059::test_unique_id_10(), test000059::test_unique_id_11(), test000059::test_unique_id_12(), test000059::test_unique_id_13(), test000059::test_unique_id_14(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_2(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), test000059::test_unique_id_21_2(), test000059::test_unique_id_22(), test000059::test_unique_id_3(), test000059::test_unique_id_4(), test000059::test_unique_id_5(), test000059::test_unique_id_6(), test000059::test_unique_id_7(), test000059::test_unique_id_8(), test000059::test_unique_id_9(), Copasi2SBMLTranslator::translateFileToSBML(), and Copasi2SBMLTranslator::translateToSBML().
 {
   CCopasiMessage::clearDeque();
   SBMLDocument* pOrigSBMLDocument = NULL;
 #if LIBSBML_VERSION >= 40100
   // if we export an L2 model to L3 or vice versa, we have to throw away any prior information
   // about the current sbml document because libsbml does not support the conversion
   // so we need to make sure that all model elements are created from scratch from the corresponding COPASI elements
   if (this->mData.pCurrentSBMLDocument != NULL &&
       ((this->mData.pCurrentSBMLDocument->getLevel() > 2 && sbmlLevel < 3) ||
        (this->mData.pCurrentSBMLDocument->getLevel() < 3 && sbmlLevel > 2)
       )
      )
     {
       pOrigSBMLDocument = this->mData.pCurrentSBMLDocument;
       this->mData.pCurrentSBMLDocument = NULL;
     }
 #endif // LIBSBML_VERSION
   CCopasiMessage::clearDeque();
   static std::string failedCompile("The model cannot be exported, as it failed to compile. \n%s");
   try
     {
       if (!mData.pModel->compileIfNecessary(pExportHandler))
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, failedCompile.c_str(), CCopasiMessage::getAllMessageText().c_str());
           return "";
         }
     }
   catch (CCopasiException&)
     {
       // don't add the exception twice
       throw;
     }
   catch (...)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, failedCompile.c_str(), CCopasiMessage::getAllMessageText().c_str());
       return "";
     }
   CSBMLExporter exporter;
   // Per default export COPASIs MIRIAM annotation.
   // This should eventually be determined by a setting in the preferences
   // dialog.
   exporter.setExportCOPASIMIRIAM(true);
   std::string str = exporter.exportModelToString(*this, sbmlLevel, sbmlVersion);
   // only get the new model if it is not a Level 1 model
   // During export to Level 1 the function definitions have been deleted and therefore
   // all information assiociated with the function definitions will be gone if the user exports
   // to Level 2 after having exported to Level 1
   // This is actual vital to get around Bug 1086 as well.
   // Once I have a Level 1 model, all calls to setName on an
   // SBML object in that model also resets the id, which does not work with the current exporter
   if ((sbmlLevel != 1 || mData.pCurrentSBMLDocument == NULL) && pOrigSBMLDocument == NULL)
     {
       if (mData.pCurrentSBMLDocument != exporter.getSBMLDocument())
         {
           pdelete(mData.pCurrentSBMLDocument);
         }
       // disown the SBML Document from the exporter so we don't have to copy it
       exporter.disownSBMLDocument();
       mData.pCurrentSBMLDocument = exporter.getSBMLDocument();
       // we also need to get the new copasi2sbml map otherwise it contains invalid pointers
       // since the objects
       mData.mCopasi2SBMLMap.clear();
       std::map<const CCopasiObject*, SBase*>::const_iterator it = exporter.getCOPASI2SBMLMap().begin();
       std::map<const CCopasiObject*, SBase*>::const_iterator endit = exporter.getCOPASI2SBMLMap().end();
       while (it != endit)
         {
           mData.mCopasi2SBMLMap.insert(std::pair<CCopasiObject*, SBase*>(const_cast<CCopasiObject*>(it->first), it->second));
           ++it;
         }
     }
   // if we have saved the original SBML model somewhere
   // we have to reset it
   else if (pOrigSBMLDocument != NULL)
     {
       mData.pCurrentSBMLDocument = pOrigSBMLDocument;
     }
   return str;
 }
std::map< CCopasiObject *, SBase * > & CCopasiDataModel::getCopasi2SBMLMap ()
Definition at line 1854 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::mCopasi2SBMLMap, and mData.
Referenced by DataModelGUI::importCellDesigner(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), and test000067::test_bug1060().
 {
   return mData.mCopasi2SBMLMap;
 }
SBMLDocument * CCopasiDataModel::getCurrentSBMLDocument ()
Definition at line 1835 of file CCopasiDataModel.cpp.
References mData, and CCopasiDataModel::CData::pCurrentSBMLDocument.
Referenced by CSBMLExporter::createSBMLDocument(), DataModelGUI::importCellDesigner(), stress_test::normalizeMath(), test000054::test_bug1002(), test000055::test_bug1004(), test000056::test_bug1005(), test000057::test_bug1006(), test000058::test_bug1025_1(), test000058::test_bug1025_10(), test000058::test_bug1025_2(), test000058::test_bug1025_3(), test000058::test_bug1025_4(), test000058::test_bug1025_5(), test000058::test_bug1025_6(), test000058::test_bug1025_7(), test000058::test_bug1025_8(), test000058::test_bug1025_9(), test000076::test_bug1035_1(), test000076::test_bug1035_2(), test000076::test_bug1035_3(), test000067::test_bug1060(), test000068::test_bug1068(), test000069::test_bug1069(), test000071::test_bug1085(), test000081::test_bug1205(), test000089::test_bug1412(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000049::test_bug894(), test000050::test_bug894(), test000048::test_bug919(), test000051::test_bug988(), test000060::test_bug_1026(), test000061::test_bug_1044(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000082::test_export_delayAssignment_1(), test000082::test_export_delayAssignment_2(), test000082::test_export_delayAssignment_3(), test000082::test_export_delayAssignment_4(), test000082::test_export_delayAssignment_5(), test000082::test_export_delayAssignment_6(), test000077::test_export_dimensionless(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000087::test_export_reaction_flux_reference_1(), test000087::test_export_reaction_flux_reference_2(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000092::test_miriam_export_7(), test000094::test_notrequired_package(), test000059::test_unique_id_1(), test000059::test_unique_id_10(), test000059::test_unique_id_11(), test000059::test_unique_id_12(), test000059::test_unique_id_13(), test000059::test_unique_id_14(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_2(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), test000059::test_unique_id_21_2(), test000059::test_unique_id_22(), test000059::test_unique_id_3(), test000059::test_unique_id_4(), test000059::test_unique_id_5(), test000059::test_unique_id_6(), test000059::test_unique_id_7(), test000059::test_unique_id_8(), and test000059::test_unique_id_9().
 {
   return mData.pCurrentSBMLDocument;
 }
CCopasiObject * CCopasiDataModel::getDataObject (const CCopasiObjectName & CN) const
Retrieve the data object with the given CN
Parameters
const CCopasiObjectName & CN
Returns
CCopasiObject * pObject
Definition at line 1947 of file CCopasiDataModel.cpp.
References CCopasiContainer::getObject().
Referenced by CQPlotSubwidget::addCurve2D(), CSEDMLExporter::createDataGenerators(), CScanItem::CScanItem(), CQOptimizationResult::enterProtected(), CQFittingResult::enterProtected(), CODEExporter::exportExpression(), CSBMLExporter::findModelEntityDependencies(), CArrayAnnotation::getAnnotationsString(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CExpression::getNodeObject(), CSensItem::getSingleObjectDisplayName(), COptItem::getStartValue(), CSensItem::getVariablesPointerList(), CScanWidgetRandom::load(), CScanWidgetScan::load(), Curve2DWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), CQFittingItemWidget::loadSelection(), CQExperimentData::loadTable(), SensitivitiesWidget::loadTask(), CQSimpleSelectionTree::populateTree(), CQReportListItem::refreshText(), COptItem::setObjectCN(), CQFittingItemWidget::setTableText(), CQExperimentData::slotTypeChanged(), and CEvaluationNodeObject::toAST().
 {
   return dynamic_cast< CCopasiObject *>(const_cast< CObjectInterface * >(getObject(CN)));
 }
const std::string & CCopasiDataModel::getFileName () const
Definition at line 1823 of file CCopasiDataModel.cpp.
References mData, and CCopasiDataModel::CData::mSaveFileName.
Referenced by main(), CReport::open(), CopasiUI3Window::slotExportMathModel(), and validate().
 {return mData.mSaveFileName;}
SCopasiXMLGUI * CCopasiDataModel::getGUI ()
Definition at line 1815 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pGUI.
Referenced by SliderDialog::getCSlidersForObject(), and save_cps_model_to_stream().
 {
   if (mData.isValid())
     return mData.pGUI;
   return mOldData.pGUI;
 }
CListOfLayouts * CCopasiDataModel::getListOfLayouts ()
Definition at line 1807 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pListOfLayouts.
Referenced by CQNewMainWindow::addGlobalRenderInfoItemsToList(), test000097::addGlobalRenderInformation(), test000097::addLocalRenderInformation(), test000097::createModel(), CSBMLExporter::exportModelToString(), Arguments::handleCommandLine(), DataModelGUI::importCellDesigner(), CQLayoutScene::initializeResolver(), save_cps_model_to_stream(), CQLayoutsWidget::slotBtnNewClicked(), CQLayoutView::slotLayoutChanged(), CQNewMainWindow::slotLayoutChanged(), CQNewMainWindow::slotRenderInfoChanged(), CQLayoutView::slotRenderInformationChanged(), test000097::test_import_global_render_information(), test000097::test_import_local_render_information(), test000097::test_importexport_global_render_information(), test000097::test_importexport_local_render_information(), test000097::test_importwrite_global_render_information(), test000097::test_importwrite_local_render_information(), test000097::test_read_global_render_information(), test000097::test_read_local_render_information(), test000097::test_readexport_global_render_information(), test000097::test_readexport_local_render_information(), test000097::test_readwrite_global_render_information(), test000097::test_readwrite_local_render_information(), CQGLLayoutPainter::update(), updateLayoutList(), CQNewMainWindow::updateLayoutList(), updateRenderInformationList(), and CQNewMainWindow::updateRenderInformationList().
 {
   if (mData.isValid())
     return mData.pListOfLayouts;
   return mOldData.pListOfLayouts;
 }
const CListOfLayouts * CCopasiDataModel::getListOfLayouts () const
Definition at line 1799 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pListOfLayouts.
 {
   if (mData.isValid())
     return mData.pListOfLayouts;
   return mOldData.pListOfLayouts;
 }
CModel * CCopasiDataModel::getModel ()
Definition at line 1407 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pModel.
Referenced by CQPlotSubwidget::addCurve2D(), CCopasiXML::buildFunctionList(), CExperiment::calculateStatistics(), CSBMLExporter::check_for_spatial_size_units(), CSBMLExporter::checkForEvents(), CSBMLExporter::checkForInitialAssignments(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CSBMLExporter::checkForPiecewiseFunctions(), CSBMLExporter::checkForUnsupportedObjectReferences(), CSBMLExporter::collectIds(), CTimeSeries::compile(), COutputHandler::compileRefresh(), CQMessageBox::confirmDelete(), CQSpeciesDetail::copy(), CQCompartment::copy(), ReactionsWidget1::copy(), CSBMLExporter::createAreaUnit(), CSBMLExporter::createCompartments(), CSEDMLExporter::createDataGenerators(), CSBMLExporter::createEvents(), CSBMLExporter::createLengthUnit(), CSBMLExporter::createMetabolites(), test000097::createModel(), CSBMLExporter::createParameters(), createParameterSetsForExperiment(), CSBMLExporter::createReactions(), CSBMLExporter::createSBMLDocument(), CSEDMLExporter::createSEDMLDocument(), CSBMLExporter::createSubstanceUnit(), CSBMLExporter::createTimeUnit(), CSBMLExporter::createVolumeUnit(), CQPlotSubwidget::deletePlot(), CQNewMainWindow::elementaryModeTriggeredSlot(), CQLayoutsWidget::enterProtected(), CODEExporter::exportExpression(), CODEExporter::exportObjectNodesFromModel(), CODEExporter::exportToStream(), CSBMLExporter::findAvogadro(), findObjectByDisplayName(), SliderDialog::getCSlidersForObject(), getQuantityParameterOrValue(), QConservedSpeciesAnimation::getScales(), CSensItem::getVariablesPointerList(), SEDMLUtils::getXPathForObject(), CSBMLExporter::hasVolumeAssignment(), QConservedSpeciesAnimation::initialize(), QFluxModeAnimation::initialize(), QTimeCourseAnimation::initialize(), CTSSAMethod::initializeIntegrationsParameter(), CLsodaMethod::initializeParameter(), CScanTask::initSubtask(), CQSpecieDM::insertRows(), CSBMLExporter::isModelSBMLCompatible(), CSlider::isValid(), CQMoietiesTaskResult::load(), CSteadyStateProblem::load(), CQBrowserPaneDM::load(), CTrajectoryProblem::load(), FunctionWidget1::loadParameterTable(), main(), stress_test::normalizeAndSimplifyExpressions(), CQPlotDM::removeRows(), CQReactionDM::removeRows(), CQFunctionDM::removeRows(), CQEventDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), CQSpecieDM::removeRows(), CSBMLExporter::replace_local_parameters(), CSBMLExporter::replaceSpeciesReferences(), CSBMLExporter::restore_local_parameters(), CQFittingWidget::runTask(), save_cps_model_to_stream(), ReactionsWidget1::saveToReaction(), CQReactionDM::setEquation(), CSlider::setSliderObject(), CQCrossSectionTaskWidget::showUnits(), CQTrajectoryWidget::showUnits(), CQPlotsWidget::slotBtnActivateAllClicked(), CQPlotsWidget::slotBtnDeactivateAllClicked(), ReactionsWidget1::slotBtnDelete(), CQCompartment::slotBtnDelete(), CQModelValue::slotBtnDelete(), CQEventWidget1::slotBtnDelete(), ReactionsWidget1::slotBtnNew(), CQSpeciesDetail::slotBtnNew(), CQLayoutsWidget::slotBtnNewClicked(), CQPlotsWidget::slotDoubleClicked(), CQReactionsWidget::slotDoubleClicked(), CQReportsWidget::slotDoubleClicked(), CQCompartmentsWidget::slotDoubleClicked(), CQEventsWidget::slotDoubleClicked(), CQGlobalQuantitiesWidget::slotDoubleClicked(), CQSpeciesWidget::slotDoubleClicked(), CQFittingWidget::taskFinishedEvent(), test000053::test1_bug1000(), test000053::test2_bug1000(), test000053::test3_bug1000(), test000053::test4_bug1000(), test000053::test5_bug1000(), test000054::test_bug1002(), test000055::test_bug1004(), test000057::test_bug1006(), test000058::test_bug1025_1(), test000058::test_bug1025_10(), test000058::test_bug1025_2(), test000058::test_bug1025_3(), test000058::test_bug1025_4(), test000058::test_bug1025_5(), test000058::test_bug1025_6(), test000058::test_bug1025_7(), test000058::test_bug1025_8(), test000058::test_bug1025_9(), test000076::test_bug1035_1(), test000076::test_bug1035_2(), test000076::test_bug1035_3(), test000067::test_bug1060(), test000068::test_bug1068(), test000069::test_bug1069(), test000071::test_bug1085(), test000073::test_bug1087(), test000081::test_bug1205(), test000089::test_bug1412(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000099::test_bug1675(), test000103::test_bug1743_l2(), test000103::test_bug1743_l3(), test000049::test_bug894(), test000050::test_bug894(), test000048::test_bug919(), test000051::test_bug988(), test000052::test_bug988(), test000060::test_bug_1026(), test000061::test_bug_1044(), test000047::test_delay(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000063::test_events_1(), test000082::test_export_delayAssignment_1(), test000082::test_export_delayAssignment_2(), test000082::test_export_delayAssignment_3(), test000082::test_export_delayAssignment_4(), test000082::test_export_delayAssignment_5(), test000082::test_export_delayAssignment_6(), test000077::test_export_dimensionless(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000087::test_export_reaction_flux_reference_1(), test000087::test_export_reaction_flux_reference_2(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_8(), test000021::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000032::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000035::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000040::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000088::test_import_assignment_without_expression(), test000086::test_import_compartment_units_1(), test000084::test_import_compartment_units_1(), test000083::test_import_compartment_units_1(), test000085::test_import_compartment_units_1(), test000086::test_import_compartment_units_10(), test000083::test_import_compartment_units_10(), test000084::test_import_compartment_units_10(), test000085::test_import_compartment_units_10(), test000086::test_import_compartment_units_11(), test000083::test_import_compartment_units_11(), test000084::test_import_compartment_units_11(), test000085::test_import_compartment_units_11(), test000083::test_import_compartment_units_12(), test000085::test_import_compartment_units_12(), test000084::test_import_compartment_units_12(), test000083::test_import_compartment_units_13(), test000085::test_import_compartment_units_13(), test000084::test_import_compartment_units_13(), test000083::test_import_compartment_units_14(), test000085::test_import_compartment_units_14(), test000084::test_import_compartment_units_14(), test000084::test_import_compartment_units_15(), test000085::test_import_compartment_units_15(), test000083::test_import_compartment_units_15(), test000083::test_import_compartment_units_16(), test000085::test_import_compartment_units_16(), test000084::test_import_compartment_units_16(), test000083::test_import_compartment_units_17(), test000084::test_import_compartment_units_17(), test000085::test_import_compartment_units_17(), test000083::test_import_compartment_units_18(), test000085::test_import_compartment_units_18(), test000084::test_import_compartment_units_18(), test000084::test_import_compartment_units_19(), test000085::test_import_compartment_units_19(), test000083::test_import_compartment_units_19(), test000086::test_import_compartment_units_2(), test000084::test_import_compartment_units_2(), test000085::test_import_compartment_units_2(), test000083::test_import_compartment_units_2(), test000083::test_import_compartment_units_20(), test000084::test_import_compartment_units_20(), test000085::test_import_compartment_units_20(), test000083::test_import_compartment_units_21(), test000084::test_import_compartment_units_21(), test000085::test_import_compartment_units_21(), test000086::test_import_compartment_units_3(), test000083::test_import_compartment_units_3(), test000085::test_import_compartment_units_3(), test000084::test_import_compartment_units_3(), test000086::test_import_compartment_units_4(), test000085::test_import_compartment_units_4(), test000084::test_import_compartment_units_4(), test000083::test_import_compartment_units_4(), test000086::test_import_compartment_units_5(), test000085::test_import_compartment_units_5(), test000084::test_import_compartment_units_5(), test000083::test_import_compartment_units_5(), test000086::test_import_compartment_units_6(), test000085::test_import_compartment_units_6(), test000084::test_import_compartment_units_6(), test000083::test_import_compartment_units_6(), test000086::test_import_compartment_units_7(), test000084::test_import_compartment_units_7(), test000083::test_import_compartment_units_7(), test000085::test_import_compartment_units_7(), test000086::test_import_compartment_units_8(), test000084::test_import_compartment_units_8(), test000085::test_import_compartment_units_8(), test000083::test_import_compartment_units_8(), test000086::test_import_compartment_units_9(), test000084::test_import_compartment_units_9(), test000083::test_import_compartment_units_9(), test000085::test_import_compartment_units_9(), test000082::test_import_delayAssignment_1(), test000082::test_import_delayAssignment_2(), test000082::test_import_delayAssignment_3(), test000082::test_import_delayAssignment_4(), test000082::test_import_delayAssignment_5(), test000082::test_import_delayAssignment_6(), test000082::test_import_delayAssignment_7(), test000082::test_import_delayAssignment_8(), test000077::test_import_dimensionless_1(), test000077::test_import_dimensionless_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000088::test_import_eventassignment_without_expression(), test000079::test_import_fast(), test000088::test_import_initialassignment_without_expression(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), test000098::test_import_notes(), test000087::test_import_reaction_flux_reference_2(), test000066::test_import_reaction_with_constant_flux(), test000066::test_import_reaction_with_constant_flux_function(), test000066::test_import_reaction_with_constant_flux_function_global_parameter(), test000066::test_import_reaction_with_constant_flux_global_parameter(), test000066::test_import_reaction_with_constant_flux_reversible(), test000066::test_import_reaction_with_constant_flux_reversible_function(), test000066::test_import_reaction_with_constant_flux_reversible_function_global_parameter(), test000066::test_import_reaction_with_constant_flux_reversible_global_parameter(), test000065::test_import_reaction_with_unsuitable_kinetic_1(), test000065::test_import_reaction_with_unsuitable_kinetic_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000062::test_kineticlaw_without_math(), test000078::test_l2v4_import_unordered_functions(), test000080::test_mass_action_recognition_bug(), test000092::test_miriam_export_1(), test000092::test_miriam_export_2(), test000092::test_miriam_export_3(), test000092::test_miriam_export_4(), test000092::test_miriam_export_5(), test000092::test_miriam_export_6(), test000092::test_miriam_export_7(), test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000092::test_miriam_import_1(), test000094::test_notrequired_package(), test000087::test_simulate_reaction_flux_reference_1(), test000045::test_stoichiometricExpression(), test000046::test_stoichiometricExpression(), test000044::test_stoichiometricExpression(), test000059::test_unique_id_1(), test000059::test_unique_id_10(), test000059::test_unique_id_11(), test000059::test_unique_id_12(), test000059::test_unique_id_13(), test000059::test_unique_id_14(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_2(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), test000059::test_unique_id_21_2(), test000059::test_unique_id_22(), test000059::test_unique_id_3(), test000059::test_unique_id_4(), test000059::test_unique_id_5(), test000059::test_unique_id_6(), test000059::test_unique_id_7(), test000059::test_unique_id_8(), test000059::test_unique_id_9(), CQGLLayoutPainter::update(), and validate().
 {
   if (mData.isValid())
     return mData.pModel;
   return mOldData.pModel;
 }
const CModel * CCopasiDataModel::getModel () const
Definition at line 1404 of file CCopasiDataModel.cpp.
References mData, and CCopasiDataModel::CData::pModel.
 {return mData.pModel;}
const COutputDefinitionVector * CCopasiDataModel::getPlotDefinitionList () const
Definition at line 1783 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pPlotDefinitionList.
Referenced by CQPlotSubwidget::addPlot(), CQPlotSubwidget::copyPlot(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), COutputAssistant::createPlot(), CSEDMLExporter::createSEDMLDocument(), CQPlotSubwidget::deletePlot(), CQBrowserPaneDM::load(), Arguments::prepareModel(), CQPlotDM::removeRows(), save_cps_model_to_stream(), CQPlotsWidget::slotBtnActivateAllClicked(), CQPlotsWidget::slotBtnDeactivateAllClicked(), and CQPlotsWidget::slotDoubleClicked().
 {
   if (mData.isValid())
     return mData.pPlotDefinitionList;
   return mOldData.pPlotDefinitionList;
 }
COutputDefinitionVector * CCopasiDataModel::getPlotDefinitionList ()
Definition at line 1791 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pPlotDefinitionList.
 {
   if (mData.isValid())
     return mData.pPlotDefinitionList;
   return mOldData.pPlotDefinitionList;
 }
const std::string & CCopasiDataModel::getReferenceDirectory () const
Definition at line 1952 of file CCopasiDataModel.cpp.
References mData, and CCopasiDataModel::CData::mReferenceDir.
Referenced by CQNewMainWindow::CQNewMainWindow(), and SBMLImporter::parseSBML().
 {
   return mData.mReferenceDir;
 }
const CReportDefinitionVector * CCopasiDataModel::getReportDefinitionList () const
Definition at line 1767 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pReportDefinitionList.
Referenced by CQReportDefinition::btnCopyReportClicked(), CQReportDefinition::btnDeleteReportClicked(), COutputAssistant::createTable(), SEDMLImporter::importTasks(), CQBrowserPaneDM::load(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQReportDM::removeRows(), save_cps_model_to_stream(), CQReportsWidget::slotDoubleClicked(), and test000087::test_simulate_reaction_flux_reference_1().
 {
   if (mData.isValid())
     return mData.pReportDefinitionList;
   return mOldData.pReportDefinitionList;
 }
CReportDefinitionVector * CCopasiDataModel::getReportDefinitionList ()
Definition at line 1775 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pReportDefinitionList.
 {
   if (mData.isValid())
     return mData.pReportDefinitionList;
   return mOldData.pReportDefinitionList;
 }
const std::string & CCopasiDataModel::getSBMLFileName () const
Definition at line 1851 of file CCopasiDataModel.cpp.
References mData, and CCopasiDataModel::CData::mSBMLFileName.
Referenced by CCopasiXML::saveSBMLReference().
 {return mData.mSBMLFileName;}
CCopasiVectorN< CCopasiTask > * CCopasiDataModel::getTaskList ()
Definition at line 1415 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pTaskList.
Referenced by CQNewMainWindow::checkForElementaryModesSlot(), COutputAssistant::createDefaultOutput(), CSEDMLExporter::createScanTask(), CSEDMLExporter::createSteadyStateTask(), CSEDMLExporter::createTasks(), CSEDMLExporter::createTimeCourseTask(), CQNewMainWindow::elementaryModeTriggeredSlot(), CFitProblem::elevateChildren(), CQFittingResult::enterProtected(), QFluxModeAnimation::getScales(), QTimeCourseAnimation::getScales(), CMCAProblem::getSubTask(), SEDMLImporter::importTasks(), CFitProblem::initialize(), QFluxModeAnimation::initialize(), CSensMethod::initialize(), CNewtonMethod::initialize(), QTimeCourseAnimation::initialize(), CScanTask::initSubtask(), CQBrowserPaneDM::load(), main(), CQSimpleSelectionTree::populateTree(), Arguments::prepareModel(), save_cps_model_to_stream(), CLNAProblem::setSteadyStateRequested(), CMCAProblem::setSteadyStateRequested(), test000087::test_simulate_reaction_flux_reference_1(), SEDMLImporter::updateCopasiTaskForSimulation(), and validate().
 {
   if (mData.isValid())
     return mData.pTaskList;
   return mOldData.pTaskList;
 }
const CCopasiVectorN< CCopasiTask > * CCopasiDataModel::getTaskList () const
Definition at line 1423 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::isValid(), mData, mOldData, and CCopasiDataModel::CData::pTaskList.
 {
   if (mData.isValid())
     return mData.pTaskList;
   return mOldData.pTaskList;
 }
bool CCopasiDataModel::importSBML (const std::string & fileName, CProcessReport * pImportHandler = NULL, const bool & deleteOldData = true)
Definition at line 603 of file CCopasiDataModel.cpp.
References CCopasiContainer::add(), CDirEntry::baseName(), CCopasiMessage::clearDeque(), commonAfterLoad(), SBMLImporter::deleteCopasiModel(), CDirEntry::dirName(), CDirEntry::fileName(), CLocaleString::fromUtf8(), CCopasiRootContainer::getFunctionList(), CCopasiTask::getProblem(), COptions::getValue(), CDirEntry::isRelativePath(), CDirEntry::makePathAbsolute(), CCopasiDataModel::CData::mCopasi2SBMLMap, mData, CCopasiDataModel::CData::mFileType, CCopasiDataModel::CData::mReferenceDir, mRenameHandler, CCopasiDataModel::CData::mSaveFileName, CCopasiDataModel::CData::mSBMLFileName, CDirEntry::normalize(), CCopasiDataModel::CData::pCurrentSBMLDocument, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, popData(), CCopasiDataModel::CData::pTaskList, pushData(), SBMLImporter::readSBML(), SBMLImporter::restoreFunctionDB(), SBML, CDirEntry::Separator, CDataModelRenameHandler::setEnabled(), SBMLImporter::setImportCOPASIMIRIAM(), SBMLImporter::setImportHandler(), and CDirEntry::suffix().
Referenced by Arguments::handleCommandLine(), main(), and stress_test::normalizeMath().
 {
   // During load no objects will be renamed;
   mRenameHandler.setEnabled(false);
   CCopasiMessage::clearDeque();
   std::string PWD;
   COptions::getValue("PWD", PWD);
   std::string FileName = fileName;
   if (CDirEntry::isRelativePath(FileName) &&
       !CDirEntry::makePathAbsolute(FileName, PWD))
     FileName = CDirEntry::fileName(FileName);
   std::ifstream File(CLocaleString::fromUtf8(FileName).c_str());
   SBMLImporter importer;
   // Right now we always import the COPASI MIRIAM annotation if it is there.
   // Later this will be settable by the user in the preferences dialog
   importer.setImportCOPASIMIRIAM(true);
   importer.setImportHandler(pImportHandler);
   CModel* pModel = NULL;
   SBMLDocument * pSBMLDocument = NULL;
   std::map<CCopasiObject*, SBase*> Copasi2SBMLMap;
   CListOfLayouts * pLol = NULL;
   pushData();
   try
     {
       // store the file name and reference dir, so the importer can use it
       mData.mSBMLFileName = CDirEntry::normalize(FileName);
       mData.mReferenceDir = CDirEntry::dirName(mData.mSBMLFileName);
       pModel = importer.readSBML(FileName, CCopasiRootContainer::getFunctionList(),
                                  pSBMLDocument, Copasi2SBMLMap, pLol, this);
     }
   catch (CCopasiException & except)
     {
       importer.restoreFunctionDB();
       importer.deleteCopasiModel();
       popData();
       mRenameHandler.setEnabled(true);
       throw except;
     }
   if (pModel == NULL)
     {
       importer.restoreFunctionDB();
       importer.deleteCopasiModel();
       popData();
       mRenameHandler.setEnabled(true);
       return false;
     }
   if (pModel != NULL)
     {
       mData.pModel = pModel;
       add(mData.pModel, true);
     }
   if (pLol != NULL)
     {
       mData.pListOfLayouts = pLol;
       add(mData.pListOfLayouts, true);
     }
   mData.pCurrentSBMLDocument = pSBMLDocument;
   mData.mCopasi2SBMLMap = Copasi2SBMLMap;
   mData.mFileType = SBML;
   commonAfterLoad(pImportHandler, deleteOldData);
   // when importing from SBML, allow continuation on simultaneous events.
   static_cast<CTrajectoryProblem *>(
     static_cast<CTrajectoryTask *>((*mData.pTaskList)["Time-Course"])->getProblem()
   )->setContinueSimultaneousEvents(true);
   mData.mSaveFileName = CDirEntry::dirName(FileName)
                         + CDirEntry::Separator
                         + CDirEntry::baseName(FileName);
   std::string Suffix = CDirEntry::suffix(FileName);
   if (strcasecmp(Suffix.c_str(), ".xml") != 0)
     mData.mSaveFileName += Suffix;
   mData.mSaveFileName += ".cps";
   mData.mSaveFileName = CDirEntry::normalize(mData.mSaveFileName);
   // store the reference directory
   mData.mReferenceDir = CDirEntry::dirName(mData.mSaveFileName);
   mData.mSBMLFileName = CDirEntry::normalize(FileName);
   mRenameHandler.setEnabled(true);
   return true;
 }
bool CCopasiDataModel::importSBMLFromString (const std::string & sbmlDocumentText, CProcessReport * pImportHandler = NULL, const bool & deleteOldData = true)
Definition at line 526 of file CCopasiDataModel.cpp.
References CCopasiContainer::add(), CCopasiMessage::clearDeque(), commonAfterLoad(), SBMLImporter::deleteCopasiModel(), CCopasiRootContainer::getFunctionList(), CCopasiTask::getProblem(), CCopasiDataModel::CData::mCopasi2SBMLMap, mData, CCopasiDataModel::CData::mFileType, mRenameHandler, SBMLImporter::parseSBML(), CCopasiDataModel::CData::pCurrentSBMLDocument, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, popData(), CCopasiDataModel::CData::pTaskList, pushData(), SBMLImporter::restoreFunctionDB(), SBML, CDataModelRenameHandler::setEnabled(), SBMLImporter::setImportCOPASIMIRIAM(), and SBMLImporter::setImportHandler().
Referenced by test000053::test1_bug1000(), test000053::test2_bug1000(), test000053::test3_bug1000(), test000053::test4_bug1000(), test000053::test5_bug1000(), test000055::test_bug1004(), test000056::test_bug1005(), test000057::test_bug1006(), test000058::test_bug1025_1(), test000058::test_bug1025_2(), test000058::test_bug1025_3(), test000058::test_bug1025_4(), test000058::test_bug1025_5(), test000068::test_bug1068(), test000070::test_bug1084(), test000071::test_bug1085(), test000072::test_bug1086(), test000073::test_bug1087(), test000074::test_bug1088(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000099::test_bug1675(), test000101::test_bug1740(), test000102::test_bug1741(), test000103::test_bug1743_l2(), test000103::test_bug1743_l3(), test000104::test_bug1744(), test000052::test_bug988(), test000060::test_bug_1026(), test000047::test_delay(), test000090::test_delay_in_function(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000063::test_events_1(), test000032::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000035::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000040::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000021::test_hasOnlySubstanceUnits(), test000088::test_import_assignment_without_expression(), test000086::test_import_compartment_units_1(), test000084::test_import_compartment_units_1(), test000085::test_import_compartment_units_1(), test000083::test_import_compartment_units_1(), test000086::test_import_compartment_units_10(), test000084::test_import_compartment_units_10(), test000085::test_import_compartment_units_10(), test000083::test_import_compartment_units_10(), test000086::test_import_compartment_units_11(), test000084::test_import_compartment_units_11(), test000085::test_import_compartment_units_11(), test000083::test_import_compartment_units_11(), test000084::test_import_compartment_units_12(), test000085::test_import_compartment_units_12(), test000083::test_import_compartment_units_12(), test000084::test_import_compartment_units_13(), test000085::test_import_compartment_units_13(), test000083::test_import_compartment_units_13(), test000084::test_import_compartment_units_14(), test000085::test_import_compartment_units_14(), test000083::test_import_compartment_units_14(), test000084::test_import_compartment_units_15(), test000085::test_import_compartment_units_15(), test000083::test_import_compartment_units_15(), test000085::test_import_compartment_units_16(), test000084::test_import_compartment_units_16(), test000083::test_import_compartment_units_16(), test000084::test_import_compartment_units_17(), test000085::test_import_compartment_units_17(), test000083::test_import_compartment_units_17(), test000084::test_import_compartment_units_18(), test000085::test_import_compartment_units_18(), test000083::test_import_compartment_units_18(), test000083::test_import_compartment_units_19(), test000084::test_import_compartment_units_19(), test000085::test_import_compartment_units_19(), test000086::test_import_compartment_units_2(), test000084::test_import_compartment_units_2(), test000085::test_import_compartment_units_2(), test000083::test_import_compartment_units_2(), test000083::test_import_compartment_units_20(), test000084::test_import_compartment_units_20(), test000085::test_import_compartment_units_20(), test000083::test_import_compartment_units_21(), test000085::test_import_compartment_units_21(), test000084::test_import_compartment_units_21(), test000086::test_import_compartment_units_3(), test000084::test_import_compartment_units_3(), test000085::test_import_compartment_units_3(), test000083::test_import_compartment_units_3(), test000086::test_import_compartment_units_4(), test000084::test_import_compartment_units_4(), test000085::test_import_compartment_units_4(), test000083::test_import_compartment_units_4(), test000086::test_import_compartment_units_5(), test000084::test_import_compartment_units_5(), test000085::test_import_compartment_units_5(), test000083::test_import_compartment_units_5(), test000086::test_import_compartment_units_6(), test000084::test_import_compartment_units_6(), test000083::test_import_compartment_units_6(), test000085::test_import_compartment_units_6(), test000086::test_import_compartment_units_7(), test000084::test_import_compartment_units_7(), test000085::test_import_compartment_units_7(), test000083::test_import_compartment_units_7(), test000086::test_import_compartment_units_8(), test000084::test_import_compartment_units_8(), test000085::test_import_compartment_units_8(), test000083::test_import_compartment_units_8(), test000086::test_import_compartment_units_9(), test000085::test_import_compartment_units_9(), test000084::test_import_compartment_units_9(), test000083::test_import_compartment_units_9(), test000082::test_import_delayAssignment_1(), test000082::test_import_delayAssignment_2(), test000082::test_import_delayAssignment_3(), test000082::test_import_delayAssignment_4(), test000082::test_import_delayAssignment_5(), test000082::test_import_delayAssignment_6(), test000082::test_import_delayAssignment_7(), test000082::test_import_delayAssignment_8(), test000077::test_import_dimensionless_1(), test000077::test_import_dimensionless_2(), test000077::test_import_dimensionless_3(), test000077::test_import_dimensionless_4(), test000077::test_import_dimensionless_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000088::test_import_eventassignment_without_expression(), test000079::test_import_fast(), test000097::test_import_global_render_information(), test000088::test_import_initialassignment_without_expression(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), test000097::test_import_local_render_information(), test000098::test_import_notes(), test000087::test_import_reaction_flux_reference_1(), test000087::test_import_reaction_flux_reference_2(), test000087::test_import_reaction_flux_reference_3(), test000066::test_import_reaction_with_constant_flux(), test000066::test_import_reaction_with_constant_flux_function(), test000066::test_import_reaction_with_constant_flux_function_global_parameter(), test000066::test_import_reaction_with_constant_flux_global_parameter(), test000066::test_import_reaction_with_constant_flux_reversible(), test000066::test_import_reaction_with_constant_flux_reversible_function(), test000066::test_import_reaction_with_constant_flux_reversible_function_global_parameter(), test000066::test_import_reaction_with_constant_flux_reversible_global_parameter(), test000065::test_import_reaction_with_unsuitable_kinetic_1(), test000065::test_import_reaction_with_unsuitable_kinetic_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000097::test_importexport_global_render_information(), test000097::test_importexport_local_render_information(), test000097::test_importwrite_global_render_information(), test000097::test_importwrite_local_render_information(), test000062::test_kineticlaw_without_math(), test000078::test_l2v4_import_unordered_functions(), test000080::test_mass_action_recognition_bug(), test000092::test_miriam_export_1(), test000092::test_miriam_export_2(), test000092::test_miriam_export_3(), test000092::test_miriam_export_4(), test000092::test_miriam_export_5(), test000092::test_miriam_export_6(), test000092::test_miriam_export_7(), test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000092::test_miriam_import_1(), test000094::test_notrequired_package(), test000094::test_required_package(), test000087::test_simulate_reaction_flux_reference_1(), test000044::test_stoichiometricExpression(), test000046::test_stoichiometricExpression(), test000045::test_stoichiometricExpression(), test000059::test_unique_id_1(), test000059::test_unique_id_10(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_2(), test000059::test_unique_id_20(), test000059::test_unique_id_22(), test000059::test_unique_id_3(), test000059::test_unique_id_4(), test000059::test_unique_id_5(), test000059::test_unique_id_6(), test000059::test_unique_id_7(), test000059::test_unique_id_8(), test000059::test_unique_id_9(), and Copasi2SBMLTranslator::translate().
 {
   // During load no objects will be renamed;
   mRenameHandler.setEnabled(false);
   pushData();
   CCopasiMessage::clearDeque();
   SBMLImporter importer;
   // Right now we always import the COPASI MIRIAM annotation if it is there.
   // Later this will be configurable by the user in the preferences dialog
   importer.setImportCOPASIMIRIAM(true);
   importer.setImportHandler(pImportHandler);
   //mCopasi2SBMLMap.clear();
   CModel* pModel = NULL;
   SBMLDocument * pSBMLDocument = NULL;
   std::map<CCopasiObject*, SBase*> Copasi2SBMLMap;
   CListOfLayouts * pLol = NULL; //
   try
     {
       pModel = importer.parseSBML(sbmlDocumentText, CCopasiRootContainer::getFunctionList(),
                                   pSBMLDocument, Copasi2SBMLMap, pLol, this);
     }
   catch (CCopasiException & except)
     {
       importer.restoreFunctionDB();
       importer.deleteCopasiModel();
       popData();
       mRenameHandler.setEnabled(true);
       throw except;
     }
   if (pModel == NULL)
     {
       importer.restoreFunctionDB();
       importer.deleteCopasiModel();
       popData();
       mRenameHandler.setEnabled(true);
       return false;
     }
   if (pModel != NULL)
     {
       mData.pModel = pModel;
       add(mData.pModel, true);
     }
   if (pLol != NULL)
     {
       mData.pListOfLayouts = pLol;
       add(mData.pListOfLayouts, true);
     }
   mData.pCurrentSBMLDocument = pSBMLDocument;
   mData.mCopasi2SBMLMap = Copasi2SBMLMap;
   mData.mFileType = SBML;
   commonAfterLoad(pImportHandler, deleteOldData);
   // when importing from SBML, allow continuation on simultaneous events.
   static_cast<CTrajectoryProblem *>(
     static_cast<CTrajectoryTask *>((*mData.pTaskList)["Time-Course"])->getProblem()
   )->setContinueSimultaneousEvents(true);
   mRenameHandler.setEnabled(true);
   return true;
 }
bool CCopasiDataModel::isChanged () const
Definition at line 1826 of file CCopasiDataModel.cpp.
References CCopasiDataModel::CData::mChanged, and mData.
 {return mData.mChanged;}
bool CCopasiDataModel::loadModel (std::istream & in, const std::string & pwd, CProcessReport * pProcessReport, const bool & deleteOldData = true)
Definition at line 158 of file CCopasiDataModel.cpp.
References CCopasiContainer::add(), CCopasiMessage::clearDeque(), commonAfterLoad(), CopasiML, CCopasiMessage::ERROR, CCopasiXML::freeGUI(), CCopasiXML::freeLayoutList(), CCopasiXML::freeModel(), CCopasiXML::freePlotList(), CCopasiXML::freeReportList(), CCopasiXML::freeTaskList(), Gepasi, CCopasiRootContainer::getFunctionList(), CCopasiXML::getLayoutList(), CCopasiXML::getModel(), CCopasiXML::getPlotList(), CCopasiXML::getReportList(), CCopasiXML::getTaskList(), CReadConfig::getVersion(), CCopasiXML::load(), CModel::load(), CTrajectoryTask::load(), CSteadyStateTask::load(), MCXML, mData, CCopasiDataModel::CData::mFileType, mRenameHandler, CCopasiDataModel::CData::mWithGUI, newModel(), CCopasiDataModel::CData::pGUI, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, popData(), CCopasiDataModel::CData::pPlotDefinitionList, CCopasiDataModel::CData::pReportDefinitionList, CCopasiDataModel::CData::pTaskList, pushData(), CCopasiXML::setDatamodel(), CDataModelRenameHandler::setEnabled(), CCopasiXML::setFunctionList(), and CCopasiXML::setGUI().
Referenced by Arguments::handleCommandLine(), load_cps_model_from_stream(), loadModel(), main(), Arguments::prepareModel(), Copasi2SBMLTranslator::translateFileToSBML(), and Copasi2SBMLTranslator::translateToSBML().
 {
   // During load no objects will be renamed;
   mRenameHandler.setEnabled(false);
   CCopasiMessage::clearDeque();
   std::string Line;
   in >> Line;
   if (!Line.compare(0, 8, "Version="))
     {
       in.seekg(0, std::ios_base::beg);
       CReadConfig inbuf(in);
       if (inbuf.getVersion() >= "4")
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          "Can't handle Gepasi Files with Version>=4.");
           mRenameHandler.setEnabled(true);
           return false;
         }
       newModel(NULL, deleteOldData);
       mData.mFileType = Gepasi;
       if (mData.pModel->load(inbuf))
         {
           popData();
           mRenameHandler.setEnabled(true);
           return false;
         }
       static_cast<CTrajectoryTask *>((*mData.pTaskList)["Time-Course"])->load(inbuf);
       static_cast<CSteadyStateTask *>((*mData.pTaskList)["Steady-State"])->load(inbuf);
     }
   else if (!Line.find("<?xml") != std::string::npos)
     {
       in.seekg(0, std::ios_base::beg);
       pushData();
       mData.mFileType = CopasiML;
       CCopasiXML XML;
       XML.setFunctionList(&CCopasiRootContainer::getFunctionList()->loadedFunctions());
       XML.setDatamodel(this);
       SCopasiXMLGUI *pGUI = NULL;
       if (mData.mWithGUI)
         {
           pGUI = new SCopasiXMLGUI("GUI", this);
           XML.setGUI(pGUI);
         }
       try
         {
           if (!XML.load(in, pwd))
             {
               XML.freeModel();
               XML.freeTaskList();
               XML.freeReportList();
               XML.freePlotList();
               XML.freeGUI();
               XML.freeLayoutList();
               // restore the OldData
               popData();
               mRenameHandler.setEnabled(true);
               return false;
             }
         }
       catch (...)
         {
           XML.freeModel();
           XML.freeTaskList();
           XML.freeReportList();
           XML.freePlotList();
           XML.freeGUI();
           XML.freeLayoutList();
           // restore the OldData
           popData();
           // rethrow the exception so the program flow should still be
           // the same as before
           mRenameHandler.setEnabled(true);
           throw;
         }
       if (XML.getModel() != NULL)
         {
           mData.pModel = XML.getModel();
           add(mData.pModel, true);
         }
       if (XML.getTaskList() != NULL)
         {
           mData.pTaskList = XML.getTaskList();
           add(mData.pTaskList, true);
         }
       if (XML.getReportList() != NULL)
         {
           mData.pReportDefinitionList = XML.getReportList();
           add(mData.pReportDefinitionList, true);
         }
       if (XML.getPlotList() != NULL)
         {
           mData.pPlotDefinitionList = XML.getPlotList();
           add(mData.pPlotDefinitionList, true);
         }
       if (XML.getLayoutList() != NULL)
         {
           mData.pListOfLayouts = XML.getLayoutList();
           add(mData.pListOfLayouts, true);
         }
       if (mData.mWithGUI)
         {
           mData.pGUI = pGUI;
         }
     }
   else
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCXML + 13);
       mRenameHandler.setEnabled(true);
       return false;
     }
   commonAfterLoad(pProcessReport, deleteOldData);
   mRenameHandler.setEnabled(true);
   return true;
 }
bool CCopasiDataModel::loadModel (const std::string & fileName, CProcessReport * pProcessReport, const bool & deleteOldData = true)
Definition at line 303 of file CCopasiDataModel.cpp.
References CDirEntry::baseName(), CopasiML, CDirEntry::dirName(), fatalError, CDirEntry::fileName(), CLocaleString::fromUtf8(), Gepasi, COptions::getValue(), CDirEntry::isRelativePath(), loadModel(), CDirEntry::makePathAbsolute(), mData, CCopasiDataModel::CData::mFileType, CCopasiDataModel::CData::mReferenceDir, CCopasiDataModel::CData::mSaveFileName, CDirEntry::normalize(), CCopasiMessage::RAW, CDirEntry::Separator, and CDirEntry::suffix().
 {
   std::string PWD;
   COptions::getValue("PWD", PWD);
   std::string FileName = fileName;
   if (CDirEntry::isRelativePath(FileName) &&
       !CDirEntry::makePathAbsolute(FileName, PWD))
     FileName = CDirEntry::fileName(FileName);
   PWD = CDirEntry::dirName(FileName);
 #ifdef WIN32
   std::ifstream File(CLocaleString::fromUtf8(FileName).c_str(), std::ios_base::binary);
 #else
   std::ifstream File(CLocaleString::fromUtf8(FileName).c_str());
 #endif
   if (File.fail())
     {
       CCopasiMessage Message(CCopasiMessage::RAW,
                              "File error when opening '%s'.",
                              FileName.c_str());
       return false;
     }
   if (!loadModel(File, PWD, pProcessReport, deleteOldData))
     {
       return false;
     }
   switch (mData.mFileType)
     {
       case CopasiML:
         mData.mSaveFileName = CDirEntry::normalize(FileName);
         // we have to store the reference directory
         mData.mReferenceDir = CDirEntry::dirName(mData.mSaveFileName);
         break;
       case Gepasi:
         mData.mSaveFileName = CDirEntry::dirName(FileName)
                               + CDirEntry::Separator
                               + CDirEntry::baseName(FileName);
         {
           std::string Suffix = CDirEntry::suffix(FileName);
           if (strcasecmp(Suffix.c_str(), ".gps") != 0)
             mData.mSaveFileName += Suffix;
         }
         mData.mSaveFileName += ".cps";
         mData.mSaveFileName = CDirEntry::normalize(mData.mSaveFileName);
         // we have to store the reference directory
         mData.mReferenceDir = CDirEntry::dirName(mData.mSaveFileName);
         break;
       default:
         fatalError();
         break;
     }
   return true;
 }
bool CCopasiDataModel::newModel (CProcessReport * pProcessReport, const bool & deleteOldData)
Definition at line 515 of file CCopasiDataModel.cpp.
References commonAfterLoad(), and pushData().
Referenced by CCopasiDataModel(), loadModel(), test000068::test_bug1068(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000103::test_bug1743_l2(), and test000103::test_bug1743_l3().
 {
   //deal with the CModel
   pushData();
   commonAfterLoad(pProcessReport, deleteOldData);
   return true;
 }
CObjectInterface * CCopasiDataModel::ObjectFromCN (const std::vector< CCopasiContainer * > & listOfContainer, const CCopasiObjectName & objName) const
Retrieve the object with the given CN
Parameters
const std::vector< CCopasiContainer * > &listOfContainer
const CCopasiObjectName& objName
Returns
CObjectInterface * pObject
Definition at line 1890 of file CCopasiDataModel.cpp.
References CCopasiObject::getCN(), CCopasiRootContainer::getFunctionList(), CCopasiContainer::getObject(), and CCopasiObjectName::getRemainder().
Referenced by CExpression::getNodeObject(), CMathContainer::getObject(), and ObjectFromName().
 {
   const CObjectInterface * pObject = NULL;
   const CCopasiContainer* pContainer;
   CCopasiObjectName ContainerName;
   size_t containerIndex;
   std::string::size_type pos;
   //favor to search the list of container first
   for (containerIndex = 0;
        containerIndex < listOfContainer.size() && !pObject;
        containerIndex++)
     {
       pContainer = listOfContainer[containerIndex];
       if (pContainer == NULL)
         {
           continue;
         }
       ContainerName = pContainer->getCN();
       while (ContainerName.getRemainder() != "")
         {
           ContainerName = ContainerName.getRemainder();
         }
       if ((pos = objName.find(ContainerName)) == std::string::npos)
         continue;
       if (pos + ContainerName.length() == objName.length())
         pObject = pContainer;
       else
         pObject = pContainer->getObject(objName.substr(pos + ContainerName.length() + 1));
     }
   // If we have not found the object in the context we search the whole data model.
   if (pObject == NULL)
     {
       pObject = getObject(objName);
     }
   // if still not found search the function database in the root container
   if (!pObject)
     pObject = CCopasiRootContainer::getFunctionList()->getObject(objName);
   return const_cast< CObjectInterface * >(pObject);
 }
CCopasiObject * CCopasiDataModel::ObjectFromName (const std::vector< CCopasiContainer * > & listOfContainer, const CCopasiObjectName & CN) const
Retrieve the data object with the given CN
Parameters
const std::vector< CCopasiContainer * > &listOfContainer
const CCopasiObjectName& CN
Returns
CCopasiObject * pObject
Definition at line 1940 of file CCopasiDataModel.cpp.
References ObjectFromCN().
Referenced by CSBMLExporter::checkForUnsupportedObjectReferences(), CTimeSeries::compile(), CExperiment::compile(), CModelParameter::compile(), CopasiPlot::compile(), CModelParameterReactionParameter::compile(), COutputHandler::compileRefresh(), contains_necessary_mass_action_elements(), SBMLImporter::doMapping(), CReport::generateObjectsFromName(), COptProblem::getSubtaskType(), CFitProblem::initialize(), COptProblem::initializeSubtaskBeforeOutput(), SBMLImporter::isConstantFlux(), SBMLImporter::isMassActionExpression(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CSlider::isValid(), CReaction::object2variable(), CReportDefinition::preCompileTable(), SBMLImporter::renameMassActionParameters(), CSBMLExporter::replace_local_parameters(), CSBMLExporter::replaceSpeciesReferences(), CSBMLExporter::restore_local_parameters(), SBMLImporter::setCorrectUsage(), CQExpressionWidget::setExpression(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000099::test_bug1675(), test000052::test_bug988(), test000047::test_delay(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000026::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000032::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000040::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000035::test_hasOnlySubstanceUnits(), test000021::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000082::test_import_delayAssignment_1(), test000082::test_import_delayAssignment_2(), test000082::test_import_delayAssignment_3(), test000082::test_import_delayAssignment_4(), test000082::test_import_delayAssignment_5(), test000082::test_import_delayAssignment_6(), test000082::test_import_delayAssignment_7(), test000082::test_import_delayAssignment_8(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), test000087::test_import_reaction_flux_reference_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000087::test_simulate_reaction_flux_reference_1(), and CModelParameter::updateModel().
 {
   // TODO CRITICAL This does not work for math as object ObjectFromCN only returns a CObjectInterface.
   return static_cast< CCopasiObject * >(ObjectFromCN(listOfContainer, objName));
 }
void CCopasiDataModel::popData () protected
Definition at line 2053 of file CCopasiDataModel.cpp.
References mData, mOldData, CCopasiDataModel::CData::mWithGUI, CCopasiDataModel::CData::pGUI, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, CCopasiDataModel::CData::pPlotDefinitionList, CCopasiDataModel::CData::pReportDefinitionList, and CCopasiDataModel::CData::pTaskList.
Referenced by importSBML(), importSBMLFromString(), and loadModel().
 {
   // Make sure the old data is valid
   assert(mOldData.pModel != NULL &&
          mOldData.pTaskList != NULL &&
          mOldData.pReportDefinitionList != NULL &&
          mOldData.pPlotDefinitionList != NULL &&
          mOldData.pListOfLayouts != NULL &&
          (mOldData.pGUI != NULL || mOldData.mWithGUI == false));
   // TODO CRITICAL We need to clean up mData to avoid memory leaks.
   mData = mOldData;
   mOldData = CData(mOldData.mWithGUI);
 }
void CCopasiDataModel::pushData () protected
Definition at line 2033 of file CCopasiDataModel.cpp.
References mData, mOldData, CCopasiDataModel::CData::mWithGUI, CCopasiDataModel::CData::pGUI, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, CCopasiDataModel::CData::pPlotDefinitionList, CCopasiDataModel::CData::pReportDefinitionList, and CCopasiDataModel::CData::pTaskList.
Referenced by importSBML(), importSBMLFromString(), loadModel(), and newModel().
 {
   bool condition = true;
 #ifdef COPASI_SEDML
   condition = mOldData.pCurrentSEDMLDocument == NULL;
 #endif
   // make sure the old data has been deleted.
   assert(mOldData.pModel == NULL &&
          mOldData.pTaskList == NULL &&
          mOldData.pReportDefinitionList == NULL &&
          mOldData.pPlotDefinitionList == NULL &&
          mOldData.pListOfLayouts == NULL &&
          mOldData.pGUI == NULL &&
          condition
         );
   mOldData = mData;
   mData = CData(mData.mWithGUI);
 }
bool CCopasiDataModel::removeLayout (const std::string & key)
Definition at line 1870 of file CCopasiDataModel.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), mData, and CCopasiDataModel::CData::pListOfLayouts.
 {
   CLayout *pLayout =
     dynamic_cast< CLayout * >(CCopasiRootContainer::getKeyFactory()->get(key));
   if (!pLayout)
     return false;
   //Check if Layout with that name exists
   size_t index =
     mData.pListOfLayouts->CCopasiVector< CLayout >::getIndex(pLayout);
   if (index == C_INVALID_INDEX)
     return false;
   mData.pListOfLayouts->CCopasiVector< CLayout >::remove(index);
   return true;
 }
void CCopasiDataModel::removeSBMLIdFromFunctions () protected
Definition at line 1859 of file CCopasiDataModel.cpp.
References CCopasiRootContainer::getFunctionList(), CFunctionDB::loadedFunctions(), and CCopasiVector< T >::size().
 {
   CFunctionDB* pFunDB = CCopasiRootContainer::getFunctionList();
   size_t i, iMax = pFunDB->loadedFunctions().size();
   for (i = 0; i < iMax; ++i)
     {
       pFunDB->loadedFunctions()[i]->setSBMLId("");
     }
 }
bool CCopasiDataModel::saveModel (const std::string & fileName, CProcessReport * pProcessReport, bool overwriteFile = false, const bool & autoSave = false)
Definition at line 372 of file CCopasiDataModel.cpp.
References changed(), CCopasiMessage::clearDeque(), CModel::compileIfNecessary(), CDirEntry::createTmpName(), CCopasiMessage::ERROR, CDirEntry::exist(), CDirEntry::fileName(), CModel::getModelParameterSet(), COptions::getValue(), CDirEntry::isRelativePath(), CDirEntry::isWritable(), CDirEntry::makePathAbsolute(), MCDirEntry, mData, CDirEntry::move(), CCopasiDataModel::CData::mSaveFileName, CDirEntry::normalize(), CCopasiDataModel::CData::pGUI, CCopasiDataModel::CData::pListOfLayouts, CCopasiDataModel::CData::pModel, CCopasiDataModel::CData::pPlotDefinitionList, CCopasiDataModel::CData::pReportDefinitionList, CCopasiDataModel::CData::pTaskList, CModelParameterGroup::refreshFromModel(), CDirEntry::remove(), CCopasiXML::setDatamodel(), CCopasiXML::setGUI(), CCopasiXML::setLayoutList(), CCopasiXML::setModel(), CCopasiXML::setPlotList(), CCopasiXML::setReportList(), and CCopasiXML::setTaskList().
Referenced by autoSave(), main(), Arguments::prepareModel(), and Copasi2SBMLTranslator::translate().
 {
   CCopasiMessage::clearDeque();
   std::string FileName = (fileName != "") ? fileName : mData.mSaveFileName;
   std::string PWD;
   COptions::getValue("PWD", PWD);
   if (CDirEntry::isRelativePath(FileName) &&
       !CDirEntry::makePathAbsolute(FileName, PWD))
     FileName = CDirEntry::fileName(FileName);
   if (CDirEntry::exist(FileName))
     {
       if (!overwriteFile)
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          MCDirEntry + 1,
                          FileName.c_str());
           return false;
         }
       if (!CDirEntry::isWritable(FileName))
         {
           CCopasiMessage(CCopasiMessage::ERROR,
                          MCDirEntry + 2,
                          FileName.c_str());
           return false;
         }
     }
   try
     {
       // We do not care whether the model compiles or not
       // We just save as much as we can
       mData.pModel->compileIfNecessary(pProcessReport);
       // Assure that the parameter set reflects all changes made to the model.
       mData.pModel->getModelParameterSet().refreshFromModel(false);
     }
   catch (...)
     {
       return false;
     }
   CCopasiXML XML;
   XML.setModel(mData.pModel);
   XML.setTaskList(mData.pTaskList);
   XML.setReportList(mData.pReportDefinitionList);
   XML.setPlotList(mData.pPlotDefinitionList);
   XML.setGUI(mData.pGUI);
   XML.setLayoutList(*mData.pListOfLayouts);
   XML.setDatamodel(this);
   bool success = true;
   if (!autoSave)
     {
       // We are first writing to a temporary file to prevent accidental
       // destruction of an existing file in case the save command fails.
       std::string TmpFileName;
       COptions::getValue("Tmp", TmpFileName);
       TmpFileName = CDirEntry::createTmpName(TmpFileName, ".cps");
       try
         {
           if (!XML.CCopasiXMLInterface::save(TmpFileName, FileName))
             {
               CDirEntry::remove(TmpFileName);
               success = false;
             }
         }
       catch (...)
         {
           CDirEntry::remove(TmpFileName);
           return false;
         }
       if (success && !CDirEntry::move(TmpFileName, FileName))
         success = false;
     }
   if (autoSave || !success)
     {
       try
         {
           if (!XML.CCopasiXMLInterface::save(FileName, FileName))
             return false;
         }
       catch (...)
         {
           return false;
         }
     }
   if (!autoSave)
     {
       changed(false);
       mData.mSaveFileName = CDirEntry::normalize(FileName);
     }
   return true;
 }
bool CCopasiDataModel::setSBMLFileName (const std::string & fileName)
Definition at line 1840 of file CCopasiDataModel.cpp.
References CDirEntry::fileName(), CDirEntry::isRelativePath(), CDirEntry::makePathAbsolute(), mData, CCopasiDataModel::CData::mSaveFileName, CCopasiDataModel::CData::mSBMLFileName, and CDirEntry::normalize().
Referenced by SEDMLImporter::importFirstSBMLModel(), and CCopasiXMLParser::SBMLReferenceElement::start().
 {
   mData.mSBMLFileName = CDirEntry::normalize(fileName);
   if (CDirEntry::isRelativePath(mData.mSBMLFileName) &&
       !CDirEntry::makePathAbsolute(mData.mSBMLFileName, mData.mSaveFileName))
     mData.mSBMLFileName = CDirEntry::fileName(mData.mSBMLFileName);
   return true;
 }
Member Data Documentation
CData CCopasiDataModel::mData protected
Definition at line 301 of file CCopasiDataModel.h.
Referenced by addDefaultReports(), addDefaultTasks(), addReport(), addTask(), appendDependentTasks(), autoSave(), changed(), commonAfterLoad(), exportMathModel(), exportMathModelToString(), exportSBML(), exportSBMLToString(), getCopasi2SBMLMap(), getCurrentSBMLDocument(), getFileName(), getGUI(), getListOfLayouts(), getModel(), getPlotDefinitionList(), getReferenceDirectory(), getReportDefinitionList(), getSBMLFileName(), getTaskList(), importSBML(), importSBMLFromString(), isChanged(), loadModel(), popData(), pushData(), removeLayout(), saveModel(), setSBMLFileName(), and ~CCopasiDataModel().
std::set<CCopasiObject*> CCopasiDataModel::mLastAddedObjects
Definition at line 312 of file CCopasiDataModel.h.
CData CCopasiDataModel::mOldData protected
Definition at line 302 of file CCopasiDataModel.h.
Referenced by commonAfterLoad(), deleteOldData(), getGUI(), getListOfLayouts(), getModel(), getPlotDefinitionList(), getReportDefinitionList(), getTaskList(), popData(), pushData(), and ~CCopasiDataModel().
CDataModelRenameHandler CCopasiDataModel::mRenameHandler protected
Definition at line 303 of file CCopasiDataModel.h.
Referenced by CCopasiDataModel(), importSBML(), importSBMLFromString(), and loadModel().
CCopasiVectorS< CMetabOld >* CCopasiDataModel::pOldMetabolites
This is a hack at the moment to be able to read Gepasi model files
Definition at line 309 of file CCopasiDataModel.h.
Referenced by CModel::load(), CReaction::loadOneRole(), and ~CCopasiDataModel().
The documentation for this class was generated from the following files:
CCopasiDataModel.h
CCopasiDataModel.cpp