COPASI API: CWindowInterface Class Reference
CWindowInterface Class Reference abstract
#include <CWindowInterface.h>
Public Member Functions
void addToMainWindow (CopasiUI3Window *window=NULL)
CWindowInterface (QWidget *parent=NULL, Qt::WindowFlags flags=NULL)
virtual QMenu * getWindowMenu () const =0
void removeFromMainWindow (CopasiUI3Window *window=NULL)
virtual void saveToFile (const QString &fileName) const
virtual ~CWindowInterface ()
Detailed Description
Definition at line 16 of file CWindowInterface.h.
Constructor & Destructor Documentation
CWindowInterface::CWindowInterface (QWidget * parent = NULL, Qt::WindowFlags flags = NULL)
Definition at line 9 of file CWindowInterface.cpp.
   : QMainWindow(parent, flags)
 {
 }
CWindowInterface::~CWindowInterface () virtual
Definition at line 14 of file CWindowInterface.cpp.
 {
 }
Member Function Documentation
void CWindowInterface::addToMainWindow (CopasiUI3Window * window = NULL)
Definition at line 18 of file CWindowInterface.cpp.
References CopasiUI3Window::addWindow(), and CopasiUI3Window::getMainWindow().
Referenced by CQCheckModelWindow::CQCheckModelWindow(), CQLayoutsWidget::createLayoutWindow(), PlotWindow::PlotWindow(), and SliderDialog::SliderDialog().
 {
   if (window == NULL)
     window = CopasiUI3Window::getMainWindow();
   if (window != NULL)
     window->addWindow(this);
 }
virtual QMenu* CWindowInterface::getWindowMenu () const pure virtual
Implemented in SliderDialog, CQNewMainWindow, PlotWindow, CQAnimationWindow, and CQCheckModelWindow.
Referenced by CopasiUI3Window::refreshWindowsMenu().
void CWindowInterface::removeFromMainWindow (CopasiUI3Window * window = NULL)
Definition at line 32 of file CWindowInterface.cpp.
References CopasiUI3Window::getMainWindow(), and CopasiUI3Window::removeWindow().
Referenced by CQNewMainWindow::closeEvent(), CQAnimationWindow::~CQAnimationWindow(), CQCheckModelWindow::~CQCheckModelWindow(), CQNewMainWindow::~CQNewMainWindow(), PlotWindow::~PlotWindow(), and SliderDialog::~SliderDialog().
 {
   if (window == NULL)
     window = CopasiUI3Window::getMainWindow();
   if (window != NULL)
     window->removeWindow(this);
 }
void CWindowInterface::saveToFile (const QString & fileName) const virtual
Saves the current window to the given filename.
This default implementation does nothing
Reimplemented in PlotWindow.
Definition at line 27 of file CWindowInterface.cpp.
Referenced by Worker::slotNotify().
 {
   // by default nothing will be saved, overwrite to implement saving to file
 }
The documentation for this class was generated from the following files:
CWindowInterface.h
CWindowInterface.cpp