COPASI API: CCopasiArray Class Reference
CCopasiArray Class Reference
#include <CCopasiArray.h>
Public Member Functions
CCopasiArray ()
CCopasiArray (const index_type &sizes)
size_t dimensionality () const
data_type & operator[] (const index_type &index)
const data_type & operator[] (const index_type &index) const
void resize (const index_type &sizes)
const index_type & size () const
virtual ~CCopasiArray ()
Public Member Functions inherited from CCopasiAbstractArray
virtual ~CCopasiAbstractArray ()
Private Attributes
std::vector< data_type > mData
size_t mDim
std::vector< size_t > mFactors
std::vector< size_t > mSizes
Additional Inherited Members
Public Types inherited from CCopasiAbstractArray
typedef C_FLOAT64 data_type
typedef std::vector< size_t > index_type
Detailed Description
this class contains an n-dimensional array
Definition at line 54 of file CCopasiArray.h.
Constructor & Destructor Documentation
CCopasiArray::CCopasiArray ()
Definition at line 21 of file CCopasiArray.cpp.
References mData.
     : mDim(0) {mData.resize(1);}
CCopasiArray::CCopasiArray (const index_type & sizes)
Definition at line 24 of file CCopasiArray.cpp.
References resize().
 {
   resize(sizes);
 }
virtual CCopasiArray::~CCopasiArray () inline virtual
Definition at line 62 of file CCopasiArray.h.
 {};
Member Function Documentation
size_t CCopasiArray::dimensionality () const inline virtual
Implements CCopasiAbstractArray.
Definition at line 79 of file CCopasiArray.h.
References mDim.
Referenced by CSensMethod::do_scaling().
   {return mDim;}
CCopasiArray::data_type & CCopasiArray::operator[] (const index_type & index) virtual
Implements CCopasiAbstractArray.
Definition at line 48 of file CCopasiArray.cpp.
References mData, mDim, and mFactors.
 {
 #ifdef COPASI_DEBUG
   assert(index.size() == mDim);
 #endif
   size_t tmpindex = 0;
   index_type::const_iterator itIndex, it, itEnd = mFactors.end();
   for (itIndex = index.begin(), it = mFactors.begin(); it != itEnd; ++it, ++itIndex)
     tmpindex += *itIndex * *it;
   return mData[tmpindex];
 }
const CCopasiArray::data_type & CCopasiArray::operator[] (const index_type & index) const virtual
Implements CCopasiAbstractArray.
Definition at line 63 of file CCopasiArray.cpp.
References mData, mDim, and mFactors.
 {
 #ifdef COPASI_DEBUG
   assert(index.size() == mDim);
 #endif
   size_t tmpindex = 0;
   index_type::const_iterator itIndex, it, itEnd = mFactors.end();
   for (itIndex = index.begin(), it = mFactors.begin(); it != itEnd; ++it, ++itIndex)
     tmpindex += *itIndex * *it;
   return mData[tmpindex];
 }
void CCopasiArray::resize (const index_type & sizes)
Definition at line 29 of file CCopasiArray.cpp.
References mData, mDim, mFactors, and mSizes.
Referenced by CSensMethod::calculate_one_level(), CCopasiArray(), CSensMethod::do_target_calculation(), and CSensMethod::initialize().
 {
   mDim = sizes.size();
   mSizes = sizes;
   mFactors.resize(mDim);
   size_t tmpDataSize = 1;
   index_type::const_reverse_iterator it, itEnd = sizes.rend();
   index_type::reverse_iterator itFaktor;
   for (it = sizes.rbegin(), itFaktor = mFactors.rbegin(); it != itEnd; ++it, ++itFaktor)
     {
       *itFaktor = tmpDataSize;
       tmpDataSize *= *it;
     }
   mData.resize(tmpDataSize);
 }
const index_type& CCopasiArray::size () const inline virtual
Implements CCopasiAbstractArray.
Definition at line 76 of file CCopasiArray.h.
References mSizes.
Referenced by CSensMethod::do_collapsing(), and CSensMethod::do_collapsing_innerloop().
   {return mSizes;}
Member Data Documentation
std::vector<data_type> CCopasiArray::mData private
Definition at line 70 of file CCopasiArray.h.
Referenced by CCopasiArray(), operator[](), and resize().
size_t CCopasiArray::mDim private
Definition at line 72 of file CCopasiArray.h.
Referenced by dimensionality(), operator[](), and resize().
std::vector<size_t> CCopasiArray::mFactors private
Definition at line 73 of file CCopasiArray.h.
Referenced by operator[](), and resize().
std::vector<size_t> CCopasiArray::mSizes private
Definition at line 71 of file CCopasiArray.h.
Referenced by resize(), and size().
The documentation for this class was generated from the following files:
CCopasiArray.h
CCopasiArray.cpp