COPASI API: CScanWidgetRandom Class Reference
CScanWidgetRandom Class Reference
#include <CScanWidgetRandom.h>
Public Member Functions
CScanWidgetRandom (QWidget *parent=0)
CScanWidgetRandom (const CScanWidgetRandom &src, QWidget *parent=0)
void initFromObject (const CCopasiObject *obj)
virtual void load (const CCopasiParameterGroup *pItem)
virtual bool save (CCopasiParameterGroup *pItem) const
virtual ~CScanWidgetRandom ()
Public Member Functions inherited from CScanItemData
CScanItemData (const CScanItemData &src)
const CScanProblem::Type & getType () const
virtual ~CScanItemData ()
Protected Slots
virtual void changeType ()
virtual void slotChooseObject ()
Protected Attributes
const CCopasiObject * mpObject
Protected Attributes inherited from CScanItemData
CCopasiParameterGroup * mpData
CScanProblem::Type mType
Private Member Functions
void init ()
Additional Inherited Members
Protected Member Functions inherited from CScanItemData
CScanItemData (const CScanProblem::Type &type)
Detailed Description
Definition at line 27 of file CScanWidgetRandom.h.
Constructor & Destructor Documentation
CScanWidgetRandom::CScanWidgetRandom (QWidget * parent = 0)
Definition at line 33 of file CScanWidgetRandom.cpp.
References CQIconResource::copasi, CQIconResource::icon(), and init().
                                                     :
   QWidget(parent),
   CScanItemData(CScanProblem::SCAN_RANDOM)
 {
   setupUi(this);
   buttonObject->setIcon(CQIconResource::icon(CQIconResource::copasi));
   init();
   retranslateUi(this);
 }
CScanWidgetRandom::CScanWidgetRandom (const CScanWidgetRandom & src, QWidget * parent = 0)
Definition at line 43 of file CScanWidgetRandom.cpp.
References CQIconResource::copasi, CQIconResource::icon(), init(), load(), and CScanItemData::mpData.
                                                                                     :
   QWidget(parent),
   CScanItemData(src)
 {
   setupUi(this);
   buttonObject->setIcon(CQIconResource::icon(CQIconResource::copasi));
   init();
   load(mpData);
   retranslateUi(this);
 }
CScanWidgetRandom::~CScanWidgetRandom () virtual
Definition at line 57 of file CScanWidgetRandom.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CScanWidgetRandom::changeType () protected virtual slot
Definition at line 206 of file CScanWidgetRandom.cpp.
References C_FLOAT64, C_INT32, CCopasiObject::getValuePointer(), and mpObject.
Referenced by load().
 {
   C_INT32 type = comboBoxType->currentIndex();
   C_FLOAT64 value = 0.0;
   if (mpObject != NULL)
     value = *(C_FLOAT64*)mpObject->getValuePointer();
   switch (type)
     {
       case 0: // uniform
         lineEditMin->setEnabled(true);
         lineEditMax->setEnabled(true);
         labelMin->setText("min");
         labelMax->setText("max");
         if (mpObject != NULL)
           {
             lineEditMin->setText(QString::number(value * 0.5));
             lineEditMax->setText(QString::number(value * 2));
           }
         else
           {
             lineEditMin->setText("");
             lineEditMax->setText("");
           }
         break;
       case 1: // normal
         lineEditMin->setEnabled(true);
         lineEditMax->setEnabled(true);
         labelMin->setText("mean");
         labelMax->setText("standard deviation");
         if (mpObject != NULL)
           {
             lineEditMin->setText(QString::number(value));
             lineEditMax->setText(QString::number(value * 0.1));
           }
         else
           {
             lineEditMin->setText("");
             lineEditMax->setText("");
           }
         break;
       case 2: // Poisson
         lineEditMin->setEnabled(true);
         lineEditMax->setEnabled(false);
         labelMin->setText("mean");
         labelMax->setText("");
         if (mpObject != NULL)
           lineEditMin->setText(QString::number(value));
         else
           lineEditMin->setText("");
         lineEditMax->setText("");
         break;
       case 3: // Gamma
         lineEditMin->setEnabled(true);
         lineEditMax->setEnabled(true);
         labelMin->setText("shape");
         labelMax->setText("scale");
         if (mpObject != NULL)
           {
             lineEditMin->setText(QString::number(1.0 * value));
             lineEditMax->setText(QString::number(0.1));
           }
         else
           {
             lineEditMin->setText("");
             lineEditMax->setText("");
           }
         break;
     }
 }
void CScanWidgetRandom::init () private
Definition at line 62 of file CScanWidgetRandom.cpp.
References mpObject.
Referenced by CScanWidgetRandom().
 {
   lineEditObject->setReadOnly(true);
   lineEditMin->setValidator(new QDoubleValidator(lineEditMin));
   lineEditMax->setValidator(new QDoubleValidator(lineEditMax));
   mpObject = NULL;
 }
void CScanWidgetRandom::initFromObject (const CCopasiObject * obj)
Definition at line 84 of file CScanWidgetRandom.cpp.
References C_FLOAT64, C_INT32, FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiObject::getValuePointer(), CCopasiObject::isValueDbl(), and mpObject.
Referenced by ScanWidget::slotAddItem(), and slotChooseObject().
 {
   mpObject = obj;
   if (obj)
     {
       lineEditObject->setText(FROM_UTF8(obj->getObjectDisplayName()));
       if (obj->isValueDbl())
         {
           C_FLOAT64 value = *(C_FLOAT64*)obj->getValuePointer();
           C_INT32 type = comboBoxType->currentIndex();
           if (type == 0) //uniform
             {
               lineEditMin->setText(QString::number(value * 0.5));
               lineEditMax->setText(QString::number(value * 2));
             }
           if (type == 1) //normal
             {
               lineEditMin->setText(QString::number(value));
               lineEditMax->setText(QString::number(value * 0.1));
             }
           if (type == 2) //poisson
             {
               lineEditMin->setText(QString::number(value));
               lineEditMax->setText("");
             }
         }
     }
   else
     {
       lineEditObject->setText("");
       lineEditMin->setText("");
       lineEditMax->setText("");
     }
 }
void CScanWidgetRandom::load (const CCopasiParameterGroup * pItem) virtual
Implements CScanItemData.
Definition at line 125 of file CScanWidgetRandom.cpp.
References C_INT32, changeType(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDisplayName(), getParameterValue(), CCopasiParameterGroup::getValue(), CScanItemData::mpData, mpObject, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUINT, and CScanProblem::SCAN_RANDOM.
Referenced by CScanWidgetRandom(), and ScanWidget::loadTask().
 {
   if (pItem == NULL) return;
   *mpData = *pItem;
   unsigned C_INT32 * tmp;
   if (!(tmp = mpData->getValue("Type").pUINT))
     return;
   if (*(CScanProblem::Type *) tmp != CScanProblem::SCAN_RANDOM)
     return;
   std::string *pString;
   if (!(pString = mpData->getValue("Object").pSTRING))
     return;
   if (*pString == "")
     mpObject = NULL;
   else
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
       assert(pDataModel != NULL);
       mpObject = pDataModel->getDataObject(*pString);
     }
   if (mpObject)
     lineEditObject->setText(FROM_UTF8(mpObject->getObjectDisplayName()));
   else
     lineEditObject->setText("");
   if (!(tmp = mpData->getValue("Distribution type").pUINT))
     return;
   comboBoxType->setCurrentIndex(*tmp);
   changeType();
   lineEditMin->setText(getParameterValue(mpData, "Minimum"));
   lineEditMax->setText(getParameterValue(mpData, "Maximum"));
   bool * pBool;
   if (!(pBool = mpData->getValue("log").pBOOL))
     return;
   checkBoxLog->setChecked(* pBool);
   return;
 }
bool CScanWidgetRandom::save (CCopasiParameterGroup * pItem) const virtual
Implements CScanItemData.
Definition at line 179 of file CScanWidgetRandom.cpp.
References C_INT32, CCopasiObject::getCN(), CScanItemData::mpData, mpObject, and CCopasiParameterGroup::setValue().
 {
   mpData->setValue("Distribution type", (unsigned C_INT32) comboBoxType->currentIndex());
   mpData->setValue("Minimum", lineEditMin->text().toDouble());
   mpData->setValue("Maximum", lineEditMax->text().toDouble());
   mpData->setValue("log", checkBoxLog->isChecked());
   if (mpObject != NULL)
     {
       mpData->setValue("Object", mpObject->getCN());
     }
   else
     {
       mpData->setValue("Object", std::string(""));
     }
   if (pItem != NULL)
     {
       if (*mpData == *pItem) return false;
       *pItem = *mpData;
       return true;
     }
   return false;
 }
void CScanWidgetRandom::slotChooseObject () protected virtual slot
Definition at line 72 of file CScanWidgetRandom.cpp.
References CCopasiSelectionDialog::getObjectSingle(), initFromObject(), CQSimpleSelectionTree::InitialTime, mpObject, and CQSimpleSelectionTree::Parameters.
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
         CQSimpleSelectionTree::InitialTime |
         CQSimpleSelectionTree::Parameters,
         mpObject);
   if (mpObject != pObject) // Object selection changed.
     initFromObject(pObject);
 }
Member Data Documentation
const CCopasiObject* CScanWidgetRandom::mpObject protected
Definition at line 45 of file CScanWidgetRandom.h.
Referenced by changeType(), init(), initFromObject(), load(), save(), and slotChooseObject().
The documentation for this class was generated from the following files:
CScanWidgetRandom.h
CScanWidgetRandom.cpp