COPASI API: CQMessageBox Class Reference
CQMessageBox Class Reference
#include <CQMessageBox.h>
Public Member Functions
CQMessageBox (Icon icon, const QString &title, const QString &text, StandardButtons buttons=NoButton, QWidget *parent=0, Qt::WindowFlags f=Qt::Dialog|Qt::MSWindowsFixedSizeDialogHint)
void setFilteredText (const QString &text)
void setText (const QString &text)
~CQMessageBox ()
Static Public Member Functions
static StandardButton confirmDelete (QWidget *parent, const QString &objectType, const QString &objects, const std::set< const CCopasiObject * > &deletedObjects)
static StandardButton critical (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
static StandardButton information (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
static StandardButton question (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
static StandardButton warning (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
Protected Attributes
QWidget * mpPage1
QWidget * mpPage2
QTabWidget * mpTabWidget
QTextEdit * mpText1
QTextEdit * mpText2
QVBoxLayout * mpVerticalLayoutPage1
QVBoxLayout * mpVerticalLayoutPage2
Detailed Description
Definition at line 27 of file CQMessageBox.h.
Constructor & Destructor Documentation
CQMessageBox::CQMessageBox (Icon icon, const QString & title, const QString & text, StandardButtons buttons = NoButton, QWidget * parent = 0, Qt::WindowFlags f = Qt::Dialog | Qt::MSWindowsFixedSizeDialogHint)
Definition at line 35 of file CQMessageBox.cpp.
References CopasiUI3Window::getMainWindow(), mpPage1, mpTabWidget, mpText1, mpVerticalLayoutPage1, and CopasiUI3Window::setMessageShown().
Referenced by critical(), information(), question(), and warning().
                                            :
     QMessageBox(icon, title, QString(), buttons, parent, f),
     mpTabWidget(NULL),
     mpPage1(NULL),
     mpVerticalLayoutPage1(NULL),
     mpText1(NULL),
     mpPage2(NULL),
     mpVerticalLayoutPage2(NULL),
     mpText2(NULL)
 {
   if (CopasiUI3Window::getMainWindow() != NULL)
     {
       CopasiUI3Window::getMainWindow()->setMessageShown(true);
     }
   mpTabWidget = new QTabWidget(this);
   mpTabWidget->setObjectName(QString::fromUtf8("mpTabWidget"));
   mpTabWidget->setMinimumSize(QSize(400, 200));
   mpPage1 = new QWidget();
   mpPage1->setObjectName(QString::fromUtf8("mpPage1"));
   mpVerticalLayoutPage1 = new QVBoxLayout(mpPage1);
   mpVerticalLayoutPage1->setMargin(2);
   mpVerticalLayoutPage1->setObjectName(QString::fromUtf8("mpVerticalLayoutPage1"));
   mpText1 = new QTextEdit(mpPage1);
   mpText1->setObjectName(QString::fromUtf8("mpText1"));
   mpText1->setReadOnly(true);
   mpText1->setText(text);
   mpVerticalLayoutPage1->addWidget(mpText1);
   mpTabWidget->addTab(mpPage1, QString("Messages"));
   // The code below is derived from qt-4.4.3/src/gui/dialogs/qmessagebox.cpp
   static_cast<QGridLayout *>(layout())->addWidget(mpTabWidget, 0, 1, 1, 1);
   QLabel * pLabel = findChild<QLabel *>("qt_msgbox_label");
   if (pLabel != NULL)
     pLabel->hide();
 }
CQMessageBox::~CQMessageBox ()
Definition at line 79 of file CQMessageBox.cpp.
References CopasiUI3Window::getMainWindow(), and CopasiUI3Window::setMessageShown().
 {
   if (CopasiUI3Window::getMainWindow() != NULL)
     {
       CopasiUI3Window::getMainWindow()->setMessageShown(false);
     }
 }
Member Function Documentation
QMessageBox::StandardButton CQMessageBox::confirmDelete (QWidget * parent, const QString & objectType, const QString & objects, const std::set< const CCopasiObject * > & deletedObjects) static
Definition at line 151 of file CQMessageBox.cpp.
References CFunctionDB::appendDependentFunctions(), CModel::appendDependentModelObjects(), CCopasiDataModel::appendDependentTasks(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiRootContainer::getFunctionList(), CCopasiDataModel::getModel(), and question().
Referenced by CQReportDefinition::btnDeleteReportClicked(), CQParameterSetsDM::removeRows(), CQReportDM::removeRows(), CQLayoutsDM::removeRows(), CQReactionDM::removeRows(), CQFunctionDM::removeRows(), CQEventDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), CQSpecieDM::removeRows(), ReactionsWidget1::saveToReaction(), CQReactionDM::setEquation(), FunctionWidget1::slotBtnDelete(), ReactionsWidget1::slotBtnDelete(), CQSpeciesDetail::slotBtnDelete(), CQCompartment::slotBtnDelete(), and CQModelValue::slotBtnDelete().
 {
   if (deletedObjects.size() == 0)
     return QMessageBox::Ok;
   // Determine the affected data model
   const CCopasiDataModel * pDataModel = (*deletedObjects.begin())->getObjectDataModel();
   // Determine the affected function DB
   CFunctionDB * pFunctionDB =
     dynamic_cast< CFunctionDB * >((*deletedObjects.begin())->getObjectAncestor("FunctionDB"));
   if (pDataModel == NULL &&
       pFunctionDB == NULL)
     return QMessageBox::Ok;
   if (pFunctionDB != NULL)
     {
       // TODO In case a function is deleted we need to loop through all data models
       pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
     }
   else
     {
       pFunctionDB = CCopasiRootContainer::getFunctionList();
     }
   QString msg =
     QString("Do you want to delete the listed %1?\n  %2\n").arg(objectType, objects);
   std::set< const CCopasiObject * > Functions;
   std::set< const CCopasiObject * > Reactions;
   std::set< const CCopasiObject * > Metabolites;
   std::set< const CCopasiObject * > Values;
   std::set< const CCopasiObject * > Compartments;
   std::set< const CCopasiObject * > Events;
   std::set< const CCopasiObject * > Tasks;
   bool Used = false;
   if (pFunctionDB != NULL)
     {
       Used |= pFunctionDB->appendDependentFunctions(deletedObjects, Functions);
       if (Functions.size() > 0)
         {
           msg.append("Following functions(s) reference above and will be deleted:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Functions.begin();
           std::set< const CCopasiObject * >::const_iterator end = Functions.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
     }
   const CModel * pModel = NULL;
   if (pDataModel != NULL)
     {
       pModel = pDataModel->getModel();
       // We need to check the tasks
       Used |= pDataModel->appendDependentTasks(deletedObjects, Tasks);
       if (Tasks.size() > 0)
         {
           msg.append("Following task(s) reference above and will be modified:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Tasks.begin();
           std::set< const CCopasiObject * >::const_iterator end = Tasks.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
     }
   if (pModel != NULL)
     {
       Used |= pModel->appendDependentModelObjects(deletedObjects, Reactions, Metabolites,
               Compartments, Values, Events);
       if (Reactions.size() > 0)
         {
           msg.append("Following reactions(s) reference above and will be deleted:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Reactions.begin();
           std::set< const CCopasiObject * >::const_iterator end = Reactions.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
       if (Metabolites.size() > 0)
         {
           msg.append("Following species reference above and will be deleted:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Metabolites.begin();
           std::set< const CCopasiObject * >::const_iterator end = Metabolites.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
       if (Values.size() > 0)
         {
           msg.append("Following global quantities reference above and will be deleted:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Values.begin();
           std::set< const CCopasiObject * >::const_iterator end = Values.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
       if (Compartments.size() > 0)
         {
           msg.append("Following compartment(s) reference above and will be deleted:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Compartments.begin();
           std::set< const CCopasiObject * >::const_iterator end = Compartments.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
       if (Events.size() > 0)
         {
           msg.append("Following event(s) reference above and will be deleted:\n  ");
           std::set< const CCopasiObject * >::const_iterator it = Events.begin();
           std::set< const CCopasiObject * >::const_iterator end = Events.end();
           for (; it != end; ++it)
             {
               msg.append(FROM_UTF8((*it)->getObjectName()));
               msg.append("\n  ");
             }
           msg.remove(msg.length() - 2, 2);
         }
     }
   StandardButton choice = QMessageBox::Ok;
   if (Used)
     {
       choice = CQMessageBox::question(parent, "CONFIRM DELETE", msg,
                                       QMessageBox::Ok | QMessageBox::Cancel,
                                       QMessageBox::Cancel);
     }
   return choice;
 }
QMessageBox::StandardButton CQMessageBox::critical (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Definition at line 135 of file CQMessageBox.cpp.
References CQMessageBox(), and CopasiUI3Window::isMainThread().
Referenced by DataModelGUI::buildChangedObjects(), TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CQGLLayoutPainter::draw(), CQGLLayoutPainter::draw_bitmap(), CQNewMainWindow::export_bitmap(), CQGLLayoutPainter::export_bitmap(), TaskWidget::finishTask(), CQFittingWidget::loadTask(), main(), CQBarChart::saveDataToFile(), CQMiriamWidget::showEvent(), CQPreferenceDialog::slotBtnOk(), CopasiUI3Window::slotExportMathModelFinished(), CopasiUI3Window::slotExportSBMLToStringFinished(), FunctionWidget1::slotFcnDescriptionChanged(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFileSaveFinished(), TaskWidget::slotFinishThread(), CopasiUI3Window::slotImportSBMLFinished(), CopasiUI3Window::slotImportSBMLFromStringFinished(), CQTimeSeriesWidget::slotSave(), PlotWindow::slotSaveData(), CQExpressionWidget::slotSelectObject(), and CopasiUI3Window::slotUpdateMIRIAMFinished().
 {
   if (!CopasiUI3Window::isMainThread())
     return defaultButton;
   CQMessageBox * pMessageBox = new CQMessageBox(QMessageBox::Critical, title, text, buttons, parent);
   pMessageBox->setDefaultButton(defaultButton);
   StandardButton choice = (StandardButton) pMessageBox->exec();
   delete pMessageBox;
   return choice;
 }
QMessageBox::StandardButton CQMessageBox::information (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Definition at line 88 of file CQMessageBox.cpp.
References CQMessageBox(), and CopasiUI3Window::isMainThread().
Referenced by SliderSettingsDialog::browseButtonPressed(), CopasiUI3Window::checkPendingMessages(), checkSelection(), CProgressBar::closeEvent(), SliderDialog::createNewSlider(), SliderDialog::createSlidersForFolder(), SliderDialog::deleteInvalidSliders(), TaskWidget::finishTask(), SliderDialog::getCSlidersForObject(), CopasiFileDialog::getSaveFileName(), CQBarChart::hotKeysMessage(), FunctionWidget1::leave(), SliderSettingsDialog::logCheckBoxToggled(), SliderSettingsDialog::minValueChanged(), CopasiFileDialog::openExampleDir(), CQTabWidget::save(), CQReportDefinition::save(), CQSpeciesDetail::save(), CQFunctionDM::setData(), CQSpecieDM::setData(), CopasiUI3Window::slotConvertToIrreversible(), CQTSSAWidget::slotDuration(), CQTrajectoryWidget::slotDuration(), CQExperimentData::slotExperimentChanged(), TaskWidget::slotFinishThread(), CQTSSAWidget::slotIntervals(), CQTrajectoryWidget::slotIntervals(), CQTSSAWidget::slotIntervalSize(), CQTrajectoryWidget::slotIntervalSize(), CQCrossSectionTaskWidget::slotOutputConvergence(), CQCrossSectionTaskWidget::slotOutputCrossings(), CQCrossSectionTaskWidget::slotOutputDelay(), CopasiUI3Window::slotQuit(), CQCrossSectionTaskWidget::slotUpdateConvergence(), CQCrossSectionTaskWidget::slotUpdateCrossings(), and WizardDialog::textBrowser_anchorClicked().
 {
   if (!CopasiUI3Window::isMainThread())
     return defaultButton;
   CQMessageBox * pMessageBox = new CQMessageBox(QMessageBox::Information, title, text, buttons, parent);
   pMessageBox->setDefaultButton(defaultButton);
   StandardButton choice = (StandardButton) pMessageBox->exec();
   delete pMessageBox;
   return choice;
 }
QMessageBox::StandardButton CQMessageBox::question (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Definition at line 103 of file CQMessageBox.cpp.
References CQMessageBox(), and CopasiUI3Window::isMainThread().
Referenced by CQReportDefinition::btnAdvancedClicked(), checkSelection(), TaskWidget::commonRunTask(), confirmDelete(), DataModelGUI::importCellDesigner(), CopasiUI3Window::importSBMLFromString(), CQReportDefinitionSelect::loadReportDefinitionVector(), SliderSettingsDialog::maxValueChanged(), SliderSettingsDialog::minValueChanged(), CopasiUI3Window::newDoc(), CQModifiedDM::removeRows(), CQBiologicalDescriptionDM::removeRows(), CQReferenceDM::removeRows(), CQCreatorDM::removeRows(), CQParameterSetsWidget::slotBtnClearClicked(), CQPlotsWidget::slotBtnClearClicked(), CQEventsWidget::slotBtnClearClicked(), CQReactionsWidget::slotBtnClearClicked(), CQReportsWidget::slotBtnClearClicked(), CQCompartmentsWidget::slotBtnClearClicked(), CQFunctionsWidget::slotBtnClearClicked(), CQGlobalQuantitiesWidget::slotBtnClearClicked(), CQSpeciesWidget::slotBtnClearClicked(), CQLayoutsWidget::slotBtnClearClicked(), CQMiriamWidget::slotBtnClearClicked(), CQParameterOverviewWidget::slotBtnNew(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotImportSBML(), CCopasiPlotSelectionDialog::slotOKButtonClicked(), and CopasiUI3Window::slotQuit().
 {
   if (!CopasiUI3Window::isMainThread())
     return defaultButton;
   CQMessageBox * pMessageBox = new CQMessageBox(QMessageBox::Question, title, text, buttons, parent);
   pMessageBox->setDefaultButton(defaultButton);
   StandardButton choice = (StandardButton) pMessageBox->exec();
   delete pMessageBox;
   return choice;
 }
void CQMessageBox::setFilteredText (const QString & text)
Definition at line 342 of file CQMessageBox.cpp.
References mpPage2, mpTabWidget, mpText2, and mpVerticalLayoutPage2.
Referenced by CopasiUI3Window::checkPendingMessages().
 {
   if (!text.isEmpty() && mpPage2 == NULL)
     {
       mpPage2 = new QWidget();
       mpPage2->setObjectName(QString::fromUtf8("mpPage2"));
       mpVerticalLayoutPage2 = new QVBoxLayout(mpPage2);
       mpVerticalLayoutPage2->setMargin(2);
       mpVerticalLayoutPage2->setObjectName(QString::fromUtf8("mpVerticalLayoutPage2"));
       mpText2 = new QTextEdit(mpPage2);
       mpText2->setObjectName(QString::fromUtf8("mpText2"));
       mpText2->setReadOnly(true);
       mpVerticalLayoutPage2->addWidget(mpText2);
       mpTabWidget->addTab(mpPage2, QString("Minor Issues"));
     }
   mpText2->setText(text);
 }
void CQMessageBox::setText (const QString & text)
Definition at line 337 of file CQMessageBox.cpp.
References mpText1.
Referenced by CopasiUI3Window::slotFileSave().
 {
   mpText1->setText(text);
 }
QMessageBox::StandardButton CQMessageBox::warning (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Definition at line 119 of file CQMessageBox.cpp.
References CQMessageBox(), and CopasiUI3Window::isMainThread().
Referenced by CCopasiSelectionDialog::chooseCellMatrix(), CQRDFTreeView::enterProtected(), CQGLLayoutPainter::export_bitmap(), CQLayoutMainWindow::saveImage(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFileSaveFinished(), and CQLayoutMainWindow::startAnimation().
 {
   if (!CopasiUI3Window::isMainThread())
     return defaultButton;
   CQMessageBox * pMessageBox = new CQMessageBox(QMessageBox::Warning, title, text, buttons, parent);
   pMessageBox->setDefaultButton(defaultButton);
   StandardButton choice = (StandardButton) pMessageBox->exec();
   delete pMessageBox;
   return choice;
 }
Member Data Documentation
QWidget* CQMessageBox::mpPage1 protected
Definition at line 64 of file CQMessageBox.h.
Referenced by CQMessageBox().
QWidget* CQMessageBox::mpPage2 protected
Definition at line 67 of file CQMessageBox.h.
Referenced by setFilteredText().
QTabWidget* CQMessageBox::mpTabWidget protected
Definition at line 63 of file CQMessageBox.h.
Referenced by CQMessageBox(), and setFilteredText().
QTextEdit* CQMessageBox::mpText1 protected
Definition at line 66 of file CQMessageBox.h.
Referenced by CQMessageBox(), and setText().
QTextEdit* CQMessageBox::mpText2 protected
Definition at line 69 of file CQMessageBox.h.
Referenced by setFilteredText().
QVBoxLayout* CQMessageBox::mpVerticalLayoutPage1 protected
Definition at line 65 of file CQMessageBox.h.
Referenced by CQMessageBox().
QVBoxLayout* CQMessageBox::mpVerticalLayoutPage2 protected
Definition at line 68 of file CQMessageBox.h.
Referenced by setFilteredText().
The documentation for this class was generated from the following files:
CQMessageBox.h
CQMessageBox.cpp