COPASI API: CQEFMNetReactionDM Class Reference
CQEFMNetReactionDM Class Reference
#include <CQEFMNetReactionDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQEFMNetReactionDM (QObject *parent=0)
QVariant data (const QModelIndex &index, int role) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool isDefaultRow (const QModelIndex &i) const
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setTask (const CEFMTask *pTask)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
bool removeRow (int position)
Protected Member Functions
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Private Attributes
std::vector< CFluxMode >
::const_iterator mBeginModes
size_t mModesSize
const CEFMTask * mpTask
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 34 of file CQEFMNetReactionDM.h.
Constructor & Destructor Documentation
CQEFMNetReactionDM::CQEFMNetReactionDM (QObject * parent = 0)
Definition at line 28 of file CQEFMNetReactionDM.cpp.
                                                      :
     CQBaseDataModel(parent),
     mpTask(NULL),
     mBeginModes(),
     mModesSize(0)
 {}
Member Function Documentation
int CQEFMNetReactionDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 43 of file CQEFMNetReactionDM.cpp.
References NetReactionDM_COLUMNS.
 {
   return NetReactionDM_COLUMNS;
 }
QVariant CQEFMNetReactionDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 56 of file CQEFMNetReactionDM.cpp.
References COL_MODIFIER, COL_REACTION, COL_ROW_NUMBER, FROM_UTF8, CEFMTask::getInternalSpecies(), CEFMTask::getNetReaction(), mBeginModes, mpTask, and rowCount().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       std::vector< CFluxMode >::const_iterator itMode = mBeginModes + index.row();
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return QVariant(index.row() + 1);
             break;
           case COL_REACTION:
             return QVariant(QString(FROM_UTF8(mpTask->getNetReaction(*itMode))));
             break;
           case COL_MODIFIER:
             return QVariant(QString(FROM_UTF8(mpTask->getInternalSpecies(*itMode))));
             break;
         }
     }
   return QVariant();
 }
Qt::ItemFlags CQEFMNetReactionDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 48 of file CQEFMNetReactionDM.cpp.
 {
   if (!index.isValid())
     return Qt::ItemIsEnabled;
   return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
 }
QVariant CQEFMNetReactionDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 87 of file CQEFMNetReactionDM.cpp.
References COL_MODIFIER, COL_REACTION, and COL_ROW_NUMBER.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
             break;
           case COL_REACTION:
             return QVariant(QString("Net Reaction"));
             break;
           case COL_MODIFIER:
             return QVariant(QString("Internal Species"));
             break;
         }
     }
   return QString("%1").arg(section + 1);
 }
bool CQEFMNetReactionDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 135 of file CQEFMNetReactionDM.cpp.
 {
   return false;
 }
bool CQEFMNetReactionDM::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 147 of file CQEFMNetReactionDM.cpp.
 {
   return false;
 }
bool CQEFMNetReactionDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 141 of file CQEFMNetReactionDM.cpp.
 {
   return false;
 }
int CQEFMNetReactionDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 35 of file CQEFMNetReactionDM.cpp.
References mModesSize, and mpTask.
Referenced by data().
 {
   if (mpTask == NULL)
     return 0;
   return (int) mModesSize;
 }
bool CQEFMNetReactionDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 129 of file CQEFMNetReactionDM.cpp.
 {
   return false;
 }
void CQEFMNetReactionDM::setTask (const CEFMTask * pTask)
Definition at line 114 of file CQEFMNetReactionDM.cpp.
References CEFMTask::getFluxModes(), mBeginModes, mModesSize, mpTask, and pTask.
Referenced by CQEFMResultWidget::loadResult().
 {
   mpTask = pTask;
   if (mpTask != NULL)
     {
       mBeginModes = mpTask->getFluxModes().begin();
       mModesSize = mpTask->getFluxModes().size();
     }
   else
     {
       mModesSize = 0;
     }
 }
Member Data Documentation
std::vector< CFluxMode >::const_iterator CQEFMNetReactionDM::mBeginModes private
Definition at line 61 of file CQEFMNetReactionDM.h.
Referenced by data(), and setTask().
size_t CQEFMNetReactionDM::mModesSize private
Definition at line 62 of file CQEFMNetReactionDM.h.
Referenced by rowCount(), and setTask().
const CEFMTask* CQEFMNetReactionDM::mpTask private
Definition at line 59 of file CQEFMNetReactionDM.h.
Referenced by data(), rowCount(), and setTask().
The documentation for this class was generated from the following files:
CQEFMNetReactionDM.h
CQEFMNetReactionDM.cpp