COPASI API: CLRenderInformationBase Class Reference
CLRenderInformationBase Class Reference
#include <CLRenderInformationBase.h>
Public Member Functions
void addColorDefinition (const CLColorDefinition *cd)
void addGradientDefinition (const CLGradientBase *gradient)
void addLineEnding (const CLLineEnding *le)
void addSBMLAttributes (RenderInformationBase *pBase) const
CLRenderInformationBase (const std::string &name, CCopasiContainer *pParent=NULL)
CLRenderInformationBase (const CLRenderInformationBase &source, CCopasiContainer *pParent)
CLRenderInformationBase (const RenderInformationBase &source, const std::string &name, CCopasiContainer *pParent=NULL)
CLColorDefinition * createColorDefinition ()
CLLinearGradient * createLinearGradientDefinition ()
CLLineEnding * createLineEnding ()
CLRadialGradient * createRadialGradientDefinition ()
const std::string & getBackgroundColor () const
CLColorDefinition * getColorDefinition (size_t index)
const CLColorDefinition * getColorDefinition (size_t index) const
CLGradientBase * getGradientDefinition (size_t index)
const CLGradientBase * getGradientDefinition (size_t index) const
const std::string & getKey () const
CLLineEnding * getLineEnding (size_t index)
const CLLineEnding * getLineEnding (size_t index) const
CCopasiVector
< CLColorDefinition > * getListOfColorDefinitions ()
const CCopasiVector
< CLColorDefinition > * getListOfColorDefinitions () const
CCopasiVector< CLGradientBase > * getListOfGradientDefinitions ()
const CCopasiVector
< CLGradientBase > * getListOfGradientDefinitions () const
CCopasiVector< CLLineEnding > * getListOfLineEndings ()
const CCopasiVector
< CLLineEnding > * getListOfLineEndings () const
const std::string & getName () const
size_t getNumColorDefinitions () const
size_t getNumGradientDefinitions () const
size_t getNumLineEndings () const
const std::string & getReferenceRenderInformationKey () const
void removeColorDefinition (size_t index)
void removeGradientDefinition (size_t index)
void removeLineEnding (size_t index)
void setBackgroundColor (const std::string &bg)
void setName (const std::string &name)
void setReferenceRenderInformationKey (const std::string &key)
~CLRenderInformationBase ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
std::string mBackgroundColor
std::string mKey
CCopasiVector< CLColorDefinition > mListOfColorDefinitions
CCopasiVector< CLGradientBase > mListOfGradientDefinitions
CCopasiVector< CLLineEnding > mListOfLineEndings
std::string mName
std::string mReferenceRenderInformation
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CLRenderInformationBase & operator= (const CLRenderInformationBase &source)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 30 of file CLRenderInformationBase.h.
Constructor & Destructor Documentation
CLRenderInformationBase::CLRenderInformationBase (const std::string & name, CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 27 of file CLRenderInformationBase.cpp.
                                                                                                 :
   CLBase(),
   CCopasiContainer(name, pParent),
   mKey(""),
   mName("")
 {
 }
CLRenderInformationBase::CLRenderInformationBase (const CLRenderInformationBase & source, CCopasiContainer * pParent)
Copy constructor.
Definition at line 38 of file CLRenderInformationBase.cpp.
                                                                                                                 :
   CLBase(source),
   CCopasiContainer(source, pParent),
   mReferenceRenderInformation(source.mReferenceRenderInformation),
   mBackgroundColor(source.mBackgroundColor),
   mListOfColorDefinitions(source.mListOfColorDefinitions, this),
   mListOfGradientDefinitions(source.mListOfGradientDefinitions, this),
   mListOfLineEndings(source.mListOfLineEndings, this),
   mKey(""),
   mName(source.mName)
 {
 }
CLRenderInformationBase::CLRenderInformationBase (const RenderInformationBase & source, const std::string & name, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 54 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), mListOfColorDefinitions, mListOfGradientDefinitions, and mListOfLineEndings.
                               :
   CLBase(),
   CCopasiContainer(name, pParent),
   mReferenceRenderInformation(source.getReferenceRenderInformationId()),
   mBackgroundColor(source.getBackgroundColor()),
   mKey(""),
   mName(source.getName())
 {
   size_t i, iMax = source.getNumColorDefinitions();
   const ColorDefinition* pCD = NULL;
   CLColorDefinition* pLCD = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pCD = source.getColorDefinition((unsigned int) i);
       pLCD = new CLColorDefinition(*pCD);
       this->mListOfColorDefinitions.add(pLCD, true);
       //colorIdToKeyMap.insert(std::pair<std::string,std::string>(pCD->getId(),pLCD->getKey()));
     }
   const GradientBase* pGD = NULL;
   CLGradientBase* pLGD = NULL;
   iMax = source.getNumGradientDefinitions();
   for (i = 0; i < iMax; ++i)
     {
       pGD = source.getGradientDefinition((unsigned int) i);
       if (dynamic_cast<const LinearGradient*>(pGD))
         {
           pLGD = new CLLinearGradient(*static_cast<const LinearGradient*>(pGD));
           this->mListOfGradientDefinitions.add(pLGD, true);
         }
       else if (dynamic_cast<const RadialGradient*>(source.getGradientDefinition((unsigned int) i)))
         {
           pLGD = new CLRadialGradient(*static_cast<const RadialGradient*>(pGD));
           this->mListOfGradientDefinitions.add(pLGD, true);
         }
       //gradientIdToKeyMap.insert(std::pair<std::string,std::string>(pGD->getId(),pLGD->getKey()));
     }
   const LineEnding* pLE = NULL;
   CLLineEnding* pLLE = NULL;
   iMax = source.getNumLineEndings();
   for (i = 0; i < iMax; ++i)
     {
       pLE = source.getLineEnding((unsigned int) i);
       pLLE = new CLLineEnding(*pLE);
       this->mListOfLineEndings.add(pLLE, true);
       //lineEndingIdToKeyMap.insert(std::pair<std::string,std::string>(pLE->getId(),pLLE->getKey()));
     }
 }
CLRenderInformationBase::~CLRenderInformationBase ()
Destructor
Definition at line 124 of file CLRenderInformationBase.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(this->mKey);
 }
Member Function Documentation
void CLRenderInformationBase::addColorDefinition (const CLColorDefinition * pCD)
Adds a copy of the given color definition to the end of the list of color definitions.
Definition at line 212 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfColorDefinitions.
Referenced by CLRenderFlattener::flatten(), and CCopasiXMLParser::ColorDefinitionElement::start().
 {
   this->mListOfColorDefinitions.add(new CLColorDefinition(*pCD), true);
 }
void CLRenderInformationBase::addGradientDefinition (const CLGradientBase * pGradient)
Adds a copy of the given gradient definition to the end of the list of gradient definitions.
Definition at line 294 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfGradientDefinitions.
Referenced by CCopasiXMLParser::LinearGradientElement::end(), CCopasiXMLParser::RadialGradientElement::end(), and CLRenderFlattener::flatten().
 {
   if (dynamic_cast<const CLLinearGradient*>(pGradient))
     {
       this->mListOfGradientDefinitions.add(new CLLinearGradient(*static_cast<const CLLinearGradient*>(pGradient)), true);
     }
   else if (dynamic_cast<const CLRadialGradient*>(pGradient))
     {
       this->mListOfGradientDefinitions.add(new CLRadialGradient(*static_cast<const CLRadialGradient*>(pGradient)), true);
     }
 }
void CLRenderInformationBase::addLineEnding (const CLLineEnding * pLE)
Adds a copy of the given line ending to the end of the list of line endings.
Definition at line 373 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfLineEndings.
Referenced by CLRenderFlattener::flatten(), and CCopasiXMLParser::LineEndingElement::start().
 {
   this->mListOfLineEndings.add(new CLLineEnding(*pLE), true);
 }
void CLRenderInformationBase::addSBMLAttributes (RenderInformationBase * pBase) const
Adds the attributes for a graphical primitive 1D object to the passed in. object.
Definition at line 400 of file CLRenderInformationBase.cpp.
References getBackgroundColor(), getColorDefinition(), getGradientDefinition(), getKey(), getLineEnding(), getReferenceRenderInformationKey(), mListOfColorDefinitions, mListOfGradientDefinitions, mListOfLineEndings, mName, CCopasiVector< T >::size(), CLLineEnding::toSBML(), and CLColorDefinition::toSBML().
Referenced by CLLocalRenderInformation::toSBML(), and CLGlobalRenderInformation::toSBML().
 {
   pBase->setReferenceRenderInformationId(this->getReferenceRenderInformationKey());
   pBase->setBackgroundColor(this->getBackgroundColor());
   pBase->setId(getKey());
   if (!mName.empty())
     {
       pBase->setName(mName);
     }
   size_t i, iMax = this->mListOfColorDefinitions.size();
   int result;
   unsigned int level = pBase->getLevel();
   unsigned int version = pBase->getVersion();
   for (i = 0; i < iMax; ++i)
     {
       ColorDefinition* pCD = this->getColorDefinition(i)->toSBML(level, version);
       result = pBase->addColorDefinition(pCD);
       assert(result == LIBSBML_OPERATION_SUCCESS);
       //colorKeyToIdMap.insert(std::pair<std::string,std::string>(this->getColorDefinition(i)->getKey(),pCD->getId()));
       delete pCD;
     }
   iMax = this->mListOfGradientDefinitions.size();
   GradientBase* pGB = NULL;
   const CLGradientBase* pLGB = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pLGB = this->getGradientDefinition(i);
       if (dynamic_cast<const CLRadialGradient*>(pLGB))
         {
           pGB = static_cast<const CLRadialGradient*>(pLGB)->toSBML(level, version);
         }
       else
         {
           pGB = static_cast<const CLLinearGradient*>(pLGB)->toSBML(level, version);
         }
       result = pBase->addGradientDefinition(pGB);
       assert(result == LIBSBML_OPERATION_SUCCESS);
       //gradientKeyToIdMap.insert(std::pair<std::string,std::string>(pLGB->getKey(),pGB->getId()));
       delete pGB;
     }
   iMax = this->mListOfLineEndings.size();
   for (i = 0; i < iMax; ++i)
     {
       const CLLineEnding* lineEnding = this->getLineEnding(i);
       LineEnding* pLE = lineEnding->toSBML(level, version);
       result = pBase->addLineEnding(pLE);
       assert(result == LIBSBML_OPERATION_SUCCESS);
       //lineEndingKeyToIdMap.insert(std::pair<std::string,std::string>(this->getLineEnding(i)->getKey(),pLE->getId()));
       delete pLE;
     }
 }
CLColorDefinition * CLRenderInformationBase::createColorDefinition ()
Creates a new color definition.
Definition at line 190 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfColorDefinitions.
Referenced by test000097::addGlobalRenderInformation(), and test000097::addLocalRenderInformation().
 {
   CLColorDefinition* pCD = new CLColorDefinition();
   this->mListOfColorDefinitions.add(pCD, true);
   return pCD;
 }
CLLinearGradient * CLRenderInformationBase::createLinearGradientDefinition ()
Creates a new linear gradient definition.
Definition at line 272 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfGradientDefinitions.
 {
   CLLinearGradient* pLG = new CLLinearGradient();
   this->mListOfGradientDefinitions.add(pLG, true);
   return pLG;
 }
CLLineEnding * CLRenderInformationBase::createLineEnding ()
Creates a new line ending.
Definition at line 351 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfLineEndings.
 {
   CLLineEnding* pLE = new CLLineEnding();
   this->mListOfLineEndings.add(pLE, true);
   return pLE;
 }
CLRadialGradient * CLRenderInformationBase::createRadialGradientDefinition ()
Creates a new radial gradient definition.
Definition at line 262 of file CLRenderInformationBase.cpp.
References CCopasiVector< T >::add(), and mListOfGradientDefinitions.
 {
   CLRadialGradient* pRG = new CLRadialGradient();
   this->mListOfGradientDefinitions.add(pRG, true);
   return pRG;
 }
const std::string & CLRenderInformationBase::getBackgroundColor () const
Returns the background color which is either the id of a color in the list of color definitions, or a color value.
Definition at line 378 of file CLRenderInformationBase.cpp.
References mBackgroundColor.
Referenced by addSBMLAttributes(), CQLayoutScene::fillFromLayout(), CCopasiXML::saveRenderInformationAttributes(), and CLRenderResolver::setBackgroundColor().
 {
   return mBackgroundColor;
 }
CLColorDefinition * CLRenderInformationBase::getColorDefinition (size_t index)
Returns a pointer to the color definition with the given index, or NULL if the index is invalid.
Definition at line 173 of file CLRenderInformationBase.cpp.
References mListOfColorDefinitions, and CCopasiVector< T >::size().
Referenced by addSBMLAttributes(), CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
 {
   return (index < this->mListOfColorDefinitions.size()) ? this->mListOfColorDefinitions[index] : NULL;
 }
const CLColorDefinition * CLRenderInformationBase::getColorDefinition (size_t index) const
Returns a const pointer to the color definition with the given index, or NULL if the index is invalid.
Definition at line 182 of file CLRenderInformationBase.cpp.
References mListOfColorDefinitions, and CCopasiVector< T >::size().
 {
   return (index < this->mListOfColorDefinitions.size()) ? this->mListOfColorDefinitions[index] : NULL;
 }
CLGradientBase * CLRenderInformationBase::getGradientDefinition (size_t index)
Returns a pointer to the gradient definition with the given index, or NULL if the index is invalid.
Definition at line 245 of file CLRenderInformationBase.cpp.
References mListOfGradientDefinitions, and CCopasiVector< T >::size().
Referenced by addSBMLAttributes(), CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
 {
   return (index < this->mListOfGradientDefinitions.size()) ? this->mListOfGradientDefinitions[index] : NULL;
 }
const CLGradientBase * CLRenderInformationBase::getGradientDefinition (size_t index) const
Returns a const pointer to the gradient definition with the given index, or NULL if the index is invalid.
Definition at line 254 of file CLRenderInformationBase.cpp.
References mListOfGradientDefinitions, and CCopasiVector< T >::size().
 {
   return (index < this->mListOfGradientDefinitions.size()) ? this->mListOfGradientDefinitions[index] : NULL;
 }
const std::string & CLRenderInformationBase::getKey () const virtual
Returns the key of the render infomation object
Returns the key of the color definition.
Reimplemented from CCopasiObject.
Definition at line 391 of file CLRenderInformationBase.cpp.
References mKey.
Referenced by CQNewMainWindow::addDefaultRenderInfoItemsToList(), CQNewMainWindow::addGlobalRenderInfoItemsToList(), addSBMLAttributes(), SBMLDocumentLoader::createLayout(), SBMLDocumentLoader::readListOfLayouts(), CCopasiXML::saveRenderInformationAttributes(), CQLayoutView::slotLayoutChanged(), updateRenderInformationList(), and CQNewMainWindow::updateRenderInformationList().
 {
   return this->mKey;
 }
CLLineEnding * CLRenderInformationBase::getLineEnding (size_t index)
Returns a pointer to the line ending with the given index, or NULL if the index is invalid.
Definition at line 334 of file CLRenderInformationBase.cpp.
References mListOfLineEndings, and CCopasiVector< T >::size().
Referenced by addSBMLAttributes(), CLRenderResolver::fill_base_maps(), CCopasiXML::saveRenderInformationDefinitionElements(), and CCopasiXMLParser::LineEndingElement::start().
 {
   return (index < this->mListOfLineEndings.size()) ? this->mListOfLineEndings[index] : NULL;
 }
const CLLineEnding * CLRenderInformationBase::getLineEnding (size_t index) const
Returns a const pointer to the line ending with the given index, or NULL if the index is invalid.
Definition at line 343 of file CLRenderInformationBase.cpp.
References mListOfLineEndings, and CCopasiVector< T >::size().
 {
   return (index < this->mListOfLineEndings.size()) ? this->mListOfLineEndings[index] : NULL;
 }
CCopasiVector< CLColorDefinition > * CLRenderInformationBase::getListOfColorDefinitions ()
Returns a pointer to the list of color definitions.
Definition at line 156 of file CLRenderInformationBase.cpp.
References mListOfColorDefinitions.
 {
   return &(this->mListOfColorDefinitions);
 }
const CCopasiVector< CLColorDefinition > * CLRenderInformationBase::getListOfColorDefinitions () const
Returns a const pointer to the list of color definitions.
Definition at line 164 of file CLRenderInformationBase.cpp.
References mListOfColorDefinitions.
 {
   return &(this->mListOfColorDefinitions);
 }
CCopasiVector< CLGradientBase > * CLRenderInformationBase::getListOfGradientDefinitions ()
Returns a pointer to the list of gradient definitions.
Definition at line 228 of file CLRenderInformationBase.cpp.
References mListOfGradientDefinitions.
 {
   return &(this->mListOfGradientDefinitions);
 }
const CCopasiVector< CLGradientBase > * CLRenderInformationBase::getListOfGradientDefinitions () const
Returns a const pointer to the list of gradient definitions.
Definition at line 236 of file CLRenderInformationBase.cpp.
References mListOfGradientDefinitions.
 {
   return &(this->mListOfGradientDefinitions);
 }
CCopasiVector< CLLineEnding > * CLRenderInformationBase::getListOfLineEndings ()
Returns a pointer to the list of line endings.
Definition at line 317 of file CLRenderInformationBase.cpp.
References mListOfLineEndings.
 {
   return &(this->mListOfLineEndings);
 }
const CCopasiVector< CLLineEnding > * CLRenderInformationBase::getListOfLineEndings () const
Returns a const pointer to the list of line endings.
Definition at line 325 of file CLRenderInformationBase.cpp.
References mListOfLineEndings.
 {
   return &(this->mListOfLineEndings);
 }
const std::string & CLRenderInformationBase::getName () const
Returns the id of the object.
Returns the name of the object.
Definition at line 479 of file CLRenderInformationBase.cpp.
References mName.
Referenced by CQNewMainWindow::addDefaultRenderInfoItemsToList(), CQNewMainWindow::addGlobalRenderInfoItemsToList(), CCopasiXML::saveRenderInformationAttributes(), CQLayoutView::slotLayoutChanged(), updateRenderInformationList(), and CQNewMainWindow::updateRenderInformationList().
 {
   return this->mName;
 }
size_t CLRenderInformationBase::getNumColorDefinitions () const
Returns the number of color definitions.
Definition at line 148 of file CLRenderInformationBase.cpp.
References mListOfColorDefinitions, and CCopasiVector< T >::size().
Referenced by CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
 {
   return this->mListOfColorDefinitions.size();
 }
size_t CLRenderInformationBase::getNumGradientDefinitions () const
Returns the number of gradient definitions.
Definition at line 220 of file CLRenderInformationBase.cpp.
References mListOfGradientDefinitions, and CCopasiVector< T >::size().
Referenced by CLRenderResolver::fill_base_maps(), and CCopasiXML::saveRenderInformationDefinitionElements().
 {
   return this->mListOfGradientDefinitions.size();
 }
size_t CLRenderInformationBase::getNumLineEndings () const
Returns the number of line endings.
Definition at line 309 of file CLRenderInformationBase.cpp.
References mListOfLineEndings, and CCopasiVector< T >::size().
Referenced by CLRenderResolver::fill_base_maps(), CCopasiXML::saveRenderInformationDefinitionElements(), and CCopasiXMLParser::LineEndingElement::start().
 {
   return this->mListOfLineEndings.size();
 }
const std::string & CLRenderInformationBase::getReferenceRenderInformationKey () const
Returns the key of the referenced render information object..
Returns the id of the referenced render information object..
Definition at line 132 of file CLRenderInformationBase.cpp.
References mReferenceRenderInformation.
Referenced by addSBMLAttributes(), CLRenderFlattener::flatten(), and CCopasiXML::saveRenderInformationAttributes().
 {
   return this->mReferenceRenderInformation;
 }
CLRenderInformationBase& CLRenderInformationBase::operator= (const CLRenderInformationBase & source) private
void CLRenderInformationBase::removeColorDefinition (size_t index)
Removes the color definition with the given index.
Definition at line 200 of file CLRenderInformationBase.cpp.
References mListOfColorDefinitions, CCopasiVector< T >::remove(), and CCopasiVector< T >::size().
 {
   if (index < this->mListOfColorDefinitions.size())
     {
       this->mListOfColorDefinitions.remove(index);
     }
 }
void CLRenderInformationBase::removeGradientDefinition (size_t index)
Removes the gradient definition with the given index.
Definition at line 282 of file CLRenderInformationBase.cpp.
References mListOfGradientDefinitions, CCopasiVector< T >::remove(), and CCopasiVector< T >::size().
 {
   if (index < this->mListOfGradientDefinitions.size())
     {
       this->mListOfGradientDefinitions.remove(index);
     }
 }
void CLRenderInformationBase::removeLineEnding (size_t index)
Removes the line ending with the given index.
Definition at line 361 of file CLRenderInformationBase.cpp.
References mListOfLineEndings, CCopasiVector< T >::remove(), and CCopasiVector< T >::size().
 {
   if (index < this->mListOfLineEndings.size())
     {
       this->mListOfLineEndings.remove(index);
     }
 }
void CLRenderInformationBase::setBackgroundColor (const std::string & bg)
Sets the background color to either the id of a color in the list of color definitions, or a color value.
Definition at line 383 of file CLRenderInformationBase.cpp.
References mBackgroundColor.
Referenced by CLRenderFlattener::flatten(), CCopasiXMLParser::LocalRenderInformationElement::start(), and CCopasiXMLParser::GlobalRenderInformationElement::start().
 {
   this->mBackgroundColor = bg;
 }
void CLRenderInformationBase::setName (const std::string & name)
Sets the id of the object.
Sets the name of the object.
Definition at line 471 of file CLRenderInformationBase.cpp.
References mName.
Referenced by test000097::addGlobalRenderInformation(), and test000097::addLocalRenderInformation().
 {
   this->mName = name;
 }
void CLRenderInformationBase::setReferenceRenderInformationKey (const std::string & key)
Sets the key of the referenced render information object.
Sets the id of the referenced render information object.
Definition at line 140 of file CLRenderInformationBase.cpp.
References mReferenceRenderInformation.
 {
   this->mReferenceRenderInformation = key;
 }
Member Data Documentation
std::string CLRenderInformationBase::mBackgroundColor protected
Definition at line 39 of file CLRenderInformationBase.h.
Referenced by getBackgroundColor(), and setBackgroundColor().
std::string CLRenderInformationBase::mKey protected
key string for the render information.
Definition at line 47 of file CLRenderInformationBase.h.
Referenced by CLGlobalRenderInformation::CLGlobalRenderInformation(), CLLocalRenderInformation::CLLocalRenderInformation(), getKey(), and ~CLRenderInformationBase().
CCopasiVector<CLColorDefinition> CLRenderInformationBase::mListOfColorDefinitions protected
Definition at line 40 of file CLRenderInformationBase.h.
Referenced by addColorDefinition(), addSBMLAttributes(), CLRenderInformationBase(), createColorDefinition(), getColorDefinition(), getListOfColorDefinitions(), getNumColorDefinitions(), and removeColorDefinition().
CCopasiVector<CLGradientBase> CLRenderInformationBase::mListOfGradientDefinitions protected
Definition at line 41 of file CLRenderInformationBase.h.
Referenced by addGradientDefinition(), addSBMLAttributes(), CLRenderInformationBase(), createLinearGradientDefinition(), createRadialGradientDefinition(), getGradientDefinition(), getListOfGradientDefinitions(), getNumGradientDefinitions(), and removeGradientDefinition().
CCopasiVector<CLLineEnding> CLRenderInformationBase::mListOfLineEndings protected
Definition at line 42 of file CLRenderInformationBase.h.
Referenced by addLineEnding(), addSBMLAttributes(), CLRenderInformationBase(), createLineEnding(), getLineEnding(), getListOfLineEndings(), getNumLineEndings(), and removeLineEnding().
std::string CLRenderInformationBase::mName protected
The name of the render information, which is more informative than the key.
Definition at line 53 of file CLRenderInformationBase.h.
Referenced by addSBMLAttributes(), getName(), and setName().
std::string CLRenderInformationBase::mReferenceRenderInformation protected
Definition at line 38 of file CLRenderInformationBase.h.
Referenced by getReferenceRenderInformationKey(), and setReferenceRenderInformationKey().
The documentation for this class was generated from the following files:
CLRenderInformationBase.h
CLRenderInformationBase.cpp