COPASI API: CModelParameterReactionParameter Class Reference
CModelParameterReactionParameter Class Reference
#include <CModelParameter.h>
Public Member Functions
CModelParameterReactionParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::ReactionParameter)
CModelParameterReactionParameter (const CModelParameterReactionParameter &src, CModelParameterGroup *pParent)
virtual void compile ()
const CRegisteredObjectName & getGlobalQuantityCN () const
const CReaction * getReaction () const
void setGlobalQuantityCN (const std::string &globalQuantityCN)
virtual ~CModelParameterReactionParameter ()
Public Member Functions inherited from CModelParameter
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
virtual const CompareResult & diff (const CModelParameter &other, const CModelParameter::Framework &framework=ParticleNumbers, const bool &createMissing=false)
virtual const CModelParameter * getChild (const size_t &index) const
const CCopasiObjectName & getCN () const
const CompareResult & getCompareResult () const
size_t getIndex () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
virtual std::string getName () const
virtual size_t getNumChildren () const
CCopasiObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
const std::string getUnit (const Framework &framework) const
virtual const double & getValue (const Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
virtual bool refreshFromModel (const bool &modifyExistence)
virtual void setCN (const CCopasiObjectName &cn)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const double &value, const Framework &framework)
virtual bool updateModel ()
virtual ~CModelParameter ()
Private Attributes
CRegisteredObjectName mGlobalQuantityCN
CModelParameter * mpGlobalQuantity
CReaction * mpReaction
Additional Inherited Members
Public Types inherited from CModelParameter
enum CompareResult {
Obsolete, Missing, Modified, Conflict,
Identical
}
enum Framework { Concentration = 0, ParticleNumbers }
enum Type {
Model, Compartment, Species, ModelValue,
ReactionParameter, Reaction, Group, Set,
unknown
}
Static Public Attributes inherited from CModelParameter
static const char * TypeNames []
Static Protected Member Functions inherited from CModelParameter
static std::string nameFromCN (const CCopasiObjectName &cn)
Protected Attributes inherited from CModelParameter
CRegisteredObjectName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CCopasiObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Detailed Description
Definition at line 428 of file CModelParameter.h.
Constructor & Destructor Documentation
CModelParameterReactionParameter::CModelParameterReactionParameter (CModelParameterGroup * pParent, const CModelParameter::Type & type = CModelParameter::ReactionParameter)
Constructor
Definition at line 874 of file CModelParameter.cpp.
                                                                                                                                   :
   CModelParameter(pParent, type),
   mpReaction(NULL),
   mGlobalQuantityCN(),
   mpGlobalQuantity(NULL)
 {}
CModelParameterReactionParameter::CModelParameterReactionParameter (const CModelParameterReactionParameter & src, CModelParameterGroup * pParent)
Copy constructor
Definition at line 881 of file CModelParameter.cpp.
                                                                                                                                               :
   CModelParameter(src, pParent),
   mpReaction(NULL),
   mGlobalQuantityCN(src.mGlobalQuantityCN),
   mpGlobalQuantity(NULL)
 {}
CModelParameterReactionParameter::~CModelParameterReactionParameter () virtual
Destructor
Definition at line 889 of file CModelParameter.cpp.
 {}
Member Function Documentation
void CModelParameterReactionParameter::compile () virtual
Compile the parameter
Reimplemented from CModelParameter.
Definition at line 893 of file CModelParameter.cpp.
References CModelEntity::ASSIGNMENT, CModelParameter::compile(), CModelEntity::FIXED, CModelParameter::getCN(), CModelParameter::getInitialExpression(), CModelParameter::getModel(), CModelParameterGroup::getModelParameter(), CCopasiObject::getObjectDataModel(), CCopasiObjectName::getObjectType(), CCopasiObjectName::getPrimary(), CCopasiObjectName::getRemainder(), CModelParameter::getSet(), CModelParameter::getValue(), mGlobalQuantityCN, mpGlobalQuantity, CModelParameter::mpParent, mpReaction, CModelParameter::mValue, CCopasiDataModel::ObjectFromName(), CModelParameter::ParticleNumbers, and CModelParameter::setSimulationType().
Referenced by setGlobalQuantityCN().
 {
   CModelParameter::compile();
   mGlobalQuantityCN = std::string();
   std::string Infix = getInitialExpression();
   if (Infix.length() > 2)
     {
       // Infix: <CN,Reference=InitialValue> or <CN,Reference=Value>
       CCopasiObjectName Tmp = Infix.substr(1, Infix.length() - 2);
       std::string Separator = "";
       for (; Tmp != ""; Tmp = Tmp.getRemainder())
         {
           CCopasiObjectName Primary = Tmp.getPrimary();
           if (Primary.getObjectType() == "Reference")
             {
               break;
             }
           mGlobalQuantityCN += Separator + Primary;
           Separator = ",";
         }
       setSimulationType(CModelEntity::ASSIGNMENT);
     }
   else
     {
       setSimulationType(CModelEntity::FIXED);
     }
   mpGlobalQuantity = this->getSet()->getModelParameter(mGlobalQuantityCN);
   if (mpGlobalQuantity != NULL)
     {
       mValue = mpGlobalQuantity->getValue(ParticleNumbers);
     }
   std::vector< CCopasiContainer * > ListOfContainer;
   CModel * pModel = getModel();
   ListOfContainer.push_back(pModel);
   mpReaction = static_cast< CReaction * >(pModel->getObjectDataModel()->ObjectFromName(ListOfContainer, mpParent->getCN()));
 }
const CRegisteredObjectName & CModelParameterReactionParameter::getGlobalQuantityCN () const
Retrieve the CN of the assigned global quantity
Returns
const CRegisteredObjectName & globalQuantityCN
Definition at line 961 of file CModelParameter.cpp.
References mGlobalQuantityCN.
 {
   return mGlobalQuantityCN;
 }
const CReaction * CModelParameterReactionParameter::getReaction () const
Retrieve a pointer to the reaction the parameter belongs to.
Returns
const CReaction * reaction
Definition at line 942 of file CModelParameter.cpp.
References mpReaction.
 {
   return mpReaction;
 }
void CModelParameterReactionParameter::setGlobalQuantityCN (const std::string & globalQuantityCN)
Set the CN of the assigned global quantity. If the CN is empty the assignment is removed.
Parameters
const std::string & globalQuantityCN
Definition at line 947 of file CModelParameter.cpp.
References compile(), and CModelParameter::setInitialExpression().
 {
   if (globalQuantityCN == "")
     {
       setInitialExpression("");
     }
   else
     {
       setInitialExpression("<" + globalQuantityCN + ">");
     }
   compile();
 }
Member Data Documentation
CRegisteredObjectName CModelParameterReactionParameter::mGlobalQuantityCN private
The CN of the assigned global quantity.
Definition at line 479 of file CModelParameter.h.
Referenced by compile(), and getGlobalQuantityCN().
CModelParameter* CModelParameterReactionParameter::mpGlobalQuantity private
A pointer to the parameter representing the assigned global quantity.
Definition at line 484 of file CModelParameter.h.
Referenced by compile().
CReaction* CModelParameterReactionParameter::mpReaction private
A pointer to the reaction the parameter belongs to.
Definition at line 474 of file CModelParameter.h.
Referenced by compile(), and getReaction().
The documentation for this class was generated from the following files:
CModelParameter.h
CModelParameter.cpp