COPASI API: CLRectangle Class Reference
CLRectangle Class Reference
#include <CLRectangle.h>
Public Member Functions
CLRectangle (CCopasiContainer *pParent=NULL)
CLRectangle (const CLRectangle &source, CCopasiContainer *pParent=NULL)
CLRectangle (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z, const CLRelAbsVector &w, const CLRelAbsVector &h, CCopasiContainer *pParent=NULL)
CLRectangle (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &w, const CLRelAbsVector &h, CCopasiContainer *pParent=NULL)
CLRectangle (const sbmlRectangle &source, CCopasiContainer *pParent=NULL)
const CLRelAbsVector & getHeight () const
CLRelAbsVector & getHeight ()
const std::string & getKey () const
const CLRelAbsVector & getRadiusX () const
CLRelAbsVector & getRadiusX ()
const CLRelAbsVector & getRadiusY () const
CLRelAbsVector & getRadiusY ()
const CLRelAbsVector & getWidth () const
CLRelAbsVector & getWidth ()
const CLRelAbsVector & getX () const
CLRelAbsVector & getX ()
const CLRelAbsVector & getY () const
CLRelAbsVector & getY ()
const CLRelAbsVector & getZ () const
CLRelAbsVector & getZ ()
void setCoordinates (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z)
void setCoordinatesAndSize (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z, const CLRelAbsVector &w, const CLRelAbsVector &h)
void setHeight (const CLRelAbsVector &h)
void setRadii (const CLRelAbsVector &rx, const CLRelAbsVector &ry)
void setRadiusX (const CLRelAbsVector &rx)
void setRadiusY (const CLRelAbsVector &ry)
void setSize (const CLRelAbsVector &w, const CLRelAbsVector &h)
void setWidth (const CLRelAbsVector &w)
void setX (const CLRelAbsVector &x)
void setY (const CLRelAbsVector &y)
void setZ (const CLRelAbsVector &z)
sbmlRectangle * toSBML (unsigned int level, unsigned int version) const
~CLRectangle ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CLRelAbsVector mHeight
std::string mKey
CLRelAbsVector mRX
CLRelAbsVector mRY
CLRelAbsVector mWidth
CLRelAbsVector mX
CLRelAbsVector mY
CLRelAbsVector mZ
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Private Member Functions
CLRectangle & operator= (const CLRectangle &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET, NONZERO, EVENODD, INHERIT }
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 24 of file CLRectangle.h.
Constructor & Destructor Documentation
CLRectangle::CLRectangle (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 25 of file CLRectangle.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                  :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Rectangle", pParent),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Rectangle", this);
 }
CLRectangle::CLRectangle (const CLRectangle & source, CCopasiContainer * pParent = NULL)
Copy Constructor.
Definition at line 36 of file CLRectangle.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                                             :
     CLGraphicalPrimitive2D(source),
     CCopasiObject(source, pParent),
     mX(source.mX),
     mY(source.mY),
     mZ(source.mZ),
     mWidth(source.mWidth),
     mHeight(source.mHeight),
     mRX(source.mRX),
     mRY(source.mRY),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Rectangle", this);
 }
CLRectangle::CLRectangle (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z, const CLRelAbsVector & w, const CLRelAbsVector & h, CCopasiContainer * pParent = NULL)
Constructor that takes x, y and z coordinate values, the width and the height.
Constructor that takes an id, the x, y and z coordinate values, the width and the height.
Definition at line 55 of file CLRectangle.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                                                                                                                                               :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Rectangle", pParent),
     mX(x),
     mY(y),
     mZ(z),
     mWidth(w),
     mHeight(h),
     mRX(CLRelAbsVector(0.0, 0.0)),
     mRY(CLRelAbsVector(0.0, 0.0)),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Rectangle", this);
 }
CLRectangle::CLRectangle (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & w, const CLRelAbsVector & h, CCopasiContainer * pParent = NULL)
Constructor that takes x and y coordinate values, the width and the height.
Constructor that takes an id, x and y coordinate values, the width and the height.
Definition at line 74 of file CLRectangle.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                                                                                                                      :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Rectangle", pParent),
     mX(x),
     mY(y),
     mZ(CLRelAbsVector(0.0, 0.0)),
     mWidth(w),
     mHeight(h),
     mRX(CLRelAbsVector(0.0, 0.0)),
     mRY(CLRelAbsVector(0.0, 0.0)),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Rectangle", this);
 }
CLRectangle::CLRectangle (const sbmlRectangle & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
CLRectangle::~CLRectangle ()
Destructor.
Destructor
Definition at line 110 of file CLRectangle.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(this->mKey);
 }
Member Function Documentation
const CLRelAbsVector & CLRectangle::getHeight () const
Returns the height.
Definition at line 187 of file CLRectangle.cpp.
References mHeight.
Referenced by CLLayoutRenderer::draw_rectangle(), fillItemFromRectangle(), getPath(), and CCopasiXML::saveRectangleElement().
 {
   return this->mHeight;
 }
CLRelAbsVector & CLRectangle::getHeight ()
Returns the height.
Definition at line 243 of file CLRectangle.cpp.
References mHeight.
 {
   return this->mHeight;
 }
const std::string & CLRectangle::getKey () const virtual
Returns the key string of the object.
Returns the key of the rectangle
Reimplemented from CCopasiObject.
Definition at line 323 of file CLRectangle.cpp.
References mKey.
 {
   return this->mKey;
 }
const CLRelAbsVector & CLRectangle::getRadiusX () const
Returns the corner radius along th x axis.
Definition at line 195 of file CLRectangle.cpp.
References mRX.
Referenced by CLLayoutRenderer::draw_rectangle(), fillItemFromRectangle(), getPath(), and CCopasiXML::saveRectangleElement().
 {
   return this->mRX;
 }
CLRelAbsVector & CLRectangle::getRadiusX ()
Returns the corner radius along th x axis.
Definition at line 251 of file CLRectangle.cpp.
References mRX.
 {
   return this->mRX;
 }
const CLRelAbsVector & CLRectangle::getRadiusY () const
Returns the corner radius along the y axis.
Definition at line 203 of file CLRectangle.cpp.
References mRY.
Referenced by CLLayoutRenderer::draw_rectangle(), fillItemFromRectangle(), getPath(), and CCopasiXML::saveRectangleElement().
 {
   return this->mRY;
 }
CLRelAbsVector & CLRectangle::getRadiusY ()
Returns the corner radius along the y axis.
Definition at line 259 of file CLRectangle.cpp.
References mRY.
 {
   return this->mRY;
 }
const CLRelAbsVector & CLRectangle::getWidth () const
Returns the width.
Definition at line 179 of file CLRectangle.cpp.
References mWidth.
Referenced by CLLayoutRenderer::draw_rectangle(), fillItemFromRectangle(), getPath(), and CCopasiXML::saveRectangleElement().
 {
   return this->mWidth;
 }
CLRelAbsVector & CLRectangle::getWidth ()
Returns the width.
Definition at line 235 of file CLRectangle.cpp.
References mWidth.
 {
   return this->mWidth;
 }
const CLRelAbsVector & CLRectangle::getX () const
Returns the x coordinate.
Definition at line 155 of file CLRectangle.cpp.
References mX.
Referenced by CLLayoutRenderer::draw_rectangle(), fillItemFromRectangle(), getPath(), and CCopasiXML::saveRectangleElement().
 {
   return this->mX;
 }
CLRelAbsVector & CLRectangle::getX ()
Returns the x coordinate.
Definition at line 211 of file CLRectangle.cpp.
References mX.
 {
   return this->mX;
 }
const CLRelAbsVector & CLRectangle::getY () const
Returns the y coordinate.
Definition at line 163 of file CLRectangle.cpp.
References mY.
Referenced by CLLayoutRenderer::draw_rectangle(), fillItemFromRectangle(), getPath(), and CCopasiXML::saveRectangleElement().
 {
   return this->mY;
 }
CLRelAbsVector & CLRectangle::getY ()
Returns the y coordinate.
Definition at line 219 of file CLRectangle.cpp.
References mY.
 {
   return this->mY;
 }
const CLRelAbsVector & CLRectangle::getZ () const
Returns the z coordinate.
Definition at line 171 of file CLRectangle.cpp.
References mZ.
Referenced by CLLayoutRenderer::draw_rectangle(), and CCopasiXML::saveRectangleElement().
 {
   return this->mZ;
 }
CLRelAbsVector & CLRectangle::getZ ()
Returns the z coordinate.
Definition at line 227 of file CLRectangle.cpp.
References mZ.
 {
   return this->mZ;
 }
CLRectangle& CLRectangle::operator= (const CLRectangle & source) private
void CLRectangle::setCoordinates (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z)
Sets the position.
Definition at line 127 of file CLRectangle.cpp.
References mX, mY, and mZ.
Referenced by setCoordinatesAndSize().
 {
   this->mX = x;
   this->mY = y;
   this->mZ = z;
 }
void CLRectangle::setCoordinatesAndSize (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z, const CLRelAbsVector & w, const CLRelAbsVector & h)
Sets the position, the width and the height.
Definition at line 118 of file CLRectangle.cpp.
References setCoordinates(), and setSize().
Referenced by CCopasiXMLParser::RectangleElement::start().
 {
   this->setCoordinates(x, y, z);
   this->setSize(w, h);
 }
void CLRectangle::setHeight (const CLRelAbsVector & h)
Sets the height.
Definition at line 275 of file CLRectangle.cpp.
References mHeight.
 {
   this->mHeight = h;
 }
void CLRectangle::setRadii (const CLRelAbsVector & rx, const CLRelAbsVector & ry)
Sets the corner radii.
Sets the size.
Definition at line 146 of file CLRectangle.cpp.
References mRX, and mRY.
Referenced by CCopasiXMLParser::RectangleElement::start().
 {
   this->mRX = rx;
   this->mRY = ry;
 }
void CLRectangle::setRadiusX (const CLRelAbsVector & rx)
Sets the x radius for the corners.
Definition at line 283 of file CLRectangle.cpp.
References mRX.
 {
   this->mRX = rx;
 }
void CLRectangle::setRadiusY (const CLRelAbsVector & ry)
Sets the y radius for the corners.
Definition at line 291 of file CLRectangle.cpp.
References mRY.
 {
   this->mRY = ry;
 }
void CLRectangle::setSize (const CLRelAbsVector & w, const CLRelAbsVector & h)
Sets the size.
Definition at line 137 of file CLRectangle.cpp.
References mHeight, and mWidth.
Referenced by setCoordinatesAndSize().
 {
   this->mWidth = w;
   this->mHeight = h;
 }
void CLRectangle::setWidth (const CLRelAbsVector & w)
Sets the width.
Definition at line 267 of file CLRectangle.cpp.
References mWidth.
 {
   this->mWidth = w;
 }
void CLRectangle::setX (const CLRelAbsVector & x)
Sets the x position.
Definition at line 299 of file CLRectangle.cpp.
References mX.
 {
   this->mX = x;
 }
void CLRectangle::setY (const CLRelAbsVector & y)
Sets the y position.
Definition at line 307 of file CLRectangle.cpp.
References mY.
 {
   this->mY = y;
 }
void CLRectangle::setZ (const CLRelAbsVector & z)
Sets the z position.
Definition at line 315 of file CLRectangle.cpp.
References mZ.
 {
   this->mZ = z;
 }
Rectangle * CLRectangle::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
Definition at line 331 of file CLRectangle.cpp.
References CLGraphicalPrimitive2D::addSBMLAttributes(), mHeight, mRX, mRY, mWidth, mX, mY, mZ, and CLRelAbsVector::toSBML().
 {
   Rectangle* pRectangle = new Rectangle(level, version);
   RelAbsVector* pV1 = this->mX.toSBML();
   RelAbsVector* pV2 = this->mY.toSBML();
   RelAbsVector* pV3 = this->mZ.toSBML();
   RelAbsVector* pV4 = this->mWidth.toSBML();
   RelAbsVector* pV5 = this->mHeight.toSBML();
   pRectangle->setCoordinatesAndSize(*pV1, *pV2, *pV3, *pV4, *pV5);
   delete pV1;
   delete pV2;
   delete pV3;
   delete pV4;
   delete pV5;
   this->addSBMLAttributes(pRectangle);
   pV1 = this->mRX.toSBML();
   pV2 = this->mRY.toSBML();
   pRectangle->setRadii(*pV1, *pV2);
   delete pV1;
   delete pV2;
   return pRectangle;
 }
Member Data Documentation
CLRelAbsVector CLRectangle::mHeight protected
Definition at line 35 of file CLRectangle.h.
Referenced by getHeight(), setHeight(), setSize(), and toSBML().
std::string CLRectangle::mKey protected
key for the object.
Definition at line 42 of file CLRectangle.h.
Referenced by CLRectangle(), getKey(), and ~CLRectangle().
CLRelAbsVector CLRectangle::mRX protected
Definition at line 36 of file CLRectangle.h.
Referenced by getRadiusX(), setRadii(), setRadiusX(), and toSBML().
CLRelAbsVector CLRectangle::mRY protected
Definition at line 37 of file CLRectangle.h.
Referenced by getRadiusY(), setRadii(), setRadiusY(), and toSBML().
CLRelAbsVector CLRectangle::mWidth protected
Definition at line 34 of file CLRectangle.h.
Referenced by getWidth(), setSize(), setWidth(), and toSBML().
CLRelAbsVector CLRectangle::mX protected
Definition at line 31 of file CLRectangle.h.
Referenced by getX(), setCoordinates(), setX(), and toSBML().
CLRelAbsVector CLRectangle::mY protected
Definition at line 32 of file CLRectangle.h.
Referenced by getY(), setCoordinates(), setY(), and toSBML().
CLRelAbsVector CLRectangle::mZ protected
Definition at line 33 of file CLRectangle.h.
Referenced by getZ(), setCoordinates(), setZ(), and toSBML().
The documentation for this class was generated from the following files:
CLRectangle.h
CLRectangle.cpp