COPASI API: DefaultPlotDialog Class Reference
DefaultPlotDialog Class Reference
#include <DefaultplotDialog.h>
Public Slots
virtual void setTask (CCopasiTask *t)
Public Member Functions
DefaultPlotDialog (QWidget *parent=0, const char *name=0, bool modal=false, Qt::WindowFlags fl=0)
~DefaultPlotDialog ()
Protected Slots
virtual void slotCreate ()
connected to create button
virtual void slotSelect ()
called when selection in listbox is changed
virtual void slotToggleAll (bool flag)
connected to check box
Protected Member Functions
void fillList ()
Protected Attributes
int mIndex
std::vector< C_INT32 > mList
CCopasiTask * mpTask
Detailed Description
Definition at line 28 of file DefaultplotDialog.h.
Constructor & Destructor Documentation
DefaultPlotDialog::DefaultPlotDialog (QWidget * parent = 0, const char * name = 0, bool modal = false, Qt::WindowFlags fl = 0)
Definition at line 29 of file DefaultplotDialog.cpp.
     : QDialog(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   setupUi(this);
 }
DefaultPlotDialog::~DefaultPlotDialog ()
Definition at line 40 of file DefaultplotDialog.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void DefaultPlotDialog::fillList () protected
Definition at line 66 of file DefaultplotDialog.cpp.
References FROM_UTF8, COutputAssistant::getItemName(), COutputAssistant::getListOfDefaultOutputDescriptions(), mList, and mpTask.
Referenced by setTask(), and slotToggleAll().
 {
   if (mpCheckAll->isChecked())
     mList = COutputAssistant::getListOfDefaultOutputDescriptions(NULL); //this gets the complete list
   else
     mList = COutputAssistant::getListOfDefaultOutputDescriptions(mpTask); //only the items fitting the task
   listBox->clear();
   std::vector<C_INT32>::const_iterator it, itEnd = mList.end();
   QStringList Items;
   for (it = mList.begin(); it != itEnd; ++it)
     {
       QString Name = FROM_UTF8(COutputAssistant::getItemName(*it));
       if (!Name.startsWith("--")) Name = "   " + Name;
       Items.append(Name);
     }
   listBox->insertItems(0, Items);
   listBox->item(0)->setSelected(true);
 }
void DefaultPlotDialog::setTask (CCopasiTask * t) virtual slot
Definition at line 59 of file DefaultplotDialog.cpp.
References fillList(), and mpTask.
Referenced by TaskWidget::assistantBtnClicked().
 {
   mpTask = t;
   fillList();
 }
void DefaultPlotDialog::slotCreate () protected virtual slot
connected to create button
Definition at line 45 of file DefaultplotDialog.cpp.
References COutputAssistant::createDefaultOutput(), CCopasiRootContainer::getDatamodelList(), mIndex, and mpTask.
 {
   if (!mpTask) return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (COutputAssistant::createDefaultOutput(mIndex, mpTask, pDataModel))
     this->accept();
   else
     this->reject();
 }
void DefaultPlotDialog::slotSelect () protected virtual slot
called when selection in listbox is changed
Definition at line 93 of file DefaultplotDialog.cpp.
References FROM_UTF8, COutputAssistant::getItem(), COutputAssistant::getItemName(), mIndex, mList, and mpTask.
 {
   if (!mpTask) return;
   int i = listBox->currentRow();
   if (i >= 0)
     {
       mIndex = mList[i];
       lineEditTitle->setText(FROM_UTF8(COutputAssistant::getItemName(mIndex)));
       textEdit->setText(FROM_UTF8(COutputAssistant::getItem(mIndex).description));
       createButton->setEnabled(!lineEditTitle->text().startsWith("-- "));
     }
   else //Listbox is emtpy, so there is no current row (-1)
     {
       mIndex = 0;
       lineEditTitle->setText("");
       textEdit->setText("");
       createButton->setEnabled(false);
     }
 }
void DefaultPlotDialog::slotToggleAll (bool flag) protected virtual slot
connected to check box
Definition at line 118 of file DefaultplotDialog.cpp.
References fillList().
 {
   fillList();
 }
Member Data Documentation
int DefaultPlotDialog::mIndex protected
Definition at line 45 of file DefaultplotDialog.h.
Referenced by slotCreate(), and slotSelect().
std::vector< C_INT32 > DefaultPlotDialog::mList protected
Definition at line 44 of file DefaultplotDialog.h.
Referenced by fillList(), and slotSelect().
CCopasiTask* DefaultPlotDialog::mpTask protected
Definition at line 43 of file DefaultplotDialog.h.
Referenced by fillList(), setTask(), slotCreate(), and slotSelect().
The documentation for this class was generated from the following files:
DefaultplotDialog.h
DefaultplotDialog.cpp