COPASI API: CLinkMatrixView Class Reference
CLinkMatrixView Class Reference
#include <CLinkMatrix.h>
Public Types
typedef C_FLOAT64 elementType
Public Member Functions
CLinkMatrixView (const CLinkMatrix &A)
size_t numCols () const
size_t numRows () const
C_FLOAT64 & operator() (const size_t &row, const size_t &col) const
CLinkMatrixView & operator= (const CLinkMatrixView &rhs)
~CLinkMatrixView ()
Private Attributes
const CLinkMatrix * mpA
const size_t * mpNumIndependent
Static Private Attributes
static const C_FLOAT64 mUnit = 1.0
static const C_FLOAT64 mZero = 0.0
Friends
std::ostream & operator<< (std::ostream &os, const CLinkMatrixView &A)
Detailed Description
Definition at line 203 of file CLinkMatrix.h.
Member Typedef Documentation
typedef C_FLOAT64 CLinkMatrixView::elementType
Definition at line 206 of file CLinkMatrix.h.
Constructor & Destructor Documentation
CLinkMatrixView::CLinkMatrixView (const CLinkMatrix & A)
Default constructor
Parameters
const const CLinkMatrix & A
const size_t & mNumIndependent
Definition at line 589 of file CLinkMatrix.cpp.
References CONSTRUCTOR_TRACE.
                                                      :
   mpA(&A),
   mpNumIndependent(&A.getNumIndependent())
 {CONSTRUCTOR_TRACE;}
CLinkMatrixView::~CLinkMatrixView ()
Destructor.
Definition at line 594 of file CLinkMatrix.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
size_t CLinkMatrixView::numCols () const
The number of columns of the matrix
Returns
size_t cols
Definition at line 611 of file CLinkMatrix.cpp.
References mpA, and CMatrix< CType >::numCols().
Referenced by operator<<().
 {
   return mpA->numCols();
 }
size_t CLinkMatrixView::numRows () const
The number of rows of the matrix.
Returns
size_t rows
Definition at line 606 of file CLinkMatrix.cpp.
References mpA, mpNumIndependent, and CMatrix< CType >::numRows().
Referenced by operator<<().
 {
   return *mpNumIndependent + mpA->numRows();
 }
C_FLOAT64& CLinkMatrixView::operator() (const size_t & row, const size_t & col) const inline
Retrieve a matrix element using the c-style indexing.
Parameters
const size_t & row
const size_t & col
Returns
elementType & element
Definition at line 252 of file CLinkMatrix.h.
References C_FLOAT64, mpNumIndependent, mUnit, and mZero.
   {
     if (row >= *mpNumIndependent)
       return *const_cast< C_FLOAT64 * >(&(*mpA)(row - *mpNumIndependent, col));
     else if (row != col)
       return *const_cast< C_FLOAT64 * >(&mZero);
     else
       return *const_cast< C_FLOAT64 * >(&mUnit);
   }
CLinkMatrixView & CLinkMatrixView::operator= (const CLinkMatrixView & rhs)
Assignment operator
Parameters
const CLinkMatrixView & rhs
Returns
CLinkMatrixView & lhs
Definition at line 598 of file CLinkMatrix.cpp.
References mpA, and mpNumIndependent.
 {
   mpA = rhs.mpA;
   mpNumIndependent = rhs.mpNumIndependent;
   return *this;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLinkMatrixView & A) friend
Output stream operator
Parameters
ostream & os
const CLinkMatrixView & A
Returns
ostream & os
Definition at line 616 of file CLinkMatrix.cpp.
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }
Member Data Documentation
const CLinkMatrix* CLinkMatrixView::mpA private
Definition at line 209 of file CLinkMatrix.h.
Referenced by numCols(), numRows(), and operator=().
const size_t* CLinkMatrixView::mpNumIndependent private
Definition at line 210 of file CLinkMatrix.h.
Referenced by numRows(), operator()(), and operator=().
const C_FLOAT64 CLinkMatrixView::mUnit = 1.0 static private
Definition at line 212 of file CLinkMatrix.h.
Referenced by operator()().
const C_FLOAT64 CLinkMatrixView::mZero = 0.0 static private
Definition at line 211 of file CLinkMatrix.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
CLinkMatrix.h
CLinkMatrix.cpp