COPASI API: DataModelGUI Class Reference
DataModelGUI Class Reference
#include <DataModelGUI.h>
Public Slots
void exportMathModelFinished ()
void exportSBMLFinished ()
void exportSBMLToStringFinished ()
void importSBMLFinished ()
void importSBMLFromStringFinished ()
void loadModelFinished ()
void miriamDownloadFinished (QNetworkReply *)
void miriamDownloadProgress (qint64 received, qint64 total)
void saveModelFinished ()
Signals
void finished (bool success)
void notifyView (ListViews::ObjectType objectType, ListViews::Action action, std::string key="")
void updateCompleteView ()
Public Member Functions
void buildChangedObjects ()
void commit ()
bool createModel ()
DataModelGUI (QObject *parent)
void deregisterListView (ListViews *pListView)
void exportMathModel (const std::string &fileName, const std::string &filter, bool overwriteFile=false)
void exportMathModelRun ()
void exportSBML (const std::string &fileName, bool overwriteFile, int sbmlLevel, int sbmlVersion, bool exportIncomplete, bool exportCOPASIMIRIAM=true)
void exportSBMLRun ()
void exportSBMLToString (std::string &sbmlDocumentText)
void exportSBMLToStringRun ()
COutputDefinitionVector & getPlotDefinitionList ()
void importCellDesigner ()
void importSBML (const std::string &fileName)
void importSBMLFromString (const std::string &sbmlDocumentText)
void importSBMLFromStringRun ()
void importSBMLRun ()
void loadFunctionDB (const std::string &fileName)
void loadModel (const std::string &fileName)
void loadModelRun ()
bool notify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
void refreshInitialValues ()
void registerListView (ListViews *pListView)
void saveFunctionDB (const std::string &fileName)
void saveModel (const std::string &fileName, bool overwriteFile=false)
void saveModelRun ()
void setFramework (int framework)
bool updateMIRIAM (CMIRIAMResources &miriamResources)
void updateMIRIAMResourceContents ()
virtual ~DataModelGUI ()
Private Member Functions
void linkDataModelToGUI ()
void threadFinished ()
Private Attributes
std::set< const CCopasiObject * > mChangedObjects
unsigned int mDownloadedBytes
unsigned int mDownloadedTotalBytes
std::string mExportFormat
std::string mFileName
int mFramework
std::set< ListViews * > mListViews
COutputHandlerPlot mOutputHandlerPlot
bool mOverWrite
QApplication * mpApp
CMIRIAMResources * mpMiriamResources
CProgressBar * mpProgressBar
std::string * mpSBMLExportString
CQThread * mpThread
bool mSBMLExportCOPASIMIRIAM
bool mSBMLExportIncomplete
std::string mSBMLImportString
int mSBMLLevel
int mSBMLVersion
bool mSuccess
size_t mUpdateItem
std::vector< Refresh * > mUpdateVector
Detailed Description
Definition at line 34 of file DataModelGUI.h.
Constructor & Destructor Documentation
DataModelGUI::DataModelGUI (QObject * parent)
Definition at line 79 of file DataModelGUI.cpp.
References CCopasiRootContainer::getDatamodelList(), and mOutputHandlerPlot.
                                           :
   QObject(parent),
   mpApp(NULL),
   mOutputHandlerPlot(),
   mListViews(),
   mFramework(0),
   mUpdateVector(),
   mChangedObjects(),
   mpThread(NULL),
   mpProgressBar(NULL),
   mSuccess(false),
   mSBMLImportString(),
   mpSBMLExportString(NULL),
   mFileName(),
   mOverWrite(false),
   mSBMLLevel(2),
   mSBMLVersion(4),
   mSBMLExportIncomplete(true),
   mSBMLExportCOPASIMIRIAM(true),
   mExportFormat()
 #ifdef COPASI_SEDML
   , mSEDMLImportString()
   , mpSEDMLExportString(NULL)
   , mSEDMLLevel(1)
   , mSEDMLVersion(1)
   , mSEDMLExportIncomplete(true)
   , mSEDMLExportCOPASIMIRIAM(true)
 #endif
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   (*CCopasiRootContainer::getDatamodelList())[0]->addInterface(&mOutputHandlerPlot);
   //mpMathModel = NULL;
   //mMathModelUpdateScheduled = false;
 }
DataModelGUI::~DataModelGUI () virtual
Definition at line 117 of file DataModelGUI.cpp.
 {
 }
Member Function Documentation
void DataModelGUI::buildChangedObjects ()
Definition at line 634 of file DataModelGUI.cpp.
References CArrayAnnotation::appendElementReferences(), CModelEntity::ASSIGNMENT, CCopasiVector< T >::begin(), CModel::buildInitialRefreshSequence(), CCopasiMessage::clearDeque(), CModel::compileIfNecessary(), CQMessageBox::critical(), CCopasiVector< T >::end(), CStateTemplate::endFixed(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CStateTemplate::getEntities(), CMetab::getInitialConcentration(), CMetab::getInitialConcentrationReference(), CModelEntity::getInitialValueReference(), CCopasiMessage::getLastMessage(), CCopasiContainer::getObject(), CCopasiParameterGroup::getParameter(), CModel::getReactions(), CModel::getStateTemplate(), CMetab::isInitialConcentrationChangeAllowed(), mChangedObjects, mFramework, mUpdateVector, and CCopasiParameterGroup::size().
Referenced by refreshInitialValues().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel * pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   pModel->compileIfNecessary(NULL);
   mChangedObjects.clear();
   CModelEntity ** ppEntity = pModel->getStateTemplate().getEntities();
   CModelEntity ** ppEntityEnd = pModel->getStateTemplate().endFixed();
   CMetab * pMetab;
   std::set< const CCopasiObject * > Objects;
   // The objects which are changed are all initial values of of all model entities including
   // fixed and unused once. Additionally, all kinetic parameters are possibly changed.
   // This is basically all the parameters in the parameter overview whose value is editable.
   // :TODO: Theoretically, it is possible that also task parameters influence the initial
   // state of a model but that is currently not handled.
   for (; ppEntity != ppEntityEnd; ++ppEntity)
     {
       // If we have an initial expression we have no initial values
       if ((*ppEntity)->getInitialExpression() != "" ||
           (*ppEntity)->getStatus() == CModelEntity::ASSIGNMENT)
         continue;
       // Metabolites have two initial values
       if (mFramework == 0 &&
           (pMetab = dynamic_cast< CMetab * >(*ppEntity)) != NULL)
         {
           // The concentration is assumed to be fix accept when this would lead to circular dependencies,
           // for the parent's compartment's initial volume.
           if (pMetab->isInitialConcentrationChangeAllowed() &&
               !isnan(pMetab->getInitialConcentration()))
             mChangedObjects.insert(pMetab->getInitialConcentrationReference());
           else
             mChangedObjects.insert(pMetab->getInitialValueReference());
         }
       else
         mChangedObjects.insert((*ppEntity)->getInitialValueReference());
     }
   // The reaction parameters
   CCopasiVector< CReaction >::const_iterator itReaction = pModel->getReactions().begin();
   CCopasiVector< CReaction >::const_iterator endReaction = pModel->getReactions().end();
   size_t i, imax;
   for (; itReaction != endReaction; ++itReaction)
     {
       const CCopasiParameterGroup & Group = (*itReaction)->getParameters();
       for (i = 0, imax = Group.size(); i < imax; i++)
         mChangedObjects.insert(static_cast< const CCopasiObject * >(Group.getParameter(i)->getObject(CCopasiObjectName("Reference=Value"))));
     }
   // Fix for Issue 1170: We need to add elements of the stoichiometry, reduced stoichiometry,
   // and link matrices.
   const CArrayAnnotation * pMatrix = NULL;
   pMatrix = dynamic_cast<const CArrayAnnotation *>(pModel->getObject(std::string("Array=Stoichiometry(ann)")));
   if (pMatrix != NULL)
     pMatrix->appendElementReferences(mChangedObjects);
   pMatrix = dynamic_cast<const CArrayAnnotation *>(pModel->getObject(std::string("Array=Reduced stoichiometry(ann)")));
   if (pMatrix != NULL)
     pMatrix->appendElementReferences(mChangedObjects);
   pMatrix = dynamic_cast<const CArrayAnnotation *>(pModel->getObject(std::string("Array=Link matrix(ann)")));
   if (pMatrix != NULL)
     pMatrix->appendElementReferences(mChangedObjects);
   try
     {
       mUpdateVector = pModel->buildInitialRefreshSequence(mChangedObjects);
     }
   catch (...)
     {
       QString Message = "Error while updating the initial values!\n\n";
       Message += FROM_UTF8(CCopasiMessage::getLastMessage().getText());
       CQMessageBox::critical(NULL, QString("COPASI Error"), Message,
                              QMessageBox::Ok, QMessageBox::Ok);
       CCopasiMessage::clearDeque();
       mUpdateVector.clear();
       return;
     }
 }
void DataModelGUI::commit ()
Definition at line 768 of file DataModelGUI.cpp.
References mListViews.
Referenced by CopasiUI3Window::exportSBMLToString(), CopasiUI3Window::importSBMLFromString(), CopasiUI3Window::newDoc(), CopasiUI3Window::slotApplyInitialState(), CopasiUI3Window::slotConvertToIrreversible(), CopasiUI3Window::slotExportMathModel(), CopasiUI3Window::slotExportSBML(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotFileSave(), CopasiUI3Window::slotFileSaveAs(), CopasiUI3Window::slotFrameworkChanged(), CopasiUI3Window::slotFunctionDBLoad(), CopasiUI3Window::slotFunctionDBSave(), CopasiUI3Window::slotImportSBML(), CopasiUI3Window::slotQuit(), and CopasiUI3Window::slotUpdateInitialState().
 {
   std::set< ListViews * >::iterator it = mListViews.begin();
   std::set< ListViews * >::iterator end = mListViews.end();
   for (; it != end; ++it)
     {
       (*it)->commit();
     }
 }
bool DataModelGUI::createModel ()
Definition at line 200 of file DataModelGUI.cpp.
References CCopasiRootContainer::getDatamodelList(), getPlotDefinitionList(), linkDataModelToGUI(), mOutputHandlerPlot, and COutputHandlerPlot::setOutputDefinitionVector().
Referenced by CopasiUI3Window::newDoc(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotImportSBMLFinished(), and CopasiUI3Window::slotImportSBMLFromStringFinished().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (!(*CCopasiRootContainer::getDatamodelList())[0]->newModel(NULL, false)) return false;
   mOutputHandlerPlot.setOutputDefinitionVector((*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList());
   linkDataModelToGUI();
   return true;
 }
void DataModelGUI::deregisterListView (ListViews * pListView)
Definition at line 628 of file DataModelGUI.cpp.
References mListViews, and ListViews::setDataModel().
Referenced by CopasiUI3Window::~CopasiUI3Window().
 {
   pListView->setDataModel(NULL);
   mListViews.erase(pListView);
 }
void DataModelGUI::exportMathModel (const std::string & fileName, const std::string & filter, bool overwriteFile = false)
Definition at line 487 of file DataModelGUI.cpp.
References CProgressBar::create(), exportMathModelFinished(), exportMathModelRun(), finished(), mExportFormat, mFileName, mOverWrite, mpProgressBar, mpThread, and mSuccess.
Referenced by exportMathModelRun(), and CopasiUI3Window::slotExportMathModel().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mFileName = fileName;
   mOverWrite = overwriteFile;
   mExportFormat = filter;
   mpThread = new CQThread(this, &DataModelGUI::exportMathModelRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(exportMathModelFinished()));
   mpThread->start();
 }
void DataModelGUI::exportMathModelFinished () slot
Definition at line 515 of file DataModelGUI.cpp.
References finished(), mpThread, and threadFinished().
Referenced by exportMathModel().
 {
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(exportMathModelFinished()));
   threadFinished();
 }
void DataModelGUI::exportMathModelRun ()
Definition at line 501 of file DataModelGUI.cpp.
References exportMathModel(), CCopasiRootContainer::getDatamodelList(), mExportFormat, mFileName, mOverWrite, mpProgressBar, and mSuccess.
Referenced by exportMathModel().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mSuccess = (*CCopasiRootContainer::getDatamodelList())[0]->exportMathModel(mFileName, mpProgressBar, mExportFormat, mOverWrite);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::exportSBML (const std::string & fileName, bool overwriteFile, int sbmlLevel, int sbmlVersion, bool exportIncomplete, bool exportCOPASIMIRIAM = true)
Definition at line 446 of file DataModelGUI.cpp.
References CProgressBar::create(), exportSBMLFinished(), exportSBMLRun(), finished(), mFileName, mOverWrite, mpProgressBar, mpThread, mSBMLExportCOPASIMIRIAM, mSBMLExportIncomplete, mSBMLLevel, mSBMLVersion, and mSuccess.
Referenced by exportSBMLRun(), and CopasiUI3Window::slotExportSBML().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mFileName = fileName;
   mOverWrite = overwriteFile;
   mSBMLLevel = sbmlLevel;
   mSBMLVersion = sbmlVersion;
   mSBMLExportIncomplete = exportIncomplete;
   mSBMLExportCOPASIMIRIAM = exportCOPASIMIRIAM;
   mpThread = new CQThread(this, &DataModelGUI::exportSBMLRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(exportSBMLFinished()));
   mpThread->start();
 }
void DataModelGUI::exportSBMLFinished () slot
Definition at line 477 of file DataModelGUI.cpp.
References CRecentFiles::addFile(), finished(), CCopasiRootContainer::getConfiguration(), CConfigurationFile::getRecentSBMLFiles(), mFileName, mpThread, mSuccess, and threadFinished().
Referenced by exportSBML().
 {
   if (mSuccess)
     CCopasiRootContainer::getConfiguration()->getRecentSBMLFiles().addFile(mFileName);
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(exportSBMLFinished()));
   threadFinished();
 }
void DataModelGUI::exportSBMLRun ()
Definition at line 463 of file DataModelGUI.cpp.
References exportSBML(), CCopasiRootContainer::getDatamodelList(), mFileName, mOverWrite, mpProgressBar, mSBMLExportCOPASIMIRIAM, mSBMLExportIncomplete, mSBMLLevel, mSBMLVersion, and mSuccess.
Referenced by exportSBML().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mSuccess = (*CCopasiRootContainer::getDatamodelList())[0]->exportSBML(mFileName, mOverWrite, mSBMLLevel, mSBMLVersion, mSBMLExportIncomplete, mSBMLExportCOPASIMIRIAM, mpProgressBar);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::exportSBMLToString (std::string & sbmlDocumentText)
Definition at line 395 of file DataModelGUI.cpp.
References CProgressBar::create(), exportSBMLToStringFinished(), exportSBMLToStringRun(), finished(), mpProgressBar, mpSBMLExportString, mpThread, and mSuccess.
Referenced by CopasiUI3Window::exportSBMLToString(), and exportSBMLToStringRun().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mpSBMLExportString = & sbmlDocumentText;
   mpThread = new CQThread(this, &DataModelGUI::exportSBMLToStringRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(exportSBMLToStringFinished()));
   mpThread->start();
 }
void DataModelGUI::exportSBMLToStringFinished () slot
Definition at line 421 of file DataModelGUI.cpp.
References finished(), mpThread, and threadFinished().
Referenced by exportSBMLToString().
 {
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(exportSBMLToStringFinished()));
   threadFinished();
 }
void DataModelGUI::exportSBMLToStringRun ()
Definition at line 407 of file DataModelGUI.cpp.
References exportSBMLToString(), CCopasiRootContainer::getDatamodelList(), mpProgressBar, mpSBMLExportString, and mSuccess.
Referenced by exportSBMLToString().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       *mpSBMLExportString = (*CCopasiRootContainer::getDatamodelList())[0]->exportSBMLToString(mpProgressBar, 2, 4);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::finished (bool success) signal
Referenced by exportMathModel(), exportMathModelFinished(), exportSBML(), exportSBMLFinished(), exportSBMLToString(), exportSBMLToStringFinished(), importSBML(), importSBMLFinished(), importSBMLFromString(), importSBMLFromStringFinished(), loadModel(), loadModelFinished(), miriamDownloadFinished(), saveModel(), saveModelFinished(), threadFinished(), and updateMIRIAM().
COutputDefinitionVector& DataModelGUI::getPlotDefinitionList ()
Referenced by createModel(), importSBMLFinished(), importSBMLFromStringFinished(), and loadModelFinished().
void DataModelGUI::importCellDesigner ()
This method tries to import CellDesigner annotations.
Definition at line 782 of file DataModelGUI.cpp.
References CListOfLayouts::addLayout(), SBMLDocumentLoader::createLayout(), CCellDesignerImporter::determineVersion(), CCellDesignerImporter::findCellDesignerAnnotation(), CCellDesignerImporter::findCellDesignerNamespace(), CCopasiDataModel::getCopasi2SBMLMap(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiRootContainer::getDatamodelList(), SBMLUtils::getIdFromSBase(), CCellDesignerImporter::getLayout(), CCopasiDataModel::getListOfLayouts(), CQMessageBox::question(), CCopasiMessage::RAW, and CCopasiMessage::WARNING.
Referenced by importSBMLFinished(), and importSBMLFromStringFinished().
 {
   // add code to check for CellDesigner annotations
   // ask the user if the annotations should be imported
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (pDataModel != NULL)
     {
       SBMLDocument* pSBMLDocument = pDataModel->getCurrentSBMLDocument();
       if (pSBMLDocument != NULL &&
           pSBMLDocument->getModel() != NULL &&
           pSBMLDocument->getModel()->getAnnotation() != NULL)
         {
           // check for the CellDesigner namespace
           std::pair<bool, std::string> foundNamespace = CCellDesignerImporter::findCellDesignerNamespace(pSBMLDocument);
           if (foundNamespace.first == true)
             {
               const XMLNode* pAnno = CCellDesignerImporter::findCellDesignerAnnotation(pSBMLDocument, pSBMLDocument->getModel()->getAnnotation());
               // first we check if there are supported cell designer annotations
               if (pAnno != NULL)
                 {
                   // check if the file contains the correct version
                   double version = CCellDesignerImporter::determineVersion(pAnno);
                   if (version < 4.0)
                     {
                       CCopasiMessage(CCopasiMessage::RAW, "CellDesigner annotation was found in the file, but the version is not supported.\nPlease open the file in the latest version of CellDesigner and save it again.");
                     }
                   else
                     {
                       bool importCD = false;
 #if LIBSBML_VERSION >= 50400
                       // if we don't have a layout import it!
                       LayoutModelPlugin* mplugin = (LayoutModelPlugin*)pSBMLDocument->getModel()->getPlugin("layout");
                       if (mplugin == NULL || (mplugin != NULL && mplugin->getNumLayouts() == 0))
                         importCD = true;
 #endif
                       // ask the user if the CellDesigner annotation should be imported
                       if (importCD || CQMessageBox::question(NULL, "CellDesigner import", "A CellDesigner diagram was found in this file.\nDo you want to import the diagram?" , QMessageBox::Yes | QMessageBox::No , QMessageBox::No) == QMessageBox::Yes)
{
                           // do the import
                           CCellDesignerImporter cd_importer(pSBMLDocument);
                           if (cd_importer.getLayout() == NULL)
{
                               CCopasiMessage(CCopasiMessage::WARNING, "Sorry, CellDesigner annotations could not be imported.");
                             }
                           else
{
                               // now we have to import the created layout
                               // create the model map
                               std::string s1, s2;
                               std::map<std::string, std::string> modelmap;
                               std::map<CCopasiObject*, SBase*>::const_iterator it;
                               std::map<CCopasiObject*, SBase*>::const_iterator itEnd = pDataModel->getCopasi2SBMLMap().end();
                               for (it = pDataModel->getCopasi2SBMLMap().begin(); it != itEnd; ++it)
{
                                   s1 = SBMLUtils::getIdFromSBase(it->second);
                                   if (it->first)
{
                                       s2 = it->first->getKey();
                                     }
                                   else
{
                                       s2 = "";
                                     }
                                   if ((s1 != "") && (s2 != ""))
{
                                       modelmap[s1] = s2;
                                     }
                                 }
                               // the layout map and the id to key map can be empty
                               std::map<std::string, std::string> layoutmap;
                               std::map<std::string, std::string> idToKeyMap;
                               CLayout* pLayout = SBMLDocumentLoader::createLayout(*cd_importer.getLayout(), modelmap, layoutmap, idToKeyMap);
                               // add the layout to the DataModel
                               if (pLayout != NULL && pDataModel->getListOfLayouts() != NULL)
{
                                   // the addLayout methods expects a map as the second argument which currently is
                                   // ignored, so we just pass an empty one
                                   // TODO maybe the methods actually expects one of the maps above (layoutmap or idToKeyMap), but
                                   // TODO this is not documented in CListOfLayouts
                                   std::map<std::string, std::string> tmp;
                                   pDataModel->getListOfLayouts()->addLayout(pLayout, tmp);
                                 }
                               else
{
                                   CCopasiMessage(CCopasiMessage::WARNING, "Sorry, Layout from CellDesigner annotations could not be created.");
                                 }
                             }
                         }
                     }
                 }
               else
                 {
                   CCopasiMessage(CCopasiMessage::RAW, "CellDesigner annotation was found in the file, but the version is not supported.\nPlease open the file in the latest version of CellDesigner and save it again.");
                 }
             }
         }
     }
 }
void DataModelGUI::importSBML (const std::string & fileName)
Definition at line 354 of file DataModelGUI.cpp.
References CProgressBar::create(), finished(), importSBMLFinished(), importSBMLRun(), mFileName, mpProgressBar, mpThread, and mSuccess.
Referenced by importSBMLRun(), and CopasiUI3Window::slotImportSBML().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mFileName = fileName;
   mpThread = new CQThread(this, &DataModelGUI::importSBMLRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(importSBMLFinished()));
   mpThread->start();
 }
void DataModelGUI::importSBMLFinished () slot
Definition at line 379 of file DataModelGUI.cpp.
References CRecentFiles::addFile(), finished(), CCopasiRootContainer::getConfiguration(), CCopasiRootContainer::getDatamodelList(), getPlotDefinitionList(), CConfigurationFile::getRecentSBMLFiles(), importCellDesigner(), linkDataModelToGUI(), mFileName, mOutputHandlerPlot, mpThread, mSuccess, COutputHandlerPlot::setOutputDefinitionVector(), and threadFinished().
Referenced by importSBML().
 {
   if (mSuccess)
     {
       this->importCellDesigner();
       CCopasiRootContainer::getConfiguration()->getRecentSBMLFiles().addFile(mFileName);
       mOutputHandlerPlot.setOutputDefinitionVector((*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList());
       linkDataModelToGUI();
     }
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(importSBMLFinished()));
   threadFinished();
 }
void DataModelGUI::importSBMLFromString (const std::string & sbmlDocumentText)
Definition at line 290 of file DataModelGUI.cpp.
References CProgressBar::create(), finished(), importSBMLFromStringFinished(), importSBMLFromStringRun(), mpProgressBar, mpThread, mSBMLImportString, and mSuccess.
Referenced by CopasiUI3Window::importSBMLFromString(), and importSBMLFromStringRun().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mSBMLImportString = sbmlDocumentText;
   mpThread = new CQThread(this, &DataModelGUI::importSBMLFromStringRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(importSBMLFromStringFinished()));
   mpThread->start();
 }
void DataModelGUI::importSBMLFromStringFinished () slot
Definition at line 316 of file DataModelGUI.cpp.
References finished(), CCopasiRootContainer::getDatamodelList(), getPlotDefinitionList(), importCellDesigner(), linkDataModelToGUI(), mOutputHandlerPlot, mpThread, mSBMLImportString, mSuccess, COutputHandlerPlot::setOutputDefinitionVector(), and threadFinished().
Referenced by importSBMLFromString().
 {
   mSBMLImportString = "";
   if (mSuccess)
     {
       // can't run this in a separate thread because it uses GUI routines
       // TODO maybe put the main part of this routine in a separate thread after
       // TODO asking the user
       this->importCellDesigner();
       mOutputHandlerPlot.setOutputDefinitionVector((*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList());
       linkDataModelToGUI();
     }
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(importSBMLFromStringFinished()));
   threadFinished();
 }
void DataModelGUI::importSBMLFromStringRun ()
Definition at line 302 of file DataModelGUI.cpp.
References CCopasiRootContainer::getDatamodelList(), importSBMLFromString(), mpProgressBar, mSBMLImportString, and mSuccess.
Referenced by importSBMLFromString().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mSuccess = (*CCopasiRootContainer::getDatamodelList())[0]->importSBMLFromString(mSBMLImportString, mpProgressBar, false);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::importSBMLRun ()
Definition at line 365 of file DataModelGUI.cpp.
References CCopasiRootContainer::getDatamodelList(), importSBML(), mFileName, mpProgressBar, and mSuccess.
Referenced by importSBML().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mSuccess = (*CCopasiRootContainer::getDatamodelList())[0]->importSBML(mFileName, mpProgressBar, false);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::linkDataModelToGUI () private
Definition at line 123 of file DataModelGUI.cpp.
References CCopasiDataModel::deleteOldData(), CCopasiRootContainer::getDatamodelList(), and mListViews.
Referenced by createModel(), importSBMLFinished(), importSBMLFromStringFinished(), and loadModelFinished().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   std::set< ListViews * >::iterator it = mListViews.begin();
   std::set< ListViews * >::iterator end = mListViews.end();
   for (; it != end; ++it)
     {
       (*it)->setDataModel(this);
     }
   pDataModel->deleteOldData();
 }
void DataModelGUI::loadFunctionDB (const std::string & fileName)
Definition at line 344 of file DataModelGUI.cpp.
References ListViews::DELETE, ListViews::FUNCTION, CCopasiRootContainer::getFunctionList(), CFunctionDB::load(), and notify().
Referenced by CopasiUI3Window::slotFunctionDBLoad().
 {
   CFunctionDB* pFunctionDB = CCopasiRootContainer::getFunctionList();
   if (pFunctionDB == NULL) return;
   if (pFunctionDB->load(fileName))
     emit notify(ListViews::FUNCTION, ListViews::DELETE, "");
 }
void DataModelGUI::loadModel (const std::string & fileName)
Definition at line 212 of file DataModelGUI.cpp.
References CProgressBar::create(), finished(), loadModelFinished(), loadModelRun(), mFileName, mpProgressBar, mpThread, and mSuccess.
Referenced by loadModelRun(), and CopasiUI3Window::slotFileOpen().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mFileName = fileName;
   mpThread = new CQThread(this, &DataModelGUI::loadModelRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(loadModelFinished()));
   mpThread->start();
 }
void DataModelGUI::loadModelFinished () slot
Definition at line 238 of file DataModelGUI.cpp.
References CRecentFiles::addFile(), finished(), CCopasiRootContainer::getConfiguration(), CCopasiRootContainer::getDatamodelList(), getPlotDefinitionList(), CConfigurationFile::getRecentFiles(), linkDataModelToGUI(), mFileName, mOutputHandlerPlot, mpThread, mSuccess, COutputHandlerPlot::setOutputDefinitionVector(), and threadFinished().
Referenced by loadModel().
 {
   if (mSuccess)
     {
       CCopasiRootContainer::getConfiguration()->getRecentFiles().addFile(mFileName);
       mOutputHandlerPlot.setOutputDefinitionVector((*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList());
       linkDataModelToGUI();
     }
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(loadModelFinished()));
   threadFinished();
 }
void DataModelGUI::loadModelRun ()
Definition at line 224 of file DataModelGUI.cpp.
References CCopasiRootContainer::getDatamodelList(), loadModel(), mFileName, mpProgressBar, and mSuccess.
Referenced by loadModel().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mSuccess = (*CCopasiRootContainer::getDatamodelList())[0]->loadModel(mFileName, mpProgressBar, false);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::miriamDownloadFinished (QNetworkReply * reply) slot
Definition at line 522 of file DataModelGUI.cpp.
References finished(), COptions::getValue(), mDownloadedBytes, mpMiriamResources, mpProgressBar, mUpdateItem, pdelete, CProgressBar::progressItem(), and CMIRIAMResources::updateMIRIAMResourcesFromFile().
Referenced by updateMIRIAM().
 {
   bool success = true;
   mDownloadedBytes = 100;
   mpProgressBar->progressItem(mUpdateItem);
   CMIRIAMResources & miriamResources = *mpMiriamResources;
   if (reply != NULL && reply->error() == QNetworkReply::NoError)
     {
       std::string filename;
       COptions::getValue("ConfigDir", filename);
       filename += "/miriam.xml";
       QFile *miriamFile = new QFile(filename.c_str());
       if (miriamFile->open(QFile::WriteOnly))
         {
           miriamFile->write(reply->readAll());
           miriamFile->flush();
           miriamFile->close();
           success = miriamResources.updateMIRIAMResourcesFromFile(mpProgressBar, filename);
         }
       delete miriamFile;
     }
   else
     {
       success = false;
     }
   reply->deleteLater();
   pdelete(mpProgressBar);
   // notify UI to pick up
   emit finished(success);
 }
void DataModelGUI::miriamDownloadProgress (qint64 received, qint64 total) slot
Definition at line 561 of file DataModelGUI.cpp.
References mDownloadedBytes, mpProgressBar, mUpdateItem, and CProgressBar::progressItem().
Referenced by updateMIRIAM().
 {
   if (total != -1)
     {
       mDownloadedBytes = 100 * double(received) / double(total);
     }
   else
     {
       ++mDownloadedBytes;
     }
   if (!mpProgressBar->progressItem(mUpdateItem))
     {
       QNetworkReply *reply = dynamic_cast<QNetworkReply*>(sender());
       if (reply != NULL) reply->abort();
     }
 }
bool DataModelGUI::notify (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key = "")
Definition at line 607 of file DataModelGUI.cpp.
References mpProgressBar, notifyView(), refreshInitialValues(), and ListViews::RENAME.
Referenced by CopasiUI3Window::importSBMLFromString(), loadFunctionDB(), CQReportDefinitionSelect::loadReportDefinitionVector(), CopasiUI3Window::newDoc(), CopasiWidget::protectedNotify(), CopasiUI3Window::slotApplyInitialState(), CopasiUI3Window::slotConvertToIrreversible(), CopasiUI3Window::slotExpandModel(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotImportSBML(), CopasiUI3Window::slotImportSBMLFinished(), CopasiUI3Window::slotImportSBMLFromStringFinished(), and CopasiUI3Window::slotUpdateInitialState().
 {
   // The GUI is inactive whenever a progress bar exist. We wait with updates
   // until then.
   if (mpProgressBar != NULL) return false;
   // update all initial value
   if (action != ListViews::RENAME)
     refreshInitialValues();
   emit notifyView(objectType, action, key);
   return true;
 }
void DataModelGUI::notifyView (ListViews::ObjectType objectType, ListViews::Action action, std::string key = "") signal
Referenced by notify().
void DataModelGUI::refreshInitialValues ()
Definition at line 728 of file DataModelGUI.cpp.
References buildChangedObjects(), CCopasiRootContainer::getDatamodelList(), mUpdateVector, and CModel::refreshActiveParameterSet().
Referenced by notify(), CopasiSlider::setValue(), SliderDialog::updateAllSliders(), and CopasiSlider::updateValue().
 {
   buildChangedObjects();
   std::vector< Refresh * >::iterator it = mUpdateVector.begin();
   std::vector< Refresh * >::iterator end = mUpdateVector.end();
   for (; it != end; ++it)
     (**it)();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel * pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   pModel->refreshActiveParameterSet();
 }
void DataModelGUI::registerListView (ListViews * pListView)
Definition at line 622 of file DataModelGUI.cpp.
References mListViews, and ListViews::setDataModel().
Referenced by CopasiUI3Window::CopasiUI3Window().
 {
   pListView->setDataModel(this);
   mListViews.insert(pListView);
 }
void DataModelGUI::saveFunctionDB (const std::string & fileName)
Definition at line 335 of file DataModelGUI.cpp.
References CCopasiRootContainer::getFunctionList(), and CFunctionDB::save().
Referenced by CopasiUI3Window::slotFunctionDBSave().
 {
   CFunctionDB* pFunctionDB = CCopasiRootContainer::getFunctionList();
   if (pFunctionDB == NULL) return;
   pFunctionDB->save(fileName);
 }
void DataModelGUI::saveModel (const std::string & fileName, bool overwriteFile = false)
Definition at line 253 of file DataModelGUI.cpp.
References CProgressBar::create(), finished(), mFileName, mOverWrite, mpProgressBar, mpThread, mSuccess, saveModelFinished(), and saveModelRun().
Referenced by saveModelRun(), CopasiUI3Window::slotFileSave(), and CopasiUI3Window::slotFileSaveAs().
 {
   mpProgressBar = CProgressBar::create();
   mSuccess = true;
   mFileName = fileName;
   mOverWrite = overwriteFile;
   mpThread = new CQThread(this, &DataModelGUI::saveModelRun);
   connect(mpThread, SIGNAL(finished()), this, SLOT(saveModelFinished()));
   mpThread->start();
 }
void DataModelGUI::saveModelFinished () slot
Definition at line 280 of file DataModelGUI.cpp.
References CRecentFiles::addFile(), finished(), CCopasiRootContainer::getConfiguration(), CConfigurationFile::getRecentFiles(), mFileName, mpThread, mSuccess, and threadFinished().
Referenced by saveModel().
 {
   if (mSuccess)
     CCopasiRootContainer::getConfiguration()->getRecentFiles().addFile(mFileName);
   disconnect(mpThread, SIGNAL(finished()), this, SLOT(saveModelFinished()));
   threadFinished();
 }
void DataModelGUI::saveModelRun ()
Definition at line 266 of file DataModelGUI.cpp.
References CCopasiRootContainer::getDatamodelList(), mFileName, mOverWrite, mpProgressBar, mSuccess, and saveModel().
Referenced by saveModel().
 {
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mSuccess = (*CCopasiRootContainer::getDatamodelList())[0]->saveModel(mFileName, mpProgressBar, mOverWrite);
     }
   catch (...)
     {
       mSuccess = false;
     }
 }
void DataModelGUI::setFramework (int framework)
Definition at line 744 of file DataModelGUI.cpp.
References mFramework, and mListViews.
Referenced by CopasiUI3Window::slotFrameworkChanged().
 {
   mFramework = framework;
   std::set< ListViews * >::iterator it = mListViews.begin();
   std::set< ListViews * >::iterator end = mListViews.end();
   for (; it != end; ++it)
     {
       (*it)->setFramework(mFramework);
     }
 }
void DataModelGUI::threadFinished () private
Definition at line 428 of file DataModelGUI.cpp.
References CProgressBar::finish(), finished(), mpProgressBar, mpThread, and mSuccess.
Referenced by exportMathModelFinished(), exportSBMLFinished(), exportSBMLToStringFinished(), importSBMLFinished(), importSBMLFromStringFinished(), loadModelFinished(), and saveModelFinished().
 {
   if (mpThread != NULL)
     {
       mpThread->deleteLater();
       mpThread = NULL;
     }
   if (mpProgressBar != NULL)
     {
       mpProgressBar->finish();
       mpProgressBar->deleteLater();
       mpProgressBar = NULL;
     }
   emit finished(mSuccess);
 }
void DataModelGUI::updateCompleteView () signal
bool DataModelGUI::updateMIRIAM (CMIRIAMResources & miriamResources)
Definition at line 580 of file DataModelGUI.cpp.
References CProgressBar::create(), finished(), mDownloadedBytes, mDownloadedTotalBytes, miriamDownloadFinished(), miriamDownloadProgress(), mpMiriamResources, mpProgressBar, mUpdateItem, and CProgressBar::setName().
Referenced by CopasiUI3Window::slotUpdateMIRIAM().
 {
   bool success = true;
   mpMiriamResources = &miriamResources;
   mpProgressBar = CProgressBar::create();
   mpProgressBar->setName("MIRIAM Resources Update...");
   mDownloadedBytes = 0; mDownloadedTotalBytes = 100;
   mUpdateItem = ((CProcessReport*)mpProgressBar)->addItem("Download MIRIAM info", mDownloadedBytes, &mDownloadedTotalBytes);
   QNetworkAccessManager *manager = new QNetworkAccessManager(this);
   connect(manager, SIGNAL(finished(QNetworkReply*)),
           this, SLOT(miriamDownloadFinished(QNetworkReply*)));
   QNetworkReply* reply = manager->get(QNetworkRequest(QUrl("http://www.ebi.ac.uk/miriam/main/export/xml/")));
   connect(reply, SIGNAL(downloadProgress(qint64, qint64)),
           this, SLOT(miriamDownloadProgress(qint64, qint64)));
   return success;
 }
void DataModelGUI::updateMIRIAMResourceContents ()
Definition at line 757 of file DataModelGUI.cpp.
References mListViews.
Referenced by CopasiUI3Window::slotUpdateMIRIAMFinished().
 {
   std::set< ListViews * >::iterator it = mListViews.begin();
   std::set< ListViews * >::iterator end = mListViews.end();
   for (; it != end; ++it)
     {
       (*it)->updateMIRIAMResourceContents();
     }
 }
Member Data Documentation
std::set< const CCopasiObject * > DataModelGUI::mChangedObjects private
Definition at line 141 of file DataModelGUI.h.
Referenced by buildChangedObjects().
unsigned int DataModelGUI::mDownloadedBytes private
Definition at line 156 of file DataModelGUI.h.
Referenced by miriamDownloadFinished(), miriamDownloadProgress(), and updateMIRIAM().
unsigned int DataModelGUI::mDownloadedTotalBytes private
Definition at line 157 of file DataModelGUI.h.
Referenced by updateMIRIAM().
std::string DataModelGUI::mExportFormat private
Definition at line 154 of file DataModelGUI.h.
Referenced by exportMathModel(), and exportMathModelRun().
std::string DataModelGUI::mFileName private
Definition at line 148 of file DataModelGUI.h.
Referenced by exportMathModel(), exportMathModelRun(), exportSBML(), exportSBMLFinished(), exportSBMLRun(), importSBML(), importSBMLFinished(), importSBMLRun(), loadModel(), loadModelFinished(), loadModelRun(), saveModel(), saveModelFinished(), and saveModelRun().
int DataModelGUI::mFramework private
Definition at line 139 of file DataModelGUI.h.
Referenced by buildChangedObjects(), and setFramework().
std::set< ListViews * > DataModelGUI::mListViews private
Definition at line 138 of file DataModelGUI.h.
Referenced by commit(), deregisterListView(), linkDataModelToGUI(), registerListView(), setFramework(), and updateMIRIAMResourceContents().
COutputHandlerPlot DataModelGUI::mOutputHandlerPlot private
Definition at line 137 of file DataModelGUI.h.
Referenced by createModel(), DataModelGUI(), importSBMLFinished(), importSBMLFromStringFinished(), and loadModelFinished().
bool DataModelGUI::mOverWrite private
Definition at line 149 of file DataModelGUI.h.
Referenced by exportMathModel(), exportMathModelRun(), exportSBML(), exportSBMLRun(), saveModel(), and saveModelRun().
QApplication* DataModelGUI::mpApp private
Definition at line 136 of file DataModelGUI.h.
CMIRIAMResources* DataModelGUI::mpMiriamResources private
Definition at line 155 of file DataModelGUI.h.
Referenced by miriamDownloadFinished(), and updateMIRIAM().
CProgressBar* DataModelGUI::mpProgressBar private
Definition at line 144 of file DataModelGUI.h.
Referenced by exportMathModel(), exportMathModelRun(), exportSBML(), exportSBMLRun(), exportSBMLToString(), exportSBMLToStringRun(), importSBML(), importSBMLFromString(), importSBMLFromStringRun(), importSBMLRun(), loadModel(), loadModelRun(), miriamDownloadFinished(), miriamDownloadProgress(), notify(), saveModel(), saveModelRun(), threadFinished(), and updateMIRIAM().
std::string* DataModelGUI::mpSBMLExportString private
Definition at line 147 of file DataModelGUI.h.
Referenced by exportSBMLToString(), and exportSBMLToStringRun().
CQThread* DataModelGUI::mpThread private
Definition at line 143 of file DataModelGUI.h.
Referenced by exportMathModel(), exportMathModelFinished(), exportSBML(), exportSBMLFinished(), exportSBMLToString(), exportSBMLToStringFinished(), importSBML(), importSBMLFinished(), importSBMLFromString(), importSBMLFromStringFinished(), loadModel(), loadModelFinished(), saveModel(), saveModelFinished(), and threadFinished().
bool DataModelGUI::mSBMLExportCOPASIMIRIAM private
Definition at line 153 of file DataModelGUI.h.
Referenced by exportSBML(), and exportSBMLRun().
bool DataModelGUI::mSBMLExportIncomplete private
Definition at line 152 of file DataModelGUI.h.
Referenced by exportSBML(), and exportSBMLRun().
std::string DataModelGUI::mSBMLImportString private
Definition at line 146 of file DataModelGUI.h.
Referenced by importSBMLFromString(), importSBMLFromStringFinished(), and importSBMLFromStringRun().
int DataModelGUI::mSBMLLevel private
Definition at line 150 of file DataModelGUI.h.
Referenced by exportSBML(), and exportSBMLRun().
int DataModelGUI::mSBMLVersion private
Definition at line 151 of file DataModelGUI.h.
Referenced by exportSBML(), and exportSBMLRun().
bool DataModelGUI::mSuccess private
Definition at line 145 of file DataModelGUI.h.
Referenced by exportMathModel(), exportMathModelRun(), exportSBML(), exportSBMLFinished(), exportSBMLRun(), exportSBMLToString(), exportSBMLToStringRun(), importSBML(), importSBMLFinished(), importSBMLFromString(), importSBMLFromStringFinished(), importSBMLFromStringRun(), importSBMLRun(), loadModel(), loadModelFinished(), loadModelRun(), saveModel(), saveModelFinished(), saveModelRun(), and threadFinished().
size_t DataModelGUI::mUpdateItem private
Definition at line 158 of file DataModelGUI.h.
Referenced by miriamDownloadFinished(), miriamDownloadProgress(), and updateMIRIAM().
std::vector< Refresh * > DataModelGUI::mUpdateVector private
Definition at line 140 of file DataModelGUI.h.
Referenced by buildChangedObjects(), and refreshInitialValues().
The documentation for this class was generated from the following files:
DataModelGUI.h
DataModelGUI.cpp