COPASI API: CExperimentFileInfo Class Reference
CExperimentFileInfo Class Reference
#include <CExperimentFileInfo.h>
Classes
class CExperimentInfo
Public Member Functions
bool adjustForEmptyLines (size_t &First, size_t &Last)
CExperimentFileInfo (CExperimentSet &set)
CExperiment * getExperiment (const std::string &name)
std::vector< std::string > getExperimentNames () const
const std::string & getFileName () const
bool getFirstUnusedSection (size_t &First, size_t &Last)
bool getNextUnusedSection (size_t &First, size_t &Last)
bool setFileName (const std::string &fileName)
bool sync ()
bool validate () const
bool validateFirst (const size_t &index, const size_t &value)
bool validateHeader (const size_t &index, const size_t &value)
bool validateLast (const size_t &index, const size_t &value)
~CExperimentFileInfo ()
Private Member Functions
CExperimentFileInfo ()
Private Attributes
std::vector< size_t > mEmptyLines
std::string mFileName
size_t mLines
std::vector< CExperimentInfo * > mList
CExperimentSet * mpSet
size_t mUsedEnd
Detailed Description
Definition at line 30 of file CExperimentFileInfo.h.
Constructor & Destructor Documentation
CExperimentFileInfo::CExperimentFileInfo () private
Definition at line 28 of file CExperimentFileInfo.cpp.
                                         :
     mpSet(NULL),
     mFileName(""),
     mList(),
     mLines(0),
     mUsedEnd(C_INVALID_INDEX),
     mEmptyLines()
 {}
CExperimentFileInfo::CExperimentFileInfo (CExperimentSet & set)
Definition at line 37 of file CExperimentFileInfo.cpp.
                                                             :
     mpSet(&set),
     mFileName(""),
     mList(),
     mLines(0),
     mUsedEnd(C_INVALID_INDEX),
     mEmptyLines()
 {}
CExperimentFileInfo::~CExperimentFileInfo ()
Definition at line 46 of file CExperimentFileInfo.cpp.
References mList, and pdelete.
 {
   size_t i, imax;
   for (i = 0, imax = mList.size(); i < imax; i++)
     pdelete(mList[i]);
   mList.clear();
 }
Member Function Documentation
bool CExperimentFileInfo::adjustForEmptyLines (size_t & First, size_t & Last)
Definition at line 270 of file CExperimentFileInfo.cpp.
References getNextUnusedSection(), mEmptyLines, and mUsedEnd.
Referenced by getNextUnusedSection().
 {
   std::vector<size_t>::const_iterator it = mEmptyLines.begin();
   std::vector<size_t>::const_iterator end = mEmptyLines.end();
   while (it != end && *it < First) ++it;
   if (it == end)
     return true;
   if (it != end && *it == First)
     {
       if (First == Last)
         return getNextUnusedSection(First, Last);
       First++;
       return adjustForEmptyLines(First, Last);
     }
   if (*it <= Last)
     {
       Last = *it - 1;
       mUsedEnd = Last;
     }
   return true;
 }
CExperiment * CExperimentFileInfo::getExperiment (const std::string & name)
Definition at line 214 of file CExperimentFileInfo.cpp.
References mList.
Referenced by CQExperimentData::slotCheckFrom(), CQExperimentData::slotExperimentChanged(), and CQExperimentData::slotExperimentDelete().
 {
   size_t i, imax;
   for (i = 0, imax = mList.size(); i < imax; i++)
     if (mList[i]->pExperiment->getObjectName() == name)
       return mList[i]->pExperiment;
   return NULL;
 }
std::vector< std::string > CExperimentFileInfo::getExperimentNames () const
Definition at line 202 of file CExperimentFileInfo.cpp.
References mList.
Referenced by CQExperimentData::slotFileChanged(), and CQExperimentData::syncExperiments().
 {
   std::vector< std::string > List;
   size_t i, imax;
   for (i = 0, imax = mList.size(); i < imax; i++)
     List.push_back(mList[i]->pExperiment->getObjectName());
   return List;
 }
const std::string & CExperimentFileInfo::getFileName () const
Definition at line 111 of file CExperimentFileInfo.cpp.
References mFileName.
Referenced by CQExperimentData::slotExperimentAdd().
 {return mFileName;}
bool CExperimentFileInfo::getFirstUnusedSection (size_t & First, size_t & Last)
Definition at line 225 of file CExperimentFileInfo.cpp.
References getNextUnusedSection(), and mUsedEnd.
Referenced by CQExperimentData::saveExperiment(), CQExperimentData::slotExperimentAdd(), CQExperimentData::slotExperimentDelete(), CQExperimentData::slotFileAdd(), CQExperimentData::slotFileChanged(), and CQExperimentDataValidator::validate().
 {
   mUsedEnd = 0;
   return getNextUnusedSection(First, Last);
 }
bool CExperimentFileInfo::getNextUnusedSection (size_t & First, size_t & Last)
Definition at line 233 of file CExperimentFileInfo.cpp.
References adjustForEmptyLines(), C_INVALID_INDEX, mLines, mList, and mUsedEnd.
Referenced by adjustForEmptyLines(), getFirstUnusedSection(), and CQExperimentDataValidator::validate().
 {
   First = mUsedEnd + 1;
   size_t i, imax = mList.size();
   for (i = 0; i < imax; i++)
     {
       if (First < mList[i]->First)
         {
           Last = mList[i]->First - 1;
           mUsedEnd = Last;
           return adjustForEmptyLines(First, Last);
         }
       if (mList[i]->Last + 1 > First)
         First = mList[i]->Last + 1;
     }
   if (First < mLines)
     {
       Last = mLines;
       mUsedEnd = Last;
       return adjustForEmptyLines(First, Last);
     }
   First = C_INVALID_INDEX;
   Last = C_INVALID_INDEX;
   mUsedEnd = mLines;
   return false;
 }
bool CExperimentFileInfo::setFileName (const std::string & fileName)
Definition at line 56 of file CExperimentFileInfo.cpp.
References CLocaleString::fromUtf8(), mEmptyLines, mFileName, mLines, and sync().
Referenced by CQExperimentData::slotFileChanged().
 {
   mFileName = fileName;
   mLines = 0;
   mEmptyLines.clear();
   std::ifstream in;
   in.open(CLocaleString::fromUtf8(mFileName).c_str(), std::ios::binary);
   if (in.fail())  // File can not be opened.
     {
       mLines = 0;
       return sync();
     }
   bool isEmpty;
   // forwind to count lines in file
   while (!in.eof())
     {
       isEmpty = true;
       char c;
       for (in.get(c); c != 0x0a && c != 0x0d; in.get(c))
         {
           if (in.fail() || in.eof()) break;
           switch (c)
             {
               case '\x20':
               case '\x09':
               case '\x0d':
               case '\x0a':
                 break;
               default:
                 isEmpty = false;
                 break;
             }
         }
       // Eat additional line break characters appearing on DOS and Mac text format;
       if ((c == 0x0d && in.peek() == 0x0a) || // DOS
           (c == 0x0a && in.peek() == 0x0d))   // Mac
         in.ignore(1);
       mLines++;
       if (isEmpty)
         mEmptyLines.push_back(mLines);
     }
   return sync();
 }
bool CExperimentFileInfo::sync ()
Definition at line 114 of file CExperimentFileInfo.cpp.
References C_INVALID_INDEX, CExperimentSet::getExperiment(), CExperimentSet::getExperimentCount(), CExperiment::getFileName(), mFileName, mList, mpSet, mUsedEnd, pdelete, CExperimentSet::sort(), and validate().
Referenced by CQExperimentData::saveExperiment(), setFileName(), CQExperimentData::slotExperimentAdd(), CQExperimentData::syncExperiments(), and CQExperimentDataValidator::validate().
 {
   mpSet->sort();
   size_t i, imax;
   for (i = 0, imax = mList.size(); i < imax; i++)
     pdelete(mList[i]);
   mList.clear();
   // Find the desired file name
   for (i = 0, imax = mpSet->getExperimentCount(); i < imax; i++)
     if (mpSet->getExperiment(i)->getFileName() == mFileName) break;
   // Continue as long as the file name does not change
   for (; i < imax; i++)
     {
       if (mpSet->getExperiment(i)->getFileName() != mFileName) break;
       mList.push_back(new CExperimentInfo(*mpSet->getExperiment(i)));
     }
   mUsedEnd = C_INVALID_INDEX;
   return validate();
 }
bool CExperimentFileInfo::validate () const
Definition at line 142 of file CExperimentFileInfo.cpp.
References mLines, and mList.
Referenced by sync(), validateFirst(), and validateLast().
 {
   size_t Last = 0;
   size_t i, imax;
   for (i = 0, imax = mList.size(); i < imax; i++)
     {
       if (Last >= mList[i]->First) return false;
       Last = mList[i]->Last;
       if (Last > mLines) return false;
     }
   return true;
 }
bool CExperimentFileInfo::validateFirst (const size_t & index, const size_t & value)
Definition at line 159 of file CExperimentFileInfo.cpp.
References mLines, mList, and validate().
Referenced by CQExperimentDataValidator::validate().
 {
   if (mLines < value ||
       mList[index]->Last < value ||
       (value == mList[index]->Last &&
        value == mList[index]->pExperiment->getHeaderRow())) return false;
   size_t Saved = mList[index]->First;
   mList[index]->First = value;
   bool Result = validate();
   mList[index]->First = Saved;
   return Result;
 }
bool CExperimentFileInfo::validateHeader (const size_t & index, const size_t & value)
Definition at line 193 of file CExperimentFileInfo.cpp.
References mLines, and mList.
Referenced by CQExperimentDataValidator::validate().
 {
   return (value <= mLines &&
           (mList[index]->First < mList[index]->Last ||
            value < mList[index]->First ||
            mList[index]->Last < value));
 }
bool CExperimentFileInfo::validateLast (const size_t & index, const size_t & value)
Definition at line 176 of file CExperimentFileInfo.cpp.
References mLines, mList, and validate().
Referenced by CQExperimentDataValidator::validate().
 {
   if (mLines < value ||
       value < mList[index]->First ||
       (value == mList[index]->First &&
        value == mList[index]->pExperiment->getHeaderRow())) return false;
   size_t Saved = mList[index]->Last;
   mList[index]->Last = value;
   bool Result = validate();
   mList[index]->Last = Saved;
   return Result;
 }
Member Data Documentation
std::vector< size_t > CExperimentFileInfo::mEmptyLines private
Definition at line 188 of file CExperimentFileInfo.h.
Referenced by adjustForEmptyLines(), and setFileName().
std::string CExperimentFileInfo::mFileName private
Definition at line 168 of file CExperimentFileInfo.h.
Referenced by getFileName(), setFileName(), and sync().
size_t CExperimentFileInfo::mLines private
Definition at line 178 of file CExperimentFileInfo.h.
Referenced by getNextUnusedSection(), setFileName(), validate(), validateFirst(), validateHeader(), and validateLast().
std::vector< CExperimentInfo * > CExperimentFileInfo::mList private
Definition at line 173 of file CExperimentFileInfo.h.
Referenced by getExperiment(), getExperimentNames(), getNextUnusedSection(), sync(), validate(), validateFirst(), validateHeader(), validateLast(), and ~CExperimentFileInfo().
CExperimentSet* CExperimentFileInfo::mpSet private
Definition at line 163 of file CExperimentFileInfo.h.
Referenced by sync().
size_t CExperimentFileInfo::mUsedEnd private
Definition at line 183 of file CExperimentFileInfo.h.
Referenced by adjustForEmptyLines(), getFirstUnusedSection(), getNextUnusedSection(), and sync().
The documentation for this class was generated from the following files:
CExperimentFileInfo.h
CExperimentFileInfo.cpp