COPASI API: CFitItem.cpp File Reference
CFitItem.cpp File Reference
#include <limits>
#include <cmath>
#include "copasi.h"
#include "CFitItem.h"
#include "report/CKeyFactory.h"
#include "utilities/CCopasiParameterGroup.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "copasi/report/CCopasiRootContainer.h"
Functions
std::ostream & operator<< (std::ostream &os, const CFitItem &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CFitItem & o)
Output stream operator
Parameters
ostream & os
const CFitItem & A
Returns
ostream & os
Definition at line 136 of file CFitItem.cpp.
References CFitItem::getCrossValidation(), CFitItem::getExperiment(), CFitItem::mpGrpAffectedCrossValidations, CFitItem::mpGrpAffectedExperiments, and CCopasiParameterGroup::size().
 {
   os << * static_cast<const COptItem *>(&o) << std::endl;
   size_t i, imax = o.mpGrpAffectedExperiments->size();
   os << "    Affected Experiments:" << std::endl << "      ";
   if (imax == 0) os << "all";
   for (i = 0; i < imax; i++)
     {
       if (i) os << ", ";
       os << o.getExperiment(i);
     }
   imax = o.mpGrpAffectedCrossValidations->size();
   os << "    Affected Validation Experiments:" << std::endl << "      ";
   if (imax == 0) os << "all";
   for (i = 0; i < imax; i++)
     {
       if (i) os << ", ";
       os << o.getCrossValidation(i);
     }
   return os;
 }