COPASI API: SBMLDocumentLoader Class Reference
SBMLDocumentLoader Class Reference
#include <SBMLDocumentLoader.h>
Static Public Member Functions
static void combineMaps (const std::map< std::string, std::string > &sourceMap, std::map< std::string, std::string > &destMap)
static void convertLayoutObjectIds (CLLocalStyle &style, const std::map< std::string, std::string > &idToKeyMap)
static void convertLayoutObjectKeys (LocalStyle &style, const std::map< std::string, std::string > &keyToIdMap)
static void convertPropertyIds (CLTransformation2D *pObject, const std::map< std::string, std::string > &colorIdToKeyMap, const std::map< std::string, std::string > &gradientIdToKeyMap, const std::map< std::string, std::string > &lineEndingIdToKeyMap)
template<typename RENDER_INFORMATION >
static void convertRenderInformationReferencesIds (CCopasiVector< RENDER_INFORMATION > &list, const std::map< std::string, std::string > &idToKeyMap)
template<typename RENDER_INFORMATION >
static void convertRenderInformationReferencesKeys (ListOf &list, const std::map< std::string, std::string > &keyToIdMap)
static CLayout * createLayout (const Layout &sbmlLayout, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const std::map< std::string, std::string > &globalIdToKeyMap, const CCopasiContainer *pParent=NULL)
static void readListOfLayouts (CListOfLayouts &lol, const ListOf &sbmlList, const std::map< CCopasiObject *, SBase * > &copasimodelmap)
Static Protected Member Functions
static void postprocessTextGlyph (const TextGlyph &sbml, const std::map< std::string, std::string > &layoutmap)
Detailed Description
Definition at line 43 of file SBMLDocumentLoader.h.
Member Function Documentation
void SBMLDocumentLoader::combineMaps (const std::map< std::string, std::string > & sourceMap, std::map< std::string, std::string > & destMap) static
converts references to color keys, gradient keys and/or line ending keys in graphical primitives to references to the corresponding Ids. template<typename RENDER_INFORMATION> static void convertPropertyKeys(RENDER_INFORMATION* pObject, const std::map<std::string,std::string>& colorKeyToIdMap, const std::map<std::string,std::string>& gradientKeyToIdMap, const std::map<std::string,std::string>& lineEndingKeyToIdMap); converts references to color keys, gradient keys and/or line ending keys in graphical primitives to references to the corresponding Ids. static void convertPropertyKeys(Transformation2D* pObject, const std::map<std::string,std::string>& colorKeyToIdMap, const std::map<std::string,std::string>& gradientKeyToIdMap, const std::map<std::string,std::string>& lineEndingKeyToIdMap); converts references to color ids in gradient stops to references to the corresponding keys. static void convertColorKeys(GradientBase& gradient, const std::map<std::string,std::string>& colorKeyToIdMap); Adds all elements of the source map into the dest map if an element with the same key does not already exist in the dest map.
converts references to color keys, gradient keys and/or line ending keys in graphical primitives to references to the corresponding Ids. void SBMLDocumentLoader::convertPropertyKeys(Transformation2D* pObject, const std::map<std::string,std::string>& colorKeyToIdMap, const std::map<std::string,std::string>& gradientKeyToIdMap, const std::map<std::string,std::string>& lineEndingKeyToIdMap) { GraphicalPrimitive1D* pGP1=dynamic_cast<GraphicalPrimitive1D*>(pObject); if(pGP1 != NULL) { std::map<std::string,std::string>::const_iterator pos; fix the stroke color std::string s=pGP1->getStroke(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none" && s[0] != '#') { pos=colorKeyToIdMap.find(s); check if we found the color, else it must be a gradient if(pos==colorKeyToIdMap.end()) { pos=gradientKeyToIdMap.find(s); assert(pos != gradientKeyToIdMap.end()); pGP1->setStroke(pos->second); } else { pGP1->setStroke(pos->second); } } GraphicalPrimitive2D* pGP2=dynamic_cast<GraphicalPrimitive2D*>(pObject); if(pGP2 != NULL) { fix the fill color std::string s=pGP2->getFillColor(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none" && s[0] != '#') { pos=colorKeyToIdMap.find(s); check if we found the color, else it must be a gradient if(pos==colorKeyToIdMap.end()) { pos=gradientKeyToIdMap.find(s); assert(pos != gradientKeyToIdMap.end()); pGP2->setFillColor(pos->second); } else { pGP2->setFillColor(pos->second); } } Group* pG=dynamic_cast<Group*>(pObject); if(pG != NULL) { fix the line endings s=pG->getStartHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingKeyToIdMap.find(s); assert(pos != lineEndingKeyToIdMap.end()); pG->setStartHead(pos->second); } s=pG->getEndHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingKeyToIdMap.find(s); assert(pos != lineEndingKeyToIdMap.end()); pG->setEndHead(pos->second); } call this method for all children size_t i,iMax=pG->getNumElements(); for(i=0; i < iMax; ++i) { SBMLDocumentLoader::convertPropertyKeys(dynamic_cast<Transformation2D*>(pG->getElement(i)),colorKeyToIdMap,gradientKeyToIdMap,lineEndingKeyToIdMap); } } } else { RenderCurve* pC=dynamic_cast<RenderCurve*>(pObject); if(pC != NULL) { fix the line endings s=pC->getStartHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingKeyToIdMap.find(s); assert(pos != lineEndingKeyToIdMap.end()); pC->setStartHead(pos->second); } s=pC->getEndHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingKeyToIdMap.find(s); assert(pos != lineEndingKeyToIdMap.end()); pC->setEndHead(pos->second); } } } } } converts references to color ids in gradient stops to references to the corresponding keys. void SBMLDocumentLoader::convertColorKeys(GradientBase& gradient, const std::map<std::string,std::string>& colorKeyToIdMap) { size_t i,iMax=gradient.getNumGradientStops(); GradientStop* pStop=NULL; std::map<std::string,std::string>::const_iterator pos; for(i=0; i < iMax; ++i) { pStop=gradient.getGradientStop(i); std::string color=pStop->getStopColor(); if(color.find_first_not_of(" \t\n\r") != std::string::npos && color != "none" && color[0] != '#') { pos=colorKeyToIdMap.find(color); assert(pos!=colorKeyToIdMap.end()); pStop->setStopColor(pos->second); } } } Adds all elements of the source map into the dest map if an element with the same key does not already exist in the dest map.
Definition at line 601 of file SBMLDocumentLoader.cpp.
 {
   std::map<std::string, std::string>::const_iterator it = sourceMap.begin(), endit = sourceMap.end();
   while (it != endit)
     {
       if (destMap.find(it->first) == destMap.end())
         {
           destMap.insert(*it);
         }
       ++it;
     }
 }
void SBMLDocumentLoader::convertLayoutObjectIds (CLLocalStyle & style, const std::map< std::string, std::string > & idToKeyMap) static
Converts references to ids of layout objects to the corresponding key.
Definition at line 313 of file SBMLDocumentLoader.cpp.
References CLLocalStyle::getKeyList(), and CLLocalStyle::setKeyList().
Referenced by createLayout().
 {
   std::set<std::string> keys;
   std::map<std::string, std::string>::const_iterator pos;
   std::set<std::string>::const_iterator it = style.getKeyList().begin(), endit = style.getKeyList().end();
   while (it != endit)
     {
       pos = idToKeyMap.find(*it);
       assert(pos != idToKeyMap.end());
       keys.insert(pos->second);
       ++it;
     }
   style.setKeyList(keys);
 }
void SBMLDocumentLoader::convertLayoutObjectKeys (LocalStyle & style, const std::map< std::string, std::string > & keyToIdMap) static
Converts references to keys of layout objects to the corresponding id.
converts references to color ids, gradient ids and/or line ending ids in graphical primitives to references to the corresponding keys. void SBMLDocumentLoader::convertPropertyIds(CLTransformation2D* pObject, const std::map<std::string,std::string>& colorIdToKeyMap, const std::map<std::string,std::string>& gradientIdToKeyMap, const std::map<std::string,std::string>& lineEndingIdToKeyMap) { CLGraphicalPrimitive1D* pGP1=dynamic_cast<CLGraphicalPrimitive1D*>(pObject); if(pGP1 != NULL) { std::map<std::string,std::string>::const_iterator pos; fix the stroke color std::string s=pGP1->getStroke(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none" && s[0] != '#') { pos=colorIdToKeyMap.find(s); check if we found the color, else it must be a gradient if(pos==colorIdToKeyMap.end()) { pos=gradientIdToKeyMap.find(s); assert(pos != gradientIdToKeyMap.end()); pGP1->setStroke(pos->second); } else { pGP1->setStroke(pos->second); } } CLGraphicalPrimitive2D* pGP2=dynamic_cast<CLGraphicalPrimitive2D*>(pObject); if(pGP2 != NULL) { fix the fill color std::string s=pGP2->getFillColor(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none" && s[0] != '#') { pos=colorIdToKeyMap.find(s); check if we found the color, else it must be a gradient if(pos==colorIdToKeyMap.end()) { pos=gradientIdToKeyMap.find(s); assert(pos != gradientIdToKeyMap.end()); pGP2->setFillColor(pos->second); } else { pGP2->setFillColor(pos->second); } } CLGroup* pG=dynamic_cast<CLGroup*>(pObject); if(pG != NULL) { fix the line endings s=pG->getStartHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingIdToKeyMap.find(s); assert(pos != lineEndingIdToKeyMap.end()); pG->setStartHead(pos->second); } s=pG->getEndHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingIdToKeyMap.find(s); assert(pos != lineEndingIdToKeyMap.end()); pG->setEndHead(pos->second); } call this method for all children size_t i,iMax=pG->getNumElements(); for(i=0; i < iMax; ++i) { SBMLDocumentLoader::convertPropertyIds(dynamic_cast<CLTransformation2D*>(pG->getElement(i)),colorIdToKeyMap,gradientIdToKeyMap,lineEndingIdToKeyMap); } } } else { CLRenderCurve* pC=dynamic_cast<CLRenderCurve*>(pObject); if(pC != NULL) { fix the line endings s=pC->getStartHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingIdToKeyMap.find(s); assert(pos != lineEndingIdToKeyMap.end()); pC->setStartHead(pos->second); } s=pC->getEndHead(); if(s.find_first_not_of(" \t\n\r") != std::string::npos && s != "none") { pos=lineEndingIdToKeyMap.find(s); assert(pos != lineEndingIdToKeyMap.end()); pC->setEndHead(pos->second); } } } } } converts references to color ids in gradient stops to references to the corresponding keys. void SBMLDocumentLoader::convertColorIds(CLGradientBase& gradient, const std::map<std::string,std::string>& colorIdToKeyMap) { size_t i,iMax=gradient.getNumGradientStops(); CLGradientStop* pStop=NULL; std::map<std::string,std::string>::const_iterator pos; for(i=0; i < iMax; ++i) { pStop=gradient.getGradientStop(i); std::string color=pStop->getStopColor(); if(color.find_first_not_of(" \t\n\r") != std::string::npos && color != "none" && color[0] != '#') { pos=colorIdToKeyMap.find(color); assert(pos!=colorIdToKeyMap.end()); pStop->setStopColor(pos->second); } } } Converts references to keys of layout objects to the corresponding id.
Definition at line 457 of file SBMLDocumentLoader.cpp.
Referenced by CLayout::exportToSBML().
 {
   std::set<std::string> ids;
   std::map<std::string, std::string>::const_iterator pos;
   std::set<std::string>::const_iterator it = style.getIdList().begin(), endit = style.getIdList().end();
   while (it != endit)
     {
       pos = keyToIdMap.find(*it);
       assert(pos != keyToIdMap.end());
       ids.insert(pos->second);
       ++it;
     }
   style.setIdList(ids);
 }
static void SBMLDocumentLoader::convertPropertyIds (CLTransformation2D * pObject, const std::map< std::string, std::string > & colorIdToKeyMap, const std::map< std::string, std::string > & gradientIdToKeyMap, const std::map< std::string, std::string > & lineEndingIdToKeyMap) static
converts references to color ids, gradient ids and/or line ending ids in graphical primitives to references to the corresponding keys.
template<typename RENDER_INFORMATION > static void SBMLDocumentLoader::convertRenderInformationReferencesIds (CCopasiVector< RENDER_INFORMATION > & list, const std::map< std::string, std::string > & idToKeyMap) inline static
converts the sbml id for render render information objects into the corresponding copasi key where they are used in a reference. This is used for the import from SBML.
Definition at line 75 of file SBMLDocumentLoader.h.
References CCopasiVector< T >::size().
   {
     size_t i, iMax = list.size();
     RENDER_INFORMATION* pRI = NULL;
     std::map<std::string, std::string>::const_iterator pos;
     for (i = 0; i < iMax; ++i)
       {
         pRI = list[i];
         if (pRI->getReferenceRenderInformationKey().find_first_not_of(" \t\n\r") != std::string::npos)
           {
             pos = idToKeyMap.find(pRI->getReferenceRenderInformationKey());
             assert(pos != idToKeyMap.end());
             pRI->setReferenceRenderInformationKey(pos->second);
           }
       }
   }
template<typename RENDER_INFORMATION > static void SBMLDocumentLoader::convertRenderInformationReferencesKeys (ListOf & list, const std::map< std::string, std::string > & keyToIdMap) inline static
converts references to color ids in gradient stops to references to the corresponding keys. static void convertColorIds(CLGradientBase& gradient, const std::map<std::string,std::string>& colorIdToKeyMap); converts the copasi key for global render information objects into the corresponding sbml id where they are used in a reference. This is used for the SBML export.
Definition at line 122 of file SBMLDocumentLoader.h.
   {
     size_t i, iMax = list.size();
     RENDER_INFORMATION* pRI = NULL;
     std::map<std::string, std::string>::const_iterator pos;
     for (i = 0; i < iMax; ++i)
       {
         pRI = dynamic_cast<RENDER_INFORMATION*>(list.get((unsigned int) i));
         assert(pRI != NULL);
         if (pRI->getReferenceRenderInformationId().find_first_not_of(" \t\n\r") != std::string::npos)
           {
             pos = keyToIdMap.find(pRI->getReferenceRenderInformationId());
             assert(pos != keyToIdMap.end());
             pRI->setReferenceRenderInformationId(pos->second);
           }
       }
   }
CLayout * SBMLDocumentLoader::createLayout (const Layout & sbmlLayout, const std::map< std::string, std::string > & modelmap, std::map< std::string, std::string > & layoutmap, const std::map< std::string, std::string > & globalIdToKeyMap, const CCopasiContainer * pParent = NULL) static
Definition at line 142 of file SBMLDocumentLoader.cpp.
References CLayout::addCompartmentGlyph(), CLayout::addGeneralGlyph(), CLayout::addLocalRenderInformation(), CLayout::addMetaboliteGlyph(), CLayout::addReactionGlyph(), CLayout::addTextGlyph(), C_INT32, convertLayoutObjectIds(), CLRenderInformationBase::getKey(), CLayout::getListOfLocalRenderInformationObjects(), CLLocalRenderInformation::getNumStyles(), CLLocalRenderInformation::getStyle(), and postprocessTextGlyph().
Referenced by DataModelGUI::importCellDesigner(), and readListOfLayouts().
 {
   CLayout* layout = new CLayout(sbmlLayout, layoutmap, pParent);
   //compartments
   unsigned C_INT32 i, iMax = sbmlLayout.getListOfCompartmentGlyphs()->size();
   for (i = 0; i < iMax; ++i)
     {
       const CompartmentGlyph* tmp
       = dynamic_cast<const CompartmentGlyph*>(sbmlLayout.getListOfCompartmentGlyphs()->get(i));
       if (tmp)
         layout->addCompartmentGlyph(new CLCompartmentGlyph(*tmp, modelmap, layoutmap));
     }
   //species
   iMax = sbmlLayout.getListOfSpeciesGlyphs()->size();
   for (i = 0; i < iMax; ++i)
     {
       const SpeciesGlyph* tmp
       = dynamic_cast<const SpeciesGlyph*>(sbmlLayout.getListOfSpeciesGlyphs()->get(i));
       if (tmp)
         layout->addMetaboliteGlyph(new CLMetabGlyph(*tmp, modelmap, layoutmap));
     }
   //reactions
   iMax = sbmlLayout.getListOfReactionGlyphs()->size();
   for (i = 0; i < iMax; ++i)
     {
       const ReactionGlyph* tmp
       = dynamic_cast<const ReactionGlyph*>(sbmlLayout.getListOfReactionGlyphs()->get(i));
       if (tmp)
         layout->addReactionGlyph(new CLReactionGlyph(*tmp, modelmap, layoutmap));
     }
   //text
   iMax = sbmlLayout.getListOfTextGlyphs()->size();
   for (i = 0; i < iMax; ++i)
     {
       const TextGlyph* tmp
       = dynamic_cast<const TextGlyph*>(sbmlLayout.getListOfTextGlyphs()->get(i));
       if (tmp)
         layout->addTextGlyph(new CLTextGlyph(*tmp, modelmap, layoutmap));
     }
   //additional
   iMax = sbmlLayout.getListOfAdditionalGraphicalObjects()->size();
   for (i = 0; i < iMax; ++i)
     {
       const GraphicalObject* graphical
       = dynamic_cast<const GraphicalObject*>(sbmlLayout.getListOfAdditionalGraphicalObjects()->get(i));
       if (graphical)
         layout->addGeneralGlyph(new CLGeneralGlyph(*graphical, modelmap, layoutmap));
     }
   //second pass text (the text glyph can refer to other glyphs. These references can)
   //only be resolved after all glyphs are created).
   iMax = sbmlLayout.getListOfTextGlyphs()->size();
   for (i = 0; i < iMax; ++i)
     {
       const TextGlyph* tmp
       = dynamic_cast<const TextGlyph*>(sbmlLayout.getListOfTextGlyphs()->get(i));
       if (tmp)
         postprocessTextGlyph(*tmp, layoutmap);
     }
   RenderLayoutPlugin* rlPlugin = (RenderLayoutPlugin*) sbmlLayout.getPlugin("render");
   assert(rlPlugin != NULL);
   // import the local render information
   iMax = rlPlugin->getNumLocalRenderInformationObjects();
   std::map<std::string, std::string> idToKeyMap;
   CLLocalRenderInformation* pLRI = NULL;
   for (i = 0; i < iMax; ++i)
     {
       //colorIdToKeyMap.clear();
       //gradientIdToKeyMap.clear();
       //lineEndingIdToKeyMap.clear();
       //pLRI=new CLLocalRenderInformation(*sbmlLayout.getRenderInformation(i),colorIdToKeyMap,gradientIdToKeyMap,lineEndingIdToKeyMap,layout);
       pLRI = new CLLocalRenderInformation(*rlPlugin->getRenderInformation(i), layout);
       if (rlPlugin->getRenderInformation(i)->isSetId())
         idToKeyMap.insert(std::pair<std::string, std::string>(rlPlugin->getRenderInformation(i)->getId(), pLRI->getKey()));
       else
         idToKeyMap.insert(std::pair<std::string, std::string>(pLRI->getKey(), pLRI->getKey()));
       //colorIdToKeyMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pLRI->getKey(),colorIdToKeyMap));
       //gradientIdToKeyMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pLRI->getKey(),gradientIdToKeyMap));
       //lineEndingIdToKeyMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pLRI->getKey(),lineEndingIdToKeyMap));
       // fix the references to layout objects in id lists
       size_t j, jMax = pLRI->getNumStyles();
       for (j = 0; j < jMax; j++)
         {
           SBMLDocumentLoader::convertLayoutObjectIds(*(pLRI->getStyle(j)), layoutmap);
         }
       layout->addLocalRenderInformation(pLRI);
     }
   // fix the references
   // we have to consider the global ids as well
   // since all ids in these two map should be unique, we can just combine them
   size_t count = idToKeyMap.size() + globalIdToKeyMap.size();
   idToKeyMap.insert(globalIdToKeyMap.begin(), globalIdToKeyMap.end());
   // make sure the ids were really unique
   assert(idToKeyMap.size() == count);
   SBMLDocumentLoader::convertRenderInformationReferencesIds<CLLocalRenderInformation>(layout->getListOfLocalRenderInformationObjects(), idToKeyMap);
   // fix the color ids, gradient ids and line ending ids.
   return layout;
 }
void SBMLDocumentLoader::postprocessTextGlyph (const TextGlyph & sbml, const std::map< std::string, std::string > & layoutmap) static protected
resolves the graphical object reference of the text glyph
Definition at line 273 of file SBMLDocumentLoader.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), and CLTextGlyph::setGraphicalObjectKey().
Referenced by createLayout().
 {
   //the corresponding CLTextGlyph should already exist. Let's find it...
   CLTextGlyph * pTg = NULL;
   if (sbml.getId() != "")
     {
       std::map<std::string, std::string>::const_iterator it = layoutmap.find(sbml.getId());
       if (it != layoutmap.end())
         pTg = dynamic_cast<CLTextGlyph *>(CCopasiRootContainer::getKeyFactory()->get(it->second));
       if (!pTg)
         {
           //error?
           return;
         }
     }
   else
     {
       //error?
       return;
     }
   //resolve the graphical object reference
   assert(pTg);
   if (sbml.getGraphicalObjectId() != "")
     {
       std::map<std::string, std::string>::const_iterator it = layoutmap.find(sbml.getGraphicalObjectId());
       if (it != layoutmap.end())
         pTg->setGraphicalObjectKey(it->second);
     }
 }
void SBMLDocumentLoader::readListOfLayouts (CListOfLayouts & lol, const ListOf & sbmlList, const std::map< CCopasiObject *, SBase * > & copasimodelmap) static
Definition at line 47 of file SBMLDocumentLoader.cpp.
References CListOfLayouts::addGlobalRenderInformation(), CListOfLayouts::addLayout(), C_INT32, createLayout(), SBMLUtils::getIdFromSBase(), CLRenderInformationBase::getKey(), and CListOfLayouts::getListOfGlobalRenderInformationObjects().
Referenced by SBMLImporter::parseSBML().
 {
   unsigned C_INT32 i, iMax;
   // read the global render information
   const ListOfLayouts* pLoL = dynamic_cast<const ListOfLayouts*>(&sbmlList);
   assert(pLoL != NULL);
   RenderListOfLayoutsPlugin* rlolPlugin = (RenderListOfLayoutsPlugin*) pLoL ->getPlugin("render");
   if (rlolPlugin == NULL)
     {
       const_cast<SBMLDocument *>(pLoL->getSBMLDocument())->enablePackage(RenderExtension::getXmlnsL3V1V1(), "render", true);
       rlolPlugin = (RenderListOfLayoutsPlugin*) pLoL ->getPlugin("render");
     }
   iMax = rlolPlugin->getNumGlobalRenderInformationObjects();
   std::map<std::string, std::string> idToKeyMap;
   CLGlobalRenderInformation* pGRI = NULL;
   /*
   std::map<std::string,std::string> colorIdToKeyMap;
   std::map<std::string,std::string> gradientIdToKeyMap;
   std::map<std::string,std::string> lineEndingIdToKeyMap;
   std::map<std::string,std::map<std::string,std::string> > colorIdToKeyMapMap;
   std::map<std::string,std::map<std::string,std::string> > gradientIdToKeyMapMap;
   std::map<std::string,std::map<std::string,std::string> > lineEndingIdToKeyMapMap;
   */
   for (i = 0; i < iMax; ++i)
     {
       //colorIdToKeyMap.clear();
       //gradientIdToKeyMap.clear();
       //lineEndingIdToKeyMap.clear();
       //pGRI=new CLGlobalRenderInformation(*pLoL->getRenderInformation(i),colorIdToKeyMap,gradientIdToKeyMap,lineEndingIdToKeyMap,&lol);
       pGRI = new CLGlobalRenderInformation(*rlolPlugin->getRenderInformation(i), &lol);
       if (rlolPlugin->getRenderInformation(i)->isSetId())
         idToKeyMap.insert(std::pair<std::string, std::string>(rlolPlugin->getRenderInformation(i)->getId(), pGRI->getKey()));
       else
         idToKeyMap.insert(std::pair<std::string, std::string>(pGRI->getKey(), pGRI->getKey()));
       //colorIdToKeyMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pGRI->getKey(),colorIdToKeyMap));
       //gradientIdToKeyMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pGRI->getKey(),gradientIdToKeyMap));
       //lineEndingIdToKeyMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pGRI->getKey(),lineEndingIdToKeyMap));
       lol.addGlobalRenderInformation(pGRI);
     }
   // fix the references
   SBMLDocumentLoader::convertRenderInformationReferencesIds<CLGlobalRenderInformation>(lol.getListOfGlobalRenderInformationObjects(), idToKeyMap);
   // fix the color ids, gradient ids and line ending ids.
   //convert the map as used by the CLxxx constructors
   std::map<std::string, std::string> modelmap;
   std::string s1, s2;
   std::map<CCopasiObject*, SBase*>::const_iterator it;
   std::map<CCopasiObject*, SBase*>::const_iterator itEnd = copasimodelmap.end();
   for (it = copasimodelmap.begin(); it != itEnd; ++it)
     {
       s1 = SBMLUtils::getIdFromSBase(it->second);
       if (it->first)
         s2 = it->first->getKey();
       else
         s2 = "";
       if ((s1 != "") && (s2 != ""))
         modelmap[s1] = s2;
     }
   //iterate through list of layouts
   iMax = sbmlList.size();
   for (i = 0; i < iMax; ++i)
     {
       std::map<std::string, std::string> layoutmap;
       const Layout* tmp
       = dynamic_cast<const Layout*>(sbmlList.get(i));
       if (tmp)
         {
           //CLayout * pLayout = createLayout(*tmp, modelmap, layoutmap,idToKeyMap,expandedColorIdToKeyMapMap,expandedGradientIdToKeyMapMap,expandedLineEndingIdToKeyMapMap);
           CLayout * pLayout = createLayout(*tmp, modelmap, layoutmap, idToKeyMap);
           lol.addLayout(pLayout, layoutmap);
         }
     }
   //TODO: the layout object should be added to the copasimodelmap. However,
   //if this is done, the object also need to be removed if necessary in the
   //sbml exporter (see comment in CListOfLayouts::exportToSBML()).
 }
The documentation for this class was generated from the following files:
SBMLDocumentLoader.h
SBMLDocumentLoader.cpp