COPASI API: test000074 Class Reference
test000074 Class Reference
#include <test000074.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1088 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1088)
CPPUNIT_TEST_SUITE (test000074)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 26 of file test000074.h.
Member Function Documentation
test000074::CPPUNIT_TEST (test_bug1088) private
test000074::CPPUNIT_TEST_SUITE (test000074) private
test000074::CPPUNIT_TEST_SUITE_END () private
void test000074::setUp ()
Definition at line 33 of file test000074.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000074::tearDown ()
Definition at line 41 of file test000074.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000074::test_bug1088 ()
Definition at line 46 of file test000074.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   std::string s = pDataModel->exportSBMLToString(NULL, 2, 3);
   CPPUNIT_ASSERT(!s.empty());
 }
Member Data Documentation
const char * test000074::MODEL_STRING1 static protected
Definition at line 33 of file test000074.h.
Referenced by test_bug1088().
CCopasiDataModel * test000074::pCOPASIDATAMODEL = NULL static protected
Make sure importing a model with COPASI MIRIAM annotation and exporting it again does not CRASH
Definition at line 34 of file test000074.h.
Referenced by setUp(), and test_bug1088().
The documentation for this class was generated from the following files:
test000074.h
test000074.cpp