COPASI API: CMiaseBase Class Reference
CMiaseBase Class Reference
#include <CMiaseBase.h>
Public Member Functions
void addAnnotation (CMiaseAnnotation *ann)
void addNotes (CMiaseNotes *notes)
CMiaseBase ()
CMiaseAnnotation * getAnnotation ()
std::string getMetaId ()
CMiaseNotes * getNotes ()
void setAnyNote (std::string anyAnnotation)
void setMetaId (std::string metaId)
void setXmlNs (std::string xmlNs)
~CMiaseBase ()
Private Attributes
std::string mMetaId
CMiaseAnnotation * mpAnnotation
CMiaseNotes * mpNotes
Detailed Description
Definition at line 62 of file CMiaseBase.h.
Constructor & Destructor Documentation
CMiaseBase::CMiaseBase ()
Definition at line 73 of file CMiaseBase.cpp.
 {}
CMiaseBase::~CMiaseBase ()
Definition at line 76 of file CMiaseBase.cpp.
 {}
Member Function Documentation
void CMiaseBase::addAnnotation (CMiaseAnnotation * ann)
Definition at line 89 of file CMiaseBase.cpp.
References mpAnnotation.
Referenced by CMiaseParser::newAnnotation().
 {
   mpAnnotation = ann;
 }
void CMiaseBase::addNotes (CMiaseNotes * notes)
Definition at line 99 of file CMiaseBase.cpp.
References mpNotes.
Referenced by CMiaseParser::newNotes().
 {
   mpNotes = notes;
 }
CMiaseAnnotation * CMiaseBase::getAnnotation ()
Definition at line 94 of file CMiaseBase.cpp.
References mpAnnotation.
Referenced by CMiaseParser::endElement().
 {
   return mpAnnotation;
 }
std::string CMiaseBase::getMetaId ()
Definition at line 79 of file CMiaseBase.cpp.
References mMetaId.
 {
   return mMetaId;
 }
CMiaseNotes * CMiaseBase::getNotes ()
Definition at line 104 of file CMiaseBase.cpp.
References mpNotes.
Referenced by CMiaseParser::endElement(), and CMiaseParser::testDataStructure().
 {
   return mpNotes;
 }
void CMiaseBase::setAnyNote (std::string anyAnnotation)
void CMiaseBase::setMetaId (std::string metaId)
Definition at line 84 of file CMiaseBase.cpp.
References mMetaId.
 {
   mMetaId = metaId;
 }
void CMiaseBase::setXmlNs (std::string xmlNs)
Member Data Documentation
std::string CMiaseBase::mMetaId private
Definition at line 86 of file CMiaseBase.h.
Referenced by getMetaId(), and setMetaId().
CMiaseAnnotation* CMiaseBase::mpAnnotation private
Definition at line 88 of file CMiaseBase.h.
Referenced by addAnnotation(), and getAnnotation().
CMiaseNotes* CMiaseBase::mpNotes private
Definition at line 89 of file CMiaseBase.h.
Referenced by addNotes(), and getNotes().
The documentation for this class was generated from the following files:
CMiaseBase.h
CMiaseBase.cpp