COPASI API: CTSSAMethod Class Reference
CTSSAMethod Class Reference abstract
#include <CTSSAMethod.h>
Classes
struct Data
Public Member Functions
void createAnnotationsM ()
CTSSAMethod (const CTSSAMethod &src, const CCopasiContainer *pParent=NULL)
void emptyVectors ()
const int & getCurrentStep () const
const CArrayAnnotation * getTable (std::string name)
const std::vector< std::string > getTableName () const
CVector< C_FLOAT64 > getVec_TimeScale (int step)
virtual void initializeParameter ()
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual void predifineAnnotation ()
C_FLOAT64 returnCurrentTime (int step)
virtual bool setAnnotationM (size_t s)=0
void setCurrentState (CState *currentState)
void setModel (CModel *model)
void setProblem (CTSSAProblem *problem)
void setVectors (int slowMode)
virtual void start (const CState *initialState)
virtual void step (const double &deltaT)
~CTSSAMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CTSSAMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::unset)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes
std::map< std::string,
CArrayAnnotation * > mapTableToName
std::vector< std::string > tableNames
Protected Member Functions
void calculateDerivatives (C_FLOAT64 *X1, C_FLOAT64 *Y1)
void calculateDerivativesX (C_FLOAT64 *X1, C_FLOAT64 *Y1)
CTSSAMethod (const CCopasiMethod::SubType &subType, const CCopasiContainer *pParent=NULL)
bool elevateChildren ()
void evalF (const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
void initializeAtol ()
void initializeIntegrationsParameter ()
void integrationMethodStart (const CState *initialState)
void integrationStep (const double &deltaT)
void map_index (C_FLOAT64 *eval_r, C_INT *index, const C_INT &dim)
void map_index_desc (C_FLOAT64 *eval_r, C_INT *index, const C_INT &dim)
void mat_anal_fast_space (C_INT &slow)
void mat_anal_fast_space_thomas (C_INT &slow)
void mat_anal_metab (C_INT &slow)
void mat_anal_mod (C_INT &slow)
void mat_anal_mod_space (C_INT &slow)
double orthog (C_INT &number1, C_INT &number2)
void schur (C_INT &info)
void schur_desc (C_INT &info)
void sylvester (C_INT slow, C_INT &info)
void update_nid (C_INT *index, C_INT *nid, const C_INT &dim)
void update_pid (C_INT *index, C_INT *pid, const C_INT &dim)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Member Functions
static void EvalF (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
Protected Attributes
CVector< C_FLOAT64 > mAtol
CVector< C_FLOAT64 > mCfast
int mCurrentStep
std::vector< C_FLOAT64 > mCurrentTime
Data mData
C_FLOAT64 mDtol
CVector< C_FLOAT64 > mDWork
C_FLOAT64 mEPS
std::ostringstream mErrorMsg
CVector< C_INT > mIWork
CMatrix< C_FLOAT64 > mJacobian
CMatrix< C_FLOAT64 > mJacobian_initial
C_INT mJType
CLSODA mLSODA
C_INT mLsodaStatus
CState * mpCurrentState
CModel * mpModel
CTSSAProblem * mpProblem
CState * mpState
CMatrix< C_FLOAT64 > mQ
CMatrix< C_FLOAT64 > mQ_desc
CMatrix< C_FLOAT64 > mQz
CMatrix< C_FLOAT64 > mR
CMatrix< C_FLOAT64 > mR_desc
bool mReducedModel
C_FLOAT64 mRtol
C_INT mSlow
C_INT mState
CMatrix< C_FLOAT64 > mTd
CMatrix< C_FLOAT64 > mTd_save
CMatrix< C_FLOAT64 > mTdInverse
CMatrix< C_FLOAT64 > mTdInverse_save
C_FLOAT64 mTime
std::vector< C_INT > mVec_SlowModes
std::vector< CVector< C_FLOAT64 > > mVec_TimeScale
CVector< C_FLOAT64 > mVfast_space
CMatrix< C_FLOAT64 > mVslow
CMatrix< C_FLOAT64 > mVslow_metab
CVector< C_FLOAT64 > mVslow_space
C_FLOAT64 * mY
CVector< C_FLOAT64 > mY_cons
CVector< C_FLOAT64 > mY_initial
CVector< C_FLOAT64 > mYdot
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CTSSAMethod ()
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 41 of file CTSSAMethod.h.
Constructor & Destructor Documentation
CTSSAMethod::CTSSAMethod () private
Default constructor.
CTSSAMethod::CTSSAMethod (const CCopasiMethod::SubType & subType, const CCopasiContainer * pParent = NULL) protected
Default constructor.
Parameters
const CCopasiMethod::SubType & subType
const CCopasiContainer * pParent (default: NULL)
Default constructor.
Definition at line 74 of file CTSSAMethod.cpp.
                                                            :
   CCopasiMethod(CCopasiTask::tssAnalysis, subType, pParent),
   mpCurrentState(NULL),
   mpProblem(NULL),
   mpState(NULL),
   mData(),
   mY(NULL),
   mYdot(),
   mY_initial(),
   mTime(0.0),
   mJacobian(),
   mJacobian_initial(),
   mQ(),
   mQ_desc(),
   mR(),
   mR_desc(),
   mTd(),
   mTdInverse(),
   mQz(),
   mTd_save(),
   mTdInverse_save(),
   mCfast(),
   mY_cons(),
   mVslow(),
   mVslow_metab(),
   mVslow_space(),
   mVfast_space(),
   mSlow(0),
   mLsodaStatus(1),
   mReducedModel(false),
   mRtol(1e-5),
   mAtol(),
   mErrorMsg(),
   mLSODA(),
   mState(0),
   mDWork(),
   mIWork(),
   mJType(0),
   mpModel(NULL),
   mDtol(1e-6),
   mEPS(0.01),
   mVec_SlowModes(),
   mCurrentTime(),
   mVec_TimeScale(),
   mCurrentStep(0)
 {}
CTSSAMethod::CTSSAMethod (const CTSSAMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CTSSAMethod & src
const CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CTSSAMethod & src
Definition at line 126 of file CTSSAMethod.cpp.
                                                           :
   CCopasiMethod(src, pParent),
   mpCurrentState(src.mpCurrentState),
   mpProblem(src.mpProblem),
   mpState(NULL),
   mData(),
   mY(NULL),
   mYdot(),
   mY_initial(),
   mTime(src.mTime),
   mJacobian(),
   mJacobian_initial(),
   mQ(),
   mQ_desc(),
   mR(),
   mR_desc(),
   mTd(),
   mTdInverse(),
   mQz(),
   mTd_save(),
   mTdInverse_save(),
   mCfast(),
   mY_cons(),
   mVslow(),
   mVslow_metab(),
   mVslow_space(),
   mVfast_space(),
   mSlow(0),
   mLsodaStatus(1),
   mReducedModel(src.mReducedModel),
   mRtol(src.mRtol),
   mAtol(src.mAtol),
   mErrorMsg(),
   mLSODA(),
   mState(0),
   mDWork(),
   mIWork(),
   mJType(0),
   mpModel(NULL),
   mDtol(src.mDtol),
   mEPS(src.mEPS),
   mVec_SlowModes(),
   mCurrentTime(),
   mVec_TimeScale(),
   mCurrentStep(0)
 {}
CTSSAMethod::~CTSSAMethod ()
Destructor.
Definition at line 177 of file CTSSAMethod.cpp.
 {}
Member Function Documentation
void CTSSAMethod::calculateDerivatives (C_FLOAT64 * X1, C_FLOAT64 * Y1) protected
Definition at line 1867 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, CModel::calculateDerivatives(), CTSSAMethod::Data::dim, CModel::getCompartments(), CModel::getMetabolites(), CModel::getNumber2QuantityFactor(), CModel::getQuantity2NumberFactor(), mData, mpModel, mReducedModel, CVector< CType >::resize(), and CModel::updateSimulatedValues().
 {
   C_INT i, imax;
   C_INT nmetab;
   nmetab = mData.dim;
   CVector<C_FLOAT64> tmp;
   tmp.resize(nmetab);
   /* make copy of the current state concentrations */
   for (i = 0, imax = nmetab; i < imax; i++)
     tmp[i] = mpModel->getMetabolites()[i]->getValue();
   C_FLOAT64 conc2number = mpModel->getQuantity2NumberFactor() * mpModel->getCompartments()[0]->getInitialValue();
   //C_FLOAT64 conc2number = 1.;
   /* write new concentrations in the current state */
   for (i = 0, imax = nmetab; i < imax; i++)
     mpModel->getMetabolites()[i]->setValue(X1[i]*conc2number);
   mpModel->updateSimulatedValues(mReducedModel);
   mpModel->calculateDerivatives(Y1);
   C_FLOAT64 number2conc = mpModel->getNumber2QuantityFactor() / mpModel->getCompartments()[0]->getInitialValue();
   //C_FLOAT64 number2conc = 1.;
   for (i = 0; i < imax; ++i)
     Y1[i] *= number2conc;
   /* write back concentrations of the current state*/
   for (i = 0, imax = nmetab; i < imax; i++)
     mpModel->getMetabolites()[i]->setValue(tmp[i]);
   mpModel->updateSimulatedValues(mReducedModel);
   return;
 }
void CTSSAMethod::calculateDerivativesX (C_FLOAT64 * X1, C_FLOAT64 * Y1) protected
Definition at line 1824 of file CTSSAMethod.cpp.
References C_FLOAT64, CModel::calculateDerivativesX(), CModel::getCompartments(), CModel::getMetabolitesX(), CModel::getNumber2QuantityFactor(), CModel::getNumIndependentReactionMetabs(), CModel::getQuantity2NumberFactor(), mpModel, mReducedModel, CVector< CType >::resize(), and CModel::updateSimulatedValues().
Referenced by CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), CILDMMethod::newton(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), and CILDMModifiedMethod::step().
 {
   size_t i, imax;
   size_t indep;
   // indep = mpModel->getNumIndependentMetabs();
   indep = mpModel->getNumIndependentReactionMetabs();
   CVector<C_FLOAT64> tmp;
   tmp.resize(indep);
   /* make copy of the current state concentrations */
   for (i = 0, imax = indep; i < imax; i++)
     tmp[i] = mpModel->getMetabolitesX()[i]->getValue();
   C_FLOAT64 conc2number =  mpModel->getQuantity2NumberFactor() * mpModel->getCompartments()[0]->getInitialValue();
   //C_FLOAT64 conc2number = 1.;
   /* write new concentrations in the current state */
   for (i = 0, imax = indep; i < imax; i++)
     mpModel->getMetabolitesX()[i]->setValue(X1[i]*conc2number);
   //mpState->setUpdateDependentRequired(true);
   mpModel->updateSimulatedValues(mReducedModel);
   // TO REMOVE:  mpModel->applyAssignments();
   mpModel->calculateDerivativesX(Y1);
   C_FLOAT64 number2conc = mpModel->getNumber2QuantityFactor() / mpModel->getCompartments()[0]->getInitialValue();
   //C_FLOAT64 number2conc = 1.;
   for (i = 0; i < imax; ++i)
     Y1[i] *= number2conc;
   /* write back concentrations of the current state*/
   for (i = 0, imax = indep; i < imax; i++)
     mpModel->getMetabolitesX()[i]->setValue(tmp[i]);
   //mpState->setUpdateDependentRequired(true);
   mpModel->updateSimulatedValues(mReducedModel);
   return;
 }
void CTSSAMethod::createAnnotationsM ()
create the CArraAnnotations for every ILDM-tab in the CQTSSAResultSubWidget input for each CArraAnnotations is a seperate CMatrix
Create the CArraAnnotations for every ILDM-tab in the CQTSSAResultSubWidget. Input for each CArraAnnotations is a separate CMatrix.
Definition at line 2191 of file CTSSAMethod.cpp.
 {}
CTSSAMethod * CTSSAMethod::createMethod (CCopasiMethod::SubType subType = CCopasiMethod::unset) static
Create a time scale separation analysis method for a special problem. Note: the returned object has to be released after use with delete a problem is also passed so that the method has a chance to choose an appropriate simulation method.
CTSSAMethod class. This class describes the interface to all time scale separation analysis methods. The various method like ILDM or CSP have to be derived from this class.
Definition at line 44 of file CTSSAMethod.cpp.
References fatalError, CCopasiMethod::tssCSP, CCopasiMethod::tssILDM, CCopasiMethod::tssILDMModified, and CCopasiMethod::unset.
Referenced by CQTSSAWidget::createMethod(), and CTSSATask::createMethod().
 {
   CTSSAMethod * pMethod = NULL;
   switch (subType)
     {
       case unset:
       case tssILDM:
         pMethod = new CILDMMethod();
         break;
       case tssILDMModified:
         pMethod = new CILDMModifiedMethod();
         break;
       case tssCSP:
         pMethod = new CCSPMethod();
         break;
       default:
         fatalError();
         break;
     }
   return pMethod;
 }
bool CTSSAMethod::elevateChildren () protected virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 420 of file CTSSAMethod.cpp.
References initializeParameter().
 {
   initializeParameter();
   return true;
 }
void CTSSAMethod::emptyVectors ()
empty every vector to be able to fill them with new values for a new calculation also nullify the step counter
Empty every vector to be able to fill them with new values for a new calculation. Also nullify the step counter.
Definition at line 2178 of file CTSSAMethod.cpp.
Referenced by CQTSSAWidget::runTask().
 {}
void CTSSAMethod::EvalF (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) static protected
Definition at line 2128 of file CTSSAMethod.cpp.
References evalF(), and CTSSAMethod::Data::pMethod.
Referenced by integrationStep().
 {static_cast<Data *>((void *) n)->pMethod->evalF(t, y, ydot);}
void CTSSAMethod::evalF (const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) protected
This evaluates the derivatives
Definition at line 2131 of file CTSSAMethod.cpp.
References CModel::calculateDerivatives(), CModel::calculateDerivativesX(), mpModel, mpState, mReducedModel, CModel::setState(), CState::setTime(), and CModel::updateSimulatedValues().
Referenced by EvalF().
 {
   mpState->setTime(*t);
   mpModel->setState(*mpState);
   // TO REMOVE : mpModel->applyAssignments();
   mpModel->updateSimulatedValues(mReducedModel);
   if (mReducedModel)
     mpModel->calculateDerivativesX(ydot);
   else
     mpModel->calculateDerivatives(ydot);
   return;
 }
const int & CTSSAMethod::getCurrentStep () const
Retrieve the current step
Definition at line 2160 of file CTSSAMethod.cpp.
References mCurrentStep.
Referenced by CQTSSAResultWidget::enterProtected().
 {
   return mCurrentStep;
 }
const CArrayAnnotation* CTSSAMethod::getTable (std::string name) inline
Definition at line 103 of file CTSSAMethod.h.
References mapTableToName.
Referenced by CQTSSAResultSubWidget::changeInterval(), and CQTSSAResultSubWidget::slotTableChanged().
   {return mapTableToName[name];}
const std::vector<std::string> CTSSAMethod::getTableName () const inline
Definition at line 100 of file CTSSAMethod.h.
References tableNames.
Referenced by CQTSSAResultSubWidget::displayResult().
   {return tableNames;}
CVector< C_FLOAT64 > CTSSAMethod::getVec_TimeScale (int step)
return mVec_TimeScale for visualization in ILDM-tab in the CQTSSAResultSubWidget
Definition at line 2169 of file CTSSAMethod.cpp.
References mVec_TimeScale.
Referenced by CQTSSAResultSubWidget::changeInterval().
 {
   return mVec_TimeScale[step - 1];
 }
void CTSSAMethod::initializeAtol () protected
Calculate the individual absolute tolerance
Definition at line 2104 of file CTSSAMethod.cpp.
References CVectorCore< CType >::array(), CStateTemplate::beginIndependent(), C_FLOAT64, CTSSAMethod::Data::dim, CMetab::getCompartment(), CModel::getQuantity2NumberFactor(), CModel::getStateTemplate(), CModelEntity::getValue(), mAtol, mData, mpModel, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by integrationMethodStart().
 {
   //C_FLOAT64 * pTolerance = getValue("Absolute Tolerance").pUDOUBLE;
   mAtol.resize(mData.dim);
   C_FLOAT64 * pAtol = mAtol.array();
   C_FLOAT64 * pEnd = pAtol + mAtol.size();
   CModelEntity *const* ppEntity = mpModel->getStateTemplate().beginIndependent();
   const CMetab * pMetab;
   for (; pAtol != pEnd; ++pAtol, ++ppEntity)
     {
       *pAtol = 1.e-12 ; // *pTolerance;
       // Rescale for metabolites as we are using particle numbers
       if ((pMetab = dynamic_cast< const CMetab * >(*ppEntity)) != NULL)
         {
           *pAtol *=
             pMetab->getCompartment()->getValue() * mpModel->getQuantity2NumberFactor();
         }
     }
 }
void CTSSAMethod::initializeIntegrationsParameter () protected
Initialize integration method parameters
Definition at line 327 of file CTSSAMethod.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CModel::getCompartments(), CCopasiDataModel::getModel(), CCopasiObject::getObjectDataModel(), CCopasiParameterGroup::getParameter(), CModel::getQuantity2NumberFactor(), CCopasiParameter::getValue(), max, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CCopasiParameterGroup::removeParameter(), CCopasiParameterGroup::setValue(), CCopasiVector< T >::size(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), and CCSPMethod::initializeParameter().
 {
   CCopasiParameter *pParm;
   assertParameter("Integrate Reduced Model", CCopasiParameter::BOOL, (bool) true);
   assertParameter("Relative Tolerance", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0e-6);
   assertParameter("Absolute Tolerance", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0e-12);
   assertParameter("Max Internal Steps", CCopasiParameter::UINT, (unsigned C_INT32) 10000);
   // Check whether we have a method with the old parameter names
   if ((pParm = getParameter("LSODA.RelativeTolerance")) != NULL)
     {
       setValue("Relative Tolerance", *pParm->getValue().pUDOUBLE);
       removeParameter("LSODA.RelativeTolerance");
       if ((pParm = getParameter("LSODA.AbsoluteTolerance")) != NULL)
         {
           setValue("Absolute Tolerance", *pParm->getValue().pUDOUBLE);
           removeParameter("LSODA.AbsoluteTolerance");
         }
       if ((pParm = getParameter("LSODA.AdamsMaxOrder")) != NULL)
         {
           removeParameter("LSODA.AdamsMaxOrder");
         }
       if ((pParm = getParameter("LSODA.BDFMaxOrder")) != NULL)
         {
           removeParameter("LSODA.BDFMaxOrder");
         }
       if ((pParm = getParameter("LSODA.MaxStepsInternal")) != NULL)
         {
           setValue("Max Internal Steps", *pParm->getValue().pUINT);
           removeParameter("LSODA.MaxStepsInternal");
         }
     }
   // Check whether we have a method with "Use Default Absolute Tolerance"
   if ((pParm = getParameter("Use Default Absolute Tolerance")) != NULL)
     {
       C_FLOAT64 NewValue;
       if (*pParm->getValue().pBOOL)
         {
           // The default
           NewValue = 1.e-12;
         }
       else
         {
           C_FLOAT64 OldValue = *getValue("Absolute Tolerance").pUDOUBLE;
           CCopasiDataModel* pDataModel = getObjectDataModel();
           assert(pDataModel != NULL);
           CModel * pModel = pDataModel->getModel();
           if (pModel == NULL)
             // The default
             NewValue = 1.e-12;
           else
             {
               const CCopasiVectorNS< CCompartment > & Compartment = pModel->getCompartments();
               size_t i, imax;
               C_FLOAT64 Volume = std::numeric_limits< C_FLOAT64 >::max();
               for (i = 0, imax = Compartment.size(); i < imax; i++)
                 if (Compartment[i]->getValue() < Volume)
                   Volume = Compartment[i]->getValue();
               if (Volume == std::numeric_limits< C_FLOAT64 >::max())
                 // The default
                 NewValue = 1.e-12;
               else
                 // Invert the scaling as best as we can
                 NewValue = OldValue / (Volume * pModel->getQuantity2NumberFactor());
             }
         }
       setValue("Absolute Tolerance", NewValue);
       removeParameter("Use Default Absolute Tolerance");
     }
   // These parameters are no longer supported.
   removeParameter("Adams Max Order");
   removeParameter("BDF Max Order");
   //These parametera are no longer defined by user
   removeParameter("Relative Tolerance");
   removeParameter("Absolute Tolerance");
   removeParameter("Integrate Reduced Model");
   removeParameter("Max Internal Steps");
 }
void CTSSAMethod::initializeParameter () virtual
Initialize the method parameter
Reimplemented in CCSPMethod, CILDMModifiedMethod, and CILDMMethod.
Definition at line 324 of file CTSSAMethod.cpp.
Referenced by elevateChildren().
 {return;}
void CTSSAMethod::integrationMethodStart (const CState * initialState) protected
This instructs the method to prepare for integration starting with the initialState given.
Parameters
const CState * initialState
Definition at line 2055 of file CTSSAMethod.cpp.
References CState::beginIndependent(), CTSSAMethod::Data::dim, CCopasiProblem::getModel(), CModel::getNumDependentReactionMetabs(), CState::getNumIndependent(), CState::getTime(), initializeAtol(), mData, mDWork, mErrorMsg, mIWork, mJacobian, mJType, mLSODA, mLsodaStatus, mpModel, mpProblem, mpState, mReducedModel, mRtol, mState, mTime, mY, mYdot, pdelete, CMatrix< CType >::resize(), CVector< CType >::resize(), and CInternalSolver::setOstream().
Referenced by CILDMMethod::start(), CILDMModifiedMethod::start(), and CCSPMethod::start().
 {
   /* Retrieve the model to calculate */
   mpModel = mpProblem->getModel();
   /* Reset lsoda */
   mLsodaStatus = 1;
   mState = 1;
   mJType = 2;
   mErrorMsg.str("");
   mLSODA.setOstream(mErrorMsg);
   /* Release previous state and make the initialState the current */
   pdelete(mpState);
   mpState = new CState(*initialState);
   mY = mpState->beginIndependent();
   mTime = mpState->getTime();
   if (mReducedModel)
     {
       mData.dim = mpState->getNumIndependent();
     }
   else
     {
       mData.dim = mpState->getNumIndependent() + mpModel->getNumDependentReactionMetabs();
     }
   mYdot.resize(mData.dim);
   // mY_initial.resize(mData.dim);
   mJacobian.resize(mData.dim, mData.dim);
   /* Configure lsoda */
   mRtol = 1.e-6;   // * getValue("Relative Tolerance").pUDOUBLE;
   initializeAtol();
   mDWork.resize(22 + mData.dim * std::max<C_INT>(16, mData.dim + 9));
   mDWork[4] = mDWork[5] = mDWork[6] = mDWork[7] = mDWork[8] = mDWork[9] = 0.0;
   mIWork.resize(20 + mData.dim);
   mIWork[4] = mIWork[6] = mIWork[9] = 0;
   mIWork[5] =  10000 ; // * getValue("Max Internal Steps").pUINT;
   mIWork[7] = 12;
   mIWork[8] = 5;
   return;
 }
void CTSSAMethod::integrationStep (const double & deltaT) protected
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
Definition at line 426 of file CTSSAMethod.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, C_INT, CTSSAMethod::Data::dim, EvalF(), CCopasiMessage::EXCEPTION, mAtol, MCTrajectoryMethod, mData, mDWork, mErrorMsg, mIWork, mJType, mLSODA, mLsodaStatus, mpCurrentState, mpState, mRtol, mState, mTime, mY, CState::setTime(), and CVectorCore< CType >::size().
Referenced by CILDMMethod::step(), CILDMModifiedMethod::step(), and CCSPMethod::step().
 {
   if (mData.dim == 0) //just do nothing if there are no variables
     {
       mTime = mTime + deltaT;
       mpState->setTime(mTime);
       *mpCurrentState = *mpState;
       return;
     }
   C_FLOAT64 EndTime = mTime + deltaT;
   C_INT ITOL = 2; // mRtol scalar, mAtol vector
   C_INT one = 1;
   C_INT DSize = (C_INT) mDWork.size();
   C_INT ISize = (C_INT) mIWork.size();
   mLSODA(&EvalF, //  1. evaluate F
          &mData.dim, //  2. number of variables
          mY, //  3. the array of current concentrations
          &mTime, //  4. the current time
          &EndTime, //  5. the final time
          &ITOL, //  6. error control
          &mRtol, //  7. relative tolerance array
          mAtol.array(), //  8. absolute tolerance array
          &mState, //  9. output by overshoot & interpolation
          &mLsodaStatus, // 10. the state control variable
          &one, // 11. further options (one)
          mDWork.array(), // 12. the double work array
          &DSize, // 13. the double work array size
          mIWork.array(), // 14. the int work array
          &ISize, // 15. the int work array size
          NULL, // 16. evaluate J (not given)
          &mJType);        // 17. the type of jacobian calculate (2)
   // Why did we ignore this error?
   // if (mLsodaStatus == -1) mLsodaStatus = 2;
   if ((mLsodaStatus <= 0))
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 6, mErrorMsg.str().c_str());
     }
   if (mLsodaStatus == 3)
     {
       // It is sufficient to switch to 2. Eventual state changes due to events
       // are indicated via the method stateChanged()
       mLsodaStatus = 2;
     }
   mpState->setTime(mTime);
   *mpCurrentState = *mpState;
   return;
 }
bool CTSSAMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
Definition at line 227 of file CTSSAMethod.cpp.
References CModelEntity::ASSIGNMENT, CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CCopasiMessage::ERROR, fatalError, CModel::getCompartments(), CModel::getEvents(), CModel::getMetabolites(), CCopasiProblem::getModel(), CModel::getModelValues(), CModel::getNumAssignmentMetabs(), CModel::getNumODEMetabs(), CCopasiMethod::getSubType(), CCopasiMethod::isValidProblem(), MCCopasiMethod, MCTSSAMethod, mData, CModelEntity::ODE, CTSSAMethod::Data::pMethod, CCopasiVector< T >::size(), CCopasiMethod::tssCSP, CCopasiMethod::tssILDM, and CCopasiMethod::tssILDMModified.
 {
   if (!CCopasiMethod::isValidProblem(pProblem)) return false;
   const CTSSAProblem * pTP = dynamic_cast<const CTSSAProblem *>(pProblem);
   if (!pTP)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCTSSAMethod + 2);
       return false;
     }
   CModel * pModel = pTP->getModel();
   if (pModel == NULL)
     return false;
   if (pModel->getMetabolites().size() == 0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCCopasiMethod + 3);
       return false;
     }
   if (pModel->getCompartments().size() != 1)
     {
       CCopasiMethod::SubType subType;
       subType = mData.pMethod->getSubType();
       switch (subType)
         {
           case tssILDM:
           case tssILDMModified:
             CCopasiMessage(CCopasiMessage::ERROR, MCTSSAMethod + 16);
             return false;
           case tssCSP:
             return true;
           default:
             fatalError();
             break;
         }
     }
 // Check if the model has a species with an assigments or an ODE
   if (pModel->getNumODEMetabs() != 0 || pModel->getNumAssignmentMetabs() != 0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, "TSSA can not be applyed for systems with species determined by assigments or ODE.");
       return false;
     }
 // Check if the model has a compartment with an ODE
   CCopasiVector< CCompartment >::const_iterator it = pModel->getCompartments().begin();
   CCopasiVector< CCompartment >::const_iterator end = pModel->getCompartments().end();
   for (; it != end; ++it)
     if ((*it)->getStatus() == CModelEntity::ODE || (*it)->getStatus() ==  CModelEntity::ASSIGNMENT)
       {
         CCopasiMessage(CCopasiMessage::ERROR, " TSSA can not be applyed for systems with non-constant  volumes");
         return false;
       }
 // Check if the model has a model parameter  with an ODE
   size_t i;
   for (i = 0; i < pModel->getModelValues().size(); i++)
     {
       if (pModel->getModelValues()[i]->getStatus() == CModelEntity::ODE)
         {
           CCopasiMessage(CCopasiMessage::ERROR, "TSSA can not be applyed for systems with parameters defined by ODE.");
           return false;
         }
     }
 // Check if the model contains events
   if (pModel->getEvents().size() != 0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, "TSSA can not be applyed  for systems with events");
       return false;
     }
   return true;
 }
void CTSSAMethod::map_index (C_FLOAT64 * eval_r, C_INT * index, const C_INT & dim) protected
MAP_INDEX used for sorting of SchurDecompostion
Definition at line 1910 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, and max.
Referenced by schur().
 {
   C_INT i, j, count;
   C_INT max;
   C_FLOAT64 max_value, factor;
   CVector< C_FLOAT64 > abs_eval_r(dim);
   max_value = eval_r[0];
   for (i = 1; i < dim; i++)
     if (eval_r[i] > max_value)
       max_value = eval_r[i];
   if (max_value > 0)
     factor = 1.1;
   else
     {
       if (max_value == 0)
         {
           max_value = 10;
           factor = 1;
         }
       else
         factor = 0.;
     }
   for (i = 0; i < dim; i++)
     {
       index[i] = 0;
       //abs_eval_r[i] = fabs(eval_r[i]);
       abs_eval_r[i] = (eval_r[i]);
     }
   count = dim;
   for (i = 0; i < dim; i++)
     {
       max = i;
       for (j = 0; j < dim; j++)
         {
           //if (abs_eval_r[j] > abs_eval_r[max])
           if (abs_eval_r[j] < abs_eval_r[max])
             max = j;
         }
       index[max] = count;
       abs_eval_r[max] = factor * max_value;
       count --;
     }
   for (i = 0; i < dim - 1; i++)
     if (eval_r[i] == eval_r[i + 1])
       index[i + 1] = index[i];
   return;
 }
void CTSSAMethod::map_index_desc (C_FLOAT64 * eval_r, C_INT * index, const C_INT & dim) protected
This is the test only. We try to reorder the Schur matrix from slowest mode (on the bottom) to the fastest (on the top) The function map_index_desc() is used on the end of schur() in order to produce the orthogonal slow space
Definition at line 1973 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, and min.
Referenced by schur_desc().
 {
   C_INT i, j, count;
   C_INT min;
   C_FLOAT64 min_value, factor;
   CVector< C_FLOAT64 > abs_eval_r(dim);
   factor = 1.1;
   min_value = eval_r[0];
   for (i = 1; i < dim; i++)
     if (eval_r[i] < min_value)
       min_value = eval_r[i];
   for (i = 0; i < dim; i++)
     {
       index[i] = 0;
       //abs_eval_r[i] = fabs(eval_r[i]);
       abs_eval_r[i] = (eval_r[i]);
     }
   count = dim;
   for (i = 0; i < dim; i++)
     {
       min = i;
       for (j = 0; j < dim; j++)
         {
           //if (abs_eval_r[j] > abs_eval_r[max])
           if (abs_eval_r[j] >= abs_eval_r[min])
             min = j;
         }
       index[min] = count;
       abs_eval_r[min] = factor * min_value;
       count --;
     }
   for (i = 0; i < dim - 1; i++)
     if (eval_r[i] == eval_r[i + 1])
       index[i + 1] = index[i];
   return;
 }
void CTSSAMethod::mat_anal_fast_space (C_INT & slow) protected
MAT_ANAL_fast_space: mathematical analysis of matrices mTdInverse for post-analysis
Definition at line 622 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, CTSSAMethod::Data::dim, mData, mTdInverse, mVfast_space, and CMatrix< CType >::resize().
Referenced by CILDMModifiedMethod::deuflhard_metab(), CILDMMethod::step(), and CILDMModifiedMethod::step().
 {
   C_FLOAT64 denom, length;
   C_INT i, j, dim;
   dim = mData.dim;
   C_INT fast;
   fast = dim - slow;
   CMatrix<C_FLOAT64> Matrix_anal;
   Matrix_anal.resize(dim, dim);
   for (j = 0; j < dim; j++)
     {
       length = 0;
       for (i = 0; i < dim; i++)
         length = length + mTdInverse(i, j) * mTdInverse(i, j);
       length = sqrt(length);
       length = 1;
       for (i = 0; i < dim; i++)
         Matrix_anal(i, j) = mTdInverse(i, j) / length;
     }
   if (slow < dim)
     {
       denom = 0.0;
       for (i = 0; i < dim; i++)
         {
           for (j = slow; j < dim; j++)
             denom = denom + fabs(Matrix_anal(j, i));
         }
       for (i = 0; i < dim; i++)
         mVfast_space[i] = 0.0;
       for (j = 0; j < dim; j++)
         {
           for (i = slow; i < dim; i++)
             mVfast_space[j] = mVfast_space[j] + fabs(Matrix_anal(i, j));
           mVfast_space[j] = (mVfast_space[j] / denom) * 100;
         }
     }
   else
     for (i = 0; i < dim; i++)
       mVfast_space[i] = 0;
   return;
 }
void CTSSAMethod::mat_anal_fast_space_thomas (C_INT & slow) protected
MAT_ANAL_fast_space: mathematical analysis of matrices mTdInverse for post-analysis
Definition at line 680 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, CTSSAMethod::Data::dim, CModel::getCompartments(), CModel::getNumber2QuantityFactor(), mData, mpModel, mQ, mVfast_space, mY_initial, and CVector< CType >::resize().
 {
   C_FLOAT64 scalar_product, absolute_value_1;
   C_INT i, j, k, dim;
   dim = mData.dim;
   C_INT fast;
   fast = dim - slow;
   C_FLOAT64 number2conc = mpModel->getNumber2QuantityFactor() / mpModel->getCompartments()[0]->getInitialValue();
   //C_FLOAT64 number2conc = 1.;
   //this is an ugly hack that only makes sense if all metabs are in the same compartment
   //at the moment is is the only case the algorithm deals with
   CVector<C_FLOAT64> Xconc; //current state converted to concentrations
   Xconc.resize(dim);
   for (i = 0; i < dim; ++i)
     Xconc[i] = mY_initial[i] * number2conc;
   CVector<C_FLOAT64> d_full;
   d_full.resize(dim);
   CVector<C_FLOAT64> d_transformed;
   d_transformed.resize(dim);
   for (j = 0; j < dim; j++)
     {
       for (i = 0; i < slow; i++)
         d_full[i] = 0.0;
       for (i = slow; i < dim; i++)
         d_full[i] = mQ(j, i) * Xconc[j];
       for (i = 0; i < dim; i ++)
         {
           d_transformed[i] = 0.0;
           for (k = 0; k < dim; k++)
             d_transformed[i] += mQ(i, k) * d_full[k];
         }
       scalar_product = d_transformed[j];
       absolute_value_1 = 0.0;
       for (i = 0; i < dim; i++)
         absolute_value_1 += d_transformed[i] * d_transformed[i];
       absolute_value_1 = sqrt(absolute_value_1);
       if (absolute_value_1 * Xconc[j] > 0.0)
         scalar_product = scalar_product / absolute_value_1;
       else
         scalar_product = -2.0;
       mVfast_space[j] = scalar_product;
     }
   return;
 }
void CTSSAMethod::mat_anal_metab (C_INT & slow) protected
MAT_ANAL_METAB: mathematical analysis of matrices mTd for post-analysis
Definition at line 530 of file CTSSAMethod.cpp.
References C_INT, CTSSAMethod::Data::dim, mData, mTd, mVslow_metab, and CVector< CType >::resize().
Referenced by CILDMMethod::step(), and CILDMModifiedMethod::step().
 {
   C_INT i, j, dim;
   dim = mData.dim;
   CVector<C_FLOAT64> denom;
   denom.resize(dim);
   if (slow < dim)
     {
       for (j = 0; j < dim; j++)
         denom[j] = 0;
       for (i = 0; i < dim; i++)
         for (j = 0; j < dim; j++)
           denom[i] = denom[i] + fabs(mTd(i, j));
       for (i = 0; i < dim; i++)
         for (j = 0; j < dim; j++)
           mVslow_metab(i, j) = fabs(mTd(i, j)) / denom[i] * 100;
     }
   else
     for (i = 0; i < dim; i++)
       for (j = 0; j < dim; j++)
         mVslow_metab(i, j) = 0;
   return;
 }
void CTSSAMethod::mat_anal_mod (C_INT & slow) protected
This is not very elegant solution. But I don't know the better one.
MAT_ANAL_MOD: mathematical analysis of matrices mTdInverse for post-analysis
Definition at line 485 of file CTSSAMethod.cpp.
References C_INT, CTSSAMethod::Data::dim, mData, mTdInverse, mVslow, CMatrix< CType >::resize(), and CVector< CType >::resize().
Referenced by CILDMMethod::step(), and CILDMModifiedMethod::step().
 {
   C_INT i, j, dim;
   dim = mData.dim;
   CVector<C_FLOAT64> denom;
   denom.resize(dim);
   CMatrix<C_FLOAT64> Matrix_anal;
   Matrix_anal.resize(dim, dim);
   // norm  of mTd
   if (slow < dim)
     {
       for (j = 0; j < dim; j++)
         denom[j] = 0;
       for (i = 0; i < dim; i++)
         {
           for (j = 0; j < dim; j++)
             denom[i] = denom[i] + fabs(mTdInverse(i, j));
         }
       for (i = 0; i < dim; i++)
         {
           for (j = 0; j < dim; j++)
             mVslow(i, j) = fabs(mTdInverse(i, j)) / denom[i] * 100;
           //  mVslow(i, j) = fabs(mTd(i, j)) / denom[i] * 100;
         }
     }
   else
     for (i = 0; i < dim; i++)
       for (j = 0; j < dim; j++)
         mVslow(i, j) = 0;
   return;
 }
void CTSSAMethod::mat_anal_mod_space (C_INT & slow) protected
MAT_ANAL_MOD_space: mathematical analysis of matrices mTdInverse for post-analysis
Definition at line 564 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, CTSSAMethod::Data::dim, mData, mTdInverse, mVslow_space, and CMatrix< CType >::resize().
Referenced by CILDMMethod::step(), and CILDMModifiedMethod::step().
 {
   C_FLOAT64 denom, length;
   C_INT i, j, dim;
   dim = mData.dim;
   C_INT fast;
   fast = dim - slow;
   CMatrix<C_FLOAT64> Matrix_anal;
   Matrix_anal.resize(dim, dim);
   for (j = 0; j < dim; j++)
     {
       length = 0;
       for (i = 0; i < dim; i++)
         length = length + mTdInverse(i, j) * mTdInverse(i, j);
       length = sqrt(length);
       length = 1;
       for (i = 0; i < dim; i++)
         Matrix_anal(i, j) = mTdInverse(i, j) / length;
     }
   if ((slow < dim) & (slow > 0))
     {
       denom = 0.0;
       for (i = 0; i < dim; i++)
         {
           for (j = 0; j < slow; j++)
             denom = denom + fabs(Matrix_anal(j, i));
         }
       for (i = 0; i < dim; i++)
         mVslow_space[i] = 0.0;
       for (j = 0; j < dim; j++)
         {
           for (i = 0; i < slow; i++)
             mVslow_space[j] = mVslow_space[j] + fabs(Matrix_anal(i, j));
           mVslow_space[j] = (mVslow_space[j] / denom) * 100;
         }
     }
   else
     for (i = 0; i < dim; i++)
       mVslow_space[i] = 0;
   return;
 }
double CTSSAMethod::orthog (C_INT & number1, C_INT & number2) protected
Definition at line 741 of file CTSSAMethod.cpp.
References C_FLOAT64, C_INT, CTSSAMethod::Data::dim, mData, and mTdInverse.
Referenced by CILDMMethod::step().
 {
   C_FLOAT64 product = 0;
   C_INT k, dim;
   dim = mData.dim;
   for (k = 0; k < dim; k++)
     product = product + mTdInverse(k, number1) * mTdInverse(k, number2);
   return product;
 }
void CTSSAMethod::predifineAnnotation () virtual
Predefine the CArrayAnnotation for plots
Reimplemented in CCSPMethod.
Definition at line 221 of file CTSSAMethod.cpp.
Referenced by CTSSATask::initialize(), and CTSSATask::updateMatrices().
 {
   return;
 }
C_FLOAT64 CTSSAMethod::returnCurrentTime (int step)
return required time-value from timevector
Definition at line 316 of file CTSSAMethod.cpp.
References mCurrentTime, and step().
Referenced by CQTSSAResultSubWidget::slotTimeAndStepChanged().
 {
   if ((int) mCurrentTime.size() > step)
     return mCurrentTime[step];
   else
     return std::numeric_limits<C_FLOAT64>::quiet_NaN();
 };
void CTSSAMethod::schur (C_INT & info) protected
SCHUR: Schur Decomposition of Jacobian (reordered). Output: mQ - transformation matrix mR - block upper triangular matrix (with ordered eigenvalues)
Definition at line 760 of file CTSSAMethod.cpp.
References CVectorCore< CType >::array(), C_INT, dgees_(), CTSSAMethod::Data::dim, dtrexc_(), fatalError, CCopasiMethod::getSubType(), map_index(), mData, mJacobian_initial, mQ, mR, CTSSAMethod::Data::pMethod, CVector< CType >::resize(), CCopasiMethod::tssCSP, CCopasiMethod::tssILDM, CCopasiMethod::tssILDMModified, update_nid(), and update_pid().
Referenced by CCSPMethod::cspstep(), CILDMMethod::step(), and CILDMModifiedMethod::step().
 {
   /*      int dgees_(char *jobvs, char *sort, L_fp select, integer *n,
    *  doublereal *a, integer *lda, integer *sdim, doublereal *wr,
    * doublereal *wi, doublereal *vs, integer *ldvs, doublereal *work,
    * integer *lwork, logical *bwork, integer *info)
    *
    *  -- LAPACK driver routine (version 3.0) --
    *     Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd.,
    *     Courant Institute, Argonne National Lab, and Rice University
    *     June 30, 1999
    *
    *
    *  Purpose
    *  =======
    *
    *  DGEES computes for an N-by-N real nonsymmetric matrix A, the
    *  eigenvalues, the real Schur form T, and, optionally, the matrix of
    *  Schur vectors Z.  This gives the Schur factorization A = Z*T*(Z**T).
    *
    *  Optionally, it also orders the eigenvalues on the diagonal of the
    *  real Schur form so that selected eigenvalues are at the top left.
    *  The leading columns of Z then form an orthonormal basis for the
    *  invariant subspace corresponding to the selected eigenvalues.
    *
    *  A matrix is in real Schur form if it is upper quasi-triangular with
    *  1-by-1 and 2-by-2 blocks. 2-by-2 blocks will be standardized in the
    *  form
    *          [  a  b  ]
    *          [  c  a  ]
    *
    *  where b*c < 0. The eigenvalues of such a block are a +- sqrt(bc).
    *
    *  Arguments
    *  =========
    *
    *  JOBVS   (input) CHARACTER*1
    *          = 'N': Schur vectors are not computed;
    *          = 'V': Schur vectors are computed.
    *
    *  SORT    (input) CHARACTER*1
    *          Specifies whether or not to order the eigenvalues on the
    *          diagonal of the Schur form.
    *          = 'N': Eigenvalues are not ordered;
    *          = 'S': Eigenvalues are ordered (see SELECT).
    *
    *  SELECT  (input) LOGICAL FUNCTION of two DOUBLE PRECISION arguments
    *          SELECT must be declared EXTERNAL in the calling subroutine.
    *          If SORT = 'S', SELECT is used to select eigenvalues to sort
    *          to the top left of the Schur form.
    *          If SORT = 'N', SELECT is not referenced.
    *          An eigenvalue WR(j)+sqrt(-1)*WI(j) is selected if
    *          SELECT(WR(j),WI(j)) is true; i.e., if either one of a complex
    *          conjugate pair of eigenvalues is selected, then both complex
    *          eigenvalues are selected.
    *          Note that a selected complex eigenvalue may no longer
    *          satisfy SELECT(WR(j),WI(j)) = .TRUE. after ordering, since
    *          ordering may change the value of complex eigenvalues
    *          (especially if the eigenvalue is ill-conditioned); in this
    *          case INFO is set to N+2 (see INFO below).
    *
    *  N       (input) INTEGER
    *          The order of the matrix A. N >= 0.
    *
    *  A       (input/output) DOUBLE PRECISION array, dimension (LDA,N)
    *          On entry, the N-by-N matrix A.
    *          On exit, A has been overwritten by its real Schur form T.
    *
    *  LDA     (input) INTEGER
    *          The leading dimension of the array A.  LDA >= max(1,N).
    *
    *  SDIM    (output) INTEGER
    *          If SORT = 'N', SDIM = 0.
    *          If SORT = 'S', SDIM = number of eigenvalues (after sorting)
    *                         for which SELECT is true. (Complex conjugate
    *                         pairs for which SELECT is true for either
    *                         eigenvalue count as 2.)
    *
    *  WR      (output) DOUBLE PRECISION array, dimension (N)
    *  WI      (output) DOUBLE PRECISION array, dimension (N)
    *          WR and WI contain the real and imaginary parts,
    *          respectively, of the computed eigenvalues in the same order
    *          that they appear on the diagonal of the output Schur form T.
    *          Complex conjugate pairs of eigenvalues will appear
    *          consecutively with the eigenvalue having the positive
    *          imaginary part first.
    *
    *  VS      (output) DOUBLE PRECISION array, dimension (LDVS,N)
    *          If JOBVS = 'V', VS contains the orthogonal matrix Z of Schur
    *          vectors.
    *          If JOBVS = 'N', VS is not referenced.
    *
    *  LDVS    (input) INTEGER
    *          The leading dimension of the array VS.  LDVS >= 1; if
    *          JOBVS = 'V', LDVS >= N.
    *
    *  WORK    (workspace/output) DOUBLE PRECISION array, dimension (LWORK)
    *          On exit, if INFO = 0, WORK(1) contains the optimal LWORK.
    *
    *  LWORK   (input) INTEGER
    *          The dimension of the array WORK.  LWORK >= max(1,3*N).
    *          For good performance, LWORK must generally be larger.
    *
    *          If LWORK = -1, then a workspace query is assumed; the routine
    *          only calculates the optimal size of the WORK array, returns
    *          this value as the first entry of the WORK array, and no error
    *          message related to LWORK is issued by XERBLA.
    *
    *  BWORK   (workspace) LOGICAL array, dimension (N)
    *          Not referenced if SORT = 'N'.
    *
    *  INFO    (output) INTEGER
    *          = 0: successful exit
    *          < 0: if INFO = -i, the i-th argument had an illegal value.
    *          > 0: if INFO = i, and i is
    *             <= N: the QR algorithm failed to compute all the
    *                   eigenvalues; elements 1:ILO-1 and i+1:N of WR and WI
    *                   contain those eigenvalues which have converged; if
    *                   JOBVS = 'V', VS contains the matrix which reduces A
    *                   to its partially converged Schur form.
    *             = N+1: the eigenvalues could not be reordered because some
    *                   eigenvalues were too close to separate (the problem
    *                   is very ill-conditioned);
    *             = N+2: after reordering, roundoff changed values of some
    *                   complex eigenvalues so that leading eigenvalues in
    *                   the Schur form no longer satisfy SELECT=.TRUE.  This
    *                   could also be caused by underflow due to scaling.
    *
    */
   char V = 'V';
   char N = 'N';
   // TO REMOVE : L_fp select;
   C_INT dim = mData.dim;
   C_INT SDIM = 0;
   CVector<C_FLOAT64> R;
   R.resize(dim * dim);
   C_INT i, j;
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       R[j + dim * i] = mJacobian_initial(j, i);
   CVector<C_FLOAT64> eval_r;
   CVector<C_FLOAT64> eval_i;
   eval_r.resize(dim);
   eval_i.resize(dim);
   CVector<C_FLOAT64> Q;
   Q.resize(dim * dim);
   C_INT lwork = 10 * dim;
   CVector< C_FLOAT64 > work;
   work.resize(10 * dim);
   CVector< C_LOGICAL > Bwork;
   Bwork.resize(dim);
   dgees_(&V, &N, NULL, &dim, R.array(), &dim, &SDIM, eval_r.array(), eval_i.array(), Q.array(), &dim, work.array(), & lwork, Bwork.array(), &info);
   if (info)
     {
       return;
     }
   /* Sorting of Schurmatix */
   CVector<C_FLOAT64> eval_reor;
   eval_reor.resize(dim);
   CVector<C_INT> index;
   index.resize(dim);
   for (i = 0; i < dim; i++)
     eval_reor[i] = eval_r [i];
   for (i = 0; i < dim; i++) index[i] = 0;
   map_index(eval_reor.array(), index.array(), dim);
   CVector<C_INT> nid;
   CVector<C_INT> pid;
   nid.resize(dim);
   pid.resize(dim);
   if (dim > 2)
     {
       update_nid(index.array(), nid.array(), dim);
       update_pid(index.array(), pid.array(), dim);
     }
   else
     {
       for (i = 0; i < dim; i++)
         {
           nid[i] = 0;
           pid[i] = 0;
         }
     }
   bool changed = true;
   C_INT count;
   while (changed == true)
     {
       changed = false;
       count = 0;
       while (count < dim - 1)
         {
           C_INT first;
           C_INT second;
           bool diagorder = false;
           CCopasiMethod::SubType subType;
           subType = mData.pMethod->getSubType();
           switch (subType)
             {
               case tssILDM:
                 diagorder = (index[count + 1] < index[count]);
                 break;
               case tssILDMModified:
                 diagorder = (index[count + 1] < index[count]);
                 break;
               case tssCSP:
                 diagorder = (index[count + 1] > index[count]);
                 break;
               default:
                 fatalError();
                 break;
             }
           //ILDM : if (index[count + 1] < index[count])
           //CSP:  if (index[count + 1] > index[count])
           if (diagorder)
             {
               changed = true;
               first = count + 2;
               second = count + 1;
               CVector<C_FLOAT64> j_diag;
               j_diag.resize(dim);
               for (i = 0; i < dim; i++)
                 j_diag[i] = R.array()[i * dim + i];
               map_index(j_diag.array(), index.array(), dim);
               update_nid(index.array(), nid.array(), dim);
               update_pid(index.array(), pid.array(), dim);
               /*     int dtrexc_(char *compq, integer *n, doublereal *t, integer *
                *     ldt, doublereal *q, integer *ldq, integer *ifst, integer *ilst,
                *     doublereal *work, integer *info)
                *     -- LAPACK routine (version 3.0) --
                *     Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd.,
                *     Courant Institute, Argonne National Lab, and Rice University
                *     March 31, 1993
                *
                *
                *  Purpose
                *  =======
                *
                *  DTREXC reorders the real Schur factorization of a real matrix
                *  A = Q*T*Q**T, so that the diagonal block of T with row index IFST is
                *  moved to row ILST.
                *
                *  The real Schur form T is reordered by an orthogonal similarity
                *  transformation Z**T*T*Z, and optionally the matrix Q of Schur vectors
                *  is updated by postmultiplying it with Z.
                *
                *  T must be in Schur canonical form (as returned by DHSEQR), that is,
                *  block upper triangular with 1-by-1 and 2-by-2 diagonal blocks; each
                *  2-by-2 diagonal block has its diagonal elements equal and its
                *  off-diagonal elements of opposite sign.
                *
                *  Arguments
                *  =========
                *
                *  COMPQ   (input) CHARACTER*1
                *          = 'V':  update the matrix Q of Schur vectors;
                *          = 'N':  do not update Q.
                *
                *  N       (input) INTEGER
                *          The order of the matrix T. N >= 0.
                *
                *  T       (input/output) DOUBLE PRECISION array, dimension (LDT,N)
                *          On entry, the upper quasi-triangular matrix T, in Schur
                *          Schur canonical form.
                *          On exit, the reordered upper quasi-triangular matrix, again
                *          in Schur canonical form.
                *
                *  LDT     (input) INTEGER
                *          The leading dimension of the array T. LDT >= max(1,N).
                *
                *  Q       (input/output) DOUBLE PRECISION array, dimension (LDQ,N)
                *          On entry, if COMPQ = 'V', the matrix Q of Schur vectors.
                *          On exit, if COMPQ = 'V', Q has been postmultiplied by the
                *          orthogonal transformation matrix Z which reorders T.
                *          If COMPQ = 'N', Q is not referenced.
                *
                *  LDQ     (input) INTEGER
                *          The leading dimension of the array Q.  LDQ >= max(1,N).
                *
                *  IFST    (input/output) INTEGER
                *  ILST    (input/output) INTEGER
                *          Specify the reordering of the diagonal blocks of T.
                *          The block with row index IFST is moved to row ILST, by a
                *          sequence of transpositions between adjacent blocks.
                *          On exit, if IFST pointed on entry to the second row of a
                *          2-by-2 block, it is changed to point to the first row; ILST
                *          always points to the first row of the block in its final
                *          position (which may differ from its input value by +1 or -1).
                *          1 <= IFST <= N; 1 <= ILST <= N.
                *
                *  WORK    (workspace) DOUBLE PRECISION array, dimension (N)
                *
                *  INFO    (output) INTEGER
                *          = 0:  successful exit
                *          < 0:  if INFO = -i, the i-th argument had an illegal value
                *          = 1:  two adjacent blocks were too close to swap (the problem
                *                is very ill-conditioned); T may have been partially
                *                reordered, and ILST points to the first row of the
                *                current position of the block being moved.
                */
               CVector< C_FLOAT64 > work1;
               work1.resize(dim);
               dtrexc_(&V, &dim, R.array(), &dim, Q.array(), &dim, &first, &second, work1.array(), &info);
               if (info)
                 {
                   /* TODO */
                   return;
                 }
               C_INT tmp;
               if (nid[count] == 0)
                 {
                   if (pid[count] == 0)
                     {
                       /* both are not degenerate */
                       tmp = index[count];
                       index[count] = index[count + 1];
                       index[count + 1] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                   else
                     {
                       /* the first is degenerate, the second not */
                       tmp = index[count - 1];
                       index[count - 1] = index[count + 1];
                       index[count + 1] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                 }
               else
                 {
                   if (pid[count] == 0)
                     {
                       /* the next is deg, prev is not */
                       tmp = index[count];
                       index[count] = index[count + 2];
                       index[count + 2] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                   else
                     {
                       /* both are deg. */
                       tmp = index[count];
                       index[count - 1] = index[count + 1];
                       index[count] = index[count + 1];
                       index[count + 1] = tmp;
                       index[count + 2] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                 }
             }
           else
             count = count + 1;
         }
     }
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       {
         mQ(j, i) = Q.array()[j + dim * i];
         mR(j, i) = R.array()[j + dim * i];
       }
   return;
 }
void CTSSAMethod::schur_desc (C_INT & info) protected
SCHUR_desc: Schur Decomposition of Jacobian (reordered). Output: mQ_desc - transformation matrix mR_desc - block upper triangular matrix (with ordered eigenvalues)
Definition at line 1187 of file CTSSAMethod.cpp.
References CVectorCore< CType >::array(), C_INT, dgees_(), CTSSAMethod::Data::dim, dtrexc_(), map_index_desc(), mData, mJacobian_initial, mQ_desc, mR_desc, CVector< CType >::resize(), update_nid(), and update_pid().
Referenced by CILDMMethod::step().
 {
   /*      int dgees_(char *jobvs, char *sort, L_fp select, integer *n,
    *  doublereal *a, integer *lda, integer *sdim, doublereal *wr,
    * doublereal *wi, doublereal *vs, integer *ldvs, doublereal *work,
    * integer *lwork, logical *bwork, integer *info)
    *
    *  -- LAPACK driver routine (version 3.0) --
    *     Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd.,
    *     Courant Institute, Argonne National Lab, and Rice University
    *     June 30, 1999
    *
    *
    *  Purpose
    *  =======
    *
    *  DGEES computes for an N-by-N real nonsymmetric matrix A, the
    *  eigenvalues, the real Schur form T, and, optionally, the matrix of
    *  Schur vectors Z.  This gives the Schur factorization A = Z*T*(Z**T).
    *
    *  Optionally, it also orders the eigenvalues on the diagonal of the
    *  real Schur form so that selected eigenvalues are at the top left.
    *  The leading columns of Z then form an orthonormal basis for the
    *  invariant subspace corresponding to the selected eigenvalues.
    *
    *  A matrix is in real Schur form if it is upper quasi-triangular with
    *  1-by-1 and 2-by-2 blocks. 2-by-2 blocks will be standardized in the
    *  form
    *          [  a  b  ]
    *          [  c  a  ]
    *
    *  where b*c < 0. The eigenvalues of such a block are a +- sqrt(bc).
    *
    *  Arguments
    *  =========
    *
    *  JOBVS   (input) CHARACTER*1
    *          = 'N': Schur vectors are not computed;
    *          = 'V': Schur vectors are computed.
    *
    *  SORT    (input) CHARACTER*1
    *          Specifies whether or not to order the eigenvalues on the
    *          diagonal of the Schur form.
    *          = 'N': Eigenvalues are not ordered;
    *          = 'S': Eigenvalues are ordered (see SELECT).
    *
    *  SELECT  (input) LOGICAL FUNCTION of two DOUBLE PRECISION arguments
    *          SELECT must be declared EXTERNAL in the calling subroutine.
    *          If SORT = 'S', SELECT is used to select eigenvalues to sort
    *          to the top left of the Schur form.
    *          If SORT = 'N', SELECT is not referenced.
    *          An eigenvalue WR(j)+sqrt(-1)*WI(j) is selected if
    *          SELECT(WR(j),WI(j)) is true; i.e., if either one of a complex
    *          conjugate pair of eigenvalues is selected, then both complex
    *          eigenvalues are selected.
    *          Note that a selected complex eigenvalue may no longer
    *          satisfy SELECT(WR(j),WI(j)) = .TRUE. after ordering, since
    *          ordering may change the value of complex eigenvalues
    *          (especially if the eigenvalue is ill-conditioned); in this
    *          case INFO is set to N+2 (see INFO below).
    *
    *  N       (input) INTEGER
    *          The order of the matrix A. N >= 0.
    *
    *  A       (input/output) DOUBLE PRECISION array, dimension (LDA,N)
    *          On entry, the N-by-N matrix A.
    *          On exit, A has been overwritten by its real Schur form T.
    *
    *  LDA     (input) INTEGER
    *          The leading dimension of the array A.  LDA >= max(1,N).
    *
    *  SDIM    (output) INTEGER
    *          If SORT = 'N', SDIM = 0.
    *          If SORT = 'S', SDIM = number of eigenvalues (after sorting)
    *                         for which SELECT is true. (Complex conjugate
    *                         pairs for which SELECT is true for either
    *                         eigenvalue count as 2.)
    *
    *  WR      (output) DOUBLE PRECISION array, dimension (N)
    *  WI      (output) DOUBLE PRECISION array, dimension (N)
    *          WR and WI contain the real and imaginary parts,
    *          respectively, of the computed eigenvalues in the same order
    *          that they appear on the diagonal of the output Schur form T.
    *          Complex conjugate pairs of eigenvalues will appear
    *          consecutively with the eigenvalue having the positive
    *          imaginary part first.
    *
    *  VS      (output) DOUBLE PRECISION array, dimension (LDVS,N)
    *          If JOBVS = 'V', VS contains the orthogonal matrix Z of Schur
    *          vectors.
    *          If JOBVS = 'N', VS is not referenced.
    *
    *  LDVS    (input) INTEGER
    *          The leading dimension of the array VS.  LDVS >= 1; if
    *          JOBVS = 'V', LDVS >= N.
    *
    *  WORK    (workspace/output) DOUBLE PRECISION array, dimension (LWORK)
    *          On exit, if INFO = 0, WORK(1) contains the optimal LWORK.
    *
    *  LWORK   (input) INTEGER
    *          The dimension of the array WORK.  LWORK >= max(1,3*N).
    *          For good performance, LWORK must generally be larger.
    *
    *          If LWORK = -1, then a workspace query is assumed; the routine
    *          only calculates the optimal size of the WORK array, returns
    *          this value as the first entry of the WORK array, and no error
    *          message related to LWORK is issued by XERBLA.
    *
    *  BWORK   (workspace) LOGICAL array, dimension (N)
    *          Not referenced if SORT = 'N'.
    *
    *  INFO    (output) INTEGER
    *          = 0: successful exit
    *          < 0: if INFO = -i, the i-th argument had an illegal value.
    *          > 0: if INFO = i, and i is
    *             <= N: the QR algorithm failed to compute all the
    *                   eigenvalues; elements 1:ILO-1 and i+1:N of WR and WI
    *                   contain those eigenvalues which have converged; if
    *                   JOBVS = 'V', VS contains the matrix which reduces A
    *                   to its partially converged Schur form.
    *             = N+1: the eigenvalues could not be reordered because some
    *                   eigenvalues were too close to separate (the problem
    *                   is very ill-conditioned);
    *             = N+2: after reordering, roundoff changed values of some
    *                   complex eigenvalues so that leading eigenvalues in
    *                   the Schur form no longer satisfy SELECT=.TRUE.  This
    *                   could also be caused by underflow due to scaling.
    *
    */
   char V = 'V';
   char N = 'N';
   // TO REMOVE : L_fp select;
   C_INT dim = mData.dim;
   C_INT SDIM = 0;
   CVector<C_FLOAT64> R;
   R.resize(dim * dim);
   C_INT i, j;
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       R[j + dim * i] = mJacobian_initial(j, i);
   CVector<C_FLOAT64> eval_r;
   CVector<C_FLOAT64> eval_i;
   eval_r.resize(dim);
   eval_i.resize(dim);
   CVector<C_FLOAT64> Q;
   Q.resize(dim * dim);
   C_INT lwork = 10 * dim;
   CVector< C_FLOAT64 > work;
   work.resize(10 * dim);
   CVector< C_LOGICAL > Bwork;
   Bwork.resize(dim);
   dgees_(&V, &N, NULL, &dim, R.array(), &dim, &SDIM, eval_r.array(), eval_i.array(), Q.array(), &dim, work.array(), & lwork, Bwork.array(), &info);
   if (info)
     {
       return;
     }
   /* Sorting of Schurmatix */
   CVector<C_FLOAT64> eval_reor;
   eval_reor.resize(dim);
   CVector<C_INT> index;
   index.resize(dim);
   for (i = 0; i < dim; i++)
     eval_reor[i] = eval_r [i];
   for (i = 0; i < dim; i++) index[i] = 0;
   map_index_desc(eval_reor.array(), index.array(), dim);
   CVector<C_INT> nid;
   CVector<C_INT> pid;
   nid.resize(dim);
   pid.resize(dim);
   if (dim > 2)
     {
       update_nid(index.array(), nid.array(), dim);
       update_pid(index.array(), pid.array(), dim);
     }
   else
     {
       for (i = 0; i < dim; i++)
         {
           nid[i] = 0;
           pid[i] = 0;
         }
     }
   bool changed = true;
   C_INT count;
   while (changed == true)
     {
       changed = false;
       count = 0;
       while (count < dim - 1)
         {
           C_INT first;
           C_INT second;
           if (index[count + 1] < index[count])
             {
               changed = true;
               first = count + 2;
               second = count + 1;
               CVector<C_FLOAT64> j_diag;
               j_diag.resize(dim);
               for (i = 0; i < dim; i++)
                 j_diag[i] = R.array()[i * dim + i];
               map_index_desc(j_diag.array(), index.array(), dim);
               update_nid(index.array(), nid.array(), dim);
               update_pid(index.array(), pid.array(), dim);
               /*     int dtrexc_(char *compq, integer *n, doublereal *t, integer *
                *     ldt, doublereal *q, integer *ldq, integer *ifst, integer *ilst,
                *     doublereal *work, integer *info)
                *     -- LAPACK routine (version 3.0) --
                *     Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd.,
                *     Courant Institute, Argonne National Lab, and Rice University
                *     March 31, 1993
                *
                *
                *  Purpose
                *  =======
                *
                *  DTREXC reorders the real Schur factorization of a real matrix
                *  A = Q*T*Q**T, so that the diagonal block of T with row index IFST is
                *  moved to row ILST.
                *
                *  The real Schur form T is reordered by an orthogonal similarity
                *  transformation Z**T*T*Z, and optionally the matrix Q of Schur vectors
                *  is updated by postmultiplying it with Z.
                *
                *  T must be in Schur canonical form (as returned by DHSEQR), that is,
                *  block upper triangular with 1-by-1 and 2-by-2 diagonal blocks; each
                *  2-by-2 diagonal block has its diagonal elements equal and its
                *  off-diagonal elements of opposite sign.
                *
                *  Arguments
                *  =========
                *
                *  COMPQ   (input) CHARACTER*1
                *          = 'V':  update the matrix Q of Schur vectors;
                *          = 'N':  do not update Q.
                *
                *  N       (input) INTEGER
                *          The order of the matrix T. N >= 0.
                *
                *  T       (input/output) DOUBLE PRECISION array, dimension (LDT,N)
                *          On entry, the upper quasi-triangular matrix T, in Schur
                *          Schur canonical form.
                *          On exit, the reordered upper quasi-triangular matrix, again
                *          in Schur canonical form.
                *
                *  LDT     (input) INTEGER
                *          The leading dimension of the array T. LDT >= max(1,N).
                *
                *  Q       (input/output) DOUBLE PRECISION array, dimension (LDQ,N)
                *          On entry, if COMPQ = 'V', the matrix Q of Schur vectors.
                *          On exit, if COMPQ = 'V', Q has been postmultiplied by the
                *          orthogonal transformation matrix Z which reorders T.
                *          If COMPQ = 'N', Q is not referenced.
                *
                *  LDQ     (input) INTEGER
                *          The leading dimension of the array Q.  LDQ >= max(1,N).
                *
                *  IFST    (input/output) INTEGER
                *  ILST    (input/output) INTEGER
                *          Specify the reordering of the diagonal blocks of T.
                *          The block with row index IFST is moved to row ILST, by a
                *          sequence of transpositions between adjacent blocks.
                *          On exit, if IFST pointed on entry to the second row of a
                *          2-by-2 block, it is changed to point to the first row; ILST
                *          always points to the first row of the block in its final
                *          position (which may differ from its input value by +1 or -1).
                *          1 <= IFST <= N; 1 <= ILST <= N.
                *
                *  WORK    (workspace) DOUBLE PRECISION array, dimension (N)
                *
                *  INFO    (output) INTEGER
                *          = 0:  successful exit
                *          < 0:  if INFO = -i, the i-th argument had an illegal value
                *          = 1:  two adjacent blocks were too close to swap (the problem
                *                is very ill-conditioned); T may have been partially
                *                reordered, and ILST points to the first row of the
                *                current position of the block being moved.
                */
               CVector< C_FLOAT64 > work1;
               work1.resize(dim);
               dtrexc_(&V, &dim, R.array(), &dim, Q.array(), &dim, &first, &second, work1.array(), &info);
               if (info)
                 {
                   /* TODO */
                   return;
                 }
               C_INT tmp;
               if (nid[count] == 0)
                 {
                   if (pid[count] == 0)
                     {
                       /* both are not degenerate */
                       tmp = index[count];
                       index[count] = index[count + 1];
                       index[count + 1] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                   else
                     {
                       /* the first is degenerate, the second not */
                       tmp = index[count - 1];
                       index[count - 1] = index[count + 1];
                       index[count + 1] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                 }
               else
                 {
                   if (pid[count] == 0)
                     {
                       /* the next is deg, prev is not */
                       tmp = index[count];
                       index[count] = index[count + 2];
                       index[count + 2] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                   else
                     {
                       /* both are deg. */
                       tmp = index[count];
                       index[count - 1] = index[count + 1];
                       index[count] = index[count + 1];
                       index[count + 1] = tmp;
                       index[count + 2] = tmp;
                       update_nid(index.array(), nid.array(), dim);
                       update_pid(index.array(), pid.array(), dim);
                       count = count + 1;
                     }
                 }
             }
           else
             count = count + 1;
         }
     }
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       {
         mQ_desc(j, i) = Q.array()[j + dim * i];
         mR_desc(j, i) = R.array()[j + dim * i];
       }
   return;
 }
virtual bool CTSSAMethod::setAnnotationM (size_t s) pure virtual
Implemented in CCSPMethod, CILDMMethod, and CILDMModifiedMethod.
Referenced by CQTSSAResultSubWidget::changeInterval().
void CTSSAMethod::setCurrentState (CState * currentState)
Set a pointer to the current state. This method is used by CTSSATask::process() The results of the simulation are passed via this CState variable
Parameters
CState * currentState
Definition at line 180 of file CTSSAMethod.cpp.
References mpCurrentState.
Referenced by CTSSATask::processStart().
 {
   mpCurrentState = currentState;
 }
void CTSSAMethod::setModel (CModel * model)
Set the Model
Definition at line 216 of file CTSSAMethod.cpp.
References mpModel.
Referenced by CTSSATask::initialize(), and CTSSATask::updateMatrices().
 {
   mpModel = model;
 }
void CTSSAMethod::setProblem (CTSSAProblem * problem)
Set a pointer to the problem. This method is used by CTSSA
Parameters
CTSSAProblem * problem
Definition at line 190 of file CTSSAMethod.cpp.
References mpProblem.
Referenced by CTSSATask::initialize().
 {mpProblem = problem;}
void CTSSAMethod::setVectors (int slowMode)
upgrade all vectors with values from actually calculalion for current step
upgrade all vectors with values from actually calculation for current step
Definition at line 2184 of file CTSSAMethod.cpp.
 {}
void CTSSAMethod::start (const CState * initialState) virtual
This instructs the method to prepare for integration starting with the initialState given.
Parameters
const CState * initialState
This instructs the method to calculate a a time step of deltaT starting with the initialState given. The new state (after deltaT) is expected in the current state. The return value is the actual time step taken.
Parameters
double & deltaT
const CState * initialState
Returns
"const double &" actualDeltaT
Reimplemented in CCSPMethod, CILDMModifiedMethod, and CILDMMethod.
Definition at line 213 of file CTSSAMethod.cpp.
Referenced by CTSSATask::processStart().
 {return;}
void CTSSAMethod::step (const double & deltaT) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
This instructs the method to calculate a a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual time step taken.
Parameters
const double & deltaT
Reimplemented in CCSPMethod, CILDMModifiedMethod, and CILDMMethod.
Definition at line 201 of file CTSSAMethod.cpp.
Referenced by CTSSATask::processStep(), and returnCurrentTime().
 {return ;}
void CTSSAMethod::sylvester (C_INT slow, C_INT & info) protected
SYLVESTER: Solution of Sylvester equation for given slow, mQ,mR Output: mTd, mTdinverse, mQz (is used later for Newton iterations)
Definition at line 1587 of file CTSSAMethod.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, C_INT, CTSSAMethod::Data::dim, dtrsyl_(), mData, mJacobian_initial, mQ, mQz, mR, mTd, mTdInverse, CMatrix< CType >::resize(), and CVector< CType >::resize().
Referenced by CILDMMethod::step().
 {
   char N1 = 'N';
   char N2 = 'N';
   C_INT isgn = -1;
   C_INT dim = mData.dim;
   C_INT fast = dim - slow;
   //  C_INT info;
   C_INT i, j, k;
   C_FLOAT64 scale = -1;
   CVector<C_FLOAT64> st_slow;
   st_slow.resize(slow * slow);
   CVector<C_FLOAT64> st_fast;
   st_fast.resize(fast * fast);
   CVector<C_FLOAT64> st_coup;
   st_coup.resize(slow * fast);
   CMatrix<C_FLOAT64> S_coup;
   S_coup.resize(slow, fast);
   for (i = 0; i < slow; i++)
     for (j = 0; j < slow; j++)
       st_slow[j + slow * i] = mR(j, i);
   for (i = 0; i < fast; i++)
     for (j = 0; j < fast; j++)
       st_fast[j + fast * i] = mR(j + slow, i + slow);
   for (i = 0; i < slow; i++)
     for (j = 0; j < fast; j++)
       S_coup(i, j) = mR(i, j + slow);
   for (j = 0; j < fast; j++)
     for (i = 0; i < slow; i++)
       st_coup[i + slow * j] = -S_coup(i, j);
   /*     int dtrsyl_(char *trana, char *tranb, integer *isgn, integer
    *     *m, integer *n, doublereal *a, integer *lda, doublereal *b, integer *
    *     ldb, doublereal *c__, integer *ldc, doublereal *scale, integer *info)
    *
    *     -- LAPACK routine (version 3.0) --
    *     Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd.,
    *     Courant Institute, Argonne National Lab, and Rice University
    *     March 31, 1993
    *
    *
    *  Purpose
    *  =======
    *
    *  DTRSYL solves the real Sylvester matrix equation:
    *
    *     op(A)*X + X*op(B) = scale*C or
    *     op(A)*X - X*op(B) = scale*C,
    *
    *  where op(A) = A or A**T, and  A and B are both upper quasi-
    *  triangular. A is M-by-M and B is N-by-N; the right hand side C and
    *  the solution X are M-by-N; and scale is an output scale factor, set
    *  <= 1 to avoid overflow in X.
    *
    *  A and B must be in Schur canonical form (as returned by DHSEQR), that
    *  is, block upper triangular with 1-by-1 and 2-by-2 diagonal blocks;
    *  each 2-by-2 diagonal block has its diagonal elements equal and its
    *  off-diagonal elements of opposite sign.
    *
    *  Arguments
    *  =========
    *
    *  TRANA   (input) CHARACTER*1
    *          Specifies the option op(A):
    *          = 'N': op(A) = A    (No transpose)
    *          = 'T': op(A) = A**T (Transpose)
    *          = 'C': op(A) = A**H (Conjugate transpose = Transpose)
    *
    *  TRANB   (input) CHARACTER*1
    *          Specifies the option op(B):
    *          = 'N': op(B) = B    (No transpose)
    *          = 'T': op(B) = B**T (Transpose)
    *          = 'C': op(B) = B**H (Conjugate transpose = Transpose)
    *
    *  ISGN    (input) INTEGER
    *          Specifies the sign in the equation:
    *          = +1: solve op(A)*X + X*op(B) = scale*C
    *          = -1: solve op(A)*X - X*op(B) = scale*C
    *
    *  M       (input) INTEGER
    *          The order of the matrix A, and the number of rows in the
    *          matrices X and C. M >= 0.
    *
    *  N       (input) INTEGER
    *          The order of the matrix B, and the number of columns in the
    *          matrices X and C. N >= 0.
    *
    *  A       (input) DOUBLE PRECISION array, dimension (LDA,M)
    *          The upper quasi-triangular matrix A, in Schur canonical form.
    *
    *  LDA     (input) INTEGER
    *          The leading dimension of the array A. LDA >= max(1,M).
    *
    *  B       (input) DOUBLE PRECISION array, dimension (LDB,N)
    *          The upper quasi-triangular matrix B, in Schur canonical form.
    *
    *  LDB     (input) INTEGER
    *          The leading dimension of the array B. LDB >= max(1,N).
    *
    *  C       (input/output) DOUBLE PRECISION array, dimension (LDC,N)
    *          On entry, the M-by-N right hand side matrix C.
    *          On exit, C is overwritten by the solution matrix X.
    *
    *  LDC     (input) INTEGER
    *          The leading dimension of the array C. LDC >= max(1,M)
    *
    *  SCALE   (output) DOUBLE PRECISION
    *          The scale factor, scale, set <= 1 to avoid overflow in X.
    *
    *  INFO    (output) INTEGER
    *          = 0: successful exit
    *          < 0: if INFO = -i, the i-th argument had an illegal value
    *          = 1: A and B have common or very close eigenvalues; perturbed
    *               values were used to solve the equation (but the matrices
    *               A and B are unchanged).
    */
   dtrsyl_(&N1, &N2, &isgn, &slow, &fast, st_slow.array(), &slow, st_fast.array(), &fast, st_coup.array(), &slow, &scale, &info);
   /*  if (info) TODO*/
   if (info)
     {
       return;
     }
   CMatrix<C_FLOAT64> Cmat;
   Cmat.resize(dim, dim);
   CMatrix<C_FLOAT64> C;
   C.resize(dim, dim);
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       Cmat(i, j) = 0.;
   for (j = 0; j < fast; j++)
     for (i = 0; i < slow; i++)
       Cmat(i, j + slow) = st_coup[i + slow * j];
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       if (i == j)
         C(i, j) = 1. + Cmat(i, j);
       else
         C(i, j) = Cmat(i, j);
   for (i = 0; i < dim; i++)
     {
       for (j = 0; j < dim; j++)
         {
           mTd(i, j) = 0.;
           for (k = 0; k < dim; k++)
             mTd(i, j) = mTd(i, j) + mQ(i, k) * C(k, j);
         }
     }
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       if (i == j)
         C(i, j) = 1. - Cmat(i, j);
       else
         C(i, j) = - Cmat(i, j);
   CMatrix<C_FLOAT64> transp_Qt;
   transp_Qt.resize(dim, dim);
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       transp_Qt(i, j) = mQ(j, i);
   for (i = 0; i < dim; i++)
     {
       for (j = 0; j < dim; j++)
         {
           mTdInverse(i, j) = 0.0;
           for (k = 0; k < dim; k++)
             mTdInverse(i, j) = mTdInverse(i, j) + C(i, k) * transp_Qt(k, j);
         }
     }
   CMatrix<C_FLOAT64> E;
   E.resize(dim, dim);
   CMatrix<C_FLOAT64> S;
   S.resize(dim, dim);
   for (i = 0; i < dim; i++)
     {
       for (j = 0; j < dim; j++)
         {
           E(i, j) = 0.;
           for (k = 0; k < dim; k++)
             E(i, j) = E(i, j) + mJacobian_initial(i, k) * mTd(k, j);
         }
     }
   for (i = 0; i < dim; i++)
     {
       for (j = 0; j < dim; j++)
         {
           S(i, j) = 0.;
           for (k = 0; k < dim; k++)
             S(i, j) = S(i, j) + mTdInverse(i, k) * E(k, j);
         }
     }
   C_INT flag_sylvester;
   flag_sylvester = 1;
   for (i = 0; i < dim; i++)
     for (j = 0; j < dim; j++)
       mQz(i, j) = 0.;
   for (i = 0; i < fast; i++)
     for (j = 0; j < fast; j++)
       mQz(i, j) = S(i + slow, j + slow);
   return;
 }
void CTSSAMethod::update_nid (C_INT * index, C_INT * nid, const C_INT & dim) protected
UPDATE_NID: used for sorting of SchurDecompostion
Definition at line 2024 of file CTSSAMethod.cpp.
References C_INT.
Referenced by schur(), and schur_desc().
 {
   C_INT k;
   for (k = 0; k < dim; k++)
     nid[k] = 0;
   for (k = 1; k < dim - 1; k++)
     if (index[k] == index[k + 1])
       nid[k - 1] = k;
   return;
 }
void CTSSAMethod::update_pid (C_INT * index, C_INT * pid, const C_INT & dim) protected
UPDATE_PID: used for sorting of SchurDecompostion
Definition at line 2041 of file CTSSAMethod.cpp.
References C_INT.
Referenced by schur(), and schur_desc().
 {
   C_INT k;
   for (k = 0; k < dim; k++)
     pid[k] = 0;
   for (k = 1; k < dim; k++)
     if (index[k] == index[k - 1])
       pid[k] = k;
   return;
 }
Member Data Documentation
std::map< std::string, CArrayAnnotation* > CTSSAMethod::mapTableToName
Definition at line 97 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::createAnnotationsM(), CILDMMethod::createAnnotationsM(), CCSPMethod::createAnnotationsM(), and getTable().
CVector< C_FLOAT64 > CTSSAMethod::mAtol protected
A vector of absolute tolerances.
Definition at line 301 of file CTSSAMethod.h.
Referenced by initializeAtol(), and integrationStep().
CVector<C_FLOAT64> CTSSAMethod::mCfast protected
Definition at line 250 of file CTSSAMethod.h.
Referenced by CILDMMethod::deuflhard(), CILDMMethod::newton(), and CILDMMethod::step().
int CTSSAMethod::mCurrentStep protected
stepcounter
Definition at line 466 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::emptyVectors(), CILDMMethod::emptyVectors(), CCSPMethod::emptyVectors(), getCurrentStep(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), CCSPMethod::setVectorsToNaN(), CILDMMethod::step(), CILDMModifiedMethod::step(), and CCSPMethod::step().
std::vector< C_FLOAT64 > CTSSAMethod::mCurrentTime protected
Definition at line 460 of file CTSSAMethod.h.
Referenced by returnCurrentTime(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), and CCSPMethod::setVectorsToNaN().
Data CTSSAMethod::mData protected
mData.dim is the dimension of the ODE system.
Definition at line 180 of file CTSSAMethod.h.
Referenced by calculateDerivatives(), CCSPMethod::CCSPMethod(), CILDMMethod::CILDMMethod(), CILDMModifiedMethod::CILDMModifiedMethod(), CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), initializeAtol(), integrationMethodStart(), integrationStep(), isValidProblem(), mat_anal_fast_space(), mat_anal_fast_space_thomas(), mat_anal_metab(), mat_anal_mod(), mat_anal_mod_space(), CILDMMethod::newton(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), orthog(), CILDMModifiedMethod::printResult(), CCSPMethod::printResult(), schur(), schur_desc(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), CCSPMethod::setVectorsToNaN(), CILDMMethod::start(), CILDMModifiedMethod::start(), CCSPMethod::start(), CILDMMethod::step(), CILDMModifiedMethod::step(), CCSPMethod::step(), and sylvester().
C_FLOAT64 CTSSAMethod::mDtol protected
Tolerance for Deuflhard criterium
Definition at line 341 of file CTSSAMethod.h.
Referenced by CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), CILDMMethod::start(), CILDMModifiedMethod::start(), and CILDMModifiedMethod::step().
CVector< C_FLOAT64 > CTSSAMethod::mDWork protected
LSODA C_FLOAT64 work area
Definition at line 321 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
C_FLOAT64 CTSSAMethod::mEPS protected
Definition at line 346 of file CTSSAMethod.h.
Referenced by CILDMMethod::deuflhard(), and CILDMMethod::step().
std::ostringstream CTSSAMethod::mErrorMsg protected
Stream to capture LSODA error messages
Definition at line 306 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
CVector< C_INT > CTSSAMethod::mIWork protected
LSODA C_INT work area
Definition at line 326 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
CMatrix<C_FLOAT64> CTSSAMethod::mJacobian protected
Jacobian matrix
Definition at line 205 of file CTSSAMethod.h.
Referenced by CCSPMethod::cspstep(), integrationMethodStart(), CILDMMethod::step(), CILDMModifiedMethod::step(), and CCSPMethod::step().
CMatrix<C_FLOAT64> CTSSAMethod::mJacobian_initial protected
Jacobian matrix at initial point
Definition at line 210 of file CTSSAMethod.h.
Referenced by CCSPMethod::cspstep(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), schur(), schur_desc(), CILDMMethod::step(), CILDMModifiedMethod::step(), and sylvester().
C_INT CTSSAMethod::mJType protected
The way LSODA calculates the jacobian
Definition at line 331 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
CLSODA CTSSAMethod::mLSODA protected
The LSODA integrator
Definition at line 311 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
C_INT CTSSAMethod::mLsodaStatus protected
LSODA state.
Definition at line 286 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
CState* CTSSAMethod::mpCurrentState protected
A pointer to the current state. This is set from outside with the setState() method and never changed anywhere else. Its used to report the results to the calling TSSATask
Definition at line 50 of file CTSSAMethod.h.
Referenced by integrationStep(), and setCurrentState().
CModel* CTSSAMethod::mpModel protected
A pointer to the model
Definition at line 336 of file CTSSAMethod.h.
Referenced by calculateDerivatives(), calculateDerivativesX(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPOutput(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::CSPradicalPointer(), CCSPMethod::cspstep(), CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), evalF(), initializeAtol(), integrationMethodStart(), mat_anal_fast_space_thomas(), CILDMMethod::newton(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), CCSPMethod::predifineAnnotation(), CILDMModifiedMethod::printResult(), CCSPMethod::printResult(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), setModel(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), CCSPMethod::setVectorsToNaN(), CCSPMethod::start(), CILDMMethod::step(), CILDMModifiedMethod::step(), and CCSPMethod::step().
CTSSAProblem* CTSSAMethod::mpProblem protected
A pointer to the time scale separation analysis problem.
Definition at line 55 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and setProblem().
CState* CTSSAMethod::mpState protected
A pointer to the current state in complete model view.
Definition at line 175 of file CTSSAMethod.h.
Referenced by evalF(), integrationMethodStart(), integrationStep(), CCSPMethod::~CCSPMethod(), CILDMMethod::~CILDMMethod(), and CILDMModifiedMethod::~CILDMModifiedMethod().
CMatrix<C_FLOAT64> CTSSAMethod::mQ protected
Definition at line 215 of file CTSSAMethod.h.
Referenced by CCSPMethod::cspstep(), mat_anal_fast_space_thomas(), schur(), CILDMMethod::step(), CILDMModifiedMethod::step(), and sylvester().
CMatrix<C_FLOAT64> CTSSAMethod::mQ_desc protected
Definition at line 216 of file CTSSAMethod.h.
Referenced by schur_desc(), and CILDMMethod::step().
CMatrix<C_FLOAT64> CTSSAMethod::mQz protected
Definition at line 235 of file CTSSAMethod.h.
Referenced by CILDMMethod::newton(), CILDMMethod::step(), CILDMModifiedMethod::step(), and sylvester().
CMatrix<C_FLOAT64> CTSSAMethod::mR protected
Definition at line 220 of file CTSSAMethod.h.
Referenced by CCSPMethod::cspstep(), CILDMModifiedMethod::deuflhard_metab(), schur(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), CCSPMethod::setVectorsToNaN(), CILDMMethod::step(), CILDMModifiedMethod::step(), and sylvester().
CMatrix<C_FLOAT64> CTSSAMethod::mR_desc protected
Definition at line 221 of file CTSSAMethod.h.
Referenced by schur_desc(), and CILDMMethod::step().
bool CTSSAMethod::mReducedModel protected
Whether to use the reduced model
Definition at line 291 of file CTSSAMethod.h.
Referenced by calculateDerivatives(), calculateDerivativesX(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::CSPradicalPointer(), CILDMMethod::deuflhard(), evalF(), CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), integrationMethodStart(), CCSPMethod::predifineAnnotation(), CCSPMethod::setAnnotationM(), CILDMMethod::start(), CILDMModifiedMethod::start(), CCSPMethod::start(), CILDMMethod::step(), CILDMModifiedMethod::step(), and CCSPMethod::step().
C_FLOAT64 CTSSAMethod::mRtol protected
Relative tolerance.
Definition at line 296 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
C_INT CTSSAMethod::mSlow protected
Definition at line 281 of file CTSSAMethod.h.
Referenced by CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), CILDMMethod::step(), and CILDMModifiedMethod::step().
C_INT CTSSAMethod::mState protected
The state of the integrator
Definition at line 316 of file CTSSAMethod.h.
Referenced by integrationMethodStart(), and integrationStep().
CMatrix<C_FLOAT64> CTSSAMethod::mTd protected
Definition at line 225 of file CTSSAMethod.h.
Referenced by CILDMMethod::deuflhard(), mat_anal_metab(), CILDMMethod::newton(), CILDMMethod::step(), CILDMModifiedMethod::step(), and sylvester().
CMatrix<C_FLOAT64> CTSSAMethod::mTd_save protected
Definition at line 240 of file CTSSAMethod.h.
Referenced by CILDMMethod::step(), and CILDMModifiedMethod::step().
CMatrix<C_FLOAT64> CTSSAMethod::mTdInverse protected
Definition at line 230 of file CTSSAMethod.h.
Referenced by CILDMMethod::deuflhard(), mat_anal_fast_space(), mat_anal_mod(), mat_anal_mod_space(), CILDMMethod::newton(), orthog(), CILDMMethod::step(), CILDMModifiedMethod::step(), and sylvester().
CMatrix<C_FLOAT64> CTSSAMethod::mTdInverse_save protected
Definition at line 244 of file CTSSAMethod.h.
Referenced by CILDMMethod::step(), and CILDMModifiedMethod::step().
C_FLOAT64 CTSSAMethod::mTime protected
Current time.
Definition at line 200 of file CTSSAMethod.h.
Referenced by CCSPMethod::cspstep(), integrationMethodStart(), integrationStep(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), CCSPMethod::setVectorsToNaN(), CILDMMethod::step(), and CILDMModifiedMethod::step().
std::vector< C_INT > CTSSAMethod::mVec_SlowModes protected
vectors contain whole data for all calculationsteps
Definition at line 459 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::emptyVectors(), CILDMMethod::emptyVectors(), CCSPMethod::emptyVectors(), CILDMModifiedMethod::printResult(), CCSPMethod::printResult(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), and CCSPMethod::setVectorsToNaN().
std::vector< CVector<C_FLOAT64> > CTSSAMethod::mVec_TimeScale protected
Definition at line 461 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::emptyVectors(), CILDMMethod::emptyVectors(), CCSPMethod::emptyVectors(), getVec_TimeScale(), CILDMModifiedMethod::printResult(), CCSPMethod::printResult(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), and CCSPMethod::setVectorsToNaN().
CVector<C_FLOAT64> CTSSAMethod::mVfast_space protected
Definition at line 276 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::deuflhard_metab(), mat_anal_fast_space(), mat_anal_fast_space_thomas(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CILDMMethod::start(), CILDMModifiedMethod::start(), and CILDMMethod::step().
CMatrix<C_FLOAT64> CTSSAMethod::mVslow protected
Definition at line 261 of file CTSSAMethod.h.
Referenced by CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), mat_anal_mod(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CILDMMethod::start(), CILDMModifiedMethod::start(), CILDMMethod::step(), and CILDMModifiedMethod::step().
CMatrix<C_FLOAT64> CTSSAMethod::mVslow_metab protected
Definition at line 266 of file CTSSAMethod.h.
Referenced by mat_anal_metab(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CILDMMethod::start(), and CILDMModifiedMethod::start().
CVector<C_FLOAT64> CTSSAMethod::mVslow_space protected
Definition at line 271 of file CTSSAMethod.h.
Referenced by mat_anal_mod_space(), CILDMModifiedMethod::setVectors(), CILDMMethod::setVectors(), CILDMMethod::start(), CILDMModifiedMethod::start(), and CILDMMethod::step().
C_FLOAT64* CTSSAMethod::mY protected
Pointer to the array with left hand side values.
Definition at line 185 of file CTSSAMethod.h.
Referenced by CCSPMethod::cspstep(), integrationMethodStart(), integrationStep(), CILDMMethod::step(), and CILDMModifiedMethod::step().
CVector<C_FLOAT64> CTSSAMethod::mY_cons protected
Definition at line 256 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::deuflhard_metab(), CILDMModifiedMethod::newton_new(), and CILDMModifiedMethod::step().
CVector< C_FLOAT64 > CTSSAMethod::mY_initial protected
Definition at line 195 of file CTSSAMethod.h.
Referenced by CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), mat_anal_fast_space_thomas(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), CILDMMethod::step(), and CILDMModifiedMethod::step().
CVector< C_FLOAT64 > CTSSAMethod::mYdot protected
Vector containing the derivatives after calling eval
Definition at line 190 of file CTSSAMethod.h.
Referenced by integrationMethodStart().
std::vector<std::string> CTSSAMethod::tableNames
Definition at line 98 of file CTSSAMethod.h.
Referenced by CILDMModifiedMethod::createAnnotationsM(), CILDMMethod::createAnnotationsM(), CCSPMethod::createAnnotationsM(), and getTableName().
The documentation for this class was generated from the following files:
CTSSAMethod.h
CTSSAMethod.cpp