COPASI API: CCrossValidationSet Class Reference
CCrossValidationSet Class Reference
#include <CExperimentSet.h>
Public Member Functions
CCrossValidationSet (const CCopasiContainer *pParent, const std::string &name="Validation Set")
CCrossValidationSet (const CCrossValidationSet &src, const CCopasiContainer *pParent=NULL)
CCrossValidationSet (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
const unsigned C_INT32 & getThreshold () const
const C_FLOAT64 & getWeight () const
void setThreshold (const unsigned C_INT32 &threshold)
void setWeight (const C_FLOAT64 &weight)
virtual ~CCrossValidationSet ()
Public Member Functions inherited from CExperimentSet
CExperiment * addExperiment (const CExperiment &experiment)
bool calculateStatistics ()
CExperimentSet (const CCopasiContainer *pParent, const std::string &name="Experiment Set")
CExperimentSet (const CExperimentSet &src, const CCopasiContainer *pParent=NULL)
CExperimentSet (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
bool compile (const std::vector< CCopasiContainer * > listOfContainer=CCopasiContainer::EmptyList)
virtual bool elevateChildren ()
void fixBuild55 ()
size_t getDataPointCount () const
const CMatrix< C_FLOAT64 > & getDependentData (const size_t &index) const
const CVector< C_FLOAT64 > & getDependentErrorMean () const
const CVector< C_FLOAT64 > & getDependentErrorMeanSD () const
const CVector< C_FLOAT64 > & getDependentObjectiveValues () const
const CVector< CCopasiObject * > & getDependentObjects () const
const CVector< C_FLOAT64 > & getDependentRMS () const
CExperiment * getExperiment (const size_t &index)
const CExperiment * getExperiment (const size_t &index) const
CExperiment * getExperiment (const std::string &name)
const CExperiment * getExperiment (const std::string &name) const
size_t getExperimentCount () const
const CCopasiTask::Type & getExperimentType (const size_t &index) const
std::vector< std::string > getFileNames () const
const CMatrix< C_FLOAT64 > & getIndependentData (const size_t &index) const
const size_t & getValidValueCount () const
bool hasDataForTaskType (const CCopasiTask::Type &type) const
size_t keyToIndex (const std::string &key) const
void removeExperiment (const size_t &index)
void sort ()
virtual ~CExperimentSet ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initializeParameter ()
Private Attributes
unsigned C_INT32 * mpThreshold
C_FLOAT64 * mpWeight
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 276 of file CExperimentSet.h.
Constructor & Destructor Documentation
CCrossValidationSet::CCrossValidationSet (const CCopasiContainer * pParent, const std::string & name = "Validation Set")
Default constructor
Parameters
const std::string & name (default: Cross Validation Set)
const CCopasiContainer * pParent (default: NULL)
Definition at line 479 of file CExperimentSet.cpp.
References initializeParameter().
                            :
   CExperimentSet(name, pParent),
   mpWeight(NULL),
   mpThreshold(NULL)
 {initializeParameter();}
CCrossValidationSet::CCrossValidationSet (const CCrossValidationSet & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CCrossValidationSet & src
const CCopasiContainer * pParent (default: src data model)
Definition at line 486 of file CExperimentSet.cpp.
References initializeParameter().
                                      :
   CExperimentSet(src, pParent),
   mpWeight(NULL),
   mpThreshold(NULL)
 {initializeParameter();}
CCrossValidationSet::CCrossValidationSet (const CCopasiParameterGroup & group, const CCopasiContainer * pParent = NULL)
Specific constructor used for reading COPASI files
Parameters
const CCopasiParameterGroup & group
const CCopasiContainer * pParent (default: group data model)
Definition at line 493 of file CExperimentSet.cpp.
References initializeParameter().
                                      :
   CExperimentSet(group, pParent),
   mpWeight(NULL),
   mpThreshold(NULL)
 {initializeParameter();}
CCrossValidationSet::~CCrossValidationSet () virtual
Destructor
Definition at line 500 of file CExperimentSet.cpp.
 {}
Member Function Documentation
const unsigned C_INT32 & CCrossValidationSet::getThreshold () const
Retreive the threshold
Returns
const unsigned C_INT32 & threshold
Definition at line 518 of file CExperimentSet.cpp.
References mpThreshold.
Referenced by CFitProblem::calculateCrossValidation(), CQFittingWidget::saveTask(), and CQExperimentData::slotOK().
 {return *mpThreshold;}
const C_FLOAT64 & CCrossValidationSet::getWeight () const
Retreive the weight
Returns
const C_FLOAT64 & weight
Definition at line 512 of file CExperimentSet.cpp.
References mpWeight.
Referenced by CFitProblem::calculateCrossValidation(), CQFittingWidget::saveTask(), and CQExperimentData::slotOK().
 {return *mpWeight;}
void CCrossValidationSet::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 521 of file CExperimentSet.cpp.
References CCopasiParameterGroup::assertParameter(), C_FLOAT64, C_INT32, CExperimentSet::elevateChildren(), CCopasiParameter::getValue(), mpThreshold, mpWeight, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CCrossValidationSet().
 {
   mpWeight =
     assertParameter("Weight", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0)->getValue().pUDOUBLE;
   mpThreshold =
     assertParameter("Threshold", CCopasiParameter::UINT, (unsigned C_INT32) 5)->getValue().pUINT;
   elevateChildren();
 }
void CCrossValidationSet::setThreshold (const unsigned C_INT32 & threshold)
Set the threshold
Parameters
const unsigned C_INT32 & threshold
Definition at line 515 of file CExperimentSet.cpp.
References mpThreshold.
Referenced by CQExperimentData::slotOK().
 {*mpThreshold = threshold;}
void CCrossValidationSet::setWeight (const C_FLOAT64 & weight)
Set the weight
Parameters
const C_FLOAT64 & weight
Definition at line 502 of file CExperimentSet.cpp.
References mpWeight.
Referenced by CQFittingWidget::saveTask(), and CQExperimentData::slotOK().
 {
   if (weight < 0.0)
     *mpWeight = 0.0;
   else if (weight > 1.0)
     *mpWeight = 1.0;
   else
     *mpWeight = weight;
 }
Member Data Documentation
unsigned C_INT32* CCrossValidationSet::mpThreshold private
The threshold indicates the number of failed successive checks for which the objective function has not improved needed to terminate the parameter estimation.
Definition at line 352 of file CExperimentSet.h.
Referenced by getThreshold(), initializeParameter(), and setThreshold().
C_FLOAT64* CCrossValidationSet::mpWeight private
The weight of each datapoint relative to a data point of the experiment set, i.e. 1 gives each point the same weight
Definition at line 345 of file CExperimentSet.h.
Referenced by getWeight(), initializeParameter(), and setWeight().
The documentation for this class was generated from the following files:
CExperimentSet.h
CExperimentSet.cpp