COPASI API: dmnorm.cpp File Reference
dmnorm.cpp File Reference
#include <cmath>
#include <algorithm>
#include "copasi.h"
Functions
double dmnorm_ (C_INT *n, double *v, double *w)
Function Documentation
double dmnorm_ (C_INT * n, double * v, double * w)
Definition at line 35 of file dmnorm.cpp.
Referenced by CInternalSolver::dprja_(), CInternalSolver::dstoda_(), CLSODA::operator()(), and CLSODAR::operator()().
 {
   double vm = 0.0, tmp;
   double *tv = v, *tw = w, *end = tv + *n;
   while (tv != end)
     if ((tmp = fabs(*tv++) * *tw++) > vm) vm = tmp;
   return vm;
 }