COPASI API: CLNAResultWidget Class Reference
CLNAResultWidget Class Reference
#include <CLNAResultWidget.h>
Public Member Functions
CLNAResultWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool leave ()
bool loadFromBackend ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CLNAResultWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
bool saveToBackend ()
Protected Attributes
CLNAResultSubwidget * mCentralWidget
QGridLayout * mWidgetLayout
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 14 of file CLNAResultWidget.h.
Constructor & Destructor Documentation
CLNAResultWidget::CLNAResultWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 22 of file CLNAResultWidget.cpp.
References mCentralWidget, and mWidgetLayout.
   : CopasiWidget(parent, name, fl)
 {
   if (!name)
     setObjectName("CLNAResultWidget");
   setWindowTitle(trUtf8("CLNAResultWidget"));
   mWidgetLayout = new QGridLayout(this);
   mWidgetLayout->setObjectName("Layout");
   mCentralWidget = new CLNAResultSubwidget(this, "CLNAResultSubwidget");
   mWidgetLayout->addWidget(mCentralWidget, 0, 0);
 }
CLNAResultWidget::~CLNAResultWidget ()
Definition at line 40 of file CLNAResultWidget.cpp.
 {}
Member Function Documentation
bool CLNAResultWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 77 of file CLNAResultWidget.cpp.
 {
   return true;
 }
bool CLNAResultWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 72 of file CLNAResultWidget.cpp.
 {
   return true;
 }
bool CLNAResultWidget::loadFromBackend ()
Definition at line 45 of file CLNAResultWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), CLNAResultSubwidget::loadAll(), mCentralWidget, and pTask.
Referenced by CQLNAWidget::taskFinishedEvent().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CLNATask * pTask =
     dynamic_cast<CLNATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Linear Noise Approximation"]);
   if (!pTask) return false;
   mCentralWidget->loadAll(dynamic_cast<CLNAMethod*>(pTask->getMethod()));
   return true;
 }
bool CLNAResultWidget::saveToBackend () protected
Definition at line 57 of file CLNAResultWidget.cpp.
 {
   return true;
 }
bool CLNAResultWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 62 of file CLNAResultWidget.cpp.
References ListViews::ADD, CLNAResultSubwidget::loadAll(), mCentralWidget, and ListViews::MODEL.
 {
   if (objectType == ListViews::MODEL && action == ListViews::ADD)
     mCentralWidget->loadAll(NULL);
   return true;
 }
Member Data Documentation
CLNAResultSubwidget* CLNAResultWidget::mCentralWidget protected
Definition at line 34 of file CLNAResultWidget.h.
Referenced by CLNAResultWidget(), loadFromBackend(), and update().
QGridLayout* CLNAResultWidget::mWidgetLayout protected
Definition at line 32 of file CLNAResultWidget.h.
Referenced by CLNAResultWidget().
The documentation for this class was generated from the following files:
CLNAResultWidget.h
CLNAResultWidget.cpp