COPASI API: HistoWidget Class Reference
HistoWidget Class Reference
#include <HistoWidget.h>
Public Member Functions
HistoWidget (QWidget *parent=0, Qt::WindowFlags fl=0)
virtual bool LoadFromCurveSpec (const CPlotItem *curve)
virtual bool SaveToCurveSpec (CPlotItem *curve, const CPlotItem *original=NULL) const
virtual void setMultipleEditMode (bool mode)
~HistoWidget ()
Public Member Functions inherited from CQPlotEditWidget
CQPlotEditWidget (QWidget *parent=NULL, Qt::WindowFlags fl=0)
virtual void setModel (const CModel *model)
virtual ~CQPlotEditWidget ()
Protected Slots
virtual void buttonPressedX ()
Protected Attributes
const CCopasiObject * mpObjectX
Protected Attributes inherited from CQPlotEditWidget
const CModel * mpModel
Detailed Description
Definition at line 18 of file HistoWidget.h.
Constructor & Destructor Documentation
HistoWidget::HistoWidget (QWidget * parent = 0, Qt::WindowFlags fl = 0)
Definition at line 20 of file HistoWidget.cpp.
References CQIconResource::copasi, and CQIconResource::icon().
                                                          :
   CQPlotEditWidget(parent, fl),
   mpObjectX(NULL)
 {
   setupUi(this);
   mpBtnVariable->setIcon(CQIconResource::icon(CQIconResource::copasi));
 }
HistoWidget::~HistoWidget ()
Definition at line 29 of file HistoWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void HistoWidget::buttonPressedX () protected virtual slot
Definition at line 34 of file HistoWidget.cpp.
References CQPlotSubwidget::createHistograms(), FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectVector(), CQPlotEditWidget::mpModel, mpObjectX, and CQSimpleSelectionTree::NumericValues.
 {
   if (!mpModel) return;
   //  mpObjectX = CCopasiSelectionDialog::getObjectSingle(this, CQSimpleSelectionTree::NUMERIC, mpObjectX);
   //mpObjectX = CCopasiSelectionDialog::getObjectSingle(this, CQSimpleSelectionTree::PLOT_OBJECT, mpObjectX);
   std::vector< const CCopasiObject * > oldSelection;
   if (mpObjectX)
     oldSelection.push_back(mpObjectX);
   std::vector< const CCopasiObject * > objects =
     CCopasiSelectionDialog::getObjectVector(this,
         CQSimpleSelectionTree::NumericValues,
         &oldSelection);
   if (objects.size() && objects[0])
     {
       mpObjectX = objects[0];
       mpEditVariable->setText(FROM_UTF8(mpObjectX->getObjectDisplayName()));
       mpEditTitle->setText("Histogram: " + FROM_UTF8(mpObjectX->getObjectDisplayName()));
     }
   else
     {
       mpObjectX = NULL;
       mpEditVariable->setText("");
       mpEditTitle->setText("Histogram");
     }
   //check if more than one object was selected...
   if (objects.size() > 1)
     {
       CQPlotSubwidget * pParent;
       QObject* tmp = this;
       while (!(pParent = dynamic_cast< CQPlotSubwidget * >(tmp)) && this)
         tmp = tmp->parent();
       if (pParent) //tell the parent to create the remaining histogram descriptions.
         pParent->createHistograms(objects, mpEditIncrement->text().toDouble());
     }
 }
bool HistoWidget::LoadFromCurveSpec (const CPlotItem * curve) virtual
Implements CQPlotEditWidget.
Definition at line 78 of file HistoWidget.cpp.
References COutputInterface::AFTER, COutputInterface::BEFORE, C_FLOAT64, COutputInterface::DURING, FROM_UTF8, CPlotItem::getActivity(), CPlotItem::getChannels(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDisplayName(), CPlotItem::getTitle(), CPlotItem::getType(), CCopasiParameterGroup::getValue(), CPlotItem::histoItem1d, mpObjectX, and CCopasiParameter::Value::pVOID.
 {
   if (!curve)
     {
       // We need to reset the widget to defaults
       mpEditTitle->setText("");
       mpObjectX = NULL;
       mpEditVariable->setText("");
       mpEditIncrement->setText("");
       mpCheckBefore->setChecked(false);
       mpCheckDuring->setChecked(true);
       mpCheckAfter->setChecked(false);
       return true;
     }
   if (curve->getType() != CPlotItem::histoItem1d) return false;
   if (curve->getChannels().size() != 1) return false;
   //title
   mpEditTitle->setText(FROM_UTF8(curve->getTitle()));
   //variable
   mpObjectX = NULL;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (curve->getChannels().size() >= 1)
     mpObjectX = pDataModel->getDataObject(curve->getChannels()[0]);
   if (mpObjectX == pDataModel)
     {
       mpObjectX = NULL;
     }
   if (mpObjectX != NULL)
     mpEditVariable->setText(FROM_UTF8(mpObjectX->getObjectDisplayName()));
   else
     mpEditVariable->setText("");
   //other parameters:
   const void* tmp;
   if (!(tmp = curve->getValue("increment").pVOID)) return false;
   mpEditIncrement->setText(QString::number(*(const C_FLOAT64*)tmp));
   mpCheckBefore->setChecked(curve->getActivity() & COutputInterface::BEFORE);
   mpCheckDuring->setChecked(curve->getActivity() & COutputInterface::DURING);
   mpCheckAfter->setChecked(curve->getActivity() & COutputInterface::AFTER);
   return true; //TODO
 }
bool HistoWidget::SaveToCurveSpec (CPlotItem * curve, const CPlotItem * original = NULL) const virtual
Implements CQPlotEditWidget.
Definition at line 137 of file HistoWidget.cpp.
References COutputInterface::AFTER, COutputInterface::BEFORE, C_FLOAT64, C_INT32, COutputInterface::DURING, CPlotItem::getActivity(), CPlotItem::getChannels(), CCopasiObject::getCN(), CPlotItem::getTitle(), CPlotItem::getType(), CCopasiParameterGroup::getValue(), CPlotItem::histoItem1d, mpObjectX, CCopasiParameter::Value::pDOUBLE, CPlotItem::setActivity(), CPlotItem::setTitle(), CCopasiParameterGroup::setValue(), and TO_UTF8.
 {
   C_INT32 Activity = 0;
   if (mpCheckBefore->isChecked()) Activity += COutputInterface::BEFORE;
   if (mpCheckDuring->isChecked()) Activity += COutputInterface::DURING;
   if (mpCheckAfter->isChecked()) Activity += COutputInterface::AFTER;
   std::string title = TO_UTF8(mpEditTitle->text());
   CCopasiObjectName name = mpObjectX ? mpObjectX->getCN() : CCopasiObjectName("");
   C_FLOAT64 increment = mpEditIncrement->text().toDouble();
   bool thingsChanged = false;
   if (original != NULL)
     {
       if (original->getType() != CPlotItem::histoItem1d)
         thingsChanged = true;
       if (thingsChanged || original->getTitle() != title)
         thingsChanged = true;
       if (thingsChanged || *original->getValue("increment").pDOUBLE != increment)
         thingsChanged = true;
       if (thingsChanged || original->getActivity() != Activity)
         thingsChanged = true;
       if (thingsChanged || original->getChannels().size() != 1)
         thingsChanged = true;
       if (thingsChanged || original->getChannels()[0] != name)
         thingsChanged = true;
     }
   else thingsChanged = true;
   if (!thingsChanged)
     return false;
   //title
   curve->setTitle(title);
   //channels
   curve->getChannels().clear();
   curve->getChannels().push_back(CPlotDataChannelSpec(name));
   //other parameters: TODO
   curve->setValue("increment", increment);
   curve->setActivity((COutputInterface::Activity) Activity);
   return true;
 }
void HistoWidget::setMultipleEditMode (bool mode) virtual
In multiple edit mode, we don't want to edit name & channels
Implements CQPlotEditWidget.
Definition at line 197 of file HistoWidget.cpp.
 {
   mpEditTitle->setEnabled(!mode);
   mpEditVariable->setEnabled(!mode);
   mpBtnVariable->setEnabled(!mode);
 }
Member Data Documentation
const CCopasiObject* HistoWidget::mpObjectX protected
Definition at line 35 of file HistoWidget.h.
Referenced by buttonPressedX(), LoadFromCurveSpec(), and SaveToCurveSpec().
The documentation for this class was generated from the following files:
HistoWidget.h
HistoWidget.cpp