COPASI API: CQTabWidget Class Reference
CQTabWidget Class Reference
#include <CQTabWidget.h>
Signals
void copyClicked ()
void deleteClicked ()
void newClicked ()
Public Member Functions
CQTabWidget (const ListViews::ObjectType &objectType, CopasiWidget *pCopasiWidget, QWidget *parent=0, Qt::WindowFlags f=0)
virtual bool leave ()
void selectTab (int index) const
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQTabWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
void load ()
bool save ()
Private Slots
void slotBtnCommit ()
void slotBtnCopy ()
void slotBtnDelete ()
void slotBtnNew ()
void slotBtnRevert ()
Private Attributes
bool mIgnoreLeave
ListViews::ObjectType mObjectType
std::vector< CopasiWidget * > mPages
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 22 of file CQTabWidget.h.
Constructor & Destructor Documentation
CQTabWidget::CQTabWidget (const ListViews::ObjectType & objectType, CopasiWidget * pCopasiWidget, QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 24 of file CQTabWidget.cpp.
References copyClicked(), deleteClicked(), FROM_UTF8, mObjectType, ListViews::MODEL, ListViews::MODELPARAMETERSET, mPages, newClicked(), ListViews::ObjectTypeName, slotBtnCopy(), slotBtnDelete(), and slotBtnNew().
                                                             :
   CopasiWidget(parent, NULL, f),
   mPages(),
   mObjectType(objectType),
   mIgnoreLeave(false)
 {
   setupUi(this);
   mpLblName->setText("<h3>" + FROM_UTF8(ListViews::ObjectTypeName[mObjectType]) + "</h3>");
   mpTabWidget->addTab(pCopasiWidget, "Details");
   mPages.push_back(pCopasiWidget);
   switch (mObjectType)
     {
       case  ListViews::MODEL:
         mpBtnNew->hide();
         mpBtnCopy->hide();
         mpBtnDelete->hide();
         break;
       case ListViews::MODELPARAMETERSET:
         mpBtnNew->setText("Apply");
         mpBtnNew->setToolTip("Apply the current parameters to the model.");
         // The break statement is intentionally missing
       default:
         CQNotes* pNotes = new CQNotes(mpTabWidget);
         mPages.push_back(pNotes);
         mpTabWidget->addTab(pNotes, "Notes");
         connect(this, SIGNAL(newClicked()), pCopasiWidget, SLOT(slotBtnNew()));
         connect(this, SIGNAL(copyClicked()), pCopasiWidget, SLOT(slotBtnCopy()));
         connect(this, SIGNAL(deleteClicked()), pCopasiWidget, SLOT(slotBtnDelete()));
         connect(this, SIGNAL(copyClicked()), pNotes, SLOT(slotBtnCopy()));
         break;
     }
   CQMiriamWidget* pMIRIAMWidget = new CQMiriamWidget(mpTabWidget);
   mPages.push_back(pMIRIAMWidget);
   mpTabWidget->addTab(pMIRIAMWidget, "Annotation");
   connect(this, SIGNAL(copyClicked()), pMIRIAMWidget, SLOT(slotBtnCopy()));
   CQRDFTreeView* pRDFTreeView = new CQRDFTreeView(mpTabWidget);
   mPages.push_back(pRDFTreeView);
   mpTabWidget->addTab(pRDFTreeView, "RDF Browser");
 }
CQTabWidget::~CQTabWidget () virtual
Definition at line 74 of file CQTabWidget.cpp.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
void CQTabWidget::copyClicked () signal
Referenced by CQTabWidget(), and slotBtnCopy().
void CQTabWidget::deleteClicked () signal
Referenced by CQTabWidget(), and slotBtnDelete().
bool CQTabWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 94 of file CQTabWidget.cpp.
References load(), CopasiWidget::mKey, and mPages.
Referenced by slotBtnCommit(), and slotBtnRevert().
 {
   load();
   std::vector< CopasiWidget * >::iterator it = mPages.begin();
   std::vector< CopasiWidget * >::iterator end = mPages.end();
   for (; it != end; ++it)
     (*it)->enter(mKey);
   return true;
 }
bool CQTabWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 79 of file CQTabWidget.cpp.
References mIgnoreLeave, mPages, and save().
Referenced by slotBtnCommit(), slotBtnCopy(), and slotBtnNew().
 {
   if (mIgnoreLeave) return true;
   bool success = save();
   std::vector< CopasiWidget * >::iterator it = mPages.begin();
   std::vector< CopasiWidget * >::iterator end = mPages.end();
   for (; it != end; ++it)
     success &= (*it)->leave();
   return true;
 }
void CQTabWidget::load () protected
Definition at line 138 of file CQTabWidget.cpp.
References FROM_UTF8, ListViews::FUNCTION, CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CEvaluationTree::getType(), CEvaluationTree::MassAction, CopasiWidget::mKey, mObjectType, CopasiWidget::mpObject, and CEvaluationTree::PreDefined.
Referenced by enterProtected(), and update().
 {
   // mpObject can not be trusted
   mpObject = CCopasiRootContainer::getKeyFactory()->get(mKey);
   if (mpObject != NULL)
     {
       mpEditName->setText(FROM_UTF8(mpObject->getObjectName()));
       if (mObjectType == ListViews::FUNCTION)
         {
           const CFunction * pFunction = static_cast< const CFunction * >(mpObject);
           bool readOnly =
             (pFunction->getType() == CFunction::PreDefined ||
              pFunction->getType() == CFunction::MassAction);
           mpEditName->setReadOnly(readOnly);
           mpBtnCommit->setEnabled(!readOnly);
           mpBtnRevert->setEnabled(!readOnly);
           mpBtnDelete->setEnabled(!readOnly);
         }
     }
   else
     {
       mpEditName->setText("");
     }
 }
void CQTabWidget::newClicked () signal
Referenced by CQTabWidget(), slotBtnCopy(), and slotBtnNew().
bool CQTabWidget::save () protected
Definition at line 167 of file CQTabWidget.cpp.
References CCopasiDataModel::changed(), FROM_UTF8, CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CQMessageBox::information(), CopasiWidget::mKey, mObjectType, mPages, CopasiWidget::mpDataModel, CopasiWidget::mpObject, ListViews::ObjectTypeName, CopasiWidget::protectedNotify(), ListViews::RENAME, CCopasiObject::setObjectName(), and TO_UTF8.
Referenced by leave().
 {
   // mpObject can not be trusted
   mpObject = CCopasiRootContainer::getKeyFactory()->get(mKey);
   if (mpObject == NULL) return false;
   // We need to tell the sub-widgets to ignore all notifications
   std::vector< CopasiWidget * >::iterator it = mPages.begin();
   std::vector< CopasiWidget * >::iterator end = mPages.end();
   for (; it != end; ++it)
     (*it)->setIgnoreUpdates(true);
   if (mpObject->getObjectName() != TO_UTF8(mpEditName->text()))
     {
       if (!mpObject->setObjectName(TO_UTF8(mpEditName->text())))
         {
           QString msg;
           msg = "Unable to rename " + FROM_UTF8(ListViews::ObjectTypeName[mObjectType]).toLower() + " '" + FROM_UTF8(mpObject->getObjectName()) + "'\n"
                 + "to '" + mpEditName->text() + "' since a " + FROM_UTF8(ListViews::ObjectTypeName[mObjectType]).toLower() + " with that name already exists.\n";
           CQMessageBox::information(this,
                                     "Unable to rename " + FROM_UTF8(ListViews::ObjectTypeName[mObjectType]),
                                     msg,
                                     QMessageBox::Ok, QMessageBox::Ok);
           mpEditName->setText(FROM_UTF8(mpObject->getObjectName()));
         }
       else
         {
           protectedNotify(mObjectType, ListViews::RENAME, mKey);
           if (mpDataModel != NULL)
             {
               mpDataModel->changed();
             }
         }
     }
   // We need to tell the sub-widgets to accept notifications again
   it = mPages.begin();
   end = mPages.end();
   for (; it != end; ++it)
     (*it)->setIgnoreUpdates(false);
   return true;
 }
void CQTabWidget::selectTab (int index) const
Definition at line 133 of file CQTabWidget.cpp.
Referenced by CopasiUI3Window::newDoc(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotImportSBMLFinished(), and CopasiUI3Window::slotImportSBMLFromStringFinished().
 {
   mpTabWidget->setCurrentIndex(index);
 }
void CQTabWidget::slotBtnCommit () private slot
Definition at line 217 of file CQTabWidget.cpp.
References enterProtected(), and leave().
 {
   mpBtnCommit->setFocus();
   leave();
   enterProtected();
 }
void CQTabWidget::slotBtnCopy () private slot
Definition at line 248 of file CQTabWidget.cpp.
References CQSpeciesDetail::copy(), CQCompartment::copy(), ReactionsWidget1::copy(), copyClicked(), leave(), mIgnoreLeave, mPages, and newClicked().
Referenced by CQTabWidget().
 {
   mpBtnCopy->setFocus();
   leave();
   mIgnoreLeave = true;
   // CQCompartments and CQSpecies have copy options, use CModelExpansion, and do their own switching.
   if (QString(mPages[0]->metaObject()->className()) == "CQCompartment")
     {
       CQCompartment * pQCompartment = dynamic_cast< CQCompartment * >(mPages[0]);
       pQCompartment->copy();
     }
   else if (QString(mPages[0]->metaObject()->className()) == "CQSpeciesDetail")
     {
       CQSpeciesDetail * pQSpeciesDetail = dynamic_cast< CQSpeciesDetail * >(mPages[0]);
       pQSpeciesDetail->copy();
     }
   else if (QString(mPages[0]->metaObject()->className()) == "ReactionsWidget1")
     {
       ReactionsWidget1 * pReactionsWidget1 = dynamic_cast< ReactionsWidget1 * >(mPages[0]);
       pReactionsWidget1->copy();
     }
   else
     {
       emit copyClicked();
       emit newClicked();
     }
   mIgnoreLeave = false;
 }
void CQTabWidget::slotBtnDelete () private slot
Definition at line 230 of file CQTabWidget.cpp.
References deleteClicked(), and mIgnoreLeave.
Referenced by CQTabWidget().
 {
   mIgnoreLeave = true;
   emit deleteClicked();
   mIgnoreLeave = false;
 }
void CQTabWidget::slotBtnNew () private slot
Definition at line 237 of file CQTabWidget.cpp.
References leave(), mIgnoreLeave, and newClicked().
Referenced by CQTabWidget().
 {
   mpBtnNew->setFocus();
   leave();
   mIgnoreLeave = true;
   emit newClicked();
   mIgnoreLeave = false;
 }
void CQTabWidget::slotBtnRevert () private slot
Definition at line 225 of file CQTabWidget.cpp.
References enterProtected().
 {
   enterProtected();
 }
bool CQTabWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 107 of file CQTabWidget.cpp.
References ListViews::DELETE, load(), CopasiWidget::mIgnoreUpdates, CopasiWidget::mKey, mObjectType, CopasiWidget::mpObject, and ListViews::RENAME.
 {
   if (mIgnoreUpdates) return true;
   if (objectType == mObjectType &&
       key == mKey)
     {
       switch (action)
         {
           case ListViews::RENAME:
             load();
             break;
           case ListViews::DELETE:
             mpObject = NULL;
             break;
           default:
             break;
         }
     }
   // We do not need to update the child pages as they are directly called from listviews.
   return true;
 }
Member Data Documentation
bool CQTabWidget::mIgnoreLeave private
Definition at line 58 of file CQTabWidget.h.
Referenced by leave(), slotBtnCopy(), slotBtnDelete(), and slotBtnNew().
ListViews::ObjectType CQTabWidget::mObjectType private
Definition at line 57 of file CQTabWidget.h.
Referenced by CQTabWidget(), load(), save(), and update().
std::vector< CopasiWidget * > CQTabWidget::mPages private
Definition at line 56 of file CQTabWidget.h.
Referenced by CQTabWidget(), enterProtected(), leave(), save(), and slotBtnCopy().
The documentation for this class was generated from the following files:
CQTabWidget.h
CQTabWidget.cpp