COPASI API: CCopasiSelectionWidget Class Reference
CCopasiSelectionWidget Class Reference
#include <CCopasiSelectionWidget.h>
Public Member Functions
CCopasiSelectionWidget (QWidget *parent=0)
void commit ()
bool expertMode () const
bool isSingleSelection () const
void populateTree (const CModel *model, const CQSimpleSelectionTree::ObjectClasses &classes)
void setExpertMode (bool expertMode)
void setOutputVector (std::vector< const CCopasiObject * > *outputVector)
void setSingleSelection (bool singleSelection)
~CCopasiSelectionWidget ()
Protected Attributes
bool mExpertMode
ObjectBrowserWidget * mpObjectBrowser
std::vector< const
CCopasiObject * > * mpOutputVector
CQSimpleSelectionTree * mpSimpleTree
bool mSingleSelect
Detailed Description
Definition at line 28 of file CCopasiSelectionWidget.h.
Constructor & Destructor Documentation
CCopasiSelectionWidget::CCopasiSelectionWidget (QWidget * parent = 0)
Definition at line 31 of file CCopasiSelectionWidget.cpp.
References mpSimpleTree, setExpertMode(), and setSingleSelection().
                                                              :
     QStackedWidget(parent),
     mpSimpleTree(NULL),
     mpObjectBrowser(NULL),
     mpOutputVector(NULL),
     mSingleSelect(false),
     mExpertMode(false)
 {
   this->mpSimpleTree = new CQSimpleSelectionTree(this);
   this->addWidget(this->mpSimpleTree);
   this->setSingleSelection(false);
   this->setExpertMode(false);
 }
CCopasiSelectionWidget::~CCopasiSelectionWidget ()
Definition at line 45 of file CCopasiSelectionWidget.cpp.
References mpObjectBrowser, mpSimpleTree, and pdelete.
 {
   pdelete(mpObjectBrowser);
   delete mpSimpleTree;
 }
Member Function Documentation
void CCopasiSelectionWidget::commit ()
Definition at line 151 of file CCopasiSelectionWidget.cpp.
References CQSimpleSelectionTree::commitClicked(), ObjectBrowserWidget::commitClicked(), mExpertMode, mpObjectBrowser, mpOutputVector, mpSimpleTree, and mSingleSelect.
Referenced by CCopasiSelectionDialog::okButton_clicked(), and CCopasiPlotSelectionDialog::slotOKButtonClicked().
 {
   if (this->mpOutputVector)
     {
       if (this->mExpertMode)
         {
           this->mpObjectBrowser->commitClicked();
           if (this->mSingleSelect && this->mpOutputVector->size() > 1)
             {
               const CCopasiObject * object = this->mpOutputVector->at(0);
               this->mpOutputVector->clear();
               this->mpOutputVector->push_back(object);
             }
         }
       else
         {
           this->mpSimpleTree->commitClicked();
         }
     }
 }
bool CCopasiSelectionWidget::expertMode () const
Definition at line 146 of file CCopasiSelectionWidget.cpp.
References mExpertMode.
Referenced by setExpertMode().
 {
   return this->mExpertMode;
 }
bool CCopasiSelectionWidget::isSingleSelection () const
Definition at line 106 of file CCopasiSelectionWidget.cpp.
References mSingleSelect.
 {
   return this->mSingleSelect;
 }
void CCopasiSelectionWidget::populateTree (const CModel * model, const CQSimpleSelectionTree::ObjectClasses & classes)
Definition at line 51 of file CCopasiSelectionWidget.cpp.
References mpSimpleTree, and CQSimpleSelectionTree::populateTree().
Referenced by CCopasiPlotSelectionDialog::setModel(), and CCopasiSelectionDialog::setModel().
 {
   this->mpSimpleTree->populateTree(model, classes);
 }
void CCopasiSelectionWidget::setExpertMode (bool expertMode)
Definition at line 111 of file CCopasiSelectionWidget.cpp.
References CQSimpleSelectionTree::commitClicked(), ObjectBrowserWidget::commitClicked(), expertMode(), mExpertMode, mpObjectBrowser, mpOutputVector, mpSimpleTree, CQSimpleSelectionTree::setOutputVector(), and ObjectBrowserWidget::setOutputVector().
Referenced by CCopasiSelectionWidget(), CCopasiSelectionDialog::modeButton_toggled(), and CCopasiPlotSelectionDialog::slotExpertCheckBoxToggled().
 {
   if (this->mExpertMode == expertMode) return;
   this->mExpertMode = expertMode;
   if (this->mExpertMode)
     {
       if (!this->mpObjectBrowser)
         {
           // create the object browser only if needed
           // this saves some time if the model is large
           this->mpObjectBrowser = new ObjectBrowserWidget(this);
           this->addWidget(this->mpObjectBrowser);
         }
       this->mpSimpleTree->commitClicked();
       this->mpSimpleTree->setOutputVector(NULL);
       this->mpObjectBrowser->setOutputVector(this->mpOutputVector);
       this->setCurrentWidget(this->mpObjectBrowser);
     }
   else
     {
       // activate the SimpleTree and get the selection from the ObjectBrowser if there is one
       if (this->mpObjectBrowser)
         {
           this->mpObjectBrowser->commitClicked();
           this->mpObjectBrowser->setOutputVector(NULL);
         }
       this->mpSimpleTree->setOutputVector(this->mpOutputVector);
       this->setCurrentWidget(this->mpSimpleTree);
     }
 }
void CCopasiSelectionWidget::setOutputVector (std::vector< const CCopasiObject * > * outputVector)
Definition at line 57 of file CCopasiSelectionWidget.cpp.
References mExpertMode, mpObjectBrowser, mpOutputVector, mpSimpleTree, CQSimpleSelectionTree::setOutputVector(), and ObjectBrowserWidget::setOutputVector().
Referenced by CCopasiPlotSelectionDialog::CCopasiPlotSelectionDialog(), CCopasiSelectionDialog::CCopasiSelectionDialog(), CCopasiSelectionDialog::setOutputVector(), and CCopasiPlotSelectionDialog::setOutputVectors().
 {
   this->mpOutputVector = outputVector;
   if (this->mExpertMode)
     {
       this->mpObjectBrowser->setOutputVector(this->mpOutputVector);
     }
   else
     {
       this->mpSimpleTree->setOutputVector(this->mpOutputVector);
     }
 }
void CCopasiSelectionWidget::setSingleSelection (bool singleSelection)
Definition at line 71 of file CCopasiSelectionWidget.cpp.
References mpObjectBrowser, mpSimpleTree, and mSingleSelect.
Referenced by CCopasiPlotSelectionDialog::CCopasiPlotSelectionDialog(), CCopasiSelectionWidget(), and CCopasiSelectionDialog::setSingleSelection().
 {
   if (this->mSingleSelect == singleSelection) return;
   this->mSingleSelect = singleSelection;
   this->mpSimpleTree->clearSelection();
   if (this->mSingleSelect)
     {
       this->mpSimpleTree->setSelectionMode(QAbstractItemView::SingleSelection);
       if (this->mpObjectBrowser)
         {
           /* this needs to be implemented first !
              this->mpObjectBrowser->setSingleSelection(true);
            */
         }
     }
   else
     {
       this->mpSimpleTree->setSelectionMode(QAbstractItemView::ExtendedSelection);
       if (this->mpObjectBrowser)
         {
           /* this needs to be implemented first !
              this->mpObjectBrowser->setSingleSelection(true);
            */
         }
     }
 }
Member Data Documentation
bool CCopasiSelectionWidget::mExpertMode protected
Definition at line 50 of file CCopasiSelectionWidget.h.
Referenced by commit(), expertMode(), setExpertMode(), and setOutputVector().
ObjectBrowserWidget* CCopasiSelectionWidget::mpObjectBrowser protected
Definition at line 47 of file CCopasiSelectionWidget.h.
Referenced by commit(), setExpertMode(), setOutputVector(), setSingleSelection(), and ~CCopasiSelectionWidget().
std::vector< const CCopasiObject * >* CCopasiSelectionWidget::mpOutputVector protected
Definition at line 48 of file CCopasiSelectionWidget.h.
Referenced by commit(), setExpertMode(), and setOutputVector().
CQSimpleSelectionTree* CCopasiSelectionWidget::mpSimpleTree protected
Definition at line 46 of file CCopasiSelectionWidget.h.
Referenced by CCopasiSelectionWidget(), commit(), populateTree(), setExpertMode(), setOutputVector(), setSingleSelection(), and ~CCopasiSelectionWidget().
bool CCopasiSelectionWidget::mSingleSelect protected
Definition at line 49 of file CCopasiSelectionWidget.h.
Referenced by commit(), isSingleSelection(), and setSingleSelection().
The documentation for this class was generated from the following files:
CCopasiSelectionWidget.h
CCopasiSelectionWidget.cpp