COPASI API: CScanWidgetRepeat Class Reference
CScanWidgetRepeat Class Reference
#include <CScanWidgetRepeat.h>
Public Member Functions
CScanWidgetRepeat (QWidget *parent=0)
CScanWidgetRepeat (const CScanWidgetRepeat &src, QWidget *parent=0)
virtual void load (const CCopasiParameterGroup *pItem)
virtual bool save (CCopasiParameterGroup *pItem) const
virtual ~CScanWidgetRepeat ()
Public Member Functions inherited from CScanItemData
CScanItemData (const CScanItemData &src)
const CScanProblem::Type & getType () const
virtual ~CScanItemData ()
Private Member Functions
void init ()
Additional Inherited Members
Protected Member Functions inherited from CScanItemData
CScanItemData (const CScanProblem::Type &type)
Protected Attributes inherited from CScanItemData
CCopasiParameterGroup * mpData
CScanProblem::Type mType
Detailed Description
Definition at line 27 of file CScanWidgetRepeat.h.
Constructor & Destructor Documentation
CScanWidgetRepeat::CScanWidgetRepeat (QWidget * parent = 0)
Definition at line 33 of file CScanWidgetRepeat.cpp.
References init().
                                                     :
     QWidget(parent),
     CScanItemData(CScanProblem::SCAN_REPEAT)
 {
   setupUi(this);
   init();
 }
CScanWidgetRepeat::CScanWidgetRepeat (const CScanWidgetRepeat & src, QWidget * parent = 0)
Definition at line 41 of file CScanWidgetRepeat.cpp.
References init(), load(), and CScanItemData::mpData.
                                                                                     :
     QWidget(parent),
     CScanItemData(src)
 {
   setupUi(this);
   init();
   load(mpData);
 }
CScanWidgetRepeat::~CScanWidgetRepeat () virtual
Definition at line 53 of file CScanWidgetRepeat.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CScanWidgetRepeat::init () private
Definition at line 58 of file CScanWidgetRepeat.cpp.
Referenced by CScanWidgetRepeat().
 {
   lineEditNumber->setValidator(new QIntValidator(lineEditNumber));
 }
void CScanWidgetRepeat::load (const CCopasiParameterGroup * pItem) virtual
Implements CScanItemData.
Definition at line 64 of file CScanWidgetRepeat.cpp.
References C_INT32, CCopasiParameterGroup::getValue(), CScanItemData::mpData, CCopasiParameter::Value::pINT, and CScanProblem::SCAN_REPEAT.
Referenced by CScanWidgetRepeat(), ScanWidget::loadTask(), and ScanWidget::slotAddItem().
 {
   if (pItem == NULL) return;
   *mpData = *pItem;
   C_INT32 * tmp;
   if (!(tmp = mpData->getValue("Type").pINT))
     return;
   if (*(CScanProblem::Type *) tmp != CScanProblem::SCAN_REPEAT)
     return;
   if (!(tmp = mpData->getValue("Number of steps").pINT))
     return;
   lineEditNumber->setText(QString::number(* tmp));
   return;
 }
bool CScanWidgetRepeat::save (CCopasiParameterGroup * pItem) const virtual
Implements CScanItemData.
Definition at line 87 of file CScanWidgetRepeat.cpp.
References CScanItemData::mpData, and CCopasiParameterGroup::setValue().
 {
   mpData->setValue("Number of steps", lineEditNumber->text().toUInt());
   if (pItem != NULL)
     {
       if (*mpData == *pItem) return false;
       *pItem = *mpData;
       return true;
     }
   return false;
 }
The documentation for this class was generated from the following files:
CScanWidgetRepeat.h
CScanWidgetRepeat.cpp