COPASI API: CQLayoutMainWindow Class Reference
CQLayoutMainWindow Class Reference
#include <CQLayoutMainWindow.h>
Public Slots
void changeFontSize ()
void changeMinMaxNodeSizes ()
void changeStepValue (int i)
void endOfAnimationReached ()
void loadData ()
void mapLabelsToCircles ()
void mapLabelsToRectangles ()
void saveImage ()
double slotFitToScreen ()
void slotLoopActivated (bool checked)
void slotParameterTableToggled (bool checked)
void slotPlayerControlToggled (bool checked)
void slotResetView ()
void slotToolbarToggled (bool checked)
void slotValueTableToggled (bool checked)
Public Member Functions
void addItemInAnimation (std::string s)
CQLayoutMainWindow (QWidget *pParent)
bool getAnimationRunning ()
CQPlayerControlWidget * getControlWidget ()
size_t getCurrentStep ()
C_INT16 getFontSize ()
CVisParameters::MAPPING_MODE getMappingMode ()
C_FLOAT64 getMaxNodeSize ()
C_FLOAT64 getMinNodeSize ()
CVisParameters::SCALING_MODE getScalingMode ()
C_INT32 getStepsPerSecond ()
void insertValueTable (CDataEntity dataSet)
void removeItemInAnimation (std::string s)
void setAnimationRunning (bool animationRunningP)
void setColorMode ()
void setFontSizeForLabels (C_INT32 size)
void setGlobalScaling ()
void setIndividualScaling ()
void setLayout (CLayout *pLayout)
void setMaxNodeSize (C_FLOAT64 minNdSize)
void setMaxValue (C_INT32 maxNdSize)
void setMinAndMaxValue (C_INT32 minNdSize, C_INT32 maxNdSize)
void setMinNodeSize (C_FLOAT64 minNdSize)
void setMinValue (C_INT32 minNdSize)
void setSizeMode ()
void setStepsPerSecond (C_INT16 val)
void setValueOnSlider (C_INT32)
void setZoomFactor (QString s)
void setZoomFactor (double zoom)
void updateValueTable (CDataEntity dataSet)
Static Public Attributes
static const char *const ZOOM_FACTOR_STRINGS [] = {"1%", "2%", "3%", "4%", "5%", "10%", "20%", "25%", "30%", "40%", "50%", "75%", "100%", "150%", "200%", "300%", "400%", "500%", "1000%"}
static const double ZOOM_FACTORS [] = {0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.25, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 10.0}
Private Slots
void backwardAnimation ()
void forwardAnimation ()
void loadSBMLFile ()
void parameterTableValueChanged (int row)
void pauseAnimation ()
void showAnimation ()
void showStep (int i)
void startAnimation ()
void stepBackwardAnimation ()
void stepForwardAnimation ()
void stopAnimation ()
Private Member Functions
QIcon createStartIcon ()
QIcon createStopIcon ()
bool maybeSave ()
Private Attributes
QString mCurrentPlace
bool mDataPresent
bool mLooping
QAction * mpCircularShape
QAction * mpCloseAction
CQPlayerControlWidget * mpControlWidget
QAction * mpCreatePicture
QMenu * mpFileMenu
QFrame * mpFrame
CQGLViewport * mpGLViewport
QFrame * mpInfoBox
QMenu * mpLabelShapeMenu
CLayout * mpLayout
QAction * mpLoadDataAction
QAction * mpLoopItemAction
QFrame * mpMainBox
QAction * mpMimaNodeSizes
QAction * mpOpenSBMLFile
QMenu * mpOptionsMenu
QAction * mpParameterTableAction
CQParaPanel * mpParaPanel
QMenu * mpPlayMenu
QAction * mpRectangularShape
QAction * mpSFontSize
QSplitter * mpSplitter
QSlider * mpTimeSlider
QToolBar * mpToolbar
CQCurrentValueTable * mpValTable
QAction * mpValueTableAction
QMenu * mpViewMenu
CVisParameters * mpVisParameters
QActionGroup * mpZoomActionGroup
QComboBox * mpZoomComboBox
QMenu * mpZoomMenu
Detailed Description
Definition at line 51 of file CQLayoutMainWindow.h.
Constructor & Destructor Documentation
CQLayoutMainWindow::CQLayoutMainWindow (QWidget * pParent)
Definition at line 64 of file CQLayoutMainWindow.cpp.
References backwardAnimation(), CQIconResource::copasi, CQGLViewport::createGraph(), forwardAnimation(), CQIconResource::icon(), mLooping, mpControlWidget, mpFrame, mpGLViewport, mpInfoBox, mpLayout, mpMainBox, mpParaPanel, mpSplitter, mpTimeSlider, mpToolbar, mpValTable, parameterTableValueChanged(), pauseAnimation(), showStep(), startAnimation(), stepBackwardAnimation(), stepForwardAnimation(), and stopAnimation().
                                                       :
   QFrame(pParent)
   , mpVisParameters(new CVisParameters)
   , mpParaPanel(new CQParaPanel)
   , mpValTable(new CQCurrentValueTable)
   , mpMainBox(new QFrame(this))
   , mpSplitter(new QSplitter(Qt::Horizontal, this->mpMainBox))
   , mpGLViewport(NULL)
   , mpTimeSlider(new QSlider(Qt::Horizontal))
   , mpFrame(new QFrame)
   , mpInfoBox(new QFrame)
   , mpControlWidget(new CQPlayerControlWidget)
   , mDataPresent(false)
   , mCurrentPlace(QString::null)
   , mpZoomActionGroup(new QActionGroup(this))
   , mpLayout(NULL)
 {
 #ifndef Darwin
   setWindowIcon(CQIconResource::icon(CQIconResource::copasi));
 #endif // not Darwin
   QVBoxLayout* mainLayout = new QVBoxLayout(mpMainBox);
   QVBoxLayout* infoLayout = new QVBoxLayout(mpInfoBox);
   mpSplitter->addWidget(this->mpInfoBox);
   // create split window with parameter panel and graph panel
   mainLayout->addWidget(this->mpSplitter);
   infoLayout->addWidget(this->mpParaPanel);
   infoLayout->addWidget(this->mpValTable);
   this->mpInfoBox->setLayout(infoLayout);
   // Create OpenGL widget
   // we initialize it here because the parent has to be present
   this->mpGLViewport = new CQGLViewport(this->mpSplitter);
   this->mpGLViewport->setWindowTitle("Network layout");
   this->mpSplitter->addWidget(this->mpGLViewport);
   if (this->mpLayout != NULL)
     {
       this->mpGLViewport->createGraph(this->mpLayout); // create local data structures
     }
   this->mpSplitter->setStretchFactor(this->mpSplitter->indexOf(this->mpInfoBox), 0);
   this->mpSplitter->setStretchFactor(this->mpSplitter->indexOf(this->mpGLViewport), 1);
   connect(this->mpControlWidget, SIGNAL(play()), this, SLOT(startAnimation()));
   connect(this->mpControlWidget, SIGNAL(pause()), this, SLOT(pauseAnimation()));
   connect(this->mpControlWidget, SIGNAL(stop()), this, SLOT(stopAnimation()));
   connect(this->mpControlWidget, SIGNAL(forward()), this, SLOT(forwardAnimation()));
   connect(this->mpControlWidget, SIGNAL(backward()), this, SLOT(backwardAnimation()));
   connect(this->mpControlWidget, SIGNAL(step_backward()), this, SLOT(stepBackwardAnimation()));
   connect(this->mpControlWidget, SIGNAL(step_forward()), this, SLOT(stepForwardAnimation()));
   this->mpTimeSlider->setRange(0, 100);
   this->mpTimeSlider->setValue(0);
   this->mpTimeSlider->setEnabled(false);
   this->mpTimeSlider->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);
   connect(this->mpTimeSlider, SIGNAL(valueChanged(int)), this, SLOT(showStep(int)));
   QHBoxLayout* pGridLayout = new QHBoxLayout(mpFrame);
   pGridLayout->addWidget(this->mpControlWidget);
   pGridLayout->addWidget(this->mpTimeSlider);
   this->mpFrame->setLayout(pGridLayout);
   mainLayout->addWidget(this->mpFrame);
   this->mpMainBox->setLayout(mainLayout);
   this->QFrame::setLayout(new QVBoxLayout);
   this->layout()->addWidget(this->mpMainBox);
   connect(this->mpValTable , SIGNAL(valueChanged(int)), this, SLOT(parameterTableValueChanged(int)));
   this->mLooping = false;
   this->setTabOrder(this->mpGLViewport, this->mpToolbar);
   this->setTabOrder(this->mpParaPanel, this->mpValTable);
   this->setTabOrder(this->mpValTable, this->mpControlWidget);
 }
Member Function Documentation
void CQLayoutMainWindow::addItemInAnimation (std::string s)
Definition at line 411 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), mpGLViewport, and CQGLNetworkPainter::setItemAnimated().
Referenced by parameterTableValueChanged(), and CQCurrentValueTable::setAllBoxesChecked().
 {
   mpGLViewport->getPainter()->setItemAnimated(key, true);
 }
void CQLayoutMainWindow::backwardAnimation () private slot
Definition at line 814 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), CQPlayerControlWidget::isPlaying(), mpControlWidget, mpGLViewport, mpParaPanel, mpTimeSlider, pauseAnimation(), showStep(), CQGLNetworkPainter::showStep(), and startAnimation().
Referenced by CQLayoutMainWindow(), forwardAnimation(), and stopAnimation().
 {
   // go to step 0 and redisplay
   this->pauseAnimation();
   this->mpGLViewport->getPainter()->showStep(0);
   // update the slider
   disconnect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
   this->mpTimeSlider->setValue(0.0);
   this->mpParaPanel->setStepNumber(0);
   connect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
   if (this->mpControlWidget->isPlaying())
     {
       this->startAnimation();
     }
 }
void CQLayoutMainWindow::changeFontSize () slot
Definition at line 322 of file CQLayoutMainWindow.cpp.
 {
   // choose new font size (setting of size will be invoked from FontChooser panel
   FontChooser *fCh = new FontChooser(this);
   fCh->exec();
 }
void CQLayoutMainWindow::changeMinMaxNodeSizes () slot
Definition at line 316 of file CQLayoutMainWindow.cpp.
 {
   NodeSizePanel *panel = new NodeSizePanel(this);
   panel->exec();
 }
void CQLayoutMainWindow::changeStepValue (int i) slot
Definition at line 579 of file CQLayoutMainWindow.cpp.
References mpTimeSlider.
 {
   mpTimeSlider->setValue(i);
 }
QIcon CQLayoutMainWindow::createStartIcon () private
Definition at line 648 of file CQLayoutMainWindow.cpp.
References C_INT16, and C_INT32.
 {
   C_INT32 w = 19;
   C_INT32 h = 19;
   QImage img = QImage(w, h, QImage::Format_Indexed8);
   img.setNumColors(2);
   img.setColor(0, qRgb(0, 0, 200));
   C_INT16 x, y;
   for (x = 0; x < w; x++)
     {
       for (y = 0; y < h; y++)
         {
           img.setPixel(x, y, 0);
         }
     }
   C_INT32 delta = 0;
   img.setColor(1, qRgb(255, 0, 0));
   for (x = 3; x < w - 3; x++)
     {
       for (y = 3 + delta; y < h - 3 - delta; y++)
         {
           img.setPixel(x, y, 1);
         }
       if (fmod((double) x, 2.0) == 0)
         delta++;
     }
   QPixmap *pixmap = new QPixmap();
   pixmap->fromImage(img);
   QIcon iconset = QIcon(*pixmap);
   delete pixmap;
   return iconset;
 }
QIcon CQLayoutMainWindow::createStopIcon () private
Definition at line 686 of file CQLayoutMainWindow.cpp.
References C_INT16, and C_INT32.
 {
   C_INT32 w = 20;
   C_INT32 h = 20;
   QImage img = QImage(w, h, QImage::Format_Indexed8);
   img.setNumColors(2);
   img.setColor(0, qRgb(0, 0, 200));
   C_INT16 x, y;
   for (x = 0; x < w; x++)
     {
       for (y = 0; y < h; y++)
         {
           img.setPixel(x, y, 0);
         }
     }
   C_INT32 delta = 4;
   img.setColor(1, qRgb(255, 0, 0));
   for (x = (delta - 1); x <= (w - delta); x++)
     {
       for (y = (delta - 1); y <= (h - delta); y++)
         {
           img.setPixel(x, y, 1);
         }
     }
   QPixmap *pixmap = new QPixmap();
   pixmap->fromImage(img);
   QIcon iconset = QIcon(*pixmap);
   delete pixmap;
   return iconset;
 }
void CQLayoutMainWindow::endOfAnimationReached () slot
Definition at line 553 of file CQLayoutMainWindow.cpp.
References CQPlayerControlWidget::getBackwardAction(), CQPlayerControlWidget::getPauseAction(), mLooping, and mpControlWidget.
 {
   if (this->mLooping)
     {
       this->mpControlWidget->getBackwardAction()->activate(QAction::Trigger);
     }
   else
     {
       this->mpControlWidget->getPauseAction()->activate(QAction::Trigger);
     }
 }
void CQLayoutMainWindow::forwardAnimation () private slot
Definition at line 795 of file CQLayoutMainWindow.cpp.
References backwardAnimation(), CQGLNetworkPainter::getNumberOfSteps(), CQGLViewport::getPainter(), mLooping, mpGLViewport, mpTimeSlider, pauseAnimation(), and showStep().
Referenced by CQLayoutMainWindow().
 {
   // go to last step and redisplay
   if (!this->mLooping)
     {
       this->pauseAnimation();
       double stepNumber = (double)(this->mpGLViewport->getPainter()->getNumberOfSteps() - 1);
       this->showStep(stepNumber);
       // update the slider
       disconnect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
       this->mpTimeSlider->setValue(stepNumber);
       connect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
     }
   else
     {
       this->backwardAnimation();
     }
 }
bool CQLayoutMainWindow::getAnimationRunning ()
Definition at line 167 of file CQLayoutMainWindow.cpp.
References CVisParameters::mAnimationRunning, and mpVisParameters.
Referenced by CQGLNetworkPainter::triggerAnimationStep().
 {
   if (mpVisParameters != NULL)
     {
       return mpVisParameters->mAnimationRunning;
     }
   else
     return false;
 }
CQPlayerControlWidget * CQLayoutMainWindow::getControlWidget ()
Definition at line 783 of file CQLayoutMainWindow.cpp.
References mpControlWidget.
Referenced by CQNewMainWindow::createMenus().
 {
   return this->mpControlWidget;
 }
size_t CQLayoutMainWindow::getCurrentStep ()
Definition at line 245 of file CQLayoutMainWindow.cpp.
References mpTimeSlider.
Referenced by CQGLNetworkPainter::setItemAnimated(), stepBackwardAnimation(), and stepForwardAnimation().
 {
   return (size_t) this->mpTimeSlider->value();
 }
C_INT16 CQLayoutMainWindow::getFontSize ()
Definition at line 222 of file CQLayoutMainWindow.cpp.
References CQGLNetworkPainter::getFontSize(), CQGLViewport::getPainter(), and mpGLViewport.
Referenced by FontChooser::FontChooser().
 {
   return mpGLViewport->getPainter()->getFontSize();
 }
CVisParameters::MAPPING_MODE CQLayoutMainWindow::getMappingMode ()
Definition at line 260 of file CQLayoutMainWindow.cpp.
References CVisParameters::mMappingMode, mpVisParameters, and CVisParameters::SIZE_DIAMETER_MODE.
Referenced by CQGLNetworkPainter::drawGraph(), CQGLNetworkPainter::drawNode(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::showStep(), and CQGLNetworkPainter::zoom().
 {
   if (mpVisParameters != NULL)
     {
       return mpVisParameters->mMappingMode;
     }
   else
     return CVisParameters::SIZE_DIAMETER_MODE; // default mode
 }
C_FLOAT64 CQLayoutMainWindow::getMaxNodeSize ()
Definition at line 198 of file CQLayoutMainWindow.cpp.
References C_FLOAT64, CVisParameters::mMaxNodeSize, and mpVisParameters.
Referenced by CQGLNetworkPainter::createDataSets(), NodeSizePanel::NodeSizePanel(), CQGLNetworkPainter::rescaleDataSets(), setColorMode(), CQGLNetworkPainter::setItemAnimated(), setMaxValue(), setMinAndMaxValue(), setMinValue(), setSizeMode(), CQGLNetworkPainter::showStep(), and CQGLNetworkPainter::zoom().
 {
   C_FLOAT64 maxNodeSize = 100.0;
   if (mpVisParameters != NULL)
     {
       maxNodeSize = mpVisParameters->mMaxNodeSize;
     }
   return maxNodeSize;
 }
C_FLOAT64 CQLayoutMainWindow::getMinNodeSize ()
Definition at line 185 of file CQLayoutMainWindow.cpp.
References C_FLOAT64, CVisParameters::mMinNodeSize, and mpVisParameters.
Referenced by CQGLNetworkPainter::createDataSets(), NodeSizePanel::NodeSizePanel(), CQGLNetworkPainter::rescaleDataSets(), setColorMode(), CQGLNetworkPainter::setItemAnimated(), setMaxValue(), setMinAndMaxValue(), setMinValue(), setSizeMode(), CQGLNetworkPainter::showStep(), and CQGLNetworkPainter::zoom().
 {
   C_FLOAT64 minNodeSize = 10.0;
   if (mpVisParameters != NULL)
     {
       minNodeSize = mpVisParameters->mMinNodeSize;
     }
   return minNodeSize;
 }
CVisParameters::SCALING_MODE CQLayoutMainWindow::getScalingMode ()
Definition at line 250 of file CQLayoutMainWindow.cpp.
References CVisParameters::INDIVIDUAL_SCALING, mpVisParameters, and CVisParameters::mScalingMode.
Referenced by CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::setItemAnimated(), and CQGLNetworkPainter::zoom().
 {
   if (mpVisParameters != NULL)
     {
       return mpVisParameters->mScalingMode;
     }
   else
     return CVisParameters::INDIVIDUAL_SCALING;
 }
C_INT32 CQLayoutMainWindow::getStepsPerSecond ()
Definition at line 227 of file CQLayoutMainWindow.cpp.
References mpVisParameters, and CVisParameters::mStepsPerSecond.
Referenced by CQGLNetworkPainter::runAnimation().
 {
   if (mpVisParameters != NULL)
     {
       return mpVisParameters->mStepsPerSecond;
     }
   else
     return 2;
 }
void CQLayoutMainWindow::insertValueTable (CDataEntity dataSet)
Definition at line 367 of file CQLayoutMainWindow.cpp.
References C_FLOAT64, CQGLNetworkPainter::getNameForNodeKey(), CQGLNetworkPainter::getNodeNameEntry(), CDataEntity::getNumberOfElements(), CDataEntity::getOrigValueForSpecies(), CQGLViewport::getPainter(), mpGLViewport, mpValTable, parameterTableValueChanged(), CQCurrentValueTable::setNumCols(), CQCurrentValueTable::setNumRows(), and CQCurrentValueTable::setRowInTable().
Referenced by CQGLNetworkPainter::createDataSets().
 {
   int i = 0;
   std::string key, name;
   C_FLOAT64 val;
   mpValTable->setNumRows((int) dataSet.getNumberOfElements());
   mpValTable->setNumCols(2);
   disconnect(this->mpValTable , SIGNAL(valueChanged(int)), this, SLOT(parameterTableValueChanged(int)));
   while ((key = mpGLViewport->getPainter()->getNodeNameEntry(i)) != "")
     {
       name = this->mpGLViewport->getPainter()->getNameForNodeKey(key);
       val = dataSet.getOrigValueForSpecies(key); // would be (- std::numeric_limits< C_FLOAT64 >::max()) if key not present
       mpValTable->setRowInTable(i, key, name, val);
       i++;
     }
   connect(this->mpValTable , SIGNAL(valueChanged(int)), this, SLOT(parameterTableValueChanged(int)));
 }
void CQLayoutMainWindow::loadData () slot
Definition at line 329 of file CQLayoutMainWindow.cpp.
References CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::getNumberOfSteps(), CQGLViewport::getPainter(), CQGLNetworkPainter::isCircleMode(), mDataPresent, mpControlWidget, mpGLViewport, mpParaPanel, mpTimeSlider, CQPlayerControlWidget::setCurrentStep(), CQPlayerControlWidget::setNumSteps(), and showStep().
Referenced by setLayout(), and startAnimation().
 {
   bool successfulP = mpGLViewport->getPainter()->createDataSets();
   if (successfulP)
     {
       // set the number of steps in the control widget and place the current
       // step at 0
       this->mpControlWidget->setCurrentStep(0);
       this->mpTimeSlider->setEnabled(true);
       this->mDataPresent = true;
       mpParaPanel->enableStepNumberChoice();
       size_t maxVal = mpGLViewport->getPainter()->getNumberOfSteps();
       this->mpTimeSlider->setRange(0, maxVal - 1);
       this->mpControlWidget->setNumSteps(maxVal);
       mpGLViewport->getPainter()->updateGL();
       CQGLNetworkPainter* pPainter = this->mpGLViewport->getPainter();
       if (pPainter->getNumberOfSteps() > 1)
         {
           this->mpParaPanel->enableParameterChoice();
           this->mpParaPanel->enableStepNumberChoice();
           this->mpParaPanel->enableModeChoice();
           if (pPainter->isCircleMode())
             {
               showStep(this->mpTimeSlider->value());
             }
         }
       else
         {
           this->mpParaPanel->disableParameterChoice();
           this->mpParaPanel->disableStepNumberChoice();
           this->mpParaPanel->disableModeChoice();
         }
     }
 }
void CQLayoutMainWindow::loadSBMLFile () private slot
Definition at line 270 of file CQLayoutMainWindow.cpp.
References CQGLViewport::createGraph(), CCopasiRootContainer::getDatamodelList(), mpGLViewport, mpSplitter, and CCopasiVector< T >::size().
 {
   CListOfLayouts *pLayoutList;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if ((*CCopasiRootContainer::getDatamodelList())[0] != NULL)
     {
       pLayoutList = (*CCopasiRootContainer::getDatamodelList())[0]->getListOfLayouts();
     }
   else
     pLayoutList = NULL;
   mpGLViewport = new CQGLViewport(mpSplitter);
   if (pLayoutList != NULL)
     {
       CLayout * pLayout;
       if (pLayoutList->size() > 0)
         {
           pLayout = (*pLayoutList)[0];
           mpGLViewport->createGraph(pLayout); // create local data structures
         }
     }
 }
void CQLayoutMainWindow::mapLabelsToCircles () slot
Definition at line 296 of file CQLayoutMainWindow.cpp.
References CQGLNetworkPainter::getNumberOfSteps(), CQGLViewport::getPainter(), CQGLNetworkPainter::mapLabelsToCircles(), mpGLViewport, mpTimeSlider, and showStep().
 {
   if (mpGLViewport->getPainter() != NULL)
     {
       mpGLViewport->getPainter()->mapLabelsToCircles();
       if (mpGLViewport->getPainter()->getNumberOfSteps() > 0)
         showStep(this->mpTimeSlider->value());
     }
 }
void CQLayoutMainWindow::mapLabelsToRectangles () slot
Definition at line 307 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), CQGLNetworkPainter::mapLabelsToRectangles(), and mpGLViewport.
Referenced by stopAnimation().
 {
   if (mpGLViewport->getPainter() != NULL)
     {
       mpGLViewport->getPainter()->mapLabelsToRectangles();
       mpGLViewport->getPainter()->updateGL();
     }
 }
bool CQLayoutMainWindow::maybeSave () private
Definition at line 722 of file CQLayoutMainWindow.cpp.
 {
   //  int ret = CQMessageBox::warning(this, "SimWiz",
   //                                 "Do you really want to quit?",
   //                                 //                   tr("Do you really want to quit?\n"
   //                                 //                      "XXXXXXXX"),
   //                                 QMessageBox::Yes | QMessageBox::Default,
   //                                 QMessageBox::No,
   //                                 QMessageBox::Cancel | QMessageBox::Escape);
   //  if (ret == QMessageBox::Yes)
   //    return true;
   //  else if (ret == QMessageBox::Cancel)
   //    return false;
   return true;
 }
void CQLayoutMainWindow::parameterTableValueChanged (int row) private slot
Definition at line 146 of file CQLayoutMainWindow.cpp.
References addItemInAnimation(), CQCurrentValueTable::getKeyForRow(), CQCurrentValueTable::getValueForRow(), CQGLViewport::isCircleMode(), mpGLViewport, mpValTable, removeItemInAnimation(), and CQGLViewport::updateWidget().
Referenced by CQLayoutMainWindow(), insertValueTable(), and updateValueTable().
 {
   std::string key = this->mpValTable->getKeyForRow(row);
   bool value = this->mpValTable->getValueForRow(row);
   if (value == true)
     {
       this->addItemInAnimation(key);
     }
   else
     {
       this->removeItemInAnimation(key);
     }
   // redraw the layout if we are in animation mode
   if (this->mpGLViewport->isCircleMode())
     {
       this->mpGLViewport->updateWidget();
     }
 }
void CQLayoutMainWindow::pauseAnimation () private slot
Definition at line 543 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), CVisParameters::mAnimationRunning, mpGLViewport, mpParaPanel, mpTimeSlider, mpVisParameters, and CQGLNetworkPainter::pauseAnimation().
Referenced by backwardAnimation(), CQLayoutMainWindow(), forwardAnimation(), stepBackwardAnimation(), and stepForwardAnimation().
 {
   // tell the painter that the anmation is paused
   this->mpGLViewport->getPainter()->pauseAnimation();
   this->mpVisParameters->mAnimationRunning = false;
   this->mpTimeSlider->setEnabled(true);
   mpParaPanel->enableParameterChoice();
   mpParaPanel->enableStepNumberChoice();
 }
void CQLayoutMainWindow::removeItemInAnimation (std::string s)
Definition at line 417 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), mpGLViewport, and CQGLNetworkPainter::setItemAnimated().
Referenced by parameterTableValueChanged(), and CQCurrentValueTable::setAllBoxesChecked().
 {
   mpGLViewport->getPainter()->setItemAnimated(key, false);
 }
void CQLayoutMainWindow::saveImage () slot
Definition at line 450 of file CQLayoutMainWindow.cpp.
References CQScreenshotOptionsDialog::ALL_FRAMES, CQGLNetworkPainter::export_bitmap(), CQGLNetworkPainter::getCurrentPositionX(), CQGLNetworkPainter::getCurrentPositionY(), CQGLNetworkPainter::getCurrentStep(), CQScreenshotOptionsDialog::getFrameOption(), CQScreenshotOptionsDialog::getFrameSet(), CQGLNetworkPainter::getGraphMax(), CQGLNetworkPainter::getGraphMin(), CQScreenshotOptionsDialog::getHeight(), CQScreenshotOptionsDialog::getImageHeight(), CQScreenshotOptionsDialog::getImageWidth(), CQGLNetworkPainter::getNumberOfSteps(), CQGLViewport::getPainter(), CopasiFileDialog::getSaveFileName(), CQScreenshotOptionsDialog::getWidth(), CLPoint::getX(), CQScreenshotOptionsDialog::getX(), CLPoint::getY(), CQScreenshotOptionsDialog::getY(), CQGLNetworkPainter::getZoomFactor(), mpGLViewport, CQScreenshotOptionsDialog::USER_DEFINED_FRAMES, and CQMessageBox::warning().
 {
 #ifdef DEBUG_UI
 //  qDebug() << "mCurrentPlace = " << mCurrentPlace;
 #endif
   // get the parameters
   CQGLNetworkPainter* pPainter = this->mpGLViewport->getPainter();
   assert(pPainter != NULL);
   if (pPainter != NULL)
     {
       size_t step = pPainter->getCurrentStep();
       size_t lastFrame = pPainter->getNumberOfSteps();
       double x = pPainter->getCurrentPositionX();
       double y = pPainter->getCurrentPositionY();
       double layoutX = pPainter->getGraphMin().getX();
       double layoutY = pPainter->getGraphMin().getY();
       double layoutWidth = pPainter->getGraphMax().getX() - layoutX;
       double layoutHeight = pPainter->getGraphMax().getY() - layoutY;
       unsigned int imageWidth = pPainter->width();
       unsigned int imageHeight = pPainter->height();
       double zoomFactor = pPainter->getZoomFactor();
       double width = (double)imageWidth / zoomFactor;
       double height = (double)imageHeight / zoomFactor;
       // use more sophisticated dialog
       CQScreenshotOptionsDialog* pDialog = new CQScreenshotOptionsDialog(layoutX, layoutY, layoutWidth, layoutHeight,
           x, y, width, height, pPainter->width() , pPainter->height(), lastFrame, this);
       if (pDialog->exec() == QDialog::Accepted)
         {
           // ask for the filename
           // TODO use a nicer default filename
           QString fileName = CopasiFileDialog::getSaveFileName(this, "Save Image Dialog", QString("untitled.png"), QString("PNG (*.png);;All files (*)"), QString("Choose a filename to save the image(s) under"));
           if (!fileName.isEmpty() && !fileName.isNull())
             {
               // get the frames
               std::vector<size_t> v;
               switch (pDialog->getFrameOption())
                 {
                   case CQScreenshotOptionsDialog::ALL_FRAMES:
                     // add all frames from 1 to lastFrame
                     if (lastFrame != 0)
                       {
                         for (size_t i = 1; i <= lastFrame; ++i)
{
                             v.push_back(i);
                           }
                       }
                     else
                       {
                         v.push_back(step);
                       }
                     break;
                   case CQScreenshotOptionsDialog::USER_DEFINED_FRAMES:
                     v.insert(v.begin(), pDialog->getFrameSet().begin(), pDialog->getFrameSet().end());
                     if (v.empty())
                       {
                         CQMessageBox::warning(this, "No frames selected",
                                               "The frame selection was invalid.\nExporting current frame.",
                                               QMessageBox::Ok, QMessageBox::Ok);
                         v.push_back(step);
                       }
                     break;
                   default:
                     v.push_back(step);
                     break;
                 }
               bool result = pPainter->export_bitmap(pDialog->getX(), pDialog->getY(), pDialog->getWidth(), pDialog->getHeight(), pDialog->getImageWidth(), pDialog->getImageHeight(), fileName, v);
               if (result == false)
                 {
                   CQMessageBox::warning(this, "Error creating image",
                                         "The image could not be created.",
                                         QMessageBox::Ok, QMessageBox::Ok);
                   return;
                 }
             }
         }
       delete pDialog;
     }
 }
void CQLayoutMainWindow::setAnimationRunning (bool animationRunningP)
Definition at line 177 of file CQLayoutMainWindow.cpp.
References CVisParameters::mAnimationRunning, and mpVisParameters.
Referenced by CQGLNetworkPainter::runAnimation().
 {
   if (mpVisParameters != NULL)
     {
       mpVisParameters->mAnimationRunning = animationRunningP;
     }
 }
void CQLayoutMainWindow::setColorMode ()
Definition at line 607 of file CQLayoutMainWindow.cpp.
References CVisParameters::COLOR_MODE, getMaxNodeSize(), getMinNodeSize(), CQGLViewport::getPainter(), CVisParameters::mMappingMode, mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), and showStep().
 {
   mpVisParameters->mMappingMode = CVisParameters::COLOR_MODE;
   mpGLViewport->getPainter()->rescaleDataSetsWithNewMinMax(getMinNodeSize(), getMaxNodeSize(), 0.0, 1.0, mpVisParameters->mScalingMode); // rescaling, because min and max node size changed (interpretation as color value takes place elsewhere),only [0.240] of possible HSV values (not fill circle in order to get good color range)
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setFontSizeForLabels (C_INT32 size)
Definition at line 643 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), mpGLViewport, and CQGLNetworkPainter::setFontSizeForLabels().
Referenced by FontChooser::changeFontSize().
 {
   mpGLViewport->getPainter()->setFontSizeForLabels((unsigned int) size);
 }
void CQLayoutMainWindow::setGlobalScaling ()
Definition at line 592 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), CVisParameters::GLOBAL_SCALING, mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::setScaleMode(), and showStep().
 {
   mpVisParameters->mScalingMode = mpVisParameters->GLOBAL_SCALING;
   mpGLViewport->getPainter()->setScaleMode(mpVisParameters->GLOBAL_SCALING);
   mpGLViewport->getPainter()->rescaleDataSets(mpVisParameters->GLOBAL_SCALING);
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setIndividualScaling ()
Definition at line 584 of file CQLayoutMainWindow.cpp.
References CQGLViewport::getPainter(), CVisParameters::INDIVIDUAL_SCALING, mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::setScaleMode(), and showStep().
 {
   mpVisParameters->mScalingMode = mpVisParameters->INDIVIDUAL_SCALING;
   mpGLViewport->getPainter()->setScaleMode(mpVisParameters->INDIVIDUAL_SCALING);
   mpGLViewport->getPainter()->rescaleDataSets(mpVisParameters->INDIVIDUAL_SCALING);
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setLayout (CLayout * pLayout)
Definition at line 768 of file CQLayoutMainWindow.cpp.
References CQGLViewport::createGraph(), loadData(), mpGLViewport, and mpLayout.
Referenced by CQNewMainWindow::switchMode(), and CQNewMainWindow::updateRenderer().
 {
   if (this->mpLayout == pLayout) return;
   this->mpLayout = pLayout;
   if (this->mpLayout != NULL)
     {
       this->mpGLViewport->createGraph(this->mpLayout); // create local data structures
       this->loadData();
     }
   this->update();
 }
void CQLayoutMainWindow::setMaxNodeSize (C_FLOAT64 minNdSize)
Definition at line 216 of file CQLayoutMainWindow.cpp.
References CVisParameters::mMaxNodeSize, and mpVisParameters.
Referenced by setMaxValue(), setMinAndMaxValue(), and CQGLNetworkPainter::zoom().
 {
   if (mpVisParameters != NULL)
     mpVisParameters->mMaxNodeSize = maxNdSize;
 }
void CQLayoutMainWindow::setMaxValue (C_INT32 maxNdSize)
Definition at line 628 of file CQLayoutMainWindow.cpp.
References getMaxNodeSize(), getMinNodeSize(), CQGLViewport::getPainter(), mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), setMaxNodeSize(), and showStep().
Referenced by NodeSizePanel::setMaxValue().
 {
   mpGLViewport->getPainter()->rescaleDataSetsWithNewMinMax(getMinNodeSize(), getMaxNodeSize(), getMinNodeSize(), maxNdSize, mpVisParameters->mScalingMode);
   setMaxNodeSize(maxNdSize);
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setMinAndMaxValue (C_INT32 minNdSize, C_INT32 maxNdSize)
Definition at line 635 of file CQLayoutMainWindow.cpp.
References getMaxNodeSize(), getMinNodeSize(), CQGLViewport::getPainter(), mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), setMaxNodeSize(), setMinNodeSize(), and showStep().
Referenced by NodeSizePanel::setMinAndMaxValues().
 {
   mpGLViewport->getPainter()->rescaleDataSetsWithNewMinMax(getMinNodeSize(), getMaxNodeSize(), minNdSize, maxNdSize, mpVisParameters->mScalingMode);
   setMinNodeSize(minNdSize);
   setMaxNodeSize(maxNdSize);
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setMinNodeSize (C_FLOAT64 minNdSize)
Definition at line 210 of file CQLayoutMainWindow.cpp.
References CVisParameters::mMinNodeSize, and mpVisParameters.
Referenced by setMinAndMaxValue(), setMinValue(), and CQGLNetworkPainter::zoom().
 {
   if (mpVisParameters != NULL)
     mpVisParameters->mMinNodeSize = minNdSize;
 }
void CQLayoutMainWindow::setMinValue (C_INT32 minNdSize)
Definition at line 620 of file CQLayoutMainWindow.cpp.
References getMaxNodeSize(), getMinNodeSize(), CQGLViewport::getPainter(), mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), setMinNodeSize(), and showStep().
Referenced by NodeSizePanel::setMinValue().
 {
   mpGLViewport->getPainter()->rescaleDataSetsWithNewMinMax(getMinNodeSize(), getMaxNodeSize(), minNdSize, getMaxNodeSize(), mpVisParameters->mScalingMode);
   setMinNodeSize(minNdSize);
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setSizeMode ()
Definition at line 600 of file CQLayoutMainWindow.cpp.
References getMaxNodeSize(), getMinNodeSize(), CQGLViewport::getPainter(), CVisParameters::mMappingMode, mpGLViewport, mpTimeSlider, mpVisParameters, CVisParameters::mScalingMode, CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), showStep(), and CVisParameters::SIZE_DIAMETER_MODE.
 {
   mpVisParameters->mMappingMode = CVisParameters::SIZE_DIAMETER_MODE;
   mpGLViewport->getPainter()->rescaleDataSetsWithNewMinMax(0.0, 1.0, getMinNodeSize(), getMaxNodeSize(), mpVisParameters->mScalingMode); // only [0.240] of possible HSV values (not fill circle in order to get good color range)
   showStep(this->mpTimeSlider->value());
 }
void CQLayoutMainWindow::setStepsPerSecond (C_INT16 val)
Definition at line 237 of file CQLayoutMainWindow.cpp.
References mpVisParameters, and CVisParameters::mStepsPerSecond.
 {
   if (mpVisParameters != NULL)
     {
       mpVisParameters->mStepsPerSecond = val;
     }
 }
void CQLayoutMainWindow::setValueOnSlider (C_INT32 val)
Definition at line 614 of file CQLayoutMainWindow.cpp.
References mpTimeSlider.
 {
   mpTimeSlider->setValue(val);
 }
void CQLayoutMainWindow::setZoomFactor (QString s)
Definition at line 759 of file CQLayoutMainWindow.cpp.
Referenced by CQNewMainWindow::slotFitToScreen(), CQNewMainWindow::slotZoomChanged(), and CQNewMainWindow::slotZoomMenuItemActivated().
 {
   s.remove(s.size() - 1, 1);
   // create a number from the text
   double n = s.toDouble();
   n /= 100.0;
   this->setZoomFactor(n);
 }
void CQLayoutMainWindow::setZoomFactor (double zoom)
Definition at line 754 of file CQLayoutMainWindow.cpp.
References mpGLViewport, and CQGLViewport::setZoomFactor().
 {
   this->mpGLViewport->setZoomFactor(zoom);
 }
void CQLayoutMainWindow::showAnimation () private slot
Definition at line 422 of file CQLayoutMainWindow.cpp.
References startAnimation().
 {
   startAnimation();
 }
void CQLayoutMainWindow::showStep (int i) private slot
Definition at line 565 of file CQLayoutMainWindow.cpp.
References CQGLNetworkPainter::getDataSetAt(), CQGLViewport::getPainter(), mpControlWidget, mpGLViewport, mpParaPanel, CQPlayerControlWidget::setCurrentStep(), CQGLNetworkPainter::showStep(), and updateValueTable().
Referenced by backwardAnimation(), CQLayoutMainWindow(), forwardAnimation(), loadData(), mapLabelsToCircles(), setColorMode(), setGlobalScaling(), setIndividualScaling(), setMaxValue(), setMinAndMaxValue(), setMinValue(), setSizeMode(), stepBackwardAnimation(), and stepForwardAnimation().
 {
   this->mpControlWidget->setCurrentStep(static_cast<int>(i));
   mpGLViewport->getPainter()->showStep(static_cast<int>(i));
   mpGLViewport->getPainter()->updateGL();
   mpParaPanel->setStepNumber(static_cast<int>(i));
   CDataEntity* srcData = mpGLViewport->getPainter()->getDataSetAt(static_cast<int>(i));
   if (srcData)
     {
       updateValueTable(*srcData);
     }
 }
double CQLayoutMainWindow::slotFitToScreen () slot
Make the layout fit the screen.
Make the layout fit the screen. Return the new zoom factor.
Definition at line 743 of file CQLayoutMainWindow.cpp.
References CQGLViewport::fitToScreen(), and mpGLViewport.
Referenced by CQNewMainWindow::slotFitToScreen().
 {
   double zoom = this->mpGLViewport->fitToScreen();
   return zoom;
 }
void CQLayoutMainWindow::slotLoopActivated (bool checked) slot
Definition at line 906 of file CQLayoutMainWindow.cpp.
References mLooping.
 {
   this->mLooping = checked;
 }
void CQLayoutMainWindow::slotParameterTableToggled (bool checked) slot
Definition at line 866 of file CQLayoutMainWindow.cpp.
References mpInfoBox, mpParaPanel, and mpValueTableAction.
 {
   (checked == true) ? this->mpParaPanel->show() : this->mpParaPanel->hide();
   // if all object in the info box are hidden, we hide the info box
   if (!checked && !this->mpValueTableAction->isChecked())
     {
       this->mpInfoBox->hide();
     }
   else
     {
       this->mpInfoBox->show();
     }
 }
void CQLayoutMainWindow::slotPlayerControlToggled (bool checked) slot
Definition at line 901 of file CQLayoutMainWindow.cpp.
References mpFrame.
 {
   (checked == true) ? this->mpFrame->show() : this->mpFrame->hide();
 }
void CQLayoutMainWindow::slotResetView () slot
Definition at line 749 of file CQLayoutMainWindow.cpp.
References mpGLViewport, and CQGLViewport::resetView().
Referenced by CQNewMainWindow::slotResetView().
 {
   this->mpGLViewport->resetView();
 }
void CQLayoutMainWindow::slotToolbarToggled (bool checked) slot
Definition at line 896 of file CQLayoutMainWindow.cpp.
References mpToolbar.
 {
   (checked == true) ? this->mpToolbar->show() : this->mpToolbar->hide();
 }
void CQLayoutMainWindow::slotValueTableToggled (bool checked) slot
Definition at line 881 of file CQLayoutMainWindow.cpp.
References mpInfoBox, mpParameterTableAction, and mpValTable.
 {
   (checked == true) ? this->mpValTable->show() : this->mpValTable->hide();
   // if all object in the info box are hidden, we hide the info box
   if (!checked && !this->mpParameterTableAction->isChecked())
     {
       this->mpInfoBox->hide();
     }
   else
     {
       this->mpInfoBox->show();
     }
 }
void CQLayoutMainWindow::startAnimation () private slot
Definition at line 427 of file CQLayoutMainWindow.cpp.
References CQGLNetworkPainter::getNumberOfSteps(), CQGLViewport::getPainter(), loadData(), CVisParameters::mAnimationRunning, mDataPresent, mpControlWidget, mpGLViewport, mpParaPanel, mpTimeSlider, mpVisParameters, CQGLNetworkPainter::runAnimation(), CQPlayerControlWidget::setNumSteps(), and CQMessageBox::warning().
Referenced by backwardAnimation(), CQLayoutMainWindow(), and showAnimation().
 {
   if (!this->mDataPresent)
     this->loadData(); // look for data
   if (this->mDataPresent)
     {
       // only if time series data present
       this->mpVisParameters->mAnimationRunning = true;
       this->mpTimeSlider->setEnabled(false);
       this->mpGLViewport->getPainter()->runAnimation();
       this->mpControlWidget->setNumSteps(this->mpGLViewport->getPainter()->getNumberOfSteps());
       this->mpParaPanel->disableParameterChoice();
       this->mpParaPanel->disableStepNumberChoice();
     }
   else
     {
       CQMessageBox::warning(this, "Missing Data",
                             "No data found: \nYou first have to create a time course.",
                             QMessageBox::Ok, QMessageBox::Ok);
     }
 }
void CQLayoutMainWindow::stepBackwardAnimation () private slot
Definition at line 849 of file CQLayoutMainWindow.cpp.
References getCurrentStep(), mpTimeSlider, pauseAnimation(), and showStep().
Referenced by CQLayoutMainWindow().
 {
   // lower step by one if possible and redisplay
   size_t currentStep = this->getCurrentStep();
   if (currentStep > 0)
     {
       --currentStep;
       this->pauseAnimation();
       this->showStep((double)currentStep);
       // update the slider
       disconnect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
       this->mpTimeSlider->setValue((double)currentStep);
       connect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
     }
 }
void CQLayoutMainWindow::stepForwardAnimation () private slot
Definition at line 831 of file CQLayoutMainWindow.cpp.
References getCurrentStep(), CQGLNetworkPainter::getNumberOfSteps(), CQGLViewport::getPainter(), mpGLViewport, mpTimeSlider, pauseAnimation(), and showStep().
Referenced by CQLayoutMainWindow().
 {
   // raise step by one if possible and continue animation
   // go to last step and redisplay
   size_t currentStep = this->getCurrentStep();
   ++currentStep;
   if (currentStep < this->mpGLViewport->getPainter()->getNumberOfSteps())
     {
       this->pauseAnimation();
       this->showStep((double)currentStep);
       // update the slider
       disconnect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
       this->mpTimeSlider->setValue((double)currentStep);
       connect(mpTimeSlider, SIGNAL(valueChanged(double)), this, SLOT(showStep(double)));
     }
 }
void CQLayoutMainWindow::stopAnimation () private slot
Definition at line 788 of file CQLayoutMainWindow.cpp.
References backwardAnimation(), and mapLabelsToRectangles().
Referenced by CQLayoutMainWindow().
 {
   // go to step 0 and stop
   this->backwardAnimation();
   this->mapLabelsToRectangles();
 }
void CQLayoutMainWindow::updateValueTable (CDataEntity dataSet)
Definition at line 387 of file CQLayoutMainWindow.cpp.
References C_FLOAT64, CQGLNetworkPainter::getNameForNodeKey(), CQGLNetworkPainter::getNodeNameEntry(), CDataEntity::getOrigValueForSpecies(), CQGLViewport::getPainter(), mpGLViewport, mpValTable, CQCurrentValueTable::numRows(), parameterTableValueChanged(), and CQCurrentValueTable::updateRowInTable().
Referenced by showStep().
 {
   int i = 0;
   std::string key, name;
   C_FLOAT64 val;
   disconnect(this->mpValTable , SIGNAL(valueChanged(int)), this, SLOT(parameterTableValueChanged(int)));
   while ((key = mpGLViewport->getPainter()->getNodeNameEntry(i)) != "")
     {
       name = mpGLViewport->getPainter()->getNameForNodeKey(key);
       val = dataSet.getOrigValueForSpecies(key); // would be (- std::numeric_limits< C_FLOAT64 >::max()) if key not present
       if (mpValTable->numRows() > i)
         {
           mpValTable->updateRowInTable(i, val);
         }
       i++;
     }
   connect(this->mpValTable , SIGNAL(valueChanged(int)), this, SLOT(parameterTableValueChanged(int)));
 }
Member Data Documentation
QString CQLayoutMainWindow::mCurrentPlace private
Definition at line 169 of file CQLayoutMainWindow.h.
bool CQLayoutMainWindow::mDataPresent private
Definition at line 168 of file CQLayoutMainWindow.h.
Referenced by loadData(), and startAnimation().
bool CQLayoutMainWindow::mLooping private
Definition at line 172 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), endOfAnimationReached(), forwardAnimation(), and slotLoopActivated().
QAction* CQLayoutMainWindow::mpCircularShape private
Definition at line 150 of file CQLayoutMainWindow.h.
QAction* CQLayoutMainWindow::mpCloseAction private
Definition at line 148 of file CQLayoutMainWindow.h.
CQPlayerControlWidget* CQLayoutMainWindow::mpControlWidget private
Definition at line 166 of file CQLayoutMainWindow.h.
Referenced by backwardAnimation(), CQLayoutMainWindow(), endOfAnimationReached(), getControlWidget(), loadData(), showStep(), and startAnimation().
QAction* CQLayoutMainWindow::mpCreatePicture private
Definition at line 146 of file CQLayoutMainWindow.h.
QMenu* CQLayoutMainWindow::mpFileMenu private
Definition at line 139 of file CQLayoutMainWindow.h.
QFrame* CQLayoutMainWindow::mpFrame private
Definition at line 162 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), and slotPlayerControlToggled().
CQGLViewport* CQLayoutMainWindow::mpGLViewport private
Definition at line 159 of file CQLayoutMainWindow.h.
Referenced by addItemInAnimation(), backwardAnimation(), CQLayoutMainWindow(), forwardAnimation(), getFontSize(), insertValueTable(), loadData(), loadSBMLFile(), mapLabelsToCircles(), mapLabelsToRectangles(), parameterTableValueChanged(), pauseAnimation(), removeItemInAnimation(), saveImage(), setColorMode(), setFontSizeForLabels(), setGlobalScaling(), setIndividualScaling(), setLayout(), setMaxValue(), setMinAndMaxValue(), setMinValue(), setSizeMode(), setZoomFactor(), showStep(), slotFitToScreen(), slotResetView(), startAnimation(), stepForwardAnimation(), and updateValueTable().
QFrame* CQLayoutMainWindow::mpInfoBox private
Definition at line 164 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), slotParameterTableToggled(), and slotValueTableToggled().
QMenu* CQLayoutMainWindow::mpLabelShapeMenu private
Definition at line 141 of file CQLayoutMainWindow.h.
CLayout* CQLayoutMainWindow::mpLayout private
Definition at line 177 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), and setLayout().
QAction* CQLayoutMainWindow::mpLoadDataAction private
Definition at line 153 of file CQLayoutMainWindow.h.
QAction* CQLayoutMainWindow::mpLoopItemAction private
Definition at line 173 of file CQLayoutMainWindow.h.
QFrame* CQLayoutMainWindow::mpMainBox private
Definition at line 157 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow().
QAction* CQLayoutMainWindow::mpMimaNodeSizes private
Definition at line 151 of file CQLayoutMainWindow.h.
QAction* CQLayoutMainWindow::mpOpenSBMLFile private
Definition at line 147 of file CQLayoutMainWindow.h.
QMenu* CQLayoutMainWindow::mpOptionsMenu private
Definition at line 140 of file CQLayoutMainWindow.h.
QAction* CQLayoutMainWindow::mpParameterTableAction private
Definition at line 175 of file CQLayoutMainWindow.h.
Referenced by slotValueTableToggled().
CQParaPanel* CQLayoutMainWindow::mpParaPanel private
Definition at line 155 of file CQLayoutMainWindow.h.
Referenced by backwardAnimation(), CQLayoutMainWindow(), loadData(), pauseAnimation(), showStep(), slotParameterTableToggled(), and startAnimation().
QMenu* CQLayoutMainWindow::mpPlayMenu private
Definition at line 144 of file CQLayoutMainWindow.h.
QAction* CQLayoutMainWindow::mpRectangularShape private
Definition at line 149 of file CQLayoutMainWindow.h.
QAction* CQLayoutMainWindow::mpSFontSize private
Definition at line 152 of file CQLayoutMainWindow.h.
QSplitter* CQLayoutMainWindow::mpSplitter private
Definition at line 158 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), and loadSBMLFile().
QSlider* CQLayoutMainWindow::mpTimeSlider private
Definition at line 160 of file CQLayoutMainWindow.h.
Referenced by backwardAnimation(), changeStepValue(), CQLayoutMainWindow(), forwardAnimation(), getCurrentStep(), loadData(), mapLabelsToCircles(), pauseAnimation(), setColorMode(), setGlobalScaling(), setIndividualScaling(), setMaxValue(), setMinAndMaxValue(), setMinValue(), setSizeMode(), setValueOnSlider(), startAnimation(), stepBackwardAnimation(), and stepForwardAnimation().
QToolBar* CQLayoutMainWindow::mpToolbar private
Definition at line 170 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), and slotToolbarToggled().
CQCurrentValueTable* CQLayoutMainWindow::mpValTable private
Definition at line 156 of file CQLayoutMainWindow.h.
Referenced by CQLayoutMainWindow(), insertValueTable(), parameterTableValueChanged(), slotValueTableToggled(), and updateValueTable().
QAction* CQLayoutMainWindow::mpValueTableAction private
Definition at line 174 of file CQLayoutMainWindow.h.
Referenced by slotParameterTableToggled().
QMenu* CQLayoutMainWindow::mpViewMenu private
Definition at line 142 of file CQLayoutMainWindow.h.
CVisParameters* CQLayoutMainWindow::mpVisParameters private
Definition at line 138 of file CQLayoutMainWindow.h.
Referenced by getAnimationRunning(), getMappingMode(), getMaxNodeSize(), getMinNodeSize(), getScalingMode(), getStepsPerSecond(), pauseAnimation(), setAnimationRunning(), setColorMode(), setGlobalScaling(), setIndividualScaling(), setMaxNodeSize(), setMaxValue(), setMinAndMaxValue(), setMinNodeSize(), setMinValue(), setSizeMode(), setStepsPerSecond(), and startAnimation().
QActionGroup* CQLayoutMainWindow::mpZoomActionGroup private
Definition at line 176 of file CQLayoutMainWindow.h.
QComboBox* CQLayoutMainWindow::mpZoomComboBox private
Definition at line 171 of file CQLayoutMainWindow.h.
QMenu* CQLayoutMainWindow::mpZoomMenu private
Definition at line 143 of file CQLayoutMainWindow.h.
const char *const CQLayoutMainWindow::ZOOM_FACTOR_STRINGS = {"1%", "2%", "3%", "4%", "5%", "10%", "20%", "25%", "30%", "40%", "50%", "75%", "100%", "150%", "200%", "300%", "400%", "500%", "1000%"} static
Definition at line 86 of file CQLayoutMainWindow.h.
const double CQLayoutMainWindow::ZOOM_FACTORS = {0.01, 0.02, 0.03, 0.04, 0.05, 0.1, 0.2, 0.25, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 10.0} static
Definition at line 87 of file CQLayoutMainWindow.h.
The documentation for this class was generated from the following files:
CQLayoutMainWindow.h
CQLayoutMainWindow.cpp