COPASI API: CQOscillationTaskWidget Class Reference
CQOscillationTaskWidget Class Reference
#include <CQOscillationTaskWidget.h>
Public Member Functions
CQOscillationTaskWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQOscillationTaskWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
virtual bool taskFinishedEvent ()
Private Member Functions
void init ()
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 27 of file CQOscillationTaskWidget.h.
Constructor & Destructor Documentation
CQOscillationTaskWidget::CQOscillationTaskWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 33 of file CQOscillationTaskWidget.cpp.
References init().
     : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQOscillationTaskWidget::~CQOscillationTaskWidget () virtual
Definition at line 44 of file CQOscillationTaskWidget.cpp.
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQOscillationTaskWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 165 of file CQOscillationTaskWidget.cpp.
 {
   return NULL;
 }
void CQOscillationTaskWidget::init () private
Definition at line 50 of file CQOscillationTaskWidget.cpp.
References TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, and CQTaskHeaderWidget::setTaskName().
Referenced by CQOscillationTaskWidget().
 {
   mpHeaderWidget->setTaskName("Oscillation");
   oscillationTWLayout->insertWidget(0, mpHeaderWidget); // header
   // crossSectionTWLayout->insertSpacing(1, 14);      // space between header and body
   oscillationTWLayout->addWidget(mpBtnWidget);      // 'footer'
 //  addMethodParameterTable(0);
 }
bool CQOscillationTaskWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 109 of file CQOscillationTaskWidget.cpp.
 {
   /*
     // load Task
     CCrossSectionTask * pTask =
       dynamic_cast< CCrossSectionTask * >(mpTask);
     if (!pTask) return false;
     // load functions from the Parent, TaskWidget
     loadCommon();
     loadMethod();
     // load Problem
     CCrossSectionProblem* pProblem =
       dynamic_cast<CCrossSectionProblem *>(pTask->getProblem());
     assert(pProblem);
     CCrossSectionMethod* pMethod =
       dynamic_cast<CCrossSectionMethod *>(pTask->getMethod());
     assert(pMethod);
     // load the saved values
     mpCheckLC->setChecked(pProblem->getFlagLimitCrossings());
     mpLineEditLC->setEnabled(pProblem->getFlagLimitCrossings());
     if (pProblem->getFlagLimitCrossings())
       mpLineEditLC->setText(QString::number(pProblem->getCrossingsLimit()));
     else
       mpLineEditLC->setText("");
     mpCheckLT->setChecked(pProblem->getFlagLimitTime());
     mpLineEditLT->setEnabled(pProblem->getFlagLimitTime());
     if (pProblem->getFlagLimitTime())
       mpLineEditLT->setText(QString::number(pProblem->getTimeLimit()));
     else
       mpLineEditLT->setText("");
     if (pProblem->getOutputStartTime() > 0.0)
       {
         mpCheck->setChecked(true);
         mpLineEdit->setEnabled(true);
         mpLineEdit->setText(QString::number(pProblem->getOutputStartTime()));
       }
     else
       {
         mpCheck->setChecked(false);
         mpLineEdit->setEnabled(false);
         mpLineEdit->setText("");
       }
   */
   return true;
 }
bool CQOscillationTaskWidget::runTask () virtual
Implements TaskWidget.
Definition at line 61 of file CQOscillationTaskWidget.cpp.
 {
   return true;
 }
bool CQOscillationTaskWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 74 of file CQOscillationTaskWidget.cpp.
 {
   /*
     // check the existence of Task
     CCrossSectionTask * pTask =
       dynamic_cast< CCrossSectionTask * >(mpTask);
     if (!pTask) return false;
     // save functions from the Parent, TaskWidget
     saveCommon();
     saveMethod();
     // check the existence of Problem
     CCrossSectionProblem* pProblem =
       dynamic_cast<CCrossSectionProblem *>(pTask->getProblem());
     assert(pProblem);
     // save the actual changes
     if (mpCheckLC->isChecked())
       pProblem->setCrossingsLimit(mpLineEditLC->text().toDouble());
     if (mpCheckLT->isChecked())
       pProblem->setTimeLimit(mpLineEditLT->text().toDouble());
     if (mpCheck->isChecked())
       pProblem->setOutputStartTime(mpLineEdit->text().toDouble());
   */
   return true;
 }
bool CQOscillationTaskWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from TaskWidget.
Definition at line 66 of file CQOscillationTaskWidget.cpp.
 {
   return true;
 }
The documentation for this class was generated from the following files:
CQOscillationTaskWidget.h
CQOscillationTaskWidget.cpp