COPASI API: CCopasiXMLParser::ModelParameterSetElement Class Reference
CCopasiXMLParser::ModelParameterSetElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ModelParameterSetElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ModelParameterSetElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
ModelParameterSet = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
Content
}
Private Attributes
std::string mKey
ModelParameterElement * mpModelParameterElement
ModelParameterGroupElement * mpModelParameterGroupElement
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 107 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ModelParameterSetElement::Element private
Enum of invoked parsers
Enumerator
ModelParameterSet
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
Content
Definition at line 115 of file CCopasiXMLParser.h.
Constructor & Destructor Documentation
CCopasiXMLParser::ModelParameterSetElement::ModelParameterSetElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 151 of file ListOfModelParameterSets.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mKey(),
   mpModelParameterGroupElement(NULL),
   mpModelParameterElement(NULL)
 {}
CCopasiXMLParser::ModelParameterSetElement::~ModelParameterSetElement () virtual
Destructor
Definition at line 159 of file ListOfModelParameterSets.cpp.
References pdelete.
 {
   pdelete(mpModelParameterGroupElement);
   pdelete(mpModelParameterElement);
 }
Member Function Documentation
void CCopasiXMLParser::ModelParameterSetElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 275 of file ListOfModelParameterSets.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CModelParameterSet::getKey(), CCopasiXMLParser::mCommon, MCXML, SCopasiXMLParserCommon::ModelParameterGroupStack, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentModelParameter, CAnnotation::setMiriamAnnotation(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case ModelParameterSet:
         if (strcmp(pszName, "ModelParameterSet"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ModelParameterSet", mParser.getCurrentLineNumber());
         mCommon.ModelParameterGroupStack.pop();
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         {
           CModelParameterSet * pModelParameterSet = static_cast< CModelParameterSet * >(mCommon.ModelParameterGroupStack.top());
           pModelParameterSet->setMiriamAnnotation(mCommon.CharacterData, pModelParameterSet->getKey(), mKey);
         }
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         static_cast< CModelParameterSet * >(mCommon.ModelParameterGroupStack.top())->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         static_cast< CModelParameterSet * >(mCommon.ModelParameterGroupStack.top())->getUnsupportedAnnotations() =
           mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case Content:
         if (strcmp(pszName, "ModelParameterGroup") &&
             strcmp(pszName, "ModelParameter"))
           {
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "ModelParameterGroup or ModelParameter", mParser.getCurrentLineNumber());
           }
         if (mCommon.pCurrentModelParameter != NULL)
           {
             mCommon.ModelParameterGroupStack.top()->add(mCommon.pCurrentModelParameter);
             mCommon.pCurrentModelParameter = NULL;
           }
         // Content may be repeated therefore we set to the previous element which is ListOfUnkownAnnotations.
         mCurrentElement = mLastKnownElement = ModelParameterSet;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ModelParameterSetElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 165 of file ListOfModelParameterSets.cpp.
References CCopasiVectorN< CType >::add(), CKeyFactory::addFix(), CCopasiMessage::EXCEPTION, CModel::getModelParameterSets(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, SCopasiXMLParserCommon::ModelParameterGroupStack, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, CCopasiObject::setObjectName(), and UNKNOWN_ELEMENT.
 {
   const char * Name;
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case ModelParameterSet:
             if (strcmp(pszName, "ModelParameterSet"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "ModelParameterSet", mParser.getCurrentLineNumber());
             mLastKnownElement = ModelParameterSet;
             // Element specific code.
             mKey = mParser.getAttributeValue("key", papszAttrs);
             Name = mParser.getAttributeValue("name", papszAttrs);
             {
               CModelParameterSet * pModelParameterSet = new CModelParameterSet(Name);
               int index = 1;
               // We need to resolve naming conflicts.
               while (!mCommon.pModel->getModelParameterSets().add(pModelParameterSet, true))
                 {
                   std::ostringstream NewName;
                   NewName << Name << "[" << index++ << "]";
                   pModelParameterSet->setObjectName(NewName.str());
                 }
               mCommon.ModelParameterGroupStack.push(pModelParameterSet);
               mCommon.KeyMap.addFix(mKey, pModelParameterSet);
             }
             return;
           case MiriamAnnotation:
             if (!strcmp(pszName, "MiriamAnnotation"))
               {
                 mpCurrentHandler = &mParser.mMiriamAnnotationElement;
                 mLastKnownElement = mCurrentElement;
               }
             break;
           case Comment:
             if (!strcmp(pszName, "Comment"))
               {
                 mpCurrentHandler = &mParser.mCommentElement;
                 mLastKnownElement = mCurrentElement;
               }
             break;
           case ListOfUnsupportedAnnotations:
             if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
               mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             break;
           case Content:
             if (!strcmp(pszName, "ModelParameterGroup"))
               {
                 /* If we do not have an etc element handler we create one. */
                 if (!mpModelParameterGroupElement)
                   mpModelParameterGroupElement = new ModelParameterGroupElement(mParser, mCommon);
                 mpCurrentHandler = mpModelParameterGroupElement;
               }
             else if (!strcmp(pszName, "ModelParameter"))
               {
                 /* If we do not have an etc element handler we create one. */
                 if (!mpModelParameterElement)
                   mpModelParameterElement = new ModelParameterElement(mParser, mCommon);
                 mpCurrentHandler = mpModelParameterElement;
               }
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::ModelParameterSetElement::mKey private
The key as provided in the XML
Definition at line 155 of file CCopasiXMLParser.h.
ModelParameterElement* CCopasiXMLParser::ModelParameterSetElement::mpModelParameterElement private
A pointer to the ModelParameter element handler
Definition at line 165 of file CCopasiXMLParser.h.
ModelParameterGroupElement* CCopasiXMLParser::ModelParameterSetElement::mpModelParameterGroupElement private
A pointer to the ModelParameterGroup element handler
Definition at line 160 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
ListOfModelParameterSets.cpp