COPASI API: CPermutation Class Reference
CPermutation Class Reference
#include <CPermutation.h>
Public Member Functions
CPermutation (CRandom *pRandom, const size_t &size)
CPermutation (const CPermutation &src)
void init ()
const size_t & next ()
const size_t & pick ()
void shuffle (const size_t &swaps=C_INVALID_INDEX)
~CPermutation ()
Private Member Functions
CPermutation ()
Private Attributes
size_t * mpBeyond
size_t * mpNext
CRandom * mpRandom
CVector< size_t > mVector
Static Private Attributes
static size_t InvalidIndex
Detailed Description
Definition at line 13 of file CPermutation.h.
Constructor & Destructor Documentation
CPermutation::CPermutation () private
Default constructor
Definition at line 14 of file CPermutation.cpp.
                            :
   mpRandom(NULL),
   mVector(),
   mpNext(NULL),
   mpBeyond(NULL)
 {};
CPermutation::CPermutation (CRandom * pRandom, const size_t & size)
Specific constructor
Parameters
CRandom * pRandom
const size_t & size
Definition at line 21 of file CPermutation.cpp.
References init().
                                                                  :
   mpRandom(pRandom),
   mVector(size),
   mpNext(NULL),
   mpBeyond(NULL)
 {
   init();
 };
CPermutation::CPermutation (const CPermutation & src)
Copy constructor
Parameters
const CPermutation & src
Definition at line 30 of file CPermutation.cpp.
References CVectorCore< CType >::array(), mpBeyond, mpNext, mVector, and CVectorCore< CType >::size().
                                                    :
   mpRandom(src.mpRandom),
   mVector(src.mVector),
   mpNext(NULL),
   mpBeyond(NULL)
 {
   if (src.mpNext != NULL)
     {
       mpNext = mVector.array() + (src.mpNext - src.mVector.array());
       mpBeyond = mVector.array() + mVector.size();
     }
 };
CPermutation::~CPermutation ()
Destructor
Definition at line 43 of file CPermutation.cpp.
 {}
Member Function Documentation
void CPermutation::init ()
Initialize the permutation
Definition at line 46 of file CPermutation.cpp.
References CVectorCore< CType >::array(), mpBeyond, mpNext, mVector, and CVectorCore< CType >::size().
Referenced by CPermutation().
 {
   size_t Index = 0;
   size_t * pIt = mVector.array();
   size_t * pEnd = pIt + mVector.size();
   for (; pIt != pEnd; ++pIt, ++Index)
     {
       *pIt = Index;
     }
   if (Index != 0)
     {
       mpNext = mVector.array();
       mpBeyond = pEnd;
     }
 }
const size_t & CPermutation::next ()
Pick the next element
Definition at line 106 of file CPermutation.cpp.
References InvalidIndex, mpBeyond, mpNext, mpRandom, mVector, and CVectorCore< CType >::size().
Referenced by COptMethodPS::buildInformants(), COptMethodDE::replicate(), COptMethodGA::replicate(), and COptMethodGASR::replicate().
 {
   if (mpRandom == NULL || mpNext == NULL) return InvalidIndex;
   mpNext++;
   if (mpNext >= mpBeyond)
     {
       mpNext -= mVector.size();
     }
   return *mpNext;
 }
const size_t & CPermutation::pick ()
Pick a random element
Definition at line 94 of file CPermutation.cpp.
References CVectorCore< CType >::array(), CRandom::getRandomU(), InvalidIndex, mpNext, mpRandom, mVector, and CVectorCore< CType >::size().
Referenced by COptMethodPS::buildInformants(), and COptMethodDE::replicate().
 {
   if (mpRandom == NULL || mpNext == NULL) return InvalidIndex;
   if (mVector.size() > 1)
     {
       mpNext = mVector.array() + mpRandom->getRandomU(mVector.size() - 1);
     }
   return *mpNext;
 }
void CPermutation::shuffle (const size_t & swaps = C_INVALID_INDEX)
Shuffle the permutation const size_t & swaps (Default: size of permutation)
Definition at line 64 of file CPermutation.cpp.
References CVectorCore< CType >::array(), C_INT32, CRandom::getRandomU(), max, min, mpNext, mpRandom, mVector, and CVectorCore< CType >::size().
Referenced by COptMethodPS::buildInformants(), COptMethodDE::replicate(), COptMethodGA::replicate(), and COptMethodGASR::replicate().
 {
   if (mpRandom == NULL || mpNext == NULL) return;
   if (mVector.size() > 1)
     {
       unsigned C_INT32 max = mVector.size() - 1;
       size_t Swaps = std::min(swaps, mVector.size());
       // We swap each element once.
       size_t tmp;
       size_t * pBegin = mVector.array();
       size_t * pIt = pBegin;
       size_t * pEnd = pIt + Swaps;
       size_t * pTo;
       for (; pIt != pEnd; ++pIt)
         {
           pTo = pBegin + mpRandom->getRandomU(max);
           if (pTo != pIt)
             {
               tmp = *pTo;
               *pTo = *pIt;
               *pIt = tmp;
             }
         }
     }
 }
Member Data Documentation
size_t CPermutation::InvalidIndex static private
Definition at line 16 of file CPermutation.h.
Referenced by next(), and pick().
size_t* CPermutation::mpBeyond private
A pointer beyond the last index
Definition at line 83 of file CPermutation.h.
Referenced by CPermutation(), init(), and next().
size_t* CPermutation::mpNext private
A pointer to the next index
Definition at line 78 of file CPermutation.h.
Referenced by CPermutation(), init(), next(), pick(), and shuffle().
CRandom* CPermutation::mpRandom private
A pointer to the random number generator to be used
Definition at line 68 of file CPermutation.h.
Referenced by next(), pick(), and shuffle().
CVector< size_t > CPermutation::mVector private
A vector containing the permutation
Definition at line 73 of file CPermutation.h.
Referenced by CPermutation(), init(), next(), pick(), and shuffle().
The documentation for this class was generated from the following files:
CPermutation.h
CPermutation.cpp