COPASI API: CCopasiXMLParser::MetaboliteReferenceGlyphElement Class Reference
CCopasiXMLParser::MetaboliteReferenceGlyphElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
MetaboliteReferenceGlyphElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~MetaboliteReferenceGlyphElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
MetaboliteReferenceGlyph = 0, BoundingBox, Position, Dimensions,
Curve
}
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3408 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::MetaboliteReferenceGlyphElement::Element private
Enumerator
MetaboliteReferenceGlyph
BoundingBox
Position
Dimensions
Curve
Definition at line 3411 of file CCopasiXMLParser.h.
     {
       MetaboliteReferenceGlyph = 0,
       BoundingBox,
       Position,
       Dimensions,
       Curve
     };
Constructor & Destructor Documentation
CCopasiXMLParser::MetaboliteReferenceGlyphElement::MetaboliteReferenceGlyphElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Definition at line 6987 of file CCopasiXMLParser.cpp.
                                                                                                                                          :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::MetaboliteReferenceGlyphElement::~MetaboliteReferenceGlyphElement () virtual
Definition at line 6992 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::MetaboliteReferenceGlyphElement::end (const XML_Char * pszName) virtual
Definition at line 7114 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "MetaboliteReferenceGlyph"))
     {
       mParser.popElementHandler();
       mCurrentElement = START_ELEMENT;
       /* Tell the parent element we are done. */
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case BoundingBox:
             break;
           case Position:
             break;
           case Dimensions:
             //tell the handler where to continue
             mCurrentElement = BoundingBox;
             break;
           case Curve:
             break;
           case UNKNOWN_ELEMENT:
             mCurrentElement = MetaboliteReferenceGlyph;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::MetaboliteReferenceGlyphElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Definition at line 6995 of file CCopasiXMLParser.cpp.
References CLReactionGlyph::addMetabReferenceGlyph(), C_INT32, CCopasiMessage::EXCEPTION, CKeyFactory::get(), CLGlyphWithCurve::getCurve(), CLGraphicalObject::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurve, SCopasiXMLParserCommon::pMetaboliteReferenceGlyph, SCopasiXMLParserCommon::pReactionGlyph, CLGraphicalObject::setHeight(), CLMetabReferenceGlyph::setMetabGlyphKey(), CLGraphicalObject::setObjectRole(), CLMetabReferenceGlyph::setRole(), CLGraphicalObject::setWidth(), CLGraphicalObject::setX(), CLGraphicalObject::setY(), CLMetabReferenceGlyph::UNDEFINED, UNKNOWN_ELEMENT, and CLMetabReferenceGlyph::XMLRole.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case MetaboliteReferenceGlyph:
         if (strcmp(pszName, "MetaboliteReferenceGlyph"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "MetaboliteReferenceGlyph", mParser.getCurrentLineNumber());
         {
           //workload
           const char * key;
           const char * name;
           const char * metaboliteGlyph;
           const char * role;
           key = mParser.getAttributeValue("key", papszAttrs);
           name = mParser.getAttributeValue("name", papszAttrs);
           metaboliteGlyph = mParser.getAttributeValue("metaboliteGlyph", papszAttrs);
           role = mParser.getAttributeValue("role", papszAttrs);
           mCommon.pMetaboliteReferenceGlyph = new CLMetabReferenceGlyph(name);
           const char * objectRole = mParser.getAttributeValue("objectRole", papszAttrs, false);
           if (objectRole != NULL && objectRole[0] != 0)
             {
               mCommon.pMetaboliteReferenceGlyph->setObjectRole(objectRole);
             }
           CLMetabGlyph * pMetabGlyph = dynamic_cast< CLMetabGlyph * >(mCommon.KeyMap.get(metaboliteGlyph));
           //if (!pMetabGlyph) fatalError();
           if (pMetabGlyph)
             mCommon.pMetaboliteReferenceGlyph->setMetabGlyphKey(pMetabGlyph->getKey());
           //interpret role string
           C_INT32 i;
           for (i = 0; (CLMetabReferenceGlyph::XMLRole[i] != "") && (CLMetabReferenceGlyph::XMLRole[i] != role); ++i) {};
           if (CLMetabReferenceGlyph::XMLRole[i] == "")
             mCommon.pMetaboliteReferenceGlyph->setRole(CLMetabReferenceGlyph::UNDEFINED);
           else
             mCommon.pMetaboliteReferenceGlyph->setRole(CLMetabReferenceGlyph::Role(i));
           mCommon.pReactionGlyph->addMetabReferenceGlyph(mCommon.pMetaboliteReferenceGlyph);
           addFix(key, mCommon.pMetaboliteReferenceGlyph);
         }
         return;
         break;
       case BoundingBox:
         if (!strcmp(pszName, "BoundingBox"))
           return;
         break;
       case Position:
         if (!strcmp(pszName, "Position"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             mCommon.pMetaboliteReferenceGlyph->setX(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("y", papszAttrs);
             mCommon.pMetaboliteReferenceGlyph->setY(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Dimensions:
         if (!strcmp(pszName, "Dimensions"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("width", papszAttrs);
             mCommon.pMetaboliteReferenceGlyph->setWidth(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("height", papszAttrs);
             mCommon.pMetaboliteReferenceGlyph->setHeight(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Curve:
         if (!strcmp(pszName, "Curve"))
           {
             mpCurrentHandler = new CurveElement(mParser, mCommon);
             if (mCommon.pMetaboliteReferenceGlyph)
               mCommon.pCurve = &mCommon.pMetaboliteReferenceGlyph->getCurve();
           }
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::MetaboliteReferenceGlyphElement::mLineNumber private
Definition at line 3420 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp