COPASI API: CPlotSpecification Class Reference
CPlotSpecification Class Reference
#include <CPlotSpecification.h>
Public Member Functions
virtual void cleanup ()
CPlotSpecification (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const CPlotItem::Type &type=plot2d)
CPlotSpecification (const CPlotSpecification &src, const CCopasiContainer *pParent=NULL)
bool createDefaultPlot (const CModel *model)
CPlotItem * createItem (const std::string &name, CPlotItem::Type type)
const CCopasiVector< CPlotItem > & getItems () const
CCopasiVector< CPlotItem > & getItems ()
const bool & isActive () const
bool isLogX () const
bool isLogY () const
void setActive (const bool &active)
void setLogX (bool l)
void setLogY (bool l)
virtual ~CPlotSpecification ()
Public Member Functions inherited from CPlotItem
void addChannel (const CPlotDataChannelSpec &channel)
void cleanup ()
CPlotItem (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=curve2d)
CPlotItem (const CPlotItem &src, const CCopasiContainer *pParent=NULL)
const COutputInterface::Activity & getActivity () const
std::vector
< CPlotDataChannelSpec > & getChannels ()
const std::vector
< CPlotDataChannelSpec > & getChannels () const
size_t getNumChannels () const
const std::string & getTitle () const
const CPlotItem::Type & getType () const
void setActivity (const COutputInterface::Activity &activity)
void setTitle (const std::string &title)
void setType (CPlotItem::Type type)
virtual ~CPlotItem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initObjects ()
Private Attributes
CCopasiVector< CPlotItem > items
bool mActive
Additional Inherited Members
Public Types inherited from CPlotItem
enum Type {
unset = 0, curve2d, histoItem1d, bandedGraph,
surface, plot2d, simWiz
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CPlotItem
static const std::string RecordingActivityName []
static const std::string TypeName []
static const char * XMLRecordingActivity []
static const char * XMLType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 27 of file CPlotSpecification.h.
Constructor & Destructor Documentation
CPlotSpecification::CPlotSpecification (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL, const CPlotItem::Type & type = plot2d)
Definition at line 28 of file CPlotSpecification.cpp.
References initObjects().
                                                                            :
     CPlotItem(name, pParent, type),
     items("Curves", this),
     mActive(true)
 {initObjects();}
CPlotSpecification::CPlotSpecification (const CPlotSpecification & src, const CCopasiContainer * pParent = NULL)
Definition at line 36 of file CPlotSpecification.cpp.
References initObjects().
                                                                         :
     CPlotItem(src, pParent),
     items(src.getItems(), this),
     mActive(src.mActive)
 {initObjects();}
CPlotSpecification::~CPlotSpecification () virtual
Destructor
Definition at line 43 of file CPlotSpecification.cpp.
 {}
Member Function Documentation
void CPlotSpecification::cleanup () virtual
Definition at line 45 of file CPlotSpecification.cpp.
References CPlotItem::cleanup(), CCopasiVector< T >::cleanup(), and items.
Referenced by CQPlotSubwidget::saveToPlotSpec().
 {
   items.cleanup();
   this->CPlotItem::cleanup();
 }
bool CPlotSpecification::createDefaultPlot (const CModel * model)
Definition at line 99 of file CPlotSpecification.cpp.
References CPlotItem::addChannel(), createItem(), CPlotItem::curve2d, CCopasiObject::getCN(), CModel::getMetabolites(), CCopasiObject::getObjectDisplayName(), CModelEntity::getValueReference(), mActive, and CCopasiVector< T >::size().
 {
   mActive = true;
   //TODO cleanup before?
   //title = "Default Data Plot 2D";
   CPlotItem * plItem;
   std::string itemTitle;
   CPlotDataChannelSpec name2;
   const CCopasiObject * tmp;
   CPlotDataChannelSpec name1 = model->getValueReference()->getCN();
   size_t i, imax = model->getMetabolites().size();
   for (i = 0; i < imax; ++i)
     {
       tmp = model->getMetabolites()[i]->getConcentrationReference();
       name2 = tmp->getCN();
       itemTitle = tmp->getObjectDisplayName();
       plItem = this->createItem(itemTitle, CPlotItem::curve2d);
       plItem->addChannel(name1);
       plItem->addChannel(name2);
     }
   return true; //TODO: really check;
 }
CPlotItem * CPlotSpecification::createItem (const std::string & name, CPlotItem::Type type)
Definition at line 86 of file CPlotSpecification.cpp.
References CCopasiVector< T >::add(), CPlotItem::CPlotItem(), and items.
Referenced by COutputAssistant::createDefaultOutput(), createDefaultPlot(), COutputAssistant::createPlot(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), and CCopasiXMLParser::PlotItemElement::start().
 {
   CPlotItem * itm = new CPlotItem(name, NULL, type);
   if (!items.add(itm, true))
     {
       delete itm;
       return NULL;
     }
   return itm;
 }
const CCopasiVector<CPlotItem>& CPlotSpecification::getItems () const inline
Definition at line 54 of file CPlotSpecification.h.
References items.
Referenced by CopasiPlot::compile(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CQPlotDM::data(), CopasiPlot::initFromSpec(), CQPlotSubwidget::loadFromPlotSpec(), CCopasiXML::savePlotList(), and CQPlotSubwidget::saveToPlotSpec().
 {return items;};
CCopasiVector<CPlotItem>& CPlotSpecification::getItems () inline
Definition at line 56 of file CPlotSpecification.h.
References items.
 {return items;};
void CPlotSpecification::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 51 of file CPlotSpecification.cpp.
Referenced by CPlotSpecification().
 {
   //  CCopasiContainer::addObjectReference("Active", mActive, CCopasiObject::ValueBool);
 }
const bool & CPlotSpecification::isActive () const
Definition at line 61 of file CPlotSpecification.cpp.
References mActive.
Referenced by COutputHandlerPlot::compile(), CQPlotDM::data(), CQPlotSubwidget::loadFromPlotSpec(), CCopasiXML::savePlotList(), and CQPlotDM::setData().
 {return mActive;}
bool CPlotSpecification::isLogX () const
Definition at line 64 of file CPlotSpecification.cpp.
References CCopasiParameter::getValue(), and CCopasiParameter::Value::pBOOL.
Referenced by CSEDMLExporter::createDataGenerators(), PlotWindow::initFromSpec(), CopasiPlot::initFromSpec(), CQPlotSubwidget::loadFromPlotSpec(), and PlotWindow::PlotWindow().
 {
   return *getValue("log X").pBOOL;
 }
bool CPlotSpecification::isLogY () const
Definition at line 69 of file CPlotSpecification.cpp.
References CCopasiParameter::getValue(), and CCopasiParameter::Value::pBOOL.
Referenced by CSEDMLExporter::createDataGenerators(), PlotWindow::initFromSpec(), CopasiPlot::initFromSpec(), CQPlotSubwidget::loadFromPlotSpec(), and PlotWindow::PlotWindow().
 {
   return *getValue("log Y").pBOOL;
 }
void CPlotSpecification::setActive (const bool & active)
Definition at line 58 of file CPlotSpecification.cpp.
References mActive.
Referenced by CQPlotSubwidget::saveToPlotSpec(), CQPlotDM::setData(), CQPlotsWidget::slotBtnActivateAllClicked(), CQPlotsWidget::slotBtnDeactivateAllClicked(), and CCopasiXMLParser::PlotSpecificationElement::start().
 {mActive = active;}
void CPlotSpecification::setLogX (bool l)
Definition at line 74 of file CPlotSpecification.cpp.
References CCopasiParameterGroup::setValue().
Referenced by COutputAssistant::createPlot(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), and CQPlotSubwidget::saveToPlotSpec().
 {
   setValue("log X", l);
 }
void CPlotSpecification::setLogY (bool l)
Definition at line 79 of file CPlotSpecification.cpp.
References CCopasiParameterGroup::setValue().
Referenced by COutputAssistant::createDefaultOutput(), COutputAssistant::createPlot(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), and CQPlotSubwidget::saveToPlotSpec().
 {
   setValue("log Y", l);
 }
Member Data Documentation
CCopasiVector<CPlotItem> CPlotSpecification::items private
Definition at line 31 of file CPlotSpecification.h.
Referenced by cleanup(), createItem(), and getItems().
bool CPlotSpecification::mActive private
Definition at line 32 of file CPlotSpecification.h.
Referenced by createDefaultPlot(), isActive(), and setActive().
The documentation for this class was generated from the following files:
CPlotSpecification.h
CPlotSpecification.cpp