COPASI API: CQLayoutScene.cpp File Reference
CQLayoutScene.cpp File Reference
#include <QtCore/QCoreApplication>
#include <QtGui/QGraphicsScene>
#include <QtGui/QGraphicsItem>
#include <QtGui/QPainter>
#include <QtGui/QPrinter>
#include <QtGui/QImage>
#include <QtGui/QGraphicsEffect>
#include "copasi.h"
#include "qlayout/CQLayoutScene.h"
#include "qlayout/CQCopasiEffect.h"
#include "qlayout/CQLabelGraphicsItem.h"
#include "qlayout/CQStyledGraphicsItem.h"
#include "qlayout/CQConnectionGraphicsItem.h"
#include "qlayout/CQRenderConverter.h"
#include "layout/CLayout.h"
#include "layout/CLGlyphs.h"
#include "layout/CLText.h"
#include "layout/CLReactionGlyph.h"
#include "layout/CLRenderResolver.h"
#include "layout/CLGlobalRenderInformation.h"
#include "layout/CListOfLayouts.h"
#include "layout/CLLocalRenderInformation.h"
#include "layout/CLDefaultStyles.h"
#include "layout/CCopasiSpringLayout.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "copasi/report/CCopasiRootContainer.h"
#include "copasi/report/CKeyFactory.h"
#include <model/CCompartment.h>
#include <model/CMetab.h>
Functions
CLGraphicalObject * getMetabGlyphForKey (const CLayout *layout, const CMetab *metab)
CLGraphicalObject * getTextForItem (const CLayout *layout, const CLGraphicalObject *obj)
void moveObject (CLGraphicalObject *obj, const CLPoint &delta, CLayout *layout)
Function Documentation
CLGraphicalObject* getMetabGlyphForKey (const CLayout * layout, const CMetab * metab)
Definition at line 285 of file CQLayoutScene.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModelEntity::getKey(), and CLayout::getListOfMetaboliteGlyphs().
Referenced by moveObject().
 {
   const CCopasiVector<CLMetabGlyph> & metabs = layout->getListOfMetaboliteGlyphs();
   CCopasiVector<CLMetabGlyph>::const_iterator it = metabs.begin();
   while (it != metabs.end())
     {
       if ((*it)->getModelObjectKey() == metab->getKey())
         return *it;
       ++it;
     }
   return NULL;
 }
CLGraphicalObject* getTextForItem (const CLayout * layout, const CLGraphicalObject * obj)
Definition at line 266 of file CQLayoutScene.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CLGraphicalObject::getKey(), and CLayout::getListOfTextGlyphs().
Referenced by moveObject().
 {
   const CCopasiVector<CLTextGlyph> & texts = layout->getListOfTextGlyphs();
   CCopasiVector<CLTextGlyph>::const_iterator it = texts.begin();
   while (it != texts.end())
     {
       if ((*it)->getGraphicalObjectKey() == obj->getKey())
         return *it;
       ++it;
     }
   return NULL;
 }
void moveObject (CLGraphicalObject * obj, const CLPoint & delta, CLayout * layout)
Definition at line 301 of file CQLayoutScene.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), getMetabGlyphForKey(), CCompartment::getMetabolites(), CLGraphicalObject::getModelObject(), getTextForItem(), and CLGraphicalObject::moveBy().
Referenced by CQLayoutScene::updatePosition().
 {
   if (obj == NULL) return;
   // move object
   obj->moveBy(delta);
   // move its label
   CLGraphicalObject* text = getTextForItem(layout, obj);
   if (text != NULL)
     text->moveBy(delta);
   // move species within compartments as well
   CLCompartmentGlyph* lcomp = dynamic_cast<CLCompartmentGlyph*>(obj);
   if (lcomp == NULL)
     return;
   CCompartment*  comp = dynamic_cast<CCompartment*>(lcomp ->getModelObject());
   if (comp == NULL)
     return;
   CCopasiVectorNS < CMetab > & metabs = comp->getMetabolites();
   CCopasiVectorNS < CMetab >::const_iterator it = metabs.begin();
   while (it != metabs.end())
     {
       moveObject(getMetabGlyphForKey(layout, (*it)), delta, layout);
       ++it;
     }
 }