COPASI API: CExperiment.cpp File Reference
CExperiment.cpp File Reference
#include <fstream>
#include <limits>
#include <cmath>
#include "copasi.h"
#include "CExperiment.h"
#include "CExperimentObjectMap.h"
#include "CFitTask.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "model/CModel.h"
#include "report/CCopasiObjectReference.h"
#include "report/CKeyFactory.h"
#include "utilities/CTableCell.h"
#include "utilities/CSort.h"
#include "utilities/CDirEntry.h"
#include "utilities/utility.h"
#include "commandline/CLocaleString.h"
Macros
#define InvalidIndex std::numeric_limits< unsigned C_INT32 >::max()
Functions
bool operator== (const CExperiment &lhs, const CExperiment &rhs)
std::istream & skipLine (std::istream &in)
Macro Definition Documentation
#define InvalidIndex std::numeric_limits< unsigned C_INT32 >::max()
Definition at line 38 of file CExperiment.cpp.
Referenced by CExperiment::initializeParameter(), and CExperiment::readColumnNames().
Function Documentation
bool operator== (const CExperiment & lhs, const CExperiment & rhs)
Comparison operator
Parameters
const CExperiment & lhs
const CExperiment & rhs
Returns
bool equal
Definition at line 1394 of file CExperiment.cpp.
References CCopasiParameterGroup::getValue(), and CCopasiParameter::Value::pKEY.
 {
   std::string Key = *lhs.getValue("Key").pKEY;
   const_cast<CExperiment *>(&lhs)->setValue("Key", *rhs.getValue("Key").pKEY);
   bool Result =
     (*static_cast<const CCopasiParameterGroup *>(&lhs) ==
      *static_cast<const CCopasiParameterGroup *>(&rhs));
   const_cast<CExperiment *>(&lhs)->setValue("Key", Key);
   return Result;
 }
std::istream & skipLine (std::istream & in)
Definition at line 1784 of file CExperiment.cpp.
Referenced by CExperiment::guessColumnNumber(), CExperiment::read(), and CExperiment::readColumnNames().
 {
   char c;
   for (in.get(c); c != 0x0a && c != 0x0d; in.get(c))
     {
       if (in.fail() || in.eof()) break;
     }
   // Eat additional line break characters appearing on DOS and Mac text format;
   if ((c == 0x0d && in.peek() == 0x0a) ||  // DOS
       (c == 0x0a && in.peek() == 0x0d))   // Mac
     in.ignore(1);
   return in;
 }