COPASI API: CCopasiXMLParser::ModelValueElement Class Reference
CCopasiXMLParser::ModelValueElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ModelValueElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ModelValueElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
ModelValue = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
Expression, InitialExpression, MathML
}
Private Attributes
std::string mKey
MathMLElement * mpMathMLElement
CModelValue * mpMV
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1444 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ModelValueElement::Element private
Enum of invoked parsers
Enumerator
ModelValue
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
Expression
InitialExpression
MathML
Definition at line 1452 of file CCopasiXMLParser.h.
     {
       ModelValue = 0,
       MiriamAnnotation,
       Comment,
       ListOfUnsupportedAnnotations,
       Expression,
       InitialExpression,
       MathML
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ModelValueElement::ModelValueElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 2842 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpMV(NULL),
   mpMathMLElement(NULL),
   mKey("")
 {}
CCopasiXMLParser::ModelValueElement::~ModelValueElement () virtual
Destructor
Definition at line 2850 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpMathMLElement);
 }
Member Function Documentation
void CCopasiXMLParser::ModelValueElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 2969 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case ModelValue:
         if (strcmp(pszName, "ModelValue"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ModelValue", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         mpMV->setMiriamAnnotation(mCommon.CharacterData, mpMV->getKey(), mKey);
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         mpMV->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         mpMV->getUnsupportedAnnotations() = mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case Expression:
         if (strcmp(pszName, "Expression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Expression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpMV->setExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case InitialExpression:
         if (strcmp(pszName, "InitialExpression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialExpression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpMV->setInitialExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case MathML:                                                   // Old file format support
         if (strcmp(pszName, "MathML"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MathML", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpMV->setExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case UNKNOWN_ELEMENT:
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   mCurrentElement = ModelValue;
   return;
 }
void CCopasiXMLParser::ModelValueElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 2855 of file CCopasiXMLParser.cpp.
References CCopasiVectorN< CType >::add(), CCopasiMessage::EXCEPTION, CModelEntity::FIXED, CModel::getModelValues(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, toEnum(), UNKNOWN_ELEMENT, and CModelEntity::XMLStatus.
 {
   const char * Name;
   const char * simulationType;
   CModelEntity::Status SimulationType;
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case ModelValue:
             if (strcmp(pszName, "ModelValue"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "ModelValue", mParser.getCurrentLineNumber());
             mKey = mParser.getAttributeValue("key", papszAttrs);
             Name = mParser.getAttributeValue("name", papszAttrs);
             simulationType = mParser.getAttributeValue("simulationType", papszAttrs, false);
             // We need to handle old files which used the attribute status.
             if (!simulationType)
               {
                 simulationType = mParser.getAttributeValue("status", papszAttrs, false);
                 if (!simulationType) // status and simulationType are both missing
                   simulationType = mParser.getAttributeValue("simulationType", papszAttrs);
               }
             SimulationType = toEnum(simulationType, CModelEntity::XMLStatus, CModelEntity::FIXED);
             mpMV = new CModelValue();
             addFix(mKey, mpMV);
             mpMV->setObjectName(Name);
             mpMV->setStatus(SimulationType);
             mCommon.pModel->getModelValues().add(mpMV, true);
             mLastKnownElement = mCurrentElement;
             return;
           case MiriamAnnotation:
             if (!strcmp(pszName, "MiriamAnnotation"))
               mpCurrentHandler = &mParser.mMiriamAnnotationElement;
             break;
           case Comment:
             if (!strcmp(pszName, "Comment"))
               mpCurrentHandler = &mParser.mCommentElement;
             break;
           case ListOfUnsupportedAnnotations:
             if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
               mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             break;
           case Expression:
             if (!strcmp(pszName, "Expression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           case InitialExpression:
             if (!strcmp(pszName, "InitialExpression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           case MathML:                                                   // Old file format support
             if (!strcmp(pszName, "MathML"))
               {
                 /* If we do not have a MathML element handler we create one. */
                 if (!mpMathMLElement)
                   mpMathMLElement = new MathMLElement(mParser, mCommon);
                 mpCurrentHandler = mpMathMLElement;
               }
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::ModelValueElement::mKey private
The key in the CopasiML file
Definition at line 1469 of file CCopasiXMLParser.h.
MathMLElement* CCopasiXMLParser::ModelValueElement::mpMathMLElement private
Definition at line 1464 of file CCopasiXMLParser.h.
CModelValue* CCopasiXMLParser::ModelValueElement::mpMV private
Definition at line 1463 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp