COPASI API: CQExperimentDataValidator Class Reference
CQExperimentDataValidator Class Reference
Public Types
enum Type { Name = 0, FirstRow, LastRow, HeaderRow }
Public Member Functions
CQExperimentDataValidator (QLineEdit *parent, const char *name, CQExperimentData *pContext, const Type &type)
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidatorNotEmpty
CQValidatorNotEmpty (QLineEdit *parent, const char *name=0)
Public Member Functions inherited from CQValidator< QLineEdit >
CQValidator (QLineEdit *parent, QString(QLineEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Private Attributes
CQExperimentData * mpContext
QIntValidator * mpIntValidator
Type mType
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QLineEdit >
State setColor (const State &state) const
Protected Attributes inherited from CQValidator< QLineEdit >
QString mLastAccepted
QLineEdit * mpContainer
QString(QLineEdit::* mRetrieve)(void) const
Detailed Description
Definition at line 104 of file CQExperimentData.cpp.
Member Enumeration Documentation
enum CQExperimentDataValidator::Type
Enumerator
Name
FirstRow
LastRow
HeaderRow
Definition at line 107 of file CQExperimentData.cpp.
   {
     Name = 0,
     FirstRow,
     LastRow,
     HeaderRow
   };
Constructor & Destructor Documentation
CQExperimentDataValidator::CQExperimentDataValidator (QLineEdit * parent, const char * name, CQExperimentData * pContext, const Type & type) inline
Definition at line 117 of file CQExperimentData.cpp.
                                               :
     CQValidatorNotEmpty(parent, name),
     mpIntValidator(new QIntValidator(1, std::numeric_limits< int >::max(), parent)),
     mpContext(pContext),
     mType(type)
   {}
Member Function Documentation
virtual State CQExperimentDataValidator::validate (QString & input, int & pos) const inline virtual
Reimplemented from CQValidatorNotEmpty.
Definition at line 127 of file CQExperimentData.cpp.
References C_INT32, FirstRow, CExperimentFileInfo::getFirstUnusedSection(), CExperiment::getLastRow(), CExperimentFileInfo::getNextUnusedSection(), CCopasiParameterGroup::getParameter(), HeaderRow, LastRow, CQValidator< QLineEdit >::mLastAccepted, mpContext, CQExperimentData::mpExperiment, CQExperimentData::mpExperimentSetCopy, CQExperimentData::mpFileInfo, mpIntValidator, CQExperimentData::mpValidatorLast, CQExperimentData::mShown, mType, Name, CQValidator< Type >::revalidate(), CQValidator< QLineEdit >::setColor(), CExperiment::setFirstRow(), CExperiment::setHeaderRow(), CExperiment::setLastRow(), CExperimentFileInfo::sync(), CQExperimentData::syncExperiments(), TO_UTF8, CQValidatorNotEmpty::validate(), CExperimentFileInfo::validateFirst(), CExperimentFileInfo::validateHeader(), and CExperimentFileInfo::validateLast().
Referenced by CQExperimentData::saveExperiment().
   {
     if (mpContext->mShown == -1) return Acceptable;
     if (mType == Name)
       {
         if (input == "All")
           {
             setColor(Invalid);
             return Intermediate;
           }
         if (mLastAccepted != input &&
             mpContext->mpExperimentSetCopy->getParameter(TO_UTF8(input)))
           {
             setColor(Invalid);
             return Intermediate;
           }
       }
     else
       {
         if (mpIntValidator->validate(input, pos) != Acceptable)
           {
             setColor(Invalid);
             return Intermediate;
           }
         size_t First, Last;
         switch (mType)
           {
             case FirstRow:
               if (!mpContext->mpFileInfo->validateFirst(mpContext->mShown, input.toULong()))
                 {
                   size_t NewFirst = input.toULong();
                   mpContext->mpFileInfo->getFirstUnusedSection(First, Last);
                   while (NewFirst > Last)
                     mpContext->mpFileInfo->getNextUnusedSection(First, Last);
                   if (First <= NewFirst && NewFirst <= Last)
                     {
                       if (First > mpContext->mpExperiment->getLastRow())
{
                           mpContext->mpExperiment->setLastRow((unsigned C_INT32) Last);
                           mpContext->mpExperiment->setFirstRow((unsigned C_INT32) First);
                         }
                       else
{
                           mpContext->mpExperiment->setFirstRow((unsigned C_INT32) First);
                           mpContext->mpExperiment->setLastRow((unsigned C_INT32) Last);
                         }
                       mpContext->syncExperiments();
                       mpContext->mpEditFirst->setText(QString::number(First));
                       mpContext->mpEditLast->setText(QString::number(Last));
                       mpContext->mpValidatorLast->revalidate();
                       return validate(input, pos);
                     }
                   setColor(Invalid);
                   return Intermediate;
                 }
               mpContext->mpExperiment->setFirstRow(input.toULong());
               mpContext->mpFileInfo->sync();
               mpContext->mpBtnExperimentAdd->setEnabled(mpContext->mpFileInfo->getFirstUnusedSection(First, Last));
               break;
             case LastRow:
               if (!mpContext->mpFileInfo->validateLast(mpContext->mShown, input.toULong()))
                 {
                   setColor(Invalid);
                   return Intermediate;
                 }
               mpContext->mpExperiment->setLastRow(input.toULong());
               mpContext->mpFileInfo->sync();
               mpContext->mpBtnExperimentAdd->setEnabled(mpContext->mpFileInfo->getFirstUnusedSection(First, Last));
               break;
             case HeaderRow:
               if (!mpContext->mpFileInfo->validateHeader(mpContext->mShown, input.toULong()))
                 {
                   setColor(Invalid);
                   return Intermediate;
                 }
               mpContext->mpExperiment->setHeaderRow(input.toULong());
               break;
             default:
               break;
           }
       }
     return CQValidatorNotEmpty::validate(input, pos);
   }
Member Data Documentation
CQExperimentData* CQExperimentDataValidator::mpContext private
Definition at line 242 of file CQExperimentData.cpp.
Referenced by validate().
QIntValidator* CQExperimentDataValidator::mpIntValidator private
Definition at line 240 of file CQExperimentData.cpp.
Referenced by validate().
Type CQExperimentDataValidator::mType private
Definition at line 244 of file CQExperimentData.cpp.
Referenced by validate().
The documentation for this class was generated from the following file:
CQExperimentData.cpp