COPASI API: CLRenderCurve Class Reference
CLRenderCurve Class Reference
#include <CLRenderCurve.h>
Public Member Functions
void addCurveElement (const CLRenderPoint *cs)
CLRenderCurve (CCopasiContainer *pParent=NULL)
CLRenderCurve (const CLRenderCurve &source, CCopasiContainer *pParent=NULL)
CLRenderCurve (const RenderCurve &source, CCopasiContainer *pParent=NULL)
CLRenderCubicBezier * createCubicBezier ()
CLRenderPoint * createPoint ()
const CLRenderPoint * getCurveElement (size_t index) const
CLRenderPoint * getCurveElement (size_t index)
const std::string & getEndHead () const
const std::string & getKey () const
const std::vector
< CLRenderPoint * > * getListOfCurveElements () const
std::vector< CLRenderPoint * > * getListOfCurveElements ()
size_t getNumElements () const
const std::string & getStartHead () const
bool isSetEndHead () const
bool isSetStartHead () const
void removeCurveElement (size_t i)
void setEndHead (const std::string &endHead)
void setStartHead (const std::string &startHead)
RenderCurve * toSBML (unsigned int level, unsigned int version) const
~CLRenderCurve ()
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
std::string mEndHead
std::string mKey
std::vector< CLRenderPoint * > mListOfElements
std::string mStartHead
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Private Member Functions
CLRenderCurve & operator= (const CLRenderCurve &source)
Friends
class Group
Additional Inherited Members
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 27 of file CLRenderCurve.h.
Constructor & Destructor Documentation
CLRenderCurve::CLRenderCurve (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 22 of file CLRenderCurve.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                      :
   CLGraphicalPrimitive1D(),
   CCopasiObject("RenderCurve", pParent),
   mStartHead(""),
   mEndHead(""),
   mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RenderCurve", this);
 }
CLRenderCurve::CLRenderCurve (const CLRenderCurve & source, CCopasiContainer * pParent = NULL)
Copy Constructor
Copy constructor
Definition at line 35 of file CLRenderCurve.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and mListOfElements.
                                                                                   :
   CLGraphicalPrimitive1D(source),
   CCopasiObject(source, pParent),
   mStartHead(source.mStartHead),
   mEndHead(source.mEndHead),
   mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RenderCurve", this);
   size_t i, iMax = source.mListOfElements.size();
   for (i = 0; i < iMax; ++i)
     {
       if (dynamic_cast<const CLRenderCubicBezier*>(source.mListOfElements[i]))
         {
           this->mListOfElements.push_back(new CLRenderCubicBezier(*static_cast<const CLRenderCubicBezier*>(source.mListOfElements[i])));
         }
       else
         {
           this->mListOfElements.push_back(new CLRenderPoint(*source.mListOfElements[i]));
         }
     }
 }
CLRenderCurve::CLRenderCurve (const RenderCurve & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 61 of file CLRenderCurve.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and mListOfElements.
                                                                                 :
   CLGraphicalPrimitive1D(source),
   CCopasiObject("RenderCurve", pParent),
   mStartHead(source.getStartHead()),
   mEndHead(source.getEndHead()),
   mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RenderCurve", this);
   size_t i, iMax = source.getNumElements();
   for (i = 0; i < iMax; ++i)
     {
       CLRenderPoint* pElement = NULL;
       if (dynamic_cast<const RenderCubicBezier*>(source.getElement((unsigned int) i)))
         {
           pElement = new CLRenderCubicBezier(*static_cast<const RenderCubicBezier*>(source.getElement((unsigned int) i)));
         }
       else
         {
           pElement = new CLRenderPoint(*source.getElement((unsigned int) i));
         }
       this->mListOfElements.push_back(pElement);
     }
 }
CLRenderCurve::~CLRenderCurve ()
Destructor
Definition at line 91 of file CLRenderCurve.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, mListOfElements, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(this->mKey);
   size_t i, iMax = this->mListOfElements.size();
   for (i = 0; i < iMax; ++i)
     {
       delete this->mListOfElements[i];
     }
 }
Member Function Documentation
void CLRenderCurve::addCurveElement (const CLRenderPoint * pCS)
Adds a copy of the given curve segment to the end of the list of curve segments.
Definition at line 184 of file CLRenderCurve.cpp.
References mListOfElements.
 {
   if (dynamic_cast<const CLRenderCubicBezier*>(pCS))
     {
       this->mListOfElements.push_back(new CLRenderCubicBezier(*static_cast<const CLRenderCubicBezier*>(pCS)));
     }
   else
     {
       this->mListOfElements.push_back(new CLRenderPoint(*pCS));
     }
 }
CLRenderCubicBezier * CLRenderCurve::createCubicBezier ()
Creates a new bezier element. The element is added to the curve.
Creates a new cubic bezier curve segment.
Definition at line 145 of file CLRenderCurve.cpp.
References mListOfElements.
 {
   CLRenderCubicBezier* pCS = new CLRenderCubicBezier();
   this->mListOfElements.push_back(pCS);
   return pCS;
 }
CLRenderPoint * CLRenderCurve::createPoint ()
Creates a new point element. The element is added to the curve.
Creates a new curve segment.
Definition at line 155 of file CLRenderCurve.cpp.
References mListOfElements.
 {
   CLRenderPoint* pCS = new CLRenderPoint();
   this->mListOfElements.push_back(pCS);
   return pCS;
 }
const CLRenderPoint * CLRenderCurve::getCurveElement (size_t index) const
Returns a const pointer to the curve segment with the given index or NULL if the id is invalid.
Definition at line 166 of file CLRenderCurve.cpp.
References mListOfElements.
Referenced by CLLayoutRenderer::draw_curve().
 {
   return (index < this->mListOfElements.size()) ? (this->mListOfElements[index]) : NULL;
 }
CLRenderPoint * CLRenderCurve::getCurveElement (size_t index)
Returns a pointer to the curve segment with the given index or NULL if the id is invalid.
Definition at line 175 of file CLRenderCurve.cpp.
References mListOfElements.
 {
   return (index < this->mListOfElements.size()) ? (this->mListOfElements[index]) : NULL;
 }
const std::string & CLRenderCurve::getEndHead () const
Returns the id of the end head.
Definition at line 129 of file CLRenderCurve.cpp.
References mEndHead.
Referenced by fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mEndHead;
 }
const std::string & CLRenderCurve::getKey () const virtual
Returns the key string of the object.
Returns the key of the color definition.
Reimplemented from CCopasiObject.
Definition at line 245 of file CLRenderCurve.cpp.
References mKey.
 {
   return this->mKey;
 }
const std::vector< CLRenderPoint * > * CLRenderCurve::getListOfCurveElements () const
Returns a const pointer to the list of curve segments.
Definition at line 213 of file CLRenderCurve.cpp.
References mListOfElements.
Referenced by getPath(), and CCopasiXMLParser::RenderCurveElement::start().
 {
   return &(this->mListOfElements);
 }
std::vector< CLRenderPoint * > * CLRenderCurve::getListOfCurveElements ()
Returns a pointer to the list of curve segments.
Definition at line 221 of file CLRenderCurve.cpp.
References mListOfElements.
 {
   return &(this->mListOfElements);
 }
size_t CLRenderCurve::getNumElements () const
Returns the number of curve segments.
Definition at line 137 of file CLRenderCurve.cpp.
References mListOfElements.
Referenced by CLLayoutRenderer::draw_curve().
 {
   return this->mListOfElements.size();
 }
const std::string & CLRenderCurve::getStartHead () const
Returns the id of the start head.
Definition at line 121 of file CLRenderCurve.cpp.
References mStartHead.
Referenced by fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mStartHead;
 }
bool CLRenderCurve::isSetEndHead () const
Returns true if the start head is set or false otherwise.
Definition at line 237 of file CLRenderCurve.cpp.
References mEndHead.
Referenced by fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return (!this->mEndHead.empty() && this->mEndHead != "none");
 }
bool CLRenderCurve::isSetStartHead () const
Returns true if the start head is set or false otherwise.
Definition at line 229 of file CLRenderCurve.cpp.
References mStartHead.
Referenced by fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return (!this->mStartHead.empty() && this->mStartHead != "none");
 }
CLRenderCurve& CLRenderCurve::operator= (const CLRenderCurve & source) private
void CLRenderCurve::removeCurveElement (size_t i)
Removes the curve segment with the given index.
Definition at line 199 of file CLRenderCurve.cpp.
References mListOfElements.
 {
   if (i < this->mListOfElements.size())
     {
       std::vector<CLRenderPoint*>::iterator it = this->mListOfElements.begin();
       it += i;
       delete *it;
       this->mListOfElements.erase(it);
     }
 }
void CLRenderCurve::setEndHead (const std::string & endHead)
Sets the id of the end head.
Definition at line 113 of file CLRenderCurve.cpp.
References mEndHead.
Referenced by CCopasiXMLParser::RenderCurveElement::start().
 {
   this->mEndHead = endHead;
 }
void CLRenderCurve::setStartHead (const std::string & startHead)
Sets the id of the start head.
Definition at line 105 of file CLRenderCurve.cpp.
References mStartHead.
Referenced by CCopasiXMLParser::RenderCurveElement::start().
 {
   this->mStartHead = startHead;
 }
RenderCurve * CLRenderCurve::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
Definition at line 253 of file CLRenderCurve.cpp.
References CLGraphicalPrimitive1D::addSBMLAttributes(), mEndHead, mListOfElements, and mStartHead.
 {
   RenderCurve* pCurve = new RenderCurve(level, version);
   this->addSBMLAttributes(pCurve);
   pCurve->setStartHead(this->mStartHead);
   pCurve->setEndHead(this->mEndHead);
   size_t i, iMax = this->mListOfElements.size();
   for (i = 0; i < iMax; ++i)
     {
       const RenderPoint* pP = this->mListOfElements[i]->toSBML(level, version);
       pCurve->addElement(pP);
       delete pP;
     }
   return pCurve;
 }
Friends And Related Function Documentation
friend class Group friend
Definition at line 155 of file CLRenderCurve.h.
Member Data Documentation
std::string CLRenderCurve::mEndHead protected
Definition at line 35 of file CLRenderCurve.h.
Referenced by getEndHead(), isSetEndHead(), setEndHead(), and toSBML().
std::string CLRenderCurve::mKey protected
key for the object.
Definition at line 41 of file CLRenderCurve.h.
Referenced by CLRenderCurve(), getKey(), and ~CLRenderCurve().
std::vector<CLRenderPoint*> CLRenderCurve::mListOfElements protected
Definition at line 36 of file CLRenderCurve.h.
Referenced by addCurveElement(), CLRenderCurve(), createCubicBezier(), createPoint(), getCurveElement(), getListOfCurveElements(), getNumElements(), removeCurveElement(), toSBML(), and ~CLRenderCurve().
std::string CLRenderCurve::mStartHead protected
Definition at line 34 of file CLRenderCurve.h.
Referenced by getStartHead(), isSetStartHead(), setStartHead(), and toSBML().
The documentation for this class was generated from the following files:
CLRenderCurve.h
CLRenderCurve.cpp