COPASI API: MyLineEdit Class Reference
MyLineEdit Class Reference
#include <MyLineEdit.h>
Public Slots
virtual void setText (const QString &text)
void slotForceUpdate ()
Signals
void edited ()
Public Member Functions
bool isValid ()
MyLineEdit (QWidget *parent=0, const char *name=0)
MyLineEdit (const QString &contents, QWidget *parent, const char *name=0)
Protected Slots
void slotLostFocus ()
void slotReturnPressed ()
void slotTextChanged (const QString &text)
Protected Member Functions
void process ()
void setupWidget ()
virtual void updateColor ()
Protected Attributes
QColor mErrorColor
QColor mNewColor
QColor mOldColor
Detailed Description
Definition at line 20 of file MyLineEdit.h.
Constructor & Destructor Documentation
MyLineEdit::MyLineEdit (QWidget * parent = 0, const char * name = 0)
Definition at line 18 of file MyLineEdit.cpp.
References setupWidget().
   : QLineEdit(parent)
 {
   setObjectName(name);
   setupWidget();
 }
MyLineEdit::MyLineEdit (const QString & contents, QWidget * parent, const char * name = 0)
Definition at line 25 of file MyLineEdit.cpp.
References setupWidget().
   : QLineEdit(contents, parent)
 {
   setObjectName(name);
   setupWidget();
 }
Member Function Documentation
void MyLineEdit::edited () signal
Referenced by process().
bool MyLineEdit::isValid ()
Definition at line 103 of file MyLineEdit.cpp.
References mErrorColor.
 {return (palette().color(backgroundRole()) != mErrorColor);}
void MyLineEdit::process () protected
Definition at line 49 of file MyLineEdit.cpp.
References edited(), and updateColor().
Referenced by slotForceUpdate(), slotLostFocus(), and slotReturnPressed().
 {
   if (isModified())
     {
       setModified(false);
       updateColor();
       emit edited();
     }
 }
void MyLineEdit::setText (const QString & text) virtual slot
Definition at line 97 of file MyLineEdit.cpp.
References updateColor().
 {
   QLineEdit::setText(text);
   updateColor();
 }
void MyLineEdit::setupWidget () protected
Definition at line 32 of file MyLineEdit.cpp.
References mErrorColor, mNewColor, mOldColor, slotLostFocus(), slotReturnPressed(), and slotTextChanged().
Referenced by MyLineEdit().
 {
   connect(this, SIGNAL(editingFinished()), this, SLOT(slotLostFocus()));
   connect(this, SIGNAL(returnPressed()), this, SLOT(slotReturnPressed()));
   connect(this, SIGNAL(textChanged(const QString &)), this, SLOT(slotTextChanged(const QString &)));
   mOldColor = palette().color(backgroundRole());
   int h, s, v;
   mOldColor.getHsv(&h, &s, &v);
   if (s < 20) s = 20;
   mNewColor.setHsv(240, s, v);
   mErrorColor.setHsv(0, s, v);
 }
void MyLineEdit::slotForceUpdate () slot
Definition at line 65 of file MyLineEdit.cpp.
References process().
 {process();}
void MyLineEdit::slotLostFocus () protected slot
Definition at line 59 of file MyLineEdit.cpp.
References process().
Referenced by setupWidget().
 {process();}
void MyLineEdit::slotReturnPressed () protected slot
Definition at line 62 of file MyLineEdit.cpp.
References process().
Referenced by setupWidget().
 {process();}
void MyLineEdit::slotTextChanged (const QString & text) protected slot
Definition at line 68 of file MyLineEdit.cpp.
References updateColor().
Referenced by setupWidget().
 {
   updateColor();
 }
void MyLineEdit::updateColor () protected virtual
Definition at line 73 of file MyLineEdit.cpp.
References mErrorColor, mNewColor, and mOldColor.
Referenced by process(), setText(), and slotTextChanged().
 {
   if (isModified())
     {
       setStyleSheet("background-color:" + mNewColor.name() + ";");
     }
   else
     {
       setStyleSheet("background-color:" + mOldColor.name() + ";");
     }
   const QValidator * val = validator();
   int dummy = 0;
   QString ttt = text();
   if (val)
     if (val->validate(ttt, dummy) == QValidator::Intermediate)
       {
         setStyleSheet("background-color:" + mErrorColor.name() + ";");
       }
 }
Member Data Documentation
QColor MyLineEdit::mErrorColor protected
Definition at line 31 of file MyLineEdit.h.
Referenced by isValid(), setupWidget(), and updateColor().
QColor MyLineEdit::mNewColor protected
Definition at line 30 of file MyLineEdit.h.
Referenced by setupWidget(), and updateColor().
QColor MyLineEdit::mOldColor protected
Definition at line 29 of file MyLineEdit.h.
Referenced by setupWidget(), and updateColor().
The documentation for this class was generated from the following files:
MyLineEdit.h
MyLineEdit.cpp