COPASI API: CSensItem Class Reference
CSensItem Class Reference
#include <CSensProblem.h>
Public Member Functions
CSensItem ()
const CObjectLists::ListType & getListType () const
std::string getListTypeDisplayName () const
const CCopasiObjectName & getSingleObjectCN () const
std::string getSingleObjectDisplayName (const CCopasiDataModel *pDataModel) const
std::vector< CCopasiObject * > getVariablesPointerList (CCopasiDataModel *pDataModel)
bool isSingleObject () const
bool operator!= (const CSensItem &rhs) const
bool operator== (const CSensItem &rhs) const
std::string print (const CCopasiDataModel *pDataModel) const
void setListType (CObjectLists::ListType lt)
void setSingleObjectCN (const CCopasiObjectName &cn)
Private Attributes
CObjectLists::ListType mListType
CCopasiObjectName mSingleObjectCN
Detailed Description
This class describes either one specific COPASI object (represented by a registered object CN internally) or a list of objects (see CObjectLists class).
Definition at line 29 of file CSensProblem.h.
Constructor & Destructor Documentation
CSensItem::CSensItem ()
Definition at line 22 of file CSensProblem.cpp.
   : mSingleObjectCN(),
     mListType(CObjectLists::SINGLE_OBJECT)
 {}
Member Function Documentation
const CObjectLists::ListType & CSensItem::getListType () const
Definition at line 59 of file CSensProblem.cpp.
References mListType.
Referenced by CSensProblem::copySensItemToParameterGroup(), getVariablesPointerList(), operator==(), and SensitivitiesWidget::saveTask().
 {
   return mListType;
 }
std::string CSensItem::getListTypeDisplayName () const
Definition at line 64 of file CSensProblem.cpp.
References CObjectLists::ListTypeName, and mListType.
Referenced by CSensMethod::initialize(), and print().
 {
   return CObjectLists::ListTypeName[mListType];
 }
const CCopasiObjectName & CSensItem::getSingleObjectCN () const
Definition at line 39 of file CSensProblem.cpp.
References mSingleObjectCN.
Referenced by CSensProblem::copySensItemToParameterGroup(), getVariablesPointerList(), and operator==().
 {
   return mSingleObjectCN;
 }
std::string CSensItem::getSingleObjectDisplayName (const CCopasiDataModel * pDataModel) const
Definition at line 44 of file CSensProblem.cpp.
References CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDisplayName(), and mSingleObjectCN.
Referenced by print().
 {
   const CCopasiObject* tmpObject = pDataModel->getDataObject(mSingleObjectCN);
   if (tmpObject)
     return tmpObject->getObjectDisplayName();
   else
     return "";
 }
std::vector< CCopasiObject * > CSensItem::getVariablesPointerList (CCopasiDataModel * pDataModel)
Definition at line 90 of file CSensProblem.cpp.
References CCopasiDataModel::getDataObject(), CObjectLists::getListOfObjects(), getListType(), CCopasiDataModel::getModel(), getSingleObjectCN(), isSingleObject(), and CCopasiObject::isValueDbl().
Referenced by CSensMethod::initialize().
 {
   std::vector<CCopasiObject*> ret;
   if (isSingleObject())
     {
       CCopasiObject * tmpObject = pDataModel->getDataObject(getSingleObjectCN());
       if (!tmpObject) {return ret;}  //return empty list
       if (!tmpObject->isValueDbl()) {return ret;}  //return empty list
       ret.push_back(tmpObject);
     }
   else
     {
       ret = CObjectLists::getListOfObjects(getListType(), pDataModel->getModel());
     }
   return ret;
 }
bool CSensItem::isSingleObject () const
Definition at line 27 of file CSensProblem.cpp.
References mListType, and CObjectLists::SINGLE_OBJECT.
Referenced by CSensProblem::collapsRequested(), CSensProblem::copySensItemToParameterGroup(), getVariablesPointerList(), operator==(), and print().
 {
   return (mListType == CObjectLists::SINGLE_OBJECT);
 }
bool CSensItem::operator!= (const CSensItem & rhs) const
Definition at line 85 of file CSensProblem.cpp.
 {
   return !(*this == rhs);
 }
bool CSensItem::operator== (const CSensItem & rhs) const
Definition at line 69 of file CSensProblem.cpp.
References getListType(), getSingleObjectCN(), and isSingleObject().
 {
   if (isSingleObject() != rhs.isSingleObject())
     return false;
   if (isSingleObject())
     {
       if (getSingleObjectCN() != rhs.getSingleObjectCN())
         return false;
     }
   else if (getListType() != rhs.getListType())
     return false;
   return true;
 }
std::string CSensItem::print (const CCopasiDataModel * pDataModel) const
Had to disable the output operator because the datamodel is needed to print a sensitivity item. std::ostream &operator<<(std::ostream &os, const CSensItem & si) { if (si.isSingleObject()) os << si.getSingleObjectDisplayName(); else os << si.getListTypeDisplayName();
return os; }
Definition at line 600 of file CSensProblem.cpp.
References getListTypeDisplayName(), getSingleObjectDisplayName(), and isSingleObject().
Referenced by operator<<().
 {
   std::ostringstream os;
   if (this->isSingleObject())
     os << this->getSingleObjectDisplayName(pDataModel);
   else
     os << this->getListTypeDisplayName();
   return os.str();
 }
void CSensItem::setListType (CObjectLists::ListType lt)
Definition at line 54 of file CSensProblem.cpp.
References mListType.
Referenced by CSensProblem::copyParameterGroupToSensItem(), CSensProblem::CSensProblem(), CSensProblem::initDebugProblem(), SensitivitiesWidget::saveTask(), and setSingleObjectCN().
 {
   mListType = lt;
 }
void CSensItem::setSingleObjectCN (const CCopasiObjectName & cn)
Definition at line 32 of file CSensProblem.cpp.
References mSingleObjectCN, setListType(), and CObjectLists::SINGLE_OBJECT.
Referenced by CSensProblem::copyParameterGroupToSensItem(), CSensProblem::initDebugProblem(), and SensitivitiesWidget::saveTask().
 {
   mSingleObjectCN = cn;
   //  if (cn != "")
   setListType(CObjectLists::SINGLE_OBJECT);
 }
Member Data Documentation
CObjectLists::ListType CSensItem::mListType private
Definition at line 56 of file CSensProblem.h.
Referenced by getListType(), getListTypeDisplayName(), isSingleObject(), and setListType().
CCopasiObjectName CSensItem::mSingleObjectCN private
Definition at line 55 of file CSensProblem.h.
Referenced by getSingleObjectCN(), getSingleObjectDisplayName(), and setSingleObjectCN().
The documentation for this class was generated from the following files:
CSensProblem.h
CSensProblem.cpp