COPASI API: CTSSATask Class Reference
CTSSATask Class Reference
#include <CTSSATask.h>
Public Member Functions
virtual CCopasiMethod * createMethod (const int &type) const
CTSSATask (const CCopasiContainer *pParent=NULL)
CTSSATask (const CTSSATask &src, const CCopasiContainer *pParent=NULL)
CState * getState ()
const CTimeSeries & getTimeSeries () const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
virtual bool process (const bool &useInitialValues)
void processStart (const bool &useInitialValues)
bool processStep (const C_FLOAT64 &nextTime)
virtual bool restore ()
virtual bool setMethodType (const int &type)
virtual bool updateMatrices ()
~CTSSATask ()
Public Member Functions inherited from CCopasiTask
CCopasiTask (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const Type &taskType, const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const CCopasiTask &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
CProcessReport * getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
Type getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReport *pCallBack)
void setScheduled (const bool &scheduled)
void setType (const Type &type)
void setUpdateModel (const bool &updateModel)
virtual ~CCopasiTask ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const unsigned int ValidMethods []
Static Public Attributes inherited from CCopasiTask
static const std::string TypeName []
static const unsigned int ValidMethods []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Private Member Functions
void cleanup ()
Private Attributes
CState * mpCurrentState
const C_FLOAT64 * mpCurrentTime
CTSSAMethod * mpTSSAMethod
CTSSAProblem * mpTSSAProblem
CTimeSeries mTimeSeries
bool mTimeSeriesRequested
bool mUpdateMoieties
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01, STREAM = 0x02, FINISH = 0x04, REPORT = 0x10,
PLOT = 0x20, TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0, OUTPUT_BEFORE = INITIALIZE, OUTPUT_AFTER = FINISH, OUTPUT = REPORT | PLOT | STREAM,
OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH, OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH, ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
enum Type {
steadyState = 0, timeCourse, scan, fluxMode,
optimization, parameterFitting, mca, lyap,
tssAnalysis, sens, moieties, crosssection,
lna, unset
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiTask
static bool isValidMethod (const unsigned int &method, const unsigned int *validMethods)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
std::string mKey
unsigned C_INT32 mOutputCounter
CProcessReport * mpCallBack
CState * mpInitialState
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
Type mType
bool mUpdateModel
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 43 of file CTSSATask.h.
Constructor & Destructor Documentation
CTSSATask::CTSSATask (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 61 of file CTSSATask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, mUpdateMoieties, CCopasiParameter::Value::pBOOL, and CCopasiMethod::tssILDM.
                                                     :
   CCopasiTask(CCopasiTask::tssAnalysis, pParent),
   mTimeSeriesRequested(true),
   mTimeSeries(),
   mpTSSAProblem(NULL),
   mpTSSAMethod(NULL),
   mpCurrentState(NULL),
   mpCurrentTime(NULL)
 {
   mpProblem = new CTSSAProblem(this);
   mpMethod = createMethod(CCopasiMethod::tssILDM);
   this->add(mpMethod, true);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
 }
CTSSATask::CTSSATask (const CTSSATask & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CTSSATask & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 82 of file CTSSATask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiParameterGroup::elevateChildren(), CCopasiMethod::getSubType(), CCopasiParameter::getValue(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, mUpdateMoieties, and CCopasiParameter::Value::pBOOL.
                                                       :
   CCopasiTask(src, pParent),
   mTimeSeriesRequested(src.mTimeSeriesRequested),
   mTimeSeries(),
   mpTSSAProblem(NULL),
   mpTSSAMethod(NULL),
   mpCurrentState(NULL),
   mpCurrentTime(NULL)
 {
   mpProblem =
     new CTSSAProblem(*static_cast< CTSSAProblem * >(src.mpProblem), this);
   mpMethod = createMethod(src.mpMethod->getSubType());
   * mpMethod = * src.mpMethod;
   mpMethod->elevateChildren();
   this->add(mpMethod, true);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
 }
CTSSATask::~CTSSATask ()
Destructor
Definition at line 109 of file CTSSATask.cpp.
References cleanup().
 {
   cleanup();
 }
Member Function Documentation
void CTSSATask::cleanup () private
cleanup()
Definition at line 114 of file CTSSATask.cpp.
References mpCurrentState, and pdelete.
Referenced by ~CTSSATask().
 {
   pdelete(mpCurrentState);
 }
CCopasiMethod * CTSSATask::createMethod (const int & type) const virtual
Create a method of the specified type to solve the task. It is the duty of the caller to release the CCopasiMethod.
Parameters
const CCopasiMethod::SubType & type
Returns
CCopasiMethod *
Reimplemented from CCopasiTask.
Definition at line 418 of file CTSSATask.cpp.
References CTSSAMethod::createMethod().
Referenced by CTSSATask(), and setMethodType().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   return CTSSAMethod::createMethod(Type);
 }
CState * CTSSATask::getState ()
Retrieves a pointer to current state of the integration.
Returns
CState * pState
Definition at line 425 of file CTSSATask.cpp.
References mpCurrentState.
 {return mpCurrentState;}
const CTimeSeries & CTSSATask::getTimeSeries () const
gets a reference to the time series
Returns
time series
Definition at line 428 of file CTSSATask.cpp.
References mTimeSeries.
 {return mTimeSeries;}
bool CTSSATask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 138 of file CTSSATask.cpp.
References COutputHandler::addInterface(), CTimeSeries::allocate(), CTimeSeries::clear(), CCopasiProblem::getModel(), CCopasiParameterGroup::getParameter(), CModel::getState(), CTSSAProblem::getStepNumber(), CState::getTime(), CCopasiParameter::getValue(), CCopasiTask::initialize(), CCopasiMethod::isValidProblem(), mpCurrentState, mpCurrentTime, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mpTSSAMethod, mpTSSAProblem, mTimeSeries, mTimeSeriesRequested, mUpdateMoieties, CCopasiParameter::Value::pBOOL, pdelete, CTSSAMethod::predifineAnnotation(), CTSSAMethod::setModel(), CTSSAMethod::setProblem(), and CTSSAProblem::timeSeriesRequested().
 {
   assert(mpProblem && mpMethod);
   mpTSSAProblem = dynamic_cast<CTSSAProblem *>(mpProblem);
   assert(mpTSSAProblem);
   mpTSSAMethod = dynamic_cast<CTSSAMethod *>(mpMethod);
   assert(mpTSSAMethod);
   mpTSSAMethod->setProblem(mpTSSAProblem);
   bool success = mpMethod->isValidProblem(mpProblem);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
   pdelete(mpCurrentState);
   mpCurrentState = new CState(mpTSSAProblem->getModel()->getState());
   mpCurrentTime = &mpCurrentState->getTime();
   // Handle the time series as a regular output.
   mTimeSeriesRequested = mpTSSAProblem->timeSeriesRequested();
   if (pOutputHandler != NULL)
     {
       if (mTimeSeriesRequested)
         {
           mTimeSeries.allocate(mpTSSAProblem->getStepNumber());
           pOutputHandler->addInterface(&mTimeSeries);
         }
       else
         {
           mTimeSeries.clear();
         }
     }
 //NEW
   mpTSSAMethod->setModel(mpTSSAProblem->getModel());
   mpTSSAMethod->predifineAnnotation();
 //
   if (!CCopasiTask::initialize(of, pOutputHandler, pOstream)) success = false;
   return success;
 }
bool CTSSATask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 194 of file CTSSATask.cpp.
References CProcessReport::addItem(), COutputInterface::AFTER, COutputInterface::BEFORE, C_FLOAT64, COutputInterface::DURING, CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CProcessReport::finishItem(), CTSSAProblem::getDuration(), CCopasiException::getMessage(), CCopasiProblem::getModel(), CTSSAProblem::getOutputStartTime(), CTSSAProblem::getStepSize(), MCTSSAMethod, MCTSSAProblem, CCopasiTask::mpCallBack, mpCurrentState, mpCurrentTime, mpTSSAProblem, mUpdateMoieties, CCopasiTask::output(), processStart(), processStep(), CProcessReport::progressItem(), CProcessReport::setName(), CModel::setState(), tbl(), tble(), tfl(), tfle(), and CModel::updateSimulatedValues().
 {
   //*****
   processStart(useInitialValues);
   //*****
   C_FLOAT64 StepSize = mpTSSAProblem->getStepSize();
   C_FLOAT64 NextTimeToReport;
   const C_FLOAT64 EndTime = *mpCurrentTime + mpTSSAProblem->getDuration();
   const C_FLOAT64 StartTime = *mpCurrentTime;
   C_FLOAT64 StepNumber = (mpTSSAProblem->getDuration()) / StepSize;
   bool (*LE)(const C_FLOAT64 &, const C_FLOAT64 &);
   bool (*L)(const C_FLOAT64 &, const C_FLOAT64 &);
   if (StepSize < 0.0)
     {
       LE = &tble;
       L = &tbl;
     }
   else
     {
       LE = &tfle;
       L = &tfl;
     }
   size_t StepCounter = 1;
   C_FLOAT64 outputStartTime = mpTSSAProblem->getOutputStartTime();
   if (StepSize == 0.0 && mpTSSAProblem->getDuration() != 0.0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCTSSAProblem + 1, StepSize);
       return false;
     }
   output(COutputInterface::BEFORE);
   bool flagProceed = true;
   C_FLOAT64 handlerFactor = 100.0 / mpTSSAProblem->getDuration();
   C_FLOAT64 Percentage = 0;
   size_t hProcess;
   if (mpCallBack)
     {
       mpCallBack->setName("performing simulation...");
       C_FLOAT64 hundred = 100;
       hProcess = mpCallBack->addItem("Completion",
                                      Percentage,
                                      &hundred);
     }
   //if ((*LE)(outputStartTime, *mpCurrentTime)) output(COutputInterface::DURING);
   try
     {
       do
         {
           // This is numerically more stable then adding
           // mpTSSAProblem->getStepSize().
           NextTimeToReport =
             StartTime + (EndTime - StartTime) * StepCounter++ / StepNumber;
           flagProceed &= processStep(NextTimeToReport);
           if (mpCallBack)
             {
               Percentage = (*mpCurrentTime - StartTime) * handlerFactor;
               flagProceed &= mpCallBack->progressItem(hProcess);
             }
           if ((*LE)(outputStartTime, *mpCurrentTime))
             {
               output(COutputInterface::DURING);
             }
         }
       while ((*L)(*mpCurrentTime, EndTime) && flagProceed);
     }
   catch (int)
     {
       mpTSSAProblem->getModel()->setState(*mpCurrentState);
       mpTSSAProblem->getModel()->updateSimulatedValues(mUpdateMoieties);
       if ((*LE)(outputStartTime, *mpCurrentTime))
         {
           output(COutputInterface::DURING);
         }
       if (mpCallBack) mpCallBack->finishItem(hProcess);
       output(COutputInterface::AFTER);
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTSSAMethod + 4);
     }
   catch (CCopasiException & Exception)
     {
       mpTSSAProblem->getModel()->setState(*mpCurrentState);
       mpTSSAProblem->getModel()->updateSimulatedValues(mUpdateMoieties);
       if ((*LE)(outputStartTime, *mpCurrentTime))
         {
           output(COutputInterface::DURING);
         }
       if (mpCallBack) mpCallBack->finishItem(hProcess);
       output(COutputInterface::AFTER);
       throw CCopasiException(Exception.getMessage());
     }
   if (mpCallBack) mpCallBack->finishItem(hProcess);
   output(COutputInterface::AFTER);
   return true;
 }
void CTSSATask::processStart (const bool & useInitialValues)
Starts the process of integration by calling CTSSAMethod::start
Parameters
const bool & useInitialValues
Definition at line 319 of file CTSSATask.cpp.
References CModel::applyInitialValues(), CCopasiProblem::getModel(), CModel::getState(), mpCurrentState, mpTSSAMethod, mpTSSAProblem, CTSSAMethod::setCurrentState(), and CTSSAMethod::start().
Referenced by process().
 {
   if (useInitialValues)
     mpTSSAProblem->getModel()->applyInitialValues();
   *mpCurrentState = mpTSSAProblem->getModel()->getState();
   mpTSSAMethod->setCurrentState(mpCurrentState);
   mpTSSAMethod->start(mpCurrentState);
   return;
 }
bool CTSSATask::processStep (const C_FLOAT64 & nextTime)
Integrates one step
Parameters
const C_FLOAT64 & nextTime
Returns
bool success;
Definition at line 332 of file CTSSATask.cpp.
References C_FLOAT64, CCopasiMessage::EXCEPTION, CCopasiProblem::getModel(), MCTSSAMethod, mpCurrentState, mpCurrentTime, mpTSSAMethod, mpTSSAProblem, mUpdateMoieties, CModel::setState(), CTSSAMethod::step(), and CModel::updateSimulatedValues().
Referenced by process().
 {
   C_FLOAT64 CompareTime = nextTime - 100.0 * fabs(nextTime) * std::numeric_limits< C_FLOAT64 >::epsilon();
   if (*mpCurrentTime <= CompareTime)
     {
       do
         {
           mpTSSAMethod->step(nextTime - *mpCurrentTime);
           if (*mpCurrentTime > CompareTime) break;
           /* Here we will do conditional event processing */
           /* Currently this is correct since no events are processed. */
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCTSSAMethod + 3);
         }
       while (true);
       mpTSSAProblem->getModel()->setState(*mpCurrentState);
       mpTSSAProblem->getModel()->updateSimulatedValues(mUpdateMoieties);
       return true;
     }
   CompareTime = nextTime + 100.0 * fabs(nextTime) * std::numeric_limits< C_FLOAT64 >::epsilon();
   if (*mpCurrentTime >= CompareTime)
     {
       do
         {
           mpTSSAMethod->step(nextTime - *mpCurrentTime);
           if (*mpCurrentTime < CompareTime) break;
           /* Here we will do conditional event processing */
           /* Currently this is correct since no events are processed. */
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCTSSAMethod + 3);
         }
       while (true);
       mpTSSAProblem->getModel()->setState(*mpCurrentState);
       mpTSSAProblem->getModel()->updateSimulatedValues(mUpdateMoieties);
       return true;
     }
   // Current time is approximately nextTime;
   return false;
 }
bool CTSSATask::restore () virtual
Perform necessary cleanup procedures
Reimplemented from CCopasiTask.
Definition at line 384 of file CTSSATask.cpp.
References CCopasiProblem::getModel(), CModel::getState(), mpCurrentState, CCopasiTask::mpProblem, CCopasiTask::mUpdateModel, mUpdateMoieties, CCopasiTask::restore(), CModel::setInitialState(), CModel::setState(), CModel::updateInitialValues(), and CModel::updateSimulatedValues().
 {
   bool success = CCopasiTask::restore();
   if (mUpdateModel)
     {
       CModel * pModel = mpProblem->getModel();
       pModel->setState(*mpCurrentState);
       pModel->updateSimulatedValues(mUpdateMoieties);
       pModel->setInitialState(pModel->getState());
       pModel->updateInitialValues();
     }
   return success;
 }
bool CTSSATask::setMethodType (const int & type) virtual
Set the method type applied to solve the task
Parameters
const CCopasiMethod::SubType & type
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 401 of file CTSSATask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiMethod::getSubType(), CCopasiTask::isValidMethod(), CCopasiTask::mpMethod, pdelete, and ValidMethods.
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   if (!isValidMethod(Type, ValidMethods)) return false;
   if (mpMethod->getSubType() == Type) return true;
   pdelete(mpMethod);
   mpMethod = createMethod(Type);
   this->add(mpMethod, true);
   //mpMethod->setObjectParent(this);
   return true;
 }
bool CTSSATask::updateMatrices () virtual
Resizes result matrices and updates array annotations for a specific task. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented from CCopasiTask.
Definition at line 119 of file CTSSATask.cpp.
References CCopasiProblem::getModel(), CCopasiMethod::isValidProblem(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, CTSSAMethod::predifineAnnotation(), and CTSSAMethod::setModel().
 {
   assert(mpProblem != NULL && mpMethod != NULL);
   assert(dynamic_cast<CTSSAProblem *>(mpProblem) != NULL);
   if (!mpMethod->isValidProblem(mpProblem)) return false;
   CTSSAMethod * pMethod = dynamic_cast<CTSSAMethod*>(mpMethod);
   if (!pMethod) return false;
   pMethod->setModel(mpProblem->getModel());
   pMethod->predifineAnnotation();
   return true;
 }
Member Data Documentation
CState* CTSSATask::mpCurrentState private
A pointer to the current state of the integration.
Definition at line 82 of file CTSSATask.h.
Referenced by cleanup(), getState(), initialize(), process(), processStart(), processStep(), and restore().
const C_FLOAT64* CTSSATask::mpCurrentTime private
A pointer to the current time of the integration.
Definition at line 87 of file CTSSATask.h.
Referenced by initialize(), process(), and processStep().
CTSSAMethod* CTSSATask::mpTSSAMethod private
A pointer to the method
Definition at line 72 of file CTSSATask.h.
Referenced by initialize(), processStart(), and processStep().
CTSSAProblem* CTSSATask::mpTSSAProblem private
A pointer to the Problem
Definition at line 67 of file CTSSATask.h.
Referenced by initialize(), process(), processStart(), and processStep().
CTimeSeries CTSSATask::mTimeSeries private
the time series (if requested)
Definition at line 62 of file CTSSATask.h.
Referenced by getTimeSeries(), and initialize().
bool CTSSATask::mTimeSeriesRequested private
whether the time series should be stored in mTimeSeries
Definition at line 57 of file CTSSATask.h.
Referenced by initialize().
bool CTSSATask::mUpdateMoieties private
Indicates whether we need to update moieties.
Definition at line 77 of file CTSSATask.h.
Referenced by CTSSATask(), initialize(), process(), processStep(), and restore().
const unsigned int CTSSATask::ValidMethods static
Initial value:
=
{
  CCopasiMethod::tssILDM,
  CCopasiMethod::tssILDMModified,
  CCopasiMethod::tssCSP,
  CCopasiMethod::unset
}
The methods which can be selected for performing this task.
Definition at line 50 of file CTSSATask.h.
Referenced by CQTSSAWidget::init(), and setMethodType().
The documentation for this class was generated from the following files:
CTSSATask.h
CTSSATask.cpp