COPASI API: CTrajAdaptiveSA Class Reference
CTrajAdaptiveSA Class Reference
#include <CTrajAdaptiveSA.h>
Classes
class CReactionDependencies
Public Member Functions
CTrajAdaptiveSA (const CTrajAdaptiveSA &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual void start (const CState *initialState)
virtual Status step (const double &deltaT)
~CTrajAdaptiveSA ()
Public Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CTrajectoryMethod &src, const CCopasiContainer *pParent=NULL)
const CVector< C_INT > & getRoots () const
void setCurrentState (CState *currentState)
void setProblem (CTrajectoryProblem *problem)
virtual void stateChanged ()
~CTrajectoryMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CTrajAdaptiveSA * createTauLeapMethod ()
Static Public Member Functions inherited from CTrajectoryMethod
static CTrajectoryMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::deterministic)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
const C_FLOAT64 & calculateAmu (const size_t &index)
CTrajAdaptiveSA (const CCopasiContainer *pParent=NULL)
C_FLOAT64 doSingleSSAStep (const C_FLOAT64 &curTime, const C_FLOAT64 &endTime)
C_FLOAT64 doSingleTauLeapStep (const C_FLOAT64 &curTime, const C_FLOAT64 &endTime)
Protected Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CCopasiMethod::SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
C_FLOAT64 mA0
CVector< C_FLOAT64 > mAmu
bool mDoCorrection
unsigned C_INT32 mMaxSteps
bool mMaxStepsReached
CState mMethodState
size_t mNextReactionIndex
C_FLOAT64 mNextReactionTime
size_t mNumReactions
size_t mNumReactionSpecies
size_t mNumSpecies
CVector< const C_FLOAT64 * > mPartitionedAmu
CVector< const
CReactionDependencies * > mPartitionedDependencies
CModel * mpModel
CRandom * mpRandomGenerator
std::vector
< CReactionDependencies > mReactionDependencies
Protected Attributes inherited from CTrajectoryMethod
CState * mpCurrentState
CTrajectoryProblem * mpProblem
CVector< C_INT > mRoots
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void initializeParameter ()
Private Attributes
CVector< C_FLOAT64 > mAvgDX
C_FLOAT64 mEpsilon
size_t mFirstReactionSpeciesIndex
CVector< size_t > mMaxReactionFiring
CVector< C_FLOAT64 * > mPartitionedReactionFiring
C_FLOAT64 * mpMethodSpecies
CVector< C_FLOAT64 > mReactionFiring
CVector< C_FLOAT64 > mSigDX
CVector< C_FLOAT64 > mSpeciesAfterTau
C_FLOAT64 mSSAStepCounter
std::vector< Refresh * > mTauCalculations
Friends
CTrajectoryMethod * CTrajectoryMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CTrajectoryMethod
enum Status { FAILURE = -1, NORMAL = 0, ROOT = 1 }
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 36 of file CTrajAdaptiveSA.h.
Constructor & Destructor Documentation
CTrajAdaptiveSA::CTrajAdaptiveSA (const CCopasiContainer * pParent = NULL) protected
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 86 of file CTrajAdaptiveSA.cpp.
References initializeParameter().
Referenced by createTauLeapMethod().
                                                                 :
   CTrajectoryMethod(CCopasiMethod::adaptiveSA, pParent),
   mMaxReactionFiring(0),
   mReactionFiring(0),
   mPartitionedReactionFiring(0),
   mAvgDX(0),
   mSigDX(0),
   mpMethodSpecies(NULL),
   mSpeciesAfterTau(0),
   mpRandomGenerator(CRandom::createGenerator(CRandom::mt19937)),
   mpModel(NULL),
   mNumReactions(0),
   mNumSpecies(0),
   mMaxSteps(1000000),
   mNextReactionTime(0.0),
   mNextReactionIndex(C_INVALID_INDEX),
   mDoCorrection(true),
   mAmu(0),
   mPartitionedAmu(0),
   mMethodState(),
   mReactionDependencies(0),
   mPartitionedDependencies(0),
   mA0(0.0),
   mMaxStepsReached(false)
 {
   initializeParameter();
 }
CTrajAdaptiveSA::CTrajAdaptiveSA (const CTrajAdaptiveSA & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CTrajAdaptiveSA & src,
const CCopasiContainer * pParent (Default: NULL)
Definition at line 114 of file CTrajAdaptiveSA.cpp.
References initializeParameter().
                                                                   :
   CTrajectoryMethod(src, pParent),
   mMaxReactionFiring(src.mMaxReactionFiring),
   mReactionFiring(src.mReactionFiring),
   mPartitionedReactionFiring(src.mPartitionedReactionFiring),
   mAvgDX(src.mAvgDX),
   mSigDX(src.mSigDX),
   mpMethodSpecies(src.mpMethodSpecies),
   mSpeciesAfterTau(src.mSpeciesAfterTau),
   mpRandomGenerator(CRandom::createGenerator(CRandom::mt19937)),
   mpModel(src.mpModel),
   mNumReactions(src.mNumReactions),
   mNumSpecies(src.mNumSpecies),
   mMaxSteps(src.mMaxSteps),
   mNextReactionTime(src.mNextReactionTime),
   mNextReactionIndex(src.mNextReactionIndex),
   mDoCorrection(src.mDoCorrection),
   mAmu(src.mAmu),
   mPartitionedAmu(src.mPartitionedAmu),
   mMethodState(src.mMethodState),
   mReactionDependencies(src.mReactionDependencies),
   mPartitionedDependencies(src.mPartitionedDependencies),
   mA0(src.mA0),
   mMaxStepsReached(src.mMaxStepsReached)
 {
   initializeParameter();
 }
CTrajAdaptiveSA::~CTrajAdaptiveSA ()
Destructor.
Definition at line 143 of file CTrajAdaptiveSA.cpp.
References mpRandomGenerator, and pdelete.
 {
   pdelete(mpRandomGenerator);
 }
Member Function Documentation
const C_FLOAT64 & CTrajAdaptiveSA::calculateAmu (const size_t & index) protected
Calculate the propensity of the indexed reaction
Parameters
const size_t & index
Definition at line 844 of file CTrajAdaptiveSA.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, mAmu, mDoCorrection, CTrajAdaptiveSA::CReactionDependencies::mMethodSubstrates, CTrajAdaptiveSA::CReactionDependencies::mModelSubstrates, CTrajAdaptiveSA::CReactionDependencies::mpParticleFlux, mReactionDependencies, CTrajAdaptiveSA::CReactionDependencies::mSubstrateMultiplier, and CVectorCore< CType >::size().
Referenced by doSingleSSAStep(), doSingleTauLeapStep(), and start().
 {
   const CReactionDependencies & Dependencies = mReactionDependencies[index];
   C_FLOAT64 & Amu = mAmu[index];
   Amu = *Dependencies.mpParticleFlux;
   if (Amu < 0.0)
     {
       // TODO CRITICAL Create a warning message
       Amu = 0.0;
     }
   if (!mDoCorrection)
     {
       return Amu;
     }
   C_FLOAT64 SubstrateMultiplier = 1.0;
   C_FLOAT64 SubstrateDevisor = 1.0;
   C_FLOAT64 Multiplicity;
   C_FLOAT64 LowerBound;
   C_FLOAT64 Number;
   bool ApplyCorrection = false;
   const C_FLOAT64 * pMultiplicity = Dependencies.mSubstrateMultiplier.array();
   const C_FLOAT64 * pEndMultiplicity = pMultiplicity + Dependencies.mSubstrateMultiplier.size();
   C_FLOAT64 *const* ppLocalSubstrate = Dependencies.mMethodSubstrates.array();
   C_FLOAT64 *const* ppModelSubstrate = Dependencies.mModelSubstrates.array();
   for (; pMultiplicity != pEndMultiplicity; ++pMultiplicity, ++ppLocalSubstrate, ++ppModelSubstrate)
     {
       Multiplicity = *pMultiplicity;
       // TODO We should check the error introduced through rounding.
       **ppLocalSubstrate = floor(**ppModelSubstrate + 0.5);
       if (Multiplicity > 1.01)
         {
           ApplyCorrection = true;
           Number = **ppLocalSubstrate;
           LowerBound = Number - Multiplicity;
           SubstrateDevisor *= pow(Number, Multiplicity - 1.0);  //optimization
           Number -= 1.0;
           while (Number > LowerBound)
             {
               SubstrateMultiplier *= Number;
               Number -= 1.0;
             }
         }
     }
   // at least one substrate particle number is zero
   if (SubstrateMultiplier < 0.5 || SubstrateDevisor < 0.5)
     {
       Amu = 0.0;
     }
   else if (ApplyCorrection)
     {
       Amu *= SubstrateMultiplier / SubstrateDevisor;
     }
   return Amu;
 }
CTrajAdaptiveSA * CTrajAdaptiveSA::createTauLeapMethod () static
Chooses a stochastic method adequate for the problem
Definition at line 77 of file CTrajAdaptiveSA.cpp.
References CTrajAdaptiveSA().
 {
   CTrajAdaptiveSA * pMethod = NULL;
   pMethod = new CTrajAdaptiveSA();
   return pMethod;
 }
C_FLOAT64 CTrajAdaptiveSA::doSingleSSAStep (const C_FLOAT64 & curTime, const C_FLOAT64 & endTime) protected
Fire the next reaction if it fire before the endTime
Parameters
const C_FLOAT64 & curTime
const C_FLOAT64 & endTime
Returns
C_FLOAT64 timeAfterStep
Definition at line 753 of file CTrajAdaptiveSA.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, C_INVALID_INDEX, calculateAmu(), CCopasiMessage::EXCEPTION, CRandom::getRandomOO(), mA0, mAmu, CTrajAdaptiveSA::CReactionDependencies::mCalculations, MCTrajectoryMethod, CTrajAdaptiveSA::CReactionDependencies::mDependentReactions, CTrajAdaptiveSA::CReactionDependencies::mMethodSpecies, CTrajAdaptiveSA::CReactionDependencies::mModelSpecies, mNextReactionIndex, mNextReactionTime, mNumReactions, mpModel, mpRandomGenerator, mReactionDependencies, CTrajAdaptiveSA::CReactionDependencies::mSpeciesMultiplier, CModel::setTime(), and CVectorCore< CType >::size().
Referenced by step().
 {
   if (mNextReactionIndex == C_INVALID_INDEX)
     {
       if (mA0 == 0)
         {
           return endTime - curTime;
         }
       // We need to throw an exception if mA0 is NaN
       if (isnan(mA0))
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 27);
         }
       mNextReactionTime = curTime - log(mpRandomGenerator->getRandomOO()) / mA0;
     }
   if (mNextReactionTime >= endTime)
     {
       return endTime - curTime;
     }
   // Update the model time (for explicitly time dependent models)
   mpModel->setTime(mNextReactionTime);
   // We are sure that we have at least 1 reaction
   mNextReactionIndex = 0;
   C_FLOAT64 sum = 0.0;
   C_FLOAT64 rand = mpRandomGenerator->getRandomOO() * mA0;
   C_FLOAT64 * pAmu = mAmu.array();
   C_FLOAT64 * endAmu = pAmu + mNumReactions;
   for (; (sum < rand) && (pAmu != endAmu); ++pAmu, ++mNextReactionIndex)
     {
       sum += *pAmu;
     }
   mNextReactionIndex--;
   CReactionDependencies & Dependencies = mReactionDependencies[mNextReactionIndex];
   // Update the method internal and model species numbers
   C_FLOAT64 ** ppModelSpecies = Dependencies.mModelSpecies.array();
   C_FLOAT64 ** ppLocalSpecies = Dependencies.mMethodSpecies.array();
   C_FLOAT64 * pMultiplicity = Dependencies.mSpeciesMultiplier.array();
   C_FLOAT64 * pMultiplicityEnd = pMultiplicity + Dependencies.mSpeciesMultiplier.size();
   //if(mAmu.array()[mNextReactionIndex]==0) //Important check
   //  printf("Error 0\n");
   for (; pMultiplicity != pMultiplicityEnd; ++pMultiplicity, ++ppLocalSpecies, ++ppModelSpecies)
     {
       **ppLocalSpecies += *pMultiplicity;
       **ppModelSpecies = **ppLocalSpecies;
     }
   // Calculate all values which depend on the firing reaction
   std::vector< Refresh * >::const_iterator itCalcualtion =  Dependencies.mCalculations.begin();
   std::vector< Refresh * >::const_iterator endCalcualtion =  Dependencies.mCalculations.end();
   while (itCalcualtion != endCalcualtion)
     {
       (**itCalcualtion++)();
     }
   // calculate the propensities which depend on the firing reaction
   size_t * pDependentReaction = Dependencies.mDependentReactions.array();
   size_t * endDependentReactions = pDependentReaction + Dependencies.mDependentReactions.size();
   for (; pDependentReaction != endDependentReactions; ++pDependentReaction)
     {
       calculateAmu(*pDependentReaction);
     }
   // calculate the total propensity
   pAmu = mAmu.array();
   mA0 = 0.0;
   for (; pAmu != endAmu; ++pAmu)
     {
       mA0 += *pAmu;
     }
   mNextReactionIndex = C_INVALID_INDEX;
   return mNextReactionTime - curTime;
 }
C_FLOAT64 CTrajAdaptiveSA::doSingleTauLeapStep (const C_FLOAT64 & curTime, const C_FLOAT64 & endTime) protected
Fire the next reaction if it fire before the endTime
Parameters
const C_FLOAT64 & curTime
const C_FLOAT64 & endTime
Returns
C_FLOAT64 timeAfterStep
Definition at line 482 of file CTrajAdaptiveSA.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, C_INVALID_INDEX, calculateAmu(), CCopasiMessage::EXCEPTION, CRandom::getRandomOO(), CRandom::getRandomPoisson(), mA0, mAmu, mAvgDX, max, MCTrajectoryMethod, mEpsilon, mMaxReactionFiring, CTrajAdaptiveSA::CReactionDependencies::mMethodSpeciesIndex, mMethodState, mNumReactions, mNumReactionSpecies, mPartitionedAmu, mPartitionedDependencies, mPartitionedReactionFiring, mpMethodSpecies, mpModel, mpRandomGenerator, mReactionDependencies, mReactionFiring, mSigDX, mSpeciesAfterTau, CTrajAdaptiveSA::CReactionDependencies::mSpeciesMultiplier, mSSAStepCounter, CModel::setState(), CState::setTime(), CVectorCore< CType >::size(), SSA_MULTIPLE, SSA_UPPER_NUM, CModel::updateSimulatedValues(), and UPPER_LIMIT.
Referenced by step().
 {
   std::vector< CReactionDependencies >::const_iterator itDependencies = mReactionDependencies.begin();
   std::vector< CReactionDependencies >::const_iterator endDependencies = mReactionDependencies.end();
   size_t * pMaxReactionFiring = mMaxReactionFiring.array();
   for (; itDependencies != endDependencies; ++itDependencies, ++pMaxReactionFiring)
     {
       C_FLOAT64 *const* ppModelSpecies = itDependencies->mModelSpecies.array();
       const C_FLOAT64 * pMultiplicity = itDependencies->mSpeciesMultiplier.array();
       const C_FLOAT64 * pMultiplicityEnd = pMultiplicity + itDependencies->mSpeciesMultiplier.size();
       *pMaxReactionFiring = std::numeric_limits< size_t >::max(); // Assigned a maximum value
       for (; pMultiplicity != pMultiplicityEnd; pMultiplicity++, ppModelSpecies++)
         {
           if (*pMultiplicity < 0)
             {
               size_t TmpMax;
               if ((TmpMax = (size_t) fabs(**ppModelSpecies / *pMultiplicity)) < *pMaxReactionFiring)
                 {
                   *pMaxReactionFiring = TmpMax;
                 }
             }
         }
     }
   size_t NonCriticalReactions = 0;
   size_t InsertCritical = mNumReactions - 1;
   pMaxReactionFiring = mMaxReactionFiring.array();
   const C_FLOAT64 * pAmu = mAmu.array();
   itDependencies = mReactionDependencies.begin();
   C_FLOAT64 * pReactionFiring = mReactionFiring.array();
   for (; itDependencies != endDependencies; ++itDependencies, ++pAmu, ++pMaxReactionFiring, ++pReactionFiring)
     {
       *pReactionFiring = 0;
       if (*pAmu == 0 ||
           *pMaxReactionFiring > UPPER_LIMIT)
         {
           mPartitionedDependencies[NonCriticalReactions] = &(*itDependencies);
           mPartitionedAmu[NonCriticalReactions] = pAmu;
           mPartitionedReactionFiring[NonCriticalReactions] = pReactionFiring;
           NonCriticalReactions++;
         }
       else
         {
           mPartitionedDependencies[InsertCritical] = &(*itDependencies);
           mPartitionedAmu[InsertCritical] = pAmu;
           mPartitionedReactionFiring[InsertCritical] = pReactionFiring;
           InsertCritical--;
         }
     }
   mAvgDX = 0.0;
   mSigDX = 0.0;
   const CReactionDependencies **ppOrderedReactions = mPartitionedDependencies.array();
   const C_FLOAT64 ** ppOrderedAmu = mPartitionedAmu.array();
   const C_FLOAT64 ** ppOrderedAmuEnd = ppOrderedAmu + NonCriticalReactions;
   for (; ppOrderedAmu != ppOrderedAmuEnd; ++ppOrderedReactions, ++ppOrderedAmu)
     {
       const C_FLOAT64 * pMultiplicity = (*ppOrderedReactions)->mSpeciesMultiplier.array();
       const C_FLOAT64 * pMultiplicityEnd = pMultiplicity + (*ppOrderedReactions)->mSpeciesMultiplier.size();
       const size_t * pIndex = (*ppOrderedReactions)->mMethodSpeciesIndex.array();
       for (; pMultiplicity != pMultiplicityEnd; pMultiplicity++, pIndex++)
         {
           mAvgDX[*pIndex] += **ppOrderedAmu * *pMultiplicity;
           mSigDX[*pIndex] += **ppOrderedAmu * *pMultiplicity * *pMultiplicity;
         }
     }
   C_FLOAT64 MaxTau;
   if (NonCriticalReactions == 0)
     {
       MaxTau = 0;
     }
   else
     {
       C_FLOAT64 ex, t1, t2;
       t1 = t2 = std::numeric_limits< C_FLOAT64 >::infinity();
       for (size_t i = 0; i < mNumReactionSpecies; i++)
         {
           C_FLOAT64 t3, t4, t5, t6;
           ex = (*(mpMethodSpecies + i) * mEpsilon) + 1.0;
           t3 = fabs(mAvgDX[i]);
           t4 = mSigDX[i];
           t5 = ex / t3;
           t6 = ex * ex / t4;
           if (t3 != 0 && t5 < t1) t1 = t5;
           if (t4 != 0 && t6 < t2) t2 = t6;
         }
       if (t1 < t2)
         MaxTau = t1;
       else
         MaxTau = t2;
     }
   if (MaxTau < (SSA_MULTIPLE / mA0) ||
       MaxTau == std::numeric_limits< C_FLOAT64 >::infinity())
     {
       mSSAStepCounter = SSA_UPPER_NUM;
       mpModel->setState(mMethodState);
       mpModel->updateSimulatedValues(false);
       return 0;
     }
   C_FLOAT64 AmuCritical = 0;
   ppOrderedAmu = mPartitionedAmu.array() + NonCriticalReactions;
   ppOrderedAmuEnd = mPartitionedAmu.array() + mNumReactions;
   for (; ppOrderedAmu != ppOrderedAmuEnd; ++ppOrderedAmu)
     {
       AmuCritical += **ppOrderedAmu;
     }
   C_FLOAT64 CriticalReactionTau;
   if (NonCriticalReactions == mNumReactions || AmuCritical == 0)
     CriticalReactionTau = std::numeric_limits< C_FLOAT64 >::infinity();
   else
     CriticalReactionTau = -log(mpRandomGenerator->getRandomOO()) / AmuCritical;
   bool isUpdated = false;
   C_FLOAT64 Tau;
   while (!isUpdated)
     {
       Tau = MaxTau;
       if (CriticalReactionTau < Tau || Tau == 0) Tau = CriticalReactionTau;
       if ((endTime - curTime) < Tau) Tau = (endTime - curTime);
       // Calculate the firing of non critical reactions
       ppOrderedAmu = mPartitionedAmu.array();
       ppOrderedAmuEnd = mPartitionedAmu.array() + NonCriticalReactions;
       C_FLOAT64 **ppOrderedReactionFiring = mPartitionedReactionFiring.array();
       for (; ppOrderedAmu != ppOrderedAmuEnd; ++ppOrderedAmu, ++ppOrderedReactionFiring)
         {
           C_FLOAT64 Lambda = **ppOrderedAmu * Tau;
           if (Lambda < 0.0)
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 10);
           else if (Lambda > 2.0e9)
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 26);
           **ppOrderedReactionFiring = mpRandomGenerator->getRandomPoisson(Lambda);
         }
       size_t CriticalReactionIndex = C_INVALID_INDEX;
       if (CriticalReactionTau <= Tau)
         {
           // Determine the critical reaction which fires.
           C_FLOAT64 sum = 0;
           C_FLOAT64 rand = mpRandomGenerator->getRandomOO() * AmuCritical;
           ppOrderedAmu = mPartitionedAmu.array() + NonCriticalReactions;
           ppOrderedAmuEnd = mPartitionedAmu.array() + mNumReactions;
           CriticalReactionIndex = NonCriticalReactions;
           for (; (sum < rand) && (ppOrderedAmu != ppOrderedAmuEnd); ++ppOrderedAmu, ++CriticalReactionIndex)
             {
               sum += **ppOrderedAmu;
             }
           CriticalReactionIndex--;
         }
       C_FLOAT64 * pSpeciesAfterTau = mSpeciesAfterTau.array();
       C_FLOAT64 * pSpeciesAfterTauEnd = pSpeciesAfterTau + mNumReactionSpecies;
       C_FLOAT64 * pMethodSpecies = mpMethodSpecies;
       for (; pSpeciesAfterTau != pSpeciesAfterTauEnd; ++pSpeciesAfterTau, ++pMethodSpecies)
         {
           *pSpeciesAfterTau = *pMethodSpecies;
         }
       ppOrderedReactions = mPartitionedDependencies.array();
       const CReactionDependencies **ppOrderedReactionsEnd = ppOrderedReactions + NonCriticalReactions;
       ppOrderedReactionFiring = mPartitionedReactionFiring.array();
       for (; ppOrderedReactions != ppOrderedReactionsEnd; ++ppOrderedReactions, ++ppOrderedReactionFiring)
         {
           const C_FLOAT64 * pMultiplicity = (*ppOrderedReactions)->mSpeciesMultiplier.array();
           const C_FLOAT64 * pMultiplicityEnd = pMultiplicity + (*ppOrderedReactions)->mSpeciesMultiplier.size();
           const size_t *pIndex = (*ppOrderedReactions)->mMethodSpeciesIndex.array();
           for (; pMultiplicity != pMultiplicityEnd;  pMultiplicity++, pIndex++)
             {
               mSpeciesAfterTau[*pIndex] += (*pMultiplicity * **ppOrderedReactionFiring);
             }
           **ppOrderedReactionFiring = 0.0;
         }
       if (CriticalReactionIndex != C_INVALID_INDEX)
         {
           const CReactionDependencies * pCriticalReaction = mPartitionedDependencies[CriticalReactionIndex];
           const C_FLOAT64 * pMultiplicity = pCriticalReaction->mSpeciesMultiplier.array();
           const C_FLOAT64 * pMultiplicityEnd = pMultiplicity + pCriticalReaction->mSpeciesMultiplier.size();
           const size_t *pIndex = pCriticalReaction->mMethodSpeciesIndex.array();
           for (; pMultiplicity != pMultiplicityEnd;  pMultiplicity++, pIndex++)
             {
               mSpeciesAfterTau[*pIndex] += *pMultiplicity;
             }
         }
       pSpeciesAfterTau = mSpeciesAfterTau.array();
       for (; pSpeciesAfterTau != pSpeciesAfterTauEnd; ++pSpeciesAfterTau)
         {
           if (*pSpeciesAfterTau < 0)
             break;
         }
       if (pSpeciesAfterTau != pSpeciesAfterTauEnd)
         {
           isUpdated = false;
           MaxTau = MaxTau / 2.0;
         }
       else
         {
           isUpdated = true;
           pSpeciesAfterTau = mSpeciesAfterTau.array();
           pMethodSpecies = mpMethodSpecies;
           for (; pSpeciesAfterTau != pSpeciesAfterTauEnd; ++pSpeciesAfterTau, ++pMethodSpecies)
             {
               *pMethodSpecies = *pSpeciesAfterTau;
             }
         }
     }
   // Update the model time (for explicitly time dependent models)
   mMethodState.setTime(curTime + Tau);
   mpModel->setState(mMethodState);
   mpModel->updateSimulatedValues(false);
   mA0 = 0;
   size_t i;
   for (i = 0; i < mNumReactions; i++)
     {
       mA0 += calculateAmu(i);
     }
   return Tau;
 }
bool CTrajAdaptiveSA::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 156 of file CTrajAdaptiveSA.cpp.
References initializeParameter().
 {
   initializeParameter();
   return true;
 }
void CTrajAdaptiveSA::initializeParameter () private
Initialize the method parameter
Definition at line 148 of file CTrajAdaptiveSA.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::DOUBLE, EPS, CCopasiParameter::INT, and CCopasiParameter::UINT.
Referenced by CTrajAdaptiveSA(), and elevateChildren().
 {
   assertParameter("Epsilon", CCopasiParameter::DOUBLE, (C_FLOAT64) EPS);
   assertParameter("Max Internal Steps", CCopasiParameter::INT, (C_INT32) 1000000);
   assertParameter("Use Random Seed", CCopasiParameter::BOOL, false);
   assertParameter("Random Seed", CCopasiParameter::UINT, (unsigned C_INT32) 1);
 }
bool CTrajAdaptiveSA::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CTrajectoryMethod.
Definition at line 411 of file CTrajAdaptiveSA.cpp.
References CStateTemplate::beginIndependent(), CStateTemplate::endIndependent(), CCopasiMessage::EXCEPTION, CTrajectoryProblem::getDuration(), CCopasiProblem::getModel(), CModel::getStateTemplate(), CModel::getTotSteps(), CCopasiParameter::getValue(), CTrajectoryMethod::isValidProblem(), MCTrajectoryMethod, CModelEntity::ODE, CCopasiParameter::Value::pINT, and CModel::suitableForStochasticSimulation().
 {
   if (!CTrajectoryMethod::isValidProblem(pProblem)) return false;
   const CTrajectoryProblem * pTP = dynamic_cast<const CTrajectoryProblem *>(pProblem);
   if (pTP->getDuration() < 0.0)
     {
       //back integration not possible
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 9);
       return false;
     }
   if (pTP->getModel()->getTotSteps() < 1)
     {
       //at least one reaction necessary
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 17);
       return false;
     }
   // check for ODEs
   const CStateTemplate & StateTemplate = pTP->getModel()->getStateTemplate();
   CModelEntity *const* ppEntity = StateTemplate.beginIndependent();
   CModelEntity *const* ppEntityEnd = StateTemplate.endIndependent();
   for (; ppEntity != ppEntityEnd; ++ppEntity)
     {
       if ((*ppEntity)->getStatus() == CModelEntity::ODE)
         {
           if (dynamic_cast<const CModelValue *>(*ppEntity) != NULL)
             {
               // global quantity ode rule found
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 18);
               return false;
             }
           else if (dynamic_cast<const CCompartment *>(*ppEntity) != NULL)
             {
               // compartment ode rule found
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 21);
               return false;
             }
           else
             {
               // species ode rule found
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 20);
               return false;
             }
         }
     }
   //TODO: rewrite CModel::suitableForStochasticSimulation() to use
   //      CCopasiMessage
   std::string message = pTP->getModel()->suitableForStochasticSimulation();
   if (message != "")
     {
       //model not suitable, message describes the problem
       CCopasiMessage(CCopasiMessage::EXCEPTION, message.c_str());
       return false;
     }
   if (* getValue("Max Internal Steps").pINT <= 0)
     {
       //max steps should be at least 1
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 15);
       return false;
     }
   return true;
 }
void CTrajAdaptiveSA::start (const CState * initialState) virtual
This instructs the method to prepare for integration starting with the initialState given.
Parameters
const CState * initialState
Reimplemented from CTrajectoryMethod.
Definition at line 194 of file CTrajAdaptiveSA.cpp.
References CVectorCore< CType >::array(), CCopasiVector< T >::begin(), CStateTemplate::beginIndependent(), CState::beginIndependent(), CCopasiObject::buildUpdateSequence(), C_FLOAT64, C_INT32, C_INVALID_INDEX, calculateAmu(), CModel::deterministic, CCopasiVector< T >::end(), CStateTemplate::endFixed(), CStateTemplate::getIndex(), CModel::getMetabolitesX(), CCopasiProblem::getModel(), CModel::getModelType(), CModel::getNumDependentReactionMetabs(), CModel::getNumIndependentReactionMetabs(), CModel::getReactions(), CModel::getState(), CModel::getStateTemplate(), CModelEntity::getStatus(), CState::getTime(), CCopasiParameter::getValue(), CCopasiObject::getValuePointer(), CModelEntity::getValueReference(), CRandom::initialize(), mA0, mAmu, mAvgDX, mDoCorrection, mEpsilon, mFirstReactionSpeciesIndex, mMaxReactionFiring, mMaxSteps, mMaxStepsReached, mMethodState, mNextReactionIndex, mNextReactionTime, mNumReactions, mNumReactionSpecies, mNumSpecies, mPartitionedAmu, mPartitionedDependencies, mPartitionedReactionFiring, CTrajectoryMethod::mpCurrentState, mpMethodSpecies, mpModel, CTrajectoryMethod::mpProblem, mpRandomGenerator, mReactionDependencies, mReactionFiring, mSigDX, mSpeciesAfterTau, mSSAStepCounter, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pUINT, CModelEntity::REACTIONS, CVector< CType >::resize(), CModel::setState(), CCopasiVector< T >::size(), and CModel::updateSimulatedValues().
 {
   /* get configuration data */
   mMaxSteps = * getValue("Max Internal Steps").pINT;
   mEpsilon = * getValue("Epsilon").pDOUBLE;
   bool useRandomSeed = * getValue("Use Random Seed").pBOOL;
   unsigned C_INT32 randomSeed = * getValue("Random Seed").pUINT;
   if (useRandomSeed) mpRandomGenerator->initialize(randomSeed);
   //mpCurrentState is initialized. This state is not used internally in the
   //stochastic solver, but it is used for returning the result after each step.
   *mpCurrentState = *initialState;
   mpModel = mpProblem->getModel();
   assert(mpModel);
   if (mpModel->getModelType() == CModel::deterministic)
     mDoCorrection = true;
   else
     mDoCorrection = false;
   //initialize the vector of ints that contains the particle numbers
   //for the discrete simulation. This also floors all particle numbers in the model.
   mNumReactions = mpModel->getReactions().size();
   mNumSpecies = mpModel->getMetabolitesX().size();
   mPartitionedDependencies.resize(mNumReactions);
   mMaxReactionFiring.resize(mNumReactions);
   mPartitionedAmu.resize(mNumReactions);
   mReactionFiring.resize(mNumReactions);
   mPartitionedReactionFiring.resize(mNumReactions);
   mReactionDependencies.resize(mNumReactions);
   mAmu.resize(mNumReactions);
   mAmu = 0.0;
   mNumReactionSpecies = mpModel->getNumIndependentReactionMetabs() + mpModel->getNumDependentReactionMetabs();
   mSpeciesAfterTau.resize(mNumReactionSpecies);
   mAvgDX.resize(mNumReactionSpecies);
   mSigDX.resize(mNumReactionSpecies);
   // Initialize the
   // Create a local copy of the state where the particle number are rounded to integers
   mMethodState = mpModel->getState();
   const CStateTemplate & StateTemplate = mpModel->getStateTemplate();
   CModelEntity *const* ppEntity = StateTemplate.beginIndependent();
   CModelEntity *const* endEntity = StateTemplate.endFixed();
   C_FLOAT64 * pValue = mMethodState.beginIndependent();
   mFirstReactionSpeciesIndex = 0;
   size_t Index = 1;
   C_FLOAT64 * pSpeciesAfterTau = mSpeciesAfterTau.array();
   for (; ppEntity != endEntity; ++ppEntity, ++pValue, ++Index)
     {
       if (dynamic_cast< const CMetab * >(*ppEntity) != NULL)
         {
           *pValue = floor(*pValue + 0.5);
           if ((*ppEntity)->getStatus() == CModelEntity::REACTIONS &&
               (*ppEntity)->isUsed())
             {
               *pSpeciesAfterTau = *pValue;
               pSpeciesAfterTau++;
               if (mFirstReactionSpeciesIndex == 0)
                 {
                   mFirstReactionSpeciesIndex = Index;
                   mpMethodSpecies = pValue;
                 }
             }
         }
     }
   // Update the model state so that the species are all represented by integers.
   mpModel->setState(mMethodState);
   mpModel->updateSimulatedValues(false); //for assignments
   // TODO handle species of type ASSIGNMENT.
   // These need to be checked whether they are sufficiently close to an integer
   C_FLOAT64 * pMethodStateValue = mMethodState.beginIndependent() - 1;
   // Build the reaction dependencies
   size_t NumReactions = 0;
   CCopasiVector< CReaction >::const_iterator it = mpModel->getReactions().begin();
   CCopasiVector< CReaction >::const_iterator end = mpModel->getReactions().end();
   std::vector< CReactionDependencies >::iterator itDependencies = mReactionDependencies.begin();
   for (; it  != end; ++it)
     {
       const CCopasiVector<CChemEqElement> & Balances = (*it)->getChemEq().getBalances();
       const CCopasiVector<CChemEqElement> & Substrates = (*it)->getChemEq().getSubstrates();
       // This reactions does not change anything we ignore it
       if (Balances.size() == 0 && Substrates.size() == 0)
         {
           continue;
         }
       itDependencies->mpParticleFlux = (C_FLOAT64 *)(*it)->getParticleFluxReference()->getValuePointer();
       itDependencies->mMethodSpeciesIndex.resize(Balances.size());
       itDependencies->mSpeciesMultiplier.resize(Balances.size());
       itDependencies->mMethodSpecies.resize(Balances.size());
       itDependencies->mModelSpecies.resize(Balances.size());
       std::set< const CCopasiObject * > changed;
       // The time is always updated
       changed.insert(mpModel->getValueReference());
       CCopasiVector< CChemEqElement >::const_iterator itBalance = Balances.begin();
       CCopasiVector< CChemEqElement >::const_iterator endBalance = Balances.end();
       size_t Index = 0;
       for (; itBalance != endBalance; ++itBalance)
         {
           const CMetab * pMetab = (*itBalance)->getMetabolite();
           if (pMetab->getStatus() == CModelEntity::REACTIONS)
             {
               itDependencies->mMethodSpeciesIndex[Index] = StateTemplate.getIndex(pMetab) - mFirstReactionSpeciesIndex;
               itDependencies->mSpeciesMultiplier[Index] = floor((*itBalance)->getMultiplicity() + 0.5);
               itDependencies->mMethodSpecies[Index] = pMethodStateValue + StateTemplate.getIndex(pMetab);
               itDependencies->mModelSpecies[Index] = (C_FLOAT64 *) pMetab->getValueReference()->getValuePointer();
               changed.insert(pMetab->getValueReference());
               Index++;
             }
         }
       // Correct allocation for metabolites which are not determined by reactions
       itDependencies->mMethodSpeciesIndex.resize(Index, true);
       itDependencies->mSpeciesMultiplier.resize(Index, true);
       itDependencies->mMethodSpecies.resize(Index, true);
       itDependencies->mModelSpecies.resize(Index, true);
       itDependencies->mSubstrateMultiplier.resize(Substrates.size());
       itDependencies->mMethodSubstrates.resize(Substrates.size());
       itDependencies->mModelSubstrates.resize(Substrates.size());
       CCopasiVector< CChemEqElement >::const_iterator itSubstrate = Substrates.begin();
       CCopasiVector< CChemEqElement >::const_iterator endSubstrate = Substrates.end();
       Index = 0;
       for (; itSubstrate != endSubstrate; ++itSubstrate, ++Index)
         {
           const CMetab * pMetab = (*itSubstrate)->getMetabolite();
           itDependencies->mSubstrateMultiplier[Index] = floor((*itSubstrate)->getMultiplicity() + 0.5);
           itDependencies->mMethodSubstrates[Index] = pMethodStateValue + StateTemplate.getIndex(pMetab);
           itDependencies->mModelSubstrates[Index] = (C_FLOAT64 *) pMetab->getValueReference()->getValuePointer();
         }
       std::set< const CCopasiObject * > dependend;
       CCopasiVector< CReaction >::const_iterator itReaction = mpModel->getReactions().begin();
       itDependencies->mDependentReactions.resize(mNumReactions);
       Index = 0;
       size_t Count = 0;
       for (; itReaction != end; ++itReaction, ++Index)
         {
           if ((*itReaction)->getParticleFluxReference()->dependsOn(changed))
             {
               dependend.insert((*itReaction)->getParticleFluxReference());
               itDependencies->mDependentReactions[Count] = Index;
               Count++;
             }
         }
       itDependencies->mDependentReactions.resize(Count, true);
       itDependencies->mCalculations = CCopasiObject::buildUpdateSequence(dependend, changed);
       ++itDependencies;
       ++NumReactions;
     }
   mNumReactions = NumReactions;
   mReactionDependencies.resize(mNumReactions);
   mAmu.resize(mNumReactions, true);
   mA0 = 0;
   size_t i;
   for (i = 0; i < mNumReactions; i++)
     {
       mA0 += calculateAmu(i);
     }
   mMaxStepsReached = false;
   mNextReactionTime = mpCurrentState->getTime();
   mNextReactionIndex = C_INVALID_INDEX;
   mSSAStepCounter = 0;
   return;
 }
CTrajectoryMethod::Status CTrajAdaptiveSA::step (const double & deltaT) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
Returns
Status status
Reimplemented from CTrajectoryMethod.
Definition at line 162 of file CTrajAdaptiveSA.cpp.
References C_FLOAT64, doSingleSSAStep(), doSingleTauLeapStep(), CCopasiMessage::EXCEPTION, CCopasiProblem::getModel(), CModel::getState(), CState::getTime(), MCTrajectoryMethod, mMaxSteps, CTrajectoryMethod::mpCurrentState, CTrajectoryMethod::mpProblem, mSSAStepCounter, CTrajectoryMethod::NORMAL, and CState::setTime().
 {
   // do several steps
   C_FLOAT64 Time = mpCurrentState->getTime();
   C_FLOAT64 EndTime = Time + deltaT;
   size_t Steps = 0;
   while (Time < EndTime)
     {
       if (mSSAStepCounter > 0)
         {
           Time += doSingleSSAStep(Time, EndTime);
           mSSAStepCounter--;
         }
       else
         {
           Time += doSingleTauLeapStep(Time, EndTime);
         }
       if (++Steps > mMaxSteps)
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 12);
         }
     }
   *mpCurrentState = mpProblem->getModel()->getState();
   mpCurrentState->setTime(Time);
   return NORMAL;
 }
Friends And Related Function Documentation
CTrajectoryMethod* CTrajectoryMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
C_FLOAT64 CTrajAdaptiveSA::mA0 protected
Total propensity (sum over mAmu[i])
Definition at line 337 of file CTrajAdaptiveSA.h.
Referenced by doSingleSSAStep(), doSingleTauLeapStep(), and start().
CVector< C_FLOAT64 > CTrajAdaptiveSA::mAmu protected
A vector of reaction propensities
Definition at line 312 of file CTrajAdaptiveSA.h.
Referenced by calculateAmu(), doSingleSSAStep(), doSingleTauLeapStep(), and start().
CVector< C_FLOAT64 > CTrajAdaptiveSA::mAvgDX private
The mean and variance of species
Definition at line 233 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
bool CTrajAdaptiveSA::mDoCorrection protected
A boolean flag indicating whether correction for higher order reactions need to be applied
Definition at line 302 of file CTrajAdaptiveSA.h.
Referenced by calculateAmu(), and start().
C_FLOAT64 CTrajAdaptiveSA::mEpsilon private
The tolerance ratio x(t+t')< eps*x(t)
Definition at line 212 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
size_t CTrajAdaptiveSA::mFirstReactionSpeciesIndex private
The Ordered reaction
Definition at line 257 of file CTrajAdaptiveSA.h.
Referenced by start().
CVector< size_t > CTrajAdaptiveSA::mMaxReactionFiring private
The upper fires of the j-th reactions
Definition at line 222 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
unsigned C_INT32 CTrajAdaptiveSA::mMaxSteps protected
max number of single stochastic steps to do in one step()
Definition at line 287 of file CTrajAdaptiveSA.h.
Referenced by start(), and step().
bool CTrajAdaptiveSA::mMaxStepsReached protected
A boolean flag indicating whether the maximum steps have been reached. This is used to avoid multiple messages.
Definition at line 343 of file CTrajAdaptiveSA.h.
Referenced by start().
CState CTrajAdaptiveSA::mMethodState protected
The method internal state which contains particle rounded particle numbers.
Definition at line 322 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
size_t CTrajAdaptiveSA::mNextReactionIndex protected
The index of the next reaction which fires
Definition at line 297 of file CTrajAdaptiveSA.h.
Referenced by doSingleSSAStep(), and start().
C_FLOAT64 CTrajAdaptiveSA::mNextReactionTime protected
The time the next reaction fires
Definition at line 292 of file CTrajAdaptiveSA.h.
Referenced by doSingleSSAStep(), and start().
size_t CTrajAdaptiveSA::mNumReactions protected
The particle and reaction numbers
Definition at line 282 of file CTrajAdaptiveSA.h.
Referenced by doSingleSSAStep(), doSingleTauLeapStep(), and start().
size_t CTrajAdaptiveSA::mNumReactionSpecies protected
Number of variable metabolites.
Definition at line 307 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
size_t CTrajAdaptiveSA::mNumSpecies protected
Definition at line 282 of file CTrajAdaptiveSA.h.
Referenced by start().
CVector< const C_FLOAT64 * > CTrajAdaptiveSA::mPartitionedAmu protected
The ordered propensity function
Definition at line 317 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
CVector< const CReactionDependencies * > CTrajAdaptiveSA::mPartitionedDependencies protected
The Ordered reaction
Definition at line 332 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
CVector< C_FLOAT64 * > CTrajAdaptiveSA::mPartitionedReactionFiring private
Definition at line 228 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
C_FLOAT64* CTrajAdaptiveSA::mpMethodSpecies private
The species pointer for average, variance, and population (ordered)
Definition at line 242 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
CModel* CTrajAdaptiveSA::mpModel protected
A pointer to the instance of CModel being used.
Definition at line 277 of file CTrajAdaptiveSA.h.
Referenced by doSingleSSAStep(), doSingleTauLeapStep(), and start().
CRandom* CTrajAdaptiveSA::mpRandomGenerator protected
The random number generator
Definition at line 272 of file CTrajAdaptiveSA.h.
Referenced by doSingleSSAStep(), doSingleTauLeapStep(), start(), and ~CTrajAdaptiveSA().
std::vector< CReactionDependencies > CTrajAdaptiveSA::mReactionDependencies protected
A vector containing dependency information to minimize the required updates.
Definition at line 327 of file CTrajAdaptiveSA.h.
Referenced by calculateAmu(), doSingleSSAStep(), doSingleTauLeapStep(), and start().
CVector< C_FLOAT64 > CTrajAdaptiveSA::mReactionFiring private
The number of fires
Definition at line 227 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
CVector< C_FLOAT64 > CTrajAdaptiveSA::mSigDX private
Definition at line 234 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
CVector< C_FLOAT64 > CTrajAdaptiveSA::mSpeciesAfterTau private
The temporary species
Definition at line 247 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), and start().
C_FLOAT64 CTrajAdaptiveSA::mSSAStepCounter private
The counter to count the time of doing single SSA
Definition at line 217 of file CTrajAdaptiveSA.h.
Referenced by doSingleTauLeapStep(), start(), and step().
std::vector< Refresh * > CTrajAdaptiveSA::mTauCalculations private
Vector of refresh methods which need to be executed to update all values required for simulation
Definition at line 252 of file CTrajAdaptiveSA.h.
The documentation for this class was generated from the following files:
CTrajAdaptiveSA.h
CTrajAdaptiveSA.cpp