COPASI API: CBitPatternMethod Class Reference
CBitPatternMethod Class Reference
#include <CBitPatternMethod.h>
Public Member Functions
virtual bool calculate ()
CBitPatternMethod (const CBitPatternMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool initialize ()
~CBitPatternMethod ()
Public Member Functions inherited from CEFMMethod
CEFMMethod (const CEFMMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual ~CEFMMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static bool CalculateKernel (CMatrix< C_INT64 > &matrix, CMatrix< C_INT64 > &kernel, CVector< size_t > &rowPivot)
static void GCD (C_INT64 &m, C_INT64 &n)
Static Public Member Functions inherited from CEFMMethod
static CEFMMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::EFMAlgorithm)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
CBitPatternMethod (const CCopasiContainer *pParent=NULL)
CBitPatternMethod (const CCopasiMethod::SubType subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CEFMMethod
CEFMMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
bool mContinueCombination
CMatrix< C_INT64 > mExpandedStoiTranspose
size_t mhProgressCounter
size_t mhProgressCounter2
size_t mMinimumSetSize
std::vector< CStepMatrixColumn * > mNewColumns
CModel * mpModel
unsigned C_INT32 mProgressCounter
unsigned C_INT32 mProgressCounter2
unsigned C_INT32 mProgressCounter2Max
unsigned C_INT32 mProgressCounterMax
CStepMatrix * mpStepMatrix
std::vector< std::pair< size_t,
bool > > mReactionForward
CVector< size_t > mReactionPivot
size_t mStep
Protected Attributes inherited from CEFMMethod
std::vector< CFluxMode > * mpFluxModes
std::vector< const CReaction * > * mpReorderedReactions
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void addMode (const CFluxMode &mode)
void buildFluxModeMatrix (CStepMatrix *fluxModeMatrix, std::stack< CStepMatrixColumn * > kernelStack)
void buildFluxModes ()
void buildKernelMatrix (CMatrix< C_INT64 > &kernel)
void combine (const CStepMatrixColumn *pPositive, const CStepMatrixColumn *pNegative, const std::vector< CStepMatrixColumn * > NullColumns)
void findRemoveInvalidColumns (const std::vector< CStepMatrixColumn * > &nullColumns)
void getAllUnsetBitIndexes (const CStepMatrixColumn *pColumn, CVector< size_t > &indexes) const
void getUnsetBitIndexes (const CStepMatrixColumn *pColumn, CVector< size_t > &indexes) const
void initObjects ()
CMatrix< C_INT64 > performRankTest (CStepMatrixColumn *pIntersectColumn)
Friends
CEFMMethod * CEFMMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 34 of file CBitPatternMethod.h.
Constructor & Destructor Documentation
CBitPatternMethod::CBitPatternMethod (const CCopasiContainer * pParent = NULL) protected
Default constructor
Parameters
const CCopasiContainer * pParent (Default: NULL)
Definition at line 27 of file CBitPatternMethod.cpp.
References initObjects().
                                                                     :
   CEFMMethod(CCopasiTask::fluxMode, CCopasiMethod::EFMBitPatternAlgorithm, pParent),
   mpModel(NULL),
   mProgressCounter(0),
   mProgressCounterMax(0),
   mhProgressCounter(0),
   mProgressCounter2(0),
   mProgressCounter2Max(0),
   mhProgressCounter2(0),
   mReactionForward(),
   mReactionPivot(0),
   mExpandedStoiTranspose(0, 0),
   mpStepMatrix(NULL),
   mMinimumSetSize(0),
   mStep(0),
   mContinueCombination(true)
 {
   initObjects();
 }
CBitPatternMethod::CBitPatternMethod (const CCopasiMethod::SubType subType, const CCopasiContainer * pParent = NULL) protected
Constructor to be called by derived methods
Parameters
const CCopasiMethod::SubType subType
const CCopasiContainer * pParent (Default: NULL)
Definition at line 47 of file CBitPatternMethod.cpp.
References initObjects().
                                                                       :
   CEFMMethod(CCopasiTask::fluxMode, subType, pParent),
   mpModel(NULL),
   mProgressCounter(0),
   mProgressCounterMax(0),
   mhProgressCounter(0),
   mProgressCounter2(0),
   mProgressCounter2Max(0),
   mhProgressCounter2(0),
   mReactionForward(),
   mReactionPivot(0),
   mExpandedStoiTranspose(0, 0),
   mpStepMatrix(NULL),
   mMinimumSetSize(0),
   mStep(0),
   mContinueCombination(true)
 {
   initObjects();
 }
CBitPatternMethod::CBitPatternMethod (const CBitPatternMethod & src, const CCopasiContainer * pParent = NULL)
Copy Constructor
Parameters
const CBitPatternMethod & src
Definition at line 68 of file CBitPatternMethod.cpp.
References initObjects().
                                                                       :
   CEFMMethod(src, pParent),
   mpModel(src.mpModel),
   mProgressCounter(src.mProgressCounter),
   mProgressCounterMax(src.mProgressCounterMax),
   mhProgressCounter(src.mhProgressCounter),
   mProgressCounter2(src.mProgressCounter2),
   mProgressCounter2Max(src.mProgressCounter2Max),
   mhProgressCounter2(src.mhProgressCounter2),
   mReactionForward(src.mReactionForward),
   mReactionPivot(src.mReactionPivot),
   mExpandedStoiTranspose(src.mExpandedStoiTranspose),
   mpStepMatrix(src.mpStepMatrix),
   mMinimumSetSize(src.mMinimumSetSize),
   mStep(src.mStep),
   mContinueCombination(src.mContinueCombination)
 {
   initObjects();
 }
CBitPatternMethod::~CBitPatternMethod ()
Destructor
Definition at line 89 of file CBitPatternMethod.cpp.
 {
 }
Member Function Documentation
void CBitPatternMethod::addMode (const CFluxMode & mode) private
Add the flux mode to the list only if the reversed does not exist
Parameters
const CFluxMode & mode
Definition at line 650 of file CBitPatternMethod.cpp.
References CEFMMethod::mpFluxModes.
Referenced by buildFluxModes().
 {
   std::vector< CFluxMode >::iterator itMode = mpFluxModes->begin();
   std::vector< CFluxMode >::iterator endMode = mpFluxModes->end();
   for (; itMode != endMode; ++itMode)
     {
       if (itMode->isReversed(mode))
         {
           return;
         }
     }
   mpFluxModes->push_back(mode);
   return;
 }
void CBitPatternMethod::buildFluxModeMatrix (CStepMatrix * fluxModeMatrix, std::stack< CStepMatrixColumn * > kernelStack) private
Definition at line 955 of file CBitPatternMethod.cpp.
References CStepMatrix::add(), CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), performRankTest(), and CStepMatrixColumn::push_front().
 {
   CStepMatrixColumn * KernelCol;
   unsigned int col, row;
   while (!kernelStack.empty())
     {
       KernelCol = kernelStack.top();
 #ifdef COPASI_DEBUG_TRACE
       DebugFile << "Current Column: " << *KernelCol << std::endl;
 #endif // COPASI_DEBUG_TRACE
       CMatrix<C_INT64> RankKernel = performRankTest(KernelCol);
 #ifdef COPASI_DEBUG_TRACE
       DebugFile << "New Rank Kernel " << RankKernel << std::endl;
 #endif // COPASI_DEBUG_TRACE
       if (RankKernel.numCols() == 1)
         {
           fluxModeMatrix->add(KernelCol);
         }
       else if (RankKernel.numCols() > 1)
         {
           for (col = 0; col < RankKernel.numCols(); col++)
             {
               KernelCol = new CStepMatrixColumn(RankKernel.numRows());
               for (row = 0; row < RankKernel.numRows(); row++)
                 {
                   KernelCol->push_front(RankKernel(row, col));
                 }
               kernelStack.push(KernelCol);
             }
         }
       kernelStack.pop();
     }
 }
void CBitPatternMethod::buildFluxModes () private
Postprocess the step matrix to construct the flux modes.
Definition at line 423 of file CBitPatternMethod.cpp.
References addMode(), CVectorCore< CType >::array(), CMatrix< CType >::array(), CStepMatrix::begin(), C_FLOAT64, C_INT64, CalculateKernel(), CStepMatrix::end(), getUnsetBitIndexes(), mExpandedStoiTranspose, CEFMMethod::mpReorderedReactions, mpStepMatrix, mReactionForward, CMatrix< CType >::numCols(), and CVectorCore< CType >::size().
Referenced by calculate().
 {
   CStepMatrix::const_iterator it = mpStepMatrix->begin();
   CStepMatrix::const_iterator end = mpStepMatrix->end();
   CVector< size_t > Indexes;
   size_t NumSpecies = mExpandedStoiTranspose.numCols();
   for (; it != end; ++it)
     {
       getUnsetBitIndexes(*it, Indexes);
       size_t NumReactions = Indexes.size();
       // Remove trivial modes, i.e., reversible reactions
       if (NumReactions == 2 &&
           (*mpReorderedReactions)[mReactionForward[Indexes[0]].first] ==
           (*mpReorderedReactions)[mReactionForward[Indexes[1]].first])
         {
           continue;
         }
       // Build the stoichiometry matrix reduced to the reactions participating in the current mode.
       CMatrix< C_INT64 > A(NumReactions, NumSpecies);
       size_t * pIndex = Indexes.array();
       size_t * pIndexEnd = pIndex + NumReactions;
       C_INT64 * pARow = A.array();
       for (; pIndex != pIndexEnd; ++pIndex, pARow += NumSpecies)
         {
           memcpy(pARow, &mExpandedStoiTranspose(*pIndex, 0), NumSpecies * sizeof(C_INT64));
         }
       // Calculate the kernel of the matrix
       CMatrix< C_INT64 > ExpandedStoiTranspose(A);
       CMatrix< C_INT64 > Kernel;
       CVector< size_t > Pivot;
       CalculateKernel(ExpandedStoiTranspose, Kernel, Pivot);
       size_t NumCols = Kernel.numCols();
       // Now we create the flux mode as we have the multiplier and reaction indexes.
       // We need to invert the sign of the multiplier for reactions which are not forward.
       // A flux mode is reversible if all reactions are reversible;
       C_INT64 * pColumn = Kernel.array();
       C_INT64 * pColumnEnd = pColumn + NumCols;
       for (; pColumn != pColumnEnd; ++pColumn)
         {
           std::map< size_t, C_FLOAT64 > Reactions;
           bool Reversible = true;
           pIndex = Indexes.array();
           C_INT64 * pFluxMultiplier = pColumn;
           for (; pIndex != pIndexEnd; ++pIndex, pFluxMultiplier += NumCols)
             {
               if (*pFluxMultiplier < 0)
                 {
                   break;
                 }
               else if (*pFluxMultiplier < 0)
                 {
                   continue;
                 }
               std::pair< size_t, bool > & ReactionForward = mReactionForward[*pIndex];
               Reactions[ReactionForward.first] =
                 (C_FLOAT64)((ReactionForward.second == true) ? *pFluxMultiplier : -*pFluxMultiplier);
               if (!(*mpReorderedReactions)[ReactionForward.first]->isReversible())
                 {
                   Reversible = false;
                 }
             }
           if (pIndex != pIndexEnd)
             {
               continue;
             }
           addMode(CFluxMode(Reactions, Reversible));
         }
     }
 }
void CBitPatternMethod::buildKernelMatrix (CMatrix< C_INT64 > & kernel) private
Construct the kernel matrix
Parameters
CMatrix< C_FLOAT64> & kernel
Definition at line 343 of file CBitPatternMethod.cpp.
References CMatrix< CType >::array(), CCopasiVector< T >::begin(), C_FLOAT64, C_INT64, CalculateKernel(), CCopasiVector< T >::end(), CModel::getReactions(), CModel::getRedStoi(), mExpandedStoiTranspose, min, mpModel, CEFMMethod::mpReorderedReactions, mReactionForward, mReactionPivot, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CMatrix< CType >::resize(), and CMatrix< CType >::size().
Referenced by initialize().
 {
   // Calculate the kernel matrix
   // of the reduced stoichiometry matrix to get the kernel matrix for the:
   //   Nullspace Approach to Determine the Elementary Modes of Chemical Reaction Systems (Wagner 2004)
   CCopasiVector< CReaction >::const_iterator itReaction = mpModel->getReactions().begin();
   CCopasiVector< CReaction >::const_iterator endReaction = mpModel->getReactions().end();
   size_t ReactionCounter = 0;
   for (; itReaction != endReaction; ++itReaction, ++ReactionCounter)
     {
       if ((*itReaction)->isReversible())
         {
           // mpReorderedReactons->push_back(*itReaction);
           mReactionForward.push_back(std::make_pair(ReactionCounter, false));
         }
       mpReorderedReactions->push_back(*itReaction);
       mReactionForward.push_back(std::make_pair(ReactionCounter, true));
     }
   const CMatrix< C_FLOAT64 > & Stoi = mpModel->getRedStoi();
   size_t NumReactions = Stoi.numCols();
   size_t NumExpandedReactions = mReactionForward.size();
   size_t NumSpecies = Stoi.numRows();
   size_t Dim = std::min(NumExpandedReactions, NumSpecies);
   if (Dim == 0)
     {
       return;
     }
   mExpandedStoiTranspose.resize(NumExpandedReactions, NumSpecies);
   const C_FLOAT64 *pStoi = Stoi.array();
   const C_FLOAT64 *pStoiEnd = pStoi + Stoi.size();
   const C_FLOAT64 *pStoiRowEnd;
   C_INT64 *pExpandedStoiTranspose;
   C_INT64 *pExpandedStoiTransposeColumn = mExpandedStoiTranspose.array();
   std::vector< const CReaction * >::const_iterator itReactionPivot;
   std::vector< const CReaction * >::const_iterator endReactionPivot;
   std::vector< std::pair< size_t, bool > >::const_iterator itReactionExpansion;
   for (; pStoi != pStoiEnd; ++pExpandedStoiTransposeColumn)
     {
       pStoiRowEnd = pStoi + NumReactions;
       pExpandedStoiTranspose = pExpandedStoiTransposeColumn;
       itReactionExpansion = mReactionForward.begin();
       for (; pStoi < pStoiRowEnd; ++pStoi, pExpandedStoiTranspose += NumSpecies, ++itReactionExpansion)
         {
           // TODO We should check the we have integer stoichiometry.
           if (itReactionExpansion->second == false)
             {
               *pExpandedStoiTranspose = (C_INT64) - floor(*pStoi + 0.5);
               // Advance the iterators
               ++itReactionExpansion;
               pExpandedStoiTranspose += NumSpecies;
             }
           *pExpandedStoiTranspose = (C_INT64) floor(*pStoi + 0.5);
         }
     }
   // Calculate the kernel of the matrix
   CMatrix< C_INT64 > ExpandedStoiTranspose(mExpandedStoiTranspose);
   CalculateKernel(ExpandedStoiTranspose, kernelInt, mReactionPivot);
   return;
 }
bool CBitPatternMethod::calculate (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback. @ return success;
Reimplemented from CEFMMethod.
Definition at line 165 of file CBitPatternMethod.cpp.
References CProcessReport::addItem(), buildFluxModes(), C_INT32, combine(), CStepMatrix::compact(), CStepMatrix::convertRow(), findRemoveInvalidColumns(), CProcessReport::finishItem(), CStepMatrix::getFirstUnconvertedRow(), CStepMatrix::getNumUnconvertedRows(), initialize(), mContinueCombination, mhProgressCounter, mhProgressCounter2, CCopasiMethod::mpCallBack, mProgressCounter, mProgressCounter2, mProgressCounter2Max, mProgressCounterMax, mpStepMatrix, mStep, CProcessReport::progressItem(), CStepMatrix::removeInvalidColumns(), and CStepMatrix::splitColumns().
 {
   bool Continue = true;
   if (!initialize())
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhProgressCounter);
       return false;
     }
   while (mpStepMatrix->getNumUnconvertedRows() > 0 &&
          Continue)
     {
       mStep = mpStepMatrix->getFirstUnconvertedRow();
       std::vector< CStepMatrixColumn * > PositiveColumns;
       std::vector< CStepMatrixColumn * > NegativeColumns;
       std::vector< CStepMatrixColumn * > NullColumns;
       if (mpStepMatrix->splitColumns(PositiveColumns,
                                      NegativeColumns,
                                      NullColumns))
         {
           // Process each step.
           // Iterate over all combinations and add/remove columns to the step matrix
           mProgressCounter2 = 0;
           mProgressCounter2Max = (unsigned C_INT32)(PositiveColumns.size() * NegativeColumns.size());
           if (mpCallBack)
             mhProgressCounter2 =
               mpCallBack->addItem("Combinations",
                                   mProgressCounter2,
                                   & mProgressCounter2Max);
           for (unsigned int i = 0; i < NegativeColumns.size(); i++)
             for (unsigned int j = 0; j < PositiveColumns.size(); j++)
               combine(PositiveColumns[j], NegativeColumns[i], NullColumns);
           if (mpCallBack)
             mpCallBack->finishItem(mhProgressCounter2);
           Continue &= mContinueCombination;
           if (Continue)
             {
               // We can now destroy all negative columns, which removes them from
               // the step matrix.
               mpStepMatrix->removeInvalidColumns(NegativeColumns);
               // Remove columns of the step matrix which are no longer extreme rays.
               findRemoveInvalidColumns(NullColumns);
               // We compact the step matrix which has empty columns due to the removal of columns above.
               mpStepMatrix->compact();
               // Now we can convert the processed row.
               mpStepMatrix->convertRow();
             }
         }
       mProgressCounter = mProgressCounterMax - (unsigned C_INT32) mpStepMatrix->getNumUnconvertedRows();
       if (mpCallBack)
         Continue &= mpCallBack->progressItem(mhProgressCounter);
     }
   if (Continue)
     {
       buildFluxModes();
     }
   if (mpCallBack)
     Continue &= mpCallBack->finishItem(mhProgressCounter);
   return true;
 }
bool CBitPatternMethod::CalculateKernel (CMatrix< C_INT64 > & matrix, CMatrix< C_INT64 > & kernel, CVector< size_t > & rowPivot) static
A static method that calculates the kernel of a full column rank matrix. Note, the input matrix is used as work area and will be modified during the calculation.
Parameters
const CMatrix< C_INT64 > & matrix
CMatrix< C_INT64 > & kernel
CVector< size_t > & rowPivot
Returns
bool success
Definition at line 668 of file CBitPatternMethod.cpp.
References abs64, CVectorCore< CType >::array(), CMatrix< CType >::array(), C_FLOAT64, C_INT64, GCD(), max, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CMatrix< CType >::resize(), CVector< CType >::resize(), and CMatrix< CType >::size().
Referenced by buildFluxModes(), buildKernelMatrix(), and performRankTest().
 {
   // Gaussian elimination
   size_t NumRows = matrix.numRows();
   size_t NumCols = matrix.numCols();
   assert(NumRows > 0);
   assert(NumCols > 0);
   // Initialize row pivots
   rowPivot.resize(NumRows);
   size_t * pPivot = rowPivot.array();
   for (size_t i = 0; i < NumRows; i++, pPivot++)
     {
       *pPivot = i;
     }
   CVector< size_t > RowPivot(rowPivot);
   CVector< C_INT64 > Identity(NumRows);
   Identity = 1;
   C_INT64 * pColumn = matrix.array();
   C_INT64 * pColumnEnd = pColumn + NumCols;
   C_INT64 * pActiveRow;
   C_INT64 * pActiveRowStart = pColumn;
   C_INT64 * pActiveRowEnd = pColumnEnd;
   C_INT64 * pRow;
   C_INT64 * pRowEnd = pColumn + matrix.size();
   C_INT64 * pCurrent;
   C_INT64 * pIdentity;
   CVector< C_INT64 > SwapTmp(NumCols);
   size_t CurrentRowIndex = 0;
   size_t CurrentColumnIndex = 0;
   size_t NonZeroIndex = 0;
   CVector< bool > IgnoredColumns(NumCols);
   IgnoredColumns = false;
   bool * pIgnoredColumn = IgnoredColumns.array();
   size_t IgnoredColumnCount = 0;
   // For each column
   for (; pColumn < pColumnEnd; ++pColumn, ++CurrentColumnIndex, ++pIgnoredColumn)
     {
       assert(CurrentColumnIndex == CurrentRowIndex + IgnoredColumnCount);
       // Find non zero entry in current column.
       pRow = pActiveRowStart + CurrentColumnIndex;
       NonZeroIndex = CurrentRowIndex;
       for (; pRow < pRowEnd; pRow += NumCols, ++NonZeroIndex)
         {
           if (*pRow != 0)
             break;
         }
       if (NonZeroIndex >= NumRows)
         {
           *pIgnoredColumn = true;
           IgnoredColumnCount++;
           continue;
         }
       if (NonZeroIndex != CurrentRowIndex)
         {
           // Swap rows
           memcpy(SwapTmp.array(), matrix[CurrentRowIndex], NumCols * sizeof(C_INT64));
           memcpy(matrix[CurrentRowIndex], matrix[NonZeroIndex], NumCols * sizeof(C_INT64));
           memcpy(matrix[NonZeroIndex], SwapTmp.array(), NumCols * sizeof(C_INT64));
           // Record pivot
           size_t tmp = RowPivot[CurrentRowIndex];
           RowPivot[CurrentRowIndex] = RowPivot[NonZeroIndex];
           RowPivot[NonZeroIndex] = tmp;
           C_INT64 TMP = Identity[CurrentRowIndex];
           Identity[CurrentRowIndex]  = Identity[NonZeroIndex];
           Identity[NonZeroIndex] = TMP;
         }
       if (*(pActiveRowStart + CurrentColumnIndex) < 0)
         {
           for (pRow = pActiveRowStart; pRow < pActiveRowEnd; ++pRow)
             {
               *pRow *= -1;
             }
           Identity[CurrentRowIndex] *= -1;
         }
       // For each row
       pRow = pActiveRowStart + NumCols;
       pIdentity = Identity.array() + CurrentRowIndex + 1;
       C_INT64 ActiveRowValue = *(pActiveRowStart + CurrentColumnIndex);
       *(pActiveRowStart + CurrentColumnIndex) = Identity[CurrentRowIndex];
       for (; pRow < pRowEnd; pRow += NumCols, ++pIdentity)
         {
           C_INT64 RowValue = *(pRow + CurrentColumnIndex);
           if (RowValue == 0)
             continue;
           *(pRow + CurrentColumnIndex) = 0;
           // compute GCD(*pActiveRowStart, *pRow)
           C_INT64 GCD1 = abs64(ActiveRowValue);
           C_INT64 GCD2 = abs64(RowValue);
           GCD(GCD1, GCD2);
           C_INT64 alpha = ActiveRowValue / GCD1;
           C_INT64 beta = RowValue / GCD1;
           // update rest of row
           pActiveRow = pActiveRowStart;
           pCurrent = pRow;
           *pIdentity *= alpha;
           GCD1 = abs64(*pIdentity);
           for (; pActiveRow < pActiveRowEnd; ++pActiveRow, ++pCurrent)
             {
               // Assert that we do not have a numerical overflow.
               assert(fabs(((C_FLOAT64) alpha) * ((C_FLOAT64) * pCurrent) - ((C_FLOAT64) beta) * ((C_FLOAT64) * pActiveRow)) < std::numeric_limits< C_INT64 >::max());
               *pCurrent = alpha * *pCurrent - beta * *pActiveRow;
               // We check that the row values do not have any common divisor.
               if (GCD1 > 1 &&
                   (GCD2 = abs64(*pCurrent)) > 0)
                 {
                   GCD(GCD1, GCD2);
                 }
             }
           if (GCD1 > 1)
             {
               *pIdentity /= GCD1;
               pActiveRow = pActiveRowStart;
               pCurrent = pRow;
               for (; pActiveRow < pActiveRowEnd; ++pActiveRow, ++pCurrent)
                 {
                   *pCurrent /= GCD1;
                 }
             }
         }
       pActiveRowStart += NumCols;
       pActiveRowEnd += NumCols;
       CurrentRowIndex++;
       // DebugFile << matrix << std::endl;
       // DebugFile << Identity << std::endl;
     }
   assert(CurrentColumnIndex == CurrentRowIndex + IgnoredColumnCount);
   assert(CurrentColumnIndex == NumCols);
   // std::cout << matrix << std::endl;
   // std::cout << IgnoredColumns << std::endl;
   // std::cout << Identity << std::endl;
   // std::cout << RowPivot << std::endl << std::endl;
   size_t KernelRows = NumRows;
   size_t KernelCols = NumRows + IgnoredColumnCount - NumCols;
   assert(KernelCols > 0);
   kernel.resize(KernelRows, KernelCols);
   CMatrix< C_INT64 > Kernel(KernelRows, KernelCols);
   Kernel = 0;
   C_INT64 * pKernelInt = Kernel.array();
   C_INT64 * pKernelIntEnd = pKernelInt + Kernel.size();
   pActiveRowStart = matrix[CurrentRowIndex];
   pActiveRowEnd = matrix[NumRows];
   // Null space matrix identity part
   pIdentity = Identity.array() + CurrentRowIndex;
   C_INT64 * pKernelColumn = Kernel.array();
   for (; pActiveRowStart < pActiveRowEnd; pActiveRowStart += NumCols, ++pKernelColumn, ++pIdentity)
     {
       pKernelInt = pKernelColumn;
       pIgnoredColumn = IgnoredColumns.array();
       pRow = pActiveRowStart;
       pRowEnd = pRow + NumCols;
       if (*pIdentity < 0)
         {
           *pIdentity *= -1;
           for (; pRow < pRowEnd; ++pRow, ++pIgnoredColumn)
             {
               if (*pIgnoredColumn)
                 {
                   continue;
                 }
               *pKernelInt = - *pRow;
               pKernelInt += KernelCols;
             }
         }
       else
         {
           for (; pRow < pRowEnd; ++pRow, ++pIgnoredColumn)
             {
               if (*pIgnoredColumn)
                 {
                   continue;
                 }
               *pKernelInt = *pRow;
               pKernelInt += KernelCols;
             }
         }
     }
   pIdentity = Identity.array() + CurrentRowIndex;
   pKernelInt = Kernel[CurrentRowIndex];
   for (; pKernelInt < pKernelIntEnd; pKernelInt += KernelCols + 1, ++pIdentity)
     {
       *pKernelInt = *pIdentity;
     }
   // Undo the reordering introduced by Gaussian elimination to the kernel matrix.
   pPivot = RowPivot.array();
   pRow = Kernel.array();
   pRowEnd = pRow + Kernel.size();
   for (; pRow < pRowEnd; ++pPivot, pRow += KernelCols)
     {
       memcpy(kernel[*pPivot], pRow, KernelCols * sizeof(C_INT64));
     }
   return true;
 }
void CBitPatternMethod::combine (const CStepMatrixColumn * pPositive, const CStepMatrixColumn * pNegative, const std::vector< CStepMatrixColumn * > NullColumns) private
Create all possible linear combinations of the bit pattern nodes pPositive and pNegative and all their child nodes.
Parameters
const CBitPatternTreeNode * pPositive
const CBitPatternTreeNode * pNegative
Definition at line 245 of file CBitPatternMethod.cpp.
References CStepMatrix::addColumn(), CZeroSet::getNumberOfSetBits(), CStepMatrixColumn::getZeroSet(), CZeroSet::intersection(), CZeroSet::isExtremeRay(), mContinueCombination, mhProgressCounter2, mMinimumSetSize, mNewColumns, CCopasiMethod::mpCallBack, mProgressCounter2, mpStepMatrix, CMatrix< CType >::numCols(), performRankTest(), CProcessReport::proceed(), CProcessReport::progressItem(), and CStepMatrix::removeColumn().
Referenced by calculate().
 {
   if (mContinueCombination && mpCallBack)
     {
       mContinueCombination = mpCallBack->proceed();
     }
   if (!mContinueCombination)
     {
       return;
     }
   CZeroSet Intersection = CZeroSet::intersection(pPositive->getZeroSet(),
                           pNegative->getZeroSet());
   // Adjacency test
   if (Intersection.getNumberOfSetBits() < mMinimumSetSize)
     {
       return;
     }
   //INSERT RANK TEST HERE
   CStepMatrixColumn * RankTestColumn = new CStepMatrixColumn(Intersection, pPositive, pNegative);
   CMatrix<C_INT64> rtKernel = performRankTest(RankTestColumn);
   if (rtKernel.numCols() > 1)
     {
       return;
     }
   // Assert columns are not null
   if (pPositive != NULL && pNegative != NULL)
     {
       // We need to check whether the existing matrix contains already a leaf which is a superset
       if (Intersection.isExtremeRay(NullColumns))
         {
           // We are sure that the previous Null Tree did not contain any
           // super sets, however the new columns may.
           // We check whether the new columns do not already contain a superset
           if (Intersection.isExtremeRay(mNewColumns))
             {
               CStepMatrixColumn * pColumn = mpStepMatrix->addColumn(Intersection, pPositive, pNegative);
               // Remove all new column which are no longer extreme rays
               std::vector< CStepMatrixColumn * >::iterator it = mNewColumns.begin();
               std::vector< CStepMatrixColumn * >::iterator end = mNewColumns.end();
               for (; it != end; ++it)
                 {
                   if ((*it) != NULL &&
                       (*it)->getZeroSet() >= Intersection)
                     {
                       // We need to remove the column from the step matrix, which can be done by deleting it.
                       mpStepMatrix->removeColumn(*it);
                       *it = NULL;
                     }
                 }
               mNewColumns.push_back(pColumn);
             }
         }
       mProgressCounter2++;
       if (mpCallBack)
         mContinueCombination = mpCallBack->progressItem(mhProgressCounter2);
     }
 }
void CBitPatternMethod::findRemoveInvalidColumns (const std::vector< CStepMatrixColumn * > & nullColumns) private
Remove the invalid columns from the step matrix
Parameters
const std::vector< CStepMatrix::iterator > & nullColumns
Definition at line 318 of file CBitPatternMethod.cpp.
References mNewColumns, mpStepMatrix, and CStepMatrix::removeInvalidColumns().
Referenced by calculate().
 {
   if (mNewColumns.empty())
     {
       return;
     }
   // Determine the columns which became invalid.
   std::vector< CStepMatrixColumn * > InvalidColumns;
   std::vector< CStepMatrixColumn * >::const_iterator NullIt = nullColumns.begin();
   std::vector< CStepMatrixColumn * >::const_iterator NullEnd = nullColumns.end();
   for (; NullIt != NullEnd; ++NullIt)
     {
       if (!((*NullIt)->getZeroSet()).isExtremeRay(mNewColumns))
         {
           InvalidColumns.push_back(*NullIt);
         }
     }
   mpStepMatrix->removeInvalidColumns(InvalidColumns);
   mNewColumns.clear();
 }
static void CBitPatternMethod::GCD (C_INT64 & m, C_INT64 & n) inline static
Calculate the greatest common divisor (GCD) of 2 positive integers. On return m and n contain the GCD
Parameters
C_INT64 & m
C_INT64 & n
Definition at line 57 of file CBitPatternMethod.h.
Referenced by CalculateKernel().
   {
     assert(m > 0 && n > 0);
     while (m != n)
       {
         if (m > n)
           {
             m %= n;
             if (m == 0)
               {
                 m = n;
               }
           }
         else
           {
             n %= m;
             if (n == 0)
               {
                 n = m;
               }
           }
       }
   }
void CBitPatternMethod::getAllUnsetBitIndexes (const CStepMatrixColumn * pColumn, CVector< size_t > & indexes) const private
Definition at line 619 of file CBitPatternMethod.cpp.
References CVectorCore< CType >::array(), CStepMatrix::getAllUnsetBitIndexes(), mpStepMatrix, mReactionPivot, and CVectorCore< CType >::size().
Referenced by performRankTest().
 {
   mpStepMatrix->getAllUnsetBitIndexes(pColumn, indexes);
   // Apply the QR pivot
   size_t * pIndex = indexes.array();
   size_t * pIndexEnd = pIndex + indexes.size();
   for (; pIndex != pIndexEnd; ++pIndex)
     *pIndex = mReactionPivot[*pIndex];
   //DebugFile << "@CBPM: " << indexes << std::endl;
 }
void CBitPatternMethod::getUnsetBitIndexes (const CStepMatrixColumn * pColumn, CVector< size_t > & indexes) const private
Get the index of the unset bits of the flux mode.
Definition at line 634 of file CBitPatternMethod.cpp.
References CVectorCore< CType >::array(), CStepMatrix::getUnsetBitIndexes(), mpStepMatrix, mReactionPivot, and CVectorCore< CType >::size().
Referenced by buildFluxModes().
 {
   mpStepMatrix->getUnsetBitIndexes(pColumn, indexes);
   // Apply the QR pivot
   size_t * pIndex = indexes.array();
   size_t * pIndexEnd = pIndex + indexes.size();
   for (; pIndex != pIndexEnd; ++pIndex)
     {
       *pIndex = mReactionPivot[*pIndex];
     }
 }
bool CBitPatternMethod::initialize () virtual
Initialize arrays and pointer.
Returns
bool success
Reimplemented from CEFMMethod.
Definition at line 98 of file CBitPatternMethod.cpp.
References CProcessReport::addItem(), buildKernelMatrix(), C_INT32, CCopasiProblem::getModel(), CStepMatrix::getNumUnconvertedRows(), CCopasiObject::getObjectParent(), CCopasiTask::getProblem(), CEFMMethod::initialize(), mContinueCombination, mhProgressCounter, mMinimumSetSize, CCopasiMethod::mpCallBack, mpModel, mProgressCounter, mProgressCounterMax, mpStepMatrix, mReactionForward, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), pdelete, pTask, and CStepMatrixColumn::push_front().
Referenced by calculate().
 {
   if (!CEFMMethod::initialize())
     {
       return false;
     }
   pdelete(mpStepMatrix);
   mReactionForward.clear();
   mContinueCombination = true;
   CEFMTask * pTask = dynamic_cast< CEFMTask *>(getObjectParent());
   if (pTask == NULL) return false;
   mpModel = pTask->getProblem()->getModel();
   if (mpModel == NULL) return false;
   // We first build the kernel matrix
   CMatrix< C_INT64 > KernelMatrix;
   buildKernelMatrix(KernelMatrix);
   mMinimumSetSize = KernelMatrix.numCols() - 2;
   std::stack< CStepMatrixColumn * > KernelStack;
   CStepMatrixColumn * KernelCol;
   for (unsigned int col = 0; col < KernelMatrix.numCols(); col++)
     {
       KernelCol = new CStepMatrixColumn(KernelMatrix.numRows());
       for (unsigned int row = 0; row < KernelMatrix.numRows(); row++)
         {
           KernelCol->push_front(KernelMatrix(row, col));
         }
       KernelStack.push(KernelCol);
     }
   // Now we create the initial step matrix
   mpStepMatrix = new CStepMatrix(KernelMatrix);
   /*mpStepMatrix = new CStepMatrix(KernelMatrix.numRows());
   buildFluxModeMatrix(mpStepMatrix, KernelStack);
   DebugFile << *mpStepMatrix << std::endl;*/
   /*
   mpStepMatrix = FluxModeMatrix;
   mpStepMatrix.convertMatrix();
   */
   //mpStepMatrix = new CStepMatrix(KernelMatrix);
   mProgressCounter = 0;
   mProgressCounterMax = (unsigned C_INT32) mpStepMatrix->getNumUnconvertedRows();
   if (mpCallBack)
     mhProgressCounter =
       mpCallBack->addItem("Current Step",
                           mProgressCounter,
                           & mProgressCounterMax);
   return true;
 }
void CBitPatternMethod::initObjects () private
Initialize the needed CCopasiObjects.
Definition at line 93 of file CBitPatternMethod.cpp.
References CCopasiContainer::addObjectReference(), mProgressCounter, and CCopasiObject::ValueInt.
Referenced by CBitPatternMethod().
 {
   addObjectReference("Current Step", mProgressCounter, CCopasiObject::ValueInt);
 }
CMatrix< C_INT64 > CBitPatternMethod::performRankTest (CStepMatrixColumn * pIntersectColumn) private
Performs rank test on given intersection.
Definition at line 923 of file CBitPatternMethod.cpp.
References CVectorCore< CType >::array(), CMatrix< CType >::array(), C_INT64, CalculateKernel(), getAllUnsetBitIndexes(), mExpandedStoiTranspose, CMatrix< CType >::numCols(), and CVectorCore< CType >::size().
Referenced by buildFluxModeMatrix(), and combine().
 {
   CVector<size_t> Indexes;
   getAllUnsetBitIndexes(pIntersectColumn, Indexes);
   size_t NumReactions = Indexes.size();
   size_t NumSpecies = mExpandedStoiTranspose.numCols();
   // Build the stoichiometry matrix reduced to the reactions participating in the current mode.
   CMatrix< C_INT64 > A(NumReactions, NumSpecies);
   size_t * pIndex = Indexes.array();
   size_t * pIndexEnd = pIndex + NumReactions;
   C_INT64 * pARow = A.array();
   for (; pIndex != pIndexEnd; ++pIndex, pARow += NumSpecies)
     {
       memcpy(pARow, &mExpandedStoiTranspose(*pIndex, 0), NumSpecies * sizeof(C_INT64));
     }
   // Calculate the kernel of the matrix
   CMatrix< C_INT64 > ExpandedStoiTranspose(A);
   CMatrix< C_INT64 > Kernel;
   CVector< size_t > Pivot;
   //DebugFile << ExpandedStoiTranspose << std::endl;
   CalculateKernel(ExpandedStoiTranspose, Kernel, Pivot);
   return Kernel;
 }
Friends And Related Function Documentation
CEFMMethod* CEFMMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
bool CBitPatternMethod::mContinueCombination protected
Boolean value indicating whether combination should continue.
Definition at line 257 of file CBitPatternMethod.h.
Referenced by calculate(), combine(), and initialize().
CMatrix< C_INT64 > CBitPatternMethod::mExpandedStoiTranspose protected
The transpose of the expanded stoichiometry matrix.
Definition at line 232 of file CBitPatternMethod.h.
Referenced by buildFluxModes(), buildKernelMatrix(), and performRankTest().
size_t CBitPatternMethod::mhProgressCounter protected
Handle to the process report item "Current Step"
Definition at line 202 of file CBitPatternMethod.h.
Referenced by calculate(), and initialize().
size_t CBitPatternMethod::mhProgressCounter2 protected
Handle to the process report item "Combination"
Definition at line 217 of file CBitPatternMethod.h.
Referenced by calculate(), and combine().
size_t CBitPatternMethod::mMinimumSetSize protected
The minimum set size use to determine whether a linear combination is allowed.
Definition at line 247 of file CBitPatternMethod.h.
Referenced by combine(), and initialize().
std::vector< CStepMatrixColumn * > CBitPatternMethod::mNewColumns protected
A list of invalid columns currently in the step matrix
Definition at line 242 of file CBitPatternMethod.h.
Referenced by combine(), and findRemoveInvalidColumns().
CModel* CBitPatternMethod::mpModel protected
A pointer to the model which is analyzed.
Definition at line 187 of file CBitPatternMethod.h.
Referenced by buildKernelMatrix(), and initialize().
unsigned C_INT32 CBitPatternMethod::mProgressCounter protected
The current step used for process report.
Definition at line 192 of file CBitPatternMethod.h.
Referenced by calculate(), initialize(), and initObjects().
unsigned C_INT32 CBitPatternMethod::mProgressCounter2 protected
The current combination used for process report.
Definition at line 207 of file CBitPatternMethod.h.
Referenced by calculate(), and combine().
unsigned C_INT32 CBitPatternMethod::mProgressCounter2Max protected
The max combination used for process report.
Definition at line 212 of file CBitPatternMethod.h.
Referenced by calculate().
unsigned C_INT32 CBitPatternMethod::mProgressCounterMax protected
The max step used for process report.
Definition at line 197 of file CBitPatternMethod.h.
Referenced by calculate(), and initialize().
CStepMatrix* CBitPatternMethod::mpStepMatrix protected
A pointer to the step matrix for creating the flux modes
Definition at line 237 of file CBitPatternMethod.h.
Referenced by buildFluxModes(), calculate(), combine(), findRemoveInvalidColumns(), getAllUnsetBitIndexes(), getUnsetBitIndexes(), and initialize().
std::vector< std::pair< size_t, bool > > CBitPatternMethod::mReactionForward protected
A vector to recording the expansion of the stoichiometry matrix.
Definition at line 222 of file CBitPatternMethod.h.
Referenced by buildFluxModes(), buildKernelMatrix(), and initialize().
CVector< size_t > CBitPatternMethod::mReactionPivot protected
A vector recording the pivots for the QR factorization
Definition at line 227 of file CBitPatternMethod.h.
Referenced by buildKernelMatrix(), getAllUnsetBitIndexes(), and getUnsetBitIndexes().
size_t CBitPatternMethod::mStep protected
The currently process step
Definition at line 252 of file CBitPatternMethod.h.
Referenced by calculate().
The documentation for this class was generated from the following files:
CBitPatternMethod.h
CBitPatternMethod.cpp