COPASI API: CGraphCurve Class Reference
CGraphCurve Class Reference
#include <CGraphCurve.h>
Public Member Functions
CGraphCurve ()
CGraphCurve (const CLCurve &c)
CGraphCurve (const CGraphCurve &c)
CArrow getArrow ()
CLMetabReferenceGlyph::Role getRole ()
bool hasArrowP ()
void invertOrderOfPoints ()
void scale (const double &scaleFactor)
void setArrow (CArrow ar)
void setArrowP (bool b)
void setRole (CLMetabReferenceGlyph::Role r)
Public Member Functions inherited from CLCurve
void addCurveSegment (const CLLineSegment &ls)
void addCurveSegment (const CLLineSegment *pLs)
CLBoundingBox calculateBoundingBox () const
CLCurve ()
CLCurve (const CLCurve &c)
CLCurve (const Curve &sbmlcurve)
void clear ()
void exportToSBML (Curve *c, const std::map< const CCopasiObject *, SBase * > &copasimodelmap) const
const std::vector
< CLLineSegment > & getCurveSegments () const
std::vector< CLPoint > getListOfPoints () const
size_t getNumCurveSegments () const
const CLLineSegment * getSegmentAt (size_t i) const
CLLineSegment * getSegmentAt (size_t i)
bool isContinuous () const
virtual void moveBy (const CLPoint &p)
bool operator== (const CLCurve &rhs) const
void scale (const double &scaleFactor)
~CLCurve ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Private Attributes
CArrow mArrow
bool mHasArrow
CLMetabReferenceGlyph::Role mRole
Additional Inherited Members
Protected Attributes inherited from CLCurve
std::vector< CLLineSegment > mvCurveSegments
Protected Attributes inherited from CLBase
std::string mTag
Detailed Description
Definition at line 31 of file CGraphCurve.h.
Constructor & Destructor Documentation
CGraphCurve::CGraphCurve ()
Definition at line 29 of file CGraphCurve.cpp.
References mHasArrow.
     : CLCurve()
 {
   mHasArrow = false;
 }
CGraphCurve::CGraphCurve (const CLCurve & c)
Definition at line 35 of file CGraphCurve.cpp.
References mHasArrow.
     : CLCurve(c)
 {
   mHasArrow = false;
 }
CGraphCurve::CGraphCurve (const CGraphCurve & c)
copy constructor (should make deep copy)
Definition at line 41 of file CGraphCurve.cpp.
References mArrow, mHasArrow, and mRole.
     : CLCurve(c)
 {
   mHasArrow = c.mHasArrow;
   mArrow = c.mArrow;
   mRole = c.mRole;
 }
Member Function Documentation
CArrow CGraphCurve::getArrow () inline
Definition at line 54 of file CGraphCurve.h.
References mArrow.
Referenced by CQGLNetworkPainter::drawEdge().
 {return mArrow;}
CLMetabReferenceGlyph::Role CGraphCurve::getRole () inline
Definition at line 53 of file CGraphCurve.h.
References mRole.
Referenced by CQGLNetworkPainter::drawEdge().
 {return mRole;}
bool CGraphCurve::hasArrowP () inline
Definition at line 49 of file CGraphCurve.h.
References mHasArrow.
Referenced by CQGLNetworkPainter::drawEdge(), and CQGLNetworkPainter::setNodeSize().
 {return mHasArrow;}
void CGraphCurve::invertOrderOfPoints ()
Definition at line 62 of file CGraphCurve.cpp.
References BezierCurve::curvePts(), CLLineSegment::getBase1(), CLLineSegment::getBase2(), CLLineSegment::getEnd(), CLLineSegment::getStart(), CLPoint::getX(), CLPoint::getY(), CLLineSegment::isBezier(), mArrow, mHasArrow, CLCurve::mvCurveSegments, CArrow::setLine(), and CArrow::setPoint().
Referenced by CQGLNetworkPainter::checkCurve().
 {
   unsigned int i; // invert order of points in each segment
   CLPoint h; // puffer variable
   for (i = 0; i < mvCurveSegments.size(); i++)
     {
       h = mvCurveSegments[i].getStart();
       mvCurveSegments[i].setStart(mvCurveSegments[i].getEnd());
       mvCurveSegments[i].setEnd(h);
       if (mvCurveSegments[i].isBezier())
         {
           h = mvCurveSegments[i].getBase1();
           mvCurveSegments[i].setBase1(mvCurveSegments[i].getBase2());
           mvCurveSegments[i].setBase2(h);
         }
     }
   // now invert order of segments
   std::reverse(mvCurveSegments.begin(), mvCurveSegments.end());
   if (mHasArrow)
     {// exchange line segment and end point
       CLLineSegment lastSeg = mvCurveSegments[mvCurveSegments.size() - 1];
       CLPoint p = lastSeg.getEnd();
       if (lastSeg.isBezier())
         {
           BezierCurve *bezier = new BezierCurve();
           std::vector<CLPoint> pts = std::vector<CLPoint>();
           pts.push_back(lastSeg.getStart());
           pts.push_back(lastSeg.getBase1());
           pts.push_back(lastSeg.getBase2());
           pts.push_back(lastSeg.getEnd());
           std::vector<CLPoint> bezierPts = bezier->curvePts(pts);
           size_t num = bezierPts.size();
           CLLineSegment segForArrow = CLLineSegment(bezierPts[num - 2], bezierPts[num - 1]);
           mArrow.setLine(segForArrow);
           mArrow.setPoint(CLPoint(bezierPts[num - 1].getX(), bezierPts[num - 1].getY()));
           //ar = new CArrow(segForArrow, bezierPts[num - 1].getX(), bezierPts[num - 1].getY(), this->currentZoom);
         }
       else
         {
           mArrow.setLine(lastSeg);
           mArrow.setPoint(CLPoint(p.getX(), p.getY()));
         }
       //ar = new CArrow(lastSeg, p.getX(), p.getY(), this->currentZoom);
     }
 }
void CGraphCurve::scale (const double & scaleFactor)
Definition at line 49 of file CGraphCurve.cpp.
References mArrow, mHasArrow, CLCurve::mvCurveSegments, and CArrow::scale().
 {
   unsigned int i; // scale all segments
   for (i = 0; i < mvCurveSegments.size(); i++)
     {
       mvCurveSegments[i].scale(scaleFactor);
     }
   if (mHasArrow)
     mArrow.scale(scaleFactor);
 }
void CGraphCurve::setArrow (CArrow ar) inline
Definition at line 51 of file CGraphCurve.h.
References mArrow.
Referenced by CQGLNetworkPainter::createGraph(), and CQGLNetworkPainter::setNodeSize().
 {mArrow = ar;}
void CGraphCurve::setArrowP (bool b) inline
Definition at line 50 of file CGraphCurve.h.
References mHasArrow.
Referenced by CQGLNetworkPainter::createGraph().
 {mHasArrow = b;}
void CGraphCurve::setRole (CLMetabReferenceGlyph::Role r) inline
Definition at line 52 of file CGraphCurve.h.
References mRole.
Referenced by CQGLNetworkPainter::createGraph().
 {mRole = r;}
Member Data Documentation
CArrow CGraphCurve::mArrow private
Definition at line 34 of file CGraphCurve.h.
Referenced by CGraphCurve(), getArrow(), invertOrderOfPoints(), scale(), and setArrow().
bool CGraphCurve::mHasArrow private
Definition at line 35 of file CGraphCurve.h.
Referenced by CGraphCurve(), hasArrowP(), invertOrderOfPoints(), scale(), and setArrowP().
CLMetabReferenceGlyph::Role CGraphCurve::mRole private
Definition at line 36 of file CGraphCurve.h.
Referenced by CGraphCurve(), getRole(), and setRole().
The documentation for this class was generated from the following files:
CGraphCurve.h
CGraphCurve.cpp