COPASI API: CFittingPoint Class Reference
CFittingPoint Class Reference
#include <CExperiment.h>
Public Member Functions
CFittingPoint (const std::string &name="unknown", const CCopasiContainer *pParent=NULL)
CFittingPoint (const CFittingPoint &src, const CCopasiContainer *pParent=NULL)
const std::string & getModelObjectCN () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
void setValues (const C_FLOAT64 &independent, const C_FLOAT64 &measured, const C_FLOAT64 &fitted, const C_FLOAT64 &weightedError)
~CFittingPoint ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initObjects ()
Private Attributes
C_FLOAT64 mFittedValue
C_FLOAT64 mIndependentValue
C_FLOAT64 mMeasuredValue
CRegisteredObjectName mModelObjectCN
C_FLOAT64 mWeightedError
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 28 of file CExperiment.h.
Constructor & Destructor Documentation
CFittingPoint::CFittingPoint (const std::string & name = "unknown", const CCopasiContainer * pParent = NULL)
Definition at line 1718 of file CExperiment.cpp.
References initObjects().
                                                               :
   CCopasiContainer("Fitting Point", pParent, "Fitted Point"),
   mModelObjectCN(name),
   mIndependentValue(std::numeric_limits<C_FLOAT64>::quiet_NaN()),
   mMeasuredValue(std::numeric_limits<C_FLOAT64>::quiet_NaN()),
   mFittedValue(std::numeric_limits<C_FLOAT64>::quiet_NaN()),
   mWeightedError(std::numeric_limits<C_FLOAT64>::quiet_NaN())
 {initObjects();}
CFittingPoint::CFittingPoint (const CFittingPoint & src, const CCopasiContainer * pParent = NULL)
Definition at line 1728 of file CExperiment.cpp.
References initObjects().
                                                               :
   CCopasiContainer(src, pParent),
   mModelObjectCN(src.mModelObjectCN),
   mIndependentValue(src.mIndependentValue),
   mMeasuredValue(src.mMeasuredValue),
   mFittedValue(src.mFittedValue),
   mWeightedError(src.mWeightedError)
 {initObjects();}
CFittingPoint::~CFittingPoint ()
Definition at line 1738 of file CExperiment.cpp.
 {}
Member Function Documentation
const std::string & CFittingPoint::getModelObjectCN () const
Definition at line 1760 of file CExperiment.cpp.
References mModelObjectCN.
 {
   return mModelObjectCN;
 }
std::string CFittingPoint::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
Reimplemented from CCopasiObject.
Definition at line 1741 of file CExperiment.cpp.
References CCopasiContainer::getObject(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectDisplayName(), and mModelObjectCN.
 {
   const CCopasiDataModel * pDataModel = this->getObjectDataModel();
   if (pDataModel == NULL)
     {
       return CCopasiContainer::getObjectDisplayName(regular, richtext);
     }
   const CCopasiObject * pObject = dynamic_cast< const CCopasiObject * >(pDataModel->getObject(mModelObjectCN));
   if (pObject == NULL)
     {
       return CCopasiContainer::getObjectDisplayName(regular, richtext);
     }
   return pObject->getObjectDisplayName(regular, richtext);
 }
void CFittingPoint::initObjects () private
Definition at line 1776 of file CExperiment.cpp.
References CCopasiContainer::addObjectReference(), mFittedValue, mIndependentValue, mMeasuredValue, mWeightedError, and CCopasiObject::ValueDbl.
Referenced by CFittingPoint().
 {
   addObjectReference("Independent Value", mIndependentValue, CCopasiObject::ValueDbl);
   addObjectReference("Measured Value", mMeasuredValue, CCopasiObject::ValueDbl);
   addObjectReference("Fitted Value", mFittedValue, CCopasiObject::ValueDbl);
   addObjectReference("Weighted Error", mWeightedError, CCopasiObject::ValueDbl);
 }
void CFittingPoint::setValues (const C_FLOAT64 & independent, const C_FLOAT64 & measured, const C_FLOAT64 & fitted, const C_FLOAT64 & weightedError)
Definition at line 1765 of file CExperiment.cpp.
References mFittedValue, mIndependentValue, mMeasuredValue, and mWeightedError.
 {
   mIndependentValue = independent;
   mMeasuredValue = measured;
   mFittedValue = fitted;
   mWeightedError = weightedError;
 }
Member Data Documentation
C_FLOAT64 CFittingPoint::mFittedValue private
Definition at line 57 of file CExperiment.h.
Referenced by initObjects(), and setValues().
C_FLOAT64 CFittingPoint::mIndependentValue private
Definition at line 55 of file CExperiment.h.
Referenced by initObjects(), and setValues().
C_FLOAT64 CFittingPoint::mMeasuredValue private
Definition at line 56 of file CExperiment.h.
Referenced by initObjects(), and setValues().
CRegisteredObjectName CFittingPoint::mModelObjectCN private
Definition at line 54 of file CExperiment.h.
Referenced by getModelObjectCN(), and getObjectDisplayName().
C_FLOAT64 CFittingPoint::mWeightedError private
Definition at line 58 of file CExperiment.h.
Referenced by initObjects(), and setValues().
The documentation for this class was generated from the following files:
CExperiment.h
CExperiment.cpp