COPASI API: CProgressBar Class Reference
CProgressBar Class Reference
#include <CProgressBar.h>
Signals
void signalAddItem (const int handle)
void signalFinishItem (const int handle)
void signalProgressAll ()
void signalSetName (QString name)
Public Member Functions
virtual bool finish ()
virtual bool finishItem (const size_t &handle)
virtual bool proceed ()
virtual bool progressItem (const size_t &handle)
virtual bool resetItem (const size_t &handle)
virtual bool setName (const std::string &name)
virtual ~CProgressBar ()
Public Member Functions inherited from CQProgressDialog
CQProgressDialog (QWidget *parent=0, const char *name=0, Qt::WindowModality windowModality=Qt::WindowModal, Qt::WindowFlags fl=0)
bool insertProgressItem (CQProgressItem *pItem)
bool removeProgressItem (CQProgressItem *pItem)
~CQProgressDialog ()
Public Member Functions inherited from CProcessReport
size_t addItem (const std::string &name, const std::string &value, const std::string *pEndValue=NULL)
size_t addItem (const std::string &name, const C_INT32 &value, const C_INT32 *pEndValue=NULL)
size_t addItem (const std::string &name, const unsigned C_INT32 &value, const unsigned C_INT32 *pEndValue=NULL)
size_t addItem (const std::string &name, const C_FLOAT64 &value, const C_FLOAT64 *pEndValue=NULL)
CProcessReport (const unsigned int &maxTime=0)
virtual bool isValidHandle (const size_t handle) const
virtual bool progress ()
virtual bool reset ()
virtual ~CProcessReport ()
Static Public Member Functions
static CProgressBar * create (QWidget *parent=0, const char *name=0, Qt::WindowModality windowModality=Qt::WindowModal)
Protected Slots
virtual void btnContinuePressed ()
virtual void btnStopPressed ()
virtual void slotAddItem (const int handle)
virtual void slotFinishItem (const int handle)
virtual void slotProgressAll ()
virtual void slotSetName (QString name)
Protected Slots inherited from CQProgressDialog
virtual void accept ()
virtual void btnContinuePressed ()
virtual void btnPausePressed ()
virtual void btnStopPressed ()
virtual void done (int)
virtual void reject ()
void timerShow ()
Protected Member Functions
virtual size_t addItem (const std::string &name, const CCopasiParameter::Type &type, const void *pValue, const void *pEndValue=NULL)
virtual void closeEvent (QCloseEvent *e)
Protected Attributes
size_t mLastHItem
QMutex mMutex
bool mSlotFinished
QWaitCondition mWaitPause
QWaitCondition mWaitSlot
Protected Attributes inherited from CQProgressDialog
bool mPause
bool mProceed
Protected Attributes inherited from CProcessReport
std::string mName
CCopasiTimeVariable * mpEndTime
CVector< CProcessReportItem * > mProcessReportItemList
Private Member Functions
CProgressBar (QWidget *parent, const char *name, Qt::WindowModality windowModality)
Private Attributes
QDateTime mNextEventProcessing
QWidget * mpMainWidget
CVector< CQProgressItem * > mProgressItemList
Detailed Description
This is used to call the progress bar code We do not want to call GUI stuff directly from the CModel.
Definition at line 41 of file CProgressBar.h.
Constructor & Destructor Documentation
CProgressBar::CProgressBar (QWidget * parent, const char * name, Qt::WindowModality windowModality) private
Definition at line 56 of file CProgressBar.cpp.
References CopasiUI3Window::disableSliders(), CopasiUI3Window::getMainWindow(), mProgressItemList, signalAddItem(), signalFinishItem(), signalProgressAll(), signalSetName(), slotAddItem(), slotFinishItem(), slotProgressAll(), and slotSetName().
Referenced by create().
                                                                                             :
   CQProgressDialog(parent, name, windowModality, Qt::WindowMinimizeButtonHint),
   CProcessReport(),
   mProgressItemList(1),
   mNextEventProcessing(QDateTime::currentDateTime()),
   mpMainWidget(NULL)
 {
   CopasiUI3Window::getMainWindow()->disableSliders(true);
   mProgressItemList[0] = NULL;
   connect(this, SIGNAL(signalAddItem(const int)),
           this, SLOT(slotAddItem(const int)));
   connect(this, SIGNAL(signalSetName(QString)),
           this, SLOT(slotSetName(QString)));
   connect(this, SIGNAL(signalProgressAll()),
           this, SLOT(slotProgressAll()));
   connect(this, SIGNAL(signalFinishItem(const int)),
           this, SLOT(slotFinishItem(const int)));
 }
CProgressBar::~CProgressBar () virtual
Definition at line 80 of file CProgressBar.cpp.
References finish(), mProgressItemList, pdelete, and CVectorCore< CType >::size().
 {
   finish();
   size_t i, imax = mProgressItemList.size();
   for (i = 0; i < imax; i++)
     pdelete(mProgressItemList[i]);
 }
Member Function Documentation
size_t CProgressBar::addItem (const std::string & name, const CCopasiParameter::Type & type, const void * pValue, const void * pEndValue = NULL) protected virtual
Add a process report item to to the list of reporting items. The return value is the handle of the item and can be used to indicate process, finish, or reset the item. If the method fails C_INVALID_INDEX is returned.
Parameters
const std::string & name
const CCopasiParameter::Type & type
const void * pValue
const void * pEndValue = NULL
Returns
size_t handle
Reimplemented from CProcessReport.
Definition at line 90 of file CProgressBar.cpp.
References CProcessReport::addItem(), CopasiUI3Window::isMainThread(), mMutex, mSlotFinished, mWaitSlot, signalAddItem(), and slotAddItem().
 {
   size_t hItem = CProcessReport::addItem(name, type, pValue, pEndValue);
   if (!CopasiUI3Window::isMainThread())
     {
       QMutexLocker Locker(&mMutex);
       mSlotFinished = false;
       emit signalAddItem((int) hItem);
       if (!mSlotFinished)
         {
           mWaitSlot.wait(&mMutex);
         }
     }
   else
     {
       slotAddItem((int) hItem);
       QCoreApplication::processEvents();
     }
   return hItem;
 }
void CProgressBar::btnContinuePressed () protected virtual slot
Definition at line 346 of file CProgressBar.cpp.
References CQProgressDialog::btnContinuePressed(), and mWaitPause.
 {
   CQProgressDialog::btnContinuePressed();
   mWaitPause.wakeAll();
 }
void CProgressBar::btnStopPressed () protected virtual slot
Definition at line 339 of file CProgressBar.cpp.
References CQProgressDialog::btnStopPressed(), and mWaitPause.
 {
   CQProgressDialog::btnStopPressed();
   mWaitPause.wakeAll();
 }
void CProgressBar::closeEvent (QCloseEvent * e) protected virtual
Definition at line 330 of file CProgressBar.cpp.
References CQMessageBox::information().
 {
   CQMessageBox::information(this, "COPASI", "COPASI is currently executing tasks.\n"
                             "Please stop them first before closing COPASI.");
   e->ignore();
 }
CProgressBar * CProgressBar::create (QWidget * parent = 0, const char * name = 0, Qt::WindowModality windowModality = Qt::WindowModal) static
Definition at line 37 of file CProgressBar.cpp.
References CProgressBar(), CopasiUI3Window::getMainWindow(), and CopasiUI3Window::isMainThread().
Referenced by TaskWidget::commonBeforeRunTask(), DataModelGUI::exportMathModel(), DataModelGUI::exportSBML(), DataModelGUI::exportSBMLToString(), DataModelGUI::importSBML(), DataModelGUI::importSBMLFromString(), DataModelGUI::loadModel(), DataModelGUI::saveModel(), and DataModelGUI::updateMIRIAM().
 {
   QWidget * pParent = parent;
   if (pParent == NULL)
     {
       pParent = CopasiUI3Window::getMainWindow();
     }
   if (CopasiUI3Window::isMainThread())
     {
       return new CProgressBar(pParent, name, windowModality);
     }
   else
     {
       return NULL;
     }
 }
bool CProgressBar::finish () virtual
Indicate that all items are finished reporting. All item handles loose their validity. If the return value is false the calling process must halt execution and return.
Parameters
bool continue
Reimplemented from CProcessReport.
Definition at line 208 of file CProgressBar.cpp.
References CVectorCore< CType >::array(), CopasiUI3Window::disableSliders(), CQProgressDialog::done(), CProcessReport::finish(), CopasiUI3Window::getMainWindow(), CopasiUI3Window::isMainThread(), CQProgressDialog::mProceed, CProcessReport::mProcessReportItemList, mProgressItemList, CQProgressDialog::removeProgressItem(), and CVectorCore< CType >::size().
Referenced by TaskWidget::commonAfterRunTask(), TaskWidget::commonRunTask(), TaskWidget::finishTask(), DataModelGUI::threadFinished(), and ~CProgressBar().
 {
   // Assure that all signals have been properly handled before we delete
   // the progress items
   if (CopasiUI3Window::isMainThread())
     QCoreApplication::processEvents();
   // The method must only be called from the main thread!
   CQProgressItem ** ppIt = mProgressItemList.array();
   CQProgressItem ** ppEnd = ppIt + mProgressItemList.size();
   CProcessReportItem **ppItem = mProcessReportItemList.array();
   for (; ppIt != ppEnd; ++ppIt, ++ppItem)
     {
       if (*ppIt != NULL)
         {
           removeProgressItem(*ppIt);
           // We must make sure the CProcessReportItem is not deleted prior to the actual delete.
           // The destructor of CQProgressItem will take care of the deletion.
           *ppItem = NULL;
           (*ppIt)->deleteLater();
           (*ppIt) = NULL;
         }
     }
   CopasiUI3Window::getMainWindow()->disableSliders(false);
   CProcessReport::finish();
   done(1);
   return mProceed;
 }
bool CProgressBar::finishItem (const size_t & handle) virtual
Indicate that item handle is finished reporting. The handle of that item is no longer valid after the call. If the return value is false the calling process must halt execution and return.
Parameters
const size_t & handle
bool continue
Reimplemented from CProcessReport.
Definition at line 243 of file CProgressBar.cpp.
References CopasiUI3Window::isMainThread(), CProcessReport::isValidHandle(), mMutex, CQProgressDialog::mProceed, mProgressItemList, mSlotFinished, mWaitSlot, signalFinishItem(), and slotFinishItem().
 {
   if (!isValidHandle(handle) || mProgressItemList[handle] == NULL) return false;
   if (!CopasiUI3Window::isMainThread())
     {
       QMutexLocker Locker(&mMutex);
       mSlotFinished = false;
       emit signalFinishItem((int) handle);
       if (!mSlotFinished)
         {
           mWaitSlot.wait(&mMutex);
         }
     }
   else
     {
       slotFinishItem((int) handle);
       QCoreApplication::processEvents();
     }
   return mProceed;
 }
bool CProgressBar::proceed () virtual
Check whether processing shall proceed. If the return value is false the calling process must halt execution and return. This method is provided so that lengthy processing without advances in any of the reporting items can check whether continuation is requested.
Parameters
bool continue
Reimplemented from CProcessReport.
Definition at line 291 of file CProgressBar.cpp.
References CQProgressDialog::mProceed.
 {
   return mProceed;
 }
bool CProgressBar::progressItem (const size_t & handle) virtual
Report process on item handle. If the return value is false the calling process must halt execution and return.
Parameters
const size_t & handle
bool continue
Reimplemented from CProcessReport.
Definition at line 158 of file CProgressBar.cpp.
References CopasiUI3Window::isMainThread(), CProcessReport::isValidHandle(), mMutex, mNextEventProcessing, CQProgressDialog::mPause, CQProgressDialog::mProceed, mProgressItemList, mSlotFinished, mWaitPause, signalProgressAll(), and slotProgressAll().
Referenced by DataModelGUI::miriamDownloadFinished(), and DataModelGUI::miriamDownloadProgress().
 {
   if (!isValidHandle(handle) || mProgressItemList[handle] == NULL) return false;
   QDateTime currDateTime = QDateTime::currentDateTime();
   if (mNextEventProcessing >= currDateTime)
     return mProceed;
   mNextEventProcessing = currDateTime.addSecs(1);
   if (mPause)
     {
       QMutexLocker Locker(&mMutex);
       mWaitPause.wait(&mMutex);
     }
   if (!CopasiUI3Window::isMainThread())
     {
       if (mSlotFinished)
         {
           mSlotFinished = false;
           emit signalProgressAll();
         }
     }
   else
     {
       slotProgressAll();
       QCoreApplication::processEvents();
     }
   return mProceed;
 }
bool CProgressBar::resetItem (const size_t & handle) virtual
Reset item handle. This means that the value of the item has changed but not as part of a continuous process. If you run multiple processes call reset between them. If the return value is false the calling process must halt execution and return.
Parameters
const size_t & handle
bool continue
Reimplemented from CProcessReport.
Definition at line 151 of file CProgressBar.cpp.
References CProcessReport::isValidHandle(), CQProgressDialog::mProceed, mProgressItemList, and CProcessReport::reset().
 {
   if (!isValidHandle(handle) || mProgressItemList[handle] == NULL) return false;
   return (mProgressItemList[handle]->reset() && mProceed);
 }
bool CProgressBar::setName (const std::string & name) virtual
Set the name of the process.
Parameters
const std::string & name
Returns
success
Reimplemented from CProcessReport.
Definition at line 297 of file CProgressBar.cpp.
References FROM_UTF8, CopasiUI3Window::isMainThread(), mMutex, mSlotFinished, mWaitSlot, signalSetName(), and slotSetName().
Referenced by DataModelGUI::updateMIRIAM().
 {
   if (!CopasiUI3Window::isMainThread())
     {
       QMutexLocker Locker(&mMutex);
       mSlotFinished = false;
       emit signalSetName(FROM_UTF8(name));
       if (!mSlotFinished)
         {
           mWaitSlot.wait(&mMutex);
         }
     }
   else
     {
       slotSetName(FROM_UTF8(name));
       QCoreApplication::processEvents();
     }
   return true;
 }
void CProgressBar::signalAddItem (const int handle) signal
Referenced by addItem(), and CProgressBar().
void CProgressBar::signalFinishItem (const int handle) signal
Referenced by CProgressBar(), and finishItem().
void CProgressBar::signalProgressAll () signal
Referenced by CProgressBar(), and progressItem().
void CProgressBar::signalSetName (QString name) signal
Referenced by CProgressBar(), and setName().
void CProgressBar::slotAddItem (const int handle) protected virtual slot
Definition at line 119 of file CProgressBar.cpp.
References C_INVALID_INDEX, CQProgressDialog::insertProgressItem(), mMutex, CProcessReport::mProcessReportItemList, mProgressItemList, mSlotFinished, mWaitSlot, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by addItem(), and CProgressBar().
 {
   size_t Handle = (size_t) handle;
   if (Handle == C_INVALID_INDEX) return;
   QMutexLocker Locker(&mMutex);
   if (Handle >= mProgressItemList.size()) // we need to resize
     {
       size_t i, imax = mProgressItemList.size();
       mProgressItemList.resize(2 * imax, true); // Note, imax is never zero
       i = imax;
       imax *= 2;
       while (i < imax) mProgressItemList[i++] = NULL;
     }
   if (mProcessReportItemList[Handle]->hasEndValue())
     mProgressItemList[Handle] = new CQProgressItemBar(static_cast<CQProgressDialog *>(this));
   else
     mProgressItemList[Handle] = new CQProgressItemText(static_cast<CQProgressDialog *>(this));
   mProgressItemList[Handle]->initFromProcessReportItem(mProcessReportItemList[Handle]);
   insertProgressItem(mProgressItemList[Handle]);
   mSlotFinished = true;
   mWaitSlot.wakeAll();
 }
void CProgressBar::slotFinishItem (const int handle) protected virtual slot
Definition at line 268 of file CProgressBar.cpp.
References CProcessReport::isValidHandle(), mMutex, CProcessReport::mProcessReportItemList, mProgressItemList, mSlotFinished, mWaitSlot, and CQProgressDialog::removeProgressItem().
Referenced by CProgressBar(), and finishItem().
 {
   size_t Handle = (size_t) handle;
   if (isValidHandle(Handle) &&
       mProgressItemList[Handle] != NULL)
     {
       QMutexLocker Locker(&mMutex);
       removeProgressItem(mProgressItemList[Handle]);
       // We must make sure the CProcessReportItem is not deleted prior to the actual delete.
       // The destructor of CQProgressItem will take care of the deletion.
       mProcessReportItemList[Handle] = NULL;
       mProgressItemList[Handle]->deleteLater();
       mProgressItemList[Handle] = NULL;
     }
   mSlotFinished = true;
   mWaitSlot.wakeAll();
 }
void CProgressBar::slotProgressAll () protected virtual slot
Definition at line 193 of file CProgressBar.cpp.
References mMutex, CQProgressDialog::mProceed, mProgressItemList, mSlotFinished, and CVectorCore< CType >::size().
Referenced by CProgressBar(), and progressItem().
 {
   size_t hItem, hmax = mProgressItemList.size();
   QMutexLocker Locker(&mMutex);
   for (hItem = 0; hItem < hmax; hItem++)
     {
       if (mProgressItemList[hItem])
         mProceed &= mProgressItemList[hItem]->process();
     }
   mSlotFinished = true;
 }
void CProgressBar::slotSetName (QString name) protected virtual slot
Definition at line 319 of file CProgressBar.cpp.
References mMutex, mSlotFinished, mWaitSlot, CProcessReport::setName(), and TO_UTF8.
Referenced by CProgressBar(), and setName().
 {
   QMutexLocker Locker(&mMutex);
   setWindowTitle(name);
   CProcessReport::setName(TO_UTF8(name));
   mSlotFinished = true;
   mWaitSlot.wakeAll();
 }
Member Data Documentation
size_t CProgressBar::mLastHItem protected
Definition at line 132 of file CProgressBar.h.
QMutex CProgressBar::mMutex protected
Definition at line 128 of file CProgressBar.h.
Referenced by addItem(), finishItem(), progressItem(), setName(), slotAddItem(), slotFinishItem(), slotProgressAll(), and slotSetName().
QDateTime CProgressBar::mNextEventProcessing private
Definition at line 137 of file CProgressBar.h.
Referenced by progressItem().
QWidget* CProgressBar::mpMainWidget private
Definition at line 139 of file CProgressBar.h.
CVector< CQProgressItem * > CProgressBar::mProgressItemList private
Definition at line 135 of file CProgressBar.h.
Referenced by CProgressBar(), finish(), finishItem(), progressItem(), resetItem(), slotAddItem(), slotFinishItem(), slotProgressAll(), and ~CProgressBar().
bool CProgressBar::mSlotFinished protected
Definition at line 126 of file CProgressBar.h.
Referenced by addItem(), finishItem(), progressItem(), setName(), slotAddItem(), slotFinishItem(), slotProgressAll(), and slotSetName().
QWaitCondition CProgressBar::mWaitPause protected
Definition at line 130 of file CProgressBar.h.
Referenced by btnContinuePressed(), btnStopPressed(), and progressItem().
QWaitCondition CProgressBar::mWaitSlot protected
Definition at line 129 of file CProgressBar.h.
Referenced by addItem(), finishItem(), setName(), slotAddItem(), slotFinishItem(), and slotSetName().
The documentation for this class was generated from the following files:
CProgressBar.h
CProgressBar.cpp