COPASI API: test000064 Class Reference
test000064 Class Reference
#include <test000064.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7 ()
void test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_1 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_2 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_3 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_4 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_5 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_6 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_7 ()
void test_export_rule_expression_and_hasOnlySubstanceUnits_8 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7 ()
void test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_1 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_2 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_3 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_4 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_5 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_6 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_7 ()
void test_import_rule_expression_and_hasOnlySubstanceUnits_8 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING10
static const char * MODEL_STRING101
static const char * MODEL_STRING102
static const char * MODEL_STRING103
static const char * MODEL_STRING104
static const char * MODEL_STRING105
static const char * MODEL_STRING106
static const char * MODEL_STRING107
static const char * MODEL_STRING108
static const char * MODEL_STRING109
static const char * MODEL_STRING11
static const char * MODEL_STRING110
static const char * MODEL_STRING111
static const char * MODEL_STRING112
static const char * MODEL_STRING113
static const char * MODEL_STRING114
static const char * MODEL_STRING115
static const char * MODEL_STRING116
static const char * MODEL_STRING12
static const char * MODEL_STRING13
static const char * MODEL_STRING14
static const char * MODEL_STRING15
static const char * MODEL_STRING16
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static const char * MODEL_STRING7
static const char * MODEL_STRING8
static const char * MODEL_STRING9
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_1)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_2)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_3)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_4)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_5)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_6)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_7)
CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_8)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7)
CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_1)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_2)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_3)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_4)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_5)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_6)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_7)
CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_8)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7)
CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8)
CPPUNIT_TEST_SUITE (test000064)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000064.h.
Member Function Documentation
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_1) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_2) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_3) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_4) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_5) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_6) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_7) private
test000064::CPPUNIT_TEST (test_import_rule_expression_and_hasOnlySubstanceUnits_8) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7) private
test000064::CPPUNIT_TEST (test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_1) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_2) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_3) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_4) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_5) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_6) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_7) private
test000064::CPPUNIT_TEST (test_export_rule_expression_and_hasOnlySubstanceUnits_8) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7) private
test000064::CPPUNIT_TEST (test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8) private
test000064::CPPUNIT_TEST_SUITE (test000064) private
test000064::CPPUNIT_TEST_SUITE_END () private
void test000064::setUp ()
Definition at line 56 of file test000064.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000064::tearDown ()
Definition at line 64 of file test000064.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1 ()
Definition at line 3108 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING109, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING109);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2 ()
Definition at line 3274 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING110, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING110);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
     }
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   Rule* pRule = pModel->getRule(0);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pCompartment->getId());
   CPPUNIT_ASSERT(pRule->isSetMath() == true);
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter multiplied by the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_NAME);
   ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild1->getName() == pParameter1->getId() || pChild2->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pChild1->getName() == pCompartment->getId() || pChild2->getName() == pCompartment->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3 ()
Definition at line 3473 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING111, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING111);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4 ()
Definition at line 3637 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING112, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING112);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
     }
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   Rule* pRule = pModel->getRule(0);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pCompartment->getId());
   CPPUNIT_ASSERT(pRule->isSetMath() == true);
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter multiplied by the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_NAME);
   const ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild1->getName() == pParameter1->getId() || pChild2->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pChild1->getName() == pCompartment->getId() || pChild2->getName() == pCompartment->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5 ()
Definition at line 3836 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING113, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING113);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_DIVIDE);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild->getName() == pParameter1->getId());
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild->getName() == pCompartment->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6 ()
Definition at line 4008 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING114, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING114);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
     }
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   Rule* pRule = pModel->getRule(0);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pCompartment->getId());
   CPPUNIT_ASSERT(pRule->isSetMath() == true);
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7 ()
Definition at line 4199 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING115, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING115);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_DIVIDE);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_NAME);
   ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild1->getName() == pParameter1->getId() || pChild2->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pChild1->getName() == pCompartment->getId() || pChild2->getName() == pCompartment->getId());
 }
void test000064::test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8 ()
Definition at line 4371 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING116, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING116);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
     }
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   Rule* pRule = pModel->getRule(0);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pCompartment->getId());
   CPPUNIT_ASSERT(pRule->isSetMath() == true);
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event asssignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter multiplied by the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_1 ()
Definition at line 1973 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING101, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING101);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   AssignmentRule* pRule = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pSpecies1->getId());
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_2 ()
Definition at line 2092 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING102, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING102);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is not constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter2 != NULL);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter1 != NULL);
     }
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 2);
   AssignmentRule* pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   AssignmentRule* pRule2 = NULL;
   CPPUNIT_ASSERT(pRule1 != NULL);
   if (pRule1->getVariable() == pSpecies1->getId())
     {
       pRule2 = pRule1;
       pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   else
     {
       pRule2 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   // check the rule for the compartment
   const ASTNode* pMath = pRule1->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter P
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   pMath = pRule2->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains a multiplication of the
   // global parameter K and the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild1 = pMath->getChild(0);
   ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild1->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild2->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild1->getName() == pParameter1->getId() || pChild2->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pChild1->getName() == pCompartment->getId() || pChild2->getName() == pCompartment->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_3 ()
Definition at line 2257 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING103, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING103);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   AssignmentRule* pRule = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pSpecies1->getId());
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_4 ()
Definition at line 2376 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING104, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING104);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is not constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter2 != NULL);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter1 != NULL);
     }
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 2);
   AssignmentRule* pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   AssignmentRule* pRule2 = NULL;
   CPPUNIT_ASSERT(pRule1 != NULL);
   if (pRule1->getVariable() == pSpecies1->getId())
     {
       pRule2 = pRule1;
       pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   else
     {
       pRule2 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   // check the rule for the compartment
   const ASTNode* pMath = pRule1->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter P
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   pMath = pRule2->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains a multiplication of the
   // global parameter K and the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild1 = pMath->getChild(0);
   ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild1->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild2->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild1->getName() == pParameter1->getId() || pChild2->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pChild1->getName() == pCompartment->getId() || pChild2->getName() == pCompartment->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_5 ()
Definition at line 2540 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING105, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING105);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   AssignmentRule* pRule = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pSpecies1->getId());
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter divided by the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_DIVIDE);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild->getName() == pParameter->getId());
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME);
   CPPUNIT_ASSERT(pChild->getName() == pCompartment->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_6 ()
Definition at line 2665 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING106, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING106);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is not constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter2 != NULL);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter1 != NULL);
     }
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 2);
   AssignmentRule* pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   AssignmentRule* pRule2 = NULL;
   CPPUNIT_ASSERT(pRule1 != NULL);
   if (pRule1->getVariable() == pSpecies1->getId())
     {
       pRule2 = pRule1;
       pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   else
     {
       pRule2 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   // check the rule for the compartment
   const ASTNode* pMath = pRule1->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter P
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   pMath = pRule2->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains a multiplication of the
   // global parameter K and the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_7 ()
Definition at line 2824 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING107, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING107);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == true);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == false);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == false);
   CPPUNIT_ASSERT(pModel->getNumRules() == 1);
   AssignmentRule* pRule = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == pSpecies1->getId());
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_DIVIDE);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getName() == pParameter->getId());
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getName() == pCompartment->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_export_rule_expression_and_hasOnlySubstanceUnits_8 ()
Definition at line 2949 of file test000064.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING108, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000064::MODEL_STRING108);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_ITEM);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is not constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment->getConstant() == false);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 2);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   Parameter* pParameter2 = NULL;
   if (pParameter1->getName() == "K")
     {
       pParameter2 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter2 != NULL);
     }
   else
     {
       pParameter2 = pParameter1;
       pParameter1 = pModel->getParameter(1);
       CPPUNIT_ASSERT(pParameter1 != NULL);
     }
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pParameter2->getName() == "P");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getHasOnlySubstanceUnits() == true);
   std::string idSpeciesA = pSpecies1->getId();
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getHasOnlySubstanceUnits() == true);
   CPPUNIT_ASSERT(pModel->getNumRules() == 2);
   AssignmentRule* pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(0));
   AssignmentRule* pRule2 = NULL;
   CPPUNIT_ASSERT(pRule1 != NULL);
   if (pRule1->getVariable() == pSpecies1->getId())
     {
       pRule2 = pRule1;
       pRule1 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   else
     {
       pRule2 = dynamic_cast<AssignmentRule*>(pModel->getRule(1));
     }
   // check the rule for the compartment
   const ASTNode* pMath = pRule1->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter P
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter2->getId());
   pMath = pRule2->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains a multiplication of the
   // global parameter K and the compartment volume
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1 ()
Definition at line 441 of file test000064.cpp.
References CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING5, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING5));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::DIVIDE);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2 ()
Definition at line 590 of file test000064.cpp.
References CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING6, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING6));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3 ()
Definition at line 723 of file test000064.cpp.
References CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, MODEL_STRING7, CEvaluationNode::NUMBER, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING7));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4 ()
Definition at line 856 of file test000064.cpp.
References CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, MODEL_STRING8, CEvaluationNode::NUMBER, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING8));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::DIVIDE);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5 ()
Definition at line 1393 of file test000064.cpp.
References CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING13, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING13));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6 ()
Definition at line 1530 of file test000064.cpp.
References CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING14, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING14));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7 ()
Definition at line 1683 of file test000064.cpp.
References CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, MODEL_STRING15, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::NUMBER, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING15));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8 ()
Definition at line 1836 of file test000064.cpp.
References CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, MODEL_STRING16, CEvaluationNode::NUMBER, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING16));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is no delay
   const CExpression* pExpression = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpression == NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpression = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpression != NULL);
   pNode = pExpression->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1 ()
Definition at line 69 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, CModel::mMol, MODEL_STRING1, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::DIVIDE);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2 ()
Definition at line 170 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, CModel::mMol, MODEL_STRING2, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3 ()
Definition at line 255 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, MODEL_STRING3, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING3));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4 ()
Definition at line 340 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, MODEL_STRING4, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING4));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::DIVIDE);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5 ()
Definition at line 1005 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, CModel::mMol, MODEL_STRING9, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING9));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6 ()
Definition at line 1094 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, CModel::mMol, MODEL_STRING10, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING10));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7 ()
Definition at line 1199 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, MODEL_STRING11, CEvaluationNodeOperator::MULTIPLY, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING11));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Volume"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pCompartment);
 }
void test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8 ()
Definition at line 1304 of file test000064.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, MODEL_STRING12, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING12));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   const CExpression* pExpr = pA->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
Member Data Documentation
const char * test000064::MODEL_STRING1 static protected
Definition at line 63 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_1().
const char * test000064::MODEL_STRING10 static protected
Definition at line 72 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_6().
const char * test000064::MODEL_STRING101 static protected
Definition at line 81 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_1().
const char * test000064::MODEL_STRING102 static protected
Definition at line 82 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_2().
const char * test000064::MODEL_STRING103 static protected
Definition at line 83 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_3().
const char * test000064::MODEL_STRING104 static protected
Definition at line 84 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_4().
const char * test000064::MODEL_STRING105 static protected
Definition at line 85 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_5().
const char * test000064::MODEL_STRING106 static protected
Definition at line 86 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_6().
const char * test000064::MODEL_STRING107 static protected
Definition at line 87 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_7().
const char * test000064::MODEL_STRING108 static protected
Definition at line 88 of file test000064.h.
Referenced by test_export_rule_expression_and_hasOnlySubstanceUnits_8().
const char * test000064::MODEL_STRING109 static protected
Definition at line 89 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1().
const char * test000064::MODEL_STRING11 static protected
Definition at line 73 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_7().
const char * test000064::MODEL_STRING110 static protected
Definition at line 90 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2().
const char * test000064::MODEL_STRING111 static protected
Definition at line 91 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3().
const char * test000064::MODEL_STRING112 static protected
Definition at line 92 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4().
const char * test000064::MODEL_STRING113 static protected
Definition at line 93 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5().
const char * test000064::MODEL_STRING114 static protected
Definition at line 94 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6().
const char * test000064::MODEL_STRING115 static protected
Definition at line 95 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7().
const char * test000064::MODEL_STRING116 static protected
Definition at line 96 of file test000064.h.
Referenced by test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8().
const char * test000064::MODEL_STRING12 static protected
Definition at line 74 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_8().
const char * test000064::MODEL_STRING13 static protected
Definition at line 75 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5().
const char * test000064::MODEL_STRING14 static protected
Definition at line 76 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6().
const char * test000064::MODEL_STRING15 static protected
Definition at line 77 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7().
const char * test000064::MODEL_STRING16 static protected
Definition at line 78 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8().
const char * test000064::MODEL_STRING2 static protected
Definition at line 64 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_2().
const char * test000064::MODEL_STRING3 static protected
Definition at line 65 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_3().
const char * test000064::MODEL_STRING4 static protected
Definition at line 66 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_4().
const char * test000064::MODEL_STRING5 static protected
Definition at line 67 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1().
const char * test000064::MODEL_STRING6 static protected
Definition at line 68 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2().
const char * test000064::MODEL_STRING7 static protected
Definition at line 69 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3().
const char * test000064::MODEL_STRING8 static protected
Definition at line 70 of file test000064.h.
Referenced by test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4().
const char * test000064::MODEL_STRING9 static protected
Definition at line 71 of file test000064.h.
Referenced by test_import_rule_expression_and_hasOnlySubstanceUnits_5().
CCopasiDataModel * test000064::pCOPASIDATAMODEL = NULL static protected
These tests are supposed to make sure that assignments on a species with the hasOnlySubstanceUnits flag set are exported correctly. It tests rules and event assignments with and without the flag set.
Definition at line 98 of file test000064.h.
Referenced by setUp(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test_export_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test_export_rule_expression_and_hasOnlySubstanceUnits_1(), test_export_rule_expression_and_hasOnlySubstanceUnits_2(), test_export_rule_expression_and_hasOnlySubstanceUnits_3(), test_export_rule_expression_and_hasOnlySubstanceUnits_4(), test_export_rule_expression_and_hasOnlySubstanceUnits_5(), test_export_rule_expression_and_hasOnlySubstanceUnits_6(), test_export_rule_expression_and_hasOnlySubstanceUnits_7(), test_export_rule_expression_and_hasOnlySubstanceUnits_8(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test_import_rule_expression_and_hasOnlySubstanceUnits_7(), and test_import_rule_expression_and_hasOnlySubstanceUnits_8().
The documentation for this class was generated from the following files:
test000064.h
test000064.cpp