COPASI API: CQEffectDescription.cpp File Reference
CQEffectDescription.cpp File Reference
#include <QtGui/QGraphicsItem>
#include <QtGui/QGraphicsEffect>
#include <qlayout/CQEffectDescription.h>
#include <qlayout/CQCopasiEffect.h>
Functions
QColor interpolate (const QColor &a, const QColor &b, float t)
qreal linear (qreal a, qreal b, qreal t)
Function Documentation
QColor interpolate (const QColor & a, const QColor & b, float t)
Interpolate between a, and b
0.0 <= t <= 1.0
Definition at line 22 of file CQEffectDescription.cpp.
References linear().
Referenced by CQEffectDescription::applyToScene().
 {
   int ah, as, av, aa;
   a.getHsv(&ah, &as, &av, &aa);
   int bh, bs, bv, ba;
   b.getHsv(&bh, &bs, &bv, &ba);
   int rh, rs, rv, ra;
   rh = linear(ah, bh, t);
   rs = linear(as, bs, t);
   rv = linear(av, bv, t);
   ra = linear(aa, ba, t);
   return QColor::fromHsv(rh, rs, rv, ra);
 }
qreal linear (qreal a, qreal b, qreal t)
Definition at line 12 of file CQEffectDescription.cpp.
Referenced by CQEffectDescription::applyToScene(), CGA::creation(), getGradient(), interpolate(), COptMethodEP2::optimise(), and COptMethodHGASA::optimise().
 {
   return a * (1 - t) + b * t;
 }