COPASI API: CMIRIAMResourceObject Class Reference
CMIRIAMResourceObject Class Reference
#include <CConstants.h>
Public Member Functions
CMIRIAMResourceObject (CRDFNode *pNode)
CMIRIAMResourceObject (const std::string &displayName, const std::string &id)
CMIRIAMResourceObject (const CMIRIAMResourceObject &src)
std::string getDisplayName () const
const std::string & getId () const
std::string getIdentifiersOrgURL () const
CRDFNode * getNode () const
size_t getResource (const std::string &URI)
std::string getURI () const
bool isValid () const
bool isValid (const std::string &URI) const
bool setDisplayName (const std::string &displayName)
bool setId (const std::string &id)
bool setNode (CRDFNode *pNode)
bool setURI (const std::string &URI)
virtual ~CMIRIAMResourceObject ()
Static Public Member Functions
static const CMIRIAMResources & getResourceList ()
static void setMIRIAMResources (const CMIRIAMResources *pResources)
Private Member Functions
CMIRIAMResourceObject ()
void extractId (const std::string &URI)
Static Private Member Functions
static std::string trimId (const std::string &id)
static void unescapeId (std::string &id)
Private Attributes
std::string mId
CRDFNode * mpNode
size_t mResource
Static Private Attributes
static const CMIRIAMResources * mpResources = NULL
Detailed Description
Definition at line 23 of file CConstants.h.
Constructor & Destructor Documentation
CMIRIAMResourceObject::CMIRIAMResourceObject () private
CMIRIAMResourceObject::CMIRIAMResourceObject (CRDFNode * pNode)
Definition at line 72 of file CConstants.cpp.
References CRDFNode::getObject(), CRDFObject::getResource(), mpNode, and setURI().
                                                             :
   mId(),
   mpNode(pNode)
 {
   if (mpNode != NULL)
     setURI(mpNode->getObject().getResource());
 }
CMIRIAMResourceObject::CMIRIAMResourceObject (const std::string & displayName, const std::string & id)
Definition at line 86 of file CConstants.cpp.
References mId, and setDisplayName().
                                                                                                :
   mResource(C_INVALID_INDEX),
   mId(),
   mpNode(NULL)
 {
   setDisplayName(displayName);
   mId = id;
 }
CMIRIAMResourceObject::CMIRIAMResourceObject (const CMIRIAMResourceObject & src)
Definition at line 95 of file CConstants.cpp.
                                                                              :
   mResource(src.mResource),
   mId(src.mId),
   mpNode(NULL)
 {}
CMIRIAMResourceObject::~CMIRIAMResourceObject () virtual
Destructor
Definition at line 262 of file CConstants.cpp.
 {}
Member Function Documentation
void CMIRIAMResourceObject::extractId (const std::string & URI) private
Definition at line 205 of file CConstants.cpp.
References CCopasiParameterGroup::beginIndex(), C_INVALID_INDEX, CCopasiParameterGroup::endIndex(), CMIRIAMResource::getIdentifiersOrgURL(), CMIRIAMResources::getMIRIAMResource(), CMIRIAMResource::getMIRIAMURI(), mId, mpResources, mResource, and unescapeId().
Referenced by setURI().
 {
   mId = "";
   // Check whether the resource is known.
   if (mpResources == NULL ||
       mResource == C_INVALID_INDEX)
     {
       mId = URI;
       return;
     }
   int offset;
   const std::string * pTmp = & mpResources->getMIRIAMResource(mResource).getMIRIAMURI();
   if (URI.substr(0, pTmp->length()) == *pTmp &&
       URI.length() > pTmp->length())
     {
       offset = (pTmp->at(pTmp->length() - 1) == '/') ? 0 : 1;
       mId = URI.substr(pTmp->length() + offset);
     }
   if (mId == "")
     {
       std::string Tmp = mpResources->getMIRIAMResource(mResource).getIdentifiersOrgURL();
       if (URI.substr(0, Tmp.length()) == Tmp &&
           URI.length() > Tmp.length())
         {
           offset = (Tmp[Tmp.length() - 1] == '/') ? 0 : 1;
           mId = URI.substr(Tmp.length() + offset);
         }
     }
   if (mId == "")
     {
       // We need to check for deprecated URIs
       const CCopasiParameterGroup * pDeprecated = &(mpResources->getMIRIAMResource(mResource)).getMIRIAMDeprecated();
       CCopasiParameterGroup::index_iterator itDeprecated = pDeprecated->beginIndex();
       CCopasiParameterGroup::index_iterator endDeprecated = pDeprecated->endIndex();
       for (; itDeprecated != endDeprecated; ++itDeprecated)
         if (URI.substr(0, (*itDeprecated)->getValue().pSTRING->length()) == *(*itDeprecated)->getValue().pSTRING &&
             URI.length() > (*itDeprecated)->getValue().pSTRING->length())
           {
             const std::string& uri = *(*itDeprecated)->getValue().pSTRING;
             offset = (uri[uri.length() - 1] == '/') ? 0 : 1;
             mId = URI.substr(uri.length() + offset);
             break;
           }
     }
   unescapeId(mId);
   return;
 }
std::string CMIRIAMResourceObject::getDisplayName () const
Definition at line 173 of file CConstants.cpp.
References C_INVALID_INDEX, CMIRIAMResources::getMIRIAMResource(), mpResources, and mResource.
Referenced by CBiologicalDescription::getResource(), and CReference::getResource().
 {
   // Check whether the resource is known.
   if (mResource == C_INVALID_INDEX)
     return "";
   return (mpResources->getMIRIAMResource(mResource)).getMIRIAMDisplayName();
 }
const std::string & CMIRIAMResourceObject::getId () const
Definition at line 116 of file CConstants.cpp.
References mId.
Referenced by CBiologicalDescription::getId(), and CReference::getId().
 {return mId;}
std::string CMIRIAMResourceObject::getIdentifiersOrgURL () const
Definition at line 138 of file CConstants.cpp.
References CMIRIAMResource::getIdentifiersOrgURL(), CMIRIAMResources::getMIRIAMResource(), mId, mpResources, and mResource.
Referenced by CQMiriamWidget::slotBtnBrowseDescription(), CQMiriamWidget::slotBtnBrowseReference(), and CSBMLExporter::updateMIRIAMAnnotation().
 {
   std::string URL = mpResources->getMIRIAMResource(mResource).getIdentifiersOrgURL();
   if (URL == "http://identifiers.org/unknown")
     {
       return mId;
     }
   return URL + "/" + mId;
 }
CRDFNode * CMIRIAMResourceObject::getNode () const
Definition at line 160 of file CConstants.cpp.
References mpNode.
Referenced by CRDFNode::setFieldValue().
 {return mpNode;}
size_t CMIRIAMResourceObject::getResource (const std::string & URI)
Definition at line 23 of file CConstants.cpp.
References CMIRIAMResources::getMIRIAMResourceIndex(), and mpResources.
Referenced by setURI().
 {return mpResources->getMIRIAMResourceIndex(URI);}
const CMIRIAMResources & CMIRIAMResourceObject::getResourceList () static
Definition at line 27 of file CConstants.cpp.
References mpResources.
 {return *mpResources;}
std::string CMIRIAMResourceObject::getURI () const
Definition at line 133 of file CConstants.cpp.
References CMIRIAMResources::getMIRIAMResource(), mId, mpResources, and mResource.
Referenced by CBiologicalDescription::getURI(), CReference::getURI(), CRDFNode::setFieldValue(), CBiologicalDescription::setId(), CReference::setId(), CBiologicalDescription::setResource(), and CReference::setResource().
 {
   return (mpResources->getMIRIAMResource(mResource)).getMIRIAMURI() + ":" + mId;
 }
bool CMIRIAMResourceObject::isValid () const
Definition at line 182 of file CConstants.cpp.
References C_INVALID_INDEX, mId, and mResource.
Referenced by CBiologicalDescription::clearInvalidEntries(), CReference::clearInvalidEntries(), CRDFNode::setFieldValue(), setId(), and setURI().
 {
   // Check whether the resource is known.
   if (mResource == C_INVALID_INDEX)
     return false;
   // Empty IDs are not allowed.
   if (mId == "")
     return false;
   // TODO Check whether the Id matches the regular expression.
   return true;
 }
bool CMIRIAMResourceObject::isValid (const std::string & URI) const
Definition at line 196 of file CConstants.cpp.
References C_INVALID_INDEX, CMIRIAMResources::getMIRIAMResourceIndex(), mpResources, and mResource.
 {
   if (mpResources->getMIRIAMResourceIndex(URI) != mResource ||
       mResource == C_INVALID_INDEX)
     return false;
   return true;
 }
bool CMIRIAMResourceObject::setDisplayName (const std::string & displayName)
Definition at line 163 of file CConstants.cpp.
References C_INVALID_INDEX, CMIRIAMResources::getResourceIndexFromDisplayName(), mpResources, and mResource.
Referenced by CMIRIAMResourceObject(), CBiologicalDescription::setResource(), and CReference::setResource().
 {
   mResource = mpResources->getResourceIndexFromDisplayName(displayName);
   if (mResource == C_INVALID_INDEX)
     return false;
   return true;
 }
bool CMIRIAMResourceObject::setId (const std::string & id)
Definition at line 101 of file CConstants.cpp.
References C_INVALID_INDEX, isValid(), mId, mResource, and trimId().
Referenced by CBiologicalDescription::setId(), and CReference::setId().
 {
   mId = trimId(id);
   // Empty IDs are not allowed.
   if (mId == "")
     return false;
   // Check whether the resource is known.
   if (mResource == C_INVALID_INDEX)
     return true;
   return isValid();
 }
void CMIRIAMResourceObject::setMIRIAMResources (const CMIRIAMResources * pResources) static
Definition at line 81 of file CConstants.cpp.
References mpResources.
Referenced by CConfigurationFile::elevateChildren(), and CopasiUI3Window::slotUpdateMIRIAMFinished().
 {
   mpResources = pResources;
 }
bool CMIRIAMResourceObject::setNode (CRDFNode * pNode)
Definition at line 150 of file CConstants.cpp.
References CRDFNode::getObject(), CRDFObject::getResource(), mpNode, and setURI().
Referenced by CReference::CReference(), CReference::setId(), and CReference::setResource().
 {
   mpNode = pNode;
   if (mpNode != NULL)
     return setURI(mpNode->getObject().getResource());
   return true;
 }
bool CMIRIAMResourceObject::setURI (const std::string & URI)
Definition at line 119 of file CConstants.cpp.
References C_INVALID_INDEX, extractId(), getResource(), isValid(), MCAnnotation, mResource, and CCopasiMessage::WARNING.
Referenced by CReference::clearInvalidEntries(), CMIRIAMResourceObject(), and setNode().
 {
   mResource = getResource(URI);
   if (mResource == C_INVALID_INDEX)
     {
       CCopasiMessage(CCopasiMessage::WARNING, MCAnnotation + 4, URI.c_str());
     }
   extractId(URI);
   return isValid();
 }
std::string CMIRIAMResourceObject::trimId (const std::string & id) static private
Definition at line 48 of file CConstants.cpp.
Referenced by setId().
 {
   std::string Id = id;
   /* Trim leading and trailing whitespaces from the string */
   std::string::size_type begin = Id.find_first_not_of("\x20\x09\x0d\x0a");
   if (begin == std::string::npos)
     {
       Id = "";
     }
   else
     {
       std::string::size_type end = id.find_last_not_of("\x20\x09\x0d\x0a");
       if (end == std::string::npos)
         Id = id.substr(begin);
       else
         Id = id.substr(begin, end - begin + 1);
     }
   return Id;
 }
void CMIRIAMResourceObject::unescapeId (std::string & id) static private
Definition at line 31 of file CConstants.cpp.
References CCopasiXMLInterface::utf8().
Referenced by extractId().
 {
   // We have to convert all %[0-9a-fA-F][0-9a-fA-F] character sequences to utf8 characters.
   std::string::size_type pos;
   for (pos = 0; pos < id.length(); pos++)
     if (id[pos] == '%' &&
         id.find_first_not_of("0123456789abcdefABCDEF", pos + 1) > pos + 2)
       {
         char ascii[2];
         ascii[0] = (unsigned char) strtol(id.substr(pos + 1 , 2).c_str(), NULL, 16);
         ascii[1] = 0x0;
         id.replace(pos, 3, CCopasiXMLInterface::utf8(ascii));
       }
 }
Member Data Documentation
std::string CMIRIAMResourceObject::mId private
Definition at line 80 of file CConstants.h.
Referenced by CMIRIAMResourceObject(), extractId(), getId(), getIdentifiersOrgURL(), getURI(), isValid(), and setId().
CRDFNode* CMIRIAMResourceObject::mpNode private
Definition at line 81 of file CConstants.h.
Referenced by CMIRIAMResourceObject(), getNode(), and setNode().
const CMIRIAMResources * CMIRIAMResourceObject::mpResources = NULL static private
Definition at line 73 of file CConstants.h.
Referenced by extractId(), getDisplayName(), getIdentifiersOrgURL(), getResource(), getResourceList(), getURI(), isValid(), setDisplayName(), and setMIRIAMResources().
size_t CMIRIAMResourceObject::mResource private
Definition at line 79 of file CConstants.h.
Referenced by extractId(), getDisplayName(), getIdentifiersOrgURL(), getURI(), isValid(), setDisplayName(), setId(), and setURI().
The documentation for this class was generated from the following files:
CConstants.h
CConstants.cpp