COPASI API: CNodeContextIterator< Node, Context > Class Template Reference
CNodeContextIterator< Node, Context > Class Template Reference
#include <CNodeIterator.h>
Classes
class CStackElement
Public Member Functions
CNodeContextIterator ()
CNodeContextIterator (const CNodeContextIterator &src)
CNodeContextIterator (Node *pNode, Context *pParentContext=NULL)
Context & context ()
CNodeIteratorMode::State end () const
CNodeIteratorMode::Flag getProcessingModes () const
size_t level ()
const CNodeIteratorMode::State & next ()
Node * operator* ()
Node * operator-> ()
Context * parentContextPtr ()
const CNodeIteratorMode::State & processingMode () const
void setProcessingModes (const CNodeIteratorMode::Flag &processingModes)
const CNodeIteratorMode::State & skipChildren ()
~CNodeContextIterator ()
Private Member Functions
void increment ()
Private Attributes
CNodeIteratorMode::State mCurrentMode
CNodeIteratorMode::Flag mProcessingModes
std::stack< CStackElement > mStack
Detailed Description
template<class Node, class Context>
class CNodeContextIterator< Node, Context >
Definition at line 40 of file CNodeIterator.h.
Constructor & Destructor Documentation
template<class Node, class Context> CNodeContextIterator< Node, Context >::CNodeContextIterator () inline
Default constructor
Definition at line 126 of file CNodeIterator.h.
                         :
     mStack(),
     mCurrentMode(CNodeIteratorMode::End),
     mProcessingModes((CNodeIteratorMode::State)(CNodeIteratorMode::After | CNodeIteratorMode::End))
   {}
template<class Node, class Context> CNodeContextIterator< Node, Context >::CNodeContextIterator (const CNodeContextIterator< Node, Context > & src) inline
Copy constructor
Parameters
const CNodeContextIterator & src
Definition at line 136 of file CNodeIterator.h.
                                                         :
     mStack(src.mStack),
     mCurrentMode(src.mCurrentMode),
     mProcessingModes(src.mProcessingModes)
   {}
template<class Node, class Context> CNodeContextIterator< Node, Context >::CNodeContextIterator (Node * pNode, Context * pParentContext = NULL) inline
Constructor
Parameters
Node * pNode
Context * pParentContext (default: NULL)
Definition at line 147 of file CNodeIterator.h.
                                                                      :
     mStack(),
     mCurrentMode(CNodeIteratorMode::Start),
     mProcessingModes((CNodeIteratorMode::State)(CNodeIteratorMode::After | CNodeIteratorMode::End))
   {
     mStack.push(CStackElement(pNode, pParentContext));
   }
template<class Node, class Context> CNodeContextIterator< Node, Context >::~CNodeContextIterator () inline
Destructor
Definition at line 158 of file CNodeIterator.h.
 {}
Member Function Documentation
template<class Node, class Context> Context& CNodeContextIterator< Node, Context >::context () inline
Retrieve the context of the current node.
Returns
Context & context
Definition at line 291 of file CNodeIterator.h.
Referenced by CEvaluationNode::buildBerkeleyMadonnaString(), CEvaluationNode::buildCCodeString(), CEvaluationNode::buildDisplayString(), CEvaluationNode::buildInfix(), CEvaluationNode::buildMMLString(), CEvaluationNode::buildXPPString(), CMathEventN::CTrigger::compile(), CMathContainer::copyBranch(), CEvaluationNode::copyBranch(), CMathEventN::CTrigger::countRoots(), CFunctionAnalyzer::evaluateNode(), CEvaluationNode::findTopMinus(), CEvaluationTree::fromAST(), and CReaction::objects2variables().
 {return mStack.top().mContext;}
template<class Node, class Context> CNodeIteratorMode::State CNodeContextIterator< Node, Context >::end () const inline
Retrieve the end of the iterator, i.e., the
Definition at line 285 of file CNodeIterator.h.
Referenced by CEvaluationNode::buildBerkeleyMadonnaString(), CEvaluationNode::buildCCodeString(), CEvaluationNode::buildDisplayString(), CEvaluationNode::buildInfix(), CEvaluationNode::buildMMLString(), CEvaluationNode::buildXPPString(), CMathEventN::CTrigger::compile(), CMathContainer::copyBranch(), CEvaluationNode::copyBranch(), CMathEventN::CTrigger::countRoots(), CFunctionAnalyzer::evaluateNode(), CEvaluationNode::findTopMinus(), CEvaluationTree::fromAST(), and CReaction::objects2variables().
 {return CNodeIteratorMode::End;}
template<class Node, class Context> CNodeIteratorMode::Flag CNodeContextIterator< Node, Context >::getProcessingModes () const inline
Retrieve the processing modes to which the method next will advance the iterator.
Returns
CNodeIteratorMode::Flag processingModes
Definition at line 317 of file CNodeIterator.h.
 {return (mProcessingModes & ~CNodeIteratorMode::End);}
template<class Node, class Context> void CNodeContextIterator< Node, Context >::increment () inline private
This method moves the iterator to the next node in the tree. The tree is traversed depth first. A return value of false indicates that the tree has been completed traversed.
Please note that the iterator points to the same node twice, once before the first child and once after the last child to allow pre and post processing. This behavior is also true for childless nodes. To determine whether the iterator is in the pre or post processing phase one may check the nextChildIndex where zero indicates pre and None indicates post processing.
Returns
bool moreNodes
Definition at line 175 of file CNodeIterator.h.
Referenced by CNodeContextIterator< Node, int >::next().
   {
     if (mStack.empty())
       {
         mCurrentMode = CNodeIteratorMode::End;
         return;
       }
     CStackElement & Current = mStack.top();
     if (Current.mNextChildIndex < Current.mChildCount)
       {
         mStack.push(CStackElement(static_cast< Node * >(Current.mpNode->getChild(Current.mNextChildIndex++)), &Current.mContext));
         mCurrentMode = CNodeIteratorMode::Before;
         return;
       }
     if (Current.mNextChildIndex == Current.mChildCount)
       {
         Current.mNextChildIndex++;
         mCurrentMode = CNodeIteratorMode::After;
         return;
       }
     mStack.pop();
     if (mStack.empty())
       {
         mCurrentMode = CNodeIteratorMode::End;
         return;
       }
     CStackElement & Parent = mStack.top();
     if (Parent.mNextChildIndex < Parent.mChildCount)
       {
         mCurrentMode = CNodeIteratorMode::Intermediate;
       }
     else
       {
         mCurrentMode = CNodeIteratorMode::After;
         Parent.mNextChildIndex++;
       }
     return;
   }
template<class Node, class Context> size_t CNodeContextIterator< Node, Context >::level () inline
The nesting level of the tree. Note, the nesting level of the root of the tree is 1. This is to distinguish its level from the end of the iterator which reports 0.
Definition at line 304 of file CNodeIterator.h.
 {return mStack.size();}
template<class Node, class Context> const CNodeIteratorMode::State& CNodeContextIterator< Node, Context >::next () inline
This method moves the iterator to the next node based on the setting of the processing modes and returns the processing mode of the iterator.
Returns
const CNodeIteratorMode::State & processingMode
Definition at line 233 of file CNodeIterator.h.
Referenced by CEvaluationNode::buildBerkeleyMadonnaString(), CEvaluationNode::buildCCodeString(), CEvaluationNode::buildDisplayString(), CEvaluationNode::buildInfix(), CEvaluationNode::buildMMLString(), CEvaluationNode::buildXPPString(), CMathEventN::CTrigger::compile(), CMathContainer::copyBranch(), CEvaluationNode::copyBranch(), CMathEventN::CTrigger::countRoots(), CFunctionAnalyzer::evaluateNode(), CEvaluationNode::findTopMinus(), CEvaluationTree::fromAST(), and CReaction::objects2variables().
   {
     if (mCurrentMode != CNodeIteratorMode::Start)
       {
         increment();
       }
     else
       {
         mCurrentMode = CNodeIteratorMode::Before;
       }
     while (!(mProcessingModes & mCurrentMode))
       {
         increment();
       }
     return mCurrentMode;
   }
template<class Node, class Context> Node* CNodeContextIterator< Node, Context >::operator* () inline
Dereference the iterator
Returns
Node * pNode
Definition at line 268 of file CNodeIterator.h.
 {return mStack.top().mpNode;}
template<class Node, class Context> Node* CNodeContextIterator< Node, Context >::operator-> () inline
Dereference the iterator
Returns
Node * pNode
Definition at line 274 of file CNodeIterator.h.
 {return mStack.top().mpNode;}
template<class Node, class Context> Context* CNodeContextIterator< Node, Context >::parentContextPtr () inline
Retrieve the pointer to the parent node context if it exists.
Returns
Context * parentContextPtr.
Definition at line 297 of file CNodeIterator.h.
Referenced by CEvaluationNode::buildBerkeleyMadonnaString(), CEvaluationNode::buildCCodeString(), CEvaluationNode::buildDisplayString(), CEvaluationNode::buildInfix(), CEvaluationNode::buildMMLString(), CEvaluationNode::buildXPPString(), CMathEventN::CTrigger::compile(), CMathContainer::copyBranch(), CEvaluationNode::copyBranch(), CMathEventN::CTrigger::countRoots(), CFunctionAnalyzer::evaluateNode(), CEvaluationNode::findTopMinus(), CEvaluationTree::fromAST(), and CReaction::objects2variables().
 {return mStack.top().mpParentContext;}
template<class Node, class Context> const CNodeIteratorMode::State& CNodeContextIterator< Node, Context >::processingMode () const inline
Retrieve the processing mode
Returns
const CNodeIteratorMode::State & processingMode
Definition at line 280 of file CNodeIterator.h.
Referenced by CMathEventN::CTrigger::compile(), CMathEventN::CTrigger::countRoots(), and CEvaluationNode::findTopMinus().
 {return mCurrentMode;}
template<class Node, class Context> void CNodeContextIterator< Node, Context >::setProcessingModes (const CNodeIteratorMode::Flag & processingModes) inline
Set the processing modes to which the method next will advance the iterator. Note, the iterator will always stop at the end.
Parameters
const CNodeIteratorMode::Flag & processingModes
Definition at line 311 of file CNodeIterator.h.
Referenced by CMathEventN::CTrigger::compile(), CMathEventN::CTrigger::countRoots(), and CEvaluationNode::findTopMinus().
 {mProcessingModes = (processingModes | CNodeIteratorMode::End);}
template<class Node, class Context> const CNodeIteratorMode::State& CNodeContextIterator< Node, Context >::skipChildren () inline
This method moves the iterator beyond the last child.
Definition at line 255 of file CNodeIterator.h.
Referenced by CMathEventN::CTrigger::compile(), CMathEventN::CTrigger::countRoots(), and CEvaluationNode::findTopMinus().
   {
     CStackElement & Current = mStack.top();
     Current.mNextChildIndex = Current.mChildCount + 1;
     mCurrentMode = CNodeIteratorMode::After;
     return mCurrentMode;
   }
Member Data Documentation
template<class Node, class Context> CNodeIteratorMode::State CNodeContextIterator< Node, Context >::mCurrentMode private
The current processing mode.
Definition at line 328 of file CNodeIterator.h.
Referenced by CNodeContextIterator< Node, int >::increment(), CNodeContextIterator< Node, int >::next(), CNodeContextIterator< Node, int >::processingMode(), and CNodeContextIterator< Node, int >::skipChildren().
template<class Node, class Context> CNodeIteratorMode::Flag CNodeContextIterator< Node, Context >::mProcessingModes private
The processing modes to which the method next will advance the iterator
Definition at line 333 of file CNodeIterator.h.
Referenced by CNodeContextIterator< Node, int >::getProcessingModes(), CNodeContextIterator< Node, int >::next(), and CNodeContextIterator< Node, int >::setProcessingModes().
template<class Node, class Context> std::stack< CStackElement > CNodeContextIterator< Node, Context >::mStack private
A stack representing the nested elements of the tree.
Definition at line 323 of file CNodeIterator.h.
Referenced by CNodeContextIterator< Node, int >::CNodeContextIterator(), CNodeContextIterator< Node, int >::context(), CNodeContextIterator< Node, int >::increment(), CNodeContextIterator< Node, int >::level(), CNodeContextIterator< Node, int >::operator*(), CNodeContextIterator< Node, int >::operator->(), CNodeContextIterator< Node, int >::parentContextPtr(), and CNodeContextIterator< Node, int >::skipChildren().
The documentation for this class was generated from the following file:
CNodeIterator.h