COPASI API: CExpression Class Reference
CExpression Class Reference
#include <CExpression.h>
Public Member Functions
virtual const C_FLOAT64 & calcValue ()
CExpression (const std::string &name="Expression", const CCopasiContainer *pParent=NULL)
CExpression (const CExpression &src, const CCopasiContainer *pParent=NULL)
virtual bool compile (std::vector< CCopasiContainer * > listOfContainer=CCopasiContainer::EmptyList)
std::string getBerkeleyMadonnaString () const
std::string getCCodeString () const
const std::string & getDisplayString () const
const std::vector
< CCopasiContainer * > & getListOfContainer () const
const CObjectInterface * getNodeObject (const CCopasiObjectName &CN) const
std::string getXPPString () const
void refresh ()
virtual bool setInfix (const std::string &infix)
void setIsBoolean (const bool &booleanRequired)
bool updateInfix ()
void writeMathML (std::ostream &out, bool fullExpand, size_t l) const
virtual ~CExpression ()
Public Member Functions inherited from CEvaluationTree
bool calls (std::set< std::string > &list) const
CEvaluationTree (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=Function)
CEvaluationTree (const CEvaluationTree &src, const CCopasiContainer *pParent=NULL)
virtual bool compile ()
bool dependsOnTree (const std::string &name) const
CCopasiObject::DataObjectSet getDeletedObjects () const
std::string::size_type getErrorPosition () const
const std::string & getInfix () const
const std::vector
< CEvaluationNode * > & getNodeList () const
CEvaluationNode * getRoot ()
const CEvaluationNode * getRoot () const
const CEvaluationTree::Type & getType () const
virtual size_t getVariableIndex (const std::string &name) const
virtual const C_FLOAT64 & getVariableValue (const size_t &index) const
bool hasCircularDependency () const
bool hasDiscontinuity () const
bool isBoolean () const
bool isUsable () const
bool operator== (const CEvaluationTree &rhs) const
virtual bool setRoot (CEvaluationNode *pRootNode)
bool setTree (const ASTNode &pRootNode)
virtual ASTNode * toAST (const CCopasiDataModel *pDataModel) const
bool updateTree ()
virtual ~CEvaluationTree ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CExpression * createInitialExpression (const CExpression &expression, const CCopasiDataModel *pDataModel)
Static Public Member Functions inherited from CEvaluationTree
static CEvaluationTree * copy (const CEvaluationTree &src)
static CEvaluationTree * create (CEvaluationTree::Type type)
static CEvaluationNode * fromAST (const ASTNode *pASTNode)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Attributes
std::string mDisplayString
bool mIsBoolean
const std::vector
< CCopasiContainer * > * mpListOfContainer
Protected Attributes inherited from CEvaluationTree
std::vector< CEvaluationNode * > mCalculationSequence
std::string mInfix
std::vector< CEvaluationNode * > * mpNodeList
CEvaluationNode * mpRoot
CEvaluationTree::Type mType
bool mUsable
C_FLOAT64 mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void initObjects ()
Additional Inherited Members
Public Types inherited from CEvaluationTree
enum Type {
Function = 0, MassAction, PreDefined, UserDefined,
Expression, MathExpression
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CEvaluationTree
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CEvaluationTree
void buildCalculationSequence ()
void calculate ()
bool compileNodes ()
bool parse ()
void setType (const CEvaluationTree::Type &type)
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 28 of file CExpression.h.
Constructor & Destructor Documentation
CExpression::CExpression (const std::string & name = "Expression", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "Expression")
const CCopasiContainer * pParent (default: NULL)
Definition at line 26 of file CExpression.cpp.
References initObjects().
Referenced by createInitialExpression().
                                                           :
   CEvaluationTree(name, pParent, CEvaluationTree::Expression),
   mpListOfContainer(NULL),
   mDisplayString(""),
   mIsBoolean(false)
 {
   initObjects();
 }
CExpression::CExpression (const CExpression & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CExpression & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 36 of file CExpression.cpp.
References CEvaluationTree::compile(), and initObjects().
                                                           :
   CEvaluationTree(src, pParent),
   mpListOfContainer(NULL),
   mDisplayString(src.mDisplayString),
   mIsBoolean(src.mIsBoolean)
 {
   initObjects();
   compile();
 }
CExpression::~CExpression () virtual
Destructor
Definition at line 47 of file CExpression.cpp.
 {}
Member Function Documentation
const C_FLOAT64 & CExpression::calcValue () virtual
Calculates the value of the function
Returns
const C_FLOAT64 & result
Definition at line 122 of file CExpression.cpp.
References CEvaluationTree::calculate(), and CEvaluationTree::mValue.
Referenced by SBMLImporter::applyStoichiometricExpressions(), CEvaluationNodeCall::calculate(), CModelEntity::calculate(), COptProblem::calculate(), CMathTrigger::calculate(), CMetab::calculate(), CMathEvent::calculateDelayedTime(), CModelEntity::compile(), CMetab::compileInitialValueDependencies(), refresh(), CMetab::refreshInitialConcentration(), and CModelEntity::refreshInitialValue().
 {
   calculate();
   return mValue;
 }
bool CExpression::compile (std::vector< CCopasiContainer * > listOfContainer = CCopasiContainer::EmptyList) virtual
Compile the evaluation tree.
Parameters
std::vector< CCopasiContainer * > listOfContainer (Default: CCopasiContainer::EmptyList)
Returns
bool success
Definition at line 97 of file CExpression.cpp.
References CEvaluationNode::buildDisplayString(), CEvaluationNode::buildInfix(), CEvaluationTree::compileNodes(), CCopasiObject::getObjectParent(), mDisplayString, CEvaluationTree::mInfix, mpListOfContainer, and CEvaluationTree::mpRoot.
Referenced by CMathEventN::CTrigger::allocate(), SBMLImporter::applyStoichiometricExpressions(), CMathEventN::CAssignment::compile(), CEventAssignment::compile(), CEvaluationNodeCall::compile(), CModelEntity::compile(), CMathEventN::CTrigger::compile(), CMathTrigger::compile(), CModelParameter::compile(), CEvent::compile(), CMathEventN::compile(), CMetab::compile(), CMathEvent::compile(), CMetab::compileInitialValueDependencies(), CModelExpansion::duplicateEvent(), COptProblem::initialize(), CEvent::setDelayExpressionPtr(), CMathObject::setExpression(), CEventAssignment::setExpressionPtr(), CEvent::setPriorityExpressionPtr(), and CEvent::setTriggerExpressionPtr().
 {
   if (getObjectParent() != NULL)
     listOfContainer.push_back(getObjectParent());
   mpListOfContainer = & listOfContainer;
   bool success = compileNodes();
   if (mpRoot)
     {
       mDisplayString = mpRoot->buildDisplayString();
       mInfix = mpRoot->buildInfix();
     }
   else
     {
       mDisplayString = "";
       mInfix = "";
     }
   mpListOfContainer = NULL;
   return success;
 }
CExpression * CExpression::createInitialExpression (const CExpression & expression, const CCopasiDataModel * pDataModel) static
Creates the corresponding initial expression for the given expression by converting each transient value to the corresponding initial value.
Parameters
const CExpression & expression
Returns
CExpression * pInitialExpression
Definition at line 219 of file CExpression.cpp.
References CExpression(), CCopasiObject::getCN(), CMetab::getConcentrationReference(), CMetab::getInitialConcentrationReference(), CModelEntity::getInitialValueReference(), CCopasiMessage::getLastMessage(), CEvaluationTree::getNodeList(), CCopasiContainer::getObject(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectParent(), CModelEntity::getValueReference(), CEvaluationNodeObject::setData(), CCopasiMessage::size(), and CEvaluationTree::updateTree().
Referenced by CModelEntity::compile(), CMetab::compile(), and CModelEntity::setStatus().
 {
   size_t Size = CCopasiMessage::size();
   CExpression * pInitialExpression = new CExpression(expression, expression.getObjectParent());
   std::vector< CEvaluationNode * > * pNodeList =
     const_cast< std::vector< CEvaluationNode * > * >(&pInitialExpression->getNodeList());
   std::vector< CEvaluationNode * >::iterator it = pNodeList->begin();
   std::vector< CEvaluationNode * >::iterator end = pNodeList->end();
   CEvaluationNodeObject * pNode;
   const CCopasiObject * pObject;
   const CCopasiContainer * pObjectParent;
   const CModelEntity * pEntity;
   const CMetab * pMetab;
   for (; it != end; ++it)
     {
       if ((pNode = dynamic_cast< CEvaluationNodeObject * >(*it)) != NULL)
         {
           assert(pDataModel != NULL);
           if ((pObject = static_cast< const CCopasiObject * >(pDataModel->getObject(pNode->getObjectCN()))) != NULL &&
               (pObjectParent = pObject->getObjectParent()) != NULL &&
               (pEntity = dynamic_cast<const CModelEntity * >(pObjectParent)) != NULL)
             {
               if (pEntity->getValueReference() == pObject)
                 pNode->setData("<" + pEntity->getInitialValueReference()->getCN() + ">");
               else if ((pMetab = dynamic_cast<const CMetab * >(pEntity)) != NULL &&
                        pMetab->getConcentrationReference() == pObject)
                 pNode->setData("<" + pMetab->getInitialConcentrationReference()->getCN() + ">");
             }
         }
     }
   pInitialExpression->updateTree();
   while (CCopasiMessage::size() > Size)
     CCopasiMessage::getLastMessage();
   return pInitialExpression;
 }
std::string CExpression::getBerkeleyMadonnaString () const
Retrieve the display string in Berkeley Madonna syntax.
Definition at line 175 of file CExpression.cpp.
References CEvaluationNode::buildBerkeleyMadonnaString(), and CEvaluationTree::mpRoot.
 {
   std::string str1;
   if (mpRoot)
     str1 = mpRoot->buildBerkeleyMadonnaString();
   else
     str1 = "";
   return str1;
 }
std::string CExpression::getCCodeString () const
Retrieve the display string in C syntax.
Definition at line 163 of file CExpression.cpp.
References CEvaluationNode::buildCCodeString(), and CEvaluationTree::mpRoot.
 {
   std::string str1;
   if (mpRoot)
     str1 = mpRoot->buildCCodeString();
   else
     str1 = "";
   return str1;
 }
const std::string & CExpression::getDisplayString () const
Retrieve the human readable display string. Note, the expression must be compiled for this return a displayable string.
Returns
const std::string & displayString
Definition at line 160 of file CExpression.cpp.
References mDisplayString.
Referenced by CQParameterOverviewDM::assignmentData(), CQEventDM::data(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), and operator<<().
 {return mDisplayString;}
const std::vector< CCopasiContainer * > & CExpression::getListOfContainer () const
Retrieve the list of container used for compile
Returns
const std::vector< CCopasiContainer * > & listOfContainer
Definition at line 148 of file CExpression.cpp.
References mpListOfContainer.
 {return *mpListOfContainer;}
const CObjectInterface * CExpression::getNodeObject (const CCopasiObjectName & CN) const
Retrieve a pointer to the object defined by CN. This method may only be called during compile() since the list mpListOfContainer is only valid then.
Parameters
const CCopasiObjectName & CN
Returns
const CObjectInterface * value
Definition at line 132 of file CExpression.cpp.
References CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDataModel(), mpListOfContainer, and CCopasiDataModel::ObjectFromCN().
Referenced by CEvaluationNodeObject::compile().
 {
   const CCopasiDataModel* pDataModel = getObjectDataModel();
   if (pDataModel == NULL) return NULL;
   if (mpListOfContainer != NULL)
     {
       return pDataModel->ObjectFromCN(*mpListOfContainer, CN);
     }
   else
     {
       return pDataModel->getDataObject(CN);
     }
 }
std::string CExpression::getXPPString () const
Retrieve the display string in XPPAUT syntax.
Definition at line 187 of file CExpression.cpp.
References CEvaluationNode::buildXPPString(), and CEvaluationTree::mpRoot.
 {
   std::string str1;
   if (mpRoot)
     str1 = mpRoot->buildXPPString();
   else
     str1 = "";
   return str1;
 }
void CExpression::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 49 of file CExpression.cpp.
References CCopasiContainer::getObject(), refresh(), and CCopasiObject::setRefresh().
Referenced by CExpression().
 {
   CObjectInterface * pObject =
     const_cast< CObjectInterface * >(getObject(CCopasiObjectName("Reference=Value")));
   assert(pObject != NULL);
   static_cast< CCopasiObject * >(pObject)->setRefresh(this, &CExpression::refresh);
 }
void CExpression::refresh ()
Refresh the value of the expression
Definition at line 129 of file CExpression.cpp.
References calcValue().
Referenced by CMathTrigger::CRootFinder::initObjects(), and initObjects().
 {calcValue();}
bool CExpression::setInfix (const std::string & infix) virtual
Set the infix description of the tree and compile it.
Parameters
const std::string & infix
Returns
bool success
Reimplemented from CEvaluationTree.
Definition at line 63 of file CExpression.cpp.
References CEvaluationNode::isBoolean(), mIsBoolean, CEvaluationTree::mpNodeList, CEvaluationTree::mpRoot, CEvaluationTree::setInfix(), and CEvaluationNode::VARIABLE.
Referenced by CMathEventN::CTrigger::allocate(), CMathEventN::CAssignment::compile(), CMathEventN::CTrigger::compile(), CMathTrigger::compile(), CMathEventN::compile(), CMathEvent::compile(), CMathObject::compileDependentMass(), CMathObject::compileParticleFlux(), CMathObject::compilePropensity(), CMathObject::compileTotalMass(), CMathObject::createExtensiveODERateExpression(), CMathObject::createExtensiveReactionRateExpression(), CMathObject::createExtensiveValueExpression(), CMathObject::createIntensiveRateExpression(), CMathObject::createIntensiveValueExpression(), CCopasiXMLParser::FunctionElement::end(), CEvent::setDelayExpression(), CEventAssignment::setExpression(), CMathObject::setExpression(), CModelEntity::setExpression(), CModelParameter::setInitialExpression(), CModelEntity::setInitialExpression(), COptProblem::setObjectiveFunction(), CEvent::setPriorityExpression(), and CEvent::setTriggerExpression().
 {
   if (!CEvaluationTree::setInfix(infix)) return false;
   if (mpNodeList == NULL) return true;
   // Check whether the expression has the expected type.
   if (mpRoot != NULL)
     {
       if (mIsBoolean && !mpRoot->isBoolean())
         {
           return false;
         }
       // We wrap a boolean expression in an if construct for
       // non-boolean expressions
       if (!mIsBoolean && mpRoot->isBoolean())
         {
           std::string Infix = "if(" + infix + ", 1, 0)";
           CEvaluationTree::setInfix(Infix);
         }
     }
   // We need to check that the expression does not contain any variables
   std::vector< CEvaluationNode * >::const_iterator it = mpNodeList->begin();
   std::vector< CEvaluationNode * >::const_iterator end = mpNodeList->end();
   for (; it != end; ++it)
     if (((*it)->getType() & 0xFF000000) == CEvaluationNode::VARIABLE)
       return false;
   return true;
 }
void CExpression::setIsBoolean (const bool & booleanRequired)
Set whether this a boolean expression or not
Parameters
const bool & isBoolean
Definition at line 58 of file CExpression.cpp.
References CEvaluationTree::isBoolean(), and mIsBoolean.
Referenced by CMathEventN::CTrigger::allocate(), CMathEventN::CTrigger::compile(), CQValidatorExpression::CQValidatorExpression(), SBMLImporter::importEvent(), CQValidatorExpression::setBooleanRequired(), CMathObject::setExpression(), and CEvent::setTriggerExpression().
 {
   mIsBoolean = isBoolean;
 }
bool CExpression::updateInfix ()
This method performs an infix update if a referenced object has been renamed
Returns
bool success
Definition at line 151 of file CExpression.cpp.
References CEvaluationNode::buildInfix(), CEvaluationTree::mInfix, CEvaluationTree::mpNodeList, and CEvaluationTree::mpRoot.
Referenced by CEvent::getDelayExpression(), CEventAssignment::getExpression(), CModelEntity::getExpression(), CModelEntity::getInitialExpression(), CEvent::getPriorityExpression(), and CEvent::getTriggerExpression().
 {
   if (mpNodeList == NULL) return false;
   mInfix = mpRoot->buildInfix();
   return true;
 }
void CExpression::writeMathML (std::ostream & out, bool fullExpand, size_t l) const
Write display mathml of the expression into the ostream "out" level specifies indentation fullExpand==true means function calls are expanded
Definition at line 201 of file CExpression.cpp.
References CEvaluationNode::buildMMLString(), CEvaluationTree::mpRoot, and SPC.
Referenced by CQExpressionWidget::writeMathML(), and CMMLOutput::writeRHS_ModelEntity().
 {
   if (mpRoot)
     {
       //create empty environment. Variable nodes should not occur in an expression
       std::vector<std::vector<std::string> > env;
       bool flag = false; //TODO include check if parantheses are necessary
       if (flag) out << SPC(l) << "<mfenced>" << std::endl;
       out << mpRoot->buildMMLString(fullExpand, env);
       if (flag) out << SPC(l) << "</mfenced>" << std::endl;
     }
 }
Member Data Documentation
std::string CExpression::mDisplayString protected
Human readable display string.
Definition at line 161 of file CExpression.h.
Referenced by compile(), and getDisplayString().
bool CExpression::mIsBoolean protected
Indicates whether the expression is boolean or not.
Definition at line 166 of file CExpression.h.
Referenced by setInfix(), and setIsBoolean().
const std::vector< CCopasiContainer * >* CExpression::mpListOfContainer protected
Pointer to the list of containers used for compilation.
Definition at line 156 of file CExpression.h.
Referenced by compile(), getListOfContainer(), and getNodeObject().
The documentation for this class was generated from the following files:
CExpression.h
CExpression.cpp