COPASI API: CMiaseModel Class Reference
CMiaseModel Class Reference
#include <CMiaseModel.h>
Public Member Functions
void addChange (CMiaseChange *chnage)
CMiaseModel ()
CMiaseChange * getChange (int num)
CMiaseChange * getLastChange ()
int getNumOfChanges ()
std::string getSource ()
std::string getType ()
void setSource (std::string source)
void setType (std::string type)
~CMiaseModel ()
Public Member Functions inherited from CMiaseBaseEnhanced
CMiaseBaseEnhanced ()
std::string getId ()
std::string getName ()
void setId (std::string id)
void setName (std::string name)
~CMiaseBaseEnhanced ()
Public Member Functions inherited from CMiaseBase
void addAnnotation (CMiaseAnnotation *ann)
void addNotes (CMiaseNotes *notes)
CMiaseBase ()
CMiaseAnnotation * getAnnotation ()
std::string getMetaId ()
CMiaseNotes * getNotes ()
void setAnyNote (std::string anyAnnotation)
void setMetaId (std::string metaId)
void setXmlNs (std::string xmlNs)
~CMiaseBase ()
Private Attributes
std::vector< CMiaseChange * > mListOfChanges
std::string mSource
std::string mType
Detailed Description
Definition at line 83 of file CMiaseModel.h.
Constructor & Destructor Documentation
CMiaseModel::CMiaseModel ()
Definition at line 84 of file CMiaseModel.cpp.
                          : CMiaseBaseEnhanced()
 {}
CMiaseModel::~CMiaseModel ()
Definition at line 87 of file CMiaseModel.cpp.
 {
   //TODO:
   //delete content of following vector:  mListOfChanges
 }
Member Function Documentation
void CMiaseModel::addChange (CMiaseChange * chnage)
Definition at line 113 of file CMiaseModel.cpp.
References mListOfChanges.
Referenced by CMiaseParser::newChange().
 {
   mListOfChanges.push_back(change);
 }
CMiaseChange * CMiaseModel::getChange (int num)
Definition at line 118 of file CMiaseModel.cpp.
References mListOfChanges.
Referenced by CMiaseParser::testDataStructure().
 {
   return mListOfChanges[ num ];
 }
CMiaseChange * CMiaseModel::getLastChange ()
Definition at line 123 of file CMiaseModel.cpp.
References mListOfChanges.
Referenced by CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newChange(), and CMiaseParser::newNotes().
 {
   return mListOfChanges[ mListOfChanges.size() - 1];
 }
int CMiaseModel::getNumOfChanges ()
Definition at line 128 of file CMiaseModel.cpp.
References mListOfChanges.
Referenced by CMiaseParser::testDataStructure().
 {
   return mListOfChanges.size();
 }
std::string CMiaseModel::getSource ()
Definition at line 98 of file CMiaseModel.cpp.
References mSource.
Referenced by CMiaseParser::testDataStructure().
 {
   return mSource;
 }
std::string CMiaseModel::getType ()
Definition at line 93 of file CMiaseModel.cpp.
References mType.
Referenced by CMiaseParser::testDataStructure().
 {
   return mType;
 }
void CMiaseModel::setSource (std::string source)
Definition at line 108 of file CMiaseModel.cpp.
References mSource.
Referenced by CMiaseParser::newModel().
 {
   mSource = source;
 }
void CMiaseModel::setType (std::string type)
Definition at line 103 of file CMiaseModel.cpp.
References mType.
Referenced by CMiaseParser::newModel().
 {
   mType = type;
 }
Member Data Documentation
std::vector< CMiaseChange* > CMiaseModel::mListOfChanges private
Definition at line 109 of file CMiaseModel.h.
Referenced by addChange(), getChange(), getLastChange(), and getNumOfChanges().
std::string CMiaseModel::mSource private
Definition at line 107 of file CMiaseModel.h.
Referenced by getSource(), and setSource().
std::string CMiaseModel::mType private
Definition at line 106 of file CMiaseModel.h.
Referenced by getType(), and setType().
The documentation for this class was generated from the following files:
CMiaseModel.h
CMiaseModel.cpp