COPASI API: CLLineSegment Class Reference
CLLineSegment Class Reference
#include <CLCurve.h>
Public Member Functions
CLLineSegment ()
CLLineSegment (const CLPoint &s, const CLPoint &e)
CLLineSegment (const CLPoint &s, const CLPoint &e, const CLPoint &b1, const CLPoint &b2)
CLLineSegment (const LineSegment &ls)
void exportToSBMLBezier (CubicBezier *c, const std::map< const CCopasiObject *, SBase * > &copasimodelmap) const
void exportToSBMLLineSegment (LineSegment *l, const std::map< const CCopasiObject *, SBase * > &copasimodelmap) const
const CLPoint & getBase1 () const
CLPoint & getBase1 ()
const CLPoint & getBase2 () const
CLPoint & getBase2 ()
const CLPoint & getEnd () const
CLPoint & getEnd ()
const CLPoint & getStart () const
CLPoint & getStart ()
bool isBezier () const
bool operator< (const CLLineSegment &rhs) const
bool operator== (const CLLineSegment &rhs) const
void scale (const double &scaleFactor)
void setBase1 (const CLPoint &p)
void setBase2 (const CLPoint &p)
void setEnd (const CLPoint &p)
void setIsBezier (bool b)
void setStart (const CLPoint &p)
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
CLPoint mBase1
CLPoint mBase2
CLPoint mEnd
bool mIsBezier
CLPoint mStart
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLLineSegment &ls)
Detailed Description
This class describes a line segment.
Definition at line 33 of file CLCurve.h.
Constructor & Destructor Documentation
CLLineSegment::CLLineSegment () inline
Definition at line 47 of file CLCurve.h.
     : mStart(), mEnd(),
       mBase1(), mBase2(),
       mIsBezier(false) {};
CLLineSegment::CLLineSegment (const CLPoint & s, const CLPoint & e) inline
Constructor for a straight line segment
Definition at line 55 of file CLCurve.h.
     : mStart(s), mEnd(e),
       mBase1(), mBase2(),
       mIsBezier(false) {};
CLLineSegment::CLLineSegment (const CLPoint & s, const CLPoint & e, const CLPoint & b1, const CLPoint & b2) inline
Constructor for a bezier segment
Definition at line 63 of file CLCurve.h.
     : mStart(s), mEnd(e),
       mBase1(b1), mBase2(b2),
       mIsBezier(true) {};
CLLineSegment::CLLineSegment (const LineSegment & ls)
constructor from libsbml object
Definition at line 22 of file CLCurve.cpp.
References mBase1, mBase2, and mIsBezier.
   : CLBase(ls),
     mStart(*ls.getStart()),
     mEnd(*ls.getEnd()),
     mBase1(),
     mBase2(),
     mIsBezier(false)
 {
   //handle bezier
   const CubicBezier * cb = dynamic_cast<const CubicBezier *>(&ls);
   if (cb)
     {
       mIsBezier = true;
       mBase1 = CLPoint(*cb->getBasePoint1());
       mBase2 = CLPoint(*cb->getBasePoint2());
     }
 }
Member Function Documentation
void CLLineSegment::exportToSBMLBezier (CubicBezier * c, const std::map< const CCopasiObject *, SBase * > & copasimodelmap) const
This method writes the information of the copasi layout object into the corresponding sbml object. This is only guaranteed to work if isBezier() is true.
Definition at line 41 of file CLCurve.cpp.
References exportToSBMLLineSegment(), getBase1(), and getBase2().
 {
   if (!c) return;
   //first the part that is inherited from line segment
   exportToSBMLLineSegment(c, copasimodelmap);
   //now the rest
   c->setBasePoint1(this->getBase1().getX(), this->getBase1().getY());
   c->setBasePoint2(this->getBase2().getX(), this->getBase2().getY());
 }
void CLLineSegment::exportToSBMLLineSegment (LineSegment * l, const std::map< const CCopasiObject *, SBase * > & copasimodelmap) const
This method writes the information of the copasi layout object into the corresponding sbml object. This is only guaranteed to work if isBezier() is false.
Definition at line 53 of file CLCurve.cpp.
References getEnd(), and getStart().
Referenced by exportToSBMLBezier().
 {
   if (!l) return;
   l->setStart(this->getStart().getX(), this->getStart().getY());
   l->setEnd(this->getEnd().getX(), this->getEnd().getY());
 }
const CLPoint& CLLineSegment::getBase1 () const inline
Definition at line 82 of file CLCurve.h.
References mBase1.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::draw_curve(), CQGLNetworkPainter::drawEdge(), exportToSBMLBezier(), fillItemFromCurve(), CLLayoutRenderer::getCurveBoundingBox(), CQConnectionGraphicsItem::getPath(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CQGLLayoutPainter::mouseMoveEvent(), CLLayoutRenderer::move_curve_object(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), CQGLNetworkPainter::setNodeSize(), and CQGLLayoutPainter::update_status_and_cursor().
 {return mBase1;};
CLPoint& CLLineSegment::getBase1 () inline
Definition at line 84 of file CLCurve.h.
References mBase1.
 {return mBase1;};
const CLPoint& CLLineSegment::getBase2 () const inline
Definition at line 83 of file CLCurve.h.
References mBase2.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::draw_curve(), CQGLNetworkPainter::drawEdge(), exportToSBMLBezier(), fillItemFromCurve(), CLLayoutRenderer::getCurveBoundingBox(), CQConnectionGraphicsItem::getPath(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CQGLLayoutPainter::mouseMoveEvent(), CLLayoutRenderer::move_curve_object(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), CQGLNetworkPainter::setNodeSize(), and CQGLLayoutPainter::update_status_and_cursor().
 {return mBase2;};
CLPoint& CLLineSegment::getBase2 () inline
Definition at line 85 of file CLCurve.h.
References mBase2.
 {return mBase2;};
const CLPoint& CLLineSegment::getEnd () const inline
Definition at line 75 of file CLCurve.h.
References mEnd.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::draw_curve(), CQGLNetworkPainter::drawEdge(), exportToSBMLLineSegment(), fillItemFromCurve(), CLLayoutRenderer::getCurveBoundingBox(), CArrow::getEndOfLine(), CQConnectionGraphicsItem::getPath(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CQGLLayoutPainter::mouseMoveEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), and CQGLNetworkPainter::setNodeSize().
 {return mEnd;};
CLPoint& CLLineSegment::getEnd () inline
Definition at line 77 of file CLCurve.h.
References mEnd.
 {return mEnd;};
const CLPoint& CLLineSegment::getStart () const inline
Definition at line 74 of file CLCurve.h.
References mStart.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::draw_curve(), CQGLNetworkPainter::drawEdge(), exportToSBMLLineSegment(), fillItemFromCurve(), CLLayoutRenderer::getCurveBoundingBox(), CQConnectionGraphicsItem::getPath(), CArrow::getStartOfLine(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CQGLLayoutPainter::mouseMoveEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), CQGLNetworkPainter::setNodeSize(), and CLLayoutRenderer::update_associations().
 {return mStart;};
CLPoint& CLLineSegment::getStart () inline
Definition at line 76 of file CLCurve.h.
References mStart.
 {return mStart;};
bool CLLineSegment::isBezier () const inline
Definition at line 90 of file CLCurve.h.
References mIsBezier.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::draw_curve(), CQGLNetworkPainter::drawEdge(), CCopasiXMLParser::CurveElement::end(), fillItemFromCurve(), CLLayoutRenderer::getCurveBoundingBox(), CQConnectionGraphicsItem::getPath(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::move_curve_object(), CLCurve::moveBy(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), CQGLNetworkPainter::setNodeSize(), and CQGLLayoutPainter::update_status_and_cursor().
 {return mIsBezier;};
bool CLLineSegment::operator< (const CLLineSegment & rhs) const inline
Definition at line 101 of file CLCurve.h.
References mStart.
   {return (mStart < rhs.mStart);};
bool CLLineSegment::operator== (const CLLineSegment & rhs) const inline
Definition at line 94 of file CLCurve.h.
References mBase1, mBase2, mEnd, mIsBezier, and mStart.
   {
     if (mIsBezier) return((mStart == rhs.mStart) && (mEnd == rhs.mEnd) && (mBase1 == rhs.mBase1) && (mBase2 == rhs.mBase2));
     else return ((mStart == rhs.mStart) && (mEnd == rhs.mEnd));
   };
void CLLineSegment::scale (const double & scaleFactor) inline
Definition at line 104 of file CLCurve.h.
References mBase1, mBase2, mEnd, mIsBezier, mStart, and CLPoint::scale().
Referenced by CArrow::scalePosition().
   {
     mStart.scale(scaleFactor); mEnd.scale(scaleFactor);
     if (mIsBezier) {mBase1.scale(scaleFactor); mBase2.scale(scaleFactor);}
   }
void CLLineSegment::setBase1 (const CLPoint & p) inline
Definition at line 87 of file CLCurve.h.
References mBase1.
Referenced by CLLayoutRenderer::revert_curve(), and CCopasiXMLParser::CurveElement::start().
 {mBase1 = p;};
void CLLineSegment::setBase2 (const CLPoint & p) inline
Definition at line 88 of file CLCurve.h.
References mBase2.
Referenced by CLLayoutRenderer::revert_curve(), and CCopasiXMLParser::CurveElement::start().
 {mBase2 = p;};
void CLLineSegment::setEnd (const CLPoint & p) inline
Definition at line 80 of file CLCurve.h.
References mEnd.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), CQGLNetworkPainter::setNodeSize(), and CCopasiXMLParser::CurveElement::start().
 {mEnd = p;};
void CLLineSegment::setIsBezier (bool b) inline
Definition at line 91 of file CLCurve.h.
References mIsBezier.
Referenced by CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::revert_curve(), and CCopasiXMLParser::CurveElement::start().
 {mIsBezier = b;};
void CLLineSegment::setStart (const CLPoint & p) inline
Definition at line 79 of file CLCurve.h.
References mStart.
Referenced by CCopasiXMLParser::CurveElement::start().
 {mStart = p;};
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLLineSegment & ls) friend
insert operator
Definition at line 62 of file CLCurve.cpp.
 {
   os << "[" << ls.mStart << "->" << ls.mEnd << "]";
   if (ls.mIsBezier)
     os << "  " << ls.mBase1 << ", " << ls.mBase2;
   return os;
 }
Member Data Documentation
CLPoint CLLineSegment::mBase1 protected
Definition at line 40 of file CLCurve.h.
Referenced by CLLineSegment(), getBase1(), operator<<(), operator==(), scale(), and setBase1().
CLPoint CLLineSegment::mBase2 protected
Definition at line 41 of file CLCurve.h.
Referenced by CLLineSegment(), getBase2(), operator<<(), operator==(), scale(), and setBase2().
CLPoint CLLineSegment::mEnd protected
Definition at line 38 of file CLCurve.h.
Referenced by getEnd(), operator<<(), operator==(), scale(), and setEnd().
bool CLLineSegment::mIsBezier protected
Definition at line 43 of file CLCurve.h.
Referenced by CLLineSegment(), isBezier(), operator<<(), operator==(), scale(), and setIsBezier().
CLPoint CLLineSegment::mStart protected
Definition at line 37 of file CLCurve.h.
Referenced by getStart(), operator<(), operator<<(), operator==(), scale(), and setStart().
The documentation for this class was generated from the following files:
CLCurve.h
CLCurve.cpp