COPASI API: CQSteadyStateResult Class Reference
CQSteadyStateResult Class Reference
#include <CQSteadyStateResult.h>
Public Member Functions
CQSteadyStateResult (QWidget *parent=0, const char *name=0)
virtual bool leave ()
void loadResult ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQSteadyStateResult ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotSave (void)
void slotUpdateModel ()
Private Member Functions
void init ()
Private Attributes
const CSteadyStateProblem * mpProblem
CSteadyStateTask * mpTask
bool mUpToDate
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 16 of file CQSteadyStateResult.h.
Constructor & Destructor Documentation
CQSteadyStateResult::CQSteadyStateResult (QWidget * parent = 0, const char * name = 0)
Definition at line 31 of file CQSteadyStateResult.cpp.
References init().
     : CopasiWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQSteadyStateResult::~CQSteadyStateResult ()
Definition at line 42 of file CQSteadyStateResult.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
bool CQSteadyStateResult::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 69 of file CQSteadyStateResult.cpp.
 {
   return true;
 }
void CQSteadyStateResult::init () private
Definition at line 47 of file CQSteadyStateResult.cpp.
References mpProblem, mpTask, and mUpToDate.
Referenced by CQSteadyStateResult().
 {
   mpProblem = NULL;
   mpTask = NULL;
   mUpToDate = false;
 }
bool CQSteadyStateResult::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 64 of file CQSteadyStateResult.cpp.
 {
   return true;
 }
void CQSteadyStateResult::loadResult ()
Definition at line 74 of file CQSteadyStateResult.cpp.
References CCopasiParameterGroup::clear(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getProblem(), CSteadyStateTask::getState(), mpProblem, mpTask, and mUpToDate.
Referenced by SteadyStateWidget::taskFinishedEvent().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   mpTask =
     dynamic_cast<CSteadyStateTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Steady-State"]);
   if (!mpTask) return;
   mpProblem = dynamic_cast<const CSteadyStateProblem *>(mpTask->getProblem());
   if (!mpProblem) return;
   if (!mpTask) return;
   if (!mpTask->getState())
     {
       mpCentralWidget->clear();
       mUpToDate = false;
       return;
     }
   mpCentralWidget->loadAll(mpTask);
   mUpToDate = true;
   return;
 }
void CQSteadyStateResult::slotSave (void) private slot
Definition at line 102 of file CQSteadyStateResult.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CopasiFileDialog::getSaveFileName(), mpTask, and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail()) return;
   if (mpTask != NULL)
     file << *mpTask;
   return;
 }
void CQSteadyStateResult::slotUpdateModel () private slot
Definition at line 131 of file CQSteadyStateResult.cpp.
References ListViews::CHANGE, CModel::compileIfNecessary(), CModel::getKey(), CCopasiProblem::getModel(), CSteadyStateTask::getState(), CCopasiTask::isUpdateModel(), mpProblem, mpTask, mUpToDate, CopasiWidget::protectedNotify(), CSteadyStateTask::restore(), CCopasiTask::setUpdateModel(), and ListViews::STATE.
 {
   if (mUpToDate &&
       mpTask != NULL &&
       mpProblem != NULL &&
       mpTask->getState() != NULL)
     {
       CModel *pModel = mpProblem->getModel();
       if (pModel != NULL)
         {
           pModel->compileIfNecessary(NULL);
           if (mpTask->isUpdateModel())
             {
               mpTask->restore();
             }
           else
             {
               mpTask->setUpdateModel(true);
               mpTask->restore();
               mpTask->setUpdateModel(false);
             }
           protectedNotify(ListViews::STATE, ListViews::CHANGE, pModel->getKey());
         }
     }
 }
bool CQSteadyStateResult::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 54 of file CQSteadyStateResult.cpp.
References mUpToDate, and ListViews::STATE.
 {
   if (objectType != ListViews::STATE)
     mUpToDate = false;
   return true;
 }
Member Data Documentation
const CSteadyStateProblem* CQSteadyStateResult::mpProblem private
Definition at line 35 of file CQSteadyStateResult.h.
Referenced by init(), loadResult(), and slotUpdateModel().
CSteadyStateTask* CQSteadyStateResult::mpTask private
Definition at line 36 of file CQSteadyStateResult.h.
Referenced by init(), loadResult(), slotSave(), and slotUpdateModel().
bool CQSteadyStateResult::mUpToDate private
Definition at line 37 of file CQSteadyStateResult.h.
Referenced by init(), loadResult(), slotUpdateModel(), and update().
The documentation for this class was generated from the following files:
CQSteadyStateResult.h
CQSteadyStateResult.cpp