COPASI API: CCopasiXMLParser::ModifierElement Class Reference
CCopasiXMLParser::ModifierElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ModifierElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ModifierElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Modifier = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 874 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ModifierElement::Element private
Enum of invoked parsers
Enumerator
Modifier
Definition at line 882 of file CCopasiXMLParser.h.
     {
       Modifier = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ModifierElement::ModifierElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 4449 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ModifierElement::~ModifierElement () virtual
Destructor
Definition at line 4454 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::ModifierElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 4499 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Modifier:
         if (strcmp(pszName, "Modifier"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Modifier", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ModifierElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 4459 of file CCopasiXMLParser.cpp.
References CReaction::addModifier(), CCopasiMessage::EXCEPTION, fatalError, CKeyFactory::get(), CModelEntity::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pReaction, and UNKNOWN_ELEMENT.
 {
   const char * Metabolite;
   CMetab * pMetabolite;
   const char * Stoichiometry;
   mCurrentElement++; /* We should always be on the next element */
   switch (mCurrentElement)
     {
       case Modifier:
         if (strcmp(pszName, "Modifier"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Modifier", mParser.getCurrentLineNumber());
         Metabolite = mParser.getAttributeValue("metabolite", papszAttrs);
         Stoichiometry = mParser.getAttributeValue("stoichiometry", papszAttrs);
         pMetabolite = dynamic_cast< CMetab * >(mCommon.KeyMap.get(Metabolite));
         if (!pMetabolite) fatalError();
         mCommon.pReaction->addModifier(pMetabolite->getKey(),
                                        CCopasiXMLInterface::DBL(Stoichiometry));
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp