COPASI API: CNormalChoiceLogical Class Reference
CNormalChoiceLogical Class Reference
#include <CNormalChoiceLogical.h>
Public Member Functions
CNormalChoiceLogical ()
CNormalChoiceLogical (const CNormalChoiceLogical &src)
virtual CNormalBase * copy () const
const CNormalLogical & getCondition () const
CNormalLogical & getCondition ()
const CNormalLogical & getFalseExpression () const
CNormalLogical & getFalseExpression ()
const CNormalLogical & getTrueExpression () const
CNormalLogical & getTrueExpression ()
void negate ()
bool operator< (const CNormalChoiceLogical &rhs) const
CNormalChoiceLogical & operator= (const CNormalChoiceLogical &src)
bool operator== (const CNormalChoiceLogical &rhs) const
bool setCondition (const CNormalLogical &cond)
bool setFalseExpression (const CNormalLogical &branch)
bool setTrueExpression (const CNormalLogical &branch)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalChoiceLogical ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Static Public Member Functions
static bool checkConditionTree (const CNormalBase &branch)
Protected Attributes
CNormalLogical * mpCondition
CNormalLogical * mpFalse
CNormalLogical * mpTrue
Detailed Description
Definition at line 23 of file CNormalChoiceLogical.h.
Constructor & Destructor Documentation
CNormalChoiceLogical::CNormalChoiceLogical ()
Definition at line 27 of file CNormalChoiceLogical.cpp.
Referenced by copy().
                                           : CNormalBase(), mpCondition(NULL), mpTrue(NULL), mpFalse(NULL)
 {}
CNormalChoiceLogical::CNormalChoiceLogical (const CNormalChoiceLogical & src)
Definition at line 30 of file CNormalChoiceLogical.cpp.
                                                                          :
     CNormalBase(src),
     mpCondition(NULL),
     mpTrue(NULL),
     mpFalse(NULL)
 {*this = src;}
CNormalChoiceLogical::~CNormalChoiceLogical () virtual
Definition at line 37 of file CNormalChoiceLogical.cpp.
References mpCondition, mpFalse, mpTrue, and pdelete.
 {
   pdelete(mpCondition);
   pdelete(mpTrue);
   pdelete(mpFalse);
 }
Member Function Documentation
bool CNormalChoiceLogical::checkConditionTree (const CNormalBase & branch) static
Definition at line 129 of file CNormalChoiceLogical.cpp.
References CNormalItem::CONSTANT, getCondition(), getFalseExpression(), CNormalItem::getName(), getTrueExpression(), and CNormalItem::getType().
Referenced by setCondition(), setFalseExpression(), and setTrueExpression().
 {
   bool result = true;
   const CNormalChoiceLogical* pChoice = dynamic_cast<const CNormalChoiceLogical*>(&branch);
   if (pChoice != NULL)
     {
       // check the condition and the two branches
       result = checkConditionTree(pChoice->getCondition());
       if (result == true) result = checkConditionTree(pChoice->getTrueExpression());
       if (result == true) result = checkConditionTree(pChoice->getFalseExpression());
     }
   else
     {
       const CNormalLogical* pLogical = dynamic_cast<const CNormalLogical*>(&branch);
       if (pLogical == NULL)
         {
           const CNormalItem* pItem = dynamic_cast<const CNormalItem*>(&branch);
           if (pItem == NULL)
             {
               result = false;
             }
           else
             {
               result = pItem->getType() == CNormalItem::CONSTANT;
               if (result == true)
                 {
                   std::string name = pItem->getName();
                   if (name != "true" && name != "TRUE" && name != "false" && name != "FALSE")
                     {
                       result = false;
                     }
                 }
             }
         }
     }
   return result;
 }
CNormalBase * CNormalChoiceLogical::copy () const virtual
Implements CNormalBase.
Definition at line 124 of file CNormalChoiceLogical.cpp.
References CNormalChoiceLogical().
   {
     return new CNormalChoiceLogical(*this);
   }
const CNormalLogical & CNormalChoiceLogical::getCondition () const
Definition at line 94 of file CNormalChoiceLogical.cpp.
References mpCondition.
Referenced by checkConditionTree(), and convertToCEvaluationNode().
   {
     return *mpCondition;
   }
CNormalLogical & CNormalChoiceLogical::getCondition ()
Definition at line 99 of file CNormalChoiceLogical.cpp.
References mpCondition.
 {
   return *mpCondition;
 }
const CNormalLogical & CNormalChoiceLogical::getFalseExpression () const
Definition at line 114 of file CNormalChoiceLogical.cpp.
References mpFalse.
Referenced by checkConditionTree(), and convertToCEvaluationNode().
   {
     return *mpFalse;
   }
CNormalLogical & CNormalChoiceLogical::getFalseExpression ()
Definition at line 119 of file CNormalChoiceLogical.cpp.
References mpFalse.
 {
   return *mpFalse;
 }
const CNormalLogical & CNormalChoiceLogical::getTrueExpression () const
Definition at line 104 of file CNormalChoiceLogical.cpp.
References mpTrue.
Referenced by checkConditionTree(), and convertToCEvaluationNode().
   {
     return *mpTrue;
   }
CNormalLogical & CNormalChoiceLogical::getTrueExpression ()
Definition at line 109 of file CNormalChoiceLogical.cpp.
References mpTrue.
 {
   return *mpTrue;
 }
void CNormalChoiceLogical::negate ()
Definition at line 189 of file CNormalChoiceLogical.cpp.
References mpFalse, and mpTrue.
 {
   CNormalLogical* pTmp = this->mpTrue;
   this->mpTrue = this->mpFalse;
   this->mpFalse = pTmp;
 }
bool CNormalChoiceLogical::operator< (const CNormalChoiceLogical & rhs) const
Definition at line 201 of file CNormalChoiceLogical.cpp.
References mpCondition, mpFalse, and mpTrue.
   {
     bool result = true;
     if ((*rhs.mpCondition) < (*this->mpCondition))
       {
         result = false;
       }
     else if ((*this->mpCondition) == (*rhs.mpCondition))
       {
         if ((*rhs.mpTrue) < (*this->mpTrue))
           {
             result = false;
           }
         else if ((*rhs.mpTrue) == (*this->mpTrue))
           {
             if (!((*this->mpFalse) < (*rhs.mpFalse)))
               {
                 result = false;
               }
           }
       }
     return result;
   }
CNormalChoiceLogical & CNormalChoiceLogical::operator= (const CNormalChoiceLogical & src)
Definition at line 44 of file CNormalChoiceLogical.cpp.
References mpCondition, mpFalse, mpTrue, and pdelete.
 {
   pdelete(mpCondition);
   pdelete(mpTrue);
   pdelete(mpFalse);
   if (src.mpCondition != NULL)
     mpCondition = new CNormalLogical(*src.mpCondition);
   if (src.mpTrue != NULL)
     mpTrue = new CNormalLogical(*src.mpTrue);
   if (src.mpFalse != NULL)
     mpFalse = new CNormalLogical(*src.mpFalse);
   return *this;
 }
bool CNormalChoiceLogical::operator== (const CNormalChoiceLogical & rhs) const
Definition at line 196 of file CNormalChoiceLogical.cpp.
References mpCondition, mpFalse, and mpTrue.
   {
     return ((*this->mpCondition) == (*rhs.mpCondition) && (*this->mpTrue == *rhs.mpTrue) && (*this->mpFalse == *rhs.mpFalse));
   }
bool CNormalChoiceLogical::setCondition (const CNormalLogical & cond)
Definition at line 60 of file CNormalChoiceLogical.cpp.
References checkConditionTree(), mpCondition, and pdelete.
Referenced by createLogicalChoice().
 {
   bool result = true;
   pdelete(mpCondition);
   // check the cond if it is OK
   result = checkConditionTree(cond);
   if (result == true)
     mpCondition = new CNormalLogical(cond);
   return result;
 }
bool CNormalChoiceLogical::setFalseExpression (const CNormalLogical & branch)
Definition at line 83 of file CNormalChoiceLogical.cpp.
References checkConditionTree(), mpFalse, and pdelete.
Referenced by createLogicalChoice().
 {
   bool result = true;
   pdelete(mpFalse);
   // check the branch if it is OK
   result = checkConditionTree(branch);
   mpFalse = new CNormalLogical(branch);
   return result;
 }
bool CNormalChoiceLogical::setTrueExpression (const CNormalLogical & branch)
Definition at line 72 of file CNormalChoiceLogical.cpp.
References checkConditionTree(), mpTrue, and pdelete.
Referenced by createLogicalChoice().
 {
   bool result = true;
   pdelete(mpTrue);
   // check the branch if it is OK
   result = checkConditionTree(branch);
   mpTrue = new CNormalLogical(branch);
   return result;
 }
bool CNormalChoiceLogical::simplify () virtual
Implements CNormalBase.
Definition at line 180 of file CNormalChoiceLogical.cpp.
References mpCondition, mpFalse, mpTrue, and CNormalLogical::simplify().
 {
   bool result = true;
   if (this->mpCondition != NULL) result &= this->mpCondition->simplify();
   if (this->mpTrue != NULL) result &= this->mpTrue->simplify();
   if (this->mpFalse != NULL) result &= this->mpFalse->simplify();
   return result;
 }
std::string CNormalChoiceLogical::toString () const virtual
Implements CNormalBase.
Definition at line 167 of file CNormalChoiceLogical.cpp.
References mpCondition, mpFalse, mpTrue, and CNormalLogical::toString().
Referenced by operator<<().
   {
     std::ostringstream os;
     os << "if(" << this->mpCondition->toString() << ") then (" << this->mpTrue->toString() << ") else (" << this->mpFalse->toString() << ")";
     return os.str();
   }
Member Data Documentation
CNormalLogical* CNormalChoiceLogical::mpCondition protected
Definition at line 26 of file CNormalChoiceLogical.h.
Referenced by getCondition(), operator<(), operator=(), operator==(), setCondition(), simplify(), toString(), and ~CNormalChoiceLogical().
CNormalLogical* CNormalChoiceLogical::mpFalse protected
Definition at line 28 of file CNormalChoiceLogical.h.
Referenced by getFalseExpression(), negate(), operator<(), operator=(), operator==(), setFalseExpression(), simplify(), toString(), and ~CNormalChoiceLogical().
CNormalLogical* CNormalChoiceLogical::mpTrue protected
Definition at line 27 of file CNormalChoiceLogical.h.
Referenced by getTrueExpression(), negate(), operator<(), operator=(), operator==(), setTrueExpression(), simplify(), toString(), and ~CNormalChoiceLogical().
The documentation for this class was generated from the following files:
CNormalChoiceLogical.h
CNormalChoiceLogical.cpp