COPASI API: CRDFParser Class Reference
CRDFParser Class Reference
#include <CRDFParser.h>
Public Member Functions
CRDFParser ()
CRDFGraph * parse (std::istream &stream)
~CRDFParser ()
Static Public Member Functions
static void ErrorHandler (void *, raptor_locator *pLocator, const char *message)
static void FatalErrorHandler (void *, raptor_locator *pLocator, const char *message)
static unsigned char * GenerateIdHandler (void *pGraph, raptor_genid_type type, unsigned char *userNodeId)
static CRDFGraph * graphFromXml (const std::string &xml)
static void NameSpaceHandler (void *pGraph, raptor_namespace *pNameSpace)
static void TripleHandler (void *pGraph, const raptor_statement *pTriple)
static void WarningHandler (void *, raptor_locator *pLocator, const char *message)
Private Attributes
raptor_parser * mpParser
Additional Inherited Members
Private Member Functions inherited from CRaptorInit
CRaptorInit ()
~CRaptorInit ()
Static Private Member Functions inherited from CRaptorInit
static bool isLocalURI (raptor_uri *pURI)
Detailed Description
Definition at line 29 of file CRDFParser.h.
Constructor & Destructor Documentation
CRDFParser::CRDFParser ()
Default Constructor
Definition at line 40 of file CRDFParser.cpp.
References ErrorHandler(), FatalErrorHandler(), mpParser, and WarningHandler().
                        :
   CRaptorInit(),
   mpParser(NULL)
 {
   mpParser = raptor_new_parser("rdfxml");
   raptor_set_fatal_error_handler(mpParser, NULL, &CRDFParser::FatalErrorHandler);
   raptor_set_error_handler(mpParser, NULL, &CRDFParser::ErrorHandler);
   raptor_set_warning_handler(mpParser, NULL, &CRDFParser::WarningHandler);
 }
CRDFParser::~CRDFParser ()
Destructor
Definition at line 51 of file CRDFParser.cpp.
References mpParser.
 {
   if (mpParser != NULL)
     raptor_free_parser(mpParser);
 }
Member Function Documentation
void CRDFParser::ErrorHandler (void * , raptor_locator * pLocator, const char * message) static
A static handler to interface with the C parser library. This is called whenever the parser encounters an error;
Parameters
void * userdata (ignored)
raptor_locator * pLocator
const char * message
Definition at line 241 of file CRDFParser.cpp.
References CCopasiMessage::ERROR, and MCAnnotation.
Referenced by CRDFParser().
 {
   CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 1,
                  raptor_locator_line(pLocator),
                  raptor_locator_column(pLocator),
                  message);
 }
void CRDFParser::FatalErrorHandler (void * , raptor_locator * pLocator, const char * message) static
A static handler to interface with the C parser library. This is called whenever the parser encounters a fatal error;
Parameters
void * userdata (ignored)
raptor_locator * pLocator
const char * message
Definition at line 232 of file CRDFParser.cpp.
References CCopasiMessage::ERROR, and MCAnnotation.
Referenced by CRDFParser().
 {
   CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 1,
                  raptor_locator_line(pLocator),
                  raptor_locator_column(pLocator),
                  message);
 }
unsigned char * CRDFParser::GenerateIdHandler (void * pGraph, raptor_genid_type type, unsigned char * userNodeId) static
A static handler to interface with the C parser library. This is called whenever a node id needs to be generated.
Parameters
void * pGraph
raptor_genid_type type
unsigned char * userNodeId
Returns
unsigned char * generatedId
Definition at line 217 of file CRDFParser.cpp.
Referenced by parse().
 {
   std::string NodeId;
   if (existingNodeId != NULL)
     NodeId = static_cast<CRDFGraph *>(pGraph)->generatedNodeId((char *) existingNodeId).c_str();
   else
     NodeId = static_cast<CRDFGraph *>(pGraph)->generatedNodeId().c_str();
   return (unsigned char *) strdup(NodeId.c_str());
 }
CRDFGraph * CRDFParser::graphFromXml (const std::string & xml) static
Convert an RDF/XML syntax string to an RDF Graph. If the conversion fails a NULL pointer is returned. Otherwise a pointer to the resulting graph is returned. It is the responsibility of the caller to destroy the created graph.
Parameters
const std::string & xml
Returns
CRDFGraph * graphFromXml
Definition at line 30 of file CRDFParser.cpp.
References parse().
Referenced by CQRDFTreeView::enterProtected(), CMIRIAMInfo::load(), and CRDFGraphConverter::SBML2Copasi().
 {
   CRDFParser Parser;
   std::istringstream XML;
   XML.str(xml);
   return Parser.parse(XML);
 }
void CRDFParser::NameSpaceHandler (void * pGraph, raptor_namespace * pNameSpace) static
A static handler to interface with the C parser library. This is called whenever a namespace is declared.
Parameters
void * pGraph
raptor_namespace * pNameSpace
Definition at line 199 of file CRDFParser.cpp.
Referenced by parse().
 {
   const unsigned char * pURI =
     raptor_uri_as_string(raptor_namespace_get_uri(pNameSpace));
   std::string URI("");
   if (pURI) URI = (const char *) pURI;
   const unsigned char * pPrefix =
     raptor_namespace_get_prefix(pNameSpace);
   std::string Prefix("");
   if (pPrefix) Prefix = (const char *) pPrefix;
   static_cast<CRDFGraph *>(pGraph)->addNameSpace(Prefix, URI);
 }
CRDFGraph * CRDFParser::parse (std::istream & stream)
Parse the stream. If the parsing fails a NULL pointer is returned. Otherwise a pointer to the resulting graph is returned. It is the responsibility of the caller to destroy the created graph. &param std::istream & stream
Returns
CRDFGraph * pGraph
Definition at line 57 of file CRDFParser.cpp.
References BUFFER_SIZE, C_INT32, fatalError, GenerateIdHandler(), CRDFGraph::guessGraphRoot(), mpParser, NameSpaceHandler(), pdelete, pRaptorFreeUri, and TripleHandler().
Referenced by graphFromXml().
 {
   bool success = true;
   bool done = false;
   stream.imbue(std::locale::classic());
   stream.precision(16);
   // Create the new graph
   CRDFGraph * pGraph = new CRDFGraph;
   unsigned C_INT32 BUFFER_SIZE = 0xfffe;
   char * pBuffer = new char[BUFFER_SIZE + 1];
   stream.get(pBuffer, BUFFER_SIZE, 0);
   if (stream.gcount() != 0)
     {
       raptor_uri * pURI = raptor_new_uri((unsigned char *) "#");
       if (raptor_start_parse(mpParser, pURI))
         fatalError();
       raptor_set_statement_handler(mpParser, pGraph, &CRDFParser::TripleHandler);
       raptor_set_namespace_handler(mpParser, pGraph, &CRDFParser::NameSpaceHandler);
       raptor_set_generate_id_handler(mpParser, pGraph, &CRDFParser::GenerateIdHandler);
       while (!done)
         {
           if (stream.eof()) done = true;
           if (stream.fail() && !done)
             fatalError();
           if (raptor_parse_chunk(mpParser,
                                  (unsigned char *) pBuffer,
                                  strlen(pBuffer),
                                  done ? 1 : 0))
             {
               done = true;
               success = false;
             }
           stream.get(pBuffer, BUFFER_SIZE, 0);
         }
       pRaptorFreeUri(pURI);
     }
   delete [] pBuffer;
   if (!success)
     {
       pdelete(pGraph);
       return NULL;
     }
   if (pGraph)
     pGraph->guessGraphRoot();
   return pGraph;
 }
void CRDFParser::TripleHandler (void * pGraph, const raptor_statement * pTriple) static
A static handler to interface with the C parser library. This is called whenever an RDF triple is created. Its only purpose is to add the triple to the graph which must provide addTriplet(CRDFSubject, std::string, CRDFObject);
Parameters
void * pGraph
const raptor_statement * pTriple
Definition at line 121 of file CRDFParser.cpp.
References CRDFSubject::BLANK_NODE, CRDFObject::BLANK_NODE, fatalError, CRaptorInit::isLocalURI(), CRDFObject::LITERAL, CRDFLiteral::PLAIN, CRDFSubject::RESOURCE, CRDFObject::RESOURCE, CRDFSubject::setBlankNodeId(), CRDFObject::setBlankNodeId(), CRDFLiteral::setDataType(), CRDFLiteral::setLanguage(), CRDFLiteral::setLexicalData(), CRDFObject::setLiteral(), CRDFSubject::setResource(), CRDFObject::setResource(), CRDFLiteral::setType(), CRDFSubject::setType(), CRDFObject::setType(), and CRDFLiteral::TYPED.
Referenced by parse().
 {
   // We need to create a CRDFSubject, Predicate, and CRDFObject
   CRDFSubject Subject;
   std::string Predicate;
   CRDFObject Object;
   CRDFLiteral Literal;
   switch (pTriple->subject_type)
     {
       case RAPTOR_IDENTIFIER_TYPE_RESOURCE:
         Subject.setType(CRDFSubject::RESOURCE);
         Subject.setResource((char *) raptor_uri_as_string((raptor_uri *) pTriple->subject),
                             CRaptorInit::isLocalURI((raptor_uri *) pTriple->subject));
         break;
       case RAPTOR_IDENTIFIER_TYPE_ANONYMOUS:
         Subject.setType(CRDFSubject::BLANK_NODE);
         Subject.setBlankNodeId((char *) pTriple->subject);
         break;
       default:
         fatalError();
     }
   switch (pTriple->predicate_type)
     {
       case RAPTOR_IDENTIFIER_TYPE_RESOURCE:
         Predicate = (char *) raptor_uri_as_string((raptor_uri *) pTriple->predicate);
         break;
       default:
         fatalError();
     }
   switch (pTriple->object_type)
     {
       case RAPTOR_IDENTIFIER_TYPE_ORDINAL:
       case RAPTOR_IDENTIFIER_TYPE_RESOURCE:
         Object.setType(CRDFObject::RESOURCE);
         Object.setResource((char *) raptor_uri_as_string((raptor_uri *) pTriple->object),
                            CRaptorInit::isLocalURI((raptor_uri *) pTriple->object));
         break;
       case RAPTOR_IDENTIFIER_TYPE_ANONYMOUS:
         Object.setType(CRDFObject::BLANK_NODE);
         Object.setBlankNodeId((char *) pTriple->object);
         break;
       case RAPTOR_IDENTIFIER_TYPE_LITERAL:
         Object.setType(CRDFObject::LITERAL);
         if (pTriple->object_literal_datatype != NULL)
           {
             Literal.setType(CRDFLiteral::TYPED);
             Literal.setDataType((const char *) raptor_uri_as_string(pTriple->object_literal_datatype));
           }
         else
           {
             Literal.setType(CRDFLiteral::PLAIN);
             if (pTriple->object_literal_language != NULL)
               Literal.setLanguage((const char *) pTriple->object_literal_language);
           }
         Literal.setLexicalData((char *) pTriple->object);
         Object.setLiteral(Literal);
         break;
       default:
         fatalError();
     }
   // Add the triplet to the graph
   static_cast<CRDFGraph *>(pGraph)->addTriplet(Subject, Predicate, Object);
 }
void CRDFParser::WarningHandler (void * , raptor_locator * pLocator, const char * message) static
A static handler to interface with the C parser library. This is called whenever the parser encounters a warning;
Parameters
void * userdata (ignored)
raptor_locator * pLocator
const char * message
Definition at line 250 of file CRDFParser.cpp.
References MCAnnotation, and CCopasiMessage::WARNING.
Referenced by CRDFParser().
 {
   CCopasiMessage(CCopasiMessage::WARNING, MCAnnotation + 1,
                  raptor_locator_line(pLocator),
                  raptor_locator_column(pLocator),
                  message);
 }
Member Data Documentation
raptor_parser* CRDFParser::mpParser private
Pointer to the underlying C parser from the Raptor library
Definition at line 122 of file CRDFParser.h.
Referenced by CRDFParser(), parse(), and ~CRDFParser().
The documentation for this class was generated from the following files:
CRDFParser.h
CRDFParser.cpp