COPASI API: Worker Class Reference
Worker Class Reference
#include <worker.h>
Public Slots
void finishedLoading (bool success)
bool slotNotify (ListViews::ObjectType objectType, ListViews::Action action, std::string key="")
Public Member Functions
Worker (CopasiUI3Window *window, Arguments *args)
Static Public Member Functions
static int getIndexForTask (CCopasiTask *task)
Private Member Functions
TaskWidget * getWidgetForTask (CCopasiTask *task) const
Static Private Member Functions
static int getIndexForWidget (TaskWidget *widget)
Private Attributes
Arguments * mpArgs
DataModelGUI * mpDataModel
CopasiUI3Window * mpWindow
bool mTaskStarted
Detailed Description
Definition at line 18 of file worker.h.
Constructor & Destructor Documentation
Worker::Worker (CopasiUI3Window * window, Arguments * args)
Definition at line 25 of file worker.cpp.
References finishedLoading(), CopasiUI3Window::getDataModel(), Arguments::getFilename(), mpArgs, mpDataModel, mpWindow, CopasiUI3Window::openInitialDocument(), and slotNotify().
                                                        : mTaskStarted(false)
 {
   mpArgs = args;
   mpWindow = window;
   mpDataModel = mpWindow->getDataModel();
   // open the newly generated model
   mpWindow->openInitialDocument(QString((args->getFilename() + ".view.cps").c_str()));
   // connect the finish slot, so it will switch to the correct tab
   connect(mpDataModel, SIGNAL(finished(bool)), this, SLOT(finishedLoading(bool)));
   connect(mpDataModel, SIGNAL(notifyView(ListViews::ObjectType, ListViews::Action, std::string)),
           this, SLOT(slotNotify(ListViews::ObjectType, ListViews::Action, std::string)));
 }
Member Function Documentation
void Worker::finishedLoading (bool success) slot
Definition at line 169 of file worker.cpp.
References Arguments::getFirstScheduledTask(), getIndexForTask(), CopasiUI3Window::getMainWidget(), Arguments::getTaskToSwitchTo(), getWidgetForTask(), Arguments::isHideWindow(), Arguments::isRunScheduled(), Arguments::isSwitchToTask(), mpArgs, mpWindow, mTaskStarted, TaskWidget::runTask(), and ListViews::switchToOtherWidget().
Referenced by Worker().
 {
   if (!success)
     return;
   if (mpArgs->isSwitchToTask())
     {
       mpWindow ->getMainWidget()->switchToOtherWidget(mpArgs->getTaskToSwitchTo(), "");
     }
   if (mpArgs->isRunScheduled())
     {
       CCopasiTask *task = Arguments::getFirstScheduledTask();
       if (task == NULL)
         return;
       if (!mpArgs->isSwitchToTask())
         mpWindow ->getMainWidget()->switchToOtherWidget(getIndexForTask(task), "");
       TaskWidget *widget = getWidgetForTask(task);
       mTaskStarted = true;
       widget->runTask();
     }
   if (mpArgs->isHideWindow())
     mpWindow->hide();
 }
int Worker::getIndexForTask (CCopasiTask * task) static
Definition at line 121 of file worker.cpp.
References CCopasiTask::crosssection, CCopasiTask::fluxMode, CCopasiTask::getType(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, CCopasiTask::moieties, CCopasiTask::optimization, CCopasiTask::parameterFitting, CCopasiTask::scan, CCopasiTask::sens, CCopasiTask::steadyState, CCopasiTask::timeCourse, CCopasiTask::tssAnalysis, and CCopasiTask::unset.
Referenced by finishedLoading(), and getIndexForWidget().
 {
   if (task == NULL) return -1;
   switch (task->getType())
     {
       case CCopasiTask::steadyState:
         return 21;
       case CCopasiTask::timeCourse:
         return 23;
       case CCopasiTask::scan:
         return 31;
       case CCopasiTask::optimization:
         return 32;
       case CCopasiTask::parameterFitting:
         return 33;
       case CCopasiTask::mca:
         return 24;
       case CCopasiTask::lna:
         return 35;
       case CCopasiTask::lyap:
       case CCopasiTask::fluxMode:
       case CCopasiTask::tssAnalysis:
       case CCopasiTask::sens:
       case CCopasiTask::moieties:
       case CCopasiTask::crosssection:
       case CCopasiTask::unset:
       default:
         // have no id
         return -1;
     }
 }
int Worker::getIndexForWidget (TaskWidget * widget) static private
Definition at line 161 of file worker.cpp.
References getIndexForTask(), and TaskWidget::getTask().
 {
   if (widget == NULL) return -1;
   CCopasiTask *task = widget->getTask();
   return getIndexForTask(task);
 }
TaskWidget * Worker::getWidgetForTask (CCopasiTask * task) const private
Definition at line 79 of file worker.cpp.
References CCopasiTask::crosssection, CCopasiTask::fluxMode, ListViews::getFittingWidget(), ListViews::getLNAWidget(), CopasiUI3Window::getMainWidget(), ListViews::getMCAWidget(), ListViews::getOptimizationWidget(), ListViews::getScanWidget(), ListViews::getSteadyStateWidget(), ListViews::getTrajectoryWidget(), CCopasiTask::getType(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, CCopasiTask::moieties, mpWindow, CCopasiTask::optimization, CCopasiTask::parameterFitting, CCopasiTask::scan, CCopasiTask::sens, CCopasiTask::steadyState, CCopasiTask::timeCourse, CCopasiTask::tssAnalysis, and CCopasiTask::unset.
Referenced by finishedLoading().
 {
   if (task == NULL) return NULL;
   ListViews* views = mpWindow->getMainWidget();
   switch (task->getType())
     {
       case CCopasiTask::steadyState:
         return reinterpret_cast<TaskWidget*>(views->getSteadyStateWidget());
       case CCopasiTask::timeCourse:
         return reinterpret_cast<TaskWidget*>(views->getTrajectoryWidget());
       case CCopasiTask::scan:
         return reinterpret_cast<TaskWidget*>(views->getScanWidget());
       case CCopasiTask::optimization:
         return reinterpret_cast<TaskWidget*>(views->getOptimizationWidget());
       case CCopasiTask::parameterFitting:
         return reinterpret_cast<TaskWidget*>(views->getFittingWidget());
       case CCopasiTask::mca:
         return reinterpret_cast<TaskWidget*>(views->getMCAWidget());
       case CCopasiTask::lna:
         return reinterpret_cast<TaskWidget*>(views->getLNAWidget());
       case CCopasiTask::lyap:
       case CCopasiTask::fluxMode:
       case CCopasiTask::tssAnalysis:
       case CCopasiTask::sens:
       case CCopasiTask::moieties:
       case CCopasiTask::crosssection:
       case CCopasiTask::unset:
       default:
         // have no widget for these
         return NULL;
     }
 }
bool Worker::slotNotify (ListViews::ObjectType objectType, ListViews::Action action, std::string key = "") slot
Definition at line 40 of file worker.cpp.
References ListViews::CHANGE, Arguments::getFileType(), Arguments::getOutputDir(), CopasiUI3Window::getWindows(), Arguments::haveOutputDir(), Arguments::isQuitAfterTaskExecution(), mpArgs, mpWindow, mTaskStarted, CWindowInterface::saveToFile(), and ListViews::STATE.
Referenced by Worker().
 {
   if (objectType == ListViews::STATE && action == ListViews::CHANGE && mTaskStarted)
     {
       mTaskStarted = false;
       if (mpArgs->haveOutputDir())
         {
           const QList< QPointer<QMainWindow> >& windows = mpWindow->getWindows();
           for (int index = 0; index < windows.count(); ++index)
             {
               const QMainWindow* mainWindow = windows[index];
               if (mainWindow == NULL) continue;
               const CWindowInterface* window = dynamic_cast<const CWindowInterface*>(mainWindow);
               if (window == NULL) continue;
               QString fileName = QString("%1/plot%2.%3")
                                  .arg(mpArgs->getOutputDir().c_str())
                                  .arg(index + 1)
                                  .arg(mpArgs->getFileType().c_str());
               window->saveToFile(fileName);
             }
         }
       if (mpArgs->isQuitAfterTaskExecution())
         {
           // quit
           qApp->quit();
         }
     }
   return true;
 }
Member Data Documentation
Arguments* Worker::mpArgs private
Definition at line 44 of file worker.h.
Referenced by finishedLoading(), slotNotify(), and Worker().
DataModelGUI* Worker::mpDataModel private
Definition at line 42 of file worker.h.
Referenced by Worker().
CopasiUI3Window* Worker::mpWindow private
Definition at line 40 of file worker.h.
Referenced by finishedLoading(), getWidgetForTask(), slotNotify(), and Worker().
bool Worker::mTaskStarted private
Definition at line 46 of file worker.h.
Referenced by finishedLoading(), and slotNotify().
The documentation for this class was generated from the following files:
worker.h
worker.cpp