COPASI API: test000066 Class Reference
test000066 Class Reference
#include <test000066.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_import_reaction_with_constant_flux ()
void test_import_reaction_with_constant_flux_function ()
void test_import_reaction_with_constant_flux_function_global_parameter ()
void test_import_reaction_with_constant_flux_global_parameter ()
void test_import_reaction_with_constant_flux_reversible ()
void test_import_reaction_with_constant_flux_reversible_function ()
void test_import_reaction_with_constant_flux_reversible_function_global_parameter ()
void test_import_reaction_with_constant_flux_reversible_global_parameter ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static const char * MODEL_STRING7
static const char * MODEL_STRING8
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_reaction_with_constant_flux)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_global_parameter)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_function)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_function_global_parameter)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible_global_parameter)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible_function)
CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible_function_global_parameter)
CPPUNIT_TEST_SUITE (test000066)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 26 of file test000066.h.
Member Function Documentation
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_global_parameter) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_function) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_function_global_parameter) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible_global_parameter) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible_function) private
test000066::CPPUNIT_TEST (test_import_reaction_with_constant_flux_reversible_function_global_parameter) private
test000066::CPPUNIT_TEST_SUITE (test000066) private
test000066::CPPUNIT_TEST_SUITE_END () private
void test000066::setUp ()
Definition at line 44 of file test000066.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000066::tearDown ()
Definition at line 52 of file test000066.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000066::test_import_reaction_with_constant_flux ()
Definition at line 57 of file test000066.cpp.
References CCopasiParameter::DOUBLE, CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING1, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 0);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == false);
   // check for the local parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   const CCopasiParameter* pParameter = pReaction->getParameters().getParameter(0);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == true);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pParameter->getType() == CCopasiParameter::DOUBLE);
   CPPUNIT_ASSERT(fabs(((*(pParameter->getValue().pDOUBLE)) - 0.015) / 0.015) < 1e-12);
   CPPUNIT_ASSERT(pParameter->getObjectName() == "v");
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (irreversible)");
 }
void test000066::test_import_reaction_with_constant_flux_function ()
Definition at line 93 of file test000066.cpp.
References CCopasiParameter::DOUBLE, CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING2, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 0);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == false);
   // check for the local parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   const CCopasiParameter* pParameter = pReaction->getParameters().getParameter(0);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == true);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pParameter->getType() == CCopasiParameter::DOUBLE);
   CPPUNIT_ASSERT(fabs(((*pParameter->getValue().pDOUBLE) - 0.015) / 0.015) < 1e-12);
   CPPUNIT_ASSERT(pParameter->getObjectName() == "v");
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (irreversible)");
 }
void test000066::test_import_reaction_with_constant_flux_function_global_parameter ()
Definition at line 275 of file test000066.cpp.
References CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING4, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING4));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 0);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == false);
   // check for the global parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == false);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (irreversible)");
 }
void test000066::test_import_reaction_with_constant_flux_global_parameter ()
Definition at line 244 of file test000066.cpp.
References CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING3, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING3));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 0);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == false);
   // check for the global parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == false);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (irreversible)");
 }
void test000066::test_import_reaction_with_constant_flux_reversible ()
Definition at line 421 of file test000066.cpp.
References CCopasiParameter::DOUBLE, CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING5, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING5));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check for the local parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   const CCopasiParameter* pParameter = pReaction->getParameters().getParameter(0);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == true);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pParameter->getType() == CCopasiParameter::DOUBLE);
   CPPUNIT_ASSERT(fabs(((*(pParameter->getValue().pDOUBLE)) - 0.015) / 0.015) < 1e-12);
   CPPUNIT_ASSERT(pParameter->getObjectName() == "v");
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (reversible)");
 }
void test000066::test_import_reaction_with_constant_flux_reversible_function ()
Definition at line 457 of file test000066.cpp.
References CCopasiParameter::DOUBLE, CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING6, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING6));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check for the local parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   const CCopasiParameter* pParameter = pReaction->getParameters().getParameter(0);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == true);
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pParameter->getType() == CCopasiParameter::DOUBLE);
   CPPUNIT_ASSERT(fabs(((*pParameter->getValue().pDOUBLE) - 0.015) / 0.015) < 1e-12);
   CPPUNIT_ASSERT(pParameter->getObjectName() == "v");
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (reversible)");
 }
void test000066::test_import_reaction_with_constant_flux_reversible_function_global_parameter ()
Definition at line 647 of file test000066.cpp.
References CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING8, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING8));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check for the global parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == false);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (reversible)");
 }
void test000066::test_import_reaction_with_constant_flux_reversible_global_parameter ()
Definition at line 616 of file test000066.cpp.
References CModelEntity::FIXED, CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING7, pCOPASIDATAMODEL, CEvaluationTree::PreDefined, and CModel::s.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING7));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check for the global parameter
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   CPPUNIT_ASSERT(pReaction->isLocalParameter(0) == false);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::PreDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Constant flux (reversible)");
 }
Member Data Documentation
const char * test000066::MODEL_STRING1 static protected
Definition at line 40 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux().
const char * test000066::MODEL_STRING2 static protected
Definition at line 41 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_function().
const char * test000066::MODEL_STRING3 static protected
Definition at line 42 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_global_parameter().
const char * test000066::MODEL_STRING4 static protected
Definition at line 43 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_function_global_parameter().
const char * test000066::MODEL_STRING5 static protected
Definition at line 44 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_reversible().
const char * test000066::MODEL_STRING6 static protected
Definition at line 45 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_reversible_function().
const char * test000066::MODEL_STRING7 static protected
Definition at line 46 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_reversible_global_parameter().
const char * test000066::MODEL_STRING8 static protected
Definition at line 47 of file test000066.h.
Referenced by test_import_reaction_with_constant_flux_reversible_function_global_parameter().
CCopasiDataModel * test000066::pCOPASIDATAMODEL = NULL static protected
These tests are supposed to make sure that assignments on a species with the hasOnlySubstanceUnits flag set are exported correctly. It tests rules and event assignments with and without the flag set.
Definition at line 48 of file test000066.h.
Referenced by setUp(), test_import_reaction_with_constant_flux(), test_import_reaction_with_constant_flux_function(), test_import_reaction_with_constant_flux_function_global_parameter(), test_import_reaction_with_constant_flux_global_parameter(), test_import_reaction_with_constant_flux_reversible(), test_import_reaction_with_constant_flux_reversible_function(), test_import_reaction_with_constant_flux_reversible_function_global_parameter(), and test_import_reaction_with_constant_flux_reversible_global_parameter().
The documentation for this class was generated from the following files:
test000066.h
test000066.cpp