COPASI API: test000023 Class Reference
test000023 Class Reference
#include <test000023.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_hasOnlySubstanceUnits ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_hasOnlySubstanceUnits)
CPPUNIT_TEST_SUITE (test000023)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000023.h.
Member Function Documentation
test000023::CPPUNIT_TEST (test_hasOnlySubstanceUnits) private
test000023::CPPUNIT_TEST_SUITE (test000023) private
test000023::CPPUNIT_TEST_SUITE_END () private
void test000023::setUp ()
Definition at line 36 of file test000023.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000023::tearDown ()
Definition at line 44 of file test000023.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000023::test_hasOnlySubstanceUnits ()
Definition at line 49 of file test000023.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CChemEq::getCompartmentNumber(), CModelEntity::getExpressionPtr(), CCopasiDataModel::getModel(), CChemEq::getModifiers(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CChemEq::getProducts(), CModelEntity::getStatus(), CChemEq::getSubstrates(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, CModel::mMol, MODEL_STRING, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CCopasiVector< T >::size(), and CEvaluationNode::subType().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 2);
   const CModelValue* pFactor = pModel->getModelValues()[1];
   CPPUNIT_ASSERT(pFactor != NULL);
   CPPUNIT_ASSERT(pFactor->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(fabs((pFactor->getInitialValue() - pModel->getQuantity2NumberFactor()) / pModel->getQuantity2NumberFactor()) < 1e-3);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pModelValue->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   const CEvaluationNodeOperator* pOperatorNode = dynamic_cast<const CEvaluationNodeOperator*>(pNode);
   CPPUNIT_ASSERT(pOperatorNode != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pOperatorNode->getType())) == CEvaluationNodeOperator::DIVIDE);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pOperatorNode->getChild());
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("ParticleNumber"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pA);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pOperatorNode->getChild()->getSibling());
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pFactor);
   // check the reactions
   CPPUNIT_ASSERT(pModel->getReactions().size() == 2);
   const CReaction* pReaction1 = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction1 != NULL);
   CPPUNIT_ASSERT(pReaction1->isReversible() == false);
   // check the kinetic law
   const CFunction* pKineticFunction = pReaction1->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   const CMassAction* pMassAction = dynamic_cast<const CMassAction*>(pKineticFunction);
   //FTB: this no longer is recognized as mass action reaction because of the
   //     special case of a species with hOSU
   CPPUNIT_ASSERT(pMassAction == NULL);
   const CChemEq* pChemEq = &pReaction1->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   const CChemEqElement* pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 0);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   const CReaction* pReaction2 = pModel->getReactions()[1];
   CPPUNIT_ASSERT(pReaction2 != NULL);
   CPPUNIT_ASSERT(pReaction2->isReversible() == false);
   // check the kinetic law
   pKineticFunction = pReaction2->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   CPPUNIT_ASSERT(pKineticFunction->getObjectName() == std::string("Henri-Michaelis-Menten (irreversible)"));
   // check the function parameters one should be the reference to the substrate
   pChemEq = &pReaction2->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 1);
   pElement = pChemEq->getProducts()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pB);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   const std::vector<std::vector<std::string> > parameterMappings = pReaction2->getParameterMappings();
   CPPUNIT_ASSERT(parameterMappings.size() == 3);
   CPPUNIT_ASSERT(parameterMappings[0].size() == 1);
   const std::string parameterKey = parameterMappings[0][0];
   CPPUNIT_ASSERT(parameterKey == pA->getKey());
 }
Member Data Documentation
const char * test000023::MODEL_STRING static protected
Definition at line 31 of file test000023.h.
Referenced by test_hasOnlySubstanceUnits().
CCopasiDataModel * test000023::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000023.h.
Referenced by setUp(), and test_hasOnlySubstanceUnits().
The documentation for this class was generated from the following files:
test000023.h
test000023.cpp