COPASI API: test000090 Class Reference
test000090 Class Reference
#include <test000090.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_delay_in_function ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_delay_in_function)
CPPUNIT_TEST_SUITE (test000090)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000090.h.
Member Function Documentation
test000090::CPPUNIT_TEST (test_delay_in_function) private
test000090::CPPUNIT_TEST_SUITE (test000090) private
test000090::CPPUNIT_TEST_SUITE_END () private
void test000090::setUp ()
Definition at line 31 of file test000090.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000090::tearDown ()
Definition at line 39 of file test000090.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000090::test_delay_in_function ()
Definition at line 44 of file test000090.cpp.
References CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiMessage::getText(), CCopasiMessage::getType(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       pDataModel->importSBMLFromString(MODEL_STRING);
     }
   catch (...)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       CPPUNIT_ASSERT(message.getType() == CCopasiMessage::EXCEPTION);
       std::string s = message.getText();
       CPPUNIT_ASSERT(!s.empty());
       CPPUNIT_ASSERT(s.find(std::string("Call to delay function used in function definition")) != std::string::npos);
       return;
     }
   // we should never get here
   CPPUNIT_ASSERT(false);
 }
Member Data Documentation
const char * test000090::MODEL_STRING static protected
Definition at line 31 of file test000090.h.
Referenced by test_delay_in_function().
CCopasiDataModel * test000090::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000090.h.
Referenced by setUp(), and test_delay_in_function().
The documentation for this class was generated from the following files:
test000090.h
test000090.cpp