COPASI API: COutputHandler Class Reference
COutputHandler Class Reference
#include <COutputHandler.h>
Public Member Functions
virtual void addInterface (COutputInterface *pInterface)
virtual bool compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel *pDataModel)
COutputHandler ()
COutputHandler (const COutputHandler &src)
virtual void finish ()
std::set< COutputInterface * > getInterfaces () const
bool isMaster () const
virtual void output (const Activity &activity)
virtual void removeInterface (COutputInterface *pInterface)
virtual void separate (const Activity &activity)
void setMaster (COutputHandler *pMaster)
virtual ~COutputHandler ()
Public Member Functions inherited from COutputInterface
virtual void close ()
COutputInterface ()
COutputInterface (const COutputInterface &src)
virtual const std::set< const
CCopasiObject * > & getObjects () const
virtual ~COutputInterface ()
Protected Member Functions
bool compileRefresh (const std::vector< CCopasiContainer * > &listOfContainer, const CCopasiDataModel *pDataModel)
void refresh ()
Protected Attributes
std::set< COutputInterface * > mInterfaces
std::vector< Refresh * > mObjectRefreshes
COutputHandler * mpMaster
Protected Attributes inherited from COutputInterface
std::set< const CCopasiObject * > mObjects
Additional Inherited Members
Public Types inherited from COutputInterface
enum Activity { BEFORE = 0x01, DURING = 0x02, AFTER = 0x04 }
Detailed Description
This is the lass which drives all output of COPASI.
Definition at line 112 of file COutputHandler.h.
Constructor & Destructor Documentation
COutputHandler::COutputHandler ()
Default Constructor
Definition at line 26 of file COutputHandler.cpp.
                               :
   COutputInterface(),
   mInterfaces(),
   mpMaster(NULL),
   mObjectRefreshes()
 {}
COutputHandler::COutputHandler (const COutputHandler & src)
Copy constructor
Parameters
const COutputInterface & src
Definition at line 33 of file COutputHandler.cpp.
                                                         :
   COutputInterface(src),
   mInterfaces(src.mInterfaces),
   mpMaster(src.mpMaster),
   mObjectRefreshes(src.mObjectRefreshes)
 {}
COutputHandler::~COutputHandler () virtual
Destructor
Definition at line 40 of file COutputHandler.cpp.
 {};
Member Function Documentation
void COutputHandler::addInterface (COutputInterface * pInterface) virtual
Add an interface
Parameters
COutputInterface * pInterface;
Definition at line 140 of file COutputHandler.cpp.
References mInterfaces, and setMaster().
Referenced by CScanTask::initialize(), CTSSATask::initialize(), CTrajectoryTask::initialize(), CCrossSectionTask::initialize(), and CCopasiTask::initialize().
 {
   mInterfaces.insert(pInterface);
   // Assure that this is the only one master.
   COutputHandler * pHandler = dynamic_cast< COutputHandler * >(pInterface);
   if (pHandler != NULL) pHandler->setMaster(this);
 }
bool COutputHandler::compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel * pDataModel) virtual
compile the object list from name vector
Parameters
std::vector< CCopasiContainer * > listOfContainer
const CCopasiDataModel* pDataModel
Returns
bool success
Reimplemented from COutputInterface.
Reimplemented in COutputHandlerPlot.
Definition at line 47 of file COutputHandler.cpp.
References compileRefresh(), mInterfaces, COutputInterface::mObjects, mpMaster, and setMaster().
Referenced by COutputHandlerPlot::compile(), CCopasiTask::initialize(), and CMoietiesTask::process().
 {
   bool success = true;
   mObjects.clear();
   std::set< COutputInterface *>::iterator it = mInterfaces.begin();
   std::set< COutputInterface *>::iterator end = mInterfaces.end();
   std::set< const CCopasiObject * >::const_iterator itObj;
   std::set< const CCopasiObject * >::const_iterator endObj;
   for (; it != end; ++it)
     {
       success &= (*it)->compile(listOfContainer, pDataModel);
       // Assure that this is the only one master.
       COutputHandler * pHandler = dynamic_cast< COutputHandler * >(*it);
       if (pHandler != NULL) pHandler->setMaster(this);
       // Collect the list of objects
       const std::set< const CCopasiObject * > & Objects = (*it)->getObjects();
       for (itObj = Objects.begin(), endObj = Objects.end(); itObj != endObj; ++itObj)
         mObjects.insert(*itObj);
     }
   if (mpMaster == NULL)
     success &= compileRefresh(listOfContainer, pDataModel);
   return success;
 }
bool COutputHandler::compileRefresh (const std::vector< CCopasiContainer * > & listOfContainer, const CCopasiDataModel * pDataModel) protected
Compile the object refresh list
Parameters
const std::vector< CCopasiContainer * > & listOfContainer
Returns
bool success
Definition at line 174 of file COutputHandler.cpp.
References CCopasiObject::buildUpdateSequence(), CCopasiObject::getCN(), CCopasiDataModel::getModel(), CModel::getUptoDateObjects(), mObjectRefreshes, COutputInterface::mObjects, and CCopasiDataModel::ObjectFromName().
Referenced by compile().
 {
   const CModel * pModel =
     dynamic_cast<const CModel * >(pDataModel->ObjectFromName(listOfContainer, pDataModel->getModel()->getCN()));
   mObjectRefreshes = CCopasiObject::buildUpdateSequence(mObjects, pModel->getUptoDateObjects());
   std::set< const CCopasiObject * >::const_iterator it = mObjects.begin();
   std::set< const CCopasiObject * >::const_iterator end = mObjects.end();
   // Timers are treated differently they are started during compilation.
   for (; it != end; ++it)
     if (dynamic_cast< const CCopasiTimer * >(*it))
       const_cast< CCopasiTimer * >(static_cast< const CCopasiTimer * >(*it))->start();
   return true;
 }
void COutputHandler::finish () virtual
Finish the output
Reimplemented from COutputInterface.
Definition at line 105 of file COutputHandler.cpp.
References mInterfaces, and removeInterface().
Referenced by main(), and validate().
 {
   std::set< COutputInterface *>::iterator it = mInterfaces.begin();
   std::set< COutputInterface *>::iterator end = mInterfaces.end();
   // This hack is necessary as the reverse iterator behaves strangely
   // under Visual C++ 6.0, i.e., removing an object advances the iterator.
   std::vector< COutputInterface * > ToBeRemoved;
   // Closing a stream is separated from finishing the output
   // since subtask may still need to finish their output.
   for (; it != end; ++it)
     {
       (*it)->finish();
     }
   for (it = mInterfaces.begin(); it != end; ++it)
     {
       (*it)->close();
       // CTimesSeries and CReport are only used once.
       if (dynamic_cast< CReport * >(*it) != NULL ||
           dynamic_cast< CTimeSeries * >(*it) != NULL)
         ToBeRemoved.push_back(*it);
     }
   std::vector< COutputInterface * >::iterator itRemove = ToBeRemoved.begin();
   std::vector< COutputInterface * >::iterator endRemove = ToBeRemoved.end();
   for (; itRemove != endRemove; ++itRemove)
     removeInterface(*itRemove);
   return;
 }
std::set< COutputInterface * > COutputHandler::getInterfaces () const
Definition at line 42 of file COutputHandler.cpp.
References mInterfaces.
 {
   return mInterfaces;
 }
bool COutputHandler::isMaster () const
Check whether the handler is a master
Returns
bool isMaster
Definition at line 163 of file COutputHandler.cpp.
References mpMaster.
 {return (mpMaster == NULL);}
void COutputHandler::output (const Activity & activity) virtual
Perform an output event for the current activity
Parameters
const Activity & activity
Reimplemented from COutputInterface.
Definition at line 80 of file COutputHandler.cpp.
References mInterfaces, mpMaster, and refresh().
Referenced by CCopasiTask::output().
 {
   if (mpMaster == NULL)
     refresh();
   std::set< COutputInterface *>::iterator it = mInterfaces.begin();
   std::set< COutputInterface *>::iterator end = mInterfaces.end();
   for (; it != end; ++it)
     (*it)->output(activity);
   return;
 }
void COutputHandler::refresh () protected
Refresh all objects
Definition at line 166 of file COutputHandler.cpp.
References mObjectRefreshes.
Referenced by output().
 {
   std::vector< Refresh * >::iterator it = mObjectRefreshes.begin();
   std::vector< Refresh * >::iterator end = mObjectRefreshes.end();
   for (; it != end; ++it)(**it)();
 }
void COutputHandler::removeInterface (COutputInterface * pInterface) virtual
Remove an interface
Parameters
COutputInterface * pInterface;
Reimplemented in COutputHandlerPlot.
Definition at line 150 of file COutputHandler.cpp.
References mInterfaces, and setMaster().
Referenced by finish(), and COutputHandlerPlot::removeInterface().
 {
   mInterfaces.erase(pInterface);
   // Assure that the removed handler is its own master.
   COutputHandler * pHandler = dynamic_cast< COutputHandler * >(pInterface);
   if (pHandler != NULL) pHandler->setMaster(NULL);
 }
void COutputHandler::separate (const Activity & activity) virtual
Introduce an additional separator into the output
Parameters
const Activity & activity
Reimplemented from COutputInterface.
Definition at line 94 of file COutputHandler.cpp.
References mInterfaces.
Referenced by CCopasiTask::separate().
 {
   std::set< COutputInterface *>::iterator it = mInterfaces.begin();
   std::set< COutputInterface *>::iterator end = mInterfaces.end();
   for (; it != end; ++it)
     (*it)->separate(activity);
   return;
 }
void COutputHandler::setMaster (COutputHandler * pMaster)
Set whether the handler is the master handler
Parameters
COutputHandler * pMaster
Definition at line 160 of file COutputHandler.cpp.
References mpMaster.
Referenced by addInterface(), compile(), and removeInterface().
 {mpMaster = pMaster;}
Member Data Documentation
std::set<COutputInterface *> COutputHandler::mInterfaces protected
A list of all active output interfaces.
Definition at line 202 of file COutputHandler.h.
Referenced by addInterface(), COutputHandlerPlot::compile(), compile(), finish(), getInterfaces(), output(), removeInterface(), and separate().
std::vector< Refresh * > COutputHandler::mObjectRefreshes protected
An ordered list of refresh methods needed by the master
Definition at line 213 of file COutputHandler.h.
Referenced by compileRefresh(), and refresh().
COutputHandler* COutputHandler::mpMaster protected
Points to the master handler. The master handler is responsible for the and object updates and all the output.
Definition at line 208 of file COutputHandler.h.
Referenced by compile(), isMaster(), output(), and setMaster().
The documentation for this class was generated from the following files:
COutputHandler.h
COutputHandler.cpp