COPASI API: test000098 Class Reference
test000098 Class Reference
#include <test000098.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_export_notes ()
void test_import_notes ()
Protected Attributes
CCopasiDataModel * pDataModel
Static Protected Attributes
static const char * CPS_MODEL_1
static const char * SBML_MODEL_1
Private Member Functions
CPPUNIT_TEST (test_import_notes)
CPPUNIT_TEST (test_export_notes)
CPPUNIT_TEST_SUITE (test000098)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 28 of file test000098.h.
Member Function Documentation
test000098::CPPUNIT_TEST (test_import_notes) private
test000098::CPPUNIT_TEST (test_export_notes) private
test000098::CPPUNIT_TEST_SUITE (test000098) private
test000098::CPPUNIT_TEST_SUITE_END () private
void test000098::setUp ()
Definition at line 33 of file test000098.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pDataModel.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   pDataModel = CCopasiRootContainer::addDatamodel();
 }
void test000098::tearDown ()
Definition at line 40 of file test000098.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000098::test_export_notes ()
Definition at line 96 of file test000098.cpp.
References CPS_MODEL_1, CCopasiDataModel::exportSBMLToString(), load_cps_model_from_stream(), and pDataModel.
 {
   CPPUNIT_ASSERT(pDataModel != NULL);
   std::istringstream iss(test000098::CPS_MODEL_1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   std::string s;
   try
     {
       s = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(!s.empty());
   SBMLReader reader;
   SBMLDocument* pSBMLDocument = NULL;
   try
     {
       pSBMLDocument = reader.readSBMLFromString(s);
     }
   catch (...)
     {
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(pSBMLDocument != NULL);
   Model* pModel = pSBMLDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->isSetNotes() == true);
   std::string notes = pModel->getNotesString();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on model") != std::string::npos);
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 1);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   // compartment
   SBase* pObject = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isSetNotes() == true);
   notes = pObject->getNotesString();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on compartment") != std::string::npos);
   // species
   pObject = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isSetNotes() == true);
   notes = pObject->getNotesString();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on species") != std::string::npos);
   // parameter
   pObject = pModel->getParameter(0);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isSetNotes() == true);
   notes = pObject->getNotesString();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on parameter") != std::string::npos);
   // reaction
   pObject = pModel->getReaction(0);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isSetNotes() == true);
   notes = pObject->getNotesString();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on reaction") != std::string::npos);
   // event
   pObject = pModel->getEvent(0);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isSetNotes() == true);
   notes = pObject->getNotesString();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on event") != std::string::npos);
 }
void test000098::test_import_notes ()
Definition at line 47 of file test000098.cpp.
References CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), pDataModel, and SBML_MODEL_1.
 {
   CPPUNIT_ASSERT(pDataModel != NULL);
   // import the file and check if we find all the notes
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(SBML_MODEL_1));
   // check if all the elements have notes
   const CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   std::string notes = pModel->getNotes();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on model") != std::string::npos);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   // compartment
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   notes = pCompartment->getNotes();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on compartment") != std::string::npos);
   // species
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   notes = pMetab->getNotes();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on species") != std::string::npos);
   // reaction
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   notes = pReaction->getNotes();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on reaction") != std::string::npos);
   // parameter
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   notes = pModelValue->getNotes();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on parameter") != std::string::npos);
   // event
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   notes = pEvent->getNotes();
   CPPUNIT_ASSERT(!notes.empty());
   CPPUNIT_ASSERT(notes.find("Simple note on event") != std::string::npos);
 }
Member Data Documentation
const char * test000098::CPS_MODEL_1 static protected
Definition at line 39 of file test000098.h.
Referenced by test_export_notes().
CCopasiDataModel* test000098::pDataModel protected
Definition at line 41 of file test000098.h.
Referenced by setUp(), test_export_notes(), and test_import_notes().
const char * test000098::SBML_MODEL_1 static protected
Definition at line 37 of file test000098.h.
Referenced by test_import_notes().
The documentation for this class was generated from the following files:
test000098.h
test000098.cpp