COPASI API: CQMoietiesTaskResult Class Reference
CQMoietiesTaskResult Class Reference
#include <CQMoietiesTaskResult.h>
Public Member Functions
void clear ()
CQMoietiesTaskResult (QWidget *parent=0, const char *name=0)
virtual bool leave ()
void load ()
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQMoietiesTaskResult ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Protected Attributes
CMoietiesTask * mpMoietiesTask
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Private Slots
void slotCreateGlobalQuantity (const QModelIndex &index)
void slotSave (void)
Private Member Functions
void init ()
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 21 of file CQMoietiesTaskResult.h.
Constructor & Destructor Documentation
CQMoietiesTaskResult::CQMoietiesTaskResult (QWidget * parent = 0, const char * name = 0)
Definition at line 39 of file CQMoietiesTaskResult.cpp.
References init().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQMoietiesTaskResult::~CQMoietiesTaskResult ()
Definition at line 50 of file CQMoietiesTaskResult.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQMoietiesTaskResult::clear ()
Definition at line 121 of file CQMoietiesTaskResult.cpp.
Referenced by update().
 {
   mpMoieties->setRowCount(0);
   mpStoichiometry->setArrayAnnotation(NULL);
   mpLinkMatrix->setArrayAnnotation(NULL);
   mpReducedStoichiometry->setArrayAnnotation(NULL);
 }
bool CQMoietiesTaskResult::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 132 of file CQMoietiesTaskResult.cpp.
References load(), mpMoietiesTask, and CopasiWidget::mpObject.
 {
   mpMoietiesTask = dynamic_cast< CMoietiesTask * >(mpObject);
   load();
   return true;
 }
void CQMoietiesTaskResult::init () private
Definition at line 55 of file CQMoietiesTaskResult.cpp.
References COL_AMOUNT, COL_BTN, COL_EQUATION, COL_NUMBER, COL_SPECIES, CQIconResource::icon(), mpMoietiesTask, slotCreateGlobalQuantity(), CQIconResource::tool, and CQPushButtonDelegate::ToolButton.
Referenced by CQMoietiesTaskResult().
 {
   mpMoietiesTask = NULL;
   QImage ToolBtn;
   // Initialize the moieties tab
   mpMoieties->setColumnCount(5);
   QTableWidgetItem * pItem = new QTableWidgetItem("Dependent Species");
   mpMoieties->setHorizontalHeaderItem(COL_SPECIES, pItem);
   pItem = new QTableWidgetItem("Total Particle Number");
   mpMoieties->setHorizontalHeaderItem(COL_NUMBER, pItem);
   pItem = new QTableWidgetItem("Total Amount");
   mpMoieties->setHorizontalHeaderItem(COL_AMOUNT, pItem);
   pItem = new QTableWidgetItem("");
   mpMoieties->setHorizontalHeaderItem(COL_BTN, pItem);
   pItem = new QTableWidgetItem("Expression");
   mpMoieties->setHorizontalHeaderItem(COL_EQUATION, pItem);
   CQPushButtonDelegate * pDelegate = new CQPushButtonDelegate(CQIconResource::icon(CQIconResource::tool), "",  CQPushButtonDelegate::ToolButton, this);
   mpMoieties->setItemDelegateForColumn(COL_BTN, pDelegate);
   connect(pDelegate, SIGNAL(clicked(const QModelIndex &)), this, SLOT(slotCreateGlobalQuantity(const QModelIndex &)));
   // Initialize the stoichiometry tab
   mpStoichiometry->setLegendEnabled(true);
   // Initialize the stoichiometry tab
   mpLinkMatrix->setLegendEnabled(true);
   // Initialize the stoichiometry tab
   mpReducedStoichiometry->setLegendEnabled(true);
 }
bool CQMoietiesTaskResult::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 129 of file CQMoietiesTaskResult.cpp.
 {return true;}
void CQMoietiesTaskResult::load ()
Definition at line 141 of file CQMoietiesTaskResult.cpp.
References CCopasiVector< T >::begin(), COL_AMOUNT, COL_BTN, COL_EQUATION, COL_NUMBER, COL_SPECIES, CCopasiVector< T >::end(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getModel(), CModel::getMoieties(), CCopasiContainer::getObject(), and CModel::getQuantityUnitsDisplayString().
Referenced by enterProtected().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL) return;
   // Set the units for the amount column
   QString AmountUnits = FROM_UTF8(pModel->getQuantityUnitsDisplayString());
   if (!AmountUnits.isEmpty())
     AmountUnits = "\n(" + AmountUnits + ")";
   mpMoieties->horizontalHeaderItem(COL_AMOUNT)->setText("Total Amount" + AmountUnits);
   // Fill the moieties table
   CCopasiVector< CMoiety >::const_iterator it = pModel->getMoieties().begin();
   CCopasiVector< CMoiety >::const_iterator end = pModel->getMoieties().end();
   mpMoieties->setRowCount(end - it);
   QTableWidgetItem * pItem;
   int i = 0;
   for (; it != end; ++it, i++)
     {
       pItem = new QTableWidgetItem(FROM_UTF8((*it)->getObjectName()));
       mpMoieties->setItem(i, COL_SPECIES, pItem);;
       pItem = new QTableWidgetItem(QString::number((*it)->getNumber()));
       mpMoieties->setItem(i, COL_NUMBER, pItem);
       (*it)->refreshAmount();
       pItem = new QTableWidgetItem(QString::number((*it)->getAmount()));
       mpMoieties->setItem(i, COL_AMOUNT, pItem);
       pItem = new QTableWidgetItem("");
       mpMoieties->setItem(i, COL_BTN, pItem);
       // Show the Button
       pItem = mpMoieties->item(i, COL_BTN);
       pItem->setFlags(pItem->flags() | Qt::ItemIsEditable | Qt::ItemIsEnabled);
       mpMoieties->openPersistentEditor(pItem);
       pItem = new QTableWidgetItem(FROM_UTF8((*it)->getDescription(pModel)));
       mpMoieties->setItem(i, COL_EQUATION, pItem);
     }
   mpTabWidget->setTabText(mpTabWidget->indexOf(mpMoieties), "Moieties (" + QString::number(i) + ")");
   mpMoieties->resizeColumnsToContents();
   mpMoieties->resizeRowsToContents();
   // Fill the stoichiometry matrix
   CColorScaleBiLog * tcs = NULL;
   const CArrayAnnotation * pAnnotation =
     static_cast< const CArrayAnnotation * >(pModel->getObject(CCopasiObjectName("Array=Stoichiometry(ann)")));
   tcs = new CColorScaleBiLog();
   mpStoichiometry->setColorCoding(tcs);
   mpStoichiometry->setColorScalingAutomatic(true);
   mpStoichiometry->setArrayAnnotation(pAnnotation);
   // Fill the link matrix
   pAnnotation =
     static_cast< const CArrayAnnotation * >(pModel->getObject(CCopasiObjectName("Array=Link matrix(ann)")));
   tcs = new CColorScaleBiLog();
   mpLinkMatrix->setColorCoding(tcs);
   mpLinkMatrix->setColorScalingAutomatic(true);
   mpLinkMatrix->setArrayAnnotation(pAnnotation);
   // Fill the reduced stoichiometry matrix
   pAnnotation =
     static_cast< const CArrayAnnotation * >(pModel->getObject(CCopasiObjectName("Array=Reduced stoichiometry(ann)")));
   tcs = new CColorScaleBiLog();
   mpReducedStoichiometry->setColorCoding(tcs);
   mpReducedStoichiometry->setColorScalingAutomatic(true);
   mpReducedStoichiometry->setArrayAnnotation(pAnnotation);
   return;
 }
void CQMoietiesTaskResult::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 280 of file CQMoietiesTaskResult.cpp.
References COL_AMOUNT, COL_NUMBER, CopasiWidget::mFramework, and CopasiWidget::setFramework().
 {
   CopasiWidget::setFramework(framework);
   switch (mFramework)
     {
       case 0: // Concentration
         mpMoieties->showColumn(COL_AMOUNT);
         mpMoieties->hideColumn(COL_NUMBER);
         break;
       case 1: // Particle Number
         mpMoieties->hideColumn(COL_AMOUNT);
         mpMoieties->showColumn(COL_NUMBER);
         break;
     }
 }
void CQMoietiesTaskResult::slotCreateGlobalQuantity (const QModelIndex & index) private slot
Definition at line 253 of file CQMoietiesTaskResult.cpp.
References ListViews::ADD, C_INT32, CModel::createModelValue(), CCopasiRootContainer::getDatamodelList(), CMoiety::getExpression(), CModel::getMoieties(), CCopasiObject::getObjectName(), ListViews::MODELVALUE, CopasiWidget::protectedNotify(), CModelEntity::setInitialExpression(), CCopasiVector< T >::size(), and TO_UTF8.
Referenced by init().
 {
   int row = index.row();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel * pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   if (pModel == NULL) return;
   CCopasiVector< CMoiety > Moieties = pModel->getMoieties();
   if (row >= (C_INT32) Moieties.size()) return;
   const CMoiety * pMoiety = Moieties[row];
   CModelValue * pMV = pModel->createModelValue("Moiety[" + pMoiety->getObjectName() + "].TotalAmount");
   int i = 0;
   while (pMV == NULL)
     pMV = pModel->createModelValue("Moiety[" + pMoiety->getObjectName() + "].TotalAmount_" + TO_UTF8(QString::number(++i)));
   pMV->setInitialExpression(pMoiety->getExpression());
   protectedNotify(ListViews::MODELVALUE, ListViews::ADD);
 }
void CQMoietiesTaskResult::slotSave (void) private slot
Definition at line 223 of file CQMoietiesTaskResult.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CCopasiTask::getResult(), CopasiFileDialog::getSaveFileName(), mpMoietiesTask, and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail())
     return;
   if (mpMoietiesTask != NULL)
     file << mpMoietiesTask->getResult();
   return;
 }
bool CQMoietiesTaskResult::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 90 of file CQMoietiesTaskResult.cpp.
References ListViews::ADD, ListViews::CHANGE, clear(), and ListViews::MODEL.
 {
   // :TODO:
   switch (objectType)
     {
       case ListViews::MODEL:
         switch (action)
           {
             case ListViews::ADD:
               clear();
               break;
             case ListViews::CHANGE:
               break;
             default:
               break;
           }
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
CMoietiesTask* CQMoietiesTaskResult::mpMoietiesTask protected
Definition at line 38 of file CQMoietiesTaskResult.h.
Referenced by enterProtected(), init(), and slotSave().
The documentation for this class was generated from the following files:
CQMoietiesTaskResult.h
CQMoietiesTaskResult.cpp