COPASI API: CTableauLine Class Reference
CTableauLine Class Reference
#include <CTableauLine.h>
Public Member Functions
CTableauLine ()
CTableauLine (const std::vector< C_FLOAT64 > &reaction, bool reversible, const size_t &reactionCounter, const size_t &reactionNumber)
CTableauLine (C_FLOAT64 m1, const CTableauLine &src1, C_FLOAT64 m2, const CTableauLine &src2)
const std::vector< C_FLOAT64 > & getFluxMode () const
const C_FLOAT64 & getMultiplier (const size_t &index) const
const CFluxScore & getScore () const
bool isReversible () const
~CTableauLine ()
Static Private Member Functions
static void reduce (C_FLOAT64 &r1, C_FLOAT64 &r2)
Private Attributes
std::vector< C_FLOAT64 > mFluxMode
CFluxScore * mpFluxScore
std::vector< C_FLOAT64 > mReaction
bool mReversible
Friends
std::ostream & operator<< (std::ostream &, const CTableauLine &)
Detailed Description
CTableauLine class. This store one row of the Tableau Matrix
Created for COPASI by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 37 of file CTableauLine.h.
Constructor & Destructor Documentation
CTableauLine::CTableauLine ()
Default constructor
CTableauLine class. This store one row of the Tableau Matrix
Created for COPASI by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 37 of file CTableauLine.cpp.
References CONSTRUCTOR_TRACE, and mpFluxScore.
 {CONSTRUCTOR_TRACE; mpFluxScore = NULL;}
CTableauLine::CTableauLine (const std::vector< C_FLOAT64 > & reaction, bool reversible, const size_t & reactionCounter, const size_t & reactionNumber)
Specific constructor
Definition at line 39 of file CTableauLine.cpp.
References CONSTRUCTOR_TRACE, mFluxMode, mpFluxScore, mReaction, and mReversible.
 {
   CONSTRUCTOR_TRACE;
   mReaction = reaction;
   mReversible = reversible;
   mFluxMode.resize(reactionNumber, 0);
   mFluxMode[reactionCounter] = 1;
   mpFluxScore = new CFluxScore(mFluxMode);
 }
CTableauLine::CTableauLine (C_FLOAT64 m1, const CTableauLine & src1, C_FLOAT64 m2, const CTableauLine & src2)
Specific constructor
Definition at line 54 of file CTableauLine.cpp.
References CONSTRUCTOR_TRACE, mFluxMode, mpFluxScore, mReaction, mReversible, and reduce().
 {
   CONSTRUCTOR_TRACE;
   // We need to remove common factors in m1 and m2
   reduce(m1, m2);
   mReversible = (src1.mReversible && src2.mReversible);
   mReaction.resize(src1.mReaction.size());
   mFluxMode.resize(src1.mFluxMode.size());
   std::vector< C_FLOAT64 >::const_iterator it1 = src1.mReaction.begin();
   std::vector< C_FLOAT64 >::const_iterator it2 = src2.mReaction.begin();
   std::vector< C_FLOAT64 >::iterator it = mReaction.begin();
   std::vector< C_FLOAT64 >::iterator end = mReaction.end();
   for (; it != end; ++it, ++it1, ++it2)
     *it = m1 * *it1 + m2 * *it2;
   it1 = src1.mFluxMode.begin();
   it2 = src2.mFluxMode.begin();
   it = mFluxMode.begin();
   end = mFluxMode.end();
   for (; it != end; ++it, ++it1, ++it2)
     *it = m1 * *it1 + m2 * *it2;
   mpFluxScore = new CFluxScore(mFluxMode);
 }
CTableauLine::~CTableauLine ()
Destructor
Definition at line 87 of file CTableauLine.cpp.
References DESTRUCTOR_TRACE, mpFluxScore, and pdelete.
 {DESTRUCTOR_TRACE; pdelete(mpFluxScore);}
Member Function Documentation
const std::vector< C_FLOAT64 > & CTableauLine::getFluxMode () const
Retrieves the flux mode
Definition at line 97 of file CTableauLine.cpp.
References mFluxMode.
Referenced by CFluxMode::CFluxMode().
 {
   return mFluxMode;
 }
const C_FLOAT64 & CTableauLine::getMultiplier (const size_t & index) const
Retrieve the multiplier for this reaction for the indexed species
Parameters
const size_t & index
Returns
const C_FLOAT64 & multiplier
Definition at line 94 of file CTableauLine.cpp.
References mReaction.
 {return mReaction[mReaction.size() - index - 1];}
const CFluxScore & CTableauLine::getScore () const
Retrieves the flux score
Definition at line 89 of file CTableauLine.cpp.
References mpFluxScore.
Referenced by CTableauMatrix::isValid().
 {
   return *mpFluxScore;
 }
bool CTableauLine::isReversible () const
Checks whether the reaction is reversible
Returns
"bool" isReversible
Definition at line 102 of file CTableauLine.cpp.
References mReversible.
Referenced by CTableauMatrix::addLine(), CFluxMode::CFluxMode(), and operator<<().
 {
   return mReversible;
 }
void CTableauLine::reduce (C_FLOAT64 & r1, C_FLOAT64 & r2) static private
Remove the first entry from the reaction vector Divides m1 and m2 by the largest common factor.
Definition at line 137 of file CTableauLine.cpp.
References C_FLOAT64, and C_INT32.
Referenced by CTableauLine().
 {
   if (floor(r1) != r1 || floor(r2) != r2)
     return;
   C_INT32 GCD1 = (C_INT32) fabs(r1);
   C_INT32 GCD2 = (C_INT32) fabs(r2);
   while (GCD1 != GCD2)
     {
       if (GCD1 > GCD2)
         {
           GCD1 %= GCD2;
           if (GCD1 == 0)
             {
               GCD1 = GCD2;
             }
         }
       else
         {
           GCD2 %= GCD1;
           if (GCD2 == 0)
             {
               GCD2 = GCD1;
             }
         }
     }
   r1 /= (C_FLOAT64) GCD1;
   r2 /= (C_FLOAT64) GCD2;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CTableauLine & l) friend
Definition at line 113 of file CTableauLine.cpp.
 {
   size_t i, imax = l.mReaction.size();
   size_t j, jmax = l.mFluxMode.size();
   if (l.isReversible())
     os << "reversible:  ";
   else
     os << "irreversible:";
   for (i = 0; i < imax; i++)
     os << "  " << l.mReaction[i];
   os << "\t";
   for (j = 0; j < jmax; j++)
     os << "  " << l.mFluxMode[j];
   os << std::endl;
   return os;
 }
Member Data Documentation
std::vector<C_FLOAT64> CTableauLine::mFluxMode private
Definition at line 56 of file CTableauLine.h.
Referenced by CTableauLine(), getFluxMode(), and operator<<().
CFluxScore* CTableauLine::mpFluxScore private
Definition at line 61 of file CTableauLine.h.
Referenced by CTableauLine(), getScore(), and ~CTableauLine().
std::vector<C_FLOAT64> CTableauLine::mReaction private
Definition at line 46 of file CTableauLine.h.
Referenced by CTableauLine(), getMultiplier(), and operator<<().
bool CTableauLine::mReversible private
Definition at line 51 of file CTableauLine.h.
Referenced by CTableauLine(), and isReversible().
The documentation for this class was generated from the following files:
CTableauLine.h
CTableauLine.cpp