COPASI API: CTrajectoryTask Class Reference
CTrajectoryTask Class Reference
#include <CTrajectoryTask.h>
Public Member Functions
virtual CCopasiMethod * createMethod (const int &type) const
CTrajectoryTask (const CCopasiContainer *pParent=NULL)
CTrajectoryTask (const CTrajectoryTask &src, const CCopasiContainer *pParent=NULL)
CState * getState ()
const CTimeSeries & getTimeSeries () const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
void load (CReadConfig &configBuffer)
virtual bool process (const bool &useInitialValues)
void processStart (const bool &useInitialValues)
bool processStep (const C_FLOAT64 &nextTime)
virtual bool restore ()
virtual bool setMethodType (const int &type)
~CTrajectoryTask ()
Public Member Functions inherited from CCopasiTask
CCopasiTask (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const Type &taskType, const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const CCopasiTask &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
CProcessReport * getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
Type getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReport *pCallBack)
void setScheduled (const bool &scheduled)
void setType (const Type &type)
void setUpdateModel (const bool &updateModel)
virtual bool updateMatrices ()
virtual ~CCopasiTask ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const unsigned int ValidMethods []
Static Public Attributes inherited from CCopasiTask
static const std::string TypeName []
static const unsigned int ValidMethods []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Private Member Functions
void cleanup ()
Private Attributes
C_FLOAT64 mOutputStartTime
CState * mpCurrentState
const C_FLOAT64 * mpCurrentTime
bool(* mpLess)(const C_FLOAT64 &, const C_FLOAT64 &)
bool(* mpLessOrEqual)(const C_FLOAT64 &, const C_FLOAT64 &)
CTrajectoryMethod * mpTrajectoryMethod
CTrajectoryProblem * mpTrajectoryProblem
CTimeSeries mTimeSeries
bool mTimeSeriesRequested
bool mUpdateMoieties
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01, STREAM = 0x02, FINISH = 0x04, REPORT = 0x10,
PLOT = 0x20, TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0, OUTPUT_BEFORE = INITIALIZE, OUTPUT_AFTER = FINISH, OUTPUT = REPORT | PLOT | STREAM,
OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH, OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH, ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
enum Type {
steadyState = 0, timeCourse, scan, fluxMode,
optimization, parameterFitting, mca, lyap,
tssAnalysis, sens, moieties, crosssection,
lna, unset
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiTask
static bool isValidMethod (const unsigned int &method, const unsigned int *validMethods)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
std::string mKey
unsigned C_INT32 mOutputCounter
CProcessReport * mpCallBack
CState * mpInitialState
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
Type mType
bool mUpdateModel
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 37 of file CTrajectoryTask.h.
Constructor & Destructor Documentation
CTrajectoryTask::CTrajectoryTask (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 73 of file CTrajectoryTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiMethod::deterministic, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, mUpdateMoieties, and CCopasiParameter::Value::pBOOL.
                                                                 :
   CCopasiTask(CCopasiTask::timeCourse, pParent),
   mTimeSeriesRequested(true),
   mTimeSeries(),
   mpTrajectoryProblem(NULL),
   mpTrajectoryMethod(NULL),
   mUpdateMoieties(false),
   mpCurrentState(NULL),
   mpCurrentTime(NULL),
   mOutputStartTime(0.0),
   mpLessOrEqual(&fle),
   mpLess(&fl)
 {
   mpProblem = new CTrajectoryProblem(this);
   mpMethod = createMethod(CCopasiMethod::deterministic);
   this->add(mpMethod, true);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
 }
CTrajectoryTask::CTrajectoryTask (const CTrajectoryTask & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CTrajectoryTask & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 98 of file CTrajectoryTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiParameterGroup::elevateChildren(), CCopasiMethod::getSubType(), CCopasiParameter::getValue(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, mUpdateMoieties, and CCopasiParameter::Value::pBOOL.
                                                                   :
   CCopasiTask(src, pParent),
   mTimeSeriesRequested(src.mTimeSeriesRequested),
   mTimeSeries(),
   mpTrajectoryProblem(NULL),
   mpTrajectoryMethod(NULL),
   mUpdateMoieties(false),
   mpCurrentState(NULL),
   mpCurrentTime(NULL),
   mOutputStartTime(0.0),
   mpLessOrEqual(src.mpLessOrEqual),
   mpLess(src.mpLess)
 {
   mpProblem =
     new CTrajectoryProblem(*static_cast< CTrajectoryProblem * >(src.mpProblem), this);
   mpMethod = createMethod(src.mpMethod->getSubType());
   * mpMethod = * src.mpMethod;
   mpMethod->elevateChildren();
   this->add(mpMethod, true);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
 }
CTrajectoryTask::~CTrajectoryTask ()
Destructor
Definition at line 130 of file CTrajectoryTask.cpp.
References cleanup().
 {
   cleanup();
 }
Member Function Documentation
void CTrajectoryTask::cleanup () private
cleanup()
Definition at line 135 of file CTrajectoryTask.cpp.
References mpCurrentState, and pdelete.
Referenced by ~CTrajectoryTask().
 {
   pdelete(mpCurrentState);
 }
CCopasiMethod * CTrajectoryTask::createMethod (const int & type) const virtual
Create a method of the specified type to solve the task. It is the duty of the caller to release the CCopasiMethod.
Parameters
const CCopasiMethod::SubType & type
Returns
CCopasiMethod *
Reimplemented from CCopasiTask.
Definition at line 537 of file CTrajectoryTask.cpp.
References CTrajectoryMethod::createMethod().
Referenced by CTrajectoryTask(), and setMethodType().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   return CTrajectoryMethod::createMethod(Type);
 }
CState * CTrajectoryTask::getState ()
Retrieves a pointer to current state of the integration.
Returns
CState * pState
Definition at line 544 of file CTrajectoryTask.cpp.
References mpCurrentState.
Referenced by CNewtonMethod::doIntegration().
 {return mpCurrentState;}
const CTimeSeries & CTrajectoryTask::getTimeSeries () const
gets a reference to the time series
Returns
time series
Definition at line 547 of file CTrajectoryTask.cpp.
References mTimeSeries.
Referenced by CQGLNetworkPainter::createDataSets(), QTimeCourseAnimation::getScales(), getTimeSeriesFromTask(), and QTimeCourseAnimation::initialize().
 {return mTimeSeries;}
bool CTrajectoryTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 161 of file CTrajectoryTask.cpp.
References COutputHandler::addInterface(), CTimeSeries::allocate(), CTimeSeries::clear(), CTrajectoryProblem::getContinueSimultaneousEvents(), CModel::getMathModel(), CCopasiProblem::getModel(), CCopasiParameterGroup::getParameter(), CMathModel::getProcessQueue(), CModel::getState(), CTrajectoryProblem::getStepNumber(), CState::getTime(), CCopasiParameter::getValue(), CCopasiTask::initialize(), CCopasiMethod::isValidProblem(), mpCurrentState, mpCurrentTime, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mpTrajectoryMethod, mpTrajectoryProblem, mTimeSeries, mTimeSeriesRequested, mUpdateMoieties, CCopasiParameter::Value::pBOOL, pdelete, CProcessQueue::setContinueSimultaneousEvents(), CTrajectoryMethod::setProblem(), CCopasiTask::TIME_SERIES, and CTrajectoryProblem::timeSeriesRequested().
Referenced by CFitProblem::initialize(), CNewtonMethod::initialize(), and test000087::test_simulate_reaction_flux_reference_1().
 {
   assert(mpProblem && mpMethod);
   mpTrajectoryProblem = dynamic_cast<CTrajectoryProblem *>(mpProblem);
   assert(mpTrajectoryProblem);
   mpTrajectoryMethod = dynamic_cast<CTrajectoryMethod *>(mpMethod);
   assert(mpTrajectoryMethod);
   mpTrajectoryMethod->setProblem(mpTrajectoryProblem);
   bool success = mpMethod->isValidProblem(mpProblem);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
   pdelete(mpCurrentState);
   mpCurrentState = new CState(mpTrajectoryProblem->getModel()->getState());
   mpCurrentTime = &mpCurrentState->getTime();
   //mpOutputStartTime = & mpTrajectoryProblem->getOutputStartTime();
   // Handle the time series as a regular output.
   mTimeSeriesRequested = mpTrajectoryProblem->timeSeriesRequested();
   if ((pOutputHandler != NULL) &&
       mTimeSeriesRequested &&
       (of & CCopasiTask::TIME_SERIES))
     {
       mTimeSeries.allocate(mpTrajectoryProblem->getStepNumber());
       pOutputHandler->addInterface(&mTimeSeries);
     }
   else
     {
       mTimeSeries.clear();
     }
   mpTrajectoryProblem->getModel()->getMathModel()->getProcessQueue().setContinueSimultaneousEvents(mpTrajectoryProblem->getContinueSimultaneousEvents());
   if (!CCopasiTask::initialize(of, pOutputHandler, pOstream)) success = false;
   return success;
 }
void CTrajectoryTask::load (CReadConfig & configBuffer)
Loads parameters for this solver with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
configbuffer reference to a CReadConfig object.
Definition at line 140 of file CTrajectoryTask.cpp.
References CCopasiContainer::add(), CTrajectoryMethod::createMethod(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), CReadConfig::getVariable(), CReadConfig::LOOP, CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::mScheduled, mUpdateMoieties, CCopasiParameter::Value::pBOOL, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   configBuffer.getVariable("Dynamics", "bool", &mScheduled,
                            CReadConfig::LOOP);
   pdelete(mpProblem);
   mpProblem = new CTrajectoryProblem(this);
   ((CTrajectoryProblem *) mpProblem)->load(configBuffer);
   pdelete(mpMethod);
   mpMethod = CTrajectoryMethod::createMethod();
   this->add(mpMethod, true);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   ((CTrajectoryMethod *)mpMethod)->setProblem((CTrajectoryProblem *) mpProblem);
 }
bool CTrajectoryTask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 212 of file CTrajectoryTask.cpp.
References CProcessReport::addItem(), COutputInterface::AFTER, COutputInterface::BEFORE, bl(), ble(), C_FLOAT64, C_INT32, COutputInterface::DURING, CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CProcessReport::finishItem(), fl(), fle(), CTrajectoryProblem::getDuration(), CCopasiException::getMessage(), CCopasiProblem::getModel(), CTrajectoryProblem::getOutputStartTime(), CTrajectoryProblem::getStepSize(), MCTrajectoryMethod, MCTrajectoryProblem, min, mOutputStartTime, CCopasiTask::mpCallBack, mpCurrentState, mpCurrentTime, mpLess, mpLessOrEqual, mpTrajectoryProblem, mUpdateMoieties, CCopasiTask::output(), processStart(), processStep(), CProcessReport::progressItem(), CProcessReport::setName(), CModel::setState(), and CModel::updateSimulatedValues().
Referenced by CNewtonMethod::doIntegration(), and test000087::test_simulate_reaction_flux_reference_1().
 {
   //*****
   processStart(useInitialValues);
   //*****
   //size_t FailCounter = 0;
   C_FLOAT64 Duration = mpTrajectoryProblem->getDuration();
   C_FLOAT64 StepSize = mpTrajectoryProblem->getStepSize();
   C_FLOAT64 StepNumber = fabs(Duration) / StepSize;
   if (isnan(StepNumber) || StepNumber < 1.0)
     StepNumber = 1.0;
   //the output starts only after "outputStartTime" has passed
   if (useInitialValues)
     mOutputStartTime = mpTrajectoryProblem->getOutputStartTime();
   else
     mOutputStartTime = *mpCurrentTime + mpTrajectoryProblem->getOutputStartTime();
   C_FLOAT64 NextTimeToReport;
   const C_FLOAT64 EndTime = *mpCurrentTime + Duration;
   const C_FLOAT64 StartTime = *mpCurrentTime;
   C_FLOAT64 CompareEndTime;
   if (StepSize < 0.0)
     {
       mpLessOrEqual = &ble;
       mpLess = &bl;
       // It suffices to reach the end time within machine precision
       CompareEndTime = EndTime + 100.0 * (fabs(EndTime) * std::numeric_limits< C_FLOAT64 >::epsilon() + std::numeric_limits< C_FLOAT64 >::min());
     }
   else
     {
       mpLessOrEqual = &fle;
       mpLess = &fl;
       // It suffices to reach the end time within machine precision
       CompareEndTime = EndTime - 100.0 * (fabs(EndTime) * std::numeric_limits< C_FLOAT64 >::epsilon() + std::numeric_limits< C_FLOAT64 >::min());
     }
   unsigned C_INT32 StepCounter = 1;
   if (StepSize == 0.0 && Duration != 0.0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCTrajectoryProblem + 1, StepSize);
       return false;
     }
   output(COutputInterface::BEFORE);
   bool flagProceed = true;
   C_FLOAT64 handlerFactor = 100.0 / Duration;
   C_FLOAT64 Percentage = 0;
   size_t hProcess;
   if (mpCallBack != NULL && StepNumber > 1.0)
     {
       mpCallBack->setName("performing simulation...");
       C_FLOAT64 hundred = 100;
       hProcess = mpCallBack->addItem("Completion",
                                      Percentage,
                                      &hundred);
     }
   if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime)) output(COutputInterface::DURING);
   try
     {
       do
         {
           // This is numerically more stable then adding
           // mpTrajectoryProblem->getStepSize().
           NextTimeToReport =
             StartTime + (EndTime - StartTime) * StepCounter++ / StepNumber;
           flagProceed &= processStep(NextTimeToReport);
           if (mpCallBack != NULL && StepNumber > 1.0)
             {
               Percentage = (*mpCurrentTime - StartTime) * handlerFactor;
               flagProceed &= mpCallBack->progressItem(hProcess);
             }
           if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime))
             {
               output(COutputInterface::DURING);
             }
         }
       while ((*mpLess)(*mpCurrentTime, CompareEndTime) && flagProceed);
     }
   catch (int)
     {
       mpTrajectoryProblem->getModel()->setState(*mpCurrentState);
       mpTrajectoryProblem->getModel()->updateSimulatedValues(mUpdateMoieties);
       if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime))
         {
           output(COutputInterface::DURING);
         }
       if (mpCallBack != NULL && StepNumber > 1.0) mpCallBack->finishItem(hProcess);
       output(COutputInterface::AFTER);
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 16);
     }
   catch (CCopasiException & Exception)
     {
       mpTrajectoryProblem->getModel()->setState(*mpCurrentState);
       mpTrajectoryProblem->getModel()->updateSimulatedValues(mUpdateMoieties);
       if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime))
         {
           output(COutputInterface::DURING);
         }
       if (mpCallBack != NULL && StepNumber > 1.0) mpCallBack->finishItem(hProcess);
       output(COutputInterface::AFTER);
       throw CCopasiException(Exception.getMessage());
     }
   if (mpCallBack != NULL && StepNumber > 1.0) mpCallBack->finishItem(hProcess);
   output(COutputInterface::AFTER);
   return true;
 }
void CTrajectoryTask::processStart (const bool & useInitialValues)
Starts the process of integration by calling CTrajectoryMethod::start
Parameters
const bool & useInitialValues
Definition at line 351 of file CTrajectoryTask.cpp.
References CModel::applyInitialValues(), CCopasiProblem::getModel(), CModel::getState(), mpCurrentState, mpTrajectoryMethod, mpTrajectoryProblem, CTrajectoryMethod::setCurrentState(), and CTrajectoryMethod::start().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), and process().
 {
   if (useInitialValues)
     mpTrajectoryProblem->getModel()->applyInitialValues();
   *mpCurrentState = mpTrajectoryProblem->getModel()->getState();
   mpTrajectoryMethod->setCurrentState(mpCurrentState);
   mpTrajectoryMethod->start(mpCurrentState);
   return;
 }
bool CTrajectoryTask::processStep (const C_FLOAT64 & nextTime)
Integrates one step
Parameters
const C_FLOAT64 & nextTime
Returns
bool success;
Definition at line 364 of file CTrajectoryTask.cpp.
References C_FLOAT64, COutputInterface::DURING, CCopasiMessage::EXCEPTION, CTrajectoryMethod::FAILURE, CCopasiProblem::getModel(), CTrajectoryProblem::getOutputEvent(), CModel::getProcessQueueExecutionTime(), CTrajectoryMethod::getRoots(), CModel::getState(), MCTrajectoryMethod, min, mOutputStartTime, CCopasiTask::mpCallBack, mpCurrentState, mpCurrentTime, mpLessOrEqual, mpTrajectoryMethod, mpTrajectoryProblem, mUpdateMoieties, CTrajectoryMethod::NORMAL, CCopasiTask::output(), CProcessReport::proceed(), CModel::processQueue(), CModel::processRoots(), CTrajectoryMethod::ROOT, CModel::setState(), CTrajectoryMethod::stateChanged(), CTrajectoryMethod::step(), and CModel::updateSimulatedValues().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), and process().
 {
   CModel * pModel = mpTrajectoryProblem->getModel();
   bool StateChanged = false;
   bool proceed = true;
   C_FLOAT64 Tolerance = 100.0 * (fabs(endTime) * std::numeric_limits< C_FLOAT64 >::epsilon() + std::numeric_limits< C_FLOAT64 >::min());
   C_FLOAT64 NextTime = endTime;
   while (proceed)
     {
       // TODO Provide a call back method for resolving simultaneous assignments.
       StateChanged = pModel->processQueue(*mpCurrentTime, false, NULL);
       if (StateChanged)
         {
           if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime) &&
               mpTrajectoryProblem->getOutputEvent())
             {
               output(COutputInterface::DURING);
             }
           *mpCurrentState = pModel->getState();
           mpTrajectoryMethod->stateChanged();
           StateChanged = false;
         }
       // std::min suffices since events are only supported in forward integration.
       NextTime = std::min(endTime, pModel->getProcessQueueExecutionTime());
       switch (mpTrajectoryMethod->step(NextTime - *mpCurrentTime))
         {
           case CTrajectoryMethod::NORMAL:
             pModel->setState(*mpCurrentState);
             pModel->updateSimulatedValues(mUpdateMoieties);
             if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime) &&
                 *mpCurrentTime == pModel->getProcessQueueExecutionTime() &&
                 mpTrajectoryProblem->getOutputEvent())
               {
                 output(COutputInterface::DURING);
               }
             // TODO Provide a call back method for resolving simultaneous assignments.
             StateChanged = pModel->processQueue(*mpCurrentTime, true, NULL);
             if (fabs(*mpCurrentTime - endTime) < Tolerance)
               {
                 if (StateChanged)
                   {
                     *mpCurrentState = pModel->getState();
                     mpTrajectoryMethod->stateChanged();
                     StateChanged = false;
                   }
                 return true;
               }
             if (StateChanged)
               {
                 if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime) &&
                     mpTrajectoryProblem->getOutputEvent())
                   {
                     output(COutputInterface::DURING);
                   }
                 *mpCurrentState = pModel->getState();
                 mpTrajectoryMethod->stateChanged();
                 StateChanged = false;
               }
             break;
           case CTrajectoryMethod::ROOT:
             pModel->setState(*mpCurrentState);
             pModel->updateSimulatedValues(mUpdateMoieties);
             pModel->processRoots(*mpCurrentTime, true, true, mpTrajectoryMethod->getRoots());
             if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime) &&
                 *mpCurrentTime == pModel->getProcessQueueExecutionTime() &&
                 mpTrajectoryProblem->getOutputEvent())
               {
                 output(COutputInterface::DURING);
               }
             // TODO Provide a call back method for resolving simultaneous assignments.
             StateChanged = pModel->processQueue(*mpCurrentTime, true, NULL);
             pModel->processRoots(*mpCurrentTime, false, true, mpTrajectoryMethod->getRoots());
             // If the root happens to coincide with end of the step we have to return
             if (fabs(*mpCurrentTime - endTime) < Tolerance)
               {
                 if (StateChanged)
                   {
                     *mpCurrentState = pModel->getState();
                     mpTrajectoryMethod->stateChanged();
                     StateChanged = false;
                   }
                 return true;
               }
             if ((*mpLessOrEqual)(mOutputStartTime, *mpCurrentTime) &&
                 (StateChanged || *mpCurrentTime == pModel->getProcessQueueExecutionTime()) &&
                 mpTrajectoryProblem->getOutputEvent())
               {
                 output(COutputInterface::DURING);
               }
             if (StateChanged)
               {
                 *mpCurrentState = pModel->getState();
                 mpTrajectoryMethod->stateChanged();
                 StateChanged = false;
               }
             break;
           case CTrajectoryMethod::FAILURE:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 12);
             return false;
             break;
         }
       proceed = mpCallBack == NULL || mpCallBack->proceed();
     }
   return proceed;
 }
bool CTrajectoryTask::restore () virtual
Perform necessary cleanup procedures
Reimplemented from CCopasiTask.
Definition at line 497 of file CTrajectoryTask.cpp.
References CCopasiProblem::getModel(), CModel::getState(), mpCurrentState, CCopasiTask::mpProblem, CCopasiTask::mUpdateModel, mUpdateMoieties, CCopasiTask::restore(), CModel::setInitialState(), CModel::setState(), CModel::updateInitialValues(), and CModel::updateSimulatedValues().
Referenced by CFitProblem::restore(), and test000087::test_simulate_reaction_flux_reference_1().
 {
   bool success = CCopasiTask::restore();
   if (mUpdateModel)
     {
       CModel * pModel = mpProblem->getModel();
       pModel->setState(*mpCurrentState);
       pModel->updateSimulatedValues(mUpdateMoieties);
       pModel->setInitialState(pModel->getState());
       pModel->updateInitialValues();
     }
   return success;
 }
bool CTrajectoryTask::setMethodType (const int & type) virtual
Set the method type applied to solve the task
Parameters
const CCopasiMethod::SubType & type
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 514 of file CTrajectoryTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiParameterGroup::getParameter(), CCopasiMethod::getSubType(), CCopasiParameter::getValue(), CCopasiTask::isValidMethod(), CCopasiTask::mpMethod, mUpdateMoieties, CCopasiParameter::Value::pBOOL, pdelete, and ValidMethods.
Referenced by CNewtonMethod::initialize(), test000087::test_simulate_reaction_flux_reference_1(), and SEDMLImporter::updateCopasiTaskForSimulation().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   if (!isValidMethod(Type, ValidMethods)) return false;
   if (mpMethod->getSubType() == Type) return true;
   pdelete(mpMethod);
   mpMethod = createMethod(Type);
   this->add(mpMethod, true);
   CCopasiParameter * pParameter = mpMethod->getParameter("Integrate Reduced Model");
   if (pParameter != NULL)
     mUpdateMoieties = *pParameter->getValue().pBOOL;
   else
     mUpdateMoieties = false;
   return true;
 }
Member Data Documentation
C_FLOAT64 CTrajectoryTask::mOutputStartTime private
A pointer to the time at which the output starts.
Definition at line 86 of file CTrajectoryTask.h.
Referenced by process(), and processStep().
CState* CTrajectoryTask::mpCurrentState private
A pointer to the current state of the integration.
Definition at line 76 of file CTrajectoryTask.h.
Referenced by cleanup(), getState(), initialize(), process(), processStart(), processStep(), and restore().
const C_FLOAT64* CTrajectoryTask::mpCurrentTime private
A pointer to the current time of the integration.
Definition at line 81 of file CTrajectoryTask.h.
Referenced by initialize(), process(), and processStep().
bool(* CTrajectoryTask::mpLess)(const C_FLOAT64 &, const C_FLOAT64 &) private
A pointer to less comparison
Definition at line 96 of file CTrajectoryTask.h.
Referenced by process().
bool(* CTrajectoryTask::mpLessOrEqual)(const C_FLOAT64 &, const C_FLOAT64 &) private
A pointer to lessOrEqual comparison
Definition at line 91 of file CTrajectoryTask.h.
Referenced by process(), and processStep().
CTrajectoryMethod* CTrajectoryTask::mpTrajectoryMethod private
A pointer to the trajectory method
Definition at line 66 of file CTrajectoryTask.h.
Referenced by initialize(), processStart(), and processStep().
CTrajectoryProblem* CTrajectoryTask::mpTrajectoryProblem private
A pointer to the trajectory Problem
Definition at line 61 of file CTrajectoryTask.h.
Referenced by initialize(), process(), processStart(), and processStep().
CTimeSeries CTrajectoryTask::mTimeSeries private
the time series (if requested)
Definition at line 56 of file CTrajectoryTask.h.
Referenced by getTimeSeries(), and initialize().
bool CTrajectoryTask::mTimeSeriesRequested private
whether the time series should be stored in mTimeSeries
Definition at line 51 of file CTrajectoryTask.h.
Referenced by initialize().
bool CTrajectoryTask::mUpdateMoieties private
Indicates whether we need to update moieties.
Definition at line 71 of file CTrajectoryTask.h.
Referenced by CTrajectoryTask(), initialize(), load(), process(), processStep(), restore(), and setMethodType().
const unsigned int CTrajectoryTask::ValidMethods static
Initial value:
=
{
  CCopasiMethod::deterministic,
  CCopasiMethod::stochastic,
  CCopasiMethod::directMethod,
  CCopasiMethod::tauLeap,
  CCopasiMethod::adaptiveSA,
  CCopasiMethod::hybrid,
  CCopasiMethod::hybridLSODA,
  CCopasiMethod::unset
}
The methods which can be selected for performing this task.
Definition at line 44 of file CTrajectoryTask.h.
Referenced by CQTrajectoryWidget::init(), and setMethodType().
The documentation for this class was generated from the following files:
CTrajectoryTask.h
CTrajectoryTask.cpp