COPASI API: CMathEventN::CAssignment Class Reference
CMathEventN::CAssignment Class Reference
#include <CMathEvent.h>
Public Member Functions
CAssignment ()
bool compile (CEventAssignment *pDataAssignment, CMathContainer &container)
void copy (const CAssignment &src, CMathContainer &container, const size_t &valueOffset, const size_t &objectOffset)
void initialize (CMath::sPointers &pointers)
void setExpression (CMathObject *pExpression)
void setTarget (CMathObject *pTarget)
~CAssignment ()
Private Attributes
CMathObject * mpAssignment
CMathObject * mpTarget
Detailed Description
Definition at line 23 of file CMathEvent.h.
Constructor & Destructor Documentation
CMathEventN::CAssignment::CAssignment ()
Default constructor
Definition at line 21 of file CMathEvent.cpp.
                                    :
   mpTarget(NULL),
   mpAssignment(NULL)
 {}
CMathEventN::CAssignment::~CAssignment ()
Destructor
Definition at line 26 of file CMathEvent.cpp.
 {}
Member Function Documentation
bool CMathEventN::CAssignment::compile (CEventAssignment * pDataAssignment, CMathContainer & container)
Definition at line 47 of file CMathEvent.cpp.
References CExpression::compile(), CMath::EventTarget, CMath::Fixed, CEventAssignment::getExpression(), CMathContainer::getMathObject(), CEventAssignment::getTargetObject(), CExpression::setInfix(), and CMathObject::setSimulationType().
Referenced by CMathEventN::compile().
 {
   // A compiled pDataAssignment is prerequisite.
   bool success = true;
   // Determine the target object
   mpTarget = container.getMathObject(pDataAssignment->getTargetObject());
   if (mpTarget != NULL &&
       mpTarget->getSimulationType() == CMath::Fixed)
     {
       mpTarget->setSimulationType(CMath::EventTarget);
     }
   std::vector< CCopasiContainer * > ListOfContainer;
   // Compile the assignment object in the model context
   CExpression AssignmentExpression("AssignmentExpression", &container);
   success &= AssignmentExpression.setInfix(pDataAssignment->getExpression());
   success &= AssignmentExpression.compile(ListOfContainer);
   success &= mpAssignment->setExpression(AssignmentExpression, container);
   return success;
 }
void CMathEventN::CAssignment::copy (const CAssignment & src, CMathContainer & container, const size_t & valueOffset, const size_t & objectOffset)
Copy an existing object
Parameters
const CAssignment & src
CMathContainer & container
const size_t & valueOffset
const size_t & objectOffset
Definition at line 38 of file CMathEvent.cpp.
References mpAssignment, and mpTarget.
Referenced by CMathEventN::copy().
 {
   mpTarget = src.mpTarget + objectOffset;
   mpAssignment = src.mpAssignment + objectOffset;
 }
void CMathEventN::CAssignment::initialize (CMath::sPointers & pointers)
Definition at line 29 of file CMathEvent.cpp.
References CMath::Event, CMath::EventAssignment, CMathObject::initialize(), CMath::sPointers::pEventAssignments, CMath::sPointers::pEventAssignmentsObject, and CMath::SimulationTypeUndefined.
Referenced by CMathEventN::initialize().
 {
   // Initialize the assignment object
   mpAssignment = pointers.pEventAssignmentsObject;
   CMathObject::initialize(pointers.pEventAssignmentsObject, pointers.pEventAssignments,
                           CMath::EventAssignment, CMath::Event, CMath::SimulationTypeUndefined,
                           false, false, NULL);
 }
void CMathEventN::CAssignment::setExpression (CMathObject * pExpression)
Definition at line 78 of file CMathEvent.cpp.
Referenced by CMathEventN::addAssignment().
 {
   mpAssignment = pExpression;
 }
void CMathEventN::CAssignment::setTarget (CMathObject * pTarget)
Definition at line 73 of file CMathEvent.cpp.
Referenced by CMathEventN::addAssignment().
 {
   mpTarget = pTarget;
 }
Member Data Documentation
CMathObject* CMathEventN::CAssignment::mpAssignment private
Definition at line 56 of file CMathEvent.h.
Referenced by copy().
CMathObject* CMathEventN::CAssignment::mpTarget private
Definition at line 55 of file CMathEvent.h.
Referenced by copy().
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp