COPASI API: CLGraphicalPrimitive1D Class Reference
CLGraphicalPrimitive1D Class Reference
#include <CLGraphicalPrimitive1D.h>
Public Member Functions
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Additional Inherited Members
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Detailed Description
Definition at line 24 of file CLGraphicalPrimitive1D.h.
Constructor & Destructor Documentation
CLGraphicalPrimitive1D::CLGraphicalPrimitive1D ()
Constructor.
Definition at line 24 of file CLGraphicalPrimitive1D.cpp.
                                               :
     CLTransformation2D(),
     mStroke(""),
     mStrokeWidth(std::numeric_limits<double>::quiet_NaN())
 {
 }
CLGraphicalPrimitive1D::CLGraphicalPrimitive1D (const GraphicalPrimitive1D & source)
Constructor to generate object from the corresponding SBML object.
Definition at line 34 of file CLGraphicalPrimitive1D.cpp.
                                                                                 :
     CLTransformation2D(source),
     mStroke(source.getStroke()),
     mStrokeWidth(source.getStrokeWidth()),
     mStrokeDashArray(source.getDashArray())
 {
 }
Member Function Documentation
void CLGraphicalPrimitive1D::addSBMLAttributes (GraphicalPrimitive1D * pPrimitive) const virtual
Adds the attributes for a graphical primitive 1D object to the passed in. object.
Converts this object to the corresponding SBML object.
Definition at line 189 of file CLGraphicalPrimitive1D.cpp.
References CLTransformation2D::addSBMLAttributes(), mStroke, mStrokeDashArray, and mStrokeWidth.
Referenced by CLGraphicalPrimitive2D::addSBMLAttributes(), CLRenderCurve::toSBML(), and CLText::toSBML().
 {
   this->CLTransformation2D::addSBMLAttributes(pPrimitive);
   pPrimitive->setStroke(this->mStroke);
   pPrimitive->setStrokeWidth(this->mStrokeWidth);
   pPrimitive->setDashArray(this->mStrokeDashArray);
 }
const std::vector< unsigned int > & CLGraphicalPrimitive1D::getDashArray () const
Returns the stroke color.
Definition at line 85 of file CLGraphicalPrimitive1D.cpp.
References mStrokeDashArray.
Referenced by CLLayoutRenderer::extract_1d_attributes(), getPen(), CCopasiXML::save1DAttributes(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mStrokeDashArray;
 }
const std::string & CLGraphicalPrimitive1D::getStroke () const
Returns the stroke color.
Definition at line 69 of file CLGraphicalPrimitive1D.cpp.
References mStroke.
Referenced by CQRenderConverter::applyStyle(), CLLayoutRenderer::extract_1d_attributes(), fillItemFromText(), getPen(), CCopasiXML::save1DAttributes(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mStroke;
 }
double CLGraphicalPrimitive1D::getStrokeWidth () const
Returns the stroke width.
Definition at line 77 of file CLGraphicalPrimitive1D.cpp.
References mStrokeWidth.
Referenced by CLLayoutRenderer::extract_1d_attributes(), getPen(), and CCopasiXML::save1DAttributes().
 {
   return this->mStrokeWidth;
 }
bool CLGraphicalPrimitive1D::isSetDashArray () const
Returns true is the dash array has been set or false otherwise.
Definition at line 109 of file CLGraphicalPrimitive1D.cpp.
References mStrokeDashArray.
Referenced by CLLayoutRenderer::extract_1d_attributes(), getPen(), CCopasiXML::save1DAttributes(), and CLLayoutRenderer::update_textures_and_colors().
 {
   bool result = true;
   if (mStrokeDashArray.size() < 2 || mStrokeDashArray[0] != mStrokeDashArray[0])
     {
       result = false;
     }
   return result;
 }
bool CLGraphicalPrimitive1D::isSetStroke () const
Returns true is the stroke has been set or false otherwise.
Definition at line 101 of file CLGraphicalPrimitive1D.cpp.
References mStroke.
Referenced by CQRenderConverter::applyStyle(), CCopasiXMLParser::GroupElement::end(), CLLayoutRenderer::extract_1d_attributes(), fillItemFromText(), getPen(), CCopasiXML::save1DAttributes(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return (!this->mStroke.empty() && this->mStroke != "none");
 }
bool CLGraphicalPrimitive1D::isSetStrokeWidth () const
Returns true is the stroke width has been set or false otherwise.
Definition at line 93 of file CLGraphicalPrimitive1D.cpp.
References mStrokeWidth.
Referenced by CCopasiXMLParser::GroupElement::end(), CLLayoutRenderer::extract_1d_attributes(), getPen(), and CCopasiXML::save1DAttributes().
 {
   return (mStrokeWidth == mStrokeWidth);
 }
void CLGraphicalPrimitive1D::parseDashArray (const std::string & s)
Definition at line 121 of file CLGraphicalPrimitive1D.cpp.
References mStrokeDashArray.
Referenced by CCopasiXMLParser::RectangleElement::start(), CCopasiXMLParser::EllipseElement::start(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mStrokeDashArray.clear();
   if (!s.empty())
     {
       std::istringstream is(s);
       size_t size = s.size() + 1;
       char* tmp = new char[size];
       char* tmp2 = tmp;
       char* tmp3;
       char** endptr;
       long value;
       is.getline(tmp2, size, ',');
       // continue until the string is empty or the stream is
       // no longer usable
       while (tmp2[0] != 0 && is.good())
         {
           endptr = &tmp2;
           tmp3 = tmp2;
           value = strtol(tmp2, endptr, 10);
           if (value < 0 || *endptr == tmp3 || (**endptr != '\0' && **endptr != ' ' && **endptr != '\t'))
             {
               this->mStrokeDashArray.clear();
             }
           else
             {
               this->mStrokeDashArray.push_back((unsigned int)value);
             }
           // read next element
           is.getline(tmp2, size, ',');
         }
       // check if the string was parsed to the end
       if (is.eof())
         {
           // we have to parse the current tmp2
           // and check if that was ok
           endptr = &tmp2;
           tmp3 = tmp2;
           value = strtol(tmp2, endptr, 10);
           if (value < 0 || *endptr == tmp3 || (**endptr != '\0' && **endptr != ' ' && **endptr != '\t'))
             {
               this->mStrokeDashArray.clear();
             }
           else
             {
               this->mStrokeDashArray.push_back((unsigned int)value);
             }
         }
       else
         {
           // since we did not parse to the end,
           // there most have been an error
           this->mStrokeDashArray.clear();
         }
       delete[] tmp;
     }
 }
void CLGraphicalPrimitive1D::setDashArray (const std::vector< unsigned int > & array)
Sets the dasharray.
Definition at line 61 of file CLGraphicalPrimitive1D.cpp.
References mStrokeDashArray.
 {
   this->mStrokeDashArray = array;
 }
void CLGraphicalPrimitive1D::setStroke (const std::string & key)
Sets the stroke color.
Definition at line 45 of file CLGraphicalPrimitive1D.cpp.
References mStroke.
Referenced by CCopasiXMLParser::GroupElement::end(), CCopasiXMLParser::RectangleElement::start(), CCopasiXMLParser::EllipseElement::start(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mStroke = key;
 }
void CLGraphicalPrimitive1D::setStrokeWidth (double width)
Sets the stroke width.
Definition at line 53 of file CLGraphicalPrimitive1D.cpp.
References mStrokeWidth.
Referenced by CCopasiXMLParser::GroupElement::end(), CCopasiXMLParser::RectangleElement::start(), CCopasiXMLParser::EllipseElement::start(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mStrokeWidth = (width > 0 || width != width) ? width : 0.0;
 }
Member Data Documentation
std::string CLGraphicalPrimitive1D::mStroke protected
Definition at line 27 of file CLGraphicalPrimitive1D.h.
Referenced by addSBMLAttributes(), getStroke(), isSetStroke(), and setStroke().
std::vector<unsigned int> CLGraphicalPrimitive1D::mStrokeDashArray protected
Definition at line 29 of file CLGraphicalPrimitive1D.h.
Referenced by addSBMLAttributes(), getDashArray(), isSetDashArray(), parseDashArray(), and setDashArray().
double CLGraphicalPrimitive1D::mStrokeWidth protected
Definition at line 28 of file CLGraphicalPrimitive1D.h.
Referenced by addSBMLAttributes(), getStrokeWidth(), isSetStrokeWidth(), and setStrokeWidth().
The documentation for this class was generated from the following files:
CLGraphicalPrimitive1D.h
CLGraphicalPrimitive1D.cpp