COPASI API: CQEFMSpeciesDM Class Reference
CQEFMSpeciesDM Class Reference
#include <CQEFMSpeciesDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQEFMSpeciesDM (QObject *parent=0)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool isDefaultRow (const QModelIndex &i) const
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setTask (const CEFMTask *pTask)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
bool removeRow (int position)
Protected Member Functions
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Private Attributes
std::vector< CFluxMode >
::const_iterator mBeginModes
std::vector< CMetab * >
::const_iterator mBeginSpecies
size_t mModesSize
const CModel * mpModel
const CEFMTask * mpTask
size_t mSpeciesSize
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 31 of file CQEFMSpeciesDM.h.
Constructor & Destructor Documentation
CQEFMSpeciesDM::CQEFMSpeciesDM (QObject * parent = 0)
Definition at line 29 of file CQEFMSpeciesDM.cpp.
                                              :
     CQBaseDataModel(parent),
     mpTask(NULL),
     mBeginModes(),
     mModesSize(0),
     mpModel(NULL),
     mBeginSpecies(),
     mSpeciesSize(0)
 {}
Member Function Documentation
int CQEFMSpeciesDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 47 of file CQEFMSpeciesDM.cpp.
References mpTask, and mSpeciesSize.
 {
   if (mpTask == NULL)
     return 0;
   return (int)(mSpeciesSize + 1);  // For flux mode number
 }
QVariant CQEFMSpeciesDM::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 63 of file CQEFMSpeciesDM.cpp.
References COL_ROW_NUMBER, CEFMTask::getSpeciesChanges(), mBeginModes, mBeginSpecies, mpTask, and rowCount().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       //std::vector< CFluxMode >::const_iterator itMode = mBeginModes + index.row();
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return QVariant(index.row() + 1);
             break;
           default:
           {
             std::pair< C_FLOAT64, C_FLOAT64 > Changes =
               mpTask->getSpeciesChanges(*(mBeginModes + index.row()), **(mBeginSpecies + index.column() - 1));
             if (Changes.first > 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() ||
                 Changes.second > 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon())
               {
                 return QVariant(QString("-" + QString::number(Changes.first) + " | +" + QString::number(Changes.second)));
               }
             return QVariant();
           }
         }
     }
   return QVariant();
 }
Qt::ItemFlags CQEFMSpeciesDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 55 of file CQEFMSpeciesDM.cpp.
 {
   if (!index.isValid())
     return Qt::ItemIsEnabled;
   return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
 }
QVariant CQEFMSpeciesDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 100 of file CQEFMSpeciesDM.cpp.
References COL_ROW_NUMBER, FROM_UTF8, CMetabNameInterface::getDisplayName(), mBeginSpecies, and mpModel.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
             break;
           default:
             return QVariant(QString(FROM_UTF8(CMetabNameInterface::getDisplayName(mpModel, **(mBeginSpecies + section - 1), false))));
             break;
         }
     }
   return QString("%1").arg(section + 1);
 }
bool CQEFMSpeciesDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 158 of file CQEFMSpeciesDM.cpp.
 {
   return false;
 }
bool CQEFMSpeciesDM::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 170 of file CQEFMSpeciesDM.cpp.
 {
   return false;
 }
bool CQEFMSpeciesDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 164 of file CQEFMSpeciesDM.cpp.
 {
   return false;
 }
int CQEFMSpeciesDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 39 of file CQEFMSpeciesDM.cpp.
References mModesSize, and mpTask.
Referenced by data().
 {
   if (mpTask == NULL)
     return 0;
   return (int) mModesSize;
 }
bool CQEFMSpeciesDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 152 of file CQEFMSpeciesDM.cpp.
 {
   return false;
 }
void CQEFMSpeciesDM::setTask (const CEFMTask * pTask)
Definition at line 123 of file CQEFMSpeciesDM.cpp.
References CCopasiVector< T >::begin(), CEFMTask::getFluxModes(), CModel::getMetabolites(), CCopasiProblem::getModel(), CCopasiTask::getProblem(), mBeginModes, mBeginSpecies, mModesSize, mpModel, mpTask, mSpeciesSize, pTask, and CCopasiVector< T >::size().
Referenced by CQEFMResultWidget::loadResult().
 {
   mpTask = pTask;
   if (mpTask != NULL)
     {
       mBeginModes = mpTask->getFluxModes().begin();
       mModesSize = mpTask->getFluxModes().size();
       mpModel = mpTask->getProblem()->getModel();
       if (mpModel != NULL)
         {
           mBeginSpecies = mpModel->getMetabolites().begin();
           mSpeciesSize = mpModel->getMetabolites().size();
         }
       else
         {
           mSpeciesSize = 0;
         }
     }
   else
     {
       mModesSize = 0;
       mpModel = NULL;
       mSpeciesSize = 0;
     }
 }
Member Data Documentation
std::vector< CFluxMode >::const_iterator CQEFMSpeciesDM::mBeginModes private
Definition at line 60 of file CQEFMSpeciesDM.h.
Referenced by data(), and setTask().
std::vector< CMetab * >::const_iterator CQEFMSpeciesDM::mBeginSpecies private
Definition at line 64 of file CQEFMSpeciesDM.h.
Referenced by data(), headerData(), and setTask().
size_t CQEFMSpeciesDM::mModesSize private
Definition at line 61 of file CQEFMSpeciesDM.h.
Referenced by rowCount(), and setTask().
const CModel* CQEFMSpeciesDM::mpModel private
Definition at line 63 of file CQEFMSpeciesDM.h.
Referenced by headerData(), and setTask().
const CEFMTask* CQEFMSpeciesDM::mpTask private
Definition at line 58 of file CQEFMSpeciesDM.h.
Referenced by columnCount(), data(), rowCount(), and setTask().
size_t CQEFMSpeciesDM::mSpeciesSize private
Definition at line 65 of file CQEFMSpeciesDM.h.
Referenced by columnCount(), and setTask().
The documentation for this class was generated from the following files:
CQEFMSpeciesDM.h
CQEFMSpeciesDM.cpp