COPASI API: CQLyapWidget Class Reference
CQLyapWidget Class Reference
#include <CQLyapWidget.h>
Public Member Functions
CQLyapWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
~CQLyapWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void slotDelayChecked ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Member Functions
void init ()
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 26 of file CQLyapWidget.h.
Constructor & Destructor Documentation
CQLyapWidget::CQLyapWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 35 of file CQLyapWidget.cpp.
References init().
   : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQLyapWidget::~CQLyapWidget ()
Definition at line 46 of file CQLyapWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQLyapWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 69 of file CQLyapWidget.cpp.
References CLyapMethod::createMethod().
 {return CLyapMethod::createMethod(type);}
void CQLyapWidget::init () private
Definition at line 151 of file CQLyapWidget.cpp.
References TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, CQTaskHeaderWidget::setTaskName(), and CQTaskMethodWidget::showMethodParameters().
Referenced by CQLyapWidget().
 {
   mpHeaderWidget->setTaskName("Lyapunov Exponents");
   vboxLayout->insertWidget(0, mpHeaderWidget);  // header
   // vboxLayout->insertSpacing(1, 14);       // space between header and body
   mpMethodWidget->showMethodParameters(true);
   vboxLayout->addWidget(mpMethodWidget);
   vboxLayout->addWidget(mpBtnWidget);     // 'footer'
 }
bool CQLyapWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 72 of file CQLyapWidget.cpp.
References CLyapProblem::divergenceRequested(), CCopasiRootContainer::getDatamodelList(), CLyapProblem::getExponentNumber(), CCopasiTask::getProblem(), CLyapProblem::getTransientTime(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), TaskWidget::mChanged, TaskWidget::mpTask, and pTask.
 {
   CLyapTask * pTask = dynamic_cast< CLyapTask * >(mpTask);
   if (!pTask) return false;
   loadCommon();
   loadMethod();
   CLyapProblem* pProblem =
     dynamic_cast< CLyapProblem * >(mpTask->getProblem());
   if (!pProblem) return false;
   mpEditExponent->setText(QString::number(pProblem->getExponentNumber()));
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   bool enabled =
     ((*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getInitialTime() != pProblem->getTransientTime());
   mpCheckDelay->setChecked(enabled);
   mpEditDelay->setEnabled(enabled);
   mpEditDelay->setText(QString::number(pProblem->getTransientTime()));
   mpCheckDivergence->setChecked(pProblem->divergenceRequested());
   mChanged = false;
   return true;
 }
bool CQLyapWidget::runTask () virtual
Implements TaskWidget.
Definition at line 51 of file CQLyapWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CopasiWidget::mKey, and pTask.
 {
   CLyapTask * pTask =
     dynamic_cast< CLyapTask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!pTask) return false;
   if (!commonBeforeRunTask()) return false;
   return commonRunTask();
 }
bool CQLyapWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 103 of file CQLyapWidget.cpp.
References CLyapProblem::divergenceRequested(), CCopasiRootContainer::getDatamodelList(), CLyapProblem::getExponentNumber(), CCopasiTask::getProblem(), CLyapProblem::getTransientTime(), max, TaskWidget::mChanged, TaskWidget::mpTask, pTask, TaskWidget::saveCommon(), TaskWidget::saveMethod(), CLyapProblem::setDivergenceRequested(), CLyapProblem::setExponentNumber(), and CLyapProblem::setTransientTime().
 {
   CLyapTask * pTask = dynamic_cast< CLyapTask * >(mpTask);
   if (!pTask) return false;
   saveCommon();
   saveMethod();
   CLyapProblem* pProblem =
     dynamic_cast< CLyapProblem * >(mpTask->getProblem());
   if (!pProblem) return false;
   if (QString::number(pProblem->getExponentNumber()) != mpEditExponent->text())
     {
       pProblem->setExponentNumber(std::max(0, mpEditExponent->text().toInt()));
       mChanged = true;
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   bool enabled =
     ((*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getInitialTime() != pProblem->getTransientTime());
   if (mpCheckDelay->isChecked() != enabled ||
       (mpCheckDelay->isChecked() &&
        mpEditDelay->text() != QString::number(pProblem->getTransientTime())))
     {
       if (mpCheckDelay->isChecked())
         pProblem->setTransientTime(mpEditDelay->text().toDouble());
       else
         pProblem->setTransientTime((*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getInitialTime());
       mChanged = true;
     }
   if (mpCheckDivergence->isChecked() != pProblem->divergenceRequested())
     {
       pProblem->setDivergenceRequested(mpCheckDivergence->isChecked());
       mChanged = true;
     }
   if (mChanged)(*CCopasiRootContainer::getDatamodelList())[0]->changed();
   mChanged = false;
   return true;
 }
void CQLyapWidget::slotDelayChecked () protected slot
Definition at line 164 of file CQLyapWidget.cpp.
 {
   mpEditDelay->setEnabled(mpCheckDelay->isChecked());
 }
bool CQLyapWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 63 of file CQLyapWidget.cpp.
References CopasiWidget::mpListView, and ListViews::switchToOtherWidget().
 {
   mpListView->switchToOtherWidget(261, ""); //change to the results window
   return true;
 }
The documentation for this class was generated from the following files:
CQLyapWidget.h
CQLyapWidget.cpp