COPASI API: CFunctionAnalyzer::CValue Class Reference
CFunctionAnalyzer::CValue Class Reference
#include <CFunctionAnalyzer.h>
Public Types
enum Status {
novalue = 0, negative = 1, zero = 2, positive = 4,
invalid = 8, known = 16, unknown = 7
}
Public Member Functions
bool containsInvalid () const
bool containsNegative () const
bool containsPositive () const
bool containsZero () const
CValue ()
CValue (Status status)
CValue (const double &d)
const Status & getStatus () const
const double & getValue () const
CValue invert () const
bool isInvalid () const
bool isNegative () const
bool isPositive () const
bool isZero () const
CValue operator* (const CValue &rhs) const
CValue operator+ (const CValue &rhs) const
CValue operator- (const CValue &rhs) const
CValue operator/ (const CValue &rhs) const
bool operator== (const CValue &rhs) const
CValue operator^ (const CValue &rhs) const
void setStatus (const Status &status)
void setValue (const double &value)
Protected Member Functions
void Or (int s)
void Or (const CValue &v)
void orValue (const double &value)
Static Protected Member Functions
static CValue generalize (const double &d)
Private Attributes
double mDouble
Status mStatus
Friends
std::ostream & operator<< (std::ostream &os, const CValue &v)
Detailed Description
This is the base class of the arithmetics of the function analyzer. It describes possibilities for values. It basically consists of some flags that tell whether the value can be positive, can be negative, can be zero, or invalid, or if an actual exact numerical value is known. The usual arithmetic operators are defined for this class, the most important functions need to be implemented still. The missing functions are not critical since there is a save fallback: If you do not know how to perform a specific operation on CValues, the result should be (unknown|invalid).
Definition at line 55 of file CFunctionAnalyzer.h.
Member Enumeration Documentation
enum CFunctionAnalyzer::CValue::Status
Enumerator
novalue
negative
zero
positive
invalid
known
unknown
Definition at line 58 of file CFunctionAnalyzer.h.
     {
       novalue = 0,
       negative = 1,
       zero = 2,
       positive = 4,
       invalid = 8,
       known = 16,
       unknown = 7
     };
Constructor & Destructor Documentation
CFunctionAnalyzer::CValue::CValue () inline
Definition at line 69 of file CFunctionAnalyzer.h.
Referenced by orValue().
         : mStatus(Status(novalue)), mDouble(0.0) {};
CFunctionAnalyzer::CValue::CValue (Status status) inline
Definition at line 72 of file CFunctionAnalyzer.h.
         : mStatus(status), mDouble(0.0) {};
CFunctionAnalyzer::CValue::CValue (const double & d) inline
Definition at line 75 of file CFunctionAnalyzer.h.
         : mStatus(known), mDouble(d) {};
Member Function Documentation
bool CFunctionAnalyzer::CValue::containsInvalid () const
Definition at line 385 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus & invalid) return true;
   return false;
 }
bool CFunctionAnalyzer::CValue::containsNegative () const
Definition at line 369 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus & negative) return true;
   if ((mStatus & known) && (mDouble < 0.0)) return true;
   return false;
 }
bool CFunctionAnalyzer::CValue::containsPositive () const
Definition at line 333 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus & positive) return true;
   if ((mStatus & known) && (mDouble > 0.0)) return true;
   return false;
 }
bool CFunctionAnalyzer::CValue::containsZero () const
Definition at line 351 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus & zero) return true;
   if ((mStatus & known) && (mDouble == 0.0)) return true;
   return false;
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::generalize (const double & d) static protected
convert a CValue with status "known" to a more general status.
Definition at line 300 of file CFunctionAnalyzer.cpp.
Referenced by operator*().
 {
   if (d == 0.0) return zero;
   else if (d > 0.0) return positive;
   else if (d < 0.0) return negative;
   else return invalid;
 }
const Status& CFunctionAnalyzer::CValue::getStatus () const inline
Definition at line 85 of file CFunctionAnalyzer.h.
References mStatus.
Referenced by operator*(), operator+(), operator/(), and operator^().
 {return mStatus;};
const double& CFunctionAnalyzer::CValue::getValue () const inline
Definition at line 78 of file CFunctionAnalyzer.h.
References mDouble.
 {return mDouble;};
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::invert () const
Definition at line 187 of file CFunctionAnalyzer.cpp.
References mDouble, mStatus, and Or().
Referenced by operator-().
 {
   CValue ret;
   ret.mStatus = Status(this->mStatus & (zero | invalid | known));
   if (this->mStatus & known) ret.mDouble = -this->mDouble;
   if (this->mStatus & positive) ret.Or(negative);
   if (this->mStatus & negative) ret.Or(positive);
   return ret;
 }
bool CFunctionAnalyzer::CValue::isInvalid () const
Definition at line 378 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus == invalid) return true;
   return false;
 }
bool CFunctionAnalyzer::CValue::isNegative () const
Definition at line 360 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus == negative) return true;
   if ((mStatus == known) && (mDouble < 0.0)) return true;
   return false;
 }
bool CFunctionAnalyzer::CValue::isPositive () const
Definition at line 324 of file CFunctionAnalyzer.cpp.
Referenced by CEvaluationNode::findTopMinus().
 {
   if (mStatus == positive) return true;
   if ((mStatus == known) && (mDouble > 0.0)) return true;
   return false;
 }
bool CFunctionAnalyzer::CValue::isZero () const
Definition at line 342 of file CFunctionAnalyzer.cpp.
 {
   if (mStatus == zero) return true;
   if ((mStatus == known) && (mDouble == 0.0)) return true;
   return false;
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::operator* (const CValue & rhs) const
Definition at line 57 of file CFunctionAnalyzer.cpp.
References generalize(), getStatus(), invalid, known, mDouble, mStatus, negative, Or(), orValue(), positive, and zero.
 {
   CValue ret;
   //invalid
   if ((this->getStatus() & invalid) || (rhs.getStatus() & invalid))
     ret.Or(invalid);
   const CValue* v1, *v2;
   v1 = this; v2 = &rhs;
   if ((v1->mStatus & negative) && (v2->mStatus & negative)) ret.Or(positive);
   if ((v1->mStatus & negative) && (v2->mStatus & zero)) ret.Or(zero);
   if ((v1->mStatus & negative) && (v2->mStatus & positive)) ret.Or(negative);
   if ((v1->mStatus & zero) && (v2->mStatus & negative)) ret.Or(zero);
   if ((v1->mStatus & zero) && (v2->mStatus & zero)) ret.Or(zero);
   if ((v1->mStatus & zero) && (v2->mStatus & positive)) ret.Or(zero);
   if ((v1->mStatus & positive) && (v2->mStatus & negative)) ret.Or(negative);
   if ((v1->mStatus & positive) && (v2->mStatus & zero)) ret.Or(zero);
   if ((v1->mStatus & positive) && (v2->mStatus & positive)) ret.Or(positive);
   //known values
   if ((this->mStatus & known) && (rhs.mStatus & known))
     ret.orValue(this->mDouble * rhs.mDouble);
   else if (this->mStatus & known)
     ret.Or(generalize(this->mDouble) * rhs);
   else if (rhs.mStatus & known)
     ret.Or(*this * generalize(rhs.mDouble));
 #ifdef C_DBG_FA
   std::cout << "      *: " << *this << " * " << rhs << " = " << ret << std::endl;
 #endif
   return ret;
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::operator+ (const CValue & rhs) const
Definition at line 142 of file CFunctionAnalyzer.cpp.
References getStatus(), mDouble, mStatus, Or(), and orValue().
 {
   CValue ret;
   //invalid
   if ((this->getStatus() & invalid) || (rhs.getStatus() & invalid))
     ret.Or(invalid);
   //zero
   if (this->getStatus() & zero)
     ret.Or(rhs);
   if (rhs.getStatus() & zero)
     ret.Or(*this);
   //symmetry
   const CValue* v1, *v2;
   v1 = this; v2 = &rhs;
   if ((v1->mStatus & negative) && (v2->mStatus & negative)) ret.Or(negative);
   if ((v1->mStatus & negative) && (v2->mStatus & positive)) ret.Or(negative | zero | positive);
   if ((v1->mStatus & positive) && (v2->mStatus & negative)) ret.Or(negative | zero | positive);
   if ((v1->mStatus & positive) && (v2->mStatus & positive)) ret.Or(positive);
   //known values
   if ((this->mStatus & known) && (rhs.mStatus & known)) ret.orValue(this->mDouble + rhs.mDouble);
   if ((this->mStatus & negative) && (rhs.mStatus & known)) ret.Or(*this + generalize(rhs.mDouble));
   if ((this->mStatus & positive) && (rhs.mStatus & known)) ret.Or(*this + generalize(rhs.mDouble));
   if ((this->mStatus & known) && (rhs.mStatus & negative)) ret.Or(generalize(this->mDouble) + rhs);
   if ((this->mStatus & known) && (rhs.mStatus & positive)) ret.Or(generalize(this->mDouble) + rhs);
 #ifdef C_DBG_FA
   std::cout << "      +: " << *this << " + " << rhs << " = " << ret << std::endl;
 #endif
   return ret;
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::operator- (const CValue & rhs) const
Definition at line 201 of file CFunctionAnalyzer.cpp.
References invert().
 {
   return *this + rhs.invert();
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::operator/ (const CValue & rhs) const
Definition at line 101 of file CFunctionAnalyzer.cpp.
References getStatus(), mDouble, mStatus, Or(), and orValue().
 {
   CValue ret;
   //invalid
   if ((this->getStatus() & invalid) || (rhs.getStatus() & invalid))
     ret.Or(invalid);
   if (rhs.getStatus() & zero)
     ret.Or(invalid);
   const CValue* v1, *v2;
   v1 = this; v2 = &rhs;
   if ((v1->mStatus & negative) && (v2->mStatus & negative)) ret.Or(positive);
   if ((v1->mStatus & negative) && (v2->mStatus & positive)) ret.Or(negative);
   if ((v1->mStatus & zero) && (v2->mStatus & negative)) ret.Or(zero);
   if ((v1->mStatus & zero) && (v2->mStatus & positive)) ret.Or(zero);
   if ((v1->mStatus & positive) && (v2->mStatus & negative)) ret.Or(negative);
   if ((v1->mStatus & positive) && (v2->mStatus & positive)) ret.Or(positive);
   //known values
   if ((this->mStatus & known) && (rhs.mStatus & known))
     ret.orValue(this->mDouble / rhs.mDouble);
   else if (this->mStatus & known)
     ret.Or(generalize(this->mDouble) / rhs);
   else if (rhs.mStatus & known)
     ret.Or(*this / generalize(rhs.mDouble));
 #ifdef C_DBG_FA
   std::cout << "      /: " << *this << " / " << rhs << " = " << ret << std::endl;
 #endif
   return ret;
 }
bool CFunctionAnalyzer::CValue::operator== (const CValue & rhs) const
Definition at line 392 of file CFunctionAnalyzer.cpp.
References mDouble, and mStatus.
 {
   if (mStatus != rhs.mStatus) return false;
   if ((mStatus & known) && (mDouble != rhs.mDouble)) return false;
   return true;
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::CValue::operator^ (const CValue & rhs) const
Definition at line 206 of file CFunctionAnalyzer.cpp.
References getStatus(), mDouble, mStatus, Or(), and orValue().
 {
   CValue ret;
   //invalid
   if ((this->getStatus() & invalid) || (rhs.getStatus() & invalid))
     ret.Or(invalid);
   const CValue* v1, *v2;
   v1 = this; v2 = &rhs;
   if ((v1->mStatus & negative) && (v2->mStatus & negative)) ret.Or(negative | positive | invalid);
   if ((v1->mStatus & negative) && (v2->mStatus & zero)) ret.orValue(1.0);
   if ((v1->mStatus & negative) && (v2->mStatus & positive)) ret.Or(negative | positive | invalid);
   if ((v1->mStatus & zero) && (v2->mStatus & negative)) ret.Or(invalid);
   if ((v1->mStatus & zero) && (v2->mStatus & zero)) ret.Or(invalid);
   if ((v1->mStatus & zero) && (v2->mStatus & positive)) ret.Or(zero);
   if ((v1->mStatus & positive) && (v2->mStatus & negative)) ret.Or(positive);
   if ((v1->mStatus & positive) && (v2->mStatus & zero)) ret.orValue(1.0);
   if ((v1->mStatus & positive) && (v2->mStatus & positive)) ret.Or(positive);
   //known values
   //base and exponent are known
   if ((this->mStatus & known) && (rhs.mStatus & known)) ret.orValue(pow(this->mDouble, rhs.mDouble));
   //base is known
   if ((this->mStatus & known) && ((rhs.mStatus & negative)
                                   || (rhs.mStatus & zero)
                                   || (rhs.mStatus & positive)))
     {
       if (this->mDouble == 1.0) // base is 1
         ret.orValue(1.0);
       else
         ret.Or(generalize(this->mDouble) ^ rhs);
     }
   //exponent is known
   if (((this->mStatus & negative)
        || (this->mStatus & zero)
        || (this->mStatus & positive)) && (rhs.mStatus & known))
     {
       if ((rhs.mDouble == trunc(rhs.mDouble)) && (rhs.mDouble != 0.0)) //exponent is integer but not 0
         {
           if (rhs.mDouble / 2.0 == trunc(rhs.mDouble / 2.0)) //exponent is even
             {
               if (this->mStatus & negative) ret.Or(positive);
               if (this->mStatus & zero) ret.Or(zero);
               if (this->mStatus & positive) ret.Or(positive);
             }
           else //uneven
             {
               if (this->mStatus & negative) ret.Or(negative);
               if (this->mStatus & zero) ret.Or(zero);
               if (this->mStatus & positive) ret.Or(positive);
             }
         }
       else
         ret.Or(*this ^ generalize(rhs.mDouble));
     }
 #ifdef C_DBG_FA
   std::cout << "      ^: " << *this << " ^ " << rhs << " = " << ret << std::endl;
 #endif
   return ret;
 }
void CFunctionAnalyzer::CValue::Or (int s) inline protected
Definition at line 116 of file CFunctionAnalyzer.h.
References mStatus.
Referenced by invert(), operator*(), operator+(), operator/(), operator^(), Or(), and orValue().
 {mStatus = Status(mStatus | s);};
void CFunctionAnalyzer::CValue::Or (const CValue & v) protected
Definition at line 308 of file CFunctionAnalyzer.cpp.
References mDouble, mStatus, and Or().
 {
   if ((this->mStatus & known) && (v.mStatus & known) && (this->mDouble != v.mDouble))
     {
       //the two CValues have different known values
       CValue tmp = generalize(this->mDouble);
       tmp.Or(generalize(v.mDouble));
       *this = tmp;
       return;
     }
   Or(v.mStatus);
   if (v.mStatus & known) this->mDouble = v.mDouble;
 }
void CFunctionAnalyzer::CValue::orValue (const double & value) inline protected
add the value to the set off possible values
Definition at line 125 of file CFunctionAnalyzer.h.
References CValue(), and Or().
Referenced by operator*(), operator+(), operator/(), and operator^().
 {Or(CValue(value)); /*  mDouble = value; Or(known);*/};
void CFunctionAnalyzer::CValue::setStatus (const Status & status) inline
Definition at line 87 of file CFunctionAnalyzer.h.
References mStatus.
 {mStatus = status;};
void CFunctionAnalyzer::CValue::setValue (const double & value) inline
set value to be the only possible value
Definition at line 83 of file CFunctionAnalyzer.h.
References known, mDouble, and mStatus.
 {mDouble = value; mStatus = known;};
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CValue & v) friend
insert operator
Definition at line 38 of file CFunctionAnalyzer.cpp.
 {
   os << "{";
   if (v.mStatus & CFunctionAnalyzer::CValue::negative) os << "- ";
   if (v.mStatus & CFunctionAnalyzer::CValue::zero) os << "0 ";
   if (v.mStatus & CFunctionAnalyzer::CValue::positive) os << "+ ";
   if (v.mStatus & CFunctionAnalyzer::CValue::invalid) os << "E ";
   if (v.mStatus & CFunctionAnalyzer::CValue::known) os << "v" << v.mDouble << " ";
   os << "}";
   return os;
 }
Member Data Documentation
double CFunctionAnalyzer::CValue::mDouble private
Definition at line 130 of file CFunctionAnalyzer.h.
Referenced by getValue(), invert(), operator*(), operator+(), operator/(), operator<<(), operator==(), operator^(), Or(), and setValue().
Status CFunctionAnalyzer::CValue::mStatus private
Definition at line 125 of file CFunctionAnalyzer.h.
Referenced by getStatus(), invert(), operator*(), operator+(), operator/(), operator<<(), operator==(), operator^(), Or(), setStatus(), and setValue().
The documentation for this class was generated from the following files:
CFunctionAnalyzer.h
CFunctionAnalyzer.cpp