COPASI API: CBitPatternTree Class Reference
CBitPatternTree Class Reference
#include <CBitPatternTree.h>
Public Member Functions
CBitPatternTree (const std::vector< CStepMatrixColumn * > &patterns)
const CBitPatternTreeNode * getRoot () const
bool isExtremeRay (const CZeroSet &ray) const
size_t size () const
~CBitPatternTree ()
Private Member Functions
CBitPatternTree ()
Private Attributes
CBitPatternTreeNode * mpRoot
Detailed Description
Definition at line 20 of file CBitPatternTree.h.
Constructor & Destructor Documentation
CBitPatternTree::CBitPatternTree () private
Definition at line 18 of file CBitPatternTree.cpp.
                                 :
     mpRoot(NULL)
 {}
CBitPatternTree::CBitPatternTree (const std::vector< CStepMatrixColumn * > & patterns)
Definition at line 22 of file CBitPatternTree.cpp.
References mpRoot.
                                                                                  :
     mpRoot(NULL)
 {
   if (!patterns.empty())
     {
       mpRoot = new CBitPatternTreeNode(0, patterns);
     }
 }
CBitPatternTree::~CBitPatternTree ()
Definition at line 31 of file CBitPatternTree.cpp.
References mpRoot, and pdelete.
 {
   pdelete(mpRoot);
 }
Member Function Documentation
const CBitPatternTreeNode * CBitPatternTree::getRoot () const
Definition at line 36 of file CBitPatternTree.cpp.
References mpRoot.
Referenced by CBitPatternTreeMethod::calculate().
 {
   return mpRoot;
 }
bool CBitPatternTree::isExtremeRay (const CZeroSet & ray) const
Definition at line 41 of file CBitPatternTree.cpp.
References CBitPatternTreeNode::hasSuperset(), and mpRoot.
Referenced by CBitPatternTreeMethod::combine(), and CBitPatternTreeMethod::findRemoveInvalidColumns().
 {
   if (mpRoot != NULL)
     {
       return !mpRoot->hasSuperset(set);
     }
   return true;
 }
size_t CBitPatternTree::size () const
Definition at line 51 of file CBitPatternTree.cpp.
References CBitPatternTreeNode::getChildrenCount(), and mpRoot.
Referenced by CBitPatternTreeMethod::calculate().
 {
   if (mpRoot != NULL)
     {
       return mpRoot->getChildrenCount();
     }
   return 0;
 }
Member Data Documentation
CBitPatternTreeNode* CBitPatternTree::mpRoot private
Definition at line 39 of file CBitPatternTree.h.
Referenced by CBitPatternTree(), getRoot(), isExtremeRay(), size(), and ~CBitPatternTree().
The documentation for this class was generated from the following files:
CBitPatternTree.h
CBitPatternTree.cpp