COPASI API: CSteadyStateTask.cpp File Reference
CSteadyStateTask.cpp File Reference
#include "copasi.h"
#include "CSteadyStateTask.h"
#include "CSteadyStateProblem.h"
#include "CSteadyStateMethod.h"
#include "model/CModel.h"
#include "model/CState.h"
#include "model/CMetabNameInterface.h"
#include "report/CKeyFactory.h"
#include "report/CReport.h"
#include <sstream>
Macros
#define XXXX_Reporting
Functions
std::ostream & operator<< (std::ostream &os, const CSteadyStateTask &A)
Macro Definition Documentation
#define XXXX_Reporting
CSteadyStateTask class.
This class implements a steady state task which is comprised of a of a problem and a method. Additionally calls to the reporting methods are done when initialized.
Created for COPASI by Stefan Hoops 2002
Definition at line 38 of file CSteadyStateTask.cpp.
Function Documentation
std::ostream& operator<< (std::ostream & os, const CSteadyStateTask & A)
Definition at line 439 of file CSteadyStateTask.cpp.
References CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, CMetab::getConcentration(), CMetab::getConcentrationRate(), CModel::getConcentrationRateUnitsDisplayString(), CModel::getConcentrationUnitsDisplayString(), CMetabNameInterface::getDisplayName(), CReaction::getFlux(), CModel::getFrequencyUnitsDisplayString(), CEigen::getI(), CModel::getMetabolites(), CCopasiProblem::getModel(), CCopasiObject::getObjectName(), CReaction::getParticleFlux(), CModel::getQuantityRateUnitsDisplayString(), CEigen::getR(), CModelEntity::getRate(), CModel::getReactions(), CSteadyStateTask::getResult(), CSteadyStateTask::getState(), CModel::getTimeUnitsDisplayString(), CMetab::getTransitionTime(), CModelEntity::getValue(), CSteadyStateTask::mEigenValues, CSteadyStateTask::mEigenValuesX, CSteadyStateTask::mpJacobianAnn, CSteadyStateTask::mpJacobianXAnn, CCopasiTask::mpProblem, CSteadyStateMethod::notFound, CModel::setState(), CVectorCore< CType >::size(), CCopasiVector< T >::size(), CModel::updateNonSimulatedValues(), and CModel::updateSimulatedValues().
 {
   switch (A.getResult())
     {
       case CSteadyStateMethod::found:
         os << "A steady state with given resolution was found." << std::endl;
         break;
       case CSteadyStateMethod::notFound:
         os << "No steady state with given resolution was found!" << std::endl;
         os << "(below are the last unsuccessful trial values)" << std::endl;
         break;
       case CSteadyStateMethod::foundEquilibrium:
         os << "An equilibrium steady state (zero fluxes) was found." << std::endl;
         break;
       case CSteadyStateMethod::foundNegative:
         os << "An invalid steady state (negative concentrations) was found." << std::endl;
     }
   os << std::endl;
   // Update all necessary values.
   CState * pState = const_cast<CState *>(A.getState());
   if (!pState) return os;
   CModel * pModel = A.mpProblem->getModel();
   if (!pModel) return os;
   pModel->setState(*pState);
   pModel->updateSimulatedValues(true);
   pModel->updateNonSimulatedValues();
   // Metabolite Info: Name, Concentration, Concentration Rate, Particle Number, Particle Rate, Transition Time
   const CCopasiVector<CMetab> & Metabolites = pModel->getMetabolites();
   const CMetab * pMetab;
   size_t i, imax = Metabolites.size();
   os << "Species" << "\t";
   os << "Concentration";
   std::string Units = pModel->getConcentrationUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Concentration Rate";
   Units = pModel->getConcentrationRateUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Particle Number" << "\t";
   os << "Particle Number Rate";
   Units = pModel->getFrequencyUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Transition Time";
   Units = pModel->getTimeUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << std::endl;
   for (i = 0; i < imax; ++i)
     {
       pMetab = Metabolites[i];
       os << CMetabNameInterface::getDisplayName(pModel, *pMetab, false) << "\t";
       os << pMetab->getConcentration() << "\t";
       os << pMetab->getConcentrationRate() << "\t";
       os << pMetab->getValue() << "\t";
       os << pMetab->getRate() << "\t";
       os << pMetab->getTransitionTime() << std::endl;
     }
   os << std::endl;
   // Reaction Info: Name, Flux, Particle Flux
   const CCopasiVector<CReaction>& Reactions = pModel->getReactions();
   const CReaction * pReaction;
   imax = Reactions.size();
   os << "Reaction" << "\t";
   os << "Flux";
   Units = pModel->getQuantityRateUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Particle Flux";
   Units = pModel->getFrequencyUnitsDisplayString();;
   if (Units != "")
     os << " (" << Units << ")";
   os << std::endl;
   for (i = 0; i < imax; ++i)
     {
       pReaction = Reactions[i];
       os << pReaction->getObjectName() << "\t";
       os << pReaction->getFlux() << "\t";
       os << pReaction->getParticleFlux() << std::endl;
     }
   os << std::endl;
   if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isJacobianRequested())
     {
       os << *A.mpJacobianAnn << std::endl;
       if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isStabilityAnalysisRequested())
         {
           os << "Eigenvalues\treal\timaginary" << std::endl;
           imax = A.mEigenValues.getR().size();
           for (i = 0; i < imax; i++)
             os << "\t" << A.mEigenValues.getR()[i] << "\t" << A.mEigenValues.getI()[i] << std::endl;
           os << std::endl;
         }
       os << *A.mpJacobianXAnn << std::endl;
       if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isStabilityAnalysisRequested())
         {
           os << "Eigenvalues\treal\timaginary" << std::endl;
           imax = A.mEigenValuesX.getR().size();
           for (i = 0; i < imax; i++)
             os << "\t" << A.mEigenValuesX.getR()[i] << "\t" << A.mEigenValuesX.getI()[i] << std::endl;
           os << std::endl;
         }
     }
   if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isStabilityAnalysisRequested())
     {
       os << "Stability Analysis of the Reduced System" << std::endl;
       os << A.mEigenValuesX << std::endl;
     }
   return os;
 }