COPASI API: CMiaseML Class Reference
CMiaseML Class Reference
#include <CMiaseML.h>
Public Member Functions
CMiaseML ()
CMiaseSed * getSed ()
std::string getVersion ()
std::string getXmlns ()
void setMiaseSed (CMiaseSed *sed)
void setVersion (std::string version)
void setXmlns (std::string xmlns)
~CMiaseML ()
Public Member Functions inherited from CMiaseBase
void addAnnotation (CMiaseAnnotation *ann)
void addNotes (CMiaseNotes *notes)
CMiaseBase ()
CMiaseAnnotation * getAnnotation ()
std::string getMetaId ()
CMiaseNotes * getNotes ()
void setAnyNote (std::string anyAnnotation)
void setMetaId (std::string metaId)
void setXmlNs (std::string xmlNs)
~CMiaseBase ()
Private Attributes
CMiaseSed * mSed
std::string mVersion
std::string mXmlns
Detailed Description
Definition at line 64 of file CMiaseML.h.
Constructor & Destructor Documentation
CMiaseML::CMiaseML ()
Definition at line 157 of file CMiaseML.cpp.
                    : CMiaseBase()
 {}
CMiaseML::~CMiaseML ()
Definition at line 160 of file CMiaseML.cpp.
 {}
Member Function Documentation
CMiaseSed * CMiaseML::getSed ()
Definition at line 168 of file CMiaseML.cpp.
References mSed.
Referenced by CMiaseParser::endElement(), CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newChange(), CMiaseParser::newMeasurementData(), CMiaseParser::newModel(), CMiaseParser::newNotes(), CMiaseParser::newOutput(), CMiaseParser::newSimulation(), CMiaseParser::newTask(), and CMiaseParser::testDataStructure().
 {
   return mSed;
 }
std::string CMiaseML::getVersion ()
Definition at line 178 of file CMiaseML.cpp.
References mVersion.
 {
   return mVersion;
 }
std::string CMiaseML::getXmlns ()
Definition at line 173 of file CMiaseML.cpp.
References mXmlns.
 {
   return mXmlns;
 }
void CMiaseML::setMiaseSed (CMiaseSed * sed)
Definition at line 163 of file CMiaseML.cpp.
References mSed.
Referenced by CMiaseParser::startElement().
 {
   mSed = sed;
 }
void CMiaseML::setVersion (std::string version)
Definition at line 188 of file CMiaseML.cpp.
References mVersion.
Referenced by CMiaseParser::newMiase().
 {
   mVersion = version;
 }
void CMiaseML::setXmlns (std::string xmlns)
Definition at line 183 of file CMiaseML.cpp.
References mXmlns.
Referenced by CMiaseParser::newMiase().
 {
   mXmlns = xmlns;
 }
Member Data Documentation
CMiaseSed* CMiaseML::mSed private
Definition at line 84 of file CMiaseML.h.
Referenced by getSed(), and setMiaseSed().
std::string CMiaseML::mVersion private
Definition at line 87 of file CMiaseML.h.
Referenced by getVersion(), and setVersion().
std::string CMiaseML::mXmlns private
Definition at line 86 of file CMiaseML.h.
Referenced by getXmlns(), and setXmlns().
The documentation for this class was generated from the following files:
CMiaseML.h
CMiaseML.cpp