COPASI API: CLTransformation2D Class Reference
CLTransformation2D Class Reference
#include <CLTransformation2D.h>
Public Member Functions
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Static Public Member Functions
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Attributes
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Member Functions
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Attributes
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Detailed Description
Definition at line 21 of file CLTransformation2D.h.
Constructor & Destructor Documentation
CLTransformation2D::CLTransformation2D ()
Constructor.
Definition at line 25 of file CLTransformation2D.cpp.
References CLTransformation::IDENTITY3D, CLTransformation::mMatrix, and updateMatrix2D().
                                       : CLTransformation()
 {
   unsigned int i;
   for (i = 0; i < 12; ++i)
     {
       mMatrix[i] = IDENTITY3D[i];
     }
   this->updateMatrix2D();
 }
CLTransformation2D::CLTransformation2D (const double matrix[6])
Constructor with a matrix.
Constructor with values for the matrix.
Definition at line 40 of file CLTransformation2D.cpp.
References setMatrix2D().
                                                             : CLTransformation()
 {
   this->setMatrix2D(matrix);
 }
CLTransformation2D::CLTransformation2D (const Transformation2D & source)
Constructor to generate object from the corresponding SBML object.
Definition at line 48 of file CLTransformation2D.cpp.
References setMatrix2D(), and updateMatrix2D().
                                                                     :
     CLTransformation()
 {
   if (source.isSetMatrix())
     {
       this->setMatrix2D(source.getMatrix2D());
     }
   else
     {
       this->updateMatrix2D();
     }
 }
Member Function Documentation
void CLTransformation2D::addSBMLAttributes (Transformation2D * pTransformation) const protected virtual
Adds the attributes for a 2d transformation object to the passed in. object.
Definition at line 189 of file CLTransformation2D.cpp.
References mMatrix2D.
Referenced by CLGraphicalPrimitive1D::addSBMLAttributes(), and CLImage::toSBML().
 {
   pTransformation->setMatrix2D(this->mMatrix2D);
 }
std::string CLTransformation2D::get2DTransformationString () const
Returns a string to represent the 2D transformation.
Definition at line 96 of file CLTransformation2D.cpp.
References mMatrix2D.
Referenced by CCopasiXML::saveTransformationAttributes().
 {
   // transform the matrix to a string
   std::ostringstream os;
   unsigned int i;
   os << mMatrix2D[0];
   for (i = 1; i < 6; ++i)
     {
       os << "," << mMatrix2D[i];
     }
   return os.str();
 }
const double * CLTransformation2D::getIdentityMatrix2D () static
Returns a 2D identity matrix. The matrix contains 6 values.
Definition at line 89 of file CLTransformation2D.cpp.
References IDENTITY2D.
 {
   return IDENTITY2D;
 }
const double * CLTransformation2D::getMatrix2D () const
Returns the matrix. The matrix contains 6 values.
Definition at line 80 of file CLTransformation2D.cpp.
References mMatrix2D.
Referenced by transform().
 {
   return mMatrix2D;
 }
void CLTransformation2D::parseTransformation (const std::string & transformationString) virtual
Sets the transformation matrix from the given string. The string has to contain either 6 or 12 numerical values seperated by ",". Otherwise the matrix is set to the identity matrix.
Reimplemented from CLTransformation.
Definition at line 149 of file CLTransformation2D.cpp.
References mMatrix2D, CLTransformation::parseTransformation(), updateMatrix2D(), and updateMatrix3D().
Referenced by CCopasiXMLParser::ImageElement::start(), CCopasiXMLParser::RectangleElement::start(), CCopasiXMLParser::EllipseElement::start(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), and CCopasiXMLParser::GroupElement::start().
 {
   // the string should contain a list of 6 komma seperated numbers
   // if it doesn't, we try to set the 3D matrix
   bool result = true;
   std::string delimiter = ",";
   std::size_t lastPos = transformationString.find_first_not_of(delimiter);
   std::size_t pos;
   unsigned int index = 0;
   while (lastPos != std::string::npos)
     {
       if (index > 5)
         {
           result = false;
           break;
         }
       pos = transformationString.find_first_of(delimiter, lastPos);
       double value = strtod(transformationString.substr(lastPos, pos - lastPos).c_str(), NULL);
       mMatrix2D[index] = value;
       index++;
       lastPos = transformationString.find_first_not_of(delimiter, pos);
     }
   if (!result || index != 6)
     {
       this->CLTransformation::parseTransformation(transformationString);
       this->updateMatrix2D();
     }
   else
     {
       this->updateMatrix3D();
     }
 }
void CLTransformation2D::setMatrix (const double m[12])
Sets the 3D matrix. The 2D matrix is updated accordingly.
Definition at line 143 of file CLTransformation2D.cpp.
References CLTransformation::setMatrix(), and updateMatrix2D().
 {
   this->CLTransformation::setMatrix(m);
   this->updateMatrix2D();
 }
void CLTransformation2D::setMatrix2D (const double m[6])
Sets the 2D matrix. The 3D matrix is updated accordingly.
Sets the matrix.
Definition at line 64 of file CLTransformation2D.cpp.
References mMatrix2D, and updateMatrix3D().
Referenced by CLTransformation2D().
 {
   unsigned int i;
   for (i = 0; i < 6; ++i)
     {
       mMatrix2D[i] = m[i];
     }
   this->updateMatrix3D();
 }
void CLTransformation2D::updateMatrix2D () protected
Fills the 2D matrix with data from the 3D matrix.
Definition at line 133 of file CLTransformation2D.cpp.
References CLTransformation::mMatrix, and mMatrix2D.
Referenced by CLTransformation2D(), parseTransformation(), and setMatrix().
 {
   mMatrix2D[0] = mMatrix[0];
   mMatrix2D[1] = mMatrix[1];
   mMatrix2D[2] = mMatrix[3];
   mMatrix2D[3] = mMatrix[4];
   mMatrix2D[4] = mMatrix[9];
   mMatrix2D[5] = mMatrix[10];
 }
void CLTransformation2D::updateMatrix3D () protected
Sets the 3D matrix from the 2D matrix.
Definition at line 114 of file CLTransformation2D.cpp.
References CLTransformation::mMatrix, and mMatrix2D.
Referenced by parseTransformation(), and setMatrix2D().
 {
   mMatrix[0] = mMatrix2D[0];
   mMatrix[1] = mMatrix2D[1];
   mMatrix[2] = 0.0;
   mMatrix[3] = mMatrix2D[2];
   mMatrix[4] = mMatrix2D[3];
   mMatrix[5] = 0.0;
   mMatrix[6] = 0.0;
   mMatrix[7] = 0.0;
   mMatrix[8] = 1.0;
   mMatrix[9] = mMatrix2D[4];
   mMatrix[10] = mMatrix2D[5];
   mMatrix[11] = 0.0;
 }
Member Data Documentation
const double CLTransformation2D::IDENTITY2D = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0} static
Definition at line 24 of file CLTransformation2D.h.
Referenced by getIdentityMatrix2D().
double CLTransformation2D::mMatrix2D[6] protected
the 2D matrix.
Definition at line 92 of file CLTransformation2D.h.
Referenced by addSBMLAttributes(), get2DTransformationString(), getMatrix2D(), parseTransformation(), setMatrix2D(), updateMatrix2D(), and updateMatrix3D().
The documentation for this class was generated from the following files:
CLTransformation2D.h
CLTransformation2D.cpp