COPASI API: CQReportDefinition Class Reference
CQReportDefinition Class Reference
#include <CQReportDefinition.h>
Public Member Functions
CQReportDefinition (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQReportDefinition ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void btnAdvancedClicked ()
void btnCommitClicked ()
void btnCopyReportClicked ()
void btnDeleteClicked ()
void btnDeleteReportClicked ()
void btnDownClicked ()
void btnItemClicked ()
void btnNewReportClicked ()
void btnRevertClicked ()
void btnSeparatorClicked ()
void btnTextClicked ()
void btnUpClicked ()
void chkTabClicked ()
void chkTitleClicked ()
void commentChanged ()
void nameChanged (const QString &string)
void precisionChanged (const QString &string)
void separatorChanged (const QString &string)
void taskChanged (const QString &string)
Private Member Functions
bool load ()
bool save ()
bool setAdvancedMode (const bool &advanced)
Private Attributes
bool mAdvanced
bool mChanged
QString mOldComment
CReportDefinition * mpReportDefinition
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 28 of file CQReportDefinition.h.
Constructor & Destructor Documentation
CQReportDefinition::CQReportDefinition (QWidget * parent = 0, const char * name = 0)
Definition at line 34 of file CQReportDefinition.cpp.
References C_INT32, FROM_UTF8, CopasiWidget::mKey, mpReportDefinition, setAdvancedMode(), and CCopasiTask::TypeName.
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   mKey = "";
   mpReportDefinition = NULL;
   // We start with the table since this is simpler.
   setAdvancedMode(false);
   unsigned C_INT32 i;
   QStringList TaskNames;
   for (i = 0; CCopasiTask::TypeName[i] != ""; i++)
     {
       TaskNames.append(FROM_UTF8(CCopasiTask::TypeName[i]));
     }
   mpTaskBox->addItems(TaskNames);
 }
CQReportDefinition::~CQReportDefinition ()
Definition at line 60 of file CQReportDefinition.cpp.
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQReportDefinition::btnAdvancedClicked () private slot
Definition at line 91 of file CQReportDefinition.cpp.
References C_INT32, load(), mAdvanced, mChanged, CopasiWidget::mpDataModel, mpReportDefinition, CReportDefinition::preCompileTable(), CQMessageBox::question(), save(), setAdvancedMode(), CReportDefinition::setIsTable(), and TO_UTF8.
 {
   if (mAdvanced)
     {
       if (CQMessageBox::question(NULL, "Report Conversion",
                                  "Converting an advanced report to a table may result in loss of customization.\n"
                                  "Do you want to proceed?",
                                  QMessageBox::Ok | QMessageBox::Cancel,
                                  QMessageBox::Cancel) == QMessageBox::Ok)
         {
           // We convert the body without the separators to a table.
           mpTableList->clear();
           unsigned C_INT32 i, imax;
           for (i = 0, imax = mpBodyList->count(); i < imax; i++)
             if (static_cast<CQReportListItem *>(mpBodyList->item(i))->getCN().getObjectType()
                 != "Separator")
               new CQReportListItem(static_cast<CQReportListItem *>(mpBodyList->item(i))->getCN());
           mpHeaderList->clear();
           mpBodyList->clear();
           mpFooterList->clear();
           setAdvancedMode(false);
           mChanged = true;
         }
     }
   else
     {
       // To achieve the same result as with the table we use the preCompileTable
       // method of CReportDefinition. Since we must not change the existing report,
       // which may only be done by btnCommitClicked or leave, we create a temporary
       // copy.
       CReportDefinition * pStore = mpReportDefinition;
       // We avoid the renaming signal.
       mpReportDefinition = new CReportDefinition(TO_UTF8(mpName->text()), mpDataModel);
       mChanged = true;
       save();
       mpReportDefinition->preCompileTable();
       mpReportDefinition->setIsTable(false);
       load();
       delete mpReportDefinition;
       mpReportDefinition = pStore;
       mChanged = true;
     }
 }
void CQReportDefinition::btnCommitClicked () private slot
Definition at line 467 of file CQReportDefinition.cpp.
References save().
Referenced by btnCopyReportClicked(), and btnNewReportClicked().
 {save();}
void CQReportDefinition::btnCopyReportClicked () private slot
Definition at line 408 of file CQReportDefinition.cpp.
References ListViews::ADD, CCopasiVectorN< CType >::add(), btnCommitClicked(), C_INVALID_INDEX, CopasiWidget::enter(), CCopasiVectorN< CType >::getIndex(), CReportDefinition::getKey(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectName(), CCopasiDataModel::getReportDefinitionList(), CopasiWidget::mKey, CopasiWidget::mpListView, CopasiWidget::mpObject, CopasiWidget::protectedNotify(), ListViews::REPORT, CCopasiObject::setObjectName(), ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   btnCommitClicked();
   CCopasiDataModel* pDataModel = mpObject->getObjectDataModel();
   if (pDataModel == NULL) return;
   CReportDefinition * pRep = new CReportDefinition(*dynamic_cast<CReportDefinition*>(CCopasiRootContainer::getKeyFactory()->get(mKey)));
   std::string baseName = pRep->getObjectName() + "_copy";
   std::string name = baseName;
   int i =1;
   while (pDataModel->getReportDefinitionList()->getIndex(name) != C_INVALID_INDEX)
     {
       i++;
       name = baseName + TO_UTF8(QString::number(i));
     }
   pRep->setObjectName(name);
   pDataModel->getReportDefinitionList()->add(pRep, true);
   std::string key = pRep->getKey();
   protectedNotify(ListViews::REPORT, ListViews::ADD, key);
   enter(key);
   mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQReportDefinition::btnDeleteClicked () private slot
Definition at line 213 of file CQReportDefinition.cpp.
References mChanged.
 {
   QListWidget * pList = static_cast< QListWidget * >(mpReportSectionTab->currentWidget());
   QListWidgetItem * pNewSelection = NULL;
   int i, multipleSelection;
   for (i = pList->count() - 1, multipleSelection = 0; 0 <= i; i--)
     if (pList->item(i)->isSelected())
       {
         delete pList->takeItem(i);
         if (!pNewSelection && i < pList->count())
           {
             pNewSelection = pList->item(i); // We select the next.
           }
         multipleSelection++;
       }
   if (multipleSelection == 0) return; // Nothing selected,
   mChanged = true;
   pList->clearSelection();
   if (multipleSelection > 1) return;
   // Only one item was select and we move the selection to the next
   if (!pNewSelection && pList->count()) // We have removed item at the end.
     pNewSelection = pList->item(pList->count() - 1);
   // pNewSelection is NULL if the list is empty
   if (pNewSelection)
     {
       pNewSelection->setSelected(true);
     }
   return;
 }
void CQReportDefinition::btnDeleteReportClicked () private slot
Definition at line 329 of file CQReportDefinition.cpp.
References CCopasiDataModel::appendDependentTasks(), CQMessageBox::confirmDelete(), ListViews::DELETE, CopasiWidget::enter(), FROM_UTF8, CCopasiVector< T >::getIndex(), CCopasiObject::getKey(), CCopasiObject::getObjectName(), CCopasiDataModel::getReportDefinitionList(), min, CopasiWidget::mpDataModel, CopasiWidget::mpObject, CopasiWidget::protectedNotify(), pTask, CCopasiVector< T >::remove(), ListViews::REPORT, and CCopasiVector< T >::size().
 {
   if (mpDataModel == NULL)
     return;
   std::set< const CCopasiObject * > Tasks;
   std::set< const CCopasiObject * > DeletedObjects;
   DeletedObjects.insert(mpObject);
   QMessageBox::StandardButton choice =
     CQMessageBox::confirmDelete(this, "report",
                                 FROM_UTF8(mpObject->getObjectName()),
                                 DeletedObjects);
   switch (choice)
     {
       case QMessageBox::Ok:
       {
         CCopasiVector< CReportDefinition > * pReportList = mpDataModel->getReportDefinitionList();
         if (pReportList == NULL)
           return;
         if (mpDataModel->appendDependentTasks(DeletedObjects, Tasks))
           {
             std::set< const CCopasiObject * >::iterator it = Tasks.begin();
             std::set< const CCopasiObject * >::iterator end = Tasks.end();
             for (; it != end; ++it)
               {
                 const CCopasiTask * pTask = static_cast< const CCopasiTask *>(*it);
                 const_cast< CCopasiTask * >(pTask)->getReport().setReportDefinition(NULL);
               }
           }
         size_t Index = pReportList->getIndex(mpObject);
         std::string DeletedKey = mpObject->getKey();
         pReportList->remove(Index);
         size_t Size = pReportList->size();
         if (Size > 0)
           enter((*pReportList)[std::min(Index, Size - 1)]->getKey());
         else
           enter("");
         protectedNotify(ListViews::REPORT, ListViews::DELETE, DeletedKey);
         break;
       }
       default:
         break;
     }
 }
void CQReportDefinition::btnDownClicked () private slot
Definition at line 291 of file CQReportDefinition.cpp.
References mChanged.
 {
   QListWidget * pList = static_cast< QListWidget * >(mpReportSectionTab->currentWidget());
   int i, imax, to, multipleSelection;
   QListWidgetItem * pMove;
   // Find the index of the first selected item.
   for (i = 0, imax = pList->count(), to = -1, multipleSelection = 0; i < imax; i++)
     if (pList->item(i)->isSelected())
       {
         if (multipleSelection == 0) to = i;
         multipleSelection++;
       }
     else if (multipleSelection > 0)
       {
         pMove = pList->takeItem(i);
         if (pMove)
           {
             pList->insertItem(to, pMove);
             multipleSelection = 0;
             mChanged = true;
           }
       }
   // Unselect things we can not move.
   for (i = pList->count() - multipleSelection, imax = pList->count(); i < imax; i++)
     pList->item(i)->setSelected(false);
   return;
 }
void CQReportDefinition::btnItemClicked () private slot
Definition at line 147 of file CQReportDefinition.cpp.
References CQSimpleSelectionTree::AnyObject, CCopasiRootContainer::getDatamodelList(), CCopasiSelectionDialog::getObjectVector(), and mChanged.
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel* pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   if (!pModel) return;
   std::vector< const CCopasiObject * > SelectedVector =
     //    CCopasiSelectionDialog::getObjectVector(this, CQSimpleSelectionTree::NO_RESTRICTION);
     CCopasiSelectionDialog::getObjectVector(this, CQSimpleSelectionTree::AnyObject);
   CQReportListItem * pItem;
   if (SelectedVector.size() != 0)
     {
       QListWidget * pList = static_cast< QListWidget * >(mpReportSectionTab->currentWidget());
       std::vector< const CCopasiObject * >::const_iterator it = SelectedVector.begin();
       std::vector< const CCopasiObject * >::const_iterator end = SelectedVector.end();
       for (; it != end; ++it)
         {
           pItem = new CQReportListItem(*it);
           pList->addItem(pItem);
         }
       mChanged = true;
     }
   return;
 }
void CQReportDefinition::btnNewReportClicked () private slot
Definition at line 385 of file CQReportDefinition.cpp.
References ListViews::ADD, btnCommitClicked(), C_INVALID_INDEX, CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), CReportDefinition::getKey(), CopasiWidget::mpListView, CopasiWidget::protectedNotify(), ListViews::REPORT, ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   btnCommitClicked();
   std::string Name = "report";
   int i = 0;
   CReportDefinition* pRep;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   while (!(pRep = (*CCopasiRootContainer::getDatamodelList())[0]->getReportDefinitionList()->createReportDefinition(Name, "")))
     {
       i++;
       Name = "report_";
       Name += TO_UTF8(QString::number(i));
     }
   std::string key = pRep->getKey();
   protectedNotify(ListViews::REPORT, ListViews::ADD, key);
   enter(key);
   mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQReportDefinition::btnRevertClicked () private slot
Definition at line 464 of file CQReportDefinition.cpp.
References load().
 {load();}
void CQReportDefinition::btnSeparatorClicked () private slot
Definition at line 178 of file CQReportDefinition.cpp.
References CCopasiObject::getCN(), mChanged, and TO_UTF8.
 {
   CCopasiReportSeparator Separator;
   if (mpTabCheck->isChecked())
     Separator = "\t";
   else
     Separator = TO_UTF8(mpSeparator->text());
   static_cast<QListWidget *>(mpReportSectionTab->currentWidget())->addItem(new CQReportListItem(Separator.getCN()));
   mChanged = true;
   return;
 }
void CQReportDefinition::btnTextClicked () private slot
Definition at line 194 of file CQReportDefinition.cpp.
References CCopasiObject::getCN(), CQTextDialog::getText(), mChanged, and TO_UTF8.
 {
   CQTextDialog * pDialog = new CQTextDialog(this);
   if (pDialog->exec() == QDialog::Accepted &&
       pDialog->getText() != "")
     {
       CCopasiStaticString Text(TO_UTF8(pDialog->getText()));
       static_cast<QListWidget *>(mpReportSectionTab->currentWidget())->addItem(new CQReportListItem(Text.getCN()));
     }
   delete pDialog;
   mChanged = true;
   return;
 }
void CQReportDefinition::btnUpClicked () private slot
Definition at line 254 of file CQReportDefinition.cpp.
References mChanged.
 {
   QListWidget * pList = static_cast< QListWidget * >(mpReportSectionTab->currentWidget());
   int i, to, multipleSelection;
   QListWidgetItem * pMove;
   for (i = pList->count() - 1, to = -1, multipleSelection = 0; i >= 0; i--)
     if (pList->item(i)->isSelected())
       {
         if (multipleSelection == 0)
           {
             to = i;
           }
         multipleSelection++;
       }
     else if (multipleSelection > 0)
       {
         pMove = pList->takeItem(i);
         if (pMove)
           {
             pList->insertItem(to, pMove);
             multipleSelection = 0;
             mChanged = true;
           }
       }
   // Unselect things we can not move.
   for (i = 0; i < multipleSelection; i++)
     pList->item(i)->setSelected(false);
   return;
 }
void CQReportDefinition::chkTabClicked () private slot
Definition at line 81 of file CQReportDefinition.cpp.
References mChanged.
 {
   mChanged = true;
   if (mpTabCheck->isChecked())
     mpSeparator->setEnabled(false);
   else
     mpSeparator->setEnabled(true);
 }
void CQReportDefinition::chkTitleClicked () private slot
Definition at line 326 of file CQReportDefinition.cpp.
References mChanged.
 {mChanged = true;}
void CQReportDefinition::commentChanged () private slot
Definition at line 72 of file CQReportDefinition.cpp.
References mChanged.
 {mChanged = true;}
bool CQReportDefinition::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 504 of file CQReportDefinition.cpp.
References load(), CopasiWidget::mKey, CopasiWidget::mpListView, CopasiWidget::mpObject, mpReportDefinition, and ListViews::switchToOtherWidget().
 {
   mpReportDefinition = dynamic_cast<CReportDefinition *>(mpObject);
   if (!mpReportDefinition)
     {
       mpListView->switchToOtherWidget(43, "");
       return false;
     }
   load();
   mpNotes->enter(mKey);
   return true;
 }
bool CQReportDefinition::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 493 of file CQReportDefinition.cpp.
References save().
 {
   mpBtnCommit->setFocus();
   save();
   mpNotes->leave();
   return true;
 }
bool CQReportDefinition::load () private
Definition at line 521 of file CQReportDefinition.cpp.
References FROM_UTF8, CReportDefinition::getBodyAddr(), CReportDefinition::getFooterAddr(), CReportDefinition::getHeaderAddr(), CCopasiObject::getObjectName(), CReportDefinition::getPrecision(), CReportDefinition::getSeparator(), CCopasiStaticString::getStaticString(), CReportDefinition::getTableAddr(), CReportDefinition::getTaskType(), CReportDefinition::getTitle(), CReportDefinition::isTable(), mChanged, mpReportDefinition, and setAdvancedMode().
Referenced by btnAdvancedClicked(), btnRevertClicked(), enterProtected(), and update().
 {
   if (!mpReportDefinition) return false;
   // Reset everything.
   mpHeaderList->clear();
   mpBodyList->clear();
   mpFooterList->clear();
   mpTableList->clear();
   mpName->setText(FROM_UTF8(mpReportDefinition->getObjectName()));
   mpTaskBox->setCurrentIndex(mpReportDefinition->getTaskType());
   //separator
   if (mpReportDefinition->getSeparator().getStaticString() == "\t")
     {
       mpSeparator->setEnabled(false);
       mpTabCheck->setChecked(true);
     }
   else
     {
       mpSeparator->setEnabled(true);
       mpTabCheck->setChecked(false);
       mpSeparator->setText(FROM_UTF8(mpReportDefinition->getSeparator().getStaticString()));
     }
   mpPrecision->setText(QString::number(mpReportDefinition->getPrecision()));
   std::vector< CRegisteredObjectName > * pList = NULL;
   std::vector< CRegisteredObjectName >::const_iterator it;
   std::vector< CRegisteredObjectName >::const_iterator end;
   // Toggle the display mode.
   if (mpReportDefinition->isTable())
     {
       setAdvancedMode(false);
       mpTitleCheck->setChecked(mpReportDefinition->getTitle());
       pList = mpReportDefinition->getTableAddr();
       for (it = pList->begin(), end = pList->end(); it != end; ++it)
         mpTableList->addItem(new CQReportListItem(*it));
     }
   else
     {
       setAdvancedMode(true);
       pList = mpReportDefinition->getHeaderAddr();
       for (it = pList->begin(), end = pList->end(); it != end; ++it)
         mpHeaderList->addItem(new CQReportListItem(*it));
       pList = mpReportDefinition->getBodyAddr();
       for (it = pList->begin(), end = pList->end(); it != end; ++it)
         mpBodyList->addItem(new CQReportListItem(*it));
       pList = mpReportDefinition->getFooterAddr();
       for (it = pList->begin(), end = pList->end(); it != end; ++it)
         mpFooterList->addItem(new CQReportListItem(*it));
     }
   mChanged = false;
   return true;
 }
void CQReportDefinition::nameChanged (const QString & string) private slot
Definition at line 66 of file CQReportDefinition.cpp.
References mChanged.
 {mChanged = true;}
void CQReportDefinition::precisionChanged (const QString & string) private slot
Definition at line 78 of file CQReportDefinition.cpp.
References mChanged.
 {mChanged = true;}
bool CQReportDefinition::save () private
Definition at line 589 of file CQReportDefinition.cpp.
References C_INT32, FROM_UTF8, CReportDefinition::getBodyAddr(), CCopasiObject::getCN(), CCopasiRootContainer::getDatamodelList(), CReportDefinition::getFooterAddr(), CReportDefinition::getHeaderAddr(), CCopasiObject::getObjectName(), CReportDefinition::getTableAddr(), CQMessageBox::information(), mAdvanced, mChanged, CopasiWidget::mKey, mpReportDefinition, CopasiWidget::protectedNotify(), ListViews::RENAME, ListViews::REPORT, CReportDefinition::setIsTable(), CCopasiObject::setObjectName(), CReportDefinition::setPrecision(), CReportDefinition::setSeparator(), CReportDefinition::setTaskType(), CReportDefinition::setTitle(), and TO_UTF8.
Referenced by btnAdvancedClicked(), btnCommitClicked(), and leave().
 {
   if (!mChanged) return true;
   if (!mpReportDefinition) return false;
   if (mpReportDefinition->getObjectName() != TO_UTF8(mpName->text()))
     {
       if (!mpReportDefinition->setObjectName(TO_UTF8(mpName->text())))
         {
           QString msg;
           msg = "Unable to rename report '" + FROM_UTF8(mpReportDefinition->getObjectName()) + "'\n"
                 + "to '" + mpName->text() + "' since a report with that name already exists.";
           CQMessageBox::information(this,
                                     "Unable to rename Report",
                                     msg,
                                     QMessageBox::Ok, QMessageBox::Ok);
           mpName->setText(FROM_UTF8(mpReportDefinition->getObjectName()));
         }
       else
         protectedNotify(ListViews::REPORT, ListViews::RENAME, mKey);
     }
   mpReportDefinition->setTaskType((CCopasiTask::Type) mpTaskBox->currentIndex());
   CCopasiReportSeparator Separator;
   if (mpTabCheck->isChecked())
     Separator = "\t";
   else
     Separator = TO_UTF8(mpSeparator->text());
   mpReportDefinition->setSeparator(Separator);
   mpReportDefinition->setPrecision(mpPrecision->text().toULong());
   mpReportDefinition->getHeaderAddr()->clear();
   mpReportDefinition->getBodyAddr()->clear();
   mpReportDefinition->getFooterAddr()->clear();
   mpReportDefinition->getTableAddr()->clear();
   std::vector< CRegisteredObjectName > * pList = NULL;
   unsigned C_INT32 i, imax;
   if (mAdvanced)
     {
       mpReportDefinition->setIsTable(false);
       pList = mpReportDefinition->getHeaderAddr();
       for (i = 0, imax = mpHeaderList->count(); i < imax; i++)
         if (static_cast<CQReportListItem *>(mpHeaderList->item(i))->getCN().getObjectType()
             == "Separator")
           pList->push_back(Separator.getCN());
         else
           pList->push_back(static_cast<CQReportListItem *>(mpHeaderList->item(i))->getCN());
       pList = mpReportDefinition->getBodyAddr();
       for (i = 0, imax = mpBodyList->count(); i < imax; i++)
         if (static_cast<CQReportListItem *>(mpBodyList->item(i))->getCN().getObjectType()
             == "Separator")
           pList->push_back(Separator.getCN());
         else
           pList->push_back(static_cast<CQReportListItem *>(mpBodyList->item(i))->getCN());
       pList = mpReportDefinition->getFooterAddr();
       for (i = 0, imax = mpFooterList->count(); i < imax; i++)
         if (static_cast<CQReportListItem *>(mpFooterList->item(i))->getCN().getObjectType()
             == "Separator")
           pList->push_back(Separator.getCN());
         else
           pList->push_back(static_cast<CQReportListItem *>(mpFooterList->item(i))->getCN());
     }
   else
     {
       mpReportDefinition->setIsTable(true);
       mpReportDefinition->setTitle(mpTitleCheck->isChecked());
       pList = mpReportDefinition->getTableAddr();
       for (i = 0, imax = mpTableList->count(); i < imax; i++)
         pList->push_back(static_cast<CQReportListItem *>(mpTableList->item(i))->getCN());
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   (*CCopasiRootContainer::getDatamodelList())[0]->changed();
   mChanged = false;
   return false;
 }
void CQReportDefinition::separatorChanged (const QString & string) private slot
Definition at line 75 of file CQReportDefinition.cpp.
References mChanged.
 {mChanged = true;}
bool CQReportDefinition::setAdvancedMode (const bool & advanced) private
Definition at line 685 of file CQReportDefinition.cpp.
References mAdvanced.
Referenced by btnAdvancedClicked(), CQReportDefinition(), and load().
 {
   if (advanced)
     {
       mAdvanced = true;
       mpBtnAdvanced->setText("Advanced <<");
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpTableList), false);
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpHeaderList), true);
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpBodyList), true);
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpFooterList), true);
       mpReportSectionTab->setCurrentIndex(2);
       mpBtnSeparator->show();
       mpBtnText->show();
       mpTitleCheck->hide();
     }
   else
     {
       mAdvanced = false;
       mpBtnAdvanced->setText("Advanced >>");
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpTableList), true);
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpHeaderList), false);
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpBodyList), false);
       mpReportSectionTab->setTabEnabled(mpReportSectionTab->indexOf(mpFooterList), false);
       mpReportSectionTab->setCurrentIndex(0);
       mpBtnSeparator->hide();
       mpBtnText->hide();
       mpTitleCheck->show();
     }
   return true;
 }
void CQReportDefinition::taskChanged (const QString & string) private slot
Definition at line 69 of file CQReportDefinition.cpp.
References mChanged.
 {mChanged = true;}
bool CQReportDefinition::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 470 of file CQReportDefinition.cpp.
References ListViews::ADD, ListViews::DELETE, load(), CopasiWidget::mIgnoreUpdates, CopasiWidget::mKey, ListViews::MODEL, mpReportDefinition, and ListViews::REPORT.
 {
   // If the model is deleted or a new model is loaded the existing pointer
   // becomes invalid.
   if (objectType == ListViews::MODEL &&
       (action == ListViews::DELETE ||
        action == ListViews::ADD))
     {
       mpReportDefinition = NULL;
       return true;
     }
   if (mIgnoreUpdates ||
       objectType != ListViews::REPORT ||
       key != mKey ||
       action == ListViews::DELETE)
     return true;
   return load();
 }
Member Data Documentation
bool CQReportDefinition::mAdvanced private
Definition at line 45 of file CQReportDefinition.h.
Referenced by btnAdvancedClicked(), save(), and setAdvancedMode().
bool CQReportDefinition::mChanged private
Definition at line 46 of file CQReportDefinition.h.
Referenced by btnAdvancedClicked(), btnDeleteClicked(), btnDownClicked(), btnItemClicked(), btnSeparatorClicked(), btnTextClicked(), btnUpClicked(), chkTabClicked(), chkTitleClicked(), commentChanged(), load(), nameChanged(), precisionChanged(), save(), separatorChanged(), and taskChanged().
QString CQReportDefinition::mOldComment private
Definition at line 48 of file CQReportDefinition.h.
CReportDefinition* CQReportDefinition::mpReportDefinition private
Definition at line 47 of file CQReportDefinition.h.
Referenced by btnAdvancedClicked(), CQReportDefinition(), enterProtected(), load(), save(), and update().
The documentation for this class was generated from the following files:
CQReportDefinition.h
CQReportDefinition.cpp