COPASI API: CQProgressDialog Class Reference
CQProgressDialog Class Reference
#include <CQProgressDialog.h>
Public Member Functions
CQProgressDialog (QWidget *parent=0, const char *name=0, Qt::WindowModality windowModality=Qt::WindowModal, Qt::WindowFlags fl=0)
bool insertProgressItem (CQProgressItem *pItem)
bool removeProgressItem (CQProgressItem *pItem)
~CQProgressDialog ()
Protected Slots
virtual void accept ()
virtual void btnContinuePressed ()
virtual void btnPausePressed ()
virtual void btnStopPressed ()
virtual void done (int)
virtual void reject ()
void timerShow ()
Protected Attributes
bool mPause
bool mProceed
Private Member Functions
void init ()
Private Attributes
unsigned C_INT32 mItemCount
Detailed Description
Definition at line 22 of file CQProgressDialog.h.
Constructor & Destructor Documentation
CQProgressDialog::CQProgressDialog (QWidget * parent = 0, const char * name = 0, Qt::WindowModality windowModality = Qt::WindowModal, Qt::WindowFlags fl = 0)
Definition at line 31 of file CQProgressDialog.cpp.
References init().
   : QDialog(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   setupUi(this);
   setWindowModality(windowModality);
   init();
 }
CQProgressDialog::~CQProgressDialog ()
Definition at line 46 of file CQProgressDialog.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQProgressDialog::accept () protected virtual slot
Definition at line 102 of file CQProgressDialog.cpp.
 {
   // ignore
 }
void CQProgressDialog::btnContinuePressed () protected virtual slot
Definition at line 111 of file CQProgressDialog.cpp.
References mPause.
Referenced by CProgressBar::btnContinuePressed().
 {
   mPause = false;
   mpBtnPause->setEnabled(true);
   mpBtnContinue->setEnabled(false);
 }
void CQProgressDialog::btnPausePressed () protected virtual slot
Definition at line 119 of file CQProgressDialog.cpp.
References mPause.
 {
   mPause = true;
   mpBtnPause->setEnabled(false);
   mpBtnContinue->setEnabled(true);
 }
void CQProgressDialog::btnStopPressed () protected virtual slot
Definition at line 127 of file CQProgressDialog.cpp.
References mPause, and mProceed.
Referenced by CProgressBar::btnStopPressed().
 {
   mPause = false;
   mProceed = false;
   mpBtnPause->setEnabled(false);
   mpBtnContinue->setEnabled(false);
   mpBtnStop->setEnabled(false);
 }
void CQProgressDialog::done (int) protected virtual slot
Definition at line 98 of file CQProgressDialog.cpp.
Referenced by CProgressBar::finish().
 {
   // ignore
 }
void CQProgressDialog::init () private
Definition at line 76 of file CQProgressDialog.cpp.
References CQIconResource::icon(), mItemCount, mPause, mProceed, CQIconResource::playerPause, CQIconResource::playerStart, CQIconResource::playerStop, and timerShow().
Referenced by CQProgressDialog().
 {
   mpBtnPause->setIcon(CQIconResource::icon(CQIconResource::playerPause));
   mpBtnContinue->setIcon(CQIconResource::icon(CQIconResource::playerStart));
   mpBtnStop->setIcon(CQIconResource::icon(CQIconResource::playerStop));
   mpLine->hide();
   //  mpBtnPause->hide();
   //  mpBtnContinue->hide();
   mpBtnContinue->setEnabled(false);
   mItemCount = 0;
   mPause = false;
   mProceed = true;
   QTimer::singleShot(1500, this, SLOT(timerShow()));
   return;
 }
bool CQProgressDialog::insertProgressItem (CQProgressItem * pItem)
Definition at line 51 of file CQProgressDialog.cpp.
References mItemCount.
Referenced by CProgressBar::slotAddItem().
 {
   if (mItemCount == 0) mpLine->show();
   vboxLayout->removeItem(mpSpacer);
   vboxLayout->addWidget(pItem);
   vboxLayout->addItem(mpSpacer);
   pItem->show();
   mItemCount++;
   return true;
 }
void CQProgressDialog::reject () protected virtual slot
Definition at line 106 of file CQProgressDialog.cpp.
 {
   // ignore
 }
bool CQProgressDialog::removeProgressItem (CQProgressItem * pItem)
Definition at line 65 of file CQProgressDialog.cpp.
References mItemCount.
Referenced by CProgressBar::finish(), and CProgressBar::slotFinishItem().
 {
   vboxLayout->removeWidget(pItem);
   mItemCount--;
   if (mItemCount == 0) mpLine->hide();
   return true;
 }
void CQProgressDialog::timerShow () protected slot
Definition at line 137 of file CQProgressDialog.cpp.
References CopasiUI3Window::getMainWindow().
Referenced by init().
 {
   if (CopasiUI3Window::getMainWindow() != NULL &&
       CopasiUI3Window::getMainWindow()->messageShown())
     {
       QTimer::singleShot(1500, this, SLOT(timerShow()));
     }
   else
     {
       show();
     }
 }
Member Data Documentation
unsigned C_INT32 CQProgressDialog::mItemCount private
Definition at line 49 of file CQProgressDialog.h.
Referenced by init(), insertProgressItem(), and removeProgressItem().
bool CQProgressDialog::mPause protected
Definition at line 35 of file CQProgressDialog.h.
Referenced by btnContinuePressed(), btnPausePressed(), btnStopPressed(), init(), and CProgressBar::progressItem().
bool CQProgressDialog::mProceed protected
Definition at line 34 of file CQProgressDialog.h.
Referenced by btnStopPressed(), CProgressBar::finish(), CProgressBar::finishItem(), init(), CProgressBar::proceed(), CProgressBar::progressItem(), CProgressBar::resetItem(), and CProgressBar::slotProgressAll().
The documentation for this class was generated from the following files:
CQProgressDialog.h
CQProgressDialog.cpp