COPASI API: SEDMLImporter.cpp File Reference
SEDMLImporter.cpp File Reference
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <map>
#include <limits>
#include <cmath>
#include <algorithm>
#include <sedml/SedTypes.h>
#include <sbml/math/FormulaFormatter.h>
#include "copasi.h"
#include "report/CKeyFactory.h"
#include "model/CModel.h"
#include "model/CCompartment.h"
#include "model/CMetab.h"
#include "model/CReaction.h"
#include "model/CModelValue.h"
#include "model/CEvent.h"
#include "function/CNodeK.h"
#include "function/CFunctionDB.h"
#include "function/CEvaluationTree.h"
#include "function/CExpression.h"
#include "function/CFunctionParameters.h"
#include "report/CCopasiObjectReference.h"
#include "utilities/CCopasiTree.h"
#include "utilities/CNodeIterator.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "MIRIAM/CRDFGraphConverter.h"
#include "compareExpressions/CEvaluationNodeNormalizer.h"
#include "commandline/CLocaleString.h"
#include "commandline/COptions.h"
#include "utilities/CProcessReport.h"
#include "copasi/commandline/CConfigurationFile.h"
#include "utilities/CCopasiMessage.h"
#include "trajectory/CTrajectoryTask.h"
#include "trajectory/CTrajectoryProblem.h"
#include "sbml/SBMLImporter.h"
#include "utilities/CDirEntry.h"
#include "utilities/CCopasiException.h"
#include "utilities/CCopasiTask.h"
#include "plot/COutputDefinitionVector.h"
#include "plot/CPlotSpecification.h"
#include "report/CReportDefinitionVector.h"
#include <steadystate/CSteadyStateTask.h>
#include <scan/CScanTask.h>
#include "SEDMLImporter.h"
#include "SEDMLUtils.h"
Functions
bool applyAttributeChange (CModel *pCopasiModel, CModelParameterSet &set, const std::string &target, const std::string &newValue)
bool applyValueToModelParameter (CModelParameter *modelParameter, CCopasiObject *obj, double newValue)
bool applyValueToParameterSet (CModelParameterSet &set, CCopasiObject *obj, double newValue)
bool isScan (const SedTask *task)
bool isScan (const SedRepeatedTask *task)
bool isTC (const SedTask *task)
Function Documentation
bool applyAttributeChange (CModel * pCopasiModel, CModelParameterSet & set, const std::string & target, const std::string & newValue)
Definition at line 787 of file SEDMLImporter.cpp.
References applyValueToParameterSet(), CCopasiObject::getObjectParent(), and SEDMLUtils::resolveXPath().
Referenced by SEDMLImporter::importFirstSBMLModel().
 {
   CCopasiObject *obj = const_cast<CCopasiObject*>(SEDMLUtils::resolveXPath(pCopasiModel, target, true));
   if (obj == NULL)
     return false;
   // convert the string to double
   std::stringstream str;
   str << newValue;
   double result;
   str >> result;
   // set the value
   applyValueToParameterSet(set, obj->getObjectParent(), result);
   return true;
 }
bool applyValueToModelParameter (CModelParameter * modelParameter, CCopasiObject * obj, double newValue)
Definition at line 746 of file SEDMLImporter.cpp.
References CModelParameter::Concentration, CModelParameter::getChild(), CModelParameter::getCN(), CCopasiObject::getCN(), CModelParameter::getNumChildren(), and CModelParameter::setValue().
Referenced by applyValueToParameterSet().
 {
   if (modelParameter == NULL || obj == NULL) return false;
   size_t numChilren = modelParameter->getNumChildren();
   const CCopasiObjectName& cn = modelParameter->getCN();
   const CCopasiObjectName& targetCN = obj->getCN();
   if (cn == targetCN)
     {
       modelParameter->setValue(newValue, CModelParameter::Concentration);
       return true;
     }
   for (unsigned int i = 0; i < numChilren; ++i)
     {
       CModelParameter* current = const_cast<CModelParameter* >(modelParameter->getChild(i));
       if (applyValueToModelParameter(current, obj, newValue))
         return true;
     }
   return false;
 }
bool applyValueToParameterSet (CModelParameterSet & set, CCopasiObject * obj, double newValue)
Definition at line 772 of file SEDMLImporter.cpp.
References applyValueToModelParameter(), CModelParameterGroup::begin(), and CModelParameterGroup::end().
Referenced by applyAttributeChange().
 {
   CModelParameterGroup::iterator it = set.begin();
   while (it != set.end())
     {
       if (applyValueToModelParameter(*it, obj, newValue))
         return true;
       ++it;
     }
   return false;
 }
bool isScan (const SedTask * task)
Definition at line 184 of file SEDMLImporter.cpp.
Referenced by isScan(), and SEDMLImporter::readListOfPlotsFromSedMLOutput().
 {
   if (task == NULL || task->getSedDocument() == NULL) return false;
   const SedDocument* doc = task->getSedDocument();
   if (task->isSetSimulationReference())
     {
       const SedSimulation* sim = doc->getSimulation(task->getSimulationReference());
       if (sim != NULL && (
             sim->getTypeCode() == SEDML_SIMULATION_STEADYSTATE ||
             sim->getTypeCode() == SEDML_SIMULATION_ONESTEP ||
             sim->getTypeCode() == SEDML_SIMULATION_UNIFORMTIMECOURSE))
         return true;
     }
   return false;
 }
bool isScan (const SedRepeatedTask * task)
Definition at line 205 of file SEDMLImporter.cpp.
References isScan().
 {
   if (task == NULL || task->getSedDocument() == NULL) return false;
   const SedDocument* doc = task->getSedDocument();
   if (task->isSetSimulationReference())
     {
       const SedSimulation* sim = doc->getSimulation(task->getSimulationReference());
       if (sim != NULL && (
             sim->getTypeCode() == SEDML_SIMULATION_STEADYSTATE ||
             sim->getTypeCode() == SEDML_SIMULATION_ONESTEP ||
             sim->getTypeCode() == SEDML_SIMULATION_UNIFORMTIMECOURSE))
         return true;
     }
   for (size_t i = 0; i < task->getNumSubTasks(); ++i)
     {
       const SedSubTask* subTask = task->getSubTask(i);
       const SedTask* t = doc->getTask(subTask->getTask());
       if (isScan(t)) return true;
     }
   return false;
 }
bool isTC (const SedTask * task)
Definition at line 166 of file SEDMLImporter.cpp.
Referenced by SEDMLImporter::readListOfPlotsFromSedMLOutput().
 {
   if (task == NULL || task->getSedDocument() == NULL) return false;
   const SedDocument* doc = task->getSedDocument();
   if (task->isSetSimulationReference())
     {
       const SedSimulation* sim = doc->getSimulation(task->getSimulationReference());
       if (sim != NULL && (
             sim->getTypeCode() == SEDML_SIMULATION_UNIFORMTIMECOURSE))
         return true;
     }
   return false;
 }