COPASI API: CMathEventN Class Reference
CMathEventN Class Reference
#include <CMathEvent.h>
Classes
class CAssignment
class CTrigger
Public Member Functions
void addAssignment (CMathObject *pTarget, CMathObject *pExpression)
CMathEventN ()
bool compile (CEvent *pDataEvent, CMathContainer &container)
bool compile (CMathContainer &container)
void copy (const CMathEventN &src, CMathContainer &container, const size_t &valueOffset, const size_t &objectOffset)
const CVector< CAssignment > & getAssignments () const
const CTrigger & getTrigger () const
void initialize (CMath::sPointers &pointers)
void setDelayExpression (const std::string &infix, CMathContainer &container)
void setPriorityExpression (const std::string &infix, CMathContainer &container)
void setTriggerExpression (const std::string &infix, CMathContainer &container)
~CMathEventN ()
Static Public Member Functions
static void allocate (CMathEventN *pEvent, const CEvent *pDataEvent, const CMathContainer &container)
Private Attributes
CVector< CAssignment > mAssignments
bool mDelayAssignment
bool mFireAtInitialTime
CMathObject * mpDelay
bool mPersistentTrigger
CMathObject * mpPriority
CTrigger mTrigger
CEvent::Type mType
Detailed Description
Definition at line 20 of file CMathEvent.h.
Constructor & Destructor Documentation
CMathEventN::CMathEventN ()
Default constructor
Definition at line 846 of file CMathEvent.cpp.
                         :
   mType(CEvent::Assignment),
   mTrigger(),
   mAssignments(),
   mpDelay(NULL),
   mpPriority(NULL),
   mFireAtInitialTime(false),
   mPersistentTrigger(false),
   mDelayAssignment(true)
 {}
CMathEventN::~CMathEventN ()
Destructor
Definition at line 860 of file CMathEvent.cpp.
 {}
Member Function Documentation
void CMathEventN::addAssignment (CMathObject * pTarget, CMathObject * pExpression)
Add an assignment
Parameters
CMathObject * pTarget
CMathObject * pExpression
Definition at line 991 of file CMathEvent.cpp.
References mAssignments, CMathEventN::CAssignment::setExpression(), and CMathEventN::CAssignment::setTarget().
Referenced by CMathContainer::replaceDiscontinuousNode().
 {
   size_t OldSize = mAssignments.size();
   mAssignments.resize(OldSize + 1, true);
   CAssignment & Assignment = mAssignments[OldSize];
   Assignment.setTarget(pTarget);
   Assignment.setExpression(pExpression);
 }
void CMathEventN::allocate (CMathEventN * pEvent, const CEvent * pDataEvent, const CMathContainer & container) static
Definition at line 838 of file CMathEvent.cpp.
References CMathEventN::CTrigger::allocate(), CEvent::getAssignments(), mAssignments, mTrigger, and CCopasiVector< T >::size().
Referenced by CMathContainer::allocate().
 {
   pEvent->mTrigger.allocate(pDataEvent, container);
   pEvent->mAssignments.resize(pDataEvent->getAssignments().size());
 }
bool CMathEventN::compile (CEvent * pDataEvent, CMathContainer & container)
Definition at line 916 of file CMathEvent.cpp.
References CCopasiVector< T >::begin(), CMathEventN::CAssignment::compile(), CExpression::compile(), CMathEventN::CTrigger::compile(), CEvent::getAssignments(), CEvent::getDelayAssignment(), CEvent::getDelayExpression(), CEvent::getFireAtInitialTime(), CEvent::getPersistentTrigger(), CEvent::getPriorityExpression(), mAssignments, mDelayAssignment, mFireAtInitialTime, mpDelay, mPersistentTrigger, mpPriority, mTrigger, CMathObject::setExpression(), and CExpression::setInfix().
Referenced by CMathEventN::CTrigger::compile(), CMathContainer::compileEvents(), CMathEventN::CTrigger::compileFUNCTION(), and CMathEventN::CTrigger::setExpression().
 {
   bool success = true;
   mFireAtInitialTime = pDataEvent->getFireAtInitialTime();
   mPersistentTrigger = pDataEvent->getPersistentTrigger();
   mDelayAssignment = pDataEvent->getDelayAssignment();
   // Compile Trigger
   success &= mTrigger.compile(pDataEvent, container);
   CAssignment * pAssignment = mAssignments.array();
   CAssignment * pAssignmentEnd = pAssignment + mAssignments.size();
   CCopasiVector< CEventAssignment >::const_iterator itAssignment = pDataEvent->getAssignments().begin();
   // Compile assignments.
   for (; pAssignment != pAssignmentEnd; ++pAssignment, ++itAssignment)
     {
       success &= pAssignment->compile(*itAssignment, container);
     }
   std::vector< CCopasiContainer * > ListOfContainer;
   // ListOfContainer.push_back(const_cast< CMathContainer * >(&container));
   // Compile the delay object.
   CExpression DelayExpression("DelayExpression", &container);
   success &= DelayExpression.setInfix(pDataEvent->getDelayExpression());
   success &= DelayExpression.compile(ListOfContainer);
   success &= mpDelay->setExpression(DelayExpression, container);
   // Compile the priority object.
   CExpression PriorityExpression("PriorityExpression", &container);
   success &= PriorityExpression.setInfix(pDataEvent->getPriorityExpression());
   success &= PriorityExpression.compile(ListOfContainer);
   success &= mpPriority->setExpression(PriorityExpression, container);
   return success;
 }
bool CMathEventN::compile (CMathContainer & container)
Definition at line 956 of file CMathEvent.cpp.
References CMathEventN::CTrigger::compile(), and mTrigger.
 {
   bool success = true;
   // Compile Trigger
   success &= mTrigger.compile(NULL, container);
   // Compile assignments.
   // Nothing to do since the target and expression objects are already compiled
   // The delay object is already compiled.
   // The priority object is already compiled.
   return success;
 }
void CMathEventN::copy (const CMathEventN & src, CMathContainer & container, const size_t & valueOffset, const size_t & objectOffset)
Copy an existing object
Parameters
const CMathEventN & src
CMathContainer & container
const size_t & valueOffset
const size_t & objectOffset
Definition at line 894 of file CMathEvent.cpp.
References CMathEventN::CAssignment::copy(), CMathEventN::CTrigger::copy(), mAssignments, mDelayAssignment, mFireAtInitialTime, mpDelay, mPersistentTrigger, mpPriority, mTrigger, and mType.
Referenced by CMathContainer::CMathContainer().
 {
   mType = src.mType;
   mTrigger.copy(src.mTrigger, container, valueOffset, objectOffset);
   mAssignments.resize(src.mAssignments.size());
   CAssignment * pAssignment = mAssignments.array();
   CAssignment * pAssignmentEnd = pAssignment + mAssignments.size();
   const CAssignment * pAssignmentSrc = src.mAssignments.array();
   for (; pAssignment != pAssignmentEnd; ++pAssignment, ++pAssignmentSrc)
     {
       pAssignment->copy(*pAssignmentSrc, container, valueOffset, objectOffset);
     }
   mpDelay = src.mpDelay + objectOffset;
   mpPriority = src.mpPriority + objectOffset;
   mFireAtInitialTime = src.mFireAtInitialTime;
   mPersistentTrigger = src.mPersistentTrigger;
   mDelayAssignment = src.mDelayAssignment;
 }
const CVector< CMathEventN::CAssignment > & CMathEventN::getAssignments () const
Definition at line 1001 of file CMathEvent.cpp.
References mAssignments.
Referenced by CMathContainer::allocate().
 {
   return mAssignments;
 }
const CMathEventN::CTrigger & CMathEventN::getTrigger () const
Definition at line 863 of file CMathEvent.cpp.
References mTrigger.
Referenced by CMathContainer::allocate().
 {
   return mTrigger;
 }
void CMathEventN::initialize (CMath::sPointers & pointers)
Definition at line 868 of file CMathEvent.cpp.
References CMath::Event, CMath::EventDelay, CMath::EventPriority, CMathEventN::CAssignment::initialize(), CMathObject::initialize(), CMathEventN::CTrigger::initialize(), mAssignments, mpDelay, mpPriority, mTrigger, CMath::sPointers::pEventDelays, CMath::sPointers::pEventDelaysObject, CMath::sPointers::pEventPriorities, CMath::sPointers::pEventPrioritiesObject, and CMath::SimulationTypeUndefined.
Referenced by CMathContainer::initializeEvents().
 {
   mTrigger.initialize(pointers);
   CAssignment * pAssignment = mAssignments.array();
   CAssignment * pAssignmentEnd = pAssignment + mAssignments.size();
   // Initialize assignments.
   for (; pAssignment != pAssignmentEnd; ++pAssignment)
     {
       pAssignment->initialize(pointers);
     }
   // Initialize delay object.
   mpDelay = pointers.pEventDelaysObject;
   CMathObject::initialize(pointers.pEventDelaysObject, pointers.pEventDelays,
                           CMath::EventDelay, CMath::Event, CMath::SimulationTypeUndefined,
                           false, false, NULL);
   // Initialize priority object.
   mpPriority = pointers.pEventDelaysObject;
   CMathObject::initialize(pointers.pEventPrioritiesObject, pointers.pEventPriorities,
                           CMath::EventPriority, CMath::Event, CMath::SimulationTypeUndefined,
                           false, false, NULL);
 }
void CMathEventN::setDelayExpression (const std::string & infix, CMathContainer & container)
Set the delay expression
Parameters
const std::string & infix
CMathContainer & container
Definition at line 977 of file CMathEvent.cpp.
References mpDelay, and CMathObject::setExpression().
 {
   assert(mpDelay != NULL);
   mpDelay->setExpression(infix, false, container);
 }
void CMathEventN::setPriorityExpression (const std::string & infix, CMathContainer & container)
Set the priority expression
Parameters
const std::string & infix
CMathContainer & container
Definition at line 984 of file CMathEvent.cpp.
References mpPriority, and CMathObject::setExpression().
 {
   assert(mpPriority != NULL);
   mpPriority->setExpression(infix, false, container);
 }
void CMathEventN::setTriggerExpression (const std::string & infix, CMathContainer & container)
Set the trigger expression
Parameters
const std::string & infix
CMathContainer & container
Definition at line 972 of file CMathEvent.cpp.
References mTrigger, and CMathEventN::CTrigger::setExpression().
Referenced by CMathContainer::replaceDiscontinuousNode().
 {
   mTrigger.setExpression(infix, container);
 }
Member Data Documentation
CVector< CAssignment > CMathEventN::mAssignments private
Definition at line 271 of file CMathEvent.h.
Referenced by addAssignment(), allocate(), compile(), copy(), getAssignments(), and initialize().
bool CMathEventN::mDelayAssignment private
Definition at line 276 of file CMathEvent.h.
Referenced by compile(), and copy().
bool CMathEventN::mFireAtInitialTime private
Definition at line 274 of file CMathEvent.h.
Referenced by compile(), and copy().
CMathObject* CMathEventN::mpDelay private
Definition at line 272 of file CMathEvent.h.
Referenced by compile(), copy(), initialize(), and setDelayExpression().
bool CMathEventN::mPersistentTrigger private
Definition at line 275 of file CMathEvent.h.
Referenced by compile(), and copy().
CMathObject* CMathEventN::mpPriority private
Definition at line 273 of file CMathEvent.h.
Referenced by compile(), copy(), initialize(), and setPriorityExpression().
CTrigger CMathEventN::mTrigger private
Definition at line 270 of file CMathEvent.h.
Referenced by allocate(), compile(), copy(), getTrigger(), initialize(), and setTriggerExpression().
CEvent::Type CMathEventN::mType private
Definition at line 269 of file CMathEvent.h.
Referenced by copy().
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp