COPASI API: CSBMLunit Class Reference
CSBMLunit Class Reference
#include <CSBMLunit.h>
Classes
class SymbolicExponent
this class uniquely (in a given context) identifies a symbol
Public Member Functions
void applyExponent (double exp)
apply numeric exponent to the unit.
void applyExponent (const std::string &id, size_t frame)
apply symbolic exponent to the unit
void applyInverseExponent (const std::string &id, size_t frame)
apply inverse of symbolic exponent to the unit
CSBMLunit (unsigned int sbmlLevel, unsigned int sbmlVersion)
Default constructor.
CSBMLunit (const CSBMLunit &src)
Copy constructor.
CSBMLunit (const UnitDefinition *ud)
Constructor from libsbml units.
virtual std::string getDisplayString () const
UnitDefinition & getSBMLUnitDefinition ()
const UnitDefinition & getSBMLUnitDefinition () const
int getSymbolicExpExp () const
const std::string & getSymbolicExponent () const
void invert ()
bool isDimensionless () const
bool multiply (const CSBMLunit &unit)
virtual ~CSBMLunit ()
Static Public Member Functions
static bool isEqual (const CSBMLunit &unit1, const CSBMLunit &unit2)
Private Attributes
SymbolicExponent mSymExp
int mSymExpExp
UnitDefinition mUD
Detailed Description
The current implementation of the units is just a wrapper for the libsbml UnitDefinition class.
Definition at line 21 of file CSBMLunit.h.
Constructor & Destructor Documentation
CSBMLunit::CSBMLunit (unsigned int sbmlLevel, unsigned int sbmlVersion)
Default constructor.
Definition at line 12 of file CSBMLunit.cpp.
References mUD.
     : mUD(UnitDefinition(sbmlLevel, sbmlVersion)),
     mSymExp(),
     mSymExpExp(0)
 {
   Unit *tmp = mUD.createUnit();
   tmp->setKind(UNIT_KIND_DIMENSIONLESS);
 #if LIBSBML_VERSION > 40100
   tmp->initDefaults();
 #endif
 }
CSBMLunit::CSBMLunit (const CSBMLunit & src)
Copy constructor.
Definition at line 25 of file CSBMLunit.cpp.
     : mUD(src.mUD),
     mSymExp(src.mSymExp),
     mSymExpExp(src.mSymExpExp)
 {
   //TODO verify that this does indeed do a deep copy
 }
CSBMLunit::CSBMLunit (const UnitDefinition * ud)
Constructor from libsbml units.
Definition at line 33 of file CSBMLunit.cpp.
     : mUD(*ud),
     mSymExp(),
     mSymExpExp(0)
 {
 }
CSBMLunit::~CSBMLunit () virtual
Definition at line 40 of file CSBMLunit.cpp.
 {
 }
Member Function Documentation
void CSBMLunit::applyExponent (double exp)
apply numeric exponent to the unit.
The current implementation only supports integer exponents.
Definition at line 104 of file CSBMLunit.cpp.
References isDimensionless(), mSymExpExp, and mUD.
Referenced by CSBMLunitInterface::recursionPower().
 {
   if (isDimensionless())
     return;
   if (mSymExpExp != 0)
     {
       // could not apply numeric exponent because of symbolic exponent !!!
     }
   unsigned int i, imax = mUD.getNumUnits();
   for (i = 0; i < imax; ++i)
     {
       mUD.getUnit(i)->setExponent(floor(0.5 + exp*(double)mUD.getUnit(i)->getExponent()));
     }
 }
void CSBMLunit::applyExponent (const std::string & id, size_t frame)
apply symbolic exponent to the unit
This method applies a symbol as an exponent to the unit. The result is not really a valid unit itself, but the exponent can cancel out later during the calculations (via applyInverseExponent()). In the current implementation, a string and an integer (sbml id + frame stack index) are sufficient to uniquely identify a symbol within one expression. In other words: Once we know the frame index the ID is unique.
Definition at line 122 of file CSBMLunit.cpp.
References isDimensionless(), CSBMLunit::SymbolicExponent::isEqual(), mSymExp, and mSymExpExp.
 {
   if (isDimensionless())
     return;
   if ((mSymExpExp == 0) || mSymExp.isEqual(SymbolicExponent(id, frame)))
     {
       // applied symbolic exponent
       ++mSymExpExp;
       mSymExp = SymbolicExponent(id, frame);
     }
   else
     {
       // could not apply symbolic exponent !!!
       assert(false);
     }
 }
void CSBMLunit::applyInverseExponent (const std::string & id, size_t frame)
apply inverse of symbolic exponent to the unit
This method applies a symbol as a reverse exponent to the unit. The result is not really a valid unit itself, but the exponent can cancel out later. See applyExponent(std::string id, int frame)
Definition at line 140 of file CSBMLunit.cpp.
References isDimensionless(), CSBMLunit::SymbolicExponent::isEqual(), mSymExp, and mSymExpExp.
Referenced by CSBMLunitInterface::recursionPower().
 {
   if (isDimensionless())
     return;
   if ((mSymExpExp == 0) || mSymExp.isEqual(SymbolicExponent(id, frame)))
     {
       // applied inverse symbolic exponent
       --mSymExpExp;
       mSymExp = SymbolicExponent(id, frame);
     }
   else
     {
       // could not apply inverse symbolic exponent !!!
       assert(false);
     }
 }
std::string CSBMLunit::getDisplayString () const virtual
Reimplemented in CSBMLunitInformation.
Definition at line 44 of file CSBMLunit.cpp.
References CSBMLunit::SymbolicExponent::mID, mSymExp, mSymExpExp, and mUD.
Referenced by CSBMLunitInformation::getDisplayString().
 {
   if (mSymExpExp == 0)
     {
       return UnitDefinition::printUnits(&mUD, true);
     }
   else if (mSymExpExp == 1)
     {
       return "(" + UnitDefinition::printUnits(&mUD, true) + ")^" + mSymExp.mID;
     }
   else
     {
       return "(" + UnitDefinition::printUnits(&mUD, true) + ")^" + mSymExp.mID + "^someExponent";
     }
 }
UnitDefinition& CSBMLunit::getSBMLUnitDefinition () inline
Definition at line 69 of file CSBMLunit.h.
References mUD.
Referenced by Expression2PresentationMMLUnits::getMathML(), and CSBMLunitInterface::writeBackToModel().
 {return mUD;};
const UnitDefinition& CSBMLunit::getSBMLUnitDefinition () const inline
Definition at line 70 of file CSBMLunit.h.
References mUD.
 {return mUD;};
int CSBMLunit::getSymbolicExpExp () const inline
Definition at line 72 of file CSBMLunit.h.
References mSymExpExp.
Referenced by Expression2PresentationMMLUnits::getMathML(), and CSBMLunitInterface::writeBackToModel().
 {return mSymExpExp;};
const std::string& CSBMLunit::getSymbolicExponent () const inline
Definition at line 73 of file CSBMLunit.h.
Referenced by Expression2PresentationMMLUnits::getMathML().
 {return mSymExp.mID;};
void CSBMLunit::invert ()
Definition at line 88 of file CSBMLunit.cpp.
References isDimensionless(), mSymExpExp, and mUD.
Referenced by CSBMLunitInterface::handleOneExpression(), CSBMLunitInterface::initializeFromSBMLModel(), CSBMLunitInterface::recursionDivide(), and CSBMLunitInterface::recursionTimes().
 {
   if (isDimensionless())
     return;
   if (mSymExpExp != 0)
     {
       // could not invert units because of symbolic exponent !!!
     }
   unsigned int i, imax = mUD.getNumUnits();
   for (i = 0; i < imax; ++i)
     mUD.getUnit(i)->setExponent(-mUD.getUnit(i)->getExponent());
 }
bool CSBMLunit::isDimensionless () const
Definition at line 175 of file CSBMLunit.cpp.
References mUD.
Referenced by applyExponent(), applyInverseExponent(), invert(), isEqual(), and multiply().
 {
   return mUD.isVariantOfDimensionless();
 }
bool CSBMLunit::isEqual (const CSBMLunit & unit1, const CSBMLunit & unit2) static
Definition at line 159 of file CSBMLunit.cpp.
References isDimensionless(), CSBMLunit::SymbolicExponent::isEqual(), mSymExp, mSymExpExp, and mUD.
Referenced by CSBMLunitInterface::handleTerminalNode(), and CSBMLunitInformation::isEqual().
 {
   if (unit1.isDimensionless() && unit2.isDimensionless())
     return true;
   if (((unit1.mSymExpExp == 0) && (unit2.mSymExpExp == 0))
       || (unit1.mSymExp.isEqual(unit2.mSymExp) && (unit1.mSymExpExp == unit2.mSymExpExp)))
     {
       return UnitDefinition::areEquivalent(&unit1.mUD, &unit2.mUD);
     }
   else
     {
       return false;
     }
 }
bool CSBMLunit::multiply (const CSBMLunit & unit)
Definition at line 60 of file CSBMLunit.cpp.
References isDimensionless(), CSBMLunit::SymbolicExponent::isEqual(), mSymExp, mSymExpExp, and mUD.
Referenced by CSBMLunitInterface::handleOneExpression(), CSBMLunitInterface::initializeFromSBMLModel(), CSBMLunitInterface::recursionDivide(), and CSBMLunitInterface::recursionTimes().
 {
   if (unit.isDimensionless())
     return true;
   if (isDimensionless())
     {
       mUD = unit.mUD;
       mSymExp = unit.mSymExp;
       mSymExpExp = unit.mSymExpExp;
       return true;
     }
   if ((mSymExpExp == 0 && unit.mSymExpExp == 0)
       || ((mSymExpExp == unit.mSymExpExp) && (mSymExp.isEqual(unit.mSymExp))))
     {
       UnitDefinition tmp = unit.mUD;
       UnitDefinition * tmpPointerUD = UnitDefinition::combine(&this->mUD, &tmp);
       mUD = *tmpPointerUD;
       delete tmpPointerUD;
       return true;
     }
   // could not multiply units because of symbolic exponent !!!
   return false;
 }
Member Data Documentation
SymbolicExponent CSBMLunit::mSymExp private
Definition at line 90 of file CSBMLunit.h.
Referenced by applyExponent(), applyInverseExponent(), getDisplayString(), isEqual(), and multiply().
int CSBMLunit::mSymExpExp private
Definition at line 91 of file CSBMLunit.h.
Referenced by applyExponent(), applyInverseExponent(), getDisplayString(), getSymbolicExpExp(), invert(), isEqual(), and multiply().
UnitDefinition CSBMLunit::mUD private
Definition at line 73 of file CSBMLunit.h.
Referenced by applyExponent(), CSBMLunit(), getDisplayString(), getSBMLUnitDefinition(), invert(), isDimensionless(), isEqual(), and multiply().
The documentation for this class was generated from the following files:
CSBMLunit.h
CSBMLunit.cpp