COPASI API: CStepMatrix Class Reference
CStepMatrix Class Reference
#include <CStepMatrix.h>
Public Types
typedef CStepMatrixColumn *const * const_iterator
Public Member Functions
void add (CStepMatrixColumn *pColumn)
CStepMatrixColumn * addColumn (const CZeroSet &set, const CStepMatrixColumn *pPositive, const CStepMatrixColumn *pNegative)
const_iterator begin () const
void compact ()
void convertRow ()
CStepMatrix (size_t rows)
CStepMatrix (CMatrix< C_INT64 > &nullspaceMatrix)
const_iterator end () const
void getAllUnsetBitIndexes (const CStepMatrixColumn *pColumn, CVector< size_t > &indexes) const
size_t getFirstUnconvertedRow () const
size_t getNumUnconvertedRows () const
void getUnsetBitIndexes (const CStepMatrixColumn *pColumn, CVector< size_t > &indexes) const
void removeColumn (CStepMatrixColumn *pColumn)
void removeInvalidColumns (std::vector< CStepMatrixColumn * > &invalidColumns)
bool splitColumns (std::vector< CStepMatrixColumn * > &PositiveColumns, std::vector< CStepMatrixColumn * > &NegativeColumns, std::vector< CStepMatrixColumn * > &NullColumns)
~CStepMatrix ()
Private Types
typedef CStepMatrixColumn ** iterator
Private Types inherited from CVectorCore< CStepMatrixColumn * >
typedef CStepMatrixColumn * elementType
Private Member Functions
void convertRow (const size_t &index, CMatrix< C_INT64 > &nullspaceMatrix)
CStepMatrix ()
Private Member Functions inherited from CVector< CStepMatrixColumn * >
CVector (size_t size=0)
CVector (const CVector< CStepMatrixColumn * > &src)
CVector< CStepMatrixColumn * > & operator= (const CVectorCore< CStepMatrixColumn * > &rhs)
CVector< CStepMatrixColumn * > & operator= (const CVector< CStepMatrixColumn * > &rhs)
CVector< CStepMatrixColumn * > & operator= (const CStepMatrixColumn *&value)
void resize (size_t size, const bool &copy=false)
~CVector ()
void copy (const CVectorCore< CStepMatrixColumn * > &rhs)
Private Member Functions inherited from CVectorCore< CStepMatrixColumn * >
bool applyPivot (const CVectorCore< size_t > &pivot)
CStepMatrixColumn ** array ()
const CStepMatrixColumn ** array () const
CVectorCore (const size_t &size=0, CStepMatrixColumn **vector=NULL)
CVectorCore (const CVectorCore< CStepMatrixColumn * > &src)
CStepMatrixColumn *& operator() (const size_t &row)
const CStepMatrixColumn *& operator() (const size_t &row) const
CVectorCore< CStepMatrixColumn * > & operator= (const CStepMatrixColumn *&value)
CStepMatrixColumn *& operator[] (const size_t &row)
const CStepMatrixColumn *& operator[] (const size_t &row) const
size_t size () const
~CVectorCore ()
Private Attributes
iterator mBeyond
size_t mFirstUnconvertedRow
iterator mInsert
CVector< size_t > mPivot
size_t mRows
Private Attributes inherited from CVectorCore< CStepMatrixColumn * >
size_t mSize
CStepMatrixColumn ** mVector
Friends
std::ostream & operator<< (std::ostream &, const CStepMatrix &)
Detailed Description
Definition at line 23 of file CStepMatrix.h.
Member Typedef Documentation
typedef CStepMatrixColumn* const* CStepMatrix::const_iterator
Definition at line 29 of file CStepMatrix.h.
typedef CStepMatrixColumn** CStepMatrix::iterator private
Definition at line 26 of file CStepMatrix.h.
Constructor & Destructor Documentation
CStepMatrix::CStepMatrix () private
Definition at line 26 of file CStepMatrix.cpp.
                         :
     CVector< CStepMatrixColumn * >(0),
     mRows(0),
     mPivot(0),
     mFirstUnconvertedRow(0)
 {}
CStepMatrix::CStepMatrix (size_t rows)
Definition at line 33 of file CStepMatrix.cpp.
References CVectorCore< CType >::array(), mPivot, and mRows.
                                    :
     CVector< CStepMatrixColumn * >(0),
     mRows(rows),
     mPivot(rows),
     mFirstUnconvertedRow(0)
 {
   size_t * pPivot = mPivot.array();
   for (size_t i = 0; i < mRows; ++i, ++pPivot)
     {
       *pPivot = i;
     }
 }
CStepMatrix::CStepMatrix (CMatrix< C_INT64 > & nullspaceMatrix)
Definition at line 47 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array(), CVectorCore< CType >::array(), CMatrix< CType >::array(), C_INT64, convertRow(), mBeyond, mFirstUnconvertedRow, mInsert, mPivot, mRows, CMatrix< CType >::numCols(), CStepMatrixColumn::push_front(), CVector< CStepMatrixColumn * >::resize(), and CMatrix< CType >::size().
                                                             :
     CVector< CStepMatrixColumn * >(0),
     mRows(nullspaceMatrix.numRows()),
     mPivot(nullspaceMatrix.numRows()),
     mFirstUnconvertedRow(0)
 {
   size_t Cols = nullspaceMatrix.numCols();
   resize(Cols);
   iterator it = array();
   mInsert = mBeyond = it + Cols;
   CVector< CStepMatrixColumn * > Columns(Cols);
   CStepMatrixColumn ** pColumn = Columns.array();
   CStepMatrixColumn ** pColumnEnd = pColumn + Cols;
   for (; pColumn != pColumnEnd; ++pColumn, ++it)
     {
       *pColumn = new CStepMatrixColumn(mRows);
       (*pColumn)->setIterator(it);
       *it = *pColumn;
     }
   size_t i;
   size_t j;
   const C_INT64 * pValue = nullspaceMatrix.array();
   size_t * pPivot = mPivot.array();
   std::vector< size_t > NegativeRows;
   bool hasNegative;
   bool hasPositive;
   for (i = 0; i < mRows; ++i, ++pPivot)
     {
       *pPivot = i;
       hasNegative = false;
       hasPositive = false;
       for (j = 0; j < Cols; ++j, ++pValue)
         {
           if (*pValue > 0)
             {
               hasPositive = true;
             }
           else if (*pValue < 0)
             {
               hasNegative = true;
             }
         }
       if ((!hasNegative && hasPositive))
         {
           convertRow(i, nullspaceMatrix);
         }
     }
   // We need to add the information of the unconverted rows of nullspace matrix
   // to the columns
   if (nullspaceMatrix.size() != 0 &&
       mFirstUnconvertedRow < mRows)
     {
       pValue = & nullspaceMatrix(mFirstUnconvertedRow, 0);
     }
   else
     {
       pValue = NULL;
     }
   for (i = mFirstUnconvertedRow; i < mRows; ++i)
     {
       pColumn = Columns.array();
       for (j = 0; j < Cols; ++j, ++pValue,  ++pColumn)
         {
           (*pColumn)->push_front(*pValue);
         }
     }
 }
CStepMatrix::~CStepMatrix ()
Definition at line 129 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array(), and mInsert.
 {
   iterator it = array();
   for (; it != mInsert; ++it)
     {
       if (*it != NULL)
         {
           delete *it;
         }
     }
 }
Member Function Documentation
void CStepMatrix::add (CStepMatrixColumn * pColumn) inline
Definition at line 50 of file CStepMatrix.h.
References CVectorCore< CStepMatrixColumn * >::array(), end(), max, mBeyond, mInsert, CVector< CStepMatrixColumn * >::resize(), CStepMatrixColumn::setIterator(), and CVectorCore< CStepMatrixColumn * >::size().
Referenced by addColumn(), and CBitPatternMethod::buildFluxModeMatrix().
   {
     if (pColumn != NULL)
       {
         if (mInsert >= mBeyond)
           {
             size_t OldSize = size();
             resize(std::max((size_t) 2, 2 * OldSize), true);
             mInsert = array() + OldSize;
             mBeyond = array() + size();
             memset(mInsert, 0x0, OldSize * sizeof(CStepMatrixColumn *));
             //We need to update the iterators.
             iterator it = array();
             iterator end = mInsert;
             for (; it != end; ++it)
               {
                 if (*it != NULL)
                   {
                     (*it)->setIterator(it);
                   }
               }
           }
         pColumn->setIterator(mInsert);
         *mInsert = pColumn;
         mInsert++;
       }
     return;
   }
CStepMatrixColumn * CStepMatrix::addColumn (const CZeroSet & set, const CStepMatrixColumn * pPositive, const CStepMatrixColumn * pNegative)
Add the linear combination of the two columns to the step matrix if appropriate and remove columns if necessary.
Parameters
const CZeroSet & set
const CStepMatrixColumn * pPositive
const CStepMatrixColumn * pNegative
Returns
CStepMatrixColumn * pColumn
Definition at line 181 of file CStepMatrix.cpp.
References add().
Referenced by CBitPatternTreeMethod::combine(), and CBitPatternMethod::combine().
 {
   CStepMatrixColumn * pColumn = new CStepMatrixColumn(set, pPositive, pNegative);
   add(pColumn);
   return pColumn;
 }
CStepMatrix::const_iterator CStepMatrix::begin () const
Definition at line 289 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array().
Referenced by CBitPatternTreeMethod::buildFluxModes(), CBitPatternMethod::buildFluxModes(), and operator<<().
 {
   return array();
 }
void CStepMatrix::compact ()
Definition at line 345 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array(), and mInsert.
Referenced by CBitPatternMethod::calculate(), and CBitPatternTreeMethod::calculate().
 {
   iterator from = array();
   iterator to = array();
   for (; from != mInsert; ++from)
     {
       if (*from != NULL)
         {
           (*from)->setIterator(to);
           *to = *from;
           ++to;
         }
     }
   mInsert = to;
 }
void CStepMatrix::convertRow ()
Definition at line 142 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array(), mFirstUnconvertedRow, and mInsert.
Referenced by CBitPatternMethod::calculate(), CBitPatternTreeMethod::calculate(), CStepMatrix(), and splitColumns().
 {
   CZeroSet::CIndex Index(mFirstUnconvertedRow);
   iterator it = array();
   for (; it != mInsert; ++it)
     {
       assert(*it != NULL);
       assert((*it)->getMultiplier() >= 0);
       if ((*it)->getMultiplier() > 0)
         {
           (*it)->unsetBit(Index);
         }
       (*it)->truncate();
     }
   mFirstUnconvertedRow++;
 }
void CStepMatrix::convertRow (const size_t & index, CMatrix< C_INT64 > & nullspaceMatrix) private
Definition at line 299 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array(), C_INT64, mFirstUnconvertedRow, mInsert, and mPivot.
 {
   CZeroSet::CIndex Index(mFirstUnconvertedRow);
   iterator it = array();
   C_INT64 * pValue = & nullspaceMatrix(index, 0);
   if (mFirstUnconvertedRow != index)
     {
       C_INT64 * pFirstUnconvertedValue = & nullspaceMatrix(mFirstUnconvertedRow, 0);
       for (; it != mInsert; ++it, ++pValue, ++pFirstUnconvertedValue)
         {
           // At this point the matrix is compact since no columns have been destroyed,
           // i.e., we do not need to check whether *it != NULL.
           assert(*pValue >= 0);
           if (*pValue > 0)
             {
               (*it)->unsetBit(Index);
             }
           *pValue = *pFirstUnconvertedValue;
         }
       // We need to remember the reordering.
       size_t tmp = mPivot[index];
       mPivot[index] = mPivot[mFirstUnconvertedRow];
       mPivot[mFirstUnconvertedRow] = tmp;
     }
   else
     {
       for (; it != mInsert; ++it, ++pValue)
         {
           if (*pValue != 0)
             {
               (*it)->unsetBit(Index);
             }
         }
     }
   mFirstUnconvertedRow++;
 }
CStepMatrix::const_iterator CStepMatrix::end () const
Definition at line 294 of file CStepMatrix.cpp.
References mInsert.
Referenced by add(), CBitPatternTreeMethod::buildFluxModes(), CBitPatternMethod::buildFluxModes(), operator<<(), and removeInvalidColumns().
 {
   return mInsert;
 }
void CStepMatrix::getAllUnsetBitIndexes (const CStepMatrixColumn * pColumn, CVector< size_t > & indexes) const
Definition at line 249 of file CStepMatrix.cpp.
References CVectorCore< CType >::array(), CStepMatrixColumn::getAllUnsetBitIndexes(), mPivot, and CVectorCore< CType >::size().
Referenced by CBitPatternMethod::getAllUnsetBitIndexes().
 {
   pColumn->getAllUnsetBitIndexes(indexes);
   // Apply the QR pivot
   size_t * pIndex = indexes.array();
   size_t * pIndexEnd = pIndex + indexes.size();
   for (; pIndex != pIndexEnd; ++pIndex)
     *pIndex = mPivot[*pIndex];
   //DebugFile << "@CSM: " << indexes << std::endl;
 }
size_t CStepMatrix::getFirstUnconvertedRow () const
Definition at line 171 of file CStepMatrix.cpp.
References mFirstUnconvertedRow.
Referenced by CBitPatternMethod::calculate(), and CBitPatternTreeMethod::calculate().
 {
   return mFirstUnconvertedRow;
 }
size_t CStepMatrix::getNumUnconvertedRows () const
Definition at line 176 of file CStepMatrix.cpp.
References mFirstUnconvertedRow, and mRows.
Referenced by CBitPatternMethod::calculate(), CBitPatternTreeMethod::calculate(), CBitPatternMethod::initialize(), and CBitPatternTreeMethod::initialize().
 {
   return mRows - mFirstUnconvertedRow;
 }
void CStepMatrix::getUnsetBitIndexes (const CStepMatrixColumn * pColumn, CVector< size_t > & indexes) const
Definition at line 264 of file CStepMatrix.cpp.
References CVectorCore< CType >::array(), CZeroSet::getNumberOfUnsetBits(), CStepMatrixColumn::getZeroSet(), CZeroSet::isSet(), mPivot, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by CBitPatternTreeMethod::getUnsetBitIndexes(), and CBitPatternMethod::getUnsetBitIndexes().
 {
   const CZeroSet & ZeroSet = pColumn->getZeroSet();
   indexes.resize(ZeroSet.getNumberOfUnsetBits());
   size_t * pIndex = indexes.array();
   size_t * pIndexEnd = pIndex + indexes.size();
   CZeroSet::CIndex Bit = 0;
   size_t Index = 0;
   for (; pIndex != pIndexEnd; ++Bit, ++Index)
     {
       if (!ZeroSet.isSet(Bit))
         {
           // Apply pivot.
           *pIndex = mPivot[Index];
           pIndex++;
         }
     }
   return;
 }
void CStepMatrix::removeColumn (CStepMatrixColumn * pColumn)
Definition at line 192 of file CStepMatrix.cpp.
Referenced by CBitPatternTreeMethod::combine(), CBitPatternMethod::combine(), and removeInvalidColumns().
 {
   delete pColumn;
 }
void CStepMatrix::removeInvalidColumns (std::vector< CStepMatrixColumn * > & invalidColumns)
Definition at line 238 of file CStepMatrix.cpp.
References end(), and removeColumn().
Referenced by CBitPatternMethod::calculate(), CBitPatternTreeMethod::calculate(), CBitPatternTreeMethod::findRemoveInvalidColumns(), and CBitPatternMethod::findRemoveInvalidColumns().
 {
   std::vector< CStepMatrixColumn * >::iterator it = invalidColumns.begin();
   std::vector< CStepMatrixColumn * >::iterator end = invalidColumns.end();
   for (; it != end; ++it)
     {
       removeColumn(*it);
     }
 }
bool CStepMatrix::splitColumns (std::vector< CStepMatrixColumn * > & PositiveColumns, std::vector< CStepMatrixColumn * > & NegativeColumns, std::vector< CStepMatrixColumn * > & NullColumns)
Definition at line 197 of file CStepMatrix.cpp.
References CVectorCore< CStepMatrixColumn * >::array(), C_INT64, convertRow(), and mInsert.
Referenced by CBitPatternMethod::calculate(), and CBitPatternTreeMethod::calculate().
 {
   assert(PositiveColumns.empty());
   assert(NegativeColumns.empty());
   assert(NullColumns.empty());
   iterator it = array();
   for (; it != mInsert; ++it)
     {
       assert(*it != NULL);
       const C_INT64 & Value = (*it)->getMultiplier();
       if (Value > 0)
         {
           PositiveColumns.push_back(*it);
         }
       else if (Value < 0)
         {
           NegativeColumns.push_back(*it);
         }
       else
         {
           NullColumns.push_back(*it);
         }
     }
   if (NegativeColumns.empty())
     {
       // We do not have any linear combinations, thus we can convert immediately
       convertRow();
       return false;
     }
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CStepMatrix & m) friend
Definition at line 364 of file CStepMatrix.cpp.
 {
   os << m.mPivot << std::endl;
   CZeroSet::CIndex Bit;
   CStepMatrix::const_iterator it;
   CStepMatrix::const_iterator end = m.end();
   for (it = m.begin(); it != end; ++it)
     {
       os << **it << std::endl;
     }
   return os;
 }
Member Data Documentation
iterator CStepMatrix::mBeyond private
Definition at line 138 of file CStepMatrix.h.
Referenced by add(), and CStepMatrix().
size_t CStepMatrix::mFirstUnconvertedRow private
Definition at line 134 of file CStepMatrix.h.
Referenced by convertRow(), CStepMatrix(), getFirstUnconvertedRow(), and getNumUnconvertedRows().
iterator CStepMatrix::mInsert private
Definition at line 136 of file CStepMatrix.h.
Referenced by add(), compact(), convertRow(), CStepMatrix(), end(), splitColumns(), and ~CStepMatrix().
CVector< size_t > CStepMatrix::mPivot private
Definition at line 132 of file CStepMatrix.h.
Referenced by convertRow(), CStepMatrix(), getAllUnsetBitIndexes(), getUnsetBitIndexes(), and operator<<().
size_t CStepMatrix::mRows private
Definition at line 130 of file CStepMatrix.h.
Referenced by CStepMatrix(), and getNumUnconvertedRows().
The documentation for this class was generated from the following files:
CStepMatrix.h
CStepMatrix.cpp