COPASI API: CLDimensions Class Reference
CLDimensions Class Reference
#include <CLBase.h>
Public Member Functions
CLDimensions ()
CLDimensions (const C_FLOAT64 &w, const C_FLOAT64 &h, const C_FLOAT64 &d=0.0)
CLDimensions (const Dimensions &d)
const C_FLOAT64 & getDepth () const
C_FLOAT64 & getDepth ()
const C_FLOAT64 & getHeight () const
C_FLOAT64 & getHeight ()
Dimensions getSBMLDimensions () const
const C_FLOAT64 & getWidth () const
C_FLOAT64 & getWidth ()
void scale (const double &scaleFactor)
void setDepth (const C_FLOAT64 &d)
void setHeight (const C_FLOAT64 &h)
void setWidth (const C_FLOAT64 &w)
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
C_FLOAT64 mDepth
C_FLOAT64 mHeight
C_FLOAT64 mWidth
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLDimensions &d)
Detailed Description
This class describes a size in a layout. It is 2-dimensional at the moment.
Definition at line 181 of file CLBase.h.
Constructor & Destructor Documentation
CLDimensions::CLDimensions () inline
Definition at line 190 of file CLBase.h.
                  :
     mWidth(0.0)
     , mHeight(0.0)
     , mDepth(0.0)
   {};
CLDimensions::CLDimensions (const C_FLOAT64 & w, const C_FLOAT64 & h, const C_FLOAT64 & d = 0.0) inline
Definition at line 197 of file CLBase.h.
                :
     mWidth(w)
     , mHeight(h)
     , mDepth(d)
   {};
CLDimensions::CLDimensions (const Dimensions & d)
constructor from libsbml object
Definition at line 37 of file CLBase.cpp.
                                               :
   mWidth(d.getWidth())
   , mHeight(d.getHeight())
   , mDepth(d.getDepth())
 {}
Member Function Documentation
const C_FLOAT64& CLDimensions::getDepth () const inline
Definition at line 213 of file CLBase.h.
References mDepth.
Referenced by CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::draw_ellipse(), and CLLayoutRenderer::draw_text().
 {return mDepth;};
C_FLOAT64& CLDimensions::getDepth () inline
Definition at line 217 of file CLBase.h.
References mDepth.
 {return mDepth;};
const C_FLOAT64& CLDimensions::getHeight () const inline
Definition at line 212 of file CLBase.h.
References mHeight.
Referenced by CLabel::adaptToHeight(), addToPath(), adjustPosition(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateBoundingBox(), CQGLNetworkPainter::checkCurve(), CLLayoutRenderer::convert_to_absolute(), CQGLNetworkPainter::createGraph(), CCopasiSpringLayout::createLayout(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), CLBoundingBox::getCenter(), getFont(), CLGraphicalObject::getHeight(), getLinearGradient(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), getPath(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), getRadialGradient(), CLBoundingBox::getSBMLBoundingBox(), CLLayoutRenderer::map_arrow_head(), moveToPoint(), compareGraphicalObjectsBySize::operator()(), randomlyPlaceGlyphInCompartmentGlyph(), randomlyPlaceGlyphInDimensions(), CCopasiXML::saveDimensions(), CCopasiXML::saveLayoutList(), CLLineEnding::toSBML(), and CLLayoutRenderer::update_textures_and_colors().
 {return mHeight;};
C_FLOAT64& CLDimensions::getHeight () inline
Definition at line 216 of file CLBase.h.
References mHeight.
 {return mHeight;};
Dimensions CLDimensions::getSBMLDimensions () const
convert to sbml dimension
Definition at line 43 of file CLBase.cpp.
References mDepth, mHeight, and mWidth.
Referenced by CLayout::exportToSBML().
 {
   Dimensions d(new LayoutPkgNamespaces()
                , mWidth
                , mHeight
                , mDepth
               );
   return d;
 }
const C_FLOAT64& CLDimensions::getWidth () const inline
Definition at line 211 of file CLBase.h.
References mWidth.
Referenced by CLabel::adaptToHeight(), addToPath(), adjustPosition(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateBoundingBox(), CQGLNetworkPainter::checkCurve(), CLLayoutRenderer::convert_to_absolute(), CQGLNetworkPainter::createGraph(), CCopasiSpringLayout::createLayout(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), CLBoundingBox::getCenter(), getLinearGradient(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), getPath(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), getRadialGradient(), CLBoundingBox::getSBMLBoundingBox(), CLGraphicalObject::getWidth(), CLLayoutRenderer::map_arrow_head(), moveToPoint(), compareGraphicalObjectsBySize::operator()(), randomlyPlaceGlyphInCompartmentGlyph(), randomlyPlaceGlyphInDimensions(), CCopasiXML::saveDimensions(), CCopasiXML::saveLayoutList(), CLLineEnding::toSBML(), and CLLayoutRenderer::update_textures_and_colors().
 {return mWidth;};
C_FLOAT64& CLDimensions::getWidth () inline
Definition at line 215 of file CLBase.h.
References mWidth.
 {return mWidth;};
void CLDimensions::scale (const double & scaleFactor) inline
Definition at line 223 of file CLBase.h.
References mDepth, mHeight, and mWidth.
Referenced by CLayout::scale(), and CLBoundingBox::scale().
   {
     mWidth *= scaleFactor;
     mHeight *= scaleFactor;
     mDepth *= scaleFactor;
   }
void CLDimensions::setDepth (const C_FLOAT64 & d) inline
Definition at line 221 of file CLBase.h.
References mDepth.
 {mDepth = d;};
void CLDimensions::setHeight (const C_FLOAT64 & h) inline
Definition at line 220 of file CLBase.h.
References mHeight.
Referenced by CQGLLayoutPainter::calculateAndAssignBounds(), and CLGraphicalObject::setHeight().
 {mHeight = h;};
void CLDimensions::setWidth (const C_FLOAT64 & w) inline
Definition at line 219 of file CLBase.h.
References mWidth.
Referenced by CQGLLayoutPainter::calculateAndAssignBounds(), and CLGraphicalObject::setWidth().
 {mWidth = w;};
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLDimensions & d) friend
insert operator
Definition at line 74 of file CLBase.cpp.
 {
   os << "(w=" << d.mWidth << ", h=" << d.mHeight << ")";
   return os;
 }
Member Data Documentation
C_FLOAT64 CLDimensions::mDepth protected
Definition at line 186 of file CLBase.h.
Referenced by getDepth(), getSBMLDimensions(), scale(), and setDepth().
C_FLOAT64 CLDimensions::mHeight protected
Definition at line 185 of file CLBase.h.
Referenced by getHeight(), getSBMLDimensions(), operator<<(), scale(), and setHeight().
C_FLOAT64 CLDimensions::mWidth protected
Definition at line 185 of file CLBase.h.
Referenced by getSBMLDimensions(), getWidth(), operator<<(), scale(), and setWidth().
The documentation for this class was generated from the following files:
CLBase.h
CLBase.cpp