COPASI API: CModelExpansion::ElementsMap Class Reference
CModelExpansion::ElementsMap Class Reference
#include <CModelExpansion.h>
Public Member Functions
void add (const CCopasiObject *source, CCopasiObject *copy)
add a source->duplicate mapping
bool exists (const CCopasiObject *source) const
does a copy of the source object exist?
bool exists (const std::string &sourceKey) const
std::string getDuplicateKey (const std::string &sourceKey) const
find the key of the duplicated object from the source object (if it exists)
CCopasiObject * getDuplicatePtr (const CCopasiObject *source) const
find the pointer of the duplicated object from the pointer to the source object (if it exists)
const std::map< const
CCopasiObject *, CCopasiObject * > & getMap () const
Protected Attributes
std::map< const CCopasiObject
*, CCopasiObject * > mMap
Detailed Description
This class contains a map from original to duplicated sets of model elements
Definition at line 90 of file CModelExpansion.h.
Member Function Documentation
void CModelExpansion::ElementsMap::add (const CCopasiObject * source, CCopasiObject * copy)
add a source->duplicate mapping
Definition at line 222 of file CModelExpansion.cpp.
Referenced by CQSpeciesDetail::copy(), ReactionsWidget1::copy(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), and CQMergingData::slotBtnMerge().
 {
   mMap[source] = copy;
 }
bool CModelExpansion::ElementsMap::exists (const CCopasiObject * source) const
does a copy of the source object exist?
Definition at line 209 of file CModelExpansion.cpp.
Referenced by CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CModelExpansion::replaceInMetab(), and CModelExpansion::updateExpression().
 {
   std::map<const CCopasiObject*, CCopasiObject*>::const_iterator it;
   it = mMap.find(source);
   return (it != mMap.end() && it->second != NULL);
 }
bool CModelExpansion::ElementsMap::exists (const std::string & sourceKey) const
Definition at line 216 of file CModelExpansion.cpp.
References CKeyFactory::get(), and CCopasiRootContainer::getKeyFactory().
 {
   const CCopasiObject* tmp = CCopasiRootContainer::getKeyFactory()->get(sourceKey);
   return exists(tmp);
 }
std::string CModelExpansion::ElementsMap::getDuplicateKey (const std::string & sourceKey) const
find the key of the duplicated object from the source object (if it exists)
Definition at line 238 of file CModelExpansion.cpp.
References CKeyFactory::get(), CCopasiObject::getKey(), and CCopasiRootContainer::getKeyFactory().
Referenced by CQSpeciesDetail::copy(), CQCompartment::copy(), ReactionsWidget1::copy(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateReaction(), CModelExpansion::replaceInEvent(), CModelExpansion::replaceInReaction(), and CModelExpansion::simpleCall().
 {
   const CCopasiObject* tmp = CCopasiRootContainer::getKeyFactory()->get(sourceKey);
   if (tmp)
     {
       const CCopasiObject* retObj = getDuplicatePtr(tmp);
       if (retObj)
         return retObj->getKey();
       else
         return "";
     }
   else
     return "";
 }
CCopasiObject * CModelExpansion::ElementsMap::getDuplicatePtr (const CCopasiObject * source) const
find the pointer of the duplicated object from the pointer to the source object (if it exists)
Definition at line 227 of file CModelExpansion.cpp.
Referenced by CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CModelExpansion::replaceInExpression(), CModelExpansion::replaceInMetab(), CModelExpansion::replaceInReaction(), and CModelExpansion::updateExpression().
 {
   std::map<const CCopasiObject*, CCopasiObject*>::const_iterator it;
   it = mMap.find(source);
   if (it != mMap.end())
     return it->second;
   else
     return NULL;
 }
const std::map< const CCopasiObject *, CCopasiObject * > & CModelExpansion::ElementsMap::getMap () const
Definition at line 255 of file CModelExpansion.cpp.
Referenced by CModelExpansion::copyCompleteModel(), and CModelExpansion::replaceInModel().
 {
   return mMap;
 }
Member Data Documentation
std::map<const CCopasiObject*, CCopasiObject*> CModelExpansion::ElementsMap::mMap protected
Definition at line 111 of file CModelExpansion.h.
The documentation for this class was generated from the following files:
CModelExpansion.h
CModelExpansion.cpp