COPASI API: CCopasiXMLParser::CurveElement Class Reference
CCopasiXMLParser::CurveElement Class Reference
Public Member Functions
CurveElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~CurveElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Curve = 0, ListOfCurveSegments, CurveSegment, Start,
End, BasePoint1, BasePoint2
}
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3288 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::CurveElement::Element private
Enumerator
Curve
ListOfCurveSegments
CurveSegment
Start
End
BasePoint1
BasePoint2
Definition at line 3291 of file CCopasiXMLParser.h.
     {
       Curve = 0,
       ListOfCurveSegments,
       CurveSegment,
       Start,
       End,
       BasePoint1,
       BasePoint2
     };
Constructor & Destructor Documentation
CCopasiXMLParser::CurveElement::CurveElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Definition at line 6294 of file CCopasiXMLParser.cpp.
                                                                                                    :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::CurveElement::~CurveElement () virtual
Definition at line 6299 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::CurveElement::end (const XML_Char * pszName) virtual
Definition at line 6442 of file CCopasiXMLParser.cpp.
References CLCurve::addCurveSegment(), CCopasiMessage::EXCEPTION, CLLineSegment::isBezier(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurve, SCopasiXMLParserCommon::pLineSegment, and START_ELEMENT.
 {
   if (!strcmp(pszName, "Curve"))
     {
       mParser.popElementHandler();
       mCurrentElement = START_ELEMENT;
       /* Tell the parent element we are done. */
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case ListOfCurveSegments:
             break;
           case CurveSegment:
             mCommon.pCurve->addCurveSegment(mCommon.pLineSegment);
             //tell the handler where to continue
             mCurrentElement = ListOfCurveSegments;
             break;
           case Start:
             break;
           case End:
             //tell the handler where to continue, depending on the type of the curve segment
             if (mCommon.pLineSegment && !mCommon.pLineSegment->isBezier())
               mCurrentElement = CurveSegment;
             break;
           case BasePoint1:
             break;
           case BasePoint2:
             mCurrentElement = CurveSegment;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::CurveElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Definition at line 6302 of file CCopasiXMLParser.cpp.
References C_FLOAT64, CLCurve::clear(), CCopasiMessage::EXCEPTION, fatalError, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurve, SCopasiXMLParserCommon::pLineSegment, CLLineSegment::setBase1(), CLLineSegment::setBase2(), CLLineSegment::setEnd(), CLLineSegment::setIsBezier(), CLLineSegment::setStart(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on hte next element */
   //  mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case Curve:
         if (strcmp(pszName, "Curve"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Curve", mParser.getCurrentLineNumber());
         if (!mCommon.pCurve) fatalError(); //pCurve must point to a curve of a reaction glyph
         //or a metab reference glyph
         mCommon.pCurve->clear();
         {
           //workload
           /*        mCommon.pReactionGlyph = new CLReactionGlyph(name);
                   CReaction * pReaction = dynamic_cast< CReaction * >(mCommon.KeyMap.get(reaction));
                   if (!pReaction) fatalError();
                   mCommon.pReactionGlyph->setModelObjectKey(pReaction->getKey());
                   mCommon.pCurrentLayout->addReactionGlyph(mCommon.pReactionGlyph);
                   addFix(key, mCommon.pReactionGlyph);*/
         }
         return;
         break;
       case ListOfCurveSegments:
         if (!strcmp(pszName, "ListOfCurveSegments"))
           return;
         break;
       case CurveSegment:
         if (!strcmp(pszName, "CurveSegment"))
           {
             //workload
             const char * type;
             type = mParser.getAttributeValue("xsi:type", papszAttrs);
             if (!mCommon.pLineSegment)
               mCommon.pLineSegment = new CLLineSegment;
             mCommon.pLineSegment->setIsBezier(!strcmp(type, "CubicBezier"));
           }
         return;
         break;
       case Start:
         if (!strcmp(pszName, "Start"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             C_FLOAT64 dX = CCopasiXMLInterface::DBL(attr);
             attr = mParser.getAttributeValue("y", papszAttrs);
             C_FLOAT64 dY = CCopasiXMLInterface::DBL(attr);
             mCommon.pLineSegment->setStart(CLPoint(dX, dY));
             return;
           }
         return;
         break;
       case End:
         if (!strcmp(pszName, "End"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             C_FLOAT64 dX = CCopasiXMLInterface::DBL(attr);
             attr = mParser.getAttributeValue("y", papszAttrs);
             C_FLOAT64 dY = CCopasiXMLInterface::DBL(attr);
             mCommon.pLineSegment->setEnd(CLPoint(dX, dY));
             return;
           }
         return;
         break;
       case BasePoint1:
         if (!strcmp(pszName, "BasePoint1"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             C_FLOAT64 dX = CCopasiXMLInterface::DBL(attr);
             attr = mParser.getAttributeValue("y", papszAttrs);
             C_FLOAT64 dY = CCopasiXMLInterface::DBL(attr);
             mCommon.pLineSegment->setBase1(CLPoint(dX, dY));
             return;
           }
         return;
         break;
       case BasePoint2:
         if (!strcmp(pszName, "BasePoint2"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             C_FLOAT64 dX = CCopasiXMLInterface::DBL(attr);
             attr = mParser.getAttributeValue("y", papszAttrs);
             C_FLOAT64 dY = CCopasiXMLInterface::DBL(attr);
             mCommon.pLineSegment->setBase2(CLPoint(dX, dY));
             return;
           }
         return;
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   //   if (mpCurrentHandler)
   //     mParser.pushElementHandler(mpCurrentHandler);
   //
   //   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::CurveElement::mLineNumber private
Definition at line 3302 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp