COPASI API: CLNAProblem.cpp File Reference
CLNAProblem.cpp File Reference
#include <string>
#include "copasi.h"
#include "CLNAProblem.h"
#include "CLNATask.h"
#include "steadystate/CSteadyStateTask.h"
#include "model/CModel.h"
#include "model/CState.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CKeyFactory.h"
#include "report/CCopasiRootContainer.h"
Functions
std::ostream & operator<< (std::ostream &os, const CLNAProblem &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CLNAProblem & o)
Output stream operator. Prints description of the problem incl. the subtask
Parameters
ostream & os
const CLNAProblem & A
Returns
ostream & os
Definition at line 158 of file CLNAProblem.cpp.
References CCopasiTask::getDescription(), CLNAProblem::getSubTask(), CLNAProblem::isSteadyStateRequested(), and CCopasiTask::CDescription::print().
 {
   os << "Problem Description:" << std::endl;
   if (o.isSteadyStateRequested())
     {
       os << "Calculation of a steady state is requested before the LNA." << std::endl << std::endl;
       if (o.getSubTask())
         {
           o.getSubTask()->getDescription().print(&os);
         }
       else
         {
           os << "However an error occurred. Please report this as a bug." << std::endl;
         }
     }
   else
     {
       os << "LNA is performed on the current state (which is not necessarily a steady state)." << std::endl;
     }
   os << std::endl;
   return os;
 }