COPASI API: CMiaseNotes Class Reference
CMiaseNotes Class Reference
#include <CMiaseBase.h>
Public Member Functions
CMiaseNotes ()
std::string getNotes ()
std::string getXmlNs ()
void setNotes (std::string notes)
void setXmlNs (std::string xmlNs)
~CMiaseNotes ()
Private Attributes
std::string mNotes
std::string mXmlNs
Detailed Description
Definition at line 20 of file CMiaseBase.h.
Constructor & Destructor Documentation
CMiaseNotes::CMiaseNotes ()
Definition at line 17 of file CMiaseBase.cpp.
 {}
CMiaseNotes::~CMiaseNotes ()
Definition at line 20 of file CMiaseBase.cpp.
 {}
Member Function Documentation
std::string CMiaseNotes::getNotes ()
Definition at line 23 of file CMiaseBase.cpp.
References mNotes.
Referenced by CMiaseParser::testDataStructure().
 {
   return mNotes;
 }
std::string CMiaseNotes::getXmlNs ()
Definition at line 33 of file CMiaseBase.cpp.
References mXmlNs.
 {
   return mXmlNs;
 }
void CMiaseNotes::setNotes (std::string notes)
Definition at line 28 of file CMiaseBase.cpp.
References mNotes.
Referenced by CMiaseParser::endElement().
 {
   mNotes = notes;
 }
void CMiaseNotes::setXmlNs (std::string xmlNs)
Definition at line 38 of file CMiaseBase.cpp.
References mXmlNs.
Referenced by CMiaseParser::newNotes().
 {
   mXmlNs = xmlNs;
 }
Member Data Documentation
std::string CMiaseNotes::mNotes private
Definition at line 37 of file CMiaseBase.h.
Referenced by getNotes(), and setNotes().
std::string CMiaseNotes::mXmlNs private
Definition at line 38 of file CMiaseBase.h.
Referenced by getXmlNs(), and setXmlNs().
The documentation for this class was generated from the following files:
CMiaseBase.h
CMiaseBase.cpp