COPASI API: test000076 Class Reference
test000076 Class Reference
#include <test000076.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1035_1 ()
void test_bug1035_2 ()
void test_bug1035_3 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1035_1)
CPPUNIT_TEST (test_bug1035_2)
CPPUNIT_TEST (test_bug1035_3)
CPPUNIT_TEST_SUITE (test000076)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 27 of file test000076.h.
Member Function Documentation
test000076::CPPUNIT_TEST (test_bug1035_1) private
test000076::CPPUNIT_TEST (test_bug1035_2) private
test000076::CPPUNIT_TEST (test_bug1035_3) private
test000076::CPPUNIT_TEST_SUITE (test000076) private
test000076::CPPUNIT_TEST_SUITE_END () private
void test000076::setUp ()
Test the export of models with references to local parameters in expressions.
Definition at line 47 of file test000076.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000076::tearDown ()
Definition at line 55 of file test000076.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000076::test_bug1035_1 ()
Definition at line 60 of file test000076.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000076::MODEL_STRING1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   std::string sbmlString;
   try
     {
       sbmlString = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       // fail if an uncaught exception occurs during export
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(!sbmlString.empty());
   // check if the exported SBML model has two parameters
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   const Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getListOfParameters()->size() == 2);
   const Parameter *pP1 = NULL, *pP2 = NULL;
   pP1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pP1 != NULL);
   if (pP1->getName() != std::string("K"))
     {
       pP2 = pP1;
       pP1 = pModel->getParameter(1);
     }
   else
     {
       pP2 = pModel->getParameter(1);
     }
   CPPUNIT_ASSERT(pP2->getName() == std::string("reaction_k1"));
   CPPUNIT_ASSERT(pP2->getConstant() == true);
   CPPUNIT_ASSERT(fabs((pP2->getValue() - 0.1) / 0.1) < 1e-6);
   CPPUNIT_ASSERT(pP1->getName() == std::string("K"));
   CPPUNIT_ASSERT(pP1->getConstant() == false);
   CPPUNIT_ASSERT(fabs((pP1->getValue() - 0.1) / 0.1) < 1e-6);
   // check there is exactly one rule
   CPPUNIT_ASSERT(pModel->getListOfRules()->size() == 1);
   const Rule* pRule = pModel->getRule(0);
   CPPUNIT_ASSERT(pRule != NULL);
   const AssignmentRule* pAssignmentRule = dynamic_cast<const AssignmentRule*>(pRule);
   CPPUNIT_ASSERT(pAssignmentRule != NULL);
   CPPUNIT_ASSERT(pAssignmentRule->getVariable() == pP1->getId());
   const ASTNode* pMath = pAssignmentRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == std::string(pP2->getId()));
   // now check the reaction
   CPPUNIT_ASSERT(pModel->getListOfReactions()->size() == 1);
   const Reaction* pReaction = pModel->getReaction(0);
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pReaction->getListOfModifiers()->size() == 0);
   const KineticLaw* pKLaw = pReaction->getKineticLaw();
   CPPUNIT_ASSERT(pKLaw != NULL);
   CPPUNIT_ASSERT(pKLaw->getListOfParameters()->size() == 0);
   const SpeciesReference* pSpeciesReference = pReaction->getReactant(0);
   CPPUNIT_ASSERT(pSpeciesReference != NULL);
   CPPUNIT_ASSERT(pModel->getListOfCompartments()->size() == 1);
   const Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment != NULL);
   pMath = pKLaw->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // check that the expression is the compartment times the substrate times the
   // parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   std::vector<std::string> ids;
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2 || pMath->getNumChildren() == 3);
   if (pMath->getNumChildren() == 3)
     {
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(2)->getType() == AST_NAME);
       ids.push_back(pMath->getChild(0)->getName());
       ids.push_back(pMath->getChild(1)->getName());
       ids.push_back(pMath->getChild(2)->getName());
     }
   else
     {
       if (pMath->getChild(0)->getType() == AST_NAME)
         {
           ids.push_back(pMath->getChild(0)->getName());
           pMath = pMath->getChild(1);
         }
       else
         {
           CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
           ids.push_back(pMath->getChild(1)->getName());
           pMath = pMath->getChild(0);
         }
       CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
       CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
       ids.push_back(pMath->getChild(0)->getName());
       ids.push_back(pMath->getChild(1)->getName());
     }
   CPPUNIT_ASSERT(ids.size() == 3);
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pCompartment->getId())) != ids.end());
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pP2->getId())) != ids.end());
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pSpeciesReference->getSpecies())) != ids.end());
 }
void test000076::test_bug1035_2 ()
Definition at line 180 of file test000076.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING2, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000076::MODEL_STRING2);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   std::string sbmlString;
   try
     {
       // we need to export to Level 2 Version 3 because of the initial assignment
       sbmlString = pDataModel->exportSBMLToString(NULL, 2, 3);
     }
   catch (...)
     {
       // fail if any exception occurs during the export
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(!sbmlString.empty());
   // check if the exported SBML model has two parameters
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   const Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getListOfParameters()->size() == 2);
   const Parameter *pP1 = NULL, *pP2 = NULL;
   pP1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pP1 != NULL);
   if (pP1->getName() != std::string("K"))
     {
       pP2 = pP1;
       pP1 = pModel->getParameter(1);
     }
   else
     {
       pP2 = pModel->getParameter(1);
     }
   CPPUNIT_ASSERT(pP2->getName() == std::string("reaction_k1"));
   CPPUNIT_ASSERT(pP2->getConstant() == true);
   CPPUNIT_ASSERT(fabs((pP2->getValue() - 0.1) / 0.1) < 1e-6);
   CPPUNIT_ASSERT(pP1->getName() == std::string("K"));
   CPPUNIT_ASSERT(pP1->getConstant() == true);
   CPPUNIT_ASSERT(fabs((pP1->getValue() - 0.1) / 0.1) < 1e-6);
   // check there is exactly one initial assignment
   CPPUNIT_ASSERT(pModel->getListOfInitialAssignments()->size() == 1);
   const InitialAssignment* pAssignment = pModel->getInitialAssignment(0);
   CPPUNIT_ASSERT(pAssignment != NULL);
   CPPUNIT_ASSERT(pAssignment->getSymbol() == pP1->getId());
   const ASTNode* pMath = pAssignment->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == std::string(pP2->getId()));
   // now check the reaction
   CPPUNIT_ASSERT(pModel->getListOfReactions()->size() == 1);
   const Reaction* pReaction = pModel->getReaction(0);
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pReaction->getListOfModifiers()->size() == 0);
   const KineticLaw* pKLaw = pReaction->getKineticLaw();
   CPPUNIT_ASSERT(pKLaw != NULL);
   CPPUNIT_ASSERT(pKLaw->getListOfParameters()->size() == 0);
   const SpeciesReference* pSpeciesReference = pReaction->getReactant(0);
   CPPUNIT_ASSERT(pSpeciesReference != NULL);
   CPPUNIT_ASSERT(pModel->getListOfCompartments()->size() == 1);
   const Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment != NULL);
   pMath = pKLaw->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // check that the expression is the compartment times the substrate times the
   // parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   std::vector<std::string> ids;
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2 || pMath->getNumChildren() == 3);
   if (pMath->getNumChildren() == 3)
     {
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(2)->getType() == AST_NAME);
       ids.push_back(pMath->getChild(0)->getName());
       ids.push_back(pMath->getChild(1)->getName());
       ids.push_back(pMath->getChild(2)->getName());
     }
   else
     {
       if (pMath->getChild(0)->getType() == AST_NAME)
         {
           ids.push_back(pMath->getChild(0)->getName());
           pMath = pMath->getChild(1);
         }
       else
         {
           CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
           ids.push_back(pMath->getChild(1)->getName());
           pMath = pMath->getChild(0);
         }
       CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
       CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
       ids.push_back(pMath->getChild(0)->getName());
       ids.push_back(pMath->getChild(1)->getName());
     }
   CPPUNIT_ASSERT(ids.size() == 3);
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pCompartment->getId())) != ids.end());
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pP2->getId())) != ids.end());
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pSpeciesReference->getSpecies())) != ids.end());
 }
void test000076::test_bug1035_3 ()
Definition at line 301 of file test000076.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING3, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000076::MODEL_STRING3);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   std::string sbmlString;
   try
     {
       sbmlString = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       // fail if an uncaught exception occurs during export
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(!sbmlString.empty());
   // check if the exported SBML model has two parameters
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   const Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getListOfParameters()->size() == 1);
   const Parameter *pP1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pP1 != NULL);
   CPPUNIT_ASSERT(pP1->getName() == std::string("K"));
   CPPUNIT_ASSERT(pP1->getConstant() == true);
   CPPUNIT_ASSERT(fabs((pP1->getValue() - 0.1) / 0.1) < 1e-6);
   // check there are no rules and no initial assignments
   CPPUNIT_ASSERT(pModel->getListOfRules()->size() == 0);
   CPPUNIT_ASSERT(pModel->getListOfInitialAssignments()->size() == 0);
   // now check the reaction
   CPPUNIT_ASSERT(pModel->getListOfReactions()->size() == 1);
   const Reaction* pReaction = pModel->getReaction(0);
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pReaction->getListOfModifiers()->size() == 0);
   const KineticLaw* pKLaw = pReaction->getKineticLaw();
   CPPUNIT_ASSERT(pKLaw != NULL);
   CPPUNIT_ASSERT(pKLaw->getListOfParameters()->size() == 1);
   pP1 = pKLaw->getParameter(0);
   CPPUNIT_ASSERT(pP1 != NULL);
   CPPUNIT_ASSERT(pP1->getId() == std::string("k1"));
   const SpeciesReference* pSpeciesReference = pReaction->getReactant(0);
   CPPUNIT_ASSERT(pSpeciesReference != NULL);
   CPPUNIT_ASSERT(pModel->getListOfCompartments()->size() == 1);
   const Compartment* pCompartment = pModel->getCompartment(0);
   CPPUNIT_ASSERT(pCompartment != NULL);
   const ASTNode* pMath = pKLaw->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // check that the expression is the compartment times the substrate times the
   // local parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   std::vector<std::string> ids;
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2 || pMath->getNumChildren() == 3);
   if (pMath->getNumChildren() == 3)
     {
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(2)->getType() == AST_NAME);
       ids.push_back(pMath->getChild(0)->getName());
       ids.push_back(pMath->getChild(1)->getName());
       ids.push_back(pMath->getChild(2)->getName());
     }
   else
     {
       if (pMath->getChild(0)->getType() == AST_NAME)
         {
           ids.push_back(pMath->getChild(0)->getName());
           pMath = pMath->getChild(1);
         }
       else
         {
           CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
           ids.push_back(pMath->getChild(1)->getName());
           pMath = pMath->getChild(0);
         }
       CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
       CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getChild(1)->getType() == AST_NAME);
       ids.push_back(pMath->getChild(0)->getName());
       ids.push_back(pMath->getChild(1)->getName());
     }
   CPPUNIT_ASSERT(ids.size() == 3);
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pCompartment->getId())) != ids.end());
   // make sure the local parameter is multiplied in
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pP1->getId())) != ids.end());
   CPPUNIT_ASSERT(std::find(ids.begin(), ids.end(), std::string(pSpeciesReference->getSpecies())) != ids.end());
 }
Member Data Documentation
const char * test000076::MODEL_STRING1 static protected
Definition at line 37 of file test000076.h.
Referenced by test_bug1035_1().
const char * test000076::MODEL_STRING2 static protected
Definition at line 38 of file test000076.h.
Referenced by test_bug1035_2().
const char * test000076::MODEL_STRING3 static protected
Definition at line 39 of file test000076.h.
Referenced by test_bug1035_3().
CCopasiDataModel * test000076::pCOPASIDATAMODEL = NULL static protected
Definition at line 36 of file test000076.h.
Referenced by setUp(), test_bug1035_1(), test_bug1035_2(), and test_bug1035_3().
The documentation for this class was generated from the following files:
test000076.h
test000076.cpp