COPASI API: CSensProblem Class Reference
CSensProblem Class Reference
#include <CSensProblem.h>
Public Types
enum SubTaskType {
Evaluation, SteadyState, TimeSeries, ParameterEstimation,
Optimization, CrossSection
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
void addVariables (const CSensItem &item)
void changeTargetFunctions (const CSensItem item)
bool changeVariables (size_t index, const CSensItem &item)
bool collapsRequested () const
CSensProblem (const CCopasiContainer *pParent=NULL)
CSensProblem (const CSensProblem &src, const CCopasiContainer *pParent=NULL)
CCopasiArray & getCollapsedResult ()
const CCopasiArray & getCollapsedResult () const
CArrayAnnotation * getCollapsedResultAnnotated ()
const CArrayAnnotation * getCollapsedResultAnnotated () const
size_t getNumberOfVariables () const
CCopasiArray & getResult ()
const CCopasiArray & getResult () const
CArrayAnnotation * getResultAnnotated ()
const CArrayAnnotation * getResultAnnotated () const
CCopasiArray & getScaledResult ()
const CCopasiArray & getScaledResult () const
CArrayAnnotation * getScaledResultAnnotated ()
const CArrayAnnotation * getScaledResultAnnotated () const
CSensProblem::SubTaskType getSubTaskType () const
CSensItem getTargetFunctions () const
CSensItem getVariables (size_t index) const
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
bool removeVariables (size_t index)
bool removeVariables ()
void setSubTaskType (const CSensProblem::SubTaskType &type)
virtual ~CSensProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual bool initialize ()
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setModel (CModel *pModel)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static std::vector
< CObjectLists::ListType > getPossibleTargetFunctions (CSensProblem::SubTaskType)
static std::vector
< CObjectLists::ListType > getPossibleVariables (CSensProblem::SubTaskType)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes
static const std::string SubTaskName []
static const char * XMLSubTask []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Private Member Functions
void initDebugProblem ()
void initObjects ()
Static Private Member Functions
static void copyParameterGroupToSensItem (const CCopasiParameterGroup *pg, CSensItem *si)
static void copySensItemToParameterGroup (const CSensItem *si, CCopasiParameterGroup *pg)
static void createParametersInGroup (CCopasiParameterGroup *pg)
Private Attributes
CCopasiArray mCollapsedResult
CArrayAnnotation * mpCollapsedResultAnnotation
CArrayAnnotation * mpResultAnnotation
CArrayAnnotation * mpScaledResultAnnotation
CSensProblem::SubTaskType * mpSubTaskType
CCopasiParameterGroup * mpTargetFunctions
CCopasiParameterGroup * mpVariablesGroup
CCopasiArray mResult
CCopasiArray mScaledResult
Friends
std::ostream & operator<< (std::ostream &os, const CSensProblem &o)
Additional Inherited Members
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CSensProblem class.
Definition at line 64 of file CSensProblem.h.
Member Enumeration Documentation
enum CSensProblem::SubTaskType
this enumeration
Enumerator
Evaluation
SteadyState
TimeSeries
ParameterEstimation
Optimization
CrossSection
Definition at line 71 of file CSensProblem.h.
   {
     Evaluation,
     SteadyState,
     TimeSeries,
     ParameterEstimation,
     Optimization,
     CrossSection
     //LyapunovExp
   };
Constructor & Destructor Documentation
CSensProblem::CSensProblem (const CCopasiContainer * pParent = NULL)
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
Default constructor.
Parameters
CModel * pModel
Definition at line 192 of file CSensProblem.cpp.
References CCopasiParameterGroup::addGroup(), CCopasiParameterGroup::addParameter(), addVariables(), CObjectLists::ALL_PARAMETER_VALUES, C_INT32, changeTargetFunctions(), CONSTRUCTOR_TRACE, createParametersInGroup(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), initObjects(), mpSubTaskType, mpTargetFunctions, mpVariablesGroup, CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CCopasiParameter::Value::pUINT, CSensItem::setListType(), setSubTaskType(), SteadyState, and CCopasiParameter::UINT.
                                                           :
   CCopasiProblem(CCopasiTask::sens, pParent),
   mpSubTaskType(NULL),
   mpTargetFunctions(NULL),
   mpVariablesGroup(NULL),
   mpResultAnnotation(NULL),
   mpScaledResultAnnotation(NULL),
   mpCollapsedResultAnnotation(NULL)
 {
   addParameter("SubtaskType", CCopasiParameter::UINT, (unsigned C_INT32) 0);
   mpSubTaskType = (CSensProblem::SubTaskType*)getValue("SubtaskType").pUINT;
   //---------------------------------------------------
   addGroup("TargetFunctions");
   mpTargetFunctions = dynamic_cast<CCopasiParameterGroup*>(getParameter("TargetFunctions"));
   createParametersInGroup(mpTargetFunctions);
   //---------------------------------------------------
   addGroup("ListOfVariables");
   mpVariablesGroup = dynamic_cast<CCopasiParameterGroup*>(getParameter("ListOfVariables"));
   //create a useful default problem
   setSubTaskType(SteadyState);
   CSensItem item;
   item.setListType(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
   changeTargetFunctions(item);
   item.setListType(CObjectLists::ALL_PARAMETER_VALUES);
   addVariables(item);
   //  initDebugProblem();
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CSensProblem::CSensProblem (const CSensProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CSensProblem & src CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CSensProblem & src
Definition at line 233 of file CSensProblem.cpp.
References CONSTRUCTOR_TRACE, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), initObjects(), mpSubTaskType, mpTargetFunctions, mpVariablesGroup, and CCopasiParameter::Value::pUINT.
                                                             :
   CCopasiProblem(src, pParent),
   mpSubTaskType(NULL),
   mpTargetFunctions(NULL),
   mpVariablesGroup(NULL),
   mpResultAnnotation(NULL),
   mpScaledResultAnnotation(NULL),
   mpCollapsedResultAnnotation(NULL)
 {
   mpSubTaskType = (CSensProblem::SubTaskType*)getValue("SubtaskType").pUINT;
   mpTargetFunctions = dynamic_cast<CCopasiParameterGroup*>(getParameter("TargetFunctions"));
   mpVariablesGroup = dynamic_cast<CCopasiParameterGroup*>(getParameter("ListOfVariables"));
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CSensProblem::~CSensProblem () virtual
Destructor.
Definition at line 269 of file CSensProblem.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
void CSensProblem::addVariables (const CSensItem & item)
Definition at line 324 of file CSensProblem.cpp.
References CCopasiParameterGroup::addGroup(), copySensItemToParameterGroup(), createParametersInGroup(), getNumberOfVariables(), CCopasiParameterGroup::getParameter(), and mpVariablesGroup.
Referenced by changeVariables(), CSensProblem(), initDebugProblem(), and SensitivitiesWidget::saveTask().
 {
   //create parameter group corresponding to sens item
   CCopasiParameterGroup* tmp;
   mpVariablesGroup->addGroup("Variables");
   tmp = (CCopasiParameterGroup*)(mpVariablesGroup->getParameter(getNumberOfVariables() - 1));
   createParametersInGroup(tmp);
   copySensItemToParameterGroup(&item, tmp);
 }
void CSensProblem::changeTargetFunctions (const CSensItem item)
Definition at line 302 of file CSensProblem.cpp.
References copySensItemToParameterGroup(), and mpTargetFunctions.
Referenced by CSensProblem(), and SensitivitiesWidget::saveTask().
 {
   copySensItemToParameterGroup(&item, mpTargetFunctions);
 }
bool CSensProblem::changeVariables (size_t index, const CSensItem & item)
Definition at line 351 of file CSensProblem.cpp.
References addVariables(), copySensItemToParameterGroup(), getNumberOfVariables(), CCopasiParameterGroup::getParameter(), and mpVariablesGroup.
 {
   size_t num = getNumberOfVariables();
   if (index > num)
     return false;
   if (index == num)
     addVariables(item);
   else
     {
       CCopasiParameterGroup * tmp =
         (CCopasiParameterGroup *)(mpVariablesGroup->getParameter(index));
       copySensItemToParameterGroup(&item, tmp);
     }
   return true;
 }
bool CSensProblem::collapsRequested () const
Definition at line 430 of file CSensProblem.cpp.
References getTargetFunctions(), and CSensItem::isSingleObject().
Referenced by CSensMethod::do_collapsing(), CSensMethod::initialize(), and CQSensResultWidget::newResult().
 {
   return !getTargetFunctions().isSingleObject();
 }
void CSensProblem::copyParameterGroupToSensItem (const CCopasiParameterGroup * pg, CSensItem * si) static private
Definition at line 166 of file CSensProblem.cpp.
References CCopasiParameterGroup::getValue(), CCopasiParameter::Value::pCN, CCopasiParameter::Value::pUINT, CSensItem::setListType(), and CSensItem::setSingleObjectCN().
Referenced by getTargetFunctions(), and getVariables().
 {
   if (!pg) return; if (!si) return;
   CCopasiObjectName* pCN = pg->getValue("SingleObject").pCN;
   CObjectLists::ListType* pLT = (CObjectLists::ListType*)pg->getValue("ObjectListType").pUINT;
   CCopasiObjectName cn("");
   if (pCN) cn = *pCN;
   CObjectLists::ListType lt = (CObjectLists::ListType)0;
   if (pLT) lt = *pLT;
   //  if (cn != "")
   si->setSingleObjectCN(cn);
   //  else
   si->setListType(lt);
 }
void CSensProblem::copySensItemToParameterGroup (const CSensItem * si, CCopasiParameterGroup * pg) static private
Definition at line 152 of file CSensProblem.cpp.
References C_INT32, CSensItem::getListType(), CSensItem::getSingleObjectCN(), CSensItem::isSingleObject(), and CCopasiParameterGroup::setValue().
Referenced by addVariables(), changeTargetFunctions(), and changeVariables().
 {
   CCopasiObjectName cn("");
   if (!pg) return; if (!si) return;
   if (si->isSingleObject())
     cn = si->getSingleObjectCN();
   pg->setValue("SingleObject", cn);
   pg->setValue("ObjectListType", (unsigned C_INT32)si->getListType());
 }
void CSensProblem::createParametersInGroup (CCopasiParameterGroup * pg) static private
create the copasi parameters corresponding to the members of a CSensItem
Definition at line 143 of file CSensProblem.cpp.
References CCopasiParameterGroup::addParameter(), C_INT32, CCopasiParameter::CN, and CCopasiParameter::UINT.
Referenced by addVariables(), and CSensProblem().
 {
   if (!pg) return;
   pg->addParameter("SingleObject", CCopasiParameter::CN, CCopasiObjectName(""));
   pg->addParameter("ObjectListType", CCopasiParameter::UINT, (unsigned C_INT32) 0);
 }
CCopasiArray & CSensProblem::getCollapsedResult ()
Definition at line 410 of file CSensProblem.cpp.
References mCollapsedResult.
Referenced by CSensMethod::do_collapsing(), and CSensMethod::initialize().
 {
   return mCollapsedResult;
 }
const CCopasiArray & CSensProblem::getCollapsedResult () const
Definition at line 415 of file CSensProblem.cpp.
References mCollapsedResult.
 {
   return mCollapsedResult;
 }
CArrayAnnotation * CSensProblem::getCollapsedResultAnnotated ()
Definition at line 420 of file CSensProblem.cpp.
References mpCollapsedResultAnnotation.
Referenced by CSensMethod::initialize(), and CQSensResultWidget::newResult().
 {
   return mpCollapsedResultAnnotation;
 }
const CArrayAnnotation * CSensProblem::getCollapsedResultAnnotated () const
Definition at line 425 of file CSensProblem.cpp.
References mpCollapsedResultAnnotation.
 {
   return mpCollapsedResultAnnotation;
 }
size_t CSensProblem::getNumberOfVariables () const
Definition at line 307 of file CSensProblem.cpp.
References mpVariablesGroup, and CCopasiParameterGroup::size().
Referenced by addVariables(), changeVariables(), CSensMethod::initialize(), SensitivitiesWidget::loadTask(), and operator<<().
 {
   return mpVariablesGroup->size();
 }
std::vector< CObjectLists::ListType > CSensProblem::getPossibleTargetFunctions (CSensProblem::SubTaskType type) static
Definition at line 437 of file CSensProblem.cpp.
References CObjectLists::ALL_VARIABLES, CrossSection, Evaluation, CObjectLists::GLOBAL_PARAMETER_RATES, CObjectLists::METAB_CONC_RATES, CObjectLists::METAB_PART_RATES, CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES, CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CObjectLists::NON_CONST_METAB_NUMBERS, Optimization, ParameterEstimation, CObjectLists::REACTION_CONC_FLUXES, CObjectLists::REACTION_PART_FLUXES, CObjectLists::REDUCED_JACOBIAN_EV_IM, CObjectLists::REDUCED_JACOBIAN_EV_RE, CObjectLists::SINGLE_OBJECT, SteadyState, and TimeSeries.
Referenced by SensitivitiesWidget::updateComboBoxes().
 {
   std::vector<CObjectLists::ListType> list;
   //list.push_back(CObjectLists::EMPTY_LIST);
   // Add new functions here, under applicable SubTaskType case.
   // Don't forget to provide for a string value in
   //   getTargetFunctionName()
   switch (type)
     {
       case (CSensProblem::Evaluation):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::REACTION_CONC_FLUXES);
         list.push_back(CObjectLists::REACTION_PART_FLUXES);
         list.push_back(CObjectLists::METAB_CONC_RATES);
         list.push_back(CObjectLists::METAB_PART_RATES);
         list.push_back(CObjectLists::GLOBAL_PARAMETER_RATES);
         break;
       case (CSensProblem::SteadyState):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::ALL_VARIABLES);
         list.push_back(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
         list.push_back(CObjectLists::NON_CONST_METAB_NUMBERS);
         list.push_back(CObjectLists::METAB_CONC_RATES);
         list.push_back(CObjectLists::METAB_PART_RATES);
         list.push_back(CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::REACTION_CONC_FLUXES);
         list.push_back(CObjectLists::REACTION_PART_FLUXES);
         list.push_back(CObjectLists::REDUCED_JACOBIAN_EV_RE);
         list.push_back(CObjectLists::REDUCED_JACOBIAN_EV_IM);
         break;
       case (CSensProblem::TimeSeries):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::ALL_VARIABLES);
         list.push_back(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
         list.push_back(CObjectLists::NON_CONST_METAB_NUMBERS);
         list.push_back(CObjectLists::METAB_CONC_RATES);
         list.push_back(CObjectLists::METAB_PART_RATES);
         list.push_back(CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::REACTION_CONC_FLUXES);
         list.push_back(CObjectLists::REACTION_PART_FLUXES);
         //TODO all model variables
         break;
       case (CSensProblem::ParameterEstimation):
       case (CSensProblem::Optimization):
       case (CSensProblem::CrossSection):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         break;
         /*case (CSensProblem::LyapunovExp):
                 list.push_back(CObjectLists::SINGLE_OBJECT);
                 list.push_back(CObjectLists::NON_CONST_METAB_NUMBERS);
                 list.push_back(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
                 list.push_back(CObjectLists::REACTION_CONC_FLUXES);
                 list.push_back(CObjectLists::NON_CONST_METAB_PART_RATES);
           break;*/
     }
   return list;
 }
std::vector< CObjectLists::ListType > CSensProblem::getPossibleVariables (CSensProblem::SubTaskType type) static
Definition at line 504 of file CSensProblem.cpp.
References CObjectLists::ALL_LOCAL_PARAMETER_VALUES, CObjectLists::ALL_PARAMETER_AND_INITIAL_VALUES, CObjectLists::ALL_PARAMETER_VALUES, CrossSection, Evaluation, CObjectLists::GLOBAL_PARAMETER_VALUES, CObjectLists::METAB_CONCENTRATIONS, CObjectLists::METAB_INITIAL_CONCENTRATIONS, CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES, CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CObjectLists::NON_CONST_METAB_NUMBERS, Optimization, ParameterEstimation, CObjectLists::SINGLE_OBJECT, SteadyState, and TimeSeries.
Referenced by SensitivitiesWidget::updateComboBoxes().
 {
   std::vector<CObjectLists::ListType> list;
   // the 'unset' type, abusing CObjectLists::ALL_METABS
   list.push_back((CObjectLists::ListType) 0);
   // Add new variables here, to applicable SubTaskType case.
   // Don't forget to provide for a string value in
   //   getVariableName()
   switch (type)
     {
       case (Evaluation):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
         list.push_back(CObjectLists::METAB_CONCENTRATIONS);
         list.push_back(CObjectLists::NON_CONST_METAB_NUMBERS);
         list.push_back(CObjectLists::NON_CONST_GLOBAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::GLOBAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::ALL_LOCAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::ALL_PARAMETER_VALUES);
         break;
       case (SteadyState):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::ALL_LOCAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::ALL_PARAMETER_VALUES);
         list.push_back(CObjectLists::METAB_INITIAL_CONCENTRATIONS);
         //TODO all const values, all model parameters
         break;
       case (TimeSeries):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::ALL_LOCAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::ALL_PARAMETER_VALUES);
         list.push_back(CObjectLists::METAB_INITIAL_CONCENTRATIONS);
         list.push_back(CObjectLists::ALL_PARAMETER_AND_INITIAL_VALUES);
         //TODO all const values, all model parameters, all initial values
         break;
       case (CSensProblem::ParameterEstimation):
       case (CSensProblem::Optimization):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::ALL_LOCAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::ALL_PARAMETER_VALUES);
         list.push_back(CObjectLists::METAB_INITIAL_CONCENTRATIONS);
         list.push_back(CObjectLists::ALL_PARAMETER_AND_INITIAL_VALUES);
         break;
       case (CSensProblem::CrossSection):
         list.push_back(CObjectLists::SINGLE_OBJECT);
         list.push_back(CObjectLists::ALL_LOCAL_PARAMETER_VALUES);
         list.push_back(CObjectLists::ALL_PARAMETER_VALUES);
         list.push_back(CObjectLists::METAB_INITIAL_CONCENTRATIONS);
         list.push_back(CObjectLists::ALL_PARAMETER_AND_INITIAL_VALUES);
         break;
         /*case (LyapunovExp):
                 list.push_back(CObjectLists::SINGLE_OBJECT);
                 list.push_back(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
                 list.push_back(CObjectLists::GLOBAL_PARAMETER_VALUES);
                 list.push_back(CObjectLists::ALL_LOCAL_PARAMETER_VALUES);
                 list.push_back(CObjectLists::ALL_PARAMETER_VALUES);
                 list.push_back(CObjectLists::ALL_PARAMETER_AND_INITIAL_VALUES);
           break;*/
     }
   return list;
 }
CCopasiArray & CSensProblem::getResult ()
Definition at line 370 of file CSensProblem.cpp.
References mResult.
Referenced by CSensMethod::do_scaling(), CSensMethod::initialize(), CSensMethod::process(), and CSensMethod::scaling_targetfunction().
 {
   return mResult;
 }
const CCopasiArray & CSensProblem::getResult () const
Definition at line 375 of file CSensProblem.cpp.
References mResult.
 {
   return mResult;
 }
CArrayAnnotation * CSensProblem::getResultAnnotated ()
Definition at line 380 of file CSensProblem.cpp.
References mpResultAnnotation.
Referenced by CQSensResultWidget::enterProtected(), CSensMethod::initialize(), and CQSensResultWidget::newResult().
 {
   return mpResultAnnotation;
 }
const CArrayAnnotation * CSensProblem::getResultAnnotated () const
Definition at line 385 of file CSensProblem.cpp.
References mpResultAnnotation.
 {
   return mpResultAnnotation;
 }
CCopasiArray & CSensProblem::getScaledResult ()
Definition at line 390 of file CSensProblem.cpp.
References mScaledResult.
Referenced by CSensMethod::do_collapsing(), CSensMethod::do_collapsing_innerloop(), CSensMethod::initialize(), and CSensMethod::scaling_targetfunction().
 {
   return mScaledResult;
 }
const CCopasiArray & CSensProblem::getScaledResult () const
Definition at line 395 of file CSensProblem.cpp.
References mScaledResult.
 {
   return mScaledResult;
 }
CArrayAnnotation * CSensProblem::getScaledResultAnnotated ()
Definition at line 400 of file CSensProblem.cpp.
References mpScaledResultAnnotation.
Referenced by CSensMethod::initialize(), and CQSensResultWidget::newResult().
 {
   return mpScaledResultAnnotation;
 }
const CArrayAnnotation * CSensProblem::getScaledResultAnnotated () const
Definition at line 405 of file CSensProblem.cpp.
References mpScaledResultAnnotation.
 {
   return mpScaledResultAnnotation;
 }
CSensProblem::SubTaskType CSensProblem::getSubTaskType () const
get the problem's SubTaskType:
Definition at line 282 of file CSensProblem.cpp.
References Evaluation, and mpSubTaskType.
Referenced by CSensMethod::initialize(), SensitivitiesWidget::loadTask(), and operator<<().
 {
   if (mpSubTaskType)
     return *mpSubTaskType;
   else
     return CSensProblem::Evaluation;
 }
CSensItem CSensProblem::getTargetFunctions () const
Definition at line 290 of file CSensProblem.cpp.
References copyParameterGroupToSensItem(), and mpTargetFunctions.
Referenced by collapsRequested(), CSensMethod::initialize(), SensitivitiesWidget::loadTask(), and operator<<().
 {
   CSensItem ret;
   CCopasiParameterGroup* tmp;
   tmp = (CCopasiParameterGroup*)(mpTargetFunctions);
   copyParameterGroupToSensItem(tmp, &ret);
   return ret;
 }
CSensItem CSensProblem::getVariables (size_t index) const
Definition at line 312 of file CSensProblem.cpp.
References copyParameterGroupToSensItem(), CCopasiParameterGroup::getParameter(), and mpVariablesGroup.
Referenced by CSensMethod::initialize(), SensitivitiesWidget::loadTask(), and operator<<().
 {
   CSensItem ret;
   CCopasiParameterGroup* tmp;
   tmp = (CCopasiParameterGroup*)(mpVariablesGroup->getParameter(index));
   copyParameterGroupToSensItem(tmp, &ret);
   return ret;
 }
void CSensProblem::initDebugProblem () private
this sets up a problem for debugging purposes
Definition at line 636 of file CSensProblem.cpp.
References addVariables(), CCopasiParameter::getCN(), CObjectLists::NON_CONST_METAB_CONCENTRATIONS, CSensItem::setListType(), and CSensItem::setSingleObjectCN().
 {
   CSensItem item;
   item.setSingleObjectCN(this->getCN());
   addVariables(item);
   item.setListType(CObjectLists::NON_CONST_METAB_CONCENTRATIONS);
   addVariables(item);
 }
void CSensProblem::initObjects () private
Definition at line 251 of file CSensProblem.cpp.
References mCollapsedResult, mpCollapsedResultAnnotation, mpResultAnnotation, mpScaledResultAnnotation, mResult, mScaledResult, CArrayAnnotation::OBJECTS, CArrayAnnotation::setDescription(), and CArrayAnnotation::setMode().
Referenced by CSensProblem().
 {
   mpResultAnnotation = new CArrayAnnotation("Sensitivities array", this, &mResult, false);
   mpResultAnnotation->setDescription("");
   mpResultAnnotation->setMode(CArrayAnnotation::OBJECTS);
   mpScaledResultAnnotation = new CArrayAnnotation("Scaled sensitivities array", this, &mScaledResult, false);
   mpScaledResultAnnotation->setDescription("");
   mpScaledResultAnnotation->setMode(CArrayAnnotation::OBJECTS);
   mpCollapsedResultAnnotation = new CArrayAnnotation("Summarized sensitivities array", this, &mCollapsedResult, false);
   mpCollapsedResultAnnotation->setDescription("");
   mpCollapsedResultAnnotation->setMode(CArrayAnnotation::OBJECTS);
 }
void CSensProblem::print (std::ostream * ostream) const virtual
This is the output method for any object. It calls the insert operator<<
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Definition at line 633 of file CSensProblem.cpp.
 {*ostream << *this;}
void CSensProblem::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implemented." To overide this default behaviour one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Definition at line 574 of file CSensProblem.cpp.
References mpResultAnnotation, and mpScaledResultAnnotation.
 {
   std::ostream & os = *ostream;
   //os << "Sensitivities result." << std::endl;
   if (mpResultAnnotation)
     os << *mpResultAnnotation << std::endl;
   if (mpScaledResultAnnotation)
     os << *mpScaledResultAnnotation << std::endl;
 }
bool CSensProblem::removeVariables (size_t index)
Definition at line 346 of file CSensProblem.cpp.
References mpVariablesGroup, and CCopasiParameterGroup::removeParameter().
Referenced by SensitivitiesWidget::saveTask().
 {
   return mpVariablesGroup->removeParameter(index);
 }
bool CSensProblem::removeVariables ()
Definition at line 336 of file CSensProblem.cpp.
References mpVariablesGroup, CCopasiParameterGroup::removeParameter(), and CCopasiParameterGroup::size().
 {
   size_t imax = mpVariablesGroup->size();
   for (size_t i = 0; i < imax; ++i)
     mpVariablesGroup->removeParameter(0);
   return true;
 }
void CSensProblem::setSubTaskType (const CSensProblem::SubTaskType & type)
set the problem's SubTaskType:
Definition at line 276 of file CSensProblem.cpp.
References mpSubTaskType.
Referenced by CSensProblem(), and SensitivitiesWidget::saveTask().
 {*mpSubTaskType = type;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CSensProblem & o) friend
Output stream operator. Prints description of the problem
Parameters
ostream & os
const Problem & A
Returns
ostream & os
Definition at line 612 of file CSensProblem.cpp.
 {
   os << "Function(s) to be derived:" << std::endl;
   const CCopasiDataModel* pDataModel = o.getObjectDataModel();
   assert(pDataModel != NULL);
   os << o.getTargetFunctions().print(pDataModel) << std::endl << std::endl;
   os << "Calculation to perform: "
      << CSensProblem::SubTaskName[o.getSubTaskType()] << std::endl << std::endl;
   size_t i, imax = o.getNumberOfVariables();
   for (i = 0; i < imax; ++i)
     {
       os << "Variable(s) for " << i + 1 << ". derivation:" << std::endl;
       os << o.getVariables(i).print(pDataModel) << std::endl << std::endl;
     }
   return os;
 }
Member Data Documentation
CCopasiArray CSensProblem::mCollapsedResult private
This holds the collapsed result
Definition at line 220 of file CSensProblem.h.
Referenced by getCollapsedResult(), and initObjects().
CArrayAnnotation* CSensProblem::mpCollapsedResultAnnotation private
Definition at line 222 of file CSensProblem.h.
Referenced by getCollapsedResultAnnotated(), and initObjects().
CArrayAnnotation* CSensProblem::mpResultAnnotation private
Definition at line 208 of file CSensProblem.h.
Referenced by getResultAnnotated(), initObjects(), and printResult().
CArrayAnnotation* CSensProblem::mpScaledResultAnnotation private
Definition at line 215 of file CSensProblem.h.
Referenced by getScaledResultAnnotated(), initObjects(), and printResult().
CSensProblem::SubTaskType* CSensProblem::mpSubTaskType private
Definition at line 192 of file CSensProblem.h.
Referenced by CSensProblem(), getSubTaskType(), and setSubTaskType().
CCopasiParameterGroup* CSensProblem::mpTargetFunctions private
Definition at line 194 of file CSensProblem.h.
Referenced by changeTargetFunctions(), CSensProblem(), and getTargetFunctions().
CCopasiParameterGroup* CSensProblem::mpVariablesGroup private
This holds the variables items
Definition at line 201 of file CSensProblem.h.
Referenced by addVariables(), changeVariables(), CSensProblem(), getNumberOfVariables(), getVariables(), and removeVariables().
CCopasiArray CSensProblem::mResult private
This holds the result
Definition at line 206 of file CSensProblem.h.
Referenced by getResult(), and initObjects().
CCopasiArray CSensProblem::mScaledResult private
This holds the scaled result
Definition at line 213 of file CSensProblem.h.
Referenced by getScaledResult(), and initObjects().
const std::string CSensProblem::SubTaskName static
Initial value:
=
{
  "Evaluation",
  "Steady State",
  "Time Series",
  "Parameter Estimation",
  "Optimization",
  "Cross Section",
  ""
}
Definition at line 82 of file CSensProblem.h.
Referenced by SensitivitiesWidget::initCombos(), and operator<<().
const char * CSensProblem::XMLSubTask static
Initial value:
=
{
  "Evaluation",
  "SteadyState",
  "TimeSeries",
  "ParameterEstimation",
  "Optimization",
  "CrossSection",
  NULL
}
Definition at line 84 of file CSensProblem.h.
The documentation for this class was generated from the following files:
CSensProblem.h
CSensProblem.cpp