COPASI API: CExperimentObjectMap Class Reference
CExperimentObjectMap Class Reference
#include <CExperimentObjectMap.h>
Classes
class CDataColumn
Public Member Functions
CExperimentObjectMap (const std::string &name="Object Map", const CCopasiContainer *pParent=NULL)
CExperimentObjectMap (const CExperimentObjectMap &src, const CCopasiContainer *pParent=NULL)
CExperimentObjectMap (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
bool compile (const std::vector< CCopasiContainer * > listOfContainer=CCopasiContainer::EmptyList)
virtual bool elevateChildren ()
void fixBuild55 ()
C_FLOAT64 getDefaultScale (const size_t &index) const
const size_t & getLastColumn () const
size_t getLastNotIgnoredColumn () const
const CVector< CCopasiObject * > & getMappedObjects () const
virtual const std::string & getName (const size_t &index) const
std::string getObjectCN (const size_t &index) const
CExperiment::Type getRole (const size_t &index) const
C_FLOAT64 getScale (const size_t &index) const
bool setNumCols (const size_t &numCols)
bool setObjectCN (const size_t &index, const std::string &objectCN)
bool setRole (const size_t &index, const CExperiment::Type &role)
bool setScale (const size_t &index, const C_FLOAT64 &scale)
virtual ~CExperimentObjectMap ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initializeParameter ()
Private Attributes
size_t mLastColumn
CVector< CCopasiObject * > mObjects
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 23 of file CExperimentObjectMap.h.
Constructor & Destructor Documentation
CExperimentObjectMap::CExperimentObjectMap (const std::string & name = "Object Map", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: Object Map)
const CCopasiContainer * pParent (default: NULL)
Definition at line 27 of file CExperimentObjectMap.cpp.
References initializeParameter().
                                      :
   CCopasiParameterGroup(name, pParent),
   mObjects(0),
   mLastColumn(0)
 {initializeParameter();}
CExperimentObjectMap::CExperimentObjectMap (const CExperimentObjectMap & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CExperimentObjectMap & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 34 of file CExperimentObjectMap.cpp.
References initializeParameter().
                                      :
   CCopasiParameterGroup(src, pParent),
   mObjects(src.mObjects),
   mLastColumn(src.mLastColumn)
 {initializeParameter();}
CExperimentObjectMap::CExperimentObjectMap (const CCopasiParameterGroup & group, const CCopasiContainer * pParent = NULL)
Specific constructor used for reading copasi files
Parameters
const CCopasiParameterGroup & group
const CCopasiContainer * pParent (default: NULL)
Definition at line 41 of file CExperimentObjectMap.cpp.
References initializeParameter().
                                      :
   CCopasiParameterGroup(group, pParent),
   mObjects(0),
   mLastColumn(0)
 {initializeParameter();}
CExperimentObjectMap::~CExperimentObjectMap () virtual
Destructor
Definition at line 48 of file CExperimentObjectMap.cpp.
 {}
Member Function Documentation
bool CExperimentObjectMap::compile (const std::vector< CCopasiContainer * > listOfContainer = CCopasiContainer::EmptyList)
Compile the map. This function must be called before any operations can be performed.
Parameters
const std::vector< CCopasiContainer * > listOfContainer
Returns
bool success
Definition at line 222 of file CExperimentObjectMap.cpp.
References C_INVALID_INDEX, CCopasiParameter::CN, getName(), getObjectCN(), CCopasiObject::getObjectDataModel(), CCopasiObject::isValueDbl(), mLastColumn, mObjects, CVector< CType >::resize(), and CCopasiParameterGroup::size().
Referenced by CExperiment::compile().
 {
   size_t i, imax = size();
   size_t Column;
   // We need to find out the size of the object map
   if (imax == 0)
     mLastColumn = C_INVALID_INDEX;
   else
     {
       mLastColumn = strtoul(getName(0).c_str(), NULL, 0);
       for (i = 1; i < imax; i++)
         {
           Column = strtoul(getName(i).c_str(), NULL, 0);
           if (mLastColumn < Column)
             mLastColumn = Column;
         }
     }
   mObjects.resize(mLastColumn + 1);
   mObjects = NULL;
   CCopasiObject * pObject = NULL;
   std::string CN;
   for (i = 0; i < imax; i++)
     {
       if ((CN = getObjectCN(i)) == "") continue;
       if ((pObject =
              getObjectDataModel()->ObjectFromName(listOfContainer, CN)) != NULL &&
           pObject->isValueDbl())
         {
           Column = strtoul(getName(i).c_str(), NULL, 0);
           mObjects[Column] = pObject;
         }
       else
         return false;
     }
   return true;
 }
bool CExperimentObjectMap::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 55 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::assertGroup(), CCopasiParameterGroup::assertParameter(), CCopasiParameterGroup::clear(), CCopasiParameter::CN, CCopasiObject::getObjectName(), CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by CExperimentObjectMap::CDataColumn::initializeParameter(), and initializeParameter().
 {
   bool success = true;
   std::vector<CCopasiParameter *>::iterator itColumn = mValue.pGROUP->begin();
   std::vector<CCopasiParameter *>::iterator endColumn = mValue.pGROUP->end();
   if (itColumn != endColumn &&
       dynamic_cast< CCopasiParameterGroup * >(*itColumn) == NULL) // We have an old data format.
     {
       CCopasiParameterGroup New(getObjectName());
       for (; itColumn != endColumn; ++itColumn)
         {
           CCopasiParameterGroup * pGroup = New.assertGroup((*itColumn)->getObjectName());
           pGroup->assertParameter("Object CN", CCopasiParameter::CN, *(*itColumn)->getValue().pCN);
         }
       clear();
       *this = New;
     }
   for (itColumn = mValue.pGROUP->begin(); itColumn != endColumn; ++itColumn)
     if (((*itColumn) = elevate<CDataColumn, CCopasiParameterGroup>(*itColumn)) == NULL)
       success = false;
   return success;
 }
void CExperimentObjectMap::fixBuild55 ()
Fix files written with Version 4.10.55, which wrote the square root of user defined weights for the parameter fitting task
Definition at line 273 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), and CExperimentObjectMap::CDataColumn::fixBuild55().
Referenced by CExperiment::fixBuild55().
 {
   CCopasiParameterGroup::index_iterator it = beginIndex();
   CCopasiParameterGroup::index_iterator end = endIndex();
   for (; it != end; ++it)
     {
       CDataColumn * pColumn = dynamic_cast< CDataColumn * >(*it);
       if (pColumn != NULL)
         {
           pColumn->fixBuild55();
         }
     }
 }
C_FLOAT64 CExperimentObjectMap::getDefaultScale (const size_t & index) const
Retrieve the default scaling factor according to the selected weight method of the indexed column
Parameters
const size_t & index
Returns
C_FLOAT64 defaultScale
Definition at line 211 of file CExperimentObjectMap.cpp.
References CExperimentObjectMap::CDataColumn::getDefaultScale(), CCopasiParameterGroup::getGroup(), and StringPrint().
Referenced by CExperimentObjectMap::CDataColumn::getScale(), CQExperimentData::loadTable(), CExperimentObjectMap::CDataColumn::setScale(), and CQExperimentData::updateScales().
 {
   const CDataColumn * pColumn =
     dynamic_cast< const CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->getDefaultScale();
   else
     return std::numeric_limits<C_FLOAT64>::quiet_NaN();
 }
const size_t & CExperimentObjectMap::getLastColumn () const
Retrieve the last mapped column number
Returns
const size_t & lastColumn
Definition at line 270 of file CExperimentObjectMap.cpp.
References mLastColumn.
Referenced by CExperiment::compile().
 {return mLastColumn;}
size_t CExperimentObjectMap::getLastNotIgnoredColumn () const
Retrieve the last non ignored column
Returns
size_t lastNotIgnoredColumn
Definition at line 110 of file CExperimentObjectMap.cpp.
References C_INT32, CExperiment::ignore, CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by CExperiment::compile(), and CExperiment::printResult().
 {
   std::vector<CCopasiParameter *>::iterator itColumn = mValue.pGROUP->begin();
   std::vector<CCopasiParameter *>::iterator endColumn = mValue.pGROUP->end();
   C_INT32 LastNotIgnored = -1;
   for (; itColumn != endColumn; ++itColumn)
     if (static_cast< CDataColumn * >(*itColumn)->getRole() != CExperiment::ignore)
       {
         C_INT32 index = strtol(static_cast< CDataColumn * >(*itColumn)->getObjectName().c_str(), NULL, 10);
         if (index > LastNotIgnored) LastNotIgnored = index;
       }
   return LastNotIgnored;
 }
const CVector< CCopasiObject * > & CExperimentObjectMap::getMappedObjects () const
Retrieve the vector of mapped objects
Returns
const CVector< CCopasiObject * > & mappedObjects
Definition at line 267 of file CExperimentObjectMap.cpp.
References mObjects.
Referenced by CExperiment::compile(), and CExperiment::printResult().
 {return mObjects;}
const std::string & CExperimentObjectMap::getName (const size_t & index) const virtual
Retrieve the name of a parameter or subgroup
Parameters
const size_t & index
Returns
std::string name
Reimplemented from CCopasiParameterGroup.
Definition at line 129 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CCopasiObject::getObjectName(), and StringPrint().
Referenced by compile().
 {
   static const std::string NoName("");
   const CDataColumn * pColumn =
     dynamic_cast< const CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->getObjectName();
   else
     return NoName;
 }
std::string CExperimentObjectMap::getObjectCN (const size_t & index) const
Retrieve the object CN of the object mapped to the indexed column
Parameters
const size_t & index
Returns
std::stringobjctCN
Definition at line 177 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CExperimentObjectMap::CDataColumn::getObjectCN(), and StringPrint().
Referenced by compile(), CExperiment::elevateChildren(), CQExperimentData::loadTable(), CQExperimentData::saveTable(), and CExperiment::updateFittedPoints().
 {
   const CDataColumn * pColumn =
     dynamic_cast< const CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->getObjectCN();
   else
     return "";
 }
CExperiment::Type CExperimentObjectMap::getRole (const size_t & index) const
Retrieve the role of the indexed column
Parameters
const size_t & index
Returns
CExperiment::Type role
Definition at line 154 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CExperimentObjectMap::CDataColumn::getRole(), CExperiment::ignore, and StringPrint().
Referenced by CExperiment::compile(), CQExperimentData::loadTable(), CExperiment::printResult(), CExperiment::read(), CQExperimentData::saveTable(), CExperiment::updateFittedPoints(), and CQExperimentData::updateScales().
 {
   const CDataColumn * pColumn =
     dynamic_cast< const CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->getRole();
   else
     return CExperiment::ignore;
 }
C_FLOAT64 CExperimentObjectMap::getScale (const size_t & index) const
Retrieve the scaling factor of the indexed column
Parameters
const size_t & index
Returns
C_FLOAT64 scale
Definition at line 200 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CExperimentObjectMap::CDataColumn::getScale(), and StringPrint().
Referenced by CExperiment::compile(), CQExperimentData::loadTable(), and CQExperimentData::saveTable().
 {
   const CDataColumn * pColumn =
     dynamic_cast< const CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->getScale();
   else
     return std::numeric_limits<C_FLOAT64>::quiet_NaN();
 }
void CExperimentObjectMap::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 50 of file CExperimentObjectMap.cpp.
References elevateChildren().
Referenced by CExperimentObjectMap().
 {
   elevateChildren();
 }
bool CExperimentObjectMap::setNumCols (const size_t & numCols)
Set the number of data columns
Parameters
const size_t & numCols
Returns
bool success
Definition at line 84 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::assertGroup(), CCopasiParameter::mValue, CCopasiParameter::Value::pGROUP, and StringPrint().
Referenced by CExperiment::elevateChildren(), and CQExperimentData::saveTable().
 {
   if (numCols == mValue.pGROUP->size())
     return true;
   // We only clear the vector of parameter. We do not destroy the parameter they are still
   // accessible through CCopasiContainer::mObjects and thus will be automatically destroyed.
   mValue.pGROUP->clear();
   bool success = true;
   for (size_t col = 0; col < numCols; col++)
     {
       CCopasiParameterGroup * pGrp = assertGroup(StringPrint("%d", col));
       // assertGroup() adds only newly created groups to mValue.pGROUP. We need to add the existing
       // ones.
       if (mValue.pGROUP->size() < col + 1)
         mValue.pGROUP->push_back(pGrp);
       success &= (elevate<CDataColumn, CCopasiParameterGroup>(pGrp) != NULL);
     }
   return success;
 }
bool CExperimentObjectMap::setObjectCN (const size_t & index, const std::string & objectCN)
Set the object CN of the object mapped to the indexed column
Parameters
const size_t & index
const std::string & objectCN
Returns
bool success
Definition at line 165 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CExperimentObjectMap::CDataColumn::setObjectCN(), and StringPrint().
Referenced by CExperiment::elevateChildren(), CExperimentObjectMap::CDataColumn::operator=(), and CQExperimentData::saveTable().
 {
   CDataColumn * pColumn =
     dynamic_cast< CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->setObjectCN((CCopasiObjectName) CN);
   else
     return false;
 }
bool CExperimentObjectMap::setRole (const size_t & index, const CExperiment::Type & role)
Set the role of the indexed column
Parameters
const size_t & index
const CExperiment::Type & role
Returns
bool success
Definition at line 142 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CExperimentObjectMap::CDataColumn::setRole(), and StringPrint().
Referenced by CExperiment::elevateChildren(), CQExperimentData::loadTable(), CQExperimentData::saveTable(), and CQExperimentData::slotExprimentType().
 {
   CDataColumn * pColumn =
     dynamic_cast< CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->setRole(role);
   else
     return false;
 }
bool CExperimentObjectMap::setScale (const size_t & index, const C_FLOAT64 & scale)
Set the scaling factor for the indexed column
Parameters
const size_t & index
const C_FLOAT64 & scale
Returns
bool success
Definition at line 188 of file CExperimentObjectMap.cpp.
References CCopasiParameterGroup::getGroup(), CExperimentObjectMap::CDataColumn::setScale(), and StringPrint().
Referenced by CExperimentObjectMap::CDataColumn::operator=(), CQExperimentData::saveTable(), and CExperiment::setWeightMethod().
 {
   CDataColumn * pColumn =
     dynamic_cast< CDataColumn * >(getGroup(StringPrint("%d", index)));
   if (pColumn)
     return pColumn->setScale(weight);
   else
     return false;
 }
Member Data Documentation
size_t CExperimentObjectMap::mLastColumn private
The last mapped column
Definition at line 299 of file CExperimentObjectMap.h.
Referenced by compile(), and getLastColumn().
CVector<CCopasiObject *> CExperimentObjectMap::mObjects private
A vector of pointer to the objects corresponding to the data column.
Definition at line 294 of file CExperimentObjectMap.h.
Referenced by compile(), and getMappedObjects().
The documentation for this class was generated from the following files:
CExperimentObjectMap.h
CExperimentObjectMap.cpp