COPASI API: BezierCurve Class Reference
BezierCurve Class Reference
#include <BezierCurve.h>
Public Member Functions
BezierCurve ()
BezierCurve (size_t numberOfStepsOnCurve)
std::vector< CLPoint > curvePts (const std::vector< CLPoint > &pts)
Private Member Functions
C_FLOAT64 bernstein (C_INT32 i, C_INT32 n, C_FLOAT64 t)
CLPoint bezierPt (C_FLOAT64 t, std::vector< CLPoint > pts)
void init ()
C_FLOAT64 multiplyFromTo (C_INT32 n1, C_INT32 n2)
Private Attributes
C_FLOAT64 dt
size_t steps
C_FLOAT64 t
Detailed Description
Definition at line 37 of file BezierCurve.h.
Constructor & Destructor Documentation
BezierCurve::BezierCurve ()
Definition at line 32 of file BezierCurve.cpp.
References init().
 {
   init();
 }
BezierCurve::BezierCurve (size_t numberOfStepsOnCurve)
Definition at line 37 of file BezierCurve.cpp.
References steps, and t.
 {
   steps = numberOfStepsOnCurve;
   t = 1.0 / steps;
 }
Member Function Documentation
C_FLOAT64 BezierCurve::bernstein (C_INT32 i, C_INT32 n, C_FLOAT64 t) private
Definition at line 79 of file BezierCurve.cpp.
References C_FLOAT64, and multiplyFromTo().
Referenced by bezierPt(), and curvePts().
 {
   // first compute n over i
   C_FLOAT64 top = multiplyFromTo(n - i + 1, n);
   C_FLOAT64 bottom = multiplyFromTo(1, i);
   return (top / bottom * pow(t, (C_FLOAT64)i) * pow(1.0 - t, (C_FLOAT64)n - i));
 }
CLPoint BezierCurve::bezierPt (C_FLOAT64 t, std::vector< CLPoint > pts) private
Definition at line 89 of file BezierCurve.cpp.
References bernstein(), C_FLOAT64, and C_INT32.
 {
   C_INT32 i;
   C_FLOAT64 x = 0.0;
   C_FLOAT64 y = 0.0;
   C_INT32 n = (C_INT32) pts.size() - 1;
   for (i = 0; i <= n; i++)
     {
       x += bernstein(i, n, t) * pts[i].getX();
       y += bernstein(i, n, t) * pts[i].getY();
     }
   return CLPoint(x, y);
 }
std::vector< CLPoint > BezierCurve::curvePts (const std::vector< CLPoint > & pts)
Definition at line 49 of file BezierCurve.cpp.
References bernstein(), C_FLOAT64, C_INT32, dt, and t.
Referenced by CGraphCurve::invertOrderOfPoints().
 {
   C_FLOAT64 x;
   C_FLOAT64 y;
   std::vector<CLPoint>points;
   points = std::vector<CLPoint>();
   C_FLOAT64 t = 0.0;
   C_INT32 i;
   C_INT32 n = (C_INT32) pts.size() - 1;
   while (t <= 1.0000001)
     {
       x = 0.0;
       y = 0.0;
       for (i = 0; i <= n; i++)
         {
           x += bernstein(i, n, t) * pts[i].getX();
           y += bernstein(i, n, t) * pts[i].getY();
         }
       points.push_back(CLPoint(x, y));
       t += dt;
     }
   return points;
 }
void BezierCurve::init () private
Definition at line 43 of file BezierCurve.cpp.
References dt, and steps.
Referenced by BezierCurve().
 {
   steps = 100;
   dt = 0.01;
 }
C_FLOAT64 BezierCurve::multiplyFromTo (C_INT32 n1, C_INT32 n2) private
Definition at line 108 of file BezierCurve.cpp.
References C_FLOAT64, and C_INT32.
Referenced by bernstein().
 {
   C_INT32 i;
   C_FLOAT64 prod = 1;
   if (n2 >= n1)
     {
       for (i = n1; i <= n2; i++)
         prod *= (C_FLOAT64)i;
     }
   return prod;
 }
Member Data Documentation
C_FLOAT64 BezierCurve::dt private
Definition at line 47 of file BezierCurve.h.
Referenced by curvePts(), and init().
size_t BezierCurve::steps private
Definition at line 46 of file BezierCurve.h.
Referenced by BezierCurve(), and init().
C_FLOAT64 BezierCurve::t private
Definition at line 45 of file BezierCurve.h.
Referenced by BezierCurve(), and curvePts().
The documentation for this class was generated from the following files:
BezierCurve.h
BezierCurve.cpp