COPASI API: CQParameterOverviewWidget Class Reference
CQParameterOverviewWidget Class Reference
#include <CQParameterOverviewWidget.h>
Public Member Functions
CQParameterOverviewWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQParameterOverviewWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Slots
virtual void slotBtnCommit ()
virtual void slotBtnCopy ()
virtual void slotBtnDelete ()
virtual void slotBtnNew ()
virtual void slotBtnRevert ()
virtual void slotBtnSaveAs ()
virtual void slotBtnSaveToFile ()
void slotCloseEditor (const QModelIndex &index)
void slotOpenEditor (const QModelIndex &index)
void slotResolve (const QModelIndex &index)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Private Member Functions
void buildSelectionList ()
virtual bool enterProtected ()
Private Attributes
QStringList mGlobalQuantities
CModelParameterSet * mpParameterSet
CModelParameterSet * mpParameterSetCopy
CQParameterOverviewDM * mpParameterSetDM
QSortFilterProxyModel * mpParameterSetSortDM
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 17 of file CQParameterOverviewWidget.h.
Constructor & Destructor Documentation
CQParameterOverviewWidget::CQParameterOverviewWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 24 of file CQParameterOverviewWidget.cpp.
References mGlobalQuantities, mpParameterSetDM, mpParameterSetSortDM, CQPushButtonDelegate::PushButton, slotCloseEditor(), slotOpenEditor(), and slotResolve().
                                                                                      :
   CopasiWidget(parent, name),
   mpParameterSet(NULL),
   mpParameterSetCopy(NULL),
   mpParameterSetDM(NULL),
   mpParameterSetSortDM(NULL),
   mGlobalQuantities()
 {
   setupUi(this);
   // create a new QListview to be displayed on the screen..and set its property
   mpParameterSetDM = new CQParameterOverviewDM(this);
   mpParameterSetSortDM = new QSortFilterProxyModel(this);
   mpParameterSetSortDM->setSourceModel(mpParameterSetDM);
   mpParameterSetSortDM->setSortRole(Qt::EditRole);
   mpParameterSetSortDM->setSortCaseSensitivity(Qt::CaseInsensitive);
   // pSortModel->sort(0, Qt::AscendingOrder);
   mpTreeView->setModel(mpParameterSetSortDM);
   mpTreeView->sortByColumn(0, Qt::AscendingOrder);
   CQPushButtonDelegate * pPushButtonDelegate = new CQPushButtonDelegate(CQPushButtonDelegate::PushButton, this);
   mpTreeView->setItemDelegateForColumn(1, pPushButtonDelegate);
   connect(pPushButtonDelegate, SIGNAL(clicked(const QModelIndex &)), this, SLOT(slotResolve(const QModelIndex &)));
   CQComboDelegate * pComboDelegate = new CQComboDelegate(&mGlobalQuantities, this);
   mpTreeView->setItemDelegateForColumn(5, pComboDelegate);
   connect(mpParameterSetDM, SIGNAL(signalOpenEditor(const QModelIndex &)), this, SLOT(slotOpenEditor(const QModelIndex &)));
   connect(mpParameterSetDM, SIGNAL(signalCloseEditor(const QModelIndex &)), this, SLOT(slotCloseEditor(const QModelIndex &)));
 }
CQParameterOverviewWidget::~CQParameterOverviewWidget () virtual
Definition at line 57 of file CQParameterOverviewWidget.cpp.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
void CQParameterOverviewWidget::buildSelectionList () private
Definition at line 219 of file CQParameterOverviewWidget.cpp.
References CModelParameterGroup::begin(), CModelParameterGroup::end(), FROM_UTF8, CModelParameterGroup::getModelParameter(), mGlobalQuantities, CModelParameter::Missing, and mpParameterSetCopy.
Referenced by enterProtected(), and slotResolve().
 {
   // We build the selection for the global parameters for kinetic constants.
   const CModelParameterGroup *pGlobalQuantities =
     static_cast< CModelParameterGroup * >(mpParameterSetCopy->getModelParameter(CCopasiStaticString("Initial Global Quantities").getCN()));
   CModelParameterGroup::const_iterator it = pGlobalQuantities->begin();
   CModelParameterGroup::const_iterator end = pGlobalQuantities->end();
   mGlobalQuantities.clear();
   mGlobalQuantities.append("");
   for (; it != end; ++it)
     {
       if ((*it)->getCompareResult() != CModelParameter::Missing)
         {
           mGlobalQuantities.append(FROM_UTF8((*it)->getName()));
         }
     }
 }
bool CQParameterOverviewWidget::enterProtected () private virtual
Reimplemented from CopasiWidget.
Definition at line 173 of file CQParameterOverviewWidget.cpp.
References buildSelectionList(), CModelParameterSet::compareWithModel(), CModelParameterGroup::compile(), CModelParameterSet::isActive(), CopasiWidget::mFramework, mGlobalQuantities, CopasiWidget::mpDataModel, CopasiWidget::mpObject, mpParameterSet, mpParameterSetCopy, mpParameterSetDM, pdelete, and CQParameterOverviewDM::setModelParameterset().
Referenced by slotBtnCommit(), slotBtnNew(), slotBtnRevert(), and update().
 {
   mpParameterSet = dynamic_cast< CModelParameterSet * >(mpObject);
   if (!mpParameterSet)
     {
       mpParameterSetDM->setModelParameterset(NULL);
       pdelete(mpParameterSetCopy);
       return false;
     }
   // We need to make sure the original is fully compiled.
   mpParameterSet->compile();
   CModelParameterSet * pOldParameterSet = mpParameterSetCopy;
   mpParameterSetCopy = new CModelParameterSet(*mpParameterSet, mpDataModel, false);
   mGlobalQuantities.clear();
   if (mpParameterSet->isActive())
     {
       mpTreeView->header()->hideSection(1);
     }
   else
     {
       mpParameterSetCopy->compareWithModel(static_cast< CModelParameter::Framework >(mFramework));
       mpHeaderWidget->hide();
       mpBtnWidget->hide();
     }
   buildSelectionList();
   mpParameterSetDM->setModelParameterset(mpParameterSetCopy);
   pdelete(pOldParameterSet);
   mpTreeView->expandAll();
   for (int i = 0; i < 6; i++)
     {
       mpTreeView->resizeColumnToContents(i);
     }
   return true;
 }
bool CQParameterOverviewWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 122 of file CQParameterOverviewWidget.cpp.
References CModelParameterSet::assignSetContent(), ListViews::CHANGE, CModelParameterGroup::diff(), CCopasiRootContainer::getDatamodelList(), CModelParameter::Identical, CModelParameterSet::isActive(), CopasiWidget::mFramework, CopasiWidget::mKey, ListViews::MODELPARAMETERSET, mpParameterSet, mpParameterSetCopy, CopasiWidget::protectedNotify(), ListViews::STATE, and CModelParameterSet::updateModel().
Referenced by slotBtnCommit().
 {
   if (mpParameterSet == NULL)
     {
       return true;
     }
   if (mpParameterSet->diff(*mpParameterSetCopy,
                            static_cast< CModelParameter::Framework >(mFramework),
                            false) != CModelParameter::Identical)
     {
       mpParameterSet->assignSetContent(*mpParameterSetCopy, false);
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed();
       if (mpParameterSet->isActive())
         {
           mpParameterSet->updateModel();
           protectedNotify(ListViews::STATE, ListViews::CHANGE, "");
         }
       else
         {
           protectedNotify(ListViews::MODELPARAMETERSET, ListViews::CHANGE, mKey);
         }
     }
   return true;
 }
void CQParameterOverviewWidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 153 of file CQParameterOverviewWidget.cpp.
References CModelParameterSet::compareWithModel(), CModelParameterSet::isActive(), CopasiWidget::mFramework, mpParameterSet, mpParameterSetCopy, mpParameterSetDM, CQParameterOverviewDM::setFramework(), and CopasiWidget::setFramework().
 {
   CopasiWidget::setFramework(framework);
   if (mpParameterSet == NULL)
     {
       return;
     }
   if (!mpParameterSet->isActive())
     {
       mpParameterSetCopy->compareWithModel(static_cast< CModelParameter::Framework >(mFramework));
     }
   mpParameterSetDM->setFramework(framework);
   mpTreeView->expandAll();
   mpTreeView->resizeColumnToContents(3);
 }
void CQParameterOverviewWidget::slotBtnCommit () protected virtual slot
Definition at line 248 of file CQParameterOverviewWidget.cpp.
References enterProtected(), and leave().
Referenced by slotBtnCopy(), slotBtnNew(), slotBtnSaveAs(), and slotBtnSaveToFile().
 {
   mpBtnCommit->setFocus();
   leave();
   enterProtected();
 }
void CQParameterOverviewWidget::slotBtnCopy () protected virtual slot
Definition at line 354 of file CQParameterOverviewWidget.cpp.
References ListViews::ADD, CCopasiVectorN< CType >::add(), C_INVALID_INDEX, CCopasiVectorN< CType >::getIndex(), CModelParameterSet::getKey(), CModelParameterSet::getModel(), CModel::getModelParameterSet(), CModel::getModelParameterSets(), ListViews::MODELPARAMETERSET, CopasiWidget::mpListView, mpParameterSet, CopasiWidget::protectedNotify(), CCopasiObject::setObjectName(), slotBtnCommit(), ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   // commit all changes
   slotBtnCommit();
   // Sanity checks
   if (mpParameterSet == NULL)
     {
       return;
     }
   CModel * pModel = mpParameterSet->getModel();
   if (pModel == NULL)
     {
       return;
     }
   CCopasiVectorN< CModelParameterSet > & Sets = pModel->getModelParameterSets();
   std::string Name = "Parameter Set";
   int i = 0;
   while (Sets.getIndex(Name) != C_INVALID_INDEX)
     {
       i++;
       Name = "Parameter Set ";
       Name += TO_UTF8(QString::number(i));
     }
   CModelParameterSet * pNew = new CModelParameterSet(pModel->getModelParameterSet(), pModel, false);
   pNew->setObjectName(Name);
   Sets.add(pNew, true);
   // Notify the GUI of the insert
   protectedNotify(ListViews::MODELPARAMETERSET, ListViews::ADD, pNew->getKey());
   mpListView->switchToOtherWidget(C_INVALID_INDEX, pNew->getKey());
 }
void CQParameterOverviewWidget::slotBtnDelete () protected virtual slot
Definition at line 256 of file CQParameterOverviewWidget.cpp.
References ListViews::DELETE, CModelParameterSet::getModel(), CModel::getModelParameterSets(), CCopasiObject::getObjectName(), CopasiWidget::mKey, ListViews::MODELPARAMETERSET, mpParameterSet, mpParameterSetDM, CopasiWidget::protectedNotify(), CCopasiVectorN< CType >::remove(), and CQParameterOverviewDM::setModelParameterset().
 {
   if (mpParameterSet == NULL)
     {
       return;
     }
   CModel * pModel = mpParameterSet->getModel();
   if (pModel == NULL)
     {
       return;
     }
   mpParameterSetDM->setModelParameterset(NULL);
   pModel->getModelParameterSets().remove(mpParameterSet->getObjectName());
   // Notify the GUI of the delete.
   protectedNotify(ListViews::MODELPARAMETERSET, ListViews::DELETE, mKey);
 }
void CQParameterOverviewWidget::slotBtnNew () protected virtual slot
Definition at line 279 of file CQParameterOverviewWidget.cpp.
References ListViews::ADD, CCopasiVectorN< CType >::add(), CModelParameterSet::assignSetContent(), CCopasiVector< T >::begin(), ListViews::CHANGE, CCopasiVector< T >::end(), enterProtected(), FROM_UTF8, CModelParameterSet::getKey(), CModel::getKey(), CModelParameterSet::getModel(), CModel::getModelParameterSet(), CModel::getModelParameterSets(), CQNameSelectionDialog::getSelection(), ListViews::MODELPARAMETERSET, mpParameterSet, CopasiWidget::protectedNotify(), CQMessageBox::question(), CCopasiObject::setObjectName(), CQNameSelectionDialog::setSelectionList(), slotBtnCommit(), ListViews::STATE, TO_UTF8, and CModelParameterSet::updateModel().
 {
   // This button is shown as Apply and is used to assign the parameter values to the model.
   // commit all changes
   slotBtnCommit();
   // Sanity checks
   if (mpParameterSet == NULL)
     {
       return;
     }
   CModel * pModel = mpParameterSet->getModel();
   if (pModel == NULL)
     {
       return;
     }
   // We first asked whether the user wants to save the current model values
   if (CQMessageBox::question(this, "Save current Model Parameters?",
                              "You are about to overwrite the current model values.\n"
                              "Do you want to save them?",
                              QMessageBox::Save | QMessageBox::Discard,
                              QMessageBox::Save) == QMessageBox::Save)
     {
       // Save the parameter set to a new or existing set
       CQNameSelectionDialog Dialog(this);
       CCopasiVectorN< CModelParameterSet > & Sets = pModel->getModelParameterSets();
       CCopasiVectorN< CModelParameterSet >::const_iterator it = Sets.begin();
       CCopasiVectorN< CModelParameterSet >::const_iterator end = Sets.end();
       QStringList SelectionList;
       for (; it != end; ++it)
         {
           SelectionList.append(FROM_UTF8((*it)->getName()));
         }
       Dialog.setSelectionList(SelectionList);
       QString Name;
       if (Dialog.exec() != QDialog::Rejected &&
           (Name = Dialog.getSelection()) != "")
         {
           if (SelectionList.indexOf(Name) == -1)
             {
               CModelParameterSet * pNew = new CModelParameterSet(pModel->getModelParameterSet(), pModel, false);
               pNew->setObjectName(TO_UTF8(Name));
               Sets.add(pNew, true);
               // Notify the GUI of the insert
               protectedNotify(ListViews::MODELPARAMETERSET, ListViews::ADD, pNew->getKey());
             }
           else
             {
               CModelParameterSet * pExisting = Sets[TO_UTF8(Name)];
               pExisting->assignSetContent(pModel->getModelParameterSet(), false);
               // Notify the GUI of the insert
               protectedNotify(ListViews::MODELPARAMETERSET, ListViews::CHANGE, pExisting->getKey());
             }
         }
     }
   mpParameterSet->updateModel();
   // Notify the GUI that the model state has changed.
   protectedNotify(ListViews::STATE, ListViews::CHANGE, pModel->getKey());
   enterProtected();
 }
void CQParameterOverviewWidget::slotBtnRevert () protected virtual slot
Definition at line 241 of file CQParameterOverviewWidget.cpp.
References enterProtected().
 {
   mpBtnRevert->setFocus();
   enterProtected();
 }
void CQParameterOverviewWidget::slotBtnSaveAs () protected virtual slot
Definition at line 445 of file CQParameterOverviewWidget.cpp.
References ListViews::ADD, CCopasiVectorN< CType >::add(), CModelParameterSet::assignSetContent(), CCopasiVector< T >::begin(), ListViews::CHANGE, CCopasiVector< T >::end(), FROM_UTF8, CModelParameterSet::getKey(), CModelParameterSet::getModel(), CModel::getModelParameterSets(), CQNameSelectionDialog::getSelection(), ListViews::MODELPARAMETERSET, mpParameterSet, CopasiWidget::protectedNotify(), CCopasiObject::setObjectName(), CQNameSelectionDialog::setSelectionList(), slotBtnCommit(), and TO_UTF8.
 {
   // commit all changes
   slotBtnCommit();
   if (mpParameterSet == NULL)
     {
       return;
     }
   CModel * pModel = mpParameterSet->getModel();
   if (pModel == NULL)
     {
       return;
     }
   // Save the parameter set to a new or existing set
   CQNameSelectionDialog Dialog(this);
   CCopasiVectorN< CModelParameterSet > & Sets = pModel->getModelParameterSets();
   CCopasiVectorN< CModelParameterSet >::const_iterator it = Sets.begin();
   CCopasiVectorN< CModelParameterSet >::const_iterator end = Sets.end();
   QStringList SelectionList;
   for (; it != end; ++it)
     {
       SelectionList.append(FROM_UTF8((*it)->getName()));
     }
   Dialog.setSelectionList(SelectionList);
   if (Dialog.exec() == QDialog::Rejected)
     {
       return;
     }
   QString Name = Dialog.getSelection();
   if (Name == "")
     {
       return;
     }
   if (SelectionList.indexOf(Name) == -1)
     {
       CModelParameterSet * pNew = new CModelParameterSet(*mpParameterSet, pModel, false);
       pNew->setObjectName(TO_UTF8(Name));
       Sets.add(pNew, true);
       // Notify the GUI of the insert
       protectedNotify(ListViews::MODELPARAMETERSET, ListViews::ADD, pNew->getKey());
     }
   else
     {
       CModelParameterSet * pExisting = Sets[TO_UTF8(Name)];
       pExisting->assignSetContent(*mpParameterSet, false);
       // Notify the GUI of the insert
       protectedNotify(ListViews::MODELPARAMETERSET, ListViews::CHANGE, pExisting->getKey());
     }
   return;
 }
void CQParameterOverviewWidget::slotBtnSaveToFile () protected virtual slot
Definition at line 394 of file CQParameterOverviewWidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CopasiFileDialog::getSaveFileName(), CopasiWidget::mFramework, mpParameterSet, CModelParameterSet::saveToStream(), slotBtnCommit(), and TO_UTF8.
 {
   // Commit all changes
   slotBtnCommit();
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.tsv", "Tab Separated Files (*.tsv);;Comma Separated Files (*.csv);;TEXT Files (*.txt)", "Save as");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail()) return;
   std::string mode;
   std::string separator;
   if (fileName.endsWith(".txt"))
     {
       mode = "report";
       separator = "\t";
     }
   else if (fileName.endsWith(".csv"))
     {
       mode = "table";
       separator = ",";
     }
   else
     {
       mode = "table";
       separator = "\t";
     }
   mpParameterSet->saveToStream(file, static_cast< CModelParameter::Framework >(mFramework), mode, separator);
   file.close();
 }
void CQParameterOverviewWidget::slotCloseEditor (const QModelIndex & index) protected slot
Definition at line 525 of file CQParameterOverviewWidget.cpp.
Referenced by CQParameterOverviewWidget().
 {
   QModelIndex Tmp = index;
   const QAbstractItemModel *pModel = Tmp.model();
   while (pModel->inherits("QSortFilterProxyModel"))
     {
       Tmp = static_cast< const QSortFilterProxyModel *>(pModel)->mapToSource(index);
       pModel = Tmp.model();
     }
   mpTreeView->closePersistentEditor(Tmp);
 }
void CQParameterOverviewWidget::slotOpenEditor (const QModelIndex & index) protected slot
Definition at line 511 of file CQParameterOverviewWidget.cpp.
References mpParameterSetSortDM.
Referenced by CQParameterOverviewWidget().
 {
   QModelIndex Tmp = index;
   const QAbstractItemModel *pModel = Tmp.model();
   while (pModel->inherits("QSortFilterProxyModel"))
     {
       Tmp = static_cast< const QSortFilterProxyModel *>(pModel)->mapToSource(index);
       pModel = Tmp.model();
     }
   mpTreeView->openPersistentEditor(mpParameterSetSortDM->mapFromSource(Tmp));
 }
void CQParameterOverviewWidget::slotResolve (const QModelIndex & index) protected slot
Definition at line 539 of file CQParameterOverviewWidget.cpp.
References buildSelectionList(), CModelParameterSet::compareWithModel(), CopasiWidget::mFramework, mpParameterSetCopy, mpParameterSetDM, CQParameterOverviewDM::nodeFromIndex(), CModelParameter::refreshFromModel(), and CQParameterOverviewDM::setFramework().
Referenced by CQParameterOverviewWidget().
 {
   CModelParameter * pModelParameter = mpParameterSetDM->nodeFromIndex(index);
   if (pModelParameter == NULL)
     {
       return;
     }
   pModelParameter->refreshFromModel(true);
   mpParameterSetCopy->compareWithModel(static_cast< CModelParameter::Framework >(mFramework));
   buildSelectionList();
   mpParameterSetDM->setFramework(mFramework);
   mpTreeView->expandAll();
   mpTreeView->resizeColumnToContents(3);
 }
bool CQParameterOverviewWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 63 of file CQParameterOverviewWidget.cpp.
References ListViews::ADD, ListViews::CHANGE, ListViews::DELETE, enterProtected(), CopasiWidget::mIgnoreUpdates, CopasiWidget::mKey, ListViews::MODEL, ListViews::MODELPARAMETERSET, CopasiWidget::mpObject, ListViews::PARAMETEROVERVIEW, and ListViews::STATE.
 {
   if (mIgnoreUpdates)
     {
       return true;
     }
   switch (objectType)
     {
       case ListViews::STATE:
         enterProtected();
         break;
       case ListViews::MODEL:
         if (action == ListViews::ADD ||
             action == ListViews::DELETE)
           {
             mKey = "";
             mpObject = NULL;
             enterProtected();
           }
         break;
       case ListViews::PARAMETEROVERVIEW:
       case ListViews::MODELPARAMETERSET:
         if (mKey == key)
           {
             switch (action)
               {
                 case ListViews::DELETE:
                   mKey = "";
                   mpObject = NULL;
                   enterProtected();
                   break;
                 case ListViews::CHANGE:
                   enterProtected();
                   break;
                 default:
                   break;
               }
           }
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
QStringList CQParameterOverviewWidget::mGlobalQuantities private
Definition at line 55 of file CQParameterOverviewWidget.h.
Referenced by buildSelectionList(), CQParameterOverviewWidget(), and enterProtected().
CModelParameterSet* CQParameterOverviewWidget::mpParameterSet private
Definition at line 47 of file CQParameterOverviewWidget.h.
Referenced by enterProtected(), leave(), setFramework(), slotBtnCopy(), slotBtnDelete(), slotBtnNew(), slotBtnSaveAs(), and slotBtnSaveToFile().
CModelParameterSet* CQParameterOverviewWidget::mpParameterSetCopy private
Definition at line 49 of file CQParameterOverviewWidget.h.
Referenced by buildSelectionList(), enterProtected(), leave(), setFramework(), and slotResolve().
CQParameterOverviewDM* CQParameterOverviewWidget::mpParameterSetDM private
Definition at line 51 of file CQParameterOverviewWidget.h.
Referenced by CQParameterOverviewWidget(), enterProtected(), setFramework(), slotBtnDelete(), and slotResolve().
QSortFilterProxyModel* CQParameterOverviewWidget::mpParameterSetSortDM private
Definition at line 53 of file CQParameterOverviewWidget.h.
Referenced by CQParameterOverviewWidget(), and slotOpenEditor().
The documentation for this class was generated from the following files:
CQParameterOverviewWidget.h
CQParameterOverviewWidget.cpp