COPASI API: CQLayoutsWidget Class Reference
CQLayoutsWidget Class Reference
#include <CQLayoutsWidget.h>
Public Member Functions
CQLayoutsWidget (QWidget *parent)
void deleteLayoutWindows ()
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQLayoutsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
void slotShowLayout (const QModelIndex &index)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Private Types
typedef CWindowInterface LayoutWindow
typedef std::map< std::string,
LayoutWindow * > LayoutWindowMap
Private Member Functions
LayoutWindow * createLayoutWindow (int row, CLayout *pLayout)
void deleteSelectedLayouts ()
virtual bool enterProtected ()
void showButtons ()
void updateDeleteBtns ()
Private Attributes
LayoutWindowMap mLayoutWindowMap
CQLayoutsDM * mpLayoutsDM
CQSortFilterProxyModel * mpProxyModel
CQPushButtonDelegate * mpPushButtonDelegate
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 30 of file CQLayoutsWidget.h.
Member Typedef Documentation
typedef CWindowInterface CQLayoutsWidget::LayoutWindow private
Definition at line 34 of file CQLayoutsWidget.h.
typedef std::map< std::string, LayoutWindow * > CQLayoutsWidget::LayoutWindowMap private
Definition at line 36 of file CQLayoutsWidget.h.
Constructor & Destructor Documentation
CQLayoutsWidget::CQLayoutsWidget (QWidget * parent)
Definition at line 44 of file CQLayoutsWidget.cpp.
References COL_ROW_NUMBER, COL_SHOW, dataChanged(), CQIconResource::icon(), mpLayoutsDM, mpProxyModel, mpPushButtonDelegate, CopasiWidget::protectedNotify(), CQPushButtonDelegate::PushButton, slotFilterChanged(), slotShowLayout(), and CQIconResource::unknown.
   : CopasiWidget(parent)
 {
   setupUi(this);
   // Create Source Data Model.
   mpLayoutsDM = new CQLayoutsDM(this);
   // Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpProxyModel->setSourceModel(mpLayoutsDM);
   mpTblLayouts->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblLayouts->verticalHeader()->hide();
   mpTblLayouts->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   mpTblLayouts->setModel(mpProxyModel);
   mpPushButtonDelegate = new CQPushButtonDelegate(CQIconResource::icon(CQIconResource::unknown), QString(), CQPushButtonDelegate::PushButton, this);
   mpTblLayouts->setItemDelegateForColumn(COL_SHOW, mpPushButtonDelegate);
   // Connect the table widget
   connect(mpLayoutsDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpLayoutsDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
   connect(mpPushButtonDelegate, SIGNAL(clicked(const QModelIndex &)), this, SLOT(slotShowLayout(const QModelIndex &)));
 }
CQLayoutsWidget::~CQLayoutsWidget () virtual
Definition at line 78 of file CQLayoutsWidget.cpp.
References mpProxyModel, and pdelete.
 {
   pdelete(mpProxyModel);
 }
Member Function Documentation
CQLayoutsWidget::LayoutWindow * CQLayoutsWidget::createLayoutWindow (int row, CLayout * pLayout) private
This creates a new layout window.
This creates a new layout window and return a pointer to it. In case of an error, NULL is returned.
Definition at line 367 of file CQLayoutsWidget.cpp.
References CWindowInterface::addToMainWindow(), CCopasiRootContainer::getConfiguration(), CCopasiRootContainer::getDatamodelList(), CLayout::getKey(), CCopasiObject::getObjectName(), and mLayoutWindowMap.
Referenced by slotBtnNewClicked(), and slotShowLayout().
 {
   if (pLayout == NULL || row < 0) return NULL;
   LayoutWindow * pWin = NULL;
 #ifndef DISABLE_QT_LAYOUT_RENDERING
   if (CCopasiRootContainer::getConfiguration()->useOpenGL())
     {
       pWin = new CQNewMainWindow((*CCopasiRootContainer::getDatamodelList())[0]);
       (static_cast<CQNewMainWindow*>(pWin))->slotLayoutChanged(row);
     }
   else
     {
       pWin = new CQAnimationWindow(pLayout, (*CCopasiRootContainer::getDatamodelList())[0]);
     }
 #else
   pWin = new CQNewMainWindow((*CCopasiRootContainer::getDatamodelList())[0]);
   (static_cast<CQNewMainWindow*>(pWin))->slotLayoutChanged(row);
 #endif //DISABLE_QT_LAYOUT_RENDERING
   std::string title = "COPASI Diagram: "  + pLayout->getObjectName();
   pWin->setWindowTitle(title.c_str());
   pWin->addToMainWindow();
   pWin->resize(900, 600);
   mLayoutWindowMap[pLayout->getKey()] = pWin;
   return pWin;
 }
void CQLayoutsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 348 of file CQLayoutsWidget.cpp.
References showButtons(), and updateDeleteBtns().
Referenced by CQLayoutsWidget(), enterProtected(), and slotBtnNewClicked().
 {
   mpTblLayouts->resizeColumnsToContents();
   updateDeleteBtns();
   showButtons();
 }
void CQLayoutsWidget::deleteLayoutWindows ()
Definition at line 100 of file CQLayoutsWidget.cpp.
References mLayoutWindowMap.
Referenced by slotBtnClearClicked(), ListViews::slotNotify(), and ListViews::~ListViews().
 {
   LayoutWindowMap::iterator it = mLayoutWindowMap.begin(), endit = mLayoutWindowMap.end();
   while (it != endit)
     {
       delete it->second;
       ++it;
     }
   mLayoutWindowMap.clear();
 }
void CQLayoutsWidget::deleteSelectedLayouts () private
Definition at line 113 of file CQLayoutsWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), mLayoutWindowMap, mpLayoutsDM, mpProxyModel, CQLayoutsDM::removeRows(), and CQLayoutsDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblLayouts->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpLayoutsDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty()) return;
   // We need to make sure that we remove the window mapped for each layout
   QModelIndexList::const_iterator it = mappedSelRows.begin();
   QModelIndexList::const_iterator end = mappedSelRows.end();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CListOfLayouts * pListOfLayouts = (*CCopasiRootContainer::getDatamodelList())[0]->getListOfLayouts();
   for (; it != end; ++it)
     {
       LayoutWindowMap::iterator itWindow = mLayoutWindowMap.find((*pListOfLayouts)[it->row()]->getKey());
       if (itWindow != mLayoutWindowMap.end())
         {
           mLayoutWindowMap.erase(itWindow);
           delete itWindow->second;
         }
     }
   mpLayoutsDM->removeRows(mappedSelRows);
 }
bool CQLayoutsWidget::enterProtected () private virtual
Reimplemented from CopasiWidget.
Definition at line 158 of file CQLayoutsWidget.cpp.
References CCopasiVector< T >::begin(), dataChanged(), CCopasiVector< T >::end(), CModel::getCompartments(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getModel(), mLayoutWindowMap, mpLayoutsDM, CQLayoutsDM::setListOfLayouts(), CCopasiVector< T >::size(), and slotSelectionChanged().
Referenced by update().
 {
   if (mpTblLayouts->selectionModel() != NULL)
     {
       disconnect(mpTblLayouts->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CListOfLayouts * pListOfLayouts = (*CCopasiRootContainer::getDatamodelList())[0]->getListOfLayouts();
   mpLayoutsDM->setListOfLayouts(pListOfLayouts);
   // check if we have at least a compartment
   // that we can lay out.
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   if (pDataModel != NULL &&
       pDataModel->getModel() != NULL &&
       pDataModel->getModel()->getCompartments().size() > 0)
     {
       mpBtnNew->setEnabled(true);
     }
   else
     {
       mpBtnNew->setEnabled(false);
     }
   // We need to make sure that we have a window mapped for each layout
   CListOfLayouts::const_iterator it = pListOfLayouts->begin();
   CListOfLayouts::const_iterator end = pListOfLayouts->end();
   for (; it != end; ++it)
     {
       LayoutWindowMap::iterator pos = mLayoutWindowMap.find((*it)->getKey());
       // if this layout does not have an entry in the layout window map, add one
       if (pos == mLayoutWindowMap.end())
         {
           mLayoutWindowMap.insert(std::pair<std::string, LayoutWindow*>((*it)->getKey(), (LayoutWindow*)NULL));
         }
     }
   connect(mpTblLayouts->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   dataChanged(QModelIndex(), QModelIndex());
   return true;
 }
bool CQLayoutsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 95 of file CQLayoutsWidget.cpp.
 {
   return true;
 }
void CQLayoutsWidget::showButtons () private
Definition at line 208 of file CQLayoutsWidget.cpp.
References COL_SHOW, mpLayoutsDM, mpProxyModel, and CQLayoutsDM::rowCount().
Referenced by dataChanged().
 {
   int i, imax = mpLayoutsDM->rowCount();
   for (i = 0; i < imax; ++i)
     {
       this->mpTblLayouts->openPersistentEditor(mpProxyModel->index(i, COL_SHOW, QModelIndex()));
     }
 }
void CQLayoutsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 316 of file CQLayoutsWidget.cpp.
References CQLayoutsDM::clear(), deleteLayoutWindows(), mpLayoutsDM, and CQMessageBox::question().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Layouts?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpLayoutsDM->clear();
       deleteLayoutWindows();
     }
 }
void CQLayoutsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 309 of file CQLayoutsWidget.cpp.
References deleteSelectedLayouts().
 {
   if (mpTblLayouts->hasFocus())
     {deleteSelectedLayouts();}
 }
void CQLayoutsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 234 of file CQLayoutsWidget.cpp.
References CListOfLayouts::addLayout(), CCopasiSpringLayout::createLayout(), createLayoutWindow(), dataChanged(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getListOfLayouts(), CCopasiDataModel::getModel(), CQAutolayoutWizard::getSelectedCompartments(), CQAutolayoutWizard::getSelectedMetabolites(), CQAutolayoutWizard::getSelectedReactions(), CQAutolayoutWizard::getSideMetabolites(), hasLayout(), CQLayoutsDM::insertRows(), mpLayoutsDM, CCopasiObject::setObjectName(), CCopasiVector< T >::size(), and CQAnimationWindow::slotAutoLayout().
 {
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   const CModel* pModel = pDataModel->getModel();
   assert(pModel != NULL);
   std::string name = "COPASI autolayout";
   int ncount = 1;
   while (hasLayout(*(pDataModel->getListOfLayouts()), name))
     {
       std::stringstream str;
       str << "COPASI autolayout " << ncount++;
       name = str.str();
     }
   CQAutolayoutWizard pWizard(*pModel);
   if (pWizard.exec() != QDialog::Accepted)
     return;
   // add the layout to the datamodel
   std::map<std::string, std::string> m;
   CListOfLayouts * pListOfLayouts = pDataModel->getListOfLayouts();
   // create the random layout
   CCopasiSpringLayout::Parameters p;
   CLayout* pLayout = CCopasiSpringLayout::createLayout(
                        pDataModel, pWizard.getSelectedCompartments(),
                        pWizard.getSelectedReactions(),
                        pWizard.getSelectedMetabolites(),
                        pWizard.getSideMetabolites(),
                        &p);
   pLayout->setObjectName(name);
   pListOfLayouts->addLayout(pLayout, m);
   // update the table
   mpLayoutsDM->insertRows(pListOfLayouts->size() - 1, 1);
   dataChanged(QModelIndex(), QModelIndex());
   LayoutWindow *window = createLayoutWindow(pListOfLayouts->size() - 1, pLayout);
   CQNewMainWindow* pWin = dynamic_cast<CQNewMainWindow*>(window);
 #ifndef DISABLE_QT_LAYOUT_RENDERING
   CQAnimationWindow* pAnim = dynamic_cast<CQAnimationWindow*>(window);
   if (pAnim != NULL)
     {
       pAnim->show();
       // now we create the spring layout
       pAnim->slotAutoLayout();
     }
   else
 #endif //DISABLE_QT_LAYOUT_RENDERING
     if (pWin != NULL)
       {
         pWin->updateRenderer();
         pWin->setMode();
         // show the new layout
         pWin->show();
         pWin->redrawNow();
         // now we create the spring layout
         pWin->slotRunSpringLayout();
       }
     else
       {
         delete pLayout;
       }
 }
void CQLayoutsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 336 of file CQLayoutsWidget.cpp.
References mpLayoutsDM, mpProxyModel, CQLayoutsDM::rowCount(), and slotShowLayout().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   int row = index.row();
   if (row >= mpLayoutsDM->rowCount() || row < 0) return;
   slotShowLayout(index);
 }
void CQLayoutsWidget::slotFilterChanged () protected virtual slot
Definition at line 357 of file CQLayoutsWidget.cpp.
References mpProxyModel.
Referenced by CQLayoutsWidget().
 {
   QRegExp regExp(mpLEFilter->text(), Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQLayoutsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 329 of file CQLayoutsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
void CQLayoutsWidget::slotShowLayout (const QModelIndex & index) protected slot
Definition at line 399 of file CQLayoutsWidget.cpp.
References createLayoutWindow(), CCopasiRootContainer::getDatamodelList(), CLayout::getKey(), mLayoutWindowMap, CQNewMainWindow::setMode(), and CQNewMainWindow::slotLayoutChanged().
Referenced by CQLayoutsWidget(), and slotDoubleClicked().
 {
   int row = index.row();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CListOfLayouts* pListOfLayouts = (*CCopasiRootContainer::getDatamodelList())[0]->getListOfLayouts();
   CLayout* pLayout = (* pListOfLayouts)[row];
   std::string Key = pLayout->getKey();
   if (pLayout != NULL)
     {
       // check if we already have a widget for the layout
       // if yes, open it, else create one and add it to the map
       LayoutWindow * pLayoutWindow = NULL;
       LayoutWindowMap::iterator pos = mLayoutWindowMap.find(Key);
       if (pos != mLayoutWindowMap.end())
         {
           pLayoutWindow = pos->second;
         }
       if (pLayoutWindow == NULL)
         {
           pLayoutWindow = createLayoutWindow(row, pLayout);
           // need to add it to the list, so the window can be deleted later
           mLayoutWindowMap[pLayout->getKey()] = pLayoutWindow;
         }
       if (pLayoutWindow != NULL)
         {
           CQNewMainWindow* cqWin = dynamic_cast<CQNewMainWindow*>(pLayoutWindow);
           if (cqWin != NULL)
             {
               cqWin ->slotLayoutChanged(row);
               cqWin ->setMode();
             }
           pLayoutWindow->show();
           pLayoutWindow->showNormal();
           pLayoutWindow->activateWindow();
         }
     }
   else
     {
       //std::cerr << "Could not find layout." << std::endl;
     }
 }
bool CQLayoutsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 84 of file CQLayoutsWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQLayoutsWidget::updateDeleteBtns () private
Definition at line 151 of file CQLayoutsWidget.cpp.
References mpProxyModel.
Referenced by dataChanged(), and slotSelectionChanged().
 {
   mpBtnDelete->setEnabled(mpTblLayouts->selectionModel()->selectedRows().size() > 0);
   mpBtnClear->setEnabled(mpProxyModel->rowCount() > 0);
 }
Member Data Documentation
LayoutWindowMap CQLayoutsWidget::mLayoutWindowMap private
Definition at line 50 of file CQLayoutsWidget.h.
Referenced by createLayoutWindow(), deleteLayoutWindows(), deleteSelectedLayouts(), enterProtected(), and slotShowLayout().
CQLayoutsDM* CQLayoutsWidget::mpLayoutsDM private
Definition at line 48 of file CQLayoutsWidget.h.
Referenced by CQLayoutsWidget(), deleteSelectedLayouts(), enterProtected(), showButtons(), slotBtnClearClicked(), slotBtnNewClicked(), and slotDoubleClicked().
CQSortFilterProxyModel* CQLayoutsWidget::mpProxyModel private
Definition at line 49 of file CQLayoutsWidget.h.
Referenced by CQLayoutsWidget(), deleteSelectedLayouts(), showButtons(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQLayoutsWidget().
CQPushButtonDelegate* CQLayoutsWidget::mpPushButtonDelegate private
Definition at line 51 of file CQLayoutsWidget.h.
Referenced by CQLayoutsWidget().
The documentation for this class was generated from the following files:
CQLayoutsWidget.h
CQLayoutsWidget.cpp