COPASI API: CEFMAlgorithm::CSpeciesOrderNode Class Reference
CEFMAlgorithm::CSpeciesOrderNode Class Reference
Public Member Functions
CSpeciesOrderNode (const CSpeciesOrderNode &src)
CSpeciesOrderNode (const size_t &index, const CTableauMatrix &matrix)
void update (const CTableauMatrix &matrix)
~CSpeciesOrderNode ()
Public Member Functions inherited from CCopasiNode< size_t >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Private Member Functions
CSpeciesOrderNode ()
Private Attributes
std::vector< size_t > mTableauLines
Additional Inherited Members
Public Types inherited from CCopasiNode< size_t >
typedef size_t Data
Protected Member Functions inherited from CCopasiNode< size_t >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CCopasiNode< size_t >
Data mData
Detailed Description
Definition at line 44 of file CEFMAlgorithm.h.
Constructor & Destructor Documentation
CEFMAlgorithm::CSpeciesOrderNode::CSpeciesOrderNode () private
CEFMAlgorithm class. Used to calculate elementary flux modes
Created for COPASI by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 35 of file CEFMAlgorithm.cpp.
                                                  :
   CCopasiNode< size_t >(),
   mTableauLines()
 {}
CEFMAlgorithm::CSpeciesOrderNode::CSpeciesOrderNode (const CSpeciesOrderNode & src)
Definition at line 40 of file CEFMAlgorithm.cpp.
                                                                               :
   CCopasiNode< size_t >(src),
   mTableauLines(src.mTableauLines)
 {}
CEFMAlgorithm::CSpeciesOrderNode::CSpeciesOrderNode (const size_t & index, const CTableauMatrix & matrix)
Definition at line 45 of file CEFMAlgorithm.cpp.
References update().
                                   :
   CCopasiNode< size_t >(index),
   mTableauLines()
 {
   update(matrix);
 }
CEFMAlgorithm::CSpeciesOrderNode::~CSpeciesOrderNode ()
Definition at line 53 of file CEFMAlgorithm.cpp.
 {}
Member Function Documentation
void CEFMAlgorithm::CSpeciesOrderNode::update (const CTableauMatrix & matrix)
Definition at line 56 of file CEFMAlgorithm.cpp.
References CTableauMatrix::begin(), and CTableauMatrix::end().
Referenced by CSpeciesOrderNode().
 {
   mTableauLines.clear();
   std::list< const CTableauLine * >::const_iterator it = matrix.begin();
   std::list< const CTableauLine * >::const_iterator end = matrix.end();
   size_t TableauLineIndex = 0;
   for (; it != end; ++it, ++TableauLineIndex)
     {
       if ((*it)->getMultiplier(TableauLineIndex) != 0.0)
         {
           mTableauLines.push_back(TableauLineIndex);
         }
     }
 }
Member Data Documentation
std::vector< size_t > CEFMAlgorithm::CSpeciesOrderNode::mTableauLines private
Definition at line 60 of file CEFMAlgorithm.h.
The documentation for this class was generated from the following files:
CEFMAlgorithm.h
CEFMAlgorithm.cpp