COPASI API: CQReportsWidget Class Reference
CQReportsWidget Class Reference
#include <CQReportsWidget.h>
Public Member Functions
CQReportsWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQReportsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
virtual void keyPressEvent (QKeyEvent *ev)
Private Member Functions
void deleteSelectedReports ()
void updateDeleteBtns ()
Private Attributes
CQSortFilterProxyModel * mpProxyModel
CQReportDM * mpReportDM
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 29 of file CQReportsWidget.h.
Constructor & Destructor Documentation
CQReportsWidget::CQReportsWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 31 of file CQReportsWidget.cpp.
References COL_ROW_NUMBER, dataChanged(), CopasiWidget::mFramework, mpProxyModel, mpReportDM, CopasiWidget::protectedNotify(), setFramework(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpReportDM = new CQReportDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpTblReports->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblReports->verticalHeader()->hide();
   mpTblReports->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   setFramework(mFramework);
   // Connect the table widget
   connect(mpReportDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpReportDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
 }
CQReportsWidget::~CQReportsWidget ()
Definition at line 62 of file CQReportsWidget.cpp.
References mpProxyModel, mpReportDM, and pdelete.
 {
   pdelete(mpProxyModel);
   pdelete(mpReportDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQReportsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 189 of file CQReportsWidget.cpp.
References CopasiWidget::mFramework, setFramework(), and updateDeleteBtns().
Referenced by CQReportsWidget().
 {
   mpTblReports->resizeColumnsToContents();
   setFramework(mFramework);
   updateDeleteBtns();
 }
void CQReportsWidget::deleteSelectedReports () private
Definition at line 83 of file CQReportsWidget.cpp.
References mpProxyModel, mpReportDM, CQReportDM::removeRows(), and CQReportDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblReports->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpReportDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpReportDM->removeRows(mappedSelRows);
 }
bool CQReportsWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 133 of file CQReportsWidget.cpp.
References CopasiWidget::mFramework, mpProxyModel, mpReportDM, setFramework(), slotSelectionChanged(), and updateDeleteBtns().
Referenced by update().
 {
   if (mpTblReports->selectionModel() != NULL)
     {
       disconnect(mpTblReports->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpProxyModel->setSourceModel(mpReportDM);
   //Set Model for the TableView
   mpTblReports->setModel(NULL);
   mpTblReports->setModel(mpProxyModel);
   connect(mpTblReports->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblReports->resizeColumnsToContents();
   setFramework(mFramework);
   return true;
 }
void CQReportsWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 222 of file CQReportsWidget.cpp.
References CQReportDM::columnCount(), mpProxyModel, mpReportDM, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C && (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblReports->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpReportDM->columnCount(); ++x)
             {
               if (!mpTblReports->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpReportDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQReportsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 128 of file CQReportsWidget.cpp.
 {
   return true;
 }
void CQReportsWidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 262 of file CQReportsWidget.cpp.
References CopasiWidget::setFramework().
Referenced by CQReportsWidget(), dataChanged(), and enterProtected().
 {
   CopasiWidget::setFramework(framework);
 }
void CQReportsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 104 of file CQReportsWidget.cpp.
References CQBaseDataModel::clear(), mpReportDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Reports?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpReportDM->clear();
     }
   updateDeleteBtns();
 }
void CQReportsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 75 of file CQReportsWidget.cpp.
References deleteSelectedReports(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblReports->hasFocus())
     {deleteSelectedReports();}
   updateDeleteBtns();
 }
void CQReportsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 69 of file CQReportsWidget.cpp.
References CQBaseDataModel::insertRow(), mpReportDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpReportDM->insertRow();
   updateDeleteBtns();
 }
void CQReportsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 197 of file CQReportsWidget.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CCopasiRootContainer::getDatamodelList(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CCopasiDataModel::getReportDefinitionList(), CQBaseDataModel::isDefaultRow(), CopasiWidget::mpListView, mpProxyModel, mpReportDM, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpReportDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (!pDataModel->getModel())
     return;
   std::string key = pDataModel->getReportDefinitionList()->operator[](index.row())->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQReportsWidget::slotFilterChanged () protected virtual slot
Definition at line 256 of file CQReportsWidget.cpp.
References mpProxyModel.
Referenced by CQReportsWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Report", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQReportsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 183 of file CQReportsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQReportsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 118 of file CQReportsWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQReportsWidget::updateDeleteBtns () private
Definition at line 154 of file CQReportsWidget.cpp.
References CQBaseDataModel::isDefaultRow(), mpProxyModel, and mpReportDM.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblReports->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpReportDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
CQSortFilterProxyModel* CQReportsWidget::mpProxyModel private
Definition at line 43 of file CQReportsWidget.h.
Referenced by CQReportsWidget(), deleteSelectedReports(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQReportsWidget().
CQReportDM* CQReportsWidget::mpReportDM private
Definition at line 42 of file CQReportsWidget.h.
Referenced by CQReportsWidget(), deleteSelectedReports(), enterProtected(), keyPressEvent(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQReportsWidget().
The documentation for this class was generated from the following files:
CQReportsWidget.h
CQReportsWidget.cpp