COPASI API: ConverterASTNode Class Reference
ConverterASTNode Class Reference
#include <ConverterASTNode.h>
Public Member Functions
ConverterASTNode ()
ConverterASTNode (const ASTNode &templ)
ASTNode * removeChild (unsigned int index)
void setChildren (List *children)
Static Public Member Functions
static ASTNode * shallowCopy (const ASTNode *pOrig)
Detailed Description
Definition at line 23 of file ConverterASTNode.h.
Constructor & Destructor Documentation
ConverterASTNode::ConverterASTNode ()
Standard constructor.
Standard constructor
Definition at line 27 of file ConverterASTNode.cpp.
Referenced by ConverterASTNode(), and shallowCopy().
                                   : ASTNode()
 {};
ConverterASTNode::ConverterASTNode (const ASTNode & templ)
Constructor that makes a ConverterASTNode from an ASTNode.
Definition at line 64 of file ConverterASTNode.cpp.
References ConverterASTNode(), and isNumber().
                                                       : ASTNode(templ.getType())
 {
   if (this->getType() == AST_RATIONAL)
     {
       setValue(templ.getNumerator(), templ.getDenominator());
     }
   else if (this->getType() == AST_REAL)
     {
       setValue(templ.getReal());
     }
   else if (this->getType() == AST_REAL_E)
     {
       setValue(templ.getMantissa(), templ.getExponent());
     }
   if (this->getType() == AST_PLUS ||
       this->getType() == AST_MINUS ||
       this->getType() == AST_TIMES ||
       this->getType() == AST_DIVIDE ||
       this->getType() == AST_POWER)
     {
       this->mChar = templ.getCharacter();
     }
   else if (this->getType() == AST_INTEGER)
     {
       setValue(templ.getInteger());
     }
   if ((!this->isOperator()) && (!this->isNumber()) && !isConstant())
     {
       this->setName(templ.getName());
     }
   unsigned int counter;
   for (counter = 0; counter < templ.getNumChildren(); counter++)
     {
       this->addChild(new ConverterASTNode(*templ.getChild(counter)));
     }
 };
Member Function Documentation
ASTNode * ConverterASTNode::removeChild (unsigned int index)
Removes a child from the list of children.
This function returns true if the node represents a user defined function.
Definition at line 165 of file ConverterASTNode.cpp.
Referenced by SBMLImporter::multiplySubstanceOnlySpeciesByVolume(), SBMLImporter::replace_delay_nodes(), SBMLImporter::replaceAmountReferences(), and shallowCopy().
 {
   ASTNode * removedChild = getChild(index);
   this->ASTNode::removeChild(index);
   return removedChild;
 };
void ConverterASTNode::setChildren (List * children)
Sets the list of children to the one given as argument. The list is not copied.
Extension of the ASTNode class from libsbml. This class extends the original ASTNode by some functions to manipulate the children of a node. Sets the list of children to the one given as argument. The list is not copied.
Definition at line 39 of file ConverterASTNode.cpp.
References CCopasiVector< T >::size().
 {
   if (mNumber != NULL)
     {
       return; // cannot add children to a number type astnode
     }
   else if (mFunction != NULL)
     {
       unsigned int size = mFunction->getNumChildren();
       for (unsigned int i = mFunction->getNumChildren(); i > 0; i--)
         {
           mFunction->removeChild(i - 1);
         }
       for (unsigned int i = 0; i < children->getSize(); i++)
         {
           mFunction->addChild(static_cast<ASTNode*>(children->get(i)));
         }
     }
 };
ASTNode * ConverterASTNode::shallowCopy (const ASTNode * pOrig) static
This function returns true if the node represents a user defined function.
Constructor that makes a ConverterASTNode from an ASTNode.
Definition at line 177 of file ConverterASTNode.cpp.
References ConverterASTNode(), and removeChild().
Referenced by expand_function_calls(), replace_variable_names(), and CSBMLExporter::replaceL1IncompatibleNodes().
 {
   ConverterASTNode* pTmp = new ConverterASTNode(*pOrig);
   while (pTmp->getNumChildren() > 0)
     {
       delete pTmp->removeChild(0);
     }
   ASTNode* pCopy = pTmp->deepCopy();
   delete pTmp;
   return pCopy;
 };
The documentation for this class was generated from the following files:
ConverterASTNode.h
ConverterASTNode.cpp