COPASI API: CVector< CType > Class Template Reference
CVector< CType > Class Template Reference
#include <COptMethod.h>
Public Member Functions
CVector (size_t size=0)
CVector (const CVector< CType > &src)
CVector< CType > & operator= (const CVectorCore< CType > &rhs)
CVector< CType > & operator= (const CVector< CType > &rhs)
CVector< CType > & operator= (const CType &value)
void resize (size_t size, const bool &copy=false)
~CVector ()
Public Member Functions inherited from CVectorCore< CType >
bool applyPivot (const CVectorCore< size_t > &pivot)
CType * array ()
const CType * array () const
CVectorCore (const size_t &size=0, CType *vector=NULL)
CVectorCore (const CVectorCore< CType > &src)
CType & operator() (const size_t &row)
const CType & operator() (const size_t &row) const
CVectorCore< CType > & operator= (const CType &value)
CType & operator[] (const size_t &row)
const CType & operator[] (const size_t &row) const
size_t size () const
~CVectorCore ()
Protected Member Functions
void copy (const CVectorCore< CType > &rhs)
Additional Inherited Members
Public Types inherited from CVectorCore< CType >
typedef CType elementType
Protected Attributes inherited from CVectorCore< CType >
size_t mSize
CType * mVector
Detailed Description
template<class CType>
class CVector< CType >
Template class CVector < class CType > This template class is a simple vector class allowing standard C-style and fortran style access to the elements. It also supplies an ostream operator.
Definition at line 41 of file COptMethod.h.
Constructor & Destructor Documentation
template<class CType> CVector< CType >::CVector (size_t size = 0) inline
Default constructor
Parameters
size_t size (default = 0)
Definition at line 231 of file CVector.h.
                            :
     CVectorCore< CType >(0, NULL)
   {
     resize(size);
   }
template<class CType> CVector< CType >::CVector (const CVector< CType > & src) inline
Copy constructor
Parameters
const CVector <CType> & src
Definition at line 241 of file CVector.h.
                                       :
     CVectorCore< CType >(0, NULL)
   {
     copy(src);
   }
template<class CType> CVector< CType >::~CVector () inline
Destructor.
Definition at line 250 of file CVector.h.
   {
     if (CVectorCore< CType >::mVector != NULL)
       delete [] CVectorCore< CType >::mVector;
   }
Member Function Documentation
template<class CType> void CVector< CType >::copy (const CVectorCore< CType > & rhs) inline protected
Definition at line 360 of file CVector.h.
Referenced by CVector< CProcessReportItem * >::CVector(), CVector< CProcessReportItem * >::operator=(), and CVector< CProcessReportItem * >::resize().
   {
     if (this != &rhs)
       {
         if (CVectorCore< CType >::mSize != rhs.size())
           {
             resize(rhs.size());
           }
         if (CVectorCore< CType >::mSize != 0)
           {
             memcpy((void *) CVectorCore< CType >::mVector,
                    (void *) rhs.array(),
                    CVectorCore< CType >::mSize * sizeof(CType));
           }
       }
   }
template<class CType> CVector< CType >& CVector< CType >::operator= (const CVectorCore< CType > & rhs) inline
Assignment operator
Parameters
const CVectorCore <CType> & rhs
Returns
CVector <CType> & lhs
Definition at line 261 of file CVector.h.
   {
     copy(rhs);
     return * this;
   }
template<class CType> CVector< CType >& CVector< CType >::operator= (const CVector< CType > & rhs) inline
Assignment operator
Parameters
const CVector <CType> & rhs
Returns
CVector <CType> & lhs
Definition at line 273 of file CVector.h.
   {
     copy(rhs);
     return * this;
   }
template<class CType> CVector< CType>& CVector< CType >::operator= (const CType & value) inline
Assignment operator
Parameters
const CType & value
Definition at line 284 of file CVector.h.
   {
     size_t i;
     CType * tmp = CVectorCore< CType >::mVector;
     for (i = 0; i < CVectorCore< CType >::mSize; i++, tmp++)
       {
         *tmp = value;
       }
     return *this;
   }
template<class CType> void CVector< CType >::resize (size_t size, const bool & copy = false) inline
Resize the vector. The previous content is lost
Parameters
size_t size
Definition at line 301 of file CVector.h.
Referenced by CProcessReport::addItem(), CMathContainer::allocate(), CHistoCurveData::boundingRect(), CLinkMatrix::build(), CSSAMethod::buildExtremeCurrents(), CModel::buildStoi(), CModel::buildUserOrder(), CEigen::calcEigenValues(), CLNAMethod::calculateCovarianceMatrixReduced(), CTSSAMethod::calculateDerivatives(), CTSSAMethod::calculateDerivativesX(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CMathModel::calculateRootDerivatives(), CExperimentSet::calculateStatistics(), CFitProblem::calculateStatistics(), COptProblem::calculateStatistics(), CExperiment::calculateStatistics(), CMCAMethod::calculateUnscaledConcentrationCC(), CFluxScore::CFluxScore(), CMCAMethod::checkSummationTheorems(), CTimeSeries::clear(), COptMethodSS::combination(), CMathModel::compile(), CTimeSeries::compile(), CExperimentSet::compile(), CExperiment::compile(), CExperimentObjectMap::compile(), CLinkMatrix::completePivotInformation(), CMathReaction::copy(), CVector< CProcessReportItem * >::copy(), CLsodaMethod::createRootMask(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::cspstep(), CVector< CProcessReportItem * >::CVector(), CLsodaMethod::destroyRootMask(), CMathModel::determineInitialRoots(), CILDMMethod::deuflhard(), CILDMModifiedMethod::deuflhard_metab(), CStepMatrixColumn::getAllUnsetBitIndexes(), CStepMatrix::getUnsetBitIndexes(), CMathContainer::init(), CExperiment::initExtendedTimeSeries(), CopasiPlot::initFromSpec(), CMathReaction::initialize(), COptMethodEP::initialize(), COptMethodSteepestDescent::initialize(), COptMethodStatistics::initialize(), CRandomSearch::initialize(), COptMethodDE::initialize(), COptMethodSRES::initialize(), COptMethodPS::initialize(), COptMethodGA::initialize(), COptMethodGASR::initialize(), COptMethodHookeJeeves::initialize(), COptMethodLevenbergMarquardt::initialize(), COptMethodNelderMead::initialize(), COptMethodSA::initialize(), COptMethodCoranaWalk::initialize(), COptMethodPraxis::initialize(), COptMethodTruncatedNewton::initialize(), CFitProblem::initialize(), COptProblem::initialize(), CLyapTask::initialize(), COptMethodSS::initialize(), CNewtonMethod::initialize(), CProcessQueue::initialize(), CEigen::initialize(), CTSSAMethod::initializeAtol(), CModel::initializeAtolVector(), CHybridMethodODE45::initMethod(), CHybridMethodLSODA::initMethod(), CLyapTask::initObjects(), CTSSAMethod::integrationMethodStart(), LUfactor(), CTSSAMethod::mat_anal_fast_space_thomas(), CTSSAMethod::mat_anal_metab(), CTSSAMethod::mat_anal_mod(), CILDMMethod::newton(), CILDMModifiedMethod::newton_for_timestep(), CILDMModifiedMethod::newton_new(), COptMethodLevenbergMarquardt::optimise(), COptMethodEP2::optimise(), partialSortWithPivot(), CExperiment::read(), CTSSAMethod::schur(), CTSSAMethod::schur_desc(), CFitProblem::setResidualsRequired(), CHybridMethodODE45::setupReactionFlags(), CStateTemplate::setUserOrder(), CProgressBar::slotAddItem(), CNewtonMethod::solveJacobianXeqB(), sortWithPivot(), CILDMMethod::start(), CILDMModifiedMethod::start(), CTauLeapMethod::start(), CStochDirectMethod::start(), CCSPMethod::start(), CLyapWolfMethod::start(), CTrajAdaptiveSA::start(), CLsodaMethod::start(), CTrajectoryMethodDsaLsodar::start(), CILDMMethod::step(), CILDMModifiedMethod::step(), CTSSAMethod::sylvester(), and CCSPMethod::yCorrection().
   {
     //TODO: maybe we should only resize if the vector gets bigger
     //or much smaller?
     if (size == CVectorCore< CType >::mSize) return;
     size_t OldSize = CVectorCore< CType >::mSize;
     CType * OldVector = CVectorCore< CType >::mVector;
     //TODO: maybe we should only resize if the vector gets bigger
     //or much smaller?
     CVectorCore< CType >::mSize = size;
     CVectorCore< CType >::mVector = NULL;
     if (CVectorCore< CType >::mSize > 0)
       {
         try
           {
             // We need to detect size_t overflow
             if ((C_FLOAT64) CVectorCore< CType >::mSize * (C_FLOAT64) sizeof(CType) >= (C_FLOAT64) std::numeric_limits< size_t >::max())
               {
                 CVectorCore< CType >::mVector = NULL;
               }
             else
               {
                 CVectorCore< CType >::mVector = new CType[CVectorCore< CType >::mSize];
               }
           }
         catch (...)
           {
             CVectorCore< CType >::mSize = 0;
             CVectorCore< CType >::mVector = NULL;
           }
       }
     if (copy &&
         CVectorCore< CType >::mVector != NULL &&
         OldVector != NULL)
       {
         memcpy((void *) CVectorCore< CType >::mVector,
                (void *) OldVector,
                std::min(CVectorCore< CType >::mSize, OldSize) * sizeof(CType));
       }
     if (OldVector != NULL)
       {
         delete [] OldVector;
       }
     // Check if allocation failed
     if (CVectorCore< CType >::mVector == NULL &&
         size > 0)
       {
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCopasiBase + 1, size * sizeof(CType));
       }
   }
The documentation for this class was generated from the following files:
COptMethod.h
CVector.h