COPASI API: CCopasiVector< T > Class Template Reference
CCopasiVector< T > Class Template Reference
#include <compare_utilities.h>
Public Types
typedef std::vector< CType * >
::const_iterator const_iterator
typedef std::vector< CType * >
::iterator iterator
typedef std::vector< CType * >
::value_type value_type
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
virtual bool add (const CType &src)
virtual bool add (CType *src, bool adopt=false)
iterator begin ()
const_iterator begin () const
CCopasiVector (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const unsigned C_INT32 &flag=CCopasiObject::Vector)
CCopasiVector (const CCopasiVector< CType > &src, const CCopasiContainer *pParent=NULL)
virtual void cleanup ()
virtual void clear ()
void deepCopy (const CCopasiVector< CType > &source)
iterator end ()
const_iterator end () const
virtual size_t getIndex (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &name) const
CCopasiVector< CType > & operator= (const CCopasiVector< CType > &rhs)
CCopasiVector< CType > & operator= (const std::vector< CType * > &rhs)
const value_type & operator[] (const size_t &index) const
value_type & operator[] (const size_t &index)
virtual void remove (const size_t &index)
virtual bool remove (CCopasiObject *pObject)
virtual void resize (const size_t &newSize)
virtual size_t size () const
virtual void swap (const size_t &indexFrom, const size_t &indexTo)
virtual ~CCopasiVector ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiVector< CType > &d)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
template<typename T>
class CCopasiVector< T >
CCopasiXMLInterface class. The class CCopasiXMLInterface is the interface to various XML document containing COPASI relevant information.
Created for COPASI by Stefan Hoops 2003
Definition at line 34 of file compare_utilities.h.
Member Typedef Documentation
template<typename T> typedef std::vector< CType * >::const_iterator CCopasiVector< T >::const_iterator
Definition at line 57 of file CCopasiVector.h.
template<typename T> typedef std::vector< CType * >::iterator CCopasiVector< T >::iterator
Definition at line 56 of file CCopasiVector.h.
template<typename T> typedef std::vector< CType * >::value_type CCopasiVector< T >::value_type
Definition at line 55 of file CCopasiVector.h.
Constructor & Destructor Documentation
template<typename T> CCopasiVector< T >::CCopasiVector (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL, const unsigned C_INT32 & flag = CCopasiObject::Vector) inline
Default constructor
Parameters
const const std::string & name (Default: "NoName")
const CCopasiContainer * pParent (Default: NULL)
const size_t & flag (Default: flag | CCopasiObject::Vector)
Definition at line 68 of file CCopasiVector.h.
                                            :
       std::vector< CType * >(),
       CCopasiContainer(name, pParent, "Vector", flag | CCopasiObject::Vector)
   {CONSTRUCTOR_TRACE;}
template<typename T> CCopasiVector< T >::CCopasiVector (const CCopasiVector< CType > & src, const CCopasiContainer * pParent = NULL) inline
Copy constructor
Parameters
const CCopasiVector < CType > & src
const CCopasiContainer * pParent (Default: NULL)
Definition at line 81 of file CCopasiVector.h.
                                                         :
       std::vector< CType * >(src),
       CCopasiContainer(src, pParent)
   {
     CONSTRUCTOR_TRACE;
     size_t i, imax = size();
     iterator Target = begin();
     const_iterator Source = src.begin();
     for (i = 0; i < imax; i++, Target++, Source++)
       {
         try
           {
             *Target = new CType(**Source, this);
           }
         catch (...)
           {
             *Target = NULL;
           }
         if (*Target == NULL)
           CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCopasiBase + 1, imax * sizeof(CType));
       }
   }
template<typename T> virtual CCopasiVector< T >::~CCopasiVector () inline virtual
Destructor
Definition at line 111 of file CCopasiVector.h.
   {
     cleanup();
     DESTRUCTOR_TRACE;
   }
Member Function Documentation
template<typename T> virtual bool CCopasiVector< T >::add (const CType & src) inline virtual
Add a copy of the object to the end of the vector.
Parameters
const CType & src
Returns
bool success.
Reimplemented in CCopasiVectorN< CType >.
Definition at line 223 of file CCopasiVector.h.
Referenced by CLGroup::addChildElement(), CLRenderInformationBase::addColorDefinition(), CLayout::addCompartmentGlyph(), CCopasiRootContainer::addDatamodel(), CChemEq::addElement(), CLayout::addGeneralGlyph(), CListOfLayouts::addGlobalRenderInformation(), CLRenderInformationBase::addGradientDefinition(), CLGradientBase::addGradientStop(), CLRenderInformationBase::addLineEnding(), CLayout::addLocalRenderInformation(), CLayout::addMetaboliteGlyph(), CLReactionGlyph::addMetabReferenceGlyph(), CLayout::addReactionGlyph(), CLGeneralGlyph::addReferenceGlyph(), SliderDialog::addSlider(), CLLocalRenderInformation::addStyle(), CLGlobalRenderInformation::addStyle(), CLGeneralGlyph::addSubglyph(), CLayout::addTextGlyph(), CModel::buildMoieties(), CLayout::CLayout(), CLGlobalRenderInformation::CLGlobalRenderInformation(), CLGroup::CLGroup(), CLLocalRenderInformation::CLLocalRenderInformation(), CLRenderInformationBase::CLRenderInformationBase(), CMathModel::compile(), CMIRIAMInfo::createBiologicalDescription(), CLRenderInformationBase::createColorDefinition(), CMIRIAMInfo::createCreator(), CLGroup::createCurve(), CMathContainer::createDiscontinuityDataEvent(), CLGroup::createEllipse(), CLGradientBase::createGradientStop(), CLGroup::createGroup(), CLGroup::createImage(), CPlotSpecification::createItem(), CLRenderInformationBase::createLinearGradientDefinition(), CLRenderInformationBase::createLineEnding(), CModel::createMetabolite(), CMIRIAMInfo::createModification(), CLGroup::createPolygon(), CLRenderInformationBase::createRadialGradientDefinition(), CLGroup::createRectangle(), CMIRIAMInfo::createReference(), CLLocalRenderInformation::createStyle(), CLGlobalRenderInformation::createStyle(), CLGroup::createText(), CCopasiXMLParser::ListOfLayoutsElement::end(), CModel::initializeMetabolites(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), loadDefaultStyles(), CQEventWidget1::loadFromEvent(), CMIRIAMInfo::loadModifications(), CMIRIAMInfo::loadReferences(), CCopasiVector< CLGeneralGlyph >::operator=(), CQPlotSubwidget::saveToPlotSpec(), CQEventWidget1::slotAddTarget(), CCopasiXMLParser::MetaboliteElement::start(), CCopasiXMLParser::SliderElement::start(), and CExperiment::updateFittedPoints().
   {
     CType * Element;
     try
       {
         Element = new CType(src);
       }
     catch (...)
       {
         Element = NULL;
       }
     if (Element == NULL)
       CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCopasiBase + 1, sizeof(CType));
     // This is not very efficient !!!
     // It results in a lot of resizing of the vector !!!
     std::vector< CType * >::push_back(Element);
     return CCopasiContainer::add(Element);
   }
template<typename T> virtual bool CCopasiVector< T >::add (CType * src, bool adopt = false) inline virtual
Add an object to the end of the vector, if adobt is true the vector. becomes the parent of the object.
Parameters
CType * src
const bool & adopt (Default: false)
Returns
bool success
Definition at line 275 of file CCopasiVector.h.
   {
     // This is not very efficient !!!
     // It results in a lot of resizing of the vector !!!
     std::vector< CType * >::push_back(src);
     return CCopasiContainer::add(src, adopt);
   }
template<typename T> iterator CCopasiVector< T >::begin () inline
Definition at line 185 of file CCopasiVector.h.
Referenced by CQLayoutScene::addGlyph(), CMathContainer::allocate(), CModel::appendDependentCompartments(), CModel::appendDependentEvents(), CFunctionDB::appendDependentFunctions(), CModel::appendDependentMetabolites(), CModel::appendDependentModelValues(), CModel::appendDependentReactions(), CCopasiDataModel::appendDependentTasks(), CMathModel::applyInitialValues(), SBMLImporter::applyStoichiometricExpressions(), CLayoutState::applyTo(), CSBMLExporter::assignSBMLIdsToReactions(), DataModelGUI::buildChangedObjects(), CModel::buildDependencyGraphs(), CMathModel::buildDependendRefreshList(), CModel::buildInitialRefreshSequence(), CModel::buildInitialSequence(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CSSAMethod::buildKineticMatrix(), CModel::buildMoieties(), CModel::buildNonSimulatedSequence(), CModel::buildRedStoi(), CModel::buildSimulatedSequence(), CModel::buildStateTemplate(), CModel::buildStoi(), CModel::buildUserOrder(), CLNAMethod::calculateCovarianceMatrixReduced(), CModel::calculateElasticityMatrix(), CMCAMethod::calculateUnscaledElasticities(), CCopasiVector< CLGeneralGlyph >::CCopasiVector(), CSBMLExporter::check_for_spatial_size_units(), CSBMLExporter::checkForInitialAssignments(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CFixLocalReactionParameters::checkModel(), CLayout::CLayout(), CLayoutState::CLayoutState(), CCopasiVector< CLGeneralGlyph >::cleanup(), CCopasiVector< CLGeneralGlyph >::clear(), CCopasiDataModel::commonAfterLoad(), CMathModel::compile(), CEvent::compile(), CMathEventN::compile(), CMetab::compile(), CReaction::compile(), CMathEvent::compile(), CModel::compile(), CMathContainer::compileEvents(), CModel::compileEvents(), CMathObject::compilePropensity(), contains_necessary_mass_action_elements(), containsKey(), CModel::convert2NonReversible(), CQSpeciesDetail::copy(), CQCompartment::copy(), ReactionsWidget1::copy(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CSBMLExporter::createCompartments(), SBMLImporter::createCReactionFromReaction(), COutputAssistant::createDefaultOutput(), CSBMLExporter::createEvents(), CMathObject::createExtensiveReactionRateExpression(), CModelParameterSet::createFromModel(), CCopasiSpringLayout::createLayout(), CSBMLExporter::createMetabolites(), CSBMLExporter::createParameters(), CSBMLExporter::createReactions(), CQEventDM::data(), CCopasiVector< CLGeneralGlyph >::deepCopy(), CQLayoutsWidget::enterProtected(), CSBMLExporter::exportEventAssignments(), CCopasiDataModel::exportMathModel(), CCopasiDataModel::exportMathModelToString(), CQLayoutScene::fillFromLayout(), CSBMLExporter::findAvogadro(), CModel::findMetabByName(), findObjectByDisplayName(), CChemEq::getCompartments(), CObjectLists::getEventTargets(), getFunctionForKey(), CCopasiVector< CLGeneralGlyph >::getIndex(), CCopasiVectorN< CReportDefinition >::getIndex(), CObjectLists::getListOfConstObjects(), getMetabGlyphForKey(), CEFMTask::getNetReactionData(), CCopasiVector< CLGeneralGlyph >::getObject(), CCopasiVectorN< CReportDefinition >::getObject(), getQuantityParameterOrValue(), CEFMTask::getSpeciesChanges(), getTextForItem(), CModel::getTreesWithDiscontinuities(), CFunctionDB::getUsedFunctions(), CModel::handleUnusedMetabolites(), CSBMLExporter::hasVolumeAssignment(), CMathContainer::init(), CopasiPlot::initFromSpec(), CMathReaction::initialize(), QConservedSpeciesAnimation::initialize(), QFluxModeAnimation::initialize(), QTimeCourseAnimation::initialize(), CMathContainer::initializeMathObjects(), CModel::initializeMetabolites(), CSteadyStateMethod::isEquilibrium(), CSBMLExporter::isEventSBMLCompatible(), CSBMLExporter::isModelSBMLCompatible(), CTSSAMethod::isValidProblem(), CMCAMethod::isValidProblem(), CLNAMethod::isValidProblem(), CFunctionDB::listDependentTrees(), CQMoietiesTaskResult::load(), CQBrowserPaneDM::load(), CCopasiVectorS< CMetabOld >::load(), CCopasiVectorNS< CMetab >::load(), StateSubwidget::loadCompartments(), CQEventWidget1::loadFromEvent(), CQPlotSubwidget::loadFromPlotSpec(), StateSubwidget::loadMetabolites(), StateSubwidget::loadModelValues(), StateSubwidget::loadReactions(), moveObject(), CEvent::mustBeDeleted(), CCopasiVector< CLGeneralGlyph >::operator=(), CCopasiVector< CLGeneralGlyph >::operator[](), CCopasiVectorN< CReportDefinition >::operator[](), CMoietiesProblem::printResult(), CEFMProblem::printResult(), CCopasiVector< CLGeneralGlyph >::remove(), CFunctionDB::removeFunction(), CQParameterSetsDM::removeRows(), CQFunctionDM::removeRows(), CQReactionDM::removeRows(), CQEventDM::removeRows(), CQLayoutsDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), CQSpecieDM::removeRows(), SBMLImporter::removeUnusedFunctions(), CCopasiVector< CLGeneralGlyph >::resize(), CCopasiXML::saveModel(), CQEventWidget1::saveToEvent(), CMCAMethod::scaleMCA(), CQNewMainWindow::selectMetabolite(), CQNewMainWindow::selectReaction(), SBMLImporter::setInitialValues(), CChemEq::setMultiplicity(), CQEFMSpeciesDM::setTask(), CQParameterOverviewWidget::slotBtnNew(), CQParameterOverviewWidget::slotBtnSaveAs(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethodDsaLsodar::start(), CCopasiVector< CLGeneralGlyph >::swap(), CLayoutState::tagLayout(), CExperiment::updateFittedPointValues(), CExperiment::updateFittedPointValuesFromExtendedTimeSeries(), updateLayoutList(), CModel::updateMatrixAnnotations(), CModel::updateMoietyValues(), updateRenderInformationList(), and CModel::updateSimulatedValues().
   {return std::vector< CType * >::begin();}
template<typename T> const_iterator CCopasiVector< T >::begin () const inline
Definition at line 188 of file CCopasiVector.h.
   {return std::vector< CType * >::begin();}
template<typename T> virtual void CCopasiVector< T >::cleanup () inline virtual
Cleanup
Reimplemented in CReportDefinitionVector, and COutputDefinitionVector.
Definition at line 200 of file CCopasiVector.h.
Referenced by CModel::buildMoieties(), CPlotSpecification::cleanup(), CFunctionParameters::cleanup(), CChemEq::cleanup(), CFunctionDB::cleanup(), CCompartment::cleanup(), CKinFunction::createParameters(), CCopasiVector< CLGeneralGlyph >::deepCopy(), CSSAMethod::initialize(), CModel::load(), CCopasiVectorS< CMetabOld >::load(), CCopasiVectorNS< CMetab >::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), CMIRIAMInfo::loadModifications(), CMIRIAMInfo::loadReferences(), CCopasiVector< CLGeneralGlyph >::operator=(), and CCopasiVector< CLGeneralGlyph >::~CCopasiVector().
   {
     iterator it = begin();
     iterator End = end();
     for (; it != End; it++)
       if (*it)
         if ((*it)->getObjectParent() == this)
           {
             CCopasiContainer::remove(*it);
             (*it)->setObjectParent(NULL);
             delete(*it);
             *it = NULL;
           }
     CCopasiVector< CType >::clear();
   }
template<typename T> virtual void CCopasiVector< T >::clear () inline virtual
Definition at line 431 of file CCopasiVector.h.
Referenced by CCopasiVector< CLGeneralGlyph >::cleanup(), CModel::clearMoieties(), CMathModel::compile(), CMathContainer::init(), CModel::initializeMetabolites(), CQEventWidget1::loadFromEvent(), CLGeneralGlyph::operator=(), CCopasiXMLParser::ListOfModelParameterSetsElement::start(), CCopasiXMLParser::ListOfReactionsElement::start(), CCopasiXMLParser::ListOfCompartmentsElement::start(), and CExperiment::updateFittedPoints().
   {
     size_t OldSize = size();
     if (OldSize == 0) return; // Nothing to do.
     iterator Target = begin();
     iterator End = end();
     for (; Target != End; Target++)
       if (*Target)
         {
           if ((*Target)->getObjectParent() == this)
             {
               CCopasiContainer::remove(*Target);
               (*Target)->setObjectParent(NULL);
               delete *Target;
             }
           else
             CCopasiContainer::remove(*Target);
         }
     std::vector< CType * >::resize(0);
   }
template<typename T> void CCopasiVector< T >::deepCopy (const CCopasiVector< CType > & source) inline
This creates a deep copy of the source, i.e., all objects are copied and the parent of these copies is the current vector.
Parameters
const CCopasiVector< CType > & source
Definition at line 160 of file CCopasiVector.h.
Referenced by CFunctionParameters::operator=().
   {
     cleanup();
     resize(source.size());
     size_t i, imax = size();
     iterator Target = begin();
     const_iterator Source = source.begin();
     for (i = 0; i < imax; i++, Target++, Source++)
       {
         try
           {
             *Target = new CType(**Source, this);
           }
         catch (...)
           {
             *Target = NULL;
           }
         if (*Target == NULL)
           CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCopasiBase + 1, imax * sizeof(CType));
       }
   }
template<typename T> iterator CCopasiVector< T >::end () inline
Definition at line 191 of file CCopasiVector.h.
Referenced by CQLayoutScene::addGlyph(), CMathContainer::allocate(), CModel::appendDependentCompartments(), CModel::appendDependentEvents(), CFunctionDB::appendDependentFunctions(), CModel::appendDependentMetabolites(), CModel::appendDependentModelValues(), CModel::appendDependentReactions(), CCopasiDataModel::appendDependentTasks(), CMathModel::applyInitialValues(), SBMLImporter::applyStoichiometricExpressions(), CLayoutState::applyTo(), CSBMLExporter::assignSBMLIdsToReactions(), DataModelGUI::buildChangedObjects(), CModel::buildDependencyGraphs(), CMathModel::buildDependendRefreshList(), CModel::buildInitialRefreshSequence(), CModel::buildInitialSequence(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CSSAMethod::buildKineticMatrix(), CModel::buildNonSimulatedSequence(), CModel::buildSimulatedSequence(), CModel::buildStateTemplate(), CModel::buildStoi(), CModel::buildUserOrder(), CLNAMethod::calculateCovarianceMatrixReduced(), CModel::calculateElasticityMatrix(), CMCAMethod::calculateUnscaledElasticities(), CSBMLExporter::check_for_spatial_size_units(), CSBMLExporter::checkForInitialAssignments(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CFixLocalReactionParameters::checkModel(), CLayout::CLayout(), CLayoutState::CLayoutState(), CCopasiVector< CLGeneralGlyph >::cleanup(), CCopasiVector< CLGeneralGlyph >::clear(), CCopasiDataModel::commonAfterLoad(), CMathModel::compile(), CEvent::compile(), CMetab::compile(), CReaction::compile(), CMathEvent::compile(), CModel::compile(), CMathContainer::compileEvents(), CModel::compileEvents(), CMathObject::compilePropensity(), contains_necessary_mass_action_elements(), containsKey(), CModel::convert2NonReversible(), CQSpeciesDetail::copy(), CQCompartment::copy(), ReactionsWidget1::copy(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CSBMLExporter::createCompartments(), SBMLImporter::createCReactionFromReaction(), COutputAssistant::createDefaultOutput(), CSBMLExporter::createEvents(), CMathObject::createExtensiveReactionRateExpression(), CModelParameterSet::createFromModel(), CCopasiSpringLayout::createLayout(), CSBMLExporter::createMetabolites(), CSBMLExporter::createParameters(), CSBMLExporter::createReactions(), CQEventDM::data(), CQLayoutsWidget::enterProtected(), CSBMLExporter::exportEventAssignments(), CCopasiDataModel::exportMathModel(), CCopasiDataModel::exportMathModelToString(), CQLayoutScene::fillFromLayout(), CSBMLExporter::findAvogadro(), findObjectByDisplayName(), CChemEq::getCompartments(), CObjectLists::getEventTargets(), getFunctionForKey(), CObjectLists::getListOfConstObjects(), getMetabGlyphForKey(), CEFMTask::getNetReactionData(), getQuantityParameterOrValue(), CEFMTask::getSpeciesChanges(), getTextForItem(), CModel::getTreesWithDiscontinuities(), CFunctionDB::getUsedFunctions(), CSBMLExporter::hasVolumeAssignment(), CopasiPlot::initFromSpec(), QConservedSpeciesAnimation::initialize(), QFluxModeAnimation::initialize(), QTimeCourseAnimation::initialize(), CMathContainer::initializeMathObjects(), CModel::initializeMetabolites(), CSteadyStateMethod::isEquilibrium(), CSBMLExporter::isEventSBMLCompatible(), CSBMLExporter::isModelSBMLCompatible(), CTSSAMethod::isValidProblem(), CMCAMethod::isValidProblem(), CLNAMethod::isValidProblem(), CFunctionDB::listDependentTrees(), CQMoietiesTaskResult::load(), CQBrowserPaneDM::load(), StateSubwidget::loadCompartments(), CQEventWidget1::loadFromEvent(), CQPlotSubwidget::loadFromPlotSpec(), StateSubwidget::loadMetabolites(), StateSubwidget::loadModelValues(), StateSubwidget::loadReactions(), moveObject(), CEvent::mustBeDeleted(), CCopasiVector< CLGeneralGlyph >::operator=(), CMoietiesProblem::printResult(), CEFMProblem::printResult(), CFunctionDB::removeFunction(), SBMLImporter::removeUnusedFunctions(), CCopasiVector< CLGeneralGlyph >::resize(), CCopasiXML::saveModel(), CQEventWidget1::saveToEvent(), CMCAMethod::scaleMCA(), CQNewMainWindow::selectMetabolite(), CQNewMainWindow::selectReaction(), SBMLImporter::setInitialValues(), CChemEq::setMultiplicity(), CQParameterOverviewWidget::slotBtnNew(), CQParameterOverviewWidget::slotBtnSaveAs(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethodDsaLsodar::start(), CLayoutState::tagLayout(), CExperiment::updateFittedPointValues(), CExperiment::updateFittedPointValuesFromExtendedTimeSeries(), updateLayoutList(), CModel::updateMoietyValues(), updateRenderInformationList(), and CModel::updateSimulatedValues().
   {return std::vector< CType * >::end();}
template<typename T> const_iterator CCopasiVector< T >::end () const inline
Definition at line 194 of file CCopasiVector.h.
   {return std::vector< CType * >::end();}
template<typename T> virtual size_t CCopasiVector< T >::getIndex (const CCopasiObject * pObject) const inline virtual
Retrieve the index of the pointed to object in the vector. If the object is not found C_INVALID_INDEX is returned.
Parameters
const CCopasiObject * pObject
Returns
size_t index
Definition at line 462 of file CCopasiVector.h.
Referenced by CQReportDefinition::btnDeleteReportClicked(), CLNAMethod::calculateCovarianceMatrixReduced(), CModel::createMetabolite(), CCopasiObject::getCN(), CCopasiVector< CLGeneralGlyph >::remove(), COutputDefinitionVector::removePlotSpec(), CReportDefinitionVector::removeReportDefinition(), CQReportDM::removeRows(), CQLayoutsDM::removeRows(), CHybridMethodODE45::setupBalances(), CHybridMethod::setupBalances(), CHybridMethodLSODA::setupBalances(), CStochMethod::setupDependencyGraphAndBalances(), and CHybridMethodODE45::setupMetab2React().
   {
     size_t i, imax = size();
     const_iterator Target = begin();
     for (i = 0; i < imax; i++, Target++)
       {
         const CCopasiObject * pTarget = static_cast< const CCopasiObject * >(*Target);
         if (pTarget == pObject)
           {
             return i;
           }
       }
     return C_INVALID_INDEX;
   }
template<typename T> virtual const CObjectInterface* CCopasiVector< T >::getObject (const CCopasiObjectName & name) const inline virtual
Retrieve a the CCopasiObject with the given name.
Parameters
const CCopasiObjectName &name
Returns
const CObjectInterface * object
Reimplemented from CCopasiContainer.
Reimplemented in CCopasiVectorN< CType >, CCopasiVectorN< CReaction >, CCopasiVectorN< CEventAssignment >, CCopasiVectorN< CFunctionParameter >, CCopasiVectorN< CCopasiTask >, CCopasiVectorN< CPlotSpecification >, CCopasiVectorN< CCompartment >, CCopasiVectorN< CModelParameterSet >, CCopasiVectorN< CEvent >, CCopasiVectorN< CMetab >, CCopasiVectorN< CFunction >, CCopasiVectorN< CModelValue >, and CCopasiVectorN< CReportDefinition >.
Definition at line 364 of file CCopasiVector.h.
   {
     size_t Index = name.getElementIndex();
     if (Index < size())
       {
         CCopasiObject * pObject = *(begin() + Index);
         if (name.getObjectType() == pObject->getObjectType())
           return pObject; //exact match of type and name
         if (name.getObjectName() == "")
           return pObject; //cn contains no "="; type cannot be checked
       }
     return NULL;
   }
template<typename T> CCopasiVector< CType >& CCopasiVector< T >::operator= (const CCopasiVector< CType > & rhs) inline
Assignment operator. The effect of this operator is that both vectors will share the same objects. However, the parentship of the objects is not affected This means that the assigned vector must be used with some care.
Parameters
const CCopasiVector< CType > & rhs
Returns
CCopasiVector< CType > & lhs
Definition at line 124 of file CCopasiVector.h.
Referenced by CCopasiVectorN< CReportDefinition >::operator=().
   {
     cleanup();
     const_iterator it = rhs.begin();
     const_iterator end = rhs.end();
     for (; it != end; ++it)
       add(*it, false);
     return *this;
   }
template<typename T> CCopasiVector< CType >& CCopasiVector< T >::operator= (const std::vector< CType * > & rhs) inline
Assignment operator.
Parameters
const std::vector< CType * > & rhs
Returns
CCopasiVector< CType > & lhs
Definition at line 142 of file CCopasiVector.h.
   {
     cleanup();
     typename std::vector< CType * >::const_iterator it = rhs.begin();
     typename std::vector< CType * >::const_iterator end = rhs.end();
     for (; it != end; ++it)
       add(*it, false);
     return *this;
   }
template<typename T> const value_type& CCopasiVector< T >::operator[] (const size_t & index) const inline
Retrieve the indexed object.
Parameters
const size_t & index
Returns
const value_type & object
Definition at line 338 of file CCopasiVector.h.
Referenced by CCopasiVectorN< CReportDefinition >::operator[]().
   {
     if (!(index < size()))
       CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCCopasiVector + 3, index, size() - 1);
     return *(begin() + index);
   }
template<typename T> value_type& CCopasiVector< T >::operator[] (const size_t & index) inline
Retrieve the indexed object.
Parameters
const size_t & index
Returns
value_type & object
Definition at line 351 of file CCopasiVector.h.
   {
     if (!(index < size()))
       CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCCopasiVector + 3, index, size() - 1);
     return *(begin() + index);
   }
template<typename T> virtual void CCopasiVector< T >::remove (const size_t & index) inline virtual
Removes the index-th element from the vector
Parameters
const size_t & index
Definition at line 287 of file CCopasiVector.h.
Referenced by CQReportDefinition::btnDeleteReportClicked(), contains_necessary_mass_action_elements(), SliderDialog::getCSlidersForObject(), CCopasiVectorN< CReportDefinition >::remove(), CMIRIAMInfo::removeBiologicalDescription(), CLRenderInformationBase::removeColorDefinition(), CMIRIAMInfo::removeCreator(), CCopasiRootContainer::removeDatamodel(), CLRenderInformationBase::removeGradientDefinition(), CLRenderInformationBase::removeLineEnding(), CModel::removeMetabolite(), CMIRIAMInfo::removeModification(), COutputDefinitionVector::removePlotSpec(), CMIRIAMInfo::removeReference(), CReportDefinitionVector::removeReportDefinition(), CQReportDM::removeRows(), SliderDialog::removeSlider(), and CQEventWidget1::slotDeleteTarget().
   {
     if (!(index < size()))
       return;
     iterator Target = begin() + index;
     if (*Target)
       {
         if ((*Target)->getObjectParent() == this)
           {
             //                (*Target)->cleanup();
             delete *Target;
           }
         else
           {
             CCopasiContainer::remove(*Target);
             std::vector< CType * >::erase(Target, Target + 1);
           }
       }
   }
template<typename T> virtual bool CCopasiVector< T >::remove (CCopasiObject * pObject) inline virtual
Removes the pointed to object from the vector
Parameters
CCopasiObject * pObject
Returns
bool success
Reimplemented from CCopasiContainer.
Definition at line 314 of file CCopasiVector.h.
   {
     const size_t index = getIndex(pObject);
     bool success = true;
     if (index != C_INVALID_INDEX)
       {
         iterator Target = begin() + index;
         std::vector< CType * >::erase(Target, Target + 1);
       }
     else
       success = false;
     success &= CCopasiContainer::remove(pObject);
     return success;
   }
template<typename T> virtual void CCopasiVector< T >::resize (const size_t & newSize) inline virtual
Resizes the vector but does not create new member objects
Parameters
const size_t & newSize
Definition at line 393 of file CCopasiVector.h.
Referenced by CCopasiVector< CLGeneralGlyph >::deepCopy(), CModel::initializeMetabolites(), CCopasiVectorS< CMetabOld >::load(), CCopasiVectorNS< CMetab >::load(), CCSPMethod::predifineAnnotation(), CCSPMethod::setAnnotationM(), and CCSPMethod::start().
   {
     size_t OldSize = size();
     if (OldSize == newSize) return; // Nothing to do.
     if (OldSize < newSize)
       {
         std::vector< CType * >::resize(newSize);
         size_t i;
         iterator Target = begin() + OldSize;
         for (i = OldSize; i < newSize; i++, Target++)
           *Target = NULL;
       }
     else
       {
         iterator Target = begin() + newSize;
         iterator End = end();
         for (; Target != End; Target++)
           if (*Target)
             {
               if ((*Target)->getObjectParent() == this)
                 {
                   CCopasiContainer::remove(*Target);
                   (*Target)->setObjectParent(NULL);
                   delete *Target;
                 }
               else
                 CCopasiContainer::remove(*Target);
             }
         std::vector< CType * >::resize(newSize);
       }
   }
template<typename T> virtual size_t CCopasiVector< T >::size () const inline virtual
Retrieves the size of the vector
Returns
size_t size
Definition at line 386 of file CCopasiVector.h.
Referenced by CModelAdd::addCompartments(), CModelAdd::addCompartmentsExpressions(), CChemEq::addElement(), CModelAdd::addEvents(), CQNewMainWindow::addGlobalRenderInfoItemsToList(), test000097::addGlobalRenderInformation(), test000097::addLocalRenderInformation(), CModelAdd::addMetabolites(), CModelAdd::addMetabolitesExpressions(), CModelAdd::addModelValues(), CModelAdd::addModelValuesExpressions(), CModelAdd::addReactions(), CLGradientBase::addSBMLAttributes(), CLRenderInformationBase::addSBMLAttributes(), CMathEventN::allocate(), CMathContainer::allocate(), CQReportDefinition::btnDeleteReportClicked(), CSSAMethod::buildKineticMatrix(), CModel::buildStateTemplate(), CModel::buildStoi(), CModel::buildUserOrder(), CLayout::calculateBoundingBox(), CLNAMethod::calculateCovarianceMatrixReduced(), CModel::calculateDerivatives(), CModel::calculateDerivativesX(), CMCAMethod::calculateUnscaledElasticities(), CCopasiVector< CLGeneralGlyph >::CCopasiVector(), CSBMLExporter::checkForEvents(), CSBMLExporter::checkForPiecewiseFunctions(), CHybridMethod::checkModel(), CHybridMethodLSODA::checkModel(), CHybridMethodODE45::checkModel(), CModelAnalyzer::checkReaction(), CLayout::CLayout(), CCopasiVector< CLGeneralGlyph >::clear(), CLGeneralGlyph::CLGeneralGlyph(), CLGroup::CLGroup(), CModel::CModel(), CSBMLExporter::collectIds(), COutputHandlerPlot::compile(), CopasiPlot::compile(), CChemEqInterface::completeCompartments(), CReactionInterface::connectNonMetabolites(), contains_necessary_mass_action_elements(), CModel::convert2NonReversible(), SBMLDocumentLoader::convertRenderInformationReferencesIds(), CArrayAnnotation::createAnnotationsCNFromCopasiVector(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCReactionFromReaction(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), CQGLNetworkPainter::createGraph(), CSBMLExporter::createKineticLaw(), CCopasiSpringLayout::createLayout(), CModel::createMetabolite(), test000097::createModel(), CKinFunction::createParameters(), COutputDefinitionVector::createPlotSpec(), CSBMLExporter::createReaction(), CLayoutInitializer::createReactionGlyph(), CReportDefinitionVector::createReportDefinition(), CSBMLExporter::createTimesTree(), CCopasiSpringLayout::createVariables(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::CSPradicalPointer(), CCSPMethod::cspstep(), CQPlotDM::data(), CQSpecieDM::data(), CCopasiVector< CLGeneralGlyph >::deepCopy(), CQPlotSubwidget::deletePlot(), CModel::determineIsAutonomous(), SBMLImporter::doMapping(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateReaction(), CQNewMainWindow::elementaryModeTriggeredSlot(), CFitProblem::elevateChildren(), CCopasiXMLParser::ListOfFunctionsElement::end(), CQLayoutsWidget::enterProtected(), SliderDialog::equivalentSliderExists(), CObjectLists::existsFixedMetab(), CODEExporter::exportCompartments(), CODEExporter::exportKineticFunction(), CODEExporterC::exportKineticFunctionGroup(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelValues(), CODEExporter::exportModelValuesExpressions(), CODEExporter::exportODEs(), CODEExporter::exportReacParamsAndFuncs(), CODEExporterC::exportTitleData(), CLayout::exportToDotFile(), CListOfLayouts::exportToSBML(), CLayout::exportToSBML(), CLGeneralGlyph::exportToSBML(), CLReactionGlyph::exportToSBML(), CModelExpansion::SetOfModelElements::fillComplete(), CQMergingData::fillTree(), CQSelectionWizardPage::fillTree(), CCopasiSpringLayout::finalizeState(), CCopasiSpringLayout::findCompartmentForReactionNode(), SBMLImporter::findCorrespondingFunction(), findFunction(), CFunctionDB::findLoadFunction(), CModel::findMetabByName(), CModel::findMoiety(), CFunctionParameters::findParameterByName(), CLRenderFlattener::flatten(), CStochMethod::generateReactionIndex(), CStochMethod::getAffects(), CLRenderInformationBase::getColorDefinition(), CChemEqInterface::getCompartment(), SliderDialog::getCSlidersForObject(), CHybridMethodODE45::getDefaultAtol(), CHybridMethodLSODA::getDefaultAtol(), CStochMethod::getDependsOn(), CMetabNameInterface::getDisplayName(), CLGroup::getElement(), Arguments::getFirstScheduledTask(), CLRenderInformationBase::getGradientDefinition(), CLGradientBase::getGradientStop(), CCopasiVector< CLGeneralGlyph >::getIndex(), CCopasiVectorN< CReportDefinition >::getIndex(), CChemEq::getLargestCompartment(), CLRenderInformationBase::getLineEnding(), ParameterTable::getListOfAllCompartmentNames(), ParameterTable::getListOfAllMetabNames(), CChemEq::getMolecularity(), CFunctionParameters::getNumberOfParametersByUsage(), CLRenderInformationBase::getNumColorDefinitions(), getNumDefaultStyles(), CLGroup::getNumElements(), CLRenderInformationBase::getNumGradientDefinitions(), CLGradientBase::getNumGradientStops(), CLRenderInformationBase::getNumLineEndings(), CModel::getNumMetabs(), CModel::getNumModelValues(), CLLocalRenderInformation::getNumStyles(), CLGlobalRenderInformation::getNumStyles(), CCopasiVector< CLGeneralGlyph >::getObject(), SEDMLUtils::getObjectForSbmlId(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CFunctionParameters::getParameterByUsage(), CCopasiSpringLayout::getPotential(), getReactionIndex(), CListOfLayouts::getRenderInformation(), CLayout::getRenderInformation(), QConservedSpeciesAnimation::getScales(), CLLocalRenderInformation::getStyle(), CLGlobalRenderInformation::getStyle(), Arguments::getTaskForName(), CModel::getTotSteps(), Arguments::handleCommandLine(), hasLayout(), CModel::hasReversibleReaction(), CMathContainer::init(), CCopasiSpringLayout::initFromLayout(), CopasiPlot::initFromSpec(), CMathReaction::initialize(), QConservedSpeciesAnimation::initialize(), CTSSAMethod::initializeIntegrationsParameter(), CModel::initializeMetabolites(), CLsodaMethod::initializeParameter(), CQLayoutScene::initializeResolver(), CHybridMethod::initMethod(), CHybridMethodODE45::initMethod(), CHybridMethodLSODA::initMethod(), CQParameterSetsDM::insertRows(), CQLayoutsDM::insertRows(), CQSpecieDM::insertRows(), CReactionInterface::isLocked(), SBMLImporter::isMassActionExpression(), CQSimpleSelectionTree::isMetaboliteNameUnique(), CMetabNameInterface::isUnique(), CTSSAMethod::isValidProblem(), CTauLeapMethod::isValidProblem(), CHybridMethod::isValidProblem(), CHybridMethodODE45::isValidProblem(), CCopasiMethod::isValidProblem(), CHybridMethodLSODA::isValidProblem(), CStochDirectMethod::isValidProblem(), CLNAMethod::isValidProblem(), CStochMethod::isValidProblem(), CTrajectoryMethodDsaLsodar::isValidProblem(), CFunctionParameters::isVector(), CODEExporterC::KineticFunction2ODEmember(), CMMLOutput::listReactionsForMetab(), CQSpeciesDetail::load(), CQExpandModelData::load(), CModel::load(), ObjectBrowserWidget::loadChild(), StateSubwidget::loadCompartments(), ObjectBrowserWidget::loadField(), CChemEqInterface::loadFromChemEq(), CQEventWidget1::loadFromEvent(), CQPlotSubwidget::loadFromPlotSpec(), StateSubwidget::loadMetabolites(), CQCompartment::loadMetaboliteTable(), StateSubwidget::loadModelValues(), CQUpdatesWidget::loadObjectsTable(), StateSubwidget::loadReactions(), CQReportDefinitionSelect::loadReportDefinitionVector(), CQLayoutMainWindow::loadSBMLFile(), main(), CModelMerging::mergeMetabolites(), CStochMethod::modelHasAssignments(), CHybridMethod::modelHasAssignments(), CHybridMethodLSODA::modelHasAssignments(), CHybridMethodODE45::modelHasAssignments(), CLayout::moveBy(), CLGeneralGlyph::moveBy(), CLReactionGlyph::moveBy(), stress_test::normalizeAndSimplifyExpressions(), stress_test::normalizeFunctionDB(), CReaction::object2variable(), operator<<(), CLGeneralGlyph::operator=(), CLReactionGlyph::operator=(), CCopasiVector< CLGeneralGlyph >::operator[](), CHybridMethod::outputData(), CHybridMethodODE45::outputData(), CHybridMethodLSODA::outputData(), CHybridMethod::outputDebug(), CHybridMethodODE45::outputDebug(), CHybridMethodLSODA::outputDebug(), placeTextGlyphs(), CQSimpleSelectionTree::populateTree(), CCSPMethod::predifineAnnotation(), Arguments::prepareModel(), CODEExporterC::preprocess(), CODEExporter::preprocess(), CModel::printParameterOverview(), CCSPMethod::printResult(), CCopasiSpringLayout::randomize(), CModelAdd::reactionInvolvesCompartment(), CQSpeciesWidget::refreshCompartments(), CCopasiVector< CLGeneralGlyph >::remove(), CLRenderInformationBase::removeColorDefinition(), CLRenderInformationBase::removeGradientDefinition(), CLRenderInformationBase::removeLineEnding(), CCopasiDataModel::removeSBMLIdFromFunctions(), SliderDialog::removeSlider(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInEvent(), CModelExpansion::replaceInModel(), CModelExpansion::replaceInReaction(), CCopasiVector< CLGeneralGlyph >::resize(), CQParameterSetsDM::rowCount(), CQLayoutsDM::rowCount(), CQModifiedDM::rowCount(), CQReferenceDM::rowCount(), CQBiologicalDescriptionDM::rowCount(), CQCreatorDM::rowCount(), CQFunctionDM::rowCount(), CQFittingWidget::runTask(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGUI(), CCopasiXML::saveLayoutList(), CCopasiXML::saveListOfGlobalRenderInformation(), CCopasiXML::saveListOfLocalRenderInformation(), CCopasiXML::saveModel(), CCopasiXML::savePlotList(), CCopasiXML::saveReportList(), CCopasiXML::saveTaskList(), CQEventWidget1::saveToEvent(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), ConverterASTNode::setChildren(), SBMLImporter::setCorrectUsage(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), CModel::setQuantityUnit(), CReaction::setScalingFactor(), COptProblem::setSubtaskType(), CQEFMSpeciesDM::setTask(), CHybridMethodODE45::setupBalances(), CHybridMethod::setupBalances(), CHybridMethodLSODA::setupBalances(), CHybridMethodODE45::setupDependencyGraph(), CHybridMethod::setupDependencyGraph(), CHybridMethodLSODA::setupDependencyGraph(), CStochMethod::setupDependencyGraphAndBalances(), CHybridMethodODE45::setupMetab2React(), CHybridMethod::setupMetab2React(), CHybridMethodLSODA::setupMetab2React(), CHybridMethod::setupMetab2ReactComplete(), CHybridMethodLSODA::setupMetab2ReactComplete(), CHybridMethod::setupMetab2ReactPlusModifier(), CHybridMethodLSODA::setupMetab2ReactPlusModifier(), CStochNextReactionMethod::setupPriorityQueue(), CHybridMethod::setupPriorityQueue(), CHybridMethodLSODA::setupPriorityQueue(), CILDMMethod::setVectors(), CCSPMethod::setVectors(), CCSPMethod::setVectorsToNaN(), CModelMerging::simpleCall(), CFunctionParameters::size(), CQEventWidget1::slotActualizeAssignmentExpression(), CQEventWidget1::slotAddTarget(), CQPlotsWidget::slotBtnActivateAllClicked(), CQMiriamWidget::slotBtnBrowseDescription(), CQMiriamWidget::slotBtnBrowseReference(), CQPlotsWidget::slotBtnDeactivateAllClicked(), CQSpeciesDetail::slotBtnNew(), CQLayoutsWidget::slotBtnNewClicked(), CQNewMainWindow::slotCalculateDimensions(), CQExpandModelData::slotCompartmentActivated(), CQMoietiesTaskResult::slotCreateGlobalQuantity(), CQEventWidget1::slotDeleteTarget(), CQNewMainWindow::slotRenderInfoChanged(), CQLayoutView::slotRenderInformationChanged(), CQNewMainWindow::slotRunRandomizeLayout(), CTauLeapMethod::start(), CStochDirectMethod::start(), CCSPMethod::start(), CTrajAdaptiveSA::start(), CStochMethod::start(), CTrajectoryMethodDsaLsodar::start(), CCopasiXMLParser::LocalRenderInformationElement::start(), CCopasiXMLParser::GlobalRenderInformationElement::start(), CModel::suitableForStochasticSimulation(), CFunctionDB::suitableFunctions(), CCopasiVector< CLGeneralGlyph >::swap(), CQFittingWidget::taskFinishedEvent(), test000069::test_bug1069(), test000073::test_bug1087(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000060::test_bug_1026(), test000061::test_bug_1044(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000021::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000032::test_hasOnlySubstanceUnits(), test000035::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000040::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000088::test_import_assignment_without_expression(), test000088::test_import_eventassignment_without_expression(), test000097::test_import_global_render_information(), test000088::test_import_initialassignment_without_expression(), test000097::test_import_local_render_information(), test000087::test_import_reaction_flux_reference_2(), test000097::test_importexport_global_render_information(), test000097::test_importexport_local_render_information(), test000097::test_importwrite_global_render_information(), test000097::test_importwrite_local_render_information(), test000078::test_l2v4_import_unordered_functions(), test000080::test_mass_action_recognition_bug(), test000092::test_miriam_export_7(), test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000092::test_miriam_import_1(), test000097::test_read_global_render_information(), test000097::test_read_local_render_information(), test000097::test_readexport_global_render_information(), test000097::test_readexport_local_render_information(), test000097::test_readwrite_global_render_information(), test000097::test_readwrite_local_render_information(), test000087::test_simulate_reaction_flux_reference_1(), test000044::test_stoichiometricExpression(), test000045::test_stoichiometricExpression(), test000046::test_stoichiometricExpression(), CLLocalRenderInformation::toSBML(), CLGlobalRenderInformation::toSBML(), CLGroup::toSBML(), CLLayoutRenderer::update_associations(), CQNewMainWindow::updateLayoutList(), CSBMLExporter::updateMIRIAMAnnotation(), CHybridMethod::updatePriorityQueue(), CHybridMethodLSODA::updatePriorityQueue(), updateRenderInformationList(), CQNewMainWindow::updateRenderInformationList(), validate(), CMMLOutput::writeDifferentialEquations(), and CMMLOutput::writeRHS().
   {return std::vector< CType * >::size();}
template<typename T> virtual void CCopasiVector< T >::swap (const size_t & indexFrom, const size_t & indexTo) inline virtual
Swap two objects in the vector.
Parameters
const size_t & indexFrom
const size_t & indexTo
Definition at line 250 of file CCopasiVector.h.
Referenced by CFunctionParameters::swap().
   {
     size_t Size = size();
     if (!(indexFrom < Size))
       CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCCopasiVector + 3, indexFrom, Size - 1);
     if (!(indexTo < Size))
       CCopasiMessage ex(CCopasiMessage::EXCEPTION, MCCopasiVector + 3, indexTo, Size - 1);
     iterator from = begin() + indexFrom;
     iterator to = begin() + indexTo;
     value_type tmp = *from;
     *from = *to;
     *to = tmp;
   }
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, const CCopasiVector< CType > & d) friend
ostream operator
Parameters
std::ostream & os
const CCopasiVector<CType> & d
Returns
std::ostream & os
Definition at line 870 of file CCopasiVector.h.
 {
   os << "   +++Vektor;  size: " << d.size() << std::endl;
   unsigned int i;
   for (i = 0; i < d.size(); i++)
     os << "   " << *(d[i]);
   if (d.size() == 0)
     os << "   empty" << std::endl;
   os << "   ---Vektor" << std::endl;
   return os;
 }
The documentation for this class was generated from the following files:
compare_utilities.h
CCopasiVector.h