COPASI API: CMiaseBaseEnhanced Class Reference
CMiaseBaseEnhanced Class Reference
#include <CMiaseBase.h>
Public Member Functions
CMiaseBaseEnhanced ()
std::string getId ()
std::string getName ()
void setId (std::string id)
void setName (std::string name)
~CMiaseBaseEnhanced ()
Public Member Functions inherited from CMiaseBase
void addAnnotation (CMiaseAnnotation *ann)
void addNotes (CMiaseNotes *notes)
CMiaseBase ()
CMiaseAnnotation * getAnnotation ()
std::string getMetaId ()
CMiaseNotes * getNotes ()
void setAnyNote (std::string anyAnnotation)
void setMetaId (std::string metaId)
void setXmlNs (std::string xmlNs)
~CMiaseBase ()
Private Attributes
std::string mId
std::string mName
Detailed Description
Definition at line 92 of file CMiaseBase.h.
Constructor & Destructor Documentation
CMiaseBaseEnhanced::CMiaseBaseEnhanced ()
Definition at line 111 of file CMiaseBase.cpp.
                                        : CMiaseBase()
 {}
CMiaseBaseEnhanced::~CMiaseBaseEnhanced ()
Definition at line 114 of file CMiaseBase.cpp.
 {}
Member Function Documentation
std::string CMiaseBaseEnhanced::getId ()
Definition at line 117 of file CMiaseBase.cpp.
References mId.
Referenced by CMiaseSed::getModel(), CMiaseSed::getOutput(), CMiaseSed::getSimulation(), CMiaseSed::getTask(), and CMiaseParser::testDataStructure().
 {
   return mId;
 }
std::string CMiaseBaseEnhanced::getName ()
Definition at line 122 of file CMiaseBase.cpp.
References mName.
Referenced by CMiaseParser::testDataStructure().
 {
   return mName;
 }
void CMiaseBaseEnhanced::setId (std::string id)
Definition at line 127 of file CMiaseBase.cpp.
References mId.
Referenced by CMiaseParser::newModel(), CMiaseParser::newOutput(), and CMiaseParser::newTask().
 {
   mId = id;
 }
void CMiaseBaseEnhanced::setName (std::string name)
Definition at line 132 of file CMiaseBase.cpp.
References mName.
Referenced by CMiaseParser::newModel(), CMiaseParser::newOutput(), and CMiaseParser::newTask().
 {
   mName = name;
 }
Member Data Documentation
std::string CMiaseBaseEnhanced::mId private
Definition at line 109 of file CMiaseBase.h.
Referenced by getId(), and setId().
std::string CMiaseBaseEnhanced::mName private
Definition at line 110 of file CMiaseBase.h.
Referenced by getName(), and setName().
The documentation for this class was generated from the following files:
CMiaseBase.h
CMiaseBase.cpp