COPASI API: CMathReaction Class Reference
CMathReaction Class Reference
#include <CMathReaction.h>
Public Member Functions
CMathReaction ()
void copy (const CMathReaction &src, CMathContainer &container, const size_t &valueOffset, const size_t &objectOffset)
void fire (const C_FLOAT64 &count)
const CMathObject * getFluxObject () const
const CReaction * getModelReaction () const
const CObjectInterface::ObjectSet & getModifiedSpecies () const
const CMathObject * getParticleFluxObject () const
const CMathObject * getPropensityObject () const
void initialize (const CReaction *pReaction, CMathContainer &container)
~CMathReaction ()
Private Attributes
CObjectInterface::ObjectSet mModifiedSpecies
CMathObject * mpFlux
CMathObject * mpParticleFlux
CMathObject * mpPropensity
const CReaction * mpReaction
CVector< std::pair< C_FLOAT64,
C_FLOAT64 * > > mStepUpdates
Detailed Description
Definition at line 18 of file CMathReaction.h.
Constructor & Destructor Documentation
CMathReaction::CMathReaction ()
Constructor
Definition at line 13 of file CMathReaction.cpp.
                             :
   mpReaction(NULL),
   mpParticleFlux(NULL),
   mpFlux(NULL),
   mpPropensity(NULL),
   mModifiedSpecies(),
   mStepUpdates()
 {}
CMathReaction::~CMathReaction ()
Destructor
Definition at line 22 of file CMathReaction.cpp.
 {}
Member Function Documentation
void CMathReaction::copy (const CMathReaction & src, CMathContainer & container, const size_t & valueOffset, const size_t & objectOffset)
Copy an existing object
Parameters
const CMathReaction & src
CMathContainer & container
const size_t & valueOffset
const size_t & objectOffset
Definition at line 50 of file CMathReaction.cpp.
References CVectorCore< CType >::array(), mModifiedSpecies, mpFlux, mpParticleFlux, mpPropensity, mpReaction, mStepUpdates, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by CMathContainer::CMathContainer().
 {
   mpReaction = src.mpReaction;
   mpParticleFlux = src.mpParticleFlux + objectOffset;
   mpFlux = src.mpFlux + objectOffset;
   mpPropensity = src.mpPropensity + objectOffset;
   mStepUpdates.resize(src.mStepUpdates.size());
   std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdate = mStepUpdates.array();
   std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdateEnd = pStepUpdate + mStepUpdates.size();
   const std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdateSrc = src.mStepUpdates.array();
   for (; pStepUpdate != pStepUpdateEnd; ++pStepUpdate, ++pStepUpdateSrc)
     {
       pStepUpdate->first = pStepUpdateSrc->first;
       pStepUpdate->second = pStepUpdateSrc->second + valueOffset;
     }
   CObjectInterface::ObjectSet::const_iterator it = src.mModifiedSpecies.begin();
   CObjectInterface::ObjectSet::const_iterator end = src.mModifiedSpecies.end();
   for (; it != end; ++it)
     {
       mModifiedSpecies.insert(*it + objectOffset);
     }
 }
void CMathReaction::fire (const C_FLOAT64 & count)
Fire the reaction count times. Note count must not necessarily be an integer
Parameters
const C_FLOAT64 & count
Definition at line 81 of file CMathReaction.cpp.
References CVectorCore< CType >::array(), mStepUpdates, and CVectorCore< CType >::size().
 {
   std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdate = mStepUpdates.array();
   std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdateEnd = pStepUpdate + mStepUpdates.size();
   for (; pStepUpdate != pStepUpdateEnd; ++pStepUpdate)
     {
       *pStepUpdate->second += pStepUpdate->first * count;
     }
 }
const CMathObject * CMathReaction::getFluxObject () const
Retrieve a pointer to the mathematical object for the flux.
Returns
const CMathObject * pFluxObject
Definition at line 97 of file CMathReaction.cpp.
References mpFlux.
 {
   return mpFlux;
 }
const CReaction * CMathReaction::getModelReaction () const
Retrieve a pointer to the model reaction
Returns
const CReaction * pModelReaction
Definition at line 112 of file CMathReaction.cpp.
References mpReaction.
 {
   return mpReaction;
 }
const CObjectInterface::ObjectSet & CMathReaction::getModifiedSpecies () const
Retrieve the set of modified species
Returns
const CObjectInterface::ObjectSet & modifiedSpecies
Definition at line 107 of file CMathReaction.cpp.
References mModifiedSpecies.
 {
   return mModifiedSpecies;
 }
const CMathObject * CMathReaction::getParticleFluxObject () const
Retrieve a pointer to the mathematical object for the particle flux.
Returns
const CMathObject * pParticleFluxObject
Definition at line 92 of file CMathReaction.cpp.
References mpParticleFlux.
 {
   return mpParticleFlux;
 }
const CMathObject * CMathReaction::getPropensityObject () const
Retrieve a pointer to the mathematical object for the propensity.
Returns
const CMathObject * pPropensityObject
Definition at line 102 of file CMathReaction.cpp.
References mpPropensity.
 {
   return mpPropensity;
 }
void CMathReaction::initialize (const CReaction * pReaction, CMathContainer & container)
Initialize the reaction from the model reaction in the given container context
Parameters
const CReaction * pReaction
CMathContainer & container
Definition at line 25 of file CMathReaction.cpp.
References CVectorCore< CType >::array(), CCopasiVector< T >::begin(), C_FLOAT64, CChemEq::getBalances(), CReaction::getChemEq(), CReaction::getFluxReference(), CMathContainer::getMathObject(), CReaction::getParticleFluxReference(), CReaction::getPropensityReference(), CMathObject::getValuePointer(), mModifiedSpecies, mpFlux, mpParticleFlux, mpPropensity, mpReaction, mStepUpdates, CVector< CType >::resize(), CVectorCore< CType >::size(), and CCopasiVector< T >::size().
Referenced by CMathContainer::init().
 {
   mpReaction = pReaction;
   // Sanity Check
   if (mpReaction == NULL) return;
   mpParticleFlux = container.getMathObject(mpReaction->getParticleFluxReference());
   mpFlux = container.getMathObject(mpReaction->getFluxReference());
   mpPropensity = container.getMathObject(mpReaction->getPropensityReference());
   mStepUpdates.resize(mpReaction->getChemEq().getBalances().size());
   std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdate = mStepUpdates.array();
   std::pair< C_FLOAT64, C_FLOAT64 * > * pStepUpdateEnd = pStepUpdate + mStepUpdates.size();
   CCopasiVector < CChemEqElement >::const_iterator it = mpReaction->getChemEq().getBalances().begin();
   for (; pStepUpdate != pStepUpdateEnd; ++pStepUpdate, ++it)
     {
       CMathObject * pParticleNumber = container.getMathObject((*it)->getMetabolite()->getValueReference());
       mModifiedSpecies.insert(pParticleNumber);
       pStepUpdate->first = (*it)->getMultiplicity();
       pStepUpdate->second = (C_FLOAT64 *) pParticleNumber->getValuePointer();
     }
 }
Member Data Documentation
CObjectInterface::ObjectSet CMathReaction::mModifiedSpecies private
The set of modified species
Definition at line 107 of file CMathReaction.h.
Referenced by copy(), getModifiedSpecies(), and initialize().
CMathObject* CMathReaction::mpFlux private
A pointer to the mathematical flux.
Definition at line 97 of file CMathReaction.h.
Referenced by copy(), getFluxObject(), and initialize().
CMathObject* CMathReaction::mpParticleFlux private
A pointer to the mathematical particle flux.
Definition at line 92 of file CMathReaction.h.
Referenced by copy(), getParticleFluxObject(), and initialize().
CMathObject* CMathReaction::mpPropensity private
A pointer to the mathematical propensity.
Definition at line 102 of file CMathReaction.h.
Referenced by copy(), getPropensityObject(), and initialize().
const CReaction* CMathReaction::mpReaction private
A pointer to model reaction.
Definition at line 87 of file CMathReaction.h.
Referenced by copy(), getModelReaction(), and initialize().
CVector< std::pair< C_FLOAT64, C_FLOAT64 * > > CMathReaction::mStepUpdates private
Information for updating the species particle numbers when the reaction fires.
Definition at line 113 of file CMathReaction.h.
Referenced by copy(), fire(), and initialize().
The documentation for this class was generated from the following files:
CMathReaction.h
CMathReaction.cpp