COPASI API: CCopasiMatrixReference< CType > Class Template Reference
CCopasiMatrixReference< CType > Class Template Reference
#include <CCopasiObject.h>
Public Types
typedef CType referenceType
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CCopasiMatrixReference (const std::string &name, const CCopasiContainer *pParent, referenceType &reference, const unsigned C_INT32 &flag=0)
CCopasiMatrixReference (const CCopasiMatrixReference< referenceType > &src, const CCopasiContainer *pParent)
virtual CCopasiObject * getObject (const CCopasiObjectName &cn)
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
virtual ~CCopasiMatrixReference ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
CCopasiMatrixReference ()
Private Attributes
CType & mReference
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
template<class CType>
class CCopasiMatrixReference< CType >
Definition at line 45 of file CCopasiObject.h.
Member Typedef Documentation
template<class CType> typedef CType CCopasiMatrixReference< CType >::referenceType
Definition at line 231 of file CCopasiObjectReference.h.
Constructor & Destructor Documentation
template<class CType> CCopasiMatrixReference< CType >::CCopasiMatrixReference () inline private
Definition at line 239 of file CCopasiObjectReference.h.
                           :
     mReference(CType())
   {};
template<class CType> CCopasiMatrixReference< CType >::CCopasiMatrixReference (const std::string & name, const CCopasiContainer * pParent, referenceType & reference, const unsigned C_INT32 & flag = 0) inline
Definition at line 244 of file CCopasiObjectReference.h.
                                                            :
     CCopasiObject(name, pParent, "Reference",
                   CCopasiObject::Reference |
                   CCopasiObject::NonUniqueName |
                   flag),
     mReference(reference)
   {assert(pParent != NULL);}
template<class CType> CCopasiMatrixReference< CType >::CCopasiMatrixReference (const CCopasiMatrixReference< referenceType > & src, const CCopasiContainer * pParent) inline
Definition at line 255 of file CCopasiObjectReference.h.
                                                           :
     CCopasiObject(src, pParent),
     mReference(src.mReference)
   {}
template<class CType> virtual CCopasiMatrixReference< CType >::~CCopasiMatrixReference () inline virtual
Definition at line 261 of file CCopasiObjectReference.h.
 {}
Member Function Documentation
template<class CType> virtual CCopasiObject* CCopasiMatrixReference< CType >::getObject (const CCopasiObjectName & cn) inline virtual
Definition at line 263 of file CCopasiObjectReference.h.
References CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiObject::isValueBool(), CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), CCopasiMatrixReference< CType >::mReference, CCopasiObject::ValueBool, CCopasiObject::ValueDbl, and CCopasiObject::ValueInt.
   {
 #ifdef WIN32
     return new CCopasiObjectReference< referenceType::elementType >
 #else
     return new CCopasiObjectReference< typename referenceType::elementType >
 #endif
            (getObjectName() + cn,
             getObjectParent(),
             mReference(cn.getElementIndex(),
                        cn.getElementIndex(1)),
             isValueBool() ? CCopasiObject::ValueBool :
             isValueInt() ? CCopasiObject::ValueInt :
             isValueDbl() ? CCopasiObject::ValueDbl : (CCopasiObject::Flag) 0);
   }
template<class CType> virtual const CCopasiObject* CCopasiMatrixReference< CType >::getValueObject () const inline virtual
Reimplemented from CCopasiObject.
Definition at line 280 of file CCopasiObjectReference.h.
 {return this;}
template<class CType> virtual void* CCopasiMatrixReference< CType >::getValuePointer () const inline virtual
Retrieve a pointer to the value of the object
Reimplemented from CCopasiObject.
Definition at line 279 of file CCopasiObjectReference.h.
References CCopasiMatrixReference< CType >::mReference.
 {return &mReference;}
Member Data Documentation
template<class CType> CType& CCopasiMatrixReference< CType >::mReference private
Definition at line 235 of file CCopasiObjectReference.h.
Referenced by CCopasiMatrixReference< CType >::getObject(), and CCopasiMatrixReference< CType >::getValuePointer().
The documentation for this class was generated from the following files:
CCopasiObject.h
CCopasiObjectReference.h