COPASI API: CQLNAWidget Class Reference
CQLNAWidget Class Reference
#include <CQLNAWidget.h>
Public Slots
virtual void slotSteadyStateChecked ()
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Public Member Functions
CQLNAWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
~CQLNAWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Member Functions
void init ()
bool loadParameterTable ()
bool saveParameterTable ()
Additional Inherited Members
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 26 of file CQLNAWidget.h.
Constructor & Destructor Documentation
CQLNAWidget::CQLNAWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 41 of file CQLNAWidget.cpp.
References init().
     : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQLNAWidget::~CQLNAWidget ()
Definition at line 52 of file CQLNAWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQLNAWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 89 of file CQLNAWidget.cpp.
 {return new CLNAMethod;}
void CQLNAWidget::init () private
Definition at line 146 of file CQLNAWidget.cpp.
References TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, CQTaskHeaderWidget::setTaskName(), and CQTaskMethodWidget::showMethodParameters().
Referenced by CQLNAWidget(), and loadParameterTable().
 {
   mpHeaderWidget->setTaskName("Linear Noise Approximation");
   mpHeaderWidget->mpUpdateModel->hide();
   vboxLayout->insertWidget(0, mpHeaderWidget);  // header
   // vboxLayout->insertSpacing(1, 14);       // space between header and body
   mpMethodWidget->showMethodParameters(true);
   vboxLayout->addWidget(mpMethodWidget);
   vboxLayout->addWidget(mpBtnWidget);     // 'footer'
 }
bool CQLNAWidget::loadParameterTable () private
Definition at line 160 of file CQLNAWidget.cpp.
References FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), CCopasiParameterGroup::getName(), getParameterValue(), init(), TaskWidget::mpMethod, TaskWidget::mpMethodWidget, and CCopasiParameterGroup::size().
Referenced by loadTask(), and slotSteadyStateChecked().
 {
   bool init = (mpMethodWidget->mpTableParameter->rowCount() == 0);
   size_t NumRows = mpMethod->size();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (mpCheckSteadyState->isChecked())
     {
       CSteadyStateTask * pSteadyStateTask =
         dynamic_cast<CSteadyStateTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Steady-State"]);
       if (!pSteadyStateTask) return false;
       NumRows += pSteadyStateTask->getMethod()->size();
     }
   mpMethodWidget->mpTableParameter->setRowCount((int) NumRows);
   size_t i, k;
   CCopasiParameter::Type Type;
   QString value;
   for (i = 0; i < mpMethod->size() && init; i++)
     {
       mpMethodWidget->mpTableParameter->setVerticalHeaderItem((int) i, new QTableWidgetItem());
       mpMethodWidget->mpTableParameter->verticalHeaderItem((int) i)->setText(FROM_UTF8(mpMethod->getName(i)));
       value = getParameterValue(mpMethod, i, &Type);
       QTableWidgetItem *itemValue = new QTableWidgetItem(value);
       itemValue->setTextAlignment(Qt::AlignRight);
       mpMethodWidget->mpTableParameter->setItem((int) i, 0, itemValue);
     }
   if (mpCheckSteadyState->isChecked())
     {
       CSteadyStateTask * pSteadyStateTask =
         dynamic_cast<CSteadyStateTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Steady-State"]);
       if (!pSteadyStateTask) return false;
       CCopasiMethod * pMethod = pSteadyStateTask->getMethod();
       for (i = mpMethod->size(), k = 0; k < pMethod->size(); k++, i++)
         {
           // create item of the current row and give it a name
           mpMethodWidget->mpTableParameter->setVerticalHeaderItem((int) i, new QTableWidgetItem());
           mpMethodWidget->mpTableParameter->verticalHeaderItem((int) i)->setText(FROM_UTF8(pMethod->getName(k)));
           value = getParameterValue(pMethod, k, &Type);
           QTableWidgetItem *itemValue = new QTableWidgetItem(value);
           itemValue->setTextAlignment(Qt::AlignRight);
           mpMethodWidget->mpTableParameter->setItem((int) i, 0, itemValue);
         }
     }
   // the table will be automatically adjusted -> 31.10.09
   return true;
 }
bool CQLNAWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 92 of file CQLNAWidget.cpp.
References CCopasiTask::getProblem(), CLNAProblem::isSteadyStateRequested(), TaskWidget::loadCommon(), loadParameterTable(), TaskWidget::mChanged, TaskWidget::mpTask, and pTask.
 {
   CLNATask * pTask = dynamic_cast< CLNATask * >(mpTask);
   if (!pTask) return false;
   loadCommon();
 //  loadMethod(); --> we cannot do that because of different structure -- 08.04.09
   CLNAProblem * pProblem =
     dynamic_cast< CLNAProblem * >(mpTask->getProblem());
   if (!pProblem) return false;
   // instead calling loadMethod(), the following codes is used
   mpCheckSteadyState->setChecked(pProblem->isSteadyStateRequested());
   bool success = loadParameterTable();
   mChanged = false;
   return success;
 }
bool CQLNAWidget::runTask () virtual
Implements TaskWidget.
Definition at line 62 of file CQLNAWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CopasiWidget::mKey, and pTask.
Referenced by SliderDialog::runLNATask().
 {
   CLNATask * pTask =
     dynamic_cast< CLNATask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!pTask) return false;
   if (!commonBeforeRunTask()) return false;
   bool success = commonRunTask();
   return success;
 }
bool CQLNAWidget::saveParameterTable () private
Definition at line 222 of file CQLNAWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), getParameterValue(), TaskWidget::mChanged, TaskWidget::mpMethod, TaskWidget::mpMethodWidget, setParameterValue(), and CCopasiParameterGroup::size().
Referenced by saveTask().
 {
   size_t i, k;
   QString value;
   CCopasiParameter::Type Type;
   for (i = 0; i < mpMethod->size(); i++)
     {
       value = mpMethodWidget->mpTableParameter->item((int) i, 0)->text();
       if (value != getParameterValue(mpMethod, i, &Type))
         {
           setParameterValue(mpMethod, i, value);
           mChanged = true;
         }
     }
   if (mpCheckSteadyState->isChecked())
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       CSteadyStateTask * pSteadyStateTask =
         dynamic_cast<CSteadyStateTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Steady-State"]);
       if (!pSteadyStateTask) return false;
       CCopasiMethod * pMethod = pSteadyStateTask->getMethod();
       for (i = mpMethod->size(), k = 0; k < pMethod->size(); i++, k++)
         {
           value = mpMethodWidget->mpTableParameter->item((int) i, 0)->text();
           if (value != getParameterValue(pMethod, k, &Type))
             {
               setParameterValue(pMethod, k, value);
               mChanged = true;
             }
         }
     }
   return true;
 }
bool CQLNAWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 116 of file CQLNAWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiTask::getProblem(), CLNAProblem::isSteadyStateRequested(), TaskWidget::mChanged, TaskWidget::mpTask, pTask, TaskWidget::saveCommon(), saveParameterTable(), and CLNAProblem::setSteadyStateRequested().
 {
   CLNATask * pTask = dynamic_cast< CLNATask * >(mpTask);
   if (!pTask) return false;
   saveCommon();
   // saveMethod();
   CLNAProblem * pProblem =
     dynamic_cast< CLNAProblem * >(mpTask->getProblem());
   if (!pProblem) return false;
   if (mpCheckSteadyState->isChecked() != pProblem->isSteadyStateRequested())
     {
       pProblem->setSteadyStateRequested(mpCheckSteadyState->isChecked());
       mChanged = true;
     }
   bool success = saveParameterTable();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (mChanged)(*CCopasiRootContainer::getDatamodelList())[0]->changed();
   mChanged = false;
   return success;
 }
void CQLNAWidget::slotSteadyStateChecked () virtual slot
Definition at line 57 of file CQLNAWidget.cpp.
References loadParameterTable().
 {
   loadParameterTable();
 }
bool CQLNAWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 76 of file CQLNAWidget.cpp.
References ListViews::findWidgetFromId(), CLNAResultWidget::loadFromBackend(), CopasiWidget::mpListView, pResult, and ListViews::switchToOtherWidget().
 {
   bool success = true;
   CLNAResultWidget *pResult = dynamic_cast< CLNAResultWidget * >(mpListView->findWidgetFromId(351));
   if (pResult) pResult->loadFromBackend();
   if (success && pResult)
     mpListView->switchToOtherWidget(351, ""); //change to the results window
   return success;
 }
The documentation for this class was generated from the following files:
CQLNAWidget.h
CQLNAWidget.cpp