COPASI API: test000053 Class Reference
test000053 Class Reference
#include <test000053.h>
Public Member Functions
void setUp ()
void tearDown ()
void test1_bug1000 ()
void test2_bug1000 ()
void test3_bug1000 ()
void test4_bug1000 ()
void test5_bug1000 ()
Static Protected Attributes
static const char * MODEL_STRING_1
static const char * MODEL_STRING_2
static const char * MODEL_STRING_3
static const char * MODEL_STRING_4
static const char * MODEL_STRING_5
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test1_bug1000)
CPPUNIT_TEST (test2_bug1000)
CPPUNIT_TEST (test3_bug1000)
CPPUNIT_TEST (test4_bug1000)
CPPUNIT_TEST (test5_bug1000)
CPPUNIT_TEST_SUITE (test000053)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000053.h.
Member Function Documentation
test000053::CPPUNIT_TEST (test1_bug1000) private
test000053::CPPUNIT_TEST (test2_bug1000) private
test000053::CPPUNIT_TEST (test3_bug1000) private
test000053::CPPUNIT_TEST (test4_bug1000) private
test000053::CPPUNIT_TEST (test5_bug1000) private
test000053::CPPUNIT_TEST_SUITE (test000053) private
test000053::CPPUNIT_TEST_SUITE_END () private
void test000053::setUp ()
Definition at line 45 of file test000053.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000053::tearDown ()
Definition at line 53 of file test000053.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000053::test1_bug1000 ()
Definition at line 58 of file test000053.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNode::CHOICE, CEvaluationNodeNumber::DOUBLE, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CEvaluationNode::LOGICAL, MODEL_STRING_1, CEvaluationNode::NUMBER, pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000053::MODEL_STRING_1));
   const CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pRoot = pExpr->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::CHOICE);
   const CEvaluationNodeChoice* pChoiceNode = dynamic_cast<const CEvaluationNodeChoice*>(pRoot);
   CPPUNIT_ASSERT(pChoiceNode != NULL);
   const CEvaluationNode* pChild1 = dynamic_cast<const CEvaluationNode*>(pChoiceNode->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   const CEvaluationNode* pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.5) / 0.5) < 1e-6);
   const CEvaluationNode* pChild3 = dynamic_cast<const CEvaluationNode*>(pChild2->getSibling());
   CPPUNIT_ASSERT(pChild3 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild3->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild3->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild3);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 1.5) / 1.5) < 1e-6);
   CPPUNIT_ASSERT(pChild3->getSibling() == NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT(((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeLogical::GT);
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChild1->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild1);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 4.0) / 4.0) < 1e-6);
 }
void test000053::test2_bug1000 ()
Definition at line 162 of file test000053.cpp.
References CEvaluationNodeConstant::_NaN, CModelEntity::ASSIGNMENT, CEvaluationNode::CONSTANT, CCopasiDataModel::getModel(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING_2, pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000053::MODEL_STRING_2));
   const CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pRoot = pExpr->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::CONSTANT);
   const CEvaluationNodeConstant* pConstantNode = dynamic_cast<const CEvaluationNodeConstant*>(pRoot);
   CPPUNIT_ASSERT(pConstantNode != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeConstant::SubType)CEvaluationNode::subType(pConstantNode->getType())) == CEvaluationNodeConstant::_NaN);
 }
void test000053::test3_bug1000 ()
Definition at line 223 of file test000053.cpp.
References CEvaluationNodeConstant::_NaN, CModelEntity::ASSIGNMENT, CEvaluationNode::CHOICE, CEvaluationNode::CONSTANT, CEvaluationNodeNumber::DOUBLE, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING_3, CEvaluationNode::NUMBER, pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000053::MODEL_STRING_3));
   const CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pRoot = pExpr->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::CHOICE);
   const CEvaluationNodeChoice* pChoiceNode = dynamic_cast<const CEvaluationNodeChoice*>(pRoot);
   CPPUNIT_ASSERT(pChoiceNode != NULL);
   const CEvaluationNode* pChild1 = dynamic_cast<const CEvaluationNode*>(pChoiceNode->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   const CEvaluationNode* pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.5) / 0.5) < 1e-6);
   const CEvaluationNode* pChild3 = dynamic_cast<const CEvaluationNode*>(pChild2->getSibling());
   CPPUNIT_ASSERT(pChild3 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild3->getType()) == CEvaluationNode::CONSTANT);
   CPPUNIT_ASSERT(((CEvaluationNodeConstant::SubType)CEvaluationNode::subType(pChild3->getType())) == CEvaluationNodeConstant::_NaN);
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChild1->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild1);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 4.0) / 4.0) < 1e-6);
 }
void test000053::test4_bug1000 ()
Definition at line 318 of file test000053.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNodeNumber::DOUBLE, CCopasiDataModel::getModel(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING_4, CEvaluationNode::NUMBER, pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000053::MODEL_STRING_4));
   const CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pRoot = pExpr->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pRoot->getType())) == CEvaluationNodeNumber::DOUBLE);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pRoot);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 1.5) / 1.5) < 1e-6);
 }
void test000053::test5_bug1000 ()
Definition at line 383 of file test000053.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNode::CHOICE, CEvaluationNodeNumber::DOUBLE, CEvaluationNodeLogical::EQ, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CEvaluationNodeLogical::LE, CEvaluationNode::LOGICAL, CEvaluationNodeLogical::LT, MODEL_STRING_5, CEvaluationNode::NUMBER, pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000053::MODEL_STRING_5));
   const CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pRoot = pExpr->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::CHOICE);
   const CEvaluationNodeChoice* pChoiceNode = dynamic_cast<const CEvaluationNodeChoice*>(pRoot);
   CPPUNIT_ASSERT(pChoiceNode != NULL);
   const CEvaluationNode* pChild1 = dynamic_cast<const CEvaluationNode*>(pChoiceNode->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   const CEvaluationNode* pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.1) / 0.1) < 1e-6);
   const CEvaluationNode* pChild3 = dynamic_cast<const CEvaluationNode*>(pChild2->getSibling());
   CPPUNIT_ASSERT(pChild3 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild3->getType()) == CEvaluationNode::CHOICE);
   pChoiceNode = dynamic_cast<const CEvaluationNodeChoice*>(pChild3);
   CPPUNIT_ASSERT(pChoiceNode);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT(((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeLogical::LT);
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChild1->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild1);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 4.0) / 4.0) < 1e-6);
   // second choice level (child3 of first choice level)
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChoiceNode->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.2) / 0.2) < 1e-6);
   pChild3 = dynamic_cast<const CEvaluationNode*>(pChild2->getSibling());
   CPPUNIT_ASSERT(pChild3 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild3->getType()) == CEvaluationNode::CHOICE);
   pChoiceNode = dynamic_cast<const CEvaluationNodeChoice*>(pChild3);
   CPPUNIT_ASSERT(pChoiceNode);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT(((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeLogical::GT);
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChild1->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild1);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 4.0) / 4.0) < 1e-6);
   // third choice level (child3 of second choice level)
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChoiceNode->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.3) / 0.3) < 1e-6);
   pChild3 = dynamic_cast<const CEvaluationNode*>(pChild2->getSibling());
   CPPUNIT_ASSERT(pChild3 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild3->getType()) == CEvaluationNode::CHOICE);
   pChoiceNode = dynamic_cast<const CEvaluationNodeChoice*>(pChild3);
   CPPUNIT_ASSERT(pChoiceNode);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT(((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeLogical::LE);
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChild1->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild1);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 4.0) / 4.0) < 1e-6);
   // fourth choice level (child3 of third choice level)
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChoiceNode->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.4) / 0.4) < 1e-6);
   pChild3 = dynamic_cast<const CEvaluationNode*>(pChild2->getSibling());
   CPPUNIT_ASSERT(pChild3 != NULL);
   // the third child of the fourth choice level must be the otherwise element
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild3->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild3->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild3);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 1.5) / 1.5) < 1e-6);
   CPPUNIT_ASSERT(pChild3->getSibling() == NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT(((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeLogical::EQ);
   pChild1 = dynamic_cast<const CEvaluationNode*>(pChild1->getChild());
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild1);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild2 = dynamic_cast<const CEvaluationNode*>(pChild1->getSibling());
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType())) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild2);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 4.0) / 4.0) < 1e-6);
 }
Member Data Documentation
const char * test000053::MODEL_STRING_1 static protected
Definition at line 35 of file test000053.h.
Referenced by test1_bug1000().
const char * test000053::MODEL_STRING_2 static protected
Definition at line 36 of file test000053.h.
Referenced by test2_bug1000().
const char * test000053::MODEL_STRING_3 static protected
Definition at line 37 of file test000053.h.
Referenced by test3_bug1000().
const char * test000053::MODEL_STRING_4 static protected
Definition at line 38 of file test000053.h.
Referenced by test4_bug1000().
const char * test000053::MODEL_STRING_5 static protected
Definition at line 39 of file test000053.h.
Referenced by test5_bug1000().
CCopasiDataModel * test000053::pCOPASIDATAMODEL = NULL static protected
Definition at line 40 of file test000053.h.
Referenced by setUp(), test1_bug1000(), test2_bug1000(), test3_bug1000(), test4_bug1000(), and test5_bug1000().
The documentation for this class was generated from the following files:
test000053.h
test000053.cpp