COPASI API: CCopasiXMLParser::ReactionGlyphElement Class Reference
CCopasiXMLParser::ReactionGlyphElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ReactionGlyphElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ReactionGlyphElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
ReactionGlyph = 0, BoundingBox, Position, Dimensions,
Curve, ListOfMetaboliteReferenceGlyphs
}
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3455 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ReactionGlyphElement::Element private
Enumerator
ReactionGlyph
BoundingBox
Position
Dimensions
Curve
ListOfMetaboliteReferenceGlyphs
Definition at line 3458 of file CCopasiXMLParser.h.
     {
       ReactionGlyph = 0,
       BoundingBox,
       Position,
       Dimensions,
       Curve,
       ListOfMetaboliteReferenceGlyphs
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ReactionGlyphElement::ReactionGlyphElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Definition at line 7249 of file CCopasiXMLParser.cpp.
                                                                                                                    :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::ReactionGlyphElement::~ReactionGlyphElement () virtual
Definition at line 7254 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::ReactionGlyphElement::end (const XML_Char * pszName) virtual
Definition at line 7378 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "ReactionGlyph"))
     {
       mParser.popElementHandler();
       mCurrentElement = START_ELEMENT;
       /* Tell the parent element we are done. */
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case BoundingBox:
             break;
           case Position:
             break;
           case Dimensions:
             break;
           case Curve:
             break;
           case ListOfMetaboliteReferenceGlyphs:
             break;
           case UNKNOWN_ELEMENT:
             mCurrentElement = ReactionGlyph;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::ReactionGlyphElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Definition at line 7257 of file CCopasiXMLParser.cpp.
References CLayout::addReactionGlyph(), CCopasiMessage::EXCEPTION, CKeyFactory::get(), CLGlyphWithCurve::getCurve(), CReaction::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentLayout, SCopasiXMLParserCommon::pCurve, SCopasiXMLParserCommon::pReactionGlyph, CLGraphicalObject::setHeight(), CLGraphicalObject::setModelObjectKey(), CLGraphicalObject::setObjectRole(), CLGraphicalObject::setWidth(), CLGraphicalObject::setX(), CLGraphicalObject::setY(), UNKNOWN_ELEMENT, and CCopasiMessage::WARNING.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case ReactionGlyph:
         if (strcmp(pszName, "ReactionGlyph"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "ReactionGlyph", mParser.getCurrentLineNumber());
         {
           //workload
           const char * key;
           const char * name;
           const char * reaction;
           key = mParser.getAttributeValue("key", papszAttrs);
           name = mParser.getAttributeValue("name", papszAttrs);
           reaction = mParser.getAttributeValue("reaction", papszAttrs);
           mCommon.pReactionGlyph = new CLReactionGlyph(name);
           const char * objectRole = mParser.getAttributeValue("objectRole", papszAttrs, false);
           if (objectRole != NULL && objectRole[0] != 0)
             {
               mCommon.pReactionGlyph->setObjectRole(objectRole);
             }
           if (reaction && reaction[0])
             {
               CReaction * pReaction = dynamic_cast< CReaction * >(mCommon.KeyMap.get(reaction));
               if (!pReaction)
                 {
                   CCopasiMessage(CCopasiMessage::WARNING, MCXML + 19, "ReactionGlyph" , key);
                 }
               else
                 {
                   mCommon.pReactionGlyph->setModelObjectKey(pReaction->getKey());
                 }
             }
           mCommon.pCurrentLayout->addReactionGlyph(mCommon.pReactionGlyph);
           addFix(key, mCommon.pReactionGlyph);
         }
         return;
         break;
       case BoundingBox:
         if (!strcmp(pszName, "BoundingBox"))
           return;
         break;
       case Position:
         if (!strcmp(pszName, "Position"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             mCommon.pReactionGlyph->setX(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("y", papszAttrs);
             mCommon.pReactionGlyph->setY(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Dimensions:
         if (!strcmp(pszName, "Dimensions"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("width", papszAttrs);
             mCommon.pReactionGlyph->setWidth(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("height", papszAttrs);
             mCommon.pReactionGlyph->setHeight(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Curve:
         if (!strcmp(pszName, "Curve"))
           {
             mpCurrentHandler = new CurveElement(mParser, mCommon);
             if (mCommon.pReactionGlyph)
               mCommon.pCurve = &mCommon.pReactionGlyph->getCurve();
           }
         break;
       case ListOfMetaboliteReferenceGlyphs:
         if (!strcmp(pszName, "ListOfMetaboliteReferenceGlyphs"))
           mpCurrentHandler = new ListOfMetaboliteReferenceGlyphsElement(mParser, mCommon);
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::ReactionGlyphElement::mLineNumber private
Definition at line 3468 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp