COPASI API: CReadConfig Class Reference
CReadConfig Class Reference
#include <CReadConfig.h>
Public Types
enum Mode { NEXT = 0, SEARCH, LOOP, ALL }
Public Member Functions
CReadConfig (const std::string &name)
CReadConfig (std::istream &in)
C_INT32 fail ()
void getDefaults ()
C_INT32 getVariable (const std::string &name, const std::string &type, void *pout, CReadConfig::Mode mode=CReadConfig::NEXT)
C_INT32 getVariable (const std::string &name, const std::string &type, void *pout1, void *pout2, CReadConfig::Mode mode=CReadConfig::NEXT)
std::string getVersion ()
void rewind ()
~CReadConfig ()
Private Member Functions
CReadConfig ()
C_INT32 initFileBuffer ()
std::string lookAhead ()
Private Attributes
C_INT32 mFail
std::stringstream mFileBuffer
std::string mFilename
C_INT32 mLineNumber
CReadConfig::Mode mMode
std::istream * mpBuffer
std::string mVersion
Detailed Description
CReadConfig class. A more elaborate class description. New Class based on pmutils read functionality
(C) Stefan Hoops 2001
Definition at line 34 of file CReadConfig.h.
Member Enumeration Documentation
enum CReadConfig::Mode
Enumerator
NEXT
SEARCH
LOOP
ALL
Definition at line 39 of file CReadConfig.h.
   {
     NEXT = 0,
     SEARCH,
     LOOP,
     ALL
   };
Constructor & Destructor Documentation
CReadConfig::CReadConfig (void) private
Default constructor. This creates a configuration buffer for input assigning a filename. It is currently useless.
Definition at line 34 of file CReadConfig.cpp.
                             :
   mpBuffer(NULL),
   mLineNumber(-1),
   mMode(CReadConfig::NEXT),
   mFail(0),
   mVersion(),
   mFilename(),
   mFileBuffer()
 {}
CReadConfig::CReadConfig (const std::string & name)
Specified constructor. This opens the configuration file using the filename specified as the argument.
Parameters
name name of the configuration file.
Definition at line 44 of file CReadConfig.cpp.
References getVariable(), initFileBuffer(), and mVersion.
                                              :
   mpBuffer(NULL),
   mLineNumber(-1),
   mMode(CReadConfig::NEXT),
   mFail(0),
   mVersion(),
   mFilename(name),
   mFileBuffer()
 {
   initFileBuffer();
   getVariable("Version", "string", &mVersion);
 }
CReadConfig::CReadConfig (std::istream & in)
Specified constructor. This opens the configuration file using the filename specified as the argument.
Parameters
std::istream & in
Definition at line 58 of file CReadConfig.cpp.
                                        :
   mpBuffer(&in),
   mLineNumber(-1),
   mMode(CReadConfig::NEXT),
   mFail(0),
   mVersion(),
   mFilename(),
   mFileBuffer()
 {}
CReadConfig::~CReadConfig (void)
Destructor. The destructor calls the method free().
Definition at line 68 of file CReadConfig.cpp.
 {}
Member Function Documentation
C_INT32 CReadConfig::fail ()
Returns the failure status.
Returns
mFail
See Also
mFail
Definition at line 71 of file CReadConfig.cpp.
References mFail.
 {
   // return the failure state
   return mFail;
 }
void CReadConfig::getDefaults ()
Load various system wide default values
Definition at line 78 of file CReadConfig.cpp.
 {}
C_INT32 CReadConfig::getVariable (const std::string & name, const std::string & type, void * pout, CReadConfig::Mode mode = CReadConfig::NEXT)
Retrieves a variable from the input file.
Parameters
name name of the variable to be retrieved.
type type of the variable to be retrieved.
*pout pointer to the location where the retrieved variable is stored.
Returns
mFail
See Also
mFail
Definition at line 81 of file CReadConfig.cpp.
References ALL, C_FLOAT64, C_INT16, C_INT32, CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, lookAhead(), LOOP, MCReadConfig, mFail, mFilename, mLineNumber, mpBuffer, mVersion, rewind(), SEARCH, and strToDouble().
Referenced by CKinFunction::CKinFunction(), CReadConfig(), getVariable(), CFunctionDB::load(), CCompartment::load(), CReaction::load(), CSteadyStateProblem::load(), CMCAProblem::load(), CLNAProblem::load(), CNewtonMethod::load(), CLNATask::load(), CMCATask::load(), CFunctionParameter::load(), CMCAMethod::load(), CTrajectoryProblem::load(), CModel::load(), CFunction::load(), CTrajectoryTask::load(), CSteadyStateTask::load(), CNodeK::load(), CMetab::load(), CMetabOld::load(), CReaction::loadOld(), and CReaction::loadOneRole().
 {
   char c[] = " ";
   size_t equal = 0;
   std::string Line;
   std::string Name;
   std::string Value;
   mode = (mode & CReadConfig::LOOP) ? CReadConfig::ALL : mode;
   // Get the current line
   while (true)
     {
       Line.erase();
       // Read a line form the input buffer
       mLineNumber++;
       while (true)
         {
           mpBuffer->read(c, 1);
           if (*c == '\n' || mpBuffer->eof())
             break;
           //YH: here we need to delete ^M carriage return, it is \r
           if (*c == '\r')
             continue;
           Line += c;
         }
       equal = Line.find('=');
       Name = Line.substr(0, equal);
       Value = Line.substr(equal + 1);
       // The Compartment keyword is used twice. So we must determine by
       // the context if we have found the correct one in the case the mode
       // is SEARCH.
       if ((mode & CReadConfig::SEARCH) &&
           name == "Compartment" &&
           Name == "Compartment")
         {
           if (lookAhead() != "Volume")
             {
               Name = "<CONTINUE>";
             }
         }
       // The Title keyword is used twice. So we must determine by
       // the context if we have found the correct one in the case the mode
       // is SEARCH.
       if ((mode & CReadConfig::SEARCH) &&
           name == "Title" &&
           Name == "Title")
         {
           if ((mVersion < "4" &&
                lookAhead() != "TotalMetabolites") ||
               (mVersion >= "4" &&
                lookAhead() != "Comments"))
             {
               Name = "<CONTINUE>";
             }
         }
       // We found what we are looking for
       if (name == Name)
         break;
       if (mode & CReadConfig::SEARCH)
         {
           if (mpBuffer->eof())
             {
               if (!(mode & CReadConfig::LOOP))
                 CCopasiMessage(CCopasiMessage::EXCEPTION, MCReadConfig + 1,
                                name.c_str(), mFilename.c_str(),
                                mLineNumber);
               // Rewind the buffer
               mode = CReadConfig::SEARCH;
               rewind();
             }
           continue;
         }
       // We should never reach this line!!!
       CCopasiMessage(CCopasiMessage::ERROR, MCReadConfig + 1, name.c_str(),
                      mFilename.c_str(), mLineNumber);
     }
   // Return the value depending on the type
   if (type == "string")
     {
       *(std::string *) pout = Value;
     }
   else if (type == "C_FLOAT64")
     {
       // may be we should check if Value is really a C_FLOAT64
       *(C_FLOAT64 *) pout = strToDouble(Value.c_str(), NULL);
     }
   else if (type == "C_INT32")
     {
       // may be we should check if Value is really a integer
       *(C_INT32 *) pout = atoi(Value.c_str());
     }
   else if (type == "C_INT16")
     {
       // may be we should check if Value is really a integer
       *(C_INT16 *) pout = atoi(Value.c_str());
     }
   else if (type == "bool")
     {
       // may be we should check if Value is really a integer
       *(bool *) pout = (atoi(Value.c_str()) != 0);
     }
   else if (type == "multiline")
     {
       Value.erase();
       while (true)
         {
           Line.erase();
           // Read a line form the input buffer
           mLineNumber++;
           while (true)
             {
               mpBuffer->read(c, 1);
               if (*c == '\n' || mpBuffer->eof())
                 break;
               //YH: here we need to delete ^M carriage return, it is \r
               if (*c == '\r')
                 continue;
               Line += c;
             }
           if (Line == "End" + name)
             break;
           if (Value.length())
             Value += '\n';
           Value += Line;
         }
       *(std::string *) pout = Value;
     }
   else
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCReadConfig + 5, type.c_str(),
                      name.c_str());
       mFail = 1; //Error
     }
   return mFail;
 }
C_INT32 CReadConfig::getVariable (const std::string & name, const std::string & type, void * pout1, void * pout2, CReadConfig::Mode mode = CReadConfig::NEXT)
Retrieves a variable from the input file.
Parameters
name name of the variable to be retrieved.
type type of the variable to be retrieved.
*pout1 pointer to the location where the first part of the retrieved variable is stored.
*pout2 pointer to the location where the second part of the retrieved variable is stored.
Returns
mFail
See Also
mFail
Definition at line 249 of file CReadConfig.cpp.
References CCopasiMessage::ERROR, getVariable(), MCReadConfig, and mFail.
 {
   std::string Value;
   if ((mFail = getVariable(name, "string", &Value, mode)))
     return mFail;
   if (type == "node")
     {
       size_t komma = 0;
       komma = Value.find(",");
       std::string Type = Value.substr(0, komma);
       *(char*) pout1 = (char) atoi(Type.c_str());
       std::string Subtype = Value.substr(komma + 1);
       *(char*) pout2 = (char) atoi(Subtype.c_str());
     }
   else
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCReadConfig + 5, type.c_str(),
                      name.c_str());
       mFail = 1; //Error
     }
   return mFail;
 }
std::string CReadConfig::getVersion ()
Retrieves the version string of the configbuffer
Definition at line 76 of file CReadConfig.cpp.
References mVersion.
Referenced by CSteadyStateProblem::load(), CLNAProblem::load(), CMCAProblem::load(), CNewtonMethod::load(), CTrajectoryProblem::load(), and CCopasiDataModel::loadModel().
 {return mVersion;}
C_INT32 CReadConfig::initFileBuffer () private
Initializes the input buffer for reading.
Returns
mFail
See Also
mFail
Definition at line 282 of file CReadConfig.cpp.
References CCopasiMessage::ERROR, CLocaleString::fromUtf8(), MCReadConfig, mFail, mFileBuffer, mFilename, and mpBuffer.
Referenced by CReadConfig().
 {
   char c[] = " ";
   mpBuffer = & mFileBuffer;
   // read the configuration file into the configuration buffer
 #ifdef WIN32
   std::ifstream File(CLocaleString::fromUtf8(mFilename).c_str(), std::ios_base::binary);
 #else
   std::ifstream File(CLocaleString::fromUtf8(mFilename).c_str());
 #endif
   if (File.fail())
     CCopasiMessage(CCopasiMessage::ERROR, MCReadConfig + 2,
                    mFilename.c_str());
   while (true)
     {
       File.read(c, 1);
       if (File.eof())
         break;
       if (File.fail())
         CCopasiMessage(CCopasiMessage::ERROR, MCReadConfig + 3,
                        mFilename.c_str());
       mFileBuffer << c;
     }
   File.clear();
   File.close();
   if (File.fail())
     CCopasiMessage(CCopasiMessage::ERROR, MCReadConfig + 4,
                    mFilename.c_str());
   return mFail;
 }
std::string CReadConfig::lookAhead () private
Look ahead to find the next variable name
Definition at line 324 of file CReadConfig.cpp.
References mpBuffer.
Referenced by getVariable().
 {
   std::streampos pos = mpBuffer->tellg();
   std::string Line;
   *mpBuffer >> Line;
   mpBuffer->seekg(pos - mpBuffer->tellg(), std::ios_base::cur);
   return Line.substr(0, Line.find("="));
 }
void CReadConfig::rewind ()
Rewind the buffer
Definition at line 336 of file CReadConfig.cpp.
References mLineNumber, and mpBuffer.
Referenced by getVariable().
 {
   mpBuffer->clear();
   mpBuffer->seekg(0, std::ios_base::beg);
   mLineNumber = 0;
   return;
 }
Member Data Documentation
C_INT32 CReadConfig::mFail private
Failure status: 0 = no error !0 = error
Definition at line 87 of file CReadConfig.h.
Referenced by fail(), getVariable(), and initFileBuffer().
std::stringstream CReadConfig::mFileBuffer private
A buffer for reading the file.
Definition at line 102 of file CReadConfig.h.
Referenced by initFileBuffer().
std::string CReadConfig::mFilename private
Name of the configuration file.
Definition at line 97 of file CReadConfig.h.
Referenced by getVariable(), and initFileBuffer().
C_INT32 CReadConfig::mLineNumber private
Current line number in the configuration file
Definition at line 75 of file CReadConfig.h.
Referenced by getVariable(), and rewind().
CReadConfig::Mode CReadConfig::mMode private
Mode = CReadConfig::SEARCH
Definition at line 80 of file CReadConfig.h.
std::istream* CReadConfig::mpBuffer private
A pointer to the input buffer
Definition at line 70 of file CReadConfig.h.
Referenced by getVariable(), initFileBuffer(), lookAhead(), and rewind().
std::string CReadConfig::mVersion private
Definition at line 92 of file CReadConfig.h.
Referenced by CReadConfig(), getVariable(), and getVersion().
The documentation for this class was generated from the following files:
CReadConfig.h
CReadConfig.cpp