COPASI API: ArrayOf_USCORExsd_USCOREstring Class Reference
ArrayOf_USCORExsd_USCOREstring Class Reference
#include <soapStub.h>
Public Member Functions
ArrayOf_USCORExsd_USCOREstring ()
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
virtual ~ArrayOf_USCORExsd_USCOREstring ()
Public Attributes
std::string * __ptr
int __size
struct soap * soap
Detailed Description
Definition at line 66 of file soapStub.h.
Constructor & Destructor Documentation
ArrayOf_USCORExsd_USCOREstring::ArrayOf_USCORExsd_USCOREstring () inline
Definition at line 80 of file soapStub.h.
 : __ptr(NULL), __size(0), soap(NULL) {}
virtual ArrayOf_USCORExsd_USCOREstring::~ArrayOf_USCORExsd_USCOREstring () inline virtual
Definition at line 81 of file soapStub.h.
 {}
Member Function Documentation
void ArrayOf_USCORExsd_USCOREstring::soap_default (struct soap * soap) virtual
Definition at line 1836 of file soapC.cpp.
References __ptr, __size, and soap.
Referenced by soap_in_ArrayOf_USCORExsd_USCOREstring().
 {
   this->soap = soap;
   this->__size = 0;
   this->__ptr = NULL;
 }
void * ArrayOf_USCORExsd_USCOREstring::soap_get (struct soap * soap, const char * tag, const char * type) virtual
Definition at line 1891 of file soapC.cpp.
References soap_get_ArrayOf_USCORExsd_USCOREstring().
 {
   return soap_get_ArrayOf_USCORExsd_USCOREstring(soap, this, tag, type);
 }
void * ArrayOf_USCORExsd_USCOREstring::soap_in (struct soap * soap, const char * tag, const char * type) virtual
Definition at line 1905 of file soapC.cpp.
References soap_in_ArrayOf_USCORExsd_USCOREstring().
 {
   return soap_in_ArrayOf_USCORExsd_USCOREstring(soap, tag, this, type);
 }
int ArrayOf_USCORExsd_USCOREstring::soap_out (struct soap * soap, const char * tag, int id, const char * type) const virtual
Definition at line 1863 of file soapC.cpp.
References soap_out_ArrayOf_USCORExsd_USCOREstring().
Referenced by soap_put().
 {
   return soap_out_ArrayOf_USCORExsd_USCOREstring(soap, tag, id, this, type);
 }
int ArrayOf_USCORExsd_USCOREstring::soap_put (struct soap * soap, const char * tag, const char * type) const virtual
Definition at line 1853 of file soapC.cpp.
References __ptr, soap::error, soap_embed(), soap_out(), soap_putindependent(), and SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring.
 {
   register int id = soap_embed(soap, (void*)this, (struct soap_array*) & this->__ptr, 1, tag, SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring);
   if (this->soap_out(soap, tag, id, type))
     return soap->error;
   return soap_putindependent(soap);
 }
void ArrayOf_USCORExsd_USCOREstring::soap_serialize (struct soap * soap) const virtual
Definition at line 1843 of file soapC.cpp.
References __ptr, __size, soap_array_reference(), soap_embedded(), soap_serialize_std__string(), SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring, and SOAP_TYPE_std__string.
 {
   if (this->__ptr && !soap_array_reference(soap, this, (struct soap_array*)&this->__ptr, 1, SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring))
     for (int i = 0; i < this->__size; i++)
       {
         soap_embedded(soap, this->__ptr + i, SOAP_TYPE_std__string);
         soap_serialize_std__string(soap, this->__ptr + i);
       }
 }
virtual int ArrayOf_USCORExsd_USCOREstring::soap_type () const inline virtual
Definition at line 73 of file soapStub.h.
 {return 7;} /* = unique id SOAP_TYPE_ArrayOf_USCORExsd_USCOREstring */
Member Data Documentation
std::string* ArrayOf_USCORExsd_USCOREstring::__ptr
Definition at line 69 of file soapStub.h.
Referenced by soap_default(), soap_in_ArrayOf_USCORExsd_USCOREstring(), soap_out_ArrayOf_USCORExsd_USCOREstring(), soap_out_PointerToArrayOf_USCORExsd_USCOREstring(), soap_put(), soap_serialize(), and CMIRIAMResources::updateMIRIAMResources().
int ArrayOf_USCORExsd_USCOREstring::__size
Definition at line 70 of file soapStub.h.
Referenced by soap_default(), soap_in_ArrayOf_USCORExsd_USCOREstring(), soap_out_ArrayOf_USCORExsd_USCOREstring(), soap_serialize(), and CMIRIAMResources::updateMIRIAMResources().
struct soap* ArrayOf_USCORExsd_USCOREstring::soap
Definition at line 71 of file soapStub.h.
Referenced by soap_default(), and soap_instantiate_ArrayOf_USCORExsd_USCOREstring().
The documentation for this class was generated from the following files:
soapStub.h
soapC.cpp