COPASI API: test000068 Class Reference
test000068 Class Reference
#include <test000068.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1068 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1068)
CPPUNIT_TEST_SUITE (test000068)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 26 of file test000068.h.
Member Function Documentation
test000068::CPPUNIT_TEST (test_bug1068) private
test000068::CPPUNIT_TEST_SUITE (test000068) private
test000068::CPPUNIT_TEST_SUITE_END () private
void test000068::setUp ()
Definition at line 33 of file test000068.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000068::tearDown ()
Definition at line 41 of file test000068.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000068::test_bug1068 ()
Definition at line 46 of file test000068.cpp.
References CModelEntity::ASSIGNMENT, CCopasiDataModel::exportSBMLToString(), CModelEntity::FIXED, CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CModel::l, MODEL_STRING1, CModel::Mol, CCopasiDataModel::newModel(), CModelEntity::ODE, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, and CEvaluationTree::UserDefined.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::Mol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::l);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 6);
   // check metabolites
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::REACTIONS);
   pMetab = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "B");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::REACTIONS);
   pMetab = pModel->getMetabolites()[2];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "C");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   // check assignment
   const CEvaluationTree* pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   const CEvaluationNode* pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_5");
   pMetab = pModel->getMetabolites()[3];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "D");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ODE);
   // check ode
   pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_2");
   pMetab = pModel->getMetabolites()[4];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "E");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ODE);
   // check ode
   pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_4");
   pMetab = pModel->getMetabolites()[5];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "F");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ODE);
   // check ode
   pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_6");
   // check model values
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 3);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "K1");
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::ASSIGNMENT);
   // check assignment
   pTree = pModelValue->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_1");
   pModelValue = pModel->getModelValues()[1];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "K2");
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   pModelValue = pModel->getModelValues()[2];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "K3");
   // check assignment
   pTree = pModelValue->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_3");
   CPPUNIT_ASSERT(pModel->getReactions().size() == 6);
   // check reactions
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction1");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[1];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 2);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction2");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[2];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction3");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[3];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 0);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction4");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[4];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 2);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction5");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[5];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 3);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction6");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   // export to SBML
   std::string s = pDataModel->exportSBMLToString(NULL, 1, 2);
   CPPUNIT_ASSERT(s.empty() == false);
   // due to the bugfix for Bug 1086 and some issues with libsbml and the current exporter,
   // we now no longer have a L1 document in the datamodel if there was an SBMLDocument prior
   // to exporting to L1 already.
   // To test now, we have to call newModel on the datamodel to delete the old sbml document,
   // and reimport the exported model
   // This will also lead to a Level 2 Version 1 model since we convert all Level 1 model to
   //  Level 2 Version 1 on import, but we can at least test if the export worked.
   pCOPASIDATAMODEL->newModel(NULL, true);
   CPPUNIT_ASSERT(pCOPASIDATAMODEL->importSBMLFromString(s));
   // check the sbml model
   const SBMLDocument* pDocument = pCOPASIDATAMODEL->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 1);
   const Model* pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getListOfFunctionDefinitions()->size() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getListOfCompartments()->size() == 1);
   CPPUNIT_ASSERT(pSBMLModel->getListOfSpecies()->size() == 6);
   CPPUNIT_ASSERT(pSBMLModel->getListOfParameters()->size() == 3);
   CPPUNIT_ASSERT(pSBMLModel->getListOfRules()->size() == 6);
   CPPUNIT_ASSERT(pSBMLModel->getListOfReactions()->size() == 6);
   std::map<std::string, const Rule*> ruleMap;
   unsigned int i, iMax = pSBMLModel->getListOfRules()->size();
   const Rule* pRule = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pRule = pSBMLModel->getRule(i);
       ruleMap.insert(std::pair<std::string, const Rule*>(pRule->getVariable(), pRule));
     }
   // check the rules
   std::map<std::string, const Rule*>::const_iterator pos = ruleMap.find("parameter_1");
   CPPUNIT_ASSERT(pos != ruleMap.end());
   pRule = pos->second;
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == "parameter_1");
   const ASTNode* pMath = pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // only check the infix
   std::string formula = pRule->getFormula();
   CPPUNIT_ASSERT(formula == "3 * 4.5");
   pos = ruleMap.find("parameter_3");
   CPPUNIT_ASSERT(pos != ruleMap.end());
   pRule = pos->second;
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == "parameter_3");
   pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // only check the infix
   formula = pRule->getFormula();
   CPPUNIT_ASSERT(formula == "parameter_1 - 2 * 1.3");
   pos = ruleMap.find("species_3");
   CPPUNIT_ASSERT(pos != ruleMap.end());
   pRule = pos->second;
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == "species_3");
   pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // only check the infix
   formula = pRule->getFormula();
   CPPUNIT_ASSERT(formula == "parameter_1 - 3.5 * 1.3 + (3 * 2.4 - 5.23)");
   pos = ruleMap.find("species_4");
   CPPUNIT_ASSERT(pos != ruleMap.end());
   pRule = pos->second;
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == "species_4");
   pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // only check the infix
   formula = pRule->getFormula();
   CPPUNIT_ASSERT(formula == "3.4 + parameter_1");
   pos = ruleMap.find("species_5");
   CPPUNIT_ASSERT(pos != ruleMap.end());
   pRule = pos->second;
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == "species_5");
   pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // only check the infix
   formula = pRule->getFormula();
   CPPUNIT_ASSERT(formula == "(parameter_2 + 1.4) / 2");
   pos = ruleMap.find("species_6");
   CPPUNIT_ASSERT(pos != ruleMap.end());
   pRule = pos->second;
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getVariable() == "species_6");
   pRule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // only check the infix
   formula = pRule->getFormula();
   CPPUNIT_ASSERT(formula == "parameter_3 - 3.4 * 1.3 + (3 * parameter_1 - 5.23)");
   // check the reactions
   const Reaction* pSBMLReaction = pSBMLModel->getReaction(0);
   CPPUNIT_ASSERT(pSBMLReaction != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfModifiers()->size() == 0);
   CPPUNIT_ASSERT(pSBMLReaction->getReversible() == true);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw() != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw()->getListOfParameters()->size() == 0);
   pMath = pSBMLReaction->getKineticLaw()->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   formula = pSBMLReaction->getKineticLaw()->getFormula();
   CPPUNIT_ASSERT(formula == "compartment_1 * 3 * parameter_1");
   pSBMLReaction = pSBMLModel->getReaction(1);
   CPPUNIT_ASSERT(pSBMLReaction != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfModifiers()->size() == 0);
   CPPUNIT_ASSERT(pSBMLReaction->getReversible() == true);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw() != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw()->getListOfParameters()->size() == 0);
   pMath = pSBMLReaction->getKineticLaw()->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   formula = pSBMLReaction->getKineticLaw()->getFormula();
   CPPUNIT_ASSERT(formula == "compartment_1 * (parameter_2 + parameter_1)");
   pSBMLReaction = pSBMLModel->getReaction(2);
   CPPUNIT_ASSERT(pSBMLReaction != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfModifiers()->size() == 0);
   CPPUNIT_ASSERT(pSBMLReaction->getReversible() == true);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw() != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw()->getListOfParameters()->size() == 0);
   pMath = pSBMLReaction->getKineticLaw()->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   formula = pSBMLReaction->getKineticLaw()->getFormula();
   CPPUNIT_ASSERT(formula == "compartment_1 * (species_2 - parameter_1 * 1.3)");
   pSBMLReaction = pSBMLModel->getReaction(3);
   CPPUNIT_ASSERT(pSBMLReaction != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfModifiers()->size() == 0);
   CPPUNIT_ASSERT(pSBMLReaction->getReversible() == true);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw() != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw()->getListOfParameters()->size() == 0);
   pMath = pSBMLReaction->getKineticLaw()->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   formula = pSBMLReaction->getKineticLaw()->getFormula();
   CPPUNIT_ASSERT(formula == "compartment_1 * ((species_2 + species_1) / 2)");
   pSBMLReaction = pSBMLModel->getReaction(4);
   CPPUNIT_ASSERT(pSBMLReaction != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfModifiers()->size() == 0);
   CPPUNIT_ASSERT(pSBMLReaction->getReversible() == true);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw() != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw()->getListOfParameters()->size() == 0);
   pMath = pSBMLReaction->getKineticLaw()->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   formula = pSBMLReaction->getKineticLaw()->getFormula();
   CPPUNIT_ASSERT(formula == "compartment_1 * (parameter_1 - species_2 * 1.3 + (3 * parameter_3 - 5.23))");
   pSBMLReaction = pSBMLModel->getReaction(5);
   CPPUNIT_ASSERT(pSBMLReaction != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfReactants()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfProducts()->size() == 1);
   CPPUNIT_ASSERT(pSBMLReaction->getListOfModifiers()->size() == 0);
   CPPUNIT_ASSERT(pSBMLReaction->getReversible() == true);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw() != NULL);
   CPPUNIT_ASSERT(pSBMLReaction->getKineticLaw()->getListOfParameters()->size() == 0);
   pMath = pSBMLReaction->getKineticLaw()->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   formula = pSBMLReaction->getKineticLaw()->getFormula();
   CPPUNIT_ASSERT(formula == "compartment_1 * (parameter_1 - parameter_3 * 1.3 + (3 * parameter_2 - 5.23))");
 }
Member Data Documentation
const char * test000068::MODEL_STRING1 static protected
Definition at line 33 of file test000068.h.
Referenced by test_bug1068().
CCopasiDataModel * test000068::pCOPASIDATAMODEL = NULL static protected
Definition at line 34 of file test000068.h.
Referenced by setUp(), and test_bug1068().
The documentation for this class was generated from the following files:
test000068.h
test000068.cpp