COPASI API: CCopasiXMLParser::RenderCurveElement Class Reference
CCopasiXMLParser::RenderCurveElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
RenderCurveElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~RenderCurveElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { RenderCurve = 0, ListOfElements }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4236 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::RenderCurveElement::Element private
Enumerator
RenderCurve
ListOfElements
Definition at line 4243 of file CCopasiXMLParser.h.
     {
       RenderCurve = 0,
       ListOfElements
     };
Constructor & Destructor Documentation
CCopasiXMLParser::RenderCurveElement::RenderCurveElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 12137 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::RenderCurveElement::~RenderCurveElement () virtual
Destructor
Definition at line 12142 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::RenderCurveElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 12244 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pListOfCurveElements, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case RenderCurve:
         if (strcmp(pszName, "Curve"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Curve", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCommon.pListOfCurveElements = NULL;
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case ListOfElements:
         if (strcmp(pszName, "ListOfElements"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfElements", mParser.getCurrentLineNumber());
         //tell the handler where to continue
         mCurrentElement = RenderCurve;
         //no need to delete Handler (since it is the only one the destructor
         //will handle it)
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::RenderCurveElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 12147 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CCopasiMessage::EXCEPTION, CLGroup::getElement(), CLRenderCurve::getListOfCurveElements(), CLGroup::getNumElements(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive1D::parseDashArray(), CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, SCopasiXMLParserCommon::pListOfCurveElements, CLRenderCurve::setEndHead(), CLRenderCurve::setStartHead(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), strToDouble(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * Stroke;
   const char * StrokeWidth;
   const char * StrokeDashArray;
   const char * StartHead;
   const char * EndHead;
   CLRenderCurve* pRenderCurve = NULL;
   switch (mCurrentElement)
     {
       case RenderCurve:
         if (strcmp(pszName, "Curve"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Curve", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         Stroke = mParser.getAttributeValue("stroke", papszAttrs, false);
         StrokeWidth = mParser.getAttributeValue("stroke-width", papszAttrs, false);
         StrokeDashArray = mParser.getAttributeValue("stroke-dasharray", papszAttrs, false);
         StartHead = mParser.getAttributeValue("startHead", papszAttrs, false);
         EndHead = mParser.getAttributeValue("endHead", papszAttrs, false);
         pRenderCurve = new CLRenderCurve();
         if (Transform != NULL)
           {
             pRenderCurve->parseTransformation(Transform);
           }
         if (Stroke != NULL)
           {
             pRenderCurve->setStroke(Stroke);
           }
         if (StrokeWidth != NULL)
           {
             double width = strToDouble(StrokeWidth, NULL);
             pRenderCurve->setStrokeWidth(width);
           }
         if (StrokeDashArray != NULL)
           {
             pRenderCurve->parseDashArray(StrokeDashArray);
           }
         if (StartHead != NULL)
           {
             pRenderCurve->setStartHead(StartHead);
           }
         if (EndHead != NULL)
           {
             pRenderCurve->setEndHead(EndHead);
           }
         assert(mCommon.pGroup != NULL);
         mCommon.pGroup->addChildElement(pRenderCurve);
         // delete the polygon again since the addElement method made a copy
         delete pRenderCurve;
         pRenderCurve = dynamic_cast<CLRenderCurve*>(mCommon.pGroup->getElement(mCommon.pGroup->getNumElements() - 1));
         assert(pRenderCurve != NULL);
         mCommon.pListOfCurveElements = pRenderCurve->getListOfCurveElements();
         break;
       case ListOfElements:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "ListOfElements"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "ListOfElements", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new ListOfCurveElementsElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp