COPASI API: SensitivitiesWidget Class Reference
SensitivitiesWidget Class Reference
#include <SensitivitiesWidget.h>
Public Member Functions
virtual bool runTask ()
SensitivitiesWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
~SensitivitiesWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Slots
void slotChooseFunction (int)
void slotChooseSingleFunction ()
void slotChooseSingleVariable ()
void slotChooseSingleVariable2 ()
void slotChooseSubTask (int)
void slotChooseVariable (int)
void slotChooseVariable2 (int)
Private Member Functions
void init ()
void initCombos ()
void updateAllLineditEnable ()
void updateComboBoxes (CSensProblem::SubTaskType type)
void updateLineeditEnable (const SensWidgetComboBox *box, QWidget *w1, QWidget *w2)
Private Attributes
const CCopasiObject * mpSingleFunction
const CCopasiObject * mpSingleVariable
const CCopasiObject * mpSingleVariable2
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 31 of file SensitivitiesWidget.h.
Constructor & Destructor Documentation
SensitivitiesWidget::SensitivitiesWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0) explicit
Constructs a SensitivitiesWidget which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
Definition at line 44 of file SensitivitiesWidget.cpp.
References init().
   : TaskWidget(parent, name, fl),
     mpSingleFunction(NULL),
     mpSingleVariable(NULL),
     mpSingleVariable2(NULL)
 {
   setupUi(this);
   init();
   retranslateUi(this);
 }
SensitivitiesWidget::~SensitivitiesWidget ()
Definition at line 59 of file SensitivitiesWidget.cpp.
 {}
Member Function Documentation
CCopasiMethod * SensitivitiesWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 175 of file SensitivitiesWidget.cpp.
References CSensMethod::createMethod().
 {return CSensMethod::createMethod(type);}
void SensitivitiesWidget::init () private
Definition at line 62 of file SensitivitiesWidget.cpp.
References CQIconResource::copasi, CQIconResource::icon(), initCombos(), TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, CQTaskHeaderWidget::setTaskName(), and CQTaskMethodWidget::showMethodParameters().
Referenced by SensitivitiesWidget().
 {
   mpHeaderWidget->setTaskName("Sensitivities");
   verticalLayout->insertWidget(0, mpHeaderWidget);  // header
   // verticalLayout->insertSpacing(1, 14);      // space between header and body
   mpMethodWidget->showMethodParameters(true);
   verticalLayout->addWidget(mpMethodWidget);
   verticalLayout->addWidget(mpBtnWidget);     // 'footer'
   // icons
   SingleFunctionChooser->setIcon(CQIconResource::icon(CQIconResource::copasi));
   SingleVariableChooser->setIcon(CQIconResource::icon(CQIconResource::copasi));
   SingleVariable2Chooser->setIcon(CQIconResource::icon(CQIconResource::copasi));
   // initialization
   initCombos();
 }
void SensitivitiesWidget::initCombos () private
Definition at line 329 of file SensitivitiesWidget.cpp.
References FROM_UTF8, CSensProblem::SubTaskName, and updateComboBoxes().
Referenced by init().
 {
   QStringList StringList;
   //std::vector<int> mFunctionIndexTable, mVariableIndexTable;
   // SubTaskChooser combo
   int i = 0;
   while (CSensProblem::SubTaskName[i].length() > 0)
     {
       StringList.append(FROM_UTF8(CSensProblem::SubTaskName[i]));
       ++i;
     }
   SubTaskChooser->insertItems(SubTaskChooser->count(), StringList);
   SubTaskChooser->setCurrentIndex(0);
   updateComboBoxes((CSensProblem::SubTaskType)0);
 }
bool SensitivitiesWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 206 of file SensitivitiesWidget.cpp.
References CObjectLists::EMPTY_LIST, FROM_UTF8, CKeyFactory::get(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CCopasiRootContainer::getKeyFactory(), CSensProblem::getNumberOfVariables(), CCopasiObject::getObjectDisplayName(), CCopasiTask::getProblem(), CSensProblem::getSubTaskType(), CSensProblem::getTargetFunctions(), CSensProblem::getVariables(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), TaskWidget::mChanged, CopasiWidget::mKey, mpSingleFunction, mpSingleVariable, mpSingleVariable2, CObjectLists::SINGLE_OBJECT, updateAllLineditEnable(), and updateComboBoxes().
 {
   loadCommon();
   loadMethod();
   CSensTask* sensTask =
     dynamic_cast<CSensTask *>(CCopasiRootContainer::getKeyFactory()->get(mKey));
   assert(sensTask);
   CSensProblem* problem =
     dynamic_cast<CSensProblem *>(sensTask->getProblem());
   assert(problem);
   //CSensMethod* method =
   //  dynamic_cast<CSensMethod *>(sensTask->getMethod());
   //assert(method);
   //mSubTaskType = problem->getSubTaskType();
   SubTaskChooser->setCurrentIndex((int)problem->getSubTaskType());
   updateComboBoxes(problem->getSubTaskType());
   CSensItem tmp = problem->getTargetFunctions();
   //target function
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (tmp.isSingleObject())
     {
       FunctionChooser->setCurrentObjectList(CObjectLists::SINGLE_OBJECT);
       mpSingleFunction = pDataModel->getDataObject(tmp.getSingleObjectCN());
       if (mpSingleFunction)
         FunctionLineEdit->setText(FROM_UTF8(mpSingleFunction->getObjectDisplayName()));
     }
   else
     {
       mpSingleFunction = NULL;
       FunctionChooser->setCurrentObjectList(tmp.getListType());
     }
   //variables 1
   if (problem->getNumberOfVariables() > 0)
     {
       tmp = problem->getVariables(0);
       if (tmp.isSingleObject())
         {
           VariableChooser->setCurrentObjectList(CObjectLists::SINGLE_OBJECT);
           mpSingleVariable = pDataModel->getDataObject(tmp.getSingleObjectCN());
           if (mpSingleVariable)
             VariableLineEdit->setText(FROM_UTF8(mpSingleVariable->getObjectDisplayName()));
         }
       else
         VariableChooser->setCurrentObjectList(tmp.getListType());
     }
   else
     {
       VariableChooser->setCurrentObjectList(CObjectLists::EMPTY_LIST);
       mpSingleVariable = NULL;
     }
   //variables 2
   if (problem->getNumberOfVariables() > 1)
     {
       tmp = problem->getVariables(1);
       if (tmp.isSingleObject())
         {
           Variable2Chooser->setCurrentObjectList(CObjectLists::SINGLE_OBJECT);
           mpSingleVariable2 = pDataModel->getDataObject(tmp.getSingleObjectCN());
           if (mpSingleVariable2)
             Variable2LineEdit->setText(FROM_UTF8(mpSingleVariable2->getObjectDisplayName()));
         }
       else
         Variable2Chooser->setCurrentObjectList(tmp.getListType());
     }
   else
     {
       Variable2Chooser->setCurrentObjectList(CObjectLists::EMPTY_LIST);
       mpSingleVariable2 = NULL;
     }
   //  initCombos(problem);
   mChanged = false;
   updateAllLineditEnable();
   return true;
 }
bool SensitivitiesWidget::runTask () virtual
Implements TaskWidget.
Definition at line 178 of file SensitivitiesWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), and CObjectLists::SINGLE_OBJECT.
 {
   if (FunctionChooser->getCurrentObjectList() != CObjectLists::SINGLE_OBJECT)
     FunctionLineEdit->setText(QApplication::translate("SensitivitiesWidget", "[Please Choose Object.] --->", 0, QApplication::UnicodeUTF8));
   if (!commonBeforeRunTask()) return false;
   bool success = true;
   if (!commonRunTask()) success = false;
   return success;
 }
bool SensitivitiesWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 83 of file SensitivitiesWidget.cpp.
References CSensProblem::addVariables(), CCopasiDataModel::changed(), CSensProblem::changeTargetFunctions(), CObjectLists::EMPTY_LIST, CKeyFactory::get(), CCopasiObject::getCN(), CCopasiRootContainer::getKeyFactory(), CSensItem::getListType(), CCopasiTask::getMethod(), CCopasiTask::getProblem(), TaskWidget::mChanged, CopasiWidget::mKey, CopasiWidget::mpDataModel, mpSingleFunction, mpSingleVariable, mpSingleVariable2, CSensProblem::removeVariables(), TaskWidget::saveCommon(), TaskWidget::saveMethod(), CSensItem::setListType(), CSensItem::setSingleObjectCN(), CSensProblem::setSubTaskType(), and CObjectLists::SINGLE_OBJECT.
 {
   saveCommon();
   saveMethod();
   CSensTask* sensTask =
     dynamic_cast<CSensTask *>(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (sensTask == NULL)
     return false;
   CSensProblem* problem =
     dynamic_cast<CSensProblem *>(sensTask->getProblem());
   if (problem == NULL)
     return false;
   CSensMethod* method =
     dynamic_cast<CSensMethod *>(sensTask->getMethod());
   if (method == NULL)
     return false;
   // subtask
   problem->setSubTaskType((CSensProblem::SubTaskType)SubTaskChooser->currentIndex());
   CSensItem tmp;
   // target function
   if (FunctionChooser->getCurrentObjectList() == CObjectLists::SINGLE_OBJECT)
     {
       if (mpSingleFunction)
         tmp.setSingleObjectCN(mpSingleFunction->getCN());
     }
   else
     tmp.setListType(FunctionChooser->getCurrentObjectList());
   problem->changeTargetFunctions(tmp);
   // variables 1
   if (VariableChooser->getCurrentObjectList() == CObjectLists::SINGLE_OBJECT)
     {
       if (mpSingleVariable)
         tmp.setSingleObjectCN(mpSingleVariable->getCN());
     }
   else
     tmp.setListType(VariableChooser->getCurrentObjectList());
   problem->removeVariables();
   if (tmp.getListType() != CObjectLists::EMPTY_LIST)
     problem->addVariables(tmp);
   else
     return true;
   //variables 2
   CSensItem tmp2;
   if (Variable2Chooser->getCurrentObjectList() == CObjectLists::SINGLE_OBJECT)
     {
       if (mpSingleVariable2)
         tmp2.setSingleObjectCN(mpSingleVariable2->getCN());
     }
   else
     tmp2.setListType(Variable2Chooser->getCurrentObjectList());
   // write variables to problem
   problem->removeVariables();
   if (tmp.getListType() != CObjectLists::EMPTY_LIST)
     {
       problem->addVariables(tmp);
       if (tmp2.getListType() != CObjectLists::EMPTY_LIST)
         problem->addVariables(tmp2);
     }
   // :TODO Bug 322: This should only be called when actual changes have been saved.
   // However we do not track the changes for the variables we just delete them and add them again.
   if (true)
     {
       if (mpDataModel != NULL)
         {
           mpDataModel->changed();
         }
       mChanged = false;
     }
   return true;
 }
void SensitivitiesWidget::slotChooseFunction (int) private slot
Definition at line 369 of file SensitivitiesWidget.cpp.
References updateAllLineditEnable().
 {
   updateAllLineditEnable();
 }
void SensitivitiesWidget::slotChooseSingleFunction () private slot
Definition at line 390 of file SensitivitiesWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), mpSingleFunction, CQSimpleSelectionTree::ObservedValues, CObjectLists::SINGLE_OBJECT, and CQSimpleSelectionTree::Variables.
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
         CQSimpleSelectionTree::Variables |
         CQSimpleSelectionTree::ObservedValues);
   if (pObject)
     {
       FunctionLineEdit->setText(FROM_UTF8(pObject->getObjectDisplayName()));
       mpSingleFunction = pObject;
       FunctionChooser->setCurrentObjectList(CObjectLists::SINGLE_OBJECT);
     }
 }
void SensitivitiesWidget::slotChooseSingleVariable () private slot
Definition at line 407 of file SensitivitiesWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQSimpleSelectionTree::InitialTime, mpSingleVariable, CQSimpleSelectionTree::Parameters, and CObjectLists::SINGLE_OBJECT.
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
         CQSimpleSelectionTree::InitialTime |
         CQSimpleSelectionTree::Parameters);
   if (pObject)
     {
       VariableLineEdit->setText(FROM_UTF8(pObject->getObjectDisplayName()));
       mpSingleVariable = pObject;
       VariableChooser->setCurrentObjectList(CObjectLists::SINGLE_OBJECT);
     }
 }
void SensitivitiesWidget::slotChooseSingleVariable2 () private slot
Definition at line 424 of file SensitivitiesWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQSimpleSelectionTree::InitialTime, mpSingleVariable2, CQSimpleSelectionTree::Parameters, and CObjectLists::SINGLE_OBJECT.
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
         CQSimpleSelectionTree::InitialTime |
         CQSimpleSelectionTree::Parameters);
   if (pObject)
     {
       Variable2LineEdit->setText(FROM_UTF8(pObject->getObjectDisplayName()));
       mpSingleVariable2 = pObject;
       Variable2Chooser->setCurrentObjectList(CObjectLists::SINGLE_OBJECT);
     }
 }
void SensitivitiesWidget::slotChooseSubTask (int) private slot
Definition at line 359 of file SensitivitiesWidget.cpp.
References updateAllLineditEnable(), and updateComboBoxes().
 {
   CSensProblem::SubTaskType subTaskType = (CSensProblem::SubTaskType)SubTaskChooser->currentIndex();
   updateComboBoxes(subTaskType);
   updateAllLineditEnable();
 }
void SensitivitiesWidget::slotChooseVariable (int) private slot
Definition at line 376 of file SensitivitiesWidget.cpp.
References updateAllLineditEnable().
 {
   updateAllLineditEnable();
 }
void SensitivitiesWidget::slotChooseVariable2 (int) private slot
Definition at line 383 of file SensitivitiesWidget.cpp.
References updateAllLineditEnable().
 {
   updateAllLineditEnable();
 }
bool SensitivitiesWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 192 of file SensitivitiesWidget.cpp.
References ListViews::findWidgetFromId(), CopasiWidget::mpListView, CQSensResultWidget::newResult(), pResult, and ListViews::switchToOtherWidget().
 {
   bool success = true;
   //setup the result widget
   CQSensResultWidget *pResult =
     dynamic_cast<CQSensResultWidget*>(mpListView->findWidgetFromId(341));
   if (pResult) pResult->newResult();
   if (success && isVisible()) mpListView->switchToOtherWidget(341, ""); //change to the results window
   return success;
 }
void SensitivitiesWidget::updateAllLineditEnable () private
This calls updateLineeditEnable() for all three combo boxes
Definition at line 316 of file SensitivitiesWidget.cpp.
References updateLineeditEnable().
Referenced by loadTask(), slotChooseFunction(), slotChooseSubTask(), slotChooseVariable(), and slotChooseVariable2().
 {
   /*
     updateLineeditEnable(FunctionChooser, FunctionLineEdit, SingleFunctionChooserButton);
     updateLineeditEnable(VariableChooser, VariableLineEdit, SingleVariableChooserButton);
     updateLineeditEnable(Variable2Chooser, Variable2LineEdit, SingleVariable2ChooserButton);
   */
   updateLineeditEnable(FunctionChooser, FunctionLineEdit, SingleFunctionChooser);
   updateLineeditEnable(VariableChooser, VariableLineEdit, SingleVariableChooser);
   updateLineeditEnable(Variable2Chooser, Variable2LineEdit, SingleVariable2Chooser);
 }
void SensitivitiesWidget::updateComboBoxes (CSensProblem::SubTaskType type) private
updates the variable and target function boxes
Definition at line 348 of file SensitivitiesWidget.cpp.
References CSensProblem::getPossibleTargetFunctions(), and CSensProblem::getPossibleVariables().
Referenced by initCombos(), loadTask(), and slotChooseSubTask().
 {
   FunctionChooser->fillFromList(CSensProblem::getPossibleTargetFunctions(type));
   VariableChooser->fillFromList(CSensProblem::getPossibleVariables(type));
   Variable2Chooser->fillFromList(CSensProblem::getPossibleVariables(type));
 }
void SensitivitiesWidget::updateLineeditEnable (const SensWidgetComboBox * box, QWidget * w1, QWidget * w2) private
This checks if the combo box is set to "single object" and only then enables the two given widgets.
Definition at line 302 of file SensitivitiesWidget.cpp.
References SensWidgetComboBox::getCurrentObjectList(), and CObjectLists::SINGLE_OBJECT.
Referenced by updateAllLineditEnable().
 {
   if (!box) return;
   bool enable = false;
   if (box->getCurrentObjectList() == CObjectLists::SINGLE_OBJECT)
     enable = true;
   if (w1) w1->setVisible(enable);
   if (w2) w2->setVisible(enable);
 }
Member Data Documentation
const CCopasiObject* SensitivitiesWidget::mpSingleFunction private
Definition at line 72 of file SensitivitiesWidget.h.
Referenced by loadTask(), saveTask(), and slotChooseSingleFunction().
const CCopasiObject* SensitivitiesWidget::mpSingleVariable private
Definition at line 73 of file SensitivitiesWidget.h.
Referenced by loadTask(), saveTask(), and slotChooseSingleVariable().
const CCopasiObject* SensitivitiesWidget::mpSingleVariable2 private
Definition at line 74 of file SensitivitiesWidget.h.
Referenced by loadTask(), saveTask(), and slotChooseSingleVariable2().
The documentation for this class was generated from the following files:
SensitivitiesWidget.h
SensitivitiesWidget.cpp