COPASI API: CDependencyGraph Class Reference
CDependencyGraph Class Reference
#include <CDependencyGraph.h>
Public Member Functions
void addDependent (const size_t &node, const size_t &dependent)
CDependencyGraph ()
void clear ()
const std::set< size_t > & getDependents (const size_t &node) const
void resize (const size_t &n)
~CDependencyGraph ()
Private Member Functions
void addNode (const size_t &node)
Private Attributes
std::vector< CDependencyGraphNode > mNodes
Friends
std::ostream & operator<< (std::ostream &os, const CDependencyGraph &d)
Detailed Description
CDependencyGraph describes a dependency graph.
Definition at line 74 of file CDependencyGraph.h.
Constructor & Destructor Documentation
CDependencyGraph::CDependencyGraph ()
Constructor
Definition at line 52 of file CDependencyGraph.cpp.
 {}
CDependencyGraph::~CDependencyGraph ()
Desctructor
Definition at line 53 of file CDependencyGraph.cpp.
 {}
Member Function Documentation
void CDependencyGraph::addDependent (const size_t & node, const size_t & dependent)
Add a dependent for a particular node.
Parameters
node The number of the node.
dependent The number of the dependent node.
Definition at line 68 of file CDependencyGraph.cpp.
References addNode(), and mNodes.
Referenced by CHybridMethodODE45::setupDependencyGraph(), CHybridMethod::setupDependencyGraph(), CHybridMethodLSODA::setupDependencyGraph(), and CStochMethod::setupDependencyGraphAndBalances().
 {
   addNode(node);
   mNodes[node].addDependent(dependent);
 }
void CDependencyGraph::addNode (const size_t & node) private
Add a node with a given number.
Parameters
node The number of the node to add.
Definition at line 55 of file CDependencyGraph.cpp.
References mNodes.
Referenced by addDependent().
 {
   if (node >= mNodes.size())
     mNodes.resize(node + 1);
   //  mNodes.push_back(node);
 }
void CDependencyGraph::clear ()
Definition at line 86 of file CDependencyGraph.cpp.
References mNodes.
Referenced by CHybridMethodODE45::setupDependencyGraph(), CHybridMethod::setupDependencyGraph(), CHybridMethodLSODA::setupDependencyGraph(), and CStochMethod::setupDependencyGraphAndBalances().
 {mNodes.clear();}
const std::set< size_t > & CDependencyGraph::getDependents (const size_t & node) const
Retrieve a vector of dependents for a given node.
Parameters
node The number of the node to access.
Returns
A vector of node numbers.
Definition at line 74 of file CDependencyGraph.cpp.
References mNodes.
Referenced by CHybridMethod::fireReaction(), CHybridMethodLSODA::fireReaction(), CHybridMethod::integrateDeterministicPart(), CHybridMethodLSODA::integrateDeterministicPart(), CHybridMethod::integrateDeterministicPartEuler(), CStochNextReactionMethod::updatePriorityQueue(), and CStochMethod::updateSystemState().
 {
   static std::set< size_t > NoDependents;
   if (mNodes.size() <= node)
     {
       return NoDependents;
     }
   return mNodes[node].getDependents();
 }
void CDependencyGraph::resize (const size_t & n)
Definition at line 63 of file CDependencyGraph.cpp.
References mNodes.
Referenced by CStochMethod::setupDependencyGraphAndBalances().
 {
   mNodes.resize(n);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CDependencyGraph & d) friend
insert operator
Definition at line 102 of file CDependencyGraph.cpp.
 {
   unsigned int i;
   for (i = 0; i < d.mNodes.size(); i++)
     os << d.mNodes[i];
   os << std::endl;
   return os;
 }
Member Data Documentation
std::vector<CDependencyGraphNode> CDependencyGraph::mNodes private
A vector containing the nodes in the graph
Definition at line 116 of file CDependencyGraph.h.
Referenced by addDependent(), addNode(), clear(), getDependents(), operator<<(), and resize().
The documentation for this class was generated from the following files:
CDependencyGraph.h
CDependencyGraph.cpp