COPASI API: CCopasiXMLParser::ParameterElement Class Reference
CCopasiXMLParser::ParameterElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ParameterElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ParameterElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Parameter = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2216 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ParameterElement::Element private
Enum of invoked parsers
Enumerator
Parameter
Definition at line 2224 of file CCopasiXMLParser.h.
     {
       Parameter = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ParameterElement::ParameterElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 9008 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ParameterElement::~ParameterElement () virtual
Destructor
Definition at line 9013 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::ParameterElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 9144 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Parameter:
         if (strcmp(pszName, "Parameter"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Parameter", mParser.getCurrentLineNumber());
         mCurrentElement = START_ELEMENT;
         mParser.popElementHandler();
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ParameterElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 9016 of file CCopasiXMLParser.cpp.
References CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::CN, CCopasiParameter::DOUBLE, CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CCopasiParameter::FILE, CKeyFactory::get(), CCopasiParameter::getKey(), CCopasiObject::getKey(), CCopasiParameter::INT, CCopasiParameter::INVALID, CKeyFactory::isValidKey(), CCopasiParameter::KEY, SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentParameter, CCopasiParameter::STRING, strToInt(), strToUnsignedInt(), toEnum(), CCopasiParameter::UDOUBLE, CCopasiParameter::UINT, UNKNOWN_ELEMENT, SCopasiXMLParserCommon::UnmappedKeyParameters, and CCopasiParameter::XMLType.
 {
   mCurrentElement++; // We should always be on the next element
   const char * cValue = NULL;
   const char * cType = NULL;
   std::string name;
   std::string sValue("");
   bool UnmappedKey = false;
   void * pValue = NULL;
   CCopasiParameter::Type type;
   C_FLOAT64 d;
   C_INT32 i;
   size_t ui;
   bool b;
   switch (mCurrentElement)
     {
       case Parameter:
         if (strcmp(pszName, "Parameter"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Parameter", mParser.getCurrentLineNumber());
         // Parameter has attributes name, type and value
         name = mParser.getAttributeValue("name", papszAttrs);
         cType = mParser.getAttributeValue("type", papszAttrs);
         type = toEnum(cType, CCopasiParameter::XMLType, CCopasiParameter::INVALID);
         cValue = mParser.getAttributeValue("value", papszAttrs);
         if (cValue != NULL)
           {
             sValue = cValue;
           }
         switch (type)
           {
             case CCopasiParameter::DOUBLE:
               d = CCopasiXMLInterface::DBL(sValue.c_str());
               pValue = &d;
               break;
             case CCopasiParameter::UDOUBLE:
               d = CCopasiXMLInterface::DBL(sValue.c_str());
               pValue = &d;
               break;
             case CCopasiParameter::INT:
               i = strToInt(sValue.c_str());
               pValue = &i;
               break;
             case CCopasiParameter::UINT:
               ui = strToUnsignedInt(sValue.c_str());
               pValue = &ui;
               break;
             case CCopasiParameter::BOOL:
               if (sValue == "0" || sValue == "false")
                 {
                   b = false;
                 }
               else
                 {
                   b = true;
                 }
               pValue = &b;
               break;
             case CCopasiParameter::STRING:
             case CCopasiParameter::FILE:
             case CCopasiParameter::CN:
               pValue = &sValue;
               break;
             case CCopasiParameter::KEY:
             {
               if (sValue != "" &&
                   CKeyFactory::isValidKey(sValue))
                 {
                   CCopasiObject * pObject = mCommon.KeyMap.get(sValue);
                   if (pObject)
                     {
                       sValue = pObject->getKey();
                     }
                   else
                     {
                       UnmappedKey = true;
                     }
                 }
               pValue = &sValue;
             }
             break;
             default:
               CCopasiMessage(CCopasiMessage::ERROR, MCXML + 16, name.c_str(), cType, mParser.getCurrentLineNumber());
               pValue = NULL;
               break;
           }
         mCommon.pCurrentParameter = new CCopasiParameter(name, type, pValue);
         if (UnmappedKey)
           {
             mCommon.UnmappedKeyParameters.push_back(mCommon.pCurrentParameter->getKey());
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp