COPASI API: CLRelAbsVector Class Reference
CLRelAbsVector Class Reference
#include <CLRelAbsVector.h>
Public Member Functions
CLRelAbsVector (double a=0.0, double r=0.0)
CLRelAbsVector (const std::string &coordString)
CLRelAbsVector (const RelAbsVector &source)
double getAbsoluteValue () const
double getRelativeValue () const
bool operator!= (const CLRelAbsVector &other) const
CLRelAbsVector operator+ (const CLRelAbsVector &other) const
CLRelAbsVector operator/ (double x) const
CLRelAbsVector & operator= (const CLRelAbsVector &src)
bool operator== (const CLRelAbsVector &other) const
void setAbsoluteValue (double abs)
void setCoordinate (double abs, double rel=0.0)
void setCoordinate (const std::string &coordString)
void setRelativeValue (double rel)
RelAbsVector * toSBML () const
std::string toString () const
Protected Attributes
double mAbs
double mRel
Detailed Description
Definition at line 22 of file CLRelAbsVector.h.
Constructor & Destructor Documentation
CLRelAbsVector::CLRelAbsVector (double a = 0.0, double r = 0.0)
Constructor with two values. First value sets the absolute value, econd sets the relative value.
Definition at line 30 of file CLRelAbsVector.cpp.
Referenced by operator+(), and operator/().
                                                 : mAbs(a), mRel(r)
 {
 }
CLRelAbsVector::CLRelAbsVector (const std::string & coordString)
Constructor with a string. The string has to be parsed. If the string does not represent a valid value, the relative and the absolute component of the CLRelAbsVector are set to NaN.
Constructor with two values. First value sets the absolute value, econd sets the relative value.
Definition at line 38 of file CLRelAbsVector.cpp.
References setCoordinate().
                                                           : mAbs(0.0), mRel(0.0)
 {
   setCoordinate(coordString);
 }
CLRelAbsVector::CLRelAbsVector (const RelAbsVector & source)
Constructor to generate object from the corresponding SBML object.
Definition at line 46 of file CLRelAbsVector.cpp.
                                                         :
     mAbs(source.getAbsoluteValue()),
     mRel(source.getRelativeValue())
 {
 }
Member Function Documentation
double CLRelAbsVector::getAbsoluteValue () const
Returns the absolute coordinate value.
Definition at line 161 of file CLRelAbsVector.cpp.
References mAbs.
Referenced by addToPath(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::create_linear_gradient_texture(), CLLayoutRenderer::create_radial_gradient_texture(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_text(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), getFont(), CLLayoutRenderer::getFontSpec(), getLinearGradient(), getPath(), getRadialGradient(), CLText::isSetFontSize(), CLGroup::isSetFontSize(), and moveToPoint().
 {
   return this->mAbs;
 }
double CLRelAbsVector::getRelativeValue () const
Returns the relative coordinate value.
Definition at line 169 of file CLRelAbsVector.cpp.
References mRel.
Referenced by addToPath(), CLGradientStops::CLGradientStops(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::create_linear_gradient_texture(), CLLayoutRenderer::create_radial_gradient_texture(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_text(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), getFont(), CLLayoutRenderer::getFontSpec(), getLinearGradient(), getPath(), getRadialGradient(), CLText::isSetFontSize(), CLGroup::isSetFontSize(), and moveToPoint().
 {
   return this->mRel;
 }
bool CLRelAbsVector::operator!= (const CLRelAbsVector & other) const
Definition at line 218 of file CLRelAbsVector.cpp.
 {
   return !((*this) == other);
 }
CLRelAbsVector CLRelAbsVector::operator+ (const CLRelAbsVector & other) const
addition operator
Definition at line 177 of file CLRelAbsVector.cpp.
References CLRelAbsVector(), mAbs, and mRel.
 {
   return CLRelAbsVector(this->mAbs + other.mAbs, this->mRel + other.mRel);
 }
CLRelAbsVector CLRelAbsVector::operator/ (double x) const
division by a double.
Definition at line 185 of file CLRelAbsVector.cpp.
References CLRelAbsVector(), mAbs, and mRel.
 {
   return CLRelAbsVector(this->mAbs / x, this->mRel / x);
 }
CLRelAbsVector & CLRelAbsVector::operator= (const CLRelAbsVector & src)
Definition at line 254 of file CLRelAbsVector.cpp.
References mAbs, and mRel.
 {
   if (&src != this)
     {
       this->mAbs = src.mAbs;
       this->mRel = src.mRel;
     }
   return *this;
 }
bool CLRelAbsVector::operator== (const CLRelAbsVector & other) const
Definition at line 190 of file CLRelAbsVector.cpp.
References mAbs, and mRel.
 {
   bool result = true;
   if (this->mAbs == 0.0)
     {
       result = (fabs(other.mAbs) < 1e-12);
     }
   else
     {
       result = (fabs((this->mAbs - other.mAbs) / this->mAbs) < 1e-12);
     }
   if (result)
     {
       if (this->mRel == 0.0)
         {
           result = (fabs(other.mRel) < 1e-12);
         }
       else
         {
           result = (fabs((this->mRel - other.mRel) / this->mRel) < 1e-12);
         }
     }
   return result;
 }
void CLRelAbsVector::setAbsoluteValue (double abs)
Sets the absolute coordinate value.
Definition at line 145 of file CLRelAbsVector.cpp.
References abs, and mAbs.
 {
   this->mAbs = abs;
 }
void CLRelAbsVector::setCoordinate (double abs, double rel = 0.0)
Sets the coordiantes.
Definition at line 55 of file CLRelAbsVector.cpp.
References abs, mAbs, and mRel.
Referenced by CLRelAbsVector().
 {
   this->mAbs = abs;
   this->mRel = rel;
 }
void CLRelAbsVector::setCoordinate (const std::string & coordString)
Sets the coordiantes from the given string.
Definition at line 64 of file CLRelAbsVector.cpp.
References mAbs, and mRel.
 {
   bool result = true;
   // first we remove all whitespaces from the string
   size_t i, iMax = coordString.size();
   std::string trimmed;
   for (i = 0; i < iMax; ++i)
     {
       if (!(coordString[i] == ' ' || coordString[i] == '\t' || coordString[i] == '\n' || coordString[i] == '\r'))
         {
           trimmed += coordString[i];
         }
     }
   if (trimmed.empty())
     {
       result = false;
     }
   else
     {
       char* s = new char[trimmed.size()+1];
       strncpy(s, trimmed.c_str(), trimmed.size() + 1);
       char* p = s;
       char* pp;
       // p is changed if the value is parsed
       double value = strtod(p, &pp);
       // check if strtod stopped at the '%' and if it is the last character in the string
       if ((*pp) == '%' && pp == (s + trimmed.size() - 1))
         {
           // we only have a relative value
           this->mAbs = 0.0;
           this->mRel = value;
         }
       else
         {
           // either pp is at the end, then we only have an absolute value
           // or pp has stopped on a '+' or '-' which connects the relative to the absolute value
           // or we have an error
           if ((*pp) == '\0')
             {
               this->mAbs = value;
               this->mRel = 0.0;
             }
           else if ((*pp) == '+' || (*pp) == '-')
             {
               this->mAbs = value;
               p = pp;
               double value = strtod(p, &pp);
               // pp must point to the '%' character
               if ((*pp) != '%' || pp != (s + trimmed.size() - 1))
                 {
                   result = false;
                 }
               else
                 {
                   this->mRel = value;
                 }
             }
           else
             {
               result = false;
             }
         }
       delete[] s;
     }
   if (result == false)
     {
       // set relative and absolute value to NaN
       this->mAbs = std::numeric_limits<double>::quiet_NaN();
       this->mRel = std::numeric_limits<double>::quiet_NaN();
     }
 }
void CLRelAbsVector::setRelativeValue (double rel)
Sets the relative coordinate value.
Definition at line 153 of file CLRelAbsVector.cpp.
References mRel.
 {
   this->mRel = rel;
 }
RelAbsVector * CLRelAbsVector::toSBML () const
Converts this object to the corresponding SBML object.
Definition at line 268 of file CLRelAbsVector.cpp.
References mAbs, and mRel.
Referenced by CLRenderPoint::addSBMLAttributes(), CLGradientStop::toSBML(), CLLinearGradient::toSBML(), CLRadialGradient::toSBML(), CLImage::toSBML(), CLEllipse::toSBML(), CLRenderCubicBezier::toSBML(), CLRectangle::toSBML(), CLText::toSBML(), and CLGroup::toSBML().
 {
   return new RelAbsVector(mAbs, mRel);
 }
std::string CLRelAbsVector::toString () const
Definition at line 223 of file CLRelAbsVector.cpp.
References mAbs, and mRel.
Referenced by operator<<(), CCopasiXML::saveEllipseElement(), CCopasiXML::saveGradientStop(), CCopasiXML::saveImageElement(), CCopasiXML::saveLinearGradient(), CCopasiXML::saveRadialGradient(), CCopasiXML::saveRectangleElement(), CCopasiXML::saveRenderPoint(), and CCopasiXML::saveRenderTextElement().
 {
   std::ostringstream os;
   if (this->mAbs != 0.0 || this->mRel == 0.0)
     {
       os << this->mAbs;
       if (this->mRel < 0.0)
         {
           os << this->mRel << "%";
         }
       else if (this->mRel > 0.0)
         {
           os << "+" << this->mRel << "%";
         }
     }
   else
     {
       os << this->mRel << "%";
     }
   return os.str();
 }
Member Data Documentation
double CLRelAbsVector::mAbs protected
Definition at line 25 of file CLRelAbsVector.h.
Referenced by getAbsoluteValue(), operator+(), operator/(), operator=(), operator==(), setAbsoluteValue(), setCoordinate(), toSBML(), and toString().
double CLRelAbsVector::mRel protected
Definition at line 26 of file CLRelAbsVector.h.
Referenced by getRelativeValue(), operator+(), operator/(), operator=(), operator==(), setCoordinate(), setRelativeValue(), toSBML(), and toString().
The documentation for this class was generated from the following files:
CLRelAbsVector.h
CLRelAbsVector.cpp