COPASI API: CCopasiXMLInterface.cpp File Reference
CCopasiXMLInterface.cpp File Reference
#include <fstream>
#include <limits>
#include <cmath>
#include "copasi.h"
#include "CCopasiXMLInterface.h"
#include "model/CModel.h"
#include "report/CReportDefinition.h"
#include "report/CReportDefinitionVector.h"
#include "plot/COutputDefinitionVector.h"
#include "plot/CPlotSpecification.h"
#include "CCopasiXMLParser.h"
#include "utilities/CCopasiVector.h"
#include "utilities/CSlider.h"
#include "utilities/CDirEntry.h"
#include "commandline/CLocaleString.h"
Functions
void encodeATTRIBUTE (const char &chr, std::ostringstream &xml)
void encodeCHARACTER (const char &chr, std::ostringstream &xml)
void encodeNONE (const char &chr, std::ostringstream &xml)
void encodeSTD (const char &chr, std::ostringstream &xml)
std::ostream & operator<< (std::ostream &os, const CCopasiXMLInterface::DBL &dbl)
std::ostream & operator<< (std::ostream &os, const CXMLAttributeList &attr)
Function Documentation
void encodeATTRIBUTE (const char & chr, std::ostringstream & xml)
Definition at line 106 of file CCopasiXMLInterface.cpp.
Referenced by CCopasiXMLInterface::encode().
 {
   switch (chr)
     {
       case '&':
         xml << "&amp;";
         break;
       case '<':
         xml << "&lt;";
         break;
       case '\"':
         xml << "&quot;";
         break;
       case '\t':            // Without this <tab> is converted to <space>
         xml << "&#x09;";
         break;
       case '\n':            // Without this linebreak is converted to <space>
         xml << "&#x0a;";
         break;
       default:
         xml << chr;
         break;
     }
   return;
 }
void encodeCHARACTER (const char & chr, std::ostringstream & xml)
Definition at line 138 of file CCopasiXMLInterface.cpp.
Referenced by CCopasiXMLInterface::encode().
 {
   switch (chr)
     {
       case '&':
         xml << "&amp;";
         break;
       case '<':
         xml << "&lt;";
         break;
       default:
         xml << chr;
         break;
     }
   return;
 }
void encodeNONE (const char & chr, std::ostringstream & xml)
Definition at line 68 of file CCopasiXMLInterface.cpp.
Referenced by CCopasiXMLInterface::encode().
 {
   xml << chr;
   return;
 }
void encodeSTD (const char & chr, std::ostringstream & xml)
Definition at line 74 of file CCopasiXMLInterface.cpp.
Referenced by CCopasiXMLInterface::encode().
 {
   switch (chr)
     {
       case '&':
         xml << "&amp;";
         break;
       case '\'':
         xml << "&apos;";
         break;
       case '<':
         xml << "&lt;";
         break;
       case '>':
         xml << "&gt;";
         break;
       case '\"':
         xml << "&quot;";
         break;
       default:
         xml << chr;
         break;
     }
   return;
 }
std::ostream& operator<< (std::ostream & os, const CCopasiXMLInterface::DBL & dbl)
Definition at line 229 of file CCopasiXMLInterface.cpp.
References CCopasiXMLInterface::DBL::mValue.
 {
   os.precision(16);
   if (isnan(dbl.mValue))
     os << "NaN";
   else if (finite(dbl.mValue))
     os << dbl.mValue;
   else if (dbl.mValue > 0.0)
     os << "INF";
   else if (dbl.mValue < 0.0)
     os << "-INF";
   return os;
 }
std::ostream& operator<< (std::ostream & os, const CXMLAttributeList & attr)
Definition at line 558 of file CCopasiXMLInterface.cpp.
References CXMLAttributeList::mAttributeList, and CXMLAttributeList::mSaveList.
 {
   std::vector< std::string >::const_iterator itAttr = attr.mAttributeList.begin();
   std::vector< bool >::const_iterator itSave = attr.mSaveList.begin();
   std::vector< bool >::const_iterator endSave = attr.mSaveList.end();
   for (; itSave != endSave; ++itSave)
     if (*itSave)
       {
         os << " " << *itAttr++;
         os << "=\"" << *itAttr++ << "\"";
       }
     else
       itAttr += 2;
   return os;
 }