COPASI API: CQPushButtonDelegate Class Reference
CQPushButtonDelegate Class Reference
#include <CQPushButtonDelegate.h>
Public Types
enum ButtonType { PushButton, ToolButton }
Signals
void clicked (const QModelIndex &)
Public Member Functions
CQPushButtonDelegate (const ButtonType &buttonType, QObject *parent=0)
CQPushButtonDelegate (const QIcon &icon, const QString &text, const ButtonType &buttonType, QObject *parent=0)
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void setEditorData (QWidget *pEditor, const QModelIndex &index) const
virtual void setModelData (QWidget *pEditor, QAbstractItemModel *pModel, const QModelIndex &index) const
virtual void updateEditorGeometry (QWidget *pEditor, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual ~CQPushButtonDelegate ()
Protected Slots
void slotButtonClicked ()
void slotEditorDeleted (QObject *pObject)
Private Attributes
ButtonType mButtonType
QMap< QAbstractButton
*, QModelIndex > mEditorToIndex
QIcon mIcon
QString mText
Detailed Description
Definition at line 13 of file CQPushButtonDelegate.h.
Member Enumeration Documentation
enum CQPushButtonDelegate::ButtonType
Enumerator
PushButton
ToolButton
Definition at line 18 of file CQPushButtonDelegate.h.
 {PushButton, ToolButton};
Constructor & Destructor Documentation
CQPushButtonDelegate::CQPushButtonDelegate (const ButtonType & buttonType, QObject * parent = 0)
Definition at line 14 of file CQPushButtonDelegate.cpp.
                     :
   QStyledItemDelegate(parent),
   mIcon(),
   mText(),
   mButtonType(buttonType),
   mEditorToIndex()
 {}
CQPushButtonDelegate::CQPushButtonDelegate (const QIcon & icon, const QString & text, const ButtonType & buttonType, QObject * parent = 0)
Definition at line 23 of file CQPushButtonDelegate.cpp.
                     :
   QStyledItemDelegate(parent),
   mIcon(icon),
   mText(text),
   mButtonType(buttonType),
   mEditorToIndex()
 {}
CQPushButtonDelegate::~CQPushButtonDelegate () virtual
Definition at line 34 of file CQPushButtonDelegate.cpp.
 {}
Member Function Documentation
void CQPushButtonDelegate::clicked (const QModelIndex &) signal
Referenced by createEditor(), and slotButtonClicked().
QWidget * CQPushButtonDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 37 of file CQPushButtonDelegate.cpp.
References clicked(), mButtonType, mEditorToIndex, mIcon, mText, PushButton, slotButtonClicked(), slotEditorDeleted(), and ToolButton.
 {
   QModelIndex  SourceIndex = index;
   const QAbstractItemModel *pModel = index.model();
   while (pModel->inherits("QSortFilterProxyModel"))
     {
       SourceIndex = static_cast< const QSortFilterProxyModel *>(pModel)->mapToSource(index);
       pModel = SourceIndex.model();
     }
   QAbstractButton * pEditor;
   QVariant Data;
   Data = SourceIndex.model()->data(SourceIndex, Qt::UserRole);
   if (Data.type() == QVariant::Icon)
     {
       mIcon = Data.value< QIcon >();
     }
   switch (mButtonType)
     {
       case PushButton:
         pEditor = new QPushButton(mIcon, mText, parent);
         break;
       case ToolButton:
         pEditor = new QToolButton(parent);
         if (mIcon.isNull())
           {
             Data = SourceIndex.model()->data(SourceIndex, Qt::DisplayRole);
             if (Data.type() == QVariant::String)
               {
                 mText = Data.toString();
               }
             pEditor->setText(mText);
           }
         else
           {
             pEditor->setIcon(mIcon);
           }
         break;
     }
   mEditorToIndex[pEditor] = SourceIndex;
   connect(pEditor, SIGNAL(clicked(bool)), this, SLOT(slotButtonClicked()));
   connect(pEditor, SIGNAL(destroyed(QObject *)), this, SLOT(slotEditorDeleted(QObject *)));
   return pEditor;
 }
void CQPushButtonDelegate::setEditorData (QWidget * pEditor, const QModelIndex & index) const virtual
Definition at line 96 of file CQPushButtonDelegate.cpp.
 {
   QString value = index.model()->data(index, Qt::EditRole).toString();
   QPushButton * pButton = static_cast< QPushButton * >(pEditor);
   if (pButton->icon().isNull())
     {
       pButton->setText(value);
     }
 }
void CQPushButtonDelegate::setModelData (QWidget * pEditor, QAbstractItemModel * pModel, const QModelIndex & index) const virtual
Definition at line 108 of file CQPushButtonDelegate.cpp.
 {}
void CQPushButtonDelegate::slotButtonClicked () protected slot
Definition at line 120 of file CQPushButtonDelegate.cpp.
References clicked(), and mEditorToIndex.
Referenced by createEditor().
 {
   QAbstractButton * pEditor = dynamic_cast< QAbstractButton *>(sender());
   if (pEditor)
     {
       QMap< QAbstractButton *, QModelIndex >::const_iterator found = mEditorToIndex.find(pEditor);
       if (found != mEditorToIndex.end())
         {
           emit clicked(found.value());
         }
     }
 }
void CQPushButtonDelegate::slotEditorDeleted (QObject * pObject) protected slot
Definition at line 135 of file CQPushButtonDelegate.cpp.
References mEditorToIndex.
Referenced by createEditor().
 {
   QAbstractButton * pEditor = dynamic_cast< QAbstractButton *>(sender());
   if (pEditor)
     {
       mEditorToIndex.remove(pEditor);
     }
 }
void CQPushButtonDelegate::updateEditorGeometry (QWidget * pEditor, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 113 of file CQPushButtonDelegate.cpp.
 {
   pEditor->setGeometry(option.rect);
 }
Member Data Documentation
ButtonType CQPushButtonDelegate::mButtonType private
Definition at line 48 of file CQPushButtonDelegate.h.
Referenced by createEditor().
QMap< QAbstractButton * , QModelIndex > CQPushButtonDelegate::mEditorToIndex mutable private
Definition at line 50 of file CQPushButtonDelegate.h.
Referenced by createEditor(), slotButtonClicked(), and slotEditorDeleted().
QIcon CQPushButtonDelegate::mIcon mutable private
Definition at line 46 of file CQPushButtonDelegate.h.
Referenced by createEditor().
QString CQPushButtonDelegate::mText mutable private
Definition at line 47 of file CQPushButtonDelegate.h.
Referenced by createEditor().
The documentation for this class was generated from the following files:
CQPushButtonDelegate.h
CQPushButtonDelegate.cpp