COPASI API: CRDFSubject Class Reference
CRDFSubject Class Reference
#include <CRDFSubject.h>
Public Types
enum eSubjectType { RESOURCE = 0, BLANK_NODE }
Public Member Functions
void clearData ()
CRDFSubject ()
CRDFSubject (const CRDFSubject &src)
const std::string & getBlankNodeID () const
const std::string & getResource () const
const eSubjectType & getType () const
const bool & isLocal () const
CRDFSubject & operator= (const CRDFSubject &rhs)
void setBlankNodeId (const std::string &blankNodeId)
void setResource (const std::string &resource, const bool &isLocal)
void setType (const eSubjectType &type)
~CRDFSubject ()
Private Member Functions
bool operator== (const CRDFSubject &rhs) const
Private Attributes
std::string mBlankNodeId
bool mIsLocalResource
std::string mResource
eSubjectType mType
Detailed Description
Definition at line 23 of file CRDFSubject.h.
Member Enumeration Documentation
enum CRDFSubject::eSubjectType
The two different types possible for subjects
Enumerator
RESOURCE
BLANK_NODE
Definition at line 30 of file CRDFSubject.h.
 {RESOURCE = 0, BLANK_NODE};
Constructor & Destructor Documentation
CRDFSubject::CRDFSubject ()
Default Constructor
Definition at line 22 of file CRDFSubject.cpp.
                         :
     mType(RESOURCE),
     mResource(""),
     mIsLocalResource(false),
     mBlankNodeId("")
 {}
CRDFSubject::CRDFSubject (const CRDFSubject & src)
Copy Constructor
Parameters
const CRDFSubject & src
Definition at line 29 of file CRDFSubject.cpp.
                                                :
     mType(src.mType),
     mResource(src.mResource),
     mIsLocalResource(src.mIsLocalResource),
     mBlankNodeId(src.mBlankNodeId)
 {}
CRDFSubject::~CRDFSubject ()
Destructor
Definition at line 36 of file CRDFSubject.cpp.
 {}
Member Function Documentation
void CRDFSubject::clearData ()
Reset all Data
Definition at line 94 of file CRDFSubject.cpp.
References mBlankNodeId, mIsLocalResource, mResource, mType, and RESOURCE.
 {
   mBlankNodeId = "";
   mResource = "";
   mType = CRDFSubject::RESOURCE;
   mIsLocalResource = false;
 }
const std::string & CRDFSubject::getBlankNodeID () const
Retrieve the ID of the blank node of the subject
Returns
const std::string & blankNodeId
Definition at line 91 of file CRDFSubject.cpp.
References mBlankNodeId.
Referenced by CRDFGraph::addTriplet(), CQRDFTreeView::enterProtected(), operator<<(), CRDFNode::setSubject(), and CRDFWriter::write().
   {return mBlankNodeId;}
const std::string & CRDFSubject::getResource () const
Retrieve the resource of the subject
Returns
const std::string & resource
Definition at line 82 of file CRDFSubject.cpp.
References mResource.
Referenced by CRDFGraph::addTriplet(), CQRDFTreeView::enterProtected(), CRDFGraph::guessGraphRoot(), operator<<(), and CRDFWriter::write().
   {return mResource;}
const CRDFSubject::eSubjectType & CRDFSubject::getType () const
Retrieve the type of the subject
Returns
const eSubjectType & type
Definition at line 73 of file CRDFSubject.cpp.
References mType.
Referenced by CRDFGraph::addTriplet(), CQRDFTreeView::enterProtected(), CRDFGraph::guessGraphRoot(), operator<<(), CRDFNode::setSubject(), and CRDFWriter::write().
   {return mType;}
const bool & CRDFSubject::isLocal () const
Check whehter the resource is local
Returns
const bool & isLocal
Definition at line 85 of file CRDFSubject.cpp.
References mIsLocalResource.
Referenced by CRDFGraph::addTriplet(), CRDFGraph::guessGraphRoot(), and setResource().
   {return mIsLocalResource;}
CRDFSubject & CRDFSubject::operator= (const CRDFSubject & rhs)
Definition at line 39 of file CRDFSubject.cpp.
References mBlankNodeId, mIsLocalResource, mResource, and mType.
 {
   if (this != &rhs)
     {
       mType = rhs.mType;
       mResource = rhs.mResource;
       mBlankNodeId = rhs.mBlankNodeId;
       mIsLocalResource = rhs.mIsLocalResource;
     }
   return *this;
 }
bool CRDFSubject::operator== (const CRDFSubject & rhs) const private
Definition at line 51 of file CRDFSubject.cpp.
References BLANK_NODE, mBlankNodeId, mIsLocalResource, mResource, mType, and RESOURCE.
   {
     if (mType == rhs.mType)
       {
         switch (mType)
           {
           case CRDFSubject::BLANK_NODE:
             if (mBlankNodeId == rhs.mBlankNodeId)
             {return true;}
             break;
           case CRDFSubject::RESOURCE:
             if (mResource == rhs.mResource && mIsLocalResource == rhs.mIsLocalResource)
             {return true;}
             break;
           }
       }
     return false;
   }
void CRDFSubject::setBlankNodeId (const std::string & blankNodeId)
Set the ID of the blank node of the subject
Parameters
const std::string & blankNodeId
Definition at line 88 of file CRDFSubject.cpp.
References mBlankNodeId.
Referenced by CRDFNode::setObject(), and CRDFParser::TripleHandler().
 {mBlankNodeId = blankNodeId;}
void CRDFSubject::setResource (const std::string & resource, const bool & isLocal)
Set the resource of the subject
Parameters
const std::string & resource
const bool & isLocal
Definition at line 76 of file CRDFSubject.cpp.
References isLocal(), mIsLocalResource, and mResource.
Referenced by CRDFGraph::createAboutNode(), and CRDFParser::TripleHandler().
 {
   mResource = resource;
   mIsLocalResource = isLocal;
 }
void CRDFSubject::setType (const eSubjectType & type)
Set the type of the subject
Parameters
const eSubjectType & type
Definition at line 70 of file CRDFSubject.cpp.
References mType.
Referenced by CRDFGraph::createAboutNode(), CRDFNode::setObject(), and CRDFParser::TripleHandler().
 {mType = type;}
Member Data Documentation
std::string CRDFSubject::mBlankNodeId private
The Id of the blank node for type BLANK_NODE
Definition at line 124 of file CRDFSubject.h.
Referenced by clearData(), getBlankNodeID(), operator=(), operator==(), and setBlankNodeId().
bool CRDFSubject::mIsLocalResource private
Stores whether the reources is resolve locally or remotely.
Definition at line 119 of file CRDFSubject.h.
Referenced by clearData(), isLocal(), operator=(), operator==(), and setResource().
std::string CRDFSubject::mResource private
The URI of the resource of type RESOURCE
Definition at line 114 of file CRDFSubject.h.
Referenced by clearData(), getResource(), operator=(), operator==(), and setResource().
eSubjectType CRDFSubject::mType private
The type of the subject
Definition at line 109 of file CRDFSubject.h.
Referenced by clearData(), getType(), operator=(), operator==(), and setType().
The documentation for this class was generated from the following files:
CRDFSubject.h
CRDFSubject.cpp