COPASI API: ReactionsWidget1 Class Reference
ReactionsWidget1 Class Reference
#include <ReactionsWidget1.h>
Public Member Functions
void copy ()
virtual bool leave ()
ReactionsWidget1 (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~ReactionsWidget1 ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Slots
virtual void slotBtnCopy ()
virtual void slotBtnDelete ()
virtual void slotBtnNew ()
virtual void slotCheckBoxClicked ()
virtual void slotComboBoxSelectionChanged (const QString &)
virtual void slotGotoFunction ()
virtual void slotLineEditChanged ()
virtual void slotNewFunction ()
virtual void slotParameterStatusChanged (int index, bool local)
virtual void slotTableChanged (int index, int sub, QString newValue)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
void FillWidgetFromRI ()
bool loadFromReaction (const CReaction *reaction)
bool saveToReaction ()
Protected Attributes
CReactionInterface * mpRi
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 35 of file ReactionsWidget1.h.
Constructor & Destructor Documentation
ReactionsWidget1::ReactionsWidget1 (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 53 of file ReactionsWidget1.cpp.
   : CopasiWidget(parent, name, f),
     mpRi(NULL)
 {
   setupUi(this);
   if (!name)
     setObjectName("ReactionsWidget1");
   setWindowTitle(trUtf8("ReactionsWidget1"));
   LineEdit2->setValidator(new ChemEqValidator(LineEdit2));
 #ifndef COPASI_DEBUG
   mpFast->hide();
 #endif
 }
ReactionsWidget1::~ReactionsWidget1 ()
Definition at line 71 of file ReactionsWidget1.cpp.
References mpRi, and pdelete.
 {
   pdelete(mpRi);
 }
Member Function Documentation
void ReactionsWidget1::copy ()
Definition at line 278 of file ReactionsWidget1.cpp.
References CModelExpansion::ElementsMap::add(), CModelExpansion::SetOfModelElements::addCompartment(), CModelExpansion::SetOfModelElements::addMetab(), CModelExpansion::SetOfModelElements::addReaction(), CCopasiVector< T >::begin(), C_INVALID_INDEX, ListViews::COMPARTMENT, ListViews::DELETE, CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CCopasiVector< T >::end(), FROM_UTF8, CReaction::getChemEq(), CModel::getCompartments(), CModelExpansion::ElementsMap::getDuplicateKey(), CCopasiDataModel::getModel(), CChemEq::getModifiers(), CCopasiObject::getObjectName(), CChemEq::getProducts(), CChemEq::getSubstrates(), ListViews::METABOLITE, CopasiWidget::mKey, CopasiWidget::mpDataModel, CopasiWidget::mpListView, CopasiWidget::mpObject, pdelete, CopasiWidget::protectedNotify(), ListViews::REACTION, CQNameSelectionDialog::setSelectionList(), and ListViews::switchToOtherWidget().
Referenced by CQTabWidget::slotBtnCopy().
 {
   CReaction* reac = dynamic_cast< CReaction * >(mpObject);
   if (reac == NULL) return;
   CModel * pModel = NULL;
   if (reac) pModel = mpDataModel->getModel();
   if (pModel == NULL) return; // for getting compartments and initializing cModelExpObj
   // Create and customize compartment choices dialog
   CQNameSelectionDialog * pDialog = new CQNameSelectionDialog(this);
   pDialog->resize(350, pDialog->height());
   pDialog->setToolTip("Cancel to re-use original species");
   pDialog->mpLblName->setText("compartment");
   pDialog->mpSelectionBox->clear();
   pDialog->mpSelectionBox->setDuplicatesEnabled(false);
   pDialog->mpSelectionBox->setEditable(false); // at least for now, unless we want to add new compartment creation here.
   // Use CModelExpansion for duplication
   CModelExpansion cModelExpObj = CModelExpansion(pModel);
   CModelExpansion::SetOfModelElements sourceObjects;
   CModelExpansion::ElementsMap origToCopyMapping;
   // for comboBox compartment list and setting compartment
   CCopasiVectorNS< CCompartment > & Compartments = pModel->getCompartments();
   CCopasiVectorN< CCompartment >::const_iterator Compartment_it = Compartments.begin();
   CCopasiVectorN< CCompartment >::const_iterator end = Compartments.end();
   QStringList SelectionList;
   // Collect and load list of compartment names in comboBox
   for (; Compartment_it != end; ++Compartment_it)
     {
       SelectionList.append(FROM_UTF8((*Compartment_it)->getObjectName()));
     }
   pDialog->setSelectionList(SelectionList);
   const CCompartment * origCompartment = NULL;
   // to use here, and for testing if compartment changed after executing the dialog
   int origCompartmentIndex;
   CCopasiVector< CChemEqElement >::const_iterator MetabIt;
   const CCopasiVector< CChemEqElement > & substratesToCopy = reac->getChemEq().getSubstrates();
   for (MetabIt = substratesToCopy.begin(); MetabIt != substratesToCopy.end(); MetabIt++)
     {
       pDialog->setWindowTitle("Create copy of " + FROM_UTF8((*MetabIt)->getMetabolite()->getObjectName()) + "?");
       origCompartment = (*MetabIt)->getMetabolite()->getCompartment();
       origCompartmentIndex = pDialog->mpSelectionBox->findText(FROM_UTF8(origCompartment->getObjectName()));
       pDialog->mpSelectionBox->setCurrentIndex(origCompartmentIndex);
       Compartment_it = Compartments.begin(); // Reuse Compartments iterator to set compartment choice
       if (pDialog->exec() != QDialog::Rejected)
         {
           // Put species in different compartment (without name modification) by making
           // duplicateMetab think the other compartment was duplicated from the original
           if (origCompartmentIndex != pDialog->mpSelectionBox->currentIndex())
             {
               sourceObjects.addCompartment(origCompartment);
               origToCopyMapping.add(origCompartment, *(Compartment_it + pDialog->mpSelectionBox->currentIndex()));
             }
           sourceObjects.addMetab((*MetabIt)->getMetabolite());
           cModelExpObj.duplicateMetab((*MetabIt)->getMetabolite(), "_copy", sourceObjects, origToCopyMapping);
         }
     }
   const CCopasiVector< CChemEqElement > & productsToCopy = reac->getChemEq().getProducts();
   for (MetabIt = productsToCopy.begin(); MetabIt != productsToCopy.end(); MetabIt++)
     {
       pDialog->setWindowTitle("Create copy of " + FROM_UTF8((*MetabIt)->getMetabolite()->getObjectName()) + "?");
       origCompartment = (*MetabIt)->getMetabolite()->getCompartment();
       origCompartmentIndex = pDialog->mpSelectionBox->findText(FROM_UTF8(origCompartment->getObjectName()));
       pDialog->mpSelectionBox->setCurrentIndex(origCompartmentIndex);
       Compartment_it = Compartments.begin();
       if (pDialog->exec() != QDialog::Rejected)
         {
           if (origCompartmentIndex != pDialog->mpSelectionBox->currentIndex())
             {
               sourceObjects.addCompartment(origCompartment);
               origToCopyMapping.add(origCompartment, *(Compartment_it + pDialog->mpSelectionBox->currentIndex()));
             }
           sourceObjects.addMetab((*MetabIt)->getMetabolite());
           cModelExpObj.duplicateMetab((*MetabIt)->getMetabolite(), "_copy", sourceObjects, origToCopyMapping);
         }
     }
   const CCopasiVector< CChemEqElement > & modifiersToCopy = reac->getChemEq().getModifiers();
   for (MetabIt = modifiersToCopy.begin(); MetabIt != modifiersToCopy.end(); MetabIt++)
     {
       pDialog->setWindowTitle("Create copy of " + FROM_UTF8((*MetabIt)->getMetabolite()->getObjectName()) + "?");
       origCompartment = (*MetabIt)->getMetabolite()->getCompartment();
       origCompartmentIndex = pDialog->mpSelectionBox->findText(FROM_UTF8(origCompartment->getObjectName()));
       pDialog->mpSelectionBox->setCurrentIndex(origCompartmentIndex);
       Compartment_it = Compartments.begin();
       if (pDialog->exec() != QDialog::Rejected)
         {
           if (origCompartmentIndex != pDialog->mpSelectionBox->currentIndex())
             {
               sourceObjects.addCompartment(origCompartment);
               origToCopyMapping.add(origCompartment, *(Compartment_it + pDialog->mpSelectionBox->currentIndex()));
             }
           sourceObjects.addMetab((*MetabIt)->getMetabolite());
           cModelExpObj.duplicateMetab((*MetabIt)->getMetabolite(), "_copy", sourceObjects, origToCopyMapping);
         }
     }
   sourceObjects.addReaction(reac);
   cModelExpObj.duplicateReaction(reac, "_copy", sourceObjects, origToCopyMapping);
   protectedNotify(ListViews::COMPARTMENT, ListViews::DELETE, "");//Refresh all
   protectedNotify(ListViews::METABOLITE, ListViews::DELETE, ""); //Refresh all
   protectedNotify(ListViews::REACTION, ListViews::DELETE, "");   //Refresh all
   mpListView->switchToOtherWidget(C_INVALID_INDEX, origToCopyMapping.getDuplicateKey(mKey));
   pdelete(pDialog);
 }
bool ReactionsWidget1::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 624 of file ReactionsWidget1.cpp.
References loadFromReaction(), CopasiWidget::mpListView, CopasiWidget::mpObject, and ListViews::switchToOtherWidget().
Referenced by slotTableChanged().
 {
   CReaction* reac = dynamic_cast< CReaction * >(mpObject);
   if (reac)
     return loadFromReaction(reac);
   mpListView->switchToOtherWidget(114, "");
   return false;
 }
void ReactionsWidget1::FillWidgetFromRI () protected
Definition at line 449 of file ReactionsWidget1.cpp.
References FROM_UTF8, CReactionInterface::getChemEqString(), CCopasiRootContainer::getDatamodelList(), CReactionInterface::getFunctionDescription(), CReactionInterface::getFunctionName(), CReactionInterface::getListOfPossibleFunctions(), CReactionInterface::isMulticompartment(), CReactionInterface::isReversible(), CopasiWidget::mFramework, CopasiWidget::mpObject, mpRi, setFramework(), and vectorOfStrings2QStringList().
Referenced by loadFromReaction(), slotCheckBoxClicked(), slotComboBoxSelectionChanged(), and slotLineEditChanged().
 {
   LineEdit2->setText(FROM_UTF8(mpRi->getChemEqString()));
   setFramework(mFramework);
   // the reversibility checkbox
   CheckBox->setChecked(false);
   if (mpRi->isReversible() == true)
     {
       CheckBox->setChecked(true);
     }
   mpMultiCompartment->setChecked(mpRi->isMulticompartment());
   // the function combobox
   QStringList comboEntries;
   vectorOfStrings2QStringList(mpRi->getListOfPossibleFunctions(), comboEntries);
   ComboBox1->clear();
   ComboBox1->insertItems(0, comboEntries);
   // if there is a current function the parameter table is initialized
   if (mpRi->getFunctionName() != "")
     {
       if (comboEntries.filter(FROM_UTF8(mpRi->getFunctionName())).size() == 0)
         ComboBox1->insertItem(0, FROM_UTF8(mpRi->getFunctionName()));
       ComboBox1->setCurrentIndex(ComboBox1->findText(FROM_UTF8(mpRi->getFunctionName())));
       ComboBox1->setToolTip(FROM_UTF8(mpRi->getFunctionDescription()));
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       table->updateTable(*mpRi, dynamic_cast< CReaction * >(mpObject));
     }
   else
     {
       ComboBox1->insertItem(0, "undefined");
       ComboBox1->setCurrentIndex(0);
       table->initTable();
     }
 }
bool ReactionsWidget1::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 617 of file ReactionsWidget1.cpp.
References saveToReaction().
Referenced by slotTableChanged().
 {
   saveToReaction();
   return true; //always return true. That means that the widget can be
   //left without saving
 }
bool ReactionsWidget1::loadFromReaction (const CReaction * reaction) protected
Definition at line 78 of file ReactionsWidget1.cpp.
References FillWidgetFromRI(), CCopasiRootContainer::getDatamodelList(), CReaction::getKey(), CReactionInterface::initFromReaction(), CReaction::isFast(), CopasiWidget::mpObject, mpRi, and pdelete.
Referenced by enterProtected(), and update().
 {
   if (!reaction) return false;
   // this function is also called via notify, when the control has
   // not been entered, thus we need to ensure we are pointing to the
   // right object
   mpObject = const_cast<CReaction*>(reaction);
   // this loads the reaction into a CReactionInterface object.
   // the gui works on this object and later writes back the changes to the reaction
   pdelete(mpRi);
   mpRi = new CReactionInterface((*CCopasiRootContainer::getDatamodelList())[0]->getModel());
   mpRi->initFromReaction(reaction->getKey());
   // update the widget.
   FillWidgetFromRI();
   mpFast->setChecked(reaction->isFast());
   return true; //TODO: really check
 }
bool ReactionsWidget1::saveToReaction () protected
Definition at line 102 of file ReactionsWidget1.cpp.
References ListViews::ADD, ListViews::CHANGE, CQMessageBox::confirmDelete(), CReactionInterface::createMetabolites(), CReactionInterface::createOtherObjects(), ListViews::DELETE, FROM_UTF8, CKeyFactory::get(), CCopasiRootContainer::getDatamodelList(), CReactionInterface::getDeletedParameters(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CReaction::isFast(), CReactionInterface::isValid(), ListViews::METABOLITE, CopasiWidget::mKey, ListViews::MODEL, mpRi, CopasiWidget::protectedNotify(), ListViews::REACTION, CModel::removeLocalReactionParameter(), CReaction::setFast(), CReactionInterface::setFunctionWithEmptyMapping(), and CReactionInterface::writeBackToReaction().
Referenced by leave().
 {
   CReaction* reac = dynamic_cast< CReaction * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (reac == NULL) return true;
   if (!LineEdit2->isValid()) return false;
   LineEdit2->slotForceUpdate();
   if (!mpRi->isValid()) return false;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL) return false;
   if (reac->isFast() != mpFast->isChecked())
     {
       reac->setFast(mpFast->isChecked());
     }
   // Before we save any changes we must check whether any local reaction parameters,
   // which are used in any mathematical expression in the model are removed.
   // If that is the case the user must have option to cancel the changes or remove the
   // affected expressions.
   std::set< const CCopasiObject * > DeletedParameters = mpRi->getDeletedParameters();
   if (DeletedParameters.size() != 0)
     {
       QString ObjectType = "parameter(s)";
       QString Objects;
       std::set< const CCopasiObject * >::const_iterator itParameter, endParameter = DeletedParameters.end();
       std::set< const CCopasiObject * > DeletedObjects;
       for (itParameter = DeletedParameters.begin(); itParameter != endParameter; ++itParameter) //all parameters
         {
           Objects.append(FROM_UTF8((*itParameter)->getObjectName()) + ", ");
           DeletedObjects.insert(static_cast< const CCopasiObject * >((*itParameter)->getObject(CCopasiObjectName("Reference=Value"))));
         }
       Objects.remove(Objects.length() - 2, 2);
       QMessageBox::StandardButton choice =
         CQMessageBox::confirmDelete(NULL, ObjectType,
                                     Objects, DeletedObjects);
       switch (choice)
         {
           case QMessageBox::Ok:
             for (itParameter = DeletedParameters.begin(); itParameter != endParameter; ++itParameter) //all parameters
               pModel->removeLocalReactionParameter((*itParameter)->getKey());
             protectedNotify(ListViews::REACTION, ListViews::DELETE, "");
             break;
           default:
             return true;
             break;
         }
     }
   // We need to check whether the current reaction still exists, since it is possible that
   // removing a local reaction parameter triggers its deletion.
   reac = dynamic_cast< CReaction * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (reac == NULL)
     {
       mpRi->setFunctionWithEmptyMapping("");
       protectedNotify(ListViews::REACTION, ListViews::DELETE, mKey);
       protectedNotify(ListViews::REACTION, ListViews::DELETE, ""); //Refresh all as there may be dependencies.
       return true;
     }
   //first check if new metabolites need to be created
   bool createdMetabs = mpRi->createMetabolites();
   bool createdObjects = mpRi->createOtherObjects();
   //this writes all changes to the reaction
   mpRi->writeBackToReaction(reac);
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   //(*CCopasiRootContainer::getDatamodelList())[0]->getModel()->compile();
   //this tells the gui what it needs to know.
   if (createdObjects)
     protectedNotify(ListViews::MODEL, ListViews::CHANGE, "");
   else
     {
       if (createdMetabs) protectedNotify(ListViews::METABOLITE, ListViews::ADD, "");
       // :TODO Bug 322: This should only be called when actual changes have been saved.
       if (!this->isHidden())
         protectedNotify(ListViews::REACTION, ListViews::CHANGE, mKey);
     }
   //TODO: detect rename events (mpRi->writeBackToReaction has to do this)
   // :TODO Bug 322: This should only be called when actual changes have been saved.
   if (!this->isHidden())
     (*CCopasiRootContainer::getDatamodelList())[0]->changed();
   return true;
 }
void ReactionsWidget1::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 635 of file ReactionsWidget1.cpp.
References FROM_UTF8, CKeyFactory::get(), CReaction::getFlux(), CModel::getFrequencyUnitsDisplayString(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectAncestor(), CReaction::getParticleFlux(), CModel::getQuantityRateUnitsDisplayString(), CopasiWidget::mFramework, CopasiWidget::mKey, and CopasiWidget::setFramework().
Referenced by FillWidgetFromRI().
 {
   CopasiWidget::setFramework(framework);
   const CReaction * pReaction = dynamic_cast< CReaction * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   const CModel * pModel = NULL;
   if (pReaction != NULL)
     pModel = dynamic_cast<const CModel *>(pReaction->getObjectAncestor("Model"));
   QString Units;
   switch (mFramework)
     {
       case 0:
         if (pModel)
           Units = FROM_UTF8(pModel->getQuantityRateUnitsDisplayString());
         if (!Units.isEmpty())
           Units = " (" + Units + ")";
         TextLabel8->setText("Flux" + Units);
         if (pReaction != NULL)
           LineEdit3->setText(QString::number(pReaction->getFlux(), 'g', 10));
         break;
       case 1:
         if (pModel)
           Units = FROM_UTF8(pModel->getFrequencyUnitsDisplayString());
         if (!Units.isEmpty())
           Units = " (" + Units + ")";
         TextLabel8->setText("Particle Flux" + Units);
         if (pReaction != NULL)
           LineEdit3->setText(QString::number(pReaction->getParticleFlux(), 'g', 10));
         break;
     }
 }
virtual void ReactionsWidget1::slotBtnCopy () inline protected virtual slot
Definition at line 50 of file ReactionsWidget1.h.
 {}; //dummy, to bypass warnings from TabWidget connections
void ReactionsWidget1::slotBtnDelete () protected virtual slot
Definition at line 411 of file ReactionsWidget1.cpp.
References CQMessageBox::confirmDelete(), ListViews::DELETE, FROM_UTF8, CKeyFactory::get(), CCopasiRootContainer::getDatamodelList(), CReaction::getDeletedObjects(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CopasiWidget::mKey, mpRi, CopasiWidget::protectedNotify(), ListViews::REACTION, CModel::removeReaction(), and CReactionInterface::setFunctionWithEmptyMapping().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return;
   CReaction * pReaction =
     dynamic_cast< CReaction * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (pReaction == NULL) return;
   QMessageBox::StandardButton choice =
     CQMessageBox::confirmDelete(NULL, "reaction",
                                 FROM_UTF8(pReaction->getObjectName()),
                                 pReaction->getDeletedObjects());
   switch (choice)
     {
       case QMessageBox::Ok:                                                     // Yes or Enter
       {
         pDataModel->getModel()->removeReaction(mKey);
         mpRi->setFunctionWithEmptyMapping("");
         protectedNotify(ListViews::REACTION, ListViews::DELETE, mKey);
         protectedNotify(ListViews::REACTION, ListViews::DELETE, "");//Refresh all as there may be dependencies.
         break;
       }
       default:                                                     // No or Escape
         break;
     }
 }
void ReactionsWidget1::slotBtnNew () protected virtual slot
Definition at line 257 of file ReactionsWidget1.cpp.
References ListViews::ADD, C_INVALID_INDEX, CModel::createReaction(), CCopasiRootContainer::getDatamodelList(), CCopasiObject::getKey(), CCopasiDataModel::getModel(), CModel::getReactions(), CopasiWidget::mpListView, CopasiWidget::protectedNotify(), ListViews::REACTION, ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   std::string name = "reaction_1";
   size_t i = 1;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   while (!pDataModel->getModel()->createReaction(name))
     {
       i++;
       name = "reaction_";
       name += TO_UTF8(QString::number(i));
     }
   std::string key = pDataModel->getModel()->getReactions()[name]->getKey();
   protectedNotify(ListViews::REACTION, ListViews::ADD, key);
 //  enter(key);
   mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void ReactionsWidget1::slotCheckBoxClicked () protected virtual slot
Definition at line 213 of file ReactionsWidget1.cpp.
References FillWidgetFromRI(), mpRi, and CReactionInterface::setReversibility().
 {
   LineEdit2->slotForceUpdate();
   // tell the reaction interface
   mpRi->setReversibility(CheckBox->isChecked(), "");
   // update the widget
   FillWidgetFromRI();
 }
void ReactionsWidget1::slotComboBoxSelectionChanged (const QString & p2) protected virtual slot
Definition at line 225 of file ReactionsWidget1.cpp.
References FillWidgetFromRI(), mpRi, CReactionInterface::setFunctionAndDoMapping(), and TO_UTF8.
 {
   // tell the reaction interface
   mpRi->setFunctionAndDoMapping(TO_UTF8(p2));
   // update the widget
   FillWidgetFromRI();
 }
void ReactionsWidget1::slotGotoFunction () protected virtual slot
Definition at line 556 of file ReactionsWidget1.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CReaction::getFunction(), CFunction::getKey(), CCopasiRootContainer::getKeyFactory(), CopasiWidget::mKey, CopasiWidget::mpListView, and ListViews::switchToOtherWidget().
 {
   CReaction * pReaction =
     dynamic_cast< CReaction * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (pReaction == NULL) return;
   const CFunction * pFunc = pReaction->getFunction();
   if (pFunc == NULL) return;
   mpListView->switchToOtherWidget(C_INVALID_INDEX, pFunc->getKey());
 }
void ReactionsWidget1::slotLineEditChanged () protected virtual slot
Definition at line 235 of file ReactionsWidget1.cpp.
References FillWidgetFromRI(), CChemEqInterface::isValidEq(), mpRi, CReactionInterface::setChemEqString(), and TO_UTF8.
 {
   //std::string rName = TO_UTF8(LineEdit1->text());
   std::string eq = TO_UTF8(LineEdit2->text());
   //first check if the string is a valid equation
   if (!CChemEqInterface::isValidEq(eq))
     {
       return;  // abort further processing
     }
   // tell the reaction interface
   //mpRi->setReactionName(rName);
   mpRi->setChemEqString(eq, "");
   // update the widget
   FillWidgetFromRI();
 }
void ReactionsWidget1::slotNewFunction () protected virtual slot
Definition at line 570 of file ReactionsWidget1.cpp.
References CFunctionDB::add(), ListViews::ADD, C_INVALID_INDEX, ListViews::FUNCTION, CCopasiRootContainer::getFunctionList(), CCopasiVectorN< CType >::getIndex(), CFunction::getKey(), CCopasiObject::getObjectName(), CFunctionDB::loadedFunctions(), CopasiWidget::mpListView, CopasiWidget::mpObject, CopasiWidget::protectedNotify(), ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   // FunctionWidget1 * fw = new FunctionWidget1(NULL);
   // fw->show();
   // TODO: we could think about calling the function widget as a dialogue here...
   std::string name = std::string("Rate Law for ") + mpObject->getObjectName();
   std::string nname = name;
   size_t i = 0;
   CCopasiVectorN<CFunction>& FunctionList
   = CCopasiRootContainer::getFunctionList()->loadedFunctions();
   CFunction* pFunc;
   while (FunctionList.getIndex(nname) != C_INVALID_INDEX)
     {
       i++;
       nname = name + "_";
       nname += TO_UTF8(QString::number(i));
     }
   CCopasiRootContainer::getFunctionList()->add(pFunc = new CKinFunction(nname), true);
   protectedNotify(ListViews::FUNCTION, ListViews::ADD, pFunc->getKey());
   mpListView->switchToOtherWidget(C_INVALID_INDEX, pFunc->getKey());
 }
void ReactionsWidget1::slotParameterStatusChanged (int index, bool local) protected virtual slot
Definition at line 545 of file ReactionsWidget1.cpp.
References mpRi, CReactionInterface::setLocal(), and CReactionInterface::setMapping().
 {
   // slot is a reminant of when a checkbox handled this.
   // This could be added in to slotTableChanged
   if (local)
     mpRi->setLocal(index);
   else
     mpRi->setMapping(index, "unknown"); //TODO keep global parameter
 }
void ReactionsWidget1::slotTableChanged (int index, int sub, QString newValue) protected virtual slot
Definition at line 492 of file ReactionsWidget1.cpp.
References enterProtected(), CReactionInterface::getUsage(), CReactionInterface::isLocalValue(), CReactionInterface::isValid(), leave(), mpRi, CFunctionParameter::PARAMETER, CReactionInterface::setLocalValue(), CReactionInterface::setMapping(), TO_UTF8, and CFunctionParameter::VOLUME.
 {
   size_t Index = index;
   bool SkipFillWidget = false;
   // setValue
   if (mpRi->getUsage(Index) == CFunctionParameter::PARAMETER)
     {
       if (sub != 0) return;
       if (mpRi->isLocalValue(Index))
         {
           mpRi->setLocalValue(Index, newValue.toDouble()); // TODO: check
           SkipFillWidget = true;
         }
       else
         mpRi->setMapping(Index, TO_UTF8(newValue));
     }
   else if (mpRi->getUsage(Index) == CFunctionParameter::VOLUME)
     {
       if (sub != 0) return;
       mpRi->setMapping(Index, TO_UTF8(newValue));
     }
   else
     {
       if (sub == 0) //here we assume that vector parameters cannot be edited
         {
 //          mpRi->setMapping((int) Index, TO_UTF8(table->item((int) table->mIndex2Line[index], 3)->text()));
           mpRi->setMapping((int) Index, TO_UTF8(newValue));
         }
     }
   // if we don't stop here, we loose changes!
   // instead just prevent updating, that way the user has a chance to correct the reaction,
   // only if the user selects another reaction (or somehow else leaves the editing,
   // the changes will be lost)
   //
   if (!mpRi->isValid())
     return;
   // update the widget
   int rrr = table->currentRow();
   int ccc = table->currentColumn();
   table->setCurrentCell(rrr, ccc);
   // Save changes when leaving cell
   leave();
   // Will ultimately update mpRi for updateTable and FillWidgetFromRI
   enterProtected();
 }
bool ReactionsWidget1::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 596 of file ReactionsWidget1.cpp.
References ListViews::COMPARTMENT, CCopasiRootContainer::getKeyFactory(), loadFromReaction(), ListViews::METABOLITE, CopasiWidget::mIgnoreUpdates, CopasiWidget::mKey, ListViews::MODEL, and ListViews::STATE.
 {
   if (mIgnoreUpdates) return true;
   switch (objectType)
     {
       case ListViews::MODEL:
       case ListViews::STATE:
       case ListViews::COMPARTMENT:
       case ListViews::METABOLITE:
         return loadFromReaction(dynamic_cast< CReaction * >(CCopasiRootContainer::getKeyFactory()->get(mKey)));
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
CReactionInterface* ReactionsWidget1::mpRi protected
Definition at line 68 of file ReactionsWidget1.h.
Referenced by FillWidgetFromRI(), loadFromReaction(), saveToReaction(), slotBtnDelete(), slotCheckBoxClicked(), slotComboBoxSelectionChanged(), slotLineEditChanged(), slotParameterStatusChanged(), slotTableChanged(), and ~ReactionsWidget1().
The documentation for this class was generated from the following files:
ReactionsWidget1.h
ReactionsWidget1.cpp