COPASI API: CQTimeSeriesWidget Class Reference
CQTimeSeriesWidget Class Reference
#include <CQTimeSeriesWidget.h>
Public Member Functions
CQTimeSeriesWidget (QWidget *parent=0)
virtual bool leave ()
virtual bool loadResult (const CCopasiTask *pTask)
virtual void setFramework (int framework)
virtual void setTitle (const QString &title)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQTimeSeriesWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotSave ()
Private Attributes
CQTimeSeriesDM * mpDataModel
const CTimeSeries * mpTimeSeries
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 18 of file CQTimeSeriesWidget.h.
Constructor & Destructor Documentation
CQTimeSeriesWidget::CQTimeSeriesWidget (QWidget * parent = 0)
Definition at line 15 of file CQTimeSeriesWidget.cpp.
References mpDataModel.
                                                      :
   CopasiWidget(parent),
   mpTimeSeries(NULL),
   mpDataModel(NULL)
 {
   setupUi(this);
   mpDataModel = new CQTimeSeriesDM(this);
   mpTableView->setModel(mpDataModel);
 }
CQTimeSeriesWidget::~CQTimeSeriesWidget () virtual
Definition at line 26 of file CQTimeSeriesWidget.cpp.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
bool CQTimeSeriesWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 117 of file CQTimeSeriesWidget.cpp.
 {
   return true;
 }
bool CQTimeSeriesWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 62 of file CQTimeSeriesWidget.cpp.
 {
   return true;
 }
bool CQTimeSeriesWidget::loadResult (const CCopasiTask * pTask) virtual
Definition at line 88 of file CQTimeSeriesWidget.cpp.
References getTimeSeriesFromTask(), mpDataModel, mpTimeSeries, CQTimeSeriesDM::rowCount(), and CQTimeSeriesDM::setTimeSeries().
Referenced by CQCrossSectionTaskWidget::taskFinishedEvent(), CQTrajectoryWidget::taskFinishedEvent(), and update().
 {
   mpTimeSeries = getTimeSeriesFromTask(pTask);
   mpDataModel->setTimeSeries(mpTimeSeries);
   // mpTableView->resizeRowsToContents(); This is to slow
   int RowCount = mpDataModel->rowCount();
   if (RowCount > 0)
     {
       mpTableView->resizeRowToContents(0);
       int RowHeight = mpTableView->rowHeight(0);
       mpTableView->verticalHeader()->setDefaultSectionSize(RowHeight);
     }
   // mpTableView->resizeColumnsToContents(); This is to slow
   return true;
 }
void CQTimeSeriesWidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 110 of file CQTimeSeriesWidget.cpp.
References mpDataModel, CQTimeSeriesDM::setFramework(), and CopasiWidget::setFramework().
 {
   CopasiWidget::setFramework(framework);
   mpDataModel->setFramework(framework);
 }
void CQTimeSeriesWidget::setTitle (const QString & title) virtual
Definition at line 67 of file CQTimeSeriesWidget.cpp.
Referenced by CQCrossSectionTaskWidget::init().
 {
   mpLblResult->setText(title);
 }
void CQTimeSeriesWidget::slotSave (void) private slot
Definition at line 122 of file CQTimeSeriesWidget.cpp.
References C_INT32, checkSelection(), CQMessageBox::critical(), FROM_UTF8, CopasiFileDialog::getSaveFileName(), CopasiWidget::mFramework, mpTimeSeries, CTimeSeries::save(), and TO_UTF8.
 {
   if (mpTimeSeries == NULL) return;
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   int failed = 0;
   QCursor oldCursor = cursor();
   setCursor(Qt::WaitCursor);
   failed = mpTimeSeries->save(TO_UTF8(fileName), (mFramework == 1), "\t");
   setCursor(oldCursor);
   if (failed)
     {
       std::string s = "Could not save data to ";
       s += TO_UTF8(fileName);
       CQMessageBox::critical(this, "Save Error", FROM_UTF8(s), QMessageBox::Ok, QMessageBox::Cancel);
     }
 }
bool CQTimeSeriesWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 32 of file CQTimeSeriesWidget.cpp.
References ListViews::ADD, ListViews::DELETE, loadResult(), and ListViews::MODEL.
 {
   // We need to update the task when a new model is loaded.
   switch (objectType)
     {
       case ListViews::MODEL:
         switch (action)
           {
             case ListViews::ADD:
             case ListViews::DELETE:
               loadResult(NULL);
               break;
             default:
               break;
           }
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
CQTimeSeriesDM* CQTimeSeriesWidget::mpDataModel private
Definition at line 47 of file CQTimeSeriesWidget.h.
Referenced by CQTimeSeriesWidget(), loadResult(), and setFramework().
const CTimeSeries* CQTimeSeriesWidget::mpTimeSeries private
Definition at line 46 of file CQTimeSeriesWidget.h.
Referenced by loadResult(), and slotSave().
The documentation for this class was generated from the following files:
CQTimeSeriesWidget.h
CQTimeSeriesWidget.cpp