COPASI API: CLTextGlyph Class Reference
CLTextGlyph Class Reference
#include <CLGlyphs.h>
Public Member Functions
void clearText ()
virtual CLGraphicalObject * clone () const
CLTextGlyph (const std::string &name="TextGlyph", const CCopasiContainer *pParent=NULL)
CLTextGlyph (const CLTextGlyph &src, const CCopasiContainer *pParent=NULL)
CLTextGlyph (const TextGlyph &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
void exportReferenceToSBML (TextGlyph *g, const std::map< const CLBase *, const SBase * > &layoutmap) const
virtual void exportToSBML (TextGlyph *g, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
CLGraphicalObject * getGraphicalObject () const
const std::string & getGraphicalObjectKey () const
virtual std::string getText () const
bool isTextSet () const
CLTextGlyph & operator= (const CLTextGlyph &rhs)
void print (std::ostream *ostream) const
void setGraphicalObjectKey (const std::string &k)
void setText (const std::string &t)
Public Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const std::string &name="GraphicalObject", const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const CLGraphicalObject &src, const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
const CLBoundingBox & getBoundingBox () const
CLBoundingBox & getBoundingBox ()
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CCopasiObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
virtual void moveBy (const CLPoint &p)
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void print (std::ostream *ostream) const
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
std::string mGraphicalObjectKey
bool mIsTextSet
std::string mText
Protected Attributes inherited from CLGraphicalObject
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Friends
std::ostream & operator<< (std::ostream &os, const CLTextGlyph &g)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Graphical representation of a Label
Definition at line 118 of file CLGlyphs.h.
Constructor & Destructor Documentation
CLTextGlyph::CLTextGlyph (const std::string & name = "TextGlyph", const CCopasiContainer * pParent = NULL)
Definition at line 180 of file CLGlyphs.cpp.
Referenced by clone().
     : CLGraphicalObject(name, pParent),
     mIsTextSet(false),
     mText(""),
     mGraphicalObjectKey("")
 {}
CLTextGlyph::CLTextGlyph (const CLTextGlyph & src, const CCopasiContainer * pParent = NULL)
Definition at line 188 of file CLGlyphs.cpp.
     : CLGraphicalObject(src, pParent),
     mIsTextSet(src.mIsTextSet),
     mText(src.mText),
     mGraphicalObjectKey(src.mGraphicalObjectKey)
 {}
CLTextGlyph::CLTextGlyph (const TextGlyph & sbml, const std::map< std::string, std::string > & modelmap, std::map< std::string, std::string > & layoutmap, const CCopasiContainer * pParent = NULL)
constructor from libsbml object
Definition at line 196 of file CLGlyphs.cpp.
References CLGraphicalObject::setModelObjectKey().
     : CLGraphicalObject(sbml, layoutmap, pParent),
     mIsTextSet(sbml.isSetText()),
     mText(sbml.getText()),
     mGraphicalObjectKey("")
 {
   //get the copasi key corresponding to the sbml id for the graphical object
   /*  if (sbml.getGraphicalObjectId() != "")
       {
         std::map<std::string, std::string>::const_iterator it = m.find(sbml.getGraphicalObjectId());
         if (it != m.end())
           mGraphicalObjectKey = it->second;
       }*/
   //get the copasi key corresponding to the sbml id for the model element (OriginOfText)
   if (sbml.getOriginOfTextId() != "")
     {
       std::map<std::string, std::string>::const_iterator it = modelmap.find(sbml.getOriginOfTextId());
       if (it != modelmap.end())
         setModelObjectKey(it->second);
     }
 }
Member Function Documentation
void CLTextGlyph::clearText ()
Definition at line 256 of file CLGlyphs.cpp.
References mIsTextSet, and mText.
 {
   mIsTextSet = false;
   mText = "";
 }
virtual CLGraphicalObject* CLTextGlyph::clone () const inline virtual
Reimplemented from CLGraphicalObject.
Definition at line 167 of file CLGlyphs.h.
References CLTextGlyph().
 {return new CLTextGlyph(*this, NULL);};
void CLTextGlyph::exportReferenceToSBML (TextGlyph * g, const std::map< const CLBase *, const SBase * > & layoutmap) const
handle the reference to another graphical object for sbml export. This should only be called after all other graphical objects are in the layout map.
Definition at line 297 of file CLGlyphs.cpp.
References getGraphicalObject().
Referenced by CLayout::exportToSBML().
 {
   if (!g) return;
   //reference to layout object
   CLGraphicalObject* tmp = getGraphicalObject();
   if (tmp)
     {
       std::map<const CLBase*, const SBase*>::const_iterator it = layoutmap.find(tmp);
       if (it != layoutmap.end() && it->second)
         {
           //we need to cast here since layout objects in libsbml dont inherit the getId() method
           //from SBase
           const GraphicalObject* pGO = dynamic_cast<const GraphicalObject*>(it->second);
           if (pGO)
             g->setGraphicalObjectId(pGO->getId());
         }
     }
 }
void CLTextGlyph::exportToSBML (TextGlyph * g, const std::map< const CCopasiObject *, SBase * > & copasimodelmap, std::map< std::string, const SBase * > & sbmlIDs) const virtual
This method writes the information of the copasi layout object into the corresponding sbml object. The reference to other graphical objects cannot be done in this method since when this method is called not necessarily all other graphical objects have been created.
Definition at line 267 of file CLGlyphs.cpp.
References CLGraphicalObject::exportToSBML(), CLGraphicalObject::getModelObject(), isTextSet(), and mText.
Referenced by CLayout::exportToSBML(), and CLGeneralGlyph::exportToSBML().
 {
   if (!g) return;
   //call the coresponding method of the base class
   CLGraphicalObject::exportToSBML(g, copasimodelmap, sbmlIDs);
   //reference to model objects
   CCopasiObject* tmp = getModelObject();
   if (tmp)
     {
       std::map<const CCopasiObject*, SBase*>::const_iterator it = copasimodelmap.find(tmp);
       if (it != copasimodelmap.end())
         {
           if (it->second)
             g->setOriginOfTextId(it->second->getId());
         }
     }
   //explicit text
   if (isTextSet())
     {
       g->setText(mText);
     }
 }
CLGraphicalObject * CLTextGlyph::getGraphicalObject () const
Definition at line 262 of file CLGlyphs.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), and mGraphicalObjectKey.
Referenced by exportReferenceToSBML(), operator<<(), and placeTextGlyphs().
 {
   return dynamic_cast<CLGraphicalObject*>(CCopasiRootContainer::getKeyFactory()->get(mGraphicalObjectKey));
 }
const std::string& CLTextGlyph::getGraphicalObjectKey () const inline
Definition at line 163 of file CLGlyphs.h.
References mGraphicalObjectKey.
Referenced by CLayout::CLayout(), CCopasiXML::saveLayoutList(), and CLLayoutRenderer::update_associations().
 {return mGraphicalObjectKey;};
std::string CLTextGlyph::getText () const virtual
Reimplemented in CLabel.
Definition at line 238 of file CLGlyphs.cpp.
References CLGraphicalObject::getModelObjectDisplayName(), mIsTextSet, and mText.
Referenced by CLLayoutRenderer::resolve_text(), and CCopasiXML::saveLayoutList().
 {
   if (mIsTextSet)
     {
       return mText;
     }
   else
     {
       return getModelObjectDisplayName();
     }
 }
bool CLTextGlyph::isTextSet () const inline
Definition at line 161 of file CLGlyphs.h.
References mIsTextSet.
Referenced by exportToSBML(), CLLayoutRenderer::resolve_text(), and CCopasiXML::saveLayoutList().
 {return mIsTextSet;};
CLTextGlyph & CLTextGlyph::operator= (const CLTextGlyph & rhs)
assignment operator.
Definition at line 223 of file CLGlyphs.cpp.
References mGraphicalObjectKey, mIsTextSet, mText, and CLGraphicalObject::operator=().
 {
   if (this == &rhs) return * this; //do nothing if lhs and rhs are the same
   CLGraphicalObject::operator=(rhs);
   //handle the specific text glyph stuff:
   mIsTextSet = rhs.mIsTextSet;
   mText = rhs.mText;
   mGraphicalObjectKey = rhs.mGraphicalObjectKey;
   return *this;
 }
void CLTextGlyph::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 335 of file CLGlyphs.cpp.
 {*ostream << *this;}
void CLTextGlyph::setGraphicalObjectKey (const std::string & k)
Definition at line 338 of file CLGlyphs.cpp.
References mGraphicalObjectKey.
Referenced by CLayout::CLayout(), CCopasiSpringLayout::createLayout(), SBMLDocumentLoader::postprocessTextGlyph(), and CCopasiXMLParser::TextGlyphElement::start().
 {
   mGraphicalObjectKey = k;
 }
void CLTextGlyph::setText (const std::string & t)
Definition at line 250 of file CLGlyphs.cpp.
References mIsTextSet, and mText.
Referenced by CCopasiXML::saveLayoutList(), and CCopasiXMLParser::TextGlyphElement::start().
 {
   mIsTextSet = true;
   mText = t;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLTextGlyph & g) friend
insert operator
Definition at line 320 of file CLGlyphs.cpp.
 {
   os << "TextGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   if (g.mIsTextSet)
     os << "  Explicit text is: \"" << g.mText << "\"\n";
   CLGraphicalObject* tmp = g.getGraphicalObject();
   if (tmp)
     os << "  Label for: \"" << tmp->getObjectName() << "\"\n";
   return os;
 }
Member Data Documentation
std::string CLTextGlyph::mGraphicalObjectKey protected
Key of a layout element. If this is set the text glyph is considered to be a label to this layout element.
Definition at line 133 of file CLGlyphs.h.
Referenced by getGraphicalObject(), getGraphicalObjectKey(), operator=(), and setGraphicalObjectKey().
bool CLTextGlyph::mIsTextSet protected
indicates if a text is set. If the text is not set the label text is taken from the model object.
Definition at line 126 of file CLGlyphs.h.
Referenced by clearText(), CLabel::getText(), getText(), isTextSet(), operator<<(), operator=(), and setText().
std::string CLTextGlyph::mText protected
Definition at line 127 of file CLGlyphs.h.
Referenced by clearText(), exportToSBML(), CLabel::getText(), getText(), operator<<(), operator=(), and setText().
The documentation for this class was generated from the following files:
CLGlyphs.h
CLGlyphs.cpp