COPASI API: CQParameterSetsDM Class Reference
CQParameterSetsDM Class Reference
#include <CQParameterSetsDM.h>
Public Member Functions
virtual bool clear ()
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQParameterSetsDM (QObject *parent=0)
virtual QVariant data (const QModelIndex &index, int role) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRows (QModelIndexList rows, const QModelIndex &index=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setListOfModelParameterSets (CCopasiVectorN< CModelParameterSet > *pListOfModelParameterSets)
virtual ~CQParameterSetsDM ()
Public Member Functions inherited from CQBaseDataModel
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
bool removeRow (int position)
Protected Member Functions
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Private Attributes
CCopasiVectorN
< CModelParameterSet > * mpListOfParameterSets
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 18 of file CQParameterSetsDM.h.
Constructor & Destructor Documentation
CQParameterSetsDM::CQParameterSetsDM (QObject * parent = 0)
Definition at line 17 of file CQParameterSetsDM.cpp.
                                                     :
   CQBaseDataModel(parent),
   mpListOfParameterSets(NULL)
 {}
CQParameterSetsDM::~CQParameterSetsDM () virtual
Definition at line 22 of file CQParameterSetsDM.cpp.
 {}
Member Function Documentation
bool CQParameterSetsDM::clear () virtual
Reimplemented from CQBaseDataModel.
Definition at line 32 of file CQParameterSetsDM.cpp.
References removeRows(), and rowCount().
Referenced by CQParameterSetsWidget::slotBtnClearClicked().
 {
   return removeRows(0, rowCount());
 }
int CQParameterSetsDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 37 of file CQParameterSetsDM.cpp.
References TOTAL_COLS.
Referenced by CQParameterSetsWidget::keyPressEvent().
 {
   return TOTAL_COLS;
 }
QVariant CQParameterSetsDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 61 of file CQParameterSetsDM.cpp.
References COL_NAME, COL_ROW_NUMBER, FROM_UTF8, mpListOfParameterSets, and rowCount().
 {
   if (mpListOfParameterSets == NULL) return QVariant();
   if (!index.isValid()) return QVariant();
   if (index.row() >= rowCount()) return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return QVariant(index.row() + 1);
             break;
           case COL_NAME:
             return QVariant(FROM_UTF8((*mpListOfParameterSets)[index.row()]->getObjectName()));
             break;
         }
     }
   return QVariant();
 }
Qt::ItemFlags CQParameterSetsDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 42 of file CQParameterSetsDM.cpp.
References COL_NAME, and COL_ROW_NUMBER.
 {
   if (!index.isValid())
     return QAbstractItemModel::flags(index);
   switch (index.column())
     {
       case COL_ROW_NUMBER:
         return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
         break;
       case COL_NAME:
         return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
         break;
     }
   return QAbstractItemModel::flags(index);
 }
QVariant CQParameterSetsDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 86 of file CQParameterSetsDM.cpp.
References COL_NAME, and COL_ROW_NUMBER.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
             break;
           case COL_NAME:
             return QVariant(QString("Name"));
             break;
           default:
             return QVariant();
             break;
         }
     }
   return QString("%1").arg(section + 1);
 }
bool CQParameterSetsDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) virtual
Implements CQBaseDataModel.
Definition at line 148 of file CQParameterSetsDM.cpp.
References ListViews::ADD, ListViews::LAYOUT, mpListOfParameterSets, CQBaseDataModel::notifyGUI(), and CCopasiVector< T >::size().
 {
   if (mpListOfParameterSets == NULL) return false;
   if (position + rows > (int) mpListOfParameterSets->size())  return false;
   beginInsertRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       emit notifyGUI(ListViews::LAYOUT, ListViews::ADD, (*mpListOfParameterSets)[position + row]->getKey());
     }
   endInsertRows();
   return true;
 }
bool CQParameterSetsDM::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 143 of file CQParameterSetsDM.cpp.
Referenced by CQParameterSetsWidget::slotDoubleClicked(), and CQParameterSetsWidget::updateDeleteBtns().
 {
   return false;
 }
bool CQParameterSetsDM::removeRows (QModelIndexList rows, const QModelIndex & index = QModelIndex())
Definition at line 201 of file CQParameterSetsDM.cpp.
References C_INVALID_INDEX, CQMessageBox::confirmDelete(), FROM_UTF8, CCopasiObject::getObjectName(), mpListOfParameterSets, and CQBaseDataModel::removeRow().
Referenced by clear(), and CQParameterSetsWidget::deleteSelected().
 {
   if (rows.isEmpty()) return false;
   if (mpListOfParameterSets == NULL) return false;
   //  Build the list of pointers to items to be deleted
   //  before actually deleting any item.
   QList< CModelParameterSet * > ModelParameterSets;
   QModelIndexList::const_iterator i;
   for (i = rows.begin(); i != rows.end(); ++i)
     {
       ModelParameterSets.append((*mpListOfParameterSets)[(*i).row()]);
     }
   QList< CModelParameterSet * >::const_iterator j;
   for (j = ModelParameterSets.begin(); j != ModelParameterSets.end(); ++j)
     {
       CModelParameterSet * pModelParameterSet = *j;
       size_t delRow = mpListOfParameterSets->CCopasiVector< CModelParameterSet >::getIndex(pModelParameterSet);
       if (delRow != C_INVALID_INDEX)
         {
           QMessageBox::StandardButton choice =
             CQMessageBox::confirmDelete(NULL, "layout",
                                         FROM_UTF8(pModelParameterSet->getObjectName()),
                                         std::set< const CCopasiObject * >());
           if (choice == QMessageBox::Ok)
             removeRow((int) delRow);
         }
     }
   return true;
 }
bool CQParameterSetsDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 166 of file CQParameterSetsDM.cpp.
References CCopasiVector< T >::begin(), ListViews::DELETE, CCopasiObject::getKey(), ListViews::MODELPARAMETERSET, mpListOfParameterSets, CQBaseDataModel::notifyGUI(), and pdelete.
 {
   if (rows <= 0) return true;
   if (mpListOfParameterSets == NULL) return false;
   beginRemoveRows(QModelIndex(), position, position + rows - 1);
   std::vector< CModelParameterSet * > DeletedModelParameterSets;
   DeletedModelParameterSets.resize(rows);
   std::vector< CModelParameterSet * >::iterator itDeletedModelParameterSet;
   std::vector< CModelParameterSet * >::iterator endDeletedModelParameterSet = DeletedModelParameterSets.end();
   CCopasiVectorN< CModelParameterSet >::const_iterator itRow = mpListOfParameterSets->begin() + position;
   for (itDeletedModelParameterSet = DeletedModelParameterSets.begin(); itDeletedModelParameterSet != endDeletedModelParameterSet; ++itDeletedModelParameterSet, ++itRow)
     {
       *itDeletedModelParameterSet = *itRow;
     }
   for (itDeletedModelParameterSet = DeletedModelParameterSets.begin(); itDeletedModelParameterSet != endDeletedModelParameterSet; ++itDeletedModelParameterSet)
     {
       std::string Key = (*itDeletedModelParameterSet)->getKey();
       pdelete(*itDeletedModelParameterSet);
       emit notifyGUI(ListViews::MODELPARAMETERSET, ListViews::DELETE, Key);
     }
   endRemoveRows();
   return true;
 }
int CQParameterSetsDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 25 of file CQParameterSetsDM.cpp.
References mpListOfParameterSets, and CCopasiVector< T >::size().
Referenced by clear(), data(), CQParameterSetsWidget::deleteSelected(), and setData().
 {
   if (mpListOfParameterSets == NULL) return 0;
   return (int) mpListOfParameterSets->size();
 }
bool CQParameterSetsDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 113 of file CQParameterSetsDM.cpp.
References COL_NAME, COL_ROW_NUMBER, mpListOfParameterSets, and rowCount().
 {
   if (mpListOfParameterSets == NULL) return false;
   if (!index.isValid()) return false;
   if (index.row() >= rowCount()) return false;
   if (index.isValid() && role == Qt::EditRole)
     {
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return false;
             break;
           case COL_NAME:
             return false;
             break;
           default:
             return false;
             break;
         }
     }
   return true;
 }
void CQParameterSetsDM::setListOfModelParameterSets (CCopasiVectorN< CModelParameterSet > * pListOfModelParameterSets)
Definition at line 240 of file CQParameterSetsDM.cpp.
References mpListOfParameterSets.
Referenced by CQParameterSetsWidget::enterProtected().
 {
   if (mpListOfParameterSets != pListOfModelParameterSets)
     {
       mpListOfParameterSets = pListOfModelParameterSets;
       reset();
     }
 }
Member Data Documentation
CCopasiVectorN< CModelParameterSet >* CQParameterSetsDM::mpListOfParameterSets private
Definition at line 46 of file CQParameterSetsDM.h.
Referenced by data(), insertRows(), removeRows(), rowCount(), setData(), and setListOfModelParameterSets().
The documentation for this class was generated from the following files:
CQParameterSetsDM.h
CQParameterSetsDM.cpp