COPASI API: CQExpandModelData Class Reference
CQExpandModelData Class Reference
#include <CQExpandModelData.h>
Public Member Functions
CQExpandModelData (QWidget *parent=0, Qt::WindowFlags fl=0)
~CQExpandModelData ()
Protected Slots
void slotCompartmentActivated (QTreeWidgetItem *pItem, int col)
handles activation or deactivation of a compartment
void slotMode ()
handles change of linear/rectangular mode
Protected Attributes
std::map< QTreeWidgetItem
*, const CCompartment * > mItemCompartmentMap
std::map< QTreeWidgetItem
*, const CMetab * > mItemMetabMap
CModel * pModel
Private Slots
void slotCancel ()
void slotOK ()
Private Member Functions
void load ()
Detailed Description
Definition at line 32 of file CQExpandModelData.h.
Constructor & Destructor Documentation
CQExpandModelData::CQExpandModelData (QWidget * parent = 0, Qt::WindowFlags fl = 0)
Definition at line 22 of file CQExpandModelData.cpp.
References load().
   : QDialog(parent, fl)
 {
   setupUi(this);
   mpLineEditSizeX->setValidator(new QIntValidator(1, 10000, this));
   mpLineEditSizeY->setValidator(new QIntValidator(1, 10000, this));
   load();
 }
CQExpandModelData::~CQExpandModelData ()
Definition at line 33 of file CQExpandModelData.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQExpandModelData::load () private
Definition at line 38 of file CQExpandModelData.cpp.
References FROM_UTF8, CModel::getCompartments(), CCopasiRootContainer::getDatamodelList(), CCopasiObject::getObjectName(), mItemCompartmentMap, pModel, CCopasiVector< T >::size(), slotCompartmentActivated(), and slotMode().
Referenced by CQExpandModelData().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   size_t i, imax = pModel->getCompartments().size();
   for (i = 0; i < imax; ++i)
     {
       QTreeWidgetItem * pItem = new QTreeWidgetItem((QTreeWidget*)NULL, 1000);
       pItem->setText(0,  FROM_UTF8(pModel->getCompartments()[i]->getObjectName()));
       pItem->setCheckState(0, Qt::Unchecked);
       mItemCompartmentMap[pItem] = pModel->getCompartments()[i];
       mpTreeWidget->addTopLevelItem(pItem);
     }
   connect(mpTreeWidget, SIGNAL(itemChanged(QTreeWidgetItem*, int)), this, SLOT(slotCompartmentActivated(QTreeWidgetItem*, int)));
   connect(mpRadioButtonLin, SIGNAL(toggled(bool)), this, SLOT(slotMode()));
   connect(mpRadioButtonRec, SIGNAL(toggled(bool)), this, SLOT(slotMode()));
 }
void CQExpandModelData::slotCancel () private slot
Definition at line 153 of file CQExpandModelData.cpp.
 {
   reject();
 }
void CQExpandModelData::slotCompartmentActivated (QTreeWidgetItem * pItem, int col) protected slot
handles activation or deactivation of a compartment
Definition at line 61 of file CQExpandModelData.cpp.
References FROM_UTF8, CCompartment::getMetabolites(), CCopasiObject::getObjectName(), if(), mItemCompartmentMap, mItemMetabMap, and CCopasiVector< T >::size().
Referenced by load().
 {
   //only do something if a checkbox in the first column is clicked
   if (col != 0)
     return;
   const CCompartment* pComp = NULL;
   std::map<QTreeWidgetItem*, const CCompartment*>::const_iterator it = mItemCompartmentMap.find(pItem);
   if (it != mItemCompartmentMap.end())
     pComp = it->second;
   if (!pComp)
     return;
   //checked
   if (pItem->checkState(0) == Qt::Checked)
     {
       size_t i, imax = pComp->getMetabolites().size();
       for (i = 0; i < imax; ++i)
         {
           QTreeWidgetItem * pChild = new QTreeWidgetItem(pItem, 1001);
           pChild->setText(0,  FROM_UTF8(pComp->getMetabolites()[i]->getObjectName()));
           pChild->setCheckState(1, Qt::Unchecked);
           mItemMetabMap[pChild] = pComp->getMetabolites()[i];
         }
       pItem->setExpanded(true);
     }
   //unchecked
   if (pItem->checkState(0) == Qt::Unchecked)
     {
       //remove children
       size_t i, imax = pItem->childCount();
       for (i = 0; i < imax; ++i)
         {
           pItem->removeChild(pItem->child(0));
         }
     }
 }
void CQExpandModelData::slotMode () protected slot
handles change of linear/rectangular mode
Definition at line 158 of file CQExpandModelData.cpp.
Referenced by load().
 {
   if (mpRadioButtonLin->isChecked())
     {
       mpLabelCross->setEnabled(false);
       mpLineEditSizeY->setEnabled(false);
     }
   else if (mpRadioButtonRec->isChecked())
     {
       mpLabelCross->setEnabled(true);
       mpLineEditSizeY->setEnabled(true);
     }
 }
void CQExpandModelData::slotOK () private slot
Definition at line 105 of file CQExpandModelData.cpp.
References CModelExpansion::SetOfModelElements::addCompartment(), CModelExpansion::createLinearArray(), CModelExpansion::createRectangularArray(), CModelExpansion::SetOfModelElements::fillDependencies(), mItemCompartmentMap, mItemMetabMap, and pModel.
 {
   CModelExpansion::SetOfModelElements modelelements;
   std::set<std::string> metabkeys;
   std::map<QTreeWidgetItem*, const CCompartment*>::const_iterator it;
   for (it = mItemCompartmentMap.begin(); it != mItemCompartmentMap.end(); ++it)
     {
       if (it->first->checkState(0) == Qt::Checked)
         {
           //the compartment is included
           modelelements.addCompartment(it->second);
           //check whether diffusion is requested for the metabolites inside
           size_t i;
           for (i = 0; i < it->first->childCount(); ++i)
             {
               if (it->first->child(i)->checkState(1) == Qt::Checked)
                 {
                   std::map<QTreeWidgetItem*, const CMetab*>::const_iterator itMetab = mItemMetabMap.find(it->first->child(i));
                   //const CMetab* pMetab = NULL;
                   if (itMetab != mItemMetabMap.end())
                     metabkeys.insert(itMetab->second->getKey());
                 }
             }
         }
     }
   CModelExpansion me(pModel);
   modelelements.fillDependencies(pModel);
   int multx, multy;
   multx = mpLineEditSizeX->text().toInt();
   multy = mpLineEditSizeY->text().toInt();
   if (mpRadioButtonLin->isChecked())
     me.createLinearArray(modelelements, multx, metabkeys);
   else if (mpRadioButtonRec->isChecked())
     me.createRectangularArray(modelelements, multx, multy, metabkeys);
   accept();
   // std::string name =  static_cast<std::string >(mpBoxCompartmentName->currentText().toUtf8());     //toStdString();
 }
Member Data Documentation
std::map<QTreeWidgetItem*, const CCompartment*> CQExpandModelData::mItemCompartmentMap protected
Definition at line 42 of file CQExpandModelData.h.
Referenced by load(), slotCompartmentActivated(), and slotOK().
std::map<QTreeWidgetItem*, const CMetab*> CQExpandModelData::mItemMetabMap protected
Definition at line 43 of file CQExpandModelData.h.
Referenced by slotCompartmentActivated(), and slotOK().
CModel* CQExpandModelData::pModel protected
Definition at line 44 of file CQExpandModelData.h.
Referenced by load(), and slotOK().
The documentation for this class was generated from the following files:
CQExpandModelData.h
CQExpandModelData.cpp