COPASI API: CStateTemplate Class Reference
CStateTemplate Class Reference
#include <CState.h>
Public Member Functions
void add (CModelEntity *entity)
CModelEntity ** beginDependent ()
CModelEntity *const * beginDependent () const
CModelEntity ** beginFixed ()
CModelEntity *const * beginFixed () const
CModelEntity ** beginIndependent ()
CModelEntity *const * beginIndependent () const
CStateTemplate (CModel &model, CState &initialState, CState &currentState)
CModelEntity ** endDependent ()
CModelEntity *const * endDependent () const
CModelEntity ** endFixed ()
CModelEntity *const * endFixed () const
CModelEntity ** endIndependent ()
CModelEntity *const * endIndependent () const
CModelEntity ** getEntities ()
CModelEntity *const * getEntities () const
size_t getIndex (const CModelEntity *entity) const
size_t getNumDependent () const
size_t getNumFixed () const
size_t getNumIndependent () const
size_t getNumVariable () const
const CVector< size_t > & getUserOrder () const
void remove (CModelEntity *entity)
void reorder (const CVector< CModelEntity * > &newOrder)
void setUserOrder (const CVector< CModelEntity * > &userOrder)
const size_t & size () const
~CStateTemplate ()
Protected Member Functions
void resize ()
Private Member Functions
CStateTemplate ()
Private Attributes
CState & mCurrentState
std::map< CModelEntity *, size_t > mIndexMap
CState & mInitialState
size_t mInsert
CModel & mModel
CModelEntity ** mpBeginDependent
CModelEntity ** mpBeginFixed
CModelEntity ** mpBeginIndependent
C_FLOAT64 * mpCurrentValues
CModelEntity ** mpEnd
CModelEntity ** mpEntities
C_FLOAT64 * mpInitialValues
size_t mSize
CVector< size_t > mUserOrder
Detailed Description
Definition at line 46 of file CState.h.
Constructor & Destructor Documentation
CStateTemplate::CStateTemplate () private
Default Constructor (inaccessible)
CStateTemplate::CStateTemplate (CModel & model, CState & initialState, CState & currentState)
Specific constructor
Parameters
CModel & model
CState & initialState
CState & currentState
Definition at line 41 of file CState.cpp.
                                                                                           :
     mModel(model),
     mInitialState(initialState),
     mCurrentState(currentState),
     mpEntities(NULL),
     mSize(0),
     mpBeginIndependent(NULL),
     mpBeginDependent(NULL),
     mpBeginFixed(NULL),
     mpEnd(NULL),
     mInsert(0),
     mIndexMap(),
     mUserOrder(0),
     mpInitialValues(NULL),
     mpCurrentValues(NULL)
 {}
CStateTemplate::~CStateTemplate ()
Destructor
Definition at line 58 of file CState.cpp.
References mpEntities, and pdeletev.
 {
   pdeletev(mpEntities);
 }
Member Function Documentation
void CStateTemplate::add (CModelEntity * entity)
Add an entity to the template.
Parameters
CModelEntity * entity
Definition at line 63 of file CState.cpp.
References mIndexMap, mInsert, mModel, mpCurrentValues, mpEntities, mpInitialValues, mSize, resize(), CModel::setCompileFlag(), CModelEntity::setInitialValuePtr(), and CModelEntity::setValuePtr().
Referenced by CModelEntity::initObjects(), CModel::initObjects(), and CModelEntity::setObjectParent().
 {
   if (mIndexMap.count(entity))
     return;
   if (mInsert == mSize) resize();
   mpEntities[mInsert] = entity;
   entity->setInitialValuePtr(mpInitialValues + mInsert);
   entity->setValuePtr(mpCurrentValues + mInsert);
   mIndexMap[entity] = mInsert++;
   mModel.setCompileFlag(true);
 }
CModelEntity ** CStateTemplate::beginDependent ()
Retrieve the array of pointers to all dependent entities, which are only dependent species for a reduced model.
Returns
CModelEntities ** dependentEntities
Definition at line 210 of file CState.cpp.
References mpBeginDependent.
Referenced by CModel::buildSimulatedSequence(), CMathContainer::initializeObjects(), and CQUpdatesWidget::loadObjectsTable().
 {return mpBeginDependent;}
CModelEntity *const * CStateTemplate::beginDependent () const
Retrieve the array of pointers to all dependent entities, which are only dependent species for a reduced model.
Returns
CModelEntities const dependentEntities
Definition at line 217 of file CState.cpp.
References mpBeginDependent.
 {return mpBeginDependent;}
CModelEntity ** CStateTemplate::beginFixed ()
Retrieve the array of pointers to all fixed entities.
Returns
CModelEntities ** fixedEntities
Definition at line 212 of file CState.cpp.
References mpBeginFixed.
Referenced by CMathContainer::initializeObjects(), and CQUpdatesWidget::loadObjectsTable().
 {return mpBeginFixed;}
CModelEntity *const * CStateTemplate::beginFixed () const
Retrieve the array of pointers to all fixed entities.
Returns
CModelEntities const fixedEntities
Definition at line 219 of file CState.cpp.
References mpBeginFixed.
 {return mpBeginFixed;}
CModelEntity ** CStateTemplate::beginIndependent ()
Retrieve the array of pointers to all independent entities.
Returns
CModelEntities ** independentEntities
Definition at line 208 of file CState.cpp.
References mpBeginIndependent.
Referenced by CSteadyStateMethod::allPositive(), CModel::buildApplyInitialValuesSequence(), CModel::buildDependencyGraphs(), CModel::buildInitialRefreshSequence(), CModel::buildInitialSequence(), CModel::buildSimulatedSequence(), CModel::buildStateTemplate(), CModel::calculateElasticityMatrix(), CCSPMethod::CSPOutput(), CCSPMethod::cspstep(), CSteadyStateTask::initialize(), CTSSAMethod::initializeAtol(), CModel::initializeAtolVector(), CMathContainer::initializeObjects(), CModel::isStateVariable(), CMCAMethod::isValidProblem(), CStochDirectMethod::isValidProblem(), CTrajAdaptiveSA::isValidProblem(), CQUpdatesWidget::loadObjectsTable(), CCSPMethod::predifineAnnotation(), CCSPMethod::printResult(), CCSPMethod::setAnnotationM(), CNewtonMethod::solveJacobianXeqB(), CTauLeapMethod::start(), CStochDirectMethod::start(), CCSPMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethodDsaLsodar::start(), CNewtonMethod::targetFunction(), and CSteadyStateTask::updateMatrices().
 {return mpBeginIndependent;}
CModelEntity *const * CStateTemplate::beginIndependent () const
Retrieve the array of pointers to all independent entities.
Returns
CModelEntities const independentEntities
Definition at line 215 of file CState.cpp.
References mpBeginIndependent.
 {return mpBeginIndependent;}
CModelEntity ** CStateTemplate::endDependent ()
Retrieve pointer just beyond the dependent entities.
Returns
CModelEntities ** endDependentEntities
Definition at line 211 of file CState.cpp.
References mpBeginFixed.
Referenced by CModel::buildSimulatedSequence(), CModel::calculateElasticityMatrix(), CMathModel::compile(), CMathContainer::initializeObjects(), CModel::isStateVariable(), and CQUpdatesWidget::loadObjectsTable().
 {return mpBeginFixed;}
CModelEntity *const * CStateTemplate::endDependent () const
Retrieve pointer just beyond the dependent entities.
Returns
CModelEntities ** endDependentEntities
Definition at line 218 of file CState.cpp.
References mpBeginFixed.
 {return mpBeginFixed;}
CModelEntity ** CStateTemplate::endFixed ()
Retrieve pointer just beyond the fixed entities.
Returns
CModelEntities ** endFixedEntities
Definition at line 213 of file CState.cpp.
References mpEnd.
Referenced by CModel::buildApplyInitialValuesSequence(), DataModelGUI::buildChangedObjects(), CModel::buildDependencyGraphs(), CModel::buildInitialRefreshSequence(), CModel::buildInitialSequence(), CModel::buildSimulatedSequence(), CModel::buildStateTemplate(), CTimeSeries::compile(), CMathContainer::initializeObjects(), CQUpdatesWidget::loadObjectsTable(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), and CTrajectoryMethodDsaLsodar::start().
 {return mpEnd;}
CModelEntity *const * CStateTemplate::endFixed () const
Retrieve pointer just beyond the fixed entities.
Returns
CModelEntities const endFixedEntities
Definition at line 220 of file CState.cpp.
References mpEnd.
 {return mpEnd;}
CModelEntity ** CStateTemplate::endIndependent ()
Retrieve pointer just beyond the independent entities.
Returns
CModelEntities ** endIndependentEntities
Definition at line 209 of file CState.cpp.
References mpBeginDependent.
Referenced by CModel::buildSimulatedSequence(), CMathContainer::initializeObjects(), CMCAMethod::isValidProblem(), CStochDirectMethod::isValidProblem(), CTrajAdaptiveSA::isValidProblem(), and CQUpdatesWidget::loadObjectsTable().
 {return mpBeginDependent;}
CModelEntity *const * CStateTemplate::endIndependent () const
Retrieve pointer just beyond the independent entities.
Returns
CModelEntities const endIndependentEntities
Definition at line 216 of file CState.cpp.
References mpBeginDependent.
 {return mpBeginDependent;}
CModelEntity ** CStateTemplate::getEntities ()
Retrieve the array of pointers to all entities.
Returns
CModelEntities ** entities
Definition at line 204 of file CState.cpp.
References mpEntities.
Referenced by DataModelGUI::buildChangedObjects(), CMathModel::buildDependendRefreshList(), CModel::buildUserOrder(), CModel::calculateDerivatives(), CModel::calculateDerivativesX(), CFixLocalReactionParameters::checkModel(), CMathModel::compile(), CTimeSeries::compile(), CModel::getTreesWithDiscontinuities(), CSteadyStateTask::initialize(), CQUpdatesWidget::loadObjectsTable(), CCopasiXML::saveModel(), and CSteadyStateTask::updateMatrices().
 {return mpEntities;}
CModelEntity *const * CStateTemplate::getEntities () const
Retrieve the array of pointers to all entities.
Returns
CModelEntities const entities
Definition at line 205 of file CState.cpp.
References mpEntities.
 {return mpEntities;}
size_t CStateTemplate::getIndex (const CModelEntity * entity) const
Retrieve the index of an entity in the template. Returns C_INVALID_INDEX if the entity is not found.
Parameters
const CModelEntity * entity
Returns
size_t index
Definition at line 231 of file CState.cpp.
References C_INVALID_INDEX, and mIndexMap.
Referenced by CTimeSeries::compile(), CCopasiXMLParser::InitialStateElement::end(), setUserOrder(), CTauLeapMethod::start(), CHybridMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), CStochMethod::start(), and CTrajectoryMethodDsaLsodar::start().
 {
   std::map< CModelEntity *, size_t >::const_iterator found =
     mIndexMap.find(const_cast< CModelEntity * >(entity));
   if (found != mIndexMap.end())
     return found->second;
   return C_INVALID_INDEX;
 }
size_t CStateTemplate::getNumDependent () const
Retrieve the number of dependent entities.
Returns
size_t numDependent
Definition at line 224 of file CState.cpp.
References mpBeginDependent, and mpBeginFixed.
Referenced by CSteadyStateTask::updateMatrices().
 {return mpBeginFixed - mpBeginDependent;}
size_t CStateTemplate::getNumFixed () const
Retrieve the number of fixed entities.
Returns
size_t numFixed
Definition at line 228 of file CState.cpp.
References mpBeginFixed, and mpEnd.
 {return mpEnd - mpBeginFixed;}
size_t CStateTemplate::getNumIndependent () const
Retrieve the number of independent entities.
Returns
size_t numIndependent
Definition at line 222 of file CState.cpp.
References mpBeginDependent, and mpBeginIndependent.
Referenced by CModel::buildUserOrder(), CModel::calculateDerivatives(), CModel::calculateDerivativesX(), CMathModel::calculateRootDerivatives(), CNewtonMethod::initialize(), CModel::initializeAtolVector(), and CSteadyStateTask::updateMatrices().
 {return mpBeginDependent - mpBeginIndependent;}
size_t CStateTemplate::getNumVariable () const
Retrieve the number of variable entities, i.e., the sum of independent and dependent variables.
Returns
size_t numVariable
Definition at line 226 of file CState.cpp.
References mpBeginFixed, and mpBeginIndependent.
 {return mpBeginFixed - mpBeginIndependent;}
const CVector< size_t > & CStateTemplate::getUserOrder () const
Retrieve a pivot vector which can be used to reconstruct the user order.
Returns
const CVector<size_t> & userOrder
Definition at line 201 of file CState.cpp.
References mUserOrder.
Referenced by CModel::buildUserOrder(), CTimeSeries::compile(), CSteadyStateTask::initialize(), and CSteadyStateTask::updateMatrices().
 {return mUserOrder;}
void CStateTemplate::remove (CModelEntity * entity)
Remove an entity from the template.
Parameters
CModelEntity * entity
Definition at line 80 of file CState.cpp.
References mIndexMap, mModel, mpEntities, CModel::setCompileFlag(), CModelEntity::setInitialValuePtr(), and CModelEntity::setValuePtr().
Referenced by CModelEntity::setObjectParent(), and CModelEntity::~CModelEntity().
 {
   std::map< CModelEntity *, size_t >::iterator it =
     mIndexMap.find(entity);
   if (it == mIndexMap.end())
     return;
   entity->setInitialValuePtr(NULL);
   entity->setValuePtr(NULL);
   mpEntities[it->second] = NULL;
   mIndexMap.erase(it);
   mModel.setCompileFlag(true);
 }
void CStateTemplate::reorder (const CVector< CModelEntity * > & newOrder)
Reorder the template.
Parameters
const CVector< CModelEntity * > & newOrder
Definition at line 98 of file CState.cpp.
References CVectorCore< CType >::array(), CModelEntity::ASSIGNMENT, C_FLOAT64, CModelEntity::FIXED, mCurrentState, mIndexMap, mInitialState, mInsert, mpBeginDependent, mpBeginFixed, mpBeginIndependent, mpCurrentValues, mpEnd, mpEntities, mpInitialValues, CModelEntity::ODE, CModelEntity::REACTIONS, CVectorCore< CType >::size(), CModelEntity::TIME, and CState::updateIterator().
Referenced by CModel::buildSimulatedSequence(), and CModel::buildStateTemplate().
 {
   assert(entitiesX.size() + 1 == mIndexMap.size());
   // Update mpEntities to reflect the new order;
   memcpy(mpEntities + 1, entitiesX.array(), sizeof(CModelEntity *) * entitiesX.size());
   mInsert = entitiesX.size() + 1;
   std::map< CModelEntity *, size_t >::iterator found;
   CVector<C_FLOAT64> InitialValues(entitiesX.size());
   CVector<C_FLOAT64> CurrentValues(entitiesX.size());
   CModelEntity *const*it = entitiesX.array();
   CModelEntity *const*end = it + entitiesX.size();
   size_t i;
   size_t Independent, Dependent, Fixed;
   Independent = Dependent = Fixed = 0;
   for (i = 1; it != end; ++it, i++)
     {
       found = mIndexMap.find(*it);
       assert(found != mIndexMap.end());
       // Build new order
       InitialValues[i - 1] = *(mpInitialValues + found->second);
       CurrentValues[i - 1] = *(mpCurrentValues + found->second);
       // Update pointer if necessary
       if (i != found->second)
         {
           found->second = i;
           found->first->setInitialValuePtr(mpInitialValues + found->second);
           found->first->setValuePtr(mpCurrentValues + found->second);
         }
       // Count numbers for each status type;
       if ((*it)->isUsed())
         switch ((*it)->getStatus())
           {
             case CModelEntity::FIXED:
               Fixed++;
               break;
             case CModelEntity::REACTIONS:
               if (static_cast< CMetab * >(*it)->isDependent())
                 {
                   assert(Fixed == 0);
                   Dependent++;
                 }
               else
                 {
                   assert(Dependent == 0);
                   Independent++;
                 }
               break;
             case CModelEntity::ODE:
               assert(Dependent == 0);
               Independent++;
               break;
             case CModelEntity::ASSIGNMENT:
               assert(Fixed == 0);
               Dependent++;
               break;
             case CModelEntity::TIME:
               assert(false);
               break;
           }
       else
         Fixed++;
     }
   mpBeginIndependent = mpEntities + 1;
   mpBeginDependent = mpBeginIndependent + Independent;
   mpBeginFixed = mpBeginDependent + Dependent;
   mpEnd = mpBeginFixed + Fixed;
   memcpy(mpInitialValues + 1, InitialValues.array(), sizeof(C_FLOAT64) * entitiesX.size());
   memcpy(mpCurrentValues + 1, CurrentValues.array(), sizeof(C_FLOAT64) * entitiesX.size());
   // Update the iterators of the states
   mInitialState.updateIterator(Independent, Dependent, Fixed);
   mCurrentState.updateIterator(Independent, Dependent, Fixed);
 }
void CStateTemplate::resize () protected
Resize the template
Definition at line 245 of file CState.cpp.
References C_FLOAT64, mCurrentState, mInitialState, mInsert, mpCurrentValues, mpEntities, mpInitialValues, mSize, pdeletev, and CState::resize().
Referenced by add().
 {
   size_t OldSize = mSize;
   if (mSize)
     mSize *= 2;
   else
     mSize = 16;
   // Resize the entities array.
   CModelEntity ** pTmp = mpEntities;
   mpEntities = new CModelEntity * [mSize];
   memcpy(mpEntities, pTmp, sizeof(CModelEntity *) * OldSize);
   pdeletev(pTmp);
   // Resize the states
   C_FLOAT64 * pInitialValues = mpInitialValues = mInitialState.resize(mSize);
   C_FLOAT64 * pCurrentValues = mpCurrentValues = mCurrentState.resize(mSize);
   // Update all pointers in the entities
   pTmp = mpEntities;
   CModelEntity ** pEnd = pTmp + mInsert;
   for (; pTmp != pEnd; ++pTmp, ++pInitialValues, ++pCurrentValues)
     if (*pTmp != NULL)
       {
         (*pTmp)->setInitialValuePtr(pInitialValues);
         (*pTmp)->setValuePtr(pCurrentValues);
       }
 }
void CStateTemplate::setUserOrder (const CVector< CModelEntity * > & userOrder)
Set the user preferred order of the entities.
Parameters
const CVector< CModelEntity * > & userOrder
Definition at line 189 of file CState.cpp.
References CVectorCore< CType >::array(), getIndex(), mUserOrder, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by CModel::buildUserOrder().
 {
   mUserOrder.resize(entities.size() + 1);
   size_t * pUserOrder = mUserOrder.array();
   *pUserOrder++ = 0; // for time
   CModelEntity *const *it = entities.array();
   CModelEntity *const *end = it + entities.size();
   while (it != end) *pUserOrder++ = getIndex(*it++);
 }
const size_t & CStateTemplate::size () const
Retrieve size of the template, i.e., the number of entities.
Returns
size_t size
Definition at line 242 of file CState.cpp.
References mInsert.
Referenced by CMathContainer::allocate(), CMathModel::buildDependendRefreshList(), CModel::buildSimulatedSequence(), CFixLocalReactionParameters::checkModel(), CModel::getTreesWithDiscontinuities(), CQUpdatesWidget::loadObjectsTable(), and CCopasiXML::saveModel().
 {return mInsert;}
Member Data Documentation
CState& CStateTemplate::mCurrentState private
A reference to the current state of the model
Definition at line 247 of file CState.h.
Referenced by reorder(), and resize().
std::map< CModelEntity *, size_t > CStateTemplate::mIndexMap private
A map of pointer to entities to the index it appear in the template
Definition at line 287 of file CState.h.
Referenced by add(), getIndex(), remove(), and reorder().
CState& CStateTemplate::mInitialState private
A reference to the initial state of the model
Definition at line 242 of file CState.h.
Referenced by reorder(), and resize().
size_t CStateTemplate::mInsert private
The index in which the next added entity must be inserted.
Definition at line 282 of file CState.h.
Referenced by add(), reorder(), resize(), and size().
CModel& CStateTemplate::mModel private
A reference to the model
Definition at line 237 of file CState.h.
Referenced by add(), and remove().
CModelEntity** CStateTemplate::mpBeginDependent private
A pointer to the dependent entities
Definition at line 267 of file CState.h.
Referenced by beginDependent(), endIndependent(), getNumDependent(), getNumIndependent(), and reorder().
CModelEntity** CStateTemplate::mpBeginFixed private
A pointer to the fixed entities
Definition at line 272 of file CState.h.
Referenced by beginFixed(), endDependent(), getNumDependent(), getNumFixed(), getNumVariable(), and reorder().
CModelEntity** CStateTemplate::mpBeginIndependent private
A pointer to the independent entities
Definition at line 262 of file CState.h.
Referenced by beginIndependent(), getNumIndependent(), getNumVariable(), and reorder().
C_FLOAT64* CStateTemplate::mpCurrentValues private
The array of current values of all entities
Definition at line 302 of file CState.h.
Referenced by add(), reorder(), and resize().
CModelEntity** CStateTemplate::mpEnd private
A pointer just beyond the entities
Definition at line 277 of file CState.h.
Referenced by endFixed(), getNumFixed(), and reorder().
CModelEntity** CStateTemplate::mpEntities private
The array of entities
Definition at line 252 of file CState.h.
Referenced by add(), getEntities(), remove(), reorder(), resize(), and ~CStateTemplate().
C_FLOAT64* CStateTemplate::mpInitialValues private
The array of initial values of all entities
Definition at line 297 of file CState.h.
Referenced by add(), reorder(), and resize().
size_t CStateTemplate::mSize private
The allocate size of the template
Definition at line 257 of file CState.h.
Referenced by add(), and resize().
CVector<size_t> CStateTemplate::mUserOrder private
A pivot vector storing the user order of the entities
Definition at line 292 of file CState.h.
Referenced by getUserOrder(), and setUserOrder().
The documentation for this class was generated from the following files:
CState.h
CState.cpp