COPASI API: CQSensResultWidget Class Reference
CQSensResultWidget Class Reference
#include <CQSensResultWidget.h>
Public Member Functions
CQSensResultWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool leave ()
void newResult ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQSensResultWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void saveToFile ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
void clearArrays ()
virtual bool enterProtected ()
Protected Attributes
const CArrayAnnotation * mpCollapsedResult
const CArrayAnnotation * mpResult
const CArrayAnnotation * mpScaledResult
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Private Member Functions
void init ()
Detailed Description
Definition at line 32 of file CQSensResultWidget.h.
Constructor & Destructor Documentation
CQSensResultWidget::CQSensResultWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 37 of file CQSensResultWidget.cpp.
References init().
   : CopasiWidget(parent, name, fl),
     mpResult(NULL)
 {
   setupUi(this);
   init();
 }
CQSensResultWidget::~CQSensResultWidget ()
Definition at line 49 of file CQSensResultWidget.cpp.
 {}
Member Function Documentation
void CQSensResultWidget::clearArrays () protected
Definition at line 111 of file CQSensResultWidget.cpp.
Referenced by enterProtected(), and newResult().
 {
   mArrayWidget->setArrayAnnotation(NULL);
   mArrayWidgetScaled->setArrayAnnotation(NULL);
   mArrayWidgetCollapsed->setArrayAnnotation(NULL);
 }
bool CQSensResultWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 135 of file CQSensResultWidget.cpp.
References clearArrays(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getProblem(), CSensProblem::getResultAnnotated(), mpResult, and pTask.
 {
   //clear the widget if the pointer to the result has changed
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CSensTask * pTask =
     dynamic_cast<CSensTask*>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Sensitivities"]);
   if (!pTask)
     {
       clearArrays();
       return false;
     }
   CSensProblem * pProblem = dynamic_cast< CSensProblem * >(pTask->getProblem());
   if (!pProblem)
     {
       clearArrays();
       return false;
     }
   if (mpResult != pProblem->getResultAnnotated())
     {
       clearArrays();
       return false;
     }
   return true;
 }
void CQSensResultWidget::init () private
Definition at line 52 of file CQSensResultWidget.cpp.
References CColorScaleAverage::setFactor().
Referenced by CQSensResultWidget().
 {
   // unscaled array
   CColorScaleBiLog * tcs = new CColorScaleBiLog();
   mArrayWidget->setColorCoding(tcs);
   mArrayWidget->setColorScalingAutomatic(true);
   //scaled array
   CColorScaleAverage* tcs2 = new CColorScaleAverage();
   mArrayWidgetScaled->setColorCoding(tcs2);
   tcs2->setFactor(3.0);
   mArrayWidgetScaled->setColorScalingAutomatic(true);
   //scaled array
   CColorScaleAverage* tcs3 = new CColorScaleAverage();
   mArrayWidgetCollapsed->setColorCoding(tcs3);
   tcs3->setFactor(3.0);
   mArrayWidgetCollapsed->setColorScalingAutomatic(true);
 }
bool CQSensResultWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 130 of file CQSensResultWidget.cpp.
 {
   return true;
 }
void CQSensResultWidget::newResult ()
Definition at line 72 of file CQSensResultWidget.cpp.
References clearArrays(), CSensProblem::collapsRequested(), CSensProblem::getCollapsedResultAnnotated(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getProblem(), CSensProblem::getResultAnnotated(), CSensProblem::getScaledResultAnnotated(), mpCollapsedResult, mpResult, mpScaledResult, and pTask.
Referenced by SensitivitiesWidget::taskFinishedEvent().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   // clear the old one
   clearArrays();
   CSensTask * pTask =
     dynamic_cast<CSensTask*>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Sensitivities"]);
   if (!pTask)
     return;
   CSensProblem * pProblem = dynamic_cast< CSensProblem * >(pTask->getProblem());
   if (!pProblem)
     return;
   mpResult = pProblem->getResultAnnotated();
   mpScaledResult = pProblem->getScaledResultAnnotated();
   mArrayWidget->setArrayAnnotation(mpResult);
   mArrayWidgetScaled->setArrayAnnotation(mpScaledResult);
   //tab for collapsed result
   if (pProblem->collapsRequested())
     {
       mpCollapsedResult = pProblem->getCollapsedResultAnnotated();
       mpTab->setTabEnabled(mpTab->indexOf(mArrayWidgetCollapsed), true);
     }
   else
     {
       mpCollapsedResult = NULL;
       mpTab->setTabEnabled(mpTab->indexOf(mArrayWidgetCollapsed), false);
     }
   mArrayWidgetCollapsed->setArrayAnnotation(mpCollapsedResult);
 }
void CQSensResultWidget::saveToFile () protected slot
Definition at line 165 of file CQSensResultWidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getResult(), CopasiFileDialog::getSaveFileName(), pTask, and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail())
     return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CSensTask * pTask =
     dynamic_cast<CSensTask*>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Sensitivities"]);
   if (pTask != NULL)
     file << pTask->getResult();
 //    pTask->print(&file);
   return;
 }
bool CQSensResultWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 120 of file CQSensResultWidget.cpp.
 {
   /*  if (this->isShown())
       return loadFromBackend();
     else
       return true;*/
   return true;
 }
Member Data Documentation
const CArrayAnnotation* CQSensResultWidget::mpCollapsedResult protected
Definition at line 55 of file CQSensResultWidget.h.
Referenced by newResult().
const CArrayAnnotation* CQSensResultWidget::mpResult protected
Definition at line 53 of file CQSensResultWidget.h.
Referenced by enterProtected(), and newResult().
const CArrayAnnotation* CQSensResultWidget::mpScaledResult protected
Definition at line 54 of file CQSensResultWidget.h.
Referenced by newResult().
The documentation for this class was generated from the following files:
CQSensResultWidget.h
CQSensResultWidget.cpp