COPASI API: CLRadialGradient Class Reference
CLRadialGradient Class Reference
#include <CLRadialGradient.h>
Public Member Functions
CLRadialGradient (CCopasiContainer *pParent=NULL)
CLRadialGradient (const CLRadialGradient &source, CCopasiContainer *pParent=NULL)
CLRadialGradient (const RadialGradient &source, CCopasiContainer *pParent=NULL)
const CLRelAbsVector & getCenterX () const
CLRelAbsVector & getCenterX ()
const CLRelAbsVector & getCenterY () const
CLRelAbsVector & getCenterY ()
const CLRelAbsVector & getCenterZ () const
CLRelAbsVector & getCenterZ ()
const CLRelAbsVector & getFocalPointX () const
CLRelAbsVector & getFocalPointX ()
const CLRelAbsVector & getFocalPointY () const
CLRelAbsVector & getFocalPointY ()
const CLRelAbsVector & getFocalPointZ () const
CLRelAbsVector & getFocalPointZ ()
const CLRelAbsVector & getRadius () const
CLRelAbsVector & getRadius ()
void setCenter (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setCoordinates (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z, const CLRelAbsVector &r, const CLRelAbsVector &fx, const CLRelAbsVector &fy, const CLRelAbsVector &fz)
void setCoordinates (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &r, const CLRelAbsVector &fx, const CLRelAbsVector &fy)
void setFocalPoint (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setRadius (const CLRelAbsVector &r)
virtual RadialGradient * toSBML (unsigned int level, unsigned int version) const
Public Member Functions inherited from CLGradientBase
void addGradientStop (const CLGradientStop *pStop)
virtual void addSBMLAttributes (GradientBase *pBase) const
CLGradientBase (const std::string &name, CCopasiContainer *pParent=NULL)
CLGradientBase (const CLGradientBase &source, CCopasiContainer *pParent=NULL)
CLGradientBase (const GradientBase &source, const std::string &name, CCopasiContainer *pParent=NULL)
CLGradientStop * createGradientStop ()
CLGradientStop * getGradientStop (size_t i)
const CLGradientStop * getGradientStop (size_t i) const
const std::string & getId () const
const std::string & getKey () const
CCopasiVector< CLGradientStop > * getListOfGradientStops ()
const CCopasiVector
< CLGradientStop > * getListOfGradientStops () const
size_t getNumGradientStops () const
SPREADMETHOD getSpreadMethod () const
void setId (const std::string &id)
void setSpreadMethod (SPREADMETHOD method)
virtual ~CLGradientBase ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CLRelAbsVector mCX
CLRelAbsVector mCY
CLRelAbsVector mCZ
CLRelAbsVector mFX
CLRelAbsVector mFY
CLRelAbsVector mFZ
CLRelAbsVector mRadius
Protected Attributes inherited from CLGradientBase
CCopasiVector< CLGradientStop > mGradientStops
std::string mId
std::string mKey
SPREADMETHOD mSpreadMethod
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CLRadialGradient & operator= (const CLRadialGradient &source)
Additional Inherited Members
Public Types inherited from CLGradientBase
enum SPREADMETHOD { PAD, REFLECT, REPEAT }
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 25 of file CLRadialGradient.h.
Constructor & Destructor Documentation
CLRadialGradient::CLRadialGradient (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 26 of file CLRadialGradient.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and CLGradientBase::mKey.
     : CLGradientBase("RadialGradient", pParent),
     mCX(CLRelAbsVector(0.0, 50.0)),
     mCY(CLRelAbsVector(0.0, 50.0)),
     mCZ(CLRelAbsVector(0.0, 50.0)),
     mRadius(CLRelAbsVector(0.0, 50.0)),
     mFX(CLRelAbsVector(0.0, 50.0)),
     mFY(CLRelAbsVector(0.0, 50.0)),
     mFZ(CLRelAbsVector(0.0, 50.0))
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RadialGradient", this);
 }
CLRadialGradient::CLRadialGradient (const CLRadialGradient & source, CCopasiContainer * pParent = NULL)
Copy Constructor.
Definition at line 42 of file CLRadialGradient.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and CLGradientBase::mKey.
                                                                                            :
     CLGradientBase(source, pParent),
     mCX(source.mCX),
     mCY(source.mCY),
     mCZ(source.mCZ),
     mRadius(source.mRadius),
     mFX(source.mFX),
     mFY(source.mFY),
     mFZ(source.mFZ)
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RadialGradient", this);
 }
CLRadialGradient::CLRadialGradient (const RadialGradient & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 58 of file CLRadialGradient.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and CLGradientBase::mKey.
                                                                                          :
     CLGradientBase(source, "RadialGradient", pParent),
     mCX(source.getCenterX()),
     mCY(source.getCenterY()),
     mCZ(source.getCenterZ()),
     mRadius(source.getRadius()),
     mFX(source.getFocalPointX()),
     mFY(source.getFocalPointY()),
     mFZ(source.getFocalPointZ())
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RadialGradient", this);
 }
Member Function Documentation
const CLRelAbsVector & CLRadialGradient::getCenterX () const
Returns the x coordinate for the center point.
Definition at line 122 of file CLRadialGradient.cpp.
References mCX.
Referenced by CLLayoutRenderer::create_radial_gradient_texture(), getRadialGradient(), CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mCX;
 }
CLRelAbsVector & CLRadialGradient::getCenterX ()
Returns the x coordinate for the center point.
Definition at line 178 of file CLRadialGradient.cpp.
References mCX.
 {
   return this->mCX;
 }
const CLRelAbsVector & CLRadialGradient::getCenterY () const
Returns the y coordinate for the center point.
Definition at line 130 of file CLRadialGradient.cpp.
References mCY.
Referenced by CLLayoutRenderer::create_radial_gradient_texture(), getRadialGradient(), CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mCY;
 }
CLRelAbsVector & CLRadialGradient::getCenterY ()
Returns the y coordinate for the center point.
Definition at line 186 of file CLRadialGradient.cpp.
References mCY.
 {
   return this->mCY;
 }
const CLRelAbsVector & CLRadialGradient::getCenterZ () const
Returns the z coordinate for the center point.
Definition at line 138 of file CLRadialGradient.cpp.
References mCZ.
Referenced by CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mCZ;
 }
CLRelAbsVector & CLRadialGradient::getCenterZ ()
Returns the z coordinate for the center point.
Definition at line 194 of file CLRadialGradient.cpp.
References mCZ.
 {
   return this->mCZ;
 }
const CLRelAbsVector & CLRadialGradient::getFocalPointX () const
Returns the x coordinate for the focal point.
Definition at line 146 of file CLRadialGradient.cpp.
References mFX.
Referenced by CLLayoutRenderer::create_radial_gradient_texture(), getRadialGradient(), CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mFX;
 }
CLRelAbsVector & CLRadialGradient::getFocalPointX ()
Returns the x coordinate for the focal point.
Definition at line 202 of file CLRadialGradient.cpp.
References mFX.
 {
   return this->mFX;
 }
const CLRelAbsVector & CLRadialGradient::getFocalPointY () const
Returns the x coordinate for the focal point.
Definition at line 154 of file CLRadialGradient.cpp.
References mFY.
Referenced by CLLayoutRenderer::create_radial_gradient_texture(), getRadialGradient(), CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mFY;
 }
CLRelAbsVector & CLRadialGradient::getFocalPointY ()
Returns the x coordinate for the focal point.
Definition at line 210 of file CLRadialGradient.cpp.
References mFY.
 {
   return this->mFY;
 }
const CLRelAbsVector & CLRadialGradient::getFocalPointZ () const
Returns the x coordinate for the focal point.
Definition at line 162 of file CLRadialGradient.cpp.
References mFZ.
Referenced by CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mFZ;
 }
CLRelAbsVector & CLRadialGradient::getFocalPointZ ()
Returns the x coordinate for the focal point.
Definition at line 218 of file CLRadialGradient.cpp.
References mFZ.
 {
   return this->mFZ;
 }
const CLRelAbsVector & CLRadialGradient::getRadius () const
Returns the radius.
Definition at line 170 of file CLRadialGradient.cpp.
References mRadius.
Referenced by CLLayoutRenderer::create_radial_gradient_texture(), getRadialGradient(), CCopasiXML::saveRadialGradient(), and toSBML().
 {
   return this->mRadius;
 }
CLRelAbsVector & CLRadialGradient::getRadius ()
Returns the radius.
Definition at line 226 of file CLRadialGradient.cpp.
References mRadius.
 {
   return this->mRadius;
 }
CLRadialGradient& CLRadialGradient::operator= (const CLRadialGradient & source) private
void CLRadialGradient::setCenter (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Sets the coordinates for the first point.
Definition at line 94 of file CLRadialGradient.cpp.
References mCX, mCY, and mCZ.
Referenced by setCoordinates(), and CCopasiXMLParser::RadialGradientElement::start().
 {
   this->mCX = x;
   this->mCY = y;
   this->mCZ = z;
 }
void CLRadialGradient::setCoordinates (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z, const CLRelAbsVector & r, const CLRelAbsVector & fx, const CLRelAbsVector & fy, const CLRelAbsVector & fz)
Sets the 3D coordinates for the center and the focal point as well as the radius.
Definition at line 75 of file CLRadialGradient.cpp.
References setCenter(), setFocalPoint(), and setRadius().
Referenced by setCoordinates().
 {
   this->setCenter(x, y, z);
   this->setRadius(r);
   this->setFocalPoint(fx, fy, fz);
 }
void CLRadialGradient::setCoordinates (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & r, const CLRelAbsVector & fx, const CLRelAbsVector & fy)
Sets the 2D coordinates for center and the focal point as well as the radius.
Definition at line 86 of file CLRadialGradient.cpp.
References setCoordinates().
 {
   this->setCoordinates(x, y, CLRelAbsVector(0.0, 50.0), r, fx, fy, CLRelAbsVector(0.0, 50.0));
 }
void CLRadialGradient::setFocalPoint (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Sets the coordinates for the second point.
Definition at line 104 of file CLRadialGradient.cpp.
References mFX, mFY, and mFZ.
Referenced by setCoordinates(), and CCopasiXMLParser::RadialGradientElement::start().
 {
   this->mFX = x;
   this->mFY = y;
   this->mFZ = z;
 }
void CLRadialGradient::setRadius (const CLRelAbsVector & r)
Sets the radius.
Definition at line 114 of file CLRadialGradient.cpp.
References mRadius.
Referenced by setCoordinates(), and CCopasiXMLParser::RadialGradientElement::start().
 {
   this->mRadius = r;
 }
RadialGradient * CLRadialGradient::toSBML (unsigned int level, unsigned int version) const virtual
Converts this object to the corresponding SBML object.
Definition at line 234 of file CLRadialGradient.cpp.
References CLGradientBase::addSBMLAttributes(), getCenterX(), getCenterY(), getCenterZ(), getFocalPointX(), getFocalPointY(), getFocalPointZ(), getRadius(), and CLRelAbsVector::toSBML().
 {
   RadialGradient* pRG = new RadialGradient(level, version);
   this->addSBMLAttributes(pRG);
   RelAbsVector* pV1 = this->getCenterX().toSBML();
   RelAbsVector* pV2 = this->getCenterY().toSBML();
   RelAbsVector* pV3 = this->getCenterZ().toSBML();
   pRG->setCenter(*pV1, *pV2, *pV3);
   delete pV1;
   delete pV2;
   delete pV3;
   pV1 = this->getFocalPointX().toSBML();
   pV2 = this->getFocalPointY().toSBML();
   pV3 = this->getFocalPointZ().toSBML();
   pRG->setFocalPoint(*pV1, *pV2, *pV3);
   pV1 = this->getRadius().toSBML();
   pRG->setRadius(*pV1);
   delete pV1;
   return pRG;
 }
Member Data Documentation
CLRelAbsVector CLRadialGradient::mCX protected
Definition at line 32 of file CLRadialGradient.h.
Referenced by getCenterX(), and setCenter().
CLRelAbsVector CLRadialGradient::mCY protected
Definition at line 33 of file CLRadialGradient.h.
Referenced by getCenterY(), and setCenter().
CLRelAbsVector CLRadialGradient::mCZ protected
Definition at line 34 of file CLRadialGradient.h.
Referenced by getCenterZ(), and setCenter().
CLRelAbsVector CLRadialGradient::mFX protected
Definition at line 36 of file CLRadialGradient.h.
Referenced by getFocalPointX(), and setFocalPoint().
CLRelAbsVector CLRadialGradient::mFY protected
Definition at line 37 of file CLRadialGradient.h.
Referenced by getFocalPointY(), and setFocalPoint().
CLRelAbsVector CLRadialGradient::mFZ protected
Definition at line 38 of file CLRadialGradient.h.
Referenced by getFocalPointZ(), and setFocalPoint().
CLRelAbsVector CLRadialGradient::mRadius protected
Definition at line 35 of file CLRadialGradient.h.
Referenced by getRadius(), and setRadius().
The documentation for this class was generated from the following files:
CLRadialGradient.h
CLRadialGradient.cpp