COPASI API: CNormalLcm Class Reference
CNormalLcm Class Reference
#include <CNormalLcm.h>
Public Member Functions
bool add (const CNormalItemPower &itemPower)
bool add (const CNormalSum &sum)
CNormalLcm ()
CNormalLcm (const CNormalLcm &src)
const std::set
< CNormalItemPower
*, compareItemPowers > & getItemPowers () const
const std::vector< CNormalSum * > & getSums () const
CNormalLcm & operator= (const CNormalLcm &src)
bool remove (const CNormalItemPower &itemPower)
bool remove (const CNormalSum &sum)
std::string toString () const
~CNormalLcm ()
Private Attributes
std::set< CNormalItemPower
*, compareItemPowers > mItemPowers
std::vector< CNormalSum * > mSums
Friends
std::ostream & operator<< (std::ostream &os, const CNormalLcm &d)
Detailed Description
The class for lcms used in CNormal
Definition at line 33 of file CNormalLcm.h.
Constructor & Destructor Documentation
CNormalLcm::CNormalLcm ()
Default constructor
Definition at line 37 of file CNormalLcm.cpp.
 {}
CNormalLcm::CNormalLcm (const CNormalLcm & src)
Copy contructor
Definition at line 43 of file CNormalLcm.cpp.
References mItemPowers, and mSums.
 {
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = src.mItemPowers.end();
   for (it = src.mItemPowers.begin(); it != itEnd; ++it)
     {
       mItemPowers.insert(new CNormalItemPower(**it));
     }
   std::vector<CNormalSum*>::const_iterator it2;
   std::vector<CNormalSum*>::const_iterator it2End = src.mSums.end();
   for (it2 = src.mSums.begin(); it2 != it2End; ++it2)
     {
       mSums.push_back(new CNormalSum(**it2));
     }
 }
CNormalLcm::~CNormalLcm ()
Destructor
Definition at line 85 of file CNormalLcm.cpp.
References mItemPowers, and mSums.
 {
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     delete *it;
   std::vector<CNormalSum*>::const_iterator it2;
   std::vector<CNormalSum*>::const_iterator it2End = mSums.end();
   for (it2 = mSums.begin(); it2 != it2End; ++it2)
     delete *it2;
 }
Member Function Documentation
bool CNormalLcm::add (const CNormalItemPower & itemPower)
Add an itempower to this lcm, ie. lcm := LeastCommonMultiple(lcm,itempower)
Returns
true.
Definition at line 105 of file CNormalLcm.cpp.
References CNormalItemPower::getExp(), CNormalItemPower::getItem(), and mItemPowers.
Referenced by add(), and CNormalFraction::findLcm().
 {
   std::set <CNormalItemPower*, compareItemPowers >::iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(itemPower.getItem()))
         {
           (*it)->setExp((*it)->getExp() > itemPower.getExp() ? (*it)->getExp() : itemPower.getExp());
           return true;
         }
     }
   CNormalItemPower* tmp = new CNormalItemPower(itemPower);
   mItemPowers.insert(tmp);
   return true;
 }
bool CNormalLcm::add (const CNormalSum & sum)
Add a fractionless sum to this lcm, ie. lcm := LeastCommonMultiple(lcm,sum)
Returns
true.
Definition at line 129 of file CNormalLcm.cpp.
References add(), CNormalProduct::getItemPowers(), CNormalSum::getProducts(), and mSums.
 {
   switch (sum.getProducts().size())
     {
       case 0:     //Sum must contain at least one product!
       {
         return false;
       }
       case 1:
       {
         CNormalProduct* product = *sum.getProducts().begin();
         std::set<CNormalItemPower*, compareItemPowers >::const_iterator it;
         std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = product->getItemPowers().end();
         for (it = product->getItemPowers().begin(); it != itEnd; ++it)
           {
             add(**it);
           }
         return true;
       }
       default:
       {
         std::vector<CNormalSum*>::iterator it;
         std::vector<CNormalSum*>::iterator itEnd = mSums.end();
         for (it = mSums.begin(); it != itEnd; ++it)
           {
             if (sum == **it)
               {
                 return true;
               }
           }
         CNormalSum* tmp = new CNormalSum(sum);
         mSums.push_back(tmp);
         return true;
       }
     }
 }
const std::set< CNormalItemPower *, compareItemPowers > & CNormalLcm::getItemPowers () const
Retrieve the set of itempowers of this lcm.
Returns
mItemPowers.
Definition at line 266 of file CNormalLcm.cpp.
References mItemPowers.
Referenced by convertToCEvaluationNode(), and CNormalProduct::multiply().
 {
   return mItemPowers;
 }
const std::vector< CNormalSum * > & CNormalLcm::getSums () const
Retrieve the vector of sums of this lcm.
Returns
mSums.
Definition at line 275 of file CNormalLcm.cpp.
References mSums.
Referenced by convertToCEvaluationNode(), and CNormalProduct::multiply().
 {
   return mSums;
 }
CNormalLcm & CNormalLcm::operator= (const CNormalLcm & src)
Assignment operator
Definition at line 65 of file CNormalLcm.cpp.
References mItemPowers, and mSums.
 {
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = src.mItemPowers.end();
   for (it = src.mItemPowers.begin(); it != itEnd; ++it)
     mItemPowers.insert(new CNormalItemPower(**it));
   std::vector<CNormalSum*>::const_iterator it2;
   std::vector<CNormalSum*>::const_iterator it2End = src.mSums.end();
   for (it2 = src.mSums.begin(); it2 != it2End; ++it2)
     mSums.push_back(new CNormalSum(**it2));
   return *this;
 }
bool CNormalLcm::remove (const CNormalItemPower & itemPower)
Remove an itempower from this lcm, provided it is a factor
Returns
true.
Definition at line 176 of file CNormalLcm.cpp.
References C_FLOAT64, CNormalItemPower::getExp(), CNormalItemPower::getItem(), and mItemPowers.
Referenced by CNormalFraction::multiply().
 {
   std::set <CNormalItemPower*, compareItemPowers >::iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(itemPower.getItem()))
         {
           C_FLOAT64 dif = (*it)->getExp() - itemPower.getExp();
           if (dif <= -1.0E-100)
             return false;
           if (fabs(dif) < 1.0E-100)
             {
               delete *it;
               mItemPowers.erase(it);
               return true;
             }
           (*it)->setExp(dif);
           return true;
         }
     }
   return false;
 }
bool CNormalLcm::remove (const CNormalSum & sum)
Remove a fractionless sum from this lcm, provided it is a factor
Returns
true.
Definition at line 209 of file CNormalLcm.cpp.
References CNormalProduct::getItemPowers(), CNormalSum::getProducts(), and mSums.
 {
   bool result = true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it, itEnd;
   std::vector<CNormalSum*>::iterator it2, itEnd2;
   const CNormalProduct* pProduct = NULL;
   switch (sum.getProducts().size())
     {
       case 0:
         result = false;
         break;
       case 1:
         pProduct = *sum.getProducts().begin();
         itEnd = pProduct->getItemPowers().end();
         for (it = pProduct->getItemPowers().begin(); it != itEnd && result == true; ++it)
           {
             if (remove(**it) == false)
               {
                 result = false;
               }
           }
         break;
       default:
         itEnd2 = mSums.end();
         result = false;
         for (it2 = mSums.begin(); it2 != itEnd2; ++it2)
           {
             if (**it2 == sum)
               {
                 delete *it2;
                 mSums.erase(it2);
                 result = true;
                 break;
               }
           }
         // the below causes issues on VS, as in a way the iterator is no longer
         // valid after removal, instead the result is set in the loop
         //if (it2 == itEnd2)
         //{
         //  result = false;
         //}
     }
   return result;
 }
std::string CNormalLcm::toString () const
Definition at line 280 of file CNormalLcm.cpp.
 {
   std::ostringstream os;
   os << *this;
   return os.str();
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CNormalLcm & d) friend
Definition at line 287 of file CNormalLcm.cpp.
 {
   if (d.mItemPowers.size() + d.mSums.size() != 0)
     {
       bool firstFactor = true;
       std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
       std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = d.mItemPowers.end();
       for (it = d.mItemPowers.begin(); it != itEnd; ++it)
         {
           if (firstFactor == false)
             {
               os << " * ";
             }
           os << **it;
           firstFactor = false;
         }
       std::vector<CNormalSum*>::const_iterator it2;
       std::vector<CNormalSum*>::const_iterator it2End = d.mSums.end();
       for (it2 = d.mSums.begin(); it2 != it2End; ++it2)
         {
           if (firstFactor == false)
             {
               os << " * ";
             }
           os << "(" << **it2 << ")";
           firstFactor = false;
         }
     }
   else
     {
       os << "1.0";
     }
   return os;
 }
Member Data Documentation
std::set<CNormalItemPower*, compareItemPowers > CNormalLcm::mItemPowers private
Enumeration of members
Definition at line 39 of file CNormalLcm.h.
Referenced by add(), CNormalLcm(), getItemPowers(), operator<<(), operator=(), remove(), and ~CNormalLcm().
std::vector<CNormalSum*> CNormalLcm::mSums private
Definition at line 40 of file CNormalLcm.h.
Referenced by add(), CNormalLcm(), getSums(), operator<<(), operator=(), remove(), and ~CNormalLcm().
The documentation for this class was generated from the following files:
CNormalLcm.h
CNormalLcm.cpp