COPASI API: CNormalBase Class Reference
CNormalBase Class Reference abstract
#include <CNormalBase.h>
Public Member Functions
virtual bool areEqual (const CNormalBase &rhs) const
virtual CNormalBase * copy () const =0
virtual bool simplify ()=0
virtual std::string toString () const =0
virtual ~CNormalBase ()
Detailed Description
Definition at line 23 of file CNormalBase.h.
Constructor & Destructor Documentation
virtual CNormalBase::~CNormalBase () inline virtual
Definition at line 27 of file CNormalBase.h.
 {};
Member Function Documentation
bool CNormalBase::areEqual (const CNormalBase & rhs) const virtual
Definition at line 37 of file CNormalBase.cpp.
   {
     bool result = false;
     if (dynamic_cast<const CNormalItem*>(this) != NULL && dynamic_cast<const CNormalItem*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalItem&>(*this) == static_cast<const CNormalItem&>(rhs));
       }
     else if (dynamic_cast<const CNormalFraction*>(this) != NULL && dynamic_cast<const CNormalFraction*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalFraction&>(*this) == static_cast<const CNormalFraction&>(rhs));
       }
     else if (dynamic_cast<const CNormalSum*>(this) != NULL && dynamic_cast<const CNormalSum*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalSum&>(*this) == static_cast<const CNormalSum&>(rhs));
       }
     else if (dynamic_cast<const CNormalProduct*>(this) != NULL && dynamic_cast<const CNormalProduct*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalProduct&>(*this) == static_cast<const CNormalProduct&>(rhs));
       }
     else if (dynamic_cast<const CNormalItemPower*>(this) != NULL && dynamic_cast<const CNormalItemPower*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalItemPower&>(*this) == static_cast<const CNormalItemPower&>(rhs));
       }
     else if (dynamic_cast<const CNormalGeneralPower*>(this) != NULL && dynamic_cast<const CNormalGeneralPower*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalGeneralPower&>(*this) == static_cast<const CNormalGeneralPower&>(rhs));
       }
     else if (dynamic_cast<const CNormalFunction*>(this) != NULL && dynamic_cast<const CNormalFunction*>(&rhs) != NULL)
       {
         result = (static_cast<const CNormalFunction&>(*this) == static_cast<const CNormalFunction&>(rhs));
       }
     /*
     else if(dynamic_cast<const CNormalLogical*>(this)!=NULL && dynamic_cast<const CNormalLogical*>(&rhs)!=NULL)
     {
         result=(static_cast<const CNormalLogical&>(*this)==static_cast<const CNormalLogical&>(rhs));
     }
     else if(dynamic_cast<const CNormalChoice*>(this)!=NULL && dynamic_cast<const CNormalChoice*>(&rhs)!=NULL)
     {
         result=(static_cast<const CNormalChoice&>(*this)==static_cast<const CNormalChoice&>(rhs));
     }
     */
     return result;
   }
virtual CNormalBase* CNormalBase::copy () const pure virtual
Implemented in CNormalLogical, CNormalCall, CNormalFunction, CNormalSum, CNormalItemPower, CNormalProduct, CNormalFraction, CNormalGeneralPower, CNormalLogicalItem, CNormalItem, CNormalChoice, and CNormalChoiceLogical.
Referenced by CNormalItemPower::CNormalItemPower(), CNormalItemPower::operator=(), CNormalItemPower::setItem(), and CNormalSum::simplify().
virtual bool CNormalBase::simplify () pure virtual
Implemented in CNormalLogical, CNormalProduct, CNormalSum, CNormalFraction, CNormalItemPower, CNormalCall, CNormalItem, CNormalFunction, CNormalChoice, CNormalChoiceLogical, CNormalGeneralPower, and CNormalLogicalItem.
Referenced by CNormalItemPower::simplify().
virtual std::string CNormalBase::toString () const pure virtual
Implemented in CNormalLogical, CNormalProduct, CNormalFraction, CNormalSum, CNormalItemPower, CNormalCall, CNormalItem, CNormalFunction, CNormalGeneralPower, CNormalChoice, CNormalChoiceLogical, and CNormalLogicalItem.
Referenced by CNormalItemPower::toString().
The documentation for this class was generated from the following files:
CNormalBase.h
CNormalBase.cpp