COPASI API: CQExpressionWidget.cpp File Reference
CQExpressionWidget.cpp File Reference
#include <iostream>
#include <QtGui/QLabel>
#include <QtGui/QComboBox>
#include <QtGui/QKeyEvent>
#include "CQExpressionWidget.h"
#include "CQMessageBox.h"
#include "CCopasiSelectionDialog.h"
#include "qtUtilities.h"
#include "copasi.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "function/CExpression.h"
#include "function/CFunctionDB.h"
#include "function/CMassAction.h"
#include "utilities/CAnnotatedMatrix.h"
#include "model/CModel.h"
#include "CQMatrixDialog.h"
#include "report/CCopasiRootContainer.h"
#include "commandline/CConfigurationFile.h"
Macros
#define DEBUG_UI
Functions
const CCopasiObject * findObjectByDisplayName (const CCopasiDataModel *dataModel, const std::string displayString)
std::ostream & operator<< (std::ostream &os, const QTextCursor &d)
Macro Definition Documentation
#define DEBUG_UI
Definition at line 40 of file CQExpressionWidget.cpp.
Function Documentation
const CCopasiObject* findObjectByDisplayName (const CCopasiDataModel * dataModel, const std::string displayString)
Definition at line 655 of file CQExpressionWidget.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModel::getCompartments(), CMetab::getConcentrationRateReference(), CMetab::getConcentrationReference(), CMetab::getInitialConcentrationReference(), CModelEntity::getInitialValueReference(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CModel::getModelValues(), CCopasiContainer::getObject(), CCopasiObjectReference< CType >::getObjectDisplayName(), CMetab::getObjectDisplayName(), CCopasiObject::getObjectDisplayName(), CModelEntity::getRateReference(), and CModelEntity::getValueReference().
Referenced by CQExpressionWidget::getExpression().
 {
   if (dataModel == NULL || displayString.empty()) return NULL;
   const CModel* model = dataModel->getModel();
   if (displayString == "Time") return model;
   if (displayString == "Avogadro Constant") return dynamic_cast<const CCopasiObject* >(model->getObject("Reference=" + displayString));
   if (displayString == "Quantity Conversion Factor") return dynamic_cast<const CCopasiObject* >(model->getObject("Reference=" + displayString));
   size_t pos = displayString.find("Compartments[");
   if (pos != std::string::npos)
     {
       const CCopasiVectorN< CCompartment > & compartments = model->getCompartments();
       for (CCopasiVectorN< CCompartment >::const_iterator it = compartments.begin(); it != compartments.end(); ++it)
         {
           const CCompartment *current = *it;
           if (current->getObjectDisplayName() == displayString)
             {
               return current;
             }
           else if (current->getInitialValueReference() != NULL &&
                    current->getInitialValueReference()->getObjectDisplayName() == displayString)
             {
               return current->getInitialValueReference();
             }
           else if (current->getValueReference() != NULL &&
                    current->getValueReference()->getObjectDisplayName() == displayString)
             {
               return current->getValueReference();
             }
           else if (current->getRateReference() != NULL &&
                    current->getRateReference()->getObjectDisplayName() == displayString)
             {
               return current->getRateReference();
             }
         }
     }
   pos = displayString.find("Values[");
   if (pos != std::string::npos)
     {
       const CCopasiVectorN< CModelValue > & values = model->getModelValues();
       for (CCopasiVectorN< CModelValue >::const_iterator it = values.begin(); it != values.end(); ++it)
         {
           const CModelValue *current = *it;
           if (current->getObjectDisplayName() == displayString)
             {
               return current;
             }
           else if (current->getInitialValueReference() != NULL &&
                    current->getInitialValueReference()->getObjectDisplayName() == displayString)
             {
               return current->getInitialValueReference();
             }
           else if (current->getValueReference() != NULL &&
                    current->getValueReference()->getObjectDisplayName() == displayString)
             {
               return current->getValueReference();
             }
           else if (current->getRateReference() != NULL &&
                    current->getRateReference()->getObjectDisplayName() == displayString)
             {
               return current->getRateReference();
             }
         }
     }
   // no reasonable check for metabolites, so lets just go through them
   {
     const CCopasiVector< CMetab > & metabs = model->getMetabolites();
     for (CCopasiVector< CMetab >::const_iterator it = metabs.begin(); it != metabs.end(); ++it)
       {
         const CMetab *current = *it;
         if (current->getObjectDisplayName() == displayString)
           {
             return current;
           }
         else if (current->getInitialValueReference() != NULL &&
                  current->getInitialValueReference()->getObjectDisplayName() == displayString)
           {
             return current->getInitialValueReference();
           }
         else if (current->getInitialConcentrationReference() != NULL &&
                  current->getInitialConcentrationReference()->getObjectDisplayName() == displayString)
           {
             return current->getInitialConcentrationReference();
           }
         else if (current->getValueReference() != NULL &&
                  current->getValueReference()->getObjectDisplayName() == displayString)
           {
             return current->getValueReference();
           }
         else if (current->getConcentrationReference() != NULL &&
                  current->getConcentrationReference()->getObjectDisplayName() == displayString)
           {
             return current->getConcentrationReference();
           }
         else if (current->getRateReference() != NULL &&
                  current->getRateReference()->getObjectDisplayName() == displayString)
           {
             return current->getRateReference();
           }
         else if (current->getConcentrationRateReference() != NULL &&
                  current->getConcentrationRateReference()->getObjectDisplayName() == displayString)
           {
             return current->getConcentrationRateReference();
           }
       }
   }
   return NULL;
 }
std::ostream& operator<< (std::ostream & os, const QTextCursor & d)
Definition at line 43 of file CQExpressionWidget.cpp.
References TO_UTF8.
 {
   os << "Position:        " << d.position() << std::endl;
   os << "Selection Start: " << d.selectionStart() << std::endl;
   os << "Selection End:   " << d.selectionEnd() << std::endl;
   os << "Anchor:          " << d.anchor() << std::endl;
   os << "Selected Text:   " << TO_UTF8(d.selectedText()) << std::endl;
   return os;
 }