COPASI API: CRDFObject Class Reference
CRDFObject Class Reference
#include <CRDFObject.h>
Public Types
enum eObjectType { RESOURCE = 0, BLANK_NODE, LITERAL }
Public Member Functions
void clearData ()
CRDFObject ()
CRDFObject (const CRDFObject &src)
const std::string & getBlankNodeID () const
CRDFLiteral & getLiteral ()
const CRDFLiteral & getLiteral () const
const std::string & getResource () const
const eObjectType & getType () const
const bool & isLocal () const
CRDFObject & operator= (const CRDFObject &rhs)
void setBlankNodeId (const std::string &blankNodeId)
void setLiteral (const CRDFLiteral &literal)
void setResource (const std::string &resource, const bool &isLocal)
void setType (const eObjectType &type)
virtual ~CRDFObject ()
Private Member Functions
bool operator== (const CRDFObject &rhs) const
Private Attributes
std::string mBlankNodeId
bool mIsLocalResource
CRDFLiteral * mpLiteral
std::string mResource
eObjectType mType
Detailed Description
Definition at line 25 of file CRDFObject.h.
Member Enumeration Documentation
enum CRDFObject::eObjectType
The three different types possible for objects
Enumerator
RESOURCE
BLANK_NODE
LITERAL
Definition at line 32 of file CRDFObject.h.
 {RESOURCE = 0, BLANK_NODE, LITERAL};
Constructor & Destructor Documentation
CRDFObject::CRDFObject ()
Default Constructor
Definition at line 23 of file CRDFObject.cpp.
                       :
     mType(RESOURCE),
     mResource(""),
     mBlankNodeId(""),
     mIsLocalResource(false),
     mpLiteral(NULL)
 {}
CRDFObject::CRDFObject (const CRDFObject & src)
Copy Constructor
Parameters
const CRDFObject & src
Definition at line 31 of file CRDFObject.cpp.
                                             :
     mType(src.mType),
     mResource(src.mResource),
     mBlankNodeId(src.mBlankNodeId),
     mIsLocalResource(src.mIsLocalResource),
     mpLiteral(src.mpLiteral == NULL ? NULL : new CRDFLiteral(*src.mpLiteral))
 {}
CRDFObject::~CRDFObject () virtual
Destructor
Definition at line 52 of file CRDFObject.cpp.
References mpLiteral, and pdelete.
 {pdelete(mpLiteral);}
Member Function Documentation
void CRDFObject::clearData ()
Reset all Data
Definition at line 128 of file CRDFObject.cpp.
References mBlankNodeId, mIsLocalResource, mpLiteral, mResource, mType, and RESOURCE.
 {
   mType = RESOURCE;
   mResource = "";
   mBlankNodeId = "";
   mIsLocalResource = false;
   mpLiteral = NULL;
 }
const std::string & CRDFObject::getBlankNodeID () const
Retrieve the ID of the blank node of the object
Returns
const std::string & blankNodeId
Definition at line 103 of file CRDFObject.cpp.
References mBlankNodeId.
Referenced by CRDFGraph::destroyUnreferencedNode(), CRDFNode::getFieldValue(), CRDFNode::setObject(), CQRDFTreeViewItem::setTriplet(), and CRDFWriter::write().
   {return mBlankNodeId;}
CRDFLiteral & CRDFObject::getLiteral ()
Retrieve the literal of the object
Returns
CRDFLiteral & literal
Definition at line 112 of file CRDFObject.cpp.
References mpLiteral.
Referenced by CRDFNode::getFieldValue(), CRDFNode::setFieldValue(), CQRDFTreeViewItem::setTriplet(), and CRDFWriter::write().
 {
   if (mpLiteral == NULL)
     mpLiteral = new CRDFLiteral;
   return *mpLiteral;
 }
const CRDFLiteral & CRDFObject::getLiteral () const
Retrieve the literal of the object
Returns
const CRDFLiteral & literal
Definition at line 120 of file CRDFObject.cpp.
References mpLiteral.
   {
     if (mpLiteral == NULL)
       mpLiteral = new CRDFLiteral;
     return *mpLiteral;
   }
const std::string & CRDFObject::getResource () const
Retrieve the resource of the object
Returns
const std::string & resource
Definition at line 94 of file CRDFObject.cpp.
References mResource.
Referenced by CMIRIAMResourceObject::CMIRIAMResourceObject(), CRDFGraph::destroyUnreferencedNode(), CRDFNode::getFieldValue(), CMIRIAMResourceObject::setNode(), CQRDFTreeViewItem::setTriplet(), and CRDFWriter::write().
   {return mResource;}
const CRDFObject::eObjectType & CRDFObject::getType () const
Retrieve the type of the object
Returns
const eObjectType & type
Definition at line 85 of file CRDFObject.cpp.
References mType.
Referenced by CRDFGraph::destroyUnreferencedNode(), CRDFNode::getFieldValue(), CRDFNode::setFieldValue(), CRDFNode::setObject(), CQRDFTreeViewItem::setTriplet(), and CRDFWriter::write().
   {return mType;}
const bool & CRDFObject::isLocal () const
Check whehter the resource is local
Returns
const bool & isLocal
Definition at line 97 of file CRDFObject.cpp.
References mIsLocalResource.
Referenced by CRDFGraph::destroyUnreferencedNode(), and setResource().
   {return mIsLocalResource;}
CRDFObject & CRDFObject::operator= (const CRDFObject & rhs)
Definition at line 39 of file CRDFObject.cpp.
References mBlankNodeId, mIsLocalResource, mpLiteral, mResource, and mType.
 {
   if (this != &rhs)
     {
       mType = rhs.mType;
       mResource = rhs.mResource;
       mBlankNodeId = rhs.mBlankNodeId;
       mIsLocalResource = rhs.mIsLocalResource;
       mpLiteral = (rhs.mpLiteral == NULL ? NULL : new CRDFLiteral(*rhs.mpLiteral));
     }
   return *this;
 }
bool CRDFObject::operator== (const CRDFObject & rhs) const private
Definition at line 55 of file CRDFObject.cpp.
References BLANK_NODE, LITERAL, mBlankNodeId, mIsLocalResource, mpLiteral, mResource, mType, and RESOURCE.
   {
     if (mType == rhs.mType)
       {
         switch (mType)
           {
           case CRDFObject::BLANK_NODE:
             if (mBlankNodeId == rhs.mBlankNodeId)
               return true;
             break;
           case CRDFObject::RESOURCE:
             if (mResource == rhs.mResource && mIsLocalResource == rhs.mIsLocalResource)
               return true;
             break;
           case CRDFObject::LITERAL:
             if (mpLiteral != NULL && rhs.mpLiteral != NULL)
               return false; // TODO (*mpLiteral == *rhs.mpLiteral);
             else if (mpLiteral == NULL && rhs.mpLiteral == NULL)
               return true;
             break;
           }
       }
     return false;
   }
void CRDFObject::setBlankNodeId (const std::string & blankNodeId)
Set the ID of the blank node of the object
Parameters
const std::string & blankNodeId
Definition at line 100 of file CRDFObject.cpp.
References mBlankNodeId.
Referenced by CRDFGraphConverter::convert(), CMIRIAMInfo::createCreator(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), CMIRIAMInfo::setCreatedDT(), CRDFNode::setSubject(), and CRDFParser::TripleHandler().
 {mBlankNodeId = blankNodeId;}
void CRDFObject::setLiteral (const CRDFLiteral & literal)
Set the literal of the object
Parameters
const std::string & lexicalData
Definition at line 106 of file CRDFObject.cpp.
References mpLiteral, and pdelete.
Referenced by CRDFParser::TripleHandler().
 {
   pdelete(mpLiteral);
   mpLiteral = new CRDFLiteral(literal);
 }
void CRDFObject::setResource (const std::string & resource, const bool & isLocal)
Set the resource of the object
Parameters
const std::string & resource
const bool & isLocal
Definition at line 88 of file CRDFObject.cpp.
References isLocal(), mIsLocalResource, and mResource.
Referenced by CRDFNode::addEdge(), CRDFGraphConverter::convert(), CMIRIAMInfo::createBiologicalDescription(), CRDFNode::setFieldValue(), CBiologicalDescription::setId(), CReference::setId(), CBiologicalDescription::setResource(), CReference::setResource(), and CRDFParser::TripleHandler().
 {
   mResource = resource;
   mIsLocalResource = isLocal;
 }
void CRDFObject::setType (const eObjectType & type)
Set the type of the object
Parameters
const eObjectType & type
Definition at line 82 of file CRDFObject.cpp.
References mType.
Referenced by CRDFNode::addEdge(), CRDFGraphConverter::convert(), CMIRIAMInfo::createBiologicalDescription(), CMIRIAMInfo::createCreator(), CRDFNode::createMissingAncestors(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), CMIRIAMInfo::setCreatedDT(), CRDFNode::setFieldValue(), CRDFNode::setSubject(), and CRDFParser::TripleHandler().
 {mType = type;}
Member Data Documentation
std::string CRDFObject::mBlankNodeId private
The Id of the blank node for type BLANK_NODE
Definition at line 139 of file CRDFObject.h.
Referenced by clearData(), getBlankNodeID(), operator=(), operator==(), and setBlankNodeId().
bool CRDFObject::mIsLocalResource private
Stores whether the reources is resolve locally or remotely.
Definition at line 144 of file CRDFObject.h.
Referenced by clearData(), isLocal(), operator=(), operator==(), and setResource().
CRDFLiteral* CRDFObject::mpLiteral mutable private
The pointer to the literal for type LITERAL
Definition at line 149 of file CRDFObject.h.
Referenced by clearData(), getLiteral(), operator=(), operator==(), setLiteral(), and ~CRDFObject().
std::string CRDFObject::mResource private
The URI of the resource of type RESOURCE
Definition at line 134 of file CRDFObject.h.
Referenced by clearData(), getResource(), operator=(), operator==(), and setResource().
eObjectType CRDFObject::mType private
The type of the object
Definition at line 129 of file CRDFObject.h.
Referenced by clearData(), getType(), operator=(), operator==(), and setType().
The documentation for this class was generated from the following files:
CRDFObject.h
CRDFObject.cpp