COPASI API: CQCompartment Class Reference
CQCompartment Class Reference
#include <CQCompartment.h>
Public Member Functions
void copy ()
CQCompartment (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQCompartment ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotBtnCopy ()
void slotBtnDelete ()
void slotBtnNew ()
void slotExpressionValid (bool valid)
void slotInitialExpressionValid (bool valid)
void slotInitialTypeChanged (bool useInitialAssignment)
void slotMetaboliteTableCurrentChanged (int row, int col)
void slotTypeChanged (int type)
Private Member Functions
void destroy ()
void init ()
void load ()
void loadMetaboliteTable ()
void save ()
Private Attributes
bool mChanged
bool mExpressionValid
bool mInitialExpressionValid
std::vector< int > mItemToType
CCompartment * mpCompartment
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 26 of file CQCompartment.h.
Constructor & Destructor Documentation
CQCompartment::CQCompartment (QWidget * parent = 0, const char * name = 0)
Definition at line 38 of file CQCompartment.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, FROM_UTF8, CQExpressionWidget::InitialExpression, mExpressionValid, mInitialExpressionValid, mItemToType, CModelEntity::ODE, CModelEntity::StatusName, and CQExpressionWidget::TransientExpression.
                                                              :
   CopasiWidget(parent, name),
   mItemToType(),
   mpCompartment(NULL),
   mChanged(false),
   mExpressionValid(true),
   mInitialExpressionValid(true)
 {
   setupUi(this);
   mpComboBoxType->insertItem(mpComboBoxType->count(), FROM_UTF8(CModelEntity::StatusName[CModelEntity::FIXED]));
   mpComboBoxType->insertItem(mpComboBoxType->count(), FROM_UTF8(CModelEntity::StatusName[CModelEntity::ASSIGNMENT]));
   mpComboBoxType->insertItem(mpComboBoxType->count(), FROM_UTF8(CModelEntity::StatusName[CModelEntity::ODE]));
   mItemToType.push_back(CModelEntity::FIXED);
   mItemToType.push_back(CModelEntity::ASSIGNMENT);
   mItemToType.push_back(CModelEntity::ODE);
   mpMetaboliteTable->horizontalHeader()->hide();
   mExpressionValid = false;
   mpExpressionEMW->mpExpressionWidget->setExpressionType(CQExpressionWidget::TransientExpression);
   mInitialExpressionValid = false;
   mpInitialExpressionEMW->mpExpressionWidget->setExpressionType(CQExpressionWidget::InitialExpression);
 #ifdef COPASI_EXTUNIT
   mpLblDim->show();
   mpComboBoxDim->show();
 #else
   mpLblDim->hide();
   mpComboBoxDim->hide();
 #endif
 }
CQCompartment::~CQCompartment ()
Definition at line 76 of file CQCompartment.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQCompartment::copy ()
Definition at line 103 of file CQCompartment.cpp.
References CModelExpansion::SetOfModelElements::addMetab(), CModelExpansion::SetOfModelElements::addObject(), CModelExpansion::SetOfModelElements::addReaction(), CQCompartmentCopyOptions::ALLREAC, CCopasiVector< T >::begin(), C_INVALID_INDEX, CQCompartmentCopyOptions::COMP, ListViews::COMPARTMENT, ListViews::DELETE, CModelExpansion::duplicate(), CCopasiVector< T >::end(), CModelExpansion::SetOfModelElements::fillDependencies(), CReactionInterface::getChemEqInterface(), CChemEqInterface::getCompartment(), CModelExpansion::ElementsMap::getDuplicateKey(), CModelEntity::getKey(), CCompartment::getMetabolites(), CCopasiDataModel::getModel(), CModel::getReactions(), CReactionInterface::initFromReaction(), CQCompartmentCopyOptions::INTREAC, CReactionInterface::isMulticompartment(), ListViews::METABOLITE, CopasiWidget::mKey, mpCompartment, CopasiWidget::mpDataModel, CopasiWidget::mpListView, CopasiWidget::mpObject, pdelete, CopasiWidget::protectedNotify(), ListViews::REACTION, CQCompartmentCopyOptions::SPECIES, and ListViews::switchToOtherWidget().
Referenced by CQTabWidget::slotBtnCopy().
 {
   CModel * pModel = mpDataModel->getModel();
   CModelExpansion cModelExpObj = CModelExpansion(pModel);
   CModelExpansion::SetOfModelElements compartmentObjectsToCopy;
   CModelExpansion::ElementsMap origToCopyMappings;
   CQCompartmentCopyOptions * pDialog = new CQCompartmentCopyOptions(this);
   pDialog->exec();
   bool success = false;
   switch (pDialog->result())
     {
       case QDialog::Rejected:
         break;
       case CQCompartmentCopyOptions::COMP:      //compartment only
         compartmentObjectsToCopy.addObject(mpObject);
         success = true;
         break;
       case CQCompartmentCopyOptions::SPECIES: // include the species
       {
         compartmentObjectsToCopy.addObject(mpObject);
         CCopasiVectorNS < CMetab > & Metabolites = mpCompartment->getMetabolites();
         CCopasiVectorNS < CMetab >::const_iterator itMetab;
         for (itMetab = Metabolites.begin(); itMetab != Metabolites.end(); ++itMetab)
           {
             compartmentObjectsToCopy.addMetab(*itMetab);
           }
       }
       success = true;
       break;
       case CQCompartmentCopyOptions::INTREAC:    //also include the internal reactions
       {
         compartmentObjectsToCopy.addObject(mpObject);
         // Get all the compartment's species first
         CCopasiVectorNS < CMetab > & Metabolites = mpCompartment->getMetabolites();
         CCopasiVectorNS < CMetab >::const_iterator itMetab;
         for (itMetab = Metabolites.begin(); itMetab != Metabolites.end(); ++itMetab)
           {
             compartmentObjectsToCopy.addMetab(*itMetab);
           }
         // Now get the reactions which are not multi-compartment
         CCopasiVectorN< CReaction >::const_iterator it = pModel->getReactions().begin();
         CCopasiVectorN< CReaction >::const_iterator end = pModel->getReactions().end();
         CReactionInterface * pRi = new CReactionInterface(pModel);
         for (; it != end; ++it)
           {
             pRi->initFromReaction((*it)->getKey());
             if (!pRi->isMulticompartment())
               {
                 if (pRi->getChemEqInterface().getCompartment()->getKey() == mKey)
                   compartmentObjectsToCopy.addReaction(*it);
               }
           }
         pdelete(pRi);
         success = true;
         break;
       }
       case CQCompartmentCopyOptions::ALLREAC:    //get everything in compartment
         compartmentObjectsToCopy.addObject(mpObject);
         compartmentObjectsToCopy.fillDependencies(pModel);
         success = true;
         break;
     }
   pdelete(pDialog);
   if (success)
     {
       cModelExpObj.duplicate(compartmentObjectsToCopy, "_copy", origToCopyMappings);
       protectedNotify(ListViews::COMPARTMENT, ListViews::DELETE, "");//Refresh all
       protectedNotify(ListViews::METABOLITE, ListViews::DELETE, ""); //Refresh all
       protectedNotify(ListViews::REACTION, ListViews::DELETE, "");   //Refresh all
       mpListView->switchToOtherWidget(C_INVALID_INDEX, origToCopyMappings.getDuplicateKey(mKey));
     }
 }
void CQCompartment::destroy () private
Definition at line 521 of file CQCompartment.cpp.
 {}
bool CQCompartment::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 330 of file CQCompartment.cpp.
References load(), mpCompartment, and CopasiWidget::mpObject.
 {
   mpCompartment = dynamic_cast< CCompartment * >(mpObject);
   load();
   return true;
 }
void CQCompartment::init () private
bool CQCompartment::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 339 of file CQCompartment.cpp.
References CModelEntity::FIXED, mItemToType, and save().
Referenced by slotBtnNew().
 {
   if ((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()] != CModelEntity::FIXED)
     {
       // -- Expression --
       mpExpressionEMW->updateWidget();
     }
   if (mpBoxUseInitialExpression->isChecked())
     {
       // -- Initial Expression --
       mpInitialExpressionEMW->updateWidget();
     }
   save();
   return true;
 }
void CQCompartment::load () private
Definition at line 380 of file CQCompartment.cpp.
References CModelEntity::ASSIGNMENT, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCompartment::getDimensionality(), CModelEntity::getExpression(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CCopasiObject::getObjectAncestor(), CModelEntity::getRate(), CModelEntity::getStatus(), CModelEntity::getValue(), CModel::getVolumeRateUnitsDisplayString(), CModel::getVolumeUnitsDisplayString(), loadMetaboliteTable(), mChanged, mpCompartment, slotTypeChanged(), and CModelEntity::StatusName.
Referenced by enterProtected(), and update().
 {
   if (mpCompartment == NULL) return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   const CModel * pModel = NULL;
   if (mpCompartment != NULL)
     pModel = dynamic_cast<const CModel *>(mpCompartment->getObjectAncestor("Model"));
   // Update the labels to reflect the model units
   QString ValueUnits;
   if (pModel)
     ValueUnits = FROM_UTF8(pModel->getVolumeUnitsDisplayString());
   if (!ValueUnits.isEmpty())
     ValueUnits = " (" + ValueUnits + ")";
   QString RateUnits;
   if (pModel)
     RateUnits = FROM_UTF8(pModel->getVolumeRateUnitsDisplayString());
   if (!RateUnits.isEmpty())
     RateUnits = " (" + RateUnits + ")";
   mpLblInitialValue->setText("Initial Volume" + ValueUnits);
   mpLblInitialExpression->setText("Initial Expression" + ValueUnits);
   mpLblVolume->setText("Volume" + ValueUnits);
   mpLblRate->setText("Rate" + RateUnits);
   //Dimensionality
   mpComboBoxDim->setCurrentIndex(mpCompartment->getDimensionality());
   //this assumes the indices of the entries in the combobox correspond 1to1 to the values of dimensionality
   // Simulation Type
   mpComboBoxType->setCurrentIndex(mpComboBoxType->findText(FROM_UTF8(CModelEntity::StatusName[mpCompartment->getStatus()])));
   // Initial Volume
   mpEditInitialVolume->setText(QString::number(mpCompartment->getInitialValue(), 'g', 10));
   // Transient Volume
   mpEditCurrentVolume->setText(QString::number(mpCompartment->getValue(), 'g', 10));
   // Concentration Rate
   mpEditRate->setText(QString::number(mpCompartment->getRate(), 'g', 10));
   // Expression
   mpExpressionEMW->mpExpressionWidget->setExpression(mpCompartment->getExpression());
   mpExpressionEMW->updateWidget();
   // Initial Expression
   mpInitialExpressionEMW->mpExpressionWidget->setExpression(mpCompartment->getInitialExpression());
   mpInitialExpressionEMW->updateWidget();
   // Type dependent display of values
   slotTypeChanged(mpComboBoxType->currentIndex());
   // Use Initial Expression
   if (mpCompartment->getStatus() == CModelEntity::ASSIGNMENT ||
       mpCompartment->getInitialExpression() == "")
     {
       mpBoxUseInitialExpression->setChecked(false);
     }
   else
     {
       mpBoxUseInitialExpression->setChecked(true);
     }
   loadMetaboliteTable();
   mChanged = false;
   return;
 }
void CQCompartment::loadMetaboliteTable () private
Definition at line 548 of file CQCompartment.cpp.
References FROM_UTF8, CCompartment::getMetabolites(), CCopasiContainer::getObjects(), mpCompartment, and CCopasiVector< T >::size().
Referenced by load().
 {
   if (mpCompartment == NULL) return;
   mpMetaboliteTable->setRowCount(mpCompartment->getMetabolites().size());
   CCopasiContainer::objectMap::const_iterator it =
     mpCompartment->getMetabolites().getObjects().begin();
   CCopasiContainer::objectMap::const_iterator end =
     mpCompartment->getMetabolites().getObjects().end();
   for (int i = 0; it != end; ++it)
     {
       if (dynamic_cast< CMetab * >(it->second) != NULL)
         {
           mpMetaboliteTable->setItem(i++, 0, new QTableWidgetItem(FROM_UTF8(it->second->getObjectName())));
         }
     }
   mpMetaboliteTable->resizeRowsToContents();
   return;
 }
void CQCompartment::save () private
Definition at line 457 of file CQCompartment.cpp.
References CModelEntity::ASSIGNMENT, C_INT32, ListViews::CHANGE, ListViews::COMPARTMENT, CCopasiRootContainer::getDatamodelList(), CCompartment::getDimensionality(), CModelEntity::getExpression(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CModelEntity::getStatus(), mChanged, mItemToType, CopasiWidget::mKey, mpCompartment, CopasiWidget::protectedNotify(), CCompartment::setDimensionality(), CModelEntity::setExpression(), CModelEntity::setInitialExpression(), CModelEntity::setInitialValue(), and CModelEntity::setStatus().
Referenced by leave().
 {
   if (mpCompartment == NULL) return;
 #ifdef COPASI_EXTUNIT
   //Dimensionality
   if ((C_INT32)mpCompartment->getDimensionality() != mpComboBoxDim->currentIndex()) //this makes assumptions about the order of entries in the combo box!
     {
       mpCompartment->setDimensionality(mpComboBoxDim->currentIndex());
       mChanged = true;
     }
 #endif
   // Type
   if (mpCompartment->getStatus() != (CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()])
     {
       mpCompartment->setStatus((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()]);
       mChanged = true;
     }
   // Initial Volume
   if (QString::number(mpCompartment->getInitialValue(), 'g', 10) != mpEditInitialVolume->text())
     {
       mpCompartment->setInitialValue(mpEditInitialVolume->text().toDouble());
       mChanged = true;
     }
   // Expression
   if (mpCompartment->getExpression() != mpExpressionEMW->mpExpressionWidget->getExpression())
     {
       mpCompartment->setExpression(mpExpressionEMW->mpExpressionWidget->getExpression());
       mChanged = true;
     }
   // Initial Expression
   if ((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()] != CModelEntity::ASSIGNMENT)
     {
       if (mpBoxUseInitialExpression->isChecked() &&
           mpCompartment->getInitialExpression() != mpInitialExpressionEMW->mpExpressionWidget->getExpression())
         {
           mpCompartment->setInitialExpression(mpInitialExpressionEMW->mpExpressionWidget->getExpression());
           mChanged = true;
         }
       else if (!mpBoxUseInitialExpression->isChecked() &&
                mpCompartment->getInitialExpression() != "")
         {
           mpCompartment->setInitialExpression("");
           mChanged = true;
         }
     }
   if (mChanged)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed();
       protectedNotify(ListViews::COMPARTMENT, ListViews::CHANGE, mKey);
     }
   mChanged = false;
 }
void CQCompartment::slotBtnCopy () inline private slot
Definition at line 58 of file CQCompartment.h.
 {}; //dummy, to bypass warnings from TabWidget connections
void CQCompartment::slotBtnDelete () private slot
Definition at line 196 of file CQCompartment.cpp.
References ListViews::COMPARTMENT, CQMessageBox::confirmDelete(), ListViews::DELETE, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCompartment::getDeletedObjects(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CopasiWidget::mKey, mpCompartment, CopasiWidget::protectedNotify(), and CModel::removeCompartment().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL) return;
   if (mpCompartment == NULL) return;
   QMessageBox::StandardButton choice =
     CQMessageBox::confirmDelete(this, "compartment",
                                 FROM_UTF8(mpCompartment->getObjectName()),
                                 mpCompartment->getDeletedObjects());
   switch (choice)
     {
       case QMessageBox::Ok:
       {
         pDataModel->getModel()->removeCompartment(mKey);
         protectedNotify(ListViews::COMPARTMENT, ListViews::DELETE, mKey);
         protectedNotify(ListViews::COMPARTMENT, ListViews::DELETE, ""); //Refresh all as there may be dependencies.
         break;
       }
       default:
         break;
     }
 }
void CQCompartment::slotBtnNew () private slot
Definition at line 81 of file CQCompartment.cpp.
References ListViews::ADD, C_INVALID_INDEX, ListViews::COMPARTMENT, CCopasiRootContainer::getDatamodelList(), CModelEntity::getKey(), leave(), mpCompartment, CopasiWidget::mpListView, CopasiWidget::protectedNotify(), ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   leave();
   std::string name = "compartment_1";
   int i = 1;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   while (!(mpCompartment = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->createCompartment(name)))
     {
       i++;
       name = "compartment_";
       name += TO_UTF8(QString::number(i));
     }
   std::string key = mpCompartment->getKey();
   protectedNotify(ListViews::COMPARTMENT, ListViews::ADD, key);
   mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQCompartment::slotExpressionValid (bool valid) private slot
Definition at line 320 of file CQCompartment.cpp.
References mExpressionValid.
 {
   mExpressionValid = valid;
 }
void CQCompartment::slotInitialExpressionValid (bool valid) private slot
Definition at line 325 of file CQCompartment.cpp.
References mInitialExpressionValid.
 {
   mInitialExpressionValid = valid;
 }
void CQCompartment::slotInitialTypeChanged (bool useInitialAssignment) private slot
This function is used in case of not FIXED type
Definition at line 298 of file CQCompartment.cpp.
References CModelEntity::ASSIGNMENT, and mItemToType.
Referenced by slotTypeChanged().
 {
   if (useInitialAssignment)
     {
       mpLblInitialExpression->show();
       mpInitialExpressionEMW->show();
       mpEditInitialVolume->setEnabled(false);
       mpInitialExpressionEMW->updateWidget();
     }
   else
     {
       mpLblInitialExpression->hide();
       mpInitialExpressionEMW->hide();
       mpEditInitialVolume->setEnabled((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()] != CModelEntity::ASSIGNMENT);
     }
 }
void CQCompartment::slotMetaboliteTableCurrentChanged (int row, int col) private slot
Definition at line 524 of file CQCompartment.cpp.
References C_INVALID_INDEX, CCompartment::getMetabolites(), CCopasiContainer::getObjects(), mpCompartment, CopasiWidget::mpListView, ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   if (mpCompartment == NULL) return;
   QTableWidgetItem * pItem = mpMetaboliteTable->item(row, col);
   std::string s1, s2;
   s1 = TO_UTF8(pItem->text());
   CCopasiContainer::objectMap::const_iterator it =
     mpCompartment->getMetabolites().getObjects().begin();
   CCopasiContainer::objectMap::const_iterator end =
     mpCompartment->getMetabolites().getObjects().end();
   for (; it != end; ++it)
     if (dynamic_cast< CMetab * >(it->second) != NULL)
       {
         s2 = it->second->getObjectName();
         if (s1 == s2)
           mpListView->switchToOtherWidget(C_INVALID_INDEX, it->second->getKey());
       }
 }
void CQCompartment::slotTypeChanged (int type) private slot
If the simulation type is changed then COPASI will automatically adjust its appearance, especially correlating to the Expression Widget and its buttons.
Definition at line 232 of file CQCompartment.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, FROM_UTF8, CCopasiObject::getObjectAncestor(), CModel::getVolumeRateUnitsDisplayString(), CModel::getVolumeUnitsDisplayString(), mItemToType, mpCompartment, CModelEntity::ODE, and slotInitialTypeChanged().
Referenced by load().
 {
   QString Units;
   const CModel * pModel = NULL;
   if (mpCompartment != NULL)
     pModel = dynamic_cast<const CModel *>(mpCompartment->getObjectAncestor("Model"));
   switch ((CModelEntity::Status) mItemToType[type])
     {
       case CModelEntity::FIXED:
         mpLblExpression->hide();
         mpExpressionEMW->hide();
         mpBoxUseInitialExpression->setEnabled(true);
         slotInitialTypeChanged(mpBoxUseInitialExpression->isChecked());
         break;
       case CModelEntity::ASSIGNMENT:
         if (pModel)
           Units = FROM_UTF8(pModel->getVolumeUnitsDisplayString());
         if (!Units.isEmpty())
           Units = " (" + Units + ")";
         mpLblExpression->setText("Expression" + Units);
         mpLblExpression->show();
         mpExpressionEMW->show();
         mpBoxUseInitialExpression->setEnabled(false);
         slotInitialTypeChanged(false);
         mpExpressionEMW->updateWidget();
         break;
       case CModelEntity::ODE:
         if (pModel)
           Units = FROM_UTF8(pModel->getVolumeRateUnitsDisplayString());
         if (!Units.isEmpty())
           Units = " (" + Units + ")";
         mpLblExpression->setText("Expression" + Units);
         mpLblExpression->show();
         mpExpressionEMW->show();
         mpBoxUseInitialExpression->setEnabled(true);
         slotInitialTypeChanged(mpBoxUseInitialExpression->isChecked());
         mpExpressionEMW->updateWidget();
         break;
       default:
         break;
     }
 }
bool CQCompartment::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 358 of file CQCompartment.cpp.
References ListViews::COMPARTMENT, load(), ListViews::METABOLITE, CopasiWidget::mIgnoreUpdates, ListViews::MODEL, and ListViews::STATE.
 {
   if (!isVisible() || mIgnoreUpdates) return true;
   switch (objectType)
     {
       case ListViews::STATE:
       case ListViews::MODEL:
       case ListViews::METABOLITE:
       case ListViews::COMPARTMENT:
         load();
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
bool CQCompartment::mChanged private
Definition at line 46 of file CQCompartment.h.
Referenced by load(), and save().
bool CQCompartment::mExpressionValid private
Definition at line 47 of file CQCompartment.h.
Referenced by CQCompartment(), and slotExpressionValid().
bool CQCompartment::mInitialExpressionValid private
Definition at line 48 of file CQCompartment.h.
Referenced by CQCompartment(), and slotInitialExpressionValid().
std::vector< int > CQCompartment::mItemToType private
Definition at line 44 of file CQCompartment.h.
Referenced by CQCompartment(), leave(), save(), slotInitialTypeChanged(), and slotTypeChanged().
CCompartment* CQCompartment::mpCompartment private
Definition at line 45 of file CQCompartment.h.
Referenced by copy(), enterProtected(), load(), loadMetaboliteTable(), save(), slotBtnDelete(), slotBtnNew(), slotMetaboliteTableCurrentChanged(), and slotTypeChanged().
The documentation for this class was generated from the following files:
CQCompartment.h
CQCompartment.cpp