COPASI API: CMathExpression Class Reference
CMathExpression Class Reference
#include <CMathExpression.h>
Public Member Functions
CMathExpression (const std::string &name, CMathContainer &container)
CMathExpression (const CExpression &src, CMathContainer &container, const bool &replaceDiscontinuousNodes)
CMathExpression (const CFunction &src, const CCallParameters< C_FLOAT64 > &callParameters, CMathContainer &container, const bool &replaceDiscontinuousNodes)
virtual bool compile ()
bool convertToInitialExpression ()
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
const C_FLOAT64 & value ()
virtual ~CMathExpression ()
Public Member Functions inherited from CEvaluationTree
bool calls (std::set< std::string > &list) const
CEvaluationTree (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=Function)
CEvaluationTree (const CEvaluationTree &src, const CCopasiContainer *pParent=NULL)
bool dependsOnTree (const std::string &name) const
CCopasiObject::DataObjectSet getDeletedObjects () const
std::string::size_type getErrorPosition () const
const std::string & getInfix () const
const std::vector
< CEvaluationNode * > & getNodeList () const
CEvaluationNode * getRoot ()
const CEvaluationNode * getRoot () const
const CEvaluationTree::Type & getType () const
virtual size_t getVariableIndex (const std::string &name) const
virtual const C_FLOAT64 & getVariableValue (const size_t &index) const
bool hasCircularDependency () const
bool hasDiscontinuity () const
bool isBoolean () const
bool isUsable () const
bool operator== (const CEvaluationTree &rhs) const
virtual bool setInfix (const std::string &infix)
bool setTree (const ASTNode &pRootNode)
virtual ASTNode * toAST (const CCopasiDataModel *pDataModel) const
bool updateTree ()
virtual ~CEvaluationTree ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CMathExpression * copy (const CMathExpression &src, CMathContainer &container, const size_t &valueOffset, const size_t &objectOffset)
Static Public Member Functions inherited from CEvaluationTree
static CEvaluationTree * copy (const CEvaluationTree &src)
static CEvaluationTree * create (CEvaluationTree::Type type)
static CEvaluationNode * fromAST (const ASTNode *pASTNode)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Private Member Functions
CMathExpression ()
CEvaluationNode * createMassActionPart (const C_FLOAT64 *pK, const CCallParameters< C_FLOAT64 > *pSpecies)
CEvaluationNode * createNodeFromValue (const C_FLOAT64 *pDataValue)
virtual bool setRoot (CEvaluationNode *pRootNode)
Private Attributes
CObjectInterface::ObjectSet mPrerequisites
Additional Inherited Members
Public Types inherited from CEvaluationTree
enum Type {
Function = 0, MassAction, PreDefined, UserDefined,
Expression, MathExpression
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CEvaluationTree
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CEvaluationTree
void buildCalculationSequence ()
void calculate ()
bool compileNodes ()
bool parse ()
void setType (const CEvaluationTree::Type &type)
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CEvaluationTree
std::vector< CEvaluationNode * > mCalculationSequence
std::string mInfix
std::vector< CEvaluationNode * > * mpNodeList
CEvaluationNode * mpRoot
CEvaluationTree::Type mType
bool mUsable
C_FLOAT64 mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 20 of file CMathExpression.h.
Constructor & Destructor Documentation
CMathExpression::CMathExpression () private
Hidden default constructor
Definition at line 20 of file CMathExpression.cpp.
Referenced by copy().
                                 :
   CEvaluationTree(),
   mPrerequisites()
 {}
CMathExpression::CMathExpression (const std::string & name, CMathContainer & container)
Specific constructor.
Parameters
const std::string & name
CMathContainer & container
Definition at line 25 of file CMathExpression.cpp.
                                                             :
   CEvaluationTree(name, &container, CEvaluationTree::MathExpression),
   mPrerequisites()
 {}
CMathExpression::CMathExpression (const CExpression & src, CMathContainer & container, const bool & replaceDiscontinuousNodes)
Specific constructor. The src expression must have been successfully compiled in the context of the current model
Parameters
const CExpression & src
CMathContainer & container
const bool & replaceDiscontinuousNodes
Definition at line 31 of file CMathExpression.cpp.
References compile(), CMathContainer::copyBranch(), CEvaluationTree::getRoot(), and CEvaluationTree::mpRoot.
                                                                         :
   CEvaluationTree(src.getObjectName(), &container, CEvaluationTree::MathExpression),
   mPrerequisites()
 {
   // Create a converted copy of the existing expression tree.
   mpRoot = container.copyBranch(src.getRoot(), replaceDiscontinuousNodes);
   compile();
 }
CMathExpression::CMathExpression (const CFunction & src, const CCallParameters< C_FLOAT64 > & callParameters, CMathContainer & container, const bool & replaceDiscontinuousNodes)
Specific constructor. The src function must have been successfully compiled in the context of the current model
Parameters
const CFunction & src
const CCallParameters< C_FLOAT64 > & callParameters
CMathContainer & container
const bool & replaceDiscontinuousNodes
Definition at line 43 of file CMathExpression.cpp.
References CCopasiNode< _Data >::addChild(), CCallParameters< Type >::begin(), C_FLOAT64, compile(), CMathContainer::copyBranch(), createMassActionPart(), createNodeFromValue(), CCallParameters< Type >::end(), CEvaluationTree::Expression, CEvaluationTree::Function, CEvaluationTree::getRoot(), CEvaluationTree::getType(), CEvaluationTree::MassAction, CEvaluationTree::MathExpression, CEvaluationNodeOperator::MINUS, CEvaluationTree::mpRoot, CEvaluationTree::PreDefined, and CEvaluationTree::UserDefined.
                                                                         :
   CEvaluationTree(src.getObjectName(), &container, CEvaluationTree::MathExpression),
   mPrerequisites()
 {
   // Deal with the different function types
   switch (src.getType())
     {
       case CEvaluationTree::Function:
       case CEvaluationTree::PreDefined:
       case CEvaluationTree::UserDefined:
       {
         // Create a vector of CEvaluationNodeObject for each variable
         CMath::Variables< CEvaluationNode * > Variables;
         CCallParameters< C_FLOAT64 >::const_iterator it = callParameters.begin();
         CCallParameters< C_FLOAT64 >::const_iterator end = callParameters.end();
         for (; it != end; ++it)
           {
             Variables.push_back(createNodeFromValue(it->value));
           }
         // Create a converted copy of the existing expression tree.
         mpRoot = container.copyBranch(src.getRoot(), Variables, replaceDiscontinuousNodes);
       }
       break;
       case CEvaluationTree::MassAction:
       {
         // We build a mass action expression based on the call parameters.
         CCallParameters< C_FLOAT64 >::const_iterator it = callParameters.begin();
         // We always have reactants
         const C_FLOAT64 * pK = it->value;
         ++it;
         const CCallParameters< C_FLOAT64 > * pSpecies = it->vector;
         ++it;
         CEvaluationNode * pPart = createMassActionPart(pK, pSpecies);
         if (it != callParameters.end())
           {
             mpRoot = new CEvaluationNodeOperator(CEvaluationNodeOperator::MINUS, "-");
             mpRoot->addChild(pPart);
             pK = it->value;
             ++it;
             pSpecies = it->vector;
             ++it;
             pPart = createMassActionPart(pK, pSpecies);
             mpRoot->addChild(pPart);
           }
         else
           {
             mpRoot = pPart;
           }
       }
       break;
       case CEvaluationTree::MathExpression:
       case CEvaluationTree::Expression:
         // This cannot happen and is only here to satisfy the compiler.
         break;
     }
   compile();
 }
CMathExpression::~CMathExpression () virtual
Destructor
Definition at line 118 of file CMathExpression.cpp.
 {}
Member Function Documentation
bool CMathExpression::compile () virtual
Compile the evaluation tree.
Reimplemented from CEvaluationTree.
Definition at line 163 of file CMathExpression.cpp.
References CEvaluationTree::buildCalculationSequence(), C_FLOAT64, CEvaluationTree::mCalculationSequence, CEvaluationTree::mInfix, mpContainer, CEvaluationTree::mpNodeList, mPrerequisites, CEvaluationTree::mUsable, CEvaluationNode::OBJECT, CEvaluationNodeObject::POINTER, stringToPointer(), and CEvaluationTree::updateTree().
Referenced by CMathExpression(), copy(), and CMathObject::setExpressionPtr().
 {
   mPrerequisites.clear();
   mUsable = true;
   if (!updateTree())
     {
       mUsable = false;
       mCalculationSequence.clear();
       return mUsable;
     }
   std::vector< CEvaluationNode * >::iterator it = mpNodeList->begin();
   std::vector< CEvaluationNode * >::iterator end = mpNodeList->end();
   for (; it != end; ++it)
     {
       mUsable &= (*it)->compile(this);
       if ((*it)->getType() == (CEvaluationNode::OBJECT | CEvaluationNodeObject::POINTER))
         {
           void * pValue = stringToPointer((*it)->getData());
           // TODO CRITICAL It is possible that the user selects non model objects, i.e.,
           // problem or method values within the expression. These cannot be mapped to a
           // math objects and therefore dependencies will be broken.
           CMathObject * pMathObject = mpContainer->getMathObject((C_FLOAT64 *) pValue);
           if (pMathObject != NULL)
             {
               mPrerequisites.insert(pMathObject);
             }
           else
             {
               // For the moment we stop.
               assert(false);
             }
         }
     }
   if (mInfix == "@")
     {
       mUsable = true;
     }
   buildCalculationSequence();
   return mUsable;
 }
bool CMathExpression::convertToInitialExpression ()
Convert to a corresponding initial expression.
Returns
bool success
Definition at line 215 of file CMathExpression.cpp.
References CEvaluationNode::buildInfix(), C_FLOAT64, CCopasiObject::getObjectName(), CEvaluationNodeObject::getObjectValuePtr(), CEvaluationTree::mInfix, mpContainer, CEvaluationTree::mpNodeList, mPrerequisites, CEvaluationTree::mpRoot, CEvaluationNode::OBJECT, CEvaluationNodeObject::POINTER, CCopasiObject::setObjectName(), and CEvaluationNodeObject::setObjectValuePtr().
Referenced by CMathObject::compileExpression().
 {
   if (getObjectName().substr(0, 7) != "Initial")
     {
       setObjectName("Initial" + getObjectName());
     }
   if (mpNodeList == NULL)
     {
       return false;
     }
   std::vector< CEvaluationNode * >::iterator it = mpNodeList->begin();
   std::vector< CEvaluationNode * >::iterator end = mpNodeList->end();
   bool changed = false;
   for (; it != end; ++it)
     {
       if ((*it)->getType() == (CEvaluationNode::OBJECT | CEvaluationNodeObject::POINTER))
         {
           CEvaluationNodeObject * pNode = static_cast< CEvaluationNodeObject *>(*it);
           const C_FLOAT64 * pValue = pNode->getObjectValuePtr();
           C_FLOAT64 * pInitialValue = mpContainer->getInitialValuePointer(pValue);
           if (pValue != pInitialValue)
             {
               changed = true;
               pNode->setObjectValuePtr(pInitialValue);
               mPrerequisites.erase(mpContainer->getMathObject(pValue));
               mPrerequisites.insert(mpContainer->getMathObject(pInitialValue));
             }
         }
     }
   if (changed)
     {
       mInfix = mpRoot->buildInfix();
     }
   return true;
 }
CMathExpression * CMathExpression::copy (const CMathExpression & src, CMathContainer & container, const size_t & valueOffset, const size_t & objectOffset) static
Copy an expression with the given offsets
Parameters
const CMathExpression & src
CMathContainer & container
const size_t & valueOffset
const size_t & objectOffset
Definition at line 122 of file CMathExpression.cpp.
References C_FLOAT64, CMathExpression(), compile(), CEvaluationNode::copyBranch(), CCopasiObject::getObjectName(), CEvaluationTree::getRoot(), CEvaluationNode::OBJECT, CEvaluationNodeObject::POINTER, setRoot(), and stringToPointer().
Referenced by CMathObject::copy().
 {
   CMathExpression * pExpression = new CMathExpression(src.getObjectName(), container);
   pExpression->setRoot(src.getRoot()->copyBranch());
   // Apply the offset to all nodes
   CCopasiTree<CEvaluationNode>::iterator it = pExpression->getRoot();
   CCopasiTree<CEvaluationNode>::iterator end = NULL;
   for (; it != end; ++it)
     {
       if (it->getType() == (CEvaluationNode::OBJECT | CEvaluationNodeObject::POINTER))
         {
           C_FLOAT64 * pPointer = (C_FLOAT64 *) stringToPointer(it->getData());
           static_cast< CEvaluationNodeObject * >(&*it)->setObjectValuePtr((C_FLOAT64 *)((size_t) pPointer + valueOffset));
         }
     }
   pExpression->compile();
   return pExpression;
 }
CEvaluationNode * CMathExpression::createMassActionPart (const C_FLOAT64 * pK, const CCallParameters< C_FLOAT64 > * pSpecies) private
Create a part of Mass Action kinetics
Parameters
const C_FLOAT64 * pK
const CCallParameters< C_FLOAT64 > * pSpecies
Returns
CEvaluationNode * massActionPart
Definition at line 291 of file CMathExpression.cpp.
References CCopasiNode< _Data >::addChild(), CCallParameters< Type >::begin(), createNodeFromValue(), CCallParameters< Type >::end(), and CEvaluationNodeOperator::MULTIPLY.
Referenced by CMathExpression().
 {
   CEvaluationNode * pPart = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
   pPart->addChild(createNodeFromValue(pK));
   CEvaluationNode * pNode = pPart;
   CCallParameters< C_FLOAT64 >::const_iterator itSpecies = pSpecies->begin();
   CCallParameters< C_FLOAT64 >::const_iterator endSpecies = pSpecies->end();
   for (; itSpecies != endSpecies - 1; ++itSpecies)
     {
       CEvaluationNode * p = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
       p->addChild(createNodeFromValue(itSpecies->value));
       pNode->addChild(p);
       pNode = p;
     }
   pNode->addChild(createNodeFromValue(itSpecies->value));
   return pPart;
 }
CEvaluationNode * CMathExpression::createNodeFromValue (const C_FLOAT64 * pDataValue) private
Create a node based on the given pointer to a data value
Parameters
const C_FLOAT64 * pDataValue
Returns
CEvaluationNode * pNode
Definition at line 263 of file CMathExpression.cpp.
References CEvaluationNodeConstant::_NaN, C_FLOAT64, CMathObject::getValuePointer(), and mpContainer.
Referenced by CMathExpression(), and createMassActionPart().
 {
   CEvaluationNode * pNode = NULL;
   CMathObject * pMathObject = NULL;
   if (pDataValue != NULL)
     {
       pMathObject = mpContainer->getMathObject(pDataValue);
       if (pMathObject != NULL)
         {
           pNode = new CEvaluationNodeObject((C_FLOAT64 *) pMathObject->getValuePointer());
         }
       else
         {
           // We must have a constant value like the conversion factor from the model.
           pNode = new CEvaluationNodeNumber(*pDataValue);
         }
     }
   else
     {
       // We have an invalid value, i.e. NaN
       pNode = new CEvaluationNodeConstant(CEvaluationNodeConstant::_NaN, "NAN");
     }
   return pNode;
 }
const CObjectInterface::ObjectSet & CMathExpression::getPrerequisites () const virtual
Retrieve the prerequisites, i.e., the objects which need to be evaluated before this.
Returns
const CObjectInterface::ObjectSet & prerequisites
Reimplemented from CCopasiObject.
Definition at line 157 of file CMathExpression.cpp.
References mPrerequisites.
Referenced by CMathObject::compileExpression().
 {
   return mPrerequisites;
 }
bool CMathExpression::setRoot (CEvaluationNode * pRootNode) private virtual
Sets the root node of the tree. Note: This is private to assure that only valid root node representing mathematical expressions are set.
Parameters
CEvaluationNode* root node of the tree
Returns
bool success
Reimplemented from CEvaluationTree.
Definition at line 258 of file CMathExpression.cpp.
References CEvaluationTree::setRoot().
Referenced by copy().
 {
   return CEvaluationTree::setRoot(pRootNode);
 }
const C_FLOAT64 & CMathExpression::value ()
Evaluate the expression
Returns
const C_FLOAT64 & value
Definition at line 149 of file CMathExpression.cpp.
References CEvaluationTree::calculate(), and CEvaluationTree::mValue.
Referenced by CMathObject::calculate().
 {
   calculate();
   return mValue;
 }
Member Data Documentation
CObjectInterface::ObjectSet CMathExpression::mPrerequisites private
The prerequisites for calculating the expression.
Definition at line 132 of file CMathExpression.h.
Referenced by compile(), convertToInitialExpression(), and getPrerequisites().
The documentation for this class was generated from the following files:
CMathExpression.h
CMathExpression.cpp