COPASI API: CMiaseSed Class Reference
CMiaseSed Class Reference
#include <CMiaseML.h>
Public Member Functions
void addModel (CMiaseModel *model)
void addOutput (CMiaseOutput *output)
void addSimulation (CMiaseSimulation *simulation)
void addTask (CMiaseTask *task)
CMiaseSed ()
CMiaseModel * getLastModel ()
CMiaseOutput * getLastOutput ()
CMiaseSimulation * getLastSimulation ()
CMiaseTask * getLastTask ()
CMiaseModel * getModel (int num)
CMiaseModel * getModel (std::string id)
int getNumOfModels ()
int getNumOfOutputs ()
int getNumOfSimulations ()
int getNumOfTasks ()
CMiaseOutput * getOutput (int num)
CMiaseOutput * getOutput (std::string id)
CMiaseSimulation * getSimulation (int num)
CMiaseSimulation * getSimulation (std::string id)
CMiaseTask * getTask (int num)
CMiaseTask * getTask (std::string id)
~CMiaseSed ()
Public Member Functions inherited from CMiaseBase
void addAnnotation (CMiaseAnnotation *ann)
void addNotes (CMiaseNotes *notes)
CMiaseBase ()
CMiaseAnnotation * getAnnotation ()
std::string getMetaId ()
CMiaseNotes * getNotes ()
void setAnyNote (std::string anyAnnotation)
void setMetaId (std::string metaId)
void setXmlNs (std::string xmlNs)
~CMiaseBase ()
Private Attributes
std::vector< CMiaseModel * > mListofModels
std::vector< CMiaseOutput * > mListofOutputs
std::vector< CMiaseSimulation * > mListofSimulations
std::vector< CMiaseTask * > mListofTasks
Detailed Description
Definition at line 23 of file CMiaseML.h.
Constructor & Destructor Documentation
CMiaseSed::CMiaseSed ()
Definition at line 17 of file CMiaseML.cpp.
                      : CMiaseBase()
 {}
CMiaseSed::~CMiaseSed ()
Definition at line 20 of file CMiaseML.cpp.
 {
   //TODO:
   //delete content of following vectors:  mListofSimulations, mListofTasks,
   //                                      mListofModels, mListofOutputs
 }
Member Function Documentation
void CMiaseSed::addModel (CMiaseModel * model)
Definition at line 37 of file CMiaseML.cpp.
References mListofModels.
Referenced by CMiaseParser::newModel().
 {
   mListofModels.push_back(model);
 }
void CMiaseSed::addOutput (CMiaseOutput * output)
Definition at line 42 of file CMiaseML.cpp.
References mListofOutputs.
Referenced by CMiaseParser::newOutput().
 {
   mListofOutputs.push_back(output);
 }
void CMiaseSed::addSimulation (CMiaseSimulation * simulation)
Definition at line 27 of file CMiaseML.cpp.
References mListofSimulations.
Referenced by CMiaseParser::newSimulation().
 {
   mListofSimulations.push_back(simulation);
 }
void CMiaseSed::addTask (CMiaseTask * task)
Definition at line 32 of file CMiaseML.cpp.
References mListofTasks.
Referenced by CMiaseParser::newTask().
 {
   mListofTasks.push_back(task);
 }
CMiaseModel * CMiaseSed::getLastModel ()
Definition at line 118 of file CMiaseML.cpp.
References mListofModels.
Referenced by CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newChange(), CMiaseParser::newModel(), and CMiaseParser::newNotes().
 {
   return mListofModels[ mListofModels.size() - 1 ];
 }
CMiaseOutput * CMiaseSed::getLastOutput ()
Definition at line 145 of file CMiaseML.cpp.
References mListofOutputs.
Referenced by CMiaseParser::endElement(), CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newNotes(), and CMiaseParser::newOutput().
 {
   return mListofOutputs[ mListofOutputs.size() - 1 ];
 }
CMiaseSimulation * CMiaseSed::getLastSimulation ()
Definition at line 64 of file CMiaseML.cpp.
References mListofSimulations.
Referenced by CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newNotes(), and CMiaseParser::newSimulation().
 {
   return mListofSimulations[ mListofSimulations.size() - 1 ];
 }
CMiaseTask * CMiaseSed::getLastTask ()
Definition at line 91 of file CMiaseML.cpp.
References mListofTasks.
Referenced by CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newMeasurementData(), CMiaseParser::newNotes(), and CMiaseParser::newTask().
 {
   return mListofTasks[ mListofTasks.size() - 1 ];
 }
CMiaseModel * CMiaseSed::getModel (int num)
Definition at line 101 of file CMiaseML.cpp.
References mListofModels.
Referenced by getModel(), and CMiaseParser::testDataStructure().
 {
   return mListofModels[ num ];
 }
CMiaseModel * CMiaseSed::getModel (std::string id)
Definition at line 106 of file CMiaseML.cpp.
References CMiaseBaseEnhanced::getId(), getModel(), and getNumOfModels().
 {
   int i;
   CMiaseModel* tmp;
   for (i = 0 ; i <= getNumOfModels() ; i++)
     {
       tmp = getModel(i);
       if (tmp->getId() == id)
         return tmp;
     }
 }
int CMiaseSed::getNumOfModels ()
Definition at line 123 of file CMiaseML.cpp.
References mListofModels.
Referenced by getModel(), and CMiaseParser::testDataStructure().
 {
   return mListofModels.size();
 }
int CMiaseSed::getNumOfOutputs ()
Definition at line 150 of file CMiaseML.cpp.
References mListofOutputs.
Referenced by getOutput(), and CMiaseParser::testDataStructure().
 {
   return mListofOutputs.size();
 }
int CMiaseSed::getNumOfSimulations ()
Definition at line 69 of file CMiaseML.cpp.
References mListofSimulations.
Referenced by getSimulation(), and CMiaseParser::testDataStructure().
 {
   return mListofSimulations.size();
 }
int CMiaseSed::getNumOfTasks ()
Definition at line 96 of file CMiaseML.cpp.
References mListofTasks.
Referenced by getTask(), and CMiaseParser::testDataStructure().
 {
   return mListofTasks.size();
 }
CMiaseOutput * CMiaseSed::getOutput (int num)
Definition at line 128 of file CMiaseML.cpp.
References mListofOutputs.
Referenced by getOutput(), and CMiaseParser::testDataStructure().
 {
   return mListofOutputs[ num ];
 }
CMiaseOutput * CMiaseSed::getOutput (std::string id)
Definition at line 133 of file CMiaseML.cpp.
References CMiaseBaseEnhanced::getId(), getNumOfOutputs(), and getOutput().
 {
   int i;
   CMiaseOutput* tmp;
   for (i = 0 ; i <= getNumOfOutputs() ; i++)
     {
       tmp = getOutput(i);
       if (tmp->getId() == id)
         return tmp;
     }
 }
CMiaseSimulation * CMiaseSed::getSimulation (int num)
Definition at line 47 of file CMiaseML.cpp.
References mListofSimulations.
Referenced by getSimulation(), and CMiaseParser::testDataStructure().
 {
   return mListofSimulations[ num ];
 }
CMiaseSimulation * CMiaseSed::getSimulation (std::string id)
Definition at line 52 of file CMiaseML.cpp.
References CMiaseBaseEnhanced::getId(), getNumOfSimulations(), and getSimulation().
 {
   int i;
   CMiaseSimulation* tmp;
   for (i = 0 ; i <= getNumOfSimulations() ; i++)
     {
       tmp = getSimulation(i);
       if (tmp->getId() == id)
         return tmp;
     }
 }
CMiaseTask * CMiaseSed::getTask (int num)
Definition at line 74 of file CMiaseML.cpp.
References mListofTasks.
Referenced by getTask(), and CMiaseParser::testDataStructure().
 {
   return mListofTasks[ num ];
 }
CMiaseTask * CMiaseSed::getTask (std::string id)
Definition at line 79 of file CMiaseML.cpp.
References CMiaseBaseEnhanced::getId(), getNumOfTasks(), and getTask().
 {
   int i;
   CMiaseTask* tmp;
   for (i = 0 ; i <= getNumOfTasks() ; i++)
     {
       tmp = getTask(i);
       if (tmp->getId() == id)
         return tmp;
     }
 }
Member Data Documentation
std::vector< CMiaseModel* > CMiaseSed::mListofModels private
Definition at line 60 of file CMiaseML.h.
Referenced by addModel(), getLastModel(), getModel(), and getNumOfModels().
std::vector< CMiaseOutput* > CMiaseSed::mListofOutputs private
Definition at line 61 of file CMiaseML.h.
Referenced by addOutput(), getLastOutput(), getNumOfOutputs(), and getOutput().
std::vector< CMiaseSimulation* > CMiaseSed::mListofSimulations private
Definition at line 58 of file CMiaseML.h.
Referenced by addSimulation(), getLastSimulation(), getNumOfSimulations(), and getSimulation().
std::vector< CMiaseTask* > CMiaseSed::mListofTasks private
Definition at line 59 of file CMiaseML.h.
Referenced by addTask(), getLastTask(), getNumOfTasks(), and getTask().
The documentation for this class was generated from the following files:
CMiaseML.h
CMiaseML.cpp