COPASI API: CEFMMethod Class Reference
CEFMMethod Class Reference
#include <CEFMMethod.h>
Public Member Functions
virtual bool calculate ()
CEFMMethod (const CEFMMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool initialize ()
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual ~CEFMMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CEFMMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::EFMAlgorithm)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
CEFMMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
std::vector< CFluxMode > * mpFluxModes
std::vector< const CReaction * > * mpReorderedReactions
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CEFMMethod ()
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 25 of file CEFMMethod.h.
Constructor & Destructor Documentation
CEFMMethod::CEFMMethod () private
Default constructor.
Definition at line 80 of file CEFMMethod.cpp.
References CONSTRUCTOR_TRACE.
                       :
     CCopasiMethod(CCopasiTask::fluxMode, CCopasiMethod::unset),
     mpFluxModes(NULL),
     mpReorderedReactions(NULL)
 {CONSTRUCTOR_TRACE;}
CEFMMethod::CEFMMethod (const CCopasiTask::Type & taskType, const SubType & subType, const CCopasiContainer * pParent = NULL) protected
Specific constructor
Parameters
const CCopasiTask::Type & type
const CCopasiMethod::SubType & subType
const CCopasiContainer * pParent (default: NULL)
Definition at line 86 of file CEFMMethod.cpp.
References CONSTRUCTOR_TRACE.
                                                         :
     CCopasiMethod(taskType, subType, pParent),
     mpFluxModes(NULL),
     mpReorderedReactions(NULL)
 {CONSTRUCTOR_TRACE;}
CEFMMethod::CEFMMethod (const CEFMMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CEFMMethod & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 94 of file CEFMMethod.cpp.
References CONSTRUCTOR_TRACE.
                                                         :
     CCopasiMethod(src, pParent),
     mpFluxModes(src.mpFluxModes),
     mpReorderedReactions(src.mpReorderedReactions)
 {CONSTRUCTOR_TRACE;}
CEFMMethod::~CEFMMethod () virtual
Destructor
Definition at line 101 of file CEFMMethod.cpp.
 {}
Member Function Documentation
bool CEFMMethod::calculate (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback. @ return success;
Reimplemented in CBitPatternTreeMethod, CBitPatternMethod, CEFMAlgorithm, and CSSAMethod.
Definition at line 104 of file CEFMMethod.cpp.
 {
   return false;
 }
CEFMMethod * CEFMMethod::createMethod (CCopasiMethod::SubType subType = CCopasiMethod::EFMAlgorithm) static
Create a EFM method. Note: the returned object has to be released after use with delete
CEFMMethod class This class describes the interface to all optimization methods. The various method like RandomSearch or GA have to be derived from this class.
Created for COPASI by Stefan Hoops 2002
Definition at line 47 of file CEFMMethod.cpp.
References CCopasiMethod::EFMAlgorithm, CCopasiMethod::EFMBitPatternAlgorithm, and CCopasiMethod::EFMBitPatternTreeAlgorithm.
Referenced by CEFMTask::CEFMTask(), and CEFMTask::createMethod().
 {
   CEFMMethod * pMethod = NULL;
   switch (subType)
     {
       case EFMAlgorithm:
         pMethod = new CEFMAlgorithm();
         break;
       case EFMBitPatternTreeAlgorithm:
         pMethod = new CBitPatternTreeMethod();
         break;
       case EFMBitPatternAlgorithm:
         pMethod = new CBitPatternMethod();
         break;
 #ifdef COPASI_SSA
       case stoichiometricStabilityAnalysis:
         pMethod = new CSSAMethod();
         break;
 #endif
       default:
         pMethod = new CEFMAlgorithm();
         break;
     }
   return pMethod;
 }
bool CEFMMethod::initialize () virtual
Initialize arrays and pointer.
Returns
bool success
Reimplemented in CBitPatternTreeMethod, CBitPatternMethod, CEFMAlgorithm, and CSSAMethod.
Definition at line 109 of file CEFMMethod.cpp.
References CCopasiMessage::ERROR, CEFMProblem::getFluxModes(), CCopasiObject::getObjectParent(), CCopasiTask::getProblem(), CEFMProblem::getReorderedReactions(), MCEFMAnalysis, mpFluxModes, mpReorderedReactions, and pTask.
Referenced by CEFMAlgorithm::initialize(), CBitPatternMethod::initialize(), and CBitPatternTreeMethod::initialize().
 {
   CEFMTask * pTask = dynamic_cast< CEFMTask * >(getObjectParent());
   if (pTask == NULL)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCEFMAnalysis + 1);
       return false;
     }
   CEFMProblem * pProblem = dynamic_cast< CEFMProblem *>(pTask->getProblem());
   if (pProblem == NULL)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCEFMAnalysis + 2);
       return false;
     }
   mpFluxModes = & pProblem->getFluxModes();
   mpReorderedReactions = & pProblem->getReorderedReactions();
   mpReorderedReactions->clear();
   mpFluxModes->clear();
   return true;
 }
bool CEFMMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
Definition at line 136 of file CEFMMethod.cpp.
References CMatrix< CType >::array(), C_FLOAT64, CCopasiMessage::ERROR, CCopasiProblem::getModel(), CCopasiObject::getObjectName(), CModel::getReactions(), CModel::getRedStoi(), CCopasiMethod::isValidProblem(), MCEFMAnalysis, CMatrix< CType >::numCols(), and CMatrix< CType >::size().
 {
   if (!CCopasiMethod::isValidProblem(pProblem)) return false;
   if (pProblem == NULL)
     {
       return false;
     }
   const CModel * pModel = pProblem ->getModel();
   if (pModel == NULL)
     {
       return false;
     }
   // Check that the stoichiometry matrix contains only integers.
   const CMatrix< C_FLOAT64 > & RedStoi = pModel->getRedStoi();
   const C_FLOAT64 * pValue = RedStoi.array();
   const C_FLOAT64 * pValueEnd = pValue + RedStoi.size();
   for (; pValue != pValueEnd; ++pValue)
     {
       if (fabs(*pValue - floor(*pValue + 0.5)) > 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon())
         {
           break;
         }
     }
   if (pValue != pValueEnd)
     {
       const CReaction * pReaction = pModel->getReactions()[(pValue - RedStoi.array()) % RedStoi.numCols()];
       CCopasiMessage(CCopasiMessage::ERROR, MCEFMAnalysis + 3, pReaction->getObjectName().c_str());
       return false;
     }
   return true;
 }
Member Data Documentation
std::vector< CFluxMode >* CEFMMethod::mpFluxModes protected
The resulting elementary flux modes
Definition at line 91 of file CEFMMethod.h.
Referenced by CBitPatternTreeMethod::addMode(), CBitPatternMethod::addMode(), CEFMAlgorithm::buildFluxModes(), initialize(), and CEFMAlgorithm::initialize().
std::vector< const CReaction * >* CEFMMethod::mpReorderedReactions protected
Reactions in the order used in the analysis
Definition at line 96 of file CEFMMethod.h.
Referenced by CBitPatternTreeMethod::buildFluxModes(), CBitPatternMethod::buildFluxModes(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), initialize(), and CEFMAlgorithm::initialize().
The documentation for this class was generated from the following files:
CEFMMethod.h
CEFMMethod.cpp