COPASI API: test000082 Class Reference
test000082 Class Reference
#include <test000082.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_export_delayAssignment_1 ()
void test_export_delayAssignment_2 ()
void test_export_delayAssignment_3 ()
void test_export_delayAssignment_4 ()
void test_export_delayAssignment_5 ()
void test_export_delayAssignment_6 ()
void test_import_delayAssignment_1 ()
void test_import_delayAssignment_2 ()
void test_import_delayAssignment_3 ()
void test_import_delayAssignment_4 ()
void test_import_delayAssignment_5 ()
void test_import_delayAssignment_6 ()
void test_import_delayAssignment_7 ()
void test_import_delayAssignment_8 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING101
static const char * MODEL_STRING102
static const char * MODEL_STRING103
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static const char * MODEL_STRING7
static const char * MODEL_STRING8
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_delayAssignment_1)
CPPUNIT_TEST (test_import_delayAssignment_2)
CPPUNIT_TEST (test_import_delayAssignment_3)
CPPUNIT_TEST (test_import_delayAssignment_4)
CPPUNIT_TEST (test_import_delayAssignment_5)
CPPUNIT_TEST (test_import_delayAssignment_6)
CPPUNIT_TEST (test_import_delayAssignment_7)
CPPUNIT_TEST (test_import_delayAssignment_8)
CPPUNIT_TEST (test_export_delayAssignment_1)
CPPUNIT_TEST (test_export_delayAssignment_2)
CPPUNIT_TEST (test_export_delayAssignment_3)
CPPUNIT_TEST (test_export_delayAssignment_4)
CPPUNIT_TEST (test_export_delayAssignment_5)
CPPUNIT_TEST (test_export_delayAssignment_6)
CPPUNIT_TEST_SUITE (test000082)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 29 of file test000082.h.
Member Function Documentation
test000082::CPPUNIT_TEST (test_import_delayAssignment_1) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_2) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_3) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_4) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_5) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_6) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_7) private
test000082::CPPUNIT_TEST (test_import_delayAssignment_8) private
test000082::CPPUNIT_TEST (test_export_delayAssignment_1) private
test000082::CPPUNIT_TEST (test_export_delayAssignment_2) private
test000082::CPPUNIT_TEST (test_export_delayAssignment_3) private
test000082::CPPUNIT_TEST (test_export_delayAssignment_4) private
test000082::CPPUNIT_TEST (test_export_delayAssignment_5) private
test000082::CPPUNIT_TEST (test_export_delayAssignment_6) private
test000082::CPPUNIT_TEST_SUITE (test000082) private
test000082::CPPUNIT_TEST_SUITE_END () private
void test000082::setUp ()
Definition at line 51 of file test000082.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000082::tearDown ()
Definition at line 59 of file test000082.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000082::test_export_delayAssignment_1 ()
Definition at line 1116 of file test000082.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING101, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000082::MODEL_STRING101);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 4).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 4);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   CPPUNIT_ASSERT(pEvent->getUseValuesFromTriggerTime() == true);
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event assignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000082::test_export_delayAssignment_2 ()
Definition at line 1224 of file test000082.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), load_cps_model_from_stream(), MCSBML, MODEL_STRING101, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000082::MODEL_STRING101);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 1).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 1);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   CPPUNIT_ASSERT(pEvent->getUseValuesFromTriggerTime() == true);
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event assignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
   // make sure there is actually no warning MCSBML + 77
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 77);
       ++i;
     }
 }
void test000082::test_export_delayAssignment_3 ()
Definition at line 1398 of file test000082.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING102, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000082::MODEL_STRING102);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 4).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 4);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   CPPUNIT_ASSERT(pEvent->getUseValuesFromTriggerTime() == false);
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event assignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000082::test_export_delayAssignment_4 ()
Definition at line 1506 of file test000082.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), load_cps_model_from_stream(), MCSBML, MODEL_STRING102, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000082::MODEL_STRING102);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 1).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 1);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay());
   CPPUNIT_ASSERT(pEvent->getUseValuesFromTriggerTime() == true);
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay != NULL);
   CPPUNIT_ASSERT(pDelay->isSetMath());
   pMath = pDelay->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pMath->getReal() - 4.0) / 4.0) < 1e-6);
   // check the event assignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
   // make sure there is actually a warning MCSBML + 77
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 77)
         {
           break;
         }
       ++i;
     }
   CPPUNIT_ASSERT(i != iMax);
 }
void test000082::test_export_delayAssignment_5 ()
Definition at line 1687 of file test000082.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING103, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000082::MODEL_STRING103);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 4).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 4);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay() == false);
   CPPUNIT_ASSERT(pEvent->getUseValuesFromTriggerTime() == true);
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay == NULL);
   // check the event assignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
 }
void test000082::test_export_delayAssignment_6 ()
Definition at line 1790 of file test000082.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), load_cps_model_from_stream(), MCSBML, MODEL_STRING103, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000082::MODEL_STRING103);
   bool result = load_cps_model_from_stream(iss, *pDataModel);
   CPPUNIT_ASSERT(result == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 1).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   CPPUNIT_ASSERT(pDocument->getLevel() == 2);
   CPPUNIT_ASSERT(pDocument->getVersion() == 1);
   Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check the units
   UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   Unit* pUnit = NULL;
   // since second is the default time unit, it does not have to be exported and
   // might be NULL
   if (pUDef != NULL)
     {
       CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
       pUnit = pUDef->getUnit(0);
       CPPUNIT_ASSERT(pUnit != NULL);
       CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_SECOND);
       CPPUNIT_ASSERT(pUnit->getScale() == 0);
       CPPUNIT_ASSERT(pUnit->getExponent() == 1);
       CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
     }
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_MOLE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getNumUnits() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_LITRE);
   CPPUNIT_ASSERT(pUnit->getScale() == -3);
   CPPUNIT_ASSERT(pUnit->getExponent() == 1);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   // assert that there is only one compartment and
   // assert the compartment is constant
   CPPUNIT_ASSERT(pModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pModel->getNumParameters() == 1);
   Parameter* pParameter1 = pModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getName() == "K");
   CPPUNIT_ASSERT(pModel->getNumSpecies() == 2);
   Species* pSpecies1 = pModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies1->getName() == "A");
   Species* pSpecies2 = pModel->getSpecies(1);
   CPPUNIT_ASSERT(pSpecies2->getName() == "B");
   CPPUNIT_ASSERT(pModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pModel->getNumEvents() == 1);
   Event* pEvent = pModel->getEvent(0);
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger
   CPPUNIT_ASSERT(pEvent->isSetTrigger());
   Trigger* pTrigger = pEvent->getTrigger();
   CPPUNIT_ASSERT(pTrigger != NULL);
   CPPUNIT_ASSERT(pTrigger->isSetMath());
   const ASTNode* pMath = pTrigger->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_RELATIONAL_GT);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_NAME_TIME);
   pChild = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(pChild->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild->getReal() - 2.0) / 2.0) < 1e-6);
   // check the delay
   CPPUNIT_ASSERT(pEvent->isSetDelay() == false);
   CPPUNIT_ASSERT(pEvent->getUseValuesFromTriggerTime() == true);
   Delay* pDelay = pEvent->getDelay();
   CPPUNIT_ASSERT(pDelay == NULL);
   // check the event assignment
   CPPUNIT_ASSERT(pEvent->getNumEventAssignments() == 1);
   EventAssignment* pEA = pEvent->getEventAssignment(0);
   CPPUNIT_ASSERT(pEA != NULL);
   CPPUNIT_ASSERT(pEA->getVariable() == pSpecies1->getId());
   pMath = pEA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // make sure the mathematical expression contains only one node that is a
   // reference to the global parameter
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
   // make sure there is actually no warning MCSBML + 77
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 77);
       ++i;
     }
 }
void test000082::test_import_delayAssignment_1 ()
Definition at line 64 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING1, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 10.0) / 10.0) < 1e-6);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_2 ()
Definition at line 201 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING2, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr == NULL);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_3 ()
Definition at line 327 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING3, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING3));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 10.0) / 10.0) < 1e-6);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_4 ()
Definition at line 464 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING4, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING4));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 10.0) / 10.0) < 1e-6);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_5 ()
Definition at line 601 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING5, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING5));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 10.0) / 10.0) < 1e-6);
   // check that the delayAssignment flag is set to false
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == false);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_6 ()
Definition at line 738 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING6, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING6));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr == NULL);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_7 ()
Definition at line 864 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING7, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING7));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr == NULL);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
void test000082::test_import_delayAssignment_8 ()
Definition at line 990 of file test000082.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, CModel::ml, CModel::mMol, MODEL_STRING8, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING8));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 1);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   pExpr = pEvent->getDelayExpressionPtr();
   CPPUNIT_ASSERT(pExpr == NULL);
   // check that the delayAssignment flag is set to true
   CPPUNIT_ASSERT(pEvent->getDelayAssignment() == true);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pA->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Value"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModelValue);
 }
Member Data Documentation
const char * test000082::MODEL_STRING1 static protected
Definition at line 53 of file test000082.h.
Referenced by test_import_delayAssignment_1().
const char * test000082::MODEL_STRING101 static protected
Definition at line 74 of file test000082.h.
Referenced by test_export_delayAssignment_1(), and test_export_delayAssignment_2().
const char * test000082::MODEL_STRING102 static protected
Definition at line 76 of file test000082.h.
Referenced by test_export_delayAssignment_3(), and test_export_delayAssignment_4().
const char * test000082::MODEL_STRING103 static protected
Definition at line 78 of file test000082.h.
Referenced by test_export_delayAssignment_5(), and test_export_delayAssignment_6().
const char * test000082::MODEL_STRING2 static protected
Definition at line 56 of file test000082.h.
Referenced by test_import_delayAssignment_2().
const char * test000082::MODEL_STRING3 static protected
Definition at line 59 of file test000082.h.
Referenced by test_import_delayAssignment_3().
const char * test000082::MODEL_STRING4 static protected
Definition at line 61 of file test000082.h.
Referenced by test_import_delayAssignment_4().
const char * test000082::MODEL_STRING5 static protected
Definition at line 63 of file test000082.h.
Referenced by test_import_delayAssignment_5().
const char * test000082::MODEL_STRING6 static protected
Definition at line 65 of file test000082.h.
Referenced by test_import_delayAssignment_6().
const char * test000082::MODEL_STRING7 static protected
Definition at line 67 of file test000082.h.
Referenced by test_import_delayAssignment_7().
const char * test000082::MODEL_STRING8 static protected
Definition at line 69 of file test000082.h.
Referenced by test_import_delayAssignment_8().
CCopasiDataModel * test000082::pCOPASIDATAMODEL = NULL static protected
Definition at line 80 of file test000082.h.
Referenced by setUp(), test_export_delayAssignment_1(), test_export_delayAssignment_2(), test_export_delayAssignment_3(), test_export_delayAssignment_4(), test_export_delayAssignment_5(), test_export_delayAssignment_6(), test_import_delayAssignment_1(), test_import_delayAssignment_2(), test_import_delayAssignment_3(), test_import_delayAssignment_4(), test_import_delayAssignment_5(), test_import_delayAssignment_6(), test_import_delayAssignment_7(), and test_import_delayAssignment_8().
The documentation for this class was generated from the following files:
test000082.h
test000082.cpp