COPASI API: CCopasiXMLParser::PlotItemElement Class Reference
CCopasiXMLParser::PlotItemElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
PlotItemElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~PlotItemElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { PlotItem = 0, Parameter, ParameterGroup, ListOfChannels }
Private Attributes
size_t mLineNumber
CXMLElementHandler
< CCopasiXMLParser,
SCopasiXMLParserCommon > * mpListOfChannelsElement
CXMLElementHandler
< CCopasiXMLParser,
SCopasiXMLParserCommon > * mpParameterElement
CXMLElementHandler
< CCopasiXMLParser,
SCopasiXMLParserCommon > * mpParameterGroupElement
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1899 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::PlotItemElement::Element private
Enumerator
PlotItem
Parameter
ParameterGroup
ListOfChannels
Definition at line 1906 of file CCopasiXMLParser.h.
     {
       PlotItem = 0,
       Parameter,
       ParameterGroup,
       ListOfChannels
     };
Constructor & Destructor Documentation
CCopasiXMLParser::PlotItemElement::PlotItemElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 5777 of file CCopasiXMLParser.cpp.
                                                                                                          :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpParameterElement(NULL),
   mpParameterGroupElement(NULL),
   mpListOfChannelsElement(NULL),
   mLineNumber(0)
 {}
CCopasiXMLParser::PlotItemElement::~PlotItemElement () virtual
Destructor
Definition at line 5786 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpParameterElement);
   pdelete(mpParameterGroupElement);
   pdelete(mpListOfChannelsElement);
 }
Member Function Documentation
void CCopasiXMLParser::PlotItemElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 5882 of file CCopasiXMLParser.cpp.
References CCopasiParameter::BOOL, CCopasiParameter::CN, CCopasiParameter::DOUBLE, CCopasiMessage::EXCEPTION, CCopasiParameter::EXPRESSION, fatalError, CCopasiParameter::FILE, CKeyFactory::get(), CCopasiParameter::getKey(), CCopasiObject::getKey(), CCopasiObject::getObjectName(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getType(), CCopasiParameter::getValue(), CCopasiParameter::GROUP, CCopasiParameter::INT, CCopasiParameter::INVALID, CCopasiParameter::KEY, SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, SCopasiXMLParserCommon::pCurrentParameter, SCopasiXMLParserCommon::pCurrentPlotItem, pdelete, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pFILE, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pKEY, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CCopasiMessage::RAW, CCopasiParameter::setValue(), START_ELEMENT, CCopasiParameter::STRING, CCopasiParameter::UDOUBLE, CCopasiParameter::UINT, UNKNOWN_ELEMENT, and SCopasiXMLParserCommon::UnmappedKeyParameters.
 {
   CCopasiParameter * p = NULL;
   switch (mCurrentElement)
     {
       case PlotItem:
         if (strcmp(pszName, "PlotItem"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "PlotItem", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         mParser.onEndElement(pszName);
         break;
       case Parameter:
         if (!strcmp(pszName, "Parameter"))
           {
             p = mCommon.pCurrentPlotItem->getParameter(mCommon.pCurrentParameter->getObjectName());
             //TODO warning if type mismatch. Is silently ignored currently.
             if (p && p->getType() == mCommon.pCurrentParameter->getType())
               {
                 switch (p->getType())
                   {
                     case CCopasiParameter::INT:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pINT);
                       break;
                     case CCopasiParameter::UINT:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pUINT);
                       break;
                     case CCopasiParameter::DOUBLE:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pDOUBLE);
                       break;
                     case CCopasiParameter::UDOUBLE:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pUDOUBLE);
                       break;
                     case CCopasiParameter::BOOL:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pBOOL);
                       break;
                     case CCopasiParameter::STRING:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pSTRING);
                       break;
                     case CCopasiParameter::KEY:
                     {
                       CCopasiObject * pObject =
                         mCommon.KeyMap.get(* mCommon.pCurrentParameter->getValue().pKEY);
                       if (pObject)
                         p->setValue(pObject->getKey());
                       else
{
                           p->setValue(*mCommon.pCurrentParameter->getValue().pKEY);
                           mCommon.UnmappedKeyParameters.push_back(p->getKey());
                         }
                     }
                     break;
                     case CCopasiParameter::FILE:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pFILE);
                       break;
                     case CCopasiParameter::CN:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pCN);
                       break;
                     case CCopasiParameter::EXPRESSION:
                     case CCopasiParameter::GROUP:
                     case CCopasiParameter::INVALID:
                       break;
                     default:
                       fatalError();
                       break;
                   }
               }
             else
               {
                 CCopasiMessage(CCopasiMessage::RAW, MCXML + 4,
                                mCommon.pCurrentParameter->getObjectName().c_str(),
                                mLineNumber);
               }
             pdelete(mCommon.pCurrentParameter);
             mCurrentElement = PlotItem;
           }
         break;
       case ParameterGroup:
         if (!strcmp(pszName, "ParameterGroup"))
           {
             mCurrentElement = PlotItem;
           }
         break;
       case ListOfChannels:
         if (!strcmp(pszName, "ListOfChannels"))
           {
             mCurrentElement = PlotItem;
           }
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::PlotItemElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 5793 of file CCopasiXMLParser.cpp.
References CPlotSpecification::createItem(), CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentPlot, SCopasiXMLParserCommon::pCurrentPlotItem, toEnum(), UNKNOWN_ELEMENT, CPlotItem::unset, and CPlotItem::XMLType.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   std::string name;
   std::string sType;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case PlotItem:
         if (strcmp(pszName, "PlotItem"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "PlotItem", mParser.getCurrentLineNumber());
         // create a new CPlotSpecification element depending on the type
         name = mParser.getAttributeValue("name", papszAttrs);
         sType = mParser.getAttributeValue("type", papszAttrs);
         mCommon.pCurrentPlotItem =
           mCommon.pCurrentPlot->createItem(name, toEnum(sType.c_str(), CPlotItem::XMLType, CPlotItem::unset));
         return;
         break;
       case Parameter:
         if (!strcmp(pszName, "Parameter"))
           {
             mLineNumber = mParser.getCurrentLineNumber();
             if (!mpParameterElement)
               {
                 mpParameterElement = new ParameterElement(mParser, mCommon);
               }
             mpCurrentHandler = mpParameterElement;
           }
         break;
       case ParameterGroup:
         if (!strcmp(pszName, "ParameterGroup"))
           {
             mLineNumber = mParser.getCurrentLineNumber();
             if (!mpParameterGroupElement)
               {
                 mpParameterGroupElement = new ParameterGroupElement(mParser, mCommon);
               }
             mpCurrentHandler = mpParameterGroupElement;
           }
         break;
       case ListOfChannels:
         if (!strcmp(pszName, "ListOfChannels"))
           {
             mLineNumber = mParser.getCurrentLineNumber();
             if (!mpListOfChannelsElement)
               {
                 mpListOfChannelsElement = new ListOfChannelsElement(mParser, mCommon);
               }
             mpCurrentHandler = mpListOfChannelsElement;
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::PlotItemElement::mLineNumber private
The line number the unknown parameter was encountered.
Definition at line 1932 of file CCopasiXMLParser.h.
CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >* CCopasiXMLParser::PlotItemElement::mpListOfChannelsElement private
Pointer to the List Of Channels Element Handler
Definition at line 1927 of file CCopasiXMLParser.h.
CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >* CCopasiXMLParser::PlotItemElement::mpParameterElement private
Pointer to the Parameter Element Handler
Definition at line 1917 of file CCopasiXMLParser.h.
CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >* CCopasiXMLParser::PlotItemElement::mpParameterGroupElement private
Pointer to the Parameter Group Element Handler
Definition at line 1922 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp