COPASI API: COptProblem.cpp File Reference
COptProblem.cpp File Reference
#include <cmath>
#include "copasi.h"
#include "COptTask.h"
#include "COptProblem.h"
#include "COptItem.h"
#include "function/CFunctionDB.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "steadystate/CSteadyStateTask.h"
#include "trajectory/CTrajectoryTask.h"
#include "steadystate/CSteadyStateProblem.h"
#include "trajectory/CTrajectoryProblem.h"
#include "model/CModel.h"
#include "model/CCompartment.h"
#include "report/CCopasiObjectReference.h"
#include "report/CKeyFactory.h"
#include "utilities/CProcessReport.h"
#include "utilities/CCopasiException.h"
Functions
std::ostream & operator<< (std::ostream &os, const COptProblem &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const COptProblem & o)
Output stream operator
Parameters
ostream & os
const COptProblem & A
Returns
ostream & os
Definition at line 892 of file COptProblem.cpp.
References CCopasiTask::getDescription(), CExpression::getDisplayString(), COptProblem::mpConstraintItems, COptProblem::mpObjectiveExpression, COptProblem::mpOptItems, COptProblem::mpSubtask, and CCopasiTask::CDescription::print().
 {
   os << "Problem Description:" << std::endl;
   os << "Subtask: " << std::endl;
   if (o.mpSubtask)
     o.mpSubtask->getDescription().print(&os);
   else
     os << "No Subtask specified.";
   os << std::endl;
   if (o.mpObjectiveExpression)
     {
       os << "Objective Function:" << std::endl;
       os << "    " << o.mpObjectiveExpression->getDisplayString() << std::endl;
       os << std:: endl;
     }
   os << "List of Optimization Items:" << std::endl;
   std::vector< COptItem * >::const_iterator itItem =
     o.mpOptItems->begin();
   std::vector< COptItem * >::const_iterator endItem =
     o.mpOptItems->end();
   for (; itItem != endItem; ++itItem)
     os << "    " << **itItem << std::endl;
   itItem = o.mpConstraintItems->begin();
   endItem = o.mpConstraintItems->end();
   for (; itItem != endItem; ++itItem)
     os << "    " << **itItem << std::endl;
   return os;
 }