COPASI API: CMatrix.h File Reference
CMatrix.h File Reference
#include <algorithm>
#include <iostream>
#include <assert.h>
#include <string.h>
#include "copasi.h"
#include "utilities/CVector.h"
Classes
class CFortranAccess< Matrix >
class CLowerTriangularView< Matrix >
class CLowerTriangularView< Matrix >
class CMatrix< CType >
class CMatrix< CType >
class CTransposeView< Matrix >
class CTransposeView< Matrix >
class CUnitLowerTriangularView< Matrix >
class CUnitLowerTriangularView< Matrix >
class CUnitUpperTriangularView< Matrix >
class CUnitUpperTriangularView< Matrix >
class CUpperTriangularView< Matrix >
class CUpperTriangularView< Matrix >
Functions
template<class CType >
std::ostream & operator<< (std::ostream &os, const CMatrix< CType > &A)
template<class Matrix >
std::ostream & operator<< (std::ostream &os, const CTransposeView< Matrix > &A)
template<class Matrix >
std::ostream & operator<< (std::ostream &os, const CLowerTriangularView< Matrix > &A)
template<class Matrix >
std::ostream & operator<< (std::ostream &os, const CUpperTriangularView< Matrix > &A)
template<class Matrix >
std::ostream & operator<< (std::ostream &os, const CUnitUpperTriangularView< Matrix > &A)
template<class Matrix >
std::ostream & operator<< (std::ostream &os, const CUnitLowerTriangularView< Matrix > &A)
Function Documentation
template<class CType > std::ostream & operator<< (std::ostream & os, const CMatrix< CType > & A)
Output stream operator
Parameters
ostream & os
const CMatrix< CType > & A
Returns
ostream & os
Definition at line 809 of file CMatrix.h.
 {
   os << "Matrix(" << A.mRows << "x" << A.mCols << ")" << std::endl;
   size_t i, j;
   CType * tmp = A.mArray;
   for (i = 0; i < A.mRows; i++)
     {
       for (j = 0; j < A.mCols; j++)
         os << "\t" << *(tmp++);
       os << std::endl;
     }
   return os;
 }
template<class Matrix > std::ostream & operator<< (std::ostream & os, const CTransposeView< Matrix > & A)
Output stream operator
Parameters
ostream & os
const CTransposeView< Matrix > & A
Returns
ostream & os
Definition at line 904 of file CMatrix.h.
References CTransposeView< Matrix >::numCols(), and CTransposeView< Matrix >::numRows().
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }
template<class Matrix > std::ostream & operator<< (std::ostream & os, const CLowerTriangularView< Matrix > & A)
Output stream operator
Parameters
ostream & os
const CLowerTriangularView< Matrix > & A
Returns
ostream & os
Definition at line 847 of file CMatrix.h.
References CLowerTriangularView< Matrix >::numCols(), and CLowerTriangularView< Matrix >::numRows().
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }
template<class Matrix > std::ostream & operator<< (std::ostream & os, const CUpperTriangularView< Matrix > & A)
Output stream operator
Parameters
ostream & os
const CUpperTriangularView< Matrix > & A
Returns
ostream & os
Definition at line 828 of file CMatrix.h.
References CUpperTriangularView< Matrix >::numCols(), and CUpperTriangularView< Matrix >::numRows().
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }
template<class Matrix > std::ostream & operator<< (std::ostream & os, const CUnitUpperTriangularView< Matrix > & A)
Output stream operator
Parameters
ostream & os
const CUnitUpperTriangularView< Matrix > & A
Returns
ostream & os
Definition at line 866 of file CMatrix.h.
References CUnitUpperTriangularView< Matrix >::numCols(), and CUnitUpperTriangularView< Matrix >::numRows().
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }
template<class Matrix > std::ostream & operator<< (std::ostream & os, const CUnitLowerTriangularView< Matrix > & A)
Output stream operator
Parameters
ostream & os
const CUnitLowerTriangularView< Matrix > & A
Returns
ostream & os
Definition at line 885 of file CMatrix.h.
References CUnitLowerTriangularView< Matrix >::numCols(), and CUnitLowerTriangularView< Matrix >::numRows().
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }