COPASI API: CNewtonMethod Class Reference
CNewtonMethod Class Reference
#include <CNewtonMethod.h>
Public Member Functions
CNewtonMethod (const CNewtonMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
virtual bool initialize (const CSteadyStateProblem *pProblem)
bool isSteadyState (C_FLOAT64 value)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual
CSteadyStateMethod::ReturnCode processInternal ()
C_FLOAT64 targetFunction (const CVector< C_FLOAT64 > &particleFluxes)
~CNewtonMethod ()
Public Member Functions inherited from CSteadyStateMethod
CSteadyStateMethod (const CSteadyStateMethod &src, const CCopasiContainer *pParent=NULL)
void doJacobian (CMatrix< C_FLOAT64 > &jacobian, CMatrix< C_FLOAT64 > &jacobianX)
bool elevateChildren ()
std::string getMethodLog () const
C_FLOAT64 getStabilityResolution ()
CSteadyStateMethod::ReturnCode process (CState *pState, CMatrix< C_FLOAT64 > &jacobianX, CProcessReport *handler)
~CSteadyStateMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Types
enum NewtonResultCode {
found = 0, notFound, iterationLimitExceeded, dampingLimitExceeded,
singularJacobian, negativeValueFound, stepSuccesful
}
Private Member Functions
void calculateDerivativesX ()
void cleanup ()
CNewtonMethod (const CCopasiContainer *pParent=NULL)
bool containsNaN () const
CNewtonMethod::NewtonResultCode doIntegration (bool forward)
CNewtonMethod::NewtonResultCode doNewtonStep (C_FLOAT64 &currentValue)
void initializeParameter ()
CNewtonMethod::NewtonResultCode processNewton ()
C_FLOAT64 solveJacobianXeqB (CVector< C_FLOAT64 > &X, const CVector< C_FLOAT64 > &B) const
Private Attributes
bool mAcceptNegative
CVector< C_FLOAT64 > mAtol
size_t mDimension
CVector< C_FLOAT64 > mdxdt
bool mForceNewton
CVector< C_FLOAT64 > mH
C_INT * mIpiv
unsigned C_INT32 mIterationLimit
bool mKeepProtocol
C_FLOAT64 mMaxDurationBackward
C_FLOAT64 mMaxDurationForward
CTrajectoryTask * mpTrajectory
C_FLOAT64 * mpX
CState mStartState
bool mUseBackIntegration
bool mUseIntegration
bool mUseNewton
CVector< C_FLOAT64 > mXold
Friends
CSteadyStateMethod * CSteadyStateMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CSteadyStateMethod
enum ReturnCode { notFound = 0, found, foundEquilibrium, foundNegative }
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CSteadyStateMethod
static CSteadyStateMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::Newton)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CSteadyStateMethod
bool allPositive ()
void calculateJacobianX (const C_FLOAT64 &oldMaxRate)
CSteadyStateMethod (CCopasiMethod::SubType subType, const CCopasiContainer *pParent=NULL)
void initializeParameter ()
bool isEquilibrium (const C_FLOAT64 &resolution) const
virtual
CSteadyStateMethod::ReturnCode returnProcess (bool steadyStateFound)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CSteadyStateMethod
std::ostringstream mMethodLog
C_FLOAT64 * mpDerivationFactor
C_FLOAT64 * mpDerivationResolution
CMatrix< C_FLOAT64 > * mpJacobianX
CModel * mpModel
CSteadyStateTask * mpParentTask
const CSteadyStateProblem * mpProblem
C_FLOAT64 * mpSSResolution
CState * mpSteadyState
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 32 of file CNewtonMethod.h.
Member Enumeration Documentation
enum CNewtonMethod::NewtonResultCode private
Enumerator
found
notFound
iterationLimitExceeded
dampingLimitExceeded
singularJacobian
negativeValueFound
stepSuccesful
Definition at line 39 of file CNewtonMethod.h.
   {
     found = 0,
     notFound,
     iterationLimitExceeded,
     dampingLimitExceeded,
     singularJacobian,
     negativeValueFound,
     stepSuccesful
   };
Constructor & Destructor Documentation
CNewtonMethod::CNewtonMethod (const CCopasiContainer * pParent = NULL) private
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 39 of file CNewtonMethod.cpp.
References initializeParameter().
                                                             :
   CSteadyStateMethod(CCopasiMethod::Newton, pParent),
   mIpiv(NULL),
   mpTrajectory(NULL),
   mStartState()
 {
   initializeParameter();
 }
CNewtonMethod::CNewtonMethod (const CNewtonMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CNewtonMethod & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 48 of file CNewtonMethod.cpp.
References initializeParameter().
                                                               :
   CSteadyStateMethod(src, pParent),
   mIpiv(NULL),
   mpTrajectory(NULL),
   mStartState()
 {
   initializeParameter();
 }
CNewtonMethod::~CNewtonMethod ()
Destructor.
Definition at line 58 of file CNewtonMethod.cpp.
References cleanup().
 {cleanup();}
Member Function Documentation
void CNewtonMethod::calculateDerivativesX () private
Definition at line 567 of file CNewtonMethod.cpp.
References CVectorCore< CType >::array(), CModel::calculateDerivativesX(), mdxdt, CSteadyStateMethod::mpModel, CSteadyStateMethod::mpSteadyState, CModel::setState(), and CModel::updateSimulatedValues().
Referenced by doIntegration(), doNewtonStep(), and processNewton().
 {
   mpModel->setState(*mpSteadyState);
   mpModel->updateSimulatedValues(true);
   mpModel->calculateDerivativesX(mdxdt.array());
 }
void CNewtonMethod::cleanup () private
Definition at line 120 of file CNewtonMethod.cpp.
References mIpiv, mpTrajectory, and pdelete.
Referenced by initialize(), and ~CNewtonMethod().
 {
   if (mIpiv) delete [] mIpiv; mIpiv = NULL;
   pdelete(mpTrajectory);
 }
bool CNewtonMethod::containsNaN () const private
Definition at line 574 of file CNewtonMethod.cpp.
References CState::beginIndependent(), C_FLOAT64, CState::endIndependent(), and CSteadyStateMethod::mpSteadyState.
Referenced by doIntegration(), and isSteadyState().
 {
   //checks for NaNs
   const C_FLOAT64 * pIt = mpSteadyState->beginIndependent();
   const C_FLOAT64 * pEnd = mpSteadyState->endIndependent();
   for (; pIt != pEnd; ++pIt)
     if (isnan(*pIt))
       return true;
   return false;
 }
CNewtonMethod::NewtonResultCode CNewtonMethod::doIntegration (bool forward) private
Definition at line 186 of file CNewtonMethod.cpp.
References CProcessReport::addItem(), CSteadyStateMethod::allPositive(), C_FLOAT64, C_INT32, calculateDerivativesX(), containsNaN(), CProcessReport::finishItem(), found, CCopasiTask::getProblem(), CTrajectoryTask::getState(), isSteadyState(), mAcceptNegative, mdxdt, mKeepProtocol, mMaxDurationBackward, mMaxDurationForward, CSteadyStateMethod::mMethodLog, CCopasiMethod::mpCallBack, CSteadyStateMethod::mpModel, CSteadyStateMethod::mpSteadyState, mpTrajectory, mStartState, mUseNewton, notFound, CTrajectoryTask::process(), processNewton(), CProcessReport::progressItem(), CCopasiTask::setCallBack(), CTrajectoryProblem::setDuration(), CModel::setState(), CTrajectoryProblem::setStepNumber(), and targetFunction().
Referenced by processInternal().
 {
   C_FLOAT64 iterationFactor = forward ? 10.0 : 2.0;
   C_FLOAT64 maxDuration = forward ? mMaxDurationForward : -mMaxDurationBackward;
   //minimum duration is either hardcoded or equal to maximum duration, whichever is smaller.
   C_FLOAT64 minDuration = forward ? (mMaxDurationForward < 1e-1 ? mMaxDurationForward : 1e-1)
                           : -(mMaxDurationBackward < 1e-2 ? mMaxDurationBackward : 1e-2);
   //progress bar
   size_t hProcess;
   unsigned C_INT32 Step = 0;
   unsigned C_INT32 MaxSteps;
   MaxSteps = (unsigned C_INT32) ceil(log(maxDuration / minDuration) / log(iterationFactor));
   std::string tmpstring = forward ? "forward integrating..." : "backward integrating...";
   if (mpCallBack)
     hProcess = mpCallBack->addItem(tmpstring,
                                    Step,
                                    & MaxSteps);
   //setup trajectory
   CTrajectoryProblem * pTrajectoryProblem = NULL;
   if (mpTrajectory)
     {
       mpTrajectory->setCallBack(mpCallBack);
       pTrajectoryProblem =
         dynamic_cast<CTrajectoryProblem *>(mpTrajectory->getProblem());
       assert(pTrajectoryProblem);
       pTrajectoryProblem->setStepNumber(1);
     }
   bool stepLimitReached = false;
   C_FLOAT64 duration;
   for (duration = minDuration; fabs(duration) <= fabs(maxDuration); duration *= iterationFactor, Step++)
     {
       if (mpCallBack && !mpCallBack->progressItem(hProcess)) break;
       pTrajectoryProblem->setDuration(duration);
       try
         {
           // We must not use useInitialValues = true here as this will interfere with scan continuation.
           mpModel->setState(mStartState);
           stepLimitReached = !mpTrajectory->process(false); //single step
         }
       catch (CCopasiException & /*Exception*/)
         {
           *mpSteadyState = *mpTrajectory->getState();
           if (mKeepProtocol)
             mMethodLog << "  Integration with duration " << duration << " failed (Exception).\n\n";
           break;
         }
       *mpSteadyState = *mpTrajectory->getState();
       if (containsNaN())
         {
           if (mKeepProtocol)
             mMethodLog << "  Integration with duration " << duration << " failed (NaN).\n\n";
           break;
         }
       if (!(mAcceptNegative || allPositive()))
         {
           if (mKeepProtocol)
             mMethodLog << "  Integration with duration " << duration
                        << " resulted in negative concentrations.\n\n";
           break;
         }
       calculateDerivativesX();
       C_FLOAT64 value = targetFunction(mdxdt);
       if (isSteadyState(value))
         {
           if (mpCallBack) mpCallBack->finishItem(hProcess);
           if (mKeepProtocol)
             mMethodLog << "  Integration with duration " << duration
                        << ". Criterium matched by " << value << ".\n\n";
           return CNewtonMethod::found;
         }
       else
         {
           if (mKeepProtocol)
             mMethodLog << "  Integration with duration " << duration
                        << ". Criterium not matched by " << value << ".\n\n";
         }
       if (mUseNewton)
         {
           if (mKeepProtocol) mMethodLog << "  Try Newton's method from this starting point. \n";
           NewtonResultCode returnCode = processNewton();
           if (mKeepProtocol) mMethodLog << "\n";
           // mpParentTask->separate(COutputInterface::DURING);
           if (returnCode == CNewtonMethod::found)
             {
               if (mpCallBack) mpCallBack->finishItem(hProcess);
               return CNewtonMethod::found;
             }
         }
       if (stepLimitReached)
         {
           if (mKeepProtocol)
             mMethodLog << "  Integration with duration " << duration
                        << " reached internal step limit.\n";
           break;
         }
     }
   if (mpCallBack) mpCallBack->finishItem(hProcess);
   return CNewtonMethod::notFound;
 }
CNewtonMethod::NewtonResultCode CNewtonMethod::doNewtonStep (C_FLOAT64 & currentValue) private
Do one newton step and subsequent damping. The value of the targetfunction before the step is provided by the calling method in currentValue, the value after the step is returned in currentValue. The step starts from the state in mpX (pointing to the independent variables of mpSteadyState). After the method returns mpX contains either the old state or the state after the step (if the step was succesful). mdxdt can be expected to be up to date. Possible return values are: dampingLimitExceeded, singularJacobian, stepSuccesful
Definition at line 371 of file CNewtonMethod.cpp.
References CSteadyStateMethod::allPositive(), CVectorCore< CType >::array(), C_FLOAT64, calculateDerivativesX(), CSteadyStateMethod::calculateJacobianX(), dampingLimitExceeded, mAcceptNegative, mDimension, mdxdt, mH, mKeepProtocol, CSteadyStateMethod::mMethodLog, mpX, mXold, negativeValueFound, singularJacobian, CVectorCore< CType >::size(), solveJacobianXeqB(), stepSuccesful, and targetFunction().
Referenced by processNewton().
 {
   memcpy(mXold.array(), mpX, mDimension * sizeof(C_FLOAT64));
   // DebugFile << "Iteration: " << k << std::endl;
   calculateJacobianX(currentValue);
   if (solveJacobianXeqB(mH, mdxdt) != 0.0)
     {
       // We need to check that mH != 0
       C_FLOAT64 * pH = mH.array();
       C_FLOAT64 * pHEnd = pH + mH.size();
       for (; pH != pHEnd; ++pH)
         {
           if (fabs(*pH) > 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon())
             break;
         }
       if (pH == pHEnd)
         {
           if (mKeepProtocol)
             mMethodLog << "    Newton step failed. Jacobian could not be inverted.\n\n";
           return CNewtonMethod::singularJacobian;
         }
     }
   C_FLOAT64 newValue = currentValue * 1.001;
   //repeat till the new max rate is smaller than the old.
   //max 32 times
   size_t i;
   for (i = 0; (i < 32) && !((newValue < currentValue)); i++)
     {
       C_FLOAT64 * pXit = mpX;
       C_FLOAT64 * pXoldIt = mXold.array();
       C_FLOAT64 * pHit = mH.array();
       C_FLOAT64 * pEnd = pHit + mDimension;
       for (; pHit != pEnd; ++pHit, ++pXit, ++pXoldIt)
         {
           *pXit = *pXoldIt - *pHit;
           (*pHit) *= 0.5;
         }
       calculateDerivativesX();
       newValue = targetFunction(mdxdt);
       // mpParentTask->output(COutputInterface::DURING);
     }
   if (i == 32)
     {
       //discard the step
       memcpy(mpX, mXold.array(), mDimension * sizeof(C_FLOAT64));
       calculateDerivativesX();
       currentValue = targetFunction(mdxdt);
       if (mKeepProtocol) mMethodLog << "    Newton step failed. Damping limit exceeded.\n";
       return CNewtonMethod::dampingLimitExceeded;
       //       if (isSteadyState(oldMaxRate) && (mAcceptNegative || allPositive()))
       //         ReturnCode = CNewtonMethod::found;
       //       else if (oldMaxRate < *mpSSResolution)
       //         ReturnCode = CNewtonMethod::notFound;
       //       else
       //         ReturnCode = CNewtonMethod::dampingLimitExceeded;
       //if (mpCallBack) mpCallBack->finish(hProcess);
     }
   if (!(mAcceptNegative || allPositive()))
     {
       if (mKeepProtocol)
         mMethodLog << "    Newton step failed. Negative volume or concentration found.\n\n";
       return CNewtonMethod::negativeValueFound;
     }
   currentValue = newValue; //return the new target value
   if (mKeepProtocol)
     {
       if (i <= 1)
         mMethodLog << "    Regular Newton step.      New value: " << currentValue << "\n";
       else
         mMethodLog << "    Newton step with damping. New value: " << currentValue
                    << " (" << i - 1 << " damping iteration(s))\n";
     }
   return CNewtonMethod::stepSuccesful;
 }
bool CNewtonMethod::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 113 of file CNewtonMethod.cpp.
References CSteadyStateMethod::initializeParameter(), and initializeParameter().
 {
   CSteadyStateMethod::initializeParameter();
   initializeParameter();
   return true;
 }
bool CNewtonMethod::initialize (const CSteadyStateProblem * pProblem) virtual
Initialize the method must be called before process
Parameters
const CSteadyStateProblem * pProblem
Returns
bool success
Reimplemented from CSteadyStateMethod.
Definition at line 692 of file CNewtonMethod.cpp.
References C_INT, cleanup(), CCopasiMethod::deterministic, CCopasiTask::getMethod(), CCopasiProblem::getModel(), CStateTemplate::getNumIndependent(), CCopasiObject::getObjectDataModel(), CCopasiTask::getProblem(), CModel::getStateTemplate(), CCopasiMethod::getSubType(), CCopasiDataModel::getTaskList(), CCopasiParameter::getValue(), CTrajectoryTask::initialize(), CSteadyStateMethod::initialize(), CModel::initializeAtolVector(), mAcceptNegative, mAtol, mDimension, mdxdt, mForceNewton, mH, mIpiv, mIterationLimit, mKeepProtocol, mMaxDurationBackward, mMaxDurationForward, CSteadyStateMethod::mpModel, CSteadyStateMethod::mpProblem, CSteadyStateMethod::mpSSResolution, mpTrajectory, mUseBackIntegration, mUseIntegration, mUseNewton, mXold, CCopasiTask::NO_OUTPUT, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CVector< CType >::resize(), CTrajectoryTask::setMethodType(), CCopasiProblem::setModel(), and CTrajectoryProblem::setStepNumber().
 {
   if (!CSteadyStateMethod::initialize(pProblem)) return false;
   CTrajectoryProblem * pTrajectoryProblem = NULL;
   CTrajectoryMethod * pTrajectoryMethod = NULL;
   cleanup();
   /* Configure Newton */
   mUseNewton = mUseIntegration = mUseBackIntegration = mAcceptNegative
                                  = mForceNewton = mKeepProtocol = false;
   if (* getValue("Use Newton").pBOOL)
     mUseNewton = true;
   if (* getValue("Use Integration").pBOOL)
     mUseIntegration = true;
   if (* getValue("Use Back Integration").pBOOL)
     mUseBackIntegration = true;
   if (* getValue("Accept Negative Concentrations").pBOOL)
     mAcceptNegative = true;
   //if (* getValue("Force additional Newton step").pBOOL)
   mForceNewton = true;
   //if (* getValue("Keep Protocol").pBOOL)
   mKeepProtocol = true;
   mIterationLimit = * getValue("Iteration Limit").pUINT;
   mMaxDurationForward = *getValue("Maximum duration for forward integration").pUDOUBLE;
   mMaxDurationBackward = *getValue("Maximum duration for backward integration").pUDOUBLE;
   //mFactor = * getValue("Derivation Factor").pUDOUBLE;
   //mSSResolution = * getValue("Steady State Resolution").pUDOUBLE;
   //mScaledResolution =
   //  mSSResolution; // * initialState.getModel()->getQuantity2NumberFactor();
   // :TODO: discuss scaling
   // convert CState to CStateX
   //mInitialStateX = mpProblem->getInitialState();
   //*mpSteadyStateX = mInitialStateX; //not strictly necessary
   mDimension = mpProblem->getModel()->getStateTemplate().getNumIndependent();
   mAtol = mpModel->initializeAtolVector(*mpSSResolution, true);
   mH.resize(mDimension);
   mXold.resize(mDimension);
   mdxdt.resize(mDimension);
   mIpiv = new C_INT [mDimension];
   if (mUseIntegration || mUseBackIntegration)
     {
       // create an appropriate trajectory task
       CCopasiDataModel* pDataModel = getObjectDataModel();
       assert(pDataModel != NULL);
       CTrajectoryTask * pSrc =
         dynamic_cast< CTrajectoryTask * >((*pDataModel->getTaskList())["Time-Course"]);
       if (pSrc)
         mpTrajectory = new CTrajectoryTask(*pSrc, this);
       else
         mpTrajectory = new CTrajectoryTask(this);
       pTrajectoryProblem =
         dynamic_cast<CTrajectoryProblem *>(mpTrajectory->getProblem());
       assert(pTrajectoryProblem);
       if (mpTrajectory->getMethod()->getSubType() != CCopasiMethod::deterministic)
         mpTrajectory->setMethodType(CCopasiMethod::deterministic);
       pTrajectoryMethod =
         dynamic_cast<CTrajectoryMethod *>(mpTrajectory->getMethod());
       assert(pTrajectoryMethod);
       pTrajectoryProblem->setModel(mpProblem->getModel());
       pTrajectoryProblem->setStepNumber(1);
       mpTrajectory->initialize(CCopasiTask::NO_OUTPUT, NULL, NULL);
     }
   return true;
 }
void CNewtonMethod::initializeParameter () private
Initialize the method parameter
Definition at line 61 of file CNewtonMethod.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pUINT, CCopasiParameterGroup::removeParameter(), CCopasiParameterGroup::setValue(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CNewtonMethod(), and elevateChildren().
 {
   CCopasiParameter *pParm;
   assertParameter("Use Newton", CCopasiParameter::BOOL, true);
   assertParameter("Use Integration", CCopasiParameter::BOOL, true);
   assertParameter("Use Back Integration", CCopasiParameter::BOOL, true);
   assertParameter("Accept Negative Concentrations", CCopasiParameter::BOOL, false);
   assertParameter("Iteration Limit", CCopasiParameter::UINT, (unsigned C_INT32) 50);
   assertParameter("Maximum duration for forward integration", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1e9);
   assertParameter("Maximum duration for backward integration", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1e6);
   //assertParameter("Force additional Newton step", CCopasiParameter::BOOL, true);
   //assertParameter("Keep Protocol", CCopasiParameter::BOOL, true);
   // Check whether we have a method with the old parameter names
   if ((pParm = getParameter("Newton.UseNewton")) != NULL)
     {
       setValue("Use Newton", *pParm->getValue().pBOOL);
       removeParameter("Newton.UseNewton");
       if ((pParm = getParameter("Newton.UseIntegration")) != NULL)
         {
           setValue("Use Integration", *pParm->getValue().pBOOL);
           removeParameter("Newton.UseIntegration");
         }
       if ((pParm = getParameter("Newton.UseBackIntegration")) != NULL)
         {
           setValue("Use Back Integration", *pParm->getValue().pBOOL);
           removeParameter("Newton.UseBackIntegration");
         }
       if ((pParm = getParameter("Newton.acceptNegativeConcentrations")) != NULL)
         {
           setValue("Accept Negative Concentrations", *pParm->getValue().pBOOL);
           removeParameter("Newton.acceptNegativeConcentrations");
         }
       if ((pParm = getParameter("Newton.IterationLimit")) != NULL)
         {
           setValue("Iteration Limit", *pParm->getValue().pUINT);
           removeParameter("Newton.IterationLimit");
         }
       removeParameter("Newton.LSODA.RelativeTolerance");
       removeParameter("Newton.LSODA.AbsoluteTolerance");
       removeParameter("Newton.LSODA.AdamsMaxOrder");
       removeParameter("Newton.LSODA.BDFMaxOrder");
       removeParameter("Newton.LSODA.MaxStepsInternal");
     }
 }
bool CNewtonMethod::isSteadyState (C_FLOAT64 value)
Definition at line 587 of file CNewtonMethod.cpp.
References containsNaN(), and CSteadyStateMethod::mpSSResolution.
Referenced by doIntegration(), and processNewton().
 {
   if (value > *mpSSResolution)
     return false;
   if (containsNaN())
     return false;
   return true;
 }
bool CNewtonMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CSteadyStateMethod.
Definition at line 656 of file CNewtonMethod.cpp.
References CCopasiMessage::ERROR, CCopasiProblem::getModel(), CCopasiParameter::getValue(), CModel::isAutonomous(), CSteadyStateMethod::isValidProblem(), MCSteadyState, CCopasiParameter::Value::pBOOL, and CCopasiMessage::WARNING.
 {
   if (!CSteadyStateMethod::isValidProblem(pProblem)) return false;
   const CModel * pModel = pProblem->getModel();
   if (!pModel->isAutonomous() &&
       *getValue("Use Newton").pBOOL)
     CCopasiMessage(CCopasiMessage::WARNING, MCSteadyState + 1);
   //const CSteadyStateProblem * pP = dynamic_cast<const CSteadyStateProblem *>(pProblem);
   if (!((* getValue("Use Newton").pBOOL)
         || (* getValue("Use Integration").pBOOL)
         || (* getValue("Use Back Integration").pBOOL)))
     {
       //would do nothing
       CCopasiMessage(CCopasiMessage::ERROR, "At least one of the features \n   - UseNewton\n   - UseIntegration\n   - UseBackIntegration\nmust be activated.");
       return false;
     }
   if (*getValue("Maximum duration for forward integration").pUDOUBLE <= 0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, "Maximum duration for forward integration needs to be positive.");
       return false;
     }
   if (*getValue("Maximum duration for backward integration").pUDOUBLE <= 0)
     {
       CCopasiMessage(CCopasiMessage::ERROR, "Maximum duration for backward integration needs to be positive.");
       return false;
     }
   return true;
 }
void CNewtonMethod::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::SEARCH) virtual
Load a list of parameters
Parameters
CReadConfig & configBuffer
CReadConfig::Mode mode Default(CReadConfig::SEARCH)
Reimplemented from CCopasiMethod.
Definition at line 127 of file CNewtonMethod.cpp.
References C_FLOAT64, C_INT32, fatalError, CReadConfig::getVariable(), CReadConfig::getVersion(), CReadConfig::LOOP, CReadConfig::SEARCH, and CCopasiParameterGroup::setValue().
 {
   if (configBuffer.getVersion() < "4.0")
     {
       C_FLOAT64 Dbl;
       C_INT32 Int;
       bool Bool;
       configBuffer.getVariable("SSStrategy", "C_INT32", &Int, CReadConfig::LOOP);
       switch (Int)
         {
           case 0:
             setValue("Use Newton", true);
             setValue("Use Integration", true);
             setValue("Use Back Integration", false);
             break;
           case 1:
             setValue("Use Newton", false);
             setValue("Use Integration", true);
             setValue("Use Back Integration", false);
             break;
           case 2:
             setValue("Use Newton", true);
             setValue("Use Integration", false);
             setValue("Use Back Integration", false);
             break;
           case 3:
             setValue("Use Newton", false);
             setValue("Use Integration", false);
             setValue("Use Back Integration", true);
             break;
           default:
             fatalError();
             break;
         }
       configBuffer.getVariable("SSBackIntegration", "bool", &Bool);
       setValue("Use Back Integration", Bool);
       configBuffer.getVariable("NewtonLimit", "C_INT32", &Int,
                                CReadConfig::SEARCH);
       setValue("Iteration Limit", Int);
       configBuffer.getVariable("SSResoltion", "C_FLOAT64", &Dbl); //typo is necessary!!
       //setValue("Steady State Resolution", Dbl);
       //setValue("Derivation Resolution", Dbl);
       //setValue("Stability Resolution", Dbl);
       setValue("Resolution", Dbl);
     }
 }
CSteadyStateMethod::ReturnCode CNewtonMethod::processInternal () virtual
This instructs the method to calculate a the steady state starting with the initialState given. The steady state is returned in the object pointed to by steadyState.
Parameters
CState & steadyState
const CState & initialState
Returns
CSteadyStateMethod::ReturnCode returnCode
Reimplemented from CSteadyStateMethod.
Definition at line 320 of file CNewtonMethod.cpp.
References CState::beginIndependent(), doIntegration(), found, mKeepProtocol, CSteadyStateMethod::mMethodLog, CCopasiMethod::mpCallBack, CSteadyStateMethod::mpSteadyState, mpX, mStartState, mUseBackIntegration, mUseIntegration, mUseNewton, processNewton(), CSteadyStateMethod::returnProcess(), and CProcessReport::setName().
 {
   //clear log
   mMethodLog.str("");
   if (mpCallBack)
     mpCallBack->setName("performing steady state calculation...");
   mStartState = * mpSteadyState;
   mpX = mpSteadyState->beginIndependent();
   NewtonResultCode returnCode;
   // Newton
   if (mUseNewton)
     {
       if (mKeepProtocol) mMethodLog << "Try Newton's method. \n";
       returnCode = processNewton();
       if (returnCode == CNewtonMethod::found)
         return returnProcess(true);
     }
   // forward integration
   if (mUseIntegration)
     {
       if (mKeepProtocol) mMethodLog << "\nTry forward integration. \n";
       returnCode = doIntegration(true); //true means forward
       if (returnCode == CNewtonMethod::found)
         return returnProcess(true);
     }
   // backward integration
   if (mUseBackIntegration)
     {
       if (mKeepProtocol) mMethodLog << "\nTry backward integration. \n";
       returnCode = doIntegration(false); //false means backwards
       if (returnCode == CNewtonMethod::found)
         return returnProcess(true);
     }
   return returnProcess(false);
 }
CNewtonMethod::NewtonResultCode CNewtonMethod::processNewton () private
This instructs the method to calculate a the steady state starting with the initialState given. The steady state is returned in the object pointed to by steadyState.
Parameters
CState * steadyState
const CState * initialState
Returns
CNewtonMethod::NewtonReturnCode newtonReturnCode
Definition at line 471 of file CNewtonMethod.cpp.
References CProcessReport::addItem(), C_FLOAT64, C_INT32, calculateDerivativesX(), dampingLimitExceeded, doNewtonStep(), CProcessReport::finishItem(), found, isSteadyState(), iterationLimitExceeded, mdxdt, mForceNewton, mIterationLimit, mKeepProtocol, CSteadyStateMethod::mMethodLog, CCopasiMethod::mpCallBack, negativeValueFound, notFound, CProcessReport::progressItem(), singularJacobian, stepSuccesful, and targetFunction().
Referenced by doIntegration(), and processInternal().
 {
   NewtonResultCode result = CNewtonMethod::notFound;
   unsigned C_INT32 k;
   k = 0;
   //start progress bar
   size_t hProcess;
   if (mpCallBack)
     hProcess = mpCallBack->addItem("Newton method...",
                                    k,
                                    & mIterationLimit);
   C_FLOAT64 targetValue;
   calculateDerivativesX();
   targetValue = targetFunction(mdxdt);
   {
     if (mKeepProtocol) mMethodLog << "   Starting Newton Iterations...\n";
     for (k = 0; k < mIterationLimit && !isSteadyState(targetValue); k++)
       {
         if (mpCallBack && !mpCallBack->progressItem(hProcess)) break;
         result = doNewtonStep(targetValue);
         if (singularJacobian == result) break;
         if (dampingLimitExceeded == result) break;
         if (negativeValueFound == result) break;
       }
   }
   //check if ss was found. If not make sure the correct return value is set
   if (isSteadyState(targetValue))
     result = CNewtonMethod::found;
   else if (CNewtonMethod::stepSuccesful == result)
     result = CNewtonMethod::iterationLimitExceeded;
   //log
   if (mKeepProtocol)
     {
       if (CNewtonMethod::found == result)
         mMethodLog << "   Success: Target criterium matched by " << targetValue << ".\n";
       else if (CNewtonMethod::dampingLimitExceeded == result)
         mMethodLog << "   Failed: Target criterium not matched after reaching iteration limit. " << targetValue << "\n";
     }
   //do an additional Newton step to refine the result
   if ((CNewtonMethod::found == result) && mForceNewton && targetValue > 0.0)
     {
       bool tmp = true;
       ++k; if (mpCallBack && !mpCallBack->progressItem(hProcess)) tmp = false;
       if (tmp)
         {
           if (mKeepProtocol) mMethodLog << "   Do additional step to refine result...\n";
           result = doNewtonStep(targetValue);
           if (CNewtonMethod::stepSuccesful == result)
             result = CNewtonMethod::found;
           if (CNewtonMethod::singularJacobian == result)
             {
               if (mKeepProtocol) mMethodLog << "   Additional step failed. Old values restored.\n";
               result = CNewtonMethod::found;
             }
           if (CNewtonMethod::dampingLimitExceeded == result)
             {
               if (mKeepProtocol) mMethodLog << "   Additional step failed. Old values restored.\n";
               result = CNewtonMethod::found;
             }
           if (CNewtonMethod::negativeValueFound == result)
             {
               if (mKeepProtocol) mMethodLog << "   Additional step failed. Old values restored.\n";
               result = CNewtonMethod::found;
             }
         }
     }
   //end progress bar
   if (mpCallBack) mpCallBack->finishItem(hProcess);
   return result;
 }
C_FLOAT64 CNewtonMethod::solveJacobianXeqB (CVector< C_FLOAT64 > & X, const CVector< C_FLOAT64 > & B) const private
Solve JacobiabX * X = B
Parameters
CVector< C_FLOAT64 > & X
const CVector< C_FLOAT64 > & B
Returns
C_FLOAT64 error
Definition at line 778 of file CNewtonMethod.cpp.
References CVectorCore< CType >::array(), CMatrix< CType >::array(), CStateTemplate::beginIndependent(), CState::beginIndependent(), C_FLOAT64, C_INT, dgelsy_(), dgemm_(), CMetab::getCompartment(), CModel::getNumber2QuantityFactor(), CModel::getStateTemplate(), CModelEntity::getValue(), mAtol, max, CSteadyStateMethod::mpJacobianX, CSteadyStateMethod::mpModel, CSteadyStateMethod::mpSteadyState, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), CVector< CType >::resize(), CVectorCore< CType >::size(), CMatrix< CType >::size(), and CModel::updateSimulatedValues().
Referenced by doNewtonStep(), and targetFunction().
 {
   X = B;
   C_INT M = (C_INT) mpJacobianX->numCols();
   C_INT N = (C_INT) mpJacobianX->numRows();
   if (M == 0 || N == 0 || M != N)
     {
       return std::numeric_limits< C_FLOAT64 >::infinity();
     }
   C_INT LDA = std::max< C_INT >(1, M);
   C_INT NRHS = 1;
   // We need the transpose of the Jacobian;
   CMatrix< C_FLOAT64 > JT(M, N);
   C_FLOAT64 * mpJ = mpJacobianX->array();
   C_FLOAT64 * mpJTcolumn = JT.array();
   C_FLOAT64 * mpJTcolumnEnd = mpJTcolumn + M;
   C_FLOAT64 * mpJT = JT.array();
   C_FLOAT64 * mpJTEnd = mpJT + JT.size();
   for (; mpJTcolumn != mpJTcolumnEnd; ++mpJTcolumn)
     {
       mpJT = mpJTcolumn;
       for (; mpJT < mpJTEnd; mpJT += M, ++mpJ)
         {
           *mpJT = *mpJ;
         }
     }
   CVector< C_INT > JPVT(M);
   JPVT = 0;
   C_FLOAT64 RCOND = 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon();
   C_INT RANK = 0;
   CVector< C_FLOAT64 > WORK(1);
   C_INT LWORK = -1;
   C_INT INFO;
   /*
       SUBROUTINE DGELSY(M, N, NRHS, A, LDA, B, LDB, JPVT, RCOND, RANK,
      $                   WORK, LWORK, INFO)
    *
    *  -- LAPACK driver routine (version 3.2) --
    *  -- LAPACK is a software package provided by Univ. of Tennessee,    --
    *  -- Univ. of California Berkeley, Univ. of Colorado Denver and NAG Ltd..--
    *     November 2006
    *
    *     .. Scalar Arguments ..
       INTEGER            INFO, LDA, LDB, LWORK, M, N, NRHS, RANK
       DOUBLE PRECISION   RCOND
    *     ..
    *     .. Array Arguments ..
       INTEGER            JPVT(*)
       DOUBLE PRECISION   A(LDA, * ), B(LDB, * ), WORK(*)
    *     ..
    *
    *  Purpose
    *  =======
    *
    *  DGELSY computes the minimum-norm solution to a real linear least
    *  squares problem:
    *      minimize || A * X - B ||
    *  using a complete orthogonal factorization of A.  A is an M-by-N
    *  matrix which may be rank-deficient.
    *
    *  Several right hand side vectors b and solution vectors x can be
    *  handled in a single call; they are stored as the columns of the
    *  M-by-NRHS right hand side matrix B and the N-by-NRHS solution
    *  matrix X.
    *
    *  The routine first computes a QR factorization with column pivoting:
    *      A * P = Q * [ R11 R12 ]
    *                  [  0  R22 ]
    *  with R11 defined as the largest leading submatrix whose estimated
    *  condition number is less than 1/RCOND.  The order of R11, RANK,
    *  is the effective rank of A.
    *
    *  Then, R22 is considered to be negligible, and R12 is annihilated
    *  by orthogonal transformations from the right, arriving at the
    *  complete orthogonal factorization:
    *     A * P = Q * [ T11 0 ] * Z
    *                 [  0  0 ]
    *  The minimum-norm solution is then
    *     X = P * Z' [ inv(T11)*Q1'*B ]
    *                [        0       ]
    *  where Q1 consists of the first RANK columns of Q.
    *
    *  This routine is basically identical to the original xGELSX except
    *  three differences:
    *    o The call to the subroutine xGEQPF has been substituted by the
    *      the call to the subroutine xGEQP3. This subroutine is a Blas-3
    *      version of the QR factorization with column pivoting.
    *    o Matrix B (the right hand side) is updated with Blas-3.
    *    o The permutation of matrix B (the right hand side) is faster and
    *      more simple.
    *
    *  Arguments
    *  =========
    *
    *  M       (input) INTEGER
    *          The number of rows of the matrix A.  M >= 0.
    *
    *  N       (input) INTEGER
    *          The number of columns of the matrix A.  N >= 0.
    *
    *  NRHS    (input) INTEGER
    *          The number of right hand sides, i.e., the number of
    *          columns of matrices B and X. NRHS >= 0.
    *
    *  A       (input/output) DOUBLE PRECISION array, dimension (LDA,N)
    *          On entry, the M-by-N matrix A.
    *          On exit, A has been overwritten by details of its
    *          complete orthogonal factorization.
    *
    *  LDA     (input) INTEGER
    *          The leading dimension of the array A.  LDA >= max(1,M).
    *
    *  B       (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS)
    *          On entry, the M-by-NRHS right hand side matrix B.
    *          On exit, the N-by-NRHS solution matrix X.
    *
    *  LDB     (input) INTEGER
    *          The leading dimension of the array B. LDB >= max(1,M,N).
    *
    *  JPVT    (input/output) INTEGER array, dimension (N)
    *          On entry, if JPVT(i) .ne. 0, the i-th column of A is permuted
    *          to the front of AP, otherwise column i is a free column.
    *          On exit, if JPVT(i) = k, then the i-th column of AP
    *          was the k-th column of A.
    *
    *  RCOND   (input) DOUBLE PRECISION
    *          RCOND is used to determine the effective rank of A, which
    *          is defined as the order of the largest leading triangular
    *          submatrix R11 in the QR factorization with pivoting of A,
    *          whose estimated condition number < 1/RCOND.
    *
    *  RANK    (output) INTEGER
    *          The effective rank of A, i.e., the order of the submatrix
    *          R11.  This is the same as the order of the submatrix T11
    *          in the complete orthogonal factorization of A.
    *
    *  WORK    (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK))
    *          On exit, if INFO = 0, WORK(1) returns the optimal LWORK.
    *
    *  LWORK   (input) INTEGER
    *          The dimension of the array WORK.
    *          The unblocked strategy requires that:
    *             LWORK >= MAX(MN+3*N+1, 2*MN+NRHS ),
    *          where MN = min(M, N ).
    *          The block algorithm requires that:
    *             LWORK >= MAX(MN+2*N+N*(N+1), 2*MN+NB*NRHS ),
    *          where NB is an upper bound on the blocksize returned
    *          by ILAENV for the routines DGEQP3, DTZRZF, STZRQF, DORMQR,
    *          and DORMRZ.
    *
    *          If LWORK = -1, then a workspace query is assumed; the routine
    *          only calculates the optimal size of the WORK array, returns
    *          this value as the first entry of the WORK array, and no error
    *          message related to LWORK is issued by XERBLA.
    *
    *  INFO    (output) INTEGER
    *          = 0: successful exit
    *          < 0: If INFO = -i, the i-th argument had an illegal value.
    *
    *  Further Details
    *  ===============
    *
    *  Based on contributions by
    *    A. Petitet, Computer Science Dept., Univ. of Tenn., Knoxville, USA
    *    E. Quintana-Orti, Depto. de Informatica, Universidad Jaime I, Spain
    *    G. Quintana-Orti, Depto. de Informatica, Universidad Jaime I, Spain
    *
    *  =====================================================================
    */
   dgelsy_(&M, &N, &NRHS, JT.array(), &LDA, X.array(), &LDA, JPVT.array(), &RCOND, &RANK,
           WORK.array(), &LWORK, &INFO);
   if (INFO < 0)
     {
       return std::numeric_limits< C_FLOAT64 >::infinity();
     }
   LWORK = (C_INT) WORK[0];
   WORK.resize(LWORK);
   dgelsy_(&M, &N, &NRHS, JT.array(), &LDA, X.array(), &LDA, JPVT.array(), &RCOND, &RANK,
           WORK.array(), &LWORK, &INFO);
   if (INFO < 0)
     {
       return std::numeric_limits< C_FLOAT64 >::infinity();
     }
   C_FLOAT64 Error = 0;
   if (RANK != M)
     {
       // We need to check whether the || Ax - b || is sufficiently small.
       // Calculate Ax
       char T = 'N';
       M = 1;
       C_FLOAT64 Alpha = 1.0;
       C_FLOAT64 Beta = 0.0;
       CVector< C_FLOAT64 > Ax = B;
       dgemm_(&T, &T, &M, &N, &N, &Alpha, X.array(), &M,
              mpJacobianX->array(), &N, &Beta, Ax.array(), &M);
       // Calculate absolute and relative error
       C_FLOAT64 *pAx = Ax.array();
       C_FLOAT64 *pAxEnd = pAx + Ax.size();
       const C_FLOAT64 *pB = B.array();
       C_FLOAT64 * pCurrentState = mpSteadyState->beginIndependent();
       const C_FLOAT64 * pAtol = mAtol.array();
       // Assure that all values are updated.
       mpModel->updateSimulatedValues(true);
       CModelEntity *const* ppEntity = mpModel->getStateTemplate().beginIndependent();
       const CMetab * pMetab = NULL;
       C_FLOAT64 Number2Quantity = mpModel->getNumber2QuantityFactor();
       C_FLOAT64 AbsoluteDistance = 0.0; // Largest relative distance
       C_FLOAT64 RelativeDistance = 0.0; // Total relative distance
       C_FLOAT64 tmp;
       for (; pAx != pAxEnd; ++pAx, ++pB, ++pCurrentState, ++pAtol, ++ppEntity)
         {
           // Prevent division by 0
           tmp = fabs(*pAx - *pB) / std::max(fabs(*pCurrentState), *pAtol);
           RelativeDistance += tmp * tmp;
           tmp = fabs(*pAx - *pB);
           if ((pMetab = dynamic_cast< const CMetab * >(*ppEntity)) != NULL)
             {
               tmp *= Number2Quantity / fabs(pMetab->getCompartment()->getValue());
             }
           AbsoluteDistance += tmp * tmp;
         }
       RelativeDistance =
         isnan(RelativeDistance) ? std::numeric_limits< C_FLOAT64 >::infinity() : sqrt(RelativeDistance);
       AbsoluteDistance =
         isnan(AbsoluteDistance) ? std::numeric_limits< C_FLOAT64 >::infinity() : sqrt(AbsoluteDistance);
       Error = std::max(RelativeDistance, AbsoluteDistance);
     }
   return Error;
 }
C_FLOAT64 CNewtonMethod::targetFunction (const CVector< C_FLOAT64 > & particleFluxes)
This is the function that is supposed to be near zero if a steady state is detected.
Parameters
const CVector< C_FLOAT64 > & particleFluxes
Definition at line 598 of file CNewtonMethod.cpp.
References CVectorCore< CType >::array(), CStateTemplate::beginIndependent(), CState::beginIndependent(), C_FLOAT64, CSteadyStateMethod::calculateJacobianX(), CMetab::getCompartment(), CModel::getNumber2QuantityFactor(), CModel::getStateTemplate(), CModelEntity::getValue(), mAtol, max, CSteadyStateMethod::mpModel, CSteadyStateMethod::mpSSResolution, CSteadyStateMethod::mpSteadyState, CVectorCore< CType >::size(), solveJacobianXeqB(), and CModel::updateSimulatedValues().
Referenced by doIntegration(), doNewtonStep(), and processNewton().
 {
   // New criterion: We solve Jacobian * x = current rates and compare x with the current state
   // Calculate the Jacobian
   calculateJacobianX(*mpSSResolution);
   CVector< C_FLOAT64 > Distance;
   C_FLOAT64 Error = solveJacobianXeqB(Distance, particlefluxes);
   // We look at all ODE determined entity and dependent species rates.
   C_FLOAT64 * pDistance = Distance.array();
   C_FLOAT64 * pDistanceEnd = pDistance + Distance.size();
   C_FLOAT64 * pCurrentState = mpSteadyState->beginIndependent();
   const C_FLOAT64 * pAtol = mAtol.array();
   // Assure that all values are updated.
   mpModel->updateSimulatedValues(true);
   CModelEntity *const* ppEntity = mpModel->getStateTemplate().beginIndependent();
   const CMetab * pMetab = NULL;
   C_FLOAT64 Number2Quantity = mpModel->getNumber2QuantityFactor();
   C_FLOAT64 AbsoluteDistance = 0.0; // Largest relative distance
   C_FLOAT64 RelativeDistance = 0.0; // Total relative distance
   C_FLOAT64 tmp;
   for (; pDistance != pDistanceEnd; ++pDistance, ++pCurrentState, ++pAtol, ++ppEntity)
     {
       // Prevent division by 0
       tmp = fabs(*pDistance) / std::max(fabs(*pCurrentState), *pAtol);
       RelativeDistance += tmp * tmp;
       tmp = fabs(*pDistance);
       if ((pMetab = dynamic_cast< const CMetab * >(*ppEntity)) != NULL)
         {
           tmp *= Number2Quantity / fabs(pMetab->getCompartment()->getValue());
         }
       AbsoluteDistance += tmp * tmp;
     }
   RelativeDistance =
     isnan(RelativeDistance) ? std::numeric_limits< C_FLOAT64 >::infinity() : sqrt(RelativeDistance);
   AbsoluteDistance =
     isnan(AbsoluteDistance) ? std::numeric_limits< C_FLOAT64 >::infinity() : sqrt(AbsoluteDistance);
   C_FLOAT64 TargetValue = std::max(RelativeDistance, AbsoluteDistance);
   if (Error < TargetValue)
     return TargetValue * (1.0 + Error);
   else
     return Error;
 }
Friends And Related Function Documentation
CSteadyStateMethod* CSteadyStateMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
bool CNewtonMethod::mAcceptNegative private
Definition at line 55 of file CNewtonMethod.h.
Referenced by doIntegration(), doNewtonStep(), and initialize().
CVector< C_FLOAT64 > CNewtonMethod::mAtol private
Definition at line 64 of file CNewtonMethod.h.
Referenced by initialize(), solveJacobianXeqB(), and targetFunction().
size_t CNewtonMethod::mDimension private
Definition at line 62 of file CNewtonMethod.h.
Referenced by doNewtonStep(), and initialize().
CVector< C_FLOAT64 > CNewtonMethod::mdxdt private
Definition at line 67 of file CNewtonMethod.h.
Referenced by calculateDerivativesX(), doIntegration(), doNewtonStep(), initialize(), and processNewton().
bool CNewtonMethod::mForceNewton private
Definition at line 56 of file CNewtonMethod.h.
Referenced by initialize(), and processNewton().
CVector< C_FLOAT64 > CNewtonMethod::mH private
Definition at line 65 of file CNewtonMethod.h.
Referenced by doNewtonStep(), and initialize().
C_INT* CNewtonMethod::mIpiv private
Definition at line 68 of file CNewtonMethod.h.
Referenced by cleanup(), and initialize().
unsigned C_INT32 CNewtonMethod::mIterationLimit private
Definition at line 58 of file CNewtonMethod.h.
Referenced by initialize(), and processNewton().
bool CNewtonMethod::mKeepProtocol private
Definition at line 57 of file CNewtonMethod.h.
Referenced by doIntegration(), doNewtonStep(), initialize(), processInternal(), and processNewton().
C_FLOAT64 CNewtonMethod::mMaxDurationBackward private
Definition at line 60 of file CNewtonMethod.h.
Referenced by doIntegration(), and initialize().
C_FLOAT64 CNewtonMethod::mMaxDurationForward private
Definition at line 59 of file CNewtonMethod.h.
Referenced by doIntegration(), and initialize().
CTrajectoryTask* CNewtonMethod::mpTrajectory private
Definition at line 70 of file CNewtonMethod.h.
Referenced by cleanup(), doIntegration(), and initialize().
C_FLOAT64* CNewtonMethod::mpX private
Definition at line 63 of file CNewtonMethod.h.
Referenced by doNewtonStep(), and processInternal().
CState CNewtonMethod::mStartState private
Definition at line 72 of file CNewtonMethod.h.
Referenced by doIntegration(), and processInternal().
bool CNewtonMethod::mUseBackIntegration private
Definition at line 54 of file CNewtonMethod.h.
Referenced by initialize(), and processInternal().
bool CNewtonMethod::mUseIntegration private
Definition at line 53 of file CNewtonMethod.h.
Referenced by initialize(), and processInternal().
bool CNewtonMethod::mUseNewton private
Definition at line 52 of file CNewtonMethod.h.
Referenced by doIntegration(), initialize(), and processInternal().
CVector< C_FLOAT64 > CNewtonMethod::mXold private
Definition at line 66 of file CNewtonMethod.h.
Referenced by doNewtonStep(), and initialize().
The documentation for this class was generated from the following files:
CNewtonMethod.h
CNewtonMethod.cpp