COPASI API: CQEventsWidget Class Reference
CQEventsWidget Class Reference
#include <CQEventsWidget.h>
Public Member Functions
CQEventsWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQEventsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
virtual void keyPressEvent (QKeyEvent *ev)
Private Member Functions
void deleteSelectedEvents ()
void updateDeleteBtns ()
Private Attributes
CQEventDM * mpEventDM
CQSortFilterProxyModel * mpProxyModel
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 30 of file CQEventsWidget.h.
Constructor & Destructor Documentation
CQEventsWidget::CQEventsWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 33 of file CQEventsWidget.cpp.
References COL_ROW_NUMBER, dataChanged(), mpEventDM, mpProxyModel, CopasiWidget::protectedNotify(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpEventDM = new CQEventDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpTblEvents->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblEvents->verticalHeader()->hide();
   mpTblEvents->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   // Connect the table widget
   connect(mpEventDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpEventDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
 }
CQEventsWidget::~CQEventsWidget ()
Definition at line 62 of file CQEventsWidget.cpp.
References mpEventDM, mpProxyModel, and pdelete.
 {
   pdelete(mpProxyModel);
   pdelete(mpEventDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQEventsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 188 of file CQEventsWidget.cpp.
References updateDeleteBtns().
Referenced by CQEventsWidget().
 {
   mpTblEvents->resizeColumnsToContents();
   updateDeleteBtns();
 }
void CQEventsWidget::deleteSelectedEvents () private
Definition at line 83 of file CQEventsWidget.cpp.
References mpEventDM, mpProxyModel, CQEventDM::removeRows(), and CQEventDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblEvents->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpEventDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpEventDM->removeRows(mappedSelRows);
 }
bool CQEventsWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 133 of file CQEventsWidget.cpp.
References mpEventDM, mpProxyModel, slotSelectionChanged(), and updateDeleteBtns().
Referenced by update().
 {
   if (mpTblEvents->selectionModel() != NULL)
     {
       disconnect(mpTblEvents->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpProxyModel->setSourceModel(mpEventDM);
   //Set Model for the TableView
   mpTblEvents->setModel(NULL);
   mpTblEvents->setModel(mpProxyModel);
   connect(mpTblEvents->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblEvents->resizeColumnsToContents();
   return true;
 }
void CQEventsWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 221 of file CQEventsWidget.cpp.
References CQEventDM::columnCount(), mpEventDM, mpProxyModel, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C && (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblEvents->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpEventDM->columnCount(); ++x)
             {
               if (!mpTblEvents->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpEventDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQEventsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 128 of file CQEventsWidget.cpp.
 {
   return true;
 }
void CQEventsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 104 of file CQEventsWidget.cpp.
References CQBaseDataModel::clear(), mpEventDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Events?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpEventDM->clear();
     }
   updateDeleteBtns();
 }
void CQEventsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 75 of file CQEventsWidget.cpp.
References deleteSelectedEvents(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblEvents->hasFocus())
     {deleteSelectedEvents();}
   updateDeleteBtns();
 }
void CQEventsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 69 of file CQEventsWidget.cpp.
References CQBaseDataModel::insertRow(), mpEventDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpEventDM->insertRow();
   updateDeleteBtns();
 }
void CQEventsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 195 of file CQEventsWidget.cpp.
References C_INVALID_INDEX, CCopasiRootContainer::getDatamodelList(), CModel::getEvents(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CQBaseDataModel::isDefaultRow(), mpEventDM, CopasiWidget::mpListView, mpProxyModel, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpEventDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return;
   std::string key = pModel->getEvents()[index.row()]->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQEventsWidget::slotFilterChanged () protected virtual slot
Definition at line 255 of file CQEventsWidget.cpp.
References mpProxyModel.
Referenced by CQEventsWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Event", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQEventsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 182 of file CQEventsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQEventsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 118 of file CQEventsWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQEventsWidget::updateDeleteBtns () private
Definition at line 153 of file CQEventsWidget.cpp.
References CQBaseDataModel::isDefaultRow(), mpEventDM, and mpProxyModel.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblEvents->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpEventDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
CQEventDM* CQEventsWidget::mpEventDM private
Definition at line 42 of file CQEventsWidget.h.
Referenced by CQEventsWidget(), deleteSelectedEvents(), enterProtected(), keyPressEvent(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQEventsWidget().
CQSortFilterProxyModel* CQEventsWidget::mpProxyModel private
Definition at line 43 of file CQEventsWidget.h.
Referenced by CQEventsWidget(), deleteSelectedEvents(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQEventsWidget().
The documentation for this class was generated from the following files:
CQEventsWidget.h
CQEventsWidget.cpp