COPASI API: CQCompartmentsWidget Class Reference
CQCompartmentsWidget Class Reference
#include <CQCompartmentsWidget.h>
Public Member Functions
CQCompartmentsWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQCompartmentsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *ev)
Private Member Functions
void deleteSelectedCompartments ()
virtual bool enterProtected ()
void updateDeleteBtns ()
Private Attributes
CQCompartmentDM * mpCompartmentDM
CQSortFilterProxyModel * mpProxyModel
CQIndexComboDelegate * mpTypeDelegate
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 30 of file CQCompartmentsWidget.h.
Constructor & Destructor Documentation
CQCompartmentsWidget::CQCompartmentsWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 29 of file CQCompartmentsWidget.cpp.
References COL_ROW_NUMBER, COL_TYPE_COMPARTMENTS, dataChanged(), CQCompartmentDM::getTypes(), mpCompartmentDM, mpProxyModel, mpTypeDelegate, CopasiWidget::protectedNotify(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpCompartmentDM = new CQCompartmentDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   //Setting values for Types comboBox
   mpTypeDelegate = new CQIndexComboDelegate(&mpCompartmentDM->getTypes(), this);
   mpTblCompartments->setItemDelegateForColumn(COL_TYPE_COMPARTMENTS, mpTypeDelegate);
   mpTblCompartments->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblCompartments->verticalHeader()->hide();
   mpTblCompartments->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   // Connect the table widget
   connect(mpCompartmentDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpCompartmentDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
 }
CQCompartmentsWidget::~CQCompartmentsWidget () virtual
Definition at line 62 of file CQCompartmentsWidget.cpp.
References mpCompartmentDM, mpProxyModel, mpTypeDelegate, and pdelete.
 {
   pdelete(mpTypeDelegate);
   pdelete(mpProxyModel);
   pdelete(mpCompartmentDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQCompartmentsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 188 of file CQCompartmentsWidget.cpp.
References updateDeleteBtns().
Referenced by CQCompartmentsWidget().
 {
   mpTblCompartments->resizeColumnsToContents();
   updateDeleteBtns();
 }
void CQCompartmentsWidget::deleteSelectedCompartments () private
Definition at line 84 of file CQCompartmentsWidget.cpp.
References mpCompartmentDM, mpProxyModel, CQCompartmentDM::removeRows(), and CQCompartmentDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblCompartments->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpCompartmentDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpCompartmentDM->removeRows(mappedSelRows);
 }
bool CQCompartmentsWidget::enterProtected () private virtual
Reimplemented from CopasiWidget.
Definition at line 133 of file CQCompartmentsWidget.cpp.
References mpCompartmentDM, mpProxyModel, slotSelectionChanged(), and updateDeleteBtns().
Referenced by update().
 {
   if (mpTblCompartments->selectionModel() != NULL)
     {
       disconnect(mpTblCompartments->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpProxyModel->setSourceModel(mpCompartmentDM);
   //Set Model for the TableView
   mpTblCompartments->setModel(NULL);
   mpTblCompartments->setModel(mpProxyModel);
   connect(mpTblCompartments->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblCompartments->resizeColumnsToContents();
   return true;
 }
void CQCompartmentsWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 221 of file CQCompartmentsWidget.cpp.
References CQCompartmentDM::columnCount(), mpCompartmentDM, mpProxyModel, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C && (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblCompartments->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpCompartmentDM->columnCount(); ++x)
             {
               if (!mpTblCompartments->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpCompartmentDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQCompartmentsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 128 of file CQCompartmentsWidget.cpp.
 {
   return true;
 }
void CQCompartmentsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 105 of file CQCompartmentsWidget.cpp.
References CQBaseDataModel::clear(), mpCompartmentDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Compartments?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpCompartmentDM->clear();
     }
   updateDeleteBtns();
 }
void CQCompartmentsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 76 of file CQCompartmentsWidget.cpp.
References deleteSelectedCompartments(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblCompartments->hasFocus())
     {deleteSelectedCompartments();}
   updateDeleteBtns();
 }
void CQCompartmentsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 70 of file CQCompartmentsWidget.cpp.
References CQBaseDataModel::insertRow(), mpCompartmentDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpCompartmentDM->insertRow();
   updateDeleteBtns();
 }
void CQCompartmentsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 195 of file CQCompartmentsWidget.cpp.
References C_INVALID_INDEX, CModel::getCompartments(), CCopasiRootContainer::getDatamodelList(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CQBaseDataModel::isDefaultRow(), mpCompartmentDM, CopasiWidget::mpListView, mpProxyModel, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpCompartmentDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return;
   std::string key = pModel->getCompartments()[index.row()]->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQCompartmentsWidget::slotFilterChanged () protected virtual slot
Definition at line 255 of file CQCompartmentsWidget.cpp.
References mpProxyModel.
Referenced by CQCompartmentsWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Compartment", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQCompartmentsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 182 of file CQCompartmentsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQCompartmentsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 118 of file CQCompartmentsWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQCompartmentsWidget::updateDeleteBtns () private
Definition at line 153 of file CQCompartmentsWidget.cpp.
References CQBaseDataModel::isDefaultRow(), mpCompartmentDM, and mpProxyModel.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblCompartments->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpCompartmentDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
CQCompartmentDM* CQCompartmentsWidget::mpCompartmentDM private
Definition at line 42 of file CQCompartmentsWidget.h.
Referenced by CQCompartmentsWidget(), deleteSelectedCompartments(), enterProtected(), keyPressEvent(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQCompartmentsWidget().
CQSortFilterProxyModel* CQCompartmentsWidget::mpProxyModel private
Definition at line 43 of file CQCompartmentsWidget.h.
Referenced by CQCompartmentsWidget(), deleteSelectedCompartments(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQCompartmentsWidget().
CQIndexComboDelegate* CQCompartmentsWidget::mpTypeDelegate private
Definition at line 44 of file CQCompartmentsWidget.h.
Referenced by CQCompartmentsWidget(), and ~CQCompartmentsWidget().
The documentation for this class was generated from the following files:
CQCompartmentsWidget.h
CQCompartmentsWidget.cpp