COPASI API: CScanMethod Class Reference
CScanMethod Class Reference
#include <CScanMethod.h>
Public Member Functions
size_t getTotalNumberOfSteps () const
bool init ()
virtual bool isValidProblem (const CCopasiProblem *pProblem)
bool scan ()
void setProblem (CScanProblem *problem)
~CScanMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CScanMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::scanMethod)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
CScanMethod (CCopasiMethod::SubType subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
bool mContinueFromCurrentState
std::vector< Refresh * > mInitialRefreshes
size_t mLastNestingItem
CScanProblem * mpProblem
CRandom * mpRandomGenerator
CScanTask * mpTask
std::vector< CScanItem * > mScanItems
size_t mTotalSteps
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
bool calculate ()
bool cleanupScanItems ()
CScanMethod ()
bool loop (size_t level)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 159 of file CScanMethod.h.
Constructor & Destructor Documentation
CScanMethod::CScanMethod () private
Default constructor.
Definition at line 353 of file CScanMethod.cpp.
References CRandom::createGenerator(), mpRandomGenerator, and CRandom::r250.
Referenced by createMethod().
                         :
   CCopasiMethod(CCopasiTask::scan, CCopasiMethod::scanMethod),
   mpProblem(NULL),
   mpTask(NULL),
   mpRandomGenerator(NULL),
   mTotalSteps(1),
   mLastNestingItem(C_INVALID_INDEX),
   mContinueFromCurrentState(false)
 {
   mpRandomGenerator = CRandom::createGenerator(CRandom::r250);
 }
CScanMethod::CScanMethod (CCopasiMethod::SubType subType, const CCopasiContainer * pParent = NULL) protected
Specific constructor.
Parameters
CCopasiMethod::SubType subType
const CCopasiContainer * pParent (default: NULL)
CScanMethod::~CScanMethod ()
Copy constructor.
Parameters
const CTrajectoryMethod & src Destructor.
Definition at line 365 of file CScanMethod.cpp.
References cleanupScanItems(), and mpRandomGenerator.
 {
   cleanupScanItems();
   delete mpRandomGenerator;
   mpRandomGenerator = NULL;
 }
Member Function Documentation
bool CScanMethod::calculate (void) private
Definition at line 508 of file CScanMethod.cpp.
References mInitialRefreshes, mpTask, and CScanTask::processCallback().
Referenced by loop(), and scan().
 {
   std::vector< Refresh * >::iterator it = mInitialRefreshes.begin();
   std::vector< Refresh * >::iterator end = mInitialRefreshes.end();
   while (it != end)
     (**it++)();
   return mpTask->processCallback();
 }
bool CScanMethod::cleanupScanItems () private
Definition at line 372 of file CScanMethod.cpp.
References mpProblem, and mScanItems.
Referenced by init(), and ~CScanMethod().
 {
   if (!mpProblem) return false;
   size_t i, imax = mScanItems.size();
   for (i = 0; i < imax; ++i) if (mScanItems[i]) delete mScanItems[i];
   mScanItems.clear();
   return true;
 }
CScanMethod * CScanMethod::createMethod (CCopasiMethod::SubType subType = CCopasiMethod::scanMethod) static
Create a trajectory method. Note: the returned object has to be released after use with delete
Definition at line 348 of file CScanMethod.cpp.
References CScanMethod().
Referenced by CScanTask::createMethod().
 {
   return new CScanMethod();
 }
size_t CScanMethod::getTotalNumberOfSteps () const inline
Definition at line 243 of file CScanMethod.h.
References mTotalSteps.
Referenced by CScanTask::process().
 {return mTotalSteps;};
bool CScanMethod::init ()
Definition at line 384 of file CScanMethod.cpp.
References CModel::buildInitialRefreshSequence(), CCopasiObject::buildUpdateSequence(), C_INVALID_INDEX, cleanupScanItems(), CScanItem::createScanItemFromParameterGroup(), CScanProblem::getContinueFromCurrentState(), CCopasiProblem::getModel(), CScanProblem::getNumberOfScanItems(), CScanItem::getNumSteps(), CScanItem::getObject(), CCopasiObject::getObjectParent(), CScanProblem::getScanItem(), CModel::getUptoDateObjects(), mContinueFromCurrentState, mInitialRefreshes, mLastNestingItem, mpProblem, mpRandomGenerator, mpTask, mScanItems, and mTotalSteps.
Referenced by CScanTask::process().
 {
   if (!mpProblem) return false;
   mpTask = dynamic_cast< CScanTask * >(getObjectParent());
   if (mpTask == NULL) return false;
   cleanupScanItems();
   mInitialRefreshes.clear();
   //mTransientRefreshes.clear();
   mTotalSteps = 1;
   std::set< const CCopasiObject * > InitialObjectSet;
   std::set< const CCopasiObject * > TransientObjectSet;
   size_t i, imax = mpProblem->getNumberOfScanItems();
   mContinueFromCurrentState = mpProblem->getContinueFromCurrentState();
   for (i = 0; i < imax; ++i)
     {
       CScanItem * pItem = CScanItem::createScanItemFromParameterGroup(mpProblem->getScanItem(i),
                           mpRandomGenerator,
                           mContinueFromCurrentState);
       if (pItem == NULL)
         {
           continue;
         }
       mScanItems.push_back(pItem);
       mTotalSteps *= pItem->getNumSteps() + 1;
       if (pItem->getObject() != NULL)
         {
           InitialObjectSet.insert(pItem->getObject());
         }
     }
   if (mContinueFromCurrentState)
     {
       mInitialRefreshes = CCopasiObject::buildUpdateSequence(mpProblem->getModel()->getUptoDateObjects(), InitialObjectSet);
     }
   else
     {
       mInitialRefreshes = mpProblem->getModel()->buildInitialRefreshSequence(InitialObjectSet);
     }
   //set mLastNestingItem
   mLastNestingItem = C_INVALID_INDEX;
   if (imax != 0)
     {
       //search from the end
       size_t j;
       for (j = mScanItems.size() - 1; j != C_INVALID_INDEX; --j)
         {
           if (mScanItems[j]->isNesting())
             {
               mLastNestingItem = j;
               break;
             }
         }
     }
   return true;
 }
bool CScanMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
The main scan method. Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
Definition at line 523 of file CScanMethod.cpp.
References CScanItem::createScanItemFromParameterGroup(), CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CScanProblem::getContinueFromCurrentState(), CScanProblem::getNumberOfScanItems(), CScanProblem::getScanItem(), CCopasiMethod::isValidProblem(), CScanItem::isValidScanItem(), mContinueFromCurrentState, mpProblem, mpRandomGenerator, and CCopasiMessage::WARNING.
 {
   if (!CCopasiMethod::isValidProblem(pProblem)) return false;
   const CScanProblem * pP = dynamic_cast<const CScanProblem *>(pProblem);
   if (!pP)
     {
       //not a TrajectoryProblem
       CCopasiMessage(CCopasiMessage::EXCEPTION, "Problem is not a Scan problem.");
       return false;
     }
   mContinueFromCurrentState = pP->getContinueFromCurrentState();
   size_t i, imax = pP->getNumberOfScanItems();
   if (imax <= 0)
     {
       //no scan items
       CCopasiMessage(CCopasiMessage::WARNING, "There is nothing to scan.");
       return false;
     }
   for (i = 0; i < imax; ++i)
     {
       CScanItem * si = CScanItem::createScanItemFromParameterGroup(mpProblem->getScanItem(i),
                        mpRandomGenerator,
                        mContinueFromCurrentState);
       if (!si)
         {
           //parameter group could not be interpreted
           CCopasiMessage(CCopasiMessage::ERROR, "Internal problem with scan definition.");
           return false;
         }
       if (!si->isValidScanItem(mContinueFromCurrentState))
         {
           //the self check of the scan item failed.
           //the message should be generated by the isValidScanItem() method.
           delete si;
           return false;
         }
       delete si;
       //mTotalSteps *= mScanItems[i]->getNumSteps();
     }
   return true;
 }
bool CScanMethod::loop (size_t level) private
Definition at line 481 of file CScanMethod.cpp.
References calculate(), CCopasiObject::getObjectParent(), CScanItem::isFinished(), CScanItem::isNesting(), mLastNestingItem, mScanItems, CScanItem::reset(), and CScanItem::step().
Referenced by scan().
 {
   bool isLastMasterItem = (level == (mScanItems.size() - 1)); //TODO
   CScanItem* currentSI = mScanItems[level];
   for (currentSI->reset(); !currentSI->isFinished(); currentSI->step())
     {
       //TODO: handle slave SIs
       if (isLastMasterItem)
         {
           if (!calculate()) return false;
         }
       else
         {
           if (!loop(level + 1)) return false;
         } //TODO
       //separator needs to be handled slightly differently if we are at the last item
       if (currentSI->isNesting())
         ((CScanTask*)(getObjectParent()))->outputSeparatorCallback(level == mLastNestingItem);
     }
   return true;
 }
bool CScanMethod::scan ()
Definition at line 453 of file CScanMethod.cpp.
References calculate(), loop(), mpProblem, and mScanItems.
Referenced by CScanTask::process().
 {
   if (!mpProblem) return false;
   //a hack to ensure that the first subtask is run with initial conditions
   //pDataModel->getModel()->setState(&mpProblem->getInitialState());
   bool success = true;
   size_t i, imax = mScanItems.size();
   //store old parameter values
   for (i = 0; i < imax; ++i)
     mScanItems[i]->storeValue();
   //Do the scan...
   if (imax) //there are scan items
     success = loop(0);
   else
     success = calculate(); //nothing to scan, only one call to the subtask
   //restore old parameter values
   for (i = 0; i < imax; ++i)
     mScanItems[i]->restoreValue();
   return success;
 }
void CScanMethod::setProblem (CScanProblem * problem)
Set a pointer to the problem. This method is used by CTrajectory
Parameters
CTrajectoryProblem * problem
Definition at line 519 of file CScanMethod.cpp.
References mpProblem.
Referenced by CScanTask::process().
 {mpProblem = problem;}
Member Data Documentation
bool CScanMethod::mContinueFromCurrentState protected
Variable indicating whether the subtask shall continue from the current state or the initial state
Definition at line 195 of file CScanMethod.h.
Referenced by init(), and isValidProblem().
std::vector< Refresh * > CScanMethod::mInitialRefreshes protected
Definition at line 179 of file CScanMethod.h.
Referenced by calculate(), and init().
size_t CScanMethod::mLastNestingItem protected
the index of the last item that has several subitems, also the last item that need to generate output separators
Definition at line 189 of file CScanMethod.h.
Referenced by init(), and loop().
CScanProblem* CScanMethod::mpProblem protected
A pointer to the trajectory problem.
Definition at line 165 of file CScanMethod.h.
Referenced by cleanupScanItems(), init(), isValidProblem(), scan(), and setProblem().
CRandom* CScanMethod::mpRandomGenerator protected
A pointer to the random number generator
Definition at line 175 of file CScanMethod.h.
Referenced by CScanMethod(), init(), isValidProblem(), and ~CScanMethod().
CScanTask* CScanMethod::mpTask protected
A pointer to the scan Task.
Definition at line 170 of file CScanMethod.h.
Referenced by calculate(), and init().
std::vector<CScanItem*> CScanMethod::mScanItems protected
Definition at line 177 of file CScanMethod.h.
Referenced by cleanupScanItems(), init(), loop(), and scan().
size_t CScanMethod::mTotalSteps protected
Definition at line 183 of file CScanMethod.h.
Referenced by getTotalNumberOfSteps(), and init().
The documentation for this class was generated from the following files:
CScanMethod.h
CScanMethod.cpp