COPASI API: CEvaluationNodeNormalizer Class Reference
CEvaluationNodeNormalizer Class Reference
#include <CEvaluationNodeNormalizer.h>
Static Public Member Functions
static CEvaluationNode * normalize (const CEvaluationNode *node)
Static Private Member Functions
static CEvaluationNodeOperator * buildOperatorBranchFromChain (CEvaluationNodeOperator::SubType subType, const std::vector< CEvaluationNode * > &chainNodes)
static bool collectIdenticalBranches (CEvaluationNodeOperator::SubType subType, std::vector< CEvaluationNode * > &chainNodes)
static bool eliminateMultipleNumbers (CEvaluationNodeOperator::SubType subType, std::vector< CEvaluationNode * > &chainNodes)
static void findChainNodes (CEvaluationNodeOperator *pNode, std::vector< CEvaluationNode * > &nodes)
static CEvaluationNode * normalizeCEvaluationNodeCall (const CEvaluationNodeCall *pNode)
static CEvaluationNode * normalizeCEvaluationNodeChoice (const CEvaluationNodeChoice *pNode)
static CEvaluationNode * normalizeCEvaluationNodeConstant (const CEvaluationNodeConstant *pNode)
static CEvaluationNode * normalizeCEvaluationNodeDelay (const CEvaluationNodeDelay *pNode)
static CEvaluationNode * normalizeCEvaluationNodeFunction (const CEvaluationNodeFunction *pNode)
static CEvaluationNode * normalizeCEvaluationNodeLogical (const CEvaluationNodeLogical *pNode)
static CEvaluationNode * normalizeCEvaluationNodeNumber (const CEvaluationNodeNumber *pNode)
static CEvaluationNode * normalizeCEvaluationNodeObject (const CEvaluationNodeObject *pNode)
static CEvaluationNode * normalizeCEvaluationNodeOperator (const CEvaluationNodeOperator *pNode)
static CEvaluationNode * normalizeCEvaluationNodeStructure (const CEvaluationNodeStructure *pNode)
static CEvaluationNode * normalizeCEvaluationNodeVariable (const CEvaluationNodeVariable *pNode)
static CEvaluationNode * normalizeCEvaluationNodeVector (const CEvaluationNodeVector *pNode)
static CEvaluationNode * normalizeCEvaluationNodeWhiteSpace (const CEvaluationNodeWhiteSpace *pNode)
static CEvaluationNode * normalizeDivideNode (const CEvaluationNodeOperator *pNode)
static CEvaluationNode * normalizeMinusNode (const CEvaluationNodeOperator *pNode)
static CEvaluationNode * normalizeModulusNode (const CEvaluationNodeOperator *pNode)
static CEvaluationNode * normalizeMultiplyNode (const CEvaluationNodeOperator *pNode)
static CEvaluationNode * normalizePlusNode (const CEvaluationNodeOperator *pNode)
static CEvaluationNode * normalizePowerNode (const CEvaluationNodeOperator *pNode)
static bool reorderNodes (std::vector< CEvaluationNode * > &chainNodes)
Static Private Attributes
static const double ZERO = 1e-100
Detailed Description
Definition at line 39 of file CEvaluationNodeNormalizer.h.
Member Function Documentation
CEvaluationNodeOperator * CEvaluationNodeNormalizer::buildOperatorBranchFromChain (CEvaluationNodeOperator::SubType subType, const std::vector< CEvaluationNode * > & chainNodes) static private
Definition at line 1171 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeOperator::DIVIDE, fatalError, CEvaluationNodeOperator::MINUS, CEvaluationNodeOperator::MODULUS, CEvaluationNodeOperator::MULTIPLY, CEvaluationNodeOperator::PLUS, CEvaluationNodeOperator::POWER, and pResult.
Referenced by normalizeMultiplyNode(), and normalizePlusNode().
 {
   CEvaluationNodeOperator* pResult = NULL;
   std::string data;
   switch (subType)
     {
       case CEvaluationNodeOperator::POWER:
         data = "^";
         break;
       case CEvaluationNodeOperator::MULTIPLY:
         data = "*";
         break;
       case CEvaluationNodeOperator::DIVIDE:
         data = "/";
         break;
       case CEvaluationNodeOperator::MODULUS:
         data = "%";
         break;
       case CEvaluationNodeOperator::PLUS:
         data = "+";
         break;
       case CEvaluationNodeOperator::MINUS:
         data = "-";
         break;
       default:
         fatalError();
         break;
     }
   if (chainNodes.size() > 1)
     {
       std::vector<CEvaluationNode*>::const_reverse_iterator it = chainNodes.rbegin(), endit = chainNodes.rend();
       CEvaluationNodeOperator* pTmpOperator = new CEvaluationNodeOperator(subType, data);
       // add the first child
       pTmpOperator->addChild(*it);
       ++it;
       --endit;
       while (it != endit)
         {
           pTmpOperator->addChild(*it);
           pResult = new CEvaluationNodeOperator(subType, data);
           pResult->addChild(pTmpOperator);
           pTmpOperator = pResult;
           ++it;
         }
       // add the last child
       pResult->addChild(*it);
     }
   return pResult;
 }
bool CEvaluationNodeNormalizer::collectIdenticalBranches (CEvaluationNodeOperator::SubType subType, std::vector< CEvaluationNode * > & chainNodes) static private
Definition at line 1226 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::create(), CCopasiNode< _Data >::getData(), CEvaluationNode::getType(), CEvaluationNodeNumber::INTEGER, CEvaluationNodeOperator::MULTIPLY, CEvaluationNodeOperator::PLUS, and CEvaluationNodeOperator::POWER.
Referenced by normalizeMultiplyNode(), and normalizePlusNode().
 {
   bool changed = false;
   if (chainNodes.size() > 1)
     {
       // what is done depends on the subtype
       // if it is an additon we replace identical nodes with a multiplication of
       // the node with the number of occurences
       // for a multiplication it's the same, but we use a power instead of a
       // multiplication
       if (subType == CEvaluationNodeOperator::MULTIPLY || subType == CEvaluationNodeOperator::PLUS)
         {
           CEvaluationNodeOperator* pOperation = (subType == CEvaluationNodeOperator::MULTIPLY) ? new CEvaluationNodeOperator(CEvaluationNodeOperator::POWER, "^") : new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
           std::vector<CEvaluationNode*>::iterator it = chainNodes.begin(), endit = chainNodes.end();
           std::map<CEvaluationNode, unsigned int> occurenceMap;
           while (it != endit)
             {
               std::map<CEvaluationNode, unsigned int>::iterator pos = occurenceMap.find(**it);
               if (pos == occurenceMap.end())
                 {
                   occurenceMap[**it] = 1;
                 }
               else
                 {
                   ++(pos->second);
                   changed = true;
                 }
               // delete the node
               delete(*it);
               ++it;
             }
           chainNodes.clear();
           // convert the contents of the occurenceMap to new nodes
           std::map<CEvaluationNode, unsigned int>::const_iterator mapIt = occurenceMap.begin(), mapEndit = occurenceMap.end();
           std::ostringstream os;
           while (mapIt != mapEndit)
             {
               os << mapIt->second;
               CEvaluationNodeNumber* pNumberNode = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, os.str());
               CEvaluationNodeOperator* pNewOperator = dynamic_cast<CEvaluationNodeOperator*>(CEvaluationNode::create(pOperation->getType(), pOperation->getData()));
               pNewOperator->addChild(pNumberNode);
               pNewOperator->addChild(mapIt->first.copyBranch());
               chainNodes.push_back(pNewOperator);
               os.str("");
               ++mapIt;
             }
           delete pOperation;
         }
     }
   return changed;
 }
bool CEvaluationNodeNormalizer::eliminateMultipleNumbers (CEvaluationNodeOperator::SubType subType, std::vector< CEvaluationNode * > & chainNodes) static private
Definition at line 1077 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::getValue(), CEvaluationNodeOperator::MULTIPLY, and CEvaluationNodeOperator::PLUS.
Referenced by normalizeMultiplyNode(), and normalizePlusNode().
 {
   // check if there are several numerical values in the operator chain and
   // evaluate those operations
   bool changed = false;
   if (chainNodes.size() > 1)
     {
       std::vector<CEvaluationNode*>::iterator it = chainNodes.begin(), endit = chainNodes.end();
       if (subType == CEvaluationNodeOperator::MULTIPLY || subType == CEvaluationNodeOperator::PLUS)
         {
           double value = (subType == CEvaluationNodeOperator::MULTIPLY) ? 1.0 : 0.0;
           CEvaluationNodeNumber* pNumberNode = NULL;
           std::vector<CEvaluationNode*> numbers;
           while (it != endit)
             {
               pNumberNode = dynamic_cast<CEvaluationNodeNumber*>(*it);
               if (pNumberNode != NULL)
                 {
                   numbers.push_back(pNumberNode);
                   if (subType == CEvaluationNodeOperator::MULTIPLY)
                     {
                       value *= pNumberNode->getValue();
                     }
                   else
                     {
                       value += pNumberNode->getValue();
                     }
                 }
               ++it;
             }
           if (numbers.size() > 1)
             {
               changed = true;
               it = numbers.begin(), endit = numbers.end();
               // don't delete the last one since we reset it's value
               --endit;
               while (it != endit)
                 {
                   chainNodes.erase(std::find(chainNodes.begin(), chainNodes.end(), *it));
                   delete *it;
                   ++it;
                 }
               std::ostringstream os;
               os << value;
               (*it)->setData(os.str());
             }
         }
     }
   return changed;
 }
void CEvaluationNodeNormalizer::findChainNodes (CEvaluationNodeOperator * pNode, std::vector< CEvaluationNode * > & nodes) static private
Definition at line 1139 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CEvaluationNode::OPERATOR, CEvaluationNode::subType(), and CEvaluationNode::type().
Referenced by normalizeMultiplyNode(), and normalizePlusNode().
 {
   CEvaluationNodeOperator::SubType subType = (CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType());
   CEvaluationNode* pChild1 = dynamic_cast<CEvaluationNode*>(pNode->getChild());
   if (pChild1 != NULL)
     {
       CEvaluationNode* pChild2 = dynamic_cast<CEvaluationNode*>(pChild1->getSibling());
       if (pChild2 != NULL)
         {
           if (CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild1->getType())) == subType)
             {
               findChainNodes(dynamic_cast<CEvaluationNodeOperator*>(pChild1), nodes);
             }
           else
             {
               nodes.push_back(pChild1->copyBranch());
             }
           if (CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild2->getType())) == subType)
             {
               findChainNodes(dynamic_cast<CEvaluationNodeOperator*>(pChild2), nodes);
             }
           else
             {
               nodes.push_back(pChild2->copyBranch());
             }
         }
     }
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalize (const CEvaluationNode * node) static
Creates a normalized copy of the given CEvaluationNode.
Definition at line 45 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::CALL, CEvaluationNode::CHOICE, CEvaluationNode::CONSTANT, CEvaluationNode::copyBranch(), CEvaluationNode::DELAY, CEvaluationNode::FUNCTION, CEvaluationNode::getType(), CEvaluationNode::INVALID, CEvaluationNode::LOGICAL, CEvaluationNode::MV_FUNCTION, normalizeCEvaluationNodeCall(), normalizeCEvaluationNodeChoice(), normalizeCEvaluationNodeConstant(), normalizeCEvaluationNodeDelay(), normalizeCEvaluationNodeFunction(), normalizeCEvaluationNodeLogical(), normalizeCEvaluationNodeNumber(), normalizeCEvaluationNodeObject(), normalizeCEvaluationNodeOperator(), normalizeCEvaluationNodeStructure(), normalizeCEvaluationNodeVariable(), normalizeCEvaluationNodeVector(), normalizeCEvaluationNodeWhiteSpace(), CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CEvaluationNode::OPERATOR, pResult, CEvaluationNode::STRUCTURE, CEvaluationNode::type(), CEvaluationNode::VARIABLE, CEvaluationNode::VECTOR, and CEvaluationNode::WHITESPACE.
Referenced by normalizeCEvaluationNodeCall(), normalizeCEvaluationNodeChoice(), normalizeCEvaluationNodeDelay(), normalizeCEvaluationNodeFunction(), normalizeCEvaluationNodeLogical(), normalizeCEvaluationNodeVector(), normalizeDivideNode(), normalizeMinusNode(), normalizeModulusNode(), normalizeMultiplyNode(), normalizePlusNode(), and normalizePowerNode().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       switch (CEvaluationNode::type(pNode->getType()))
         {
           case CEvaluationNode::INVALID:
             break;
           case CEvaluationNode::NUMBER:
             pResult = normalizeCEvaluationNodeNumber(dynamic_cast<const CEvaluationNodeNumber*>(pNode));
             break;
           case CEvaluationNode::CONSTANT:
             pResult = normalizeCEvaluationNodeConstant(dynamic_cast<const CEvaluationNodeConstant*>(pNode));
             break;
           case CEvaluationNode::DELAY:
             pResult = normalizeCEvaluationNodeDelay(dynamic_cast<const CEvaluationNodeDelay*>(pNode));
             break;
           case CEvaluationNode::OPERATOR:
             pResult = normalizeCEvaluationNodeOperator(dynamic_cast<const CEvaluationNodeOperator*>(pNode));
             break;
           case CEvaluationNode::OBJECT:
             pResult = normalizeCEvaluationNodeObject(dynamic_cast<const CEvaluationNodeObject*>(pNode));
             break;
           case CEvaluationNode::FUNCTION:
             pResult = normalizeCEvaluationNodeFunction(dynamic_cast<const CEvaluationNodeFunction*>(pNode));
             break;
           case CEvaluationNode::CALL:
             pResult = normalizeCEvaluationNodeCall(dynamic_cast<const CEvaluationNodeCall*>(pNode));
             break;
           case CEvaluationNode::STRUCTURE:
             pResult = normalizeCEvaluationNodeStructure(dynamic_cast<const CEvaluationNodeStructure*>(pNode));
             break;
           case CEvaluationNode::CHOICE:
             pResult = normalizeCEvaluationNodeChoice(dynamic_cast<const CEvaluationNodeChoice*>(pNode));
             break;
           case CEvaluationNode::VARIABLE:
             pResult = normalizeCEvaluationNodeVariable(dynamic_cast<const CEvaluationNodeVariable*>(pNode));
             break;
           case CEvaluationNode::WHITESPACE:
             pResult = normalizeCEvaluationNodeWhiteSpace(dynamic_cast<const CEvaluationNodeWhiteSpace*>(pNode));
             break;
           case CEvaluationNode::LOGICAL:
             pResult = normalizeCEvaluationNodeLogical(dynamic_cast<const CEvaluationNodeLogical*>(pNode));
             break;
           case CEvaluationNode::MV_FUNCTION:
             break;
           case CEvaluationNode::VECTOR:
             pResult = normalizeCEvaluationNodeVector(dynamic_cast<const CEvaluationNodeVector*>(pNode));
             break;
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeCall (const CEvaluationNodeCall * pNode) static private
Creates a normalized copy of the given CEvaluationNodeCall.
Definition at line 337 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNodeCall::addChild(), CEvaluationNode::copyBranch(), CEvaluationNode::create(), CEvaluationNodeCall::EXPRESSION, CEvaluationNodeCall::FUNCTION, CCopasiNode< _Data >::getChild(), CEvaluationNodeCall::getData(), CEvaluationNodeCall::getListOfChildNodes(), CEvaluationNode::getType(), CEvaluationNodeCall::INVALID, normalize(), pResult, CEvaluationNodeCall::removeChild(), and CEvaluationNode::subType().
Referenced by normalize().
 {
   CEvaluationNodeCall* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pTmpResult = NULL;
       CCopasiNode<std::string>* pTmpNode = NULL;
       switch ((CEvaluationNodeCall::SubType)CEvaluationNode::subType(pNode->getType()))
         {
           case CEvaluationNodeCall::INVALID:
             break;
           case CEvaluationNodeCall::EXPRESSION:
           case CEvaluationNodeCall::FUNCTION:
             pResult = dynamic_cast<CEvaluationNodeCall*>(CEvaluationNode::create(pNode->getType(), pNode->getData()));
             // add normalized call nodes
             const std::vector<CEvaluationNode*>& callNodes = pNode->getListOfChildNodes();
             std::vector<CEvaluationNode*>::const_iterator it = callNodes.begin(), endit = callNodes.end();
             while (it != endit)
               {
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(*it));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                   }
                 else
                   {
                     // delete all newly created call nodes
                     while (!pResult->getListOfChildNodes().empty())
                       {
                         pTmpNode = pResult->getChild();
                         pResult->removeChild(pTmpNode);
                         delete pTmpNode;
                       }
                     delete pResult;
                     pResult = NULL;
                     break;
                   }
                 ++it;
               }
             break;
         }
       if (pResult == NULL) pResult = static_cast<CEvaluationNodeCall*>(pNode->copyBranch());
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeChoice (const CEvaluationNodeChoice * pNode) static private
Creates a normalized copy of the given CEvaluationNodeChoice.
Definition at line 405 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNodeChoice::IF, CEvaluationNodeChoice::INVALID, normalize(), pResult, and CEvaluationNode::type().
Referenced by normalize().
 {
   CEvaluationNodeChoice* pResult = NULL;
   CEvaluationNode* pTmpResult;
   if (pNode != NULL)
     {
       switch ((CEvaluationNodeChoice::SubType)CEvaluationNode::type(pNode->getType()))
         {
           case CEvaluationNodeChoice::INVALID:
             break;
           case CEvaluationNodeChoice::IF:
             // create a new choice node with normalized if, true and false
             // elements
             pResult = new CEvaluationNodeChoice(CEvaluationNodeChoice::IF, "if");
             // if element
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
                 // true element
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                     // false element
                     pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()->getSibling()));
                     if (pTmpResult != NULL)
                       {
                         pResult->addChild(pTmpResult);
                       }
                     else
                       {
                         delete pResult;
                         pResult = NULL;
                       }
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                   }
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
         }
       if (pResult == NULL) pResult = static_cast<CEvaluationNodeChoice*>(pNode->copyBranch());
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeConstant (const CEvaluationNodeConstant * pNode) static private
Creates a normalized copy of the given CEvaluationNodeConstant.
Definition at line 118 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), and pResult.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       // copy the node
       pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeDelay (const CEvaluationNodeDelay * pNode) static private
Creates a normalized copy of the given CEvaluationNodeDelay.
Definition at line 288 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CEvaluationNodeDelay::DELAY, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CEvaluationNode::getType(), CEvaluationNodeDelay::INVALID, normalize(), pResult, and CEvaluationNode::subType().
Referenced by normalize().
 {
   CEvaluationNodeDelay* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pTmpResult = NULL;
       switch ((CEvaluationNodeDelay::SubType)CEvaluationNode::subType(pNode->getType()))
         {
           case CEvaluationNodeDelay::INVALID:
             break;
           case CEvaluationNodeDelay::DELAY:
             pResult = new CEvaluationNodeDelay((CEvaluationNodeDelay::SubType)CEvaluationNode::subType(pNode->getType()), pNode->getData());
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                   }
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
             break;
         }
       if (pResult == NULL)
         {
           pResult = static_cast<CEvaluationNodeDelay*>(pNode->copyBranch());
         }
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeFunction (const CEvaluationNodeFunction * pNode) static private
Creates a normalized copy of the given CEvaluationNodeFunction.
Definition at line 180 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNodeFunction::ABS, CCopasiNode< _Data >::addChild(), CEvaluationNodeFunction::ARCCOS, CEvaluationNodeFunction::ARCCOSH, CEvaluationNodeFunction::ARCCOT, CEvaluationNodeFunction::ARCCOTH, CEvaluationNodeFunction::ARCCSC, CEvaluationNodeFunction::ARCCSCH, CEvaluationNodeFunction::ARCSEC, CEvaluationNodeFunction::ARCSECH, CEvaluationNodeFunction::ARCSIN, CEvaluationNodeFunction::ARCSINH, CEvaluationNodeFunction::ARCTAN, CEvaluationNodeFunction::ARCTANH, CEvaluationNodeFunction::CEIL, CEvaluationNode::copyBranch(), CEvaluationNodeFunction::COS, CEvaluationNodeFunction::COSH, CEvaluationNodeFunction::COT, CEvaluationNodeFunction::COTH, CEvaluationNodeFunction::CSC, CEvaluationNodeFunction::CSCH, CEvaluationNodeFunction::EXP, CEvaluationNodeFunction::FACTORIAL, CEvaluationNodeFunction::FLOOR, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CEvaluationNode::getType(), CEvaluationNodeFunction::INVALID, CEvaluationNodeFunction::LOG, CEvaluationNodeFunction::LOG10, CEvaluationNodeFunction::MINUS, normalize(), CEvaluationNodeFunction::NOT, CEvaluationNodeFunction::PLUS, pResult, CEvaluationNodeFunction::RNORMAL, CEvaluationNodeFunction::RUNIFORM, CEvaluationNodeFunction::SEC, CEvaluationNodeFunction::SECH, CEvaluationNodeFunction::SIN, CEvaluationNodeFunction::SINH, CEvaluationNodeFunction::SQRT, CEvaluationNode::subType(), CEvaluationNodeFunction::TAN, and CEvaluationNodeFunction::TANH.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pTmpResult;
       switch ((CEvaluationNodeFunction::SubType)CEvaluationNode::subType(pNode->getType()))
         {
           case CEvaluationNodeFunction::INVALID:
             break;
           case CEvaluationNodeFunction::LOG:
           case CEvaluationNodeFunction::LOG10:
           case CEvaluationNodeFunction::EXP:
           case CEvaluationNodeFunction::SIN:
           case CEvaluationNodeFunction::COS:
           case CEvaluationNodeFunction::TAN:
           case CEvaluationNodeFunction::SEC:
           case CEvaluationNodeFunction::CSC:
           case CEvaluationNodeFunction::COT:
           case CEvaluationNodeFunction::SINH:
           case CEvaluationNodeFunction::COSH:
           case CEvaluationNodeFunction::TANH:
           case CEvaluationNodeFunction::SECH:
           case CEvaluationNodeFunction::CSCH:
           case CEvaluationNodeFunction::COTH:
           case CEvaluationNodeFunction::ARCSIN:
           case CEvaluationNodeFunction::ARCCOS:
           case CEvaluationNodeFunction::ARCTAN:
           case CEvaluationNodeFunction::ARCSEC:
           case CEvaluationNodeFunction::ARCCSC:
           case CEvaluationNodeFunction::ARCCOT:
           case CEvaluationNodeFunction::ARCSINH:
           case CEvaluationNodeFunction::ARCCOSH:
           case CEvaluationNodeFunction::ARCTANH:
           case CEvaluationNodeFunction::ARCSECH:
           case CEvaluationNodeFunction::ARCCSCH:
           case CEvaluationNodeFunction::ARCCOTH:
           case CEvaluationNodeFunction::SQRT:
           case CEvaluationNodeFunction::ABS:
           case CEvaluationNodeFunction::FLOOR:
           case CEvaluationNodeFunction::CEIL:
           case CEvaluationNodeFunction::FACTORIAL:
           case CEvaluationNodeFunction::NOT:
           case CEvaluationNodeFunction::MINUS:
             pResult = new CEvaluationNodeFunction((CEvaluationNodeFunction::SubType)CEvaluationNode::subType(pNode->getType()), pNode->getData());
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
             break;
           case CEvaluationNodeFunction::RUNIFORM:
           case CEvaluationNodeFunction::RNORMAL:
             //case CEvaluationNodeFunction::DELAY:
             // normalize all children
             pResult = new CEvaluationNodeFunction((CEvaluationNodeFunction::SubType)CEvaluationNode::subType(pNode->getType()), pNode->getData());
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                   }
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
             break;
             /*
             case CEvaluationNodeFunction::MINUS:
                 // relace the - by a multiplication with -1
                 // !!! Maybe this is not possible since CEvaluationNodeNumber
                 // elements can not hold negative numbers.
                 pResult=new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY,"");
             */
           case CEvaluationNodeFunction::PLUS:
             // eliminate the plus
             pResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
             break;
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeLogical (const CEvaluationNodeLogical * pNode) static private
Creates a normalized copy of the given CEvaluationNodeLogical.
Definition at line 477 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeLogical::AND, CEvaluationNode::copyBranch(), CEvaluationNodeLogical::EQ, CEvaluationNodeLogical::GE, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CEvaluationNode::getType(), CEvaluationNodeLogical::GT, CEvaluationNodeLogical::INVALID, CEvaluationNodeLogical::LE, CEvaluationNodeLogical::LT, CEvaluationNodeLogical::NE, normalize(), CEvaluationNodeLogical::OR, pResult, CEvaluationNode::subType(), and CEvaluationNodeLogical::XOR.
Referenced by normalize().
 {
   CEvaluationNodeLogical* pResult = NULL;
   CEvaluationNode* pTmpResult = NULL;
   if (pNode != NULL)
     {
       switch ((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()))
         {
           case CEvaluationNodeLogical::INVALID:
             break;
           case CEvaluationNodeLogical::OR:
           case CEvaluationNodeLogical::XOR:
           case CEvaluationNodeLogical::AND:
           case CEvaluationNodeLogical::EQ:
           case CEvaluationNodeLogical::NE:
           case CEvaluationNodeLogical::LT:
           case CEvaluationNodeLogical::LE:
             pResult = new CEvaluationNodeLogical((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()), pNode->getData());
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                   }
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
             break;
           case CEvaluationNodeLogical::GT:
             // turn the order of the operands and change to LT
             pResult = new CEvaluationNodeLogical(CEvaluationNodeLogical::LT, "<");
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                   }
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
             break;
           case CEvaluationNodeLogical::GE:
             // turn the order of the operands and change to LE
             pResult = new CEvaluationNodeLogical(CEvaluationNodeLogical::LE, "<=");
             pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
             if (pTmpResult != NULL)
               {
                 pResult->addChild(pTmpResult);
                 pTmpResult = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
                 if (pTmpResult != NULL)
                   {
                     pResult->addChild(pTmpResult);
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                   }
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
             break;
         }
       if (pResult == NULL) pResult = static_cast<CEvaluationNodeLogical*>(pNode->copyBranch());
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeNumber (const CEvaluationNodeNumber * pNode) static private
Creates a normalized copy of the given CEvaluationNodeNumber.
Definition at line 105 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), and pResult.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       // copy the node
       pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeObject (const CEvaluationNodeObject * pNode) static private
Creates a normalized copy of the given CEvaluationNodeObject.
Definition at line 167 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), and pResult.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       // copy the node
       pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeOperator (const CEvaluationNodeOperator * pNode) static private
Creates a normalized copy of the given CEvaluationNodeOperator.
Definition at line 131 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), CEvaluationNodeOperator::DIVIDE, CEvaluationNode::getType(), CEvaluationNodeOperator::INVALID, CEvaluationNodeOperator::MINUS, CEvaluationNodeOperator::MODULUS, CEvaluationNodeOperator::MULTIPLY, normalizeDivideNode(), normalizeMinusNode(), normalizeModulusNode(), normalizeMultiplyNode(), normalizePlusNode(), normalizePowerNode(), CEvaluationNodeOperator::PLUS, CEvaluationNodeOperator::POWER, pResult, and CEvaluationNode::subType().
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       switch ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pNode->getType()))
         {
           case CEvaluationNodeOperator::INVALID:
             break;
           case CEvaluationNodeOperator::POWER:
             pResult = CEvaluationNodeNormalizer::normalizePowerNode(pNode);
             break;
           case CEvaluationNodeOperator::MULTIPLY:
             pResult = CEvaluationNodeNormalizer::normalizeMultiplyNode(pNode);
             break;
           case CEvaluationNodeOperator::DIVIDE:
             pResult = CEvaluationNodeNormalizer::normalizeDivideNode(pNode);
             break;
           case CEvaluationNodeOperator::MODULUS:
             pResult = CEvaluationNodeNormalizer::normalizeModulusNode(pNode);
             break;
           case CEvaluationNodeOperator::PLUS:
             pResult = CEvaluationNodeNormalizer::normalizePlusNode(pNode);
             break;
           case CEvaluationNodeOperator::MINUS:
             pResult = CEvaluationNodeNormalizer::normalizeMinusNode(pNode);
             break;
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeStructure (const CEvaluationNodeStructure * pNode) static private
Creates a normalized copy of the given CEvaluationNodeStructure.
Definition at line 392 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), and pResult.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       // copy the node
       pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeVariable (const CEvaluationNodeVariable * pNode) static private
Creates a normalized copy of the given CEvaluationNodeVariable.
Definition at line 464 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), and pResult.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       // copy the node
       pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeVector (const CEvaluationNodeVector * pNode) static private
Creates a normalized copy of the given CEvaluationNodeVector.
Definition at line 595 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNodeVector::addChild(), CEvaluationNode::copyBranch(), CEvaluationNode::getType(), CEvaluationNodeVector::getVector(), CEvaluationNodeVector::INVALID, normalize(), pResult, CEvaluationNode::subType(), and CEvaluationNodeVector::VECTOR.
Referenced by normalize().
 {
   CEvaluationNodeVector* pResult = NULL;
   CEvaluationNode* pTmpResult;
   if (pNode != NULL)
     {
       const std::vector<CEvaluationNode*>* pItems;
       std::vector<CEvaluationNode*>::const_iterator it, endit;
       switch ((CEvaluationNodeVector::SubType)CEvaluationNode::subType(pNode->getType()))
         {
           case CEvaluationNodeVector::VECTOR:
             // create a new vector with normalized forms of all children
             pResult = new CEvaluationNodeVector();
             pItems = &pNode->getVector();
             it = pItems->begin();
             endit = pItems->end();
             while (it != endit)
               {
                 pTmpResult = CEvaluationNodeNormalizer::normalize(*it);
                 if (pTmpResult != NULL)
                   {
                     if (!pResult->addChild(pTmpResult))
                       {
                         delete pResult;
                         pResult = NULL;
                         break;
                       }
                   }
                 else
                   {
                     delete pResult;
                     pResult = NULL;
                     break;
                   }
                 ++it;
               }
             break;
           case CEvaluationNodeVector::INVALID:
             break;
         }
       if (pResult == NULL) pResult = static_cast<CEvaluationNodeVector*>(pNode->copyBranch());
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeCEvaluationNodeWhiteSpace (const CEvaluationNodeWhiteSpace * pNode) static private
Creates a normalized copy of the given CEvaluationNodeWhitespace.
Definition at line 582 of file CEvaluationNodeNormalizer.cpp.
References CEvaluationNode::copyBranch(), and pResult.
Referenced by normalize().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       // copy node
       pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeDivideNode (const CEvaluationNodeOperator * pNode) static private
Definition at line 866 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CEvaluationNodeOperator::DIVIDE, CEvaluationNodeNumber::DOUBLE, CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNode::getValue(), normalize(), CEvaluationNode::NUMBER, pResult, CEvaluationNode::type(), and ZERO.
Referenced by normalizeCEvaluationNodeOperator().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pChild1 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
       if (pChild1 != NULL)
         {
           CEvaluationNode* pChild2 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
           if (pChild2 != NULL)
             {
               if (CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER)
                 {
                   // eliminate divisions by 1
                   if (fabs(pChild2->getValue() - 1.0) < ZERO)
                     {
                       pResult = pChild1;
                       delete pChild2;
                       pChild2 = NULL;
                     }
                   else if (CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER)
                     {
                       // if both children are numbers, do the calculation
                       std::ostringstream os;
                       os << pChild1->getValue() / pChild2->getValue();
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, os.str());
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               else
                 {
                   // try to shorten numerator and denominator
                   // TODO find out if a factor is involved
                   if (*pChild1 == *pChild2)
                     {
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "1.0");
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (pResult == NULL)
                 {
                   pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::DIVIDE, "/");
                   pResult->addChild(pChild1);
                   pResult->addChild(pChild2);
                 }
             }
           else
             {
               delete pChild1;
               pChild1 = NULL;
             }
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeMinusNode (const CEvaluationNodeOperator * pNode) static private
Definition at line 1008 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CEvaluationNodeNumber::DOUBLE, CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeOperator::MINUS, normalize(), CEvaluationNode::NUMBER, pResult, CEvaluationNode::type(), and ZERO.
Referenced by normalizeCEvaluationNodeOperator().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pChild1 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
       if (pChild1 != NULL)
         {
           CEvaluationNode* pChild2 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
           if (pChild2 != NULL)
             {
               if (CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER)
                 {
                   // eliminate subtraction of 0
                   if (fabs(pChild2->getValue()) < ZERO)
                     {
                       pResult = pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                   else if (CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER)
                     {
                       // if both children are numbers, do the calculation
                       std::ostringstream os;
                       os << pChild1->getValue() - pChild2->getValue();
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, os.str());
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               else
                 {
                   // TODO find out if a factor is involved
                   if (*pChild1 == *pChild2)
                     {
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "0.0");
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (pResult == NULL)
                 {
                   pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::MINUS, "-");
                   pResult->addChild(pChild1);
                   pResult->addChild(pChild2);
                 }
             }
           else
             {
               delete pChild1;
               pChild1 = NULL;
             }
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeModulusNode (const CEvaluationNodeOperator * pNode) static private
Definition at line 935 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeNumber::INTEGER, CEvaluationNodeOperator::MODULUS, normalize(), CEvaluationNode::NUMBER, pResult, CEvaluationNode::subType(), CEvaluationNode::type(), and ZERO.
Referenced by normalizeCEvaluationNodeOperator().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pChild1 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
       if (pChild1 != NULL)
         {
           CEvaluationNode* pChild2 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
           if (pChild2 != NULL)
             {
               if (CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER)
                 {
                   // eliminate modulus 1
                   if (fabs(pChild2->getValue() - 1.0) < ZERO)
                     {
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, "0");
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                   else if (CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER &&
                            (CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild1->getType()) == CEvaluationNodeNumber::INTEGER &&
                            (CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild2->getType()) == CEvaluationNodeNumber::INTEGER)
                     {
                       // if both children are numbers, do the calculation
                       std::ostringstream os;
                       os << (long)pChild1->getValue() % (long)pChild2->getValue();
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, os.str());
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               else
                 {
                   // try to shorten numerator and denominator
                   // TODO find out if a factor is involved
                   if (*pChild1 == *pChild2)
                     {
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, "0");
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (pResult == NULL)
                 {
                   pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::MODULUS, "%");
                   pResult->addChild(pChild1);
                   pResult->addChild(pChild2);
                 }
             }
           else
             {
               delete pChild1;
               pChild1 = NULL;
             }
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizeMultiplyNode (const CEvaluationNodeOperator * pNode) static private
Definition at line 696 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), buildOperatorBranchFromChain(), collectIdenticalBranches(), CEvaluationNode::copyBranch(), eliminateMultipleNumbers(), findChainNodes(), CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeNumber::INTEGER, CEvaluationNodeOperator::MULTIPLY, normalize(), CEvaluationNode::NUMBER, CEvaluationNode::OPERATOR, pResult, reorderNodes(), CEvaluationNode::subType(), CEvaluationNode::type(), and ZERO.
Referenced by normalizeCEvaluationNodeOperator().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pChild1 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
       if (pChild1 != NULL)
         {
           CEvaluationNode* pChild2 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
           if (pChild2 != NULL)
             {
               // if one of the child nodes is zero, replace the node with a number
               // node of value 0
               // if one of the nodes is a number node of 1, replace the node by the
               // other child
               if (CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER)
                 {
                   if (fabs(pChild1->getValue() - 1.0) < ZERO)
                     {
                       pResult = pChild2;
                       delete pChild1;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                   else if (fabs(pChild1->getValue()) < ZERO)
                     {
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, "0");
                       // we are done
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (pChild2 && CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER)
                 {
                   if (fabs(pChild2->getValue() - 1.0) < ZERO)
                     {
                       pResult = pChild1;
                       delete pChild2;
                       pChild2 = NULL;
                       pChild1 = NULL;
                     }
                   else if (fabs(pChild2->getValue()) < ZERO)
                     {
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, "0");
                       // we are done
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (!pResult)
                 {
                   pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
                   pResult->addChild(pChild1);
                   pResult->addChild(pChild2);
                 }
               if (pResult->getType() == CEvaluationNode::OPERATOR)
                 {
                   // multiply all number nodes in a multiplication chain
                   std::vector<CEvaluationNode*> chainNodes;
                   findChainNodes(dynamic_cast<CEvaluationNodeOperator*>(pResult), chainNodes);
                   CEvaluationNodeNormalizer::eliminateMultipleNumbers((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pResult->getType()), chainNodes);
                   // replace multiplication of identical items by a power node with the
                   // correct power
                   CEvaluationNodeNormalizer::collectIdenticalBranches((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pResult->getType()), chainNodes);
                   // reorder nodes again
                   CEvaluationNodeNormalizer::reorderNodes(chainNodes);
                   // rebuild pResult;
                   CEvaluationNodeOperator::SubType subType = (CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pResult->getType());
                   delete pResult;
                   pResult = CEvaluationNodeNormalizer::buildOperatorBranchFromChain(subType, chainNodes);
                 }
             }
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizePlusNode (const CEvaluationNodeOperator * pNode) static private
Definition at line 787 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), buildOperatorBranchFromChain(), collectIdenticalBranches(), CEvaluationNode::copyBranch(), eliminateMultipleNumbers(), findChainNodes(), CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNode::getValue(), normalize(), CEvaluationNode::NUMBER, CEvaluationNode::OPERATOR, CEvaluationNodeOperator::PLUS, pResult, reorderNodes(), CEvaluationNode::subType(), CEvaluationNode::type(), and ZERO.
Referenced by normalizeCEvaluationNodeOperator().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pChild1 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
       if (pChild1 != NULL)
         {
           CEvaluationNode* pChild2 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
           if (pChild2 != NULL)
             {
               // if one of the nodes is a number node of 0, replace the node by the
               // other child
               if (CEvaluationNode::type(pChild1->getType()) == CEvaluationNode::NUMBER)
                 {
                   if (fabs(pChild1->getValue()) < ZERO)
                     {
                       pResult = pChild2;
                       delete pChild1;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (pChild2 != NULL && CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER)
                 {
                   if (fabs(pChild2->getValue()) < ZERO)
                     {
                       if (pChild2 != pResult)
{
                           pResult = pChild1;
                           delete pChild2;
                         }
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               if (!pResult)
                 {
                   pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::PLUS, "+");
                   pResult->addChild(pChild1);
                   pResult->addChild(pChild2);
                 }
               if (pResult->getType() == CEvaluationNode::OPERATOR)
                 {
                   // add all number nodes in a summation chain
                   std::vector<CEvaluationNode*> chainNodes;
                   findChainNodes(dynamic_cast<CEvaluationNodeOperator*>(pResult), chainNodes);
                   CEvaluationNodeNormalizer::eliminateMultipleNumbers((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pResult->getType()), chainNodes);
                   // replace addition of identical items by a multiplication node with the
                   // correct number
                   CEvaluationNodeNormalizer::collectIdenticalBranches((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pResult->getType()), chainNodes);
                   // reorder nodes again
                   CEvaluationNodeNormalizer::reorderNodes(chainNodes);
                   // rebuild pResult;
                   CEvaluationNodeOperator::SubType subType = (CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pResult->getType());
                   delete pResult;
                   pResult = CEvaluationNodeNormalizer::buildOperatorBranchFromChain(subType, chainNodes);
                 }
             }
           else
             {
               delete pChild1;
               pChild1 = NULL;
             }
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
CEvaluationNode * CEvaluationNodeNormalizer::normalizePowerNode (const CEvaluationNodeOperator * pNode) static private
Definition at line 648 of file CEvaluationNodeNormalizer.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::copyBranch(), CCopasiNode< _Data >::getChild(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeNumber::INTEGER, normalize(), CEvaluationNode::NUMBER, CEvaluationNodeOperator::POWER, pResult, CEvaluationNode::type(), and ZERO.
Referenced by normalizeCEvaluationNodeOperator().
 {
   CEvaluationNode* pResult = NULL;
   if (pNode != NULL)
     {
       CEvaluationNode* pChild1 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()));
       if (pChild1 != NULL)
         {
           CEvaluationNode* pChild2 = CEvaluationNodeNormalizer::normalize(dynamic_cast<const CEvaluationNode*>(pNode->getChild()->getSibling()));
           if (pChild2 != NULL)
             {
               if (CEvaluationNode::type(pChild2->getType()) == CEvaluationNode::NUMBER)
                 {
                   if (pChild2->getValue() - 1.0 < ZERO)
                     {
                       // replace it with the first child
                       pResult = pChild1;
                       delete pChild2;
                       pChild2 = NULL;
                     }
                   else if (pChild2->getValue() < ZERO)
                     {
                       // replace it by a number node of 1
                       pResult = new CEvaluationNodeNumber(CEvaluationNodeNumber::INTEGER, "1");
                       delete pChild1;
                       delete pChild2;
                       pChild1 = NULL;
                       pChild2 = NULL;
                     }
                 }
               else
                 {
                   pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::POWER, "^");
                   pResult->addChild(pChild1);
                   pResult->addChild(pChild2);
                 }
             }
         }
       if (pResult == NULL) pResult = pNode->copyBranch();
     }
   return pResult;
 }
bool CEvaluationNodeNormalizer::reorderNodes (std::vector< CEvaluationNode * > & chainNodes) static private
Definition at line 1286 of file CEvaluationNodeNormalizer.cpp.
Referenced by normalizeMultiplyNode(), and normalizePlusNode().
 {
   std::sort(chainNodes.begin(), chainNodes.end(), lessCEvaluationNodes());
   return true;
 }
Member Data Documentation
const double CEvaluationNodeNormalizer::ZERO = 1e-100 static private
Definition at line 48 of file CEvaluationNodeNormalizer.h.
Referenced by normalizeDivideNode(), normalizeMinusNode(), normalizeModulusNode(), normalizeMultiplyNode(), normalizePlusNode(), and normalizePowerNode().
The documentation for this class was generated from the following files:
CEvaluationNodeNormalizer.h
CEvaluationNodeNormalizer.cpp