COPASI API: CLGlobalRenderInformation Class Reference
CLGlobalRenderInformation Class Reference
#include <CLGlobalRenderInformation.h>
Public Member Functions
void addStyle (const CLGlobalStyle *pStyle)
CLGlobalRenderInformation (CCopasiContainer *pParent=NULL)
CLGlobalRenderInformation (const CLGlobalRenderInformation &source, CCopasiContainer *pParent=NULL)
CLGlobalRenderInformation (const GlobalRenderInformation &source, CCopasiContainer *pParent=NULL)
CLGlobalStyle * createStyle ()
CCopasiVector< CLGlobalStyle > * getListOfStyles ()
const CCopasiVector
< CLGlobalStyle > * getListOfStyles () const
size_t getNumStyles () const
CLStyle * getStyle (size_t i)
const CLStyle * getStyle (size_t i) const
bool toSBML (GlobalRenderInformation *pGRI, unsigned int level, unsigned int version) const
Public Member Functions inherited from CLRenderInformationBase
void addColorDefinition (const CLColorDefinition *cd)
void addGradientDefinition (const CLGradientBase *gradient)
void addLineEnding (const CLLineEnding *le)
void addSBMLAttributes (RenderInformationBase *pBase) const
CLRenderInformationBase (const std::string &name, CCopasiContainer *pParent=NULL)
CLRenderInformationBase (const CLRenderInformationBase &source, CCopasiContainer *pParent)
CLRenderInformationBase (const RenderInformationBase &source, const std::string &name, CCopasiContainer *pParent=NULL)
CLColorDefinition * createColorDefinition ()
CLLinearGradient * createLinearGradientDefinition ()
CLLineEnding * createLineEnding ()
CLRadialGradient * createRadialGradientDefinition ()
const std::string & getBackgroundColor () const
CLColorDefinition * getColorDefinition (size_t index)
const CLColorDefinition * getColorDefinition (size_t index) const
CLGradientBase * getGradientDefinition (size_t index)
const CLGradientBase * getGradientDefinition (size_t index) const
const std::string & getKey () const
CLLineEnding * getLineEnding (size_t index)
const CLLineEnding * getLineEnding (size_t index) const
CCopasiVector
< CLColorDefinition > * getListOfColorDefinitions ()
const CCopasiVector
< CLColorDefinition > * getListOfColorDefinitions () const
CCopasiVector< CLGradientBase > * getListOfGradientDefinitions ()
const CCopasiVector
< CLGradientBase > * getListOfGradientDefinitions () const
CCopasiVector< CLLineEnding > * getListOfLineEndings ()
const CCopasiVector
< CLLineEnding > * getListOfLineEndings () const
const std::string & getName () const
size_t getNumColorDefinitions () const
size_t getNumGradientDefinitions () const
size_t getNumLineEndings () const
const std::string & getReferenceRenderInformationKey () const
void removeColorDefinition (size_t index)
void removeGradientDefinition (size_t index)
void removeLineEnding (size_t index)
void setBackgroundColor (const std::string &bg)
void setName (const std::string &name)
void setReferenceRenderInformationKey (const std::string &key)
~CLRenderInformationBase ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CCopasiVector< CLGlobalStyle > mListOfStyles
Protected Attributes inherited from CLRenderInformationBase
std::string mBackgroundColor
std::string mKey
CCopasiVector< CLColorDefinition > mListOfColorDefinitions
CCopasiVector< CLGradientBase > mListOfGradientDefinitions
CCopasiVector< CLLineEnding > mListOfLineEndings
std::string mName
std::string mReferenceRenderInformation
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 27 of file CLGlobalRenderInformation.h.
Constructor & Destructor Documentation
CLGlobalRenderInformation::CLGlobalRenderInformation (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 22 of file CLGlobalRenderInformation.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and CLRenderInformationBase::mKey.
                                                                              :
   CLRenderInformationBase("GlobalRenderInformation", pParent)
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("GlobalRenderInformation", this);
 }
CLGlobalRenderInformation::CLGlobalRenderInformation (const CLGlobalRenderInformation & source, CCopasiContainer * pParent = NULL)
Copy Constructor.
Copy constructor
Definition at line 31 of file CLGlobalRenderInformation.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and CLRenderInformationBase::mKey.
                                                                                                                       :
   CLRenderInformationBase(source, pParent),
   mListOfStyles(source.mListOfStyles, this)
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("GlobalRenderInformation", this);
 }
CLGlobalRenderInformation::CLGlobalRenderInformation (const GlobalRenderInformation & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 41 of file CLGlobalRenderInformation.cpp.
References CKeyFactory::add(), CCopasiVector< T >::add(), CCopasiRootContainer::getKeyFactory(), CLRenderInformationBase::mKey, and mListOfStyles.
                               :
   //CLRenderInformationBase(source,"GlobalRenderInformation",colorIdToKeyMap,gradientIdToKeyMap,lineEndingIdToKeyMap,pParent)
   CLRenderInformationBase(source, "GlobalRenderInformation", pParent)
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("GlobalRenderInformation", this);
   unsigned int i, iMax = source.getNumStyles();
   for (i = 0; i < iMax; ++i)
     {
       this->mListOfStyles.add(new CLGlobalStyle(*static_cast<const GlobalStyle*>(source.getStyle(i))), true);
     }
 }
Member Function Documentation
void CLGlobalRenderInformation::addStyle (const CLGlobalStyle * pStyle)
Definition at line 109 of file CLGlobalRenderInformation.cpp.
References CCopasiVector< T >::add(), and mListOfStyles.
 {
   this->mListOfStyles.add(new CLGlobalStyle(*pStyle), true);
 }
CLGlobalStyle * CLGlobalRenderInformation::createStyle ()
Definition at line 102 of file CLGlobalRenderInformation.cpp.
References CCopasiVector< T >::add(), and mListOfStyles.
 {
   CLGlobalStyle* pStyle = new CLGlobalStyle();
   this->mListOfStyles.add(pStyle, true);
   return pStyle;
 }
CCopasiVector< CLGlobalStyle > * CLGlobalRenderInformation::getListOfStyles ()
Returns a pointer to the LitOfStyles object.
Definition at line 71 of file CLGlobalRenderInformation.cpp.
References mListOfStyles.
Referenced by CLRenderFlattener::flatten().
 {
   return &(this->mListOfStyles);
 }
const CCopasiVector< CLGlobalStyle > * CLGlobalRenderInformation::getListOfStyles () const
Returns a pointer to the LitOfStyles object.
Returns a pointer to the ListOfStyles object.
Definition at line 79 of file CLGlobalRenderInformation.cpp.
References mListOfStyles.
 {
   return &(this->mListOfStyles);
 }
size_t CLGlobalRenderInformation::getNumStyles () const
Returns the number of styles.
Definition at line 63 of file CLGlobalRenderInformation.cpp.
References mListOfStyles, and CCopasiVector< T >::size().
Referenced by CLRenderResolver::fill_global_maps(), and CCopasiXML::saveGlobalRenderInformation().
 {
   return this->mListOfStyles.size();
 }
CLStyle * CLGlobalRenderInformation::getStyle (size_t i)
Returns a pointer to the style with the given index. If the index is invalid, NULL is returned.
Definition at line 88 of file CLGlobalRenderInformation.cpp.
References mListOfStyles, and CCopasiVector< T >::size().
Referenced by CLRenderResolver::fill_global_maps(), CLRenderFlattener::flatten(), CCopasiXML::saveGlobalRenderInformation(), and toSBML().
 {
   return (i < this->mListOfStyles.size()) ? this->mListOfStyles[i] : NULL;
 }
const CLStyle * CLGlobalRenderInformation::getStyle (size_t i) const
Returns a pointer to the style with the given index. If the index is invalid, NULL is returned.
Definition at line 97 of file CLGlobalRenderInformation.cpp.
References mListOfStyles, and CCopasiVector< T >::size().
 {
   return (i < this->mListOfStyles.size()) ? this->mListOfStyles[i] : NULL;
 }
bool CLGlobalRenderInformation::toSBML (GlobalRenderInformation * pGRI, unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
Definition at line 118 of file CLGlobalRenderInformation.cpp.
References CLRenderInformationBase::addSBMLAttributes(), getStyle(), mListOfStyles, and CCopasiVector< T >::size().
Referenced by CSBMLExporter::exportModelToString().
 {
   bool result = true;
   this->addSBMLAttributes(pGRI);
   size_t i, iMax = this->mListOfStyles.size();
   for (i = 0; i < iMax; ++i)
     {
       GlobalStyle* pStyle = static_cast<const CLGlobalStyle*>(this->getStyle(i))->toSBML(level, version);
       int success = pGRI->addStyle(pStyle);
       assert(success == LIBSBML_OPERATION_SUCCESS);
       result = (result && (success == LIBSBML_OPERATION_SUCCESS));
       delete pStyle;
     }
   return result;
 }
Member Data Documentation
CCopasiVector<CLGlobalStyle> CLGlobalRenderInformation::mListOfStyles protected
Definition at line 30 of file CLGlobalRenderInformation.h.
Referenced by addStyle(), CLGlobalRenderInformation(), createStyle(), getListOfStyles(), getNumStyles(), getStyle(), and toSBML().
The documentation for this class was generated from the following files:
CLGlobalRenderInformation.h
CLGlobalRenderInformation.cpp