COPASI API: CCopasiXMLParser::EllipseElement Class Reference
CCopasiXMLParser::EllipseElement Class Reference
Public Member Functions
EllipseElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~EllipseElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Ellipse = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4156 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::EllipseElement::Element private
Enumerator
Ellipse
Definition at line 4163 of file CCopasiXMLParser.h.
     {
       Ellipse = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::EllipseElement::EllipseElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 11827 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::EllipseElement::~EllipseElement () virtual
Destructor
Definition at line 11832 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::EllipseElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 11938 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Ellipse:
         if (strcmp(pszName, "Ellipse"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Ellipse", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::EllipseElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 11837 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CLGraphicalPrimitive2D::EVENODD, CCopasiMessage::EXCEPTION, CLGraphicalPrimitive2D::INHERIT, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive2D::NONZERO, CLGraphicalPrimitive1D::parseDashArray(), CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, CLEllipse::setCenter3D(), CLGraphicalPrimitive2D::setFillColor(), CLGraphicalPrimitive2D::setFillRule(), CLEllipse::setRadii(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), strToDouble(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * Stroke;
   const char * StrokeWidth;
   const char * StrokeDashArray;
   const char * Fill;
   const char * FillRule;
   const char * CX;
   const char * CY;
   const char * CZ;
   const char * RX;
   const char * RY;
   CLEllipse* pEllipse = NULL;
   switch (mCurrentElement)
     {
       case Ellipse:
         if (strcmp(pszName, "Ellipse"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Ellipse", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         Stroke = mParser.getAttributeValue("stroke", papszAttrs, false);
         StrokeWidth = mParser.getAttributeValue("stroke-width", papszAttrs, false);
         StrokeDashArray = mParser.getAttributeValue("stroke-dasharray", papszAttrs, false);
         Fill = mParser.getAttributeValue("fill", papszAttrs, false);
         FillRule = mParser.getAttributeValue("fill-rule", papszAttrs, false);
         CX = mParser.getAttributeValue("cx", papszAttrs);
         CY = mParser.getAttributeValue("cy", papszAttrs);
         CZ = mParser.getAttributeValue("cz", papszAttrs, "0.0");
         RX = mParser.getAttributeValue("rx", papszAttrs);
         RY = mParser.getAttributeValue("ry", papszAttrs, RX);
         pEllipse = new CLEllipse();
         if (Transform != NULL)
           {
             pEllipse->parseTransformation(Transform);
           }
         if (Stroke != NULL)
           {
             pEllipse->setStroke(Stroke);
           }
         if (StrokeWidth != NULL)
           {
             double width = strToDouble(StrokeWidth, NULL);
             pEllipse->setStrokeWidth(width);
           }
         if (StrokeDashArray != NULL)
           {
             pEllipse->parseDashArray(StrokeDashArray);
           }
         if (Fill != NULL)
           {
             pEllipse->setFillColor(Fill);
           }
         if (FillRule != NULL)
           {
             std::string f(FillRule);
             if (f == "nonzero")
               {
                 pEllipse->setFillRule(CLGraphicalPrimitive2D::NONZERO);
               }
             else if (f == "evenodd")
               {
                 pEllipse->setFillRule(CLGraphicalPrimitive2D::EVENODD);
               }
             else
               {
                 pEllipse->setFillRule(CLGraphicalPrimitive2D::INHERIT);
               }
           }
         pEllipse->setCenter3D(CLRelAbsVector(CX), CLRelAbsVector(CY), CLRelAbsVector(CZ));
         pEllipse->setRadii(CLRelAbsVector(RX), CLRelAbsVector(RY));
         mCommon.pGroup->addChildElement(pEllipse);
         // delete the gradient stop again since the add method made a copy
         delete pEllipse;
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp