COPASI API: CQTSSAResultSubWidget Class Reference
CQTSSAResultSubWidget Class Reference
#include <CQTSSAResultSubWidget.h>
Public Slots
void changeInterval ()
Public Member Functions
CQTSSAResultSubWidget (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
void discardOldResults ()
void displayResult ()
~CQTSSAResultSubWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
Public Attributes
bool mAnnot
C_INT mpIndex
CTSSAMethod * pMethod
CModel * pModel
CTSSAProblem * pProblem
CTSSATask * pTSSATask
Protected Slots
void changeContents ()
virtual void init ()
void saveDataToFile ()
void slotTableChanged ()
void slotTimeAndStepChanged ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Additional Inherited Members
Protected Member Functions inherited from CopasiWidget
virtual bool enterProtected ()
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 26 of file CQTSSAResultSubWidget.h.
Constructor & Destructor Documentation
CQTSSAResultSubWidget::CQTSSAResultSubWidget (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 34 of file CQTSSAResultSubWidget.cpp.
References init().
     : CopasiWidget(parent, name, fl)
 {
   setupUi(this);
   init();
 }
CQTSSAResultSubWidget::~CQTSSAResultSubWidget ()
Definition at line 45 of file CQTSSAResultSubWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQTSSAResultSubWidget::changeContents () protected slot
Definition at line 148 of file CQTSSAResultSubWidget.cpp.
References mpIndex.
Referenced by init().
 {
   if (mpIndex == 0)
     {
       mpTimeScaleWidget->show();
       mpArrayWidget->hide();
       mpBox1->hide();
       mpButton->setText("Show Tables");
       mpIndex = 1;
     }
   else
     {
       mpTimeScaleWidget->hide();
       mpBox1->show();
       mpArrayWidget->show();
       mpButton->setText("Show Time scales");
       mpIndex = 0;
     }
 }
void CQTSSAResultSubWidget::changeInterval () slot
Get the results for the requested step from the method. Fill widgets with this results.
Definition at line 263 of file CQTSSAResultSubWidget.cpp.
References CTSSAMethod::getTable(), CTSSAMethod::getVec_TimeScale(), pMethod, CTSSAMethod::setAnnotationM(), and slotTimeAndStepChanged().
Referenced by displayResult(), and init().
 {
   slotTimeAndStepChanged();
   int s = mpSlider->value();
   if (pMethod->setAnnotationM(s - 1))
     {
       std::string name  =  static_cast<std::string >(mpBox1->currentText().toUtf8());
       pResult = pMethod->getTable(name);
       mpArrayWidget->setArrayAnnotation(pResult);
       CVector< C_FLOAT64> vec = pMethod->getVec_TimeScale(s);
       mpTimeScaleWidget->paintTimeScale(vec);
     }
   else
     {
       //mpSlider->setDisabled(true);
       mpArrayWidget->setArrayAnnotation(NULL);
       mpTimeScaleWidget->clearWidget();
     }
 }
void CQTSSAResultSubWidget::discardOldResults ()
Clear ArrayAnnotation-widgets.
Definition at line 251 of file CQTSSAResultSubWidget.cpp.
Referenced by CQTSSAResultWidget::enterProtected(), and CQTSSAWidget::taskFinishedEvent().
 {
   mpArrayWidget->setArrayAnnotation(NULL);
   mpArrayWidget->clearWidget();
   mpTimeScaleWidget->clearWidget();
 }
void CQTSSAResultSubWidget::displayResult ()
Definition at line 211 of file CQTSSAResultSubWidget.cpp.
References C_INT, changeInterval(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), CCopasiProblem::getModel(), CCopasiTask::getProblem(), CTSSAProblem::getStepNumber(), CTSSAMethod::getTableName(), CModel::getTimeUnitName(), pMethod, pModel, pProblem, and pTSSATask.
Referenced by CQTSSAWidget::taskFinishedEvent().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pTSSATask =
     dynamic_cast<CTSSATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time Scale Separation Analysis"]);
   if (!pTSSATask) return;
   pProblem = dynamic_cast<CTSSAProblem*>(pTSSATask->getProblem());
   pModel = pProblem->getModel();
   pMethod = dynamic_cast<CTSSAMethod*>(pTSSATask->getMethod());
   QString a = FROM_UTF8(pModel->getTimeUnitName());
   mpSlider->setRange(1, pProblem->getStepNumber());
   mpSlider->setValue(mpSlider->minimum());
   mpBox1->clear();
   unsigned C_INT i;
   for (i = 0; i <  pMethod->getTableName().size(); i++)
     {
       mpBox1->insertItem(0, FROM_UTF8(pMethod->getTableName()[i]));
     }
   mpArrayWidget->switchToTable();
   mpSlider->setDisabled(false);
   changeInterval();
 }
void CQTSSAResultSubWidget::init () protected virtual slot
Definition at line 171 of file CQTSSAResultSubWidget.cpp.
References changeContents(), changeInterval(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), CCopasiProblem::getModel(), CCopasiTask::getProblem(), mpIndex, pMethod, pModel, pProblem, pTSSATask, saveDataToFile(), CColorScaleAdvanced::setColorMax(), CColorScaleAdvanced::setColorMin(), and slotTableChanged().
Referenced by CQTSSAResultSubWidget().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pTSSATask =
     dynamic_cast<CTSSATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time Scale Separation Analysis"]);
   if (!pTSSATask) return;
   pProblem = dynamic_cast<CTSSAProblem*>(pTSSATask->getProblem());
   pModel = pProblem->getModel();
   pMethod = dynamic_cast<CTSSAMethod*>(pTSSATask->getMethod());
   mpLabelTime->setNum(0);
   mpLabelStep->setNum(0);
   connect(mpBox1, SIGNAL(currentIndexChanged(int)), this, SLOT(slotTableChanged(/* int */)));
   //set colorsettings for ArrayAnnotationWidgets
   CColorScaleAdvanced * tcs = new CColorScaleAdvanced() ;
   tcs->setColorMin(QColor(240, 240, 240));
   tcs->setColorMax(QColor(0, 255, 0));
   mpArrayWidget->setColorCoding(tcs);
   mpArrayWidget->setColorScalingAutomatic(true);
   connect(mpSlider, SIGNAL(valueChanged(int)), this, SLOT(changeInterval()));
   connect(mpButton, SIGNAL(clicked()), this, SLOT(changeContents()));
   connect(ButtonSaveData, SIGNAL(clicked()), this, SLOT(saveDataToFile()));
   mpBox1->setEditable(false);
   mpIndex = 0;
   mpTimeScaleWidget->hide();
   mpBox1->show();
   mpArrayWidget->show();
 }
void CQTSSAResultSubWidget::saveDataToFile () protected slot
Definition at line 50 of file CQTSSAResultSubWidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getProblem(), CopasiFileDialog::getSaveFileName(), CCopasiProblem::printResult(), and TO_UTF8.
Referenced by init().
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "Text Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail()) return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiTask* mpTask =
     dynamic_cast<CTSSATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time Scale Separation Analysis"]);
   if (!mpTask) return;
   CCopasiProblem* mpProblem = mpTask->getProblem();
   mpProblem->printResult(&file);
   return;
 }
void CQTSSAResultSubWidget::slotTableChanged () protected slot
Definition at line 88 of file CQTSSAResultSubWidget.cpp.
References CTSSAMethod::getTable(), pMethod, and CColorScaleSimple::setSymmetric().
Referenced by init().
 {
   std::string name  =  static_cast<std::string >(mpBox1->currentText().toUtf8());
   if (name == "Reactions slow space" ||
       name == "Reactions contribution to the mode" ||
       name == "Reactions distribution between modes " ||
       name == "Reactions fast space" ||
       name == "Participation Index" ||
       name == "Fast Participation Index" ||
       name == "Slow Participation Index" ||
       name == "Normed Participation Index (by column)" ||
       name == "Normed Participation Index (by row)" ||
       name == "Importance Index" ||
       name == "Normed Importance Index (by row)")
     {
       CColorScaleSimple* tcs = new CColorScaleSimple();
       tcs->setSymmetric(true);
       mpArrayWidget->setColorCoding(tcs);
       mpArrayWidget->setColorScalingAutomatic(true);
     }
   else
     {
       //CColorScaleAdvanced * tcs = new CColorScaleAdvanced() ;
       //tcs->setColorMin(QColor(240, 240, 240));
       //tcs->setColorMax(QColor(0, 255, 0));
       CColorScaleSimple* tcs = new CColorScaleSimple();
       tcs->setSymmetric(true);
       mpArrayWidget->setColorCoding(tcs);
       mpArrayWidget->setColorScalingAutomatic(true);
     }
   pResult = pMethod->getTable(name);
   mpArrayWidget->setArrayAnnotation(pResult);
 }
void CQTSSAResultSubWidget::slotTimeAndStepChanged () protected slot
Definition at line 134 of file CQTSSAResultSubWidget.cpp.
References pMethod, and CTSSAMethod::returnCurrentTime().
Referenced by changeInterval().
 {
   int s = mpSlider->value();
   if (s > 1)
     mpLabelTime->setNum((double)pMethod->returnCurrentTime(s - 1));
   else
     mpLabelTime->setNum(0);
   mpLabelStep->setNum(s);
 }
Member Data Documentation
bool CQTSSAResultSubWidget::mAnnot
Definition at line 40 of file CQTSSAResultSubWidget.h.
C_INT CQTSSAResultSubWidget::mpIndex
Definition at line 39 of file CQTSSAResultSubWidget.h.
Referenced by changeContents(), and init().
CTSSAMethod* CQTSSAResultSubWidget::pMethod
Definition at line 36 of file CQTSSAResultSubWidget.h.
Referenced by changeInterval(), displayResult(), init(), slotTableChanged(), and slotTimeAndStepChanged().
CModel* CQTSSAResultSubWidget::pModel
Definition at line 38 of file CQTSSAResultSubWidget.h.
Referenced by displayResult(), and init().
CTSSAProblem* CQTSSAResultSubWidget::pProblem
Definition at line 35 of file CQTSSAResultSubWidget.h.
Referenced by displayResult(), and init().
CTSSATask* CQTSSAResultSubWidget::pTSSATask
Definition at line 34 of file CQTSSAResultSubWidget.h.
Referenced by displayResult(), and init().
The documentation for this class was generated from the following files:
CQTSSAResultSubWidget.h
CQTSSAResultSubWidget.cpp