COPASI API: CSBMLunit::SymbolicExponent Class Reference
CSBMLunit::SymbolicExponent Class Reference
this class uniquely (in a given context) identifies a symbol
Public Member Functions
bool isEqual (const SymbolicExponent &se) const
SymbolicExponent ()
SymbolicExponent (std::string id, size_t frame)
Public Attributes
size_t mFrame
std::string mID
Detailed Description
this class uniquely (in a given context) identifies a symbol
Definition at line 79 of file CSBMLunit.h.
Constructor & Destructor Documentation
CSBMLunit::SymbolicExponent::SymbolicExponent () inline
Definition at line 84 of file CSBMLunit.h.
 : mID(), mFrame(0) {};
CSBMLunit::SymbolicExponent::SymbolicExponent (std::string id, size_t frame) inline
Definition at line 85 of file CSBMLunit.h.
 : mID(id), mFrame(frame) {};
Member Function Documentation
bool CSBMLunit::SymbolicExponent::isEqual (const SymbolicExponent & se) const inline
Definition at line 86 of file CSBMLunit.h.
References mFrame, and mID.
Referenced by CSBMLunit::applyExponent(), CSBMLunit::applyInverseExponent(), CSBMLunit::isEqual(), and CSBMLunit::multiply().
 {return mID == se.mID && mFrame == se.mFrame;};
Member Data Documentation
size_t CSBMLunit::SymbolicExponent::mFrame
Definition at line 83 of file CSBMLunit.h.
Referenced by isEqual().
std::string CSBMLunit::SymbolicExponent::mID
Definition at line 82 of file CSBMLunit.h.
Referenced by CSBMLunit::getDisplayString(), and isEqual().
The documentation for this class was generated from the following file:
CSBMLunit.h