COPASI API: CMathEvent Class Reference
CMathEvent Class Reference
#include <CMathEvent.h>
Classes
class CAssignment
Public Member Functions
void applyDelayRefreshes ()
CMathEvent (const CCopasiContainer *pParent=NULL)
CMathEvent (const CMathEvent &src, const CCopasiContainer *pParent=NULL)
bool compile (const CEvent *pEvent, std::vector< CCopasiContainer * > listOfContainer)
const bool & delayAssignment () const
bool executeAssignment ()
void fire (const C_FLOAT64 &time, const bool &equality, CProcessQueue &processQueue)
C_FLOAT64 getAssignmentTime (const C_FLOAT64 &currentTime)
C_FLOAT64 getCalculationTime (const C_FLOAT64 &currentTime)
CMathTrigger & getMathTrigger ()
const size_t & getOrder () const
CVector< C_FLOAT64 > getTargetValues ()
const CEvent::Type & getType () const
bool setTargetValues (const CVector< C_FLOAT64 > &targetValues)
~CMathEvent ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void applyDependentRefreshes ()
void applyValueRefreshes ()
C_FLOAT64 calculateDelayedTime (const C_FLOAT64 &currentTime)
Private Attributes
CCopasiVector< CAssignment > mAssignments
std::vector< Refresh * > mAssignmentValueRefreshes
CExpression mDelay
bool mDelayAssignment
std::vector< Refresh * > mDelayValueRefreshes
std::vector< Refresh * > mDependentValueRefreshes
bool mHaveDelay
size_t mOrder
CMathTrigger mTrigger
CEvent::Type mType
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 279 of file CMathEvent.h.
Constructor & Destructor Documentation
CMathEvent::CMathEvent (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 1048 of file CMathEvent.cpp.
                                                        :
   CCopasiContainer("MathEvent", pParent, "MathEvent"),
   mTrigger(this),
   mOrder(false),
   mHaveDelay(false),
   mDelay("DelayExpression", this),
   mDelayAssignment(true),
   mAssignments("ListOfMathEventAssignment", this),
   mDelayValueRefreshes(),
   mAssignmentValueRefreshes(),
   mDependentValueRefreshes(),
   mType(CEvent::Assignment)
 {}
CMathEvent::CMathEvent (const CMathEvent & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CMathEvent & src
"const CCopasiContainer * pParent (default: NULL)
Definition at line 1062 of file CMathEvent.cpp.
                                                          :
   CCopasiContainer(src, pParent),
   mTrigger(src.mTrigger, this),
   mOrder(src.mOrder),
   mHaveDelay(src.mHaveDelay),
   mDelay(src.mDelay, this),
   mDelayAssignment(src.mDelayAssignment),
   mAssignments(src.mAssignments, this),
   mDelayValueRefreshes(src.mDelayValueRefreshes),
   mAssignmentValueRefreshes(src.mAssignmentValueRefreshes),
   mDependentValueRefreshes(src.mDependentValueRefreshes),
   mType(src.mType)
 {}
CMathEvent::~CMathEvent ()
Destructor
Definition at line 1077 of file CMathEvent.cpp.
 {}
Member Function Documentation
void CMathEvent::applyDelayRefreshes ()
Apply all needed refreshes so that the delay expression are correctly calculated.
Definition at line 1198 of file CMathEvent.cpp.
References mDelayValueRefreshes.
Referenced by calculateDelayedTime().
 {
   std::vector< Refresh * >::const_iterator itRefresh = mDelayValueRefreshes.begin();
   std::vector< Refresh * >::const_iterator endRefresh = mDelayValueRefreshes.end();
   while (itRefresh != endRefresh)
     (**itRefresh++)();
   return;
 }
void CMathEvent::applyDependentRefreshes () private
Apply all needed refreshes to update all values depending on the assignment targets.
Definition at line 1220 of file CMathEvent.cpp.
References mDependentValueRefreshes.
Referenced by setTargetValues().
 {
   std::vector< Refresh * >::const_iterator itRefresh = mDependentValueRefreshes.begin();
   std::vector< Refresh * >::const_iterator endRefresh = mDependentValueRefreshes.end();
   while (itRefresh != endRefresh)
     (**itRefresh++)();
   return;
 }
void CMathEvent::applyValueRefreshes () private
Apply all needed refreshes so that the assignment expressions are correctly calculated.
Definition at line 1209 of file CMathEvent.cpp.
References mAssignmentValueRefreshes.
Referenced by getTargetValues().
 {
   std::vector< Refresh * >::const_iterator itRefresh = mAssignmentValueRefreshes.begin();
   std::vector< Refresh * >::const_iterator endRefresh = mAssignmentValueRefreshes.end();
   while (itRefresh != endRefresh)
     (**itRefresh++)();
   return;
 }
C_FLOAT64 CMathEvent::calculateDelayedTime (const C_FLOAT64 & currentTime) private
Calculate the time for delays. This accounts for small errors relative to the current time.
Parameters
const C_FLOAT64 & currentTime
Returns
C_FLOAT64 delayedTime
Definition at line 1266 of file CMathEvent.cpp.
References applyDelayRefreshes(), C_FLOAT64, CExpression::calcValue(), CCopasiMessage::EXCEPTION, CEvaluationTree::getInfix(), MCMathModel, mDelay, and min.
Referenced by getAssignmentTime(), and getCalculationTime().
 {
   if (mDelay.getInfix() == "")
     {
       return currentTime;
     }
   // We make sure everything is up to date.
   applyDelayRefreshes();
   C_FLOAT64 DelayedTime = currentTime + mDelay.calcValue();
   // Events are only allowed in forward integration. Thus the ExecutionTime
   // must not be less than the time.
   if (DelayedTime - currentTime < 0.0)
     {
       // We allow small numerical errors.
       C_FLOAT64 Scale =
         (fabs(DelayedTime) + fabs(currentTime)) * 50.0 * std::numeric_limits< C_FLOAT64 >::epsilon();
       // Both are approximately zero
       if (Scale < 100.0 * std::numeric_limits< C_FLOAT64 >::min())
         {
           DelayedTime = currentTime;
         }
       // The difference is small compared to the scale
       else if (fabs(DelayedTime - currentTime) < Scale)
         {
           DelayedTime = currentTime;
         }
       // The execution time is definitely in the past
       else
         {
           // Create an error message and throw an exception.
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCMathModel + 2, DelayedTime, currentTime);
         }
     }
   return DelayedTime;
 }
bool CMathEvent::compile (const CEvent * pEvent, std::vector< CCopasiContainer * > listOfContainer)
Compile the root finder
Parameters
const CEvent * pEvent
std::vector< CCopasiContainer * > listOfContainer
Definition at line 1080 of file CMathEvent.cpp.
References CCopasiVector< T >::begin(), CMathModel::buildDependendRefreshList(), CMathModel::buildRequiredRefreshList(), CExpression::compile(), CMathTrigger::compile(), CMathEvent::CAssignment::compile(), CCopasiVector< T >::end(), CEvent::getAssignments(), CEvent::getDelayAssignment(), CEvent::getDelayExpression(), CCopasiObject::getDirectDependencies(), CEvaluationTree::getInfix(), CCopasiObject::getObjectAncestor(), CEvent::getTriggerExpressionPtr(), CEvent::getType(), mAssignments, mAssignmentValueRefreshes, mDelay, mDelayAssignment, mDelayValueRefreshes, mDependentValueRefreshes, mHaveDelay, mTrigger, mType, and CExpression::setInfix().
Referenced by CMathModel::compile().
 {
   // A CMathEvent must be part of CMathModel to be compiled.
   CMathModel * pMathModel = dynamic_cast< CMathModel *>(getObjectAncestor("CMathModel"));
   if (pMathModel == NULL)
     return false;
   bool success = true;
   success &= mTrigger.compile(pEvent->getTriggerExpressionPtr(), listOfContainer);
   success &= mDelay.setInfix(pEvent->getDelayExpression());
   success &= mDelay.compile(listOfContainer);
   mHaveDelay = (mDelay.getInfix() != "");
   mType = pEvent->getType();
   // Build the list of refresh calls needed to assure that the delay expression
   // can be calculated.
   mDelayValueRefreshes = pMathModel->buildRequiredRefreshList(mDelay.getDirectDependencies());
   mDelayAssignment = pEvent->getDelayAssignment();
   mAssignments.clear();
   CCopasiVectorN< CEventAssignment >::const_iterator it = pEvent->getAssignments().begin();
   CCopasiVectorN< CEventAssignment >::const_iterator end = pEvent->getAssignments().end();
   std::set< const CCopasiObject * > Assignments;
   std::set< const CCopasiObject * > Targets;
   for (; it != end; ++it)
     {
       CAssignment * pAssignment = new CAssignment();
       mAssignments.add(pAssignment, true);
       success &= pAssignment->compile(*it, listOfContainer);
       Assignments.insert(pAssignment);
       Targets.insert((*it)->getTargetObject());
     }
   // Build the list of refresh calls needed to assure that the assignment expressions
   // can be calculated.
   mAssignmentValueRefreshes = pMathModel->buildRequiredRefreshList(Assignments);
   // Build the list of refresh calls needed to assure that all dependent model values
   // are updated after the assignments are executed.
   mDependentValueRefreshes = pMathModel->buildDependendRefreshList(Targets);
   return success;
 }
const bool & CMathEvent::delayAssignment () const
Check whether to delay the assignment
Returns
const bool & delayAssignment
Definition at line 1241 of file CMathEvent.cpp.
References mDelayAssignment.
 {
   return mDelayAssignment;
 }
bool CMathEvent::executeAssignment ()
Calculate and assign the new target values
Returns
bool stateChanged
Definition at line 1193 of file CMathEvent.cpp.
References getTargetValues(), and setTargetValues().
 {
   return setTargetValues(getTargetValues());
 }
void CMathEvent::fire (const C_FLOAT64 & time, const bool & equality, CProcessQueue & processQueue)
The event fires and the appropriate actions are scheduled in the process queue.
Parameters
const C_FLOAT64 & time
const bool & equality
CProcessQueue & processQueue
Definition at line 1137 of file CMathEvent.cpp.
References CProcessQueue::addAssignment(), CProcessQueue::addCalculation(), getAssignmentTime(), getCalculationTime(), getTargetValues(), and mDelayAssignment.
Referenced by CMathModel::processRoots().
 {
   if (mDelayAssignment)
     {
       processQueue.addAssignment(getAssignmentTime(time), equality, getTargetValues(), this);
     }
   else
     {
       processQueue.addCalculation(getCalculationTime(time), equality, this);
     }
 }
C_FLOAT64 CMathEvent::getAssignmentTime (const C_FLOAT64 & currentTime)
Retrieve the time for executing the assignmentS
Parameters
const C_FLOAT64 & currentTime
Returns
C_FLOAT64 executionTime
Definition at line 1256 of file CMathEvent.cpp.
References calculateDelayedTime(), and mDelayAssignment.
Referenced by fire().
 {
   if (!mDelayAssignment)
     {
       return currentTime;
     }
   return calculateDelayedTime(currentTime);
 }
C_FLOAT64 CMathEvent::getCalculationTime (const C_FLOAT64 & currentTime)
Retrieve the time for calculating the assignment expression
Parameters
const C_FLOAT64 & currentTime
Returns
C_FLOAT64 calculationTime
Definition at line 1246 of file CMathEvent.cpp.
References calculateDelayedTime(), and mDelayAssignment.
Referenced by fire().
 {
   if (mDelayAssignment)
     {
       return currentTime;
     }
   return calculateDelayedTime(currentTime);
 }
CMathTrigger & CMathEvent::getMathTrigger ()
Retrieve the trigger for this event.
Returns
CMathTrigger & mathTrigger
Definition at line 1231 of file CMathEvent.cpp.
References mTrigger.
Referenced by CMathModel::compile(), and CMathModel::processRoots().
 {
   return mTrigger;
 }
const size_t & CMathEvent::getOrder () const
Retrieve the order in which this event shall be processed
Returns
const size_t & order
Definition at line 1236 of file CMathEvent.cpp.
References mOrder.
 {
   return mOrder;
 }
CVector< C_FLOAT64 > CMathEvent::getTargetValues ()
Calculate and retrieve the new target values
Returns
CVector< C_FLOAT64 > targetValues
Definition at line 1151 of file CMathEvent.cpp.
References applyValueRefreshes(), C_FLOAT64, and mAssignments.
Referenced by executeAssignment(), and fire().
 {
   applyValueRefreshes();
   CVector< C_FLOAT64 > Values(mAssignments.size());
   C_FLOAT64 * pValue = Values.array();
   CCopasiVector< CAssignment >::iterator itAssignment = mAssignments.begin();
   CCopasiVector< CAssignment >::iterator endAssignment = mAssignments.end();
   for (; itAssignment != endAssignment; ++itAssignment, ++pValue)
     {
       *pValue = (*itAssignment)->mExpression.calcValue();
     }
   return Values;
 }
const CEvent::Type & CMathEvent::getType () const
Retrieve the type of the event
Returns
const CEvent::Type & type
Definition at line 1307 of file CMathEvent.cpp.
References mType.
Referenced by CProcessQueue::CAction::CAction().
 {
   return mType;
 }
bool CMathEvent::setTargetValues (const CVector< C_FLOAT64 > & targetValues)
Set the target values
Parameters
const CVector< C_FLOAT64 > & targetValues
Returns
bool stateChanged
Definition at line 1168 of file CMathEvent.cpp.
References applyDependentRefreshes(), CVectorCore< CType >::array(), C_FLOAT64, and mAssignments.
Referenced by executeAssignment().
 {
   bool StateChanged = false;
   const C_FLOAT64 * pValue = values.array();
   CCopasiVector< CAssignment >::iterator itAssignment = mAssignments.begin();
   CCopasiVector< CAssignment >::iterator endAssignment = mAssignments.end();
   for (; itAssignment != endAssignment; ++itAssignment, ++pValue)
     {
       if (*(*itAssignment)->mpTarget != *pValue)
         {
           StateChanged = true;
           *(*itAssignment)->mpTarget = *pValue;
         }
     }
   if (StateChanged)
     {
       applyDependentRefreshes();
     }
   return StateChanged;
 }
Member Data Documentation
CCopasiVector< CAssignment > CMathEvent::mAssignments private
List of assignments
Definition at line 483 of file CMathEvent.h.
Referenced by compile(), getTargetValues(), and setTargetValues().
std::vector< Refresh * > CMathEvent::mAssignmentValueRefreshes private
A sequence of refresh calls needed to prepare to calculate the current values of the assignments.
Definition at line 495 of file CMathEvent.h.
Referenced by applyValueRefreshes(), and compile().
CExpression CMathEvent::mDelay private
Delay expression.
Definition at line 473 of file CMathEvent.h.
Referenced by calculateDelayedTime(), and compile().
bool CMathEvent::mDelayAssignment private
Boolean value indicating whether the calculation or the assignment is delayed.
Definition at line 478 of file CMathEvent.h.
Referenced by compile(), delayAssignment(), fire(), getAssignmentTime(), and getCalculationTime().
std::vector< Refresh * > CMathEvent::mDelayValueRefreshes private
A sequence of refresh calls needed to prepare to calculate the delay value.
Definition at line 489 of file CMathEvent.h.
Referenced by applyDelayRefreshes(), and compile().
std::vector< Refresh * > CMathEvent::mDependentValueRefreshes private
A sequence of refresh calls needed to calculate all values which depend on the target values of the assignments.
Definition at line 501 of file CMathEvent.h.
Referenced by applyDependentRefreshes(), and compile().
bool CMathEvent::mHaveDelay private
Boolean value indicating whether the event involves a delay.
Definition at line 468 of file CMathEvent.h.
Referenced by compile().
size_t CMathEvent::mOrder private
The order in which the event is processed in case of simultaneous assignments
Definition at line 463 of file CMathEvent.h.
Referenced by getOrder().
CMathTrigger CMathEvent::mTrigger private
Trigger expression.
Definition at line 457 of file CMathEvent.h.
Referenced by compile(), and getMathTrigger().
CEvent::Type CMathEvent::mType private
The type of the event
Definition at line 506 of file CMathEvent.h.
Referenced by compile(), and getType().
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp