COPASI API: CEvent Class Reference
CEvent Class Reference
#include <CEvent.h>
Public Types
enum Type { Assignment, Discontinuity, CutPlane }
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Public Member Functions
CEvent (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CEvent (const CEvent &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
bool compile (std::vector< CCopasiContainer * > listOfContainer)
void deleteAssignment (const std::string &key)
const CCopasiVectorN
< CEventAssignment > & getAssignments () const
CCopasiVectorN
< CEventAssignment > & getAssignments ()
const bool & getDelayAssignment () const
std::string getDelayExpression () const
CExpression * getDelayExpressionPtr ()
const CExpression * getDelayExpressionPtr () const
const bool & getFireAtInitialTime () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const bool & getPersistentTrigger () const
std::string getPriorityExpression () const
CExpression * getPriorityExpressionPtr ()
const CExpression * getPriorityExpressionPtr () const
const std::string & getSBMLId () const
std::string getTriggerExpression () const
const CExpression * getTriggerExpressionPtr () const
CExpression * getTriggerExpressionPtr ()
const Type & getType () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void setDelayAssignment (const bool &delayCalculation)
bool setDelayExpression (const std::string &expression)
bool setDelayExpressionPtr (CExpression *pExpression)
void setFireAtInitialTime (const bool &fireAtInitialTime)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setPersistentTrigger (const bool &persistentTrigger)
bool setPriorityExpression (const std::string &expression)
bool setPriorityExpressionPtr (CExpression *pExpression)
void setSBMLId (const std::string &id)
bool setTriggerExpression (const std::string &expression)
bool setTriggerExpressionPtr (CExpression *pExpression)
void setType (const Type &type)
~CEvent ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Private Member Functions
void initObjects ()
CEvent & operator= (const CEvent &)
Private Attributes
CCopasiVectorN< CEventAssignment > mAssignments
bool mDelayAssignment
bool mFireAtInitialTime
CExpression * mpDelayExpression
bool mPersistentTrigger
CModel * mpModel
CExpression * mpPriorityExpression
CExpression * mpTriggerExpression
std::string mSBMLId
Type mType
Friends
std::ostream & operator<< (std::ostream &os, const CEvent &d)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 152 of file CEvent.h.
Member Enumeration Documentation
enum CEvent::Type
Enumerator
Assignment
Discontinuity
CutPlane
Definition at line 155 of file CEvent.h.
   {
     Assignment,
     Discontinuity,
     CutPlane
   };
Constructor & Destructor Documentation
CEvent::CEvent (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 238 of file CEvent.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectType(), initObjects(), and CAnnotation::mKey.
                                                 :
   CCopasiContainer(name, pParent, "Event"),
   CAnnotation(),
   mpModel(static_cast<CModel *>(getObjectAncestor("Model"))),
   mAssignments("ListOfAssignments", this),
   mDelayAssignment(true),
   mFireAtInitialTime(false),
   mPersistentTrigger(false),
   mpTriggerExpression(NULL),
   mpDelayExpression(NULL),
   mpPriorityExpression(NULL),
   mType(Assignment)
 {
   mKey = (CCopasiRootContainer::getKeyFactory()->add(getObjectType(), this));
   initObjects();
 }
CEvent::CEvent (const CEvent & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CEvent & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 257 of file CEvent.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CCopasiObject::getObjectType(), initObjects(), CAnnotation::mKey, and CAnnotation::setMiriamAnnotation().
                                                 :
   CCopasiContainer(src, pParent),
   CAnnotation(src),
   mpModel(static_cast<CModel *>(getObjectAncestor("Model"))),
   mAssignments(src.mAssignments, this),
   mDelayAssignment(src.mDelayAssignment),
   mFireAtInitialTime(src.mFireAtInitialTime),
   mPersistentTrigger(src.mPersistentTrigger),
   mpTriggerExpression(src.mpTriggerExpression != NULL ? new CExpression(*src.mpTriggerExpression, this) : NULL),
   mpDelayExpression(src.mpDelayExpression != NULL ? new CExpression(*src.mpDelayExpression, this) : NULL),
   mpPriorityExpression(src.mpPriorityExpression != NULL ? new CExpression(*src.mpPriorityExpression, this) : NULL),
   mType(src.mType)
 {
   mKey = (CCopasiRootContainer::getKeyFactory()->add(getObjectType(), this));
   initObjects();
   setMiriamAnnotation(src.getMiriamAnnotation(), mKey, src.mKey);
 }
CEvent::~CEvent ()
Destructor
Definition at line 278 of file CEvent.cpp.
References CCopasiRootContainer::getKeyFactory(), CAnnotation::mKey, mpDelayExpression, mpPriorityExpression, mpTriggerExpression, pdelete, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
   pdelete(mpTriggerExpression);
   pdelete(mpDelayExpression);
   pdelete(mpPriorityExpression);
 }
Member Function Documentation
void CEvent::cleanup ()
Delete
bool CEvent::compile (std::vector< CCopasiContainer * > listOfContainer)
Compile the event.
Parameters
std::vector< CCopasiContainer * > listOfContainer
Returns
bool success
Definition at line 346 of file CEvent.cpp.
References CCopasiObject::addDirectDependency(), CCopasiVector< T >::begin(), CCopasiObject::clearDirectDependencies(), CExpression::compile(), CCopasiVector< T >::end(), mAssignments, mpDelayExpression, and mpTriggerExpression.
 {
   bool success = true;
   // Clear the old direct dependencies.
   clearDirectDependencies();
   // Compile the trigger expression
   if (mpTriggerExpression != NULL)
     {
       success &= mpTriggerExpression->compile(listOfContainer);
       addDirectDependency(mpTriggerExpression);
     }
   // Compile the delay expression
   if (mpDelayExpression != NULL)
     {
       success &= mpDelayExpression->compile(listOfContainer);
       addDirectDependency(mpDelayExpression);
     }
   // Compile the assignments
   CCopasiVectorN< CEventAssignment >::iterator itAssignment = mAssignments.begin();
   CCopasiVectorN< CEventAssignment >::iterator endAssignment = mAssignments.end();
   for (; itAssignment != endAssignment; ++itAssignment)
     {
       success &= (*itAssignment)->compile(listOfContainer);
       addDirectDependency(*itAssignment);
     }
   return success;
 }
void CEvent::deleteAssignment (const std::string & key)
Delete assignment with the given key. Please note this is not the target key.
Parameters
const std::string & key
Definition at line 688 of file CEvent.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), and mAssignments.
 {
   CEventAssignment * pAssignment =
     dynamic_cast<CEventAssignment *>(CCopasiRootContainer::getKeyFactory()->get(key));
   if (pAssignment != NULL)
     {
       mAssignments.CCopasiVector< CEventAssignment >::remove(pAssignment);
     }
 }
const CCopasiVectorN< CEventAssignment > & CEvent::getAssignments () const
Retrieve the assignments
Returns
const CCopasiVectorN< CEventAssignment > & assignments
Definition at line 678 of file CEvent.cpp.
References mAssignments.
Referenced by CModelAdd::addEvents(), CMathEventN::allocate(), CMathEventN::compile(), CMathEvent::compile(), CModel::convert2NonReversible(), CQEventDM::data(), CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), CSBMLExporter::isEventSBMLCompatible(), CQEventWidget1::loadFromEvent(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInEvent(), CCopasiXML::saveModel(), CQEventWidget1::saveToEvent(), and CCopasiXMLParser::AssignmentElement::start().
 {
   return mAssignments;
 }
CCopasiVectorN< CEventAssignment > & CEvent::getAssignments ()
Retrieve the assignments
Returns
CCopasiVectorN< CEventAssignment > & assignments
Definition at line 683 of file CEvent.cpp.
References mAssignments.
 {
   return mAssignments;
 }
const bool & CEvent::getDelayAssignment () const
Retrieve whether to delay the calculation of the assignment.
Returns
const bool & delayCalculation
Definition at line 419 of file CEvent.cpp.
References mDelayAssignment.
Referenced by CModelAdd::addEvents(), CMathEventN::compile(), CMathEvent::compile(), CSBMLExporter::createEvent(), CQEventDM::data(), CModelExpansion::duplicateEvent(), CQEventWidget1::loadFromEvent(), CCopasiXML::saveModel(), and CQEventWidget1::saveToEvent().
 {
   return mDelayAssignment;
 }
std::string CEvent::getDelayExpression () const
Retrieve the expression of the delay as a string.
Returns
std::string expression
Definition at line 591 of file CEvent.cpp.
References CEvaluationTree::getInfix(), mpDelayExpression, and CExpression::updateInfix().
Referenced by CMathEventN::compile(), CMathEvent::compile(), CModel::convert2NonReversible(), CQEventDM::data(), CModelExpansion::duplicateEvent(), CQEventWidget1::loadFromEvent(), CCopasiXML::saveModel(), and CQEventWidget1::saveToEvent().
 {
   if (mpDelayExpression == NULL)
     return "";
   mpDelayExpression->updateInfix();
   return mpDelayExpression->getInfix();
 }
CExpression * CEvent::getDelayExpressionPtr ()
Retrieve the pointer to the expression of the delay.
Returns
CExpression* pExpression
Definition at line 606 of file CEvent.cpp.
References mpDelayExpression.
Referenced by CModelAdd::addEvents(), CModelAdd::copyDelayExpression(), CQEventDM::data(), CModelExpansion::duplicateEvent(), CSBMLExporter::isEventSBMLCompatible(), SBMLImporter::removeUnusedFunctions(), and CModelExpansion::replaceInEvent().
 {
   return mpDelayExpression;
 }
const CExpression * CEvent::getDelayExpressionPtr () const
Retrieve the pointer to the expression of the delay.
Returns
CExpression* pExpression
Definition at line 601 of file CEvent.cpp.
References mpDelayExpression.
 {
   return mpDelayExpression;
 }
const bool & CEvent::getFireAtInitialTime () const
Retrieve whether the trigger may fire at the initial time.
Returns
const bool & fireAtInitialTime
Definition at line 429 of file CEvent.cpp.
References mFireAtInitialTime.
Referenced by CMathEventN::compile(), and CCopasiXML::saveModel().
 {
   return mFireAtInitialTime;
 }
const std::string & CEvent::getKey () const virtual
Retrieves the key of the event
Returns
std::string key
Reimplemented from CAnnotation.
Definition at line 287 of file CEvent.cpp.
References CAnnotation::getKey().
Referenced by CModelExpansion::duplicateEvent(), CCopasiXMLParser::EventElement::end(), CQEventDM::insertRows(), CCopasiXML::saveModel(), CQEventDM::setData(), and CSBMLExporter::updateMIRIAMAnnotation().
 {
   return CAnnotation::getKey();
 }
std::string CEvent::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
Retrieve display name. Special treatment for reaction to provide a shorter display
Reimplemented from CCopasiObject.
Definition at line 464 of file CEvent.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDisplayName(), and CCopasiObject::getObjectName().
 {
   CModel* tmp = dynamic_cast<CModel*>(this->getObjectAncestor("Model"));
   if (tmp)
     return "((" + getObjectName() + "))";
   return CCopasiObject::getObjectDisplayName(regular, richtext);
 }
const bool & CEvent::getPersistentTrigger () const
Retrieve whether the trigger must remain true between firing and executions.
Returns
const bool & persistentTrigger
Definition at line 439 of file CEvent.cpp.
References mPersistentTrigger.
Referenced by CMathEventN::compile(), and CCopasiXML::saveModel().
 {
   return mPersistentTrigger;
 }
std::string CEvent::getPriorityExpression () const
Retrieve the expression of the priority as a string.
Returns
std::string expression
Definition at line 658 of file CEvent.cpp.
References CEvaluationTree::getInfix(), mpPriorityExpression, and CExpression::updateInfix().
Referenced by CMathEventN::compile(), and CModel::convert2NonReversible().
 {
   if (mpPriorityExpression == NULL)
     return "";
   mpPriorityExpression->updateInfix();
   return mpPriorityExpression->getInfix();
 }
CExpression * CEvent::getPriorityExpressionPtr ()
Retrieve the pointer to the expression of the priority.
Returns
CExpression* pExpression
Definition at line 668 of file CEvent.cpp.
References mpPriorityExpression.
 {
   return mpPriorityExpression;
 }
const CExpression * CEvent::getPriorityExpressionPtr () const
Retrieve the pointer to the expression of the priority.
Returns
CExpression* pExpression
Definition at line 673 of file CEvent.cpp.
References mpPriorityExpression.
 {
   return mpPriorityExpression;
 }
const std::string & CEvent::getSBMLId () const
Returns a reference to the SBML Id.
Definition at line 403 of file CEvent.cpp.
References mSBMLId.
Referenced by CSBMLExporter::collectIds(), CSBMLExporter::createEvent(), CSBMLExporter::exportEventAssignments(), and CCopasiXML::saveModel().
 {
   return this->mSBMLId;
 }
std::string CEvent::getTriggerExpression () const
Retrieve the expression of trigger as a string.
Returns
std::string expression
Definition at line 524 of file CEvent.cpp.
References CEvaluationTree::getInfix(), mpTriggerExpression, and CExpression::updateInfix().
Referenced by CMathEventN::CTrigger::allocate(), CMathEventN::CTrigger::compile(), CModel::convert2NonReversible(), CQEventDM::data(), CModelExpansion::duplicateEvent(), CQEventWidget1::loadFromEvent(), CCopasiXML::saveModel(), and CQEventWidget1::saveToEvent().
 {
   if (mpTriggerExpression == NULL)
     return "";
   mpTriggerExpression->updateInfix();
   return mpTriggerExpression->getInfix();
 }
const CExpression * CEvent::getTriggerExpressionPtr () const
Retrieve the pointer to the expression of trigger.
Returns
CExpression* pExpression
Definition at line 534 of file CEvent.cpp.
References mpTriggerExpression.
Referenced by CModelAdd::addEvents(), CMathEvent::compile(), CModelAdd::copyTriggerExpression(), CQEventDM::data(), CModelExpansion::duplicateEvent(), CSBMLExporter::isEventSBMLCompatible(), SBMLImporter::removeUnusedFunctions(), and CModelExpansion::replaceInEvent().
 {
   return mpTriggerExpression;
 }
CExpression * CEvent::getTriggerExpressionPtr ()
Retrieve the pointer to the expression of trigger.
Returns
CExpression* pExpression
Definition at line 539 of file CEvent.cpp.
References mpTriggerExpression.
 {
   return mpTriggerExpression;
 }
const CEvent::Type & CEvent::getType () const
Retrieve the type of the event
Returns
const Type & type
Definition at line 699 of file CEvent.cpp.
References mType.
Referenced by CMathEvent::compile().
 {
   return mType;
 }
void CEvent::initObjects () private
Definition at line 380 of file CEvent.cpp.
References mpModel, and CModel::setCompileFlag().
Referenced by CEvent().
 {
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
 }
bool CEvent::mustBeDeleted (const DataObjectSet & deletedObjects) const virtual
Check whether an object must be deleted because its prerequisites can no longer be fulfilled due to the given deleted objects
Parameters
const DataObjectSet & deletedObjects
Returns
bool mustBeDeleted
Reimplemented from CCopasiObject.
Definition at line 293 of file CEvent.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), mAssignments, mpDelayExpression, mpPriorityExpression, and mpTriggerExpression.
 {
   bool MustBeDeleted = false;
   CCopasiObject::DataObjectSet ChildObjects;
   if (mpTriggerExpression != NULL)
     {
       ChildObjects.insert(mpTriggerExpression);
     }
   if (mpDelayExpression != NULL)
     {
       ChildObjects.insert(mpDelayExpression);
     }
   if (mpPriorityExpression != NULL)
     {
       ChildObjects.insert(mpPriorityExpression);
     }
   // We need to add all assignment targets and expressions
   CCopasiVector< CEventAssignment >::const_iterator itAssignment = mAssignments.begin();
   CCopasiVector< CEventAssignment >::const_iterator endAssignment = mAssignments.end();
   for (; itAssignment != endAssignment; ++itAssignment)
     {
       if ((*itAssignment)->getTargetObject() != NULL)
         {
           ChildObjects.insert((*itAssignment)->getTargetObject());
         }
       if ((*itAssignment)->getExpressionPtr() != NULL)
         {
           ChildObjects.insert((*itAssignment)->getExpressionPtr());
         }
     }
   DataObjectSet::const_iterator it = ChildObjects.begin();
   DataObjectSet::const_iterator end = ChildObjects.end();
   for (; it != end; ++it)
     {
       if ((*it)->mustBeDeleted(deletedObjects))
         {
           MustBeDeleted = true;
           break;
         }
     }
   return MustBeDeleted;
 }
CEvent& CEvent::operator= (const CEvent &) private
void CEvent::setDelayAssignment (const bool & delayCalculation)
Set whether the calculation or the assignment shall be delayed.
Parameters
const bool & delayCalculation
Definition at line 408 of file CEvent.cpp.
References mDelayAssignment, mpModel, and CModel::setCompileFlag().
Referenced by CModelAdd::addEvents(), CModelExpansion::duplicateEvent(), SBMLImporter::importEvent(), CQEventWidget1::saveToEvent(), and CCopasiXMLParser::EventElement::start().
 {
   if (mDelayAssignment != delayAssignment &&
       mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   mDelayAssignment = delayAssignment;
 }
bool CEvent::setDelayExpression (const std::string & expression)
Set the expression of delay from a string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
Definition at line 544 of file CEvent.cpp.
References CEvaluationTree::getInfix(), mpDelayExpression, mpModel, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by CModel::convert2NonReversible(), CModelAdd::copyDelayExpression(), CModelExpansion::duplicateEvent(), CCopasiXMLParser::EventElement::end(), and CQEventWidget1::saveToEvent().
 {
   if (mpDelayExpression == NULL)
     mpDelayExpression = new CExpression("DelayExpression", this);
   if (mpDelayExpression->getInfix() != expression &&
       mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   return mpDelayExpression->setInfix(expression);
 }
bool CEvent::setDelayExpressionPtr (CExpression * pExpression)
Set the expression of delay from an expression.
Parameters
CExpression* pExpression
Returns
bool success
Definition at line 558 of file CEvent.cpp.
References CCopasiContainer::add(), CExpression::compile(), mpDelayExpression, mpModel, pdelete, CModel::setCompileFlag(), CCopasiObject::setObjectName(), and CCopasiObject::setObjectParent().
Referenced by SBMLImporter::importEvent().
 {
   if (pExpression == mpDelayExpression) return true;
   if (pExpression == NULL) return false;
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   CExpression * pOld = mpDelayExpression;
   mpDelayExpression = pExpression;
   mpDelayExpression->setObjectName("DelayExpression");
   add(mpDelayExpression, true);
   std::vector< CCopasiContainer * > listOfContainer;
   listOfContainer.push_back(mpModel);
   if (mpDelayExpression->compile(listOfContainer))
     {
       pdelete(pOld);
       return true;
     }
   // If compile fails we do not take ownership
   // and we remove the object from the container
   remove(mpDelayExpression);
   mpDelayExpression->setObjectParent(NULL);
   mpDelayExpression = pOld;
   return false;
 }
void CEvent::setFireAtInitialTime (const bool & fireAtInitialTime)
Set whether the trigger may fire at the initial time.
Parameters
const bool & fireAtInitialTime
Definition at line 424 of file CEvent.cpp.
References mFireAtInitialTime.
Referenced by CCopasiXMLParser::EventElement::start().
 {
   mFireAtInitialTime = fireAtInitialTime;
 }
bool CEvent::setObjectParent (const CCopasiContainer * pParent) virtual
Set the object parent
Parameters
const CCopasiContainer * pParent
Returns
bool success
Reimplemented from CCopasiObject.
Definition at line 444 of file CEvent.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectParent(), mpModel, CModel::setCompileFlag(), and CCopasiObject::setObjectParent().
 {
   if (pParent != getObjectParent() &&
       mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   bool success = CCopasiContainer::setObjectParent(pParent);
   mpModel = static_cast<CModel *>(getObjectAncestor("Model"));
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   return success;
 }
void CEvent::setPersistentTrigger (const bool & persistentTrigger)
Set whether the trigger must remain true between firing and executions.
Parameters
const bool & persistentTrigger
Definition at line 434 of file CEvent.cpp.
References mPersistentTrigger.
Referenced by CCopasiXMLParser::EventElement::start().
 {
   mPersistentTrigger = persistentTrigger;
 }
bool CEvent::setPriorityExpression (const std::string & expression)
Set the expression of priority from a string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
Definition at line 611 of file CEvent.cpp.
References CEvaluationTree::getInfix(), mpModel, mpPriorityExpression, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by CModel::convert2NonReversible().
 {
   if (mpPriorityExpression == NULL)
     mpPriorityExpression = new CExpression("PriorityExpression", this);
   if (mpPriorityExpression->getInfix() != expression &&
       mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   return mpPriorityExpression->setInfix(expression);
 }
bool CEvent::setPriorityExpressionPtr (CExpression * pExpression)
Set the expression of priority from an expression.
Parameters
CExpression* pExpression
Returns
bool success
Definition at line 625 of file CEvent.cpp.
References CCopasiContainer::add(), CExpression::compile(), mpModel, mpPriorityExpression, pdelete, CModel::setCompileFlag(), CCopasiObject::setObjectName(), and CCopasiObject::setObjectParent().
 {
   if (pExpression == mpPriorityExpression) return true;
   if (pExpression == NULL) return false;
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   CExpression * pOld = mpPriorityExpression;
   mpPriorityExpression = pExpression;
   mpPriorityExpression->setObjectName("PriorityExpression");
   add(mpPriorityExpression, true);
   std::vector< CCopasiContainer * > listOfContainer;
   listOfContainer.push_back(mpModel);
   if (mpPriorityExpression->compile(listOfContainer))
     {
       pdelete(pOld);
       return true;
     }
   // If compile fails we do not take ownership
   // and we remove the object from the container
   remove(mpPriorityExpression);
   mpPriorityExpression->setObjectParent(NULL);
   mpPriorityExpression = pOld;
   return false;
 }
void CEvent::setSBMLId (const std::string & id)
Sets the SBMLId.
Parameters
const std::string & id
Definition at line 398 of file CEvent.cpp.
References mSBMLId.
Referenced by SBMLImporter::importEvent().
 {
   this->mSBMLId = id;
 }
bool CEvent::setTriggerExpression (const std::string & expression)
Set the expression of trigger from a string. The return value indicates if parsing the expression was successful.
Parameters
const std::string & expression
Returns
bool success
Definition at line 474 of file CEvent.cpp.
References CEvaluationTree::getInfix(), mpModel, mpTriggerExpression, CModel::setCompileFlag(), CExpression::setInfix(), and CExpression::setIsBoolean().
Referenced by CModel::convert2NonReversible(), CModelAdd::copyTriggerExpression(), CMathContainer::createDiscontinuityDataEvent(), CCrossSectionTask::createEvent(), CModelExpansion::duplicateEvent(), CCopasiXMLParser::EventElement::end(), and CQEventWidget1::saveToEvent().
 {
   if (mpTriggerExpression == NULL)
     {
       mpTriggerExpression = new CExpression("TriggerExpression", this);
       mpTriggerExpression->setIsBoolean(true);
     }
   if (mpTriggerExpression->getInfix() != expression &&
       mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   return mpTriggerExpression->setInfix(expression);
 }
bool CEvent::setTriggerExpressionPtr (CExpression * pExpression)
Set the expression of trigger from an expression.
Parameters
CExpression* pExpression
Returns
bool success
Definition at line 491 of file CEvent.cpp.
References CCopasiContainer::add(), CExpression::compile(), mpModel, mpTriggerExpression, pdelete, CModel::setCompileFlag(), CCopasiObject::setObjectName(), and CCopasiObject::setObjectParent().
Referenced by SBMLImporter::importEvent().
 {
   if (pExpression == mpTriggerExpression) return true;
   if (pExpression == NULL) return false;
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   CExpression * pOld = mpTriggerExpression;
   mpTriggerExpression = pExpression;
   mpTriggerExpression->setObjectName("TriggerExpression");
   add(mpTriggerExpression, true);
   std::vector< CCopasiContainer * > listOfContainer;
   listOfContainer.push_back(mpModel);
   if (mpTriggerExpression->compile(listOfContainer))
     {
       pdelete(pOld);
       return true;
     }
   // If compile fails we do not take ownership
   // and we remove the object from the container
   remove(mpTriggerExpression);
   mpTriggerExpression->setObjectParent(NULL);
   mpTriggerExpression = pOld;
   return false;
 }
void CEvent::setType (const Type & type)
Set the type of the event
Parameters
const Type & type
Definition at line 704 of file CEvent.cpp.
References mType.
Referenced by CMathContainer::createDiscontinuityDataEvent(), and CCrossSectionTask::createEvent().
 {
   mType = type;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CEvent & d) friend
insert operator
Definition at line 388 of file CEvent.cpp.
 {
   os << "CEvent:  " << d.getObjectName() << std::endl;
   os << "   SBML id:  " << d.mSBMLId << std::endl;
   os << "----CEvent" << std::endl;
   return os;
 }
Member Data Documentation
CCopasiVectorN< CEventAssignment > CEvent::mAssignments private
A vector assignments expressions which specify the changes made by the event.
Definition at line 417 of file CEvent.h.
Referenced by compile(), deleteAssignment(), getAssignments(), and mustBeDeleted().
bool CEvent::mDelayAssignment private
A Boolean flag indicating whether the calculation or the assignment should be delayed in the case that a delay is present.
Definition at line 423 of file CEvent.h.
Referenced by getDelayAssignment(), and setDelayAssignment().
bool CEvent::mFireAtInitialTime private
A Boolean flag indicating whether the trigger may fire at the initial time if the trigger expression is true;
Definition at line 429 of file CEvent.h.
Referenced by getFireAtInitialTime(), and setFireAtInitialTime().
CExpression* CEvent::mpDelayExpression private
Pointer to the Delay Expression of the event
Definition at line 445 of file CEvent.h.
Referenced by compile(), getDelayExpression(), getDelayExpressionPtr(), mustBeDeleted(), setDelayExpression(), setDelayExpressionPtr(), and ~CEvent().
bool CEvent::mPersistentTrigger private
A Boolean flag indicating whether the trigger expression must remain true between firing and executing the event.
Definition at line 435 of file CEvent.h.
Referenced by getPersistentTrigger(), and setPersistentTrigger().
CModel* CEvent::mpModel private
The parent model
Definition at line 412 of file CEvent.h.
Referenced by initObjects(), setDelayAssignment(), setDelayExpression(), setDelayExpressionPtr(), setObjectParent(), setPriorityExpression(), setPriorityExpressionPtr(), setTriggerExpression(), and setTriggerExpressionPtr().
CExpression* CEvent::mpPriorityExpression private
Pointer to the Priority Expression of the event
Definition at line 450 of file CEvent.h.
Referenced by getPriorityExpression(), getPriorityExpressionPtr(), mustBeDeleted(), setPriorityExpression(), setPriorityExpressionPtr(), and ~CEvent().
CExpression* CEvent::mpTriggerExpression private
Pointer to the boolean Trigger Expression of the event
Definition at line 440 of file CEvent.h.
Referenced by compile(), getTriggerExpression(), getTriggerExpressionPtr(), mustBeDeleted(), setTriggerExpression(), setTriggerExpressionPtr(), and ~CEvent().
std::string CEvent::mSBMLId private
The id of the corresponding event in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Definition at line 462 of file CEvent.h.
Referenced by getSBMLId(), operator<<(), and setSBMLId().
Type CEvent::mType private
The type of the event
Definition at line 455 of file CEvent.h.
Referenced by getType(), and setType().
The documentation for this class was generated from the following files:
CEvent.h
CEvent.cpp