COPASI API: CQOptimizationWidget Class Reference
CQOptimizationWidget Class Reference
#include <CQOptimizationWidget.h>
Public Slots
void slotConstraintNumberChanged (int number)
virtual void slotEditExpression ()
void slotParameterNumberChanged (int number)
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Public Member Functions
CQOptimizationWidget (QWidget *parent=0, const char *name=0)
bool isSteadyState ()
virtual bool runTask ()
~CQOptimizationWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void slotExpressionValid (bool valid)
void slotPageChange (QWidget *currentPage)
void slotSubtaskChanged (const QString &subtask)
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
virtual bool taskFinishedEvent ()
Protected Attributes
QColor mChangedColor
CQFittingItemWidget * mpCurrentList
QColor mSavedColor
std::map< std::string, C_INT32 > mSubtaskMap
bool mTypeChanged
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Private Member Functions
void destroy ()
void init ()
Detailed Description
Definition at line 28 of file CQOptimizationWidget.h.
Constructor & Destructor Documentation
CQOptimizationWidget::CQOptimizationWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 41 of file CQOptimizationWidget.cpp.
References init().
   : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQOptimizationWidget::~CQOptimizationWidget ()
Definition at line 52 of file CQOptimizationWidget.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQOptimizationWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 185 of file CQOptimizationWidget.cpp.
References COptMethod::createMethod().
 {return COptMethod::createMethod(type);}
void CQOptimizationWidget::destroy () private
Definition at line 237 of file CQOptimizationWidget.cpp.
Referenced by ~CQOptimizationWidget().
 {}
void CQOptimizationWidget::init () private
Definition at line 200 of file CQOptimizationWidget.cpp.
References FROM_UTF8, TaskWidget::mpBtnWidget, mpCurrentList, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, mSubtaskMap, CQExpressionWidget::ObjectiveFunctions, CQFittingItemWidget::OPT_CONSTRAINT, CQFittingItemWidget::OPT_ITEM, CQTaskHeaderWidget::setTaskName(), CQTaskMethodWidget::setValidMethods(), CQTaskMethodWidget::showMethodParameters(), slotConstraintNumberChanged(), slotParameterNumberChanged(), CCopasiTask::TypeName, CCopasiTask::unset, COptTask::ValidMethods, and COptProblem::ValidSubtasks.
Referenced by CQOptimizationWidget().
 {
   std::string taskName = "Optimization";
   mpHeaderWidget->setTaskName(taskName);
   verticalLayout->insertWidget(0, mpHeaderWidget);
   // verticalLayout->insertSpacing(1, 14);      // space between header and body
   mpMethodWidget->setValidMethods(COptTask::ValidMethods);
   mpMethodWidget->showMethodParameters(true);
   verticalLayout->addWidget(mpMethodWidget);
   verticalLayout->addWidget(mpBtnWidget);
   mpExpressionEMW->mpExpressionWidget->setExpressionType(CQExpressionWidget::ObjectiveFunctions);
   //mpBtnMaximize->setMinimumWidth(mpLblExpression->width());
   const unsigned int * pSubtask = COptProblem::ValidSubtasks;
   for (; *pSubtask != CCopasiTask::unset; ++pSubtask)
     {
       mpBoxSubtask->insertItem(mpBoxSubtask->count(), FROM_UTF8(CCopasiTask::TypeName[*pSubtask]));
       mSubtaskMap[CCopasiTask::TypeName[*pSubtask]] = *pSubtask;
     }
   mpParameters->setItemType(CQFittingItemWidget::OPT_ITEM);
   connect(mpParameters, SIGNAL(numberChanged(int)), this, SLOT(slotParameterNumberChanged(int)));
   mpConstraints->setItemType(CQFittingItemWidget::OPT_CONSTRAINT);
   connect(mpConstraints, SIGNAL(numberChanged(int)), this, SLOT(slotConstraintNumberChanged(int)));
   mpCurrentList = mpParameters;
 }
bool CQOptimizationWidget::isSteadyState ()
bool CQOptimizationWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 123 of file CQOptimizationWidget.cpp.
References FROM_UTF8, COptProblem::getCalculateStatistics(), CCopasiParameterGroup::getGroup(), COptProblem::getObjectiveFunction(), CCopasiTask::getProblem(), COptProblem::getRandomizeStartValues(), COptProblem::getSubtaskType(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), COptProblem::maximize(), TaskWidget::mChanged, CopasiWidget::mpDataModel, TaskWidget::mpTask, pTask, and CCopasiTask::TypeName.
 {
   COptTask * pTask =
     dynamic_cast< COptTask * >(mpTask);
   if (!pTask) return false;
   loadCommon();
   loadMethod();
   COptProblem * pProblem =
     dynamic_cast<COptProblem *>(mpTask->getProblem());
   if (!pProblem) return false;
   // expression
   mpExpressionEMW->mpExpressionWidget->setExpression(pProblem->getObjectiveFunction());
   mpExpressionEMW->updateWidget();
   mpBtnMaximize->setChecked(pProblem->maximize());
   mpBtnMinimize->setChecked(!pProblem->maximize());
   mpCheckRandomize->setChecked(pProblem->getRandomizeStartValues());
   mpCheckStatistics->setChecked(pProblem->getCalculateStatistics());
   mpBoxSubtask->setCurrentIndex(mpBoxSubtask->findText(FROM_UTF8(CCopasiTask::TypeName[pProblem->getSubtaskType()])));
   mpParameters->load(mpDataModel, pProblem->getGroup("OptimizationItemList"), NULL, NULL);
   mpConstraints->load(mpDataModel, pProblem->getGroup("OptimizationConstraintList"), NULL, NULL);
   mChanged = false;
   return true;
 }
bool CQOptimizationWidget::runTask () virtual
Implements TaskWidget.
Definition at line 159 of file CQOptimizationWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CopasiWidget::mKey, and pTask.
Referenced by SliderDialog::runOptimizationTask().
 {
   // --- expression
   mpExpressionEMW->updateWidget();
   // ----
   COptTask * pTask =
     dynamic_cast< COptTask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!pTask) return false;
   if (!commonBeforeRunTask()) return false;
   return commonRunTask();
 }
bool CQOptimizationWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 58 of file CQOptimizationWidget.cpp.
References CCopasiMessage::ERROR, FROM_UTF8, COptProblem::getCalculateStatistics(), CCopasiRootContainer::getDatamodelList(), COptProblem::getObjectiveFunction(), CCopasiTask::getProblem(), COptProblem::getRandomizeStartValues(), COptProblem::getSubtaskType(), COptProblem::maximize(), TaskWidget::mChanged, MCOptimization, TaskWidget::mpTask, mSubtaskMap, pTask, TaskWidget::saveCommon(), TaskWidget::saveMethod(), COptProblem::setCalculateStatistics(), COptProblem::setMaximize(), COptProblem::setObjectiveFunction(), COptProblem::setRandomizeStartValues(), COptProblem::setSubtaskType(), TO_UTF8, and CCopasiTask::TypeName.
 {
   COptTask * pTask =
     dynamic_cast< COptTask * >(mpTask);
   if (!pTask) return false;
   saveCommon();
   saveMethod();
   COptProblem * pProblem =
     dynamic_cast<COptProblem *>(mpTask->getProblem());
   if (!pProblem) return false;
   // expression
   if (pProblem->getObjectiveFunction() != mpExpressionEMW->mpExpressionWidget->getExpression())
     {
       if (!pProblem->setObjectiveFunction(mpExpressionEMW->mpExpressionWidget->getExpression()))
         {
           CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 5);
           return false;
         }
       mChanged = true;
     }
   if (mpBoxSubtask->currentText() != FROM_UTF8(CCopasiTask::TypeName[pProblem->getSubtaskType()]))
     {
       mChanged = true;
       pProblem->setSubtaskType((CCopasiTask::Type) mSubtaskMap[TO_UTF8(mpBoxSubtask->currentText())]);
     }
   if (mpBtnMaximize->isChecked() != pProblem->maximize())
     {
       mChanged = true;
       pProblem->setMaximize(mpBtnMaximize->isChecked());
     }
   if (mpCheckRandomize->isChecked() != pProblem->getRandomizeStartValues())
     {
       mChanged = true;
       pProblem->setRandomizeStartValues(mpCheckRandomize->isChecked());
     }
   if (mpCheckStatistics->isChecked() != pProblem->getCalculateStatistics())
     {
       mChanged = true;
       pProblem->setCalculateStatistics(mpCheckStatistics->isChecked());
     }
   mChanged |= mpParameters->save(NULL, NULL);
   mChanged |= mpConstraints->save(NULL, NULL);
   if (mChanged)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed();
     }
   mChanged = false;
   return true;
 }
void CQOptimizationWidget::slotConstraintNumberChanged (int number) slot
Definition at line 194 of file CQOptimizationWidget.cpp.
Referenced by init().
 {
   QString TabLabel = "Constraints (" + QString::number(number) + ")";
   mpTabWidget->setTabText(mpTabWidget->indexOf(mpConstraints), TabLabel);
 }
void CQOptimizationWidget::slotEditExpression () virtual slot
The slot to activate the editor page of type CQExpressionWidget for being able to type a new mathematical expression or edit the existing one
Definition at line 249 of file CQOptimizationWidget.cpp.
 {}
void CQOptimizationWidget::slotExpressionValid (bool valid) protected slot
Definition at line 240 of file CQOptimizationWidget.cpp.
References TaskWidget::mpBtnWidget.
 {
   mpBtnWidget->mpBtnRun->setEnabled(valid);
 }
void CQOptimizationWidget::slotPageChange (QWidget * currentPage) protected slot
Definition at line 177 of file CQOptimizationWidget.cpp.
References mpCurrentList.
 {
   if (mpTabWidget->tabText(mpTabWidget->indexOf(currentPage)).contains("Parameters", Qt::CaseSensitive))
     mpCurrentList = mpParameters;
   else
     mpCurrentList = mpConstraints;
 }
void CQOptimizationWidget::slotParameterNumberChanged (int number) slot
Definition at line 188 of file CQOptimizationWidget.cpp.
Referenced by init().
 {
   QString TabLabel = "Parameters (" + QString::number(number) + ")";
   mpTabWidget->setTabText(mpTabWidget->indexOf(mpParameters), TabLabel);
 }
void CQOptimizationWidget::slotSubtaskChanged (const QString & subtask) protected slot
Definition at line 252 of file CQOptimizationWidget.cpp.
 {}
Member Data Documentation
QColor CQOptimizationWidget::mChangedColor protected
Definition at line 46 of file CQOptimizationWidget.h.
CQFittingItemWidget* CQOptimizationWidget::mpCurrentList protected
Definition at line 45 of file CQOptimizationWidget.h.
Referenced by init(), and slotPageChange().
QColor CQOptimizationWidget::mSavedColor protected
Definition at line 47 of file CQOptimizationWidget.h.
std::map< std::string, C_INT32 > CQOptimizationWidget::mSubtaskMap protected
Definition at line 50 of file CQOptimizationWidget.h.
Referenced by init(), and saveTask().
bool CQOptimizationWidget::mTypeChanged protected
Definition at line 48 of file CQOptimizationWidget.h.
The documentation for this class was generated from the following files:
CQOptimizationWidget.h
CQOptimizationWidget.cpp