COPASI API: CReference Class Reference
CReference Class Reference
#include <CReference.h>
Public Member Functions
void clearInvalidEntries ()
CReference (const std::string &objectName, const CCopasiContainer *pParent=NULL)
CReference (const CRDFTriplet &triplet, const std::string &objectName="", const CCopasiContainer *pParent=NULL)
CReference (const CReference &src, const CCopasiContainer *pParent=NULL)
const std::string & getDescription () const
const std::string & getId () const
virtual const std::string & getKey () const
const CMIRIAMResourceObject & getMIRIAMResourceObject () const
std::string getResource () const
const CRDFTriplet & getTriplet () const
std::string getURI () const
void setDescription (const std::string &description)
void setId (const std::string &id)
void setResource (const std::string &resource)
~CReference ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
CRDFTriplet mIdTriplet
std::string mKey
CRDFPredicate::Path mNodePath
CMIRIAMResourceObject mResource
CRDFTriplet mTriplet
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CReferences: Stores publication details such as PubMed Id and DOI.
Definition at line 24 of file CReference.h.
Constructor & Destructor Documentation
CReference::CReference (const std::string & objectName, const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & objectName
const CCopasiContainer * pParent (default: NULL)
Definition at line 22 of file CReference.cpp.
                                                         :
   CCopasiContainer(objectName, pParent, "Reference"),
   mTriplet(),
   mNodePath(),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Reference", this)),
   mIdTriplet(),
   mResource(NULL)
 {}
CReference::CReference (const CRDFTriplet & triplet, const std::string & objectName = "", const CCopasiContainer * pParent = NULL)
Specific constructor
Parameters
const CRDFTriplet & triplet
const std::string & objectName (default: "")
const CCopasiContainer * pParent (default: NULL)
Definition at line 32 of file CReference.cpp.
References CRDFPredicate::bqbiol_isDescribedBy, CRDFPredicate::bqmodel_isDescribedBy, CRDFPredicate::copasi_isDescribedBy, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), mIdTriplet, mNodePath, mResource, mTriplet, CRDFTriplet::pObject, and CMIRIAMResourceObject::setNode().
                                                         :
   CCopasiContainer(objectName, pParent, "Reference"),
   mTriplet(triplet),
   mNodePath(),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Creator", this)),
   mIdTriplet(),
   mResource(NULL)
 {
   if (!mTriplet)
     return;
   mNodePath = mTriplet.pObject->getPath();
   CRDFPredicate::ePredicateType Predicates[] =
   {
     CRDFPredicate::copasi_isDescribedBy,
     CRDFPredicate::bqbiol_isDescribedBy,
     CRDFPredicate::bqmodel_isDescribedBy,
     CRDFPredicate::end
   };
   std::set< CRDFTriplet > Triples;
   CRDFPredicate::ePredicateType * pPredicate = Predicates;
   std::set< CRDFTriplet >::iterator it;
   for (; *pPredicate != CRDFPredicate::end; ++pPredicate)
     {
       Triples = mTriplet.pObject->getDescendantsWithPredicate(*pPredicate);
       it = Triples.begin();
       if (it != Triples.end())
         {
           mIdTriplet = *it;
           mResource.setNode(mIdTriplet.pObject);
         }
     }
 }
CReference::CReference (const CReference & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CReference & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 73 of file CReference.cpp.
                                                         :
   CCopasiContainer(src, pParent),
   mTriplet(src.mTriplet),
   mNodePath(src.mNodePath),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Creator", this)),
   mIdTriplet(src.mIdTriplet),
   mResource(src.mResource)
 {}
CReference::~CReference ()
Destructor
Definition at line 83 of file CReference.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
void CReference::clearInvalidEntries ()
Remove invalid combinations of resource and id
Definition at line 165 of file CReference.cpp.
References CRDFPredicate::copasi_isDescribedBy, CMIRIAMResourceObject::isValid(), mIdTriplet, mNodePath, mResource, mTriplet, CRDFTriplet::pObject, CRDFNode::setFieldValue(), and CMIRIAMResourceObject::setURI().
 {
   // Empty descriptions are handled automatically since setFieldValue removes
   // a triplet if the value is an empty string.
   // Handle invalid resource
   if (!mResource.isValid() && mIdTriplet)
     {
       // We remove the Id triplet
       mTriplet.pObject->setFieldValue("", CRDFPredicate::copasi_isDescribedBy, mNodePath);
       mIdTriplet = CRDFTriplet(); // This makes it invalid.
       mResource.setURI("---");
     }
 }
const std::string & CReference::getDescription () const
Retrieve the description for the reference.
Returns
std::string description
Definition at line 157 of file CReference.cpp.
References CRDFPredicate::dcterms_description, CRDFNode::getFieldValue(), mTriplet, and CRDFTriplet::pObject.
 {return mTriplet.pObject->getFieldValue(CRDFPredicate::dcterms_description);}
const std::string & CReference::getId () const
Retrieve the id of the reference in the MIRIAM resource.
Returns
const std::string & id
Definition at line 127 of file CReference.cpp.
References CMIRIAMResourceObject::getId(), and mResource.
 {return mResource.getId();}
const std::string & CReference::getKey () const virtual
Retrieve the key for the object
Returns
const std::string & key
Reimplemented from CCopasiObject.
Definition at line 95 of file CReference.cpp.
References mKey.
 {return mKey;}
const CMIRIAMResourceObject & CReference::getMIRIAMResourceObject () const
Retrieve the MIRIAM resource object for this reference
Definition at line 90 of file CReference.cpp.
References mResource.
Referenced by CQMiriamWidget::slotBtnBrowseReference(), and CSBMLExporter::updateMIRIAMAnnotation().
 {
   return mResource;
 }
std::string CReference::getResource () const
Retrieve the MIRIAM resource for the reference.
Returns
std::string resource
Definition at line 98 of file CReference.cpp.
References CMIRIAMResourceObject::getDisplayName(), and mResource.
 {return mResource.getDisplayName();}
const CRDFTriplet & CReference::getTriplet () const
Retrieve the RDF triplet holding the information for this reference.
Returns
const CRDFTriplet & triplet
Definition at line 88 of file CReference.cpp.
References mTriplet.
Referenced by CMIRIAMInfo::removeReference(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return mTriplet;}
std::string CReference::getURI () const
Retrieve the URI (comprised of resource an id) specifying this reference.
Returns
std::string uri
Definition at line 154 of file CReference.cpp.
References CMIRIAMResourceObject::getURI(), and mResource.
 {return mResource.getURI();}
void CReference::setDescription (const std::string & description)
Set the description for the reference.
Parameters
std::string description
Definition at line 160 of file CReference.cpp.
References CRDFPredicate::dcterms_description, mNodePath, mTriplet, CRDFTriplet::pObject, and CRDFNode::setFieldValue().
 {
   mTriplet.pObject->setFieldValue(description, CRDFPredicate::dcterms_description, mNodePath);
 }
void CReference::setId (const std::string & id)
Set the id of the reference in the MIRIAM resource.
Parameters
const std::string & id
Definition at line 130 of file CReference.cpp.
References CRDFPredicate::copasi_isDescribedBy, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getObject(), CMIRIAMResourceObject::getURI(), mIdTriplet, mNodePath, mResource, mTriplet, CRDFTriplet::pObject, CRDFNode::setFieldValue(), CMIRIAMResourceObject::setId(), CMIRIAMResourceObject::setNode(), and CRDFObject::setResource().
 {
   if (!mIdTriplet)
     {
       // We create an Id triplet
       mTriplet.pObject->setFieldValue("---", CRDFPredicate::copasi_isDescribedBy, mNodePath);
       std::set< CRDFTriplet > Triples;
       std::set< CRDFTriplet >::iterator it;
       Triples = mTriplet.pObject->getDescendantsWithPredicate(CRDFPredicate::copasi_isDescribedBy);
       it = Triples.begin();
       if (it != Triples.end())
         {
           mIdTriplet = *it;
           mResource.setNode(mIdTriplet.pObject);
         }
     }
   if (mResource.setId(id))
     mIdTriplet.pObject->getObject().setResource(mResource.getURI(), false);
 }
void CReference::setResource (const std::string & resource)
Set the MIRIAM resource for the reference
Parameters
const std::string & resource
Definition at line 101 of file CReference.cpp.
References CRDFPredicate::copasi_isDescribedBy, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getObject(), CMIRIAMResourceObject::getURI(), mIdTriplet, mNodePath, mResource, mTriplet, CRDFTriplet::pObject, CMIRIAMResourceObject::setDisplayName(), CRDFNode::setFieldValue(), CMIRIAMResourceObject::setNode(), and CRDFObject::setResource().
 {
   if (!mIdTriplet)
     {
       // We create an Id triplet
       // This only adds the triplet if the resource is valid, i.e., it does not work;
       mTriplet.pObject->setFieldValue("---", CRDFPredicate::copasi_isDescribedBy, mNodePath);
       std::set< CRDFTriplet > Triples;
       std::set< CRDFTriplet >::iterator it;
       Triples = mTriplet.pObject->getDescendantsWithPredicate(CRDFPredicate::copasi_isDescribedBy);
       it = Triples.begin();
       if (it != Triples.end())
         {
           mIdTriplet = *it;
           mResource.setNode(mIdTriplet.pObject);
         }
     }
   if (mResource.setDisplayName(resource))
     mIdTriplet.pObject->getObject().setResource(mResource.getURI(), false);
 }
Member Data Documentation
CRDFTriplet CReference::mIdTriplet private
Triplet in the RDF graph representing the reference.
Definition at line 46 of file CReference.h.
Referenced by clearInvalidEntries(), CReference(), setId(), and setResource().
std::string CReference::mKey private
The key of the object needed for the COPASI tables.
Definition at line 41 of file CReference.h.
Referenced by getKey(), and ~CReference().
CRDFPredicate::Path CReference::mNodePath private
The predicate path to the node.
Definition at line 36 of file CReference.h.
Referenced by clearInvalidEntries(), CReference(), setDescription(), setId(), and setResource().
CMIRIAMResourceObject CReference::mResource private
MIRIAM resource for holding database and Id.
Definition at line 51 of file CReference.h.
Referenced by clearInvalidEntries(), CReference(), getId(), getMIRIAMResourceObject(), getResource(), getURI(), setId(), and setResource().
CRDFTriplet CReference::mTriplet private
Triplet in the RDF graph representing the reference.
Definition at line 31 of file CReference.h.
Referenced by clearInvalidEntries(), CReference(), getDescription(), getTriplet(), setDescription(), setId(), and setResource().
The documentation for this class was generated from the following files:
CReference.h
CReference.cpp