COPASI API: CQValidatorFunction Class Reference
CQValidatorFunction Class Reference
#include <CQExpressionWidget.h>
Signals
void stateChanged (bool) const
Public Member Functions
CQValidatorFunction (QTextEdit *parent, const char *name=0)
virtual CFunction * getFunction ()
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QTextEdit >
CQValidator (QTextEdit *parent, QString(QTextEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Protected Attributes
CFunction mFunction
Protected Attributes inherited from CQValidator< QTextEdit >
QString mLastAccepted
QTextEdit * mpContainer
QString(QTextEdit::* mRetrieve)(void) const
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QTextEdit >
State setColor (const State &state) const
Detailed Description
The class for checking the validity of a given mathematical function
Definition at line 82 of file CQExpressionWidget.h.
Constructor & Destructor Documentation
CQValidatorFunction::CQValidatorFunction (QTextEdit * parent, const char * name = 0)
Specific constructor
Parameters
QTextEdit * parent
const char * name (Default: NULL)
Definition at line 132 of file CQExpressionWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), mFunction, and CCopasiObject::setObjectParent().
                                                                              :
   CQValidator< QTextEdit >(parent, &QTextEdit::toPlainText, name),
   mFunction()
 {
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   mFunction.setObjectParent(pDataModel);
 }
Member Function Documentation
CFunction * CQValidatorFunction::getFunction () virtual
Retrieve a pointer to the function object
Returns
CFunction * pFunction
Definition at line 181 of file CQExpressionWidget.cpp.
References mFunction.
Referenced by CQExpressionWidget::writeMathML().
 {
   return &mFunction;
 }
void CQValidatorFunction::stateChanged (bool) const signal
Referenced by validate().
QValidator::State CQValidatorFunction::validate (QString & input, int & pos) const virtual
Function to validate a string input
Parameters
QString & input
int & pos
Returns
State
This function ensures that any characters on Expression Widget are validated to go to further processes.
Reimplemented from CQValidator< QTextEdit >.
Definition at line 146 of file CQExpressionWidget.cpp.
References CQExpressionWidget::getFunction(), CMassAction::Infix, mFunction, CQValidator< QTextEdit >::mpContainer, CQValidator< QTextEdit >::mRetrieve, CQValidator< QTextEdit >::setColor(), stateChanged(), and CQValidator< Type >::validate().
 {
   // The input is the display version of the infix string.
   // We must first convert the display string to infix.
   State CurrentState = Invalid;
   CQExpressionWidget * pExpressionWidget =
     static_cast< CQExpressionWidget * >(parent());
   if (pExpressionWidget != NULL)
     {
       std::string Infix = pExpressionWidget->getFunction();
       if (Infix == CMassAction::Infix[0] ||
           Infix == CMassAction::Infix[1] ||
           (const_cast< CFunction * >(&mFunction)->setInfix(Infix) &&
            const_cast< CFunction * >(&mFunction)->compile()))
         {
           QString Input = (*mpContainer.*mRetrieve)();
           CurrentState = CQValidator< QTextEdit >::validate(input, pos);
         }
     }
   if (CurrentState != Acceptable)
     {
       setColor(Invalid);
       CurrentState = Intermediate;
     }
   emit stateChanged(CurrentState == Acceptable);
   return CurrentState;
 }
Member Data Documentation
CFunction CQValidatorFunction::mFunction protected
Definition at line 108 of file CQExpressionWidget.h.
Referenced by CQValidatorFunction(), getFunction(), and validate().
The documentation for this class was generated from the following files:
CQExpressionWidget.h
CQExpressionWidget.cpp