COPASI API: TaskWidget Class Reference
TaskWidget Class Reference abstract
#include <TaskWidget.h>
Public Slots
void adjustTable ()
void slotFinishThread ()
Public Member Functions
CCopasiTask * getTask ()
virtual bool leave ()
virtual bool runTask ()=0
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)=0
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
virtual bool loadTask ()=0
bool saveCommon ()
bool saveMethod ()
virtual bool saveTask ()=0
virtual bool taskFinishedEvent ()
Protected Attributes
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 57 of file TaskWidget.h.
Constructor & Destructor Documentation
TaskWidget::TaskWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 52 of file TaskWidget.cpp.
References assistantBtnClicked(), mpBtnWidget, mpHeaderWidget, mpMethodWidget, mpTaskThread, reportBtnClicked(), revertBtnClicked(), runBtnClicked(), and slotFinishThread().
                                                                     :
   CopasiWidget(parent, name, fl),
   mProgressBar(NULL),
   mpHeaderWidget(NULL),
   mpMethodWidget(NULL),
   mpBtnWidget(NULL),
   mpMethodLayout(NULL),
   mpSpacer1(NULL),
   mpSpacer2(NULL),
   mpTask(NULL),
   mpMethod(NULL),
   mChanged(false)
 {
   if (!name)
     setObjectName("TaskWidget");
   setWindowTitle(trUtf8("TaskWidget"));
   mpTaskThread = new CQTaskThread(this);
   mpHeaderWidget = new CQTaskHeaderWidget(this);
   mpMethodWidget = new CQTaskMethodWidget(this);
   mpBtnWidget = new CQTaskBtnWidget(this);
   connect(mpBtnWidget->mpBtnRun, SIGNAL(clicked()), this, SLOT(runBtnClicked()));
   connect(mpBtnWidget->mpBtnRevert, SIGNAL(clicked()), this, SLOT(revertBtnClicked()));
   connect(mpBtnWidget->mpBtnReport, SIGNAL(clicked()), this, SLOT(reportBtnClicked()));
   connect(mpBtnWidget->mpBtnAssistant, SIGNAL(clicked()), this, SLOT(assistantBtnClicked()));
   connect(mpTaskThread, SIGNAL(finished()), this, SLOT(slotFinishThread()));
 }
TaskWidget::~TaskWidget ()
Definition at line 84 of file TaskWidget.cpp.
References mpTaskThread, and pdelete.
 {
   pdelete(mpTaskThread);
 }
Member Function Documentation
void TaskWidget::adjustTable () slot
Definition at line 293 of file TaskWidget.cpp.
Referenced by CopasiUI3Window::slotFontSelection().
 {
 #ifdef DEBUG_UI
   qDebug() << "--> TaskWidget::adjustTable <--";
 #endif
   // mpTblParameter->resizeColumnsToContents();
   // mpTblParameter->resizeRowsToContents();
   /*
   mpTblParameter->setFixedSize(mpTblParameter->columnWidth(0) + mpTblParameter->verticalHeader()->sizeHint().width() + 5,
                                mpTblParameter->verticalHeader()->sizeHint().height() * mpTblParameter->rowCount() + 5);
                                */
 }
void TaskWidget::assistantBtnClicked () protected slot
Definition at line 228 of file TaskWidget.cpp.
References ListViews::ADD, mpTask, ListViews::PLOT, CopasiWidget::protectedNotify(), saveTask(), and DefaultPlotDialog::setTask().
Referenced by TaskWidget().
 {
   if (!mpTask) return;
   saveTask(); //this is necessary since the output may use information from the problem
   DefaultPlotDialog * pDlg = new DefaultPlotDialog(this);
   pDlg->setTask(mpTask);
   if (pDlg->exec() == QDialog::Accepted)
     {
       protectedNotify(ListViews::PLOT, ListViews::ADD, "");
     }
   if (pDlg)delete pDlg;
 }
bool TaskWidget::commonAfterRunTask () protected
Definition at line 365 of file TaskWidget.cpp.
References ListViews::CHANGE, CCopasiMessage::clearDeque(), CProgressBar::finish(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWindow(), loadTask(), mProgressBar, mpTask, CopasiWidget::protectedNotify(), CCopasiTask::setCallBack(), ListViews::STATE, CopasiUI3Window::suspendAutoSave(), CModel::updateNonSimulatedValues(), and CModel::updateSimulatedValues().
Referenced by finishTask().
 {
   if (!mpTask) return false;
   if (mProgressBar != NULL)
     {
       mProgressBar->finish();
       mProgressBar->deleteLater();
       mProgressBar = NULL;
     }
   mpTask->setCallBack(NULL);
   CCopasiMessage::clearDeque();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   (*CCopasiRootContainer::getDatamodelList())[0]->finish();
   // Update all values shown in the GUI
   CModel * pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   pModel->updateSimulatedValues(true);
   pModel->updateNonSimulatedValues();
   protectedNotify(ListViews::STATE, ListViews::CHANGE, (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
   unsetCursor();
   CopasiUI3Window::getMainWindow()->suspendAutoSave(false);
   return loadTask();
 }
bool TaskWidget::commonBeforeRunTask () protected
Definition at line 317 of file TaskWidget.cpp.
References CopasiUI3Window::autoSave(), CCopasiMessage::clearDeque(), CReport::confirmOverwrite(), CProgressBar::create(), CQMessageBox::critical(), CCopasiMessage::getAllMessageText(), CopasiUI3Window::getMainWindow(), CCopasiTask::getReport(), CReport::getTarget(), mProgressBar, mpTask, saveTask(), CCopasiTask::setCallBack(), and CopasiUI3Window::suspendAutoSave().
Referenced by CQCrossSectionTaskWidget::runTask(), CQMoietiesTaskWidget::runTask(), CQLNAWidget::runTask(), CQLyapWidget::runTask(), CQMCAWidget::runTask(), CQFittingWidget::runTask(), CQEFMWidget::runTask(), CQOptimizationWidget::runTask(), ScanWidget::runTask(), CQTSSAWidget::runTask(), SensitivitiesWidget::runTask(), SteadyStateWidget::runTask(), and CQTrajectoryWidget::runTask().
 {
   // save the state of the widget
   if (!saveTask())
     {
       CQMessageBox::critical(this, "Simulation Error",
                              CCopasiMessage::getAllMessageText().c_str(),
                              QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
       return false;
     }
   if (!mpTask) return false;
   if (mProgressBar != NULL)
     {
       //CQMessageBox::critical(this, "Task in Progress",
       //                       "A task is currently running, another cannot be started before the current task ended.",
       //                       QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
       return false;
     }
   // if overwrite is enabled and the file exists, then ask
   if (!mpTask->getReport().getTarget().empty() &&
       mpTask->getReport().confirmOverwrite() &&
       QFile(mpTask->getReport().getTarget().c_str()).exists())
     {
       if (QMessageBox::question(this,
                                 QString("Confirm Overwrite"),
                                 QString("The report file already exists. Would you like to overwrite it? \n\n(You can disable this dialog by clicking the 'Report' button.)"),
                                 QMessageBox::Yes, QMessageBox::No) == QMessageBox::No)
         return false;
     }
   //set mouse cursor
   setCursor(Qt::WaitCursor);
   //handle autosave feature
   CopasiUI3Window::getMainWindow()->autoSave();
   CopasiUI3Window::getMainWindow()->suspendAutoSave(true);
   //create progress bar
   mProgressBar = CProgressBar::create();
   mpTask->setCallBack(mProgressBar);
   CCopasiMessage::clearDeque();
   return true;
 }
bool TaskWidget::commonRunTask () protected
Definition at line 395 of file TaskWidget.cpp.
References C_INT, CCopasiMessage::clearDeque(), CCopasiMessage::COMMANDLINE, CQMessageBox::critical(), CCopasiMessage::ERROR, CProgressBar::finish(), finishTask(), CCopasiMessage::getAllMessageText(), CCopasiRootContainer::getDatamodelList(), CCopasiMessage::getHighestSeverity(), CCopasiMessage::getNumber(), CCopasiTask::initialize(), MCCopasiMessage, mProgressBar, mpTask, mpTaskThread, CCopasiTask::OUTPUT_UI, CCopasiMessage::peekLastMessage(), and CQMessageBox::question().
Referenced by CQCrossSectionTaskWidget::runTask(), CQMoietiesTaskWidget::runTask(), CQLNAWidget::runTask(), CQLyapWidget::runTask(), CQMCAWidget::runTask(), CQFittingWidget::runTask(), CQEFMWidget::runTask(), CQOptimizationWidget::runTask(), ScanWidget::runTask(), CQTSSAWidget::runTask(), SensitivitiesWidget::runTask(), SteadyStateWidget::runTask(), and CQTrajectoryWidget::runTask().
 {
   // Initialize the task
   try
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       if (!mpTask->initialize(CCopasiTask::OUTPUT_UI, (*CCopasiRootContainer::getDatamodelList())[0], NULL))
         throw CCopasiException(CCopasiMessage::peekLastMessage());
     }
   catch (CCopasiException & /*Exception*/)
     {
       if (CCopasiMessage::peekLastMessage().getNumber() != MCCopasiMessage + 1)
         {
           if (mProgressBar != NULL) mProgressBar->finish();
           CQMessageBox::critical(this, "Initialization Error",
                                  CCopasiMessage::getAllMessageText().c_str(),
                                  QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
           finishTask();
           return false;
         }
     }
   if (CCopasiMessage::getHighestSeverity() > CCopasiMessage::ERROR)
     {
       if (mProgressBar != NULL) mProgressBar->finish();
       CQMessageBox::critical(this, "Initialization Error",
                              CCopasiMessage::getAllMessageText().c_str(),
                              QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
       finishTask();
       return false;
     }
   if (CCopasiMessage::getHighestSeverity() > CCopasiMessage::COMMANDLINE)
     {
       C_INT Result =
         CQMessageBox::question(this, "Initialization Warning",
                                CCopasiMessage::getAllMessageText().c_str(),
                                QMessageBox::Ignore | QMessageBox::Abort, QMessageBox::Ignore);
       if (Result == QMessageBox::Abort)
         {
           finishTask();
           return false;
         }
     }
   CCopasiMessage::clearDeque();
   // Execute the task
   mpTaskThread->start();
   return true;
 }
virtual CCopasiMethod* TaskWidget::createMethod (const CCopasiMethod::SubType & type) protected pure virtual
Implemented in CQTrajectoryWidget, CQOptimizationWidget, CQTSSAWidget, SteadyStateWidget, CQFittingWidget, ScanWidget, SensitivitiesWidget, CQOscillationTaskWidget, CQEFMWidget, CQLNAWidget, CQMCAWidget, CQCrossSectionTaskWidget, CQLyapWidget, and CQMoietiesTaskWidget.
bool TaskWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 547 of file TaskWidget.cpp.
References CCopasiTask::getMethod(), loadTask(), mpMethod, CopasiWidget::mpObject, and mpTask.
 {
   mpTask = dynamic_cast< CCopasiTask * >(mpObject);
   // :TODO: We need a message here.
   if (!mpTask) return false;
   mpMethod = mpTask->getMethod();
   return loadTask();
 }
void TaskWidget::finishTask () protected
Definition at line 474 of file TaskWidget.cpp.
References CCopasiMessage::clearDeque(), CCopasiMessage::COMMANDLINE, commonAfterRunTask(), CQMessageBox::critical(), CProgressBar::finish(), CCopasiMessage::getAllMessageText(), CCopasiMessage::getHighestSeverity(), CQMessageBox::information(), MCCopasiMessage, mProgressBar, mpTask, CCopasiMessage::peekLastMessage(), CCopasiTask::restore(), and taskFinishedEvent().
Referenced by commonRunTask(), and slotFinishThread().
 {
   CCopasiMessage::clearDeque();
   try {mpTask->restore();}
   catch (CCopasiException & /*Exception*/)
     {
       if (CCopasiMessage::peekLastMessage().getNumber() != MCCopasiMessage + 1)
         {
           if (mProgressBar != NULL) mProgressBar->finish();
           CQMessageBox::critical(this, "Calculation Error", CCopasiMessage::getAllMessageText().c_str(),
                                  QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
           CCopasiMessage::clearDeque();
         }
     }
   catch (...) {}
   if (CCopasiMessage::getHighestSeverity() > CCopasiMessage::COMMANDLINE)
     {
       CQMessageBox::information(this, "Calculation Warning",
                                 CCopasiMessage::getAllMessageText().c_str(),
                                 QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
     }
   CCopasiMessage::clearDeque();
   commonAfterRunTask();
   taskFinishedEvent();
 }
CCopasiTask * TaskWidget::getTask ()
Definition at line 513 of file TaskWidget.cpp.
References mpTask.
Referenced by Worker::getIndexForWidget(), and CQTaskThread::run().
 {
   return mpTask;
 }
bool TaskWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 542 of file TaskWidget.cpp.
References saveTask().
Referenced by SliderDialog::runTask().
 {
   return saveTask();
 }
bool TaskWidget::loadCommon () protected
Definition at line 247 of file TaskWidget.cpp.
References CCopasiTask::isScheduled(), CCopasiTask::isUpdateModel(), mpHeaderWidget, mpTask, and CQTaskHeaderWidget::saved().
Referenced by CQMoietiesTaskWidget::loadTask(), CQEFMWidget::loadTask(), CQCrossSectionTaskWidget::loadTask(), CQLyapWidget::loadTask(), CQLNAWidget::loadTask(), ScanWidget::loadTask(), CQMCAWidget::loadTask(), SensitivitiesWidget::loadTask(), SteadyStateWidget::loadTask(), CQFittingWidget::loadTask(), CQTSSAWidget::loadTask(), CQOptimizationWidget::loadTask(), and CQTrajectoryWidget::loadTask().
 {
   if (!mpTask) return false;
   mpHeaderWidget->mpBoxExecutable->setChecked(mpTask->isScheduled());
   mpHeaderWidget->mpUpdateModel->setChecked(mpTask->isUpdateModel());
   mpHeaderWidget->saved();
   return true;
 }
bool TaskWidget::loadMethod () protected
Definition at line 284 of file TaskWidget.cpp.
References CQTaskMethodWidget::loadMethod(), mpMethodWidget, mpTask, and CQTaskMethodWidget::setTask().
Referenced by CQCrossSectionTaskWidget::loadTask(), CQEFMWidget::loadTask(), CQLyapWidget::loadTask(), SensitivitiesWidget::loadTask(), SteadyStateWidget::loadTask(), CQFittingWidget::loadTask(), CQTSSAWidget::loadTask(), CQOptimizationWidget::loadTask(), and CQTrajectoryWidget::loadTask().
 {
   if (!mpTask) return false;
   mpMethodWidget->setTask(mpTask);
   return mpMethodWidget->loadMethod();
 }
virtual bool TaskWidget::loadTask () protected pure virtual
Implemented in CQTrajectoryWidget, CQOptimizationWidget, CQTSSAWidget, CQFittingWidget, SteadyStateWidget, SensitivitiesWidget, CQLNAWidget, CQMCAWidget, ScanWidget, CQOscillationTaskWidget, CQLyapWidget, CQCrossSectionTaskWidget, CQEFMWidget, and CQMoietiesTaskWidget.
Referenced by commonAfterRunTask(), enterProtected(), and revertBtnClicked().
void TaskWidget::reportBtnClicked () protected slot
Definition at line 216 of file TaskWidget.cpp.
References CQReportDefinitionSelect::exec(), CCopasiTask::getReport(), CQReportDefinitionSelect::loadReportDefinitionVector(), CopasiWidget::mpListView, mpTask, and CQReportDefinitionSelect::setReport().
Referenced by TaskWidget().
 {
   if (!mpTask) return;
   CQReportDefinitionSelect * pSelectDlg = new CQReportDefinitionSelect(mpListView);
   pSelectDlg->setReport(&mpTask->getReport());
   pSelectDlg->loadReportDefinitionVector();
   pSelectDlg->exec();
   delete pSelectDlg;
 }
void TaskWidget::revertBtnClicked () protected slot
Definition at line 193 of file TaskWidget.cpp.
References CCopasiTask::getMethod(), loadTask(), mpMethod, mpTask, and pdelete.
Referenced by TaskWidget().
 {
   if (!mpTask) return;
   CCopasiMethod* pMethod = mpTask->getMethod();
   if (pMethod != mpMethod)
     {
       pdelete(mpMethod);
       mpMethod = pMethod;
     }
   loadTask();
 }
void TaskWidget::runBtnClicked () protected slot
Definition at line 208 of file TaskWidget.cpp.
References mpBtnWidget, and runTask().
Referenced by TaskWidget().
 {
   // Assure that all edits to the current widget are committed.
   mpBtnWidget->mpBtnRun->setFocus();
   runTask();
 }
virtual bool TaskWidget::runTask () pure virtual
Implemented in CQTrajectoryWidget, CQTSSAWidget, SensitivitiesWidget, SteadyStateWidget, ScanWidget, CQOptimizationWidget, CQEFMWidget, CQOscillationTaskWidget, CQFittingWidget, CQLNAWidget, CQLyapWidget, CQMCAWidget, CQCrossSectionTaskWidget, and CQMoietiesTaskWidget.
Referenced by Worker::finishedLoading(), and runBtnClicked().
bool TaskWidget::saveCommon () protected
Definition at line 258 of file TaskWidget.cpp.
References CCopasiTask::isScheduled(), CCopasiTask::isUpdateModel(), mChanged, mpHeaderWidget, mpTask, CQTaskHeaderWidget::saved(), CCopasiTask::setScheduled(), and CCopasiTask::setUpdateModel().
Referenced by CQMoietiesTaskWidget::saveTask(), CQEFMWidget::saveTask(), CQCrossSectionTaskWidget::saveTask(), CQLyapWidget::saveTask(), CQLNAWidget::saveTask(), CQMCAWidget::saveTask(), ScanWidget::saveTask(), SensitivitiesWidget::saveTask(), SteadyStateWidget::saveTask(), CQFittingWidget::saveTask(), CQTSSAWidget::saveTask(), CQOptimizationWidget::saveTask(), and CQTrajectoryWidget::saveTask().
 {
   if (!mpTask) return false;
   bool Value = mpHeaderWidget->mpBoxExecutable->isChecked();
   if (mpTask->isScheduled() != Value)
     {
       mpTask->setScheduled(Value);
       mChanged = true;
     }
   Value = mpHeaderWidget->mpUpdateModel->isChecked();
   if (mpTask->isUpdateModel() != Value)
     {
       mpTask->setUpdateModel(Value);
       mChanged = true;
     }
   mpHeaderWidget->saved();
   return true;
 }
bool TaskWidget::saveMethod () protected
Definition at line 308 of file TaskWidget.cpp.
References mChanged, mpMethodWidget, mpTask, and CQTaskMethodWidget::saveMethod().
Referenced by CQCrossSectionTaskWidget::saveTask(), CQEFMWidget::saveTask(), CQLyapWidget::saveTask(), SensitivitiesWidget::saveTask(), SteadyStateWidget::saveTask(), CQFittingWidget::saveTask(), CQTSSAWidget::saveTask(), CQOptimizationWidget::saveTask(), and CQTrajectoryWidget::saveTask().
 {
   if (!mpTask) return false;
   mChanged &= mpMethodWidget->saveMethod();
   return true;
 }
virtual bool TaskWidget::saveTask () protected pure virtual
Implemented in CQTrajectoryWidget, CQOptimizationWidget, CQTSSAWidget, CQFittingWidget, SteadyStateWidget, SensitivitiesWidget, ScanWidget, CQLNAWidget, CQMCAWidget, CQLyapWidget, CQOscillationTaskWidget, CQCrossSectionTaskWidget, CQEFMWidget, and CQMoietiesTaskWidget.
Referenced by assistantBtnClicked(), commonBeforeRunTask(), and leave().
void TaskWidget::slotFinishThread () slot
Definition at line 455 of file TaskWidget.cpp.
References CCopasiMessage::COMMANDLINE, CQMessageBox::critical(), finishTask(), CCopasiMessage::getAllMessageText(), CCopasiMessage::getHighestSeverity(), CQMessageBox::information(), mpTaskThread, CCopasiMessage::size(), and CQTaskThread::success().
Referenced by TaskWidget().
 {
   if (!mpTaskThread->success() &&
       CCopasiMessage::size() != 0)
     {
       CQMessageBox::critical(this, "Calculation Error",
                              CCopasiMessage::getAllMessageText().c_str(),
                              QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
     }
   else if (CCopasiMessage::getHighestSeverity() > CCopasiMessage::COMMANDLINE)
     {
       CQMessageBox::information(this, "Calculation Warning",
                                 CCopasiMessage::getAllMessageText().c_str(),
                                 QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
     }
   finishTask();
 }
bool TaskWidget::taskFinishedEvent () protected virtual
Reimplemented in CQTrajectoryWidget, CQFittingWidget, CQTSSAWidget, SteadyStateWidget, SensitivitiesWidget, CQLNAWidget, CQMCAWidget, CQLyapWidget, CQCrossSectionTaskWidget, CQEFMWidget, and CQMoietiesTaskWidget.
Definition at line 508 of file TaskWidget.cpp.
Referenced by finishTask(), and CQFittingWidget::taskFinishedEvent().
 {
   return true;
 }
bool TaskWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Reimplemented in CQTrajectoryWidget, CQOscillationTaskWidget, and CQCrossSectionTaskWidget.
Definition at line 519 of file TaskWidget.cpp.
References ListViews::ADD, CQTaskMethodWidget::clearHistory(), CopasiWidget::mIgnoreUpdates, ListViews::MODEL, and mpMethodWidget.
 {
   if (mIgnoreUpdates) return true;
   switch (objectType)
     {
       case ListViews::MODEL:
         if (action == ListViews::ADD &&
             mpMethodWidget != NULL)
           {
             mpMethodWidget->clearHistory();
           }
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
bool TaskWidget::mChanged protected
Definition at line 133 of file TaskWidget.h.
Referenced by CQLyapWidget::loadTask(), CQMCAWidget::loadTask(), CQLNAWidget::loadTask(), ScanWidget::loadTask(), SensitivitiesWidget::loadTask(), SteadyStateWidget::loadTask(), CQFittingWidget::loadTask(), CQOptimizationWidget::loadTask(), saveCommon(), saveMethod(), CQLNAWidget::saveParameterTable(), CQMCAWidget::saveParameterTable(), CQLyapWidget::saveTask(), CQMCAWidget::saveTask(), CQLNAWidget::saveTask(), ScanWidget::saveTask(), SensitivitiesWidget::saveTask(), SteadyStateWidget::saveTask(), CQFittingWidget::saveTask(), CQTSSAWidget::saveTask(), CQOptimizationWidget::saveTask(), and CQTrajectoryWidget::saveTask().
CQTaskBtnWidget* TaskWidget::mpBtnWidget protected
Definition at line 124 of file TaskWidget.h.
Referenced by CQEFMWidget::CQEFMWidget(), CQMoietiesTaskWidget::init(), CQCrossSectionTaskWidget::init(), CQLyapWidget::init(), CQOscillationTaskWidget::init(), CQLNAWidget::init(), CQMCAWidget::init(), SensitivitiesWidget::init(), SteadyStateWidget::init(), CQFittingWidget::init(), CQOptimizationWidget::init(), CQTSSAWidget::init(), CQTrajectoryWidget::init(), runBtnClicked(), ScanWidget::ScanWidget(), CQOptimizationWidget::slotExpressionValid(), and TaskWidget().
CQTaskHeaderWidget* TaskWidget::mpHeaderWidget protected
Definition at line 122 of file TaskWidget.h.
Referenced by CQEFMWidget::CQEFMWidget(), CQMoietiesTaskWidget::init(), CQCrossSectionTaskWidget::init(), CQOscillationTaskWidget::init(), CQLyapWidget::init(), CQLNAWidget::init(), CQMCAWidget::init(), SensitivitiesWidget::init(), SteadyStateWidget::init(), CQFittingWidget::init(), CQOptimizationWidget::init(), CQTSSAWidget::init(), CQTrajectoryWidget::init(), loadCommon(), saveCommon(), ScanWidget::ScanWidget(), and TaskWidget().
CCopasiMethod* TaskWidget::mpMethod protected
Definition at line 131 of file TaskWidget.h.
Referenced by enterProtected(), CQMCAWidget::loadParameterTable(), CQLNAWidget::loadParameterTable(), revertBtnClicked(), CQMCAWidget::saveParameterTable(), CQLNAWidget::saveParameterTable(), and SteadyStateWidget::taskFinishedEvent().
QGridLayout* TaskWidget::mpMethodLayout protected
Definition at line 125 of file TaskWidget.h.
CQTaskMethodWidget* TaskWidget::mpMethodWidget protected
Definition at line 123 of file TaskWidget.h.
Referenced by CQCrossSectionTaskWidget::init(), CQLyapWidget::init(), CQLNAWidget::init(), CQMCAWidget::init(), SensitivitiesWidget::init(), SteadyStateWidget::init(), CQFittingWidget::init(), CQOptimizationWidget::init(), CQTSSAWidget::init(), CQTrajectoryWidget::init(), loadMethod(), CQLNAWidget::loadParameterTable(), CQMCAWidget::loadParameterTable(), saveMethod(), CQLNAWidget::saveParameterTable(), CQMCAWidget::saveParameterTable(), TaskWidget(), and update().
CProgressBar* TaskWidget::mProgressBar protected
Definition at line 121 of file TaskWidget.h.
Referenced by commonAfterRunTask(), commonBeforeRunTask(), commonRunTask(), and finishTask().
QSpacerItem* TaskWidget::mpSpacer1 protected
Definition at line 127 of file TaskWidget.h.
QSpacerItem* TaskWidget::mpSpacer2 protected
Definition at line 128 of file TaskWidget.h.
CCopasiTask* TaskWidget::mpTask protected
Definition at line 130 of file TaskWidget.h.
Referenced by assistantBtnClicked(), commonAfterRunTask(), commonBeforeRunTask(), commonRunTask(), CQEFMWidget::createMethod(), enterProtected(), finishTask(), getTask(), loadCommon(), loadMethod(), CQMoietiesTaskWidget::loadTask(), CQCrossSectionTaskWidget::loadTask(), CQEFMWidget::loadTask(), CQLyapWidget::loadTask(), CQLNAWidget::loadTask(), CQMCAWidget::loadTask(), CQFittingWidget::loadTask(), CQTSSAWidget::loadTask(), CQOptimizationWidget::loadTask(), CQTrajectoryWidget::loadTask(), reportBtnClicked(), revertBtnClicked(), CQMoietiesTaskWidget::runTask(), CQEFMWidget::runTask(), saveCommon(), saveMethod(), CQMoietiesTaskWidget::saveTask(), CQEFMWidget::saveTask(), CQCrossSectionTaskWidget::saveTask(), CQLyapWidget::saveTask(), CQMCAWidget::saveTask(), CQLNAWidget::saveTask(), CQFittingWidget::saveTask(), CQTSSAWidget::saveTask(), CQOptimizationWidget::saveTask(), CQTrajectoryWidget::saveTask(), CQCrossSectionTaskWidget::taskFinishedEvent(), CQEFMWidget::taskFinishedEvent(), and CQTrajectoryWidget::taskFinishedEvent().
CQTaskThread* TaskWidget::mpTaskThread protected
Definition at line 134 of file TaskWidget.h.
Referenced by commonRunTask(), slotFinishThread(), TaskWidget(), and ~TaskWidget().
The documentation for this class was generated from the following files:
TaskWidget.h
TaskWidget.cpp