COPASI API: CQParameterSetsWidget Class Reference
CQParameterSetsWidget Class Reference
#include <CQParameterSetsWidget.h>
Public Member Functions
CQParameterSetsWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQParameterSetsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
virtual void keyPressEvent (QKeyEvent *ev)
Private Member Functions
void deleteSelected ()
void updateDeleteBtns ()
Private Attributes
CQParameterSetsDM * mpParameterSetsDM
CQSortFilterProxyModel * mpProxyModel
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 16 of file CQParameterSetsWidget.h.
Constructor & Destructor Documentation
CQParameterSetsWidget::CQParameterSetsWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 26 of file CQParameterSetsWidget.cpp.
References COL_ROW_NUMBER, dataChanged(), CopasiWidget::mFramework, mpParameterSetsDM, mpProxyModel, CopasiWidget::protectedNotify(), setFramework(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpParameterSetsDM = new CQParameterSetsDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpTblParameterSets->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblParameterSets->verticalHeader()->hide();
   mpTblParameterSets->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   setFramework(mFramework);
   // Connect the table widget
   connect(mpParameterSetsDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpParameterSetsDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
 }
CQParameterSetsWidget::~CQParameterSetsWidget ()
Definition at line 57 of file CQParameterSetsWidget.cpp.
References mpParameterSetsDM, mpProxyModel, and pdelete.
 {
   pdelete(mpProxyModel);
   pdelete(mpParameterSetsDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQParameterSetsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 202 of file CQParameterSetsWidget.cpp.
References CopasiWidget::mFramework, setFramework(), and updateDeleteBtns().
Referenced by CQParameterSetsWidget().
 {
   mpTblParameterSets->resizeColumnsToContents();
   setFramework(mFramework);
   updateDeleteBtns();
 }
void CQParameterSetsWidget::deleteSelected () private
Definition at line 78 of file CQParameterSetsWidget.cpp.
References mpParameterSetsDM, mpProxyModel, CQParameterSetsDM::removeRows(), and CQParameterSetsDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblParameterSets->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpParameterSetsDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpParameterSetsDM->removeRows(mappedSelRows);
 }
bool CQParameterSetsWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 137 of file CQParameterSetsWidget.cpp.
References CopasiWidget::mFramework, CopasiWidget::mpObject, mpParameterSetsDM, mpProxyModel, setFramework(), CQParameterSetsDM::setListOfModelParameterSets(), slotSelectionChanged(), and updateDeleteBtns().
 {
   if (mpObject == NULL)
     {
       return false;
     }
   if (mpTblParameterSets->selectionModel() != NULL)
     {
       disconnect(mpTblParameterSets->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpParameterSetsDM->setListOfModelParameterSets(&static_cast< CModel * >(mpObject)->getModelParameterSets());
   mpProxyModel->setSourceModel(mpParameterSetsDM);
   //Set Model for the TableView
   mpTblParameterSets->setModel(NULL);
   mpTblParameterSets->setModel(mpProxyModel);
   connect(mpTblParameterSets->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblParameterSets->resizeColumnsToContents();
   setFramework(mFramework);
   mpBtnNew->hide();
   return true;
 }
void CQParameterSetsWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 233 of file CQParameterSetsWidget.cpp.
References CQParameterSetsDM::columnCount(), mpParameterSetsDM, mpProxyModel, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C && (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblParameterSets->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpParameterSetsDM->columnCount(); ++x)
             {
               if (!mpTblParameterSets->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpParameterSetsDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQParameterSetsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 132 of file CQParameterSetsWidget.cpp.
 {
   return true;
 }
void CQParameterSetsWidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 273 of file CQParameterSetsWidget.cpp.
References CopasiWidget::setFramework().
Referenced by CQParameterSetsWidget(), dataChanged(), and enterProtected().
 {
   CopasiWidget::setFramework(framework);
 }
void CQParameterSetsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 99 of file CQParameterSetsWidget.cpp.
References CQParameterSetsDM::clear(), mpParameterSetsDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Reports?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpParameterSetsDM->clear();
     }
   updateDeleteBtns();
 }
void CQParameterSetsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 70 of file CQParameterSetsWidget.cpp.
References deleteSelected(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblParameterSets->hasFocus())
     {deleteSelected();}
   updateDeleteBtns();
 }
void CQParameterSetsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 64 of file CQParameterSetsWidget.cpp.
References CQBaseDataModel::insertRow(), mpParameterSetsDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpParameterSetsDM->insertRow();
   updateDeleteBtns();
 }
void CQParameterSetsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 210 of file CQParameterSetsWidget.cpp.
References C_INVALID_INDEX, CModel::getKey(), CCopasiRootContainer::getKeyFactory(), CQParameterSetsDM::isDefaultRow(), CopasiWidget::mpListView, CopasiWidget::mpObject, mpParameterSetsDM, mpProxyModel, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpParameterSetsDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   if (mpObject == NULL)
     {
       return;
     }
   std::string key = static_cast< CModel * >(mpObject)->getModelParameterSets()[index.row()]->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQParameterSetsWidget::slotFilterChanged () protected virtual slot
Definition at line 267 of file CQParameterSetsWidget.cpp.
References mpProxyModel.
Referenced by CQParameterSetsWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Report", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQParameterSetsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 196 of file CQParameterSetsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQParameterSetsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 113 of file CQParameterSetsWidget.cpp.
References ListViews::ADD, ListViews::DELETE, CopasiWidget::mIgnoreUpdates, CopasiWidget::mKey, ListViews::MODEL, CopasiWidget::mpDataModel, and CopasiWidget::mpObject.
 {
   if (mIgnoreUpdates)
     {
       return true;
     }
   if (objectType == ListViews::MODEL &&
       (action == ListViews::DELETE ||
        action == ListViews::ADD))
     {
       mpDataModel = NULL;
       mpObject = NULL;
       mKey = "";
     }
   return true;
 }
void CQParameterSetsWidget::updateDeleteBtns () private
Definition at line 167 of file CQParameterSetsWidget.cpp.
References CQParameterSetsDM::isDefaultRow(), mpParameterSetsDM, and mpProxyModel.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblParameterSets->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpParameterSetsDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
CQParameterSetsDM* CQParameterSetsWidget::mpParameterSetsDM private
Definition at line 29 of file CQParameterSetsWidget.h.
Referenced by CQParameterSetsWidget(), deleteSelected(), enterProtected(), keyPressEvent(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQParameterSetsWidget().
CQSortFilterProxyModel* CQParameterSetsWidget::mpProxyModel private
Definition at line 30 of file CQParameterSetsWidget.h.
Referenced by CQParameterSetsWidget(), deleteSelected(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQParameterSetsWidget().
The documentation for this class was generated from the following files:
CQParameterSetsWidget.h
CQParameterSetsWidget.cpp