COPASI API: CQMatrixDialog Class Reference
CQMatrixDialog Class Reference
#include <CQMatrixDialog.h>
Public Slots
virtual void setArray (const CArrayAnnotation *tmp, bool single)
Public Member Functions
CQMatrixDialog (QWidget *parent=0, const char *name=0, bool modal=false, Qt::WindowFlags fl=0)
~CQMatrixDialog ()
Detailed Description
Definition at line 22 of file CQMatrixDialog.h.
Constructor & Destructor Documentation
CQMatrixDialog::CQMatrixDialog (QWidget * parent = 0, const char * name = 0, bool modal = false, Qt::WindowFlags fl = 0)
Definition at line 27 of file CQMatrixDialog.cpp.
     : QDialog(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   setupUi(this);
 }
CQMatrixDialog::~CQMatrixDialog ()
Definition at line 39 of file CQMatrixDialog.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQMatrixDialog::setArray (const CArrayAnnotation * tmp, bool single) virtual slot
Definition at line 44 of file CQMatrixDialog.cpp.
References CArrayAnnotation::dimensionality(), FROM_UTF8, CArrayAnnotation::getAnnotationsString(), CArrayAnnotation::getDimensionDescription(), CCopasiObject::getObjectName(), and CArrayAnnotation::size().
Referenced by CCopasiSelectionDialog::chooseCellMatrix().
 {
   size_t i;
   mpLabelRow->setText("Rows : " + FROM_UTF8(tmp->getDimensionDescription(0)));
   size_t nRows = tmp->size()[0];
   if (!single)
     mpCBRow->insertItem(mpCBRow->count(), "ALL");
   if (FROM_UTF8(tmp->getObjectName()).contains("Eigenvalues"))
     {
       for (i = 0; i < nRows; i++)
         mpCBRow->insertItem(mpCBRow->count(), QString::number(i + 1));
     }
   else
     {
       for (i = 0; i < nRows; i++)
         mpCBRow->insertItem(mpCBRow->count(), FROM_UTF8(tmp->getAnnotationsString(0, true)[i]));
     }
   mpLabelColumn->hide();
   mpCBColumn->hide();
   mpLabelDim3->hide();
   mpCBDim3->hide();
   if (tmp->dimensionality() > 1)
     {
       mpLabelColumn->show();
       mpCBColumn->show();
       mpLabelColumn->setText("Columns : " + FROM_UTF8(tmp->getDimensionDescription(1)));
       size_t nCols = tmp->size()[1];
       if (!single)
         mpCBColumn->insertItem(mpCBColumn->count(), "ALL");
       if (FROM_UTF8(tmp->getObjectName()).contains("Eigenvalues"))
         {
           mpCBColumn->insertItem(mpCBColumn->count(), "Real part");
           mpCBColumn->insertItem(mpCBColumn->count(), "Imaginary part");
         }
       else
         {
           for (i = 0; i < nCols; i++)
             mpCBColumn->insertItem(mpCBColumn->count(), FROM_UTF8(tmp->getAnnotationsString(1, true)[i]));
         }
       if (tmp->dimensionality() == 3)
         {
           mpLabelDim3->show();
           mpCBDim3->show();
           mpLabelDim3->setText("Dimension : " + FROM_UTF8(tmp->getDimensionDescription(2)));
           size_t nDims = tmp->size()[2];
           if (!single)
             mpCBDim3->insertItem(mpCBDim3->count(), "ALL");
           for (i = 0; i < nDims; i++)
             mpCBDim3->insertItem(mpCBDim3->count(), FROM_UTF8(tmp->getAnnotationsString(2, true)[i]));
         }
     }
 }
The documentation for this class was generated from the following files:
CQMatrixDialog.h
CQMatrixDialog.cpp