COPASI API: CReaction Class Reference
CReaction Class Reference
#include <CReaction.h>
Public Member Functions
bool addModifier (const std::string &metabKey, const C_FLOAT64 &multiplicity=1.0)
void addParameterMapping (const size_t &index, const std::string &key)
void addParameterMapping (const std::string &parameterName, const std::string &key)
bool addProduct (const std::string &metabKey, const C_FLOAT64 &multiplicity=1.0)
bool addSubstrate (const std::string &metabKey, const C_FLOAT64 &multiplicity=1.0)
const C_FLOAT64 & calculateFlux ()
C_FLOAT64 calculatePartialDerivative (C_FLOAT64 *pXi, const C_FLOAT64 &derivationFactor, const C_FLOAT64 &resolution)
const C_FLOAT64 & calculateParticleFlux ()
void cleanup ()
void clearParameterMapping (const std::string &parameterName)
void clearParameterMapping (const size_t &index)
void compile ()
CReaction (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CReaction (const CReaction &src, const CCopasiContainer *pParent=NULL)
const CCallParameters
< C_FLOAT64 > & getCallParameters () const
const CChemEq & getChemEq () const
CChemEq & getChemEq ()
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
size_t getCompartmentNumber () const
virtual std::set< const
CCopasiObject * > getDeletedObjects () const
CEvaluationNode * getExpressionTree ()
const C_FLOAT64 & getFlux () const
CCopasiObject * getFluxReference ()
const CCopasiObject * getFluxReference () const
const CFunction * getFunction () const
const CFunctionParameters & getFunctionParameters () const
virtual const std::string & getKey () const
const CCompartment * getLargestCompartment () const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
size_t getParameterIndex (const std::string &parameterName, CFunctionParameter::DataType *pType=NULL) const
const std::vector< std::string > & getParameterMapping (const size_t &index) const
const std::vector< std::string > & getParameterMapping (const std::string &parameterName) const
const std::vector< std::vector
< std::string > > & getParameterMappings () const
std::vector< std::vector
< std::string > > & getParameterMappings ()
const CCopasiParameterGroup & getParameters () const
CCopasiParameterGroup & getParameters ()
const C_FLOAT64 & getParameterValue (const std::string &parameterName) const
const C_FLOAT64 & getParticleFlux () const
CCopasiObject * getParticleFluxReference ()
const CCopasiObject * getParticleFluxReference () const
CCopasiObject * getPropensityReference ()
const CCopasiObject * getPropensityReference () const
const std::string & getSBMLId () const
const bool & isFast () const
bool isLocalParameter (const size_t &index) const
bool isLocalParameter (const std::string &parameterName) const
bool isReversible () const
C_INT32 load (CReadConfig &configbuffer)
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void printDebug () const
void setFast (const bool &fast)
bool setFunction (const std::string &functionName)
bool setFunction (CFunction *pFunction)
CFunction * setFunctionFromExpressionTree (const CExpression &tree, std::map< CCopasiObject *, SBase * > &copasi2sbmlmap, CFunctionDB *pFunctionDB)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setParameterMapping (const size_t &index, const std::string &key)
bool setParameterMapping (const std::string &parameterName, const std::string &key)
void setParameterMappingVector (const std::string &parameterName, const std::vector< std::string > &keys)
void setParameterValue (const std::string &parameterName, const C_FLOAT64 &value, const bool &updateStatus=true)
void setReversible (bool reversible)
void setSBMLId (const std::string &id)
virtual ~CReaction ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Private Member Functions
void calculate ()
std::string escapeId (const std::string &id)
void initializeMetaboliteKeyMap ()
void initializeParameters ()
void initObjects ()
C_INT32 loadOld (CReadConfig &configbuffer)
bool loadOneRole (CReadConfig &configbuffer, CFunctionParameter::Role role, C_INT32 n, const std::string &prefix)
CEvaluationNodeVariable * object2variable (const CEvaluationNodeObject *objectNode, std::map< std::string, std::pair< CCopasiObject *, CFunctionParameter * > > &replacementMap, std::map< CCopasiObject *, SBase * > &copasi2sbmlmap)
CEvaluationNode * objects2variables (const CEvaluationNode *expression, std::map< std::string, std::pair< CCopasiObject *, CFunctionParameter * > > &replacementMap, std::map< CCopasiObject *, SBase * > &copasi2sbmlmap)
CReaction & operator= (const CReaction &)
void setScalingFactor ()
CEvaluationNodeObject * variable2object (CEvaluationNodeVariable *pVariableNode)
CEvaluationNode * variables2objects (CEvaluationNode *expression)
Private Attributes
CChemEq mChemEq
bool mFast
C_FLOAT64 mFlux
CFunctionParameterMap mMap
std::vector< std::vector
< std::string > > mMetabKeyMap
CCopasiParameterGroup mParameters
C_FLOAT64 mParticleFlux
CCopasiObjectReference
< C_FLOAT64 > * mpFluxReference
CFunction * mpFunction
CCopasiObjectReference
< C_FLOAT64 > * mpParticleFluxReference
CCopasiObjectReference
< C_FLOAT64 > * mpPropensityReference
C_FLOAT64 mPropensity
std::string mSBMLId
const C_FLOAT64 * mScalingFactor
const C_FLOAT64 * mUnitScalingFactor
Static Private Attributes
static C_FLOAT64 mDefaultScalingFactor = 1.0
Friends
std::ostream & operator<< (std::ostream &os, const CReaction &d)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 44 of file CReaction.h.
Constructor & Destructor Documentation
CReaction::CReaction (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 51 of file CReaction.cpp.
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectType(), CCopasiRootContainer::getUndefinedFunction(), initObjects(), CAnnotation::mKey, and setFunction().
                                                       :
   CCopasiContainer(name, pParent, "Reaction"),
   CAnnotation(),
   mChemEq("Chemical Equation", this),
   mpFunction(NULL),
   mFlux(0),
   mpFluxReference(NULL),
   mParticleFlux(0),
   mpParticleFluxReference(NULL),
   mPropensity(0),
   mpPropensityReference(NULL),
   mScalingFactor(&mDefaultScalingFactor),
   mUnitScalingFactor(&mDefaultScalingFactor),
   mMetabKeyMap(),
   mParameters("Parameters", this),
   mFast(false)
 {
   mKey = CCopasiRootContainer::getKeyFactory()->add(getObjectType(), this);
   CONSTRUCTOR_TRACE;
   initObjects();
   setFunction(CCopasiRootContainer::getUndefinedFunction());
 }
CReaction::CReaction (const CReaction & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CReaction & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 76 of file CReaction.cpp.
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CCopasiObject::getObjectType(), initObjects(), CAnnotation::mKey, mpFunction, and CAnnotation::setMiriamAnnotation().
                                                       :
   CCopasiContainer(src, pParent),
   CAnnotation(src),
   mChemEq(src.mChemEq, this),
   mpFunction(src.mpFunction),
   mFlux(src.mFlux),
   mpFluxReference(NULL),
   mParticleFlux(src.mParticleFlux),
   mpParticleFluxReference(NULL),
   mPropensity(src.mPropensity),
   mpPropensityReference(NULL),
   mScalingFactor(src.mScalingFactor),
   mUnitScalingFactor(src.mUnitScalingFactor),
   mMap(src.mMap),
   mMetabKeyMap(src.mMetabKeyMap),
   mParameters(src.mParameters, this),
   mFast(src.mFast)
 {
   mKey = CCopasiRootContainer::getKeyFactory()->add(getObjectType(), this);
   CONSTRUCTOR_TRACE;
   initObjects();
   if (mpFunction)
     {
       //compileParameters();
     }
   setMiriamAnnotation(src.getMiriamAnnotation(), mKey, src.mKey);
 }
CReaction::~CReaction () virtual
Destructor
Definition at line 108 of file CReaction.cpp.
References cleanup(), DESTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), CAnnotation::mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
   cleanup();
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
bool CReaction::addModifier (const std::string & metabKey, const C_FLOAT64 & multiplicity = 1.0)
Add a modifier to the reaction
Parameters
std::string & metabKey
const C_FLOAT64 & multiplicity (Default 1.0)
Returns
bool success
Definition at line 240 of file CReaction.cpp.
References CChemEq::addMetabolite(), mChemEq, and CChemEq::MODIFIER.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::duplicateReaction(), and CCopasiXMLParser::ModifierElement::start().
 {return mChemEq.addMetabolite(metabKey, multiplicity, CChemEq::MODIFIER);}
void CReaction::addParameterMapping (const size_t & index, const std::string & key)
Add a parameter mapping for the indexed parameter.
Parameters
const size_t & index
const std::string & key
Definition at line 348 of file CReaction.cpp.
References fatalError, getFunctionParameters(), mMetabKeyMap, mpFunction, and CFunctionParameter::VFLOAT64.
Referenced by CModelAdd::addReactions(), CModelExpansion::createDiffusionReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), loadOneRole(), and CReactionInterface::writeBackToReaction().
 {
   if (!mpFunction) fatalError();
   if (getFunctionParameters()[index]->getType() != CFunctionParameter::VFLOAT64) fatalError(); //wrong data type
   mMetabKeyMap[index].push_back(key);
 }
void CReaction::addParameterMapping (const std::string & parameterName, const std::string & key)
Add a parameter mapping for the named parameter.
Parameters
const std::string & parameterName
const std::string & key
Definition at line 374 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, getParameterIndex(), mMetabKeyMap, mpFunction, and CFunctionParameter::VFLOAT64.
 {
   if (!mpFunction) fatalError();
   CFunctionParameter::DataType type;
   size_t index;
   index = getParameterIndex(parameterName, &type);
   if (C_INVALID_INDEX == index)
     return;
   if (type != CFunctionParameter::VFLOAT64) fatalError();
   mMetabKeyMap[index].push_back(key);
 }
bool CReaction::addProduct (const std::string & metabKey, const C_FLOAT64 & multiplicity = 1.0)
Add a product to the reaction
Parameters
std::string & metabKey
const C_FLOAT64 & multiplicity (Default 1.0)
Returns
bool success
Definition at line 236 of file CReaction.cpp.
References CChemEq::addMetabolite(), mChemEq, and CChemEq::PRODUCT.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::ProductElement::start(), test000058::test_bug1025_1(), test000058::test_bug1025_6(), test000059::test_unique_id_10(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_4(), test000059::test_unique_id_7(), and test000059::test_unique_id_9().
 {return mChemEq.addMetabolite(metabKey, multiplicity, CChemEq::PRODUCT);}
bool CReaction::addSubstrate (const std::string & metabKey, const C_FLOAT64 & multiplicity = 1.0)
Add a substrate to the reaction
Parameters
std::string & metabKey
const C_FLOAT64 & multiplicity (Default 1.0)
Returns
bool success
Definition at line 232 of file CReaction.cpp.
References CChemEq::addMetabolite(), mChemEq, and CChemEq::SUBSTRATE.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), and CCopasiXMLParser::SubstrateElement::start().
 {return mChemEq.addMetabolite(metabKey, multiplicity, CChemEq::SUBSTRATE);}
void CReaction::calculate (void) private
Calculate the kinetic function
Definition at line 840 of file CReaction.cpp.
References CFunction::calcValue(), CFunctionParameterMap::getPointers(), mFlux, mMap, mParticleFlux, mpFunction, mScalingFactor, and mUnitScalingFactor.
Referenced by calculateFlux(), calculateParticleFlux(), compile(), and initObjects().
 {
   mFlux = *mScalingFactor * mpFunction->calcValue(mMap.getPointers());
   mParticleFlux = *mUnitScalingFactor * mFlux;
   return;
 }
const C_FLOAT64 & CReaction::calculateFlux ()
Calculate the kinetic function and returns the flux
Returns
const C_FLOAT64 & Flux
Definition at line 826 of file CReaction.cpp.
References calculate(), and mFlux.
 {
   calculate();
   return mFlux;
 }
C_FLOAT64 CReaction::calculatePartialDerivative (C_FLOAT64 * pXi, const C_FLOAT64 & derivationFactor, const C_FLOAT64 & resolution)
Calculate partial derivative of the flux
Parameters
C_FLOAT64 * pXi
const C_FLOAT64 & derivationFactor
const C_FLOAT64 & resolution (unscaled resolution)
Returns
C_FLOAT64 partial
Definition at line 847 of file CReaction.cpp.
References C_FLOAT64, CFunction::calcValue(), CFunction::dependsOn(), CFunctionParameterMap::getPointers(), mMap, mpFunction, and mScalingFactor.
 {
   if (mpFunction->dependsOn(pXi, mMap.getPointers()))
     {
       C_FLOAT64 store = *pXi;
       C_FLOAT64 f1, f2;
       C_FLOAT64 tmp =
         (store < resolution) ? resolution * (1.0 + derivationFactor) : store; //TODO: why assymmetric?
       *pXi = tmp * (1.0 + derivationFactor);
       f1 = mpFunction->calcValue(mMap.getPointers());
       *pXi = tmp * (1.0 - derivationFactor);
       f2 = mpFunction->calcValue(mMap.getPointers());
       *pXi = store;
       return *mScalingFactor * (f1 - f2) / (2.0 * tmp * derivationFactor);
       //this is d(flow)/d(concentration)
     }
   else
     return 0.0;
 }
const C_FLOAT64 & CReaction::calculateParticleFlux ()
Calculates the kinetic function and returns the particle flux
Returns
const C_FLOAT64 & ParticleFlux
Definition at line 832 of file CReaction.cpp.
References calculate(), CCopasiRootContainer::getUndefinedFunction(), mParticleFlux, and mpFunction.
 {
   if (mpFunction != CCopasiRootContainer::getUndefinedFunction())
     calculate();
   return mParticleFlux;
 }
void CReaction::cleanup ()
Delete
Definition at line 135 of file CReaction.cpp.
Referenced by ~CReaction().
 {
   // TODO: mMap.cleanup();
   //mParameterDescription.cleanup();
 }
void CReaction::clearParameterMapping (const std::string & parameterName)
Clear the parameter mapping for the named parameter.
Parameters
const size_t & index
Definition at line 407 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, getParameterIndex(), mMetabKeyMap, mpFunction, and CFunctionParameter::VFLOAT64.
Referenced by CModelAdd::addReactions(), CModelExpansion::duplicateReaction(), loadOneRole(), and CReactionInterface::writeBackToReaction().
 {
   if (!mpFunction) fatalError();
   CFunctionParameter::DataType type;
   size_t index;
   index = getParameterIndex(parameterName, &type);
   if (C_INVALID_INDEX == index)
     return;
   if (type != CFunctionParameter::VFLOAT64) fatalError(); //wrong data type
   mMetabKeyMap[index].clear();
 }
void CReaction::clearParameterMapping (const size_t & index)
Clear the parameter mapping for the indexed parameter.
Parameters
const size_t & index
Definition at line 423 of file CReaction.cpp.
References fatalError, getFunctionParameters(), mMetabKeyMap, mpFunction, and CFunctionParameter::VFLOAT64.
 {
   if (!mpFunction) fatalError();
   if (getFunctionParameters()[index]->getType() != CFunctionParameter::VFLOAT64) fatalError();
   mMetabKeyMap[index].clear();
 }
void CReaction::compile ()
Compile the reaction, i.e., links the metabolites and parameters with the rate function. The connection of the reaction and the function parameter mapping to the actual metabolites is established (before compile() the chemical equation and the reaction only hold the names of the metabolites).
Parameters
CCopasiVectorNS < CCompartment > & compartments
Definition at line 583 of file CReaction.cpp.
References CFunctionParameterMap::addCallParameter(), CCopasiObject::addDirectDependency(), CCopasiVector< T >::begin(), calculate(), CFunctionParameterMap::clearCallParameter(), CCopasiObject::clearDirectDependencies(), CCopasiObject::clearRefresh(), CCopasiVector< T >::end(), CFunctionParameterMap::getFunctionParameters(), getFunctionParameters(), CCopasiRootContainer::getKeyFactory(), CChemEq::getModifiers(), CCopasiObject::getObjectName(), CChemEq::getProducts(), CChemEq::getSubstrates(), CCopasiRootContainer::getUndefinedFunction(), CCopasiObject::getValueObject(), mChemEq, mFlux, mMap, mMetabKeyMap, mParticleFlux, mpFluxReference, mpFunction, mpParticleFluxReference, CFunctionParameterMap::pUnmappedObject, CFunctionParameterMap::setCallParameter(), CCopasiObject::setDirectDependencies(), CCopasiObject::setRefresh(), setScalingFactor(), CFunctionParameters::size(), and CFunctionParameter::VINT32.
Referenced by CModel::convert2NonReversible(), and CReactionInterface::writeBackToReaction().
 {
   clearDirectDependencies();
   std::set< const CCopasiObject * > Dependencies;
   CCopasiObject * pObject;
   if (mpFunction)
     {
       if (mpFunction != CCopasiRootContainer::getUndefinedFunction())
         {
           addDirectDependency(mpFunction);
           mpFluxReference->setRefresh(this, &CReaction::calculate);
           mpParticleFluxReference->setRefresh(this, &CReaction::calculate);
         }
       else
         {
           mFlux = 0.0;
           mParticleFlux = 0.0;
           mpFluxReference->clearRefresh();
           mpParticleFluxReference->clearRefresh();
         }
       size_t i, j, jmax;
       size_t imax = mMap.getFunctionParameters().size();
       std::string paramName;
       for (i = 0; i < imax; ++i)
         {
           paramName = getFunctionParameters()[i]->getObjectName();
           if (mMap.getFunctionParameters()[i]->getType() >= CFunctionParameter::VINT32)
             {
               mMap.clearCallParameter(paramName);
               jmax = mMetabKeyMap[i].size();
               for (j = 0; j < jmax; ++j)
                 if ((pObject = CCopasiRootContainer::getKeyFactory()->get(mMetabKeyMap[i][j])) != NULL)
                   {
                     mMap.addCallParameter(paramName, pObject);
                     Dependencies.insert(pObject->getValueObject());
                   }
                 else
                   {
                     mMap.addCallParameter(paramName, CFunctionParameterMap::pUnmappedObject);
                   }
             }
           else if ((pObject = CCopasiRootContainer::getKeyFactory()->get(mMetabKeyMap[i][0])) != NULL)
             {
               mMap.setCallParameter(paramName, pObject);
               Dependencies.insert(pObject->getValueObject());
             }
           else
             {
               mMap.setCallParameter(paramName, CFunctionParameterMap::pUnmappedObject);
             }
         }
     }
   CCopasiVector < CChemEqElement >::const_iterator it = mChemEq.getSubstrates().begin();
   CCopasiVector < CChemEqElement >::const_iterator end = mChemEq.getSubstrates().end();
   for (; it != end; ++it)
     addDirectDependency((*it)->getMetabolite());
   it = mChemEq.getProducts().begin();
   end = mChemEq.getProducts().end();
   for (; it != end; ++it)
     addDirectDependency((*it)->getMetabolite());
   it = mChemEq.getModifiers().begin();
   end = mChemEq.getModifiers().end();
   for (; it != end; ++it)
     addDirectDependency((*it)->getMetabolite());
   mpFluxReference->setDirectDependencies(Dependencies);
   mpParticleFluxReference->setDirectDependencies(Dependencies);
   setScalingFactor();
 }
std::string CReaction::escapeId (const std::string & id) private
Escapes double quotes and backslashes in a string and puts strings with tabs and spaces in double quotes.
Definition at line 1659 of file CReaction.cpp.
Referenced by object2variable().
 {
   std::string s = id;
   std::string::size_type idx = s.find('\\');
   while (idx != std::string::npos)
     {
       s.insert(idx, "\\");
       ++idx;
       idx = s.find('\\', ++idx);
     }
   idx = s.find('"');
   while (idx != std::string::npos)
     {
       s.insert(idx, "\\");
       ++idx;
       idx = s.find('"', ++idx);
     }
   if (s.find(' ') != std::string::npos || s.find('\t') != std::string::npos)
     {
       s = std::string("\"") + s + std::string("\"");
     }
   return s;
 }
const CCallParameters< C_FLOAT64 > & CReaction::getCallParameters () const
Retrieve the call parameter given to the kinetic function.
Returns
const CCallParameters< C_FLOAT64 > & callParameters
Definition at line 216 of file CReaction.cpp.
References CFunctionParameterMap::getPointers(), and mMap.
Referenced by CMathObject::compileFlux().
 {
   return mMap.getPointers();
 }
const CChemEq & CReaction::getChemEq () const
Retrieves the chemical equation of the reaction
Returns
const CChemEq & chemEq
Definition at line 223 of file CReaction.cpp.
References mChemEq.
Referenced by CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), CMathObject::compileFlux(), CMathObject::compilePropensity(), CModel::convert2NonReversible(), ReactionsWidget1::copy(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createKineticLaw(), CSBMLExporter::createReaction(), CLayoutInitializer::createReactionGlyph(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), SBMLImporter::findCorrespondingFunction(), CChemEqInterface::getChemEqString(), CEFMTask::getNetReactionData(), CEFMTask::getSpeciesChanges(), CModelParameter::getUnit(), CReactionInterface::initFromReaction(), CMathReaction::initialize(), CODEExporterC::KineticFunction2ODEmember(), CModelMerging::mergeMetabolites(), object2variable(), CModel::printParameterOverview(), CModelAdd::reactionInvolvesCompartment(), CModelExpansion::replaceInReaction(), CCopasiXML::saveModel(), CChemEqInterface::setChemEqFromString(), SBMLImporter::setCorrectUsage(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), CLLayoutRenderer::update_associations(), CReactionInterface::writeBackToReaction(), and CMMLOutput::writeRHS().
 {return mChemEq;}
CChemEq & CReaction::getChemEq ()
Retrieves the chemical equation of the reaction
Returns
CChemEq & chemEq
Definition at line 226 of file CReaction.cpp.
References mChemEq.
 {return mChemEq;}
std::string CReaction::getChildObjectUnits (const CCopasiObject * pObject) const virtual
Retrieve the units of the child object.
Returns
std::string units
Reimplemented from CCopasiContainer.
Definition at line 116 of file CReaction.cpp.
References CModel::getFrequencyUnitsDisplayString(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectName(), and CModel::getQuantityRateUnitsDisplayString().
 {
   const CModel * pModel =
     dynamic_cast< const CModel * >(getObjectAncestor("Model"));
   if (pModel == NULL) return "";
   const std::string & Name = pObject->getObjectName();
   if (Name == "ParticleFlux")
     return pModel->getFrequencyUnitsDisplayString();
   else if (Name == "Flux")
     return pModel->getQuantityRateUnitsDisplayString();
   else if (Name == "Propensity")
     return pModel->getFrequencyUnitsDisplayString();
   return "";
 }
size_t CReaction::getCompartmentNumber () const
Retrieves the number of compartments the reaction is acting in.
Returns
"size_t" the compartment number
Definition at line 873 of file CReaction.cpp.
References CChemEq::getCompartmentNumber(), and mChemEq.
Referenced by CSBMLExporter::createKineticLaw(), CODEExporter::exportReacParamsAndFuncs(), CModelParameter::getUnit(), CModel::printParameterOverview(), setScalingFactor(), and CMMLOutput::writeRHS().
 {return mChemEq.getCompartmentNumber();}
std::set< const CCopasiObject * > CReaction::getDeletedObjects () const virtual
Retrieve the list of deleted numeric child objects;
Returns
std::set< const CCopasiObject * > deletedObjects
Definition at line 959 of file CReaction.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), isLocalParameter(), mParameters, mpFluxReference, and mpParticleFluxReference.
Referenced by CModel::appendDependentModelObjects(), CModel::removeReaction(), CQReactionDM::removeRows(), and ReactionsWidget1::slotBtnDelete().
 {
   std::set< const CCopasiObject * > Deleted;
   Deleted.insert(this);
   Deleted.insert(mpFluxReference);
   Deleted.insert(mpParticleFluxReference);
   // We need to add all local reaction parameters
   CCopasiParameterGroup::index_iterator it = mParameters.beginIndex();
   CCopasiParameterGroup::index_iterator end = mParameters.endIndex();
   for (; it != end ; ++it)
     {
       if (isLocalParameter((*it)->getObjectName()))
         Deleted.insert((*it)->getValueReference());
     }
   return Deleted;
 }
CEvaluationNode * CReaction::getExpressionTree ()
Converts the function tree into the corresponding expression tree. All variable nodes are replaced by object nodes.
Definition at line 1644 of file CReaction.cpp.
References getFunction(), and variables2objects().
 {
   return this->variables2objects(const_cast<CFunction*>(this->getFunction())->getRoot());
 }
const C_FLOAT64 & CReaction::getFlux () const
Retrieves the flux of the reaction
Returns
const C_FLOAT64 & flux
Definition at line 192 of file CReaction.cpp.
References mFlux.
Referenced by CQReactionDM::data(), operator<<(), and ReactionsWidget1::setFramework().
 {return mFlux;}
CCopasiObject * CReaction::getFluxReference ()
Retrieve object referencing the flux
Returns
CCopasiObject * fluxReference
Definition at line 198 of file CReaction.cpp.
References mpFluxReference.
Referenced by CMathObject::compileParticleFlux(), CModel::convert2NonReversible(), and CMathReaction::initialize().
 {return this->mpFluxReference;}
const CCopasiObject * CReaction::getFluxReference () const
Retrieve const object referencing the flux
Returns
CCopasiObject * fluxReference
Definition at line 195 of file CReaction.cpp.
References mpFluxReference.
 {return this->mpFluxReference;}
const CFunction * CReaction::getFunction () const
Retrieves the rate function of the reaction
Returns
"CBaseFunction &"
Definition at line 252 of file CReaction.cpp.
References mpFunction.
Referenced by CModelAdd::addReactions(), CSBMLExporter::checkForPiecewiseFunctions(), CModelAnalyzer::checkReaction(), CMathObject::compileFlux(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CSBMLExporter::createReaction(), CQReactionDM::data(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::KineticLawElement::end(), CODEExporter::exportKineticFunction(), CODEExporterC::exportKineticFunctionGroup(), CReactionInterface::getDeletedParameters(), getExpressionTree(), CModelParameter::getUnit(), CReactionInterface::initFromReaction(), CODEExporterC::KineticFunction2ODEmember(), stress_test::normalizeAndSimplifyExpressions(), CModel::printParameterOverview(), CCopasiXML::saveModel(), SBMLImporter::setCorrectUsage(), ReactionsWidget1::slotGotoFunction(), variable2object(), and CMMLOutput::writeRHS().
 {return mpFunction;}
const CFunctionParameters & CReaction::getFunctionParameters () const
Gets the description of what parameters the function expects.
Definition at line 576 of file CReaction.cpp.
References fatalError, CFunctionParameterMap::getFunctionParameters(), mMap, and mpFunction.
Referenced by addParameterMapping(), CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), clearParameterMapping(), compile(), CFunctionAnalyzer::constructCallParametersActualValues(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CModelExpansion::duplicateReaction(), CODEExporterC::KineticFunction2ODEmember(), CModelMerging::mergeMetabolites(), CModel::printParameterOverview(), CModelExpansion::replaceInReaction(), CCopasiXML::saveModel(), setParameterMapping(), and setParameterValue().
 {
   if (!mpFunction) fatalError();
   return mMap.getFunctionParameters();
 }
const std::string & CReaction::getKey () const virtual
Retrieves the key of the reaction
Returns
std::string key
Reimplemented from CAnnotation.
Definition at line 190 of file CReaction.cpp.
References CAnnotation::getKey().
Referenced by CLayoutInitializer::createReactionGlyph(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::ReactionElement::end(), CODEExporter::exportKineticFunction(), CODEExporter::exportSingleFunction(), CQSelectionWizardPage::fillTree(), SBMLImporter::importMIRIAM(), CReactionInterface::initFromReaction(), CQReactionDM::insertRows(), CODEExporterBM::KineticFunction2ODEmember(), CODEExporterXPPAUT::KineticFunction2ODEmember(), ReactionsWidget1::loadFromReaction(), CCopasiXML::saveModel(), CQNewMainWindow::selectReaction(), CQReactionDM::setData(), CQReactionDM::setEquation(), CQSpeciesDetail::slotSwitchToReaction(), CCopasiXMLParser::ReactionGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return CAnnotation::getKey();}
const CCompartment * CReaction::getLargestCompartment () const
Retrieve the largest compartment that the reaction touches. This is time dependent it can only be called after update initial values has been called. Note for an empty reaction a NULL pointer is returned.
Returns
const CCompartment * pCompartment
Definition at line 876 of file CReaction.cpp.
References CChemEq::getLargestCompartment(), and mChemEq.
 {return mChemEq.getLargestCompartment();}
const CObjectInterface * CReaction::getObject (const CCopasiObjectName & cn) const virtual
We are hiding local reaction parameter which are covered by global quantities.
Parameters
const CCopasiObjectName & cn
Returns
const CObjectInterface * pObject
Reimplemented from CCopasiContainer.
Definition at line 479 of file CReaction.cpp.
References CCopasiContainer::getObject(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), isLocalParameter(), CCopasiObject::isStaticString(), and mParameters.
Referenced by CQSimpleSelectionTree::populateTree().
 {
   const CCopasiObject * pObject =
     static_cast< const CCopasiObject * >(CCopasiContainer::getObject(cn));
   if (pObject == NULL ||
       pObject->isStaticString()) return pObject;
   const CCopasiContainer * pParent = pObject->getObjectParent();
   while (pParent != this)
     {
       if (pParent->getObjectParent() == &mParameters)
         {
           if (isLocalParameter(pParent->getObjectName()))
             {
               return pObject;
             }
           else
             {
               return NULL;
             }
         }
       pParent = pParent->getObjectParent();
     }
   return pObject;
 }
std::string CReaction::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
Overload display name. Special treatment for reaction to provide a shorter display
Reimplemented from CCopasiObject.
Definition at line 1688 of file CReaction.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDisplayName(), and CCopasiObject::getObjectName().
Referenced by CQSelectionWizardPage::fillTree().
 {
   CModel* tmp = dynamic_cast<CModel*>(this->getObjectAncestor("Model"));
   if (tmp)
     {
       return "(" + getObjectName() + ")";
     }
   return CCopasiObject::getObjectDisplayName(regular, richtext);
 }
size_t CReaction::getParameterIndex (const std::string & parameterName, CFunctionParameter::DataType * pType = NULL) const
Retrieve the index of the given parameter name in the function call. If pType is not NULL the type of the parameter is returned
Parameters
const std::string & parameterName
CFunctionParameter::DataType * pType (default: NULL)
Returns
size_t index;
Retrieve the index of the given parameter name in the function call
Parameters
const std::string & parameterName
Returns
size_t index;
Definition at line 292 of file CReaction.cpp.
References CFunctionParameterMap::findParameterByName(), and mMap.
Referenced by addParameterMapping(), clearParameterMapping(), SBMLImporter::findCorrespondingFunction(), getParameterMapping(), CModelParameter::getUnit(), initializeParameters(), isLocalParameter(), setParameterMapping(), setParameterMappingVector(), and setParameterValue().
 {
   if (pType != NULL)
     {
       return mMap.findParameterByName(parameterName, *pType);
     }
   CFunctionParameter::DataType Type;
   return mMap.findParameterByName(parameterName, Type);
 }
const std::vector< std::string > & CReaction::getParameterMapping (const size_t & index) const
Definition at line 432 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, mMetabKeyMap, and mpFunction.
Referenced by CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), getParameterMapping(), CModelParameter::refreshFromModel(), and ParameterTable::updateTable().
 {
   if (!mpFunction) fatalError();
   if (C_INVALID_INDEX == index || index >= mMetabKeyMap.size())
     return mMetabKeyMap[0]; //TODO this is kind of ugly!
   return mMetabKeyMap[index];
 }
const std::vector< std::string > & CReaction::getParameterMapping (const std::string & parameterName) const
Definition at line 442 of file CReaction.cpp.
References getParameterIndex(), and getParameterMapping().
 {
   size_t index = getParameterIndex(parameterName);
   return getParameterMapping(index);
 }
const std::vector< std::vector<std::string> >& CReaction::getParameterMappings () const inline
Retrieve the mappings of kinetic function parameters.
Definition at line 285 of file CReaction.h.
References mMetabKeyMap.
Referenced by CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), CFunctionAnalyzer::constructCallParametersActualValues(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), CODEExporterC::KineticFunction2ODEmember(), CReactionInterface::loadMappingAndValues(), CModelMerging::mergeMetabolites(), CModel::printParameterOverview(), CModelExpansion::replaceInReaction(), CCopasiXML::saveModel(), and variable2object().
   {return mMetabKeyMap;}
std::vector< std::vector<std::string> >& CReaction::getParameterMappings () inline
Definition at line 288 of file CReaction.h.
References mMetabKeyMap.
   {return mMetabKeyMap;}
const CCopasiParameterGroup & CReaction::getParameters () const
Gets the list of kinetic parameter objects of the reaction/function
Definition at line 333 of file CReaction.cpp.
References mParameters.
Referenced by CModelAnalyzer::checkReaction(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CODEExporter::exportReacParamsAndFuncs(), CODEExporterC::exportTitleData(), CReactionInterface::getDeletedParameters(), CReactionInterface::loadMappingAndValues(), CQSimpleSelectionTree::populateTree(), CCopasiXML::saveModel(), CCopasiXMLParser::ConstantElement::start(), CCopasiXMLParser::ListOfConstantsElement::start(), test000058::test_bug1025_1(), test000058::test_bug1025_6(), test000059::test_unique_id_10(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_4(), test000059::test_unique_id_7(), and test000059::test_unique_id_9().
 {return mParameters;}
CCopasiParameterGroup & CReaction::getParameters ()
Gets the list of kinetic parameter objects of the reaction/function
Definition at line 336 of file CReaction.cpp.
References mParameters.
 {return mParameters;}
const C_FLOAT64 & CReaction::getParameterValue (const std::string & parameterName) const
Retrieves a parameter value
Definition at line 326 of file CReaction.cpp.
References fatalError, CCopasiParameterGroup::getValue(), mParameters, mpFunction, and CCopasiParameter::Value::pDOUBLE.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), and CModelExpansion::duplicateReaction().
 {
   if (!mpFunction) fatalError();
   return * mParameters.getValue(parameterName).pDOUBLE;
 }
const C_FLOAT64 & CReaction::getParticleFlux () const
Retrieves the scaled flux of the reaction
Returns
const C_FLOAT64 & scaledFlux
Definition at line 201 of file CReaction.cpp.
References mParticleFlux.
Referenced by CQReactionDM::data(), operator<<(), and ReactionsWidget1::setFramework().
 {return mParticleFlux;}
CCopasiObject * CReaction::getParticleFluxReference ()
Retrieve object referencing the particle flux
Returns
CCopasiObject * particleFluxReference
Definition at line 207 of file CReaction.cpp.
References mpParticleFluxReference.
Referenced by CMathObject::compilePropensity(), CModel::convert2NonReversible(), CMathReaction::initialize(), and CHybridMethodODE45::setupMetab2React().
 {return mpParticleFluxReference;}
const CCopasiObject * CReaction::getParticleFluxReference () const
Retrieve const object referencing the particle flux
Returns
CCopasiObject * particleFluxReference
Definition at line 204 of file CReaction.cpp.
References mpParticleFluxReference.
 {return mpParticleFluxReference;}
CCopasiObject * CReaction::getPropensityReference ()
Retrieve object referencing the propensity
Returns
CCopasiObject * propensityReference
Definition at line 210 of file CReaction.cpp.
References mpPropensityReference.
Referenced by CMathReaction::initialize().
 {return mpPropensityReference;}
const CCopasiObject * CReaction::getPropensityReference () const
Retrieve object referencing the propensity
Returns
CCopasiObject * propensityReference
Definition at line 213 of file CReaction.cpp.
References mpPropensityReference.
 {return mpPropensityReference;}
const std::string & CReaction::getSBMLId () const
Returns a reference to the SBML Id.
Definition at line 1654 of file CReaction.cpp.
References mSBMLId.
Referenced by SBMLImporter::applyStoichiometricExpressions(), CSBMLExporter::collectIds(), CSBMLExporter::createReaction(), object2variable(), SBMLImporter::replaceObjectNames(), CCopasiXML::saveModel(), and CEvaluationNodeObject::toAST().
 {
   return this->mSBMLId;
 }
void CReaction::initializeMetaboliteKeyMap () private
Initializes the mMetabNameMap vectors to the right size.
Definition at line 558 of file CReaction.cpp.
References fatalError, CFunctionParameterMap::getFunctionParameters(), mMap, mMetabKeyMap, mpFunction, CFunctionParameters::size(), and CFunctionParameter::VINT32.
Referenced by setFunction().
 {
   if (!mpFunction) fatalError();
   size_t i;
   size_t imax = mMap.getFunctionParameters().size();
   mMetabKeyMap.resize(imax);
   for (i = 0; i < imax; ++i)
     {
       if (mMap.getFunctionParameters()[i]->getType() >= CFunctionParameter::VINT32)
         mMetabKeyMap[i].resize(0);
       else
         mMetabKeyMap[i].resize(1);
     }
 }
void CReaction::initializeParameters () private
creates the mParamters List of CParameter objects. mMap needs to be initialized before.
Definition at line 509 of file CReaction.cpp.
References CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::beginIndex(), C_FLOAT64, C_INVALID_INDEX, CCopasiParameter::DOUBLE, CCopasiParameterGroup::endIndex(), fatalError, CFunctionParameterMap::getFunctionParameters(), CCopasiParameter::getKey(), CFunctionParameters::getNumberOfParametersByUsage(), CCopasiObject::getObjectName(), CCopasiParameterGroup::getParameter(), CFunctionParameters::getParameterByUsage(), getParameterIndex(), mMap, mMetabKeyMap, mParameters, mpFunction, CFunctionParameter::PARAMETER, and CCopasiParameterGroup::removeParameter().
Referenced by setFunction().
 {
   if (!mpFunction) fatalError();
   size_t i;
   size_t imax = mMap.getFunctionParameters().getNumberOfParametersByUsage(CFunctionParameter::PARAMETER);
   size_t pos;
   std::string name;
   /* We have to be more intelligent here because during an XML load we have
      already the correct parameters */
   /* Add missing parameters with default value 1.0. */
   for (i = 0, pos = 0; i < imax; ++i)
     {
       name = mMap.getFunctionParameters().getParameterByUsage(CFunctionParameter::PARAMETER, pos)->getObjectName();
       //      param.setName(name);
       if (!mParameters.getParameter(name))
         {
           mParameters.addParameter(name,
                                    CCopasiParameter::DOUBLE,
                                    (C_FLOAT64) 1.0);
         }
       CCopasiParameter * tmpPar = mParameters.getParameter(name);
       mMetabKeyMap[pos - 1][0] = tmpPar->getKey();
     }
   /* Remove parameters not fitting current function */
   CCopasiParameterGroup::index_iterator it = mParameters.beginIndex();
   CCopasiParameterGroup::index_iterator end = mParameters.endIndex();
   std::vector< std::string > ToBeDeleted;
   for (; it != end; ++it)
     {
       name = (*it)->getObjectName();
       if (getParameterIndex(name) == C_INVALID_INDEX)
         ToBeDeleted.push_back(name);
     }
   std::vector< std::string >::const_iterator itToBeDeleted = ToBeDeleted.begin();
   std::vector< std::string >::const_iterator endToBeDeleted = ToBeDeleted.end();
   for (; itToBeDeleted != endToBeDeleted; ++itToBeDeleted)
     mParameters.removeParameter(*itToBeDeleted);
 }
void CReaction::initObjects () private
Definition at line 945 of file CReaction.cpp.
References CCopasiContainer::addObjectReference(), calculate(), mFlux, mParticleFlux, mpFluxReference, mpParticleFluxReference, mpPropensityReference, mPropensity, CCopasiObject::setRefresh(), and CCopasiObject::ValueDbl.
Referenced by CReaction().
 {
   mpFluxReference =
     static_cast<CCopasiObjectReference<C_FLOAT64> *>(addObjectReference("Flux", mFlux, CCopasiObject::ValueDbl));
   mpFluxReference->setRefresh(this, &CReaction::calculate);
   mpParticleFluxReference =
     static_cast<CCopasiObjectReference<C_FLOAT64> *>(addObjectReference("ParticleFlux", mParticleFlux, CCopasiObject::ValueDbl));
   mpParticleFluxReference->setRefresh(this, &CReaction::calculate);
   mpPropensityReference =
     static_cast<CCopasiObjectReference<C_FLOAT64> *>(addObjectReference("Propensity", mPropensity, CCopasiObject::ValueDbl));
 }
const bool & CReaction::isFast () const
Check whether the reaction needs to be treated as fast @ return const bool & fast
Definition at line 1712 of file CReaction.cpp.
References mFast.
Referenced by ReactionsWidget1::loadFromReaction(), CCopasiXML::saveModel(), and ReactionsWidget1::saveToReaction().
 {
   return mFast;
 }
bool CReaction::isLocalParameter (const size_t & index) const
Check whether the indexed parameter is a local parameter.
Parameters
const size_t & index
Returns
bool isLocal
Definition at line 449 of file CReaction.cpp.
References CCopasiParameter::getKey(), CCopasiParameterGroup::getParameter(), mMetabKeyMap, mParameters, and CCopasiParameterGroup::size().
Referenced by CModelAdd::addReactions(), CFixLocalReactionParameters::changeModel(), CModel::convert2NonReversible(), CSBMLExporter::createKineticLaw(), CMMLOutput::createParameterMapping(), CModelExpansion::duplicateReaction(), CODEExporter::exportKineticFunction(), CODEExporter::exportReacParamsAndFuncs(), CODEExporterC::exportTitleData(), CQSimpleSelectionTree::filter(), getDeletedObjects(), CReactionInterface::getDeletedParameters(), getObject(), isLocalParameter(), CODEExporterC::KineticFunction2ODEmember(), CReactionInterface::loadMappingAndValues(), mustBeDeleted(), CQSimpleSelectionTree::populateTree(), CModel::printParameterOverview(), and CModelParameter::refreshFromModel().
 {
   size_t i, imax = mParameters.size();
   for (i = 0; i < imax; ++i)
     {
       if (mParameters.getParameter(i)->getKey() == mMetabKeyMap[index][0])
         return true;
     }
   return false;
 }
bool CReaction::isLocalParameter (const std::string & parameterName) const
Check whether the named parameter is a local parameter.
Parameters
const std::string & parameterName
Returns
bool isLocal
Definition at line 462 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, CFunctionParameter::FLOAT64, getParameterIndex(), isLocalParameter(), and mpFunction.
 {
   if (!mpFunction) fatalError();
   CFunctionParameter::DataType type;
   size_t index = getParameterIndex(parameterName, &type);
   if (C_INVALID_INDEX == index)
     return false;
   if (type != CFunctionParameter::FLOAT64) fatalError();
   return isLocalParameter(index);
 }
bool CReaction::isReversible () const
Retrieves whether the reaction is reversible
Returns
bool
Definition at line 229 of file CReaction.cpp.
References CChemEq::getReversibility(), and mChemEq.
Referenced by CModelAdd::addReactions(), CModelAnalyzer::checkReaction(), CMathObject::compilePropensity(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), SBMLImporter::findCorrespondingFunction(), CEFMTask::getReactionEquation(), CCopasiXML::saveModel(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), and setFunctionFromExpressionTree().
 {return mChemEq.getReversibility();}
C_INT32 CReaction::load (CReadConfig & configbuffer)
Loads an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
pconfigbuffer reference to a CReadConfig object.
Returns
mFail
See Also
mFail
Definition at line 148 of file CReaction.cpp.
References C_INT32, CCopasiObject::getObjectAncestor(), CReadConfig::getVariable(), loadOld(), mChemEq, mpFunction, CReadConfig::SEARCH, CChemEqInterface::setChemEqFromString(), setFunction(), CCopasiObject::setObjectName(), and CChemEq::setReversibility().
 {
   C_INT32 Fail = 0;
   std::string tmp;
   if ((Fail = configbuffer.getVariable("Step", "string", &tmp,
                                        CReadConfig::SEARCH)))
     return Fail;
   setObjectName(tmp);
   std::string ChemEq;
   if ((Fail = configbuffer.getVariable("Equation", "string", &ChemEq)))
     return Fail;
   CModel * pModel
   = dynamic_cast< CModel * >(getObjectAncestor("Model"));
   CChemEqInterface::setChemEqFromString(pModel, *this, ChemEq);
   if ((Fail = configbuffer.getVariable("KineticType", "string", &tmp)))
     return Fail;
   setFunction(tmp);
   if (mpFunction == NULL)
     return Fail = 1;
   bool revers;
   if ((Fail = configbuffer.getVariable("Reversible", "bool", &revers,
                                        CReadConfig::SEARCH)))
     return Fail;
   mChemEq.setReversibility(revers); // TODO: this should be consistent with the ChemEq string
   Fail = loadOld(configbuffer);
   return Fail;
 }
C_INT32 CReaction::loadOld (CReadConfig & configbuffer) private
Loads a reaction from a Gepasi file
Definition at line 767 of file CReaction.cpp.
References C_FLOAT64, C_INT32, fatalError, CFunctionParameter::FLOAT64, CFunctionParameterMap::getFunctionParameters(), CFunctionParameters::getNumberOfParametersByUsage(), CCopasiObject::getObjectName(), CFunctionParameters::getParameterByUsage(), CFunctionParameter::getType(), CReadConfig::getVariable(), loadOneRole(), mMap, CFunctionParameter::MODIFIER, CFunctionParameter::PARAMETER, CFunctionParameter::PRODUCT, setParameterValue(), StringPrint(), and CFunctionParameter::SUBSTRATE.
Referenced by load().
 {
   C_INT32 SubstrateSize, ProductSize, ModifierSize, ParameterSize;
   configbuffer.getVariable("Substrates", "C_INT32", &SubstrateSize);
   configbuffer.getVariable("Products", "C_INT32", &ProductSize);
   configbuffer.getVariable("Modifiers", "C_INT32", &ModifierSize);
   configbuffer.getVariable("Constants", "C_INT32", &ParameterSize);
   // Construct metabolite mappings
   loadOneRole(configbuffer, CFunctionParameter::SUBSTRATE,
               SubstrateSize, "Subs");
   loadOneRole(configbuffer, CFunctionParameter::PRODUCT,
               ProductSize, "Prod");
   loadOneRole(configbuffer, CFunctionParameter::MODIFIER,
               ModifierSize, "Modf");
   C_INT32 Fail = 0;
   // Construct parameters
   if (mMap.getFunctionParameters().getNumberOfParametersByUsage(CFunctionParameter::PARAMETER)
       != (size_t) ParameterSize)
     {
       // no. of parameters not matching function definition.
       fatalError();
     }
   size_t i, pos;
   std::string name;
   const CFunctionParameter* pParameter;
   C_FLOAT64 value;
   for (i = 0, pos = 0; i < (size_t) ParameterSize; i++)
     {
       name = StringPrint("Param%d", i);
       configbuffer.getVariable(name, "C_FLOAT64", &value);
       pParameter = mMap.getFunctionParameters().getParameterByUsage(CFunctionParameter::PARAMETER, pos);
       if (!pParameter)
         {
           // could not find variable.
           fatalError();
         }
       if (pParameter->getType() != CFunctionParameter::FLOAT64)
         {
           // unexpected parameter type.
           fatalError();
         }
       setParameterValue(pParameter->getObjectName(), value);
     }
   return Fail;
 }
bool CReaction::loadOneRole (CReadConfig & configbuffer, CFunctionParameter::Role role, C_INT32 n, const std::string & prefix) private
Used for loading Gepasi files. Loads the mapping for one role
Definition at line 668 of file CReaction.cpp.
References CChemEq::addMetabolite(), addParameterMapping(), C_INT32, clearParameterMapping(), fatalError, CModel::findMetabByName(), CFunctionParameterMap::getFunctionParameters(), CCopasiObject::getKey(), CModel::getMetabolites(), CFunctionParameters::getNumberOfParametersByUsage(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectName(), CFunctionParameters::getParameterByUsage(), CFunctionParameter::getType(), CReadConfig::getVariable(), CFunctionParameters::isVector(), mChemEq, mMap, CChemEq::MODIFIER, CFunctionParameter::MODIFIER, CCopasiDataModel::pOldMetabolites, setParameterMapping(), StringPrint(), and CFunctionParameter::VINT32.
Referenced by loadOld().
 {
   const CModel * pModel
   = dynamic_cast< const CModel * >(getObjectAncestor("Model"));
   const CCopasiVector< CMetab > & Metabolites = pModel->getMetabolites();
   size_t pos;
   C_INT32 i, imax;
   C_INT32 index;
   std::string name, parName, metabName;
   const CFunctionParameter* pParameter;
   CCopasiDataModel* pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   if (mMap.getFunctionParameters().isVector(role))
     {
       if (mMap.getFunctionParameters().getNumberOfParametersByUsage(role) != 1)
         {
           // not exactly one variable of this role as vector.
           fatalError();
         }
       pos = 0;
       pParameter = mMap.getFunctionParameters().getParameterByUsage(role, pos);
       if (!pParameter)
         {
           // could not find variable.
           fatalError();
         }
       parName = pParameter->getObjectName();
       clearParameterMapping(parName);
       for (i = 0; i < n; i++)
         {
           name = StringPrint(std::string(prefix + "%d").c_str(), i);
           configbuffer.getVariable(name, "C_INT32", &index);
           metabName = (*pDataModel->pOldMetabolites)[index]->getObjectName();
           addParameterMapping(parName, Metabolites[pModel->findMetabByName(metabName)]->getKey());
         }
     }
   else //no vector
     {
       imax = mMap.getFunctionParameters().getNumberOfParametersByUsage(role);
       if (imax > n)
         {
           // no. of metabs not matching function definition.
           fatalError();
         }
       for (i = 0, pos = 0; i < imax; i++)
         {
           name = StringPrint(std::string(prefix + "%d").c_str(), i);
           configbuffer.getVariable(name, "C_INT32", &index);
           metabName = (*pDataModel->pOldMetabolites)[index]->getObjectName();
           pParameter = mMap.getFunctionParameters().getParameterByUsage(role, pos);
           if (!pParameter)
             {
               // could not find variable.
               fatalError();
             }
           if (pParameter->getType() >= CFunctionParameter::VINT32)
             {
               // unexpected vector variable.
               fatalError();
             }
           parName = pParameter->getObjectName();
           setParameterMapping(parName, Metabolites[pModel->findMetabByName(metabName)]->getKey());
           // in the old files the chemical equation does not contain
           // information about modifiers. This has to be extracted from here.
           if (role == CFunctionParameter::MODIFIER)
             mChemEq.addMetabolite(Metabolites[pModel->findMetabByName(metabName)]->getKey(),
                                   1, CChemEq::MODIFIER);
         }
       //just throw away the rest (the Gepasi files gives all species, not only
       //those that influence the kinetics)
       for (i = imax; i < n; i++)
         {
           name = StringPrint(std::string(prefix + "%d").c_str(), i);
           configbuffer.getVariable(name, "C_INT32", &index);
         }
     }
   return true;
 }
bool CReaction::mustBeDeleted (const DataObjectSet & deletedObjects) const virtual
Check whether an object must be deleted because its prerequisites can no longer be fulfilled due to the given deleted objects
Parameters
const DataObjectSet & deletedObjects
Returns
bool mustBeDeleted
Reimplemented from CCopasiObject.
Definition at line 981 of file CReaction.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), isLocalParameter(), mParameters, mpFluxReference, and mpParticleFluxReference.
 {
   bool MustBeDeleted = false;
   DataObjectSet DeletedObjects = deletedObjects;
   // We need to ignore all local reaction parameters
   CCopasiParameterGroup::index_iterator itParameter = mParameters.beginIndex();
   CCopasiParameterGroup::index_iterator endParameter = mParameters.endIndex();
   for (; itParameter != endParameter ; ++itParameter)
     {
       if (isLocalParameter((*itParameter)->getObjectName()))
         {
           DeletedObjects.erase((*itParameter)->getValueReference());
         }
     }
   DataObjectSet ChildObjects;
   ChildObjects.insert(this);
   ChildObjects.insert(mpFluxReference);
   ChildObjects.insert(mpParticleFluxReference);
   DataObjectSet::const_iterator it = ChildObjects.begin();
   DataObjectSet::const_iterator end = ChildObjects.end();
   for (; it != end; ++it)
     {
       if (*it == this)
         {
           if ((*it)->CCopasiObject::mustBeDeleted(DeletedObjects))
             {
               MustBeDeleted = true;
               break;
             }
           continue;
         }
       if ((*it)->mustBeDeleted(DeletedObjects))
         {
           MustBeDeleted = true;
           break;
         }
     }
   return MustBeDeleted;
 }
CEvaluationNodeVariable * CReaction::object2variable (const CEvaluationNodeObject * objectNode, std::map< std::string, std::pair< CCopasiObject *, CFunctionParameter * > > & replacementMap, std::map< CCopasiObject *, SBase * > & copasi2sbmlmap) private
Converts a single object node to a variable node. The usage term of the variable nodes is recorded in terms of CFunctionParameters that are stored in the replacementMap. On failure a NULL pointer is returned.
Definition at line 1076 of file CReaction.cpp.
References CEvaluationNodeVariable::ANY, CCopasiMessage::ERROR, escapeId(), CCopasiMessage::EXCEPTION, CFunctionParameter::FLOAT64, getChemEq(), CEvaluationNodeObject::getData(), CChemEq::getModifiers(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectParent(), CChemEq::getProducts(), getSBMLId(), CChemEq::getSubstrates(), MCReaction, MCSBML, CFunctionParameter::MODIFIER, CCopasiDataModel::ObjectFromName(), CFunctionParameter::PARAMETER, CFunctionParameter::PRODUCT, CCopasiVector< T >::size(), CFunctionParameter::SUBSTRATE, CFunctionParameter::TIME, and CFunctionParameter::VOLUME.
Referenced by objects2variables().
 {
   CEvaluationNodeVariable* pVariableNode = NULL;
   std::string objectCN = objectNode->getData();
   CModel * pModel
   = dynamic_cast< CModel * >(getObjectAncestor("Model"));
   std::vector<CCopasiContainer*> containers = std::vector<CCopasiContainer*>();
   containers.push_back(pModel);
   CCopasiObject* object = getObjectDataModel()->ObjectFromName(containers, CCopasiObjectName(objectCN.substr(1, objectCN.size() - 2)));
   std::string id;
   // if the object if of type reference
   if (object)
     {
       if (dynamic_cast<CCopasiObjectReference<C_FLOAT64>*>(object))
         {
           object = object->getObjectParent();
           if (object)
             {
               std::map<CCopasiObject*, SBase*>::iterator pos = copasi2sbmlmap.find(object);
               //assert(pos!=copasi2sbmlmap.end());
               // check if it is a CMetab, a CModelValue or a CCompartment
               if (dynamic_cast<CMetab*>(object))
                 {
                   Species* pSpecies = dynamic_cast<Species*>(pos->second);
                   id = pSpecies->getId();
                   // We need to check that we have no reserved name.
                   const char *Reserved[] =
                   {
                     "pi", "exponentiale", "true", "false", "infinity", "nan",
                     "PI", "EXPONENTIALE", "TRUE", "FALSE", "INFINITY", "NAN"
                   };
                   size_t j, jmax = 12;
                   for (j = 0; j < jmax; j++)
                     if (id == Reserved[j]) break;
                   if (j != jmax)
                     id = "\"" + id + "\"";
                   pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, id);
                   if (replacementMap.find(id) == replacementMap.end())
                     {
                       // check whether it is a substrate, a product or a modifier
                       bool found = false;
                       const CCopasiVector<CChemEqElement>* v = &this->getChemEq().getSubstrates();
                       unsigned int i;
                       //std::string usage;
                       CFunctionParameter::Role usage;
                       for (i = 0; i < v->size(); ++i)
{
                           if (((*v)[i]->getMetabolite()) == static_cast<CMetab *>(object))
{
                               found = true;
                               usage = CFunctionParameter::SUBSTRATE;
                               break;
                             }
                         }
                       if (!found)
{
                           v = &this->getChemEq().getProducts();
                           for (i = 0; i < v->size(); ++i)
{
                               if (((*v)[i]->getMetabolite()) == static_cast<CMetab *>(object))
{
                                   found = true;
                                   usage = CFunctionParameter::PRODUCT;
                                   break;
                                 }
                             }
                           if (!found)
{
                               v = &this->getChemEq().getModifiers();
                               for (i = 0; i < v->size(); ++i)
{
                                   if (((*v)[i]->getMetabolite()) == static_cast<CMetab *>(object))
{
                                       found = true;
                                       usage = CFunctionParameter::MODIFIER;
                                       break;
                                     }
                                 }
                               if (!found)
{
                                   // if we are reading an SBML Level 1 file
                                   // we can assume that this is a modifier since
                                   // Level 1 did not define these in the reaction
                                   if (pSpecies->getLevel() == 1)
{
                                       found = true;
                                       usage = CFunctionParameter::MODIFIER;
                                     }
                                   else
{
                                       delete pVariableNode;
                                       pVariableNode = NULL;
                                       CCopasiMessage(CCopasiMessage::EXCEPTION, MCReaction + 7, id.c_str(), this->getSBMLId().c_str());
                                     }
                                 }
                             }
                         }
                       if (found)
{
                           CFunctionParameter* pFunParam = new CFunctionParameter(id, CFunctionParameter::FLOAT64, usage);
                           replacementMap[id] = std::make_pair(object, pFunParam);
                         }
                     }
                 }
               else if (dynamic_cast<CModelValue*>(object))
                 {
                   // usage = "PARAMETER"
                   id = dynamic_cast<Parameter*>(pos->second)->getId();
                   pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, id);
                   if (replacementMap.find(id) == replacementMap.end())
                     {
                       CFunctionParameter* pFunParam = new CFunctionParameter(id, CFunctionParameter::FLOAT64,
                           CFunctionParameter::PARAMETER);
                       replacementMap[id] = std::make_pair(object, pFunParam);
                     }
                 }
               else if (dynamic_cast<CCompartment*>(object))
                 {
                   // usage = "VOLUME"
                   id = dynamic_cast<Compartment*>(pos->second)->getId();
                   pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, id);
                   if (replacementMap.find(id) == replacementMap.end())
                     {
                       CFunctionParameter* pFunParam = new CFunctionParameter(id, CFunctionParameter::FLOAT64,
                           CFunctionParameter::VOLUME);
                       replacementMap[id] = std::make_pair(object, pFunParam);
                     }
                 }
               else if (dynamic_cast<CModel*>(object))
                 {
                   id = object->getObjectName();
                   id = this->escapeId(id);
                   pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, id);
                   if (replacementMap.find(id) == replacementMap.end())
                     {
                       CFunctionParameter* pFunParam = new CFunctionParameter(id, CFunctionParameter::FLOAT64,
                           CFunctionParameter::TIME);
                       replacementMap[id] = std::make_pair(object, pFunParam);
                     }
                 }
               else if (dynamic_cast<CReaction*>(object))
                 {
                   const CReaction* pReaction = static_cast<const CReaction*>(object);
                   CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 88, pReaction->getSBMLId().c_str(), this->getSBMLId().c_str());
                 }
               else
                 {
                   // error
                   CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 4);
                 }
             }
         }
       else if (dynamic_cast<CCopasiParameter*>(object))
         {
           id = object->getObjectName();
           id = this->escapeId(id);
           pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, id);
           if (replacementMap.find(id) == replacementMap.end())
             {
               CFunctionParameter* pFunParam = new CFunctionParameter(id, CFunctionParameter::FLOAT64,
                   CFunctionParameter::PARAMETER);
               replacementMap[id] = std::make_pair(object, pFunParam);
             }
         }
       /*
       else if (dynamic_cast<CModel*>(object))
         {
           // usage = "TIME"
           id = object->getObjectName();
           id = this->escapeId(id);
           pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, id);
           if (replacementMap.find(id) == replacementMap.end())
             {
               CFunctionParameter* pFunParam = new CFunctionParameter(id, CFunctionParameter::FLOAT64,
                                               CFunctionParameter::TIME);
               replacementMap[id] = std::make_pair(object, pFunParam);
             }
         }
         */
       else
         {
           // error
           CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 4);
         }
     }
   return pVariableNode;
 }
CEvaluationNode * CReaction::objects2variables (const CEvaluationNode * expression, std::map< std::string, std::pair< CCopasiObject *, CFunctionParameter * > > & replacementMap, std::map< CCopasiObject *, SBase * > & copasi2sbmlmap) private
Replaces all object nodes in an expression tree by variable nodes. The usage term of the variable nodes is recorded in terms of CFunctionParameters that are stored in the replacementMap. On failure a NULL pointer is returned.
Definition at line 1285 of file CReaction.cpp.
References CNodeContextIterator< Node, Context >::context(), CEvaluationNode::copyNode(), CNodeContextIterator< Node, Context >::end(), CCopasiMessage::ERROR, fatalError, CEvaluationNode::getType(), CEvaluationNode::INVALID, MCReaction, CEvaluationNode::MV_FUNCTION, CNodeContextIterator< Node, Context >::next(), CEvaluationNode::OBJECT, object2variable(), CNodeContextIterator< Node, Context >::parentContextPtr(), pResult, CEvaluationNode::STRUCTURE, CEvaluationNode::type(), and CEvaluationNode::VARIABLE.
Referenced by setFunctionFromExpressionTree().
 {
   CNodeContextIterator< const CEvaluationNode, std::vector< CEvaluationNode * > > itNode(pNode);
   CEvaluationNode* pResult = NULL;
   while (itNode.next() != itNode.end())
     {
       if (*itNode == NULL)
         {
           continue;
         }
       switch (CEvaluationNode::type(itNode->getType()))
         {
           case CEvaluationNode::OBJECT:
             // convert to a variable node
             pResult = object2variable(static_cast<const CEvaluationNodeObject * >(*itNode), replacementMap, copasi2sbmlmap);
             break;
           case CEvaluationNode::STRUCTURE:
             // this should not occur here
             fatalError();
             break;
           case CEvaluationNode::VARIABLE:
             // error variables may not be in an expression
             CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 6);
             pResult = NULL;
             break;
           case CEvaluationNode::MV_FUNCTION:
             // create an error message until there is a class for it
             CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 5, "MV_FUNCTION");
             pResult = NULL;
             break;
           case CEvaluationNode::INVALID:
             CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 5, "INVALID");
             // create an error message
             pResult = NULL;
             break;
           default:
             pResult = itNode->copyNode(itNode.context());
             break;
         }
       if (pResult != NULL &&
           itNode.parentContextPtr() != NULL)
         {
           itNode.parentContextPtr()->push_back(pResult);
         }
     }
   return pResult;
 }
CReaction& CReaction::operator= (const CReaction &) private
void CReaction::printDebug () const
Definition at line 1700 of file CReaction.cpp.
 {}
void CReaction::setFast (const bool & fast)
Set whether the reaction is to be treated as fast
Parameters
const bool & fast
Definition at line 1703 of file CReaction.cpp.
References mFast.
Referenced by ReactionsWidget1::saveToReaction(), and CCopasiXMLParser::ReactionElement::start().
 {
   mFast = fast;
 }
bool CReaction::setFunction (const std::string & functionName)
Sets the rate function of the reaction
Parameters
const string & functionName
Returns
bool success
Definition at line 255 of file CReaction.cpp.
References CCopasiMessage::ERROR, CFunctionDB::findLoadFunction(), CCopasiRootContainer::getFunctionList(), and MCReaction.
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), CReaction(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::KineticLawElement::end(), load(), setFunctionFromExpressionTree(), test000058::test_bug1025_1(), test000058::test_bug1025_6(), test000059::test_unique_id_10(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_4(), test000059::test_unique_id_7(), test000059::test_unique_id_9(), and CReactionInterface::writeBackToReaction().
 {
   CFunction * pFunction =
     dynamic_cast<CFunction *>(CCopasiRootContainer::getFunctionList()->findLoadFunction(functionName));
   if (!pFunction)
     CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 1, functionName.c_str());
   return setFunction(pFunction);
 }
bool CReaction::setFunction (CFunction * pFunction)
Sets the rate function of the reaction
Parameters
CFunction * pFunction
Returns
bool success
Definition at line 266 of file CReaction.cpp.
References CCopasiObject::addDirectDependency(), CCopasiRootContainer::getUndefinedFunction(), CFunction::getVariables(), CFunctionParameterMap::initializeFromFunctionParameters(), initializeMetaboliteKeyMap(), initializeParameters(), mMap, mpFunction, and CCopasiObject::removeDirectDependency().
 {
   removeDirectDependency(mpFunction);
   if (!pFunction)
     mpFunction = CCopasiRootContainer::getUndefinedFunction();
   else
     mpFunction = pFunction;
   addDirectDependency(mpFunction);
   mMap.initializeFromFunctionParameters(mpFunction->getVariables());
   initializeMetaboliteKeyMap(); //needs to be called before initializeParamters();
   initializeParameters();
   return true;
 }
CFunction * CReaction::setFunctionFromExpressionTree (const CExpression & tree, std::map< CCopasiObject *, SBase * > & copasi2sbmlmap, CFunctionDB * pFunctionDB)
Converts an expression tree into a CFunction object and sets the mapping for the reaction.
Definition at line 1343 of file CReaction.cpp.
References CFunctionDB::add(), CCopasiObject::addDirectDependency(), CFunction::addVariable(), SBMLImporter::areEqualFunctions(), CEvaluationTree::compile(), CEvaluationNode::copyBranch(), CFunctionDB::findFunction(), CCopasiObject::getObjectName(), CEvaluationTree::getRoot(), CFunctionParameter::getType(), CFunctionParameter::getUsage(), CFunction::getVariables(), CFunction::isReversible(), isReversible(), mpFunction, objects2variables(), pdelete, CCopasiObject::removeDirectDependency(), setFunction(), CCopasiObject::setObjectName(), setParameterMapping(), CFunction::setReversible(), CEvaluationTree::setRoot(), TriFalse, and TriTrue.
Referenced by SBMLImporter::createCReactionFromReaction().
 {
   // walk the tree and replace all object nodes with variable nodes.
   CFunction* pTmpFunction = NULL;
   const CEvaluationNode * pOrigNode = expression.getRoot();
   std::map<std::string, std::pair<CCopasiObject*, CFunctionParameter*> > replacementMap = std::map<std::string , std::pair<CCopasiObject*, CFunctionParameter*> >();
   CEvaluationNode* copy = pOrigNode->copyBranch();
   CEvaluationNode* pFunctionTree = objects2variables(copy, replacementMap, copasi2sbmlmap);
   delete copy;
   if (pFunctionTree)
     {
       // create the function object
       // later I might have to find out if I have to create a generic
       // function or a kinetic function
       // this can be distinguished by looking if the replacement map
       // contains CFunctionParameters that don't have the usage PARAMETER
       // create a unique name first
       pTmpFunction = new CKinFunction("\t"); // tab is an invalid name
       pTmpFunction->setRoot(pFunctionTree);
       pTmpFunction->setReversible(this->isReversible() ? TriTrue : TriFalse);
       pFunctionDB->add(pTmpFunction, true);
       // add the variables
       // and do the mapping
       std::map<std::string, std::pair<CCopasiObject*, CFunctionParameter*> >::iterator it = replacementMap.begin();
       std::map<std::string, std::pair<CCopasiObject*, CFunctionParameter*> >::iterator endIt = replacementMap.end();
       while (it != endIt)
         {
           CFunctionParameter* pFunPar = it->second.second;
           pTmpFunction->addVariable(pFunPar->getObjectName(), pFunPar->getUsage(), pFunPar->getType());
           ++it;
         }
       pTmpFunction->compile();
       setFunction(pTmpFunction);
       it = replacementMap.begin();
       while (it != endIt)
         {
           CFunctionParameter* pFunPar = it->second.second;
           std::string id = it->first;
           setParameterMapping(pFunPar->getObjectName(), it->second.first->getKey());
           delete pFunPar;
           ++it;
         }
       std::string functionName = "Function for " + this->getObjectName();
       if (expression.getObjectName() != "Expression")
         {
           functionName = expression.getObjectName();
         }
       std::string appendix = "";
       unsigned int counter = 0;
       std::ostringstream numberStream;
       CFunction * pExistingFunction = NULL;
       while ((pExistingFunction = pFunctionDB->findFunction(functionName + appendix)) != NULL)
         {
           if (SBMLImporter::areEqualFunctions(pExistingFunction, pTmpFunction))
             {
               removeDirectDependency(mpFunction);
               mpFunction = pExistingFunction;
               addDirectDependency(mpFunction);
               // The functions and their signature are equal however the role of the variables
               // might not be defined for the existing function if this is the first time it is used
               mpFunction->setReversible(pTmpFunction->isReversible());
               mpFunction->getVariables() = pTmpFunction->getVariables();
               pdelete(pTmpFunction);
               return NULL;
             }
           counter++;
           numberStream.str("");
           numberStream << "_" << counter;
           appendix = numberStream.str();
         }
       pTmpFunction->setObjectName(functionName + appendix);
     }
   return pTmpFunction;
 }
bool CReaction::setObjectParent (const CCopasiContainer * pParent) virtual
Sets the parent of the metabolite;
Parameters
const CCopasiContainer * pParent
Returns
bool success
Reimplemented from CCopasiObject.
Definition at line 141 of file CReaction.cpp.
References CCopasiObject::setObjectParent().
 {
   bool success = CCopasiContainer::setObjectParent(pParent);
   return success;
 }
void CReaction::setParameterMapping (const size_t & index, const std::string & key)
Sets a parameter mapping for the indexed parameter.
Parameters
const size_t & index
const std::string & key
Definition at line 339 of file CReaction.cpp.
References fatalError, CFunctionParameter::FLOAT64, getFunctionParameters(), mMetabKeyMap, and mpFunction.
Referenced by CModelAdd::addReactions(), CFixLocalReactionParameters::changeModel(), CModel::convert2NonReversible(), CModelExpansion::createDiffusionReaction(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), loadOneRole(), setFunctionFromExpressionTree(), CModelParameter::updateModel(), and CReactionInterface::writeBackToReaction().
 {
   if (!mpFunction) fatalError();
   if (getFunctionParameters()[index]->getType() != CFunctionParameter::FLOAT64) fatalError(); //wrong data type
   mMetabKeyMap[index][0] = key;
 }
bool CReaction::setParameterMapping (const std::string & parameterName, const std::string & key)
Sets a parameter mapping for the named parameter.
Parameters
const std::string & parameterName
const std::string & key
Returns
bool success
Definition at line 357 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, CFunctionParameter::FLOAT64, getParameterIndex(), mMetabKeyMap, and mpFunction.
 {
   if (!mpFunction) fatalError();
   CFunctionParameter::DataType type;
   size_t index = getParameterIndex(parameterName, &type);
   if (C_INVALID_INDEX == index)
     return false;
   if (type != CFunctionParameter::FLOAT64) fatalError();
   mMetabKeyMap[index][0] = key;
   return true;
 }
void CReaction::setParameterMappingVector (const std::string & parameterName, const std::vector< std::string > & keys)
Set the mapping for the name parameter which must be of type vector
Parameters
const std::string & parameterName
const std::vector<std::string> & keys
Definition at line 390 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, CFunctionParameter::FLOAT64, getParameterIndex(), mMetabKeyMap, and mpFunction.
Referenced by CModel::convert2NonReversible(), and CCopasiXMLParser::KineticLawElement::end().
 {
   if (!mpFunction) fatalError();
   CFunctionParameter::DataType type;
   size_t index;
   index = getParameterIndex(parameterName, &type);
   if (C_INVALID_INDEX == index)
     return;
   if ((type == CFunctionParameter::FLOAT64) && (keys.size() != 1)) fatalError();
   mMetabKeyMap[index] = keys;
 }
void CReaction::setParameterValue (const std::string & parameterName, const C_FLOAT64 & value, const bool & updateStatus = true)
Sets a parameter value if updateStatus==true the status is also updated to make sure the value is actually used (instead of a global value that may have been used before). if updateStatus==false only the value of the local parameter is set, even if it is not used
Parameters
const std::string & parameterName
const C_FLOAT64 & value
const bool & updateStatus (default: true(
Definition at line 303 of file CReaction.cpp.
References C_INVALID_INDEX, fatalError, CFunctionParameter::FLOAT64, getFunctionParameters(), CCopasiParameter::getKey(), CCopasiParameterGroup::getParameter(), getParameterIndex(), mMetabKeyMap, mParameters, mpFunction, and CCopasiParameterGroup::setValue().
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), CModelExpansion::duplicateReaction(), loadOld(), test000058::test_bug1025_1(), test000058::test_bug1025_6(), test000059::test_unique_id_10(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_4(), test000059::test_unique_id_7(), test000059::test_unique_id_9(), and CReactionInterface::writeBackToReaction().
 {
   if (!mpFunction) fatalError();
   mParameters.setValue(parameterName, value);
   if (!updateStatus) return;
   //make sure that this local parameter is actually used:
   //first find index
   size_t index = getParameterIndex(parameterName);
   if (index == C_INVALID_INDEX) return;
   if (getFunctionParameters()[index]->getType() != CFunctionParameter::FLOAT64) fatalError(); //wrong data type
   //set the key map
   mMetabKeyMap[index][0] = mParameters.getParameter(parameterName)->getKey();
 }
void CReaction::setReversible (bool reversible)
Sets whether the reaction is reversible
Parameters
bool reversible
Definition at line 247 of file CReaction.cpp.
References mChemEq, and CChemEq::setReversibility().
Referenced by CModelAdd::addReactions(), CModel::convert2NonReversible(), SBMLImporter::createCReactionFromReaction(), CModelExpansion::createDiffusionReaction(), CModelExpansion::duplicateReaction(), and CCopasiXMLParser::ReactionElement::start().
 {mChemEq.setReversibility(reversible);}
void CReaction::setSBMLId (const std::string & id)
Sets the SBMLId.
Definition at line 1649 of file CReaction.cpp.
References mSBMLId.
Referenced by SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createReaction(), CCopasiXMLParser::ReactionElement::start(), and CCopasiXMLParser::SBMLMapElement::start().
 {
   this->mSBMLId = id;
 }
void CReaction::setScalingFactor () private
Sets the scaling factor of the for the fluxes
Definition at line 879 of file CReaction.cpp.
References C_FLOAT64, CCopasiMessage::ERROR, CMetab::getCompartment(), getCompartmentNumber(), CCopasiObject::getDirectDependencies(), CCopasiException::getMessage(), CCopasiMessage::getNumber(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectName(), CChemEq::getProducts(), CModel::getQuantity2NumberFactor(), CChemEq::getSubstrates(), CModelEntity::getValuePointer(), CModelEntity::getValueReference(), MCChemEq, mChemEq, MCReaction, mDefaultScalingFactor, mpFluxReference, mpParticleFluxReference, mScalingFactor, mUnitScalingFactor, CCopasiObject::setDirectDependencies(), and CCopasiVector< T >::size().
Referenced by compile().
 {
   const CCompartment * pCompartment = NULL;
   if (1 == getCompartmentNumber())
     {
       const CMetab *pMetab = NULL;
       if (mChemEq.getSubstrates().size())
         pMetab = mChemEq.getSubstrates()[0]->getMetabolite();
       else if (mChemEq.getProducts().size())
         pMetab = mChemEq.getProducts()[0]->getMetabolite();
       if (pMetab != NULL)
         pCompartment = pMetab->getCompartment();
     }
   if (pCompartment != NULL)
     {
       mScalingFactor = (C_FLOAT64 *) pCompartment->getValuePointer();
       std::set< const CCopasiObject * > Dependencies = mpFluxReference->getDirectDependencies();
       Dependencies.insert(pCompartment->getValueReference());
       mpFluxReference->setDirectDependencies(Dependencies);
       mpParticleFluxReference->setDirectDependencies(Dependencies);
     }
   else
     mScalingFactor = &mDefaultScalingFactor;
 #ifdef XXXX
   if (mpFunctionCompartment)
     {
       // should propably check if the compartment appears in the chemical equation
       mScalingFactor = & mpFunctionCompartment->getVolume();
     }
   else
     {
       try
         {mScalingFactor = & mChemEq.CheckAndGetFunctionCompartment()->getVolume();}
       catch (CCopasiException Exc)
         {
           size_t nr = Exc.getMessage().getNumber();
           if ((MCChemEq + 2 == nr) || (MCChemEq + 3 == nr))
             CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 2, getObjectName().c_str());
           if (MCChemEq + 1 == nr)
             CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 3, getObjectName().c_str());
           throw;
         }
     }
 #endif // XXXX
   CModel * pModel = (CModel *) getObjectAncestor("Model");
   if (pModel)
     mUnitScalingFactor = & pModel->getQuantity2NumberFactor();
   else
     mUnitScalingFactor = & mDefaultScalingFactor;
 }
CEvaluationNodeObject * CReaction::variable2object (CEvaluationNodeVariable * pVariableNode) private
Converts a single variable node to an object node. On failure a NULL pointer is returned.
Definition at line 1614 of file CReaction.cpp.
References C_INVALID_INDEX, CEvaluationNodeObject::CN, CCopasiMessage::EXCEPTION, CFunctionParameters::findParameterByName(), CKeyFactory::get(), CCopasiObject::getCN(), CCopasiNode< _Data >::getData(), getFunction(), CCopasiRootContainer::getKeyFactory(), getParameterMappings(), CFunction::getVariables(), MCReaction, CFunctionParameter::VFLOAT64, and CFunctionParameter::VINT32.
Referenced by variables2objects().
 {
   CEvaluationNodeObject* pObjectNode = NULL;
   const std::string paraName = static_cast<const std::string>(pVariableNode->getData());
   CFunctionParameter::DataType type;
   size_t index = this->getFunction()->getVariables().findParameterByName(paraName, type);
   if (index == C_INVALID_INDEX)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCReaction + 8, (static_cast<std::string>(pVariableNode->getData())).c_str());
     }
   if (type == CFunctionParameter::VFLOAT64 || type == CFunctionParameter::VINT32)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCReaction + 10, (static_cast<std::string>(pVariableNode->getData())).c_str());
     }
   const std::string& key = this->getParameterMappings()[index][0];
   CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(key);
   if (!pObject)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCReaction + 9 , key.c_str());
     }
   pObjectNode = new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pObject->getCN() + ">");
   return pObjectNode;
 }
CEvaluationNode * CReaction::variables2objects (CEvaluationNode * expression) private
Replaces all variable nodes in a function tree by object nodes. On failure a NULL pointer is returned.
Definition at line 1440 of file CReaction.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::CALL, CEvaluationNode::CHOICE, CEvaluationNode::CONSTANT, CCopasiMessage::ERROR, CEvaluationNode::FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CEvaluationNode::INVALID, CEvaluationNode::LOGICAL, MCReaction, CEvaluationNode::MV_FUNCTION, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CEvaluationNode::OPERATOR, CEvaluationNode::STRUCTURE, CEvaluationNode::subType(), CEvaluationNode::type(), CEvaluationNode::VARIABLE, variable2object(), and CEvaluationNode::WHITESPACE.
Referenced by getExpressionTree().
 {
   CEvaluationNode* pTmpNode = NULL;
   CEvaluationNode* pChildNode = NULL;
   CEvaluationNode* pChildNode2 = NULL;
   switch (CEvaluationNode::type(expression->getType()))
     {
       case CEvaluationNode::NUMBER:
         pTmpNode = new CEvaluationNodeNumber(static_cast<CEvaluationNodeNumber::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         break;
       case CEvaluationNode::CONSTANT:
         pTmpNode = new CEvaluationNodeConstant(static_cast<CEvaluationNodeConstant::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         break;
       case CEvaluationNode::OPERATOR:
         pTmpNode = new CEvaluationNodeOperator(static_cast<CEvaluationNodeOperator::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         // convert the two children as well
         pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()));
         if (pChildNode)
           {
             pTmpNode->addChild(pChildNode);
             pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()->getSibling()));
             if (pChildNode)
               {
                 pTmpNode->addChild(pChildNode);
               }
             else
               {
                 delete pTmpNode;
                 pTmpNode = NULL;
               }
           }
         else
           {
             delete pTmpNode;
             pTmpNode = NULL;
           }
         break;
       case CEvaluationNode::OBJECT:
         pTmpNode = new CEvaluationNodeObject(static_cast<CEvaluationNodeObject::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         break;
       case CEvaluationNode::FUNCTION:
         pTmpNode = new CEvaluationNodeFunction(static_cast<CEvaluationNodeFunction::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         // convert the only child as well
         pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()));
         if (pChildNode)
           {
             pTmpNode->addChild(pChildNode);
           }
         else
           {
             delete pTmpNode;
             pTmpNode = NULL;
           }
         break;
       case CEvaluationNode::CALL:
         pTmpNode = new CEvaluationNodeCall(static_cast<CEvaluationNodeCall::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         // convert all children
         pChildNode2 = static_cast<CEvaluationNode*>(expression->getChild());
         while (pChildNode2)
           {
             pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(pChildNode2));
             if (pChildNode)
               {
                 pTmpNode->addChild(pChildNode);
               }
             else
               {
                 delete pTmpNode;
                 pTmpNode = NULL;
               }
             pChildNode2 = static_cast<CEvaluationNode*>(pChildNode2->getSibling());
           }
         break;
       case CEvaluationNode::STRUCTURE:
         pTmpNode = new CEvaluationNodeStructure(static_cast<CEvaluationNodeStructure::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         break;
       case CEvaluationNode::CHOICE:
         pTmpNode = new CEvaluationNodeChoice(static_cast<CEvaluationNodeChoice::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         // convert the two children as well
         pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()));
         if (pChildNode)
           {
             pTmpNode->addChild(pChildNode);
             pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()->getSibling()));
             if (pChildNode)
               {
                 pTmpNode->addChild(pChildNode);
               }
             else
               {
                 delete pTmpNode;
                 pTmpNode = NULL;
               }
           }
         else
           {
             delete pTmpNode;
             pTmpNode = NULL;
           }
         break;
       case CEvaluationNode::VARIABLE:
         pTmpNode = this->variable2object(static_cast<CEvaluationNodeVariable*>(expression));
         break;
       case CEvaluationNode::WHITESPACE:
         pTmpNode = new CEvaluationNodeWhiteSpace(static_cast<CEvaluationNodeWhiteSpace::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         break;
       case CEvaluationNode::LOGICAL:
         pTmpNode = new CEvaluationNodeLogical(static_cast<CEvaluationNodeLogical::SubType>((int) CEvaluationNode::subType(expression->getType())), expression->getData());
         // convert the two children as well
         pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()));
         if (pChildNode)
           {
             pTmpNode->addChild(pChildNode);
             pChildNode = this->variables2objects(static_cast<CEvaluationNode*>(expression->getChild()->getSibling()));
             if (pChildNode)
               {
                 pTmpNode->addChild(pChildNode);
               }
             else
               {
                 delete pTmpNode;
                 pTmpNode = NULL;
               }
           }
         else
           {
             delete pTmpNode;
             pTmpNode = NULL;
           }
         break;
       case CEvaluationNode::MV_FUNCTION:
         // create an error message until there is a class for it
         CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 5, "MV_FUNCTION");
         break;
       case CEvaluationNode::INVALID:
         CCopasiMessage(CCopasiMessage::ERROR, MCReaction + 5, "INVALID");
         // create an error message
         break;
       default:
         break;
     }
   return pTmpNode;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CReaction & d) friend
Friend declaration for ostream operator
Parameters
std::ostream & os
const CReaction & d
Returns
std::ostream & os
Definition at line 1029 of file CReaction.cpp.
 {
   os << "CReaction:  " << d.getObjectName() << std::endl;
   os << "   SBML id:  " << d.mSBMLId << std::endl;
   os << "   mChemEq " << std::endl;
   os << d.mChemEq;
   if (d.mpFunction)
     os << "   *mpFunction " << d.mpFunction->getObjectName() << std::endl;
   else
     os << "   mpFunction == 0 " << std::endl;
   //os << "   mParameterDescription: " << std::endl << d.mParameterDescription;
   os << "   mFlux: " << d.mFlux << std::endl;
   if (d.mScalingFactor)
     os << "   *mScalingFactor " << *(d.mScalingFactor) << std::endl;
   else
     os << "   mScalingFactor == NULL " << std::endl;
   if (d.mUnitScalingFactor)
     os << "   *mUnitScalingFactor " << *(d.mUnitScalingFactor) << std::endl;
   else
     os << "   mUnitScalingFactor == NULL " << std::endl;
   os << "   parameter group:" << std::endl;
   os << d.mParameters;
   os << "   key map:" << std::endl;
   size_t i, j;
   for (i = 0; i < d.mMetabKeyMap.size(); ++i)
     {
       os << i << ": ";
       for (j = 0; j < d.mMetabKeyMap[i].size(); ++j)
         os << d.mMetabKeyMap[i][j] << ", ";
       os << std::endl;
     }
   os << "----CReaction" << std::endl;
   return os;
 }
Member Data Documentation
CChemEq CReaction::mChemEq private
The chemical equation
Definition at line 558 of file CReaction.h.
Referenced by addModifier(), addProduct(), addSubstrate(), compile(), getChemEq(), getCompartmentNumber(), getLargestCompartment(), isReversible(), load(), loadOneRole(), operator<<(), setReversible(), and setScalingFactor().
C_FLOAT64 CReaction::mDefaultScalingFactor = 1.0 static private
The default scaling factor of a reaction which is 1.
Definition at line 553 of file CReaction.h.
Referenced by setScalingFactor().
bool CReaction::mFast private
This flag indicates whether the reaction is treated as fast. The interpretation of fast is up to to the integration algorithm.
Definition at line 623 of file CReaction.h.
Referenced by isFast(), and setFast().
C_FLOAT64 CReaction::mFlux private
The flux of the reaction, as amount of substance/time
Definition at line 568 of file CReaction.h.
Referenced by calculate(), calculateFlux(), compile(), getFlux(), initObjects(), and operator<<().
CFunctionParameterMap CReaction::mMap private
This describes the mapping of the species and parameters to the function parameters. Here are the pointers to the actual objects and values.
Definition at line 599 of file CReaction.h.
Referenced by calculate(), calculatePartialDerivative(), compile(), getCallParameters(), getFunctionParameters(), getParameterIndex(), initializeMetaboliteKeyMap(), initializeParameters(), loadOld(), loadOneRole(), and setFunction().
std::vector< std::vector< std::string > > CReaction::mMetabKeyMap private
This describes the mapping of the species to the function parameters. Here the keys of the metabolites (as in the chemical equation) are stored.
Definition at line 605 of file CReaction.h.
Referenced by addParameterMapping(), clearParameterMapping(), compile(), getParameterMapping(), getParameterMappings(), initializeMetaboliteKeyMap(), initializeParameters(), isLocalParameter(), operator<<(), setParameterMapping(), setParameterMappingVector(), and setParameterValue().
CCopasiParameterGroup CReaction::mParameters private
This is a list of parameter objects.
Definition at line 610 of file CReaction.h.
Referenced by getDeletedObjects(), getObject(), getParameters(), getParameterValue(), initializeParameters(), isLocalParameter(), mustBeDeleted(), operator<<(), and setParameterValue().
C_FLOAT64 CReaction::mParticleFlux private
The scaled flux of the reaction, as particle number/time
Definition at line 574 of file CReaction.h.
Referenced by calculate(), calculateParticleFlux(), compile(), getParticleFlux(), and initObjects().
CCopasiObjectReference<C_FLOAT64>* CReaction::mpFluxReference private
Definition at line 569 of file CReaction.h.
Referenced by compile(), getDeletedObjects(), getFluxReference(), initObjects(), mustBeDeleted(), and setScalingFactor().
CFunction* CReaction::mpFunction private
A pointer to the rate function of the reaction
Definition at line 563 of file CReaction.h.
Referenced by addParameterMapping(), calculate(), calculatePartialDerivative(), calculateParticleFlux(), clearParameterMapping(), compile(), CReaction(), getFunction(), getFunctionParameters(), getParameterMapping(), getParameterValue(), initializeMetaboliteKeyMap(), initializeParameters(), isLocalParameter(), load(), operator<<(), setFunction(), setFunctionFromExpressionTree(), setParameterMapping(), setParameterMappingVector(), and setParameterValue().
CCopasiObjectReference<C_FLOAT64>* CReaction::mpParticleFluxReference private
Definition at line 575 of file CReaction.h.
Referenced by compile(), getDeletedObjects(), getParticleFluxReference(), initObjects(), mustBeDeleted(), and setScalingFactor().
CCopasiObjectReference<C_FLOAT64>* CReaction::mpPropensityReference private
Definition at line 581 of file CReaction.h.
Referenced by getPropensityReference(), and initObjects().
C_FLOAT64 CReaction::mPropensity private
The propensity of the reaction
Definition at line 580 of file CReaction.h.
Referenced by initObjects().
std::string CReaction::mSBMLId private
The id of the corresponding reaction in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Definition at line 617 of file CReaction.h.
Referenced by getSBMLId(), operator<<(), and setSBMLId().
const C_FLOAT64* CReaction::mScalingFactor private
A pointer to the scaling factor for the flux to calculate the particle number changes. For a single compartment reaction this is the volume of the compartment
Definition at line 588 of file CReaction.h.
Referenced by calculate(), calculatePartialDerivative(), operator<<(), and setScalingFactor().
const C_FLOAT64* CReaction::mUnitScalingFactor private
The unit conversion factor
Definition at line 593 of file CReaction.h.
Referenced by calculate(), operator<<(), and setScalingFactor().
The documentation for this class was generated from the following files:
CReaction.h
CReaction.cpp