COPASI API: CQEffectDescriptionEdit.cpp File Reference
CQEffectDescriptionEdit.cpp File Reference
#include <QtGui/QColorDialog>
#include <qlayout/CQEffectDescription.h>
#include <qlayout/CQEffectDescriptionEdit.h>
#include <QtGui/QPainter>
Functions
void setColor (QLabel *widget, const QColor &color)
Function Documentation
void setColor (QLabel * widget, const QColor & color)
Definition at line 26 of file CQEffectDescriptionEdit.cpp.
Referenced by CQEffectDescriptionEdit::initFrom(), CQEffectDescriptionEdit::slotSelectColorEnd(), and CQEffectDescriptionEdit::slotSelectColorStart().
 {
   QPalette palette(color);
   palette.setColor(QPalette::Base, color);
   palette.setColor(QPalette::Background, color);
   palette.setColor(QPalette::Window, color);
   palette.setColor(QPalette::Foreground, color);
   widget->setPalette(palette);
   QImage image(widget->rect().size(), QImage::Format_ARGB32);
 #if QT_VERSION >= 0x040800
   image.fill(color);
 #else
   QPainter painter(&image);
   painter.fillRect(widget->rect(), color);
 #endif
   QPixmap pix = QPixmap::fromImage(image);
   widget->setPixmap(pix);
 }