COPASI API: CQCrossSectionTaskWidget Class Reference
CQCrossSectionTaskWidget Class Reference
#include <CQCrossSectionTaskWidget.h>
Public Member Functions
CQCrossSectionTaskWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQCrossSectionTaskWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
void commitInput ()
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Slots
void slotChooseVariable ()
void slotOutputConvergence (bool)
void slotOutputConvergenceTolerance ()
void slotOutputCrossings (bool)
void slotOutputCrossingsLimit ()
void slotOutputDelay (bool)
void slotOutputDelayTime ()
void slotUpdateConvergence (bool)
void slotUpdateConvergenceTolerance ()
void slotUpdateCrossings (bool)
void slotUpdateCrossingsLimit ()
void slotUpdateTime ()
void slotValueRate ()
Private Member Functions
void destroy ()
void init ()
void setSingleObject (const CCopasiObject *pSingleVariable)
void showUnits ()
void updateValues ()
Private Attributes
CCrossSectionProblem * mpCrossSectionProblem
const CCopasiObject * mpSingleVariable
CQValidatorDouble * mpValidatorCrossing
CQValidatorInt * mpValidatorLC
CQValidatorInt * mpValidatorOutLC
CQValidatorDouble * mpValidatorOutTime
CQValidatorDouble * mpValidatorOutTolerance
CQValidatorDouble * mpValidatorTime
CQValidatorDouble * mpValidatorTolerance
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 23 of file CQCrossSectionTaskWidget.h.
Constructor & Destructor Documentation
CQCrossSectionTaskWidget::CQCrossSectionTaskWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 41 of file CQCrossSectionTaskWidget.cpp.
References CQIconResource::copasi, CQIconResource::icon(), and init().
   : TaskWidget(parent, name)
   , mpSingleVariable(NULL)
   , mpCrossSectionProblem(NULL)
   , mpValidatorLC(NULL)
   , mpValidatorTime(NULL)
   , mpValidatorTolerance(NULL)
   , mpValidatorOutLC(NULL)
   , mpValidatorOutTime(NULL)
   , mpValidatorOutTolerance(NULL)
   , mpValidatorCrossing(NULL)
 {
   setupUi(this);
   mpButtonVariable->setIcon(CQIconResource::icon(CQIconResource::copasi));
   init();
 }
CQCrossSectionTaskWidget::~CQCrossSectionTaskWidget () virtual
Definition at line 63 of file CQCrossSectionTaskWidget.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQCrossSectionTaskWidget::commitInput () protected
Definition at line 124 of file CQCrossSectionTaskWidget.cpp.
References mpCrossSectionProblem, mpSingleVariable, CCrossSectionProblem::setConvergenceOutTolerance(), CCrossSectionProblem::setConvergenceTolerance(), CCrossSectionProblem::setCrossingsLimit(), CCrossSectionProblem::setFlagLimitConvergence(), CCrossSectionProblem::setFlagLimitCrossings(), CCrossSectionProblem::setFlagLimitOutConvergence(), CCrossSectionProblem::setFlagLimitOutCrossings(), CCrossSectionProblem::setFlagLimitOutTime(), CCrossSectionProblem::setOutCrossingsLimit(), CTrajectoryProblem::setOutputStartTime(), CCrossSectionProblem::setPositiveDirection(), CCrossSectionProblem::setSingleObjectCN(), CCrossSectionProblem::setThreshold(), and CCrossSectionProblem::setTimeLimit().
Referenced by runTask(), slotUpdateTime(), and slotValueRate().
 {
   if (!mpCrossSectionProblem) return;
   mpCrossSectionProblem->setFlagLimitCrossings(mpCheckSimCrossings->isChecked());
   mpCrossSectionProblem->setCrossingsLimit(mpTxtCrossings->text().toULong());
   mpCrossSectionProblem->setFlagLimitOutCrossings(mpCheckOutputCrossings->isChecked());
   mpCrossSectionProblem->setOutCrossingsLimit(mpTxtOutCrossings->text().toULong());
   mpCrossSectionProblem->setTimeLimit(mpTxtTime->text().toDouble());
   mpCrossSectionProblem->setOutputStartTime(mpTxtOutTime->text().toDouble());
   mpCrossSectionProblem->setFlagLimitOutTime(mpCheckOutputDelay->isChecked());
   mpCrossSectionProblem->setFlagLimitConvergence(mpCheckSimConvergence->isChecked());
   mpCrossSectionProblem->setConvergenceTolerance(mpTxtConvergence->text().toDouble());
   mpCrossSectionProblem->setFlagLimitOutConvergence(mpCheckOutputConvergence->isChecked());
   mpCrossSectionProblem->setConvergenceOutTolerance(mpTxtOutConvergence->text().toDouble());
   mpCrossSectionProblem->setSingleObjectCN(mpSingleVariable);
   mpCrossSectionProblem->setPositiveDirection(mpDirectionPositive->isChecked());
   mpCrossSectionProblem->setThreshold(mpLineEditValue->text().toDouble());
 }
CCopasiMethod * CQCrossSectionTaskWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 336 of file CQCrossSectionTaskWidget.cpp.
 {
   return NULL;
 }
void CQCrossSectionTaskWidget::destroy () private
Definition at line 119 of file CQCrossSectionTaskWidget.cpp.
References mpCrossSectionProblem, and pdelete.
Referenced by ~CQCrossSectionTaskWidget().
 {
   pdelete(mpCrossSectionProblem);
 }
void CQCrossSectionTaskWidget::init () private
Definition at line 69 of file CQCrossSectionTaskWidget.cpp.
References ListViews::findWidgetFromId(), max, TaskWidget::mpBtnWidget, mpCrossSectionProblem, TaskWidget::mpHeaderWidget, CopasiWidget::mpListView, TaskWidget::mpMethodWidget, mpValidatorCrossing, mpValidatorLC, mpValidatorOutLC, mpValidatorOutTime, mpValidatorOutTolerance, mpValidatorTime, mpValidatorTolerance, pResult, CQValidatorDouble::setRange(), CQValidatorInt::setRange(), CQTaskHeaderWidget::setTaskName(), CQTimeSeriesWidget::setTitle(), and CQTaskMethodWidget::showMethodParameters().
Referenced by CQCrossSectionTaskWidget().
 {
   mpCrossSectionProblem = NULL;
   mpHeaderWidget->setTaskName("Cross Section");
   verticalLayout->insertWidget(0, mpHeaderWidget);
   mpMethodWidget->showMethodParameters(true);
   mpGridLayout->addWidget(mpMethodWidget->mpLblParameter, 11, 0, 1, 1);
   mpGridLayout->addWidget(mpMethodWidget->mpTableParameter, 11, 1, 1, 2);
   // unsigned int ValidMethods = CCopasiMethod::unset;
   // mpMethodWidget->setValidMethods(&ValidMethods);
   // mpMethodWidget->setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
   // verticalLayout->addWidget(mpMethodWidget);
   verticalLayout->addWidget(mpBtnWidget);
   mpValidatorCrossing = new CQValidatorDouble(mpLineEditValue);
   mpLineEditValue->setValidator(mpValidatorCrossing);
   mpValidatorLC = new CQValidatorInt(mpTxtCrossings);
   mpValidatorLC->setRange(0, std::numeric_limits< int >::max());
   mpTxtCrossings->setValidator(mpValidatorLC);
   mpValidatorTime = new CQValidatorDouble(mpTxtTime);
   mpValidatorTime->setRange(0, std::numeric_limits< double >::max());
   mpTxtTime->setValidator(mpValidatorTime);
   mpValidatorOutTime = new CQValidatorDouble(mpTxtOutTime);
   mpTxtOutTime->setValidator(mpValidatorOutTime);
   mpValidatorTolerance = new CQValidatorDouble(mpTxtConvergence);
   mpTxtConvergence->setValidator(mpValidatorTolerance);
   mpValidatorOutLC = new CQValidatorInt(mpTxtOutCrossings);
   mpValidatorOutLC->setRange(0, std::numeric_limits< int >::max());
   mpTxtOutCrossings->setValidator(mpValidatorOutLC);
   mpValidatorOutTolerance = new CQValidatorDouble(mpTxtOutConvergence);
   mpTxtOutConvergence->setValidator(mpValidatorOutTolerance);
   CQTimeSeriesWidget * pResult =
     dynamic_cast< CQTimeSeriesWidget * >(mpListView->findWidgetFromId(281));
   if (pResult != NULL)
     pResult->setTitle("<h2>Cross Section Result</h2>");
 }
bool CQCrossSectionTaskWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 234 of file CQCrossSectionTaskWidget.cpp.
References CCrossSectionProblem::getConvergenceOutTolerance(), CCrossSectionProblem::getConvergenceTolerance(), CCrossSectionProblem::getCrossingsLimit(), CCrossSectionProblem::getFlagLimitConvergence(), CCrossSectionProblem::getFlagLimitCrossings(), CCrossSectionProblem::getFlagLimitOutConvergence(), CCrossSectionProblem::getFlagLimitOutCrossings(), CCrossSectionProblem::getFlagLimitOutTime(), CCopasiContainer::getObject(), CCopasiObject::getObjectDataModel(), CCrossSectionProblem::getOutCrossingsLimit(), CTrajectoryProblem::getOutputStartTime(), CCopasiTask::getProblem(), CCrossSectionProblem::getSingleObjectCN(), CCrossSectionProblem::getThreshold(), CCrossSectionProblem::getTimeLimit(), CCrossSectionProblem::isPositiveDirection(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), mpCrossSectionProblem, TaskWidget::mpTask, mpValidatorCrossing, mpValidatorLC, mpValidatorOutLC, mpValidatorOutTime, mpValidatorOutTolerance, mpValidatorTime, mpValidatorTolerance, pdelete, pTask, CQValidator< Type >::saved(), setSingleObject(), and showUnits().
 {
   // load Task
   CCrossSectionTask * pTask =
     dynamic_cast< CCrossSectionTask * >(mpTask);
   if (!pTask) return false;
   // load functions from the Parent, TaskWidget
   loadCommon();
   loadMethod();
   showUnits();
   // load Problem
   CCrossSectionProblem* pProblem =
     dynamic_cast<CCrossSectionProblem *>(pTask->getProblem());
   assert(pProblem);
   pdelete(mpCrossSectionProblem);
   mpCrossSectionProblem = new CCrossSectionProblem(*pProblem);
   //CCrossSectionMethod* pMethod =
   //  dynamic_cast<CCrossSectionMethod *>(pTask->getMethod());
   //assert(pMethod);
   //for now, we use a trajectory method
   //CTrajectoryMethod* pMethod =
   //  dynamic_cast<CTrajectoryMethod *>(pTask->getMethod());
   //assert(pMethod);
   // load the saved values
   const std::string &name = pProblem->getSingleObjectCN();
   if (name.empty())
     setSingleObject(NULL);
   else
     setSingleObject(static_cast<const CCopasiObject*>(pTask->getObjectDataModel()->getObject(name)));
   mpLineEditValue->setText(QString::number(pProblem->getThreshold()));
   mpDirectionPositive->setChecked(mpCrossSectionProblem->isPositiveDirection());
   mpDirectionNegative->setChecked(!mpCrossSectionProblem->isPositiveDirection());
   mpCheckSimConvergence->setChecked(pProblem->getFlagLimitConvergence());
   mpTxtConvergence->setEnabled(pProblem->getFlagLimitConvergence());
   if (pProblem->getFlagLimitConvergence())
     mpTxtConvergence->setText(QString::number(pProblem->getConvergenceTolerance()));
   else
     mpTxtConvergence->setText("");
   mpCheckOutputConvergence->setChecked(pProblem->getFlagLimitOutConvergence());
   mpTxtOutConvergence->setEnabled(pProblem->getFlagLimitOutConvergence());
   if (pProblem->getFlagLimitOutConvergence())
     mpTxtOutConvergence->setText(QString::number(pProblem->getConvergenceOutTolerance()));
   else
     mpTxtOutConvergence->setText("");
   mpCheckSimCrossings->setChecked(pProblem->getFlagLimitCrossings());
   mpTxtCrossings->setEnabled(pProblem->getFlagLimitCrossings());
   if (pProblem->getFlagLimitCrossings())
     mpTxtCrossings->setText(QString::number(pProblem->getCrossingsLimit()));
   else
     mpTxtCrossings->setText("");
   mpCheckOutputCrossings->setChecked(pProblem->getFlagLimitOutCrossings());
   mpTxtOutCrossings->setEnabled(pProblem->getFlagLimitOutCrossings());
   if (pProblem->getFlagLimitOutCrossings())
     mpTxtOutCrossings->setText(QString::number(pProblem->getOutCrossingsLimit()));
   else
     mpTxtOutCrossings->setText("");
   //mpCheckLT->setChecked(pProblem->getFlagLimitTime());
   if (pProblem->getFlagLimitOutTime())
     {
       mpCheckOutputDelay->setChecked(true);
       mpTxtOutTime->setEnabled(true);
       mpTxtOutTime->setText(QString::number(pProblem->getOutputStartTime()));
     }
   else
     {
       mpCheckOutputDelay->setChecked(false);
       mpTxtOutTime->setEnabled(false);
       mpTxtOutTime->setText("");
     }
   mpTxtTime->setText(QString::number(pProblem->getTimeLimit()));
   mpValidatorCrossing->saved();
   mpValidatorTolerance->saved();
   mpValidatorOutTolerance->saved();
   mpValidatorLC->saved();
   mpValidatorOutLC->saved();
   mpValidatorTime->saved();
   mpValidatorOutTime->saved();
   return true;
 }
bool CQCrossSectionTaskWidget::runTask () virtual
Implements TaskWidget.
Definition at line 144 of file CQCrossSectionTaskWidget.cpp.
References commitInput(), TaskWidget::commonBeforeRunTask(), and TaskWidget::commonRunTask().
Referenced by SliderDialog::runCrossSectionTask().
 {
   commitInput();
   if (!commonBeforeRunTask()) return false;
   bool success = true;
   if (!commonRunTask()) success = false;
   return success;
 }
bool CQCrossSectionTaskWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 160 of file CQCrossSectionTaskWidget.cpp.
References CCopasiTask::getProblem(), mpSingleVariable, TaskWidget::mpTask, mpValidatorCrossing, mpValidatorLC, mpValidatorOutLC, mpValidatorOutTime, mpValidatorOutTolerance, mpValidatorTime, mpValidatorTolerance, pTask, TaskWidget::saveCommon(), CQValidator< Type >::saved(), TaskWidget::saveMethod(), CCrossSectionProblem::setConvergenceOutTolerance(), CCrossSectionProblem::setConvergenceTolerance(), CCrossSectionProblem::setCrossingsLimit(), CCrossSectionProblem::setFlagLimitConvergence(), CCrossSectionProblem::setFlagLimitCrossings(), CCrossSectionProblem::setFlagLimitOutConvergence(), CCrossSectionProblem::setFlagLimitOutCrossings(), CCrossSectionProblem::setFlagLimitOutTime(), CCrossSectionProblem::setOutCrossingsLimit(), CTrajectoryProblem::setOutputStartTime(), CCrossSectionProblem::setPositiveDirection(), CCrossSectionProblem::setSingleObjectCN(), CCrossSectionProblem::setThreshold(), and CCrossSectionProblem::setTimeLimit().
 {
   // check the existence of Task
   CCrossSectionTask * pTask =
     dynamic_cast< CCrossSectionTask * >(mpTask);
   if (!pTask) return false;
   // save functions from the Parent, TaskWidget
   saveCommon();
   saveMethod();
   // check the existence of Problem
   CCrossSectionProblem* pProblem =
     dynamic_cast<CCrossSectionProblem *>(pTask->getProblem());
   assert(pProblem);
   // save the actual changes
   if (mpCheckSimConvergence->isChecked())
     pProblem->setCrossingsLimit(mpTxtCrossings->text().toULong());
   pProblem->setPositiveDirection(mpDirectionPositive->isChecked());
   pProblem->setThreshold(mpLineEditValue->text().toDouble());
   //if (mpCheckLT->isChecked())
   pProblem->setTimeLimit(mpTxtTime->text().toDouble());
   pProblem->setSingleObjectCN(mpSingleVariable);
   pProblem->setFlagLimitOutTime(mpCheckOutputDelay->isChecked());
   if (mpCheckOutputDelay->isChecked())
     {
       pProblem->setOutputStartTime(mpTxtOutTime->text().toDouble());
     }
   pProblem->setFlagLimitCrossings(mpCheckSimCrossings->isChecked());
   pProblem->setCrossingsLimit(mpTxtCrossings->text().toULong());
   pProblem->setFlagLimitOutCrossings(mpCheckOutputCrossings->isChecked());
   pProblem->setOutCrossingsLimit(mpTxtOutCrossings->text().toULong());
   pProblem->setFlagLimitConvergence(mpCheckSimConvergence->isChecked());
   pProblem->setConvergenceTolerance(mpTxtConvergence->text().toDouble());
   pProblem->setFlagLimitOutConvergence(mpCheckOutputConvergence->isChecked());
   pProblem->setConvergenceOutTolerance(mpTxtOutConvergence->text().toDouble());
   mpValidatorCrossing->saved();
   mpValidatorTolerance->saved();
   mpValidatorOutTolerance->saved();
   mpValidatorLC->saved();
   mpValidatorOutLC->saved();
   mpValidatorTime->saved();
   mpValidatorOutTime->saved();
   return true;
 }
void CQCrossSectionTaskWidget::setSingleObject (const CCopasiObject * pSingleVariable) private
Definition at line 350 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), and mpSingleVariable.
Referenced by loadTask(), and slotChooseVariable().
 {
   mpSingleVariable = pSingleVariable;
   if (pSingleVariable == NULL)
     mpLineEditVariable->setText(tr("[Please Choose Object.] --->"));
   else
     mpLineEditVariable->setText(FROM_UTF8(pSingleVariable->getObjectDisplayName()));
 }
void CQCrossSectionTaskWidget::showUnits () private
Definition at line 565 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiDataModel::getModel(), CModel::getTimeUnitsDisplayString(), and CopasiWidget::mpDataModel.
Referenced by loadTask(), and update().
 {
   const CModel * pModel = NULL;
   QString TimeUnits;
   if (mpDataModel != NULL &&
       (pModel = mpDataModel->getModel()) != NULL)
     {
       TimeUnits = "(" + FROM_UTF8(pModel->getTimeUnitsDisplayString()) + ")";
     }
   mpLblDurationLimit->setText("if detection time " + TimeUnits + " larger:");
   mpCheckOutputDelay->setText("if time " + TimeUnits + " larger:");
 }
void CQCrossSectionTaskWidget::slotChooseVariable () private slot
Definition at line 341 of file CQCrossSectionTaskWidget.cpp.
References CCopasiSelectionDialog::getObjectSingle(), mpSingleVariable, CQSimpleSelectionTree::ObservedValues, setSingleObject(), and CQSimpleSelectionTree::Variables.
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
         CQSimpleSelectionTree::Variables + CQSimpleSelectionTree::ObservedValues, mpSingleVariable);
   setSingleObject(pObject);
 }
void CQCrossSectionTaskWidget::slotOutputConvergence (bool b) private slot
Definition at line 454 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CQMessageBox::information(), mpCrossSectionProblem, and CCrossSectionProblem::setConvergenceOutTolerance().
 {
   mpTxtOutConvergence->setEnabled(b);
   if (!mpTxtOutConvergence->hasAcceptableInput())
     return;
   try
     {
       mpCrossSectionProblem->setConvergenceOutTolerance(mpTxtOutConvergence->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
 }
void CQCrossSectionTaskWidget::slotOutputConvergenceTolerance () private slot
Definition at line 498 of file CQCrossSectionTaskWidget.cpp.
 {
   if (!mpTxtOutConvergence->hasAcceptableInput())
     return;
   // TODO: Implement
 }
void CQCrossSectionTaskWidget::slotOutputCrossings (bool b) private slot
Definition at line 435 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CQMessageBox::information(), mpCrossSectionProblem, and CCrossSectionProblem::setOutCrossingsLimit().
 {
   mpTxtOutCrossings->setEnabled(b);
   if (!mpTxtOutCrossings->hasAcceptableInput())
     return;
   try
     {
       mpCrossSectionProblem->setOutCrossingsLimit(mpTxtOutCrossings->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
 }
void CQCrossSectionTaskWidget::slotOutputCrossingsLimit () private slot
Definition at line 505 of file CQCrossSectionTaskWidget.cpp.
 {
   if (!mpTxtOutCrossings->hasAcceptableInput())
     return;
   // TODO: Implement
 }
void CQCrossSectionTaskWidget::slotOutputDelay (bool b) private slot
Definition at line 413 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CQMessageBox::information(), mpCrossSectionProblem, and CTrajectoryProblem::setOutputStartTime().
 {
   mpTxtOutTime->setEnabled(b);
   if (!mpTxtOutTime->hasAcceptableInput())
     return;
   try
     {
       mpCrossSectionProblem->setOutputStartTime(mpTxtOutTime->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
 //  updateValues();
 }
void CQCrossSectionTaskWidget::slotOutputDelayTime () private slot
Definition at line 512 of file CQCrossSectionTaskWidget.cpp.
 {
   if (!mpTxtOutTime->hasAcceptableInput())
     return;
   // TODO: Implement
 }
void CQCrossSectionTaskWidget::slotUpdateConvergence (bool b) private slot
Definition at line 391 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CQMessageBox::information(), mpCrossSectionProblem, and CCrossSectionProblem::setConvergenceTolerance().
 {
   mpTxtConvergence->setEnabled(b);
   if (!mpTxtConvergence->hasAcceptableInput())
     return;
   try
     {
       mpCrossSectionProblem->setConvergenceTolerance(mpTxtConvergence->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
 //  updateValues();
 }
void CQCrossSectionTaskWidget::slotUpdateConvergenceTolerance () private slot
Definition at line 483 of file CQCrossSectionTaskWidget.cpp.
 {
   if (!mpTxtConvergence->hasAcceptableInput())
     return;
   // TODO: Implement
 }
void CQCrossSectionTaskWidget::slotUpdateCrossings (bool b) private slot
Definition at line 368 of file CQCrossSectionTaskWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CQMessageBox::information(), mpCrossSectionProblem, CCrossSectionProblem::setCrossingsLimit(), and CCrossSectionProblem::setFlagLimitCrossings().
 {
   mpTxtCrossings->setEnabled(b);
   if (!mpTxtCrossings->hasAcceptableInput())
     return;
   try
     {
       mpCrossSectionProblem->setFlagLimitCrossings(b);
       mpCrossSectionProblem->setCrossingsLimit(mpTxtCrossings->text().toULong());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
 //  updateValues();
 }
void CQCrossSectionTaskWidget::slotUpdateCrossingsLimit () private slot
Definition at line 490 of file CQCrossSectionTaskWidget.cpp.
 {
   if (!mpTxtCrossings->hasAcceptableInput())
     return;
   // TODO: Implement
 }
void CQCrossSectionTaskWidget::slotUpdateTime () private slot
Definition at line 474 of file CQCrossSectionTaskWidget.cpp.
References commitInput().
 {
   if (!mpTxtTime->hasAcceptableInput())
     return;
   commitInput();
   // TODO: Implement
 }
void CQCrossSectionTaskWidget::slotValueRate () private slot
Definition at line 360 of file CQCrossSectionTaskWidget.cpp.
References commitInput().
 {
   if (!mpLineEditValue->hasAcceptableInput())
     return;
   commitInput();
 }
bool CQCrossSectionTaskWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 215 of file CQCrossSectionTaskWidget.cpp.
References ListViews::findWidgetFromId(), CQTimeSeriesWidget::loadResult(), CopasiWidget::mpListView, TaskWidget::mpTask, and pResult.
 {
   bool success = true;
   // We need to load the result here as this is the only place where
   // we know that it is correct.
   CQTimeSeriesWidget * pResult =
     dynamic_cast< CQTimeSeriesWidget * >(mpListView->findWidgetFromId(281));
   if (pResult == NULL)
     return false;
   success &= pResult->loadResult(mpTask);
   return success;
 }
bool CQCrossSectionTaskWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from TaskWidget.
Definition at line 545 of file CQCrossSectionTaskWidget.cpp.
References ListViews::CHANGE, ListViews::MODEL, and showUnits().
 {
   switch (objectType)
     {
       case ListViews::MODEL:
         if (action == ListViews::CHANGE)
           {
             showUnits();
           }
         break;
       default:
         break;
     }
   return true;
 }
void CQCrossSectionTaskWidget::updateValues () private
Definition at line 520 of file CQCrossSectionTaskWidget.cpp.
References CCrossSectionProblem::getConvergenceOutTolerance(), CCrossSectionProblem::getConvergenceTolerance(), CCrossSectionProblem::getCrossingsLimit(), CCrossSectionProblem::getOutCrossingsLimit(), CTrajectoryProblem::getOutputStartTime(), CCrossSectionProblem::getThreshold(), CCrossSectionProblem::getTimeLimit(), mpCrossSectionProblem, mpValidatorCrossing, mpValidatorLC, mpValidatorOutLC, mpValidatorOutTime, mpValidatorOutTolerance, mpValidatorTime, mpValidatorTolerance, and CQValidator< Type >::revalidate().
 {
   mpTxtCrossings->setText(QString::number(mpCrossSectionProblem->getCrossingsLimit()));
   mpValidatorLC->revalidate();
   mpTxtOutCrossings->setText(QString::number(mpCrossSectionProblem->getOutCrossingsLimit()));
   mpValidatorOutLC->revalidate();
   mpTxtTime->setText(QString::number(mpCrossSectionProblem->getTimeLimit()));
   mpValidatorTime->revalidate();
   mpTxtOutTime->setText(QString::number(mpCrossSectionProblem->getOutputStartTime()));
   mpValidatorOutTime->revalidate();
   mpTxtConvergence->setText(QString::number(mpCrossSectionProblem->getConvergenceTolerance()));
   mpValidatorTolerance->revalidate();
   mpTxtOutConvergence->setText(QString::number(mpCrossSectionProblem->getConvergenceOutTolerance()));
   mpValidatorOutTolerance->revalidate();
   mpLineEditValue->setText(QString::number(mpCrossSectionProblem->getThreshold()));
   mpValidatorCrossing->revalidate();
 }
Member Data Documentation
CCrossSectionProblem* CQCrossSectionTaskWidget::mpCrossSectionProblem private
Definition at line 53 of file CQCrossSectionTaskWidget.h.
Referenced by commitInput(), destroy(), init(), loadTask(), slotOutputConvergence(), slotOutputCrossings(), slotOutputDelay(), slotUpdateConvergence(), slotUpdateCrossings(), and updateValues().
const CCopasiObject* CQCrossSectionTaskWidget::mpSingleVariable private
Definition at line 52 of file CQCrossSectionTaskWidget.h.
Referenced by commitInput(), saveTask(), setSingleObject(), and slotChooseVariable().
CQValidatorDouble* CQCrossSectionTaskWidget::mpValidatorCrossing private
Definition at line 61 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
CQValidatorInt* CQCrossSectionTaskWidget::mpValidatorLC private
Definition at line 55 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
CQValidatorInt* CQCrossSectionTaskWidget::mpValidatorOutLC private
Definition at line 58 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
CQValidatorDouble* CQCrossSectionTaskWidget::mpValidatorOutTime private
Definition at line 59 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
CQValidatorDouble* CQCrossSectionTaskWidget::mpValidatorOutTolerance private
Definition at line 60 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
CQValidatorDouble* CQCrossSectionTaskWidget::mpValidatorTime private
Definition at line 56 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
CQValidatorDouble* CQCrossSectionTaskWidget::mpValidatorTolerance private
Definition at line 57 of file CQCrossSectionTaskWidget.h.
Referenced by init(), loadTask(), saveTask(), and updateValues().
The documentation for this class was generated from the following files:
CQCrossSectionTaskWidget.h
CQCrossSectionTaskWidget.cpp