COPASI API: CRDFPredicate Class Reference
CRDFPredicate Class Reference
#include <CRDFPredicate.h>
Classes
struct sAllowedLocation
Public Types
typedef std::vector
< sAllowedLocation > AllowedLocationList
enum ePredicateType {
copasi_encodes = 0, copasi_hasPart, copasi_hasVersion, copasi_is,
copasi_isDescribedBy, copasi_isEncodedBy, copasi_isHomologTo, copasi_isPartOf,
copasi_isVersionOf, copasi_occursIn, bqbiol_encodes, bqbiol_hasPart,
bqbiol_hasVersion, bqbiol_is, bqbiol_isDescribedBy, bqbiol_isEncodedBy,
bqbiol_isHomologTo, bqbiol_isPartOf, bqbiol_isVersionOf, bqbiol_occursIn,
bqmodel_is, bqmodel_isDescribedBy, dc_creator, dcterms_creator,
dcterms_bibliographicCitation, dcterms_created, dcterms_description, dcterms_modified,
dcterms_W3CDTF, vcard_EMAIL, vcard_Family, vcard_Given,
vcard_N, vcard_ORG, vcard_Orgname, rdf_type,
rdf_li, rdf__n, rdf_subject, rdf_predicate,
rdf_object, unknown, about, any,
end
}
typedef std::vector
< ePredicateType > Path
Public Member Functions
CRDFPredicate (const ePredicateType &type=end)
CRDFPredicate (const std::string &uri)
CRDFPredicate (const CRDFPredicate &src)
const ePredicateType & getType () const
const std::string & getURI () const
bool operator!= (const CRDFPredicate &rhs) const
bool operator< (const CRDFPredicate &rhs) const
CRDFPredicate operator= (const ePredicateType &type)
bool operator== (const CRDFPredicate &rhs) const
void setURI (const std::string &uri)
~CRDFPredicate ()
Static Public Member Functions
static const AllowedLocationList & getAllowedLocationList (const ePredicateType &predicate)
static const std::string & getDisplayName (const CRDFPredicate &predicate)
static ePredicateType getPredicateFromDisplayName (const std::string &displayName)
static ePredicateType getPredicateFromURI (const std::string &URI)
static size_t getSubPathIndex (const Path &fullPath, const Path &currentPath)
static const std::string & getURI (const CRDFPredicate &predicate)
static bool isReadOnly (const Path &currentPath)
Static Private Member Functions
static void createAllowedLocationsAbsolute ()
static void createAllowedLocationsAbsolute (const ePredicateType &predicate)
static void createAllowedLocationsRelative ()
static void createDisplayName2Predicate ()
static void createURI2Predicate ()
static void initialize ()
Private Attributes
ePredicateType mType
std::string mURI
Static Private Attributes
static std::map< std::string,
ePredicateType > DisplayName2Predicate
static std::vector
< AllowedLocationList > Predicate2AllowedLocationsAbsolute
static std::vector
< AllowedLocationList > Predicate2AllowedLocationsRelative
static const std::string PredicateDisplayName []
static const std::string PredicateURI []
static std::map< std::string,
ePredicateType > URI2Predicate
Friends
std::ostream & operator<< (std::ostream &os, const CRDFPredicate &p)
Detailed Description
Definition at line 29 of file CRDFPredicate.h.
Member Typedef Documentation
typedef std::vector< sAllowedLocation > CRDFPredicate::AllowedLocationList
Definition at line 102 of file CRDFPredicate.h.
typedef std::vector< ePredicateType > CRDFPredicate::Path
Definition at line 91 of file CRDFPredicate.h.
Member Enumeration Documentation
enum CRDFPredicate::ePredicateType
Enumerator
copasi_encodes
copasi_hasPart
copasi_hasVersion
copasi_is
copasi_isDescribedBy
copasi_isEncodedBy
copasi_isHomologTo
copasi_isPartOf
copasi_isVersionOf
copasi_occursIn
bqbiol_encodes
bqbiol_hasPart
bqbiol_hasVersion
bqbiol_is
bqbiol_isDescribedBy
bqbiol_isEncodedBy
bqbiol_isHomologTo
bqbiol_isPartOf
bqbiol_isVersionOf
bqbiol_occursIn
bqmodel_is
bqmodel_isDescribedBy
dc_creator
dcterms_creator
dcterms_bibliographicCitation
dcterms_created
dcterms_description
dcterms_modified
dcterms_W3CDTF
vcard_EMAIL
vcard_Family
vcard_Given
vcard_N
vcard_ORG
vcard_Orgname
rdf_type
rdf_li
rdf__n
rdf_subject
rdf_predicate
rdf_object
unknown
about
any
end
Definition at line 32 of file CRDFPredicate.h.
   {
     /* These are proposed to unify:
      * http://biomodels.net/biology-qualifiers/...
      * http://biomodels.net/model-qualifiers/...
      */
     copasi_encodes = 0,
     copasi_hasPart,
     copasi_hasVersion,
     copasi_is,
     copasi_isDescribedBy,
     copasi_isEncodedBy,
     copasi_isHomologTo,
     copasi_isPartOf,
     copasi_isVersionOf,
     copasi_occursIn,
     // copasi_modification,
     bqbiol_encodes,
     bqbiol_hasPart,
     bqbiol_hasVersion,
     bqbiol_is,
     bqbiol_isDescribedBy,
     bqbiol_isEncodedBy,
     bqbiol_isHomologTo,
     bqbiol_isPartOf,
     bqbiol_isVersionOf,
     bqbiol_occursIn,
     bqmodel_is,
     bqmodel_isDescribedBy,
     dc_creator,
     dcterms_creator,
     dcterms_bibliographicCitation,
     // dcterms_contributor,
     dcterms_created,
     dcterms_description,
     // dcterms_license,
     dcterms_modified,
     // dcterms_rights,
     // dcterms_rightsHolder,
     dcterms_W3CDTF,
     vcard_EMAIL,
     vcard_Family,
     vcard_Given,
     vcard_N,
     vcard_ORG,
     vcard_Orgname,
     rdf_type,
     rdf_li,
     rdf__n,
     rdf_subject,
     rdf_predicate,
     rdf_object,
     unknown,
     // For internal use
     about,
     any,
     end
   };
Constructor & Destructor Documentation
CRDFPredicate::CRDFPredicate (const ePredicateType & type = end)
Default constructor
Parameters
const ePredicateType & type (default CRDFPredicate::end)
Definition at line 555 of file CRDFPredicate.cpp.
References initialize(), mType, mURI, and PredicateURI.
Referenced by operator=().
                                                        :
     mType(type),
     mURI()
 {
   initialize();
   mURI = CRDFPredicate::PredicateURI[mType];
 }
CRDFPredicate::CRDFPredicate (const std::string & uri)
Specific constructor
Parameters
const std::string & uri
Definition at line 563 of file CRDFPredicate.cpp.
References getPredicateFromURI(), initialize(), mType, mURI, PredicateURI, and rdf_li.
                                                  :
     mType(),
     mURI(uri)
 {
   initialize();
   mType = CRDFPredicate::getPredicateFromURI(mURI);
   if (mType == rdf_li)
     mURI = CRDFPredicate::PredicateURI[mType];
 }
CRDFPredicate::CRDFPredicate (const CRDFPredicate & src)
Copy constructor
Parameters
const CRDFPredicate & src
Definition at line 574 of file CRDFPredicate.cpp.
                                                      :
     mType(src.mType),
     mURI(src.mURI)
 {}
CRDFPredicate::~CRDFPredicate ()
Destructor
Definition at line 579 of file CRDFPredicate.cpp.
 {}
Member Function Documentation
void CRDFPredicate::createAllowedLocationsAbsolute () static private
Create the list of absolute allowed locations for each predicate
Definition at line 452 of file CRDFPredicate.cpp.
References Predicate2AllowedLocationsRelative.
Referenced by createAllowedLocationsAbsolute(), and initialize().
 {
   size_t Predicate, PredicateMax = Predicate2AllowedLocationsRelative.size();
   for (Predicate = 0; Predicate < PredicateMax; Predicate++)
     createAllowedLocationsAbsolute((ePredicateType) Predicate);
 }
void CRDFPredicate::createAllowedLocationsAbsolute (const ePredicateType & predicate) static private
Create the list of absolute allowed locations for the given predicate
Parameters
const ePredicateType & predicate
Definition at line 461 of file CRDFPredicate.cpp.
References about, any, createAllowedLocationsAbsolute(), CRDFPredicate::sAllowedLocation::Location, CRDFPredicate::sAllowedLocation::MaxOccurance, Predicate2AllowedLocationsAbsolute, Predicate2AllowedLocationsRelative, CRDFPredicate::sAllowedLocation::ReadOnly, and CRDFPredicate::sAllowedLocation::Type.
 {
   AllowedLocationList & RelativeList = Predicate2AllowedLocationsRelative[predicate];
   AllowedLocationList & AbsoluteList = Predicate2AllowedLocationsAbsolute[predicate];
   // Since we are called recursively the absolute locations might already have been build.
   if (AbsoluteList.size() > 0) return;
   sAllowedLocation Relative;
   size_t i, imax = RelativeList.size();
   for (i = 0; i < imax; i++)
     {
       sAllowedLocation & Relative = RelativeList[i];
       sAllowedLocation Absolute;
       Absolute.MaxOccurance = Relative.MaxOccurance;
       Absolute.Type = Relative.Type;
       // Debugging
       assert(Relative.Location.size() > 0);
       ePredicateType Parent = Relative.Location[0];
       size_t StartIndex = 0;
       // about is the root, i.e., the path is absolute
       if (Parent == about)
         {
           Absolute.ReadOnly = Relative.ReadOnly;
           Absolute.Location = Relative.Location;
           // Add the predicate itself.
           Absolute.Location.push_back(predicate);
           AbsoluteList.push_back(Absolute);
           continue;
         }
       if (Parent == any)
         {
           // Debugging
           assert(Relative.Location.size() > 1);
           Parent = Relative.Location[1];
           StartIndex = 1;
         }
       // Make sure that the absolute path of the parent is known
       createAllowedLocationsAbsolute(Parent);
       AllowedLocationList & ParentList = Predicate2AllowedLocationsAbsolute[Parent];
       // For each parent path append the relative path
       size_t j, jmax = ParentList.size();
       for (j = 0; j < jmax; j++)
         {
           Absolute.ReadOnly = ParentList[j].ReadOnly || Relative.ReadOnly;
           Absolute.Location = ParentList[j].Location;
           size_t k, kmax = Relative.Location.size();
           for (k = StartIndex + 1; k < kmax; k++)
             Absolute.Location.push_back(Relative.Location[k]);
           // Add the predicate itself.
           Absolute.Location.push_back(predicate);
           AbsoluteList.push_back(Absolute);
         }
     }
 }
void CRDFPredicate::createAllowedLocationsRelative () static private
Create the list of relative allowed locations for each predicate
Definition at line 179 of file CRDFPredicate.cpp.
References about, any, CRDFObject::BLANK_NODE, bqbiol_encodes, bqbiol_hasPart, bqbiol_hasVersion, bqbiol_is, bqbiol_isDescribedBy, bqbiol_isEncodedBy, bqbiol_isHomologTo, bqbiol_isPartOf, bqbiol_isVersionOf, bqbiol_occursIn, bqmodel_is, bqmodel_isDescribedBy, C_INVALID_INDEX, copasi_encodes, copasi_hasPart, copasi_hasVersion, copasi_is, copasi_isDescribedBy, copasi_isEncodedBy, copasi_isHomologTo, copasi_isPartOf, copasi_isVersionOf, copasi_occursIn, dc_creator, dcterms_bibliographicCitation, dcterms_created, dcterms_creator, dcterms_description, dcterms_modified, dcterms_W3CDTF, CRDFObject::LITERAL, Predicate2AllowedLocationsRelative, CRDFObject::RESOURCE, vcard_EMAIL, vcard_Family, vcard_Given, vcard_N, vcard_ORG, and vcard_Orgname.
Referenced by initialize().
 {
   AllowedLocationList AboutUnboundedResource;
   AboutUnboundedResource.resize(1);
   AboutUnboundedResource[0].MaxOccurance = C_INVALID_INDEX;
   AboutUnboundedResource[0].ReadOnly = false;
   AboutUnboundedResource[0].Type = CRDFObject::RESOURCE;
   AboutUnboundedResource[0].Location.resize(1);
   AboutUnboundedResource[0].Location[0] = about;
   AllowedLocationList AboutOneLiteral;
   AboutOneLiteral.resize(1);
   AboutOneLiteral[0].MaxOccurance = 1;
   AboutOneLiteral[0].ReadOnly = false;
   AboutOneLiteral[0].Type = CRDFObject::LITERAL;
   AboutOneLiteral[0].Location.resize(1);
   AboutOneLiteral[0].Location[0] = about;
   /* These are proposed to replace:
    * http://biomodels.net/biology-qualifiers/...
    * http://biomodels.net/model-qualifiers/...
    */
   // copasi_encodes:
   Predicate2AllowedLocationsRelative[copasi_encodes] = AboutUnboundedResource;
   // copasi_hasPart:
   Predicate2AllowedLocationsRelative[copasi_hasPart] = AboutUnboundedResource;
   // copasi_hasVersion:
   Predicate2AllowedLocationsRelative[copasi_hasVersion] = AboutUnboundedResource;
   // copasi_is:
   Predicate2AllowedLocationsRelative[copasi_is] = AboutUnboundedResource;
   // copasi_isDescribedBy:
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy].resize(1);
   //  *.dcterms_bibliographicCitation, *
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy][0].MaxOccurance = C_INVALID_INDEX;
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy][0].Type = CRDFObject::RESOURCE;
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy][0].Location.resize(2);
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy][0].Location[0] = any;
   Predicate2AllowedLocationsRelative[copasi_isDescribedBy][0].Location[1] = dcterms_bibliographicCitation;
   // copasi_isEncodedBy:
   Predicate2AllowedLocationsRelative[copasi_isEncodedBy] = AboutUnboundedResource;
   // copasi_isHomologTo:
   Predicate2AllowedLocationsRelative[copasi_isHomologTo] = AboutUnboundedResource;
   // copasi_isPartOf:
   Predicate2AllowedLocationsRelative[copasi_isPartOf] = AboutUnboundedResource;
   // copasi_isVersionOf:
   Predicate2AllowedLocationsRelative[copasi_isVersionOf] = AboutUnboundedResource;
   // copasi_occursIn:
   Predicate2AllowedLocationsRelative[copasi_occursIn] = AboutUnboundedResource;
   /*
   copasi_modification:
     about, *
    */
   // bq* is read only
   AboutUnboundedResource[0].ReadOnly = true;
   // bqbiol_encodes:
   Predicate2AllowedLocationsRelative[bqbiol_encodes] = AboutUnboundedResource;
   // bqbiol_hasPart:
   Predicate2AllowedLocationsRelative[bqbiol_hasPart] = AboutUnboundedResource;
   // bqbiol_hasVersion:
   Predicate2AllowedLocationsRelative[bqbiol_hasVersion] = AboutUnboundedResource;
   // bqbiol_is:
   Predicate2AllowedLocationsRelative[bqbiol_is] = AboutUnboundedResource;
   // bqbiol_isDescribedBy:
   Predicate2AllowedLocationsRelative[bqbiol_isDescribedBy] = AboutUnboundedResource;
   // bqbiol_isEncodedBy:
   Predicate2AllowedLocationsRelative[bqbiol_isEncodedBy] = AboutUnboundedResource;
   // bqbiol_isHomologTo:
   Predicate2AllowedLocationsRelative[bqbiol_isHomologTo] = AboutUnboundedResource;
   // bqbiol_isPartOf:
   Predicate2AllowedLocationsRelative[bqbiol_isPartOf] = AboutUnboundedResource;
   // bqbiol_isVersionOf:
   Predicate2AllowedLocationsRelative[bqbiol_isVersionOf] = AboutUnboundedResource;
   // bqbiol_occursIn:
   Predicate2AllowedLocationsRelative[bqbiol_occursIn] = AboutUnboundedResource;
   // bqmodel_is:
   Predicate2AllowedLocationsRelative[bqmodel_is] = AboutUnboundedResource;
   // bqmodel_isDescribedBy:
   Predicate2AllowedLocationsRelative[bqmodel_isDescribedBy] = AboutUnboundedResource;
   // dc_creator:
   Predicate2AllowedLocationsRelative[dc_creator] = AboutUnboundedResource;
   Predicate2AllowedLocationsRelative[dc_creator][0].Type = CRDFObject::BLANK_NODE;
   // change back to writable
   AboutUnboundedResource[0].ReadOnly = false;
   // dcterms_creator:
   Predicate2AllowedLocationsRelative[dcterms_creator] = AboutUnboundedResource;
   Predicate2AllowedLocationsRelative[dcterms_creator][0].Type = CRDFObject::BLANK_NODE;
   // dcterms_bibliographicCitation:
   Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation].resize(1);
   // about, *
   Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][0].MaxOccurance = C_INVALID_INDEX;
   Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][0].Type = CRDFObject::BLANK_NODE;
   Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][0].Location.resize(1);
   Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][0].Location[0] = about;
   // *.copasi_modification, *
   // Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][1].MaxOccurance = C_INVALID_INDEX;
   // Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][1].ReadOnly = false;
   // Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][1].Type = CRDFObject::BLANK_NODE;
   // Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][1].Location.resize(2);
   // Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][1].Location[0] = any;
   // Predicate2AllowedLocationsRelative[dcterms_bibliographicCitation][1].Location[1] = copasi_modification;
   // dcterms_contributor:
   // Predicate2AllowedLocationsRelative[dcterms_modified].resize(1);
   // *.copasi_modification, *
   // Predicate2AllowedLocationsRelative[dcterms_modified][0].MaxOccurance = C_INVALID_INDEX;
   // Predicate2AllowedLocationsRelative[dcterms_modified][0].ReadOnly = false;
   // Predicate2AllowedLocationsRelative[dcterms_modified][0].Type = CRDFObject::BLANK_NODE;
   // Predicate2AllowedLocationsRelative[dcterms_modified][0].Location.resize(2);
   // Predicate2AllowedLocationsRelative[dcterms_modified][0].Location[0] = any;
   // Predicate2AllowedLocationsRelative[dcterms_modified][0].Location[1] = copasi_modification;
   // dcterms_created:
   Predicate2AllowedLocationsRelative[dcterms_created].resize(1);
   // about, 1
   Predicate2AllowedLocationsRelative[dcterms_created][0].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[dcterms_created][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[dcterms_created][0].Type = CRDFObject::BLANK_NODE;
   Predicate2AllowedLocationsRelative[dcterms_created][0].Location.resize(1);
   Predicate2AllowedLocationsRelative[dcterms_created][0].Location[0] = about;
   // dcterms_description
   Predicate2AllowedLocationsRelative[dcterms_description].resize(1);
   // bibliographicCitation, 1
   Predicate2AllowedLocationsRelative[dcterms_description][0].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[dcterms_description][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[dcterms_description][0].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[dcterms_description][0].Location.resize(2);
   Predicate2AllowedLocationsRelative[dcterms_description][0].Location[0] = any;
   Predicate2AllowedLocationsRelative[dcterms_description][0].Location[1] = dcterms_bibliographicCitation;
   // dcterms_license:
   // Predicate2AllowedLocationsRelative[dcterms_license] = AboutOneLiteral;
   // dcterms_modified:
   Predicate2AllowedLocationsRelative[dcterms_modified].resize(1);
   // about, *
   Predicate2AllowedLocationsRelative[dcterms_modified][0].MaxOccurance = C_INVALID_INDEX;
   Predicate2AllowedLocationsRelative[dcterms_modified][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[dcterms_modified][0].Type = CRDFObject::BLANK_NODE;
   Predicate2AllowedLocationsRelative[dcterms_modified][0].Location.resize(1);
   Predicate2AllowedLocationsRelative[dcterms_modified][0].Location[0] = about;
   // *.copasi_modification, *
   // Predicate2AllowedLocationsRelative[dcterms_modified][1].MaxOccurance = C_INVALID_INDEX;
   // Predicate2AllowedLocationsRelative[dcterms_modified][1].ReadOnly = false;
   // Predicate2AllowedLocationsRelative[dcterms_modified][1].Type = CRDFObject::BLANK_NODE;
   // Predicate2AllowedLocationsRelative[dcterms_modified][1].Location.resize(2);
   // Predicate2AllowedLocationsRelative[dcterms_modified][1].Location[0] = any;
   // Predicate2AllowedLocationsRelative[dcterms_modified][1].Location[1] = copasi_modification;
   // dcterms_rights:
   // Predicate2AllowedLocationsRelative[dcterms_rights] = AboutOneLiteral;
   // dcterms_rightsHolder:
   // Predicate2AllowedLocationsRelative[dcterms_rights] = AboutOneLiteral;
   // dcterms_W3CDTF:
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF].resize(2);
   // *.dcterms_created, 1
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][0].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][0].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][0].Location.resize(2);
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][0].Location[0] = any;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][0].Location[1] = dcterms_created;
   // *.dcterms_modified, 1
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][1].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][1].ReadOnly = false;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][1].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][1].Location.resize(2);
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][1].Location[0] = any;
   Predicate2AllowedLocationsRelative[dcterms_W3CDTF][1].Location[1] = dcterms_modified;
   AllowedLocationList VCardOneBlankNode;
   VCardOneBlankNode.resize(2);
   // *.dcterms_creator, 1
   VCardOneBlankNode[0].MaxOccurance = 1;
   VCardOneBlankNode[0].ReadOnly = false;
   VCardOneBlankNode[0].Type = CRDFObject::BLANK_NODE;
   VCardOneBlankNode[0].Location.resize(2);
   VCardOneBlankNode[0].Location[0] = any;
   VCardOneBlankNode[0].Location[1] = dcterms_creator;
   // *.dc_creator, 1
   VCardOneBlankNode[1].MaxOccurance = 1;
   VCardOneBlankNode[1].ReadOnly = true;
   VCardOneBlankNode[1].Type = CRDFObject::BLANK_NODE;
   VCardOneBlankNode[1].Location.resize(2);
   VCardOneBlankNode[1].Location[0] = any;
   VCardOneBlankNode[1].Location[1] = dc_creator;
   // *.dcterms_contributor, 1
   // VCardOneBlankNode[1].MaxOccurance = 1;
   // VCardOneBlankNode[1].ReadOnly = false;
   // VCardOneBlankNode[1].Type = CRDFObject::BLANK_NODE;
   // VCardOneBlankNode[1].Location.resize(2);
   // VCardOneBlankNode[1].Location[0] = any;
   // VCardOneBlankNode[1].Location[1] = dcterms_contributor;
   // vcard_EMAIL:
   Predicate2AllowedLocationsRelative[vcard_EMAIL] = VCardOneBlankNode;
   // Override the default for vcard which is literal = true;
   Predicate2AllowedLocationsRelative[vcard_EMAIL][0].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[vcard_EMAIL][1].Type = CRDFObject::LITERAL;
   // vcard_Family:
   Predicate2AllowedLocationsRelative[vcard_Family].resize(1);
   // *.vcard_N, 1
   Predicate2AllowedLocationsRelative[vcard_Family][0].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[vcard_Family][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[vcard_Family][0].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[vcard_Family][0].Location.resize(2);
   Predicate2AllowedLocationsRelative[vcard_Family][0].Location[0] = any;
   Predicate2AllowedLocationsRelative[vcard_Family][0].Location[1] = vcard_N;
   // vcard_Given:
   Predicate2AllowedLocationsRelative[vcard_Given].resize(1);
   // *.vcard_N, 1
   Predicate2AllowedLocationsRelative[vcard_Given][0].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[vcard_Given][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[vcard_Given][0].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[vcard_Given][0].Location.resize(2);
   Predicate2AllowedLocationsRelative[vcard_Given][0].Location[0] = any;
   Predicate2AllowedLocationsRelative[vcard_Given][0].Location[1] = vcard_N;
   // vcard_N:
   Predicate2AllowedLocationsRelative[vcard_N] = VCardOneBlankNode;
   // vcard_ORG:
   Predicate2AllowedLocationsRelative[vcard_ORG] = VCardOneBlankNode;
   // vcard_Orgname:
   Predicate2AllowedLocationsRelative[vcard_Orgname].resize(1);
   // *.vcard_ORG, 1
   Predicate2AllowedLocationsRelative[vcard_Orgname][0].MaxOccurance = 1;
   Predicate2AllowedLocationsRelative[vcard_Orgname][0].ReadOnly = false;
   Predicate2AllowedLocationsRelative[vcard_Orgname][0].Type = CRDFObject::LITERAL;
   Predicate2AllowedLocationsRelative[vcard_Orgname][0].Location.resize(2);
   Predicate2AllowedLocationsRelative[vcard_Orgname][0].Location[0] = any;
   Predicate2AllowedLocationsRelative[vcard_Orgname][0].Location[1] = vcard_ORG;
 }
void CRDFPredicate::createDisplayName2Predicate () static private
Initialize the map from display name to predicate
Definition at line 165 of file CRDFPredicate.cpp.
References DisplayName2Predicate, and PredicateDisplayName.
Referenced by initialize().
 {
   int Predicate = 0;
   for (; PredicateDisplayName[Predicate] != "end"; Predicate++)
     DisplayName2Predicate.insert(std::map< std::string, ePredicateType >::value_type(PredicateDisplayName[Predicate], (ePredicateType) Predicate));
   DisplayName2Predicate.insert(std::map< std::string, ePredicateType >::value_type(PredicateDisplayName[Predicate], (ePredicateType) Predicate));
 }
void CRDFPredicate::createURI2Predicate () static private
Initialize the map from URI to predicate
Definition at line 87 of file CRDFPredicate.cpp.
References Predicate2AllowedLocationsAbsolute, Predicate2AllowedLocationsRelative, PredicateURI, and URI2Predicate.
Referenced by initialize().
 {
   int Predicate = 0;
   for (; PredicateURI[Predicate] != "end"; Predicate++)
     URI2Predicate[PredicateURI[Predicate]] = (ePredicateType) Predicate;
   URI2Predicate[PredicateURI[Predicate]] = (ePredicateType) Predicate;
   // Now we now the number of supported predicates.
   Predicate2AllowedLocationsRelative.resize(URI2Predicate.size());
   Predicate2AllowedLocationsAbsolute.resize(URI2Predicate.size());
 }
const CRDFPredicate::AllowedLocationList & CRDFPredicate::getAllowedLocationList (const ePredicateType & predicate) static
Retrieve the list of allowed locations in the RDF graph for the given predicate
Parameters
const ePredicateType & predicate
Returns
const AllowedLocationList & listOfAllowedLocations
Definition at line 618 of file CRDFPredicate.cpp.
References Predicate2AllowedLocationsAbsolute.
Referenced by CRDFGraphConverter::convert(), and CRDFNode::createMissingAncestors().
 {
   return Predicate2AllowedLocationsAbsolute[predicate];
 }
const std::string & CRDFPredicate::getDisplayName (const CRDFPredicate & predicate) static
Retrieve the display name for the given predicate
Parameters
const CRDFPredicate & predicate
Returns
const std::string & displayName
Definition at line 644 of file CRDFPredicate.cpp.
References mType, and PredicateDisplayName.
Referenced by CQMiriamWidget::CQMiriamWidget(), and CBiologicalDescription::getPredicate().
 {
   return PredicateDisplayName[predicate.mType];
 }
CRDFPredicate::ePredicateType CRDFPredicate::getPredicateFromDisplayName (const std::string & displayName) static
Retrieve the type of predicate from the given display name
Parameters
const std::string & displayName
Returns
ePredicateType type
Definition at line 650 of file CRDFPredicate.cpp.
References DisplayName2Predicate, and unknown.
Referenced by CBiologicalDescription::setPredicate().
 {
   std::map< std::string, ePredicateType >::iterator it = DisplayName2Predicate.find(displayName);
   if (it != DisplayName2Predicate.end())
     return it->second;
   else
     return unknown;
 }
CRDFPredicate::ePredicateType CRDFPredicate::getPredicateFromURI (const std::string & URI) static
Retrieve the type of predicate for the given URI
Parameters
const std::string & URI
Returns
ePredicateType type
Definition at line 630 of file CRDFPredicate.cpp.
References if(), PredicateURI, rdf__n, rdf_li, unknown, and URI2Predicate.
Referenced by CRDFPredicate(), and setURI().
 {
   std::map< std::string, ePredicateType >::iterator it = URI2Predicate.find(URI);
   if (it != URI2Predicate.end())
     return it->second;
   // Handle rdf:_n and map it to rdf:li
   else if (URI.compare(0, PredicateURI[rdf__n].length(), PredicateURI[rdf__n]) == 0)
     return rdf_li;
   else
     return unknown;
 }
size_t CRDFPredicate::getSubPathIndex (const Path & fullPath, const Path & currentPath) static
Retrieve the index of the next path element of the full path beyond the current path. If the current path is not part of the full path C_INVALID_INDEX is returned
Parameters
const Path & fullPath
const Path & currentPath
Returns
size_t index
Definition at line 661 of file CRDFPredicate.cpp.
References C_INVALID_INDEX.
Referenced by CRDFGraphConverter::convert(), and CRDFNode::createMissingAncestors().
 {
   // If the current path is longer than the full path we fail
   if (currentPath.size() > fullPath.size())
     return C_INVALID_INDEX;
   // Check whether the current path is part of the full path;
   Path::const_iterator itCurrent = currentPath.begin();
   Path::const_iterator endCurrent = currentPath.end();
   Path::const_iterator itFull = fullPath.begin();
   for (; itCurrent != endCurrent; ++itCurrent, ++itFull)
     if (*itCurrent != *itFull)
       return C_INVALID_INDEX;
   return currentPath.size();
 }
const CRDFPredicate::ePredicateType & CRDFPredicate::getType () const
Retrieve the type og the predicate.
Returns
const ePredicateType & type
Definition at line 585 of file CRDFPredicate.cpp.
References mType.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
 {return mType;}
const std::string & CRDFPredicate::getURI () const
Retrieve the URI.
Returns
const std::string & URI
Definition at line 598 of file CRDFPredicate.cpp.
References mURI.
Referenced by CBiologicalDescription::clearInvalidEntries(), CRDFGraphConverter::convert(), CMIRIAMInfo::createCreator(), CRDFNode::createMissingAncestors(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), operator<<(), CMIRIAMInfo::removeCreator(), CMIRIAMInfo::removeModification(), CMIRIAMInfo::removeReference(), CMIRIAMInfo::setCreatedDT(), CRDFNode::setFieldValue(), and CQRDFTreeViewItem::setTriplet().
 {return mURI;}
const std::string & CRDFPredicate::getURI (const CRDFPredicate & predicate) static
Retrieve the URI for the given predicate
Parameters
const CRDFPredicate & predicate
Returns
const std::string & uri
Definition at line 624 of file CRDFPredicate.cpp.
References mType, and PredicateURI.
 {
   return PredicateURI[predicate.mType];
 }
void CRDFPredicate::initialize () static private
Initialize the static information
Definition at line 532 of file CRDFPredicate.cpp.
References createAllowedLocationsAbsolute(), createAllowedLocationsRelative(), createDisplayName2Predicate(), and createURI2Predicate().
Referenced by CRDFPredicate().
 {
   static bool Initialized = false;
   if (Initialized)
     return;
   Initialized = true;
   // Fill URI2Predicate
   createURI2Predicate();
   // Fill DisplayName2Predicate
   createDisplayName2Predicate();
   // Fill relative allowed locations
   createAllowedLocationsRelative();
   // Fill relative allowed locations
   createAllowedLocationsAbsolute();
 }
bool CRDFPredicate::isReadOnly (const Path & currentPath) static
Checks whether the element pointed to by the current path is read-only
Parameters
const Path & currentPath
Returns
bool isReadOnly
Definition at line 681 of file CRDFPredicate.cpp.
References Predicate2AllowedLocationsAbsolute.
Referenced by CRDFNode::isReadOnly().
 {
   // Iterate over each predicate
   std::vector< AllowedLocationList >::const_iterator itPredicate = Predicate2AllowedLocationsAbsolute.begin();
   std::vector< AllowedLocationList >::const_iterator endPredicate = Predicate2AllowedLocationsAbsolute.end();
   for (; itPredicate != endPredicate; ++itPredicate)
     {
       // Iterate over each location
       AllowedLocationList::const_iterator itLocation = itPredicate->begin();
       AllowedLocationList::const_iterator endLocation = itPredicate->end();
       for (; itLocation != endLocation; ++itLocation)
         if (itLocation->ReadOnly &&
             currentPath.size() == itLocation->Location.size())
           {
             // Compare the path.
             Path::const_iterator itCurrent = currentPath.begin();
             Path::const_iterator endCurrent = currentPath.end();
             Path::const_iterator itAbsolute = itLocation->Location.begin();
             for (; itCurrent != endCurrent; ++itCurrent, ++itAbsolute)
               if (*itCurrent != *itAbsolute)
                 break;
             if (itCurrent == endCurrent)
               return true;
           }
     }
   return false;
 }
bool CRDFPredicate::operator!= (const CRDFPredicate & rhs) const
Comparison operator for inequality.
Parameters
const CRDFPredicate & rhs
Returns
bool isNotEqual
Definition at line 604 of file CRDFPredicate.cpp.
References mURI.
 {return mURI != rhs.mURI;}
bool CRDFPredicate::operator< (const CRDFPredicate & rhs) const
Comparison operator for less.
Parameters
const CRDFPredicate & rhs
Returns
bool isLess
Definition at line 607 of file CRDFPredicate.cpp.
References mURI.
 {return mURI < rhs.mURI;}
CRDFPredicate CRDFPredicate::operator= (const ePredicateType & type)
Assignment operator.
Parameters
const ePredicateType & type
Returns
CRDFPredicate predicate
Definition at line 582 of file CRDFPredicate.cpp.
References CRDFPredicate().
 {return CRDFPredicate(type);}
bool CRDFPredicate::operator== (const CRDFPredicate & rhs) const
Comparison operator for equality.
Parameters
const CRDFPredicate & rhs
Returns
bool isEqual
Definition at line 601 of file CRDFPredicate.cpp.
References mURI.
 {return mURI == rhs.mURI;}
void CRDFPredicate::setURI (const std::string & uri)
Set the URI.
Parameters
const std::string & URI
Definition at line 588 of file CRDFPredicate.cpp.
References getPredicateFromURI(), mType, mURI, PredicateURI, and rdf_li.
 {
   mType = getPredicateFromURI(uri);
   if (mType == rdf_li)
     mURI = CRDFPredicate::PredicateURI[mType];
   else
     mURI = uri;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CRDFPredicate & p) friend
Friend declaration of ostream operator
Parameters
std::ostream & os
const CRDFPredicate & p
Returns
std::ostream & os
Definition at line 611 of file CRDFPredicate.cpp.
 {
   os << p.mType;
   return os;
 }
Member Data Documentation
std::map< std::string, CRDFPredicate::ePredicateType > CRDFPredicate::DisplayName2Predicate static private
Map from display name to predicate type
Definition at line 296 of file CRDFPredicate.h.
Referenced by createDisplayName2Predicate(), and getPredicateFromDisplayName().
ePredicateType CRDFPredicate::mType private
The type of the predicate
Definition at line 271 of file CRDFPredicate.h.
Referenced by CRDFPredicate(), getDisplayName(), getType(), getURI(), operator<<(), and setURI().
std::string CRDFPredicate::mURI private
The URI
Definition at line 276 of file CRDFPredicate.h.
Referenced by CRDFPredicate(), getURI(), operator!=(), operator<(), operator==(), and setURI().
std::vector< CRDFPredicate::AllowedLocationList > CRDFPredicate::Predicate2AllowedLocationsAbsolute static private
Vector of absolute allowed locations
Definition at line 306 of file CRDFPredicate.h.
Referenced by createAllowedLocationsAbsolute(), createURI2Predicate(), getAllowedLocationList(), and isReadOnly().
std::vector< CRDFPredicate::AllowedLocationList > CRDFPredicate::Predicate2AllowedLocationsRelative static private
Vector of relative allowed locations
Definition at line 301 of file CRDFPredicate.h.
Referenced by createAllowedLocationsAbsolute(), createAllowedLocationsRelative(), and createURI2Predicate().
const std::string CRDFPredicate::PredicateDisplayName static private
Static strings for display names
Definition at line 291 of file CRDFPredicate.h.
Referenced by createDisplayName2Predicate(), and getDisplayName().
const std::string CRDFPredicate::PredicateURI static private
Static strings for URIs
Definition at line 281 of file CRDFPredicate.h.
Referenced by CRDFPredicate(), createURI2Predicate(), getPredicateFromURI(), getURI(), and setURI().
std::map< std::string, CRDFPredicate::ePredicateType > CRDFPredicate::URI2Predicate static private
Map from URI to predicate type
Definition at line 286 of file CRDFPredicate.h.
Referenced by createURI2Predicate(), and getPredicateFromURI().
The documentation for this class was generated from the following files:
CRDFPredicate.h
CRDFPredicate.cpp