COPASI API: CCopasiXMLParser::AdditionalGOElement Class Reference
CCopasiXMLParser::AdditionalGOElement Class Reference
Public Member Functions
AdditionalGOElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~AdditionalGOElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { AdditionalGO = 0, BoundingBox, Position, Dimensions }
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3549 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::AdditionalGOElement::Element private
Enumerator
AdditionalGO
BoundingBox
Position
Dimensions
Definition at line 3552 of file CCopasiXMLParser.h.
     {
       AdditionalGO = 0,
       BoundingBox,
       Position,
       Dimensions
     };
Constructor & Destructor Documentation
CCopasiXMLParser::AdditionalGOElement::AdditionalGOElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Definition at line 7778 of file CCopasiXMLParser.cpp.
                                                                                                                  :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::AdditionalGOElement::~AdditionalGOElement () virtual
Definition at line 7783 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::AdditionalGOElement::end (const XML_Char * pszName) virtual
Definition at line 7872 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "AdditionalGraphicalObject"))
     {
       mParser.popElementHandler();
       mCurrentElement = START_ELEMENT;
       /* Tell the parent element we are done. */
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case BoundingBox:
             break;
           case Position:
             break;
           case Dimensions:
             //tell the handler where to continue
             mCurrentElement = BoundingBox;
             break;
           case UNKNOWN_ELEMENT:
             mCurrentElement = AdditionalGO;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::AdditionalGOElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Definition at line 7786 of file CCopasiXMLParser.cpp.
References CLayout::addGeneralGlyph(), CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentLayout, SCopasiXMLParserCommon::pGeneralGlyph, CLGraphicalObject::setHeight(), CLGraphicalObject::setObjectRole(), CLGraphicalObject::setWidth(), CLGraphicalObject::setX(), CLGraphicalObject::setY(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case AdditionalGO:
         if (strcmp(pszName, "AdditionalGraphicalObject"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "AdditionalGraphicalObject", mParser.getCurrentLineNumber());
         {
           //workload //TODO
           const char * key;
           const char * name;
           key = mParser.getAttributeValue("key", papszAttrs);
           name = mParser.getAttributeValue("name", papszAttrs);
           mCommon.pGeneralGlyph = new CLGeneralGlyph(name);
           const char * objectRole = mParser.getAttributeValue("objectRole", papszAttrs, false);
           if (objectRole != NULL && objectRole[0] != 0)
             {
               mCommon.pGeneralGlyph->setObjectRole(objectRole);
             }
           mCommon.pCurrentLayout->addGeneralGlyph(mCommon.pGeneralGlyph);
           addFix(key, mCommon.pGeneralGlyph);
         }
         return;
         break;
       case BoundingBox:
         if (!strcmp(pszName, "BoundingBox"))
           return;
         break;
       case Position:
         if (!strcmp(pszName, "Position"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             mCommon.pGeneralGlyph->setX(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("y", papszAttrs);
             mCommon.pGeneralGlyph->setY(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Dimensions:
         if (!strcmp(pszName, "Dimensions"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("width", papszAttrs);
             mCommon.pGeneralGlyph->setWidth(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("height", papszAttrs);
             mCommon.pGeneralGlyph->setHeight(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::AdditionalGOElement::mLineNumber private
Definition at line 3560 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp