COPASI API: CAbstractLayoutInterface Class Reference
CAbstractLayoutInterface Class Reference abstract
#include <CAbstractLayoutInterface.h>
Classes
class VariableDescription
Public Member Functions
CAbstractLayoutInterface ()
virtual const std::vector
< double > & getInitialValues () const =0
virtual const std::vector
< double > & getMassVector () const
unsigned int getNumVariables () const
virtual double getPotential ()=0
const std::vector
< VariableDescription > & getVariablesDescription () const
virtual bool setState (const std::vector< double > &vars)=0
virtual ~CAbstractLayoutInterface ()
Protected Attributes
std::vector< double > mMassVector
std::vector< VariableDescription > mVarDescription
Detailed Description
This abstract class describes how an optimization algorithm will see a layout.
Definition at line 15 of file CAbstractLayoutInterface.h.
Constructor & Destructor Documentation
CAbstractLayoutInterface::CAbstractLayoutInterface () inline
Definition at line 18 of file CAbstractLayoutInterface.h.
 {};
virtual CAbstractLayoutInterface::~CAbstractLayoutInterface () inline virtual
Definition at line 19 of file CAbstractLayoutInterface.h.
 {};
Member Function Documentation
virtual const std::vector<double>& CAbstractLayoutInterface::getInitialValues () const pure virtual
Implemented in CCopasiSpringLayout.
Referenced by CLayoutEngine::CLayoutEngine().
const std::vector< double > & CAbstractLayoutInterface::getMassVector () const virtual
Definition at line 27 of file CAbstractLayoutInterface.cpp.
References mMassVector.
Referenced by CLayoutEngine::calcRHS().
 {
   return mMassVector;
 }
unsigned int CAbstractLayoutInterface::getNumVariables () const
Definition at line 17 of file CAbstractLayoutInterface.cpp.
References mVarDescription.
Referenced by CLayoutEngine::calcForces(), and CLayoutEngine::calcRHS().
 {
   return mVarDescription.size();
 }
virtual double CAbstractLayoutInterface::getPotential () pure virtual
Implemented in CCopasiSpringLayout.
Referenced by CLayoutEngine::calcForces(), and CLayoutEngine::step().
const std::vector< CAbstractLayoutInterface::VariableDescription > & CAbstractLayoutInterface::getVariablesDescription () const
Definition at line 22 of file CAbstractLayoutInterface.cpp.
References mVarDescription.
 {
   return mVarDescription;
 }
virtual bool CAbstractLayoutInterface::setState (const std::vector< double > & vars) pure virtual
Implemented in CCopasiSpringLayout.
Referenced by CLayoutEngine::calcForces(), CLayoutEngine::step(), and CLayoutEngine::stepIntegration().
Member Data Documentation
std::vector<double> CAbstractLayoutInterface::mMassVector protected
Definition at line 43 of file CAbstractLayoutInterface.h.
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addPositionVariables(), CCopasiSpringLayout::addReactionVariables(), CCopasiSpringLayout::createVariables(), and getMassVector().
std::vector<VariableDescription> CAbstractLayoutInterface::mVarDescription protected
Definition at line 42 of file CAbstractLayoutInterface.h.
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addPositionVariables(), CCopasiSpringLayout::addReactionVariables(), CCopasiSpringLayout::createVariables(), getNumVariables(), getVariablesDescription(), and CCopasiSpringLayout::setState().
The documentation for this class was generated from the following files:
CAbstractLayoutInterface.h
CAbstractLayoutInterface.cpp