COPASI API: CLyapProblem Class Reference
CLyapProblem Class Reference
#include <CLyapProblem.h>
Public Member Functions
CLyapProblem (const CCopasiContainer *pParent=NULL)
CLyapProblem (const CLyapProblem &src, const CCopasiContainer *pParent=NULL)
bool divergenceRequested () const
virtual bool elevateChildren ()
const unsigned C_INT32 & getExponentNumber () const
const C_FLOAT64 & getTransientTime () const
virtual void printResult (std::ostream *ostream) const
void setDivergenceRequested (bool flag)
void setExponentNumber (const unsigned C_INT32 &number)
void setTransientTime (const C_FLOAT64 &endTime)
~CLyapProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual bool initialize ()
virtual void print (std::ostream *ostream) const
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setModel (CModel *pModel)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initializeParameter ()
Private Attributes
bool * mpDivergenceRequested
unsigned C_INT32 * mpExponentNumber
C_FLOAT64 * mpTransientTime
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CLyapProblem class.
Definition at line 25 of file CLyapProblem.h.
Constructor & Destructor Documentation
CLyapProblem::CLyapProblem (const CCopasiContainer * pParent = NULL)
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
CLyapProblem class. Default constructor.
Definition at line 35 of file CLyapProblem.cpp.
References CONSTRUCTOR_TRACE, and initializeParameter().
                                                           :
     CCopasiProblem(CCopasiTask::lyap, pParent),
     mpExponentNumber(NULL),
     //mpTimeSeriesRequested(NULL),
     mpDivergenceRequested(NULL),
     mpTransientTime(NULL)
 {
   initializeParameter();
   CONSTRUCTOR_TRACE;
 }
CLyapProblem::CLyapProblem (const CLyapProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CTrajectoryProblem & src CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CLyapProblem & src
Definition at line 50 of file CLyapProblem.cpp.
References CONSTRUCTOR_TRACE, and initializeParameter().
                                                             :
     CCopasiProblem(src, pParent),
     mpExponentNumber(NULL),
     //mpTimeSeriesRequested(NULL),
     mpDivergenceRequested(NULL),
     mpTransientTime(NULL)
 {
   initializeParameter();
   CONSTRUCTOR_TRACE;
 }
CLyapProblem::~CLyapProblem ()
Destructor.
Definition at line 65 of file CLyapProblem.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
bool CLyapProblem::divergenceRequested () const
Definition at line 115 of file CLyapProblem.cpp.
References mpDivergenceRequested.
Referenced by CLyapMethod::isValidProblem(), CQLyapWidget::loadTask(), CLyapTask::printResult(), CLyapTask::process(), CQLyapWidget::saveTask(), and CLyapWolfMethod::start().
 {return *mpDivergenceRequested;}
bool CLyapProblem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 68 of file CLyapProblem.cpp.
Referenced by initializeParameter().
 {
   return true;
 }
const unsigned C_INT32 & CLyapProblem::getExponentNumber () const
Retrieve the number of exponents to calculate.
Returns
"const unsigned C_INT32 &"
Definition at line 90 of file CLyapProblem.cpp.
References mpExponentNumber.
Referenced by CLyapTask::calculationsBeforeOutput(), CLyapTask::initialize(), CLyapMethod::isValidProblem(), CQLyapResultWidget::loadFromBackend(), CQLyapWidget::loadTask(), CLyapTask::printResult(), CLyapTask::process(), CQLyapWidget::saveTask(), and CLyapWolfMethod::start().
 {return *mpExponentNumber;}
const C_FLOAT64 & CLyapProblem::getTransientTime () const
Retrieve the end time.
Returns
"const C_FLOAT64 &" endTime
Definition at line 98 of file CLyapProblem.cpp.
References mpTransientTime.
Referenced by CLyapWolfMethod::calculate(), CLyapWolfMethod::isValidProblem(), CQLyapWidget::loadTask(), and CQLyapWidget::saveTask().
 {return *mpTransientTime;}
void CLyapProblem::initializeParameter () private
Load a trajectory problem
Parameters
CReadConfig & configBuffer
"CReadConfig::Mode mode (Default: CReadConfig::NEXT) Allocates all group parameters and assures that they are properly initialized.
Definition at line 73 of file CLyapProblem.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::DOUBLE, elevateChildren(), CCopasiParameter::getValue(), mpDivergenceRequested, mpExponentNumber, mpTransientTime, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pUINT, and CCopasiParameter::UINT.
Referenced by CLyapProblem().
 {
   mpExponentNumber =
     assertParameter("ExponentNumber", CCopasiParameter::UINT, (unsigned C_INT32) 3)->getValue().pUINT;
   mpDivergenceRequested =
     assertParameter("DivergenceRequested", CCopasiParameter::BOOL, (bool) true)->getValue().pBOOL;
   mpTransientTime =
     assertParameter("TransientTime", CCopasiParameter::DOUBLE, (C_FLOAT64) 0.0)->getValue().pDOUBLE;
   elevateChildren();
 }
void CLyapProblem::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implmented." To overide this default behaviour one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Definition at line 118 of file CLyapProblem.cpp.
References CCopasiObject::getObjectParent(), and CLyapTask::printResult().
 {
   CLyapTask* parent = dynamic_cast<CLyapTask*>(getObjectParent());
   if (!parent) return;
   parent->printResult(ostream);
 }
void CLyapProblem::setDivergenceRequested (bool flag)
Definition at line 110 of file CLyapProblem.cpp.
References mpDivergenceRequested.
Referenced by CQLyapWidget::saveTask().
 {
   *mpDivergenceRequested = flag;
 }
void CLyapProblem::setExponentNumber (const unsigned C_INT32 & number)
Set the number of exponents to calculate
Parameters
const unsigned C_INT32 &
Definition at line 85 of file CLyapProblem.cpp.
References mpExponentNumber.
Referenced by CQLyapWidget::saveTask().
 {
   *mpExponentNumber = number;
 }
void CLyapProblem::setTransientTime (const C_FLOAT64 & endTime)
Set the end time.
Parameters
const C_FLOAT64 & endTime
Definition at line 93 of file CLyapProblem.cpp.
References mpTransientTime.
Referenced by CQLyapWidget::saveTask().
 {
   *mpTransientTime = startTime;
 }
Member Data Documentation
bool* CLyapProblem::mpDivergenceRequested private
whether the divergence should also be calculated
Definition at line 42 of file CLyapProblem.h.
Referenced by divergenceRequested(), initializeParameter(), and setDivergenceRequested().
unsigned C_INT32* CLyapProblem::mpExponentNumber private
Number of exponents to calculate. 0 means all.
Definition at line 32 of file CLyapProblem.h.
Referenced by getExponentNumber(), initializeParameter(), and setExponentNumber().
C_FLOAT64* CLyapProblem::mpTransientTime private
Indicates at which point of time the calculation of exponents should be started.
Definition at line 48 of file CLyapProblem.h.
Referenced by getTransientTime(), initializeParameter(), and setTransientTime().
The documentation for this class was generated from the following files:
CLyapProblem.h
CLyapProblem.cpp