COPASI API: CTSSATask.cpp File Reference
CTSSATask.cpp File Reference
#include <string>
#include "copasi.h"
#include "CTSSATask.h"
#include "CTSSAProblem.h"
#include "CTSSAMethod.h"
#include "model/CModel.h"
#include "model/CState.h"
#include "report/CKeyFactory.h"
#include "report/CReport.h"
#include "utilities/CProcessReport.h"
#include "utilities/CCopasiException.h"
#include "CopasiDataModel/CCopasiDataModel.h"
Macros
#define XXXX_Reporting
Functions
bool tbl (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
bool tble (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
bool tfl (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
bool tfle (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
Macro Definition Documentation
#define XXXX_Reporting
CTSSATask class.
This class implements a time scale separation analysis task which is comprised of a of a problem and a method. Additionally calls to the reporting methods are done when initialized.
Definition at line 39 of file CTSSATask.cpp.
Function Documentation
bool tbl (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 50 of file CTSSATask.cpp.
Referenced by CTSSATask::process().
 {return (d1 > d2);}
bool tble (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 47 of file CTSSATask.cpp.
Referenced by CTSSATask::process().
 {return (d1 >= d2);}
bool tfl (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 44 of file CTSSATask.cpp.
Referenced by CTSSATask::process().
 {return (d1 < d2);}
bool tfle (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 41 of file CTSSATask.cpp.
Referenced by CTSSATask::process().
 {return (d1 <= d2);}