COPASI API: CState Class Reference
CState Class Reference
#include <CState.h>
Public Member Functions
C_FLOAT64 * beginDependent ()
const C_FLOAT64 * beginDependent () const
C_FLOAT64 * beginFixed ()
const C_FLOAT64 * beginFixed () const
C_FLOAT64 * beginIndependent ()
const C_FLOAT64 * beginIndependent () const
CState ()
CState (const CState &src)
C_FLOAT64 * endDependent ()
const C_FLOAT64 * endDependent () const
C_FLOAT64 * endFixed ()
const C_FLOAT64 * endFixed () const
C_FLOAT64 * endIndependent ()
const C_FLOAT64 * endIndependent () const
size_t getNumDependent () const
size_t getNumFixed () const
size_t getNumIndependent () const
size_t getNumVariable () const
const C_FLOAT64 & getTime () const
bool isValid () const
CState & operator= (const CState &rhs)
void setTime (const C_FLOAT64 &time)
~CState ()
Protected Member Functions
C_FLOAT64 * resize (const size_t &size)
void updateIterator (const size_t &numIndependent, const size_t &numDependent, const size_t &numFixed)
Private Attributes
C_FLOAT64 * mpBeginDependent
C_FLOAT64 * mpBeginFixed
C_FLOAT64 * mpBeginIndependent
C_FLOAT64 * mpEnd
C_FLOAT64 * mpValues
size_t mSize
bool mUpdateDependentRequired
Friends
class CStateTemplate
std::ostream & operator<< (std::ostream &os, const CState &s)
Detailed Description
Definition at line 305 of file CState.h.
Constructor & Destructor Documentation
CState::CState ()
Constructor
Definition at line 279 of file CState.cpp.
               :
     mpValues(NULL),
     mSize(0),
     mpBeginIndependent(NULL),
     mpBeginDependent(NULL),
     mpBeginFixed(NULL),
     mpEnd(NULL),
     mUpdateDependentRequired(false)
 {}
CState::CState (const CState & src)
Copy constructor
Parameters
const CState & src
Definition at line 289 of file CState.cpp.
References C_FLOAT64, mpValues, and mSize.
                                 :
     mpValues(new C_FLOAT64[src.mSize]),
     mSize(src.mSize),
     mpBeginIndependent(mpValues + (src.mpBeginIndependent - src.mpValues)),
     mpBeginDependent(mpValues + (src.mpBeginDependent - src.mpValues)),
     mpBeginFixed(mpValues + (src.mpBeginFixed - src.mpValues)),
     mpEnd(mpValues + (src.mpEnd - src.mpValues)),
     mUpdateDependentRequired(src.mUpdateDependentRequired)
 {
   memcpy(mpValues, src.mpValues, sizeof(C_FLOAT64) * mSize);
 }
CState::~CState ()
Destructor
Definition at line 301 of file CState.cpp.
References mpValues, and pdeletev.
 {pdeletev(mpValues);}
Member Function Documentation
C_FLOAT64 * CState::beginDependent ()
Retrieve the array of pointers of values of all dependent entities, which are only dependent species for a reduced model.
Returns
C_FLOAT64 * dependentValues
Definition at line 330 of file CState.cpp.
References mpBeginDependent.
Referenced by CHybridMethodODE45::outputState(), and CModel::updateSimulatedValues().
 {return mpBeginDependent;}
const C_FLOAT64 * CState::beginDependent () const
Retrieve the array of pointers of values of all dependent entities, which are only dependent species for a reduced model.
Returns
const C_FLOAT64 * dependentValues
Definition at line 337 of file CState.cpp.
References mpBeginDependent.
 {return mpBeginDependent;}
C_FLOAT64 * CState::beginFixed ()
Retrieve the array of pointers of values of all fixed entities.
Returns
C_FLOAT64 * fixedValues
Definition at line 332 of file CState.cpp.
References mpBeginFixed.
Referenced by CHybridMethodODE45::outputState(), and CLsodaMethod::stateChanged().
 {return mpBeginFixed;}
const C_FLOAT64 * CState::beginFixed () const
Retrieve the array of pointers of values of all fixed entities.
Returns
const C_FLOAT64 * fixedValues
Definition at line 339 of file CState.cpp.
References mpBeginFixed.
 {return mpBeginFixed;}
C_FLOAT64 * CState::beginIndependent ()
Retrieve the array of pointers of values of all independent entities.
Returns
C_FLOAT64 * independentValues
Definition at line 328 of file CState.cpp.
References mpBeginIndependent.
Referenced by CSteadyStateMethod::allPositive(), CLyapWolfMethod::calculate(), CModel::calculateJacobian(), CModel::calculateJacobianX(), CMathModel::calculateRootJacobian(), CNewtonMethod::containsNaN(), CHybridMethodODE45::doInverseInterpolation(), CTauLeapMethod::doSingleStep(), CCopasiXMLParser::InitialStateElement::end(), CLyapWolfMethod::evalF(), CHybridMethodODE45::evalF(), CHybridMethodLSODA::integrateDeterministicPart(), CHybridMethodODE45::integrateDeterministicPart(), CTSSAMethod::integrationMethodStart(), CTrajectoryMethodDsaLsodar::CPartition::intialize(), CHybridMethodODE45::outputState(), CLsodaMethod::peekAhead(), CNewtonMethod::processInternal(), CCrossSectionTask::relativeDifferenceOfStates(), CTrajectoryMethodDsaLsodar::CPartition::rePartition(), CNewtonMethod::solveJacobianXeqB(), CTauLeapMethod::start(), CStochDirectMethod::start(), CLyapWolfMethod::start(), CTrajAdaptiveSA::start(), CLsodaMethod::start(), CTrajectoryMethodDsaLsodar::start(), CLsodaMethod::stateChanged(), CHybridMethod::step(), CHybridMethodLSODA::step(), CStochMethod::step(), CNewtonMethod::targetFunction(), and CTauLeapMethod::updateSystem().
 {return mpBeginIndependent;}
const C_FLOAT64 * CState::beginIndependent () const
Retrieve the array of pointers of values of all independent entities.
Returns
const C_FLOAT64 * independentValues
Definition at line 335 of file CState.cpp.
References mpBeginIndependent.
 {return mpBeginIndependent;}
C_FLOAT64 * CState::endDependent ()
Retrieve pointer just beyond the values of all dependent entities.
Returns
C_FLOAT64 * endDependentValues
Definition at line 331 of file CState.cpp.
References mpBeginFixed.
Referenced by CSteadyStateMethod::allPositive(), and CHybridMethodODE45::outputState().
 {return mpBeginFixed;}
const C_FLOAT64 * CState::endDependent () const
Retrieve pointer just beyond the values of all dependent entities.
Returns
const C_FLOAT64 * endDependentValues
Definition at line 338 of file CState.cpp.
References mpBeginFixed.
 {return mpBeginFixed;}
C_FLOAT64 * CState::endFixed ()
Retrieve pointer just beyond the values of all fixed entities.
Returns
C_FLOAT64 * endFixedValues
Definition at line 333 of file CState.cpp.
References mpEnd.
Referenced by CHybridMethodODE45::outputState(), and CLsodaMethod::stateChanged().
 {return mpEnd;}
const C_FLOAT64 * CState::endFixed () const
Retrieve pointer just beyond the values of all fixed entities.
Returns
const C_FLOAT64 * endFixedValues
Definition at line 340 of file CState.cpp.
References mpEnd.
 {return mpEnd;}
C_FLOAT64 * CState::endIndependent ()
Retrieve pointer just beyond the values of all independent entities.
Returns
C_FLOAT64 * endIndependentValues
Definition at line 329 of file CState.cpp.
References mpBeginDependent.
Referenced by CNewtonMethod::containsNaN(), CHybridMethodODE45::outputState(), and CCrossSectionTask::relativeDifferenceOfStates().
 {return mpBeginDependent;}
const C_FLOAT64 * CState::endIndependent () const
Retrieve pointer just beyond the values of all independent entities.
Returns
const C_FLOAT64 * endIndependentValues
Definition at line 336 of file CState.cpp.
References mpBeginDependent.
 {return mpBeginDependent;}
size_t CState::getNumDependent () const
Retrieve the number of dependent entities.
Returns
size_t numDependent
Definition at line 344 of file CState.cpp.
References mpBeginDependent, and mpBeginFixed.
Referenced by CSteadyStateTask::initialize(), CHybridMethodODE45::outputState(), and resize().
 {return mpBeginFixed - mpBeginDependent;}
size_t CState::getNumFixed () const
Retrieve the number of fixed entities.
Returns
size_t numFixed
Definition at line 348 of file CState.cpp.
References mpBeginFixed, and mpEnd.
Referenced by resize().
 {return mpEnd - mpBeginFixed;}
size_t CState::getNumIndependent () const
Retrieve the number of independent entities.
Returns
size_t numIndependent
Definition at line 342 of file CState.cpp.
References mpBeginDependent, and mpBeginIndependent.
Referenced by CModel::calculateJacobian(), CModel::calculateJacobianX(), CMathModel::calculateRootJacobian(), CSteadyStateTask::initialize(), CTSSAMethod::integrationMethodStart(), CLyapMethod::isValidProblem(), CHybridMethodODE45::outputState(), CLyapTask::process(), resize(), CLyapWolfMethod::start(), and CLsodaMethod::start().
 {return mpBeginDependent - mpBeginIndependent;}
size_t CState::getNumVariable () const
Retrieve the number of variable entities, i.e., the sum of independent and dependent variables.
Returns
size_t numVariable
Definition at line 346 of file CState.cpp.
References mpBeginFixed, and mpBeginIndependent.
 {return mpBeginFixed - mpBeginIndependent;}
const C_FLOAT64 & CState::getTime () const
Retrieve the time of the state
Returns
const C_FLOAT64 & time
Definition at line 325 of file CState.cpp.
References mpValues.
Referenced by CHybridMethodODE45::doSingleStep(), CTrajectoryMethodDsaLsodar::fireReaction(), CTSSATask::initialize(), CTrajectoryTask::initialize(), CCrossSectionTask::initialize(), CHybridMethodLSODA::integrateDeterministicPart(), CHybridMethodODE45::integrateDeterministicPart(), CTSSAMethod::integrationMethodStart(), CTimeSeries::output(), CHybridMethod::outputData(), CHybridMethodLSODA::outputData(), CHybridMethod::outputDebug(), CHybridMethodODE45::outputDebug(), CHybridMethodLSODA::outputDebug(), CHybridMethodODE45::outputState(), CHybridMethod::partitionSystem(), CLsodaMethod::peekAhead(), CSteadyStateTask::process(), CHybridMethod::start(), CStochDirectMethod::start(), CLyapWolfMethod::start(), CTrajAdaptiveSA::start(), CStochMethod::start(), CLsodaMethod::start(), CLsodaMethod::stateChanged(), CTauLeapMethod::step(), CHybridMethod::step(), CStochDirectMethod::step(), CTrajAdaptiveSA::step(), CStochMethod::step(), CLsodaMethod::step(), and CTrajectoryMethodDsaLsodar::step().
 {return *mpValues;}
bool CState::isValid () const
Check whether the current state is valid (contains no NaN)
Returns
bool isValid
Definition at line 351 of file CState.cpp.
References C_FLOAT64, mpBeginDependent, and mpBeginIndependent.
Referenced by CSteadyStateTask::process(), and CLsodaMethod::step().
 {
   const C_FLOAT64 * pIt = mpBeginIndependent;
   const C_FLOAT64 * pEnd = mpBeginDependent;
   for (; pIt != pEnd; ++pIt)
     {
       if (isnan(*pIt))
         return false;
     }
   return true;
 }
CState & CState::operator= (const CState & rhs)
Assignment operator
Parameters
const CState & rhs
Returns
CState & lhs
Definition at line 303 of file CState.cpp.
References C_FLOAT64, mpBeginDependent, mpBeginFixed, mpBeginIndependent, mpEnd, mpValues, mSize, mUpdateDependentRequired, and pdeletev.
 {
   if (this != &rhs)
     {
       if (mSize != rhs.mSize)
         {
           pdeletev(mpValues);
           mpValues = new C_FLOAT64[rhs.mSize];
           mSize = rhs.mSize;
         }
       memcpy(mpValues, rhs.mpValues, sizeof(C_FLOAT64) * mSize);
       mpBeginIndependent = mpValues + (rhs.mpBeginIndependent - rhs.mpValues);
       mpBeginDependent = mpValues + (rhs.mpBeginDependent - rhs.mpValues);
       mpBeginFixed = mpValues + (rhs.mpBeginFixed - rhs.mpValues);
       mpEnd = mpValues + (rhs.mpEnd - rhs.mpValues);
       mUpdateDependentRequired = rhs.mUpdateDependentRequired;
     }
   return *this;
 }
C_FLOAT64 * CState::resize (const size_t & size) protected
Definition at line 365 of file CState.cpp.
References C_FLOAT64, getNumDependent(), getNumFixed(), getNumIndependent(), min, mpValues, mSize, pdeletev, and updateIterator().
Referenced by CStateTemplate::resize().
 {
   if (mSize != size)
     {
       C_FLOAT64 * pTmp = mpValues;
       if (size > 0)
         {
           mpValues = new C_FLOAT64[size];
           memcpy(mpValues, pTmp, sizeof(C_FLOAT64) * std::min(mSize, size));
         }
       else
         mpValues = NULL;
       pdeletev(pTmp);
       mSize = size;
     }
   updateIterator(getNumIndependent(), getNumDependent(), getNumFixed());
   return mpValues;
 }
void CState::setTime (const C_FLOAT64 & time)
Set the time of the state
Parameters
const C_FLOAT64 & time
Definition at line 326 of file CState.cpp.
References mpValues.
Referenced by CLyapWolfMethod::calculate(), CHybridMethodODE45::doInverseInterpolation(), CHybridNextReactionLSODAMethod::doSingleStep(), CHybridNextReactionRKMethod::doSingleStep(), CHybridMethodODE45::doSingleStep(), CTrajectoryMethodDsaLsodar::doSingleStep(), CTrajAdaptiveSA::doSingleTauLeapStep(), CLyapWolfMethod::evalF(), CLsodaMethod::evalF(), CHybridMethodLSODA::evalF(), CHybridMethodODE45::evalF(), CTrajectoryMethodDsaLsodar::evalF(), CTSSAMethod::evalF(), CLsodaMethod::evalR(), CHybridMethodLSODA::integrateDeterministicPart(), CHybridMethodODE45::integrateDeterministicPart(), CTSSAMethod::integrationStep(), CLsodaMethod::peekAhead(), CSteadyStateTask::process(), CModel::setInitialState(), CTauLeapMethod::step(), CHybridMethod::step(), CHybridMethodLSODA::step(), CStochDirectMethod::step(), CLyapWolfMethod::step(), CTrajAdaptiveSA::step(), CStochMethod::step(), CLsodaMethod::step(), and CTrajectoryMethodDsaLsodar::step().
 {*mpValues = time;}
void CState::updateIterator (const size_t & numIndependent, const size_t & numDependent, const size_t & numFixed) protected
Update the pointers to the different types of entities
Parameters
const size_t & numIndependent
const size_t & numDependent
const size_t & numFixed
Definition at line 388 of file CState.cpp.
References mpBeginDependent, mpBeginFixed, mpBeginIndependent, mpEnd, and mpValues.
Referenced by CStateTemplate::reorder(), and resize().
 {
   mpBeginIndependent = mpValues + 1; // One for Time
   mpBeginDependent = mpBeginIndependent + numIndependent;
   mpBeginFixed = mpBeginDependent + numDependent;
   mpEnd = mpBeginFixed + numFixed;
 }
Friends And Related Function Documentation
friend class CStateTemplate friend
Definition at line 453 of file CState.h.
std::ostream& operator<< (std::ostream & os, const CState & s) friend
Definition at line 398 of file CState.cpp.
 {
   os << "(";
   const C_FLOAT64 * pValue = s.mpValues;
   for (; pValue != s.mpEnd; ++pValue)
     {
       os << "\t" << *pValue;
     }
   os << "\t)";
   return os;
 }
Member Data Documentation
C_FLOAT64* CState::mpBeginDependent private
Pointer to the beginning of values of dependent entities.
Definition at line 485 of file CState.h.
Referenced by beginDependent(), endIndependent(), getNumDependent(), getNumIndependent(), isValid(), operator=(), and updateIterator().
C_FLOAT64* CState::mpBeginFixed private
Pointer to the beginning of values of fixed entities.
Definition at line 490 of file CState.h.
Referenced by beginFixed(), endDependent(), getNumDependent(), getNumFixed(), getNumVariable(), operator=(), and updateIterator().
C_FLOAT64* CState::mpBeginIndependent private
Pointer to the beginning of values of independent entities.
Definition at line 480 of file CState.h.
Referenced by beginIndependent(), getNumIndependent(), getNumVariable(), isValid(), operator=(), and updateIterator().
C_FLOAT64* CState::mpEnd private
Pointer just beyond the values of fixed entities.
Definition at line 495 of file CState.h.
Referenced by endFixed(), getNumFixed(), operator<<(), operator=(), and updateIterator().
C_FLOAT64* CState::mpValues private
Array of entity values
Definition at line 470 of file CState.h.
Referenced by CState(), getTime(), operator<<(), operator=(), resize(), setTime(), updateIterator(), and ~CState().
size_t CState::mSize private
Size of the state
Definition at line 475 of file CState.h.
Referenced by CState(), operator=(), and resize().
bool CState::mUpdateDependentRequired private
Indicates whether the state is of a reduced or complete model
Definition at line 500 of file CState.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
CState.h
CState.cpp