COPASI API: pvmtest.cpp File Reference
pvmtest.cpp File Reference
#include "copasi.h"
#include "utilities/CGlobals.h"
#include "optimization/COptMethod.h"
#include "optimization/CRealProblem.h"
#include "utilities/CCopasiException.h"
#include "report/CCopasiRootContainer.h"
Macros
#define COPASI_MAIN
Functions
C_INT main (C_INT argc, char *argv[])
C_INT32 TestOptimization (void)
Macro Definition Documentation
#define COPASI_MAIN
Definition at line 18 of file pvmtest.cpp.
Function Documentation
C_INT main (C_INT argc, char * argv[])
Definition at line 29 of file pvmtest.cpp.
References CCopasiException::getMessage(), CCopasiMessage::getText(), pdelete, CCopasiObject::Root, and TestOptimization().
 {
   cout << "Starting main program." << endl;
   CCopasiContainer::init();
   Copasi = new CGlobals;
   Copasi->setArguments(argc, argv);
   try
     {
       TestOptimization();
     }
   catch (CCopasiException Exception)
     {
       cout << Exception.getMessage().getText() << endl;
     }
   pdelete(Copasi);
   pdelete(CCopasiRootContainer::Root);
   cout << "Leaving main program." << endl;
   return 0;
 } // end of main
C_INT32 TestOptimization (void)
Definition at line 55 of file pvmtest.cpp.
References COptMethod::createMethod(), COptMethod::optimise(), pdelete, COptMethod::setProblem(), and CCopasiParameterGroup::setValue().
Referenced by main().
 {
   int i, num_params;
   cout << "TestOptimization() begins --- " << endl;
   COptMethod * CRand = COptMethod::createMethod();
   CRealProblem *CReal = new CRealProblem();
   CRand->setProblem(CReal);
   // set parameter numbers....
   /**** hard coded num of params ***/
   num_params = 10;
   CReal->setParameterNum(num_params);
   // set the individual parameters
   CRand->setValue(0, 100000);
   for (i = 0; i < num_params; i++)
     {
       CReal->setParameterMin(i, -5);
       CReal->setParameterMax(i, 2);
     }
   CRand->optimise();
   cout << "result---best values";
   for (i = 0; i < num_params; i++)
     {
       cout << CReal->getBestValue(i);
       cout << "\n";
     }
   pdelete(CRand);
   return 0;
 }