COPASI API: CScanContainerWidget Class Reference
CScanContainerWidget Class Reference
#include <CScanContainerWidget.h>
Signals
void copyWidget (int)
void itemDeleted ()
Public Member Functions
void addWidget (QWidget *widget, bool controls=true)
void clearWidgetList ()
CScanContainerWidget (QWidget *parent=0, const char *name=0)
void enableCopy (const bool &enable)
std::vector< QWidget * > getWidgetList () const
void insertWidget (QWidget *widget, int row=-1)
~CScanContainerWidget ()
Protected Slots
void slotCopy (int index)
void slotDel (int index)
void slotDown (int index)
void slotUp (int index)
Protected Member Functions
void resizeEvent (QResizeEvent *event)
void updateIndices ()
void updateTable ()
Protected Attributes
bool mCopyEnabled
Detailed Description
This widget is a table that contains other widgets (arranged vertically) it adds buttons to delete, move up or down the widgets
Definition at line 33 of file CScanContainerWidget.h.
Constructor & Destructor Documentation
CScanContainerWidget::CScanContainerWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 27 of file CScanContainerWidget.cpp.
References mCopyEnabled.
                                                                               :
   QTableWidget(parent)
 {
   if (!name)
     setObjectName("CScanContainerWidget");
   horizontalHeader()->setStretchLastSection(true);
   horizontalHeader()->hide();
   verticalHeader()->hide();
   setShowGrid(false);
   setColumnCount(2);
   setAutoScroll(true);
   setSelectionMode(QAbstractItemView::NoSelection);
   mCopyEnabled = false;
   //TODO maybe reimplement paintFocus() to make the focus completely invisible
   // (it is already invisible most of the time)
 }
CScanContainerWidget::~CScanContainerWidget ()
Definition at line 50 of file CScanContainerWidget.cpp.
 {}
Member Function Documentation
void CScanContainerWidget::addWidget (QWidget * widget, bool controls = true)
Definition at line 76 of file CScanContainerWidget.cpp.
References CUpDownSubwidget::enableCopy(), mCopyEnabled, CUpDownSubwidget::setIndex(), slotCopy(), slotDel(), slotDown(), slotUp(), updateIndices(), and updateTable().
Referenced by ScanWidget::loadTask().
 {
   setRowCount(rowCount() + 1);
   int i = rowCount() - 1;
   if (controls) //add control widget
     {
       CUpDownSubwidget * tmpUD = new CUpDownSubwidget(this);
       tmpUD->setIndex(i, false, true); //assumes...
       tmpUD->enableCopy(mCopyEnabled);
       connect(tmpUD, SIGNAL(del(int)), this, SLOT(slotDel(int)));
       connect(tmpUD, SIGNAL(up(int)), this, SLOT(slotUp(int)));
       connect(tmpUD, SIGNAL(down(int)), this, SLOT(slotDown(int)));
       connect(tmpUD, SIGNAL(copy(int)), this, SLOT(slotCopy(int)));
       setCellWidget(i, 0, tmpUD);
       //tell the widget above that it is not the last anymore
       if (i > 0)
         {
           CUpDownSubwidget* tmpWidget = dynamic_cast<CUpDownSubwidget*>(cellWidget(i - 1, 0));
           if (tmpWidget)
             tmpWidget->setIndex(i - 1, false, false); //assumes...
         }
     }
   setCellWidget(i, 1, widget);
   updateIndices();
   updateTable();
 }
void CScanContainerWidget::clearWidgetList ()
Definition at line 71 of file CScanContainerWidget.cpp.
Referenced by ScanWidget::loadTask().
 {
   setRowCount(0);
 }
void CScanContainerWidget::copyWidget (int) signal
Referenced by slotCopy().
void CScanContainerWidget::enableCopy (const bool & enable)
Definition at line 219 of file CScanContainerWidget.cpp.
References mCopyEnabled.
 {mCopyEnabled = enable;}
std::vector< QWidget * > CScanContainerWidget::getWidgetList () const
Definition at line 53 of file CScanContainerWidget.cpp.
Referenced by ScanWidget::saveTask().
 {
   std::vector< QWidget * > ret;
   QWidget* tmpWidget;
   int i, imax = rowCount();
   for (i = 0; i < imax; ++i)
     {
       tmpWidget = cellWidget(i, 1);
       if (tmpWidget)
         ret.push_back(tmpWidget);
     }
   return ret;
 }
void CScanContainerWidget::insertWidget (QWidget * widget, int row = -1)
Definition at line 109 of file CScanContainerWidget.cpp.
References C_INT32, CUpDownSubwidget::enableCopy(), mCopyEnabled, slotCopy(), slotDel(), slotDown(), slotUp(), updateIndices(), and updateTable().
Referenced by ScanWidget::slotAddItem(), and slotDown().
 {
   if (row == -1)
     {
       if (rowCount() == 0)
         row = 0;
       else
         row = rowCount() - 1;
     }
   insertRow(row);
   unsigned C_INT32 i = row;
   if (true) //add control widget
     {
       CUpDownSubwidget * tmpUD = new CUpDownSubwidget(this);
       tmpUD->enableCopy(mCopyEnabled);
       connect(tmpUD, SIGNAL(del(int)), this, SLOT(slotDel(int)));
       connect(tmpUD, SIGNAL(up(int)), this, SLOT(slotUp(int)));
       connect(tmpUD, SIGNAL(down(int)), this, SLOT(slotDown(int)));
       connect(tmpUD, SIGNAL(copy(int)), this, SLOT(slotCopy(int)));
       setCellWidget(i, 0, tmpUD);
     }
   setCellWidget(i, 1, widget);
   updateIndices();
   updateTable();
 }
void CScanContainerWidget::itemDeleted () signal
void CScanContainerWidget::resizeEvent (QResizeEvent * event) protected
Definition at line 222 of file CScanContainerWidget.cpp.
 {
   QTableWidget::resizeEvent(e);
   resizeRowsToContents();
   resizeColumnsToContents();
 }
void CScanContainerWidget::slotCopy (int index) protected slot
Definition at line 187 of file CScanContainerWidget.cpp.
References copyWidget().
Referenced by addWidget(), and insertWidget().
 {emit copyWidget(index);}
void CScanContainerWidget::slotDel (int index) protected slot
Definition at line 179 of file CScanContainerWidget.cpp.
References updateIndices(), and updateTable().
Referenced by addWidget(), and insertWidget().
 {
   removeRow(index);
   updateIndices();
   updateTable();
 }
void CScanContainerWidget::slotDown (int index) protected slot
Definition at line 149 of file CScanContainerWidget.cpp.
References insertWidget().
Referenced by addWidget(), insertWidget(), and slotUp().
 {
   if (index >= rowCount() - 1) return; //do nothing
   QWidget * pWidget = cellWidget(index, 1);
   QWidget * pNewWidget = NULL;
   if (pWidget->objectName() == "CScanWidgetScan")
     {
       static_cast< CScanWidgetScan * >(pWidget)->save(NULL);
       pNewWidget = new CScanWidgetScan(*static_cast< CScanWidgetScan * >(pWidget), this);
     }
   else if (pWidget->objectName() == "CScanWidgetRandom")
     {
       static_cast< CScanWidgetRandom * >(pWidget)->save(NULL);
       pNewWidget = new CScanWidgetRandom(*static_cast< CScanWidgetRandom * >(pWidget), this);
     }
   else if (pWidget->objectName() == "CScanWidgetRepeat")
     {
       static_cast< CScanWidgetRepeat * >(pWidget)->save(NULL);
       pNewWidget = new CScanWidgetRepeat(*static_cast< CScanWidgetRepeat * >(pWidget), this);
     }
   if (pNewWidget != NULL)
     {
       removeRow(index);
       insertWidget(pNewWidget, index + 1);
     }
 }
void CScanContainerWidget::slotUp (int index) protected slot
Definition at line 142 of file CScanContainerWidget.cpp.
References slotDown().
Referenced by addWidget(), and insertWidget().
 {
   if (index <= 0) return; //do nothing
   slotDown(index - 1);
 }
void CScanContainerWidget::updateIndices () protected
Definition at line 190 of file CScanContainerWidget.cpp.
References C_INT32, and CUpDownSubwidget::setIndex().
Referenced by addWidget(), insertWidget(), and slotDel().
 {
   //update the indices of the updown widgets
   CUpDownSubwidget* tmp, *tmp_last, *tmp_next;
   C_INT32 i, imax = rowCount();
   for (i = 0; i < imax; ++i)
     {
       tmp_last = dynamic_cast<CUpDownSubwidget*>(cellWidget(i - 1, 0));
       tmp = dynamic_cast<CUpDownSubwidget*>(cellWidget(i, 0));
       tmp_next = dynamic_cast<CUpDownSubwidget*>(cellWidget(i + 1, 0));
       if (tmp)
         {
           tmp->setIndex(i, (tmp_last == NULL), (tmp_next == NULL));
         }
     }
 }
void CScanContainerWidget::updateTable () protected
Definition at line 211 of file CScanContainerWidget.cpp.
Referenced by addWidget(), insertWidget(), and slotDel().
 {
   qApp->processEvents();
   resizeRowsToContents();
   resizeColumnsToContents();
 }
Member Data Documentation
bool CScanContainerWidget::mCopyEnabled protected
Definition at line 58 of file CScanContainerWidget.h.
Referenced by addWidget(), CScanContainerWidget(), enableCopy(), and insertWidget().
The documentation for this class was generated from the following files:
CScanContainerWidget.h
CScanContainerWidget.cpp