COPASI API: CMathTrigger::CRootFinder Class Reference
CMathTrigger::CRootFinder Class Reference
#include <CMathTrigger.h>
Public Member Functions
void applyInitialValues ()
void calculateTrueValue ()
bool compile (std::vector< CCopasiContainer * > listOfContainer)
CRootFinder (const CCopasiContainer *pParent=NULL)
CRootFinder (const CRootFinder &src, const CCopasiContainer *pParent=NULL)
void determineDiscrete (const std::set< const CCopasiObject * > &stateVariables)
C_FLOAT64 * getRootValuePtr ()
CEvaluationNode * getTrueExpression () const
void initObjects ()
const bool & isDiscrete () const
const bool & isEquality () const
bool isTrue () const
void toggle (const C_FLOAT64 &time, const bool &equality, const bool &continous)
void toggle (const C_FLOAT64 &time)
virtual ~CRootFinder ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
bool mDiscrete
bool mEquality
C_FLOAT64 mLastToggleTime
C_FLOAT64 * mpRootValue
CExpression mRoot
C_FLOAT64 mTrue
Friends
class CMathTrigger
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 16 of file CMathTrigger.h.
Constructor & Destructor Documentation
CMathTrigger::CRootFinder::CRootFinder (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 14 of file CMathTrigger.cpp.
References initObjects().
                                                                      :
   CCopasiContainer("Root", pParent),
   mRoot("Expression", this),
   mpRootValue(NULL),
   mEquality(false),
   mDiscrete(false),
   mTrue(0.0),
   mLastToggleTime(std::numeric_limits< C_FLOAT64 >::quiet_NaN())
 {
   initObjects();
 }
CMathTrigger::CRootFinder::CRootFinder (const CRootFinder & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CRoot & src
"const CCopasiContainer * pParent (default: NULL)
Definition at line 26 of file CMathTrigger.cpp.
References initObjects().
                                                                          :
   CCopasiContainer(src, pParent),
   mRoot(src.mRoot, this),
   mpRootValue(NULL),
   mEquality(src.mEquality),
   mDiscrete(src.mDiscrete),
   mTrue(src.mTrue),
   mLastToggleTime(src.mLastToggleTime)
 {
   initObjects();
 }
CMathTrigger::CRootFinder::~CRootFinder () virtual
Destructor
Definition at line 39 of file CMathTrigger.cpp.
 {}
Member Function Documentation
void CMathTrigger::CRootFinder::applyInitialValues ()
Initialize all values of the math model with their initial values.
Definition at line 141 of file CMathTrigger.cpp.
References CMathTrigger::calculateTrueValue().
 {
   calculateTrueValue();
   mLastToggleTime = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
 }
void CMathTrigger::CRootFinder::calculateTrueValue ()
Determine the truth value for the initial conditions.
Definition at line 147 of file CMathTrigger.cpp.
Referenced by CMathModel::processRoots().
 {
   if ((*mpRootValue < 0.0) ||
       ((*mpRootValue <= 0.0) && !mEquality))
     {
       mTrue = 0.0;
     }
   else
     {
       mTrue = 1.0;
     }
 }
bool CMathTrigger::CRootFinder::compile (std::vector< CCopasiContainer * > listOfContainer)
Compile the root finder
Parameters
std::vector< CCopasiContainer * > listOfContainer
Definition at line 51 of file CMathTrigger.cpp.
 {
   bool success = true;
   success &= mRoot.compile(listOfContainer);
   return true;
 }
void CMathTrigger::CRootFinder::determineDiscrete (const std::set< const CCopasiObject * > & stateVariables)
Determine whether the root only changes during discrete events. The root must be compiled before calling this method.
Parameters
const std::set< const CCopasiObject *> & stateVariables
Definition at line 60 of file CMathTrigger.cpp.
 {
   mDiscrete = !mRoot.dependsOn(stateVariables);
 }
C_FLOAT64 * CMathTrigger::CRootFinder::getRootValuePtr ()
Retrieve a pointer to the current value of the root.
Definition at line 160 of file CMathTrigger.cpp.
 {
   return mpRootValue;
 }
CEvaluationNode * CMathTrigger::CRootFinder::getTrueExpression () const
Retrieve the expression evaluating the truth value
Returns
CEvalutionNode * trueExpression
Definition at line 80 of file CMathTrigger.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeNumber::DOUBLE, and CEvaluationNodeLogical::GT.
Referenced by CMathTrigger::compileGE(), CMathTrigger::compileGT(), CMathTrigger::compileLE(), and CMathTrigger::compileLT().
 {
   CEvaluationNode * pTrueExpression = NULL;
   pTrueExpression = new CEvaluationNodeLogical(CEvaluationNodeLogical::GT, "GT");
   pTrueExpression->addChild(new CEvaluationNodeObject(&mTrue));
   pTrueExpression->addChild(new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "0.5"));
   return pTrueExpression;
 }
void CMathTrigger::CRootFinder::initObjects ()
Initialize the contained object references.
Definition at line 42 of file CMathTrigger.cpp.
References CCopasiObject::addDirectDependency(), C_FLOAT64, CExpression::refresh(), and CCopasiObject::setRefresh().
Referenced by CRootFinder().
 {
   mpRootValue =
     (C_FLOAT64 *)mRoot.getObject(std::string("Reference=Value"))->getValuePointer();
   addDirectDependency(&mRoot);
   setRefresh(&mRoot, &CExpression::refresh);
 }
const bool & CMathTrigger::CRootFinder::isDiscrete () const
Check whether the root change only during discrete events.
Returns
const bool & isDiscrete
Definition at line 65 of file CMathTrigger.cpp.
 {
   return mDiscrete;
 }
const bool & CMathTrigger::CRootFinder::isEquality () const
Check whether the root is checked for equality.
Returns
const bool & isEquality
Definition at line 70 of file CMathTrigger.cpp.
 {
   return mEquality;
 }
bool CMathTrigger::CRootFinder::isTrue () const
Check whether the root's current state is true .
Returns
bool isTrue
Definition at line 75 of file CMathTrigger.cpp.
 {
   return mTrue > 0.5;
 }
void CMathTrigger::CRootFinder::toggle (const C_FLOAT64 & time, const bool & equality, const bool & continous)
Toggle the root status dependent on the processed equality status
Parameters
const C_FLOAT64 & time
const bool & equality
const bool & continuous
Definition at line 91 of file CMathTrigger.cpp.
 {
   // This function must only be called if we found a root, i.e., the
   // value of the root expression changes sign. In that case it is save
   // to toggle the activity.
   if (continous &&
       !isnan(mLastToggleTime) &&
       mLastToggleTime == time)
     {
       return;
     }
   if (mDiscrete &&
       equality == true)
     {
       mTrue = (mTrue > 0.5) ? 0.0 : 1.0;
       mLastToggleTime = time;
     }
   else if (!mDiscrete)
     {
       if (equality == mEquality && mTrue < 0.5)
         {
           mTrue = 1.0;
           mLastToggleTime = time;
         }
       else if (equality != mEquality && mTrue > 0.5)
         {
           mTrue = 0.0;
           mLastToggleTime = time;
         }
     }
   return;
 }
void CMathTrigger::CRootFinder::toggle (const C_FLOAT64 & time)
Toggle the root status dependent on the processed equality status
Parameters
const C_FLOAT64 & time
Definition at line 129 of file CMathTrigger.cpp.
 {
   // This function must only be called if we found a root, i.e., the
   // value of the root expression changes sign. In that case it is save
   // to toggle the activity.
   mTrue = (mTrue > 0.5) ? 0.0 : 1.0;
   mLastToggleTime = time;
   return;
 }
Friends And Related Function Documentation
friend class CMathTrigger friend
Definition at line 18 of file CMathTrigger.h.
Member Data Documentation
bool CMathTrigger::CRootFinder::mDiscrete private
This indicates whether the root changes only discretely
Definition at line 136 of file CMathTrigger.h.
bool CMathTrigger::CRootFinder::mEquality private
This indicates whether the root is checked for equality
Definition at line 131 of file CMathTrigger.h.
Referenced by CMathTrigger::compileGE(), CMathTrigger::compileGT(), CMathTrigger::compileLE(), and CMathTrigger::compileLT().
C_FLOAT64 CMathTrigger::CRootFinder::mLastToggleTime private
The time at which the last toggle of the truth value occurred
Definition at line 147 of file CMathTrigger.h.
C_FLOAT64* CMathTrigger::CRootFinder::mpRootValue private
A pointer to the value of the root expression
Definition at line 126 of file CMathTrigger.h.
CExpression CMathTrigger::CRootFinder::mRoot private
This expression calculates the root
Definition at line 121 of file CMathTrigger.h.
Referenced by CMathTrigger::compileGE(), CMathTrigger::compileGT(), CMathTrigger::compileLE(), and CMathTrigger::compileLT().
C_FLOAT64 CMathTrigger::CRootFinder::mTrue private
Indicates the truth value of the root active This should be a bool but the CExpressionTree only handles double
Definition at line 142 of file CMathTrigger.h.
The documentation for this class was generated from the following files:
CMathTrigger.h
CMathTrigger.cpp