COPASI API: CCopasiXMLParser::SliderElement Class Reference
CCopasiXMLParser::SliderElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
SliderElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~SliderElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Slider = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3247 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::SliderElement::Element private
Enum of invoked parsers
Enumerator
Slider
Definition at line 3255 of file CCopasiXMLParser.h.
     {
       Slider = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::SliderElement::SliderElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 10662 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::SliderElement::~SliderElement () virtual
Destructor
Definition at line 10667 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::SliderElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 10757 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Slider:
         if (strcmp(pszName, "Slider"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Slider", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::SliderElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 10672 of file CCopasiXMLParser.cpp.
References CCopasiVector< T >::add(), C_FLOAT64, C_INT32, CSlider::convertScaleNameToScale(), CCopasiMessage::EXCEPTION, CSlider::Float, CKeyFactory::get(), CCopasiObject::getKey(), SCopasiXMLGUI::getSliderList(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pGUI, CSlider::setAssociatedEntityKey(), CSlider::setMaxValue(), CSlider::setMinValue(), CSlider::setScaling(), CSlider::setSliderObject(), CSlider::setSliderType(), CSlider::setSliderValue(), CSlider::setTickFactor(), CSlider::setTickNumber(), strToUnsignedInt(), toEnum(), CSlider::TypeName, and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   CSlider * pSlider = NULL;
   const char * Key;
   const char * AssociatedEntityKey;
   const char * ObjectCN;
   const char * objectType;
   CSlider::Type ObjectType;
   const char * tmp;
   C_FLOAT64 ObjectValue;
   C_FLOAT64 MinValue;
   C_FLOAT64 MaxValue;
   unsigned C_INT32 TickNumber;
   unsigned C_INT32 TickFactor;
   const char* scaling;
   switch (mCurrentElement)
     {
       case Slider:
         if (strcmp(pszName, "Slider"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Slider", mParser.getCurrentLineNumber());
         Key = mParser.getAttributeValue("key", papszAttrs);
         AssociatedEntityKey = mParser.getAttributeValue("associatedEntityKey", papszAttrs);
         ObjectCN = mParser.getAttributeValue("objectCN", papszAttrs);
         objectType = mParser.getAttributeValue("objectType", papszAttrs);
         ObjectType = toEnum(objectType, CSlider::TypeName, CSlider::Float);
         tmp = mParser.getAttributeValue("objectValue", papszAttrs);
         ObjectValue = CCopasiXMLInterface::DBL(tmp);
         tmp = mParser.getAttributeValue("minValue", papszAttrs);
         MinValue = CCopasiXMLInterface::DBL(tmp);
         tmp = mParser.getAttributeValue("maxValue", papszAttrs);
         MaxValue = CCopasiXMLInterface::DBL(tmp);
         tmp = mParser.getAttributeValue("tickNumber", papszAttrs, "1000");
         TickNumber = strToUnsignedInt(tmp);
         tmp = mParser.getAttributeValue("tickFactor", papszAttrs, "100");
         TickFactor = strToUnsignedInt(tmp);
         scaling = mParser.getAttributeValue("scaling", papszAttrs, "linear");
         // This is always the case if the XML is conforming to the schema.
         if (mCommon.KeyMap.get(AssociatedEntityKey))
           {
             pSlider = new CSlider("slider", mCommon.pGUI->getSliderList());
             addFix(Key, pSlider);
             if (strncmp(AssociatedEntityKey, "", 1))
               {
                 pSlider->setAssociatedEntityKey(mCommon.KeyMap.get(AssociatedEntityKey)->getKey());
               }
             else
               {
                 pSlider->setAssociatedEntityKey("");
               }
             pSlider->setSliderObject((std::string) ObjectCN);
             pSlider->setSliderType(ObjectType);
             pSlider->setMaxValue(MaxValue);
             pSlider->setMinValue(MinValue);
             pSlider->setSliderValue(ObjectValue);
             pSlider->setTickNumber(TickNumber);
             pSlider->setTickFactor(TickFactor);
             pSlider->setScaling(pSlider->convertScaleNameToScale(scaling));
             mCommon.pGUI->getSliderList()->add(pSlider, true);
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp