COPASI API: CQComboDelegate Class Reference
CQComboDelegate Class Reference
#include <CQComboDelegate.h>
Signals
void currentIndexChanged (int, int)
Public Member Functions
CQComboDelegate (const QStringList *pComboItems, QObject *parent=NULL, bool commitOnSelect=true)
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
const QStringList * getItems (int row) const
bool isCommitOnSelect () const
void setCommitOnSelect (bool commitOnSelect)
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const
void setItems (int row, const QStringList *pComboItems)
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
virtual void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual ~CQComboDelegate ()
Protected Slots
void slotCurrentIndexChanged (int index)
void slotEditorDeleted (QObject *pObject)
Private Attributes
bool mCommitOnSelect
QMap< QWidget *, QModelIndex > mEditorToIndex
const QStringList * mpComboItems
QMap< int, const QStringList * > mRowToItems
Detailed Description
Definition at line 16 of file CQComboDelegate.h.
Constructor & Destructor Documentation
CQComboDelegate::CQComboDelegate (const QStringList * pComboItems, QObject * parent = NULL, bool commitOnSelect = true)
Definition at line 18 of file CQComboDelegate.cpp.
                                                                                                     :
   QItemDelegate(parent),
   mpComboItems(pComboItems),
   mEditorToIndex(),
   mRowToItems(),
   mCommitOnSelect(commitOnSelect)
 {}
CQComboDelegate::~CQComboDelegate () virtual
Definition at line 26 of file CQComboDelegate.cpp.
 {}
Member Function Documentation
QWidget * CQComboDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 29 of file CQComboDelegate.cpp.
References currentIndexChanged(), getItems(), mEditorToIndex, slotCurrentIndexChanged(), and slotEditorDeleted().
 {
   QModelIndex  SourceIndex = index;
   const QAbstractItemModel *pModel = index.model();
   while (pModel->inherits("QSortFilterProxyModel"))
     {
       SourceIndex = static_cast< const QSortFilterProxyModel *>(pModel)->mapToSource(index);
       pModel = SourceIndex.model();
     }
   QComboBox *pEditor = new QComboBox(parent);
   if (getItems(SourceIndex.row()) != NULL)
     {
       pEditor->addItems(*getItems(SourceIndex.row()));
     }
   mEditorToIndex[pEditor] = SourceIndex;
   connect(pEditor, SIGNAL(currentIndexChanged(int)), this, SLOT(slotCurrentIndexChanged(int)));
   connect(pEditor, SIGNAL(destroyed(QObject *)), this, SLOT(slotEditorDeleted(QObject *)));
   return pEditor;
 }
void CQComboDelegate::currentIndexChanged (int , int) signal
Referenced by createEditor(), and slotCurrentIndexChanged().
const QStringList * CQComboDelegate::getItems (int row) const
Definition at line 87 of file CQComboDelegate.cpp.
References mpComboItems, and mRowToItems.
Referenced by createEditor(), and ParameterTable::slotCellChanged().
 {
   if (mpComboItems != NULL)
     {
       return mpComboItems;
     }
   QMap< int, const QStringList * >::const_iterator found = mRowToItems.find(row);
   if (found != mRowToItems.end()) // OK to return found.value() = NULL
     {
       return found.value();
     }
   return NULL;
 }
bool CQComboDelegate::isCommitOnSelect () const
Definition at line 128 of file CQComboDelegate.cpp.
References mCommitOnSelect.
 {
   return mCommitOnSelect;
 }
void CQComboDelegate::setCommitOnSelect (bool commitOnSelect)
Definition at line 134 of file CQComboDelegate.cpp.
References mCommitOnSelect.
 {
   mCommitOnSelect = commitOnSelect;
 }
void CQComboDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const virtual
Definition at line 57 of file CQComboDelegate.cpp.
 {
   QString value = index.model()->data(index, Qt::DisplayRole).toString();
   QComboBox *comboBox = static_cast<QComboBox*>(editor);
   comboBox->blockSignals(true);
   comboBox->setCurrentIndex(comboBox->findText(value));
   comboBox->blockSignals(false);
 }
void CQComboDelegate::setItems (int row, const QStringList * pComboItems)
Definition at line 82 of file CQComboDelegate.cpp.
References mRowToItems.
Referenced by CQExperimentData::setTypeItems(), and ParameterTable::updateTable().
 {
   mRowToItems[row] = pComboItems;
 }
void CQComboDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const virtual
Reimplemented in CQIndexComboDelegate.
Definition at line 68 of file CQComboDelegate.cpp.
 {
   QComboBox *comboBox = static_cast<QComboBox*>(editor);
   QVariant value(comboBox->currentText());
   model->setData(index, value, Qt::EditRole);
 }
void CQComboDelegate::slotCurrentIndexChanged (int index) protected slot
Definition at line 104 of file CQComboDelegate.cpp.
References currentIndexChanged(), mCommitOnSelect, and mEditorToIndex.
Referenced by createEditor().
 {
   QComboBox * pEditor = dynamic_cast< QComboBox * >(sender());
   if (pEditor)
     {
       QMap< QWidget * , QModelIndex >::const_iterator found = mEditorToIndex.find(pEditor);
       if (found != mEditorToIndex.end())
         {
           emit currentIndexChanged(found.value().row(), index);
           if (mCommitOnSelect)
             commitData(pEditor);
         }
     }
 }
void CQComboDelegate::slotEditorDeleted (QObject * pObject) protected slot
Definition at line 122 of file CQComboDelegate.cpp.
References mEditorToIndex.
Referenced by createEditor().
 {
   mEditorToIndex.remove(static_cast< QWidget * >(pObject));
 }
void CQComboDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 76 of file CQComboDelegate.cpp.
 {
   editor->setGeometry(option.rect);
 }
Member Data Documentation
bool CQComboDelegate::mCommitOnSelect private
Definition at line 61 of file CQComboDelegate.h.
Referenced by isCommitOnSelect(), setCommitOnSelect(), and slotCurrentIndexChanged().
QMap< QWidget * , QModelIndex > CQComboDelegate::mEditorToIndex mutable private
Definition at line 58 of file CQComboDelegate.h.
Referenced by createEditor(), slotCurrentIndexChanged(), and slotEditorDeleted().
const QStringList* CQComboDelegate::mpComboItems private
Definition at line 56 of file CQComboDelegate.h.
Referenced by getItems().
QMap< int, const QStringList * > CQComboDelegate::mRowToItems mutable private
Definition at line 59 of file CQComboDelegate.h.
Referenced by getItems(), and setItems().
The documentation for this class was generated from the following files:
CQComboDelegate.h
CQComboDelegate.cpp