COPASI API: CRDFLiteral Class Reference
CRDFLiteral Class Reference
#include <CRDFLiteral.h>
Public Types
enum eLiteralType { PLAIN = 0, TYPED }
Public Member Functions
CRDFLiteral ()
CRDFLiteral (const CRDFLiteral &src)
const std::string & getDataType () const
const std::string & getLanguage () const
const std::string & getLexicalData () const
const eLiteralType & getType () const
void setDataType (const std::string &dataType)
void setLanguage (const std::string &language)
void setLexicalData (const std::string &lexicalData)
void setType (const eLiteralType &type)
~CRDFLiteral ()
Private Attributes
std::string mDataType
std::string mLanguage
std::string mLexicalData
eLiteralType mType
Detailed Description
Definition at line 23 of file CRDFLiteral.h.
Member Enumeration Documentation
enum CRDFLiteral::eLiteralType
The two different types possible for literals
Enumerator
PLAIN
TYPED
Definition at line 30 of file CRDFLiteral.h.
 {PLAIN = 0, TYPED};
Constructor & Destructor Documentation
CRDFLiteral::CRDFLiteral ()
Default Constructor
Definition at line 22 of file CRDFLiteral.cpp.
                         :
     mType(PLAIN),
     mLanguage(""),
     mDataType(""),
     mLexicalData("")
 {}
CRDFLiteral::CRDFLiteral (const CRDFLiteral & src)
Copy Constructor
Parameters
const CRDFLiteral & src
Definition at line 29 of file CRDFLiteral.cpp.
                                                :
     mType(src.mType),
     mLanguage(src.mLanguage),
     mDataType(src.mDataType),
     mLexicalData(src.mLexicalData)
 {}
CRDFLiteral::~CRDFLiteral ()
Destructor
Definition at line 36 of file CRDFLiteral.cpp.
 {}
Member Function Documentation
const std::string & CRDFLiteral::getDataType () const
Retrieve the data type of the literal
Returns
const std::string & dataType
Definition at line 54 of file CRDFLiteral.cpp.
References mDataType.
Referenced by CRDFWriter::write().
   {return mDataType;}
const std::string & CRDFLiteral::getLanguage () const
Retrieve the language of the literal
Returns
const std::string & language
Definition at line 48 of file CRDFLiteral.cpp.
References mLanguage.
Referenced by CRDFWriter::write().
   {return mLanguage;}
const std::string & CRDFLiteral::getLexicalData () const
Retrieve the lexical data of the literal
Returns
const std::string & lexicalData
Definition at line 60 of file CRDFLiteral.cpp.
References mLexicalData.
Referenced by CRDFNode::getFieldValue(), operator<<(), CQRDFTreeViewItem::setTriplet(), and CRDFWriter::write().
   {return mLexicalData;}
const CRDFLiteral::eLiteralType & CRDFLiteral::getType () const
Retrieve the type of the literal
Returns
const eLiteralType & type
Definition at line 42 of file CRDFLiteral.cpp.
References mType.
Referenced by CQRDFTreeViewItem::setTriplet(), and CRDFWriter::write().
   {return mType;}
void CRDFLiteral::setDataType (const std::string & dataType)
Set the data type of the literal
Parameters
const std::string & dataType
Definition at line 51 of file CRDFLiteral.cpp.
References mDataType.
Referenced by CRDFParser::TripleHandler().
 {mDataType = dataType;}
void CRDFLiteral::setLanguage (const std::string & language)
Set the language of the literal
Parameters
const std::string & language
Definition at line 45 of file CRDFLiteral.cpp.
References mLanguage.
Referenced by CRDFParser::TripleHandler().
 {mLanguage = language;}
void CRDFLiteral::setLexicalData (const std::string & lexicalData)
Set the lexical data of the literal
Parameters
const std::string & lexicalData
Definition at line 57 of file CRDFLiteral.cpp.
References mLexicalData.
Referenced by CRDFNode::setFieldValue(), and CRDFParser::TripleHandler().
 {mLexicalData = lexicalData;}
void CRDFLiteral::setType (const eLiteralType & type)
Set the type of the literal
Parameters
const eLiteralType & type
Definition at line 39 of file CRDFLiteral.cpp.
References mType.
Referenced by CRDFNode::setFieldValue(), and CRDFParser::TripleHandler().
 {mType = type;}
Member Data Documentation
std::string CRDFLiteral::mDataType private
The data type describing URI for literals of type TYPED.
Definition at line 113 of file CRDFLiteral.h.
Referenced by getDataType(), and setDataType().
std::string CRDFLiteral::mLanguage private
The language tag for literals of type PLAIN
Definition at line 108 of file CRDFLiteral.h.
Referenced by getLanguage(), and setLanguage().
std::string CRDFLiteral::mLexicalData private
The lical form of the data
Definition at line 118 of file CRDFLiteral.h.
Referenced by getLexicalData(), and setLexicalData().
eLiteralType CRDFLiteral::mType private
The type of the literal
Definition at line 103 of file CRDFLiteral.h.
Referenced by getType(), and setType().
The documentation for this class was generated from the following files:
CRDFLiteral.h
CRDFLiteral.cpp