COPASI API: CCopasiTimer Class Reference
CCopasiTimer Class Reference
#include <CCopasiTimer.h>
Public Types
enum Type { WALL = 0, PROCESS, THREAD }
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CCopasiTimer (const Type &type=WALL, const CCopasiContainer *pParent=NULL)
CCopasiTimer (const CCopasiTimer &src, const CCopasiContainer *pParent=NULL)
const CCopasiTimeVariable & getElapsedTime () const
const C_FLOAT64 & getElapsedTimeSeconds () const
virtual void * getValuePointer () const
virtual void print (std::ostream *ostream) const
void refresh ()
bool start ()
~CCopasiTimer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
virtual const CCopasiObject * getValueObject () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
CCopasiTimeVariable mElapsedTime
C_FLOAT64 mElapsedTimeSeconds
CCopasiTimeVariable mStartTime
Type mType
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 24 of file CCopasiTimer.h.
Member Enumeration Documentation
enum CCopasiTimer::Type
Enumeration of timer types
Enumerator
WALL
PROCESS
THREAD
Definition at line 30 of file CCopasiTimer.h.
   {
     WALL = 0,
     PROCESS,
     THREAD
   };
Constructor & Destructor Documentation
CCopasiTimer::CCopasiTimer (const Type & type = WALL, const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const Type & type (default: WALL)
const CCopasiContainer * pParent (default: NULL)
Definition at line 24 of file CCopasiTimer.cpp.
References CCopasiTimeVariable::getCurrentWallTime(), CCopasiTimeVariable::getProcessTime(), CCopasiTimeVariable::getThreadTime(), mStartTime, mType, PROCESS, refresh(), CCopasiObject::setRefresh(), THREAD, and WALL.
                                                             :
     CCopasiObject((type == CCopasiTimer::WALL) ? "Wall Clock Time" : "CPU Time",
                   pParent, "Timer", CCopasiObject::ValueDbl),
     mType(type),
     mStartTime(),
     mElapsedTime(0),
     mElapsedTimeSeconds(0)
 {
   switch (mType)
     {
       case WALL:
         mStartTime = CCopasiTimeVariable::getCurrentWallTime();
         break;
       case PROCESS:
         mStartTime = CCopasiTimeVariable::getProcessTime();
         break;
       case THREAD:
         mStartTime = CCopasiTimeVariable::getThreadTime();
         break;
     }
   setRefresh(this, &CCopasiTimer::refresh);
 }
CCopasiTimer::CCopasiTimer (const CCopasiTimer & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CCopasiTimer & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 53 of file CCopasiTimer.cpp.
References refresh(), and CCopasiObject::setRefresh().
                                                             :
     CCopasiObject(src, pParent),
     mType(src.mType),
     mStartTime(src.mStartTime),
     mElapsedTime(src.mElapsedTime),
     mElapsedTimeSeconds(src.mElapsedTimeSeconds)
 {setRefresh(this, &CCopasiTimer::refresh);}
CCopasiTimer::~CCopasiTimer ()
Destructor.
Definition at line 62 of file CCopasiTimer.cpp.
 {}
Member Function Documentation
const CCopasiTimeVariable & CCopasiTimer::getElapsedTime () const
Retrieve the elapsed time.
Returns
const CCopasiTimeVariable & elapsedTime
Definition at line 111 of file CCopasiTimer.cpp.
References mElapsedTime.
Referenced by CFitProblem::printResult(), and COptProblem::printResult().
 {
   return mElapsedTime;
 }
const C_FLOAT64 & CCopasiTimer::getElapsedTimeSeconds () const
Retrieve the elapsed time in seconds.
Returns
const C_FLOAT64 & elapsedTimeSeconds
Definition at line 116 of file CCopasiTimer.cpp.
References mElapsedTimeSeconds.
Referenced by COptProblem::getExecutionTime().
 {
   return mElapsedTimeSeconds;
 }
void * CCopasiTimer::getValuePointer () const virtual
Retrieve a pointer to the value of the object
Reimplemented from CCopasiObject.
Definition at line 124 of file CCopasiTimer.cpp.
References mElapsedTimeSeconds.
 {return & const_cast<CCopasiTimer *>(this)->mElapsedTimeSeconds;}
void CCopasiTimer::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object. To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 121 of file CCopasiTimer.cpp.
References mElapsedTimeSeconds.
 {(*ostream) << mElapsedTimeSeconds;}
void CCopasiTimer::refresh ()
Actualizes the timer.
Definition at line 88 of file CCopasiTimer.cpp.
References CCopasiTimeVariable::getCurrentWallTime(), CCopasiTimeVariable::getMicroSeconds(), CCopasiTimeVariable::getProcessTime(), CCopasiTimeVariable::getThreadTime(), mElapsedTime, mElapsedTimeSeconds, mStartTime, mType, PROCESS, THREAD, and WALL.
Referenced by CCopasiTimer(), and main().
 {
   switch (mType)
     {
       case WALL:
         mElapsedTime = CCopasiTimeVariable::getCurrentWallTime() - mStartTime;
         break;
       case PROCESS:
         mElapsedTime = CCopasiTimeVariable::getProcessTime() - mStartTime;
         break;
       case THREAD:
         mElapsedTime = CCopasiTimeVariable::getThreadTime() - mStartTime;
         break;
     }
   mElapsedTimeSeconds =
     (mElapsedTime.getMicroSeconds() * 1e-6);
   return;
 }
bool CCopasiTimer::start ()
Start or restart the timer.
Returns
bool success
Definition at line 65 of file CCopasiTimer.cpp.
References CCopasiTimeVariable::getCurrentWallTime(), CCopasiTimeVariable::getProcessTime(), CCopasiTimeVariable::getThreadTime(), mElapsedTime, mElapsedTimeSeconds, mStartTime, mType, PROCESS, THREAD, and WALL.
Referenced by COptProblem::initialize().
 {
   switch (mType)
     {
       case WALL:
         mStartTime = CCopasiTimeVariable::getCurrentWallTime();
         break;
       case PROCESS:
         mStartTime = CCopasiTimeVariable::getProcessTime();
         break;
       case THREAD:
         mStartTime = CCopasiTimeVariable::getThreadTime();
         break;
     }
   mElapsedTime = 0;
   mElapsedTimeSeconds = 0;
   return true;
 }
Member Data Documentation
CCopasiTimeVariable CCopasiTimer::mElapsedTime private
The elapsed time of the timer.
Definition at line 108 of file CCopasiTimer.h.
Referenced by getElapsedTime(), refresh(), and start().
C_FLOAT64 CCopasiTimer::mElapsedTimeSeconds private
The elapsed time as a double used for reporting.
Definition at line 113 of file CCopasiTimer.h.
Referenced by getElapsedTimeSeconds(), getValuePointer(), print(), refresh(), and start().
CCopasiTimeVariable CCopasiTimer::mStartTime private
The start time of the timer.
Definition at line 103 of file CCopasiTimer.h.
Referenced by CCopasiTimer(), refresh(), and start().
Type CCopasiTimer::mType private
The timer type
Definition at line 98 of file CCopasiTimer.h.
Referenced by CCopasiTimer(), refresh(), and start().
The documentation for this class was generated from the following files:
CCopasiTimer.h
CCopasiTimer.cpp