COPASI API: CCopasiObject.cpp File Reference
CCopasiObject.cpp File Reference
#include <sstream>
#include <algorithm>
#include "copasi/copasi.h"
#include "copasi/report/CCopasiObjectName.h"
#include "copasi/report/CCopasiObject.h"
#include "copasi/report/CCopasiContainer.h"
#include "copasi/report/CCopasiStaticString.h"
#include "copasi/report/CRenameHandler.h"
#include "copasi/utilities/CCopasiVector.h"
#include "copasi/model/CModelValue.h"
#include "copasi/model/CModel.h"
#include "copasi/CopasiDataModel/CCopasiDataModel.h"
#include "copasi/report/CCopasiRootContainer.h"
#include "copasi/function/CFunctionDB.h"
Functions
std::ostream & operator<< (std::ostream &os, const CCopasiObject &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiObject & o)
Definition at line 645 of file CCopasiObject.cpp.
References CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectType(), CCopasiObject::isContainer(), CCopasiObject::isMatrix(), CCopasiObject::isNameVector(), CCopasiObject::isReference(), CCopasiObject::isValueBool(), CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), and CCopasiObject::isVector().
 {
   os << "Name:      " << o.getObjectDisplayName() << std::endl;
   os << "Type:      " << o.getObjectType() << std::endl;
   os << "Container: " << o.isContainer() << std::endl;
   os << "Vector:    " << o.isVector() << std::endl;
   os << "VectorN:   " << o.isNameVector() << std::endl;
   os << "Matrix:    " << o.isMatrix() << std::endl;
   os << "Reference: " << o.isReference() << std::endl;
   os << "Bool:      " << o.isValueBool() << std::endl;
   os << "Int:       " << o.isValueInt() << std::endl;
   os << "Dbl:       " << o.isValueDbl() << std::endl;
   return os;
 }