COPASI API: CRenameHandler Class Reference
CRenameHandler Class Reference abstract
#include <CRenameHandler.h>
Public Member Functions
virtual void handle (const std::string &oldCN, const std::string &newCN) const =0
virtual void setEnabled (const bool &enabled)=0
virtual ~CRenameHandler ()
Detailed Description
Definition at line 20 of file CRenameHandler.h.
Constructor & Destructor Documentation
virtual CRenameHandler::~CRenameHandler () inline virtual
Definition at line 23 of file CRenameHandler.h.
 {};
Member Function Documentation
virtual void CRenameHandler::handle (const std::string & oldCN, const std::string & newCN) const pure virtual
Implemented in CDataModelRenameHandler.
Referenced by CCompartment::addMetabolite(), and CCopasiObject::setObjectName().
virtual void CRenameHandler::setEnabled (const bool & enabled) pure virtual
Enable and disable the rename handler
Parameters
const bool & enabled
Implemented in CDataModelRenameHandler.
Referenced by CModel::compile().
The documentation for this class was generated from the following file:
CRenameHandler.h