COPASI API: test000081 Class Reference
test000081 Class Reference
#include <test000081.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1205 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1205)
CPPUNIT_TEST_SUITE (test000081)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 30 of file test000081.h.
Member Function Documentation
test000081::CPPUNIT_TEST (test_bug1205) private
test000081::CPPUNIT_TEST_SUITE (test000081) private
test000081::CPPUNIT_TEST_SUITE_END () private
void test000081::setUp ()
Test for bug 1205
Definition at line 36 of file test000081.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000081::tearDown ()
Definition at line 44 of file test000081.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000081::test_bug1205 ()
Definition at line 49 of file test000081.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000081::MODEL_STRING1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   std::string sbmlString;
   try
     {
       sbmlString = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       // fail if an uncaught exception occurs during export
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(!sbmlString.empty());
   // check if the exported SBML model has three compartments
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   const Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   unsigned int iMax = pModel->getListOfCompartments()->size();
   CPPUNIT_ASSERT(iMax == 3);
   // check that the compartment named compartment_2 has the id compartment_1
   const Compartment* pCompartment = pModel->getCompartment("compartment_1");
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getName() == "compartment_2");
   // check if the exported SBML model has three species
   iMax = pModel->getListOfSpecies()->size();
   CPPUNIT_ASSERT(iMax == 3);
   // check that the species named species_2 has the id species_1
   const Species* pSpecies = pModel->getSpecies("species_1");
   CPPUNIT_ASSERT(pSpecies != NULL);
   CPPUNIT_ASSERT(pSpecies->getName() == "species_2");
   // check if the exported SBML model has three parameters
   iMax = pModel->getListOfParameters()->size();
   CPPUNIT_ASSERT(iMax == 3);
   // check that the parameter named quantity_2 has the id parameter_1
   const Parameter* pParameter = pModel->getParameter("parameter_1");
   CPPUNIT_ASSERT(pParameter != NULL);
   CPPUNIT_ASSERT(pParameter->getName() == "quantity_2");
   // check if the exported SBML model has three reactions
   iMax = pModel->getListOfReactions()->size();
   CPPUNIT_ASSERT(iMax == 3);
   // check that the reaction named reaction_2 has the id reaction_1
   const Reaction* pReaction = pModel->getReaction("reaction_1");
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getName() == "reaction_2");
 }
Member Data Documentation
const char * test000081::MODEL_STRING1 static protected
Definition at line 40 of file test000081.h.
Referenced by test_bug1205().
CCopasiDataModel * test000081::pCOPASIDATAMODEL = NULL static protected
Definition at line 39 of file test000081.h.
Referenced by setUp(), and test_bug1205().
The documentation for this class was generated from the following files:
test000081.h
test000081.cpp