COPASI API: CQSideCompoundWizardPage Class Reference
CQSideCompoundWizardPage Class Reference
#include <CQAutolayoutWizard.h>
Classes
class alphaSorter
class CQListWidgetModelItem
Public Member Functions
CQSideCompoundWizardPage ()
void getSideCompounds (std::set< const CMetab * > &sideCompounds) const
void setSpeciesList (const std::set< const CMetab * > &metabs)
Protected Slots
void slotAddButtonClicked ()
void slotRemoveButtonClicked ()
void slotSideCompoundSelectionChanged ()
void slotSpeciesSelectionChanged ()
Protected Attributes
QPushButton * mpAddButton
QPushButton * mpRemoveButton
QListWidget * mpSideCompoundList
QListWidget * mpSpeciesList
std::set< const CMetab
*, alphaSorter > mSortedSpecies
Detailed Description
In this page the user can select which species should be treated as side compounds by the layout algorithm.
Definition at line 128 of file CQAutolayoutWizard.h.
Constructor & Destructor Documentation
CQSideCompoundWizardPage::CQSideCompoundWizardPage ()
Definition at line 616 of file CQAutolayoutWizard.cpp.
References mpAddButton, mpRemoveButton, mpSideCompoundList, mpSpeciesList, slotAddButtonClicked(), slotRemoveButtonClicked(), slotSideCompoundSelectionChanged(), and slotSpeciesSelectionChanged().
                                                    :
   QWizardPage()
   , mpSpeciesList(new QListWidget)
   , mpSideCompoundList(new QListWidget)
   , mpAddButton(new QPushButton(">>"))
   , mpRemoveButton(new QPushButton("<<"))
 {
   this->setTitle("Side Compounds");
   this->setSubTitle("Please select the species that you want to be considered as side compounds in the layout.\n\nSide compounds can be duplicated for each reaction they occur in and they might be treated differently by the layout algorithm.");
   // the page should contain two lists
   // and the user can push elements back and forth
   // between the lists
   this->mpSpeciesList->setSelectionMode(QAbstractItemView::ExtendedSelection);
   this->mpSideCompoundList->setSelectionMode(QAbstractItemView::ExtendedSelection);
   QHBoxLayout* pLayout = new QHBoxLayout;
   this->setLayout(pLayout);
   QFrame* pFrame = new QFrame;
   QVBoxLayout* pLayout2 = new QVBoxLayout;
   pFrame->setLayout(pLayout2);
   pLayout2->addWidget(new QLabel("Species"));
   pLayout2->addWidget(this->mpSpeciesList);
   pLayout->addWidget(pFrame);
   pLayout2 = new QVBoxLayout;
   pFrame = new QFrame;
   pFrame->setLayout(pLayout2);
   pLayout2->addStretch();
   this->mpAddButton->setEnabled(false);
   this->mpRemoveButton->setEnabled(false);
   pLayout2->addWidget(this->mpAddButton);
   pLayout2->addSpacing(20);
   pLayout2->addWidget(this->mpRemoveButton);
   pLayout2->addStretch();
   pLayout->addWidget(pFrame);
   pFrame = new QFrame;
   pLayout2 = new QVBoxLayout;
   pFrame->setLayout(pLayout2);
   pLayout2->addWidget(new QLabel("Side-Species"));
   pLayout2->addWidget(this->mpSideCompoundList);
   pLayout->addWidget(pFrame);
   connect(this->mpAddButton, SIGNAL(clicked()), this, SLOT(slotAddButtonClicked()));
   connect(this->mpRemoveButton, SIGNAL(clicked()), this, SLOT(slotRemoveButtonClicked()));
   connect(this->mpSpeciesList, SIGNAL(itemSelectionChanged()), this, SLOT(slotSpeciesSelectionChanged()));
   connect(this->mpSideCompoundList, SIGNAL(itemSelectionChanged()), this, SLOT(slotSideCompoundSelectionChanged()));
 }
Member Function Documentation
void CQSideCompoundWizardPage::getSideCompounds (std::set< const CMetab * > & sideCompounds) const
Fills the given set with the side compounds that have been selected by the user.
Definition at line 670 of file CQAutolayoutWizard.cpp.
References CQSideCompoundWizardPage::CQListWidgetModelItem::getObject(), and mpSideCompoundList.
 {
   sideCompounds.clear();
   unsigned int i, iMax = this->mpSideCompoundList->count();
   const CQListWidgetModelItem* pItem = NULL;
   const CMetab* pMetab = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pItem = dynamic_cast<const CQListWidgetModelItem*>(this->mpSideCompoundList->item(i));
       assert(pItem != NULL);
       pMetab = dynamic_cast<const CMetab*>(pItem->getObject());
       sideCompounds.insert(pMetab);
     }
 }
void CQSideCompoundWizardPage::setSpeciesList (const std::set< const CMetab * > & metabs)
Passes the species that have been selected by the user for use in the layout to the page. These species are used to fill the list on the left.
Definition at line 691 of file CQAutolayoutWizard.cpp.
References mpSideCompoundList, mpSpeciesList, and mSortedSpecies.
 {
   this->mSortedSpecies.clear();
   this->mSortedSpecies.insert(metabs.begin(), metabs.end());
   std::set<std::string> keys;
   this->mpSpeciesList->clear();
   std::set<const CMetab*, alphaSorter>::const_iterator it = this->mSortedSpecies.begin(), endit = this->mSortedSpecies.end();
   QList<QListWidgetItem*> itemList;
   int i, iMax;
   while (it != endit)
     {
       std::string displayName = (*it)->getObjectDisplayName();
       keys.insert((*it)->getKey());
       // if the item is already marked as a side compound, we don't
       // have to add it to the species list
       itemList = this->mpSideCompoundList->findItems(displayName.c_str(), Qt::MatchExactly);
       i = 0;
       iMax = itemList.size();
       bool found = false;
       while (i < iMax)
         {
           if (static_cast<const CQListWidgetModelItem*>(itemList[i])->getKey() == (*it)->getKey())
             {
               found = true;
             }
           ++i;
         }
       if (found == false)
         {
           // the item is not a side compound, so we add it to the species list
           this->mpSpeciesList->addItem(new CQListWidgetModelItem(displayName.c_str(), (*it)->getKey()));
         }
       ++it;
     }
   // now we have to go through the side compounds again and check
   // if all the names that are in there are also in the sorted name list
   // If not, we have to delete the item from the side compounds
   iMax = this->mpSideCompoundList->count() - 1;
   std::set<std::string>::const_iterator end = keys.end();
   QListWidgetItem* pItem = NULL;
   while (iMax > 0)
     {
       if (keys.find(static_cast<const CQListWidgetModelItem*>(this->mpSideCompoundList->item(iMax))->getKey()) == end)
         {
           pItem = this->mpSideCompoundList->takeItem(iMax);
           if (pItem != NULL)
             {
               delete pItem;
             }
         }
       --iMax;
     }
 }
void CQSideCompoundWizardPage::slotAddButtonClicked () protected slot
Definition at line 756 of file CQAutolayoutWizard.cpp.
References CQSideCompoundWizardPage::CQListWidgetModelItem::getObject(), CCopasiObject::getObjectDisplayName(), mpSideCompoundList, and mpSpeciesList.
Referenced by CQSideCompoundWizardPage().
 {
   // move the selected items from the species list to the side compound list
   QList<QListWidgetItem*> selection = this->mpSpeciesList->selectedItems();
   //  insert the items into the side compound list in the correct order
   //  and remove them from the species list
   //  the items should be selected in the side compound list
   int index = 0;
   QList<QListWidgetItem*>::iterator it = selection.begin(), endit = selection.end();
   while (it != endit)
     {
       while (index < this->mpSideCompoundList->count() && static_cast<CQListWidgetModelItem*>(this->mpSideCompoundList->item(index))->getObject()->getObjectDisplayName() < static_cast<CQListWidgetModelItem*>(*it)->getObject()->getObjectDisplayName())
         {
           ++index;
         }
       if (index == this->mpSideCompoundList->count())
         {
           // we add all items at the end
           while (it != endit)
             {
               this->mpSpeciesList->takeItem(this->mpSpeciesList->row(*it));
               this->mpSideCompoundList->addItem((*it));
               ++it;
             }
         }
       // now we insert items until the item is not at the right place
       while (it != endit && static_cast<CQListWidgetModelItem*>(this->mpSideCompoundList->item(index))->getObject()->getObjectDisplayName() > static_cast<CQListWidgetModelItem*>(*it)->getObject()->getObjectDisplayName())
         {
           this->mpSpeciesList->takeItem(this->mpSpeciesList->row(*it));
           this->mpSideCompoundList->insertItem(index, *it);
           ++it;
         }
     }
   // TODO set the newly added items as selected
   // TODO disconnect and reconnect the slot that listend to the selection change
   // TODO and emit the signal after changing the selection
   this->mpSpeciesList->update();
 }
void CQSideCompoundWizardPage::slotRemoveButtonClicked () protected slot
Definition at line 800 of file CQAutolayoutWizard.cpp.
References CQSideCompoundWizardPage::CQListWidgetModelItem::getObject(), CCopasiObject::getObjectDisplayName(), mpSideCompoundList, and mpSpeciesList.
Referenced by CQSideCompoundWizardPage().
 {
   // move the selected items from the side compound list to the species list
   QList<QListWidgetItem*> selection = this->mpSideCompoundList->selectedItems();
   // insert the items into the species list in the correct order
   // and remove them from the side compound list
   // the items should be selected in the species list
   QList<QListWidgetItem*>::iterator it = selection.begin(), endit = selection.end();
   int index = 0;
   while (it != endit)
     {
       while (index < this->mpSpeciesList->count() && static_cast<CQListWidgetModelItem*>(this->mpSpeciesList->item(index))->getObject()->getObjectDisplayName() < static_cast<CQListWidgetModelItem*>(*it)->getObject()->getObjectDisplayName())
         {
           ++index;
         }
       if (index == this->mpSpeciesList->count())
         {
           // we add all items at the end
           while (it != endit)
             {
               this->mpSideCompoundList->takeItem(this->mpSideCompoundList->row(*it));
               this->mpSpeciesList->addItem((*it));
               ++it;
             }
           break;
         }
       // now we insert items until the item is not at the right place
       while (it != endit && static_cast<CQListWidgetModelItem*>(this->mpSpeciesList->item(index))->getObject()->getObjectDisplayName() > static_cast<CQListWidgetModelItem*>(*it)->getObject()->getObjectDisplayName())
         {
           this->mpSideCompoundList->takeItem(this->mpSideCompoundList->row(*it));
           this->mpSpeciesList->insertItem(index, *it);
           ++it;
         }
     }
   // TODO set the newly added items as selected
   // TODO disconnect and reconnect the slot that listend to the selection change
   // TODO and emit the signal after changing the selection
   this->mpSideCompoundList->update();
 }
void CQSideCompoundWizardPage::slotSideCompoundSelectionChanged () protected slot
Definition at line 866 of file CQAutolayoutWizard.cpp.
References mpRemoveButton, mpSideCompoundList, and mpSpeciesList.
Referenced by CQSideCompoundWizardPage().
 {
   // if something is selected, delete the selection in the
   // species list and active the remove button
   // else deactivate the remove button
   QList<QListWidgetItem*> selection = this->mpSideCompoundList->selectedItems();
   if (selection.size() == 0)
     {
       this->mpRemoveButton->setEnabled(false);
     }
   else
     {
       this->mpRemoveButton->setEnabled(true);
       this->mpSpeciesList->clearSelection();
     }
 }
void CQSideCompoundWizardPage::slotSpeciesSelectionChanged () protected slot
Definition at line 846 of file CQAutolayoutWizard.cpp.
References mpAddButton, mpSideCompoundList, and mpSpeciesList.
Referenced by CQSideCompoundWizardPage().
 {
   // if something is selected
   // delete the selection in the side compound list
   // if nothing is selected deactive the add button, else active the add
   // button
   QList<QListWidgetItem*> selection = this->mpSpeciesList->selectedItems();
   if (selection.size() == 0)
     {
       this->mpAddButton->setEnabled(false);
     }
   else
     {
       this->mpAddButton->setEnabled(true);
       this->mpSideCompoundList->clearSelection();
     }
 }
Member Data Documentation
QPushButton* CQSideCompoundWizardPage::mpAddButton protected
Definition at line 181 of file CQAutolayoutWizard.h.
Referenced by CQSideCompoundWizardPage(), and slotSpeciesSelectionChanged().
QPushButton* CQSideCompoundWizardPage::mpRemoveButton protected
Definition at line 185 of file CQAutolayoutWizard.h.
Referenced by CQSideCompoundWizardPage(), and slotSideCompoundSelectionChanged().
QListWidget* CQSideCompoundWizardPage::mpSideCompoundList protected
Definition at line 177 of file CQAutolayoutWizard.h.
Referenced by CQSideCompoundWizardPage(), getSideCompounds(), setSpeciesList(), slotAddButtonClicked(), slotRemoveButtonClicked(), slotSideCompoundSelectionChanged(), and slotSpeciesSelectionChanged().
QListWidget* CQSideCompoundWizardPage::mpSpeciesList protected
Definition at line 174 of file CQAutolayoutWizard.h.
Referenced by CQSideCompoundWizardPage(), setSpeciesList(), slotAddButtonClicked(), slotRemoveButtonClicked(), slotSideCompoundSelectionChanged(), and slotSpeciesSelectionChanged().
std::set<const CMetab*, alphaSorter> CQSideCompoundWizardPage::mSortedSpecies protected
Definition at line 188 of file CQAutolayoutWizard.h.
Referenced by setSpeciesList().
The documentation for this class was generated from the following files:
CQAutolayoutWizard.h
CQAutolayoutWizard.cpp