COPASI API: CCopasiXMLParser::LocalStyleElement Class Reference
CCopasiXMLParser::LocalStyleElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
LocalStyleElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~LocalStyleElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { LocalStyle = 0, Group }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4399 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::LocalStyleElement::Element private
Enumerator
LocalStyle
Group
Definition at line 4406 of file CCopasiXMLParser.h.
     {
       LocalStyle = 0,
       Group
     };
Constructor & Destructor Documentation
CCopasiXMLParser::LocalStyleElement::LocalStyleElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 13388 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::LocalStyleElement::~LocalStyleElement () virtual
Destructor
Definition at line 13393 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::LocalStyleElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 13496 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pStyle, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case LocalStyle:
         if (strcmp(pszName, "Style"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Style", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCommon.pStyle = NULL;
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case Group:
         if (strcmp(pszName, "Group"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Group", mParser.getCurrentLineNumber());
         //tell the handler where to continue
         mCurrentElement = LocalStyle;
         //no need to delete Handler (since it is the only one the destructor
         //will handle it)
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::LocalStyleElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 13398 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CKeyFactory::get(), CLGraphicalObject::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pRenderInformation, SCopasiXMLParserCommon::pStyle, CLStyle::readIntoSet(), CLLocalStyle::setKeyList(), CLStyle::setRoleList(), CLStyle::setTypeList(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * RoleList;
   const char * TypeList;
   const char * KeyList;
   CLLocalStyle* pLocalStyle = NULL;
   switch (mCurrentElement)
     {
       case LocalStyle:
         if (strcmp(pszName, "Style"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Style", mParser.getCurrentLineNumber());
         RoleList = mParser.getAttributeValue("roleList", papszAttrs, false);
         TypeList = mParser.getAttributeValue("typeList", papszAttrs, false);
         KeyList = mParser.getAttributeValue("keyList", papszAttrs, false);
         pLocalStyle = new CLLocalStyle();
         if (RoleList != NULL)
           {
             std::set<std::string> s;
             CLStyle::readIntoSet(RoleList, s);
             pLocalStyle->setRoleList(s);
           }
         if (TypeList != NULL)
           {
             std::set<std::string> s;
             CLStyle::readIntoSet(TypeList, s);
             pLocalStyle->setTypeList(s);
           }
         if (KeyList != NULL)
           {
             std::set<std::string> s;
             CLStyle::readIntoSet(KeyList, s);
             // we need to translate the keys from the file to the actual keys assigned now
             std::set<std::string> s_conv;
             std::set<std::string>::const_iterator keyIt = s.begin(), keyEndit = s.end();
             CLGraphicalObject* pGO = NULL;
             while (keyIt != keyEndit)
               {
                 pGO = dynamic_cast<CLGraphicalObject *>(mCommon.KeyMap.get(*keyIt));
                 assert(pGO);
                 if (pGO != NULL)
                   {
                     s_conv.insert(pGO->getKey());
                   }
                 ++keyIt;
               }
             pLocalStyle->setKeyList(s_conv);
           }
         assert(dynamic_cast<CLLocalRenderInformation*>(mCommon.pRenderInformation) != NULL);
         static_cast<CLLocalRenderInformation*>(mCommon.pRenderInformation)->addStyle(pLocalStyle);
         // delete the line ending again since the addLocalStyle method made a copy
         delete pLocalStyle;
         assert(static_cast<CLLocalRenderInformation*>(mCommon.pRenderInformation)->getNumStyles() > 0);
         mCommon.pStyle = static_cast<CLLocalRenderInformation*>(mCommon.pRenderInformation)->getStyle(static_cast<CLLocalRenderInformation*>(mCommon.pRenderInformation)->getNumStyles() - 1);
         break;
       case Group:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "Group"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Group", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new GroupElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp