COPASI API: CQMoietiesTaskWidget Class Reference
CQMoietiesTaskWidget Class Reference
#include <CQMoietiesTaskWidget.h>
Public Member Functions
CQMoietiesTaskWidget (QWidget *parent=0, const char *name=0)
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool runTask ()
virtual bool saveTask ()
~CQMoietiesTaskWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Member Functions
void destroy ()
void init ()
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 23 of file CQMoietiesTaskWidget.h.
Constructor & Destructor Documentation
CQMoietiesTaskWidget::CQMoietiesTaskWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 25 of file CQMoietiesTaskWidget.cpp.
References init().
   : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQMoietiesTaskWidget::~CQMoietiesTaskWidget ()
Definition at line 36 of file CQMoietiesTaskWidget.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQMoietiesTaskWidget::createMethod (const CCopasiMethod::SubType & type) virtual
Implements TaskWidget.
Definition at line 94 of file CQMoietiesTaskWidget.cpp.
References CMoietiesMethod::createMethod().
 {
   return CMoietiesMethod::createMethod(type);
 }
void CQMoietiesTaskWidget::destroy () private
Definition at line 51 of file CQMoietiesTaskWidget.cpp.
Referenced by ~CQMoietiesTaskWidget().
 {}
void CQMoietiesTaskWidget::init () private
Definition at line 42 of file CQMoietiesTaskWidget.cpp.
References TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, and CQTaskHeaderWidget::setTaskName().
Referenced by CQMoietiesTaskWidget().
 {
   mpHeaderWidget->setTaskName("Mass Conservation");
   mpHeaderWidget->mpUpdateModel->hide();
   vboxLayout->insertWidget(0, mpHeaderWidget);
   vboxLayout->addWidget(mpBtnWidget);
 }
bool CQMoietiesTaskWidget::loadTask () virtual
Implements TaskWidget.
Definition at line 84 of file CQMoietiesTaskWidget.cpp.
References TaskWidget::loadCommon(), and TaskWidget::mpTask.
 {
   if (dynamic_cast< CMoietiesTask * >(mpTask) == NULL)
     return false;
   loadCommon();
   return true;
 }
bool CQMoietiesTaskWidget::runTask () virtual
Implements TaskWidget.
Definition at line 54 of file CQMoietiesTaskWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), and TaskWidget::mpTask.
 {
   if (dynamic_cast< CMoietiesTask * >(mpTask) == NULL)
     return false;
   if (!commonBeforeRunTask()) return false;
   return commonRunTask();
 }
bool CQMoietiesTaskWidget::saveTask () virtual
Implements TaskWidget.
Definition at line 74 of file CQMoietiesTaskWidget.cpp.
References TaskWidget::mpTask, and TaskWidget::saveCommon().
 {
   if (dynamic_cast< CMoietiesTask * >(mpTask) == NULL)
     return false;
   saveCommon();
   return true;
 }
bool CQMoietiesTaskWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 64 of file CQMoietiesTaskWidget.cpp.
References CopasiWidget::mpListView, and ListViews::switchToOtherWidget().
 {
   bool success = true;
   if (success && isVisible())
     mpListView->switchToOtherWidget(2221, ""); //change to the results window
   return success;
 }
The documentation for this class was generated from the following files:
CQMoietiesTaskWidget.h
CQMoietiesTaskWidget.cpp