COPASI API: CMathEventN::CTrigger::CRoot Class Reference
CMathEventN::CTrigger::CRoot Class Reference
#include <CMathEvent.h>
Public Member Functions
bool compile (CEvaluationNode *pRootNode, const bool &equality, CMathContainer &container)
void copy (const CRoot &src, CMathContainer &container, const size_t &valueOffset, const size_t &objectOffset)
CEvaluationNode * createTriggerExpressionNode () const
CRoot ()
void initialize (CMath::sPointers &pointers)
~CRoot ()
Public Attributes
bool mDiscrete
bool mEquality
CMathObject * mpRoot
CMathObject * mpRootState
Detailed Description
Definition at line 62 of file CMathEvent.h.
Constructor & Destructor Documentation
CMathEventN::CTrigger::CRoot::CRoot ()
Default constructor
Definition at line 83 of file CMathEvent.cpp.
                                :
   mpRoot(NULL),
   mpRootState(NULL),
   mEquality(false),
   mDiscrete(false)
 {}
CMathEventN::CTrigger::CRoot::~CRoot ()
Destructor
Definition at line 90 of file CMathEvent.cpp.
 {}
Member Function Documentation
bool CMathEventN::CTrigger::CRoot::compile (CEvaluationNode * pRootNode, const bool & equality, CMathContainer & container)
Definition at line 121 of file CMathEvent.cpp.
References CCopasiNode< _Data >::addChild(), C_FLOAT64, CEvaluationNodeNumber::DOUBLE, and CEvaluationNodeLogical::GT.
Referenced by CMathEventN::CTrigger::compileLE().
 {
   mEquality = equality;
   std::vector< CCopasiContainer * > ListOfContainer;
   ListOfContainer.push_back(const_cast< CMathContainer * >(&container));
   CMathExpression * pExpression = new CMathExpression("RootExpression", container);
   bool success = static_cast< CEvaluationTree * >(pExpression)->setRoot(pRootNode);
   success &= mpRoot->setExpressionPtr(pExpression);
   // Compile the root state object
   CMathExpression * pStateExpression = new CMathExpression("RootStateExpression", container);
   CEvaluationNode * pStateExpressionNode = new CEvaluationNodeLogical(CEvaluationNodeLogical::GT, "GT");
   pStateExpressionNode->addChild(new CEvaluationNodeObject((C_FLOAT64 *) mpRoot->getValuePointer()));
   pStateExpressionNode->addChild(new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "0.5"));
   success &= static_cast< CEvaluationTree * >(pStateExpression)->setRoot(pStateExpressionNode);
   success &= mpRootState->setExpressionPtr(pStateExpression);
   return success;
 }
void CMathEventN::CTrigger::CRoot::copy (const CRoot & src, CMathContainer & container, const size_t & valueOffset, const size_t & objectOffset)
Copy an existing object
Parameters
const CRoot & src
CMathContainer & container
const size_t & valueOffset
const size_t & objectOffset
Definition at line 110 of file CMathEvent.cpp.
References mDiscrete, mEquality, mpRoot, and mpRootState.
Referenced by CMathEventN::CTrigger::copy().
 {
   mpRoot = src.mpRoot + objectOffset;
   mpRootState = src.mpRootState + objectOffset;
   mEquality = src.mEquality;
   mDiscrete = src.mDiscrete;
 }
CEvaluationNode * CMathEventN::CTrigger::CRoot::createTriggerExpressionNode () const
Definition at line 148 of file CMathEvent.cpp.
References C_FLOAT64.
Referenced by CMathEventN::CTrigger::compileLE().
 {
   return  new CEvaluationNodeObject((C_FLOAT64 *) mpRootState->getValuePointer());
 }
void CMathEventN::CTrigger::CRoot::initialize (CMath::sPointers & pointers)
Definition at line 93 of file CMathEvent.cpp.
References CMath::Event, CMath::EventRoot, CMath::EventRootState, CMathObject::initialize(), CMath::sPointers::pEventRoots, CMath::sPointers::pEventRootsObject, CMath::sPointers::pEventRootStates, CMath::sPointers::pEventRootStatesObject, and CMath::SimulationTypeUndefined.
Referenced by CMathEventN::CTrigger::initialize().
 {
   // Initialize the root object!
   mpRoot = pointers.pEventRootsObject;
   *pointers.pEventRoots = 1.0;
   CMathObject::initialize(pointers.pEventRootsObject, pointers.pEventRoots,
                           CMath::EventRoot, CMath::Event, CMath::SimulationTypeUndefined,
                           false, false, NULL);
   // Initialize the root state object!
   mpRootState = pointers.pEventRootStatesObject;
   *pointers.pEventRootStates = 1.0;
   CMathObject::initialize(pointers.pEventRootStatesObject, pointers.pEventRootStates,
                           CMath::EventRootState, CMath::Event, CMath::SimulationTypeUndefined,
                           false, false, NULL);
 }
Member Data Documentation
bool CMathEventN::CTrigger::CRoot::mDiscrete
Definition at line 96 of file CMathEvent.h.
Referenced by copy().
bool CMathEventN::CTrigger::CRoot::mEquality
Definition at line 95 of file CMathEvent.h.
Referenced by copy().
CMathObject* CMathEventN::CTrigger::CRoot::mpRoot
Definition at line 93 of file CMathEvent.h.
Referenced by copy(), and CMathEventN::CTrigger::setExpression().
CMathObject* CMathEventN::CTrigger::CRoot::mpRootState
Definition at line 94 of file CMathEvent.h.
Referenced by copy(), and CMathEventN::CTrigger::setExpression().
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp