COPASI API: test000054 Class Reference
test000054 Class Reference
#include <test000054.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1002 ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1002)
CPPUNIT_TEST_SUITE (test000054)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000054.h.
Member Function Documentation
test000054::CPPUNIT_TEST (test_bug1002) private
test000054::CPPUNIT_TEST_SUITE (test000054) private
test000054::CPPUNIT_TEST_SUITE_END () private
void test000054::setUp ()
Definition at line 36 of file test000054.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000054::tearDown ()
Definition at line 44 of file test000054.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000054::test_bug1002 ()
Definition at line 49 of file test000054.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING, and pCOPASIDATAMODEL.
 {
   // load the CPS file
   // export to SBML
   // check the resulting SBML model
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000054::MODEL_STRING);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   Model* pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getNumCompartments() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumSpecies() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumInitialAssignments() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumParameters() == 5);
   const Parameter* pParameter1 = pSBMLModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getConstant() == false);
   const Parameter* pParameter2 = pSBMLModel->getParameter(1);
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter2->getConstant() == false);
   const Parameter* pParameter3 = pSBMLModel->getParameter(2);
   CPPUNIT_ASSERT(pParameter3 != NULL);
   CPPUNIT_ASSERT(pParameter3->getConstant() == false);
   const Parameter* pParameter4 = pSBMLModel->getParameter(3);
   CPPUNIT_ASSERT(pParameter4 != NULL);
   CPPUNIT_ASSERT(pParameter4->getConstant() == false);
   const Parameter* pParameter5 = pSBMLModel->getParameter(4);
   CPPUNIT_ASSERT(pParameter5 != NULL);
   CPPUNIT_ASSERT(pParameter5->getConstant() == false);
   CPPUNIT_ASSERT(pSBMLModel->getNumRules() == 5);
   const Rule* pRule = pSBMLModel->getRule(0);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getTypeCode() == SBML_ASSIGNMENT_RULE);
   const AssignmentRule* pARule = dynamic_cast<const AssignmentRule*>(pRule);
   CPPUNIT_ASSERT(pARule != NULL);
   CPPUNIT_ASSERT(pARule->getVariable() == pParameter4->getId());
   CPPUNIT_ASSERT(pARule->isSetMath() == true);
   const ASTNode* pMath = pARule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_PLUS);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 2.0) / 2.0) < 1e-15);
   const ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 4.0) / 4.0) < 1e-15);
   pRule = pSBMLModel->getRule(1);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getTypeCode() == SBML_ASSIGNMENT_RULE);
   pARule = dynamic_cast<const AssignmentRule*>(pRule);
   CPPUNIT_ASSERT(pARule != NULL);
   CPPUNIT_ASSERT(pARule->getVariable() == pParameter1->getId());
   CPPUNIT_ASSERT(pARule->isSetMath() == true);
   pMath = pARule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter4->getId());
   CPPUNIT_ASSERT(pMath->getNumChildren() == 0);
   pRule = pSBMLModel->getRule(2);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getTypeCode() == SBML_ASSIGNMENT_RULE);
   pARule = dynamic_cast<const AssignmentRule*>(pRule);
   CPPUNIT_ASSERT(pARule != NULL);
   CPPUNIT_ASSERT(pARule->getVariable() == pParameter3->getId());
   CPPUNIT_ASSERT(pARule->isSetMath() == true);
   pMath = pARule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter1->getId());
   CPPUNIT_ASSERT(pMath->getNumChildren() == 0);
   pRule = pSBMLModel->getRule(3);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getTypeCode() == SBML_ASSIGNMENT_RULE);
   pARule = dynamic_cast<const AssignmentRule*>(pRule);
   CPPUNIT_ASSERT(pARule != NULL);
   CPPUNIT_ASSERT(pARule->getVariable() == pParameter5->getId());
   CPPUNIT_ASSERT(pARule->isSetMath() == true);
   pMath = pARule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter3->getId());
   CPPUNIT_ASSERT(pMath->getNumChildren() == 0);
   pRule = pSBMLModel->getRule(4);
   CPPUNIT_ASSERT(pRule != NULL);
   CPPUNIT_ASSERT(pRule->getTypeCode() == SBML_ASSIGNMENT_RULE);
   pARule = dynamic_cast<const AssignmentRule*>(pRule);
   CPPUNIT_ASSERT(pARule != NULL);
   CPPUNIT_ASSERT(pARule->getVariable() == pParameter2->getId());
   CPPUNIT_ASSERT(pARule->isSetMath() == true);
   pMath = pARule->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
   CPPUNIT_ASSERT(pMath->getName() == pParameter5->getId());
   CPPUNIT_ASSERT(pMath->getNumChildren() == 0);
 }
Member Data Documentation
const char * test000054::MODEL_STRING static protected
Definition at line 31 of file test000054.h.
Referenced by test_bug1002().
CCopasiDataModel * test000054::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000054.h.
Referenced by setUp(), and test_bug1002().
The documentation for this class was generated from the following files:
test000054.h
test000054.cpp