COPASI API: CFitItem Class Reference
CFitItem Class Reference
#include <CFitItem.h>
Public Member Functions
bool addCrossValidation (const std::string &key)
bool addExperiment (const std::string &key)
CFitItem (const CCopasiContainer *pParent, const std::string &name="FitItem")
CFitItem (const CFitItem &src, const CCopasiContainer *pParent=NULL)
CFitItem (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
virtual C_INT32 checkConstraint () const
virtual bool compile (const std::vector< CCopasiContainer * > listOfContainer=CCopasiContainer::EmptyList)
virtual bool elevateChildren ()
virtual C_FLOAT64 getConstraintViolation () const
const std::string & getCrossValidation (const size_t &index) const
size_t getCrossValidationCount () const
std::string getCrossValidations () const
const std::string & getExperiment (const size_t &index) const
size_t getExperimentCount () const
std::string getExperiments () const
const C_FLOAT64 & getLocalValue () const
virtual const C_FLOAT64 * getObjectValue () const
virtual UpdateMethod * getUpdateMethod () const
virtual bool isValid () const
bool removeCrossValidation (const size_t &index)
bool removeExperiment (const size_t &index)
void setLocalValue (const C_FLOAT64 &value)
bool updateBounds (std::vector< COptItem * >::iterator it)
virtual ~CFitItem ()
Public Member Functions inherited from COptItem
C_INT32 checkConstraint (const C_FLOAT64 &value) const
bool checkLowerBound (const C_FLOAT64 &value) const
bool checkUpperBound (const C_FLOAT64 &value) const
COptItem (const CCopasiContainer *pParent, const std::string &name="OptimizationItem")
COptItem (const COptItem &src, const CCopasiContainer *pParent=NULL)
COptItem (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
const C_FLOAT64 & getLastStartValue () const
const std::string getLowerBound () const
const C_FLOAT64 * getLowerBoundValue () const
const CCopasiObject * getObject () const
const CCopasiObjectName getObjectCN () const
std::string getObjectDisplayName () const
C_FLOAT64 getRandomValue (CRandom *pRandom=NULL)
const C_FLOAT64 & getStartValue () const
const std::string getUpperBound () const
const C_FLOAT64 * getUpperBoundValue () const
void rememberStartValue ()
bool setLowerBound (const CCopasiObjectName &lowerBound)
bool setObjectCN (const CCopasiObjectName &objectCN)
bool setStartValue (const C_FLOAT64 &value)
bool setUpperBound (const CCopasiObjectName &upperBound)
virtual ~COptItem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static bool isValid (CCopasiParameterGroup &group)
Static Public Member Functions inherited from COptItem
static bool isValid (CCopasiParameterGroup &group)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
CFitItem ()
Protected Member Functions inherited from COptItem
COptItem ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
C_FLOAT64 mLocalValue
CCopasiParameterGroup * mpGrpAffectedCrossValidations
CCopasiParameterGroup * mpGrpAffectedExperiments
UpdateMethod * mpLocalMethod
Protected Attributes inherited from COptItem
C_FLOAT64 mLastStartValue
C_FLOAT64 mLowerBound
const C_FLOAT64 * mpLowerBound
const CCopasiObject * mpLowerObject
UpdateMethod * mpMethod
const CCopasiObject * mpObject
const C_FLOAT64 * mpObjectValue
std::string * mpParmLowerBound
std::string * mpParmObjectCN
C_FLOAT64 * mpParmStartValue
std::string * mpParmUpperBound
const C_FLOAT64 * mpUpperBound
const CCopasiObject * mpUpperObject
C_FLOAT64 mUpperBound
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void initializeParameter ()
Friends
class CFitProblem
std::ostream & operator<< (std::ostream &os, const CFitItem &o)
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from COptItem
static CRandom * mpRandom = NULL
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 22 of file CFitItem.h.
Constructor & Destructor Documentation
CFitItem::CFitItem () protected
Default constructor
CFitItem::CFitItem (const CCopasiContainer * pParent, const std::string & name = "FitItem")
Specific constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
const std::string & name (default: FitItem)
Definition at line 27 of file CFitItem.cpp.
References initializeParameter().
                                           :
   COptItem(pParent, name),
   mpGrpAffectedExperiments(NULL),
   mpGrpAffectedCrossValidations(NULL),
   mLocalValue(0),
   mpLocalMethod(new SpecificUpdateMethod<CFitItem, C_FLOAT64>(this, &CFitItem::setLocalValue))
 {initializeParameter();}
CFitItem::CFitItem (const CFitItem & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CFitItem & src
const CCopasiContainer * pParent (default: src data model)
Definition at line 36 of file CFitItem.cpp.
References initializeParameter().
                                                     :
   COptItem(src, pParent),
   mpGrpAffectedExperiments(NULL),
   mpGrpAffectedCrossValidations(NULL),
   mLocalValue(0),
   mpLocalMethod(new SpecificUpdateMethod<CFitItem, C_FLOAT64>(this, &CFitItem::setLocalValue))
 {initializeParameter();}
CFitItem::CFitItem (const CCopasiParameterGroup & group, const CCopasiContainer * pParent = NULL)
Specific constructor used for reading COPASI files
Parameters
const CCopasiParameterGroup & group
const CCopasiContainer * pParent (default: group data model)
Definition at line 45 of file CFitItem.cpp.
References initializeParameter().
                                                     :
   COptItem(group, pParent),
   mpGrpAffectedExperiments(NULL),
   mpGrpAffectedCrossValidations(NULL),
   mLocalValue(0),
   mpLocalMethod(new SpecificUpdateMethod<CFitItem, C_FLOAT64>(this, &CFitItem::setLocalValue))
 {initializeParameter();}
CFitItem::~CFitItem () virtual
Destructor
Definition at line 54 of file CFitItem.cpp.
References mpLocalMethod, and pdelete.
 {pdelete(mpLocalMethod);}
Member Function Documentation
bool CFitItem::addCrossValidation (const std::string & key)
Add an experiment to the list of affected cross validations.
Parameters
const std::string & key
Returns
bool success
Definition at line 234 of file CFitItem.cpp.
References CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::getValue(), CCopasiParameter::KEY, mpGrpAffectedCrossValidations, CCopasiParameter::Value::pKEY, and CCopasiParameterGroup::size().
Referenced by CQFittingItemWidget::save().
 {
   size_t i, imax = mpGrpAffectedCrossValidations->size();
   for (i = 0; i < imax; i++)
     if (*mpGrpAffectedCrossValidations->getValue(i).pKEY == key) return false; // The key already exists.
   return mpGrpAffectedCrossValidations->addParameter("Experiment Key", CCopasiParameter::KEY, key);
 }
bool CFitItem::addExperiment (const std::string & key)
Add an experiment to the list of affected experiments.
Parameters
const std::string & key
Returns
bool success
Definition at line 184 of file CFitItem.cpp.
References CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::getValue(), CCopasiParameter::KEY, mpGrpAffectedExperiments, CCopasiParameter::Value::pKEY, and CCopasiParameterGroup::size().
Referenced by CQFittingItemWidget::save(), and CQFittingItemWidget::slotDuplicatePerExperiment().
 {
   size_t i, imax = mpGrpAffectedExperiments->size();
   for (i = 0; i < imax; i++)
     if (*mpGrpAffectedExperiments->getValue(i).pKEY == key) return false; // The key already exists.
   return mpGrpAffectedExperiments->addParameter("Experiment Key", CCopasiParameter::KEY, key);
 }
C_INT32 CFitItem::checkConstraint () const virtual
This functions check whether the current value is within the limits of the optimization item.
Returns
C_INT32 result (-1: to small, 0: within boundaries, 1 to large)
Reimplemented from COptItem.
Reimplemented in CFitConstraint.
Definition at line 111 of file CFitItem.cpp.
References mLocalValue, COptItem::mpLowerBound, and COptItem::mpUpperBound.
Referenced by getConstraintViolation().
 {
   if (*mpLowerBound > mLocalValue) return - 1;
   if (mLocalValue > *mpUpperBound) return 1;
   return 0;
 }
bool CFitItem::compile (const std::vector< CCopasiContainer * > listOfContainer = CCopasiContainer::EmptyList) virtual
Compile the optimization item. This function must be called before any of the check functions are called.
Parameters
const std::vector< CCopasiContainer * > listOfContainer
Returns
bool success
Reimplemented from COptItem.
Definition at line 102 of file CFitItem.cpp.
References COptItem::compile(), mLocalValue, and COptItem::mpParmStartValue.
 {
   bool success = COptItem::compile(listOfContainer);
   mLocalValue = *mpParmStartValue;
   return success;
 }
bool CFitItem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 66 of file CFitItem.cpp.
References CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), mpGrpAffectedCrossValidations, mpGrpAffectedExperiments, CCopasiParameter::Value::pDOUBLE, CCopasiParameterGroup::removeParameter(), and COptItem::setStartValue().
Referenced by initializeParameter().
 {
   // The functionality of SavedValue is no handled more transparently
   // through the StartValue. Therefore, in case we encounter an old file
   // we need to copy its value.
   CCopasiParameter *pSavedValue = getParameter("SavedValue");
   if (pSavedValue)
     {
       setStartValue(*pSavedValue->getValue().pDOUBLE);
       removeParameter("SavedValue");
     }
   mpGrpAffectedExperiments =
     elevate<CCopasiParameterGroup, CCopasiParameterGroup>(mpGrpAffectedExperiments);
   if (!mpGrpAffectedExperiments) return false;
   mpGrpAffectedCrossValidations =
     elevate<CCopasiParameterGroup, CCopasiParameterGroup>(mpGrpAffectedCrossValidations);
   if (!mpGrpAffectedCrossValidations) return false;
   return true;
 }
C_FLOAT64 CFitItem::getConstraintViolation () const virtual
Retrieve the magnitude of the constraint violation This is always a positive number
Returns
C_FLOAT64 constraintViolation;
Reimplemented from COptItem.
Reimplemented in CFitConstraint.
Definition at line 120 of file CFitItem.cpp.
References checkConstraint(), mLocalValue, COptItem::mpLowerBound, and COptItem::mpUpperBound.
 {
   switch (checkConstraint())
     {
       case - 1:
         return *mpLowerBound - mLocalValue;
         break;
       case 1:
         return mLocalValue - *mpUpperBound;
         break;
     }
   return 0.0;
 }
const std::string & CFitItem::getCrossValidation (const size_t & index) const
Retreive the key of the indexed experiment.
Parameters
const size_t & index
Returns
const std::string & key
Definition at line 244 of file CFitItem.cpp.
References CCopasiParameterGroup::getValue(), mpGrpAffectedCrossValidations, CCopasiParameter::Value::pKEY, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), CQFittingItemWidget::load(), operator<<(), and CQFittingItemWidget::save().
 {
   static const std::string Empty("");
   if (index < mpGrpAffectedCrossValidations->size())
     return *mpGrpAffectedCrossValidations->getValue(index).pKEY;
   return Empty;
 }
size_t CFitItem::getCrossValidationCount () const
Retrieve the number of cross validations
Returns
size_t size
Definition at line 257 of file CFitItem.cpp.
References mpGrpAffectedCrossValidations, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), CQFittingItemWidget::load(), and CQFittingItemWidget::save().
 {return mpGrpAffectedCrossValidations->size();}
std::string CFitItem::getCrossValidations () const
Retrieve a string listing all cross validations the item applies to
Returns
std::string crossValidations
Definition at line 260 of file CFitItem.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CCopasiParameterGroup::getValue(), mpGrpAffectedCrossValidations, CCopasiParameter::Value::pKEY, and CCopasiParameterGroup::size().
 {
   std::string CrossValidations;
   size_t i, imax = mpGrpAffectedCrossValidations->size();
   const CCopasiObject * pObject;
   for (i = 0; i < imax; i++)
     {
       pObject = CCopasiRootContainer::getKeyFactory()->get(*mpGrpAffectedCrossValidations->getValue(i).pKEY);
       if (i && pObject)
         CrossValidations += ", ";
       CrossValidations += pObject->getObjectName();
     }
   return CrossValidations;
 }
const std::string & CFitItem::getExperiment (const size_t & index) const
Retreive the key of the indexed experiment.
Parameters
const size_t & index
Returns
const std::string & key
Definition at line 194 of file CFitItem.cpp.
References CCopasiParameterGroup::getValue(), mpGrpAffectedExperiments, CCopasiParameter::Value::pKEY, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), CQFittingItemWidget::load(), operator<<(), CFitProblem::printResult(), and CQFittingItemWidget::save().
 {
   static const std::string Empty("");
   if (index < mpGrpAffectedExperiments->size())
     return *mpGrpAffectedExperiments->getValue(index).pKEY;
   return Empty;
 }
size_t CFitItem::getExperimentCount () const
Retrieve the number of experiments
Returns
size_t size
Definition at line 207 of file CFitItem.cpp.
References mpGrpAffectedExperiments, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), CQFittingItemWidget::load(), CFitProblem::printResult(), and CQFittingItemWidget::save().
 {return mpGrpAffectedExperiments->size();}
std::string CFitItem::getExperiments () const
Retrieve a string listing all experiments the item applies to
Returns
std::string experiments
Definition at line 210 of file CFitItem.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CCopasiParameterGroup::getValue(), mpGrpAffectedExperiments, CCopasiParameter::Value::pKEY, and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize().
 {
   std::string Experiments;
   size_t i, imax = mpGrpAffectedExperiments->size();
   const CCopasiObject * pObject;
   for (i = 0; i < imax; i++)
     {
       pObject = CCopasiRootContainer::getKeyFactory()->get(*mpGrpAffectedExperiments->getValue(i).pKEY);
       if (pObject != NULL)
         {
           if (i != 0)
             {
               Experiments += ", ";
             }
           Experiments += pObject->getObjectName();
         }
     }
   return Experiments;
 }
const C_FLOAT64 & CFitItem::getLocalValue () const
Retreive the local value.
Returns
const C_FLOAT64 & value
Definition at line 175 of file CFitItem.cpp.
References mLocalValue.
Referenced by CFitProblem::calculate(), and updateBounds().
 {return mLocalValue;}
const C_FLOAT64 * CFitItem::getObjectValue () const virtual
Retrieve the value of the optimization object.
Returns
const C_FLOAT64 * objectValue
Reimplemented from COptItem.
Definition at line 178 of file CFitItem.cpp.
References mLocalValue.
 {return & mLocalValue;}
UpdateMethod * CFitItem::getUpdateMethod () const virtual
Retrieve the update method
Returns
UpdateMethod * pUpdateMethod
Reimplemented from COptItem.
Definition at line 181 of file CFitItem.cpp.
References mpLocalMethod.
 {return mpLocalMethod;}
void CFitItem::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 57 of file CFitItem.cpp.
References CCopasiParameterGroup::assertGroup(), elevateChildren(), mpGrpAffectedCrossValidations, and mpGrpAffectedExperiments.
Referenced by CFitItem().
 {
   mpGrpAffectedExperiments = assertGroup("Affected Experiments");
   mpGrpAffectedCrossValidations = assertGroup("Affected Cross Validation Experiments");
   elevateChildren();
 }
bool CFitItem::isValid () const virtual
Check the validity of the optimization item.
Returns
bool isValid
Reimplemented from COptItem.
Definition at line 92 of file CFitItem.cpp.
References COptItem::isValid().
Referenced by isValid().
 {return COptItem::isValid();}
bool CFitItem::isValid (CCopasiParameterGroup & group) static
Check whether the group describes a valid optimization item.
Parameters
CCopasiParameterGroup & group
Returns
bool isValid
Definition at line 95 of file CFitItem.cpp.
References isValid().
 {
   CFitItem tmp(group);
   return tmp.isValid();
 }
bool CFitItem::removeCrossValidation (const size_t & index)
Remove the indexed experiment from the affected cross validations
Parameters
const size_t & index
Returns
bool success
Definition at line 254 of file CFitItem.cpp.
References mpGrpAffectedCrossValidations, and CCopasiParameterGroup::removeParameter().
Referenced by CQFittingItemWidget::save(), and CQFittingItemWidget::slotCrossValidationChanged().
 {return mpGrpAffectedCrossValidations->removeParameter(index);}
bool CFitItem::removeExperiment (const size_t & index)
Remove the indexed experiment from the affected experiments
Parameters
const size_t & index
Returns
bool success
Definition at line 204 of file CFitItem.cpp.
References mpGrpAffectedExperiments, and CCopasiParameterGroup::removeParameter().
Referenced by CQFittingItemWidget::save(), CQFittingItemWidget::slotDuplicatePerExperiment(), and CQFittingItemWidget::slotExperimentChanged().
 {return mpGrpAffectedExperiments->removeParameter(index);}
void CFitItem::setLocalValue (const C_FLOAT64 & value)
Set the local value.
Parameters
const C_FLOAT64 & value
Definition at line 169 of file CFitItem.cpp.
References mLocalValue.
 {
   mLocalValue = value;
   return;
 }
bool CFitItem::updateBounds (std::vector< COptItem * >::iterator it)
Update bounds
Parameters
std::vector<COptItem * >::iterator it
Returns
bool success
Definition at line 279 of file CFitItem.cpp.
References getLocalValue(), COptItem::getLowerBound(), COptItem::getUpperBound(), COptItem::mpLowerBound, COptItem::mpLowerObject, COptItem::mpUpperBound, and COptItem::mpUpperObject.
Referenced by CFitProblem::initialize().
 {
   while (*it != this)
     {
       if (mpLowerObject && (getLowerBound() == (*it)->getObjectCN()))
         mpLowerBound = &static_cast<CFitItem *>(*it)->getLocalValue();
       if (mpUpperObject && (getUpperBound() == (*it)->getObjectCN()))
         mpUpperBound = &static_cast<CFitItem *>(*it)->getLocalValue();
       ++it;
     }
   return true;
 }
Friends And Related Function Documentation
friend class CFitProblem friend
Definition at line 24 of file CFitItem.h.
std::ostream& operator<< (std::ostream & os, const CFitItem & o) friend
Output stream operator
Parameters
ostream & os
const CFitItem & A
Returns
ostream & os
Definition at line 136 of file CFitItem.cpp.
 {
   os << * static_cast<const COptItem *>(&o) << std::endl;
   size_t i, imax = o.mpGrpAffectedExperiments->size();
   os << "    Affected Experiments:" << std::endl << "      ";
   if (imax == 0) os << "all";
   for (i = 0; i < imax; i++)
     {
       if (i) os << ", ";
       os << o.getExperiment(i);
     }
   imax = o.mpGrpAffectedCrossValidations->size();
   os << "    Affected Validation Experiments:" << std::endl << "      ";
   if (imax == 0) os << "all";
   for (i = 0; i < imax; i++)
     {
       if (i) os << ", ";
       os << o.getCrossValidation(i);
     }
   return os;
 }
Member Data Documentation
C_FLOAT64 CFitItem::mLocalValue protected
The value for local items, which affect the experiments in the list.
Definition at line 235 of file CFitItem.h.
Referenced by checkConstraint(), compile(), getConstraintViolation(), getLocalValue(), getObjectValue(), and setLocalValue().
CCopasiParameterGroup* CFitItem::mpGrpAffectedCrossValidations protected
A pointer to the value of the CCopasiParameterGroup holding the list of Affected Validation Experiments
Definition at line 230 of file CFitItem.h.
Referenced by addCrossValidation(), elevateChildren(), getCrossValidation(), getCrossValidationCount(), getCrossValidations(), initializeParameter(), operator<<(), and removeCrossValidation().
CCopasiParameterGroup* CFitItem::mpGrpAffectedExperiments protected
A pointer to the value of the CCopasiParameterGroup holding the list of AffectedExperiments
Definition at line 224 of file CFitItem.h.
Referenced by addExperiment(), elevateChildren(), getExperiment(), getExperimentCount(), getExperiments(), initializeParameter(), operator<<(), and removeExperiment().
UpdateMethod* CFitItem::mpLocalMethod protected
A pointer to the local update method
Definition at line 240 of file CFitItem.h.
Referenced by getUpdateMethod(), and ~CFitItem().
The documentation for this class was generated from the following files:
CFitItem.h
CFitItem.cpp