COPASI API: CQEffectDescriptionEdit Class Reference
CQEffectDescriptionEdit Class Reference
#include <CQEffectDescriptionEdit.h>
Public Slots
void slotModeChanged ()
void slotScaleEndChanged (QString)
void slotScaleStartChanged (QString)
void slotSelectColorEnd ()
void slotSelectColorStart ()
void slotSelectObject ()
Public Member Functions
CQEffectDescriptionEdit (QWidget *parent=0, Qt::WindowFlags f=0)
void initFrom (const CQEffectDescription *other, bool multiple=false)
void saveTo (CQEffectDescription *other, bool multiple=false)
CQEffectDescription * toDescription () const
~CQEffectDescriptionEdit ()
Protected Attributes
CQEffectDescription * mpCurrent
Detailed Description
Definition at line 12 of file CQEffectDescriptionEdit.h.
Constructor & Destructor Documentation
CQEffectDescriptionEdit::CQEffectDescriptionEdit (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 15 of file CQEffectDescriptionEdit.cpp.
                                                                                 :
   QWidget(parent, f),
   mpCurrent(NULL)
 {
   setupUi(this);
 }
CQEffectDescriptionEdit::~CQEffectDescriptionEdit ()
Definition at line 22 of file CQEffectDescriptionEdit.cpp.
 {
 }
Member Function Documentation
void CQEffectDescriptionEdit::initFrom (const CQEffectDescription * other, bool multiple = false)
Definition at line 47 of file CQEffectDescriptionEdit.cpp.
References CQEffectDescription::Colorize, CQEffectDescription::DropShadow, CQEffectDescription::getCN(), CQEffectDescription::getEndColor(), CQEffectDescription::getMode(), CQEffectDescription::getScaleEnd(), CQEffectDescription::getScaleStart(), CQEffectDescription::getStartColor(), CQEffectDescription::Scale, and setColor().
 {
   setColor(txtColorEnd, other->getEndColor());
   setColor(txtColorStart, other->getStartColor());
   if (multiple)
     txtObjectName->setText("");
   else
     txtObjectName->setText(other->getCN().c_str());
   txtScaleStart->setText(QString::number(other->getScaleStart()));
   txtScaleEnd->setText(QString::number(other->getScaleEnd()));
   switch (other->getMode())
     {
       case CQEffectDescription::Colorize:
         radColorize->setChecked(true);
         break;
       case CQEffectDescription::DropShadow:
         radShadow->setChecked(true);
         break;
       default:
       case CQEffectDescription::Scale:
         radScale->setChecked(true);
         break;
     }
 }
void CQEffectDescriptionEdit::saveTo (CQEffectDescription * other, bool multiple = false)
Definition at line 77 of file CQEffectDescriptionEdit.cpp.
References CQEffectDescription::Colorize, CQEffectDescription::DropShadow, CQEffectDescription::Scale, CQEffectDescription::setEndColor(), CQEffectDescription::setMode(), CQEffectDescription::setScaleEnd(), CQEffectDescription::setScaleStart(), and CQEffectDescription::setStartColor().
 {
   other->setStartColor(txtColorStart->palette().color(QPalette::Background));
   other->setEndColor(txtColorEnd->palette().color(QPalette::Background));
   other->setScaleStart(txtScaleStart->text().toDouble());
   other->setScaleEnd(txtScaleEnd->text().toDouble());
   if (radColorize->isChecked())
     other->setMode(CQEffectDescription::Colorize);
   else if (radShadow->isChecked())
     other->setMode(CQEffectDescription::DropShadow);
   else
     other->setMode(CQEffectDescription::Scale);
 }
void CQEffectDescriptionEdit::slotModeChanged () slot
Definition at line 111 of file CQEffectDescriptionEdit.cpp.
 {
 }
void CQEffectDescriptionEdit::slotScaleEndChanged (QString) slot
Definition at line 115 of file CQEffectDescriptionEdit.cpp.
 {
 }
void CQEffectDescriptionEdit::slotScaleStartChanged (QString) slot
Definition at line 119 of file CQEffectDescriptionEdit.cpp.
 {
 }
void CQEffectDescriptionEdit::slotSelectColorEnd () slot
Definition at line 127 of file CQEffectDescriptionEdit.cpp.
References getColor(), and setColor().
 {
   setColor(txtColorEnd, QColorDialog::getColor(txtColorEnd->palette().color(QPalette::Background), this));
 }
void CQEffectDescriptionEdit::slotSelectColorStart () slot
Definition at line 132 of file CQEffectDescriptionEdit.cpp.
References getColor(), and setColor().
 {
   setColor(txtColorStart, QColorDialog::getColor(txtColorStart->palette().color(QPalette::Background), this));
 }
void CQEffectDescriptionEdit::slotSelectObject () slot
Definition at line 123 of file CQEffectDescriptionEdit.cpp.
 {
 }
CQEffectDescription * CQEffectDescriptionEdit::toDescription () const
Definition at line 92 of file CQEffectDescriptionEdit.cpp.
References CQEffectDescription::Colorize, CQEffectDescription::DropShadow, CQEffectDescription::Scale, CQEffectDescription::setEndColor(), CQEffectDescription::setMode(), CQEffectDescription::setScaleEnd(), CQEffectDescription::setScaleStart(), and CQEffectDescription::setStartColor().
 {
   CQEffectDescription *result = new CQEffectDescription(txtObjectName->text().toStdString());
   result->setStartColor(txtColorStart->palette().color(QPalette::Background));
   result->setEndColor(txtColorEnd->palette().color(QPalette::Background));
   result->setScaleStart(txtScaleStart->text().toDouble());
   result->setScaleEnd(txtScaleEnd->text().toDouble());
   if (radColorize->isChecked())
     result->setMode(CQEffectDescription::Colorize);
   else if (radShadow->isChecked())
     result->setMode(CQEffectDescription::DropShadow);
   else
     result->setMode(CQEffectDescription::Scale);
   return result;
 }
Member Data Documentation
CQEffectDescription* CQEffectDescriptionEdit::mpCurrent protected
Definition at line 30 of file CQEffectDescriptionEdit.h.
The documentation for this class was generated from the following files:
CQEffectDescriptionEdit.h
CQEffectDescriptionEdit.cpp