COPASI API: test000062 Class Reference
test000062 Class Reference
#include <test000062.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_kineticlaw_without_math ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_kineticlaw_without_math)
CPPUNIT_TEST_SUITE (test000062)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
This test check if a kinetic law without math element is imported with the correct warning.
Definition at line 30 of file test000062.h.
Member Function Documentation
test000062::CPPUNIT_TEST (test_kineticlaw_without_math) private
test000062::CPPUNIT_TEST_SUITE (test000062) private
test000062::CPPUNIT_TEST_SUITE_END () private
void test000062::setUp ()
Definition at line 39 of file test000062.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000062::tearDown ()
Definition at line 47 of file test000062.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000062::test_kineticlaw_without_math ()
Definition at line 52 of file test000062.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiMessage::getType(), CCopasiRootContainer::getUndefinedFunction(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING1, pCOPASIDATAMODEL, CCopasiMessage::size(), and CCopasiMessage::WARNING.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000062::MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 0);
   // check if the reactions function is set correctly
   CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction->getFunction() == CCopasiRootContainer::getUndefinedFunction());
   // check if the correct error message has been created
 #if LIBSBML_VERSION >= 40200
   // recent libsbml versions will complain about missing math element!
   CPPUNIT_ASSERT(CCopasiMessage::size() == 2);
 #else
   CPPUNIT_ASSERT(CCopasiMessage::size() == 1);
 #endif
   const CCopasiMessage& message = CCopasiMessage::getLastMessage();
   CPPUNIT_ASSERT(message.getType() == CCopasiMessage::WARNING);
   CPPUNIT_ASSERT(message.getNumber() == MCSBML + 56);
 }
Member Data Documentation
const char * test000062::MODEL_STRING1 static protected
The units given for the two parameters in the kinetic law are wrong and they are only there to stop libsbml from issuing warnings about best modeling practice.
Definition at line 37 of file test000062.h.
Referenced by test_kineticlaw_without_math().
CCopasiDataModel * test000062::pCOPASIDATAMODEL = NULL static protected
Definition at line 38 of file test000062.h.
Referenced by setUp(), and test_kineticlaw_without_math().
The documentation for this class was generated from the following files:
test000062.h
test000062.cpp