COPASI API: CQParameterOverviewDM Class Reference
CQParameterOverviewDM Class Reference
#include <CQParameterOverviewDM.h>
Signals
void signalCloseEditor (const QModelIndex &) const
void signalOpenEditor (const QModelIndex &) const
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQParameterOverviewDM (QObject *pParent)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
virtual QModelIndex parent (const QModelIndex &index) const
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setFramework (const int &framework)
void setModelParameterset (CModelParameterSet *pModelParameterSet)
virtual ~CQParameterOverviewDM ()
Static Public Member Functions
static CModelParameter * nodeFromIndex (const QModelIndex &index)
Private Member Functions
QModelIndex index (CModelParameter *pNode) const
QVariant unitData (const CModelParameter *pNode, int role) const
QVariant valueData (const CModelParameter *pNode, int role) const
Static Private Member Functions
static QVariant assignmentData (const CModelParameter *pNode, int role)
static QVariant diffData (const CModelParameter *pNode, int role)
static int getRow (const CModelParameter *pNode)
static QVariant nameData (const CModelParameter *pNode, int role)
static QVariant typeData (const CModelParameter *pNode, int role)
Private Attributes
int mFramework
CModelParameterGroup * mpModelParameterSet
Detailed Description
Definition at line 17 of file CQParameterOverviewDM.h.
Constructor & Destructor Documentation
CQParameterOverviewDM::CQParameterOverviewDM (QObject * pParent)
Definition at line 29 of file CQParameterOverviewDM.cpp.
                                                              :
   QAbstractItemModel(pParent),
   mpModelParameterSet(NULL),
   mFramework(0)
 {
 }
CQParameterOverviewDM::~CQParameterOverviewDM () virtual
Definition at line 37 of file CQParameterOverviewDM.cpp.
 {
 }
Member Function Documentation
QVariant CQParameterOverviewDM::assignmentData (const CModelParameter * pNode, int role) static private
Definition at line 495 of file CQParameterOverviewDM.cpp.
References FROM_UTF8, CExpression::getDisplayString(), CModelParameter::getInitialExpression(), CModelParameter::getInitialExpressionPtr(), CModelParameterGroup::getModelParameter(), CModelParameter::getName(), CModelParameter::getSet(), CModelParameter::getType(), and CModelParameter::ReactionParameter.
Referenced by data().
 {
   if (role == Qt::DisplayRole)
     {
       if (pNode->getType() == CModelParameter::ReactionParameter)
         {
           CCopasiObjectName GlobalQuantityCN = static_cast< const CModelParameterReactionParameter *>(pNode)->getGlobalQuantityCN();
           CModelParameter * pGlobalQuantity = pNode->getSet()->getModelParameter(GlobalQuantityCN);
           if (pGlobalQuantity != NULL)
             {
               return QVariant(QString(FROM_UTF8(pGlobalQuantity->getName())));
             }
           return QVariant(QString(FROM_UTF8(GlobalQuantityCN)));
         }
       const CExpression* pExpression = pNode->getInitialExpressionPtr();
       if (pExpression != NULL)
         return QVariant(QString(FROM_UTF8(pExpression->getDisplayString())));
       else
         return QVariant(QString(FROM_UTF8(pNode->getInitialExpression())));
     }
   return QVariant();
 }
int CQParameterOverviewDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 42 of file CQParameterOverviewDM.cpp.
References COLUMN_COUNT.
 {
   return COLUMN_COUNT;
 }
QVariant CQParameterOverviewDM::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Definition at line 48 of file CQParameterOverviewDM.cpp.
References assignmentData(), COL_ASSIGNMENT, COL_DIFF, COL_NAME, COL_TYPE, COL_UNIT, COL_VALUE, diffData(), nameData(), nodeFromIndex(), typeData(), unitData(), and valueData().
 {
   CModelParameter * pNode = nodeFromIndex(index);
   if (pNode == NULL) return QVariant();
   switch (index.column())
     {
       case COL_NAME:
         return nameData(pNode, role);
         break;
       case COL_DIFF:
         return diffData(pNode, role);
         break;
       case COL_TYPE:
         return typeData(pNode, role);
         break;
       case COL_VALUE:
         return valueData(pNode, role);
         break;
       case COL_UNIT:
         return unitData(pNode, role);
         break;
       case COL_ASSIGNMENT:
         return assignmentData(pNode, role);
         break;
     }
   return QVariant();
 }
QVariant CQParameterOverviewDM::diffData (const CModelParameter * pNode, int role) static private
Definition at line 362 of file CQParameterOverviewDM.cpp.
References CModelParameter::Conflict, CModelParameter::getCompareResult(), CModelParameter::getType(), CModelParameter::Group, CQIconResource::icon(), CModelParameter::Identical, CModelParameter::Missing, CModelParameter::Modified, CModelParameter::Obsolete, CQIconResource::parameterConflict, CQIconResource::parameterMissing, CQIconResource::parameterModified, CQIconResource::parameterObsolete, and CModelParameter::Set.
Referenced by data().
 {
   if (pNode->getType() == CModelParameter::Group ||
       pNode->getType() == CModelParameter::Set)
     {
       return QVariant();
     }
   switch (role)
     {
       case Qt::UserRole:
         switch (pNode->getCompareResult())
           {
             case CModelParameter::Obsolete:
               return QVariant(CQIconResource::icon(CQIconResource::parameterObsolete));
               break;
             case CModelParameter::Missing:
               return QVariant(CQIconResource::icon(CQIconResource::parameterMissing));
               break;
             case CModelParameter::Modified:
               return QVariant(CQIconResource::icon(CQIconResource::parameterModified));
               break;
             case CModelParameter::Conflict:
               return QVariant(CQIconResource::icon(CQIconResource::parameterConflict));
               break;
             case CModelParameter::Identical:
               return QVariant();
               break;
           }
         break;
       case Qt::ToolTipRole:
         switch (pNode->getCompareResult())
           {
             case CModelParameter::Obsolete:
               return QVariant(QString("The item is no longer present in the model. \n\n"
                                       "Click to remove from the set."));
               break;
             case CModelParameter::Missing:
               return QVariant(QString("The item is present in the model but is missing in the parameter set. \n\n"
                                       "Click to add to the set."));
               break;
             case CModelParameter::Modified:
               return QVariant(QString("The item's value differs from the current model. \n\n"
                                       "Click to update the sets value."));
               break;
             case CModelParameter::Conflict:
               return QVariant(QString("The item's value cannot be assigned to the model object since the\n"
                                       "object is determined by an assignment. \n\n"
                                       "Click to resolve conflict."));
               break;
             case CModelParameter::Identical:
               return QVariant(QString("The item's value is identical with the current model."));
               break;
           }
         break;
       case Qt::SizeHintRole:
         return QVariant(QSize(20, 20));
         break;
     }
   return QVariant();
 }
Qt::ItemFlags CQParameterOverviewDM::flags (const QModelIndex & index) const virtual
Definition at line 85 of file CQParameterOverviewDM.cpp.
References COL_ASSIGNMENT, COL_DIFF, COL_VALUE, CModelParameter::getCompareResult(), CModelParameter::getType(), CModelParameter::Group, CModelParameter::Identical, CModelParameter::isReadOnly(), nodeFromIndex(), CModelParameter::ReactionParameter, CModelParameter::Set, signalCloseEditor(), and signalOpenEditor().
 {
   CModelParameter * pNode = nodeFromIndex(index);
   if (pNode == NULL)
     {
       return Qt::ItemIsEnabled;
     }
   if (index.column() == COL_VALUE &&
       !pNode->isReadOnly())
     {
       return QAbstractItemModel::flags(index)  | Qt::ItemIsEditable | Qt::ItemIsEnabled;
     }
   if (index.column() == COL_DIFF)
     {
       if (pNode->getCompareResult() != CModelParameter::Identical &&
           pNode->getType() != CModelParameter::Group &&
           pNode->getType() != CModelParameter::Set)
         {
           emit signalOpenEditor(index);
           return QAbstractItemModel::flags(index)  | Qt::ItemIsEditable | Qt::ItemIsEnabled;
         }
       emit signalCloseEditor(index);
     }
   if (index.column() == COL_ASSIGNMENT)
     {
       if (pNode->getType() == CModelParameter::ReactionParameter)
         {
           emit signalOpenEditor(index);
           return QAbstractItemModel::flags(index)  | Qt::ItemIsEditable | Qt::ItemIsEnabled;
         }
       emit signalCloseEditor(index);
     }
   return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
 }
int CQParameterOverviewDM::getRow (const CModelParameter * pNode) static private
Definition at line 322 of file CQParameterOverviewDM.cpp.
References CModelParameterGroup::begin(), CModelParameterGroup::end(), and CModelParameter::getParent().
Referenced by index(), and parent().
 {
   if (pNode == NULL)
     {
       return -1;
     }
   CModelParameterGroup * pParent = pNode->getParent();
   if (pParent == NULL)
     {
       return 0;
     }
   CModelParameterGroup::const_iterator it = pParent->begin();
   CModelParameterGroup::const_iterator end = pParent->end();
   for (int i = 0; it != end; ++it, ++i)
     {
       if (*it == pNode)
         {
           return i;
         }
     }
   return -1;
 }
QVariant CQParameterOverviewDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Definition at line 130 of file CQParameterOverviewDM.cpp.
References COL_ASSIGNMENT, COL_DIFF, COL_NAME, COL_TYPE, COL_UNIT, and COL_VALUE.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   switch (section)
     {
       case COL_NAME:
         return QVariant("Name");
         break;
       case COL_DIFF:
         return QVariant("");
         break;
       case COL_TYPE:
         return QVariant("Type");
         break;
       case COL_VALUE:
         return QVariant("Value");
         break;
       case COL_UNIT:
         return QVariant("Unit");
         break;
       case COL_ASSIGNMENT:
         return QVariant("Expression");
         break;
     }
   return QVariant();
 }
QModelIndex CQParameterOverviewDM::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 166 of file CQParameterOverviewDM.cpp.
References CModelParameterGroup::begin(), mpModelParameterSet, nodeFromIndex(), and CModelParameterGroup::size().
Referenced by index(), and nodeFromIndex().
 {
   CModelParameterGroup * pParent = static_cast< CModelParameterGroup *>(nodeFromIndex(parent));
   if (pParent == NULL)
     {
       return createIndex(row, column, *(mpModelParameterSet->begin() + row));
     }
   if (row < (int) pParent->size())
     return createIndex(row, column, *(pParent->begin() + row));
   else
     return QModelIndex();
 }
QModelIndex CQParameterOverviewDM::index (CModelParameter * pNode) const private
Definition at line 287 of file CQParameterOverviewDM.cpp.
References CModelParameter::getParent(), getRow(), index(), and mpModelParameterSet.
 {
   if (pNode == NULL)
     {
       return QModelIndex();
     }
   if (pNode == mpModelParameterSet)
     {
       return index(0, 0, QModelIndex());
     }
   QModelIndex Parent = index(static_cast< CModelParameter * >(pNode->getParent()));
   return index(getRow(pNode), 0, Parent);
 }
QVariant CQParameterOverviewDM::nameData (const CModelParameter * pNode, int role) static private
Definition at line 351 of file CQParameterOverviewDM.cpp.
References FROM_UTF8, and CModelParameter::getName().
Referenced by data().
 {
   if (role == Qt::DisplayRole)
     {
       return QVariant(QString(FROM_UTF8(pNode->getName())));
     }
   return QVariant();
 }
CModelParameter * CQParameterOverviewDM::nodeFromIndex (const QModelIndex & index) static
Definition at line 305 of file CQParameterOverviewDM.cpp.
References index().
Referenced by data(), flags(), index(), parent(), rowCount(), setData(), and CQParameterOverviewWidget::slotResolve().
 {
   if (!index.isValid()) return NULL;
   QModelIndex Tmp = index;
   const QAbstractItemModel *pModel = Tmp.model();
   while (pModel->inherits("QSortFilterProxyModel"))
     {
       Tmp = static_cast< const QSortFilterProxyModel *>(pModel)->mapToSource(index);
       pModel = Tmp.model();
     }
   return static_cast< CModelParameter * >(Tmp.internalPointer());
 }
QModelIndex CQParameterOverviewDM::parent (const QModelIndex & index) const virtual
Definition at line 182 of file CQParameterOverviewDM.cpp.
References CModelParameter::getParent(), getRow(), mpModelParameterSet, and nodeFromIndex().
 {
   CModelParameter * pNode = nodeFromIndex(index);
   if (pNode == NULL || pNode == mpModelParameterSet)
     {
       return QModelIndex();
     }
   if (pNode->getParent() == mpModelParameterSet)
     {
       return QModelIndex();
     }
   CModelParameter * pParent = static_cast< CModelParameter * >(pNode->getParent());
   return createIndex(getRow(pParent), 0, pParent);
 }
int CQParameterOverviewDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 202 of file CQParameterOverviewDM.cpp.
References CModelParameter::getType(), CModelParameter::Group, mpModelParameterSet, nodeFromIndex(), CModelParameter::Reaction, and CModelParameter::Set.
 {
   if (!parent.isValid())
     {
       if (mpModelParameterSet != NULL)
         return 5;
       else
         return 0;
     }
   CModelParameter * pParent = nodeFromIndex(parent);
   switch (pParent->getType())
     {
       case CModelParameter::Reaction:
       case CModelParameter::Group:
       case CModelParameter::Set:
         return (int) static_cast< CModelParameterGroup * >(pParent) ->size();
         break;
       default:
         break;
     }
   return 0;
 }
bool CQParameterOverviewDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Definition at line 230 of file CQParameterOverviewDM.cpp.
References COL_ASSIGNMENT, COL_VALUE, CModelParameter::getCN(), CModelParameterGroup::getModelParameter(), CModelParameter::getSet(), mFramework, CModelParameter::ModelValue, nodeFromIndex(), CModelParameter::setValue(), and TO_UTF8.
 {
   CModelParameter * pNode = nodeFromIndex(_index);
   bool success = false;
   if (pNode != NULL &&
       role == Qt::EditRole)
     {
       switch (_index.column())
         {
           case COL_VALUE:
             pNode->setValue(value.toDouble(), static_cast< CModelParameter::Framework >(mFramework));
             success = true;
             break;
           case COL_ASSIGNMENT:
           {
             CModelParameter * pGlobalQuantity = pNode->getSet()->getModelParameter(TO_UTF8(value.toString()), CModelParameter::ModelValue);
             if (pGlobalQuantity != NULL)
               {
                 static_cast< CModelParameterReactionParameter * >(pNode)->setGlobalQuantityCN(pGlobalQuantity->getCN());
               }
             else
               {
                 static_cast< CModelParameterReactionParameter * >(pNode)->setGlobalQuantityCN("");
               }
           }
           success = true;
           break;
         }
     }
   return success;
 }
void CQParameterOverviewDM::setFramework (const int & framework)
Definition at line 277 of file CQParameterOverviewDM.cpp.
References mFramework, and mpModelParameterSet.
Referenced by CQParameterOverviewWidget::setFramework(), and CQParameterOverviewWidget::slotResolve().
 {
   if (mpModelParameterSet != NULL)
     {
       beginResetModel();
       mFramework = framework;
       endResetModel();
     }
 }
void CQParameterOverviewDM::setModelParameterset (CModelParameterSet * pModelParameterSet)
Definition at line 267 of file CQParameterOverviewDM.cpp.
References mpModelParameterSet.
Referenced by CQParameterOverviewWidget::enterProtected(), and CQParameterOverviewWidget::slotBtnDelete().
 {
   if (mpModelParameterSet != pModelParameterSet)
     {
       beginResetModel();
       mpModelParameterSet = pModelParameterSet;
       endResetModel();
     }
 }
void CQParameterOverviewDM::signalCloseEditor (const QModelIndex &) const signal
Referenced by flags().
void CQParameterOverviewDM::signalOpenEditor (const QModelIndex &) const signal
Referenced by flags().
QVariant CQParameterOverviewDM::typeData (const CModelParameter * pNode, int role) static private
Definition at line 440 of file CQParameterOverviewDM.cpp.
References FROM_UTF8, CModelParameter::getSimulationType(), CModelParameter::getType(), CModelParameter::Group, CModelParameter::Reaction, CModelParameter::Set, and CModelEntity::StatusName.
Referenced by data().
 {
   switch (pNode->getType())
     {
       case CModelParameter::Reaction:
       case CModelParameter::Group:
       case CModelParameter::Set:
         break;
       default:
         if (role == Qt::DisplayRole)
           {
             return QVariant(QString(FROM_UTF8(CModelEntity::StatusName[pNode->getSimulationType()])));
           }
         break;
     }
   return QVariant();
 }
QVariant CQParameterOverviewDM::unitData (const CModelParameter * pNode, int role) const private
Definition at line 484 of file CQParameterOverviewDM.cpp.
References FROM_UTF8, CModelParameter::getUnit(), and mFramework.
Referenced by data().
 {
   if (role == Qt::DisplayRole)
     {
       return QVariant(QString(FROM_UTF8(pNode->getUnit(static_cast< CModelParameter::Framework >(mFramework)))));
     }
   return QVariant();
 }
QVariant CQParameterOverviewDM::valueData (const CModelParameter * pNode, int role) const private
Definition at line 462 of file CQParameterOverviewDM.cpp.
References CModelParameter::getType(), CModelParameter::getValue(), CModelParameter::Group, mFramework, CModelParameter::Reaction, and CModelParameter::Set.
Referenced by data().
 {
   switch (pNode->getType())
     {
       case CModelParameter::Reaction:
       case CModelParameter::Group:
       case CModelParameter::Set:
         break;
       default:
         if (role == Qt::EditRole)
           return QVariant(QString::number(pNode->getValue(static_cast< CModelParameter::Framework >(mFramework)), 'g', 10));
         else if (role == Qt::DisplayRole)
           return QVariant(pNode->getValue(static_cast< CModelParameter::Framework >(mFramework)));
         break;
     }
   return QVariant();
 }
Member Data Documentation
int CQParameterOverviewDM::mFramework private
Definition at line 73 of file CQParameterOverviewDM.h.
Referenced by setData(), setFramework(), unitData(), and valueData().
CModelParameterGroup* CQParameterOverviewDM::mpModelParameterSet private
Definition at line 71 of file CQParameterOverviewDM.h.
Referenced by index(), parent(), rowCount(), setFramework(), and setModelParameterset().
The documentation for this class was generated from the following files:
CQParameterOverviewDM.h
CQParameterOverviewDM.cpp