COPASI API: CCopasiXMLParser::LinearGradientElement Class Reference
CCopasiXMLParser::LinearGradientElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
LinearGradientElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~LinearGradientElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { LinearGradient = 0, GradientStop }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3789 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::LinearGradientElement::Element private
Enumerator
LinearGradient
GradientStop
Definition at line 3796 of file CCopasiXMLParser.h.
     {
       LinearGradient = 0,
       GradientStop
     };
Constructor & Destructor Documentation
CCopasiXMLParser::LinearGradientElement::LinearGradientElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 11342 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::LinearGradientElement::~LinearGradientElement () virtual
Destructor
Definition at line 11347 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::LinearGradientElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 11448 of file CCopasiXMLParser.cpp.
References CLRenderInformationBase::addGradientDefinition(), CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pGradient, SCopasiXMLParserCommon::pRenderInformation, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case LinearGradient:
         if (strcmp(pszName, "LinearGradient"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "LinearGradient", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCommon.pRenderInformation->addGradientDefinition(mCommon.pGradient);
         // delete the gradient since the add method made a copy
         delete mCommon.pGradient;
         mCommon.pGradient = NULL;
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case GradientStop:
         if (strcmp(pszName, "Stop"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Stop", mParser.getCurrentLineNumber());
         //tell the handler where to continue
         mCurrentElement = LinearGradient;
         //no need to delete Handler (since it is the only one the destructor
         //will handle it)
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::LinearGradientElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 11352 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGradientBase::PAD, SCopasiXMLParserCommon::pGradient, CLGradientBase::REFLECT, CLGradientBase::REPEAT, CLGradientBase::setId(), CLLinearGradient::setPoint1(), CLLinearGradient::setPoint2(), CLGradientBase::setSpreadMethod(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * X1;
   const char * Y1;
   const char * Z1;
   const char * X2;
   const char * Y2;
   const char * Z2;
   const char * ID;
   const char * SPREADMETHOD;
   CLLinearGradient* pLinearGradient = NULL;
   switch (mCurrentElement)
     {
       case LinearGradient:
         if (strcmp(pszName, "LinearGradient"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "LinearGradient", mParser.getCurrentLineNumber());
         X1 = mParser.getAttributeValue("x1", papszAttrs);
         Y1 = mParser.getAttributeValue("y1", papszAttrs);
         Z1 = mParser.getAttributeValue("z1", papszAttrs, false);
         X2 = mParser.getAttributeValue("x2", papszAttrs);
         Y2 = mParser.getAttributeValue("y2", papszAttrs);
         Z2 = mParser.getAttributeValue("z2", papszAttrs, false);
         ID = mParser.getAttributeValue("id", papszAttrs);
         SPREADMETHOD = mParser.getAttributeValue("spreadMethod", papszAttrs, "pad");
         pLinearGradient = new CLLinearGradient();
         pLinearGradient->setId(ID);
         if (Z1 == NULL)
           {
             pLinearGradient->setPoint1(CLRelAbsVector(X1), CLRelAbsVector(Y1));
           }
         else
           {
             pLinearGradient->setPoint1(CLRelAbsVector(X1), CLRelAbsVector(Y1), CLRelAbsVector(Z1));
           }
         if (Z2 == NULL)
           {
             pLinearGradient->setPoint2(CLRelAbsVector(X2), CLRelAbsVector(Y2));
           }
         else
           {
             pLinearGradient->setPoint2(CLRelAbsVector(X2), CLRelAbsVector(Y2), CLRelAbsVector(Z2));
           }
         if (!strcmp(SPREADMETHOD, "reflect"))
           {
             pLinearGradient->setSpreadMethod(CLGradientBase::REFLECT);
           }
         else if (!strcmp(SPREADMETHOD, "repeat"))
           {
             pLinearGradient->setSpreadMethod(CLGradientBase::REPEAT);
           }
         else
           {
             pLinearGradient->setSpreadMethod(CLGradientBase::PAD);
           }
         mCommon.pGradient = pLinearGradient;
         break;
       case GradientStop:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "Stop"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Stop", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new GradientStopElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp