COPASI API: CLReactionGlyph.cpp File Reference
CLReactionGlyph.cpp File Reference
#include <sbml/packages/layout/sbml/ReactionGlyph.h>
#include <sbml/packages/layout/sbml/SpeciesReferenceGlyph.h>
#include "copasi.h"
#include "CLReactionGlyph.h"
#include "report/CKeyFactory.h"
#include "copasi/report/CCopasiRootContainer.h"
Macros
#define USE_LAYOUT 1
Functions
std::ostream & operator<< (std::ostream &os, const CLGlyphWithCurve &g)
std::ostream & operator<< (std::ostream &os, const CLReferenceGlyph &g)
std::ostream & operator<< (std::ostream &os, const CLMetabReferenceGlyph &g)
std::ostream & operator<< (std::ostream &os, const CLGeneralGlyph &g)
std::ostream & operator<< (std::ostream &os, const CLReactionGlyph &g)
Macro Definition Documentation
#define USE_LAYOUT 1
Definition at line 17 of file CLReactionGlyph.cpp.
Function Documentation
std::ostream& operator<< (std::ostream & os, const CLGlyphWithCurve & g)
insert operator
Definition at line 94 of file CLReactionGlyph.cpp.
References CLGlyphWithCurve::mCurve.
 {
   //TODO: bounding box?
   os << g.mCurve;
   return os;
 }
std::ostream& operator<< (std::ostream & os, const CLReferenceGlyph & g)
insert operator
Definition at line 210 of file CLReactionGlyph.cpp.
References CLGraphicalObject::getModelObjectDisplayName(), CLReferenceGlyph::getTargetGlyph(), and CLGlyphWithCurve::mCurve.
 {
   os << "    ReferenceGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   const CLGraphicalObject* tmp = g.getTargetGlyph();
   if (tmp)
     os << "      refers to a Glyph that refers to "
        << tmp->getModelObjectDisplayName() << std::endl;
   os << g.mCurve; //TODO refer to base class?
   return os;
 }
std::ostream& operator<< (std::ostream & os, const CLMetabReferenceGlyph & g)
insert operator
Definition at line 362 of file CLReactionGlyph.cpp.
References CLMetabReferenceGlyph::getMetabGlyph(), CLGraphicalObject::getModelObjectDisplayName(), CLMetabReferenceGlyph::getRole(), and CLGlyphWithCurve::mCurve.
 {
   os << "    MetabReferenceGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   os << "      Role: " << CLMetabReferenceGlyph::RoleName[g.getRole()] << "\n";
   const CLMetabGlyph* tmp = g.getMetabGlyph();
   if (tmp)
     os << "      refers to a MetabGlyph that refers to "
        << tmp->getModelObjectDisplayName() << std::endl;
   os << g.mCurve;
   return os;
 }
std::ostream& operator<< (std::ostream & os, const CLGeneralGlyph & g)
insert operator
Definition at line 641 of file CLReactionGlyph.cpp.
References CLGlyphWithCurve::mCurve, CLGeneralGlyph::mvReferences, CLGeneralGlyph::mvSubglyphs, and CCopasiVector< T >::size().
 {
   os << "GeneralGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   os << g.mCurve;
   size_t i, imax = g.mvReferences.size();
   if (imax)
     {
       os << "  List of reference glyphs: \n";
       for (i = 0; i < imax; ++i)
         os << *g.mvReferences[i];
     }
   imax = g.mvSubglyphs.size();
   if (imax)
     {
       os << "  List of reference glyphs: \n";
       for (i = 0; i < imax; ++i)
         os << *g.mvSubglyphs[i];
     }
   return os;
 }
std::ostream& operator<< (std::ostream & os, const CLReactionGlyph & g)
insert operator
Definition at line 824 of file CLReactionGlyph.cpp.
References CLGlyphWithCurve::mCurve, CLReactionGlyph::mvMetabReferences, and CCopasiVector< T >::size().
 {
   os << "ReactionGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   os << g.mCurve;
   size_t i, imax = g.mvMetabReferences.size();
   if (imax)
     {
       os << "  List of metab reference glyphs: \n";
       for (i = 0; i < imax; ++i)
         os << *g.mvMetabReferences[i];
     }
   return os;
 }