COPASI API: Arguments Class Reference
Arguments Class Reference
#include <arguments.h>
Public Member Functions
Arguments (int argc, char *argv[])
const std::string & getFilename () const
const std::string & getFileType () const
char ** getInitArgs () const
const std::string & getOutputDir () const
int getOutputToGenerate () const
const std::string & getReportFile () const
const std::string & getTaskName () const
int getTaskToSwitchTo () const
bool handleCommandLine () const
bool haveFile () const
bool haveOutputDir () const
bool haveReportFile () const
bool haveTaskName () const
bool isDisablePlots () const
bool isDisableRandomizeStartValues () const
bool isDisableStatistic () const
bool isGenerateOutput () const
bool isHideWindow () const
bool isQuitAfterTaskExecution () const
bool isRunScheduled () const
bool isSaveLayout () const
bool isSolutionStatistic () const
bool isSwitchToTask () const
bool isValid () const
std::string prepareModel () const
Static Public Member Functions
static CCopasiTask * getFirstScheduledTask ()
Private Member Functions
CCopasiTask * getTask () const
CCopasiTask * getTaskForName (const std::string &name) const
void parseArgs (int arc, char *argv[])
Private Attributes
int mArgc
char ** mArgv
bool mClearTargets
bool mDisablePlots
bool mDisableRandomizeStartValues
bool mDisableStatistic
std::string mFilename
std::string mFileType
int mGenerateOutput
bool mHideWindow
std::string mOutputDir
bool mQuitAfterTaskExecution
std::string mReportFile
bool mRunScheduled
bool mSaveLayout
bool mSetSolutionStatistic
int mSwitchToTask
std::string mTask
Detailed Description
Definition at line 13 of file arguments.h.
Constructor & Destructor Documentation
Arguments::Arguments (int argc, char * argv[])
Definition at line 31 of file arguments.cpp.
References parseArgs().
   : mFilename("")
   , mOutputDir("")
   , mTask("")
   , mReportFile("")
   , mFileType("pdf")
   , mRunScheduled(false)
   , mSetSolutionStatistic(false)
   , mDisableStatistic(false)
   , mDisablePlots(false)
   , mDisableRandomizeStartValues(false)
   , mHideWindow(false)
   , mQuitAfterTaskExecution(false)
   , mClearTargets(false)
   , mSwitchToTask(-1)
   , mGenerateOutput(-1)
   , mArgc(argc)
   , mArgv(argv)
 {
   parseArgs(argc, argv);
 }
Member Function Documentation
const std::string & Arguments::getFilename () const
Definition at line 255 of file arguments.cpp.
References mFilename.
Referenced by prepareModel(), and Worker::Worker().
 {
   return mFilename;
 }
const std::string & Arguments::getFileType () const
Definition at line 260 of file arguments.cpp.
References mFileType.
Referenced by Worker::slotNotify().
 {
   return mFileType;
 }
CCopasiTask * Arguments::getFirstScheduledTask () static
Definition at line 53 of file arguments.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiTask::isScheduled(), and CCopasiVector< T >::size().
Referenced by Worker::finishedLoading(), and getTask().
 {
   CCopasiVectorN<CCopasiTask> &taskList = *(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList();
   for (size_t i = 0; i < taskList.size(); ++i)
     {
       CCopasiTask *current = taskList[i];
       if (current->isScheduled())
         return current;
     }
   return NULL;
 }
char ** Arguments::getInitArgs () const
Definition at line 247 of file arguments.cpp.
References mArgv, and mFilename.
 {
   char ** result = (char**)malloc(sizeof(char*) * 2);
   result[0] = strdup(mArgv[0]);
   result[1] = strdup((mFilename + ".view.cps").c_str());
   return result;
 }
const std::string & Arguments::getOutputDir () const
Definition at line 106 of file arguments.cpp.
References mOutputDir.
Referenced by Worker::slotNotify().
 {
   return mOutputDir;
 }
int Arguments::getOutputToGenerate () const
Definition at line 96 of file arguments.cpp.
References mGenerateOutput.
 {
   return mGenerateOutput;
 }
const std::string & Arguments::getReportFile () const
Definition at line 151 of file arguments.cpp.
References mReportFile.
 {
   return mReportFile;
 }
CCopasiTask * Arguments::getTask () const private
Definition at line 83 of file arguments.cpp.
References getFirstScheduledTask(), getTaskForName(), haveTaskName(), and mTask.
Referenced by prepareModel().
 {
   if (haveTaskName())
     return getTaskForName(mTask);
   return getFirstScheduledTask();
 }
CCopasiTask * Arguments::getTaskForName (const std::string & name) const private
Definition at line 68 of file arguments.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiObject::getObjectName(), and CCopasiVector< T >::size().
Referenced by getTask().
 {
   CCopasiVectorN<CCopasiTask> &taskList = *(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList();
   for (size_t i = 0; i < taskList.size(); ++i)
     {
       CCopasiTask *current = taskList[i];
       if (current->getObjectName() == name)
         return current;
     }
   return NULL;
 }
const std::string & Arguments::getTaskName () const
Definition at line 280 of file arguments.cpp.
References mTask.
 {
   return mTask;
 }
int Arguments::getTaskToSwitchTo () const
Definition at line 242 of file arguments.cpp.
References mSwitchToTask.
Referenced by Worker::finishedLoading().
 {
   return mSwitchToTask;
 }
bool Arguments::handleCommandLine () const
Definition at line 116 of file arguments.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiMessage::getAllMessageText(), CCopasiDataModel::getListOfLayouts(), CCopasiException::getMessage(), CCopasiObject::getObjectName(), haveFile(), haveOutputDir(), CCopasiDataModel::importSBML(), CCopasiRootContainer::init(), CCopasiDataModel::loadModel(), mFilename, mFileType, mOutputDir, mSaveLayout, CQLayoutScene::recreate(), CQLayoutScene::saveToFile(), and CCopasiVector< T >::size().
Referenced by main().
 {
   if (!(mSaveLayout && haveFile() && haveOutputDir()))
     return false;
   CCopasiRootContainer::init(0, NULL, false);
   CCopasiDataModel& model = *CCopasiRootContainer::addDatamodel();
   try
     {
       if (!model.importSBML(mFilename, NULL))
         model.loadModel(mFilename, NULL);
     }
   catch (CCopasiException &ex)
     {
       std::cerr << ex.getMessage().getAllMessageText() << std::endl;
       return true;
     }
   for (size_t i = 0; i < model.getListOfLayouts()->size(); ++i)
     {
       CLayout* layout = (*model.getListOfLayouts())[i];
       CQLayoutScene scene(layout, &model);
       scene.recreate();
       scene.saveToFile(mOutputDir + "/" + QFileInfo(mFilename.c_str()).baseName().toStdString() + "_" + layout->getObjectName() + "." + mFileType, mFileType);
     }
   return true;
 }
bool Arguments::haveFile () const
Definition at line 265 of file arguments.cpp.
References mFilename.
Referenced by handleCommandLine(), and isValid().
 {
   return !mFilename.empty();
 }
bool Arguments::haveOutputDir () const
Definition at line 101 of file arguments.cpp.
References mOutputDir.
Referenced by handleCommandLine(), and Worker::slotNotify().
 {
   return !mOutputDir.empty();
 }
bool Arguments::haveReportFile () const
Definition at line 111 of file arguments.cpp.
References mReportFile.
Referenced by prepareModel().
 {
   return !mReportFile.empty();
 }
bool Arguments::haveTaskName () const
Definition at line 275 of file arguments.cpp.
References mTask.
Referenced by getTask().
 {
   return !mTask.empty();
 }
bool Arguments::isDisablePlots () const
Definition at line 300 of file arguments.cpp.
References mDisablePlots.
 {
   return mDisablePlots;
 }
bool Arguments::isDisableRandomizeStartValues () const
Definition at line 295 of file arguments.cpp.
References mDisableRandomizeStartValues.
Referenced by prepareModel().
 {
   return mDisableRandomizeStartValues;
 }
bool Arguments::isDisableStatistic () const
Definition at line 290 of file arguments.cpp.
References mDisableStatistic.
Referenced by prepareModel().
 {
   return mDisableStatistic;
 }
bool Arguments::isGenerateOutput () const
Definition at line 91 of file arguments.cpp.
References mGenerateOutput.
Referenced by prepareModel().
 {
   return mGenerateOutput != -1;
 }
bool Arguments::isHideWindow () const
Definition at line 305 of file arguments.cpp.
References mHideWindow.
Referenced by Worker::finishedLoading().
 {
   return mHideWindow;
 }
bool Arguments::isQuitAfterTaskExecution () const
Definition at line 310 of file arguments.cpp.
References mQuitAfterTaskExecution.
Referenced by Worker::slotNotify().
 {
   return mQuitAfterTaskExecution;
 }
bool Arguments::isRunScheduled () const
Definition at line 270 of file arguments.cpp.
References mRunScheduled.
Referenced by Worker::finishedLoading().
 {
   return mRunScheduled;
 }
bool Arguments::isSaveLayout () const
Definition at line 146 of file arguments.cpp.
References mSaveLayout.
 {
   return mSaveLayout;
 }
bool Arguments::isSolutionStatistic () const
Definition at line 285 of file arguments.cpp.
References mSetSolutionStatistic.
 {
   return mSetSolutionStatistic;
 }
bool Arguments::isSwitchToTask () const
Definition at line 237 of file arguments.cpp.
References mSwitchToTask.
Referenced by Worker::finishedLoading().
 {
   return mSwitchToTask != -1;
 }
bool Arguments::isValid () const
Definition at line 315 of file arguments.cpp.
References haveFile(), and mFilename.
Referenced by main(), and prepareModel().
 {
   if (!haveFile()) return false;
   if (!QFile(mFilename.c_str()).exists()) return false;
   return true;
 }
void Arguments::parseArgs (int arc, char * argv[]) private
Definition at line 156 of file arguments.cpp.
References mClearTargets, mDisablePlots, mDisableRandomizeStartValues, mDisableStatistic, mFilename, mFileType, mGenerateOutput, mHideWindow, mOutputDir, mQuitAfterTaskExecution, mReportFile, mRunScheduled, mSaveLayout, mSetSolutionStatistic, mSwitchToTask, and mTask.
Referenced by Arguments().
 {
   for (int i = 1; i < argc; ++i)
     {
       QString current(argv[i]);
       QString lower = current.toLower();
       if (lower == "-r" || lower == "--run-scheduled")
         {
           mRunScheduled = true;
         }
       else if (lower == "-q" || lower == "--quit-after-task-execution")
         {
           mQuitAfterTaskExecution = true;
         }
       else if (i + 1 < argc && (lower == "--switch-to-task"))
         {
           mSwitchToTask = QString(argv[i + 1]).toInt();
           ++i;
         }
       else if (i + 1 < argc && (lower == "--task"))
         {
           mTask = argv[i + 1];
           ++i;
         }
       else if (lower == "--set-solution-statistic")
         {
           mSetSolutionStatistic = true;
         }
       else if (lower == "--disable-calculate-statistic")
         {
           mDisableStatistic = true;
         }
       else if (lower == "--disable-other-plots")
         {
           mDisablePlots = true;
         }
       else if (lower == "--hide")
         {
           mHideWindow = true;
         }
       else if (lower == "--clear-targets")
         {
           mClearTargets = true;
         }
       else if (lower == "--disable-randomize-startvalues")
         {
           mDisableRandomizeStartValues = true;
         }
       else if (lower == "--save-layout")
         {
           mSaveLayout = true;
         }
       else if (i + 1 < argc && (lower == "-g" || lower == "--generate-output"))
         {
           mGenerateOutput = QString(argv[i + 1]).toInt();
           ++i;
         }
       else if (i + 1 < argc && (lower == "-f" || lower == "--set-report-file"))
         {
           mReportFile = argv[i + 1];
           ++i;
         }
       else if (i + 1 < argc && (lower == "-o" || lower == "--set-output-dir"))
         {
           mOutputDir = argv[i + 1];
           ++i;
         }
       else if (i + 1 < argc && (lower == "-t" || lower == "--set-file-type"))
         {
           mFileType = argv[i + 1];
           ++i;
         }
       else if (QFile(current).exists() && mFilename.empty())
         {
           // only if we don't have a file yet, we assume this to be the copasi file
           mFilename = current.toStdString();
         }
     }
 }
std::string Arguments::prepareModel () const
Definition at line 324 of file arguments.cpp.
References COutputAssistant::createDefaultOutput(), CCopasiRootContainer::getDatamodelList(), getFilename(), COutputAssistant::getListOfDefaultOutputDescriptions(), CCopasiDataModel::getPlotDefinitionList(), CCopasiTask::getProblem(), CCopasiTask::getReport(), getTask(), CCopasiDataModel::getTaskList(), haveReportFile(), isDisableRandomizeStartValues(), isDisableStatistic(), isGenerateOutput(), isValid(), CCopasiDataModel::loadModel(), mClearTargets, mDisablePlots, mGenerateOutput, mReportFile, mSetSolutionStatistic, CCopasiDataModel::saveModel(), COptProblem::setCalculateStatistics(), COptTask::setMethodType(), COptProblem::setRandomizeStartValues(), CReport::setTarget(), CCopasiVector< T >::size(), and CCopasiMethod::Statistics.
Referenced by main().
 {
   if (!isValid()) return "";
   CCopasiDataModel* model = (*CCopasiRootContainer::getDatamodelList())[0];
   model->loadModel(getFilename(), NULL);
   if (mDisablePlots)
     {
       for (size_t index = 0; index < model->getPlotDefinitionList()->size(); ++index)
         {
           (*model->getPlotDefinitionList())[index]->setActive(false);
         }
     }
   if (mClearTargets)
     {
       for (size_t index = 0; index < model->getTaskList()->size(); ++index)
         {
           (*model->getTaskList())[index]->getReport().setTarget("");
         }
     }
   CCopasiTask *task = getTask();
   if (task != NULL)
     {
       if (isGenerateOutput())
         {
           // calls initialize which is private
           COutputAssistant::getListOfDefaultOutputDescriptions();
           // generate the output
           COutputAssistant::createDefaultOutput(mGenerateOutput, task, model);
         }
       if (haveReportFile())
         task->getReport().setTarget(mReportFile);
       COptTask* optTask = dynamic_cast<COptTask*>(task);
       if (optTask != NULL)
         {
           COptProblem *problem = (COptProblem *)optTask->getProblem();
           if (mSetSolutionStatistic)
             optTask->setMethodType(CCopasiMethod::Statistics);
           if (isDisableRandomizeStartValues())
             problem->setRandomizeStartValues(false);
           if (isDisableStatistic())
             problem->setCalculateStatistics(false);
         }
     }
   model->saveModel(getFilename() + ".view.cps", NULL, true);
   return getFilename() + ".view.cps";
 }
Member Data Documentation
int Arguments::mArgc private
Definition at line 112 of file arguments.h.
char** Arguments::mArgv private
Definition at line 114 of file arguments.h.
Referenced by getInitArgs().
bool Arguments::mClearTargets private
Definition at line 106 of file arguments.h.
Referenced by parseArgs(), and prepareModel().
bool Arguments::mDisablePlots private
Definition at line 98 of file arguments.h.
Referenced by isDisablePlots(), parseArgs(), and prepareModel().
bool Arguments::mDisableRandomizeStartValues private
Definition at line 100 of file arguments.h.
Referenced by isDisableRandomizeStartValues(), and parseArgs().
bool Arguments::mDisableStatistic private
Definition at line 96 of file arguments.h.
Referenced by isDisableStatistic(), and parseArgs().
std::string Arguments::mFilename private
Definition at line 80 of file arguments.h.
Referenced by getFilename(), getInitArgs(), handleCommandLine(), haveFile(), isValid(), and parseArgs().
std::string Arguments::mFileType private
Definition at line 88 of file arguments.h.
Referenced by getFileType(), handleCommandLine(), and parseArgs().
int Arguments::mGenerateOutput private
Definition at line 110 of file arguments.h.
Referenced by getOutputToGenerate(), isGenerateOutput(), parseArgs(), and prepareModel().
bool Arguments::mHideWindow private
Definition at line 102 of file arguments.h.
Referenced by isHideWindow(), and parseArgs().
std::string Arguments::mOutputDir private
Definition at line 82 of file arguments.h.
Referenced by getOutputDir(), handleCommandLine(), haveOutputDir(), and parseArgs().
bool Arguments::mQuitAfterTaskExecution private
Definition at line 104 of file arguments.h.
Referenced by isQuitAfterTaskExecution(), and parseArgs().
std::string Arguments::mReportFile private
Definition at line 86 of file arguments.h.
Referenced by getReportFile(), haveReportFile(), parseArgs(), and prepareModel().
bool Arguments::mRunScheduled private
Definition at line 90 of file arguments.h.
Referenced by isRunScheduled(), and parseArgs().
bool Arguments::mSaveLayout private
Definition at line 92 of file arguments.h.
Referenced by handleCommandLine(), isSaveLayout(), and parseArgs().
bool Arguments::mSetSolutionStatistic private
Definition at line 94 of file arguments.h.
Referenced by isSolutionStatistic(), parseArgs(), and prepareModel().
int Arguments::mSwitchToTask private
Definition at line 108 of file arguments.h.
Referenced by getTaskToSwitchTo(), isSwitchToTask(), and parseArgs().
std::string Arguments::mTask private
Definition at line 84 of file arguments.h.
Referenced by getTask(), getTaskName(), haveTaskName(), and parseArgs().
The documentation for this class was generated from the following files:
arguments.h
arguments.cpp