COPASI API: CNormalItemPower Class Reference
CNormalItemPower Class Reference
#include <CNormalItemPower.h>
Public Types
enum ItemType {
ITEM, FUNCTION, POWER, CHOICE,
CALL, LOGICAL, INVALID
}
Public Member Functions
CNormalItemPower ()
CNormalItemPower (const CNormalItemPower &src)
CNormalItemPower (const CNormalBase &item, const C_FLOAT64 &exp)
virtual CNormalBase * copy () const
const C_FLOAT64 & getExp () const
CNormalBase & getItem ()
const CNormalBase & getItem () const
ItemType getItemType () const
bool operator< (const CNormalItemPower &rhs) const
CNormalItemPower & operator= (const CNormalItemPower &src)
bool operator== (const CNormalItemPower &rhs) const
bool setExp (const C_FLOAT64 &number)
bool setItem (const CNormalBase &item)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalItemPower ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Protected Attributes
C_FLOAT64 mExp
ItemType mItemType
CNormalBase * mpItem
Friends
std::ostream & operator<< (std::ostream &os, const CNormalItemPower &d)
Detailed Description
The class for powers of items with real positive exponent used in CNormal
Definition at line 34 of file CNormalItemPower.h.
Member Enumeration Documentation
enum CNormalItemPower::ItemType
Enumerator
ITEM
FUNCTION
POWER
CHOICE
CALL
LOGICAL
INVALID
Definition at line 37 of file CNormalItemPower.h.
   {
     ITEM,
     FUNCTION,
     POWER,
     CHOICE,
     CALL,
     LOGICAL,
     INVALID
   };
Constructor & Destructor Documentation
CNormalItemPower::CNormalItemPower ()
Default constructor
Definition at line 45 of file CNormalItemPower.cpp.
Referenced by copy().
                                   : CNormalBase(), mpItem(NULL), mExp(1.0), mItemType(CNormalItemPower::INVALID)
 {}
CNormalItemPower::CNormalItemPower (const CNormalItemPower & src)
Copy Constructor
Definition at line 51 of file CNormalItemPower.cpp.
References CNormalBase::copy(), INVALID, mItemType, and mpItem.
                                                              : CNormalBase(src), mpItem(NULL), mExp(src.mExp), mItemType(src.mItemType)
 {
   if (this->mItemType != CNormalItemPower::INVALID)
     {
       this->mpItem = src.mpItem->copy();
     }
 }
CNormalItemPower::~CNormalItemPower () virtual
Destructor
Definition at line 59 of file CNormalItemPower.cpp.
References mpItem.
 {
   if (this->mpItem != NULL) delete this->mpItem;
 }
CNormalItemPower::CNormalItemPower (const CNormalBase & item, const C_FLOAT64 & exp)
Data constructor
Definition at line 89 of file CNormalItemPower.cpp.
References mExp, and setItem().
     : mpItem(NULL), mExp(exp), mItemType(CNormalItemPower::INVALID)
 {
   if (!this->setItem(item))
     {
       this->mExp = 1.0;
     }
 }
Member Function Documentation
CNormalBase * CNormalItemPower::copy () const virtual
Implements CNormalBase.
Definition at line 372 of file CNormalItemPower.cpp.
References CNormalItemPower().
 {
   return new CNormalItemPower(*this);
 }
const C_FLOAT64 & CNormalItemPower::getExp () const
Retrieve the exponent of this power
Returns
mExp
Definition at line 191 of file CNormalItemPower.cpp.
References mExp.
Referenced by CNormalLcm::add(), convertToCEvaluationNode(), CNormalProduct::multiply(), CNormalFraction::multiply(), CNormalLcm::remove(), CNormalProduct::remove(), test_biomodels217_expression::test_term_den1(), test_biomodels217_expression::test_term_den2(), test_biomodels217_expression::test_term_den3(), test_biomodels217_expression::test_term_den4(), test_biomodels217_expression::test_term_den5(), test_biomodels217_expression::test_term_den6(), test_biomodels217_expression::test_term_den7(), test_biomodels217_expression::test_term_num1(), test_biomodels217_expression::test_term_num2(), test_biomodels217_expression::test_term_num3(), test_biomodels217_expression::test_term_num4(), test_biomodels217_expression::test_term_num5(), test_biomodels217_expression::test_term_num6(), and test_biomodels217_expression::test_term_num7().
 {
   return mExp;
 }
CNormalBase & CNormalItemPower::getItem ()
Retrieve the base of this power
Returns
mItem
Definition at line 173 of file CNormalItemPower.cpp.
References mpItem.
Referenced by CNormalLcm::add(), convertToCEvaluationNode(), CNormalProduct::multiply(), CNormalFraction::multiply(), normalize_variable_names(), CNormalLcm::remove(), CNormalProduct::remove(), test_biomodels217_expression::test_term_den1(), test_biomodels217_expression::test_term_den2(), test_biomodels217_expression::test_term_den3(), test_biomodels217_expression::test_term_den4(), test_biomodels217_expression::test_term_den5(), test_biomodels217_expression::test_term_den6(), test_biomodels217_expression::test_term_den7(), test_biomodels217_expression::test_term_num1(), test_biomodels217_expression::test_term_num2(), test_biomodels217_expression::test_term_num3(), test_biomodels217_expression::test_term_num4(), test_biomodels217_expression::test_term_num5(), test_biomodels217_expression::test_term_num6(), and test_biomodels217_expression::test_term_num7().
 {
   return *mpItem;
 }
const CNormalBase & CNormalItemPower::getItem () const
Retrieve the base of this power
Returns
mItem
Definition at line 182 of file CNormalItemPower.cpp.
References mpItem.
 {
   return *mpItem;
 }
CNormalItemPower::ItemType CNormalItemPower::getItemType () const
Definition at line 377 of file CNormalItemPower.cpp.
References mItemType.
Referenced by test_biomodels217_expression::test_term_den1(), test_biomodels217_expression::test_term_den2(), test_biomodels217_expression::test_term_den3(), test_biomodels217_expression::test_term_den4(), test_biomodels217_expression::test_term_den5(), test_biomodels217_expression::test_term_den6(), test_biomodels217_expression::test_term_den7(), test_biomodels217_expression::test_term_num1(), test_biomodels217_expression::test_term_num2(), test_biomodels217_expression::test_term_num3(), test_biomodels217_expression::test_term_num4(), test_biomodels217_expression::test_term_num5(), test_biomodels217_expression::test_term_num6(), and test_biomodels217_expression::test_term_num7().
 {
   return this->mItemType;
 }
bool CNormalItemPower::operator< (const CNormalItemPower & rhs) const
Examine inequality of two item powers.
Returns
bool.
Definition at line 240 of file CNormalItemPower.cpp.
References CALL, CHOICE, FUNCTION, INVALID, ITEM, LOGICAL, mExp, mItemType, mpItem, and POWER.
 {
   bool result = false;
   if (this->mItemType < rhs.mItemType)
     {
       result = true;
     }
   else if (this->mItemType == rhs.mItemType)
     {
       switch (this->mItemType)
         {
           case CNormalItemPower::ITEM:
             result = (dynamic_cast<CNormalItem&>(*this->mpItem) < dynamic_cast<CNormalItem&>(*rhs.mpItem));
             if (!result)
               {
                 result = !(dynamic_cast<CNormalItem&>(*rhs.mpItem) < dynamic_cast<CNormalItem&>(*this->mpItem));
                 if (result)
                   {
                     result = (rhs.mExp < this->mExp);
                   }
               }
             break;
           case CNormalItemPower::FUNCTION:
             result = (dynamic_cast<CNormalFunction&>(*this->mpItem) < dynamic_cast<CNormalFunction&>(*rhs.mpItem));
             if (!result)
               {
                 result = !(dynamic_cast<CNormalFunction&>(*rhs.mpItem) < dynamic_cast<CNormalFunction&>(*this->mpItem));
                 if (result)
                   {
                     result = (rhs.mExp < this->mExp);
                   }
               }
             break;
           case CNormalItemPower::POWER:
             result = (dynamic_cast<CNormalGeneralPower&>(*this->mpItem) < dynamic_cast<CNormalGeneralPower&>(*rhs.mpItem));
             if (!result)
               {
                 result = !(dynamic_cast<CNormalGeneralPower&>(*rhs.mpItem) < dynamic_cast<CNormalGeneralPower&>(*this->mpItem));
                 if (result)
                   {
                     result = (rhs.mExp < this->mExp);
                   }
               }
             break;
           case CNormalItemPower::CHOICE:
             result = (dynamic_cast<CNormalChoice&>(*this->mpItem) < dynamic_cast<CNormalChoice&>(*rhs.mpItem));
             if (!result)
               {
                 result = !(dynamic_cast<CNormalChoice&>(*rhs.mpItem) < dynamic_cast<CNormalChoice&>(*this->mpItem));
                 if (result)
                   {
                     result = (rhs.mExp < this->mExp);
                   }
               }
             break;
           case CNormalItemPower::CALL:
             result = (dynamic_cast<CNormalCall&>(*this->mpItem) < dynamic_cast<CNormalCall&>(*rhs.mpItem));
             if (!result)
               {
                 result = !(dynamic_cast<CNormalCall&>(*rhs.mpItem) < dynamic_cast<CNormalCall&>(*this->mpItem));
                 if (result)
                   {
                     result = (rhs.mExp < this->mExp);
                   }
               }
             break;
           case CNormalItemPower::LOGICAL:
             result = (dynamic_cast<CNormalLogical&>(*this->mpItem) < dynamic_cast<CNormalLogical&>(*rhs.mpItem));
             if (!result)
               {
                 result = !(dynamic_cast<CNormalLogical&>(*rhs.mpItem) < dynamic_cast<CNormalLogical&>(*this->mpItem));
                 if (result)
                   {
                     result = (rhs.mExp < this->mExp);
                   }
               }
             break;
           case CNormalItemPower::INVALID:
             result = false;
             break;
         }
     }
   return result;
 }
CNormalItemPower & CNormalItemPower::operator= (const CNormalItemPower & src)
Assignment operator Constructor
Definition at line 67 of file CNormalItemPower.cpp.
References CNormalBase::copy(), INVALID, mExp, mItemType, and mpItem.
 {
   if (this->mpItem != NULL) delete this->mpItem;
   this->mItemType = src.mItemType;
   if (this->mItemType != CNormalItemPower::INVALID)
     {
       this->mpItem = src.mpItem->copy();
     }
   else
     {
       this->mpItem = NULL;
     }
   mExp = src.mExp;
   return *this;
 }
bool CNormalItemPower::operator== (const CNormalItemPower & rhs) const
Examine equality of two item powers.
Returns
bool.
Definition at line 200 of file CNormalItemPower.cpp.
References CALL, CHOICE, FUNCTION, INVALID, ITEM, LOGICAL, mExp, mItemType, mpItem, and POWER.
 {
   bool result = (this->mItemType == rhs.mItemType);
   result &= (this->mExp == rhs.mExp);
   if (result == true)
     {
       switch (this->mItemType)
         {
           case CNormalItemPower::ITEM:
             result = (dynamic_cast<CNormalItem&>(*this->mpItem) == dynamic_cast<CNormalItem&>(*rhs.mpItem));
             break;
           case CNormalItemPower::FUNCTION:
             result = (dynamic_cast<CNormalFunction&>(*this->mpItem) == dynamic_cast<CNormalFunction&>(*rhs.mpItem));
             break;
           case CNormalItemPower::POWER:
             result = (dynamic_cast<CNormalGeneralPower&>(*this->mpItem) == dynamic_cast<CNormalGeneralPower&>(*rhs.mpItem));
             break;
           case CNormalItemPower::CHOICE:
             result = (dynamic_cast<CNormalChoice&>(*this->mpItem) == dynamic_cast<CNormalChoice&>(*rhs.mpItem));
             break;
           case CNormalItemPower::CALL:
             result = (dynamic_cast<CNormalCall&>(*this->mpItem) == dynamic_cast<CNormalCall&>(*rhs.mpItem));
             break;
           case CNormalItemPower::LOGICAL:
             result = (dynamic_cast<CNormalLogical&>(*this->mpItem) == dynamic_cast<CNormalLogical&>(*rhs.mpItem));
             break;
           case CNormalItemPower::INVALID:
             result = true;
             break;
         }
     }
   return result;
 }
bool CNormalItemPower::setExp (const C_FLOAT64 & number)
Set the exponent of this power
Returns
true
Definition at line 160 of file CNormalItemPower.cpp.
References mExp.
Referenced by createItemPower(), CNormalSum::simplify(), CNormalProduct::simplify(), and test_simplify::test_simplify_1().
 {
   if (mExp < 0.0)
     return false;
   mExp = number;
   return true;
 }
bool CNormalItemPower::setItem (const CNormalBase & item)
Set the base of this itempower.
Returns
true.
Definition at line 102 of file CNormalItemPower.cpp.
References CALL, CHOICE, CNormalBase::copy(), FUNCTION, ITEM, LOGICAL, mItemType, mpItem, and POWER.
Referenced by CNormalItemPower(), createItemPower(), CNormalSum::simplify(), CNormalProduct::simplify(), and test_simplify::test_simplify_1().
 {
   bool result = true;
   if (dynamic_cast<const CNormalItem*>(&item))
     {
       if (this->mpItem != NULL) delete this->mpItem;
       this->mItemType = CNormalItemPower::ITEM;
       this->mpItem = item.copy();
     }
   else if (dynamic_cast<const CNormalFunction*>(&item))
     {
       if (this->mpItem != NULL) delete this->mpItem;
       this->mItemType = CNormalItemPower::FUNCTION;
       this->mpItem = item.copy();
     }
   else if (dynamic_cast<const CNormalGeneralPower*>(&item))
     {
       if (this->mpItem != NULL) delete this->mpItem;
       this->mItemType = CNormalItemPower::POWER;
       this->mpItem = item.copy();
     }
   else if (dynamic_cast<const CNormalChoice*>(&item))
     {
       if (this->mpItem != NULL) delete this->mpItem;
       this->mItemType = CNormalItemPower::CHOICE;
       this->mpItem = item.copy();
     }
   else if (dynamic_cast<const CNormalCall*>(&item))
     {
       if (this->mpItem != NULL) delete this->mpItem;
       this->mItemType = CNormalItemPower::CALL;
       this->mpItem = item.copy();
     }
   else if (dynamic_cast<const CNormalLogical*>(&item))
     {
       if (this->mpItem != NULL) delete this->mpItem;
       this->mItemType = CNormalItemPower::LOGICAL;
       this->mpItem = item.copy();
     }
   else
     {
       result = false;
     }
   return result;
 }
bool CNormalItemPower::simplify () virtual
Implements CNormalBase.
Definition at line 382 of file CNormalItemPower.cpp.
References mpItem, and CNormalBase::simplify().
Referenced by CNormalProduct::simplify(), and test_simplify::test_simplify_1().
 {
   return this->mpItem->simplify();
 }
std::string CNormalItemPower::toString () const virtual
Implements CNormalBase.
Definition at line 351 of file CNormalItemPower.cpp.
References CALL, FUNCTION, ITEM, LOGICAL, mExp, mItemType, mpItem, POWER, and CNormalBase::toString().
Referenced by operator<<().
 {
   std::ostringstream os;
   if (this->mItemType == CNormalItemPower::ITEM || this->mItemType == CNormalItemPower::LOGICAL || this->mItemType == CNormalItemPower::FUNCTION || this->mItemType == CNormalItemPower::CALL || (this->mItemType == CNormalItemPower::POWER && this->mExp == 1.0))
     {
       os << this->mpItem->toString();
     }
   else
     {
       os << "(" << this->mpItem->toString() << ")";
     }
   if (this->mExp != 1.0)
     {
       os << "^" << this->mExp;
     }
   return os.str();
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CNormalItemPower & d) friend
Definition at line 345 of file CNormalItemPower.cpp.
 {
   os << d.toString();
   return os;
 }
Member Data Documentation
C_FLOAT64 CNormalItemPower::mExp protected
Definition at line 54 of file CNormalItemPower.h.
Referenced by CNormalItemPower(), getExp(), operator<(), operator=(), operator==(), setExp(), and toString().
ItemType CNormalItemPower::mItemType protected
Definition at line 56 of file CNormalItemPower.h.
Referenced by CNormalItemPower(), getItemType(), operator<(), operator=(), operator==(), setItem(), and toString().
CNormalBase* CNormalItemPower::mpItem protected
Enumeration of members.
Definition at line 53 of file CNormalItemPower.h.
Referenced by CNormalItemPower(), getItem(), operator<(), operator=(), operator==(), setItem(), simplify(), toString(), and ~CNormalItemPower().
The documentation for this class was generated from the following files:
CNormalItemPower.h
CNormalItemPower.cpp