COPASI API: Expression2PresentationMMLUnits Class Reference
Expression2PresentationMMLUnits Class Reference
#include <Expression2PresentationMMLUnits.h>
Public Member Functions
Expression2PresentationMMLUnits (const ASTNode *rootnode)
std::string getMathML (const CSBMLunitInformation &ui) const
void setUnitInterface (CSBMLunitInterface *unitInterface, CSBMLunitInterface *unitInterface2)
Public Member Functions inherited from Expression2PresentationMML
Expression2PresentationMML (const ASTNode *rootnode)
void setModel (const Model *m)
void setReaction (const Reaction *m)
void setUseReactionNameInLocalParameters (bool b)
void writeMathML (std::ostream &out) const
virtual ~Expression2PresentationMML ()
Protected Member Functions
std::string getMathML (const UnitDefinition &ud) const
std::string getMathML (const Unit *u, bool absExp) const
void writeMathMLBox (std::ostream &out, const std::string &a, const std::string &b, const std::string &color, size_t l) const
void writeMathMLBox (std::ostream &out, const std::string &a, const std::string &b, const std::string &c, const std::string &color, size_t l) const
virtual void writeMathMLName (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLNumber (std::ostream &out, const ASTNode *node, size_t l) const
Protected Member Functions inherited from Expression2PresentationMML
void writeMathML (std::ostream &out, const ASTNode *node, size_t l) const
virtual void writeMathMLFunction (std::ostream &out, const ASTNode *node, size_t l) const
Protected Attributes
CSBMLunitInterface * mpUnitInterface
CSBMLunitInterface * mpUnitInterface2
Protected Attributes inherited from Expression2PresentationMML
const Model * mpModel
const Reaction * mpReaction
const ASTNode * mRootNode
bool mUseReactionNameInLocalParameters
Detailed Description
Definition at line 24 of file Expression2PresentationMMLUnits.h.
Constructor & Destructor Documentation
Expression2PresentationMMLUnits::Expression2PresentationMMLUnits (const ASTNode * rootnode)
Definition at line 18 of file Expression2PresentationMMLUnits.cpp.
     : Expression2PresentationMML(rootnode),
     mpUnitInterface(NULL)
 {
 }
Member Function Documentation
std::string Expression2PresentationMMLUnits::getMathML (const CSBMLunitInformation & ui) const
Definition at line 115 of file Expression2PresentationMMLUnits.cpp.
References CSBMLunitInformation::DEFAULT, CSBMLunitInformation::DERIVED, CSBMLunitInformation::getInfo(), CSBMLunit::getSBMLUnitDefinition(), CSBMLunit::getSymbolicExpExp(), CSBMLunit::getSymbolicExponent(), CSBMLunitInformation::GLOBAL, CSBMLunitInformation::isConflict(), CSBMLunitInformation::PROVIDED, and CSBMLunitInformation::UNKNOWN.
Referenced by getMathML(), writeMathMLName(), and writeMathMLNumber().
 {
   std::string tmp;
   tmp += "<mrow>";
   if (ui.isConflict())
     tmp += "<mi mathcolor = \"red\">conflict!</mi>";
   if (ui.getSymbolicExpExp() > 0)
     tmp += "<mfenced>";
   switch (ui.getInfo())
     {
       case CSBMLunitInformation::UNKNOWN:
         tmp += "<mi mathcolor = \"orange\">unknown</mi>";
         break;
       case CSBMLunitInformation::DEFAULT:
         tmp += "<mstyle mathcolor=\"#000060\">" + getMathML(ui.getSBMLUnitDefinition()) + "</mstyle>";
         break;
       case CSBMLunitInformation::GLOBAL:
         tmp += "<mstyle mathcolor=\"#0000a0\">" + getMathML(ui.getSBMLUnitDefinition()) + "</mstyle>";
         break;
       case CSBMLunitInformation::PROVIDED:
         tmp += "<mstyle mathcolor=\"#2020ff\">" + getMathML(ui.getSBMLUnitDefinition()) + "</mstyle>";
         break;
       case CSBMLunitInformation::DERIVED:
         tmp += "<mstyle mathcolor=\"green\">" + getMathML(ui.getSBMLUnitDefinition()) + "</mstyle>";
         break;
     }
   if (ui.getSymbolicExpExp() > 0)
     {
       std::ostringstream ttt; ttt << ui.getSymbolicExpExp();
       tmp += "</mfenced><mo>^</mo><mi mathcolor = \"#c06000\">" + ui.getSymbolicExponent() + "</mi><mo>^</mo><mn>" + ttt.str() + "</mn>";
     }
   tmp += "</mrow>";
   return tmp;
 }
std::string Expression2PresentationMMLUnits::getMathML (const UnitDefinition & ud) const protected
Definition at line 192 of file Expression2PresentationMMLUnits.cpp.
References getMathML().
 {
   std::string tmp;
   /*tmp += "<mrow>";
   size_t i, imax = ud.getNumUnits();
   for (i=0; i<imax; ++i)
   {
     if (i) tmp += "<mo>&CenterDot;</mo>";
     tmp += getMathML(ud.getUnit(i), false);
   }
   tmp += "</mrow>";*/
   tmp += "<mrow>";
   bool isFirst = true;
   size_t i, imax = ud.getNumUnits();
   for (i = 0; i < imax; ++i)
     {
       if (ud.getUnit((unsigned int) i)->getExponent() >= 0)
         {
           if (!isFirst) tmp += "<mo>&CenterDot;</mo>";
           tmp += getMathML(ud.getUnit((unsigned int) i), true);
           isFirst = false;
         }
     }
   if (isFirst) tmp += "<mn>1</mn>"; //there are no units with pos. exponent
   std::string tmp2;
   isFirst = true;
   for (i = 0; i < imax; ++i)
     {
       if (ud.getUnit((unsigned int) i)->getExponent() < 0)
         {
           if (!isFirst) tmp2 += "<mo>&CenterDot;</mo>";
           tmp2 += getMathML(ud.getUnit((unsigned int) i), true);
           isFirst = false;
         }
     }
   if (!isFirst) tmp += "<mo>/</mo>" + tmp2; //only create fraction when there is a denominator
   tmp += "</mrow>";
   return tmp;
 }
std::string Expression2PresentationMMLUnits::getMathML (const Unit * u, bool absExp) const protected
Definition at line 243 of file Expression2PresentationMMLUnits.cpp.
References abs.
 {
   if (!u)
     return "<mi>EEE</mi>";
   int exponent = absExp ? abs(u->getExponent()) : u->getExponent();
   bool flagExp = (exponent != 1);
   bool flag = (u->getMultiplier() != 1.0) || (u->getScale() != 0); //are brackets needed?
   std::ostringstream tmp;
   if (flagExp) tmp << "<msup>";
   //if (flag) tmp << "<mfenced>";
   tmp << "<mrow>";
   if (flag) tmp << "<mo>(</mo>";
   if (u->getMultiplier() != 1.0)
     tmp << "<mn>" <<  u->getMultiplier() << "</mn><mo>&CenterDot;</mo>";
   if (u->getScale() != 0)
     tmp << "<msup><mn>10</mn><mn>" << u->getScale() << "</mn></msup><mo>&CenterDot;</mo>";
   tmp << "<mi>";
   tmp << UnitKind_toString(u->getKind());
   tmp << "</mi>";
   if (flag) tmp << "<mo>)</mo>";
   tmp << "</mrow>";
   //if (flag) tmp << "</mfenced>";
   if (flagExp) tmp << "<mn>" << exponent << "</mn>";
   if (flagExp) tmp << "</msup>";
   //tmp << "</mrow>";
   return tmp.str();
 }
void Expression2PresentationMMLUnits::setUnitInterface (CSBMLunitInterface * unitInterface, CSBMLunitInterface * unitInterface2)
sets the unit interface to the SBML model so that the units can be displayed. this implicitly also handles setting the model
Definition at line 24 of file Expression2PresentationMMLUnits.cpp.
References CSBMLunitInterface::getModel(), Expression2PresentationMML::mpModel, mpUnitInterface, and mpUnitInterface2.
 {
   mpUnitInterface = unitInterface;
   mpUnitInterface2 = unitInterface2;
   mpModel = mpUnitInterface->getModel();
 }
void Expression2PresentationMMLUnits::writeMathMLBox (std::ostream & out, const std::string & a, const std::string & b, const std::string & color, size_t l) const protected
write the mathML for a box that is used to display an object identifier + its unit information a and b are mathML strings
Definition at line 159 of file Expression2PresentationMMLUnits.cpp.
References SPC.
Referenced by writeMathMLName(), and writeMathMLNumber().
 {
   out << SPC(l) << "<mstyle background=\"" << color << "\"><mfrac linethickness=\"0\">" << std::endl;
   out << a;
   out << SPC(l + 1) << "<mstyle scriptlevel=\"+1\">" << std::endl;
   out << SPC(l + 2) << b << std::endl;
   out << SPC(l + 1) << "</mstyle>" << std::endl;
   out << SPC(l) << "</mfrac></mstyle>" << std::endl;
   //formating is done so that it looks best when a is already indented nicely while b
   //is just a one line string
 }
void Expression2PresentationMMLUnits::writeMathMLBox (std::ostream & out, const std::string & a, const std::string & b, const std::string & c, const std::string & color, size_t l) const protected
Definition at line 173 of file Expression2PresentationMMLUnits.cpp.
References SPC.
 {
   out << SPC(l) << "<mstyle background=\"" << color << "\"><mtable rowspacing=\"0.1 ex\">" << std::endl;
   out << SPC(l + 1) << "<mtr><mtd>" << std::endl;
   out << a;
   out << SPC(l + 1) << "</mtd></mtr>" << std::endl;
   out << SPC(l + 1) << "<mtr><mtd><mstyle scriptlevel=\"+1\">" << std::endl;
   out << SPC(l + 2) << b << std::endl;
   out << SPC(l + 1) << "</mstyle></mtd></mtr>" << std::endl;
   out << SPC(l + 1) << "<mtr><mtd><mstyle scriptlevel=\"+1\">" << std::endl;
   out << SPC(l + 2) << c << std::endl;
   out << SPC(l + 1) << "</mstyle></mtd></mtr>" << std::endl;
   out << SPC(l) << "</mtable></mstyle>" << std::endl;
   //formating is done so that it looks best when a is already indented nicely while b
   //is just a one line string
 }
void Expression2PresentationMMLUnits::writeMathMLName (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
Reimplemented from Expression2PresentationMML.
Definition at line 33 of file Expression2PresentationMMLUnits.cpp.
References CSBMLunitInterface::getListOfConflictingNodes(), CSBMLunitInterface::getMappedUnitFromIdentifier(), getMathML(), CSBMLunitInformation::isEqual(), Expression2PresentationMML::mpReaction, mpUnitInterface, mpUnitInterface2, writeMathMLBox(), and Expression2PresentationMML::writeMathMLName().
 {
   std::string reactionID = mpReaction ? mpReaction->getId() : "";
   CSBMLunitInformation* unitInformation = mpUnitInterface->getMappedUnitFromIdentifier(node->getName(),
                                       CSBMLunitInterface::CEnvironmentInformation(reactionID));
   if (!unitInformation)
     {
       //use the base class implementation
       Expression2PresentationMML::writeMathMLName(out, node, l + 1);
       return;
     }
   std::string color;
   if (mpUnitInterface->getListOfConflictingNodes().count(node)
       || mpUnitInterface2->getListOfConflictingNodes().count(node))
     color = "#f0b0b0";
   else
     color = "#d0d0e0";
   CSBMLunitInformation * unitInformation2 = NULL;
   if (mpUnitInterface2)
     unitInformation2 = mpUnitInterface2->getMappedUnitFromIdentifier(node->getName(),
                        CSBMLunitInterface::CEnvironmentInformation(reactionID));
   std::ostringstream oss;
   Expression2PresentationMML::writeMathMLName(oss, node, l + 2);
   if (unitInformation2 != NULL)
     {
       if (CSBMLunitInformation::isEqual(*unitInformation, *unitInformation2))
         writeMathMLBox(out, oss.str(), getMathML(*unitInformation), "", color, l);
       else
         writeMathMLBox(out, oss.str(), getMathML(*unitInformation), getMathML(*unitInformation2), color, l);
     }
   else
     writeMathMLBox(out, oss.str(), getMathML(*unitInformation), color, l);
 }
void Expression2PresentationMMLUnits::writeMathMLNumber (std::ostream & out, const ASTNode * node, size_t l) const protected virtual
Reimplemented from Expression2PresentationMML.
Definition at line 74 of file Expression2PresentationMMLUnits.cpp.
References CSBMLunitInterface::getListOfConflictingNodes(), CSBMLunitInterface::getMappedUnitFromNumberNode(), getMathML(), mpUnitInterface, mpUnitInterface2, writeMathMLBox(), and Expression2PresentationMML::writeMathMLNumber().
 {
   CSBMLunitInformation* unitInformation = mpUnitInterface->getMappedUnitFromNumberNode(node);
   CSBMLunitInformation* unitInformation2 = NULL;
   if (mpUnitInterface2)
     unitInformation2 = mpUnitInterface2->getMappedUnitFromNumberNode(node);
   if (!unitInformation && !unitInformation2)
     {
       Expression2PresentationMML::writeMathMLNumber(out, node, l + 1);
       return;
     }
   std::string color;
   if (mpUnitInterface->getListOfConflictingNodes().count(node)
       || mpUnitInterface2->getListOfConflictingNodes().count(node))
     color = "#f0b0b0";
   else
     color = "#d0e0d0";
   std::ostringstream oss;
   Expression2PresentationMML::writeMathMLNumber(oss, node, l + 2);
   if (!unitInformation && unitInformation2)
     {
       writeMathMLBox(out, oss.str(), "<mi>unknown</mi>", getMathML(*unitInformation2), color, l);
     }
   if (unitInformation && !unitInformation2)
     {
       writeMathMLBox(out, oss.str(),  getMathML(*unitInformation), color, l);
     }
   if (unitInformation && unitInformation2)
     {
       writeMathMLBox(out, oss.str(),  getMathML(*unitInformation), getMathML(*unitInformation2), color, l);
     }
 }
Member Data Documentation
CSBMLunitInterface* Expression2PresentationMMLUnits::mpUnitInterface protected
Definition at line 55 of file Expression2PresentationMMLUnits.h.
Referenced by setUnitInterface(), writeMathMLName(), and writeMathMLNumber().
CSBMLunitInterface* Expression2PresentationMMLUnits::mpUnitInterface2 protected
Definition at line 56 of file Expression2PresentationMMLUnits.h.
Referenced by setUnitInterface(), writeMathMLName(), and writeMathMLNumber().
The documentation for this class was generated from the following files:
Expression2PresentationMMLUnits.h
Expression2PresentationMMLUnits.cpp