COPASI API: CQSpringLayoutParameterWindow Class Reference
CQSpringLayoutParameterWindow Class Reference
#include <CQSpringLayoutParameterWindow.h>
Public Member Functions
CQSpringLayoutParameterWindow (const QString &title, QWidget *parent=0, Qt::WindowFlags flags=0)
CCopasiSpringLayout::Parameters & getLayoutParameters ()
virtual ~CQSpringLayoutParameterWindow ()
Protected Slots
void slotLayoutSliderChanged ()
Protected Attributes
CCopasiSpringLayout::Parameters mLayoutParameters
std::vector< QwtSlider * > mLayoutSliders
Detailed Description
Definition at line 17 of file CQSpringLayoutParameterWindow.h.
Constructor & Destructor Documentation
CQSpringLayoutParameterWindow::CQSpringLayoutParameterWindow (const QString & title, QWidget * parent = 0, Qt::WindowFlags flags = 0)
Definition at line 14 of file CQSpringLayoutParameterWindow.cpp.
References CCopasiSpringLayout::Parameters::isLog, CCopasiSpringLayout::Parameters::max, CCopasiSpringLayout::Parameters::min, mLayoutParameters, mLayoutSliders, CCopasiSpringLayout::Parameters::names, slotLayoutSliderChanged(), and CCopasiSpringLayout::Parameters::values.
   : QDockWidget(title, parent, flags)
 {
   QWidget* pParaWidget = new QWidget(this);
   QVBoxLayout* pLayout = new QVBoxLayout;
   pParaWidget->setLayout(pLayout);
   size_t i;
   for (i = 0; i < mLayoutParameters.values.size(); ++i)
     {
       QLabel* label = new QLabel(mLayoutParameters.names[i].c_str());
       pLayout->addWidget(label);
       QwtSlider* slider = new QwtSlider(pParaWidget, Qt::Horizontal, QwtSlider::BottomScale);
       if (mLayoutParameters.isLog[i])
         {
           slider->setScaleEngine(new QwtLog10ScaleEngine);
           slider->setRange(log10(mLayoutParameters.min[i]), log10(mLayoutParameters.max[i]));
           slider->setScale(mLayoutParameters.min[i], mLayoutParameters.max[i]);
           slider->setValue(log10(mLayoutParameters.values[i]));
         }
       else
         {
           slider->setRange(mLayoutParameters.min[i], mLayoutParameters.max[i]);
           slider->setValue(mLayoutParameters.values[i]);
         }
       pLayout->addWidget(slider);
       mLayoutSliders.push_back(slider);
       connect(slider, SIGNAL(valueChanged(double)), this, SLOT(slotLayoutSliderChanged()));
     }
   setWidget(pParaWidget);
   setVisible(false);
 }
CQSpringLayoutParameterWindow::~CQSpringLayoutParameterWindow () virtual
Definition at line 51 of file CQSpringLayoutParameterWindow.cpp.
 {
 }
Member Function Documentation
CCopasiSpringLayout::Parameters & CQSpringLayoutParameterWindow::getLayoutParameters ()
Definition at line 55 of file CQSpringLayoutParameterWindow.cpp.
References mLayoutParameters.
Referenced by CQLayoutThread::randomizeLayout(), and CQLayoutThread::run().
 {
   return mLayoutParameters;
 }
void CQSpringLayoutParameterWindow::slotLayoutSliderChanged () protected slot
Definition at line 60 of file CQSpringLayoutParameterWindow.cpp.
References CCopasiSpringLayout::Parameters::isLog, mLayoutParameters, mLayoutSliders, and CCopasiSpringLayout::Parameters::values.
Referenced by CQSpringLayoutParameterWindow().
 {
   //std::cout << "slider..." << std::endl;
   size_t i;
   for (i = 0; i < mLayoutSliders.size(); ++i)
     {
       if (mLayoutParameters.isLog[i])
         mLayoutParameters.values[i] = pow(10, mLayoutSliders[i]->value());
       else
         mLayoutParameters.values[i] = mLayoutSliders[i]->value();
     }
 }
Member Data Documentation
CCopasiSpringLayout::Parameters CQSpringLayoutParameterWindow::mLayoutParameters protected
Definition at line 29 of file CQSpringLayoutParameterWindow.h.
Referenced by CQSpringLayoutParameterWindow(), getLayoutParameters(), and slotLayoutSliderChanged().
std::vector<QwtSlider*> CQSpringLayoutParameterWindow::mLayoutSliders protected
Definition at line 28 of file CQSpringLayoutParameterWindow.h.
Referenced by CQSpringLayoutParameterWindow(), and slotLayoutSliderChanged().
The documentation for this class was generated from the following files:
CQSpringLayoutParameterWindow.h
CQSpringLayoutParameterWindow.cpp