COPASI API: CCopasiXMLParser::AssignmentElement Class Reference
CCopasiXMLParser::AssignmentElement Class Reference
Public Member Functions
AssignmentElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~AssignmentElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Assignment = 0, Expression }
Private Attributes
std::pair< std::string,
std::string > mAssignmentPair
std::string mKey
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1686 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::AssignmentElement::Element private
Enum of invoked parsers
Enumerator
Assignment
Expression
Definition at line 1694 of file CCopasiXMLParser.h.
     {
       Assignment = 0,
       Expression
     };
Constructor & Destructor Documentation
CCopasiXMLParser::AssignmentElement::AssignmentElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 3516 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::AssignmentElement::~AssignmentElement () virtual
Destructor
Definition at line 3521 of file CCopasiXMLParser.cpp.
 {deleteCurrentHandler();}
Member Function Documentation
void CCopasiXMLParser::AssignmentElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 3577 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pEventAssignment, CEventAssignment::setExpression(), CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Assignment:
         if (strcmp(pszName, "Assignment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Assignment", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case Expression:
         if (strcmp(pszName, "Expression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Expression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           if (mCommon.pEventAssignment != NULL)
             mCommon.pEventAssignment->setExpression(mCommon.CharacterData);
           CCopasiMessage msg = CCopasiMessage::getLastMessage();
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             {
               msg = CCopasiMessage::getLastMessage();
             }
         }
         mCurrentElement = Assignment;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::AssignmentElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 3524 of file CCopasiXMLParser.cpp.
References CCopasiVectorN< CType >::add(), C_INVALID_INDEX, CCopasiMessage::EXCEPTION, CKeyFactory::get(), CEvent::getAssignments(), CCopasiVectorN< CType >::getIndex(), CModelEntity::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pEvent, SCopasiXMLParserCommon::pEventAssignment, and UNKNOWN_ELEMENT.
 {
   mpCurrentHandler = NULL;
   mCurrentElement++; /* We should always be on the next element */
   const CModelEntity* pME = NULL;
   switch (mCurrentElement)
     {
       case Assignment:
         if (strcmp(pszName, "Assignment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Assignment", mParser.getCurrentLineNumber());
         mCommon.pEventAssignment = NULL;
         mKey = mParser.getAttributeValue("targetKey", papszAttrs);
         pME = dynamic_cast<const CModelEntity *>(mCommon.KeyMap.get(mKey));
         if (pME != NULL &&
             mCommon.pEvent->getAssignments().getIndex(pME->getKey()) == C_INVALID_INDEX)
           {
             mCommon.pEventAssignment = new CEventAssignment(pME->getKey());
             mCommon.pEvent->getAssignments().add(mCommon.pEventAssignment, true);
           }
         return;
       case Expression:
         if (!strcmp(pszName, "Expression"))
           {
             mpCurrentHandler = &mParser.mCharacterDataElement;
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::pair<std::string, std::string> CCopasiXMLParser::AssignmentElement::mAssignmentPair private
Definition at line 1705 of file CCopasiXMLParser.h.
std::string CCopasiXMLParser::AssignmentElement::mKey private
The key in the CopasiML file
Definition at line 1703 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp