COPASI API: CQQtImageTexturizer Class Reference
CQQtImageTexturizer Class Reference
#include <CQQtImageTexturizer.h>
Public Member Functions
virtual CLTextureSpec * operator() (const std::string &filename, const std::string &basedir)
Protected Member Functions
CLTextureSpec * create_texture_for_image (const std::string &filename, const char *format=NULL)
Additional Inherited Members
Static Protected Member Functions inherited from CLImageTexturizer
static std::string to_absolute_path (const std::string &filename, const std::string &basedir)
Detailed Description
Definition at line 23 of file CQQtImageTexturizer.h.
Member Function Documentation
CLTextureSpec * CQQtImageTexturizer::create_texture_for_image (const std::string & filename, const char * format = NULL) protected
Definition at line 60 of file CQQtImageTexturizer.cpp.
References CCopasiMessage::ERROR, FROM_UTF8, GL_CLAMP_TO_EDGE, MCLayout, CLTextureSpec::mNumComponents, CLTextureSpec::mTextHeight, CLTextureSpec::mTextureHeight, CLTextureSpec::mTextureName, CLTextureSpec::mTextureWidth, CLTextureSpec::mTextWidth, and pResult.
Referenced by operator()().
 {
   CLTextureSpec* pResult = NULL;
   // use UTF8 strings for filenames since this seems to be safer across platforms
   QImage image(FROM_UTF8(filename), format);
   if (!image.isNull())
     {
       image = image.mirrored();
       QImage glImage = QGLWidget::convertToGLFormat(image);
       pResult = new CLTextureSpec;
       pResult->mTextureWidth = pResult->mTextWidth = glImage.width();
       pResult->mTextureHeight = pResult->mTextHeight = glImage.height();
       pResult->mNumComponents = 4;
       glGenTextures(1, &pResult->mTextureName);
       assert(pResult->mTextureName != 0);
       glBindTexture(GL_TEXTURE_2D, pResult->mTextureName);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
       glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
       glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE);
       glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, (GLsizei)pResult->mTextureWidth, (GLsizei)pResult->mTextureHeight, 0, GL_RGBA, GL_UNSIGNED_BYTE, glImage.bits());
     }
   else
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCLayout + 1, filename.c_str());
     }
   return pResult;
 }
CLTextureSpec * CQQtImageTexturizer::operator() (const std::string & filename, const std::string & basedir) virtual
Implements CLImageTexturizer.
Definition at line 30 of file CQQtImageTexturizer.cpp.
References create_texture_for_image(), CLImageTexturizer::to_absolute_path(), and transform().
 {
   std::string reference = to_absolute_path(filename, basedir);
   CLTextureSpec* pTexture = NULL;
   // test if the filename ends in "JPG","JPEG","jpeg" or "jpg"
   std::string::size_type pos = reference.rfind(".");
   std::string ending;
   if (pos != std::string::npos)
     {
       ++pos;
       ending = reference.substr(pos);
       std::transform(ending.begin(), ending.end(), ending.begin(), &tolower);
     }
   if (!ending.empty())
     {
       if (ending == "jpeg" || ending == "jpg")
         {
           pTexture = create_texture_for_image(reference/*,"JPG"*/);
         }
       else if (ending == "png")
         {
           pTexture = create_texture_for_image(reference/*,"PNG"*/);
         }
     }
   return pTexture;
 }
The documentation for this class was generated from the following files:
CQQtImageTexturizer.h
CQQtImageTexturizer.cpp