COPASI API: PlotWindow Class Reference
PlotWindow Class Reference
#include <plotwindow.h>
Public Member Functions
virtual bool compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel *pDataModel)
virtual void finish ()
virtual const std::set< const
CCopasiObject * > & getObjects () const
CopasiPlot * getPlot () const
virtual QMenu * getWindowMenu () const
bool initFromSpec (const CPlotSpecification *ptrSpec)
virtual void output (const Activity &activity)
PlotWindow (COutputHandlerPlot *pHandler, const CPlotSpecification *ptrSpec, CopasiUI3Window *pMainWindow)
virtual void saveToFile (const QString &fileName) const
virtual void separate (const Activity &activity)
virtual ~PlotWindow ()
Public Member Functions inherited from CWindowInterface
void addToMainWindow (CopasiUI3Window *window=NULL)
CWindowInterface (QWidget *parent=NULL, Qt::WindowFlags flags=NULL)
void removeFromMainWindow (CopasiUI3Window *window=NULL)
virtual ~CWindowInterface ()
Public Member Functions inherited from COutputInterface
virtual void close ()
COutputInterface ()
COutputInterface (const COutputInterface &src)
virtual ~COutputInterface ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *closeEvent)
Private Slots
void printAsImage ()
void printPlot ()
void slotCloseWindow ()
void slotDeselectAll ()
void slotSaveData ()
Save data into a file.
void slotSelectAll ()
void slotZoomOut ()
Zoom out.
void toggleLogX (bool)
void toggleLogY (bool)
Private Member Functions
void createActions ()
void createMenus ()
void createToolBar ()
Private Attributes
bool initializing
QAction * mpaCloseWindow
QAction * mpaHideAll
QAction * mpaPrint
QAction * mpaSaveData
QAction * mpaSaveImage
QAction * mpaShowAll
QAction * mpaToggleLogX
QAction * mpaToggleLogY
QAction * mpaZoomOut
COutputHandlerPlot * mpHandler
CopasiUI3Window * mpMainWindow
CopasiPlot * mpPlot
QMenu * mpWindowMenu
Additional Inherited Members
Public Types inherited from COutputInterface
enum Activity { BEFORE = 0x01, DURING = 0x02, AFTER = 0x04 }
Protected Attributes inherited from COutputInterface
std::set< const CCopasiObject * > mObjects
Detailed Description
Definition at line 34 of file plotwindow.h.
Constructor & Destructor Documentation
PlotWindow::PlotWindow (COutputHandlerPlot * pHandler, const CPlotSpecification * ptrSpec, CopasiUI3Window * pMainWindow)
Definition at line 57 of file plotwindow.cpp.
References CWindowInterface::addToMainWindow(), CQIconResource::copasi, createActions(), createMenus(), createToolBar(), CPlotItem::getTitle(), CQIconResource::icon(), initializing, CPlotSpecification::isLogX(), CPlotSpecification::isLogY(), mpaToggleLogX, mpaToggleLogY, mpMainWindow, and mpPlot.
                                                                                                                      :
   CWindowInterface(),
   mpPlot(NULL),
   mpHandler(pHandler),
   mpMainWindow(pMainWindow),
   mpWindowMenu(NULL),
   mpaCloseWindow(NULL),
   mpaShowAll(NULL),
   mpaHideAll(NULL),
   mpaPrint(NULL),
   mpaSaveImage(NULL),
   mpaSaveData(NULL),
   mpaZoomOut(NULL),
   mpaToggleLogX(NULL),
   mpaToggleLogY(NULL),
   initializing(false)
 {
   this->resize(640, 480);
   this->setWindowTitle(("COPASI Plot: " + ptrSpec->getTitle()).c_str());
 #ifndef Darwin
   setWindowIcon(CQIconResource::icon(CQIconResource::copasi));
 #endif // not Darwin
   // set up the GUI - the toolbar
   createActions();
   createMenus();
   createToolBar();
   mpPlot = new CopasiPlot(ptrSpec, this);
   setCentralWidget(mpPlot);
   initializing  = true;
   mpaToggleLogX->setChecked(ptrSpec->isLogX());
   mpaToggleLogY->setChecked(ptrSpec->isLogY());
   initializing = false;
   addToMainWindow(mpMainWindow);
 }
PlotWindow::~PlotWindow () virtual
Definition at line 417 of file plotwindow.cpp.
References mpHandler, mpMainWindow, CWindowInterface::removeFromMainWindow(), and COutputHandlerPlot::removeInterface().
 {
   if (mpHandler)
     mpHandler->removeInterface(this);
   if (mpMainWindow != NULL)
     removeFromMainWindow(mpMainWindow);
 }
Member Function Documentation
void PlotWindow::closeEvent (QCloseEvent * closeEvent) protected virtual
Definition at line 472 of file plotwindow.cpp.
References mpHandler, mpMainWindow, COutputHandlerPlot::removeInterface(), and CopasiUI3Window::removeWindow().
 {
   mpMainWindow->removeWindow(this);
   mpHandler->removeInterface(this);
 }
bool PlotWindow::compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel * pDataModel) virtual
compile the object list from name vector
Parameters
std::vector< CCopasiContainer * > listOfContainer
const CCopasiDataModel* pDataModel
Returns
bool success
Reimplemented from COutputInterface.
Definition at line 426 of file plotwindow.cpp.
References CopasiPlot::compile(), COutputInterface::mObjects, and mpPlot.
 {
   mObjects.clear();
   bool success = true;
   if (mpPlot != NULL)
     success = mpPlot->compile(listOfContainer, pDataModel);
   return success;
 };
void PlotWindow::createActions () private
Definition at line 123 of file plotwindow.cpp.
References mpaCloseWindow, mpaHideAll, mpaPrint, mpaSaveData, mpaSaveImage, mpaShowAll, mpaToggleLogX, mpaToggleLogY, mpaZoomOut, printAsImage(), printPlot(), slotCloseWindow(), slotDeselectAll(), slotSaveData(), slotSelectAll(), slotZoomOut(), toggleLogX(), and toggleLogY().
Referenced by PlotWindow().
 {
   mpaToggleLogX = new QAction("Log &X", this);
   mpaToggleLogX->setCheckable(true);
   mpaToggleLogX->setToolTip("Toggle x-axis logscale.");
   connect(mpaToggleLogX, SIGNAL(toggled(bool)), this, SLOT(toggleLogX(bool)));
   mpaToggleLogY = new QAction("Log &Y", this);
   mpaToggleLogY->setCheckable(true);
   mpaToggleLogY->setToolTip("Toggle y-axis logscale.");
   connect(mpaToggleLogY, SIGNAL(toggled(bool)), this, SLOT(toggleLogY(bool)));
   mpaPrint = new QAction("Print", this);
   mpaPrint ->setToolTip("Print Plot");
   mpaPrint -> setShortcut(Qt::CTRL + Qt::Key_P);
   connect(mpaPrint, SIGNAL(triggered()), this, SLOT(printPlot()));
   mpaSaveImage = new QAction("Save Image", this);
   mpaSaveImage ->setShortcut(Qt::CTRL + Qt::Key_S);
   mpaSaveImage ->setToolTip("Save Plot as Image");
   connect(mpaSaveImage, SIGNAL(triggered()), this, SLOT(printAsImage()));
   mpaSaveData = new QAction("Save Data", this);
   mpaSaveData ->setShortcut(Qt::CTRL + Qt::SHIFT + Qt::Key_S);
   mpaSaveData ->setToolTip("Save Data");
   connect(mpaSaveData, SIGNAL(triggered()), this, SLOT(slotSaveData()));
   mpaZoomOut = new QAction("Zoom out", this);
   mpaZoomOut ->setShortcut(Qt::CTRL + Qt::Key_0);
   mpaZoomOut ->setToolTip("Zoom out");
   connect(mpaZoomOut, SIGNAL(triggered()), this, SLOT(slotZoomOut()));
   mpaShowAll = new QAction("Show All", this);
   mpaShowAll ->setShortcut(Qt::CTRL + Qt::Key_A);
   mpaShowAll ->setToolTip("Show all curves");
   connect(mpaShowAll, SIGNAL(triggered()), this, SLOT(slotSelectAll()));
   mpaHideAll = new QAction("Hide All", this);
   mpaHideAll ->setShortcut(Qt::CTRL + Qt::Key_D);
   mpaHideAll ->setToolTip("Hide all curves");
   connect(mpaHideAll, SIGNAL(triggered()), this, SLOT(slotDeselectAll()));
   mpaCloseWindow = new QAction("Close", this);
   mpaCloseWindow->setObjectName("close");
   mpaCloseWindow->setShortcut(Qt::CTRL + Qt::Key_W);
   connect(mpaCloseWindow, SIGNAL(triggered()), this, SLOT(slotCloseWindow()));
 }
void PlotWindow::createMenus () private
Definition at line 97 of file plotwindow.cpp.
References mpaCloseWindow, mpaHideAll, mpaPrint, mpaSaveData, mpaSaveImage, mpaShowAll, mpaToggleLogX, mpaToggleLogY, mpaZoomOut, and mpWindowMenu.
Referenced by PlotWindow().
 {
   QMenu *fileMenu = menuBar()->addMenu("&File");
   fileMenu->addAction(mpaSaveImage);
   fileMenu->addAction(mpaSaveData);
   fileMenu->addAction(mpaPrint);
   fileMenu->addSeparator();
   fileMenu->addAction(mpaCloseWindow);
   QMenu *viewMenu = menuBar()->addMenu("&View");
   viewMenu->addAction(mpaShowAll);
   viewMenu->addAction(mpaHideAll);
   viewMenu->addSeparator();
   viewMenu->addAction(mpaToggleLogX);
   viewMenu->addAction(mpaToggleLogY);
   viewMenu->addSeparator();
   viewMenu->addAction(mpaZoomOut);
   // add a place holder menu, to be filled by the main window
   mpWindowMenu = menuBar()->addMenu("&Window");
 }
void PlotWindow::createToolBar () private
Definition at line 171 of file plotwindow.cpp.
References mpaCloseWindow, mpaHideAll, mpaPrint, mpaSaveData, mpaSaveImage, mpaShowAll, mpaToggleLogX, mpaToggleLogY, and mpaZoomOut.
Referenced by PlotWindow().
 {
   QToolBar * plotTools = addToolBar("plot operations");
   plotTools->addAction(mpaPrint);
   plotTools->addAction(mpaSaveImage);
   plotTools->addAction(mpaSaveData);
   plotTools->addAction(mpaZoomOut);
   plotTools->addSeparator();
   plotTools->addAction(mpaToggleLogX);
   plotTools->addAction(mpaToggleLogY);
   plotTools->addSeparator();
   plotTools->addAction(mpaShowAll);
   plotTools->addAction(mpaHideAll);
   plotTools->addSeparator();
   plotTools->addAction(mpaCloseWindow);
   //TODO button icons...
   setUnifiedTitleAndToolBarOnMac(true);
 //  plotTools->setStretchableWidget(new QWidget(plotTools));
 }
void PlotWindow::finish () virtual
Finish the output
Reimplemented from COutputInterface.
Definition at line 444 of file plotwindow.cpp.
References CopasiPlot::finish(), and mpPlot.
 {if (mpPlot) mpPlot->finish();};
const std::set< const CCopasiObject * > & PlotWindow::getObjects () const virtual
Retrieve the list of objects handled by the interface
Returns
const std::set< const CCopasiObject * > & objects
Reimplemented from COutputInterface.
Definition at line 447 of file plotwindow.cpp.
References COutputInterface::getObjects(), COutputInterface::mObjects, and mpPlot.
 {
   if (mpPlot)
     return mpPlot->getObjects();
   return mObjects;
 }
CopasiPlot * PlotWindow::getPlot () const
Definition at line 478 of file plotwindow.cpp.
References mpPlot.
 {
   return mpPlot;
 }
QMenu * PlotWindow::getWindowMenu () const virtual
Returns
a pointer to this plot windows 'window' menu.
Implements CWindowInterface.
Definition at line 118 of file plotwindow.cpp.
References mpWindowMenu.
 {
   return mpWindowMenu;
 }
bool PlotWindow::initFromSpec (const CPlotSpecification * ptrSpec)
Definition at line 199 of file plotwindow.cpp.
References CPlotItem::getTitle(), CopasiPlot::initFromSpec(), initializing, CPlotSpecification::isLogX(), CPlotSpecification::isLogY(), mpaToggleLogX, mpaToggleLogY, and mpPlot.
 {
   this->setWindowTitle(("COPASI Plot: " + ptrSpec->getTitle()).c_str());
   bool result = mpPlot->initFromSpec(ptrSpec);
   if (result)
     {
       initializing  = true;
       mpaToggleLogX->setChecked(ptrSpec->isLogX());
       mpaToggleLogY->setChecked(ptrSpec->isLogY());
       initializing = false;
     }
   return result;
 }
void PlotWindow::output (const Activity & activity) virtual
Perform an output event for the current activity
Parameters
const Activity & activity
Reimplemented from COutputInterface.
Definition at line 438 of file plotwindow.cpp.
References mpPlot, and CopasiPlot::output().
 {if (mpPlot) mpPlot->output(activity);}
void PlotWindow::printAsImage () private slot
Definition at line 311 of file plotwindow.cpp.
References C_INT32, checkSelection(), CopasiFileDialog::getSaveFileName(), and saveToFile().
Referenced by createActions().
 {
   // take a name from QFileDialog
   C_INT32 Answer = QMessageBox::No;
   QString fileName, extensionName;
   while (Answer == QMessageBox::No)
     {
 //      QString userFilter = new QString;
       /*
             fileName = CopasiFileDialog::getSaveFileNameAndFilter(filter, this, "Save File Dialog",
                        QString::null, "PNG Files (*.png);;SVG Files (*.svg)", "Save to");
       */
       fileName = CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                  "untitled.png", "PDF Files (*.pdf);;PNG Files (*.png);;SVG Files (*.svg)", "Save Plot as Image", new QString);
       if (fileName.isEmpty()) return;
       /*
             QFileInfo fileInfo(fileName);
             extensionName = fileInfo.extension();
       */
 #ifdef DEBUG_UI
 //      qDebug() << "extensionName = " << extensionName;
 #endif
       // check whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   // print plot as an image
   saveToFile(fileName);
 }
void PlotWindow::printPlot () private slot
Definition at line 349 of file plotwindow.cpp.
References mpPlot.
Referenced by createActions().
 {
   QPrinter printer;
   QString docName = mpPlot->title().text();
   if (docName.isEmpty())
     {
       //docName.replace (QRegExp (QString::fromLatin1 ("\n")), tr (" -- "));
       docName = QString::fromLatin1("A plot of selected COPASI output");
       printer.setDocName(docName);
     }
   printer.setCreator("COPASI");
   printer.setOrientation(QPrinter::Landscape);
   QPrintDialog dialog(&printer);
   if (dialog.exec())
     mpPlot->print(printer, PrintFilter());
 }
void PlotWindow::saveToFile (const QString & fileName) const virtual
Saves the current plot to the given filename.
This implementation supports PDF, SVG and PNG
Reimplemented from CWindowInterface.
Definition at line 274 of file plotwindow.cpp.
References mpPlot.
Referenced by printAsImage().
 {
   QRect rect;
   rect.setSize(this->size());
   if (fileName.endsWith(".png"))
     {
       QPixmap pixmap(rect.width(), rect.height());
       pixmap.fill();
       QPainter painter(&pixmap);
       painter.begin(&pixmap);
       mpPlot->print(&painter, rect, PrintFilter());
       painter.end();
       pixmap.save(fileName, "PNG");
     }
   else if (fileName.endsWith(".svg"))
     {
       QSvgGenerator generator;
       generator.setFileName(fileName);
       QPainter painter(&generator);
       painter.begin(&generator);
       mpPlot->print(&painter, rect, PrintFilter());
       painter.end();
     }
   else if (fileName.endsWith(".pdf"))
     {
       QPrinter printer;
       printer.setOutputFileName(fileName);
       printer.setOutputFormat(QPrinter::PdfFormat);
       QPainter painter(&printer);
       painter.begin(&printer);
       mpPlot->print(&painter, rect, PrintFilter());
       painter.end();
     }
 }
void PlotWindow::separate (const Activity & activity) virtual
Introduce an additional separator into the output
Parameters
const Activity & activity
Reimplemented from COutputInterface.
Definition at line 441 of file plotwindow.cpp.
References mpPlot, and CopasiPlot::separate().
 {if (mpPlot) mpPlot->separate(activity);};
void PlotWindow::slotCloseWindow () private slot
Definition at line 467 of file plotwindow.cpp.
Referenced by createActions().
 {
   QWidget::close();
 }
void PlotWindow::slotDeselectAll () private slot
Hide all curves.
Definition at line 461 of file plotwindow.cpp.
References mpPlot, and CopasiPlot::setCurvesVisibility().
Referenced by createActions().
 {
   // We hide all curves in mpPlot
   mpPlot->setCurvesVisibility(false);
 }
void PlotWindow::slotSaveData () private slot
Save data into a file.
Definition at line 371 of file plotwindow.cpp.
References C_INT32, checkSelection(), CQMessageBox::critical(), FROM_UTF8, CopasiFileDialog::getSaveFileName(), mpPlot, CopasiPlot::saveData(), and TO_UTF8.
Referenced by createActions().
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog", "untitled.txt", "TEXT Files (*.txt)", "Save Plot Data to");
       if (fileName.isNull()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   bool success = false;
   if (mpPlot)
     {
       QCursor oldCursor = cursor();
       setCursor(Qt::WaitCursor);
       success = mpPlot->saveData(TO_UTF8(fileName));
       setCursor(oldCursor);
     }
   if (!success)
     {
       std::string s = "Could not save data to ";
       s += TO_UTF8(fileName);
       CQMessageBox::critical(this, "Save Error", FROM_UTF8(s), QMessageBox::Ok, QMessageBox::NoButton);
     }
 }
void PlotWindow::slotSelectAll () private slot
Show all curves.
Definition at line 455 of file plotwindow.cpp.
References mpPlot, and CopasiPlot::setCurvesVisibility().
Referenced by createActions().
 {
   // We show all curves in mpPlot
   mpPlot->setCurvesVisibility(true);
 }
void PlotWindow::slotZoomOut () private slot
Zoom out.
Definition at line 409 of file plotwindow.cpp.
References mpPlot, and CopasiPlot::mpZoomer.
Referenced by createActions().
 {
   if (mpPlot && mpPlot->mpZoomer)
     mpPlot->mpZoomer->zoom(0);
 }
void PlotWindow::toggleLogX (bool logX) private slot
Definition at line 216 of file plotwindow.cpp.
References initializing, mpPlot, and CopasiPlot::replot().
Referenced by createActions().
 {
   if (initializing) return;
   if (logX)
     {
       mpPlot->setAxisScaleEngine(QwtPlot::xBottom, new QwtLog10ScaleEngine());
     }
   else
     {
       mpPlot->setAxisScaleEngine(QwtPlot::xBottom, new QwtLinearScaleEngine());
     }
   mpPlot->setAxisAutoScale(QwtPlot::xBottom);
   mpPlot->updateAxes();
   mpPlot->replot();
   mpPlot->update();
 }
void PlotWindow::toggleLogY (bool logY) private slot
Definition at line 236 of file plotwindow.cpp.
References initializing, mpPlot, and CopasiPlot::replot().
Referenced by createActions().
 {
   if (initializing) return;
   if (logY)
     {
       mpPlot->setAxisScaleEngine(QwtPlot::yLeft, new QwtLog10ScaleEngine());
     }
   else
     {
       mpPlot->setAxisScaleEngine(QwtPlot::yLeft, new QwtLinearScaleEngine());
     }
   mpPlot->setAxisAutoScale(QwtPlot::yLeft);
   mpPlot->updateAxes();
   mpPlot->replot();
   mpPlot->update();
 }
Member Data Documentation
bool PlotWindow::initializing private
Definition at line 56 of file plotwindow.h.
Referenced by initFromSpec(), PlotWindow(), toggleLogX(), and toggleLogY().
QAction* PlotWindow::mpaCloseWindow private
Definition at line 46 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
QAction* PlotWindow::mpaHideAll private
Definition at line 48 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
QAction* PlotWindow::mpaPrint private
Definition at line 49 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
QAction* PlotWindow::mpaSaveData private
Definition at line 51 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
QAction* PlotWindow::mpaSaveImage private
Definition at line 50 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
QAction* PlotWindow::mpaShowAll private
Definition at line 47 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
QAction* PlotWindow::mpaToggleLogX private
Definition at line 53 of file plotwindow.h.
Referenced by createActions(), createMenus(), createToolBar(), initFromSpec(), and PlotWindow().
QAction* PlotWindow::mpaToggleLogY private
Definition at line 54 of file plotwindow.h.
Referenced by createActions(), createMenus(), createToolBar(), initFromSpec(), and PlotWindow().
QAction* PlotWindow::mpaZoomOut private
Definition at line 52 of file plotwindow.h.
Referenced by createActions(), createMenus(), and createToolBar().
COutputHandlerPlot* PlotWindow::mpHandler private
Definition at line 42 of file plotwindow.h.
Referenced by closeEvent(), and ~PlotWindow().
CopasiUI3Window* PlotWindow::mpMainWindow private
Definition at line 43 of file plotwindow.h.
Referenced by closeEvent(), PlotWindow(), and ~PlotWindow().
CopasiPlot* PlotWindow::mpPlot private
Definition at line 41 of file plotwindow.h.
Referenced by compile(), finish(), getObjects(), getPlot(), initFromSpec(), output(), PlotWindow(), printPlot(), saveToFile(), separate(), slotDeselectAll(), slotSaveData(), slotSelectAll(), slotZoomOut(), toggleLogX(), and toggleLogY().
QMenu* PlotWindow::mpWindowMenu private
Definition at line 44 of file plotwindow.h.
Referenced by createMenus(), and getWindowMenu().
The documentation for this class was generated from the following files:
plotwindow.h
plotwindow.cpp