COPASI API: CLReactionGlyph Class Reference
CLReactionGlyph Class Reference
#include <CLReactionGlyph.h>
Public Member Functions
void addMetabReferenceGlyph (CLMetabReferenceGlyph *glyph)
virtual CLGraphicalObject * clone () const
CLReactionGlyph (const std::string &name="ReactionGlyph", const CCopasiContainer *pParent=NULL)
CLReactionGlyph (const CLReactionGlyph &src, const CCopasiContainer *pParent=NULL)
CLReactionGlyph (const ReactionGlyph &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual void exportToSBML (ReactionGlyph *g, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs, std::map< const CLBase *, const SBase * > &layoutmap) const
const CCopasiVector
< CLMetabReferenceGlyph > & getListOfMetabReferenceGlyphs () const
CCopasiVector
< CLMetabReferenceGlyph > & getListOfMetabReferenceGlyphs ()
virtual void moveBy (const CLPoint &p)
CLReactionGlyph & operator= (const CLReactionGlyph &rhs)
void print (std::ostream *ostream) const
Public Member Functions inherited from CLGlyphWithCurve
CLGlyphWithCurve (const std::string &name="ReferenceGlyph", const CCopasiContainer *pParent=NULL)
CLGlyphWithCurve (const CLGlyphWithCurve &src, const CCopasiContainer *pParent=NULL)
CLGlyphWithCurve (const GraphicalObject &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
const CLCurve & getCurve () const
CLCurve & getCurve ()
CLGlyphWithCurve & operator= (const CLGlyphWithCurve &rhs)
void setCurve (const CLCurve &c)
Public Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const std::string &name="GraphicalObject", const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const CLGraphicalObject &src, const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
const CLBoundingBox & getBoundingBox () const
CLBoundingBox & getBoundingBox ()
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CCopasiObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CCopasiVector
< CLMetabReferenceGlyph > mvMetabReferences
Protected Attributes inherited from CLGlyphWithCurve
CLCurve mCurve
Protected Attributes inherited from CLGraphicalObject
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Friends
std::ostream & operator<< (std::ostream &os, const CLReactionGlyph &g)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Graphical representation of a reaction
Definition at line 312 of file CLReactionGlyph.h.
Constructor & Destructor Documentation
CLReactionGlyph::CLReactionGlyph (const std::string & name = "ReactionGlyph", const CCopasiContainer * pParent = NULL)
Definition at line 674 of file CLReactionGlyph.cpp.
Referenced by clone().
   : CLGlyphWithCurve(name, pParent),
     mvMetabReferences("ListOfMetabReferenceGlyphs", this)
 {}
CLReactionGlyph::CLReactionGlyph (const CLReactionGlyph & src, const CCopasiContainer * pParent = NULL)
Definition at line 680 of file CLReactionGlyph.cpp.
   : CLGlyphWithCurve(src, pParent),
     mvMetabReferences(src.mvMetabReferences, this)
 {
   //TODO
 }
CLReactionGlyph::CLReactionGlyph (const ReactionGlyph & sbml, const std::map< std::string, std::string > & modelmap, std::map< std::string, std::string > & layoutmap, const CCopasiContainer * pParent = NULL)
constructor from libsbml object
Definition at line 688 of file CLReactionGlyph.cpp.
References addMetabReferenceGlyph(), C_INT32, CLGlyphWithCurve::mCurve, and CLGraphicalObject::setModelObjectKey().
   : CLGlyphWithCurve(sbml, modelmap, layoutmap, pParent),
     mvMetabReferences("ListOfMetabReferenceGlyphs", this)
 {
   //get the copasi key corresponding to the sbml id for the reaction
   if (sbml.getReactionId() != "")
     {
       std::map<std::string, std::string>::const_iterator it = modelmap.find(sbml.getReactionId());
       if (it != modelmap.end())
         setModelObjectKey(it->second);
     }
   //species reference glyphs
   C_INT32 i, imax = sbml.getListOfSpeciesReferenceGlyphs()->size();
   for (i = 0; i < imax; ++i)
     {
       const SpeciesReferenceGlyph* tmp
         = dynamic_cast<const SpeciesReferenceGlyph*>(sbml.getListOfSpeciesReferenceGlyphs()->get(i));
       if (tmp)
         addMetabReferenceGlyph(new CLMetabReferenceGlyph(*tmp, modelmap, layoutmap));
     }
   //curve
   if (sbml.getCurve())
     {
       CLCurve copy(*sbml.getCurve());
       mCurve = copy;
     }
 }
Member Function Documentation
void CLReactionGlyph::addMetabReferenceGlyph (CLMetabReferenceGlyph * glyph)
add Glyph to reaction glyph. The reaction glyph takes ownership of the glyph.
Definition at line 753 of file CLReactionGlyph.cpp.
References CCopasiVector< T >::add(), and mvMetabReferences.
Referenced by CLReactionGlyph(), CCopasiSpringLayout::createLayout(), CLayoutInitializer::createReactionGlyph(), operator=(), and CCopasiXMLParser::MetaboliteReferenceGlyphElement::start().
 {
   if (glyph)
     mvMetabReferences.add(glyph, true); //true means vector takes ownership
 }
virtual CLGraphicalObject* CLReactionGlyph::clone () const inline virtual
Reimplemented from CLGraphicalObject.
Definition at line 351 of file CLReactionGlyph.h.
References CLReactionGlyph().
 {return new CLReactionGlyph(*this, NULL);};
void CLReactionGlyph::exportToSBML (ReactionGlyph * g, const std::map< const CCopasiObject *, SBase * > & copasimodelmap, std::map< std::string, const SBase * > & sbmlIDs, std::map< const CLBase *, const SBase * > & layoutmap) const virtual
This method writes the information of the COPASI layout object into the corresponding SBML object layoutmap contains a map from COPASI layout objects to libsbml layout objects. the exported metab reference glyphs will be added.
Definition at line 769 of file CLReactionGlyph.cpp.
References CLGraphicalObject::exportToSBML(), CLMetabReferenceGlyph::exportToSBML(), CLCurve::exportToSBML(), CLGraphicalObject::getModelObject(), CLGlyphWithCurve::mCurve, mvMetabReferences, and CCopasiVector< T >::size().
Referenced by CLayout::exportToSBML().
 {
   if (!g) return;
   //call the coresponding method of the base class
   CLGraphicalObject::exportToSBML(g, copasimodelmap, sbmlIDs);
   //reference to model objects
   CCopasiObject* tmp = getModelObject();
   if (tmp)
     {
       std::map<const CCopasiObject*, SBase*>::const_iterator it = copasimodelmap.find(tmp);
       if (it != copasimodelmap.end())
         {
           if (it->second)
             g->setReactionId(it->second->getId());
         }
     }
   //curve
   mCurve.exportToSBML(g->getCurve(), copasimodelmap);
   //Metab reference  glyphs
   size_t i, imax = mvMetabReferences.size();
   for (i = 0; i < imax; ++i)
     {
       CLMetabReferenceGlyph * tmp = mvMetabReferences[i];
       //check if the glyph exists in the libsbml data
       std::map<const CCopasiObject*, SBase*>::const_iterator it;
       it = copasimodelmap.find(tmp);
       SpeciesReferenceGlyph * pG;
       if (it == copasimodelmap.end()) //not found
         {
           pG = new SpeciesReferenceGlyph;
           g->getListOfSpeciesReferenceGlyphs()->appendAndOwn(pG);
         }
       else
         {
           pG = dynamic_cast<SpeciesReferenceGlyph*>(it->second);
         }
       layoutmap.insert(std::pair<const CLBase*, const SBase*>(tmp, pG));
       tmp->exportToSBML(pG, copasimodelmap, sbmlIDs, layoutmap);
     }
 }
const CCopasiVector<CLMetabReferenceGlyph>& CLReactionGlyph::getListOfMetabReferenceGlyphs () const inline
Definition at line 338 of file CLReactionGlyph.h.
References mvMetabReferences.
Referenced by CLayout::calculateBoundingBox(), CLayout::CLayout(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CCopasiSpringLayout::finalizeState(), CCopasiSpringLayout::findCompartmentForReactionNode(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CCopasiSpringLayout::getPotential(), CCopasiSpringLayout::randomize(), CCopasiXML::saveLayoutList(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), and CLLayoutRenderer::update_associations().
   {return mvMetabReferences;};
CCopasiVector<CLMetabReferenceGlyph>& CLReactionGlyph::getListOfMetabReferenceGlyphs () inline
Definition at line 341 of file CLReactionGlyph.h.
References mvMetabReferences.
   {return mvMetabReferences;};
void CLReactionGlyph::moveBy (const CLPoint & p) virtual
Reimplemented from CLGlyphWithCurve.
Definition at line 759 of file CLReactionGlyph.cpp.
References CLGlyphWithCurve::moveBy(), mvMetabReferences, and CCopasiVector< T >::size().
 {
   CLGlyphWithCurve::moveBy(p);
   size_t i, imax = mvMetabReferences.size();
   for (i = 0; i < imax; ++i)
     mvMetabReferences[i]->moveBy(p);
 }
CLReactionGlyph & CLReactionGlyph::operator= (const CLReactionGlyph & rhs)
assignment operator. makes a deep copy
Definition at line 724 of file CLReactionGlyph.cpp.
References addMetabReferenceGlyph(), mvMetabReferences, CLGlyphWithCurve::operator=(), and CCopasiVector< T >::size().
 {
   if (this == &rhs) return * this; //do nothing if lhs and rhs are the same
   CLGlyphWithCurve::operator=(rhs);
   //handle the specific glyph stuff:
   size_t i, imax = rhs.mvMetabReferences.size();
   for (i = 0; i < imax; ++i)
     addMetabReferenceGlyph(new CLMetabReferenceGlyph(*rhs.mvMetabReferences[i]));
   return *this;
 }
void CLReactionGlyph::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CLGlyphWithCurve.
Definition at line 842 of file CLReactionGlyph.cpp.
 {*ostream << *this;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLReactionGlyph & g) friend
insert operator
Definition at line 824 of file CLReactionGlyph.cpp.
 {
   os << "ReactionGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   os << g.mCurve;
   size_t i, imax = g.mvMetabReferences.size();
   if (imax)
     {
       os << "  List of metab reference glyphs: \n";
       for (i = 0; i < imax; ++i)
         os << *g.mvMetabReferences[i];
     }
   return os;
 }
Member Data Documentation
CCopasiVector<CLMetabReferenceGlyph> CLReactionGlyph::mvMetabReferences protected
Definition at line 315 of file CLReactionGlyph.h.
Referenced by addMetabReferenceGlyph(), exportToSBML(), getListOfMetabReferenceGlyphs(), moveBy(), operator<<(), and operator=().
The documentation for this class was generated from the following files:
CLReactionGlyph.h
CLReactionGlyph.cpp