COPASI API: ScanWidget Class Reference
ScanWidget Class Reference
#include <ScanWidget.h>
Public Member Functions
virtual bool runTask ()
ScanWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
~ScanWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
bool slotAddItem ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &)
virtual bool loadTask ()
virtual bool saveTask ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
virtual bool taskFinishedEvent ()
Protected Attributes
QPushButton * buttonNewItem
QComboBox * comboType
QGridLayout * ScanWidgetLayout
CScanContainerWidget * scrollview
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Detailed Description
Definition at line 29 of file ScanWidget.h.
Constructor & Destructor Documentation
ScanWidget::ScanWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 56 of file ScanWidget.cpp.
References buttonNewItem, comboType, TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, ScanWidgetLayout, scrollview, CQTaskHeaderWidget::setTaskName(), and slotAddItem().
   : TaskWidget(parent, name, f)
 {
   if (!name)
     setObjectName("ScanWidget");
   setWindowTitle(trUtf8("ScanWidget"));
   ScanWidgetLayout = new QGridLayout(this);
   ScanWidgetLayout->setMargin(11);
   ScanWidgetLayout->setSpacing(6);
   ScanWidgetLayout->setObjectName("ScanWidgetLayout");
   mpHeaderWidget->setTaskName("Parameter Scan");
   ScanWidgetLayout->addWidget(mpHeaderWidget, 0, 0);
   mpBtnWidget->verticalLayout->removeItem(mpBtnWidget->verticalSpacer);
   ScanWidgetLayout->addWidget(mpBtnWidget, 3, 0);
   //*****************
   QHBoxLayout* tmpLayout = new QHBoxLayout();
   QSpacerItem* tmpSpacer = new QSpacerItem(0, 0, QSizePolicy::Expanding, QSizePolicy::Minimum);
   tmpLayout->addItem(tmpSpacer);
   QLabel* tmpLabel = new QLabel(this);
   tmpLabel->setText("New scan item: ");
   tmpLayout->addWidget(tmpLabel);
   comboType = new QComboBox(this);
   //+++
   comboType->addItem("Scan");
   comboType->addItem("Repeat");
   comboType->addItem("Random distribution");
   tmpLayout->addWidget(comboType);
   QSpacerItem *mpSpacer = new QSpacerItem(20, 20, QSizePolicy::Maximum, QSizePolicy::Minimum);
   tmpLayout->addItem(mpSpacer);
   buttonNewItem = new QPushButton(this);
   buttonNewItem->setObjectName("buttonNewItem");
   buttonNewItem->setText("Create");
   //ScanWidgetLayout->addWidget(buttonNewItem, 1, 2);
   tmpLayout->addWidget(buttonNewItem);
   ScanWidgetLayout->addLayout(tmpLayout, 1, 0);
   //*****************************
   scrollview = new CScanContainerWidget(this);
   ScanWidgetLayout->addWidget(scrollview, 2, 0);
   // tab order
   /*setTabOrder(taskName, sExecutable);
   setTabOrder(sExecutable, steadyState);*/
   connect(buttonNewItem, SIGNAL(clicked()), this, SLOT(slotAddItem()));
 }
ScanWidget::~ScanWidget ()
Definition at line 116 of file ScanWidget.cpp.
 {}
Member Function Documentation
virtual CCopasiMethod* ScanWidget::createMethod (const CCopasiMethod::SubType &) inline protected virtual
Implements TaskWidget.
Definition at line 46 of file ScanWidget.h.
 {return NULL;};
bool ScanWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 130 of file ScanWidget.cpp.
References CScanContainerWidget::addWidget(), CScanContainerWidget::clearWidgetList(), CKeyFactory::get(), CCopasiRootContainer::getDatamodelList(), CCopasiRootContainer::getKeyFactory(), CScanProblem::getNumberOfScanItems(), CCopasiTask::getProblem(), CScanProblem::getScanItem(), CCopasiParameterGroup::getValue(), CScanWidgetRepeat::load(), CScanWidgetRandom::load(), CScanWidgetTask::load(), CScanWidgetScan::load(), TaskWidget::loadCommon(), TaskWidget::mChanged, CopasiWidget::mKey, CCopasiParameter::Value::pVOID, CScanProblem::SCAN_LINEAR, CScanProblem::SCAN_RANDOM, CScanProblem::SCAN_REPEAT, and scrollview.
 {
   loadCommon();
   CScanTask* scanTask =
     dynamic_cast< CScanTask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!scanTask) return false;
   CScanProblem *scanProblem = dynamic_cast<CScanProblem *>(scanTask->getProblem());
   if (!scanProblem) return false;
   scrollview->clearWidgetList();
   //std::vector<QWidget*> & widgetList = scrollview->getWidgetList();
   //+++
   CScanWidgetScan* tmp1;
   CScanWidgetRepeat* tmp2;
   CScanWidgetRandom* tmp3;
   //CScanWidgetBreak* tmp4;
   // the scan items
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   //CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   //assert(pDataModel != NULL);
   size_t i, imax = scanProblem->getNumberOfScanItems();
   for (i = 0; i < imax; ++i)
     {
       void * pTmp;
       if (!(pTmp = scanProblem->getScanItem(i)->getValue("Type").pVOID)) return false;
       CScanProblem::Type type = *(CScanProblem::Type*)pTmp;
       switch (type)
         {
             //+++
           case CScanProblem::SCAN_LINEAR:
             tmp1 = new CScanWidgetScan(scrollview);
             tmp1->load(scanProblem->getScanItem(i));
             scrollview->addWidget(tmp1);
             break;
           case CScanProblem::SCAN_REPEAT:
             tmp2 = new CScanWidgetRepeat(scrollview);
             tmp2->load(scanProblem->getScanItem(i));
             scrollview->addWidget(tmp2);
             break;
           case CScanProblem::SCAN_RANDOM:
             tmp3 = new CScanWidgetRandom(scrollview);
             tmp3->load(scanProblem->getScanItem(i));
             scrollview->addWidget(tmp3);
             break;
           default:
             break;
         }
     }
   // the widget for the subtask
   CScanWidgetTask* tmpT = new CScanWidgetTask(scrollview);
   tmpT->load(scanProblem);
   scrollview->addWidget(tmpT, false); //false: no control buttons (up/down/del)
   mChanged = false;
   return true;
 }
bool ScanWidget::runTask () virtual
Implements TaskWidget.
Definition at line 119 of file ScanWidget.cpp.
References TaskWidget::commonBeforeRunTask(), and TaskWidget::commonRunTask().
Referenced by SliderDialog::runScanTask().
 {
   if (!commonBeforeRunTask()) return false;
   bool success = true;
   if (!commonRunTask()) success = false;
   return success;
 }
bool ScanWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 304 of file ScanWidget.cpp.
References CScanProblem::addScanItem(), CCopasiDataModel::changed(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CScanProblem::getNumberOfScanItems(), CCopasiTask::getProblem(), CScanProblem::getScanItem(), CScanContainerWidget::getWidgetList(), TaskWidget::mChanged, min, CopasiWidget::mKey, CopasiWidget::mpDataModel, CScanProblem::removeScanItem(), CScanWidgetTask::save(), TaskWidget::saveCommon(), CScanProblem::SCAN_LINEAR, and scrollview.
 {
   saveCommon();
   CScanTask* scanTask =
     dynamic_cast< CScanTask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!scanTask) return false;
   CScanProblem *scanProblem = dynamic_cast<CScanProblem *>(scanTask->getProblem());
   if (!scanProblem) return false;
   const std::vector< QWidget * > & widgetList = scrollview->getWidgetList();
   size_t newSize = widgetList.size() - 1; // The last widget is reserved for the subtask.
   size_t oldSize = scanProblem->getNumberOfScanItems();
   size_t i, imax = std::min(newSize, oldSize);
   mChanged = false;
   for (i = 0; i < imax; ++i)
     {
       QWidget * pWidget = widgetList[i];
       if (pWidget->objectName() == "CScanWidgetScan")
         {
           mChanged |= static_cast< CScanWidgetScan * >(pWidget)->save(scanProblem->getScanItem(i));
         }
       else if (pWidget->objectName() == "CScanWidgetRandom")
         {
           mChanged |= static_cast< CScanWidgetRandom * >(pWidget)->save(scanProblem->getScanItem(i));
         }
       else if (pWidget->objectName() == "CScanWidgetRepeat")
         {
           mChanged |= static_cast< CScanWidgetRepeat * >(pWidget)->save(scanProblem->getScanItem(i));
         }
     }
   for (; i < newSize; ++i)
     {
       mChanged = true;
       QWidget * pWidget = widgetList[i];
       CCopasiParameterGroup * pItem = scanProblem->addScanItem(CScanProblem::SCAN_LINEAR);
       if (pWidget->objectName() == "CScanWidgetScan")
         {
           static_cast< CScanWidgetScan * >(pWidget)->save(pItem);
         }
       else if (pWidget->objectName() == "CScanWidgetRandom")
         {
           static_cast< CScanWidgetRandom * >(pWidget)->save(pItem);
         }
       else if (pWidget->objectName() == "CScanWidgetRepeat")
         {
           static_cast< CScanWidgetRepeat * >(pWidget)->save(pItem);
         }
     }
   for (; i < oldSize; ++i)
     {
       mChanged = true;
       scanProblem->removeScanItem(newSize);
     }
   // the subtask
   const CScanWidgetTask * tmpT = dynamic_cast<CScanWidgetTask*>(widgetList[newSize]);
   if (tmpT != NULL)
     {
       mChanged |= tmpT->save(scanProblem);
     }
   // :TODO Bug 322: This should only be called when actual changes have been saved.
   // However we do not check whether the scan item are mChanged we delete all
   // and create them new.
   if (mChanged)
     {
       if (mpDataModel != NULL)
         {
           mpDataModel->changed();
         }
       mChanged = false;
     }
   return true;
 }
bool ScanWidget::slotAddItem () protected slot
Definition at line 203 of file ScanWidget.cpp.
References comboType, CScanProblem::createScanItem(), CCopasiSelectionDialog::getObjectVector(), CScanWidgetRandom::initFromObject(), CScanWidgetScan::initFromObject(), CQSimpleSelectionTree::InitialTime, CScanContainerWidget::insertWidget(), CScanWidgetRepeat::load(), CQSimpleSelectionTree::Parameters, pdelete, CScanProblem::SCAN_LINEAR, CScanProblem::SCAN_RANDOM, CScanProblem::SCAN_REPEAT, and scrollview.
Referenced by ScanWidget().
 {
   int totalRows = -1;
   //+++
   CScanWidgetScan* tmp1;
   CScanWidgetRepeat* tmp2;
   CScanWidgetRandom* tmp3;
   //CScanWidgetBreak* tmp4;
   int intType = comboType->currentIndex();
   CScanProblem::Type type;
   switch (intType)
     {
       case 0:
         type = CScanProblem::SCAN_LINEAR;
         break;
       case 1:
         type = CScanProblem::SCAN_REPEAT;
         break;
       case 2:
         type = CScanProblem::SCAN_RANDOM;
         break;
       default:
         type = CScanProblem::SCAN_LINEAR;
         break;
     }
   switch (type)
     {
       case CScanProblem::SCAN_REPEAT:
       {
         tmp2 = new CScanWidgetRepeat(scrollview);
         //create item to get the default values
         CCopasiParameterGroup* pItem = CScanProblem::createScanItem(type, 10);
         tmp2->load(pItem);
         pdelete(pItem);
         scrollview->insertWidget(tmp2);
         totalRows = scrollview->rowCount();
         tmp2->lineEditNumber->setFocus();
       }
       break;
       case CScanProblem::SCAN_LINEAR:
       {
         CQSimpleSelectionTree::ObjectClasses Classes = CQSimpleSelectionTree::InitialTime |
             CQSimpleSelectionTree::Parameters;
         std::vector< const CCopasiObject * > Selection = CCopasiSelectionDialog::getObjectVector(this, Classes);
         // create scan widgets as many as the number of selected objects
         std::vector< const CCopasiObject * >::iterator it = Selection.begin();
         std::vector< const CCopasiObject * >::iterator end = Selection.end();
         for (; it != end; ++it)
           {
             tmp1 = new CScanWidgetScan(scrollview);
             tmp1->initFromObject(*it);
             scrollview->insertWidget(tmp1);
             totalRows = scrollview->rowCount();
             tmp1->lineEditMin->setFocus();
           }
         break;
       }
       case CScanProblem::SCAN_RANDOM:
       {
         CQSimpleSelectionTree::ObjectClasses Classes = CQSimpleSelectionTree::InitialTime |
             CQSimpleSelectionTree::Parameters;
         std::vector< const CCopasiObject * > Selection = CCopasiSelectionDialog::getObjectVector(this, Classes);
         // create scan widgets as many as the number of selected objects
         std::vector< const CCopasiObject * >::iterator it = Selection.begin();
         std::vector< const CCopasiObject * >::iterator end = Selection.end();
         for (; it != end; ++it)
           {
             tmp3 = new CScanWidgetRandom(scrollview);
             tmp3->initFromObject(*it);
             scrollview->insertWidget(tmp3);
             totalRows = scrollview->rowCount();
             tmp3->lineEditMin->setFocus();
           }
         break;
       }
       default:
         break;
     }
   return true;
 }
Member Data Documentation
QPushButton* ScanWidget::buttonNewItem protected
Definition at line 50 of file ScanWidget.h.
Referenced by ScanWidget().
QComboBox* ScanWidget::comboType protected
Definition at line 51 of file ScanWidget.h.
Referenced by ScanWidget(), and slotAddItem().
QGridLayout* ScanWidget::ScanWidgetLayout protected
Definition at line 53 of file ScanWidget.h.
Referenced by ScanWidget().
CScanContainerWidget* ScanWidget::scrollview protected
Definition at line 46 of file ScanWidget.h.
Referenced by loadTask(), saveTask(), ScanWidget(), and slotAddItem().
The documentation for this class was generated from the following files:
ScanWidget.h
ScanWidget.cpp