COPASI API: CCopasiTimeVariable Class Reference
CCopasiTimeVariable Class Reference
#include <CopasiTime.h>
Public Member Functions
CCopasiTimeVariable ()
CCopasiTimeVariable (const CCopasiTimeVariable &src)
CCopasiTimeVariable (const C_INT64 &value)
C_INT64 getDays () const
C_INT64 getHours (const bool &bounded=false) const
C_INT64 getMicroSeconds (const bool &bounded=false) const
C_INT64 getMilliSeconds (const bool &bounded=false) const
C_INT64 getMinutes (const bool &bounded=false) const
C_INT64 getSeconds (const bool &bounded=false) const
std::string isoFormat () const
CCopasiTimeVariable operator+ (const CCopasiTimeVariable &value)
CCopasiTimeVariable operator- (const CCopasiTimeVariable &value)
bool operator< (const CCopasiTimeVariable &value)
CCopasiTimeVariable & operator= (const CCopasiTimeVariable &rhs)
CCopasiTimeVariable & operator= (const C_INT64 &value)
~CCopasiTimeVariable ()
Static Public Member Functions
static CCopasiTimeVariable getCurrentWallTime ()
static CCopasiTimeVariable getProcessTime ()
static CCopasiTimeVariable getThreadTime ()
static std::string LL2String (const C_INT64 &value, const C_INT32 &digits=0)
Private Attributes
C_INT64 mTime
Detailed Description
This class is for handling execution time related values. static methods for retreiving wall clock and CPU time are provided.
Definition at line 28 of file CopasiTime.h.
Constructor & Destructor Documentation
CCopasiTimeVariable::CCopasiTimeVariable ()
Default constructor.
Definition at line 41 of file CopasiTime.cpp.
                                         :
     mTime(LLONG_CONST(0))
 {}
CCopasiTimeVariable::CCopasiTimeVariable (const CCopasiTimeVariable & src)
Copy constructor.
Parameters
const CCopasiTimeVariable & src
Definition at line 45 of file CopasiTime.cpp.
                                                                        :
     mTime(src.mTime)
 {}
CCopasiTimeVariable::CCopasiTimeVariable (const C_INT64 & value)
Specific constructor from a C_INT64 value.
Parameters
const C_INT64 & value
Definition at line 49 of file CopasiTime.cpp.
                                                              :
     mTime(value)
 {}
CCopasiTimeVariable::~CCopasiTimeVariable ()
Destructor.
Definition at line 53 of file CopasiTime.cpp.
 {}
Member Function Documentation
CCopasiTimeVariable CCopasiTimeVariable::getCurrentWallTime () static
Retrieve the current wall clock time in micro seconds since 1970-01-01:00:00:00.0
Returns
CCopasiTimeVariable time
Definition at line 160 of file CopasiTime.cpp.
References C_INT64, and LLONG_CONST.
Referenced by CCopasiTimer::CCopasiTimer(), CopasiPlot::compile(), CProcessReport::CProcessReport(), CRandom::getSystemSeed(), CProcessReport::proceed(), CCopasiTimer::refresh(), CopasiPlot::replot(), and CCopasiTimer::start().
 {
   timeval ttt;
   gettimeofday(&ttt, 0);
   C_INT64 time;
   time = ((C_INT64) ttt.tv_sec) * LLONG_CONST(1000000) + (C_INT64) ttt.tv_usec;
   return time;
 }
C_INT64 CCopasiTimeVariable::getDays () const
Retrieve the time in days.
Parameters
const bool & bounded (default: false)
Returns
C_INT64 days
Definition at line 150 of file CopasiTime.cpp.
References C_INT64, LLONG_CONST, and mTime.
Referenced by isoFormat().
 {
   C_INT64 Days = mTime / LLONG_CONST(86400000000);
   return Days;
 }
C_INT64 CCopasiTimeVariable::getHours (const bool & bounded = false) const
Retrieve the time in hours. If bounded is true 0 <= hours < 24
Parameters
const bool & bounded (default: false)
Returns
C_INT64 hours
Definition at line 142 of file CopasiTime.cpp.
References C_INT64, LLONG_CONST, and mTime.
Referenced by isoFormat().
 {
   C_INT64 Hours = mTime / LLONG_CONST(3600000000);
   if (bounded) return Hours % LLONG_CONST(24);
   else return Hours;
 }
C_INT64 CCopasiTimeVariable::getMicroSeconds (const bool & bounded = false) const
Retrieve the time in micro seconds. If bounded is true 0 <= microSeconds < 1000
Parameters
const bool & bounded (default: false)
Returns
C_INT64 microSeconds
Definition at line 112 of file CopasiTime.cpp.
References LLONG_CONST, and mTime.
Referenced by CRandom::getSystemSeed(), isoFormat(), CCopasiTimer::refresh(), and CopasiPlot::replot().
 {
   if (bounded) return mTime % LLONG_CONST(1000);
   else return mTime;
 }
C_INT64 CCopasiTimeVariable::getMilliSeconds (const bool & bounded = false) const
Retrieve the time in milli seconds. If bounded is true 0 <= milliSeconds < 1000
Parameters
const bool & bounded (default: false)
Returns
C_INT64 milliSeconds
Definition at line 118 of file CopasiTime.cpp.
References C_INT64, LLONG_CONST, and mTime.
Referenced by isoFormat(), CFitProblem::printResult(), and COptProblem::printResult().
 {
   C_INT64 MilliSeconds = mTime / LLONG_CONST(1000);
   if (bounded) return MilliSeconds % LLONG_CONST(1000);
   else return MilliSeconds;
 }
C_INT64 CCopasiTimeVariable::getMinutes (const bool & bounded = false) const
Retrieve the time in minutes. If bounded is true 0 <= minutes < 60
Parameters
const bool & bounded (default: false)
Returns
C_INT64 minutes
Definition at line 134 of file CopasiTime.cpp.
References C_INT64, LLONG_CONST, and mTime.
Referenced by isoFormat().
 {
   C_INT64 Minutes = mTime / LLONG_CONST(60000000);
   if (bounded) return Minutes % LLONG_CONST(60);
   else return Minutes;
 }
CCopasiTimeVariable CCopasiTimeVariable::getProcessTime () static
Retrieve the current process CPU time used since the start of the process.
Returns
CCopasiTimeVariable time
Definition at line 180 of file CopasiTime.cpp.
References C_INT64, and LLONG_CONST.
Referenced by CCopasiTimer::CCopasiTimer(), CCopasiTimer::refresh(), and CCopasiTimer::start().
 {
 #ifdef WIN32
   LARGE_INTEGER CreationTime;
   LARGE_INTEGER ExitTime;
   LARGE_INTEGER KernelTime;
   LARGE_INTEGER UserTime;
   GetProcessTimes(GetCurrentProcess(),
                   (FILETIME *) &CreationTime,
                   (FILETIME *) &ExitTime,
                   (FILETIME *) &KernelTime,
                   (FILETIME *) &UserTime);
   return (KernelTime.QuadPart + UserTime.QuadPart) / LLONG_CONST(10);
 #else
   struct rusage ResourceUsage;
   getrusage(RUSAGE_SELF, &ResourceUsage);
   return ((C_INT64) ResourceUsage.ru_utime.tv_sec) * LLONG_CONST(1000000)
          + (C_INT64) ResourceUsage.ru_utime.tv_usec;
 #endif // WIN32
 }
C_INT64 CCopasiTimeVariable::getSeconds (const bool & bounded = false) const
Retrieve the time in seconds. If bounded is true 0 <= seconds < 60
Parameters
const bool & bounded (default: false)
Returns
C_INT64 seconds
Definition at line 126 of file CopasiTime.cpp.
References C_INT64, LLONG_CONST, and mTime.
Referenced by isoFormat(), CFitProblem::printResult(), and COptProblem::printResult().
 {
   C_INT64 Seconds = mTime / LLONG_CONST(1000000);
   if (bounded) return Seconds % LLONG_CONST(60);
   else return Seconds;
 }
CCopasiTimeVariable CCopasiTimeVariable::getThreadTime () static
Retrieve the current process thread time used since the start of the process.
Returns
CCopasiTimeVariable time
Definition at line 206 of file CopasiTime.cpp.
References C_INT64, LLONG_CONST, and RUSAGE_THREAD.
Referenced by CCopasiTimer::CCopasiTimer(), CCopasiTimer::refresh(), and CCopasiTimer::start().
 {
 #ifdef WIN32
   LARGE_INTEGER CreationTime;
   LARGE_INTEGER ExitTime;
   LARGE_INTEGER KernelTime;
   LARGE_INTEGER UserTime;
   GetThreadTimes(GetCurrentThread(),
                  (FILETIME *) &CreationTime,
                  (FILETIME *) &ExitTime,
                  (FILETIME *) &KernelTime,
                  (FILETIME *) &UserTime);
   return (KernelTime.QuadPart + UserTime.QuadPart) / LLONG_CONST(10);
 #elif defined Darwin
   struct thread_basic_info t_info;
   mach_msg_type_number_t t_info_count = THREAD_BASIC_INFO_COUNT;
   if (KERN_SUCCESS != task_info(mach_task_self(),
                                 THREAD_BASIC_INFO, (task_info_t) & t_info, & t_info_count))
     {
       return -1;
     }
   return ((C_INT64) t_info.user_time.seconds) * LLONG_CONST(1000000)
          + (C_INT64) t_info.user_time.microseconds;
 #else
   struct rusage ResourceUsage;
   getrusage(RUSAGE_THREAD, &ResourceUsage);
   return ((C_INT64) ResourceUsage.ru_utime.tv_sec) * LLONG_CONST(1000000)
          + (C_INT64) ResourceUsage.ru_utime.tv_usec;
 #endif // WIN32
 }
std::string CCopasiTimeVariable::isoFormat () const
Create a iso formated string (D:HH:MM:SS.ssssss)
Returns
std::string
Definition at line 76 of file CopasiTime.cpp.
References getDays(), getHours(), getMicroSeconds(), getMilliSeconds(), getMinutes(), getSeconds(), isoFormat(), LL2String(), LLONG_CONST, and mTime.
Referenced by isoFormat().
 {
   std::stringstream Iso;
   bool first = true;
   if (mTime < LLONG_CONST(0))
     {
       CCopasiTimeVariable Tmp(-mTime);
       Iso << "-";
       Iso << Tmp.isoFormat();
       return Iso.str();
     }
   if (mTime >= LLONG_CONST(86400000000))
     {
       Iso << LL2String(getDays()) << ":";
       first = false;
     }
   if (mTime >= LLONG_CONST(3600000000))
     Iso << LL2String(getHours(true), first ? 0 : 2) << ":";
   if (mTime >= LLONG_CONST(60000000))
     Iso << LL2String(getMinutes(true), first ? 0 : 2) << ":";
   if (mTime >= LLONG_CONST(1000000))
     Iso << LL2String(getSeconds(true), first ? 0 : 2) << ".";
   else
     Iso << "0.";
   Iso << LL2String(getMilliSeconds(true), 3) << LL2String(getMicroSeconds(true), 3);
   return Iso.str();
 }
std::string CCopasiTimeVariable::LL2String (const C_INT64 & value, const C_INT32 & digits = 0) static
Helper function to convert a C_INT32 to a std::string. If the number of digits is non zero the value is padded with zeros.
Parameters
const C_INT64 & value
const C_INT32 & digits (default: 0)
Returns
std::string
Definition at line 246 of file CopasiTime.cpp.
References StringPrint().
Referenced by isoFormat(), CFitProblem::printResult(), and COptProblem::printResult().
 {
   std::string format;
   if (digits > 0)
     format = "%0" + StringPrint("%d", digits);
   else
     format = "%";
 #ifdef WIN32
   format += "I64d";
 #else
   format += "lld";
 #endif
   return StringPrint(format.c_str(), value);
 }
CCopasiTimeVariable CCopasiTimeVariable::operator+ (const CCopasiTimeVariable & value)
Operator + for adding CCopasiTimeVariables
Parameters
const CCopasiTimeVariable & value
Returns
CCopasiTimeVariable sum
Definition at line 55 of file CopasiTime.cpp.
References mTime.
 {return mTime + value.mTime;}
CCopasiTimeVariable CCopasiTimeVariable::operator- (const CCopasiTimeVariable & value)
Operator - for subtracting CCopasiTimeVariables
Parameters
const CCopasiTimeVariable & value
Returns
CCopasiTimeVariable difference
Definition at line 58 of file CopasiTime.cpp.
References mTime.
 {return mTime - value.mTime;}
bool CCopasiTimeVariable::operator< (const CCopasiTimeVariable & value)
Coparison operator <
Parameters
const CCopasiTimeVariable & value
Returns
bool isLess
Definition at line 73 of file CopasiTime.cpp.
References mTime.
 {return (mTime < value.mTime);}
CCopasiTimeVariable & CCopasiTimeVariable::operator= (const CCopasiTimeVariable & rhs)
Assignement operator
Parameters
const CCopasiTimeVariable & rhs
Returns
CCopasiTimeVariable & this
Definition at line 61 of file CopasiTime.cpp.
References mTime.
 {
   mTime = rhs.mTime;
   return *this;
 }
CCopasiTimeVariable & CCopasiTimeVariable::operator= (const C_INT64 & value)
Assignement operator assigning a C_INT64 value to a CCopasiTimeVariable
Parameters
const CCopasiTimeVariable & rhs
Returns
CCopasiTimeVariable & this
Definition at line 67 of file CopasiTime.cpp.
References mTime.
 {
   mTime = value;
   return *this;
 }
Member Data Documentation
C_INT64 CCopasiTimeVariable::mTime private
Value containing the time in micro seconds.
Definition at line 175 of file CopasiTime.h.
Referenced by getDays(), getHours(), getMicroSeconds(), getMilliSeconds(), getMinutes(), getSeconds(), isoFormat(), operator+(), operator-(), operator<(), and operator=().
The documentation for this class was generated from the following files:
CopasiTime.h
CopasiTime.cpp