COPASI API: CColorScale Class Reference
CColorScale Class Reference abstract
#include <CColorScale.h>
Public Member Functions
CColorScale ()
virtual void finishAutomaticParameterCalculation ()
virtual QColor getColor (const C_FLOAT64 &number)=0
bool isUsed () const
virtual void passValue (const C_FLOAT64 &)
void setIsUsed (bool f)
virtual void startAutomaticParameterCalculation ()
virtual ~CColorScale ()
Private Attributes
bool mIsUsed
Detailed Description
Base class for color scales. The derived classes provide algorithms to map a double number to a QColor. The scaling parameters can either be set automatically (by using methods provided by the derived classes) or be determined automatically. For automatic scaling all numbers that are to be displayed (or at least a typical sample) have to be passed to the passValue() method before the getColor() method is used. This class is used by ArrayAnnotationWidget.
Definition at line 32 of file CColorScale.h.
Constructor & Destructor Documentation
CColorScale::CColorScale () inline
Definition at line 35 of file CColorScale.h.
 : mIsUsed(false) {};
virtual CColorScale::~CColorScale () inline virtual
Definition at line 37 of file CColorScale.h.
 {};
Member Function Documentation
virtual void CColorScale::finishAutomaticParameterCalculation () inline virtual
this finishes the calculation of the scaling parameters.
Reimplemented in CColorScaleBiLog, CColorScaleAverage, and CColorScaleSimple.
Definition at line 57 of file CColorScale.h.
Referenced by CQArrayAnnotationsWidget::fillTable1(), and CQArrayAnnotationsWidget::fillTableN().
 {};
virtual QColor CColorScale::getColor (const C_FLOAT64 & number) pure virtual
this method maps a number to a color.
Implemented in CColorScaleBiLog, CColorScaleAdvanced, CColorScaleSimple, and CColorScale1.
Referenced by CQArrayAnnotationsWidget::fillBarChart(), CQArrayAnnotationsWidget::fillTable1(), and CQArrayAnnotationsWidget::fillTableN().
bool CColorScale::isUsed () const inline
if setIsUsed() was used isUsed() can be called to find out if the scaler is already in use. One scaler must not be used in several widgets.
Definition at line 68 of file CColorScale.h.
Referenced by CQArrayAnnotationsWidget::setColorCoding().
 {return mIsUsed;};
virtual void CColorScale::passValue (const C_FLOAT64 &) inline virtual
with this method numbers are passed to the automatic scaling algorithm.
Reimplemented in CColorScaleBiLog, CColorScaleAverage, and CColorScaleSimple.
Definition at line 52 of file CColorScale.h.
Referenced by CQArrayAnnotationsWidget::fillTable1(), and CQArrayAnnotationsWidget::fillTableN().
 {};
void CColorScale::setIsUsed (bool f) inline
this is called by the array annotation widget to indicate that the scaler is in use
Definition at line 62 of file CColorScale.h.
References mIsUsed.
Referenced by CQArrayAnnotationsWidget::setColorCoding().
 {mIsUsed = f;};
virtual void CColorScale::startAutomaticParameterCalculation () inline virtual
this method starts the calculation of the scaling parameters.
Reimplemented in CColorScaleBiLog, CColorScaleAverage, and CColorScaleSimple.
Definition at line 47 of file CColorScale.h.
Referenced by CQArrayAnnotationsWidget::fillTable1(), and CQArrayAnnotationsWidget::fillTableN().
 {};
Member Data Documentation
bool CColorScale::mIsUsed private
This flag indicates whether the scaler is in use. The widget using the scaler must call setIsUsed() to keep this up to date.
Definition at line 68 of file CColorScale.h.
Referenced by setIsUsed().
The documentation for this class was generated from the following file:
CColorScale.h