COPASI API: CCopasiXMLParser::InitialStateElement Class Reference
CCopasiXMLParser::InitialStateElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
InitialStateElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~InitialStateElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { InitialState = 0, etc }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 499 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::InitialStateElement::Element private
Enum of invoked parsers
Enumerator
InitialState
etc
Definition at line 507 of file CCopasiXMLParser.h.
     {
       InitialState = 0,
       etc
     };
Constructor & Destructor Documentation
CCopasiXMLParser::InitialStateElement::InitialStateElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 5284 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::InitialStateElement::~InitialStateElement () virtual
Destructor
Definition at line 5289 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::InitialStateElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 5327 of file CCopasiXMLParser.cpp.
References CState::beginIndependent(), C_FLOAT64, C_INVALID_INDEX, CCopasiMessage::EXCEPTION, fatalError, CStateTemplate::getIndex(), CModel::getInitialState(), CModel::getStateTemplate(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, CModel::setInitialState(), START_ELEMENT, SCopasiXMLParserCommon::StateVariableList, and UNKNOWN_ELEMENT.
 {
   std::istringstream Values;
   std::string StringValue;
   std::vector< CModelEntity * >::iterator it;
   std::vector< CModelEntity * >::iterator end;
   double Value;
   const CStateTemplate & Template = mCommon.pModel->getStateTemplate();
   CState IState = mCommon.pModel->getInitialState();
   C_FLOAT64 * pValues = IState.beginIndependent() - 1;
   size_t Index;
   switch (mCurrentElement)
     {
       case InitialState:
         if (strcmp(pszName, "InitialState"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialState", mParser.getCurrentLineNumber());
         Values.str(mParser.getCharacterData("\x0a\x0d\t ", " "));
         it = mCommon.StateVariableList.begin();
         end = mCommon.StateVariableList.end();
         for (Values >> StringValue; it != end; ++it, Values >> StringValue)
           {
             if (Values.fail()) break;
             Value = CCopasiXMLInterface::DBL(StringValue.c_str());
             Index = Template.getIndex(*it);
             if (Index != C_INVALID_INDEX)
               {
                 pValues[Index] = Value;
                 continue;
               }
             fatalError();
           }
         if (it != end || !Values.fail() || !Values.eof())
           {
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 17, mParser.getCurrentLineNumber());
           }
         mCommon.pModel->setInitialState(IState);
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::InitialStateElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 5294 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, fatalError, MCXML, CExpatTemplate< CExpat >::mParser, and UNKNOWN_ELEMENT.
 {
   const char * Type;
   mCurrentElement++; /* We should always be on the next element */
   switch (mCurrentElement)
     {
       case InitialState:
         if (strcmp(pszName, "InitialState"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "InitialState", mParser.getCurrentLineNumber());
         Type = mParser.getAttributeValue("type", papszAttrs, "initialState");
         if (strcmp(Type, "initialState")) fatalError();
         mParser.enableCharacterDataHandler();
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp