COPASI API: ListViews Class Reference
ListViews Class Reference
#include <listviews.h>
Public Types
enum Action { CHANGE = 0, ADD, DELETE, RENAME }
enum ObjectType {
METABOLITE = 0, COMPARTMENT, REACTION, FUNCTION,
MODEL, STATE, REPORT, PLOT,
MODELVALUE, EVENT, MIRIAM, LAYOUT,
PARAMETEROVERVIEW, MODELPARAMETERSET
}
Public Slots
void slotFolderChanged (const QModelIndex &index)
Signals
void signalFolderChanged (const QModelIndex &index)
Public Member Functions
void commit ()
CopasiWidget * findWidgetFromId (const size_t &id) const
CQCrossSectionTaskWidget * getCrossSectionWidget ()
size_t getCurrentItemId ()
CopasiWidget * getCurrentWidget ()
DataModelGUI * getDataModel ()
CQFittingWidget * getFittingWidget ()
CQLNAWidget * getLNAWidget ()
CQMCAWidget * getMCAWidget ()
CQOptimizationWidget * getOptimizationWidget ()
ScanWidget * getScanWidget ()
SteadyStateWidget * getSteadyStateWidget ()
CQTrajectoryWidget * getTrajectoryWidget ()
ListViews (QWidget *parent=0, const char *name=0)
void setDataModel (DataModelGUI *pDM)
void setFramework (int framework)
void switchToOtherWidget (const size_t &id, const std::string &key)
void updateMIRIAMResourceContents ()
virtual ~ListViews ()
Static Public Attributes
static const std::string ObjectTypeName []
Private Slots
bool slotNotify (ListViews::ObjectType objectType, ListViews::Action action, std::string key="")
void slotSort (const QModelIndex &index1, const QModelIndex &index2)
Private Member Functions
void ConstructNodeWidgets ()
CopasiWidget * findWidgetFromIndex (const QModelIndex &index) const
void notifyChildWidgets (ObjectType objectType, Action action, const std::string &key)
bool updateCurrentWidget (ObjectType objectType, Action action, const std::string &key="")
Private Attributes
CQTabWidget * compartmentsWidget1
CQCrossSectionTaskWidget * crossSectionTaskWidget
CQTimeSeriesWidget * crossSectionTimeSeriesWidget
CQSplashWidget * defaultWidget
CQDifferentialEquations * differentialEquations
CQEventsWidget * eventsWidget
CQTabWidget * eventWidget1
CQTabWidget * functionWidget1
CQLyapResultWidget * lyapResultWidget
CQLyapWidget * lyapWidget
std::string mCurrentItemKey
CQTabWidget * metabolitesWidget1
CQTabWidget * modelWidget
CLNAResultWidget * mpCLNAResultWidget
CMCAResultWidget * mpCMCAResultWidget
CQCompartmentsWidget * mpCompartmentsWidget
CQLNAWidget * mpCQLNAWidget
CQMCAWidget * mpCQMCAWidget
CopasiWidget * mpCurrentWidget
DataModelGUI * mpDataModelGUI
CQEFMResultWidget * mpEFMResultWidget
CQEFMWidget * mpEFMWidget
CQFittingResult * mpFittingResultWidget
CQFunctionsWidget * mpFunctionsWidget
CQGlobalQuantitiesWidget * mpGlobalQuantitiesWidget
CQLayoutsWidget * mpLayoutsWidget
CQMathMatrixWidget * mpMathMatrixWidget
CMathModel * mpMathModel
CQTabWidget * mpModelValueWidget
CQMoietiesTaskResult * mpMoietiesTaskResult
CQMoietiesTaskWidget * mpMoietiesTaskWidget
CQParameterOverviewWidget * mpParameterOverviewWidget
CQParameterSetsWidget * mpParameterSetsWidget
CQTabWidget * mpParameterSetWidget
CQPlotSubwidget * mpPlotSubwidget
CQPlotsWidget * mpPlotsWidget
CQReactionsWidget * mpReactionsWidget
CQReportsWidget * mpReportsWidget
CQSpeciesWidget * mpSpeciesWidget
QStackedWidget * mpStackedWidget
CQBrowserPaneDM * mpTreeDM
QSortFilterProxyModel * mpTreeSortDM
CQBrowserPane * mpTreeView
CQOptimizationWidget * optimizationWidget
CQOptimizationResult * optResultWidget
CQFittingWidget * paramFittingWidget
CQTabWidget * reactionsWidget1
ScanWidget * scanWidget
CQSensResultWidget * sensResultWidget
SensitivitiesWidget * sensWidget
CQSteadyStateResult * stateWidget
SteadyStateWidget * steadystateWidget
CQReportDefinition * tableDefinition1
CQTimeSeriesWidget * timeSeriesWidget
CQTrajectoryWidget * trajectoryWidget
CQTSSAResultWidget * tssaResultWidget
CQTSSAWidget * tssaWidget
Friends
class CopasiUI3Window
Detailed Description
Definition at line 100 of file listviews.h.
Member Enumeration Documentation
enum ListViews::Action
Enumerator
CHANGE
ADD
DELETE
RENAME
Definition at line 116 of file listviews.h.
 {CHANGE = 0, ADD, DELETE, RENAME};
enum ListViews::ObjectType
Enumerator
METABOLITE
COMPARTMENT
REACTION
FUNCTION
MODEL
STATE
REPORT
PLOT
MODELVALUE
EVENT
MIRIAM
LAYOUT
PARAMETEROVERVIEW
MODELPARAMETERSET
Definition at line 117 of file listviews.h.
                   {METABOLITE = 0
                                 , COMPARTMENT
                    , REACTION
                    , FUNCTION
                    , MODEL
                    , STATE
                    , REPORT
                    , PLOT
                    , MODELVALUE
                    , EVENT
                    , MIRIAM
                    , LAYOUT
                    , PARAMETEROVERVIEW
                    , MODELPARAMETERSET
                   };
Constructor & Destructor Documentation
ListViews::ListViews (QWidget * parent = 0, const char * name = 0)
Definition at line 143 of file listviews.cpp.
References defaultWidget, mCurrentItemKey, mpCurrentWidget, mpStackedWidget, mpTreeDM, mpTreeSortDM, mpTreeView, and slotSort().
                                                      :
   QSplitter(Qt::Horizontal, parent),
   mpDataModelGUI(NULL),
   mpTreeDM(NULL),
   mpTreeSortDM(NULL),
   mpMathModel(NULL),
   mpCurrentWidget(NULL),
   mCurrentItemKey(),
   mpCMCAResultWidget(NULL),
   mpCQMCAWidget(NULL),
   mpCQLNAWidget(NULL),
   mpCLNAResultWidget(NULL),
   mpCompartmentsWidget(NULL),
   compartmentsWidget1(NULL),
   defaultWidget(NULL),
   differentialEquations(NULL),
   eventsWidget(NULL),
   eventWidget1(NULL),
   mpFunctionsWidget(NULL),
   functionWidget1(NULL),
   lyapWidget(NULL),
   lyapResultWidget(NULL),
   mpSpeciesWidget(NULL),
   metabolitesWidget1(NULL),
   modelWidget(NULL),
   mpGlobalQuantitiesWidget(NULL),
   mpModelValueWidget(NULL),
   mpEFMWidget(NULL),
   mpEFMResultWidget(NULL),
   mpMoietiesTaskResult(NULL),
   mpMoietiesTaskWidget(NULL),
   optimizationWidget(NULL),
   optResultWidget(NULL),
   paramFittingWidget(NULL),
   mpFittingResultWidget(NULL),
   mpParameterOverviewWidget(NULL),
   mpParameterSetsWidget(NULL),
   mpParameterSetWidget(NULL),
   mpPlotsWidget(NULL),
   mpPlotSubwidget(NULL),
   mpReactionsWidget(NULL),
   reactionsWidget1(NULL),
   scanWidget(NULL),
   sensWidget(NULL),
   sensResultWidget(NULL),
   stateWidget(NULL),
   steadystateWidget(NULL),
   mpReportsWidget(NULL),
   tableDefinition1(NULL),
   timeSeriesWidget(NULL),
   trajectoryWidget(NULL),
   tssaWidget(NULL),
   tssaResultWidget(NULL),
   crossSectionTaskWidget(NULL),
   crossSectionTimeSeriesWidget(NULL),
 #ifdef COPASI_NONLIN_DYN_OSCILLATION
   oscillationTaskWidget(NULL),
 #endif
 #ifdef COPASI_DEBUG
   mpUpdatesWidget(NULL),
 #endif
   mpLayoutsWidget(NULL),
   mpMathMatrixWidget(NULL)
 {
   // Qt3 support to Qt4 reference states . . .
   // "Use the QSizePolicy() constructor and call the setHorizontalStretch(), setVerticalStretch(), and setHeightForWidth() functions instead."
   // The stretch was set at "1 ,1", before, but maybe it doesn't need to be explicitly set now.
   this->setSizePolicy(QSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred));
   setChildrenCollapsible(false);
   // create a new QListview to be displayed on the screen..and set its property
   mpTreeView = new CQBrowserPane(this);
   mpTreeDM = new CQBrowserPaneDM(this);
   mpTreeSortDM = new QSortFilterProxyModel(this);
   mpTreeSortDM->setSourceModel(mpTreeDM);
   mpTreeSortDM->setSortRole(Qt::EditRole);
   mpTreeSortDM->setSortCaseSensitivity(Qt::CaseInsensitive);
   // pSortModel->sort(0, Qt::AscendingOrder);
   mpTreeView->setModel(mpTreeSortDM);
   mpTreeView->sortByColumn(0, Qt::AscendingOrder);
   mpStackedWidget = new QStackedWidget(this);
   addWidget(mpTreeView);
   addWidget(mpStackedWidget);
   if (!opaqueResize())
     setOpaqueResize();
   defaultWidget = new CQSplashWidget(this);
   mpStackedWidget->addWidget(defaultWidget);
   mpCurrentWidget = defaultWidget; // keeps track of the mpCurrentWidget in use
   mCurrentItemKey = "";
   mpStackedWidget->setCurrentWidget(defaultWidget);
   QList<int> Sizes = sizes();
   Sizes[0] = 240;
   Sizes[1] = 560;
   setSizes(Sizes);
   // establishes the communication between the mpTreeView clicked and the routine called....
   connect(mpTreeDM, SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
           this, SLOT(slotSort(const QModelIndex &, const QModelIndex &)));
 }
ListViews::~ListViews () virtual
Definition at line 252 of file listviews.cpp.
References CQLayoutsWidget::deleteLayoutWindows(), and mpLayoutsWidget.
 {
   //TODO clean up
   if (mpLayoutsWidget != NULL)
     mpLayoutsWidget->deleteLayoutWindows();
 }
Member Function Documentation
void ListViews::commit ()
Definition at line 998 of file listviews.cpp.
References CopasiWidget::leave(), and mpCurrentWidget.
 {
   if (mpCurrentWidget != NULL)
     mpCurrentWidget->leave();
 }
void ListViews::ConstructNodeWidgets () private
Definition at line 298 of file listviews.cpp.
References COMPARTMENT, compartmentsWidget1, crossSectionTaskWidget, crossSectionTimeSeriesWidget, differentialEquations, EVENT, eventsWidget, eventWidget1, FUNCTION, functionWidget1, lyapResultWidget, lyapWidget, METABOLITE, metabolitesWidget1, MODEL, MODELPARAMETERSET, MODELVALUE, modelWidget, mpCLNAResultWidget, mpCMCAResultWidget, mpCompartmentsWidget, mpCQLNAWidget, mpCQMCAWidget, mpEFMResultWidget, mpEFMWidget, mpFittingResultWidget, mpFunctionsWidget, mpGlobalQuantitiesWidget, mpLayoutsWidget, mpMathMatrixWidget, mpModelValueWidget, mpMoietiesTaskResult, mpMoietiesTaskWidget, mpParameterOverviewWidget, mpParameterSetsWidget, mpParameterSetWidget, mpPlotSubwidget, mpPlotsWidget, mpReactionsWidget, mpReportsWidget, mpSpeciesWidget, mpStackedWidget, optimizationWidget, optResultWidget, paramFittingWidget, REACTION, reactionsWidget1, scanWidget, sensResultWidget, sensWidget, stateWidget, steadystateWidget, tableDefinition1, timeSeriesWidget, trajectoryWidget, tssaResultWidget, and tssaWidget.
Referenced by setDataModel().
 {
   // create the model widgets
   if (!mpCompartmentsWidget)
     {
       mpCompartmentsWidget = new CQCompartmentsWidget(this);
       mpStackedWidget->addWidget(mpCompartmentsWidget);
     }
   if (!compartmentsWidget1)
     {
       compartmentsWidget1 = new CQTabWidget(ListViews::COMPARTMENT, new CQCompartment(this), this);
       mpStackedWidget->addWidget(compartmentsWidget1);
     }
 #ifdef HAVE_MML
   if (!differentialEquations)
     {
       differentialEquations = new CQDifferentialEquations(this);
       mpStackedWidget->addWidget(differentialEquations);
     }
 #endif // HAVE_MML
   if (!eventsWidget)
     {
       eventsWidget = new CQEventsWidget(this);
       mpStackedWidget->addWidget(eventsWidget);
     }
   if (!eventWidget1)
     {
       eventWidget1 = new CQTabWidget(ListViews::EVENT, new CQEventWidget1(this), this);
       mpStackedWidget->addWidget(eventWidget1);
     }
   if (!mpFunctionsWidget)
     {
       mpFunctionsWidget = new CQFunctionsWidget(this);
       mpStackedWidget->addWidget(mpFunctionsWidget);
     }
   if (!functionWidget1)
     {
       functionWidget1 = new CQTabWidget(ListViews::FUNCTION, new FunctionWidget1(this), this);
       mpStackedWidget->addWidget(functionWidget1);
     }
   if (!lyapWidget)
     {
       lyapWidget = new CQLyapWidget(this);
       mpStackedWidget->addWidget(lyapWidget);
     }
   if (!lyapResultWidget)
     {
       lyapResultWidget = new CQLyapResultWidget(this);
       mpStackedWidget->addWidget(lyapResultWidget);
     }
   if (!mpSpeciesWidget)
     {
       mpSpeciesWidget = new CQSpeciesWidget(this);
       mpStackedWidget->addWidget(mpSpeciesWidget);
     }
   if (!metabolitesWidget1)
     {
       metabolitesWidget1 = new CQTabWidget(ListViews::METABOLITE, new CQSpeciesDetail(this), this);
       mpStackedWidget->addWidget(metabolitesWidget1);
     }
   if (!modelWidget)
     {
       modelWidget = new CQTabWidget(ListViews::MODEL, new CQModelWidget(this), this);
       mpStackedWidget->addWidget(modelWidget);
     }
   if (!mpModelValueWidget)
     {
       mpModelValueWidget = new CQTabWidget(ListViews::MODELVALUE, new CQModelValue(this), this);
       mpStackedWidget->addWidget(mpModelValueWidget);
     }
   if (!mpGlobalQuantitiesWidget)
     {
       mpGlobalQuantitiesWidget = new CQGlobalQuantitiesWidget(this);
       mpStackedWidget->addWidget(mpGlobalQuantitiesWidget);
     }
   if (!mpEFMWidget)
     {
       mpEFMWidget = new CQEFMWidget(this);
       mpStackedWidget->addWidget(mpEFMWidget);
     }
   if (!mpEFMResultWidget)
     {
       mpEFMResultWidget = new CQEFMResultWidget(this);
       mpStackedWidget->addWidget(mpEFMResultWidget);
     }
   if (!mpMoietiesTaskResult)
     {
       mpMoietiesTaskResult = new CQMoietiesTaskResult(this);
       mpStackedWidget->addWidget(mpMoietiesTaskResult);
     }
   if (!mpMoietiesTaskWidget)
     {
       mpMoietiesTaskWidget = new CQMoietiesTaskWidget(this);
       mpStackedWidget->addWidget(mpMoietiesTaskWidget);
     }
   if (!mpParameterOverviewWidget)
     {
       mpParameterOverviewWidget = new CQParameterOverviewWidget(this);
       mpStackedWidget->addWidget(mpParameterOverviewWidget);
     }
   if (!mpParameterSetsWidget)
     {
       mpParameterSetsWidget = new CQParameterSetsWidget(this);
       mpStackedWidget->addWidget(mpParameterSetsWidget);
     }
   if (!mpParameterSetWidget)
     {
       mpParameterSetWidget = new CQTabWidget(ListViews::MODELPARAMETERSET, new CQParameterOverviewWidget(this), this);
       mpStackedWidget->addWidget(mpParameterSetWidget);
     }
   if (!mpCMCAResultWidget)
     {
       mpCMCAResultWidget = new CMCAResultWidget(this);
       mpStackedWidget->addWidget(mpCMCAResultWidget);
     }
   if (!mpCQMCAWidget)
     {
       mpCQMCAWidget = new CQMCAWidget(this);
       mpStackedWidget->addWidget(mpCQMCAWidget);
     }
   if (!mpCLNAResultWidget)
     {
       mpCLNAResultWidget = new CLNAResultWidget(this);
       mpStackedWidget->addWidget(mpCLNAResultWidget);
     }
   if (!mpCQLNAWidget)
     {
       mpCQLNAWidget = new CQLNAWidget(this);
       mpStackedWidget->addWidget(mpCQLNAWidget);
     }
   if (!optimizationWidget)
     {
       optimizationWidget = new CQOptimizationWidget(this);
       mpStackedWidget->addWidget(optimizationWidget);
     }
   if (!optResultWidget)
     {
       optResultWidget = new CQOptimizationResult(this);
       mpStackedWidget->addWidget(optResultWidget);
     }
   if (!paramFittingWidget)
     {
       paramFittingWidget = new CQFittingWidget(this);
       mpStackedWidget->addWidget(paramFittingWidget);
     }
   if (!mpFittingResultWidget)
     {
       mpFittingResultWidget = new CQFittingResult(this);
       mpStackedWidget->addWidget(mpFittingResultWidget);
     }
   if (!mpPlotsWidget)
     {
       mpPlotsWidget = new CQPlotsWidget(this);
       mpStackedWidget->addWidget(mpPlotsWidget);
     }
   if (!mpPlotSubwidget)
     {
       mpPlotSubwidget = new CQPlotSubwidget(this);
       mpStackedWidget->addWidget(mpPlotSubwidget);
     }
   if (!mpReactionsWidget)
     {
       mpReactionsWidget = new CQReactionsWidget(this);
       mpStackedWidget->addWidget(mpReactionsWidget);
     }
   if (!reactionsWidget1)
     {
       reactionsWidget1 = new CQTabWidget(ListViews::REACTION, new ReactionsWidget1(this), this);
       mpStackedWidget->addWidget(reactionsWidget1);
     }
   if (!scanWidget)
     {
       scanWidget = new ScanWidget(this);
       mpStackedWidget->addWidget(scanWidget);
     }
   if (!stateWidget)
     {
       stateWidget = new CQSteadyStateResult(this);
       mpStackedWidget->addWidget(stateWidget);
     }
   if (!steadystateWidget)
     {
       steadystateWidget = new SteadyStateWidget(this);
       mpStackedWidget->addWidget(steadystateWidget);
     }
   if (!mpReportsWidget)
     {
       mpReportsWidget = new CQReportsWidget(this);
       mpStackedWidget->addWidget(mpReportsWidget);
     }
   if (!tableDefinition1)
     {
       tableDefinition1 = new CQReportDefinition(this);
       mpStackedWidget->addWidget(tableDefinition1);
     }
   if (!sensWidget)
     {
       sensWidget = new SensitivitiesWidget(this);
       mpStackedWidget->addWidget(sensWidget);
     }
   if (!sensResultWidget)
     {
       sensResultWidget = new CQSensResultWidget(this);
       mpStackedWidget->addWidget(sensResultWidget);
     }
   if (!timeSeriesWidget)
     {
       timeSeriesWidget = new CQTimeSeriesWidget(this);
       mpStackedWidget->addWidget(timeSeriesWidget);
     }
   if (!trajectoryWidget)
     {
       trajectoryWidget = new CQTrajectoryWidget(this);
       mpStackedWidget->addWidget(trajectoryWidget);
     }
   if (!tssaWidget)
     {
       tssaWidget = new CQTSSAWidget(this);
       mpStackedWidget->addWidget(tssaWidget);
     }
   if (!tssaResultWidget)
     {
       tssaResultWidget = new CQTSSAResultWidget(this);
       mpStackedWidget->addWidget(tssaResultWidget);
     }
   if (!crossSectionTimeSeriesWidget)
     {
       crossSectionTimeSeriesWidget = new CQTimeSeriesWidget(this);
       mpStackedWidget->addWidget(crossSectionTimeSeriesWidget);
     }
   if (!crossSectionTaskWidget)
     {
       crossSectionTaskWidget = new CQCrossSectionTaskWidget(this);
       mpStackedWidget->addWidget(crossSectionTaskWidget);
     }
 #ifdef COPASI_NONLIN_DYN_OSCILLATION
   if (!oscillationTaskWidget)
     {
       oscillationTaskWidget = new CQOscillationTaskWidget(this);
       mpStackedWidget->addWidget(oscillationTaskWidget);
     }
 #endif
 #ifdef COPASI_DEBUG
   if (!mpUpdatesWidget)
     {
       mpUpdatesWidget = new CQUpdatesWidget(this);
       mpStackedWidget->addWidget(mpUpdatesWidget);
     }
 #endif // COPASI_DEBUG
   if (!mpMathMatrixWidget)
     {
       mpMathMatrixWidget = new CQMathMatrixWidget(this);
       mpStackedWidget->addWidget(mpMathMatrixWidget);
     }
   if (!mpLayoutsWidget)
     {
       mpLayoutsWidget = new CQLayoutsWidget(this);
       mpStackedWidget->addWidget(mpLayoutsWidget);
     }
 }
CopasiWidget * ListViews::findWidgetFromId (const size_t & id) const
Definition at line 678 of file listviews.cpp.
References crossSectionTaskWidget, crossSectionTimeSeriesWidget, defaultWidget, differentialEquations, eventsWidget, lyapResultWidget, lyapWidget, modelWidget, mpCLNAResultWidget, mpCMCAResultWidget, mpCompartmentsWidget, mpCQLNAWidget, mpCQMCAWidget, mpEFMResultWidget, mpEFMWidget, mpFittingResultWidget, mpFunctionsWidget, mpGlobalQuantitiesWidget, mpLayoutsWidget, mpMathMatrixWidget, mpMoietiesTaskResult, mpMoietiesTaskWidget, mpParameterOverviewWidget, mpParameterSetsWidget, mpPlotsWidget, mpReactionsWidget, mpReportsWidget, mpSpeciesWidget, optimizationWidget, optResultWidget, paramFittingWidget, scanWidget, sensResultWidget, sensWidget, stateWidget, steadystateWidget, timeSeriesWidget, trajectoryWidget, tssaResultWidget, and tssaWidget.
Referenced by findWidgetFromIndex(), CQCrossSectionTaskWidget::init(), SliderDialog::runTask(), CQCrossSectionTaskWidget::taskFinishedEvent(), CQEFMWidget::taskFinishedEvent(), CQLNAWidget::taskFinishedEvent(), CQMCAWidget::taskFinishedEvent(), SensitivitiesWidget::taskFinishedEvent(), SteadyStateWidget::taskFinishedEvent(), CQTSSAWidget::taskFinishedEvent(), and CQTrajectoryWidget::taskFinishedEvent().
 {
   switch (id)
     {
       case static_cast<size_t>(-1):
         break; //continue with parent id
       case 0:
         return defaultWidget;
         break;
       case 1:
         return modelWidget;
         break;
       case 111:
         return mpCompartmentsWidget;
         break;
       case 112:
         return mpSpeciesWidget;
         break;
       case 114:
         return mpReactionsWidget;
         break;
       case 115:
         return mpGlobalQuantitiesWidget;
         break;
       case 116:
         return eventsWidget;
         break;
       case 118:
         return mpParameterOverviewWidget;
         break;
       case 119:
         return mpParameterSetsWidget;
         break;
         //case 122:
         //  return functionSymbols;
         //  break;
 #ifdef HAVE_MML
       case 126:
         return differentialEquations;
         break;
 #endif // HAVE_MML
       case 127:
         return mpMathMatrixWidget;
         break;
 #ifdef COPASI_DEBUG
       case 128:
         return mpUpdatesWidget;
         break;
 #endif
       case 13:
         return mpLayoutsWidget;
         break;
       case 21:
         return steadystateWidget;
         break;
       case 211:
         return stateWidget;
         break;
       case 221:
         return mpEFMWidget;
         break;
       case 2211:
         return mpEFMResultWidget;
         break;
       case 222:
         return mpMoietiesTaskWidget;
         break;
       case 2221:
         return mpMoietiesTaskResult;
         break;
       case 23:
         return trajectoryWidget;
         break;
       case 231:
         return timeSeriesWidget;
         break;
       case 24:
         return mpCQMCAWidget;
         break;
       case 241:
         return mpCMCAResultWidget;
         break;
       case 26:
         return lyapWidget;
         break;
       case 261:
         return lyapResultWidget;
         break;
       case 27:
         return tssaWidget;
         break;
       case 271:
         return tssaResultWidget;
         break;
       case 28:
         return crossSectionTaskWidget;
         break;
       case 281:
         return crossSectionTimeSeriesWidget;
 #ifdef COPASI_NONLIN_DYN_OSCILLATION
       case 29:
         return oscillationTaskWidget;
         break;
 #endif
       case 31:
         return scanWidget;
         break;
       case 32:
         return optimizationWidget;
         break;
       case 321:
         return optResultWidget;
         break;
       case 33:
         return paramFittingWidget;
         break;
       case 331:
         return mpFittingResultWidget;
         break;
       case 34:
         return sensWidget;
         break;
       case 341:
         return sensResultWidget;
         break;
       case 35:
         return mpCQLNAWidget;
         break;
       case 351:
         return mpCLNAResultWidget;
         break;
       case 43:                                         //Report
         return mpReportsWidget;
         break;
       case 42:
         return mpPlotsWidget;
         break;
       case 5:
         return mpFunctionsWidget;
         break;
     }
   return NULL;
 }
CopasiWidget * ListViews::findWidgetFromIndex (const QModelIndex & index) const private
tries to find the right hand side widget that belongs to an item of the tree view
Definition at line 618 of file listviews.cpp.
References C_INVALID_INDEX, compartmentsWidget1, eventWidget1, findWidgetFromId(), functionWidget1, CQBrowserPaneDM::getIdFromIndex(), metabolitesWidget1, mpDataModelGUI, mpModelValueWidget, mpParameterSetWidget, mpPlotSubwidget, mpTreeDM, CQBrowserPaneDM::parent(), reactionsWidget1, and tableDefinition1.
Referenced by slotFolderChanged().
 {
   if (!index.isValid() || !mpDataModelGUI)
     return NULL;
   // first try ID
   size_t id = mpTreeDM->getIdFromIndex(index);
   if (id != C_INVALID_INDEX)
     {
       return findWidgetFromId(id);
     }
   // then try parent id:
   id = mpTreeDM->getIdFromIndex(mpTreeDM->parent(index));
   switch (id)
     {
       case 111:
         return compartmentsWidget1;
         break;
       case 112:
         return metabolitesWidget1;
         break;
       case 114:
         return reactionsWidget1;
         break;
       case 115:
         return mpModelValueWidget;
         break;
       case 116:
         return eventWidget1;
         break;
       case 119:
         return mpParameterSetWidget;
         break;
       case 43:
         return tableDefinition1;
         break;
       case 42:
         return mpPlotSubwidget;
         break;
       case 5:
         return functionWidget1;
         break;
     }
   //give up
   return NULL;
 }
CQCrossSectionTaskWidget * ListViews::getCrossSectionWidget ()
Definition at line 1084 of file listviews.cpp.
References crossSectionTaskWidget.
Referenced by SliderDialog::runCrossSectionTask().
 {
   return crossSectionTaskWidget;
 }
size_t ListViews::getCurrentItemId ()
Definition at line 938 of file listviews.cpp.
References C_INVALID_INDEX, CQBrowserPaneDM::getIdFromIndex(), mpDataModelGUI, mpTreeDM, and mpTreeView.
Referenced by CopasiUI3Window::CopasiUI3Window(), and CopasiUI3Window::listViewsFolderChanged().
 {
   QModelIndex index = mpTreeView->currentIndex();
   if (!index.isValid() || !mpDataModelGUI)
     return C_INVALID_INDEX;
   return mpTreeDM->getIdFromIndex(index);
 }
CopasiWidget * ListViews::getCurrentWidget ()
Definition at line 995 of file listviews.cpp.
References mpCurrentWidget.
Referenced by CopasiUI3Window::newDoc(), CopasiUI3Window::slotCapture(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFontSelection(), CopasiUI3Window::slotImportSBMLFinished(), and CopasiUI3Window::slotImportSBMLFromStringFinished().
 {return this->mpCurrentWidget;}
DataModelGUI* ListViews::getDataModel () inline
Definition at line 134 of file listviews.h.
References mpDataModelGUI.
Referenced by CQReportDefinitionSelect::loadReportDefinitionVector(), and CopasiWidget::protectedNotify().
 {return mpDataModelGUI;};
CQFittingWidget * ListViews::getFittingWidget ()
Definition at line 1074 of file listviews.cpp.
References paramFittingWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runParameterEstimationTask().
 {
   return paramFittingWidget;
 }
CQLNAWidget * ListViews::getLNAWidget ()
Definition at line 1069 of file listviews.cpp.
References mpCQLNAWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runLNATask().
 {
   return mpCQLNAWidget;
 }
CQMCAWidget * ListViews::getMCAWidget ()
Definition at line 1064 of file listviews.cpp.
References mpCQMCAWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runMCATask().
 {
   return mpCQMCAWidget;
 }
CQOptimizationWidget * ListViews::getOptimizationWidget ()
Definition at line 1079 of file listviews.cpp.
References optimizationWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runOptimizationTask().
 {
   return optimizationWidget;
 }
ScanWidget * ListViews::getScanWidget ()
Definition at line 1059 of file listviews.cpp.
References scanWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runScanTask().
 {
   return scanWidget;
 }
SteadyStateWidget * ListViews::getSteadyStateWidget ()
Definition at line 1054 of file listviews.cpp.
References steadystateWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runSteadyStateTask().
 {
   return steadystateWidget;
 }
CQTrajectoryWidget * ListViews::getTrajectoryWidget ()
Definition at line 1049 of file listviews.cpp.
References trajectoryWidget.
Referenced by Worker::getWidgetForTask(), and SliderDialog::runTimeCourse().
 {
   return trajectoryWidget;
 }
void ListViews::notifyChildWidgets (ObjectType objectType, Action action, const std::string & key) private
Definition at line 1004 of file listviews.cpp.
References CopasiWidget::update().
Referenced by slotNotify().
 {
   QList <CopasiWidget *> widgets = findChildren<CopasiWidget *>();
   QListIterator<CopasiWidget *> it(widgets); // iterate over the CopasiWidgets
   CopasiWidget * pCopasiWidget;
   while (it.hasNext())
     {
       if ((pCopasiWidget = it.next()) != NULL)
         {
           pCopasiWidget->update(objectType, action, key);
         }
     }
 }
void ListViews::setDataModel (DataModelGUI * pDM)
Definition at line 267 of file listviews.cpp.
References ConstructNodeWidgets(), CCopasiRootContainer::getDatamodelList(), CQBrowserPaneDM::index(), mpDataModelGUI, mpTreeDM, mpTreeSortDM, mpTreeView, CQBrowserPaneDM::setCopasiDM(), CQBrowserPaneDM::setGuiDM(), and slotNotify().
Referenced by DataModelGUI::deregisterListView(), and DataModelGUI::registerListView().
 {
   //First Disconnect updateCompleteView() and notifyView() from DataModelGUI
   if (mpDataModelGUI)
     {
       disconnect(mpDataModelGUI, SIGNAL(notifyView(ListViews::ObjectType, ListViews::Action, std::string)),
                  this, SLOT(slotNotify(ListViews::ObjectType, ListViews::Action, std::string)));
     }
   mpDataModelGUI = pDM;
   mpTreeDM->setGuiDM(mpDataModelGUI);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   //Set Model for the TableView
   mpTreeDM->setCopasiDM(pDataModel);
   mpTreeView->expand(mpTreeSortDM->mapFromSource(mpTreeDM->index(0, 0, QModelIndex())));
   if (mpDataModelGUI)
     {
       connect(mpDataModelGUI, SIGNAL(notifyView(ListViews::ObjectType, ListViews::Action, const std::string &)),
               this, SLOT(slotNotify(ListViews::ObjectType, ListViews::Action, const std::string &)));
     }
   ConstructNodeWidgets();
 }
void ListViews::setFramework (int framework)
Definition at line 1036 of file listviews.cpp.
References CopasiWidget::setFramework().
 {
   QList <CopasiWidget *> widgets = findChildren<CopasiWidget *>();
   QListIterator<CopasiWidget *> it(widgets); // iterate over the CopasiWidgets
   CopasiWidget * pCopasiWidget;
   while (it.hasNext())
     {
       if ((pCopasiWidget = it.next()) != NULL)
         pCopasiWidget->setFramework(framework);
     }
 }
void ListViews::signalFolderChanged (const QModelIndex & index) signal
Referenced by slotFolderChanged().
void ListViews::slotFolderChanged (const QModelIndex & index) slot
Definition at line 875 of file listviews.cpp.
References defaultWidget, CopasiWidget::enter(), findWidgetFromIndex(), CQBrowserPaneDM::getKeyFromIndex(), CopasiWidget::leave(), mCurrentItemKey, mpCurrentWidget, mpDataModelGUI, mpStackedWidget, mpTreeDM, mpTreeView, and signalFolderChanged().
 {
   bool changeWidget = true;
   if (!index.isValid() || !mpDataModelGUI) return;
   // find the widget
   CopasiWidget* newWidget = findWidgetFromIndex(index);
   if (!newWidget) return; //do nothing
   std::string itemKey = mpTreeDM->getKeyFromIndex(index);
   if (newWidget == mpCurrentWidget)
     if (itemKey == mCurrentItemKey) return; //do nothing
   // leave old widget
   if (mpCurrentWidget)
     {
       //item may point to an invalid ListViewItem now
       QModelIndex newIndex = mpTreeView->currentIndex();
       // find the widget again (it may have changed)
       newWidget = findWidgetFromIndex(newIndex);
       changeWidget = mpCurrentWidget->leave();
       if (!changeWidget) return;
     }
   if (!newWidget) newWidget = defaultWidget; //should never happen
   // enter new widget
   if (newWidget)
     ((CopasiWidget*)newWidget)->enter(itemKey);
   // fall back
   if (!newWidget)
     {newWidget = defaultWidget;}
   // we emit the signal after the old widget has saved
   // the changes
   emit signalFolderChanged(index);
   mpCurrentWidget = newWidget;
   mpStackedWidget->setCurrentWidget(mpCurrentWidget);
   mCurrentItemKey = itemKey;
   mpTreeView->scrollTo(index);
 }
bool ListViews::slotNotify (ListViews::ObjectType objectType, ListViews::Action action, std::string key = "") private slot
Definition at line 952 of file listviews.cpp.
References ADD, DELETE, CQLayoutsWidget::deleteLayoutWindows(), CCopasiRootContainer::getDatamodelList(), MODEL, mpLayoutsWidget, notifyChildWidgets(), STATE, and updateCurrentWidget().
Referenced by setDataModel().
 {
   if (objectType != MODEL &&
       objectType != STATE &&
       action != ADD)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed();
     }
   bool success = true;
   // delete the layout windows when the current model is added
   // actually it would have been better to do this when a model is deleted, but
   // the deletion notification is only sent to the listviews if the deleted
   // model had been changed.
   if (objectType == MODEL && action == DELETE)
     {
       mpLayoutsWidget->deleteLayoutWindows();
     }
   if (!updateCurrentWidget(objectType, action, key)) success = false;
   notifyChildWidgets(objectType, action, key);
   return success;
 }
void ListViews::slotSort (const QModelIndex & index1, const QModelIndex & index2) private slot
Definition at line 980 of file listviews.cpp.
References mpTreeView.
Referenced by ListViews().
 {
   mpTreeView->sortByColumn(0, Qt::AscendingOrder);
 }
void ListViews::switchToOtherWidget (const size_t & id, const std::string & key)
Definition at line 926 of file listviews.cpp.
References CQBrowserPaneDM::index(), mpDataModelGUI, mpTreeDM, mpTreeSortDM, and mpTreeView.
Referenced by CQPlotSubwidget::addPlot(), CQReportDefinition::btnCopyReportClicked(), CQReportDefinition::btnNewReportClicked(), CopasiUI3Window::CopasiUI3Window(), CQSpeciesDetail::copy(), CQCompartment::copy(), ReactionsWidget1::copy(), CQPlotSubwidget::copyPlot(), CQSpeciesDetail::enterProtected(), CQReportDefinition::enterProtected(), CQModelValue::enterProtected(), CQEventWidget1::enterProtected(), FunctionWidget1::enterProtected(), ReactionsWidget1::enterProtected(), CQPlotSubwidget::enterProtected(), Worker::finishedLoading(), CopasiUI3Window::importSBMLFromString(), CopasiUI3Window::newDoc(), CQParameterOverviewWidget::slotBtnCopy(), FunctionWidget1::slotBtnNew(), ReactionsWidget1::slotBtnNew(), CQSpeciesDetail::slotBtnNew(), CQCompartment::slotBtnNew(), CQModelValue::slotBtnNew(), CQEventWidget1::slotBtnNew(), CopasiUI3Window::slotConvertToIrreversible(), CQParameterSetsWidget::slotDoubleClicked(), CQPlotsWidget::slotDoubleClicked(), CQReactionsWidget::slotDoubleClicked(), CQReportsWidget::slotDoubleClicked(), CQEventsWidget::slotDoubleClicked(), CQFunctionsWidget::slotDoubleClicked(), CQCompartmentsWidget::slotDoubleClicked(), CQGlobalQuantitiesWidget::slotDoubleClicked(), CQSpeciesWidget::slotDoubleClicked(), CQReportDefinitionSelect::slotEdit(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotFileOpenFinished(), ReactionsWidget1::slotGotoFunction(), CopasiUI3Window::slotImportSBML(), CopasiUI3Window::slotImportSBMLFinished(), CopasiUI3Window::slotImportSBMLFromStringFinished(), CQCompartment::slotMetaboliteTableCurrentChanged(), ReactionsWidget1::slotNewFunction(), CQSpeciesDetail::slotSwitchToReaction(), CopasiUI3Window::slotUpdateMIRIAMFinished(), CQMoietiesTaskWidget::taskFinishedEvent(), CQEFMWidget::taskFinishedEvent(), CQLyapWidget::taskFinishedEvent(), CQLNAWidget::taskFinishedEvent(), CQMCAWidget::taskFinishedEvent(), SensitivitiesWidget::taskFinishedEvent(), SteadyStateWidget::taskFinishedEvent(), CQTSSAWidget::taskFinishedEvent(), and WizardDialog::textBrowser_anchorClicked().
 {
   if (!mpDataModelGUI) return;
   QModelIndex Index = mpTreeDM->index(id, key);
   QModelIndex SortIndex = mpTreeSortDM->mapFromSource(Index);
   mpTreeView->setCurrentIndex(SortIndex);
 }
bool ListViews::updateCurrentWidget (ObjectType objectType, Action action, const std::string & key = "") private
Definition at line 985 of file listviews.cpp.
References mpCurrentWidget, and CopasiWidget::update().
Referenced by slotNotify().
 {
   bool success = true;
   if (mpCurrentWidget)
     mpCurrentWidget->update(objectType, action, key);
   return success;
 }
void ListViews::updateMIRIAMResourceContents ()
Definition at line 1021 of file listviews.cpp.
 {
   QList <CQMiriamWidget *> widgets = findChildren<CQMiriamWidget *>();
   QListIterator<CQMiriamWidget *> it(widgets); // iterate over the CQMiriamWidgets
   CQMiriamWidget * pWidget;
   while (it.hasNext())
     {
       pWidget = it.next();
       if (dynamic_cast<CQMiriamWidget* >(pWidget))
         dynamic_cast<CQMiriamWidget* >(pWidget)->updateResourcesList();
     }
 }
Friends And Related Function Documentation
friend class CopasiUI3Window friend
Definition at line 104 of file listviews.h.
Member Data Documentation
CQTabWidget* ListViews::compartmentsWidget1 private
Definition at line 198 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQCrossSectionTaskWidget* ListViews::crossSectionTaskWidget private
Definition at line 238 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getCrossSectionWidget().
CQTimeSeriesWidget* ListViews::crossSectionTimeSeriesWidget private
Definition at line 239 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQSplashWidget* ListViews::defaultWidget private
Definition at line 199 of file listviews.h.
Referenced by findWidgetFromId(), ListViews(), and slotFolderChanged().
CQDifferentialEquations* ListViews::differentialEquations private
Definition at line 200 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQEventsWidget* ListViews::eventsWidget private
Definition at line 201 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQTabWidget* ListViews::eventWidget1 private
Definition at line 202 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQTabWidget* ListViews::functionWidget1 private
Definition at line 204 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQLyapResultWidget* ListViews::lyapResultWidget private
Definition at line 206 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQLyapWidget* ListViews::lyapWidget private
Definition at line 205 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
std::string ListViews::mCurrentItemKey private
Definition at line 187 of file listviews.h.
Referenced by ListViews(), and slotFolderChanged().
CQTabWidget* ListViews::metabolitesWidget1 private
Definition at line 208 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQTabWidget* ListViews::modelWidget private
Definition at line 209 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CLNAResultWidget* ListViews::mpCLNAResultWidget private
Definition at line 196 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CMCAResultWidget* ListViews::mpCMCAResultWidget private
Definition at line 193 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQCompartmentsWidget* ListViews::mpCompartmentsWidget private
Definition at line 197 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQLNAWidget* ListViews::mpCQLNAWidget private
Definition at line 195 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getLNAWidget().
CQMCAWidget* ListViews::mpCQMCAWidget private
Definition at line 194 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getMCAWidget().
CopasiWidget* ListViews::mpCurrentWidget private
Definition at line 186 of file listviews.h.
Referenced by commit(), getCurrentWidget(), ListViews(), slotFolderChanged(), and updateCurrentWidget().
DataModelGUI* ListViews::mpDataModelGUI private
Definition at line 182 of file listviews.h.
Referenced by findWidgetFromIndex(), getCurrentItemId(), getDataModel(), setDataModel(), slotFolderChanged(), and switchToOtherWidget().
CQEFMResultWidget* ListViews::mpEFMResultWidget private
Definition at line 213 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQEFMWidget* ListViews::mpEFMWidget private
Definition at line 212 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQFittingResult* ListViews::mpFittingResultWidget private
Definition at line 219 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQFunctionsWidget* ListViews::mpFunctionsWidget private
Definition at line 203 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQGlobalQuantitiesWidget* ListViews::mpGlobalQuantitiesWidget private
Definition at line 210 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQLayoutsWidget* ListViews::mpLayoutsWidget private
Definition at line 249 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), slotNotify(), and ~ListViews().
CQMathMatrixWidget* ListViews::mpMathMatrixWidget private
Definition at line 250 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CMathModel* ListViews::mpMathModel private
Definition at line 185 of file listviews.h.
CQTabWidget* ListViews::mpModelValueWidget private
Definition at line 211 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQMoietiesTaskResult* ListViews::mpMoietiesTaskResult private
Definition at line 214 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQMoietiesTaskWidget* ListViews::mpMoietiesTaskWidget private
Definition at line 215 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQParameterOverviewWidget* ListViews::mpParameterOverviewWidget private
Definition at line 220 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQParameterSetsWidget* ListViews::mpParameterSetsWidget private
Definition at line 221 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQTabWidget* ListViews::mpParameterSetWidget private
Definition at line 222 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQPlotSubwidget* ListViews::mpPlotSubwidget private
Definition at line 224 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQPlotsWidget* ListViews::mpPlotsWidget private
Definition at line 223 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQReactionsWidget* ListViews::mpReactionsWidget private
Definition at line 225 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQReportsWidget* ListViews::mpReportsWidget private
Definition at line 232 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQSpeciesWidget* ListViews::mpSpeciesWidget private
Definition at line 207 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
QStackedWidget* ListViews::mpStackedWidget private
Definition at line 191 of file listviews.h.
Referenced by ConstructNodeWidgets(), ListViews(), and slotFolderChanged().
CQBrowserPaneDM* ListViews::mpTreeDM private
Definition at line 183 of file listviews.h.
Referenced by findWidgetFromIndex(), getCurrentItemId(), ListViews(), setDataModel(), slotFolderChanged(), and switchToOtherWidget().
QSortFilterProxyModel* ListViews::mpTreeSortDM private
Definition at line 184 of file listviews.h.
Referenced by ListViews(), setDataModel(), and switchToOtherWidget().
CQBrowserPane* ListViews::mpTreeView private
Definition at line 190 of file listviews.h.
Referenced by getCurrentItemId(), ListViews(), setDataModel(), slotFolderChanged(), slotSort(), and switchToOtherWidget().
const std::string ListViews::ObjectTypeName static
Initial value:
=
{
  "Species",
  "Compartment",
  "Reaction",
  "Function",
  "Model",
  "State",
  "Report",
  "Plot",
  "Global Quantity",
  "Event",
  "Annotation",
  "Layout",
  "Parameter Overview",
  "Parameter Set",
  ""
}
Definition at line 107 of file listviews.h.
Referenced by CQTabWidget::CQTabWidget(), and CQTabWidget::save().
CQOptimizationWidget* ListViews::optimizationWidget private
Definition at line 216 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getOptimizationWidget().
CQOptimizationResult* ListViews::optResultWidget private
Definition at line 217 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQFittingWidget* ListViews::paramFittingWidget private
Definition at line 218 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getFittingWidget().
CQTabWidget* ListViews::reactionsWidget1 private
Definition at line 226 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
ScanWidget* ListViews::scanWidget private
Definition at line 227 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getScanWidget().
CQSensResultWidget* ListViews::sensResultWidget private
Definition at line 229 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
SensitivitiesWidget* ListViews::sensWidget private
Definition at line 228 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQSteadyStateResult* ListViews::stateWidget private
Definition at line 230 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
SteadyStateWidget* ListViews::steadystateWidget private
Definition at line 231 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getSteadyStateWidget().
CQReportDefinition* ListViews::tableDefinition1 private
Definition at line 233 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromIndex().
CQTimeSeriesWidget* ListViews::timeSeriesWidget private
Definition at line 234 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQTrajectoryWidget* ListViews::trajectoryWidget private
Definition at line 235 of file listviews.h.
Referenced by ConstructNodeWidgets(), findWidgetFromId(), and getTrajectoryWidget().
CQTSSAResultWidget* ListViews::tssaResultWidget private
Definition at line 237 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
CQTSSAWidget* ListViews::tssaWidget private
Definition at line 236 of file listviews.h.
Referenced by ConstructNodeWidgets(), and findWidgetFromId().
The documentation for this class was generated from the following files:
listviews.h
listviews.cpp