COPASI API: CMoiety Class Reference
CMoiety Class Reference
#include <CMoiety.h>
Public Member Functions
void add (C_FLOAT64 value, CMetab *metabolite)
void cleanup ()
CMoiety (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CMoiety (const CMoiety &src, const CCopasiContainer *pParent=NULL)
const C_FLOAT64 & dependentNumber ()
const C_FLOAT64 & getAmount () const
const C_FLOAT64 & getDependentNumber () const
CCopasiObject * getDependentNumberReference () const
std::string getDescription (const CModel *model) const
const std::vector< std::pair
< C_FLOAT64, CMetab * > > & getEquation () const
std::string getExpression () const
CCopasiObject * getInitialValueReference () const
virtual const std::string & getKey () const
C_FLOAT64 getNumber () const
CCopasiObject * getTotalNumberReference () const
CCopasiObject * getValueReference () const
void refreshAmount ()
void refreshDependentNumber ()
void refreshInitialValue ()
void refreshValue ()
virtual bool setObjectParent (const CCopasiContainer *pParent)
~CMoiety ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initConversionFactor ()
void initObjects ()
Private Attributes
std::vector< std::pair
< C_FLOAT64, CMetab * > > mEquation
C_FLOAT64 mIAmount
C_FLOAT64 mINumber
std::string mKey
C_FLOAT64 mNumber
const C_FLOAT64 * mpConversionFactor
CDependentNumberReference * mpDNumberReference
CTotalNumberReference * mpINumberReference
CTotalNumberReference * mpNumberReference
Static Private Attributes
static const C_FLOAT64 DefaultFactor
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 119 of file CMoiety.h.
Constructor & Destructor Documentation
CMoiety::CMoiety (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 36 of file CMoiety.cpp.
References CONSTRUCTOR_TRACE, and initObjects().
                                                   :
   CCopasiContainer(name, pParent, "Moiety"),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Moiety", this)), //By G
   mNumber(0),
   mINumber(0),
   mIAmount(0),
   mEquation(),
   mpINumberReference(NULL),
   mpNumberReference(NULL),
   mpDNumberReference(NULL),
   mpConversionFactor(&CMoiety::DefaultFactor)
 {
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CMoiety::CMoiety (const CMoiety & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CMoiety & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 53 of file CMoiety.cpp.
References CONSTRUCTOR_TRACE, and initObjects().
                                                   :
   CCopasiContainer(src, pParent),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Moiety", this)), //By G
   mNumber(src.mNumber),
   mINumber(src.mINumber),
   mIAmount(src.mIAmount),
   mEquation(src.mEquation),
   mpINumberReference(NULL),
   mpNumberReference(NULL),
   mpDNumberReference(NULL),
   mpConversionFactor(src.mpConversionFactor)
 {
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CMoiety::~CMoiety ()
Destructor
Definition at line 70 of file CMoiety.cpp.
References DESTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
void CMoiety::add (C_FLOAT64 value, CMetab * metabolite)
Add a metabolite to a moiety
Parameters
C_FLOAT64 value
CMetab * metabolite
Definition at line 96 of file CMoiety.cpp.
References CCopasiObject::addDirectDependency(), mEquation, mpINumberReference, CModelEntity::mpIValueReference, mpNumberReference, CModelEntity::mpValueReference, and CMetab::setDependentOn().
Referenced by CModel::buildMoieties().
 {
   if (!mEquation.size())
     pMetabolite->setDependentOn(this);
   else
     addDirectDependency(pMetabolite->mpValueReference);
   mpINumberReference->addDirectDependency(pMetabolite->mpIValueReference);
   mpNumberReference->addDirectDependency(pMetabolite->mpValueReference);
   std::pair<C_FLOAT64, CMetab *> element;
   element.first = value;
   element.second = pMetabolite;
   mEquation.push_back(element);
 }
void CMoiety::cleanup ()
Definition at line 114 of file CMoiety.cpp.
References CCopasiObject::clearDirectDependencies(), mEquation, mpINumberReference, and mpNumberReference.
 {
   clearDirectDependencies();
   mEquation.clear();
   mpINumberReference->clearDirectDependencies();
   mpNumberReference->clearDirectDependencies();
 }
const C_FLOAT64 & CMoiety::dependentNumber ()
Retrieve and refresh the dependent number;
Returns
const C_FLOAT64 & dependentNumber
Definition at line 139 of file CMoiety.cpp.
References mNumber, and refreshDependentNumber().
 {
   refreshDependentNumber();
   return mNumber;
 }
const C_FLOAT64 & CMoiety::getAmount () const
Retrieve the total amount
Returns
const C_FLOAT64 & amount
Definition at line 257 of file CMoiety.cpp.
References mIAmount.
 {
   return mIAmount;
 }
const C_FLOAT64 & CMoiety::getDependentNumber () const
Retrieve the dependent number;
Returns
const C_FLOAT64 & dependentNumber
Definition at line 145 of file CMoiety.cpp.
References mNumber.
Referenced by CMetab::calculate().
 {return mNumber;}
CCopasiObject * CMoiety::getDependentNumberReference () const
Retrieve the object for the dependent particle number
Returns
CCopasiObject * dependentNumberReference
Definition at line 151 of file CMoiety.cpp.
References mpDNumberReference.
Referenced by CMathObject::compileValue(), and CParticleReference::getPrerequisites().
 {return mpDNumberReference;}
std::string CMoiety::getDescription (const CModel * model) const
get the string representation of the moiety using the CMetabNameInterface
Definition at line 164 of file CMoiety.cpp.
References CMetabNameInterface::getDisplayName(), and mEquation.
 {
   std::ostringstream Description;
   Description.imbue(std::locale::classic());
   Description.precision(16);
   std::vector< std::pair< C_FLOAT64, CMetab * > >::const_iterator it = mEquation.begin();
   std::vector< std::pair< C_FLOAT64, CMetab * > >::const_iterator end = mEquation.end();
   for (; it != end; ++it)
     {
       if (it != mEquation.begin())
         {
           if (it->first < 0.0)
             Description << " - ";
           else
             Description << " + ";
         }
       if (fabs(it->first) > 1.0 + 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() ||
           fabs(it->first) < 1.0 - 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon())
         Description << fabs(it->first) << "*";
       Description << CMetabNameInterface::getDisplayName(model, *it->second, false);
     }
   return Description.str();
 }
const std::vector< std::pair< C_FLOAT64, CMetab * > > & CMoiety::getEquation () const
Retrieve the components of the total mass equation
Returns
const std::vector<std::pair< C_FLOAT64, CMetab * > > & equation
Definition at line 267 of file CMoiety.cpp.
References mEquation.
Referenced by CMathObject::compileDependentMass(), CMathObject::compileTotalMass(), and QConservedSpeciesAnimation::getScales().
 {
   return mEquation;
 }
std::string CMoiety::getExpression () const
Retrieve the infix expression, which can be used to calculate the total amount.
Returns
std::string expression
Definition at line 228 of file CMoiety.cpp.
References mEquation.
Referenced by CQMoietiesTaskResult::slotCreateGlobalQuantity().
 {
   std::ostringstream Infix;
   Infix.imbue(std::locale::classic());
   Infix.precision(16);
   std::vector< std::pair< C_FLOAT64, CMetab * > >::const_iterator it = mEquation.begin();
   std::vector< std::pair< C_FLOAT64, CMetab * > >::const_iterator end = mEquation.end();
   for (; it != end; ++it)
     {
       if (it != mEquation.begin())
         {
           if (it->first < 0.0)
             Infix << "-";
           else
             Infix << "+";
         }
       if (fabs(it->first) > 1.0 + 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() ||
           fabs(it->first) < 1.0 - 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon())
         Infix << fabs(it->first) << "*";
       Infix << "<" << it->second->getInitialValueReference()->getCN() << ">";
     }
   return Infix.str();
 }
CCopasiObject * CMoiety::getInitialValueReference () const
Retrieve the object for the total particle number
Returns
CCopasiObject * initialValueReference
Definition at line 206 of file CMoiety.cpp.
References mpINumberReference.
 {return mpINumberReference;}
const std::string & CMoiety::getKey () const virtual
Returns a string with the name of this compartment.
Returns
std::string key
Reimplemented from CCopasiObject.
Definition at line 154 of file CMoiety.cpp.
References mKey.
 {return mKey;} //By G
C_FLOAT64 CMoiety::getNumber () const
Definition at line 209 of file CMoiety.cpp.
References mINumber.
 {
   return mINumber;
 }
CCopasiObject * CMoiety::getTotalNumberReference () const
Retrieve the object for the dependent particle number
Returns
CCopasiObject * totalNumberReference
Definition at line 148 of file CMoiety.cpp.
References mpNumberReference.
Referenced by CMathObject::compileDependentMass().
 {return mpNumberReference;}
CCopasiObject * CMoiety::getValueReference () const
Retrieve the object for the total particle number
Returns
CCopasiObject * valueReference
Definition at line 223 of file CMoiety.cpp.
References mpNumberReference.
 {
   return mpNumberReference;
 }
void CMoiety::initConversionFactor () private
Initialize the number to amount conversion factor
Definition at line 272 of file CMoiety.cpp.
References DefaultFactor, CModel::getNumber2QuantityFactor(), CCopasiObject::getObjectAncestor(), and mpConversionFactor.
Referenced by setObjectParent().
 {
   const CModel * pModel = dynamic_cast< const CModel * >(getObjectAncestor("Model"));
   if (pModel != NULL)
     {
       mpConversionFactor = &pModel->getNumber2QuantityFactor();
     }
   else
     {
       mpConversionFactor = &DefaultFactor;
     }
 }
void CMoiety::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 76 of file CMoiety.cpp.
References CCopasiObject::addDirectDependency(), CCopasiContainer::addObjectReference(), mIAmount, mINumber, mNumber, mpDNumberReference, mpINumberReference, mpNumberReference, refreshAmount(), refreshDependentNumber(), refreshInitialValue(), refreshValue(), CCopasiObject::setRefresh(), and CCopasiObject::ValueDbl.
Referenced by CMoiety().
 {
   setRefresh(this, &CMoiety::refreshDependentNumber);
   mpINumberReference = new CTotalNumberReference("InitialValue", this, mINumber);
   mpINumberReference->setRefresh(this, &CMoiety::refreshInitialValue);
   mpNumberReference = new CTotalNumberReference("Value", this, mNumber);
   mpNumberReference->setRefresh(this, &CMoiety::refreshValue);
   mpDNumberReference = new CDependentNumberReference("DependentValue", this, mNumber);
   mpDNumberReference->addDirectDependency(this);
   CCopasiObject * pObject = addObjectReference("Amount", mIAmount, CCopasiObject::ValueDbl);
   pObject->setRefresh(this, &CMoiety::refreshAmount);
   pObject->addDirectDependency(mpNumberReference);
   return;
 }
void CMoiety::refreshAmount ()
Refresh the total amount
Definition at line 262 of file CMoiety.cpp.
References mIAmount, mINumber, and mpConversionFactor.
Referenced by initObjects().
 {
   mIAmount = mINumber * *mpConversionFactor;
 }
void CMoiety::refreshDependentNumber ()
Refreshes the value of the dependent number
Definition at line 122 of file CMoiety.cpp.
References mEquation, mINumber, and mNumber.
Referenced by dependentNumber(), and initObjects().
 {
   mNumber = mINumber;
   std::vector< std::pair< C_FLOAT64, CMetab * > >::iterator it = mEquation.begin() + 1;
   std::vector< std::pair< C_FLOAT64, CMetab * > >::iterator end = mEquation.end();
   for (; it != end; ++it)
     mNumber -= it->first * it->second->getValue();
   // It is save to update the particle number of the dependent species here.
   // We are mimicking the behavior of the new math container by doing it.
   mEquation.begin()->second->setValue(mNumber);
   return;
 }
void CMoiety::refreshInitialValue ()
Refresh the initial total particle number
Definition at line 193 of file CMoiety.cpp.
References mEquation, and mINumber.
Referenced by initObjects().
 {
   mINumber = 0;
   std::vector< std::pair< C_FLOAT64, CMetab * > >::iterator it = mEquation.begin();
   std::vector< std::pair< C_FLOAT64, CMetab * > >::iterator end = mEquation.end();
   for (; it != end; ++it)
     mINumber += it->first * it->second->getInitialValue();
   return;
 }
void CMoiety::refreshValue ()
Refresh the total particle number
Definition at line 214 of file CMoiety.cpp.
References mEquation, and mINumber.
Referenced by initObjects().
 {
   std::vector< std::pair< C_FLOAT64, CMetab * > >::iterator it = mEquation.begin();
   std::vector< std::pair< C_FLOAT64, CMetab * > >::iterator end = mEquation.end();
   for (; it != end; ++it)
     mINumber += it->first * it->second->getValue();
 }
bool CMoiety::setObjectParent (const CCopasiContainer * pParent) virtual
Sets the parent of the moiety;
Parameters
const CCopasiContainer * pParent
Returns
bool success
Reimplemented from CCopasiObject.
Definition at line 156 of file CMoiety.cpp.
References initConversionFactor(), and CCopasiObject::setObjectParent().
 {
   bool success = CCopasiContainer::setObjectParent(pParent);
   initConversionFactor();
   return success;
 }
Member Data Documentation
const C_FLOAT64 CMoiety::DefaultFactor static private
The default conversion factor used if the moiety is not part of a model
Definition at line 126 of file CMoiety.h.
Referenced by initConversionFactor().
std::vector<std::pair< C_FLOAT64, CMetab * > > CMoiety::mEquation private
Vector of linear dependent CChemEqElement 0..*
Definition at line 153 of file CMoiety.h.
Referenced by add(), cleanup(), getDescription(), getEquation(), getExpression(), refreshDependentNumber(), refreshInitialValue(), and refreshValue().
C_FLOAT64 CMoiety::mIAmount private
The total Amount of the Moiety.
Definition at line 146 of file CMoiety.h.
Referenced by getAmount(), initObjects(), and refreshAmount().
C_FLOAT64 CMoiety::mINumber private
Initial Number of Particles of Moiety.
Definition at line 141 of file CMoiety.h.
Referenced by getNumber(), initObjects(), refreshAmount(), refreshDependentNumber(), refreshInitialValue(), and refreshValue().
std::string CMoiety::mKey private
The key of the moiety
Definition at line 131 of file CMoiety.h.
Referenced by getKey(), and ~CMoiety().
C_FLOAT64 CMoiety::mNumber private
Number of Particles of Moiety.
Definition at line 136 of file CMoiety.h.
Referenced by dependentNumber(), getDependentNumber(), initObjects(), and refreshDependentNumber().
const C_FLOAT64* CMoiety::mpConversionFactor private
A pointer to the conversion factor between the particle number and the amount.
Definition at line 174 of file CMoiety.h.
Referenced by initConversionFactor(), and refreshAmount().
CDependentNumberReference* CMoiety::mpDNumberReference private
A pointer to the object for the dependent particle number
Definition at line 169 of file CMoiety.h.
Referenced by getDependentNumberReference(), and initObjects().
CTotalNumberReference* CMoiety::mpINumberReference private
A pointer to the object for the initial total particle number
Definition at line 158 of file CMoiety.h.
Referenced by add(), cleanup(), getInitialValueReference(), and initObjects().
CTotalNumberReference* CMoiety::mpNumberReference private
A pointer to the object for the total particle number This is used during events
Definition at line 164 of file CMoiety.h.
Referenced by add(), cleanup(), getTotalNumberReference(), getValueReference(), and initObjects().
The documentation for this class was generated from the following files:
CMoiety.h
CMoiety.cpp