COPASI API: CCopasiXMLParser::ListOfModelParameterSetsElement Class Reference
CCopasiXMLParser::ListOfModelParameterSetsElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ListOfModelParameterSetsElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ListOfModelParameterSetsElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { ListOfModelParameterSets = 0, ModelParameterSet }
Private Attributes
std::string mActiveSet
ModelParameterSetElement * mpModelParameterSetElement
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 168 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ListOfModelParameterSetsElement::Element private
Enum of invoked parsers
Enumerator
ListOfModelParameterSets
ModelParameterSet
Definition at line 176 of file CCopasiXMLParser.h.
Constructor & Destructor Documentation
CCopasiXMLParser::ListOfModelParameterSetsElement::ListOfModelParameterSetsElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 19 of file ListOfModelParameterSets.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mActiveSet(),
   mpModelParameterSetElement(NULL)
 {}
CCopasiXMLParser::ListOfModelParameterSetsElement::~ListOfModelParameterSetsElement () virtual
Destructor
Definition at line 27 of file ListOfModelParameterSets.cpp.
References pdelete.
 {
   pdelete(mpModelParameterSetElement);
 }
Member Function Documentation
void CCopasiXMLParser::ListOfModelParameterSetsElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 89 of file ListOfModelParameterSets.cpp.
References CModelParameterSet::assignSetContent(), CCopasiMessage::EXCEPTION, CKeyFactory::get(), CCopasiMessage::getLastMessage(), CModel::getModelParameterSet(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case ListOfModelParameterSets:
         if (strcmp(pszName, "ListOfModelParameterSets"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfModelParameterSets", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         mLastKnownElement = mCurrentElement;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         return;
         break;
       case ModelParameterSet:
         if (strcmp(pszName, "ModelParameterSet"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ModelParameterSet", mParser.getCurrentLineNumber());
         {
           const CModelParameterSet * pModelParameterSet = dynamic_cast< CModelParameterSet * >(mCommon.KeyMap.get(mActiveSet));
           if (pModelParameterSet != NULL)
             {
               size_t Size = CCopasiMessage::size();
               mCommon.pModel->getModelParameterSet().assignSetContent(*pModelParameterSet, false);
               delete pModelParameterSet;
               mActiveSet = "";
               // Remove error messages created by setExpression as this may fail
               // due to incomplete model specification at this time.
               while (CCopasiMessage::size() > Size)
                 CCopasiMessage::getLastMessage();
             }
         }
         mCurrentElement = ListOfModelParameterSets;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   mLastKnownElement = mCurrentElement;
   return;
 }
void CCopasiXMLParser::ListOfModelParameterSetsElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 33 of file ListOfModelParameterSets.cpp.
References CCopasiVector< T >::clear(), CCopasiMessage::EXCEPTION, CModel::getModelParameterSets(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, and UNKNOWN_ELEMENT.
 {
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case ListOfModelParameterSets:
             if (strcmp(pszName, "ListOfModelParameterSets"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "ListOfModelParameterSets", mParser.getCurrentLineNumber());
             mLastKnownElement = ListOfModelParameterSets;
             mCommon.pModel->getModelParameterSets().clear();
             mActiveSet = mParser.getAttributeValue("activeSet", papszAttrs, "");
             return;
           case ModelParameterSet:
             if (!strcmp(pszName, "ModelParameterSet"))
               {
                 /* If we do not have a ModelParameterSet element handler we create one. */
                 if (!mpModelParameterSetElement)
                   mpModelParameterSetElement = new ModelParameterSetElement(mParser, mCommon);
                 mpCurrentHandler = mpModelParameterSetElement;
               }
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
 }
Member Data Documentation
std::string CCopasiXMLParser::ListOfModelParameterSetsElement::mActiveSet private
The key of the active parameter set
Definition at line 213 of file CCopasiXMLParser.h.
ModelParameterSetElement* CCopasiXMLParser::ListOfModelParameterSetsElement::mpModelParameterSetElement private
A pointer to the ModelParameterSet element handler
Definition at line 218 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
ListOfModelParameterSets.cpp