COPASI API: CQPreferenceDialog Class Reference
CQPreferenceDialog Class Reference
#include <CQPreferenceDialog.h>
Public Member Functions
CQPreferenceDialog (QWidget *parent=0, const char *name=0, bool modal=false, Qt::WindowFlags fl=0)
~CQPreferenceDialog ()
Private Slots
virtual void slotBtnCancel ()
virtual void slotBtnOk ()
virtual void slotItemDoubleClicked (QTreeWidgetItem *, int)
Private Member Functions
void init ()
Detailed Description
Definition at line 24 of file CQPreferenceDialog.h.
Constructor & Destructor Documentation
CQPreferenceDialog::CQPreferenceDialog (QWidget * parent = 0, const char * name = 0, bool modal = false, Qt::WindowFlags fl = 0)
Definition at line 32 of file CQPreferenceDialog.cpp.
References init().
   : QDialog(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   setupUi(this);
   init();
 }
CQPreferenceDialog::~CQPreferenceDialog ()
Definition at line 45 of file CQPreferenceDialog.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQPreferenceDialog::init () private
Definition at line 50 of file CQPreferenceDialog.cpp.
References COL_NAME, COL_VALUE, FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiParameterGroup::getParameter(), CConfigurationFile::getRecentFiles(), CConfigurationFile::getRecentSBMLFiles(), CCopasiParameter::getValue(), CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pSTRING, and CCopasiParameter::Value::pUINT.
Referenced by CQPreferenceDialog().
 {
   mpTreeWidget->setColumnWidth(COL_NAME, 150);
   mpTreeWidget->setColumnWidth(COL_VALUE, 100);
   CConfigurationFile * configFile = CCopasiRootContainer::getConfiguration();
   CCopasiParameter * pParameter = configFile->getRecentFiles().getParameter("MaxFiles");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Max Last Visited Files");
       Values.append(QString::number(*pParameter->getValue().pUINT));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getRecentSBMLFiles().getParameter("MaxFiles");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Max Last Visited SBML Files");
       Values.append(QString::number(*pParameter->getValue().pUINT));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getParameter("Application for opening URLs");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Application for opening URLs");
       Values.append(FROM_UTF8(*pParameter->getValue().pSTRING));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getParameter("Validate Units");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Validate Units");
       Values.append((*pParameter->getValue().pBOOL ? "YES" : "NO"));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getParameter("Use OpenGL");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Use OpenGL");
       Values.append((*pParameter->getValue().pBOOL ? "YES" : "NO"));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getParameter("Use Advanced Sliders");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Use Advanced Sliders");
       Values.append((*pParameter->getValue().pBOOL ? "YES" : "NO"));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getParameter("Use Advanced Editing");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Use Advanced Editing");
       Values.append((*pParameter->getValue().pBOOL ? "YES" : "NO"));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
   pParameter = configFile->getParameter("Normalize Weights per Experiment");
   if (pParameter != NULL)
     {
       QStringList Values;
       Values.append("Normalize Weights per Experiment");
       Values.append((*pParameter->getValue().pBOOL ? "YES" : "NO"));
       new QTreeWidgetItem(mpTreeWidget, Values);
     }
 }
void CQPreferenceDialog::slotBtnCancel () private virtual slot
Definition at line 251 of file CQPreferenceDialog.cpp.
 {
   done(0);
 }
void CQPreferenceDialog::slotBtnOk () private virtual slot
Definition at line 141 of file CQPreferenceDialog.cpp.
References C_INT32, COL_VALUE, CQMessageBox::critical(), FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiParameterGroup::getParameter(), CConfigurationFile::getRecentFiles(), CConfigurationFile::getRecentSBMLFiles(), CCopasiParameter::getValue(), CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUINT, CCopasiParameter::setValue(), and TO_UTF8.
 {
   // We need to commit the changes
   unsigned C_INT32 newMaxFiles = 0;
   CConfigurationFile * configFile = CCopasiRootContainer::getConfiguration();
   QList< QTreeWidgetItem *> Items = mpTreeWidget->findItems("Max Last Visited Files", 0, 0);
   CCopasiParameter * pParameter = configFile->getRecentFiles().getParameter("MaxFiles");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       newMaxFiles = Items[0]->text(COL_VALUE).toUInt();
       unsigned C_INT32 maxFiles = *pParameter->getValue().pUINT;
       if (newMaxFiles > 0 && newMaxFiles <= 20)
         pParameter->setValue(newMaxFiles);
       else
         {
           CQMessageBox::critical(this, "Incorrect Setting",
                                  "Max Last Visited Files should be a number between 1 and 20.",
                                  QMessageBox::Ok, QMessageBox::Ok);
           Items[0]->setText(COL_VALUE, QString::number(maxFiles));
           return;
         }
     }
   Items = mpTreeWidget->findItems("Max Last Visited SBML Files", 0, 0);
   pParameter = configFile->getRecentSBMLFiles().getParameter("MaxFiles");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       newMaxFiles = Items[0]->text(COL_VALUE).toUInt();
       unsigned C_INT32 maxFiles = *pParameter->getValue().pUINT;
       if (newMaxFiles > 0 && newMaxFiles <= 20)
         pParameter->setValue(newMaxFiles);
       else
         {
           CQMessageBox::critical(this, "Incorrect Setting", "Max Last Visited SBML Files should be a number between 1 and 20.",
                                  QMessageBox::Ok, QMessageBox::Ok);
           Items[0]->setText(COL_VALUE, QString::number(maxFiles));
           return;
         }
     }
   Items = mpTreeWidget->findItems("Application for opening URLs", 0, 0);
   pParameter = configFile->getParameter("Application for opening URLs");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       if (Items[0]->text(COL_VALUE) != FROM_UTF8(*pParameter->getValue().pSTRING))
         pParameter->setValue(std::string(TO_UTF8(Items[0]->text(COL_VALUE))));
     }
   Items = mpTreeWidget->findItems("Validate Units", 0, 0);
   pParameter = configFile->getParameter("Validate Units");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       pParameter->setValue(Items[0]->text(COL_VALUE).toUpper() == "YES");
     }
   Items = mpTreeWidget->findItems("Use OpenGL", 0, 0);
   pParameter = configFile->getParameter("Use OpenGL");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       pParameter->setValue(Items[0]->text(COL_VALUE).toUpper() == "YES");
     }
   Items = mpTreeWidget->findItems("Use Advanced Sliders", 0, 0);
   pParameter = configFile->getParameter("Use Advanced Sliders");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       pParameter->setValue(Items[0]->text(COL_VALUE).toUpper() == "YES");
     }
   Items = mpTreeWidget->findItems("Use Advanced Editing", 0, 0);
   pParameter = configFile->getParameter("Use Advanced Editing");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       pParameter->setValue(Items[0]->text(COL_VALUE).toUpper() == "YES");
     }
   Items = mpTreeWidget->findItems("Normalize Weights per Experiment", 0, 0);
   pParameter = configFile->getParameter("Normalize Weights per Experiment");
   if (Items.size() > 0 &&
       pParameter != NULL)
     {
       pParameter->setValue(Items[0]->text(COL_VALUE).toUpper() == "YES");
     }
   done(1);
 }
void CQPreferenceDialog::slotItemDoubleClicked (QTreeWidgetItem * pItem, int column) private virtual slot
Definition at line 257 of file CQPreferenceDialog.cpp.
References COL_VALUE.
 {
   if (column == COL_VALUE)
     {
       Qt::ItemFlags Flags = pItem->flags();
       pItem->setFlags(Flags | Qt::ItemIsEditable);
       mpTreeWidget->editItem(pItem, column);
       pItem->setFlags(Flags);
     }
 }
The documentation for this class was generated from the following files:
CQPreferenceDialog.h
CQPreferenceDialog.cpp