COPASI API: CQAnimationWindow Class Reference
CQAnimationWindow Class Reference
#include <CQAnimationWindow.h>
Public Slots
void slotAutoLayout ()
Slots the auto layout.
void slotEditSettings ()
void slotExportImage ()
void slotLayoutStateChanged (QSharedPointer< CLayoutState > state)
void slotRandomizeLayout ()
void slotShowStep (int)
void slotStopLayout ()
void slotSwitchAnimation ()
Public Member Functions
CQAnimationWindow (CLayout *layout, CCopasiDataModel *dataModel=NULL)
CQAnimationWindow ()
virtual QMenu * getWindowMenu () const
void setAnimation (CQCopasiAnimation *animation, CCopasiDataModel *dataModel)
void setScene (CQLayoutScene *scene, CCopasiDataModel *dataModel)
virtual ~CQAnimationWindow ()
Public Member Functions inherited from CWindowInterface
void addToMainWindow (CopasiUI3Window *window=NULL)
CWindowInterface (QWidget *parent=NULL, Qt::WindowFlags flags=NULL)
void removeFromMainWindow (CopasiUI3Window *window=NULL)
virtual void saveToFile (const QString &fileName) const
virtual ~CWindowInterface ()
Protected Member Functions
virtual void closeEvent (QCloseEvent *closeEvent)
Protected Attributes
CQCopasiAnimation * mAnimation
CLayout * mpCopy
CQLayoutThread * mpLayoutThread
CCopasiDataModel * mpModel
CQLayoutScene * mpScene
QMenu * mpWindowMenu
Private Member Functions
void init ()
void toggleUI (bool isPlaying)
Detailed Description
Definition at line 25 of file CQAnimationWindow.h.
Constructor & Destructor Documentation
CQAnimationWindow::CQAnimationWindow (CLayout * layout, CCopasiDataModel * dataModel = NULL)
Definition at line 263 of file CQAnimationWindow.cpp.
References init(), and setScene().
   : mpScene(NULL)
   , mpModel(NULL)
   , mpWindowMenu(NULL)
   , mAnimation(NULL)
   , mpLayoutThread(NULL)
   , mpCopy(NULL)
 {
   init();
   setScene(new CQLayoutScene(layout, dataModel), dataModel);
 }
CQAnimationWindow::CQAnimationWindow ()
Definition at line 275 of file CQAnimationWindow.cpp.
References init().
   : mpScene(NULL)
   , mpModel(NULL)
   , mpWindowMenu(NULL)
   , mAnimation(NULL)
   , mpLayoutThread(NULL)
   , mpCopy(NULL)
 {
   init();
 }
CQAnimationWindow::~CQAnimationWindow () virtual
Definition at line 331 of file CQAnimationWindow.cpp.
References mAnimation, mpCopy, mpLayoutThread, mpScene, pdelete, CWindowInterface::removeFromMainWindow(), and CQLayoutThread::terminateLayout().
 {
   mpLayoutThread->terminateLayout();
   if (mpCopy != NULL)
     {
       delete mpCopy;
       mpCopy = NULL;
     }
   if (mAnimation != NULL)
     {
       delete mAnimation;
       mAnimation = NULL;
     }
   removeFromMainWindow();
   pdelete(mpScene);
   pdelete(mpLayoutThread);
 }
Member Function Documentation
void CQAnimationWindow::closeEvent (QCloseEvent * closeEvent) protected virtual
Definition at line 431 of file CQAnimationWindow.cpp.
References mpLayoutThread, and CQLayoutThread::stopLayout().
 {
   // stop the autolayout
   mpLayoutThread->stopLayout();
 }
QMenu * CQAnimationWindow::getWindowMenu () const virtual
Implements CWindowInterface.
Definition at line 390 of file CQAnimationWindow.cpp.
References mpWindowMenu.
 {
   return mpWindowMenu;
 }
void CQAnimationWindow::init () private
Definition at line 286 of file CQAnimationWindow.cpp.
References CQIconResource::copasi, CQIconResource::fileExport, CQLayoutThread::getParameterWindow(), CQIconResource::icon(), mpLayoutThread, mpWindowMenu, CQIconResource::play, CQIconResource::roll, slotLayoutStateChanged(), slotStopLayout(), and toggleUI().
Referenced by CQAnimationWindow().
 {
   setupUi(this);
   setWindowIcon(CQIconResource::icon(CQIconResource::copasi));
   setUnifiedTitleAndToolBarOnMac(true);
   actionAuto_Layout->setIcon(CQIconResource::icon(CQIconResource::play));
   actionRandomize_Layout->setIcon(CQIconResource::icon(CQIconResource::roll));
   actionExport->setIcon(CQIconResource::icon(CQIconResource::fileExport));
   QMenu* viewMenu = menuBar()->addMenu(tr("&View"));
   graphicsView->fillZoomMenu(viewMenu);
   QToolBar* actionToolbar = this->addToolBar("Actions");
   actionToolbar->addAction(actionExport);
   actionToolbar->addAction(actionAuto_Layout);
   actionToolbar->addAction(actionRandomize_Layout);
   QToolBar* selectToolbar = this->addToolBar("Select");
   graphicsView->fillSelectionToolBar(selectToolbar);
   QToolBar* viewToolBar = this->addToolBar("View");
   graphicsView->fillZoomTooBar(viewToolBar);
   mpWindowMenu = menuBar()->addMenu(tr("&Window"));
   mpLayoutThread = new CQLayoutThread(this);
   connect(mpLayoutThread, SIGNAL(layoutFinished()), this, SLOT(slotStopLayout()));
   connect(mpLayoutThread, SIGNAL(layoutStateChanged(QSharedPointer<CLayoutState>)), this, SLOT(slotLayoutStateChanged(QSharedPointer<CLayoutState>)));
   QDockWidget* pParameterWindow = mpLayoutThread->getParameterWindow();
   addDockWidget(Qt::LeftDockWidgetArea, pParameterWindow);
   viewMenu->addSeparator();
   viewMenu->addAction(pParameterWindow->toggleViewAction());
   toggleUI(false);
 }
void CQAnimationWindow::setAnimation (CQCopasiAnimation * animation, CCopasiDataModel * dataModel)
Definition at line 395 of file CQAnimationWindow.cpp.
References CQCopasiAnimation::getNumSteps(), CQCopasiAnimation::initialize(), mAnimation, mpScene, CQCopasiAnimation::removeFromScene(), and slotShowStep().
Referenced by setScene(), and slotSwitchAnimation().
 {
   if (mAnimation != NULL)
     {
       mAnimation->removeFromScene(*mpScene);
       delete mAnimation;
     }
   mAnimation = animation;
   mAnimation->initialize(*dataModel);
   size_t numSteps = mAnimation->getNumSteps();
   if (numSteps > 0)
     {
       mpControls->setVisible(true);
       mpControls->setNumSteps(numSteps);
       slotShowStep(0);
     }
   else
     {
       mpControls->setVisible(false);
       statusBar()->showMessage("No data for the animation! Run task first, and load data.", 1000);
     }
 }
void CQAnimationWindow::setScene (CQLayoutScene * scene, CCopasiDataModel * dataModel)
Definition at line 353 of file CQAnimationWindow.cpp.
References CQLayoutScene::getCurrentLayout(), mpModel, mpScene, pdelete, CQLayoutScene::recreate(), and setAnimation().
Referenced by CQAnimationWindow().
 {
   mpModel = dataModel;
   if (mpScene != NULL && mpScene != scene)
     pdelete(mpScene);
   mpScene = scene;
   this->graphicsView->setScene(mpScene);
   mpScene->recreate();
   graphicsView->setDataModel(dataModel, scene->getCurrentLayout());
   this->graphicsView->invalidateScene();
   //setAnimation(new QConservedSpeciesAnimation(), dataModel);
   //setAnimation(new QFluxModeAnimation(), dataModel);
   setAnimation(new QTimeCourseAnimation(), dataModel);
 }
void CQAnimationWindow::slotAutoLayout () slot
Slots the auto layout.
Definition at line 500 of file CQAnimationWindow.cpp.
References CQLayoutThread::createSpringLayout(), CQLayoutScene::getCurrentLayout(), mpCopy, mpLayoutThread, mpScene, CQLayoutThread::stopLayout(), CLayoutState::tagLayout(), and toggleUI().
Referenced by CQLayoutsWidget::slotBtnNewClicked().
 {
   if (sender() != NULL && !actionAuto_Layout->isChecked())
     {
       mpLayoutThread->stopLayout();
       return;
     }
   toggleUI(true);
   // work on a copy!
   CLayoutState::tagLayout(mpScene->getCurrentLayout());
   if (mpCopy != NULL)
     {
       delete mpCopy;
       mpCopy = NULL;
     }
   mpCopy = new CLayout(*mpScene->getCurrentLayout());
   mpLayoutThread->createSpringLayout(mpCopy, 100000);
 }
void CQAnimationWindow::slotEditSettings () slot
Definition at line 437 of file CQAnimationWindow.cpp.
References CQAnimationSettingsEditor::initFrom(), mAnimation, and CQAnimationSettingsEditor::saveTo().
 {
   CQAnimationSettingsEditor editor;
   editor.initFrom(mAnimation);
   if (editor.exec() == QDialog::Accepted)
     {
       editor.saveTo(mAnimation);
     }
 }
void CQAnimationWindow::slotExportImage () slot
Definition at line 323 of file CQAnimationWindow.cpp.
 {
   QString fileName = QFileDialog::getSaveFileName(this, tr("Export Image"),
                      "",
                      tr("PDF files (*.pdf);;Images (*.png *.xpm *.jpg);;All files (*.*)"));
   graphicsView->slotSaveToFile(fileName);
 }
void CQAnimationWindow::slotLayoutStateChanged (QSharedPointer< CLayoutState > state) slot
Definition at line 477 of file CQAnimationWindow.cpp.
References CQLayoutScene::getCurrentLayout(), mpScene, and CQLayoutScene::recreate().
Referenced by init().
 {
   state->applyTo(mpScene->getCurrentLayout());
   mpScene->recreate();
 }
void CQAnimationWindow::slotRandomizeLayout () slot
Definition at line 448 of file CQAnimationWindow.cpp.
References CQLayoutScene::getCurrentLayout(), mpLayoutThread, mpScene, CQLayoutThread::randomizeLayout(), CQLayoutThread::stopLayout(), and CLayoutState::tagLayout().
 {
   mpLayoutThread->stopLayout();
   mpLayoutThread->wait();
   CLayoutState::tagLayout(mpScene->getCurrentLayout());
   mpLayoutThread->randomizeLayout(mpScene->getCurrentLayout());
 }
void CQAnimationWindow::slotShowStep (int step) slot
Definition at line 420 of file CQAnimationWindow.cpp.
References CQCopasiAnimation::applyToScene(), CQCopasiAnimation::getNumSteps(), mAnimation, and mpScene.
Referenced by setAnimation().
 {
   statusBar()->showMessage(QString("Displaying step %1").arg(step + 1), 1000);
   if (mAnimation == NULL) return;
   mAnimation->applyToScene(*mpScene, step);
   mpControls->setNumSteps(mAnimation->getNumSteps());
   mpScene->update();
 }
void CQAnimationWindow::slotStopLayout () slot
Definition at line 464 of file CQAnimationWindow.cpp.
References CQIconResource::icon(), mpCopy, and CQIconResource::play.
Referenced by init().
 {
   if (mpCopy != NULL)
     {
       delete mpCopy;
       mpCopy = NULL;
     }
   actionAuto_Layout->setChecked(false);
   actionAuto_Layout->setText("Run Auto Layout");
   actionAuto_Layout->setIcon(CQIconResource::icon(CQIconResource::play));
 }
void CQAnimationWindow::slotSwitchAnimation () slot
Definition at line 370 of file CQAnimationWindow.cpp.
References setAnimation().
 {
   QAction *action = dynamic_cast<QAction *>(sender());
   if (action == NULL) return;
   if (action->text() == "View Time Course")
     {
       setAnimation(new QTimeCourseAnimation(), graphicsView->getDataModel());
     }
   else if (action->text() == "View Elementary Modes")
     {
       setAnimation(new QFluxModeAnimation(), graphicsView->getDataModel());
     }
   else if (action->text() == "View Conserved Species")
     {
       setAnimation(new QConservedSpeciesAnimation(), graphicsView->getDataModel());
     }
 }
void CQAnimationWindow::toggleUI (bool isPlaying) private
Definition at line 483 of file CQAnimationWindow.cpp.
References CQIconResource::icon(), mpLayoutThread, CQIconResource::pause, and CQLayoutThread::stopLayout().
Referenced by init(), and slotAutoLayout().
 {
   if (isPlaying)
     {
       actionAuto_Layout->setChecked(true);
       actionAuto_Layout->setText("Stop Auto Layout");
       actionAuto_Layout->setIcon(CQIconResource::icon(CQIconResource::pause));
     }
   else
     {
       mpLayoutThread->stopLayout();
     }
 }
Member Data Documentation
CQCopasiAnimation* CQAnimationWindow::mAnimation protected
Definition at line 53 of file CQAnimationWindow.h.
Referenced by setAnimation(), slotEditSettings(), slotShowStep(), and ~CQAnimationWindow().
CLayout* CQAnimationWindow::mpCopy protected
Definition at line 55 of file CQAnimationWindow.h.
Referenced by slotAutoLayout(), slotStopLayout(), and ~CQAnimationWindow().
CQLayoutThread* CQAnimationWindow::mpLayoutThread protected
Definition at line 54 of file CQAnimationWindow.h.
Referenced by closeEvent(), init(), slotAutoLayout(), slotRandomizeLayout(), toggleUI(), and ~CQAnimationWindow().
CCopasiDataModel* CQAnimationWindow::mpModel protected
Definition at line 51 of file CQAnimationWindow.h.
Referenced by setScene().
CQLayoutScene* CQAnimationWindow::mpScene protected
Definition at line 50 of file CQAnimationWindow.h.
Referenced by setAnimation(), setScene(), slotAutoLayout(), slotLayoutStateChanged(), slotRandomizeLayout(), slotShowStep(), and ~CQAnimationWindow().
QMenu* CQAnimationWindow::mpWindowMenu protected
Definition at line 52 of file CQAnimationWindow.h.
Referenced by getWindowMenu(), and init().
The documentation for this class was generated from the following files:
CQAnimationWindow.h
CQAnimationWindow.cpp