COPASI API: Copasi2SBMLTranslator Class Reference
Copasi2SBMLTranslator Class Reference
#include <SBWTranslator.h>
Public Member Functions
Copasi2SBMLTranslator ()
virtual ~Copasi2SBMLTranslator ()
Static Public Member Functions
static void registerMethods (SystemsBiologyWorkbench::MethodTable< Copasi2SBMLTranslator > &table)
static std::string translate (const std::string &sbmlString)
static std::string translateFileToSBML (const std::string &fileName)
static std::string translateToSBML (const std::string &copasiString)
Protected Member Functions
SystemsBiologyWorkbench::DataBlockWriter getAuthor (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getCopyright (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getDescription (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getFileExtension (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getFileType (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getName (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getURL (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter getVersion (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter translate (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter translateFileToSBML (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
SystemsBiologyWorkbench::DataBlockWriter translateToSBML (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader)
Static Private Attributes
static int mLevel = 3
static int mVersion = 1
Detailed Description
Definition at line 16 of file SBWTranslator.h.
Constructor & Destructor Documentation
Copasi2SBMLTranslator::Copasi2SBMLTranslator ()
Definition at line 35 of file SBWTranslator.cpp.
 {
 }
Copasi2SBMLTranslator::~Copasi2SBMLTranslator () virtual
Definition at line 38 of file SBWTranslator.cpp.
 {
 }
Member Function Documentation
DataBlockWriter Copasi2SBMLTranslator::getAuthor (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 110 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string author("Frank T. Bergmann");
   return DataBlockWriter() << author;
 }
DataBlockWriter Copasi2SBMLTranslator::getCopyright (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 120 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string copy("(c) 2012 COPASI Team");
   return DataBlockWriter() << copy;
 }
DataBlockWriter Copasi2SBMLTranslator::getDescription (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 115 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string description("This converter converts a COPASI model to an SBML file");
   return DataBlockWriter();
 }
DataBlockWriter Copasi2SBMLTranslator::getFileExtension (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 130 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string extension(".cps");
   return DataBlockWriter() << extension;
 }
DataBlockWriter Copasi2SBMLTranslator::getFileType (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 135 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string fileType("COPASI file");
   return DataBlockWriter() << fileType;
 }
DataBlockWriter Copasi2SBMLTranslator::getName (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 98 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string name("Copasi2SBML Translator");
   return DataBlockWriter();
 }
DataBlockWriter Copasi2SBMLTranslator::getURL (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 125 of file SBWTranslator.cpp.
Referenced by registerMethods().
 {
   static string url("http://copasi.org");
   return DataBlockWriter() << url;
 }
DataBlockWriter Copasi2SBMLTranslator::getVersion (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Definition at line 104 of file SBWTranslator.cpp.
References CVersion::VERSION.
Referenced by registerMethods().
 {
   static string version(CVersion::VERSION.getVersion());
   return DataBlockWriter() << version;
 }
void Copasi2SBMLTranslator::registerMethods (SystemsBiologyWorkbench::MethodTable< Copasi2SBMLTranslator > & table) static
Definition at line 42 of file SBWTranslator.cpp.
References getAuthor(), getCopyright(), getDescription(), getFileExtension(), getFileType(), getName(), getURL(), getVersion(), translate(), translateFileToSBML(), and translateToSBML().
 {
   table.addMethod(&Copasi2SBMLTranslator::getName,            "string getName()", false, "Return the name of this importer");
   table.addMethod(&Copasi2SBMLTranslator::getVersion,         "string getVersion()", false, "Return the version of this importer");
   table.addMethod(&Copasi2SBMLTranslator::getAuthor,          "string getAuthor()", false, "Return the corresponding author for this importer");
   table.addMethod(&Copasi2SBMLTranslator::getDescription,       "string getDescription()", false, "Return a description for this importer");
   table.addMethod(&Copasi2SBMLTranslator::getName,        "string getDisplayName()", false, "Return the display name for this importer.");
   table.addMethod(&Copasi2SBMLTranslator::getCopyright,       "string getCopyright()", false, "Return the copyright for this importer");
   table.addMethod(&Copasi2SBMLTranslator::getURL,           "string getURL()", false, "Return a URL for this reporter.");
   table.addMethod(&Copasi2SBMLTranslator::getFileExtension,            "string getFileExtension()", false, "Returns the file extension as a string");
   table.addMethod(&Copasi2SBMLTranslator::getFileType,                 "string getFileType()", false, "Returns a string describing the type of file");
   table.addMethod(&Copasi2SBMLTranslator::translate,          "string translate(string)", false, "Translate SBML string to COPASI.");
   table.addMethod(&Copasi2SBMLTranslator::translateToSBML,          "string translateToSBML(string)", false, "Translate COPASI string to SBML.");
   table.addMethod(&Copasi2SBMLTranslator::translateFileToSBML,          "string translateFileToSBML(string)", false, "Translate COPASI string to SBML.");
 }
std::string Copasi2SBMLTranslator::translate (const std::string & sbmlString) static
Definition at line 67 of file SBWTranslator.cpp.
References CCopasiRootContainer::addDatamodel(), CDirEntry::fileName(), COptions::getValue(), CCopasiDataModel::importSBMLFromString(), CCopasiRootContainer::init(), CDirEntry::makePathAbsolute(), CDirEntry::remove(), and CCopasiDataModel::saveModel().
Referenced by registerMethods().
 {
   CCopasiRootContainer::init(0, NULL);
   CCopasiDataModel* pDataModel = CCopasiRootContainer::addDatamodel();
   pDataModel->importSBMLFromString(sbmlString);
   string tempDir;
   COptions::getValue("Tmp", tempDir);
   string tempFile = "tmp.cps";
   CDirEntry::makePathAbsolute(tempFile, tempDir);
   tempFile = CDirEntry::fileName(tempFile);
   pDataModel->saveModel(tempFile, NULL, true);
   std::ifstream ifs(tempFile.c_str());
   std::string str((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
   ifs.close();
   CDirEntry::remove(tempFile);
   return str;
 }
SystemsBiologyWorkbench::DataBlockWriter Copasi2SBMLTranslator::translate (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
std::string Copasi2SBMLTranslator::translateFileToSBML (const std::string & fileName) static
Definition at line 58 of file SBWTranslator.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiDataModel::exportSBMLToString(), CCopasiRootContainer::init(), and CCopasiDataModel::loadModel().
Referenced by main(), and registerMethods().
 {
   CCopasiRootContainer::init(0, NULL);
   CCopasiDataModel* pDataModel = CCopasiRootContainer::addDatamodel();
   pDataModel->loadModel(fileName, NULL);
   string sbml = pDataModel->exportSBMLToString(NULL, mLevel, mVersion);
   return sbml;
 }
SystemsBiologyWorkbench::DataBlockWriter Copasi2SBMLTranslator::translateFileToSBML (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
std::string Copasi2SBMLTranslator::translateToSBML (const std::string & copasiString) static
Definition at line 86 of file SBWTranslator.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiDataModel::exportSBMLToString(), COptions::getPWD(), CCopasiRootContainer::init(), and CCopasiDataModel::loadModel().
Referenced by registerMethods().
 {
   CCopasiRootContainer::init(0, NULL);
   CCopasiDataModel* pDataModel = CCopasiRootContainer::addDatamodel();
   istringstream str(copasiString);
   pDataModel->loadModel(str, COptions::getPWD(), NULL);
   string sbml = pDataModel->exportSBMLToString(NULL, mLevel, mVersion);
   return sbml;
 }
SystemsBiologyWorkbench::DataBlockWriter Copasi2SBMLTranslator::translateToSBML (SystemsBiologyWorkbench::Module from, SystemsBiologyWorkbench::DataBlockReader reader) protected
Member Data Documentation
int Copasi2SBMLTranslator::mLevel = 3 static private
Definition at line 44 of file SBWTranslator.h.
int Copasi2SBMLTranslator::mVersion = 1 static private
Definition at line 45 of file SBWTranslator.h.
The documentation for this class was generated from the following files:
SBWTranslator.h
SBWTranslator.cpp