COPASI API: compareGraphicalObjectsBySize Class Reference
compareGraphicalObjectsBySize Class Reference
#include <utility_classes.h>
Public Member Functions
bool operator() (const CLGraphicalObject *pObject1, const CLGraphicalObject *pObject2) const
Detailed Description
Definition at line 87 of file utility_classes.h.
Member Function Documentation
bool compareGraphicalObjectsBySize::operator() (const CLGraphicalObject * pObject1, const CLGraphicalObject * pObject2) const
Definition at line 109 of file utility_classes.cpp.
References CLGraphicalObject::getBoundingBox(), CLGlyphWithCurve::getCurve(), CLBoundingBox::getDimensions(), CLDimensions::getHeight(), CLCurve::getNumCurveSegments(), and CLDimensions::getWidth().
 {
   const CLReactionGlyph* pRG1 = dynamic_cast<const CLReactionGlyph*>(pObject1);
   const CLReactionGlyph* pRG2 = dynamic_cast<const CLReactionGlyph*>(pObject2);
   const CLMetabReferenceGlyph* pSRG1 = dynamic_cast<const CLMetabReferenceGlyph*>(pObject1);
   const CLMetabReferenceGlyph* pSRG2 = dynamic_cast<const CLMetabReferenceGlyph*>(pObject2);
   bool result = false;
   if (!(((pRG1 && pRG1->getCurve().getNumCurveSegments() != 0) || (pSRG1 && pSRG1->getCurve().getNumCurveSegments() != 0)) && ((pRG2 && pRG2->getCurve().getNumCurveSegments() != 0) || (pSRG2 && pSRG2->getCurve().getNumCurveSegments() != 0))))
     {
       result = ((pObject1->getBoundingBox().getDimensions().getWidth() * pObject1->getBoundingBox().getDimensions().getHeight()) < (pObject2->getBoundingBox().getDimensions().getWidth() * pObject2->getBoundingBox().getDimensions().getHeight()));
     }
   return result;
 }
The documentation for this class was generated from the following files:
utility_classes.h
utility_classes.cpp