COPASI API: CQValidator< Type > Class Template Reference
CQValidator< Type > Class Template Reference
#include <CQValidator.h>
Public Member Functions
CQValidator (Type *parent, QString(Type::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
virtual State validate (QString &input, int &) const
Protected Member Functions
State setColor (const State &state) const
Protected Attributes
QString mLastAccepted
Type * mpContainer
QString(Type::* mRetrieve)(void) const
Private Attributes
QColor mAcceptableColor
QColor mErrorColor
QColor mSavedColor
Detailed Description
template<typename Type>
class CQValidator< Type >
Definition at line 26 of file CQValidator.h.
Constructor & Destructor Documentation
template<typename Type> CQValidator< Type >::CQValidator (Type * parent, QString(Type::*)(void) const retrieve, const char * name = 0) inline
Definition at line 30 of file CQValidator.h.
                                                                                        :
     QValidator(parent),
     mpContainer(parent),
     mRetrieve(retrieve),
     mLastAccepted("")
   {
     setObjectName(QString::fromUtf8(name));
     int h, s, v;
     QPalette palette = mpContainer->palette();
     QBrush brush = palette.brush(QPalette::Active, QPalette::Base);
     mSavedColor = brush.color();
 //    mSavedColor = mpLineEdit->paletteBackgroundColor();
     mSavedColor.getHsv(&h, &s, &v);
     if (s < 20) s = 20;
     mAcceptableColor.setHsv(240, s, v);
     mErrorColor.setHsv(0, s, v);
   }
Member Function Documentation
template<typename Type> virtual void CQValidator< Type >::force (const QString & input) const inline virtual
Reimplemented in CQValidatorBound.
Definition at line 77 of file CQValidator.h.
Referenced by CQValidatorBound::force().
   {
     const_cast<CQValidator *>(this)->mLastAccepted = input;
     setColor(Acceptable);
   }
template<typename Type> virtual State CQValidator< Type >::revalidate () inline virtual
Definition at line 63 of file CQValidator.h.
Referenced by CQFittingItemWidget::init(), CQExpressionWidget::isValid(), CQValidator< QTextEdit >::saved(), CQExpressionWidget::setBoolean(), CQExpressionWidget::setExpression(), CQExpressionWidget::setFunction(), CQFittingItemWidget::slotCheckLowerInf(), CQFittingItemWidget::slotCheckUpperInf(), CQTSSAWidget::slotDuration(), CQTrajectoryWidget::slotDuration(), CQTSSAWidget::slotIntervals(), CQTrajectoryWidget::slotIntervals(), CQTSSAWidget::slotIntervalSize(), CQTrajectoryWidget::slotIntervalSize(), CQCrossSectionTaskWidget::updateValues(), and CQExperimentDataValidator::validate().
   {
     QString Input = (*mpContainer.*mRetrieve)();
     int Pos = Input.length();
     return validate(Input, Pos);
   }
template<typename Type> virtual void CQValidator< Type >::saved () const inline virtual
Definition at line 71 of file CQValidator.h.
Referenced by CQNotes::load(), CQExperimentData::loadExperiment(), CQFittingItemWidget::loadSelection(), CQCrossSectionTaskWidget::loadTask(), CQTSSAWidget::loadTask(), CQTrajectoryWidget::loadTask(), CQExperimentData::saveExperiment(), CQFittingItemWidget::saveSelection(), CQCrossSectionTaskWidget::saveTask(), CQTSSAWidget::saveTask(), CQTrajectoryWidget::saveTask(), CQExpressionWidget::setExpression(), and CQExperimentData::slotCheckFrom().
   {
     const_cast<CQValidator *>(this)->mLastAccepted = (*mpContainer.*mRetrieve)();
     const_cast<CQValidator *>(this)->revalidate();
   }
template<typename Type> State CQValidator< Type >::setColor (const State & state) const inline protected
Definition at line 84 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::force(), and CQValidator< QTextEdit >::validate().
   {
     if (state == Invalid)
       {
         mpContainer->setStyleSheet(QString(mpContainer->metaObject()->className()) + " {background-color:" + mErrorColor.name() + ";}");
       }
     else
       {
         mpContainer->setStyleSheet(QString(mpContainer->metaObject()->className()) + " {background-color:" + mAcceptableColor.name() + ";}");
       }
     return state;
   }
template<typename Type> virtual State CQValidator< Type >::validate (QString & input, int &) const inline virtual
Reimplemented in CQValidatorInt, CQValidatorDouble, CQValidatorBound, CQExperimentDataValidator, CQValidatorNotEmpty, CQValidatorFunction, CQValidatorExpression, and CQValidatorXML.
Definition at line 51 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::revalidate(), CQExpressionWidget::slotTextChanged(), CQValidatorXML::validate(), CQValidatorExpression::validate(), CQValidatorFunction::validate(), and CQValidatorNotEmpty::validate().
   {
     if (input == mLastAccepted)
       {
         mpContainer->setStyleSheet(QString(mpContainer->metaObject()->className()) + " {background-color:" + mSavedColor.name() + ";}");
       }
     else
       setColor(Acceptable);
     return Acceptable;
   }
Member Data Documentation
template<typename Type> QColor CQValidator< Type >::mAcceptableColor private
Definition at line 111 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::CQValidator(), and CQValidator< QTextEdit >::setColor().
template<typename Type> QColor CQValidator< Type >::mErrorColor private
Definition at line 113 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::CQValidator(), and CQValidator< QTextEdit >::setColor().
template<typename Type> QString CQValidator< Type >::mLastAccepted protected
Definition at line 106 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::force(), CQValidator< QTextEdit >::saved(), and CQValidator< QTextEdit >::validate().
template<typename Type> Type* CQValidator< Type >::mpContainer protected
Definition at line 99 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::CQValidator(), CQValidator< QTextEdit >::revalidate(), CQValidator< QTextEdit >::saved(), CQValidator< QTextEdit >::setColor(), and CQValidator< QTextEdit >::validate().
template<typename Type> QString(Type::* CQValidator< Type >::mRetrieve)(void) const protected
Method to retrieve the content of the container as a QString
Definition at line 104 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::revalidate(), and CQValidator< QTextEdit >::saved().
template<typename Type> QColor CQValidator< Type >::mSavedColor private
Definition at line 109 of file CQValidator.h.
Referenced by CQValidator< QTextEdit >::CQValidator(), and CQValidator< QTextEdit >::validate().
The documentation for this class was generated from the following file:
CQValidator.h