COPASI API: WizardDialog Class Reference
WizardDialog Class Reference
#include <wizard.h>
Public Slots
virtual void backButton_clicked ()
virtual void buttonGroup2_clicked (int)
virtual void forwardButton_clicked ()
virtual void textBrowser_anchorClicked (const QUrl &url)
Public Member Functions
virtual void setCopasiMainWindow (QWidget *copasiMainWindow)
WizardDialog (QWidget *parent=0, const char *name=0, bool modal=false, Qt::WindowFlags fl=0)
~WizardDialog ()
Static Public Attributes
static const char * texts [6] = {"TutWiz-Step1.html", "TutWiz-Step2.html", "TutWiz-Step3.html", "TutWiz-Step4.html", "TutWiz-Step5.html", "TutWiz-Step6.html"}
Protected Attributes
QButtonGroup * buttonGroup
QWidget * copasiMainWindow
Static Protected Attributes
static const char * Error = "<html><head><title>Error</title></head><body><h1>Could not find help files.<br><br>Please set the COPASI_HELP_PATH environment variable to the absolute path that contains the html help files!</h1></body></html>"
static QString helpPath = ""
Detailed Description
Definition at line 23 of file wizard.h.
Constructor & Destructor Documentation
WizardDialog::WizardDialog (QWidget * parent = 0, const char * name = 0, bool modal = false, Qt::WindowFlags fl = 0)
Definition at line 35 of file wizard.cpp.
References buttonGroup, buttonGroup2_clicked(), Error, COptions::getValue(), helpPath, textBrowser_anchorClicked(), and texts.
                                                                                   :
   QDialog(parent, fl),
   copasiMainWindow(NULL),
   buttonGroup(NULL)
 {
   setupUi(this);
   std::string WizardDir;
   COptions::getValue("WizardDir", WizardDir);
   if (!WizardDir.empty())
     {
       // the next line will hopefully ensure that this works under windows as well.
       WizardDialog::helpPath = "file:///" + QDir(WizardDir.c_str()).absolutePath();
       QString source = WizardDialog::helpPath + "/" + WizardDialog::texts[0];
       this->textBrowser->setSource(source);
     }
   else
     {
       this->textBrowser->setText(WizardDialog::Error);;
     }
   buttonGroup = new QButtonGroup(this);
   buttonGroup->addButton(button1, 0);
   buttonGroup->addButton(button2, 1);
   buttonGroup->addButton(button3, 2);
   buttonGroup->addButton(button4, 3);
   buttonGroup->addButton(button5, 4);
   buttonGroup->addButton(button6, 5);
   buttonGroup->button(0)->setChecked(true);
   connect(buttonGroup, SIGNAL(buttonClicked(int)), this, SLOT(buttonGroup2_clicked(int)));
   connect(textBrowser, SIGNAL(anchorClicked(const QUrl &)), this, SLOT(textBrowser_anchorClicked(const QUrl &)));
 }
WizardDialog::~WizardDialog ()
Definition at line 75 of file wizard.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void WizardDialog::backButton_clicked () virtual slot
Definition at line 119 of file wizard.cpp.
References buttonGroup, and buttonGroup2_clicked().
 {
   buttonGroup->button(buttonGroup->checkedId() - 1)->setChecked(true);
   buttonGroup2_clicked(this->buttonGroup->checkedId());
 }
void WizardDialog::buttonGroup2_clicked (int) virtual slot
Definition at line 86 of file wizard.cpp.
References buttonGroup, helpPath, and texts.
Referenced by backButton_clicked(), forwardButton_clicked(), textBrowser_anchorClicked(), and WizardDialog().
 {
   int checkedId = this->buttonGroup->checkedId();
   if (checkedId == 0)
     {
       this->backButton->setEnabled(false);
       this->forwardButton->setEnabled(true);
     }
   else if (checkedId == 5)
     {
       this->forwardButton->setEnabled(false);
       this->backButton->setEnabled(true);
     }
   else
     {
       this->forwardButton->setEnabled(true);
       this->backButton->setEnabled(true);
     }
   if (WizardDialog::helpPath != "")
     {
       QString source = WizardDialog::helpPath + "/" + WizardDialog::texts[checkedId];
       this->textBrowser->setSource(source);
     }
 }
void WizardDialog::forwardButton_clicked () virtual slot
Definition at line 113 of file wizard.cpp.
References buttonGroup, and buttonGroup2_clicked().
 {
   buttonGroup->button(buttonGroup->checkedId() + 1)->setChecked(true);
   buttonGroup2_clicked(this->buttonGroup->checkedId());
 }
void WizardDialog::setCopasiMainWindow (QWidget * copasiMainWindow) virtual
Definition at line 170 of file wizard.cpp.
References copasiMainWindow.
Referenced by CopasiUI3Window::slotTutorialWizard().
 {
   this->copasiMainWindow = copasiMainWindow;
 }
void WizardDialog::textBrowser_anchorClicked (const QUrl & url) virtual slot
Definition at line 125 of file wizard.cpp.
References buttonGroup, buttonGroup2_clicked(), copasiMainWindow, CopasiUI3Window::getMainWidget(), CQMessageBox::information(), and ListViews::switchToOtherWidget().
Referenced by WizardDialog().
 {
   QString name = url.fragment();
   std::cout << name.toUtf8().data() << std::endl;
   CopasiUI3Window * pMainWindow = dynamic_cast<CopasiUI3Window *>(copasiMainWindow);
   if (name == "Model Settings")
     {
       if (pMainWindow)
         pMainWindow->getMainWidget()->switchToOtherWidget(1, "");
     }
   else if (name == "Reaction Overview")
     {
       if (pMainWindow)
         pMainWindow->getMainWidget()->switchToOtherWidget(114, "");
     }
   else if (name == "Report Definition")
     {
       if (pMainWindow)
         pMainWindow->getMainWidget()->switchToOtherWidget(43, "");
     }
   else if (name == "Step 1")
     {
       buttonGroup->button(0)->setChecked(true);
       buttonGroup2_clicked(this->buttonGroup->checkedId());
     }
   else if (name == "Time Course")
     {
       if (pMainWindow)
         pMainWindow->getMainWidget()->switchToOtherWidget(23, "");
     }
   else if (name == "Plot Definition Overview")
     {
       if (pMainWindow)
         pMainWindow->getMainWidget()->switchToOtherWidget(42, "");
     }
   else
     {
       CQMessageBox::information(this, "Error", "Link not found",
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
 }
Member Data Documentation
QButtonGroup* WizardDialog::buttonGroup protected
Definition at line 45 of file wizard.h.
Referenced by backButton_clicked(), buttonGroup2_clicked(), forwardButton_clicked(), textBrowser_anchorClicked(), and WizardDialog().
QWidget* WizardDialog::copasiMainWindow protected
Definition at line 44 of file wizard.h.
Referenced by setCopasiMainWindow(), and textBrowser_anchorClicked().
const char * WizardDialog::Error = "<html><head><title>Error</title></head><body><h1>Could not find help files.<br><br>Please set the COPASI_HELP_PATH environment variable to the absolute path that contains the html help files!</h1></body></html>" static protected
Definition at line 42 of file wizard.h.
Referenced by WizardDialog().
QString WizardDialog::helpPath = "" static protected
Definition at line 43 of file wizard.h.
Referenced by buttonGroup2_clicked(), and WizardDialog().
const char * WizardDialog::texts = {"TutWiz-Step1.html", "TutWiz-Step2.html", "TutWiz-Step3.html", "TutWiz-Step4.html", "TutWiz-Step5.html", "TutWiz-Step6.html"} static
Definition at line 31 of file wizard.h.
Referenced by buttonGroup2_clicked(), and WizardDialog().
The documentation for this class was generated from the following files:
wizard.h
wizard.cpp