COPASI API: CSensMethod Class Reference
CSensMethod Class Reference
#include <CSensMethod.h>
Public Member Functions
CSensMethod (const CSensMethod &src, const CCopasiContainer *pParent=NULL)
size_t getNumberOfSubtaskCalculations ()
bool initialize (CSensProblem *problem)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
bool process (CProcessReport *handler)
bool restore (const bool &updateModel)
~CSensMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CSensMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::sensMethod)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
void calculate_difference (size_t level, const C_FLOAT64 &delta, CCopasiArray &result, CCopasiArray::index_type &resultindex)
bool calculate_one_level (size_t level, CCopasiArray &result)
CSensMethod (CCopasiMethod::SubType subType, const CCopasiContainer *pParent=NULL)
void do_collapsing ()
C_FLOAT64 do_collapsing_innerloop (CCopasiArray::index_type &fullindex)
void do_scaling ()
bool do_target_calculation (CCopasiArray &result, bool first)
C_FLOAT64 do_variation (CCopasiObject *variable)
void scaling_targetfunction (const C_FLOAT64 &factor, CCopasiArray::index_type &resultindex)
void scaling_variables (size_t level, const C_FLOAT64 &factor, CCopasiArray::index_type &resultindex)
void setValue (CCopasiObject *variable, C_FLOAT64 value)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
std::vector< Refresh * > mInitialRefreshes
std::vector< CSensMethodLocalData > mLocalData
C_FLOAT64 * mpDeltaFactor
C_FLOAT64 * mpMinDelta
CSensProblem * mpProblem
CCopasiTask * mpSubTask
bool mStoreSubtasktUpdateFlag
stores the update model flag of the subtask
std::vector< CCopasiObject * > mTargetfunctionPointers
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CSensMethod ()
Private Attributes
size_t mCounter
size_t mFailedCounter
unsigned C_INT32 mProgress
size_t mProgressHandler
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 49 of file CSensMethod.h.
Constructor & Destructor Documentation
CSensMethod::CSensMethod () private
Default constructor.
Referenced by createMethod().
CSensMethod::CSensMethod (CCopasiMethod::SubType subType, const CCopasiContainer * pParent = NULL) explicit protected
Specific constructor.
Parameters
CCopasiMethod::SubType subType
const CCopasiContainer * pParent (default: NULL)
Default constructor.
Definition at line 55 of file CSensMethod.cpp.
References CCopasiParameterGroup::addParameter(), C_FLOAT64, CONSTRUCTOR_TRACE, CCopasiParameter::getValue(), mpDeltaFactor, mpMinDelta, CCopasiParameter::Value::pUDOUBLE, and CCopasiParameter::UDOUBLE.
                                                           :
   CCopasiMethod(CCopasiTask::sens, subType, pParent),
   mpProblem(NULL),
   mLocalData(),
   mTargetfunctionPointers(),
   mpSubTask(NULL),
   mInitialRefreshes(),
   mpDeltaFactor(NULL),
   mpMinDelta(NULL),
   mStoreSubtasktUpdateFlag(false),
   mProgressHandler(C_INVALID_INDEX),
   mProgress(0),
   mCounter(0),
   mFailedCounter(0)
 {
   addParameter("Delta factor",
                CCopasiParameter::UDOUBLE, (C_FLOAT64) 1e-3);
   mpDeltaFactor = (C_FLOAT64*)getValue("Delta factor").pUDOUBLE;
   addParameter("Delta minimum",
                CCopasiParameter::UDOUBLE, (C_FLOAT64) 1e-12);
   mpMinDelta = (C_FLOAT64*)getValue("Delta minimum").pUDOUBLE;
   CONSTRUCTOR_TRACE;
 }
CSensMethod::CSensMethod (const CSensMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CTSSMethod & src
const CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CSensMethod & src
Definition at line 86 of file CSensMethod.cpp.
References CONSTRUCTOR_TRACE.
                                                           :
   CCopasiMethod(src, pParent),
   mpProblem(src.mpProblem),
   mLocalData(),
   mTargetfunctionPointers(),
   mpSubTask(NULL),
   mInitialRefreshes(),
   mpDeltaFactor(NULL),
   mpMinDelta(NULL),
   mStoreSubtasktUpdateFlag(false),
   mProgressHandler(C_INVALID_INDEX),
   mProgress(0),
   mCounter(0),
   mFailedCounter(0)
 {CONSTRUCTOR_TRACE;}
CSensMethod::~CSensMethod ()
Destructor.
Definition at line 106 of file CSensMethod.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
void CSensMethod::calculate_difference (size_t level, const C_FLOAT64 & delta, CCopasiArray & result, CCopasiArray::index_type & resultindex) protected
Definition at line 213 of file CSensMethod.cpp.
References C_INVALID_INDEX, and mLocalData.
Referenced by calculate_one_level().
 {
   assert(delta != 0.0);
   assert(mLocalData[level].tmp1.size() == mLocalData[level].tmp2.size());
   size_t dim = mLocalData[level].tmp1.dimensionality();
   assert(resultindex.size() >= dim);
   CCopasiArray::index_type indexmax = mLocalData[level].tmp1.size();
   //init index with zero
   CCopasiArray::index_type indexit; indexit.resize(dim);
   size_t i;
   for (i = 0; i < dim; ++i)
     indexit[i] = 0;
   //handle scalars separately
   if (dim == 0)
     {
       result[resultindex] = (mLocalData[level].tmp2[indexit] - mLocalData[level].tmp1[indexit]) / delta;
       return;
     }
   //now for all higher dimensionalities
   for (;;)
     {
       //do difference calculation
       for (i = 0; i < dim; ++i)
         resultindex[i] = indexit[i];  //TODO: use stl algorithm
       result[resultindex] = (mLocalData[level].tmp2[indexit] - mLocalData[level].tmp1[indexit]) / delta;
       //increase index
       ++indexit[dim - 1];
       //check overflow
       size_t j;
       for (j = dim - 1; j != C_INVALID_INDEX; --j)
         {
           if (indexit[j] >= indexmax[j])
             {
               indexit[j] = 0;
               if (j > 0)
                 ++indexit[j - 1];
               else
                 return;
             }
           else
             break;
         }
     }
 }
bool CSensMethod::calculate_one_level (size_t level, CCopasiArray & result) protected
Definition at line 269 of file CSensMethod.cpp.
References C_FLOAT64, calculate_difference(), do_target_calculation(), do_variation(), CCopasiParameter::getValuePointer(), mLocalData, CCopasiArray::resize(), and setValue().
Referenced by process().
 {
   //do first calculation
   if (level == 0)
     {
       if (!do_target_calculation(mLocalData[level].tmp1, true)) return false;
     }
   else
     {
       if (!calculate_one_level(level - 1, mLocalData[level].tmp1)) return false;
     }
   //resize results array
   CCopasiArray::index_type resultindex; resultindex = mLocalData[level].tmp1.size();
   if (mLocalData[level].variables.size() > 1)
     resultindex.push_back(mLocalData[level].variables.size());
   result.resize(resultindex);
   //loop over all variables
   size_t i, imax = mLocalData[level].variables.size();
   for (i = 0; i < imax; ++i)
     {
       //store variable value
       C_FLOAT64 store = *(C_FLOAT64 *)mLocalData[level].variables[i]->getValuePointer();
       //change variable
       C_FLOAT64 delta = do_variation(mLocalData[level].variables[i]);
       //do second calculation
       if (level == 0)
         {
           if (!do_target_calculation(mLocalData[level].tmp2, false)) return false;
         }
       else
         {
           if (!calculate_one_level(level - 1, mLocalData[level].tmp2)) return false;
         }
       //restore variable
       //mLocalData[level].variables[i]->setObjectValue(store);
       setValue(mLocalData[level].variables[i], store);
       //calculate derivative
       if (imax > 1)
         resultindex[resultindex.size() - 1] = i;
       calculate_difference(level, delta, result, resultindex);
     }
   return true;
 }
CSensMethod * CSensMethod::createMethod (CCopasiMethod::SubType subType = CCopasiMethod::sensMethod) static
Create a trajectory method. Note: the returned object has to be released after use with delete
CSensMethod class.
Definition at line 34 of file CSensMethod.cpp.
References CSensMethod(), fatalError, CCopasiMethod::sensMethod, and CCopasiMethod::unset.
Referenced by SensitivitiesWidget::createMethod(), and CSensTask::createMethod().
 {
   CSensMethod * pMethod = NULL;
   switch (subType)
     {
       case unset:
       case sensMethod:
         pMethod = new CSensMethod(subType);
         break;
       default:
         fatalError();
     }
   return pMethod;
 }
void CSensMethod::do_collapsing () protected
collapse the first dimension of the scaled result (by calculating the 2-norm over the target functions)
Definition at line 437 of file CSensMethod.cpp.
References C_INVALID_INDEX, CSensProblem::collapsRequested(), do_collapsing_innerloop(), CSensProblem::getCollapsedResult(), CSensProblem::getScaledResult(), mpProblem, and CCopasiArray::size().
Referenced by process().
 {
   if (mpProblem->collapsRequested())
     {
       CCopasiArray::index_type fullresultindex = mpProblem->getScaledResult().size();
       CCopasiArray::index_type collapsedresultindex = mpProblem->getCollapsedResult().size();
       size_t shift = fullresultindex.size() - collapsedresultindex.size();
       if (shift != 1) return; //only supported if target functions list is 1D
       //***** skalar ********
       if (collapsedresultindex.size() == 0)
         {
           mpProblem->getCollapsedResult()[collapsedresultindex] =
             do_collapsing_innerloop(fullresultindex);
           return;
         }
       //***** higher dimensions *********
       size_t i, dim = collapsedresultindex.size();
       CCopasiArray::index_type indexmax = mpProblem->getCollapsedResult().size();
       //set index to zero
       for (i = 0; i < dim; ++i) collapsedresultindex[i] = 0;
       for (;;)
         {
           fullresultindex[0] = 0;
           for (i = 0; i < dim; ++i)
             fullresultindex[i + shift] = collapsedresultindex[i];
           mpProblem->getCollapsedResult()[collapsedresultindex] =
             do_collapsing_innerloop(fullresultindex);
           //increase index
           ++collapsedresultindex[dim - 1];
           //check overflow
           size_t j;
           for (j = dim - 1; j != C_INVALID_INDEX; --j)
             {
               if (collapsedresultindex[j] >= indexmax[j])
                 {
                   collapsedresultindex[j] = 0;
                   if (j > 0)
                     ++collapsedresultindex[j - 1];
                   else
                     return;
                 }
               else
                 break;
             }
         }
     }
   else
     {}
 }
C_FLOAT64 CSensMethod::do_collapsing_innerloop (CCopasiArray::index_type & fullindex) protected
Definition at line 413 of file CSensMethod.cpp.
References C_FLOAT64, CSensProblem::getScaledResult(), max, mpProblem, and CCopasiArray::size().
Referenced by do_collapsing().
 {
   //fullindex[0]=0;
   //return mpProblem->getScaledResult()[fullindex];
   //assumes the sum is to be taken over the first dim of the scaled result array
   C_FLOAT64 tmpFloat, tmpSum = 0;
   size_t i, imax = mpProblem->getScaledResult().size()[0];
   for (i = 0; i < imax; ++i)
     {
       fullindex[0] = i;
       tmpFloat = mpProblem->getScaledResult()[fullindex];
       if (tmpFloat != tmpFloat) continue;
       if (fabs(tmpFloat) >= std::numeric_limits< C_FLOAT64 >::max()) continue;
       tmpSum += tmpFloat * tmpFloat;
     }
   return sqrt(tmpSum);
 }
void CSensMethod::do_scaling () protected
calculate the scaled sensitivities. Calls scaling_variables(). It is assumed that the scaled result array is already of the correct size (this is done in initialize()).
Definition at line 404 of file CSensMethod.cpp.
References CCopasiArray::dimensionality(), CSensProblem::getResult(), mLocalData, mpProblem, and scaling_variables().
Referenced by process().
 {
   CCopasiArray::index_type index;
   index.resize(mpProblem->getResult().dimensionality());
   scaling_variables(mLocalData.size() - 1, 1.0, index);
 }
bool CSensMethod::do_target_calculation (CCopasiArray & result, bool first) protected
Definition at line 111 of file CSensMethod.cpp.
References C_FLOAT64, CCopasiProblem::getModel(), CCopasiParameter::getValuePointer(), mCounter, mFailedCounter, mInitialRefreshes, CCopasiMethod::mpCallBack, mpProblem, mProgress, mProgressHandler, mpSubTask, mTargetfunctionPointers, CCopasiTask::process(), CProcessReport::progressItem(), CCopasiArray::resize(), CModel::updateNonSimulatedValues(), and CModel::updateSimulatedValues().
Referenced by calculate_one_level().
 {
   bool success = false;
   //perform the necessary updates
   std::vector< Refresh * >::iterator it = mInitialRefreshes.begin();
   std::vector< Refresh * >::iterator end = mInitialRefreshes.end();
   while (it != end)
     (**it++)();
   //****** do subtask ******************
   if (mpSubTask != NULL)
     {
       success = mpSubTask->process(/*first*/true);
       mCounter++;
     }
   else
     {
       success = true; // doing nothing should never fail.
     }
   mpProblem->getModel()->updateSimulatedValues(true);
   mpProblem->getModel()->updateNonSimulatedValues();
   //****** retrieve results ************
   //resize results array
   CCopasiArray::index_type resultindex;
   size_t i, imax = mTargetfunctionPointers.size();
   if (imax > 1)
     resultindex.push_back(imax);
   result.resize(resultindex);
   //copy result
   if (success)
     {
       for (i = 0; i < imax; ++i)
         {
           if (imax > 1)
             resultindex[0] = i;
           result[resultindex] = *(C_FLOAT64 *)mTargetfunctionPointers[i]->getValuePointer();
         }
     }
   else
     {
       mFailedCounter++;
       for (i = 0; i < imax; ++i)
         {
           if (imax > 1)
             resultindex[0] = i;
           result[resultindex] = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
         }
     }
   //progress bar
   ++mProgress;
   if (mpCallBack)
     {
       bool tmp = mpCallBack->progressItem(mProgressHandler);
       return tmp;
     }
   return success;
 }
C_FLOAT64 CSensMethod::do_variation (CCopasiObject * variable) protected
Definition at line 183 of file CSensMethod.cpp.
References C_FLOAT64, CCopasiObject::getValuePointer(), mpDeltaFactor, mpMinDelta, and setValue().
Referenced by calculate_one_level().
 {
   C_FLOAT64 value;
   value = *(C_FLOAT64*)variable->getValuePointer();
   C_FLOAT64 delta;
   delta = fabs(value) * *mpDeltaFactor;
   if (delta < *mpMinDelta) delta = *mpMinDelta;
   setValue(variable, delta + value);
   return delta;
 }
size_t CSensMethod::getNumberOfSubtaskCalculations ()
estimate how many calls to the subtask are necessary. Works only after initialize() was called.
Definition at line 686 of file CSensMethod.cpp.
References mLocalData.
Referenced by process().
 {
   size_t ret = 1;
   size_t i;
   for (i = 0; i < mLocalData.size(); ++i)
     {
       ret *= mLocalData[i].variables.size() + 1;
     }
   return ret;
 }
bool CSensMethod::initialize (CSensProblem * problem)
initializes the subtask, creates the internal data structures of the method, resizes the result arrays and creates the array annotations
Definition at line 501 of file CSensMethod.cpp.
References CModel::buildInitialRefreshSequence(), C_INVALID_INDEX, CSensProblem::collapsRequested(), CSensProblem::CrossSection, CSensProblem::Evaluation, CCopasiParameter::getCN(), CSensProblem::getCollapsedResult(), CSensProblem::getCollapsedResultAnnotated(), CSensItem::getListTypeDisplayName(), CCopasiProblem::getModel(), CSensProblem::getNumberOfVariables(), CCopasiObject::getObjectDataModel(), CCopasiTask::getProblem(), CSensProblem::getResult(), CSensProblem::getResultAnnotated(), CSensProblem::getScaledResult(), CSensProblem::getScaledResultAnnotated(), CSensProblem::getSubTaskType(), CSensProblem::getTargetFunctions(), CCopasiDataModel::getTaskList(), CSensProblem::getVariables(), CSensItem::getVariablesPointerList(), CCopasiTask::initialize(), CCopasiTask::isUpdateModel(), mInitialRefreshes, mLocalData, mpProblem, mpSubTask, mStoreSubtasktUpdateFlag, mTargetfunctionPointers, CCopasiTask::NO_OUTPUT, CSensProblem::Optimization, CSensProblem::ParameterEstimation, CCopasiArray::resize(), CArrayAnnotation::resize(), CArrayAnnotation::setAnnotationCN(), CCopasiTask::setCallBack(), CArrayAnnotation::setDimensionDescription(), CCopasiProblem::setModel(), CCopasiTask::setUpdateModel(), CSensProblem::SteadyState, and CSensProblem::TimeSeries.
Referenced by CSensTask::updateMatrices().
 {
   bool success = true;
   mpProblem = problem;
   assert(mpProblem);
   //initialize the target calculation
   mpSubTask = NULL;
   CCopasiDataModel* pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   switch (mpProblem->getSubTaskType())
     {
       case CSensProblem::Evaluation:
         mpSubTask = NULL;
         break;
       case CSensProblem::SteadyState:
         mpSubTask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Steady-State"]);
         break;
       case CSensProblem::TimeSeries:
         mpSubTask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Time-Course"]);
         break;
         /*    case CSensProblem::LyapunovExp:
               mpSubTask = dynamic_cast<CCopasiTask*>
                           ((*pDataModel->getTaskList())["Lyapunov Exponents"]);
               break;*/
       case CSensProblem::ParameterEstimation:
         mpSubTask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Parameter Estimation"]);
         break;
       case CSensProblem::Optimization:
         mpSubTask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Optimization"]);
         break;
       case CSensProblem::CrossSection:
         mpSubTask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Cross Section"]);
         break;
     }
   if (mpSubTask)
     {
       //the subtask should not change the initial state of the model
       mStoreSubtasktUpdateFlag = mpSubTask->isUpdateModel();
       mpSubTask->setUpdateModel(false);
       mpSubTask->getProblem()->setModel(mpProblem->getModel());
       mpSubTask->setCallBack(NULL);
       success &= mpSubTask->initialize(CCopasiTask::NO_OUTPUT, NULL, NULL);
     }
   //initialize the variables pointers
   std::set< const CCopasiObject * > ObjectSet;
   size_t i, imax = mpProblem->getNumberOfVariables();
   mLocalData.resize(imax);
   for (i = 0; i < imax; ++i)
     {
       mLocalData[i].variables = mpProblem->getVariables(i).getVariablesPointerList(pDataModel);
       ObjectSet.insert(mLocalData[i].variables.begin(), mLocalData[i].variables.end());
     }
   //determine which refreshes need to be called when the variables are changed
   ObjectSet.erase(NULL);
   mInitialRefreshes.clear();
   mInitialRefreshes = mpProblem->getModel()->buildInitialRefreshSequence(ObjectSet);
   //initialize the target function pointers
   mTargetfunctionPointers = mpProblem->getTargetFunctions().getVariablesPointerList(pDataModel);
   //****** initialize result annotations ****************
   //determine dimensions of result
   CCopasiArray::index_type s;
   CCopasiArray::index_type sc; //size of collapsed result
   if (mTargetfunctionPointers.size() > 1)
     {
       s.push_back(mTargetfunctionPointers.size());
     }
   for (i = 0; i < imax; ++i)
     {
       if (mLocalData[i].variables.size() > 1)
         {
           mLocalData[i].index = s.size();
           s.push_back(mLocalData[i].variables.size());
           sc.push_back(mLocalData[i].variables.size());
         }
       else
         mLocalData[i].index = C_INVALID_INDEX;
     }
   //resize result & annotations
   mpProblem->getResult().resize(s);
   mpProblem->getResultAnnotated()->resize();
   //mpProblem->getResultAnnotated()->setMode(CArrayAnnotation::OBJECTS);
   mpProblem->getScaledResult().resize(s);
   mpProblem->getScaledResultAnnotated()->resize();
   //mpProblem->getScaledResultAnnotated()->setMode(CArrayAnnotation::OBJECTS);
   if (mpProblem->collapsRequested())
     {
       mpProblem->getCollapsedResult().resize(sc);
       mpProblem->getCollapsedResultAnnotated()->resize();
       //mpProblem->getCollapsedResultAnnotated()->setMode(CArrayAnnotation::OBJECTS);
     }
   size_t dim = 0;
   size_t j;
   //target function annotations //TODO: only implemented for scalar and vector
   if (mTargetfunctionPointers.size() > 1)
     {
       std::ostringstream tmp;
       tmp << "Target functions, " << mpProblem->getTargetFunctions().getListTypeDisplayName();
       mpProblem->getResultAnnotated()->setDimensionDescription(dim, tmp.str());
       mpProblem->getScaledResultAnnotated()->setDimensionDescription(dim, tmp.str());
       for (j = 0; j < mTargetfunctionPointers.size(); ++j)
         {
           mpProblem->getResultAnnotated()->setAnnotationCN(dim, j, mTargetfunctionPointers[j]->getCN());
           mpProblem->getScaledResultAnnotated()->setAnnotationCN(dim, j, mTargetfunctionPointers[j]->getCN());
         }
       ++dim;
     }
   //variables annotiation
   size_t dim2 = 0; //for collapsed result
   for (i = 0; i < imax; ++i)
     {
       if (mLocalData[i].variables.size() > 1)
         {
           std::ostringstream tmp;
           tmp << "Variables " << i + 1 << ", " << mpProblem->getVariables(i).getListTypeDisplayName();
           mpProblem->getResultAnnotated()->setDimensionDescription(dim, tmp.str());
           mpProblem->getScaledResultAnnotated()->setDimensionDescription(dim, tmp.str());
           if (mpProblem->collapsRequested())
             mpProblem->getCollapsedResultAnnotated()->setDimensionDescription(dim2, tmp.str());
           for (j = 0; j < mLocalData[i].variables.size(); ++j)
             {
               mpProblem->getResultAnnotated()->setAnnotationCN(dim, j, mLocalData[i].variables[j]->getCN());
               mpProblem->getScaledResultAnnotated()->setAnnotationCN(dim, j, mLocalData[i].variables[j]->getCN());
               if (mpProblem->collapsRequested())
                 mpProblem->getCollapsedResultAnnotated()->setAnnotationCN(dim2, j, mLocalData[i].variables[j]->getCN());
             }
           ++dim;
           ++dim2;
         }
     }
   return success;
 }
bool CSensMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
Definition at line 738 of file CSensMethod.cpp.
References CCopasiMessage::EXCEPTION, and CCopasiMethod::isValidProblem().
 {
   if (!CCopasiMethod::isValidProblem(pProblem)) return false;
   const CSensProblem * pP = dynamic_cast<const CSensProblem *>(pProblem);
   if (!pP)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, "Problem is not a sensitivities problem.");
       return false;
     }
   return true;
   //all sizes at least one
   //dimension of variables 0 or 1
   //if target is scan make sure the scan subtask is not sens.
 }
bool CSensMethod::process (CProcessReport * handler)
Definition at line 699 of file CSensMethod.cpp.
References CProcessReport::addItem(), C_INT32, calculate_one_level(), do_collapsing(), do_scaling(), CProcessReport::finishItem(), getNumberOfSubtaskCalculations(), CSensProblem::getResult(), max, MCCopasiTask, mCounter, mFailedCounter, mLocalData, CCopasiMethod::mpCallBack, mpProblem, mProgress, mProgressHandler, mpSubTask, CCopasiTask::setCallBack(), CProcessReport::setName(), and CCopasiMessage::WARNING.
Referenced by CSensTask::process().
 {
   // Reset the evaluation counter
   mCounter = 0;
   mFailedCounter = 0;
   if (!mLocalData.size()) return false;
   //initialize progress bar
   mpCallBack = handler;
   if (mpCallBack)
     {
       mpCallBack->setName("performing sensitivities calculation...");
       unsigned C_INT32 max = (unsigned C_INT32) getNumberOfSubtaskCalculations();
       mProgress = 0;
       mProgressHandler = mpCallBack->addItem("Completion",
                                              mProgress,
                                              &max);
       if (mpSubTask)
         mpSubTask->setCallBack(mpCallBack);
     }
   if (!calculate_one_level(mLocalData.size() - 1, mpProblem->getResult())) return false;
   do_scaling();
   do_collapsing();
   if (mpCallBack) mpCallBack->finishItem(mProgressHandler);
   if (mFailedCounter * 20 > mCounter) // > 5% failure rate
     CCopasiMessage(CCopasiMessage::WARNING, MCCopasiTask + 8, mFailedCounter, mCounter);
   return true;
 }
bool CSensMethod::restore (const bool & updateModel)
Do all necessary restore procedures so that the model is in the same state as before
Parameters
const bool & updateModel
Returns
bool success
Definition at line 672 of file CSensMethod.cpp.
References mpSubTask, mStoreSubtasktUpdateFlag, CCopasiTask::restore(), and CCopasiTask::setUpdateModel().
Referenced by CSensTask::restore().
 {
   bool success = true;
   if (mpSubTask != NULL)
   {
     success &= mpSubTask->restore();
     //restore the update model flag
     mpSubTask->setUpdateModel(mStoreSubtasktUpdateFlag);
   }
   return success;
 }
void CSensMethod::scaling_targetfunction (const C_FLOAT64 & factor, CCopasiArray::index_type & resultindex) protected
This contains the loop over the target functions for scaling the sensitivities
Definition at line 326 of file CSensMethod.cpp.
References C_INVALID_INDEX, CSensProblem::getResult(), CSensProblem::getScaledResult(), mLocalData, and mpProblem.
Referenced by scaling_variables().
 {
   size_t dim = mLocalData[0].tmp1.dimensionality();
   assert(resultindex.size() >= dim);
   CCopasiArray::index_type indexmax = mLocalData[0].tmp1.size();
   //init index with zero
   CCopasiArray::index_type indexit; indexit.resize(dim);
   size_t i;
   for (i = 0; i < dim; ++i)
     indexit[i] = 0;
   //handle scalars separately
   if (dim == 0)
     {
       mpProblem->getScaledResult()[resultindex] = mpProblem->getResult()[resultindex] * factor / mLocalData[0].tmp1[indexit];
       return;
     }
   //now for all higher dimensionalities
   for (;;)
     {
       for (i = 0; i < dim; ++i)
         resultindex[i] = indexit[i];  //TODO: use stl algorithm
       mpProblem->getScaledResult()[resultindex] = mpProblem->getResult()[resultindex] * factor / mLocalData[0].tmp1[indexit];
       //increase index
       ++indexit[dim - 1];
       //check overflow
       size_t j;
       for (j = dim - 1; j != C_INVALID_INDEX; --j)
         {
           if (indexit[j] >= indexmax[j])
             {
               indexit[j] = 0;
               if (j > 0)
                 ++indexit[j - 1];
               else
                 return;
             }
           else
             break;
         }
     }
 }
void CSensMethod::scaling_variables (size_t level, const C_FLOAT64 & factor, CCopasiArray::index_type & resultindex) protected
This contains the loop over the variables for scaling the sensitivities. Works recursively and calls scaling_targetfunction() in the end.
Definition at line 378 of file CSensMethod.cpp.
References C_FLOAT64, CCopasiParameter::getValuePointer(), mLocalData, and scaling_targetfunction().
Referenced by do_scaling().
 {
   //loop over all variables
   size_t i, imax = mLocalData[level].variables.size();
   for (i = 0; i < imax; ++i)
     {
       //get Value
       C_FLOAT64 value = *(C_FLOAT64 *)mLocalData[level].variables[i]->getValuePointer() * factor;
       //do recursive calculation
       if (imax > 1)
         resultindex[mLocalData[level].index] = i;
       if (level == 0)
         {
           scaling_targetfunction(value, resultindex);
         }
       else
         {
           scaling_variables(level - 1, value, resultindex);
         }
     }
 }
void CSensMethod::setValue (CCopasiObject * variable, C_FLOAT64 value) protected
wraps the CCopasiObject::setObjectValue() method so we can add special treatment of concentrations
Definition at line 197 of file CSensMethod.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectName(), CMetab::refreshNumber(), CMetab::setConcentration(), and CCopasiObject::setObjectValue().
Referenced by calculate_one_level(), and do_variation().
 {
   variable->setObjectValue(value);
   if (variable->getObjectName() == "Concentration")
     {
       CMetab* pMetab = dynamic_cast<CMetab*>(variable->getObjectAncestor("Metabolite"));
       if (pMetab)
         {
           pMetab->setConcentration(value);
           pMetab->refreshNumber();
         }
     }
 }
Member Data Documentation
size_t CSensMethod::mCounter private
Definition at line 188 of file CSensMethod.h.
Referenced by do_target_calculation(), and process().
size_t CSensMethod::mFailedCounter private
Definition at line 189 of file CSensMethod.h.
Referenced by do_target_calculation(), and process().
std::vector< Refresh * > CSensMethod::mInitialRefreshes protected
Definition at line 176 of file CSensMethod.h.
Referenced by do_target_calculation(), and initialize().
std::vector<CSensMethodLocalData> CSensMethod::mLocalData protected
Definition at line 170 of file CSensMethod.h.
Referenced by calculate_difference(), calculate_one_level(), do_scaling(), getNumberOfSubtaskCalculations(), initialize(), process(), scaling_targetfunction(), and scaling_variables().
C_FLOAT64* CSensMethod::mpDeltaFactor protected
Definition at line 178 of file CSensMethod.h.
Referenced by CSensMethod(), and do_variation().
C_FLOAT64* CSensMethod::mpMinDelta protected
Definition at line 179 of file CSensMethod.h.
Referenced by CSensMethod(), and do_variation().
CSensProblem* CSensMethod::mpProblem protected
A pointer to the sensitivities problem.
Definition at line 168 of file CSensMethod.h.
Referenced by do_collapsing(), do_collapsing_innerloop(), do_scaling(), do_target_calculation(), initialize(), process(), and scaling_targetfunction().
unsigned C_INT32 CSensMethod::mProgress private
Definition at line 186 of file CSensMethod.h.
Referenced by do_target_calculation(), and process().
size_t CSensMethod::mProgressHandler private
Definition at line 185 of file CSensMethod.h.
Referenced by do_target_calculation(), and process().
CCopasiTask* CSensMethod::mpSubTask protected
Definition at line 174 of file CSensMethod.h.
Referenced by do_target_calculation(), initialize(), process(), and restore().
bool CSensMethod::mStoreSubtasktUpdateFlag protected
stores the update model flag of the subtask
Definition at line 182 of file CSensMethod.h.
Referenced by initialize(), and restore().
std::vector<CCopasiObject*> CSensMethod::mTargetfunctionPointers protected
Definition at line 172 of file CSensMethod.h.
Referenced by do_target_calculation(), and initialize().
The documentation for this class was generated from the following files:
CSensMethod.h
CSensMethod.cpp