COPASI API: test000046 Class Reference
test000046 Class Reference
#include <test000046.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_stoichiometricExpression ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_stoichiometricExpression)
CPPUNIT_TEST_SUITE (test000046)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000046.h.
Member Function Documentation
test000046::CPPUNIT_TEST (test_stoichiometricExpression) private
test000046::CPPUNIT_TEST_SUITE (test000046) private
test000046::CPPUNIT_TEST_SUITE_END () private
void test000046::setUp ()
Definition at line 28 of file test000046.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000046::tearDown ()
Definition at line 36 of file test000046.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000046::test_stoichiometricExpression ()
Definition at line 41 of file test000046.cpp.
References CModelEntity::FIXED, CChemEq::getCompartmentNumber(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CChemEq::getModifiers(), CChemEq::getProducts(), CChemEq::getSubstrates(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING, pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, CCopasiVector< T >::size(), and CCopasiMessage::WARNING.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(fabs((pModelValue->getInitialValue() - 3.7) / 3.7) < 1e-3);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction1 = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction1 != NULL);
   CPPUNIT_ASSERT(pReaction1->isReversible() == true);
   // check the kinetic law
   const CFunction* pKineticFunction = pReaction1->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   const CMassAction* pMassAction = dynamic_cast<const CMassAction*>(pKineticFunction);
   CPPUNIT_ASSERT(pMassAction != NULL);
   const CChemEq* pChemEq = &pReaction1->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   const CChemEqElement* pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs((pElement->getMultiplicity() - 1.85) / 1.85) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 1);
   pElement = pChemEq->getProducts()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs((pElement->getMultiplicity() - 3.35) / 3.35) / 3.35 < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pB);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   //CPPUNIT_ASSERT(CCopasiMessage::size() == 5);
   CCopasiMessage message = CCopasiMessage::getLastMessage();
   CPPUNIT_ASSERT(message.getType() == CCopasiMessage::WARNING);
   std::string s = message.getText();
   CPPUNIT_ASSERT(!s.empty());
   CPPUNIT_ASSERT(s.find(std::string("One or more stoichiometric expressions were evaluated and converted to constants values.")) != std::string::npos);
   // the other four messages are libSBML unit warnings I don't care about right
   // now.
 }
Member Data Documentation
const char * test000046::MODEL_STRING static protected
Definition at line 31 of file test000046.h.
Referenced by test_stoichiometricExpression().
CCopasiDataModel * test000046::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000046.h.
Referenced by setUp(), and test_stoichiometricExpression().
The documentation for this class was generated from the following files:
test000046.h
test000046.cpp