COPASI API: CCopasiXMLParser::RectangleElement Class Reference
CCopasiXMLParser::RectangleElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
RectangleElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~RectangleElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Rectangle = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4116 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::RectangleElement::Element private
Enumerator
Rectangle
Definition at line 4123 of file CCopasiXMLParser.h.
     {
       Rectangle = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::RectangleElement::RectangleElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 11679 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::RectangleElement::~RectangleElement () virtual
Destructor
Definition at line 11684 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::RectangleElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 11794 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Rectangle:
         if (strcmp(pszName, "Rectangle"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Rectangle", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::RectangleElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 11689 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CLGraphicalPrimitive2D::EVENODD, CCopasiMessage::EXCEPTION, CLGraphicalPrimitive2D::INHERIT, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive2D::NONZERO, CLGraphicalPrimitive1D::parseDashArray(), CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, CLRectangle::setCoordinatesAndSize(), CLGraphicalPrimitive2D::setFillColor(), CLGraphicalPrimitive2D::setFillRule(), CLRectangle::setRadii(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), strToDouble(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * Stroke;
   const char * StrokeWidth;
   const char * StrokeDashArray;
   const char * Fill;
   const char * FillRule;
   const char * X;
   const char * Y;
   const char * Z;
   const char * WIDTH;
   const char * HEIGHT;
   const char * RX;
   const char * RY;
   CLRectangle* pRectangle = NULL;
   switch (mCurrentElement)
     {
       case Rectangle:
         if (strcmp(pszName, "Rectangle"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Rectangle", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         Stroke = mParser.getAttributeValue("stroke", papszAttrs, false);
         StrokeWidth = mParser.getAttributeValue("stroke-width", papszAttrs, false);
         StrokeDashArray = mParser.getAttributeValue("stroke-dasharray", papszAttrs, false);
         Fill = mParser.getAttributeValue("fill", papszAttrs, false);
         FillRule = mParser.getAttributeValue("fill-rule", papszAttrs, false);
         X = mParser.getAttributeValue("x", papszAttrs);
         Y = mParser.getAttributeValue("y", papszAttrs);
         Z = mParser.getAttributeValue("z", papszAttrs, "0.0");
         WIDTH = mParser.getAttributeValue("width", papszAttrs);
         HEIGHT = mParser.getAttributeValue("height", papszAttrs);
         RX = mParser.getAttributeValue("rx", papszAttrs, "0.0");
         RY = mParser.getAttributeValue("ry", papszAttrs, "0.0");
         pRectangle = new CLRectangle();
         if (Transform != NULL)
           {
             pRectangle->parseTransformation(Transform);
           }
         if (Stroke != NULL)
           {
             pRectangle->setStroke(Stroke);
           }
         if (StrokeWidth != NULL)
           {
             double width = strToDouble(StrokeWidth, NULL);
             pRectangle->setStrokeWidth(width);
           }
         if (StrokeDashArray != NULL)
           {
             pRectangle->parseDashArray(StrokeDashArray);
           }
         if (Fill != NULL)
           {
             pRectangle->setFillColor(Fill);
           }
         if (FillRule != NULL)
           {
             std::string f(FillRule);
             if (f == "nonzero")
               {
                 pRectangle->setFillRule(CLGraphicalPrimitive2D::NONZERO);
               }
             else if (f == "evenodd")
               {
                 pRectangle->setFillRule(CLGraphicalPrimitive2D::EVENODD);
               }
             else
               {
                 pRectangle->setFillRule(CLGraphicalPrimitive2D::INHERIT);
               }
           }
         pRectangle->setCoordinatesAndSize(CLRelAbsVector(X), CLRelAbsVector(Y), CLRelAbsVector(Z), CLRelAbsVector(WIDTH), CLRelAbsVector(HEIGHT));
         pRectangle->setRadii(CLRelAbsVector(RX), CLRelAbsVector(RY));
         mCommon.pGroup->addChildElement(pRectangle);
         // delete the gradient stop again since the add method made a copy
         delete pRectangle;
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp