COPASI API: SteadyStateWidget Class Reference
SteadyStateWidget Class Reference
#include <SteadyStateWidget.h>
Public Member Functions
virtual bool runTask ()
SteadyStateWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
~SteadyStateWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
virtual void taskJacobianToggled ()
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Member Functions
void init ()
Additional Inherited Members
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 32 of file SteadyStateWidget.h.
Constructor & Destructor Documentation
SteadyStateWidget::SteadyStateWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Constructs a SteadyStateWidget which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
Definition at line 48 of file SteadyStateWidget.cpp.
References init().
     : TaskWidget(parent, name, fl)
 {
   setupUi(this);
   init();
   retranslateUi(this);
 }
SteadyStateWidget::~SteadyStateWidget ()
Definition at line 60 of file SteadyStateWidget.cpp.
 {}
Member Function Documentation
CCopasiMethod * SteadyStateWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 76 of file SteadyStateWidget.cpp.
 {return NULL; /*CTSSMethod::createTSSMethod(type);*/}
void SteadyStateWidget::init () private
Definition at line 63 of file SteadyStateWidget.cpp.
References TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, CQTaskHeaderWidget::setTaskName(), and CQTaskMethodWidget::showMethodParameters().
Referenced by SteadyStateWidget().
 {
   mpHeaderWidget->setTaskName("Steady State");
   SteadyStateWidgetLayout->insertWidget(0, mpHeaderWidget); // header
   // SteadyStateWidgetLayout->insertSpacing(1, 14);      // space between header and body
   mpMethodWidget->showMethodParameters(true);
   SteadyStateWidgetLayout->addWidget(mpMethodWidget);
   SteadyStateWidgetLayout->addWidget(mpBtnWidget);      // 'footer'
 }
bool SteadyStateWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 136 of file SteadyStateWidget.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiTask::getMethod(), CCopasiTask::getProblem(), CSteadyStateProblem::isJacobianRequested(), CSteadyStateProblem::isStabilityAnalysisRequested(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), TaskWidget::mChanged, and CopasiWidget::mKey.
 {
   loadCommon();
   loadMethod();
   CSteadyStateTask* mSteadyStateTask =
     dynamic_cast<CSteadyStateTask *>(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (mSteadyStateTask == NULL)
     return false;
   CSteadyStateProblem* steadystateproblem =
     dynamic_cast<CSteadyStateProblem *>(mSteadyStateTask->getProblem());
   if (steadystateproblem == NULL)
     return false;
   CSteadyStateMethod* steadystatemethod =
     dynamic_cast<CSteadyStateMethod *>(mSteadyStateTask->getMethod());
   if (steadystatemethod == NULL)
     return false;
   bool bJacobian = steadystateproblem->isJacobianRequested();
   bool bStatistics = steadystateproblem->isStabilityAnalysisRequested();
   taskJacobian->setChecked(bJacobian);
   if (bJacobian)
     {
       taskStability->setEnabled(true);
       taskStability->setChecked(bStatistics);
     }
   mChanged = false;
   return true;
 }
bool SteadyStateWidget::runTask () virtual
Implements TaskWidget.
Definition at line 79 of file SteadyStateWidget.cpp.
References TaskWidget::commonBeforeRunTask(), and TaskWidget::commonRunTask().
Referenced by SliderDialog::runSteadyStateTask().
 {
   bool success = true;
   if (!commonBeforeRunTask()) return false;
   if (!commonRunTask()) success = false;
   return success;
 }
bool SteadyStateWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 174 of file SteadyStateWidget.cpp.
References CCopasiDataModel::changed(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiTask::getMethod(), CCopasiTask::getProblem(), TaskWidget::mChanged, CopasiWidget::mKey, CopasiWidget::mpDataModel, TaskWidget::saveCommon(), TaskWidget::saveMethod(), CSteadyStateProblem::setJacobianRequested(), and CSteadyStateProblem::setStabilityAnalysisRequested().
 {
   saveCommon();
   saveMethod();
   CSteadyStateTask* mSteadyStateTask =
     dynamic_cast<CSteadyStateTask *>(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (mSteadyStateTask == NULL)
     return false;
   CSteadyStateProblem* steadystateproblem =
     dynamic_cast<CSteadyStateProblem *>(mSteadyStateTask->getProblem());
   if (steadystateproblem == NULL)
     return false;
   CSteadyStateMethod* steadystatemethod =
     dynamic_cast<CSteadyStateMethod *>(mSteadyStateTask->getMethod());
   if (steadystatemethod == NULL)
     return false;
   bool bJacobian = taskJacobian->isChecked();
   bool bStatistics = taskStability->isChecked();
   steadystateproblem->setJacobianRequested(bJacobian);
   steadystateproblem->setStabilityAnalysisRequested(bStatistics);
   if (mChanged)
     {
       if (mpDataModel != NULL)
         {
           mpDataModel->changed();
         }
       mChanged = false;
     }
   return true;
 }
bool SteadyStateWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 90 of file SteadyStateWidget.cpp.
References ListViews::findWidgetFromId(), CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, CCopasiParameterGroup::getParameter(), CSteadyStateTask::getResult(), CCopasiParameter::getValue(), CQSteadyStateResult::loadResult(), CopasiWidget::mpListView, TaskWidget::mpMethod, CopasiWidget::mpObject, CCopasiParameter::Value::pBOOL, pResult, and ListViews::switchToOtherWidget().
 {
   bool success = false;
   CSteadyStateTask* pSteadyStateTask = dynamic_cast<CSteadyStateTask *>(mpObject);
   if (pSteadyStateTask == NULL)
     return success;
   switch (pSteadyStateTask->getResult())
     {
       case CSteadyStateMethod::found:
       case CSteadyStateMethod::foundEquilibrium:
         success = true;
         break;
       case CSteadyStateMethod::foundNegative:
         if (mpMethod != NULL)
           {
             const CCopasiParameter *pParm = mpMethod->getParameter("Accept Negative Concentrations");
             if (pParm != NULL)
               {
                 success = *pParm->getValue().pBOOL;
               }
           }
         break;
       default:
         break;
     }
   CQSteadyStateResult *pResult =
     dynamic_cast< CQSteadyStateResult * >(mpListView->findWidgetFromId(211));
   if (pResult)
     pResult->loadResult();
   if (success && isVisible())
     mpListView->switchToOtherWidget(211, ""); //change to the results window
   return success;
 }
void SteadyStateWidget::taskJacobianToggled () protected virtual slot
Definition at line 216 of file SteadyStateWidget.cpp.
 {
   if (!taskJacobian->isChecked())
     {
       taskStability->setChecked(false);
       taskStability->setEnabled(false);
     }
   else taskStability->setEnabled(true);
 }
The documentation for this class was generated from the following files:
SteadyStateWidget.h
SteadyStateWidget.cpp