COPASI API: CQLyapResultWidget Class Reference
CQLyapResultWidget Class Reference
#include <CQLyapResultWidget.h>
Public Member Functions
CQLyapResultWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQLyapResultWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void saveToFile ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
bool loadFromBackend ()
Private Member Functions
void init ()
Private Attributes
CLyapTask * mpTask
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 30 of file CQLyapResultWidget.h.
Constructor & Destructor Documentation
CQLyapResultWidget::CQLyapResultWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 36 of file CQLyapResultWidget.cpp.
References init().
   : CopasiWidget(parent, name, fl)
 {
   setupUi(this);
   init();
 }
CQLyapResultWidget::~CQLyapResultWidget ()
Definition at line 47 of file CQLyapResultWidget.cpp.
 {}
Member Function Documentation
bool CQLyapResultWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 155 of file CQLyapResultWidget.cpp.
References loadFromBackend().
 {
   return loadFromBackend();
 }
void CQLyapResultWidget::init () private
Definition at line 50 of file CQLyapResultWidget.cpp.
Referenced by CQLyapResultWidget().
 {
   /*
     mSaveButton->setEnabled(false);
     mSaveButton->hide();
   */
 }
bool CQLyapResultWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 150 of file CQLyapResultWidget.cpp.
 {
   return true;
 }
bool CQLyapResultWidget::loadFromBackend () protected
Definition at line 60 of file CQLyapResultWidget.cpp.
References CLyapTask::averageDivergence(), C_FLOAT64, C_INT32, CLyapTask::exponents(), CCopasiRootContainer::getDatamodelList(), CLyapProblem::getExponentNumber(), CCopasiTask::getProblem(), CLyapTask::modelVariablesInResult(), mpTask, CLyapTask::numberOfExponentsCalculated(), CLyapTask::resultAvailable(), CLyapTask::resultHasDivergence(), and CLyapTask::sumOfExponents().
Referenced by enterProtected(), and update().
 {
   //bool success = true;
   //std::ostringstream os;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   mpTask = dynamic_cast<CLyapTask*>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Lyapunov Exponents"]);
   if (!mpTask) return false;
   CLyapProblem * pProblem = dynamic_cast< CLyapProblem * >(mpTask->getProblem());
   if (!pProblem) return false;
   if (!mpTask->resultAvailable())
     {
       mTableExponents->setEnabled(false);
       mTableExponents->setRowCount(0);
       mLineEditSum->setEnabled(false);
       mLineEditSum->setText("");
       mLineEditDivergence->setEnabled(false);
       mLineEditDivergence->setText("");
       mLabelComment->setText("No result available.");
       return false;
     }
   mTableExponents->setEnabled(true);
   mLineEditSum->setEnabled(true);
   mLineEditDivergence->setEnabled(true);
   unsigned C_INT32 i, imax = pProblem->getExponentNumber();
   mTableExponents->setRowCount(imax);
   for (i = 0; i < imax; ++i)
     {
       QTableWidgetItem *pItem = mTableExponents->item(i, 0);
       if (pItem == NULL)
         {
           pItem = new QTableWidgetItem(QString::number(mpTask->exponents()[i]));
           pItem->setFlags(Qt::ItemIsDragEnabled | Qt::ItemIsUserCheckable | Qt::ItemIsEnabled);
           mTableExponents->setItem(i, 0, pItem);
         }
       else
         {
           pItem->setText(QString::number(mpTask->exponents()[i]));
         }
     }
   mLineEditSum->setText(QString::number(mpTask->sumOfExponents()));
   if (mpTask->resultHasDivergence())
     {
       mLineEditDivergence->setEnabled(true);
       mLineEditDivergence->setText(QString::number(mpTask->averageDivergence()));
     }
   else
     {
       mLineEditDivergence->setEnabled(false);
       mLineEditDivergence->setText("");
     }
   //comment
   mLabelComment->setText("");
   if (mpTask->resultHasDivergence()
       && (mpTask->modelVariablesInResult() == mpTask->numberOfExponentsCalculated()))
     {
       if ((mpTask->sumOfExponents() < 0.0) && (mpTask->averageDivergence() < 0.0))
         {
           C_FLOAT64 factor = mpTask->averageDivergence() / mpTask->sumOfExponents();
           if (factor > 1.01)
             mLabelComment->setText("Warning: Divergence differs from sum of exponents. This may indicate that the strongly negative exponents are calculated inaccuratly.");
         }
     }
   return true;
 }
void CQLyapResultWidget::saveToFile () protected slot
Definition at line 160 of file CQLyapResultWidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CopasiFileDialog::getSaveFileName(), mpTask, CLyapTask::printResult(), and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail())
     return;
   if (mpTask != NULL)
     mpTask->printResult(&file);
   return;
 }
bool CQLyapResultWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 141 of file CQLyapResultWidget.cpp.
References loadFromBackend().
 {
   if (this->isVisible())
     return loadFromBackend();
   else
     return true;
 }
Member Data Documentation
CLyapTask* CQLyapResultWidget::mpTask private
Definition at line 52 of file CQLyapResultWidget.h.
Referenced by loadFromBackend(), and saveToFile().
The documentation for this class was generated from the following files:
CQLyapResultWidget.h
CQLyapResultWidget.cpp