COPASI API: CRDFTriplet.cpp File Reference
CRDFTriplet.cpp File Reference
#include "copasi.h"
#include "CRDFGraph.h"
#include "CRDFSubject.h"
Functions
std::ostream & operator<< (std::ostream &os, const CRDFTriplet &triplet)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CRDFTriplet & triplet)
Definition at line 56 of file CRDFTriplet.cpp.
References CRDFNode::getObject(), CRDFNode::getSubject(), CRDFPredicate::getURI(), CRDFTriplet::pObject, CRDFTriplet::Predicate, and CRDFTriplet::pSubject.
 {
   if (triplet)
     {
       os << triplet.pSubject->getSubject() << ", ";
       os << triplet.Predicate.getURI() << ", ";
       os << triplet.pObject->getObject() << std::endl;
     }
   else
     os << "Invalid Triplet" << std::endl;
   return os;
 }