COPASI API: test000086 Class Reference
test000086 Class Reference
#include <test000086.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_import_compartment_units_1 ()
void test_import_compartment_units_10 ()
void test_import_compartment_units_11 ()
void test_import_compartment_units_2 ()
void test_import_compartment_units_3 ()
void test_import_compartment_units_4 ()
void test_import_compartment_units_5 ()
void test_import_compartment_units_6 ()
void test_import_compartment_units_7 ()
void test_import_compartment_units_8 ()
void test_import_compartment_units_9 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING10
static const char * MODEL_STRING11
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static const char * MODEL_STRING7
static const char * MODEL_STRING8
static const char * MODEL_STRING9
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_compartment_units_1)
CPPUNIT_TEST (test_import_compartment_units_2)
CPPUNIT_TEST (test_import_compartment_units_3)
CPPUNIT_TEST (test_import_compartment_units_4)
CPPUNIT_TEST (test_import_compartment_units_5)
CPPUNIT_TEST (test_import_compartment_units_6)
CPPUNIT_TEST (test_import_compartment_units_7)
CPPUNIT_TEST (test_import_compartment_units_8)
CPPUNIT_TEST (test_import_compartment_units_9)
CPPUNIT_TEST (test_import_compartment_units_10)
CPPUNIT_TEST (test_import_compartment_units_11)
CPPUNIT_TEST_SUITE (test000086)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 28 of file test000086.h.
Member Function Documentation
test000086::CPPUNIT_TEST (test_import_compartment_units_1) private
test000086::CPPUNIT_TEST (test_import_compartment_units_2) private
test000086::CPPUNIT_TEST (test_import_compartment_units_3) private
test000086::CPPUNIT_TEST (test_import_compartment_units_4) private
test000086::CPPUNIT_TEST (test_import_compartment_units_5) private
test000086::CPPUNIT_TEST (test_import_compartment_units_6) private
test000086::CPPUNIT_TEST (test_import_compartment_units_7) private
test000086::CPPUNIT_TEST (test_import_compartment_units_8) private
test000086::CPPUNIT_TEST (test_import_compartment_units_9) private
test000086::CPPUNIT_TEST (test_import_compartment_units_10) private
test000086::CPPUNIT_TEST (test_import_compartment_units_11) private
test000086::CPPUNIT_TEST_SUITE (test000086) private
test000086::CPPUNIT_TEST_SUITE_END () private
void test000086::setUp ()
Definition at line 36 of file test000086.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000086::tearDown ()
Definition at line 44 of file test000086.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000086::test_import_compartment_units_1 ()
Definition at line 49 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING1, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
void test000086::test_import_compartment_units_10 ()
Definition at line 480 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING10, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING10));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
void test000086::test_import_compartment_units_11 ()
Definition at line 531 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING11, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING11));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 2);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 0);
 }
void test000086::test_import_compartment_units_2 ()
Definition at line 100 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING2, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
void test000086::test_import_compartment_units_3 ()
Definition at line 151 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING3, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING3));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 0);
 }
void test000086::test_import_compartment_units_4 ()
Definition at line 202 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING4, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING4));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
void test000086::test_import_compartment_units_5 ()
Definition at line 253 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING5, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING5));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
void test000086::test_import_compartment_units_6 ()
Definition at line 304 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING6, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING6));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // make sure there is no message about units not being consistent
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 24);
       // make sure all units were imported
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 55);
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 66);
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 79);
       ++i;
     }
 }
void test000086::test_import_compartment_units_7 ()
Definition at line 327 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING7, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING7));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
void test000086::test_import_compartment_units_8 ()
Definition at line 378 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING8, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING8));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 0);
 }
void test000086::test_import_compartment_units_9 ()
Definition at line 429 of file test000086.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING9, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING9));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found66 == 0);
   CPPUNIT_ASSERT(found79 == 1);
 }
Member Data Documentation
const char * test000086::MODEL_STRING1 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a compartment with length units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"length\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 49 of file test000086.h.
Referenced by test_import_compartment_units_1().
const char * test000086::MODEL_STRING10 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with substance units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"substance\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 76 of file test000086.h.
Referenced by test_import_compartment_units_10().
const char * test000086::MODEL_STRING11 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with two compartments. One has no unit, the other uses dimensionless as the unit.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  />"
  "      <compartment id=\"compartment_2\" name=\"compartment_2\" size=\"1\" spatialDimensions=\"0\"  units=\"dimensionless\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 79 of file test000086.h.
Referenced by test_import_compartment_units_11().
const char * test000086::MODEL_STRING2 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a compartment with metre units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"metre\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 52 of file test000086.h.
Referenced by test_import_compartment_units_2().
const char * test000086::MODEL_STRING3 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a compartment with no units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  />"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 55 of file test000086.h.
Referenced by test_import_compartment_units_3().
const char * test000086::MODEL_STRING4 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with volume units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"volume\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 58 of file test000086.h.
Referenced by test_import_compartment_units_4().
const char * test000086::MODEL_STRING5 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with area units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 61 of file test000086.h.
Referenced by test_import_compartment_units_5().
const char * test000086::MODEL_STRING6 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with dimensionless units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"dimensionless\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 64 of file test000086.h.
Referenced by test_import_compartment_units_6().
const char * test000086::MODEL_STRING7 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with m^2 units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_dimensionless\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"0\" exponent=\"2\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"my_dimensionless\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 67 of file test000086.h.
Referenced by test_import_compartment_units_7().
const char * test000086::MODEL_STRING8 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with dimensionless units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_dimensionless\">"
  "        <listOfUnits>"
  "          <unit kind=\"dimensionless\" scale=\"0\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"my_dimensionless\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 70 of file test000086.h.
Referenced by test_import_compartment_units_8().
const char * test000086::MODEL_STRING9 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with a 0D compartment with mole units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_dimensionless\">"
  "        <listOfUnits>"
  "          <unit kind=\"mole\" scale=\"0\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"0\"  units=\"my_dimensionless\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 73 of file test000086.h.
Referenced by test_import_compartment_units_9().
CCopasiDataModel * test000086::pCOPASIDATAMODEL = NULL static protected
Definition at line 81 of file test000086.h.
Referenced by setUp(), test_import_compartment_units_1(), test_import_compartment_units_10(), test_import_compartment_units_11(), test_import_compartment_units_2(), test_import_compartment_units_3(), test_import_compartment_units_4(), test_import_compartment_units_5(), test_import_compartment_units_6(), test_import_compartment_units_7(), test_import_compartment_units_8(), and test_import_compartment_units_9().
The documentation for this class was generated from the following files:
test000086.h
test000086.cpp