COPASI API: CStateRecord Class Reference
CStateRecord Class Reference
#include <CInterpolation.h>
Public Member Functions
CStateRecord ()
CStateRecord (size_t reactionNum)
CStateRecord (const CStateRecord &src)
C_FLOAT64 * getArray () const
const size_t & getArrayLen () const
const C_FLOAT64 & getSlowPropensitySum () const
const C_FLOAT64 & getTime () const
CStateRecord & operator= (const CStateRecord &rhs)
~CStateRecord ()
Private Attributes
C_FLOAT64 * mpValues
size_t mSize
Friends
void printRecord (const CStateRecord &record)
Detailed Description
Definition at line 16 of file CInterpolation.h.
Constructor & Destructor Documentation
CStateRecord::CStateRecord ()
Constructor
Definition at line 21 of file CInterpolation.cpp.
                           :
   mpValues(NULL),
   mSize(0)
 {}
CStateRecord::CStateRecord (size_t reactionNum)
Assignment Constructor
Definition at line 26 of file CInterpolation.cpp.
                                            :
   mpValues(new C_FLOAT64[speciesNum + 2]),
   mSize(speciesNum + 2)
 {}
CStateRecord::CStateRecord (const CStateRecord & src)
Copy constructor
Parameters
const CStateRecord & src
Definition at line 31 of file CInterpolation.cpp.
References C_FLOAT64, mpValues, and mSize.
                                                   :
   mpValues(new C_FLOAT64[src.mSize]),
   mSize(src.mSize)
 {
   memcpy(mpValues, src.mpValues, sizeof(C_FLOAT64)*mSize);
 }
CStateRecord::~CStateRecord ()
Destructor
Definition at line 38 of file CInterpolation.cpp.
References mpValues, and pdeletev.
Referenced by CInterpolation::~CInterpolation().
 {
   pdeletev(mpValues);
 }
Member Function Documentation
C_FLOAT64 * CStateRecord::getArray () const
Retrieve the pointer of the C_FLOAT64 array recording all the values,
Returns
const C_FLOAT64 *mpValue
Definition at line 60 of file CInterpolation.cpp.
References mpValues.
Referenced by CInterpolation::calculateFiringTime(), CInterpolation::calculateState(), CHybridMethodODE45::doInverseInterpolation(), and CInterpolation::recordState().
 {
   return mpValues;
 }
const size_t & CStateRecord::getArrayLen () const
Retrieve the attibute mSize, the length of the array
Definition at line 75 of file CInterpolation.cpp.
References mSize.
Referenced by CInterpolation::calculateState(), and CInterpolation::recordState().
 {
   return mSize;
 }
const C_FLOAT64 & CStateRecord::getSlowPropensitySum () const
Retrieve the Sum of Slow Reaction Propensities
Returns
const C_FLOAT64 & mpValue(mSize-1)
Definition at line 70 of file CInterpolation.cpp.
References mpValues, and mSize.
Referenced by CInterpolation::calculateFiringTime().
 {
   return mpValues[mSize - 1];
 }
const C_FLOAT64 & CStateRecord::getTime () const
Retrive the time of the state
Returns
const C_FLOAT64 & mpValue(0)
Definition at line 65 of file CInterpolation.cpp.
References mpValues.
Referenced by CInterpolation::calculateFiringTime(), CInterpolation::calculateState(), and CHybridMethodODE45::doInverseInterpolation().
 {
   return mpValues[0];
 }
CStateRecord & CStateRecord::operator= (const CStateRecord & rhs)
Assignment operator
Parameters
const CStateRecord & rhs
Returns
CStateRecord & lhs
Definition at line 43 of file CInterpolation.cpp.
References C_FLOAT64, mpValues, mSize, and pdeletev.
 {
   if (this != &rhs)
     {
       if (mSize != rhs.mSize)
         {
           pdeletev(mpValues);
           mpValues = new C_FLOAT64[rhs.mSize];
           mSize    = rhs.mSize;
         }
       memcpy(mpValues, rhs.mpValues, sizeof(C_FLOAT64)*mSize);
     }
   return *this;
 }
Friends And Related Function Documentation
void printRecord (const CStateRecord & record) friend
Friend Function for Debug
Definition at line 81 of file CInterpolation.cpp.
 {
   for (size_t i = 0; i < record.mSize; i++)
     {
       std::cout << record.mpValues[i] << " ";
     }
   std::cout << std::endl;
   return;
 }
Member Data Documentation
C_FLOAT64* CStateRecord::mpValues private
Array of values
Definition at line 87 of file CInterpolation.h.
Referenced by CStateRecord(), getArray(), getSlowPropensitySum(), getTime(), operator=(), printRecord(), and ~CStateRecord().
size_t CStateRecord::mSize private
Size of array
Definition at line 92 of file CInterpolation.h.
Referenced by CStateRecord(), getArrayLen(), getSlowPropensitySum(), operator=(), and printRecord().
The documentation for this class was generated from the following files:
CInterpolation.h
CInterpolation.cpp