COPASI API: CTimeSeries Class Reference
CTimeSeries Class Reference
#include <CTimeSeries.h>
Public Member Functions
void allocate (const size_t &steps)
void clear ()
virtual bool compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel *pDataModel)
CTimeSeries ()
CTimeSeries (const CTimeSeries &src)
virtual void finish ()
C_FLOAT64 getConcentrationData (const size_t &step, const size_t &variable) const
const C_FLOAT64 & getData (const size_t &step, const size_t &variable) const
const std::string & getKey (const size_t &variable) const
const size_t & getNumVariables () const
const size_t & getRecordedSteps () const
std::string getSBMLId (const size_t &variable, const CCopasiDataModel *pDataModel) const
const std::string & getTitle (const size_t &variable) const
void increaseAllocation ()
virtual void output (const Activity &activity)
int save (const std::string &fileName, bool writeConcentrations=false, const std::string &separator="\t") const
virtual void separate (const Activity &activity)
~CTimeSeries ()
Public Member Functions inherited from COutputInterface
virtual void close ()
COutputInterface ()
COutputInterface (const COutputInterface &src)
virtual const std::set< const
CCopasiObject * > & getObjects () const
virtual ~COutputInterface ()
Private Member Functions
CTimeSeries & operator= (const CTimeSeries &)
Private Attributes
size_t mAllocatedSteps
CVector< size_t > mCompartment
std::vector< std::string > mKeys
C_FLOAT64 mNumberToQuantityFactor
C_FLOAT64 * mpEnd
C_FLOAT64 * mpIt
CVector< size_t > mPivot
const CState * mpState
size_t mRecordedSteps
std::vector< std::string > mTitles
Static Private Attributes
static C_FLOAT64 mDummyFloat
static std::string mDummyString
Additional Inherited Members
Public Types inherited from COutputInterface
enum Activity { BEFORE = 0x01, DURING = 0x02, AFTER = 0x04 }
Protected Types inherited from CMatrix< C_FLOAT64 >
typedef C_FLOAT64 elementType
Protected Member Functions inherited from CMatrix< C_FLOAT64 >
bool applyPivot (const CVector< size_t > &pivot)
virtual C_FLOAT64 * array ()
virtual const C_FLOAT64 * array () const
CMatrix (size_t rows=0, size_t cols=0)
CMatrix (const CMatrix< C_FLOAT64 > &src)
virtual size_t numCols () const
virtual size_t numRows () const
virtual elementType & operator() (const size_t &row, const size_t &col)
virtual const elementType & operator() (const size_t &row, const size_t &col) const
virtual CMatrix< C_FLOAT64 > & operator= (const CMatrix< C_FLOAT64 > &rhs)
virtual CMatrix< C_FLOAT64 > & operator= (const C_FLOAT64 &value)
virtual C_FLOAT64 * operator[] (size_t row)
virtual const C_FLOAT64 * operator[] (size_t row) const
virtual void resize (size_t rows, size_t cols, const bool &copy=false)
virtual size_t size () const
virtual ~CMatrix ()
Protected Attributes inherited from COutputInterface
std::set< const CCopasiObject * > mObjects
Protected Attributes inherited from CMatrix< C_FLOAT64 >
C_FLOAT64 * mArray
size_t mCols
size_t mRows
Detailed Description
Definition at line 28 of file CTimeSeries.h.
Constructor & Destructor Documentation
CTimeSeries::CTimeSeries ()
Default constructor
Definition at line 40 of file CTimeSeries.cpp.
                         :
   COutputInterface(),
   CMatrix< C_FLOAT64 >(),
   mAllocatedSteps(0),
   mRecordedSteps(0),
   mpIt(mArray),
   mpEnd(mArray + size()),
   mpState(NULL),
   mTitles(),
   mCompartment(),
   mPivot(),
   mKeys(),
   mNumberToQuantityFactor(0.0)
 {}
CTimeSeries::CTimeSeries (const CTimeSeries & src)
Copy constructor
Parameters
const CTimeSeries & src
Definition at line 55 of file CTimeSeries.cpp.
                                                :
   COutputInterface(src),
   CMatrix< C_FLOAT64 >(src),
   mAllocatedSteps(src.mAllocatedSteps),
   mRecordedSteps(src.mRecordedSteps),
   mpIt(mArray + mRecordedSteps * mCols),
   mpEnd(mArray + size()),
   mpState(src.mpState),
   mTitles(src.mTitles),
   mCompartment(src.mCompartment),
   mPivot(src.mPivot),
   mKeys(src.mKeys),
   mNumberToQuantityFactor(src.mNumberToQuantityFactor)
 {}
CTimeSeries::~CTimeSeries ()
Destructor
Definition at line 70 of file CTimeSeries.cpp.
 {}
Member Function Documentation
void CTimeSeries::allocate (const size_t & steps)
The maximal number of recorded steps. This must be set before compiling
Parameters
const size_t & steps
Definition at line 73 of file CTimeSeries.cpp.
References mAllocatedSteps.
Referenced by CQGLNetworkPainter::createDataSets(), CTSSATask::initialize(), CTrajectoryTask::initialize(), and CCrossSectionTask::initialize().
 {
   // The actual allocation is deferred to compile
   mAllocatedSteps = steps;
 }
void CTimeSeries::clear ()
Clear the time series
Definition at line 96 of file CTimeSeries.cpp.
References mAllocatedSteps, CMatrix< C_FLOAT64 >::mArray, mCompartment, mKeys, mNumberToQuantityFactor, COutputInterface::mObjects, mpEnd, mpIt, mPivot, mpState, mRecordedSteps, CMatrix< C_FLOAT64 >::mRows, mTitles, CMatrix< CType >::resize(), CVector< CType >::resize(), and CMatrix< C_FLOAT64 >::size().
Referenced by CTrajectoryTask::initialize(), CTSSATask::initialize(), and CCrossSectionTask::initialize().
 {
   mObjects.clear();
   CMatrix< C_FLOAT64 >::resize(0, 0);
   mAllocatedSteps = mRows;
   mRecordedSteps = 0;
   mpIt = mArray;
   mpEnd = mArray + size();
   mpState = NULL;
   mTitles.clear();
   mCompartment.resize(0);
   mPivot.resize(0);
   mKeys.clear();
   mNumberToQuantityFactor = 0.0;
 }
bool CTimeSeries::compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel * pDataModel) virtual
compile the object list from name vector
Parameters
std::vector< CCopasiContainer * > listOfContainer
const CCopasiDataModel* pDataModel
Returns
bool success
Reimplemented from COutputInterface.
Definition at line 113 of file CTimeSeries.cpp.
References CVectorCore< CType >::array(), C_INVALID_INDEX, CStateTemplate::endFixed(), CCopasiObject::getCN(), CMetab::getCompartment(), CMetabNameInterface::getDisplayName(), CStateTemplate::getEntities(), CStateTemplate::getIndex(), CModel::getKey(), CCopasiDataModel::getModel(), CModel::getNumber2QuantityFactor(), CModel::getState(), CModel::getStateTemplate(), CStateTemplate::getUserOrder(), mAllocatedSteps, CMatrix< C_FLOAT64 >::mArray, mCompartment, mKeys, mNumberToQuantityFactor, COutputInterface::mObjects, mpEnd, mpIt, mPivot, mpState, mRecordedSteps, mTitles, CCopasiDataModel::ObjectFromName(), CMatrix< CType >::resize(), CVector< CType >::resize(), CVectorCore< CType >::size(), and CMatrix< C_FLOAT64 >::size().
Referenced by CQGLNetworkPainter::createDataSets().
 {
   const CModel * pModel =
     dynamic_cast< const CModel * >(pDataModel->ObjectFromName(listOfContainer, pDataModel->getModel()->getCN()));
   if (pModel == NULL)
     return false;
   mpState = & pModel->getState();
   const CStateTemplate & Template = pModel->getStateTemplate();
   // We store all variables of the system.
   // The reason for this is that events will be able to change even fixed values.
   CModelEntity *const* it = Template.getEntities();
   CModelEntity *const* end = Template.endFixed();
   size_t i, imax = end - it;
   CMatrix< C_FLOAT64 >::resize(mAllocatedSteps + 1, imax);
   mObjects.clear();
   mPivot.resize(imax);
   mTitles.resize(imax);
   mCompartment.resize(imax);
   mKeys.resize(imax);
   mRecordedSteps = 0;
   mpIt = mArray;
   mpEnd = mArray + size();
   mCompartment = C_INVALID_INDEX;
   mNumberToQuantityFactor = pModel->getNumber2QuantityFactor();
   const CMetab * pMetab;
   for (i = 0; it != end; ++i, ++it)
     {
       if ((pMetab = dynamic_cast< const CMetab *>(*it)) != NULL)
         {
           mTitles[i] = CMetabNameInterface::getDisplayName(pModel, *pMetab, false);
           mCompartment[i] = Template.getIndex(pMetab->getCompartment());
         }
       else
         {
           mTitles[i] = (*it)->getObjectDisplayName();
         }
       mKeys[i] = (*it)->getKey();
       mObjects.insert((*it)->getValueReference());
     }
   mTitles[0] = "Time";
   mKeys[0] = pModel->getKey();
   const size_t * pUserOrder = Template.getUserOrder().array();
   const size_t * pUserOrderEnd = pUserOrder + Template.getUserOrder().size();
   it = Template.getEntities();
   for (i = 0; pUserOrder != pUserOrderEnd; ++pUserOrder)
     mPivot[i++] = *pUserOrder;
   return true;
 }
void CTimeSeries::finish () virtual
Finish the output
Reimplemented from COutputInterface.
Definition at line 223 of file CTimeSeries.cpp.
 {}
C_FLOAT64 CTimeSeries::getConcentrationData (const size_t & step, const size_t & variable) const
Retrieve the data (concentration for species) for the indexed step and variable
Parameters
const size_t & step
const size_t & variable
Returns
const C_FLOAT64 & data
Definition at line 243 of file CTimeSeries.cpp.
References C_INVALID_INDEX, CMatrix< C_FLOAT64 >::mArray, CMatrix< C_FLOAT64 >::mCols, mCompartment, mDummyFloat, mNumberToQuantityFactor, mPivot, and mRecordedSteps.
Referenced by CQGLNetworkPainter::createDataSets(), CQTimeSeriesDM::data(), and save().
 {
   if (step < mRecordedSteps && var < mCols)
     {
       const size_t & Col = mPivot[var];
       if (mCompartment[Col] != C_INVALID_INDEX)
         return *(mArray + step * mCols + Col) * mNumberToQuantityFactor / *(mArray + step * mCols + mCompartment[Col]);
       else
         return *(mArray + step * mCols + Col);
     }
   return mDummyFloat;
 }
const C_FLOAT64 & CTimeSeries::getData (const size_t & step, const size_t & variable) const
Retrieve the data (particle number for species) for the indexed step and variable
Parameters
const size_t & step
const size_t & variable
Returns
const C_FLOAT64 & data
Definition at line 234 of file CTimeSeries.cpp.
References CMatrix< C_FLOAT64 >::mArray, CMatrix< C_FLOAT64 >::mCols, mDummyFloat, mPivot, and mRecordedSteps.
Referenced by CQTimeSeriesDM::data(), QTimeCourseAnimation::getMax(), QTimeCourseAnimation::getValue(), and save().
 {
   if (step < mRecordedSteps && var < mCols)
     return *(mArray + step * mCols + mPivot[var]);
   return mDummyFloat;
 }
const std::string & CTimeSeries::getKey (const size_t & variable) const
Retrieve the key of the model entity of the indexed variable (column)
Parameters
const size_t & variable
Returns
const std::string & key
Definition at line 267 of file CTimeSeries.cpp.
References CMatrix< C_FLOAT64 >::mCols, mDummyString, mKeys, and mPivot.
Referenced by CQGLNetworkPainter::createDataSets(), QTimeCourseAnimation::getIndex(), and getSBMLId().
 {
   if (var < mCols)
     return mKeys[mPivot[var]];
   return mDummyString;
 }
const size_t & CTimeSeries::getNumVariables () const
Retrieve the number of variables (columns)
Returns
size_t & numVariables
Definition at line 231 of file CTimeSeries.cpp.
References CMatrix< C_FLOAT64 >::mCols.
Referenced by CQTimeSeriesDM::columnCount(), CQGLNetworkPainter::createDataSets(), QTimeCourseAnimation::getIndex(), QTimeCourseAnimation::getMax(), and save().
 {return mCols;}
const size_t & CTimeSeries::getRecordedSteps () const
Retrieve the number of time steps (rows)
Returns
const size_t & recordedSteps
Definition at line 228 of file CTimeSeries.cpp.
References mRecordedSteps.
Referenced by CQGLNetworkPainter::createDataSets(), QTimeCourseAnimation::getMax(), QTimeCourseAnimation::getScales(), QTimeCourseAnimation::initialize(), and CQTimeSeriesDM::rowCount().
 {return mRecordedSteps;}
std::string CTimeSeries::getSBMLId (const size_t & variable, const CCopasiDataModel * pDataModel) const
get the id of the SBML object corresponding to column indexed by variable. If there is no corresponding SBML object (e.g. if the model comes from a COPASI file) the empty string is returned.
Parameters
const size_t & variable
Returns
const std::string SBMLId
Definition at line 275 of file CTimeSeries.cpp.
References CKeyFactory::get(), getKey(), CCopasiRootContainer::getKeyFactory(), and mDummyString.
 {
   std::string key = getKey(var);
   std::string result("");
   if (key != mDummyString)
     {
       const CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(key);
       if (pObject != NULL)
         {
           std::map<CCopasiObject*, SBase*>::const_iterator pos = const_cast<CCopasiDataModel*>(pDataModel)->getCopasi2SBMLMap().find(const_cast<CCopasiObject*>(pObject));
           if (pos != const_cast<CCopasiDataModel*>(pDataModel)->getCopasi2SBMLMap().end())
             {
               const SBase* pSBMLObject = pos->second;
               const Compartment* pSBMLCompartment = NULL;
               const Species* pSBMLSpecies = NULL;
               const Parameter* pSBMLParameter = NULL;
               const Model* pSBMLModel = NULL;
               switch (pSBMLObject->getTypeCode())
                 {
                   case SBML_COMPARTMENT:
                     pSBMLCompartment = dynamic_cast<const Compartment*>(pSBMLObject);
                     if (pSBMLCompartment && pSBMLCompartment->isSetId())
                       {
                         result = pSBMLCompartment->getId();
                       }
                     break;
                   case SBML_SPECIES:
                     pSBMLSpecies = dynamic_cast<const Species*>(pSBMLObject);
                     if (pSBMLSpecies && pSBMLSpecies->isSetId())
                       {
                         result = pSBMLSpecies->getId();
                       }
                     break;
                   case SBML_PARAMETER:
                     pSBMLParameter = dynamic_cast<const Parameter*>(pSBMLObject);
                     if (pSBMLParameter && pSBMLParameter->isSetId())
                       {
                         result = pSBMLParameter->getId();
                       }
                     break;
                   case SBML_MODEL:
                     pSBMLModel = dynamic_cast<const Model*>(pSBMLObject);
                     if (pSBMLModel && pSBMLModel->isSetId())
                       {
                         result = pSBMLModel->getId();
                       }
                     break;
                   default:
                     break;
                 }
             }
         }
     }
   return result;
 }
const std::string & CTimeSeries::getTitle (const size_t & variable) const
Retrieve the title of the indexed variable (column)
Parameters
const size_t & variable
Returns
const std::string & title
Definition at line 259 of file CTimeSeries.cpp.
References CMatrix< C_FLOAT64 >::mCols, mDummyString, mPivot, and mTitles.
Referenced by CQGLNetworkPainter::createDataSets(), CQTimeSeriesDM::headerData(), and save().
 {
   if (var < mCols)
     return mTitles[mPivot[var]];
   return mDummyString;
 }
void CTimeSeries::increaseAllocation ()
Increase the allocated space for the time series.
Definition at line 79 of file CTimeSeries.cpp.
References mAllocatedSteps, CMatrix< C_FLOAT64 >::mArray, CMatrix< C_FLOAT64 >::mCols, mpEnd, mpIt, mRecordedSteps, CMatrix< CType >::resize(), and CMatrix< C_FLOAT64 >::size().
Referenced by output(), and separate().
 {
   size_t diff;
   diff = mAllocatedSteps / 4;
   if (diff < 10)
     diff = 10;
   else if (diff > 10000)
     diff = 10000;
   mAllocatedSteps += diff;
   CMatrix< C_FLOAT64 >::resize(mAllocatedSteps, mCols, true);
   mpIt = mArray + mRecordedSteps * mCols;
   mpEnd = mArray + size();
 }
CTimeSeries& CTimeSeries::operator= (const CTimeSeries &) private
void CTimeSeries::output (const Activity & activity) virtual
Perform an output event for the current activity
Parameters
const Activity & activity
Reimplemented from COutputInterface.
Definition at line 182 of file CTimeSeries.cpp.
References C_FLOAT64, COutputInterface::DURING, CState::getTime(), increaseAllocation(), CMatrix< C_FLOAT64 >::mCols, mpEnd, mpIt, mpState, and mRecordedSteps.
Referenced by CQGLNetworkPainter::createDataSets().
 {
   if (activity != DURING)
     return;
   // We may have to reallocate due to additional output caused from events
   if (mpIt == mpEnd)
     {
       increaseAllocation();
     }
   if (mpIt != mpEnd)
     {
       memcpy(mpIt, &mpState->getTime(), mCols * sizeof(C_FLOAT64));
       mpIt += mCols;
       mRecordedSteps++;
     }
 }
int CTimeSeries::save (const std::string & fileName, bool writeConcentrations = false, const std::string & separator = "\t") const
Save the time series to a file
Parameters
const std::string & fileName
bool writeConcentrations (default: false)
const std::string& separator (default: "\t")
Returns
int retcode
Definition at line 348 of file CTimeSeries.cpp.
References C_FLOAT64, CLocaleString::fromUtf8(), getConcentrationData(), getData(), getNumVariables(), getTitle(), and mRecordedSteps.
Referenced by CQTimeSeriesWidget::slotSave().
 {
   std::ofstream fileStream(CLocaleString::fromUtf8(fileName).c_str());
   std::ostringstream* stringStream = new std::ostringstream();
   (*stringStream) << "# ";
   size_t counter2;
   size_t maxCount2 = this->getNumVariables();
   for (counter2 = 0; counter2 < maxCount2; ++counter2)
     {
       (*stringStream) << this->getTitle(counter2) << separator;
     }
   (*stringStream) << std::endl;
   fileStream << stringStream->str();
   if (!fileStream.good()) return 1;
   size_t counter;
   size_t maxCount = mRecordedSteps;
   for (counter = 0; counter < maxCount; ++counter)
     {
       delete stringStream;
       stringStream = new std::ostringstream();
       for (counter2 = 0; counter2 < maxCount2; ++counter2)
         {
           C_FLOAT64 value;
           if (writeParticleNumbers)
             {
               value = this->getData(counter, counter2);
             }
           else
             {
               value = this->getConcentrationData(counter, counter2);
             }
           (*stringStream) << value << separator;
         }
       (*stringStream) << std::endl;
       fileStream << stringStream->str();
       if (!fileStream.good()) return 1;
     }
   fileStream.close();
   delete stringStream;
   return 0;
 }
void CTimeSeries::separate (const Activity & activity) virtual
Introduce an additional separator into the output
Parameters
const Activity & activity
Reimplemented from COutputInterface.
Definition at line 202 of file CTimeSeries.cpp.
References C_FLOAT64, increaseAllocation(), CMatrix< C_FLOAT64 >::mCols, mpEnd, mpIt, and mRecordedSteps.
 {
   // We may have to reallocate due to additional output caused from events
   if (mpIt == mpEnd)
     {
       increaseAllocation();
     }
   if (mpIt != mpEnd)
     {
       C_FLOAT64 * pIt = mpIt;
       mpIt += mCols;
       mRecordedSteps++;
       // We copy NaN to indicate separation, which is similar to plotting.
       for (; pIt != mpIt; ++pIt)
         *pIt = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
     }
 }
Member Data Documentation
size_t CTimeSeries::mAllocatedSteps private
The number of allocated steps
Definition at line 167 of file CTimeSeries.h.
Referenced by allocate(), clear(), compile(), and increaseAllocation().
CVector< size_t > CTimeSeries::mCompartment private
Vector of indexes pointing to the column storing the volume of the containing compartment for a species (C_INVALID_INDEX otherwise)
Definition at line 198 of file CTimeSeries.h.
Referenced by clear(), compile(), and getConcentrationData().
C_FLOAT64 CTimeSeries::mDummyFloat static private
Static C_FLOAT64 0.0 for performance reasons
Definition at line 223 of file CTimeSeries.h.
Referenced by getConcentrationData(), and getData().
std::string CTimeSeries::mDummyString static private
Static empty string for performance reasons
Definition at line 218 of file CTimeSeries.h.
Referenced by getKey(), getSBMLId(), and getTitle().
std::vector< std::string > CTimeSeries::mKeys private
Vector storing the keys for the model entity represented by each column
Definition at line 208 of file CTimeSeries.h.
Referenced by clear(), compile(), and getKey().
C_FLOAT64 CTimeSeries::mNumberToQuantityFactor private
Conversion factor needed for computing concentration data
Definition at line 213 of file CTimeSeries.h.
Referenced by clear(), compile(), and getConcentrationData().
C_FLOAT64* CTimeSeries::mpEnd private
Iterator pointing beyond the last allocated step (row)
Definition at line 182 of file CTimeSeries.h.
Referenced by clear(), compile(), increaseAllocation(), output(), and separate().
C_FLOAT64* CTimeSeries::mpIt private
Iterator pointing the next step (row) to be recorded
Definition at line 177 of file CTimeSeries.h.
Referenced by clear(), compile(), increaseAllocation(), output(), and separate().
CVector< size_t > CTimeSeries::mPivot private
Pivot rearranging the columns to a more user friendly order
Definition at line 203 of file CTimeSeries.h.
Referenced by clear(), compile(), getConcentrationData(), getData(), getKey(), and getTitle().
const CState* CTimeSeries::mpState private
Pointer to the state which has to be recorded.
Definition at line 187 of file CTimeSeries.h.
Referenced by clear(), compile(), and output().
size_t CTimeSeries::mRecordedSteps private
The number of actually recorded steps
Definition at line 172 of file CTimeSeries.h.
Referenced by clear(), compile(), getConcentrationData(), getData(), getRecordedSteps(), increaseAllocation(), output(), save(), and separate().
std::vector< std::string > CTimeSeries::mTitles private
Vector of column titles.
Definition at line 192 of file CTimeSeries.h.
Referenced by clear(), compile(), and getTitle().
The documentation for this class was generated from the following files:
CTimeSeries.h
CTimeSeries.cpp