COPASI API: CFunctionParameterMap Class Reference
CFunctionParameterMap Class Reference
#include <CCallParameters.h>
Public Member Functions
void addCallParameter (const std::string paramName, const CCopasiObject *obj)
CFunctionParameterMap ()
CFunctionParameterMap (const CFunctionParameterMap &src)
void clearCallParameter (const std::string paramName)
size_t findParameterByName (const std::string &name, CFunctionParameter::DataType &dataType) const
const CFunctionParameters & getFunctionParameters () const
CCallParameters< CCopasiObject > & getObjects ()
const CCallParameters
< CCopasiObject > & getObjects () const
std::vector< const
CCopasiObject * > getObjects (const size_t &index) const
CCallParameters< C_FLOAT64 > & getPointers ()
const CCallParameters
< C_FLOAT64 > & getPointers () const
void initializeFromFunctionParameters (const CFunctionParameters &src)
void removeCallParameter (const std::string paramName, const CCopasiObject *obj)
void setCallParameter (const std::string paramName, const CCopasiObject *obj)
~CFunctionParameterMap ()
Static Public Attributes
static CCopasiObject * pUnmappedObject = NULL
Private Member Functions
void checkCallParameters () const
void clearCallParameters ()
void initCallParameters ()
Private Attributes
CCallParameters< CCopasiObject > mObjects
CFunctionParameters * mpFunctionParameters
CCallParameters< C_FLOAT64 > mPointers
Detailed Description
CFunctionParameterMap
This class describes how a reaction fills the call parameters of a function. It is generated from a CFunctionParameters object. The reaction provides what exactly is to be passed as function parameters.
Definition at line 108 of file CCallParameters.h.
Constructor & Destructor Documentation
CFunctionParameterMap::CFunctionParameterMap ()
Definition at line 26 of file CCallParameters.cpp.
References C_FLOAT64, CCopasiParameter::DOUBLE, and pUnmappedObject.
                                             :
   mPointers(),
   mObjects(),
   mpFunctionParameters(NULL)
 {
   if (pUnmappedObject == NULL)
     {
       C_FLOAT64 InvalidValue = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
       pUnmappedObject =
         new CCopasiParameter("NaN", CCopasiParameter::DOUBLE, & InvalidValue);
     }
 };
CFunctionParameterMap::CFunctionParameterMap (const CFunctionParameterMap & src)
Definition at line 40 of file CCallParameters.cpp.
References mObjects, mpFunctionParameters, mPointers, CFunctionParameters::size(), and CFunctionParameter::VINT32.
                                                                              :
   mPointers(src.mPointers),
   mObjects(src.mObjects),
   mpFunctionParameters(new CFunctionParameters(*src.mpFunctionParameters))
 {
   size_t i, imax = mpFunctionParameters->size();
   for (i = 0; i < imax; ++i)
     if ((*mpFunctionParameters)[i]->getType() >= CFunctionParameter::VINT32)
       {
         mPointers[i].vector = new CCallParameters<C_FLOAT64>(*src.mPointers[i].vector);
         mObjects[i].vector = new CCallParameters<CCopasiObject>(*src.mObjects[i].vector);
       }
 }
CFunctionParameterMap::~CFunctionParameterMap ()
Destructor();
Definition at line 55 of file CCallParameters.cpp.
References clearCallParameters(), mpFunctionParameters, and pdelete.
 {
   clearCallParameters();
   pdelete(mpFunctionParameters)
 };
Member Function Documentation
void CFunctionParameterMap::addCallParameter (const std::string paramName, const CCopasiObject * obj)
Adds an object to a specific parameter vector. Works only if the parameter is a vector
Definition at line 158 of file CCallParameters.cpp.
References C_FLOAT64, fatalError, findParameterByName(), CCopasiObject::getValuePointer(), CCopasiObject::isValueDbl(), mObjects, mPointers, CCallParameters< Type >::push_back(), and CFunctionParameter::VINT32.
Referenced by CReaction::compile().
 {
   CFunctionParameter::DataType type;
   size_t index = findParameterByName(paramName, type);
   if (type < CFunctionParameter::VINT32) fatalError(); // is not a vector
   assert(obj->getValuePointer());
   assert(obj->isValueDbl());
   mObjects[index].vector->push_back(obj);
   mPointers[index].vector->push_back((const C_FLOAT64*) obj->getValuePointer());
 }
void CFunctionParameterMap::checkCallParameters () const private
Check if all pointers are !=NULL.
Definition at line 113 of file CCallParameters.cpp.
References fatalError, mObjects, mpFunctionParameters, mPointers, CCallParameters< Type >::size(), CFunctionParameters::size(), and CFunctionParameter::VINT32.
 {
   size_t i, imax = mpFunctionParameters->size();
   size_t j, jmax;
   for (i = 0; i < imax; i++)
     {
       if (mPointers[i].vector == NULL)
         fatalError();
       if (mObjects[i].vector == NULL)
         fatalError();
       if ((*mpFunctionParameters)[i]->getType() < CFunctionParameter::VINT32)
         continue;
       jmax = mPointers[i].vector->size();
       for (j = 0; j < jmax; j++)
         if ((*mPointers[i].vector)[j].value == NULL)
           fatalError();
       if (jmax != mObjects[i].vector->size()) fatalError();
       for (j = 0; j < jmax; j++)
         if ((*mObjects[i].vector)[j].value == NULL)
           fatalError();
     }
 }
void CFunctionParameterMap::clearCallParameter (const std::string paramName)
Removes all objects from a specific parameter vector. Works only if the parameter is a vector.
Definition at line 172 of file CCallParameters.cpp.
References CCallParameters< Type >::clear(), fatalError, findParameterByName(), mObjects, mPointers, and CFunctionParameter::VINT32.
Referenced by CReaction::compile().
 {
   CFunctionParameter::DataType type;
   size_t index = findParameterByName(paramName, type);
   if (type < CFunctionParameter::VINT32) fatalError(); // is not a vector
   // TODO: check type of object
   mObjects[index].vector->clear();
   mPointers[index].vector->clear();
 }
void CFunctionParameterMap::clearCallParameters () private
Clear the mPointers and mObjects vectors.
Definition at line 71 of file CCallParameters.cpp.
References CCallParameters< Type >::clear(), mObjects, mpFunctionParameters, mPointers, CFunctionParameters::size(), and CFunctionParameter::VINT32.
Referenced by initializeFromFunctionParameters(), and ~CFunctionParameterMap().
 {
   if (mpFunctionParameters)
     {
       size_t i, imax = mpFunctionParameters->size();
       for (i = 0; i < imax; i++)
         {
           if ((*mpFunctionParameters)[i]->getType() >= CFunctionParameter::VINT32)
             {
               if (mObjects[i].vector)
                 delete mObjects[i].vector;
               if (mPointers[i].vector)
                 delete mPointers[i].vector;
             }
         }
     }
   mPointers.clear();
   mObjects.clear();
 }
size_t CFunctionParameterMap::findParameterByName (const std::string & name, CFunctionParameter::DataType & dataType) const
Definition at line 185 of file CCallParameters.cpp.
References CFunctionParameters::findParameterByName(), and mpFunctionParameters.
Referenced by addCallParameter(), clearCallParameter(), CReaction::getParameterIndex(), and setCallParameter().
 {
   return mpFunctionParameters->findParameterByName(name, dataType);
 }
const CFunctionParameters & CFunctionParameterMap::getFunctionParameters () const
Definition at line 226 of file CCallParameters.cpp.
References mpFunctionParameters.
Referenced by CReaction::compile(), CReaction::getFunctionParameters(), CReaction::initializeMetaboliteKeyMap(), CReaction::initializeParameters(), CReaction::loadOld(), and CReaction::loadOneRole().
 {return * mpFunctionParameters;};
CCallParameters<CCopasiObject>& CFunctionParameterMap::getObjects ()
const CCallParameters< CCopasiObject > & CFunctionParameterMap::getObjects () const
Definition at line 223 of file CCallParameters.cpp.
References mObjects.
 {return mObjects;};
std::vector< const CCopasiObject * > CFunctionParameterMap::getObjects (const size_t & index) const
Definition at line 201 of file CCallParameters.cpp.
References C_INVALID_INDEX, mObjects, mpFunctionParameters, CCallParameters< Type >::size(), and CFunctionParameter::VINT32.
 {
   std::vector< const CCopasiObject * > Objects;
   if (index != C_INVALID_INDEX)
     {
       if ((*mpFunctionParameters)[index]->getType() < CFunctionParameter::VINT32)
         Objects.push_back(mObjects[index].value);
       else
         {
           size_t i, imax = mObjects[index].vector->size();
           for (i = 0; i < imax; i++)
             Objects.push_back((*mObjects[index].vector)[i].value);
         }
     }
   return Objects;
 }
CCallParameters< C_FLOAT64 > & CFunctionParameterMap::getPointers ()
Definition at line 191 of file CCallParameters.cpp.
References mPointers.
Referenced by CReaction::calculate(), CReaction::calculatePartialDerivative(), and CReaction::getCallParameters().
 {
   return mPointers;
 }
const CCallParameters< C_FLOAT64 > & CFunctionParameterMap::getPointers () const
Definition at line 196 of file CCallParameters.cpp.
References mPointers.
 {
   return mPointers;
 }
void CFunctionParameterMap::initCallParameters () private
Create the mPointers and mObjects vectors with type information from the CFunctionParameters object.
Definition at line 94 of file CCallParameters.cpp.
References mObjects, mpFunctionParameters, mPointers, CCallParameters< Type >::resize(), CFunctionParameters::size(), and CFunctionParameter::VINT32.
Referenced by initializeFromFunctionParameters().
 {
   size_t i, imax = mpFunctionParameters->size();
   // Resizing call the CCallParameters clear() method and initializes
   // all values to NULL.
   mPointers.resize(imax);
   mObjects.resize(imax);
   for (i = 0; i < imax; i++)
     {
       if ((*mpFunctionParameters)[i]->getType() >= CFunctionParameter::VINT32)
         {
           mObjects[i].vector = new CCallParameters<CCopasiObject>;
           mPointers[i].vector = new CCallParameters<C_FLOAT64>;
         }
     }
 }
void CFunctionParameterMap::initializeFromFunctionParameters (const CFunctionParameters & src)
Initializes a CallParameters object from a CFunctionParameters object.
Definition at line 61 of file CCallParameters.cpp.
References clearCallParameters(), initCallParameters(), mpFunctionParameters, and pdelete.
Referenced by CReaction::setFunction().
 {
   clearCallParameters();
   pdelete(mpFunctionParameters)
   mpFunctionParameters = new CFunctionParameters(src);
   initCallParameters();
 }
void CFunctionParameterMap::removeCallParameter (const std::string paramName, const CCopasiObject * obj)
Removes an object from a specific parameter vector. Works only if the parameter is a vector
void CFunctionParameterMap::setCallParameter (const std::string paramName, const CCopasiObject * obj)
Sets a specific parameter. Works only if the parameter is no vector
Definition at line 143 of file CCallParameters.cpp.
References C_FLOAT64, fatalError, findParameterByName(), CCopasiObject::getValuePointer(), CCopasiObject::isValueDbl(), mObjects, mPointers, and CFunctionParameter::VINT32.
Referenced by CReaction::compile().
 {
   CFunctionParameter::DataType type;
   size_t index = findParameterByName(paramName, type);
   if (type >= CFunctionParameter::VINT32) fatalError(); // is a vector
   // TODO: check type of object
   mObjects[index].value = obj;
   assert(obj->getValuePointer());
   assert(obj->isValueDbl());
   mPointers[index].value = (const C_FLOAT64*) obj->getValuePointer();
 }
Member Data Documentation
CCallParameters<CCopasiObject> CFunctionParameterMap::mObjects private
This is a vector of pointers to objects. Each objects needs to have a value that can be passed to a function
Definition at line 177 of file CCallParameters.h.
Referenced by addCallParameter(), CFunctionParameterMap(), checkCallParameters(), clearCallParameter(), clearCallParameters(), getObjects(), initCallParameters(), and setCallParameter().
CFunctionParameters* CFunctionParameterMap::mpFunctionParameters private
The CFunctionParameters object provides the data types of the call parameters
Definition at line 182 of file CCallParameters.h.
Referenced by CFunctionParameterMap(), checkCallParameters(), clearCallParameters(), findParameterByName(), getFunctionParameters(), getObjects(), initCallParameters(), initializeFromFunctionParameters(), and ~CFunctionParameterMap().
CCallParameters<C_FLOAT64> CFunctionParameterMap::mPointers private
This is a vector of pointers to the data that is passed to a function
Definition at line 171 of file CCallParameters.h.
Referenced by addCallParameter(), CFunctionParameterMap(), checkCallParameters(), clearCallParameter(), clearCallParameters(), getPointers(), initCallParameters(), and setCallParameter().
CCopasiObject * CFunctionParameterMap::pUnmappedObject = NULL static
Definition at line 111 of file CCallParameters.h.
Referenced by CFunctionParameterMap(), CReaction::compile(), CCopasiRootContainer::destroy(), and CCopasiXMLParser::SourceParameterElement::start().
The documentation for this class was generated from the following files:
CCallParameters.h
CCallParameters.cpp