COPASI API: CDimension Class Reference
CDimension Class Reference
#include <CDimension.h>
Public Member Functions
CDimension ()
CDimension compare (const CDimension &rhs) const
void fixDimensionless (bool d1, bool d2, bool d3, bool d4, bool d5)
std::string getDebugString () const
std::string getDisplayString (const CModel *pModel) const
bool isContradiction () const
bool isUnknown () const
CDimension operator* (const C_FLOAT64 &rhs) const
CDimension operator+ (const CDimension &rhs) const
CDimension operator- (const CDimension &rhs) const
bool operator== (const CDimension &rhs) const
std::string print (const CModel *pModel) const
void setContradiction ()
void setDimension (const C_FLOAT64 &d1, const C_FLOAT64 &d2, const C_FLOAT64 &d3, const C_FLOAT64 &d4, const C_FLOAT64 &d5)
void setUnknown ()
Static Private Member Functions
static std::string constructDisplayElement (const std::string &base, C_FLOAT64 exponent)
Private Attributes
bool mContradiction
C_FLOAT64 mD1
exponent of quantity base unit
C_FLOAT64 mD2
exponent of volume base unit
C_FLOAT64 mD3
exponent of time base unit
C_FLOAT64 mD4
exponent of area base unit
C_FLOAT64 mD5
exponent of length base unit
bool mUnknown
Detailed Description
CDimension class. The class describes the dimension of a value, usually a CFunctionParameter.
The dimension is given as a quintuple of real numbers: (amount of substance, volume, time, area, length). It can also be "unknown" or "contradiction". The actual unit can be constructed from the dimension and the 5 basic units from the CModel class (which is done in the getDisplayString() method).
Definition at line 33 of file CDimension.h.
Constructor & Destructor Documentation
CDimension::CDimension ()
Definition at line 22 of file CDimension.cpp.
   : mD1(0), mD2(0), mD3(0), mD4(0), mD5(0),
     mUnknown(true),
     mContradiction(false)
 {}
Member Function Documentation
CDimension CDimension::compare (const CDimension & rhs) const
Definition at line 219 of file CDimension.cpp.
References isContradiction(), isUnknown(), and setContradiction().
Referenced by CFindDimensions::findDimension().
 {
   CDimension result;
   if (this->isContradiction() || rhs.isContradiction())
     result.setContradiction();
   else if (*this == rhs)
     result = *this;
   else if (this->isUnknown())
     result = rhs;
   else if (rhs.isUnknown())
     result = *this;
   else
     result.setContradiction();
   return result;
 }
std::string CDimension::constructDisplayElement (const std::string & base, C_FLOAT64 exponent) static private
Definition at line 61 of file CDimension.cpp.
Referenced by getDisplayString().
 {
   if (exponent <= 0) return "";
   if (exponent == 1.0) return base;
   std::ostringstream ss;
   ss << base << "^" << exponent;
   return ss.str();
 }
void CDimension::fixDimensionless (bool d1, bool d2, bool d3, bool d4, bool d5)
If one of the base units is dimensionless, the corresponding exponent is adjusted to be 0.0. d1,d2,d3, d4, d5 indicate whether the base units are dimensionless
Definition at line 263 of file CDimension.cpp.
References mD1, mD2, mD3, mD4, and mD5.
Referenced by CFindDimensions::findDimensions(), and CFindDimensions::findDimensionsMassAction().
 {
   if (d1)
     mD1 = 0;
   if (d2)
     mD2 = 0;
   if (d3)
     mD3 = 0;
   if (d4)
     mD4 = 0;
   if (d5)
     mD5 = 0;
 }
std::string CDimension::getDebugString () const
std::string CDimension::getDisplayString (const CModel * pModel) const
Definition at line 72 of file CDimension.cpp.
References constructDisplayElement(), CModel::getAreaUnitName(), CModel::getLengthUnitName(), CModel::getQuantityUnitName(), CModel::getTimeUnitName(), CModel::getVolumeUnitName(), isContradiction(), isUnknown(), mD1, mD2, mD3, mD4, and mD5.
Referenced by print().
 {
   if (isUnknown())
     return "?";
   if (isContradiction())
     return "EEE";
   assert(pModel != NULL);
   std::string vol = pModel->getVolumeUnitName();
   std::string time = pModel->getTimeUnitName();
   std::string quan = pModel->getQuantityUnitName();
   std::string area = pModel->getAreaUnitName();
   std::string len = pModel->getLengthUnitName();
   std::string tmp;
   //positive exponents
   std::string s1;
   s1 = constructDisplayElement(quan, mD1);
   tmp = constructDisplayElement(vol, mD2);
   if ((s1 != "") && (tmp != "")) s1 += "*";
   s1 += tmp;
   tmp = constructDisplayElement(time, mD3);
   if ((s1 != "") && (tmp != "")) s1 += "*";
   s1 += tmp;
   tmp = constructDisplayElement(area, mD4);
   if ((s1 != "") && (tmp != "")) s1 += "*";
   s1 += tmp;
   tmp = constructDisplayElement(len, mD5);
   if ((s1 != "") && (tmp != "")) s1 += "*";
   s1 += tmp;
   //negative exponents
   std::string s2;
   bool parflag = false;
   s2 = constructDisplayElement(quan, -mD1);
   tmp = constructDisplayElement(vol, -mD2);
   if ((s2 != "") && (tmp != ""))
     {s2 += "*"; parflag = true;}
   s2 += tmp;
   tmp = constructDisplayElement(time, -mD3);
   if ((s2 != "") && (tmp != ""))
     {s2 += "*"; parflag = true;}
   s2 += tmp;
   tmp = constructDisplayElement(area, -mD4);
   if ((s2 != "") && (tmp != ""))
     {s2 += "*"; parflag = true;}
   s2 += tmp;
   tmp = constructDisplayElement(len, -mD5);
   if ((s2 != "") && (tmp != ""))
     {s2 += "*"; parflag = true;}
   s2 += tmp;
   if (parflag) s2 = "(" + s2 + ")";
   //put it together..
   if ((s1 == "") && (s2 == ""))
     return "1";
   if (s1 == "")
     return "1/" + s2;
   if (s2 == "")
     return s1;
   return s1 + "/" + s2;
 }
bool CDimension::isContradiction () const
Definition at line 43 of file CDimension.cpp.
References mContradiction.
Referenced by compare(), getDisplayString(), operator*(), operator+(), and operator-().
 {
   return mContradiction;
 }
bool CDimension::isUnknown () const
Definition at line 33 of file CDimension.cpp.
References mUnknown.
Referenced by compare(), getDisplayString(), operator*(), operator+(), and operator-().
 {
   return mUnknown;
 }
CDimension CDimension::operator* (const C_FLOAT64 & rhs) const
Definition at line 205 of file CDimension.cpp.
References isContradiction(), isUnknown(), mD1, mD2, mD3, mD4, mD5, setContradiction(), setDimension(), and setUnknown().
 {
   CDimension result;
   if (isContradiction())
     result.setContradiction();
   else if (isUnknown())
     result.setUnknown();
   else
     result.setDimension(mD1 * rhs, mD2 * rhs, mD3 * rhs, mD4 * rhs, mD5 * rhs);
   return result;
 }
CDimension CDimension::operator+ (const CDimension & rhs) const
Definition at line 177 of file CDimension.cpp.
References isContradiction(), isUnknown(), mD1, mD2, mD3, mD4, mD5, setContradiction(), setDimension(), and setUnknown().
 {
   CDimension result;
   if (isContradiction() || rhs.isContradiction())
     result.setContradiction();
   else if (isUnknown() || rhs.isUnknown())
     result.setUnknown();
   else
     result.setDimension(mD1 + rhs.mD1, mD2 + rhs.mD2, mD3 + rhs.mD3, mD4 + rhs.mD4, mD5 + rhs.mD5);
   return result;
 }
CDimension CDimension::operator- (const CDimension & rhs) const
Definition at line 191 of file CDimension.cpp.
References isContradiction(), isUnknown(), mD1, mD2, mD3, mD4, mD5, setContradiction(), setDimension(), and setUnknown().
 {
   CDimension result;
   if (isContradiction() || rhs.isContradiction())
     result.setContradiction();
   else if (isUnknown() || rhs.isUnknown())
     result.setUnknown();
   else
     result.setDimension(mD1 - rhs.mD1, mD2 - rhs.mD2, mD3 - rhs.mD3, mD4 - rhs.mD4, mD5 - rhs.mD5);
   return result;
 }
bool CDimension::operator== (const CDimension & rhs) const
Definition at line 166 of file CDimension.cpp.
References mContradiction, mD1, mD2, mD3, mD4, mD5, and mUnknown.
 {
   return (mUnknown == rhs.mUnknown)
          && (mContradiction == rhs.mContradiction)
          && (mD1 == rhs.mD1)
          && (mD2 == rhs.mD2)
          && (mD3 == rhs.mD3)
          && (mD4 == rhs.mD4)
          && (mD5 == rhs.mD5);
 }
std::string CDimension::print (const CModel * pModel) const
insert operator
Disabled becuase the in order to generate output, the dimensions instance needs the datamodel. std::ostream & operator<<(std::ostream &os, const CDimension & d) { if (d.mUnknown) os << "Dim: unknown"; else if (d.mContradiction) os << "Dim: conctradiction"; else os << "Dim: (" << d.mD1 << ", " << d.mD2 << ", " << d.mD3 << ") " << d.getDisplayString();
return os; }
Definition at line 250 of file CDimension.cpp.
References getDisplayString(), mContradiction, mD1, mD2, mD3, mD4, mD5, and mUnknown.
 {
   std::ostringstream os;
   if (this->mUnknown) os << "Dim: unknown";
   else if (this->mContradiction) os << "Dim: contradiction";
   else os << "Dim: (" << this->mD1 << ", " << this->mD2 << ", " << this->mD3
             << ", " << this->mD4 << ", " << this->mD5 << ")  "
             << this->getDisplayString(pModel);
   return os.str();
 }
void CDimension::setContradiction ()
Definition at line 38 of file CDimension.cpp.
References mContradiction, and mUnknown.
Referenced by compare(), operator*(), operator+(), and operator-().
 {
   mUnknown = false;
   mContradiction = true;
 }
void CDimension::setDimension (const C_FLOAT64 & d1, const C_FLOAT64 & d2, const C_FLOAT64 & d3, const C_FLOAT64 & d4, const C_FLOAT64 & d5)
Definition at line 48 of file CDimension.cpp.
References mContradiction, mD1, mD2, mD3, mD4, mD5, and mUnknown.
Referenced by CFindDimensions::findDimension(), CFindDimensions::findDimensions(), CFindDimensions::findDimensionsMassAction(), operator*(), operator+(), and operator-().
 {
   mUnknown = false;
   mContradiction = false;
   mD1 = d1;
   mD2 = d2;
   mD3 = d3;
   mD4 = d4;
   mD5 = d5;
 }
void CDimension::setUnknown ()
Definition at line 28 of file CDimension.cpp.
References mContradiction, and mUnknown.
Referenced by CFindDimensions::findDimension(), operator*(), operator+(), and operator-().
 {
   mUnknown = true;
   mContradiction = false;
 }
Member Data Documentation
bool CDimension::mContradiction private
Definition at line 85 of file CDimension.h.
Referenced by isContradiction(), operator==(), print(), setContradiction(), setDimension(), and setUnknown().
C_FLOAT64 CDimension::mD1 private
exponent of quantity base unit
Definition at line 74 of file CDimension.h.
Referenced by fixDimensionless(), getDisplayString(), operator*(), operator+(), operator-(), operator==(), print(), and setDimension().
C_FLOAT64 CDimension::mD2 private
exponent of volume base unit
Definition at line 76 of file CDimension.h.
Referenced by fixDimensionless(), getDisplayString(), operator*(), operator+(), operator-(), operator==(), print(), and setDimension().
C_FLOAT64 CDimension::mD3 private
exponent of time base unit
Definition at line 78 of file CDimension.h.
Referenced by fixDimensionless(), getDisplayString(), operator*(), operator+(), operator-(), operator==(), print(), and setDimension().
C_FLOAT64 CDimension::mD4 private
exponent of area base unit
Definition at line 80 of file CDimension.h.
Referenced by fixDimensionless(), getDisplayString(), operator*(), operator+(), operator-(), operator==(), print(), and setDimension().
C_FLOAT64 CDimension::mD5 private
exponent of length base unit
Definition at line 82 of file CDimension.h.
Referenced by fixDimensionless(), getDisplayString(), operator*(), operator+(), operator-(), operator==(), print(), and setDimension().
bool CDimension::mUnknown private
Definition at line 84 of file CDimension.h.
Referenced by isUnknown(), operator==(), print(), setContradiction(), setDimension(), and setUnknown().
The documentation for this class was generated from the following files:
CDimension.h
CDimension.cpp