COPASI API: COutputHandlerPlot Class Reference
COutputHandlerPlot Class Reference
#include <COutputHandlerPlot.h>
Public Member Functions
virtual bool compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel *pDataModel)
COutputHandlerPlot ()
COutputHandlerPlot (const COutputHandlerPlot &src)
virtual void removeInterface (COutputInterface *pInterface)
void setOutputDefinitionVector (COutputDefinitionVector *pDefinitionVector)
virtual ~COutputHandlerPlot ()
Public Member Functions inherited from COutputHandler
virtual void addInterface (COutputInterface *pInterface)
COutputHandler ()
COutputHandler (const COutputHandler &src)
virtual void finish ()
std::set< COutputInterface * > getInterfaces () const
bool isMaster () const
virtual void output (const Activity &activity)
virtual void separate (const Activity &activity)
void setMaster (COutputHandler *pMaster)
virtual ~COutputHandler ()
Public Member Functions inherited from COutputInterface
virtual void close ()
COutputInterface ()
COutputInterface (const COutputInterface &src)
virtual const std::set< const
CCopasiObject * > & getObjects () const
virtual ~COutputInterface ()
Private Attributes
COutputDefinitionVector * mpDefinitionVector
std::map< std::string,
PlotWindow * > mPlotMap
Additional Inherited Members
Public Types inherited from COutputInterface
enum Activity { BEFORE = 0x01, DURING = 0x02, AFTER = 0x04 }
Protected Member Functions inherited from COutputHandler
bool compileRefresh (const std::vector< CCopasiContainer * > &listOfContainer, const CCopasiDataModel *pDataModel)
void refresh ()
Protected Attributes inherited from COutputHandler
std::set< COutputInterface * > mInterfaces
std::vector< Refresh * > mObjectRefreshes
COutputHandler * mpMaster
Protected Attributes inherited from COutputInterface
std::set< const CCopasiObject * > mObjects
Detailed Description
This is used to call the plotting routines from the tasks We do not want to call gui stuff directly from the trajectory task.
Definition at line 32 of file COutputHandlerPlot.h.
Constructor & Destructor Documentation
COutputHandlerPlot::COutputHandlerPlot ()
Default constructor
Definition at line 27 of file COutputHandlerPlot.cpp.
                                       :
   COutputHandler(),
   mpDefinitionVector(NULL)
 {}
COutputHandlerPlot::COutputHandlerPlot (const COutputHandlerPlot & src)
Copy constructor
Parameters
const COutputHandlerPlot & src
Definition at line 32 of file COutputHandlerPlot.cpp.
                                                                     :
   COutputHandler(src),
   mpDefinitionVector(src.mpDefinitionVector)
 {}
COutputHandlerPlot::~COutputHandlerPlot () virtual
Destructor
Definition at line 37 of file COutputHandlerPlot.cpp.
 {}
Member Function Documentation
bool COutputHandlerPlot::compile (std::vector< CCopasiContainer * > listOfContainer, const CCopasiDataModel * pDataModel) virtual
compile the object list from name vector
Parameters
std::vector< CCopasiContainer * > listOfContainer
const CCopasiDataModel* pDataModel
Returns
bool success
Reimplemented from COutputHandler.
Definition at line 40 of file COutputHandlerPlot.cpp.
References COutputHandler::compile(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWindow(), CPlotItem::getTitle(), CPlotSpecification::isActive(), CopasiUI3Window::isMainThread(), COutputHandler::mInterfaces, mpDefinitionVector, mPlotMap, CCopasiVector< T >::size(), and TO_UTF8.
 {
   if (!mpDefinitionVector) return false;
   // This must only be executed in the main thread.
   if (CopasiUI3Window::isMainThread())
     {
       mInterfaces.clear();
       //step through the vector of specifications and create the plot windows
       std::string key;
       size_t i, imax = mpDefinitionVector->size();
       for (i = 0; i < imax; i++)
         {
           CPlotSpecification * pSpecification = (*mpDefinitionVector)[i];
           if (pSpecification->isActive())
             {
               key = pSpecification->CCopasiParameter::getKey();
               if (!mPlotMap.count(key))
                 mPlotMap[key] = new PlotWindow(this, pSpecification, CopasiUI3Window::getMainWindow());
               else if ("COPASI Plot: " + pSpecification->getTitle() !=
                        TO_UTF8(mPlotMap[key]->windowTitle()))
                 mPlotMap[key] = new PlotWindow(this, pSpecification, CopasiUI3Window::getMainWindow());
               else
                 mPlotMap[key]->initFromSpec(pSpecification);
               mPlotMap[key]->show();
               mInterfaces.insert(mPlotMap[key]);
             }
         }
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   return COutputHandler::compile(listOfContainer, pDataModel);
 }
void COutputHandlerPlot::removeInterface (COutputInterface * pInterface) virtual
Perform an output event for the current activity
Parameters
const Activity & activity Introduce an additional separator into the output
const Activity & activity Finish the output Remove an interface
COutputInterface * pInterface;
Reimplemented from COutputHandler.
Definition at line 82 of file COutputHandlerPlot.cpp.
References mPlotMap, and COutputHandler::removeInterface().
Referenced by PlotWindow::closeEvent(), and PlotWindow::~PlotWindow().
 {
   std::map<std::string, PlotWindow*>::iterator it = mPlotMap.begin();
   std::map<std::string, PlotWindow*>::iterator end = mPlotMap.end();
   for (; it != end; ++it)
     if (it->second == pInterface)
       {
         mPlotMap.erase(it);
         return;
       }
   COutputHandler::removeInterface(pInterface);
   return;
 }
void COutputHandlerPlot::setOutputDefinitionVector (COutputDefinitionVector * pDefinitionVector)
Definition at line 98 of file COutputHandlerPlot.cpp.
References mpDefinitionVector.
Referenced by DataModelGUI::createModel(), DataModelGUI::importSBMLFinished(), DataModelGUI::importSBMLFromStringFinished(), and DataModelGUI::loadModelFinished().
 {mpDefinitionVector = pDefinitionVector;}
Member Data Documentation
COutputDefinitionVector* COutputHandlerPlot::mpDefinitionVector private
The plot definition
Definition at line 88 of file COutputHandlerPlot.h.
Referenced by compile(), and setOutputDefinitionVector().
std::map<std::string, PlotWindow*> COutputHandlerPlot::mPlotMap private
This maps the key of a plot spec to a plot window
Definition at line 93 of file COutputHandlerPlot.h.
Referenced by compile(), and removeInterface().
The documentation for this class was generated from the following files:
COutputHandlerPlot.h
COutputHandlerPlot.cpp