COPASI API: CNormalChoice Class Reference
CNormalChoice Class Reference
#include <CNormalChoice.h>
Public Member Functions
CNormalChoice ()
CNormalChoice (const CNormalChoice &src)
virtual CNormalBase * copy () const
const CNormalLogical & getCondition () const
CNormalLogical & getCondition ()
const CNormalFraction & getFalseExpression () const
CNormalFraction & getFalseExpression ()
const CNormalFraction & getTrueExpression () const
CNormalFraction & getTrueExpression ()
bool operator< (const CNormalChoice &rhs) const
CNormalChoice & operator= (const CNormalChoice &src)
bool operator== (const CNormalChoice &rhs) const
bool setCondition (const CNormalLogical &cond)
bool setFalseExpression (const CNormalFraction &branch)
bool setTrueExpression (const CNormalFraction &branch)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalChoice ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Static Public Member Functions
static bool checkConditionTree (const CNormalBase &branch)
static bool checkExpressionTree (const CNormalBase &branch)
Protected Attributes
CNormalLogical * mpCondition
CNormalFraction * mpFalse
CNormalFraction * mpTrue
Friends
std::ostream & operator<< (std::ostream &os, const CNormalChoice &choice)
Detailed Description
Definition at line 23 of file CNormalChoice.h.
Constructor & Destructor Documentation
CNormalChoice::CNormalChoice ()
Definition at line 27 of file CNormalChoice.cpp.
Referenced by copy().
                             : CNormalBase(), mpCondition(NULL), mpTrue(NULL), mpFalse(NULL)
 {}
CNormalChoice::CNormalChoice (const CNormalChoice & src)
Definition at line 30 of file CNormalChoice.cpp.
                                                     :
     CNormalBase(src),
     mpCondition(NULL),
     mpTrue(NULL),
     mpFalse(NULL)
 {*this = src;}
CNormalChoice::~CNormalChoice () virtual
Definition at line 37 of file CNormalChoice.cpp.
References mpCondition, mpFalse, mpTrue, and pdelete.
 {
   pdelete(mpCondition);
   pdelete(mpTrue);
   pdelete(mpFalse);
 }
Member Function Documentation
bool CNormalChoice::checkConditionTree (const CNormalBase & branch) static
Definition at line 133 of file CNormalChoice.cpp.
References CNormalItem::CONSTANT, getCondition(), getFalseExpression(), CNormalItem::getName(), getTrueExpression(), and CNormalItem::getType().
Referenced by checkExpressionTree(), and setCondition().
 {
   bool result = true;
   const CNormalChoice* pChoice = dynamic_cast<const CNormalChoice*>(&branch);
   if (pChoice != NULL)
     {
       // check the condition and the two branches
       result = checkConditionTree(pChoice->getCondition());
       if (result == true) result = checkConditionTree(pChoice->getTrueExpression());
       if (result == true) result = checkConditionTree(pChoice->getFalseExpression());
     }
   else
     {
       const CNormalLogical* pLogical = dynamic_cast<const CNormalLogical*>(&branch);
       if (pLogical == NULL)
         {
           const CNormalItem* pItem = dynamic_cast<const CNormalItem*>(&branch);
           if (pItem == NULL)
             {
               result = false;
             }
           else
             {
               result = pItem->getType() == CNormalItem::CONSTANT;
               if (result == true)
                 {
                   std::string name = pItem->getName();
                   if (name != "true" && name != "TRUE" && name != "false" && name != "FALSE")
                     {
                       result = false;
                     }
                 }
             }
         }
     }
   return result;
 }
bool CNormalChoice::checkExpressionTree (const CNormalBase & branch) static
Definition at line 171 of file CNormalChoice.cpp.
References checkConditionTree(), getCondition(), getFalseExpression(), and getTrueExpression().
Referenced by setFalseExpression(), and setTrueExpression().
 {
   bool result = true;
   const CNormalChoice* pChoice = dynamic_cast<const CNormalChoice*>(&branch);
   if (pChoice != NULL)
     {
       result = checkConditionTree(pChoice->getCondition());
       if (result == true) result = checkExpressionTree(pChoice->getTrueExpression());
       if (result == true) result = checkExpressionTree(pChoice->getFalseExpression());
     }
   else
     {
       const CNormalFraction* pFraction = dynamic_cast<const CNormalFraction*>(&branch);
       if (pFraction == NULL)
         {
           result = false;
         }
     }
   return result;
 }
CNormalBase * CNormalChoice::copy () const virtual
Implements CNormalBase.
Definition at line 128 of file CNormalChoice.cpp.
References CNormalChoice().
   {
     return new CNormalChoice(*this);
   }
const CNormalLogical & CNormalChoice::getCondition () const
Definition at line 98 of file CNormalChoice.cpp.
References mpCondition.
Referenced by checkConditionTree(), checkExpressionTree(), convertToCEvaluationNode(), and normalize_variable_names().
   {
     return *mpCondition;
   }
CNormalLogical & CNormalChoice::getCondition ()
Definition at line 103 of file CNormalChoice.cpp.
References mpCondition.
 {
   return *mpCondition;
 }
const CNormalFraction & CNormalChoice::getFalseExpression () const
Definition at line 118 of file CNormalChoice.cpp.
References mpFalse.
Referenced by checkConditionTree(), checkExpressionTree(), convertToCEvaluationNode(), and normalize_variable_names().
   {
     return *mpFalse;
   }
CNormalFraction & CNormalChoice::getFalseExpression ()
Definition at line 123 of file CNormalChoice.cpp.
References mpFalse.
 {
   return *mpFalse;
 }
const CNormalFraction & CNormalChoice::getTrueExpression () const
Definition at line 108 of file CNormalChoice.cpp.
References mpTrue.
Referenced by checkConditionTree(), checkExpressionTree(), convertToCEvaluationNode(), and normalize_variable_names().
   {
     return *mpTrue;
   }
CNormalFraction & CNormalChoice::getTrueExpression ()
Definition at line 113 of file CNormalChoice.cpp.
References mpTrue.
 {
   return *mpTrue;
 }
bool CNormalChoice::operator< (const CNormalChoice & rhs) const
Definition at line 224 of file CNormalChoice.cpp.
References mpCondition, mpFalse, and mpTrue.
   {
     bool result = false;
     if ((*this->mpCondition) < (*rhs.mpCondition))
       {
         result = true;
       }
     else if ((*this->mpCondition) == (*rhs.mpCondition))
       {
         if ((*this->mpTrue) < (*rhs.mpTrue))
           {
             result = true;
           }
         else if ((*this->mpTrue) == (*rhs.mpTrue))
           {
             if ((*this->mpFalse) < (*rhs.mpFalse))
               {
                 result = true;
               }
           }
       }
     return result;
   }
CNormalChoice & CNormalChoice::operator= (const CNormalChoice & src)
Definition at line 44 of file CNormalChoice.cpp.
References mpCondition, mpFalse, mpTrue, and pdelete.
 {
   pdelete(mpCondition);
   pdelete(mpTrue);
   pdelete(mpFalse);
   if (src.mpCondition != NULL)
     mpCondition = new CNormalLogical(*src.mpCondition);
   if (src.mpCondition != NULL)
     mpTrue = new CNormalFraction(*src.mpTrue);
   if (src.mpCondition != NULL)
     mpFalse = new CNormalFraction(*src.mpFalse);
   return *this;
 }
bool CNormalChoice::operator== (const CNormalChoice & rhs) const
Definition at line 214 of file CNormalChoice.cpp.
References mpCondition, mpFalse, and mpTrue.
   {
     bool result = true;
     if (!(((*this->mpCondition) == (*rhs.mpCondition)) && ((*this->mpTrue) == (*rhs.mpTrue)) && ((*this->mpFalse) == (*rhs.mpFalse))))
       {
         result = false;
       }
     return result;
   }
bool CNormalChoice::setCondition (const CNormalLogical & cond)
Definition at line 60 of file CNormalChoice.cpp.
References checkConditionTree(), mpCondition, and pdelete.
Referenced by createChoice().
 {
   bool result = true;
   pdelete(mpCondition);
   // check the cond if it is OK
   result = checkConditionTree(cond);
   if (result == true)
     mpCondition = new CNormalLogical(cond);
   return result;
 }
bool CNormalChoice::setFalseExpression (const CNormalFraction & branch)
Definition at line 87 of file CNormalChoice.cpp.
References checkExpressionTree(), mpFalse, and pdelete.
Referenced by createChoice().
 {
   bool result = true;
   pdelete(mpFalse);
   // check the branch if it is OK
   result = checkExpressionTree(branch);
   mpFalse = new CNormalFraction(branch);
   return result;
 }
bool CNormalChoice::setTrueExpression (const CNormalFraction & branch)
Definition at line 74 of file CNormalChoice.cpp.
References checkExpressionTree(), mpTrue, and pdelete.
Referenced by createChoice().
 {
   bool result = true;
   pdelete(mpTrue);
   // check the branch if it is OK
   result = checkExpressionTree(branch);
   mpTrue = new CNormalFraction(branch);
   return result;
 }
bool CNormalChoice::simplify () virtual
Implements CNormalBase.
Definition at line 205 of file CNormalChoice.cpp.
References mpCondition, mpFalse, mpTrue, CNormalFraction::simplify(), and CNormalLogical::simplify().
 {
   bool result = true;
   if (this->mpCondition != NULL) result &= this->mpCondition->simplify();
   if (this->mpTrue != NULL) result &= this->mpTrue->simplify();
   if (this->mpFalse != NULL) result &= this->mpFalse->simplify();
   return result;
 }
std::string CNormalChoice::toString () const virtual
Implements CNormalBase.
Definition at line 192 of file CNormalChoice.cpp.
References mpCondition, mpFalse, mpTrue, CNormalFraction::toString(), and CNormalLogical::toString().
Referenced by operator<<().
   {
     std::ostringstream os;
     os << "if(" << this->mpCondition->toString() << ") then (" << this->mpTrue->toString() << ") else (" << this->mpFalse->toString() << ")";
     return os.str();
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CNormalChoice & choice) friend
Definition at line 199 of file CNormalChoice.cpp.
 {
   os << choice.toString();
   return os;
 }
Member Data Documentation
CNormalLogical* CNormalChoice::mpCondition protected
Definition at line 26 of file CNormalChoice.h.
Referenced by getCondition(), operator<(), operator=(), operator==(), setCondition(), simplify(), toString(), and ~CNormalChoice().
CNormalFraction* CNormalChoice::mpFalse protected
Definition at line 28 of file CNormalChoice.h.
Referenced by getFalseExpression(), operator<(), operator=(), operator==(), setFalseExpression(), simplify(), toString(), and ~CNormalChoice().
CNormalFraction* CNormalChoice::mpTrue protected
Definition at line 27 of file CNormalChoice.h.
Referenced by getTrueExpression(), operator<(), operator=(), operator==(), setTrueExpression(), simplify(), toString(), and ~CNormalChoice().
The documentation for this class was generated from the following files:
CNormalChoice.h
CNormalChoice.cpp