COPASI API: CTrajectoryTask.cpp File Reference
CTrajectoryTask.cpp File Reference
#include <string>
#include <cmath>
#include "copasi.h"
#include "CTrajectoryTask.h"
#include "CTrajectoryProblem.h"
#include "CTrajectoryMethod.h"
#include "model/CModel.h"
#include "model/CMathModel.h"
#include "model/CState.h"
#include "report/CKeyFactory.h"
#include "report/CReport.h"
#include "utilities/CProcessReport.h"
#include "utilities/CCopasiException.h"
#include "CopasiDataModel/CCopasiDataModel.h"
Macros
#define XXXX_Reporting
Functions
bool bl (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
bool ble (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
bool fl (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
bool fle (const C_FLOAT64 &d1, const C_FLOAT64 &d2)
Macro Definition Documentation
#define XXXX_Reporting
CTrajectoryTask class.
This class implements a trajectory task which is comprised of a of a problem and a method. Additionally calls to the reporting methods are done when initialized.
Created for COPASI by Stefan Hoops 2002
Definition at line 43 of file CTrajectoryTask.cpp.
Function Documentation
bool bl (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 54 of file CTrajectoryTask.cpp.
Referenced by CTrajectoryTask::process().
 {return (d1 > d2);}
bool ble (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 51 of file CTrajectoryTask.cpp.
Referenced by CTrajectoryTask::process().
 {return (d1 >= d2);}
bool fl (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 48 of file CTrajectoryTask.cpp.
Referenced by CReactionInterface::findAndSetFunction(), and CTrajectoryTask::process().
 {return (d1 < d2);}
bool fle (const C_FLOAT64 & d1, const C_FLOAT64 & d2)
Definition at line 45 of file CTrajectoryTask.cpp.
Referenced by CTrajectoryTask::process().
 {return (d1 <= d2);}