COPASI API: CCopasiMethod Class Reference
CCopasiMethod Class Reference
#include <CCopasiMethod.h>
Public Types
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Member Functions
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CCopasiMethod ()
Private Attributes
CCopasiMethod::SubType mSubType
CCopasiTask::Type mType
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiMethod &o)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 34 of file CCopasiMethod.h.
Member Enumeration Documentation
enum CCopasiMethod::SubType
Enumeration of the sub types of methods known to COPASI.
Enumerator
unset
RandomSearch
RandomSearchMaster
SimulatedAnnealing
CoranaWalk
DifferentialEvolution
ScatterSearch
GeneticAlgorithm
EvolutionaryProgram
SteepestDescent
HybridGASA
GeneticAlgorithmSR
HookeJeeves
LevenbergMarquardt
NelderMead
SRES
Statistics
ParticleSwarm
Praxis
TruncatedNewton
Newton
deterministic
LSODAR
directMethod
stochastic
tauLeap
adaptiveSA
hybrid
hybridLSODA
hybridODE45
DsaLsodar
tssILDM
tssILDMModified
tssCSP
mcaMethodReder
scanMethod
lyapWolf
sensMethod
EFMAlgorithm
EFMBitPatternTreeAlgorithm
EFMBitPatternAlgorithm
Householder
crossSectionMethod
linearNoiseApproximation
Definition at line 40 of file CCopasiMethod.h.
   {
     unset = 0,
     RandomSearch,
     RandomSearchMaster,
     SimulatedAnnealing,
     CoranaWalk,
     DifferentialEvolution,
     ScatterSearch,
     GeneticAlgorithm,
     EvolutionaryProgram,
     SteepestDescent,
     HybridGASA,
     GeneticAlgorithmSR,
     HookeJeeves,
     LevenbergMarquardt,
     NelderMead,
     SRES,
     Statistics,
     ParticleSwarm,
     Praxis,
     TruncatedNewton,
     Newton,
     deterministic,
     LSODAR,
     directMethod,
     stochastic,
     tauLeap,
     adaptiveSA,
     hybrid,
     hybridLSODA,
     hybridODE45,
     DsaLsodar,
     tssILDM,
     tssILDMModified,
     tssCSP,
     mcaMethodReder,
     scanMethod,
     lyapWolf,
     sensMethod,
 #ifdef COPASI_SSA
     stoichiometricStabilityAnalysis,
 #endif // COPASI_SSA
     EFMAlgorithm,
     EFMBitPatternTreeAlgorithm,
     EFMBitPatternAlgorithm,
     Householder,
     crossSectionMethod,
     linearNoiseApproximation
   };
Constructor & Destructor Documentation
CCopasiMethod::CCopasiMethod () private
A pointer to the report Default constructor
Definition at line 134 of file CCopasiMethod.cpp.
References mType, CCopasiObject::setObjectName(), and SubTypeName.
                             :
   CCopasiParameterGroup("NoName", NULL, "Method"),
   mType(CCopasiTask::unset),
   mSubType(unset),
   mpCallBack(NULL)
   //mpReport(NULL)
 {setObjectName(SubTypeName[mType]);}
CCopasiMethod::CCopasiMethod (const CCopasiTask::Type & taskType, const SubType & subType, const CCopasiContainer * pParent = NULL) protected
Specific constructor
Parameters
const CCopasiTask::Type & type
const CCopasiMethod::SubType & subType
const CCopasiContainer * pParent (default: NULL)
Definition at line 142 of file CCopasiMethod.cpp.
References mSubType, CCopasiObject::setObjectName(), and SubTypeName.
                                                               :
   CCopasiParameterGroup(CCopasiTask::TypeName[type], pParent, "Method"),
   mType(type),
   mSubType(subType),
   mpCallBack(NULL)
   //mpReport(NULL)
 {setObjectName(SubTypeName[mSubType]);}
CCopasiMethod::CCopasiMethod (const CCopasiMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CCopasiMethodr & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 152 of file CCopasiMethod.cpp.
                                                               :
   CCopasiParameterGroup(src, pParent),
   mType(src.mType),
   mSubType(src.mSubType),
   mpCallBack(src.mpCallBack)
   //mpReport(src.mpReport)
 {}
CCopasiMethod::~CCopasiMethod () virtual
Destructor
Definition at line 161 of file CCopasiMethod.cpp.
 {}
Member Function Documentation
const CCopasiMethod::SubType & CCopasiMethod::getSubType () const
Retrieve the sub type of the method
Returns
CCopasiMethod::SubType & subType
Definition at line 173 of file CCopasiMethod.cpp.
References mSubType.
Referenced by CQTaskMethodWidget::addToHistory(), CCrossSectionTask::CCrossSectionTask(), CEFMTask::CEFMTask(), CFitTask::CFitTask(), CLNATask::CLNATask(), CMCATask::CMCATask(), CMoietiesTask::CMoietiesTask(), COptTask::COptTask(), COscillationTask::COscillationTask(), CSensTask::CSensTask(), CSteadyStateTask::CSteadyStateTask(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), CEFMTask::getFluxModeDescription(), CEFMTask::getReactionEquation(), CNewtonMethod::initialize(), CTSSAMethod::isValidProblem(), CQTaskMethodWidget::loadMethod(), CQSimpleSelectionTree::populateTree(), CQTaskMethodWidget::removeFromHistory(), CQTaskMethodWidget::saveMethod(), CCopasiXML::saveTaskList(), CTSSAMethod::schur(), CFitTask::setMethodType(), CMoietiesTask::setMethodType(), COscillationTask::setMethodType(), COptTask::setMethodType(), CEFMTask::setMethodType(), CTrajectoryTask::setMethodType(), CLyapTask::setMethodType(), CTSSATask::setMethodType(), CCrossSectionTask::setMethodType(), CQTaskMethodWidget::setTask(), and CCopasiXMLParser::MethodElement::start().
 {return mSubType;}
const CCopasiTask::Type & CCopasiMethod::getType (void) const
Retrieve the type of the method
Returns
const string & type
Definition at line 169 of file CCopasiMethod.cpp.
References mType.
 {return mType;}
bool CCopasiMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented in CTrajectoryMethodDsaLsodar, CScanMethod, CStochMethod, CLyapWolfMethod, CTrajAdaptiveSA, CLNAMethod, CStochDirectMethod, CHybridMethodLSODA, CHybridMethodODE45, CHybridMethod, CTauLeapMethod, CTrajectoryMethod, CSteadyStateMethod, CMCAMethod, CTSSAMethod, CLyapMethod, COptMethod, CNewtonMethod, CSensMethod, COscillationMethod, CEFMMethod, CFitMethod, and CCrossSectionMethod.
Definition at line 180 of file CCopasiMethod.cpp.
References CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, CModel::getEvents(), CCopasiProblem::getModel(), CCopasiTask::lna, CCopasiTask::lyap, MCCopasiMethod, mType, CCopasiVector< T >::size(), and CCopasiTask::tssAnalysis.
Referenced by CMoietiesTask::initialize(), CLNATask::initialize(), CEFMTask::initialize(), CScanTask::initialize(), CLyapTask::initialize(), CMCATask::initialize(), CTrajectoryTask::initialize(), CTSSATask::initialize(), CSteadyStateTask::initialize(), CCrossSectionTask::initialize(), CCrossSectionMethod::isValidProblem(), CEFMMethod::isValidProblem(), COscillationMethod::isValidProblem(), CSensMethod::isValidProblem(), COptMethod::isValidProblem(), CLyapMethod::isValidProblem(), CTSSAMethod::isValidProblem(), CMCAMethod::isValidProblem(), CSteadyStateMethod::isValidProblem(), CTrajectoryMethod::isValidProblem(), CLNAMethod::isValidProblem(), CScanMethod::isValidProblem(), CFitTask::process(), CSensTask::process(), COscillationTask::process(), COptTask::process(), CLNATask::updateMatrices(), CMCATask::updateMatrices(), and CTSSATask::updateMatrices().
 {
   if (!pProblem)
     {
       //no problem
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCCopasiMethod + 2);
       return false;
     }
   if (! pProblem->getModel())
     {
       //no model
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCCopasiMethod + 3);
       return false;
     }
   if (pProblem->getModel()->getEvents().size())
     {
       if (mType == CCopasiTask::lyap)
         {
           CCopasiMessage(CCopasiMessage::ERROR, MCCopasiMethod + 4, "Lyapunov Exponents");
           return false;
         }
       if (mType == CCopasiTask::tssAnalysis)
         {
           CCopasiMessage(CCopasiMessage::ERROR, MCCopasiMethod + 4, "Time Scale Separation Analysis");
           return false;
         }
       if (mType == CCopasiTask::lna)
         {
           CCopasiMessage(CCopasiMessage::ERROR, MCCopasiMethod + 4, "Linear Noise Approximation");
           return false;
         }
     }
   return true;
 }
void CCopasiMethod::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::SEARCH) virtual
Load a list of parameters
Parameters
CReadConfig & configBuffer
CReadConfig::Mode mode Default(CReadConfig::SEARCH)
Reimplemented in CNewtonMethod.
Definition at line 220 of file CCopasiMethod.cpp.
References fatalError.
 {fatalError();}
void CCopasiMethod::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To overide this default behaviour one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiParameterGroup.
Definition at line 224 of file CCopasiMethod.cpp.
Referenced by operator<<(), CILDMModifiedMethod::printResult(), and CCSPMethod::printResult().
 {*ostream << *this;}
void CCopasiMethod::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a method. The default implementation provided with CCopasiMethod. Does only print "Not implmented." To overide this default behaviour one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented in CCSPMethod, CILDMMethod, and CILDMModifiedMethod.
Definition at line 245 of file CCopasiMethod.cpp.
Referenced by CTSSAProblem::printResult().
 {*ostream << " Not implemented.";}
bool CCopasiMethod::setCallBack (CProcessReport * pCallBack) virtual
Set the call back of the problem
Parameters
CProcessReport * pCallBack
Returns
bool succes
Definition at line 163 of file CCopasiMethod.cpp.
References mpCallBack.
Referenced by CMoietiesTask::setCallBack(), CFitTask::setCallBack(), COscillationTask::setCallBack(), CEFMTask::setCallBack(), and COptTask::setCallBack().
 {
   mpCallBack = pCallBack;
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiMethod & o) friend
Output stream operator
Parameters
ostream & os
const CCopasiMethod & A
Returns
ostream & os
Definition at line 227 of file CCopasiMethod.cpp.
 {
   os << "Method: " << o.getObjectName() << std::endl;
   CCopasiParameterGroup::parameterGroup::const_iterator it =
     o.CCopasiParameter::getValue().pGROUP->begin();
   CCopasiParameterGroup::parameterGroup::const_iterator end =
     o.CCopasiParameter::getValue().pGROUP->end();
   for (; it != end; ++it)
     {
       (*it)->print(&os);
       os << std::endl;
     }
   return os;
 }
Member Data Documentation
CProcessReport* CCopasiMethod::mpCallBack protected
a pointer to the callback
Definition at line 118 of file CCopasiMethod.h.
Referenced by CSSAMethod::calculate(), CEFMAlgorithm::calculate(), CBitPatternMethod::calculate(), CBitPatternTreeMethod::calculate(), CEFMAlgorithm::calculateFluxModes(), CEFMAlgorithm::calculateNextTableau(), CBitPatternTreeMethod::combine(), CBitPatternMethod::combine(), CSensMethod::do_target_calculation(), CNewtonMethod::doIntegration(), CSSAMethod::initialize(), COptMethodEP::initialize(), COptMethodDE::initialize(), COptMethodSRES::initialize(), COptMethodPS::initialize(), COptMethodGA::initialize(), COptMethodGASR::initialize(), COptMethodHookeJeeves::initialize(), COptMethodCoranaWalk::initialize(), COptMethodSA::initialize(), COptMethodLevenbergMarquardt::initialize(), COptMethodNelderMead::initialize(), CEFMAlgorithm::initialize(), COptMethodSS::initialize(), CBitPatternMethod::initialize(), CBitPatternTreeMethod::initialize(), COptMethodDE::optimise(), COptMethodSRES::optimise(), COptMethodSS::optimise(), COptMethodGA::optimise(), COptMethodPS::optimise(), COptMethodHookeJeeves::optimise(), COptMethodGASR::optimise(), COptMethodSA::optimise(), COptMethodNelderMead::optimise(), COptMethodCoranaWalk::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodEP::optimise(), CMoietiesMethod::process(), CSensMethod::process(), CSteadyStateMethod::process(), CNewtonMethod::processInternal(), CNewtonMethod::processNewton(), and setCallBack().
CCopasiMethod::SubType CCopasiMethod::mSubType private
The type of the method
Definition at line 112 of file CCopasiMethod.h.
Referenced by CCopasiMethod(), and getSubType().
CCopasiTask::Type CCopasiMethod::mType private
The type of the method
Definition at line 107 of file CCopasiMethod.h.
Referenced by CCopasiMethod(), getType(), and isValidProblem().
const std::string CCopasiMethod::SubTypeName static
String literals for the GUI to display sub type names of methods known to COPASI.
CCopasiMethod class. This class is used to describe a task in COPASI. This class is intended to be used as the parent class for all methods whithin COPASI.
Created for Copasi by Stefan Hoops 2003
Definition at line 95 of file CCopasiMethod.h.
Referenced by CCopasiMethod(), CQTaskMethodWidget::changeMethod(), CQTaskMethodWidget::loadMethod(), and CQTaskMethodWidget::setValidMethods().
const char * CCopasiMethod::XMLSubType static
XML sub type names of methods known to COPASI.
Definition at line 100 of file CCopasiMethod.h.
Referenced by CCopasiXML::saveTaskList(), and CCopasiXMLParser::MethodElement::start().
The documentation for this class was generated from the following files:
CCopasiMethod.h
CCopasiMethod.cpp