COPASI API: COptItem.cpp File Reference
COptItem.cpp File Reference
#include <algorithm>
#include <limits>
#include <cmath>
#include <sstream>
#include <stdlib.h>
#include "copasi.h"
#include "COptItem.h"
#include "randomGenerator/CRandom.h"
#include "report/CCopasiContainer.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiObjectName.h"
#include "utilities/CCopasiParameterGroup.h"
#include "utilities/CCopasiMessage.h"
#include "utilities/utility.h"
Functions
std::ostream & operator<< (std::ostream &os, const COptItem &o)
Variables
UpdateMethod DoNothing
C_FLOAT64 NaN = std::numeric_limits< C_FLOAT64 >::quiet_NaN()
Function Documentation
std::ostream& operator<< (std::ostream & os, const COptItem & o)
Output stream operator
Parameters
ostream & os
const COptItem & A
Returns
ostream & os
Definition at line 505 of file COptItem.cpp.
References COptItem::getLowerBound(), CCopasiObject::getObjectDisplayName(), COptItem::getStartValue(), COptItem::getUpperBound(), COptItem::mpLowerObject, COptItem::mpObject, and COptItem::mpUpperObject.
 {
   if (o.mpObject == NULL && !const_cast<COptItem *>(&o)->compile())
     return os << "Invalid Optimization Item";
   if (o.mpLowerObject)
     os << o.mpLowerObject->getObjectDisplayName();
   else
     os << o.getLowerBound();
   os << " <= ";
   os << o.mpObject->getObjectDisplayName();
   os << " <= ";
   if (o.mpUpperObject)
     os << o.mpUpperObject->getObjectDisplayName();
   else
     os << o.getUpperBound();
   os << "; Start Value = " << o.getStartValue();
   return os;
 }
Variable Documentation
UpdateMethod DoNothing
Definition at line 35 of file COptItem.cpp.
Referenced by COptItem::compile().
C_FLOAT64 NaN = std::numeric_limits< C_FLOAT64 >::quiet_NaN()
Definition at line 33 of file COptItem.cpp.
Referenced by COptItem::compile(), COptItem::getRandomValue(), COptItem::getStartValue(), COptItem::initializeParameter(), and FPraxis::operator()().