COPASI API: CSparseMatrix Class Reference
CSparseMatrix Class Reference
#include <CSparseMatrix.h>
Public Member Functions
CSparseMatrix (const size_t &rows=0, const size_t &cols=0)
CSparseMatrix (const CCompressedColumnFormat &ccf)
const std::vector< std::vector
< CSparseMatrixElement * > > & getColumns () const
std::vector< std::vector
< CSparseMatrixElement * > > & getColumns ()
const std::vector< std::vector
< CSparseMatrixElement * > > & getRows () const
std::vector< std::vector
< CSparseMatrixElement * > > & getRows ()
const C_FLOAT64 & getTreshold () const
bool insert (const size_t &row, const size_t &col, const C_FLOAT64 &value)
const size_t & numCols () const
size_t numNonZeros () const
const size_t & numRows () const
operator const CMatrix< C_FLOAT64 > () const
CSparseMatrixElement & operator() (const size_t &row, const size_t &col)
const CSparseMatrixElement & operator() (const size_t &row, const size_t &col) const
CSparseMatrix & operator= (const CCompressedColumnFormat &ccf)
CSparseMatrix & operator= (const CMatrix< C_FLOAT64 > &matrix)
bool remove (const size_t &row, const size_t &col)
bool resize (const size_t &rows, const size_t &columns)
bool setTreshold (const C_FLOAT64 &threshold)
~CSparseMatrix ()
Private Member Functions
void cleanup ()
Private Attributes
std::vector< size_t > mColIndex
std::vector< std::vector
< CSparseMatrixElement * > > mCols
CSparseMatrixElement mElement
size_t mNumCols
size_t mNumRows
std::vector< size_t > mRowIndex
std::vector< std::vector
< CSparseMatrixElement * > > mRows
size_t mSearchCol
size_t mSearchRow
C_FLOAT64 mThreshold
Friends
std::ostream & operator<< (std::ostream &os, const CSparseMatrix &A)
Detailed Description
Definition at line 67 of file CSparseMatrix.h.
Constructor & Destructor Documentation
CSparseMatrix::CSparseMatrix (const size_t & rows = 0, const size_t & cols = 0)
Definition at line 78 of file CSparseMatrix.cpp.
References resize().
                                                  :
   mThreshold(std::numeric_limits< C_FLOAT64 >::epsilon()),
   mNumRows(0),
   mNumCols(0),
   mRowIndex(),
   mColIndex(),
   mRows(),
   mCols(),
   mSearchRow(0),
   mSearchCol(0),
   mElement(*this, this->mSearchRow, this->mSearchCol, 0.0)
 {resize(rows, cols);}
CSparseMatrix::CSparseMatrix (const CCompressedColumnFormat & ccf)
Definition at line 92 of file CSparseMatrix.cpp.
                                                                :
   mThreshold(std::numeric_limits< C_FLOAT64 >::epsilon()),
   mNumRows(0),
   mNumCols(0),
   mRowIndex(),
   mColIndex(),
   mRows(),
   mCols(),
   mSearchRow(0),
   mSearchCol(0),
   mElement(*this, this->mSearchRow, this->mSearchCol, 0.0)
 {*this = ccf;}
CSparseMatrix::~CSparseMatrix ()
Definition at line 105 of file CSparseMatrix.cpp.
References cleanup().
 {cleanup();}
Member Function Documentation
void CSparseMatrix::cleanup () private
Definition at line 108 of file CSparseMatrix.cpp.
References mRows.
Referenced by ~CSparseMatrix().
 {
   std::vector< std::vector< CSparseMatrixElement * > >::iterator itRow;
   std::vector< std::vector< CSparseMatrixElement * > >::iterator endRow;
   std::vector< CSparseMatrixElement * >::iterator itElement;
   std::vector< CSparseMatrixElement * >::iterator endElement;
   for (itRow = mRows.begin(), endRow = mRows.end(); itRow != endRow; ++itRow)
     for (itElement = itRow->begin(), endElement = itRow->end(); itElement != endElement; ++itElement)
       delete *itElement;
 }
const std::vector< std::vector< CSparseMatrixElement * > > & CSparseMatrix::getColumns () const
Definition at line 162 of file CSparseMatrix.cpp.
References mCols.
Referenced by CCompressedColumnFormat::operator=().
 {return mCols;}
std::vector< std::vector< CSparseMatrixElement * > > & CSparseMatrix::getColumns ()
Definition at line 165 of file CSparseMatrix.cpp.
References mCols.
 {return mCols;}
const std::vector< std::vector< CSparseMatrixElement * > > & CSparseMatrix::getRows () const
Definition at line 168 of file CSparseMatrix.cpp.
References mRows.
 {return mRows;}
std::vector< std::vector< CSparseMatrixElement * > > & CSparseMatrix::getRows ()
Definition at line 171 of file CSparseMatrix.cpp.
References mRows.
 {return mRows;}
const C_FLOAT64 & CSparseMatrix::getTreshold () const
Definition at line 279 of file CSparseMatrix.cpp.
References mThreshold.
Referenced by CSparseMatrixElement::operator=().
 {return mThreshold;}
bool CSparseMatrix::insert (const size_t & row, const size_t & col, const C_FLOAT64 & value)
Definition at line 312 of file CSparseMatrix.cpp.
References CSparseMatrixElement::compareCol(), CSparseMatrixElement::compareRow(), mColIndex, mCols, mElement, mRowIndex, mRows, mSearchCol, and mSearchRow.
Referenced by CSparseMatrixElement::operator=().
 {
   mSearchRow = row;
   mSearchCol = col;
   std::vector< CSparseMatrixElement * >::iterator found
   = std::lower_bound(mCols[col].begin(), mCols[col].end(), &mElement, CSparseMatrixElement::compareRow);
   if (found != mCols[col].end() &&
       (*found)->row() == row) return false; // The element already exists.
   CSparseMatrixElement * pElement = new CSparseMatrixElement(*this, mRowIndex[row], mColIndex[col], value);
   mCols[col].insert(found, pElement);
   found = std::lower_bound(mRows[row].begin(), mRows[row].end(), &mElement, CSparseMatrixElement::compareCol);
   mRows[row].insert(found, pElement);
   return true;
 }
const size_t & CSparseMatrix::numCols () const
Definition at line 146 of file CSparseMatrix.cpp.
References mNumCols.
Referenced by CCompressedColumnFormat::operator=().
 {return mNumCols;}
size_t CSparseMatrix::numNonZeros () const
Definition at line 149 of file CSparseMatrix.cpp.
References mRows.
Referenced by CCompressedColumnFormat::operator=().
 {
   size_t NonZeros = 0;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator itRow;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator endRow;
   for (itRow = mRows.begin(), endRow = mRows.end(); itRow != endRow; ++itRow)
     NonZeros += itRow->size();
   return NonZeros;
 }
const size_t & CSparseMatrix::numRows () const
Definition at line 143 of file CSparseMatrix.cpp.
References mNumRows.
Referenced by CCompressedColumnFormat::operator=().
 {return mNumRows;}
CSparseMatrix::operator const CMatrix< C_FLOAT64 > () const
Definition at line 226 of file CSparseMatrix.cpp.
References CMatrix< CType >::array(), C_FLOAT64, and CMatrix< CType >::resize().
 {
   CMatrix< C_FLOAT64 > M;
   M.resize(mNumRows, mNumCols);
   C_FLOAT64 * pTmp = M.array();
   size_t i;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator itRow;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator endRow;
   std::vector< CSparseMatrixElement * >::const_iterator itElement;
   std::vector< CSparseMatrixElement * >::const_iterator endElement;
   for (itRow = mRows.begin(), endRow = mRows.end(); itRow != endRow; ++itRow)
     {
       for (i = 0, itElement = itRow->begin(), endElement = itRow->end();
            itElement != endElement; ++itElement, i++, pTmp++)
         {
           for (; i < (*itElement)->col(); i++, pTmp++)
             *pTmp = 0.0;
           *pTmp = **itElement;
         }
       for (; i < mNumCols; i++, pTmp++)
         *pTmp = 0.0;
     }
   return M;
 }
CSparseMatrixElement & CSparseMatrix::operator() (const size_t & row, const size_t & col)
Definition at line 282 of file CSparseMatrix.cpp.
References CSparseMatrixElement::compareRow(), mCols, mElement, mSearchCol, and mSearchRow.
 {
   mSearchRow = row;
   mSearchCol = col;
   std::vector< CSparseMatrixElement * >::iterator found
   = std::lower_bound(mCols[col].begin(), mCols[col].end(), &mElement, CSparseMatrixElement::compareRow);
   if (found != mCols[col].end() &&
       (*found)->row() == row) return **found;
   return mElement;
 }
const CSparseMatrixElement & CSparseMatrix::operator() (const size_t & row, const size_t & col) const
Definition at line 297 of file CSparseMatrix.cpp.
References CSparseMatrixElement::compareRow(), mCols, mElement, mSearchCol, and mSearchRow.
 {
   const_cast<CSparseMatrix *>(this)->mSearchRow = row;
   const_cast<CSparseMatrix *>(this)->mSearchCol = col;
   std::vector< CSparseMatrixElement * >::const_iterator found
   = std::lower_bound(mCols[col].begin(), mCols[col].end(), &mElement, CSparseMatrixElement::compareRow);
   if (found != mCols[col].end() &&
       (*found)->row() == row) return **found;
   return mElement;
 }
CSparseMatrix & CSparseMatrix::operator= (const CCompressedColumnFormat & ccf)
Definition at line 174 of file CSparseMatrix.cpp.
References C_FLOAT64, CSparseMatrixElement::compareCol(), CCompressedColumnFormat::getColumnStart(), CCompressedColumnFormat::getRowIndex(), CCompressedColumnFormat::getValues(), mColIndex, mCols, mNumCols, mNumRows, mRowIndex, mRows, CCompressedColumnFormat::numCols(), CCompressedColumnFormat::numRows(), and resize().
 {
   resize(ccf.numRows(), ccf.numCols());
   const C_FLOAT64 * pValue = ccf.getValues();
   const size_t * pRowIndex = ccf.getRowIndex();
   const size_t * pColumnStart = ccf.getColumnStart() + 1;
   size_t i, j, k;
   CSparseMatrixElement * pElement;
   for (j = 0, i = 0; j < mNumCols; j++, pColumnStart++)
     {
       mCols[j].resize(*pColumnStart - * (pColumnStart - 1));
       for (k = 0; i < *pColumnStart; i++, k++, pRowIndex++, pValue++)
         {
           pElement = new CSparseMatrixElement(*this, mRowIndex[*pRowIndex], mColIndex[j], *pValue);
           mCols[j][k] = pElement;
           mRows[*pRowIndex].push_back(pElement); // Note, these are out of order and must be sorted.
         }
     }
   for (i = 0; i < mNumRows; i++)
     std::sort(mRows[i].begin(), mRows[i].end(), &CSparseMatrixElement::compareCol);
   return *this;
 }
CSparseMatrix & CSparseMatrix::operator= (const CMatrix< C_FLOAT64 > & matrix)
Definition at line 203 of file CSparseMatrix.cpp.
References CMatrix< CType >::array(), C_FLOAT64, CSparseMatrixElement::compareRow(), mColIndex, mCols, mNumCols, mNumRows, mRowIndex, mRows, mThreshold, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), and resize().
 {
   size_t i, j;
   CSparseMatrixElement * pElement;
   resize(matrix.numRows(), matrix.numCols());
   const C_FLOAT64 * pTmp = matrix.array();
   for (i = 0; i < mNumRows; i++)
     for (j = 0; j < mNumCols; j++, pTmp++)
       if (fabs(*pTmp) >= mThreshold)
         {
           pElement = new CSparseMatrixElement(*this, mRowIndex[i], mColIndex[j], *pTmp);
           mRows[i].push_back(pElement);
           mCols[j].push_back(pElement); // Note, these are out of order and must be sorted.
         }
   for (j = 0; j < mNumCols; j++)
     std::sort(mCols[j].begin(), mCols[j].end(), &CSparseMatrixElement::compareRow);
   return *this;
 }
bool CSparseMatrix::remove (const size_t & row, const size_t & col)
Definition at line 334 of file CSparseMatrix.cpp.
References CSparseMatrixElement::compareCol(), CSparseMatrixElement::compareRow(), mCols, mElement, mRows, mSearchCol, and mSearchRow.
Referenced by CSparseMatrixElement::operator=().
 {
   mSearchRow = row;
   mSearchCol = col;
   std::vector< CSparseMatrixElement * >::iterator found
   = std::lower_bound(mCols[col].begin(), mCols[col].end(), &mElement, CSparseMatrixElement::compareRow);
   if (found == mCols[col].end()) return false; // The element does not exist.
   mCols[col].erase(found);
   found = std::lower_bound(mRows[row].begin(), mRows[row].end(), &mElement, CSparseMatrixElement::compareCol);
   mRows[row].erase(found);
   delete *found;
   return true;
 }
bool CSparseMatrix::resize (const size_t & rows, const size_t & columns)
Definition at line 121 of file CSparseMatrix.cpp.
References mColIndex, mCols, mNumCols, mNumRows, mRowIndex, and mRows.
Referenced by CSparseMatrix(), and operator=().
 {
   size_t i;
   mNumRows = rows;
   mNumCols = cols;
   mRowIndex.resize(mNumRows);
   for (i = 0; i < mNumRows; i++)
     mRowIndex[i] = i;
   mColIndex.resize(mNumCols);
   for (i = 0; i < mNumCols; i++)
     mColIndex[i] = i;
   mRows.resize(mNumRows);
   mCols.resize(mNumCols);
   return true;
 }
bool CSparseMatrix::setTreshold (const C_FLOAT64 & threshold)
Definition at line 258 of file CSparseMatrix.cpp.
References mRows, and mThreshold.
 {
   if (threshold < mThreshold)
     {
       std::vector< std::vector< CSparseMatrixElement * > >::iterator itRow;
       std::vector< std::vector< CSparseMatrixElement * > >::iterator endRow;
       std::vector< CSparseMatrixElement * >::reverse_iterator itElement;
       std::vector< CSparseMatrixElement * >::reverse_iterator endElement;
       for (itRow = mRows.begin(), endRow = mRows.end(); itRow != endRow; ++itRow)
         for (itElement = itRow->rbegin(), endElement = itRow->rend(); itElement != endElement; ++itElement)
           if (fabs(**itElement) < threshold)
             remove((*itElement)->row(), (*itElement)->col());
     }
   mThreshold = threshold;
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CSparseMatrix & A) friend
Definition at line 355 of file CSparseMatrix.cpp.
 {
   os << "Matrix(" << A.mNumRows << "x" << A.mNumCols << ")" << std::endl;
   size_t i;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator itRow;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator endRow;
   std::vector< CSparseMatrixElement * >::const_iterator itElement;
   std::vector< CSparseMatrixElement * >::const_iterator endElement;
   for (itRow = A.mRows.begin(), endRow = A.mRows.end(); itRow != endRow; ++itRow)
     {
       for (i = 0, itElement = itRow->begin(), endElement = itRow->end();
            itElement != endElement; ++itElement, i++)
         {
           for (; i < (*itElement)->col(); i++)
             os << "\t" << 0.0;
           os << "\t" << **itElement;
         }
       for (; i < A.mNumCols; i++)
         os << "\t" << 0.0;
       os << std::endl;
     }
   return os;
 }
Member Data Documentation
std::vector< size_t> CSparseMatrix::mColIndex private
Definition at line 118 of file CSparseMatrix.h.
Referenced by insert(), operator=(), and resize().
std::vector< std::vector< CSparseMatrixElement *> > CSparseMatrix::mCols private
Definition at line 121 of file CSparseMatrix.h.
Referenced by getColumns(), insert(), operator()(), operator=(), remove(), and resize().
CSparseMatrixElement CSparseMatrix::mElement private
Definition at line 125 of file CSparseMatrix.h.
Referenced by insert(), operator()(), and remove().
size_t CSparseMatrix::mNumCols private
Definition at line 115 of file CSparseMatrix.h.
Referenced by numCols(), operator<<(), operator=(), and resize().
size_t CSparseMatrix::mNumRows private
Definition at line 114 of file CSparseMatrix.h.
Referenced by numRows(), operator<<(), operator=(), and resize().
std::vector< size_t > CSparseMatrix::mRowIndex private
Definition at line 117 of file CSparseMatrix.h.
Referenced by insert(), operator=(), and resize().
std::vector< std::vector< CSparseMatrixElement *> > CSparseMatrix::mRows private
Definition at line 120 of file CSparseMatrix.h.
Referenced by cleanup(), getRows(), insert(), numNonZeros(), operator<<(), operator=(), remove(), resize(), and setTreshold().
size_t CSparseMatrix::mSearchCol private
Definition at line 124 of file CSparseMatrix.h.
Referenced by insert(), operator()(), and remove().
size_t CSparseMatrix::mSearchRow private
Definition at line 123 of file CSparseMatrix.h.
Referenced by insert(), operator()(), and remove().
C_FLOAT64 CSparseMatrix::mThreshold private
Definition at line 112 of file CSparseMatrix.h.
Referenced by getTreshold(), operator=(), and setTreshold().
The documentation for this class was generated from the following files:
CSparseMatrix.h
CSparseMatrix.cpp