COPASI API: BandedGraphWidget Class Reference
BandedGraphWidget Class Reference
#include <BandedGraphWidget.h>
Public Member Functions
BandedGraphWidget (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
virtual bool LoadFromCurveSpec (const CPlotItem *curve)
virtual bool SaveToCurveSpec (CPlotItem *curve, const CPlotItem *original=NULL) const
virtual void setMultipleEditMode (bool mode)
~BandedGraphWidget ()
Public Member Functions inherited from CQPlotEditWidget
CQPlotEditWidget (QWidget *parent=NULL, Qt::WindowFlags fl=0)
virtual void setModel (const CModel *model)
virtual ~CQPlotEditWidget ()
Protected Slots
virtual void buttonPressedX ()
virtual void buttonPressedY ()
void buttonPressedYone ()
void buttonPressedYtwo ()
Protected Attributes
const CCopasiObject * mpObjectX
const CCopasiObject * mpObjectYone
const CCopasiObject * mpObjectYtwo
Protected Attributes inherited from CQPlotEditWidget
const CModel * mpModel
Detailed Description
Definition at line 18 of file BandedGraphWidget.h.
Constructor & Destructor Documentation
BandedGraphWidget::BandedGraphWidget (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 36 of file BandedGraphWidget.cpp.
References CQIconResource::copasi, and CQIconResource::icon().
                                                                                     :
   CQPlotEditWidget(parent, fl),
   mpObjectYone(NULL),
   mpObjectYtwo(NULL),
   mpObjectX(NULL)
 {
   setupUi(this);
   mpBtnX->setIcon(CQIconResource::icon(CQIconResource::copasi));
   mpBtnYone->setIcon(CQIconResource::icon(CQIconResource::copasi));
   mpBtnYtwo->setIcon(CQIconResource::icon(CQIconResource::copasi));
 }
BandedGraphWidget::~BandedGraphWidget ()
Definition at line 52 of file BandedGraphWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void BandedGraphWidget::buttonPressedX () protected virtual slot
Definition at line 189 of file BandedGraphWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQPlotEditWidget::mpModel, mpObjectX, mpObjectYone, mpObjectYtwo, and CQSimpleSelectionTree::NumericValues.
 {
   if (!mpModel) return;
   mpObjectX = CCopasiSelectionDialog::getObjectSingle(this,
               CQSimpleSelectionTree::NumericValues,
               mpObjectX);
   if (mpObjectX)
     {
       mpEditX->setText(FROM_UTF8(mpObjectX->getObjectDisplayName()));
       if (mpObjectYone)
         if (mpObjectYtwo && (mpObjectYtwo != mpObjectYone))
           mpEditTitle->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()
                                          + "/"
                                          + mpObjectYtwo->getObjectDisplayName()
                                          + "|"
                                          + mpObjectX->getObjectDisplayName()));
         else
           mpEditTitle->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()
                                          + "|"
                                          + mpObjectX->getObjectDisplayName()));
       //TODO update tab title
     }
   else
     mpEditX->setText("");
 }
virtual void BandedGraphWidget::buttonPressedY () inline protected virtual slot
Definition at line 42 of file BandedGraphWidget.h.
References buttonPressedYone().
 {buttonPressedYone();};
void BandedGraphWidget::buttonPressedYone () protected slot
Definition at line 220 of file BandedGraphWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQPlotEditWidget::mpModel, mpObjectX, mpObjectYone, mpObjectYtwo, and CQSimpleSelectionTree::NumericValues.
Referenced by buttonPressedY().
 {
   if (!mpModel) return;
   mpObjectYone = CCopasiSelectionDialog::getObjectSingle(this,
                  CQSimpleSelectionTree::NumericValues,
                  mpObjectYone);
   if (mpObjectYone)
     {
       mpEditYone->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()));
       if (mpObjectX)
         if (mpObjectYtwo && (mpObjectYtwo != mpObjectYone))
           mpEditTitle->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()
                                          + "/"
                                          + mpObjectYtwo->getObjectDisplayName()
                                          + "|"
                                          + mpObjectX->getObjectDisplayName()));
         else
           mpEditTitle->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()
                                          + "|"
                                          + mpObjectX->getObjectDisplayName()));
       //TODO update tab title
     }
   else
     mpEditYone->setText("");
 }
void BandedGraphWidget::buttonPressedYtwo () protected slot
Definition at line 251 of file BandedGraphWidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQPlotEditWidget::mpModel, mpObjectX, mpObjectYone, mpObjectYtwo, and CQSimpleSelectionTree::NumericValues.
 {
   if (!mpModel) return;
   mpObjectYtwo = CCopasiSelectionDialog::getObjectSingle(this,
                  CQSimpleSelectionTree::NumericValues,
                  mpObjectYtwo);
   if (mpObjectYtwo)
     {
       mpEditYtwo->setText(FROM_UTF8(mpObjectYtwo->getObjectDisplayName()));
       if (mpObjectX)
         if (mpObjectYone && (mpObjectYone != mpObjectYtwo))
           mpEditTitle->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()
                                          + "/"
                                          + mpObjectYtwo->getObjectDisplayName()
                                          + "|"
                                          + mpObjectX->getObjectDisplayName()));
         else
           mpEditTitle->setText(FROM_UTF8(mpObjectYtwo->getObjectDisplayName()
                                          + "|"
                                          + mpObjectX->getObjectDisplayName()));
       //TODO update tab title
     }
   else
     mpEditYtwo->setText("");
 }
bool BandedGraphWidget::LoadFromCurveSpec (const CPlotItem * curve) virtual
Implements CQPlotEditWidget.
Definition at line 58 of file BandedGraphWidget.cpp.
References COutputInterface::AFTER, CPlotItem::bandedGraph, COutputInterface::BEFORE, COutputInterface::DURING, FROM_UTF8, CPlotItem::getActivity(), CPlotItem::getChannels(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDisplayName(), CPlotItem::getTitle(), CPlotItem::getType(), CCopasiParameterGroup::getValue(), mpObjectX, mpObjectYone, mpObjectYtwo, and CCopasiParameter::Value::pVOID.
 {
   if (!curve)
     {
       // We need to reset the widget to defaults
       mpEditTitle->setText("");
       mpObjectX = mpObjectYone = mpObjectYtwo = NULL;
       mpEditX->setText("");
       mpEditYone->setText("");
       mpEditYtwo->setText("");
       mpCheckBefore->setChecked(false);
       mpCheckDuring->setChecked(true);
       mpCheckAfter->setChecked(false);
       return true;
     }
   if (curve->getType() != CPlotItem::bandedGraph) return false;
   //if (curve->getChannels().getSize != 3) return false;
   mpEditTitle->setText(FROM_UTF8(curve->getTitle()));
   //TODO: check if objects exist....
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   mpObjectX = mpObjectYone = mpObjectYtwo = NULL;
   if (curve->getChannels().size() >= 1)
     mpObjectX = pDataModel->getDataObject(curve->getChannels()[0]);
   if (curve->getChannels().size() >= 2)
     mpObjectYone = pDataModel->getDataObject(curve->getChannels()[1]);
   if (curve->getChannels().size() >= 3)
     {
       mpObjectYtwo = pDataModel->getDataObject(curve->getChannels()[2]);
       if ((mpObjectYtwo->getObjectDisplayName() == "(CN)Root") && mpObjectYone)
         mpObjectYtwo = mpObjectYone;  // as long as we haven't a second Y-axis chooser, this has to suffice.
     }
   if (mpObjectX)
     mpEditX->setText(FROM_UTF8(mpObjectX->getObjectDisplayName()));
   if (mpObjectYone)
     mpEditYone->setText(FROM_UTF8(mpObjectYone->getObjectDisplayName()));
   if (mpObjectYtwo)
     mpEditYtwo->setText(FROM_UTF8(mpObjectYtwo->getObjectDisplayName()));
   const void* tmp;
   if (!(tmp = curve->getValue("Line type").pVOID)) return false;
   mpCheckBefore->setChecked(curve->getActivity() & COutputInterface::BEFORE);
   mpCheckDuring->setChecked(curve->getActivity() & COutputInterface::DURING);
   mpCheckAfter->setChecked(curve->getActivity() & COutputInterface::AFTER);
   return true;
 }
bool BandedGraphWidget::SaveToCurveSpec (CPlotItem * curve, const CPlotItem * original = NULL) const virtual
Implements CQPlotEditWidget.
Definition at line 125 of file BandedGraphWidget.cpp.
References COutputInterface::AFTER, CPlotItem::bandedGraph, COutputInterface::BEFORE, C_INT32, COutputInterface::DURING, CPlotItem::getActivity(), CPlotItem::getChannels(), CCopasiObject::getCN(), CPlotItem::getTitle(), CPlotItem::getType(), mpObjectX, mpObjectYone, mpObjectYtwo, CPlotItem::setActivity(), CPlotItem::setTitle(), and TO_UTF8.
 {
   //curve->setType(CPlotItem::bandedGraph);
   std::string title = TO_UTF8(mpEditTitle->text());
   CCopasiObjectName xName = mpObjectX ? mpObjectX->getCN() : CCopasiObjectName("");
   CCopasiObjectName yName1 = mpObjectYone ? mpObjectYone->getCN() : CCopasiObjectName("");
   CCopasiObjectName yName2 = mpObjectYtwo ? mpObjectYtwo->getCN() : (mpObjectYone ? mpObjectYone->getCN() : CCopasiObjectName(""));
   C_INT32 Activity = 0;
   if (mpCheckBefore->isChecked()) Activity += COutputInterface::BEFORE;
   if (mpCheckDuring->isChecked()) Activity += COutputInterface::DURING;
   if (mpCheckAfter->isChecked()) Activity += COutputInterface::AFTER;
   bool thingsChanged = false;
   if (original != NULL)
     {
       // compare whether things changed
       if (original->getTitle() != title)
         thingsChanged = true;
       if (thingsChanged || original->getType() != CPlotItem::bandedGraph)
         thingsChanged = true;
       if (thingsChanged || original->getActivity() != Activity)
         thingsChanged = true;
       if (thingsChanged || original->getChannels().size() != 3)
         thingsChanged = true;
       if (thingsChanged || original->getChannels()[0] != xName)
         thingsChanged = true;
       if (thingsChanged || original->getChannels()[1] != yName1)
         thingsChanged = true;
       if (thingsChanged || original->getChannels()[2] != yName2)
         thingsChanged = true;
     }
   else thingsChanged = true;
   if (!thingsChanged)
     return false;
   //title
   curve->setTitle(title);
   //channels
   curve->getChannels().clear();
   curve->getChannels().push_back(CPlotDataChannelSpec(xName));
   curve->getChannels().push_back(CPlotDataChannelSpec(yName1));
   curve->getChannels().push_back(CPlotDataChannelSpec(yName2));
   curve->setActivity((COutputInterface::Activity) Activity);
   return true;
 }
void BandedGraphWidget::setMultipleEditMode (bool mode) virtual
In multiple edit mode, we don't want to edit name & channels
Implements CQPlotEditWidget.
Definition at line 21 of file BandedGraphWidget.cpp.
 {
   mpEditTitle->setEnabled(!mode);
   mpEditX->setEnabled(!mode);
   mpEditYone->setEnabled(!mode);
   mpEditYtwo->setEnabled(!mode);
   mpBtnX->setEnabled(!mode);
   mpBtnYone->setEnabled(!mode);
   mpBtnYtwo->setEnabled(!mode);
 }
Member Data Documentation
const CCopasiObject* BandedGraphWidget::mpObjectX protected
Definition at line 37 of file BandedGraphWidget.h.
Referenced by buttonPressedX(), buttonPressedYone(), buttonPressedYtwo(), LoadFromCurveSpec(), and SaveToCurveSpec().
const CCopasiObject* BandedGraphWidget::mpObjectYone protected
Definition at line 35 of file BandedGraphWidget.h.
Referenced by buttonPressedX(), buttonPressedYone(), buttonPressedYtwo(), LoadFromCurveSpec(), and SaveToCurveSpec().
const CCopasiObject* BandedGraphWidget::mpObjectYtwo protected
Definition at line 36 of file BandedGraphWidget.h.
Referenced by buttonPressedX(), buttonPressedYone(), buttonPressedYtwo(), LoadFromCurveSpec(), and SaveToCurveSpec().
The documentation for this class was generated from the following files:
BandedGraphWidget.h
BandedGraphWidget.cpp