COPASI API: CEvaluationParserBase Class Reference
CEvaluationParserBase Class Reference abstract
#include <CEvaluationLexer.h>
Public Member Functions
CEvaluationParserBase ()
size_t getErrorPosition ()
std::vector< CEvaluationNode * > * getNodeList ()
CEvaluationNode * getRootNode ()
bool isBoolean () const
virtual int yylex ()=0
virtual int yyparse ()
virtual ~CEvaluationParserBase ()
Static Public Member Functions
static void freeNodeList (std::vector< CEvaluationNode * > *pNodeList)
Protected Attributes
bool mBoolean
CEvaluationNode * mpNode
std::vector< CEvaluationNode * > * mpNodeList
size_t mPosition
CEvaluationNode * mpRootNode
Private Member Functions
void correctErrorPosition ()
Detailed Description
This is a base class for the CEvaluationLexer adding member attributes to enhance the internal functionality.
Definition at line 39 of file CEvaluationLexer.h.
Constructor & Destructor Documentation
CEvaluationParserBase::CEvaluationParserBase () inline
Default constructor
Definition at line 45 of file CEvaluationLexer.h.
                 :
     mpNode(NULL),
     mpRootNode(NULL),
     mBoolean(false),
     mpNodeList(NULL),
     mPosition(0)
   {}
virtual CEvaluationParserBase::~CEvaluationParserBase () inline virtual
Destructor
Definition at line 56 of file CEvaluationLexer.h.
 {}
Member Function Documentation
void CEvaluationParserBase::correctErrorPosition () inline private
Definition at line 108 of file CEvaluationLexer.h.
   {
     std::vector< CEvaluationNode * >::iterator it
     = mpNodeList->begin();
     std::vector< CEvaluationNode * >::iterator end
     = mpNodeList->end();
     size_t oldPosition = mPosition;
     mPosition = 0;
     for (; it != end && mPosition < oldPosition; ++it)
       mPosition += (*it)->getData().length();
     if (mPosition > 0)
       mPosition -= (*--it)->getData().length();
   }
static void CEvaluationParserBase::freeNodeList (std::vector< CEvaluationNode * > * pNodeList) inline static
Convenient function to free the list of generated nodes.
Parameters
std::vector< CEvaluationNode * > * pNodeList
Definition at line 73 of file CEvaluationLexer.h.
References pdelete.
Referenced by CEvaluationTree::parse(), CEvaluationTree::setRoot(), CEvaluationTree::updateTree(), and CEvaluationTree::~CEvaluationTree().
   {
     if (pNodeList == NULL) return;
     std::vector< CEvaluationNode * >::iterator it;
     std::vector< CEvaluationNode * >::iterator end = pNodeList->end();
     for (it = pNodeList->begin(); it != end; ++it)
       if (*it && (*it)->getParent())
         (*it)->getParent()->removeChild(*it);
     for (it = pNodeList->begin(); it != end; ++it)
       pdelete(*it);
     pdelete(pNodeList);
   }
size_t CEvaluationParserBase::getErrorPosition () inline
Definition at line 98 of file CEvaluationLexer.h.
Referenced by CEvaluationTree::parse().
 {return mPosition;}
std::vector< CEvaluationNode * >* CEvaluationParserBase::getNodeList () inline
Retrieve the generated list of nodes. The user owns the list and is repsonsible for the destruction. To delete the list please use freeNodeList. Please note that each call to yylex() creates a new list which must be destoyed.
Returns
std::vector< CEvaluationNode * > * pNodeList
Definition at line 66 of file CEvaluationLexer.h.
Referenced by CEvaluationTree::parse().
   {return mpNodeList;}
CEvaluationNode* CEvaluationParserBase::getRootNode () inline
Definition at line 94 of file CEvaluationLexer.h.
Referenced by CEvaluationTree::parse().
 {return mpRootNode;}
bool CEvaluationParserBase::isBoolean () const inline
Definition at line 96 of file CEvaluationLexer.h.
 {return mBoolean;}
virtual int CEvaluationParserBase::yylex () pure virtual
Implemented in CEvaluationLexer.
int CEvaluationParserBase::yyparse () virtual
Definition at line 1324 of file CEvaluationParser_yacc.cpp.
References setBooleanRequired(), YY_, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYID, YYINITDEPTH, YYLAST, YYLEX, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, yypact_value_is_default, YYPOPSTACK, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYSTYPE, yytable_value_is_error, YYTERROR, YYTRANSLATE, and yyalloc::yyvs_alloc.
Referenced by CEvaluationTree::parse().
 {
   int yystate;
   /* Number of tokens to shift before error messages enabled.  */
   int yyerrstatus;
   /* The stacks and their tools:
      `yyss': related to states.
      `yyvs': related to semantic values.
      Refer to the stacks through separate pointers, to allow yyoverflow
      to reallocate them elsewhere.  */
   /* The state stack.  */
   yytype_int16 yyssa[YYINITDEPTH];
   yytype_int16 *yyss;
   yytype_int16 *yyssp;
   /* The semantic value stack.  */
   YYSTYPE yyvsa[YYINITDEPTH];
   YYSTYPE *yyvs;
   YYSTYPE *yyvsp;
   YYSIZE_T yystacksize;
   int yyn;
   int yyresult;
   /* Lookahead token as an internal (translated) token number.  */
   int yytoken = 0;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   yyssp = yyss = yyssa;
   yyvsp = yyvs = yyvsa;
   yystacksize = YYINITDEPTH;
   YYDPRINTF((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY; /* Cause a token to be read.  */
   goto yysetstate;
   /*------------------------------------------------------------.
   | yynewstate -- Push a new state, which is found in yystate.  |
   `------------------------------------------------------------*/
 yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
 yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         YYSTYPE *yyvs1 = yyvs;
         yytype_int16 *yyss1 = yyss;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow(YY_("memory exhausted"),
                    &yyss1, yysize * sizeof(*yyssp),
                    &yyvs1, yysize * sizeof(*yyvsp),
                    &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyexhaustedlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yytype_int16 *yyss1 = yyss;
         union yyalloc *yyptr =
             (union yyalloc *) YYSTACK_ALLOC(YYSTACK_BYTES(yystacksize));
         if (! yyptr)
           goto yyexhaustedlab;
         YYSTACK_RELOCATE(yyss_alloc, yyss);
         YYSTACK_RELOCATE(yyvs_alloc, yyvs);
 #  undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE(yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
   YYDPRINTF((stderr, "Entering state %d\n", yystate));
   if (yystate == YYFINAL)
     YYACCEPT;
   goto yybackup;
   /*-----------.
   | yybackup.  |
   `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      lookahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to lookahead token.  */
   yyn = yypact[yystate];
   if (yypact_value_is_default(yyn))
     goto yydefault;
   /* Not known => get a lookahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF((stderr, "Reading a token: "));
       yychar = YYLEX;
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE(yychar);
       YY_SYMBOL_PRINT("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yytable_value_is_error(yyn))
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the lookahead token.  */
   YY_SYMBOL_PRINT("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token.  */
   yychar = YYEMPTY;
   yystate = yyn;
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   goto yynewstate;
   /*-----------------------------------------------------------.
   | yydefault -- do the default action for the current state.  |
   `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
   /*-----------------------------.
   | yyreduce -- Do a reduction.  |
   `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      `$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1 - yylen];
   YY_REDUCE_PRINT(yyn);
   switch (yyn)
     {
       case 2:
         /* Line 1778 of yacc.c  */
 #line 93 "CEvaluationParser.ypp"
         {
           mBoolean = false;
           mpRootNode = (yyval);
         }
         break;
       case 3:
         /* Line 1778 of yacc.c  */
 #line 98 "CEvaluationParser.ypp"
         {
           mBoolean = true;
           mpRootNode = (yyval);
         }
         break;
       case 4:
         /* Line 1778 of yacc.c  */
 #line 104 "CEvaluationParser.ypp"
         {
           mpRootNode = (yyvsp[(1) - (1)]);
         }
         break;
       case 5:
         /* Line 1778 of yacc.c  */
 #line 108 "CEvaluationParser.ypp"
         {
           mpRootNode = (yyvsp[(1) - (1)]);
         }
         break;
       case 6:
         /* Line 1778 of yacc.c  */
 #line 112 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 7:
         /* Line 1778 of yacc.c  */
 #line 119 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 8:
         /* Line 1778 of yacc.c  */
 #line 126 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 9:
         /* Line 1778 of yacc.c  */
 #line 133 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 10:
         /* Line 1778 of yacc.c  */
 #line 140 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           mpRootNode = (yyval);
         }
         break;
       case 11:
         /* Line 1778 of yacc.c  */
 #line 145 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (4)]);
           (yyval)->addChild((yyvsp[(3) - (4)]));
           mpRootNode = (yyval);
         }
         break;
       case 12:
         /* Line 1778 of yacc.c  */
 #line 151 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (6)]);
           (yyval)->addChild((yyvsp[(3) - (6)]));
           (yyval)->addChild((yyvsp[(5) - (6)]));
           mpRootNode = (yyval);
         }
         break;
       case 13:
         /* Line 1778 of yacc.c  */
 #line 158 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (2)]);
           (yyval)->addChild((yyvsp[(2) - (2)]));
           mpRootNode = (yyval);
         }
         break;
       case 14:
         /* Line 1778 of yacc.c  */
 #line 164 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (8)]);
           (yyval)->addChild((yyvsp[(3) - (8)]));
           (yyval)->addChild((yyvsp[(5) - (8)]));
           (yyval)->addChild((yyvsp[(7) - (8)]));
           mpRootNode = (yyval);
         }
         break;
       case 15:
         /* Line 1778 of yacc.c  */
 #line 172 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (8)]);
           (yyval)->addChild((yyvsp[(3) - (8)]));
           (yyval)->addChild((yyvsp[(5) - (8)]));
           (yyval)->addChild((yyvsp[(7) - (8)]));
           mpRootNode = (yyval);
         }
         break;
       case 16:
         /* Line 1778 of yacc.c  */
 #line 180 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (1)]);
           mpRootNode = (yyval);
         }
         break;
       case 17:
         /* Line 1778 of yacc.c  */
 #line 186 "CEvaluationParser.ypp"
         {
           mpRootNode = (yyvsp[(1) - (1)]);
         }
         break;
       case 18:
         /* Line 1778 of yacc.c  */
 #line 190 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (8)]);
           (yyval)->addChild((yyvsp[(3) - (8)]));
           (yyval)->addChild((yyvsp[(5) - (8)]));
           (yyval)->addChild((yyvsp[(7) - (8)]));
           mpRootNode = (yyval);
         }
         break;
       case 19:
         /* Line 1778 of yacc.c  */
 #line 198 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (8)]);
           (yyval)->addChild((yyvsp[(3) - (8)]));
           (yyval)->addChild((yyvsp[(5) - (8)]));
           (yyval)->addChild((yyvsp[(7) - (8)]));
           mpRootNode = (yyval);
         }
         break;
       case 20:
         /* Line 1778 of yacc.c  */
 #line 206 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 21:
         /* Line 1778 of yacc.c  */
 #line 213 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 22:
         /* Line 1778 of yacc.c  */
 #line 221 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 23:
         /* Line 1778 of yacc.c  */
 #line 229 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 24:
         /* Line 1778 of yacc.c  */
 #line 236 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 25:
         /* Line 1778 of yacc.c  */
 #line 243 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 26:
         /* Line 1778 of yacc.c  */
 #line 251 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 27:
         /* Line 1778 of yacc.c  */
 #line 259 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 28:
         /* Line 1778 of yacc.c  */
 #line 266 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 29:
         /* Line 1778 of yacc.c  */
 #line 273 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 30:
         /* Line 1778 of yacc.c  */
 #line 280 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 31:
         /* Line 1778 of yacc.c  */
 #line 287 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 32:
         /* Line 1778 of yacc.c  */
 #line 294 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 33:
         /* Line 1778 of yacc.c  */
 #line 301 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 34:
         /* Line 1778 of yacc.c  */
 #line 309 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 35:
         /* Line 1778 of yacc.c  */
 #line 317 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 36:
         /* Line 1778 of yacc.c  */
 #line 326 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 37:
         /* Line 1778 of yacc.c  */
 #line 333 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 38:
         /* Line 1778 of yacc.c  */
 #line 341 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 39:
         /* Line 1778 of yacc.c  */
 #line 349 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 40:
         /* Line 1778 of yacc.c  */
 #line 358 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 41:
         /* Line 1778 of yacc.c  */
 #line 365 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 42:
         /* Line 1778 of yacc.c  */
 #line 373 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 43:
         /* Line 1778 of yacc.c  */
 #line 381 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(1) - (3)]), true);
           setBooleanRequired((yyvsp[(3) - (3)]), true);
           (yyval) = (yyvsp[(2) - (3)]);
           (yyval)->addChild((yyvsp[(1) - (3)]));
           (yyval)->addChild((yyvsp[(3) - (3)]));
           mpRootNode = (yyval);
         }
         break;
       case 44:
         /* Line 1778 of yacc.c  */
 #line 390 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           mpRootNode = (yyval);
         }
         break;
       case 45:
         /* Line 1778 of yacc.c  */
 #line 395 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (2)]);
           (yyval)->addChild((yyvsp[(2) - (2)]));
           mpRootNode = (yyval);
         }
         break;
       case 46:
         /* Line 1778 of yacc.c  */
 #line 401 "CEvaluationParser.ypp"
         {
           setBooleanRequired((yyvsp[(2) - (2)]), true);
           (yyval) = (yyvsp[(1) - (2)]);
           (yyval)->addChild((yyvsp[(2) - (2)]));
           mpRootNode = (yyval);
         }
         break;
       case 47:
         /* Line 1778 of yacc.c  */
 #line 409 "CEvaluationParser.ypp"
         {
           (yyval) = new CEvaluationNodeVector();
           mpNodeList->push_back((yyval));
         }
         break;
       case 48:
         /* Line 1778 of yacc.c  */
 #line 414 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (2)]);
         }
         break;
       case 49:
         /* Line 1778 of yacc.c  */
 #line 420 "CEvaluationParser.ypp"
         {
           (yyval) = new CEvaluationNodeVector();
           mpNodeList->push_back((yyval));
           (yyval)->addChild((yyvsp[(2) - (2)]));
         }
         break;
       case 50:
         /* Line 1778 of yacc.c  */
 #line 426 "CEvaluationParser.ypp"
         {
           (yyval) = new CEvaluationNodeVector();
           mpNodeList->push_back((yyval));
           (yyval)->addChild((yyvsp[(2) - (2)]));
         }
         break;
       case 51:
         /* Line 1778 of yacc.c  */
 #line 432 "CEvaluationParser.ypp"
         {
           (yyval)->addChild((yyvsp[(3) - (3)]));
         }
         break;
       case 52:
         /* Line 1778 of yacc.c  */
 #line 436 "CEvaluationParser.ypp"
         {
           (yyval)->addChild((yyvsp[(3) - (3)]));
         }
         break;
       case 53:
         /* Line 1778 of yacc.c  */
 #line 441 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (2)]);
         }
         break;
       case 54:
         /* Line 1778 of yacc.c  */
 #line 445 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (3)]);
           (yyval)->addChild((yyvsp[(2) - (3)]));
         }
         break;
       case 55:
         /* Line 1778 of yacc.c  */
 #line 450 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (3)]);
           (yyval)->addChild((yyvsp[(2) - (3)]));
         }
         break;
       case 56:
         /* Line 1778 of yacc.c  */
 #line 456 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (1)]);
         }
         break;
       case 57:
         /* Line 1778 of yacc.c  */
 #line 460 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (3)]);
           (yyval)->addChild((yyvsp[(2) - (3)]));
         }
         break;
       case 58:
         /* Line 1778 of yacc.c  */
 #line 465 "CEvaluationParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (3)]);
           (yyval)->addChild((yyvsp[(2) - (3)]));
         }
         break;
         /* Line 1778 of yacc.c  */
 #line 2145 "CEvaluationParser_yacc.cpppp"
       default: break;
     }
   /* User semantic actions sometimes alter yychar, and that requires
      that yytoken be updated with the new translation.  We take the
      approach of translating immediately before every use of yytoken.
      One alternative is translating here after every semantic action,
      but that translation would be missed if the semantic action invokes
      YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
      if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
      incorrect destructor might then be invoked immediately.  In the
      case of YYERROR or YYBACKUP, subsequent parser actions might lead
      to an incorrect destructor call or verbose syntax error message
      before the lookahead is translated.  */
   YY_SYMBOL_PRINT("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK(yylen);
   yylen = 0;
   YY_STACK_PRINT(yyss, yyssp);
   *++yyvsp = yyval;
   /* Now `shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
   /*------------------------------------.
   | yyerrlab -- here on detecting error |
   `------------------------------------*/
 yyerrlab:
   /* Make sure we have latest lookahead translation.  See comments at
      user semantic actions for why this is necessary.  */
   yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE(yychar);
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror(YY_("syntax error"));
 #else
 # define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                         yyssp, yytoken)
       {
         char const *yymsgp = YY_("syntax error");
         int yysyntax_error_status;
         yysyntax_error_status = YYSYNTAX_ERROR;
         if (yysyntax_error_status == 0)
           yymsgp = yymsg;
         else if (yysyntax_error_status == 1)
           {
             if (yymsg != yymsgbuf)
               YYSTACK_FREE(yymsg);
             yymsg = (char *) YYSTACK_ALLOC(yymsg_alloc);
             if (!yymsg)
               {
                 yymsg = yymsgbuf;
                 yymsg_alloc = sizeof yymsgbuf;
                 yysyntax_error_status = 2;
               }
             else
               {
                 yysyntax_error_status = YYSYNTAX_ERROR;
                 yymsgp = yymsg;
               }
           }
         yyerror(yymsgp);
         if (yysyntax_error_status == 2)
           goto yyexhaustedlab;
       }
 # undef YYSYNTAX_ERROR
 #endif
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse lookahead token after an
       error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct("Error: discarding",
                      yytoken, &yylval);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse lookahead token after shifting the error
      token.  */
   goto yyerrlab1;
   /*---------------------------------------------------.
   | yyerrorlab -- error raised explicitly by YYERROR.  |
   `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers like GCC when the user code never invokes
      YYERROR and the label yyerrorlab therefore never appears in user
      code.  */
   if (/*CONSTCOND*/ 0)
     goto yyerrorlab;
   /* Do not reclaim the symbols of the rule which action triggered
      this YYERROR.  */
   YYPOPSTACK(yylen);
   yylen = 0;
   YY_STACK_PRINT(yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
   /*-------------------------------------------------------------.
   | yyerrlab1 -- common code for both syntax error and YYERROR.  |
   `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;  /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (!yypact_value_is_default(yyn))
         {
           yyn += YYTERROR;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct("Error: popping",
                  yystos[yystate], yyvsp);
       YYPOPSTACK(1);
       yystate = *yyssp;
       YY_STACK_PRINT(yyss, yyssp);
     }
   YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
   *++yyvsp = yylval;
   YY_IGNORE_MAYBE_UNINITIALIZED_END
   /* Shift the error token.  */
   YY_SYMBOL_PRINT("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
   /*-------------------------------------.
   | yyacceptlab -- YYACCEPT comes here.  |
   `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
   /*-----------------------------------.
   | yyabortlab -- YYABORT comes here.  |
   `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #if !defined yyoverflow || YYERROR_VERBOSE
   /*-------------------------------------------------.
   | yyexhaustedlab -- memory exhaustion comes here.  |
   `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror(YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
   if (yychar != YYEMPTY)
     {
       /* Make sure we have latest lookahead translation.  See comments at
          user semantic actions for why this is necessary.  */
       yytoken = YYTRANSLATE(yychar);
       yydestruct("Cleanup: discarding lookahead",
                  yytoken, &yylval);
     }
   /* Do not reclaim the symbols of the rule which action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK(yylen);
   YY_STACK_PRINT(yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct("Cleanup: popping",
                  yystos[*yyssp], yyvsp);
       YYPOPSTACK(1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE(yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE(yymsg);
 #endif
   /* Make sure YYID is used.  */
   return YYID(yyresult);
 }
Member Data Documentation
bool CEvaluationParserBase::mBoolean protected
Definition at line 103 of file CEvaluationLexer.h.
CEvaluationNode* CEvaluationParserBase::mpNode protected
Definition at line 101 of file CEvaluationLexer.h.
std::vector< CEvaluationNode * >* CEvaluationParserBase::mpNodeList protected
Definition at line 104 of file CEvaluationLexer.h.
size_t CEvaluationParserBase::mPosition protected
Definition at line 105 of file CEvaluationLexer.h.
CEvaluationNode* CEvaluationParserBase::mpRootNode protected
Definition at line 102 of file CEvaluationLexer.h.
The documentation for this class was generated from the following files:
CEvaluationLexer.h
CEvaluationParser_yacc.cpp