COPASI API: CQValidatorNotEmpty Class Reference
CQValidatorNotEmpty Class Reference
#include <CQValidator.h>
Public Member Functions
CQValidatorNotEmpty (QLineEdit *parent, const char *name=0)
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QLineEdit >
CQValidator (QLineEdit *parent, QString(QLineEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QLineEdit >
State setColor (const State &state) const
Protected Attributes inherited from CQValidator< QLineEdit >
QString mLastAccepted
QLineEdit * mpContainer
QString(QLineEdit::* mRetrieve)(void) const
Detailed Description
Definition at line 116 of file CQValidator.h.
Constructor & Destructor Documentation
CQValidatorNotEmpty::CQValidatorNotEmpty (QLineEdit * parent, const char * name = 0)
Definition at line 21 of file CQValidator.cpp.
                                                                              :
   CQValidator< QLineEdit >(parent, &QLineEdit::text, name)
 {}
Member Function Documentation
QValidator::State CQValidatorNotEmpty::validate (QString & input, int & pos) const virtual
Reimplemented from CQValidator< QLineEdit >.
Reimplemented in CQExperimentDataValidator.
Definition at line 25 of file CQValidator.cpp.
References CQValidator< QLineEdit >::setColor(), and CQValidator< Type >::validate().
Referenced by CQFittingItemWidget::loadSelection(), and CQExperimentDataValidator::validate().
 {
   if (input != "")
     return CQValidator< QLineEdit >::validate(input, pos);
   setColor(Invalid);
   return Intermediate;
 }
The documentation for this class was generated from the following files:
CQValidator.h
CQValidator.cpp