COPASI API: CParticleReference Class Reference
CParticleReference Class Reference
#include <CMetab.h>
Public Member Functions
CParticleReference (const std::string &name, const CCopasiContainer *pParent, C_FLOAT64 &reference)
CParticleReference (const CParticleReference &src, const CCopasiContainer *pParent)
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
~CParticleReference ()
Public Member Functions inherited from CCopasiObjectReference< C_FLOAT64 >
CCopasiObjectReference (const std::string &name, const CCopasiContainer *pParent, referenceType &reference, const unsigned C_INT32 &flag=0)
CCopasiObjectReference (const CCopasiObjectReference< referenceType > &src, const CCopasiContainer *pParent)
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
virtual void print (std::ostream *ostream) const
virtual void setReference (referenceType &reference)
virtual ~CCopasiObjectReference ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
CParticleReference ()
Private Attributes
ObjectSet mPrerequisites
Static Private Attributes
static DataObjectSet EmptyDependencies
Additional Inherited Members
Public Types inherited from CCopasiObjectReference< C_FLOAT64 >
typedef C_FLOAT64 referenceType
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 108 of file CMetab.h.
Constructor & Destructor Documentation
CParticleReference::CParticleReference () private
Hidden default constructor
CParticleReference::CParticleReference (const std::string & name, const CCopasiContainer * pParent, C_FLOAT64 & reference)
Specific constructor
Parameters
const std::string & name
const CCopasiContainer * pParent,
C_FLOAT64 & reference,
Definition at line 1144 of file CMetab.cpp.
                                                               :
   CCopasiObjectReference< C_FLOAT64 >(name, pParent, reference),
   mPrerequisites()
 {}
CParticleReference::CParticleReference (const CParticleReference & src, const CCopasiContainer * pParent)
Copy constructor
Parameters
const CParticleReference & src
const CCopasiContainer * pParent,
Definition at line 1151 of file CMetab.cpp.
                                                                          :
   CCopasiObjectReference< C_FLOAT64 >(src, pParent)
 {}
CParticleReference::~CParticleReference ()
Destructor
Definition at line 1156 of file CMetab.cpp.
 {}
Member Function Documentation
const CCopasiObject::DataObjectSet & CParticleReference::getDirectDependencies (const DataObjectSet & context = DataObjectSet()) const virtual
Retrieve the list of direct dependencies
Parameters
const CCopasiObject::DataObjectSet & context (default empty set)
Returns
const CCopasiObject::DataObjectSet & directDependencies
Reimplemented from CCopasiObject.
Definition at line 1161 of file CMetab.cpp.
References CModelEntity::ASSIGNMENT, EmptyDependencies, CMetab::getConcentrationReference(), CCopasiObject::getDirectDependencies(), CMetab::getInitialConcentrationReference(), CModelEntity::getInitialExpression(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), and CModelEntity::getStatus().
 {
   // If the particle number was changed in the context it has no further dependencies
   if (context.count(this) > 0)
     {
       return EmptyDependencies;
     }
   const CMetab * pSpecies = static_cast< const CMetab * >(getObjectParent());
   // In an assignment the particles (initial or transient) have always dependencies
   if (pSpecies == NULL ||
       pSpecies->getStatus() == CModelEntity::ASSIGNMENT)
     {
       return CCopasiObjectReference< C_FLOAT64 >::getDirectDependencies();
     }
   // We need to distinguish between initial and transient value.
   const CCopasiObject * pConcentrationReference = NULL;
   if (getObjectName() == "InitialParticleNumber")
     {
       // If we have an initial expression the initial particle number has dependencies.
       if (pSpecies->getInitialExpression() != "")
         return CCopasiObjectReference< C_FLOAT64 >::getDirectDependencies();
       pConcentrationReference = pSpecies->getInitialConcentrationReference();
     }
   else
     {
       pConcentrationReference = pSpecies->getConcentrationReference();
     }
   // In other cases we need to find out whether the concentration was changed in
   // the context.
   if (pConcentrationReference != NULL &&
       context.count(pConcentrationReference) > 0)
     {
       return CCopasiObjectReference< C_FLOAT64 >::getDirectDependencies();
     }
   return EmptyDependencies;
 }
const CObjectInterface::ObjectSet & CParticleReference::getPrerequisites () const virtual
Retrieve the prerequisites, i.e., the objects which need to be evaluated before this.
Returns
const CObjectInterface::ObjectSet & prerequisites
Reimplemented from CCopasiObject.
Definition at line 1207 of file CMetab.cpp.
References CMoiety::getDependentNumberReference(), CCopasiObject::getDirectDependencies(), CCopasiObject::getObjectParent(), and mPrerequisites.
 {
   mPrerequisites = * reinterpret_cast< const CObjectInterface::ObjectSet * >(&CCopasiObjectReference< C_FLOAT64 >::getDirectDependencies());
   const CMoiety * pMoiety = static_cast< const CMetab * >(getObjectParent())->getMoiety();
   if (pMoiety != NULL)
     {
       mPrerequisites.insert(pMoiety->getDependentNumberReference());
     }
   return mPrerequisites;
 }
bool CParticleReference::isPrerequisiteForContext (const CObjectInterface * pObject, const CMath::SimulationContextFlag & context, const CObjectInterface::ObjectSet & changedObjects) const virtual
Check whether a given object is a prerequisite for a context.
Parameters
const CObjectInterface * pObject
const CMath::SimulationContextFlag & context
const CObjectInterface::ObjectSet & changedObjects
Returns
bool isPrerequisiteForContext
Reimplemented from CCopasiObject.
Definition at line 1221 of file CMetab.cpp.
References CModelEntity::ASSIGNMENT, CMetab::getConcentrationReference(), CMetab::getInitialConcentrationReference(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CModelEntity::getStatus(), CMetab::isDependent(), and CMath::UseMoieties.
 {
   const CMetab * pSpecies = static_cast< const CMetab * >(getObjectParent());
   if ((context & CMath::UseMoieties) &&
       pSpecies->isDependent())
     {
       return true;
     }
   // If the value is changed it must not be recalculated, i.e., it does not depend on the object.
   if (changedObjects.find(this) != changedObjects.end())
     return false;
   // Amounts which are determine by assignment need to be recalculated.
   if (pSpecies->getStatus() == CModelEntity::ASSIGNMENT)
     return true;
   const CConcentrationReference * pConcentrationReference = NULL;
   if (getObjectName() != "ParticleNumber")
     {
       pConcentrationReference = pSpecies->getInitialConcentrationReference();
     }
   else
     {
       pConcentrationReference = pSpecies->getConcentrationReference();
     }
   // If the concentration was changed in the context we need to recalculate.
   if (changedObjects.find(pConcentrationReference) != changedObjects.end())
     return true;
   return false;
 }
Member Data Documentation
CCopasiObject::DataObjectSet CParticleReference::EmptyDependencies static private
The list of direct dependencies when the values is in the changed context, i.e., it is always empty
Definition at line 170 of file CMetab.h.
Referenced by getDirectDependencies().
ObjectSet CParticleReference::mPrerequisites mutable private
The prerequisites for building the math dependency graph.
Definition at line 175 of file CMetab.h.
Referenced by getPrerequisites().
The documentation for this class was generated from the following files:
CMetab.h
CMetab.cpp