COPASI API: CQValidatorXML Class Reference
CQValidatorXML Class Reference
#include <CQNotes.h>
Public Member Functions
CQValidatorXML (QPlainTextEdit *parent, const char *name=0)
const bool & isFreeText () const
const bool & needsWrap () const
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QPlainTextEdit >
CQValidator (QPlainTextEdit *parent, QString(QPlainTextEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Private Attributes
bool mIsFreeText
bool mNeedsWrap
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QPlainTextEdit >
State setColor (const State &state) const
Protected Attributes inherited from CQValidator< QPlainTextEdit >
QString mLastAccepted
QPlainTextEdit * mpContainer
QString(QPlainTextEdit::* mRetrieve)(void) const
Detailed Description
Definition at line 16 of file CQNotes.h.
Constructor & Destructor Documentation
CQValidatorXML::CQValidatorXML (QPlainTextEdit * parent, const char * name = 0)
Definition at line 32 of file CQNotes.cpp.
                                                                         :
   CQValidator< QPlainTextEdit >(parent, &QPlainTextEdit::toPlainText, name),
   mIsFreeText(true),
   mNeedsWrap(false)
 {}
Member Function Documentation
const bool & CQValidatorXML::isFreeText () const
Definition at line 63 of file CQNotes.cpp.
References mIsFreeText.
Referenced by CQNotes::load(), and CQNotes::slotValidateXML().
 {
   return mIsFreeText;
 }
const bool & CQValidatorXML::needsWrap () const
Definition at line 68 of file CQNotes.cpp.
References mNeedsWrap.
Referenced by CQNotes::save().
 {
   return mNeedsWrap;
 }
QValidator::State CQValidatorXML::validate (QString & input, int & pos) const virtual
Reimplemented from CQValidator< QPlainTextEdit >.
Definition at line 39 of file CQNotes.cpp.
References CQNotesContentHandler::isFreeText(), mIsFreeText, mNeedsWrap, CQNotesContentHandler::needsWrap(), CQValidator< QPlainTextEdit >::setColor(), and CQValidator< Type >::validate().
Referenced by CQNotes::slotValidateXML().
 {
   QXmlSimpleReader Validator;
   QXmlInputSource Input;
   CQNotesContentHandler ContentHandler;
   Validator.setContentHandler(&ContentHandler);
   // We like to allow free text and therefore wrap the text to create valid XML.
   Input.setData("<Validate:XML xmlns:Validate=\"http://www.copasi.org/Validate\">" + input + "</Validate:XML>");
   if (Validator.parse(Input))
     {
       mIsFreeText = ContentHandler.isFreeText();
       mNeedsWrap = ContentHandler.needsWrap();
       return CQValidator< QPlainTextEdit >::validate(input, pos);
     }
   mIsFreeText = true;
   mNeedsWrap = false;
   setColor(Invalid);
   return Intermediate;
 }
Member Data Documentation
bool CQValidatorXML::mIsFreeText mutable private
Definition at line 30 of file CQNotes.h.
Referenced by isFreeText(), and validate().
bool CQValidatorXML::mNeedsWrap mutable private
Definition at line 32 of file CQNotes.h.
Referenced by needsWrap(), and validate().
The documentation for this class was generated from the following files:
CQNotes.h
CQNotes.cpp