COPASI API: CQTimeSeriesDM Class Reference
CQTimeSeriesDM Class Reference
#include <CQTimeSeriesDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQTimeSeriesDM (QObject *parent=0)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool isDefaultRow (const QModelIndex &i) const
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setFramework (int framework)
void setTimeSeries (const CTimeSeries *pTimeSeries)
virtual ~CQTimeSeriesDM ()
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
bool removeRow (int position)
Protected Member Functions
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Private Attributes
int mFramework
const CTimeSeries * mpTimeSeries
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 21 of file CQTimeSeriesDM.h.
Constructor & Destructor Documentation
CQTimeSeriesDM::CQTimeSeriesDM (QObject * parent = 0)
Definition at line 19 of file CQTimeSeriesDM.cpp.
                                              :
     CQBaseDataModel(parent),
     mpTimeSeries(NULL),
     mFramework(0)
 {}
CQTimeSeriesDM::~CQTimeSeriesDM () virtual
Definition at line 25 of file CQTimeSeriesDM.cpp.
 {}
Member Function Documentation
int CQTimeSeriesDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 37 of file CQTimeSeriesDM.cpp.
References CTimeSeries::getNumVariables(), and mpTimeSeries.
Referenced by data(), headerData(), and setFramework().
 {
   if (mpTimeSeries == NULL) return 0;
   return (int) mpTimeSeries->getNumVariables();
 }
QVariant CQTimeSeriesDM::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 51 of file CQTimeSeriesDM.cpp.
References columnCount(), CTimeSeries::getConcentrationData(), CTimeSeries::getData(), mFramework, mpTimeSeries, and rowCount().
 {
   if (mpTimeSeries == NULL || role != Qt::DisplayRole) return QVariant();
   if (!index.isValid() ||
       index.row() < 0 || rowCount() <= index.row() ||
       index.column() < 0 || columnCount() <= index.column())  return QVariant();
   switch (mFramework)
     {
       case 0:
         return QString::number(mpTimeSeries->getConcentrationData(index.row(), index.column()));
       case 1:
         return QString::number(mpTimeSeries->getData(index.row(), index.column()));
     }
   return QVariant();
 }
Qt::ItemFlags CQTimeSeriesDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 45 of file CQTimeSeriesDM.cpp.
 {
   return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
 }
QVariant CQTimeSeriesDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 72 of file CQTimeSeriesDM.cpp.
References columnCount(), FROM_UTF8, CTimeSeries::getTitle(), mpTimeSeries, and rowCount().
 {
   if (mpTimeSeries == NULL || role != Qt::DisplayRole) return QVariant();
   switch (orientation)
     {
       case Qt::Horizontal:
         if (section < 0 || columnCount() <= section) return QVariant();
         return QString(FROM_UTF8(mpTimeSeries->getTitle(section)));
       case Qt::Vertical:
         if (section < 0 || rowCount() <= section) return QVariant();
         return QString("%1").arg(section + 1);
     }
   return QVariant();
 }
bool CQTimeSeriesDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 115 of file CQTimeSeriesDM.cpp.
 {
   return false;
 }
bool CQTimeSeriesDM::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 127 of file CQTimeSeriesDM.cpp.
 {
   return false;
 }
bool CQTimeSeriesDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 121 of file CQTimeSeriesDM.cpp.
 {
   return false;
 }
int CQTimeSeriesDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 29 of file CQTimeSeriesDM.cpp.
References CTimeSeries::getRecordedSteps(), and mpTimeSeries.
Referenced by data(), headerData(), CQTimeSeriesWidget::loadResult(), and setFramework().
 {
   if (mpTimeSeries == NULL) return 0;
   return (int) mpTimeSeries->getRecordedSteps();
 }
bool CQTimeSeriesDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 109 of file CQTimeSeriesDM.cpp.
 {
   return false;
 }
void CQTimeSeriesDM::setFramework (int framework)
Definition at line 101 of file CQTimeSeriesDM.cpp.
References columnCount(), mFramework, and rowCount().
Referenced by CQTimeSeriesWidget::setFramework().
 {
   if (mFramework == framework) return;
   mFramework = framework;
   emit dataChanged(index(0, 0), index(rowCount(), columnCount()));
 }
void CQTimeSeriesDM::setTimeSeries (const CTimeSeries * pTimeSeries)
Definition at line 95 of file CQTimeSeriesDM.cpp.
References mpTimeSeries.
Referenced by CQTimeSeriesWidget::loadResult().
 {
   mpTimeSeries = pTimeSeries;
   reset();
 }
Member Data Documentation
int CQTimeSeriesDM::mFramework private
Definition at line 53 of file CQTimeSeriesDM.h.
Referenced by data(), and setFramework().
const CTimeSeries* CQTimeSeriesDM::mpTimeSeries private
Definition at line 52 of file CQTimeSeriesDM.h.
Referenced by columnCount(), data(), headerData(), rowCount(), and setTimeSeries().
The documentation for this class was generated from the following files:
CQTimeSeriesDM.h
CQTimeSeriesDM.cpp