COPASI API: CLStyle Class Reference
CLStyle Class Reference
#include <CLStyle.h>
Public Member Functions
void addRole (const std::string &role)
void addSBMLAttributes (Style *pStyle) const
void addType (const std::string &type)
CLStyle (const std::string &name, CCopasiContainer *pParent=NULL)
CLStyle (const CLStyle &source, CCopasiContainer *pParent=NULL)
CLStyle (const Style &source, const std::string &name, CCopasiContainer *pParent=NULL)
const CLGroup * getGroup () const
CLGroup * getGroup ()
const std::string & getKey () const
size_t getNumRoles () const
size_t getNumTypes () const
const std::set< std::string > & getRoleList () const
const std::set< std::string > & getTypeList () const
bool isInRoleList (const std::string &role) const
bool isInTypeList (const std::string &type) const
void removeRole (const std::string &role)
void removeType (const std::string &type)
void setGroup (const CLGroup *pGroup)
void setRoleList (const std::set< std::string > &roleList)
void setTypeList (const std::set< std::string > &typeList)
~CLStyle ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static std::string createStringFromSet (const std::set< std::string > &set)
static void readIntoSet (const std::string &s, std::set< std::string > &set)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Attributes
std::string mKey
CLGroup * mpGroup
std::set< std::string > mRoleList
std::set< std::string > mTypeList
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CLStyle & operator= (const CLStyle &source)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 27 of file CLStyle.h.
Constructor & Destructor Documentation
CLStyle::CLStyle (const std::string & name, CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 26 of file CLStyle.cpp.
                                                                 :
     CLBase(),
     CCopasiContainer(name, pParent),
     mpGroup(NULL),
     mKey("")
 {
 }
CLStyle::CLStyle (const CLStyle & source, CCopasiContainer * pParent = NULL)
Copy Constructor.
Definition at line 37 of file CLStyle.cpp.
References mpGroup.
                                                                 :
     CLBase(source),
     CCopasiContainer(source, pParent),
     mRoleList(source.mRoleList),
     mTypeList(source.mTypeList),
     mpGroup(NULL),
     mKey("")
 {
   if (source.mpGroup != NULL)
     {
       this->mpGroup = new CLGroup(*source.mpGroup, this);
     }
 }
CLStyle::CLStyle (const Style & source, const std::string & name, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 54 of file CLStyle.cpp.
References createStringFromSet(), mRoleList, mTypeList, and readIntoSet().
                                                                                      :
     CLBase(),
     CCopasiContainer(name, pParent),
     mpGroup(new CLGroup(*source.getGroup(), this)),
     mKey("")
 {
   CLStyle::readIntoSet(CLStyle::createStringFromSet(source.getRoleList()), this->mRoleList);
   CLStyle::readIntoSet(CLStyle::createStringFromSet(source.getTypeList()), this->mTypeList);
 }
CLStyle::~CLStyle ()
Destructor
Definition at line 67 of file CLStyle.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(this->mKey);
 }
Member Function Documentation
void CLStyle::addRole (const std::string & role)
Adds an role to the role list.
Definition at line 115 of file CLStyle.cpp.
References mRoleList.
 {
   this->mRoleList.insert(role);
 }
void CLStyle::addSBMLAttributes (Style * pStyle) const
Adds the attributes for a style object to the passed in. object.
Definition at line 237 of file CLStyle.cpp.
References createStringFromSet(), mpGroup, mRoleList, mTypeList, readIntoSet(), and CLGroup::toSBML().
Referenced by CLGlobalStyle::toSBML(), and CLLocalStyle::toSBML().
 {
   RenderGroup* pG = this->mpGroup->toSBML(pStyle->getLevel(), pStyle->getVersion());
   pStyle->setGroup(pG);
   delete pG;
   std::set<std::string> s;
   CLStyle::readIntoSet(CLStyle::createStringFromSet(this->mRoleList), s);
   pStyle->setRoleList(s);
   s.clear();
   CLStyle::readIntoSet(CLStyle::createStringFromSet(this->mTypeList), s);
   pStyle->setTypeList(s);
 }
void CLStyle::addType (const std::string & type)
Adds a type to the type list.
Adds an type to the type list.
Definition at line 147 of file CLStyle.cpp.
References mTypeList.
 {
   this->mTypeList.insert(type);
 }
std::string CLStyle::createStringFromSet (const std::set< std::string > & set) static
Definition at line 182 of file CLStyle.cpp.
Referenced by addSBMLAttributes(), CLLocalStyle::CLLocalStyle(), CLStyle(), CCopasiXML::saveLocalStyle(), CCopasiXML::saveStyleAttributes(), and CLLocalStyle::toSBML().
 {
   std::ostringstream os;
   std::set<std::string>::const_iterator it = set.begin(), endit = set.end();
   while (it != endit)
     {
       os << *it << " ";
       ++it;
     }
   if (!os.str().empty())
     {
       os.str(os.str().substr(0, os.str().size() - 1));
     }
   return os.str();
 }
const CLGroup * CLStyle::getGroup () const
Returns the group.
Definition at line 91 of file CLStyle.cpp.
References mpGroup.
Referenced by CLRenderFlattener::convertGlobalToLocalStyle(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CQLabelGraphicsItem::CQLabelGraphicsItem(), CLLayoutRenderer::draw_object(), CLLayoutRenderer::draw_text(), CLLayoutRenderer::extract_group_attributes(), CQRenderConverter::fillGroupFromStyle(), CCopasiXML::saveStyleElements(), and CCopasiXMLParser::GroupElement::start().
 {
   return this->mpGroup;
 }
CLGroup * CLStyle::getGroup ()
Returns the group.
Definition at line 99 of file CLStyle.cpp.
References mpGroup.
 {
   return this->mpGroup;
 }
const std::string & CLStyle::getKey () const virtual
Returns the key of the style
Reimplemented from CCopasiObject.
Definition at line 228 of file CLStyle.cpp.
References mKey.
Referenced by CCopasiXML::saveStyleAttributes().
 {
   return this->mKey;
 }
size_t CLStyle::getNumRoles () const
Returns the number of roles in the role list.
Returns the number roles ids in the role list.
Definition at line 107 of file CLStyle.cpp.
References mRoleList.
Referenced by CCopasiXML::saveStyleAttributes().
 {
   return this->mRoleList.size();
 }
size_t CLStyle::getNumTypes () const
Returns the number of types in the type list.
Definition at line 139 of file CLStyle.cpp.
References mTypeList.
Referenced by CCopasiXML::saveStyleAttributes().
 {
   return this->mTypeList.size();
 }
const std::set< std::string > & CLStyle::getRoleList () const
Returns the role list.
Definition at line 201 of file CLStyle.cpp.
References mRoleList.
Referenced by CLRenderFlattener::convertGlobalToLocalStyle(), CLRenderResolver::fill_global_maps(), CLRenderResolver::fill_local_maps(), CLRenderFlattener::flatten(), and CCopasiXML::saveStyleAttributes().
 {
   return this->mRoleList;
 }
const std::set< std::string > & CLStyle::getTypeList () const
Returns the type list.
Definition at line 206 of file CLStyle.cpp.
References mTypeList.
Referenced by CLRenderFlattener::convertGlobalToLocalStyle(), CLRenderResolver::fill_global_maps(), CLRenderResolver::fill_local_maps(), CLRenderFlattener::flatten(), and CCopasiXML::saveStyleAttributes().
 {
   return this->mTypeList;
 }
bool CLStyle::isInRoleList (const std::string & role) const
Checks whether a given role is in the role list.
Definition at line 123 of file CLStyle.cpp.
References mRoleList.
 {
   return (this->mRoleList.find(role) != this->mRoleList.end());
 }
bool CLStyle::isInTypeList (const std::string & type) const
Checks whether a given type is in the type list.
Definition at line 155 of file CLStyle.cpp.
References mTypeList.
 {
   return (this->mTypeList.find(type) != this->mTypeList.end());
 }
CLStyle& CLStyle::operator= (const CLStyle & source) private
void CLStyle::readIntoSet (const std::string & s, std::set< std::string > & set) static
Definition at line 168 of file CLStyle.cpp.
Referenced by addSBMLAttributes(), CLLocalStyle::CLLocalStyle(), CLStyle(), CCopasiXMLParser::LocalStyleElement::start(), CCopasiXMLParser::GlobalStyleElement::start(), and CLLocalStyle::toSBML().
 {
   std::string delimiter = "\n\r\t ";
   std::size_t lastPos = s.find_first_not_of(delimiter);
   std::size_t pos;
   while (lastPos != std::string::npos)
     {
       pos = s.find_first_of(delimiter, lastPos);
       set.insert(s.substr(lastPos, pos - lastPos));
       lastPos = s.find_first_not_of(delimiter, pos);
     }
 }
void CLStyle::removeRole (const std::string & role)
Removes a role from the role list.
Removes an role from the role list.
Definition at line 131 of file CLStyle.cpp.
References mRoleList.
 {
   this->mRoleList.erase(role);
 }
void CLStyle::removeType (const std::string & type)
Removes an type from the type list.
Definition at line 163 of file CLStyle.cpp.
References mTypeList.
 {
   this->mTypeList.erase(type);
 }
void CLStyle::setGroup (const CLGroup * pGroup)
Sets the group.
Definition at line 75 of file CLStyle.cpp.
References mpGroup.
Referenced by CLRenderFlattener::convertGlobalToLocalStyle(), and CCopasiXMLParser::GroupElement::start().
 {
   if (pGroup)
     {
       if (this->mpGroup != NULL)
         {
           delete this->mpGroup;
         }
       this->mpGroup = new CLGroup(*pGroup, this);
     }
 }
void CLStyle::setRoleList (const std::set< std::string > & roleList)
Sets the role list.
Definition at line 211 of file CLStyle.cpp.
References mRoleList.
Referenced by CLRenderFlattener::convertGlobalToLocalStyle(), CCopasiXMLParser::LocalStyleElement::start(), and CCopasiXMLParser::GlobalStyleElement::start().
 {
   // I do not check roles on purpose since this is more versatil in the light
   // of future extensions
   this->mRoleList = roleList;
 }
void CLStyle::setTypeList (const std::set< std::string > & typeList)
Sets the type list.
Definition at line 218 of file CLStyle.cpp.
References mTypeList.
Referenced by CLRenderFlattener::convertGlobalToLocalStyle(), CCopasiXMLParser::LocalStyleElement::start(), and CCopasiXMLParser::GlobalStyleElement::start().
 {
   // I do not check types on purpose since this is more versatil in the light
   // of future extensions
   this->mTypeList = typeList;
 }
Member Data Documentation
std::string CLStyle::mKey protected
key string for the style.
Definition at line 41 of file CLStyle.h.
Referenced by CLGlobalStyle::CLGlobalStyle(), CLLocalStyle::CLLocalStyle(), getKey(), and ~CLStyle().
CLGroup* CLStyle::mpGroup protected
Definition at line 36 of file CLStyle.h.
Referenced by addSBMLAttributes(), CLStyle(), getGroup(), and setGroup().
std::set<std::string> CLStyle::mRoleList protected
Definition at line 34 of file CLStyle.h.
Referenced by addRole(), addSBMLAttributes(), CLStyle(), getNumRoles(), getRoleList(), isInRoleList(), removeRole(), and setRoleList().
std::set<std::string> CLStyle::mTypeList protected
Definition at line 35 of file CLStyle.h.
Referenced by addSBMLAttributes(), addType(), CLStyle(), getNumTypes(), getTypeList(), isInTypeList(), removeType(), and setTypeList().
The documentation for this class was generated from the following files:
CLStyle.h
CLStyle.cpp