COPASI API: test000088 Class Reference
test000088 Class Reference
#include <test000088.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_import_assignment_without_expression ()
void test_import_eventassignment_without_expression ()
void test_import_initialassignment_without_expression ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_assignment_without_expression)
CPPUNIT_TEST (test_import_initialassignment_without_expression)
CPPUNIT_TEST (test_import_eventassignment_without_expression)
CPPUNIT_TEST_SUITE (test000088)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000088.h.
Member Function Documentation
test000088::CPPUNIT_TEST (test_import_assignment_without_expression) private
test000088::CPPUNIT_TEST (test_import_initialassignment_without_expression) private
test000088::CPPUNIT_TEST (test_import_eventassignment_without_expression) private
test000088::CPPUNIT_TEST_SUITE (test000088) private
test000088::CPPUNIT_TEST_SUITE_END () private
void test000088::setUp ()
Definition at line 28 of file test000088.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000088::tearDown ()
Definition at line 36 of file test000088.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000088::test_import_assignment_without_expression ()
Definition at line 41 of file test000088.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CModel::getModelValues(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING1, pCOPASIDATAMODEL, CCopasiMessage::size(), and CCopasiVector< T >::size().
 {
   CPPUNIT_ASSERT(pCOPASIDATAMODEL->importSBMLFromString(test000088::MODEL_STRING1));
   // check if we have the correct warning message on the stack
   // there should be a warning (MCSBML + 58)
   unsigned int i, iMax = CCopasiMessage::size();
   CCopasiMessage message;
   bool found58 = false;
   for (i = 0; i < iMax; ++i)
     {
       message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 58)
         {
           found58 = true;
           break;
         }
     }
   CPPUNIT_ASSERT(found58 == true);
   // check if the model contains one parameter and that this parameter does not
   // have an expression
   const CModel* pModel = pCOPASIDATAMODEL->getModel();
   CPPUNIT_ASSERT(pModel !=  NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pMV = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pMV != NULL);
   CPPUNIT_ASSERT(pMV->getExpression().empty());
 }
void test000088::test_import_eventassignment_without_expression ()
Definition at line 106 of file test000088.cpp.
References CModel::getEvents(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CModel::getModelValues(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING3, pCOPASIDATAMODEL, CCopasiMessage::size(), and CCopasiVector< T >::size().
 {
   CPPUNIT_ASSERT(pCOPASIDATAMODEL->importSBMLFromString(test000088::MODEL_STRING3));
   // check if we have the correct warning message on the stack
   // there should be a warning (MCSBML + 58)
   unsigned int i, iMax = CCopasiMessage::size();
   CCopasiMessage message;
   bool found58 = false;
   for (i = 0; i < iMax; ++i)
     {
       message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 58)
         {
           found58 = true;
           break;
         }
     }
   CPPUNIT_ASSERT(found58 == true);
   // check if the model contains one parameter and that this parameter does not
   // have an expression
   const CModel* pModel = pCOPASIDATAMODEL->getModel();
   CPPUNIT_ASSERT(pModel !=  NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pMV = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pMV != NULL);
   // since the parameter does not set an initial value, it's value should be 1
   CPPUNIT_ASSERT(fabs(pMV->getInitialValue() - 1.0) < 1e-6);
   // check if there is one event and that this event does not have an event
   // assignment
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 0);
 }
void test000088::test_import_initialassignment_without_expression ()
Definition at line 72 of file test000088.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CModel::getModelValues(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING2, pCOPASIDATAMODEL, CCopasiMessage::size(), and CCopasiVector< T >::size().
 {
   bool result = pCOPASIDATAMODEL->importSBMLFromString(test000088::MODEL_STRING2);
   CPPUNIT_ASSERT(result == true);
   // check if we have the correct warning message on the stack
   // there should be a warning (MCSBML + 58)
   unsigned int i, iMax = CCopasiMessage::size();
   CCopasiMessage message;
   bool found58 = false;
   for (i = 0; i < iMax; ++i)
     {
       message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 58)
         {
           found58 = true;
           break;
         }
     }
   CPPUNIT_ASSERT(found58 == true);
   // check if the model contains one parameter and that this parameter does not
   // have an expression
   const CModel* pModel = pCOPASIDATAMODEL->getModel();
   CPPUNIT_ASSERT(pModel !=  NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pMV = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pMV != NULL);
   CPPUNIT_ASSERT(pMV->getInitialExpression().empty());
   // since the parameter does not set an initial value, it's value should be 1.0
   CPPUNIT_ASSERT(fabs(pMV->getInitialValue() - 1.0) < 1e-6);
 }
Member Data Documentation
const char * test000088::MODEL_STRING1 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">\n"
  "  <model id=\"model_1\" name=\"model\">\n"
  "    <listOfParameters>\n"
  "      <parameter constant=\"false\" id=\"parameter_1\"/>\n"
  "    </listOfParameters>\n"
  "    <listOfRules>\n"
  "      <assignmentRule variable=\"parameter_1\" />\n"
  "    </listOfRules>\n"
  "  </model>\n"
  "</sbml>\n"
Definition at line 36 of file test000088.h.
Referenced by test_import_assignment_without_expression().
const char * test000088::MODEL_STRING2 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2/version4\" level=\"2\" version=\"4\">\n"
  "  <model id=\"model_1\" name=\"model\">\n"
  "    <listOfParameters>\n"
  "      <parameter constant=\"false\" id=\"parameter_1\"/>\n"
  "    </listOfParameters>\n"
  "    <listOfInitialAssignments>\n"
  "      <initialAssignment symbol=\"parameter_1\" />\n"
  "    </listOfInitialAssignments>\n"
  "  </model>\n"
  "</sbml>\n"
Definition at line 37 of file test000088.h.
Referenced by test_import_initialassignment_without_expression().
const char * test000088::MODEL_STRING3 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">\n"
  "  <model id=\"model_1\" name=\"model\">\n"
  "    <listOfParameters>\n"
  "      <parameter constant=\"false\" id=\"parameter_1\"/>\n"
  "    </listOfParameters>\n"
  "    <listOfEvents>\n"
  "      <event>\n"
  "        <trigger>\n"
  "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
  "            <apply>\n"
  "              <geq/>\n"
  "              <ci> parameter_1 </ci>\n"
  "              <cn> 3.0 </cn>\n"
  "            </apply>\n"
  "          </math>\n"
  "        </trigger>\n"
  "        <listOfEventAssignments>\n"
  "          <eventAssignment variable=\"parameter_1\" />\n"
  "        </listOfEventAssignments>\n"
  "      </event>\n"
  "    </listOfEvents>\n"
  "  </model>\n"
  "</sbml>\n"
Definition at line 38 of file test000088.h.
Referenced by test_import_eventassignment_without_expression().
CCopasiDataModel * test000088::pCOPASIDATAMODEL = NULL static protected
Definition at line 35 of file test000088.h.
Referenced by setUp(), test_import_assignment_without_expression(), test_import_eventassignment_without_expression(), and test_import_initialassignment_without_expression().
The documentation for this class was generated from the following files:
test000088.h
test000088.cpp