COPASI API: CCopasiXML Class Reference
CCopasiXML Class Reference
#include <CCopasiXML.h>
Public Member Functions
CCopasiXML ()
bool freeFunctionList ()
bool freeGUI ()
bool freeLayoutList ()
bool freeModel ()
bool freePlotList ()
bool freeReportList ()
bool freeTaskList ()
CCopasiVectorN< CFunction > * getFunctionList () const
SCopasiXMLGUI * getGUI () const
CListOfLayouts * getLayoutList () const
CModel * getModel () const
COutputDefinitionVector * getPlotList () const
CReportDefinitionVector * getReportList () const
CCopasiVectorN< CCopasiTask > * getTaskList () const
bool haveFunctionList () const
bool haveGUI () const
bool haveLayoutList () const
bool haveModel () const
bool havePlotList () const
bool haveReportList () const
bool haveTaskList () const
virtual bool load (std::istream &is, const std::string &pwd)
virtual bool save (std::ostream &os, const std::string &relativeTo)
bool setDatamodel (CCopasiDataModel *pDataModel)
bool setFunctionList (CCopasiVectorN< CFunction > *pFunctionList)
bool setGUI (SCopasiXMLGUI *pGUI)
bool setLayoutList (const CListOfLayouts &reportList)
bool setModel (CModel *pModel)
bool setPlotList (COutputDefinitionVector *pPlotList)
bool setReportList (CReportDefinitionVector *pReportList)
bool setTaskList (CCopasiVectorN< CCopasiTask > *pTaskList)
~CCopasiXML ()
Public Member Functions inherited from CCopasiXMLInterface
CCopasiXMLInterface ()
bool load (const std::string &fileName, const std::string &relativeTo)
bool save (const std::string &fileName, const std::string &relativeTo)
virtual ~CCopasiXMLInterface ()
Private Member Functions
bool buildFunctionList ()
void fixBuild55 ()
void fixBuild81 ()
void save1DAttributes (const CLGraphicalPrimitive1D &primitive, CXMLAttributeList &attributes)
void save2DAttributes (const CLGraphicalPrimitive2D &primitive, CXMLAttributeList &attributes)
bool saveAnnotation (const CAnnotation *pAnnotation)
template<typename HEADELEMENT >
void saveArrowHeadAttributes (const HEADELEMENT &element, CXMLAttributeList &attributes)
void saveBoundingBox (const CLBoundingBox &bb)
void saveColorDefinition (const CLColorDefinition &color)
void saveCurve (const CLCurve &c)
void saveCurveElements (const std::vector< CLRenderPoint * > &curveElements)
void saveDimensions (const CLDimensions &d)
void saveEllipseElement (const CLEllipse &ellipse)
bool saveFunctionList ()
void saveGlobalRenderInformation (const CLGlobalRenderInformation &renderInfo)
void saveGlobalStyle (const CLGlobalStyle &style)
void saveGradientAttributes (const CLGradientBase &gradient, CXMLAttributeList &attributes)
void saveGradientElements (const CLGradientBase &gradient)
void saveGradientStop (const CLGradientStop &stop)
void saveGroupElement (const CLGroup &group)
bool saveGUI ()
void saveImageElement (const CLImage &image)
bool saveLayoutList ()
void saveLinearGradient (const CLLinearGradient &gradient)
void saveLineEnding (const CLLineEnding &lineEnding)
void saveListOfGlobalRenderInformation (const CCopasiVector< CLGlobalRenderInformation > &list)
void saveListOfLocalRenderInformation (const CCopasiVector< CLLocalRenderInformation > &list)
void saveLocalRenderInformation (const CLLocalRenderInformation &renderInfo)
void saveLocalStyle (const CLLocalStyle &style)
bool saveModel ()
bool saveModelParameter (const CModelParameter *pModelParameter)
bool savePlotList ()
void savePolygonElement (const CLPolygon &polygon)
void savePosition (const CLPoint &p, const std::string &tag="Position")
void saveRadialGradient (const CLRadialGradient &gradient)
void saveRectangleElement (const CLRectangle &rectangle)
void saveRenderCurveElement (const CLRenderCurve &curve)
void saveRenderInformationAttributes (const CLRenderInformationBase &renderInfo, CXMLAttributeList &attributes)
void saveRenderInformationDefinitionElements (const CLRenderInformationBase &renderInfo)
void saveRenderPoint (const CLRenderPoint &point)
void saveRenderTextElement (const CLText &text)
bool saveReportList ()
bool saveReportSection (const std::string &name, const std::vector< CRegisteredObjectName > &section)
bool saveSBMLReference ()
void saveStyleAttributes (const CLStyle &style, CXMLAttributeList &attributes)
void saveStyleElements (const CLStyle &style)
bool saveTaskList ()
template<typename TEXTELEMENT >
void saveTextAttributes (const TEXTELEMENT &text, CXMLAttributeList &attributes)
void saveTransformation2D (const CLTransformation2D &transformation)
void saveTransformationAttributes (const CLTransformation2D &transformation, CXMLAttributeList &attributes)
Private Attributes
bool mMCXML21Issued
CCopasiDataModel * mpDataModel
CCopasiVectorN< CFunction > * mpFunctionList
SCopasiXMLGUI * mpGUI
CListOfLayouts * mpLayoutList
CModel * mpModel
COutputDefinitionVector * mpPlotList
CReportDefinitionVector * mpReportList
CCopasiVectorN< CCopasiTask > * mpTaskList
std::map< std::string,
std::string > mSBMLReference
Additional Inherited Members
Public Types inherited from CCopasiXMLInterface
enum EncodingType { none = 0, standard, attribute, character }
Static Public Member Functions inherited from CCopasiXMLInterface
static std::string encode (const std::string &str, const EncodingType &type=standard)
static std::string utf8 (const std::string &str)
Protected Member Functions inherited from CCopasiXMLInterface
bool endSaveElement (const std::string &name)
bool saveData (const std::string &data)
bool saveElement (const std::string &name, CXMLAttributeList &attributeList)
bool saveParameter (const CCopasiParameter &parameter)
bool saveParameterGroup (const std::vector< CCopasiParameter * > &group)
bool saveXhtml (const std::string &xhtml)
bool startSaveElement (const std::string &name)
bool startSaveElement (const std::string &name, CXMLAttributeList &attributeList)
Protected Attributes inherited from CCopasiXMLInterface
std::string mIndent
std::istream * mpIstream
std::ostream * mpOstream
std::string mPWD
Detailed Description
Definition at line 75 of file CCopasiXML.h.
Constructor & Destructor Documentation
CCopasiXML::CCopasiXML ()
Constructor
CCopasiXML class. This class implements a CCopasiXMLInterface to the COPASI XML specified in http://www.copasi.org/schema/copasi.xsd
Created for COPASI by Stefan Hoops 2003 Copyright Stefan Hoops
Definition at line 87 of file CCopasiXML.cpp.
                       :
   CCopasiXMLInterface(),
   mpModel(NULL),
   mpFunctionList(NULL),
   mpTaskList(NULL),
   mpReportList(NULL),
   mpPlotList(NULL),
   mpGUI(NULL),
   mpLayoutList(NULL),
   mpDataModel(NULL),
   mMCXML21Issued(false)
 {}
CCopasiXML::~CCopasiXML ()
Destructor
Definition at line 100 of file CCopasiXML.cpp.
 {}
Member Function Documentation
bool CCopasiXML::buildFunctionList () private
Build a list of functions.
Returns
bool success
Definition at line 1872 of file CCopasiXML.cpp.
References CCopasiRootContainer::getFunctionList(), CCopasiDataModel::getModel(), CFunctionDB::getUsedFunctions(), mpDataModel, and setFunctionList().
Referenced by save().
 {
   bool success = true;
   CCopasiVectorN< CFunction > * pFunctionList
   = new CCopasiVectorN< CFunction >;
   *pFunctionList = CCopasiRootContainer::getFunctionList()->getUsedFunctions(this->mpDataModel->getModel());
   if (!setFunctionList(pFunctionList)) success = false;
   return success;
 }
void CCopasiXML::fixBuild55 () private
Fix files written with Version 4.10.55, which wrote the square root of user defined weights for the parameter fitting task
Definition at line 1886 of file CCopasiXML.cpp.
References C_INVALID_INDEX, CFitTask::fixBuild55(), CCopasiVectorN< CType >::getIndex(), mpTaskList, and pTask.
Referenced by load().
 {
   if (mpTaskList == NULL) return;
   size_t Index = mpTaskList->getIndex("Parameter Estimation");
   if (Index == C_INVALID_INDEX) return;
   CFitTask * pTask = dynamic_cast< CFitTask * >((*mpTaskList)[Index]);
   if (pTask == NULL) return;
   pTask->fixBuild55();
   return;
 }
void CCopasiXML::fixBuild81 () private
Fix files written with Version 4.12.81 and earlier, which wrote the exp(mean) and exp(std. deviation) for normal random distributions in the scan task.
Definition at line 1903 of file CCopasiXML.cpp.
References C_INVALID_INDEX, CScanTask::fixBuild81(), CCopasiVectorN< CType >::getIndex(), mpTaskList, and pTask.
Referenced by load().
 {
   if (mpTaskList == NULL) return;
   size_t Index = mpTaskList->getIndex("Scan");
   if (Index == C_INVALID_INDEX) return;
   CScanTask * pTask = dynamic_cast< CScanTask * >((*mpTaskList)[Index]);
   if (pTask == NULL) return;
   pTask->fixBuild81();
   return;
 }
bool CCopasiXML::freeFunctionList ()
Free the function list.
Returns
bool success
Definition at line 282 of file CCopasiXML.cpp.
References mpFunctionList, and pdelete.
Referenced by save().
 {
   pdelete(mpFunctionList);
   return true;
 }
bool CCopasiXML::freeGUI ()
Free the GUI.
Returns
bool success
Definition at line 369 of file CCopasiXML.cpp.
References mpGUI, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   pdelete(mpGUI);
   return true;
 }
bool CCopasiXML::freeLayoutList ()
Free the layout list.
Returns
bool success
Definition at line 389 of file CCopasiXML.cpp.
References mpLayoutList, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   pdelete(mpLayoutList);
   return true;
 }
bool CCopasiXML::freeModel ()
Free the model.
Returns
bool success
Definition at line 264 of file CCopasiXML.cpp.
References mpModel, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   pdelete(mpModel);
   return true;
 }
bool CCopasiXML::freePlotList ()
Free the plot list.
Returns
bool success
Definition at line 331 of file CCopasiXML.cpp.
References mpPlotList, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   pdelete(mpPlotList);
   return true;
 }
bool CCopasiXML::freeReportList ()
Free the report list.
Returns
bool success
Definition at line 351 of file CCopasiXML.cpp.
References mpReportList, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   pdelete(mpReportList);
   return true;
 }
bool CCopasiXML::freeTaskList ()
Free the task list.
Returns
bool success
Definition at line 311 of file CCopasiXML.cpp.
References mpTaskList, and pdelete.
Referenced by CCopasiDataModel::loadModel().
 {
   pdelete(mpTaskList);
   return true;
 }
CCopasiVectorN< CFunction > * CCopasiXML::getFunctionList () const
Retrieve the function list.
Returns
CCopasiVectorN< CFunction > * pFunctionList
Definition at line 276 of file CCopasiXML.cpp.
References mpFunctionList.
 {return mpFunctionList;}
SCopasiXMLGUI * CCopasiXML::getGUI () const
Retrieve the SCopasiXMLGUI.
Returns
SCopasiXMLGUI * pGUI
Definition at line 365 of file CCopasiXML.cpp.
References mpGUI.
 {return mpGUI;}
CListOfLayouts * CCopasiXML::getLayoutList () const
Retrieve the layout list.
Returns
CListOfLayouts * layoutList
Definition at line 383 of file CCopasiXML.cpp.
References mpLayoutList.
Referenced by CCopasiDataModel::loadModel().
 {return mpLayoutList;}
CModel * CCopasiXML::getModel () const
Retreive the model.
Returns
CModel * pModel
Definition at line 260 of file CCopasiXML.cpp.
References mpModel.
Referenced by CCopasiDataModel::loadModel().
 {return mpModel;}
COutputDefinitionVector * CCopasiXML::getPlotList () const
Retrieve the plot list.
Returns
COutputDefinitionVector * plotList
Definition at line 325 of file CCopasiXML.cpp.
References mpPlotList.
Referenced by CCopasiDataModel::loadModel().
 {return mpPlotList;}
CReportDefinitionVector * CCopasiXML::getReportList () const
Retrieve the report list.
Returns
CReportDefinitionVector * reportList
Definition at line 345 of file CCopasiXML.cpp.
References mpReportList.
Referenced by CCopasiDataModel::loadModel().
 {return mpReportList;}
CCopasiVectorN< CCopasiTask > * CCopasiXML::getTaskList () const
Retrieve the task list.
Returns
CCopasiVectorN< CCopasiTask > * taskList
Definition at line 305 of file CCopasiXML.cpp.
References mpTaskList.
Referenced by CCopasiDataModel::loadModel().
 {return mpTaskList;}
bool CCopasiXML::haveFunctionList () const
Retrieve whether the XML contains a function list.
Returns
bool haveFunctionList
Definition at line 279 of file CCopasiXML.cpp.
References mpFunctionList.
Referenced by save(), and saveFunctionList().
 {return mpFunctionList != NULL;}
bool CCopasiXML::haveGUI () const
Retrieve whether the XML contains a GUI.
Returns
bool have GUI
Definition at line 367 of file CCopasiXML.cpp.
References mpGUI.
Referenced by saveGUI().
 {return mpGUI != NULL;}
bool CCopasiXML::haveLayoutList () const
Retrieve whether the XML contains a layout list.
Returns
bool haveLayoutList
Definition at line 386 of file CCopasiXML.cpp.
References mpLayoutList.
Referenced by saveLayoutList().
 {return mpLayoutList != NULL;}
bool CCopasiXML::haveModel () const
Retreive whether the XML contains a model.
Returns
bool have Model
Definition at line 262 of file CCopasiXML.cpp.
References mpModel.
Referenced by save(), and saveModel().
 {return mpModel != NULL;}
bool CCopasiXML::havePlotList () const
Retrieve whether the XML contains a plot list.
Returns
bool havePlotList
Definition at line 328 of file CCopasiXML.cpp.
References mpPlotList.
Referenced by savePlotList().
 {return mpPlotList != NULL;}
bool CCopasiXML::haveReportList () const
Retrieve whether the XML contains a report list.
Returns
bool haveReportList
Definition at line 348 of file CCopasiXML.cpp.
References mpReportList.
Referenced by saveReportList().
 {return mpReportList != NULL;}
bool CCopasiXML::haveTaskList () const
Retrieve whether the XML contains a task list.
Returns
bool haveTaskList
Definition at line 308 of file CCopasiXML.cpp.
References mpTaskList.
Referenced by saveTaskList().
 {return mpTaskList != NULL;}
bool CCopasiXML::load (std::istream & is, const std::string & pwd) virtual
Load information from a given istream.
Parameters
std::istream & is
const std::string & pwd
Returns
bool success
Implements CCopasiXMLInterface.
Definition at line 169 of file CCopasiXML.cpp.
References BUFFER_SIZE, fatalError, fixBuild55(), fixBuild81(), CExpatTemplate< CType >::getCurrentColumnNumber(), CExpatTemplate< CType >::getCurrentLineNumber(), CExpatTemplate< CType >::getErrorString(), CCopasiXMLParser::getLayoutList(), CCopasiXMLParser::getModel(), CCopasiXMLParser::getPlotList(), CCopasiXMLParser::getReportList(), CCopasiXMLParser::getTaskList(), CVersion::getVersion(), CVersion::getVersionDevel(), MCXML, mpDataModel, mpFunctionList, mpGUI, CCopasiXMLInterface::mpIstream, mpLayoutList, mpModel, mpPlotList, mpReportList, mpTaskList, CCopasiXMLInterface::mPWD, CExpatTemplate< CType >::parse(), pdelete, CCopasiMessage::RAW, CCopasiXMLParser::setDatamodel(), CCopasiXMLParser::setFunctionList(), CCopasiXMLParser::setGUI(), CCopasiXMLParser::setLayoutList(), CVersion::VERSION, and CCopasiMessage::WARNING.
Referenced by CFunctionDB::load(), and CCopasiDataModel::loadModel().
 {
   mPWD = relativeTo;
   is.imbue(std::locale::classic());
   is.precision(16);
   mpIstream = &is;
   bool success = true;
   bool done = false;
   CVersion FileVersion;
   CCopasiXMLParser Parser(FileVersion);
   Parser.setFunctionList(mpFunctionList);
   Parser.setGUI(mpGUI);
   Parser.setLayoutList(mpLayoutList);
   Parser.setDatamodel(this->mpDataModel);
 #define BUFFER_SIZE 0xfffe
   char * pBuffer = new char[BUFFER_SIZE + 1];
   try
     {
       while (!done)
         {
           mpIstream->get(pBuffer, BUFFER_SIZE, 0);
           if (mpIstream->eof()) done = true;
           if (mpIstream->fail() && !done) fatalError();
           if (!Parser.parse(pBuffer, -1, done))
             {
               CCopasiMessage Message(CCopasiMessage::RAW, MCXML + 2,
                                      Parser.getCurrentLineNumber(),
                                      Parser.getCurrentColumnNumber(),
                                      Parser.getErrorString());
               done = true;
               success = false;
             }
         }
     }
   catch (...)
     {
       success = false;
     }
   delete [] pBuffer;
 #undef BUFFER_SIZE
   mpModel = Parser.getModel();
   mpReportList = Parser.getReportList();
   mpTaskList = Parser.getTaskList();
   mpPlotList = Parser.getPlotList();
   mpLayoutList = Parser.getLayoutList();
   if (!success)
     {
       pdelete(mpModel);
       pdelete(mpReportList);
       pdelete(mpTaskList);
       pdelete(mpPlotList);
       pdelete(mpLayoutList);
     }
   // The range in which the fix needs to be applied
   if (36 <= FileVersion.getVersionDevel() && FileVersion.getVersionDevel() <= 58)
     {
       fixBuild55();
     }
   if (FileVersion.getVersionDevel() <= 81)
     {
       fixBuild81();
     }
   if (!CVersion::VERSION.isCompatible(FileVersion))
     CCopasiMessage(CCopasiMessage::WARNING, MCXML + 9, FileVersion.getVersion().c_str());
   return success;
 }
bool CCopasiXML::save (std::ostream & os, const std::string & relativeTo) virtual
Save information to a given ostream.
Parameters
std::ostream & os
const std::string & relativeTo
Returns
bool success
Implements CCopasiXMLInterface.
Definition at line 102 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), buildFunctionList(), CCopasiXMLInterface::endSaveElement(), freeFunctionList(), CVersion::getVersion(), haveFunctionList(), haveModel(), CCopasiXMLInterface::mpOstream, CCopasiXMLInterface::mPWD, saveFunctionList(), saveGUI(), saveLayoutList(), saveModel(), savePlotList(), saveReportList(), saveSBMLReference(), saveTaskList(), CCopasiXMLInterface::startSaveElement(), UTCTimeStamp(), and CVersion::VERSION.
Referenced by save_cps_model_to_stream().
 {
   mPWD = relativeTo;
   os.imbue(std::locale::classic());
   os.precision(16);
   mpOstream = &os;
   bool success = true;
   *mpOstream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
              << std::endl;
   *mpOstream << "<!-- generated with COPASI "
              << CVersion::VERSION.getVersion()
              << " (http://www.copasi.org) at "
              << UTCTimeStamp()
              << " UTC -->"
              << std::endl;
   *mpOstream << "<?oxygen RNGSchema=\"http://www.copasi.org/static/schema/CopasiML.rng\" type=\"xml\"?>" << std::endl;
   CXMLAttributeList Attributes;
   Attributes.add("xmlns", "http://www.copasi.org/static/schema");
   Attributes.add("versionMajor", CVersion::VERSION.getVersionMajor());
   Attributes.add("versionMinor", CVersion::VERSION.getVersionMinor());
   Attributes.add("versionDevel", CVersion::VERSION.getVersionDevel());
   Attributes.add("copasiSourcesModified", CVersion::VERSION.isSourceModified());
   /*
   Attributes.add("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
   Attributes.add("xsi:noNamespaceSchemaLocation",
                  "http://www.copasi.org/static/schema/CopasiML.rng");
   */
   startSaveElement("COPASI", Attributes);
   if (haveModel() && !haveFunctionList())
     {
       if (!buildFunctionList()) success = false;
       if (!saveFunctionList()) success = false;
       if (!freeFunctionList()) success = false;
     }
   else if (!saveFunctionList()) success = false;
   if (!saveModel()) success = false;
   if (!saveTaskList()) success = false;
   if (!saveReportList()) success = false;
   if (!savePlotList()) success = false;
   if (!saveGUI()) success = false;
   if (!saveLayoutList()) success = false;
   if (!saveSBMLReference()) success = false;
   endSaveElement("COPASI");
   return success;
 }
void CCopasiXML::save1DAttributes (const CLGraphicalPrimitive1D & primitive, CXMLAttributeList & attributes) private
Saves the attributes for a 1D element
Definition at line 2342 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLGraphicalPrimitive1D::getDashArray(), CLGraphicalPrimitive1D::getStroke(), CLGraphicalPrimitive1D::getStrokeWidth(), CLGraphicalPrimitive1D::isSetDashArray(), CLGraphicalPrimitive1D::isSetStroke(), CLGraphicalPrimitive1D::isSetStrokeWidth(), and saveTransformationAttributes().
Referenced by save2DAttributes(), saveRenderCurveElement(), and saveRenderTextElement().
 {
   // first we go and add the transformation attributes because each 1D element is automatically a transformation element.
   saveTransformationAttributes(primitive, attributes);
   // stroke
   if (primitive.isSetStroke())
     {
       attributes.add("stroke", primitive.getStroke());
     }
   // stroke size
   if (primitive.isSetStrokeWidth())
     {
       std::ostringstream os;
       os << primitive.getStrokeWidth();
       attributes.add("stroke-width", os.str());
     }
   // stroke dash array
   if (primitive.isSetDashArray())
     {
       std::ostringstream os;
       size_t i, iMax = primitive.getDashArray().size();
       os << primitive.getDashArray()[0];
       for (i = 1; i < iMax; ++i)
         {
           os << ", " << primitive.getDashArray()[i];
         }
       attributes.add("stroke-dasharray", os.str());
     }
 }
void CCopasiXML::save2DAttributes (const CLGraphicalPrimitive2D & primitive, CXMLAttributeList & attributes) private
Saves the attributes for a 2D element
Definition at line 2380 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLGraphicalPrimitive2D::EVENODD, CLGraphicalPrimitive2D::getFillColor(), CLGraphicalPrimitive2D::getFillRule(), CLGraphicalPrimitive2D::isSetFill(), CLGraphicalPrimitive2D::isSetFillRule(), CLGraphicalPrimitive2D::NONZERO, and save1DAttributes().
Referenced by saveEllipseElement(), saveGroupElement(), savePolygonElement(), and saveRectangleElement().
 {
   // first we go and add the 1D attributes because each 2D element is automatically a 1D element.
   save1DAttributes(primitive, attributes);
   // fill
   if (primitive.isSetFill())
     {
       attributes.add("fill", primitive.getFillColor());
     }
   // fill rule
   if (primitive.isSetFillRule())
     {
       switch (primitive.getFillRule())
         {
           case CLGraphicalPrimitive2D::EVENODD:
             attributes.add("fill-rule", "evenodd");
             break;
           case CLGraphicalPrimitive2D::NONZERO:
           default:
             attributes.add("fill-rule", "nonzero");
             break;
         }
     }
 }
bool CCopasiXML::saveAnnotation (const CAnnotation * pAnnotation) private
Definition at line 922 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CAnnotation::getMiriamAnnotation(), CAnnotation::getNotes(), CAnnotation::getUnsupportedAnnotations(), CCopasiXMLInterface::mpOstream, CCopasiXMLInterface::saveXhtml(), CXMLAttributeList::setValue(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveFunctionList(), and saveModel().
 {
   if (pAnnotation->getMiriamAnnotation() != "")
     {
       startSaveElement("MiriamAnnotation");
       *mpOstream << pAnnotation->getMiriamAnnotation() << std::endl;
       endSaveElement("MiriamAnnotation");
     }
   if (pAnnotation->getNotes() != "")
     {
       startSaveElement("Comment");
       saveXhtml(pAnnotation->getNotes());
       endSaveElement("Comment");
     }
   if (pAnnotation->getUnsupportedAnnotations().size() > 0)
     {
       startSaveElement("ListOfUnsupportedAnnotations");
       CAnnotation::UnsupportedAnnotation::const_iterator it = pAnnotation->getUnsupportedAnnotations().begin();
       CAnnotation::UnsupportedAnnotation::const_iterator end = pAnnotation->getUnsupportedAnnotations().end();
       CXMLAttributeList Attributes;
       Attributes.add("name", "");
       for (; it != end; ++it)
         {
           Attributes.setValue(0, it->first);
           startSaveElement("UnsupportedAnnotation", Attributes);
           *mpOstream << it->second << std::endl;
           endSaveElement("UnsupportedAnnotation");
         }
       endSaveElement("ListOfUnsupportedAnnotations");
     }
   return true;
 }
template<typename HEADELEMENT > void CCopasiXML::saveArrowHeadAttributes (const HEADELEMENT & element, CXMLAttributeList & attributes) private
Saves the startHead and endHead attribute as found in group and curves. We write it as a template so that it can be used on curves and group elements.
Definition at line 2505 of file CCopasiXML.cpp.
References CXMLAttributeList::add().
 {
   // start head
   if (element.isSetStartHead())
     {
       attributes.add("startHead", element.getStartHead());
     }
   // start head
   if (element.isSetEndHead())
     {
       attributes.add("endHead", element.getEndHead());
     }
 }
void CCopasiXML::saveBoundingBox (const CLBoundingBox & bb) private
Definition at line 1382 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), CLBoundingBox::getDimensions(), CLBoundingBox::getPosition(), saveDimensions(), savePosition(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveLayoutList(), and saveLineEnding().
 {
   startSaveElement("BoundingBox");
   savePosition(bb.getPosition());
   saveDimensions(bb.getDimensions());
   endSaveElement("BoundingBox");
 }
void CCopasiXML::saveColorDefinition (const CLColorDefinition & color) private
Save a single color definition element.
Definition at line 2103 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLColorDefinition::createValueString(), CLColorDefinition::getId(), and CCopasiXMLInterface::saveElement().
Referenced by saveRenderInformationDefinitionElements().
 {
   CXMLAttributeList attributes;
   attributes.add("id", color.getId());
   attributes.add("value", color.createValueString());
   saveElement("ColorDefinition", attributes);
 }
void CCopasiXML::saveCurve (const CLCurve & c) private
Definition at line 1390 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CLLineSegment::getBase1(), CLLineSegment::getBase2(), CLCurve::getCurveSegments(), CLLineSegment::getEnd(), CLCurve::getNumCurveSegments(), CLLineSegment::getStart(), CLLineSegment::isBezier(), savePosition(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveLayoutList().
 {
   CXMLAttributeList Attributes;
   startSaveElement("Curve");
   if (c.getNumCurveSegments() > 0)
     {
       startSaveElement("ListOfCurveSegments");
       size_t i, imax = c.getNumCurveSegments();
       for (i = 0; i < imax; ++i)
         {
           const CLLineSegment & cs = c.getCurveSegments()[i];
           Attributes.erase();
           if (cs.isBezier())
             Attributes.add("xsi:type", "CubicBezier");
           else
             Attributes.add("xsi:type", "LineSegment");
           startSaveElement("CurveSegment", Attributes);
           savePosition(cs.getStart(), "Start");
           savePosition(cs.getEnd(), "End");
           if (cs.isBezier())
             {
               savePosition(cs.getBase1(), "BasePoint1");
               savePosition(cs.getBase2(), "BasePoint2");
             }
           endSaveElement("CurveSegment");
         }
       endSaveElement("ListOfCurveSegments");
     }
   endSaveElement("Curve");
 }
void CCopasiXML::saveCurveElements (const std::vector< CLRenderPoint * > & curveElements) private
saves a vector of curve elements. This can be called from the polygon as well as the curve.
Definition at line 2718 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), saveRenderPoint(), and CCopasiXMLInterface::startSaveElement().
Referenced by savePolygonElement(), and saveRenderCurveElement().
 {
   startSaveElement("ListOfElements");
   size_t i, iMax = curveElements.size();
   for (i = 0; i < iMax; ++i)
     {
       saveRenderPoint(*curveElements[i]);
     }
   endSaveElement("ListOfElements");
 }
void CCopasiXML::saveDimensions (const CLDimensions & d) private
Definition at line 1373 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CXMLAttributeList::erase(), CLDimensions::getHeight(), CLDimensions::getWidth(), and CCopasiXMLInterface::saveElement().
Referenced by saveBoundingBox().
 {
   CXMLAttributeList Attributes;
   Attributes.erase();
   Attributes.add("width", d.getWidth());
   Attributes.add("height", d.getHeight());
   saveElement("Dimensions", Attributes);
 }
void CCopasiXML::saveEllipseElement (const CLEllipse & ellipse) private
saves a single ellipse element.
Definition at line 2636 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLEllipse::getCX(), CLEllipse::getCY(), CLEllipse::getCZ(), CLEllipse::getRX(), CLEllipse::getRY(), save2DAttributes(), CCopasiXMLInterface::saveElement(), and CLRelAbsVector::toString().
Referenced by saveTransformation2D().
 {
   CXMLAttributeList attributes;
   // first we add the attributes for a 2D object
   save2DAttributes(ellipse, attributes);
   // now we add the ellipse specific attributes
   attributes.add("cx", ellipse.getCX().toString());
   attributes.add("cy", ellipse.getCY().toString());
   if (ellipse.getCZ() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("cz", ellipse.getCZ().toString());
     }
   if (ellipse.getRX() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("rx", ellipse.getRX().toString());
     }
   if (ellipse.getRY() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("ry", ellipse.getRY().toString());
     }
   saveElement("Ellipse", attributes);
 }
bool CCopasiXML::saveFunctionList () private
Save the list of functions.
Returns
bool success
Definition at line 1018 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CEvaluationTree::getInfix(), CFunction::getKey(), CFunctionParameter::getKey(), CCopasiObject::getObjectName(), CFunction::getSBMLId(), CEvaluationTree::getType(), CFunctionParameter::getUsage(), CFunction::getVariables(), haveFunctionList(), CFunction::isReversible(), mpFunctionList, mSBMLReference, CFunctionParameter::RoleNameXML, saveAnnotation(), CCopasiXMLInterface::saveData(), CCopasiXMLInterface::saveElement(), CXMLAttributeList::setValue(), CFunctionParameters::size(), CCopasiVector< T >::size(), CCopasiXMLInterface::startSaveElement(), TriFalse, TriTrue, TriUnspecified, and CEvaluationTree::XMLType.
Referenced by save().
 {
   bool success = true;
   if (!haveFunctionList()) return success;
   size_t i, imax = mpFunctionList->size();
   if (!imax) return success;
   CXMLAttributeList Attributes;
   CFunction * pFunction = NULL;
   startSaveElement("ListOfFunctions");
   for (i = 0; i < imax; i++)
     {
       pFunction = (*mpFunctionList)[i];
       Attributes.erase();
       Attributes.add("key", pFunction->getKey());
       Attributes.add("name", pFunction->getObjectName());
       Attributes.add("type", CEvaluationTree::XMLType[pFunction->getType()]);
       if (pFunction)
         {
           switch (pFunction->isReversible())
             {
               case TriUnspecified:
                 Attributes.add("reversible", "unspecified");
                 break;
               case TriFalse:
                 Attributes.add("reversible", "false");
                 break;
               case TriTrue:
                 Attributes.add("reversible", "true");
                 break;
             }
           if (pFunction->getSBMLId() != "")
             mSBMLReference[pFunction->getSBMLId()] = pFunction->getKey();
         }
       startSaveElement("Function", Attributes);
       saveAnnotation(pFunction);
       startSaveElement("Expression");
       saveData(pFunction->getInfix());
       endSaveElement("Expression");
       if (pFunction)
         {
           startSaveElement("ListOfParameterDescriptions");
           size_t j, jmax = pFunction->getVariables().size();
           CFunctionParameter * pParameter;
           Attributes.erase();
           Attributes.add("key", "");
           Attributes.add("name", "");
           Attributes.add("order", "");
           Attributes.add("role", "");
           for (j = 0; j < jmax; j++)
             {
               pParameter = pFunction->getVariables()[j];
               Attributes.setValue(0, pParameter->getKey());
               Attributes.setValue(1, pParameter->getObjectName());
               Attributes.setValue(2, j);
               Attributes.setValue(3, CFunctionParameter::RoleNameXML[pParameter->getUsage()]);
               saveElement("ParameterDescription", Attributes);
             }
           endSaveElement("ListOfParameterDescriptions");
         }
       endSaveElement("Function");
     }
   endSaveElement("ListOfFunctions");
   return success;
 }
void CCopasiXML::saveGlobalRenderInformation (const CLGlobalRenderInformation & renderInfo) private
Saves a single global render information object.
Definition at line 1955 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), CLGlobalRenderInformation::getNumStyles(), CLGlobalRenderInformation::getStyle(), saveGlobalStyle(), saveRenderInformationAttributes(), saveRenderInformationDefinitionElements(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveListOfGlobalRenderInformation().
 {
   // first we create the attributes that are common to all render information objects
   CXMLAttributeList attributes;
   saveRenderInformationAttributes(renderInfo, attributes);
   startSaveElement("RenderInformation", attributes);
   // now we save the definition that are the same for all render information objects
   saveRenderInformationDefinitionElements(renderInfo);
   // last we save the global styles
   size_t i, iMax = renderInfo.getNumStyles();
   if (iMax > 0)
     {
       startSaveElement("ListOfStyles");
       for (i = 0; i < iMax; ++i)
         {
           saveGlobalStyle(*(dynamic_cast<const CLGlobalStyle*>(renderInfo.getStyle(i))));
         }
       endSaveElement("ListOfStyles");
     }
   endSaveElement("RenderInformation");
 }
void CCopasiXML::saveGlobalStyle (const CLGlobalStyle & style) private
Saves a single local style element.
Definition at line 2253 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), saveStyleAttributes(), saveStyleElements(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveGlobalRenderInformation().
 {
   // first we create the attributes
   CXMLAttributeList attributes;
   saveStyleAttributes(style, attributes);
   startSaveElement("Style", attributes);
   saveStyleElements(style);
   endSaveElement("Style");
 }
void CCopasiXML::saveGradientAttributes (const CLGradientBase & gradient, CXMLAttributeList & attributes) private
Adds the attributes common to radial and linear gradient.
Definition at line 2167 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLGradientBase::getId(), CLGradientBase::getSpreadMethod(), CLGradientBase::PAD, CLGradientBase::REFLECT, and CLGradientBase::REPEAT.
Referenced by saveLinearGradient(), and saveRadialGradient().
 {
   attributes.add("id", gradient.getId());
   switch (gradient.getSpreadMethod())
     {
       case CLGradientBase::REPEAT:
         attributes.add("spreadMethod", "repeat");
         break;
       case CLGradientBase::REFLECT:
         attributes.add("spreadMethod", "reflect");
         break;
       case CLGradientBase::PAD:
       default:
         attributes.add("spreadMethod", "pad");
         break;
     }
 }
void CCopasiXML::saveGradientElements (const CLGradientBase & gradient) private
Saves the elements that are common to linear and radial gradients.
Definition at line 2191 of file CCopasiXML.cpp.
References CLGradientBase::getGradientStop(), CLGradientBase::getNumGradientStops(), and saveGradientStop().
Referenced by saveLinearGradient(), and saveRadialGradient().
 {
   size_t i, iMax = gradient.getNumGradientStops();
   if (iMax > 0)
     {
       for (i = 0; i < iMax; ++i)
         {
           saveGradientStop(*(gradient.getGradientStop(i)));
         }
     }
 }
void CCopasiXML::saveGradientStop (const CLGradientStop & stop) private
Saves a single gradient stop element.
Definition at line 2207 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLGradientStop::getOffset(), CLGradientStop::getStopColor(), CCopasiXMLInterface::saveElement(), and CLRelAbsVector::toString().
Referenced by saveGradientElements().
 {
   CXMLAttributeList attributes;
   attributes.add("offset", stop.getOffset().toString());
   attributes.add("stop-color", stop.getStopColor());
   saveElement("Stop", attributes);
 }
void CCopasiXML::saveGroupElement (const CLGroup & group) private
Saves a group element.
Definition at line 2293 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), save2DAttributes(), saveTransformation2D(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveLineEnding(), saveStyleElements(), and saveTransformation2D().
 {
   CXMLAttributeList attributes;
   save2DAttributes(group, attributes);
   saveTextAttributes<CLGroup>(group, attributes);
   saveArrowHeadAttributes<CLGroup>(group, attributes);
   startSaveElement("Group", attributes);
   size_t i, iMax = group.getNumElements();
   if (iMax > 0)
     {
       for (i = 0; i < iMax; ++i)
         {
           saveTransformation2D(*dynamic_cast<const CLTransformation2D*>(group.getElement(i)));
         }
     }
   endSaveElement("Group");
 }
bool CCopasiXML::saveGUI () private
Save GUI information
Returns
bool success
Definition at line 1779 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CSlider::convertScaleToScaleName(), CCopasiXMLInterface::endSaveElement(), CSlider::getAssociatedEntityKey(), CSlider::getKey(), CSlider::getMaxValue(), CSlider::getMinValue(), CSlider::getScaling(), SCopasiXMLGUI::getSliderList(), CSlider::getSliderObjectCN(), CSlider::getSliderType(), CSlider::getSliderValue(), CSlider::getTickFactor(), CSlider::getTickNumber(), haveGUI(), mpGUI, CCopasiXMLInterface::saveElement(), CXMLAttributeList::setValue(), CCopasiVector< T >::size(), CCopasiXMLInterface::startSaveElement(), and CSlider::TypeName.
Referenced by save().
 {
   bool success = true;
   if (!haveGUI()) return success;
   startSaveElement("GUI");
   if (mpGUI->getSliderList() && mpGUI->getSliderList()->size())
     {
       startSaveElement("ListOfSliders");
       CSlider * pSlider;
       CXMLAttributeList Attributes;
       Attributes.add("key", "");
       Attributes.add("associatedEntityKey", "");
       Attributes.add("objectCN", "");
       Attributes.add("objectType", "");
       Attributes.add("objectValue", "");
       Attributes.add("minValue", "");
       Attributes.add("maxValue", "");
       Attributes.add("tickNumber", "");
       Attributes.add("tickFactor", "");
       Attributes.add("scaling", "");
       size_t i, imax = mpGUI->getSliderList()->size();
       for (i = 0; i < imax; i++)
         {
           pSlider = (*mpGUI->getSliderList())[i];
           Attributes.setValue(0, pSlider->getKey());
           Attributes.setValue(1, pSlider->getAssociatedEntityKey());
           Attributes.setValue(2, pSlider->getSliderObjectCN());
           Attributes.setValue(3, CSlider::TypeName[pSlider->getSliderType()]);
           Attributes.setValue(4, pSlider->getSliderValue());
           Attributes.setValue(5, pSlider->getMinValue());
           Attributes.setValue(6, pSlider->getMaxValue());
           Attributes.setValue(7, pSlider->getTickNumber());
           Attributes.setValue(8, pSlider->getTickFactor());
           Attributes.setValue(9, pSlider->convertScaleToScaleName(pSlider->getScaling()));
           saveElement("Slider", Attributes);
         }
       endSaveElement("ListOfSliders");
     }
   endSaveElement("GUI");
   return success;
 }
void CCopasiXML::saveImageElement (const CLImage & image) private
saves a single image element.
Definition at line 2580 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLImage::getHeight(), CLImage::getImageReference(), CLImage::getWidth(), CLImage::getX(), CLImage::getY(), CLImage::getZ(), CCopasiXMLInterface::saveElement(), saveTransformationAttributes(), and CLRelAbsVector::toString().
Referenced by saveTransformation2D().
 {
   CXMLAttributeList attributes;
   // first we add the attributes for a transformation
   saveTransformationAttributes(image, attributes);
   // now we add the image specific attributes
   attributes.add("x", image.getX().toString());
   attributes.add("y", image.getY().toString());
   if (image.getZ() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("z", image.getZ().toString());
     }
   attributes.add("width", image.getWidth().toString());
   attributes.add("height", image.getHeight().toString());
   attributes.add("href", image.getImageReference());
   saveElement("Image", attributes);
 }
bool CCopasiXML::saveLayoutList () private
Save the list of layout.
Returns
bool success
Definition at line 1431 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CLGraphicalObject::getBoundingBox(), CLGlyphWithCurve::getCurve(), CLayout::getDimensions(), CLTextGlyph::getGraphicalObjectKey(), CLDimensions::getHeight(), CLayout::getKey(), CLGraphicalObject::getKey(), CLayout::getListOfCompartmentGlyphs(), CLayout::getListOfGeneralGlyphs(), CListOfLayouts::getListOfGlobalRenderInformationObjects(), CLayout::getListOfLocalRenderInformationObjects(), CLayout::getListOfMetaboliteGlyphs(), CLReactionGlyph::getListOfMetabReferenceGlyphs(), CLayout::getListOfReactionGlyphs(), CLayout::getListOfTextGlyphs(), CLMetabReferenceGlyph::getMetabGlyphKey(), CLGraphicalObject::getModelObjectKey(), CLCurve::getNumCurveSegments(), CCopasiObject::getObjectName(), CLGraphicalObject::getObjectRole(), CLMetabReferenceGlyph::getRole(), CLTextGlyph::getText(), CLDimensions::getWidth(), CLGraphicalObject::hasValidModelReference(), haveLayoutList(), CLTextGlyph::isTextSet(), MCXML, mMCXML21Issued, mpLayoutList, saveBoundingBox(), saveCurve(), CCopasiXMLInterface::saveElement(), saveListOfGlobalRenderInformation(), saveListOfLocalRenderInformation(), CLGraphicalObject::setModelObjectKey(), CLTextGlyph::setText(), CCopasiVector< T >::size(), CCopasiXMLInterface::startSaveElement(), CCopasiMessage::WARNING, and CLMetabReferenceGlyph::XMLRole.
Referenced by save().
 {
   bool success = true;
   if (!haveLayoutList()) return success;
   size_t i, imax = mpLayoutList->size();
   if (!imax) return success;
   CXMLAttributeList Attributes;
   CLayout * pLayout = NULL;
   Attributes.add("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");
   startSaveElement("ListOfLayouts", Attributes);
   for (i = 0; i < imax; i++)
     {
       pLayout = (*mpLayoutList)[i];
       Attributes.erase();
       Attributes.add("key", pLayout->getKey());
       Attributes.add("name", pLayout->getObjectName());
       startSaveElement("Layout", Attributes);
       Attributes.erase();
       Attributes.add("width", pLayout->getDimensions().getWidth());
       Attributes.add("height", pLayout->getDimensions().getHeight());
       saveElement("Dimensions", Attributes);
       size_t j, jmax;
       //compartment glyphs
       if (pLayout->getListOfCompartmentGlyphs().size() > 0)
         {
           startSaveElement("ListOfCompartmentGlyphs");
           jmax = pLayout->getListOfCompartmentGlyphs().size();
           for (j = 0; j < jmax; ++j)
             {
               CLCompartmentGlyph* cg = pLayout->getListOfCompartmentGlyphs()[j];
               Attributes.erase();
               Attributes.add("key", cg->getKey());
               Attributes.add("name", cg->getObjectName());
               if (!cg->getModelObjectKey().empty() && cg->hasValidModelReference())
                 {
                   Attributes.add("compartment", cg->getModelObjectKey());
                 }
               else
                 {
                   // we set the model reference to the empty string so that
                   // the warnings message only appears on the first save operation
                   cg->setModelObjectKey("");
                   if (!this->mMCXML21Issued)
                     {
                       CCopasiMessage(CCopasiMessage::WARNING, MCXML + 21);
                       this->mMCXML21Issued = true;
                     }
                   // Bug 1973: we still write out the attribute, so that older
                   //           versions of COPASI do not refuse to read the model
                   Attributes.add("metabolite", "");
                 }
               if (cg->getObjectRole().find_first_not_of(" \t\r\n") != std::string::npos)
                 {
                   Attributes.add("objectRole", cg->getObjectRole());
                 }
               startSaveElement("CompartmentGlyph", Attributes);
               saveBoundingBox(cg->getBoundingBox());
               endSaveElement("CompartmentGlyph");
             }
           endSaveElement("ListOfCompartmentGlyphs");
         }
       //species glyphs
       if (pLayout->getListOfMetaboliteGlyphs().size() > 0)
         {
           startSaveElement("ListOfMetabGlyphs");
           jmax = pLayout->getListOfMetaboliteGlyphs().size();
           for (j = 0; j < jmax; ++j)
             {
               CLMetabGlyph* cg = pLayout->getListOfMetaboliteGlyphs()[j];
               Attributes.erase();
               Attributes.add("key", cg->getKey());
               Attributes.add("name", cg->getObjectName());
               if (!cg->getModelObjectKey().empty() && cg->hasValidModelReference())
                 {
                   Attributes.add("metabolite", cg->getModelObjectKey());
                 }
               else
                 {
                   // we set the model reference to the empty string so that
                   // the warnings message only appears on the first save operation
                   cg->setModelObjectKey("");
                   if (!this->mMCXML21Issued)
                     {
                       CCopasiMessage(CCopasiMessage::WARNING, MCXML + 21);
                       this->mMCXML21Issued = true;
                     }
                   // Bug 1973: we still write out the attribute, so that older
                   //           versions of COPASI do not refuse to read the model
                   Attributes.add("metabolite", "");
                 }
               if (cg->getObjectRole().find_first_not_of(" \t\r\n") != std::string::npos)
                 {
                   Attributes.add("objectRole", cg->getObjectRole());
                 }
               startSaveElement("MetaboliteGlyph", Attributes);
               saveBoundingBox(cg->getBoundingBox());
               endSaveElement("MetaboliteGlyph");
             }
           endSaveElement("ListOfMetabGlyphs");
         }
       //reaction glyphs
       if (pLayout->getListOfReactionGlyphs().size() > 0)
         {
           startSaveElement("ListOfReactionGlyphs");
           jmax = pLayout->getListOfReactionGlyphs().size();
           for (j = 0; j < jmax; ++j)
             {
               CLReactionGlyph* cg = pLayout->getListOfReactionGlyphs()[j];
               Attributes.erase();
               Attributes.add("key", cg->getKey());
               Attributes.add("name", cg->getObjectName());
               if (!cg->getModelObjectKey().empty() && cg->hasValidModelReference())
                 {
                   Attributes.add("reaction", cg->getModelObjectKey());
                 }
               else
                 {
                   // we set the model reference to the empty string so that
                   // the warnings message only appears on the first save operation
                   cg->setModelObjectKey("");
                   if (!this->mMCXML21Issued)
                     {
                       CCopasiMessage(CCopasiMessage::WARNING, MCXML + 21);
                       this->mMCXML21Issued = true;
                     }
                 }
               if (cg->getObjectRole().find_first_not_of(" \t\r\n") != std::string::npos)
                 {
                   Attributes.add("objectRole", cg->getObjectRole());
                 }
               startSaveElement("ReactionGlyph", Attributes);
               if (cg->getCurve().getNumCurveSegments() == 0)
                 saveBoundingBox(cg->getBoundingBox());
               else
                 saveCurve(cg->getCurve());
               // metab reference glyphs
               startSaveElement("ListOfMetaboliteReferenceGlyphs");
               size_t k, kmax = cg->getListOfMetabReferenceGlyphs().size();
               for (k = 0; k < kmax; ++k)
                 {
                   CLMetabReferenceGlyph * mrg = cg->getListOfMetabReferenceGlyphs()[k];
                   Attributes.erase();
                   Attributes.add("key", mrg->getKey());
                   Attributes.add("name", mrg->getObjectName());
                   Attributes.add("metaboliteGlyph", mrg->getMetabGlyphKey());
                   //Attributes.add("metaboliteReference", mrg->getXXX());
                   Attributes.add("role", CLMetabReferenceGlyph::XMLRole[mrg->getRole()]);
                   if (mrg->getObjectRole().find_first_not_of(" \t\r\n") != std::string::npos)
                     {
                       Attributes.add("objectRole", mrg->getObjectRole());
                     }
                   startSaveElement("MetaboliteReferenceGlyph", Attributes);
                   if (mrg->getCurve().getNumCurveSegments() == 0)
                     saveBoundingBox(mrg->getBoundingBox());
                   else
                     saveCurve(mrg->getCurve());
                   endSaveElement("MetaboliteReferenceGlyph");
                 }
               endSaveElement("ListOfMetaboliteReferenceGlyphs");
               endSaveElement("ReactionGlyph");
             }
           endSaveElement("ListOfReactionGlyphs");
         }
       //text Glyphs
       if (pLayout->getListOfTextGlyphs().size() > 0)
         {
           startSaveElement("ListOfTextGlyphs");
           jmax = pLayout->getListOfTextGlyphs().size();
           for (j = 0; j < jmax; ++j)
             {
               CLTextGlyph* cg = pLayout->getListOfTextGlyphs()[j];
               // we only export the text glyph if it either has a text
               // or a valid originOfText
               std::string id = cg->getModelObjectKey();
               if (cg->isTextSet() || id.find_first_not_of(" \t\r\n") != std::string::npos)
                 {
                   Attributes.erase();
                   Attributes.add("key", cg->getKey());
                   Attributes.add("name", cg->getObjectName());
                   Attributes.add("graphicalObject", cg->getGraphicalObjectKey());
                   if (cg->isTextSet())
                     {
                       Attributes.add("text", cg->getText());
                     }
                   else
                     {
                       // check if the object actually exists
                       if (cg->hasValidModelReference())
{
                           Attributes.add("originOfText", id);
                         }
                       else
{
                           // set the text to unset instead
                           Attributes.add("text", "unset");
                           // set the invalid key to the empty string
                           cg->setModelObjectKey("");
                           cg->setText("unset");
                           if (!this->mMCXML21Issued)
{
                               CCopasiMessage(CCopasiMessage::WARNING, MCXML + 21);
                               this->mMCXML21Issued = true;
                             }
                         }
                     }
                   if (cg->getObjectRole().find_first_not_of(" \t\r\n") != std::string::npos)
                     {
                       Attributes.add("objectRole", cg->getObjectRole());
                     }
                   startSaveElement("TextGlyph", Attributes);
                   saveBoundingBox(cg->getBoundingBox());
                   endSaveElement("TextGlyph");
                 }
             }
           endSaveElement("ListOfTextGlyphs");
         }
       //additional graphical objects
       if (pLayout->getListOfGeneralGlyphs().size() > 0)
         {
           startSaveElement("ListOfAdditionalGraphicalObjects");
           jmax = pLayout->getListOfGeneralGlyphs().size();
           for (j = 0; j < jmax; ++j)
             {
               CLGeneralGlyph* cg = pLayout->getListOfGeneralGlyphs()[j];
               Attributes.erase();
               Attributes.add("key", cg->getKey());
               Attributes.add("name", cg->getObjectName());
               if (!cg->getModelObjectKey().empty() && cg->hasValidModelReference())
                 {
                   Attributes.add("reference", cg->getModelObjectKey());
                 }
               else
                 {
                   // we set the model reference to the empty string so that
                   // the warnings message only appears on the first save operation
                   cg->setModelObjectKey("");
                   //a general glyph does not necessarily have a model reference.
                   //so no warning is issued
                   /*if (!this->mMCXML21Issued)
                     {
                       CCopasiMessage(CCopasiMessage::WARNING, MCXML + 21);
                       this->mMCXML21Issued = true;
                     }*/
                 }
               if (cg->getObjectRole().find_first_not_of(" \t\r\n") != std::string::npos)
                 {
                   Attributes.add("objectRole", cg->getObjectRole());
                 }
               startSaveElement("AdditionalGraphicalObject", Attributes);
               //if (cg->getCurve().getNumCurveSegments() == 0)
               saveBoundingBox(cg->getBoundingBox());
               //else
               //  saveCurve(cg->getCurve());
               // reference glyphs
               endSaveElement("AdditionalGraphicalObject");
             }
           endSaveElement("ListOfAdditionalGraphicalObjects");
         }
       // save the local render information
       if (pLayout->getListOfLocalRenderInformationObjects().size() > 0)
         {
           saveListOfLocalRenderInformation(pLayout->getListOfLocalRenderInformationObjects());
         }
       endSaveElement("Layout");
     }
   // save the global render information list
   if (mpLayoutList->getListOfGlobalRenderInformationObjects().size() > 0)
     {
       saveListOfGlobalRenderInformation(mpLayoutList->getListOfGlobalRenderInformationObjects());
     }
   endSaveElement("ListOfLayouts");
   return success;
 }
void CCopasiXML::saveLinearGradient (const CLLinearGradient & gradient) private
Saves a single linear gradient definition.
Definition at line 2114 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CLLinearGradient::getXPoint1(), CLLinearGradient::getXPoint2(), CLLinearGradient::getYPoint1(), CLLinearGradient::getYPoint2(), CLLinearGradient::getZPoint1(), CLLinearGradient::getZPoint2(), saveGradientAttributes(), saveGradientElements(), CCopasiXMLInterface::startSaveElement(), and CLRelAbsVector::toString().
Referenced by saveRenderInformationDefinitionElements().
 {
   CXMLAttributeList attributes;
   // first we create the common attributes
   saveGradientAttributes(gradient, attributes);
   // now we add the attributes specific to the radial gradient
   attributes.add("x1", gradient.getXPoint1().toString());
   attributes.add("y1", gradient.getYPoint1().toString());
   if (gradient.getZPoint1() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("z1", gradient.getZPoint1().toString());
     }
   attributes.add("x2", gradient.getXPoint2().toString());
   attributes.add("y2", gradient.getYPoint2().toString());
   if (gradient.getZPoint2() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("z2", gradient.getZPoint2().toString());
     }
   startSaveElement("LinearGradient", attributes);
   // save the gradient stops
   saveGradientElements(gradient);
   endSaveElement("LinearGradient");
 }
void CCopasiXML::saveLineEnding (const CLLineEnding & lineEnding) private
Saves a line ending definiton,
Definition at line 2215 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CLLineEnding::getBoundingBox(), CLLineEnding::getGroup(), CLLineEnding::getId(), CLLineEnding::getIsEnabledRotationalMapping(), saveBoundingBox(), saveGroupElement(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveRenderInformationDefinitionElements().
 {
   // create the attributes
   CXMLAttributeList attributes;
   attributes.add("id", lineEnding.getId());
   attributes.add("enableRotationalMapping", lineEnding.getIsEnabledRotationalMapping() ? std::string("true") : std::string("false"));
   startSaveElement("LineEnding", attributes);
   // a line ending has a bounding box
   saveBoundingBox(*(lineEnding.getBoundingBox()));
   // and a group element
   assert(lineEnding.getGroup() != NULL);
   saveGroupElement(*lineEnding.getGroup());
   endSaveElement("LineEnding");
 }
void CCopasiXML::saveListOfGlobalRenderInformation (const CCopasiVector< CLGlobalRenderInformation > & list) private
Saves the list of global render information objects.
Definition at line 1923 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), saveGlobalRenderInformation(), CCopasiVector< T >::size(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveLayoutList().
 {
   startSaveElement("ListOfGlobalRenderInformation");
   size_t i, iMax = list.size();
   for (i = 0; i < iMax; ++i)
     {
       saveGlobalRenderInformation(*list[i]);
     }
   endSaveElement("ListOfGlobalRenderInformation");
 }
void CCopasiXML::saveListOfLocalRenderInformation (const CCopasiVector< CLLocalRenderInformation > & list) private
Saves the list of local render information objects.
Definition at line 1939 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), saveLocalRenderInformation(), CCopasiVector< T >::size(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveLayoutList().
 {
   startSaveElement("ListOfRenderInformation");
   size_t i, iMax = list.size();
   for (i = 0; i < iMax; ++i)
     {
       saveLocalRenderInformation(*list[i]);
     }
   endSaveElement("ListOfRenderInformation");
 }
void CCopasiXML::saveLocalRenderInformation (const CLLocalRenderInformation & renderInfo) private
Saves a single local render information object.
Definition at line 1984 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), CLLocalRenderInformation::getNumStyles(), CLLocalRenderInformation::getStyle(), saveLocalStyle(), saveRenderInformationAttributes(), saveRenderInformationDefinitionElements(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveListOfLocalRenderInformation().
 {
   // first we create the attributes that are common to all render information objects
   CXMLAttributeList attributes;
   saveRenderInformationAttributes(renderInfo, attributes);
   startSaveElement("RenderInformation", attributes);
   // now we save the definition that are the same for all render information objects
   saveRenderInformationDefinitionElements(renderInfo);
   // last we save the global styles
   size_t i, iMax = renderInfo.getNumStyles();
   if (iMax > 0)
     {
       startSaveElement("ListOfStyles");
       for (i = 0; i < iMax; ++i)
         {
           saveLocalStyle(*(dynamic_cast<const CLLocalStyle*>(renderInfo.getStyle(i))));
         }
       endSaveElement("ListOfStyles");
     }
   endSaveElement("RenderInformation");
 }
void CCopasiXML::saveLocalStyle (const CLLocalStyle & style) private
Saves a single local style element.
Definition at line 2233 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLStyle::createStringFromSet(), CCopasiXMLInterface::endSaveElement(), CLLocalStyle::getKeyList(), CLLocalStyle::getNumKeys(), saveStyleAttributes(), saveStyleElements(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveLocalRenderInformation().
 {
   // first we create the attributes
   CXMLAttributeList attributes;
   saveStyleAttributes(style, attributes);
   // now we add the attributes that are specific to local styles
   if (style.getNumKeys() > 0)
     {
       attributes.add("keyList", CLStyle::createStringFromSet(style.getKeyList()));
     }
   startSaveElement("Style", attributes);
   saveStyleElements(style);
   endSaveElement("Style");
 }
bool CCopasiXML::saveModel () private
Save the model.
Returns
bool success
Definition at line 395 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CModelParameterGroup::begin(), CCopasiVector< T >::begin(), CModelParameterGroup::end(), CCopasiVector< T >::end(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CModelEntity::FIXED, CModel::getAreaUnitName(), CEvent::getAssignments(), CModel::getAvogadro(), CReaction::getChemEq(), CMetab::getCompartment(), CModel::getCompartments(), CEvent::getDelayAssignment(), CEvent::getDelayExpression(), CCompartment::getDimensionality(), CStateTemplate::getEntities(), CModel::getEvents(), CModelEntity::getExpression(), CEvent::getFireAtInitialTime(), CReaction::getFunction(), CReaction::getFunctionParameters(), CModelEntity::getInitialExpression(), CModelParameterSet::getKey(), CFunction::getKey(), CModelEntity::getKey(), CReaction::getKey(), CEvent::getKey(), CCopasiParameterGroup::getKey(), CModel::getKey(), CModel::getLengthUnitName(), CModel::getMetabolites(), CModel::getModelParameterSet(), CModel::getModelParameterSets(), CModel::getModelType(), CModel::getModelValues(), CChemEq::getModifiers(), CCopasiParameterGroup::getName(), CCopasiObject::getObjectName(), CReaction::getParameterMappings(), CReaction::getParameters(), CEvent::getPersistentTrigger(), CChemEq::getProducts(), CModel::getQuantityUnitName(), CModel::getReactions(), CModelEntity::getSBMLId(), CEvent::getSBMLId(), CReaction::getSBMLId(), CModel::getStateTemplate(), CModelEntity::getStatus(), CChemEq::getSubstrates(), CModel::getTimeUnitName(), CEvent::getTriggerExpression(), CCopasiRootContainer::getUndefinedFunction(), CCopasiParameterGroup::getValue(), CModel::getVolumeUnitName(), haveModel(), CReaction::isFast(), CReaction::isReversible(), CCopasiXMLInterface::mIndent, CModel::ModelTypeNames, mpModel, CCopasiXMLInterface::mpOstream, mSBMLReference, CCopasiParameter::Value::pDOUBLE, CModelEntity::REACTIONS, saveAnnotation(), CCopasiXMLInterface::saveData(), CCopasiXMLInterface::saveElement(), saveModelParameter(), CXMLAttributeList::setValue(), CFunctionParameters::size(), CStateTemplate::size(), CCopasiVector< T >::size(), CCopasiParameterGroup::size(), CXMLAttributeList::skip(), CCopasiXMLInterface::startSaveElement(), and CModelEntity::XMLStatus.
Referenced by save().
 {
   bool success = true;
   if (!haveModel()) return success;
   CXMLAttributeList Attributes;
   Attributes.add("key", mpModel->getKey());
   Attributes.add("name", mpModel->getObjectName());
   Attributes.add("simulationType", CModelEntity::XMLStatus[mpModel->getStatus()]);
   Attributes.add("timeUnit", mpModel->getTimeUnitName());
   Attributes.add("volumeUnit", mpModel->getVolumeUnitName());
   Attributes.add("areaUnit", mpModel->getAreaUnitName());
   Attributes.add("lengthUnit", mpModel->getLengthUnitName());
   Attributes.add("quantityUnit", mpModel->getQuantityUnitName());
   Attributes.add("type", CModel::ModelTypeNames[mpModel->getModelType()]);
   Attributes.add("avogadroConstant", mpModel->getAvogadro());
   // This is now optional
   // Attributes.add("stateVariable",
   //                mpModel->getStateTemplate().getKey(mpModel->getKey()));
   startSaveElement("Model", Attributes);
   saveAnnotation(mpModel);
   if (mpModel->getInitialExpression() != "")
     {
       startSaveElement("InitialExpression");
       saveData(mpModel->getInitialExpression());
       endSaveElement("InitialExpression");
     }
   size_t i, imax;
   // Compartment
   if ((imax = mpModel->getCompartments().size()) > 0)
     {
       startSaveElement("ListOfCompartments");
       Attributes.erase();
       Attributes.add("key", "");
       Attributes.add("name", "");
       Attributes.add("simulationType", "");
       Attributes.add("dimensionality", "");
       size_t i, imax = mpModel->getCompartments().size();
       for (i = 0; i < imax; i++)
         {
           CCompartment * pComp = mpModel->getCompartments()[i];
           Attributes.setValue(0, pComp->getKey());
           Attributes.setValue(1, pComp->getObjectName());
           CModelEntity::Status SimulationType = pComp->getStatus();
           Attributes.setValue(2, CModelEntity::XMLStatus[SimulationType]);
           Attributes.setValue(3, pComp->getDimensionality());
           startSaveElement("Compartment", Attributes);
           saveAnnotation(pComp);
           if (SimulationType != CModelEntity::FIXED &&
               pComp->getExpression() != "")
             {
               startSaveElement("Expression");
               saveData(pComp->getExpression());
               endSaveElement("Expression");
             }
           if (pComp->getInitialExpression() != "")
             {
               startSaveElement("InitialExpression");
               saveData(pComp->getInitialExpression());
               endSaveElement("InitialExpression");
             }
           endSaveElement("Compartment");
           if (pComp->getSBMLId() != "")
             mSBMLReference[pComp->getSBMLId()] = pComp->getKey();
         }
       endSaveElement("ListOfCompartments");
     }
   // Metabolites (aka. Species)
   if ((imax = mpModel->getMetabolites().size()) > 0)
     {
       startSaveElement("ListOfMetabolites");
       Attributes.erase();
       Attributes.add("key", "");
       Attributes.add("name", "");
       Attributes.add("simulationType", "");
       Attributes.add("compartment", "");
       for (i = 0; i < imax; i++)
         {
           CMetab * pMetab = mpModel->getMetabolites()[i];
           Attributes.setValue(0, pMetab->getKey());
           Attributes.setValue(1, pMetab->getObjectName());
           CModelEntity::Status SimulationType = pMetab->getStatus();
           Attributes.setValue(2, CModelEntity::XMLStatus[SimulationType]);
           Attributes.setValue(3, pMetab->getCompartment()->getKey());
           startSaveElement("Metabolite", Attributes);
           saveAnnotation(pMetab);
           if (SimulationType != CModelEntity::FIXED &&
               SimulationType != CModelEntity::REACTIONS &&
               pMetab->getExpression() != "")
             {
               startSaveElement("Expression");
               saveData(pMetab->getExpression());
               endSaveElement("Expression");
             }
           if (pMetab->getInitialExpression() != "")
             {
               startSaveElement("InitialExpression");
               saveData(pMetab->getInitialExpression());
               endSaveElement("InitialExpression");
             }
           endSaveElement("Metabolite");
           if (pMetab->getSBMLId() != "")
             mSBMLReference[pMetab->getSBMLId()] = pMetab->getKey();
         }
       endSaveElement("ListOfMetabolites");
     }
   // Model Values (aka. Global Quantities)
   if ((imax = mpModel->getModelValues().size()) > 0)
     {
       startSaveElement("ListOfModelValues");
       Attributes.erase();
       Attributes.add("key", "");
       Attributes.add("name", "");
       Attributes.add("simulationType", "");
       for (i = 0; i < imax; i++)
         {
           CModelValue * pMV = mpModel->getModelValues()[i];
           Attributes.setValue(0, pMV->getKey());
           Attributes.setValue(1, pMV->getObjectName());
           CModelEntity::Status SimulationType = pMV->getStatus();
           Attributes.setValue(2, CModelEntity::XMLStatus[SimulationType]);
           startSaveElement("ModelValue", Attributes);
           saveAnnotation(pMV);
           if (SimulationType != CModelEntity::FIXED &&
               pMV->getExpression() != "")
             {
               startSaveElement("Expression");
               saveData(pMV->getExpression());
               endSaveElement("Expression");
             }
           if (pMV->getInitialExpression() != "")
             {
               startSaveElement("InitialExpression");
               saveData(pMV->getInitialExpression());
               endSaveElement("InitialExpression");
             }
           endSaveElement("ModelValue");
           if (pMV->getSBMLId() != "")
             mSBMLReference[pMV->getSBMLId()] = pMV->getKey();
         }
       endSaveElement("ListOfModelValues");
     }
   // Reactions
   if ((imax = mpModel->getReactions().size()) > 0)
     {
       startSaveElement("ListOfReactions");
       CXMLAttributeList Attr;
       const CCopasiVector< CChemEqElement > * pReactantList;
       size_t j, jmax;
       std::vector< const CCopasiObject * > ObjectList;
       size_t k, kmax;
       Attributes.erase();
       Attributes.add("key", "");
       Attributes.add("name", "");
       Attributes.add("reversible", "");
       Attributes.add("fast", "");
       for (i = 0; i < imax; i++)
         {
           CReaction * pReaction = mpModel->getReactions()[i];
           Attributes.setValue(0, pReaction->getKey());
           Attributes.setValue(1, pReaction->getObjectName());
           Attributes.setValue(2, pReaction->isReversible() ? "true" : "false");
           Attributes.setValue(3, pReaction->isFast() ? "true" : "false");
           if (pReaction->getSBMLId() != "")
             mSBMLReference[pReaction->getSBMLId()] = pReaction->getKey();
           startSaveElement("Reaction", Attributes);
           saveAnnotation(pReaction);
           Attr.erase();
           Attr.add("metabolite", "");
           Attr.add("stoichiometry", "");
           pReactantList = & pReaction->getChemEq().getSubstrates();
           if ((jmax = pReactantList->size()) > 0)
             {
               startSaveElement("ListOfSubstrates");
               for (j = 0; j < jmax; j++)
                 {
                   Attr.setValue(0, (*pReactantList)[j]->getMetaboliteKey());
                   Attr.setValue(1, (*pReactantList)[j]->getMultiplicity());
                   saveElement("Substrate", Attr);
                 }
               endSaveElement("ListOfSubstrates");
             }
           //startSaveElement("ListOfProducts"); // this seems to belong further down
           pReactantList = & pReaction->getChemEq().getProducts();
           if ((jmax = pReactantList->size()) > 0)
             {
               startSaveElement("ListOfProducts"); //this seems to belong here
               for (j = 0; j < jmax; j++)
                 {
                   Attr.setValue(0, (*pReactantList)[j]->getMetaboliteKey());
                   Attr.setValue(1, (*pReactantList)[j]->getMultiplicity());
                   saveElement("Product", Attr);
                 }
               endSaveElement("ListOfProducts");
             }
           pReactantList = & pReaction->getChemEq().getModifiers();
           if ((jmax = pReactantList->size()) > 0)
             {
               startSaveElement("ListOfModifiers");
               for (j = 0, jmax = pReactantList->size(); j < jmax; j++)
                 {
                   Attr.setValue(0, (*pReactantList)[j]->getMetaboliteKey());
                   Attr.setValue(1, (*pReactantList)[j]->getMultiplicity());
                   saveElement("Modifier", Attr);
                 }
               endSaveElement("ListOfModifiers");
             }
           const CCopasiParameterGroup * pParamList;
           pParamList = & pReaction->getParameters();
           if ((jmax = pParamList->size()) > 0)
             {
               startSaveElement("ListOfConstants");
               Attr.erase();
               Attr.add("key", "");
               Attr.add("name", "");
               Attr.add("value", "");
               for (j = 0; j < jmax; j++)
                 {
                   Attr.setValue(0, pParamList->getKey(j));
                   Attr.setValue(1, pParamList->getName(j));
                   Attr.setValue(2, * pParamList->getValue(j).pDOUBLE);
                   saveElement("Constant", Attr);
                 }
               endSaveElement("ListOfConstants");
             }
           if (pReaction->getFunction() != CCopasiRootContainer::getUndefinedFunction())
             {
               Attr.erase();
               Attr.add("function", pReaction->getFunction()->getKey());
               startSaveElement("KineticLaw", Attr);
               if ((jmax = pReaction->getFunctionParameters().size()))
                 {
                   startSaveElement("ListOfCallParameters");
                   const std::vector< std::vector<std::string> > & rMap =
                     pReaction->getParameterMappings();
                   for (j = 0; j < jmax; j++)
                     {
                       Attr.erase();
                       Attr.add("functionParameter",
                                pReaction->
                                getFunction()->getVariables()[j]->getKey());
                       startSaveElement("CallParameter", Attr);
                       Attr.erase();
                       Attr.add("reference", "");
                       for (k = 0, kmax = rMap[j].size(); k < kmax; k++)
{
                           Attr.setValue(0, rMap[j][k]);
                           saveElement("SourceParameter", Attr);
                         }
                       endSaveElement("CallParameter");
                     }
                   endSaveElement("ListOfCallParameters");
                 }
               endSaveElement("KineticLaw");
             }
           endSaveElement("Reaction");
         }
       endSaveElement("ListOfReactions");
     }
   // Events (added 07.04.08)
   if ((imax = mpModel->getEvents().size()) > 0)
     {
       startSaveElement("ListOfEvents");
       Attributes.erase();
       Attributes.add("key", "");
       Attributes.add("name", "");
       Attributes.add("delayAssignment", "");
       Attributes.add("fireAtInitialTime", "");
       Attributes.add("persistentTrigger", "");
       for (i = 0; i < imax; i++)
         {
           CEvent * pEvent = mpModel->getEvents()[i];
           Attributes.setValue(0, pEvent->getKey());
           Attributes.setValue(1, pEvent->getObjectName());
           if (pEvent->getDelayExpression() != "")
             {
               Attributes.setValue(2, pEvent->getDelayAssignment() ? "true" : "false");
             }
           else
             {
               Attributes.skip(2);
             }
           Attributes.setValue(3, pEvent->getFireAtInitialTime());
           Attributes.setValue(4, pEvent->getPersistentTrigger());
           startSaveElement("Event", Attributes);
           saveAnnotation(pEvent);
           if (pEvent->getTriggerExpression() != "")
             {
               startSaveElement("TriggerExpression");
               saveData(pEvent->getTriggerExpression());
               endSaveElement("TriggerExpression");
             }
           if (pEvent->getDelayExpression() != "")
             {
               startSaveElement("DelayExpression");
               saveData(pEvent->getDelayExpression());
               endSaveElement("DelayExpression");
             }
           const CCopasiVectorN< CEventAssignment > & Assignments = pEvent->getAssignments();
           if (Assignments.size() > 0)
             {
               startSaveElement("ListOfAssignments");
               CXMLAttributeList Attr;
               Attr.add("targetKey", "");
               CCopasiVectorN< CEventAssignment >::const_iterator it = Assignments.begin();
               CCopasiVectorN< CEventAssignment >::const_iterator end = Assignments.end();
               for (; it != end; ++it)
                 {
                   Attr.setValue(0, (*it)->getTargetKey());
                   startSaveElement("Assignment", Attr);
                   startSaveElement("Expression");
                   saveData((*it)->getExpression());
                   endSaveElement("Expression");
                   endSaveElement("Assignment");
                 }
               endSaveElement("ListOfAssignments");
             }
           endSaveElement("Event");
           if (pEvent->getSBMLId() != "")
             mSBMLReference[pEvent->getSBMLId()] = pEvent->getKey();
         }
       endSaveElement("ListOfEvents");
     }
   // Save the model parameter sets
   Attributes.erase();
   const CModelParameterSet * pSet = & mpModel->getModelParameterSet();
   Attributes.add("activeSet", pSet->getKey());
   startSaveElement("ListOfModelParameterSets", Attributes);
   Attributes.erase();
   Attributes.add("key", "");
   Attributes.add("name", "");
   pSet = & mpModel->getModelParameterSet();
   Attributes.setValue(0, pSet->getKey());
   Attributes.setValue(1, pSet->getObjectName());
   startSaveElement("ModelParameterSet", Attributes);
   saveAnnotation(pSet);
   CModelParameterGroup::const_iterator itSet = pSet->begin();
   CModelParameterGroup::const_iterator endSet = pSet->end();
   for (; itSet != endSet; ++itSet)
     {
       saveModelParameter(*itSet);
     }
   endSaveElement("ModelParameterSet");
   imax = mpModel->getModelParameterSets().size();
   for (i = 0; i < imax; i++)
     {
       pSet = mpModel->getModelParameterSets()[i];
       Attributes.setValue(0, pSet->getKey());
       Attributes.setValue(1, pSet->getObjectName());
       startSaveElement("ModelParameterSet", Attributes);
       saveAnnotation(pSet);
       itSet = pSet->begin();
       endSet = pSet->end();
       for (; itSet != endSet; ++itSet)
         {
           saveModelParameter(*itSet);
         }
       endSaveElement("ModelParameterSet");
     }
   endSaveElement("ListOfModelParameterSets");
   // The State an state Template is only save for backwards compatibility
   startSaveElement("StateTemplate");
   Attributes.erase();
   // This is now optional.
   // Attributes.add("key", "");
   Attributes.add("objectReference", "");
   std::pair< std::string, std::string > Variable;
   CModelEntity *const* ppEntity = mpModel->getStateTemplate().getEntities();
   CModelEntity *const* ppEntityEnd = ppEntity + mpModel->getStateTemplate().size();
   for (; ppEntity != ppEntityEnd; ++ppEntity)
     {
       Attributes.setValue(0, (*ppEntity)->getKey());
       saveElement("StateTemplateVariable", Attributes);
     }
   endSaveElement("StateTemplate");
   Attributes.erase();
   Attributes.add("type", "initialState");
   startSaveElement("InitialState", Attributes);
   *mpOstream << mIndent;
   ppEntity = mpModel->getStateTemplate().getEntities();
   for (; ppEntity != ppEntityEnd; ++ppEntity)
     {
       *mpOstream << (DBL)(*ppEntity)->getInitialValue() << " ";
     }
   *mpOstream << std::endl;
   endSaveElement("InitialState");
   endSaveElement("Model");
   return success;
 }
bool CCopasiXML::saveModelParameter (const CModelParameter * pModelParameter) private
Save a model parameter
Parameters
const CModelParameter * pModelParameter
Returns
bool success
Definition at line 963 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CModelParameter::getCN(), CModelParameter::getCompareResult(), CModelParameter::getInitialExpression(), CModelParameter::getSimulationType(), CModelParameter::getType(), CModelParameter::getValue(), CModelParameter::Group, CModelParameter::Missing, CModelParameter::ParticleNumbers, CModelParameter::Reaction, CCopasiXMLInterface::saveData(), CCopasiXMLInterface::saveElement(), CCopasiXMLInterface::startSaveElement(), CModelParameter::TypeNames, and CModelEntity::XMLStatus.
Referenced by saveModel().
 {
   // We do not save model parameters which are marked missing to preserve
   // their missing state.
   if (pModelParameter->getCompareResult() == CModelParameter::Missing)
     {
       return true;
     }
   bool success = true;
   CXMLAttributeList Attributes;
   if (pModelParameter->getType() != CModelParameter::Reaction &&
       pModelParameter->getType() != CModelParameter::Group)
     {
       Attributes.add("cn", pModelParameter->getCN());
       Attributes.add("value", pModelParameter->getValue(CModelParameter::ParticleNumbers));
       Attributes.add("type", CModelParameter::TypeNames[pModelParameter->getType()]);
       Attributes.add("simulationType", CModelEntity::XMLStatus[pModelParameter->getSimulationType()]);
       if (pModelParameter->getInitialExpression() != "")
         {
           startSaveElement("ModelParameter", Attributes);
           startSaveElement("InitialExpression");
           saveData(pModelParameter->getInitialExpression());
           endSaveElement("InitialExpression");
           endSaveElement("ModelParameter");
         }
       else
         {
           saveElement("ModelParameter", Attributes);
         }
     }
   else
     {
       Attributes.add("cn", pModelParameter->getCN());
       Attributes.add("type", CModelParameter::TypeNames[pModelParameter->getType()]);
       startSaveElement("ModelParameterGroup", Attributes);
       CModelParameterGroup::const_iterator it = static_cast< const CModelParameterGroup * >(pModelParameter)->begin();
       CModelParameterGroup::const_iterator end = static_cast< const CModelParameterGroup * >(pModelParameter)->end();
       for (; it != end; ++it)
         {
           success &= saveModelParameter(*it);
         }
       endSaveElement("ModelParameterGroup");
     }
   return success;
 }
bool CCopasiXML::savePlotList () private
Save the list of plots.
Returns
bool success
Definition at line 1106 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CPlotItem::getChannels(), CPlotSpecification::getItems(), CPlotItem::getNumChannels(), CCopasiObject::getObjectName(), CPlotItem::getType(), havePlotList(), CPlotSpecification::isActive(), CPlotDataChannelSpec::max, CPlotDataChannelSpec::maxAutoscale, CPlotDataChannelSpec::min, CPlotDataChannelSpec::minAutoscale, mpPlotList, CCopasiXMLInterface::saveElement(), CCopasiXMLInterface::saveParameterGroup(), CCopasiVector< T >::size(), CCopasiXMLInterface::startSaveElement(), and CPlotItem::XMLType.
Referenced by save().
 {
   //std::cerr << "Saving plot list. " << std::endl;
   bool success = true;
   if (!havePlotList())
     {
       //std::cerr << "No plot list defined." << std::endl;
       return success;
     }
   size_t i, imax = mpPlotList->size();
   //std::cerr << "Saving " << imax << " plots." << std::endl;
   if (!imax) return success;
   CXMLAttributeList Attributes;
   startSaveElement("ListOfPlots");
   for (i = 0; i < imax; i++)
     {
       const CPlotSpecification* pPlot = (*mpPlotList)[i];
       Attributes.erase();
       Attributes.add("name", pPlot->getObjectName());
       Attributes.add("type", CPlotSpecification::XMLType[pPlot->getType()]);
       Attributes.add("active", pPlot->isActive());
       startSaveElement("PlotSpecification", Attributes);
       saveParameterGroup(* pPlot->CCopasiParameter::getValue().pGROUP);
       startSaveElement("ListOfPlotItems");
       size_t j, jmax = pPlot->getItems().size();
       //std::cerr << "Saving " << jmax << "PlotItems." << std::endl;
       for (j = 0; j < jmax; j++)
         {
           const CPlotItem* pPlotItem = pPlot->getItems()[j];
           Attributes.erase();
           Attributes.add("name", pPlotItem->getObjectName());
           Attributes.add("type", CPlotItem::XMLType[pPlotItem->getType()]);
           startSaveElement("PlotItem", Attributes);
           saveParameterGroup(* pPlotItem->CCopasiParameter::getValue().pGROUP);
           startSaveElement("ListOfChannels");
           size_t k, kmax = pPlotItem->getNumChannels();
           //std::cerr << "Saving " << kmax << " Channels." << std::endl;
           for (k = 0; k < kmax; k++)
             {
               const CPlotDataChannelSpec pDataChannelSpec = pPlotItem->getChannels()[k];
               Attributes.erase();
               Attributes.add("cn", pDataChannelSpec);
               if (!pDataChannelSpec.minAutoscale)
                 {
                   Attributes.add("min", pDataChannelSpec.min);
                 }
               if (!pDataChannelSpec.maxAutoscale)
                 {
                   Attributes.add("max", pDataChannelSpec.max);
                 }
               saveElement("ChannelSpec", Attributes);
             }
           endSaveElement("ListOfChannels");
           endSaveElement("PlotItem");
         }
       endSaveElement("ListOfPlotItems");
       endSaveElement("PlotSpecification");
     }
   endSaveElement("ListOfPlots");
   return success;
 }
void CCopasiXML::savePolygonElement (const CLPolygon & polygon) private
saves a single image element.
Definition at line 2690 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), CLPolygon::getListOfElements(), save2DAttributes(), saveCurveElements(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveTransformation2D().
 {
   CXMLAttributeList attributes;
   // first we add the attributes for a 2D object
   save2DAttributes(polygon, attributes);
   startSaveElement("Polygon", attributes);
   saveCurveElements(*polygon.getListOfElements());
   endSaveElement("Polygon");
 }
void CCopasiXML::savePosition (const CLPoint & p, const std::string & tag = "Position") private
Definition at line 1364 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CXMLAttributeList::erase(), CLPoint::getX(), CLPoint::getY(), and CCopasiXMLInterface::saveElement().
Referenced by saveBoundingBox(), and saveCurve().
 {
   CXMLAttributeList Attributes;
   Attributes.erase();
   Attributes.add("x", p.getX());
   Attributes.add("y", p.getY());
   saveElement(tag, Attributes);
 }
void CCopasiXML::saveRadialGradient (const CLRadialGradient & gradient) private
Saves a single radial gradient definition.
Definition at line 2145 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CLRadialGradient::getCenterX(), CLRadialGradient::getCenterY(), CLRadialGradient::getCenterZ(), CLRadialGradient::getFocalPointX(), CLRadialGradient::getFocalPointY(), CLRadialGradient::getFocalPointZ(), CLRadialGradient::getRadius(), saveGradientAttributes(), saveGradientElements(), CCopasiXMLInterface::startSaveElement(), and CLRelAbsVector::toString().
Referenced by saveRenderInformationDefinitionElements().
 {
   CXMLAttributeList attributes;
   // first we create the common attributes
   saveGradientAttributes(gradient, attributes);
   // now we add the attributes specific to the radial gradient
   attributes.add("cx", gradient.getCenterX().toString());
   attributes.add("cy", gradient.getCenterY().toString());
   attributes.add("cz", gradient.getCenterZ().toString());
   attributes.add("r", gradient.getRadius().toString());
   attributes.add("fx", gradient.getFocalPointX().toString());
   attributes.add("fy", gradient.getFocalPointY().toString());
   attributes.add("fz", gradient.getFocalPointZ().toString());
   startSaveElement("RadialGradient", attributes);
   // save the gradient stops
   saveGradientElements(gradient);
   endSaveElement("RadialGradient");
 }
void CCopasiXML::saveRectangleElement (const CLRectangle & rectangle) private
saves a single rectangle element.
Definition at line 2603 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLRectangle::getHeight(), CLRectangle::getRadiusX(), CLRectangle::getRadiusY(), CLRectangle::getWidth(), CLRectangle::getX(), CLRectangle::getY(), CLRectangle::getZ(), save2DAttributes(), CCopasiXMLInterface::saveElement(), and CLRelAbsVector::toString().
Referenced by saveTransformation2D().
 {
   CXMLAttributeList attributes;
   // first we add the attributes for a 2D object
   save2DAttributes(rectangle, attributes);
   // now we add the rectangle specific attributes
   attributes.add("x", rectangle.getX().toString());
   attributes.add("y", rectangle.getY().toString());
   if (rectangle.getZ() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("z", rectangle.getZ().toString());
     }
   attributes.add("width", rectangle.getWidth().toString());
   attributes.add("height", rectangle.getHeight().toString());
   if (rectangle.getRadiusX() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("rx", rectangle.getRadiusX().toString());
     }
   if (rectangle.getRadiusY() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("ry", rectangle.getRadiusY().toString());
     }
   saveElement("Rectangle", attributes);
 }
void CCopasiXML::saveRenderCurveElement (const CLRenderCurve & curve) private
saves a single image element.
Definition at line 2703 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), save1DAttributes(), saveCurveElements(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveTransformation2D().
 {
   CXMLAttributeList attributes;
   // first we add the attributes for a 1D object
   save1DAttributes(curve, attributes);
   // next we add the arrow head attributes
   saveArrowHeadAttributes<CLRenderCurve>(curve, attributes);
   startSaveElement("Curve", attributes);
   saveCurveElements(*curve.getListOfCurveElements());
   endSaveElement("Curve");
 }
void CCopasiXML::saveRenderInformationAttributes (const CLRenderInformationBase & renderInfo, CXMLAttributeList & attributes) private
Saves the attributes that render information objects have in common.
Definition at line 2010 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLRenderInformationBase::getBackgroundColor(), CLRenderInformationBase::getKey(), CLRenderInformationBase::getName(), and CLRenderInformationBase::getReferenceRenderInformationKey().
Referenced by saveGlobalRenderInformation(), and saveLocalRenderInformation().
 {
   // save the key
   attributes.add("key", renderInfo.getKey());
   // save the name
   std::string s = renderInfo.getName();
   const char* ws = " \t\n\r";
   if (s.find_first_not_of(ws) != std::string::npos)
     {
       attributes.add("name", s);
     }
   // save the background color
   s = renderInfo.getBackgroundColor();
   if (s.find_first_not_of(ws) != std::string::npos)
     {
       // save the name
       attributes.add("backgroundColor", s);
     }
   // save the reference render information key
   s = renderInfo.getReferenceRenderInformationKey();
   if (s.find_first_not_of(ws) != std::string::npos)
     {
       // save the name
       attributes.add("referenceRenderInformation", s);
     }
 }
void CCopasiXML::saveRenderInformationDefinitionElements (const CLRenderInformationBase & renderInfo) private
Saves color definitions, gradient definitions and line endings.
Saves color definitions , gradient definitions and line endings.
Definition at line 2045 of file CCopasiXML.cpp.
References CCopasiXMLInterface::endSaveElement(), CLRenderInformationBase::getColorDefinition(), CLRenderInformationBase::getGradientDefinition(), CLRenderInformationBase::getLineEnding(), CLRenderInformationBase::getNumColorDefinitions(), CLRenderInformationBase::getNumGradientDefinitions(), CLRenderInformationBase::getNumLineEndings(), saveColorDefinition(), saveLinearGradient(), saveLineEnding(), saveRadialGradient(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveGlobalRenderInformation(), and saveLocalRenderInformation().
 {
   size_t i, iMax = renderInfo.getNumColorDefinitions();
   if (iMax > 0)
     {
       startSaveElement("ListOfColorDefinitions");
       for (i = 0; i < iMax; ++i)
         {
           saveColorDefinition(*(renderInfo.getColorDefinition(i)));
         }
       endSaveElement("ListOfColorDefinitions");
     }
   iMax = renderInfo.getNumGradientDefinitions();
   if (iMax > 0)
     {
       startSaveElement("ListOfGradientDefinitions");
       const CLGradientBase* pGradient = NULL;
       for (i = 0; i < iMax; ++i)
         {
           pGradient = renderInfo.getGradientDefinition(i);
           if (dynamic_cast<const CLRadialGradient*>(pGradient))
             {
               saveRadialGradient(*static_cast<const CLRadialGradient*>(pGradient));
             }
           else if (dynamic_cast<const CLLinearGradient*>(pGradient))
             {
               saveLinearGradient(*static_cast<const CLLinearGradient*>(pGradient));
             }
         }
       endSaveElement("ListOfGradientDefinitions");
     }
   iMax = renderInfo.getNumLineEndings();
   if (iMax > 0)
     {
       startSaveElement("ListOfLineEndings");
       for (i = 0; i < iMax; ++i)
         {
           saveLineEnding(*(renderInfo.getLineEnding(i)));
         }
       endSaveElement("ListOfLineEndings");
     }
 }
void CCopasiXML::saveRenderPoint (const CLRenderPoint & point) private
saves a single render point element.
Definition at line 2734 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLRenderCubicBezier::basePoint1_X(), CLRenderCubicBezier::basePoint1_Y(), CLRenderCubicBezier::basePoint1_Z(), CLRenderCubicBezier::basePoint2_X(), CLRenderCubicBezier::basePoint2_Y(), CLRenderCubicBezier::basePoint2_Z(), CCopasiXMLInterface::saveElement(), CLRelAbsVector::toString(), CLRenderPoint::x(), CLRenderPoint::y(), and CLRenderPoint::z().
Referenced by saveCurveElements().
 {
   CXMLAttributeList attributes;
   attributes.add("x", point.x().toString());
   attributes.add("y", point.y().toString());
   if (point.z() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("z", point.z().toString());
     }
   const CLRenderCubicBezier* pCB = dynamic_cast<const CLRenderCubicBezier*>(&point);
   if (pCB != NULL)
     {
       attributes.add("basePoint1_x", pCB->basePoint1_X().toString());
       attributes.add("basePoint1_y", pCB->basePoint1_Y().toString());
       if (pCB->basePoint1_Z() != CLRelAbsVector(0.0, 0.0))
         {
           attributes.add("basePoint1_z", pCB->basePoint1_Z().toString());
         }
       attributes.add("basePoint2_x", pCB->basePoint2_X().toString());
       attributes.add("basePoint2_y", pCB->basePoint2_Y().toString());
       if (pCB->basePoint2_Z() != CLRelAbsVector(0.0, 0.0))
         {
           attributes.add("basePoint2_z", pCB->basePoint2_Z().toString());
         }
     }
   saveElement("Element", attributes);
 }
void CCopasiXML::saveRenderTextElement (const CLText & text) private
saves a single text element.
Definition at line 2666 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CLText::getX(), CLText::getY(), CLText::getZ(), save1DAttributes(), CCopasiXMLInterface::saveData(), CCopasiXMLInterface::startSaveElement(), and CLRelAbsVector::toString().
Referenced by saveTransformation2D().
 {
   CXMLAttributeList attributes;
   // first we add the attributes for a 1D object
   save1DAttributes(text, attributes);
   // save text attributes
   attributes.add("x", text.getX().toString());
   attributes.add("y", text.getY().toString());
   if (text.getZ() != CLRelAbsVector(0.0, 0.0))
     {
       attributes.add("z", text.getZ().toString());
     }
   // next we add the text specific attributes
   saveTextAttributes<CLText>(text, attributes);
   startSaveElement("Text", attributes);
   saveData(text.getText());
   endSaveElement("Text");
 }
bool CCopasiXML::saveReportList () private
Save the list of reports.
Returns
bool success
Definition at line 1297 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CReportDefinition::getBodyAddr(), CReportDefinition::getComment(), CReportDefinition::getFooterAddr(), CReportDefinition::getHeaderAddr(), CReportDefinition::getKey(), CCopasiObject::getObjectName(), CReportDefinition::getPrecision(), CReportDefinition::getSeparator(), CCopasiStaticString::getStaticString(), CReportDefinition::getTableAddr(), CReportDefinition::getTaskType(), CReportDefinition::getTitle(), haveReportList(), CReportDefinition::isTable(), mpReportList, CCopasiXMLInterface::saveElement(), saveReportSection(), CCopasiXMLInterface::saveXhtml(), CXMLAttributeList::setValue(), CCopasiVector< T >::size(), CCopasiXMLInterface::startSaveElement(), and CCopasiTask::XMLType.
Referenced by save().
 {
   bool success = true;
   if (!haveReportList()) return success;
   size_t i, imax = mpReportList->size();
   if (!imax) return success;
   CXMLAttributeList Attributes;
   CReportDefinition * pReport = NULL;
   startSaveElement("ListOfReports");
   for (i = 0; i < imax; i++)
     {
       pReport = (*mpReportList)[i];
       Attributes.erase();
       Attributes.add("key", pReport->getKey());
       Attributes.add("name", pReport->getObjectName());
       Attributes.add("taskType", CCopasiTask::XMLType[pReport->getTaskType()]);
       Attributes.add("separator", pReport->getSeparator().getStaticString());
       Attributes.add("precision", pReport->getPrecision());
       startSaveElement("Report", Attributes);
       startSaveElement("Comment");
       saveXhtml(pReport->getComment());
       endSaveElement("Comment");
       if (pReport->isTable())
         {
           Attributes.erase();
           Attributes.add("printTitle", pReport->getTitle());
           startSaveElement("Table", Attributes);
           const std::vector <CRegisteredObjectName> & Table = * pReport->getTableAddr();
           size_t j, jmax = Table.size();
           Attributes.erase();
           Attributes.add("cn", "");
           for (j = 0; j < jmax; j++)
             {
               Attributes.setValue(0, Table[j]);
               saveElement("Object", Attributes);
             }
           endSaveElement("Table");
         }
       else
         {
           saveReportSection("Header", * pReport->getHeaderAddr());
           saveReportSection("Body", * pReport->getBodyAddr());
           saveReportSection("Footer", * pReport->getFooterAddr());
         }
       endSaveElement("Report");
     }
   endSaveElement("ListOfReports");
   return success;
 }
bool CCopasiXML::saveReportSection (const std::string & name, const std::vector< CRegisteredObjectName > & section) private
Save a Report Section such as Header, Body or Footer.
Parameters
const std::string & name
const std::vector <CCopasiObjectName> & section
Returns
bool success
Definition at line 1259 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CCopasiXMLInterface::saveData(), CCopasiXMLInterface::saveElement(), CXMLAttributeList::set(), and CCopasiXMLInterface::startSaveElement().
Referenced by saveReportList().
 {
   CXMLAttributeList Attributes;
   Attributes.add("NoName", "");
   size_t j, jmax = section.size();
   if (jmax)
     {
       startSaveElement(name);
       for (j = 0; j < jmax; j++)
         {
           if (section[j].getObjectType() == "html")
             {
               //Write in Text
               startSaveElement("html");
               Attributes.set(0, "xmlns", "http://www.w3.org/1999/xhtml");
               startSaveElement("body", Attributes);
               saveData(section[j].getObjectName()); //TODO check
               endSaveElement("body");
               endSaveElement("html");
             }
           else
             {
               //Write in Object
               Attributes.set(0, "cn", section[j]);
               saveElement("Object", Attributes);
             }
         }
       endSaveElement(name);
     }
   return true;
 }
bool CCopasiXML::saveSBMLReference () private
Save the SBML reference information
Returns
bool success
Definition at line 1831 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CDirEntry::fileName(), CCopasiDataModel::getSBMLFileName(), CDirEntry::isRelativePath(), CDirEntry::makePathRelative(), mpDataModel, CCopasiXMLInterface::mPWD, mSBMLReference, CCopasiXMLInterface::saveElement(), CXMLAttributeList::setValue(), and CCopasiXMLInterface::startSaveElement().
Referenced by save().
 {
   // if there is no model, there are no SBML references to save,
   // so no reason to fail saving at this point
   if (!this->mpDataModel) return true;
   if (this->mpDataModel->getSBMLFileName() == "" ||
       mSBMLReference.size() == 0)
     return true;
   CXMLAttributeList Attributes;
   std::string SBMLFile = this->mpDataModel->getSBMLFileName();
   if (!CDirEntry::isRelativePath(SBMLFile) &&
       !CDirEntry::makePathRelative(SBMLFile, mPWD))
     SBMLFile = CDirEntry::fileName(SBMLFile);
   Attributes.add("file", SBMLFile);
   startSaveElement("SBMLReference", Attributes);
   Attributes.erase();
   Attributes.add("SBMLid", "");
   Attributes.add("COPASIkey", "");
   std::map<std::string, std::string>::const_iterator it = mSBMLReference.begin();
   std::map<std::string, std::string>::const_iterator end = mSBMLReference.end();
   for (; it != end; ++it)
     {
       Attributes.setValue(0, it->first);
       Attributes.setValue(1, it->second);
       saveElement("SBMLMap", Attributes);
     }
   endSaveElement("SBMLReference");
   return true;
 }
void CCopasiXML::saveStyleAttributes (const CLStyle & style, CXMLAttributeList & attributes) private
Adds the attributes common to both style types.
Definition at line 2266 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLStyle::createStringFromSet(), CLStyle::getKey(), CLStyle::getNumRoles(), CLStyle::getNumTypes(), CLStyle::getRoleList(), and CLStyle::getTypeList().
Referenced by saveGlobalStyle(), and saveLocalStyle().
 {
   attributes.add("key", style.getKey());
   if (style.getNumRoles() > 0)
     {
       attributes.add("roleList", CLStyle::createStringFromSet(style.getRoleList()));
     }
   if (style.getNumTypes() > 0)
     {
       attributes.add("typeList", CLStyle::createStringFromSet(style.getTypeList()));
     }
 }
void CCopasiXML::saveStyleElements (const CLStyle & style) private
Saves the elements common to both style types.
Definition at line 2284 of file CCopasiXML.cpp.
References CLStyle::getGroup(), and saveGroupElement().
Referenced by saveGlobalStyle(), and saveLocalStyle().
 {
   assert(style.getGroup() != NULL);
   saveGroupElement(*(style.getGroup()));
 }
bool CCopasiXML::saveTaskList () private
Save the list of tasks.
Returns
bool success
Definition at line 1184 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CReport::append(), CReport::confirmOverwrite(), CCopasiXMLInterface::endSaveElement(), CXMLAttributeList::erase(), CDirEntry::fileName(), CReportDefinition::getKey(), CCopasiTask::getKey(), CCopasiTask::getMethod(), CCopasiObject::getObjectName(), CCopasiTask::getProblem(), CCopasiTask::getReport(), CReport::getReportDefinition(), CCopasiMethod::getSubType(), CReport::getTarget(), CCopasiTask::getType(), haveTaskList(), CDirEntry::isRelativePath(), CCopasiTask::isScheduled(), CCopasiTask::isUpdateModel(), CDirEntry::makePathRelative(), mpTaskList, CCopasiXMLInterface::mPWD, pTask, CCopasiXMLInterface::saveElement(), CCopasiXMLInterface::saveParameterGroup(), CCopasiVector< T >::size(), CCopasiXMLInterface::startSaveElement(), CCopasiMethod::XMLSubType, and CCopasiTask::XMLType.
Referenced by save().
 {
   bool success = true;
   if (!haveTaskList()) return success;
   size_t i, imax = mpTaskList->size();
   if (!imax) return success;
   CXMLAttributeList Attributes;
   CCopasiTask * pTask = NULL;
   startSaveElement("ListOfTasks");
   for (i = 0; i < imax; i++)
     {
       pTask = (*mpTaskList)[i];
       Attributes.erase();
       Attributes.add("key", pTask->getKey());
       Attributes.add("name", pTask->getObjectName());
       Attributes.add("type", CCopasiTask::XMLType[pTask->getType()]);
       Attributes.add("scheduled", pTask->isScheduled() ? "true" : "false");
       Attributes.add("updateModel", pTask->isUpdateModel() ? "true" : "false");
       startSaveElement("Task", Attributes);
       // Report Element
       CReport & tReport = pTask->getReport();
       if (tReport.getReportDefinition())
         {
           Attributes.erase();
           Attributes.add("reference", tReport.getReportDefinition()->getKey());
           std::string Target = tReport.getTarget();
           if (!CDirEntry::isRelativePath(Target) &&
               !CDirEntry::makePathRelative(Target, mPWD))
             Target = CDirEntry::fileName(Target);
           Attributes.add("target", Target);
           Attributes.add("append", tReport.append());
           Attributes.add("confirmOverwrite", tReport.confirmOverwrite());
           saveElement("Report", Attributes);
         }
       //Problem Element
       CCopasiProblem *tProblem = pTask->getProblem();
       Attributes.erase();
       startSaveElement("Problem");
       saveParameterGroup(* tProblem->CCopasiParameter::getValue().pGROUP);
       endSaveElement("Problem");
       // Method Element
       CCopasiMethod *tMethod = pTask->getMethod();
       Attributes.erase();
       Attributes.add("name", tMethod->CCopasiParameter::getObjectName());
       Attributes.add("type", CCopasiMethod::XMLSubType[tMethod->getSubType()]);
       startSaveElement("Method", Attributes);
       saveParameterGroup(* tMethod->CCopasiParameter::getValue().pGROUP);
       endSaveElement("Method");
       endSaveElement("Task");
     }
   endSaveElement("ListOfTasks");
   return success;
 }
template<typename TEXTELEMENT > void CCopasiXML::saveTextAttributes (const TEXTELEMENT & text, CXMLAttributeList & attributes) private
Saves the attributes for a text element. We make this a template so that we can use it for a group as well as a text element.
Definition at line 2413 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_START, CLText::ANCHOR_TOP, CLText::STYLE_ITALIC, and CLText::WEIGHT_BOLD.
 {
   // text size
   if (text.isSetFontSize())
     {
       attributes.add("font-size", text.getFontSize().toString());
     }
   // font family
   if (text.isSetFontFamily())
     {
       attributes.add("font-family", text.getFontFamily());
     }
   // font weight
   if (text.isSetFontWeight())
     {
       switch (text.getFontWeight())
         {
           case CLText::WEIGHT_BOLD:
             attributes.add("font-weight", "bold");
             break;
           default:
             break;
         }
     }
   // font style
   if (text.isSetFontStyle())
     {
       switch (text.getFontStyle())
         {
           case CLText::STYLE_ITALIC:
             attributes.add("font-style", "italic");
             break;
           default:
             break;
         }
     }
   // text anchor
   if (text.isSetTextAnchor())
     {
       switch (text.getTextAnchor())
         {
           case CLText::ANCHOR_MIDDLE:
             attributes.add("text-anchor", "middle");
             break;
           case CLText::ANCHOR_END:
             attributes.add("text-anchor", "end");
             break;
           case CLText::ANCHOR_START:
             attributes.add("text-anchor", "start");
             break;
           default:
             break;
         }
     }
   // vertical text anchor
   if (text.isSetVTextAnchor())
     {
       switch (text.getVTextAnchor())
         {
           case CLText::ANCHOR_MIDDLE:
             attributes.add("vtext-anchor", "middle");
             break;
           case CLText::ANCHOR_BOTTOM:
             attributes.add("vtext-anchor", "bottom");
             break;
           case CLText::ANCHOR_TOP:
             attributes.add("vtext-anchor", "top");
             break;
           default:
             break;
         }
     }
 }
void CCopasiXML::saveTransformation2D (const CLTransformation2D & transformation) private
Saves a class that is subclasses from Transformation2D. This covers images, curves, rectangles, ellipses, polygons, text elements and groups.
Definition at line 2524 of file CCopasiXML.cpp.
References saveEllipseElement(), saveGroupElement(), saveImageElement(), savePolygonElement(), saveRectangleElement(), saveRenderCurveElement(), and saveRenderTextElement().
Referenced by saveGroupElement().
 {
   if (dynamic_cast<const CLGraphicalPrimitive1D*>(&transformation))
     {
       if (dynamic_cast<const CLRenderCurve*>(&transformation))
         {
           saveRenderCurveElement(static_cast<const CLRenderCurve&>(transformation));
         }
       else if (dynamic_cast<const CLGraphicalPrimitive2D*>(&transformation))
         {
           if (dynamic_cast<const CLRectangle*>(&transformation))
             {
               saveRectangleElement(static_cast<const CLRectangle&>(transformation));
             }
           else if (dynamic_cast<const CLEllipse*>(&transformation))
             {
               saveEllipseElement(static_cast<const CLEllipse&>(transformation));
             }
           else if (dynamic_cast<const CLPolygon*>(&transformation))
             {
               savePolygonElement(static_cast<const CLPolygon&>(transformation));
             }
           else if (dynamic_cast<const CLGroup*>(&transformation))
             {
               saveGroupElement(static_cast<const CLGroup&>(transformation));
             }
           else
             {
               // we should never end up here.
               assert(false);
             }
         }
       else if (dynamic_cast<const CLText*>(&transformation))
         {
           saveRenderTextElement(static_cast<const CLText&>(transformation));
         }
       else
         {
           // we should never end up here.
           assert(false);
         }
     }
   else if (dynamic_cast<const CLImage*>(&transformation))
     {
       saveImageElement(static_cast<const CLImage&>(transformation));
     }
   else
     {
       // we should never end up here.
       assert(false);
     }
 }
void CCopasiXML::saveTransformationAttributes (const CLTransformation2D & transformation, CXMLAttributeList & attributes) private
Saves the attributes for a transformation.
Definition at line 2316 of file CCopasiXML.cpp.
References CXMLAttributeList::add(), CLTransformation2D::get2DTransformationString(), CLTransformation::get3DTransformationString(), CLTransformation::is2DTransformation(), CLTransformation::isIdentityMatrix(), and CLTransformation::isSetMatrix().
Referenced by save1DAttributes(), and saveImageElement().
 {
   // transformation
   if (!transformation.isIdentityMatrix())
     {
       // check if it is a 2D or a 3D transformation
       if (transformation.is2DTransformation())
         {
           if (transformation.isSetMatrix())
             {
               attributes.add("transform", transformation.get2DTransformationString());
             }
         }
       else
         {
           if (transformation.isSetMatrix())
             {
               attributes.add("transform", transformation.get3DTransformationString());
             }
         }
     }
 }
bool CCopasiXML::setDatamodel (CCopasiDataModel * pDataModel)
Set the datamodel.
Parameters
CCopasiDataModel* pDataModel
Returns
bool success
Definition at line 299 of file CCopasiXML.cpp.
References mpDataModel.
Referenced by CCopasiDataModel::loadModel(), save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   this->mpDataModel = pDataModel;
   return true;
 }
bool CCopasiXML::setFunctionList (CCopasiVectorN< CFunction > * pFunctionList)
Set the function list.
Parameters
CopasiVectorN< CFunction > * pFunctionList
Returns
bool success
Definition at line 270 of file CCopasiXML.cpp.
References mpFunctionList.
Referenced by buildFunctionList(), CFunctionDB::load(), CCopasiDataModel::loadModel(), and CFunctionDB::save().
 {
   mpFunctionList = pFunctionList;
   return true;
 }
bool CCopasiXML::setGUI (SCopasiXMLGUI * pGUI)
Set the GUI.
Parameters
SCopasiXMLGUI *pGUI
Returns
bool success
Definition at line 359 of file CCopasiXML.cpp.
References mpGUI.
Referenced by CCopasiDataModel::loadModel(), save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   mpGUI = pGUI;
   return true;
 }
bool CCopasiXML::setLayoutList (const CListOfLayouts & reportList)
Set the layout list.
Parameters
const CListOfLayouts & reportList
Returns
bool success
Definition at line 377 of file CCopasiXML.cpp.
References mpLayoutList.
Referenced by save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   mpLayoutList = const_cast<CListOfLayouts *>(&layoutList);
   return true;
 }
bool CCopasiXML::setModel (CModel * pModel)
Set the model.
Parameters
CModel * pModel
Returns
bool success
Definition at line 254 of file CCopasiXML.cpp.
References mpModel.
Referenced by save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   mpModel = pModel;
   return true;
 }
bool CCopasiXML::setPlotList (COutputDefinitionVector * pPlotList)
Set the plot list.
Parameters
COutputDefinitionVector * pPlotList
Returns
bool success
Definition at line 319 of file CCopasiXML.cpp.
References mpPlotList.
Referenced by save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   mpPlotList = pPlotList;
   return true;
 }
bool CCopasiXML::setReportList (CReportDefinitionVector * pReportList)
Set the report list.
Parameters
CReportDefinitionVector *pReportList
Returns
bool success
Definition at line 339 of file CCopasiXML.cpp.
References mpReportList.
Referenced by save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   mpReportList = pReportList;
   return true;
 }
bool CCopasiXML::setTaskList (CCopasiVectorN< CCopasiTask > * pTaskList)
Set the task list.
Parameters
CCopasiVectorN< CCopasiTask > *pTaskList
Returns
bool success
Definition at line 288 of file CCopasiXML.cpp.
References mpTaskList.
Referenced by save_cps_model_to_stream(), and CCopasiDataModel::saveModel().
 {
   mpTaskList = pTaskList;
   return true;
 }
Member Data Documentation
bool CCopasiXML::mMCXML21Issued private
Remember if we already issued MCXML21
Definition at line 604 of file CCopasiXML.h.
Referenced by saveLayoutList().
CCopasiDataModel* CCopasiXML::mpDataModel private
Pointer to the datamodel
Definition at line 599 of file CCopasiXML.h.
Referenced by buildFunctionList(), load(), saveSBMLReference(), and setDatamodel().
CCopasiVectorN< CFunction >* CCopasiXML::mpFunctionList private
Pointer to a vector of functions which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 559 of file CCopasiXML.h.
Referenced by freeFunctionList(), getFunctionList(), haveFunctionList(), load(), saveFunctionList(), and setFunctionList().
SCopasiXMLGUI* CCopasiXML::mpGUI private
Pointer to a GUI related information, which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 583 of file CCopasiXML.h.
Referenced by freeGUI(), getGUI(), haveGUI(), load(), saveGUI(), and setGUI().
CListOfLayouts* CCopasiXML::mpLayoutList private
Pointer to a vector of plots which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 589 of file CCopasiXML.h.
Referenced by freeLayoutList(), getLayoutList(), haveLayoutList(), load(), saveLayoutList(), and setLayoutList().
CModel* CCopasiXML::mpModel private
Pointer to a model which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 553 of file CCopasiXML.h.
Referenced by freeModel(), getModel(), haveModel(), load(), saveModel(), and setModel().
COutputDefinitionVector* CCopasiXML::mpPlotList private
Pointer to a vector of plots which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 577 of file CCopasiXML.h.
Referenced by freePlotList(), getPlotList(), havePlotList(), load(), savePlotList(), and setPlotList().
CReportDefinitionVector* CCopasiXML::mpReportList private
Pointer to a vector of reports which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 571 of file CCopasiXML.h.
Referenced by freeReportList(), getReportList(), haveReportList(), load(), saveReportList(), and setReportList().
CCopasiVectorN< CCopasiTask >* CCopasiXML::mpTaskList private
Pointer to a vector of tasks which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 565 of file CCopasiXML.h.
Referenced by fixBuild55(), fixBuild81(), freeTaskList(), getTaskList(), haveTaskList(), load(), saveTaskList(), and setTaskList().
std::map< std::string, std::string > CCopasiXML::mSBMLReference private
SBML Reference
Definition at line 594 of file CCopasiXML.h.
Referenced by saveFunctionList(), saveModel(), and saveSBMLReference().
The documentation for this class was generated from the following files:
CCopasiXML.h
CCopasiXML.cpp