COPASI API: CQAutolayoutWizard Class Reference
CQAutolayoutWizard Class Reference
#include <CQAutolayoutWizard.h>
Public Member Functions
CQAutolayoutWizard (const CModel &model, QWidget *parent=0, Qt::WindowFlags flags=0)
const std::set< const
CCompartment * > & getSelectedCompartments () const
const std::set< const CMetab * > & getSelectedMetabolites () const
const std::set< const
CReaction * > & getSelectedReactions () const
const std::set< const CMetab * > & getSideMetabolites () const
virtual int nextId () const
~CQAutolayoutWizard ()
Protected Types
enum PageOrder {
NO_PAGE = -1, SELECTION_PAGE_ID = 1, NO_SELECTION_ERROR_PAGE_ID = 2, SIDE_COMPOUND_PAGE_ID = 3,
LAYOUT_PARAMETER_PAGE_ID = 4
}
Protected Slots
void slotCurrentIdChanged (int id)
Protected Member Functions
QWizardPage * createErrorPage ()
QWizardPage * createLayoutParameterPage ()
QWizardPage * createSelectionPage ()
QWizardPage * createSideCompoundPage ()
virtual void done (int result)
Protected Attributes
std::set< const CCompartment * > mCompartments
PageOrder mLastPageId
const CModel & mModel
std::set< const CReaction * > mReactions
std::set< const CMetab * > mSideSpecies
std::set< const CMetab * > mSpecies
Detailed Description
Definition at line 213 of file CQAutolayoutWizard.h.
Member Enumeration Documentation
enum CQAutolayoutWizard::PageOrder protected
Enumerator
NO_PAGE
SELECTION_PAGE_ID
NO_SELECTION_ERROR_PAGE_ID
SIDE_COMPOUND_PAGE_ID
LAYOUT_PARAMETER_PAGE_ID
Definition at line 218 of file CQAutolayoutWizard.h.
   {
     NO_PAGE = -1,
     SELECTION_PAGE_ID = 1,
     NO_SELECTION_ERROR_PAGE_ID = 2,
     SIDE_COMPOUND_PAGE_ID = 3,
     LAYOUT_PARAMETER_PAGE_ID = 4
   };
Constructor & Destructor Documentation
CQAutolayoutWizard::CQAutolayoutWizard (const CModel & model, QWidget * parent = 0, Qt::WindowFlags flags = 0)
Constructor needs a const reference to a COPASI model and a layout object that is filled by the wizard.
Constructor needs a const reference to a COPASI model.
Definition at line 890 of file CQAutolayoutWizard.cpp.
References createErrorPage(), createSelectionPage(), createSideCompoundPage(), NO_SELECTION_ERROR_PAGE_ID, SELECTION_PAGE_ID, SIDE_COMPOUND_PAGE_ID, and slotCurrentIdChanged().
                                                                                                  :
   QWizard(parent, flags)
   , mModel(model)
   , mLastPageId(CQAutolayoutWizard::NO_PAGE)
 {
   this->setOptions(this->options() | QWizard::HaveFinishButtonOnEarlyPages);
   this->setOptions(this->options() & ~QWizard::NoCancelButton);
   this->setWindowTitle(tr("Autolayout Wizard"));
   this->setPage(SELECTION_PAGE_ID, this->createSelectionPage());
   this->setPage(NO_SELECTION_ERROR_PAGE_ID, this->createErrorPage());
   this->setPage(SIDE_COMPOUND_PAGE_ID, this->createSideCompoundPage());
   //this->setPage(LAYOUT_PARAMETER_PAGE_ID,this->createLayoutParameterPage());
   connect(this, SIGNAL(currentIdChanged(int)), this, SLOT(slotCurrentIdChanged(int)));
 }
CQAutolayoutWizard::~CQAutolayoutWizard ()
Definition at line 906 of file CQAutolayoutWizard.cpp.
 {
   // do nothing
 }
Member Function Documentation
QWizardPage * CQAutolayoutWizard::createErrorPage () protected
Definition at line 936 of file CQAutolayoutWizard.cpp.
Referenced by CQAutolayoutWizard().
 {
   return new CQNoSelectionErrorWizardPage;
 }
QWizardPage * CQAutolayoutWizard::createLayoutParameterPage () protected
Definition at line 929 of file CQAutolayoutWizard.cpp.
 {
   return new CQLayoutParametersWizardPage;
 }
QWizardPage * CQAutolayoutWizard::createSelectionPage () protected
Definition at line 913 of file CQAutolayoutWizard.cpp.
References mModel.
Referenced by CQAutolayoutWizard().
 {
   return new CQSelectionWizardPage(this->mModel);
 }
QWizardPage * CQAutolayoutWizard::createSideCompoundPage () protected
Definition at line 921 of file CQAutolayoutWizard.cpp.
Referenced by CQAutolayoutWizard().
 {
   return new CQSideCompoundWizardPage;
 }
void CQAutolayoutWizard::done (int result) protected virtual
Definition at line 941 of file CQAutolayoutWizard.cpp.
References LAYOUT_PARAMETER_PAGE_ID, mCompartments, mReactions, mSideSpecies, mSpecies, SELECTION_PAGE_ID, and SIDE_COMPOUND_PAGE_ID.
 {
   // depending on the result, I have to update
   // the selections
   if (result == QDialog::Accepted)
     {
       // right now, the dialog can only be ended on the second page,
       // so in theory we only have to update the side compounds
       // But I would like to change the wizard so that the user is
       // not forced to go through all pages and that he can close the
       // wizard at each step
       if (this->currentId() == CQAutolayoutWizard::SELECTION_PAGE_ID)
         {
           static_cast<CQSelectionWizardPage*>(this->currentPage())->fillContainers(this->mCompartments, this->mReactions, this->mSpecies);
         }
       else if (this->currentId() == CQAutolayoutWizard::SIDE_COMPOUND_PAGE_ID)
         {
           static_cast<CQSideCompoundWizardPage*>(this->currentPage())->getSideCompounds(this->mSideSpecies);
         }
       else if (this->currentId() == CQAutolayoutWizard::LAYOUT_PARAMETER_PAGE_ID)
         {
           // do nothing right now
         }
       // make sure that the side species container does not contain
       // any species that is not in the species container
       std::set<const CMetab*>::iterator it = this->mSideSpecies.begin(), endit = this->mSideSpecies.end(), speciesEnd = this->mSpecies.end();
       while (it != endit)
         {
           if (this->mSpecies.find(*it) == speciesEnd)
             {
               // remove the item from the side species
               // this is not very efficient, but should be ok since this code
               // is probably not critical
               this->mSideSpecies.erase(*it);
               // back to start
               it = this->mSideSpecies.begin();
               endit = this->mSideSpecies.end();
               continue;
             }
           ++it;
         }
     }
   else
     {
       this->mCompartments.clear();
       this->mReactions.clear();
       this->mSpecies.clear();
       this->mSideSpecies.clear();
     }
   this->QWizard::done(result);
 }
const std::set<const CCompartment*>& CQAutolayoutWizard::getSelectedCompartments () const inline
Definition at line 260 of file CQAutolayoutWizard.h.
References mCompartments.
Referenced by CQLayoutsWidget::slotBtnNewClicked().
   {
     return this->mCompartments;
   }
const std::set<const CMetab*>& CQAutolayoutWizard::getSelectedMetabolites () const inline
Definition at line 270 of file CQAutolayoutWizard.h.
References mSpecies.
Referenced by CQLayoutsWidget::slotBtnNewClicked().
   {
     return this->mSpecies;
   }
const std::set<const CReaction*>& CQAutolayoutWizard::getSelectedReactions () const inline
Definition at line 265 of file CQAutolayoutWizard.h.
References mReactions.
Referenced by CQLayoutsWidget::slotBtnNewClicked().
   {
     return this->mReactions;
   }
const std::set<const CMetab*>& CQAutolayoutWizard::getSideMetabolites () const inline
Definition at line 275 of file CQAutolayoutWizard.h.
References mSideSpecies.
Referenced by CQLayoutsWidget::slotBtnNewClicked().
   {
     return this->mSideSpecies;
   }
int CQAutolayoutWizard::nextId () const virtual
Definition at line 1023 of file CQAutolayoutWizard.cpp.
References LAYOUT_PARAMETER_PAGE_ID, mCompartments, mReactions, mSpecies, NO_PAGE, NO_SELECTION_ERROR_PAGE_ID, SELECTION_PAGE_ID, and SIDE_COMPOUND_PAGE_ID.
 {
   PageOrder nextPage = NO_PAGE;
   switch (this->currentId())
     {
       case SELECTION_PAGE_ID:
         static_cast<CQSelectionWizardPage*>(this->currentPage())->fillContainers(this->mCompartments, this->mReactions, this->mSpecies);
         if (this->mCompartments.empty() && this->mSpecies.empty())
           {
             nextPage = NO_SELECTION_ERROR_PAGE_ID;
           }
         else
           {
             nextPage = SIDE_COMPOUND_PAGE_ID;
           }
         break;
       case NO_SELECTION_ERROR_PAGE_ID:
         break;
       case SIDE_COMPOUND_PAGE_ID:
         //nextPage=LAYOUT_PARAMETER_PAGE_ID;
         break;
       case LAYOUT_PARAMETER_PAGE_ID:
         break;
     }
   return nextPage;
 }
void CQAutolayoutWizard::slotCurrentIdChanged (int id) protected slot
Definition at line 997 of file CQAutolayoutWizard.cpp.
References mLastPageId, mSideSpecies, mSpecies, SELECTION_PAGE_ID, and SIDE_COMPOUND_PAGE_ID.
Referenced by CQAutolayoutWizard().
 {
   // if the last id was the id of the selection widget, we
   // have to store the selection data
   if (this->mLastPageId == CQAutolayoutWizard::SELECTION_PAGE_ID)
     {
       // this is now done in the nextId method
       //static_cast<CQSelectionWizardPage*>(this->page(CQAutolayoutWizard::SELECTION_PAGE_ID))->fillContainers(this->mCompartments,this->mReactions,this->mSpecies);
     }
   // if the last id is that of the side compound page,
   // we have to save the side compounds
   else if (this->mLastPageId == CQAutolayoutWizard::SIDE_COMPOUND_PAGE_ID)
     {
       static_cast<CQSideCompoundWizardPage*>(this->page(CQAutolayoutWizard::SIDE_COMPOUND_PAGE_ID))->getSideCompounds(this->mSideSpecies);
     }
   // if we are in the side compound page,
   // we have to update the species
   if (id == CQAutolayoutWizard::SIDE_COMPOUND_PAGE_ID)
     {
       static_cast<CQSideCompoundWizardPage*>(this->page(CQAutolayoutWizard::SIDE_COMPOUND_PAGE_ID))->setSpeciesList(this->mSpecies);
     }
   this->mLastPageId = (PageOrder)id;
 }
Member Data Documentation
std::set<const CCompartment*> CQAutolayoutWizard::mCompartments mutable protected
Definition at line 239 of file CQAutolayoutWizard.h.
Referenced by done(), getSelectedCompartments(), and nextId().
PageOrder CQAutolayoutWizard::mLastPageId protected
Definition at line 245 of file CQAutolayoutWizard.h.
Referenced by slotCurrentIdChanged().
const CModel& CQAutolayoutWizard::mModel protected
Definition at line 227 of file CQAutolayoutWizard.h.
Referenced by createSelectionPage().
std::set<const CReaction*> CQAutolayoutWizard::mReactions mutable protected
Definition at line 242 of file CQAutolayoutWizard.h.
Referenced by done(), getSelectedReactions(), and nextId().
std::set<const CMetab*> CQAutolayoutWizard::mSideSpecies mutable protected
Definition at line 236 of file CQAutolayoutWizard.h.
Referenced by done(), getSideMetabolites(), and slotCurrentIdChanged().
std::set<const CMetab*> CQAutolayoutWizard::mSpecies mutable protected
Definition at line 231 of file CQAutolayoutWizard.h.
Referenced by done(), getSelectedMetabolites(), nextId(), and slotCurrentIdChanged().
The documentation for this class was generated from the following files:
CQAutolayoutWizard.h
CQAutolayoutWizard.cpp