COPASI API: COptProblem Class Reference
COptProblem Class Reference
#include <COptProblem.h>
Public Member Functions
COptItem & addOptItem (const CCopasiObjectName &objectCN)
virtual bool calculate ()
virtual bool calculateStatistics (const C_FLOAT64 &factor=1.0e-003, const C_FLOAT64 &resolution=1.0e-009)
virtual bool checkFunctionalConstraints ()
virtual bool checkParametricConstraints ()
COptProblem (const CCopasiTask::Type &type=CCopasiTask::optimization, const CCopasiContainer *pParent=NULL)
COptProblem (const COptProblem &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
const bool & getCalculateStatistics () const
const C_FLOAT64 & getCalculateValue () const
const std::vector
< UpdateMethod * > & getCalculateVariableUpdateMethods () const
const std::vector< COptItem * > & getConstraintList () const
const C_FLOAT64 & getExecutionTime () const
const unsigned C_INT32 & getFunctionEvaluations () const
const std::string getObjectiveFunction ()
COptItem & getOptItem (const size_t &index)
const std::vector< COptItem * > & getOptItemList () const
size_t getOptItemSize () const
const bool & getRandomizeStartValues () const
const C_FLOAT64 & getSolutionValue () const
const CVector< C_FLOAT64 > & getSolutionVariables () const
CCopasiTask::Type getSubtaskType () const
const CVector< C_FLOAT64 > & getVariableGradients () const
size_t getVariableSize () const
void incrementEvaluations (unsigned C_INT32 increment)
virtual bool initialize ()
virtual bool initializeSubtaskBeforeOutput ()
const bool & maximize () const
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
void randomizeStartValues ()
void rememberStartValues ()
bool removeOptItem (const size_t &index)
void reset ()
void resetEvaluations ()
virtual bool restore (const bool &updateModel)
void restoreModel (const bool &updateModel)
void setCalculateStatistics (const bool &calculate)
virtual bool setCallBack (CProcessReport *pCallBack)
void setMaximize (const bool &maximize)
virtual bool setModel (CModel *pModel)
bool setObjectiveFunction (const std::string &infix)
void setRandomizeStartValues (const bool &randomize)
virtual bool setSolution (const C_FLOAT64 &value, const CVector< C_FLOAT64 > &variables)
bool setSubtaskType (const CCopasiTask::Type &subtaskType)
bool swapOptItem (const size_t &iFrom, const size_t &iTo)
virtual ~COptProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const unsigned int ValidSubtasks []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Attributes
C_FLOAT64 mCalculateValue
unsigned C_INT32 mConstraintCounter
unsigned C_INT32 mCounter
CCopasiTimer mCPUTime
unsigned C_INT32 mFailedConstraintCounter
unsigned C_INT32 mFailedCounter
CVector< C_FLOAT64 > mGradient
bool mHaveStatistics
size_t mhCounter
size_t mhSolutionValue
std::vector< Refresh * > mInitialRefreshMethods
CVector< C_FLOAT64 > mOriginalVariables
std::vector< COptItem * > * mpConstraintItems
CCopasiParameterGroup * mpGrpConstraints
CCopasiParameterGroup * mpGrpItems
CExpression * mpObjectiveExpression
std::vector< COptItem * > * mpOptItems
bool * mpParmCalculateStatistics
bool * mpParmMaximize
std::string * mpParmObjectiveExpression
bool * mpParmRandomizeStartValues
std::string * mpParmSubtaskCN
CCopasiTask * mpSubtask
std::vector< Refresh * > mRefreshConstraints
std::vector< Refresh * > mRefreshMethods
C_FLOAT64 mSolutionValue
CVector< C_FLOAT64 > mSolutionVariables
bool mStoreResults
std::vector< UpdateMethod * > mUpdateMethods
C_FLOAT64 mWorstValue
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void initializeParameter ()
void initObjects ()
Friends
std::ostream & operator<< (std::ostream &os, const COptProblem &o)
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 49 of file COptProblem.h.
Constructor & Destructor Documentation
COptProblem::COptProblem (const CCopasiTask::Type & type = CCopasiTask::optimization, const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiTask::Type & type (default: optimization)
const CCopasiContainer * pParent (default: NULL)
Definition at line 67 of file COptProblem.cpp.
References initializeParameter(), and initObjects().
                                                           :
   CCopasiProblem(type, pParent),
   mWorstValue(0.0),
   mpParmSubtaskCN(NULL),
   mpParmObjectiveExpression(NULL),
   mpParmMaximize(NULL),
   mpParmRandomizeStartValues(NULL),
   mpParmCalculateStatistics(NULL),
   mpGrpItems(NULL),
   mpGrpConstraints(NULL),
   mpOptItems(NULL),
   mpConstraintItems(NULL),
   mpSubtask(NULL),
   mpObjectiveExpression(NULL),
   mUpdateMethods(),
   mInitialRefreshMethods(),
   mRefreshMethods(),
   mRefreshConstraints(),
   mCalculateValue(0),
   mSolutionVariables(),
   mOriginalVariables(),
   mSolutionValue(0),
   mCounter(0),
   mFailedCounter(0),
   mConstraintCounter(0),
   mFailedConstraintCounter(0),
   mCPUTime(CCopasiTimer::PROCESS, this),
   mhSolutionValue(C_INVALID_INDEX),
   mhCounter(C_INVALID_INDEX),
   mStoreResults(false),
   mHaveStatistics(false),
   mGradient(0)
 {
   initializeParameter();
   initObjects();
 }
COptProblem::COptProblem (const COptProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const COptProblem & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 106 of file COptProblem.cpp.
References initializeParameter(), and initObjects().
                                                           :
   CCopasiProblem(src, pParent),
   mWorstValue(src.mWorstValue),
   mpParmSubtaskCN(NULL),
   mpParmObjectiveExpression(NULL),
   mpParmMaximize(NULL),
   mpParmRandomizeStartValues(NULL),
   mpParmCalculateStatistics(NULL),
   mpGrpItems(NULL),
   mpGrpConstraints(NULL),
   mpOptItems(NULL),
   mpConstraintItems(NULL),
   mpSubtask(NULL),
   mpObjectiveExpression(NULL),
   mUpdateMethods(),
   mInitialRefreshMethods(),
   mRefreshMethods(),
   mRefreshConstraints(),
   mCalculateValue(src.mCalculateValue),
   mSolutionVariables(src.mSolutionVariables),
   mOriginalVariables(src.mOriginalVariables),
   mSolutionValue(src.mSolutionValue),
   mCounter(0),
   mFailedCounter(0),
   mConstraintCounter(0),
   mFailedConstraintCounter(0),
   mCPUTime(CCopasiTimer::PROCESS, this),
   mhSolutionValue(C_INVALID_INDEX),
   mhCounter(C_INVALID_INDEX),
   mStoreResults(src.mStoreResults),
   mHaveStatistics(src.mHaveStatistics),
   mGradient(src.mGradient)
 {
   initializeParameter();
   initObjects();
 }
COptProblem::~COptProblem () virtual
Destructor
Definition at line 145 of file COptProblem.cpp.
 {}
Member Function Documentation
COptItem & COptProblem::addOptItem (const CCopasiObjectName & objectCN)
Add an optimization item to the problem.
Parameters
const CCopasiObjectName & objectCN
Returns
COptItem optItemAdded
Definition at line 708 of file COptProblem.cpp.
References CCopasiParameterGroup::addParameter(), CCopasiObject::getObjectDataModel(), mpGrpItems, and COptItem::setObjectCN().
 {
   CCopasiDataModel* pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   COptItem * pItem = new COptItem(pDataModel);
   pItem->setObjectCN(objectCN);
   mpGrpItems->addParameter(pItem);
   return *pItem;
 }
bool COptProblem::calculate (void) virtual
Do the calculating based on CalculateVariables and fill CalculateResults with the results.
Returns
bool continue
calculate() decides whether the problem is a steady state problem or a trajectory problem based on whether the pointer to that type of problem is null or not. It then calls the process() method for that type of problem. Currently process takes ofstream& as a parameter but it will change so that process() takes no parameters.
Reimplemented in CFitProblem, and CRealProblem.
Definition at line 538 of file COptProblem.cpp.
References CExpression::calcValue(), CCopasiMessage::getLastMessage(), CCopasiTask::getProblem(), CCopasiTask::getType(), CCopasiTask::initialize(), mCalculateValue, mCounter, mFailedCounter, mhCounter, mInitialRefreshMethods, CCopasiProblem::mpCallBack, mpObjectiveExpression, mpParmMaximize, mpSubtask, mRefreshMethods, mStoreResults, CCopasiTask::NO_OUTPUT, CCopasiTask::ONLY_TIME_SERIES, pdelete, CCopasiTask::process(), CProcessReport::progressItem(), and CCopasiTask::timeCourse.
Referenced by calculateStatistics(), COptMethodEP::evaluate(), COptMethodStatistics::evaluate(), COptMethodSteepestDescent::evaluate(), CRandomSearch::evaluate(), COptMethodDE::evaluate(), COptMethodSRES::evaluate(), COptMethodPS::evaluate(), COptMethodGA::evaluate(), COptMethodHookeJeeves::evaluate(), COptMethodGASR::evaluate(), COptMethodLevenbergMarquardt::evaluate(), COptMethodNelderMead::evaluate(), COptMethodCoranaWalk::evaluate(), COptMethodSA::evaluate(), COptMethodSS::evaluate(), COptMethodPraxis::evaluate(), COptMethodTruncatedNewton::evaluate(), COptMethodEP2::optimise(), and setCalculateStatistics().
 {
   mCounter++;
   bool success = false;
   COutputHandler * pOutputHandler = NULL;
   if (mpSubtask == NULL)
     return false;
   if (mStoreResults &&
       mpSubtask->getType() == CCopasiTask::timeCourse)
     {
       static_cast< CTrajectoryProblem * >(mpSubtask->getProblem())->setTimeSeriesRequested(true);
       pOutputHandler = new COutputHandler();
       mpSubtask->initialize(CCopasiTask::ONLY_TIME_SERIES, pOutputHandler, NULL);
     }
   try
     {
       // Update all initial values which depend on the optimization items.
       std::vector< Refresh * >::const_iterator it = mInitialRefreshMethods.begin();
       std::vector< Refresh * >::const_iterator end = mInitialRefreshMethods.end();
       for (; it != end; ++it)
         (**it)();
       success = mpSubtask->process(true);
       // Refresh all values needed to calculate the objective function.
       it = mRefreshMethods.begin();
       end = mRefreshMethods.end();
       for (; it != end; ++it)
         (**it)();
       mCalculateValue = *mpParmMaximize ? -mpObjectiveExpression->calcValue() : mpObjectiveExpression->calcValue();
     }
   catch (CCopasiException & /*Exception*/)
     {
       // We do not want to clog the message cue.
       CCopasiMessage::getLastMessage();
       success = false;
     }
   catch (...)
     {
       success = false;
     }
   if (mStoreResults &&
       mpSubtask->getType() == CCopasiTask::timeCourse)
     {
       mStoreResults = false;
       mpSubtask->initialize(CCopasiTask::NO_OUTPUT, NULL, NULL);
       pdelete(pOutputHandler);
     }
   if (!success || isnan(mCalculateValue))
     {
       mFailedCounter++;
       mCalculateValue = std::numeric_limits< C_FLOAT64 >::infinity();
     }
   if (mpCallBack) return mpCallBack->progressItem(mhCounter);
   return true;
 }
bool COptProblem::calculateStatistics (const C_FLOAT64 & factor = 1.0e-003, const C_FLOAT64 & resolution = 1.0e-009) virtual
Calculate the statistics for the problem
Parameters
const C_FLOAT64 & factor (Default: 1.0e-003)
const C_FLOAT64 & resolution (Default: 1.0e-009)
Reimplemented in CFitProblem.
Definition at line 609 of file COptProblem.cpp.
References C_FLOAT64, calculate(), CCopasiObject::getRefresh(), mCalculateValue, mCPUTime, mGradient, mHaveStatistics, mpParmCalculateStatistics, mpParmMaximize, mSolutionValue, mSolutionVariables, mStoreResults, mUpdateMethods, mWorstValue, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by COptTask::process().
 {
   // Set the current values to the solution values.
   size_t i, imax = mSolutionVariables.size();
   mGradient.resize(imax);
   mGradient = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   // Recalculate the best solution.
   for (i = 0; i < imax; i++)
     (*mUpdateMethods[i])(mSolutionVariables[i]);
   // This is necessary so that the result can be displayed.
   mStoreResults = true;
   calculate();
   mStoreResults = false;
   // Make sure the timer is accurate.
   mCPUTime.getRefresh();
   if (mSolutionValue == mWorstValue)
     return false;
   if (*mpParmCalculateStatistics)
     {
       mHaveStatistics = true;
       C_FLOAT64 Current;
       C_FLOAT64 Delta;
       // Calculate the gradient
       for (i = 0; i < imax; i++)
         {
           Current = mSolutionVariables[i];
           if (fabs(Current) > resolution)
             {
               (*mUpdateMethods[i])(Current * (1.0 + factor));
               Delta = 1.0 / (Current * factor);
             }
           else
             {
               (*mUpdateMethods[i])(resolution);
               Delta = 1.0 / resolution;
             }
           calculate();
           mGradient[i] = ((*mpParmMaximize ? -mCalculateValue : mCalculateValue) - mSolutionValue) * Delta;
           // Restore the value
           (*mUpdateMethods[i])(Current);
         }
       calculate();
       // Make sure the timer is accurate.
       (*mCPUTime.getRefresh())();
     }
   return true;
 }
bool COptProblem::checkFunctionalConstraints () virtual
Check whether all functional constraints are fulfilled.
Returns
bool fulfilled
Reimplemented in CFitProblem.
Definition at line 507 of file COptProblem.cpp.
References mConstraintCounter, mFailedConstraintCounter, mpConstraintItems, and mRefreshConstraints.
Referenced by COptMethodEP::evaluate(), COptMethodStatistics::evaluate(), COptMethodSteepestDescent::evaluate(), CRandomSearch::evaluate(), COptMethodDE::evaluate(), COptMethodPS::evaluate(), COptMethodGA::evaluate(), COptMethodHookeJeeves::evaluate(), COptMethodSA::evaluate(), COptMethodNelderMead::evaluate(), COptMethodCoranaWalk::evaluate(), COptMethodLevenbergMarquardt::evaluate(), COptMethodSS::evaluate(), COptMethodPraxis::evaluate(), COptMethodTruncatedNewton::evaluate(), COptMethodSA::optimise(), and COptMethodCoranaWalk::optimise().
 {
   // Make sure the constraint values are up to date.
   std::vector< Refresh *>::const_iterator itRefresh = mRefreshConstraints.begin();
   std::vector< Refresh *>::const_iterator endRefresh = mRefreshConstraints.end();
   for (; itRefresh != endRefresh; ++itRefresh)
     (**itRefresh)();
   std::vector< COptItem * >::const_iterator it = mpConstraintItems->begin();
   std::vector< COptItem * >::const_iterator end = mpConstraintItems->end();
   mConstraintCounter++;
   for (; it != end; ++it)
     if ((*it)->checkConstraint())
       {
         mFailedConstraintCounter++;
         return false;
       }
   return true;
 }
bool COptProblem::checkParametricConstraints () virtual
Check whether all parameters are within their boundaries.
Returns
bool within
Definition at line 496 of file COptProblem.cpp.
References mpOptItems.
Referenced by COptMethodSteepestDescent::evaluate(), COptMethodHookeJeeves::evaluate(), COptMethodNelderMead::evaluate(), COptMethodLevenbergMarquardt::evaluate(), COptMethodPraxis::evaluate(), COptMethodTruncatedNewton::evaluate(), COptMethodSA::optimise(), and COptMethodCoranaWalk::optimise().
 {
   std::vector< COptItem * >::const_iterator it = mpOptItems->begin();
   std::vector< COptItem * >::const_iterator end = mpOptItems->end();
   for (; it != end; ++it)
     if ((*it)->checkConstraint()) return false;
   return true;
 }
bool COptProblem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Reimplemented in CFitProblem.
Definition at line 167 of file COptProblem.cpp.
References C_INVALID_INDEX, CCopasiRootContainer::getFunctionList(), CCopasiVectorN< CType >::getIndex(), CEvaluationTree::getInfix(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), CFunctionDB::loadedFunctions(), mpConstraintItems, mpGrpConstraints, mpGrpItems, mpOptItems, mpParmObjectiveExpression, mpParmSubtaskCN, CCopasiParameter::Value::pSTRING, CCopasiParameterGroup::removeParameter(), setObjectiveFunction(), setSubtaskType(), CCopasiTask::steadyState, and CCopasiTask::timeCourse.
Referenced by CFitProblem::elevateChildren(), and initializeParameter().
 {
   // We need to handle the old file format which had two different task keys
   if (mpParmSubtaskCN != NULL)
     {
       CCopasiParameter * pParameter;
       if ((pParameter = getParameter("Steady-State")) != NULL)
         {
           if (*pParameter->getValue().pSTRING != "")
             {
               setSubtaskType(CCopasiTask::steadyState);
             }
           removeParameter("Steady-State");
         }
       if ((pParameter = getParameter("Time-Course")) != NULL)
         {
           if (*pParameter->getValue().pSTRING != "")
             {
               setSubtaskType(CCopasiTask::timeCourse);
             }
           removeParameter("Time-Course");
         }
       // If no subtask is defined we default to steady-state
       if (*mpParmSubtaskCN == "")
         setSubtaskType(CCopasiTask::steadyState);
     }
   // Handle old file format in which the objective expression was stored in the function DB
   if (mpParmObjectiveExpression != NULL)
     {
       CCopasiParameter * pParameter = getParameter("ObjectiveFunction");
       CExpression * pObjectiveFunction = NULL;
       // We do not use the key to find the objective function because keys are not re-mapped
       // for unknown parameters, instead we rely on the uniqueness of the name and the fact that
       // this is the only expression in the list.
       size_t Index = CCopasiRootContainer::getFunctionList()->loadedFunctions().getIndex("Objective Function");
       if (Index != C_INVALID_INDEX)
         {
           pObjectiveFunction =
             dynamic_cast<CExpression *>(CCopasiRootContainer::getFunctionList()->loadedFunctions()[Index]);
         }
       if (pObjectiveFunction != NULL &&
           pParameter != NULL)
         {
           *mpParmObjectiveExpression = pObjectiveFunction->getInfix();
           removeParameter("ObjectiveFunction");
         }
       setObjectiveFunction(*mpParmObjectiveExpression);
     }
   mpGrpItems =
     elevate<CCopasiParameterGroup, CCopasiParameterGroup>(mpGrpItems);
   if (!mpGrpItems) return false;
   std::vector<CCopasiParameter *> * pValue =
     mpGrpItems->CCopasiParameter::getValue().pGROUP;
   index_iterator it = pValue->begin();
   index_iterator end = pValue->end();
   for (; it != end; ++it)
     if (!elevate<COptItem, CCopasiParameterGroup>(*it)) return false;
   mpOptItems =
     static_cast<std::vector<COptItem * > * >(mpGrpItems->CCopasiParameter::getValue().pVOID);
   mpGrpConstraints =
     elevate<CCopasiParameterGroup, CCopasiParameterGroup>(mpGrpConstraints);
   if (!mpGrpConstraints) return false;
   pValue = mpGrpConstraints->CCopasiParameter::getValue().pGROUP;
   it = pValue->begin();
   end = pValue->end();
   for (; it != end; ++it)
     if (!elevate<COptItem, CCopasiParameterGroup>(*it)) return false;
   mpConstraintItems =
     static_cast<std::vector<COptItem * > * >(mpGrpConstraints->CCopasiParameter::getValue().pVOID);
   return true;
 }
const bool & COptProblem::getCalculateStatistics () const
Retrieve whether we have to calculate statistics
Returns
const bool & maximize
Definition at line 838 of file COptProblem.cpp.
References mpParmCalculateStatistics.
Referenced by CQFittingResult::enterProtected(), CQFittingWidget::loadTask(), CQOptimizationWidget::loadTask(), CQFittingWidget::saveTask(), and CQOptimizationWidget::saveTask().
 {return *mpParmCalculateStatistics;}
const C_FLOAT64 & COptProblem::getCalculateValue () const
Retrieve the result of a calculation
Definition at line 673 of file COptProblem.cpp.
References mCalculateValue.
Referenced by COptMethodEP::evaluate(), COptMethodStatistics::evaluate(), COptMethodSteepestDescent::evaluate(), CRandomSearch::evaluate(), COptMethodDE::evaluate(), COptMethodSRES::evaluate(), COptMethodPS::evaluate(), COptMethodGA::evaluate(), COptMethodHookeJeeves::evaluate(), COptMethodSA::evaluate(), COptMethodNelderMead::evaluate(), COptMethodCoranaWalk::evaluate(), COptMethodGASR::evaluate(), COptMethodLevenbergMarquardt::evaluate(), COptMethodSS::evaluate(), COptMethodPraxis::evaluate(), and COptMethodTruncatedNewton::evaluate().
 {return mCalculateValue;}
const std::vector< UpdateMethod * > & COptProblem::getCalculateVariableUpdateMethods () const
Retrieve the update methods for the variables for calculation.
Returns
const std::vector< UpdateMethod * > & updateMethods
Definition at line 734 of file COptProblem.cpp.
References mUpdateMethods.
Referenced by COptMethod::initialize(), and COptMethodEP2::optimise().
 {return mUpdateMethods;}
const std::vector< COptItem * > & COptProblem::getConstraintList () const
Retrieve the list of constraints.
Returns
const std::vector< COptItem * > & constraintList
Definition at line 731 of file COptProblem.cpp.
References mpConstraintItems.
Referenced by COptMethod::initialize().
 {return *mpConstraintItems;}
const C_FLOAT64 & COptProblem::getExecutionTime () const
Retrieve the objective function.
Returns
const C_FLOAT64 & executionTime
Definition at line 850 of file COptProblem.cpp.
References CCopasiTimer::getElapsedTimeSeconds(), and mCPUTime.
Referenced by CQOptimizationResult::enterProtected(), CQFittingResultTab1::load(), CQOptimizationResult::slotSave(), and CQFittingResult::slotSave().
 {
   return mCPUTime.getElapsedTimeSeconds();
 }
const unsigned C_INT32 & COptProblem::getFunctionEvaluations () const
Retrieve the evaluation counter.
Returns
const unsigned C_INT32 & functionEvaluations
Definition at line 841 of file COptProblem.cpp.
References mCounter.
Referenced by CQOptimizationResult::enterProtected(), CQFittingResult::enterProtected(), CQFittingResultTab1::load(), COptMethodSS::localmin(), CQOptimizationResult::slotSave(), and CQFittingResult::slotSave().
 {return mCounter;}
const std::string COptProblem::getObjectiveFunction ()
Retrieve the objective function.
Returns
const std::string infix.
Definition at line 747 of file COptProblem.cpp.
References mpParmObjectiveExpression.
Referenced by CQOptimizationWidget::loadTask(), and CQOptimizationWidget::saveTask().
 {
   return *mpParmObjectiveExpression;
 }
COptItem & COptProblem::getOptItem (const size_t & index)
Retrieve the 'index' optimization item.
Parameters
const size_t & index
Returns
COptItem optItem
Definition at line 702 of file COptProblem.cpp.
 {return *(*mpOptItems)[index];}
const std::vector< COptItem * > & COptProblem::getOptItemList () const
Retrieve the list of optimization parameters.
Returns
const std::vector< COptItem * > & optItemList
Definition at line 728 of file COptProblem.cpp.
References mpOptItems.
Referenced by CQOptimizationResult::enterProtected(), CQFittingResult::enterProtected(), COptMethod::initialize(), and COptMethodSS::localmin().
 {return *mpOptItems;}
size_t COptProblem::getOptItemSize () const
Retrieve the number of optimization items.
Returns
const size_t size
Definition at line 705 of file COptProblem.cpp.
References mpGrpItems, and CCopasiParameterGroup::size().
 {return mpGrpItems->size();}
const bool & COptProblem::getRandomizeStartValues () const
Retrieve whether we have to calculate statistics
Returns
const bool & randomize
Definition at line 803 of file COptProblem.cpp.
References mpParmRandomizeStartValues.
Referenced by CQFittingWidget::loadTask(), CQOptimizationWidget::loadTask(), CQFittingWidget::saveTask(), and CQOptimizationWidget::saveTask().
 {return *mpParmRandomizeStartValues;}
const C_FLOAT64 & COptProblem::getSolutionValue () const
Retrieve the result for the solution
Definition at line 699 of file COptProblem.cpp.
References mSolutionValue.
Referenced by CQOptimizationResult::enterProtected(), CQFittingResultTab1::load(), COptMethodSS::localmin(), CQOptimizationResult::slotSave(), and CQFittingResult::slotSave().
 {return mSolutionValue;}
const CVector< C_FLOAT64 > & COptProblem::getSolutionVariables () const
Retrieve the solution variables
Definition at line 676 of file COptProblem.cpp.
References mSolutionVariables.
Referenced by CQOptimizationResult::enterProtected(), CQFittingResult::enterProtected(), COptMethodSS::localmin(), COptMethodSS::optimise(), COptMethodCoranaWalk::optimise(), COptMethodNelderMead::optimise(), COptMethodSA::optimise(), and CQFittingItemWidget::slotReset().
 {return mSolutionVariables;}
CCopasiTask::Type COptProblem::getSubtaskType () const
Retrieve the subtask type
Returns
CCopasiTask::Type subtaskType
Definition at line 781 of file COptProblem.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDataModel(), CCopasiTask::getType(), mpParmSubtaskCN, mpSubtask, CCopasiDataModel::ObjectFromName(), and CCopasiTask::unset.
Referenced by CQOptimizationWidget::loadTask(), and CQOptimizationWidget::saveTask().
 {
   std::vector< CCopasiContainer * > ListOfContainer;
   ListOfContainer.push_back(getObjectAncestor("Vector"));
   mpSubtask =
     dynamic_cast< CCopasiTask * >(const_cast< CCopasiObject *>(getObjectDataModel()->ObjectFromName(ListOfContainer, *mpParmSubtaskCN)));
   if (mpSubtask == NULL)
     return CCopasiTask::unset;
   return mpSubtask->getType();
 }
const CVector< C_FLOAT64 > & COptProblem::getVariableGradients () const
Retrieve the gradients for each solution variable.
Returns
const CVector< C_FLOAT64 > & variableGradients
Definition at line 679 of file COptProblem.cpp.
References mGradient.
Referenced by CQOptimizationResult::enterProtected(), and CQFittingResult::enterProtected().
 {return mGradient;}
size_t COptProblem::getVariableSize () const
Retrieve the size of the variable vectors.
Returns
size_t VariableSize
Referenced by COptMethodEP2::optimise().
void COptProblem::incrementEvaluations (unsigned C_INT32 increment)
Adds increment to the function evaluation counter
Parameters
unsigned C_INT32 increment
Definition at line 844 of file COptProblem.cpp.
References mCounter.
Referenced by COptMethodSS::localmin().
 {mCounter += increment;}
bool COptProblem::initialize () virtual
Do all necessary initialization so that calls to calculate will be successful. This is called once from CCopasiTask::process()
Returns
bool success
Reimplemented from CCopasiProblem.
Reimplemented in CFitProblem.
Definition at line 328 of file COptProblem.cpp.
References CModel::buildInitialRefreshSequence(), CCopasiObject::buildUpdateSequence(), CExpression::compile(), CModel::compileIfNecessary(), CCopasiMessage::ERROR, CCopasiObject::getDirectDependencies(), CEvaluationTree::getInfix(), CCopasiObject::getObjectParent(), CCopasiTask::getReport(), CReport::getStream(), CModel::getUptoDateObjects(), mConstraintCounter, MCOptimization, mCounter, mCPUTime, mFailedConstraintCounter, mFailedCounter, mInitialRefreshMethods, mOriginalVariables, CCopasiProblem::mpCallBack, mpConstraintItems, CCopasiProblem::mpModel, mpObjectiveExpression, mpOptItems, mpParmMaximize, CCopasiProblem::mpReport, mpSubtask, mRefreshConstraints, mRefreshMethods, mSolutionValue, mSolutionVariables, mUpdateMethods, mWorstValue, pTask, CVector< CType >::resize(), and CCopasiTimer::start().
Referenced by CFitProblem::initialize(), COptTask::initialize(), and COptMethodSS::initialize().
 {
   mWorstValue = (*mpParmMaximize ? - std::numeric_limits<C_FLOAT64>::infinity() : std::numeric_limits<C_FLOAT64>::infinity());
   if (!mpModel) return false;
   mpModel->compileIfNecessary(mpCallBack);
   bool success = true;
   mpReport = NULL;
   mCounter = 0;
   mFailedCounter = 0;
   mConstraintCounter = 0;
   mFailedConstraintCounter = 0;
   mSolutionValue = mWorstValue;
   std::vector< CCopasiContainer * > ContainerList;
   ContainerList.push_back(mpModel);
   COptTask * pTask = dynamic_cast<COptTask *>(getObjectParent());
   if (pTask)
     {
       ContainerList.push_back(pTask);
       mpReport = &pTask->getReport();
       if (!mpReport->getStream()) mpReport = NULL;
     }
   if (mpSubtask != NULL)
     ContainerList.push_back(mpSubtask);
   size_t i;
   size_t Size = mpOptItems->size();
   mUpdateMethods.resize(Size);
   mSolutionVariables.resize(Size);
   mOriginalVariables.resize(Size);
   mSolutionVariables = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   mOriginalVariables = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   std::vector< COptItem * >::iterator it = mpOptItems->begin();
   std::vector< COptItem * >::iterator end = mpOptItems->end();
   if (it == end)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 6);
       return false;
     }
   std::set< const CCopasiObject * > changedObjects;
   for (i = 0; it != end; ++it, i++)
     {
       success &= (*it)->compile(ContainerList);
       mUpdateMethods[i] = (*it)->getUpdateMethod();
       changedObjects.insert((*it)->getObject());
       mOriginalVariables[i] = *(*it)->COptItem::getObjectValue();
     }
   changedObjects.erase(NULL);
   mInitialRefreshMethods = mpModel->buildInitialRefreshSequence(changedObjects);
   it = mpConstraintItems->begin();
   end = mpConstraintItems->end();
   // We need to build a refresh sequence so the constraint values are updated
   std::set< const CCopasiObject * > Objects;
   for (i = 0; it != end; ++it, i++)
     {
       success &= (*it)->compile(ContainerList);
       Objects.insert((*it)->getDirectDependencies().begin(),
                      (*it)->getDirectDependencies().end());
     }
   mRefreshConstraints = CCopasiObject::buildUpdateSequence(Objects, mpModel->getUptoDateObjects());
   mCPUTime.start();
   if (mpObjectiveExpression == NULL ||
       mpObjectiveExpression->getInfix() == "" ||
       !mpObjectiveExpression->compile(ContainerList))
     {
       mRefreshMethods.clear();
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 5);
       return false;
     }
   mRefreshMethods = CCopasiObject::buildUpdateSequence(mpObjectiveExpression->getDirectDependencies(), mpModel->getUptoDateObjects());
   return success;
 }
void COptProblem::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 148 of file COptProblem.cpp.
References CCopasiParameterGroup::assertGroup(), CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, CCopasiParameter::CN, elevateChildren(), CCopasiParameter::EXPRESSION, CCopasiParameter::getValue(), mpGrpConstraints, mpGrpItems, mpParmCalculateStatistics, mpParmMaximize, mpParmObjectiveExpression, mpParmRandomizeStartValues, mpParmSubtaskCN, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, and CCopasiParameter::Value::pEXPRESSION.
Referenced by COptProblem().
 {
   mpParmSubtaskCN =
     assertParameter("Subtask", CCopasiParameter::CN, CCopasiObjectName(""))->getValue().pCN;
   mpParmObjectiveExpression =
     assertParameter("ObjectiveExpression", CCopasiParameter::EXPRESSION, std::string(""))->getValue().pEXPRESSION;
   mpParmMaximize =
     assertParameter("Maximize", CCopasiParameter::BOOL, false)-> getValue().pBOOL;
   mpParmRandomizeStartValues =
     assertParameter("Randomize Start Values", CCopasiParameter::BOOL, false)-> getValue().pBOOL;
   mpParmCalculateStatistics =
     assertParameter("Calculate Statistics", CCopasiParameter::BOOL, true)-> getValue().pBOOL;
   mpGrpItems = assertGroup("OptimizationItemList");
   mpGrpConstraints = assertGroup("OptimizationConstraintList");
   elevateChildren();
 }
bool COptProblem::initializeSubtaskBeforeOutput () virtual
perform at least the initializations of the subtask that must be done before the output is initialized.
Definition at line 303 of file COptProblem.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDataModel(), CCopasiTask::initialize(), mpParmSubtaskCN, mpSubtask, CCopasiTask::NO_OUTPUT, and CCopasiDataModel::ObjectFromName().
Referenced by COptTask::initialize(), and COptMethodSS::initialize().
 {
   if (mpParmSubtaskCN != NULL)
     {
       std::vector< CCopasiContainer * > ListOfContainer;
       ListOfContainer.push_back(getObjectAncestor("Vector"));
       mpSubtask =
         dynamic_cast< CCopasiTask * >(getObjectDataModel()->ObjectFromName(ListOfContainer, *mpParmSubtaskCN));
       try
         {
           if (mpSubtask != NULL)
             return mpSubtask->initialize(CCopasiTask::NO_OUTPUT, NULL, NULL);
         }
       catch (...) {}
       return false;
     }
   // We have a CFitProblem for which it is OK not to have a subtask.
   mpSubtask = NULL;
   return true;
 }
void COptProblem::initObjects () private
Definition at line 296 of file COptProblem.cpp.
References CCopasiContainer::addObjectReference(), CCopasiContainer::addVectorReference(), mCounter, mSolutionValue, mSolutionVariables, CCopasiObject::ValueDbl, and CCopasiObject::ValueInt.
Referenced by COptProblem().
 {
   addObjectReference("Function Evaluations", mCounter, CCopasiObject::ValueInt);
   addObjectReference("Best Value", mSolutionValue, CCopasiObject::ValueDbl);
   addVectorReference("Best Parameters", mSolutionVariables, CCopasiObject::ValueDbl);
 }
const bool & COptProblem::maximize () const
Check whether we have to maximize
Returns
const bool & maximize
Definition at line 797 of file COptProblem.cpp.
References mpParmMaximize.
Referenced by CQOptimizationWidget::loadTask(), CQOptimizationWidget::saveTask(), and setMaximize().
 {return *mpParmMaximize;}
void COptProblem::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Reimplemented in CFitProblem.
Definition at line 855 of file COptProblem.cpp.
 {*ostream << *this;}
void COptProblem::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implemented." To override this default behavior one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Reimplemented in CFitProblem.
Definition at line 858 of file COptProblem.cpp.
References C_FLOAT64, CCopasiTimer::getElapsedTime(), CCopasiTimeVariable::getMilliSeconds(), CCopasiTimeVariable::getSeconds(), CCopasiTimeVariable::LL2String(), mCounter, mCPUTime, mpOptItems, mSolutionValue, mSolutionVariables, and CVectorCore< CType >::size().
 {
   std::ostream & os = *ostream;
   if (mSolutionVariables.size() == 0)
     {
       return;
     }
   os << "    Objective Function Value:\t" << mSolutionValue << std::endl;
   CCopasiTimeVariable CPUTime = const_cast<COptProblem *>(this)->mCPUTime.getElapsedTime();
   os << "    Function Evaluations:\t" << mCounter << std::endl;
   os << "    CPU Time [s]:\t"
      << CCopasiTimeVariable::LL2String(CPUTime.getSeconds(), 1) << "."
      << CCopasiTimeVariable::LL2String(CPUTime.getMilliSeconds(true), 3) << std::endl;
   os << "    Evaluations/Second [1/s]:\t" << mCounter / (C_FLOAT64)(CPUTime.getMilliSeconds() / 1e3) << std::endl;
   os << std::endl;
   std::vector< COptItem * >::const_iterator itItem =
     mpOptItems->begin();
   std::vector< COptItem * >::const_iterator endItem =
     mpOptItems->end();
   size_t i;
   for (i = 0; itItem != endItem; ++itItem, i++)
     {
       os << "    " << (*itItem)->getObjectDisplayName() << ": "
          << mSolutionVariables[i] << std::endl;
     }
 }
void COptProblem::randomizeStartValues ()
Randomize the start values if requested
Definition at line 806 of file COptProblem.cpp.
References mpOptItems, and mpParmRandomizeStartValues.
Referenced by CFitTask::process(), and COptTask::process().
 {
   if (*mpParmRandomizeStartValues)
     {
       std::vector< COptItem * >::iterator it = mpOptItems->begin();
       std::vector< COptItem * >::iterator end = mpOptItems->end();
       for (; it != end; ++it)
         {
           (*it)->setStartValue((*it)->getRandomValue());
         }
     }
   return;
 }
void COptProblem::rememberStartValues ()
Remember the start values;
Definition at line 822 of file COptProblem.cpp.
References mpOptItems.
Referenced by CFitTask::process(), and COptTask::process().
 {
   std::vector< COptItem * >::iterator it = mpOptItems->begin();
   std::vector< COptItem * >::iterator end = mpOptItems->end();
   for (; it != end; ++it)
     {
       (*it)->rememberStartValue();
     }
   return;
 }
bool COptProblem::removeOptItem (const size_t & index)
Remove an optimization items.
Parameters
const size_t & index
Returns
bool success
Definition at line 721 of file COptProblem.cpp.
References mpGrpItems, and CCopasiParameterGroup::removeParameter().
 {return mpGrpItems->removeParameter(index);}
void COptProblem::reset ()
Reset counters and objective value.
Definition at line 269 of file COptProblem.cpp.
References mCounter, mpParmMaximize, and mSolutionValue.
Referenced by COptMethodSS::localmin(), and setCallBack().
 {
   mSolutionValue = (*mpParmMaximize ? - std::numeric_limits<C_FLOAT64>::infinity() : std::numeric_limits<C_FLOAT64>::infinity());
   mCounter = 0;
 }
void COptProblem::resetEvaluations ()
Resets the function evaluation counter
Definition at line 847 of file COptProblem.cpp.
References mCounter.
Referenced by COptMethodSS::localmin(), and COptTask::process().
 {mCounter = 0;}
bool COptProblem::restore (const bool & updateModel) virtual
Do all necessary restore procedures so that the model and task are in the same state as before.
Parameters
const bool & updateModel
Returns
bool success
Reimplemented from CCopasiProblem.
Reimplemented in CFitProblem.
Definition at line 478 of file COptProblem.cpp.
References mConstraintCounter, MCOptimization, mCounter, mFailedConstraintCounter, mFailedCounter, mpSubtask, CCopasiTask::restore(), restoreModel(), and CCopasiMessage::WARNING.
Referenced by CFitProblem::restore().
 {
   bool success = true;
   if (mpSubtask != NULL)
     success &= mpSubtask->restore();
   restoreModel(updateModel);
   if (mFailedCounter * 20 > mCounter) // > 5% failure rate
     CCopasiMessage(CCopasiMessage::WARNING, MCOptimization + 8, mFailedCounter, mCounter);
   if (10 * mFailedConstraintCounter > 8 * mConstraintCounter) // > 80 % failure rate
     CCopasiMessage(CCopasiMessage::WARNING, MCOptimization + 9, mFailedConstraintCounter, mConstraintCounter);
   return success;
 }
void COptProblem::restoreModel (const bool & updateModel)
Do all necessary restore procedures for the model is in the same state as before.
Parameters
const bool & updateModel
Definition at line 427 of file COptProblem.cpp.
References CVectorCore< CType >::array(), CModel::buildInitialRefreshSequence(), C_FLOAT64, mOriginalVariables, CCopasiProblem::mpModel, mpOptItems, mSolutionValue, mSolutionVariables, and mWorstValue.
Referenced by CScanTask::processCallback(), and restore().
 {
   std::vector<COptItem * >::iterator it = mpOptItems->begin();
   std::vector<COptItem * >::iterator end = mpOptItems->end();
   const C_FLOAT64 * pTmp;
   std::set< const CCopasiObject * > ChangedObjects;
   if (updateModel && mSolutionValue != mWorstValue)
     {
       // Set the model values and start values to the solution values
       pTmp = mSolutionVariables.array();
       for (; it != end; ++it, pTmp++)
         {
           if ((*it)->getObject())
             {
               (*(*it)->COptItem::getUpdateMethod())(*pTmp);
               (*it)->setStartValue(*pTmp);
               ChangedObjects.insert((*it)->getObject());
             }
         }
     }
   else
     {
       // Reset the model values to the original values
       pTmp = mOriginalVariables.array();
       for (; it != end; ++it, pTmp++)
         {
           if ((*it)->getObject())
             {
               if (!isnan(*pTmp))
                 (*(*it)->COptItem::getUpdateMethod())(*pTmp);
               ChangedObjects.insert((*it)->getObject());
             }
         }
     }
   // We need to update the dependent initial values
   std::vector< Refresh * > UpdateSequence = mpModel->buildInitialRefreshSequence(ChangedObjects);
   std::vector< Refresh * >::iterator itUpdate = UpdateSequence.begin();
   std::vector< Refresh * >::iterator endUpdate = UpdateSequence.end();
   for (; itUpdate != endUpdate; ++itUpdate)
     {
       (**itUpdate)();
     }
 }
void COptProblem::setCalculateStatistics (const bool & calculate)
Set whether we have to calculate statistics
Parameters
const bool & calculate
Definition at line 835 of file COptProblem.cpp.
References calculate(), and mpParmCalculateStatistics.
Referenced by COptMethodSS::initialize(), Arguments::prepareModel(), CQFittingWidget::saveTask(), and CQOptimizationWidget::saveTask().
 {*mpParmCalculateStatistics = calculate;}
bool COptProblem::setCallBack (CProcessReport * pCallBack) virtual
Set the call back of the problem
Parameters
CProcessReport * pCallBack
Returns
bool success
Reimplemented from CCopasiProblem.
Reimplemented in CFitProblem.
Definition at line 275 of file COptProblem.cpp.
References CProcessReport::addItem(), mCounter, mhCounter, mhSolutionValue, CCopasiProblem::mpCallBack, mSolutionValue, reset(), and CCopasiProblem::setCallBack().
Referenced by COptMethodSS::initialize(), and CFitProblem::setCallBack().
 {
   CCopasiProblem::setCallBack(pCallBack);
   if (pCallBack)
     {
       reset();
       // We need to reset mSolutionValue to correctly initialize the progress item.
       mhSolutionValue =
         mpCallBack->addItem("Best Value",
                             mSolutionValue);
       // We need to reset mCounter to correctly initialize the progress item.
       mhCounter =
         mpCallBack->addItem("Function Evaluations",
                             mCounter);
     }
   return true;
 }
void COptProblem::setMaximize (const bool & maximize)
Set whether we have to maximize the objective function
Parameters
const bool & maximize
Definition at line 794 of file COptProblem.cpp.
References maximize(), and mpParmMaximize.
Referenced by CQOptimizationWidget::saveTask().
 {*mpParmMaximize = maximize;}
bool COptProblem::setModel (CModel * pModel) virtual
Set the model of the problem
Parameters
CModel * pModel
Returns
bool success
Reimplemented from CCopasiProblem.
Reimplemented in CFitProblem.
Definition at line 263 of file COptProblem.cpp.
References CCopasiProblem::mpModel.
Referenced by CFitProblem::setModel().
 {
   mpModel = pModel;
   return true;
 }
bool COptProblem::setObjectiveFunction (const std::string & infix)
Set optimization function
Parameters
const std::string & infix
Returns
bool success
Definition at line 737 of file COptProblem.cpp.
References mpObjectiveExpression, mpParmObjectiveExpression, and CExpression::setInfix().
Referenced by elevateChildren(), and CQOptimizationWidget::saveTask().
 {
   *mpParmObjectiveExpression = infix;
   if (mpObjectiveExpression == NULL)
     mpObjectiveExpression = new CExpression("Expression", this);
   return mpObjectiveExpression->setInfix(infix);
 }
void COptProblem::setRandomizeStartValues (const bool & randomize)
Set whether we have to randomize start values
Parameters
const bool & randomize
Definition at line 800 of file COptProblem.cpp.
References mpParmRandomizeStartValues.
Referenced by COptMethodSS::initialize(), Arguments::prepareModel(), CQFittingWidget::saveTask(), and CQOptimizationWidget::saveTask().
 {*mpParmRandomizeStartValues = randomize;}
bool COptProblem::setSolution (const C_FLOAT64 & value, const CVector< C_FLOAT64 > & variables) virtual
Set the solution.
Parameters
const C_FLOAT64 & value
const CVector< C_FLOAT64 > & variables
Returns
bool continue;
Reimplemented in CFitProblem.
Definition at line 682 of file COptProblem.cpp.
References mhSolutionValue, CCopasiProblem::mpCallBack, mpParmMaximize, mSolutionValue, mSolutionVariables, and CProcessReport::progressItem().
Referenced by COptMethodPS::create(), COptMethodPraxis::evaluateFunction(), COptMethodPS::move(), COptMethodDE::optimise(), COptMethodSRES::optimise(), COptMethodSS::optimise(), COptMethodGA::optimise(), COptMethodPS::optimise(), COptMethodGASR::optimise(), COptMethodHookeJeeves::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodNelderMead::optimise(), COptMethodCoranaWalk::optimise(), COptMethodSA::optimise(), COptMethodTruncatedNewton::optimise(), COptMethodPraxis::optimise(), COptMethodStatistics::optimise(), COptMethodSteepestDescent::optimise(), COptMethodEP::optimise(), CRandomSearch::optimise(), CFitProblem::setSolution(), and COptMethodTruncatedNewton::sFun().
 {
   mSolutionValue = *mpParmMaximize ? -value : value;
   mSolutionVariables = variables;
   bool Continue = true;
   if (value == -std::numeric_limits< C_FLOAT64 >::infinity())
     Continue = false;
   if (mpCallBack)
     Continue &= mpCallBack->progressItem(mhSolutionValue);
   return Continue;
 }
bool COptProblem::setSubtaskType (const CCopasiTask::Type & subtaskType)
Set subtask type
Parameters
const CCopasiTask::Type & subtaskType
Returns
success
Definition at line 752 of file COptProblem.cpp.
References CCopasiObject::getCN(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDataModel(), CCopasiProblem::getType(), mpParmSubtaskCN, mpSubtask, and CCopasiVector< T >::size().
Referenced by elevateChildren(), and CQOptimizationWidget::saveTask().
 {
   mpSubtask = NULL;
   *mpParmSubtaskCN = "";
   CCopasiVectorN< CCopasiTask > * pTasks =
     dynamic_cast< CCopasiVectorN< CCopasiTask > *>(getObjectAncestor("Vector"));
   CCopasiDataModel* pDataModel = getObjectDataModel();
   if (pTasks == NULL && pDataModel)
     pTasks = pDataModel->getTaskList();
   if (pTasks)
     {
       size_t i, imax = pTasks->size();
       for (i = 0; i < imax; i++)
         if ((*pTasks)[i]->getType() == subtaskType)
           {
             mpSubtask = (*pTasks)[i];
             *mpParmSubtaskCN = mpSubtask->getCN();
             return true;
           }
     }
   return false;
 }
bool COptProblem::swapOptItem (const size_t & iFrom, const size_t & iTo)
Swap two optimization items.
Parameters
const size_t & iFrom
const size_t & iTo
Returns
bool success
Definition at line 724 of file COptProblem.cpp.
References mpGrpItems, and CCopasiParameterGroup::swap().
 {return mpGrpItems->swap(iFrom, iTo);}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const COptProblem & o) friend
Output stream operator
Parameters
ostream & os
const COptProblem & A
Returns
ostream & os
Definition at line 892 of file COptProblem.cpp.
 {
   os << "Problem Description:" << std::endl;
   os << "Subtask: " << std::endl;
   if (o.mpSubtask)
     o.mpSubtask->getDescription().print(&os);
   else
     os << "No Subtask specified.";
   os << std::endl;
   if (o.mpObjectiveExpression)
     {
       os << "Objective Function:" << std::endl;
       os << "    " << o.mpObjectiveExpression->getDisplayString() << std::endl;
       os << std:: endl;
     }
   os << "List of Optimization Items:" << std::endl;
   std::vector< COptItem * >::const_iterator itItem =
     o.mpOptItems->begin();
   std::vector< COptItem * >::const_iterator endItem =
     o.mpOptItems->end();
   for (; itItem != endItem; ++itItem)
     os << "    " << **itItem << std::endl;
   itItem = o.mpConstraintItems->begin();
   endItem = o.mpConstraintItems->end();
   for (; itItem != endItem; ++itItem)
     os << "    " << **itItem << std::endl;
   return os;
 }
Member Data Documentation
C_FLOAT64 COptProblem::mCalculateValue protected
A vector of results for calculate
Definition at line 474 of file COptProblem.h.
Referenced by CFitProblem::calculate(), calculate(), CFitProblem::calculateStatistics(), calculateStatistics(), and getCalculateValue().
unsigned C_INT32 COptProblem::mConstraintCounter protected
Counter of constraint checks
Definition at line 504 of file COptProblem.h.
Referenced by CFitProblem::checkFunctionalConstraints(), checkFunctionalConstraints(), initialize(), and restore().
unsigned C_INT32 COptProblem::mCounter protected
Counter of evaluations
Definition at line 494 of file COptProblem.h.
Referenced by CFitProblem::calculate(), calculate(), CFitProblem::calculateCrossValidation(), getFunctionEvaluations(), incrementEvaluations(), initialize(), initObjects(), CFitProblem::printResult(), printResult(), reset(), resetEvaluations(), restore(), and setCallBack().
CCopasiTimer COptProblem::mCPUTime protected
A CPU Timer
Definition at line 514 of file COptProblem.h.
Referenced by CFitProblem::calculateStatistics(), calculateStatistics(), getExecutionTime(), initialize(), CFitProblem::printResult(), and printResult().
unsigned C_INT32 COptProblem::mFailedConstraintCounter protected
Counter of failed constraint checks
Definition at line 509 of file COptProblem.h.
Referenced by CFitProblem::checkFunctionalConstraints(), checkFunctionalConstraints(), initialize(), and restore().
unsigned C_INT32 COptProblem::mFailedCounter protected
Counter of failed evaluations
Definition at line 499 of file COptProblem.h.
Referenced by CFitProblem::calculate(), calculate(), CFitProblem::calculateCrossValidation(), initialize(), and restore().
CVector< C_FLOAT64 > COptProblem::mGradient protected
The gradient vector for the parameters
Definition at line 541 of file COptProblem.h.
Referenced by CFitProblem::calculateStatistics(), calculateStatistics(), getVariableGradients(), and CFitProblem::printResult().
bool COptProblem::mHaveStatistics protected
Indicates whether the statistics have been calculated for the current result
Definition at line 536 of file COptProblem.h.
Referenced by CFitProblem::calculateStatistics(), calculateStatistics(), CFitProblem::initialize(), and CFitProblem::printResult().
size_t COptProblem::mhCounter protected
Handle of "Function Evaluations" process report item
Definition at line 524 of file COptProblem.h.
Referenced by CFitProblem::calculate(), calculate(), CFitProblem::calculateCrossValidation(), and setCallBack().
size_t COptProblem::mhSolutionValue protected
Handle of "Best Value" process report item
Definition at line 519 of file COptProblem.h.
Referenced by setCallBack(), and setSolution().
std::vector< Refresh * > COptProblem::mInitialRefreshMethods protected
A vector of refresh methods which need to be called update all initial values which depend on the optimization items.
Definition at line 457 of file COptProblem.h.
Referenced by calculate(), and initialize().
CVector< C_FLOAT64 > COptProblem::mOriginalVariables protected
A vector of solution variables
Definition at line 484 of file COptProblem.h.
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), initialize(), and restoreModel().
std::vector<COptItem *>* COptProblem::mpConstraintItems protected
A pointer to the vector of optimization constraints
Definition at line 436 of file COptProblem.h.
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), CFitProblem::checkFunctionalConstraints(), checkFunctionalConstraints(), CFitProblem::elevateChildren(), elevateChildren(), getConstraintList(), CFitProblem::initialize(), initialize(), and operator<<().
CCopasiParameterGroup* COptProblem::mpGrpConstraints protected
A pointer to the value of the CCopasiParameter holding the OptimizationConstraints
Definition at line 426 of file COptProblem.h.
Referenced by elevateChildren(), and initializeParameter().
CCopasiParameterGroup* COptProblem::mpGrpItems protected
A pointer to the value of the CCopasiParameterGroup holding the OptimizationItems
Definition at line 421 of file COptProblem.h.
Referenced by addOptItem(), elevateChildren(), getOptItemSize(), initializeParameter(), removeOptItem(), and swapOptItem().
CExpression* COptProblem::mpObjectiveExpression protected
The objective function which should be minimized or maximized.
Definition at line 446 of file COptProblem.h.
Referenced by calculate(), initialize(), operator<<(), and setObjectiveFunction().
std::vector<COptItem *>* COptProblem::mpOptItems protected
A pointer to the vector of optimization items
Definition at line 431 of file COptProblem.h.
Referenced by CFitProblem::calculate(), checkParametricConstraints(), CFitProblem::elevateChildren(), elevateChildren(), getOptItemList(), CFitProblem::initialize(), initialize(), operator<<(), CFitProblem::printResult(), printResult(), randomizeStartValues(), rememberStartValues(), and restoreModel().
bool* COptProblem::mpParmCalculateStatistics protected
A pointer to the value of the CCopasiParameter holding Calculate Statistics
Definition at line 416 of file COptProblem.h.
Referenced by CFitProblem::calculateStatistics(), calculateStatistics(), getCalculateStatistics(), initializeParameter(), CFitProblem::printResult(), and setCalculateStatistics().
bool* COptProblem::mpParmMaximize protected
A pointer to the value of the CCopasiParameter holding Maximize
Definition at line 406 of file COptProblem.h.
Referenced by calculate(), calculateStatistics(), initialize(), CFitProblem::initializeParameter(), initializeParameter(), maximize(), reset(), setMaximize(), and setSolution().
std::string* COptProblem::mpParmObjectiveExpression protected
A pointer to the value of the CCopasiParameter holding the ObjectiveFunctionKey A pointer to the value of the CCopasiParameter holding the infix expression of the objective function
Definition at line 401 of file COptProblem.h.
Referenced by elevateChildren(), getObjectiveFunction(), CFitProblem::initializeParameter(), initializeParameter(), and setObjectiveFunction().
bool* COptProblem::mpParmRandomizeStartValues protected
A pointer to the value of the CCopasiParameter holding Randomize Start Values
Definition at line 411 of file COptProblem.h.
Referenced by getRandomizeStartValues(), initializeParameter(), randomizeStartValues(), and setRandomizeStartValues().
std::string* COptProblem::mpParmSubtaskCN protected
A pointer to the value of the CCopasiParameter holding the CN for the subtask
Definition at line 390 of file COptProblem.h.
Referenced by elevateChildren(), getSubtaskType(), CFitProblem::initializeParameter(), initializeParameter(), initializeSubtaskBeforeOutput(), and setSubtaskType().
CCopasiTask* COptProblem::mpSubtask mutable protected
Pointer to the subtask to be used in the optimization
Definition at line 441 of file COptProblem.h.
Referenced by calculate(), getSubtaskType(), initialize(), initializeSubtaskBeforeOutput(), operator<<(), restore(), and setSubtaskType().
std::vector< Refresh * > COptProblem::mRefreshConstraints protected
A vector of refresh methods which need to be called retrieve the values of constraints.
Definition at line 469 of file COptProblem.h.
Referenced by checkFunctionalConstraints(), and initialize().
std::vector< Refresh * > COptProblem::mRefreshMethods protected
A vector of refresh methods which need to be called retrieve the value of the objective function.
Definition at line 463 of file COptProblem.h.
Referenced by calculate(), and initialize().
C_FLOAT64 COptProblem::mSolutionValue protected
A vector of solution results
Definition at line 489 of file COptProblem.h.
Referenced by CFitProblem::calculateCrossValidation(), CFitProblem::calculateStatistics(), calculateStatistics(), getSolutionValue(), initialize(), initObjects(), CFitProblem::printResult(), printResult(), reset(), restoreModel(), setCallBack(), and setSolution().
CVector< C_FLOAT64 > COptProblem::mSolutionVariables protected
A vector of solution variables
Definition at line 479 of file COptProblem.h.
Referenced by CFitProblem::calculateCrossValidation(), CFitProblem::calculateStatistics(), calculateStatistics(), getSolutionVariables(), CFitProblem::initialize(), initialize(), initObjects(), CFitProblem::printResult(), printResult(), restoreModel(), and setSolution().
bool COptProblem::mStoreResults protected
Indicates whether the results shall be stored. The default is false.
Definition at line 530 of file COptProblem.h.
Referenced by CFitProblem::calculate(), calculate(), CFitProblem::calculateCrossValidation(), CFitProblem::calculateStatistics(), calculateStatistics(), and CFitProblem::initialize().
std::vector< UpdateMethod * > COptProblem::mUpdateMethods protected
A vector of update method to the values of the optimization items.
Definition at line 451 of file COptProblem.h.
Referenced by CFitProblem::calculateStatistics(), calculateStatistics(), getCalculateVariableUpdateMethods(), and initialize().
C_FLOAT64 COptProblem::mWorstValue protected
A static value containing Infinity.
Definition at line 385 of file COptProblem.h.
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), CFitProblem::calculateStatistics(), calculateStatistics(), CFitProblem::initialize(), initialize(), and restoreModel().
const unsigned int COptProblem::ValidSubtasks static
Initial value:
=
{
  CCopasiTask::steadyState,
  CCopasiTask::timeCourse,
  CCopasiTask::scan,
  CCopasiTask::parameterFitting,
  CCopasiTask::mca,
  CCopasiTask::lyap,
  CCopasiTask::tssAnalysis,
  CCopasiTask::sens,
  CCopasiTask::crosssection,
  CCopasiTask::lna,
  CCopasiTask::unset
}
The methods which can be selected for performing this task.
File name: COptProblem.cpp
Programmer: Yongqun He Contact email: yohe@.nosp@m.vt.e.nosp@m.du Purpose: This is the source file of the COptProblem class. It specifies the optimization problem with its own members and functions. It's used by COptAlgorithm class and COptimization class
Definition at line 57 of file COptProblem.h.
Referenced by CQOptimizationWidget::init().
The documentation for this class was generated from the following files:
COptProblem.h
COptProblem.cpp