COPASI API: CModelEntity Class Reference
CModelEntity Class Reference
#include <CModelValue.h>
Public Types
enum Status {
FIXED = 0, ASSIGNMENT, REACTIONS, ODE,
TIME
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Public Member Functions
virtual void calculate ()
CModelEntity (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="ModelEntity", const unsigned C_INT32 &flag=CCopasiObject::Container|CCopasiObject::ValueDbl)
CModelEntity (const CModelEntity &src, const CCopasiContainer *pParent=NULL)
virtual bool compile ()
virtual std::set< const
CCopasiObject * > getDeletedObjects () const
std::string getExpression () const
const CExpression * getExpressionPtr () const
CExpression * getExpressionPtr ()
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CExpression * getInitialExpressionPtr ()
const C_FLOAT64 & getInitialValue () const
CCopasiObject * getInitialValueReference () const
virtual const std::string & getKey () const
const C_FLOAT64 & getRate () const
CCopasiObject * getRateReference () const
const std::string & getSBMLId () const
const CModelEntity::Status & getStatus () const
const C_FLOAT64 & getValue () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isFixed () const
const bool & isUsed () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void refreshInitialValue ()
bool setExpression (const std::string &expression)
bool setExpressionPtr (CExpression *pExpression)
bool setInitialExpression (const std::string &expression)
bool setInitialExpressionPtr (CExpression *pExpression)
virtual void setInitialValue (const C_FLOAT64 &initialValue)
void setInitialValuePtr (C_FLOAT64 *pInitialValue)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setRate (const C_FLOAT64 &rate)
void setSBMLId (const std::string &id)
virtual void setStatus (const CModelEntity::Status &status)
void setUsed (const bool &used)
virtual void setValue (const C_FLOAT64 &value)
void setValuePtr (C_FLOAT64 *pValue)
~CModelEntity ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Static Public Attributes
static const std::string StatusName []
static const char * XMLStatus []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Attributes
CExpression * mpExpression
CExpression * mpInitialExpression
C_FLOAT64 * mpIValue
CCopasiObjectReference
< C_FLOAT64 > * mpIValueReference
CModel * mpModel
CCopasiObjectReference
< C_FLOAT64 > * mpRateReference
C_FLOAT64 * mpValue
CCopasiObjectReference
< C_FLOAT64 > * mpValueReference
C_FLOAT64 mRate
std::string mSBMLId
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Private Member Functions
void initObjects ()
Private Attributes
Status mStatus
bool mUsed
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
The base class for CCompartment, CMetab and CModelValue. CModelEntity is a base class for CCompartment, CMetab and CModelValue. These three classes have in common that (in the long run) they can each be model variables (subject to ODEs), constant, or subject to algebraic assignments. In addition, the CMetab objects can also be subject to reactions, and conservation rules.
Definition at line 39 of file CModelValue.h.
Member Enumeration Documentation
enum CModelEntity::Status
The valid states for metabolites
Enumerator
FIXED
ASSIGNMENT
REACTIONS
ODE
TIME
Definition at line 53 of file CModelValue.h.
   {
     FIXED = 0, //the entity is constant (for species even if they are part of a reaction)
     ASSIGNMENT, //the entity is changed by an assignment rule
     REACTIONS, //applies only for species, the species concentration is changed by reactions
     //      DEPENDENT, //applies only for species, the species concentration is determined by conservation rules
     //      UNUSED,
     ODE, //the entity is changed by an ordinary differential equation
     TIME
   };
Constructor & Destructor Documentation
CModelEntity::CModelEntity (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL, const std::string & type = "ModelEntity", const unsigned C_INT32 & flag = CCopasiObject::Container | CCopasiObject::ValueDbl)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 62 of file CModelValue.cpp.
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectType(), initObjects(), CAnnotation::mKey, mpIValue, and mpValue.
                                                          :
   CCopasiContainer(name, pParent, type, (flag | CCopasiObject::Container | CCopasiObject::ValueDbl | CCopasiObject::ModelEntity)),
   CAnnotation(),
   mpValue(NULL),
   mpIValue(NULL),
   mRate(0.0),
   mpExpression(NULL),
   mpInitialExpression(NULL),
   mStatus(FIXED),
   mUsed(false),
   mpModel(NULL)
 {
   mKey = CCopasiRootContainer::getKeyFactory()->add(getObjectType(), this);
   initObjects();
   *mpIValue = 1.0;
   *mpValue = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   CONSTRUCTOR_TRACE;
 }
CModelEntity::CModelEntity (const CModelEntity & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CModelValue & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 87 of file CModelValue.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CCopasiObject::getObjectType(), initObjects(), CAnnotation::mKey, mpIValue, mpValue, mStatus, CAnnotation::setMiriamAnnotation(), and setStatus().
                                                             :
   CCopasiContainer(src, pParent),
   CAnnotation(src),
   mpValue(NULL),
   mpIValue(NULL),
   mRate(src.mRate),
   mpExpression(src.mpExpression ? new CExpression(*src.mpExpression, this) : NULL),
   mpInitialExpression(src.mpInitialExpression ? new CExpression(*src.mpInitialExpression, this) : NULL),
   mStatus(FIXED),
   mUsed(false),
   mpModel(NULL)
 {
   mKey = CCopasiRootContainer::getKeyFactory()->add(getObjectType(), this);
   initObjects();
   setStatus(src.mStatus);
   *mpValue = *src.mpValue;
   *mpIValue = *src.mpIValue;
   setMiriamAnnotation(src.getMiriamAnnotation(), mKey, src.mKey);
 }
CModelEntity::~CModelEntity ()
Destructor.
Definition at line 112 of file CModelValue.cpp.
References DESTRUCTOR_TRACE, CModel::getStateTemplate(), mpIValue, mpModel, mpValue, pdelete, and CStateTemplate::remove().
 {
   if (mpModel)
     mpModel->getStateTemplate().remove(this);
   // After the above call we definitely own the data and
   // therefore must destroy them.
   pdelete(mpValue);
   pdelete(mpIValue);
   // since the expressions now have the model entity as parent, they should
   // automatically be destroyed be the destructor of CCopasiContainer
   //pdelete(mpExpression);
   //pdelete(mpInitialExpression);
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
void CModelEntity::calculate (void) virtual
Calculate the value or the rate depending whether we have an ASIGNMENT or ODE
Reimplemented in CMetab.
Definition at line 197 of file CModelValue.cpp.
References ASSIGNMENT, CExpression::calcValue(), mpExpression, mpValue, mRate, mStatus, and ODE.
Referenced by setStatus().
 {
   switch (mStatus)
     {
       case ASSIGNMENT:
         *mpValue = mpExpression->calcValue();
         break;
       case ODE:
         mRate = mpExpression->calcValue();
         break;
       default:
         break;
     }
 }
bool CModelEntity::compile () virtual
Compile the model value. This is only needed for status ASIGNMENT and ODE.
Returns
bool success
Reimplemented in CModel, and CMetab.
Definition at line 143 of file CModelValue.cpp.
References CCopasiContainer::add(), CCopasiObject::addDirectDependency(), ASSIGNMENT, CExpression::calcValue(), CExpression::compile(), CExpression::createInitialExpression(), CCopasiObject::getDirectDependencies(), CEvaluationTree::getInfix(), CCopasiObject::getObjectDataModel(), CEvaluationTree::isUsable(), mpExpression, mpInitialExpression, mpIValue, mpIValueReference, mpModel, mpRateReference, mpValueReference, mStatus, ODE, pdelete, CCopasiObject::setDirectDependencies(), and CCopasiObject::setObjectName().
Referenced by CModel::buildSimulatedSequence(), CModel::buildStateTemplate(), setExpression(), setExpressionPtr(), setInitialExpression(), and setInitialExpressionPtr().
 {
   bool success = true;
   std::set< const CCopasiObject * > NoDependencies;
   std::vector< CCopasiContainer * > listOfContainer;
   listOfContainer.push_back(mpModel);
   CCopasiDataModel* pDataModel = NULL;
   switch (mStatus)
     {
       case ASSIGNMENT:
         success &= mpExpression->compile(listOfContainer);
         mpValueReference->setDirectDependencies(mpExpression->getDirectDependencies());
         pdelete(mpInitialExpression);
         pDataModel = getObjectDataModel();
         assert(pDataModel != NULL);
         mpInitialExpression = CExpression::createInitialExpression(*mpExpression, pDataModel);
         mpInitialExpression->setObjectName("InitialExpression");
         add(mpInitialExpression, true);
         break;
       case ODE:
         mpValueReference->addDirectDependency(this);
         success &= mpExpression->compile(listOfContainer);
         mpRateReference->setDirectDependencies(mpExpression->getDirectDependencies());
         break;
       default:
         break;
     }
   // Here we handle initial expressions for all types.
   if (mpInitialExpression != NULL &&
       mpInitialExpression->getInfix() != "")
     {
       success &= mpInitialExpression->compile(listOfContainer);
       mpIValueReference->setDirectDependencies(mpInitialExpression->getDirectDependencies());
       // If we have a valid initial expression, we update the initial value.
       // In case the expression is constant this suffices other are updated lated again.
       if (mpInitialExpression->isUsable())
         *mpIValue = mpInitialExpression->calcValue();
     }
   else
     {
       mpIValueReference->setDirectDependencies(NoDependencies);
     }
   return success;
 }
std::set< const CCopasiObject * > CModelEntity::getDeletedObjects () const virtual
Retrieve the list of deleted numeric child objects;
Returns
std::set< const CCopasiObject * > deletedObjects
Reimplemented in CMetab, and CCompartment.
Definition at line 587 of file CModelValue.cpp.
References mpIValueReference, mpRateReference, and mpValueReference.
Referenced by CModel::appendDependentModelObjects(), CModel::determineIsAutonomous(), CCompartment::getDeletedObjects(), CMetab::getDeletedObjects(), mustBeDeleted(), CModel::removeModelValue(), CQGlobalQuantityDM::removeRows(), and CQModelValue::slotBtnDelete().
 {
   std::set< const CCopasiObject * > Deleted;
   Deleted.insert(this);
   Deleted.insert(mpIValueReference);
   Deleted.insert(mpValueReference);
   Deleted.insert(mpRateReference);
   return Deleted;
 }
std::string CModelEntity::getExpression () const
Retrieve the expression for non FIXED model values.
Returns
std::string expression
Definition at line 236 of file CModelValue.cpp.
References CEvaluationTree::getInfix(), isFixed(), mpExpression, and CExpression::updateInfix().
Referenced by CModel::convert2NonReversible(), CMathObject::createExtensiveODERateExpression(), CSBMLExporter::createRule(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CQSpeciesDetail::load(), CQCompartment::load(), CQModelValue::load(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), and CCopasiXML::saveModel().
 {
   if (isFixed() || mpExpression == NULL)
     return "";
   mpExpression->updateInfix();
   return mpExpression->getInfix();
 }
const CExpression * CModelEntity::getExpressionPtr () const
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
Definition at line 250 of file CModelValue.cpp.
References mpExpression.
Referenced by CSBMLExporter::checkForPiecewiseFunctions(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMathObject::compileRate(), CMathObject::compileValue(), CModelAdd::copyExpression(), CSBMLExporter::createRule(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValuesExpressions(), SBMLImporter::importRuleForModelEntity(), CModelMerging::mergeMetabolites(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInModelEntity(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000027::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000087::test_import_reaction_flux_reference_2(), test000075::test_import_time_dependent_function_definition(), test000087::test_simulate_reaction_flux_reference_1(), and CMMLOutput::writeRHS_ModelEntity().
 {
   return mpExpression;
 }
CExpression * CModelEntity::getExpressionPtr ()
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
Definition at line 245 of file CModelValue.cpp.
References mpExpression.
 {
   return mpExpression;
 }
std::string CModelEntity::getInitialExpression () const
Retrieve the expression for ODE or REACTION model values.
Returns
std::string expression
Definition at line 350 of file CModelValue.cpp.
References ASSIGNMENT, CEvaluationTree::getInfix(), mpInitialExpression, mStatus, and CExpression::updateInfix().
Referenced by CModelAdd::addCompartmentsExpressions(), CModelAdd::addMetabolitesExpressions(), CModelAdd::addModelValuesExpressions(), CModel::buildInitialRefreshSequence(), CModel::convert2NonReversible(), CSBMLExporter::createCompartment(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CQGlobalQuantityDM::data(), CQSpecieDM::data(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), SliderDialog::fillSliderBox(), CQSimpleSelectionTree::filter(), CParticleReference::getDirectDependencies(), CQSpeciesDetail::load(), CQCompartment::load(), CQModelValue::load(), CModelMerging::mergeMetabolites(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), CCopasiXML::saveModel(), test000041::test_hasOnlySubstanceUnits(), and test000040::test_hasOnlySubstanceUnits().
 {
   if (mStatus == ASSIGNMENT || mpInitialExpression == NULL)
     return "";
   mpInitialExpression->updateInfix();
   return mpInitialExpression->getInfix();
 }
const CExpression * CModelEntity::getInitialExpressionPtr () const
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
Definition at line 294 of file CModelValue.cpp.
References mpInitialExpression.
Referenced by CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMathObject::compileInitialValue(), CModelAdd::copyInitialExpression(), CSBMLExporter::createInitialAssignment(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), SBMLImporter::importInitialAssignments(), CModelMerging::mergeMetabolites(), SBMLImporter::removeUnusedFunctions(), CModelExpansion::replaceInModelEntity(), test000093::test_bug1503_1(), test000040::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), and test000075::test_import_time_dependent_function_definition().
 {
   return mpInitialExpression;
 }
CExpression * CModelEntity::getInitialExpressionPtr ()
Retrieve the pointer to the expression for non FIXED model values.
Returns
CExpression*
Definition at line 289 of file CModelValue.cpp.
References mpInitialExpression.
 {
   return mpInitialExpression;
 }
const C_FLOAT64 & CModelEntity::getInitialValue () const
Retrieve the initial value
Definition at line 138 of file CModelValue.cpp.
References mpIValue.
Referenced by CModelAdd::addCompartments(), CModelAdd::addModelValues(), CFunctionAnalyzer::constructCallParametersActualValues(), CMetab::convertToConcentration(), CMetab::convertToNumber(), CSBMLExporter::createCompartment(), CModelParameterSet::createFromModel(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CCSPMethod::cspstep(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CODEExporter::exportCompartments(), CODEExporter::exportExpression(), CODEExporter::exportMetabolites(), CODEExporter::exportModelValues(), CModel::initializeAtolVector(), CQSpeciesDetail::load(), CQCompartment::load(), CQModelValue::load(), CReactionInterface::loadMappingAndValues(), CQUpdatesWidget::loadObjectsTable(), CModelParameter::refreshFromModel(), CMetab::refreshInitialConcentration(), CMetab::refreshInitialValue(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), CQSpecieDM::setData(), CQSpeciesDetail::slotCompartmentChanged(), CModel::suitableForStochasticSimulation(), test000091::test_delay_in_kinetic_law_local_parameter(), test000026::test_hasOnlySubstanceUnits(), test000087::test_simulate_reaction_flux_reference_1(), and ParameterTable::updateTable().
 {return *mpIValue;}
CCopasiObject * CModelEntity::getInitialValueReference () const
Retrieve object referencing the initial value
Returns
CCopasiObject * initialValueReference
Definition at line 367 of file CModelValue.cpp.
References mpIValueReference.
Referenced by DataModelGUI::buildChangedObjects(), CModel::buildInitialRefreshSequence(), CMetab::compileInitialValueDependencies(), CMathObject::createExtensiveValueExpression(), CModelParameterSet::createFromModel(), CSBMLExporter::createInitialAssignment(), CExpression::createInitialExpression(), CMathObject::createIntensiveValueExpression(), test000097::createModel(), SliderDialog::determineCorrectObjectForSlider(), findObjectByDisplayName(), CMetab::getChildObjectUnits(), getInitialCNForSBase(), CModelParameter::getUnit(), SBMLImporter::importInitialAssignments(), CMathContainer::initializeObjects(), CQSimpleSelectionTree::populateTree(), SBMLImporter::replace_time_with_initial_time(), test000058::test_bug1025_10(), test000058::test_bug1025_2(), test000058::test_bug1025_4(), test000058::test_bug1025_5(), test000058::test_bug1025_7(), test000058::test_bug1025_9(), test000059::test_unique_id_1(), test000059::test_unique_id_12(), test000059::test_unique_id_14(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), test000059::test_unique_id_21_2(), test000059::test_unique_id_3(), test000059::test_unique_id_6(), and test000059::test_unique_id_8().
 {return mpIValueReference;}
const std::string & CModelEntity::getKey () const virtual
Retrieve the key
Returns
std::string key
Reimplemented from CAnnotation.
Reimplemented in CModel.
Definition at line 131 of file CModelValue.cpp.
References CAnnotation::getKey().
Referenced by CModelAdd::addCompartments(), CModelAdd::addCompartmentsExpressions(), CModelAdd::addMetabolites(), CModelAdd::addMetabolitesExpressions(), CModelAdd::addModelValues(), CModelAdd::addModelValuesExpressions(), CModelAdd::addReactions(), CFixLocalReactionParameters::changeModel(), CQCompartment::copy(), CLayoutInitializer::createCompartmentGlyph(), CMathObject::createExtensiveReactionRateExpression(), CCopasiSpringLayout::createLayout(), CLayoutInitializer::createMetabGlyph(), test000097::createModel(), CSBMLExporter::createSBMLDocument(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CODEExporter::exportExpression(), CODEExporter::exportKineticFunction(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportODEs(), CODEExporterBM::exportSingleCompartment(), CODEExporterXPPAUT::exportSingleCompartment(), CODEExporterC::exportSingleCompartment(), CODEExporterBM::exportSingleMetabolite(), CODEExporterXPPAUT::exportSingleMetabolite(), CODEExporterC::exportSingleMetabolite(), CODEExporterBM::exportSingleModelEntity(), CODEExporterXPPAUT::exportSingleModelEntity(), CODEExporterC::exportSingleModelEntity(), CODEExporterBM::exportSingleModVal(), CODEExporterXPPAUT::exportSingleModVal(), CODEExporterC::exportSingleModVal(), CODEExporterBM::exportSingleODE(), CODEExporterXPPAUT::exportSingleODE(), CODEExporterC::exportSingleODE(), CQSelectionWizardPage::fillTree(), getMetabGlyphForKey(), CMetabNameInterface::getMetaboliteKey(), CEFMTask::getSpeciesChanges(), SBMLImporter::importMIRIAM(), CCopasiSpringLayout::initFromLayout(), CQGlobalQuantityDM::insertRows(), CQCompartmentDM::insertRows(), CQSpecieDM::insertRows(), CODEExporterC::KineticFunction2ODEmember(), CModelMerging::mergeMetabolites(), CODEExporterC::preprocess(), CODEExporter::preprocess(), CCopasiSpringLayout::randomize(), CModelExpansion::replaceInReaction(), CCopasiXML::saveModel(), CQNewMainWindow::selectMetabolite(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), CChemEq::setMultiplicity(), CModelMerging::simpleCall(), CModelExpansion::simpleCall(), CQEventWidget1::slotAddTarget(), CQSpeciesDetail::slotBtnNew(), CQCompartment::slotBtnNew(), CQModelValue::slotBtnNew(), CQEventWidget1::slotSelectObject(), CCopasiXMLParser::SourceParameterElement::start(), CCopasiXMLParser::ModifierElement::start(), CCopasiXMLParser::ProductElement::start(), CCopasiXMLParser::SubstrateElement::start(), CCopasiXMLParser::AssignmentElement::start(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000087::test_simulate_reaction_flux_reference_1(), CSBMLExporter::updateMIRIAMAnnotation(), and CMMLOutput::writeRHS().
 {
   return CAnnotation::getKey();
 }
const C_FLOAT64 & CModelEntity::getRate () const
Return rate of production of this entity
Definition at line 362 of file CModelValue.cpp.
References mRate.
Referenced by CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CQCompartment::load(), CQModelValue::load(), operator<<(), CMetab::refreshConcentrationRate(), and CQSpeciesDetail::setFramework().
 {
   return mRate;
 }
CCopasiObject * CModelEntity::getRateReference () const
Retrieve object referencing the rate
Returns
CCopasiObject * rateReference
Definition at line 373 of file CModelValue.cpp.
References mpRateReference.
Referenced by CMetab::compile(), CMathObject::createIntensiveRateExpression(), findObjectByDisplayName(), CMathContainer::initializeObjects(), and CQSimpleSelectionTree::populateTree().
 {return mpRateReference;}
const std::string & CModelEntity::getSBMLId () const
Returns a reference to the SBML Id.
Definition at line 637 of file CModelValue.cpp.
References mSBMLId.
Referenced by SBMLImporter::applyStoichiometricExpressions(), CSBMLExporter::collectIds(), CSBMLExporter::createCompartment(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createKineticLaw(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CSBMLExporter::createReaction(), CSBMLExporter::createRule(), CSBMLExporter::createRules(), CSBMLExporter::createSBMLDocument(), CSBMLExporter::createTimesTree(), SBMLImporter::replaceObjectNames(), CCopasiXML::saveModel(), test000055::test_bug1004(), test000057::test_bug1006(), test000103::test_bug1743_l2(), test000103::test_bug1743_l3(), and CEvaluationNodeObject::toAST().
 {
   return this->mSBMLId;
 }
const CModelEntity::Status & CModelEntity::getStatus () const
Retrieve the status of the entity.
Returns
const CModelEntity::Status & status
Definition at line 141 of file CModelValue.cpp.
References mStatus.
Referenced by CModelAdd::addCompartments(), CModelAdd::addMetabolites(), CModelAdd::addModelValues(), CModel::buildInitialRefreshSequence(), CMetab::calculate(), CLNAMethod::calculateCovarianceMatrixReduced(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CSBMLExporter::checkForPiecewiseFunctions(), CEventAssignment::compile(), CMetab::compile(), CMetab::compileInitialValueDependencies(), CFunctionAnalyzer::constructCallParametersActualValues(), CModel::convert2NonReversible(), CSBMLExporter::createCompartment(), CCopasiSpringLayout::createLayout(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CSBMLExporter::createRule(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CODEExporter::exportCompartments(), CODEExporter::exportExpression(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValues(), CODEExporter::exportModelValuesExpressions(), CODEExporter::exportODEs(), CODEExporterBM::exportSingleCompartment(), CODEExporterXPPAUT::exportSingleCompartment(), CODEExporterC::exportSingleCompartment(), CODEExporterBM::exportSingleMetabolite(), CODEExporterXPPAUT::exportSingleMetabolite(), CODEExporterC::exportSingleMetabolite(), CODEExporterBM::exportSingleModelEntity(), CODEExporterXPPAUT::exportSingleModelEntity(), CODEExporterC::exportSingleModelEntity(), CODEExporterBM::exportSingleModVal(), CODEExporterXPPAUT::exportSingleModVal(), CODEExporterC::exportSingleModVal(), CQSimpleSelectionTree::filter(), CParticleReference::getDirectDependencies(), SBMLImporter::importRuleForModelEntity(), CSteadyStateTask::initialize(), CMathContainer::initializeObjects(), CSBMLExporter::isEventAssignmentSBMLCompatible(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CParticleReference::isPrerequisiteForContext(), CQSpeciesDetail::load(), CQCompartment::load(), CQModelValue::load(), CQUpdatesWidget::loadObjectsTable(), CModelMerging::mergeMetabolites(), CMetab::mustBeDeleted(), operator<<(), CQSimpleSelectionTree::populateTree(), CODEExporterC::preprocess(), CODEExporter::preprocess(), CMetab::refreshRate(), CMetab::refreshTransitionTime(), SBMLImporter::removeUnusedFunctions(), CSBMLExporter::replaceSpeciesReferences(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), CCopasiXML::saveModel(), CQSpeciesDetail::setFramework(), CMetab::setObjectParent(), CMetab::setStatus(), CHybridMethodODE45::setupBalances(), CHybridMethod::setupBalances(), CHybridMethodLSODA::setupBalances(), CHybridMethodODE45::setupMetab2React(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethodDsaLsodar::start(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000040::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000087::test_import_reaction_flux_reference_2(), test000075::test_import_time_dependent_function_definition(), CSteadyStateTask::updateMatrices(), CModelParameter::updateModel(), and ParameterTable::updateTable().
 {return mStatus;}
const C_FLOAT64 & CModelEntity::getValue () const
Retrieve the value
Definition at line 136 of file CModelValue.cpp.
References mpValue.
Referenced by CMetab::calculate(), CModel::calculateElasticityMatrix(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CHybridMethod::fireReaction(), CHybridMethodLSODA::fireReaction(), CHybridMethodODE45::fireReaction(), CTSSAMethod::initializeAtol(), CSteadyStateMethod::isEquilibrium(), CQCompartment::load(), CQModelValue::load(), operator<<(), CMetab::refreshConcentration(), CMetab::refreshConcentrationRate(), CMetab::refreshNumber(), CSBMLExporter::replaceSpeciesReferences(), CMCAMethod::scaleMCA(), CQSpeciesDetail::setFramework(), CNewtonMethod::solveJacobianXeqB(), and CNewtonMethod::targetFunction().
 {return *mpValue;}
const CCopasiObject * CModelEntity::getValueObject () const virtual
Retrieve the object representing the value;
Reimplemented from CCopasiContainer.
Reimplemented in CMetab.
Definition at line 484 of file CModelValue.cpp.
References mpValueReference.
Referenced by CEventAssignment::compile().
 {
   return mpValueReference;
 }
void * CModelEntity::getValuePointer () const virtual
Retrieve a pointer to the value;
Reimplemented from CCopasiObject.
Reimplemented in CMetab.
Definition at line 490 of file CModelValue.cpp.
References C_FLOAT64, and mpValue.
Referenced by CReaction::setScalingFactor().
 {
   return const_cast<C_FLOAT64 *>(mpValue);
 }
CCopasiObject * CModelEntity::getValueReference () const
Retrieve object referencing the value
Returns
CCopasiObject * valueReference
Definition at line 370 of file CModelValue.cpp.
References mpValueReference.
Referenced by CMathModel::buildDependendRefreshList(), CMetab::compile(), CPlotSpecification::createDefaultPlot(), CMathObject::createExtensiveODERateExpression(), CMathObject::createExtensiveValueExpression(), CExpression::createInitialExpression(), CMathObject::createIntensiveRateExpression(), CMathObject::createIntensiveValueExpression(), CSBMLExporter::createRule(), CSBMLExporter::exportEventAssignments(), findObjectByDisplayName(), CModel::getCorrespondingTransientObject(), SBMLImporter::importEvent(), SBMLImporter::importRuleForModelEntity(), CMathContainer::initializeObjects(), CQSimpleSelectionTree::populateTree(), CReaction::setScalingFactor(), CMetab::setStatus(), CHybridMethodODE45::setupMetab2React(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), and CTrajectoryMethodDsaLsodar::start().
 {return mpValueReference;}
void CModelEntity::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 495 of file CModelValue.cpp.
References CStateTemplate::add(), CCopasiContainer::addObjectReference(), C_FLOAT64, CCopasiObject::getObjectAncestor(), CModel::getStateTemplate(), mpIValueReference, mpModel, mpRateReference, mpValueReference, mRate, mSBMLId, refreshInitialValue(), setInitialValue(), setInitialValuePtr(), CCopasiObject::setRefresh(), CCopasiObject::setUpdateMethod(), setValue(), setValuePtr(), CCopasiObject::ValueDbl, and CCopasiObject::ValueString.
Referenced by CModelEntity().
 {
   C_FLOAT64 Dummy;
   mpValueReference =
     static_cast<CCopasiObjectReference<C_FLOAT64> *>(addObjectReference("Value",
         Dummy,
         CCopasiObject::ValueDbl));
   mpValueReference->setUpdateMethod(this, &CModelEntity::setValue);
   mpIValueReference =
     static_cast<CCopasiObjectReference<C_FLOAT64> *>(addObjectReference("InitialValue",
         Dummy,
         CCopasiObject::ValueDbl));
   mpIValueReference->setUpdateMethod(this, &CModelEntity::setInitialValue);
   mpIValueReference->setRefresh(this, &CModelEntity::refreshInitialValue);
   mpRateReference =
     static_cast<CCopasiObjectReference<C_FLOAT64> *>(addObjectReference("Rate", mRate, CCopasiObject::ValueDbl));
   addObjectReference("SBMLId", mSBMLId, CCopasiObject::ValueString);
   mpModel = static_cast<CModel *>(getObjectAncestor("Model"));
   if (mpModel)
     {
       mpModel->getStateTemplate().add(this);
     }
   else
     {
       // This creates the needed values.
       setInitialValuePtr(NULL);
       setValuePtr(NULL);
     }
 }
bool CModelEntity::isFixed () const inline
Check whether the entity is FIXED or not.
Returns
bool isFixed
Definition at line 124 of file CModelValue.h.
References FIXED, and mStatus.
Referenced by getExpression(), CMetab::refreshInitialConcentration(), CMetab::setConcentration(), setExpression(), and setExpressionPtr().
 {return mStatus == FIXED;}
const bool & CModelEntity::isUsed () const
Retrieve whether the model value is used during simulation
Returns
const bool & used
Definition at line 645 of file CModelValue.cpp.
References mUsed.
Referenced by CModel::buildUserOrder(), and CQUpdatesWidget::loadObjectsTable().
 {return mUsed;}
bool CModelEntity::mustBeDeleted (const DataObjectSet & deletedObjects) const virtual
Check whether an object must be deleted because its prerequisites can no longer be fulfilled due to the given deleted objects
Parameters
const DataObjectSet & deletedObjects
Returns
bool mustBeDeleted
Reimplemented from CCopasiObject.
Reimplemented in CMetab.
Definition at line 600 of file CModelValue.cpp.
References getDeletedObjects().
 {
   bool MustBeDeleted = false;
   DataObjectSet ChildObjects = getDeletedObjects();
   DataObjectSet::const_iterator it = ChildObjects.begin();
   DataObjectSet::const_iterator end = ChildObjects.end();
   for (; it != end; ++it)
     {
       if (*it == this)
         {
           if ((*it)->CCopasiObject::mustBeDeleted(deletedObjects))
             {
               MustBeDeleted = true;
               break;
             }
           continue;
         }
       if ((*it)->mustBeDeleted(deletedObjects))
         {
           MustBeDeleted = true;
           break;
         }
     }
   return MustBeDeleted;
 }
void CModelEntity::refreshInitialValue () virtual
Refresh the initial value
Reimplemented in CMetab.
Definition at line 214 of file CModelValue.cpp.
References CExpression::calcValue(), CEvaluationTree::getInfix(), mpInitialExpression, and mpIValue.
Referenced by initObjects().
 {
   if (mpInitialExpression != NULL &&
       mpInitialExpression->getInfix() != "")
     *mpIValue = mpInitialExpression->calcValue();
 }
bool CModelEntity::setExpression (const std::string & expression)
Set the expression for non FIXED model values
Parameters
const std::string & expression
Returns
bool success
Definition at line 221 of file CModelValue.cpp.
References compile(), isFixed(), mpExpression, mpModel, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by CModel::convert2NonReversible(), CModelAdd::copyExpression(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CQEventWidget1::loadFromEvent(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), test000058::test_bug1025_10(), test000058::test_bug1025_5(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), and test000059::test_unique_id_21_2().
 {
   if (isFixed()) return false;
   if (mpExpression == NULL)
     mpExpression = new CExpression("Expression", this);
   if (mpModel)
     mpModel->setCompileFlag(true);
   if (!mpExpression->setInfix(expression)) return false;
   return compile();
 }
bool CModelEntity::setExpressionPtr (CExpression * pExpression)
Set the expression for non FIXED model values
Parameters
CExpression*
Returns
bool success
Definition at line 255 of file CModelValue.cpp.
References CCopasiContainer::add(), compile(), isFixed(), mpExpression, mpModel, pdelete, CModel::setCompileFlag(), CCopasiObject::setObjectName(), and CCopasiObject::setObjectParent().
Referenced by SBMLImporter::importRuleForModelEntity().
 {
   if (isFixed()) return false;
   if (pExpression == mpExpression) return true;
   if (pExpression == NULL) return false;
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   CExpression * pOld = mpExpression;
   mpExpression = pExpression;
   mpExpression->setObjectName("Expression");
   add(mpExpression, true);
   if (compile())
     {
       pdelete(pOld);
       return true;
     }
   // If compile fails we do not take ownership
   // and we remove the object from the container
   remove(mpExpression);
   mpExpression->setObjectParent(NULL);
   mpExpression = pOld;
   return false;
 }
bool CModelEntity::setInitialExpression (const std::string & expression)
Set the expression for ODE or REACTION model values
Parameters
const std::string & expression
Returns
bool success
Definition at line 333 of file CModelValue.cpp.
References ASSIGNMENT, compile(), mpInitialExpression, mpModel, mStatus, CModel::setCompileFlag(), and CExpression::setInfix().
Referenced by CModel::convert2NonReversible(), CModelAdd::copyInitialExpression(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CCopasiXMLParser::ModelElement::end(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), CQMoietiesTaskResult::slotCreateGlobalQuantity(), and CModelParameter::updateModel().
 {
   if (mStatus == ASSIGNMENT) return false;
   if (mpModel)
     mpModel->setCompileFlag(true);
   if (mpInitialExpression == NULL)
     {
       mpInitialExpression = new CExpression("InitialExpression", this);
     }
   if (!mpInitialExpression->setInfix(expression)) return false;
   return compile();
 }
bool CModelEntity::setInitialExpressionPtr (CExpression * pExpression)
Set the expression for non FIXED model values
Parameters
CExpression*
Returns
bool success
Definition at line 299 of file CModelValue.cpp.
References CCopasiContainer::add(), ASSIGNMENT, compile(), mpInitialExpression, mpModel, mStatus, pdelete, CModel::setCompileFlag(), CCopasiObject::setObjectName(), and CCopasiObject::setObjectParent().
Referenced by SBMLImporter::importInitialAssignments().
 {
   if (mStatus == ASSIGNMENT) return false;
   if (pExpression == mpInitialExpression) return true;
   if (pExpression == NULL) return false;
   if (mpModel != NULL)
     {
       mpModel->setCompileFlag(true);
     }
   CExpression * pOld = mpInitialExpression;
   mpInitialExpression = pExpression;
   mpInitialExpression->setObjectName("InitialExpression");
   add(mpInitialExpression, true);
   if (compile())
     {
       pdelete(pOld);
       return true;
     }
   // If compile fails we do not take ownership
   // and we remove the object from the container
   remove(mpInitialExpression);
   mpInitialExpression->setObjectParent(NULL);
   mpInitialExpression = pOld;
   return false;
 }
void CModelEntity::setInitialValue (const C_FLOAT64 & initialValue) virtual
Set the initial value
Parameters
const C_FLOAT64 & initialValue
Definition at line 383 of file CModelValue.cpp.
References mpIValue.
Referenced by CModel::createCompartment(), CModel::createModelValue(), CModel::determineIsAutonomous(), initObjects(), CCompartment::load(), CMetab::operator=(), CQSpeciesDetail::save(), CQCompartment::save(), CQModelValue::save(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), CQSpeciesDetail::slotBtnNew(), and CModelParameter::updateModel().
 {
   *mpIValue = initialValue;
 }
void CModelEntity::setInitialValuePtr (C_FLOAT64 * pInitialValue)
Set the pointer to the initial value
Parameters
C_FLOAT64 * pInitialValue
Definition at line 531 of file CModelValue.cpp.
References C_FLOAT64, mpIValue, mpIValueReference, and CCopasiObjectReference< CType >::setReference().
Referenced by CStateTemplate::add(), initObjects(), and CStateTemplate::remove().
 {
   mpIValue = pInitialValue;
   if (!mpIValue) mpIValue = new C_FLOAT64;
   mpIValueReference->setReference(*mpIValue);
 }
bool CModelEntity::setObjectParent (const CCopasiContainer * pParent) virtual
Set the object parent
Parameters
const CCopasiContainer * pParent
Returns
bool success
Reimplemented from CCopasiObject.
Reimplemented in CMetab.
Definition at line 549 of file CModelValue.cpp.
References CStateTemplate::add(), C_FLOAT64, CCopasiObject::getObjectAncestor(), CModel::getStateTemplate(), mpIValue, mpModel, mpValue, pdelete, CStateTemplate::remove(), and CCopasiObject::setObjectParent().
Referenced by CCopasiDataModel::commonAfterLoad(), and CMetab::setObjectParent().
 {
   CCopasiContainer::setObjectParent(pParent);
   CModel * pNewModel = static_cast<CModel *>(getObjectAncestor("Model"));
   if (mpModel == pNewModel) return true;
   C_FLOAT64 InitialValue = *mpIValue;
   C_FLOAT64 Value = *mpValue;
   if (mpModel)
     {
       // This allocates new objects for mpIValue and mpValueData
       mpModel->getStateTemplate().remove(this);
     }
   // We can safely remove the currently allocated objects as they
   // are not part of an CStateTemplate
   pdelete(mpIValue);
   pdelete(mpValue);
   if (pNewModel)
     {
       pNewModel->getStateTemplate().add(this);
     }
   else
     {
       mpValue = new C_FLOAT64;
       mpIValue = new C_FLOAT64;
     }
   mpModel = pNewModel;
   *mpIValue = InitialValue;
   *mpValue = Value;
   return true;
 }
void CModelEntity::setRate (const C_FLOAT64 & rate)
Set the rate (dmValue/dt)
Parameters
const C_FLOAT64 & rate
Definition at line 388 of file CModelValue.cpp.
References mRate.
 {
   mRate = rate;
 }
void CModelEntity::setSBMLId (const std::string & id)
Sets the SBMLId.
Definition at line 632 of file CModelValue.cpp.
References mSBMLId.
Referenced by SBMLImporter::createCCompartmentFromCompartment(), SBMLImporter::createCMetabFromSpecies(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCModelValueFromParameter(), CSBMLExporter::createCompartment(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CCopasiXMLParser::SBMLMapElement::start(), test000103::test_bug1743_l2(), and test000103::test_bug1743_l3().
 {
   this->mSBMLId = id;
 }
void CModelEntity::setStatus (const CModelEntity::Status & status) virtual
Set the status
Parameters
const CModelEntity::Status & status
Reimplemented in CMetab.
Definition at line 395 of file CModelValue.cpp.
References CCopasiContainer::add(), ASSIGNMENT, calculate(), CCopasiObject::clearRefresh(), CExpression::createInitialExpression(), FIXED, CCopasiObject::getDirectDependencies(), CCopasiObject::getObjectDataModel(), mpExpression, mpInitialExpression, mpIValueReference, mpModel, mpRateReference, mpValue, mpValueReference, mRate, mStatus, mUsed, ODE, pdelete, REACTIONS, CModel::setCompileFlag(), CCopasiObject::setDirectDependencies(), CCopasiObject::setObjectName(), CCopasiObject::setRefresh(), setValuePtr(), and TIME.
Referenced by CModelAdd::addCompartments(), CModelAdd::addModelValues(), CCompartment::CCompartment(), CModel::CModel(), CModelEntity(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateGlobalQuantity(), SBMLImporter::importRuleForModelEntity(), CQCompartment::save(), CQModelValue::save(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CMetab::setStatus(), test000058::test_bug1025_10(), test000058::test_bug1025_5(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), and test000059::test_unique_id_21_2().
 {
   if (mStatus != status)
     {
       if (mpModel != NULL)
         mpModel->setCompileFlag(true);
       // An assignment may not have an initial expression.
       // However, internally we always create one, which need
       // to be deleted.
       if (mStatus == ASSIGNMENT)
         pdelete(mpInitialExpression);
       mStatus = status;
       this->setValuePtr(mpValue);
       if (mpModel != NULL)
         mpModel->setCompileFlag(true);
       std::set< const CCopasiObject * > NoDependencies;
       setDirectDependencies(NoDependencies);
       clearRefresh();
       mpIValueReference->setDirectDependencies(NoDependencies);
       mpValueReference->setDirectDependencies(NoDependencies);
       mpValueReference->clearRefresh();
       mpRateReference->setDirectDependencies(NoDependencies);
       mpRateReference->clearRefresh();
       CCopasiDataModel* pDataModel = NULL;
       switch (mStatus)
         {
           case ASSIGNMENT:
             if (mpExpression == NULL)
               mpExpression = new CExpression("Expression", this);
             pdelete(mpInitialExpression);
             pDataModel = getObjectDataModel();
             mpInitialExpression = CExpression::createInitialExpression(*mpExpression, pDataModel);
             mpInitialExpression->setObjectName("InitialExpression");
             add(mpInitialExpression, true);
             mpValueReference->setDirectDependencies(mpExpression->getDirectDependencies());
             mpValueReference->setRefresh(this, &CModelEntity::calculate);
             mRate = std::numeric_limits<C_FLOAT64>::quiet_NaN();
             mUsed = true;
             break;
           case ODE:
             if (mpExpression == NULL)
               mpExpression = new CExpression("Expression", this);
             mpRateReference->setDirectDependencies(mpExpression->getDirectDependencies());
             mpRateReference->setRefresh(this, &CModelEntity::calculate);
             mUsed = true;
             break;
           case REACTIONS:
             pdelete(mpExpression);
             mUsed = true;
             break;
           case TIME:
             pdelete(mpExpression);
             mUsed = true;
             break;
           case FIXED:
             pdelete(mpExpression);
             mRate = 0.0;
             mUsed = false;
             break;
         }
     }
 }
void CModelEntity::setUsed (const bool & used)
Set whether the model entity is used during simulation
Parameters
const bool & used
Definition at line 642 of file CModelValue.cpp.
References mUsed.
Referenced by CModel::buildStateTemplate(), and CModel::CModel().
 {mUsed = used;}
void CModelEntity::setValue (const C_FLOAT64 & value) virtual
Set the value
Parameters
const C_FLOAT64 & value
Definition at line 378 of file CModelValue.cpp.
References mpValue.
Referenced by CHybridMethod::fireReaction(), CHybridMethodLSODA::fireReaction(), CHybridMethodODE45::fireReaction(), initObjects(), CQSpecieDM::setData(), and CStochMethod::updateSystemState().
 {
   *mpValue = value;
 }
void CModelEntity::setValuePtr (C_FLOAT64 * pValue)
Set the pointer to the value
Parameters
C_FLOAT64 * pValue
Definition at line 540 of file CModelValue.cpp.
References C_FLOAT64, mpValue, mpValueReference, and CCopasiObjectReference< CType >::setReference().
Referenced by CStateTemplate::add(), initObjects(), CStateTemplate::remove(), and setStatus().
 {
   mpValue = pValue;
   if (!mpValue) mpValue = new C_FLOAT64;
   mpValueReference->setReference(*mpValue);
 }
Member Data Documentation
CExpression* CModelEntity::mpExpression protected
The infix expression for objects of type ASSIGNMENT or ODE
Definition at line 336 of file CModelValue.h.
Referenced by calculate(), CMetab::calculate(), compile(), CMetab::compile(), getExpression(), getExpressionPtr(), setExpression(), setExpressionPtr(), setStatus(), and CMetab::setStatus().
CExpression* CModelEntity::mpInitialExpression protected
Optional initial expression
Definition at line 341 of file CModelValue.h.
Referenced by compile(), CMetab::compile(), CMetab::compileInitialValueDependencies(), getInitialExpression(), getInitialExpressionPtr(), CMetab::refreshInitialConcentration(), refreshInitialValue(), setInitialExpression(), setInitialExpressionPtr(), and setStatus().
C_FLOAT64* CModelEntity::mpIValue protected
Pointer to the initial value of the model entity.
Definition at line 326 of file CModelValue.h.
Referenced by CCompartment::CCompartment(), CModel::CModel(), CModelEntity(), compile(), CModel::getInitialTime(), getInitialValue(), CModel::initObjects(), CModel::load(), operator<<(), CMetab::refreshInitialConcentration(), refreshInitialValue(), CMetab::refreshInitialValue(), CModel::setInitialTime(), setInitialValue(), setInitialValuePtr(), setObjectParent(), CModel::~CModel(), and ~CModelEntity().
CCopasiObjectReference<C_FLOAT64>* CModelEntity::mpIValueReference protected
Definition at line 356 of file CModelValue.h.
Referenced by CMoiety::add(), compile(), CMetab::compileInitialValueDependencies(), CMetab::compileIsInitialConcentrationChangeAllowed(), CCompartment::getChildObjectUnits(), CMetab::getChildObjectUnits(), getDeletedObjects(), getInitialValueReference(), CCompartment::initObjects(), initObjects(), CMetab::initObjects(), CModel::initObjects(), setInitialValuePtr(), and setStatus().
CModel* CModelEntity::mpModel protected
Definition at line 359 of file CModelValue.h.
Referenced by CMetab::calculate(), compile(), CMetab::compile(), CCompartment::getChildObjectUnits(), CMetab::getChildObjectUnits(), CMetab::getModel(), initObjects(), operator<<(), CMetab::operator=(), CMetab::refreshConcentration(), CMetab::refreshConcentrationRate(), CMetab::refreshInitialConcentration(), CMetab::refreshInitialValue(), CMetab::refreshNumber(), setExpression(), setExpressionPtr(), setInitialExpression(), setInitialExpressionPtr(), setObjectParent(), setStatus(), CMetab::setStatus(), and ~CModelEntity().
CCopasiObjectReference<C_FLOAT64>* CModelEntity::mpRateReference protected
Definition at line 358 of file CModelValue.h.
Referenced by compile(), CMetab::compile(), CCompartment::getChildObjectUnits(), CMetab::getChildObjectUnits(), getDeletedObjects(), getRateReference(), initObjects(), CMetab::initObjects(), CMetab::mustBeDeleted(), setStatus(), and CMetab::setStatus().
C_FLOAT64* CModelEntity::mpValue protected
Pointer to the value of the model entity.
Definition at line 321 of file CModelValue.h.
Referenced by calculate(), CMetab::calculate(), CModel::CModel(), CModelEntity(), CModel::getTime(), getValue(), getValuePointer(), CModel::initObjects(), operator<<(), CMetab::refreshConcentration(), CMetab::refreshNumber(), CMetab::refreshTransitionTime(), setObjectParent(), setStatus(), CModel::setTime(), setValue(), setValuePtr(), CModel::~CModel(), and ~CModelEntity().
CCopasiObjectReference<C_FLOAT64>* CModelEntity::mpValueReference protected
Definition at line 357 of file CModelValue.h.
Referenced by CMoiety::add(), compile(), CMetab::compile(), CModel::compile(), CCompartment::getChildObjectUnits(), CMetab::getChildObjectUnits(), getDeletedObjects(), getValueObject(), getValueReference(), CCompartment::initObjects(), initObjects(), CMetab::initObjects(), CModel::initObjects(), setStatus(), CMetab::setStatus(), and setValuePtr().
C_FLOAT64 CModelEntity::mRate protected
Rate of change/time.
Definition at line 331 of file CModelValue.h.
Referenced by calculate(), CMetab::calculate(), CMetab::compile(), getRate(), initObjects(), CModel::initObjects(), operator<<(), CMetab::operator=(), CMetab::refreshConcentrationRate(), CMetab::refreshRate(), CMetab::refreshTransitionTime(), setRate(), and setStatus().
std::string CModelEntity::mSBMLId protected
The id of the corresponding parameter in an SBML file. This value is either set upon importing an SBML file, or when the object is first exported to an SBML file.
Definition at line 47 of file CModelValue.h.
Referenced by getSBMLId(), initObjects(), and setSBMLId().
Status CModelEntity::mStatus private
Status of the model entity.
Definition at line 347 of file CModelValue.h.
Referenced by calculate(), CModelEntity(), compile(), getInitialExpression(), getStatus(), isFixed(), setInitialExpression(), setInitialExpressionPtr(), and setStatus().
bool CModelEntity::mUsed private
Indicates whether the model value is used, i.e., must be calculated during the simulation
Definition at line 353 of file CModelValue.h.
Referenced by isUsed(), setStatus(), and setUsed().
const std::string CModelEntity::StatusName static
Initial value:
=
{
  "fixed",
  "assignment",
  "reactions",
  "ode",
  "time",
  ""
}
String representation of the states
Definition at line 67 of file CModelValue.h.
Referenced by CQCompartment::CQCompartment(), CQCompartmentDM::CQCompartmentDM(), CQGlobalQuantityDM::CQGlobalQuantityDM(), CQSpecieDM::CQSpecieDM(), CQSpeciesDetail::CQSpeciesDetail(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CODEExporter::exportCompartments(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValues(), CQGlobalQuantityDM::flags(), CQCompartmentDM::flags(), CQSpecieDM::flags(), CQModelValue::init(), CQSpeciesDetail::load(), CQCompartment::load(), CQModelValue::load(), StateSubwidget::loadCompartments(), StateSubwidget::loadMetabolites(), StateSubwidget::loadModelValues(), CQUpdatesWidget::loadObjectsTable(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), and CQParameterOverviewDM::typeData().
const char * CModelEntity::XMLStatus static
Initial value:
=
{
  "fixed",
  "assignment",
  "reactions",
  "ode",
  "time",
  NULL
}
XML representation of the states
Definition at line 72 of file CModelValue.h.
Referenced by CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), CCopasiXMLParser::ModelParameterElement::start(), CCopasiXMLParser::MetaboliteElement::start(), CCopasiXMLParser::CompartmentElement::start(), and CCopasiXMLParser::ModelValueElement::start().
The documentation for this class was generated from the following files:
CModelValue.h
CModelValue.cpp