COPASI API: CModelParameterCompartment Class Reference
CModelParameterCompartment Class Reference
#include <CModelParameter.h>
Public Member Functions
void addSpecies (CModelParameterSpecies *pSpecies)
CModelParameterCompartment (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::Compartment)
CModelParameterCompartment (const CModelParameterCompartment &src, CModelParameterGroup *pParent)
void removeSpecies (CModelParameterSpecies *pSpecies)
virtual void setValue (const C_FLOAT64 &value, const Framework &framework)
virtual ~CModelParameterCompartment ()
Public Member Functions inherited from CModelParameter
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
virtual void compile ()
virtual const CompareResult & diff (const CModelParameter &other, const CModelParameter::Framework &framework=ParticleNumbers, const bool &createMissing=false)
virtual const CModelParameter * getChild (const size_t &index) const
const CCopasiObjectName & getCN () const
const CompareResult & getCompareResult () const
size_t getIndex () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
virtual std::string getName () const
virtual size_t getNumChildren () const
CCopasiObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
const std::string getUnit (const Framework &framework) const
virtual const double & getValue (const Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
virtual bool refreshFromModel (const bool &modifyExistence)
virtual void setCN (const CCopasiObjectName &cn)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const double &value, const Framework &framework)
virtual bool updateModel ()
virtual ~CModelParameter ()
Private Attributes
std::set
< CModelParameterSpecies * > mSpecies
Additional Inherited Members
Public Types inherited from CModelParameter
enum CompareResult {
Obsolete, Missing, Modified, Conflict,
Identical
}
enum Framework { Concentration = 0, ParticleNumbers }
enum Type {
Model, Compartment, Species, ModelValue,
ReactionParameter, Reaction, Group, Set,
unknown
}
Static Public Attributes inherited from CModelParameter
static const char * TypeNames []
Static Protected Member Functions inherited from CModelParameter
static std::string nameFromCN (const CCopasiObjectName &cn)
Protected Attributes inherited from CModelParameter
CRegisteredObjectName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CCopasiObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Detailed Description
Definition at line 310 of file CModelParameter.h.
Constructor & Destructor Documentation
CModelParameterCompartment::CModelParameterCompartment (CModelParameterGroup * pParent, const CModelParameter::Type & type = CModelParameter::Compartment)
Constructor
Definition at line 678 of file CModelParameter.cpp.
                                                                                                                       :
   CModelParameter(pParent, type),
   mSpecies()
 {}
CModelParameterCompartment::CModelParameterCompartment (const CModelParameterCompartment & src, CModelParameterGroup * pParent)
Copy constructor
Definition at line 683 of file CModelParameter.cpp.
                                                                                                                             :
   CModelParameter(src, pParent),
   mSpecies()
 {}
CModelParameterCompartment::~CModelParameterCompartment () virtual
Destructor
Definition at line 689 of file CModelParameter.cpp.
References mSpecies.
 {
   // If a compartment is deleted all contained species are not deleted however
   // their compartment is set to NULL.
   std::set< CModelParameterSpecies * >::iterator it = mSpecies.begin();
   std::set< CModelParameterSpecies * >::iterator end = mSpecies.end();
   for (; it != end; ++it)
     {
       (*it)->mpCompartment = NULL;
     }
 }
Member Function Documentation
void CModelParameterCompartment::addSpecies (CModelParameterSpecies * pSpecies)
Add a pointer to a species parameter to the compartment
Definition at line 727 of file CModelParameter.cpp.
References mSpecies.
Referenced by CModelParameterSpecies::compile().
 {
   mSpecies.insert(pSpecies);
 }
void CModelParameterCompartment::removeSpecies (CModelParameterSpecies * pSpecies)
Remove a pointer to a species parameter from the compartment
Definition at line 732 of file CModelParameter.cpp.
References mSpecies.
Referenced by CModelParameterSpecies::~CModelParameterSpecies().
 {
   mSpecies.erase(pSpecies);
 }
void CModelParameterCompartment::setValue (const C_FLOAT64 & value, const Framework & framework) virtual
Set the value of the parameter based on the current framework
Parameters
const double & value
const Framework & framework
Definition at line 703 of file CModelParameter.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, mSpecies, and CModelParameter::mValue.
 {
   CVector< C_FLOAT64 > SpeciesValues(mSpecies.size());
   C_FLOAT64 * pSpeciesValue = SpeciesValues.array();
   std::set< CModelParameterSpecies * >::iterator it = mSpecies.begin();
   std::set< CModelParameterSpecies * >::iterator end = mSpecies.end();
   for (; it != end; ++it, ++pSpeciesValue)
     {
       *pSpeciesValue = (*it)->getValue(framework);
     }
   mValue = value;
   pSpeciesValue = SpeciesValues.array();
   it = mSpecies.begin();
   for (; it != end; ++it, ++pSpeciesValue)
     {
       (*it)->setValue(*pSpeciesValue, framework);
     }
 }
Member Data Documentation
std::set< CModelParameterSpecies * > CModelParameterCompartment::mSpecies private
The set of species parameters which are contained in the compartment
Definition at line 350 of file CModelParameter.h.
Referenced by addSpecies(), removeSpecies(), setValue(), and ~CModelParameterCompartment().
The documentation for this class was generated from the following files:
CModelParameter.h
CModelParameter.cpp