COPASI API: CCopasiXMLParser::CompartmentElement Class Reference
CCopasiXMLParser::CompartmentElement Class Reference
Public Member Functions
CompartmentElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~CompartmentElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Compartment = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
Expression, InitialExpression
}
Private Attributes
std::string mKey
CCompartment * mpCompartment
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1343 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::CompartmentElement::Element private
Enum of invoked parsers
Enumerator
Compartment
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
Expression
InitialExpression
Definition at line 1351 of file CCopasiXMLParser.h.
     {
       Compartment = 0,
       MiriamAnnotation,
       Comment,
       ListOfUnsupportedAnnotations,
       Expression,
       InitialExpression
     };
Constructor & Destructor Documentation
CCopasiXMLParser::CompartmentElement::CompartmentElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 2236 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpCompartment(NULL)
 {}
CCopasiXMLParser::CompartmentElement::~CompartmentElement () virtual
Destructor
Definition at line 2242 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::CompartmentElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 2339 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Compartment:
         if (strcmp(pszName, "Compartment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Compartment", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         mpCompartment->setMiriamAnnotation(mCommon.CharacterData, mpCompartment->getKey(), mKey);
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         mpCompartment->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         mpCompartment->getUnsupportedAnnotations() = mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case Expression:
         if (strcmp(pszName, "Expression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Expression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpCompartment->setExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case InitialExpression:
         if (strcmp(pszName, "InitialExpression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialExpression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpCompartment->setInitialExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case UNKNOWN_ELEMENT:
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   mCurrentElement = Compartment;
   return;
 }
void CCopasiXMLParser::CompartmentElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 2245 of file CCopasiXMLParser.cpp.
References CCopasiVectorN< CType >::add(), CCopasiMessage::EXCEPTION, CModelEntity::FIXED, CModel::getCompartments(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, strToUnsignedInt(), toEnum(), UNKNOWN_ELEMENT, and CModelEntity::XMLStatus.
 {
   const char * Name;
   const char * simulationType;
   const char * Dimensionality;
   CModelEntity::Status SimulationType;
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case Compartment:
             if (strcmp(pszName, "Compartment"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "Compartment", mParser.getCurrentLineNumber());
             mKey = mParser.getAttributeValue("key", papszAttrs);
             Name = mParser.getAttributeValue("name", papszAttrs);
             simulationType = mParser.getAttributeValue("simulationType", papszAttrs, "fixed");
             SimulationType = toEnum(simulationType, CModelEntity::XMLStatus, CModel::FIXED);
             Dimensionality = mParser.getAttributeValue("dimensionality", papszAttrs, "3");
             mpCompartment = new CCompartment();
             addFix(mKey, mpCompartment);
             mpCompartment->setObjectName(Name);
             mpCompartment->setStatus(SimulationType);
             mpCompartment->setDimensionality(strToUnsignedInt(Dimensionality));
             mCommon.pModel->getCompartments().add(mpCompartment, true);
             mLastKnownElement = Compartment;
             return;
           case MiriamAnnotation:
             if (!strcmp(pszName, "MiriamAnnotation"))
               mpCurrentHandler = &mParser.mMiriamAnnotationElement;
             break;
           case Comment:
             if (!strcmp(pszName, "Comment"))
               mpCurrentHandler = &mParser.mCommentElement;
             break;
           case ListOfUnsupportedAnnotations:
             if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
               mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             break;
           case Expression:
             if (!strcmp(pszName, "Expression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           case InitialExpression:
             if (!strcmp(pszName, "InitialExpression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::CompartmentElement::mKey private
The key in the CopasiML file
Definition at line 1397 of file CCopasiXMLParser.h.
CCompartment* CCopasiXMLParser::CompartmentElement::mpCompartment private
A pointer to the current compartment
Definition at line 1392 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp