COPASI API: test000071 Class Reference
test000071 Class Reference
#include <test000071.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1085 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1085)
CPPUNIT_TEST_SUITE (test000071)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 26 of file test000071.h.
Member Function Documentation
test000071::CPPUNIT_TEST (test_bug1085) private
test000071::CPPUNIT_TEST_SUITE (test000071) private
test000071::CPPUNIT_TEST_SUITE_END () private
void test000071::setUp ()
Definition at line 44 of file test000071.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000071::tearDown ()
Definition at line 52 of file test000071.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000071::test_bug1085 ()
Definition at line 57 of file test000071.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), load_cps_model_from_stream(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000071::MODEL_STRING1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   std::string sbmlString = pDataModel->exportSBMLToString(NULL, 2, 1);
   CPPUNIT_ASSERT(!sbmlString.empty());
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(sbmlString));
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   const Model* pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   // check if there is one function defintition
   CPPUNIT_ASSERT(pSBMLModel->getListOfFunctionDefinitions()->size() == 1);
   const FunctionDefinition* pFunDef = pSBMLModel->getFunctionDefinition(0);
   CPPUNIT_ASSERT(pFunDef != NULL);
   CPPUNIT_ASSERT(pFunDef->getName() == "sqrt_call");
   const ASTNode* pMath = pFunDef->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   // the last child should be the actual function expression
   pMath = pMath->getChild(pMath->getNumChildren() - 1);
   CPPUNIT_ASSERT(pMath != NULL);
   // check that the root node is a root function call
   CPPUNIT_ASSERT(pMath->getType() == AST_FUNCTION_ROOT);
   // the root function can have either one or two arguments
   // if there are two arguments the first one is the degree and needs to be 2
   // since we have a sqrt call
   CPPUNIT_ASSERT(pMath->getNumChildren() == 1 || pMath->getNumChildren() == 2);
   if (pMath->getNumChildren() == 2)
     {
       CPPUNIT_ASSERT(pMath->getChild(0) != NULL);
       CPPUNIT_ASSERT(pMath->getChild(0)->getType() == AST_INTEGER);
       CPPUNIT_ASSERT(pMath->getChild(0)->getInteger() == 2);
       pMath = pMath->getChild(1);
       CPPUNIT_ASSERT(pMath != NULL);
       CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getName() == std::string("k"));
     }
   else if (pMath->getNumChildren() == 1)
     {
       pMath = pMath->getChild(0);
       CPPUNIT_ASSERT(pMath != NULL);
       CPPUNIT_ASSERT(pMath->getType() == AST_NAME);
       CPPUNIT_ASSERT(pMath->getName() == std::string("k"));
     }
 }
Member Data Documentation
const char * test000071::MODEL_STRING1 static protected
Definition at line 33 of file test000071.h.
Referenced by test_bug1085().
CCopasiDataModel * test000071::pCOPASIDATAMODEL = NULL static protected
This test checks if the workaround for bug 1085 works. Or once libSBML has been fixed, it checks that the bug no longer occurs.
Definition at line 34 of file test000071.h.
Referenced by setUp(), and test_bug1085().
The documentation for this class was generated from the following files:
test000071.h
test000071.cpp