COPASI API: CLNAProblem Class Reference
CLNAProblem Class Reference
#include <CLNAProblem.h>
Public Member Functions
CLNAProblem (const CCopasiContainer *pParent=NULL)
CLNAProblem (const CLNAProblem &src, const CCopasiContainer *pParent=NULL)
CSteadyStateTask * getSubTask () const
bool isSteadyStateRequested () const
void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::NEXT)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
void setInitialState (const CState &initialState)
virtual bool setModel (CModel *pModel)
void setSteadyStateRequested (const bool &steadyStateRequested)
virtual ~CLNAProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual bool initialize ()
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
CState mInitialState
Friends
std::ostream & operator<< (std::ostream &os, const CLNAProblem &o)
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 32 of file CLNAProblem.h.
Constructor & Destructor Documentation
CLNAProblem::CLNAProblem (const CCopasiContainer * pParent = NULL)
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
CLNAProblem class. This class describes the LNA analysis problem.
Created for Copasi by Juergen Pahle 2010 Default constructor.
Parameters
CModel * pModel
Definition at line 30 of file CLNAProblem.cpp.
References CCopasiParameterGroup::addParameter(), CONSTRUCTOR_TRACE, and CCopasiParameter::KEY.
                                                         :
   CCopasiProblem(CCopasiTask::lna, pParent),
   mInitialState()
 {
   addParameter("Steady-State", CCopasiParameter::KEY, std::string(""));
   CONSTRUCTOR_TRACE;
 }
CLNAProblem::CLNAProblem (const CLNAProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CLNAProblem & src CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CLNAProblem & src
Definition at line 42 of file CLNAProblem.cpp.
References CONSTRUCTOR_TRACE.
                                                           :
   CCopasiProblem(src, pParent)
 {CONSTRUCTOR_TRACE;}
CLNAProblem::~CLNAProblem () virtual
Destructor.
Definition at line 50 of file CLNAProblem.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
CSteadyStateTask * CLNAProblem::getSubTask () const
Retrieve the subtask return CSteadyStateTask * pSubTask;
Definition at line 137 of file CLNAProblem.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiParameter::getValue(), and isSteadyStateRequested().
Referenced by CLNATask::initialize(), operator<<(), and CLNATask::printResult().
 {
   if (isSteadyStateRequested())
     return dynamic_cast<CSteadyStateTask *>(CCopasiRootContainer::getKeyFactory()->get(* getValue("Steady-State").pKEY));
   else
     return NULL;
 }
bool CLNAProblem::isSteadyStateRequested () const
Retrieve whether a steady state analysis is requested.
Returns
bool steadyStateRequested
Retrieve whether the steady state analysis is requested.
Returns
bool steadyStateRequested
Definition at line 134 of file CLNAProblem.cpp.
References CCopasiParameter::getValue().
Referenced by getSubTask(), CQLNAWidget::loadTask(), operator<<(), CLNATask::printResult(), and CQLNAWidget::saveTask().
 {return (* getValue("Steady-State").pKEY != "");}
void CLNAProblem::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::NEXT)
Load a LNA problem
Parameters
CReadConfig & configBuffer
"CReadConfig::Mode mode (Default: CReadConfig::NEXT)
Load a lna problem
Parameters
CReadConfig & configBuffer
Definition at line 67 of file CLNAProblem.cpp.
References CReadConfig::getVariable(), CReadConfig::getVersion(), CReadConfig::LOOP, and setSteadyStateRequested().
 {
   if (configBuffer.getVersion() < "4.0")
     {
       bool SteadyStateRequested;
       configBuffer.getVariable("RepxSteadyStateAnalysis", "bool" ,
                                &SteadyStateRequested,
                                CReadConfig::LOOP);
       setSteadyStateRequested(SteadyStateRequested);
     }
 }
void CLNAProblem::print (std::ostream * ostream) const virtual
This is the output method for any object. It calls the insert operator<<
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Definition at line 185 of file CLNAProblem.cpp.
 {
   *ostream << *this;
 }
void CLNAProblem::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a problem. The default implementation is provided with CCopasiProblem. Does only print "Not implemented." To overide this default behaviour one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Definition at line 145 of file CLNAProblem.cpp.
References CCopasiObject::getObjectParent(), and CLNATask::printResult().
 {
   //this functionality is expected from the problem. However it is implemented in
   //the task.
   CLNATask* parent = dynamic_cast<CLNATask*>(getObjectParent());
   if (!parent) return;
   parent->printResult(ostream);
 }
void CLNAProblem::setInitialState (const CState & initialState)
Set the initial state of the problem.
Parameters
const CState & InitialState
Set the initial state of the problem.
Parameters
const CState & initialState
Definition at line 85 of file CLNAProblem.cpp.
References mInitialState.
 {
   mInitialState = initialState;
 }
bool CLNAProblem::setModel (CModel * pModel) virtual
Set the model of the problem
Parameters
CModel * pModel
Returns
bool succes
Set the model the problem is dealing with.
Parameters
CModel * pModel
Reimplemented from CCopasiProblem.
Definition at line 57 of file CLNAProblem.cpp.
References CCopasiProblem::mpModel.
 {
   mpModel = pModel;
   return true;
 }
void CLNAProblem::setSteadyStateRequested (const bool & steadyStateRequested)
Retrieve the initial state of the problem.
Returns
"const CState &" pInitialState Set whether the steady state analysis is requested.
Parameters
const bool & steadyStateRequested
Set whether the steady state analysis is requested.
Parameters
bool * steadyStateRequested
Definition at line 115 of file CLNAProblem.cpp.
References CCopasiTask::getKey(), CCopasiObject::getObjectDataModel(), CCopasiDataModel::getTaskList(), and CCopasiParameterGroup::setValue().
Referenced by load(), and CQLNAWidget::saveTask().
 {
   CSteadyStateTask * pSubTask = NULL;
   CCopasiDataModel* pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   if (pDataModel && pDataModel->getTaskList())
     pSubTask = dynamic_cast<CSteadyStateTask *>((*pDataModel->getTaskList())["Steady-State"]);
   if (steadyStateRequested && pSubTask)
     setValue("Steady-State", pSubTask->getKey());
   else
     setValue("Steady-State", std::string(""));
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLNAProblem & o) friend
Output stream operator. Prints description of the problem incl. the subtask
Parameters
ostream & os
const CLNAProblem & A
Returns
ostream & os
Definition at line 158 of file CLNAProblem.cpp.
 {
   os << "Problem Description:" << std::endl;
   if (o.isSteadyStateRequested())
     {
       os << "Calculation of a steady state is requested before the LNA." << std::endl << std::endl;
       if (o.getSubTask())
         {
           o.getSubTask()->getDescription().print(&os);
         }
       else
         {
           os << "However an error occurred. Please report this as a bug." << std::endl;
         }
     }
   else
     {
       os << "LNA is performed on the current state (which is not necessarily a steady state)." << std::endl;
     }
   os << std::endl;
   return os;
 }
Member Data Documentation
CState CLNAProblem::mInitialState private
The initial state, i.e., at which the LNA is calculated.
Definition at line 39 of file CLNAProblem.h.
Referenced by setInitialState().
The documentation for this class was generated from the following files:
CLNAProblem.h
CLNAProblem.cpp