COPASI API: CQPlayerControlWidget Class Reference
CQPlayerControlWidget Class Reference
#include <CQPlayerControlWidget.h>
Signals
void backward ()
void forward ()
void pause ()
void play ()
void step_backward ()
void step_forward ()
void stop ()
Public Member Functions
CQPlayerControlWidget (QWidget *pParent=NULL)
QAction * getBackwardAction ()
QAction * getForwardAction ()
QAction * getPauseAction ()
QAction * getPlayAction ()
QAction * getStepBackwardAction ()
QAction * getStepForwardAction ()
QAction * getStopAction ()
bool isPlaying () const
void setCurrentStep (size_t currentStep)
void setNumSteps (size_t numSteps)
Protected Member Functions
void createActions ()
void updateActions ()
void updateButtons ()
Protected Attributes
size_t mCurrentStep
size_t mNumSteps
QAction * mpBackwardAction
QPushButton * mpBackwardButton
QAction * mpForwardAction
QPushButton * mpForwardButton
bool mPlaying
QAction * mpPauseAction
QAction * mpPlayAction
QPushButton * mpPlayButton
QAction * mpStepBackwardAction
QPushButton * mpStepBackwardButton
QAction * mpStepForwardAction
QPushButton * mpStepForwardButton
QAction * mpStopAction
QPushButton * mpStopButton
Private Slots
void slot_backward_clicked ()
void slot_forward_clicked ()
void slot_pause_clicked ()
void slot_play_clicked ()
void slot_step_backward_clicked ()
void slot_step_forward_clicked ()
void slot_stop_clicked ()
Detailed Description
Definition at line 19 of file CQPlayerControlWidget.h.
Constructor & Destructor Documentation
CQPlayerControlWidget::CQPlayerControlWidget (QWidget * pParent = NULL)
Definition at line 35 of file CQPlayerControlWidget.cpp.
References CQIconResource::backward, createActions(), createControl(), CQIconResource::forward, mpBackwardButton, mpForwardButton, mpPlayButton, mpStepBackwardButton, mpStepForwardButton, mpStopButton, CQIconResource::play, CQIconResource::skipBackward, CQIconResource::skipForward, slot_backward_clicked(), slot_forward_clicked(), slot_play_clicked(), slot_step_backward_clicked(), slot_step_forward_clicked(), slot_stop_clicked(), CQIconResource::stop, updateActions(), and updateButtons().
                                                             :
   QWidget(pParent),
   mNumSteps(0),
   mCurrentStep(0),
   mPlaying(false),
   mpPlayButton(NULL),
   mpStopButton(NULL),
   mpForwardButton(NULL),
   mpBackwardButton(NULL),
   mpStepForwardButton(NULL),
   mpStepBackwardButton(NULL),
   mpPlayAction(NULL),
   mpPauseAction(NULL),
   mpStopAction(NULL),
   mpForwardAction(NULL),
   mpBackwardAction(NULL),
   mpStepForwardAction(NULL),
   mpStepBackwardAction(NULL)
 {
   QGridLayout* pLayout = new QGridLayout;
   this->mpStepBackwardButton = createControl(CQIconResource::backward);
   pLayout->addWidget(this->mpStepBackwardButton, 0, 0, 1, 1);
   this->mpPlayButton = createControl(CQIconResource::play);
   pLayout->addWidget(this->mpPlayButton, 0, 1, 1, 1);
   this->mpStepForwardButton = createControl(CQIconResource::forward);
   pLayout->addWidget(this->mpStepForwardButton, 0, 2, 1, 1);
   this->mpBackwardButton = createControl(CQIconResource::skipBackward);
   pLayout->addWidget(this->mpBackwardButton, 1, 0, 1, 1);
   this->mpStopButton = createControl(CQIconResource::stop);
   pLayout->addWidget(this->mpStopButton, 1, 1, 1, 1);
   this->mpForwardButton = createControl(CQIconResource::skipForward);
   pLayout->addWidget(this->mpForwardButton, 1, 2, 1, 1);
   this->setLayout(pLayout);
   pLayout->setSizeConstraint(QLayout::SetFixedSize);
   this->createActions();
   this->updateButtons();
   this->updateActions();
   this->setTabOrder(this->mpPlayButton, this->mpStopButton);
   this->setTabOrder(this->mpStopButton, this->mpStepForwardButton);
   this->setTabOrder(this->mpStepForwardButton, this->mpStepBackwardButton);
   this->setTabOrder(this->mpStepBackwardButton, this->mpForwardButton);
   this->setTabOrder(this->mpForwardButton, this->mpBackwardButton);
   connect(this->mpPlayButton, SIGNAL(clicked()), this, SLOT(slot_play_clicked()));
   connect(this->mpStopButton, SIGNAL(clicked()), this, SLOT(slot_stop_clicked()));
   connect(this->mpForwardButton, SIGNAL(clicked()), this, SLOT(slot_forward_clicked()));
   connect(this->mpBackwardButton, SIGNAL(clicked()), this, SLOT(slot_backward_clicked()));
   connect(this->mpStepForwardButton, SIGNAL(clicked()), this, SLOT(slot_step_forward_clicked()));
   connect(this->mpStepBackwardButton, SIGNAL(clicked()), this, SLOT(slot_step_backward_clicked()));
 }
Member Function Documentation
void CQPlayerControlWidget::backward () signal
Referenced by slot_backward_clicked().
void CQPlayerControlWidget::createActions () protected
Definition at line 95 of file CQPlayerControlWidget.cpp.
References CQIconResource::backward, CQIconResource::forward, CQIconResource::icon(), mpBackwardAction, mpForwardAction, mpPauseAction, mpPlayAction, mpStepBackwardAction, mpStepForwardAction, mpStopAction, CQIconResource::pause, CQIconResource::play, CQIconResource::skipBackward, CQIconResource::skipForward, slot_backward_clicked(), slot_forward_clicked(), slot_pause_clicked(), slot_play_clicked(), slot_step_backward_clicked(), slot_step_forward_clicked(), slot_stop_clicked(), and CQIconResource::stop.
Referenced by CQPlayerControlWidget().
 {
   this->mpPlayAction = new QAction(CQIconResource::icon(CQIconResource::play), "Play", this);
   connect(this->mpPlayAction, SIGNAL(triggered()), this, SLOT(slot_play_clicked()));
   this->mpPauseAction = new QAction(CQIconResource::icon(CQIconResource::pause), "Pause", this);
   connect(this->mpPauseAction, SIGNAL(triggered()), this, SLOT(slot_pause_clicked()));
   this->mpStopAction = new QAction(CQIconResource::icon(CQIconResource::stop), "Stop", this);
   connect(this->mpStopAction, SIGNAL(triggered()), this, SLOT(slot_stop_clicked()));
   this->mpForwardAction = new QAction(CQIconResource::icon(CQIconResource::skipForward), "Forward", this);
   connect(this->mpForwardAction, SIGNAL(triggered()), this, SLOT(slot_forward_clicked()));
   this->mpBackwardAction = new QAction(CQIconResource::icon(CQIconResource::skipBackward), "Backward", this);
   connect(this->mpBackwardAction, SIGNAL(triggered()), this, SLOT(slot_backward_clicked()));
   this->mpStepForwardAction = new QAction(CQIconResource::icon(CQIconResource::forward), "Step Forward", this);
   connect(this->mpStepForwardAction, SIGNAL(triggered()), this, SLOT(slot_step_forward_clicked()));
   this->mpStepBackwardAction = new QAction(CQIconResource::icon(CQIconResource::backward), "Step Backward", this);
   connect(this->mpStepBackwardAction, SIGNAL(triggered()), this, SLOT(slot_step_backward_clicked()));
 }
void CQPlayerControlWidget::forward () signal
Referenced by slot_forward_clicked().
QAction * CQPlayerControlWidget::getBackwardAction ()
Definition at line 551 of file CQPlayerControlWidget.cpp.
References mpBackwardAction.
Referenced by CQNewMainWindow::createMenus(), and CQLayoutMainWindow::endOfAnimationReached().
 {
   return this->mpBackwardAction;
 }
QAction * CQPlayerControlWidget::getForwardAction ()
Definition at line 546 of file CQPlayerControlWidget.cpp.
References mpForwardAction.
Referenced by CQNewMainWindow::createMenus().
 {
   return this->mpForwardAction;
 }
QAction * CQPlayerControlWidget::getPauseAction ()
Definition at line 536 of file CQPlayerControlWidget.cpp.
References mpPauseAction.
Referenced by CQNewMainWindow::createMenus(), and CQLayoutMainWindow::endOfAnimationReached().
 {
   return this->mpPauseAction;
 }
QAction * CQPlayerControlWidget::getPlayAction ()
Definition at line 531 of file CQPlayerControlWidget.cpp.
References mpPlayAction.
Referenced by CQNewMainWindow::createMenus().
 {
   return this->mpPlayAction;
 }
QAction * CQPlayerControlWidget::getStepBackwardAction ()
Definition at line 561 of file CQPlayerControlWidget.cpp.
References mpStepBackwardAction.
Referenced by CQNewMainWindow::createMenus().
 {
   return this->mpStepBackwardAction;
 }
QAction * CQPlayerControlWidget::getStepForwardAction ()
Definition at line 556 of file CQPlayerControlWidget.cpp.
References mpStepForwardAction.
Referenced by CQNewMainWindow::createMenus().
 {
   return this->mpStepForwardAction;
 }
QAction * CQPlayerControlWidget::getStopAction ()
Definition at line 541 of file CQPlayerControlWidget.cpp.
References mpStopAction.
Referenced by CQNewMainWindow::createMenus().
 {
   return this->mpStopAction;
 }
bool CQPlayerControlWidget::isPlaying () const
Definition at line 526 of file CQPlayerControlWidget.cpp.
References mPlaying.
Referenced by CQLayoutMainWindow::backwardAnimation().
 {
   return this->mPlaying;
 }
void CQPlayerControlWidget::pause () signal
Referenced by slot_pause_clicked().
void CQPlayerControlWidget::play () signal
Referenced by slot_play_clicked().
void CQPlayerControlWidget::setCurrentStep (size_t currentStep)
Definition at line 120 of file CQPlayerControlWidget.cpp.
References mCurrentStep, mNumSteps, updateActions(), and updateButtons().
Referenced by CQLayoutMainWindow::loadData(), and CQLayoutMainWindow::showStep().
 {
   if (currentStep < this->mNumSteps)
     {
       this->mCurrentStep = currentStep;
     }
   else
     {
       this->mCurrentStep = this->mNumSteps - 1;
     }
   this->updateButtons();
   this->updateActions();
 }
void CQPlayerControlWidget::setNumSteps (size_t numSteps)
Definition at line 113 of file CQPlayerControlWidget.cpp.
References mNumSteps, updateActions(), and updateButtons().
Referenced by CQLayoutMainWindow::loadData(), and CQLayoutMainWindow::startAnimation().
 {
   this->mNumSteps = numSteps;
   this->updateButtons();
   this->updateActions();
 }
void CQPlayerControlWidget::slot_backward_clicked () private slot
Definition at line 494 of file CQPlayerControlWidget.cpp.
References backward(), mCurrentStep, updateActions(), and updateButtons().
Referenced by CQPlayerControlWidget(), and createActions().
 {
   this->mCurrentStep = 0;
   this->updateButtons();
   this->updateActions();
   emit backward();
 }
void CQPlayerControlWidget::slot_forward_clicked () private slot
Definition at line 167 of file CQPlayerControlWidget.cpp.
References forward(), mCurrentStep, mNumSteps, updateActions(), and updateButtons().
Referenced by CQPlayerControlWidget(), and createActions().
 {
   this->mCurrentStep = this->mNumSteps - 1;
   this->updateButtons();
   this->updateActions();
   emit forward();
 }
void CQPlayerControlWidget::slot_pause_clicked () private slot
Definition at line 135 of file CQPlayerControlWidget.cpp.
References FALSE, CQIconResource::icon(), mPlaying, mpPauseAction, mpPlayButton, pause(), and CQIconResource::play.
Referenced by createActions(), and slot_play_clicked().
 {
   this->mpPlayButton->setIcon(CQIconResource::icon(CQIconResource::play));
   this->mPlaying = !this->mPlaying;
   this->mpPauseAction->setEnabled(FALSE);
   emit pause();
 }
void CQPlayerControlWidget::slot_play_clicked () private slot
Definition at line 143 of file CQPlayerControlWidget.cpp.
References CQIconResource::icon(), mPlaying, mpPauseAction, mpPlayButton, CQIconResource::pause, play(), slot_pause_clicked(), and TRUE.
Referenced by CQPlayerControlWidget(), and createActions().
 {
   if (this->mPlaying)
     {
       this->slot_pause_clicked();
     }
   else
     {
       this->mpPlayButton->setIcon(CQIconResource::icon(CQIconResource::pause));
       this->mPlaying = !this->mPlaying;
       this->mpPauseAction->setEnabled(TRUE);
       emit play();
     }
 }
void CQPlayerControlWidget::slot_step_backward_clicked () private slot
Definition at line 514 of file CQPlayerControlWidget.cpp.
References mCurrentStep, step_backward(), updateActions(), and updateButtons().
Referenced by CQPlayerControlWidget(), and createActions().
 {
   if (this->mCurrentStep != 0)
     {
       --this->mCurrentStep;
     }
   this->updateButtons();
   this->updateActions();
   emit step_backward();
 }
void CQPlayerControlWidget::slot_step_forward_clicked () private slot
Definition at line 502 of file CQPlayerControlWidget.cpp.
References mCurrentStep, mNumSteps, step_forward(), updateActions(), and updateButtons().
Referenced by CQPlayerControlWidget(), and createActions().
 {
   if (this->mCurrentStep != this->mNumSteps - 1)
     {
       ++this->mCurrentStep;
     }
   this->updateButtons();
   this->updateActions();
   emit step_forward();
 }
void CQPlayerControlWidget::slot_stop_clicked () private slot
Definition at line 158 of file CQPlayerControlWidget.cpp.
References mCurrentStep, mPlaying, stop(), updateActions(), and updateButtons().
Referenced by CQPlayerControlWidget(), and createActions().
 {
   this->mCurrentStep = 0;
   this->mPlaying = false;
   this->updateButtons();
   this->updateActions();
   emit stop();
 }
void CQPlayerControlWidget::step_backward () signal
Referenced by slot_step_backward_clicked().
void CQPlayerControlWidget::step_forward () signal
Referenced by slot_step_forward_clicked().
void CQPlayerControlWidget::stop () signal
Referenced by slot_stop_clicked().
void CQPlayerControlWidget::updateActions () protected
Definition at line 175 of file CQPlayerControlWidget.cpp.
References FALSE, mCurrentStep, mNumSteps, mpBackwardAction, mpForwardAction, mPlaying, mpPauseAction, mpPlayAction, mpStepBackwardAction, mpStepForwardAction, mpStopAction, and TRUE.
Referenced by CQPlayerControlWidget(), setCurrentStep(), setNumSteps(), slot_backward_clicked(), slot_forward_clicked(), slot_step_backward_clicked(), slot_step_forward_clicked(), and slot_stop_clicked().
 {
   if (this->mNumSteps < 2)
     {
       // disable all actionsw
       if (this->mpPlayAction->isEnabled())
         {
           this->mpPlayAction->setEnabled(FALSE);
         }
       if (this->mpPauseAction->isEnabled())
         {
           this->mpPauseAction->setEnabled(FALSE);
         }
       if (this->mpStopAction->isEnabled())
         {
           this->mpStopAction->setEnabled(FALSE);
         }
       if (this->mpForwardAction->isEnabled())
         {
           this->mpForwardAction->setEnabled(FALSE);
         }
       if (this->mpStepForwardAction->isEnabled())
         {
           this->mpStepForwardAction->setEnabled(FALSE);
         }
       if (this->mpBackwardAction->isEnabled())
         {
           this->mpBackwardAction->setEnabled(FALSE);
         }
       if (this->mpStepBackwardAction->isEnabled())
         {
           this->mpStepBackwardAction->setEnabled(FALSE);
         }
     }
   else
     {
       if (this->mCurrentStep == 0)
         {
           // make sure backward and step_backward are disabled and all other
           // actions are enabled
           if (!this->mPlaying)
             {
               this->mpPauseAction->setEnabled(FALSE);
             }
           else
             {
               this->mpPauseAction->setEnabled(TRUE);
             }
           if (this->mpBackwardAction->isEnabled())
             {
               this->mpBackwardAction->setEnabled(FALSE);
             }
           if (this->mpStepBackwardAction->isEnabled())
             {
               this->mpStepBackwardAction->setEnabled(FALSE);
             }
           if (this->mpPlayAction->isEnabled() == FALSE)
             {
               this->mpPlayAction->setEnabled(TRUE);
             }
           if (this->mpStopAction->isEnabled() == FALSE)
             {
               this->mpStopAction->setEnabled(TRUE);
             }
           if (this->mpForwardAction->isEnabled() == FALSE)
             {
               this->mpForwardAction->setEnabled(TRUE);
             }
           if (this->mpStepForwardAction->isEnabled() == FALSE)
             {
               this->mpStepForwardAction->setEnabled(TRUE);
             }
         }
       else if (this->mCurrentStep == this->mNumSteps - 1)
         {
           // make sure play, forward and step_forward are disabled and all other
           // actions are enabled
           // reset the icon on the play button
           if (this->mpForwardAction->isEnabled())
             {
               this->mpForwardAction->setEnabled(FALSE);
             }
           if (this->mpStepForwardAction->isEnabled())
             {
               this->mpStepForwardAction->setEnabled(FALSE);
             }
           if (this->mpPlayAction->isEnabled())
             {
               this->mpPlayAction->setEnabled(FALSE);
             }
           if (this->mpPauseAction->isEnabled())
             {
               this->mpPauseAction->setEnabled(FALSE);
             }
           if (this->mpBackwardAction->isEnabled() == FALSE)
             {
               this->mpBackwardAction->setEnabled(TRUE);
             }
           if (this->mpStepBackwardAction->isEnabled() == FALSE)
             {
               this->mpStepBackwardAction->setEnabled(TRUE);
             }
           if (this->mpStopAction->isEnabled() == FALSE)
             {
               this->mpStopAction->setEnabled(TRUE);
             }
         }
       else
         {
           // make sure all buttons are enabled
           if (this->mpPlayAction->isEnabled() == FALSE)
             {
               this->mpPlayAction->setEnabled(TRUE);
             }
           if (this->mpStopAction->isEnabled() == FALSE)
             {
               this->mpStopAction->setEnabled(TRUE);
             }
           if (this->mpForwardAction->isEnabled() == FALSE)
             {
               this->mpForwardAction->setEnabled(TRUE);
             }
           if (this->mpBackwardAction->isEnabled() == FALSE)
             {
               this->mpBackwardAction->setEnabled(TRUE);
             }
           if (this->mpStepBackwardAction->isEnabled() == FALSE)
             {
               this->mpStepBackwardAction->setEnabled(TRUE);
             }
           if (this->mpStepForwardAction->isEnabled() == FALSE)
             {
               this->mpStepForwardAction->setEnabled(TRUE);
             }
         }
     }
 }
void CQPlayerControlWidget::updateButtons () protected
Definition at line 336 of file CQPlayerControlWidget.cpp.
References FALSE, CQIconResource::icon(), mCurrentStep, mNumSteps, mpBackwardButton, mpForwardButton, mPlaying, mpPlayButton, mpStepBackwardButton, mpStepForwardButton, mpStopButton, CQIconResource::pause, CQIconResource::play, and TRUE.
Referenced by CQPlayerControlWidget(), setCurrentStep(), setNumSteps(), slot_backward_clicked(), slot_forward_clicked(), slot_step_backward_clicked(), slot_step_forward_clicked(), and slot_stop_clicked().
 {
   if (this->mNumSteps < 2)
     {
       // disable all buttons
       if (this->mpPlayButton->isEnabled())
         {
           this->mpPlayButton->setEnabled(FALSE);
           if (this->mPlaying)
             {
               // reset the icon
               this->mpPlayButton->setIcon(CQIconResource::icon(CQIconResource::play));
             }
         }
       if (this->mpStopButton->isEnabled())
         {
           this->mpStopButton->setEnabled(FALSE);
         }
       if (this->mpForwardButton->isEnabled())
         {
           this->mpForwardButton->setEnabled(FALSE);
         }
       if (this->mpStepForwardButton->isEnabled())
         {
           this->mpStepForwardButton->setEnabled(FALSE);
         }
       if (this->mpBackwardButton->isEnabled())
         {
           this->mpBackwardButton->setEnabled(FALSE);
         }
       if (this->mpStepBackwardButton->isEnabled())
         {
           this->mpStepBackwardButton->setEnabled(FALSE);
         }
     }
   else
     {
       if (this->mCurrentStep == 0)
         {
           // make sure backward and step_backward are disabled and all other
           // buttons are enabled
           if (!this->mPlaying)
             {
               this->mpPlayButton->setIcon(CQIconResource::icon(CQIconResource::play));
             }
           else
             {
               this->mpPlayButton->setIcon(CQIconResource::icon(CQIconResource::pause));
             }
           if (this->mpBackwardButton->isEnabled())
             {
               this->mpBackwardButton->setEnabled(FALSE);
             }
           if (this->mpStepBackwardButton->isEnabled())
             {
               this->mpStepBackwardButton->setEnabled(FALSE);
             }
           if (this->mpPlayButton->isEnabled() == FALSE)
             {
               this->mpPlayButton->setEnabled(TRUE);
             }
           if (this->mpStopButton->isEnabled() == FALSE)
             {
               this->mpStopButton->setEnabled(TRUE);
             }
           if (this->mpForwardButton->isEnabled() == FALSE)
             {
               this->mpForwardButton->setEnabled(TRUE);
             }
           if (this->mpStepForwardButton->isEnabled() == FALSE)
             {
               this->mpStepForwardButton->setEnabled(TRUE);
             }
         }
       else if (this->mCurrentStep == this->mNumSteps - 1)
         {
           // make sure play, forward and step_forward are disabled and all other
           // buttons are enabled
           // reset the icon on the play button
           if (this->mpForwardButton->isEnabled())
             {
               this->mpForwardButton->setEnabled(FALSE);
             }
           if (this->mpStepForwardButton->isEnabled())
             {
               this->mpStepForwardButton->setEnabled(FALSE);
             }
           if (this->mpPlayButton->isEnabled())
             {
               this->mpPlayButton->setIcon(CQIconResource::icon(CQIconResource::play));
               this->mpPlayButton->setEnabled(FALSE);
             }
           if (this->mpBackwardButton->isEnabled() == FALSE)
             {
               this->mpBackwardButton->setEnabled(TRUE);
             }
           if (this->mpStepBackwardButton->isEnabled() == FALSE)
             {
               this->mpStepBackwardButton->setEnabled(TRUE);
             }
           if (this->mpStopButton->isEnabled() == FALSE)
             {
               this->mpStopButton->setEnabled(TRUE);
             }
         }
       else
         {
           // make sure all buttons are enabled
           if (this->mpPlayButton->isEnabled() == FALSE)
             {
               this->mpPlayButton->setEnabled(TRUE);
             }
           if (this->mpStopButton->isEnabled() == FALSE)
             {
               this->mpStopButton->setEnabled(TRUE);
             }
           if (this->mpForwardButton->isEnabled() == FALSE)
             {
               this->mpForwardButton->setEnabled(TRUE);
             }
           if (this->mpBackwardButton->isEnabled() == FALSE)
             {
               this->mpBackwardButton->setEnabled(TRUE);
             }
           if (this->mpStepBackwardButton->isEnabled() == FALSE)
             {
               this->mpStepBackwardButton->setEnabled(TRUE);
             }
           if (this->mpStepForwardButton->isEnabled() == FALSE)
             {
               this->mpStepForwardButton->setEnabled(TRUE);
             }
         }
     }
 }
Member Data Documentation
size_t CQPlayerControlWidget::mCurrentStep protected
Definition at line 44 of file CQPlayerControlWidget.h.
Referenced by setCurrentStep(), slot_backward_clicked(), slot_forward_clicked(), slot_step_backward_clicked(), slot_step_forward_clicked(), slot_stop_clicked(), updateActions(), and updateButtons().
size_t CQPlayerControlWidget::mNumSteps protected
Definition at line 43 of file CQPlayerControlWidget.h.
Referenced by setCurrentStep(), setNumSteps(), slot_forward_clicked(), slot_step_forward_clicked(), updateActions(), and updateButtons().
QAction* CQPlayerControlWidget::mpBackwardAction protected
Definition at line 58 of file CQPlayerControlWidget.h.
Referenced by createActions(), getBackwardAction(), and updateActions().
QPushButton* CQPlayerControlWidget::mpBackwardButton protected
Definition at line 50 of file CQPlayerControlWidget.h.
Referenced by CQPlayerControlWidget(), and updateButtons().
QAction* CQPlayerControlWidget::mpForwardAction protected
Definition at line 57 of file CQPlayerControlWidget.h.
Referenced by createActions(), getForwardAction(), and updateActions().
QPushButton* CQPlayerControlWidget::mpForwardButton protected
Definition at line 49 of file CQPlayerControlWidget.h.
Referenced by CQPlayerControlWidget(), and updateButtons().
bool CQPlayerControlWidget::mPlaying protected
Definition at line 45 of file CQPlayerControlWidget.h.
Referenced by isPlaying(), slot_pause_clicked(), slot_play_clicked(), slot_stop_clicked(), updateActions(), and updateButtons().
QAction* CQPlayerControlWidget::mpPauseAction protected
Definition at line 55 of file CQPlayerControlWidget.h.
Referenced by createActions(), getPauseAction(), slot_pause_clicked(), slot_play_clicked(), and updateActions().
QAction* CQPlayerControlWidget::mpPlayAction protected
Definition at line 54 of file CQPlayerControlWidget.h.
Referenced by createActions(), getPlayAction(), and updateActions().
QPushButton* CQPlayerControlWidget::mpPlayButton protected
Definition at line 47 of file CQPlayerControlWidget.h.
Referenced by CQPlayerControlWidget(), slot_pause_clicked(), slot_play_clicked(), and updateButtons().
QAction* CQPlayerControlWidget::mpStepBackwardAction protected
Definition at line 60 of file CQPlayerControlWidget.h.
Referenced by createActions(), getStepBackwardAction(), and updateActions().
QPushButton* CQPlayerControlWidget::mpStepBackwardButton protected
Definition at line 52 of file CQPlayerControlWidget.h.
Referenced by CQPlayerControlWidget(), and updateButtons().
QAction* CQPlayerControlWidget::mpStepForwardAction protected
Definition at line 59 of file CQPlayerControlWidget.h.
Referenced by createActions(), getStepForwardAction(), and updateActions().
QPushButton* CQPlayerControlWidget::mpStepForwardButton protected
Definition at line 51 of file CQPlayerControlWidget.h.
Referenced by CQPlayerControlWidget(), and updateButtons().
QAction* CQPlayerControlWidget::mpStopAction protected
Definition at line 56 of file CQPlayerControlWidget.h.
Referenced by createActions(), getStopAction(), and updateActions().
QPushButton* CQPlayerControlWidget::mpStopButton protected
Definition at line 48 of file CQPlayerControlWidget.h.
Referenced by CQPlayerControlWidget(), and updateButtons().
The documentation for this class was generated from the following files:
CQPlayerControlWidget.h
CQPlayerControlWidget.cpp