COPASI API: CQValidatorInt Class Reference
CQValidatorInt Class Reference
#include <CQValidator.h>
Public Member Functions
CQValidatorInt (QLineEdit *parent, const char *name=0)
void setRange (const int &lowerBound, const int &upperBound)
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QLineEdit >
CQValidator (QLineEdit *parent, QString(QLineEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Protected Attributes
QIntValidator * mpIntValidator
Protected Attributes inherited from CQValidator< QLineEdit >
QString mLastAccepted
QLineEdit * mpContainer
QString(QLineEdit::* mRetrieve)(void) const
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QLineEdit >
State setColor (const State &state) const
Detailed Description
Definition at line 159 of file CQValidator.h.
Constructor & Destructor Documentation
CQValidatorInt::CQValidatorInt (QLineEdit * parent, const char * name = 0)
Definition at line 83 of file CQValidator.cpp.
                                                                    :
   CQValidator< QLineEdit >(parent, &QLineEdit::text, name),
   mpIntValidator(new QIntValidator(std::numeric_limits< int >::min(),
                                    std::numeric_limits< int >::max(), this))
 {}
Member Function Documentation
void CQValidatorInt::setRange (const int & lowerBound, const int & upperBound)
Definition at line 98 of file CQValidator.cpp.
References mpIntValidator.
Referenced by CQCrossSectionTaskWidget::init(), and CQTrajectoryWidget::init().
 {mpIntValidator->setRange(lowerBound, upperBound);}
QValidator::State CQValidatorInt::validate (QString & input, int & pos) const virtual
Reimplemented from CQValidator< QLineEdit >.
Definition at line 89 of file CQValidator.cpp.
References mpIntValidator, and CQValidator< QLineEdit >::setColor().
 {
   if (mpIntValidator->validate(input, pos) == Acceptable)
     return CQValidator< QLineEdit >::validate(input, pos);
   setColor(Invalid);
   return Intermediate;
 }
Member Data Documentation
QIntValidator* CQValidatorInt::mpIntValidator protected
Definition at line 171 of file CQValidator.h.
Referenced by setRange(), and validate().
The documentation for this class was generated from the following files:
CQValidator.h
CQValidator.cpp