COPASI API: CQModelElementTreeWidgetItem Class Reference
CQModelElementTreeWidgetItem Class Reference
#include <CQAutolayoutWizard.h>
Public Member Functions
CQModelElementTreeWidgetItem (const QStringList &strings, const std::string &key, int type=QTreeWidgetItem::Type)
const std::string & getKey () const
CCopasiObject * getObject () const
Protected Attributes
std::string mKey
Detailed Description
Definition at line 35 of file CQAutolayoutWizard.h.
Constructor & Destructor Documentation
CQModelElementTreeWidgetItem::CQModelElementTreeWidgetItem (const QStringList & strings, const std::string & key, int type = QTreeWidgetItem::Type)
Constructor which in addition to the attributes of the original class also takes a string which is the key of the object that is represented by the item.
Definition at line 37 of file CQAutolayoutWizard.cpp.
                                                                                                                       :
   QTreeWidgetItem(strings, type)
   , mKey(key)
 {
 }
Member Function Documentation
const std::string & CQModelElementTreeWidgetItem::getKey () const
Returns a const reference to the key of the object.
Definition at line 46 of file CQAutolayoutWizard.cpp.
References mKey.
 {
   return this->mKey;
 }
CCopasiObject * CQModelElementTreeWidgetItem::getObject () const
Returns a pointer to the COPASI object represented by this item.
Definition at line 55 of file CQAutolayoutWizard.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), and mKey.
Referenced by CQSelectionWizardPage::fillContainers().
 {
   CCopasiObject* pObject = NULL;
   if (!this->mKey.empty())
     {
       pObject = CCopasiRootContainer::getKeyFactory()->get(this->mKey);
     }
   return pObject;
 }
Member Data Documentation
std::string CQModelElementTreeWidgetItem::mKey protected
Definition at line 40 of file CQAutolayoutWizard.h.
Referenced by getKey(), and getObject().
The documentation for this class was generated from the following files:
CQAutolayoutWizard.h
CQAutolayoutWizard.cpp