COPASI API: CCopasiXMLParser::ParameterDescriptionElement Class Reference
CCopasiXMLParser::ParameterDescriptionElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ParameterDescriptionElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void reset ()
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ParameterDescriptionElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { ParameterDescription = 0 }
Private Attributes
unsigned C_INT32 mOrder
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2942 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ParameterDescriptionElement::Element private
Enumerator
ParameterDescription
Definition at line 2949 of file CCopasiXMLParser.h.
     {
       ParameterDescription = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ParameterDescriptionElement::ParameterDescriptionElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 1445 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mOrder(0)
 {}
CCopasiXMLParser::ParameterDescriptionElement::~ParameterDescriptionElement () virtual
Destructor
Definition at line 1451 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::ParameterDescriptionElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 1575 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case ParameterDescription:
         if (strcmp(pszName, "ParameterDescription"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ParameterDescription", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ParameterDescriptionElement::reset () virtual
Reset the element handler to start values.
Reimplemented from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >.
Definition at line 1605 of file CCopasiXMLParser.cpp.
 {mOrder = 0;}
void CCopasiXMLParser::ParameterDescriptionElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 1456 of file CCopasiXMLParser.cpp.
References CFunctionParameters::add(), C_INT32, C_INVALID_INDEX, CCopasiMessage::EXCEPTION, CFunctionParameters::findParameterByName(), CFunctionParameter::FLOAT64, CFunction::getVariables(), CCopasiXMLParser::mCommon, MCXML, SCopasiXMLParserCommon::mFunctionParameterKeyMap, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::mPredefinedFunction, SCopasiXMLParserCommon::pFunction, CFunctionParameter::setIsUsed(), CCopasiObject::setObjectName(), CFunctionParameter::setType(), CFunctionParameter::setUsage(), CFunctionParameters::size(), StringPrint(), strToUnsignedInt(), CFunctionParameters::swap(), CFunctionParameter::TEMPORARY, UNKNOWN_ELEMENT, CFunctionParameter::VFLOAT64, and CFunctionParameter::xmlRole2Enum().
 {
   const char * Key;
   const char * Name;
   const char * order;
   unsigned C_INT32 Order;
   const char * role; /*substrate, product, modifier, constant, other*/
   CFunctionParameter::Role Role;
   const char * minOccurs;
   unsigned C_INT32 MinOccurs;
   const char * maxOccurs;
   unsigned C_INT32 MaxOccurs;
   mCurrentElement++; /* We should always be on the next element */
   //std::string Usage[] = {"SUBSTRATE", "PRODUCT", "MODIFIER", "PARAMETER"};
   CFunctionParameter * pParm = NULL;
   CFunction * pFunction = dynamic_cast<CFunction *>(mCommon.pFunction);
   if (!pFunction) mCurrentElement++;
   switch (mCurrentElement)
     {
       case ParameterDescription:
         if (strcmp(pszName, "ParameterDescription"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "ParameterDescription", mParser.getCurrentLineNumber());
         Key = mParser.getAttributeValue("key", papszAttrs);
         Name = mParser.getAttributeValue("name", papszAttrs);
         order = mParser.getAttributeValue("order", papszAttrs);
         Order = (unsigned C_INT32) atoi(order);
         role = mParser.getAttributeValue("role", papszAttrs);
         Role = CFunctionParameter::xmlRole2Enum(role);
         //if (Role == "") fatalError();
         minOccurs = mParser.getAttributeValue("minOccurs", papszAttrs, "1");
         MinOccurs = strToUnsignedInt(minOccurs);
         maxOccurs = mParser.getAttributeValue("maxOccurs", papszAttrs , "1");
         if (std::string("unbounded") == std::string(maxOccurs))
           MaxOccurs = (unsigned C_INT32) - 1;
         else
           MaxOccurs = strToUnsignedInt(maxOccurs);
         if (mCommon.mPredefinedFunction)
           {
             addFix(Key, pFunction->getVariables()[Name]);
           }
         else
           {
             // If we are here we have a user defined function.
             // We need to check whether the variable exists within the function.
             CFunctionParameter::DataType DataType;
             size_t Index =
               pFunction->getVariables().findParameterByName(Name, DataType);
             bool isUsed = true;
             if (Index == C_INVALID_INDEX)
               {
                 // We add the missing parameter and mark it as unused.
                 pFunction->getVariables().add(Name,
                                               CFunctionParameter::FLOAT64,
                                               Role);
                 Index = pFunction->getVariables().findParameterByName(Name, DataType);
                 isUsed = false;
               }
             // Make sure that we have enough parameter to swap
             size_t Counter = 0;
             while (Order >= pFunction->getVariables().size())
               {
                 std::string NewName = StringPrint("TMP_%d", Counter++);
                 while (!pFunction->getVariables().add(NewName,
                                                       CFunctionParameter::FLOAT64,
                                                       CFunctionParameter::TEMPORARY)) {};
                 NewName = StringPrint("TMP_%d", Counter++);
               }
             // Assure that the order is correct
             if (Order != Index)
               pFunction->getVariables().swap(Order, Index);
             pParm = pFunction->getVariables()[Order];
             pParm->setObjectName(Name);
             pParm->setUsage(Role);
             pParm->setIsUsed(isUsed);
             if (MaxOccurs == 1 && MinOccurs == 1)
               pParm->setType(CFunctionParameter::FLOAT64);
             else
               pParm->setType(CFunctionParameter::VFLOAT64);
             mCommon.mFunctionParameterKeyMap[Order] = Key;
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
Member Data Documentation
unsigned C_INT32 CCopasiXMLParser::ParameterDescriptionElement::mOrder private
Order
Definition at line 2957 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp