COPASI API: CopasiUI3Window Class Reference
CopasiUI3Window Class Reference
#include <copasiui3window.h>
Public Slots
void autoSave ()
void openInitialDocument (const QString &file)
void slotFileOpen (QString file=QString::null)
void slotObjectBrowserDialogWasClosed ()
void slotShowSliders (bool flag)
Signals
void signalLoadFile (QString newFile)
void signalQuit ()
Public Member Functions
void addWindow (QMainWindow *pWindow)
void checkPendingMessages ()
void disableSliders (bool disable)
void exportSBMLToString (std::string &SBML)
DataModelGUI * getDataModel ()
ListViews * getMainWidget ()
const QList< QPointer
< QMainWindow > > & getWindows () const
void importSBMLFromString (const std::string &sbmlDocumentText)
const bool & messageShown () const
void removeWindow (QMainWindow *pWindow)
void setMessageShown (const bool &shown)
void suspendAutoSave (const bool &suspend)
~CopasiUI3Window ()
Static Public Member Functions
static CopasiUI3Window * create ()
static CopasiUI3Window * getMainWindow ()
static bool isMainThread ()
Protected Slots
void about ()
void aboutQt ()
void customEvent (QEvent *)
void license ()
void listViewsFolderChanged (const QModelIndex &index)
void newDoc ()
void slotActivateWindowTriggered (QAction *action)
void slotApplyInitialState ()
void slotCapture ()
void slotCheckModel ()
void slotCloseAllWindows ()
void slotConvertToIrreversible ()
void slotExpandModel ()
void slotExportMathModel ()
void slotExportMathModelFinished (bool success)
void slotExportSBML ()
void slotExportSBMLFinished (bool success)
void slotExportSBMLToStringFinished (bool success)
void slotFileExamplesCopasiFiles (QString file=QString::null)
void slotFileExamplesSBMLFiles (QString file=QString::null)
void slotFileOpenFinished (bool success)
void slotFilePrint ()
void slotFileSave ()
void slotFileSaveAs (QString str=QString::null)
void slotFileSaveFinished (bool success)
void slotFontSelection ()
void slotFrameworkChanged (int index)
void slotFunctionDBLoad (QString str=QString::null)
void slotFunctionDBSave (QString str=QString::null)
void slotImportSBML (QString file=QString::null)
void slotImportSBMLFinished (bool success)
void slotImportSBMLFromStringFinished (bool success)
void slotOpenRecentFile (QAction *pAction)
void slotOpenRecentSBMLFile (QAction *pAction)
void slotPreferences ()
void slotQuit ()
void slotQuitFinished (bool success)
void slotShowObjectBrowserDialog (bool flag)
void slotTutorialWizard ()
void slotUpdateInitialState ()
void slotUpdateMIRIAM ()
void slotUpdateMIRIAMFinished (bool)
Protected Member Functions
virtual void closeEvent (QCloseEvent *e)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
Private Member Functions
void CleanUp ()
CopasiUI3Window ()
void createActions ()
void createMenuBar ()
void createToolBar ()
void refreshRecentFileMenu ()
void refreshRecentSBMLFileMenu ()
void refreshWindowsMenu ()
void setApplicationFont ()
void updateTitle ()
Private Attributes
QString FixedTitle
bool mCommitRequired
bool mMessageShown
QString mNewFile
QAction * mpaApplyInitialState
QAction * mpaCapture
QAction * mpaCheckModel
QAction * mpaCloseAllWindows
QAction * mpaExpandModel
QAction * mpaExportODE
QAction * mpaExportSBML
QAction * mpaFontSelectionDialog
QAction * mpaFunctionDBLoad
QAction * mpaFunctionDBSave
QAction * mpaImportSBML
QAction * mpaNew
QAction * mpaObjectBrowser
QAction * mpaOpen
QAction * mpaOpenCopasiFiles
QAction * mpaOpenSBMLFiles
QAction * mpaQuit
QAction * mpaSave
QAction * mpaSaveAs
QAction * mpaSliders
QAction * mpaUpdateInitialState
QAction * mpaUpdateMIRIAM
QTimer * mpAutoSaveTimer
QComboBox * mpBoxSelectFramework
DataModelGUI * mpDataModelGUI
ListViews * mpListView
QThread * mpMainThread
QMenu * mpMenuExamples
QMenu * mpMenuRecentFiles
QMenu * mpMenuRecentSBMLFiles
CMIRIAMResources * mpMIRIAMResources
ObjectBrowserDialog * mpObjectBrowser
QActionGroup * mpRecentFilesActionGroup
QActionGroup * mpRecentSBMLFilesActionGroup
SliderDialog * mpSliders
QMenu * mpTools
QActionGroup * mpWindowsActionGroup
QMenu * mpWindowsMenu
bool mQuitApplication
QMap< QAction *, int > mRecentFilesActionMap
QMap< QAction *, int > mRecentSBMLFilesActionMap
bool mSaveAsRequired
bool mSliderDialogEnabled
bool mSuspendAutoSave
QList< QPointer< QMainWindow > > mWindows
Static Private Attributes
static CopasiUI3Window * pMainWindow = NULL
Detailed Description
Definition at line 54 of file copasiui3window.h.
Constructor & Destructor Documentation
CopasiUI3Window::~CopasiUI3Window ()
Definition at line 272 of file copasiui3window.cpp.
References DataModelGUI::deregisterListView(), mpDataModelGUI, mpListView, mpSliders, mWindows, and pdelete.
 {
 #ifdef COPASI_SBW_INTEGRATION
   sbwDisconnect();
 #endif // COPASI_SBW_INTEGRATION
   QList< QPointer<QMainWindow> >::iterator it = mWindows.begin();
   QList< QPointer<QMainWindow> >::iterator end = mWindows.end();
   for (; it != end; ++it)
     {
       QPointer<QMainWindow> current = *it;
       if (current == NULL)  continue;
       if (current != this)
         current->close();
     }
   pdelete(mpSliders);
   mpDataModelGUI->deregisterListView(mpListView);
   pdelete(mpDataModelGUI);
   pdelete(mpListView);
 }
CopasiUI3Window::CopasiUI3Window () private
Constructs a CopasiUI window which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
Parameters
parent The widget which this window is a child of.
name The object name is a text that can be used to identify this QObject. It's particularly useful in conjunction with the Qt Designer. You can find an object by name (and type) using child(), and more than one using queryList().
flags Flags for this widget. Refer Qt::WidgetFlags of Qt documentation for more information about these flags.
Definition at line 150 of file copasiui3window.cpp.
References AutoSaveInterval, CQIconResource::copasi, createActions(), createMenuBar(), createToolBar(), FixedTitle, FROM_UTF8, ListViews::getCurrentItemId(), CCopasiRootContainer::getDatamodelList(), CQIconResource::icon(), listViewsFolderChanged(), mpaExportODE, mpaExportSBML, mpaSave, mpaSaveAs, mpAutoSaveTimer, mpDataModelGUI, mpListView, mpSliders, mSliderDialogEnabled, mWindows, DataModelGUI::registerListView(), setApplicationFont(), SliderDialog::setChanged(), SliderDialog::setCurrentFolderId(), SliderDialog::setParentWindow(), ListViews::switchToOtherWidget(), updateTitle(), and CVersion::VERSION.
Referenced by create().
                                 :
   QMainWindow(),
   mpDataModelGUI(NULL),
   mpListView(NULL),
   mpBoxSelectFramework(NULL),
   mpSliders(NULL),
   mpObjectBrowser(NULL),
   mSaveAsRequired(true),
   mpAutoSaveTimer(NULL),
   mSuspendAutoSave(false),
   mpMenuExamples(NULL),
   mpMenuRecentFiles(NULL),
   mRecentFilesActionMap(),
   mpRecentFilesActionGroup(NULL),
   mpMenuRecentSBMLFiles(NULL),
   mRecentSBMLFilesActionMap(),
   mpRecentSBMLFilesActionGroup(NULL),
   mpWindowsActionGroup(NULL),
   mpMIRIAMResources(NULL),
   mpMainThread(QThread::currentThread()),
   mNewFile(),
   mCommitRequired(true),
   mQuitApplication(false),
   mSliderDialogEnabled(false),
   mMessageShown(false),
   mWindows()
 #ifdef COPASI_SBW_INTEGRATION
   , mpSBWModule(NULL)
   , mSBWAnalyzerModules()
   , mSBWAnalyzerServices()
   , mSBWActionMap()
   , mpSBWActionGroup(NULL)
   , mpSBWMenu(NULL)
   , mpSBWAction(NULL)
   , mSBWIgnoreShutdownEvent(true)
 #endif // COPASI_SBW_INTEGRATION
 #ifdef COPASI_SEDML
   , mpMenuSEDMLSupport(NULL)
   , mpMenuRecentSEDMLFiles(NULL)
   , mRecentSEDMLFilesActionMap()
   , mpRecentSEDMLFilesActionGroup(NULL)
 #endif //COPASI_SEDML support
 {
   // set destructive close
   this->setAttribute(Qt::WA_DeleteOnClose);
   // Add this window to the list of windows
   mWindows.append(this);
 #ifndef Darwin
   setWindowIcon(CQIconResource::icon(CQIconResource::copasi));
 #endif // not Darwin
   // Set the window caption/title
   FixedTitle = "COPASI ";
   FixedTitle += FROM_UTF8(CVersion::VERSION.getVersion());
   updateTitle();
   createActions();
   createToolBar(); // creates a tool bar
   createMenuBar();  // creates a menu bar
   setIconSize(QSize(18, 20));
   mpaSave->setEnabled(false);
   mpaSaveAs->setEnabled(false);
   mpaExportSBML->setEnabled(false);
   mpaExportODE->setEnabled(false);
   //TODO SEDML
 #ifdef COPASI_SEDML
   mpaExportSEDML->setEnabled(false);
 #endif
   if (!mpDataModelGUI)
     {
       // create the data model
       mpDataModelGUI = new DataModelGUI(this);
     }
   mpListView = new ListViews(this);
   connect(mpListView, SIGNAL(signalFolderChanged(const QModelIndex &)), this, SLOT(listViewsFolderChanged(const QModelIndex &)));
   mpDataModelGUI->registerListView(mpListView);
   mpListView->show();
   this->setCentralWidget(mpListView);
   //create sliders window
   this->mpSliders = new SliderDialog(NULL);
   this->mpSliders->setParentWindow(this);
   size_t id = mpListView->getCurrentItemId();
   this->mpSliders->setCurrentFolderId(id);
   this->mpSliders->resize(320, 350);
   this->mSliderDialogEnabled = this->mpSliders->isEnabled();
   resize(800, 600);
   show();
   mpListView->switchToOtherWidget(0, "");
   // Assure that the changed flag is still false;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   (*CCopasiRootContainer::getDatamodelList())[0]->changed(false);
   this->mpSliders->setChanged(false);
   mpAutoSaveTimer = new QTimer(this);
   mpAutoSaveTimer->start(AutoSaveInterval); // every 10 minutes
   // TODO CRITICAL We need to disable autosave to avoid race conditions.
   // connect(mpAutoSaveTimer, SIGNAL(timeout()), this, SLOT(autoSave()));
   // mpDataModelGUI->notify(ListViews::FUNCTION, ListViews::ADD, "");
   setApplicationFont();
   // drop acceptance
   setAcceptDrops(true);
 }
Member Function Documentation
void CopasiUI3Window::about () protected slot
Definition at line 1240 of file copasiui3window.cpp.
References FixedTitle, FROM_UTF8, AboutDialog::text, and CVersion::VERSION.
Referenced by createMenuBar().
 {
   QString text =
     QString(AboutDialog::text)
     .arg(FROM_UTF8(CVersion::VERSION.getVersion()))
     .arg(LIBSBML_DOTTED_VERSION);
   AboutDialog* aboutDialog = new AboutDialog(this, text, 76, 30);
   aboutDialog->setWindowTitle(FixedTitle);
   aboutDialog->exec();
 }
void CopasiUI3Window::aboutQt () protected slot
Definition at line 1259 of file copasiui3window.cpp.
Referenced by createMenuBar().
 {
   QMessageBox::aboutQt(this, "Qt");
 }
void CopasiUI3Window::addWindow (QMainWindow * pWindow)
Definition at line 1966 of file copasiui3window.cpp.
References mWindows, and refreshWindowsMenu().
Referenced by CWindowInterface::addToMainWindow(), and slotShowSliders().
 {
   mWindows.append(pWindow);
   refreshWindowsMenu();
 }
void CopasiUI3Window::autoSave () slot
Definition at line 1823 of file copasiui3window.cpp.
References AutoSaveInterval, CCopasiRootContainer::getDatamodelList(), mpAutoSaveTimer, and mSuspendAutoSave.
Referenced by TaskWidget::commonBeforeRunTask().
 {
   // TODO CRITICAL This needs to be moved into a sub thread so
   // that a progress dialog can be displayed and the user can interrupt.
   if (!mSuspendAutoSave)
     {
       mSuspendAutoSave = true;
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->autoSave();
       mSuspendAutoSave = false;
     }
   mpAutoSaveTimer->setInterval(AutoSaveInterval); // restart the timer
 }
void CopasiUI3Window::checkPendingMessages ()
Definition at line 1744 of file copasiui3window.cpp.
References FROM_UTF8, CCopasiMessage::getLastMessage(), CCopasiMessage::getNumber(), CCopasiMessage::getText(), CCopasiMessage::getType(), CQMessageBox::information(), MCCopasiMessage, and CQMessageBox::setFilteredText().
Referenced by slotExportSBMLFinished(), slotImportSBMLFinished(), slotImportSBMLFromStringFinished(), and slotUpdateMIRIAMFinished().
 {
   CCopasiMessage msg_pending = CCopasiMessage::getLastMessage();
   if (msg_pending.getNumber() != MCCopasiMessage + 1)
     {
       QString text;
       QString filteredText;
       unsigned int numMessages = 0;
       unsigned int numFilteredMessages = 0;
       while (msg_pending.getNumber() != MCCopasiMessage + 1)
         {
           if (msg_pending.getType() & 128)
             {
               ++numFilteredMessages;
               filteredText += "\n";
               filteredText += FROM_UTF8(msg_pending.getText());
             }
           else
             {
               ++numMessages;
               text += "\n";
               text += FROM_UTF8(msg_pending.getText());
             }
           msg_pending = CCopasiMessage::getLastMessage();
         }
       if (numFilteredMessages != 0)
         {
           if (text.isEmpty())
             text = "There were no serious issues encountered during the import of SBML. "
                    "However some minor issues have occurred, which can be viewed in the Minor "
                    "Issues tab.";
           CQMessageBox box(QMessageBox::Information,
                            QString("COPASI Message"), text, QMessageBox::Ok, this);
           box.setDefaultButton(QMessageBox::Ok);
           box.setFilteredText(filteredText);
           box.exec();
         }
       else
         {
           CQMessageBox::information(this, QString("COPASI Message"), text,
                                     QMessageBox::Ok, QMessageBox::Ok);
         }
     }
 }
void CopasiUI3Window::CleanUp () private
Definition at line 1227 of file copasiui3window.cpp.
References COptions::getValue(), CDirEntry::remove(), CDirEntry::removeFiles(), and signalQuit().
Referenced by slotQuitFinished().
 {
   emit signalQuit();
   std::string tempDir;
   COptions::getValue("Tmp", tempDir);
   CDirEntry::removeFiles("*.cps", tempDir);
   CDirEntry::remove(tempDir);
 }
void CopasiUI3Window::closeEvent (QCloseEvent * e) protected virtual
Definition at line 1216 of file copasiui3window.cpp.
References slotQuit().
 {
   // We handle this internally.
   ce->ignore();
   slotQuit();
   return;
 }
CopasiUI3Window * CopasiUI3Window::create () static
Definition at line 117 of file copasiui3window.cpp.
References COptions::compareValue(), CopasiUI3Window(), and pMainWindow.
Referenced by main().
 {
   CopasiUI3Window * pWindow = NULL;
   pWindow = new CopasiUI3Window;
 #ifdef COPASI_SBW_INTEGRATION
   if (pWindow != NULL &&
       COptions::compareValue("SBWRegister", true))
     {
       pWindow->sbwConnect();
       pWindow->sbwRegister();
     }
 #endif // COPASI_SBW_INTEGRATION
   pMainWindow = pWindow;
   return pWindow;
 }
void CopasiUI3Window::createActions () private
Definition at line 297 of file copasiui3window.cpp.
References CQIconResource::captureImage, CQIconResource::checkMark, CQIconResource::fileAdd, CQIconResource::fileExport, CQIconResource::fileNew, CQIconResource::fileOpen, CQIconResource::fileSave, CQIconResource::fileSaveas, CQIconResource::icon(), CQIconResource::isToS, CQIconResource::miriam, mpaApplyInitialState, mpaCapture, mpaCheckModel, mpaCloseAllWindows, mpaExpandModel, mpaExportODE, mpaExportSBML, mpaFontSelectionDialog, mpaFunctionDBLoad, mpaFunctionDBSave, mpaImportSBML, mpaNew, mpaObjectBrowser, mpaOpen, mpaOpenCopasiFiles, mpaOpenSBMLFiles, mpaQuit, mpaSave, mpaSaveAs, mpaSliders, mpaUpdateInitialState, mpaUpdateMIRIAM, newDoc(), CQIconResource::slider, slotApplyInitialState(), slotCapture(), slotCheckModel(), slotCloseAllWindows(), slotExpandModel(), slotExportMathModel(), slotExportSBML(), slotFileExamplesCopasiFiles(), slotFileExamplesSBMLFiles(), slotFileOpen(), slotFileSave(), slotFileSaveAs(), slotFontSelection(), slotFunctionDBLoad(), slotFunctionDBSave(), slotImportSBML(), slotQuit(), slotShowObjectBrowserDialog(), slotShowSliders(), slotUpdateInitialState(), slotUpdateMIRIAM(), and CQIconResource::sToIs.
Referenced by CopasiUI3Window().
 {
   //TODO: use the QKeySequence standard shortcuts
   //TODO: add tool tips, status tips etc.
   mpaNew = new QAction(CQIconResource::icon(CQIconResource::fileNew), "&New", this);
   connect(mpaNew, SIGNAL(activated()), this, SLOT(newDoc()));
   mpaNew->setShortcut(Qt::CTRL + Qt::Key_N);
   mpaOpen = new QAction(CQIconResource::icon(CQIconResource::fileOpen), "&Open...", this);
   connect(mpaOpen, SIGNAL(activated()), this, SLOT(slotFileOpen()));
   mpaOpen->setShortcut(Qt::CTRL + Qt::Key_O);
   mpaOpenCopasiFiles = new QAction(CQIconResource::icon(CQIconResource::fileOpen), "COP&ASI Files...", this);
   connect(mpaOpenCopasiFiles, SIGNAL(activated()), this, SLOT(slotFileExamplesCopasiFiles()));
   // mpaOpenCopasiFiles->setShortcut(Qt::CTRL + Qt::Key_1);
   mpaOpenSBMLFiles = new QAction(CQIconResource::icon(CQIconResource::fileOpen), "S&BML Files...", this);
   connect(mpaOpenSBMLFiles, SIGNAL(activated()), this, SLOT(slotFileExamplesSBMLFiles()));
   // mpaOpenSBMLFiles->setShortcut(Qt::CTRL + Qt::Key_2);
   mpaSave = new QAction(CQIconResource::icon(CQIconResource::fileSave), "&Save", this);
   connect(mpaSave, SIGNAL(activated()), this, SLOT(slotFileSave()));
   mpaSave->setShortcut(Qt::CTRL + Qt::Key_S);
   mpaSaveAs = new QAction(CQIconResource::icon(CQIconResource::fileSaveas), "Save &As...", this);
   connect(mpaSaveAs, SIGNAL(activated()), this, SLOT(slotFileSaveAs()));
   mpaSaveAs->setShortcut(Qt::SHIFT + Qt::CTRL + Qt::Key_S);
   mpaImportSBML = new QAction(CQIconResource::icon(CQIconResource::fileOpen), "&Import SBML...", this);
   connect(mpaImportSBML, SIGNAL(activated()), this, SLOT(slotImportSBML()));
   mpaImportSBML->setShortcut(Qt::CTRL + Qt::Key_I);
   mpaExportSBML = new QAction(CQIconResource::icon(CQIconResource::fileExport), "&Export SBML...", this);
   connect(mpaExportSBML, SIGNAL(activated()), this, SLOT(slotExportSBML()));
   mpaExportSBML->setShortcut(Qt::CTRL + Qt::Key_E);
   mpaExportODE = new QAction(CQIconResource::icon(CQIconResource::fileExport), "Export ODEs...", this);
   connect(mpaExportODE, SIGNAL(activated()), this, SLOT(slotExportMathModel()));
   mpaExportODE->setShortcut(Qt::CTRL + Qt::Key_M);
   mpaQuit = new QAction("&Quit", this);
   connect(mpaQuit, SIGNAL(activated()), this, SLOT(slotQuit()));
   mpaQuit->setShortcut(Qt::CTRL + Qt::Key_Q);
   mpaSliders = new QAction(CQIconResource::icon(CQIconResource::slider), "Show sliders", this);
   mpaSliders->setCheckable(true);
   connect(mpaSliders, SIGNAL(toggled(bool)), this, SLOT(slotShowSliders(bool)));
   mpaObjectBrowser = new QAction("Object &Browser", this);
   mpaObjectBrowser->setCheckable(true);
   connect(mpaObjectBrowser, SIGNAL(toggled(bool)), this, SLOT(slotShowObjectBrowserDialog(bool)));
   mpaCheckModel = new QAction(CQIconResource::icon(CQIconResource::checkMark), "Check model", this);
   connect(mpaCheckModel, SIGNAL(activated()), this, SLOT(slotCheckModel()));
   mpaUpdateMIRIAM = new QAction(CQIconResource::icon(CQIconResource::miriam), "Update MIRIAM", this);
   connect(mpaUpdateMIRIAM, SIGNAL(activated()), this, SLOT(slotUpdateMIRIAM()));
   mpaApplyInitialState = new QAction(CQIconResource::icon(CQIconResource::isToS), "Apply initial state", this);
   connect(mpaApplyInitialState, SIGNAL(activated()), this, SLOT(slotApplyInitialState()));
   mpaUpdateInitialState = new QAction(CQIconResource::icon(CQIconResource::sToIs), "Update initial state from current state", this);
   connect(mpaUpdateInitialState, SIGNAL(activated()), this, SLOT(slotUpdateInitialState()));
   mpaCapture = new QAction(CQIconResource::icon(CQIconResource::captureImage), "Capture the main window", this);
   connect(mpaCapture, SIGNAL(activated()), this, SLOT(slotCapture()));
   mpaExpandModel = new QAction("Create array of compartments (debug version)", this);
   connect(mpaExpandModel, SIGNAL(activated()), this, SLOT(slotExpandModel()));
   mpaFontSelectionDialog = new QAction("Select the Application Font", this);
   connect(mpaFontSelectionDialog, SIGNAL(activated()), this, SLOT(slotFontSelection()));
   //TODO SEDML
 #ifdef COPASI_SEDML
   mpaOpenSEDMLFiles = new QAction(CQIconResource::icon(CQIconResource::fileOpen), "S&ED-ML Files...", this);
   connect(mpaOpenSEDMLFiles, SIGNAL(activated()), this, SLOT(slotFileExamplesSEDMLFiles()));
   // mpaOpenSEDMLFiles->setShortcut(Qt::CTRL + Qt::Key_3);
   mpaImportSEDML = new QAction(CQIconResource::icon(CQIconResource::fileOpen), "&Import SED-ML...", this);
   connect(mpaImportSEDML, SIGNAL(activated()), this, SLOT(slotImportSEDML()));
   // mpaImportSEDML->setShortcut(Qt::CTRL + Qt::Key_X);
   mpaExportSEDML = new QAction(CQIconResource::icon(CQIconResource::fileExport), "&Export SED-ML...", this);
   connect(mpaExportSEDML, SIGNAL(activated()), this, SLOT(slotExportSEDML()));
   // mpaExportSEDML->setShortcut(Qt::CTRL + Qt::Key_Z);
 #endif
   //     QAction* mpaObjectBrowser;
 #ifdef WITH_MERGEMODEL
   mpaAddModel = new QAction(CQIconResource::icon(CQIconResource::fileAdd), "&Add ...", this);
   mpaAddModel->setShortcut(Qt::SHIFT + Qt::CTRL + Qt::Key_A);
   connect(mpaAddModel, SIGNAL(activated()), this, SLOT(slotAddFileOpen()));
   mpaMergeModels = new QAction("&Merge ...", this);
   mpaMergeModels->setShortcut(Qt::SHIFT + Qt::CTRL + Qt::Key_M);
   connect(mpaMergeModels, SIGNAL(activated()), this, SLOT(slotMergeModels()));
 #endif
   mpaCloseAllWindows = new QAction("Close all windows below:", this);
   connect(mpaCloseAllWindows, SIGNAL(activated()), this, SLOT(slotCloseAllWindows()));
   mpaFunctionDBLoad =  new QAction(CQIconResource::icon(CQIconResource::fileOpen), "Load Function DB...", this);
   connect(mpaFunctionDBLoad, SIGNAL(activated()), this, SLOT(slotFunctionDBLoad()));
   mpaFunctionDBSave =  new QAction(CQIconResource::icon(CQIconResource::fileSaveas), "Save Function DB...", this);
   connect(mpaFunctionDBSave, SIGNAL(activated()), this, SLOT(slotFunctionDBSave()));
 }
void CopasiUI3Window::createMenuBar () private
Definition at line 489 of file copasiui3window.cpp.
References about(), aboutQt(), license(), mpaApplyInitialState, mpaCapture, mpaCheckModel, mpaExpandModel, mpaExportODE, mpaExportSBML, mpaFontSelectionDialog, mpaFunctionDBLoad, mpaFunctionDBSave, mpaImportSBML, mpaNew, mpaObjectBrowser, mpaOpen, mpaOpenCopasiFiles, mpaOpenSBMLFiles, mpaQuit, mpaSave, mpaSaveAs, mpaSliders, mpaUpdateInitialState, mpaUpdateMIRIAM, mpMenuExamples, mpMenuRecentFiles, mpMenuRecentSBMLFiles, mpTools, mpWindowsMenu, refreshRecentFileMenu(), refreshRecentSBMLFileMenu(), refreshWindowsMenu(), slotConvertToIrreversible(), slotPreferences(), and slotTutorialWizard().
Referenced by CopasiUI3Window().
 {
   QMenu * pFileMenu = menuBar()->addMenu("&File");
   pFileMenu->addAction(mpaNew);
   pFileMenu->addAction(mpaOpen);
   mpMenuExamples = pFileMenu->addMenu("Examples");
   mpMenuExamples->addAction(mpaOpenCopasiFiles);
   mpMenuExamples->addAction(mpaOpenSBMLFiles);
 #ifdef COPASI_SEDML
   mpMenuExamples->addAction(mpaOpenSEDMLFiles);
 #endif
   pFileMenu->addAction(mpaSave);
   pFileMenu->addAction(mpaSaveAs);
   pFileMenu->addSeparator();
   pFileMenu->addAction(mpaImportSBML);
   pFileMenu->addAction(mpaExportSBML);
   pFileMenu->addAction(mpaExportODE);
   //TODO SEDML
 #ifdef COPASI_SEDML
   pFileMenu->addSeparator();
   mpMenuSEDMLSupport = pFileMenu->addMenu("SED-ML Support");
   mpMenuSEDMLSupport->addAction(mpaImportSEDML);
   mpMenuSEDMLSupport->addAction(mpaExportSEDML);
   mpMenuRecentSEDMLFiles = mpMenuSEDMLSupport->addMenu("Recent SED-ML Files");
   refreshRecentSEDMLFileMenu();
 #endif
 #ifdef WITH_MERGEMODEL
   pFileMenu->addAction(mpaAddModel);
   //pFileMenu->addAction(mpaMergeModels);
 #endif
   pFileMenu->addSeparator();
   pFileMenu->addAction(mpaFunctionDBLoad);
   pFileMenu->addAction(mpaFunctionDBSave);
   pFileMenu->addSeparator();
   mpMenuRecentFiles = pFileMenu->addMenu("Recent Files");
   refreshRecentFileMenu();
   mpMenuRecentSBMLFiles = pFileMenu->addMenu("Recent SBML Files");
   refreshRecentSBMLFileMenu();
   pFileMenu->addSeparator();
   pFileMenu->addAction(mpaQuit);
   //****** tools menu **************
   mpTools = menuBar()->addMenu("&Tools");
   mpTools->addAction(mpaApplyInitialState);
   mpTools->addAction(mpaUpdateInitialState);
   mpTools->addAction(mpaSliders);
   mpTools->addAction(mpaCapture);
 #ifdef WITH_MERGEMODEL
   mpTools->addAction(mpaMergeModels);
 #endif
   mpTools->addSeparator();
   mpTools->addAction(mpaExpandModel);
 #ifdef COPASI_DEBUG
   mpTools->addAction(mpaObjectBrowser);
   mpTools->addSeparator();
 #endif // COPASI_DEBUG
   mpTools->addAction(mpaCheckModel);
   mpTools->addAction("&Convert to irreversible", this, SLOT(slotConvertToIrreversible()));
 #ifdef WITH_PE_EVENT_CREATION
   mpTools->addAction("&Create Events For Timeseries Experiment", this, SLOT(slotCreateEventsForTimeseries()));
 #endif
 #ifdef COPASI_SBW_INTEGRATION
   // create and populate SBW menu
   mpSBWMenu = new QMenu("&SBW", this);
   mpSBWAction = mpTools->addMenu(mpSBWMenu);
 #endif // COPASI_SBW_INTEGRATION
   mpTools->addSeparator();
   mpTools->addAction(mpaUpdateMIRIAM);
   mpTools->addAction("&Preferences", this, SLOT(slotPreferences()));
   mpTools->addAction(mpaFontSelectionDialog);
   //****** windows menu **************
   mpWindowsMenu =  menuBar()->addMenu("&Window");
   refreshWindowsMenu();
   //*******  help menu *****************
   menuBar()->addSeparator();
   QMenu * help = menuBar()->addMenu("&Help");
   help->addAction("Simple &Wizard", this, SLOT(slotTutorialWizard()));
   help->addSeparator();
   help->addAction("&About", this, SLOT(about()), Qt::Key_F1);
   help->addAction("&License", this, SLOT(license()));
   help->addAction("About &Qt", this, SLOT(aboutQt()));
   help->addSeparator();
   // help->addAction("What's &This", this, SLOT(whatsThis()), Qt::SHIFT + Qt::Key_F1);
 }
void CopasiUI3Window::createToolBar () private
Definition at line 457 of file copasiui3window.cpp.
References mpaApplyInitialState, mpaCapture, mpaCheckModel, mpaNew, mpaOpen, mpaSave, mpaSliders, mpaUpdateInitialState, mpaUpdateMIRIAM, mpBoxSelectFramework, and slotFrameworkChanged().
Referenced by CopasiUI3Window().
 {
   QToolBar * tb = addToolBar("MainToolBar");
   tb->addAction(mpaNew);
   tb->addAction(mpaOpen);
   tb->addAction(mpaSave);
   tb->addAction(mpaCapture);
   tb->addAction(mpaSliders);
   tb->addAction(mpaCheckModel);
   tb->addAction(mpaApplyInitialState);
   tb->addAction(mpaUpdateInitialState);
   tb->addAction(mpaUpdateMIRIAM);
 #ifdef WITH_MERGEMODEL
   tb->addAction(mpaAddModel);
   //tb->addAction(mpaMergeModels);
 #endif
   tb->addSeparator();
   mpBoxSelectFramework = new QComboBox(tb);
   QStringList items;
   items << "Concentrations" << "Particle Numbers";
   mpBoxSelectFramework->addItems(items);
   tb->addWidget(mpBoxSelectFramework);
   connect(mpBoxSelectFramework, SIGNAL(activated(int)), this, SLOT(slotFrameworkChanged(int)));
   setUnifiedTitleAndToolBarOnMac(true);
 }
void CopasiUI3Window::customEvent (QEvent *) protected slot
Definition at line 2727 of file copasiui3window.cpp.
 {}
void CopasiUI3Window::disableSliders (bool disable)
The slider dialog has to be disabled before a task is run and reenabled afterwards. Actually the methods stores the state when the value true is passed and restores that state when the value false is passed.
Definition at line 2792 of file copasiui3window.cpp.
References mpSliders, mSliderDialogEnabled, and SliderDialog::updateAllSliders().
Referenced by CProgressBar::CProgressBar(), and CProgressBar::finish().
 {
   if (disable)
     {
       this->mSliderDialogEnabled = this->mpSliders->isEnabled();
       this->mpSliders->setEnabled(false);
     }
   else
     {
       this->mpSliders->setEnabled(this->mSliderDialogEnabled);
       this->mpSliders->updateAllSliders();
     }
 }
void CopasiUI3Window::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 2731 of file copasiui3window.cpp.
 {
   if (event->mimeData()->hasFormat("text/uri-list"))
     event->acceptProposedAction();
 }
void CopasiUI3Window::dropEvent (QDropEvent * event) protected
Definition at line 2762 of file copasiui3window.cpp.
References isProabablySBML(), slotFileOpen(), and slotImportSBML().
 {
   QList<QUrl> urls = event->mimeData()->urls();
   if (urls.isEmpty())
     return;
   QString fileName = urls.first().toLocalFile();
   if (fileName.isEmpty())
     return;
   if (isProabablySBML(fileName))
     slotImportSBML(fileName);
 #ifdef COPASI_SEDML
   else if (isProabablySBML(fileName))
     slotImportSEDML(fileName);
 #endif
   else
     slotFileOpen(fileName);
 }
void CopasiUI3Window::exportSBMLToString (std::string & SBML)
Definition at line 1932 of file copasiui3window.cpp.
References DataModelGUI::commit(), DataModelGUI::exportSBMLToString(), mpDataModelGUI, and slotExportSBMLToStringFinished().
 {
   mpDataModelGUI->commit();
   if (mpDataModelGUI)
     {
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotExportSBMLToStringFinished(bool)));
       mpDataModelGUI->exportSBMLToString(SBML);
     }
 }
DataModelGUI * CopasiUI3Window::getDataModel ()
Definition at line 1729 of file copasiui3window.cpp.
References mpDataModelGUI.
Referenced by SliderDialog::addSlider(), SliderDialog::createSlidersForFolder(), SliderDialog::updateAllSliders(), and Worker::Worker().
 {return mpDataModelGUI;}
ListViews * CopasiUI3Window::getMainWidget ()
Definition at line 1739 of file copasiui3window.cpp.
References mpListView.
Referenced by Worker::finishedLoading(), Worker::getWidgetForTask(), SliderDialog::runCrossSectionTask(), SliderDialog::runLNATask(), SliderDialog::runMCATask(), SliderDialog::runOptimizationTask(), SliderDialog::runParameterEstimationTask(), SliderDialog::runScanTask(), SliderDialog::runSteadyStateTask(), SliderDialog::runTask(), SliderDialog::runTimeCourse(), and WizardDialog::textBrowser_anchorClicked().
 {
   return mpListView;
 }
CopasiUI3Window * CopasiUI3Window::getMainWindow () static
Definition at line 105 of file copasiui3window.cpp.
References pMainWindow.
Referenced by CWindowInterface::addToMainWindow(), TaskWidget::commonAfterRunTask(), TaskWidget::commonBeforeRunTask(), COutputHandlerPlot::compile(), CProgressBar::CProgressBar(), CQLayoutThread::CQLayoutThread(), CQMessageBox::CQMessageBox(), CProgressBar::create(), CProgressBar::finish(), CWindowInterface::removeFromMainWindow(), slotQuit(), CQProgressDialog::timerShow(), and CQMessageBox::~CQMessageBox().
 {
   return pMainWindow;
 }
const QList< QPointer< QMainWindow > > & CopasiUI3Window::getWindows () const
Returns the list of current windows
Definition at line 1961 of file copasiui3window.cpp.
References mWindows.
Referenced by Worker::slotNotify().
 {
   return mWindows;
 }
void CopasiUI3Window::importSBMLFromString (const std::string & sbmlDocumentText)
This is used to import an SBML file from a std::string in the GUI it does all the necessary GUI stuff like asking to save the old document, displaying messages, etc.
Definition at line 1305 of file copasiui3window.cpp.
References DataModelGUI::commit(), ListViews::DELETE, CCopasiRootContainer::getDatamodelList(), DataModelGUI::importSBMLFromString(), SliderDialog::isChanged(), mCommitRequired, ListViews::MODEL, mpDataModelGUI, mpListView, mpSliders, DataModelGUI::notify(), CQMessageBox::question(), slotFileSave(), slotImportSBMLFromStringFinished(), and ListViews::switchToOtherWidget().
 {
   if (mCommitRequired)
     {
       mpDataModelGUI->commit();
     }
   if (!sbmlDocumentText.empty())
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       if (mpDataModelGUI && ((*CCopasiRootContainer::getDatamodelList())[0]->isChanged() || this->mpSliders->isChanged()))
         {
           switch (CQMessageBox::question(this, "COPASI",
                                          "The document contains unsaved changes\n"
                                          "Do you want to save the changes before exiting?",
                                          QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel,
                                          QMessageBox::Save))
             {
               case QMessageBox::Save:
                 mCommitRequired = false;
                 slotFileSave();
                 break;
               case QMessageBox::Discard:
                 break;
               case QMessageBox::Cancel:
               default:
                 return;
                 break;
             }
         }
       mpDataModelGUI->notify(ListViews::MODEL, ListViews::DELETE,
                              (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
       mpListView->switchToOtherWidget(0, "");
       if (!mpDataModelGUI)
         {
           mpDataModelGUI = new DataModelGUI(this); // create a new data model
         }
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotImportSBMLFromStringFinished(bool)));
       mpDataModelGUI->importSBMLFromString(sbmlDocumentText);
     }
 }
bool CopasiUI3Window::isMainThread () static
Definition at line 111 of file copasiui3window.cpp.
References mpMainThread, and pMainWindow.
Referenced by CProgressBar::addItem(), COutputHandlerPlot::compile(), CProgressBar::create(), CQMessageBox::critical(), CProgressBar::finish(), CProgressBar::finishItem(), CQMessageBox::information(), CProgressBar::progressItem(), CQMessageBox::question(), CProgressBar::setName(), and CQMessageBox::warning().
 {
   return pMainWindow == NULL || pMainWindow->mpMainThread == QThread::currentThread();
 }
void CopasiUI3Window::license () protected slot
Definition at line 1252 of file copasiui3window.cpp.
References FixedTitle, and CCopasiRootContainer::getLicenseHTML().
Referenced by createMenuBar().
 {
   AboutDialog* aboutDialog = new AboutDialog(this, CCopasiRootContainer::getLicenseHTML(), 76, 30);
   aboutDialog->setWindowTitle(FixedTitle);
   aboutDialog->exec();
 }
void CopasiUI3Window::listViewsFolderChanged (const QModelIndex & index) protected slot
Definition at line 1732 of file copasiui3window.cpp.
References ListViews::getCurrentItemId(), mpListView, mpSliders, refreshWindowsMenu(), and SliderDialog::setCurrentFolderId().
Referenced by CopasiUI3Window().
 {
   size_t id = mpListView->getCurrentItemId();
   this->mpSliders->setCurrentFolderId(id);
   refreshWindowsMenu();
 }
const bool & CopasiUI3Window::messageShown () const
Definition at line 2076 of file copasiui3window.cpp.
References mMessageShown.
 {
   return mMessageShown;
 }
void CopasiUI3Window::newDoc () protected slot
Definition at line 700 of file copasiui3window.cpp.
References ListViews::ADD, DataModelGUI::commit(), DataModelGUI::createModel(), ListViews::DELETE, ListViews::getCurrentWidget(), CCopasiRootContainer::getDatamodelList(), SliderDialog::isChanged(), mCommitRequired, mNewFile, ListViews::MODEL, mpaExportODE, mpaExportSBML, mpaSave, mpaSaveAs, mpDataModelGUI, mpListView, mpSliders, mSaveAsRequired, DataModelGUI::notify(), CQMessageBox::question(), SliderDialog::reset(), CQTabWidget::selectTab(), SliderDialog::setChanged(), signalLoadFile(), slotFileSave(), ListViews::switchToOtherWidget(), and updateTitle().
Referenced by createActions(), openInitialDocument(), and slotFileOpenFinished().
 {
   disconnect(this, SIGNAL(signalLoadFile(QString)), this, SLOT(newDoc()));
   if (mCommitRequired)
     {
       mpDataModelGUI->commit();
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (mpDataModelGUI && ((*CCopasiRootContainer::getDatamodelList())[0]->isChanged() || this->mpSliders->isChanged()))
     {
       switch (CQMessageBox::question(this, "COPASI",
                                      "The document contains unsaved changes\n"
                                      "Do you want to save the changes before exiting?",
                                      QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel,
                                      QMessageBox::Save))
         {
           case QMessageBox::Save:
             connect(this, SIGNAL(signalLoadFile(QString)), this, SLOT(newDoc()));
             mNewFile = "newDoc()";
             mCommitRequired = false;
             slotFileSave();
             return;
             break;
           case QMessageBox::Discard:
             break;
           case QMessageBox::Cancel:
           default:
             return;
             break;
         }
     }
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::DELETE,
                          (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
   mpListView->switchToOtherWidget(0, "");
   // delete the old sliders
   if (this->mpSliders) this->mpSliders->reset();
   mpDataModelGUI->createModel();
   this->mpSliders->setChanged(false);
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::ADD, (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
   //if (!mbObject_browser_open)
   //mpFileMenu->setItemEnabled(nobject_browser, true);
   mpaSave->setEnabled(true);
   mpaSaveAs->setEnabled(true);
   mpaExportSBML->setEnabled(true);
   mpaExportODE->setEnabled(true);
 #ifdef COPASI_SEDML
   mpaExportSEDML->setEnabled(true);
 #endif
   updateTitle();
   mpListView->switchToOtherWidget(1, "");
   CQTabWidget *widget = dynamic_cast<CQTabWidget *>(mpListView->getCurrentWidget());
   if (widget != NULL)
     widget->selectTab(0);
   mSaveAsRequired = true;
   mCommitRequired = true;
 }
void CopasiUI3Window::openInitialDocument (const QString & file) slot
Definition at line 773 of file copasiui3window.cpp.
References COptions::compareValue(), FROM_UTF8, COptions::getNonOptions(), COptions::getValue(), newDoc(), slotFileOpen(), and slotImportSBML().
Referenced by CQCopasiApplication::setMainWindow(), and Worker::Worker().
 {
   if (file != "")
     {
       slotFileOpen(file);
     }
   else if (!COptions::compareValue("ImportSBML", std::string("")))
     {
       // Import the SBML File
       std::string ImportSBML;
       COptions::getValue("ImportSBML", ImportSBML);
       slotImportSBML(FROM_UTF8(ImportSBML));
     }
 #ifdef COPASI_SEDML
   else if (!COptions::compareValue("ImportSEDML", std::string("")))
     {
       // Import the SEDML File
       std::string ImportSEDML;
       COptions::getValue("ImportSEDML", ImportSEDML);
       slotImportSEDML(FROM_UTF8(ImportSEDML));
     }
 #endif
   else if (COptions::getNonOptions().size())
     {
       // Look at commandline
       slotFileOpen(FROM_UTF8(COptions::getNonOptions()[0]));
     }
   else
     {
       newDoc();
     }
 #ifdef COPASI_SBW_INTEGRATION
   sbwConnect();
 #endif // COPASI_SBW_INTEGRATION
 }
void CopasiUI3Window::refreshRecentFileMenu () private
Definition at line 1866 of file copasiui3window.cpp.
References CCopasiParameterGroup::beginIndex(), C_INT, CCopasiParameterGroup::endIndex(), FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiParameterGroup::getGroup(), CConfigurationFile::getRecentFiles(), mpMenuRecentFiles, mpRecentFilesActionGroup, mRecentFilesActionMap, and slotOpenRecentFile().
Referenced by createMenuBar(), slotFileOpenFinished(), and slotFileSaveFinished().
 {
   mpMenuRecentFiles->clear();
   mRecentFilesActionMap.clear();
   if (mpRecentFilesActionGroup != NULL)
     {
       disconnect(mpRecentFilesActionGroup, SIGNAL(triggered(QAction *)), this, SLOT(slotOpenRecentFile(QAction *)));
       mpRecentFilesActionGroup->deleteLater();
       mpRecentFilesActionGroup = NULL;
     }
   mpRecentFilesActionGroup = new QActionGroup(this);
   connect(mpRecentFilesActionGroup, SIGNAL(triggered(QAction *)), this, SLOT(slotOpenRecentFile(QAction *)));
   QAction * pAction;
   CCopasiParameterGroup::index_iterator it =
     CCopasiRootContainer::getConfiguration()->getRecentFiles().getGroup("Recent Files")->beginIndex();
   CCopasiParameterGroup::index_iterator end =
     CCopasiRootContainer::getConfiguration()->getRecentFiles().getGroup("Recent Files")->endIndex();
   C_INT Index = 0;
   for (; it != end; ++it, ++Index)
     {
       pAction = new QAction(FROM_UTF8(*(*it)->getValue().pSTRING), mpRecentFilesActionGroup);
       mpMenuRecentFiles->addAction(pAction);
       mRecentFilesActionMap[pAction] = Index;
     }
 }
void CopasiUI3Window::refreshRecentSBMLFileMenu () private
Definition at line 1899 of file copasiui3window.cpp.
References CCopasiParameterGroup::beginIndex(), C_INT, CCopasiParameterGroup::endIndex(), FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiParameterGroup::getGroup(), CConfigurationFile::getRecentSBMLFiles(), mpMenuRecentSBMLFiles, mpRecentSBMLFilesActionGroup, mRecentSBMLFilesActionMap, and slotOpenRecentSBMLFile().
Referenced by createMenuBar(), slotExportSBMLFinished(), and slotImportSBMLFinished().
 {
   mpMenuRecentSBMLFiles->clear();
   mRecentSBMLFilesActionMap.clear();
   if (mpRecentSBMLFilesActionGroup != NULL)
     {
       disconnect(mpRecentSBMLFilesActionGroup, SIGNAL(triggered(QAction *)), this, SLOT(slotOpenRecentSBMLFile(QAction *)));
       mpRecentSBMLFilesActionGroup->deleteLater();
       mpRecentSBMLFilesActionGroup = NULL;
     }
   mpRecentSBMLFilesActionGroup = new QActionGroup(this);
   connect(mpRecentSBMLFilesActionGroup, SIGNAL(triggered(QAction *)), this, SLOT(slotOpenRecentSBMLFile(QAction *)));
   QAction * pAction;
   CCopasiParameterGroup::index_iterator it =
     CCopasiRootContainer::getConfiguration()->getRecentSBMLFiles().getGroup("Recent Files")->beginIndex();
   CCopasiParameterGroup::index_iterator end =
     CCopasiRootContainer::getConfiguration()->getRecentSBMLFiles().getGroup("Recent Files")->endIndex();
   C_INT Index = 0;
   for (; it != end; ++it, ++Index)
     {
       pAction = new QAction(FROM_UTF8(*(*it)->getValue().pSTRING), mpRecentSBMLFilesActionGroup);
       mpMenuRecentSBMLFiles->addAction(pAction);
       mRecentSBMLFilesActionMap[pAction] = Index;
     }
 }
void CopasiUI3Window::refreshWindowsMenu () private
Definition at line 1984 of file copasiui3window.cpp.
References CWindowInterface::getWindowMenu(), mpaCloseAllWindows, mpWindowsActionGroup, mpWindowsMenu, mWindows, and slotActivateWindowTriggered().
Referenced by addWindow(), createMenuBar(), listViewsFolderChanged(), removeWindow(), and slotCloseAllWindows().
 {
   // (I assume a QActionGroup was used, so only one window will be activated at a time)
   if (mpWindowsActionGroup != NULL)
     {
       disconnect(mpWindowsActionGroup, SIGNAL(triggered(QAction *)), this, SLOT(slotActivateWindowTriggered(QAction *)));
       mpWindowsActionGroup->deleteLater();
       mpWindowsActionGroup = NULL;
     }
   mpWindowsActionGroup = new QActionGroup(this);
   connect(mpWindowsActionGroup, SIGNAL(triggered(QAction *)), this, SLOT(slotActivateWindowTriggered(QAction *)));
   // Re-initialize items the menus will always have
   mpWindowsMenu->clear();
   // COPASI main window
   QAction * pAction = new QAction(mWindows[0]->windowTitle(), mpWindowsActionGroup);
   mpWindowsMenu->addAction(pAction);
   if (mWindows.count() > 1)
     {
       mpWindowsMenu->addSeparator();
       mpWindowsMenu->addAction(mpaCloseAllWindows);
       mpWindowsMenu->addSeparator();
     }
   // . . . for the secondary windows, also . . .
   for (int index = 1; index < mWindows.count(); ++index)
     {
       QMainWindow* mainWindow = mWindows[index];
       if (mainWindow == NULL) continue;
       CWindowInterface* window = dynamic_cast<CWindowInterface*>(mainWindow);
       QMenu* menu = window->getWindowMenu();
       menu->clear();
       menu->addAction(pAction);
       menu->addSeparator();
       menu->addAction(mpaCloseAllWindows);
       menu->addSeparator();
     }
   // Add secondary windows to the Window menus
   for (int index = 1; index < mWindows.count(); ++index)
     {
       QMainWindow* mActionWindow = mWindows[index];
       if (mActionWindow == NULL) continue;
       pAction = new QAction(mWindows[index]->windowTitle(), mpWindowsActionGroup);
       mpWindowsMenu->addAction(pAction);
       for (int index1 = 1; index1 < mWindows.count(); ++index1)
         {
           QMainWindow* mainWindow = mWindows[index1];
           if (mainWindow == NULL) continue;
           CWindowInterface* window = dynamic_cast<CWindowInterface*>(mainWindow);
           QMenu* menu = window->getWindowMenu();
           menu->addAction(pAction);
         }
     }
 }
void CopasiUI3Window::removeWindow (QMainWindow * pWindow)
Definition at line 1972 of file copasiui3window.cpp.
References mWindows, and refreshWindowsMenu().
Referenced by PlotWindow::closeEvent(), CWindowInterface::removeFromMainWindow(), and slotShowSliders().
 {
   int index = mWindows.indexOf(pWindow);
   if (index == -1)
     return;
   // only delete when there is such a window
   mWindows.removeAt(index);
   refreshWindowsMenu();
 }
void CopasiUI3Window::setApplicationFont () private
Definition at line 2250 of file copasiui3window.cpp.
References FROM_UTF8, CConfigurationFile::getApplicationFont(), CCopasiRootContainer::getConfiguration(), CConfigurationFile::setApplicationFont(), and TO_UTF8.
Referenced by CopasiUI3Window().
 {
   std::string ApplicationFont = CCopasiRootContainer::getConfiguration()->getApplicationFont();
   if (ApplicationFont == "")
     {
       return;
     }
   QFont Font = qApp->font();
   if (ApplicationFont == TO_UTF8(Font.toString()))
     {
       // We are using the default
       CCopasiRootContainer::getConfiguration()->setApplicationFont("");
       return;
     }
   // The user has chosen another font
   Font.fromString(FROM_UTF8(ApplicationFont));
   qApp->setFont(Font);
   // This appears to load the fonts, etc. from the previous configuration.
   // Two calls so that the tabwidget labels are correct
   qApp->setStyleSheet(" * {font : }");
   qApp->setStyleSheet(" * {font : }");
 }
void CopasiUI3Window::setMessageShown (const bool & shown)
Definition at line 2071 of file copasiui3window.cpp.
References mMessageShown.
Referenced by CQMessageBox::CQMessageBox(), and CQMessageBox::~CQMessageBox().
 {
   mMessageShown = shown;
 }
void CopasiUI3Window::signalLoadFile (QString newFile) signal
Referenced by newDoc(), slotFileOpen(), slotFileSaveFinished(), and slotImportSBML().
void CopasiUI3Window::signalQuit () signal
Referenced by CleanUp().
void CopasiUI3Window::slotActivateWindowTriggered (QAction * action) protected slot
Definition at line 2063 of file copasiui3window.cpp.
References getWindowByTitle(), and mWindows.
Referenced by refreshWindowsMenu().
 {
   QMainWindow *window  = getWindowByTitle(mWindows, action->text());
   if (window != NULL)
     window ->activateWindow();
 }
void CopasiUI3Window::slotApplyInitialState () protected slot
Definition at line 2155 of file copasiui3window.cpp.
References CModel::applyInitialValues(), ListViews::CHANGE, DataModelGUI::commit(), CModel::compileIfNecessary(), CCopasiRootContainer::getDatamodelList(), mpDataModelGUI, DataModelGUI::notify(), ListViews::STATE, and CModel::updateNonSimulatedValues().
Referenced by createActions().
 {
   mpDataModelGUI->commit();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel *pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   if (pModel != NULL)
     {
       pModel->compileIfNecessary(NULL);
       pModel->applyInitialValues();
       pModel->updateNonSimulatedValues();
       mpDataModelGUI->notify(ListViews::STATE, ListViews::CHANGE, (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
     }
 }
void CopasiUI3Window::slotCapture () protected slot
Definition at line 2197 of file copasiui3window.cpp.
References C_INT32, checkSelection(), ListViews::getCurrentWidget(), CopasiFileDialog::getSaveFileName(), and mpListView.
Referenced by createActions().
 {
   QPixmap pixmap = QPixmap::grabWidget(mpListView->getCurrentWidget());
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName = CopasiFileDialog::getSaveFileName(this,
                  "Save File Dialog", "untitled.png", "PNG Files (*.png)", "Save Capture as PNG file");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   pixmap.save(fileName, "PNG");
 }
void CopasiUI3Window::slotCheckModel () protected slot
Definition at line 2082 of file copasiui3window.cpp.
References FROM_UTF8, CCopasiRootContainer::getDatamodelList(), and CModelAnalyzer::writeReport().
Referenced by createActions().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModelAnalyzer MA((*CCopasiRootContainer::getDatamodelList())[0]->getModel());
   std::ostringstream ss;
   // MA.writeReport(ss, true, false);
   MA.writeReport(ss, true, true);
   CQCheckModelWindow * checkModelWindow = new CQCheckModelWindow(this);
   checkModelWindow->setWindowTitle("Check Model");
   checkModelWindow->textEdit->setText(FROM_UTF8(ss.str()));
   checkModelWindow->show();
 }
void CopasiUI3Window::slotCloseAllWindows () protected slot
Definition at line 2049 of file copasiui3window.cpp.
References mWindows, and refreshWindowsMenu().
Referenced by createActions().
 {
   // all except main window (index == 0)
   for (int index = mWindows.count() - 1; index >= 1 ; --index)
     {
       QMainWindow* window = mWindows[index];
       if (window != NULL)
         window->close();
     }
   refreshWindowsMenu();
 }
void CopasiUI3Window::slotConvertToIrreversible () protected slot
Definition at line 1691 of file copasiui3window.cpp.
References ListViews::CHANGE, CCopasiMessage::clearDeque(), DataModelGUI::commit(), CModel::convert2NonReversible(), CCopasiMessage::getAllMessageText(), CCopasiRootContainer::getDatamodelList(), CQMessageBox::information(), ListViews::MODEL, mpDataModelGUI, mpListView, DataModelGUI::notify(), and ListViews::switchToOtherWidget().
Referenced by createMenuBar().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel* model = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   if (!model) return;
   mpDataModelGUI->commit();
   mpListView->switchToOtherWidget(114, "");
   CCopasiMessage::clearDeque();
   if (!model->convert2NonReversible())
     {
       // Display error messages.
       CQMessageBox::information(this, "Conversion Failed",
                                 CCopasiMessage::getAllMessageText().c_str(),
                                 QMessageBox::Ok | QMessageBox::Default,
                                 QMessageBox::NoButton);
       CCopasiMessage::clearDeque();
     }
   (*CCopasiRootContainer::getDatamodelList())[0]->changed();
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::CHANGE, "");
 }
void CopasiUI3Window::slotExpandModel () protected slot
Definition at line 2279 of file copasiui3window.cpp.
References ListViews::CHANGE, ListViews::MODEL, mpDataModelGUI, and DataModelGUI::notify().
Referenced by createActions().
 {
   CQExpandModelData *widget = new CQExpandModelData;
   widget->exec();
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::CHANGE, "");
 }
void CopasiUI3Window::slotExportMathModel () protected slot
Definition at line 1585 of file copasiui3window.cpp.
References CDirEntry::baseName(), C_INT32, checkSelection(), DataModelGUI::commit(), CDirEntry::dirName(), DataModelGUI::exportMathModel(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getFileName(), CopasiFileDialog::getSaveFileName(), mpDataModelGUI, CDirEntry::Separator, slotExportMathModelFinished(), and TO_UTF8.
Referenced by createActions().
 {
   mpDataModelGUI->commit();
   C_INT32 Answer = QMessageBox::No;
   QString tmp;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   QString *userFilter = new QString;
   while (Answer == QMessageBox::No)
     {
       QString Default = QString::null;
       if (pDataModel->getFileName() != "")
         Default
         = FROM_UTF8(CDirEntry::dirName(pDataModel->getFileName())
                     + CDirEntry::Separator
                     + CDirEntry::baseName(pDataModel->getFileName()));
       else
         Default = "untitled.c";
       tmp =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           Default,
                                           "C Files (*.c);;Berkeley Madonna Files (*.mmd);;XPPAUT (*.ode)",
                                           "Choose an export format", userFilter);
       if (tmp.isEmpty()) return;
 #ifdef DEBUG_UI
       qDebug() << "user's filter pointer = " << *userFilter;
 #endif
       // Checks whether the file exists
       Answer = checkSelection(tmp);
       if (Answer == QMessageBox::Cancel) return;
     }
   if (mpDataModelGUI && !tmp.isNull())
     {
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotExportMathModelFinished(bool)));
       mpDataModelGUI->exportMathModel(TO_UTF8(tmp), TO_UTF8(*userFilter), true);
     }
 }
void CopasiUI3Window::slotExportMathModelFinished (bool success) protected slot
Definition at line 1635 of file copasiui3window.cpp.
References CCopasiMessage::clearDeque(), CQMessageBox::critical(), CCopasiMessage::getAllMessageText(), MCCopasiMessage, mpDataModelGUI, and CCopasiMessage::peekLastMessage().
Referenced by slotExportMathModel().
 {
   unsetCursor();
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotExportMathModelFinished(bool)));
   if (!success &&
       CCopasiMessage::peekLastMessage().getNumber() != MCCopasiMessage + 1)
     {
       CQMessageBox::critical(this, "Export Error",
                              CCopasiMessage::getAllMessageText().c_str(),
                              QMessageBox::Ok | QMessageBox::Default,
                              QMessageBox::NoButton);
       CCopasiMessage::clearDeque();
     }
 }
void CopasiUI3Window::slotExportSBML () protected slot
Definition at line 1516 of file copasiui3window.cpp.
References CDirEntry::baseName(), C_INT32, checkSelection(), DataModelGUI::commit(), CDirEntry::dirName(), DataModelGUI::exportSBML(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CQSBMLFileDialog::getSaveFileName(), mpDataModelGUI, CDirEntry::Separator, slotExportSBMLFinished(), and TO_UTF8.
Referenced by createActions().
 {
   mpDataModelGUI->commit();
   C_INT32 Answer = QMessageBox::No;
   QString tmp;
   bool exportIncomplete = false;
   int sbmlLevel = 2;
   int sbmlVersion = 4;
   while (Answer == QMessageBox::No)
     {
       QString Default = QString::null;
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       if ((*CCopasiRootContainer::getDatamodelList())[0]->getFileName() != "")
         Default
         = FROM_UTF8(CDirEntry::dirName((*CCopasiRootContainer::getDatamodelList())[0]->getFileName())
                     + CDirEntry::Separator
                     + CDirEntry::baseName((*CCopasiRootContainer::getDatamodelList())[0]->getFileName())
                     + ".xml");
       else
         {
           Default = "untitled.xml";
         }
       // if there already is an SBML model, we present the user with the Level
       // and Version of that document as the selected Level and Version to
       // export to.
       if ((*CCopasiRootContainer::getDatamodelList())[0]->getCurrentSBMLDocument() != NULL)
         {
           sbmlLevel = (*CCopasiRootContainer::getDatamodelList())[0]->getCurrentSBMLDocument()->getLevel();
           sbmlVersion = (*CCopasiRootContainer::getDatamodelList())[0]->getCurrentSBMLDocument()->getVersion();
         }
       std::pair<QString, std::pair<unsigned C_INT32, unsigned C_INT32> > nameAndVersion =
         CQSBMLFileDialog::getSaveFileName(this, "Export SBML Dialog", Default,
                                           "Choose a filename and SBML version for SBML export.",
                                           sbmlLevel,
                                           sbmlVersion);
       tmp = nameAndVersion.first;
       sbmlLevel = nameAndVersion.second.first;
       sbmlVersion = nameAndVersion.second.second;
       if (tmp.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(tmp);
       if (Answer == QMessageBox::Cancel) return;
     }
   if (mpDataModelGUI && !tmp.isNull())
     {
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotExportSBMLFinished(bool)));
       mpDataModelGUI->exportSBML(TO_UTF8(tmp), true, sbmlLevel, sbmlVersion, exportIncomplete);
     }
 }
void CopasiUI3Window::slotExportSBMLFinished (bool success) protected slot
Definition at line 1576 of file copasiui3window.cpp.
References checkPendingMessages(), mpDataModelGUI, and refreshRecentSBMLFileMenu().
Referenced by slotExportSBML().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotExportSBMLFinished(bool)));
   unsetCursor();
   checkPendingMessages();
   refreshRecentSBMLFileMenu();
 }
void CopasiUI3Window::slotExportSBMLToStringFinished (bool success) protected slot
Definition at line 1945 of file copasiui3window.cpp.
References CCopasiMessage::clearDeque(), CQMessageBox::critical(), FROM_UTF8, CCopasiMessage::getLastMessage(), and mpDataModelGUI.
Referenced by exportSBMLToString().
 {
   unsetCursor();
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotExportSBMLToStringFinished(bool)));
   if (!success)
     {
       QString Message = "Error while exporting SBML model!\n\n";
       Message += FROM_UTF8(CCopasiMessage::getLastMessage().getText());
       CQMessageBox::critical(this, QString("File Error"), Message,
                              QMessageBox::Ok, QMessageBox::Ok);
       CCopasiMessage::clearDeque();
     }
 }
void CopasiUI3Window::slotFileExamplesCopasiFiles (QString file = QString::null) protected slot
Definition at line 994 of file copasiui3window.cpp.
References CopasiFileDialog::openExampleDir(), and slotFileOpen().
Referenced by createActions().
 {
   CopasiFileDialog::openExampleDir(); //Sets CopasiFileDialog::LastDir
   slotFileOpen(file);
 }
void CopasiUI3Window::slotFileExamplesSBMLFiles (QString file = QString::null) protected slot
Definition at line 1000 of file copasiui3window.cpp.
References CopasiFileDialog::openExampleDir(), and slotImportSBML().
Referenced by createActions().
 {
   CopasiFileDialog::openExampleDir(); //Sets CopasiFileDialog::LastDir
   slotImportSBML(file);
 }
void CopasiUI3Window::slotFileOpen (QString file = QString::null) slot
Definition at line 812 of file copasiui3window.cpp.
References CCopasiMessage::clearDeque(), DataModelGUI::commit(), ListViews::DELETE, CCopasiRootContainer::getDatamodelList(), CopasiFileDialog::getOpenFileName(), SliderDialog::isChanged(), DataModelGUI::loadModel(), mCommitRequired, mNewFile, ListViews::MODEL, mpDataModelGUI, mpListView, mpSliders, DataModelGUI::notify(), CQMessageBox::question(), SliderDialog::reset(), signalLoadFile(), slotFileOpenFinished(), slotFileSave(), ListViews::switchToOtherWidget(), and TO_UTF8.
Referenced by createActions(), dropEvent(), CQCopasiApplication::event(), openInitialDocument(), slotFileExamplesCopasiFiles(), and slotOpenRecentFile().
 {
   disconnect(this, SIGNAL(signalLoadFile(QString)), this, SLOT(slotFileOpen(QString)));
   if (mCommitRequired)
     {
       mpDataModelGUI->commit();
     }
   QString newFile = "";
   if (file == "")
     newFile =
       CopasiFileDialog::getOpenFileName(this, "Open File Dialog", QString::null,
                                         "COPASI Files (*.gps *.cps);;All Files (*)",
                                         "Choose a file");
   else
     newFile = file;
   // gives the file information to the datamodel to handle it
   if (!newFile.isNull())
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       if (mpDataModelGUI && ((*CCopasiRootContainer::getDatamodelList())[0]->isChanged() || this->mpSliders->isChanged()))
         {
           switch (CQMessageBox::question(this, "COPASI",
                                          "The document contains unsaved changes\n"
                                          "Do you want to save the changes before exiting?",
                                          QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel,
                                          QMessageBox::Save))
             {
               case QMessageBox::Save:
                 connect(this, SIGNAL(signalLoadFile(QString)), this, SLOT(slotFileOpen(QString)));
                 mNewFile = newFile;
                 mCommitRequired = false;
                 slotFileSave();
                 return;
                 break;
               case QMessageBox::Discard:
                 break;
               case QMessageBox::Cancel:
               default:
                 return;
                 break;
             }
         }
       mpDataModelGUI->notify(ListViews::MODEL, ListViews::DELETE,
                              (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
       mpListView->switchToOtherWidget(0, "");
       if (this->mpSliders) this->mpSliders->reset();
       this->setCursor(Qt::WaitCursor);
       CCopasiMessage::clearDeque();
       mNewFile = newFile;
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotFileOpenFinished(bool)));
       mpDataModelGUI->loadModel(TO_UTF8(newFile));
     }
 }
void CopasiUI3Window::slotFileOpenFinished (bool success) protected slot
Definition at line 882 of file copasiui3window.cpp.
References ListViews::ADD, DataModelGUI::createModel(), CQMessageBox::critical(), FROM_UTF8, CCopasiMessage::getAllMessageText(), ListViews::getCurrentWidget(), CCopasiRootContainer::getDatamodelList(), CCopasiMessage::getLastMessage(), CCopasiMessage::getNumber(), CCopasiMessage::getText(), CDirEntry::isWritable(), MCCopasiMessage, mCommitRequired, mNewFile, ListViews::MODEL, mpaExportODE, mpaExportSBML, mpaSave, mpaSaveAs, mpDataModelGUI, mpListView, mSaveAsRequired, newDoc(), DataModelGUI::notify(), CQMessageBox::question(), refreshRecentFileMenu(), CQTabWidget::selectTab(), slotImportSBML(), CDirEntry::suffix(), ListViews::switchToOtherWidget(), TO_UTF8, updateTitle(), and CQMessageBox::warning().
Referenced by slotFileOpen().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotFileOpenFinished(bool)));
   unsetCursor();
   mCommitRequired = true;
   if (!success)
     {
       QString Message = "Error while loading file " + mNewFile + QString("!\n\n");
       Message += FROM_UTF8(CCopasiMessage::getAllMessageText(true));
       CQMessageBox::critical(this, QString("File Error"), Message,
                              QMessageBox::Ok, QMessageBox::Ok);
       mpDataModelGUI->createModel();
     }
   CCopasiMessage msg = CCopasiMessage::getLastMessage();
   if (msg.getNumber() == 6303 &&
       (msg.getText().find("'sbml'") != std::string::npos || msg.getText().find(":sbml'") != std::string::npos))
     {
       // someone attempted to open an SBML file but failed, instead of displaying the message
       //   XML (3): Unknown element 'sbml' encountered at line '3'.
       // we just open the SBML file!
       if (CQMessageBox::question(this, QString("Import SBML?"), QString("You tried to open an SBML file. COPASI is not able to open SBML files but is able to import it. Would you like to import it?"),
                                  QMessageBox::Yes | QMessageBox::No, QMessageBox::Yes) == QMessageBox::Yes)
         {
           emit slotImportSBML(mNewFile);
           return;
         }
       newDoc();
       return;
     }
 #ifdef COPASI_SEDML
   if (msg.getNumber() == 6303 &&
       (msg.getText().find("'sedML'") != std::string::npos || msg.getText().find(":sedML'") != std::string::npos))
     {
       // someone attempted to open an SEDML file but failed, instead of displaying the message
       //   XML (3): Unknown element 'sedml' encountered at line '3'.
       // we just open the SEDML file!
       if (CQMessageBox::question(this, QString("Import SED-ML?"), QString("You tried to open an SED-ML file. COPASI is not able to open SED-ML files but is able to import it. Would you like to import it?"),
                                  QMessageBox::Yes | QMessageBox::No, QMessageBox::Yes) == QMessageBox::Yes)
         {
           emit slotImportSEDML(mNewFile);
           return;
         }
       newDoc();
       return;
     }
 #endif
   if (msg.getNumber() != MCCopasiMessage + 1)
     {
       QString Message = "Problem while loading file " + mNewFile + QString("!\n\n");
       Message += FROM_UTF8(msg.getText());
       msg = CCopasiMessage::getLastMessage();
       while (msg.getNumber() != MCCopasiMessage + 1)
         {
           Message += "\n";
           Message += FROM_UTF8(msg.getText());
           msg = CCopasiMessage::getLastMessage();
         }
       CQMessageBox::warning(this, QString("File Warning"), Message,
                             QMessageBox::Ok, QMessageBox::Ok);
     }
   if (strcasecmp(CDirEntry::suffix(TO_UTF8(mNewFile)).c_str(), ".cps") == 0 &&
       CDirEntry::isWritable(TO_UTF8(mNewFile)))
     mSaveAsRequired = false;
   else
     mSaveAsRequired = true;
   if (!(*CCopasiRootContainer::getDatamodelList())[0]->getModel())
     {
       newDoc();
       mSaveAsRequired = true;
     }
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::ADD,
                          (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
   mpaSave->setEnabled(true);
   mpaSaveAs->setEnabled(true);
   mpaExportSBML->setEnabled(true);
   mpaExportODE->setEnabled(true);
 #ifdef COPASI_SEDML
   mpaExportSEDML->setEnabled(true);
 #endif
   updateTitle();
   mpListView->switchToOtherWidget(1, "");
   CQTabWidget *widget = dynamic_cast<CQTabWidget *>(mpListView->getCurrentWidget());
   if (widget != NULL)
     widget->selectTab(0);
   refreshRecentFileMenu();
   mNewFile = "";
 }
void CopasiUI3Window::slotFilePrint () protected slot
Definition at line 1237 of file copasiui3window.cpp.
 {}
void CopasiUI3Window::slotFileSave () protected slot
Definition at line 1098 of file copasiui3window.cpp.
References DataModelGUI::commit(), FROM_UTF8, CLocaleString::fromUtf8(), CCopasiRootContainer::getDatamodelList(), mpDataModelGUI, mSaveAsRequired, DataModelGUI::saveModel(), CQMessageBox::setText(), slotFileSaveAs(), and slotFileSaveFinished().
Referenced by createActions(), importSBMLFromString(), newDoc(), slotFileOpen(), slotImportSBML(), and slotQuit().
 {
   //  mpDataModelGUI->commit(); --> remove to the line after checking the following condition (07.04.08)
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   std::string FileName = (*CCopasiRootContainer::getDatamodelList())[0]->getFileName();
   if (mSaveAsRequired || FileName == "")
     {
       return slotFileSaveAs(FROM_UTF8(FileName));
     }
   mpDataModelGUI->commit();
   std::ifstream File(CLocaleString::fromUtf8(FileName).c_str());
   std::string Line;
   File >> Line;
   File.close();
   if (!Line.compare(0, 8, "Version=") ||
       strcasecmp(FileName.c_str(), ".gps") == 0)
     {
       /* Ask for permission to overwrite write? */
       /* If no call slotFileSaveAs */
       CQMessageBox MessageBox(QMessageBox::Question,
                               "Confirm File Version Update",
                               "You are to overwrite an existing Gepasi File.\n"
                               "This will render the file unreadable for Gepasi",
                               QMessageBox::Save | QMessageBox::Ok | QMessageBox::Cancel, this);
       MessageBox.setDefaultButton(QMessageBox::Save);
       MessageBox.button(QMessageBox::Save)->setText("Save As");
       MessageBox.button(QMessageBox::Save)->setText("Overwrite");
       int choice = MessageBox.exec();
       switch (choice)
         {
           case QMessageBox::Save:
             return slotFileSaveAs(FROM_UTF8(FileName));
             break;
           case QMessageBox::Ok:
             break;
           case QMessageBox::Cancel:
             return;
             break;
         }
     }
   if (mpDataModelGUI)
     {
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotFileSaveFinished(bool)));
       mpDataModelGUI->saveModel(FileName, true);
     }
 }
void CopasiUI3Window::slotFileSaveAs (QString str = QString::null) protected slot
Definition at line 604 of file copasiui3window.cpp.
References C_INT32, checkSelection(), DataModelGUI::commit(), CopasiFileDialog::getSaveFileName(), mpDataModelGUI, DataModelGUI::saveModel(), slotFileSaveFinished(), and TO_UTF8.
Referenced by createActions(), and slotFileSave().
 {
   mpDataModelGUI->commit();
   C_INT32 Answer = QMessageBox::No;
   QString tmp;
   if (str.isEmpty()) str = "untitled.cps";
 #ifdef DEBUG_UI
   qDebug() << "Filename on slotFileSaveAs = " << str;
 #endif
   while (Answer == QMessageBox::No)
     {
       tmp =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           str, "COPASI Files (*.cps)",
                                           "Choose a filename to save under");
       if (tmp.isEmpty()) return;
 #ifdef DEBUG_UI
       qDebug() << "tmp = " << tmp;
 #endif
       // Checks whether the file exists
       Answer = checkSelection(tmp);
       if (Answer == QMessageBox::Cancel) return;
     }
   if (mpDataModelGUI && !tmp.isNull())
     {
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotFileSaveFinished(bool)));
       mpDataModelGUI->saveModel(TO_UTF8(tmp), true);
     }
 }
void CopasiUI3Window::slotFileSaveFinished (bool success) protected slot
Definition at line 645 of file copasiui3window.cpp.
References CCopasiMessage::clearDeque(), CQMessageBox::critical(), FROM_UTF8, CCopasiMessage::getAllMessageText(), CCopasiRootContainer::getDatamodelList(), CCopasiMessage::getLastMessage(), CCopasiMessage::getNumber(), CCopasiMessage::getText(), MCCopasiMessage, mNewFile, mpDataModelGUI, mpSliders, mSaveAsRequired, CCopasiMessage::peekLastMessage(), refreshRecentFileMenu(), SliderDialog::setChanged(), signalLoadFile(), updateTitle(), and CQMessageBox::warning().
Referenced by slotFileSave(), slotFileSaveAs(), and slotUpdateMIRIAMFinished().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotFileSaveFinished(bool)));
   if (success)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed(false);
       this->mpSliders->setChanged(false);
       updateTitle();
       CCopasiMessage msg = CCopasiMessage::getLastMessage();
       if (msg.getNumber() != MCCopasiMessage + 1)
         {
           QString Message("Problem while saving file!\n\n");
           Message += FROM_UTF8(msg.getText());
           msg = CCopasiMessage::getLastMessage();
           while (msg.getNumber() != MCCopasiMessage + 1)
             {
               Message += "\n";
               Message += FROM_UTF8(msg.getText());
               msg = CCopasiMessage::getLastMessage();
             }
           CQMessageBox::warning(this, QString("File Warning"), Message,
                                 QMessageBox::Ok, QMessageBox::Ok);
         }
     }
   else
     {
       if (CCopasiMessage::peekLastMessage().getNumber() != MCCopasiMessage + 1)
         {
           CQMessageBox::critical(this, "Save File Error",
                                  CCopasiMessage::getAllMessageText().c_str(),
                                  QMessageBox::Ok | QMessageBox::Default,
                                  QMessageBox::NoButton);
           CCopasiMessage::clearDeque();
         }
     }
   unsetCursor();
   refreshRecentFileMenu();
   mSaveAsRequired = false;
   if (mNewFile != "")
     {
       emit signalLoadFile(mNewFile);
       mNewFile = "";
     }
 }
void CopasiUI3Window::slotFontSelection () protected slot
Definition at line 2220 of file copasiui3window.cpp.
References TaskWidget::adjustTable(), CCopasiRootContainer::getConfiguration(), ListViews::getCurrentWidget(), getFont(), mpListView, CConfigurationFile::setApplicationFont(), and TO_UTF8.
Referenced by createActions().
 {
   bool ok;
   QFont Font = QFontDialog::getFont(&ok, qApp->font(), this);
   if (ok)
     {
       qApp->setFont(Font);
       // The stylesheet (set in CQCopasiApplication.cpp) is apparently overriding
       // in newer versions of Qt
       // This appears to reload the font from setFont into the style.
       // Two calls so that the tabwidget labels are correct
       qApp->setStyleSheet(" * {font : }");
       qApp->setStyleSheet(" * {font : }");
       CCopasiRootContainer::getConfiguration()->setApplicationFont(TO_UTF8(Font.toString()));
       TaskWidget *pTaskWidget = dynamic_cast< TaskWidget * >(mpListView->getCurrentWidget());
       if (pTaskWidget != NULL)
         {
           pTaskWidget->adjustTable();
         }
     }
   return;
 }
void CopasiUI3Window::slotFrameworkChanged (int index) protected slot
Definition at line 2189 of file copasiui3window.cpp.
References DataModelGUI::commit(), mpDataModelGUI, mpSliders, SliderDialog::setFramework(), and DataModelGUI::setFramework().
Referenced by createToolBar().
 {
   mpDataModelGUI->commit();
   mpDataModelGUI->setFramework(index);
   mpSliders->setFramework(index);
 }
void CopasiUI3Window::slotFunctionDBLoad (QString str = QString::null) protected slot
Definition at line 436 of file copasiui3window.cpp.
References DataModelGUI::commit(), CopasiFileDialog::getOpenFileName(), DataModelGUI::loadFunctionDB(), mCommitRequired, mpDataModelGUI, and TO_UTF8.
Referenced by createActions().
 {
   if (mCommitRequired)
     {
       mpDataModelGUI->commit();
     }
   if (dbFile.isEmpty())
     {
       dbFile =
         CopasiFileDialog::getOpenFileName(this, "Open File Dialog",
                                           QString::null, "COPASI Function DB (*.cpk)",
                                           "Choose a file");
     }
   if (!dbFile.isEmpty())
     {
       mpDataModelGUI->loadFunctionDB(TO_UTF8(dbFile));
     }
 }
void CopasiUI3Window::slotFunctionDBSave (QString str = QString::null) protected slot
Definition at line 406 of file copasiui3window.cpp.
References C_INT32, checkSelection(), DataModelGUI::commit(), CopasiFileDialog::getSaveFileName(), mCommitRequired, mpDataModelGUI, DataModelGUI::saveFunctionDB(), and TO_UTF8.
Referenced by createActions().
 {
   if (mCommitRequired)
     {
       mpDataModelGUI->commit();
     }
   if (dbFile.isEmpty())
     {
       C_INT32 Answer = QMessageBox::No;
       while (Answer == QMessageBox::No)
         {
           dbFile =
             CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                               "untitled.cpk", "COPASI Function DB (*.cpk)",
                                               "Choose a file");
           if (dbFile.isEmpty()) return;
           // Checks whether the file exists
           Answer = checkSelection(dbFile);
           if (Answer == QMessageBox::Cancel) return;
         }
     }
   mpDataModelGUI->saveFunctionDB(TO_UTF8(dbFile));
 }
void CopasiUI3Window::slotImportSBML (QString file = QString::null) protected slot
Definition at line 1402 of file copasiui3window.cpp.
References DataModelGUI::commit(), ListViews::DELETE, CCopasiRootContainer::getDatamodelList(), CopasiFileDialog::getOpenFileName(), DataModelGUI::importSBML(), SliderDialog::isChanged(), mCommitRequired, mNewFile, ListViews::MODEL, mpDataModelGUI, mpListView, mpSliders, DataModelGUI::notify(), CQMessageBox::question(), SliderDialog::reset(), signalLoadFile(), slotFileSave(), slotImportSBMLFinished(), ListViews::switchToOtherWidget(), and TO_UTF8.
Referenced by createActions(), dropEvent(), openInitialDocument(), slotFileExamplesSBMLFiles(), slotFileOpenFinished(), and slotOpenRecentSBMLFile().
 {
   disconnect(this, SIGNAL(signalLoadFile(QString)), this, SLOT(slotImportSBML(QString)));
   if (mCommitRequired)
     {
       mpDataModelGUI->commit();
     }
   QString SBMLFile;
   if (file == "")
     SBMLFile =
       CopasiFileDialog::getOpenFileName(this, "Open File Dialog",
                                         QString::null, "XML Files (*.xml);;All Files (*)",
                                         "Choose a file");
   else
     SBMLFile = file;
   if (!SBMLFile.isNull())
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       if (mpDataModelGUI && ((*CCopasiRootContainer::getDatamodelList())[0]->isChanged() || this->mpSliders->isChanged()))
         {
           switch (CQMessageBox::question(this, "COPASI",
                                          "The document contains unsaved changes\n"
                                          "Do you want to save the changes before exiting?",
                                          QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel,
                                          QMessageBox::Save))
             {
               case QMessageBox::Save:
                 connect(this, SIGNAL(signalLoadFile(QString)), this, SLOT(slotImportSBML(QString)));
                 mNewFile = SBMLFile;
                 mCommitRequired = false;
                 slotFileSave();
                 return;
                 break;
               case QMessageBox::Discard:
                 break;
               case QMessageBox::Cancel:
               default:
                 return;
                 break;
             }
         }
       mpDataModelGUI->notify(ListViews::MODEL, ListViews::DELETE,
                              (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
       mpListView->switchToOtherWidget(0, "");
       if (this->mpSliders) this->mpSliders->reset();
       if (!mpDataModelGUI)
         {
           mpDataModelGUI = new DataModelGUI(this); // create a new data model
         }
       setCursor(Qt::WaitCursor);
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotImportSBMLFinished(bool)));
       mNewFile = SBMLFile;
       mpDataModelGUI->importSBML(TO_UTF8(SBMLFile));
     }
 }
void CopasiUI3Window::slotImportSBMLFinished (bool success) protected slot
Definition at line 1473 of file copasiui3window.cpp.
References ListViews::ADD, checkPendingMessages(), DataModelGUI::createModel(), CQMessageBox::critical(), FROM_UTF8, ListViews::getCurrentWidget(), CCopasiRootContainer::getDatamodelList(), CCopasiMessage::getLastMessage(), mCommitRequired, mNewFile, ListViews::MODEL, mpaExportODE, mpaExportSBML, mpaSave, mpaSaveAs, mpDataModelGUI, mpListView, mSaveAsRequired, DataModelGUI::notify(), refreshRecentSBMLFileMenu(), CQTabWidget::selectTab(), ListViews::switchToOtherWidget(), and updateTitle().
Referenced by slotImportSBML().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotImportSBMLFinished(bool)));
   unsetCursor();
   mCommitRequired = true;
   if (!success)
     {
       QString Message = "Error while loading file " + mNewFile + QString("!\n\n");
       Message += FROM_UTF8(CCopasiMessage::getLastMessage().getText());
       CQMessageBox::critical(this, QString("File Error"), Message,
                              QMessageBox::Ok, QMessageBox::Ok);
       mpDataModelGUI->createModel();
     }
   else
     // We check in all case for warnings. This will help also for unsuccessful imports
     this->checkPendingMessages();
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::ADD,
                          (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
   mpaSave->setEnabled(true);
   mpaSaveAs->setEnabled(true);
   mpaExportSBML->setEnabled(true);
   mpaExportODE->setEnabled(true);
   mpListView->switchToOtherWidget(1, "");
   CQTabWidget *widget = dynamic_cast<CQTabWidget *>(mpListView->getCurrentWidget());
   if (widget != NULL)
     widget->selectTab(0);
   refreshRecentSBMLFileMenu();
   updateTitle();
   mSaveAsRequired = true;
   mNewFile = "";
 }
void CopasiUI3Window::slotImportSBMLFromStringFinished (bool success) protected slot
Definition at line 1356 of file copasiui3window.cpp.
References ListViews::ADD, checkPendingMessages(), CCopasiMessage::clearDeque(), DataModelGUI::createModel(), CQMessageBox::critical(), FROM_UTF8, ListViews::getCurrentWidget(), CCopasiRootContainer::getDatamodelList(), CCopasiMessage::getLastMessage(), mCommitRequired, ListViews::MODEL, mpDataModelGUI, mpListView, mSaveAsRequired, DataModelGUI::notify(), CQTabWidget::selectTab(), ListViews::switchToOtherWidget(), and updateTitle().
Referenced by importSBMLFromString().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotImportSBMLFromStringFinished(bool)));
   unsetCursor();
   mCommitRequired = true;
   if (!success)
     {
       QString Message = "Error while importing SBML model!\n\n";
       Message += FROM_UTF8(CCopasiMessage::getLastMessage().getText());
       CQMessageBox::critical(this, QString("Import Error"), Message,
                              QMessageBox::Ok, QMessageBox::Ok);
       CCopasiMessage::clearDeque();
       mpDataModelGUI->createModel();
     }
   /* still check for warnings.
    * Maybe events or rules were ignored while reading
    * the file.
    */
   if (success)
     {
       this->checkPendingMessages();
     }
   mpDataModelGUI->notify(ListViews::MODEL, ListViews::ADD,
                          (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
   //if (!bobject_browser_open)
   //       mpFileMenu->setItemEnabled(nsaveas_menu_id, true);
   //       msave_button->setEnabled(true);
   //       mpFileMenu->setItemEnabled(nsave_menu_id, true);
   mpListView->switchToOtherWidget(1, "");
   CQTabWidget *widget = dynamic_cast<CQTabWidget *>(mpListView->getCurrentWidget());
   if (widget != NULL)
     widget->selectTab(0);
   updateTitle();
   mSaveAsRequired = true;
 }
void CopasiUI3Window::slotObjectBrowserDialogWasClosed () slot
This should only be called by the destructor of the object browser dialog otherwise a memory leak occurs
Definition at line 1284 of file copasiui3window.cpp.
References mpaObjectBrowser, and mpObjectBrowser.
Referenced by slotShowObjectBrowserDialog().
 {
   mpObjectBrowser = NULL;
   mpaObjectBrowser->setChecked(false);
 }
void CopasiUI3Window::slotOpenRecentFile (QAction * pAction) protected slot
Definition at line 1846 of file copasiui3window.cpp.
References FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiParameterGroup::getGroup(), CConfigurationFile::getRecentFiles(), CCopasiParameterGroup::getValue(), mRecentFilesActionMap, CCopasiParameter::Value::pSTRING, and slotFileOpen().
Referenced by refreshRecentFileMenu().
 {
   int index = mRecentFilesActionMap[pAction];
   std::string FileName =
     *CCopasiRootContainer::getConfiguration()->getRecentFiles().getGroup("Recent Files")->getValue(index).pSTRING;
   slotFileOpen(FROM_UTF8(FileName));
 }
void CopasiUI3Window::slotOpenRecentSBMLFile (QAction * pAction) protected slot
Definition at line 1856 of file copasiui3window.cpp.
References FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiParameterGroup::getGroup(), CConfigurationFile::getRecentSBMLFiles(), CCopasiParameterGroup::getValue(), mRecentSBMLFilesActionMap, CCopasiParameter::Value::pSTRING, and slotImportSBML().
Referenced by refreshRecentSBMLFileMenu().
 {
   int index = mRecentSBMLFilesActionMap[pAction];
   std::string FileName =
     *CCopasiRootContainer::getConfiguration()->getRecentSBMLFiles().getGroup("Recent Files")->getValue(index).pSTRING;
   slotImportSBML(FROM_UTF8(FileName));
 }
void CopasiUI3Window::slotPreferences () protected slot
Definition at line 1290 of file copasiui3window.cpp.
Referenced by createMenuBar().
 {
   CQPreferenceDialog * preferenceDialog = new CQPreferenceDialog(this, 0, false);
   preferenceDialog->setAttribute(Qt::WA_DeleteOnClose);
   preferenceDialog->setModal(true);
   preferenceDialog->show();
 }
void CopasiUI3Window::slotQuit () protected slot
Definition at line 1158 of file copasiui3window.cpp.
References DataModelGUI::commit(), CCopasiRootContainer::getDatamodelList(), getMainWindow(), CQMessageBox::information(), SliderDialog::isChanged(), mpDataModelGUI, mpSliders, mQuitApplication, CQMessageBox::question(), slotFileSave(), and slotQuitFinished().
Referenced by closeEvent(), and createActions().
 {
   if (!CopasiUI3Window::getMainWindow()->isEnabled())
     {
       CQMessageBox::information(this, "COPASI", "COPASI is currently executing tasks.\n"
                                 "Please stop them first before closing COPASI.");
       return;
     }
   mQuitApplication = true;
   mpDataModelGUI->commit();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (mpDataModelGUI && ((*CCopasiRootContainer::getDatamodelList())[0]->isChanged() || this->mpSliders->isChanged()))
     {
       connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotQuitFinished(bool)));
       switch (CQMessageBox::question(this, "COPASI",
                                      "The document contains unsaved changes\n"
                                      "Do you want to save the changes before exiting?",
                                      QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel,
                                      QMessageBox::Save))
         {
           case QMessageBox::Save:
             slotFileSave();
             break;
           case QMessageBox::Discard:
             slotQuitFinished(true);
             break;
           case QMessageBox::Cancel:
           default:
             slotQuitFinished(false);
             break;
         }
     }
   else
     {
       slotQuitFinished(true);
     }
 }
void CopasiUI3Window::slotQuitFinished (bool success) protected slot
Definition at line 1203 of file copasiui3window.cpp.
References CleanUp(), mpDataModelGUI, and mQuitApplication.
Referenced by slotQuit().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotQuitFinished(bool)));
   mQuitApplication &= success;
   if (mQuitApplication)
     {
       CleanUp();
       qApp->quit();
     }
 }
void CopasiUI3Window::slotShowObjectBrowserDialog (bool flag) protected slot
This should only be called via signal by the corresponding QAction mpaObjectBrowser. Otherwise the QAction will not be up to date.
Definition at line 1264 of file copasiui3window.cpp.
References mpObjectBrowser, and slotObjectBrowserDialogWasClosed().
Referenced by createActions().
 {
   if (flag /*tools->isItemEnabled(2)*/)
     {
       if (mpObjectBrowser)
         delete mpObjectBrowser;
       mpObjectBrowser = new ObjectBrowserDialog(this, 0, false, 1);
       connect(mpObjectBrowser, SIGNAL(destroyed(QObject *)), this, SLOT(slotObjectBrowserDialogWasClosed()));
       mpObjectBrowser->show();
     }
   else
     {
       if (mpObjectBrowser)
         mpObjectBrowser->hide();
     }
 }
void CopasiUI3Window::slotShowSliders (bool flag) slot
Definition at line 1718 of file copasiui3window.cpp.
References addWindow(), mpaSliders, mpSliders, and removeWindow().
Referenced by SliderDialog::closeEvent(), and createActions().
 {
   mpaSliders->setChecked(flag);
   this->mpSliders->setHidden(!flag);
   if (flag)
     addWindow(this->mpSliders);
   else
     removeWindow(this->mpSliders);
 }
void CopasiUI3Window::slotTutorialWizard () protected slot
Definition at line 1298 of file copasiui3window.cpp.
References WizardDialog::setCopasiMainWindow().
Referenced by createMenuBar().
 {
   WizardDialog* tutorialWizard = new WizardDialog();
   tutorialWizard->setCopasiMainWindow(this);
   tutorialWizard->show();
 }
void CopasiUI3Window::slotUpdateInitialState () protected slot
Definition at line 2172 of file copasiui3window.cpp.
References ListViews::CHANGE, DataModelGUI::commit(), CModel::compileIfNecessary(), CCopasiRootContainer::getDatamodelList(), CModel::getState(), mpDataModelGUI, DataModelGUI::notify(), CModel::setInitialState(), ListViews::STATE, and CModel::updateInitialValues().
Referenced by createActions().
 {
   mpDataModelGUI->commit();
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel *pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   if (pModel != NULL)
     {
       pModel->compileIfNecessary(NULL);
       pModel->setInitialState(pModel->getState());
       pModel->updateInitialValues();
       mpDataModelGUI->notify(ListViews::STATE, ListViews::CHANGE, (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getKey());
     }
 }
void CopasiUI3Window::slotUpdateMIRIAM () protected slot
Definition at line 2133 of file copasiui3window.cpp.
References CCopasiMessage::clearDeque(), CCopasiRootContainer::getConfiguration(), mpDataModelGUI, slotUpdateMIRIAMFinished(), and DataModelGUI::updateMIRIAM().
Referenced by createActions().
 {
   bool success = true;
   CCopasiMessage::clearDeque();
   if (!mpDataModelGUI)
     mpDataModelGUI = new DataModelGUI(this); // create a new data model
   connect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotUpdateMIRIAMFinished(bool)));
   try
     {
       success = mpDataModelGUI->updateMIRIAM(
                   CCopasiRootContainer::getConfiguration()->getRecentMIRIAMResources());
     }
   catch (...)
     {
       success = false;
     }
 }
void CopasiUI3Window::slotUpdateMIRIAMFinished (bool success) protected slot
Definition at line 2099 of file copasiui3window.cpp.
References checkPendingMessages(), CCopasiMessage::clearDeque(), CQMessageBox::critical(), FROM_UTF8, CCopasiRootContainer::getConfiguration(), CCopasiMessage::getLastMessage(), mpDataModelGUI, mpListView, CConfigurationFile::save(), CMIRIAMResourceObject::setMIRIAMResources(), slotFileSaveFinished(), ListViews::switchToOtherWidget(), and DataModelGUI::updateMIRIAMResourceContents().
Referenced by slotUpdateMIRIAM().
 {
   disconnect(mpDataModelGUI, SIGNAL(finished(bool)), this, SLOT(slotFileSaveFinished(bool)));
   QCursor oldCursor = cursor();
   setCursor(Qt::WaitCursor);
   if (!success)
     {
       setCursor(oldCursor);
       QString Message = "Error while updating MIRIAM" + QString("!\n\n");
       Message += FROM_UTF8(CCopasiMessage::getLastMessage().getText());
       CQMessageBox::critical(this, QString("MIRIAM Error"), Message,
                              QMessageBox::Ok, QMessageBox::Ok);
       CCopasiMessage::clearDeque();
     }
   /* still check for warnings.
   * Maybe events or rules were ignored while reading
   * the file.
   */
   if (success)
     {
       CCopasiRootContainer::getConfiguration()->save();
       CMIRIAMResourceObject::setMIRIAMResources(
         &CCopasiRootContainer::getConfiguration()->getRecentMIRIAMResources());
       mpDataModelGUI->updateMIRIAMResourceContents();
       this->checkPendingMessages();
     }
   CCopasiMessage::clearDeque();
   mpListView->switchToOtherWidget(0, "");
   setCursor(oldCursor);
 }
void CopasiUI3Window::suspendAutoSave (const bool & suspend)
Definition at line 1838 of file copasiui3window.cpp.
References AutoSaveInterval, mpAutoSaveTimer, and mSuspendAutoSave.
Referenced by TaskWidget::commonAfterRunTask(), and TaskWidget::commonBeforeRunTask().
 {
   mSuspendAutoSave = suspend;
   if (!mSuspendAutoSave)
     mpAutoSaveTimer->setInterval(AutoSaveInterval); // restart the timer
 }
void CopasiUI3Window::updateTitle () private
Definition at line 1794 of file copasiui3window.cpp.
References CDirEntry::baseName(), FixedTitle, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), and TO_UTF8.
Referenced by CopasiUI3Window(), newDoc(), slotFileOpenFinished(), slotFileSaveFinished(), slotImportSBMLFinished(), and slotImportSBMLFromStringFinished().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   QString FileName = FROM_UTF8((*CCopasiRootContainer::getDatamodelList())[0]->getFileName());
 #ifdef WIN32 // Windows allows mixing of '/' and '\' as separator.
   FileName.replace("\\", "/");
 #endif
   if (FileName.length() > 40)
     {
 #ifdef WIN32
       QRegExp mask("^(([A-Z]:/)?[^/]+/).*(/[^/]+/[^/]+$)");
 #else
       QRegExp mask("^((/*)[^/]+/).*(/[^/]+/[^/]+$)");
 #endif
       mask.indexIn(FileName);
       FileName = mask.cap(1) + "..." + mask.cap(3);
     }
   std::string BaseName;
   if (!FileName.isEmpty())
     BaseName = CDirEntry::baseName(TO_UTF8(FileName)) + " - ";
   setWindowTitle(FROM_UTF8(BaseName) + FixedTitle + " " + FileName);
 }
Member Data Documentation
QString CopasiUI3Window::FixedTitle private
Definition at line 239 of file copasiui3window.h.
Referenced by about(), CopasiUI3Window(), license(), and updateTitle().
bool CopasiUI3Window::mCommitRequired private
Definition at line 297 of file copasiui3window.h.
Referenced by importSBMLFromString(), newDoc(), slotFileOpen(), slotFileOpenFinished(), slotFunctionDBLoad(), slotFunctionDBSave(), slotImportSBML(), slotImportSBMLFinished(), and slotImportSBMLFromStringFinished().
bool CopasiUI3Window::mMessageShown private
Definition at line 300 of file copasiui3window.h.
Referenced by messageShown(), and setMessageShown().
QString CopasiUI3Window::mNewFile private
Definition at line 296 of file copasiui3window.h.
Referenced by newDoc(), slotFileOpen(), slotFileOpenFinished(), slotFileSaveFinished(), slotImportSBML(), and slotImportSBMLFinished().
QAction* CopasiUI3Window::mpaApplyInitialState private
Definition at line 256 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QAction* CopasiUI3Window::mpaCapture private
Definition at line 258 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QAction* CopasiUI3Window::mpaCheckModel private
Definition at line 255 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QAction* CopasiUI3Window::mpaCloseAllWindows private
Definition at line 263 of file copasiui3window.h.
Referenced by createActions(), and refreshWindowsMenu().
QAction* CopasiUI3Window::mpaExpandModel private
Definition at line 260 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaExportODE private
Definition at line 251 of file copasiui3window.h.
Referenced by CopasiUI3Window(), createActions(), createMenuBar(), newDoc(), slotFileOpenFinished(), and slotImportSBMLFinished().
QAction* CopasiUI3Window::mpaExportSBML private
Definition at line 250 of file copasiui3window.h.
Referenced by CopasiUI3Window(), createActions(), createMenuBar(), newDoc(), slotFileOpenFinished(), and slotImportSBMLFinished().
QAction* CopasiUI3Window::mpaFontSelectionDialog private
Definition at line 261 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaFunctionDBLoad private
Definition at line 248 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaFunctionDBSave private
Definition at line 247 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaImportSBML private
Definition at line 249 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaNew private
Definition at line 241 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QAction* CopasiUI3Window::mpaObjectBrowser private
Definition at line 253 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and slotObjectBrowserDialogWasClosed().
QAction* CopasiUI3Window::mpaOpen private
Definition at line 242 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QAction* CopasiUI3Window::mpaOpenCopasiFiles private
Definition at line 243 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaOpenSBMLFiles private
Definition at line 244 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaQuit private
Definition at line 252 of file copasiui3window.h.
Referenced by createActions(), and createMenuBar().
QAction* CopasiUI3Window::mpaSave private
Definition at line 245 of file copasiui3window.h.
Referenced by CopasiUI3Window(), createActions(), createMenuBar(), createToolBar(), newDoc(), slotFileOpenFinished(), and slotImportSBMLFinished().
QAction* CopasiUI3Window::mpaSaveAs private
Definition at line 246 of file copasiui3window.h.
Referenced by CopasiUI3Window(), createActions(), createMenuBar(), newDoc(), slotFileOpenFinished(), and slotImportSBMLFinished().
QAction* CopasiUI3Window::mpaSliders private
Definition at line 254 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), createToolBar(), and slotShowSliders().
QAction* CopasiUI3Window::mpaUpdateInitialState private
Definition at line 257 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QAction* CopasiUI3Window::mpaUpdateMIRIAM private
Definition at line 259 of file copasiui3window.h.
Referenced by createActions(), createMenuBar(), and createToolBar().
QTimer* CopasiUI3Window::mpAutoSaveTimer private
Definition at line 273 of file copasiui3window.h.
Referenced by autoSave(), CopasiUI3Window(), and suspendAutoSave().
QComboBox* CopasiUI3Window::mpBoxSelectFramework private
Definition at line 237 of file copasiui3window.h.
Referenced by createToolBar().
DataModelGUI* CopasiUI3Window::mpDataModelGUI private
Definition at line 235 of file copasiui3window.h.
Referenced by CopasiUI3Window(), exportSBMLToString(), getDataModel(), importSBMLFromString(), newDoc(), slotApplyInitialState(), slotConvertToIrreversible(), slotExpandModel(), slotExportMathModel(), slotExportMathModelFinished(), slotExportSBML(), slotExportSBMLFinished(), slotExportSBMLToStringFinished(), slotFileOpen(), slotFileOpenFinished(), slotFileSave(), slotFileSaveAs(), slotFileSaveFinished(), slotFrameworkChanged(), slotFunctionDBLoad(), slotFunctionDBSave(), slotImportSBML(), slotImportSBMLFinished(), slotImportSBMLFromStringFinished(), slotQuit(), slotQuitFinished(), slotUpdateInitialState(), slotUpdateMIRIAM(), slotUpdateMIRIAMFinished(), and ~CopasiUI3Window().
ListViews* CopasiUI3Window::mpListView private
Definition at line 236 of file copasiui3window.h.
Referenced by CopasiUI3Window(), getMainWidget(), importSBMLFromString(), listViewsFolderChanged(), newDoc(), slotCapture(), slotConvertToIrreversible(), slotFileOpen(), slotFileOpenFinished(), slotFontSelection(), slotImportSBML(), slotImportSBMLFinished(), slotImportSBMLFromStringFinished(), slotUpdateMIRIAMFinished(), and ~CopasiUI3Window().
QThread* CopasiUI3Window::mpMainThread private
Definition at line 295 of file copasiui3window.h.
Referenced by isMainThread().
QMenu* CopasiUI3Window::mpMenuExamples private
Definition at line 277 of file copasiui3window.h.
Referenced by createMenuBar().
QMenu* CopasiUI3Window::mpMenuRecentFiles private
Definition at line 278 of file copasiui3window.h.
Referenced by createMenuBar(), and refreshRecentFileMenu().
QMenu* CopasiUI3Window::mpMenuRecentSBMLFiles private
Definition at line 285 of file copasiui3window.h.
Referenced by createMenuBar(), and refreshRecentSBMLFileMenu().
CMIRIAMResources* CopasiUI3Window::mpMIRIAMResources private
Definition at line 293 of file copasiui3window.h.
ObjectBrowserDialog* CopasiUI3Window::mpObjectBrowser private
Definition at line 270 of file copasiui3window.h.
Referenced by slotObjectBrowserDialogWasClosed(), and slotShowObjectBrowserDialog().
QActionGroup* CopasiUI3Window::mpRecentFilesActionGroup private
Definition at line 281 of file copasiui3window.h.
Referenced by refreshRecentFileMenu().
QActionGroup* CopasiUI3Window::mpRecentSBMLFilesActionGroup private
Definition at line 287 of file copasiui3window.h.
Referenced by refreshRecentSBMLFileMenu().
SliderDialog* CopasiUI3Window::mpSliders private
Definition at line 269 of file copasiui3window.h.
Referenced by CopasiUI3Window(), disableSliders(), importSBMLFromString(), listViewsFolderChanged(), newDoc(), slotFileOpen(), slotFileSaveFinished(), slotFrameworkChanged(), slotImportSBML(), slotQuit(), slotShowSliders(), and ~CopasiUI3Window().
QMenu* CopasiUI3Window::mpTools private
Definition at line 291 of file copasiui3window.h.
Referenced by createMenuBar().
QActionGroup* CopasiUI3Window::mpWindowsActionGroup private
Definition at line 288 of file copasiui3window.h.
Referenced by refreshWindowsMenu().
QMenu* CopasiUI3Window::mpWindowsMenu private
Definition at line 279 of file copasiui3window.h.
Referenced by createMenuBar(), and refreshWindowsMenu().
bool CopasiUI3Window::mQuitApplication private
Definition at line 298 of file copasiui3window.h.
Referenced by slotQuit(), and slotQuitFinished().
QMap< QAction *, int > CopasiUI3Window::mRecentFilesActionMap private
Definition at line 280 of file copasiui3window.h.
Referenced by refreshRecentFileMenu(), and slotOpenRecentFile().
QMap< QAction *, int > CopasiUI3Window::mRecentSBMLFilesActionMap private
Definition at line 286 of file copasiui3window.h.
Referenced by refreshRecentSBMLFileMenu(), and slotOpenRecentSBMLFile().
bool CopasiUI3Window::mSaveAsRequired private
Definition at line 272 of file copasiui3window.h.
Referenced by newDoc(), slotFileOpenFinished(), slotFileSave(), slotFileSaveFinished(), slotImportSBMLFinished(), and slotImportSBMLFromStringFinished().
bool CopasiUI3Window::mSliderDialogEnabled private
Definition at line 299 of file copasiui3window.h.
Referenced by CopasiUI3Window(), and disableSliders().
bool CopasiUI3Window::mSuspendAutoSave private
Definition at line 274 of file copasiui3window.h.
Referenced by autoSave(), and suspendAutoSave().
QList< QPointer<QMainWindow> > CopasiUI3Window::mWindows private
Definition at line 302 of file copasiui3window.h.
Referenced by addWindow(), CopasiUI3Window(), getWindows(), refreshWindowsMenu(), removeWindow(), slotActivateWindowTriggered(), slotCloseAllWindows(), and ~CopasiUI3Window().
CopasiUI3Window * CopasiUI3Window::pMainWindow = NULL static private
Definition at line 304 of file copasiui3window.h.
Referenced by create(), getMainWindow(), and isMainThread().
The documentation for this class was generated from the following files:
copasiui3window.h
copasiui3window.cpp