COPASI API: CMetabNameInterface Class Reference
CMetabNameInterface Class Reference
#include <CMetabNameInterface.h>
Public Member Functions
CMetabNameInterface ()
~CMetabNameInterface ()
Static Public Member Functions
static bool doesExist (const CModel *model, const std::string &metabolite, const std::string &compartment)
static std::string getDisplayName (const CModel *model, const std::string &key, const bool &quoted)
static std::string getDisplayName (const CModel *model, const CMetab &metab, const bool &quoted)
static std::string getDisplayName (const CModel *model, const std::string &metabolite, const std::string &compartment, const bool &quoted)
static CMetab * getMetabolite (const CModel *model, const std::string &metabolite, const std::string &compartment)
static std::string getMetaboliteKey (const CModel *model, const std::string &metabolite, const std::string &compartment)
static bool isUnique (const CModel *model, const std::string &name)
static std::pair< std::string,
std::string > splitDisplayName (const std::string &name)
static std::string unQuote (const std::string &displayName)
Detailed Description
This class handles the display names of metabolites. It converts "Species" to "Species {Compartment}" if the metabolite name is not unique. If it is unique (that means it occurs in only one compartment) then the "{Compartment}" is not added.
Definition at line 40 of file CMetabNameInterface.h.
Constructor & Destructor Documentation
CMetabNameInterface::CMetabNameInterface ()
CMetabNameInterface::~CMetabNameInterface ()
Definition at line 38 of file CMetabNameInterface.cpp.
 {}
Member Function Documentation
bool CMetabNameInterface::doesExist (const CModel * model, const std::string & metabolite, const std::string & compartment) static
This returns whether a metabolite with the given name does exist. If a compartment is also given (as an appendix to the name) then it only returns true if the metabolite exists in the specified compartment.
Definition at line 154 of file CMetabNameInterface.cpp.
References C_INVALID_INDEX, CModel::findMetabByName(), CModel::getCompartments(), and CCopasiVectorN< CType >::getIndex().
Referenced by getDisplayName(), and CChemEqInterface::listOfNonExistingMetabNames().
 {
   if (compartment != "")
     {
       size_t Index = model->getCompartments().getIndex(compartment);
       if (Index == C_INVALID_INDEX) return false;
       Index = model->getCompartments()[Index]->getMetabolites().getIndex(metabolite);
       return (Index != C_INVALID_INDEX);
     }
   else
     return (model->findMetabByName(metabolite) != C_INVALID_INDEX);
 }
std::string CMetabNameInterface::getDisplayName (const CModel * model, const std::string & key, const bool & quoted) static
This returns a name to use for display in the GUI. If the name of the metabolite is unique it is used unaltered. If it is not then the compartment is added to the name to make it unique.
Definition at line 41 of file CMetabNameInterface.cpp.
References CKeyFactory::get(), and CCopasiRootContainer::getKeyFactory().
Referenced by CChemEqInterface::buildDisplayNames(), CTimeSeries::compile(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CMoiety::getDescription(), getDisplayName(), CEFMTask::getInternalSpecies(), ParameterTable::getListOfAllMetabNames(), CModelParameterSpecies::getName(), CEFMTask::getNetReaction(), CMetab::getObjectDisplayName(), CQEFMSpeciesDM::headerData(), CQBrowserPaneDM::load(), CReactionInterface::loadMappingAndValues(), StateSubwidget::loadMetabolites(), operator<<(), CModel::printParameterOverview(), CEFMProblem::printResult(), and CQBrowserPaneDM::slotNotify().
 {
   CMetab * metab = dynamic_cast< CMetab * >(CCopasiRootContainer::getKeyFactory()->get(key));
   if (metab)
     return getDisplayName(model, *metab, quoted);
   else
     return "";
 }
std::string CMetabNameInterface::getDisplayName (const CModel * model, const CMetab & metab, const bool & quoted) static
This returns a name to use for display in the GUI. If the name of the metabolite is unique it is used unaltered. If it is not then the compartment is added to the name to make it unique.
Definition at line 51 of file CMetabNameInterface.cpp.
References CMetab::getCompartment(), getDisplayName(), and CCopasiObject::getObjectName().
 {
   return getDisplayName(model, metab.getObjectName(), metab.getCompartment()->getObjectName(), quoted);
 }
std::string CMetabNameInterface::getDisplayName (const CModel * model, const std::string & metabolite, const std::string & compartment, const bool & quoted) static
This returns a name to use for display in the GUI. If the name of the metabolite is unique it is used unaltered. If it is not then the compartment is added to the name to make it unique.
Definition at line 56 of file CMetabNameInterface.cpp.
References doesExist(), CModel::getCompartments(), CCopasiObject::getObjectName(), isNumber(), isUnique(), quote(), and CCopasiVector< T >::size().
 {
   std::string DefaultCompartment;
   if (model->getCompartments().size() == 0)
     DefaultCompartment = "compartment";
   else
     DefaultCompartment = model->getCompartments()[0]->getObjectName();
   std::string Metabolite = quoted ? quote(metabolite, "{}") : metabolite;
   if (quoted && isNumber(Metabolite))
     Metabolite = "\"" + Metabolite + "\"";
   if ((CMetabNameInterface::doesExist(model, metabolite, compartment) &&
        CMetabNameInterface::isUnique(model, metabolite)) ||
       (!CMetabNameInterface::doesExist(model, metabolite, "") &&
        compartment == DefaultCompartment))
     return Metabolite;
   std::string Compartment = quoted ? quote(compartment, "{}") : compartment;
   if ((quoted && isNumber(Compartment)) ||
       (Compartment.find(' ') != std::string::npos && Compartment.find('"') == std::string::npos))
     Compartment = "\"" + Compartment + "\"";
   return Metabolite + '{' + Compartment + '}';
 }
CMetab * CMetabNameInterface::getMetabolite (const CModel * model, const std::string & metabolite, const std::string & compartment) static
Definition at line 100 of file CMetabNameInterface.cpp.
References C_INVALID_INDEX, CModel::findMetabByName(), CModel::getCompartments(), CCopasiVectorN< CType >::getIndex(), CCompartment::getMetabolites(), and CModel::getMetabolites().
Referenced by CChemEqInterface::completeCompartments(), and getMetaboliteKey().
 {
   size_t Index;
   if (compartment != "")
     {
       Index = model->getCompartments().getIndex(compartment);
       if (Index != C_INVALID_INDEX)
         {
           CCompartment *pCompartment = model->getCompartments()[Index];
           Index = pCompartment->getMetabolites().getIndex(metabolite);
           if (Index != C_INVALID_INDEX)
             return pCompartment->getMetabolites()[Index];
         }
       return NULL;
     }
   Index = model->findMetabByName(metabolite);
   if (Index != C_INVALID_INDEX)
     return model->getMetabolites()[Index];
   return NULL;
 }
std::string CMetabNameInterface::getMetaboliteKey (const CModel * model, const std::string & metabolite, const std::string & compartment) static
This tries to find the metabolite with the given name. If the name is not unique and is given without a compartment then the first occurrence of a metabolite with this name is returned.
Definition at line 88 of file CMetabNameInterface.cpp.
References CModelEntity::getKey(), and getMetabolite().
Referenced by CReactionInterface::writeBackToReaction(), and CChemEqInterface::writeToChemEq().
 {
   CMetab * metab = getMetabolite(model, metabolite, compartment);
   if (metab)
     return metab->getKey();
   else
     return "";
 }
bool CMetabNameInterface::isUnique (const CModel * model, const std::string & name) static
This returns whether the metabolite name is unique.
Definition at line 131 of file CMetabNameInterface.cpp.
References CModel::getMetabolites(), CCopasiObject::getObjectName(), and CCopasiVector< T >::size().
Referenced by CChemEqInterface::completeCompartments(), getDisplayName(), and CChemEqInterface::listOfNonUniqueMetabNames().
 {
   bool unique = true;
   size_t i;
   const CCopasiVector< CMetab > & metabs = model->getMetabolites();
   std::string metabName;
   for (i = 0; i < metabs.size(); i++)
     {
       metabName = metabs[i]->getObjectName();
       if (metabName == name)
         {
           if (unique)
             unique = false;
           else
             return false; //return true
         }
     }
   return true; //return unique;
 }
std::pair< std::string, std::string > CMetabNameInterface::splitDisplayName (const std::string & name) static
Definition at line 173 of file CMetabNameInterface.cpp.
References CChemEqParserBase::getSubstrateCompartments(), CChemEqParserBase::getSubstrateNames(), quote(), and CChemEqParserBase::yyparse().
Referenced by CChemEqInterface::addModifier(), and CReactionInterface::writeBackToReaction().
 {
   // parse the description into a linked node tree
   std::stringstream buffer((name.find('"') != std::string::npos ? name :  quote(name)) + " ->");
   CChemEqParser Parser(&buffer);
   std::pair< std::string, std::string > Result;
   if (Parser.yyparse() != 0)
     {
       Result.first = "";
       Result.second = "";
     }
   else
     {
       Result.first = Parser.getSubstrateNames()[0];
       Result.second = Parser.getSubstrateCompartments()[0];
     }
   return Result;
 }
std::string CMetabNameInterface::unQuote (const std::string & displayName) static
Definition at line 197 of file CMetabNameInterface.cpp.
References CChemEqParserBase::getSubstrateCompartments(), CChemEqParserBase::getSubstrateNames(), and CChemEqParserBase::yyparse().
Referenced by ParameterTable::getListOfAllMetabNames(), and ParameterTable::updateTable().
 {
   // parse the description into a linked node tree
   std::stringstream buffer(displayName + " ->");
   CChemEqParser Parser(&buffer);
   std::pair< std::string, std::string > Names;
   if (Parser.yyparse() != 0)
     {
       Names.first = displayName;
       Names.second = "";
     }
   else
     {
       Names.first = Parser.getSubstrateNames()[0];
       Names.second = Parser.getSubstrateCompartments()[0];
     }
   std::string Name = Names.first;
   if (Names.second != "")
     {
       std::string compartment = Names.second;
       if (compartment.find(' '))
         compartment = "\"" + compartment + "\"";
       Name += "{" + compartment + "}";
     }
   return Name;
 }
The documentation for this class was generated from the following files:
CMetabNameInterface.h
CMetabNameInterface.cpp