COPASI API: CCompressedColumnFormat Class Reference
CCompressedColumnFormat Class Reference
#include <CSparseMatrix.h>
Classes
class const_row_iterator
Public Member Functions
const_row_iterator beginRow (const size_t &row) const
CCompressedColumnFormat (const size_t &rows, const size_t &columns, const size_t &nonZeros)
CCompressedColumnFormat (const CSparseMatrix &matrix)
const_row_iterator endRow (const size_t &row) const
const size_t * getColumnStart () const
size_t * getColumnStart ()
const size_t * getRowIndex () const
size_t * getRowIndex ()
const C_FLOAT64 * getValues () const
C_FLOAT64 * getValues ()
size_t numCols () const
size_t numNonZeros () const
size_t numRows () const
CCompressedColumnFormat & operator= (const CSparseMatrix &ccf)
~CCompressedColumnFormat ()
Private Member Functions
CCompressedColumnFormat ()
Private Attributes
size_t mNumCols
size_t mNumRows
size_t * mpColumnStart
size_t * mpRowIndex
C_FLOAT64 * mpValue
Detailed Description
Definition at line 128 of file CSparseMatrix.h.
Constructor & Destructor Documentation
CCompressedColumnFormat::CCompressedColumnFormat () private
Definition at line 468 of file CSparseMatrix.cpp.
References mNumCols, and mpColumnStart.
                                                 :
   mNumRows(0),
   mNumCols(0),
   mpColumnStart(new size_t[1]),
   mpRowIndex(NULL),
   mpValue(NULL)
 {mpColumnStart[mNumCols] = 0;}
CCompressedColumnFormat::CCompressedColumnFormat (const size_t & rows, const size_t & columns, const size_t & nonZeros)
Definition at line 476 of file CSparseMatrix.cpp.
References mNumCols, and mpColumnStart.
                             :
   mNumRows(rows),
   mNumCols(columns),
   mpColumnStart(new size_t[columns + 1]),
   mpRowIndex(nonZeros ? new size_t[nonZeros] : NULL),
   mpValue(nonZeros ? new C_FLOAT64[nonZeros] : NULL)
 {mpColumnStart[mNumCols] = nonZeros;}
CCompressedColumnFormat::CCompressedColumnFormat (const CSparseMatrix & matrix)
Definition at line 486 of file CSparseMatrix.cpp.
                                                                             :
   mNumRows(0),
   mNumCols(0),
   mpColumnStart(NULL),
   mpRowIndex(NULL),
   mpValue(NULL)
 {*this = matrix;}
CCompressedColumnFormat::~CCompressedColumnFormat ()
Definition at line 494 of file CSparseMatrix.cpp.
References mpColumnStart, mpRowIndex, mpValue, and pdelete.
 {
   pdelete(mpValue);
   pdelete(mpRowIndex);
   pdelete(mpColumnStart);
 }
Member Function Documentation
CCompressedColumnFormat::const_row_iterator CCompressedColumnFormat::beginRow (const size_t & row) const
Definition at line 579 of file CSparseMatrix.cpp.
 {return const_row_iterator(this, row);}
CCompressedColumnFormat::const_row_iterator CCompressedColumnFormat::endRow (const size_t & row) const
Definition at line 581 of file CSparseMatrix.cpp.
 {return const_row_iterator(this);}
const size_t * CCompressedColumnFormat::getColumnStart () const
Definition at line 522 of file CSparseMatrix.cpp.
References mpColumnStart.
Referenced by CCompressedColumnFormat::const_row_iterator::const_row_iterator(), and CSparseMatrix::operator=().
 {return mpColumnStart;}
size_t * CCompressedColumnFormat::getColumnStart ()
Definition at line 525 of file CSparseMatrix.cpp.
References mpColumnStart.
 {return mpColumnStart;}
const size_t * CCompressedColumnFormat::getRowIndex () const
Definition at line 516 of file CSparseMatrix.cpp.
References mpRowIndex.
Referenced by CCompressedColumnFormat::const_row_iterator::const_row_iterator(), and CSparseMatrix::operator=().
 {return mpRowIndex;}
size_t * CCompressedColumnFormat::getRowIndex ()
Definition at line 519 of file CSparseMatrix.cpp.
References mpRowIndex.
 {return mpRowIndex;}
const C_FLOAT64 * CCompressedColumnFormat::getValues () const
Definition at line 510 of file CSparseMatrix.cpp.
References mpValue.
Referenced by CSparseMatrix::operator=().
 {return mpValue;}
C_FLOAT64 * CCompressedColumnFormat::getValues ()
Definition at line 513 of file CSparseMatrix.cpp.
References mpValue.
 {return mpValue;}
size_t CCompressedColumnFormat::numCols () const
Definition at line 504 of file CSparseMatrix.cpp.
References mNumCols.
Referenced by CSparseMatrix::operator=().
 {return mNumCols;}
size_t CCompressedColumnFormat::numNonZeros () const
Definition at line 507 of file CSparseMatrix.cpp.
References mNumCols, and mpColumnStart.
 {return mpColumnStart[mNumCols];}
size_t CCompressedColumnFormat::numRows () const
Definition at line 501 of file CSparseMatrix.cpp.
References mNumRows.
Referenced by CCompressedColumnFormat::const_row_iterator::const_row_iterator(), and CSparseMatrix::operator=().
 {return mNumRows;}
CCompressedColumnFormat & CCompressedColumnFormat::operator= (const CSparseMatrix & ccf)
Definition at line 528 of file CSparseMatrix.cpp.
References C_FLOAT64, CSparseMatrix::getColumns(), mNumCols, mNumRows, mpColumnStart, mpRowIndex, mpValue, CSparseMatrix::numCols(), CSparseMatrix::numNonZeros(), CSparseMatrix::numRows(), and pdelete.
 {
   pdelete(mpValue);
   pdelete(mpRowIndex);
   pdelete(mpColumnStart);
   mNumRows = matrix.numRows();
   mNumCols = matrix.numCols();
   mpColumnStart = new size_t[mNumCols + 1];
   mpColumnStart[mNumCols] = matrix.numNonZeros();
   if (mpColumnStart[mNumCols])
     {
       mpRowIndex = new size_t[mpColumnStart[mNumCols]];
       mpValue = new C_FLOAT64[mpColumnStart[mNumCols]];
     }
   else
     {
       mpRowIndex = NULL;
       mpValue = NULL;
     }
   size_t k = 0;
   size_t i;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator itCol;
   std::vector< std::vector< CSparseMatrixElement * > >::const_iterator endCol;
   std::vector< CSparseMatrixElement * >::const_iterator itElement;
   std::vector< CSparseMatrixElement * >::const_iterator endElement;
   size_t * pRowIndex = mpRowIndex;
   C_FLOAT64 * pValue = mpValue;
   for (i = 0, itCol = matrix.getColumns().begin(), endCol = matrix.getColumns().end();
        itCol != endCol; ++itCol, i++)
     {
       mpColumnStart[i] = k;
       for (itElement = itCol->begin(), endElement = itCol->end();
            itElement != endElement; ++itElement, k++, pRowIndex++, pValue++)
         {
           *pRowIndex = (*itElement)->row();
           *pValue = **itElement;
         }
     }
   return *this;
 }
Member Data Documentation
size_t CCompressedColumnFormat::mNumCols private
Definition at line 133 of file CSparseMatrix.h.
Referenced by CCompressedColumnFormat(), numCols(), numNonZeros(), and operator=().
size_t CCompressedColumnFormat::mNumRows private
Definition at line 132 of file CSparseMatrix.h.
Referenced by numRows(), and operator=().
size_t* CCompressedColumnFormat::mpColumnStart private
Definition at line 134 of file CSparseMatrix.h.
Referenced by CCompressedColumnFormat(), getColumnStart(), numNonZeros(), operator=(), and ~CCompressedColumnFormat().
size_t* CCompressedColumnFormat::mpRowIndex private
Definition at line 135 of file CSparseMatrix.h.
Referenced by getRowIndex(), CCompressedColumnFormat::const_row_iterator::operator++(), CCompressedColumnFormat::const_row_iterator::operator=(), operator=(), and ~CCompressedColumnFormat().
C_FLOAT64* CCompressedColumnFormat::mpValue private
Definition at line 136 of file CSparseMatrix.h.
Referenced by getValues(), operator=(), and ~CCompressedColumnFormat().
The documentation for this class was generated from the following files:
CSparseMatrix.h
CSparseMatrix.cpp