COPASI API: CQModelWidget Class Reference
CQModelWidget Class Reference
#include <CQModelWidget.h>
Public Member Functions
CQModelWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQModelWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
virtual void slotBtnOKClicked ()
virtual void slotBtnRevertClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
Private Member Functions
void load ()
void save ()
Private Attributes
CModel * mpModel
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 23 of file CQModelWidget.h.
Constructor & Destructor Documentation
CQModelWidget::CQModelWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 19 of file CQModelWidget.cpp.
References CModel::AreaUnitNames, CModel::LengthUnitNames, CModel::QuantityUnitNames, CModel::TimeUnitNames, and CModel::VolumeUnitNames.
                                                               :
   CopasiWidget(parent, name),
   mpModel(NULL)
 {
   setupUi(this);
   QStringList ComboEntries;
   const char ** pComboEntries;
   for (pComboEntries = CModel::TimeUnitNames; *pComboEntries != NULL; ++pComboEntries)
     {
       ComboEntries.push_front(QString::fromUtf8(*pComboEntries));
     }
   mpComboTimeUnit->clear();
   mpComboTimeUnit->insertItems(0, ComboEntries);
   ComboEntries.clear();
   for (pComboEntries = CModel::VolumeUnitNames; *pComboEntries != NULL; ++pComboEntries)
     {
       ComboEntries.push_front(QString::fromUtf8(*pComboEntries));
     }
   mpComboVolumeUnit->clear();
   mpComboVolumeUnit->insertItems(0, ComboEntries);
   ComboEntries.clear();
   for (pComboEntries = CModel::AreaUnitNames; *pComboEntries != NULL; ++pComboEntries)
     {
       ComboEntries.push_front(QString::fromUtf8(*pComboEntries));
     }
   mpComboAreaUnit->clear();
   mpComboAreaUnit->insertItems(0, ComboEntries);
   ComboEntries.clear();
   for (pComboEntries = CModel::LengthUnitNames; *pComboEntries != NULL; ++pComboEntries)
     {
       ComboEntries.push_front(QString::fromUtf8(*pComboEntries));
     }
   mpComboLengthUnit->clear();
   mpComboLengthUnit->insertItems(0, ComboEntries);
   ComboEntries.clear();
   for (pComboEntries = CModel::QuantityUnitNames; *pComboEntries != NULL; ++pComboEntries)
     {
       ComboEntries.push_front(QString::fromUtf8(*pComboEntries));
     }
   mpComboQuantityUnit->clear();
   mpComboQuantityUnit->insertItems(0, ComboEntries);
 #ifndef COPASI_EXTUNIT
   mpLblAreaUnit->hide();
   mpComboAreaUnit->hide();
   mpLblLengthUnit->hide();
   mpComboLengthUnit->hide();
 #endif
 }
CQModelWidget::~CQModelWidget ()
Definition at line 85 of file CQModelWidget.cpp.
 {}
Member Function Documentation
bool CQModelWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 219 of file CQModelWidget.cpp.
References load(), CopasiWidget::mKey, mpModel, and CopasiWidget::mpObject.
 {
   if (mpObject != NULL)
     mpModel = dynamic_cast< CModel * >(mpObject);
   else
     mpModel = NULL;
   load();
   mpNotes->enter(mKey);
   return true;
 }
bool CQModelWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 210 of file CQModelWidget.cpp.
References save().
 {
   save();
   mpNotes->leave();
   return true;
 }
void CQModelWidget::load () private
Definition at line 88 of file CQModelWidget.cpp.
References CModel::deterministic, FROM_UTF8, CModel::getAreaUnitName(), CModel::getInitialTime(), CModel::getLengthUnitName(), CModel::getModelType(), CModel::getQuantityUnitName(), CModel::getTime(), CModel::getTimeUnitName(), CModel::getVolumeUnitName(), CModel::isAutonomous(), and mpModel.
Referenced by enterProtected(), slotBtnOKClicked(), and slotBtnRevertClicked().
 {
   if (mpModel == NULL)
     return;
   mpComboTimeUnit->setCurrentIndex(mpComboTimeUnit->findText(FROM_UTF8(mpModel->getTimeUnitName())));
   mpComboVolumeUnit->setCurrentIndex(mpComboVolumeUnit->findText(FROM_UTF8(mpModel->getVolumeUnitName())));
   mpComboQuantityUnit->setCurrentIndex(mpComboQuantityUnit->findText(FROM_UTF8(mpModel->getQuantityUnitName())));
   mpComboAreaUnit->setCurrentIndex(mpComboAreaUnit->findText(FROM_UTF8(mpModel->getAreaUnitName())));
   mpComboLengthUnit->setCurrentIndex(mpComboLengthUnit->findText(FROM_UTF8(mpModel->getLengthUnitName())));
   mpCheckStochasticCorrection->setChecked(mpModel->getModelType() == CModel::deterministic);
   mpLblInitialTime->setText("Initial Time (" + mpComboTimeUnit->currentText() + ")");
   mpEditInitialTime->setText(QString::number(mpModel->getInitialTime()));
   mpEditInitialTime->setReadOnly(mpModel->isAutonomous());
   mpLblCurrentTime->setText("Time (" + mpComboTimeUnit->currentText() + ")");
   mpEditCurrentTime->setText(QString::number(mpModel->getTime()));
   return;
 }
void CQModelWidget::save () private
Definition at line 111 of file CQModelWidget.cpp.
References ListViews::CHANGE, CCopasiDataModel::changed(), CModel::deterministic, CModel::getAreaUnitName(), CModel::getInitialTime(), CModel::getLengthUnitName(), CModel::getModelType(), CModel::getQuantityUnitName(), CModel::getTimeUnitName(), CModel::getVolumeUnitName(), CopasiWidget::mKey, ListViews::MODEL, CopasiWidget::mpDataModel, mpModel, CopasiWidget::protectedNotify(), CModel::setAreaUnit(), CModel::setInitialTime(), CModel::setLengthUnit(), CModel::setModelType(), CModel::setQuantityUnit(), CModel::setTimeUnit(), CModel::setVolumeUnit(), CModel::stochastic, and TO_UTF8.
Referenced by leave(), and slotBtnOKClicked().
 {
   if (mpModel == NULL)
     return;
   bool changed = false;
   if (TO_UTF8(mpComboTimeUnit->currentText()) != mpModel->getTimeUnitName())
     {
       mpModel->setTimeUnit(TO_UTF8(mpComboTimeUnit->currentText()));
       changed = true;
     }
   if (TO_UTF8(mpComboVolumeUnit->currentText()) != mpModel->getVolumeUnitName())
     {
       mpModel->setVolumeUnit(TO_UTF8(mpComboVolumeUnit->currentText()));
       changed = true;
     }
   if (TO_UTF8(mpComboAreaUnit->currentText()) != mpModel->getAreaUnitName())
     {
       mpModel->setAreaUnit(TO_UTF8(mpComboAreaUnit->currentText()));
       changed = true;
     }
   if (TO_UTF8(mpComboLengthUnit->currentText()) != mpModel->getLengthUnitName())
     {
       mpModel->setLengthUnit(TO_UTF8(mpComboLengthUnit->currentText()));
       changed = true;
     }
   if (TO_UTF8(mpComboQuantityUnit->currentText()) != mpModel->getQuantityUnitName())
     {
       mpModel->setQuantityUnit(TO_UTF8(mpComboQuantityUnit->currentText()));
       changed = true;
     }
   if (mpCheckStochasticCorrection->isChecked() != (mpModel->getModelType() == CModel::deterministic))
     {
       if (mpCheckStochasticCorrection->isChecked())
         {
           mpModel->setModelType(CModel::deterministic);
         }
       else
         {
           mpModel->setModelType(CModel::stochastic);
         }
       changed = true;
     }
   if (mpEditInitialTime->text() != QString::number(mpModel->getInitialTime()))
     {
       mpModel->setInitialTime(mpEditInitialTime->text().toDouble());
       changed = true;
     }
   if (changed)
     {
       if (mpDataModel != NULL)
         {
           mpDataModel->changed();
         }
       protectedNotify(ListViews::MODEL, ListViews::CHANGE, mKey);
     }
   return;
 }
void CQModelWidget::slotBtnOKClicked () protected virtual slot
Definition at line 186 of file CQModelWidget.cpp.
References load(), and save().
 {
   save();
   load();
 }
void CQModelWidget::slotBtnRevertClicked () protected virtual slot
Definition at line 181 of file CQModelWidget.cpp.
References load().
 {
   load();
 }
bool CQModelWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 192 of file CQModelWidget.cpp.
References CopasiWidget::enter(), CopasiWidget::mIgnoreUpdates, and ListViews::MODEL.
 {
   if (mIgnoreUpdates) return true;
   switch (objectType)
     {
       case ListViews::MODEL:
         enter(key);
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
CModel* CQModelWidget::mpModel private
Definition at line 46 of file CQModelWidget.h.
Referenced by enterProtected(), load(), and save().
The documentation for this class was generated from the following files:
CQModelWidget.h
CQModelWidget.cpp