COPASI API: CDataModelRenameHandler Class Reference
CDataModelRenameHandler Class Reference
#include <CCopasiDataModel.h>
Public Member Functions
CDataModelRenameHandler ()
virtual void handle (const std::string &oldCN, const std::string &newCN) const
void setEnabled (const bool &enabled)
virtual ~CDataModelRenameHandler ()
Public Member Functions inherited from CRenameHandler
virtual ~CRenameHandler ()
Private Attributes
bool mEnabled
Detailed Description
Definition at line 54 of file CCopasiDataModel.h.
Constructor & Destructor Documentation
CDataModelRenameHandler::CDataModelRenameHandler ()
Definition at line 74 of file CCopasiDataModel.cpp.
                                                 :
   CRenameHandler(),
   mEnabled(true)
 {}
virtual CDataModelRenameHandler::~CDataModelRenameHandler () inline virtual
Definition at line 59 of file CCopasiDataModel.h.
 {};
Member Function Documentation
void CDataModelRenameHandler::handle (const std::string & oldCN, const std::string & newCN) const virtual
Implements CRenameHandler.
Definition at line 79 of file CCopasiDataModel.cpp.
References CRegisteredObjectName::getSet(), and mEnabled.
 {
   if (mEnabled)
     {
       std::set<CRegisteredObjectName*>::const_iterator it = CRegisteredObjectName::getSet().begin();
       std::set<CRegisteredObjectName*>::const_iterator itEnd = CRegisteredObjectName::getSet().end();
       size_t oldSize = oldCN.size();
       size_t currentSize;
       for (; it != itEnd; ++it)
         {
           currentSize = (*it)->size();
           // We need to make sure that we not change partial names
           if ((currentSize == oldSize ||
                (currentSize > oldSize && (**it)[oldSize] == ',')) &&
               oldCN.compare(0, oldSize, **it, 0, oldSize) == 0)
             {
               (**it).replace(0, oldSize, newCN);
             }
         }
     }
   return;
 }
void CDataModelRenameHandler::setEnabled (const bool & enabled) virtual
Enable and disable the rename handler
Parameters
const bool & enabled
Implements CRenameHandler.
Definition at line 106 of file CCopasiDataModel.cpp.
References mEnabled.
Referenced by CCopasiDataModel::importSBML(), CCopasiDataModel::importSBMLFromString(), and CCopasiDataModel::loadModel().
 {
   mEnabled = enabled;
 }
Member Data Documentation
bool CDataModelRenameHandler::mEnabled private
Flag whether the rename handler is enable or not
Definition at line 73 of file CCopasiDataModel.h.
Referenced by handle(), and setEnabled().
The documentation for this class was generated from the following files:
CCopasiDataModel.h
CCopasiDataModel.cpp