COPASI API: CLGroup Class Reference
CLGroup Class Reference
#include <CLGroup.h>
Public Member Functions
void addChildElement (const CLTransformation2D *pChild)
CLGroup (CCopasiContainer *pParent=NULL)
CLGroup (const CLGroup &source, CCopasiContainer *pParent=NULL)
CLGroup (const RenderGroup &source, CCopasiContainer *pParent=NULL)
CLRenderCurve * createCurve ()
CLEllipse * createEllipse ()
CLGroup * createGroup ()
CLImage * createImage ()
CLPolygon * createPolygon ()
CLRectangle * createRectangle ()
CLText * createText ()
CCopasiObject * getElement (size_t n)
const CCopasiObject * getElement (size_t n) const
const std::string & getEndHead () const
const std::string & getFontFamily () const
CLRelAbsVector & getFontSize ()
const CLRelAbsVector & getFontSize () const
CLText::FONT_STYLE getFontStyle () const
CLText::FONT_WEIGHT getFontWeight () const
const std::string & getKey () const
const CCopasiVector
< CCopasiObject > * getListOfElements () const
CCopasiVector< CCopasiObject > * getListOfElements ()
size_t getNumElements () const
const std::string & getStartHead () const
CLText::TEXT_ANCHOR getTextAnchor () const
CLText::TEXT_ANCHOR getVTextAnchor () const
bool isSetEndHead () const
bool isSetFontFamily () const
bool isSetFontSize () const
bool isSetFontStyle () const
bool isSetFontWeight () const
bool isSetStartHead () const
bool isSetTextAnchor () const
bool isSetVTextAnchor () const
void setEndHead (const std::string &key)
void setFontFamily (const std::string &family)
void setFontSize (const CLRelAbsVector &size)
void setFontStyle (CLText::FONT_STYLE style)
void setFontWeight (CLText::FONT_WEIGHT weight)
void setStartHead (const std::string &key)
void setTextAnchor (CLText::TEXT_ANCHOR anchor)
void setVTextAnchor (CLText::TEXT_ANCHOR anchor)
RenderGroup * toSBML (unsigned int level, unsigned int version) const
~CLGroup ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CCopasiVector< CCopasiObject > mElements
std::string mEndHead
std::string mFontFamily
CLRelAbsVector mFontSize
CLText::FONT_STYLE mFontStyle
CLText::FONT_WEIGHT mFontWeight
std::string mKey
std::string mStartHead
CLText::TEXT_ANCHOR mTextAnchor
CLText::TEXT_ANCHOR mVTextAnchor
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CLGroup & operator= (const CLGroup &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET, NONZERO, EVENODD, INHERIT }
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 33 of file CLGroup.h.
Constructor & Destructor Documentation
CLGroup::CLGroup (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 42 of file CLGroup.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
Referenced by addChildElement(), CLGroup(), and createGroup().
                                          :
   CLGraphicalPrimitive2D(),
   CCopasiContainer("RenderGroup", pParent),
   mFontFamily(""),
   mFontSize(CLRelAbsVector(std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN())),
   mFontWeight(CLText::WEIGHT_UNSET),
   mFontStyle(CLText::STYLE_UNSET),
   mTextAnchor(CLText::ANCHOR_UNSET),
   mVTextAnchor(CLText::ANCHOR_UNSET),
   mStartHead(""),
   mEndHead(""),
   mElements("GroupElements", this),
   mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RenderGroup", this);
 }
CLGroup::CLGroup (const CLGroup & source, CCopasiContainer * pParent = NULL)
Copy constructor.
Definition at line 62 of file CLGroup.cpp.
References CKeyFactory::add(), CCopasiVector< T >::add(), CLGroup(), CCopasiRootContainer::getKeyFactory(), mElements, mKey, and CCopasiVector< T >::size().
                                                                 :
   CLGraphicalPrimitive2D(source),
   CCopasiContainer(source, pParent),
   mFontFamily(source.mFontFamily),
   mFontSize(source.mFontSize),
   mFontWeight(source.mFontWeight),
   mFontStyle(source.mFontStyle),
   mTextAnchor(source.mTextAnchor),
   mVTextAnchor(source.mVTextAnchor),
   mStartHead(source.mStartHead),
   mEndHead(source.mEndHead),
   mElements("GroupElements", this),
   mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RenderGroup", this);
   // copy the elements
   size_t i, iMax = source.mElements.size();
   CCopasiObject* pChild = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pChild = source.mElements[i];
       if (dynamic_cast<const CLRectangle*>(pChild))
         {
           this->mElements.add(new CLRectangle(*static_cast<const CLRectangle*>(pChild), this), true);
         }
       else if (dynamic_cast<const CLEllipse*>(pChild))
         {
           this->mElements.add(new CLEllipse(*static_cast<const CLEllipse*>(pChild), this), true);
         }
       else if (dynamic_cast<const CLRenderCurve*>(pChild))
         {
           this->mElements.add(new CLRenderCurve(*static_cast<const CLRenderCurve*>(pChild), this), true);
         }
       else if (dynamic_cast<const CLPolygon*>(pChild))
         {
           this->mElements.add(new CLPolygon(*static_cast<const CLPolygon*>(pChild), this), true);
         }
       else if (dynamic_cast<const CLText*>(pChild))
         {
           this->mElements.add(new CLText(*static_cast<const CLText*>(pChild), this), true);
         }
       else if (dynamic_cast<const CLImage*>(pChild))
         {
           this->mElements.add(new CLImage(*static_cast<const CLImage*>(pChild), this), true);
         }
       else if (dynamic_cast<const CLGroup*>(pChild))
         {
           this->mElements.add(new CLGroup(*static_cast<const CLGroup*>(pChild), this), true);
         }
     }
 }
CLGroup::CLGroup (const RenderGroup & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 119 of file CLGroup.cpp.
References CKeyFactory::add(), CCopasiVector< T >::add(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_START, CLText::ANCHOR_TOP, CLText::ANCHOR_UNSET, CLGroup(), CCopasiRootContainer::getKeyFactory(), mElements, mKey, setFontStyle(), setFontWeight(), setTextAnchor(), setVTextAnchor(), CLText::STYLE_ITALIC, CLText::STYLE_NORMAL, CLText::STYLE_UNSET, CLText::WEIGHT_BOLD, CLText::WEIGHT_NORMAL, and CLText::WEIGHT_UNSET.
                                                                     :
   CLGraphicalPrimitive2D(source),
   CCopasiContainer("RenderGroup", pParent),
   mFontFamily(source.getFontFamily()),
   mFontSize(source.getFontSize()),
   mStartHead(source.getStartHead()),
   mEndHead(source.getEndHead()),
   mElements("GroupElements", this),
   mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("RenderGroup", this);
   // copy the elements
   switch (source.getFontWeight())
     {
       case Text::WEIGHT_UNSET:
         this->setFontWeight(CLText::WEIGHT_UNSET);
         break;
       case Text::WEIGHT_BOLD:
         this->setFontWeight(CLText::WEIGHT_BOLD);
         break;
       default:
         this->setFontWeight(CLText::WEIGHT_NORMAL);
         break;
     }
   switch (source.getFontStyle())
     {
       case Text::STYLE_UNSET:
         this->setFontStyle(CLText::STYLE_UNSET);
         break;
       case Text::STYLE_ITALIC:
         this->setFontStyle(CLText::STYLE_ITALIC);
         break;
       default:
         this->setFontStyle(CLText::STYLE_NORMAL);
         break;
     }
   switch (source.getTextAnchor())
     {
       case Text::ANCHOR_UNSET:
         this->setTextAnchor(CLText::ANCHOR_UNSET);
         break;
       case Text::ANCHOR_END:
         this->setTextAnchor(CLText::ANCHOR_END);
         break;
       case Text::ANCHOR_MIDDLE:
         this->setTextAnchor(CLText::ANCHOR_MIDDLE);
         break;
       default:
         this->setTextAnchor(CLText::ANCHOR_START);
         break;
     }
   switch (source.getVTextAnchor())
     {
       case Text::ANCHOR_UNSET:
         this->setVTextAnchor(CLText::ANCHOR_UNSET);
         break;
       case Text::ANCHOR_BOTTOM:
         this->setVTextAnchor(CLText::ANCHOR_BOTTOM);
         break;
       case Text::ANCHOR_MIDDLE:
         this->setVTextAnchor(CLText::ANCHOR_MIDDLE);
         break;
       default:
         this->setVTextAnchor(CLText::ANCHOR_TOP);
         break;
     }
   size_t i, iMax = source.getNumElements();
   const Transformation2D* pChild = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pChild = dynamic_cast<const Transformation2D*>(source.getElement((unsigned int) i));
       if (dynamic_cast<const Rectangle*>(pChild))
         {
           this->mElements.add(new CLRectangle(*static_cast<const Rectangle*>(pChild), this), true);
         }
       else if (dynamic_cast<const Ellipse*>(pChild))
         {
           this->mElements.add(new CLEllipse(*static_cast<const Ellipse*>(pChild), this), true);
         }
       else if (dynamic_cast<const RenderCurve*>(pChild))
         {
           this->mElements.add(new CLRenderCurve(*static_cast<const RenderCurve*>(pChild), this), true);
         }
       else if (dynamic_cast<const Polygon*>(pChild))
         {
           this->mElements.add(new CLPolygon(*static_cast<const Polygon*>(pChild), this), true);
         }
       else if (dynamic_cast<const Text*>(pChild))
         {
           this->mElements.add(new CLText(*static_cast<const Text*>(pChild), this), true);
         }
       else if (dynamic_cast<const Image*>(pChild))
         {
           this->mElements.add(new CLImage(*static_cast<const Image*>(pChild), this), true);
         }
       else if (dynamic_cast<const RenderGroup*>(pChild))
         {
           this->mElements.add(new CLGroup(*static_cast<const RenderGroup*>(pChild), this), true);
         }
     }
 }
CLGroup::~CLGroup ()
Destructor.
Destructor
Definition at line 240 of file CLGroup.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(this->mKey);
 }
Member Function Documentation
void CLGroup::addChildElement (const CLTransformation2D * pChild)
Adds a copy of the given element to the end of the list of children elements.
Definition at line 517 of file CLGroup.cpp.
References CCopasiVector< T >::add(), CLGroup(), and mElements.
Referenced by CCopasiXMLParser::ImageElement::start(), CCopasiXMLParser::RectangleElement::start(), CCopasiXMLParser::EllipseElement::start(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), and CCopasiXMLParser::GroupElement::start().
 {
   if (dynamic_cast<const CLRectangle*>(pChild))
     {
       this->mElements.add(new CLRectangle(*static_cast<const CLRectangle*>(pChild), this), true);
     }
   else if (dynamic_cast<const CLEllipse*>(pChild))
     {
       this->mElements.add(new CLEllipse(*static_cast<const CLEllipse*>(pChild), this), true);
     }
   else if (dynamic_cast<const CLRenderCurve*>(pChild))
     {
       this->mElements.add(new CLRenderCurve(*static_cast<const CLRenderCurve*>(pChild), this), true);
     }
   else if (dynamic_cast<const CLPolygon*>(pChild))
     {
       this->mElements.add(new CLPolygon(*static_cast<const CLPolygon*>(pChild), this), true);
     }
   else if (dynamic_cast<const CLText*>(pChild))
     {
       this->mElements.add(new CLText(*static_cast<const CLText*>(pChild), this), true);
     }
   else if (dynamic_cast<const CLImage*>(pChild))
     {
       this->mElements.add(new CLImage(*static_cast<const CLImage*>(pChild), this), true);
     }
   else if (dynamic_cast<const CLGroup*>(pChild))
     {
       this->mElements.add(new CLGroup(*static_cast<const CLGroup*>(pChild), this), true);
     }
 }
CLRenderCurve * CLGroup::createCurve ()
Creates a curve object and adds it to the end of the list of child elements.
Definition at line 485 of file CLGroup.cpp.
References CCopasiVector< T >::add(), and mElements.
 {
   CLRenderCurve* pCurve = new CLRenderCurve(this);
   this->mElements.add(pCurve, true);
   return pCurve;
 }
CLEllipse * CLGroup::createEllipse ()
Creates an ellipse object and adds it to the end of the list of child elements.
Definition at line 474 of file CLGroup.cpp.
References CCopasiVector< T >::add(), and mElements.
 {
   CLEllipse* pCLEllipse = new CLEllipse(this);
   this->mElements.add(pCLEllipse, true);
   return pCLEllipse;
 }
CLGroup * CLGroup::createGroup ()
Creates an image object and adds it to the end of the list of child elements.
Definition at line 452 of file CLGroup.cpp.
References CCopasiVector< T >::add(), CLGroup(), and mElements.
 {
   CLGroup* pCLGroup = new CLGroup(this);
   this->mElements.add(pCLGroup, true);
   return pCLGroup;
 }
CLImage * CLGroup::createImage ()
Creates an image object and adds it to the end of the list of child elements.
Definition at line 441 of file CLGroup.cpp.
References CCopasiVector< T >::add(), and mElements.
 {
   CLImage* pCLImage = new CLImage(this);
   this->mElements.add(pCLImage, true);
   return pCLImage;
 }
CLPolygon * CLGroup::createPolygon ()
Creates a polygon object and adds it to the end of the list of child elements.
Definition at line 496 of file CLGroup.cpp.
References CCopasiVector< T >::add(), and mElements.
 {
   CLPolygon* pCLPolygon = new CLPolygon(this);
   this->mElements.add(pCLPolygon, true);
   return pCLPolygon;
 }
CLRectangle * CLGroup::createRectangle ()
Creates a rectangle object and adds it to the end of the list of child elements.
Definition at line 463 of file CLGroup.cpp.
References CCopasiVector< T >::add(), and mElements.
 {
   CLRectangle* pCLRectangle = new CLRectangle(this);
   this->mElements.add(pCLRectangle, true);
   return pCLRectangle;
 }
CLText * CLGroup::createText ()
Creates a text object and adds it to the end of the list of child elements.
Definition at line 507 of file CLGroup.cpp.
References CCopasiVector< T >::add(), and mElements.
 {
   CLText* pCLText = new CLText(this);
   this->mElements.add(pCLText, true);
   return pCLText;
 }
CCopasiObject * CLGroup::getElement (size_t n)
Returns element with index n. If there is no such element, NULL is returned.
Definition at line 409 of file CLGroup.cpp.
References mElements, and CCopasiVector< T >::size().
Referenced by addLineEndingToItem(), CLLayoutRenderer::draw_group(), fillItemFromGroup(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), CCopasiXMLParser::GroupElement::start(), and CLLayoutRenderer::update_textures_and_colors().
 {
   if (n < this->mElements.size())
     {
       return this->mElements[n];
     }
   else
     {
       return NULL;
     }
 }
const CCopasiObject * CLGroup::getElement (size_t n) const
Returns element with index n. If there is no such element, NULL is returned.
Definition at line 425 of file CLGroup.cpp.
References mElements, and CCopasiVector< T >::size().
 {
   if (n < this->mElements.size())
     {
       return this->mElements[n];
     }
   else
     {
       return NULL;
     }
 }
const std::string & CLGroup::getEndHead () const
Returns the end head id.
Definition at line 376 of file CLGroup.cpp.
References mEndHead.
Referenced by CQRenderConverter::applyStyle(), fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mEndHead;
 }
const std::string & CLGroup::getFontFamily () const
Returns the font family.
Definition at line 312 of file CLGroup.cpp.
References mFontFamily.
Referenced by getFont(), CLLayoutRenderer::getFontSpec(), and toSBML().
 {
   return this->mFontFamily;
 }
CLRelAbsVector & CLGroup::getFontSize ()
Returns the font size.
Definition at line 320 of file CLGroup.cpp.
References mFontSize.
Referenced by getFont(), CLLayoutRenderer::getFontSpec(), and toSBML().
 {
   return this->mFontSize;
 }
const CLRelAbsVector & CLGroup::getFontSize () const
Returns the font size.
Definition at line 328 of file CLGroup.cpp.
References mFontSize.
 {
   return this->mFontSize;
 }
CLText::FONT_STYLE CLGroup::getFontStyle () const
Returns the font style.
Definition at line 344 of file CLGroup.cpp.
References mFontStyle.
Referenced by getFont(), CLLayoutRenderer::getFontSpec(), and toSBML().
 {
   return this->mFontStyle;
 }
CLText::FONT_WEIGHT CLGroup::getFontWeight () const
Returns the font weight.
Definition at line 336 of file CLGroup.cpp.
References mFontWeight.
Referenced by getFont(), CLLayoutRenderer::getFontSpec(), and toSBML().
 {
   return this->mFontWeight;
 }
const std::string & CLGroup::getKey () const virtual
Returns the key string of the object.
Returns the key of the color definition.
Reimplemented from CCopasiObject.
Definition at line 791 of file CLGroup.cpp.
References mKey.
 {
   return this->mKey;
 }
const CCopasiVector< CCopasiObject > * CLGroup::getListOfElements () const
Returns the list of elements.
Definition at line 392 of file CLGroup.cpp.
References mElements.
 {
   return &this->mElements;
 }
CCopasiVector< CCopasiObject > * CLGroup::getListOfElements ()
Returns the list of elements.
Definition at line 400 of file CLGroup.cpp.
References mElements.
 {
   return &this->mElements;
 }
size_t CLGroup::getNumElements () const
Returns the number of elements in the group.
Definition at line 384 of file CLGroup.cpp.
References mElements, and CCopasiVector< T >::size().
Referenced by addLineEndingToItem(), CLLayoutRenderer::draw_group(), fillItemFromGroup(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), CCopasiXMLParser::GroupElement::start(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mElements.size();
 }
const std::string & CLGroup::getStartHead () const
Returns the start head id.
Definition at line 368 of file CLGroup.cpp.
References mStartHead.
Referenced by CQRenderConverter::applyStyle(), fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mStartHead;
 }
CLText::TEXT_ANCHOR CLGroup::getTextAnchor () const
Returns the text anchor.
Definition at line 352 of file CLGroup.cpp.
References mTextAnchor.
Referenced by adjustPosition(), and toSBML().
 {
   return this->mTextAnchor;
 }
CLText::TEXT_ANCHOR CLGroup::getVTextAnchor () const
Returns the vertical text anchor.
Definition at line 360 of file CLGroup.cpp.
References mVTextAnchor.
Referenced by adjustPosition(), and toSBML().
 {
   return this->mVTextAnchor;
 }
bool CLGroup::isSetEndHead () const
Returns true if the start head is set or false otherwise.
Definition at line 560 of file CLGroup.cpp.
References mEndHead.
Referenced by CQRenderConverter::applyStyle(), CCopasiXMLParser::GroupElement::end(), fillItemFromRenderCurve(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return (!this->mEndHead.empty() && this->mEndHead != "none");
 }
bool CLGroup::isSetFontFamily () const
Returns true if the font family has been set or false otherwise.
Definition at line 568 of file CLGroup.cpp.
References mFontFamily.
Referenced by CCopasiXMLParser::GroupElement::end(), getFont(), and CLLayoutRenderer::getFontSpec().
 {
   return !this->mFontFamily.empty();
 }
bool CLGroup::isSetFontSize () const
Returns true if the font size has been set or false otherwise.
Definition at line 576 of file CLGroup.cpp.
References CLRelAbsVector::getAbsoluteValue(), CLRelAbsVector::getRelativeValue(), and mFontSize.
Referenced by getFont(), and CLLayoutRenderer::getFontSpec().
 {
   return (this->mFontSize.getAbsoluteValue() == this->mFontSize.getAbsoluteValue() && this->mFontSize.getRelativeValue() == this->mFontSize.getRelativeValue());
 }
bool CLGroup::isSetFontStyle () const
Returns true if the font style has been set or false otherwise.
Definition at line 592 of file CLGroup.cpp.
References mFontStyle, and CLText::STYLE_UNSET.
Referenced by CCopasiXMLParser::GroupElement::end(), getFont(), and CLLayoutRenderer::getFontSpec().
 {
   return (this->mFontStyle != CLText::STYLE_UNSET);
 }
bool CLGroup::isSetFontWeight () const
Returns true if the font weight has been set or false otherwise.
Definition at line 584 of file CLGroup.cpp.
References mFontWeight, and CLText::WEIGHT_UNSET.
Referenced by CCopasiXMLParser::GroupElement::end(), getFont(), and CLLayoutRenderer::getFontSpec().
 {
   return (this->mFontWeight != CLText::WEIGHT_UNSET);
 }
bool CLGroup::isSetStartHead () const
Returns true if the start head is set or false otherwise.
Definition at line 552 of file CLGroup.cpp.
References mStartHead.
Referenced by CCopasiXMLParser::GroupElement::end(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return (!this->mStartHead.empty() && this->mStartHead != "none");
 }
bool CLGroup::isSetTextAnchor () const
Returns true if the horizonal alignment attribute has been set.
This methods imports a curve in the old format into the new format. Since the old curves could have gaps, the original curve might have to be split into several new curves. void CLGroup::importOldCurve(const XMLNode& node) { const XMLAttributes& curveAttributes=node.getAttributes(); const XMLNode* child; size_t n=0,nMax = node.getNumChildren(); const XMLNode* pOrigAnnotation=NULL; const XMLNode* pOrigNotes=NULL; while(n<nMax) { child=&node.getChild(n); std::string childName=child->getName(); if(childName=="listOfCurveSegments") { size_t i,iMax=child->getNumChildren(); const XMLNode* child2=NULL; CLRenderPoint start; CLRenderPoint end; CLRenderPoint lastEnd; CLRenderPoint bp1; CLRenderPoint bp2; bool startSet=false; bool endSet=false; bool bp1Set=false; bool bp2Set=false; std::string childName2; CLRenderCurve* pCurve=new CLRenderCurve(); read the attributes pCurve->Transformation2D::readAttributes(curveAttributes); pCurve->GraphicalPrimitive1D::readAttributes(curveAttributes); pCurve->readAttributes(curveAttributes); for(i=0;i<iMax;++i) { child2=&child->getChild(i); childName2=child2->getName(); if(childName2=="curveSegment") { startSet=false; endSet=false; bp1Set=false; bp2Set=false; const XMLAttributes& innerAttributes=child2->getAttributes(); int typeIndex=innerAttributes.getIndex("type"); if(typeIndex==-1 || innerAttributes.getURI(typeIndex)!="http://www.w3.org/2001/XMLSchema-instance") { continue; } size_t j,jMax=child2->getNumChildren(); for(j=0;j<jMax;++j) { const XMLNode* child3=&child2->getChild(j); std::string childName3=child3->getName(); if(childName3=="start") { start=CLRenderPoint(<em>child3); startSet=true; } add the basepoints and the endpoint else if(childName3=="end") { end=CLRenderPoint(*child3); endSet=true; } else if(innerAttributes.getValue(typeIndex)=="CubicBezier" && childName3=="basePoint1") { bp1=CLRenderPoint(*child3); bp1Set=true; } else if(innerAttributes.getValue(typeIndex)=="CubicBezier" && childName3=="basePoint2") { bp2=CLRenderPoint(*child3); bp2Set=true; } } if(!startSet || !endSet) { skip this point TODO this is an error continue; } if(pCurve->getNumElements()==0) { add the start point pCurve->addCurveElement(&start); } else { check if start is identical to lastEnd if not, we have to start a new curve if(!(start == lastEnd)) { if(pCurve->getNumElements() > 1) { add the curve to the goup this->mElements.add(pCurve,true); } else { delete pCurve; } we have do clear the endHead on the preceeding curve pCurve->setEndHead("none"); pCurve=new CLRenderCurve(); read the attributes pCurve->Transformation2D::readAttributes(curveAttributes); pCurve->GraphicalPrimitive1D::readAttributes(curveAttributes); pCurve->readAttributes(curveAttributes); we have to clear the start head on this curve pCurve->setStartHead("none"); pCurve->addCurveElement(&start); } } if(innerAttributes.getValue(typeIndex)=="CubicBezier") { if(!bp1Set) { if(bp2Set) { basepoint1 is the same as basepoint2 bp1=bp2; } else { bp1=CLRenderPoint(CLRelAbsVector((start.x().getAbsoluteValue()+end.x().getAbsoluteValue())/2.0,(start.x().getRelativeValue()+end.x().getRelativeValue())/2.0) ,CLRelAbsVector((start.y().getAbsoluteValue()+end.y().getAbsoluteValue())/2.0,(start.y().getRelativeValue()+end.y().getRelativeValue())/2.0) ,CLRelAbsVector((start.z().getAbsoluteValue()+end.z().getAbsoluteValue())/2.0,(start.z().getRelativeValue()+end.z().getRelativeValue())/2.0)); bp1Set=true; } } if(!bp2Set) { at this time bp1 has to be set bp2=bp1; } add the cubic bezier element CLRenderCubicBezier pBezier=new CLRenderCubicBezier(bp1.x(),bp1.y(),bp1.z(), bp2.x(),bp2.y(),bp2.z(), end.x(),end.y(),end.z()); pCurve->addCurveElement(pBezier); delete pBezier; lastEnd=end; } else { add the end point pCurve->addCurveElement(&end); lastEnd=end; } } } if(pCurve->getNumElements() > 1) { add the curve to the goup this->mElements.add(pCurve,true); } } else if(childName=="annotation") { pOrigAnnotation=child; } else if(childName=="notes") { pOrigNotes=child; } ++n; } } Returns true if the horizonal alignment attribute has been set.
Definition at line 775 of file CLGroup.cpp.
References CLText::ANCHOR_UNSET, and mTextAnchor.
Referenced by adjustPosition(), and CCopasiXMLParser::GroupElement::end().
 {
   return this->mTextAnchor != CLText::ANCHOR_UNSET;
 }
bool CLGroup::isSetVTextAnchor () const
Returns true if the vertical alignment attribute has been set.
Definition at line 783 of file CLGroup.cpp.
References CLText::ANCHOR_UNSET, and mVTextAnchor.
Referenced by adjustPosition(), and CCopasiXMLParser::GroupElement::end().
 {
   return this->mVTextAnchor != CLText::ANCHOR_UNSET;
 }
CLGroup& CLGroup::operator= (const CLGroup & source) private
void CLGroup::setEndHead (const std::string & key)
Sets the end head id.
Definition at line 304 of file CLGroup.cpp.
References mEndHead.
Referenced by CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mEndHead = key;
 }
void CLGroup::setFontFamily (const std::string & family)
Sets the font family.
Definition at line 248 of file CLGroup.cpp.
References mFontFamily.
Referenced by CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mFontFamily = family;
 }
void CLGroup::setFontSize (const CLRelAbsVector & size)
Sets the font size.
Definition at line 256 of file CLGroup.cpp.
References mFontSize.
Referenced by CCopasiXMLParser::GroupElement::start().
 {
   this->mFontSize = size;
 }
void CLGroup::setFontStyle (CLText::FONT_STYLE style)
Sets the font style.
Definition at line 272 of file CLGroup.cpp.
References mFontStyle.
Referenced by CLGroup(), CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mFontStyle = style;
 }
void CLGroup::setFontWeight (CLText::FONT_WEIGHT weight)
Sets the font weight.
Definition at line 264 of file CLGroup.cpp.
References mFontWeight.
Referenced by CLGroup(), CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mFontWeight = weight;
 }
void CLGroup::setStartHead (const std::string & key)
Sets the start head id.
Definition at line 296 of file CLGroup.cpp.
References mStartHead.
Referenced by CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mStartHead = key;
 }
void CLGroup::setTextAnchor (CLText::TEXT_ANCHOR anchor)
Sets the text anchor.
Definition at line 280 of file CLGroup.cpp.
References mTextAnchor.
Referenced by CLGroup(), CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mTextAnchor = anchor;
 }
void CLGroup::setVTextAnchor (CLText::TEXT_ANCHOR anchor)
Sets the vertical text anchor.
Definition at line 288 of file CLGroup.cpp.
References mVTextAnchor.
Referenced by CLGroup(), CCopasiXMLParser::GroupElement::end(), and CCopasiXMLParser::GroupElement::start().
 {
   this->mVTextAnchor = anchor;
 }
RenderGroup * CLGroup::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
Definition at line 799 of file CLGroup.cpp.
References CLGraphicalPrimitive2D::addSBMLAttributes(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_UNSET, getFontFamily(), getFontSize(), getFontStyle(), getFontWeight(), getTextAnchor(), getVTextAnchor(), mElements, mEndHead, mStartHead, CCopasiVector< T >::size(), CLText::STYLE_ITALIC, CLText::STYLE_UNSET, CLRelAbsVector::toSBML(), CLText::WEIGHT_BOLD, and CLText::WEIGHT_UNSET.
Referenced by CLStyle::addSBMLAttributes(), and CLLineEnding::toSBML().
 {
   RenderGroup* pGroup = new RenderGroup(level, version);
   this->addSBMLAttributes(pGroup);
   pGroup->setStartHead(this->mStartHead);
   pGroup->setEndHead(this->mEndHead);
   RelAbsVector* pV = this->getFontSize().toSBML();
   pGroup->setFontSize(*pV);
   delete pV;
   pGroup->setFontFamily(this->getFontFamily());
   switch (this->getFontWeight())
     {
       case CLText::WEIGHT_UNSET:
         pGroup->setFontWeight(Text::WEIGHT_UNSET);
         break;
       case CLText::WEIGHT_BOLD:
         pGroup->setFontWeight(Text::WEIGHT_BOLD);
         break;
       default:
         pGroup->setFontWeight(Text::WEIGHT_NORMAL);
         break;
     }
   switch (this->getFontStyle())
     {
       case CLText::STYLE_UNSET:
         pGroup->setFontStyle(Text::STYLE_UNSET);
         break;
       case CLText::STYLE_ITALIC:
         pGroup->setFontStyle(Text::STYLE_ITALIC);
         break;
       default:
         pGroup->setFontStyle(Text::STYLE_NORMAL);
         break;
     }
   switch (this->getTextAnchor())
     {
       case CLText::ANCHOR_UNSET:
         pGroup->setTextAnchor(Text::ANCHOR_UNSET);
         break;
       case CLText::ANCHOR_END:
         pGroup->setTextAnchor(Text::ANCHOR_END);
         break;
       case CLText::ANCHOR_MIDDLE:
         pGroup->setTextAnchor(Text::ANCHOR_MIDDLE);
         break;
       default:
         pGroup->setTextAnchor(Text::ANCHOR_START);
         break;
     }
   switch (this->getVTextAnchor())
     {
       case CLText::ANCHOR_UNSET:
         pGroup->setVTextAnchor(Text::ANCHOR_UNSET);
         break;
       case CLText::ANCHOR_BOTTOM:
         pGroup->setVTextAnchor(Text::ANCHOR_BOTTOM);
         break;
       case CLText::ANCHOR_MIDDLE:
         pGroup->setVTextAnchor(Text::ANCHOR_MIDDLE);
         break;
       default:
         pGroup->setVTextAnchor(Text::ANCHOR_TOP);
         break;
     }
   size_t i, iMax = this->mElements.size();
   int result;
   for (i = 0; i < iMax; ++i)
     {
       const Transformation2D* pChild = NULL;
       const CCopasiObject* pObject = this->mElements[i];
       if (dynamic_cast<const CLRectangle*>(pObject))
         {
           pChild = static_cast<const CLRectangle*>(pObject)->toSBML(level, version);
         }
       else if (dynamic_cast<const CLEllipse*>(pObject))
         {
           pChild = static_cast<const CLEllipse*>(pObject)->toSBML(level, version);
         }
       else if (dynamic_cast<const CLRenderCurve*>(pObject))
         {
           pChild = static_cast<const CLRenderCurve*>(pObject)->toSBML(level, version);
         }
       else if (dynamic_cast<const CLPolygon*>(pObject))
         {
           pChild = static_cast<const CLPolygon*>(pObject)->toSBML(level, version);
         }
       else if (dynamic_cast<const CLText*>(pObject))
         {
           pChild = static_cast<const CLText*>(pObject)->toSBML(level, version);
         }
       else if (dynamic_cast<const CLImage*>(pObject))
         {
           pChild = static_cast<const CLImage*>(pObject)->toSBML(level, version);
         }
       else if (dynamic_cast<const CLGroup*>(pObject))
         {
           pChild = static_cast<const CLGroup*>(pObject)->toSBML(level, version);
         }
       result = pGroup->addChildElement(pChild);
       assert(result == LIBSBML_OPERATION_SUCCESS);
       delete pChild;
     }
   return pGroup;
 }
Member Data Documentation
CCopasiVector<CCopasiObject> CLGroup::mElements protected
Definition at line 48 of file CLGroup.h.
Referenced by addChildElement(), CLGroup(), createCurve(), createEllipse(), createGroup(), createImage(), createPolygon(), createRectangle(), createText(), getElement(), getListOfElements(), getNumElements(), and toSBML().
std::string CLGroup::mEndHead protected
Definition at line 47 of file CLGroup.h.
Referenced by getEndHead(), isSetEndHead(), setEndHead(), and toSBML().
std::string CLGroup::mFontFamily protected
Definition at line 40 of file CLGroup.h.
Referenced by getFontFamily(), isSetFontFamily(), and setFontFamily().
CLRelAbsVector CLGroup::mFontSize protected
Definition at line 41 of file CLGroup.h.
Referenced by getFontSize(), isSetFontSize(), and setFontSize().
CLText::FONT_STYLE CLGroup::mFontStyle protected
Definition at line 43 of file CLGroup.h.
Referenced by getFontStyle(), isSetFontStyle(), and setFontStyle().
CLText::FONT_WEIGHT CLGroup::mFontWeight protected
Definition at line 42 of file CLGroup.h.
Referenced by getFontWeight(), isSetFontWeight(), and setFontWeight().
std::string CLGroup::mKey protected
key for the object.
Definition at line 53 of file CLGroup.h.
Referenced by CLGroup(), getKey(), and ~CLGroup().
std::string CLGroup::mStartHead protected
Definition at line 46 of file CLGroup.h.
Referenced by getStartHead(), isSetStartHead(), setStartHead(), and toSBML().
CLText::TEXT_ANCHOR CLGroup::mTextAnchor protected
Definition at line 44 of file CLGroup.h.
Referenced by getTextAnchor(), isSetTextAnchor(), and setTextAnchor().
CLText::TEXT_ANCHOR CLGroup::mVTextAnchor protected
Definition at line 45 of file CLGroup.h.
Referenced by getVTextAnchor(), isSetVTextAnchor(), and setVTextAnchor().
The documentation for this class was generated from the following files:
CLGroup.h
CLGroup.cpp