COPASI API: CChemEqParserBase Class Reference
CChemEqParserBase Class Reference abstract
#include <CChemEqParser.h>
Classes
struct Data
Public Member Functions
CChemEqParserBase ()
const std::vector< std::string > & getModifierCompartments () const
const std::vector< C_FLOAT64 > & getModifierMulitplicities () const
const std::vector< std::string > & getModifierNames () const
const std::vector< std::string > & getProductCompartments () const
const std::vector< C_FLOAT64 > & getProductMulitplicities () const
const std::vector< std::string > & getProductNames () const
const std::vector< std::string > & getSubstrateCompartments () const
const std::vector< C_FLOAT64 > & getSubstrateMulitplicities () const
const std::vector< std::string > & getSubstrateNames () const
const bool & isReversible () const
virtual int yylex ()=0
virtual int yyparse ()
virtual ~CChemEqParserBase ()
Protected Member Functions
void correctErrorPosition ()
Protected Attributes
std::vector< std::string > mModifierCompartments
std::vector< C_FLOAT64 > mModifierMult
std::vector< std::string > mModifierNames
Data * mpData
unsigned C_INT32 mPosition
std::vector< std::string > mProductCompartments
std::vector< C_FLOAT64 > mProductMult
std::vector< std::string > mProductNames
bool mReversibility
std::vector< std::string > mSubstrateCompartments
std::vector< C_FLOAT64 > mSubstrateMult
std::vector< std::string > mSubstrateNames
Detailed Description
This is a base class for the CChemEqParser adding member attributes to enhance the internal functionality.
Definition at line 48 of file CChemEqParser.h.
Constructor & Destructor Documentation
CChemEqParserBase::CChemEqParserBase ()
Default constructor
Definition at line 19 of file CChemEqParser.cpp.
   : mpData(NULL)
 {}
CChemEqParserBase::~CChemEqParserBase () virtual
Destructor
Definition at line 23 of file CChemEqParser.cpp.
 {}
Member Function Documentation
void CChemEqParserBase::correctErrorPosition () protected
Definition at line 56 of file CChemEqParser.cpp.
 {return;}
const std::vector< std::string > & CChemEqParserBase::getModifierCompartments () const
Definition at line 53 of file CChemEqParser.cpp.
References mModifierCompartments.
Referenced by CChemEqInterface::setChemEqString().
 {return mModifierCompartments;}
const std::vector< C_FLOAT64 > & CChemEqParserBase::getModifierMulitplicities () const
Definition at line 50 of file CChemEqParser.cpp.
References mModifierMult.
Referenced by CChemEqInterface::setChemEqString().
 {return mModifierMult;}
const std::vector< std::string > & CChemEqParserBase::getModifierNames () const
Definition at line 47 of file CChemEqParser.cpp.
References mModifierNames.
Referenced by CChemEqInterface::setChemEqString().
 {return mModifierNames;}
const std::vector< std::string > & CChemEqParserBase::getProductCompartments () const
Definition at line 44 of file CChemEqParser.cpp.
References mProductCompartments.
Referenced by CChemEqInterface::setChemEqString().
 {return mProductCompartments;}
const std::vector< C_FLOAT64 > & CChemEqParserBase::getProductMulitplicities () const
Definition at line 41 of file CChemEqParser.cpp.
References mProductMult.
Referenced by CChemEqInterface::setChemEqString().
 {return mProductMult;}
const std::vector< std::string > & CChemEqParserBase::getProductNames () const
Definition at line 38 of file CChemEqParser.cpp.
References mProductNames.
Referenced by CChemEqInterface::setChemEqString().
 {return mProductNames;}
const std::vector< std::string > & CChemEqParserBase::getSubstrateCompartments () const
Definition at line 35 of file CChemEqParser.cpp.
References mSubstrateCompartments.
Referenced by CChemEqInterface::setChemEqString(), CMetabNameInterface::splitDisplayName(), and CMetabNameInterface::unQuote().
 {return mSubstrateCompartments;}
const std::vector< C_FLOAT64 > & CChemEqParserBase::getSubstrateMulitplicities () const
Definition at line 32 of file CChemEqParser.cpp.
References mSubstrateMult.
Referenced by CChemEqInterface::setChemEqString().
 {return mSubstrateMult;}
const std::vector< std::string > & CChemEqParserBase::getSubstrateNames () const
Definition at line 29 of file CChemEqParser.cpp.
References mSubstrateNames.
Referenced by CChemEqInterface::setChemEqString(), CMetabNameInterface::splitDisplayName(), and CMetabNameInterface::unQuote().
 {return mSubstrateNames;}
const bool & CChemEqParserBase::isReversible () const
Definition at line 26 of file CChemEqParser.cpp.
References mReversibility.
Referenced by CChemEqInterface::setChemEqString().
 {return mReversibility;}
virtual int CChemEqParserBase::yylex () pure virtual
Implemented in CChemEqParser.
int CChemEqParserBase::yyparse () virtual
Definition at line 1142 of file CChemEqParser_yacc.cpp.
References pdelete, strToDouble(), void(), YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYID, YYINITDEPTH, YYLAST, YYLEX, yylval, YYMAXDEPTH, yynerrs, YYNTOKENS, YYPACT_NINF, YYPOPSTACK, YYSIZE_T, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYSTYPE, YYTABLE_NINF, YYTERROR, and YYTRANSLATE.
Referenced by CChemEqInterface::isValidEq(), CChemEqInterface::setChemEqString(), CMetabNameInterface::splitDisplayName(), and CMetabNameInterface::unQuote().
 {
   int yystate;
   int yyn;
   int yyresult;
   /* Number of tokens to shift before error messages enabled.  */
   int yyerrstatus;
   /* Look-ahead token as an internal (translated) token number.  */
   int yytoken = 0;
 #if YYERROR_VERBOSE
   /* Buffer for error messages, and its allocated size.  */
   char yymsgbuf[128];
   char *yymsg = yymsgbuf;
   YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
 #endif
   /* Three stacks and their tools:
      `yyss': related to states,
      `yyvs': related to semantic values,
      `yyls': related to locations.
      Refer to the stacks thru separate pointers, to allow yyoverflow
      to reallocate them elsewhere.  */
   /* The state stack.  */
   yytype_int16 yyssa[YYINITDEPTH];
   yytype_int16 *yyss = yyssa;
   yytype_int16 *yyssp;
   /* The semantic value stack.  */
   YYSTYPE yyvsa[YYINITDEPTH];
   YYSTYPE *yyvs = yyvsa;
   YYSTYPE *yyvsp;
 #define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))
   YYSIZE_T yystacksize = YYINITDEPTH;
   /* The variables used to return semantic value and location from the
      action routines.  */
   YYSTYPE yyval;
   /* The number of symbols on the RHS of the reduced rule.
      Keep to zero when no symbol should be popped.  */
   int yylen = 0;
   YYDPRINTF((stderr, "Starting parse\n"));
   yystate = 0;
   yyerrstatus = 0;
   yynerrs = 0;
   yychar = YYEMPTY;   /* Cause a token to be read.  */
   /* Initialize stack pointers.
      Waste one element of value and location stack
      so that they stay on the same level as the state stack.
      The wasted elements are never initialized.  */
   yyssp = yyss;
   yyvsp = yyvs;
   goto yysetstate;
   /*------------------------------------------------------------.
   | yynewstate -- Push a new state, which is found in yystate.  |
   `------------------------------------------------------------*/
 yynewstate:
   /* In all cases, when you get here, the value and location stacks
      have just been pushed.  So pushing a state here evens the stacks.  */
   yyssp++;
 yysetstate:
   *yyssp = yystate;
   if (yyss + yystacksize - 1 <= yyssp)
     {
       /* Get the current used size of the three stacks, in elements.  */
       YYSIZE_T yysize = yyssp - yyss + 1;
 #ifdef yyoverflow
       {
         /* Give user a chance to reallocate the stack.  Use copies of
            these so that the &'s don't force the real ones into
            memory.  */
         YYSTYPE *yyvs1 = yyvs;
         yytype_int16 *yyss1 = yyss;
         /* Each stack pointer address is followed by the size of the
            data in use in that stack, in bytes.  This used to be a
            conditional around just the two extra args, but that might
            be undefined if yyoverflow is a macro.  */
         yyoverflow(YY_("memory exhausted"),
                    &yyss1, yysize * sizeof(*yyssp),
                    &yyvs1, yysize * sizeof(*yyvsp),
                    &yystacksize);
         yyss = yyss1;
         yyvs = yyvs1;
       }
 #else /* no yyoverflow */
 # ifndef YYSTACK_RELOCATE
       goto yyexhaustedlab;
 # else
       /* Extend the stack our own way.  */
       if (YYMAXDEPTH <= yystacksize)
         goto yyexhaustedlab;
       yystacksize *= 2;
       if (YYMAXDEPTH < yystacksize)
         yystacksize = YYMAXDEPTH;
       {
         yytype_int16 *yyss1 = yyss;
         union yyalloc *yyptr =
               (union yyalloc *) YYSTACK_ALLOC(YYSTACK_BYTES(yystacksize));
         if (! yyptr)
           goto yyexhaustedlab;
         YYSTACK_RELOCATE(yyss);
         YYSTACK_RELOCATE(yyvs);
 #  undef YYSTACK_RELOCATE
         if (yyss1 != yyssa)
           YYSTACK_FREE(yyss1);
       }
 # endif
 #endif /* no yyoverflow */
       yyssp = yyss + yysize - 1;
       yyvsp = yyvs + yysize - 1;
       YYDPRINTF((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));
       if (yyss + yystacksize - 1 <= yyssp)
         YYABORT;
     }
   YYDPRINTF((stderr, "Entering state %d\n", yystate));
   goto yybackup;
   /*-----------.
   | yybackup.  |
   `-----------*/
 yybackup:
   /* Do appropriate processing given the current state.  Read a
      look-ahead token if we need one and don't already have one.  */
   /* First try to decide what to do without reference to look-ahead token.  */
   yyn = yypact[yystate];
   if (yyn == YYPACT_NINF)
     goto yydefault;
   /* Not known => get a look-ahead token if don't already have one.  */
   /* YYCHAR is either YYEMPTY or YYEOF or a valid look-ahead symbol.  */
   if (yychar == YYEMPTY)
     {
       YYDPRINTF((stderr, "Reading a token: "));
       yychar = YYLEX;
     }
   if (yychar <= YYEOF)
     {
       yychar = yytoken = YYEOF;
       YYDPRINTF((stderr, "Now at end of input.\n"));
     }
   else
     {
       yytoken = YYTRANSLATE(yychar);
       YY_SYMBOL_PRINT("Next token is", yytoken, &yylval, &yylloc);
     }
   /* If the proper action on seeing token YYTOKEN is to reduce or to
      detect an error, take that action.  */
   yyn += yytoken;
   if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
     goto yydefault;
   yyn = yytable[yyn];
   if (yyn <= 0)
     {
       if (yyn == 0 || yyn == YYTABLE_NINF)
         goto yyerrlab;
       yyn = -yyn;
       goto yyreduce;
     }
   if (yyn == YYFINAL)
     YYACCEPT;
   /* Count tokens shifted since error; after three, turn off error
      status.  */
   if (yyerrstatus)
     yyerrstatus--;
   /* Shift the look-ahead token.  */
   YY_SYMBOL_PRINT("Shifting", yytoken, &yylval, &yylloc);
   /* Discard the shifted token unless it is eof.  */
   if (yychar != YYEOF)
     yychar = YYEMPTY;
   yystate = yyn;
   *++yyvsp = yylval;
   goto yynewstate;
   /*-----------------------------------------------------------.
   | yydefault -- do the default action for the current state.  |
   `-----------------------------------------------------------*/
 yydefault:
   yyn = yydefact[yystate];
   if (yyn == 0)
     goto yyerrlab;
   goto yyreduce;
   /*-----------------------------.
   | yyreduce -- Do a reduction.  |
   `-----------------------------*/
 yyreduce:
   /* yyn is the number of a rule to reduce with.  */
   yylen = yyr2[yyn];
   /* If YYLEN is nonzero, implement the default value of the action:
      `$$ = $1'.
      Otherwise, the following line sets YYVAL to garbage.
      This behavior is undocumented and Bison
      users should not rely upon it.  Assigning to YYVAL
      unconditionally makes the parser a bit smaller, and it avoids a
      GCC warning that YYVAL may be used uninitialized.  */
   yyval = yyvsp[1-yylen];
   YY_REDUCE_PRINT(yyn);
   switch (yyn)
     {
       case 2:
 #line 48 "CChemEqParser.ypp"
         {
         }
         break;
       case 3:
 #line 51 "CChemEqParser.ypp"
         {
           mReversibility = ((yyvsp[(2) - (3)])->name == "=") ? true : false;
           pdelete((yyvsp[(2) - (3)]));
         }
         break;
       case 4:
 #line 56 "CChemEqParser.ypp"
         {
         }
         break;
       case 5:
 #line 59 "CChemEqParser.ypp"
         {
           mReversibility = ((yyvsp[(2) - (2)])->name == "=") ? true : false;
           pdelete((yyvsp[(2) - (2)]));
         }
         break;
       case 6:
 #line 64 "CChemEqParser.ypp"
         {
         }
         break;
       case 7:
 #line 68 "CChemEqParser.ypp"
         {
         }
         break;
       case 8:
 #line 72 "CChemEqParser.ypp"
         {
           mSubstrateNames.push_back((yyvsp[(1) - (1)])->name);
           mSubstrateMult.push_back((yyvsp[(1) - (1)])->multiplicity);
           mSubstrateCompartments.push_back((yyvsp[(1) - (1)])->compartment);
           pdelete((yyvsp[(1) - (1)]));
         }
         break;
       case 9:
 #line 79 "CChemEqParser.ypp"
         {
           mSubstrateNames.push_back((yyvsp[(3) - (3)])->name);
           mSubstrateMult.push_back((yyvsp[(3) - (3)])->multiplicity);
           mSubstrateCompartments.push_back((yyvsp[(3) - (3)])->compartment);
           pdelete((yyvsp[(2) - (3)]));
           pdelete((yyvsp[(3) - (3)]));
         }
         break;
       case 10:
 #line 88 "CChemEqParser.ypp"
         {
           mReversibility = ((yyvsp[(1) - (2)])->name == "=") ? true : false;
           mProductNames.push_back((yyvsp[(2) - (2)])->name);
           mProductMult.push_back((yyvsp[(2) - (2)])->multiplicity);
           mProductCompartments.push_back((yyvsp[(2) - (2)])->compartment);
           pdelete((yyvsp[(1) - (2)]));
           pdelete((yyvsp[(2) - (2)]));
         }
         break;
       case 11:
 #line 98 "CChemEqParser.ypp"
         {
           mProductNames.push_back((yyvsp[(3) - (3)])->name);
           mProductMult.push_back((yyvsp[(3) - (3)])->multiplicity);
           mProductCompartments.push_back((yyvsp[(3) - (3)])->compartment);
           pdelete((yyvsp[(2) - (3)]));
           pdelete((yyvsp[(3) - (3)]));
         }
         break;
       case 12:
 #line 107 "CChemEqParser.ypp"
         {
           mModifierNames.push_back((yyvsp[(2) - (2)])->name);
           mModifierMult.push_back((yyvsp[(2) - (2)])->multiplicity);
           mModifierCompartments.push_back((yyvsp[(2) - (2)])->compartment);
           pdelete((yyvsp[(1) - (2)]));
           pdelete((yyvsp[(2) - (2)]));
         }
         break;
       case 13:
 #line 115 "CChemEqParser.ypp"
         {
           mModifierNames.push_back((yyvsp[(2) - (2)])->name);
           mModifierMult.push_back((yyvsp[(2) - (2)])->multiplicity);
           mModifierCompartments.push_back((yyvsp[(2) - (2)])->compartment);
           pdelete((yyvsp[(2) - (2)]));
         }
         break;
       case 14:
 #line 123 "CChemEqParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (1)]);
           (yyval)->compartment = "";
         }
         break;
       case 15:
 #line 128 "CChemEqParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (2)]);
           (yyval)->compartment = (yyvsp[(2) - (2)])->name;
           pdelete((yyvsp[(2) - (2)]));
         }
         break;
       case 16:
 #line 136 "CChemEqParser.ypp"
         {
           (yyval) = (yyvsp[(1) - (1)]);
           (yyval)->multiplicity = 1.0;
         }
         break;
       case 17:
 #line 141 "CChemEqParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (2)]);
           (yyval)->multiplicity = strToDouble((yyvsp[(1) - (2)])->name.c_str(), NULL);
           pdelete((yyvsp[(1) - (2)]));
         }
         break;
       case 18:
 #line 147 "CChemEqParser.ypp"
         {
           (yyval) = (yyvsp[(3) - (3)]);
           (yyval)->multiplicity = strToDouble((yyvsp[(1) - (3)])->name.c_str(), NULL);
           pdelete((yyvsp[(1) - (3)]));
           pdelete((yyvsp[(2) - (3)]));
         }
         break;
       case 19:
 #line 155 "CChemEqParser.ypp"
         {
           (yyval) = (yyvsp[(2) - (3)]);
           pdelete((yyvsp[(1) - (3)]));
           pdelete((yyvsp[(3) - (3)]));
         }
         break;
         /* Line 1267 of yacc.c.  */
 #line 1522 "CChemEqParser_yacc.cpp"
       default: break;
     }
   YY_SYMBOL_PRINT("-> $$ =", yyr1[yyn], &yyval, &yyloc);
   YYPOPSTACK(yylen);
   yylen = 0;
   YY_STACK_PRINT(yyss, yyssp);
   *++yyvsp = yyval;
   /* Now `shift' the result of the reduction.  Determine what state
      that goes to, based on the state we popped back to and the rule
      number reduced by.  */
   yyn = yyr1[yyn];
   yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
   if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
     yystate = yytable[yystate];
   else
     yystate = yydefgoto[yyn - YYNTOKENS];
   goto yynewstate;
   /*------------------------------------.
   | yyerrlab -- here on detecting error |
   `------------------------------------*/
 yyerrlab:
   /* If not already recovering from an error, report this error.  */
   if (!yyerrstatus)
     {
       ++yynerrs;
 #if ! YYERROR_VERBOSE
       yyerror(YY_("syntax error"));
 #else
       {
         YYSIZE_T yysize = yysyntax_error(0, yystate, yychar);
         if (yymsg_alloc < yysize && yymsg_alloc < YYSTACK_ALLOC_MAXIMUM)
           {
             YYSIZE_T yyalloc = 2 * yysize;
             if (!(yysize <= yyalloc && yyalloc <= YYSTACK_ALLOC_MAXIMUM))
               yyalloc = YYSTACK_ALLOC_MAXIMUM;
             if (yymsg != yymsgbuf)
               YYSTACK_FREE(yymsg);
             yymsg = (char *) YYSTACK_ALLOC(yyalloc);
             if (yymsg)
               yymsg_alloc = yyalloc;
             else
               {
                 yymsg = yymsgbuf;
                 yymsg_alloc = sizeof yymsgbuf;
               }
           }
         if (0 < yysize && yysize <= yymsg_alloc)
           {
             (void) yysyntax_error(yymsg, yystate, yychar);
             yyerror(yymsg);
           }
         else
           {
             yyerror(YY_("syntax error"));
             if (yysize != 0)
               goto yyexhaustedlab;
           }
       }
 #endif
     }
   if (yyerrstatus == 3)
     {
       /* If just tried and failed to reuse look-ahead token after an
       error, discard it.  */
       if (yychar <= YYEOF)
         {
           /* Return failure if at end of input.  */
           if (yychar == YYEOF)
             YYABORT;
         }
       else
         {
           yydestruct("Error: discarding",
                      yytoken, &yylval);
           yychar = YYEMPTY;
         }
     }
   /* Else will try to reuse look-ahead token after shifting the error
      token.  */
   goto yyerrlab1;
   /*---------------------------------------------------.
   | yyerrorlab -- error raised explicitly by YYERROR.  |
   `---------------------------------------------------*/
 yyerrorlab:
   /* Pacify compilers like GCC when the user code never invokes
      YYERROR and the label yyerrorlab therefore never appears in user
      code.  */
   if (/*CONSTCOND*/ 0)
     goto yyerrorlab;
   /* Do not reclaim the symbols of the rule which action triggered
      this YYERROR.  */
   YYPOPSTACK(yylen);
   yylen = 0;
   YY_STACK_PRINT(yyss, yyssp);
   yystate = *yyssp;
   goto yyerrlab1;
   /*-------------------------------------------------------------.
   | yyerrlab1 -- common code for both syntax error and YYERROR.  |
   `-------------------------------------------------------------*/
 yyerrlab1:
   yyerrstatus = 3;  /* Each real token shifted decrements this.  */
   for (;;)
     {
       yyn = yypact[yystate];
       if (yyn != YYPACT_NINF)
         {
           yyn += YYTERROR;
           if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
             {
               yyn = yytable[yyn];
               if (0 < yyn)
                 break;
             }
         }
       /* Pop the current state because it cannot handle the error token.  */
       if (yyssp == yyss)
         YYABORT;
       yydestruct("Error: popping",
                  yystos[yystate], yyvsp);
       YYPOPSTACK(1);
       yystate = *yyssp;
       YY_STACK_PRINT(yyss, yyssp);
     }
   if (yyn == YYFINAL)
     YYACCEPT;
   *++yyvsp = yylval;
   /* Shift the error token.  */
   YY_SYMBOL_PRINT("Shifting", yystos[yyn], yyvsp, yylsp);
   yystate = yyn;
   goto yynewstate;
   /*-------------------------------------.
   | yyacceptlab -- YYACCEPT comes here.  |
   `-------------------------------------*/
 yyacceptlab:
   yyresult = 0;
   goto yyreturn;
   /*-----------------------------------.
   | yyabortlab -- YYABORT comes here.  |
   `-----------------------------------*/
 yyabortlab:
   yyresult = 1;
   goto yyreturn;
 #ifndef yyoverflow
   /*-------------------------------------------------.
   | yyexhaustedlab -- memory exhaustion comes here.  |
   `-------------------------------------------------*/
 yyexhaustedlab:
   yyerror(YY_("memory exhausted"));
   yyresult = 2;
   /* Fall through.  */
 #endif
 yyreturn:
   if (yychar != YYEOF && yychar != YYEMPTY)
     yydestruct("Cleanup: discarding lookahead",
                yytoken, &yylval);
   /* Do not reclaim the symbols of the rule which action triggered
      this YYABORT or YYACCEPT.  */
   YYPOPSTACK(yylen);
   YY_STACK_PRINT(yyss, yyssp);
   while (yyssp != yyss)
     {
       yydestruct("Cleanup: popping",
                  yystos[*yyssp], yyvsp);
       YYPOPSTACK(1);
     }
 #ifndef yyoverflow
   if (yyss != yyssa)
     YYSTACK_FREE(yyss);
 #endif
 #if YYERROR_VERBOSE
   if (yymsg != yymsgbuf)
     YYSTACK_FREE(yymsg);
 #endif
   /* Make sure YYID is used.  */
   return YYID(yyresult);
 }
Member Data Documentation
std::vector< std::string > CChemEqParserBase::mModifierCompartments protected
Definition at line 107 of file CChemEqParser.h.
Referenced by getModifierCompartments().
std::vector< C_FLOAT64 > CChemEqParserBase::mModifierMult protected
Definition at line 106 of file CChemEqParser.h.
Referenced by getModifierMulitplicities().
std::vector< std::string > CChemEqParserBase::mModifierNames protected
Definition at line 105 of file CChemEqParser.h.
Referenced by getModifierNames().
Data* CChemEqParserBase::mpData protected
Definition at line 92 of file CChemEqParser.h.
unsigned C_INT32 CChemEqParserBase::mPosition protected
Definition at line 94 of file CChemEqParser.h.
std::vector< std::string > CChemEqParserBase::mProductCompartments protected
Definition at line 103 of file CChemEqParser.h.
Referenced by getProductCompartments().
std::vector< C_FLOAT64 > CChemEqParserBase::mProductMult protected
Definition at line 102 of file CChemEqParser.h.
Referenced by getProductMulitplicities().
std::vector< std::string > CChemEqParserBase::mProductNames protected
Definition at line 101 of file CChemEqParser.h.
Referenced by getProductNames().
bool CChemEqParserBase::mReversibility protected
Definition at line 95 of file CChemEqParser.h.
Referenced by isReversible().
std::vector< std::string > CChemEqParserBase::mSubstrateCompartments protected
Definition at line 99 of file CChemEqParser.h.
Referenced by getSubstrateCompartments().
std::vector< C_FLOAT64 > CChemEqParserBase::mSubstrateMult protected
Definition at line 98 of file CChemEqParser.h.
Referenced by getSubstrateMulitplicities().
std::vector< std::string > CChemEqParserBase::mSubstrateNames protected
Definition at line 97 of file CChemEqParser.h.
Referenced by getSubstrateNames().
The documentation for this class was generated from the following files:
CChemEqParser.h
CChemEqParser.cpp
CChemEqParser_yacc.cpp