COPASI API: CMiaseTask Class Reference
CMiaseTask Class Reference
#include <CMiaseTask.h>
Public Member Functions
void addMeasurement (CMiaseMeasurementData *measurement)
CMiaseTask ()
CMiaseMeasurementData * getLastMeasurement ()
CMiaseMeasurementData * getMeasurement (int num)
std::string getModelReference ()
int getNumberOfMeasurements ()
std::string getSimulationReference ()
void setModelReference (std::string model)
void setSimulationReference (std::string simulation)
~CMiaseTask ()
Public Member Functions inherited from CMiaseBaseEnhanced
CMiaseBaseEnhanced ()
std::string getId ()
std::string getName ()
void setId (std::string id)
void setName (std::string name)
~CMiaseBaseEnhanced ()
Public Member Functions inherited from CMiaseBase
void addAnnotation (CMiaseAnnotation *ann)
void addNotes (CMiaseNotes *notes)
CMiaseBase ()
CMiaseAnnotation * getAnnotation ()
std::string getMetaId ()
CMiaseNotes * getNotes ()
void setAnyNote (std::string anyAnnotation)
void setMetaId (std::string metaId)
void setXmlNs (std::string xmlNs)
~CMiaseBase ()
Private Attributes
std::vector
< CMiaseMeasurementData * > mListOfMeasurements
std::string mModelReference
std::string mSimulationReference
Detailed Description
Definition at line 42 of file CMiaseTask.h.
Constructor & Destructor Documentation
CMiaseTask::CMiaseTask ()
Definition at line 44 of file CMiaseTask.cpp.
                        : CMiaseBaseEnhanced()
 {}
CMiaseTask::~CMiaseTask ()
Definition at line 47 of file CMiaseTask.cpp.
 {
   //TODO:
   //delete content of following vector:  mListOfMeasurements
 }
Member Function Documentation
void CMiaseTask::addMeasurement (CMiaseMeasurementData * measurement)
Definition at line 53 of file CMiaseTask.cpp.
References mListOfMeasurements.
Referenced by CMiaseParser::newMeasurementData().
 {
   mListOfMeasurements.push_back(measurement);
 }
CMiaseMeasurementData * CMiaseTask::getLastMeasurement ()
Definition at line 68 of file CMiaseTask.cpp.
References mListOfMeasurements.
Referenced by CMiaseParser::getLastObj(), CMiaseParser::newAnnotation(), CMiaseParser::newMeasurementData(), and CMiaseParser::newNotes().
 {
   return mListOfMeasurements[ mListOfMeasurements.size() - 1];
 }
CMiaseMeasurementData * CMiaseTask::getMeasurement (int num)
Definition at line 58 of file CMiaseTask.cpp.
References mListOfMeasurements.
Referenced by CMiaseParser::testDataStructure().
 {
   return mListOfMeasurements[ num ];
 }
std::string CMiaseTask::getModelReference ()
Definition at line 83 of file CMiaseTask.cpp.
References mModelReference.
 {
   mModelReference;
 }
int CMiaseTask::getNumberOfMeasurements ()
Definition at line 63 of file CMiaseTask.cpp.
References mListOfMeasurements.
Referenced by CMiaseParser::testDataStructure().
 {
   return mListOfMeasurements.size();
 }
std::string CMiaseTask::getSimulationReference ()
Definition at line 88 of file CMiaseTask.cpp.
References mSimulationReference.
 {
   mSimulationReference;
 }
void CMiaseTask::setModelReference (std::string model)
Definition at line 73 of file CMiaseTask.cpp.
References mModelReference.
Referenced by CMiaseParser::newTask().
 {
   mModelReference = model;
 }
void CMiaseTask::setSimulationReference (std::string simulation)
Definition at line 78 of file CMiaseTask.cpp.
References mSimulationReference.
Referenced by CMiaseParser::newTask().
 {
   mSimulationReference = simulation;
 }
Member Data Documentation
std::vector< CMiaseMeasurementData* > CMiaseTask::mListOfMeasurements private
Definition at line 70 of file CMiaseTask.h.
Referenced by addMeasurement(), getLastMeasurement(), getMeasurement(), and getNumberOfMeasurements().
std::string CMiaseTask::mModelReference private
Definition at line 67 of file CMiaseTask.h.
Referenced by getModelReference(), and setModelReference().
std::string CMiaseTask::mSimulationReference private
Definition at line 68 of file CMiaseTask.h.
Referenced by getSimulationReference(), and setSimulationReference().
The documentation for this class was generated from the following files:
CMiaseTask.h
CMiaseTask.cpp