COPASI API: CLCurve Class Reference
CLCurve Class Reference
#include <CLCurve.h>
Public Member Functions
void addCurveSegment (const CLLineSegment &ls)
void addCurveSegment (const CLLineSegment *pLs)
CLBoundingBox calculateBoundingBox () const
CLCurve ()
CLCurve (const CLCurve &c)
CLCurve (const Curve &sbmlcurve)
void clear ()
void exportToSBML (Curve *c, const std::map< const CCopasiObject *, SBase * > &copasimodelmap) const
const std::vector
< CLLineSegment > & getCurveSegments () const
std::vector< CLPoint > getListOfPoints () const
size_t getNumCurveSegments () const
const CLLineSegment * getSegmentAt (size_t i) const
CLLineSegment * getSegmentAt (size_t i)
bool isContinuous () const
virtual void moveBy (const CLPoint &p)
bool operator== (const CLCurve &rhs) const
void scale (const double &scaleFactor)
~CLCurve ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
std::vector< CLLineSegment > mvCurveSegments
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLCurve &c)
Detailed Description
Definition at line 131 of file CLCurve.h.
Constructor & Destructor Documentation
CLCurve::CLCurve () inline
Definition at line 139 of file CLCurve.h.
     : CLBase(), mvCurveSegments() {};
CLCurve::CLCurve (const CLCurve & c)
copy constructor (should make deep copy)
Definition at line 74 of file CLCurve.cpp.
   : CLBase(c),
     mvCurveSegments(c.mvCurveSegments)
 {}
CLCurve::CLCurve (const Curve & sbmlcurve)
constructor from libsbml object
Definition at line 79 of file CLCurve.cpp.
References C_INT32, and mvCurveSegments.
   : CLBase(sbmlcurve),
     mvCurveSegments()
 {
   //TODO
   C_INT32 i, imax = sbmlcurve.getListOfCurveSegments()->size();
   for (i = 0; i < imax; ++i)
     {
       const LineSegment* tmp
         = dynamic_cast<const LineSegment*>(sbmlcurve.getListOfCurveSegments()->get(i));
       if (tmp)
         mvCurveSegments.push_back(CLLineSegment(*tmp));
       //addCurveSegment(CLLineSegment(*tmp));
     }
 }
CLCurve::~CLCurve ()
Definition at line 98 of file CLCurve.cpp.
 {}
Member Function Documentation
void CLCurve::addCurveSegment (const CLLineSegment & ls)
add a copy of the line segment to the curve
Definition at line 101 of file CLCurve.cpp.
References mvCurveSegments.
Referenced by CCopasiXMLParser::CurveElement::end(), CCopasiSpringLayout::finalizeState(), and CLLayoutRenderer::revert_curve().
 {
   mvCurveSegments.push_back(ls);
 }
void CLCurve::addCurveSegment (const CLLineSegment * pLs)
add a copy of the line segment to the curve
Definition at line 106 of file CLCurve.cpp.
References mvCurveSegments.
 {
   if (pLs)
     mvCurveSegments.push_back(*pLs);
 }
CLBoundingBox CLCurve::calculateBoundingBox () const
Calculates the bounding box for the curve. Basepoints for cubic beziers are considered to belong inside the bounding box.
Definition at line 218 of file CLCurve.cpp.
References CLLineSegment::getBase1(), CLLineSegment::getBase2(), CLLineSegment::getEnd(), getNumCurveSegments(), getSegmentAt(), CLLineSegment::getStart(), CLPoint::getX(), CLPoint::getY(), CLLineSegment::isBezier(), and max.
Referenced by CLayout::calculateBoundingBox().
 {
   double xMin = std::numeric_limits<double>::max();
   double yMin = xMin;
   double xMax = -xMin;
   double yMax = -xMin;
   double x, y;
   size_t i, iMax = this->getNumCurveSegments();
   const CLLineSegment* pLS = NULL;
   const CLPoint* pP = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pLS = this->getSegmentAt(i);
       pP = &pLS->getStart();
       x = pP->getX();
       y = pP->getY();
       xMin = (xMin < x) ? xMin : x;
       yMin = (yMin < y) ? yMin : y;
       xMax = (xMax > x) ? xMax : x;
       yMax = (yMax > y) ? yMax : y;
       pP = &pLS->getEnd();
       x = pP->getX();
       y = pP->getY();
       xMin = (xMin < x) ? xMin : x;
       yMin = (yMin < y) ? yMin : y;
       xMax = (xMax > x) ? xMax : x;
       yMax = (yMax > y) ? yMax : y;
       if (pLS->isBezier())
         {
           pP = &pLS->getBase1();
           x = pP->getX();
           y = pP->getY();
           xMin = (xMin < x) ? xMin : x;
           yMin = (yMin < y) ? yMin : y;
           xMax = (xMax > x) ? xMax : x;
           yMax = (yMax > y) ? yMax : y;
           pP = &pLS->getBase2();
           x = pP->getX();
           y = pP->getY();
           xMin = (xMin < x) ? xMin : x;
           yMin = (yMin < y) ? yMin : y;
           xMax = (xMax > x) ? xMax : x;
           yMax = (yMax > y) ? yMax : y;
         }
     }
   return CLBoundingBox(CLPoint(xMin, yMin), CLDimensions(xMax - xMin, yMax - yMin));
 }
void CLCurve::clear ()
Definition at line 112 of file CLCurve.cpp.
References mvCurveSegments.
Referenced by CCopasiSpringLayout::finalizeState(), and CCopasiXMLParser::CurveElement::start().
 {
   mvCurveSegments.clear();
 }
void CLCurve::exportToSBML (Curve * c, const std::map< const CCopasiObject *, SBase * > & copasimodelmap) const
This method writes the information of the copasi layout object into the corresponding sbml object
Definition at line 148 of file CLCurve.cpp.
References mvCurveSegments.
Referenced by CLMetabReferenceGlyph::exportToSBML(), CLGeneralGlyph::exportToSBML(), and CLReactionGlyph::exportToSBML().
 {
   if (!c) return;
   //we will reconstruct the curve completely without checking the existing curve
   size_t i, imax = c->getListOfCurveSegments()->size();
   for (i = 0; i < imax; ++i) delete c->getListOfCurveSegments()->remove(0);
   //curve segments
   imax = mvCurveSegments.size();
   for (i = 0; i < imax; ++i)
     {
       if (mvCurveSegments[i].isBezier())
         {
           mvCurveSegments[i].exportToSBMLBezier(c->createCubicBezier(), copasimodelmap);
         }
       else
         {
           mvCurveSegments[i].exportToSBMLLineSegment(c->createLineSegment(), copasimodelmap);
         }
     }
 }
const std::vector<CLLineSegment>& CLCurve::getCurveSegments () const inline
Definition at line 154 of file CLCurve.h.
References mvCurveSegments.
Referenced by CCopasiSpringLayout::addReactionVariables(), CQGLNetworkPainter::createGraph(), CQGLNetworkPainter::drawEdge(), operator<<(), and CCopasiXML::saveCurve().
 {return mvCurveSegments;};
std::vector< CLPoint > CLCurve::getListOfPoints () const
This method should only be called if isContinuous() is true. It returns the curve as a list of points rather than a list of line segments.
Definition at line 130 of file CLCurve.cpp.
References isContinuous(), and mvCurveSegments.
Referenced by CQGLNetworkPainter::checkCurve(), and fillItemFromCurve().
 {
   std::vector <CLPoint> ret;
   if (mvCurveSegments.size() == 0) return ret;
   if (!isContinuous()) return ret;
   size_t i, imax = mvCurveSegments.size();
   for (i = 0; i < imax; ++i)
     ret.push_back(mvCurveSegments[i].getStart());
   ret.push_back(mvCurveSegments[i - 1].getEnd());
   return ret;
 }
size_t CLCurve::getNumCurveSegments () const inline
Definition at line 168 of file CLCurve.h.
References mvCurveSegments.
Referenced by CQLayoutScene::addGlyph(), CCopasiSpringLayout::addReactionVariables(), CLayout::calculateBoundingBox(), calculateBoundingBox(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_layout(), CQGLNetworkPainter::drawEdge(), fillItemFromCurve(), CCopasiSpringLayout::finalizeState(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CQConnectionGraphicsItem::getPath(), CLLayoutRenderer::is_curve_visible(), CQGLLayoutPainter::mouseMoveEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_selection(), CLLayoutRenderer::move_species_reference_glyph(), moveBy(), compareGraphicalObjectsBySize::operator()(), operator<<(), CLLayoutRenderer::revert_curve(), CCopasiXML::saveCurve(), CCopasiXML::saveLayoutList(), CQGLNetworkPainter::setNodeSize(), CLLayoutRenderer::update_associations(), CQGLLayoutPainter::update_status_and_cursor(), and CLLayoutRenderer::update_textures_and_colors().
 {return mvCurveSegments.size();};
const CLLineSegment* CLCurve::getSegmentAt (size_t i) const inline
Definition at line 156 of file CLCurve.h.
References mvCurveSegments.
Referenced by calculateBoundingBox(), CLLayoutRenderer::draw_curve(), fillItemFromCurve(), CLLayoutRenderer::getCurveBoundingBox(), CLLayoutRenderer::getObjectsAt(), CQConnectionGraphicsItem::getPath(), CLLayoutRenderer::is_curve_visible(), CQGLLayoutPainter::mouseMoveEvent(), CLLayoutRenderer::move_curve_object(), moveBy(), CLLayoutRenderer::revert_curve(), CQGLNetworkPainter::setNodeSize(), CLLayoutRenderer::update_associations(), and CQGLLayoutPainter::update_status_and_cursor().
   {
     if (i < mvCurveSegments.size())return &(mvCurveSegments[i]);
     else return NULL;
   }
CLLineSegment* CLCurve::getSegmentAt (size_t i) inline
Definition at line 162 of file CLCurve.h.
References mvCurveSegments.
   {
     if (i < mvCurveSegments.size())return &(mvCurveSegments[i]);
     else return NULL;
   }
bool CLCurve::isContinuous () const
this method tells whether the curve is a continuous set of line segments, i.e. if the end point of one line segment is identical to the starting point of the following one.
Definition at line 117 of file CLCurve.cpp.
References mvCurveSegments.
Referenced by fillItemFromCurve(), and getListOfPoints().
 {
   if (mvCurveSegments.size() <= 1) return true;
   size_t i, imax = mvCurveSegments.size() - 1;
   for (i = 0; i < imax; ++i)
     if (!(mvCurveSegments[i].getEnd() == mvCurveSegments[i + 1].getStart()))
       return false;
   return true;
 }
void CLCurve::moveBy (const CLPoint & p) virtual
Reimplemented from CLBase.
Definition at line 187 of file CLCurve.cpp.
References CLLineSegment::getBase1(), CLLineSegment::getBase2(), CLLineSegment::getEnd(), getNumCurveSegments(), getSegmentAt(), CLLineSegment::getStart(), CLLineSegment::isBezier(), and CLPoint::moveBy().
Referenced by CLGlyphWithCurve::moveBy().
 {
   CLLineSegment* pLS = NULL;
   CLPoint* pP = NULL;
   size_t i, iMax = this->getNumCurveSegments();
   for (i = 0; i < iMax; ++i)
     {
       pLS = this->getSegmentAt(i);
       pP = &pLS->getStart();
       pP->moveBy(p);
       pP = &pLS->getEnd();
       pP->moveBy(p);
       if (pLS->isBezier())
         {
           pP = &pLS->getBase1();
           pP->moveBy(p);
           pP = &pLS->getBase2();
           pP->moveBy(p);
         }
     }
 }
bool CLCurve::operator== (const CLCurve & rhs) const inline
Two curves are supposed to be equal iff all there line segments including their order are equal
Definition at line 201 of file CLCurve.h.
References mvCurveSegments.
   {
     bool result = true;
     unsigned int i;
     for (i = 0; i < mvCurveSegments.size(); i++)
       {
         result = result && (mvCurveSegments[i] == rhs.mvCurveSegments[i]);
       }
     return result;
   }
void CLCurve::scale (const double & scaleFactor) inline
Definition at line 214 of file CLCurve.h.
References mvCurveSegments.
   {
     unsigned int i; // scale all segments
     for (i = 0; i < mvCurveSegments.size(); i++)
       {
         mvCurveSegments[i].scale(scaleFactor);
       }
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLCurve & c) friend
insert operator
Definition at line 173 of file CLCurve.cpp.
 {
   if (c.getNumCurveSegments())
     {
       os << "      Curve:\n";
       size_t i, imax = c.getNumCurveSegments();
       for (i = 0; i < imax; ++i)
         os << "        " << c.getCurveSegments()[i] << "\n";
     }
   return os;
 }
Member Data Documentation
std::vector<CLLineSegment> CLCurve::mvCurveSegments protected
Definition at line 135 of file CLCurve.h.
Referenced by addCurveSegment(), CLCurve(), clear(), exportToSBML(), getCurveSegments(), getListOfPoints(), getNumCurveSegments(), getSegmentAt(), CGraphCurve::invertOrderOfPoints(), isContinuous(), operator==(), CGraphCurve::scale(), and scale().
The documentation for this class was generated from the following files:
CLCurve.h
CLCurve.cpp