COPASI API: CCopasiXMLParser::TextElement Class Reference
CCopasiXMLParser::TextElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
TextElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual ~TextElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { RenderText = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4196 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::TextElement::Element private
Enumerator
RenderText
Definition at line 4203 of file CCopasiXMLParser.h.
     {
       RenderText = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::TextElement::TextElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 12291 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::TextElement::~TextElement () virtual
Destructor
Definition at line 12296 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::TextElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 12460 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pText, CLText::setText(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   std::string text;
   switch (mCurrentElement)
     {
       case RenderText:
         if (strcmp(pszName, "Text"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Text", mParser.getCurrentLineNumber());
         text = mParser.getCharacterData("\x0a\x0d\t ", "");
         assert(mCommon.pText != NULL);
         mCommon.pText->setText(text);
         mCommon.pText = NULL;
         mParser.popElementHandler();
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::TextElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 12301 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_START, CLText::ANCHOR_TOP, CCopasiMessage::EXCEPTION, CLGroup::getElement(), CLGroup::getNumElements(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive1D::parseDashArray(), CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, SCopasiXMLParserCommon::pText, CLText::setCoordinates(), CLText::setFontFamily(), CLText::setFontSize(), CLText::setFontStyle(), CLText::setFontWeight(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), CLText::setTextAnchor(), CLText::setVTextAnchor(), strToDouble(), CLText::STYLE_ITALIC, CLText::STYLE_NORMAL, UNKNOWN_ELEMENT, CLText::WEIGHT_BOLD, and CLText::WEIGHT_NORMAL.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * Stroke;
   const char * StrokeWidth;
   const char * StrokeDashArray;
   const char * X;
   const char * Y;
   const char * Z;
   const char * FontFamily;
   const char * FontSize;
   const char * FontWeight;
   const char * FontStyle;
   const char * TextAnchor;
   const char * VTextAnchor;
   CLText* pText = NULL;
   switch (mCurrentElement)
     {
       case RenderText:
         if (strcmp(pszName, "Text"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Text", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         Stroke = mParser.getAttributeValue("stroke", papszAttrs, false);
         StrokeWidth = mParser.getAttributeValue("stroke-width", papszAttrs, false);
         StrokeDashArray = mParser.getAttributeValue("stroke-dasharray", papszAttrs, false);
         X = mParser.getAttributeValue("x", papszAttrs);
         Y = mParser.getAttributeValue("y", papszAttrs);
         Z = mParser.getAttributeValue("z", papszAttrs, "0.0");
         FontFamily = mParser.getAttributeValue("font-family", papszAttrs, false);
         FontSize = mParser.getAttributeValue("font-size", papszAttrs, false);
         FontWeight = mParser.getAttributeValue("font-weight", papszAttrs, false);
         FontStyle = mParser.getAttributeValue("font-style", papszAttrs, false);
         TextAnchor = mParser.getAttributeValue("text-anchor", papszAttrs, false);
         VTextAnchor = mParser.getAttributeValue("vtext-anchor", papszAttrs, false);
         pText = new CLText(NULL);
         if (Transform != NULL)
           {
             pText->parseTransformation(Transform);
           }
         if (Stroke != NULL)
           {
             pText->setStroke(Stroke);
           }
         if (StrokeWidth != NULL)
           {
             double width = strToDouble(StrokeWidth, NULL);
             pText->setStrokeWidth(width);
           }
         if (StrokeDashArray != NULL)
           {
             pText->parseDashArray(StrokeDashArray);
           }
         pText->setCoordinates(CLRelAbsVector(X), CLRelAbsVector(Y), CLRelAbsVector(Z));
         if (FontFamily != NULL)
           {
             pText->setFontFamily(FontFamily);
           }
         if (FontSize != NULL)
           {
             pText->setFontSize(CLRelAbsVector(FontSize));
           }
         if (FontStyle != NULL)
           {
             std::string s(FontStyle);
             if (s == "normal")
               {
                 pText->setFontStyle(CLText::STYLE_NORMAL);
               }
             else if (s == "italic")
               {
                 pText->setFontStyle(CLText::STYLE_ITALIC);
               }
           }
         if (FontWeight != NULL)
           {
             std::string s(FontWeight);
             if (s == "normal")
               {
                 pText->setFontWeight(CLText::WEIGHT_NORMAL);
               }
             else if (s == "bold")
               {
                 pText->setFontWeight(CLText::WEIGHT_BOLD);
               }
           }
         if (TextAnchor != NULL)
           {
             std::string s(TextAnchor);
             if (s == "start")
               {
                 pText->setTextAnchor(CLText::ANCHOR_START);
               }
             else if (s == "middle")
               {
                 pText->setTextAnchor(CLText::ANCHOR_MIDDLE);
               }
             else if (s == "end")
               {
                 pText->setTextAnchor(CLText::ANCHOR_END);
               }
           }
         if (VTextAnchor != NULL)
           {
             std::string s(VTextAnchor);
             if (s == "top")
               {
                 pText->setVTextAnchor(CLText::ANCHOR_TOP);
               }
             else if (s == "middle")
               {
                 pText->setVTextAnchor(CLText::ANCHOR_MIDDLE);
               }
             else if (s == "bottom")
               {
                 pText->setVTextAnchor(CLText::ANCHOR_BOTTOM);
               }
           }
         mCommon.pGroup->addChildElement(pText);
         // delete the text element again since the add method made a copy
         delete pText;
         mCommon.pText = dynamic_cast<CLText*>(mCommon.pGroup->getElement(mCommon.pGroup->getNumElements() - 1));
         assert(mCommon.pText != NULL);
         mParser.enableCharacterDataHandler();
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp