COPASI API: CXMLAttributeList Class Reference
CXMLAttributeList Class Reference
#include <CCopasiXMLInterface.h>
Public Member Functions
template<class CType >
bool add (const std::string &name, const CType &value)
bool add (const std::string &name, const C_FLOAT64 &value)
template<class CType >
bool add (const std::string &name, const CType &value, const CCopasiXMLInterface::EncodingType &encodingType)
CXMLAttributeList ()
CXMLAttributeList (const CXMLAttributeList &src)
bool erase ()
std::string getAttribute (const size_t &index) const
const std::string & getName (const size_t &index) const
const std::string & getValue (const size_t &index) const
template<class CType >
bool set (const size_t &index, const std::string &name, const CType &value)
template<class CType >
bool set (const size_t &index, const std::string &name, const CType &value, const CCopasiXMLInterface::EncodingType &encodingType)
bool setName (const size_t &index, const std::string &name)
template<class CType >
bool setValue (const size_t &index, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value, const CCopasiXMLInterface::EncodingType &encodingType)
size_t size ()
bool skip (const size_t &index)
~CXMLAttributeList ()
Private Attributes
std::vector< std::string > mAttributeList
std::vector< bool > mSaveList
Friends
std::ostream & operator<< (std::ostream &os, const CXMLAttributeList &attr)
Detailed Description
A list of XML attributes used by saveElement and startSaveElement.
Definition at line 276 of file CCopasiXMLInterface.h.
Constructor & Destructor Documentation
CXMLAttributeList::CXMLAttributeList ()
Constructor.
Definition at line 502 of file CCopasiXMLInterface.cpp.
                                     :
   mAttributeList(),
   mSaveList()
 {}
CXMLAttributeList::CXMLAttributeList (const CXMLAttributeList & src)
Copy constructor.
Parameters
const CXMLAttributeList & src
Definition at line 507 of file CCopasiXMLInterface.cpp.
                                                                  :
   mAttributeList(src.mAttributeList),
   mSaveList(src.mSaveList)
 {}
CXMLAttributeList::~CXMLAttributeList ()
Destructor.
Definition at line 512 of file CCopasiXMLInterface.cpp.
 {}
Member Function Documentation
template<class CType > bool CXMLAttributeList::add (const std::string & name, const CType & value) inline
Add an attribute to the end of the list. Note: the value will be XML encoded
Parameters
const std::string & name
const CType & value
Returns
bool success
Definition at line 321 of file CCopasiXMLInterface.h.
References CCopasiXMLInterface::attribute.
Referenced by add(), CCopasiXML::save(), CCopasiXML::save1DAttributes(), CCopasiXML::save2DAttributes(), CCopasiXML::saveAnnotation(), CCopasiXML::saveArrowHeadAttributes(), CCopasiXML::saveColorDefinition(), CCopasiXML::saveCurve(), CCopasiXML::saveDimensions(), CCopasiXML::saveEllipseElement(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGradientAttributes(), CCopasiXML::saveGradientStop(), CCopasiXML::saveGUI(), CCopasiXML::saveImageElement(), CCopasiXML::saveLayoutList(), CCopasiXML::saveLinearGradient(), CCopasiXML::saveLineEnding(), CCopasiXML::saveLocalStyle(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), CCopasiXMLInterface::saveParameter(), CCopasiXML::savePlotList(), CCopasiXML::savePosition(), CCopasiXML::saveRadialGradient(), CCopasiXML::saveRectangleElement(), CCopasiXML::saveRenderInformationAttributes(), CCopasiXML::saveRenderPoint(), CCopasiXML::saveRenderTextElement(), CCopasiXML::saveReportList(), CCopasiXML::saveReportSection(), CCopasiXML::saveSBMLReference(), CCopasiXML::saveStyleAttributes(), CCopasiXML::saveTaskList(), CCopasiXML::saveTextAttributes(), and CCopasiXML::saveTransformationAttributes().
   {return add(name, value, CCopasiXMLInterface::attribute);}
bool CXMLAttributeList::add (const std::string & name, const C_FLOAT64 & value)
Add an attribute to the end of the list. Note: the value will be XML encoded
Parameters
const std::string & name
const C_FLOAT64 & value
Returns
bool success
Definition at line 524 of file CCopasiXMLInterface.cpp.
References add(), and CCopasiXMLInterface::attribute.
 {
   return add(name,
              (CCopasiXMLInterface::DBL) value,
              CCopasiXMLInterface::attribute);
 }
template<class CType > bool CXMLAttributeList::add (const std::string & name, const CType & value, const CCopasiXMLInterface::EncodingType & encodingType) inline
Add an attribute to the end of the list. Note: the value will be XML encoded
Parameters
const std::string & name
const CType & value
const CCopasiXMLInterface::EncodingType & encodingType
Returns
bool success
Definition at line 342 of file CCopasiXMLInterface.h.
References CCopasiXMLInterface::encode(), mAttributeList, and mSaveList.
   {
     std::ostringstream Value;
     try
       {
         Value << value;
       }
     catch (...)
       {
         Value << "";
       }
     mAttributeList.push_back(name);
     mAttributeList.push_back(CCopasiXMLInterface::encode(Value.str(),
                              encodingType));
     mSaveList.push_back(true);
     return true;
   }
bool CXMLAttributeList::erase ()
Erase the content of the attribute list.
Returns
bool success
Definition at line 514 of file CCopasiXMLInterface.cpp.
References mAttributeList, and mSaveList.
Referenced by CCopasiXML::saveCurve(), CCopasiXML::saveDimensions(), CCopasiXML::saveFunctionList(), CCopasiXML::saveLayoutList(), CCopasiXML::saveModel(), CCopasiXML::savePlotList(), CCopasiXML::savePosition(), CCopasiXML::saveReportList(), CCopasiXML::saveSBMLReference(), and CCopasiXML::saveTaskList().
 {
   mAttributeList.clear();
   mSaveList.clear();
   return true;
 }
std::string CXMLAttributeList::getAttribute (const size_t & index) const
Retrieve the indexed attribute (' name="value"' or '' if skipped).
Parameters
const size_t & index
Returns
std::string attribute
Definition at line 550 of file CCopasiXMLInterface.cpp.
References mAttributeList, and mSaveList.
 {
   if (mSaveList[index])
     return " " + mAttributeList[2 * index] + "=\"" + mAttributeList[2 * index + 1] + "\"";
   else
     return "";
 }
const std::string & CXMLAttributeList::getName (const size_t & index) const
Retrieve the name of the indexed attribute.
Parameters
const size_t & index
Returns
const std::string & name
Definition at line 538 of file CCopasiXMLInterface.cpp.
References mAttributeList.
 {return mAttributeList[2 * index];}
const std::string & CXMLAttributeList::getValue (const size_t & index) const
Retrieve the value of the indexed attribute.
Parameters
const size_t & index
Returns
const std::string & value
Definition at line 541 of file CCopasiXMLInterface.cpp.
References mAttributeList.
 {return mAttributeList[2 * index + 1];}
template<class CType > bool CXMLAttributeList::set (const size_t & index, const std::string & name, const CType & value) inline
Set the name and value of the indexed attribute Note: the value will be XML encoded
Parameters
const size_t & index
const std::string & name
const CType & value
Returns
bool success
Definition at line 397 of file CCopasiXMLInterface.h.
References CCopasiXMLInterface::attribute.
Referenced by CCopasiXML::saveReportSection().
   {return set(index, name, value, CCopasiXMLInterface::attribute);}
template<class CType > bool CXMLAttributeList::set (const size_t & index, const std::string & name, const CType & value, const CCopasiXMLInterface::EncodingType & encodingType) inline
Set the name and value of the indexed attribute Note: the value will be XML encoded
Parameters
const size_t & index
const std::string & name
const CType & value
const CCopasiXMLInterface::EncodingType & encodingType
Returns
bool success
Definition at line 410 of file CCopasiXMLInterface.h.
References CCopasiXMLInterface::encode(), mAttributeList, and mSaveList.
   {
     mAttributeList[2 * index] = name;
     std::ostringstream Value;
     try
       {
         Value << value;
       }
     catch (...)
       {
         Value << "";
       }
     mAttributeList[2 * index + 1] =
       CCopasiXMLInterface::encode(Value.str(),
                                   encodingType);
     mSaveList[index] = true;
     return true;
   }
bool CXMLAttributeList::setName (const size_t & index, const std::string & name)
Set the name of the indexed attribute
Parameters
const size_t & index
const std::string & name
Returns
bool success
Definition at line 531 of file CCopasiXMLInterface.cpp.
References mAttributeList.
 {
   mAttributeList[2 * index] = name;
   return true;
 }
template<class CType > bool CXMLAttributeList::setValue (const size_t & index, const CType & value) inline
Set the value of the indexed attribute Note: the value will be XML encoded
Parameters
const size_t & index
const CType & value
Returns
bool success
Definition at line 444 of file CCopasiXMLInterface.h.
References CCopasiXMLInterface::attribute.
Referenced by CCopasiXML::saveAnnotation(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGUI(), CCopasiXML::saveModel(), CCopasiXML::saveReportList(), and CCopasiXML::saveSBMLReference().
   {return setValue(index, value, CCopasiXMLInterface::attribute);}
template<class CType > bool CXMLAttributeList::setValue (const size_t & index, const CType & value, const CCopasiXMLInterface::EncodingType & encodingType) inline
Set the value of the indexed attribute Note: the value will be XML encoded
Parameters
const size_t & index
const CType & value
const CCopasiXMLInterface::EncodingType & encodingType
Returns
bool success
Definition at line 456 of file CCopasiXMLInterface.h.
References CCopasiXMLInterface::encode(), mAttributeList, and mSaveList.
   {
     std::ostringstream Value;
     try
       {
         Value << value;
       }
     catch (...)
       {
         Value << "";
       }
     mAttributeList[2 * index + 1] =
       CCopasiXMLInterface::encode(Value.str(),
                                   encodingType);
     mSaveList[index] = true;
     return true;
   }
size_t CXMLAttributeList::size ()
Retrieve the size of the list.
Returns
size_t size
Definition at line 522 of file CCopasiXMLInterface.cpp.
References mAttributeList.
 {return mAttributeList.size() / 2;}
bool CXMLAttributeList::skip (const size_t & index)
Set whether the indexed attribute shall be skipped during save.
Parameters
const size_t & index
Returns
bool success
Definition at line 544 of file CCopasiXMLInterface.cpp.
References mSaveList.
Referenced by CCopasiXML::saveModel(), and CCopasiXMLInterface::saveParameter().
 {
   mSaveList[index] = false;
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CXMLAttributeList & attr) friend
Definition at line 558 of file CCopasiXMLInterface.cpp.
 {
   std::vector< std::string >::const_iterator itAttr = attr.mAttributeList.begin();
   std::vector< bool >::const_iterator itSave = attr.mSaveList.begin();
   std::vector< bool >::const_iterator endSave = attr.mSaveList.end();
   for (; itSave != endSave; ++itSave)
     if (*itSave)
       {
         os << " " << *itAttr++;
         os << "=\"" << *itAttr++ << "\"";
       }
     else
       itAttr += 2;
   return os;
 }
Member Data Documentation
std::vector< std::string > CXMLAttributeList::mAttributeList private
The attribute list.
Definition at line 283 of file CCopasiXMLInterface.h.
Referenced by add(), erase(), getAttribute(), getName(), getValue(), operator<<(), set(), setName(), setValue(), and size().
std::vector< bool > CXMLAttributeList::mSaveList private
The list whether an attribute is to be saved.
Definition at line 288 of file CCopasiXMLInterface.h.
Referenced by add(), erase(), getAttribute(), operator<<(), set(), setValue(), and skip().
The documentation for this class was generated from the following files:
CCopasiXMLInterface.h
CCopasiXMLInterface.cpp