COPASI API: CCopasiTask.cpp File Reference
CCopasiTask.cpp File Reference
#include "copasi.h"
#include "CCopasiTask.h"
#include "CCopasiProblem.h"
#include "CCopasiMethod.h"
#include "report/CReport.h"
#include "report/CKeyFactory.h"
#include "utilities/COutputHandler.h"
#include "model/CModel.h"
#include "model/CState.h"
#include "report/CCopasiObjectReference.h"
#include "report/CCopasiTimer.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "copasi/report/CCopasiRootContainer.h"
Functions
std::ostream & operator<< (std::ostream &os, const CCopasiTask::CDescription &o)
std::ostream & operator<< (std::ostream &os, const CCopasiTask::CResult &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiTask::CDescription & o)
Output stream operator
Parameters
ostream & os
const CDescription & A
Returns
ostream & os
Definition at line 411 of file CCopasiTask.cpp.
References CCopasiTask::getMethod(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiTask::getProblem(), CCopasiProblem::print(), and CCopasiMethod::print().
 {
   const CCopasiTask & Task = *static_cast<const CCopasiTask *>(o.getObjectParent());
   os << Task.getObjectName() << " Task" << std::endl << std::endl;
   if (Task.getProblem())
     {
       Task.getProblem()->print(&os);
       os << std::endl;
     }
   else
     os << "No Problem Specified!" << std::endl;
   if (Task.getMethod())
     {
       Task.getMethod()->print(&os);
       os << std::endl;
     }
   else
     os << "No Method Specified!" << std::endl;
   return os;
 }
std::ostream& operator<< (std::ostream & os, const CCopasiTask::CResult & o)
Output stream operator
Parameters
ostream & os
const CResult & A
Returns
ostream & os
Definition at line 451 of file CCopasiTask.cpp.
References CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiTask::getProblem(), and CCopasiProblem::printResult().
 {
   const CCopasiTask & Task = *static_cast<const CCopasiTask *>(o.getObjectParent());
   os << Task.getObjectName() << " Result:" << std::endl << std::endl;
   if (Task.getProblem())
     {
       Task.getProblem()->printResult(&os);
       os << std::endl;
     }
   else
     os << "No Problem Specified!" << std::endl;
   return os;
 }