COPASI API: CQGLViewport Class Reference
CQGLViewport Class Reference
#include <CQGLViewport.h>
Public Slots
void updateWidget ()
Public Member Functions
CQGLViewport (QWidget *pParent=0, Qt::WFlags f=0)
void createGraph (CLayout *lP)
double fitToScreen ()
const CQGLNetworkPainter * getPainter () const
CQGLNetworkPainter * getPainter ()
bool isCircleMode () const
void resetView ()
void setZoomFactor (double zoom)
virtual ~CQGLViewport ()
Protected Slots
void slotHValueChanged (int value)
void slotVValueChanged (int value)
Protected Member Functions
virtual void resizeEvent (QResizeEvent *e)
void updateScrollbars ()
Protected Attributes
QScrollBar * mpHorizontalScrollbar
CQGLNetworkPainter * mpNetworkPainter
QScrollBar * mpVerticalScrollbar
Detailed Description
This class is supposed to act as a sort of scrollview for a CQGLNetworkPainter.
Definition at line 22 of file CQGLViewport.h.
Constructor & Destructor Documentation
CQGLViewport::CQGLViewport (QWidget * pParent = 0, Qt::WFlags f = 0)
Constructor.
Definition at line 31 of file CQGLViewport.cpp.
References mpHorizontalScrollbar, mpNetworkPainter, mpVerticalScrollbar, slotHValueChanged(), slotVValueChanged(), and TRUE.
                                                       :
   QFrame(pParent, f)
   , mpVerticalScrollbar(new QScrollBar(Qt::Vertical, NULL))
   , mpHorizontalScrollbar(new QScrollBar(Qt::Horizontal, NULL))
   , mpNetworkPainter(NULL)
 {
   QVBoxLayout* pVBoxLayout = new QVBoxLayout();
   this->setLayout(pVBoxLayout);
   QFrame* pHBox = new QFrame(this);
   pHBox->setLayout(new QHBoxLayout());
   pVBoxLayout->addWidget(pHBox);
   QGLFormat format;
   format.setDoubleBuffer(TRUE);
   this->mpNetworkPainter = new CQGLNetworkPainter(format, pHBox);
   pHBox->layout()->addWidget(this->mpNetworkPainter);
   pHBox->layout()->addWidget(this->mpVerticalScrollbar);
   this->mpVerticalScrollbar->setSingleStep(1);
   pVBoxLayout->addWidget(this->mpHorizontalScrollbar);
   this->mpHorizontalScrollbar->setSingleStep(1);
   connect(this->mpVerticalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotVValueChanged(int)));
   connect(this->mpHorizontalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotHValueChanged(int)));
 }
CQGLViewport::~CQGLViewport () virtual
Destructor.
Definition at line 57 of file CQGLViewport.cpp.
 {}
Member Function Documentation
void CQGLViewport::createGraph (CLayout * lP)
Pass the layout on to the network painters createGraph and set the scrollbar ranges.
Definition at line 76 of file CQGLViewport.cpp.
References CQGLNetworkPainter::createGraph(), mpNetworkPainter, and updateScrollbars().
Referenced by CQLayoutMainWindow::CQLayoutMainWindow(), CQLayoutMainWindow::loadSBMLFile(), and CQLayoutMainWindow::setLayout().
 {
   this->mpNetworkPainter->createGraph(IP);
   this->updateScrollbars();
 }
double CQGLViewport::fitToScreen ()
Make the diagram fit the screen. Returns the new zoom factor.
Make the diagram fit the screen. Returns the new zoom value.
Definition at line 158 of file CQGLViewport.cpp.
References CQGLNetworkPainter::fitToScreen(), mpNetworkPainter, and updateScrollbars().
Referenced by CQLayoutMainWindow::slotFitToScreen().
 {
   double zoom = this->mpNetworkPainter->fitToScreen();
   this->updateScrollbars();
   return zoom;
 }
const CQGLNetworkPainter * CQGLViewport::getPainter () const
Definition at line 66 of file CQGLViewport.cpp.
References mpNetworkPainter.
Referenced by CQLayoutMainWindow::addItemInAnimation(), CQLayoutMainWindow::backwardAnimation(), CQLayoutMainWindow::forwardAnimation(), CQLayoutMainWindow::getFontSize(), CQLayoutMainWindow::insertValueTable(), CQLayoutMainWindow::loadData(), CQLayoutMainWindow::mapLabelsToCircles(), CQLayoutMainWindow::mapLabelsToRectangles(), CQLayoutMainWindow::pauseAnimation(), CQLayoutMainWindow::removeItemInAnimation(), CQLayoutMainWindow::saveImage(), CQLayoutMainWindow::setColorMode(), CQLayoutMainWindow::setFontSizeForLabels(), CQLayoutMainWindow::setGlobalScaling(), CQLayoutMainWindow::setIndividualScaling(), CQLayoutMainWindow::setMaxValue(), CQLayoutMainWindow::setMinAndMaxValue(), CQLayoutMainWindow::setMinValue(), CQLayoutMainWindow::setSizeMode(), CQLayoutMainWindow::showStep(), CQLayoutMainWindow::startAnimation(), CQLayoutMainWindow::stepForwardAnimation(), and CQLayoutMainWindow::updateValueTable().
 {
   return this->mpNetworkPainter;
 }
CQGLNetworkPainter * CQGLViewport::getPainter ()
Definition at line 71 of file CQGLViewport.cpp.
References mpNetworkPainter.
 {
   return this->mpNetworkPainter;
 }
bool CQGLViewport::isCircleMode () const
Returns whether the layout window is in circle (animation mode) or not. This method only calls the corresponding method in the contained network painter.
Definition at line 170 of file CQGLViewport.cpp.
References CQGLNetworkPainter::isCircleMode(), and mpNetworkPainter.
Referenced by CQLayoutMainWindow::parameterTableValueChanged().
 {
   return this->mpNetworkPainter->isCircleMode();
 }
void CQGLViewport::resetView ()
Definition at line 146 of file CQGLViewport.cpp.
References mpNetworkPainter, CQGLNetworkPainter::resetView(), and updateScrollbars().
Referenced by CQLayoutMainWindow::slotResetView().
 {
   // TODO disconnect the scrollbar listeners
   // so that the display is only redrawn once
   this->mpNetworkPainter->resetView();
   this->updateScrollbars();
 }
void CQGLViewport::resizeEvent (QResizeEvent * e) protected virtual
Definition at line 60 of file CQGLViewport.cpp.
References updateScrollbars().
 {
   this->updateScrollbars();
   QFrame::resizeEvent(e);
 }
void CQGLViewport::setZoomFactor (double zoom)
Sets the zoom factor on the network painter and updates the scrollbars.
Definition at line 82 of file CQGLViewport.cpp.
References mpNetworkPainter, CQGLNetworkPainter::setZoomFactor(), CQGLNetworkPainter::update(), and updateScrollbars().
Referenced by CQLayoutMainWindow::setZoomFactor().
 {
   // TODO make sure the GL window is only redrawn once
   this->mpNetworkPainter->setZoomFactor(zoom);
   this->updateScrollbars();
   this->mpNetworkPainter->update();
 }
void CQGLViewport::slotHValueChanged (int value) protected slot
Definition at line 139 of file CQGLViewport.cpp.
References CQGLNetworkPainter::getGraphMin(), CLPoint::getX(), CQGLNetworkPainter::getZoomFactor(), mpNetworkPainter, and CQGLNetworkPainter::setCurrentPositionX().
Referenced by CQGLViewport().
 {
   CLPoint p = this->mpNetworkPainter->getGraphMin();
   double zoom = this->mpNetworkPainter->getZoomFactor();
   this->mpNetworkPainter->setCurrentPositionX((double)(p.getX() + value / zoom));
 }
void CQGLViewport::slotVValueChanged (int value) protected slot
Definition at line 132 of file CQGLViewport.cpp.
References CQGLNetworkPainter::getGraphMin(), CLPoint::getY(), CQGLNetworkPainter::getZoomFactor(), mpNetworkPainter, and CQGLNetworkPainter::setCurrentPositionY().
Referenced by CQGLViewport().
 {
   CLPoint p = this->mpNetworkPainter->getGraphMin();
   double zoom = this->mpNetworkPainter->getZoomFactor();
   this->mpNetworkPainter->setCurrentPositionY((double)(p.getY() + value / zoom));
 }
void CQGLViewport::updateScrollbars () protected
Definition at line 90 of file CQGLViewport.cpp.
References CQGLNetworkPainter::getGraphMax(), CQGLNetworkPainter::getGraphMin(), CLPoint::getX(), CLPoint::getY(), CQGLNetworkPainter::getZoomFactor(), max, min, mpHorizontalScrollbar, mpNetworkPainter, mpVerticalScrollbar, and CQGLNetworkPainter::update().
Referenced by createGraph(), fitToScreen(), resetView(), resizeEvent(), and setZoomFactor().
 {
   // reset the scollbar range
   // TODO check te setting for the scroll range since there seem to be some
   // error messages
   // disconnect the scrollbar listeners and handle the update so that the GL
   // window is only redrawn once
   double zoom = this->mpNetworkPainter->getZoomFactor();
   CLPoint max = this->mpNetworkPainter->getGraphMax();
   CLPoint min = this->mpNetworkPainter->getGraphMin();
   double graphWidth = (max.getX() - min.getX()) * zoom;
   double graphHeight = (max.getY() - min.getY()) * zoom;
   double rectangleHeight = this->contentsRect().height();
   double rectangleWidth = this->contentsRect().width();
   if (graphHeight < rectangleHeight)
     {
       this->mpVerticalScrollbar->hide();
       this->mpVerticalScrollbar->setValue(0);
     }
   else
     {
       this->mpVerticalScrollbar->setPageStep(rectangleHeight);
       this->mpVerticalScrollbar->setRange(0, (unsigned int)(graphHeight - rectangleHeight));
       this->mpVerticalScrollbar->show();
       this->mpNetworkPainter->update();
     }
   if (graphWidth < rectangleWidth)
     {
       this->mpHorizontalScrollbar->hide();
       this->mpHorizontalScrollbar->setValue(0);
     }
   else
     {
       this->mpHorizontalScrollbar->setPageStep(rectangleWidth);
       this->mpHorizontalScrollbar->setRange(0, (unsigned int)(graphWidth - rectangleWidth));
       this->mpHorizontalScrollbar->show();
       this->mpNetworkPainter->update();
     }
 }
void CQGLViewport::updateWidget () slot
Definition at line 165 of file CQGLViewport.cpp.
References mpNetworkPainter, and CQGLNetworkPainter::update().
Referenced by CQLayoutMainWindow::parameterTableValueChanged().
 {
   this->mpNetworkPainter->update();
 }
Member Data Documentation
QScrollBar* CQGLViewport::mpHorizontalScrollbar protected
Definition at line 28 of file CQGLViewport.h.
Referenced by CQGLViewport(), and updateScrollbars().
CQGLNetworkPainter* CQGLViewport::mpNetworkPainter protected
Definition at line 29 of file CQGLViewport.h.
Referenced by CQGLViewport(), createGraph(), fitToScreen(), getPainter(), isCircleMode(), resetView(), setZoomFactor(), slotHValueChanged(), slotVValueChanged(), updateScrollbars(), and updateWidget().
QScrollBar* CQGLViewport::mpVerticalScrollbar protected
Definition at line 27 of file CQGLViewport.h.
Referenced by CQGLViewport(), and updateScrollbars().
The documentation for this class was generated from the following files:
CQGLViewport.h
CQGLViewport.cpp