COPASI API: CQReportListItem Class Reference
CQReportListItem Class Reference
#include <CQReportListItem.h>
Public Member Functions
CQReportListItem (const std::string &cn)
CQReportListItem (const CCopasiObject *pObject)
const CCopasiObjectName & getCN () const
void refreshText ()
~CQReportListItem ()
Private Attributes
CRegisteredObjectName mCN
Detailed Description
Definition at line 31 of file CQReportListItem.h.
Constructor & Destructor Documentation
CQReportListItem::CQReportListItem (const std::string & cn)
Definition at line 27 of file CQReportListItem.cpp.
References refreshText().
                                                       :
     QListWidgetItem(),
     mCN(cn)
 {
   refreshText();
 }
CQReportListItem::CQReportListItem (const CCopasiObject * pObject)
Definition at line 34 of file CQReportListItem.cpp.
References FROM_UTF8, CCopasiObject::getCN(), CCopasiObject::getObjectDisplayName(), and mCN.
                                                                :
     QListWidgetItem(),
     mCN("")
 {
   if (pObject)
     {
       setText(FROM_UTF8(pObject->getObjectDisplayName()));
       mCN = pObject->getCN();
     }
   else
     {
       setText(QString("Not found"));
       mCN = CCopasiStaticString("NotFound").getCN();
     }
 }
CQReportListItem::~CQReportListItem ()
Definition at line 50 of file CQReportListItem.cpp.
 {}
Member Function Documentation
const CCopasiObjectName & CQReportListItem::getCN () const
Definition at line 52 of file CQReportListItem.cpp.
References mCN.
 {return mCN;};
void CQReportListItem::refreshText ()
Definition at line 54 of file CQReportListItem.cpp.
References FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDisplayName(), and mCN.
Referenced by CQReportListItem().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   const CCopasiObject * pObject = pDataModel->getDataObject(mCN);
   if (pObject)
     setText(FROM_UTF8(pObject->getObjectDisplayName()));
   else
     setText(QString("Not found: ") + FROM_UTF8(mCN));
 }
Member Data Documentation
CRegisteredObjectName CQReportListItem::mCN private
Definition at line 47 of file CQReportListItem.h.
Referenced by CQReportListItem(), getCN(), and refreshText().
The documentation for this class was generated from the following files:
CQReportListItem.h
CQReportListItem.cpp