COPASI API: CCopasiObjectName Class Reference
CCopasiObjectName Class Reference
#include <CCopasiObjectName.h>
Public Member Functions
CCopasiObjectName ()
CCopasiObjectName (const std::string &name)
CCopasiObjectName (const CCopasiObjectName &src)
std::string::size_type findEx (const std::string &toFind, const std::string::size_type &pos=0) const
size_t getElementIndex (const size_t &pos=0) const
std::string getElementName (const size_t &pos, const bool &unescape=true) const
std::string getObjectName () const
std::string getObjectType () const
CCopasiObjectName getPrimary () const
CCopasiObjectName getRemainder () const
~CCopasiObjectName ()
Static Public Member Functions
static std::string escape (const std::string &name)
static std::string unescape (const std::string &name)
Detailed Description
Class CCopasiObjectName
This class is the class for handling Copasi object names.
Copyright Stefan Hoops 2002
Definition at line 32 of file CCopasiObjectName.h.
Constructor & Destructor Documentation
CCopasiObjectName::CCopasiObjectName ()
Definition at line 40 of file CCopasiObjectName.cpp.
Referenced by getRemainder().
                                     :
     string()
 {}
CCopasiObjectName::CCopasiObjectName (const std::string & name)
Definition at line 44 of file CCopasiObjectName.cpp.
                                                           :
     string(name)
 {}
CCopasiObjectName::CCopasiObjectName (const CCopasiObjectName & src)
Definition at line 48 of file CCopasiObjectName.cpp.
                                                                  :
     string(src)
 {}
CCopasiObjectName::~CCopasiObjectName ()
Definition at line 52 of file CCopasiObjectName.cpp.
 {}
Member Function Documentation
std::string CCopasiObjectName::escape (const std::string & name) static
Definition at line 126 of file CCopasiObjectName.cpp.
References toBeEscaped.
Referenced by CExperiment::compile(), CCopasiParameter::getCN(), CCopasiObject::getCN(), and CCopasiObject::setObjectName().
 {
 #define toBeEscaped "\\[]=,>"
   std::string Escaped(name);
   std::string::size_type pos = Escaped.find_first_of(toBeEscaped);
   while (pos != std::string::npos)
     {
       Escaped.insert(pos, "\\");
       pos += 2;
       pos = Escaped.find_first_of(toBeEscaped, pos);
     }
   return Escaped;
 #undef toBeEscaped
 }
std::string::size_type CCopasiObjectName::findEx (const std::string & toFind, const std::string::size_type & pos = 0) const
Definition at line 159 of file CCopasiObjectName.cpp.
Referenced by getElementName(), getObjectName(), getObjectType(), getPrimary(), and getRemainder().
 {
   std::string::size_type where = find_first_of(toFind, pos);
   std::string::size_type tmp;
   while (where && where != std::string::npos)
     {
       tmp = find_last_not_of("\\", where - 1);
       if ((where - tmp) % 2)
         return where;
       where = find_first_of(toFind, where + 1);
     }
   return where;
 }
size_t CCopasiObjectName::getElementIndex (const size_t & pos = 0) const
Definition at line 86 of file CCopasiObjectName.cpp.
References C_INVALID_INDEX, and getElementName().
Referenced by CCopasiVector< CLGeneralGlyph >::getObject(), and CArrayElementReference::getValuePointer().
 {
   std::string Index = getElementName(pos);
   std::stringstream tmp(Index);
   size_t index = C_INVALID_INDEX;
   tmp >> index;
   if (tmp.fail()) return C_INVALID_INDEX;
   tmp << index;
   if (Index != tmp.str()) return C_INVALID_INDEX;
   return index;
 }
std::string CCopasiObjectName::getElementName (const size_t & pos, const bool & unescape = true) const
Definition at line 104 of file CCopasiObjectName.cpp.
References findEx(), getPrimary(), and unescape().
Referenced by getElementIndex(), CCopasiContainer::getObject(), CArrayAnnotation::getObject(), CCopasiVectorN< CReportDefinition >::getObject(), CArrayElementReference::getValuePointer(), and CModelParameter::nameFromCN().
 {
   CCopasiObjectName Primary = getPrimary();
   std::string::size_type open = findEx("[");
   size_t i;
   for (i = 0; i < pos && open != std::string::npos; i++)
     open = findEx("[", open + 1);
   std::string::size_type close = findEx("]", open + 1);
   if (open == std::string::npos || close == std::string::npos) return "";
   if (unescape)
     return CCopasiObjectName::unescape(Primary.substr(open + 1,
                                        close - open - 1));
   return Primary.substr(open + 1, close - open - 1);
 }
std::string CCopasiObjectName::getObjectName () const
Definition at line 74 of file CCopasiObjectName.cpp.
References findEx(), getPrimary(), and unescape().
Referenced by CCopasiContainer::getObject(), CCopasiParameterGroup::getObject(), CCopasiVector< CLGeneralGlyph >::getObject(), CCopasiVectorN< CReportDefinition >::getObject(), and CModelParameter::nameFromCN().
 {
   CCopasiObjectName Primary = getPrimary();
   std::string::size_type pos = Primary.findEx("=");
   if (pos == std::string::npos) return "";
   CCopasiObjectName tmp = Primary.substr(pos + 1);
   return CCopasiObjectName::unescape(tmp.substr(0, tmp.findEx("[")));
 }
std::string CCopasiObjectName::getObjectType () const
Definition at line 67 of file CCopasiObjectName.cpp.
References findEx(), getPrimary(), and unescape().
Referenced by CModelParameterReactionParameter::compile(), CCopasiContainer::getObject(), CCopasiVector< CLGeneralGlyph >::getObject(), CCopasiVectorN< CReportDefinition >::getObject(), and CModelExpansion::updateExpression().
 {
   CCopasiObjectName Primary(getPrimary());
   return CCopasiObjectName::unescape(Primary.substr(0, Primary.findEx("=")));
 }
CCopasiObjectName CCopasiObjectName::getPrimary () const
Definition at line 55 of file CCopasiObjectName.cpp.
References findEx().
Referenced by CModelParameterReactionParameter::compile(), getElementName(), CMathContainer::getObject(), getObjectName(), getObjectType(), CModelParameter::nameFromCN(), CModelParameterSpecies::setCN(), and CModelExpansion::updateExpression().
 {return substr(0, findEx(","));}
CCopasiObjectName CCopasiObjectName::getRemainder () const
Definition at line 58 of file CCopasiObjectName.cpp.
References CCopasiObjectName(), and findEx().
Referenced by CModelParameterReactionParameter::compile(), CCopasiContainer::getObject(), CCopasiParameterGroup::getObject(), CArrayAnnotation::getObject(), CCopasiXMLParser::getObjectFromName(), CModelParameter::nameFromCN(), CCopasiDataModel::ObjectFromCN(), CModelParameterSpecies::setCN(), and CModelExpansion::updateExpression().
 {
   std::string::size_type pos = findEx(",");
   if (pos == std::string::npos) return CCopasiObjectName();
   return substr(pos + 1);
 }
std::string CCopasiObjectName::unescape (const std::string & name) static
Definition at line 143 of file CCopasiObjectName.cpp.
Referenced by getElementName(), getObjectName(), and getObjectType().
 {
   std::string Unescaped(name);
   std::string::size_type pos = Unescaped.find("\\");
   while (pos != std::string::npos)
     {
       Unescaped.erase(pos, 1);
       pos++;
       pos = Unescaped.find("\\", pos);
     }
   return Unescaped;
 }
The documentation for this class was generated from the following files:
CCopasiObjectName.h
CCopasiObjectName.cpp