COPASI API: CSteadyStateTask Class Reference
CSteadyStateTask Class Reference
#include <CSteadyStateTask.h>
Public Member Functions
virtual CCopasiMethod * createMethod (const int &type) const
CSteadyStateTask (const CCopasiContainer *pParent=NULL)
CSteadyStateTask (const CSteadyStateTask &src, const CCopasiContainer *pParent=NULL)
const CEigen & getEigenValues () const
const CEigen & getEigenValuesReduced () const
const CMatrix< C_FLOAT64 > & getJacobian () const
const CArrayAnnotation * getJacobianAnnotated () const
const CMatrix< C_FLOAT64 > & getJacobianReduced () const
const CArrayAnnotation * getJacobianXAnnotated () const
const
CSteadyStateMethod::ReturnCode & getResult () const
const CState * getState () const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
void load (CReadConfig &configBuffer)
virtual void print (std::ostream *ostream) const
virtual bool process (const bool &useInitialValues)
virtual bool restore ()
void setInitialState ()
virtual bool updateMatrices ()
virtual ~CSteadyStateTask ()
Public Member Functions inherited from CCopasiTask
CCopasiTask (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const Type &taskType, const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const CCopasiTask &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
CProcessReport * getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
Type getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setMethodType (const int &type)
void setScheduled (const bool &scheduled)
void setType (const Type &type)
void setUpdateModel (const bool &updateModel)
virtual ~CCopasiTask ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void cleanup ()
void initObjects ()
Private Attributes
bool mCalculateReducedSystem
CEigen mEigenValues
CMatrix< C_FLOAT64 > mEigenvaluesMatrix
CEigen mEigenValuesX
CMatrix< C_FLOAT64 > mEigenvaluesXMatrix
CMatrix< C_FLOAT64 > mJacobian
CMatrix< C_FLOAT64 > mJacobianX
CArrayAnnotation * mpEigenvaluesJacobianAnn
CArrayAnnotation * mpEigenvaluesJacobianXAnn
CArrayAnnotation * mpJacobianAnn
CArrayAnnotation * mpJacobianXAnn
CState * mpSteadyState
CSteadyStateMethod::ReturnCode mResult
Friends
std::ostream & operator<< (std::ostream &os, const CSteadyStateTask &A)
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01, STREAM = 0x02, FINISH = 0x04, REPORT = 0x10,
PLOT = 0x20, TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0, OUTPUT_BEFORE = INITIALIZE, OUTPUT_AFTER = FINISH, OUTPUT = REPORT | PLOT | STREAM,
OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH, OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH, ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
enum Type {
steadyState = 0, timeCourse, scan, fluxMode,
optimization, parameterFitting, mca, lyap,
tssAnalysis, sens, moieties, crosssection,
lna, unset
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiTask
static bool isValidMethod (const unsigned int &method, const unsigned int *validMethods)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Static Public Attributes inherited from CCopasiTask
static const std::string TypeName []
static const unsigned int ValidMethods []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
std::string mKey
unsigned C_INT32 mOutputCounter
CProcessReport * mpCallBack
CState * mpInitialState
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
Type mType
bool mUpdateModel
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 49 of file CSteadyStateTask.h.
Constructor & Destructor Documentation
CSteadyStateTask::CSteadyStateTask (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 40 of file CSteadyStateTask.cpp.
References CCopasiContainer::add(), createMethod(), initObjects(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiMethod::Newton.
                                                                   :
   CCopasiTask(CCopasiTask::steadyState, pParent),
   mpSteadyState(NULL),
   mJacobian(),
   mJacobianX(),
   mpJacobianAnn(NULL),
   mpJacobianXAnn(NULL),
   mEigenValues("Eigenvalues of Jacobian", this),
   mEigenValuesX("Eigenvalues of reduced system Jacobian", this)
 {
   mpProblem = new CSteadyStateProblem(this);
   mpMethod = createMethod(CCopasiMethod::Newton);
   this->add(mpMethod, true);
   initObjects();
 }
CSteadyStateTask::CSteadyStateTask (const CSteadyStateTask & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CSteadyStateTask & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 58 of file CSteadyStateTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiMethod::getSubType(), initObjects(), CCopasiTask::mpMethod, and CCopasiTask::mpProblem.
                                                                     :
   CCopasiTask(src, pParent),
   mpSteadyState(src.mpSteadyState),
   mJacobian(src.mJacobian),
   mJacobianX(src.mJacobianX),
   mpJacobianAnn(NULL),
   mpJacobianXAnn(NULL),
   mEigenValues(src.mEigenValues, this),
   mEigenValuesX(src.mEigenValuesX, this)
 {
   mpProblem =
     new CSteadyStateProblem(*(CSteadyStateProblem *) src.mpProblem, this);
   mpMethod = createMethod(src.mpMethod->getSubType());
   this->add(mpMethod, true);
   initObjects();
 }
CSteadyStateTask::~CSteadyStateTask () virtual
Destructor
Definition at line 78 of file CSteadyStateTask.cpp.
References mpSteadyState, and pdelete.
 {
   pdelete(mpSteadyState);
 }
Member Function Documentation
void CSteadyStateTask::cleanup () private
cleanup()
Definition at line 91 of file CSteadyStateTask.cpp.
 {}
CCopasiMethod * CSteadyStateTask::createMethod (const int & type) const virtual
Create a method of the specified type to solve the task. It is the duty of the caller to release the CCopasiMethod.
Parameters
const CCopasiMethod::SubType & type
Returns
CCopasiMethod *
Reimplemented from CCopasiTask.
Definition at line 84 of file CSteadyStateTask.cpp.
References CSteadyStateMethod::createMethod().
Referenced by CSteadyStateTask().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   return CSteadyStateMethod::createMethod(Type);
 }
const CEigen & CSteadyStateTask::getEigenValues () const
Retrieves a the eigenvalues of the steady state.
Returns
const CEigen & eigenValues
Definition at line 156 of file CSteadyStateTask.cpp.
References mEigenValues.
Referenced by StateSubwidget::loadJacobian().
 {
   return mEigenValues;
 }
const CEigen & CSteadyStateTask::getEigenValuesReduced () const
Retrieves a the eigenvalues of the steady state.
Returns
const CEigen & eigenValues
Definition at line 160 of file CSteadyStateTask.cpp.
References mEigenValuesX.
Referenced by StateSubwidget::loadJacobian(), and CLNATask::process().
 {
   return mEigenValuesX;
 }
const CMatrix< C_FLOAT64 > & CSteadyStateTask::getJacobian () const
Retrieves a the jacobian of the steady state.
Returns
const CMatrix< C_FLOAT64 > jacobian
Definition at line 141 of file CSteadyStateTask.cpp.
References mJacobian.
Referenced by CMCAMethod::createLinkMatrix().
 {return mJacobian;}
const CArrayAnnotation * CSteadyStateTask::getJacobianAnnotated () const
Definition at line 146 of file CSteadyStateTask.cpp.
References mpJacobianAnn.
Referenced by StateSubwidget::loadJacobian().
 {
   return mpJacobianAnn;
 }
const CMatrix< C_FLOAT64 > & CSteadyStateTask::getJacobianReduced () const
Retrieves a the jacobian of the steady state.
Returns
const CMatrix< C_FLOAT64 > jacobian
Definition at line 143 of file CSteadyStateTask.cpp.
References mJacobianX.
 {return mJacobianX;}
const CArrayAnnotation * CSteadyStateTask::getJacobianXAnnotated () const
Definition at line 151 of file CSteadyStateTask.cpp.
References mpJacobianXAnn.
Referenced by StateSubwidget::loadJacobian().
 {
   return mpJacobianXAnn;
 }
const CSteadyStateMethod::ReturnCode& CSteadyStateTask::getResult () const inline
Converts the eigenvalues vector to matrix
Parameters
CEigen &eigenvalues
Returns
CMatrix<C_FLOAT64> &matrix
Definition at line 230 of file CSteadyStateTask.h.
References mResult.
Referenced by StateSubwidget::loadAll(), operator<<(), CLNATask::process(), CMCAMethod::setSteadyStateTask(), and SteadyStateWidget::taskFinishedEvent().
 {return mResult;}
const CState * CSteadyStateTask::getState () const
Retrieves a pointer to steady state.
Returns
CState * pSteadyState
Definition at line 138 of file CSteadyStateTask.cpp.
References mpSteadyState.
Referenced by StateSubwidget::loadAll(), CQSteadyStateResult::loadResult(), operator<<(), and CQSteadyStateResult::slotUpdateModel().
 {return mpSteadyState;}
bool CSteadyStateTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 220 of file CSteadyStateTask.cpp.
References CVectorCore< CType >::array(), CStateTemplate::beginIndependent(), CCopasiObject::getCN(), CStateTemplate::getEntities(), CModel::getInitialState(), CCopasiProblem::getModel(), CState::getNumDependent(), CModel::getNumDependentReactionMetabs(), CState::getNumIndependent(), CModel::getStateTemplate(), CModelEntity::getStatus(), CStateTemplate::getUserOrder(), CSteadyStateProblem::initialize(), CSteadyStateMethod::initialize(), CCopasiTask::initialize(), CCopasiMethod::isValidProblem(), mCalculateReducedSystem, mJacobian, mJacobianX, mpJacobianAnn, mpJacobianXAnn, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mpSteadyState, CModelEntity::ODE, pdelete, CModelEntity::REACTIONS, CMatrix< CType >::resize(), CArrayAnnotation::resize(), CArrayAnnotation::setAnnotationCN(), CVectorCore< CType >::size(), and updateMatrices().
Referenced by CFitProblem::initialize(), CLNATask::initialize(), and CMCATask::initialize().
 {
   assert(mpProblem && mpMethod);
   if (!mpMethod->isValidProblem(mpProblem)) return false;
   bool success = true;
   if (!updateMatrices())
     return false;
   success &= CCopasiTask::initialize(of, pOutputHandler, pOstream);
   pdelete(mpSteadyState);
   mpSteadyState = new CState(mpProblem->getModel()->getInitialState());
   mCalculateReducedSystem = (mpProblem->getModel()->getNumDependentReactionMetabs() != 0);
 #ifdef xxxx
   // init Jacobians
   size_t sizeX = mpSteadyState->getNumIndependent();
   mJacobianX.resize(sizeX, sizeX);
   size_t size = sizeX + mpSteadyState->getNumDependent();
   mJacobian.resize(size, size);
   //jacobian annotations
   CStateTemplate & StateTemplate = mpProblem->getModel()->getStateTemplate();
   mpJacobianAnn->resize();
   CModelEntity **ppEntities = StateTemplate.getEntities();
   const size_t * pUserOrder = StateTemplate.getUserOrder().array();
   const size_t * pUserOrderEnd = pUserOrder + StateTemplate.getUserOrder().size();
   pUserOrder++; // We skip the time which is the first.
   size_t i, imax = size;
   for (i = 0; i < imax && pUserOrder != pUserOrderEnd; pUserOrder++)
     {
       const CModelEntity::Status & Status = ppEntities[*pUserOrder]->getStatus();
       if (Status == CModelEntity::ODE ||
           (Status == CModelEntity::REACTIONS && ppEntities[*pUserOrder]->isUsed()))
         {
           mpJacobianAnn->setAnnotationCN(0 , i, ppEntities[*pUserOrder]->getCN());
           mpJacobianAnn->setAnnotationCN(1 , i, ppEntities[*pUserOrder]->getCN());
           i++;
         }
     }
   mpJacobianXAnn->resize();
   ppEntities = StateTemplate.beginIndependent();
   imax = sizeX;
   for (i = 0; i < imax; ++i, ++ppEntities)
     {
       mpJacobianXAnn->setAnnotationCN(0 , i, (*ppEntities)->getCN());
       mpJacobianXAnn->setAnnotationCN(1 , i, (*ppEntities)->getCN());
     }
 #endif
   CSteadyStateProblem* pProblem =
     dynamic_cast<CSteadyStateProblem *>(mpProblem);
   assert(pProblem);
   success &= pProblem->initialize();
   CSteadyStateMethod* pMethod =
     dynamic_cast<CSteadyStateMethod *>(mpMethod);
   assert(pMethod);
   success &= pMethod->initialize(pProblem);
   return success;
 }
void CSteadyStateTask::initObjects () private
Definition at line 94 of file CSteadyStateTask.cpp.
References mEigenvaluesMatrix, mEigenvaluesXMatrix, mJacobian, mJacobianX, mpEigenvaluesJacobianAnn, mpEigenvaluesJacobianXAnn, mpJacobianAnn, mpJacobianXAnn, CArrayAnnotation::OBJECTS, CArrayAnnotation::setDescription(), CArrayAnnotation::setDimensionDescription(), CArrayAnnotation::setMode(), and CArrayAnnotation::VECTOR.
Referenced by CSteadyStateTask().
 {
   mpJacobianAnn = new CArrayAnnotation("Jacobian (complete system)", this,
                                        new CCopasiMatrixInterface<CMatrix<C_FLOAT64> >(&mJacobian), true);
   mpJacobianAnn->setMode(CArrayAnnotation::OBJECTS);
   mpJacobianAnn->setDescription("");
   mpJacobianAnn->setDimensionDescription(0, "Variables of the system, including dependent species");
   mpJacobianAnn->setDimensionDescription(1, "Variables of the system, including dependent species");
   mpJacobianXAnn = new CArrayAnnotation("Jacobian (reduced system)", this,
                                         new CCopasiMatrixInterface<CMatrix<C_FLOAT64> >(&mJacobianX), true);
   mpJacobianXAnn->setMode(CArrayAnnotation::OBJECTS);
   mpJacobianXAnn->setDescription("");
   mpJacobianXAnn->setDimensionDescription(0, "Independent variables of the system");
   mpJacobianXAnn->setDimensionDescription(1, "Independent variables of the system");
   mpEigenvaluesJacobianAnn = new CArrayAnnotation("Eigenvalues of Jacobian", this,
       new CCopasiMatrixInterface<CMatrix<C_FLOAT64> >(&mEigenvaluesMatrix), true);
   mpEigenvaluesJacobianAnn->setMode(CArrayAnnotation::VECTOR);
   mpEigenvaluesJacobianAnn->setDescription("");
   mpEigenvaluesJacobianAnn->setDimensionDescription(0, "n-th value");
   mpEigenvaluesJacobianAnn->setDimensionDescription(1, "Real/Imaginary part");
   mpEigenvaluesJacobianXAnn = new CArrayAnnotation("Eigenvalues of reduced system Jacobian", this,
       new CCopasiMatrixInterface<CMatrix<C_FLOAT64> >(&mEigenvaluesXMatrix), true);
 //  mpEigenvaluesJacobianXAnn->setMode(CArrayAnnotation::VECTOR);
   mpEigenvaluesJacobianXAnn->setMode(CArrayAnnotation::OBJECTS);
   mpEigenvaluesJacobianXAnn->setDescription("");
   mpEigenvaluesJacobianXAnn->setDimensionDescription(0, "n-th value");
   mpEigenvaluesJacobianXAnn->setDimensionDescription(1, "Real/Imaginary part");
 }
void CSteadyStateTask::load (CReadConfig & configBuffer)
Loads parameters for this solver with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
configbuffer reference to a CReadConfig object.
Definition at line 128 of file CSteadyStateTask.cpp.
References CReadConfig::getVariable(), CReadConfig::LOOP, CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiTask::mScheduled.
Referenced by CCopasiDataModel::loadModel().
 {
   configBuffer.getVariable("SteadyState", "bool", &mScheduled,
                            CReadConfig::LOOP);
   ((CSteadyStateProblem *) mpProblem)->load(configBuffer);
   ((CSteadyStateMethod *) mpMethod)->load(configBuffer);
 }
void CSteadyStateTask::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 126 of file CSteadyStateTask.cpp.
 {(*ostream) << (*this);}
bool CSteadyStateTask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 301 of file CSteadyStateTask.cpp.
References COutputInterface::AFTER, CModel::applyInitialValues(), CMatrix< CType >::array(), COutputInterface::BEFORE, C_FLOAT64, C_INT32, CEigen::calcEigenValues(), CSteadyStateMethod::doJacobian(), CEigen::getI(), CCopasiProblem::getModel(), CEigen::getR(), CSteadyStateMethod::getStabilityResolution(), CModel::getState(), CState::getTime(), CSteadyStateProblem::isJacobianRequested(), CSteadyStateProblem::isStabilityAnalysisRequested(), CState::isValid(), mEigenValues, mEigenvaluesMatrix, mEigenValuesX, mEigenvaluesXMatrix, mJacobian, mJacobianX, CCopasiTask::mpCallBack, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mpSteadyState, mResult, CSteadyStateMethod::notFound, CCopasiTask::output(), CSteadyStateMethod::process(), restore(), CState::setTime(), CVectorCore< CType >::size(), CMatrix< CType >::size(), and CEigen::stabilityAnalysis().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), CLNATask::process(), and CMCATask::process().
 {
   if (useInitialValues)
     {
       mpProblem->getModel()->applyInitialValues();
     }
   *mpSteadyState = mpProblem->getModel()->getState();
   // A steady-state makes only sense in an autonomous model,
   // i.e., the time of the steady-state must not be changed
   // during simulation.
   C_FLOAT64 InitialTime = mpSteadyState->getTime();
   CSteadyStateMethod* pMethod =
     dynamic_cast<CSteadyStateMethod *>(mpMethod);
   assert(pMethod);
   CSteadyStateProblem* pProblem =
     dynamic_cast<CSteadyStateProblem *>(mpProblem);
   assert(pMethod);
   output(COutputInterface::BEFORE);
   //call the method
   mResult = pMethod->process(mpSteadyState,
                              mJacobianX,
                              mpCallBack);
   if (mResult == CSteadyStateMethod::notFound)
     restore();
   //update jacobian
   if (mpSteadyState->isValid())
     {
       if (pProblem->isJacobianRequested() ||
           pProblem->isStabilityAnalysisRequested())
         {
           pMethod->doJacobian(mJacobian, mJacobianX);
         }
       //mpProblem->getModel()->setState(mpSteadyState);
       //mpProblem->getModel()->updateRates();
       //calculate eigenvalues
       if (pProblem->isStabilityAnalysisRequested())
         {
           mEigenValues.calcEigenValues(mJacobian);
           mEigenValuesX.calcEigenValues(mJacobianX);
           mEigenValues.stabilityAnalysis(pMethod->getStabilityResolution());
           mEigenValuesX.stabilityAnalysis(pMethod->getStabilityResolution());
         }
     }
   // Reset the time.
   mpSteadyState->setTime(InitialTime);
   C_FLOAT64 * pTo;
   size_t i;
   // construct Eigenvalues of Jacobian
   CVector< C_FLOAT64 > vectorEigen_R = mEigenValues.getR();
   CVector< C_FLOAT64 > vectorEigen_I = mEigenValues.getI();
 #ifdef DEBUG_UI
   C_INT32 size = vectorEigen_R.size() + vectorEigen_I.size();
   std::cout << "vectorEigen_R.size() = " << vectorEigen_R.size() << " + vectorEigen_I.size() = " << vectorEigen_I.size() << " == " << size << std::endl;
   std::cout << "size = " << mEigenvaluesXMatrix.size() << std::endl;
 #endif
   assert(vectorEigen_R.size() == vectorEigen_I.size());
   pTo = mEigenvaluesMatrix.array();
   for (i = 0; i < vectorEigen_R.size(); ++i)
     {
       *pTo = vectorEigen_R[i]; ++pTo;
       *pTo = vectorEigen_I[i]; ++pTo;
     }
 #ifdef DEBUG_UI
   std::cout << mEigenvaluesMatrix << std::endl;
 #endif
   // construct Eigenvalues of Jacobian of reduced system
   CVector< C_FLOAT64 > vectorEigenX_R = mEigenValuesX.getR();
   CVector< C_FLOAT64 > vectorEigenX_I = mEigenValuesX.getI();
 #ifdef DEBUG_UI
   C_INT32 sizeX = vectorEigenX_R.size() + vectorEigenX_I.size();
   std::cout << "vectorEigenX_R.size() = " << vectorEigenX_R.size() << " + vectorEigenX_I.size() = " << vectorEigenX_I.size() << " == " << sizeX << std::endl;
   std::cout << "size = " << mEigenvaluesXMatrix.size() << std::endl;
 #endif
   assert(vectorEigenX_R.size() == vectorEigenX_I.size());
   pTo = mEigenvaluesXMatrix.array();
   for (i = 0; i < vectorEigenX_R.size(); ++i)
     {
       *pTo = vectorEigenX_R[i]; ++pTo;
       *pTo = vectorEigenX_I[i]; ++pTo;
     }
 #ifdef DEBUG_UI
   std::cout << mEigenvaluesXMatrix << std::endl;
 #endif
   output(COutputInterface::AFTER);
   return (mResult != CSteadyStateMethod::notFound);
 }
bool CSteadyStateTask::restore () virtual
Perform necessary cleanup procedures
Reimplemented from CCopasiTask.
Definition at line 422 of file CSteadyStateTask.cpp.
References CCopasiProblem::getModel(), CModel::getState(), CCopasiTask::mpProblem, mpSteadyState, CCopasiTask::mUpdateModel, CCopasiTask::restore(), CModel::setInitialState(), CModel::setState(), CModel::updateInitialValues(), and CModel::updateSimulatedValues().
Referenced by process(), CFitProblem::restore(), CLNATask::restore(), CMCATask::restore(), and CQSteadyStateResult::slotUpdateModel().
 {
   bool success = CCopasiTask::restore();
   if (mUpdateModel)
     {
       CModel * pModel = mpProblem->getModel();
       pModel->setState(*mpSteadyState);
       pModel->updateSimulatedValues(true);
       pModel->setInitialState(pModel->getState());
       pModel->updateInitialValues();
     }
   return success;
 }
void CSteadyStateTask::setInitialState ()
Set initial state by taking the current one.
Definition at line 416 of file CSteadyStateTask.cpp.
References CCopasiProblem::getModel(), CModel::getState(), CCopasiTask::mpProblem, and CModel::setInitialState().
 {
   CModel * pModel = mpProblem->getModel();
   pModel->setInitialState(pModel->getState());
 }
bool CSteadyStateTask::updateMatrices () virtual
Resizes result matrices and updates array annotations for a specific task. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented from CCopasiTask.
Definition at line 165 of file CSteadyStateTask.cpp.
References CVectorCore< CType >::array(), CStateTemplate::beginIndependent(), CCopasiObject::getCN(), CStateTemplate::getEntities(), CCopasiProblem::getModel(), CStateTemplate::getNumDependent(), CStateTemplate::getNumIndependent(), CModel::getStateTemplate(), CModelEntity::getStatus(), CStateTemplate::getUserOrder(), mEigenvaluesMatrix, mEigenvaluesXMatrix, mJacobian, mJacobianX, mpJacobianAnn, mpJacobianXAnn, CCopasiTask::mpProblem, CModelEntity::ODE, CModelEntity::REACTIONS, CMatrix< CType >::resize(), CArrayAnnotation::resize(), CArrayAnnotation::setAnnotationCN(), and CVectorCore< CType >::size().
Referenced by initialize().
 {
   if (!mpProblem->getModel()) return false;
   const CStateTemplate & stateTemplate = mpProblem->getModel()->getStateTemplate();
   // init Jacobians
   size_t sizeX = stateTemplate.getNumIndependent();
   mJacobianX.resize(sizeX, sizeX);
   size_t size = sizeX + stateTemplate.getNumDependent();
   mJacobian.resize(size, size);
   // Jacobian Annotations
   mpJacobianAnn->resize();
   CModelEntity *const* ppEntities = stateTemplate.getEntities();
   const size_t * pUserOrder = stateTemplate.getUserOrder().array();
   const size_t * pUserOrderEnd = pUserOrder + stateTemplate.getUserOrder().size();
   pUserOrder++; // We skip the time which is the first.
   size_t i, imax = size;
   for (i = 0; i < imax && pUserOrder != pUserOrderEnd; pUserOrder++)
     {
       const CModelEntity::Status & Status = ppEntities[*pUserOrder]->getStatus();
       if (Status == CModelEntity::ODE ||
           (Status == CModelEntity::REACTIONS && ppEntities[*pUserOrder]->isUsed()))
         {
           mpJacobianAnn->setAnnotationCN(0 , i, ppEntities[*pUserOrder]->getCN());
           mpJacobianAnn->setAnnotationCN(1 , i, ppEntities[*pUserOrder]->getCN());
           i++;
         }
     }
   mpJacobianXAnn->resize();
   ppEntities = stateTemplate.beginIndependent();
   imax = sizeX;
   for (i = 0; i < imax; ++i, ++ppEntities)
     {
       mpJacobianXAnn->setAnnotationCN(0 , i, (*ppEntities)->getCN());
       mpJacobianXAnn->setAnnotationCN(1 , i, (*ppEntities)->getCN());
     }
   // initial dimension of Eigenvalues of Jacobian
   mEigenvaluesMatrix.resize(size, 2);
   mEigenvaluesXMatrix.resize(sizeX, 2);
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CSteadyStateTask & A) friend
Definition at line 439 of file CSteadyStateTask.cpp.
 {
   switch (A.getResult())
     {
       case CSteadyStateMethod::found:
         os << "A steady state with given resolution was found." << std::endl;
         break;
       case CSteadyStateMethod::notFound:
         os << "No steady state with given resolution was found!" << std::endl;
         os << "(below are the last unsuccessful trial values)" << std::endl;
         break;
       case CSteadyStateMethod::foundEquilibrium:
         os << "An equilibrium steady state (zero fluxes) was found." << std::endl;
         break;
       case CSteadyStateMethod::foundNegative:
         os << "An invalid steady state (negative concentrations) was found." << std::endl;
     }
   os << std::endl;
   // Update all necessary values.
   CState * pState = const_cast<CState *>(A.getState());
   if (!pState) return os;
   CModel * pModel = A.mpProblem->getModel();
   if (!pModel) return os;
   pModel->setState(*pState);
   pModel->updateSimulatedValues(true);
   pModel->updateNonSimulatedValues();
   // Metabolite Info: Name, Concentration, Concentration Rate, Particle Number, Particle Rate, Transition Time
   const CCopasiVector<CMetab> & Metabolites = pModel->getMetabolites();
   const CMetab * pMetab;
   size_t i, imax = Metabolites.size();
   os << "Species" << "\t";
   os << "Concentration";
   std::string Units = pModel->getConcentrationUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Concentration Rate";
   Units = pModel->getConcentrationRateUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Particle Number" << "\t";
   os << "Particle Number Rate";
   Units = pModel->getFrequencyUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Transition Time";
   Units = pModel->getTimeUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << std::endl;
   for (i = 0; i < imax; ++i)
     {
       pMetab = Metabolites[i];
       os << CMetabNameInterface::getDisplayName(pModel, *pMetab, false) << "\t";
       os << pMetab->getConcentration() << "\t";
       os << pMetab->getConcentrationRate() << "\t";
       os << pMetab->getValue() << "\t";
       os << pMetab->getRate() << "\t";
       os << pMetab->getTransitionTime() << std::endl;
     }
   os << std::endl;
   // Reaction Info: Name, Flux, Particle Flux
   const CCopasiVector<CReaction>& Reactions = pModel->getReactions();
   const CReaction * pReaction;
   imax = Reactions.size();
   os << "Reaction" << "\t";
   os << "Flux";
   Units = pModel->getQuantityRateUnitsDisplayString();
   if (Units != "")
     os << " (" << Units << ")";
   os << "\t";
   os << "Particle Flux";
   Units = pModel->getFrequencyUnitsDisplayString();;
   if (Units != "")
     os << " (" << Units << ")";
   os << std::endl;
   for (i = 0; i < imax; ++i)
     {
       pReaction = Reactions[i];
       os << pReaction->getObjectName() << "\t";
       os << pReaction->getFlux() << "\t";
       os << pReaction->getParticleFlux() << std::endl;
     }
   os << std::endl;
   if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isJacobianRequested())
     {
       os << *A.mpJacobianAnn << std::endl;
       if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isStabilityAnalysisRequested())
         {
           os << "Eigenvalues\treal\timaginary" << std::endl;
           imax = A.mEigenValues.getR().size();
           for (i = 0; i < imax; i++)
             os << "\t" << A.mEigenValues.getR()[i] << "\t" << A.mEigenValues.getI()[i] << std::endl;
           os << std::endl;
         }
       os << *A.mpJacobianXAnn << std::endl;
       if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isStabilityAnalysisRequested())
         {
           os << "Eigenvalues\treal\timaginary" << std::endl;
           imax = A.mEigenValuesX.getR().size();
           for (i = 0; i < imax; i++)
             os << "\t" << A.mEigenValuesX.getR()[i] << "\t" << A.mEigenValuesX.getI()[i] << std::endl;
           os << std::endl;
         }
     }
   if (static_cast<CSteadyStateProblem *>(A.mpProblem)->isStabilityAnalysisRequested())
     {
       os << "Stability Analysis of the Reduced System" << std::endl;
       os << A.mEigenValuesX << std::endl;
     }
   return os;
 }
Member Data Documentation
bool CSteadyStateTask::mCalculateReducedSystem private
Whether the model is actually reducible and calculating stability of the reduced steady states makes sense
Definition at line 75 of file CSteadyStateTask.h.
Referenced by initialize().
CEigen CSteadyStateTask::mEigenValues private
The Eigenvalues of the Jacobian of the system
Definition at line 80 of file CSteadyStateTask.h.
Referenced by getEigenValues(), operator<<(), and process().
CMatrix<C_FLOAT64> CSteadyStateTask::mEigenvaluesMatrix private
The Eigenvalues matrix of the Jacobian of the system
Definition at line 90 of file CSteadyStateTask.h.
Referenced by initObjects(), process(), and updateMatrices().
CEigen CSteadyStateTask::mEigenValuesX private
The Eigenvalues of the Jacobian of the reduced system
Definition at line 85 of file CSteadyStateTask.h.
Referenced by getEigenValuesReduced(), operator<<(), and process().
CMatrix<C_FLOAT64> CSteadyStateTask::mEigenvaluesXMatrix private
The Eigenvalues matrix of the Jacobian of the reduced system
Definition at line 95 of file CSteadyStateTask.h.
Referenced by initObjects(), process(), and updateMatrices().
CMatrix< C_FLOAT64 > CSteadyStateTask::mJacobian private
The jacobian of the steady state.
Definition at line 61 of file CSteadyStateTask.h.
Referenced by getJacobian(), initialize(), initObjects(), process(), and updateMatrices().
CMatrix< C_FLOAT64 > CSteadyStateTask::mJacobianX private
The jacobian of the steady state.
Definition at line 66 of file CSteadyStateTask.h.
Referenced by getJacobianReduced(), initialize(), initObjects(), process(), and updateMatrices().
CArrayAnnotation* CSteadyStateTask::mpEigenvaluesJacobianAnn private
Definition at line 97 of file CSteadyStateTask.h.
Referenced by initObjects().
CArrayAnnotation* CSteadyStateTask::mpEigenvaluesJacobianXAnn private
Definition at line 98 of file CSteadyStateTask.h.
Referenced by initObjects().
CArrayAnnotation* CSteadyStateTask::mpJacobianAnn private
Definition at line 68 of file CSteadyStateTask.h.
Referenced by getJacobianAnnotated(), initialize(), initObjects(), operator<<(), and updateMatrices().
CArrayAnnotation* CSteadyStateTask::mpJacobianXAnn private
Definition at line 69 of file CSteadyStateTask.h.
Referenced by getJacobianXAnnotated(), initialize(), initObjects(), operator<<(), and updateMatrices().
CState* CSteadyStateTask::mpSteadyState private
A pointer to the found steady state.
Definition at line 56 of file CSteadyStateTask.h.
Referenced by getState(), initialize(), process(), restore(), and ~CSteadyStateTask().
CSteadyStateMethod::ReturnCode CSteadyStateTask::mResult private
The result of the steady state analysis.
Definition at line 103 of file CSteadyStateTask.h.
Referenced by getResult(), and process().
The documentation for this class was generated from the following files:
CSteadyStateTask.h
CSteadyStateTask.cpp