COPASI API: test000043 Class Reference
test000043 Class Reference
#include <test000043.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_hasOnlySubstanceUnits ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_hasOnlySubstanceUnits)
CPPUNIT_TEST_SUITE (test000043)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000043.h.
Member Function Documentation
test000043::CPPUNIT_TEST (test_hasOnlySubstanceUnits) private
test000043::CPPUNIT_TEST_SUITE (test000043) private
test000043::CPPUNIT_TEST_SUITE_END () private
void test000043::setUp ()
Definition at line 28 of file test000043.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000043::tearDown ()
Definition at line 36 of file test000043.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000043::test_hasOnlySubstanceUnits ()
Definition at line 41 of file test000043.cpp.
References CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CFunctionParameter::FLOAT64, CEvaluationNodeCall::FUNCTION, CEvaluationNodeCall::getCalledTree(), CCopasiNode< _Data >::getChild(), CChemEq::getCompartmentNumber(), CEvaluationNodeCall::getData(), CCopasiDataModel::getModel(), CChemEq::getModifiers(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CChemEq::getProducts(), CChemEq::getSubstrates(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, MODEL_STRING, CEvaluationNodeOperator::MULTIPLY, CModel::number, CCopasiDataModel::ObjectFromName(), CFunctionParameter::PARAMETER, pCOPASIDATAMODEL, CEvaluationNodeOperator::PLUS, CModelEntity::REACTIONS, CModel::s, CCopasiVector< T >::size(), CFunctionParameter::SUBSTRATE, CEvaluationNode::subType(), and CFunctionParameter::VOLUME.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModelValue->getInitialExpression() != "");
   const CExpression* pExpr = pModelValue->getInitialExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("InitialParticleNumber"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pA);
   // check the reactions
   CPPUNIT_ASSERT(pModel->getReactions().size() == 2);
   const CReaction* pReaction1 = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction1 != NULL);
   CPPUNIT_ASSERT(pReaction1->isReversible() == false);
   // check the kinetic law
   const CFunction* pKineticFunction = pReaction1->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   const CMassAction* pMassAction = dynamic_cast<const CMassAction*>(pKineticFunction);
   //FTB: this no longer is recognized as mass action reaction because of the
   //     special case of a species with hOSU
   CPPUNIT_ASSERT(pMassAction == NULL);
   const CChemEq* pChemEq = &pReaction1->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   const CChemEqElement* pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 0);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   const CReaction* pReaction2 = pModel->getReactions()[1];
   CPPUNIT_ASSERT(pReaction2 != NULL);
   CPPUNIT_ASSERT(pReaction2->isReversible() == false);
   // check the kinetic law
   pKineticFunction = pReaction2->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   CPPUNIT_ASSERT(pKineticFunction->getObjectName() == std::string("Function for reaction_1"));
   const CFunctionParameters* pFunctionParameters = &pKineticFunction->getVariables();
   CPPUNIT_ASSERT(pFunctionParameters->size() == 4);
   const CFunctionParameter* pFunctionParameter = (*pFunctionParameters)[0];
   CPPUNIT_ASSERT(pFunctionParameter != NULL);
   CPPUNIT_ASSERT(pFunctionParameter->getType() == CFunctionParameter::FLOAT64);
   CPPUNIT_ASSERT(pFunctionParameter->getUsage() == CFunctionParameter::PARAMETER);
   pFunctionParameter = (*pFunctionParameters)[1];
   CPPUNIT_ASSERT(pFunctionParameter != NULL);
   CPPUNIT_ASSERT(pFunctionParameter->getType() == CFunctionParameter::FLOAT64);
   CPPUNIT_ASSERT(pFunctionParameter->getUsage() == CFunctionParameter::PARAMETER);
   pFunctionParameter = (*pFunctionParameters)[2];
   CPPUNIT_ASSERT(pFunctionParameter != NULL);
   CPPUNIT_ASSERT(pFunctionParameter->getType() == CFunctionParameter::FLOAT64);
   CPPUNIT_ASSERT(pFunctionParameter->getUsage() == CFunctionParameter::VOLUME);
   pFunctionParameter = (*pFunctionParameters)[3];
   CPPUNIT_ASSERT(pFunctionParameter != NULL);
   CPPUNIT_ASSERT(pFunctionParameter->getType() == CFunctionParameter::FLOAT64);
   CPPUNIT_ASSERT(pFunctionParameter->getUsage() == CFunctionParameter::SUBSTRATE);
   pNode = pKineticFunction->getRoot();
   const CEvaluationNodeCall* pCallNode = dynamic_cast<const CEvaluationNodeCall*>(pNode);
   CPPUNIT_ASSERT(pCallNode != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeCall::SubType)CEvaluationNode::subType(pCallNode->getType())) == CEvaluationNodeCall::FUNCTION);
   CPPUNIT_ASSERT(pCallNode->getData() == std::string("Henri-Michaelis-Menten (irreversible)_2"));
   const CEvaluationNodeOperator* pOperatorNode = dynamic_cast<const CEvaluationNodeOperator*>(pCallNode->getChild());
   CPPUNIT_ASSERT(pOperatorNode != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pOperatorNode->getType())) == CEvaluationNodeOperator::MULTIPLY);
   const CEvaluationNodeVariable* pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pOperatorNode->getChild());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 3);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pOperatorNode->getChild()->getSibling());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 2);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pCallNode->getChild()->getSibling());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 0);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pCallNode->getChild()->getSibling()->getSibling());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 1);
   pKineticFunction = dynamic_cast<const CFunction*>(pCallNode->getCalledTree());
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   CPPUNIT_ASSERT(pKineticFunction->getObjectName() == std::string("Henri-Michaelis-Menten (irreversible)_2"));
   pNode = pKineticFunction->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   pOperatorNode = dynamic_cast<const CEvaluationNodeOperator*>(pNode);
   CPPUNIT_ASSERT(pOperatorNode != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pOperatorNode->getType())) == CEvaluationNodeOperator::DIVIDE);
   const CEvaluationNodeOperator* pOperatorNode2 = dynamic_cast<const CEvaluationNodeOperator*>(pOperatorNode->getChild());
   CPPUNIT_ASSERT(pOperatorNode2 != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeOperator::SubType)CEvaluationNodeOperator::subType(pOperatorNode2->getType())) == CEvaluationNodeOperator::MULTIPLY);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pOperatorNode2->getChild());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 2);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pOperatorNode2->getChild()->getSibling());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 0);
   pOperatorNode2 = dynamic_cast<const CEvaluationNodeOperator*>(pOperatorNode->getChild()->getSibling());
   CPPUNIT_ASSERT(pOperatorNode2 != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeOperator::SubType)CEvaluationNodeOperator::subType(pOperatorNode2->getType())) == CEvaluationNodeOperator::PLUS);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pOperatorNode2->getChild());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 1);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pOperatorNode2->getChild()->getSibling());
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getIndex() == 0);
   // check the function parameters one should be the reference to the substrate
   pChemEq = &pReaction2->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 1);
   pElement = pChemEq->getProducts()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pB);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   const std::vector<std::vector<std::string> > parameterMappings = pReaction2->getParameterMappings();
   CPPUNIT_ASSERT(parameterMappings.size() == 4);
   CPPUNIT_ASSERT(parameterMappings[2].size() == 1);
   std::string parameterKey = parameterMappings[2][0];
   CPPUNIT_ASSERT(parameterKey == pCompartment->getKey());
   CPPUNIT_ASSERT(parameterMappings[3].size() == 1);
   parameterKey = parameterMappings[3][0];
   CPPUNIT_ASSERT(parameterKey == pA->getKey());
 }
Member Data Documentation
const char * test000043::MODEL_STRING static protected
Definition at line 31 of file test000043.h.
Referenced by test_hasOnlySubstanceUnits().
CCopasiDataModel * test000043::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000043.h.
Referenced by setUp(), and test_hasOnlySubstanceUnits().
The documentation for this class was generated from the following files:
test000043.h
test000043.cpp