COPASI API: CCallParameters< Type > Class Template Reference
CCallParameters< Type > Class Template Reference
#include <CCallParameters.h>
Classes
union UType
Public Types
typedef std::vector< UType >
::const_iterator const_iterator
Public Member Functions
const_iterator begin () const
CCallParameters (const size_t &size=0)
CCallParameters (const CCallParameters &src)
void clear ()
const_iterator end () const
UType & operator[] (const size_t &index)
const UType & operator[] (const size_t &index) const
void push_back (const Type *value)
void push_back (CCallParameters< Type > *vector)
void resize (const size_t &size)
size_t size () const
~CCallParameters ()
Detailed Description
template<typename Type>
class CCallParameters< Type >
CFunctionParameterMap
Created for Copasi by Stefan Hoops (C) Stefan Hoops 2002 CCallParameterPointers
This is what is actually passed to a function. Some of the void* can be pointers to vector<const CCopasiObject*>
Definition at line 40 of file CCallParameters.h.
Member Typedef Documentation
template<typename Type> typedef std::vector< UType >::const_iterator CCallParameters< Type >::const_iterator
Definition at line 50 of file CCallParameters.h.
Constructor & Destructor Documentation
template<typename Type> CCallParameters< Type >::CCallParameters (const size_t & size = 0) inline
Definition at line 54 of file CCallParameters.h.
                                           :
       std::vector<void *>(size)
   {}
template<typename Type> CCallParameters< Type >::CCallParameters (const CCallParameters< Type > & src) inline
Definition at line 58 of file CCallParameters.h.
                                               :
       std::vector<void *>(src)
   {}
template<typename Type> CCallParameters< Type >::~CCallParameters () inline
Definition at line 62 of file CCallParameters.h.
 {}
Member Function Documentation
template<typename Type> const_iterator CCallParameters< Type >::begin () const inline
Definition at line 94 of file CCallParameters.h.
Referenced by CMassAction::calcValue(), CFunction::calcValue(), CMathExpression::CMathExpression(), CMathExpression::createMassActionPart(), CMassAction::dependsOn(), and CFunction::dependsOn().
   {return ((std::vector<UType> *) this)->begin();}
template<typename Type> void CCallParameters< Type >::clear () inline
Definition at line 82 of file CCallParameters.h.
Referenced by CFunctionParameterMap::clearCallParameter(), and CFunctionParameterMap::clearCallParameters().
   {((std::vector<void *> *) this)->clear();}
template<typename Type> const_iterator CCallParameters< Type >::end () const inline
Definition at line 97 of file CCallParameters.h.
Referenced by CMassAction::calcValue(), CMathExpression::CMathExpression(), CMathExpression::createMassActionPart(), CMassAction::dependsOn(), CFunction::dependsOn(), and CCallParameters< CCopasiObject >::resize().
   {return ((std::vector<UType> *) this)->end();}
template<typename Type> UType& CCallParameters< Type >::operator[] (const size_t & index) inline
Definition at line 88 of file CCallParameters.h.
   {return (*(std::vector< UType > *)this)[index];}
template<typename Type> const UType& CCallParameters< Type >::operator[] (const size_t & index) const inline
Definition at line 91 of file CCallParameters.h.
   {return (*(const std::vector< UType > *)this)[index];}
template<typename Type> void CCallParameters< Type >::push_back (const Type * value) inline
Definition at line 76 of file CCallParameters.h.
Referenced by CFunctionParameterMap::addCallParameter().
   {((std::vector<const Type *> *) this)->push_back(value);}
template<typename Type> void CCallParameters< Type >::push_back (CCallParameters< Type > * vector) inline
Definition at line 79 of file CCallParameters.h.
   {((std::vector<void *> *) this)->push_back(vector);}
template<typename Type> void CCallParameters< Type >::resize (const size_t & size) inline
Definition at line 64 of file CCallParameters.h.
Referenced by CFunctionParameterMap::initCallParameters().
   {
     ((std::vector<void *> *) this)->resize(size);
     std::vector<void *>::iterator it
     = ((std::vector<void *> *) this)->begin();
     typename std::vector<void *>::iterator end
     = ((std::vector<void *> *) this)->end();
     for (; it != end; ++it) *it = NULL;
   }
template<typename Type> size_t CCallParameters< Type >::size () const inline
Definition at line 85 of file CCallParameters.h.
Referenced by CFunctionParameterMap::checkCallParameters(), CFunctionParameterMap::getObjects(), and main().
   {return ((std::vector<void *> *) this)->size();}
The documentation for this class was generated from the following file:
CCallParameters.h