COPASI API: CQGLLayoutViewer Class Reference
CQGLLayoutViewer Class Reference
#include <CQGLLayoutViewer.h>
Public Slots
void slotRevertCurve ()
void updateWidget ()
Signals
void documentChanged ()
void singleCurveSelected (bool selected)
Public Member Functions
void change_style (const CLRenderInformationBase *pRenderInfo, bool defaultStyle=false)
CQGLLayoutViewer (QWidget *pParent=0, Qt::WindowFlags f=0)
double fitToScreen ()
CQGLLayoutPainter * getPainter ()
const CQGLLayoutPainter * getPainter () const
void restoreDeducedRoles ()
void revertDeducedRoles ()
void setZoomFactor (double zoom)
void update (const CCopasiDataModel *pDataModel, CLayout *pLayout, const CLRenderInformationBase *pRenderInfo, const QString &baseDir)
virtual ~CQGLLayoutViewer ()
Protected Slots
void slotDocumentChanged ()
void slotHValueChanged (int value)
void slotSingleCurveSelected (bool selected)
void slotVValueChanged (int value)
Protected Member Functions
void resetView ()
virtual void resizeEvent (QResizeEvent *e)
void updateScrollbars ()
Protected Attributes
QScrollBar * mpHorizontalScrollbar
CQGLLayoutPainter * mpLayoutPainter
QScrollBar * mpVerticalScrollbar
Detailed Description
This class is supposed to act as a sort of scrollview for a CQGLNetworkPainter.
Definition at line 20 of file CQGLLayoutViewer.h.
Constructor & Destructor Documentation
CQGLLayoutViewer::CQGLLayoutViewer (QWidget * pParent = 0, Qt::WindowFlags f = 0)
Constructor.
Definition at line 18 of file CQGLLayoutViewer.cpp.
References documentChanged(), mpHorizontalScrollbar, mpLayoutPainter, mpVerticalScrollbar, singleCurveSelected(), slotDocumentChanged(), slotHValueChanged(), slotSingleCurveSelected(), slotVValueChanged(), and TRUE.
                                                                    : QFrame(pParent, f)
 {
   QVBoxLayout* pVBoxLayout = new QVBoxLayout(this);
   this->setLayout(pVBoxLayout);
   pVBoxLayout->setContentsMargins(0, 0, 0, 0);
   QFrame* pHBox = new QFrame(this);
   QHBoxLayout* pHBoxLayout = new QHBoxLayout(pHBox);
   pHBox->setLayout(pHBoxLayout);
   pHBoxLayout->setContentsMargins(0, 0, 0, 0);
   // the QGLformat needs to enable sample buffers, otherwise
   // there is no anti aliasing
   QGLFormat format(QGL::SampleBuffers);
   format.setDoubleBuffer(TRUE);
   this->mpLayoutPainter = new CQGLLayoutPainter(format, pHBox);
   pHBoxLayout->addWidget(this->mpLayoutPainter);
   this->mpVerticalScrollbar = new QScrollBar(Qt::Vertical, pHBox);
   this->mpVerticalScrollbar->setSingleStep(1);
   pHBoxLayout->addWidget(this->mpVerticalScrollbar);
   pVBoxLayout->addWidget(pHBox);
   this->mpHorizontalScrollbar = new QScrollBar(Qt::Horizontal, this);
   this->mpHorizontalScrollbar->setSingleStep(1);
   pVBoxLayout->addWidget(this->mpHorizontalScrollbar);
   connect(this->mpVerticalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotVValueChanged(int)));
   connect(this->mpHorizontalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotHValueChanged(int)));
   connect(this->mpLayoutPainter, SIGNAL(documentChanged()), this, SLOT(slotDocumentChanged()));
   connect(this->mpLayoutPainter, SIGNAL(singleCurveSelected(bool)), this, SLOT(slotSingleCurveSelected(bool)));
 }
CQGLLayoutViewer::~CQGLLayoutViewer () virtual
Destructor.
Definition at line 49 of file CQGLLayoutViewer.cpp.
 {}
Member Function Documentation
void CQGLLayoutViewer::change_style (const CLRenderInformationBase * pRenderInfo, bool defaultStyle = false)
The default style indicates that the passed in render information is a default style. The renderer uses this information to determine whether roles for species reference glyphs need to be deduced.
Definition at line 185 of file CQGLLayoutViewer.cpp.
References CQGLLayoutPainter::change_style(), and mpLayoutPainter.
Referenced by CQNewMainWindow::change_style(), and CQNewMainWindow::updateRenderer().
 {
   this->mpLayoutPainter->change_style(pRenderInfo, defaultStyle);
 }
void CQGLLayoutViewer::documentChanged () signal
Referenced by CQGLLayoutViewer(), and slotDocumentChanged().
double CQGLLayoutViewer::fitToScreen ()
Calculates the ratio that is needed to fit the diagram on the current viewport and sets this as the zoom factor. The methods returns the new zoom factor.
Calculates the ratio that is needed to fit the diagram on the current viewport and sets this as the zoom factor. The methods return the newly calculated zoom factor.
Definition at line 163 of file CQGLLayoutViewer.cpp.
References CQGLLayoutPainter::fitToScreen(), mpLayoutPainter, and updateScrollbars().
Referenced by CQNewMainWindow::slotFitToScreen().
 {
   double zoom = this->mpLayoutPainter->fitToScreen();
   this->updateScrollbars();
   return zoom;
 }
CQGLLayoutPainter * CQGLLayoutViewer::getPainter ()
Returns a pointer to the OpenGL painter.
Definition at line 220 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter.
Referenced by CQNewMainWindow::changeColorSlot(), CQNewMainWindow::CQNewMainWindow(), CQNewMainWindow::elementaryModeTriggeredSlot(), CQNewMainWindow::export_bitmap(), CQNewMainWindow::fogDensitySlot(), CQNewMainWindow::redrawNow(), CQNewMainWindow::slotCalculateDimensions(), CQNewMainWindow::slotScreenshot(), and CQNewMainWindow::toggleHighlightSlot().
 {
   return this->mpLayoutPainter;
 }
const CQGLLayoutPainter * CQGLLayoutViewer::getPainter () const
Returns a const pointer to the OpenGL painter.
Definition at line 228 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter.
 {
   return this->mpLayoutPainter;
 }
void CQGLLayoutViewer::resetView () protected
Definition at line 150 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter, CQGLLayoutPainter::resetView(), and updateScrollbars().
 {
   // TODO disconnect the scrollbar listeners
   // so that the display is only redrawn once
   this->mpLayoutPainter->resetView();
   this->updateScrollbars();
 }
void CQGLLayoutViewer::resizeEvent (QResizeEvent * e) protected virtual
Definition at line 52 of file CQGLLayoutViewer.cpp.
References updateScrollbars().
 {
   this->updateScrollbars();
   QFrame::resizeEvent(e);
 }
void CQGLLayoutViewer::restoreDeducedRoles ()
Restores te deduced object roles after they have been temporarily reverted by a call to revertDeducedRoles.
void CQGLLayoutViewer::revertDeducedRoles ()
This method tells the painter to temporarily revert the deduced object roles. The painter will however remember the rolls and a call to restoreDeducedRoles will restore them.
void CQGLLayoutViewer::setZoomFactor (double zoom)
Sets the zoom factor on the network painter and updates the scrollbars.
Definition at line 58 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter, CQGLLayoutPainter::setZoomFactor(), CQGLLayoutPainter::update(), and updateScrollbars().
Referenced by CQNewMainWindow::slotFitToScreen(), CQNewMainWindow::slotResetView(), CQNewMainWindow::slotZoomChanged(), and CQNewMainWindow::slotZoomMenuItemActivated().
 {
   this->mpLayoutPainter->setZoomFactor(zoom);
   this->updateScrollbars();
   this->mpLayoutPainter->update();
 }
void CQGLLayoutViewer::singleCurveSelected (bool selected) signal
Referenced by CQGLLayoutViewer(), and slotSingleCurveSelected().
void CQGLLayoutViewer::slotDocumentChanged () protected slot
This slot is called when the layout painter changes the document (layout).
Definition at line 194 of file CQGLLayoutViewer.cpp.
References documentChanged().
Referenced by CQGLLayoutViewer().
 {
   emit documentChanged();
 }
void CQGLLayoutViewer::slotHValueChanged (int value) protected slot
Definition at line 143 of file CQGLLayoutViewer.cpp.
References CQGLLayoutPainter::getZoomFactor(), CQGLLayoutPainter::minX(), mpLayoutPainter, and CQGLLayoutPainter::setCurrentPositionX().
Referenced by CQGLLayoutViewer(), and updateScrollbars().
 {
   double minX = this->mpLayoutPainter->minX();
   double zoom = this->mpLayoutPainter->getZoomFactor();
   this->mpLayoutPainter->setCurrentPositionX((double)(minX + value / zoom));
 }
void CQGLLayoutViewer::slotRevertCurve () slot
This slot is called when the user initiates the action to revert the currently selected curve.
Definition at line 212 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter, and CQGLLayoutPainter::revertCurve().
 {
   this->mpLayoutPainter->revertCurve();
 }
void CQGLLayoutViewer::slotSingleCurveSelected (bool selected) protected slot
This slot is called when the selection changes. The value determines whether a single curve is selected or not.
Definition at line 203 of file CQGLLayoutViewer.cpp.
References singleCurveSelected().
Referenced by CQGLLayoutViewer().
 {
   emit singleCurveSelected(selected);
 }
void CQGLLayoutViewer::slotVValueChanged (int value) protected slot
Definition at line 136 of file CQGLLayoutViewer.cpp.
References CQGLLayoutPainter::getZoomFactor(), CQGLLayoutPainter::minY(), mpLayoutPainter, and CQGLLayoutPainter::setCurrentPositionY().
Referenced by CQGLLayoutViewer(), and updateScrollbars().
 {
   double minY = this->mpLayoutPainter->minY();
   double zoom = this->mpLayoutPainter->getZoomFactor();
   this->mpLayoutPainter->setCurrentPositionY((double)(minY + value / zoom));
 }
void CQGLLayoutViewer::update (const CCopasiDataModel * pDataModel, CLayout * pLayout, const CLRenderInformationBase * pRenderInfo, const QString & baseDir)
Definition at line 175 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter, CQGLLayoutPainter::update(), and updateScrollbars().
Referenced by CQNewMainWindow::updateRenderer().
 {
   // pass the options on to the layout painter
   if (pRenderInfo)
     {
       this->mpLayoutPainter->update(pDatamodel, pLayout, pRenderInfo, baseDir);
       this->updateScrollbars();
     }
 }
void CQGLLayoutViewer::updateScrollbars () protected
Definition at line 65 of file CQGLLayoutViewer.cpp.
References CQGLLayoutPainter::getZoomFactor(), CQGLLayoutPainter::maxX(), CQGLLayoutPainter::maxY(), CQGLLayoutPainter::minX(), CQGLLayoutPainter::minY(), mpHorizontalScrollbar, mpLayoutPainter, mpVerticalScrollbar, CQGLLayoutPainter::setCurrentPositionX(), CQGLLayoutPainter::setCurrentPositionY(), slotHValueChanged(), and slotVValueChanged().
Referenced by fitToScreen(), resetView(), resizeEvent(), setZoomFactor(), and update().
 {
   // reset the scollbar range
   // disconnect the scrollbar listeners and handle the update so that the GL
   // window is only redrawn once
   double zoom = this->mpLayoutPainter->getZoomFactor();
   double maxX = this->mpLayoutPainter->maxX();
   double maxY = this->mpLayoutPainter->maxY();
   double minX = this->mpLayoutPainter->minX();
   double minY = this->mpLayoutPainter->minY();
   double graphWidth = (maxX - minX) * zoom;
   double graphHeight = (maxY - minY) * zoom;
   double rectangleHeight = this->mpLayoutPainter->contentsRect().height();
   double rectangleWidth = this->mpLayoutPainter->contentsRect().width();
   disconnect(this->mpVerticalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotVValueChanged(int)));
   disconnect(this->mpHorizontalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotHValueChanged(int)));
   if (graphHeight < rectangleHeight)
     {
       this->mpVerticalScrollbar->hide();
       this->mpVerticalScrollbar->setValue(0);
       this->mpLayoutPainter->setCurrentPositionY(minY);
     }
   else
     {
       this->mpVerticalScrollbar->setPageStep(rectangleHeight);
       int oldMaximum = this->mpVerticalScrollbar->maximum();
       int newMaximum = (int)(graphHeight - rectangleHeight);
       int oldValue = this->mpVerticalScrollbar->value();
       int newValue = 0;
       if (oldValue != 0 && oldMaximum != 0)
         {
           newValue = (int)((double) oldValue * (double) newMaximum / (double) oldMaximum);
         }
       this->mpVerticalScrollbar->setRange(0, newMaximum);
       this->mpVerticalScrollbar->setValue(newValue);
       this->mpLayoutPainter->setCurrentPositionY((double)(minY + newValue / zoom));
       this->mpVerticalScrollbar->show();
     }
   if (graphWidth < rectangleWidth)
     {
       this->mpHorizontalScrollbar->hide();
       this->mpHorizontalScrollbar->setValue(0);
       this->mpLayoutPainter->setCurrentPositionX(minX);
     }
   else
     {
       this->mpHorizontalScrollbar->setPageStep(rectangleWidth);
       int oldMaximum = this->mpHorizontalScrollbar->maximum();
       int newMaximum = (int)(graphWidth - rectangleWidth);
       int oldValue = this->mpHorizontalScrollbar->value();
       int newValue = 0;
       if (oldValue != 0 && oldMaximum != 0)
         {
           newValue = (int)((double) oldValue * (double) newMaximum / (double) oldMaximum);
         }
       this->mpHorizontalScrollbar->setRange(0, newMaximum);
       this->mpHorizontalScrollbar->setValue(newValue);
       this->mpLayoutPainter->setCurrentPositionX((double)(minX + newValue / zoom));
       this->mpHorizontalScrollbar->show();
     }
   connect(this->mpVerticalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotVValueChanged(int)));
   connect(this->mpHorizontalScrollbar, SIGNAL(valueChanged(int)), this, SLOT(slotHValueChanged(int)));
 }
void CQGLLayoutViewer::updateWidget () slot
Definition at line 170 of file CQGLLayoutViewer.cpp.
References mpLayoutPainter, and CQGLLayoutPainter::update().
 {
   this->mpLayoutPainter->update();
 }
Member Data Documentation
QScrollBar* CQGLLayoutViewer::mpHorizontalScrollbar protected
Definition at line 26 of file CQGLLayoutViewer.h.
Referenced by CQGLLayoutViewer(), and updateScrollbars().
CQGLLayoutPainter* CQGLLayoutViewer::mpLayoutPainter protected
Definition at line 27 of file CQGLLayoutViewer.h.
Referenced by change_style(), CQGLLayoutViewer(), fitToScreen(), getPainter(), resetView(), setZoomFactor(), slotHValueChanged(), slotRevertCurve(), slotVValueChanged(), update(), updateScrollbars(), and updateWidget().
QScrollBar* CQGLLayoutViewer::mpVerticalScrollbar protected
Definition at line 25 of file CQGLLayoutViewer.h.
Referenced by CQGLLayoutViewer(), and updateScrollbars().
The documentation for this class was generated from the following files:
CQGLLayoutViewer.h
CQGLLayoutViewer.cpp