COPASI API: CTableauMatrix Class Reference
CTableauMatrix Class Reference
#include <CTableauMatrix.h>
Public Member Functions
void addLine (const CTableauLine *src, const bool &check=true)
std::list< const CTableauLine * >
::iterator begin ()
std::list< const CTableauLine * >
::const_iterator begin () const
CTableauMatrix ()
CTableauMatrix (const std::vector< std::vector< double > > &stoi, const size_t &reversibleNumber)
std::list< const CTableauLine * >
::iterator end ()
std::list< const CTableauLine * >
::const_iterator end () const
void removeLine (const std::list< const CTableauLine * >::iterator line)
size_t size () const
~CTableauMatrix ()
Private Member Functions
bool isValid (const CTableauLine *src)
Private Attributes
std::list< const CTableauLine * >
::iterator mFirstIrreversible
std::list< const CTableauLine * > mLine
Friends
std::ostream & operator<< (std::ostream &, const CTableauMatrix &)
Detailed Description
CTableauMatrix class. Used to calculate elementary flux modes
Created for Copasi by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 37 of file CTableauMatrix.h.
Constructor & Destructor Documentation
CTableauMatrix::CTableauMatrix ()
Default constructor
CTableauMatrix class. Used to calculate elementary flux modes
Created for Copasi by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 36 of file CTableauMatrix.cpp.
                               :
     mLine(),
     mFirstIrreversible(mLine.end())
 {}
CTableauMatrix::CTableauMatrix (const std::vector< std::vector< double > > & stoi, const size_t & reversibleNumber)
Specific constructor The first reversibleNumber lines of stoi must be reversible reactions. Note: stoi is actually the transpose of the stoichiometry matrix
Parameters
const std::vector < std::vector < double > > & stoi
const size_t & reversibleNumber
CTableauMatrix::~CTableauMatrix ()
Destructor
Definition at line 65 of file CTableauMatrix.cpp.
References mLine, and pdelete.
 {
   for (std::list< const CTableauLine * >::iterator i = mLine.begin();
        i != mLine.end(); i++)
     pdelete(*i);
 }
Member Function Documentation
void CTableauMatrix::addLine (const CTableauLine * src, const bool & check = true)
Add a line to the matrix
Parameters
const CTableauLine * src
const bool & check (Default: true)
Definition at line 95 of file CTableauMatrix.cpp.
References CTableauLine::isReversible(), isValid(), mFirstIrreversible, mLine, and pdelete.
Referenced by CEFMAlgorithm::calculateNextTableau().
 {
   /* First we check whether we have a valid new flux mode */
   if (!check || isValid(src))
     {
       if (src->isReversible())
         {
           mFirstIrreversible = mLine.insert(mFirstIrreversible, src);
           mFirstIrreversible++;
         }
       else if (mFirstIrreversible == mLine.end())
         {
           mFirstIrreversible = mLine.insert(mFirstIrreversible, src);
         }
       else
         {
           mLine.push_back(src);
         }
     }
   else
     pdelete(src);
 }
std::list< const CTableauLine * >::iterator CTableauMatrix::begin ()
Retrieves the first line from the matrix
Returns
list< const CTableauLine * >::iterator begin
Definition at line 75 of file CTableauMatrix.cpp.
References mLine.
Referenced by CEFMAlgorithm::buildFluxModes(), CEFMAlgorithm::calculateCombinations(), CEFMAlgorithm::calculateNextTableau(), and CEFMAlgorithm::CSpeciesOrderNode::update().
 {
   return mLine.begin();
 }
std::list< const CTableauLine * >::const_iterator CTableauMatrix::begin () const
Retrieves the first line from the matrix
Returns
list< const CTableauLine * >::const_iterator begin
Definition at line 80 of file CTableauMatrix.cpp.
References mLine.
 {
   return mLine.begin();
 }
std::list< const CTableauLine * >::iterator CTableauMatrix::end ()
Retrieves the last line from the matrix
Returns
list< const CTableauLine * >::iterator end
Definition at line 85 of file CTableauMatrix.cpp.
References mLine.
Referenced by CEFMAlgorithm::buildFluxModes(), CEFMAlgorithm::calculateCombinations(), CEFMAlgorithm::calculateNextTableau(), and CEFMAlgorithm::CSpeciesOrderNode::update().
 {
   return mLine.end();
 }
std::list< const CTableauLine * >::const_iterator CTableauMatrix::end () const
Retrieves the last line from the matrix
Returns
list< const CTableauLine * >::const_iterator end
Definition at line 90 of file CTableauMatrix.cpp.
References mLine.
 {
   return mLine.end();
 }
bool CTableauMatrix::isValid (const CTableauLine * src) private
Check whether the new line fullfills the constraints
Parameters
const CTableauLine * src
Definition at line 138 of file CTableauMatrix.cpp.
References CTableauLine::getScore(), mLine, and removeLine().
Referenced by addLine().
 {
   std::list< const CTableauLine * >::iterator i;
   std::list< const CTableauLine * >::iterator tmp;
   /* Check whether we have already better lines */
   for (i = mLine.begin(); i != mLine.end(); i++)
     if ((*i)->getScore() < src->getScore())
       return false;
   i = mLine.begin();
   /* Check whether the new line scores better than existing lines */
   /* If so the existing lines are removed */
   for (i = mLine.begin(); i != mLine.end();)
     if (src->getScore() < (*i)->getScore())
       {
         if (i == mLine.begin())
           {
             removeLine(i);
             i = mLine.begin();
           }
         else
           {
             tmp = i;
             tmp--;
             removeLine(i);
             i = tmp;
             i++;
           }
       }
     else
       i++;
   return true;
 }
void CTableauMatrix::removeLine (const std::list< const CTableauLine * >::iterator line)
Remove the indexed line of the matrix
Parameters
list< const CTableauLine * >::const_iterator line
Definition at line 119 of file CTableauMatrix.cpp.
References mFirstIrreversible, and mLine.
Referenced by CEFMAlgorithm::calculateNextTableau(), and isValid().
 {
   if (line == mFirstIrreversible && mFirstIrreversible == mLine.begin())
     {
       mLine.pop_front();
       mFirstIrreversible = mLine.begin();
     }
   else if (line == mFirstIrreversible)
     {
       mFirstIrreversible--;
       mLine.erase(line);
       mFirstIrreversible++;
     }
   else
     {
       mLine.erase(line);
     }
 }
size_t CTableauMatrix::size () const
Retrieve the number of tableau lines
Returns
size_t size
Definition at line 72 of file CTableauMatrix.cpp.
References mLine.
Referenced by CEFMAlgorithm::calculateNextTableau().
 {return mLine.size();}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CTableauMatrix & m) friend
Definition at line 176 of file CTableauMatrix.cpp.
 {
   os << "Tableau Matrix: Number of Lines = " << m.mLine.size() << std::endl;
   std::list< const CTableauLine * >::const_iterator i;
   for (i = m.mLine.begin(); i != m.mLine.end(); i++)
     {
       os << (**i);
     }
   return os;
 }
Member Data Documentation
std::list< const CTableauLine * >::iterator CTableauMatrix::mFirstIrreversible private
Iterator pointing to the first irreversible reaction
Definition at line 53 of file CTableauMatrix.h.
Referenced by addLine(), and removeLine().
std::list< const CTableauLine * > CTableauMatrix::mLine private
Vector containing the lines of the Matrix <{CTableauLine}> 0..*
Definition at line 48 of file CTableauMatrix.h.
Referenced by addLine(), begin(), end(), isValid(), operator<<(), removeLine(), size(), and ~CTableauMatrix().
The documentation for this class was generated from the following files:
CTableauMatrix.h
CTableauMatrix.cpp