COPASI API: CLayoutState.cpp File Reference
CLayoutState.cpp File Reference
#include <layout/CLayoutState.h>
#include <layout/CLBase.h>
#include <layout/CLCurve.h>
#include <layout/CLayout.h>
Macros
#define STATE_SET_POSITIONS(objectMap, it, endIt)
Functions
void tagKey (CLGraphicalObject *element)
Macro Definition Documentation
#define STATE_SET_POSITIONS (objectMap, it, endIt)
Value:
{\
    for (;it != endIt; ++it)\
      {\
        const std::string& key = ((*it)->getTag());\
        StringBoundMap::const_iterator boundIt = objectMap.find(key);\
        if (boundIt == objectMap.end()) \
          continue;    \
        CLBoundingBox* current = boundIt->second;\
        (*it)->setPosition(current->getPosition());\
      }\
  }
Definition at line 185 of file CLayoutState.cpp.
Referenced by CLayoutState::applyTo().
Function Documentation
void tagKey (CLGraphicalObject * element)
Definition at line 12 of file CLayoutState.cpp.
References CLGraphicalObject::getKey(), and CLBase::setTag().
Referenced by CLayoutState::tagLayout().
 {
   element->setTag(element->getKey());
 }