COPASI API: CObjectInterface Class Reference
CObjectInterface Class Reference abstract
#include <CCopasiObject.h>
Public Types
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CObjectInterface ()
virtual CCopasiObjectName getCN () const =0
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const =0
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const =0
virtual void * getValuePointer () const =0
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const =0
virtual void print (std::ostream *ostream) const =0
virtual ~CObjectInterface ()
Detailed Description
Definition at line 154 of file CCopasiObject.h.
Member Typedef Documentation
typedef std::set< const CObjectInterface * > CObjectInterface::ObjectSet
Definition at line 157 of file CCopasiObject.h.
typedef std::vector< CObjectInterface * > CObjectInterface::UpdateSequence
Definition at line 158 of file CCopasiObject.h.
Constructor & Destructor Documentation
CObjectInterface::CObjectInterface () inline
Constructor
Definition at line 163 of file CCopasiObject.h.
 {};
virtual CObjectInterface::~CObjectInterface () inline virtual
Destructor
Definition at line 168 of file CCopasiObject.h.
 {};
Member Function Documentation
virtual CCopasiObjectName CObjectInterface::getCN () const pure virtual
Retrieve the CN of the object
Returns
CCopasiObjectName
Implemented in CCopasiObject, CCopasiParameter, CMathContainer, CArrayElementReference, and CMathObject.
Referenced by CEvaluationNodeObject::compile(), CMathObject::createExtensiveValueExpression(), CMathObject::createIntensiveValueExpression(), CSBMLExporter::replaceSpeciesReferences(), and SBMLImporter::replaceTimeAndAvogadroNodeNames().
virtual const CObjectInterface* CObjectInterface::getObject (const CCopasiObjectName & cn) const pure virtual
Retrieve a descendant object by its CN.
Parameters
const CCopasiObjectName & cn
Returns
const CObjectInterface * pObject
Implemented in CCopasiVectorN< CType >, CCopasiVectorN< CReaction >, CCopasiVectorN< CEventAssignment >, CCopasiVectorN< CFunctionParameter >, CCopasiVectorN< CCopasiTask >, CCopasiVectorN< CPlotSpecification >, CCopasiVectorN< CCompartment >, CCopasiVectorN< CModelParameterSet >, CCopasiVectorN< CEvent >, CCopasiVectorN< CMetab >, CCopasiVectorN< CFunction >, CCopasiVectorN< CModelValue >, CCopasiVectorN< CReportDefinition >, CCopasiVector< T >, CCopasiVector< CLGlobalRenderInformation >, CCopasiVector< CModification >, CCopasiVector< CLMetabGlyph >, CCopasiVector< CLCompartmentGlyph >, CCopasiVector< CLReferenceGlyph >, CCopasiVector< CSlider >, CCopasiVector< CBiologicalDescription >, CCopasiVector< CLGlobalStyle >, CCopasiVector< CEventAssignment >, CCopasiVector< CReference >, CCopasiVector< CMathEvent::CAssignment >, CCopasiVector< CLayout >, CCopasiVector< CLGradientStop >, CCopasiVector< CLMetabReferenceGlyph >, CCopasiVector< CMoiety >, CCopasiVector< CType >, CCopasiVector< CChemEqElement >, CCopasiVector< CLColorDefinition >, CCopasiVector< CLReactionGlyph >, CCopasiVector< CEvent >, CCopasiVector< CMathEvent >, CCopasiVector< CLGradientBase >, CCopasiVector< CLLocalRenderInformation >, CCopasiVector< CMetab >, CCopasiVector< CPlotItem >, CCopasiVector< CCopasiDataModel >, CCopasiVector< CLLineEnding >, CCopasiVector< CFittingPoint >, CCopasiVector< CLTextGlyph >, CCopasiVector< CCopasiObject >, CCopasiVector< CMathTrigger::CRootFinder >, CCopasiVector< CLLocalStyle >, CCopasiVector< CCreator >, CCopasiVector< CLGraphicalObject >, CCopasiVector< CMetabOld >, CCopasiVector< CLGeneralGlyph >, CCopasiObject, CReaction, CArrayAnnotation, CMathContainer, CCopasiParameterGroup, CCopasiContainer, and CMathObject.
Referenced by CMathDependencyGraph::exportDOTFormat(), and CCopasiContainer::getObject().
virtual const CObjectInterface::ObjectSet& CObjectInterface::getPrerequisites () const pure virtual
Retrieve the prerequisites, i.e., the objects which need to be evaluated before this.
Returns
const CObjectInterface::ObjectSet & prerequisites
Implemented in CCopasiObject, CParticleReference, CMathExpression, and CMathObject.
Referenced by CMathDependencyGraph::addObject().
virtual void* CObjectInterface::getValuePointer () const pure virtual
Retrieve a pointer to the value of the object
Implemented in CCopasiObject, CCopasiParameter, CMetab, CCopasiMatrixReference< CType >, CCopasiVectorReference< CType >, CModelEntity, CCopasiTimer, CMathObject, CArrayElementReference, CCopasiObjectReference< CType >, and CCopasiObjectReference< C_FLOAT64 >.
Referenced by CEvaluationNodeObject::compile(), and CMathContainer::createNodeFromObject().
virtual bool CObjectInterface::isPrerequisiteForContext (const CObjectInterface * pObject, const CMath::SimulationContextFlag & context, const CObjectInterface::ObjectSet & changedObjects) const pure virtual
Check whether a given object is a prerequisite for a context.
Parameters
const CObjectInterface * pObject
const CMath::SimulationContextFlag & context
const CObjectInterface::ObjectSet & changedObjects
Returns
bool isPrerequisiteForContext
Implemented in CCopasiObject, CParticleReference, CDependentNumberReference, CConcentrationReference, CMathObject, and CTotalNumberReference.
Referenced by CMathDependencyNode::updateDependentState(), and CMathDependencyNode::updatePrerequisiteState().
virtual void CObjectInterface::print (std::ostream * ostream) const pure virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Implemented in CCopasiParameterGroup, CLReactionGlyph, COptProblem, CLGeneralGlyph, CCopasiObject, CEigen, CCopasiParameter, CArrayAnnotation, CLMetabReferenceGlyph, CCopasiVectorReference< CType >, CCopasiMethod, CLayout, CLTextGlyph, CCopasiProblem, CCopasiTask::CResult, CSteadyStateTask, CSensProblem, CCrossSectionProblem, CLGraphicalObject, CCopasiTask::CDescription, CLReferenceGlyph, CLNAProblem, CMCAProblem, CFitProblem, CSensTask, CLCompartmentGlyph, CCopasiTimer, CMathObject, CArrayElementReference, COscillationProblem, CCopasiObjectReference< CType >, CCopasiObjectReference< C_FLOAT64 >, CLMetabGlyph, CLGlyphWithCurve, and CCopasiStaticString.
The documentation for this class was generated from the following file:
CCopasiObject.h