COPASI API: CQLayoutView.cpp File Reference
CQLayoutView.cpp File Reference
#include <QtGui/QApplication>
#include <QtGui/QWheelEvent>
#include <QtGui/QAction>
#include <QtGui/QMenu>
#include <QtGui/QToolBar>
#include <QtCore/QFileInfo>
#include <QtGui/QHBoxLayout>
#include <QtGui/QLabel>
#include <QtGui/QComboBox>
#include <qlayout/CQLayoutScene.h>
#include <qlayout/CQLayoutView.h>
#include <copasi.h>
#include <layout/CLayout.h>
#include <layout/CListOfLayouts.h>
#include <layout/CLDefaultStyles.h>
#include <CopasiDataModel/CCopasiDataModel.h>
#include <resourcesUI/CQIconResource.h>
Macros
#define RENDERINFORMATION_TYPE_DEFAULT 2
#define RENDERINFORMATION_TYPE_GLOBAL 0
#define RENDERINFORMATION_TYPE_LOCAL 1
Functions
void updateLayoutList (QComboBox *list, CCopasiDataModel *dataModel)
CLRenderInformationBase * updateRenderInformationList (QComboBox *list, CCopasiDataModel *dataModel, CLayout *layout)
Macro Definition Documentation
#define RENDERINFORMATION_TYPE_DEFAULT 2
Definition at line 48 of file CQLayoutView.cpp.
Referenced by updateRenderInformationList().
#define RENDERINFORMATION_TYPE_GLOBAL 0
Definition at line 46 of file CQLayoutView.cpp.
Referenced by updateRenderInformationList().
#define RENDERINFORMATION_TYPE_LOCAL 1
Definition at line 47 of file CQLayoutView.cpp.
Referenced by updateRenderInformationList().
Function Documentation
void updateLayoutList (QComboBox * list, CCopasiDataModel * dataModel)
Definition at line 30 of file CQLayoutView.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CCopasiDataModel::getListOfLayouts(), and CCopasiObject::getObjectName().
Referenced by CQLayoutView::setDataModel().
 {
   if (list == NULL || dataModel == NULL) return;
   list->clear();
   CCopasiVector<CLayout> & layouts = *dataModel->getListOfLayouts();
   CCopasiVector<CLayout>::iterator it = layouts.begin();
   while (it != layouts.end())
     {
       const CLayout* layout = *it;
       list->addItem(layout->getObjectName().c_str());
       ++it;
     }
 }
CLRenderInformationBase* updateRenderInformationList (QComboBox * list, CCopasiDataModel * dataModel, CLayout * layout)
Definition at line 50 of file CQLayoutView.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), getDefaultStyle(), CLRenderInformationBase::getKey(), CListOfLayouts::getListOfGlobalRenderInformationObjects(), CCopasiDataModel::getListOfLayouts(), CLayout::getListOfLocalRenderInformationObjects(), CLRenderInformationBase::getName(), getNumDefaultStyles(), RENDERINFORMATION_TYPE_DEFAULT, RENDERINFORMATION_TYPE_GLOBAL, RENDERINFORMATION_TYPE_LOCAL, and CCopasiVector< T >::size().
Referenced by CQLayoutView::setDataModel(), and CQLayoutView::slotLayoutChanged().
 {
   if (list == NULL || dataModel == NULL) return NULL;
   bool skipGlobal = list->count() > 0;
   CLRenderInformationBase* result = NULL;
   // remove oldItems
   if (skipGlobal)
     {
       for (size_t i = list->count(); i > 0; --i)
         {
           QString current = list->itemText(i - 1);
           int type = list->itemData(i - 1).toInt();
           if (type == RENDERINFORMATION_TYPE_LOCAL)
             list->removeItem(i - 1);
         }
     }
   // add local information
   if (layout != NULL)
     {
       CCopasiVector<CLLocalRenderInformation> & render = layout->getListOfLocalRenderInformationObjects();
       CCopasiVector<CLLocalRenderInformation>::iterator it = render.begin();
       while (it != render.end())
         {
           CLLocalRenderInformation* current = *it;
           if (result == NULL) result = current;
           if (current->getName().empty())
             list->insertItem(0, current->getKey().c_str(), QVariant::fromValue(RENDERINFORMATION_TYPE_LOCAL));
           else
             list->insertItem(0, current->getName().c_str(), QVariant::fromValue(RENDERINFORMATION_TYPE_LOCAL));
           ++it;
         }
     }
   // bail
   if (skipGlobal)
     {
       if (result == NULL && dataModel->getListOfLayouts()->getListOfGlobalRenderInformationObjects().size() > 0)
         result = dataModel->getListOfLayouts()->getListOfGlobalRenderInformationObjects()[0];
       if (result == NULL && getNumDefaultStyles() > 0)
         result = getDefaultStyle(0);
       return result;
     }
   // add global ones
   {
     CCopasiVector<CLGlobalRenderInformation> & render = dataModel->getListOfLayouts()->getListOfGlobalRenderInformationObjects();
     CCopasiVector<CLGlobalRenderInformation>::const_iterator it = render.begin();
     while (it != render.end())
       {
         CLGlobalRenderInformation* current = *it;
         if (result == NULL) result = current;
         if (current->getName().empty())
           list->addItem(current->getKey().c_str(), QVariant::fromValue(RENDERINFORMATION_TYPE_GLOBAL));
         else
           list->addItem(current->getName().c_str(), QVariant::fromValue(RENDERINFORMATION_TYPE_GLOBAL));
         ++it;
       }
     // add default ones
     {
       size_t i, iMax = getNumDefaultStyles();
       CLRenderInformationBase* current = NULL;
       for (i = 0; i < iMax; ++i)
         {
           current = getDefaultStyle(i);
           if (result == NULL) result = current;
           std::string text = current->getKey();
           if (!current->getName().empty())
             {
               text = current->getName();
             }
           list->addItem(text.c_str(), QVariant::fromValue(RENDERINFORMATION_TYPE_DEFAULT));
         }
     }
   }
   return result;
 }