COPASI API: CLyapMethod Class Reference
CLyapMethod Class Reference abstract
#include <CLyapMethod.h>
Public Member Functions
virtual bool calculate ()=0
CLyapMethod (const CLyapMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (CLyapProblem *problem)
virtual void start (const CState *initialState)
virtual double step (const double &deltaT)
~CLyapMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CLyapMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::lyapWolf)
static bool isValidSubType (const CCopasiMethod::SubType &subType)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes
static const CLyapValidSubTypes ValidSubTypes
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Member Functions
CLyapMethod (const CCopasiMethod::SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
CLyapProblem * mpProblem
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CLyapMethod ()
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 47 of file CLyapMethod.h.
Constructor & Destructor Documentation
CLyapMethod::CLyapMethod () private
Default constructor.
CLyapMethod::CLyapMethod (const CCopasiMethod::SubType & subType, const CCopasiContainer * pParent = NULL) protected
Default constructor.
Parameters
const CCopasiMethod::SubType & subType
const CCopasiContainer * pParent (default: NULL)
Default constructor.
Definition at line 79 of file CLyapMethod.cpp.
References CONSTRUCTOR_TRACE.
                                                            :
     CCopasiMethod(CCopasiTask::lyap, subType, pParent),
     //mpCurrentState(NULL),
     mpProblem(NULL)
 {CONSTRUCTOR_TRACE;}
CLyapMethod::CLyapMethod (const CLyapMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CLyapMethod & src
const CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CLyapMethod & src
Definition at line 90 of file CLyapMethod.cpp.
References CONSTRUCTOR_TRACE.
                                                           :
     CCopasiMethod(src, pParent),
     //mpCurrentState(src.mpCurrentState),
     mpProblem(src.mpProblem)
 {CONSTRUCTOR_TRACE;}
CLyapMethod::~CLyapMethod ()
Destructor.
Definition at line 100 of file CLyapMethod.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
virtual bool CLyapMethod::calculate () pure virtual
Implemented in CLyapWolfMethod.
Referenced by CLyapTask::process().
CLyapMethod * CLyapMethod::createMethod (CCopasiMethod::SubType subType = CCopasiMethod::lyapWolf) static
Create a trajectory method for a special problem. Note: the returned object has to be released after use with delete a problem is also passed so that the method has a chance to choose an appropriate simulation method.
Definition at line 58 of file CLyapMethod.cpp.
References fatalError, CCopasiMethod::lyapWolf, and CCopasiMethod::unset.
Referenced by CLyapTask::CLyapTask(), CQLyapWidget::createMethod(), and CLyapTask::createMethod().
 {
   CLyapMethod * pMethod = NULL;
   switch (subType)
     {
       case unset:
       case lyapWolf:
         pMethod = new CLyapWolfMethod();
         break;
       default:
         fatalError();
     }
   return pMethod;
 }
bool CLyapMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
Reimplemented in CLyapWolfMethod.
Definition at line 140 of file CLyapMethod.cpp.
References C_INT32, CLyapProblem::divergenceRequested(), CCopasiMessage::ERROR, CLyapProblem::getExponentNumber(), CCopasiProblem::getModel(), CState::getNumIndependent(), CModel::getState(), CCopasiMethod::isValidProblem(), and MCLyap.
Referenced by CLyapWolfMethod::isValidProblem().
 {
   if (!CCopasiMethod::isValidProblem(pProblem)) return false;
   const CLyapProblem * pLP = dynamic_cast<const CLyapProblem *>(pProblem);
   if (!pLP)
     {
       //not a LyapProblem
       CCopasiMessage(CCopasiMessage::ERROR, MCLyap + 1);
       return false;
     }
   if ((!pLP->divergenceRequested()) && (pLP->getExponentNumber() < 1))
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCLyap + 2);
       return false;
     }
   unsigned C_INT32 tmp = (unsigned C_INT32) pLP->getModel()->getState().getNumIndependent();
   if (pLP->getExponentNumber() > tmp)
     {
       //to few exponents
       CCopasiMessage(CCopasiMessage::ERROR, MCLyap + 3, tmp, tmp);
       return false;
     }
   return true;
 }
bool CLyapMethod::isValidSubType (const CCopasiMethod::SubType & subType) static
Checks whether the given sub type is a valid method
Parameters
const CCopasiMethod::SubType & subType
Returns
bool isValidSubType
Definition at line 48 of file CLyapMethod.cpp.
Referenced by CLyapTask::setMethodType().
 {
   size_t i, imax = CLyapMethod::ValidSubTypes.size();
   for (i = 0; i < imax; i++)
     if (CLyapMethod::ValidSubTypes[i] == subType) return true;
   return false;
 }
void CLyapMethod::setProblem (CLyapProblem * problem)
Set a pointer to the current state. This method is used by CLyapTask::process() The results of the simulation are passed via this CState variable
Parameters
CState * currentState Set a pointer to the problem. This method is used by CLyap
CLyapProblem * problem
Set a pointer to the problem. This method is used by CLyap
Parameters
CLyapProblem * problem
Definition at line 113 of file CLyapMethod.cpp.
References mpProblem.
Referenced by CLyapTask::initialize().
 {mpProblem = problem;}
void CLyapMethod::start (const CState * initialState) virtual
This instructs the method to prepare for integration starting with the initialState given.
Parameters
const CState * initialState
This instructs the method to calculate a a time step of deltaT starting with the initialState given. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
double & deltaT
const CState * initialState
Returns
"const double &" actualDeltaT
Definition at line 136 of file CLyapMethod.cpp.
 {return;}
double CLyapMethod::step (const double & deltaT) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
This instructs the method to calculate a a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual timestep taken.
Parameters
const double & deltaT
Reimplemented in CLyapWolfMethod.
Definition at line 124 of file CLyapMethod.cpp.
 {return 0;}
Member Data Documentation
CLyapProblem* CLyapMethod::mpProblem protected
A pointer to the current state. This is set from outside with the setState() method and never changed anywhere else. Its used to report the results to the calling LyapTask A pointer to the trajectory problem.
Definition at line 74 of file CLyapMethod.h.
Referenced by CLyapWolfMethod::calculate(), CLyapWolfMethod::evalF(), setProblem(), and CLyapWolfMethod::start().
const CLyapValidSubTypes CLyapMethod::ValidSubTypes static
A list of valid trajectory method types;
Definition at line 53 of file CLyapMethod.h.
The documentation for this class was generated from the following files:
CLyapMethod.h
CLyapMethod.cpp