COPASI API: test_compare_utilities Class Reference
test_compare_utilities Class Reference
#include <test_compare_utilities.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_copasi_function_expansion ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_copasi_function_expansion)
CPPUNIT_TEST_SUITE (test_compare_utilities)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test_compare_utilities.h.
Member Function Documentation
test_compare_utilities::CPPUNIT_TEST (test_copasi_function_expansion) private
test_compare_utilities::CPPUNIT_TEST_SUITE (test_compare_utilities) private
test_compare_utilities::CPPUNIT_TEST_SUITE_END () private
void test_compare_utilities::setUp ()
Definition at line 25 of file test_compare_utilities.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(false, 0, NULL);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test_compare_utilities::tearDown ()
Definition at line 34 of file test_compare_utilities.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test_compare_utilities::test_copasi_function_expansion ()
Definition at line 39 of file test_compare_utilities.cpp.
References CEvaluationNodeCall::addChild(), CEvaluationNodeVariable::ANY, CEvaluationNodeOperator::DIVIDE, CEvaluationNodeNumber::DOUBLE, expand_function_calls(), CFunctionDB::findFunction(), CEvaluationNodeCall::FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiRootContainer::getFunctionList(), CCopasiObject::getObjectName(), CEvaluationNode::getType(), CFunction::getVariables(), load_cps_model_from_stream(), CEvaluationNodeOperator::MINUS, MODEL_STRING1, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::NUMBER, CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CEvaluationNodeOperator::PLUS, CFunctionParameters::size(), CEvaluationNode::subType(), CEvaluationNode::type(), and CEvaluationNode::VARIABLE.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;;
   std::istringstream iss(test_compare_utilities::MODEL_STRING1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CFunctionDB* pFunctionDB = CCopasiRootContainer::getFunctionList();
   // function_5
   CEvaluationTree* pTree = pFunctionDB->findFunction("function_4");
   CPPUNIT_ASSERT(pTree != NULL);
   // generate a call node
   CFunction* pFunction = dynamic_cast<CFunction*>(pTree);
   CPPUNIT_ASSERT(pFunction != NULL);
   CEvaluationNodeCall* pCallNode = new CEvaluationNodeCall(CEvaluationNodeCall::FUNCTION, pFunction->getObjectName());
   CPPUNIT_ASSERT(pCallNode != NULL);
   CFunctionParameters* pFunctionParameters = &pFunction->getVariables();
   unsigned int i = 0, iMax = pFunctionParameters->size();
   while (i < iMax)
     {
       CFunctionParameter* pParameter = (*pFunctionParameters)[i];
       CPPUNIT_ASSERT(pParameter != NULL);
       CEvaluationNodeVariable* pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, pParameter->getObjectName());
       pCallNode->addChild(pVariableNode);
       ++i;
     }
   CEvaluationNode* pExpanded = expand_function_calls(pCallNode, pFunctionDB);
   delete pCallNode;
   CPPUNIT_ASSERT(pExpanded != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pExpanded->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pExpanded->getType()) == CEvaluationNodeOperator::DIVIDE);
   CEvaluationNode* pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("y"));
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("x"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 2.0) / 2.0) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   delete pExpanded;
   // function_5
   pTree = pFunctionDB->findFunction("function_5");
   CPPUNIT_ASSERT(pTree != NULL);
   // generate a call node
   pFunction = dynamic_cast<CFunction*>(pTree);
   CPPUNIT_ASSERT(pFunction != NULL);
   pCallNode = new CEvaluationNodeCall(CEvaluationNodeCall::FUNCTION, pFunction->getObjectName());
   CPPUNIT_ASSERT(pCallNode != NULL);
   pFunctionParameters = &pFunction->getVariables();
   i = 0, iMax = pFunctionParameters->size();
   while (i < iMax)
     {
       CFunctionParameter* pParameter = (*pFunctionParameters)[i];
       CPPUNIT_ASSERT(pParameter != NULL);
       CEvaluationNodeVariable* pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, pParameter->getObjectName());
       pCallNode->addChild(pVariableNode);
       ++i;
     }
   pExpanded = expand_function_calls(pCallNode, pFunctionDB);
   delete pCallNode;
   CPPUNIT_ASSERT(pExpanded != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pExpanded->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pExpanded->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MINUS);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("a"));
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("c"));
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 1.3) / 1.3) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   // (3*b)-5.23
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MINUS);
   // 3*b
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 3.0) / 3.0) < 1e-6);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("b"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   // 5.23
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild()->getSibling()->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 5.23) / 5.23) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   delete pExpanded;
   // function_6
   pTree = pFunctionDB->findFunction("function_6");
   CPPUNIT_ASSERT(pTree != NULL);
   // generate a call node
   pFunction = dynamic_cast<CFunction*>(pTree);
   CPPUNIT_ASSERT(pFunction != NULL);
   pCallNode = new CEvaluationNodeCall(CEvaluationNodeCall::FUNCTION, pFunction->getObjectName());
   CPPUNIT_ASSERT(pCallNode != NULL);
   pFunctionParameters = &pFunction->getVariables();
   i = 0, iMax = pFunctionParameters->size();
   while (i < iMax)
     {
       CFunctionParameter* pParameter = (*pFunctionParameters)[i];
       CPPUNIT_ASSERT(pParameter != NULL);
       CEvaluationNodeVariable* pVariableNode = new CEvaluationNodeVariable(CEvaluationNodeVariable::ANY, pParameter->getObjectName());
       pCallNode->addChild(pVariableNode);
       ++i;
     }
   pExpanded = expand_function_calls(pCallNode, pFunctionDB);
   delete pCallNode;
   CPPUNIT_ASSERT(pExpanded != NULL);
   // (k1-k3*1.3)+((3*k2)-5.23)
   CPPUNIT_ASSERT(CEvaluationNode::type(pExpanded->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pExpanded->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MINUS);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("k1"));
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("k3"));
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 1.3) / 1.3) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   // (3*b)-5.23
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MINUS);
   // 3*b
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 3.0) / 3.0) < 1e-6);
   pChild = dynamic_cast<CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT(pChild->getData() == std::string("k2"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   // 5.23
   pChild = dynamic_cast<CEvaluationNode*>(pExpanded->getChild()->getSibling()->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT((fabs(pChild->getValue() - 5.23) / 5.23) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   delete pExpanded;
 }
Member Data Documentation
const char * test_compare_utilities::MODEL_STRING1 static protected
Definition at line 31 of file test_compare_utilities.h.
Referenced by test_copasi_function_expansion().
CCopasiDataModel * test_compare_utilities::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test_compare_utilities.h.
Referenced by setUp(), and test_copasi_function_expansion().
The documentation for this class was generated from the following files:
test_compare_utilities.h
test_compare_utilities.cpp