COPASI API: CEvaluationNodeDelay Class Reference
CEvaluationNodeDelay Class Reference
#include <CEvaluationNodeDelay.h>
Public Types
enum SubType { INVALID = 0x00FFFFFF, DELAY = 0x00000000 }
Public Types inherited from CEvaluationNode
enum Type {
INVALID = 0xFF000000, NUMBER = 0x01000000, CONSTANT = 0x02000000, OPERATOR = 0x03000000,
OBJECT = 0x04000000, FUNCTION = 0x05000000, CALL = 0x06000000, STRUCTURE = 0x07000000,
CHOICE = 0x08000000, VARIABLE = 0x09000000, WHITESPACE = 0x0a000000, LOGICAL = 0x0b000000,
MV_FUNCTION = 0x0c000000, VECTOR = 0x0d000000, DELAY = 0x0e000000
}
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Public Member Functions
CEvaluationNodeDelay (const SubType &subType, const Data &data)
CEvaluationNodeDelay (const CEvaluationNodeDelay &src)
virtual bool compile (const CEvaluationTree *pTree)
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const
virtual std::string getCCodeString (const std::vector< std::string > &children) const
virtual std::string getDisplayString (const std::vector< std::string > &children) const
virtual std::string getInfix (const std::vector< std::string > &children) const
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const
virtual std::string getXPPString (const std::vector< std::string > &children) const
ASTNode * toAST (const CCopasiDataModel *pDataModel) const
virtual ~CEvaluationNodeDelay ()
Public Member Functions inherited from CEvaluationNode
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
virtual void calculate ()
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
const Type & getType () const
const C_FLOAT64 & getValue () const
const C_FLOAT64 * getValuePointer () const
virtual bool isBoolean () const
virtual bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator== (const CEvaluationNode &right) const
void printRecursively (std::ostream &os, int indent=0) const
void printRecursively () const
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static CEvaluationNode * fromAST (const ASTNode *pASTNode, const std::vector< CEvaluationNode * > &children)
Static Public Member Functions inherited from CEvaluationNode
static CEvaluationNode * create (const Type &type, const Data &data)
static bool isKeyword (const std::string &str)
static Type subType (const Type &type)
static Type type (const Type &type)
Private Member Functions
CEvaluationNodeDelay ()
Private Attributes
CEvaluationNode * mpDelayedObject
CEvaluationNode * mpDeltaT
Additional Inherited Members
Protected Member Functions inherited from CEvaluationNode
CEvaluationNode (const Type &type, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CEvaluationNode
class CEvaluationNode::CPrecedence mPrecedence
const C_FLOAT64 * mpValue
Type mType
C_FLOAT64 mValue
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Detailed Description
This is class for nodes representing the (SBML) delay function.
Definition at line 28 of file CEvaluationNodeDelay.h.
Member Enumeration Documentation
enum CEvaluationNodeDelay::SubType
Enumeration of possible node types.
Enumerator
INVALID
DELAY
Definition at line 34 of file CEvaluationNodeDelay.h.
   {
     INVALID = 0x00FFFFFF,
     DELAY = 0x00000000
   };
Constructor & Destructor Documentation
CEvaluationNodeDelay::CEvaluationNodeDelay () private
Default constructor
Definition at line 24 of file CEvaluationNodeDelay.cpp.
References CEvaluationNode::mPrecedence, and PRECEDENCE_NUMBER.
Referenced by fromAST().
                                           :
     CEvaluationNode(CEvaluationNode::INVALID, ""),
     mpDelayedObject(NULL),
     mpDeltaT(NULL)
 {mPrecedence = PRECEDENCE_NUMBER;}
CEvaluationNodeDelay::CEvaluationNodeDelay (const SubType & subType, const Data & data)
constructor
Parameters
const SubType & subType
const Data & data
Definition at line 30 of file CEvaluationNodeDelay.cpp.
References DELAY, fatalError, CEvaluationNode::mPrecedence, CEvaluationNode::mValue, and PRECEDENCE_FUNCTION.
                    :
     CEvaluationNode((Type)(CEvaluationNode::DELAY | subType), "delay"),
     mpDelayedObject(NULL),
     mpDeltaT(NULL)
 {
   switch (subType)
     {
       case DELAY:
         mValue = std::numeric_limits<C_FLOAT64>::quiet_NaN();
         break;
       default:
         fatalError();
         break;
     }
   mPrecedence = PRECEDENCE_FUNCTION;
 }
CEvaluationNodeDelay::CEvaluationNodeDelay (const CEvaluationNodeDelay & src)
Copy constructor
Parameters
const CEvaluationNodeDelay & src
Definition at line 50 of file CEvaluationNodeDelay.cpp.
                                                                           :
     CEvaluationNode(src),
     mpDelayedObject(NULL),
     mpDeltaT(NULL)
 {}
CEvaluationNodeDelay::~CEvaluationNodeDelay () virtual
Destructor
Definition at line 56 of file CEvaluationNodeDelay.cpp.
 {}
Member Function Documentation
bool CEvaluationNodeDelay::compile (const CEvaluationTree * pTree) virtual
Compile a node;
Parameters
const CEvaluationTree * pTree
Returns
bool success;
Reimplemented from CEvaluationNode.
Definition at line 58 of file CEvaluationNodeDelay.cpp.
References DELAY, CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), mpDelayedObject, mpDeltaT, and CEvaluationNode::mType.
Referenced by getInfix().
 {
   bool success = true;
   switch (mType & 0x00FFFFFF)
     {
       case DELAY:
         mpDelayedObject = static_cast<CEvaluationNode *>(getChild());
         if (mpDelayedObject == NULL) return false;
         mpDeltaT = static_cast<CEvaluationNode *>(mpDelayedObject->getSibling());
         if (mpDeltaT == NULL) return false;
         return (mpDeltaT->getSibling() == NULL); // We must have exactly 2 children
         break;
       default:
         success = false;
         break;
     }
   return success;
 }
CEvaluationNode * CEvaluationNodeDelay::fromAST (const ASTNode * pASTNode, const std::vector< CEvaluationNode * > & children) static
Creates a new CEvaluationNodeCall from an ASTNode and the given children
Parameters
const ASTNode* pNode
const std::vector< CEvaluationNode * > & children
Returns
CEvaluationNode * pCretedNode
Definition at line 169 of file CEvaluationNodeDelay.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeDelay(), CEvaluationNode::compile(), DELAY, and CEvaluationNode::subType().
Referenced by CEvaluationTree::fromAST().
 {
   assert(pASTNode->getNumChildren() == children.size());
   size_t i = 0, iMax = children.size();
   SubType subType = CEvaluationNodeDelay::DELAY;
   std::string data = "delay";
   CEvaluationNode * pConvertedNode = new CEvaluationNodeDelay(subType, data);
   for (i = 0; i < iMax; ++i)
     {
       pConvertedNode->addChild(children[i]);
     }
   pConvertedNode->compile(NULL);
   return pConvertedNode;
 }
std::string CEvaluationNodeDelay::getBerkeleyMadonnaString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in Berkeley Madonna format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 137 of file CEvaluationNodeDelay.cpp.
References DELAY, CCopasiNode< std::string >::mData, and CEvaluationNode::mType.
 {
   switch (mType & 0x00FFFFFF)
     {
       case DELAY:
         return mData + "(" + children[0] + "," + children[1] + ")";
         break;
       default:
         break;
     }
   return "@";
 }
std::string CEvaluationNodeDelay::getCCodeString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 121 of file CEvaluationNodeDelay.cpp.
References DELAY, CCopasiNode< std::string >::mData, and CEvaluationNode::mType.
 {
   switch (mType & 0x00FFFFFF)
     {
       case DELAY:
         return mData + "(" + children[0] + "," + children[1] + ")";
         break;
       default:
         break;
     }
   return "@";
 }
std::string CEvaluationNodeDelay::getDisplayString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 105 of file CEvaluationNodeDelay.cpp.
References DELAY, CCopasiNode< std::string >::mData, and CEvaluationNode::mType.
 {
   switch (mType & 0x00FFFFFF)
     {
       case DELAY:
         return mData + "(" + children[0] + "," + children[1] + ")";
         break;
       default:
         break;
     }
   return "@";
 }
std::string CEvaluationNodeDelay::getInfix (const std::vector< std::string > & children) const virtual
Retrieve the infix value of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 86 of file CEvaluationNodeDelay.cpp.
References compile(), DELAY, CCopasiNode< std::string >::mData, and CEvaluationNode::mType.
 {
   if (const_cast<CEvaluationNodeDelay*>(this)->compile(NULL))
     {
       switch (mType & 0x00FFFFFF)
         {
           case DELAY:
             return mData + "(" + children[0] + "," + children[1] + ")";
             break;
           default:
             break;
         }
     }
   return "@";
 }
std::string CEvaluationNodeDelay::getMMLString (const std::vector< std::string > & children, bool expand, const std::vector< std::vector< std::string > > & variables) const virtual
Build the MathML string
Parameters
const std::vector< std::string > & children
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
Reimplemented from CEvaluationNode.
Definition at line 206 of file CEvaluationNodeDelay.cpp.
References DELAY, CCopasiNode< std::string >::mData, and CEvaluationNode::mType.
 {
   std::ostringstream out;
   switch (mType & 0x00FFFFFF)
     {
       case DELAY:
         out << "<mrow>" << std::endl;
         out << "<mi>" << mData << "</mi>" << std::endl;
         out << "<mrow>" << std::endl;
         out << "<mo> (</mo>" << std::endl;
         out << "<mrow>" << std::endl;
         out << children[0];
         out << "<mo> , </mo>" << std::endl;
         out << children[1];
         out << "</mrow>" << std::endl;
         out << "<mo>) </mo>" << std::endl;
         out << "</mrow>" << std::endl;
         out << "</mrow>" << std::endl;
         break;
       default:
         break;
     }
   return out.str();
 }
std::string CEvaluationNodeDelay::getXPPString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in XPPAUT format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 153 of file CEvaluationNodeDelay.cpp.
References DELAY, CCopasiNode< std::string >::mData, and CEvaluationNode::mType.
 {
   switch (mType & 0x00FFFFFF)
     {
       case DELAY:
         return mData + "(" + children[0] + "," + children[1] + ")";
         break;
       default:
         break;
     }
   return "@";
 }
ASTNode * CEvaluationNodeDelay::toAST (const CCopasiDataModel * pDataModel) const virtual
Create a new ASTNode corresponding to this delay node.
Returns
ASTNode* return a pointer to the newly created node;
Reimplemented from CEvaluationNode.
Definition at line 189 of file CEvaluationNodeDelay.cpp.
References CCopasiNode< _Data >::addChild(), CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), and CEvaluationNode::toAST().
 {
   ASTNode* pNode = new ASTNode(AST_FUNCTION_DELAY);
   const CEvaluationNode* child = static_cast<const CEvaluationNode*>(this->getChild());
   while (child)
     {
       pNode->addChild(child->toAST(pDataModel));
       child = static_cast<const CEvaluationNode*>(child->getSibling());
     }
   return pNode;
 }
Member Data Documentation
CEvaluationNode* CEvaluationNodeDelay::mpDelayedObject private
Definition at line 132 of file CEvaluationNodeDelay.h.
Referenced by compile().
CEvaluationNode* CEvaluationNodeDelay::mpDeltaT private
Definition at line 133 of file CEvaluationNodeDelay.h.
Referenced by compile().
The documentation for this class was generated from the following files:
CEvaluationNodeDelay.h
CEvaluationNodeDelay.cpp