COPASI API: CQOptimizationResult Class Reference
CQOptimizationResult Class Reference
#include <CQOptimizationResult.h>
Public Member Functions
CQOptimizationResult (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQOptimizationResult ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotSave (void)
void slotUpdateModel ()
Private Member Functions
void init ()
Private Attributes
const COptProblem * mpProblem
const COptTask * mpTask
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 29 of file CQOptimizationResult.h.
Constructor & Destructor Documentation
CQOptimizationResult::CQOptimizationResult (QWidget * parent = 0, const char * name = 0)
Definition at line 30 of file CQOptimizationResult.cpp.
References init().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQOptimizationResult::~CQOptimizationResult ()
Definition at line 41 of file CQOptimizationResult.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
bool CQOptimizationResult::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 63 of file CQOptimizationResult.cpp.
References C_FLOAT64, C_INT32, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), COptProblem::getExecutionTime(), COptProblem::getFunctionEvaluations(), CCopasiObject::getObjectDisplayName(), COptProblem::getOptItemList(), CCopasiTask::getProblem(), COptProblem::getSolutionValue(), COptProblem::getSolutionVariables(), COptProblem::getVariableGradients(), mpProblem, and mpTask.
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   mpTask =
     dynamic_cast<COptTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Optimization"]);
   if (!mpTask) return false;
   mpProblem = dynamic_cast<const COptProblem *>(mpTask->getProblem());
   if (!mpProblem) return false;
   // Objective Value
   mpEditObjectiveValue->setText(QString::number(mpProblem->getSolutionValue()));
   // Performance Statistics
   const unsigned C_INT32 & FunctionEvaluations = mpProblem->getFunctionEvaluations();
   mpEditEvaluations->setText(QString::number(FunctionEvaluations));
   const C_FLOAT64 & ExecutionTime = mpProblem->getExecutionTime();
   mpEditCPUTime->setText(QString::number(ExecutionTime));
   mpEditSpeed->setText(QString::number(FunctionEvaluations / ExecutionTime));
   size_t i, imax;
   // Loop over the optimization items
   const std::vector< COptItem * > & Items = mpProblem->getOptItemList();
   const CVector< C_FLOAT64 > & Solutions = mpProblem->getSolutionVariables();
   const CVector< C_FLOAT64 > & Gradients = mpProblem->getVariableGradients();
   imax = Items.size();
   QTableWidgetItem * pItem;
   if (mpProblem->getFunctionEvaluations() == 0)
     imax = 0;
   mpParameters->setRowCount((int) imax);
   QColor BackgroundColor = mpParameters->palette().brush(QPalette::Active, QPalette::Base).color();
   int h, s, v;
   BackgroundColor.getHsv(&h, &s, &v);
   if (s < 20)
     {
       s = 20;
     }
   BackgroundColor.setHsv(0, s, v);
   for (i = 0; i != imax; i++)
     {
       //1st column: parameter name
       const CCopasiObject *pObject =
         pDataModel->getDataObject(Items[i]->getObjectCN());
       if (pObject)
         pItem = new QTableWidgetItem(FROM_UTF8(pObject->getObjectDisplayName()));
       else
         pItem = new QTableWidgetItem("Not Found");
       mpParameters->setItem((int) i, 0, pItem);
       const C_FLOAT64 & Solution = Solutions[i];
       //2nd column: lower bound
       pItem = new QTableWidgetItem(FROM_UTF8(Items[i]->getLowerBound()));
       mpParameters->setItem((int) i, 1, pItem);
       if (1.01 * *Items[i]->getLowerBoundValue() > Solution)
         {
           pItem->setBackgroundColor(BackgroundColor);
         }
       //3rd column: start value
       pItem = new QTableWidgetItem(QString::number(Items[i]->getLastStartValue()));
       pItem->setForeground(QColor(120, 120, 140));
       mpParameters->setItem((int) i, 2, pItem);
       //4th column: solution value
       pItem = new QTableWidgetItem(QString::number(Solution));
       mpParameters->setItem((int) i, 3, pItem);
       //5th column: upper bound
       pItem = new QTableWidgetItem(FROM_UTF8(Items[i]->getUpperBound()));
       mpParameters->setItem((int) i, 4, pItem);
       if (0.99 * *Items[i]->getUpperBoundValue() < Solution)
         {
           pItem->setBackgroundColor(BackgroundColor);
         }
       pItem = new QTableWidgetItem(QString::number(Gradients[i]));
       mpParameters->setItem((int) i, 5,  pItem);
     }
   mpParameters->resizeColumnsToContents();
   mpParameters->resizeRowsToContents();
   return true;
 }
void CQOptimizationResult::init () private
Definition at line 46 of file CQOptimizationResult.cpp.
Referenced by CQOptimizationResult().
 {}
bool CQOptimizationResult::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 57 of file CQOptimizationResult.cpp.
 {
   // :TODO:
   return true;
 }
void CQOptimizationResult::slotSave (void) private slot
Definition at line 167 of file CQOptimizationResult.cpp.
References C_FLOAT64, C_INT32, checkSelection(), CLocaleString::fromUtf8(), COptProblem::getExecutionTime(), COptProblem::getFunctionEvaluations(), CopasiFileDialog::getSaveFileName(), COptProblem::getSolutionValue(), mpProblem, and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail()) return;
   size_t i, imax;
   // The global result and statistics
   file << "Objective Value" << std::endl;
   file << mpProblem->getSolutionValue() << std::endl;
   file << "Function Evaluations\tCPU Time [s]\tEvaluations/second [1/s]" << std::endl;
   const size_t & FunctionEvaluations = mpProblem->getFunctionEvaluations();
   const C_FLOAT64 & ExecutionTime = mpProblem->getExecutionTime();
   file << FunctionEvaluations << "\t";
   file << ExecutionTime << "\t";
   file << FunctionEvaluations / ExecutionTime << std::endl << std::endl;
   // Set up the parameters table
   file << "Parameters:" << std::endl;
   file << "Parameter\tLower Bound\tStart Value\tValue\tUpper Bound\tGradient" << std::endl;
   // Loop over the fitted values objects
   imax = mpParameters->rowCount();
   for (i = 0; i != imax; i++)
     {
       file << TO_UTF8(mpParameters->item((int) i, 0)->text()) << "\t";
       file << TO_UTF8(mpParameters->item((int) i, 1)->text()) << "\t";
       file << TO_UTF8(mpParameters->item((int) i, 2)->text()) << "\t";
       file << TO_UTF8(mpParameters->item((int) i, 3)->text()) << "\t";
       file << TO_UTF8(mpParameters->item((int) i, 4)->text()) << "\t";
       file << TO_UTF8(mpParameters->item((int) i, 5)->text()) << std::endl;
     }
   file << std::endl;
 }
void CQOptimizationResult::slotUpdateModel () private slot
Definition at line 223 of file CQOptimizationResult.cpp.
References mpProblem.
 {
   const_cast< COptProblem * >(mpProblem)->restoreModel(true);
 }
bool CQOptimizationResult::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 49 of file CQOptimizationResult.cpp.
 {
   // :TODO:
   return true;
 }
Member Data Documentation
const COptProblem* CQOptimizationResult::mpProblem private
Definition at line 46 of file CQOptimizationResult.h.
Referenced by enterProtected(), slotSave(), and slotUpdateModel().
const COptTask* CQOptimizationResult::mpTask private
Definition at line 47 of file CQOptimizationResult.h.
Referenced by enterProtected().
The documentation for this class was generated from the following files:
CQOptimizationResult.h
CQOptimizationResult.cpp