COPASI API: CSBMLExporter Class Reference
CSBMLExporter Class Reference
#include <CSBMLExporter.h>
Public Member Functions
CSBMLExporter ()
void disownSBMLDocument ()
bool exportModel (CCopasiDataModel &dataModel, const std::string &filename, unsigned int sbmlLevel=2, unsigned int sbmlVersion=1, bool overwrite=false)
const std::string exportModelToString (CCopasiDataModel &dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion)
const std::map< const
CCopasiObject *, SBase * > & getCOPASI2SBMLMap () const
SBMLDocument * getSBMLDocument ()
bool isSetExportCOPASIMIRIAM () const
void setExportCOPASIMIRIAM (bool exportMIRIAM)
~CSBMLExporter ()
Static Public Member Functions
static const std::string createUniqueId (const std::map< std::string, const SBase * > &idMap, const std::string &prefix, bool addIndexForFirst, const std::string &separator="_")
static const std::vector
< SBMLIncompatibility > isModelSBMLCompatible (const CCopasiDataModel &pDataModel, int sbmlLevel, int sbmlVersion)
Protected Member Functions
void assignSBMLIdsToReactions (CModel *pModel)
void checkForUnsupportedFunctionCalls (const CCopasiDataModel &dataModel, unsigned int sbmlLEvel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > &result)
void checkForUnsupportedObjectReferences (const CCopasiDataModel &dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > &result)
void collectIds (const CCopasiDataModel &dataModel, std::map< std::string, const SBase * > &idMap)
ASTNode * convertToASTNode (const CEvaluationNode *pOrig, CCopasiDataModel &dataModel)
void convertToLevel1 ()
void createAreaUnit (const CCopasiDataModel &dataModel)
void createCompartment (CCompartment &compartment)
void createCompartments (CCopasiDataModel &dataModel)
void createEvent (CEvent &event, Event *pSBMLEvent, CCopasiDataModel &dataModel)
void createEvents (CCopasiDataModel &dataModel)
void createFunctionDefinition (CFunction &function, CCopasiDataModel &dataModel)
void createFunctionDefinitions (CCopasiDataModel &dataModel)
const std::map< std::string,
const SBase * > createIdMap (const Model &sbmlModel)
void createInitialAssignment (const CModelEntity &modelEntity, CCopasiDataModel &dataModel)
void createInitialAssignments (CCopasiDataModel &dataModel)
CEvaluationNode * createKineticExpression (CFunction *pFun, const std::vector< std::vector< std::string > > &arguments)
KineticLaw * createKineticLaw (CReaction &reaction, CCopasiDataModel &dataModel, unsigned int level, unsigned int version)
void createLengthUnit (const CCopasiDataModel &dataModel)
void createMetabolite (CMetab &metab)
void createMetabolites (CCopasiDataModel &dataModel)
void createParameter (CModelValue &parameter)
void createParameters (CCopasiDataModel &dataModel)
void createReaction (CReaction &reaction, CCopasiDataModel &dataModel)
void createReactions (CCopasiDataModel &dataModel)
void createRule (const CModelEntity &modelEntity, CCopasiDataModel &dataModel, Rule *pOldRule)
void createRules (CCopasiDataModel &dataModel)
void createSBMLDocument (CCopasiDataModel &dataModel)
void createSubstanceUnit (const CCopasiDataModel &dataModel)
void createTimeUnit (const CCopasiDataModel &dataModel)
void createUnits (const CCopasiDataModel &dataModel)
void createVolumeUnit (const CCopasiDataModel &dataModel)
void exportEventAssignments (const CEvent &event, Event *pSBMLEvent, CCopasiDataModel &dataModel)
void findAvogadro (const CCopasiDataModel &dataModel)
bool hasVolumeAssignment (const CCopasiDataModel &dataModel)
std::vector< CModelEntity * > orderRules (const CCopasiDataModel &dataModel)
void outputIncompatibilities () const
void removeInitialAssignment (const std::string &sbmlId)
void removeRule (const std::string &sbmlId)
void removeUnusedObjects ()
void replace_local_parameters (ASTNode *pOrigNode, const CCopasiDataModel &dataModel)
XMLNode * replaceChild (const XMLNode *pParent, const XMLNode *pNewChild, unsigned int index)
CEvaluationNode * replaceSpeciesReferences (const CEvaluationNode *pOrigNode, const CCopasiDataModel &dataModel)
void restore_local_parameters (ASTNode *pOrigNode, const CCopasiDataModel &dataModel)
void setFunctionSBMLIds (const CEvaluationNode *pNode, CCopasiDataModel &dataModel)
void updateCOPASI2SBMLMap (const CCopasiDataModel &dataModel)
bool updateMIRIAMAnnotation (const CCopasiObject *pCOPASIObject, SBase *pSBMLObject, std::map< std::string, const SBase * > &metaIds)
Static Protected Member Functions
static void check_for_spatial_size_units (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void checkForEvents (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void checkForInitialAssignments (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void checkForODESpeciesInNonfixedCompartment (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > result)
static void checkForPiecewiseFunctions (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void checkForPiecewiseFunctions (const CEvaluationNode &node, std::vector< SBMLIncompatibility > &result, const std::string &objectName, const std::string &objectType)
static void checkForUnsupportedFunctionCalls (const CEvaluationNode &node, const std::set< CEvaluationNodeFunction::SubType > &unsupportedFunctions, std::vector< SBMLIncompatibility > &result, const std::string &objectDescription)
static void checkForUnsupportedObjectReferences (const CEvaluationTree &expression, const CCopasiDataModel &dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > &result, bool initialExpression=false, std::map< const std::string, Parameter * > *initialMap=NULL)
static void convert_to_l1v1 (std::string &l1v2_string)
static ASTNode * convertASTTreeToLevel1 (const ASTNode *pNode, const ListOfFunctionDefinitions &functions, std::string &message)
static const std::set
< CFunction * > createFunctionSetFromFunctionNames (const std::set< std::string > &names, CFunctionDB *pFunDB)
static CEvaluationNode * createMassActionExpression (const std::vector< std::vector< std::string > > &arguments, bool isReversible)
static ASTNode * createTimesTree (const CCopasiVector< CChemEqElement > &vect, unsigned int pos=0)
static const std::set
< CEvaluationNodeFunction::SubType > createUnsupportedFunctionTypeSet (unsigned int sbmlLevel)
static void findDirectlyUsedFunctions (const CEvaluationNode *pRootNode, std::set< std::string > &result)
static void findModelEntityDependencies (const CEvaluationNode *pNode, const CCopasiDataModel &dataModel, std::set< const CModelEntity * > &dependencies)
static const std::vector
< CFunction * > findUsedFunctions (std::set< CFunction * > &functions, CFunctionDB *pFunctionDB)
static ASTNode * isDividedByVolume (const ASTNode *pRootNode, const std::string &compartmentId)
static void isEventAssignmentSBMLCompatible (std::string &key, const CExpression *pExpression, const CCopasiDataModel &dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, const std::string &eventName, std::vector< SBMLIncompatibility > &result)
static void isEventSBMLCompatible (const CEvent *pEvent, const CCopasiDataModel &dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > &result)
static void isExpressionSBMLCompatible (const CEvaluationTree &expr, const CCopasiDataModel &dataModel, int sbmlLevel, int sbmlVersion, std::vector< SBMLIncompatibility > &result, const std::string &objectDescription, bool initialExression=false, std::map< const std::string, Parameter * > *initialMap=NULL)
static void isExpressionSBMLL1Compatible (const CEvaluationTree &expr, const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void isExpressionSBMLL2V1Compatible (const CEvaluationTree &expr, const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void isExpressionSBMLL2V3Compatible (const CEvaluationTree &expression, const CCopasiDataModel &pDataModel, std::vector< SBMLIncompatibility > &result)
static void isModelSBMLL1Compatible (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void isModelSBMLL2V1Compatible (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static void isModelSBMLL2V3Compatible (const CCopasiDataModel &dataModel, std::vector< SBMLIncompatibility > &result)
static bool isValidSId (const std::string &id)
static CEvaluationNode * multiplyByObject (const CEvaluationNode *pOrigNode, const CCopasiObject *pObject)
static ASTNode * replaceL1IncompatibleNodes (const ASTNode *pNode)
static bool setSBMLNotes (SBase *pSBase, const CAnnotation *pAnno)
Protected Attributes
std::vector< CModelEntity * > mAssignmentVector
bool mAvogadroCreated
std::map< const CCopasiObject
*, SBase * > mCOPASI2SBMLMap
bool mDocumentDisowned
bool mExportCOPASIMIRIAM
ListOfFunctionDefinitions mExportedFunctions
std::map< std::string, const
CEvaluationTree * > mFunctionIdMap
std::map< const
FunctionDefinition *, const
CCopasiObject * > mFunctionMap
std::set< SBase * > mHandledSBMLObjects
bool mHaveModelHistoryAuthorWarning
bool mHaveModelHistoryCreationDateWarning
bool mHaveModelHistoryModificationDateWarning
std::map< std::string, const
SBase * > mIdMap
std::vector< SBMLIncompatibility > mIncompatibilities
bool mIncompleteExport
std::vector< CModelEntity * > mInitialAssignmentVector
std::map< const std::string,
Parameter * > mInitialValueMap
std::map< std::string, const
SBase * > mMetaIdMap
bool mMIRIAMWarning
std::vector< CModelEntity * > mODEVector
std::map< std::string,
Parameter * > mParameterReplacementMap
const CModelValue * mpAvogadro
SBMLDocument * mpSBMLDocument
unsigned int mSBMLLevel
unsigned int mSBMLVersion
std::set< std::string > mSpatialSizeUnitsSpecies
std::set< CFunction * > mUsedFunctions
bool mVariableVolumes
Detailed Description
Definition at line 52 of file CSBMLExporter.h.
Constructor & Destructor Documentation
CSBMLExporter::CSBMLExporter ()
Default Konstruktor
Definition at line 328 of file CSBMLExporter.cpp.
                             : mpSBMLDocument(NULL), mSBMLLevel(2), mSBMLVersion(1), mIncompleteExport(false), mVariableVolumes(false), mpAvogadro(NULL), mAvogadroCreated(false), mMIRIAMWarning(false), mDocumentDisowned(false), mExportCOPASIMIRIAM(false), mExportedFunctions(2, 1)
 {}
CSBMLExporter::~CSBMLExporter ()
Destruktor
Definition at line 331 of file CSBMLExporter.cpp.
References mDocumentDisowned, mpSBMLDocument, and pdelete.
 {
   if (this->mDocumentDisowned == false)
     {
       pdelete(mpSBMLDocument);
     }
 };
Member Function Documentation
void CSBMLExporter::assignSBMLIdsToReactions (CModel * pModel) protected
Since we want to replace local reaction parameters by global parameters if they are used in an assignment, we have to create the reactions after creating the rules and events. On the other hand, a reaction flux might also be referenced in an assignment or an event and the creation of this rule or event only works if the reactions already have SBML ids. To solve this problem, the reactions have to be assigned SBML ids prior to creating rules and events. This is what this method does.
Definition at line 7556 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), createUniqueId(), CCopasiVector< T >::end(), CModel::getReactions(), and mIdMap.
Referenced by createSBMLDocument().
 {
   std::string sbmlId;
   CCopasiVectorNS<CReaction>::const_iterator it = pModel->getReactions().begin(), endit = pModel->getReactions().end();
   while (it != endit)
     {
       if ((*it)->getSBMLId().empty())
         {
           sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, (*it)->getObjectName(), false);
           (*it)->setSBMLId(sbmlId);
           this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, (const SBase*)NULL));
         }
       ++it;
     }
 }
void CSBMLExporter::check_for_spatial_size_units (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Go through all species in the model and check if the corresponding species in the SBML model has the spatialSizeUnits attribute set. This attribute is not supported in SBML L2V3 and above, so we have to get rid of this attribute when we export to a level equal to or higher than L2V3. If the attribute has the same value as the compartments units, we can just delete it without changing the model, otherwise we have to give a corresponding warning.
Definition at line 2597 of file CSBMLExporter.cpp.
References SBMLImporter::areSBMLUnitDefinitionsIdentical(), CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CCopasiMessage::EXCEPTION, CModel::getMetabolites(), CCopasiDataModel::getModel(), SBMLImporter::getSBMLUnitDefinitionForId(), and MCSBML.
Referenced by createMetabolites(), and isModelSBMLL2V3Compatible().
 {
   const SBMLDocument* pSBMLDocument = const_cast<const SBMLDocument*>(const_cast<CCopasiDataModel&>(dataModel).getCurrentSBMLDocument());
   if (pSBMLDocument != NULL)
     {
       // check all species in the model if they have a spatial size attribute set
       // and if it is identical to the unit of the compartment the species is in
       const CModel* pModel = dataModel.getModel();
       if (pModel != NULL)
         {
           CCopasiVector<CMetab>::const_iterator it = pModel->getMetabolites().begin(), endit = pModel->getMetabolites().end();
           std::set<std::string> badSpecies;
           const std::map<CCopasiObject*, SBase*>& copasi2sbmlmap = const_cast<CCopasiDataModel&>(dataModel).getCopasi2SBMLMap();
           std::map<CCopasiObject*, SBase*>::const_iterator pos;
           const Species* pSBMLSpecies = NULL;
           std::string spatialSizeUnits;
           while (it != endit)
             {
               pos = copasi2sbmlmap.find(*it);
               if (pos != copasi2sbmlmap.end())
                 {
                   // check for the spatial size units attribute
                   pSBMLSpecies = dynamic_cast<const Species*>(pos->second);
                   assert(pSBMLSpecies != NULL);
                   if (pSBMLSpecies == NULL) continue;
                   if (pSBMLSpecies->isSetSpatialSizeUnits())
                     {
                       spatialSizeUnits = pSBMLSpecies->getSpatialSizeUnits();
                       // check if the units are the same as the one on the species
                       // compartment
                       assert(pSBMLDocument->getModel() != NULL);
                       const Compartment* pCompartment = pSBMLDocument->getModel()->getCompartment(pSBMLSpecies->getCompartment());
                       assert(pCompartment != NULL);
                       if (pCompartment != NULL)
{
                           UnitDefinition* pUDef1 = NULL;
                           UnitDefinition* pUDef2 = NULL;
                           if (pCompartment->isSetUnits())
{
                               assert(pSBMLDocument->getModel() != NULL);
                               if (pSBMLDocument->getModel() != NULL)
{
                                   pUDef1 = SBMLImporter::getSBMLUnitDefinitionForId(pCompartment->getUnits(), pSBMLDocument->getModel());
                                 }
                             }
                           else
{
                               // the compartment has the default units associated with the
                               // symbol length , area or volume depending on the spatial size
                               // of the compartment
                               assert(pSBMLDocument->getModel() != NULL);
                               if (pSBMLDocument->getModel() != NULL)
{
                                   switch (pCompartment->getSpatialDimensions())
{
                                       case 0:
                                         // the species is not allowed to have a
                                         // spatialDimensionsUnit attribute
                                         CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 83 , pSBMLSpecies->getId().c_str());
                                         break;
                                       case 1:
                                         pUDef1 = SBMLImporter::getSBMLUnitDefinitionForId("length", pSBMLDocument->getModel());
                                         break;
                                       case 2:
                                         pUDef1 = SBMLImporter::getSBMLUnitDefinitionForId("area", pSBMLDocument->getModel());
                                         break;
                                       case 3:
                                         pUDef1 = SBMLImporter::getSBMLUnitDefinitionForId("volume", pSBMLDocument->getModel());
                                         break;
                                       default:
                                         CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 82 , pCompartment->getId().c_str());
                                         break;
                                     }
                                 }
                             }
                           if (pUDef1 != NULL && pUDef2 != NULL)
{
                               // compare the two unit definitions
                               if (!SBMLImporter::areSBMLUnitDefinitionsIdentical(pUDef1, pUDef2))
{
                                   // add the species to bad species
                                   badSpecies.insert(pSBMLSpecies->getId());
                                 }
                             }
                           // delete the unit definitions
                           if (pUDef1 != NULL)
{
                               delete pUDef1;
                             }
                           if (pUDef2 != NULL)
{
                               delete pUDef2;
                             }
                         }
                     }
                 }
               ++it;
             }
           if (!badSpecies.empty())
             {
               // create the incompatibility message
               std::ostringstream os;
               std::set<std::string>::const_iterator sit = badSpecies.begin(), sendit = badSpecies.end();
               while (sit != sendit)
                 {
                   os << *sit << ", ";
                   ++sit;
                 }
               result.push_back(SBMLIncompatibility(2, os.str().substr(0, os.str().size() - 2).c_str()));
             }
         }
     }
 }
void CSBMLExporter::checkForEvents (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks if the given datamodel contains events. This is called if SBML Level 1 is to be exported.
Definition at line 4552 of file CSBMLExporter.cpp.
References CModel::getEvents(), CCopasiDataModel::getModel(), and CCopasiVector< T >::size().
Referenced by createEvents(), and isModelSBMLL1Compatible().
 {
   if (dataModel.getModel() != NULL && dataModel.getModel()->getEvents().size() > 0)
     {
       result.push_back(SBMLIncompatibility(7));
     }
 }
void CSBMLExporter::checkForInitialAssignments (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
This method checks wether the given model contains any initial assignments.
This method checks whether the given model contains any initial assignments.
Definition at line 2887 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModel::getCompartments(), CModel::getMetabolites(), CCopasiDataModel::getModel(), and CModel::getModelValues().
Referenced by createSBMLDocument(), isModelSBMLL1Compatible(), and isModelSBMLL2V1Compatible().
 {
   const CModel* pModel = dataModel.getModel();
   if (pModel != NULL)
     {
       // check for rules
       const CCopasiVectorNS<CCompartment>& compartments = pModel->getCompartments();
       CCopasiVectorNS<CCompartment>::const_iterator compIt = compartments.begin(), compEndit = compartments.end();
       while (compIt != compEndit)
         {
           if ((*compIt)->getInitialExpression() != "")
             {
               result.push_back(SBMLIncompatibility(5, "Compartment", (*compIt)->getObjectName().c_str()));
             }
           ++compIt;
         }
       const CCopasiVector<CMetab>& metabs = pModel->getMetabolites();
       CCopasiVector<CMetab>::const_iterator metabIt = metabs.begin(), metabEndit = metabs.end();
       while (metabIt != metabEndit)
         {
           if ((*metabIt)->getInitialExpression() != "")
             {
               result.push_back(SBMLIncompatibility(5, "Metabolite", (*metabIt)->getObjectName().c_str()));
             }
           ++metabIt;
         }
       const CCopasiVectorN<CModelValue>& parameters = pModel->getModelValues();
       CCopasiVectorN<CModelValue>::const_iterator mvIt = parameters.begin(), mvEndit = parameters.end();
       while (mvIt != mvEndit)
         {
           if ((*mvIt)->getInitialExpression() != "")
             {
               result.push_back(SBMLIncompatibility(5, "Parameter", (*mvIt)->getObjectName().c_str()));
             }
           ++mvIt;
         }
     }
 }
void CSBMLExporter::checkForODESpeciesInNonfixedCompartment (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > result) static protected
Checks wether the model contains a metabolite that is defined by an ODE expression and that is located in a variable volume. Since COPASI interprets the expression differntly from SBML, we can not correctly export this yet. See Bug 903.
Checks whether the model contains a metabolite that is defined by an ODE expression and that is located in a variable volume. Since COPASI interprets the expression differently from SBML, we can not correctly export this yet. See Bug 903.
Definition at line 2738 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModelEntity::FIXED, CModel::getMetabolites(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CModelEntity::getStatus(), and CModelEntity::ODE.
Referenced by isModelSBMLCompatible().
 {
   const CModel* pModel = dataModel.getModel();
   const CCopasiVector<CMetab>& metabolites = pModel->getMetabolites();
   CCopasiVector<CMetab>::const_iterator it = metabolites.begin(), endit = metabolites.end();
   while (it != endit)
     {
       if ((*it)->getStatus() == CModelValue::ODE)
         {
           const CCompartment* pCompartment = (*it)->getCompartment();
           assert(pCompartment != NULL);
           if (pCompartment->getStatus() != CModelValue::FIXED)
             {
               result.push_back(SBMLIncompatibility(3, (*it)->getObjectName().c_str(), pCompartment->getObjectName().c_str()));
             }
         }
       ++it;
     }
 }
void CSBMLExporter::checkForPiecewiseFunctions (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks all expressions in the given datamodel for piecewise defined functions.
Definition at line 5531 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, createFunctionSetFromFunctionNames(), findDirectlyUsedFunctions(), findUsedFunctions(), CModel::getCompartments(), CModelEntity::getExpressionPtr(), CReaction::getFunction(), CCopasiRootContainer::getFunctionList(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CModel::getModelValues(), CCopasiObject::getObjectName(), CModel::getReactions(), CEvaluationTree::getRoot(), CModelEntity::getStatus(), CModelEntity::ODE, and CCopasiVector< T >::size().
Referenced by checkForPiecewiseFunctions(), and isModelSBMLL1Compatible().
 {
   std::set<std::string> usedFunctionNames;
   const CModel* pModel = dataModel.getModel();
   if (pModel == NULL) return;
   // go through all model entities and check assignments
   // we don't have to check initial assignment since those can not be exported
   // anyway
   const CModelEntity* pME = NULL;
   const CCopasiVectorNS<CCompartment>& compartments = pModel->getCompartments();
   size_t i, iMax = compartments.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = compartments[i];
       if (pME->getStatus() == CModelEntity::ODE || pME->getStatus() == CModelEntity::ASSIGNMENT)
         {
           const CEvaluationTree* pTree = pME->getExpressionPtr();
           CSBMLExporter::findDirectlyUsedFunctions(pTree->getRoot(), usedFunctionNames);
           CSBMLExporter::checkForPiecewiseFunctions(*pTree->getRoot(), result, pME->getObjectName(), "rule for compartment");
         }
     }
   const CCopasiVector<CMetab>& metabolites = pModel->getMetabolites();
   iMax = metabolites.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = metabolites[i];
       if (pME->getStatus() == CModelEntity::ODE || pME->getStatus() == CModelEntity::ASSIGNMENT)
         {
           const CEvaluationTree* pTree = pME->getExpressionPtr();
           CSBMLExporter::findDirectlyUsedFunctions(pTree->getRoot(), usedFunctionNames);
           CSBMLExporter::checkForPiecewiseFunctions(*pTree->getRoot(), result, pME->getObjectName(), "rule for metabolite");
         }
     }
   const CCopasiVectorN<CModelValue>& modelvalues = pModel->getModelValues();
   iMax = modelvalues.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = modelvalues[i];
       if (pME->getStatus() == CModelEntity::ODE || pME->getStatus() == CModelEntity::ASSIGNMENT)
         {
           const CEvaluationTree* pTree = pME->getExpressionPtr();
           CSBMLExporter::findDirectlyUsedFunctions(pTree->getRoot(), usedFunctionNames);
           CSBMLExporter::checkForPiecewiseFunctions(*pTree->getRoot(), result, pME->getObjectName(), "rule for global parameter");
         }
     }
   // go through all reactions and check the function called in the kinetic
   // laws.
   CReaction* pReaction = NULL;
   const CCopasiVectorNS<CReaction>& reactions = pModel->getReactions();
   iMax = reactions.size();
   for (i = 0; i < iMax; ++i)
     {
       pReaction = reactions[i];
       if (pReaction->getFunction() != NULL)
         {
           CSBMLExporter::findDirectlyUsedFunctions(pReaction->getFunction()->getRoot(), usedFunctionNames);
         }
     }
   // check indirectly called functions
   std::set<CFunction*> directlyUsedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(usedFunctionNames, CCopasiRootContainer::getFunctionList());
   std::vector<CFunction*> functions = CSBMLExporter::findUsedFunctions(directlyUsedFunctions, CCopasiRootContainer::getFunctionList());
   std::vector<CFunction*>::const_iterator it = functions.begin(), endit = functions.end();
   while (it != endit)
     {
       CSBMLExporter::checkForPiecewiseFunctions(*(*it)->getRoot(), result, (*it)->getObjectName(), "function");
       ++it;
     }
 }
void CSBMLExporter::checkForPiecewiseFunctions (const CEvaluationNode & node, std::vector< SBMLIncompatibility > & result, const std::string & objectName, const std::string & objectType) static protected
Checks the given node and all it's children for the occurence of piecewise functions.
Definition at line 5617 of file CSBMLExporter.cpp.
References checkForPiecewiseFunctions(), CEvaluationNode::CHOICE, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), and CEvaluationNode::type().
 {
   // no need to go through the children.
   // one incompatibility warning is enough
   if (CEvaluationNode::type(node.getType()) == CEvaluationNode::CHOICE)
     {
       result.push_back(SBMLIncompatibility(8, objectType.c_str(), objectName.c_str()));
     }
   else
     {
       // store the old size
       // if one error has been found, we can stop looking at the other
       // children
       size_t size = result.size();
       const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(node.getChild());
       while (pChild != NULL && result.size() == size)
         {
           CSBMLExporter::checkForPiecewiseFunctions(*pChild, result, objectName, objectType);
           pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
         }
     }
 }
void CSBMLExporter::checkForUnsupportedFunctionCalls (const CCopasiDataModel & dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > & result) protected
This static methods checks, wether the model uses any function calls that can not be expressed in SBML like the random distribution functions.
This static methods checks, whether the model uses any function calls that can not be expressed in SBML like the random distribution functions.
Definition at line 2786 of file CSBMLExporter.cpp.
References createUnsupportedFunctionTypeSet(), CModelEntity::getExpressionPtr(), CModelEntity::getInitialExpressionPtr(), CCopasiObject::getObjectName(), CCopasiObject::getObjectType(), CEvaluationTree::getRoot(), mAssignmentVector, mInitialAssignmentVector, mODEVector, and mUsedFunctions.
Referenced by checkForUnsupportedFunctionCalls(), and isExpressionSBMLCompatible().
 {
   // Fill the set of unsupported functions depending on the level and
   // version
   std::set<CEvaluationNodeFunction::SubType> unsupportedFunctionTypes = CSBMLExporter::createUnsupportedFunctionTypeSet(sbmlLevel);
   // check all metabolites,parameters and compartments
   // make sure the list of assignments and initial assignments is filled
   // before this function is called
   size_t i, iMax = mAssignmentVector.size();
   const CModelEntity* pME = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pME = mAssignmentVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           checkForUnsupportedFunctionCalls(*pME->getExpressionPtr()->getRoot(), unsupportedFunctionTypes, result, std::string(pME->getObjectType() + " called \"" + pME->getObjectName() + "\""));
         }
     }
   // check ode rules
   iMax = mODEVector.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = mODEVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           checkForUnsupportedFunctionCalls(*pME->getExpressionPtr()->getRoot(), unsupportedFunctionTypes, result, std::string(pME->getObjectType() + " called \"" + pME->getObjectName() + "\""));
         }
     }
   // check initial assignments
   iMax = mInitialAssignmentVector.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = mInitialAssignmentVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           checkForUnsupportedFunctionCalls(*pME->getInitialExpressionPtr()->getRoot(), unsupportedFunctionTypes, result, std::string(pME->getObjectType() + " called \"" + pME->getObjectName() + "\""));
         }
     }
   // if we already have a list of used functions, we can go through this here
   // make sure the list of used function has been filled before this is
   // called
   iMax = mUsedFunctions.size();
   std::set<CFunction*>::iterator it = this->mUsedFunctions.begin(), endit = this->mUsedFunctions.end();
   while (it != endit)
     {
       assert(*it != NULL);
       if (*it != NULL)
         {
           checkForUnsupportedFunctionCalls(*(*it)->getRoot(), unsupportedFunctionTypes, result, std::string("function called \"" + (*it)->getObjectName() + "\""));
         }
       ++it;
     }
 }
void CSBMLExporter::checkForUnsupportedFunctionCalls (const CEvaluationNode & node, const std::set< CEvaluationNodeFunction::SubType > & unsupportedFunctions, std::vector< SBMLIncompatibility > & result, const std::string & objectDescription) static protected
This static methods checks recursively, whether the given CEvaluationNode constains any function calls that can not be expressed in SBML like the random distribution functions.
Definition at line 2861 of file CSBMLExporter.cpp.
References checkForUnsupportedFunctionCalls(), CEvaluationNode::FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   if (CEvaluationNode::type(node.getType()) == CEvaluationNode::FUNCTION)
     {
       CEvaluationNodeFunction::SubType subtype = (CEvaluationNodeFunction::SubType)CEvaluationNode::subType(node.getType());
       if (unsupportedFunctions.find(subtype) != unsupportedFunctions.end())
         {
           result.push_back(SBMLIncompatibility(2, node.getData().c_str(), objectDescription.c_str()));
         }
     }
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(node.getChild());
   while (pChild != NULL)
     {
       checkForUnsupportedFunctionCalls(*pChild, unsupportedFunctions, result, objectDescription);
       pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
     }
 }
void CSBMLExporter::checkForUnsupportedObjectReferences (const CCopasiDataModel & dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > & result) protected
Checks all assignments (initial and transient) for references to objects that can not be exported to SBML.
Definition at line 2284 of file CSBMLExporter.cpp.
References CModelEntity::getExpressionPtr(), CModelEntity::getInitialExpressionPtr(), CCopasiDataModel::getModel(), mAssignmentVector, mInitialAssignmentVector, mInitialValueMap, and mODEVector.
Referenced by isExpressionSBMLCompatible().
 {
   // check all metabolites,parameters and compartments
   const CModel* pModel = dataModel.getModel();
   assert(pModel);
   if (pModel == NULL) return;
   size_t i, iMax = this->mAssignmentVector.size();
   const CModelEntity* pME;
   for (i = 0; i < iMax; ++i)
     {
       pME = this->mAssignmentVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           checkForUnsupportedObjectReferences(*pME->getExpressionPtr(), dataModel, sbmlLevel, sbmlVersion, result, false, &mInitialValueMap);
         }
     }
   // check ode rules
   iMax = this->mODEVector.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = this->mODEVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           checkForUnsupportedObjectReferences(*pME->getExpressionPtr(), dataModel, sbmlLevel, sbmlVersion, result, false, &mInitialValueMap);
         }
     }
   // check initial assignments
   iMax = this->mInitialAssignmentVector.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = this->mInitialAssignmentVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           checkForUnsupportedObjectReferences(*pME->getInitialExpressionPtr(), dataModel, sbmlLevel, sbmlVersion, result, false, &mInitialValueMap);
         }
     }
 }
void CSBMLExporter::checkForUnsupportedObjectReferences (const CEvaluationTree & expression, const CCopasiDataModel & dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > & result, bool initialExpression = false, std::map< const std::string, Parameter * > * initialMap = NULL) static protected
Checks the given expression for references to objects that can not be exported to SBML.
Definition at line 2376 of file CSBMLExporter.cpp.
References addToInitialValueMap(), CCopasiDataModel::getModel(), CEvaluationTree::getNodeList(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiObject::getObjectType(), CCopasiObject::isReference(), CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), and CEvaluationNode::type().
 {
   // SBML Level 1 and Level 2 Version 1 can have references to transient values of
   // compartments, metabolites and global parameters as well as time (model)
   // SBML Level 2 Version 2 and above can have the same references as level 1 plus references to
   // reaction fluxes.
   // Starting with COPASI Build 30 references to local parameters are allowed
   // as well because they are converted to global parameters
   const std::vector<CEvaluationNode*>& objectNodes = expr.getNodeList();
   size_t j, jMax = objectNodes.size();
   for (j = 0; j < jMax; ++j)
     {
       if (CEvaluationNode::type(objectNodes[j]->getType()) == CEvaluationNode::OBJECT)
         {
           const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(objectNodes[j]);
           assert(pObjectNode);
           if (pObjectNode == NULL) continue;
           std::vector<CCopasiContainer*> containers;
           containers.push_back(const_cast<CModel*>(dataModel.getModel()));
           const CCopasiObject* pObject =
             dataModel.ObjectFromName(containers, pObjectNode->getObjectCN());
           assert(pObject);
           if (pObject->isReference())
             {
               const CCopasiObject* pObjectParent = pObject->getObjectParent();
               assert(pObjectParent);
               std::string typeString = pObjectParent->getObjectType();
               if (typeString == "Compartment")
                 {
                   // must be a reference to the (transient) or initial volume
                   if (initialExpression == true)
                     {
                       if (pObject->getObjectName() != "InitialVolume")
{
                           result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "compartment", pObjectParent->getObjectName().c_str()));
                         }
                     }
                   else
                     {
                       if (pObject->getObjectName() == "InitialVolume"
                           && initialMap != NULL
                           && (sbmlLevel > 2 || (sbmlLevel == 2 && sbmlVersion > 1)))
{
                           // add new parameter for the initial value
                           addToInitialValueMap(initialMap, pObject, pObjectParent, sbmlLevel, sbmlVersion);
                         }
                       else if (pObject->getObjectName() != "Volume"
                                && pObject->getObjectName() != "Rate")
{
                           result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "compartment", pObjectParent->getObjectName().c_str()));
                         }
                     }
                 }
               else if (typeString == "Metabolite")
                 {
                   // must be a reference to the transient or initial concentration
                   if (initialExpression == true)
                     {
                       if (pObject->getObjectName() != "InitialConcentration" && pObject->getObjectName() != "InitialParticleNumber")
{
                           result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "metabolite", pObjectParent->getObjectName().c_str()));
                         }
                     }
                   else
                     {
                       if (pObject->getObjectName() == "InitialConcentration"
                           && initialMap != NULL
                           && (sbmlLevel > 2 || (sbmlLevel == 2 && sbmlVersion > 1)))
{
                           // add new parameter for the initial value
                           addToInitialValueMap(initialMap, pObject, pObjectParent, sbmlLevel, sbmlVersion);
                         }
                       else if (pObject->getObjectName() != "Concentration"
                                && pObject->getObjectName() != "ParticleNumber"
                                && pObject->getObjectName() != "Rate")
{
                           result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "metabolite", pObjectParent->getObjectName().c_str()));
                         }
                     }
                 }
               else if (typeString == "ModelValue")
                 {
                   // must be a reference to the transient or initial value
                   if (initialExpression == true)
                     {
                       if (pObject->getObjectName() != "InitialValue")
{
                           result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "parameter", pObjectParent->getObjectName().c_str()));
                         }
                     }
                   else
                     {
                       if (pObject->getObjectName() == "InitialValue"
                           && initialMap != NULL
                           && (sbmlLevel > 2 || (sbmlLevel == 2 && sbmlVersion > 1)))
{
                           // add new parameter for the initial value
                           addToInitialValueMap(initialMap, pObject, pObjectParent, sbmlLevel, sbmlVersion);
                         }
                       else if (pObject->getObjectName() != "Value"
                                && pObject->getObjectName() != "Rate")
{
                           result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "parameter", pObjectParent->getObjectName().c_str()));
                         }
                     }
                 }
               else if (typeString == "Model")
                 {
                   // must be a reference to the model time
                   if (pObject->getObjectName() != "Time")
                     {
                       result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "model", pObjectParent->getObjectName().c_str()));
                     }
                 }
               else if (typeString == "Parameter")
                 {
                   // must be a local parameter
                   if (pObject->getObjectName() != "Value")
                     {
                       result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "local parameter", pObjectParent->getObjectName().c_str()));
                     }
                 }
               else
                 {
                   if (sbmlLevel == 1 || (sbmlLevel == 2 && sbmlVersion == 1))
                     {
                       result.push_back(SBMLIncompatibility(10, pObject->getObjectName().c_str(), typeString.c_str(), pObjectParent->getObjectName().c_str()));
                     }
                   else
                     {
                       if (typeString == "Reaction")
{
                           if (pObject->getObjectName() != "Flux")
{
                               result.push_back(SBMLIncompatibility(1, pObject->getObjectName().c_str(), "reaction", pObjectParent->getObjectName().c_str()));
                             }
                         }
                     }
                 }
             }
           else
             {
               // normally local parameters are referenced via their value and
               // not directly, so this code should never be called
               const CCopasiParameter* pLocalParameter = dynamic_cast<const CCopasiParameter*>(pObject);
               if (pLocalParameter == NULL)
                 {
                   result.push_back(SBMLIncompatibility(1, "value", pObject->getObjectType().c_str() , pObject->getObjectName().c_str()));
                 }
             }
         }
     }
 }
void CSBMLExporter::collectIds (const CCopasiDataModel & dataModel, std::map< std::string, const SBase * > & idMap) protected
This method goes through the given datamodel and collects all SBML ids.
Definition at line 7465 of file CSBMLExporter.cpp.
References CModel::getCompartments(), CModel::getEvents(), CCopasiRootContainer::getFunctionList(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CModel::getModelValues(), CModel::getReactions(), CFunction::getSBMLId(), CModelEntity::getSBMLId(), CEvent::getSBMLId(), CReaction::getSBMLId(), CFunctionDB::loadedFunctions(), and CCopasiVector< T >::size().
Referenced by createSBMLDocument().
 {
   size_t i, iMax = CCopasiRootContainer::getFunctionList()->loadedFunctions().size();
   std::string id;
   for (i = 0; i < iMax; ++i)
     {
       const CFunction* pFun = CCopasiRootContainer::getFunctionList()->loadedFunctions()[i];
       id = pFun->getSBMLId();
       if (!id.empty())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
         }
     }
   const CModel* pModel = dataModel.getModel();
   id = pModel->getSBMLId();
   if (!id.empty())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
     }
   iMax = pModel->getCompartments().size();
   for (i = 0; i < iMax; ++i)
     {
       const CCompartment* pObj = pModel->getCompartments()[i];
       id = pObj->getSBMLId();
       if (!id.empty())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
         }
     }
   iMax = pModel->getMetabolites().size();
   for (i = 0; i < iMax; ++i)
     {
       const CMetab* pObj = pModel->getMetabolites()[i];
       id = pObj->getSBMLId();
       if (!id.empty())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
         }
     }
   iMax = pModel->getModelValues().size();
   for (i = 0; i < iMax; ++i)
     {
       const CModelValue* pObj = pModel->getModelValues()[i];
       id = pObj->getSBMLId();
       if (!id.empty())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
         }
     }
   iMax = pModel->getReactions().size();
   for (i = 0; i < iMax; ++i)
     {
       const CReaction* pObj = pModel->getReactions()[i];
       id = pObj->getSBMLId();
       if (!id.empty())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
         }
     }
   iMax = pModel->getEvents().size();
   for (i = 0; i < iMax; ++i)
     {
       const CEvent* pObj = pModel->getEvents()[i];
       id = pObj->getSBMLId();
       if (!id.empty())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(id, (const SBase*)NULL));
         }
     }
 }
static void CSBMLExporter::convert_to_l1v1 (std::string & l1v2_string) static protected
Converts the SBML model given in SBML Level 1 Version 2 format to SBML Level 1 Version 1. The method basically removes the namespace attribute on the sbml element and changes the version from 2 to 1. It also renames all "species" elements to "specie". All other changes between SBML Level 1 Version 2 and Level 1 Version 1 should not be relevant here.
Referenced by exportModelToString().
ASTNode * CSBMLExporter::convertASTTreeToLevel1 (const ASTNode * pNode, const ListOfFunctionDefinitions & functions, std::string & message) static protected
Creates an ASTNode based tree where all occurences of nodes that are not supported in SBML Level 1 are replaced by supported constructs. On error an exception is created. The caller is responsible for freeing the memory of the returned object.
Definition at line 5507 of file CSBMLExporter.cpp.
References create_expression(), CCopasiMessage::EXCEPTION, MCSBML, and replaceL1IncompatibleNodes().
Referenced by convertToLevel1().
 {
   ASTNode* pExpanded = create_expression(pNode, &functions);
   if (pExpanded != NULL)
     {
       ASTNode* pReplaced = CSBMLExporter::replaceL1IncompatibleNodes(pExpanded);
       delete pExpanded;
       if (pReplaced == NULL)
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 62, message.c_str());
         }
       pExpanded = pReplaced;
     }
   else
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 61, message.c_str());
     }
   return pExpanded;
 }
ASTNode * CSBMLExporter::convertToASTNode (const CEvaluationNode * pOrig, CCopasiDataModel & dataModel) protected
This converts an CEvaluationNode based tree to an ASTNode tree. It makes sure that all functions used in function calls already have a unique SBML id.
Definition at line 7078 of file CSBMLExporter.cpp.
References adjustNames(), mIdMap, mpSBMLDocument, pResult, setFunctionSBMLIds(), and CEvaluationNode::toAST().
Referenced by createEvent(), createFunctionDefinition(), createInitialAssignment(), createKineticLaw(), createRule(), and exportEventAssignments().
 {
   // first go through the tree and check that all function calls are to
   // functions that have an SBML id
   // if they don't, we have to set one
   this->setFunctionSBMLIds(pOrig, dataModel);
   ASTNode* pResult = pOrig->toAST(&dataModel);
   adjustNames(pResult, mpSBMLDocument, mIdMap);
   return pResult;
 }
void CSBMLExporter::convertToLevel1 () protected
This method takes care of expanding all function calls in all expressions and converting functions that are not supported in Level 1 as well as constants that were not supported in Level 1
Definition at line 5230 of file CSBMLExporter.cpp.
References convertASTTreeToLevel1(), fatalError, mExportedFunctions, and mpSBMLDocument.
Referenced by createSBMLDocument().
 {
   // expand all function calls in rules, events and
   // kinetic laws and delete the functions
   // initial assignments do not need to be considered since they can not be
   // exported to Level 1 anyway
   //
   // checking of the resulting expressions for piecewise functions
   // is done in the convertASTTreeToLevel1 method
   if (this->mpSBMLDocument == NULL) return;
   Model* pModel = this->mpSBMLDocument->getModel();
   Rule* pRule = NULL;
   Reaction* pReaction = NULL;
   KineticLaw* pLaw = NULL;
   unsigned int i, iMax = pModel->getNumRules();
   for (i = 0; i < iMax; ++i)
     {
       pRule = pModel->getRule(i);
       assert(pRule != NULL);
       const ASTNode* pMath = pRule->getMath();
       assert(pMath != NULL);
       std::string message = "rule for object with id \"";
       message += pRule->getVariable();
       message += "\"";
       ASTNode* pNewMath = CSBMLExporter::convertASTTreeToLevel1(pMath, this->mExportedFunctions, message);
       assert(pNewMath != NULL);
       if (pNewMath != NULL)
         {
           pRule->setMath(pNewMath);
           delete pNewMath;
         }
     }
   iMax = pModel->getNumReactions();
   for (i = 0; i < iMax; ++i)
     {
       pReaction = pModel->getReaction(i);
       assert(pReaction != NULL);
       pLaw = pReaction->getKineticLaw();
       // maybe we don't have a kinetic law for all reactions
       if (pLaw != NULL)
         {
           const ASTNode* pMath = pLaw->getMath();
           assert(pMath != NULL);
           std::string message = "kinetic law in reaction with id \"";
           message += pReaction->getId();
           message += "\"";
           ASTNode* pNewMath = CSBMLExporter::convertASTTreeToLevel1(pMath, this->mExportedFunctions, message);
           assert(pNewMath != NULL);
           if (pNewMath != NULL)
             {
               pLaw->setMath(pNewMath);
               delete pNewMath;
             }
           else
             {
               fatalError();
             }
         }
     }
 }
void CSBMLExporter::createAreaUnit (const CCopasiDataModel & dataModel) protected
Creates the volume unit for the SBML model.
Creates the area unit for the SBML model.
Definition at line 798 of file CSBMLExporter.cpp.
References SBMLImporter::areSBMLUnitDefinitionsIdentical(), CModel::cm, CModel::dimensionlessLength, CModel::dm, CCopasiMessage::EXCEPTION, CModel::fm, CModel::getAreaUnitEnum(), CCopasiDataModel::getModel(), INIT_DEFAULTS, CModel::m, CModel::microm, CModel::mm, mpSBMLDocument, mSBMLLevel, mSBMLVersion, CModel::nm, and CModel::pm.
Referenced by createUnits().
 {
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   UnitDefinition uDef(this->mSBMLLevel, this->mSBMLVersion);
   uDef.setName("area");
   uDef.setId("area");
   Unit unit(this->mSBMLLevel, this->mSBMLVersion);
   INIT_DEFAULTS(unit);
   switch (dataModel.getModel()->getAreaUnitEnum())
     {
       case CModel::m:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(0);
         break;
       case CModel::dm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-1);
         break;
       case CModel::cm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-2);
         break;
       case CModel::mm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-3);
         break;
       case CModel::microm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-6);
         break;
       case CModel::nm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-9);
         break;
       case CModel::pm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-12);
         break;
       case CModel::fm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(2);
         unit.setScale(-15);
         break;
       case CModel::dimensionlessLength:
         unit.setKind(UNIT_KIND_DIMENSIONLESS);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, "SBMLExporter Error: Unknown copasi area unit.");
         break;
     }
   unit.setMultiplier(1.0);
   uDef.addUnit(&unit);
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   UnitDefinition* pUdef = pSBMLModel->getUnitDefinition("area");
   if (pUdef != NULL)
     {
       // check if it is the same unit as the existing one if there is one
       // if yes, return, else replace the existing one
       if (!SBMLImporter::areSBMLUnitDefinitionsIdentical(pUdef, &uDef))
         {
           (*pUdef) = uDef;
         }
     }
   else
     {
       // only add it if it is not the default unit definition anyway
       if (this->mSBMLLevel > 2 ||
           unit.getKind() != UNIT_KIND_METRE ||
           unit.getScale() != 0 ||
           unit.getExponent() != 2 ||
           unit.getMultiplier() != 1.0)
         {
           // set the unit definition
           pSBMLModel->addUnitDefinition(&uDef);
         }
     }
 // if we write an SBML L3 document, we have to explicitely set the units on the model
 #if LIBSBML_VERSION >= 40100
   if (this->mSBMLLevel > 2)
     {
       pSBMLModel->setAreaUnits(uDef.getId());
     }
 #endif // LIBSBML_VERSION
 }
void CSBMLExporter::createCompartment (CCompartment & compartment) protected
Creates the compartment for the given COPASI compartment.
Definition at line 928 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, createUniqueId(), fatalError, CCompartment::getDimensionality(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CCopasiObject::getObjectName(), CModelEntity::getSBMLId(), CModelEntity::getStatus(), INIT_DEFAULTS, mAssignmentVector, mCOPASI2SBMLMap, mHandledSBMLObjects, mIdMap, mInitialAssignmentVector, mMetaIdMap, mODEVector, mpSBMLDocument, mSBMLLevel, CModelEntity::ODE, removeInitialAssignment(), removeRule(), CModelEntity::setSBMLId(), setSBMLNotes(), and updateMIRIAMAnnotation().
Referenced by createCompartments().
 {
   Compartment* pSBMLCompartment = NULL;
   std::string sbmlId = compartment.getSBMLId();
   if (!sbmlId.empty())
     {
       pSBMLCompartment = this->mpSBMLDocument->getModel()->getCompartment(sbmlId);
       if (pSBMLCompartment == NULL)
         {
           pSBMLCompartment = this->mpSBMLDocument->getModel()->createCompartment();
           this->mCOPASI2SBMLMap[&compartment] = pSBMLCompartment;
           pSBMLCompartment->setId(sbmlId);
         }
     }
   else
     {
       pSBMLCompartment = this->mpSBMLDocument->getModel()->createCompartment();
       this->mCOPASI2SBMLMap[&compartment] = pSBMLCompartment;
       sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, compartment.getObjectName(), false);
       compartment.setSBMLId(sbmlId);
       pSBMLCompartment->setId(sbmlId);
     }
   INIT_DEFAULTS((*pSBMLCompartment));
   this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, pSBMLCompartment));
   this->mHandledSBMLObjects.insert(pSBMLCompartment);
   // don't call setName on level 1 objects because this will also
   // change the id
   if (this->mpSBMLDocument->getLevel() > 1)
     {
       pSBMLCompartment->setName(compartment.getObjectName().c_str());
     }
   pSBMLCompartment->setSpatialDimensions((unsigned int)compartment.getDimensionality());
   double value = compartment.getInitialValue();
   // if the value is NaN, unset the initial volume
   if (!isnan(value))
     {
       pSBMLCompartment->setVolume(value);
     }
   else
     {
       pSBMLCompartment->unsetVolume();
     }
   // fill assignment set
   // a compartment can either have an assignment or an initial assignment but not
   // both
   CModelEntity::Status status = compartment.getStatus();
   if (status == CModelEntity::ASSIGNMENT)
     {
       if (compartment.getDimensionality() != 0)
         {
           this->mAssignmentVector.push_back(&compartment);
           pSBMLCompartment->setConstant(false);
           removeInitialAssignment(pSBMLCompartment->getId());
         }
       else
         {
           fatalError();
         }
     }
   else if (status == CModelEntity::ODE)
     {
       if (compartment.getDimensionality() != 0)
         {
           this->mODEVector.push_back(&compartment);
           pSBMLCompartment->setConstant(false);
           if (compartment.getInitialExpression() != "")
             {
               this->mInitialAssignmentVector.push_back(&compartment);
             }
           else
             {
               removeInitialAssignment(pSBMLCompartment->getId());
             }
         }
       else
         {
           fatalError();
         }
     }
   else
     {
       // do this explicitly since we might handle an existing object from an
       // earlier import that had it attribute set already
       if (this->mSBMLLevel != 1)
         {
           pSBMLCompartment->setConstant(true);
         }
       else
         {
           // Level 1 does not know the constant flag and libsbmnl does not drop
           // it automatically
           pSBMLCompartment->setConstant(false);
         }
       removeRule(pSBMLCompartment->getId());
       // fill initial assignment set
       if (compartment.getInitialExpression() != "")
         {
           if (compartment.getDimensionality() != 0)
             {
               this->mInitialAssignmentVector.push_back(&compartment);
             }
           else
             {
               fatalError();
             }
         }
       else
         {
           removeInitialAssignment(pSBMLCompartment->getId());
         }
     }
   if (pSBMLCompartment != NULL)
     {
       CSBMLExporter::setSBMLNotes(pSBMLCompartment, &compartment);
     }
   if (pSBMLCompartment != NULL && mSBMLLevel == 3)
     {
       pSBMLCompartment->setUnits("volume");
     }
   CSBMLExporter::updateMIRIAMAnnotation(&compartment, pSBMLCompartment, this->mMetaIdMap);
 }
void CSBMLExporter::createCompartments (CCopasiDataModel & dataModel) protected
Creates the compartments for the model.
Definition at line 911 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), createCompartment(), CCopasiVector< T >::end(), CModel::getCompartments(), CCopasiDataModel::getModel(), and mpSBMLDocument.
Referenced by createSBMLDocument().
 {
   // make sure the SBML Document already exists and that it has a Model set
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   CCopasiVectorNS<CCompartment>::const_iterator it = dataModel.getModel()->getCompartments().begin(), endit = dataModel.getModel()->getCompartments().end();
   while (it != endit)
     {
       createCompartment(**it);
       ++it;
     }
 }
void CSBMLExporter::createEvent (CEvent & event, Event * pSBMLEvent, CCopasiDataModel & dataModel) protected
Creates an SBML Event for the given COPASI event.
Definition at line 4005 of file CSBMLExporter.cpp.
References convertExpression(), convertToASTNode(), createFunctionSetFromFunctionNames(), createUniqueId(), CCopasiMessage::EXCEPTION, exportEventAssignments(), findDirectlyUsedFunctions(), CEvent::getDelayAssignment(), CCopasiRootContainer::getFunctionList(), CEvaluationTree::getInfix(), CCopasiObject::getObjectName(), CEvaluationTree::getRoot(), CEvent::getSBMLId(), CEvaluationNode::getType(), CEvaluationNode::INVALID, isExpressionSBMLCompatible(), mCOPASI2SBMLMap, MCSBML, mIdMap, mIncompatibilities, mIncompleteExport, mInitialValueMap, mMetaIdMap, mpSBMLDocument, mSBMLLevel, mSBMLVersion, mUsedFunctions, outputIncompatibilities(), replace_local_parameters(), replaceSpeciesReferences(), CEvaluationTree::setInfix(), setSBMLNotes(), CEvaluationNode::type(), updateMIRIAMAnnotation(), and CCopasiMessage::WARNING.
Referenced by createEvents().
 {
   // once events are functional, we create them here
   // don't forget to call replaceSpeciesReferences
   // on all mathematical expressions
   // first check if we already have a corresponding event from an earlier
   // import or export
   // if none is found, we create a new event object
   if (pSBMLEvent == NULL)
     {
       pSBMLEvent = this->mpSBMLDocument->getModel()->createEvent();
     }
   else
     {
       // Read the event to the model
       if (this->mpSBMLDocument->getModel()->getListOfEvents()->appendAndOwn(pSBMLEvent) != LIBSBML_OPERATION_SUCCESS)
         {
           // the existing event is not valid and cannot be added to the model, delete and create a new one instead
           delete pSBMLEvent;
           pSBMLEvent = this->mpSBMLDocument->getModel()->createEvent();
         }
     }
   // add the object to the COPASI2SBMLMap
   this->mCOPASI2SBMLMap[&event] = pSBMLEvent;
   // a)  we set the name and the id
   if (!pSBMLEvent->isSetId())
     {
       std::string sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, event.getObjectName(), false);
       this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, pSBMLEvent));
       pSBMLEvent->setId(sbmlId);
       event.setSBMLId(sbmlId);
     }
   // The attribute 'useValuesfromTriggerTime' is mandatory in L3V1
   if (this->mSBMLLevel > 2)
     {
       pSBMLEvent->setUseValuesFromTriggerTime(event.getDelayAssignment());
     }
 #if LIBSBML_VERSION >= 40200
   // if the event came from an SBML L3 model, we have to make sure that the
   // priority is not set when we export the event, otherwise the exported model
   // and the COPASI model will not behave the same.
   if (this->mSBMLLevel > 2)
     {
       pSBMLEvent->setPriority(NULL);
     }
 #endif  // LIBSBML_VERSION >= 40200
   // if the name doesn't consists of whitespace only, we set the name
   if (event.getObjectName().find_first_not_of("\t\r\n ") != std::string::npos)
     {
       pSBMLEvent->setName(event.getObjectName());
     }
   // b) we check the trigger expression and export the trigger
   const CExpression* pExpression = event.getTriggerExpressionPtr();
   assert(pExpression != NULL);
   std::vector<SBMLIncompatibility> result;
   CSBMLExporter::isExpressionSBMLCompatible(*pExpression
       , dataModel
       , this->mSBMLLevel
       , this->mSBMLVersion
       , result
       , std::string("event trigger for event with id\"+" + event.getSBMLId() + "\"")
       , false
       , &mInitialValueMap);
   // collect directly used functions
   if (result.empty())
     {
       std::set<std::string> directlyUsedFunctionNames;
       CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), directlyUsedFunctionNames);
       std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(directlyUsedFunctionNames, CCopasiRootContainer::getFunctionList());
 # if defined _MSC_VER && _MSC_VER < 1201 // 1200 Identifies Visual C++ 6.0
       {
         std::set<CFunction*>::const_iterator it = usedFunctions.begin();
         std::set<CFunction*>::const_iterator end = usedFunctions.end();
         for (; it != end; ++it)
           this->mUsedFunctions.insert(*it);
       }
 #else
       this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
 #endif
     }
   else
     {
       this->mIncompatibilities.insert(this->mIncompatibilities.end(), result.begin(), result.end());
       if (!this->mIncompleteExport)
         {
           this->outputIncompatibilities();
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "trigger expression", "event", event.getObjectName().c_str());
         }
     }
   const std::string& changedExpression = convertExpression(pExpression->getInfix(), mInitialValueMap);
   CEvaluationTree tree;
   tree.setInfix(changedExpression);
   const CEvaluationNode* pOrigNode = tree.getRoot();
   //const CEvaluationNode* pOrigNode = pExpression->getRoot();
   if (CEvaluationNode::type(pOrigNode->getType()) == CEvaluationNode::INVALID)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 70, "trigger", "event", event.getObjectName().c_str());
     }
   // the next few lines replace references to species depending on whether
   // it is a reference to an amount or a reference to a concentration.
   // Other factors that influence this replacement are if the model
   // contains variable volumes or if the quantity units are set to CModel::number
   pOrigNode = this->replaceSpeciesReferences(pOrigNode, dataModel);
   assert(pOrigNode != NULL);
   ASTNode* pNode = this->convertToASTNode(pOrigNode, dataModel);
   delete pOrigNode;
   // convert local parameters that are referenced in an expression to global
   // parameters
   this->replace_local_parameters(pNode, dataModel);
   if (pNode != NULL)
     {
       Trigger* pTrigger = pSBMLEvent->createTrigger();
       pTrigger->setMath(pNode);
 #if LIBSBML_VERSION >= 40200
       // we need to make sure that the initial value of the trigger is set to true
       // as well as the persistent flag
       // for L3 event because otherwise the exported model will not do the same as
       // the model in COPASI
       if (this->mSBMLLevel > 2)
         {
           pTrigger->setInitialValue(true);
           pTrigger->setPersistent(true);
         }
 #endif  // LIBSBML_VERSION >= 40200
       delete pNode;
     }
   else
     {
       if (this->mIncompleteExport != true)
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "trigger", "event", event.getObjectName().c_str());
         }
     }
   // c) we check the delay expression and export it if it is set
   pExpression = event.getDelayExpressionPtr();
   const std::string delayInfix = pExpression == NULL ? "" : pExpression->getInfix();
   if (!delayInfix.empty())
     {
       result.clear();
       CSBMLExporter::isExpressionSBMLCompatible(*pExpression
           , dataModel
           , this->mSBMLLevel
           , this->mSBMLVersion
           , result
           , std::string("event delay for event with id\"+" + event.getSBMLId() + "\"").c_str()
           , false
           , &mInitialValueMap);
       // collect directly used functions
       if (result.empty())
         {
           std::set<std::string> directlyUsedFunctionNames;
           CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), directlyUsedFunctionNames);
           std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(directlyUsedFunctionNames, CCopasiRootContainer::getFunctionList());
 # if defined _MSC_VER && _MSC_VER < 1201 // 1200 Identifies Visual C++ 6.0
           {
             it = usedFunctions.begin();
             usedFunctions.end();
             for (; it != end; ++it)
               this->mUsedFunctions.insert(*it);
           }
 #else
           this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
 #endif
         }
       else
         {
           this->mIncompatibilities.insert(this->mIncompatibilities.end(), result.begin(), result.end());
           if (!this->mIncompleteExport)
             {
               this->outputIncompatibilities();
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "delay expression", "event", event.getObjectName().c_str());
             }
         }
       //pOrigNode = pExpression->getRoot();
       const std::string& changedExpression = convertExpression(pExpression->getInfix(), mInitialValueMap);
       CEvaluationTree tree;
       tree.setInfix(changedExpression);
       const CEvaluationNode* pOrigNode = tree.getRoot();
       if (CEvaluationNode::type(pOrigNode->getType()) == CEvaluationNode::INVALID)
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 70, "delay", "event", event.getObjectName().c_str());
         }
       // the next few lines replace references to species depending on whether
       // it is a reference to an amount or a reference to a concentration.
       // Other factors that influence this replacement are if the model
       // contains variable volumes or if the quantity units are set to CModel::number
       pOrigNode = this->replaceSpeciesReferences(pOrigNode, dataModel);
       assert(pOrigNode != NULL);
       pNode = this->convertToASTNode(pOrigNode, dataModel);
       delete pOrigNode;
       // convert local parameters that are referenced in an expression to global
       // parameters
       this->replace_local_parameters(pNode, dataModel);
       if (pNode != NULL)
         {
           Delay* pDelay = new Delay(this->mSBMLLevel, this->mSBMLVersion);
           pDelay->setMath(pNode);
           pSBMLEvent->setDelay(pDelay);
           delete pNode;
           delete pDelay;
           if (this->mSBMLLevel == 2 && this->mSBMLVersion >= 4)
             {
               pSBMLEvent->setUseValuesFromTriggerTime(event.getDelayAssignment());
             }
           // if the delayAssignment is set to false, we have a problem
           // because the model semantic changes on export
           else if (event.getDelayAssignment() == false &&
                    this->mSBMLLevel <= 2 &&
                    this->mSBMLVersion <= 3)
             {
               CCopasiMessage(CCopasiMessage::WARNING, MCSBML + 77, event.getObjectName().c_str(), this->mSBMLLevel, this->mSBMLVersion);
             }
         }
       else
         {
           if (this->mIncompleteExport != true)
             {
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "delay", "event", event.getObjectName().c_str());
             }
         }
     }
   // export all event assignments
   this->exportEventAssignments(event, pSBMLEvent, dataModel);
   // check if the event has event assignments, if not, we have to delete
   // the event and create an error message (for SBML Levels < 3)
   if (pSBMLEvent->getNumEventAssignments() == 0 && mpSBMLDocument->getLevel() < 3)
     {
       unsigned int i, iMax = this->mpSBMLDocument->getModel()->getNumEvents();
       // the following code does not check if the corrct pointer is found
       // but this should not be a problem
       for (i = 0; i < iMax; ++i)
         {
           if (this->mpSBMLDocument->getModel()->getEvent(i) == pSBMLEvent)
             {
               this->mpSBMLDocument->getModel()->getListOfEvents()->remove(i);
             }
         }
       delete pSBMLEvent;
       this->mCOPASI2SBMLMap.erase(&event);
       pSBMLEvent = NULL;
       CCopasiMessage(CCopasiMessage::WARNING, "The event '%s' contained no event assignments, this is only supported for SBML Level 3 onwards. The event has not been exported.", event.getObjectName().c_str());
     }
   if (pSBMLEvent != NULL)
     {
       CSBMLExporter::setSBMLNotes(pSBMLEvent, &event);
       CSBMLExporter::updateMIRIAMAnnotation(&event, pSBMLEvent, this->mMetaIdMap);
     }
 }
void CSBMLExporter::createEvents (CCopasiDataModel & dataModel) protected
Creates the events for the given data model.
Definition at line 3938 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), checkForEvents(), createEvent(), CCopasiVector< T >::end(), CModel::getEvents(), CCopasiDataModel::getModel(), mCOPASI2SBMLMap, mIncompatibilities, mpSBMLDocument, and mSBMLLevel.
Referenced by createSBMLDocument().
 {
   if (this->mSBMLLevel == 1)
     {
       CSBMLExporter::checkForEvents(dataModel, this->mIncompatibilities);
       return;
     }
   // bail early
   if (dataModel.getModel() == NULL)
     return;
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   if (pSBMLModel == NULL)
     return;
   // remove all events from the SBML model and put them in a set
   std::set<Event*> eventSet;
   while (pSBMLModel->getNumEvents() != 0)
     {
       Event* pEvent = pSBMLModel->getListOfEvents()->remove(pSBMLModel->getNumEvents() - 1);
       assert(pEvent != NULL);
       eventSet.insert(pEvent);
     }
   const CCopasiVectorN<CEvent>& events = dataModel.getModel()->getEvents();
   CCopasiVectorN<CEvent>::const_iterator it = events.begin(), endit = events.end();
   Event* pSBMLEvent = NULL;
   std::map<const CCopasiObject*, SBase*>::const_iterator pos;
   while (it != endit)
     {
       // find the old event if there is one
       pos = this->mCOPASI2SBMLMap.find(*it);
       if (pos != this->mCOPASI2SBMLMap.end())
         {
           pSBMLEvent = dynamic_cast<Event*>(pos->second);
         }
       else
         {
           pSBMLEvent = NULL;
         }
       // remove the event from the set
       if (pSBMLEvent) eventSet.erase(pSBMLEvent);
       this->createEvent(**it, pSBMLEvent, dataModel);
       ++it;
     }
   // make sure events that have already been deleted do not get
   // exported
   std::set<Event*>::iterator it2 = eventSet.begin(), endit2 = eventSet.end();
   while (it2 != endit2)
     {
       delete *it2;
       ++it2;
     }
 }
void CSBMLExporter::createFunctionDefinition (CFunction & function, CCopasiDataModel & dataModel) protected
Create the SBML function definition from the given COPASI function.
Definition at line 3107 of file CSBMLExporter.cpp.
References convertToASTNode(), createUniqueId(), CCopasiMessage::EXCEPTION, isExpressionSBMLCompatible(), isValidSId(), mCOPASI2SBMLMap, MCSBML, mExportedFunctions, mFunctionMap, mIdMap, mIncompatibilities, mMetaIdMap, mpSBMLDocument, mSBMLLevel, mSBMLVersion, setSBMLNotes(), CFunctionParameters::size(), updateMIRIAMAnnotation(), and CCopasiMessage::WARNING.
Referenced by createFunctionDefinitions().
 {
   // check the expression
   std::map<const CCopasiObject*, SBase*>::iterator pos = this->mCOPASI2SBMLMap.find(&function);
   FunctionDefinition* pFunDef = NULL;
   // the entry could be NULL when exporting to L2 first and then to L3 because the
   // SBMLExporter::collectIds will add a NULL entry into the id table which will be
   // tranferred to the COPASI2SBMLMap.
   if (pos != this->mCOPASI2SBMLMap.end() && pos->second != NULL)
     {
       pFunDef = dynamic_cast<FunctionDefinition*>(pos->second);
       assert(pFunDef);
       this->mpSBMLDocument->getModel()->getListOfFunctionDefinitions()->appendAndOwn(pFunDef);
     }
   else
     {
       if (this->mpSBMLDocument->getLevel() == 1)
         {
           pFunDef = new FunctionDefinition(2, 4);
         }
       else
         {
           pFunDef = new FunctionDefinition(this->mpSBMLDocument->getLevel(), this->mpSBMLDocument->getVersion());
         }
       this->mFunctionMap[pFunDef] = &function;
       pFunDef->setName(function.getObjectName());
       std::string id = function.getSBMLId();
       if (id.empty())
         {
           id = function.getObjectName();
           if (CSBMLExporter::isValidSId(id))
             {
               if (this->mIdMap.find(id) != this->mIdMap.end())
                 {
                   id = CSBMLExporter::createUniqueId(this->mIdMap, id, true);
                 }
             }
           else
             {
               id = CSBMLExporter::createUniqueId(this->mIdMap, function.getObjectName(), false);
             }
         }
       this->mIdMap.insert(std::pair<const std::string, const SBase*>(id, pFunDef));
       pFunDef->setId(id);
       function.setSBMLId(id);
       this->mCOPASI2SBMLMap[&function] = pFunDef;
     }
   if (function.getRoot() == NULL)
     {
       std::string errorMessage = std::string("Can not export function '");
       errorMessage += function.getObjectName();
       errorMessage += std::string("'. Function does not have a valid root node.");
       CCopasiMessage(CCopasiMessage::EXCEPTION, errorMessage.c_str());
     }
   else
     {
       std::vector<SBMLIncompatibility> result;
       CSBMLExporter::isExpressionSBMLCompatible(function, dataModel, this->mSBMLLevel, this->mSBMLVersion, result, std::string("function with name \"" + function.getObjectName() + "\"").c_str());
       if (result.empty())
         {
           ASTNode* pFunNode = this->convertToASTNode(function.getRoot(), dataModel);
           // go through the AST tree and replace all function call nodes with with a call to the sbml id
           ASTNode* pLambda = new ASTNode(AST_LAMBDA);
           // add the parameters to the function definition
           const CFunctionParameters& funParams = function.getVariables();
           size_t i, iMax = funParams.size();
           ASTNode* pParamNode = NULL;
           for (i = 0; i < iMax; ++i)
             {
               pParamNode = new ASTNode(AST_NAME);
               pParamNode->setName(funParams[i]->getObjectName().c_str());
               pLambda->addChild(pParamNode);
             }
           pLambda->addChild(pFunNode);
           if (pFunDef->setMath(pLambda) != LIBSBML_OPERATION_SUCCESS)
             {
               CCopasiMessage(CCopasiMessage::WARNING,
                              "The function '%s' uses an invalid expression '%s' that cannot be exported to SBML, the function definition is not exported."
                              , function.getObjectName().c_str()
                              , function.getInfix().c_str());
             }
           this->mExportedFunctions.appendAndOwn(pFunDef);
           delete pLambda;
         }
       else
         {
           this->mIncompatibilities.insert(this->mIncompatibilities.end(), result.begin(), result.end());
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 28, function.getObjectName().c_str());
         }
     }
   if (pFunDef != NULL)
     {
       CSBMLExporter::setSBMLNotes(pFunDef, &function);
     }
   CSBMLExporter::updateMIRIAMAnnotation(&function, pFunDef, this->mMetaIdMap);
 }
void CSBMLExporter::createFunctionDefinitions (CCopasiDataModel & dataModel) protected
Create all function definitions.
Definition at line 2940 of file CSBMLExporter.cpp.
References createFunctionDefinition(), fatalError, findUsedFunctions(), CCopasiRootContainer::getFunctionList(), CCopasiObject::getObjectName(), mCOPASI2SBMLMap, mExportedFunctions, mFunctionMap, mpSBMLDocument, and mUsedFunctions.
Referenced by createSBMLDocument().
 {
   this->mExportedFunctions.clear(true);
   this->mFunctionMap.clear();
   // make sure the list of used functions is filled before this is
   // called
   // make sure the mCOPASI2SBMLMap is up to date
   // find all indirectly called functions
   std::vector<CFunction*> usedFunctions = findUsedFunctions(this->mUsedFunctions, CCopasiRootContainer::getFunctionList());
   this->mUsedFunctions.clear();
   this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
   // remove the function calls that have been created by copasi solely for use
   // as a kinetic law term if it is no longer needed
   Model* pModel = this->mpSBMLDocument->getModel();
   assert(pModel);
   if (pModel == NULL) fatalError();
   std::map<SBase*, const CCopasiObject*> sbml2copasiMap;
   std::map<const CCopasiObject*, SBase*>::iterator mapIt = this->mCOPASI2SBMLMap.begin();
   std::map<const CCopasiObject*, SBase*>::iterator mapEndit = this->mCOPASI2SBMLMap.end();
   while (mapIt != mapEndit)
     {
       sbml2copasiMap.insert(std::make_pair(mapIt->second, mapIt->first));
       ++mapIt;
     }
   std::set<CFunction*> unusedFunctions;
   unsigned int i = 0, iMax = pModel->getNumFunctionDefinitions();
   std::map<SBase*, const CCopasiObject*>::iterator mapPos;
   std::set<std::string> toRemove;
   while (i < iMax)
     {
       FunctionDefinition* pFunDef = pModel->getFunctionDefinition(i);
       if (pFunDef != NULL)
         {
           mapPos = sbml2copasiMap.find(pFunDef);
           if (mapPos != sbml2copasiMap.end())
             {
               CFunction* pFun = dynamic_cast<CFunction*>(const_cast<CCopasiObject*>(mapPos->second));
               if (pFun != NULL && this->mUsedFunctions.find(pFun) == this->mUsedFunctions.end())
                 {
                   // the function exists in the model, but it is not used in any
                   // expression
                   if (pFun->getObjectName().find("function_4_") == 0 || pFun->getObjectName().find("Function for ") == 0)
                     {
                       // store the function definition that is to be removed
                       toRemove.insert(pFunDef->getId());
                     }
                   else
                     {
                       // those need to be stored in a separate list since we also
                       // need to find indirectly called functions
                       unusedFunctions.insert(pFun);
                     }
                 }
             }
         }
       ++i;
     }
   // find all indirectly called functions for the unused functions
   std::vector<CFunction*> functionsVect = findUsedFunctions(unusedFunctions, CCopasiRootContainer::getFunctionList());
   usedFunctions.insert(usedFunctions.end(), functionsVect.begin(), functionsVect.end());
   // reset the used functions set
   this->mUsedFunctions.clear();
   this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
   // now we remove the function definitions from the SBML model
   std::set<std::string>::iterator toRemoveIt = toRemove.begin();
   std::set<std::string>::iterator toRemoveEndit = toRemove.end();
   while (toRemoveIt != toRemoveEndit)
     {
       FunctionDefinition* pFunDef = pModel->getFunctionDefinition(*toRemoveIt);
       if (pFunDef != NULL)
         {
           mapPos = sbml2copasiMap.find(pFunDef);
           if (mapPos != sbml2copasiMap.end() &&
               this->mUsedFunctions.find(dynamic_cast<CFunction*>(const_cast<CCopasiObject*>(mapPos->second))) == this->mUsedFunctions.end())
             {
               pModel->getListOfFunctionDefinitions()->remove(*toRemoveIt);
             }
         }
       ++toRemoveIt;
     }
   // order the remaining function definitions
   // remove duplicates from the vector, always keep the last one
   std::vector<CFunction*>::reverse_iterator reverseIt = usedFunctions.rbegin(), reverseEndit = usedFunctions.rend();
   functionsVect.clear();
   while (reverseIt != reverseEndit)
     {
       if (std::find(functionsVect.begin(), functionsVect.end(), *reverseIt) == functionsVect.end())
         {
           functionsVect.insert(functionsVect.begin(), *reverseIt);
         }
       ++reverseIt;
     }
   // remove all existing function definitions from the list
   // and remove their entries from the copasi2sbmlmap
   iMax = pModel->getNumFunctionDefinitions();
   for (unsigned int i = 0; i < iMax; ++i)
     {
       mapIt = this->mCOPASI2SBMLMap.begin();
       mapEndit = this->mCOPASI2SBMLMap.end();
       while (mapIt != mapEndit)
         {
           if (mapIt->second == pModel->getFunctionDefinition(i))
             {
               this->mCOPASI2SBMLMap.erase(mapIt->first);
               break;
             }
           ++mapIt;
         }
     }
   // don't want to remove the new custom function definitions if present
   // pModel->getListOfFunctionDefinitions()->clear(true);
   for (int i = ((int)pModel->getNumFunctionDefinitions()) - 1; i >= 0; --i)
     {
       FunctionDefinition* current = pModel->getFunctionDefinition(i);
       if (current != NULL &&
           current->isSetAnnotation() &&
           current->getAnnotation()->getNumChildren() == 1 &&
           current->getAnnotation()->getChild(0).getURI().find("http://sbml.org/annotations/") != std::string::npos)
         continue;
       // if we are here it is not one of the custom ones, so delete it
       FunctionDefinition* toDelete = pModel->removeFunctionDefinition(i);
       delete toDelete;
     }
   std::vector<CFunction*>::iterator it = functionsVect.begin(), endit = functionsVect.end();
   while (it != endit)
     {
       if (*it != NULL)
         {
           createFunctionDefinition(**it, dataModel);
         }
       ++it;
     }
 }
const std::set< CFunction * > CSBMLExporter::createFunctionSetFromFunctionNames (const std::set< std::string > & names, CFunctionDB * pFunDB) static protected
Definition at line 5054 of file CSBMLExporter.cpp.
References CCopasiMessage::ERROR, CFunctionDB::findFunction(), and MCSBML.
Referenced by checkForPiecewiseFunctions(), createEvent(), createInitialAssignment(), createRule(), exportEventAssignments(), and findUsedFunctions().
 {
   std::set<CFunction*> result;
   if (pFunDB != NULL)
     {
       std::set<std::string>::const_iterator it = names.begin();
       std::set<std::string>::const_iterator endit = names.end();
       CFunction* pFun = NULL;
       while (it != endit)
         {
           pFun = dynamic_cast<CFunction*>(pFunDB->findFunction(*it));
           if (pFun == NULL)
             {
               CCopasiMessage(CCopasiMessage::ERROR, MCSBML + 15, (*it).c_str());
             }
           else
             {
               result.insert(pFun);
             }
           ++it;
         }
     }
   return result;
 }
const std::map< std::string, const SBase * > CSBMLExporter::createIdMap (const Model & sbmlModel) protected
Goes through the given SBML model and puts all ids with the corresponding object into a map.
Definition at line 2075 of file CSBMLExporter.cpp.
 {
   // go through all function definitions, compartments, species, reactions,
   // parameters and events and create a set with all used ids.
   std::map<std::string, const SBase*> idMap;
   unsigned int i, iMax;
   if (sbmlModel.isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getId(), &sbmlModel));
     }
   if (sbmlModel.getListOfFunctionDefinitions()->isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getListOfFunctionDefinitions()->getId(), sbmlModel.getListOfFunctionDefinitions()));
     }
   iMax = sbmlModel.getNumFunctionDefinitions();
   for (i = 0; i < iMax; ++i)
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getFunctionDefinition(i)->getId(), sbmlModel.getFunctionDefinition(i)));
     }
   if (sbmlModel.getListOfCompartments()->isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getListOfCompartments()->getId(), sbmlModel.getListOfCompartments()));
     }
   iMax = sbmlModel.getNumCompartments();
   for (i = 0; i < iMax; ++i)
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getCompartment(i)->getId(), sbmlModel.getCompartment(i)));
     }
   if (sbmlModel.getListOfSpecies()->isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getListOfSpecies()->getId(), sbmlModel.getListOfSpecies()));
     }
   iMax = sbmlModel.getNumSpecies();
   for (i = 0; i < iMax; ++i)
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getSpecies(i)->getId(), sbmlModel.getSpecies(i)));
     }
   if (sbmlModel.getListOfParameters()->isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getListOfParameters()->getId(), sbmlModel.getListOfParameters()));
     }
   iMax = sbmlModel.getNumParameters();
   for (i = 0; i < iMax; ++i)
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getParameter(i)->getId(), sbmlModel.getParameter(i)));
     }
   if (sbmlModel.getListOfReactions()->isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getListOfReactions()->getId(), sbmlModel.getListOfReactions()));
     }
   iMax = sbmlModel.getNumReactions();
   for (i = 0; i < iMax; ++i)
     {
       const Reaction* pReaction = sbmlModel.getReaction(i);
       if (pReaction != NULL)
         {
           idMap.insert(std::pair<const std::string, const SBase*>(pReaction->getId(), pReaction));
           if (pReaction->getListOfReactants()->isSetId())
             {
               idMap.insert(std::pair<const std::string, const SBase*>(pReaction->getListOfReactants()->getId(), pReaction->getListOfReactants()));
             }
           unsigned int j, jMax = pReaction->getNumReactants();
           const SpeciesReference* pSRef = NULL;
           for (j = 0; j < jMax; ++j)
             {
               pSRef = pReaction->getReactant(j);
               if (pSRef->isSetId())
                 {
                   idMap.insert(std::pair<const std::string, const SBase*>(pSRef->getId(), pSRef));
                 }
             }
           if (pReaction->getListOfProducts()->isSetId())
             {
               idMap.insert(std::pair<const std::string, const SBase*>(pReaction->getListOfProducts()->getId(), pReaction->getListOfProducts()));
             }
           jMax = pReaction->getNumProducts();
           for (j = 0; j < jMax; ++j)
             {
               pSRef = pReaction->getProduct(j);
               if (pSRef->isSetId())
                 {
                   idMap.insert(std::pair<const std::string, const SBase*>(pSRef->getId(), pSRef));
                 }
             }
           if (pReaction->getListOfModifiers()->isSetId())
             {
               idMap.insert(std::pair<const std::string, const SBase*>(pReaction->getListOfModifiers()->getId(), pReaction->getListOfModifiers()));
             }
           jMax = pReaction->getNumModifiers();
           const ModifierSpeciesReference* pModSRef;
           for (j = 0; j < jMax; ++j)
             {
               pModSRef = pReaction->getModifier(j);
               if (pModSRef->isSetId())
                 {
                   idMap.insert(std::pair<const std::string, const SBase*>(pModSRef->getId(), pModSRef));
                 }
             }
         }
     }
   if (sbmlModel.getListOfEvents()->isSetId())
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getListOfEvents()->getId(), sbmlModel.getListOfEvents()));
     }
   iMax = sbmlModel.getNumEvents();
   for (i = 0; i < iMax; ++i)
     {
       idMap.insert(std::pair<const std::string, const SBase*>(sbmlModel.getEvent(i)->getId(), sbmlModel.getEvent(i)));
     }
   // if COPASI is compiled with layout, we have to add those ids as well
   const LayoutModelPlugin* lmPlugin = (LayoutModelPlugin*)sbmlModel.getPlugin("layout");
   if (lmPlugin != NULL)
     {
       if (lmPlugin->getListOfLayouts()->isSetId())
         {
           idMap.insert(std::pair<const std::string, const SBase*>(lmPlugin->getListOfLayouts()->getId(), lmPlugin->getListOfLayouts()));
         }
       iMax = lmPlugin->getListOfLayouts()->size();
       for (i = 0; i < iMax; ++i)
         {
           const Layout* pLayout = lmPlugin->getLayout(i);
           if (pLayout != NULL)
             {
               if (pLayout->isSetId())
                 {
                   idMap.insert(std::pair<const std::string, const SBase*>(pLayout->getId(), pLayout));
                 }
             }
         }
     }
   return idMap;
 }
void CSBMLExporter::createInitialAssignment (const CModelEntity & modelEntity, CCopasiDataModel & dataModel) protected
Creates the initial assignment for the given COPASI model entity.
Definition at line 1673 of file CSBMLExporter.cpp.
References convertToASTNode(), createFunctionSetFromFunctionNames(), CCopasiMessage::EXCEPTION, findDirectlyUsedFunctions(), CMetab::getCompartment(), CCompartment::getDimensionality(), CCopasiRootContainer::getFunctionList(), CModelEntity::getInitialExpressionPtr(), CModelEntity::getInitialValueReference(), CCopasiObject::getObjectName(), CCopasiObject::getObjectType(), CEvaluationTree::getRoot(), CModelEntity::getSBMLId(), CEvaluationNode::getType(), CEvaluationNode::INVALID, isExpressionSBMLCompatible(), mCOPASI2SBMLMap, MCSBML, mHandledSBMLObjects, mIncompatibilities, mIncompleteExport, mInitialValueMap, mpSBMLDocument, mSBMLLevel, mSBMLVersion, multiplyByObject(), mUsedFunctions, outputIncompatibilities(), replace_local_parameters(), replaceSpeciesReferences(), and CEvaluationNode::type().
Referenced by createInitialAssignments().
 {
   // check the expression
   std::vector<SBMLIncompatibility> result;
   CSBMLExporter::isExpressionSBMLCompatible(*modelEntity.getInitialExpressionPtr()
       , dataModel
       , this->mSBMLLevel
       , this->mSBMLVersion
       , result
       , std::string("initial expression for object named \"" + modelEntity.getObjectName() + "\"").c_str()
       , true
       , &mInitialValueMap);
   // collect directly used functions
   if (result.empty())
     {
       std::set<std::string> directlyUsedFunctionNames;
       CSBMLExporter::findDirectlyUsedFunctions(modelEntity.getInitialExpressionPtr()->getRoot(), directlyUsedFunctionNames);
       std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(directlyUsedFunctionNames, CCopasiRootContainer::getFunctionList());
 #if defined _MSC_VER && _MSC_VER < 1201 // 1200 Identifies Visual C++ 6.0
       {
         std::set<CFunction*>::const_iterator it = usedFunctions.begin();
         std::set<CFunction*>::const_iterator end = usedFunctions.end();
         for (; it != end; ++it)
           this->mUsedFunctions.insert(*it);
       }
 #else
       this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
 #endif
       // create the actual initial assignment
       InitialAssignment* pInitialAssignment = this->mpSBMLDocument->getModel()->getInitialAssignment(modelEntity.getSBMLId());
       if (pInitialAssignment == NULL)
         {
           pInitialAssignment = this->mpSBMLDocument->getModel()->createInitialAssignment();
           pInitialAssignment->setSymbol(modelEntity.getSBMLId());
         }
       // set the math
       this->mHandledSBMLObjects.insert(pInitialAssignment);
       const CEvaluationNode* pOrigNode = modelEntity.getInitialExpressionPtr()->getRoot();
       if (CEvaluationNode::type(pOrigNode->getType()) == CEvaluationNode::INVALID)
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 70, "initial assignment", modelEntity.getObjectType().c_str(), modelEntity.getObjectName().c_str());
         }
       // the next few lines replace references to species depending on whether
       // it is a reference to an amount or a reference to a concentration.
       // Other factors that influence this replacement are if the model
       // contains variable volumes or if the quantity units are set to CModel::number
       pOrigNode = this->replaceSpeciesReferences(pOrigNode, dataModel);
       assert(pOrigNode != NULL);
       // check if the rule is for an amount species
       // if this is the case, we have to multiply the expression by the volume
       // of the compartment the species is in
       // create the actual rule
       const CMetab* pMetab = dynamic_cast<const CMetab*>(&modelEntity);
       if (pMetab != NULL)
         {
           std::map<const CCopasiObject*, SBase*>::const_iterator pos = this->mCOPASI2SBMLMap.find(&modelEntity);
           assert(pos != this->mCOPASI2SBMLMap.end());
           if (dynamic_cast<const Species*>(pos->second)->getHasOnlySubstanceUnits() == true)
             {
               const CCompartment* pCompartment = pMetab->getCompartment();
               if (pCompartment->getDimensionality() != 0)
                 {
                   CEvaluationNode* pNode = CSBMLExporter::multiplyByObject(pOrigNode, pCompartment->getInitialValueReference());
                   assert(pNode != NULL);
                   if (pNode != NULL)
                     {
                       delete pOrigNode;
                       pOrigNode = pNode;
                     }
                 }
             }
         }
       ASTNode* pNode = this->convertToASTNode(pOrigNode, dataModel);
       delete pOrigNode;
       // convert local parameters that are referenced in an expression to global
       // parameters
       this->replace_local_parameters(pNode, dataModel);
       if (pNode != NULL)
         {
           pInitialAssignment->setMath(pNode);
           delete pNode;
         }
       else
         {
           if (this->mIncompleteExport == true)
             {
               // remove the initial assignment from the SBML model
               unsigned int i = 0, iMax = this->mpSBMLDocument->getModel()->getNumInitialAssignments();
               while (i < iMax)
                 {
                   if (this->mpSBMLDocument->getModel()->getInitialAssignment(i)->getSymbol() == modelEntity.getSBMLId())
                     {
                       this->mpSBMLDocument->getModel()->getListOfInitialAssignments()->remove(i);
                       break;
                     }
                   ++i;
                 }
             }
           else
             {
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "initial assignment", modelEntity.getObjectType().c_str(), modelEntity.getObjectName().c_str());
             }
         }
     }
   else
     {
       this->mIncompatibilities.insert(this->mIncompatibilities.end(), result.begin(), result.end());
       if (!this->mIncompleteExport)
         {
           this->outputIncompatibilities();
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "initial assignment", modelEntity.getObjectType().c_str(), modelEntity.getObjectName().c_str());
         }
     }
 }
void CSBMLExporter::createInitialAssignments (CCopasiDataModel & dataModel) protected
Creates the initial assignments for the model.
Definition at line 1650 of file CSBMLExporter.cpp.
References createInitialAssignment(), and mInitialAssignmentVector.
Referenced by createSBMLDocument().
 {
   // make sure the mInitialAssignmentVector has been filled already
   // create the initial assignments
   size_t i, iMax = this->mInitialAssignmentVector.size();
   const CModelEntity* pME = NULL;
   for (i = 0; i < iMax; ++i)
     {
       pME = mInitialAssignmentVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           createInitialAssignment(*pME, dataModel);
         }
     }
 }
CEvaluationNode * CSBMLExporter::createKineticExpression (CFunction * pFun, const std::vector< std::vector< std::string > > & arguments) protected
Creates an expression from a given node and a set of parameter mappings by replacing the function arguments with the parameters. static CEvaluationNode* createExpressionTree(const CEvaluationNode* const pNode, const std::map<std::string, std::string>& parameterMap, const CCopasiDataModel& dataModel); Creates an expression from a given function and a set of parameters by replacing the function arguments with the parameters. static CEvaluationNode* createExpressionTree(const CFunction* const pFun, const std::vector<std::vector<std::string> >& arguments, const CCopasiDataModel& dataModel); Create an expression that corresponds to a kinetic law. If the kinetic law was mass action, the expression is a mass action term , otherwise it is a function call.
Definition at line 4802 of file CSBMLExporter.cpp.
References CEvaluationNodeCall::addChild(), CEvaluationNodeObject::CN, createMassActionExpression(), fatalError, CEvaluationNodeCall::FUNCTION, CKeyFactory::get(), CCopasiObject::getCN(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CEvaluationTree::getType(), CFunction::getVariables(), CFunction::isReversible(), CEvaluationTree::MassAction, mUsedFunctions, pResult, CFunctionParameters::size(), and TriTrue.
Referenced by createKineticLaw().
 {
   if (!pFun || pFun->getVariables().size() != arguments.size()) fatalError();
   CEvaluationNode* pResult;
   if (pFun->getType() == CEvaluationTree::MassAction)
     {
       pResult = CSBMLExporter::createMassActionExpression(arguments, pFun->isReversible() == TriTrue);
     }
   else
     {
       CEvaluationNodeCall* pFunctionCall = new CEvaluationNodeCall(CEvaluationNodeCall::FUNCTION, pFun->getObjectName());
       this->mUsedFunctions.insert(pFun);
       size_t i, iMax = arguments.size();
       std::string cn;
       for (i = 0; i < iMax; ++i)
         {
           if (arguments[i].size() != 1) fatalError(); // we can't have arrays here.
           const CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(arguments[i][0]);
           if (!pObject) fatalError();
           if (dynamic_cast<const CModel*>(pObject) != NULL)
             {
               cn = "<" + pObject->getCN() + ",Reference=Time>";
             }
           else if (dynamic_cast<const CCompartment*>(pObject) != NULL)
             {
               cn = "<" + pObject->getCN() + ",Reference=Volume>";
             }
           else if (dynamic_cast<const CMetab*>(pObject) != NULL)
             {
               cn = "<" + pObject->getCN() + ",Reference=Concentration>";
             }
           else if (dynamic_cast<const CModelValue*>(pObject) != NULL)
             {
               cn = "<" + pObject->getCN() + ",Reference=Value>";
             }
           else if (dynamic_cast<const CReaction*>(pObject) != NULL)
             {
               cn = "<" + pObject->getCN() + ",Reference=Flux>";
             }
           else if (dynamic_cast<const CCopasiParameter*>(pObject) != NULL)
             {
               // local parameter of a reaction
               // must set the node content to the SBML id if the parameter
               cn = "<" + pObject->getCN() + ">";
             }
           else
             {
               cn = "<" + pObject->getCN() + ">";
             }
           pFunctionCall->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, cn));
         }
       pResult = pFunctionCall;
     }
   return pResult;
 }
KineticLaw * CSBMLExporter::createKineticLaw (CReaction & reaction, CCopasiDataModel & dataModel, unsigned int level, unsigned int version) protected
Create the kinetic law for the given reaction. On failure NULL is returned.
Definition at line 4584 of file CSBMLExporter.cpp.
References convertToASTNode(), createKineticExpression(), fatalError, CKeyFactory::get(), CReaction::getChemEq(), CCopasiParameter::getCN(), CReaction::getCompartmentNumber(), CCompartment::getDimensionality(), CReaction::getFunction(), CReaction::getFunctionParameters(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CReaction::getParameterMapping(), CReaction::getParameterMappings(), CReaction::getParameterValue(), CChemEq::getProducts(), CModelEntity::getSBMLId(), CChemEq::getSubstrates(), CFunctionParameter::getUsage(), isDividedByVolume(), CReaction::isLocalParameter(), CFunction::isReversible(), mParameterReplacementMap, mpSBMLDocument, mSBMLLevel, CFunctionParameter::PARAMETER, replaceSpeciesReferences(), restore_local_parameters(), CFunctionParameters::size(), CCopasiVector< T >::size(), TriUnspecified, and CFunctionParameter::VARIABLE.
Referenced by createReaction().
 {
   KineticLaw* pKLaw = NULL;
   if (!pKLaw)
     {
       /* create a new KineticLaw */
       pKLaw = new KineticLaw(level, version);
     }
   // create the local parameters
   size_t i, iMax = reaction.getFunctionParameters().size();
   for (i = 0; i < iMax; ++i)
     {
       const CFunctionParameter* pPara = reaction.getFunctionParameters()[i];
       // if the reaction calls a general function, all call parameters have a usage of VARIABLE
       // So local parameters will also have a usage of VARIABLE instead of PARAMETER
       if (pPara->getUsage() == CFunctionParameter::PARAMETER ||
           (reaction.getFunction() != NULL &&
            reaction.getFunction()->isReversible() == TriUnspecified &&
            pPara->getUsage() == CFunctionParameter::VARIABLE))
         {
           // only create a parameter if it is a local parameter,
           // and if it is not in the replacement map
           // otherwise the parameter already has been created
           if (reaction.isLocalParameter(i))
             {
               std::vector<std::string> v = reaction.getParameterMapping(pPara->getObjectName());
               assert(v.size() == 1);
               CCopasiObject* pTmpObject = CCopasiRootContainer::getKeyFactory()->get(v[0]);
               assert(pTmpObject != NULL);
               CCopasiParameter* pLocalParameter = dynamic_cast<CCopasiParameter*>(pTmpObject);
               assert(pLocalParameter != NULL);
               if (this->mParameterReplacementMap.find(pLocalParameter->getCN()) == this->mParameterReplacementMap.end())
                 {
                   // starting with SBML Level 3, the parameters of a kinetic law are expressed in
                   // libsbml 4.1 does not handle this in a nice way,
                   // so way have to distinguish between the levels we export
                   // Actually here we could probably have gotten away with the old code, but
                   // better safe than sorry
                   Parameter* pSBMLPara = NULL;
 #if LIBSBML_VERSION >= 40100
                   if (this->mSBMLLevel > 2)
                     {
                       pSBMLPara = pKLaw->createLocalParameter();
                     }
                   else
                     {
 #endif // LIBSBML_VERSION
                       pSBMLPara = pKLaw->createParameter();
 #if LIBSBML_VERSION >= 40100
                     }
                   pSBMLPara->setId(pPara->getObjectName().c_str());
 #endif // LIBSBML_VERSION
                   // don't call setName on level 1 objects because this will also
                   // change the id
                   if (this->mpSBMLDocument->getLevel() > 1)
                     {
                       pSBMLPara->setName(pPara->getObjectName().c_str());
                     }
                   double value = reaction.getParameterValue(pPara->getObjectName());
                   // if the value is NaN, leave the parameter value unset.
                   if (!isnan(value))
                     {
                       pSBMLPara->setValue(value);
                     }
                 }
             }
         }
     }
   // the next few lines replace references to species depending on whether
   // it is a reference to an amount or a reference to a concentration.
   // Other factors that influence this replacement are if the model
   // contains variable volumes or if the quantity units are set to CModel::number
   CEvaluationNode* pExpression = CSBMLExporter::createKineticExpression(const_cast<CFunction*>(reaction.getFunction()), reaction.getParameterMappings());
   if (pExpression == NULL)
     {
       delete pKLaw;
       pKLaw = NULL;
     }
   else
     {
       /*
       ** If the reaction takes place in a single compartment, the rate law has
       ** to be converted from concentration/time to substance/time by
       ** multiplying the rate law with the volume of the compartment.
       */
       CEvaluationNode* pOrigNode = this->replaceSpeciesReferences(pExpression, dataModel);
       delete pExpression;
       assert(pOrigNode != NULL);
       ASTNode* pNode = this->convertToASTNode(pOrigNode, dataModel);
       // since toAST in CEvaluationNodeObject sets the CN of local parameters
       // as the name of the node, we have to go and replace all node names
       // that have a common name that is the CN of a local parameter
       this->restore_local_parameters(pNode, dataModel);
       delete pOrigNode;
       assert(pNode != NULL);
       if (reaction.getCompartmentNumber() == 1)
         {
           const CCompartment& compartment = (reaction.getChemEq().getSubstrates().size() != 0) ? (*reaction.getChemEq().getSubstrates()[0]->getMetabolite()->getCompartment()) : (*reaction.getChemEq().getProducts()[0]->getMetabolite()->getCompartment());
           if (compartment.getDimensionality() != 0)
             {
               // check if the importer has added a division by the volume
               // if so remove it instead of multiplying again
               ASTNode* pTNode = CSBMLExporter::isDividedByVolume(pNode, compartment.getSBMLId());
               if (pTNode)
                 {
                   if (pTNode->getNumChildren() == 0)
                     {
                       fatalError();
                     }
                   if (pTNode->getNumChildren() == 1)
                     {
                       ASTNode* pTmp = static_cast<ConverterASTNode*>(pTNode)->removeChild(0);
                       delete pTNode;
                       pTNode = pTmp;
                     }
                   delete pNode;
                   pNode = pTNode;
                 }
               else
                 {
                   pTNode = new ASTNode(AST_TIMES);
                   ASTNode* pVNode = new ASTNode(AST_NAME);
                   pVNode->setName(compartment.getSBMLId().c_str());
                   pTNode->addChild(pVNode);
                   pTNode->addChild(pNode);
                   pNode = pTNode;
                 }
             }
         }
       pKLaw->setMath(pNode);
       delete pNode;
     }
   return pKLaw;
 }
void CSBMLExporter::createLengthUnit (const CCopasiDataModel & dataModel) protected
Creates the volume unit for the SBML model.
Creates the length unit for the SBML model.
Definition at line 689 of file CSBMLExporter.cpp.
References SBMLImporter::areSBMLUnitDefinitionsIdentical(), CModel::cm, CModel::dimensionlessLength, CModel::dm, CCopasiMessage::EXCEPTION, CModel::fm, CModel::getLengthUnitEnum(), CCopasiDataModel::getModel(), INIT_DEFAULTS, CModel::m, CModel::microm, CModel::mm, mpSBMLDocument, mSBMLLevel, mSBMLVersion, CModel::nm, and CModel::pm.
Referenced by createUnits().
 {
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   UnitDefinition uDef(this->mSBMLLevel, this->mSBMLVersion);
   uDef.setName("length");
   uDef.setId("length");
   Unit unit(this->mSBMLLevel, this->mSBMLVersion);
   INIT_DEFAULTS(unit);
   switch (dataModel.getModel()->getLengthUnitEnum())
     {
       case CModel::m:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       case CModel::dm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-1);
         break;
       case CModel::cm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-2);
         break;
       case CModel::mm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-3);
         break;
       case CModel::microm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-6);
         break;
       case CModel::nm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-9);
         break;
       case CModel::pm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-12);
         break;
       case CModel::fm:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(1);
         unit.setScale(-15);
         break;
       case CModel::dimensionlessLength:
         unit.setKind(UNIT_KIND_DIMENSIONLESS);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, "SBMLExporter Error: Unknown copasi length unit.");
         break;
     }
   unit.setMultiplier(1.0);
   uDef.addUnit(&unit);
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   UnitDefinition* pUdef = pSBMLModel->getUnitDefinition("length");
   if (pUdef != NULL)
     {
       // check if it is the same unit as the existing one if there is one
       // if yes, return, else replace the existing one
       if (!SBMLImporter::areSBMLUnitDefinitionsIdentical(pUdef, &uDef))
         {
           (*pUdef) = uDef;
         }
     }
   else
     {
       // only add it if it is not the default unit definition anyway
       if (this->mSBMLLevel > 2 || unit.getKind() != UNIT_KIND_METRE || unit.getScale() != 0 || unit.getExponent() != 1 || unit.getMultiplier() != 1.0)
         {
           // set the unit definition
           pSBMLModel->addUnitDefinition(&uDef);
         }
     }
 // if we write an SBML L3 document, we have to explicitely set the units on the model
 #if LIBSBML_VERSION >= 40100
   if (this->mSBMLLevel > 2)
     {
       pSBMLModel->setLengthUnits(uDef.getId());
     }
 #endif // LIBSBML_VERSION
 }
CEvaluationNode * CSBMLExporter::createMassActionExpression (const std::vector< std::vector< std::string > > & arguments, bool isReversible) static protected
This method creates the CEvaluationNode based tree for a reversible or irreversible Mass Action call. The first parameter contains the arguments from the COPASI reaction. The second argument determines whether it is reversible or irreversible mass action.
Definition at line 5907 of file CSBMLExporter.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeObject::CN, CEvaluationNodeNumber::DOUBLE, CKeyFactory::get(), CCopasiObject::getCN(), CCopasiRootContainer::getKeyFactory(), CEvaluationNodeOperator::MINUS, CEvaluationNodeOperator::MULTIPLY, CEvaluationNodeOperator::POWER, and pResult.
Referenced by createKineticExpression().
 {
   assert((isReversible && arguments.size() == 4) || arguments.size() == 2);
   assert(arguments[0].size() == 1 && arguments[1].size() > 0);
   // create a multiplication of all items in arguments[1] and multiply that
   // with item arguments[0][0]
   std::set<std::string> finishedElements;
   std::vector<CEvaluationNode*> multiplicants;
   const CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(arguments[0][0]);
   assert(pObject != NULL);
   multiplicants.push_back(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pObject->getCN() + ",Reference=Value>"));
   std::vector<std::string>::const_iterator it = arguments[1].begin(), endit = arguments[1].end();
   while (it != endit)
     {
       if (finishedElements.find(*it) == finishedElements.end())
         {
 #ifdef __SUNPRO_CC
           // replaced count call with  "old" count call
           // to compile on Sun Compiler
           unsigned int num = 0;
           std::count(arguments[1].begin(), arguments[1].end(), *it, num);
 #else
           size_t num = std::count(arguments[1].begin(), arguments[1].end(), *it);
 #endif  // __SUNPRO_CC
           assert(num != 0);
           finishedElements.insert(*it);
           pObject = CCopasiRootContainer::getKeyFactory()->get(*it);
           assert(pObject != NULL);
           if (num == 1)
             {
               multiplicants.push_back(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pObject->getCN() + ",Reference=Concentration>"));
             }
           else
             {
               std::ostringstream os;
               os << num;
               CEvaluationNodeOperator* pOperator = new CEvaluationNodeOperator(CEvaluationNodeOperator::POWER, "^");
               pOperator->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pObject->getCN() + ",Reference=Concentration>"));
               pOperator->addChild(new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, os.str()));
               multiplicants.push_back(pOperator);
             }
         }
       ++it;
     }
   std::vector<CEvaluationNode*>::reverse_iterator rIt = multiplicants.rbegin(), rEndit = multiplicants.rend();
   CEvaluationNode* pResult = *rIt;
   ++rIt;
   CEvaluationNode* pTmpNode = NULL;
   if (rIt != rEndit)
     {
       --rEndit;
       while (rIt != rEndit)
         {
           pTmpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
           pTmpNode->addChild(*rIt);
           pTmpNode->addChild(pResult);
           pResult = pTmpNode;
           ++rIt;
         }
     }
   pTmpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
   pTmpNode->addChild(*rIt);
   pTmpNode->addChild(pResult);
   pResult = pTmpNode;
   if (isReversible)
     {
       std::vector<std::vector<std::string> > tmpV;
       tmpV.push_back(arguments[2]);
       tmpV.push_back(arguments[3]);
       pTmpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MINUS, "-");
       pTmpNode->addChild(pResult);
       pTmpNode->addChild(CSBMLExporter::createMassActionExpression(tmpV, false));
       pResult = pTmpNode;
     }
   return pResult;
 }
void CSBMLExporter::createMetabolite (CMetab & metab) protected
Creates the species for the given COPASI metabolite.
Definition at line 1105 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, createUniqueId(), CModelEntity::FIXED, CMetab::getCompartment(), CMetab::getInitialConcentration(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CMetab::getObjectDisplayName(), CCopasiObject::getObjectName(), CModelEntity::getSBMLId(), CModelEntity::getStatus(), INIT_DEFAULTS, mAssignmentVector, mCOPASI2SBMLMap, mHandledSBMLObjects, mIdMap, mInitialAssignmentVector, mMetaIdMap, mODEVector, mpSBMLDocument, mSBMLLevel, mSBMLVersion, mSpatialSizeUnitsSpecies, mVariableVolumes, CModelEntity::ODE, CModelEntity::REACTIONS, removeInitialAssignment(), removeRule(), CModelEntity::setSBMLId(), setSBMLNotes(), and updateMIRIAMAnnotation().
Referenced by createMetabolites().
 {
   Species* pSBMLSpecies = NULL;
   std::string sbmlId = metab.getSBMLId();
   if (!sbmlId.empty())
     {
       pSBMLSpecies = this->mpSBMLDocument->getModel()->getSpecies(sbmlId);
       if (pSBMLSpecies == NULL)
         {
           pSBMLSpecies = this->mpSBMLDocument->getModel()->createSpecies();
           this->mCOPASI2SBMLMap[&metab] = pSBMLSpecies;
           pSBMLSpecies->setId(sbmlId);
         }
       else
         {
 #if LIBSBML_VERSION >= 40100
           if (this->mSBMLLevel > 2)
             {
               pSBMLSpecies->unsetConversionFactor();
               // we have to remove the conversionFactor because on import we multiplied the stoichiometries
               // with this factor
             }
 #endif // LIBSBML_VERSION
           // clear the spatialSizeUnits attribute if there is any
           if (this->mSBMLLevel > 2 || (this->mSBMLLevel == 2 && this->mSBMLVersion >= 3))
             {
               if (pSBMLSpecies->isSetSpatialSizeUnits())
                 {
                   pSBMLSpecies->unsetSpatialSizeUnits();
                   this->mSpatialSizeUnitsSpecies.insert(pSBMLSpecies->getId());
                 }
             }
         }
     }
   else
     {
       pSBMLSpecies = this->mpSBMLDocument->getModel()->createSpecies();
       this->mCOPASI2SBMLMap[&metab] = pSBMLSpecies;
       sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, metab.getObjectDisplayName(), false);
       metab.setSBMLId(sbmlId);
       pSBMLSpecies->setId(sbmlId);
     }
   INIT_DEFAULTS((*pSBMLSpecies));
   this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, pSBMLSpecies));
   this->mHandledSBMLObjects.insert(pSBMLSpecies);
   // don't call setName on level 1 objects because this will also
   // change the id
   if (this->mpSBMLDocument->getLevel() > 1)
     {
       pSBMLSpecies->setName(metab.getObjectName().c_str());
     }
   //const Compartment* pSBMLCompartment = dynamic_cast<const Compartment*>(this->mCOPASI2SBMLMap[const_cast<CCompartment*>(metab.getCompartment())]);
   const Compartment* pSBMLCompartment = this->mpSBMLDocument->getModel()->getCompartment(metab.getCompartment()->getSBMLId());
   assert(pSBMLCompartment);
   pSBMLSpecies->setCompartment(pSBMLCompartment->getId());
   if (this->mVariableVolumes == true)
     {
       pSBMLSpecies->setHasOnlySubstanceUnits(true);
     }
   double value = metab.getInitialConcentration();
   // if the value is NaN, unset the initial amount
   if (!isnan(value))
     {
       // if we set the concentration on a species that had the amount
       // set, the meaning of the model is different when the user changed
       // to size of the corresponding compartment
       // So if the amount had been set, we try to keep this.
       // we also have to set the initial amount if the model has variable
       // volumes since those models export all species with the
       // hasOnlySubstanceUnits flag set to true
       //
       // libsbml 4 does not set the initial concentration on a species any more
       // so we also have to set the initial amount
       if (pSBMLSpecies->isSetInitialAmount() || this->mVariableVolumes == true || pSBMLSpecies->getLevel() == 1)
         {
           pSBMLSpecies->setInitialAmount(value * metab.getCompartment()->getInitialValue());
         }
       else
         {
           pSBMLSpecies->setInitialConcentration(value);
         }
     }
   else
     {
       pSBMLSpecies->unsetInitialConcentration();
       pSBMLSpecies->unsetInitialAmount();
     }
   CModelEntity::Status status = metab.getStatus();
   // a species can either have an assignment or an initial assignment but not
   // both
   if (status == CModelEntity::ASSIGNMENT)
     {
       this->mAssignmentVector.push_back(&metab);
       pSBMLSpecies->setConstant(false);
       pSBMLSpecies->setBoundaryCondition(true);
       removeInitialAssignment(pSBMLSpecies->getId());
     }
   else if (status == CModelEntity::ODE)
     {
       this->mODEVector.push_back(&metab);
       pSBMLSpecies->setConstant(false);
       pSBMLSpecies->setBoundaryCondition(true);
       if (metab.getInitialExpression() != "")
         {
           this->mInitialAssignmentVector.push_back(&metab);
         }
       else
         {
           removeInitialAssignment(pSBMLSpecies->getId());
         }
     }
   else if (status == CModelEntity::FIXED)
     {
       // do this explicitly since we might handle an existing object from an
       // earlier import that had it attribute set already
       if (this->mSBMLLevel != 1)
         {
           pSBMLSpecies->setConstant(true);
         }
       else
         {
           // Level 1 doesn't have the constant attribute and libSBML 3.2.0 does
           // not drop it automatically
           pSBMLSpecies->setConstant(false);
         }
       pSBMLSpecies->setBoundaryCondition(true);
       removeRule(pSBMLSpecies->getId());
       // fill initial assignment set
       if (metab.getInitialExpression() != "")
         {
           this->mInitialAssignmentVector.push_back(&metab);
         }
       else
         {
           removeInitialAssignment(pSBMLSpecies->getId());
         }
     }
   else if (status == CModelEntity::REACTIONS)
     {
       pSBMLSpecies->setConstant(false);
       pSBMLSpecies->setBoundaryCondition(false);
       if (metab.getInitialExpression() != "")
         {
           this->mInitialAssignmentVector.push_back(&metab);
         }
     }
   if (pSBMLSpecies != NULL)
     {
       CSBMLExporter::setSBMLNotes(pSBMLSpecies, &metab);
     }
   if (pSBMLSpecies != NULL && mSBMLLevel == 3)
     {
       // for l3 the unit needs to be set explicitly to substance,
       pSBMLSpecies->setSubstanceUnits("substance");
     }
   CSBMLExporter::updateMIRIAMAnnotation(&metab, pSBMLSpecies, this->mMetaIdMap);
 }
void CSBMLExporter::createMetabolites (CCopasiDataModel & dataModel) protected
Creates the compartments for the model.
Definition at line 1068 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), check_for_spatial_size_units(), createMetabolite(), CCopasiVector< T >::end(), CModel::getMetabolites(), CCopasiDataModel::getModel(), MCSBML, mIncompatibilities, mpSBMLDocument, mSBMLLevel, mSBMLVersion, mSpatialSizeUnitsSpecies, and CCopasiMessage::WARNING.
Referenced by createSBMLDocument().
 {
   // make sure the SBML Document already exists and that it has a Model set
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   if (this->mSBMLLevel > 2 || (this->mSBMLLevel == 2 && this->mSBMLVersion >= 3))
     {
       check_for_spatial_size_units(dataModel, this->mIncompatibilities);
     }
   CCopasiVector<CMetab>::const_iterator it = dataModel.getModel()->getMetabolites().begin(), endit = dataModel.getModel()->getMetabolites().end();
   this->mSpatialSizeUnitsSpecies.clear();
   while (it != endit)
     {
       createMetabolite(**it);
       ++it;
     }
   if (!this->mSpatialSizeUnitsSpecies.empty())
     {
       std::ostringstream os;
       std::set<std::string>::const_iterator sit = this->mSpatialSizeUnitsSpecies.begin(), sendit = this->mSpatialSizeUnitsSpecies.end();
       while (sit != sendit)
         {
           os << *sit << ", ";
           ++sit;
         }
       CCopasiMessage(CCopasiMessage::WARNING, MCSBML + 84, os.str().substr(0, os.str().size() - 2).c_str());
     }
 }
void CSBMLExporter::createParameter (CModelValue & modelValue) protected
Creates the parameter for the given COPASI parameter.
Definition at line 1304 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, createUniqueId(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CCopasiObject::getObjectName(), CModelEntity::getSBMLId(), CModelEntity::getStatus(), INIT_DEFAULTS, mAssignmentVector, mCOPASI2SBMLMap, mHandledSBMLObjects, mIdMap, mInitialAssignmentVector, mMetaIdMap, mODEVector, mpSBMLDocument, mSBMLLevel, CModelEntity::ODE, removeInitialAssignment(), removeRule(), CModelEntity::setSBMLId(), setSBMLNotes(), and updateMIRIAMAnnotation().
Referenced by createParameters().
 {
   Parameter* pParameter = NULL;
   std::string sbmlId = modelValue.getSBMLId();
   if (!sbmlId.empty())
     {
       pParameter = this->mpSBMLDocument->getModel()->getParameter(sbmlId);
       if (pParameter == NULL)
         {
           pParameter = this->mpSBMLDocument->getModel()->createParameter();
           this->mCOPASI2SBMLMap[&modelValue] = pParameter;
           pParameter->setId(sbmlId);
         }
     }
   else
     {
       pParameter = this->mpSBMLDocument->getModel()->createParameter();
       this->mCOPASI2SBMLMap[&modelValue] = pParameter;
       sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, modelValue.getObjectName(), false);
       modelValue.setSBMLId(sbmlId);
       pParameter->setId(sbmlId);
     }
   INIT_DEFAULTS((*pParameter));
   this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, pParameter));
   this->mHandledSBMLObjects.insert(pParameter);
   // don't call setName on level 1 objects because this will also
   // change the id
   if (this->mpSBMLDocument->getLevel() > 1)
     {
       pParameter->setName(modelValue.getObjectName());
     }
   double value = modelValue.getInitialValue();
   // if the value is NaN, unset the parameters value
   if (!isnan(value))
     {
       pParameter->setValue(value);
     }
   else
     {
       pParameter->unsetValue();
     }
   // fill assignment set
   // a parameter can either have an assignment or an initial assignment but not
   // both
   CModelEntity::Status status = modelValue.getStatus();
   if (status == CModelEntity::ASSIGNMENT)
     {
       this->mAssignmentVector.push_back(&modelValue);
       pParameter->setConstant(false);
       removeInitialAssignment(pParameter->getId());
     }
   else if (status == CModelEntity::ODE)
     {
       this->mODEVector.push_back(&modelValue);
       pParameter->setConstant(false);
       if (modelValue.getInitialExpression() != "")
         {
           this->mInitialAssignmentVector.push_back(&modelValue);
         }
       else
         {
           removeInitialAssignment(pParameter->getId());
         }
     }
   else
     {
       // do this explicitly since we might handle an existing object from an
       // earlier import that had it attribute set already
       if (this->mSBMLLevel != 1)
         {
           pParameter->setConstant(true);
         }
       else
         {
           // Level 1 does not have a constant flag
           // and libsbml does not drop it automatically
           pParameter->setConstant(false);
         }
       // fill initial assignment set
       removeRule(pParameter->getId());
       if (modelValue.getInitialExpression() != "")
         {
           this->mInitialAssignmentVector.push_back(&modelValue);
         }
       else
         {
           removeInitialAssignment(pParameter->getId());
         }
     }
   if (pParameter != NULL)
     {
       CSBMLExporter::setSBMLNotes(pParameter, &modelValue);
     }
   CSBMLExporter::updateMIRIAMAnnotation(&modelValue, pParameter, this->mMetaIdMap);
 }
void CSBMLExporter::createParameters (CCopasiDataModel & dataModel) protected
Creates the parameters for the model.
Definition at line 1287 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), createParameter(), CCopasiVector< T >::end(), CCopasiDataModel::getModel(), CModel::getModelValues(), and mpSBMLDocument.
Referenced by createSBMLDocument().
 {
   // make sure the SBML Document already exists and that it has a Model set
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   CCopasiVectorN<CModelValue>::const_iterator it = dataModel.getModel()->getModelValues().begin(), endit = dataModel.getModel()->getModelValues().end();
   while (it != endit)
     {
       createParameter(**it);
       ++it;
     }
 }
void CSBMLExporter::createReaction (CReaction & reaction, CCopasiDataModel & dataModel) protected
Creates the reaction for the given COPASI reaction.
Definition at line 1434 of file CSBMLExporter.cpp.
References createKineticLaw(), createUniqueId(), CCopasiMessage::EXCEPTION, CReaction::getChemEq(), CReaction::getFunction(), CChemEqElement::getMetabolite(), CChemEq::getModifiers(), CChemEqElement::getMultiplicity(), CCopasiObject::getObjectName(), CChemEq::getProducts(), CModelEntity::getSBMLId(), CReaction::getSBMLId(), CChemEq::getSubstrates(), CCopasiRootContainer::getUndefinedFunction(), INIT_DEFAULTS, CReaction::isReversible(), mCOPASI2SBMLMap, MCSBML, mHandledSBMLObjects, mIdMap, mIncompleteExport, mMetaIdMap, mpSBMLDocument, mSBMLLevel, CReaction::setSBMLId(), setSBMLNotes(), CCopasiVector< T >::size(), and updateMIRIAMAnnotation().
Referenced by createReactions().
 {
   // make sure the mCOPASI2SBMLMap is already updated
   Reaction* pSBMLReaction = NULL;
   // if the reaction has nothing set but the name, we don't do anything
   // This is mandated since SBML Level 2 Version 2. A reactions has to have either
   // a substrate or a product.
   if (reaction.getChemEq().getSubstrates().size() == 0 &&
       reaction.getChemEq().getProducts().size() == 0) return;
   std::string sbmlId = reaction.getSBMLId();
   if (!sbmlId.empty())
     {
       pSBMLReaction = this->mpSBMLDocument->getModel()->getReaction(sbmlId);
       if (pSBMLReaction == NULL)
         {
           /* create a new reaction object */
           pSBMLReaction = this->mpSBMLDocument->getModel()->createReaction();
           mCOPASI2SBMLMap[&reaction] = pSBMLReaction;
           pSBMLReaction->setId(sbmlId);
         }
       // maybe this id was assigned by assignSBMLIdstoReactions and there is no object associated with it
       // If this is the case, we associate the object here.
       std::map<std::string, const SBase*>::const_iterator pos = this->mIdMap.find(sbmlId);
       assert(pos != this->mIdMap.end());
       if (pos->second == NULL)
         {
           this->mIdMap[sbmlId] = pSBMLReaction;
         }
     }
   else
     {
       pSBMLReaction = this->mpSBMLDocument->getModel()->createReaction();
       this->mCOPASI2SBMLMap[&reaction] = pSBMLReaction;
       sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, reaction.getObjectName(), false);
       reaction.setSBMLId(sbmlId);
       pSBMLReaction->setId(sbmlId);
     }
   INIT_DEFAULTS((*pSBMLReaction));
   this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, pSBMLReaction));
   this->mHandledSBMLObjects.insert(pSBMLReaction);
   // don't call setName on level 1 objects because this will also
   // change the id
   if (this->mpSBMLDocument->getLevel() > 1)
     {
       pSBMLReaction->setName(reaction.getObjectName().c_str());
     }
   pSBMLReaction->setReversible(reaction.isReversible());
   const CChemEq& chemicalEquation = reaction.getChemEq();
   /* Add all substrates */
   unsigned int counter;
   std::set<std::string> usedReferences;
   for (counter = 0; counter < chemicalEquation.getSubstrates().size(); counter++)
     {
       const CChemEqElement* element = chemicalEquation.getSubstrates()[counter];
       const CMetab* pMetabolite = element->getMetabolite();
       assert(pMetabolite);
       SpeciesReference* sRef = NULL;
       if (!(sRef = pSBMLReaction->getReactant(pMetabolite->getSBMLId())))
         {
           sRef = pSBMLReaction->createReactant();
           sRef->setSpecies(pMetabolite->getSBMLId().c_str());
         }
       INIT_DEFAULTS((*sRef));
 #if LIBSBML_VERSION > 40100
       if (this->mSBMLLevel > 2)
         sRef->setConstant(true);
 #endif
       sRef->setStoichiometry(element->getMultiplicity());
       sRef->setDenominator(1);
       usedReferences.insert(sRef->getSpecies());
     }
   ListOf* l = pSBMLReaction->getListOfReactants();
   for (counter = l->size(); counter > 0; --counter)
     {
       if (usedReferences.find(static_cast<SimpleSpeciesReference*>(l->get(counter - 1))->getSpecies()) == usedReferences.end())
         {
           l->remove(counter - 1);
         }
     }
   /* Add all products */
   usedReferences.clear();
   for (counter = 0; counter < chemicalEquation.getProducts().size(); counter++)
     {
       const CChemEqElement* element = chemicalEquation.getProducts()[counter];
       const CMetab* pMetabolite = element->getMetabolite();
       assert(pMetabolite);
       SpeciesReference* sRef = NULL;
       if (!(sRef = pSBMLReaction->getProduct(pMetabolite->getSBMLId())))
         {
           sRef = pSBMLReaction->createProduct();
           sRef->setSpecies(pMetabolite->getSBMLId().c_str());
         }
       INIT_DEFAULTS((*sRef));
 #if LIBSBML_VERSION > 40100
       if (this->mSBMLLevel > 2)
         sRef->setConstant(true);
 #endif
       sRef->setStoichiometry(element->getMultiplicity());
       sRef->setDenominator(1);
       usedReferences.insert(sRef->getSpecies());
     }
   l = pSBMLReaction->getListOfProducts();
   for (counter = l->size(); counter > 0; --counter)
     {
       if (usedReferences.find(static_cast<SimpleSpeciesReference*>(l->get(counter - 1))->getSpecies()) == usedReferences.end())
         {
           l->remove(counter - 1);
         }
     }
   /* Add all modifiers */
   usedReferences.clear();
   for (counter = 0; counter < chemicalEquation.getModifiers().size(); counter++)
     {
       const CChemEqElement* element = chemicalEquation.getModifiers()[counter];
       const CMetab* pMetabolite = element->getMetabolite(); assert(pMetabolite);
       ModifierSpeciesReference* sRef = NULL;
       if (!(sRef = pSBMLReaction->getModifier(pMetabolite->getSBMLId())))
         {
           if (pSBMLReaction->getLevel() > 1)
             {
               sRef = pSBMLReaction->createModifier();
               assert(sRef != NULL);
               sRef->setSpecies(pMetabolite->getSBMLId().c_str());
             }
         }
       if (pSBMLReaction->getLevel() > 1)
         {
           usedReferences.insert(sRef->getSpecies());
         }
     }
   l = pSBMLReaction->getListOfModifiers();
   for (counter = l->size(); counter > 0; --counter)
     {
       if (usedReferences.find(static_cast<SimpleSpeciesReference*>(l->get(counter - 1))->getSpecies()) == usedReferences.end())
         {
           l->remove(counter - 1);
         }
     }
   /* create the kinetic law */
   /* if there is one on COPASI */
   if ((reaction.getFunction()) != CCopasiRootContainer::getUndefinedFunction())
     {
       // make sure the creaated kinetic law has the same level and version as the reaction
       // we intend to add it to, otherwise the setKineticLaw function of libsbml 4 will fail
       // to set the kinetic law
       KineticLaw* pKineticLaw = this->createKineticLaw(reaction, dataModel, pSBMLReaction->getLevel(), pSBMLReaction->getVersion());
       if (pKineticLaw != NULL)
         {
           pSBMLReaction->setKineticLaw(pKineticLaw);
           delete pKineticLaw;
         }
       else
         {
           // create an error message and abort
           // maybe only abort if incomplete export is not wanted
           if (this->mIncompleteExport != true)
             {
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 8, reaction.getObjectName().c_str());
             }
           else
             {
               pSBMLReaction->unsetKineticLaw();
             }
         }
     }
   else
     {
       pSBMLReaction->unsetKineticLaw();
     }
   if (pSBMLReaction != NULL)
     {
       CSBMLExporter::setSBMLNotes(pSBMLReaction, &reaction);
     }
   CSBMLExporter::updateMIRIAMAnnotation(&reaction, pSBMLReaction, this->mMetaIdMap);
 }
void CSBMLExporter::createReactions (CCopasiDataModel & dataModel) protected
Creates the reactions for the model.
Definition at line 1417 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), createReaction(), CCopasiVector< T >::end(), CCopasiDataModel::getModel(), CModel::getReactions(), and mpSBMLDocument.
Referenced by createSBMLDocument().
 {
   // make sure the SBML Document already exists and that it has a Model set
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   CCopasiVectorNS<CReaction>::const_iterator it = dataModel.getModel()->getReactions().begin(), endit = dataModel.getModel()->getReactions().end();
   while (it != endit)
     {
       createReaction(**it, dataModel);
       ++it;
     }
 }
void CSBMLExporter::createRule (const CModelEntity & modelEntity, CCopasiDataModel & dataModel, Rule * pOldRule) protected
Creates the rule for the given COPASI model entity.
Definition at line 1937 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, convertExpression(), convertToASTNode(), createFunctionSetFromFunctionNames(), CCopasiMessage::ERROR, CCopasiMessage::EXCEPTION, findDirectlyUsedFunctions(), CModelEntity::FIXED, CMetab::getCompartment(), CCompartment::getDimensionality(), CModelEntity::getExpression(), CModelEntity::getExpressionPtr(), CCopasiRootContainer::getFunctionList(), CCopasiObject::getObjectName(), CCopasiObject::getObjectType(), CEvaluationTree::getRoot(), CModelEntity::getSBMLId(), CModelEntity::getStatus(), CEvaluationNode::getType(), CModelEntity::getValueReference(), CEvaluationNode::INVALID, isExpressionSBMLCompatible(), mCOPASI2SBMLMap, MCSBML, mIncompatibilities, mIncompleteExport, mInitialValueMap, mpSBMLDocument, mSBMLLevel, mSBMLVersion, multiplyByObject(), mUsedFunctions, outputIncompatibilities(), replace_local_parameters(), replaceSpeciesReferences(), CEvaluationTree::setInfix(), and CEvaluationNode::type().
Referenced by createRules().
 {
   // check the expression
   std::vector<SBMLIncompatibility> result;
   CSBMLExporter::isExpressionSBMLCompatible(*modelEntity.getExpressionPtr()
       , dataModel
       , this->mSBMLLevel
       , this->mSBMLVersion
       , result
       , std::string("rule for object named \"" + modelEntity.getObjectName() + "\"").c_str()
       , false
       , &mInitialValueMap);
   // collect directly used functions
   if (result.empty())
     {
       std::set<std::string> directlyUsedFunctionNames;
       CSBMLExporter::findDirectlyUsedFunctions(modelEntity.getExpressionPtr()->getRoot(), directlyUsedFunctionNames);
       std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(directlyUsedFunctionNames, CCopasiRootContainer::getFunctionList());
 # if defined _MSC_VER && _MSC_VER < 1201 // 1200 Identifies Visual C++ 6.0
       {
         std::set<CFunction*>::const_iterator it = usedFunctions.begin();
         std::set<CFunction*>::const_iterator end = usedFunctions.end();
         for (; it != end; ++it)
           this->mUsedFunctions.insert(*it);
       }
 #else
       this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
 #endif
       // create the actual rule
       //Rule* pRule = this->mpSBMLDocument->getModel()->getRule(modelEntity.getSBMLId());
       const CMetab* pMetab = dynamic_cast<const CMetab*>(&modelEntity);
       if (pOldRule == NULL)
         {
           if (modelEntity.getStatus() == CModelEntity::ASSIGNMENT)
             {
               pOldRule = this->mpSBMLDocument->getModel()->createAssignmentRule();
             }
           else
             {
               if (pMetab != NULL)
                 {
                   // check if the compartment is fixed
                   if (pMetab->getCompartment()->getStatus() != CModelEntity::FIXED)
                     {
                       CCopasiMessage(CCopasiMessage::ERROR, MCSBML + 52, pMetab->getObjectName().c_str());
                     }
                 }
               pOldRule = this->mpSBMLDocument->getModel()->createRateRule();
             }
           pOldRule->setVariable(modelEntity.getSBMLId());
         }
       else
         {
           // Read the rule to the model
           this->mpSBMLDocument->getModel()->getListOfRules()->appendAndOwn(pOldRule);
         }
       // set the math
       const std::string& changedExpression = convertExpression(modelEntity.getExpression(), mInitialValueMap);
       CEvaluationTree tree;
       tree.setInfix(changedExpression);
       const CEvaluationNode* pOrigNode = tree.getRoot();
       if (CEvaluationNode::type(pOrigNode->getType()) == CEvaluationNode::INVALID)
         {
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 70, "assignment", modelEntity.getObjectType().c_str(), modelEntity.getObjectName().c_str());
         }
       // the next few lines replace references to species depending on whether
       // it is a reference to an amount or a reference to a concentration.
       // Other factors that influence this replacement are if the model
       // contains variable volumes or if the quantity units are set to CModel::number
       pOrigNode = this->replaceSpeciesReferences(pOrigNode, dataModel);
       assert(pOrigNode != NULL);
       // check if the rule is for an amount species
       // if this is the case, we have to multiply the expression by the volume
       // of the compartment the species is in
       if (pMetab != NULL)
         {
           std::map<const CCopasiObject*, SBase*>::const_iterator pos = this->mCOPASI2SBMLMap.find(&modelEntity);
           assert(pos != this->mCOPASI2SBMLMap.end());
           if (dynamic_cast<const Species*>(pos->second)->getHasOnlySubstanceUnits() == true)
             {
               const CCompartment* pCompartment = pMetab->getCompartment();
               if (pCompartment->getDimensionality() != 0)
                 {
                   CEvaluationNode* pNode = CSBMLExporter::multiplyByObject(pOrigNode, pCompartment->getValueReference());
                   assert(pNode != NULL);
                   if (pNode != NULL)
                     {
                       delete pOrigNode;
                       pOrigNode = pNode;
                     }
                 }
             }
         }
       ASTNode* pNode = this->convertToASTNode(pOrigNode, dataModel);
       this->replace_local_parameters(pNode, dataModel);
       delete pOrigNode;
       if (pNode != NULL)
         {
           pOldRule->setMath(pNode);
           delete pNode;
         }
       else
         {
           if (this->mIncompleteExport != true)
             {
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "rule", modelEntity.getObjectType().c_str(), modelEntity.getObjectName().c_str());
             }
         }
     }
   else
     {
       this->mIncompatibilities.insert(this->mIncompatibilities.end(), result.begin(), result.end());
       if (!this->mIncompleteExport)
         {
           this->outputIncompatibilities();
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, "rule", modelEntity.getObjectType().c_str(), modelEntity.getObjectName().c_str());
         }
     }
 }
void CSBMLExporter::createRules (CCopasiDataModel & dataModel) protected
Creates the rules for the model.
Definition at line 1835 of file CSBMLExporter.cpp.
References createRule(), CModelEntity::getSBMLId(), mODEVector, mpSBMLDocument, and orderRules().
Referenced by createSBMLDocument().
 {
   // make sure the mAssignmentVector has been filled already
   // make sure the mODEVector has been filled already
   // order the rules for Level 1 export
   // rules in Level 2 are not ordered.
   //if (this->mSBMLLevel == 1 || (this->mSBMLLevel == 2 && this->mSBMLVersion == 1))
   //  {
   std::vector<CModelEntity*> orderedAssignmentRules = orderRules(dataModel);
   //}
   //
   // remove all rules from the SBML model
   // and put them in a map
   std::map<std::string, Rule*> ruleMap;
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   assert(pSBMLModel != NULL);
   while (pSBMLModel->getNumRules() != 0)
     {
       Rule* pRule = pSBMLModel->getRule(0);
       assert(pRule != NULL);
       // ignore algebraic rules
       if (pRule->getTypeCode() == SBML_ASSIGNMENT_RULE)
         {
           AssignmentRule* pARule = dynamic_cast<AssignmentRule*>(pRule);
           assert(pARule != NULL);
           ruleMap[pARule->getVariable()] = pARule;
         }
       else if (pRule->getTypeCode() == SBML_RATE_RULE)
         {
           RateRule* pRRule = dynamic_cast<RateRule*>(pRule);
           assert(pRRule != NULL);
           ruleMap[pRRule->getVariable()] = pRRule;
         }
       pSBMLModel->getListOfRules()->remove(0);
     }
   // create the rules
   const CModelEntity* pME = NULL;
   size_t i, iMax = orderedAssignmentRules.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = orderedAssignmentRules[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           std::map<std::string, Rule*>::const_iterator pos = ruleMap.find(pME->getSBMLId());
           Rule* pOldRule = NULL;
           if (pos != ruleMap.end())
             {
               pOldRule = pos->second;
               assert(pOldRule != NULL);
               ruleMap.erase(pos->first);
             }
           createRule(*pME, dataModel, pOldRule);
         }
     }
   iMax = mODEVector.size();
   for (i = 0; i < iMax; ++i)
     {
       pME = mODEVector[i];
       assert(pME != NULL);
       if (pME != NULL)
         {
           std::map<std::string, Rule*>::const_iterator pos = ruleMap.find(pME->getSBMLId());
           Rule* pOldRule = NULL;
           if (pos != ruleMap.end())
             {
               pOldRule = pos->second;
               assert(pOldRule != NULL);
               ruleMap.erase(pos->first);
             }
           createRule(*pME, dataModel, pOldRule);
         }
     }
   // delete the remaining rules
   std::map<std::string, Rule*>::iterator mapIt = ruleMap.begin(), mapEndit = ruleMap.end();
   while (mapIt != mapEndit)
     {
       delete mapIt->second;
       ++mapIt;
     }
   ruleMap.clear();
 }
void CSBMLExporter::createSBMLDocument (CCopasiDataModel & dataModel) protected
Creates an SBMLDocument from the given CCopasiDataModelObject. It checks if an SBMLDocument already exists from an import and if this is the case, the old document is copied. If none exists a new one is created. Copying the old one makes sure that if something goes wrong during export, the original model is still consistent.
Definition at line 3399 of file CSBMLExporter.cpp.
References addInitialAssignmentsToModel(), assignSBMLIdsToReactions(), checkForInitialAssignments(), SBMLUtils::collectIds(), collectIds(), convertToLevel1(), createCompartments(), createEvents(), createFunctionDefinitions(), createInitialAssignments(), createMetabolites(), createParameters(), createReactions(), createRules(), createUniqueId(), createUnits(), CCopasiMessage::EXCEPTION, fatalError, findAvogadro(), CCopasiDataModel::getCurrentSBMLDocument(), CModelEntity::getKey(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CModelEntity::getSBMLId(), hasVolumeAssignment(), mAvogadroCreated, mCOPASI2SBMLMap, mExportedFunctions, mFunctionIdMap, mFunctionMap, mHaveModelHistoryAuthorWarning, mHaveModelHistoryCreationDateWarning, mHaveModelHistoryModificationDateWarning, mIdMap, mIncompatibilities, mIncompleteExport, mInitialValueMap, mMetaIdMap, mpAvogadro, mpSBMLDocument, mSBMLLevel, mSBMLVersion, mVariableVolumes, outputIncompatibilities(), CModel::removeModelValue(), setSBMLNotes(), updateCOPASI2SBMLMap(), and updateMIRIAMAnnotation().
Referenced by exportModelToString().
 {
   // reset warnings for missing entries in modelhistory
   mHaveModelHistoryAuthorWarning = false;
   mHaveModelHistoryCreationDateWarning = false;
   mHaveModelHistoryModificationDateWarning = false;
   const SBMLDocument* pOldSBMLDocument = dataModel.getCurrentSBMLDocument();
   const CModel* pModel = dataModel.getModel();
   assert(pModel != NULL);
   if (pOldSBMLDocument == NULL)
     {
       this->mpSBMLDocument = new SBMLDocument(this->mSBMLLevel, this->mSBMLVersion);
     }
   else
     {
       this->mpSBMLDocument = dynamic_cast<SBMLDocument*>(pOldSBMLDocument->clone());
     }
   if (this->mpSBMLDocument == NULL) fatalError();
 #if LIBSBML_VERSION >= 50000
   const std::string uri = (this->mSBMLLevel < 3 ? LayoutExtension::getXmlnsL2() : LayoutExtension::getXmlnsL3V1V1());
   this->mpSBMLDocument->enablePackage(uri, "layout", true);
   if (this->mSBMLLevel > 2)
     this->mpSBMLDocument->setPackageRequired("layout", false);
   const std::string renderuri = (this->mSBMLLevel < 3 ? RenderExtension::getXmlnsL2() : RenderExtension::getXmlnsL3V1V1());
   this->mpSBMLDocument->enablePackage(renderuri, "render", true);
   if (this->mSBMLLevel > 2)
     this->mpSBMLDocument->setPackageRequired("render", false);
 #endif
   if (this->mpSBMLDocument->getModel() == NULL)
     {
       // there might still be COPASI object that have an SBML id, we have to
       // collect those as well
       CSBMLExporter::collectIds(dataModel, this->mIdMap);
       std::string id = pModel->getSBMLId();
       if (id.empty())
         {
           id = CSBMLExporter::createUniqueId(this->mIdMap, pModel->getObjectName(), false);
           this->mIdMap.insert(std::pair<const std::string, const SBase*>(id, this->mpSBMLDocument->getModel()));
         }
       this->mpSBMLDocument->createModel(id);
     }
   else
     {
       SBMLUtils::collectIds(this->mpSBMLDocument->getModel(), this->mIdMap, this->mMetaIdMap);
     }
   this->mFunctionIdMap.clear();
   // update the copasi2sbmlmap
   updateCOPASI2SBMLMap(dataModel);
   // update the comments on the model
   this->mpSBMLDocument->getModel()->setName(pModel->getObjectName());
   if (pModel != NULL && this->mpSBMLDocument->getModel() != NULL)
     {
       CSBMLExporter::setSBMLNotes(this->mpSBMLDocument->getModel(), pModel);
     }
   // update the MIRIAM annotation on the model
   CSBMLExporter::updateMIRIAMAnnotation(pModel, this->mpSBMLDocument->getModel(), this->mMetaIdMap);
 #if LIBSBML_VERSION >= 40100
   if (this->mSBMLLevel > 2)
     {
       // we have to remove the conversionFactor because on import we multiplied the stoichiometries
       // with this factor
       this->mpSBMLDocument->getModel()->unsetConversionFactor();
     }
 #endif // LIBSBML_VERSION
   // create units, compartments, species, parameters, reactions, initial
   // assignment, assignments, (event) and function definitions
   createUnits(dataModel);
   // try to find a parameter that represents Avogadros number
   findAvogadro(dataModel);
   // check if there is an assignment to a volume
   // in that case we has to export all species with the
   // hasOnlySubstanceUnits flag set to true
   this->mVariableVolumes = this->hasVolumeAssignment(dataModel);
   createCompartments(dataModel);
   createMetabolites(dataModel);
   createParameters(dataModel);
   // TODO here we should check the expressions but the function definitions
   // TODO have not been created yet, so we can't
   // TODO Maybe we don't have to do all checks here.
   // TODO it would probably be enough to check if the expressions are valid and
   // TODO to check the function calls later on when the functions are created.
   // only export initial assignments for Level 2 Version 2 and above
   if (this->mSBMLLevel != 1 && !(this->mSBMLLevel == 2 && this->mSBMLVersion == 1))
     {
       createInitialAssignments(dataModel);
     }
   else
     {
       checkForInitialAssignments(dataModel, this->mIncompatibilities);
     }
   // since the flux of a reaction can be referenced in an assignment,
   // we have to make sure that asll reactions do have SBML Ids prior to creating the rules
   // and events
   assignSBMLIdsToReactions(dataModel.getModel());
   createRules(dataModel);
   createEvents(dataModel);
   // we have to export the reactions after all other entities that have
   // expressions since an expression could contain a local parameter
   // If it did, it would have to be converted to a global parameter and that
   // has to be taken into consideration when creating the reactions
   createReactions(dataModel);
   // find all used functions
   createFunctionDefinitions(dataModel);
   if (this->mSBMLLevel == 1)
     {
       // do SBML Level1 Voodoo
       // e.g. replace some of the unsupported nodes with workarounds
       convertToLevel1();
       // delete all function definitions since L1 does not have functions
       Model* pSBMLModel = this->mpSBMLDocument->getModel();
       assert(pSBMLModel != NULL);
       int i = pSBMLModel->getListOfFunctionDefinitions()->size();
       while (i > 0)
         {
           --i;
           // fix for bug 1086
           // remove the object from the COPASI2SBML Map
           std::map<const CCopasiObject*, SBase*>::iterator it = this->mCOPASI2SBMLMap.begin(), endit = this->mCOPASI2SBMLMap.end();
           while (it != endit)
             {
               if (it->second == pSBMLModel->getFunctionDefinition(i))
                 {
                   this->mCOPASI2SBMLMap.erase(it);
                   break;
                 }
               ++it;
             }
           delete pSBMLModel->getListOfFunctionDefinitions()->remove(i);
         }
     }
   else
     {
       // add all function definitions to the model
       Model* pSBMLModel = this->mpSBMLDocument->getModel();
       assert(pSBMLModel != NULL);
       if (pSBMLModel != NULL)
         {
           unsigned int i = 0, iMax = this->mExportedFunctions.size();
 #if LIBSBML_VERSION >= 40100
           int result;
 #endif // LIBSBML_VERSION >= 40100
           FunctionDefinition* pFunDef = NULL;
           std::map<const FunctionDefinition*, const CCopasiObject*>::const_iterator funPos;
           while (i < iMax)
             {
               pFunDef = this->mExportedFunctions.get(i);
               assert(pFunDef != NULL);
               // match the namespaces to those of the model
               pFunDef->setSBMLNamespaces(pSBMLModel->getSBMLNamespaces());
 // add methods only return a value starting with libsbml 4
 #if LIBSBML_VERSION >= 40100
               result = pSBMLModel->addFunctionDefinition(pFunDef);
               assert(result == LIBSBML_OPERATION_SUCCESS);
 #else
               pSBMLModel->addFunctionDefinition(pFunDef);
               assert(pSBMLModel->getFunctionDefinition(pFunDef->getId()) != NULL);
 #endif // LIBSBML_VERSION >= 40100
               // now we need to add the newly created FunctionDefinition to the copasi2sbml map
               funPos = this->mFunctionMap.find(pFunDef);
               assert(funPos != this->mFunctionMap.end());
               pFunDef = pSBMLModel->getFunctionDefinition(pFunDef->getId());
               assert(pFunDef != NULL);
               this->mCOPASI2SBMLMap[funPos->second] = pFunDef;
               ++i;
             }
           //the assert below no longer holds, as we export uniform / normal as functiondefinitions
           //assert(pSBMLModel->getNumFunctionDefinitions() == this->mExportedFunctions.size());
         }
     }
   // In case the document is just a clone of an old model, we have to set the level and version
   if (this->mpSBMLDocument->getLevel() != this->mSBMLLevel || this->mpSBMLDocument->getVersion() != this->mSBMLVersion)
     {
 #if LIBSBML_VERSION >= 50400
       SBMLNamespaces targetNs(mSBMLLevel, mSBMLVersion); // use reference, as the ns gets cloned
       if (mSBMLLevel == 1 && mSBMLVersion == 1)
         {
           // l1v1 export tailor made to suit GEPASI, with pow -> ^ notation and
           // inlining of compartment sizes in kinetics.
           ConversionProperties prop(&targetNs);
           prop.addOption("convertToL1V1", true,
                          "convert the document to SBML Level 1 Version 1");
           prop.addOption("changePow", true,
                          "change pow expressions to the (^) hat notation");
           prop.addOption("inlineCompartmentSizes", true,
                          "if true, occurrances of compartment ids in expressions will be replaced with their initial size");
           mpSBMLDocument->convert(prop);
         }
       else
         {
           ConversionProperties prop(&targetNs);
           prop.addOption("strict", false);
           prop.addOption("setLevelAndVersion", true);
           prop.addOption("ignorePackages", true);
           mpSBMLDocument->convert(prop);
         }
 #else
       this->mpSBMLDocument->setLevelAndVersion(this->mSBMLLevel, this->mSBMLVersion);
 #endif
     }
   if (this->mpSBMLDocument->getLevel() != this->mSBMLLevel || this->mpSBMLDocument->getVersion() != this->mSBMLVersion)
     {
       unsigned int i, iMax = this->mpSBMLDocument->getNumErrors();
       std::string message("libSBML could not convert the model to the requested level and/or version. The reason(s) given were:");
       for (i = 0; i < iMax ; ++i)
         {
           const XMLError* pSBMLError = this->mpSBMLDocument->getError(i);
           message += "\n";
           message += pSBMLError->getMessage();
         }
       CCopasiMessage(CCopasiMessage::EXCEPTION, message.c_str());
     }
   // remove mpAvogadro from the model again
   if (this->mAvogadroCreated == true)
     {
       std::map<const CCopasiObject*, SBase*>::iterator pos = this->mCOPASI2SBMLMap.find(this->mpAvogadro);
       this->mCOPASI2SBMLMap.erase(pos);
       dataModel.getModel()->removeModelValue(this->mpAvogadro->getKey(), true);
     }
   this->outputIncompatibilities();
   // if the model is incompatible with SBML export, throw an exception
   if (!this->mIncompatibilities.empty() && !this->mIncompleteExport)
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, "Model incompatible with chosen version and/or level of SBML.");
     }
   // if initial assignments were used we will have to add them to the document
   addInitialAssignmentsToModel(mpSBMLDocument, mInitialValueMap, dataModel);
   mInitialValueMap.clear();
   // delete all temporary function definitions
   // and the function map
   this->mExportedFunctions.clear(true);
   this->mFunctionMap.clear();
 }
void CSBMLExporter::createSubstanceUnit (const CCopasiDataModel & dataModel) protected
Creates the substance unit for the SBML model.
Definition at line 583 of file CSBMLExporter.cpp.
References SBMLImporter::areSBMLUnitDefinitionsIdentical(), CModel::dimensionlessQuantity, CCopasiMessage::EXCEPTION, CModel::fMol, CCopasiDataModel::getModel(), CModel::getQuantityUnitEnum(), INIT_DEFAULTS, CModel::microMol, CModel::mMol, CModel::Mol, mpSBMLDocument, mSBMLLevel, mSBMLVersion, CModel::nMol, CModel::number, and CModel::pMol.
Referenced by createUnits().
 {
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   UnitDefinition uDef(this->mSBMLLevel, this->mSBMLVersion);
   uDef.setName("substance");
   uDef.setId("substance");
   Unit unit(this->mSBMLLevel, this->mSBMLVersion);
   INIT_DEFAULTS(unit);
   switch (dataModel.getModel()->getQuantityUnitEnum())
     {
       case CModel::Mol:
         unit.setKind(UNIT_KIND_MOLE);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       case CModel::mMol:
         unit.setKind(UNIT_KIND_MOLE);
         unit.setExponent(1);
         unit.setScale(-3);
         break;
       case CModel::microMol:
         unit.setKind(UNIT_KIND_MOLE);
         unit.setExponent(1);
         unit.setScale(-6);
         break;
       case CModel::nMol:
         unit.setKind(UNIT_KIND_MOLE);
         unit.setExponent(1);
         unit.setScale(-9);
         break;
       case CModel::pMol:
         unit.setKind(UNIT_KIND_MOLE);
         unit.setExponent(1);
         unit.setScale(-12);
         break;
       case CModel::fMol:
         unit.setKind(UNIT_KIND_MOLE);
         unit.setExponent(1);
         unit.setScale(-15);
         break;
       case CModel::number:
         unit.setKind(UNIT_KIND_ITEM);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       case CModel::dimensionlessQuantity:
         unit.setKind(UNIT_KIND_DIMENSIONLESS);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, "SBMLExporter Error: Unknown copasi quantity unit.");
         break;
     }
   unit.setMultiplier(1);
   uDef.addUnit(&unit);
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   UnitDefinition* pUdef = pSBMLModel->getUnitDefinition("substance");
   if (pUdef != NULL)
     {
       // check if it is the same unit as the existing one if there is one
       // if yes, return, else replace the existing one
       if (!SBMLImporter::areSBMLUnitDefinitionsIdentical(pUdef, &uDef))
         {
           (*pUdef) = uDef;
         }
     }
   else
     {
       // only add it if it is not the default unit definition anyway
       if (this->mSBMLLevel > 2 || unit.getKind() != UNIT_KIND_MOLE || unit.getScale() != 0 || unit.getExponent() != 1 || unit.getMultiplier() != 1.0)
         {
           // set the unit definition
           pSBMLModel->addUnitDefinition(&uDef);
         }
     }
 // if we write an SBML L3 document, we have to explicitely set the units on the model
 #if LIBSBML_VERSION >= 40100
   if (this->mSBMLLevel > 2)
     {
       pSBMLModel->setSubstanceUnits(uDef.getId());
       // here we also set the extent unit to the same unit as the substance unit
       // because COPASI does not know about different extent units
       pSBMLModel->setExtentUnits(uDef.getId());
     }
 #endif // LIBSBML_VERSION
 }
ASTNode * CSBMLExporter::createTimesTree (const CCopasiVector< CChemEqElement > & vect, unsigned int pos = 0) static protected
This method creates an ASTNode tree where all the species specified in the given vector are multiplied. This is used to create the mass action kinetic law.
Definition at line 4872 of file CSBMLExporter.cpp.
References CModelEntity::getSBMLId(), and CCopasiVector< T >::size().
 {
   ASTNode* pNode = NULL;
   double multiplicity = vect[pos]->getMultiplicity();
   if (pos == vect.size() - 1)
     {
       pNode = new ASTNode(AST_NAME);
       const CMetab* pMetab = vect[pos]->getMetabolite();
       assert(pMetab);
       pNode->setName(pMetab->getSBMLId().c_str());
       /* if the stoichiometry is not 1.0, we have to add it to the exponent */
       if (multiplicity != 1.0)
         {
           ASTNode* pTmpNode1 = new ASTNode(AST_POWER);
           ASTNode* pTmpNode2 = new ASTNode(AST_REAL);
           pTmpNode2->setValue(multiplicity);
           pTmpNode1->addChild(pNode);
           pTmpNode1->addChild(pTmpNode2);
           pNode = pTmpNode1;
         }
     }
   else
     {
       pNode = new ASTNode(AST_TIMES);
       ASTNode* pChild = new ASTNode(AST_NAME);
       const CMetab* pMetab = vect[pos]->getMetabolite();
       assert(pMetab);
       pChild->setName(pMetab->getSBMLId().c_str());
       /* if the stoichiometry is not 1.0, we have to add it to the exponent */
       if (multiplicity != 1.0)
         {
           ASTNode* pTmpNode1 = new ASTNode(AST_POWER);
           ASTNode* pTmpNode2 = new ASTNode(AST_REAL);
           pTmpNode2->setValue(multiplicity);
           pTmpNode1->addChild(pChild);
           pTmpNode1->addChild(pTmpNode2);
           pChild = pTmpNode1;
         }
       pNode->addChild(pChild);
       pNode->addChild(CSBMLExporter::createTimesTree(vect, pos + 1));
     }
   return pNode;
 }
void CSBMLExporter::createTimeUnit (const CCopasiDataModel & dataModel) protected
Creates the time unit for the SBML model.
Definition at line 354 of file CSBMLExporter.cpp.
References SBMLImporter::areSBMLUnitDefinitionsIdentical(), CModel::d, CModel::dimensionlessTime, CCopasiMessage::EXCEPTION, CModel::fs, CCopasiDataModel::getModel(), CModel::getTimeUnitEnum(), CModel::h, INIT_DEFAULTS, CModel::micros, CModel::min, mpSBMLDocument, CModel::ms, mSBMLLevel, mSBMLVersion, CModel::ns, CModel::ps, and CModel::s.
Referenced by createUnits().
 {
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   UnitDefinition uDef(this->mSBMLLevel, this->mSBMLVersion);
   uDef.setName("time");
   uDef.setId("time");
   Unit unit(this->mSBMLLevel, this->mSBMLVersion);
   INIT_DEFAULTS(unit);
   switch (dataModel.getModel()->getTimeUnitEnum())
     {
       case CModel::d:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(0);
         unit.setMultiplier(86400);
         break;
       case CModel::h:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(0);
         unit.setMultiplier(3600);
         break;
       case CModel::min:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(0);
         unit.setMultiplier(60);
         break;
       case CModel::s:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(0);
         unit.setMultiplier(1);
         break;
       case CModel::ms:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(-3);
         unit.setMultiplier(1);
         break;
       case CModel::micros:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(-6);
         unit.setMultiplier(1);
         break;
       case CModel::ns:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(-9);
         unit.setMultiplier(1);
         break;
       case CModel::ps:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(-12);
         unit.setMultiplier(1);
         break;
       case CModel::fs:
         unit.setKind(UNIT_KIND_SECOND);
         unit.setExponent(1);
         unit.setScale(-15);
         unit.setMultiplier(1);
         break;
       case CModel::dimensionlessTime:
         unit.setKind(UNIT_KIND_DIMENSIONLESS);
         unit.setExponent(1);
         unit.setScale(0);
         unit.setMultiplier(1);
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, "SBMLExporter Error: Unknown copasi time unit.");
         break;
     }
   uDef.addUnit(&unit);
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   UnitDefinition* pUdef = pSBMLModel->getUnitDefinition("time");
   if (pUdef != NULL)
     {
       // check if it is the same unit as the existing one if there is one
       // if yes, return, else replace the existing one
       if (!SBMLImporter::areSBMLUnitDefinitionsIdentical(pUdef, &uDef))
         {
           (*pUdef) = uDef;
         }
     }
   else
     {
       // only add it if it is not the default unit definition anyway
       // from SBML Level 3 on, there are no default units
       // so we have to write it
       if (this->mSBMLLevel > 2 || unit.getKind() != UNIT_KIND_SECOND || unit.getScale() != 0 || unit.getExponent() != 1 || unit.getMultiplier() != 1.0)
         {
           // set the unit definition
           pSBMLModel->addUnitDefinition(&uDef);
         }
     }
 // if we write an SBML L3 document, we have to explicitely set the units on the model
 #if LIBSBML_VERSION >= 40100
   if (this->mSBMLLevel > 2)
     {
       pSBMLModel->setTimeUnits(uDef.getId());
     }
 #endif // LIBSBML_VERSION
 }
const std::string CSBMLExporter::createUniqueId (const std::map< std::string, const SBase * > & idMap, const std::string & prefix, bool addIndexForFirst, const std::string & separator = "_") static
Create a unique id for an SBML object. I can't just take the Copasi key of the object since this might conflict with an already existing sbml id which came from the sbmlid attribute in a copasi file or directly by importing an SBML file.
Create a unique id for an SBML object. I can't just take the COPASI key of the object since this might conflict with an already existing SBML id which came from the sbmlid attribute in a COPASI file or directly by importing an SBML file.
Definition at line 2252 of file CSBMLExporter.cpp.
References nameToSbmlId().
Referenced by assignSBMLIdsToReactions(), createCompartment(), createEvent(), createFunctionDefinition(), createFunctionDefinitonForURI(), createMetabolite(), createParameter(), createReaction(), createSBMLDocument(), CLGraphicalObject::exportToSBML(), CLayout::exportToSBML(), replace_local_parameters(), replaceSpeciesReferences(), setFunctionSBMLIds(), and updateMIRIAMAnnotation().
 {
   std::string Prefix = nameToSbmlId(prefix);
   unsigned int i = 0;
   std::ostringstream Id;
   if (addIndexForFirst)
     {
       Id << Prefix << separator << i++;
     }
   else
     {
       Id << Prefix;
     }
   while (idMap.find(Id.str()) != idMap.end())
     {
       Id.str("");
       Id << Prefix << separator << i++;
     }
   return Id.str();
 }
void CSBMLExporter::createUnits (const CCopasiDataModel & dataModel) protected
Creates the units for the SBML model.
Definition at line 342 of file CSBMLExporter.cpp.
References createAreaUnit(), createLengthUnit(), createSubstanceUnit(), createTimeUnit(), and createVolumeUnit().
Referenced by createSBMLDocument().
 {
   createLengthUnit(dataModel);
   createAreaUnit(dataModel);
   createVolumeUnit(dataModel);
   createTimeUnit(dataModel);
   createSubstanceUnit(dataModel);
 }
const std::set< CEvaluationNodeFunction::SubType > CSBMLExporter::createUnsupportedFunctionTypeSet (unsigned int sbmlLevel) static protected
Creates a set of all function subtypes that can not be exported for a certain SBML level.
Definition at line 3680 of file CSBMLExporter.cpp.
References CEvaluationNodeFunction::ARCCOTH, CEvaluationNodeFunction::MAX, and CEvaluationNodeFunction::MIN.
Referenced by checkForUnsupportedFunctionCalls(), and isExpressionSBMLCompatible().
 {
   std::set<CEvaluationNodeFunction::SubType> unsupportedFunctionTypes;
   if (sbmlLevel == 1)
     {
       // check what to do with all the functions that are not supported by
       // SBML Level 1
       // Also take care of other unsupported nodes in L1
       // (inf,nan,pi,exponentiale)
       // most functions that are not supported by Level 1, but Level 2
       //  can not be converted to something that can be exported.
       // Roundtripping of those  will not succeed, but the results should stay
       // the same. The only function that can not be correctly converted
       // is ARCCOTH since we would need a piecewise for that which is not
       // supported in Level 1
       unsupportedFunctionTypes.insert(CEvaluationNodeFunction::ARCCOTH);
       //unsupportedFunctionTypes.insert(CEvaluationNodeFunction::RNORMAL);
       //unsupportedFunctionTypes.insert(CEvaluationNodeFunction::RUNIFORM);
       unsupportedFunctionTypes.insert(CEvaluationNodeFunction::MAX);
       unsupportedFunctionTypes.insert(CEvaluationNodeFunction::MIN);
     }
   else
     {
       //unsupportedFunctionTypes.insert(CEvaluationNodeFunction::RNORMAL);
       //unsupportedFunctionTypes.insert(CEvaluationNodeFunction::RUNIFORM);
       //unsupportedFunctionTypes.insert(CEvaluationNodeFunction::MAX);
       //unsupportedFunctionTypes.insert(CEvaluationNodeFunction::MIN);
     }
   return unsupportedFunctionTypes;
 }
void CSBMLExporter::createVolumeUnit (const CCopasiDataModel & dataModel) protected
Creates the volume unit for the SBML model.
Definition at line 480 of file CSBMLExporter.cpp.
References SBMLImporter::areSBMLUnitDefinitionsIdentical(), CModel::dimensionlessVolume, CCopasiMessage::EXCEPTION, CModel::fl, CCopasiDataModel::getModel(), CModel::getVolumeUnitEnum(), INIT_DEFAULTS, CModel::l, CModel::m3, CModel::microl, CModel::ml, mpSBMLDocument, mSBMLLevel, mSBMLVersion, CModel::nl, and CModel::pl.
Referenced by createUnits().
 {
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return;
   UnitDefinition uDef(this->mSBMLLevel, this->mSBMLVersion);
   uDef.setName("volume");
   uDef.setId("volume");
   Unit unit(this->mSBMLLevel, this->mSBMLVersion);
   INIT_DEFAULTS(unit);
   switch (dataModel.getModel()->getVolumeUnitEnum())
     {
       case CModel::l:
         unit.setKind(UNIT_KIND_LITRE);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       case CModel::ml:
         unit.setKind(UNIT_KIND_LITRE);
         unit.setExponent(1);
         unit.setScale(-3);
         break;
       case CModel::microl:
         unit.setKind(UNIT_KIND_LITRE);
         unit.setExponent(1);
         unit.setScale(-6);
         break;
       case CModel::nl:
         unit.setKind(UNIT_KIND_LITRE);
         unit.setExponent(1);
         unit.setScale(-9);
         break;
       case CModel::pl:
         unit.setKind(UNIT_KIND_LITRE);
         unit.setExponent(1);
         unit.setScale(-12);
         break;
       case CModel::fl:
         unit.setKind(UNIT_KIND_LITRE);
         unit.setExponent(1);
         unit.setScale(-15);
         break;
       case CModel::m3:
         unit.setKind(UNIT_KIND_METRE);
         unit.setExponent(3);
         unit.setScale(0);
         break;
       case CModel::dimensionlessVolume:
         unit.setKind(UNIT_KIND_DIMENSIONLESS);
         unit.setExponent(1);
         unit.setScale(0);
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, "SBMLExporter Error: Unknown copasi volume unit.");
         break;
     }
   unit.setMultiplier(1.0);
   uDef.addUnit(&unit);
   Model* pSBMLModel = this->mpSBMLDocument->getModel();
   UnitDefinition* pUdef = pSBMLModel->getUnitDefinition("volume");
   if (pUdef != NULL)
     {
       // check if it is the same unit as the existing one if there is one
       // if yes, return, else replace the existing one
       if (!SBMLImporter::areSBMLUnitDefinitionsIdentical(pUdef, &uDef))
         {
           (*pUdef) = uDef;
         }
     }
   else
     {
       // only add it if it is not the default unit definition anyway
       if (this->mSBMLLevel > 2 || unit.getKind() != UNIT_KIND_LITRE || unit.getScale() != 0 || unit.getExponent() != 1 || unit.getMultiplier() != 1.0)
         {
           // set the unit definition
           pSBMLModel->addUnitDefinition(&uDef);
         }
     }
 // if we write an SBML L3 document, we have to explicitely set the units on the model
 #if LIBSBML_VERSION >= 40100
   if (this->mSBMLLevel > 2)
     {
       pSBMLModel->setVolumeUnits(uDef.getId());
     }
 #endif // LIBSBML_VERSION
 }
void CSBMLExporter::disownSBMLDocument ()
This method assures that the SBMLDocument is not deleted by the destructor of the exporter. This allows us to get the SBMLDocument from the exporter and store it in the data model without having to copy it.
Definition at line 7181 of file CSBMLExporter.cpp.
References mDocumentDisowned.
Referenced by CCopasiDataModel::exportSBML(), and CCopasiDataModel::exportSBMLToString().
 {
   this->mDocumentDisowned = true;
 }
void CSBMLExporter::exportEventAssignments (const CEvent & event, Event * pSBMLEvent, CCopasiDataModel & dataModel) protected
This method creates the individual event assignments for the given event.
Definition at line 4294 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), convertExpression(), convertToASTNode(), createFunctionSetFromFunctionNames(), CCopasiVector< T >::end(), CCopasiMessage::EXCEPTION, fatalError, findDirectlyUsedFunctions(), CKeyFactory::get(), CMetab::getCompartment(), CCompartment::getDimensionality(), CCopasiRootContainer::getFunctionList(), CEvaluationTree::getInfix(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiObject::getObjectType(), CEvaluationTree::getRoot(), CEvent::getSBMLId(), CEvaluationNode::getType(), CModelEntity::getValueReference(), CEvaluationNode::INVALID, isExpressionSBMLCompatible(), mCOPASI2SBMLMap, MCSBML, mHandledSBMLObjects, mIncompatibilities, mIncompleteExport, mInitialValueMap, mSBMLLevel, mSBMLVersion, multiplyByObject(), mUsedFunctions, outputIncompatibilities(), replace_local_parameters(), replaceSpeciesReferences(), CEvaluationTree::setInfix(), CEvaluationNode::type(), and CCopasiMessage::WARNING.
Referenced by createEvent().
 {
   //  we export all event assignments
   //    i) delete all event assignments and add them to a vector (see rules)
   std::map<std::string, EventAssignment*> assignmentMap;
   while (pSBMLEvent->getNumEventAssignments() != 0)
     {
       EventAssignment* pAssignment = pSBMLEvent->getEventAssignment(pSBMLEvent->getNumEventAssignments() - 1);
       assert(pAssignment != NULL);
       assignmentMap[pAssignment->getVariable()] = pAssignment;
       pSBMLEvent->getListOfEventAssignments()->remove(pSBMLEvent->getNumEventAssignments() - 1);
     }
   CCopasiVectorN< CEventAssignment >::const_iterator itAssignment = event.getAssignments().begin();
   CCopasiVectorN< CEventAssignment >::const_iterator endAssignment = event.getAssignments().end();
   for (; itAssignment != endAssignment; ++itAssignment)
     {
       //    ii) for each assignment, check if there already is an old assignment
       //        for this variable
       std::string key = (*itAssignment)->getTargetKey();
       //        now we have to get the object for the key, check if the object is a
       //        compartment, species or global parameter,
       const CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(key);
       std::string objectType = pObject->getObjectType();
       if (objectType == "Reference")
         {
           pObject = pObject->getObjectParent();
           objectType = pObject->getObjectType();
         }
       if (objectType != "Compartment" && objectType != "Metabolite" && objectType != "ModelValue")
         {
           // create an error message that only compartment, species and
           // global parameters can be used in an event assignment
           CCopasiMessage(CCopasiMessage::WARNING, MCSBML + 32, std::string("event assignment for event called \"" + event.getObjectName() + "\"").c_str(), pObject->getObjectName().c_str());
         }
       std::map<const CCopasiObject*, SBase*>::const_iterator pos = this->mCOPASI2SBMLMap.find(pObject);
       if (pos == this->mCOPASI2SBMLMap.end())
         {
           // create a general error message that the export of an event
           // assignment failed and continue
           CCopasiMessage(CCopasiMessage::WARNING, MCSBML + 73, std::string("event assignment for object called \"" + pObject->getObjectName() + "\" in evend named \"" + event.getObjectName() + "\"").c_str(), "event assignment");
           continue;
         }
       //  iii) for each assignment, check if the object that variable points to has been exported
       SBase* pSBase = pos->second;
       assert(pSBase != NULL);
       if (this->mHandledSBMLObjects.find(pSBase) == this->mHandledSBMLObjects.end())
         {
           // create an error message that the event assignment is for an object
           // that is no longer part of the model
           // ignore it and continue
           CCopasiMessage(CCopasiMessage::WARNING, MCSBML + 57, std::string("event assignment in event called \"" + event.getObjectName() + "\"").c_str(), pSBase->getId().c_str());
           continue;
         }
       // set the constant flag to false
       Compartment* pSBMLCompartment = NULL;
       Species* pSBMLSpecies = NULL;
       Parameter* pSBMLParameter = NULL;
       switch (pSBase->getTypeCode())
         {
           case SBML_COMPARTMENT:
             pSBMLCompartment = dynamic_cast<Compartment*>(pSBase);
             assert(pSBMLCompartment != NULL);
             if (pSBMLCompartment->getConstant() == true)
               {
                 pSBMLCompartment->setConstant(false);
               }
             break;
           case SBML_SPECIES:
             pSBMLSpecies = dynamic_cast<Species*>(pSBase);
             assert(pSBMLSpecies != NULL);
             if (pSBMLSpecies->getConstant() == true)
               {
                 pSBMLSpecies->setConstant(false);
               }
             break;
           case SBML_PARAMETER:
             pSBMLParameter = dynamic_cast<Parameter*>(pSBase);
             assert(pSBMLParameter != NULL);
             if (pSBMLParameter->getConstant() == true)
               {
                 pSBMLParameter->setConstant(false);
               }
             break;
           default:
             fatalError();
             break;
         }
       std::string sbmlId = pSBase->getId();
       assert(sbmlId.find_first_not_of("\t\r\n ") != std::string::npos);
       std::map<std::string, EventAssignment*>::iterator pos2 = assignmentMap.find(sbmlId);
       EventAssignment* pAssignment = NULL;
       if (pos2 != assignmentMap.end())
         {
           pAssignment = dynamic_cast<EventAssignment*>(pos2->second);
           assert(pAssignment != NULL);
           pSBMLEvent->getListOfEventAssignments()->appendAndOwn(pAssignment);
           // remove the entry from the event assigment map
           assignmentMap.erase(pos2);
         }
       if (pAssignment == NULL)
         {
           pAssignment = pSBMLEvent->createEventAssignment();
         }
       pAssignment->setVariable(sbmlId);
       //    iv) for each assignment, check the assignment expression if it is valid
       const CExpression * pExpression = (*itAssignment)->getExpressionPtr();
       if (pExpression != NULL)
         {
           std::vector<SBMLIncompatibility> result;
           CSBMLExporter::isExpressionSBMLCompatible(
             *pExpression
             , dataModel
             , this->mSBMLLevel
             , this->mSBMLVersion
             , result
             , std::string("event assignment for variable \"" + sbmlId + "\" in event with id\"+" + event.getSBMLId() + "\"")
             , false
             , &mInitialValueMap);
           // collect directly used functions
           if (result.empty())
             {
               std::set<std::string> directlyUsedFunctionNames;
               CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), directlyUsedFunctionNames);
               std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(directlyUsedFunctionNames, CCopasiRootContainer::getFunctionList());
 # if defined _MSC_VER && _MSC_VER < 1201 // 1200 Identifies Visual C++ 6.0
               {
                 it = usedFunctions.begin();
                 usedFunctions.end();
                 for (; it != end; ++it)
                   this->mUsedFunctions.insert(*it);
               }
 #else
               this->mUsedFunctions.insert(usedFunctions.begin(), usedFunctions.end());
 #endif
             }
           else
             {
               this->mIncompatibilities.insert(this->mIncompatibilities.end(), result.begin(), result.end());
               if (!this->mIncompleteExport)
                 {
                   this->outputIncompatibilities();
                   CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, std::string("event assignment for variable with id \"" + sbmlId + "\"").c_str(), "event", event.getObjectName().c_str());
                 }
             }
           //const CEvaluationNode* pOrigNode = pExpression->getRoot();
           const std::string& changedExpression = convertExpression(pExpression->getInfix(), mInitialValueMap);
           CEvaluationTree tree;
           tree.setInfix(changedExpression);
           const CEvaluationNode* pOrigNode = tree.getRoot();
           if (CEvaluationNode::type(pOrigNode->getType()) == CEvaluationNode::INVALID)
             {
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 70, std::string("event assignment for variable with id \"" + sbmlId + "\"").c_str(), "event", event.getObjectName().c_str());
             }
           // the next few lines replace references to species depending on whether
           // it is a reference to an amount or a reference to a concentration.
           // Other factors that influence this replacement are if the model
           // contains variable volumes or if the quantity units are set to CModel::number
           pOrigNode = this->replaceSpeciesReferences(pOrigNode, dataModel);
           assert(pOrigNode != NULL);
           // check if the assignment belongs to an amount species
           // if so, multiply the expression be the volume of the compartment that
           // the species belongs to.
           const CMetab* pMetab = dynamic_cast<const CMetab*>(pObject);
           if (pMetab != NULL)
             {
               std::map<const CCopasiObject*, SBase*>::const_iterator pos = this->mCOPASI2SBMLMap.find(pObject);
               assert(pos != this->mCOPASI2SBMLMap.end());
               if (dynamic_cast<const Species*>(pos->second)->getHasOnlySubstanceUnits() == true)
                 {
                   const CCompartment* pCompartment = pMetab->getCompartment();
                   if (pCompartment->getDimensionality() != 0)
                     {
                       CEvaluationNode* pNode = CSBMLExporter::multiplyByObject(pOrigNode, pCompartment->getValueReference());
                       assert(pNode != NULL);
                       if (pNode != NULL)
{
                           delete pOrigNode;
                           pOrigNode = pNode;
                         }
                     }
                 }
             }
           ASTNode* pNode = this->convertToASTNode(pOrigNode, dataModel);
           delete pOrigNode;
           // convert local parameters that are referenced in an expression to global
           // parameters
           this->replace_local_parameters(pNode, dataModel);
           if (pNode != NULL)
             {
               pAssignment->setMath(pNode);
               delete pNode;
             }
           else
             {
               if (this->mIncompleteExport != true)
                 {
                   CCopasiMessage(CCopasiMessage::EXCEPTION, MCSBML + 60, std::string("event assignment for variable with id \"" + sbmlId + "\"").c_str(), "event", event.getObjectName().c_str());
                 }
             }
         }
       else
         {
           // create an error message that the event assignment could not be
           // created and continue
           CCopasiMessage(CCopasiMessage::WARNING, MCSBML + 73, std::string("event assignment for variable with id \"" + sbmlId + "\"").c_str(), "event assignment");
           continue;
         }
     }
   //    v) delete the old unused assignments
   std::map<std::string, EventAssignment*>::iterator it = assignmentMap.begin(), endit = assignmentMap.end();
   while (it != endit)
     {
       delete it->second;
       ++it;
     }
 }
bool CSBMLExporter::exportModel (CCopasiDataModel & dataModel, const std::string & filename, unsigned int sbmlLevel = 2, unsigned int sbmlVersion = 1, bool overwrite = false)
Export the model to SBML. The model is written to the file given by filename. If the export fails, false is returned.
Definition at line 3718 of file CSBMLExporter.cpp.
References CCopasiMessage::ERROR, exportModelToString(), CLocaleString::fromUtf8(), and MCDirEntry.
Referenced by CCopasiDataModel::exportSBML().
 {
   bool success = true;
   /* create a string that represents the SBMLDocument */
   std::string str = this->exportModelToString(dataModel, sbmlLevel, sbmlVersion);
   if (!str.empty())
     {
       /* check if the file already exists.
          If yes, write if overwrite is true,
          else create an appropriate  CCopasiMessage. */
       std::ifstream testInfile(CLocaleString::fromUtf8(filename).c_str(), std::ios::in);
       if (testInfile && !overwrite)
         {
           // create a CCopasiMessage with the appropriate error
           CCopasiMessage(CCopasiMessage::ERROR, MCDirEntry + 1, filename.c_str());
           return false;
         }
       /* write the document to a file */
       std::ofstream outfile(CLocaleString::fromUtf8(filename).c_str(), std::ios::out | std::ios::trunc);
       outfile << str;
       outfile.close();
     }
   else
     {
       /* if no SBMLDocument could be created return false */
       success = false;
     }
   return success;
 }
const std::string CSBMLExporter::exportModelToString (CCopasiDataModel & dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion)
Export the model to SBML. The SBML model is returned as a string. In case of an error, an empty string is returned.
Definition at line 3241 of file CSBMLExporter.cpp.
References convert_to_l1v1(), createSBMLDocument(), CSBMLunitInterface::determineUnits(), CListOfLayouts::exportToSBML(), getDefaultStyle(), CCopasiDataModel::getListOfLayouts(), getNumDefaultStyles(), mCOPASI2SBMLMap, mHandledSBMLObjects, mIdMap, mpSBMLDocument, mSBMLLevel, mSBMLVersion, pdelete, removeStickyTagFromElements(), removeUnusedObjects(), CSBMLunitInterface::setAssumeDimensionlessOne(), CLGlobalRenderInformation::toSBML(), and CVersion::VERSION.
Referenced by exportModel(), and CCopasiDataModel::exportSBMLToString().
 {
   this->mSBMLLevel = sbmlLevel;
   this->mSBMLVersion = sbmlVersion;
   mHandledSBMLObjects.clear();
   createSBMLDocument(dataModel);
   if (this->mpSBMLDocument && this->mpSBMLDocument->getModel())
     {
       LayoutModelPlugin* lmPlugin = static_cast<LayoutModelPlugin*>(this->mpSBMLDocument->getModel()->getPlugin("layout"));
       if (lmPlugin != NULL && sbmlLevel > 1)
         {
           // the layout can only be exported for Level 2 or Level 3
           dataModel.getListOfLayouts()->exportToSBML(lmPlugin->getListOfLayouts(),
               this->mCOPASI2SBMLMap, mIdMap, this->mpSBMLDocument->getLevel(), this->mpSBMLDocument->getVersion());
 #if LIBSBML_VERSION >= 50400
           // also ensure ther is one global render information object
           if (lmPlugin->getNumLayouts() > 0 && getNumDefaultStyles() > 0)
             {
               RenderListOfLayoutsPlugin* plugin = static_cast<RenderListOfLayoutsPlugin *>(lmPlugin->getListOfLayouts()->getPlugin("render"));
               if (plugin != NULL)
                 {
                   if (plugin->getNumGlobalRenderInformationObjects() == 0)
                     {
                       GlobalRenderInformation* info = plugin->createGlobalRenderInformation();
                       getDefaultStyle(0)->toSBML(info, this->mpSBMLDocument->getLevel(), this->mpSBMLDocument->getVersion());
                     }
                 }
             }
 #endif // LIBSBML_VERSION >= 50400
         }
     }
 #ifdef USE_SBMLUNIT
   if (this->mpSBMLDocument != NULL)
     {
       CSBMLunitInterface uif(this->mpSBMLDocument->getModel(), true);
       uif.determineUnits();
       // check if there were conflicts
       if (uif.getStatistics().all[5] == 0)
         {
           // check if there are unresolved parameter units left
           if ((uif.getStatistics().local[0] != 0 || uif.getStatistics().global[0] != 0) && uif.getStatistics().numbers[0] != 0)
             {
               // try with heuristics
               CSBMLunitInterface uif2(this->mpSBMLDocument->getModel(), true);
               uif2.setAssumeDimensionlessOne(true);
               uif2.determineUnits();
               // check again if there have been conflicts
               if (uif2.getStatistics().all[5] == 0)
                 {
                   // done use result from uif2
                   // there were no conflicts, so we write the units that could be determined
                   uif2.writeBackToModel();
                   std::cerr << "undetermined: " << uif2.getStatistics().global[0] +  uif2.getStatistics().local[0] << std::endl;
                 }
               else
                 {
                   // TODO create appropriate warning
                   std::cerr << "Warning. " << uif2.getStatistics().all[5] << " conflicts found." << std::endl;
                 }
             }
           else
             {
               // no conflicts, so we can write the parameters that could be determined to the model
               uif.writeBackToModel();
               std::cerr << "undetermined: " << uif.getStatistics().global[0] +  uif.getStatistics().local[0] << std::endl;
             }
         }
       else
         {
           // TODO create a warning
           std::cerr << "Warning. " << uif.getStatistics().all[5] << " conflicts found." << std::endl;
         }
     }
 #endif // USE_SBMLUNIT
   // export the model to a string
   if (this->mpSBMLDocument == NULL) return std::string();
   removeUnusedObjects();
   SBMLWriter* writer = new SBMLWriter();
   writer->setProgramName("COPASI");
   writer->setProgramVersion(CVersion::VERSION.getVersion().c_str());
   char* d = writer->writeToString(this->mpSBMLDocument);
   std::string returnValue = d;
   if (d) free(d);
   pdelete(writer);
   // mark some temporary objects as no longer needed
   removeStickyTagFromElements(mpSBMLDocument);
   // the workaround is no longer necessary, as the libSBML > 5.11.4 will include
   // a converter that not only converts to l1v1 but also inlines the compartment
   // sizes and changes pow implementation as needed by Gepasi
 #if LIBSBML_VERSION <= 51104
   // actually most of the work seems to be done by
   // libsbml already, so the following method doesn't have to
   // do much and most of the code is obsolete, at least for now
   if (sbmlLevel == 1 && sbmlVersion == 1)
     {
       // if there is an exception in the routine, we hand it up to the calling routine
       convert_to_l1v1(returnValue);
     }
 #endif
   return returnValue;
 }
void CSBMLExporter::findAvogadro (const CCopasiDataModel & dataModel) protected
Try to find a global parameter that represents avogadros number.
Definition at line 6335 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModelEntity::FIXED, CCopasiDataModel::getModel(), CModel::getModelValues(), CModel::getQuantity2NumberFactor(), and mpAvogadro.
Referenced by createSBMLDocument().
 {
   double factor = dataModel.getModel()->getQuantity2NumberFactor();
   CCopasiVectorN<CModelValue>::const_iterator it = dataModel.getModel()->getModelValues().begin(), endit = dataModel.getModel()->getModelValues().end();
   while (it != endit)
     {
       if ((*it)->getStatus() == CModelEntity::FIXED)
         {
           double value = (*it)->getInitialValue();
           if (fabs((factor - value) / factor) <= 1e-3)
             {
               this->mpAvogadro = *it;
             }
         }
       ++it;
     }
 }
void CSBMLExporter::findDirectlyUsedFunctions (const CEvaluationNode * pRootNode, std::set< std::string > & result) static protected
Go through a CEvaluationNode base tree and add the names of all functions directly called in this tree to the set.
Definition at line 4927 of file CSBMLExporter.cpp.
References CEvaluationNode::CALL, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), and CEvaluationNode::type().
Referenced by checkForPiecewiseFunctions(), createEvent(), createInitialAssignment(), createRule(), exportEventAssignments(), findUsedFunctions(), isEventAssignmentSBMLCompatible(), isEventSBMLCompatible(), and isModelSBMLCompatible().
 {
   if (pRootNode == NULL) return;
   if (CEvaluationNode::type(pRootNode->getType()) == CEvaluationNode::CALL)
     {
       result.insert(pRootNode->getData());
     }
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pRootNode->getChild());
   while (pChild != NULL)
     {
       CSBMLExporter::findDirectlyUsedFunctions(pChild, result);
       pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
     }
 }
void CSBMLExporter::findModelEntityDependencies (const CEvaluationNode * pNode, const CCopasiDataModel & dataModel, std::set< const CModelEntity * > & dependencies) static protected
Find all ModelEntities for which the given node and its children contains references.
Definition at line 5188 of file CSBMLExporter.cpp.
References fatalError, CCopasiNode< _Data >::getChild(), CCopasiDataModel::getDataObject(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectParent(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), CCopasiObject::isReference(), CEvaluationNode::OBJECT, and CEvaluationNode::type().
Referenced by orderRules().
 {
   if (pNode == NULL) return;
   if (CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT)
     {
       const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
       assert(pObjectNode != NULL);
       if (pObjectNode != NULL)
         {
           const CCopasiObject* pObject = dataModel.getDataObject(pObjectNode->getObjectCN());
           if (!pObject)
             {
               fatalError();
             }
           if (pObject->isReference())
             {
               pObject = pObject->getObjectParent();
               assert(pObject != NULL);
             }
           const CModelEntity* pME = dynamic_cast<const CModelEntity*>(pObject);
           if (pME != NULL)
             {
               dependencies.insert(pME);
             }
         }
     }
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   while (pChild != NULL)
     {
       CSBMLExporter::findModelEntityDependencies(pChild, dataModel, dependencies);
       pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
     }
 }
const std::vector< CFunction * > CSBMLExporter::findUsedFunctions (std::set< CFunction * > & functions, CFunctionDB * pFunctionDB) static protected
Takes a set of functions and recursively finds functions used by those functions
Definition at line 4945 of file CSBMLExporter.cpp.
References createFunctionSetFromFunctionNames(), CCopasiMessage::EXCEPTION, and findDirectlyUsedFunctions().
Referenced by checkForPiecewiseFunctions(), and createFunctionDefinitions().
 {
   std::map<CFunction*, std::set<CFunction*> > functionDependencyMap;
   std::set<CFunction*>::iterator setit = functions.begin(), setendit = functions.end();
   // create the dependency map
   while (setit != setendit)
     {
       std::set<std::string> usedFunctionNames;
       CSBMLExporter::findDirectlyUsedFunctions(const_cast<CFunction*>(*setit)->getRoot(), usedFunctionNames);
       std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(usedFunctionNames, pFunctionDB);
       functionDependencyMap[*setit] = usedFunctions;
       ++setit;
     }
   bool found = true;
   while (found)
     {
       found = false;
       std::map<CFunction*, std::set<CFunction*> >::iterator mapIt = functionDependencyMap.begin(), mapEndit = functionDependencyMap.end();
       while (mapIt != mapEndit)
         {
           setit = mapIt->second.begin(), setendit = mapIt->second.end();
           while (setit != setendit)
             {
               // check if we already have the dependencies for the function
               if (functionDependencyMap.find(*setit) == functionDependencyMap.end())
                 {
                   found = true;
                   std::set<std::string> usedFunctionNames;
                   CSBMLExporter::findDirectlyUsedFunctions(const_cast<CFunction*>(*setit)->getRoot(), usedFunctionNames);
                   std::set<CFunction*> usedFunctions = CSBMLExporter::createFunctionSetFromFunctionNames(usedFunctionNames, pFunctionDB);
                   functionDependencyMap[*setit] = usedFunctions;
                 }
               ++setit;
             }
           // if we changed the map, we have to stop the inner loop since the
           // map iterator is now invalid
           if (found)
             {
               break;
             }
           ++mapIt;
         }
     }
   bool removed = true;
   std::vector<CFunction*> functionVector;
   while (!functionDependencyMap.empty() && removed == true)
     {
       std::map<CFunction*, std::set<CFunction*> >::iterator mapIt = functionDependencyMap.begin(), mapEndit = functionDependencyMap.end();
       removed = false;
       // go through the map and find functions that have no dependencies
       while (mapIt != mapEndit)
         {
           if (mapIt->second.empty())
             {
               // set remove to true so that we know that at least one
               // function definition without dependencies has been found
               // otherwise we might end up in an endless loop
               removed = true;
               // add the function to the front
               functionVector.push_back(mapIt->first);
               // remove this function from the dependency list of all other
               // functions
               std::map<CFunction*, std::set<CFunction*> >::iterator mapIt2 = functionDependencyMap.begin(), mapEndit2 = functionDependencyMap.end();
               while (mapIt2 != mapEndit2)
                 {
                   std::set<CFunction*>::iterator pos = mapIt2->second.find(mapIt->first);
                   if (pos != mapIt2->second.end())
                     {
                       mapIt2->second.erase(pos);
                     }
                   ++mapIt2;
                 }
               // delete the entry of this function from the depenency map
               std::map<CFunction*, std::set<CFunction*> >::iterator pos = mapIt;
               ++mapIt;
               functionDependencyMap.erase(pos);
             }
           else
             {
               ++mapIt;
             }
         }
     }
   // check if the dependency map is empty. If not, there must be a dependency
   // loop
   if (!functionDependencyMap.empty())
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, "Dependency loop found in function definitions.");
     }
   return functionVector;
 }
const std::map< const CCopasiObject *, SBase * > & CSBMLExporter::getCOPASI2SBMLMap () const
Returns a const pointer to the COPASI2SBMLMap.
Definition at line 7186 of file CSBMLExporter.cpp.
References mCOPASI2SBMLMap.
Referenced by CCopasiDataModel::exportSBML(), and CCopasiDataModel::exportSBMLToString().
 {
   return this->mCOPASI2SBMLMap;
 }
SBMLDocument* CSBMLExporter::getSBMLDocument () inline
Definition at line 95 of file CSBMLExporter.h.
References mpSBMLDocument.
Referenced by CCopasiDataModel::exportSBML(), and CCopasiDataModel::exportSBMLToString().
 {return this->mpSBMLDocument;};
bool CSBMLExporter::hasVolumeAssignment (const CCopasiDataModel & dataModel) protected
This method goes through all compartments and events and checks if there is an assignment to a volume.
Definition at line 7578 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CKeyFactory::get(), CModel::getCompartments(), CModel::getEvents(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CCopasiObject::getObjectParent(), CCopasiObject::getObjectType(), mpSBMLDocument, mSBMLLevel, mSBMLVersion, and CModelEntity::ODE.
Referenced by createSBMLDocument().
 {
   bool result = false;
   // make sure the SBML Document already exists and that it has a Model set
   if (dataModel.getModel() == NULL || this->mpSBMLDocument == NULL || this->mpSBMLDocument->getModel() == NULL) return false;
   CCopasiVectorNS<CCompartment>::const_iterator it = dataModel.getModel()->getCompartments().begin(), endit = dataModel.getModel()->getCompartments().end();
   CModelEntity::Status status;
   while (it != endit && result == false)
     {
       status = (*it)->getStatus();
       if (status == CModelEntity::ASSIGNMENT || status == CModelEntity::ODE)
         {
           result = true;
         }
       if ((*it)->getInitialExpression() != "" && result == false)
         {
           if (this->mSBMLLevel > 2 || (this->mSBMLLevel == 2 && this->mSBMLVersion >= 2))
             {
               result = true;
             }
         }
       ++it;
     }
   CCopasiVectorN<CEvent>::const_iterator eit = dataModel.getModel()->getEvents().begin(), eendit = dataModel.getModel()->getEvents().end();
   std::string key;
   const CCopasiObject* pObject = NULL;
   std::string objectType;
   while (eit != eendit && result == false)
     {
       CCopasiVectorN< CEventAssignment >::const_iterator itAssignment = (*eit)->getAssignments().begin();
       CCopasiVectorN< CEventAssignment >::const_iterator endAssignment = (*eit)->getAssignments().end();
       while (itAssignment != endAssignment && result == false)
         {
           key = (*itAssignment)->getTargetKey();
           //        now we have to get the object for the key, check if the object is a
           //        compartment, species or global parameter,
           pObject = CCopasiRootContainer::getKeyFactory()->get(key);
           assert(pObject != NULL);
           objectType = pObject->getObjectType();
           if (objectType == "Reference")
             {
               pObject = pObject->getObjectParent();
               assert(pObject != NULL);
               objectType = pObject->getObjectType();
             }
           if (objectType == "Compartment")
             {
               result = true;
             }
           ++itAssignment;
         }
       ++eit;
     }
   return result;
 }
ASTNode * CSBMLExporter::isDividedByVolume (const ASTNode * pRootNode, const std::string & compartmentId) static protected
checks if the given ASTNode based tree is divided by the volume of the compartment identified by the given id string.
Definition at line 4738 of file CSBMLExporter.cpp.
References pResult.
Referenced by createKineticLaw().
 {
   ASTNode* pResult = NULL;
   if (pRootNode->getType() == AST_DIVIDE || pRootNode->getType() == AST_TIMES)
     {
       ASTNode* pTmpResultNode = new ConverterASTNode(pRootNode->getType());
       unsigned int i, iMax = pRootNode->getNumChildren();
       bool found = false;
       for (i = 0; i < iMax; ++i)
         {
           const ASTNode* pChild = pRootNode->getChild(i);
           if (pRootNode->getType() == AST_DIVIDE && pChild->getType() == AST_NAME && pChild->getName() == compartmentId)
             {
               found = true;
             }
           else if ((!found) && (pChild->getType() == AST_DIVIDE || pChild->getType() == AST_TIMES))
             {
               ASTNode* pSubResult = CSBMLExporter::isDividedByVolume(pChild, compartmentId);
               if (pSubResult != NULL)
                 {
                   found = true;
                   if (pSubResult->getNumChildren() > 1)
                     {
                       pTmpResultNode->addChild(pSubResult);
                     }
                   else if (pSubResult->getNumChildren() == 1)
                     {
                       pTmpResultNode->addChild(static_cast<ASTNode*>(static_cast<ConverterASTNode*>(pSubResult)->removeChild(0)));
                       delete pSubResult;
                     }
                   else
                     {
                       delete pSubResult;
                     }
                 }
               else
                 {
                   pTmpResultNode->addChild(new ConverterASTNode(*pChild));
                 }
             }
           else
             {
               pTmpResultNode->addChild(new ConverterASTNode(*pChild));
             }
         }
       if (found)
         {
           pResult = pTmpResultNode;
         }
       else
         {
           delete pTmpResultNode;
         }
     }
   return pResult;
 }
void CSBMLExporter::isEventAssignmentSBMLCompatible (std::string & key, const CExpression * pExpression, const CCopasiDataModel & dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, const std::string & eventName, std::vector< SBMLIncompatibility > & result) static protected
This method checks if the given event assignment object is SBML compatible.
Definition at line 7264 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, findDirectlyUsedFunctions(), CModelEntity::FIXED, CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CCopasiObject::getObjectType(), CEvaluationTree::getRoot(), CModelEntity::getStatus(), CEvaluationNode::getType(), CEvaluationNode::INVALID, isExpressionSBMLCompatible(), CCopasiMessage::RAW, and CEvaluationNode::type().
Referenced by isEventSBMLCompatible().
 {
   // check if the key points to a compartment, species or global value
   const CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(key);
   assert(pObject != NULL);
   const CModelEntity* pME = dynamic_cast<const CModelEntity*>(pObject);
   if (pME == NULL)
     {
       // create an error message since the object is not a
       // compartment, species or model value
     }
   else
     {
       std::string objectType = pME->getObjectType();
       if (objectType != "Compartment" && objectType != "Metabolite" && objectType != "ModelValue")
         {
           // create an error message since the object is not a
           // compartment, species or model value
           result.push_back(SBMLIncompatibility(9, pObject->getObjectName().c_str(), std::string("event called \"" + eventName + "\"").c_str()));
         }
       else
         {
           // make sure the component that is assigned to is not constant
           if (pME->getStatus() == CModelEntity::FIXED)
             {
               // create an nerror message since the entity may not be
               // constant
               // This is a raw message since I do expect COPASI to have the same
               // restriction as SBML, so this should never happen
               CCopasiMessage(CCopasiMessage::RAW, std::string("Error. Event assignment to constant object named \"" + pObject->getObjectName() + "\" in event named \"" + eventName + "\".").c_str());
             }
           // make sure there is no assignment rule for the variable
           else if (pME->getStatus() == CModelEntity::ASSIGNMENT)
             {
               // create an nerror message since the entity may not be
               // determined by an assignment
               // This is a raw message since I do expect COPASI to have the same
               // restriction as SBML, so this should never happen
               CCopasiMessage(CCopasiMessage::RAW, std::string("Error. Event assignment to object called \"" + pObject->getObjectName() + "\" in event named \"" + eventName + "\", which is determined by an assignment rule.").c_str());
             }
           // check if the expression only references allowed model entities
           if (pExpression != NULL && CEvaluationNode::type(pExpression->getRoot()->getType()) != CEvaluationNode::INVALID)
             {
               std::set<std::string> usedFunctionNames;
               CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("assignment expression for variable named \"" + pObject->getObjectName() + "\" in event named \"" + eventName + "\"").c_str());
               CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
             }
           else
             {
               // This is a raw message since I do expect COPASI to always have
               // an assignment expression
               CCopasiMessage(CCopasiMessage::RAW, std::string("Error. No expression set for event assignment to object called \"" + pObject->getObjectName() + "\" in event named \"" + eventName + "\".").c_str());
             }
         }
     }
 }
void CSBMLExporter::isEventSBMLCompatible (const CEvent * pEvent, const CCopasiDataModel & dataModel, unsigned int sbmlLevel, unsigned int sbmlVersion, std::vector< SBMLIncompatibility > & result) static protected
This method checks if the given event object is SBML compatible.
Definition at line 7201 of file CSBMLExporter.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), findDirectlyUsedFunctions(), CKeyFactory::get(), CEvent::getAssignments(), CEvent::getDelayExpressionPtr(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CEvaluationTree::getRoot(), CEvent::getTriggerExpressionPtr(), isEventAssignmentSBMLCompatible(), isExpressionSBMLCompatible(), and CCopasiMessage::RAW.
Referenced by isModelSBMLCompatible().
 {
   if (pEvent == NULL) return;
   // check if the trigger and the delay expression only reference allowed
   // model entities
   // make sure no two event assignments assign to the same variable
   std::set<std::string> usedFunctionNames;
   const CExpression* pExpression = pEvent->getTriggerExpressionPtr();
   if (pExpression != NULL)
     {
       // check for unsupported object references and unsupported function
       // calls
       CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("trigger expression for event named \"" + pEvent->getObjectName() + "\"").c_str());
       usedFunctionNames.clear();
       CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
     }
   pExpression = pEvent->getDelayExpressionPtr();
   if (pExpression != NULL)
     {
       // check for unsupported object references and unsupported function
       // calls
       CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("delay expression for event named \"" + pEvent->getObjectName() + "\"").c_str());
       usedFunctionNames.clear();
       CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
     }
   std::set<std::string> objectKeys;
   std::set<std::string> nonUniqueObjectKeys;
   CCopasiVectorN< CEventAssignment >::const_iterator itAssignment = pEvent->getAssignments().begin();
   CCopasiVectorN< CEventAssignment >::const_iterator endAssignment = pEvent->getAssignments().end();
   for (; itAssignment != endAssignment; ++itAssignment)
     {
       std::string key = (*itAssignment)->getTargetKey();
       if (objectKeys.find(key) == objectKeys.end())
         {
           objectKeys.insert(key);
         }
       else
         {
           // This should never happen since I assume that COPASI will have
           // the same restriction as SBML with respect to unique assignments
           // within an event
           if (nonUniqueObjectKeys.find(key) == nonUniqueObjectKeys.end())
             {
               nonUniqueObjectKeys.insert(key);
               const CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(key);
               assert(pObject != NULL);
               CCopasiMessage(CCopasiMessage::RAW, std::string("Error. Event called \"" + pEvent->getObjectName() + "\" has several assignments to the same object called \"" + pObject->getObjectName() + "\".").c_str());
             }
         }
       CSBMLExporter::isEventAssignmentSBMLCompatible(key, (*itAssignment)->getExpressionPtr(),
           dataModel, sbmlLevel, sbmlVersion, pEvent->getObjectName(), result);
     }
 }
void CSBMLExporter::isExpressionSBMLCompatible (const CEvaluationTree & expr, const CCopasiDataModel & dataModel, int sbmlLevel, int sbmlVersion, std::vector< SBMLIncompatibility > & result, const std::string & objectDescription, bool initialExpression = false, std::map< const std::string, Parameter * > * initialMap = NULL) static protected
Checks wether the rule in the given model entity can be exported to the specified version of SBML. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Checks whether the rule in the given model entity can be exported to the specified version of SBML. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Definition at line 2767 of file CSBMLExporter.cpp.
References checkForUnsupportedFunctionCalls(), checkForUnsupportedObjectReferences(), createUnsupportedFunctionTypeSet(), and CEvaluationTree::getRoot().
Referenced by createEvent(), createFunctionDefinition(), createInitialAssignment(), createRule(), exportEventAssignments(), isEventAssignmentSBMLCompatible(), isEventSBMLCompatible(), and isModelSBMLCompatible().
 {
   checkForUnsupportedObjectReferences(expr, dataModel, sbmlLevel, sbmlVersion, result, initialExpression, initialMap);
   std::set<CEvaluationNodeFunction::SubType> unsupportedFunctionTypes = CSBMLExporter::createUnsupportedFunctionTypeSet(sbmlLevel);
   checkForUnsupportedFunctionCalls(*expr.getRoot(), unsupportedFunctionTypes, result, objectDescription);
 }
static void CSBMLExporter::isExpressionSBMLL1Compatible (const CEvaluationTree & expr, const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks wether the rule in the given model entity can be exported to SBML Level2 Version1. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
static void CSBMLExporter::isExpressionSBMLL2V1Compatible (const CEvaluationTree & expr, const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks wether the rule in the given model entity can be exported to SBML Level2 Version1. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
static void CSBMLExporter::isExpressionSBMLL2V3Compatible (const CEvaluationTree & expression, const CCopasiDataModel & pDataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks wether the rule in the given model entity can be exported to SBML Level2 Version3. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
const std::vector< SBMLIncompatibility > CSBMLExporter::isModelSBMLCompatible (const CCopasiDataModel & dataModel, int sbmlLevel, int sbmlVersion) static
Checks wether the given data model can be exported to a certain version of SBML. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Checks whether the given data model can be exported to a certain version of SBML. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Definition at line 3757 of file CSBMLExporter.cpp.
References CModelEntity::ASSIGNMENT, CCopasiVector< T >::begin(), checkForODESpeciesInNonfixedCompartment(), CCopasiVector< T >::end(), findDirectlyUsedFunctions(), CModel::getCompartments(), CModel::getEvents(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CModel::getModelValues(), CEvaluationTree::getRoot(), isEventSBMLCompatible(), isExpressionSBMLCompatible(), isModelSBMLL1Compatible(), isModelSBMLL2V1Compatible(), isModelSBMLL2V3Compatible(), and CModelEntity::ODE.
 {
   const CModel* pModel = dataModel.getModel();
   std::vector<SBMLIncompatibility> result;
   if (pModel == NULL) return result;
   // general checks
   // check if there is a species with an ode rule that is in a nonfixed
   // compartment
   checkForODESpeciesInNonfixedCompartment(dataModel, result);
   // check if the model contains references to model entities that can not be
   // represented in SBML like the initial value of something as opposed to the
   // transient value
   // check if the model contains calls to functions that are not supported in
   // the given version of SBML
   CModelEntity::Status status;
   const CExpression* pExpression = NULL;
   std::set<std::string> usedFunctionNames;
   CCopasiVectorNS<CCompartment>::const_iterator compIt = pModel->getCompartments().begin();
   CCopasiVectorNS<CCompartment>::const_iterator compEndit = pModel->getCompartments().end();
   while (compIt != compEndit)
     {
       status = (*compIt)->getStatus();
       if (status == CModelEntity::ODE || status == CModelEntity::ASSIGNMENT)
         {
           pExpression = (*compIt)->getExpressionPtr();
           assert(pExpression != NULL);
           if (pExpression != NULL)
             {
               // check for unsupported object references and unsupported function
               // calls
               usedFunctionNames.clear();
               CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("compartment with name \"" + (*compIt)->getObjectName() + "\"").c_str());
               CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
             }
         }
       pExpression = (*compIt)->getInitialExpressionPtr();
       if (pExpression != NULL)
         {
           // check for unsupported object references and unsupported function
           // calls
           CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("initial expression for compartment named \"" + (*compIt)->getObjectName() + "\"").c_str());
           usedFunctionNames.clear();
           CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
         }
       ++compIt;
     }
   CCopasiVector<CMetab>::const_iterator metabIt = pModel->getMetabolites().begin();
   CCopasiVector<CMetab>::const_iterator metabEndit = pModel->getMetabolites().end();
   while (metabIt != metabEndit)
     {
       status = (*metabIt)->getStatus();
       if (status == CModelEntity::ODE || status == CModelEntity::ASSIGNMENT)
         {
           pExpression = (*metabIt)->getExpressionPtr();
           assert(pExpression != NULL);
           if (pExpression != NULL)
             {
               // check for unsupported object references and unsupported function
               // calls
               CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("rule for species named \"" + (*metabIt)->getObjectName() + "\"").c_str());
               usedFunctionNames.clear();
               CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
             }
         }
       pExpression = (*metabIt)->getInitialExpressionPtr();
       if (pExpression != NULL)
         {
           // check for unsupported object references and unsupported function
           // calls
           CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("initial species for metabolite named \"" + (*metabIt)->getObjectName() + "\"").c_str());
           usedFunctionNames.clear();
           CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
         }
       ++metabIt;
     }
   CCopasiVectorN<CModelValue>::const_iterator mvIt = pModel->getModelValues().begin();
   CCopasiVectorN<CModelValue>::const_iterator mvEndit = pModel->getModelValues().end();
   while (mvIt != mvEndit)
     {
       status = (*mvIt)->getStatus();
       if (status == CModelEntity::ODE || status == CModelEntity::ASSIGNMENT)
         {
           pExpression = (*mvIt)->getExpressionPtr();
           assert(pExpression != NULL);
           if (pExpression != NULL)
             {
               // check for unsupported object references and unsupported function
               // calls
               CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("rule for global parameter named \"" + (*mvIt)->getObjectName() + "\"").c_str());
               usedFunctionNames.clear();
               CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
             }
         }
       pExpression = (*mvIt)->getInitialExpressionPtr();
       if (pExpression != NULL)
         {
           // check for unsupported object references and unsupported function
           // calls
           CSBMLExporter::isExpressionSBMLCompatible(*pExpression, dataModel, sbmlLevel, sbmlVersion, result, std::string("initial expression for global parameter named \"" + (*mvIt)->getObjectName() + "\"").c_str());
           usedFunctionNames.clear();
           CSBMLExporter::findDirectlyUsedFunctions(pExpression->getRoot(), usedFunctionNames);
         }
       ++mvIt;
     }
   // since all kinetic laws in COPASI are simple function calls and the
   // arguments to the call can only be parameters or species, the expressions
   // in kinetic laws are always automatically valid for SBML export
   // However the functions that are called must not be valid
   // check all functions that are used if they contain invalid function calls
   // level dependent checks
   CCopasiVectorN<CEvent>::const_iterator eventIt, eventEndit;
   switch (sbmlLevel)
     {
       case 2:
         // check all events
         eventIt = pModel->getEvents().begin();
         eventEndit = pModel->getEvents().end();
         while (eventIt != eventEndit)
           {
             CSBMLExporter::isEventSBMLCompatible(*eventIt, dataModel, sbmlLevel, sbmlVersion, result);
             ++eventIt;
           }
         switch (sbmlVersion)
           {
             case 1:
               CSBMLExporter::isModelSBMLL2V1Compatible(dataModel, result);
               break;
             case 2:
             case 3:
               CSBMLExporter::isModelSBMLL2V3Compatible(dataModel, result);
               break;
             default:
               result.push_back(SBMLIncompatibility(6, sbmlLevel, sbmlVersion));
               break;
           }
         break;
       case 1:
         CSBMLExporter::isModelSBMLL1Compatible(dataModel, result);
         break;
       default:
         result.push_back(SBMLIncompatibility(6, sbmlLevel, sbmlVersion));
         break;
     }
   return result;
 }
void CSBMLExporter::isModelSBMLL1Compatible (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks wether the given data model can be exported to SBML Level1 If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Checks whether the given data model can be exported to SBML Level1 If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Definition at line 2551 of file CSBMLExporter.cpp.
References checkForEvents(), checkForInitialAssignments(), and checkForPiecewiseFunctions().
Referenced by isModelSBMLCompatible().
 {
   // check for piecewise functions
   checkForPiecewiseFunctions(dataModel, result);
   // check for initial assignments
   checkForInitialAssignments(dataModel, result);
   // check for event
   checkForEvents(dataModel, result);
 }
void CSBMLExporter::isModelSBMLL2V1Compatible (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks wether the given data model can be exported to SBML Level2 Version1. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Checks whether the given data model can be exported to SBML Level2 Version1. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Definition at line 2568 of file CSBMLExporter.cpp.
References checkForInitialAssignments().
Referenced by isModelSBMLCompatible().
 {
   // check for initial assignments
   CSBMLExporter::checkForInitialAssignments(dataModel, result);
 }
void CSBMLExporter::isModelSBMLL2V3Compatible (const CCopasiDataModel & dataModel, std::vector< SBMLIncompatibility > & result) static protected
Checks wether the given data model can be exported to SBML Level2 Version3. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Checks whether the given data model can be exported to SBML Level2 Version3. If it can be exported, the result vector will be empty, otherwise it will contain a number of messages that specify why it can't be exported.
Definition at line 2579 of file CSBMLExporter.cpp.
References check_for_spatial_size_units().
Referenced by isModelSBMLCompatible().
 {
   // if there is an SBML model, which means the model was imported from SBML,
   // we have to check for spatial size units on species in the SBML model
   // because those are not allowed in SBMLLl2V3 and above
   check_for_spatial_size_units(dataModel, result);
 }
bool CSBMLExporter::isSetExportCOPASIMIRIAM () const
Returns whether the exporter is supposed to export COPASIs MIRIAM annotation in addition to SBML MIRIAM.
Definition at line 7191 of file CSBMLExporter.cpp.
References mExportCOPASIMIRIAM.
 {
   return this->mExportCOPASIMIRIAM;
 }
bool CSBMLExporter::isValidSId (const std::string & id) static protected
Checks if the given string is a valid SId
Definition at line 5993 of file CSBMLExporter.cpp.
Referenced by createFunctionDefinition(), and setFunctionSBMLIds().
 {
   bool result = true;
   if (id.length() > 0)
     {
       char c = id[0];
       result = (c == '_' || (c > 64 && c < 91) || (c > 96 && c < 123));
       size_t i, iMax = id.length();
       for (i = 1; (i < iMax) && result; ++i)
         {
           c = id[i];
           result = (c == '_' || (c > 64 && c < 91) || (c > 96 && c < 123) || (c > 47 && c < 58));
         }
     }
   else
     {
       result = false;
     }
   return result;
 }
CEvaluationNode * CSBMLExporter::multiplyByObject (const CEvaluationNode * pOrigNode, const CCopasiObject * pObject) static protected
This method multiplies a given expression by the given object. The caller is responsible for freeing the memory for the new expression.
Definition at line 7654 of file CSBMLExporter.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeObject::CN, CEvaluationNode::copyBranch(), CEvaluationNodeOperator::DIVIDE, CCopasiNode< _Data >::getChild(), CCopasiObject::getCN(), CEvaluationNode::getType(), CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::OBJECT, CEvaluationNode::OPERATOR, pResult, CEvaluationNode::subType(), and CEvaluationNode::type().
Referenced by createInitialAssignment(), createRule(), and exportEventAssignments().
 {
   bool reverse = false;
   CEvaluationNode* pResult = NULL;
   assert(pOrigNode != NULL);
   assert(pObject != NULL);
   if (pOrigNode != NULL && pObject != NULL)
     {
       // first we check if this is thie reverse operation with the object
       // if so, we just drop the reverse operation, otherwise we apply the operation with the
       // object
       if (CEvaluationNode::type(pOrigNode->getType()) == CEvaluationNode::OPERATOR &&
           (CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pOrigNode->getType()) == CEvaluationNodeOperator::DIVIDE)
         {
           // only the second child can be the object
           const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pOrigNode->getChild()->getSibling());
           if (CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OBJECT && dynamic_cast<const CEvaluationNodeObject*>(pChild)->getData() == std::string("<" + pObject->getCN() + ">"))
             {
               pResult = dynamic_cast<const CEvaluationNode*>(pOrigNode->getChild())->copyBranch();
               reverse = true;
             }
         }
       if (reverse == false)
         {
           CEvaluationNodeObject* pVolumeNode = new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pObject->getCN() + ">");
           pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
           pResult->addChild(pOrigNode->copyBranch());
           pResult->addChild(pVolumeNode);
         }
     }
   return pResult;
 }
std::vector< CModelEntity * > CSBMLExporter::orderRules (const CCopasiDataModel & dataModel) protected
Sorts the rules.
Definition at line 5084 of file CSBMLExporter.cpp.
References findModelEntityDependencies(), CEvaluationTree::getRoot(), and mAssignmentVector.
Referenced by createRules().
 {
   // make sure the vector of rules is filled
   std::map<CModelEntity*, std::set<const CModelEntity*> > dependencyMap;
   std::vector<CModelEntity*>::iterator it = this->mAssignmentVector.begin(), endit = this->mAssignmentVector.end();
   while (it != endit)
     {
       const CExpression* pExpr = (*it)->getExpressionPtr();
       assert(pExpr != NULL);
       std::set<const CModelEntity*> dependencies;
       CSBMLExporter::findModelEntityDependencies(pExpr->getRoot(), dataModel, dependencies);
       /*
       std::vector<CModelEntity*>::iterator it2 = this->mAssignmentVector.begin(), endit2 = this->mAssignmentVector.end();
       while (it2 != endit2)
         {
           std::set<const CModelEntity*>::iterator pos = dependencies.find(*it2);
           if (pos != dependencies.end())
             {
               dependencies.erase(pos);
             }
           ++it2;
         }
         */
       dependencyMap[*it] = dependencies;
       ++it;
     }
   // now sort the entities according to their dependencies
   bool error = false;
   std::vector<CModelEntity*> orderedRules;
   // remove all dependencies that don't have assignment rules themselves
   std::map<CModelEntity*, std::set<const CModelEntity*> > reducedDependencyMap;
   std::map<CModelEntity*, std::set<const CModelEntity*> >::iterator mapIt = dependencyMap.begin(), mapEndit = dependencyMap.end();
   while (mapIt != mapEndit)
     {
       std::set<const CModelEntity*> dependencies;
       std::set<const CModelEntity*>::const_iterator setIt = mapIt->second.begin(), setEndit = mapIt->second.end();
       while (setIt != setEndit)
         {
           if (dependencyMap.find(const_cast<CModelEntity*>(*setIt)) != dependencyMap.end())
             {
               dependencies.insert(*setIt);
             }
           ++setIt;
         }
       reducedDependencyMap[mapIt->first] = dependencies;
       ++mapIt;
     }
   while (error == false && !reducedDependencyMap.empty())
     {
       mapIt = reducedDependencyMap.begin(), mapEndit = reducedDependencyMap.end();
       // if we cant't remove anything in one round, we have a circular
       // dependency
       error = true;
       while (mapIt != mapEndit)
         {
           // if the dependency list of the item is not empty
           // we remove all entities that have been removed already
           if (!mapIt->second.empty())
             {
               std::vector<CModelEntity*>::iterator vIt = orderedRules.begin(), vEndit = orderedRules.end();
               while (vIt != vEndit)
                 {
                   std::set<const CModelEntity*>::iterator pos = mapIt->second.find(*vIt);
                   if (pos != mapIt->second.end())
                     {
                       mapIt->second.erase(pos);
                     }
                   ++vIt;
                 }
             }
           if (mapIt->second.empty())
             {
               // since the dependencies are empty, we can add the rule to be
               // exported
               orderedRules.push_back(mapIt->first);
               // now we know that we could remove something in this round
               error = false;
               break;
             }
           ++mapIt;
         }
       if (error == false)
         {
           reducedDependencyMap.erase(mapIt);
         }
     }
   return orderedRules;
 }
void CSBMLExporter::outputIncompatibilities () const protected
Creates error messages from the list of incompatibilities and thows an exception.
Definition at line 7160 of file CSBMLExporter.cpp.
References SBMLIncompatibility::getDetails(), SBMLIncompatibility::getMessage(), mIncompatibilities, SBMLIncompatibility::minSBMLLevel(), SBMLIncompatibility::minSBMLVersion(), and CCopasiMessage::RAW.
Referenced by createEvent(), createInitialAssignment(), createRule(), createSBMLDocument(), and exportEventAssignments().
 {
   size_t i, iMax = this->mIncompatibilities.size();
   for (i = 0; i < iMax; ++i)
     {
       const SBMLIncompatibility* pIncompat = &this->mIncompatibilities[i];
       std::ostringstream os;
       os << pIncompat->getMessage() << "\n";
       os << pIncompat->getDetails() << "\n";
       if (pIncompat->minSBMLLevel() != 0 && pIncompat->minSBMLVersion() != 0)
         {
           os << "Please export to SBML Level " << pIncompat->minSBMLLevel();
           os << " Version " << pIncompat->minSBMLVersion() << " or higher.";
         }
       CCopasiMessage(CCopasiMessage::RAW, os.str().c_str());
     }
 }
void CSBMLExporter::removeInitialAssignment (const std::string & sbmlId) protected
Remove the initial assignment for the entity with the given id if there is any.
Definition at line 6021 of file CSBMLExporter.cpp.
References mpSBMLDocument.
Referenced by createCompartment(), createMetabolite(), and createParameter().
 {
   ListOfInitialAssignments* pList = this->mpSBMLDocument->getModel()->getListOfInitialAssignments();
   unsigned int i, iMax = pList->size();
   for (i = 0; i < iMax; ++i)
     {
       InitialAssignment* pIA = dynamic_cast<InitialAssignment*>(pList->get(i));
       if (pIA->getSymbol() == sbmlId)
         {
           pList->remove(i);
           break;
         }
     }
 }
void CSBMLExporter::removeRule (const std::string & sbmlId) protected
Remove the rule for the entity with the given id if there is any.
Definition at line 6042 of file CSBMLExporter.cpp.
References mpSBMLDocument.
Referenced by createCompartment(), createMetabolite(), and createParameter().
 {
   ListOfRules* pList = this->mpSBMLDocument->getModel()->getListOfRules();
   unsigned int i, iMax = pList->size();
   for (i = 0; i < iMax; ++i)
     {
       Rule* pR = dynamic_cast<Rule*>(pList->get(i));
       if (pR->getVariable() == sbmlId)
         {
           pList->remove(i);
           break;
         }
     }
 }
void CSBMLExporter::removeUnusedObjects () protected
Remove all compartments, species, parameters and reactions that did not end up in mHandledSBMLObjects during an export.
Remove all compartments, species, parameters and reactions and initial assignments that did not end up in mHandledSBMLObjects during an export.
Definition at line 5646 of file CSBMLExporter.cpp.
References mCOPASI2SBMLMap, mHandledSBMLObjects, and mpSBMLDocument.
Referenced by exportModelToString().
 {
   if (this->mpSBMLDocument != NULL || this->mpSBMLDocument->getModel() == NULL)
     {
       // we need to reverse the COPASI2SBMLMap so that we can remove objects
       // from the map if we delete them
       std::map<const SBase*, const CCopasiObject*> reverseCOPASI2SBMLMap;
       std::map<const CCopasiObject*, SBase*>::const_iterator it = this->mCOPASI2SBMLMap.begin(), endit = this->mCOPASI2SBMLMap.end();
       while (it != endit)
         {
           reverseCOPASI2SBMLMap.insert(std::pair<const SBase*, const CCopasiObject*>(it->second, it->first));
           ++it;
         }
       Model* pModel = this->mpSBMLDocument->getModel();
       std::list<SBase*> removedObjects;
       SBase* pSBase = NULL;
       ListOf* pList = pModel->getListOfCompartments();
       unsigned int i;
       std::map<const SBase*, const CCopasiObject*>::const_iterator pos;
       std::map<const CCopasiObject*, SBase*>::iterator pos2;
       for (i = pList->size(); i != 0; --i)
         {
           pSBase = pList->get(i - 1);
           if (this->mHandledSBMLObjects.find(pSBase) == this->mHandledSBMLObjects.end())
             {
               removedObjects.push_back(pList->remove(i - 1));
             }
         }
       pList = pModel->getListOfSpecies();
       for (i = pList->size(); i != 0; --i)
         {
           pSBase = pList->get(i - 1);
           if (this->mHandledSBMLObjects.find(pSBase) == this->mHandledSBMLObjects.end())
             {
               removedObjects.push_back(pList->remove(i - 1));
             }
         }
       pList = pModel->getListOfParameters();
       for (i = pList->size(); i != 0; --i)
         {
           pSBase = pList->get(i - 1);
           // skip all specially marked items
           if (pSBase->getUserData() != NULL && strcmp((const char*)pSBase->getUserData(), "1") == 0)
             continue;
           if (this->mHandledSBMLObjects.find(pSBase) == this->mHandledSBMLObjects.end())
             {
               removedObjects.push_back(pList->remove(i - 1));
             }
         }
       pList = pModel->getListOfInitialAssignments();
       for (i = pList->size(); i != 0; --i)
         {
           pSBase = pList->get(i - 1);
           // skip all specially marked items
           if (pSBase->getUserData() != NULL && strcmp((const char*)pSBase->getUserData(), "1") == 0)
             continue;
           if (this->mHandledSBMLObjects.find(pSBase) == this->mHandledSBMLObjects.end())
             {
               // remove the item from the COPASI2SBMLmap
               pos = reverseCOPASI2SBMLMap.find(pSBase);
               if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
                 {
                   pos2 = this->mCOPASI2SBMLMap.find(pos->second);
                   if (pos2 != this->mCOPASI2SBMLMap.end())
                     {
                       this->mCOPASI2SBMLMap.erase(pos2);
                     }
                 }
               // we don't have to store the initial assignments since
               // there are no rules or events for initial assignments
               delete pList->remove(i - 1);
             }
         }
       pList = pModel->getListOfReactions();
       for (i = pList->size(); i != 0; --i)
         {
           pSBase = pList->get(i - 1);
           if (this->mHandledSBMLObjects.find(pSBase) == this->mHandledSBMLObjects.end())
             {
               // remove the item from the COPASI2SBMLmap
               pos = reverseCOPASI2SBMLMap.find(pSBase);
               if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
                 {
                   pos2 = this->mCOPASI2SBMLMap.find(pos->second);
                   if (pos2 != this->mCOPASI2SBMLMap.end())
                     {
                       this->mCOPASI2SBMLMap.erase(pos2);
                     }
                 }
               // we don't have to store the reactions since
               // there are no rules or events for reactions
               delete pList->remove(i - 1);
             }
         }
       // check each removed object, if there is a rule or an event in
       // the SBML model for this object
       std::list<SBase*>::iterator it2 = removedObjects.begin(), endit2 = removedObjects.end();
       pList = pModel->getListOfRules();
       ListOf* pEventList = pModel->getListOfEvents();
       ListOf* pInitialAssignmentList = pModel->getListOfInitialAssignments();
       Rule* pRule = NULL;
       Event* pEvent = NULL;
       InitialAssignment* pIA = NULL;
       unsigned int iMax;
       while (it2 != endit2)
         {
           iMax = pList->size();
           for (i = 0; i < iMax; ++i)
             {
               pRule = dynamic_cast<Rule*>(pList->get(i));
               if (pRule != NULL && pRule->isSetVariable() && pRule->getVariable() == (*it2)->getId())
                 {
                   // remove the item from the COPASI2SBMLmap
                   pos = reverseCOPASI2SBMLMap.find(pRule);
                   if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
                     {
                       pos2 = this->mCOPASI2SBMLMap.find(pos->second);
                       if (pos2 != this->mCOPASI2SBMLMap.end())
{
                           this->mCOPASI2SBMLMap.erase(pos2);
                         }
                     }
                   delete pList->remove(i);
                   break;
                 }
             }
           iMax = pInitialAssignmentList->size();
           for (i = 0; i < iMax; ++i)
             {
               pIA = dynamic_cast<InitialAssignment*>(pInitialAssignmentList->get(i));
               if (pIA->isSetSymbol() && pIA->getSymbol() == (*it2)->getId())
                 {
                   // remove the item from the COPASI2SBMLmap
                   pos = reverseCOPASI2SBMLMap.find(pIA);
                   if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
                     {
                       pos2 = this->mCOPASI2SBMLMap.find(pos->second);
                       if (pos2 != this->mCOPASI2SBMLMap.end())
{
                           this->mCOPASI2SBMLMap.erase(pos2);
                         }
                     }
                   delete pInitialAssignmentList->remove(i);
                   break;
                 }
             }
           iMax = pEventList->size();
           for (i = 0; i < iMax; ++i)
             {
               pEvent = dynamic_cast<Event*>(pEventList->get(i));
               if (pEvent != NULL)
                 {
                   ListOfEventAssignments* pEAL = pEvent->getListOfEventAssignments();
                   EventAssignment* pEA = NULL;
                   unsigned int j, jMax = pEAL->size();
                   for (j = 0; j < jMax; ++j)
                     {
                       pEA = pEvent->getEventAssignment(j);
                       if (pEA != NULL && pEA->getVariable() == (*it2)->getId())
{
                           // remove the item from the COPASI2SBMLmap
                           pos = reverseCOPASI2SBMLMap.find(pEA);
                           if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
{
                               pos2 = this->mCOPASI2SBMLMap.find(pos->second);
                               if (pos2 != this->mCOPASI2SBMLMap.end())
{
                                   this->mCOPASI2SBMLMap.erase(pos2);
                                 }
                             }
                           delete pEAL->remove(j);
                           break;
                         }
                     }
                   // if there are no more event assignments, we can delete the
                   // event
                   if (pEAL->size() == 0)
                     {
                       // remove the item from the COPASI2SBMLmap
                       pos = reverseCOPASI2SBMLMap.find(pEvent);
                       if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
{
                           pos2 = this->mCOPASI2SBMLMap.find(pos->second);
                           if (pos2 != this->mCOPASI2SBMLMap.end())
{
                               this->mCOPASI2SBMLMap.erase(pos2);
                             }
                         }
                       delete pEventList->remove(i);
                     }
                 }
             }
           // remove the item from the COPASI2SBMLmap
           pos = reverseCOPASI2SBMLMap.find(*it2);
           if (pos != reverseCOPASI2SBMLMap.end() && pos->second != NULL)
             {
               pos2 = this->mCOPASI2SBMLMap.find(pos->second);
               if (pos2 != this->mCOPASI2SBMLMap.end())
                 {
                   this->mCOPASI2SBMLMap.erase(pos2);
                 }
             }
           delete *it2;
           ++it2;
         }
     }
 }
void CSBMLExporter::replace_local_parameters (ASTNode * pOrigNode, const CCopasiDataModel & dataModel) protected
Goes through the expression tree and tries to find occurences of local parameters. If one is found, a global parameter is created and all references to the local parameters are substituted.
Definition at line 7330 of file CSBMLExporter.cpp.
References createUniqueId(), CCopasiParameter::getCN(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiParameter::getValue(), mHandledSBMLObjects, mIdMap, mParameterReplacementMap, mpSBMLDocument, CCopasiDataModel::ObjectFromName(), and CCopasiParameter::Value::pDOUBLE.
Referenced by createEvent(), createInitialAssignment(), createRule(), and exportEventAssignments().
 {
   //  go through the expression and check if it contains a local reaction
   //  parameter, if it does, we have to create a global parameter to replace it
   //  the replacement has to be recorded in same data structure so that we can
   //  consider it when the reactions are created later on
   //  In the end, we need to use this map to create a warning message.
   if (pOrigNode != NULL)
     {
       // the new id for the global parameter should contain the reaction name and
       // the parameter name
       if (pOrigNode->getType() == AST_NAME)
         {
           std::string objectName = pOrigNode->getName();
           std::vector<CCopasiContainer*> containers;
           containers.push_back(const_cast<CModel*>(dataModel.getModel()));
           const CCopasiObject* pObject = dataModel.ObjectFromName(containers, objectName);
           if (pObject != NULL)
             {
               const CCopasiParameter* pLocalParameter = dynamic_cast<const CCopasiParameter*>(pObject);
               if (pLocalParameter != NULL)
                 {
                   // it must be a local parameter
                   std::map<std::string, Parameter*>::iterator pos = this->mParameterReplacementMap.find(pLocalParameter->getCN());
                   if (pos == this->mParameterReplacementMap.end())
                     {
                       // not found, so we create a new global parameter
                       const CCopasiObject* pParent = pLocalParameter->getObjectParent();
                       // find the reaction
                       while (pParent != NULL && dynamic_cast<const CReaction*>(pParent) == NULL)
{
                           pParent = pParent->getObjectParent();
                         }
                       assert(pParent);
                       // now we create a new global parameter with a unique name
                       std::string name = pParent->getObjectName() + "_" + pLocalParameter->getObjectName();
                       std::string sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, name, false);
                       Parameter* pParameter = this->mpSBMLDocument->getModel()->createParameter();
                       // don't call setName on level 1 objects because this will also
                       // change the id
                       if (this->mpSBMLDocument->getLevel() > 1)
{
                           pParameter->setName(name);
                         }
                       pParameter->setId(sbmlId);
                       this->mIdMap.insert(std::pair<std::string, SBase*>(sbmlId, pParameter));
                       pParameter->setValue(*pLocalParameter->getValue().pDOUBLE);
                       this->mParameterReplacementMap[pLocalParameter->getCN()] = pParameter;
                       pOrigNode->setName(sbmlId.c_str());
                       this->mHandledSBMLObjects.insert(pParameter);
                     }
                   else
                     {
                       // we set the node name to the existing parameter name
                       pOrigNode->setName(pos->second->getId().c_str());
                     }
                 }
             }
         }
       unsigned int i = 0, iMax = pOrigNode->getNumChildren();
       while (i < iMax)
         {
           this->replace_local_parameters(pOrigNode->getChild(i), dataModel);
           ++i;
         }
     }
 }
XMLNode * CSBMLExporter::replaceChild (const XMLNode * pParent, const XMLNode * pNewChild, unsigned int index) protected
This method creates a copy of parent where the child with the given index is replaced by the new child given as the second argument. If index is greater than the number of children - 1, NULL is returned.
This method creates a copy of parent where the child with the given index is replaced by the new child given as the second argument. If index is greater than the number of children - 1, NULL is returned. If the new child is a null pointer, this method deleted the old node at the given index.
Definition at line 7023 of file CSBMLExporter.cpp.
References pResult.
Referenced by updateMIRIAMAnnotation().
 {
   XMLNode* pResult = NULL;
   if (index < pParent->getNumChildren())
     {
       // make a shallow copy of pParent
       // The copy constructor makes a deep copy, so we have to use the
       // constructor that takes an XMLToken
       pResult = new XMLNode(XMLToken(*pParent));
       unsigned int i, iMax = pParent->getNumChildren();
       for (i = 0; i < iMax; ++i)
         {
           // make a deep copy of each child, but if the index of child is the
           // given index, we add pNewChild instead of making a copy of the
           // current child
           if (i == index && pNewChild != NULL)
             {
               pResult->addChild(*pNewChild);
             }
           else
             {
               pResult->addChild(pParent->getChild(i));
             }
         }
     }
   return pResult;
 }
ASTNode * CSBMLExporter::replaceL1IncompatibleNodes (const ASTNode * pNode) static protected
This method goes through the ASTNode based tree rooted at pNode and replaces all unsupported nodes with constructs supported by SBML Level 1 The caller is responsible for freeing the memory of the returned object.
Definition at line 5298 of file CSBMLExporter.cpp.
References fatalError, max, pResult, replace_ARCCOSH(), replace_ARCCSCH(), replace_ARCSECH(), replace_ARCSINH(), replace_ARCTANH(), replace_COSH(), replace_COT(), replace_COTH(), replace_CSC(), replace_CSCH(), replace_SEC(), replace_SECH(), replace_SINH(), replace_TANH(), and ConverterASTNode::shallowCopy().
Referenced by convertASTTreeToLevel1().
 {
   // replace all inf, pi, nan and exponentiale nodes
   // replace all unsupported functions calls: SEC,CSC, COT, SINH, COSH,
   // TANH, SECH, CSCH, COTH, ARCSINH, ARCCOSH, ARCTANH, ARCSECH, ARCSCSH,
   // ARCCOTH
   if (pNode == NULL) return NULL;
   ASTNode* pResult = NULL;
   ASTNode* pChild = NULL;
   unsigned int i, iMax;
   switch (pNode->getType())
     {
       case AST_FUNCTION_PIECEWISE:
         break;
       case AST_CONSTANT_E:
         // replace by exp(1)
         pResult = new ASTNode(AST_FUNCTION_EXP);
         pChild = new ASTNode(AST_REAL);
         pChild->setValue(1.0);
         pResult->addChild(pChild);
         break;
       case AST_CONSTANT_PI:
         // replace by 2*ASIN(1.0)
         pResult = new ASTNode(AST_TIMES);
         pChild = new ASTNode(AST_REAL);
         pChild->setValue(2.0);
         pResult->addChild(pChild);
         pResult->addChild(new ASTNode(AST_FUNCTION_ARCSIN));
         pChild = new ASTNode(AST_REAL);
         pChild->setValue(1.0);
         pResult->getChild(1)->addChild(pChild);
         break;
       case AST_FUNCTION_SEC:
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_SEC(pChild);
         // replace by 1/cos(X)
         delete pChild;
         break;
       case AST_FUNCTION_CSC:
         // replace by 1/sin(X)
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_CSC(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_COT:
         // replace by 1/tan(X)
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_COT(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_SINH:
         // replace by (e^X-e^(-X))/2
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_SINH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_COSH:
         // replace by (e^X+e^(-X))/2
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_COSH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_TANH:
         // replace by (e^X-e^(-X))/(e^X+e^(-X))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_TANH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_SECH:
         // replace by 2/(e^X+e^(-X))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_SECH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_CSCH:
         // replace by 2/(e^X-e^(-X))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_CSCH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_COTH:
         // replace by (e^X+e^(-X))/(e^X-e^(-X))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_COTH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_ARCSINH:
         // replace by log(X + sqrt(X^2 + 1))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_ARCSINH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_ARCCOSH:
         // replace by log(X + sqrt(X-1) * sqrt(X+1))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_ARCCOSH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_ARCTANH:
         // replace by 1/2 * (log(1+X) - log(1-X))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_ARCTANH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_ARCSECH:
         // replace by log(sqrt((1/X)-1) * sqrt(1+(1/X)) + 1/X)
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_ARCSECH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_ARCCSCH:
         // replace by log(sqrt(1+ (1/ (X^2)))+(1/X))
         pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(0));
         assert(pChild);
         pResult = replace_ARCCSCH(pChild);
         delete pChild;
         break;
       case AST_FUNCTION_ARCCOTH:
         // this one is difficult since it would need a piecewise definition which
         // is not available in SBML Level 1
         fatalError();
         break;
       case AST_REAL:
         // for nan and inf
         if (pNode->getReal() != pNode->getReal()) // NaN
           {
             // replace by 0/0
             pResult = new ASTNode(AST_RATIONAL);
             pResult->setValue(0L, 0L);
           }
         else if (pNode->getReal() > std::numeric_limits< C_FLOAT64 >::max())
           {
             // replace by 1/0
             pResult = new ASTNode(AST_RATIONAL);
             pResult->setValue(1L, 0L);
           }
         else if (pNode->getReal() < - std::numeric_limits< C_FLOAT64 >::max())
           {
             // replace by -1/0
             pResult = new ASTNode(AST_RATIONAL);
             pResult->setValue(-1L, 0L);
           }
         else
           {
             pResult = pNode->deepCopy();
           }
         break;
       default:
         // copy the node
         pResult = ConverterASTNode::shallowCopy(pNode);
         iMax = pNode->getNumChildren();
         for (i = 0; i < iMax; ++i)
           {
             pChild = CSBMLExporter::replaceL1IncompatibleNodes(pNode->getChild(i));
             if (pChild != NULL)
               {
                 pResult->addChild(pChild);
               }
             else
               {
                 delete pResult;
                 pResult = NULL;
               }
           }
         break;
     }
   return pResult;
 }
CEvaluationNode * CSBMLExporter::replaceSpeciesReferences (const CEvaluationNode * pOrigNode, const CCopasiDataModel & dataModel) protected
Replaces references to species with reference to species divided by volume if it is a reference to a concentration or by a reference to the species times avogadros number if it is a reference to the amount. The method also takes into consideration the substance units of the model.
Definition at line 6066 of file CSBMLExporter.cpp.
References CCopasiNode< _Data >::addChild(), addRateOfIfItDoesNotExist(), CEvaluationNodeObject::CN, CEvaluationNode::copyBranch(), CEvaluationNode::copyNode(), createUniqueId(), CEvaluationNodeOperator::DIVIDE, CEvaluationNodeNumber::DOUBLE, CEvaluationNodeNumber::ENOTATION, fatalError, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CObjectInterface::getCN(), CCopasiObject::getCN(), CMetab::getCompartment(), CCopasiNode< _Data >::getData(), CCompartment::getDimensionality(), CCopasiDataModel::getModel(), CCopasiContainer::getObject(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CModel::getQuantity2NumberFactor(), CModel::getQuantityUnitEnum(), CCopasiNode< _Data >::getSibling(), CModelEntity::getStatus(), CEvaluationNode::getType(), CModelEntity::getValue(), CEvaluationNodeObject::INVALID, CCopasiObject::isReference(), mAvogadroCreated, mCOPASI2SBMLMap, mHandledSBMLObjects, mIdMap, mpAvogadro, mpSBMLDocument, mSBMLLevel, CEvaluationNodeOperator::MULTIPLY, mVariableVolumes, CEvaluationNode::NUMBER, CModel::number, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), CEvaluationNode::OPERATOR, pResult, CEvaluationNode::subType(), and CEvaluationNode::type().
Referenced by createEvent(), createInitialAssignment(), createKineticLaw(), createRule(), and exportEventAssignments().
 {
   CEvaluationNode* pResult = NULL;
   double factor = dataModel.getModel()->getQuantity2NumberFactor();
   if (CEvaluationNodeObject::type(pOrigNode->getType()) == CEvaluationNodeObject::OBJECT)
     {
       std::vector<CCopasiContainer*> containers;
       containers.push_back(const_cast<CModel*>(dataModel.getModel()));
       const CCopasiObject* pObject = dataModel.ObjectFromName(containers, dynamic_cast<const CEvaluationNodeObject*>(pOrigNode)->getObjectCN());
       if (pObject == NULL)
         {
           // this will be the object from the mInitialValueMap
           pResult = new CEvaluationNodeObject(CEvaluationNodeObject::CN, pOrigNode->getData());
           return pResult;
         }
       if (pObject->isReference())
         {
           const CCopasiObject* pParent = pObject->getObjectParent();
           // check if the parent is a metabolite
           const CMetab* pMetab = dynamic_cast<const CMetab*>(pParent);
           if (pMetab != NULL)
             {
               // check if the reference is to the concentration or to the
               // amount
               if (pObject->getObjectName() == "InitialConcentration" || pObject->getObjectName() == "Concentration")
                 {
                   // the concentration nodes only need to be replaced if we
                   // are dealing with a model that has variable volumes
                   if (this->mVariableVolumes == true)
                     {
                       // replace the node by the concentration node divided the the volume of
                       // the (initial) volume of the node
                       // although this is semantically incorrect, the result when
                       // converted to SBML will be OK since the concentration ode
                       // is converted to a reference to the species id which will
                       // be interpreted as the amount due to the
                       // hasOnlySubstanceUnits flag being set
                       const CCompartment* pCompartment = pMetab->getCompartment();
                       assert(pCompartment != NULL);
                       pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::DIVIDE, "/");
                       // copy branch should be fine since the object node does
                       // not have children
                       pResult->addChild(pOrigNode->copyBranch());
                       if (pObject->getObjectName() == "InitialConcentration")
{
                           pResult->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pCompartment->getObject(CCopasiObjectName("Reference=InitialVolume"))->getCN() + ">"));
                         }
                       else
{
                           pResult->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pCompartment->getObject(CCopasiObjectName("Reference=Volume"))->getCN() + ">"));
                         }
                     }
                   else
                     {
                       // do nothing
                       pResult = pOrigNode->copyBranch();
                     }
                 }
               else if (pObject->getObjectName() == "Rate")
                 {
                   std::string id = addRateOfIfItDoesNotExist(mpSBMLDocument, mIdMap, "rateOf");
                   pResult = new CEvaluationNodeObject(CEvaluationNodeObject::INVALID, "<rateOf>");
                   pResult->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pObject->getObjectParent()->getObject(CCopasiObjectName("Reference=Concentration"))->getCN() + ">"));
                   pResult->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + id + ">"));
                 }
               else if (pObject->getObjectName() == "InitialParticleNumber" || pObject->getObjectName() == "ParticleNumber")
                 {
                   // if the units are not set to particle numbers anyway,
                   // replace the node by the node times avogadros number
                   if (dataModel.getModel()->getQuantityUnitEnum() != CModel::number)
                     {
                       if (this->mpAvogadro == NULL)
{
                           this->mpAvogadro = const_cast<CModel*>(dataModel.getModel())->createModelValue("quantity to number factor", dataModel.getModel()->getQuantity2NumberFactor());
                           Parameter* pSBMLAvogadro = this->mpSBMLDocument->getModel()->createParameter();
                           pSBMLAvogadro->setName("quantity to number factor");
                           std::string sbmlId = CSBMLExporter::createUniqueId(this->mIdMap, mpAvogadro->getObjectName(), false);
                           pSBMLAvogadro->setId(sbmlId);
                           const_cast<CModelValue*>(this->mpAvogadro)->setSBMLId(sbmlId);
                           this->mIdMap.insert(std::pair<const std::string, const SBase*>(sbmlId, pSBMLAvogadro));
                           if (this->mSBMLLevel != 1)
{
                               pSBMLAvogadro->setConstant(true);
                             }
                           else
{
                               // Level 1 doesn't know the constant flag and
                               // libSBML does not drop it automatically
                               pSBMLAvogadro->setConstant(true);
                             }
                           pSBMLAvogadro->setValue(dataModel.getModel()->getQuantity2NumberFactor());
                           this->mHandledSBMLObjects.insert(pSBMLAvogadro);
                           this->mCOPASI2SBMLMap[this->mpAvogadro] = pSBMLAvogadro;
                           this->mAvogadroCreated = true;
                         }
                       pResult = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
                       // copyBranch should be save here since object nodes can't
                       // have children
                       pResult->addChild(pOrigNode->copyBranch());
                       pResult->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + this->mpAvogadro->getCN() + ",Reference=InitialValue>"));
                     }
                   else
                     {
                       // the result is the same as the original node
                       pResult = pOrigNode->copyBranch();
                     }
                   if (this->mVariableVolumes == false)
                     {
                       // multiply by the volume as well
                       const CCompartment* pCompartment = pMetab->getCompartment();
                       if (pCompartment->getDimensionality() != 0)
{
                           CEvaluationNode* pTmpNode = new CEvaluationNodeOperator(CEvaluationNodeOperator::MULTIPLY, "*");
                           pTmpNode->addChild(pResult);
                           if (pObject->getObjectName() == "InitialParticleNumber")
{
                               pTmpNode->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pCompartment->getObject(CCopasiObjectName("Reference=InitialVolume"))->getCN() + ">"));
                             }
                           else
{
                               pTmpNode->addChild(new CEvaluationNodeObject(CEvaluationNodeObject::CN, "<" + pCompartment->getObject(CCopasiObjectName("Reference=Volume"))->getCN() + ">"));
                             }
                           pResult = pTmpNode;
                         }
                     }
                 }
               else
                 {
                   fatalError();
                 }
             }
         }
     }
   // check if there is a division by avogadros number and if so, just
   // drop the division instead of introducing a new multiplication
   else if (CEvaluationNodeObject::type(pOrigNode->getType()) == CEvaluationNodeObject::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pOrigNode->getType())) == CEvaluationNodeOperator::DIVIDE)
     {
       // check if one of the child nodes is a reference to a species
       const CEvaluationNode* pLeft = dynamic_cast<const CEvaluationNode*>(pOrigNode->getChild());
       const CEvaluationNode* pRight = dynamic_cast<const CEvaluationNode*>(pLeft->getSibling());
       assert(pLeft != NULL);
       assert(pRight != NULL);
       if (CEvaluationNode::type(pLeft->getType()) == CEvaluationNode::OBJECT)
         {
           std::vector<CCopasiContainer*> containers;
           containers.push_back(const_cast<CModel*>(dataModel.getModel()));
           const CCopasiObject* pObject = dataModel.ObjectFromName(containers, dynamic_cast<const CEvaluationNodeObject*>(pLeft)->getObjectCN());
           if (pObject != NULL && pObject->isReference())
             {
               const CCopasiObject* pParent = pObject->getObjectParent();
               // check if the parent is a metabolite
               const CMetab* pMetab = dynamic_cast<const CMetab*>(pParent);
               if (pMetab != NULL)
                 {
                   // check if pRight is a number or a parameter that
                   // corresponds to avogadros number
                   if (CEvaluationNode::type(pRight->getType()) == CEvaluationNode::NUMBER &&
                       (((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pRight->getType())) == CEvaluationNodeNumber::DOUBLE ||
                        ((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pRight->getType())) == CEvaluationNodeNumber::ENOTATION))
                     {
                       double value = dynamic_cast<const CEvaluationNodeNumber*>(pRight)->getValue();
                       if (fabs((factor - value) / factor) <= 1e-3)
{
                           // copyBranch should be OK since the node has no
                           // children anyway
                           pResult = pLeft->copyBranch();
                         }
                     }
                   else if (CEvaluationNode::type(pRight->getType()) == CEvaluationNode::OBJECT)
                     {
                       const CCopasiObject* pObject2 = dataModel.ObjectFromName(containers, dynamic_cast<const CEvaluationNodeObject*>(pRight)->getObjectCN());
                       if (pObject2 != NULL && pObject2->isReference())
{
                           const CCopasiObject* pObjectParent2 = pObject2->getObjectParent();
                           const CModelValue* pMV = dynamic_cast<const CModelValue*>(pObjectParent2);
                           if (pMV != NULL && pMV->getStatus() == CModelEntity::FIXED)
{
                               double value = pMV->getValue();
                               if (fabs((factor - value) / factor) <= 1e-3)
{
                                   pResult = pLeft->copyBranch();
                                 }
                             }
                         }
                     }
                 }
               else
                 {
                   // Check if pRight is an object node
                   if (CEvaluationNode::type(pRight->getType()) == CEvaluationNode::OBJECT)
                     {
                       // check if pRight is a reference to a species
                       const CCopasiObject* pObject2 = dataModel.ObjectFromName(containers, dynamic_cast<const CEvaluationNodeObject*>(pRight)->getObjectCN());
                       if (pObject2 != NULL && pObject2->isReference())
{
                           const CCopasiObject* pParent2 = pObject2->getObjectParent();
                           // check if the parent is a metabolite
                           pMetab = dynamic_cast<const CMetab*>(pParent2);
                           if (pMetab != NULL)
{
                               // if yes, check if pLeft is a parameter that corresponds
                               // to Avogadros number
                               if (CEvaluationNode::type(pLeft->getType()) == CEvaluationNode::OBJECT)
{
                                   const CCopasiObject* pObject2 = dataModel.ObjectFromName(containers, dynamic_cast<const CEvaluationNodeObject*>(pLeft)->getObjectCN());
                                   if (pObject2 != NULL && pObject2->isReference())
{
                                       const CCopasiObject* pObjectParent2 = pObject2->getObjectParent();
                                       const CModelValue* pMV = dynamic_cast<const CModelValue*>(pObjectParent2);
                                       if (pMV != NULL && pMV->getStatus() == CModelEntity::FIXED)
{
                                           double value = pMV->getValue();
                                           if (fabs((factor - value) / factor) <= 1e-3)
{
                                               pResult = pRight->copyBranch();
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
   if (pResult == NULL)
     {
       pResult = pOrigNode->copyNode(NULL, NULL);
       const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pOrigNode->getChild());
       while (pChild != NULL)
         {
           CEvaluationNode* pNewChild = this->replaceSpeciesReferences(pChild, dataModel);
           assert(pNewChild != NULL);
           pResult->addChild(pNewChild);
           pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
         }
     }
   return pResult;
 }
void CSBMLExporter::restore_local_parameters (ASTNode * pOrigNode, const CCopasiDataModel & dataModel) protected
This method goes through the expression tree and tries to find node names that correspond to common names of local parameters. If the common name also occurs in the replacement map, the node name has to be set to the id of the corresponding global parameter, otherwise the name has to be set to the object name of the parameter.
Definition at line 7414 of file CSBMLExporter.cpp.
References CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), mParameterReplacementMap, and CCopasiDataModel::ObjectFromName().
Referenced by createKineticLaw().
 {
   if (pOrigNode != NULL)
     {
       if (pOrigNode->getType() == AST_NAME)
         {
           // check if the common name is in the replacement map
           std::string objectName = pOrigNode->getName();
           std::map<std::string, Parameter*>::iterator pos = this->mParameterReplacementMap.find(objectName);
           if (pos != this->mParameterReplacementMap.end())
             {
               // it was in the map, so we know that the local parameter has
               // been replaced by a global parameter and we need to set the
               // id of the global parameter as the new name of the node
               pOrigNode->setName(pos->second->getId().c_str());
             }
           else
             {
               // we need to reset the node name to the id of the local
               // parameter which is the object name
               std::vector<CCopasiContainer*> containers;
               containers.push_back(const_cast<CModel*>(dataModel.getModel()));
               const CCopasiObject* pObject = dataModel.ObjectFromName(containers, objectName);
               if (pObject != NULL)
                 {
                   const CCopasiParameter* pLocalParameter = dynamic_cast<const CCopasiParameter*>(pObject);
                   if (pLocalParameter != NULL)
                     {
                       // we set the node name to the existing parameter name
                       pOrigNode->setName(pLocalParameter->getObjectName().c_str());
                     }
                 }
             }
         }
       unsigned int i = 0, iMax = pOrigNode->getNumChildren();
       while (i < iMax)
         {
           this->restore_local_parameters(pOrigNode->getChild(i), dataModel);
           ++i;
         }
     }
 }
void CSBMLExporter::setExportCOPASIMIRIAM (bool exportMIRIAM)
Sets whether the exporter is supposed to export COPASIs MIRIAM annotation in addition to SBML MIRIAM.
Definition at line 7196 of file CSBMLExporter.cpp.
References mExportCOPASIMIRIAM.
Referenced by CCopasiDataModel::exportSBML(), and CCopasiDataModel::exportSBMLToString().
 {
   this->mExportCOPASIMIRIAM = exportMiriam;
 }
void CSBMLExporter::setFunctionSBMLIds (const CEvaluationNode * pNode, CCopasiDataModel & dataModel) protected
This method traverse a CEvaluationTree and set the SBML id on all functions that are used in function calls in the tree.
Definition at line 7091 of file CSBMLExporter.cpp.
References CEvaluationNode::CALL, createUniqueId(), fatalError, CFunctionDB::findFunction(), CCopasiNode< _Data >::getChild(), CCopasiRootContainer::getFunctionList(), CCopasiObject::getObjectName(), CFunction::getSBMLId(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), isValidSId(), mFunctionIdMap, mIdMap, CFunction::setSBMLId(), and CEvaluationNode::type().
Referenced by convertToASTNode().
 {
   if (CEvaluationNode::type(pNode->getType()) == CEvaluationNode::CALL)
     {
       std::string funName = dynamic_cast<const CEvaluationNodeCall*>(pNode)->getData();
       CFunction* pFun = CCopasiRootContainer::getFunctionList()->findFunction(funName);
       assert(pFun != NULL);
       if (pFun == NULL) fatalError();
       std::string id = pFun->getSBMLId();
       if (id.empty())
         {
           if (CSBMLExporter::isValidSId(funName))
             {
               if (this->mIdMap.find(funName) != this->mIdMap.end())
                 {
                   id = CSBMLExporter::createUniqueId(this->mIdMap, funName, true);
                 }
               else
                 {
                   id = funName;
                 }
             }
           else
             {
               id = CSBMLExporter::createUniqueId(this->mIdMap, funName, false);
             }
           this->mIdMap.insert(std::make_pair(id, (const SBase*)NULL));
           pFun->setSBMLId(id);
           // add the id,pointer pair to the function id map so that we know
           // that this id has been used for that function
           this->mFunctionIdMap.insert(std::pair<std::string, const CEvaluationTree*>(id, pFun));
         }
       else
         {
           // check if there is an entry in the function id map for that id
           std::map<std::string, const CEvaluationTree*>::iterator pos = this->mFunctionIdMap.find(id);
           if (pos == this->mFunctionIdMap.end())
             {
               // reserve this function name
               this->mIdMap.insert(std::pair<std::string, const SBase*>(id, (SBase*)NULL));
               this->mFunctionIdMap.insert(std::pair<std::string, const CEvaluationTree*>(id, pFun));
             }
           else
             {
               if (pos->second != pFun)
                 {
                   // mark the id as taken
                   this->mIdMap.insert(std::pair<std::string, const SBase*>(id, (SBase*)NULL));
                   id = CSBMLExporter::createUniqueId(this->mIdMap, pFun->getObjectName(), false);
                   pFun->setSBMLId(id);
                 }
             }
         }
     }
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   while (pChild != NULL)
     {
       this->setFunctionSBMLIds(pChild, dataModel);
       pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
     }
 }
bool CSBMLExporter::setSBMLNotes (SBase * pSBase, const CAnnotation * pAnno) static protected
This is a general method to set the notes of an SBase object based on a COPASI Annotation. This will allow us to export notes on objects other than just the model.
Definition at line 7697 of file CSBMLExporter.cpp.
References CAnnotation::getNotes(), CAnnotation::getUnsupportedAnnotations(), and CCopasiMessage::WARNING.
Referenced by createCompartment(), createEvent(), createFunctionDefinition(), createMetabolite(), createParameter(), createReaction(), and createSBMLDocument().
 {
   bool result = true;
   if (pSBase == NULL || pAnno == NULL)
     return false;
   if ((!pAnno->getNotes().empty()) && !(pAnno->getNotes().find_first_not_of(" \n\t\r") == std::string::npos))
     {
 #if LIBSBML_VERSION >= 40100
       // the new method to create notes does not add the notes tag around the notes any
       // more because libsbml 4 checks if it is there and adds it if it isn't
       XMLNode* pNotes = CSBMLExporter::createSBMLNotes(pAnno->getNotes());
 #else
       // if we are compiling agains libsbml 3, we use the old way of setting the notes
       std::string comments = "<notes>" + pAnno->getNotes() + "</notes>";
       // the convertStringToXMLNode has changed behavior between libsbml 3 and libsbml 4
       // in libsbml it creates a dummy node and in libsbml 4 it doesn't
       // somehow this never did affect the notes because they were exported correctly with
       // libsbml 3 already
       XMLNode* pNotes = XMLNode::convertStringToXMLNode(comments);
 #endif // LIBSBML_VERSION
       if (pNotes != NULL)
         {
           int notes_result = pSBase->setNotes(pNotes);
           if (notes_result != LIBSBML_OPERATION_SUCCESS)
             {
               // issue some warning
               std::string target;
               switch (pSBase->getTypeCode())
                 {
                   case SBML_MODEL:
                     target = "the SBML model";
                     break;
                   case SBML_COMPARTMENT:
                     target = " compartment \"";
                     target += pSBase->getName();
                     target += "\"";
                     break;
                   case SBML_SPECIES:
                     target =
                       target = "species \"";
                     target += pSBase->getName();
                     target += "\"";
                     break;
                   case SBML_PARAMETER:
                     target =
                       target = "parameter \"";
                     target += pSBase->getName();
                     target += "\"";
                     break;
                   case SBML_REACTION:
                     target = "reaction \"";
                     target += pSBase->getName();
                     target += "\"";
                     break;
                   case SBML_EVENT:
                     target = "event \"";
                     target += pSBase->getName();
                     target += "\"";
                     break;
                   default:
                     target = "object \"";
                     target += pSBase->getName();
                     target += "\"";
                     break;
                 }
               std::string warning = "Warning, notes could not be set on ";
               warning += target;
               warning += ", please consider reporting this to the COPASI developers.";
               CCopasiMessage(CCopasiMessage::WARNING, warning.c_str());
               result = false;
             }
           delete pNotes;
         }
       else
         {
           std::string target;
           switch (pSBase->getTypeCode())
             {
               case SBML_MODEL:
                 target = "the SBML model";
                 break;
               case SBML_COMPARTMENT:
                 target = " compartment \"";
                 target += pSBase->getName();
                 target += "\"";
                 break;
               case SBML_SPECIES:
                 target =
                   target = "species \"";
                 target += pSBase->getName();
                 target += "\"";
                 break;
               case SBML_PARAMETER:
                 target =
                   target = "parameter \"";
                 target += pSBase->getName();
                 target += "\"";
                 break;
               case SBML_REACTION:
                 target = "reaction \"";
                 target += pSBase->getName();
                 target += "\"";
                 break;
               case SBML_EVENT:
                 target = "event \"";
                 target += pSBase->getName();
                 target += "\"";
                 break;
               default:
                 target = "object \"";
                 target += pSBase->getName();
                 target += "\"";
                 break;
             }
           std::string warning = "Warning, notes could not be set on ";
           warning += target;
           warning += ", please consider reporting this to the COPASI developers.";
           CCopasiMessage(CCopasiMessage::WARNING, warning.c_str());
           result = false;
         }
     }
   const std::map<std::string, std::string>& map = pAnno->getUnsupportedAnnotations();
   if (map.size() > 0)
     {
       std::map<std::string, std::string>::const_iterator iter;
       for (iter = map.begin(); iter != map.end(); ++iter)
         pSBase->appendAnnotation(XMLNode::convertStringToXMLNode((*iter).second));
     }
   return result;
 }
void CSBMLExporter::updateCOPASI2SBMLMap (const CCopasiDataModel & dataModel) protected
Creates a new COPASI2SBMLMap baed on the old map and the copied SBMLDocument.
Definition at line 4560 of file CSBMLExporter.cpp.
References mCOPASI2SBMLMap, and mIdMap.
Referenced by createSBMLDocument().
 {
   // make sure the idMap is already up to date
   // go through the existing map and create a new one with all SBML
   // objects updated with objects from the copied
   // model
   this->mCOPASI2SBMLMap.clear();
   std::map<CCopasiObject*, SBase*>& modelMap = const_cast<CCopasiDataModel&>(dataModel).getCopasi2SBMLMap();
   std::map<CCopasiObject*, SBase*>::const_iterator it = modelMap.begin();
   std::map<CCopasiObject*, SBase*>::const_iterator endit = modelMap.end();
   while (it != endit)
     {
       std::map<std::string, const SBase*>::iterator pos = it->second == NULL ? mIdMap.end() :  this->mIdMap.find(it->second->getId());
       if (pos != this->mIdMap.end())
         {
           this->mCOPASI2SBMLMap.insert(std::pair<const CCopasiObject * const, SBase*>(it->first, const_cast<SBase*>(pos->second)));
         }
       ++it;
     }
 }
bool CSBMLExporter::updateMIRIAMAnnotation (const CCopasiObject * pCOPASIObject, SBase * pSBMLObject, std::map< std::string, const SBase * > & metaIds) protected
This method gets the MIRIAM annotation from the given COPASI object and sets it on the given SBML object.
This method updates the MIRIAM annotation on different model entities like the model itself, compartments, species, reactions, functions and global parameters
Definition at line 6361 of file CSBMLExporter.cpp.
References CRDFPredicate::bqbiol_encodes, CRDFPredicate::bqbiol_hasPart, CRDFPredicate::bqbiol_hasVersion, CRDFPredicate::bqbiol_is, CRDFPredicate::bqbiol_isDescribedBy, CRDFPredicate::bqbiol_isEncodedBy, CRDFPredicate::bqbiol_isHomologTo, CRDFPredicate::bqbiol_isPartOf, CRDFPredicate::bqbiol_isVersionOf, CRDFPredicate::bqbiol_occursIn, CRDFPredicate::bqmodel_is, CRDFPredicate::bqmodel_isDescribedBy, CRDFPredicate::copasi_encodes, CRDFPredicate::copasi_hasPart, CRDFPredicate::copasi_hasVersion, CRDFPredicate::copasi_is, CRDFPredicate::copasi_isDescribedBy, CRDFPredicate::copasi_isEncodedBy, CRDFPredicate::copasi_isHomologTo, CRDFPredicate::copasi_isPartOf, CRDFPredicate::copasi_isVersionOf, CRDFPredicate::copasi_occursIn, createUniqueId(), CRDFPredicate::end, fatalError, CRDFUtilities::fixLocalFileAboutReference(), CMIRIAMInfo::getBiologicalDescriptions(), CMIRIAMInfo::getCreatedDT(), CMIRIAMInfo::getCreators(), CModification::getDate(), CRDFNode::getDescendantsWithPredicate(), CCreator::getEmail(), CCreator::getFamilyName(), CCreator::getGivenName(), CMIRIAMResourceObject::getIdentifiersOrgURL(), CFunction::getKey(), CModelEntity::getKey(), CReaction::getKey(), CEvent::getKey(), CCopasiObject::getKey(), CAnnotation::getMiriamAnnotation(), CBiologicalDescription::getMIRIAMResourceObject(), CReference::getMIRIAMResourceObject(), CMIRIAMInfo::getModifications(), CCreator::getORG(), CMIRIAMInfo::getReferences(), CBiologicalDescription::getTriplet(), CReference::getTriplet(), CRDFPredicate::getType(), CMIRIAMInfo::load(), mExportCOPASIMIRIAM, mHaveModelHistoryAuthorWarning, mHaveModelHistoryCreationDateWarning, mHaveModelHistoryModificationDateWarning, mSBMLLevel, CRDFTriplet::pObject, CRDFTriplet::Predicate, replaceChild(), CCopasiVector< T >::size(), and CCopasiMessage::WARNING.
Referenced by createCompartment(), createEvent(), createFunctionDefinition(), createMetabolite(), createParameter(), createReaction(), and createSBMLDocument().
 {
   bool result = true;
   if (pCOPASIObject == NULL || pSBMLObject == NULL) return false;
   const CModelEntity* pModelEntity = dynamic_cast<const CModelEntity*>(pCOPASIObject);
   const CModel* pModel = dynamic_cast<const CModel*>(pCOPASIObject);
   const CFunction* pFunction = dynamic_cast<const CFunction*>(pCOPASIObject);
   const CReaction* pReaction = dynamic_cast<const CReaction*>(pCOPASIObject);
   const CEvent* pEvent = dynamic_cast<const CEvent*>(pCOPASIObject);
   CMIRIAMInfo miriamInfo;
   std::string miriamAnnotationString;
   if (pModelEntity != NULL)
     {
       miriamInfo.load(pModelEntity->getKey());
       miriamAnnotationString = pModelEntity->getMiriamAnnotation();
     }
   else if (pReaction != NULL)
     {
       miriamInfo.load(pReaction->getKey());
       miriamAnnotationString = pReaction->getMiriamAnnotation();
     }
   else if (pFunction != NULL)
     {
       miriamInfo.load(pFunction->getKey());
       miriamAnnotationString = pFunction->getMiriamAnnotation();
     }
   else if (pEvent != NULL)
     {
       miriamInfo.load(pEvent->getKey());
       miriamAnnotationString = pEvent->getMiriamAnnotation();
     }
   else
     {
       // we should never end up here
       fatalError();
     }
   // first we clear the old CVTerms on the object
   pSBMLObject->unsetCVTerms();
   // now we have to set the CVTerms on the SBML object
   // the MIRIAM elements that are valid for all entities are the references (IS
   // DECRIBED BY) and the biological descriptions
   const CCopasiVector<CBiologicalDescription>& descriptions = miriamInfo.getBiologicalDescriptions();
   size_t i, iMax = descriptions.size();
   const CBiologicalDescription* pDescription = NULL;
   CVTerm cvTerm;
   // COPASI only uses Biological Qualifiers
   cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
   for (i = 0; i < iMax; ++i)
     {
       pDescription = descriptions[i];
       assert(pDescription != NULL);
       switch (pDescription->getTriplet().Predicate.getType())
         {
           case CRDFPredicate::bqbiol_encodes:
           case CRDFPredicate::copasi_encodes:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_ENCODES);
             break;
           case CRDFPredicate::bqbiol_hasPart:
           case CRDFPredicate::copasi_hasPart:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_HAS_PART);
             break;
           case CRDFPredicate::bqbiol_hasVersion:
           case CRDFPredicate::copasi_hasVersion:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_HAS_VERSION);
             break;
           case CRDFPredicate::bqbiol_is:
           case CRDFPredicate::copasi_is:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_IS);
             break;
           // IS DESCRIBED BY is handled in the references below
           //case bqbiol_isDescribedBy:
           //    break;
           case CRDFPredicate::bqbiol_isEncodedBy:
           case CRDFPredicate::copasi_isEncodedBy:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_IS_ENCODED_BY);
             break;
           case CRDFPredicate::bqbiol_isHomologTo:
           case CRDFPredicate::copasi_isHomologTo:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_IS_HOMOLOG_TO);
             break;
           case CRDFPredicate::bqbiol_isPartOf:
           case CRDFPredicate::copasi_isPartOf:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_IS_PART_OF);
             break;
           case CRDFPredicate::bqbiol_isVersionOf:
           case CRDFPredicate::copasi_isVersionOf:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_IS_VERSION_OF);
             break;
 #if LIBSBML_VERSION >= 40100
           // This qualifier is supported in libsbml 4.1
           case CRDFPredicate::bqbiol_occursIn:
           case CRDFPredicate::copasi_occursIn:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_OCCURS_IN);
             break;
 #endif // LIBSBML_VERSION
           case CRDFPredicate::bqmodel_is:
             cvTerm.setQualifierType(MODEL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setBiologicalQualifierType(BQB_UNKNOWN);
             cvTerm.setModelQualifierType(BQM_IS);
             break;
           // IS DESCRIBED BY is handled in the references below
           //case bqmodel_isDescribedBy:
           //    break;
           default:
             // there are many qualifiers that start e.g. with copasi_ which are
             // not handled
             cvTerm.setQualifierType(UNKNOWN_QUALIFIER);
             break;
         }
       if (cvTerm.getQualifierType() != UNKNOWN_QUALIFIER)
         {
           // now we set the resources
           // TODO In COPASI there is only one resource per CBiologicalDescription
           // TODO object, I will have to check if libsbml puts all resources with the
           // TODO same predicate into one resource object since in libsbml a CVTerm
           // TODO can have several resources.
           // TODO If this isn't handled automatically by libsbml, I will have to add
           // TODO code that does this.
           cvTerm.addResource(pDescription->getMIRIAMResourceObject().getIdentifiersOrgURL());
           // before we set the CVTerm, we should make sure that the object has
           // a meta id
           if (!pSBMLObject->isSetMetaId())
             {
               std::string metaId = CSBMLExporter::createUniqueId(metaIds, "COPASI", true, "");
               metaIds.insert(std::pair<const std::string, const SBase*>(metaId, pSBMLObject));
               pSBMLObject->setMetaId(metaId);
             }
           pSBMLObject->addCVTerm(&cvTerm, true);
         }
     }
   const CCopasiVector<CReference>& references = miriamInfo.getReferences();
   const CReference* pReference = NULL;
   iMax = references.size();
   for (i = 0; i < iMax; ++i)
     {
       pReference = references[i];
       assert(pReference != NULL);
       CRDFPredicate::ePredicateType Predicates[] =
       {
         CRDFPredicate::copasi_isDescribedBy,
         CRDFPredicate::bqbiol_isDescribedBy,
         CRDFPredicate::bqmodel_isDescribedBy,
         CRDFPredicate::end
       };
       std::set< CRDFTriplet > Triples;
       CRDFTriplet IdTriplet;
       CRDFPredicate::ePredicateType * pPredicate = Predicates;
       std::set< CRDFTriplet >::iterator it;
       for (; *pPredicate != CRDFPredicate::end; ++pPredicate)
         {
           Triples = pReference->getTriplet().pObject->getDescendantsWithPredicate(*pPredicate);
           it = Triples.begin();
           if (it != Triples.end())
             IdTriplet = *it;
         }
       if (!IdTriplet)
         continue;
       switch (IdTriplet.Predicate.getType())
         {
           case CRDFPredicate::bqbiol_isDescribedBy:
           case CRDFPredicate::copasi_isDescribedBy:
             cvTerm.setQualifierType(BIOLOGICAL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setModelQualifierType(BQM_UNKNOWN);
             cvTerm.setBiologicalQualifierType(BQB_IS_DESCRIBED_BY);
             break;
           case CRDFPredicate::bqmodel_isDescribedBy:
             cvTerm.setQualifierType(MODEL_QUALIFIER);
             // libsbml does not reset the model qualifier type and the
             // biological qualifier type if the qualifier type is set
             cvTerm.setBiologicalQualifierType(BQB_UNKNOWN);
             cvTerm.setModelQualifierType(BQM_IS_DESCRIBED_BY);
             break;
           default:
             cvTerm.setQualifierType(UNKNOWN_QUALIFIER);
             break;
         }
       // set the resources which consist of the pubmed id and the DOI
       if (cvTerm.getQualifierType() != UNKNOWN_QUALIFIER)
         {
           // now we set the resources
           // TODO In COPASI there is only one resource per CBiologicalDescription
           // TODO object, I will have to check if libsbml puts all resources with the
           // TODO same predicate into one resource object since in libsbml a CVTerm
           // TODO can have several resources.
           // TODO If this isn't handled automatically by libsbml, I will have to add
           // TODO code that does this.
           cvTerm.addResource(pReference->getMIRIAMResourceObject().getIdentifiersOrgURL());
           // before we set the CVTerm, we should make sure that the object has
           // a meta id
           if (!pSBMLObject->isSetMetaId())
             {
               std::string metaId = CSBMLExporter::createUniqueId(metaIds, "COPASI", true, "");
               metaIds.insert(std::pair<const std::string, const SBase*>(metaId, pSBMLObject));
               pSBMLObject->setMetaId(metaId);
             }
           pSBMLObject->addCVTerm(&cvTerm, true);
         }
     }
   // starting with SBML L3 all model elements that are derived from SBase can have
   // a model history
   //
   // if it is the model, we have to set the model history
   // in addition to the normal CVTerms
   if ((pModel != NULL && this->mSBMLLevel < 3)
 #if LIBSBML_VERSION >= 40100
 // actually this preprocessor directive is not really necessary, but better safe then sorry
       || this->mSBMLLevel > 2
 #endif // LIBSBML_VERSION
      )
     {
       // the model history consists of the creators, the creation time and the
       // modification time
       // create a model history instance
       bool modified = false;
       ModelHistory modelHistory;
       // first we add all creators
       const CCopasiVector<CCreator>& creators = miriamInfo.getCreators();
       size_t i, iMax = creators.size();
       const CCreator* pCreator = NULL;
       ModelCreator modelCreator;
       if (iMax > 0)
         {
           modified = true;
         }
       for (i = 0; i < iMax; ++i)
         {
           pCreator = creators[i];
           assert(pCreator != NULL);
           // a model creator can have a family name, a given name, and email
           // address and an organization
           modelCreator.setFamilyName(pCreator->getFamilyName());
           modelCreator.setGivenName(pCreator->getGivenName());
           modelCreator.setEmail(pCreator->getEmail());
           modelCreator.setOrganisation(pCreator->getORG());
           modelHistory.addCreator(&modelCreator);
         }
       if (modelHistory.getNumCreators() < 1 && !mHaveModelHistoryAuthorWarning)
         {
           mHaveModelHistoryAuthorWarning = true;
           CCopasiMessage(CCopasiMessage::WARNING, "The ModelHistory cannot be exported to SBML, as no author has been defined.");
         }
       // now set the creation date
       std::string creationDateString = miriamInfo.getCreatedDT();
       if (!creationDateString.empty())
         {
           Date creationDate = Date(creationDateString);
           modelHistory.setCreatedDate(&creationDate);
           modified = true;
         }
       if (!modelHistory.isSetCreatedDate() && !mHaveModelHistoryCreationDateWarning)
         {
           mHaveModelHistoryCreationDateWarning = true;
           CCopasiMessage(CCopasiMessage::WARNING, "The ModelHistory cannot be exported to SBML, as no creation date has been defined.");
         }
       // Since SBML can have only one modification time, and we can have several,
       // we have to take the last one
       const CCopasiVector <CModification> & modifications = miriamInfo.getModifications();
       iMax = modifications.size();
       if (iMax != 0)
         {
           modified = true;
           const CModification* pModification = modifications[0];
           assert(pModification != NULL);
           std::string lastDateString = pModification->getDate();
           for (i = 1; i < iMax; ++i)
             {
               pModification = modifications[i];
               assert(pModification != NULL);
               std::string dateString = pModification->getDate();
               // since the date string is in W3CDTF format, a normal string
               // compare should be enough to find out which date is more recent
               if (dateString > lastDateString)
                 {
                   lastDateString = dateString;
                 }
             }
           Date modifiedDate(lastDateString);
           modelHistory.setModifiedDate(&modifiedDate);
         }
       else if (modelHistory.isSetCreatedDate())
         {
           // a model history is only valid if it has a modifiedData
           modelHistory.setModifiedDate(modelHistory.getCreatedDate());
         }
       if (!modelHistory.isSetModifiedDate() && mHaveModelHistoryModificationDateWarning)
         {
           mHaveModelHistoryModificationDateWarning = true;
           CCopasiMessage(CCopasiMessage::WARNING, "The ModelHistory cannot be exported to SBML, as no modification date has been defined.");
         }
 #if LIBSBML_VERSION >= 40100
       if (this->mSBMLLevel > 2)
         {
           // set the model history on the sbml object
           // make sure the model has a meta id
           if (!pSBMLObject->isSetMetaId())
             {
               std::string metaId = CSBMLExporter::createUniqueId(metaIds, "COPASI", true, "");
               metaIds.insert(std::pair<const std::string, const SBase*>(metaId, pSBMLObject));
               pSBMLObject->setMetaId(metaId);
             }
           if (modified == true)
             {
               pSBMLObject->setModelHistory(&modelHistory);
             }
         }
       else
         {
 #endif // LIBSBML_VERSION
           // set the model history on the model
           Model* pSBMLModel = dynamic_cast<Model*>(pSBMLObject);
           assert(pSBMLModel != NULL);
           // make sure the model has a meta id
           if (!pSBMLModel->isSetMetaId())
             {
               std::string metaId = CSBMLExporter::createUniqueId(metaIds, "COPASI", true, "");
               metaIds.insert(std::pair<const std::string, const SBase*>(metaId, pSBMLModel));
               pSBMLModel->setMetaId(metaId);
             }
           if (modified == true)
             {
               pSBMLModel->setModelHistory(&modelHistory);
             }
 #if LIBSBML_VERSION >= 40100
         }
 #endif // LIBSBML_VERSION
     }
   if (this->mExportCOPASIMIRIAM == true)
     {
       // add the COPASI RDF stuff as an annotation in the COPASI namespace
       XMLNode* pCOPASIAnnotation = NULL;
       XMLNode* pAnnotation = NULL;
       int COPASIAnnotationIndex = -1;
       int oldRDFAnnotationIndex = -1;
       if (pSBMLObject->isSetAnnotation())
         {
           pAnnotation = pSBMLObject->getAnnotation();
           unsigned int i, iMax = pAnnotation->getNumChildren();
           // find the COPASI annotation if there is one
           for (i = 0; i < iMax; ++i)
             {
               if (pAnnotation->getChild(i).getURI() == "http://www.copasi.org/static/sbml")
                 {
                   pCOPASIAnnotation = pSBMLObject->getAnnotation()->getChild(i).clone();
                   COPASIAnnotationIndex = i;
                   unsigned int j, jMax = pCOPASIAnnotation->getNumChildren();
                   // find the index of the RDF subtree if there is one
                   for (j = 0; j < jMax; ++j)
                     {
                       if (pCOPASIAnnotation->getChild(j).getURI() == "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
{
                           oldRDFAnnotationIndex = j;
                           break;
                         }
                     }
                   break;
                 }
             }
         }
       // replace the meta ids in the MIRIAM annotation string
       if (miriamAnnotationString.find_first_not_of("\t\r\n ") != std::string::npos)
         {
           std::string metaId;
           if (pSBMLObject->isSetMetaId())
             {
               metaId = pSBMLObject->getMetaId();
             }
           else
             {
               metaId = CSBMLExporter::createUniqueId(metaIds, "COPASI", true, "");
               metaIds.insert(std::pair<const std::string, const SBase*>(metaId, pSBMLObject));
               pSBMLObject->setMetaId(metaId);
             }
           // now we have to replace the metaid
           CRDFUtilities::fixLocalFileAboutReference(miriamAnnotationString, metaId, pCOPASIObject->getKey());
           // the new annotation is not empty, so we have to convert it
           // the root of the returned tree is a dummy node, so the actual
           // RDF element is the first child of the returned value
           // the convertStringToXMLNode has changed behavior between libsbml 3 and libsbml 4
           // in libsbml it creates a dummy node and in libsbml 4 it doesn't
           XMLNode* pMIRIAMNode = XMLNode::convertStringToXMLNode(miriamAnnotationString);
           assert(pMIRIAMNode != NULL);
           if (pCOPASIAnnotation == NULL)
             {
               // create a new COPASI annotation
               // the root of the returned tree is a dummy node, so the actual
               // COPASI is the first child of the returned value
               // the convertStringToXMLNode has changed behavior between libsbml 3 and libsbml 4
               // in libsbml it creates a dummy node and in libsbml 4 it doesn't
               pCOPASIAnnotation = XMLNode::convertStringToXMLNode("<COPASI xmlns=\"http://www.copasi.org/static/sbml\"></COPASI>");
               // now we have to make an additional copy since otherwise we would
               // need a const_cast later on.
               // This is due to a limitation in the libsbml API.
 #if LIBSBML_VERSION < 40001
               XMLNode* pTmpNode = pCOPASIAnnotation->getChild(0).clone();
               delete pCOPASIAnnotation;
               pCOPASIAnnotation = pTmpNode;
 #endif // LIBSBML_VERSION < 40001
               // calling unsetEnd is necessary for libsbml 3.1.1 and 3.2.0,
               // otherwise libsbml will write the opening COPASI element as a
               // closing element and add another closing element later on which is
               // incorrect XML
               pCOPASIAnnotation->unsetEnd();
               assert(pCOPASIAnnotation != NULL);
               // add the RDF stuff
               // we add the first child of the MIRIAM node since it was created
               // with convertStrngToXMLNode which creates a dummy node as the
               // root node
 #if LIBSBML_VERSION < 40001
               pCOPASIAnnotation->addChild(pMIRIAMNode->getChild(0));
 #else
               pCOPASIAnnotation->addChild(*pMIRIAMNode);
 #endif // LIBSBML_VERSION < 40001
               // delete the MIRIAM node since addChild made a copy
               delete pMIRIAMNode;
             }
           else
             {
               // replace the old RDF annotation from the COPASI subtree if there
               // is one, else add the new one
               if (oldRDFAnnotationIndex != -1)
                 {
                   //
                   XMLNode* pNewCOPASIAnnotation = CSBMLExporter::replaceChild(pCOPASIAnnotation, pMIRIAMNode, oldRDFAnnotationIndex);
                   // delete the old copy of the COPASI node
                   delete pCOPASIAnnotation;
                   pCOPASIAnnotation = pNewCOPASIAnnotation;
                   // delete the MIRIAM node since replaceChild made a copy
                   delete pMIRIAMNode;
                 }
               else
                 {
                   // we add the first child of the MIRIAM node since it was created
                   // with convertStrngToXMLNode which creates a dummy node as the
                   // root node
                   pCOPASIAnnotation->addChild(pMIRIAMNode->getChild(0));
                   // delete the MIRIAM node since addChild made a copy
                   delete pMIRIAMNode;
                 }
             }
           // I don't think that getAnnotation will every return NULL because it is
           // created on the fly by libsbml if there isn't one already.
           // This is just a safety net in cast the libsbml API changes
           if (pSBMLObject->getAnnotation() == NULL)
             {
               // the convertStringToXMLNode has changed behavior between libsbml 3 and libsbml 4
               // in libsbml it creates a dummy node and in libsbml 4 it doesn't
               pAnnotation = XMLNode::convertStringToXMLNode("<annotation></annotation>");
               // the libsbml convertStringToXMLNode doesn't seem to work in the
               // same way when we create an annotation node as opposed to the
               // COPASI node above.
               // For the COPASI node, we get a dummy node as the root whereas here
               // we don't
               assert(pAnnotation != NULL);
               // add the COPASI annotation
               // if we created the COPASI element with convertStringTOXMLNode, we
               // have to use the first child since the root is a dummy node
               pAnnotation->addChild(*pCOPASIAnnotation);
               // pCOPASIAnnotation is always a copy, so we have to delete it
               delete pCOPASIAnnotation;
               pSBMLObject->setAnnotation(pAnnotation);
               delete pAnnotation;
             }
           else
             {
               // if there is a COPASI node, if yes replace it else add it
               if (COPASIAnnotationIndex != -1)
                 {
                   // we have to call getAnnotation on the SBML object instead of resulting
                   // the annotation we got above because libsbml deletes the annotation
                   //  object when it syncs the annotation. So the annotation object we
                   //  got above is most likely deleted already
                   pAnnotation = CSBMLExporter::replaceChild(pSBMLObject->getAnnotation(), pCOPASIAnnotation, COPASIAnnotationIndex);
                   // we have to delete pCOPASIAnnotation since replaceChild makes a copy
                   delete pCOPASIAnnotation;
                   pSBMLObject->setAnnotation(pAnnotation);
                   delete pAnnotation;
                 }
               else
                 {
                   // we have to call getAnnotation on the SBML object instead of resulting
                   // the annotation we got above because libsbml deletes the annotation
                   //  object when it syncs the annotation. So the annotation object we
                   //  got above is most likely deleted already
                   pSBMLObject->getAnnotation()->addChild(*pCOPASIAnnotation);
                   // we have to delete pCOPASIAnnotation since replaceChild made a copy
                   delete pCOPASIAnnotation;
                 }
             }
         }
       else
         {
           // if there is an RDF annotation in the COPASI annotation already, we
           // have to delete it.
           // if this rdf annotation is the only child of the COPASI annotation,
           // we delete the whole COPASI annotation
           if (pSBMLObject->getAnnotation() != NULL && COPASIAnnotationIndex != -1 && oldRDFAnnotationIndex != -1)
             {
               if (pCOPASIAnnotation->getNumChildren() == 1)
                 {
                   // we have to call getAnnotation on the SBML object instead of reusing
                   // the annotation we got above because libsbml deletes the annotation
                   //  object when it syncs the annotation. So the annotation object we
                   //  got above is most likely deleted already
                   if (pSBMLObject->getAnnotation()->getNumChildren() == 1)
                     {
                       // delete the complete annotation
                       pSBMLObject->unsetAnnotation();
                     }
                   else
                     {
                       // only delete the COPASI subtree
                       // we have to call getAnnotation on the SBML object instead of reusing
                       // the annotation we got above because libsbml deletes the annotation
                       //  object when it syncs the annotation. So the annotation object we
                       //  got above is most likely deleted already
                       pAnnotation = CSBMLExporter::replaceChild(pSBMLObject->getAnnotation(), NULL, COPASIAnnotationIndex);
                       assert(pAnnotation != NULL);
                       pSBMLObject->setAnnotation(pAnnotation);
                       // delete the annotation object since it has been created by
                       // replaceChild and setAnnotation made a copy
                       delete pAnnotation;
                     }
                 }
               else
                 {
                   // delete the RDF annotation from the COPASI tree
                   // replace the COPASI tree in pAnnotation
                   pCOPASIAnnotation = CSBMLExporter::replaceChild(pCOPASIAnnotation, NULL, oldRDFAnnotationIndex);
                   assert(pCOPASIAnnotation != NULL);
                   // we have to call getAnnotation on the SBML object instead of reusing
                   // the annotation we got above because libsbml deletes the annotation
                   //  object when it syncs the annotation. So the annotation object we
                   //  got above is most likely deleted already
                   pAnnotation = CSBMLExporter::replaceChild(pSBMLObject->getAnnotation(), pCOPASIAnnotation, COPASIAnnotationIndex);
                   // delete pCOPASIAnnotation since replaceChild made a copy
                   delete pCOPASIAnnotation;
                   pSBMLObject->setAnnotation(pAnnotation);
                   // delete the annotation object since it has been created by
                   // replaceChild and setAnnotation made a copy
                   delete pAnnotation;
                 }
             }
         }
     }
   return result;
 }
Member Data Documentation
std::vector<CModelEntity*> CSBMLExporter::mAssignmentVector protected
Definition at line 58 of file CSBMLExporter.h.
Referenced by checkForUnsupportedFunctionCalls(), checkForUnsupportedObjectReferences(), createCompartment(), createMetabolite(), createParameter(), and orderRules().
bool CSBMLExporter::mAvogadroCreated protected
Definition at line 69 of file CSBMLExporter.h.
Referenced by createSBMLDocument(), and replaceSpeciesReferences().
std::map<const CCopasiObject*, SBase*> CSBMLExporter::mCOPASI2SBMLMap protected
Definition at line 61 of file CSBMLExporter.h.
Referenced by createCompartment(), createEvent(), createEvents(), createFunctionDefinition(), createFunctionDefinitions(), createInitialAssignment(), createMetabolite(), createParameter(), createReaction(), createRule(), createSBMLDocument(), exportEventAssignments(), exportModelToString(), getCOPASI2SBMLMap(), removeUnusedObjects(), replaceSpeciesReferences(), and updateCOPASI2SBMLMap().
bool CSBMLExporter::mDocumentDisowned protected
Definition at line 73 of file CSBMLExporter.h.
Referenced by disownSBMLDocument(), and ~CSBMLExporter().
bool CSBMLExporter::mExportCOPASIMIRIAM protected
Definition at line 74 of file CSBMLExporter.h.
Referenced by isSetExportCOPASIMIRIAM(), setExportCOPASIMIRIAM(), and updateMIRIAMAnnotation().
ListOfFunctionDefinitions CSBMLExporter::mExportedFunctions protected
Definition at line 77 of file CSBMLExporter.h.
Referenced by convertToLevel1(), createFunctionDefinition(), createFunctionDefinitions(), and createSBMLDocument().
std::map<std::string, const CEvaluationTree*> CSBMLExporter::mFunctionIdMap protected
Definition at line 72 of file CSBMLExporter.h.
Referenced by createSBMLDocument(), and setFunctionSBMLIds().
std::map<const FunctionDefinition*, const CCopasiObject*> CSBMLExporter::mFunctionMap protected
Definition at line 78 of file CSBMLExporter.h.
Referenced by createFunctionDefinition(), createFunctionDefinitions(), and createSBMLDocument().
std::set<SBase*> CSBMLExporter::mHandledSBMLObjects protected
Definition at line 62 of file CSBMLExporter.h.
Referenced by createCompartment(), createInitialAssignment(), createMetabolite(), createParameter(), createReaction(), exportEventAssignments(), exportModelToString(), removeUnusedObjects(), replace_local_parameters(), and replaceSpeciesReferences().
bool CSBMLExporter::mHaveModelHistoryAuthorWarning protected
Definition at line 80 of file CSBMLExporter.h.
Referenced by createSBMLDocument(), and updateMIRIAMAnnotation().
bool CSBMLExporter::mHaveModelHistoryCreationDateWarning protected
Definition at line 81 of file CSBMLExporter.h.
Referenced by createSBMLDocument(), and updateMIRIAMAnnotation().
bool CSBMLExporter::mHaveModelHistoryModificationDateWarning protected
Definition at line 82 of file CSBMLExporter.h.
Referenced by createSBMLDocument(), and updateMIRIAMAnnotation().
std::map<std::string, const SBase*> CSBMLExporter::mIdMap protected
Definition at line 64 of file CSBMLExporter.h.
Referenced by assignSBMLIdsToReactions(), convertToASTNode(), createCompartment(), createEvent(), createFunctionDefinition(), createMetabolite(), createParameter(), createReaction(), createSBMLDocument(), exportModelToString(), replace_local_parameters(), replaceSpeciesReferences(), setFunctionSBMLIds(), and updateCOPASI2SBMLMap().
std::vector<SBMLIncompatibility> CSBMLExporter::mIncompatibilities protected
Definition at line 65 of file CSBMLExporter.h.
Referenced by createEvent(), createEvents(), createFunctionDefinition(), createInitialAssignment(), createMetabolites(), createRule(), createSBMLDocument(), exportEventAssignments(), and outputIncompatibilities().
bool CSBMLExporter::mIncompleteExport protected
Definition at line 66 of file CSBMLExporter.h.
Referenced by createEvent(), createInitialAssignment(), createReaction(), createRule(), createSBMLDocument(), and exportEventAssignments().
std::vector<CModelEntity*> CSBMLExporter::mInitialAssignmentVector protected
Definition at line 60 of file CSBMLExporter.h.
Referenced by checkForUnsupportedFunctionCalls(), checkForUnsupportedObjectReferences(), createCompartment(), createInitialAssignments(), createMetabolite(), and createParameter().
std::map<const std::string, Parameter*> CSBMLExporter::mInitialValueMap protected
Definition at line 79 of file CSBMLExporter.h.
Referenced by checkForUnsupportedObjectReferences(), createEvent(), createInitialAssignment(), createRule(), createSBMLDocument(), and exportEventAssignments().
std::map<std::string, const SBase*> CSBMLExporter::mMetaIdMap protected
Definition at line 70 of file CSBMLExporter.h.
Referenced by createCompartment(), createEvent(), createFunctionDefinition(), createMetabolite(), createParameter(), createReaction(), and createSBMLDocument().
bool CSBMLExporter::mMIRIAMWarning protected
Definition at line 71 of file CSBMLExporter.h.
std::vector<CModelEntity*> CSBMLExporter::mODEVector protected
Definition at line 59 of file CSBMLExporter.h.
Referenced by checkForUnsupportedFunctionCalls(), checkForUnsupportedObjectReferences(), createCompartment(), createMetabolite(), createParameter(), and createRules().
std::map<std::string, Parameter*> CSBMLExporter::mParameterReplacementMap protected
Definition at line 75 of file CSBMLExporter.h.
Referenced by createKineticLaw(), replace_local_parameters(), and restore_local_parameters().
const CModelValue* CSBMLExporter::mpAvogadro protected
Definition at line 68 of file CSBMLExporter.h.
Referenced by createSBMLDocument(), findAvogadro(), and replaceSpeciesReferences().
SBMLDocument* CSBMLExporter::mpSBMLDocument protected
Definition at line 55 of file CSBMLExporter.h.
Referenced by convertToASTNode(), convertToLevel1(), createAreaUnit(), createCompartment(), createCompartments(), createEvent(), createEvents(), createFunctionDefinition(), createFunctionDefinitions(), createInitialAssignment(), createKineticLaw(), createLengthUnit(), createMetabolite(), createMetabolites(), createParameter(), createParameters(), createReaction(), createReactions(), createRule(), createRules(), createSBMLDocument(), createSubstanceUnit(), createTimeUnit(), createVolumeUnit(), exportModelToString(), getSBMLDocument(), hasVolumeAssignment(), removeInitialAssignment(), removeRule(), removeUnusedObjects(), replace_local_parameters(), replaceSpeciesReferences(), and ~CSBMLExporter().
unsigned int CSBMLExporter::mSBMLLevel protected
Definition at line 56 of file CSBMLExporter.h.
Referenced by createAreaUnit(), createCompartment(), createEvent(), createEvents(), createFunctionDefinition(), createInitialAssignment(), createKineticLaw(), createLengthUnit(), createMetabolite(), createMetabolites(), createParameter(), createReaction(), createRule(), createSBMLDocument(), createSubstanceUnit(), createTimeUnit(), createVolumeUnit(), exportEventAssignments(), exportModelToString(), hasVolumeAssignment(), replaceSpeciesReferences(), and updateMIRIAMAnnotation().
unsigned int CSBMLExporter::mSBMLVersion protected
Definition at line 57 of file CSBMLExporter.h.
Referenced by createAreaUnit(), createEvent(), createFunctionDefinition(), createInitialAssignment(), createLengthUnit(), createMetabolite(), createMetabolites(), createRule(), createSBMLDocument(), createSubstanceUnit(), createTimeUnit(), createVolumeUnit(), exportEventAssignments(), exportModelToString(), and hasVolumeAssignment().
std::set<std::string> CSBMLExporter::mSpatialSizeUnitsSpecies protected
Definition at line 76 of file CSBMLExporter.h.
Referenced by createMetabolite(), and createMetabolites().
std::set<CFunction*> CSBMLExporter::mUsedFunctions protected
Definition at line 63 of file CSBMLExporter.h.
Referenced by checkForUnsupportedFunctionCalls(), createEvent(), createFunctionDefinitions(), createInitialAssignment(), createKineticExpression(), createRule(), and exportEventAssignments().
bool CSBMLExporter::mVariableVolumes protected
Definition at line 67 of file CSBMLExporter.h.
Referenced by createMetabolite(), createSBMLDocument(), and replaceSpeciesReferences().
The documentation for this class was generated from the following files:
CSBMLExporter.h
CSBMLExporter.cpp