COPASI API: CCopasiXMLParser::MethodElement Class Reference
CCopasiXMLParser::MethodElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
MethodElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~MethodElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Method = 0, Content }
Private Attributes
size_t mLineNumber
ParameterGroupElement * mpContentHandler
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2352 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::MethodElement::Element private
Enum of invoked parsers
Enumerator
Method
Content
Definition at line 2360 of file CCopasiXMLParser.h.
     {
       Method = 0,
       Content
     };
Constructor & Destructor Documentation
CCopasiXMLParser::MethodElement::MethodElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 9262 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler < CCopasiXMLParser,
   SCopasiXMLParserCommon > (parser, common),
   mpContentHandler(NULL),
   mLineNumber(0)
 {}
CCopasiXMLParser::MethodElement::~MethodElement () virtual
Destructor
Definition at line 9270 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpContentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::MethodElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 9340 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Method:
         if (strcmp(pszName, "Method"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Method", mParser.getCurrentLineNumber());
         mCurrentElement = START_ELEMENT;
         mParser.popElementHandler();
         mParser.onEndElement(pszName);
         break;
       case Content:
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::MethodElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 9275 of file CCopasiXMLParser.cpp.
References CCopasiTask::getMethod(), CCopasiMethod::getSubType(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentTask, CCopasiTask::setMethodType(), CCopasiObject::setObjectName(), toEnum(), UNKNOWN_ELEMENT, CCopasiMethod::unset, CCopasiMessage::WARNING, and CCopasiMethod::XMLSubType.
 {
   mCurrentElement++; // We should always be on the next element
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   std::string name;
   std::string sType;
   switch (mCurrentElement)
     {
       case Method:
         if (!strcmp(pszName, "Method"))
           {
             // get name and type attribute
             name = mParser.getAttributeValue("name", papszAttrs);
             sType = mParser.getAttributeValue("type", papszAttrs, "default");
             // first set the type of the with setMethodType of the current task
             // object
             CCopasiMethod::SubType type =
               toEnum(sType.c_str(), CCopasiMethod::XMLSubType, CCopasiMethod::unset);
             if (type != CCopasiMethod::unset)
               {
                 mCommon.pCurrentTask->setMethodType(type);
               }
             else
               {
                 // We use the default method for this task and issue a warning
                 CCopasiMessage(CCopasiMessage::WARNING, MCXML + 18, sType.c_str(),
                                mParser.getCurrentLineNumber(),
                                CCopasiMethod::XMLSubType[mCommon.pCurrentTask->getMethod()->getSubType()]);
               }
             mCommon.pCurrentTask->getMethod()->setObjectName(name);
             if (!mpContentHandler)
               {
                 mpContentHandler = new ParameterGroupElement(mParser, mCommon);
               }
             mpContentHandler->setDerivedElement(mCommon.pCurrentTask->getMethod());
             mpCurrentHandler = mpContentHandler;
           }
         break;
       case Content:
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
 }
Member Data Documentation
size_t CCopasiXMLParser::MethodElement::mLineNumber private
The line number the unknown parameter was encountered.
Definition at line 2371 of file CCopasiXMLParser.h.
ParameterGroupElement* CCopasiXMLParser::MethodElement::mpContentHandler private
Definition at line 2366 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp