COPASI API: CPlotItem Class Reference
CPlotItem Class Reference
#include <CPlotItem.h>
Public Types
enum Type {
unset = 0, curve2d, histoItem1d, bandedGraph,
surface, plot2d, simWiz
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
void addChannel (const CPlotDataChannelSpec &channel)
void cleanup ()
CPlotItem (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=curve2d)
CPlotItem (const CPlotItem &src, const CCopasiContainer *pParent=NULL)
const COutputInterface::Activity & getActivity () const
std::vector
< CPlotDataChannelSpec > & getChannels ()
const std::vector
< CPlotDataChannelSpec > & getChannels () const
size_t getNumChannels () const
const std::string & getTitle () const
const CPlotItem::Type & getType () const
void setActivity (const COutputInterface::Activity &activity)
void setTitle (const std::string &title)
void setType (CPlotItem::Type type)
virtual ~CPlotItem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const std::string RecordingActivityName []
static const std::string TypeName []
static const char * XMLRecordingActivity []
static const char * XMLType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Private Member Functions
void initObjects ()
Private Attributes
std::vector< CPlotDataChannelSpec > channels
COutputInterface::Activity mActivity
std::string * mpXMLActivity
Type mType
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 81 of file CPlotItem.h.
Member Enumeration Documentation
enum CPlotItem::Type
Enumeration of the sub types of methods known to COPASI.
Enumerator
unset
curve2d
histoItem1d
bandedGraph
surface
plot2d
simWiz
Definition at line 87 of file CPlotItem.h.
   {
     unset = 0, curve2d, histoItem1d,            //for plot items
     bandedGraph,
     surface,
     plot2d, simWiz   //for plot specifications
   };
Constructor & Destructor Documentation
CPlotItem::CPlotItem (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL, const Type & type = curve2d)
Definition at line 75 of file CPlotItem.cpp.
References CCopasiObject::setObjectName(), and setType().
Referenced by CPlotSpecification::createItem().
                                                 :
     CCopasiParameterGroup(TypeName[type], pParent, "PlotItem"),
     mType(unset),
     mActivity(),
     mpXMLActivity(NULL)
 {
   //setObjectName(TypeName[mType]); //TODO
   setObjectName(name);
   setType(type); //to create the parameters
 }
CPlotItem::CPlotItem (const CPlotItem & src, const CCopasiContainer * pParent = NULL)
Definition at line 88 of file CPlotItem.cpp.
References mType, and setType().
                                                       :
     CCopasiParameterGroup(src, pParent),
     mType(unset),
     mActivity(),
     mpXMLActivity(NULL),
     channels(src.getChannels())
 {
   setType(src.mType);
 }
CPlotItem::~CPlotItem () virtual
Destructor
Definition at line 147 of file CPlotItem.cpp.
 {}
Member Function Documentation
void CPlotItem::addChannel (const CPlotDataChannelSpec & channel)
Definition at line 223 of file CPlotItem.cpp.
References channels.
Referenced by CQPlotSubwidget::addCurveTab(), CQPlotSubwidget::addHisto1DTab(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), COutputAssistant::createPlot(), and SEDMLImporter::readListOfPlotsFromSedMLOutput().
 {
   channels.push_back(channel);
 }
void CPlotItem::cleanup ()
Definition at line 150 of file CPlotItem.cpp.
Referenced by CPlotSpecification::cleanup().
 {
   //TODO: parametergroup cleanup
 }
const COutputInterface::Activity & CPlotItem::getActivity () const
Definition at line 179 of file CPlotItem.cpp.
References COutputInterface::AFTER, bandedGraph, COutputInterface::BEFORE, curve2d, COutputInterface::DURING, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), histoItem1d, mActivity, mpXMLActivity, mType, CCopasiParameter::Value::pSTRING, surface, toEnum(), and XMLRecordingActivity.
Referenced by CopasiPlot::compile(), Curve2DWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), and CQPlotSubwidget::storeChanges().
 {
   COutputInterface::Activity Activity;
   switch (mType)
     {
       case curve2d:
       case bandedGraph:
       case histoItem1d:
       case surface:
         if (!mpXMLActivity)
           const_cast<CPlotItem *>(this)->mpXMLActivity =
             getParameter("Recording Activity")->getValue().pSTRING;
         Activity = toEnum(mpXMLActivity->c_str(), XMLRecordingActivity, COutputInterface::DURING);
         if (Activity < COutputInterface::BEFORE ||
             (COutputInterface::BEFORE | COutputInterface::DURING | COutputInterface::AFTER) < Activity)
           {
             Activity = COutputInterface::DURING;
             * mpXMLActivity = XMLRecordingActivity[Activity];
           }
         const_cast<CPlotItem *>(this)->mActivity = Activity;
         break;
       default:
         break;
     }
   return mActivity;
 }
std::vector< CPlotDataChannelSpec > & CPlotItem::getChannels ()
Definition at line 214 of file CPlotItem.cpp.
References channels.
Referenced by CopasiPlot::compile(), CSEDMLExporter::createDataGenerators(), CCopasiXMLParser::ListOfChannelsElement::end(), Curve2DWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), CCopasiXML::savePlotList(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), and CQPlotSubwidget::storeChanges().
 {return channels;}
const std::vector< CPlotDataChannelSpec > & CPlotItem::getChannels () const
Definition at line 217 of file CPlotItem.cpp.
References channels.
 {return channels;}
size_t CPlotItem::getNumChannels () const
Definition at line 220 of file CPlotItem.cpp.
References channels.
Referenced by CopasiPlot::compile(), and CCopasiXML::savePlotList().
 {return channels.size();}
const std::string & CPlotItem::getTitle () const
Definition at line 228 of file CPlotItem.cpp.
References CCopasiObject::getObjectName().
Referenced by CQPlotSubwidget::addPlotItem(), COutputHandlerPlot::compile(), PlotWindow::initFromSpec(), CopasiPlot::initFromSpec(), Curve2DWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), CQPlotSubwidget::loadFromPlotSpec(), PlotWindow::PlotWindow(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), CQPlotSubwidget::saveToPlotSpec(), and CQPlotSubwidget::storeChanges().
 {
   return getObjectName();
 }
const CPlotItem::Type & CPlotItem::getType () const
Retrieve the type of the method
Definition at line 158 of file CPlotItem.cpp.
References mType.
Referenced by CQPlotSubwidget::areOfSameType(), CopasiPlot::compile(), Curve2DWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), CQPlotSubwidget::loadFromPlotSpec(), CCopasiXML::savePlotList(), Curve2DWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), CQPlotSubwidget::selectPlotItem(), and CQPlotSubwidget::storeChanges().
 {return mType;}
void CPlotItem::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 155 of file CPlotItem.cpp.
 {}
void CPlotItem::setActivity (const COutputInterface::Activity & activity)
Definition at line 161 of file CPlotItem.cpp.
References bandedGraph, curve2d, histoItem1d, mActivity, mpXMLActivity, mType, surface, and XMLRecordingActivity.
Referenced by COutputAssistant::createDefaultOutput(), Curve2DWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), and CQPlotSubwidget::storeChanges().
 {
   switch (mType)
     {
       case curve2d:
       case bandedGraph:
       case histoItem1d:
       case surface:
         mActivity = activity;
         *mpXMLActivity = XMLRecordingActivity[mActivity];
         break;
       default:
         mActivity = (COutputInterface::Activity) 0;
         break;
     }
 }
void CPlotItem::setTitle (const std::string & title)
Definition at line 233 of file CPlotItem.cpp.
References CCopasiObject::setObjectName().
Referenced by CQPlotSubwidget::addPlotItem(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), CQPlotSubwidget::saveToPlotSpec(), and CQPlotSubwidget::storeChanges().
 {
   setObjectName(title);
 }
void CPlotItem::setType (CPlotItem::Type type)
Definition at line 99 of file CPlotItem.cpp.
References COutputInterface::AFTER, CCopasiParameterGroup::assertParameter(), bandedGraph, COutputInterface::BEFORE, CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameterGroup::clear(), curve2d, CCopasiParameter::DOUBLE, COutputInterface::DURING, CCopasiParameter::getValue(), histoItem1d, mActivity, mpXMLActivity, mType, plot2d, CCopasiParameter::Value::pSTRING, CCopasiParameter::STRING, surface, toEnum(), CCopasiParameter::UDOUBLE, CCopasiParameter::UINT, unset, and XMLRecordingActivity.
Referenced by CPlotItem(), CCopasiXMLParser::PlotSpecificationElement::start(), and CQPlotSubwidget::storeChanges().
 {
   if (type == mType) return;
   if (mType != unset) clear();
   mType = type;
   //create parameters
   if (type == curve2d || type == bandedGraph)
     {
       assertParameter("Line type", CCopasiParameter::UINT, (unsigned C_INT32) 0);
       assertParameter("Line subtype", CCopasiParameter::UINT, (unsigned C_INT32) 0);
       assertParameter("Line width", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0);
       assertParameter("Symbol subtype", CCopasiParameter::UINT, (unsigned C_INT32) 0);
     }
   if (type == histoItem1d)
     {
       assertParameter("increment", CCopasiParameter::DOUBLE, (C_FLOAT64) 1.0);
     }
   if (type == curve2d || type == histoItem1d || type == bandedGraph || type == surface)
     {
       assertParameter("Color", CCopasiParameter::STRING, std::string("auto"));
       mpXMLActivity =
         assertParameter("Recording Activity", CCopasiParameter::STRING, std::string("during"))->getValue().pSTRING;
       mActivity = toEnum(mpXMLActivity->c_str(), XMLRecordingActivity, COutputInterface::DURING);
       if (mActivity < COutputInterface::BEFORE ||
           (COutputInterface::BEFORE | COutputInterface::DURING | COutputInterface::AFTER) < mActivity)
         {
           mActivity = COutputInterface:: DURING;
           * mpXMLActivity = XMLRecordingActivity[mActivity];
         }
     }
   if (type == plot2d)
     {
       assertParameter("log X", CCopasiParameter::BOOL, false);
       assertParameter("log Y", CCopasiParameter::BOOL, false);
       mpXMLActivity = NULL;
       mActivity = (COutputInterface::Activity) 0;
     }
 }
Member Data Documentation
std::vector<CPlotDataChannelSpec> CPlotItem::channels private
Definition at line 135 of file CPlotItem.h.
Referenced by addChannel(), getChannels(), and getNumChannels().
COutputInterface::Activity CPlotItem::mActivity private
The recording activity for items of type curve2d and histoItem1d
Definition at line 128 of file CPlotItem.h.
Referenced by getActivity(), setActivity(), and setType().
std::string* CPlotItem::mpXMLActivity private
A pointer to the string containing the XML representation of the activity
Definition at line 133 of file CPlotItem.h.
Referenced by getActivity(), setActivity(), and setType().
Type CPlotItem::mType private
The type of the method
Definition at line 123 of file CPlotItem.h.
Referenced by CPlotItem(), getActivity(), getType(), setActivity(), and setType().
const std::string CPlotItem::RecordingActivityName static
Initial value:
=
{
  "",
  "Before",
  "During",
  "",
  "After"
}
String literals for the GUI to display recording activity names of plots known to COPASI.
Definition at line 110 of file CPlotItem.h.
const std::string CPlotItem::TypeName static
Initial value:
=
{
  "Unset",
  "2D Curve",
  "Histogram",
  "Banded Graph",
  "Surface",
  "2D Plot",
  "SimWiz",
  ""
}
String literals for the GUI to display plot item names of methods known to COPASI.
Definition at line 99 of file CPlotItem.h.
const char * CPlotItem::XMLRecordingActivity static
Initial value:
=
{
  "NotSet",
  "before",
  "during",
  "before&during",
  "after",
  "before&after",
  "during&after",
  "before&during&after",
  NULL
}
XML recording activity names of plots known to COPASI.
Definition at line 115 of file CPlotItem.h.
Referenced by getActivity(), setActivity(), and setType().
const char * CPlotItem::XMLType static
Initial value:
=
{
  "Unset",
  "Curve2D",
  "Histogram1DItem",
  "BandedGraph",
  "Surface",
  "Plot2D",
  "SimWiz",
  NULL
}
XML sub type names of methods known to COPASI.
Definition at line 104 of file CPlotItem.h.
Referenced by CCopasiXML::savePlotList(), CCopasiXMLParser::PlotItemElement::start(), and CCopasiXMLParser::PlotSpecificationElement::start().
The documentation for this class was generated from the following files:
CPlotItem.h
CPlotItem.cpp