COPASI API: CMathMl Class Reference
CMathMl Class Reference
#include <copasimathml.h>
Static Public Member Functions
static std::string fixName (const std::string &name)
static std::string getMMLName (const CCopasiObject *obj)
Detailed Description
Definition at line 29 of file copasimathml.h.
Member Function Documentation
static std::string CMathMl::fixName (const std::string & name) inline static
Definition at line 33 of file copasimathml.h.
References CCopasiXMLInterface::character, and CCopasiXMLInterface::encode().
Referenced by CFunction::createListOfParametersForMathML(), CMMLOutput::createParameterMapping(), getMMLName(), CEvaluationNodeVariable::getMMLString(), CEvaluationNodeCall::getMMLString(), CMMLOutput::writeDifferentialEquations(), CMMLOutput::writeLHS(), CMMLOutput::writeLHS_ModelValue(), CFunction::writeMathML(), Expression2PresentationMML::writeMathMLFunction(), Expression2PresentationMML::writeMathMLName(), and CMMLOutput::writeRHS().
   {
     std:: string Fixed;
     if (name.find_first_of(" ()*+-") == std::string::npos)
       Fixed = name;
     else
       Fixed = "\"" + name + "\"";
     return CCopasiXMLInterface::encode(Fixed, CCopasiXMLInterface::character);
   }
static std::string CMathMl::getMMLName (const CCopasiObject * obj) inline static
Definition at line 45 of file copasimathml.h.
References fixName(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), and CCopasiObject::getObjectType().
Referenced by CEvaluationNodeObject::getMMLString().
   {
     if (!obj) return "no object";
     //model value
     const CModelValue* mv = dynamic_cast<const CModelValue*>(obj);
     if (mv) return "<mi>" + fixName(mv->getObjectName()) + "</mi>";
     //metabolite
     //const CMetab* met = dynamic_cast<const CMetab*>(obj);
     //if (met) return "<mi>[" + met->getObjectName() + "]</mi>";
     //compartment
     const CCompartment* comp = dynamic_cast<const CCompartment*>(obj);
     if (comp) return "<msub><mi>V</mi><mi>" + fixName(comp->getObjectName())
                        + "</mi></msub>";
     //reference
     if (obj->getObjectType() == "Reference")
       {
         //model value
         if (obj->getObjectName() == "Value")
           {
             mv = dynamic_cast<const CModelValue*>(obj->getObjectParent());
             if (mv) return "<mi>" + fixName(mv->getObjectName()) + "</mi>";
           }
         //compartment
         if (obj->getObjectName() == "Volume")
           {
             comp = dynamic_cast<const CCompartment*>(obj->getObjectParent());
             if (comp) return "<msub><mi>V</mi><mi>" + fixName(comp->getObjectName())
                                + "</mi></msub>";
           }
       }
     return "<mi>" + fixName(obj->getObjectDisplayName()) + "</mi>";
   }
The documentation for this class was generated from the following file:
copasimathml.h