COPASI API: CSort.h File Reference
CSort.h File Reference
#include <cmath>
#include <algorithm>
#include <functional>
#include "utilities/CVector.h"
Classes
class CompareDefault< RandomAccessIterator >
class CompareDoubleWithNaN
class FSwapBase< IndexType, ReturnType >
class FSwapClass< ClassType, IndexType, ReturnType >
Functions
template<typename SwapMethod >
bool applyPartialPivot (const CVector< size_t > &pivot, const size_t &ordered, SwapMethod swap)
template<typename SwapMethod >
bool applyPivot (const CVector< size_t > &pivot, SwapMethod swap)
template<typename RandomAccessIterator >
void partialSortWithPivot (RandomAccessIterator first, RandomAccessIterator middle, RandomAccessIterator last, CVector< size_t > &pivot)
template<typename RandomAccessIterator , typename LessThanCompare >
void partialSortWithPivot (RandomAccessIterator first, RandomAccessIterator middle, RandomAccessIterator last, LessThanCompare compare, CVector< size_t > &pivot)
template<typename RandomAccessIterator >
void sortWithPivot (RandomAccessIterator first, RandomAccessIterator last, CVector< size_t > &pivot)
template<typename RandomAccessIterator , typename LessThanCompare >
void sortWithPivot (RandomAccessIterator first, RandomAccessIterator last, LessThanCompare compare, CVector< size_t > &pivot)
Function Documentation
template<typename SwapMethod > bool applyPartialPivot (const CVector< size_t > & pivot, const size_t & ordered, SwapMethod swap)
Partial reordering of the first 'ordered' elements according to the provided pivots. The swap method must be of the form: ReturnType operator() (size_t to, size_t from) where the ReturnType is not used and therefore arbitrary. Objects of type FSwapBase are suitable candidates.
Parameters
const CVector<size_t> & pivot
const size_t & ordered
SwapMethod swap
Returns
bool success
Definition at line 375 of file CSort.h.
References CVectorCore< CType >::size().
Referenced by COptMethodEP::select(), and COptMethodGA::select().
 {
   CVector< bool > Applied(pivot.size());
   Applied = false;
   size_t i;
   size_t to;
   size_t from;
   for (i = 0; i < ordered; i++)
     if (!Applied[i])
       {
         to = i;
         from = pivot[to];
         while (from != i)
           {
             if (to < ordered || from < ordered)
               {
                 swap(to, from);
                 Applied[to] = true;
                 to = from;
               }
             from = pivot[from];
           }
         Applied[to] = true;
       }
   return true;
 }
template<typename SwapMethod > bool applyPivot (const CVector< size_t > & pivot, SwapMethod swap)
Reorder the elements according to the provided pivots The swap method must be of the form: ReturnType operator() (size_t to, size_t from) where the ReturnType is not used and therefore arbitrary. Objects of type FSwapBase are suitable candidates.
Parameters
const CVector<size_t> & pivot
SwapMethod swap
Returns
bool success
Definition at line 331 of file CSort.h.
References CVectorCore< CType >::size().
 {
   CVector< bool > Applied(pivot.size());
   Applied = false;
   size_t i, imax = pivot.size();
   size_t to;
   size_t from;
   for (i = 0; i < imax; i++)
     if (!Applied[i])
       {
         to = i;
         from = pivot[to];
         while (from != i)
           {
             swap(to, from);
             Applied[to] = true;
             to = from;
             from = pivot[to];
           }
         Applied[to] = true;
       }
   return true;
 }
template<typename RandomAccessIterator > void partialSortWithPivot (RandomAccessIterator first, RandomAccessIterator middle, RandomAccessIterator last, CVector< size_t > & pivot)
Partial sorting method returning a pivot vector instead of performing the sort. The underlying sorting method is std::partial sort with the operator < used for * comparison .
Parameters
RandomAccessIterator first
RandomAccessIterator middle
RandomAccessIterator last
CVector<size_t> & pivot
Definition at line 149 of file CSort.h.
Referenced by COptMethodEP::select(), and COptMethodGA::select().
 {
   CompareDefault<RandomAccessIterator> Compare;
   partialSortWithPivot(first, middle, last, Compare, pivot);
   return;
 }
template<typename RandomAccessIterator , typename LessThanCompare > void partialSortWithPivot (RandomAccessIterator first, RandomAccessIterator middle, RandomAccessIterator last, LessThanCompare compare, CVector< size_t > & pivot)
Partial sorting method returning a pivot vector instead of performing the sort. The underlying sorting method is std::partial_sort with the specified compare method used for comparison .
Parameters
RandomAccessIterator first
RandomAccessIterator middle
RandomAccessIterator last
LessThanCompare method
CVector<size_t> & pivot
Definition at line 172 of file CSort.h.
References CVectorCore< CType >::array(), and CVector< CType >::resize().
 {
   assert(first < middle && middle <= last);
   // Initialize the two column array to be sorted
   CVector<std::pair<RandomAccessIterator, size_t> > ToBeSorted;
   ToBeSorted.resize(last - first);
   RandomAccessIterator it;
   size_t i;
   typename std::pair<RandomAccessIterator, size_t> * itToBeSorted;
   for (it = first, i = 0, itToBeSorted = ToBeSorted.array();
        it != last;
        ++it, ++i, ++itToBeSorted)
     {
       itToBeSorted->first = it;
       itToBeSorted->second = i;
     }
   itToBeSorted = ToBeSorted.array();
   std::partial_sort(itToBeSorted,
                     itToBeSorted + (middle - first),
                     itToBeSorted + (last - first),
                     compare);
   // Copy the resulting pivots to the pivot vector.
   pivot.resize(last - first);
   CVector<size_t>::elementType *itPivot = pivot.array();
   CVector<size_t>::elementType *endPivot = itPivot + (last - first);
   for (; itPivot != endPivot; ++itToBeSorted, ++itPivot)
     *itPivot = itToBeSorted->second;
   return;
 }
template<typename RandomAccessIterator > void sortWithPivot (RandomAccessIterator first, RandomAccessIterator last, CVector< size_t > & pivot)
Sorting method returning a pivot vector instead of performing the sort. The underlying sorting method is std::sort with the operator < used for comparison .
Parameters
RandomAccessIterator first
RandomAccessIterator last
CVector<size_t> & pivot
Definition at line 77 of file CSort.h.
Referenced by CExperiment::read(), and CEigen::stabilityAnalysis().
 {
   CompareDefault<RandomAccessIterator> Compare;
   sortWithPivot(first, last, Compare, pivot);
   return;
 }
template<typename RandomAccessIterator , typename LessThanCompare > void sortWithPivot (RandomAccessIterator first, RandomAccessIterator last, LessThanCompare compare, CVector< size_t > & pivot)
Sorting method returning a pivot vector instead of performing the sort. The underlying sorting method is std::sort with the specified compare method used for comparison .
Parameters
RandomAccessIterator first
RandomAccessIterator last
LessThanCompare method
CVector<size_t> & pivot
Definition at line 98 of file CSort.h.
References CVectorCore< CType >::array(), and CVector< CType >::resize().
 {
   assert(first < last);
   // Initialize the two column array to be sorted
   CVector<std::pair<RandomAccessIterator, size_t> > ToBeSorted;
   ToBeSorted.resize(last - first);
   RandomAccessIterator it;
   size_t i;
   typename std::pair<RandomAccessIterator, size_t> * itToBeSorted;
   for (it = first, i = 0, itToBeSorted = ToBeSorted.array();
        it != last;
        ++it, ++i, ++itToBeSorted)
     {
       itToBeSorted->first = it;
       itToBeSorted->second = i;
     }
   itToBeSorted = ToBeSorted.array();
   std::sort(itToBeSorted,
             itToBeSorted + (last - first),
             compare);
   // Copy the resulting pivots to the pivot vector.
   pivot.resize(last - first);
   CVector<size_t>::elementType *itPivot = pivot.array();
   CVector<size_t>::elementType *endPivot = itPivot + (last - first);
   for (; itPivot != endPivot; ++itToBeSorted, ++itPivot)
     *itPivot = itToBeSorted->second;
   return;
 }