COPASI API: CFunctionAnalyzer Class Reference
CFunctionAnalyzer Class Reference
#include <CFunctionAnalyzer.h>
Classes
class CValue
class Result
Public Types
enum Mode { NOOBJECT, GENERAL, POSITIVE, ACTUAL }
Public Member Functions
CFunctionAnalyzer (const CFunction *f, const CReaction *reaction=NULL)
void checkKineticFunction (const CFunction *f, const CReaction *reaction=NULL)
const Result & getResult () const
Static Public Member Functions
static void constructCallParameters (const CFunctionParameters &fp, std::vector< CValue > &callParameters, bool posi)
static CValue evaluateNode (const CEvaluationNode *node, const std::vector< CValue > &callParameters, Mode mode)
static std::string write (int level, bool rt, const std::string &text, const std::string &longText)
Static Protected Member Functions
static void constructCallParametersActualValues (std::vector< CValue > &callParameters, const CReaction *reaction)
Protected Attributes
Result mResult
Detailed Description
This class performs an analysis of a kinetic function. The function to analyze is passed to the constructor. The result can be retrieved with the getResult() method. The Result class has methods for reporting. The reporting methods may assume that the function (and possibly the reaction) still exists, so don't delete the function between the analysis and the reporting of the results!
Definition at line 44 of file CFunctionAnalyzer.h.
Member Enumeration Documentation
enum CFunctionAnalyzer::Mode
Mode tells how to interpret an object in CValue arithmetics. NOOBJECT means objects are invalid (e.g. for functions, where no object nodes should occur). GENERAL means concentrations and volumes are positive, all other values positive, zero, or negative. POSITIVE means all objects are positive. ACTUAL means the actual value is used for local parameters and constant values.
Enumerator
NOOBJECT
GENERAL
POSITIVE
ACTUAL
Definition at line 204 of file CFunctionAnalyzer.h.
 {NOOBJECT, GENERAL, POSITIVE, ACTUAL };
Constructor & Destructor Documentation
CFunctionAnalyzer::CFunctionAnalyzer (const CFunction * f, const CReaction * reaction = NULL) inline
Definition at line 193 of file CFunctionAnalyzer.h.
References checkKineticFunction().
   {checkKineticFunction(f, reaction);};
Member Function Documentation
void CFunctionAnalyzer::checkKineticFunction (const CFunction * f, const CReaction * reaction = NULL)
Definition at line 1220 of file CFunctionAnalyzer.cpp.
References CFunctionAnalyzer::Result::clear(), constructCallParameters(), constructCallParametersActualValues(), evaluateNode(), CFunctionParameters::getNumberOfParametersByUsage(), CCopasiObject::getObjectName(), getResult(), CEvaluationTree::getRoot(), CFunction::getVariables(), CFunction::isReversible(), CFunctionAnalyzer::Result::mBPart, CFunctionAnalyzer::Result::mFPart, CFunctionAnalyzer::Result::mIrreversibleKineticsWithProducts, CFunctionAnalyzer::Result::mOriginalFunction, CFunctionAnalyzer::Result::mpFunction, CFunctionAnalyzer::Result::FunctionInformation::mProductZero, mResult, CFunctionAnalyzer::Result::mReversibleNonSplitable, CFunctionAnalyzer::Result::FunctionInformation::mSubstrateZero, CFunctionAnalyzer::Result::FunctionInformation::mUnchangedParameters, NOOBJECT, pdelete, CFunctionParameter::PRODUCT, CFunctionParameters::size(), CFunction::splitFunction(), CFunctionParameter::SUBSTRATE, TriFalse, TriTrue, and CFunctionAnalyzer::CValue::zero.
Referenced by CFunctionAnalyzer().
 {
   mResult.clear();
   mResult.mpFunction = f;
   //assume mass action is ok.
   if (dynamic_cast<const CMassAction*>(f)) return;
   if (f->isReversible() == TriFalse)
     if (f->getVariables().getNumberOfParametersByUsage(CFunctionParameter::PRODUCT) > 0)
       {
         // An irreversible kinetics should not depend on products.
         mResult.mIrreversibleKineticsWithProducts = true;
       }
   std::vector<CValue> callParameters;
   CValue tmpValue;
   //***** just the kinetic function *****
   //construct call parameter vector
   constructCallParameters(f->getVariables(), callParameters, false);
   tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
   mResult.mOriginalFunction.mUnchangedParameters.push_back(tmpValue);
   //construct call parameter vector
   constructCallParameters(f->getVariables(), callParameters, true);
   tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
   mResult.mOriginalFunction.mUnchangedParameters.push_back(tmpValue);
   if (reaction)
     {
       //construct call parameter vector
       constructCallParametersActualValues(callParameters, reaction);
       tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
       mResult.mOriginalFunction.mUnchangedParameters.push_back(tmpValue);
     }
   else
     {
     }
   //***** now the kinetic function with single substrates or products == zero ******
   std::vector<CValue> tmpValueVector;
   size_t i, imax = f->getVariables().size();
   for (i = 0; i < imax; ++i)
     {
       if (f->getVariables()[i]->getUsage() == CFunctionParameter::SUBSTRATE)
         {
           tmpValueVector.clear();
           //construct call parameter vector
           constructCallParameters(f->getVariables(), callParameters, false);
           //set one substrate to zero
           callParameters[i] = CValue::zero;
           tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
           tmpValueVector.push_back(tmpValue);
           //construct call parameter vector
           constructCallParameters(f->getVariables(), callParameters, true);
           //set one substrate to zero
           callParameters[i] = CValue::zero;
           tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
           tmpValueVector.push_back(tmpValue);
           if (reaction)
             {
               //construct call parameter vector
               constructCallParametersActualValues(callParameters, reaction);
               //set one substrate to zero
               callParameters[i] = CValue::zero;
               tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
               //test if result is indeed 0 (as is required)
               tmpValueVector.push_back(tmpValue);
             }
           else
             {
             }
           mResult.mOriginalFunction.mSubstrateZero.push_back(std::pair<std::pair<size_t, std::string>, std::vector<CValue> >(std::pair<size_t, std::string>(i, f->getVariables()[i]->getObjectName()), tmpValueVector));
         }
       if (f->getVariables()[i]->getUsage() == CFunctionParameter::PRODUCT)
         {
           tmpValueVector.clear();
           //construct call parameter vector
           constructCallParameters(f->getVariables(), callParameters, false);
           //set one product to zero
           callParameters[i] = CValue::zero;
           tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
           tmpValueVector.push_back(tmpValue);
           //construct call parameter vector
           constructCallParameters(f->getVariables(), callParameters, true);
           //set one substrate to zero
           callParameters[i] = CValue::zero;
           tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
           tmpValueVector.push_back(tmpValue);
           if (reaction)
             {
               //construct call parameter vector
               constructCallParametersActualValues(callParameters, reaction);
               //set one substrate to zero
               callParameters[i] = CValue::zero;
               tmpValue = CFunctionAnalyzer::evaluateNode(f->getRoot(), callParameters, NOOBJECT);
               tmpValueVector.push_back(tmpValue);
             }
           else
             {
             }
           mResult.mOriginalFunction.mProductZero.push_back(std::pair<std::pair<size_t, std::string>, std::vector<CValue> >(std::pair<size_t, std::string>(i, f->getVariables()[i]->getObjectName()), tmpValueVector));
         }
     }
   //try to split reversible functions
   if ((f->isReversible() == TriTrue))
     {
       std::pair<CFunction *, CFunction *> tmp;
       tmp = f->splitFunction(NULL, "f", "b");
       if ((tmp.first == NULL) || (tmp.second == NULL))
         {
           mResult.mReversibleNonSplitable = true;
         }
       else
         {
           CFunctionAnalyzer fa1(tmp.first);
           mResult.mFPart = fa1.getResult().mOriginalFunction;
           CFunctionAnalyzer fa2(tmp.second);
           mResult.mBPart = fa2.getResult().mOriginalFunction;
         }
       pdelete(tmp.first);
       pdelete(tmp.second);
     }
 }
void CFunctionAnalyzer::constructCallParameters (const CFunctionParameters & fp, std::vector< CValue > & callParameters, bool posi) static
constructs call parameters for use with the evaluateNode() method
Definition at line 994 of file CFunctionAnalyzer.cpp.
References CFunctionParameter::MODIFIER, CFunctionParameter::PARAMETER, CFunctionAnalyzer::CValue::positive, CFunctionParameter::PRODUCT, CFunctionParameters::size(), CFunctionParameter::SUBSTRATE, CFunctionParameter::TEMPORARY, CFunctionParameter::TIME, CFunctionAnalyzer::CValue::unknown, CFunctionParameter::VARIABLE, and CFunctionParameter::VOLUME.
Referenced by checkKineticFunction(), and CFunction::splitFunction().
 {
   size_t i, imax = fp.size();
   callParameters.resize(imax);
   for (i = 0; i < imax; ++i)
     {
       CFunctionParameter::Role role = fp[i]->getUsage();
       switch (role)
         {
           case CFunctionParameter::SUBSTRATE:
           case CFunctionParameter::PRODUCT:
           case CFunctionParameter::MODIFIER:
           case CFunctionParameter::VOLUME:
             callParameters[i] = CValue::positive;
             break;
           case CFunctionParameter::TIME:
           case CFunctionParameter::PARAMETER:
           case CFunctionParameter::VARIABLE:
           case CFunctionParameter::TEMPORARY:
             callParameters[i] = posi ? CValue::positive : CValue::unknown;
             break;
         }
     }
 }
void CFunctionAnalyzer::constructCallParametersActualValues (std::vector< CValue > & callParameters, const CReaction * reaction) static protected
constructs call parameters for use with the evaluateNode() method, using the actual values for local parameters and fixed entities.
Definition at line 1023 of file CFunctionAnalyzer.cpp.
References CModelEntity::FIXED, CKeyFactory::get(), CReaction::getFunctionParameters(), CModelEntity::getInitialValue(), CCopasiRootContainer::getKeyFactory(), CReaction::getParameterMappings(), CModelEntity::getStatus(), CCopasiParameter::getValue(), CFunctionParameter::MODIFIER, CFunctionParameter::PARAMETER, CCopasiParameter::Value::pDOUBLE, CFunctionAnalyzer::CValue::positive, CFunctionParameter::PRODUCT, CFunctionParameters::size(), CFunctionParameter::SUBSTRATE, CFunctionParameter::TEMPORARY, CFunctionParameter::TIME, CFunctionAnalyzer::CValue::unknown, CFunctionParameter::VARIABLE, and CFunctionParameter::VOLUME.
Referenced by checkKineticFunction().
 {
   size_t i, imax = reaction->getFunctionParameters().size();
   callParameters.resize(imax);
   for (i = 0; i < imax; ++i)
     {
       const CModelEntity * pME;
       const CCopasiParameter * pCP;
       CFunctionParameter::Role role = reaction->getFunctionParameters()[i]->getUsage();
       switch (role)
         {
           case CFunctionParameter::SUBSTRATE:
           case CFunctionParameter::PRODUCT:
           case CFunctionParameter::MODIFIER:
           case CFunctionParameter::VOLUME:
           case CFunctionParameter::PARAMETER:
             callParameters[i] = CValue::unknown;
             pME = dynamic_cast<const CModelEntity*>(CCopasiRootContainer::getKeyFactory()->get(reaction->getParameterMappings()[i][0]));
             if (pME)
               {
                 if (pME->getStatus() == CModelEntity::FIXED)
                   callParameters[i] = CValue(pME->getInitialValue());
                 else
                   callParameters[i] = CValue::positive;
               }
             pCP = dynamic_cast<const CCopasiParameter*>(CCopasiRootContainer::getKeyFactory()->get(reaction->getParameterMappings()[i][0]));
             if (pCP)
               {
                 callParameters[i] = CValue(*pCP->getValue().pDOUBLE);
               }
             break;
           case CFunctionParameter::TIME:
           case CFunctionParameter::VARIABLE:
           case CFunctionParameter::TEMPORARY:
             callParameters[i] = CValue::unknown;
             break;
         }
     }
 }
CFunctionAnalyzer::CValue CFunctionAnalyzer::evaluateNode (const CEvaluationNode * node, const std::vector< CValue > & callParameters, Mode mode) static
Do the CValue arithmetics of a tree. The callParameters contain the CValues corresponding to the CEvaluationNodeVariable nodes. The value of mode should not have an effect if this is called for a function tree.
Definition at line 1072 of file CFunctionAnalyzer.cpp.
References CEvaluationNode::CALL, CEvaluationNode::CHOICE, CNodeContextIterator< Node, Context >::context(), CEvaluationNodeOperator::DIVIDE, CNodeContextIterator< Node, Context >::end(), CEvaluationNode::FUNCTION, CEvaluationNodeCall::getCalledTree(), CEvaluationNodeVariable::getIndex(), CEvaluationNodeCall::getListOfChildNodes(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CFunction::getVariables(), CFunctionAnalyzer::CValue::invalid, CEvaluationNodeOperator::MINUS, CEvaluationNodeFunction::MINUS, CEvaluationNodeOperator::MULTIPLY, CNodeContextIterator< Node, Context >::next(), NOOBJECT, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CEvaluationNode::OPERATOR, CNodeContextIterator< Node, Context >::parentContextPtr(), CEvaluationNodeOperator::PLUS, CFunctionAnalyzer::CValue::positive, POSITIVE, CEvaluationNodeOperator::POWER, CFunctionParameters::size(), CEvaluationNode::subType(), CEvaluationNode::type(), CFunctionAnalyzer::CValue::unknown, and CEvaluationNode::VARIABLE.
Referenced by checkKineticFunction(), and CEvaluationNode::findTopMinus().
 {
   CNodeContextIterator< const CEvaluationNode, std::vector< CValue > > itNode(pNode);
   CValue Result = CValue::invalid;
   while (itNode.next() != itNode.end())
     {
       if (*itNode == NULL)
         {
           continue;
         }
       switch (CEvaluationNode::type(itNode->getType()))
         {
           case CEvaluationNode::OPERATOR:
             switch ((CEvaluationNodeOperator::SubType) CEvaluationNode::subType(itNode->getType()))
               {
                 case CEvaluationNodeOperator::MULTIPLY:
                   Result = itNode.context()[0] * itNode.context()[1];
                   break;
                 case CEvaluationNodeOperator::DIVIDE:
                   Result = itNode.context()[0] / itNode.context()[1];
                   break;
                 case CEvaluationNodeOperator::PLUS:
                   Result = itNode.context()[0] + itNode.context()[1];
                   break;
                 case CEvaluationNodeOperator::MINUS:
                   Result = itNode.context()[0] - itNode.context()[1];
                   break;
                 case CEvaluationNodeOperator::POWER:
                   Result = itNode.context()[0] ^ itNode.context()[1];
                   break;
                   // case MODULUS:
                   //   Value = (C_FLOAT64) (((size_t) mpLeft->value()) % ((size_t) mpRight->value()));
                   //   break;
                   //
                 default:
                   Result = CValue::unknown;
                   break;
               }
             break;
           case CEvaluationNode::NUMBER:
             Result = itNode->getValue();
             break;
           case CEvaluationNode::VARIABLE:
           {
             const CEvaluationNodeVariable * pENV = static_cast<const CEvaluationNodeVariable*>(*itNode);
             if (callParameters.size() < pENV->getIndex() + 1)
               {
                 Result =  CValue::invalid;
               }
             else
               {
                 Result = callParameters[pENV->getIndex()];
               }
           }
           break;
           case CEvaluationNode::FUNCTION:
             switch ((CEvaluationNodeFunction::SubType) CEvaluationNode::subType(itNode->getType()))
               {
                 case CEvaluationNodeFunction::MINUS:
                   Result = itNode.context()[0].invert();
                   break;
                 default:
                   Result = CValue::unknown;
                   break;
               }
             break;
           case CEvaluationNode::CHOICE:
             //TODO: implement
             Result = CValue::unknown;
             break;
           case CEvaluationNode::CALL:
           {
             const CEvaluationNodeCall * pENCall = static_cast<const CEvaluationNodeCall*>(*itNode);
             //some checks
             if (pENCall->getCalledTree() && pENCall->getCalledTree()->getRoot())
               {
                 const CFunction * tmpFunc = dynamic_cast<const CFunction*>(pENCall->getCalledTree());
                 if (tmpFunc && tmpFunc->getVariables().size() == pENCall->getListOfChildNodes().size())
                   {
                     Result = evaluateNode(pENCall->getCalledTree()->getRoot(), itNode.context(), mode);
                   }
                 else
                   {
                     Result = CValue::invalid;
                   }
               }
             else
               {
                 Result = CValue::invalid;
               }
           }
           break;
           case CEvaluationNode::OBJECT:
             if (mode == NOOBJECT)
               {
                 Result = CValue::invalid;
               }
             else if (mode == POSITIVE)
               {
                 Result = CValue::positive;
               }
             else
               {
                 //TODO: implement GENERAL and ACTUAL
                 Result = CValue::unknown;
               }
             break;
           default:
             Result = CValue::unknown;
             break;
         }
       if (itNode.parentContextPtr() != NULL)
         {
           itNode.parentContextPtr()->push_back(Result);
         }
     }
   return Result;
 }
const Result& CFunctionAnalyzer::getResult () const inline
Definition at line 196 of file CFunctionAnalyzer.h.
References mResult.
Referenced by checkKineticFunction().
 {return mResult;};
std::string CFunctionAnalyzer::write (int level, bool rt, const std::string & text, const std::string & longText) static
Definition at line 1364 of file CFunctionAnalyzer.cpp.
Referenced by CFunctionAnalyzer::Result::FunctionInformation::writeAnalysis(), CModelAnalyzer::ReactionResult::writeResult(), and CFunctionAnalyzer::Result::writeResult().
 {
   std::string color;
   switch (level)
     {
       case 0: color = "\"#008000\""; break;
       case 1: color = "\"#909000\""; break;
       case 2: color = "\"#800000\""; break;
       case 3: color = "\"#c04040\""; break;
       default: color = "\"#0000a0\""; break;
     }
   std::string ret;
   if (rt) ret += "<p><font color=" + color + ">";
   ret += (text + "\n");
   if (longText != "")
     {
       if (rt) ret += "<br>";
       ret += longText + "\n";
     }
   if (rt) ret += "</font></p>";
   return ret;
 }
Member Data Documentation
Result CFunctionAnalyzer::mResult protected
Definition at line 220 of file CFunctionAnalyzer.h.
Referenced by checkKineticFunction(), and getResult().
The documentation for this class was generated from the following files:
CFunctionAnalyzer.h
CFunctionAnalyzer.cpp