COPASI API: CScanTask Class Reference
CScanTask Class Reference
#include <CScanTask.h>
Public Member Functions
void cleanup ()
virtual CCopasiMethod * createMethod (const int &type) const
CScanTask (const CCopasiContainer *pParent=NULL)
CScanTask (const CScanTask &src, const CCopasiContainer *pParent=NULL)
void fixBuild81 ()
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
void load (CReadConfig &configBuffer)
bool outputSeparatorCallback (bool isLast=false)
virtual bool process (const bool &useInitialValues)
bool processCallback ()
virtual bool restore ()
~CScanTask ()
Public Member Functions inherited from CCopasiTask
CCopasiTask (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const Type &taskType, const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const CCopasiTask &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
CProcessReport * getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
Type getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setMethodType (const int &type)
void setScheduled (const bool &scheduled)
void setType (const Type &type)
void setUpdateModel (const bool &updateModel)
virtual bool updateMatrices ()
virtual ~CCopasiTask ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Member Functions
bool initSubtask (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Private Attributes
size_t mhProgress
bool mOutputInSubtask
unsigned C_INT32 mProgress
CCopasiTask * mpSubtask
bool mUseInitialValues
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01, STREAM = 0x02, FINISH = 0x04, REPORT = 0x10,
PLOT = 0x20, TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0, OUTPUT_BEFORE = INITIALIZE, OUTPUT_AFTER = FINISH, OUTPUT = REPORT | PLOT | STREAM,
OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH, OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH, ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
enum Type {
steadyState = 0, timeCourse, scan, fluxMode,
optimization, parameterFitting, mca, lyap,
tssAnalysis, sens, moieties, crosssection,
lna, unset
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiTask
static bool isValidMethod (const unsigned int &method, const unsigned int *validMethods)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Static Public Attributes inherited from CCopasiTask
static const std::string TypeName []
static const unsigned int ValidMethods []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
std::string mKey
unsigned C_INT32 mOutputCounter
CProcessReport * mpCallBack
CState * mpInitialState
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
Type mType
bool mUpdateModel
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 34 of file CScanTask.h.
Constructor & Destructor Documentation
CScanTask::CScanTask (const CCopasiContainer * pParent = NULL)
default constructor
CScanTask class.
This class implements a scan task which is comprised of a of a problem and a method.
Definition at line 47 of file CScanTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiMethod::scanMethod.
                                                     :
   CCopasiTask(CCopasiTask::scan, pParent),
   mProgress(0),
   mhProgress(C_INVALID_INDEX),
   mpSubtask(NULL),
   mOutputInSubtask(false),
   mUseInitialValues(true)
 {
   mpProblem = new CScanProblem(this);
   mpMethod = createMethod(CCopasiMethod::scanMethod);
   this->add(mpMethod, true);
   static_cast< CScanMethod * >(mpMethod)->setProblem(static_cast< CScanProblem * >(mpProblem));
 }
CScanTask::CScanTask (const CScanTask & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CScanTask & src
Definition at line 61 of file CScanTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiMethod::scanMethod.
                                                       :
   CCopasiTask(src, pParent),
   mProgress(0),
   mhProgress(C_INVALID_INDEX),
   mpSubtask(NULL),
   mOutputInSubtask(false),
   mUseInitialValues(true)
 {
   mpProblem = new CScanProblem(*(CScanProblem *) src.mpProblem, this);
   mpMethod = createMethod(CCopasiMethod::scanMethod);
   this->add(mpMethod, true);
   static_cast< CScanMethod * >(mpMethod)->setProblem(static_cast< CScanProblem * >(mpProblem));
 }
CScanTask::~CScanTask ()
Destructor
Definition at line 76 of file CScanTask.cpp.
References cleanup().
 {cleanup();}
Member Function Documentation
void CScanTask::cleanup ()
cleanup()
Definition at line 87 of file CScanTask.cpp.
Referenced by ~CScanTask().
 {}
CCopasiMethod * CScanTask::createMethod (const int & type) const virtual
Create a method of the specified type to solve the task. It is the duty of the caller to release the CCopasiMethod.
Parameters
const CCopasiMethod::SubType & type
Returns
CCopasiMethod *
Reimplemented from CCopasiTask.
Definition at line 80 of file CScanTask.cpp.
References CScanMethod::createMethod().
Referenced by CScanTask().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   return CScanMethod::createMethod(Type);
 }
void CScanTask::fixBuild81 ()
Fix files written with Version 4.12.81 and earlier, which wrote the exp(mean) and exp(std. deviation) for normal random distributions in the scan task.
Definition at line 322 of file CScanTask.cpp.
References CScanProblem::fixBuild81(), and CCopasiTask::mpProblem.
Referenced by CCopasiXML::fixBuild81().
 {
   CScanProblem * pProblem = dynamic_cast< CScanProblem * >(mpProblem);
   if (pProblem == NULL) return;
   pProblem->fixBuild81();
   return;
 }
bool CScanTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 90 of file CScanTask.cpp.
References COutputHandler::addInterface(), CCopasiMessage::COMMANDLINE, CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectName(), CReport::getStream(), CCopasiTask::initialize(), initSubtask(), CCopasiMethod::isValidProblem(), MCCopasiTask, CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::mReport, CReport::open(), and CCopasiTask::REPORT.
 {
   assert(mpProblem && mpMethod);
   mpMethod->isValidProblem(mpProblem);
   bool success = true;
   if ((of & REPORT) &&
       pOutputHandler != NULL)
     {
       if (mReport.open(getObjectDataModel(), pOstream))
         pOutputHandler->addInterface(&mReport);
       else
         CCopasiMessage(CCopasiMessage::COMMANDLINE, MCCopasiTask + 5, getObjectName().c_str());
     }
   success &= initSubtask(of, pOutputHandler, mReport.getStream());
   success &= CCopasiTask::initialize(of, pOutputHandler, mReport.getStream());
   return success;
 }
bool CScanTask::initSubtask (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) protected
Init the subtask
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
Returns
success
Definition at line 235 of file CScanTask.cpp.
References CCopasiTask::crosssection, fatalError, CScanProblem::getContinueFromCurrentState(), CCopasiDataModel::getModel(), CCopasiObject::getObjectDataModel(), CCopasiTask::getProblem(), CCopasiDataModel::getTaskList(), CCopasiParameterGroup::getValue(), CCopasiTask::initialize(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, mOutputInSubtask, CCopasiTask::mpProblem, mpSubtask, mUseInitialValues, CCopasiTask::NO_OUTPUT, CCopasiTask::optimization, CCopasiTask::OUTPUT, CCopasiTask::parameterFitting, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pUINT, CCopasiTask::sens, CCopasiTask::setCallBack(), CCopasiProblem::setModel(), CCopasiTask::steadyState, CCopasiTask::timeCourse, CCopasiTask::tssAnalysis, and CCopasiTask::TypeName.
Referenced by initialize().
 {
   if (!mpProblem) fatalError();
   CScanProblem * pProblem = dynamic_cast<CScanProblem *>(mpProblem);
   if (!pProblem) fatalError();
   //get the parameters from the problem
   CCopasiTask::Type type = *(CCopasiTask::Type*) pProblem->getValue("Subtask").pUINT;
   CCopasiDataModel* pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   switch (type)
     {
       case CCopasiTask::steadyState:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Steady-State"]);
         break;
       case CCopasiTask::timeCourse:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Time-Course"]);
         break;
       case CCopasiTask::mca:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Metabolic Control Analysis"]);
         break;
       case CCopasiTask::lyap:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Lyapunov Exponents"]);
         break;
       case CCopasiTask::optimization:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Optimization"]);
         break;
       case CCopasiTask::parameterFitting:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Parameter Estimation"]);
         break;
       case CCopasiTask::sens:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Sensitivities"]);
         break;
       case CCopasiTask::lna:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Linear Noise Approximation"]);
         break;
       case CCopasiTask::tssAnalysis :
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())[CCopasiTask::TypeName[tssAnalysis]]);
         break;
       case CCopasiTask::crosssection:
         mpSubtask = dynamic_cast<CCopasiTask*>
                     ((*pDataModel->getTaskList())["Cross Section"]);
         break;
       default:
         mpSubtask = NULL;
     }
   mOutputInSubtask = * pProblem->getValue("Output in subtask").pBOOL;
   mUseInitialValues = !pProblem->getContinueFromCurrentState();
   if (!mpSubtask) return false;
   mpSubtask->getProblem()->setModel(pDataModel->getModel()); //TODO
   mpSubtask->setCallBack(NULL);
   if (mOutputInSubtask)
     return mpSubtask->initialize(OUTPUT, pOutputHandler, pOstream);
   else
     return mpSubtask->initialize(NO_OUTPUT, pOutputHandler, pOstream);
   return true;
 }
void CScanTask::load (CReadConfig & configBuffer)
Loads parameters for this solver with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
configbuffer reference to a CReadConfig object.
Definition at line 115 of file CScanTask.cpp.
 {}
bool CScanTask::outputSeparatorCallback (bool isLast = false)
output separators if isLast==true this method has to decide if a separator should be generated dependent on mOutputInSubtask.
Definition at line 227 of file CScanTask.cpp.
References COutputInterface::DURING, mOutputInSubtask, and CCopasiTask::separate().
 {
   if ((!isLast) || mOutputInSubtask)
     separate(COutputInterface::DURING);
   return true;
 }
bool CScanTask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 118 of file CScanTask.cpp.
References CProcessReport::addItem(), COutputInterface::AFTER, CModel::applyInitialValues(), COutputInterface::BEFORE, C_INT32, CCrossSectionTask::createEvent(), fatalError, CCopasiProblem::getModel(), CScanMethod::getTotalNumberOfSteps(), CScanMethod::init(), mhProgress, CCopasiTask::mpCallBack, CCopasiTask::mpMethod, CCopasiTask::mpProblem, mProgress, mpSubtask, CCopasiTask::output(), CCrossSectionTask::removeEvent(), CScanMethod::scan(), CCopasiTask::setCallBack(), CProcessReport::setName(), and CScanMethod::setProblem().
 {
   if (!mpProblem) fatalError();
   if (!mpMethod) fatalError();
   CScanProblem * pProblem = dynamic_cast<CScanProblem *>(mpProblem);
   if (!pProblem) fatalError();
   CScanMethod * pMethod = dynamic_cast<CScanMethod *>(mpMethod);
   if (!pMethod) fatalError();
   bool success = true;
   CCrossSectionTask* task = dynamic_cast<CCrossSectionTask*>(mpSubtask);
   if (task != NULL)
     task->createEvent();
   if (useInitialValues)
     {
       mpProblem->getModel()->applyInitialValues();
     }
   //TODO: reports
   // initialize the method (parsing the ScanItems)
   pMethod->setProblem(pProblem);
   if (!pMethod->init()) return false;
   // init progress bar
   mProgress = 0;
   if (mpCallBack)
     {
       mpCallBack->setName("performing parameter scan...");
       unsigned C_INT32 totalSteps = (unsigned C_INT32) pMethod->getTotalNumberOfSteps();
       mhProgress = mpCallBack->addItem("Number of Steps",
                                        mProgress,
                                        &totalSteps);
       if (mpSubtask)
         mpSubtask->setCallBack(mpCallBack);
     }
   // init output handler (plotting)
   output(COutputInterface::BEFORE);
   //calling the scanner, output is done in the callback
   if (!pMethod->scan()) success = false;
   if (task != NULL)
     task->removeEvent();
   //finishing progress bar and output
   //if (mpCallBack) mpCallBack->finish();
   //if (mpOutputHandler) mpOutputHandler->finish();
   output(COutputInterface::AFTER);
   if (mpSubtask)
     mpSubtask->setCallBack(NULL);
   return success;
 }
bool CScanTask::processCallback ()
Do the subtask and the output
Definition at line 201 of file CScanTask.cpp.
References COutputInterface::DURING, CCopasiTask::getProblem(), CCopasiTask::isUpdateModel(), mhProgress, mOutputInSubtask, CCopasiTask::mpCallBack, mProgress, mpSubtask, mUseInitialValues, CCopasiTask::output(), CCopasiTask::process(), CProcessReport::progressItem(), and COptProblem::restoreModel().
Referenced by CScanMethod::calculate().
 {
   bool success = mpSubtask->process(mUseInitialValues);
   //do output
   if (success && !mOutputInSubtask)
     output(COutputInterface::DURING);
   if (mpSubtask->isUpdateModel())
     {
       COptProblem* problem = dynamic_cast<COptProblem*>(mpSubtask->getProblem());
       if (problem != NULL)
         {
           problem->restoreModel(true);
         }
     }
   //do progress bar
   ++mProgress;
   if (mpCallBack) return mpCallBack->progressItem(mhProgress);
   return true;
 }
bool CScanTask::restore () virtual
Perform necessary cleanup procedures
Reimplemented from CCopasiTask.
Definition at line 187 of file CScanTask.cpp.
References mpSubtask, and CCopasiTask::restore().
 {
   bool success = true;
   if (mpSubtask != NULL)
     {
       success &= mpSubtask->restore();
     }
   success = CCopasiTask::restore();
   return success;
 }
Member Data Documentation
size_t CScanTask::mhProgress private
Handle to process item
Definition at line 52 of file CScanTask.h.
Referenced by process(), and processCallback().
bool CScanTask::mOutputInSubtask private
Definition at line 59 of file CScanTask.h.
Referenced by initSubtask(), outputSeparatorCallback(), and processCallback().
unsigned C_INT32 CScanTask::mProgress private
Pointer to the output stream for reporting for progress bar
Definition at line 47 of file CScanTask.h.
Referenced by process(), and processCallback().
CCopasiTask* CScanTask::mpSubtask private
the subtask
Definition at line 57 of file CScanTask.h.
Referenced by initSubtask(), process(), processCallback(), and restore().
bool CScanTask::mUseInitialValues private
Definition at line 61 of file CScanTask.h.
Referenced by initSubtask(), and processCallback().
The documentation for this class was generated from the following files:
CScanTask.h
CScanTask.cpp