COPASI API: CRDFWriter Class Reference
CRDFWriter Class Reference
#include <CRDFWriter.h>
Public Member Functions
CRDFWriter ()
char * write (const CRDFGraph *pGraph)
~CRDFWriter ()
Static Public Member Functions
static std::string xmlFromGraph (const CRDFGraph *pGraph)
Private Member Functions
void initNamespaces (const CRDFGraph *pGraph)
Private Member Functions inherited from CRaptorInit
CRaptorInit ()
~CRaptorInit ()
Private Attributes
CRDFGraph * mpGraph
raptor_serializer * mpWriter
Additional Inherited Members
Static Private Member Functions inherited from CRaptorInit
static bool isLocalURI (raptor_uri *pURI)
Detailed Description
Definition at line 26 of file CRDFWriter.h.
Constructor & Destructor Documentation
CRDFWriter::CRDFWriter ()
Constructor
Definition at line 43 of file CRDFWriter.cpp.
References mpWriter.
                       :
   CRaptorInit(),
   mpWriter(NULL),
   mpGraph(NULL)
 {
   mpWriter = raptor_new_serializer("rdfxml-abbrev");
   // We do not want <?xml version="1.0" encoding="utf-8"?>
   raptor_serializer_set_feature(mpWriter, RAPTOR_FEATURE_WRITER_XML_DECLARATION, 0);
   // Remove any empty elements
   raptor_serializer_set_feature(mpWriter, RAPTOR_FEATURE_WRITER_AUTO_EMPTY, 1);
 }
CRDFWriter::~CRDFWriter ()
Destructor
Definition at line 57 of file CRDFWriter.cpp.
References mpWriter.
 {
   if (mpWriter != NULL)
     {
       raptor_free_serializer(mpWriter);
       mpWriter = NULL;
     }
 }
Member Function Documentation
void CRDFWriter::initNamespaces (const CRDFGraph * pGraph) private
This adds the default name spaces to the writer
Parameters
const CRDFGraph * pGraph
Definition at line 66 of file CRDFWriter.cpp.
References CRDFGraph::getNameSpaceMap(), mpWriter, and pRaptorFreeUri.
Referenced by write().
 {
   std::map< std::string, std::string >::const_iterator it =
     pGraph->getNameSpaceMap().begin();
   std::map< std::string, std::string >::const_iterator end =
     pGraph->getNameSpaceMap().end();
   raptor_uri* pURI = NULL;
   for (; it != end; ++it)
     {
       pURI = raptor_new_uri((const unsigned char *) it->second.c_str());
       raptor_serialize_set_namespace(mpWriter, pURI, (const unsigned char *) it->first.c_str());
       pRaptorFreeUri(pURI);
     }
 }
char * CRDFWriter::write (const CRDFGraph * pGraph)
Convert an RDF graph to an XML string. It is the repsonsibility of user to free the allocate memory for the string. If the conversion fails a NULL pointer is returned.
Parameters
const CRDFGraph * pGraph
Returns
char * XML
Definition at line 83 of file CRDFWriter.cpp.
References CRDFSubject::BLANK_NODE, CRDFObject::BLANK_NODE, fatalError, CRDFSubject::getBlankNodeID(), CRDFObject::getBlankNodeID(), CRDFLiteral::getDataType(), CRDFLiteral::getLanguage(), CRDFLiteral::getLexicalData(), CRDFObject::getLiteral(), CRDFSubject::getResource(), CRDFObject::getResource(), CRDFGraph::getTriplets(), CRDFLiteral::getType(), CRDFSubject::getType(), CRDFObject::getType(), initNamespaces(), CRDFObject::LITERAL, mpWriter, CRDFLiteral::PLAIN, pRaptorFreeUri, CRDFSubject::RESOURCE, CRDFObject::RESOURCE, and CRDFLiteral::TYPED.
 {
   bool success = true;
   void * XML;     /* destination for string */
   size_t Length;  /* length of constructed string */
   initNamespaces(pGraph);
   raptor_uri * pURI = raptor_new_uri((const unsigned char *) "");
   if (raptor_serialize_start_to_string(mpWriter, pURI, & XML, & Length))
     fatalError();
   // We need to add all triplets
   std::set< CRDFTriplet >::const_iterator it = pGraph->getTriplets().begin();
   std::set< CRDFTriplet >::const_iterator end = pGraph->getTriplets().end();
   raptor_uri * pSubjectURI = NULL;
   raptor_uri * pPredicateURI = NULL;
   raptor_uri * pObjectURI = NULL;
   raptor_uri * pLiteralDataTypeURI = NULL;
   raptor_statement Triplet;
   for (; it != end; ++it)
     {
       // Set the subject of the triplet
       const CRDFSubject & Subject = it->pSubject->getSubject();
       switch (Subject.getType())
         {
           case CRDFSubject::RESOURCE:
             Triplet.subject_type = RAPTOR_IDENTIFIER_TYPE_RESOURCE;
             pSubjectURI = raptor_new_uri((const unsigned char *) Subject.getResource().c_str());
             Triplet.subject = pSubjectURI;
             break;
           case CRDFSubject::BLANK_NODE:
             Triplet.subject_type = RAPTOR_IDENTIFIER_TYPE_ANONYMOUS;
             Triplet.subject = Subject.getBlankNodeID().c_str();
             break;
         }
       // Set the predicate of the triplet
       Triplet.predicate_type = RAPTOR_IDENTIFIER_TYPE_RESOURCE;
       pPredicateURI = raptor_new_uri((const unsigned char *) it->Predicate.getURI().c_str());
       Triplet.predicate = pPredicateURI;
       // Set the object of the triplet
       const CRDFObject & Object = it->pObject->getObject();
       switch (Object.getType())
         {
           case CRDFObject::RESOURCE:
             Triplet.object_type = RAPTOR_IDENTIFIER_TYPE_RESOURCE;
             pObjectURI = raptor_new_uri((const unsigned char *) Object.getResource().c_str());
             Triplet.object = pObjectURI;
             break;
           case CRDFObject::BLANK_NODE:
             Triplet.object_type = RAPTOR_IDENTIFIER_TYPE_ANONYMOUS;
             Triplet.object = Object.getBlankNodeID().c_str();
             break;
           case CRDFObject::LITERAL:
             Triplet.object_type = RAPTOR_IDENTIFIER_TYPE_LITERAL;
             const CRDFLiteral & Literal = Object.getLiteral();
             switch (Literal.getType())
               {
                 case CRDFLiteral::TYPED:
                   pLiteralDataTypeURI = raptor_new_uri((const unsigned char *) Literal.getDataType().c_str());
                   Triplet.object_literal_datatype = pLiteralDataTypeURI;
                   Triplet.object_literal_language = NULL;
                   break;
                 case CRDFLiteral::PLAIN:
                   Triplet.object_literal_datatype = NULL;
                   if (Literal.getLanguage() != "")
                     Triplet.object_literal_language = (const unsigned char *) Literal.getLanguage().c_str();
                   else
                     Triplet.object_literal_language = NULL;
                   break;
               }
             Triplet.object = Literal.getLexicalData().c_str();
             break;
         }
       if (raptor_serialize_statement(mpWriter, &Triplet))
         success = false;
       pRaptorFreeUri(pPredicateURI);
       pRaptorFreeUri(pObjectURI);
       pRaptorFreeUri(pLiteralDataTypeURI);
       pRaptorFreeUri(pSubjectURI);
     }
   if (raptor_serialize_end(mpWriter))
     fatalError();
   return static_cast< char * >(XML);
 }
std::string CRDFWriter::xmlFromGraph (const CRDFGraph * pGraph) static
Convert an RDF graph to an XML string
Parameters
const CRDFGraph * pGraph
Returns
std::string
Definition at line 26 of file CRDFWriter.cpp.
Referenced by CMIRIAMInfo::save(), and CRDFGraphConverter::SBML2Copasi().
 {
   CRDFWriter Writer;
   char * pXML = Writer.CRDFWriter::write(pGraph);
   if (pXML != NULL)
     {
       std::string XML = pXML;
       free(pXML);
       return XML;
     }
   return "";
 }
Member Data Documentation
CRDFGraph* CRDFWriter::mpGraph private
A pointer to the created RDF graph
Definition at line 73 of file CRDFWriter.h.
raptor_serializer* CRDFWriter::mpWriter private
Pointer to the underlying C serializer from the Raptor library
Definition at line 68 of file CRDFWriter.h.
Referenced by CRDFWriter(), initNamespaces(), write(), and ~CRDFWriter().
The documentation for this class was generated from the following files:
CRDFWriter.h
CRDFWriter.cpp