COPASI API: CTruncatedNewton.cpp File Reference
CTruncatedNewton.cpp File Reference
#include <cmath>
#include "copasi.h"
#include "CTruncatedNewton.h"
#include "lapack/blaswrap.h"
#include "lapack/lapackwrap.h"
Macros
#define FALSE_ (0)
#define subscr_1 (mpsubscr_->_1)
#define subscr_2 (mpsubscr_->_2)
#define subscr_3 (mpsubscr_->_3)
#define TRUE_ (1)
Functions
int chkucp_ (C_INT *, C_INT *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *)
int cnvtst_ (C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *, C_FLOAT64 *)
int crash_ (C_INT *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_INT *)
int dxpy_ (C_INT *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_INT *)
int initp3_ (C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *)
int lsout_ (C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *)
C_FLOAT64 mchpr1_ (void)
int modz_ (C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *)
int monit_ (C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *, C_INT *, C_INT *, C_INT *)
int mslv_ (C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_INT *)
int ndia3_ (C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *)
int negvec_ (C_INT *, C_FLOAT64 *)
C_FLOAT64 pow_dd (C_FLOAT64 *ap, C_FLOAT64 *bp)
int ssbfgs_ (C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *)
C_FLOAT64 step1_ (C_FLOAT64 *fnew, C_FLOAT64 *fm, C_FLOAT64 *gtp, C_FLOAT64 *smax)
int stpmax_ (C_FLOAT64 *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *, C_INT *, C_FLOAT64 *, C_FLOAT64 *)
int ztime_ (C_INT *, C_FLOAT64 *, C_INT *)
Variables
static C_INT c__1 = 1
static C_FLOAT64 c_b246 = .6666
static C_INT c_false = (0)
static C_INT c_true = (1)
Macro Definition Documentation
#define FALSE_ (0)
Definition at line 79 of file CTruncatedNewton.cpp.
Referenced by cnvtst_(), CTruncatedNewton::getptc_(), CTruncatedNewton::gtims_(), CTruncatedNewton::lmqn_(), and CTruncatedNewton::lmqnbc_().
#define subscr_1 (mpsubscr_->_1)
Definition at line 73 of file CTruncatedNewton.cpp.
Referenced by CTruncatedNewton::lmqn_(), and CTruncatedNewton::lmqnbc_().
#define subscr_2 (mpsubscr_->_2)
Definition at line 74 of file CTruncatedNewton.cpp.
Referenced by CTruncatedNewton::gtims_(), CTruncatedNewton::initpc_(), and CTruncatedNewton::msolve_().
#define subscr_3 (mpsubscr_->_3)
Definition at line 75 of file CTruncatedNewton.cpp.
Referenced by CTruncatedNewton::setpar_().
#define TRUE_ (1)
Definition at line 78 of file CTruncatedNewton.cpp.
Referenced by cnvtst_(), CTruncatedNewton::getptc_(), CTruncatedNewton::lmqn_(), CTruncatedNewton::lmqnbc_(), and CTruncatedNewton::modlnp_().
Function Documentation
int chkucp_ (C_INT * lwtest, C_INT * maxfun, C_INT * nwhy, C_INT * n, C_FLOAT64 * alpha, C_FLOAT64 * epsmch, C_FLOAT64 * eta, C_FLOAT64 * peps, C_FLOAT64 * rteps, C_FLOAT64 * rtol, C_FLOAT64 * rtolsq, C_FLOAT64 * stepmx, C_FLOAT64 * test, C_FLOAT64 * xtol, C_FLOAT64 * xnorm, C_FLOAT64 * x, C_INT * lw, C_FLOAT64 * small, C_FLOAT64 * tiny, C_FLOAT64 * accrcy)
Definition at line 2191 of file CTruncatedNewton.cpp.
References c__1, c_b246, dnrm2_(), and mchpr1_().
Referenced by CTruncatedNewton::lmqn_(), and CTruncatedNewton::lmqnbc_().
 {
   /* Local variables */
   /* CHECKS PARAMETERS AND SETS CONSTANTS WHICH ARE COMMON TO BOTH */
   /* DERIVATIVE AND NON-DERIVATIVE ALGORITHMS */
   /* Parameter adjustments */
   --x;
   /* Function Body */
   *epsmch = mchpr1_();
   *small = *epsmch * *epsmch;
   *tiny = *small;
   *nwhy = -1;
   *rteps = sqrt(*epsmch);
   *rtol = *xtol;
   if (fabs(*rtol) < *accrcy)
     {
       *rtol = *rteps * 10.;
     }
   /* CHECK FOR ERRORS IN THE INPUT PARAMETERS */
   if (*lw < *lwtest || *n < 1 || *rtol < 0. || *eta >= 1. || *eta < 0. || *
       stepmx < *rtol || *maxfun < 1)
     {
       return 0;
     }
   *nwhy = 0;
   /* SET CONSTANTS FOR LATER */
   *rtolsq = *rtol * *rtol;
   *peps = pow(*accrcy, c_b246);
   *xnorm = dnrm2_(n, &x[1], &c__1);
   *alpha = 0.;
   *test = 0.;
   return 0;
 } /* chkucp_ */
int cnvtst_ (C_INT * conv, C_FLOAT64 * alpha, C_FLOAT64 * pnorm, C_FLOAT64 * toleps, C_FLOAT64 * xnorm, C_FLOAT64 * difnew, C_FLOAT64 * rtleps, C_FLOAT64 * ftest, C_FLOAT64 * gtg, C_FLOAT64 * peps, C_FLOAT64 * , C_FLOAT64 * gtpnew, C_FLOAT64 * fnew, C_FLOAT64 * flast, C_FLOAT64 * g, C_INT * ipivot, C_INT * n, C_FLOAT64 * accrcy)
Definition at line 1510 of file CTruncatedNewton.cpp.
References C_FLOAT64, C_INT, FALSE_, and TRUE_.
Referenced by CTruncatedNewton::lmqnbc_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_FLOAT64 cmax;
   C_INT imax, i__;
   C_FLOAT64 t;
   C_INT ltest;
   C_FLOAT64 one;
   /* TEST FOR CONVERGENCE */
   /* Parameter adjustments */
   --ipivot;
   --g;
   /* Function Body */
   imax = 0;
   cmax = 0.;
   ltest = *flast - *fnew <= *gtpnew * -.5;
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (ipivot[i__] == 0 || ipivot[i__] == 2)
         {
           goto L10;
         }
       t = -ipivot[i__] * g[i__];
       if (t >= 0.)
         {
           goto L10;
         }
       *conv = FALSE_;
       if (ltest)
         {
           goto L10;
         }
       if (cmax <= t)
         {
           goto L10;
         }
       cmax = t;
       imax = i__;
 L10:
       ;
     }
   if (imax == 0)
     {
       goto L15;
     }
   ipivot[imax] = 0;
   *flast = *fnew;
   return 0;
 L15:
   *conv = FALSE_;
   one = 1.;
   if ((*alpha * *pnorm >= *toleps * (one + *xnorm) || fabs(*difnew) >= *
        rtleps * *ftest || *gtg >= *peps * *ftest * *ftest) && *gtg >= *
       accrcy * 1e-4 * *ftest * *ftest)
     {
       return 0;
     }
   *conv = TRUE_;
   /* FOR DETAILS, SEE GILL, MURRAY, AND WRIGHT (1981, P. 308) AND */
   /* FLETCHER (1981, P. 116).  THE MULTIPLIER TESTS (HERE, TESTING */
   /* THE SIGN OF THE COMPONENTS OF THE GRADIENT) MAY STILL NEED TO */
   /* MODIFIED TO INCORPORATE TOLERANCES FOR ZERO. */
   return 0;
 } /* cnvtst_ */
int crash_ (C_INT * n, C_FLOAT64 * x, C_INT * ipivot, C_FLOAT64 * low, C_FLOAT64 * up, C_INT * ier)
Definition at line 1600 of file CTruncatedNewton.cpp.
References C_INT.
Referenced by CTruncatedNewton::lmqnbc_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i__;
   /* THIS INITIALIZES THE CONSTRAINT INFORMATION, AND ENSURES THAT THE */
   /* INITIAL POINT SATISFIES  LOW <= X <= UP. */
   /* THE CONSTRAINTS ARE CHECKED FOR CONSISTENCY. */
   /* Parameter adjustments */
   --up;
   --low;
   --ipivot;
   --x;
   /* Function Body */
   *ier = 0;
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (x[i__] < low[i__])
         {
           x[i__] = low[i__];
         }
       if (x[i__] > up[i__])
         {
           x[i__] = up[i__];
         }
       ipivot[i__] = 0;
       if (x[i__] == low[i__])
         {
           ipivot[i__] = -1;
         }
       if (x[i__] == up[i__])
         {
           ipivot[i__] = 1;
         }
       if (up[i__] == low[i__])
         {
           ipivot[i__] = 2;
         }
       if (low[i__] > up[i__])
         {
           *ier = -i__;
         }
       /* L30: */
     }
   return 0;
 } /* crash_ */
int dxpy_ (C_INT * n, C_FLOAT64 * dx, C_INT * incx, C_FLOAT64 * dy, C_INT * incy)
Definition at line 3383 of file CTruncatedNewton.cpp.
References C_INT.
Referenced by CTruncatedNewton::lmqn_(), and CTruncatedNewton::lmqnbc_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i__, m, ix, iy, mp1;
   /*     VECTOR PLUS A VECTOR. */
   /*     USES UNROLLED LOOPS FOR INCREMENTS EQUAL TO ONE. */
   /*     STEPHEN G. NASH 5/30/89. */
   /* Parameter adjustments */
   --dy;
   --dx;
   /* Function Body */
   if (*n <= 0)
     {
       return 0;
     }
   if (*incx == 1 && *incy == 1)
     {
       goto L20;
     }
   /*        CODE FOR UNEQUAL INCREMENTS OR EQUAL INCREMENTS */
   /*          NOT EQUAL TO 1 */
   ix = 1;
   iy = 1;
   if (*incx < 0)
     {
       ix = (-(*n) + 1) * *incx + 1;
     }
   if (*incy < 0)
     {
       iy = (-(*n) + 1) * *incy + 1;
     }
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       dy[iy] += dx[ix];
       ix += *incx;
       iy += *incy;
       /* L10: */
     }
   return 0;
   /*        CODE FOR BOTH INCREMENTS EQUAL TO 1 */
   /*        CLEAN-UP LOOP */
 L20:
   m = *n % 4;
   if (m == 0)
     {
       goto L40;
     }
   i__1 = m;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       dy[i__] += dx[i__];
       /* L30: */
     }
   if (*n < 4)
     {
       return 0;
     }
 L40:
   mp1 = m + 1;
   i__1 = *n;
   for (i__ = mp1; i__ <= i__1; i__ += 4)
     {
       dy[i__] += dx[i__];
       dy[i__ + 1] += dx[i__ + 1];
       dy[i__ + 2] += dx[i__ + 2];
       dy[i__ + 3] += dx[i__ + 3];
       /* L50: */
     }
   return 0;
 } /* dxpy_ */
int initp3_ (C_FLOAT64 * diagb, C_FLOAT64 * emat, C_INT * n, C_INT * lreset, C_FLOAT64 * yksk, C_FLOAT64 * yrsr, C_FLOAT64 * bsk, C_FLOAT64 * sk, C_FLOAT64 * yk, C_FLOAT64 * sr, C_FLOAT64 * yr, C_INT * modet, C_INT * upd1)
Definition at line 2535 of file CTruncatedNewton.cpp.
References c__1, C_FLOAT64, C_INT, dcopy_(), and ddot_().
Referenced by CTruncatedNewton::initpc_().
 {
   /* Format strings */
   //  char fmt_800[] = "(\002 \002,//8x,\002DMIN =\002,1pd12.4,\002  DM"
   //                        "AX =\002,1pd12.4,\002 COND =\002,1pd12.4,/)";
   /* System generated locals */
   C_INT i__1;
   /* Builtin functions */
   // C_INT s_wsfe(cilist *), do_fio(C_INT *, char *, ftnlen), e_wsfe(void);
   /* Local variables */
   C_FLOAT64 cond;
   C_FLOAT64 srds, yrsk;
   C_INT i__;
   C_FLOAT64 d1, dn, td, sds;
   /* Fortran I/O blocks */
   //  cilist io___235 = {0, 6, 0, fmt_800, 0 };
   /* Parameter adjustments */
   --yr;
   --sr;
   --yk;
   --sk;
   --bsk;
   --emat;
   --diagb;
   /* Function Body */
   if (*upd1)
     {
       goto L90;
     }
   if (*lreset)
     {
       goto L60;
     }
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       bsk[i__] = diagb[i__] * sr[i__];
       /* L10: */
     }
   sds = ddot_(n, &sr[1], &c__1, &bsk[1], &c__1);
   srds = ddot_(n, &sk[1], &c__1, &bsk[1], &c__1);
   yrsk = ddot_(n, &yr[1], &c__1, &sk[1], &c__1);
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       td = diagb[i__];
       bsk[i__] = td * sk[i__] - bsk[i__] * srds / sds + yr[i__] * yrsk / *
                  yrsr;
       emat[i__] = td - td * td * sr[i__] * sr[i__] / sds + yr[i__] * yr[i__]
                   / *yrsr;
       /* L20: */
     }
   sds = ddot_(n, &sk[1], &c__1, &bsk[1], &c__1);
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       emat[i__] = emat[i__] - bsk[i__] * bsk[i__] / sds + yk[i__] * yk[i__]
                   / *yksk;
       /* L30: */
     }
   goto L110;
 L60:
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       bsk[i__] = diagb[i__] * sk[i__];
       /* L70: */
     }
   sds = ddot_(n, &sk[1], &c__1, &bsk[1], &c__1);
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       td = diagb[i__];
       emat[i__] = td - td * td * sk[i__] * sk[i__] / sds + yk[i__] * yk[i__]
                   / *yksk;
       /* L80: */
     }
   goto L110;
 L90:
   dcopy_(n, &diagb[1], &c__1, &emat[1], &c__1);
 L110:
   if (*modet < 1)
     {
       return 0;
     }
   d1 = emat[1];
   dn = emat[1];
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (emat[i__] < d1)
         {
           d1 = emat[i__];
         }
       if (emat[i__] > dn)
         {
           dn = emat[i__];
         }
       /* L120: */
     }
   cond = dn / d1;
   /*s_wsfe(&io___235);
   do_fio(&c__1, (char *)&d1, (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&dn, (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&cond, (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();*/
   return 0;
 } /* initp3_ */
int lsout_ (C_INT * , C_INT * , C_FLOAT64 * xmin, C_FLOAT64 * , C_FLOAT64 * , C_FLOAT64 * xw, C_FLOAT64 * , C_FLOAT64 * , C_FLOAT64 * u, C_FLOAT64 * a, C_FLOAT64 * b, C_FLOAT64 * , C_FLOAT64 * , C_FLOAT64 * scxbd, C_FLOAT64 *)
Definition at line 2079 of file CTruncatedNewton.cpp.
References C_FLOAT64.
Referenced by CTruncatedNewton::linder_().
 {
   /* Format strings */
   /*  char fmt_800[] = "(///\002 OUTPUT FROM LINEAR SEARCH\002)";
     char fmt_810[] = "(\002  TOL AND EPS\002/2d25.14)";
     char fmt_820[] = "(\002  CURRENT UPPER AND LOWER BOUNDS\002/2d25."
                            "14)";
     char fmt_830[] = "(\002  STRICT UPPER BOUND\002/d25.14)";
     char fmt_840[] = "(\002  XW, FW, GW\002/3d25.14)";
     char fmt_850[] = "(\002  XMIN, FMIN, GMIN\002/3d25.14)";
     char fmt_860[] = "(\002  NEW ESTIMATE\002/2d25.14)";
     char fmt_870[] = "(\002  ILOC AND ITEST\002/2i3)"; */
   /* Builtin functions */
   // C_INT s_wsfe(cilist *), e_wsfe(void), do_fio(C_INT *, char *, ftnlen);
   /* Local variables */
   C_FLOAT64 ybnd, ya, yb, yu, yw;
   /* ERROR PRINTOUTS FOR GETPTC */
   yu = *xmin + *u;
   ya = *a + *xmin;
   yb = *b + *xmin;
   yw = *xw + *xmin;
   ybnd = *scxbd + *xmin;
   //remove the printing
   /*  s_wsfe(&io___199);
   e_wsfe();
   s_wsfe(&io___200);
   do_fio(&c__1, (char *)&(*tol), (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&(*eps), (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();
   s_wsfe(&io___201);
   do_fio(&c__1, (char *)&ya, (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&yb, (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();
   s_wsfe(&io___202);
   do_fio(&c__1, (char *)&ybnd, (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();
   s_wsfe(&io___203);
   do_fio(&c__1, (char *)&yw, (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&(*fw), (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&(*gw), (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();
   s_wsfe(&io___204);
   do_fio(&c__1, (char *)&(*xmin), (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&(*fmin), (ftnlen)sizeof(C_FLOAT64));
   do_fio(&c__1, (char *)&(*gmin), (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();
   s_wsfe(&io___205);
   do_fio(&c__1, (char *)&yu, (ftnlen)sizeof(C_FLOAT64));
   e_wsfe();
   s_wsfe(&io___206);
   do_fio(&c__1, (char *)&(*iloc), (ftnlen)sizeof(C_INT));
   do_fio(&c__1, (char *)&(*itest), (ftnlen)sizeof(C_INT));
   e_wsfe(); */
   return 0;
 } /* lsout_ */
C_FLOAT64 mchpr1_ (void)
Definition at line 2176 of file CTruncatedNewton.cpp.
References C_FLOAT64.
Referenced by chkucp_(), step1_(), CTruncatedNewton::tn_(), and CTruncatedNewton::tnbc_().
 {
   /* System generated locals */
   C_FLOAT64 ret_val;
   /* RETURNS THE VALUE OF EPSMCH, WHERE EPSMCH IS THE SMALLEST POSSIBLE */
   /* REAL NUMBER SUCH THAT 1.0 + EPSMCH .GT. 1.0 */
   /* FOR IEEE */
   ret_val = std::numeric_limits< C_FLOAT64 >::epsilon();
   return ret_val;
 } /* mchpr1_ */
int modz_ (C_INT * n, C_FLOAT64 * x, C_FLOAT64 * p, C_INT * ipivot, C_FLOAT64 * epsmch, C_FLOAT64 * low, C_FLOAT64 * up, C_FLOAT64 * flast, C_FLOAT64 * fnew)
Definition at line 1440 of file CTruncatedNewton.cpp.
References C_FLOAT64, and C_INT.
Referenced by CTruncatedNewton::lmqnbc_().
 {
   /* System generated locals */
   C_INT i__1;
   C_FLOAT64 d__1;
   /* Local variables */
   C_INT i__;
   C_FLOAT64 tol;
   /* UPDATE THE CONSTRAINT MATRIX IF A NEW CONSTRAINT IS ENCOUNTERED */
   /* Parameter adjustments */
   --up;
   --low;
   --ipivot;
   --p;
   --x;
   /* Function Body */
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (ipivot[i__] != 0)
         {
           goto L10;
         }
       if (p[i__] == 0.)
         {
           goto L10;
         }
       if (p[i__] > 0.)
         {
           goto L5;
         }
       tol = *epsmch * 10. * ((d__1 = low[i__], fabs(d__1)) + 1.);
       if (x[i__] - low[i__] > tol)
         {
           goto L10;
         }
       *flast = *fnew;
       ipivot[i__] = -1;
       x[i__] = low[i__];
       goto L10;
 L5:
       tol = *epsmch * 10. * ((d__1 = up[i__], fabs(d__1)) + 1.);
       if (up[i__] - x[i__] > tol)
         {
           goto L10;
         }
       *flast = *fnew;
       ipivot[i__] = 1;
       x[i__] = up[i__];
 L10:
       ;
     }
   return 0;
 } /* modz_ */
int monit_ (C_INT * n, C_FLOAT64 * x, C_FLOAT64 * , C_FLOAT64 * g, C_INT * , C_INT * , C_INT * , C_INT * , C_INT * ipivot)
Definition at line 1315 of file CTruncatedNewton.cpp.
References C_FLOAT64, and C_INT.
Referenced by CTruncatedNewton::lmqnbc_().
 {
   /* Format strings */
   //  char fmt_800[] = "(\002 \002,i4,1x,i4,1x,i4,1x,1pd22.15,2x,1pd15." "8)";
   /* System generated locals */
   C_INT i__1;
   /* Builtin functions */
   //C_INT s_wsfe(cilist *), do_fio(C_INT *, char *, ftnlen), e_wsfe(void);
   /* Local variables */
   C_INT i__;
   C_FLOAT64 gtg;
   /* PRINT RESULTS OF CURRENT ITERATION */
   /* Parameter adjustments */
   --ipivot;
   --g;
   --x;
   /* Function Body */
   gtg = 0.;
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (ipivot[i__] != 0)
         {
           goto L10;
         }
       gtg += g[i__] * g[i__];
 L10:
       ;
     }
   //remove the printing
   /* s_wsfe(&io___154);
    do_fio(&c__1, (char *)&(*niter), (ftnlen)sizeof(C_INT));
    do_fio(&c__1, (char *)&(*nftotl), (ftnlen)sizeof(C_INT));
    do_fio(&c__1, (char *)&(*nfeval), (ftnlen)sizeof(C_INT));
    do_fio(&c__1, (char *)&(*f), (ftnlen)sizeof(C_FLOAT64));
    do_fio(&c__1, (char *)&gtg, (ftnlen)sizeof(C_FLOAT64));
    e_wsfe();*/
   return 0;
 } /* monit_ */
int mslv_ (C_FLOAT64 * g, C_FLOAT64 * y, C_INT * n, C_FLOAT64 * sk, C_FLOAT64 * yk, C_FLOAT64 * diagb, C_FLOAT64 * sr, C_FLOAT64 * yr, C_FLOAT64 * hyr, C_FLOAT64 * hg, C_FLOAT64 * hyk, C_INT * upd1, C_FLOAT64 * yksk, C_FLOAT64 * gsk, C_FLOAT64 * yrsr, C_INT * lreset, C_INT * first)
Definition at line 2339 of file CTruncatedNewton.cpp.
References c__1, C_FLOAT64, C_INT, ddot_(), and ssbfgs_().
Referenced by CTruncatedNewton::msolve_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_FLOAT64 ghyk, ghyr, yksr = 0.0;
   C_INT i__;
   C_FLOAT64 ykhyk = 0.0, ykhyr = 0.0, yrhyr = 0.0, rdiagb;
   C_FLOAT64 one, gsr;
   /* THIS ROUTINE ACTS AS A PRECONDITIONING STEP FOR THE */
   /* LINEAR CONJUGATE-GRADIENT ROUTINE.  IT IS ALSO THE */
   /* METHOD OF COMPUTING THE SEARCH DIRECTION FROM THE */
   /* GRADIENT FOR THE NON-LINEAR CONJUGATE-GRADIENT CODE. */
   /* IT REPRESENTS A TWO-STEP SELF-SCALED BFGS FORMULA. */
   /* Parameter adjustments */
   --hyk;
   --hg;
   --hyr;
   --yr;
   --sr;
   --diagb;
   --yk;
   --sk;
   --y;
   --g;
   /* Function Body */
   if (*upd1)
     {
       goto L100;
     }
   one = 1.;
   *gsk = ddot_(n, &g[1], &c__1, &sk[1], &c__1);
   if (*lreset)
     {
       goto L60;
     }
   /* COMPUTE HG AND HY WHERE H IS THE INVERSE OF THE DIAGONALS */
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       rdiagb = 1. / diagb[i__];
       hg[i__] = g[i__] * rdiagb;
       if (*first)
         {
           hyk[i__] = yk[i__] * rdiagb;
         }
       if (*first)
         {
           hyr[i__] = yr[i__] * rdiagb;
         }
       /* L57: */
     }
   if (*first)
     {
       yksr = ddot_(n, &yk[1], &c__1, &sr[1], &c__1);
     }
   if (*first)
     {
       ykhyr = ddot_(n, &yk[1], &c__1, &hyr[1], &c__1);
     }
   gsr = ddot_(n, &g[1], &c__1, &sr[1], &c__1);
   ghyr = ddot_(n, &g[1], &c__1, &hyr[1], &c__1);
   if (*first)
     {
       yrhyr = ddot_(n, &yr[1], &c__1, &hyr[1], &c__1);
     }
   ssbfgs_(n, &one, &sr[1], &yr[1], &hg[1], &hyr[1], yrsr, &yrhyr, &gsr, &
           ghyr, &hg[1]);
   if (*first)
     {
       ssbfgs_(n, &one, &sr[1], &yr[1], &hyk[1], &hyr[1], yrsr, &yrhyr, &
               yksr, &ykhyr, &hyk[1]);
     }
   ykhyk = ddot_(n, &hyk[1], &c__1, &yk[1], &c__1);
   ghyk = ddot_(n, &hyk[1], &c__1, &g[1], &c__1);
   ssbfgs_(n, &one, &sk[1], &yk[1], &hg[1], &hyk[1], yksk, &ykhyk, gsk, &
           ghyk, &y[1]);
   return 0;
 L60:
   /* COMPUTE GH AND HY WHERE H IS THE INVERSE OF THE DIAGONALS */
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       rdiagb = 1. / diagb[i__];
       hg[i__] = g[i__] * rdiagb;
       if (*first)
         {
           hyk[i__] = yk[i__] * rdiagb;
         }
       /* L65: */
     }
   if (*first)
     {
       ykhyk = ddot_(n, &yk[1], &c__1, &hyk[1], &c__1);
     }
   ghyk = ddot_(n, &g[1], &c__1, &hyk[1], &c__1);
   ssbfgs_(n, &one, &sk[1], &yk[1], &hg[1], &hyk[1], yksk, &ykhyk, gsk, &
           ghyk, &y[1]);
   return 0;
 L100:
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L110: */
       y[i__] = g[i__] / diagb[i__];
     }
   return 0;
 } /* mslv_ */
int ndia3_ (C_INT * n, C_FLOAT64 * e, C_FLOAT64 * v, C_FLOAT64 * gv, C_FLOAT64 * r__, C_FLOAT64 * vgv, C_INT * modet)
Definition at line 1995 of file CTruncatedNewton.cpp.
References c__1, C_FLOAT64, C_INT, and ddot_().
Referenced by CTruncatedNewton::modlnp_().
 {
   /* Format strings */
   //   char fmt_800[] = "(\002 *** EMAT NEGATIVE:  \002,1pd16.8)";
   /* System generated locals */
   C_INT i__1;
   /* Builtin functions */
   //  C_INT s_wsfe(cilist *), do_fio(C_INT *, char *, ftnlen), e_wsfe(void);
   /* Local variables */
   C_INT i__;
   C_FLOAT64 vr;
   /* Fortran I/O blocks */
   // cilist io___192 = {0, 6, 0, fmt_800, 0 };
   /* UPDATE THE PRECONDITIOING MATRIX BASED ON A DIAGONAL VERSION */
   /* OF THE BFGS QUASI-NEWTON UPDATE. */
   /* Parameter adjustments */
   --r__;
   --gv;
   --v;
   --e;
   /* Function Body */
   vr = ddot_(n, &v[1], &c__1, &r__[1], &c__1);
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       e[i__] = e[i__] - r__[i__] * r__[i__] / vr + gv[i__] * gv[i__] / *vgv;
       if (e[i__] > 1e-6)
         {
           goto L10;
         }
       if (*modet > -2)
         {
           /*
              s_wsfe(&io___192);
              do_fio(&c__1, (char *)&e[i__], (ftnlen)sizeof(C_FLOAT64));
              e_wsfe();*/
         }
       e[i__] = 1.;
 L10:
       ;
     }
   return 0;
 } /* ndia3_ */
int negvec_ (C_INT * n, C_FLOAT64 * v)
Definition at line 2054 of file CTruncatedNewton.cpp.
References C_INT.
Referenced by CTruncatedNewton::modlnp_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i__;
   /* NEGATIVE OF THE VECTOR V */
   /* Parameter adjustments */
   --v;
   /* Function Body */
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       v[i__] = -v[i__];
       /* L10: */
     }
   return 0;
 } /* negvec_ */
C_FLOAT64 pow_dd (C_FLOAT64 * ap, C_FLOAT64 * bp)
Definition at line 3480 of file CTruncatedNewton.cpp.
 {
   return(pow(*ap, *bp));
 }
int ssbfgs_ (C_INT * n, C_FLOAT64 * gamma, C_FLOAT64 * sj, C_FLOAT64 * yj, C_FLOAT64 * hjv, C_FLOAT64 * hjyj, C_FLOAT64 * yjsj, C_FLOAT64 * yjhyj, C_FLOAT64 * vsj, C_FLOAT64 * vhyj, C_FLOAT64 * hjp1v)
Definition at line 2480 of file CTruncatedNewton.cpp.
References C_FLOAT64, and C_INT.
Referenced by mslv_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_FLOAT64 beta;
   C_INT i__;
   C_FLOAT64 delta;
   /* SELF-SCALED BFGS */
   /* Parameter adjustments */
   --hjp1v;
   --hjyj;
   --hjv;
   --yj;
   --sj;
   /* Function Body */
   delta = (*gamma * *yjhyj / *yjsj + 1.) * *vsj / *yjsj - *gamma * *vhyj / *
           yjsj;
   beta = -(*gamma) * *vsj / *yjsj;
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       hjp1v[i__] = *gamma * hjv[i__] + delta * sj[i__] + beta * hjyj[i__];
       /* L10: */
     }
   return 0;
 } /* ssbfgs_ */
C_FLOAT64 step1_ (C_FLOAT64 * fnew, C_FLOAT64 * fm, C_FLOAT64 * gtp, C_FLOAT64 * smax)
Definition at line 2143 of file CTruncatedNewton.cpp.
References C_FLOAT64, and mchpr1_().
Referenced by CTruncatedNewton::lmqn_(), and CTruncatedNewton::lmqnbc_().
 {
   /* System generated locals */
   C_FLOAT64 ret_val, d__1;
   /* Local variables */
   C_FLOAT64 d__, alpha;
   C_FLOAT64 epsmch;
   /* ******************************************************** */
   /* STEP1 RETURNS THE LENGTH OF THE INITIAL STEP TO BE TAKEN ALONG THE */
   /* VECTOR P IN THE NEXT LINEAR SEARCH. */
   /* ******************************************************** */
   epsmch = mchpr1_();
   d__ = (d__1 = *fnew - *fm, fabs(d__1));
   alpha = 1.;
   if (d__ * 2. <= -(*gtp) && d__ >= epsmch)
     {
       alpha = d__ * -2. / *gtp;
     }
   if (alpha >= *smax)
     {
       alpha = *smax;
     }
   ret_val = alpha;
   return ret_val;
 } /* step1_ */
int stpmax_ (C_FLOAT64 * stepmx, C_FLOAT64 * pe, C_FLOAT64 * spe, C_INT * n, C_FLOAT64 * x, C_FLOAT64 * p, C_INT * ipivot, C_FLOAT64 * low, C_FLOAT64 * up)
Definition at line 1396 of file CTruncatedNewton.cpp.
References C_FLOAT64, and C_INT.
Referenced by CTruncatedNewton::lmqnbc_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i__;
   C_FLOAT64 t;
   /* COMPUTE THE MAXIMUM ALLOWABLE STEP LENGTH */
   /* Parameter adjustments */
   --up; --low; --ipivot; --p; --x;
   /* Function Body */
   *spe = *stepmx / *pe;
   /* SPE IS THE STANDARD (UNCONSTRAINED) MAX STEP */
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (ipivot[i__] != 0) goto L10;
       if (p[i__] == 0.) goto L10;
       if (p[i__] > 0.) goto L5;
       t = low[i__] - x[i__];
       if (t > *spe * p[i__]) *spe = t / p[i__];
       goto L10;
 L5:
       t = up[i__] - x[i__];
       if (t < *spe * p[i__]) *spe = t / p[i__];
 L10:;
     }
   return 0;
 } /* stpmax_ */
int ztime_ (C_INT * n, C_FLOAT64 * x, C_INT * ipivot)
Definition at line 1366 of file CTruncatedNewton.cpp.
References C_INT.
Referenced by CTruncatedNewton::lmqnbc_(), and CTruncatedNewton::modlnp_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i__;
   /* THIS ROUTINE MULTIPLIES THE VECTOR X BY THE CONSTRAINT MATRIX Z */
   /* Parameter adjustments */
   --ipivot;
   --x;
   /* Function Body */
   i__1 = *n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if (ipivot[i__] != 0)
         {
           x[i__] = 0.;
         }
       /* L10: */
     }
   return 0;
 } /* ztime_ */
Variable Documentation
C_INT c__1 = 1 static
Definition at line 83 of file CTruncatedNewton.cpp.
Referenced by chkucp_(), initp3_(), CTruncatedNewton::linder_(), CTruncatedNewton::lmqn_(), CTruncatedNewton::lmqnbc_(), CTruncatedNewton::modlnp_(), mslv_(), ndia3_(), and CTruncatedNewton::setucr_().
C_FLOAT64 c_b246 = .6666 static
Definition at line 86 of file CTruncatedNewton.cpp.
Referenced by chkucp_().
C_INT c_false = (0) static
Definition at line 84 of file CTruncatedNewton.cpp.
Referenced by CTruncatedNewton::lmqn_().
C_INT c_true = (1) static
Definition at line 85 of file CTruncatedNewton.cpp.
Referenced by CTruncatedNewton::lmqnbc_().