COPASI API: CInternalSolver Class Reference
CInternalSolver Class Reference
#include <CInternalSolver.h>
Classes
struct State
Public Member Functions
void enablePrint (const bool &print=true)
void resetState ()
void saveState ()
void setOstream (std::ostream &os)
~CInternalSolver ()
Protected Member Functions
CInternalSolver ()
C_INT dintdy_ (double *t, const C_INT *k, double *yh, C_INT *nyh, double *dky, C_INT *iflag)
C_INT dprja_ (C_INT *neq, double *y, double *yh, C_INT *nyh, double *ewt, double *ftem, double *savf, double *wm, C_INT *iwm, evalF f, evalJ jac)
C_INT drchek_ (const C_INT *job, evalG g, C_INT *neq, double *y, double *yh, C_INT *nyh, double *g0, double *g1, double *gx, C_INT *jroot, C_INT *irt)
C_INT droots_ (C_INT *ng, double *hmin, C_INT *jflag, double *x0, double *x1, double *g0, double *g1, double *gx, double *x, C_INT *jroot)
C_INT dsolsy_ (double *wm, C_INT *iwm, double *x, double *tem)
C_INT dstoda_ (C_INT *neq, double *y, double *yh, C_INT *nyh, double *yh1, double *ewt, double *savf, double *acor, double *wm, C_INT *iwm, evalF f, evalJ jac, PJAC *pjac, SLVS *slvs)
Protected Attributes
dls001 mdls001_
dlsa01 mdlsa01_
dlsr01 mdlsr01_
State mState
Cxerrwd mxerrwd
Detailed Description
Definition at line 25 of file CInternalSolver.h.
Constructor & Destructor Documentation
CInternalSolver::CInternalSolver () protected
Definition at line 12 of file CInternalSolver.cpp.
                                 :
   mxerrwd(true),
   mdls001_(),
   mdlsa01_(),
   mdlsr01_()
 {}
CInternalSolver::~CInternalSolver ()
Definition at line 19 of file CInternalSolver.cpp.
 {}
Member Function Documentation
C_INT CInternalSolver::dintdy_ (double * t, const C_INT * k, double * yh, C_INT * nyh, double * dky, C_INT * iflag) protected
Definition at line 53 of file dintdy.cpp.
References c__0, c__1, c__2, c__30, c__51, c__52, c__60, c_b34, C_INT, d_sign(), dls001_1, if(), mxerrwd, and pow_di.
Referenced by drchek_(), CLSODA::operator()(), and CLSODAR::operator()().
 {
   /* System generated locals */
   C_INT yh_dim1, yh_offset, i__1, i__2;
   double d__1;
   /* Local variables */
   double c__;
   C_INT i__, j;
   double r__, s;
   C_INT ic, jb, jj;
   double tp;
   C_INT jb2, jj1, jp1;
   std::string msg;
   /* ***BEGIN PROLOGUE  DINTDY */
   /* ***SUBSIDIARY */
   /* ***PURPOSE  Interpolate solution derivatives. */
   /* ***TYPE      DOUBLE PRECISION (SINTDY-S, DINTDY-D) */
   /* ***AUTHOR  Hindmarsh, Alan C., (LLNL) */
   /* ***DESCRIPTION */
   /*  DINTDY computes interpolated values of the K-th derivative of the */
   /*  dependent variable vector y, and stores it in DKY.  This routine */
   /*  is called within the package with K = 0 and T = TOUT, but may */
   /*  also be called by the user for any K up to the current order. */
   /*  (See detailed instructions in the usage documentation.) */
   /*  The computed values in DKY are gotten by interpolation using the */
   /*  Nordsieck history array YH.  This array corresponds uniquely to a */
   /*  vector-valued polynomial of degree NQCUR or less, and DKY is set */
   /*  to the K-th derivative of this polynomial at T. */
   /*  The formula for DKY is: */
   /*               q */
   /*   DKY(i)  =  sum  c(j,K) * (T - tn)**(j-K) * h**(-j) * YH(i,j+1) */
   /*              j=K */
   /*  where  c(j,K) = j*(j-1)*...*(j-K+1), q = NQCUR, tn = TCUR, h = HCUR. */
   /*  The quantities  nq = NQCUR, l = nq+1, N = NEQ, tn, and h are */
   /*  communicated by COMMON.  The above sum is done in reverse order. */
   /*  IFLAG is returned negative if either K or T is out of bounds. */
   /* ***SEE ALSO  DLSODE */
   /* ***ROUTINES CALLED  XERRWD */
   /* ***COMMON BLOCKS    DLS001 */
   /* ***REVISION HISTORY  (YYMMDD) */
   /*   791129  DATE WRITTEN */
   /*   890501  Modified prologue to SLATEC/LDOC format.  (FNF) */
   /*   890503  Minor cosmetic changes.  (FNF) */
   /*   930809  Renamed to allow single/double precision versions. (ACH) */
   /*   010418  Reduced size of Common block /DLS001/. (ACH) */
   /*   031105  Restored 'own' variables to Common block /DLS001/, to */
   /*           enable interrupt/restart feature. (ACH) */
   /*   050427  Corrected roundoff decrement in TP. (ACH) */
   /* ***END PROLOGUE  DINTDY */
   /* **End */
   /* ***FIRST EXECUTABLE STATEMENT  DINTDY */
   /* Parameter adjustments */
   yh_dim1 = *nyh;
   yh_offset = 1 + yh_dim1;
   yh -= yh_offset;
   --dky;
   /* Function Body */
   *iflag = 0;
   if (*k < 0 || *k > dls001_1.nq)
     {
       goto L80;
     }
   d__1 = fabs(dls001_1.tn) + fabs(dls001_1.hu);
   tp = dls001_1.tn - dls001_1.hu - dls001_1.uround * 100. * d_sign(d__1, dls001_1.hu);
   if ((*t - tp) * (*t - dls001_1.tn) > 0.)
     {
       goto L90;
     }
   s = (*t - dls001_1.tn) / dls001_1.h__;
   ic = 1;
   if (*k == 0)
     {
       goto L15;
     }
   jj1 = dls001_1.l - *k;
   i__1 = dls001_1.nq;
   for (jj = jj1; jj <= i__1; ++jj)
     {
       /* L10: */
       ic *= jj;
     }
 L15:
   c__ = (double) ic;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L20: */
       dky[i__] = c__ * yh[i__ + dls001_1.l * yh_dim1];
     }
   if (*k == dls001_1.nq)
     {
       goto L55;
     }
   jb2 = dls001_1.nq - *k;
   i__1 = jb2;
   for (jb = 1; jb <= i__1; ++jb)
     {
       j = dls001_1.nq - jb;
       jp1 = j + 1;
       ic = 1;
       if (*k == 0)
         {
           goto L35;
         }
       jj1 = jp1 - *k;
       i__2 = j;
       for (jj = jj1; jj <= i__2; ++jj)
         {
           /* L30: */
           ic *= jj;
         }
 L35:
       c__ = (double) ic;
       i__2 = dls001_1.n;
       for (i__ = 1; i__ <= i__2; ++i__)
         {
           /* L40: */
           dky[i__] = c__ * yh[i__ + jp1 * yh_dim1] + s * dky[i__];
         }
       /* L50: */
     }
   if (*k == 0)
     {
       return 0;
     }
 L55:
   i__1 = -(*k);
   r__ = pow_di(&dls001_1.h__, &i__1);
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L60: */
       dky[i__] = r__ * dky[i__];
     }
   return 0;
 L80:
   msg = "DINTDY-  K (=I1) illegal      ";
   mxerrwd(msg, &c__30, &c__51, &c__0, &c__1, k, &c__0, &c__0, &c_b34, &
           c_b34, (C_INT)80);
   *iflag = -1;
   return 0;
 L90:
   msg = "DINTDY-  T (=R1) illegal      ";
   mxerrwd(msg, &c__30, &c__52, &c__0, &c__0, &c__0, &c__0, &c__1, t, &c_b34,
           (C_INT)80);
   msg = "      T not in interval TCUR - HU (= R1) to TCUR (=R2)      ";
   mxerrwd(msg, &c__60, &c__52, &c__0, &c__0, &c__0, &c__0, &c__2, &tp, &
           dls001_1.tn, (C_INT)80);
   *iflag = -2;
   return 0;
   /* ----------------------- END OF SUBROUTINE DINTDY ---------------------- */
 } /* dintdy_ */
C_INT CInternalSolver::dprja_ (C_INT * neq, double * y, double * yh, C_INT * nyh, double * ewt, double * ftem, double * savf, double * wm, C_INT * iwm, evalF f, evalJ jac) protected
Definition at line 47 of file dprja.cpp.
References c__0, C_INT, dbnorm_(), dfnorm_(), dgbfa_, dgefa_, dls001_1, dlsa01_2, dmnorm_(), max, and min.
Referenced by CLSODA::CLSODA(), and CLSODAR::CLSODAR().
 {
   /* System generated locals */
   C_INT yh_dim1, yh_offset, i__1, i__2, i__3, i__4;
   double d__1, d__2;
   /* Local variables */
   C_INT i__, j;
   double r__;
   C_INT i1, i2, j1;
   double r0;
   C_INT ii, jj, ml, mu;
   double yi, yj, hl0;
   C_INT ml3, np1;
   double fac;
   C_INT mba, ier;
   double con, yjj;
   C_INT meb1, lenp;
   double srur;
   C_INT mband, meband;
   /* ----------------------------------------------------------------------- */
   /* DPRJA is called by DSTODA to compute and process the matrix */
   /* P = I - H*EL(1)*J , where J is an approximation to the Jacobian. */
   /* Here J is computed by the user-supplied routine JAC if */
   /* MITER = 1 or 4 or by finite differencing if MITER = 2 or 5. */
   /* J, scaled by -H*EL(1), is stored in WM.  Then the norm of J (the */
   /* matrix norm consistent with the weighted max-norm on vectors given */
   /* by DMNORM) is computed, and J is overwritten by P.  P is then */
   /* subjected to LU decomposition in preparation for later solution */
   /* of linear systems with P as coefficient matrix.  This is done */
   /* by DGEFA if MITER = 1 or 2, and by DGBFA if MITER = 4 or 5. */
   /* In addition to variables described previously, communication */
   /* with DPRJA uses the following: */
   /* Y     = array containing predicted values on entry. */
   /* FTEM  = work array of length N (ACOR in DSTODA). */
   /* SAVF  = array containing f evaluated at predicted y. */
   /* WM    = real work space for matrices.  On output it contains the */
   /*         LU decomposition of P. */
   /*         Storage of matrix elements starts at WM(3). */
   /*         WM also contains the following matrix-related data: */
   /*         WM(1) = SQRT(UROUND), used in numerical Jacobian increments. */
   /* IWM   = integer work space containing pivot information, starting at */
   /*         IWM(21).   IWM also contains the band parameters */
   /*         ML = IWM(1) and MU = IWM(2) if MITER is 4 or 5. */
   /* EL0   = EL(1) (input). */
   /* PDNORM= norm of Jacobian matrix. (Output). */
   /* IERPJ = output error flag,  = 0 if no trouble, .gt. 0 if */
   /*         P matrix found to be singular. */
   /* JCUR  = output flag = 1 to indicate that the Jacobian matrix */
   /*         (or approximation) is now current. */
   /* This routine also uses the Common variables EL0, H, TN, UROUND, */
   /* MITER, N, NFE, and NJE. */
   /* ----------------------------------------------------------------------- */
   /* Parameter adjustments */
   --neq;
   --y;
   yh_dim1 = *nyh;
   yh_offset = 1 + yh_dim1;
   yh -= yh_offset;
   --ewt;
   --ftem;
   --savf;
   --wm;
   --iwm;
   /* Function Body */
   ++dls001_1.nje;
   dls001_1.ierpj = 0;
   dls001_1.jcur = 1;
   hl0 = dls001_1.h__ * dls001_1.el0;
   switch (dls001_1.miter)
     {
       case 1: goto L100;
       case 2: goto L200;
       case 3: goto L300;
       case 4: goto L400;
       case 5: goto L500;
     }
   /* If MITER = 1, call JAC and multiply by scalar. ----------------------- */
 L100:
   lenp = dls001_1.n * dls001_1.n;
   i__1 = lenp;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L110: */
       wm[i__ + 2] = 0.;
     }
   jac(&neq[1], &dls001_1.tn, &y[1], &c__0, &c__0, &wm[3], &dls001_1.n);
   con = -hl0;
   i__1 = lenp;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L120: */
       wm[i__ + 2] *= con;
     }
   goto L240;
   /* If MITER = 2, make N calls to F to approximate J. -------------------- */
 L200:
   fac = dmnorm_(&dls001_1.n, &savf[1], &ewt[1]);
   r0 = fabs(dls001_1.h__) * 1e3 * dls001_1.uround * dls001_1.n * fac;
   if (r0 == 0.)
     {
       r0 = 1.;
     }
   srur = wm[1];
   j1 = 2;
   i__1 = dls001_1.n;
   for (j = 1; j <= i__1; ++j)
     {
       yj = y[j];
       /* Computing MAX */
       d__1 = srur * fabs(yj), d__2 = r0 / ewt[j];
       r__ = std::max(d__1, d__2);
       y[j] += r__;
       fac = -hl0 / r__;
       f(&neq[1], &dls001_1.tn, &y[1], &ftem[1]);
       i__2 = dls001_1.n;
       for (i__ = 1; i__ <= i__2; ++i__)
         {
           /* L220: */
           wm[i__ + j1] = (ftem[i__] - savf[i__]) * fac;
         }
       y[j] = yj;
       j1 += dls001_1.n;
       /* L230: */
     }
   dls001_1.nfe += dls001_1.n;
 L240:
   /* Compute norm of Jacobian. -------------------------------------------- */
   dlsa01_2.pdnorm = dfnorm_(&dls001_1.n, &wm[3], &ewt[1]) / fabs(hl0);
   /* Add identity matrix. ------------------------------------------------- */
   j = 3;
   np1 = dls001_1.n + 1;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       wm[j] += 1.;
       /* L250: */
       j += np1;
     }
   /* Do LU decomposition on P. -------------------------------------------- */
   dgefa_(&wm[3], &dls001_1.n, &dls001_1.n, &iwm[21], &ier);
   if (ier != 0)
     {
       dls001_1.ierpj = 1;
     }
   return 0;
   /* Dummy block only, since MITER is never 3 in this routine. ------------ */
 L300:
   return 0;
   /* If MITER = 4, call JAC and multiply by scalar. ----------------------- */
 L400:
   ml = iwm[1];
   mu = iwm[2];
   ml3 = ml + 3;
   mband = ml + mu + 1;
   meband = mband + ml;
   lenp = meband * dls001_1.n;
   i__1 = lenp;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L410: */
       wm[i__ + 2] = 0.;
     }
   jac(&neq[1], &dls001_1.tn, &y[1], &ml, &mu, &wm[ml3], &meband);
   con = -hl0;
   i__1 = lenp;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L420: */
       wm[i__ + 2] *= con;
     }
   goto L570;
   /* If MITER = 5, make MBAND calls to F to approximate J. ---------------- */
 L500:
   ml = iwm[1];
   mu = iwm[2];
   mband = ml + mu + 1;
   mba = std::min(mband, dls001_1.n);
   meband = mband + ml;
   meb1 = meband - 1;
   srur = wm[1];
   fac = dmnorm_(&dls001_1.n, &savf[1], &ewt[1]);
   r0 = fabs(dls001_1.h__) * 1e3 * dls001_1.uround * dls001_1.n * fac;
   if (r0 == 0.)
     {
       r0 = 1.;
     }
   i__1 = mba;
   for (j = 1; j <= i__1; ++j)
     {
       i__2 = dls001_1.n;
       i__3 = mband;
       for (i__ = j; i__3 < 0 ? i__ >= i__2 : i__ <= i__2; i__ += i__3)
         {
           yi = y[i__];
           /* Computing MAX */
           d__1 = srur * fabs(yi), d__2 = r0 / ewt[i__];
           r__ = std::max(d__1, d__2);
           /* L530: */
           y[i__] += r__;
         }
       f(&neq[1], &dls001_1.tn, &y[1], &ftem[1]);
       i__3 = dls001_1.n;
       i__2 = mband;
       for (jj = j; i__2 < 0 ? jj >= i__3 : jj <= i__3; jj += i__2)
         {
           y[jj] = yh[jj + yh_dim1];
           yjj = y[jj];
           /* Computing MAX */
           d__1 = srur * fabs(yjj), d__2 = r0 / ewt[jj];
           r__ = std::max(d__1, d__2);
           fac = -hl0 / r__;
           /* Computing MAX */
           i__4 = jj - mu;
           i1 = std::max(i__4, (C_INT)1);
           /* Computing MIN */
           i__4 = jj + ml;
           i2 = std::min(i__4, dls001_1.n);
           ii = jj * meb1 - ml + 2;
           i__4 = i2;
           for (i__ = i1; i__ <= i__4; ++i__)
             {
               /* L540: */
               wm[ii + i__] = (ftem[i__] - savf[i__]) * fac;
             }
           /* L550: */
         }
       /* L560: */
     }
   dls001_1.nfe += mba;
 L570:
   /* Compute norm of Jacobian. -------------------------------------------- */
   dlsa01_2.pdnorm = dbnorm_(&dls001_1.n, &wm[ml + 3], &meband, &ml, &mu, &
                             ewt[1]) / fabs(hl0);
   /* Add identity matrix. ------------------------------------------------- */
   ii = mband + 2;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       wm[ii] += 1.;
       /* L580: */
       ii += meband;
     }
   /* Do LU decomposition of P. -------------------------------------------- */
   dgbfa_(&wm[3], &meband, &dls001_1.n, &ml, &mu, &iwm[21], &ier);
   if (ier != 0)
     {
       dls001_1.ierpj = 1;
     }
   return 0;
   /* ----------------------- End of Subroutine DPRJA ----------------------- */
 } /* dprja_ */
C_INT CInternalSolver::drchek_ (const C_INT * job, evalG g, C_INT * neq, double * y, double * yh, C_INT * nyh, double * g0, double * g1, double * gx, C_INT * jroot, C_INT * irt) protected
Definition at line 46 of file drcheck.cpp.
References c__0, c__1, C_INT, d_sign(), dcopy_(), dintdy_(), dls001_1, dlsr01_1, droots_(), max, and switch().
Referenced by CLSODAR::operator()().
 {
   /* System generated locals */
   C_INT yh_dim1, yh_offset, i__1;
   double d__1;
   /* Local variables */
   C_INT i__;
   double x, t1, temp1, temp2;
   C_INT iflag, jflag;
   double hming;
   bool zroot;
   /* ----------------------------------------------------------------------- */
   /* This routine checks for the presence of a root in the vicinity of */
   /* the current T, in a manner depending on the input flag JOB.  It calls */
   /* Subroutine DROOTS to locate the root as precisely as possible. */
   /* In addition to variables described previously, DRCHEK */
   /* uses the following for communication: */
   /* JOB    = integer flag indicating type of call: */
   /*          JOB = 1 means the problem is being initialized, and DRCHEK */
   /*                  is to look for a root at or very near the initial T. */
   /*          JOB = 2 means a continuation call to the solver was just */
   /*                  made, and DRCHEK is to check for a root in the */
   /*                  relevant part of the step last taken. */
   /*          JOB = 3 means a successful step was just taken, and DRCHEK */
   /*                  is to look for a root in the interval of the step. */
   /* G0     = array of length NG, containing the value of g at T = T0. */
   /*          G0 is input for JOB .ge. 2, and output in all cases. */
   /* G1,GX  = arrays of length NG for work space. */
   /* IRT    = completion flag: */
   /*          IRT = 0  means no root was found. */
   /*          IRT = -1 means JOB = 1 and a root was found too near to T. */
   /*          IRT = 1  means a legitimate root was found (JOB = 2 or 3). */
   /*                   On return, T0 is the root location, and Y is the */
   /*                   corresponding solution vector. */
   /* T0     = value of T at one endpoint of interval of interest.  Only */
   /*          roots beyond T0 in the direction of integration are sought. */
   /*          T0 is input if JOB .ge. 2, and output in all cases. */
   /*          T0 is updated by DRCHEK, whether a root is found or not. */
   /* TLAST  = last value of T returned by the solver (input only). */
   /* TOUTC  = copy of TOUT (input only). */
   /* IRFND  = input flag showing whether the last step taken had a root. */
   /*          IRFND = 1 if it did, = 0 if not. */
   /* ITASKC = copy of ITASK (input only). */
   /* NGC    = copy of NG (input only). */
   /* ----------------------------------------------------------------------- */
   /* Parameter adjustments */
   --neq;
   --y;
   yh_dim1 = *nyh;
   yh_offset = 1 + yh_dim1;
   yh -= yh_offset;
   --g0;
   --g1;
   --gx;
   --jroot;
   /* Function Body */
   *irt = 0;
   i__1 = dlsr01_1.ngc;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L10: */
       jroot[i__] = 0;
     }
   hming = (fabs(dls001_1.tn) + fabs(dls001_1.h__)) * dls001_1.uround * 100.;
   switch (*job)
     {
       case 1: goto L100;
       case 2: goto L200;
       case 3: goto L300;
     }
   /* Evaluate g at initial T, and check for zero values. ------------------ */
 L100:
   dlsr01_1.t0 = dls001_1.tn;
   (*g)(&neq[1], &dlsr01_1.t0, &y[1], &dlsr01_1.ngc, &g0[1]);
   dlsr01_1.nge = 1;
   zroot = false;
   i__1 = dlsr01_1.ngc;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L110: */
       if ((d__1 = g0[i__], fabs(d__1)) <= 0.)
         {
           zroot = true;
         }
     }
   if (! zroot)
     {
       goto L190;
     }
   /* g has a zero at T.  Look at g at T + (small increment). -------------- */
   /* Computing MAX */
   d__1 = hming / fabs(dls001_1.h__);
   temp2 = std::max(d__1, .1);
   temp1 = temp2 * dls001_1.h__;
   dlsr01_1.t0 += temp1;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L120: */
       y[i__] += temp2 * yh[i__ + (yh_dim1 << 1)];
     }
   (*g)(&neq[1], &dlsr01_1.t0, &y[1], &dlsr01_1.ngc, &g0[1]);
   ++dlsr01_1.nge;
   zroot = false;
   i__1 = dlsr01_1.ngc;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L130: */
       if ((d__1 = g0[i__], fabs(d__1)) <= 0.)
         {
           zroot = true;
         }
     }
   if (! zroot)
     {
       goto L190;
     }
   /* g has a zero at T and also close to T.  Take error return. ----------- */
   *irt = -1;
   return 0;
 L190:
   return 0;
 L200:
   if (dlsr01_1.irfnd == 0)
     {
       goto L260;
     }
   /* If a root was found on the previous step, evaluate G0 = g(T0). ------- */
   dintdy_(&dlsr01_1.t0, &c__0, &yh[yh_offset], nyh, &y[1], &iflag);
   (*g)(&neq[1], &dlsr01_1.t0, &y[1], &dlsr01_1.ngc, &g0[1]);
   ++dlsr01_1.nge;
   zroot = false;
   i__1 = dlsr01_1.ngc;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L210: */
       if ((d__1 = g0[i__], fabs(d__1)) <= 0.)
         {
           zroot = true;
         }
     }
   if (! zroot)
     {
       goto L260;
     }
   /* g has a zero at T0.  Look at g at T + (small increment). ------------- */
   temp1 = d_sign(hming, dls001_1.h__);
   dlsr01_1.t0 += temp1;
   if ((dlsr01_1.t0 - dls001_1.tn) * dls001_1.h__ < 0.)
     {
       goto L230;
     }
   temp2 = temp1 / dls001_1.h__;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L220: */
       y[i__] += temp2 * yh[i__ + (yh_dim1 << 1)];
     }
   goto L240;
 L230:
   dintdy_(&dlsr01_1.t0, &c__0, &yh[yh_offset], nyh, &y[1], &iflag);
 L240:
   (*g)(&neq[1], &dlsr01_1.t0, &y[1], &dlsr01_1.ngc, &g0[1]);
   ++dlsr01_1.nge;
   zroot = false;
   i__1 = dlsr01_1.ngc;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if ((d__1 = g0[i__], fabs(d__1)) > 0.)
         {
           goto L250;
         }
       jroot[i__] = 1;
       zroot = true;
 L250:
       ;
     }
   if (! zroot)
     {
       goto L260;
     }
   /* g has a zero at T0 and also close to T0.  Return root. --------------- */
   *irt = 1;
   return 0;
   /* G0 has no zero components.  Proceed to check relevant interval. ------ */
 L260:
   if (dls001_1.tn == dlsr01_1.tlast)
     {
       goto L390;
     }
 L300:
   /* Set T1 to TN or TOUTC, whichever comes first, and get g at T1. ------- */
   if (dlsr01_1.itaskc == 2 || dlsr01_1.itaskc == 3 || dlsr01_1.itaskc == 5)
     {
       goto L310;
     }
   if ((dlsr01_1.toutc - dls001_1.tn) * dls001_1.h__ >= 0.)
     {
       goto L310;
     }
   t1 = dlsr01_1.toutc;
   if ((t1 - dlsr01_1.t0) * dls001_1.h__ <= 0.)
     {
       goto L390;
     }
   dintdy_(&t1, &c__0, &yh[yh_offset], nyh, &y[1], &iflag);
   goto L330;
 L310:
   t1 = dls001_1.tn;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L320: */
       y[i__] = yh[i__ + yh_dim1];
     }
 L330:
   (*g)(&neq[1], &t1, &y[1], &dlsr01_1.ngc, &g1[1]);
   ++dlsr01_1.nge;
   /* Call DROOTS to search for root in interval from T0 to T1. ------------ */
   jflag = 0;
 L350:
   droots_(&dlsr01_1.ngc, &hming, &jflag, &dlsr01_1.t0, &t1, &g0[1], &g1[1],
           &gx[1], &x, &jroot[1]);
   if (jflag > 1)
     {
       goto L360;
     }
   dintdy_(&x, &c__0, &yh[yh_offset], nyh, &y[1], &iflag);
   (*g)(&neq[1], &x, &y[1], &dlsr01_1.ngc, &gx[1]);
   ++dlsr01_1.nge;
   goto L350;
 L360:
   dlsr01_1.t0 = x;
   dcopy_(&dlsr01_1.ngc, &gx[1], &c__1, &g0[1], &c__1);
   if (jflag == 4)
     {
       goto L390;
     }
   /* Found a root.  Interpolate to X and return. -------------------------- */
   dintdy_(&x, &c__0, &yh[yh_offset], nyh, &y[1], &iflag);
   *irt = 1;
   return 0;
 L390:
   return 0;
   /* ----------------------- End of Subroutine DRCHEK ---------------------- */
 } /* drchek_ */
C_INT CInternalSolver::droots_ (C_INT * ng, double * hmin, C_INT * jflag, double * x0, double * x1, double * g0, double * g1, double * gx, double * x, C_INT * jroot) protected
Definition at line 343 of file drcheck.cpp.
References c__1, c_b3, C_INT, d_sign(), dcopy_(), and dlsr01_2.
Referenced by drchek_().
 {
   /* Initialized data */
   static double zero = 0.;
   static double half = .5;
   static double tenth = .1;
   static double five = 5.;
   /* System generated locals */
   C_INT i__1;
   double d__1;
   /* Local variables */
   C_INT i__;
   double t2, tmax;
   bool xroot, zroot, sgnchg;
   C_INT imxold, nxlast;
   double fracsub, fracint;
   /* ----------------------------------------------------------------------- */
   /* This subroutine finds the leftmost root of a set of arbitrary */
   /* functions gi(x) (i = 1,...,NG) in an interval (X0,X1).  Only roots */
   /* of odd multiplicity (i.e. changes of sign of the gi) are found. */
   /* Here the sign of X1 - X0 is arbitrary, but is constant for a given */
   /* problem, and -leftmost- means nearest to X0. */
   /* The values of the vector-valued function g(x) = (gi, i=1...NG) */
   /* are communicated through the call sequence of DROOTS. */
   /* The method used is the Illinois algorithm. */
   /* Reference: */
   /* Kathie L. Hiebert and Lawrence F. Shampine, Implicitly Defined */
   /* Output Points for Solutions of ODEs, Sandia Report SAND80-0180, */
   /* February 1980. */
   /* Description of parameters. */
   /* NG     = number of functions gi, or the number of components of */
   /*          the vector valued function g(x).  Input only. */
   /* HMIN   = resolution parameter in X.  Input only.  When a root is */
   /*          found, it is located only to within an error of HMIN in X. */
   /*          Typically, HMIN should be set to something on the order of */
   /*               100 * UROUND * MAX(ABS(X0),ABS(X1)), */
   /*          where UROUND is the unit roundoff of the machine. */
   /* JFLAG  = integer flag for input and output communication. */
   /*          On input, set JFLAG = 0 on the first call for the problem, */
   /*          and leave it unchanged until the problem is completed. */
   /*          (The problem is completed when JFLAG .ge. 2 on return.) */
   /*          On output, JFLAG has the following values and meanings: */
   /*          JFLAG = 1 means DROOTS needs a value of g(x).  Set GX = g(X) */
   /*                    and call DROOTS again. */
   /*          JFLAG = 2 means a root has been found.  The root is */
   /*                    at X, and GX contains g(X).  (Actually, X is the */
   /*                    rightmost approximation to the root on an interval */
   /*                    (X0,X1) of size HMIN or less.) */
   /*          JFLAG = 3 means X = X1 is a root, with one or more of the gi */
   /*                    being zero at X1 and no sign changes in (X0,X1). */
   /*                    GX contains g(X) on output. */
   /*          JFLAG = 4 means no roots (of odd multiplicity) were */
   /*                    found in (X0,X1) (no sign changes). */
   /* X0,X1  = endpoints of the interval where roots are sought. */
   /*          X1 and X0 are input when JFLAG = 0 (first call), and */
   /*          must be left unchanged between calls until the problem is */
   /*          completed.  X0 and X1 must be distinct, but X1 - X0 may be */
   /*          of either sign.  However, the notion of -left- and -right- */
   /*          will be used to mean nearer to X0 or X1, respectively. */
   /*          When JFLAG .ge. 2 on return, X0 and X1 are output, and */
   /*          are the endpoints of the relevant interval. */
   /* G0,G1  = arrays of length NG containing the vectors g(X0) and g(X1), */
   /*          respectively.  When JFLAG = 0, G0 and G1 are input and */
   /*          none of the G0(i) should be zero. */
   /*          When JFLAG .ge. 2 on return, G0 and G1 are output. */
   /* GX     = array of length NG containing g(X).  GX is input */
   /*          when JFLAG = 1, and output when JFLAG .ge. 2. */
   /* X      = independent variable value.  Output only. */
   /*          When JFLAG = 1 on output, X is the point at which g(x) */
   /*          is to be evaluated and loaded into GX. */
   /*          When JFLAG = 2 or 3, X is the root. */
   /*          When JFLAG = 4, X is the right endpoint of the interval, X1. */
   /* JROOT  = integer array of length NG.  Output only. */
   /*          When JFLAG = 2 or 3, JROOT indicates which components */
   /*          of g(x) have a root at X.  JROOT(i) is 1 if the i-th */
   /*          component has a root, and JROOT(i) = 0 otherwise. */
   /* ----------------------------------------------------------------------- */
   /* Parameter adjustments */
   --jroot;
   --gx;
   --g1;
   --g0;
   /* Function Body */
   if (*jflag == 1)
     {
       goto L200;
     }
   /* JFLAG .ne. 1.  Check for change in sign of g or zero at X1. ---------- */
   dlsr01_2.imax = 0;
   tmax = zero;
   zroot = false;
   i__1 = *ng;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if ((d__1 = g1[i__], fabs(d__1)) > zero)
         {
           goto L110;
         }
       zroot = true;
       goto L120;
       /* At this point, G0(i) has been checked and cannot be zero. ------------ */
 L110:
       if (d_sign(c_b3, g0[i__]) == d_sign(c_b3, g1[i__]))
         {
           goto L120;
         }
       t2 = (d__1 = g1[i__] / (g1[i__] - g0[i__]), fabs(d__1));
       if (t2 <= tmax)
         {
           goto L120;
         }
       tmax = t2;
       dlsr01_2.imax = i__;
 L120:
       ;
     }
   if (dlsr01_2.imax > 0)
     {
       goto L130;
     }
   sgnchg = false;
   goto L140;
 L130:
   sgnchg = true;
 L140:
   if (! sgnchg)
     {
       goto L400;
     }
   /* There is a sign change.  Find the first root in the interval. -------- */
   xroot = false;
   nxlast = 0;
   dlsr01_2.last = 1;
   /* Repeat until the first root in the interval is found.  Loop point. --- */
 L150:
   if (xroot)
     {
       goto L300;
     }
   if (nxlast == dlsr01_2.last)
     {
       goto L160;
     }
   dlsr01_2.alpha = 1.;
   goto L180;
 L160:
   if (dlsr01_2.last == 0)
     {
       goto L170;
     }
   dlsr01_2.alpha *= .5;
   goto L180;
 L170:
   dlsr01_2.alpha *= 2.;
 L180:
   dlsr01_2.x2 = *x1 - (*x1 - *x0) * g1[dlsr01_2.imax] / (g1[dlsr01_2.imax]
                 - dlsr01_2.alpha * g0[dlsr01_2.imax]);
   /* If X2 is too close to X0 or X1, adjust it inward, by a fractional ---- */
   /* distance that is between 0.1 and 0.5. -------------------------------- */
   if ((d__1 = dlsr01_2.x2 - *x0, fabs(d__1)) < half * *hmin)
     {
       fracint = (d__1 = *x1 - *x0, fabs(d__1)) / *hmin;
       fracsub = tenth;
       if (fracint <= five)
         {
           fracsub = half / fracint;
         }
       dlsr01_2.x2 = *x0 + fracsub * (*x1 - *x0);
     }
   if ((d__1 = *x1 - dlsr01_2.x2, fabs(d__1)) < half * *hmin)
     {
       fracint = (d__1 = *x1 - *x0, fabs(d__1)) / *hmin;
       fracsub = tenth;
       if (fracint <= five)
         {
           fracsub = half / fracint;
         }
       dlsr01_2.x2 = *x1 - fracsub * (*x1 - *x0);
     }
   *jflag = 1;
   *x = dlsr01_2.x2;
   /* Return to the calling routine to get a value of GX = g(X). ----------- */
   return 0;
   /* Check to see in which interval g changes sign. ----------------------- */
 L200:
   imxold = dlsr01_2.imax;
   dlsr01_2.imax = 0;
   tmax = zero;
   zroot = false;
   i__1 = *ng;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       if ((d__1 = gx[i__], fabs(d__1)) > zero)
         {
           goto L210;
         }
       zroot = true;
       goto L220;
       /* Neither G0(i) nor GX(i) can be zero at this point. ------------------- */
 L210:
       if (d_sign(c_b3, g0[i__]) == d_sign(c_b3, gx[i__]))
         {
           goto L220;
         }
       t2 = (d__1 = gx[i__] / (gx[i__] - g0[i__]), fabs(d__1));
       if (t2 <= tmax)
         {
           goto L220;
         }
       tmax = t2;
       dlsr01_2.imax = i__;
 L220:
       ;
     }
   if (dlsr01_2.imax > 0)
     {
       goto L230;
     }
   sgnchg = false;
   dlsr01_2.imax = imxold;
   goto L240;
 L230:
   sgnchg = true;
 L240:
   nxlast = dlsr01_2.last;
   if (! sgnchg)
     {
       goto L250;
     }
   /* Sign change between X0 and X2, so replace X1 with X2. ---------------- */
   *x1 = dlsr01_2.x2;
   dcopy_(ng, &gx[1], &c__1, &g1[1], &c__1);
   dlsr01_2.last = 1;
   xroot = false;
   goto L270;
 L250:
   if (! zroot)
     {
       goto L260;
     }
   /* Zero value at X2 and no sign change in (X0,X2), so X2 is a root. ----- */
   *x1 = dlsr01_2.x2;
   dcopy_(ng, &gx[1], &c__1, &g1[1], &c__1);
   xroot = true;
   goto L270;
   /* No sign change between X0 and X2.  Replace X0 with X2. --------------- */
 L260:
   dcopy_(ng, &gx[1], &c__1, &g0[1], &c__1);
   *x0 = dlsr01_2.x2;
   dlsr01_2.last = 0;
   xroot = false;
 L270:
   if ((d__1 = *x1 - *x0, fabs(d__1)) <= *hmin)
     {
       xroot = true;
     }
   goto L150;
   /* Return with X1 as the root.  Set JROOT.  Set X = X1 and GX = G1. ----- */
 L300:
   *jflag = 2;
   *x = *x1;
   dcopy_(ng, &g1[1], &c__1, &gx[1], &c__1);
   i__1 = *ng;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       jroot[i__] = 0;
       if ((d__1 = g1[i__], fabs(d__1)) > zero)
         {
           goto L310;
         }
       jroot[i__] = 1;
       goto L320;
 L310:
       if (d_sign(c_b3, g0[i__]) != d_sign(c_b3, g1[i__]))
         {
           jroot[i__] = 1;
         }
 L320:
       ;
     }
   return 0;
   /* No sign change in the interval.  Check for zero at right endpoint. --- */
 L400:
   if (! zroot)
     {
       goto L420;
     }
   /* Zero value at X1 and no sign change in (X0,X1).  Return JFLAG = 3. --- */
   *x = *x1;
   dcopy_(ng, &g1[1], &c__1, &gx[1], &c__1);
   i__1 = *ng;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       jroot[i__] = 0;
       if ((d__1 = g1[i__], fabs(d__1)) <= zero)
         {
           jroot[i__] = 1;
         }
       /* L410: */
     }
   *jflag = 3;
   return 0;
   /* No sign changes in this interval.  Set X = X1, return JFLAG = 4. ----- */
 L420:
   dcopy_(ng, &g1[1], &c__1, &gx[1], &c__1);
   *x = *x1;
   *jflag = 4;
   return 0;
   /* ----------------------- End of Subroutine DROOTS ---------------------- */
 } /* droots_ */
C_INT CInternalSolver::dsolsy_ (double * wm, C_INT * iwm, double * x, double * tem) protected
Definition at line 43 of file dsolsy.cpp.
References c__0, C_INT, dgbsl_, dgesl_, and dls001_1.
Referenced by CLSODA::CLSODA(), and CLSODAR::CLSODAR().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i__;
   double r__, di;
   C_INT ml, mu;
   double hl0, phl0;
   C_INT meband;
   /* ***BEGIN PROLOGUE  DSOLSY */
   /* ***SUBSIDIARY */
   /* ***PURPOSE  ODEPACK linear system solver. */
   /* ***TYPE      DOUBLE PRECISION (SSOLSY-S, DSOLSY-D) */
   /* ***AUTHOR  Hindmarsh, Alan C., (LLNL) */
   /* ***DESCRIPTION */
   /*  This routine manages the solution of the linear system arising from */
   /*  a chord iteration.  It is called if MITER .ne. 0. */
   /*  If MITER is 1 or 2, it calls DGESL to accomplish this. */
   /*  If MITER = 3 it updates the coefficient h*EL0 in the diagonal */
   /*  matrix, and then computes the solution. */
   /*  If MITER is 4 or 5, it calls DGBSL. */
   /*  Communication with DSOLSY uses the following variables: */
   /*  WM    = real work space containing the inverse diagonal matrix if */
   /*          MITER = 3 and the LU decomposition of the matrix otherwise. */
   /*          Storage of matrix elements starts at WM(3). */
   /*          WM also contains the following matrix-related data: */
   /*          WM(1) = SQRT(UROUND) (not used here), */
   /*          WM(2) = HL0, the previous value of h*EL0, used if MITER = 3. */
   /*  IWM   = integer work space containing pivot information, starting at */
   /*          IWM(21), if MITER is 1, 2, 4, or 5.  IWM also contains band */
   /*          parameters ML = IWM(1) and MU = IWM(2) if MITER is 4 or 5. */
   /*  X     = the right-hand side vector on input, and the solution vector */
   /*          on output, of length N. */
   /*  TEM   = vector of work space of length N, not used in this version. */
   /*  IERSL = output flag (in COMMON).  IERSL = 0 if no trouble occurred. */
   /*          IERSL = 1 if a singular matrix arose with MITER = 3. */
   /*  This routine also uses the COMMON variables EL0, H, MITER, and N. */
   /* ***SEE ALSO  DLSODE */
   /* ***ROUTINES CALLED  DGBSL, DGESL */
   /* ***COMMON BLOCKS    DLS001 */
   /* ***REVISION HISTORY  (YYMMDD) */
   /*   791129  DATE WRITTEN */
   /*   890501  Modified prologue to SLATEC/LDOC format.  (FNF) */
   /*   890503  Minor cosmetic changes.  (FNF) */
   /*   930809  Renamed to allow single/double precision versions. (ACH) */
   /*   010418  Reduced size of Common block /DLS001/. (ACH) */
   /*   031105  Restored 'own' variables to Common block /DLS001/, to */
   /*           enable interrupt/restart feature. (ACH) */
   /* ***END PROLOGUE  DSOLSY */
   /* **End */
   /* ***FIRST EXECUTABLE STATEMENT  DSOLSY */
   /* Parameter adjustments */
   --tem;
   --x;
   --iwm;
   --wm;
   /* Function Body */
   dls001_1.iersl = 0;
   switch (dls001_1.miter)
     {
       case 1: goto L100;
       case 2: goto L100;
       case 3: goto L300;
       case 4: goto L400;
       case 5: goto L400;
     }
 L100:
   dgesl_(&wm[3], &dls001_1.n, &dls001_1.n, &iwm[21], &x[1], &c__0);
   return 0;
 L300:
   phl0 = wm[2];
   hl0 = dls001_1.h__ * dls001_1.el0;
   wm[2] = hl0;
   if (hl0 == phl0)
     {
       goto L330;
     }
   r__ = hl0 / phl0;
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       di = 1. - r__ * (1. - 1. / wm[i__ + 2]);
       if (fabs(di) == 0.)
         {
           goto L390;
         }
       /* L320: */
       wm[i__ + 2] = 1. / di;
     }
 L330:
   i__1 = dls001_1.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L340: */
       x[i__] = wm[i__ + 2] * x[i__];
     }
   return 0;
 L390:
   dls001_1.iersl = 1;
   return 0;
 L400:
   ml = iwm[1];
   mu = iwm[2];
   meband = (ml << 1) + mu + 1;
   dgbsl_(&wm[3], &meband, &dls001_1.n, &ml, &mu, &iwm[21], &x[1], &c__0);
   return 0;
   /* ----------------------- END OF SUBROUTINE DSOLSY ---------------------- */
 } /* dsolsy_ */
C_INT CInternalSolver::dstoda_ (C_INT * neq, double * y, double * yh, C_INT * nyh, double * yh1, double * ewt, double * savf, double * acor, double * wm, C_INT * iwm, evalF f, evalJ jac, PJAC * pjac, SLVS * slvs) protected
Definition at line 45 of file dstoda.cpp.
References c__1, c__2, C_INT, dcfode_(), dls001_3, dlsa01_1, dmnorm_(), max, min, and pow_dd.
Referenced by CLSODA::operator()(), and CLSODAR::operator()().
 {
   /* Initialized data */
   static const double sm1[12] =
   {
     .5, .575, .55, .45, .35, .25, .2, .15, .1, .075, .05,
     .025
   };
   /* System generated locals */
   C_INT yh_dim1, yh_offset, i__1, i__2;
   double d__1, d__2, d__3;
   /* Local variables */
   C_INT i__, j, m;
   double r__;
   C_INT i1, jb;
   double rh = 0.0, rm, dm1, dm2;
   C_INT lm1, lm2;
   double rh1, rh2, del, ddn;
   C_INT ncf;
   double pdh = 0.0, dsm, dup, exm1, exm2;
   C_INT nqm1, nqm2;
   double dcon, delp;
   C_INT lm1p1, lm2p1;
   double exdn, rhdn;
   C_INT iret;
   double told, rhsm;
   C_INT newq;
   double exsm, rhup, rate, exup, rh1it, alpha;
   C_INT iredo = 0;
   double pnorm;
   /* Parameter adjustments */
   --neq;
   --y;
   yh_dim1 = *nyh;
   yh_offset = 1 + yh_dim1;
   yh -= yh_offset;
   --yh1;
   --ewt;
   --savf;
   --acor;
   --wm;
   --iwm;
   /* Function Body */
   /* ----------------------------------------------------------------------- */
   /* DSTODA performs one step of the integration of an initial value */
   /* problem for a system of ordinary differential equations. */
   /* Note: DSTODA is independent of the value of the iteration method */
   /* indicator MITER, when this is .ne. 0, and hence is independent */
   /* of the type of chord method used, or the Jacobian structure. */
   /* Communication with DSTODA is done with the following variables: */
   /* Y      = an array of length .ge. N used as the Y argument in */
   /*          all calls to F and JAC. */
   /* NEQ    = integer array containing problem size in NEQ(1), and */
   /*          passed as the NEQ argument in all calls to F and JAC. */
   /* YH     = an NYH by LMAX array containing the dependent variables */
   /*          and their approximate scaled derivatives, where */
   /*          LMAX = MAXORD + 1.  YH(i,j+1) contains the approximate */
   /*          j-th derivative of y(i), scaled by H**j/factorial(j) */
   /*          (j = 0,1,...,NQ).  On entry for the first step, the first */
   /*          two columns of YH must be set from the initial values. */
   /* NYH    = a constant integer .ge. N, the first dimension of YH. */
   /* YH1    = a one-dimensional array occupying the same space as YH. */
   /* EWT    = an array of length N containing multiplicative weights */
   /*          for local error measurements.  Local errors in y(i) are */
   /*          compared to 1.0/EWT(i) in various error tests. */
   /* SAVF   = an array of working storage, of length N. */
   /* ACOR   = a work array of length N, used for the accumulated */
   /*          corrections.  On a successful return, ACOR(i) contains */
   /*          the estimated one-step local error in y(i). */
   /* WM,IWM = real and integer work arrays associated with matrix */
   /*          operations in chord iteration (MITER .ne. 0). */
   /* PJAC   = name of routine to evaluate and preprocess Jacobian matrix */
   /*          and P = I - H*EL0*Jac, if a chord method is being used. */
   /*          It also returns an estimate of norm(Jac) in PDNORM. */
   /* SLVS   = name of routine to solve linear system in chord iteration. */
   /* CCMAX  = maximum relative change in H*EL0 before PJAC is called. */
   /* H      = the step size to be attempted on the next step. */
   /*          H is altered by the error control algorithm during the */
   /*          problem.  H can be either positive or negative, but its */
   /*          sign must remain constant throughout the problem. */
   /* HMIN   = the minimum absolute value of the step size H to be used. */
   /* HMXI   = inverse of the maximum absolute value of H to be used. */
   /*          HMXI = 0.0 is allowed and corresponds to an infinite HMAX. */
   /*          HMIN and HMXI may be changed at any time, but will not */
   /*          take effect until the next change of H is considered. */
   /* TN     = the independent variable. TN is updated on each step taken. */
   /* JSTART = an integer used for input only, with the following */
   /*          values and meanings: */
   /*               0  perform the first step. */
   /*           .gt.0  take a new step continuing from the last. */
   /*              -1  take the next step with a new value of H, */
   /*                    N, METH, MITER, and/or matrix parameters. */
   /*              -2  take the next step with a new value of H, */
   /*                    but with other inputs unchanged. */
   /*          On return, JSTART is set to 1 to facilitate continuation. */
   /* KFLAG  = a completion code with the following meanings: */
   /*               0  the step was succesful. */
   /*              -1  the requested error could not be achieved. */
   /*              -2  corrector convergence could not be achieved. */
   /*              -3  fatal error in PJAC or SLVS. */
   /*          A return with KFLAG = -1 or -2 means either */
   /*          ABS(H) = HMIN or 10 consecutive failures occurred. */
   /*          On a return with KFLAG negative, the values of TN and */
   /*          the YH array are as of the beginning of the last */
   /*          step, and H is the last step size attempted. */
   /* MAXORD = the maximum order of integration method to be allowed. */
   /* MAXCOR = the maximum number of corrector iterations allowed. */
   /* MSBP   = maximum number of steps between PJAC calls (MITER .gt. 0). */
   /* MXNCF  = maximum number of convergence failures allowed. */
   /* METH   = current method. */
   /*          METH = 1 means Adams method (nonstiff) */
   /*          METH = 2 means BDF method (stiff) */
   /*          METH may be reset by DSTODA. */
   /* MITER  = corrector iteration method. */
   /*          MITER = 0 means functional iteration. */
   /*          MITER = JT .gt. 0 means a chord iteration corresponding */
   /*          to Jacobian type JT.  (The DLSODA/DLSODAR argument JT is */
   /*          communicated here as JTYP, but is not used in DSTODA */
   /*          except to load MITER following a method switch.) */
   /*          MITER may be reset by DSTODA. */
   /* N      = the number of first-order differential equations. */
   /* ----------------------------------------------------------------------- */
   dls001_3.kflag = 0;
   told = dls001_3.tn;
   ncf = 0;
   dls001_3.ierpj = 0;
   dls001_3.iersl = 0;
   dls001_3.jcur = 0;
   dls001_3.icf = 0;
   delp = 0.;
   if (dls001_3.jstart > 0)
     {
       goto L200;
     }
   if (dls001_3.jstart == -1)
     {
       goto L100;
     }
   if (dls001_3.jstart == -2)
     {
       goto L160;
     }
   /* ----------------------------------------------------------------------- */
   /* On the first call, the order is set to 1, and other variables are */
   /* initialized.  RMAX is the maximum ratio by which H can be increased */
   /* in a single step.  It is initially 1.E4 to compensate for the small */
   /* initial H, but then is normally equal to 10.  If a failure */
   /* occurs (in corrector convergence or error test), RMAX is set at 2 */
   /* for the next increase. */
   /* DCFODE is called to get the needed coefficients for both methods. */
   /* ----------------------------------------------------------------------- */
   dls001_3.lmax = dls001_3.maxord + 1;
   dls001_3.nq = 1;
   dls001_3.l = 2;
   dls001_3.ialth = 2;
   dls001_3.rmax = 1e4;
   dls001_3.rc = 0.;
   dls001_3.el0 = 1.;
   dls001_3.crate = .7;
   dls001_3.hold = dls001_3.h__;
   dls001_3.nslp = 0;
   dls001_3.ipup = dls001_3.miter;
   iret = 3;
   /* Initialize switching parameters.  METH = 1 is assumed initially. ----- */
   dlsa01_1.icount = 20;
   dlsa01_1.irflag = 0;
   dlsa01_1.pdest = 0.;
   dlsa01_1.pdlast = 0.;
   dlsa01_1.ratio = 5.;
   dcfode_(&c__2, dls001_3.elco, dls001_3.tesco);
   for (i__ = 1; i__ <= 5; ++i__)
     {
       /* L10: */
       dlsa01_1.cm2[i__ - 1] = dls001_3.tesco[i__ * 3 - 2] * dls001_3.elco[
                                 i__ + 1 + i__ * 13 - 14];
     }
   dcfode_(&c__1, dls001_3.elco, dls001_3.tesco);
   for (i__ = 1; i__ <= 12; ++i__)
     {
       /* L20: */
       dlsa01_1.cm1[i__ - 1] = dls001_3.tesco[i__ * 3 - 2] * dls001_3.elco[
                                 i__ + 1 + i__ * 13 - 14];
     }
   goto L150;
   /* ----------------------------------------------------------------------- */
   /* The following block handles preliminaries needed when JSTART = -1. */
   /* IPUP is set to MITER to force a matrix update. */
   /* If an order increase is about to be considered (IALTH = 1), */
   /* IALTH is reset to 2 to postpone consideration one more step. */
   /* If the caller has changed METH, DCFODE is called to reset */
   /* the coefficients of the method. */
   /* If H is to be changed, YH must be rescaled. */
   /* If H or METH is being changed, IALTH is reset to L = NQ + 1 */
   /* to prevent further changes in H for that many steps. */
   /* ----------------------------------------------------------------------- */
 L100:
   dls001_3.ipup = dls001_3.miter;
   dls001_3.lmax = dls001_3.maxord + 1;
   if (dls001_3.ialth == 1)
     {
       dls001_3.ialth = 2;
     }
   if (dls001_3.meth == dlsa01_1.mused)
     {
       goto L160;
     }
   dcfode_(&dls001_3.meth, dls001_3.elco, dls001_3.tesco);
   dls001_3.ialth = dls001_3.l;
   iret = 1;
   /* ----------------------------------------------------------------------- */
   /* The el vector and related constants are reset */
   /* whenever the order NQ is changed, or at the start of the problem. */
   /* ----------------------------------------------------------------------- */
 L150:
   i__1 = dls001_3.l;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L155: */
       dls001_3.el[i__ - 1] = dls001_3.elco[i__ + dls001_3.nq * 13 - 14];
     }
   dls001_3.nqnyh = dls001_3.nq * *nyh;
   dls001_3.rc = dls001_3.rc * dls001_3.el[0] / dls001_3.el0;
   dls001_3.el0 = dls001_3.el[0];
   dls001_3.conit = .5 / (dls001_3.nq + 2);
   switch (iret)
     {
       case 1: goto L160;
       case 2: goto L170;
       case 3: goto L200;
     }
   /* ----------------------------------------------------------------------- */
   /* If H is being changed, the H ratio RH is checked against */
   /* RMAX, HMIN, and HMXI, and the YH array rescaled.  IALTH is set to */
   /* L = NQ + 1 to prevent a change of H for that many steps, unless */
   /* forced by a convergence or error test failure. */
   /* ----------------------------------------------------------------------- */
 L160:
   if (dls001_3.h__ == dls001_3.hold)
     {
       goto L200;
     }
   rh = dls001_3.h__ / dls001_3.hold;
   dls001_3.h__ = dls001_3.hold;
   iredo = 3;
   goto L175;
 L170:
   /* Computing MAX */
   d__1 = rh, d__2 = dls001_3.hmin / fabs(dls001_3.h__);
   rh = std::max(d__1, d__2);
 L175:
   rh = std::min(rh, dls001_3.rmax);
   /* Computing MAX */
   d__1 = 1., d__2 = fabs(dls001_3.h__) * dls001_3.hmxi * rh;
   rh /= std::max(d__1, d__2);
   /* ----------------------------------------------------------------------- */
   /* If METH = 1, also restrict the new step size by the stability region. */
   /* If this reduces H, set IRFLAG to 1 so that if there are roundoff */
   /* problems later, we can assume that is the cause of the trouble. */
   /* ----------------------------------------------------------------------- */
   if (dls001_3.meth == 2)
     {
       goto L178;
     }
   dlsa01_1.irflag = 0;
   /* Computing MAX */
   d__1 = fabs(dls001_3.h__) * dlsa01_1.pdlast;
   pdh = std::max(d__1, 1e-6);
   if (rh * pdh * 1.00001 < sm1[dls001_3.nq - 1])
     {
       goto L178;
     }
   rh = sm1[dls001_3.nq - 1] / pdh;
   dlsa01_1.irflag = 1;
 L178:
   r__ = 1.;
   i__1 = dls001_3.l;
   for (j = 2; j <= i__1; ++j)
     {
       r__ *= rh;
       i__2 = dls001_3.n;
       for (i__ = 1; i__ <= i__2; ++i__)
         {
           /* L180: */
           yh[i__ + j * yh_dim1] *= r__;
         }
     }
   dls001_3.h__ *= rh;
   dls001_3.rc *= rh;
   dls001_3.ialth = dls001_3.l;
   if (iredo == 0)
     {
       goto L690;
     }
   /* ----------------------------------------------------------------------- */
   /* This section computes the predicted values by effectively */
   /* multiplying the YH array by the Pascal triangle matrix. */
   /* RC is the ratio of new to old values of the coefficient  H*EL(1). */
   /* When RC differs from 1 by more than CCMAX, IPUP is set to MITER */
   /* to force PJAC to be called, if a Jacobian is involved. */
   /* In any case, PJAC is called at least every MSBP steps. */
   /* ----------------------------------------------------------------------- */
 L200:
   if ((d__1 = dls001_3.rc - 1., fabs(d__1)) > dls001_3.ccmax)
     {
       dls001_3.ipup = dls001_3.miter;
     }
   if (dls001_3.nst >= dls001_3.nslp + dls001_3.msbp)
     {
       dls001_3.ipup = dls001_3.miter;
     }
   dls001_3.tn += dls001_3.h__;
   i1 = dls001_3.nqnyh + 1;
   i__2 = dls001_3.nq;
   for (jb = 1; jb <= i__2; ++jb)
     {
       i1 -= *nyh;
       /* DIR$ IVDEP */
       i__1 = dls001_3.nqnyh;
       for (i__ = i1; i__ <= i__1; ++i__)
         {
           /* L210: */
           yh1[i__] += yh1[i__ + *nyh];
         }
       /* L215: */
     }
   pnorm = dmnorm_(&dls001_3.n, &yh1[1], &ewt[1]);
   /* ----------------------------------------------------------------------- */
   /* Up to MAXCOR corrector iterations are taken.  A convergence test is */
   /* made on the RMS-norm of each correction, weighted by the error */
   /* weight vector EWT.  The sum of the corrections is accumulated in the */
   /* vector ACOR(i).  The YH array is not altered in the corrector loop. */
   /* ----------------------------------------------------------------------- */
 L220:
   m = 0;
   rate = 0.;
   del = 0.;
   i__2 = dls001_3.n;
   for (i__ = 1; i__ <= i__2; ++i__)
     {
       /* L230: */
       y[i__] = yh[i__ + yh_dim1];
     }
   f(&neq[1], &dls001_3.tn, &y[1], &savf[1]);
   ++dls001_3.nfe;
   if (dls001_3.ipup <= 0)
     {
       goto L250;
     }
   /* ----------------------------------------------------------------------- */
   /* If indicated, the matrix P = I - H*EL(1)*J is reevaluated and */
   /* preprocessed before starting the corrector iteration.  IPUP is set */
   /* to 0 as an indicator that this has been done. */
   /* ----------------------------------------------------------------------- */
   (*pjac)(&neq[1], &y[1], &yh[yh_offset], nyh, &ewt[1], &acor[1], &savf[1],
           &wm[1], &iwm[1], f, jac);
   dls001_3.ipup = 0;
   dls001_3.rc = 1.;
   dls001_3.nslp = dls001_3.nst;
   dls001_3.crate = .7;
   if (dls001_3.ierpj != 0)
     {
       goto L430;
     }
 L250:
   i__2 = dls001_3.n;
   for (i__ = 1; i__ <= i__2; ++i__)
     {
       /* L260: */
       acor[i__] = 0.;
     }
 L270:
   if (dls001_3.miter != 0)
     {
       goto L350;
     }
   /* ----------------------------------------------------------------------- */
   /* In the case of functional iteration, update Y directly from */
   /* the result of the last function evaluation. */
   /* ----------------------------------------------------------------------- */
   i__2 = dls001_3.n;
   for (i__ = 1; i__ <= i__2; ++i__)
     {
       savf[i__] = dls001_3.h__ * savf[i__] - yh[i__ + (yh_dim1 << 1)];
       /* L290: */
       y[i__] = savf[i__] - acor[i__];
     }
   del = dmnorm_(&dls001_3.n, &y[1], &ewt[1]);
   i__2 = dls001_3.n;
   for (i__ = 1; i__ <= i__2; ++i__)
     {
       y[i__] = yh[i__ + yh_dim1] + dls001_3.el[0] * savf[i__];
       /* L300: */
       acor[i__] = savf[i__];
     }
   goto L400;
   /* ----------------------------------------------------------------------- */
   /* In the case of the chord method, compute the corrector error, */
   /* and solve the linear system with that as right-hand side and */
   /* P as coefficient matrix. */
   /* ----------------------------------------------------------------------- */
 L350:
   i__2 = dls001_3.n;
   for (i__ = 1; i__ <= i__2; ++i__)
     {
       /* L360: */
       y[i__] = dls001_3.h__ * savf[i__] - (yh[i__ + (yh_dim1 << 1)] + acor[
                                              i__]);
     }
   (*slvs)(&wm[1], &iwm[1], &y[1], &savf[1]);
   if (dls001_3.iersl < 0)
     {
       goto L430;
     }
   if (dls001_3.iersl > 0)
     {
       goto L410;
     }
   del = dmnorm_(&dls001_3.n, &y[1], &ewt[1]);
   i__2 = dls001_3.n;
   for (i__ = 1; i__ <= i__2; ++i__)
     {
       acor[i__] += y[i__];
       /* L380: */
       y[i__] = yh[i__ + yh_dim1] + dls001_3.el[0] * acor[i__];
     }
   /* ----------------------------------------------------------------------- */
   /* Test for convergence.  If M .gt. 0, an estimate of the convergence */
   /* rate constant is stored in CRATE, and this is used in the test. */
   /* We first check for a change of iterates that is the size of */
   /* roundoff error.  If this occurs, the iteration has converged, and a */
   /* new rate estimate is not formed. */
   /* In all other cases, force at least two iterations to estimate a */
   /* local Lipschitz constant estimate for Adams methods. */
   /* On convergence, form PDEST = local maximum Lipschitz constant */
   /* estimate.  PDLAST is the most recent nonzero estimate. */
   /* ----------------------------------------------------------------------- */
 L400:
   if (del <= pnorm * 100. * dls001_3.uround)
     {
       goto L450;
     }
   if (m == 0 && dls001_3.meth == 1)
     {
       goto L405;
     }
   if (m == 0)
     {
       goto L402;
     }
   rm = 1024.;
   if (del <= delp * 1024.)
     {
       rm = del / delp;
     }
   rate = std::max(rate, rm);
   /* Computing MAX */
   d__1 = dls001_3.crate * .2;
   dls001_3.crate = std::max(d__1, rm);
 L402:
   /* Computing MIN */
   d__1 = 1., d__2 = dls001_3.crate * 1.5;
   dcon = del * std::min(d__1, d__2) / (dls001_3.tesco[dls001_3.nq * 3 - 2] *
                                        dls001_3.conit);
   if (dcon > 1.)
     {
       goto L405;
     }
   /* Computing MAX */
   d__2 = dlsa01_1.pdest, d__3 = rate / (d__1 = dls001_3.h__ * dls001_3.el[0]
                                         , fabs(d__1));
   dlsa01_1.pdest = std::max(d__2, d__3);
   if (dlsa01_1.pdest != 0.)
     {
       dlsa01_1.pdlast = dlsa01_1.pdest;
     }
   goto L450;
 L405:
   ++m;
   if (m == dls001_3.maxcor)
     {
       goto L410;
     }
   if (m >= 2 && del > delp * 2.)
     {
       goto L410;
     }
   delp = del;
   f(&neq[1], &dls001_3.tn, &y[1], &savf[1]);
   ++dls001_3.nfe;
   goto L270;
   /* ----------------------------------------------------------------------- */
   /* The corrector iteration failed to converge. */
   /* If MITER .ne. 0 and the Jacobian is out of date, PJAC is called for */
   /* the next try.  Otherwise the YH array is retracted to its values */
   /* before prediction, and H is reduced, if possible.  If H cannot be */
   /* reduced or MXNCF failures have occurred, exit with KFLAG = -2. */
   /* ----------------------------------------------------------------------- */
 L410:
   if (dls001_3.miter == 0 || dls001_3.jcur == 1)
     {
       goto L430;
     }
   dls001_3.icf = 1;
   dls001_3.ipup = dls001_3.miter;
   goto L220;
 L430:
   dls001_3.icf = 2;
   ++ncf;
   dls001_3.rmax = 2.;
   dls001_3.tn = told;
   i1 = dls001_3.nqnyh + 1;
   i__2 = dls001_3.nq;
   for (jb = 1; jb <= i__2; ++jb)
     {
       i1 -= *nyh;
       /* DIR$ IVDEP */
       i__1 = dls001_3.nqnyh;
       for (i__ = i1; i__ <= i__1; ++i__)
         {
           /* L440: */
           yh1[i__] -= yh1[i__ + *nyh];
         }
       /* L445: */
     }
   if (dls001_3.ierpj < 0 || dls001_3.iersl < 0)
     {
       goto L680;
     }
   if (fabs(dls001_3.h__) <= dls001_3.hmin * 1.00001)
     {
       goto L670;
     }
   if (ncf == dls001_3.mxncf)
     {
       goto L670;
     }
   rh = .25;
   dls001_3.ipup = dls001_3.miter;
   iredo = 1;
   goto L170;
   /* ----------------------------------------------------------------------- */
   /* The corrector has converged.  JCUR is set to 0 */
   /* to signal that the Jacobian involved may need updating later. */
   /* The local error test is made and control passes to statement 500 */
   /* if it fails. */
   /* ----------------------------------------------------------------------- */
 L450:
   dls001_3.jcur = 0;
   if (m == 0)
     {
       dsm = del / dls001_3.tesco[dls001_3.nq * 3 - 2];
     }
   if (m > 0)
     {
       dsm = dmnorm_(&dls001_3.n, &acor[1], &ewt[1]) / dls001_3.tesco[
               dls001_3.nq * 3 - 2];
     }
   if (dsm > 1.)
     {
       goto L500;
     }
   /* ----------------------------------------------------------------------- */
   /* After a successful step, update the YH array. */
   /* Decrease ICOUNT by 1, and if it is -1, consider switching methods. */
   /* If a method switch is made, reset various parameters, */
   /* rescale the YH array, and exit.  If there is no switch, */
   /* consider changing H if IALTH = 1.  Otherwise decrease IALTH by 1. */
   /* If IALTH is then 1 and NQ .lt. MAXORD, then ACOR is saved for */
   /* use in a possible order increase on the next step. */
   /* If a change in H is considered, an increase or decrease in order */
   /* by one is considered also.  A change in H is made only if it is by a */
   /* factor of at least 1.1.  If not, IALTH is set to 3 to prevent */
   /* testing for that many steps. */
   /* ----------------------------------------------------------------------- */
   dls001_3.kflag = 0;
   iredo = 0;
   ++dls001_3.nst;
   dls001_3.hu = dls001_3.h__;
   dls001_3.nqu = dls001_3.nq;
   dlsa01_1.mused = dls001_3.meth;
   i__2 = dls001_3.l;
   for (j = 1; j <= i__2; ++j)
     {
       i__1 = dls001_3.n;
       for (i__ = 1; i__ <= i__1; ++i__)
         {
           /* L460: */
           yh[i__ + j * yh_dim1] += dls001_3.el[j - 1] * acor[i__];
         }
     }
   --dlsa01_1.icount;
   if (dlsa01_1.icount >= 0)
     {
       goto L488;
     }
   if (dls001_3.meth == 2)
     {
       goto L480;
     }
   /* ----------------------------------------------------------------------- */
   /* We are currently using an Adams method.  Consider switching to BDF. */
   /* If the current order is greater than 5, assume the problem is */
   /* not stiff, and skip this section. */
   /* If the Lipschitz constant and error estimate are not polluted */
   /* by roundoff, go to 470 and perform the usual test. */
   /* Otherwise, switch to the BDF methods if the last step was */
   /* restricted to insure stability (irflag = 1), and stay with Adams */
   /* method if not.  When switching to BDF with polluted error estimates, */
   /* in the absence of other information, double the step size. */
   /* When the estimates are OK, we make the usual test by computing */
   /* the step size we could have (ideally) used on this step, */
   /* with the current (Adams) method, and also that for the BDF. */
   /* If NQ .gt. MXORDS, we consider changing to order MXORDS on switching. */
   /* Compare the two step sizes to decide whether to switch. */
   /* The step size advantage must be at least RATIO = 5 to switch. */
   /* ----------------------------------------------------------------------- */
   if (dls001_3.nq > 5)
     {
       goto L488;
     }
   if (dsm > pnorm * 100. * dls001_3.uround && dlsa01_1.pdest != 0.)
     {
       goto L470;
     }
   if (dlsa01_1.irflag == 0)
     {
       goto L488;
     }
   rh2 = 2.;
   nqm2 = std::min(dls001_3.nq, dlsa01_1.mxords);
   goto L478;
 L470:
   exsm = 1. / dls001_3.l;
   rh1 = 1. / (pow_dd(&dsm, &exsm) * 1.2 + 1.2e-6);
   rh1it = rh1 * 2.;
   pdh = dlsa01_1.pdlast * fabs(dls001_3.h__);
   if (pdh * rh1 > 1e-5)
     {
       rh1it = sm1[dls001_3.nq - 1] / pdh;
     }
   rh1 = std::min(rh1, rh1it);
   if (dls001_3.nq <= dlsa01_1.mxords)
     {
       goto L474;
     }
   nqm2 = dlsa01_1.mxords;
   lm2 = dlsa01_1.mxords + 1;
   exm2 = 1. / lm2;
   lm2p1 = lm2 + 1;
   dm2 = dmnorm_(&dls001_3.n, &yh[lm2p1 * yh_dim1 + 1], &ewt[1]) /
         dlsa01_1.cm2[dlsa01_1.mxords - 1];
   rh2 = 1. / (pow_dd(&dm2, &exm2) * 1.2 + 1.2e-6);
   goto L476;
 L474:
   dm2 = dsm * (dlsa01_1.cm1[dls001_3.nq - 1] / dlsa01_1.cm2[dls001_3.nq - 1]
               );
   rh2 = 1. / (pow_dd(&dm2, &exsm) * 1.2 + 1.2e-6);
   nqm2 = dls001_3.nq;
 L476:
   if (rh2 < dlsa01_1.ratio * rh1)
     {
       goto L488;
     }
   /* THE SWITCH TEST PASSED.  RESET RELEVANT QUANTITIES FOR BDF. ---------- */
 L478:
   rh = rh2;
   dlsa01_1.icount = 20;
   dls001_3.meth = 2;
   dls001_3.miter = dlsa01_1.jtyp;
   dlsa01_1.pdlast = 0.;
   dls001_3.nq = nqm2;
   dls001_3.l = dls001_3.nq + 1;
   goto L170;
   /* ----------------------------------------------------------------------- */
   /* We are currently using a BDF method.  Consider switching to Adams. */
   /* Compute the step size we could have (ideally) used on this step, */
   /* with the current (BDF) method, and also that for the Adams. */
   /* If NQ .gt. MXORDN, we consider changing to order MXORDN on switching. */
   /* Compare the two step sizes to decide whether to switch. */
   /* The step size advantage must be at least 5/RATIO = 1 to switch. */
   /* If the step size for Adams would be so small as to cause */
   /* roundoff pollution, we stay with BDF. */
   /* ----------------------------------------------------------------------- */
 L480:
   exsm = 1. / dls001_3.l;
   if (dlsa01_1.mxordn >= dls001_3.nq)
     {
       goto L484;
     }
   nqm1 = dlsa01_1.mxordn;
   lm1 = dlsa01_1.mxordn + 1;
   exm1 = 1. / lm1;
   lm1p1 = lm1 + 1;
   dm1 = dmnorm_(&dls001_3.n, &yh[lm1p1 * yh_dim1 + 1], &ewt[1]) /
         dlsa01_1.cm1[dlsa01_1.mxordn - 1];
   rh1 = 1. / (pow_dd(&dm1, &exm1) * 1.2 + 1.2e-6);
   goto L486;
 L484:
   dm1 = dsm * (dlsa01_1.cm2[dls001_3.nq - 1] / dlsa01_1.cm1[dls001_3.nq - 1]
               );
   rh1 = 1. / (pow_dd(&dm1, &exsm) * 1.2 + 1.2e-6);
   nqm1 = dls001_3.nq;
   exm1 = exsm;
 L486:
   rh1it = rh1 * 2.;
   pdh = dlsa01_1.pdnorm * fabs(dls001_3.h__);
   if (pdh * rh1 > 1e-5)
     {
       rh1it = sm1[nqm1 - 1] / pdh;
     }
   rh1 = std::min(rh1, rh1it);
   rh2 = 1. / (pow_dd(&dsm, &exsm) * 1.2 + 1.2e-6);
   if (rh1 * dlsa01_1.ratio < rh2 * 5.)
     {
       goto L488;
     }
   alpha = std::max(.001, rh1);
   dm1 = pow_dd(&alpha, &exm1) * dm1;
   if (dm1 <= dls001_3.uround * 1e3 * pnorm)
     {
       goto L488;
     }
   /* The switch test passed.  Reset relevant quantities for Adams. -------- */
   rh = rh1;
   dlsa01_1.icount = 20;
   dls001_3.meth = 1;
   dls001_3.miter = 0;
   dlsa01_1.pdlast = 0.;
   dls001_3.nq = nqm1;
   dls001_3.l = dls001_3.nq + 1;
   goto L170;
   /* No method switch is being made.  Do the usual step/order selection. -- */
 L488:
   --dls001_3.ialth;
   if (dls001_3.ialth == 0)
     {
       goto L520;
     }
   if (dls001_3.ialth > 1)
     {
       goto L700;
     }
   if (dls001_3.l == dls001_3.lmax)
     {
       goto L700;
     }
   i__1 = dls001_3.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L490: */
       yh[i__ + dls001_3.lmax * yh_dim1] = acor[i__];
     }
   goto L700;
   /* ----------------------------------------------------------------------- */
   /* The error test failed.  KFLAG keeps track of multiple failures. */
   /* Restore TN and the YH array to their previous values, and prepare */
   /* to try the step again.  Compute the optimum step size for this or */
   /* one lower order.  After 2 or more failures, H is forced to decrease */
   /* by a factor of 0.2 or less. */
   /* ----------------------------------------------------------------------- */
 L500:
   --dls001_3.kflag;
   dls001_3.tn = told;
   i1 = dls001_3.nqnyh + 1;
   i__1 = dls001_3.nq;
   for (jb = 1; jb <= i__1; ++jb)
     {
       i1 -= *nyh;
       /* DIR$ IVDEP */
       i__2 = dls001_3.nqnyh;
       for (i__ = i1; i__ <= i__2; ++i__)
         {
           /* L510: */
           yh1[i__] -= yh1[i__ + *nyh];
         }
       /* L515: */
     }
   dls001_3.rmax = 2.;
   if (fabs(dls001_3.h__) <= dls001_3.hmin * 1.00001)
     {
       goto L660;
     }
   if (dls001_3.kflag <= -3)
     {
       goto L640;
     }
   iredo = 2;
   rhup = 0.;
   goto L540;
   /* ----------------------------------------------------------------------- */
   /* Regardless of the success or failure of the step, factors */
   /* RHDN, RHSM, and RHUP are computed, by which H could be multiplied */
   /* at order NQ - 1, order NQ, or order NQ + 1, respectively. */
   /* In the case of failure, RHUP = 0.0 to avoid an order increase. */
   /* The largest of these is determined and the new order chosen */
   /* accordingly.  If the order is to be increased, we compute one */
   /* additional scaled derivative. */
   /* ----------------------------------------------------------------------- */
 L520:
   rhup = 0.;
   if (dls001_3.l == dls001_3.lmax)
     {
       goto L540;
     }
   i__1 = dls001_3.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L530: */
       savf[i__] = acor[i__] - yh[i__ + dls001_3.lmax * yh_dim1];
     }
   dup = dmnorm_(&dls001_3.n, &savf[1], &ewt[1]) / dls001_3.tesco[
           dls001_3.nq * 3 - 1];
   exup = 1. / (dls001_3.l + 1);
   rhup = 1. / (pow_dd(&dup, &exup) * 1.4 + 1.4e-6);
 L540:
   exsm = 1. / dls001_3.l;
   rhsm = 1. / (pow_dd(&dsm, &exsm) * 1.2 + 1.2e-6);
   rhdn = 0.;
   if (dls001_3.nq == 1)
     {
       goto L550;
     }
   ddn = dmnorm_(&dls001_3.n, &yh[dls001_3.l * yh_dim1 + 1], &ewt[1]) /
         dls001_3.tesco[dls001_3.nq * 3 - 3];
   exdn = 1. / dls001_3.nq;
   rhdn = 1. / (pow_dd(&ddn, &exdn) * 1.3 + 1.3e-6);
   /* If METH = 1, limit RH according to the stability region also. -------- */
 L550:
   if (dls001_3.meth == 2)
     {
       goto L560;
     }
   /* Computing MAX */
   d__1 = fabs(dls001_3.h__) * dlsa01_1.pdlast;
   pdh = std::max(d__1, 1e-6);
   if (dls001_3.l < dls001_3.lmax)
     {
       /* Computing MIN */
       d__1 = rhup, d__2 = sm1[dls001_3.l - 1] / pdh;
       rhup = std::min(d__1, d__2);
     }
   /* Computing MIN */
   d__1 = rhsm, d__2 = sm1[dls001_3.nq - 1] / pdh;
   rhsm = std::min(d__1, d__2);
   if (dls001_3.nq > 1)
     {
       /* Computing MIN */
       d__1 = rhdn, d__2 = sm1[dls001_3.nq - 2] / pdh;
       rhdn = std::min(d__1, d__2);
     }
   dlsa01_1.pdest = 0.;
 L560:
   if (rhsm >= rhup)
     {
       goto L570;
     }
   if (rhup > rhdn)
     {
       goto L590;
     }
   goto L580;
 L570:
   if (rhsm < rhdn)
     {
       goto L580;
     }
   newq = dls001_3.nq;
   rh = rhsm;
   goto L620;
 L580:
   newq = dls001_3.nq - 1;
   rh = rhdn;
   if (dls001_3.kflag < 0 && rh > 1.)
     {
       rh = 1.;
     }
   goto L620;
 L590:
   newq = dls001_3.l;
   rh = rhup;
   if (rh < 1.1)
     {
       goto L610;
     }
   r__ = dls001_3.el[dls001_3.l - 1] / dls001_3.l;
   i__1 = dls001_3.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L600: */
       yh[i__ + (newq + 1) * yh_dim1] = acor[i__] * r__;
     }
   goto L630;
 L610:
   dls001_3.ialth = 3;
   goto L700;
   /* If METH = 1 and H is restricted by stability, bypass 10 percent test. */
 L620:
   if (dls001_3.meth == 2)
     {
       goto L622;
     }
   if (rh * pdh * 1.00001 >= sm1[newq - 1])
     {
       goto L625;
     }
 L622:
   if (dls001_3.kflag == 0 && rh < 1.1)
     {
       goto L610;
     }
 L625:
   if (dls001_3.kflag <= -2)
     {
       rh = std::min(rh, .2);
     }
   /* ----------------------------------------------------------------------- */
   /* If there is a change of order, reset NQ, L, and the coefficients. */
   /* In any case H is reset according to RH and the YH array is rescaled. */
   /* Then exit from 690 if the step was OK, or redo the step otherwise. */
   /* ----------------------------------------------------------------------- */
   if (newq == dls001_3.nq)
     {
       goto L170;
     }
 L630:
   dls001_3.nq = newq;
   dls001_3.l = dls001_3.nq + 1;
   iret = 2;
   goto L150;
   /* ----------------------------------------------------------------------- */
   /* Control reaches this section if 3 or more failures have occured. */
   /* If 10 failures have occurred, exit with KFLAG = -1. */
   /* It is assumed that the derivatives that have accumulated in the */
   /* YH array have errors of the wrong order.  Hence the first */
   /* derivative is recomputed, and the order is set to 1.  Then */
   /* H is reduced by a factor of 10, and the step is retried, */
   /* until it succeeds or H reaches HMIN. */
   /* ----------------------------------------------------------------------- */
 L640:
   if (dls001_3.kflag == -10)
     {
       goto L660;
     }
   rh = .1;
   /* Computing MAX */
   d__1 = dls001_3.hmin / fabs(dls001_3.h__);
   rh = std::max(d__1, rh);
   dls001_3.h__ *= rh;
   i__1 = dls001_3.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L645: */
       y[i__] = yh[i__ + yh_dim1];
     }
   f(&neq[1], &dls001_3.tn, &y[1], &savf[1]);
   ++dls001_3.nfe;
   i__1 = dls001_3.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L650: */
       yh[i__ + (yh_dim1 << 1)] = dls001_3.h__ * savf[i__];
     }
   dls001_3.ipup = dls001_3.miter;
   dls001_3.ialth = 5;
   if (dls001_3.nq == 1)
     {
       goto L200;
     }
   dls001_3.nq = 1;
   dls001_3.l = 2;
   iret = 3;
   goto L150;
   /* ----------------------------------------------------------------------- */
   /* All returns are made through this section.  H is saved in HOLD */
   /* to allow the caller to change H on the next step. */
   /* ----------------------------------------------------------------------- */
 L660:
   dls001_3.kflag = -1;
   goto L720;
 L670:
   dls001_3.kflag = -2;
   goto L720;
 L680:
   dls001_3.kflag = -3;
   goto L720;
 L690:
   dls001_3.rmax = 10.;
 L700:
   r__ = 1. / dls001_3.tesco[dls001_3.nqu * 3 - 2];
   i__1 = dls001_3.n;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       /* L710: */
       acor[i__] *= r__;
     }
 L720:
   dls001_3.hold = dls001_3.h__;
   dls001_3.jstart = 1;
   return 0;
   /* ----------------------- End of Subroutine DSTODA ---------------------- */
 } /* dstoda_ */
void CInternalSolver::enablePrint (const bool & print = true)
Definition at line 27 of file CInternalSolver.cpp.
References Cxerrwd::enablePrint(), and mxerrwd.
 {
   mxerrwd.enablePrint(print);
 }
void CInternalSolver::resetState ()
Definition at line 39 of file CInternalSolver.cpp.
References CInternalSolver::State::mdls001, mdls001_, CInternalSolver::State::mdlsa01, mdlsa01_, CInternalSolver::State::mdlsr01, mdlsr01_, and mState.
Referenced by CLsodaMethod::peekAhead().
 {
   mdls001_ = mState.mdls001;
   mdlsa01_ = mState.mdlsa01;
   mdlsr01_ = mState.mdlsr01;
 }
void CInternalSolver::saveState ()
Definition at line 32 of file CInternalSolver.cpp.
References CInternalSolver::State::mdls001, mdls001_, CInternalSolver::State::mdlsa01, mdlsa01_, CInternalSolver::State::mdlsr01, mdlsr01_, and mState.
Referenced by CLsodaMethod::peekAhead().
 {
   mState.mdls001 = mdls001_;
   mState.mdlsa01 = mdlsa01_;
   mState.mdlsr01 = mdlsr01_;
 }
void CInternalSolver::setOstream (std::ostream & os)
Definition at line 22 of file CInternalSolver.cpp.
References mxerrwd, and Cxerrwd::setOstream().
Referenced by CLayoutEngine::CLayoutEngine(), CHybridMethodLSODA::integrateDeterministicPart(), CTSSAMethod::integrationMethodStart(), CLyapWolfMethod::start(), and CLsodaMethod::start().
 {
   mxerrwd.setOstream(os);
 }
Member Data Documentation
dls001 CInternalSolver::mdls001_ protected
Definition at line 74 of file CInternalSolver.h.
Referenced by resetState(), and saveState().
dlsa01 CInternalSolver::mdlsa01_ protected
Definition at line 75 of file CInternalSolver.h.
Referenced by resetState(), and saveState().
dlsr01 CInternalSolver::mdlsr01_ protected
Definition at line 76 of file CInternalSolver.h.
Referenced by resetState(), and saveState().
State CInternalSolver::mState protected
Definition at line 77 of file CInternalSolver.h.
Referenced by resetState(), and saveState().
Cxerrwd CInternalSolver::mxerrwd protected
Definition at line 73 of file CInternalSolver.h.
Referenced by dintdy_(), enablePrint(), CLSODAR::operator()(), CLSODA::operator()(), and setOstream().
The documentation for this class was generated from the following files:
CInternalSolver.h
CInternalSolver.cpp
dintdy.cpp
dprja.cpp
drcheck.cpp
dsolsy.cpp
dstoda.cpp