COPASI API: CQTableView Class Reference
CQTableView Class Reference
#include <CQTableView.h>
Public Member Functions
CQTableView (QWidget *pParent=NULL)
virtual void setModel (QAbstractItemModel *model)
virtual ~CQTableView ()
Protected Slots
void slotMoveDown ()
void slotSingleClick ()
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *pEvent)
virtual void mousePressEvent (QMouseEvent *pEvent)
Private Attributes
bool mMoveDown
QAbstractItemModel * mpModel
QMouseEvent * mpMouseEvent
QTimer * mpTimer
Detailed Description
Definition at line 28 of file CQTableView.h.
Constructor & Destructor Documentation
CQTableView::CQTableView (QWidget * pParent = NULL)
Definition at line 13 of file CQTableView.cpp.
References mpTimer, and slotSingleClick().
                                          :
   QTableView(pParent),
   mpTimer(NULL),
   mpMouseEvent(NULL),
   mMoveDown(false),
   mpModel(NULL)
 {
   mpTimer = new QTimer(this);
   mpTimer->setSingleShot(true);
   mpTimer->setInterval(250);
   connect(mpTimer, SIGNAL(timeout()), this, SLOT(slotSingleClick()));
 }
CQTableView::~CQTableView () virtual
Definition at line 28 of file CQTableView.cpp.
 {}
Member Function Documentation
void CQTableView::keyPressEvent (QKeyEvent * pEvent) protected virtual
Definition at line 48 of file CQTableView.cpp.
References mMoveDown.
 {
   QTableView::keyPressEvent(pEvent);
   switch (pEvent->key())
     {
       case Qt::Key_Return:
       case Qt::Key_Enter:
         mMoveDown = true;
         break;
       default:
         mMoveDown = false;
         break;
     }
 }
void CQTableView::mousePressEvent (QMouseEvent * pEvent) protected virtual
Definition at line 66 of file CQTableView.cpp.
References mpMouseEvent, and mpTimer.
 {
   if (mpMouseEvent != NULL)
     {
       delete mpMouseEvent;
       mpMouseEvent = NULL;
     }
   if (mpTimer->isActive())
     {
       QTableView::mousePressEvent(pEvent);
       emit doubleClicked(currentIndex());
       return;
     }
   mpMouseEvent = new QMouseEvent(*pEvent);
   pEvent->accept();
   mpTimer->start();
 }
void CQTableView::setModel (QAbstractItemModel * model) virtual
Definition at line 32 of file CQTableView.cpp.
References mpModel, and slotMoveDown().
 {
   if (mpModel != NULL)
     disconnect(mpModel, SIGNAL(dataChanged(const QModelIndex &, const QModelIndex)),
                this, SLOT(slotMoveDown()));
   mpModel = model;
   if (mpModel != NULL)
     connect(mpModel, SIGNAL(dataChanged(const QModelIndex &, const QModelIndex)),
             this, SLOT(slotMoveDown()));
   QTableView::setModel(model);
 }
void CQTableView::slotMoveDown () protected slot
Definition at line 96 of file CQTableView.cpp.
References mMoveDown.
Referenced by setModel().
 {
   if (mMoveDown)
     {
       QKeyEvent Down(QEvent::KeyPress, Qt::Key_Down, Qt::NoModifier);
       QTableView::keyPressEvent(&Down);
     }
 }
void CQTableView::slotSingleClick () protected slot
Definition at line 87 of file CQTableView.cpp.
References mpMouseEvent.
Referenced by CQTableView().
 {
   if (mpMouseEvent != NULL)
     {
       QTableView::mousePressEvent(mpMouseEvent);
       mpMouseEvent = NULL;
     }
 }
Member Data Documentation
bool CQTableView::mMoveDown private
Definition at line 50 of file CQTableView.h.
Referenced by keyPressEvent(), and slotMoveDown().
QAbstractItemModel* CQTableView::mpModel private
Definition at line 51 of file CQTableView.h.
Referenced by setModel().
QMouseEvent* CQTableView::mpMouseEvent private
Definition at line 49 of file CQTableView.h.
Referenced by mousePressEvent(), and slotSingleClick().
QTimer* CQTableView::mpTimer private
Definition at line 48 of file CQTableView.h.
Referenced by CQTableView(), and mousePressEvent().
The documentation for this class was generated from the following files:
CQTableView.h
CQTableView.cpp