COPASI API: CQFittingWidget Class Reference
CQFittingWidget Class Reference
#include <CQFittingWidget.h>
Public Slots
void slotConstraintNumberChanged (int number)
void slotParameterNumberChanged (int number)
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Public Member Functions
CQFittingWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
~CQFittingWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void slotCrossValidationData ()
void slotExperimentData ()
void slotPageChange (QWidget *currentPage)
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Protected Attributes
std::map< std::string,
std::string > mCrossValidationKeyMap
std::map< std::string,
std::string > mExperimentKeyMap
size_t mnParamterSetsBeforeRun
CCrossValidationSet * mpCrossValidationSet
CQFittingItemWidget * mpCurrentList
CExperimentSet * mpExperimentSet
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Private Member Functions
void destroy ()
void init ()
Detailed Description
Definition at line 26 of file CQFittingWidget.h.
Constructor & Destructor Documentation
CQFittingWidget::CQFittingWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 48 of file CQFittingWidget.cpp.
References init().
   : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQFittingWidget::~CQFittingWidget ()
Definition at line 59 of file CQFittingWidget.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQFittingWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 289 of file CQFittingWidget.cpp.
References CFitMethod::createMethod().
 {return CFitMethod::createMethod(type);}
void CQFittingWidget::destroy () private
Definition at line 384 of file CQFittingWidget.cpp.
References mpCrossValidationSet, mpExperimentSet, and pdelete.
Referenced by ~CQFittingWidget().
 {
   pdelete(mpExperimentSet);
   pdelete(mpCrossValidationSet);
 }
void CQFittingWidget::init () private
Definition at line 348 of file CQFittingWidget.cpp.
References CQFittingItemWidget::FIT_CONSTRAINT, CQFittingItemWidget::FIT_ITEM, TaskWidget::mpBtnWidget, mpCrossValidationSet, mpCurrentList, mpExperimentSet, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, CQTaskHeaderWidget::setTaskName(), CQTaskMethodWidget::setValidMethods(), CQTaskMethodWidget::showMethodParameters(), slotConstraintNumberChanged(), slotParameterNumberChanged(), and COptTask::ValidMethods.
Referenced by CQFittingWidget().
 {
   mpHeaderWidget->setTaskName("Parameter Estimation");
   verticalLayout->insertWidget(0, mpHeaderWidget);
   // verticalLayout->insertSpacing(1, 14);      // space between header and body
   mpMethodWidget->setValidMethods(CFitTask::ValidMethods);
   mpMethodWidget->showMethodParameters(true);
   verticalLayout->addWidget(mpMethodWidget);
   verticalLayout->addWidget(mpBtnWidget);
   mpParameters->setItemType(CQFittingItemWidget::FIT_ITEM);
   connect(mpParameters, SIGNAL(numberChanged(int)), this, SLOT(slotParameterNumberChanged(int)));
   mpConstraints->setItemType(CQFittingItemWidget::FIT_CONSTRAINT);
   connect(mpConstraints, SIGNAL(numberChanged(int)), this, SLOT(slotConstraintNumberChanged(int)));
   mpCurrentList = mpParameters;
   mpExperimentSet = NULL;
   mpCrossValidationSet = NULL;
 }
bool CQFittingWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 224 of file CQFittingWidget.cpp.
References CQMessageBox::critical(), CCopasiMessage::ERROR, CCopasiMessage::getAllMessageText(), COptProblem::getCalculateStatistics(), CFitProblem::getCreateParameterSets(), CExperimentSet::getExperiment(), CExperimentSet::getExperimentCount(), CCopasiParameterGroup::getGroup(), CCopasiTask::getProblem(), COptProblem::getRandomizeStartValues(), CCopasiMessage::getType(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), TaskWidget::mChanged, mCrossValidationKeyMap, mExperimentKeyMap, mpCrossValidationSet, CopasiWidget::mpDataModel, mpExperimentSet, TaskWidget::mpTask, pdelete, CCopasiMessage::peekLastMessage(), and pTask.
 {
   CFitTask * pTask =
     dynamic_cast< CFitTask * >(mpTask);
   if (!pTask) return false;
   loadCommon();
   loadMethod();
   CFitProblem * pProblem =
     dynamic_cast<CFitProblem *>(mpTask->getProblem());
   if (!pProblem) return false;
   pdelete(mpExperimentSet)
   CExperimentSet * pExperimentSet =
     dynamic_cast<CExperimentSet *>(pProblem->getGroup("Experiment Set"));
   mpExperimentSet = new CExperimentSet(*pExperimentSet);
   mExperimentKeyMap.clear();
   size_t i, imax = mpExperimentSet->getExperimentCount();
   for (i = 0; i < imax; i++)
     mExperimentKeyMap[pExperimentSet->getExperiment(i)->CCopasiParameter::getKey()] =
       mpExperimentSet->getExperiment(i)->CCopasiParameter::getKey();
   pdelete(mpCrossValidationSet)
   CCrossValidationSet * pCrossValidationSet =
     dynamic_cast<CCrossValidationSet *>(pProblem->getGroup("Validation Set"));
   mpCrossValidationSet = new CCrossValidationSet(*pCrossValidationSet);
   mCrossValidationKeyMap.clear();
   imax = mpCrossValidationSet->getExperimentCount();
   for (i = 0; i < imax; i++)
     mCrossValidationKeyMap[pCrossValidationSet->getExperiment(i)->CCopasiParameter::getKey()] =
       mpCrossValidationSet->getExperiment(i)->CCopasiParameter::getKey();
   mpCheckRandomize->setChecked(pProblem->getRandomizeStartValues());
   mpCreateParameterSets->setChecked(pProblem->getCreateParameterSets());
   mpCheckStatistics->setChecked(pProblem->getCalculateStatistics());
   mpParameters->load(mpDataModel, pProblem->getGroup("OptimizationItemList"), &mExperimentKeyMap, &mCrossValidationKeyMap);
   if (CCopasiMessage::peekLastMessage().getType() == CCopasiMessage::ERROR)
     {
       CQMessageBox::critical(this, "Error loading Parameter estimation task",
                              CCopasiMessage::getAllMessageText().c_str(),
                              QMessageBox::Ok | QMessageBox::Default,
                              QMessageBox::NoButton);
     }
   mpParameters->setExperimentSet(const_cast<const CExperimentSet *&>(mpExperimentSet));
   mpParameters->setCrossValidationSet(const_cast<const CCrossValidationSet *&>(mpCrossValidationSet));
   mpConstraints->load(mpDataModel, pProblem->getGroup("OptimizationConstraintList"), &mExperimentKeyMap, &mCrossValidationKeyMap);
   mpConstraints->setExperimentSet(const_cast<const CExperimentSet *&>(mpExperimentSet));
   mpConstraints->setCrossValidationSet(const_cast<const CCrossValidationSet *&>(mpCrossValidationSet));
   mChanged = false;
   return true;
 }
bool CQFittingWidget::runTask () virtual
Implements TaskWidget.
Definition at line 292 of file CQFittingWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CModel::getModelParameterSets(), CCopasiObject::getObjectDataModel(), CopasiWidget::mKey, mnParamterSetsBeforeRun, pTask, and CCopasiVector< T >::size().
Referenced by SliderDialog::runParameterEstimationTask().
 {
   CFitTask * pTask =
     dynamic_cast< CFitTask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!pTask) return false;
   mnParamterSetsBeforeRun = pTask->getObjectDataModel()->getModel()->getModelParameterSets().size();
   if (!commonBeforeRunTask()) return false;
   bool success = commonRunTask();
   return success;
 }
bool CQFittingWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 65 of file CQFittingWidget.cpp.
References CExperimentSet::addExperiment(), C_INVALID_INDEX, CKeyFactory::get(), COptProblem::getCalculateStatistics(), CFitProblem::getCreateParameterSets(), CCopasiRootContainer::getDatamodelList(), CExperimentSet::getExperiment(), CExperimentSet::getExperimentCount(), CCopasiParameterGroup::getGroup(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CCopasiTask::getProblem(), COptProblem::getRandomizeStartValues(), CCrossValidationSet::getThreshold(), CCrossValidationSet::getWeight(), if(), TaskWidget::mChanged, mCrossValidationKeyMap, mExperimentKeyMap, mpCrossValidationSet, mpExperimentSet, TaskWidget::mpTask, pTask, CExperimentSet::removeExperiment(), TaskWidget::saveCommon(), TaskWidget::saveMethod(), COptProblem::setCalculateStatistics(), CFitProblem::setCreateParameterSets(), COptProblem::setRandomizeStartValues(), and CCrossValidationSet::setWeight().
 {
   CFitTask * pTask =
     dynamic_cast< CFitTask * >(mpTask);
   if (!pTask) return false;
   saveCommon();
   saveMethod();
   CFitProblem * pProblem =
     dynamic_cast<CFitProblem *>(mpTask->getProblem());
   if (!pProblem) return false;
   std::map<std::string, std::string> ExperimentMap;
   std::map<std::string, std::string> CrossValidationMap;
   // Save experiment set
   CExperimentSet * pExperimentSet =
     dynamic_cast<CExperimentSet *>(pProblem->getGroup("Experiment Set"));
   std::string Name;
   CExperiment * pExperiment;
   size_t i, imax;
   std::set<CExperiment *> DealtWith;
   for (i = pExperimentSet->getExperimentCount() - 1; i != C_INVALID_INDEX; i--)
     {
       pExperiment =
         dynamic_cast<CExperiment *>(CCopasiRootContainer::getKeyFactory()->get(mExperimentKeyMap[pExperimentSet->getExperiment(i)->CCopasiParameter::getKey()]));
       if (pExperiment && pExperiment == mpExperimentSet->getExperiment(pExperiment->getObjectName()))
         {
           if (!(*pExperimentSet->getExperiment(i) == *pExperiment))
             {
               *pExperimentSet->getExperiment(i) = *pExperiment;
               mChanged = true;
             }
           DealtWith.insert(pExperiment);
         }
       else
         {
           mExperimentKeyMap.erase(pExperimentSet->getExperiment(i)->CCopasiParameter::getKey());
           pExperimentSet->removeExperiment(i);
           mChanged = true;
         }
     }
   for (i = 0, imax = mpExperimentSet->getExperimentCount(); i < imax; i++)
     {
       pExperiment = mpExperimentSet->getExperiment(i);
       if (DealtWith.count(pExperiment)) continue;
       pExperiment = pExperimentSet->addExperiment(*pExperiment);
       mExperimentKeyMap[pExperiment->CCopasiParameter::getKey()] =
         mpExperimentSet->getExperiment(i)->CCopasiParameter::getKey();
       mChanged = true;
     }
   // We need to invert the key map for saving!
   std::map<std::string, std::string>::iterator it = mExperimentKeyMap.begin();
   std::map<std::string, std::string>::iterator end = mExperimentKeyMap.end();
   for (; it != end; ++it)
     ExperimentMap[it->second] = it->first;
   // Save cross validation experiment set
   CCrossValidationSet * pCrossValidationSet =
     dynamic_cast<CCrossValidationSet *>(pProblem->getGroup("Validation Set"));
   if (pCrossValidationSet->getWeight() != mpCrossValidationSet->getWeight())
     {
       pCrossValidationSet->setWeight(mpCrossValidationSet->getWeight());
       mChanged = true;
     }
   if (pCrossValidationSet->getThreshold() != mpCrossValidationSet->getThreshold())
     {
       pCrossValidationSet->setThreshold(mpCrossValidationSet->getThreshold());
       mChanged = true;
     }
   DealtWith.clear();
   for (i = pCrossValidationSet->getExperimentCount() - 1; i != C_INVALID_INDEX; i--)
     {
       pExperiment =
         dynamic_cast<CExperiment *>(CCopasiRootContainer::getKeyFactory()->get(mCrossValidationKeyMap[pCrossValidationSet->getExperiment(i)->CCopasiParameter::getKey()]));
       if (pExperiment && pExperiment == mpCrossValidationSet->getExperiment(pExperiment->getObjectName()))
         {
           if (!(*pCrossValidationSet->getExperiment(i) == *pExperiment))
             {
               *pCrossValidationSet->getExperiment(i) = *pExperiment;
               mChanged = true;
             }
           DealtWith.insert(pExperiment);
         }
       else
         {
           mCrossValidationKeyMap.erase(pCrossValidationSet->getExperiment(i)->CCopasiParameter::getKey());
           pCrossValidationSet->removeExperiment(i);
           mChanged = true;
         }
     }
   for (i = 0, imax = mpCrossValidationSet->getExperimentCount(); i < imax; i++)
     {
       pExperiment = mpCrossValidationSet->getExperiment(i);
       if (DealtWith.count(pExperiment)) continue;
       pExperiment = pCrossValidationSet->addExperiment(*pExperiment);
       mCrossValidationKeyMap[pExperiment->CCopasiParameter::getKey()] =
         mpCrossValidationSet->getExperiment(i)->CCopasiParameter::getKey();
       mChanged = true;
     }
   // We need to invert the key map for saving!
   it = mCrossValidationKeyMap.begin();
   end = mCrossValidationKeyMap.end();
   for (; it != end; ++it)
     CrossValidationMap[it->second] = it->first;
   if (mpCheckRandomize->isChecked() != pProblem->getRandomizeStartValues())
     {
       mChanged = true;
       pProblem->setRandomizeStartValues(mpCheckRandomize->isChecked());
     }
   if (mpCreateParameterSets->isChecked() != pProblem->getCreateParameterSets())
     {
       mChanged = true;
       pProblem->setCreateParameterSets(mpCreateParameterSets->isChecked());
     }
   if (mpCheckStatistics->isChecked() != pProblem->getCalculateStatistics())
     {
       mChanged = true;
       pProblem->setCalculateStatistics(mpCheckStatistics->isChecked());
     }
   mChanged |= mpParameters->save(&ExperimentMap, &CrossValidationMap);
   mChanged |= mpConstraints->save(&ExperimentMap, &CrossValidationMap);
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (mChanged)(*CCopasiRootContainer::getDatamodelList())[0]->changed();
   mChanged = false;
   return true;
 }
void CQFittingWidget::slotConstraintNumberChanged (int number) slot
Definition at line 378 of file CQFittingWidget.cpp.
Referenced by init().
 {
   QString TabLabel = "Constraints (" + QString::number(number) + ")";
   mpTabWidget->setTabText(mpTabWidget->indexOf(mpConstraints), TabLabel);
 }
void CQFittingWidget::slotCrossValidationData () protected slot
Definition at line 390 of file CQFittingWidget.cpp.
References CQExperimentData::load(), mpCrossValidationSet, CopasiWidget::mpDataModel, and pdelete.
 {
   CQExperimentData * pDialog = new CQExperimentData(this);
   pDialog->load(mpCrossValidationSet, mpDataModel);
   connect(pDialog, SIGNAL(experimentChanged()), mpParameters, SLOT(slotCrossValidationChanged()));
   connect(pDialog, SIGNAL(experimentChanged()), mpConstraints, SLOT(slotCrossValidationChanged()));
   pDialog->exec();
   pdelete(pDialog);
 }
void CQFittingWidget::slotExperimentData () protected slot
Definition at line 327 of file CQFittingWidget.cpp.
References CQExperimentData::load(), CopasiWidget::mpDataModel, mpExperimentSet, and pdelete.
 {
   CQExperimentData * pDialog = new CQExperimentData(this);
   pDialog->load(mpExperimentSet, mpDataModel);
   connect(pDialog, SIGNAL(experimentChanged()), mpParameters, SLOT(slotExperimentChanged()));
   connect(pDialog, SIGNAL(experimentChanged()), mpConstraints, SLOT(slotExperimentChanged()));
   pDialog->exec();
   pdelete(pDialog);
 }
void CQFittingWidget::slotPageChange (QWidget * currentPage) protected slot
Definition at line 340 of file CQFittingWidget.cpp.
References mpCurrentList.
 {
   if (mpTabWidget->tabText(mpTabWidget->indexOf(currentPage)).contains("Parameters", Qt::CaseSensitive))
     mpCurrentList = mpParameters;
   else
     mpCurrentList = mpConstraints;
 }
void CQFittingWidget::slotParameterNumberChanged (int number) slot
Definition at line 372 of file CQFittingWidget.cpp.
Referenced by init().
 {
   QString TabLabel = "Parameters (" + QString::number(number) + ")";
   mpTabWidget->setTabText(mpTabWidget->indexOf(mpParameters), TabLabel);
 }
bool CQFittingWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 308 of file CQFittingWidget.cpp.
References ListViews::ADD, CKeyFactory::get(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CModel::getModelParameterSets(), CCopasiObject::getObjectDataModel(), CopasiWidget::mKey, mnParamterSetsBeforeRun, ListViews::MODELPARAMETERSET, CopasiWidget::protectedNotify(), pTask, CCopasiVector< T >::size(), and TaskWidget::taskFinishedEvent().
 {
   bool result = TaskWidget::taskFinishedEvent();
   CFitTask * pTask =
     dynamic_cast< CFitTask * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (!pTask) return false;
   size_t finalCount = pTask->getObjectDataModel()->getModel()->getModelParameterSets().size();
   for (size_t i = mnParamterSetsBeforeRun; i < finalCount; ++i)
     {
       protectedNotify(ListViews::MODELPARAMETERSET, ListViews::ADD, pTask->getObjectDataModel()->getModel()->getModelParameterSets()[i]->getKey());
     }
   return true;
 }
Member Data Documentation
std::map<std::string, std::string> CQFittingWidget::mCrossValidationKeyMap protected
Definition at line 45 of file CQFittingWidget.h.
Referenced by loadTask(), and saveTask().
std::map<std::string, std::string> CQFittingWidget::mExperimentKeyMap protected
Definition at line 43 of file CQFittingWidget.h.
Referenced by loadTask(), and saveTask().
size_t CQFittingWidget::mnParamterSetsBeforeRun protected
Definition at line 46 of file CQFittingWidget.h.
Referenced by runTask(), and taskFinishedEvent().
CCrossValidationSet* CQFittingWidget::mpCrossValidationSet protected
Definition at line 44 of file CQFittingWidget.h.
Referenced by destroy(), init(), loadTask(), saveTask(), and slotCrossValidationData().
CQFittingItemWidget* CQFittingWidget::mpCurrentList protected
Definition at line 41 of file CQFittingWidget.h.
Referenced by init(), and slotPageChange().
CExperimentSet* CQFittingWidget::mpExperimentSet protected
Definition at line 42 of file CQFittingWidget.h.
Referenced by destroy(), init(), loadTask(), saveTask(), and slotExperimentData().
The documentation for this class was generated from the following files:
CQFittingWidget.h
CQFittingWidget.cpp