COPASI API: CCopasiXMLParser::LineEndingElement Class Reference
CCopasiXMLParser::LineEndingElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
LineEndingElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~LineEndingElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { LineEnding = 0, BoundingBox, Group }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4034 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::LineEndingElement::Element private
Enumerator
LineEnding
BoundingBox
Group
Definition at line 4041 of file CCopasiXMLParser.h.
     {
       LineEnding = 0,
       BoundingBox,
       Group
     };
Constructor & Destructor Documentation
CCopasiXMLParser::LineEndingElement::LineEndingElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 13112 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::LineEndingElement::~LineEndingElement () virtual
Destructor
Definition at line 13117 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::LineEndingElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 13206 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, pdelete, SCopasiXMLParserCommon::pLineEnding, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case LineEnding:
         if (strcmp(pszName, "LineEnding"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "LineEnding", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCommon.pLineEnding = NULL;
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case BoundingBox:
         if (strcmp(pszName, "BoundingBox"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "BoundingBox", mParser.getCurrentLineNumber());
         pdelete(mpCurrentHandler);
         break;
       case Group:
         if (strcmp(pszName, "Group"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Group", mParser.getCurrentLineNumber());
         //tell the handler where to continue
         mCurrentElement = LineEnding;
         pdelete(mpCurrentHandler);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::LineEndingElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 13122 of file CCopasiXMLParser.cpp.
References CLRenderInformationBase::addLineEnding(), CCopasiMessage::EXCEPTION, CLRenderInformationBase::getLineEnding(), CLRenderInformationBase::getNumLineEndings(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pLineEnding, SCopasiXMLParserCommon::pRenderInformation, CLLineEnding::setEnableRotationalMapping(), CLLineEnding::setId(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   mpCurrentHandler = NULL;
   const char * Id;
   const char * EnableRotationalMapping;
   CLLineEnding* pLineEnding = NULL;
   switch (mCurrentElement)
     {
       case LineEnding:
         if (strcmp(pszName, "LineEnding"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "LineEnding", mParser.getCurrentLineNumber());
         Id = mParser.getAttributeValue("id", papszAttrs);
         EnableRotationalMapping = mParser.getAttributeValue("enableRotationalMapping", papszAttrs, "true");
         pLineEnding = new CLLineEnding();
         pLineEnding->setId(Id);
         if (!strcmp(EnableRotationalMapping, "true"))
           {
             pLineEnding->setEnableRotationalMapping(true);
           }
         else
           {
             pLineEnding->setEnableRotationalMapping(false);
           }
         mCommon.pRenderInformation->addLineEnding(pLineEnding);
         // delete the line ending again since the addLineEnding method made a copy
         delete pLineEnding;
         assert(mCommon.pRenderInformation->getNumLineEndings() > 0);
         mCommon.pLineEnding = mCommon.pRenderInformation->getLineEnding(mCommon.pRenderInformation->getNumLineEndings() - 1);
         break;
       case BoundingBox:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "BoundingBox"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "BoundingBox", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new BoundingBoxElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       case Group:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "Group"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Group", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new GroupElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp