COPASI API: CMIRIAMInfo Class Reference
CMIRIAMInfo Class Reference
#include <CModelMIRIAMInfo.h>
Public Member Functions
CMIRIAMInfo ()
CBiologicalDescription * createBiologicalDescription ()
CCreator * createCreator (const std::string &objectName)
CModification * createModification (const std::string &objectName)
CReference * createReference (const std::string &objectName)
const CCopasiVector
< CBiologicalDescription > & getBiologicalDescriptions () const
const std::string getCreatedDT () const
const CCopasiVector< CCreator > & getCreators () const
virtual const std::string & getKey () const
const CCopasiVector
< CModification > & getModifications () const
CRDFGraph * getRDFGraph ()
const CCopasiVector< CReference > & getReferences () const
void load (const std::string &key="")
void loadBiologicalDescriptions ()
void loadCreators ()
void loadModifications ()
void loadReferences ()
bool removeBiologicalDescription (int position)
bool removeCreator (int position)
bool removeModification (int position)
bool removeReference (int position)
bool save ()
void setCreatedDT (const std::string &dt)
~CMIRIAMInfo ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
CCopasiVector
< CBiologicalDescription > mBiologicalDescriptions
CRDFTriplet mCreated
CRDFObject mCreatedObj
CCopasiVector< CCreator > mCreators
std::string mKey
CCopasiVector< CModification > mModifications
CRDFGraph * mpRDFGraph
CCopasiVector< CReference > mReferences
CRDFTriplet mTriplet
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CMIRIAMInfo: Stores all MIRIAM info for a Model.
Definition at line 38 of file CModelMIRIAMInfo.h.
Constructor & Destructor Documentation
CMIRIAMInfo::CMIRIAMInfo ()
Definition at line 37 of file CModelMIRIAMInfo.cpp.
                          :
   CCopasiContainer("CMIRIAMInfoObject", NULL, "CMIRIAMInfo"),
   mKey(""),
   mCreators("Creators", this),
   mReferences("References", this),
   mModifications("Modifieds", this),
   mBiologicalDescriptions("BiologicalDescriptions", this),
   mCreatedObj(),
   mpRDFGraph(NULL),
   mTriplet(NULL, CRDFPredicate::about, NULL),
   mCreated()
 {}
CMIRIAMInfo::~CMIRIAMInfo ()
Definition at line 50 of file CModelMIRIAMInfo.cpp.
References mpRDFGraph, and pdelete.
 {pdelete(mpRDFGraph);}
Member Function Documentation
CBiologicalDescription * CMIRIAMInfo::createBiologicalDescription ()
Definition at line 312 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CRDFGraph::addTriplet(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), mBiologicalDescriptions, mpRDFGraph, CRDFObject::RESOURCE, CRDFObject::setResource(), and CRDFObject::setType().
Referenced by CQBiologicalDescriptionDM::insertRows().
 {
   const CRDFSubject & Subject = mpRDFGraph->getAboutNode()->getSubject();
   CRDFObject Object;
   Object.setType(CRDFObject::RESOURCE);
   Object.setResource("", false);
   CRDFTriplet Triplet = mpRDFGraph->addTriplet(Subject, std::string("---"), Object);
   if (!Triplet)
     return NULL;
   CBiologicalDescription * pBiologicalDescription =
     new CBiologicalDescription(Triplet);
   if (!mBiologicalDescriptions.add(pBiologicalDescription, true))
     {
       delete pBiologicalDescription;
       return NULL;
     }
   return pBiologicalDescription;
 }
CCreator * CMIRIAMInfo::createCreator (const std::string & objectName)
Definition at line 59 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_creator, CRDFGraph::generatedNodeId(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mCreators, mpRDFGraph, CRDFObject::setBlankNodeId(), and CRDFObject::setType().
Referenced by CQCreatorDM::insertRows().
 {
   const CRDFSubject & Subject = mpRDFGraph->getAboutNode()->getSubject();
   CRDFObject Object;
   Object.setType(CRDFObject::BLANK_NODE);
   std::string Id = mpRDFGraph->generatedNodeId();
   Object.setBlankNodeId(Id);
   CRDFTriplet Triplet =
     mpRDFGraph->addTriplet(Subject,
                            CRDFPredicate::getURI(CRDFPredicate::dcterms_creator),
                            Object);
   if (!Triplet)
     return NULL;
   CCreator * pCreator = new CCreator(Triplet);
   if (!mCreators.add(pCreator, true))
     {
       delete pCreator;
       return NULL;
     }
   return pCreator;
 }
CModification * CMIRIAMInfo::createModification (const std::string & objectName)
Definition at line 248 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_modified, CRDFGraph::generatedNodeId(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mModifications, mpRDFGraph, CRDFObject::setBlankNodeId(), CModification::setDate(), and CRDFObject::setType().
Referenced by CQModifiedDM::insertRows().
 {
   const CRDFSubject & Subject = mpRDFGraph->getAboutNode()->getSubject();
   CRDFObject Object;
   Object.setType(CRDFObject::BLANK_NODE);
   std::string Id = mpRDFGraph->generatedNodeId();
   Object.setBlankNodeId(Id);
   CRDFTriplet Triplet =
     mpRDFGraph->addTriplet(Subject,
                            CRDFPredicate::getURI(CRDFPredicate::dcterms_modified),
                            Object);
   if (!Triplet)
     return NULL;
   CModification * pModification = new CModification(Triplet);
   if (dateTime.size())
     pModification->setDate(dateTime);
   if (!mModifications.add(pModification, true))
     {
       delete pModification;
       return NULL;
     }
   return pModification;
 }
CReference * CMIRIAMInfo::createReference (const std::string & objectName)
Definition at line 137 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_bibliographicCitation, CRDFGraph::generatedNodeId(), CRDFGraph::getAboutNode(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mpRDFGraph, mReferences, CRDFObject::setBlankNodeId(), and CRDFObject::setType().
Referenced by CQReferenceDM::insertRows().
 {
   const CRDFSubject & Subject = mpRDFGraph->getAboutNode()->getSubject();
   CRDFObject Object;
   Object.setType(CRDFObject::BLANK_NODE);
   std::string Id = mpRDFGraph->generatedNodeId();
   Object.setBlankNodeId(Id);
   CRDFTriplet Triplet =
     mpRDFGraph->addTriplet(Subject,
                            CRDFPredicate::getURI(CRDFPredicate::dcterms_bibliographicCitation),
                            Object);
   if (!Triplet)
     return NULL;
   CReference * pReference = new CReference(Triplet);
   if (!mReferences.add(pReference, true))
     {
       delete pReference;
       return NULL;
     }
   return pReference;
 }
const CCopasiVector< CBiologicalDescription > & CMIRIAMInfo::getBiologicalDescriptions () const
Definition at line 309 of file CModelMIRIAMInfo.cpp.
References mBiologicalDescriptions.
Referenced by CQBiologicalDescriptionDM::data(), CQBiologicalDescriptionDM::removeRows(), CQBiologicalDescriptionDM::rowCount(), CQBiologicalDescriptionDM::setData(), CQMiriamWidget::slotBtnBrowseDescription(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return mBiologicalDescriptions;}
const std::string CMIRIAMInfo::getCreatedDT () const
Definition at line 212 of file CModelMIRIAMInfo.cpp.
References CRDFPredicate::dcterms_W3CDTF, CRDFNode::getFieldValue(), mCreated, and CRDFTriplet::pObject.
Referenced by CQMiriamWidget::showEvent(), CQMiriamWidget::slotCreatedDTChanged(), CQMiriamWidget::update(), and CSBMLExporter::updateMIRIAMAnnotation().
 {
   if (!mCreated)
     return "";
   return mCreated.pObject->getFieldValue(CRDFPredicate::dcterms_W3CDTF);
 }
const CCopasiVector< CCreator > & CMIRIAMInfo::getCreators () const
Definition at line 56 of file CModelMIRIAMInfo.cpp.
References mCreators.
Referenced by CQCreatorDM::data(), CQCreatorDM::removeRows(), CQCreatorDM::rowCount(), CQCreatorDM::setData(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return mCreators;}
const std::string & CMIRIAMInfo::getKey () const virtual
Reimplemented from CCopasiObject.
Definition at line 475 of file CModelMIRIAMInfo.cpp.
References mKey.
Referenced by CQMiriamWidget::update().
 {return mKey;}
const CCopasiVector< CModification > & CMIRIAMInfo::getModifications () const
Definition at line 245 of file CModelMIRIAMInfo.cpp.
References mModifications.
Referenced by CQModifiedDM::data(), CQModifiedDM::removeRows(), CQModifiedDM::rowCount(), CQModifiedDM::setData(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return mModifications;}
CRDFGraph * CMIRIAMInfo::getRDFGraph ()
Definition at line 53 of file CModelMIRIAMInfo.cpp.
References mpRDFGraph.
 {return mpRDFGraph;}
const CCopasiVector< CReference > & CMIRIAMInfo::getReferences () const
Definition at line 134 of file CModelMIRIAMInfo.cpp.
References mReferences.
Referenced by CQReferenceDM::data(), CQReferenceDM::removeRows(), CQReferenceDM::rowCount(), CQReferenceDM::setData(), CQMiriamWidget::slotBtnBrowseReference(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return mReferences;}
void CMIRIAMInfo::load (const std::string & key = "")
Definition at line 399 of file CModelMIRIAMInfo.cpp.
References CAnnotation::castObject(), CRDFGraph::createAboutNode(), CRDFPredicate::dcterms_created, CKeyFactory::get(), CRDFNode::getDescendantsWithPredicate(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CRDFNode::getPath(), CRDFParser::graphFromXml(), loadBiologicalDescriptions(), loadCreators(), loadModifications(), loadReferences(), mCreated, mKey, mpRDFGraph, mTriplet, pdelete, and CRDFTriplet::pObject.
Referenced by CQMiriamWidget::showEvent(), test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000092::test_miriam_import_1(), CQMiriamWidget::update(), and CSBMLExporter::updateMIRIAMAnnotation().
 {
   pdelete(mpRDFGraph);
   mKey = key;
   CCopasiObject * pCopasiObject = dynamic_cast< CCopasiObject * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (pCopasiObject != NULL)
     {
       const std::string * pMiriamAnnotation = NULL;
       CAnnotation * pAnnotation = CAnnotation::castObject(pCopasiObject);
       if (pAnnotation != NULL)
         {
           pMiriamAnnotation = &pAnnotation->getMiriamAnnotation();
         }
       if (pMiriamAnnotation && *pMiriamAnnotation != "")
         mpRDFGraph = CRDFParser::graphFromXml(*pMiriamAnnotation);
     }
   if (mpRDFGraph == NULL)
     mpRDFGraph = new CRDFGraph;
   // We make sure that we always have an about node.
   if (pCopasiObject != NULL)
     mTriplet.pObject = mpRDFGraph->createAboutNode(pCopasiObject->getKey());
   else
     mTriplet.pObject = mpRDFGraph->createAboutNode("");
   // Load the created date if set;
   CRDFPredicate::Path Path = mTriplet.pObject->getPath();
   std::set< CRDFTriplet > Triples =
     mTriplet.pObject->getDescendantsWithPredicate(CRDFPredicate::dcterms_created);
   if (Triples.size() > 0)
     mCreated = *Triples.begin();
   else
     mCreated = CRDFTriplet(); // This is an invalid triplet, i.e., !mCreated is true.
   loadCreators();
   loadReferences();
   loadModifications();
   loadBiologicalDescriptions();
   return;
 }
void CMIRIAMInfo::loadBiologicalDescriptions ()
Definition at line 353 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CRDFPredicate::bqbiol_encodes, CRDFPredicate::bqbiol_hasPart, CRDFPredicate::bqbiol_hasVersion, CRDFPredicate::bqbiol_is, CRDFPredicate::bqbiol_isEncodedBy, CRDFPredicate::bqbiol_isHomologTo, CRDFPredicate::bqbiol_isPartOf, CRDFPredicate::bqbiol_isVersionOf, CRDFPredicate::bqbiol_occursIn, CRDFPredicate::bqmodel_is, CCopasiVector< T >::cleanup(), CRDFPredicate::copasi_encodes, CRDFPredicate::copasi_hasPart, CRDFPredicate::copasi_hasVersion, CRDFPredicate::copasi_is, CRDFPredicate::copasi_isEncodedBy, CRDFPredicate::copasi_isHomologTo, CRDFPredicate::copasi_isPartOf, CRDFPredicate::copasi_isVersionOf, CRDFPredicate::copasi_occursIn, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), mBiologicalDescriptions, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
 {
   mBiologicalDescriptions.cleanup();
   CRDFPredicate::ePredicateType Predicates[] =
   {
     CRDFPredicate::copasi_encodes,
     CRDFPredicate::copasi_hasPart,
     CRDFPredicate::copasi_hasVersion,
     CRDFPredicate::copasi_is,
     CRDFPredicate::copasi_isEncodedBy,
     CRDFPredicate::copasi_isHomologTo,
     CRDFPredicate::copasi_isPartOf,
     CRDFPredicate::copasi_isVersionOf,
     CRDFPredicate::copasi_occursIn,
     CRDFPredicate::bqbiol_encodes,
     CRDFPredicate::bqbiol_hasPart,
     CRDFPredicate::bqbiol_hasVersion,
     CRDFPredicate::bqbiol_is,
     CRDFPredicate::bqbiol_isEncodedBy,
     CRDFPredicate::bqbiol_isHomologTo,
     CRDFPredicate::bqbiol_isPartOf,
     CRDFPredicate::bqbiol_isVersionOf,
     CRDFPredicate::bqbiol_occursIn,
     CRDFPredicate::bqmodel_is,
     CRDFPredicate::end
   };
   CRDFPredicate::Path Path = mTriplet.pObject->getPath();
   std::set< CRDFTriplet > Triples;
   CRDFPredicate::ePredicateType * pPredicate = Predicates;
   std::set< CRDFTriplet >::iterator it;
   std::set< CRDFTriplet >::iterator end;
   for (; *pPredicate != CRDFPredicate::end; ++pPredicate)
     {
       Triples = mTriplet.pObject->getDescendantsWithPredicate(*pPredicate);
       it = Triples.begin();
       end = Triples.end();
       for (; it != end; ++it)
         mBiologicalDescriptions.add(new CBiologicalDescription(*it), true);
     }
 }
void CMIRIAMInfo::loadCreators ()
Definition at line 102 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CCopasiVector< T >::cleanup(), CRDFPredicate::dc_creator, CRDFPredicate::dcterms_creator, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), mCreators, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
 {
   mCreators.cleanup();
   CRDFPredicate::ePredicateType Predicates[] =
   {
     CRDFPredicate::dcterms_creator,
     CRDFPredicate::dc_creator,
     CRDFPredicate::end
   };
   CRDFPredicate::Path Path = mTriplet.pObject->getPath();
   std::set< CRDFTriplet > Triples;
   CRDFPredicate::ePredicateType * pPredicate = Predicates;
   std::set< CRDFTriplet >::iterator it;
   std::set< CRDFTriplet >::iterator end;
   for (; *pPredicate != CRDFPredicate::end; ++pPredicate)
     {
       Triples =
         mTriplet.pObject->getDescendantsWithPredicate(*pPredicate);
       it = Triples.begin();
       end = Triples.end();
       for (; it != end; ++it)
         mCreators.add(new CCreator(*it), true);
     }
   return;
 }
void CMIRIAMInfo::loadModifications ()
Definition at line 294 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CCopasiVector< T >::cleanup(), CRDFPredicate::dcterms_modified, CRDFNode::getDescendantsWithPredicate(), mModifications, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
 {
   mModifications.cleanup();
   std::set< CRDFTriplet > Triples =
     mTriplet.pObject->getDescendantsWithPredicate(CRDFPredicate::dcterms_modified);
   std::set< CRDFTriplet >::iterator it = Triples.begin();
   std::set< CRDFTriplet >::iterator end = Triples.end();
   for (; it != end; ++it)
     mModifications.add(new CModification(*it), true);
   return;
 }
void CMIRIAMInfo::loadReferences ()
Definition at line 180 of file CModelMIRIAMInfo.cpp.
References CCopasiVector< T >::add(), CRDFPredicate::bqbiol_isDescribedBy, CRDFPredicate::bqmodel_isDescribedBy, CCopasiVector< T >::cleanup(), CRDFPredicate::dcterms_bibliographicCitation, CRDFPredicate::end, CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), mReferences, mTriplet, and CRDFTriplet::pObject.
Referenced by load().
 {
   mReferences.cleanup();
   CRDFPredicate::ePredicateType Predicates[] =
   {
     CRDFPredicate::dcterms_bibliographicCitation,
     CRDFPredicate::bqbiol_isDescribedBy,
     CRDFPredicate::bqmodel_isDescribedBy,
     CRDFPredicate::end
   };
   CRDFPredicate::Path Path = mTriplet.pObject->getPath();
   std::set< CRDFTriplet > Triples;
   CRDFPredicate::ePredicateType * pPredicate = Predicates;
   std::set< CRDFTriplet >::iterator it;
   std::set< CRDFTriplet >::iterator end;
   for (; *pPredicate != CRDFPredicate::end; ++pPredicate)
     {
       Triples = mTriplet.pObject->getDescendantsWithPredicate(*pPredicate);
       it = Triples.begin();
       end = Triples.end();
       for (; it != end; ++it)
         mReferences.add(new CReference(*it), true);
     }
   return;
 }
bool CMIRIAMInfo::removeBiologicalDescription (int position)
Definition at line 336 of file CModelMIRIAMInfo.cpp.
References CBiologicalDescription::getTriplet(), mBiologicalDescriptions, mpRDFGraph, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CCopasiVector< T >::remove(), and CRDFGraph::removeTriplet().
Referenced by CQBiologicalDescriptionDM::removeRows().
 {
   CBiologicalDescription * pBiologicalDescription =
     mBiologicalDescriptions[position];
   if (!pBiologicalDescription)
     return false;
   const CRDFTriplet & Triplet = pBiologicalDescription->getTriplet();
   mpRDFGraph->removeTriplet(Triplet.pSubject,
                             Triplet.Predicate,//CRDFPredicate::getURI(Triplet.Predicate),
                             Triplet.pObject);
   return mBiologicalDescriptions.remove(pBiologicalDescription);
 }
bool CMIRIAMInfo::removeCreator (int position)
Definition at line 86 of file CModelMIRIAMInfo.cpp.
References CCreator::getTriplet(), CRDFPredicate::getURI(), mCreators, mpRDFGraph, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CCopasiVector< T >::remove(), and CRDFGraph::removeTriplet().
Referenced by CQCreatorDM::removeRows().
 {
   CCreator * pCreator = mCreators[position];
   if (!pCreator)
     return false;
   const CRDFTriplet & Triplet = pCreator->getTriplet();
   mpRDFGraph->removeTriplet(Triplet.pSubject,
                             CRDFPredicate::getURI(Triplet.Predicate),
                             Triplet.pObject);
   return mCreators.remove(pCreator);
 }
bool CMIRIAMInfo::removeModification (int position)
Definition at line 278 of file CModelMIRIAMInfo.cpp.
References CModification::getTriplet(), CRDFPredicate::getURI(), mModifications, mpRDFGraph, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CCopasiVector< T >::remove(), and CRDFGraph::removeTriplet().
Referenced by CQModifiedDM::removeRows().
 {
   CModification * pModified = mModifications[position];
   if (!pModified)
     return false;
   const CRDFTriplet & Triplet = pModified->getTriplet();
   mpRDFGraph->removeTriplet(Triplet.pSubject,
                             CRDFPredicate::getURI(Triplet.Predicate),
                             Triplet.pObject);
   return mModifications.remove(pModified);
 }
bool CMIRIAMInfo::removeReference (int position)
Definition at line 164 of file CModelMIRIAMInfo.cpp.
References CReference::getTriplet(), CRDFPredicate::getURI(), mpRDFGraph, mReferences, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, CCopasiVector< T >::remove(), and CRDFGraph::removeTriplet().
Referenced by CQReferenceDM::removeRows().
 {
   CReference * pReference = mReferences[position];
   if (!pReference)
     return false;
   const CRDFTriplet & Triplet = pReference->getTriplet();
   mpRDFGraph->removeTriplet(Triplet.pSubject,
                             CRDFPredicate::getURI(Triplet.Predicate),
                             Triplet.pObject);
   return mReferences.remove(pReference);
 }
bool CMIRIAMInfo::save ()
Definition at line 449 of file CModelMIRIAMInfo.cpp.
References CAnnotation::castObject(), CRDFGraph::clean(), CKeyFactory::get(), CAnnotation::getKey(), CCopasiRootContainer::getKeyFactory(), mKey, mpRDFGraph, CAnnotation::setMiriamAnnotation(), CRDFGraph::updateNamespaces(), and CRDFWriter::xmlFromGraph().
Referenced by CQMiriamWidget::leave().
 {
   CCopasiObject * pCopasiObject = dynamic_cast< CCopasiObject * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (pCopasiObject && mpRDFGraph)
     {
       mpRDFGraph->clean();
       mpRDFGraph->updateNamespaces();
       std::string XML = CRDFWriter::xmlFromGraph(mpRDFGraph);
       CAnnotation * pAnnotation = CAnnotation::castObject(pCopasiObject);
       if (pAnnotation == NULL)
         {
           return false;
         }
       pAnnotation->setMiriamAnnotation(XML, pAnnotation->getKey(), pAnnotation->getKey());
       return true;
     }
   return false;
 }
void CMIRIAMInfo::setCreatedDT (const std::string & dt)
Definition at line 220 of file CModelMIRIAMInfo.cpp.
References CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFPredicate::dcterms_created, CRDFPredicate::dcterms_W3CDTF, CRDFGraph::generatedNodeId(), CRDFNode::getPath(), CRDFNode::getSubject(), CRDFPredicate::getURI(), mCreated, mpRDFGraph, mTriplet, CRDFTriplet::pObject, CRDFObject::setBlankNodeId(), CRDFNode::setFieldValue(), and CRDFObject::setType().
Referenced by CQMiriamWidget::slotCreatedDTChanged().
 {
   std::string Date = dt;
   if (Date == "0000-00-00T00:00:00")
     Date = ""; // This causes deletion of the edge
   if (!mCreated)
     {
       const CRDFSubject & Subject = mTriplet.pObject->getSubject();
       CRDFObject Object;
       Object.setType(CRDFObject::BLANK_NODE);
       std::string Id = mpRDFGraph->generatedNodeId();
       Object.setBlankNodeId(Id);
       mCreated = mpRDFGraph->addTriplet(Subject,
                                         CRDFPredicate::getURI(CRDFPredicate::dcterms_created),
                                         Object);
       // Debugging
       assert(!mCreated == false);
     }
   mCreated.pObject->setFieldValue(Date, CRDFPredicate::dcterms_W3CDTF, mCreated.pObject->getPath());
 }
Member Data Documentation
CCopasiVector<CBiologicalDescription> CMIRIAMInfo::mBiologicalDescriptions private
Definition at line 46 of file CModelMIRIAMInfo.h.
Referenced by createBiologicalDescription(), getBiologicalDescriptions(), loadBiologicalDescriptions(), and removeBiologicalDescription().
CRDFTriplet CMIRIAMInfo::mCreated private
Definition at line 50 of file CModelMIRIAMInfo.h.
Referenced by getCreatedDT(), load(), and setCreatedDT().
CRDFObject CMIRIAMInfo::mCreatedObj private
Definition at line 47 of file CModelMIRIAMInfo.h.
CCopasiVector<CCreator> CMIRIAMInfo::mCreators private
Definition at line 43 of file CModelMIRIAMInfo.h.
Referenced by createCreator(), getCreators(), loadCreators(), and removeCreator().
std::string CMIRIAMInfo::mKey private
Definition at line 42 of file CModelMIRIAMInfo.h.
Referenced by getKey(), load(), and save().
CCopasiVector<CModification> CMIRIAMInfo::mModifications private
Definition at line 45 of file CModelMIRIAMInfo.h.
Referenced by createModification(), getModifications(), loadModifications(), and removeModification().
CRDFGraph* CMIRIAMInfo::mpRDFGraph private
Definition at line 48 of file CModelMIRIAMInfo.h.
Referenced by createBiologicalDescription(), createCreator(), createModification(), createReference(), getRDFGraph(), load(), removeBiologicalDescription(), removeCreator(), removeModification(), removeReference(), save(), setCreatedDT(), and ~CMIRIAMInfo().
CCopasiVector<CReference> CMIRIAMInfo::mReferences private
Definition at line 44 of file CModelMIRIAMInfo.h.
Referenced by createReference(), getReferences(), loadReferences(), and removeReference().
CRDFTriplet CMIRIAMInfo::mTriplet private
Definition at line 49 of file CModelMIRIAMInfo.h.
Referenced by load(), loadBiologicalDescriptions(), loadCreators(), loadModifications(), loadReferences(), and setCreatedDT().
The documentation for this class was generated from the following files:
CModelMIRIAMInfo.h
CModelMIRIAMInfo.cpp