COPASI API: CCopasiXMLParser::ImageElement Class Reference
CCopasiXMLParser::ImageElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ImageElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ImageElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Image = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4076 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ImageElement::Element private
Enumerator
Image
Definition at line 4083 of file CCopasiXMLParser.h.
     {
       Image = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ImageElement::ImageElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 12499 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ImageElement::~ImageElement () virtual
Destructor
Definition at line 12504 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::ImageElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 12564 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Image:
         if (strcmp(pszName, "Image"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Image", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ImageElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 12509 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, CLImage::setCoordinates(), CLImage::setDimensions(), CLImage::setImageReference(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * X;
   const char * Y;
   const char * Z;
   const char * WIDTH;
   const char * HEIGHT;
   const char * HREF;
   CLImage* pImage = NULL;
   switch (mCurrentElement)
     {
       case Image:
         if (strcmp(pszName, "Image"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Image", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         X = mParser.getAttributeValue("x", papszAttrs);
         Y = mParser.getAttributeValue("y", papszAttrs);
         Z = mParser.getAttributeValue("z", papszAttrs, "0.0");
         WIDTH = mParser.getAttributeValue("width", papszAttrs);
         HEIGHT = mParser.getAttributeValue("height", papszAttrs);
         HREF = mParser.getAttributeValue("href", papszAttrs);
         pImage = new CLImage();
         if (Transform != NULL)
           {
             pImage->parseTransformation(Transform);
           }
         pImage->setCoordinates(CLRelAbsVector(X), CLRelAbsVector(Y), CLRelAbsVector(Z));
         pImage->setDimensions(CLRelAbsVector(WIDTH), CLRelAbsVector(HEIGHT));
         pImage->setImageReference(HREF);
         mCommon.pGroup->addChildElement(pImage);
         // delete the image again since the add method made a copy
         delete pImage;
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp