COPASI API: CCopasiContainer Class Reference
CCopasiContainer Class Reference
#include <CCopasiContainer.h>
Inherits CCopasiObject.
Inherited by CArrayAnnotation, CBiologicalDescription, CChemEq, CChemEqElement, CCopasiDataModel, CCopasiParameter, CCopasiRootContainer, CCopasiTask, CCopasiVector< T >, CCopasiVector< CBiologicalDescription >, CCopasiVector< CChemEqElement >, CCopasiVector< CCopasiDataModel >, CCopasiVector< CCopasiObject >, CCopasiVector< CCreator >, CCopasiVector< CEvent >, CCopasiVector< CEventAssignment >, CCopasiVector< CFittingPoint >, CCopasiVector< CLayout >, CCopasiVector< CLColorDefinition >, CCopasiVector< CLCompartmentGlyph >, CCopasiVector< CLGeneralGlyph >, CCopasiVector< CLGlobalRenderInformation >, CCopasiVector< CLGlobalStyle >, CCopasiVector< CLGradientBase >, CCopasiVector< CLGradientStop >, CCopasiVector< CLGraphicalObject >, CCopasiVector< CLLineEnding >, CCopasiVector< CLLocalRenderInformation >, CCopasiVector< CLLocalStyle >, CCopasiVector< CLMetabGlyph >, CCopasiVector< CLMetabReferenceGlyph >, CCopasiVector< CLReactionGlyph >, CCopasiVector< CLReferenceGlyph >, CCopasiVector< CLTextGlyph >, CCopasiVector< CMathEvent >, CCopasiVector< CMathEvent::CAssignment >, CCopasiVector< CMathTrigger::CRootFinder >, CCopasiVector< CMetab >, CCopasiVector< CMetabOld >, CCopasiVector< CModification >, CCopasiVector< CMoiety >, CCopasiVector< CPlotItem >, CCopasiVector< CReference >, CCopasiVector< CSlider >, CCopasiVector< CType >, CCreator, CEigen, CEvaluationTree, CEvent, CEventAssignment, CFittingPoint, CFunctionDB, CFunctionParameter, CFunctionParameters, CLayout, CLGradientBase, CLGraphicalObject, CLGroup, CLLineEnding, CLRenderInformationBase, CLStyle, CMathContainer, CMathEvent, CMathEvent::CAssignment, CMathModel, CMathTrigger, CMathTrigger::CRootFinder, CMetabOld, CMIRIAMInfo, CModelEntity, CModelParameterSet, CModification, CMoiety, CReaction, CReference, CSlider, and SCopasiXMLGUI.
Public Types
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const std::vector
< CCopasiContainer * > EmptyList
Protected Member Functions
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
objectMap mObjects
Private Member Functions
CCopasiContainer ()
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Class CCopasiContainer
This class is the is used to group CCopasiObjects logically. It inself is an object. Contained objects are still globally accessible.
Copyright Stefan Hoops 2002
Definition at line 37 of file CCopasiContainer.h.
Member Typedef Documentation
typedef std::multimap<std::string, CCopasiObject * > CCopasiContainer::objectMap
Definition at line 44 of file CCopasiContainer.h.
Constructor & Destructor Documentation
CCopasiContainer::CCopasiContainer () private
Definition at line 41 of file CCopasiContainer.cpp.
References addObjectReference(), and CCopasiObject::getObjectName().
                                    :
     CCopasiObject(),
     mObjects()
 {addObjectReference("Name", *const_cast<std::string *>(&getObjectName()));}
CCopasiContainer::CCopasiContainer (const std::string & name, const CCopasiContainer * pParent = NULL, const std::string & type = "CN", const unsigned C_INT32 & flag = CCopasiObject::Container)
Definition at line 46 of file CCopasiContainer.cpp.
References addObjectReference(), and CCopasiObject::getObjectName().
                                                                  :
     CCopasiObject(name, pParent, type, flag | CCopasiObject::Container),
     mObjects()
 {addObjectReference("Name", *const_cast<std::string *>(&getObjectName()));}
CCopasiContainer::CCopasiContainer (const CCopasiContainer & src, const CCopasiContainer * pParent = NULL)
Definition at line 54 of file CCopasiContainer.cpp.
References addObjectReference(), and CCopasiObject::getObjectName().
                                                                     :
     CCopasiObject(src, pParent),
     mObjects()
 {addObjectReference("Name", *const_cast<std::string *>(&getObjectName()));}
CCopasiContainer::~CCopasiContainer () virtual
Definition at line 60 of file CCopasiContainer.cpp.
References mObjects, and pdelete.
 {
   objectMap::iterator it = mObjects.begin();
   objectMap::iterator end = mObjects.end();
   for (; it != end; it++)
     if (it->second != NULL &&
         it->second->getObjectParent() == this)
       {
         it->second->setObjectParent(NULL);
         pdelete(it->second);
       }
 }
Member Function Documentation
bool CCopasiContainer::add (CCopasiObject * pObject, const bool & adopt = true) virtual
Definition at line 212 of file CCopasiContainer.cpp.
References CCopasiObject::getObjectName(), mObjects, and CCopasiObject::setObjectParent().
Referenced by CCopasiVector< CLGeneralGlyph >::add(), CCopasiVectorN< CReportDefinition >::add(), CCopasiParameterGroup::addParameter(), CCopasiObject::CCopasiObject(), CCrossSectionTask::CCrossSectionTask(), CEFMTask::CEFMTask(), CFitTask::CFitTask(), CLNATask::CLNATask(), CLyapTask::CLyapTask(), CMCATask::CMCATask(), CMoietiesTask::CMoietiesTask(), CModelEntity::compile(), COptTask::COptTask(), COscillationTask::COscillationTask(), CScanTask::CScanTask(), CSensTask::CSensTask(), CSteadyStateTask::CSteadyStateTask(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), CCopasiDataModel::importSBML(), CCopasiDataModel::importSBMLFromString(), CTrajectoryTask::load(), CCopasiDataModel::loadModel(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CModelEntity::setInitialExpressionPtr(), CFitTask::setMethodType(), CMoietiesTask::setMethodType(), COscillationTask::setMethodType(), COptTask::setMethodType(), CEFMTask::setMethodType(), CTSSATask::setMethodType(), CLyapTask::setMethodType(), CTrajectoryTask::setMethodType(), CCrossSectionTask::setMethodType(), CEvent::setPriorityExpressionPtr(), CModelEntity::setStatus(), and CEvent::setTriggerExpressionPtr().
 {
   /* We check whether we are already containing that object. */
   std::pair< objectMap::iterator, objectMap::iterator > range =
     mObjects.equal_range(pObject->getObjectName());
   objectMap::iterator it;
   for (it = range.first; it != range.second; ++it)
     if (it->second == pObject) break;
   if (it != range.second) return false;
   /* This object is not contained, so we can add it. */
   mObjects.insert
   (std::pair<const std::string, CCopasiObject * >(pObject->getObjectName(),
       pObject));
   if (adopt) pObject->setObjectParent(this);
   return true;
 }
template<class CType > CCopasiObject* CCopasiContainer::addMatrixReference (const std::string & name, CType & reference, const unsigned C_INT32 & flag = 0) inline protected
Definition at line 99 of file CCopasiContainer.h.
References createMatrixReference().
Referenced by CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), and CModel::initObjects().
   {return createMatrixReference(name, this, reference, flag);}
template<class CType > CCopasiObject* CCopasiContainer::addObjectReference (const std::string & name, CType & reference, const unsigned C_INT32 & flag = 0) inline protected
Definition at line 89 of file CCopasiContainer.h.
References createReference().
Referenced by CCopasiContainer(), CCopasiParameter::createValue(), CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), CFittingPoint::initObjects(), CRandomSearch::initObjects(), COptMethodDE::initObjects(), COptMethodEP::initObjects(), COptMethodSRES::initObjects(), COptMethodGA::initObjects(), COptMethodPS::initObjects(), COptMethodGASR::initObjects(), COptMethodHookeJeeves::initObjects(), COptMethodCoranaWalk::initObjects(), COptMethodLevenbergMarquardt::initObjects(), COptMethodNelderMead::initObjects(), COptMethodSA::initObjects(), COptMethodTruncatedNewton::initObjects(), COptMethodPraxis::initObjects(), CFunctionDB::initObjects(), COptMethodSteepestDescent::initObjects(), CEFMAlgorithm::initObjects(), COptMethodSS::initObjects(), CChemEqElement::initObjects(), CBitPatternMethod::initObjects(), CBitPatternTreeMethod::initObjects(), CLyapTask::initObjects(), CCrossSectionTask::initObjects(), CEvaluationTree::initObjects(), CFitProblem::initObjects(), CMoiety::initObjects(), CEigen::initObjects(), CModelEntity::initObjects(), COptProblem::initObjects(), CCopasiTask::initObjects(), CMetab::initObjects(), CReaction::initObjects(), and CModel::initObjects().
   {return createReference(name, this, reference, flag);}
template<class CType > CCopasiObject* CCopasiContainer::addVectorReference (const std::string & name, CType & reference, const unsigned C_INT32 & flag = 0) inline protected
Definition at line 94 of file CCopasiContainer.h.
References createVectorReference().
Referenced by CLyapTask::initObjects(), CEigen::initObjects(), and COptProblem::initObjects().
   {return createVectorReference(name, this, reference, flag);}
std::string CCopasiContainer::getChildObjectUnits (const CCopasiObject * pObject) const virtual
Retrieve the units of the child object.
Returns
std::string units
Reimplemented in CMetab, CModel, CReaction, and CCompartment.
Definition at line 260 of file CCopasiContainer.cpp.
Referenced by CCopasiObject::getUnits().
 {return "";}
const CObjectInterface * CCopasiContainer::getObject (const CCopasiObjectName & cn) const virtual
Retrieve a descendant object by its CN.
Parameters
const CCopasiObjectName & cn
Returns
const CObjectInterface * pObject
Reimplemented from CCopasiObject.
Reimplemented in CCopasiVectorN< CType >, CCopasiVectorN< CReaction >, CCopasiVectorN< CEventAssignment >, CCopasiVectorN< CFunctionParameter >, CCopasiVectorN< CCopasiTask >, CCopasiVectorN< CPlotSpecification >, CCopasiVectorN< CCompartment >, CCopasiVectorN< CModelParameterSet >, CCopasiVectorN< CEvent >, CCopasiVectorN< CMetab >, CCopasiVectorN< CFunction >, CCopasiVectorN< CModelValue >, CCopasiVectorN< CReportDefinition >, CCopasiVector< T >, CCopasiVector< CLGlobalRenderInformation >, CCopasiVector< CModification >, CCopasiVector< CLMetabGlyph >, CCopasiVector< CLCompartmentGlyph >, CCopasiVector< CLReferenceGlyph >, CCopasiVector< CSlider >, CCopasiVector< CBiologicalDescription >, CCopasiVector< CLGlobalStyle >, CCopasiVector< CEventAssignment >, CCopasiVector< CReference >, CCopasiVector< CMathEvent::CAssignment >, CCopasiVector< CLayout >, CCopasiVector< CLGradientStop >, CCopasiVector< CLMetabReferenceGlyph >, CCopasiVector< CMoiety >, CCopasiVector< CType >, CCopasiVector< CChemEqElement >, CCopasiVector< CLColorDefinition >, CCopasiVector< CLReactionGlyph >, CCopasiVector< CEvent >, CCopasiVector< CMathEvent >, CCopasiVector< CLGradientBase >, CCopasiVector< CLLocalRenderInformation >, CCopasiVector< CMetab >, CCopasiVector< CPlotItem >, CCopasiVector< CCopasiDataModel >, CCopasiVector< CLLineEnding >, CCopasiVector< CFittingPoint >, CCopasiVector< CLTextGlyph >, CCopasiVector< CCopasiObject >, CCopasiVector< CMathTrigger::CRootFinder >, CCopasiVector< CLLocalStyle >, CCopasiVector< CCreator >, CCopasiVector< CLGraphicalObject >, CCopasiVector< CMetabOld >, CCopasiVector< CLGeneralGlyph >, CReaction, CArrayAnnotation, CMathContainer, and CCopasiParameterGroup.
Definition at line 74 of file CCopasiContainer.cpp.
References C_INT32, CCopasiObjectName::getElementName(), CObjectInterface::getObject(), CCopasiObject::getObject(), CCopasiObjectName::getObjectName(), CCopasiObject::getObjectName(), CCopasiObjectName::getObjectType(), CCopasiObject::getObjectType(), CCopasiObjectName::getRemainder(), CCopasiObject::isRoot(), and mObjects.
Referenced by addInitialAssignmentsToModel(), DataModelGUI::buildChangedObjects(), CModel::buildInitialSequence(), CMathContainer::CMathContainer(), CEvaluationNodeCall::compile(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), SBMLImporter::createCModelFromSBMLDocument(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CExpression::createInitialExpression(), CSEDMLExporter::createScanTask(), findObjectByDisplayName(), CCopasiDataModel::getDataObject(), CEvaluationTree::getDeletedObjects(), CObjectLists::getListOfConstObjects(), CMathContainer::getMathObject(), CCopasiParameterGroup::getObject(), CArrayAnnotation::getObject(), CReaction::getObject(), CFittingPoint::getObjectDisplayName(), SEDMLUtils::getObjectForSbmlId(), CCopasiXMLParser::getObjectFromName(), CExpression::initObjects(), CQMoietiesTaskResult::load(), CQMathMatrixWidget::loadMatrices(), CQCrossSectionTaskWidget::loadTask(), main(), CModelMerging::mergeInExpression(), CCopasiDataModel::ObjectFromCN(), CQSimpleSelectionTree::populateTree(), CMoietiesProblem::printResult(), CSBMLExporter::replaceSpeciesReferences(), SBMLImporter::replaceTimeAndAvogadroNodeNames(), SEDMLUtils::resolveDatagenerator(), CCopasiObject::setObjectName(), and CModelExpansion::updateExpression().
 {
   if (cn == "")
     {
       if (isRoot())
         return NULL;
       else
         return this;
     }
   if (cn == "Property=DisplayName")
     {
       return CCopasiObject::getObject(cn);
     }
   std::string Name = cn.getObjectName();
   std::string Type = cn.getObjectType();
   if (getObjectName() == Name && getObjectType() == Type)
     return getObject(cn.getRemainder());
   //check if the first part of the cn matches one of the children (by name and type)
   std::pair< objectMap::const_iterator, objectMap::const_iterator > range =
     mObjects.equal_range(Name);
   objectMap::const_iterator it = range.first;
   while (it != range.second && it->second->getObjectType() != Type) ++it;
   if (it == range.second) //not found in the list of children
     {
       if (Type == "String")
         return new CCopasiStaticString(Name, this);
       else if (Type == "Separator")
         return new CCopasiReportSeparator(Name, this);
       else
         return NULL;
     }
   const CObjectInterface * pObject = NULL;
   if (it->second->isNameVector() || it->second->isVector())
     {
       if (cn.getElementName(0, false) == "")
         return it->second;
       pObject = it->second->getObject("[" + cn.getElementName(0, false) + "]");
       if (it->second->getObjectType() == "Reference" ||
           !pObject ||
           cn.getRemainder() == "")
         return pObject;
       else
         return pObject->getObject(cn.getRemainder());
     }
   //handle objects where the array flag is set. Currently this applies to the
   //CArrayAnnotation object. Since this is also a container, we have to do this
   //before handling general containers.
   if (it->second->isArray())
     {
       //we need to call the getObject() method of the child array with the
       //remainder of the cn, with the indices in square brackets, or with an empty string
       //if there are no indices there could still be a remainder (since the array can also be
       //a container)
       if (cn.getElementName(0, false) == "") //no indices
         return it->second->getObject(cn.getRemainder());
       //get the indices from the CN
       std::string indices;
       std::string tmp;
       C_INT32 ii = 0;
       while ((tmp = cn.getElementName(ii, false)) != "")
         {
           indices += "[" + tmp + "]";
           ++ii;
         }
       //try to get the array element from the indices
       pObject = it->second->getObject(indices);
       //if the element could not be resolved, just return NULL. If there is no
       //remainder, just return the array element.
       //In all other cases we call getObject() on the array element with the remainder
       //of the CN. The special treatment of the empty remainder is probably necessary
       //since not all implementations of getObject(cn) handle the case of empty CN.
       if (!pObject)
         return NULL;
       if (cn.getRemainder() == "")
         return pObject;
       else
         return pObject->getObject(cn.getRemainder());
     }
   //handle generic containers.
   if (it->second->isContainer())
     return it->second->getObject(cn.getRemainder());
   if (it->second->isMatrix())
     {
       if (cn.getElementName(0, false) == "")
         return it->second;
       pObject = it->second->getObject("[" + cn.getElementName(0, false) + "]" +                   //TODO really?
                                       "[" + cn.getElementName(1, false) + "]");
       if (it->second->getObjectType() == "Reference" || !pObject)
         return pObject;
       else
         return pObject->getObject(cn.getRemainder());
     }
   return it->second->getObject(cn.getRemainder());
 }
const CCopasiContainer::objectMap & CCopasiContainer::getObjects () const virtual
Definition at line 192 of file CCopasiContainer.cpp.
References mObjects.
Referenced by CCopasiParameterGroup::beginName(), CCopasiParameterGroup::endName(), CQUpdatesWidget::fillRefreshsMapRecursively(), CODEExporter::findObjectFromRefresh(), ObjectBrowserWidget::getFieldCopasiObject(), CCopasiParameterGroup::getParameter(), ObjectBrowserWidget::loadChild(), CQCompartment::loadMetaboliteTable(), CQSimpleSelectionTree::populateTree(), CQCompartment::slotMetaboliteTableCurrentChanged(), and CDotOutput::writeDotRecursively().
 {return mObjects;}
std::string CCopasiContainer::getUnits () const virtual
Retrieve the units of the object.
Returns
std::string units
Reimplemented from CCopasiObject.
Definition at line 256 of file CCopasiContainer.cpp.
Referenced by SBMLImporter::createCCompartmentFromCompartment().
 {return "";}
const CCopasiObject * CCopasiContainer::getValueObject () const virtual
Reimplemented from CCopasiObject.
Reimplemented in CMetab, and CModelEntity.
Definition at line 195 of file CCopasiContainer.cpp.
References CCopasiObject::getValuePointer(), and mObjects.
Referenced by CExperiment::compile().
 {
   void * ptr = getValuePointer();
   if (ptr == NULL) return NULL;
   objectMap::const_iterator it = mObjects.begin();
   objectMap::const_iterator end = mObjects.end();
   for (; it != end; ++it)
     if (ptr == it->second->getValuePointer()) return it->second;
   return NULL;
 }
void CCopasiContainer::initObjects () protected
Definition at line 210 of file CCopasiContainer.cpp.
Referenced by COptMethodStatistics::COptMethodStatistics().
 {}
bool CCopasiContainer::remove (CCopasiObject * pObject) virtual
Reimplemented in CCopasiVector< T >, CCopasiVector< CLGlobalRenderInformation >, CCopasiVector< CModification >, CCopasiVector< CLMetabGlyph >, CCopasiVector< CLCompartmentGlyph >, CCopasiVector< CLReferenceGlyph >, CCopasiVector< CSlider >, CCopasiVector< CBiologicalDescription >, CCopasiVector< CLGlobalStyle >, CCopasiVector< CEventAssignment >, CCopasiVector< CReference >, CCopasiVector< CMathEvent::CAssignment >, CCopasiVector< CLayout >, CCopasiVector< CLGradientStop >, CCopasiVector< CLMetabReferenceGlyph >, CCopasiVector< CMoiety >, CCopasiVector< CType >, CCopasiVector< CChemEqElement >, CCopasiVector< CLColorDefinition >, CCopasiVector< CLReactionGlyph >, CCopasiVector< CEvent >, CCopasiVector< CMathEvent >, CCopasiVector< CLGradientBase >, CCopasiVector< CLLocalRenderInformation >, CCopasiVector< CMetab >, CCopasiVector< CPlotItem >, CCopasiVector< CCopasiDataModel >, CCopasiVector< CLLineEnding >, CCopasiVector< CFittingPoint >, CCopasiVector< CLTextGlyph >, CCopasiVector< CCopasiObject >, CCopasiVector< CMathTrigger::CRootFinder >, CCopasiVector< CLLocalStyle >, CCopasiVector< CCreator >, CCopasiVector< CLGraphicalObject >, CCopasiVector< CMetabOld >, and CCopasiVector< CLGeneralGlyph >.
Definition at line 235 of file CCopasiContainer.cpp.
References mObjects.
Referenced by CCopasiVector< CLGeneralGlyph >::cleanup(), CCopasiVector< CLGeneralGlyph >::clear(), CCopasiXMLParser::TaskElement::end(), CCopasiVector< CLGeneralGlyph >::remove(), CCopasiVector< CLGeneralGlyph >::resize(), CCopasiObject::setObjectParent(), and CCopasiObject::~CCopasiObject().
 {
   objectMap::iterator it = mObjects.begin();
   objectMap::iterator end = mObjects.end();
   /*
     std::pair< objectMap::iterator, objectMap::iterator > range =
       mObjects.equal_range(pObject->getObjectName());
     objectMap::iterator it;
   */
   for (; it != end; ++it)
     if (it->second == pObject) break;
   if (it == end) return false;
   mObjects.erase(it);
   return true;
 }
Member Data Documentation
const std::vector< CCopasiContainer * > CCopasiContainer::EmptyList static
Class CCopasiContainer
This class is the is used to group CCopasiObjects logically. It inself is an object. Contained objects are still globally accessible.
Copyright Stefan Hoops 2002
Definition at line 42 of file CCopasiContainer.h.
Referenced by COptItem::setLowerBound(), and COptItem::setUpperBound().
objectMap CCopasiContainer::mObjects protected
Definition at line 47 of file CCopasiContainer.h.
Referenced by add(), CArrayAnnotation::appendElementReferences(), getObject(), CArrayAnnotation::getObject(), getObjects(), getValueObject(), remove(), and ~CCopasiContainer().
The documentation for this class was generated from the following files:
CCopasiContainer.h
CCopasiContainer.cpp