COPASI API: CQFittingResultTab1 Class Reference
CQFittingResultTab1 Class Reference
#include <CQFittingResultTab1.h>
Public Member Functions
CQFittingResultTab1 (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
void load (const CFitProblem *pProblem)
~CQFittingResultTab1 ()
Private Member Functions
void init ()
Detailed Description
Definition at line 23 of file CQFittingResultTab1.h.
Constructor & Destructor Documentation
CQFittingResultTab1::CQFittingResultTab1 (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 29 of file CQFittingResultTab1.cpp.
References init().
   : QWidget(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   setupUi(this);
   init();
 }
CQFittingResultTab1::~CQFittingResultTab1 ()
Definition at line 41 of file CQFittingResultTab1.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQFittingResultTab1::init () private
Definition at line 85 of file CQFittingResultTab1.cpp.
Referenced by CQFittingResultTab1().
 {}
void CQFittingResultTab1::load (const CFitProblem * pProblem)
Definition at line 46 of file CQFittingResultTab1.cpp.
References C_FLOAT64, C_INT32, CFitProblem::getCrossValidationRMS(), CFitProblem::getCrossValidationSD(), CFitProblem::getCrossValidationSet(), CFitProblem::getCrossValidationSolutionValue(), COptProblem::getExecutionTime(), CExperimentSet::getExperimentCount(), COptProblem::getFunctionEvaluations(), CFitProblem::getRMS(), COptProblem::getSolutionValue(), and CFitProblem::getStdDeviation().
 {
   mpEditObjectiveValue->setText(QString::number(pProblem->getSolutionValue()));
   mpEditRMS->setText(QString::number(pProblem->getRMS()));
   mpEditStdDeviation->setText(QString::number(pProblem->getStdDeviation()));
   bool Enable = (pProblem->getCrossValidationSet().getExperimentCount() > 0);
   mpLblCVObjectiveValue->setEnabled(Enable);
   mpEditCVObjectiveValue->setEnabled(Enable);
   mpLblCVRMS->setEnabled(Enable);
   mpEditCVRMS->setEnabled(Enable);
   mpLblCVStdDeviation->setEnabled(Enable);
   mpEditCVStdDeviation->setEnabled(Enable);
   if (Enable)
     {
       mpEditCVObjectiveValue->setText(QString::number(pProblem->getCrossValidationSolutionValue()));
       mpEditCVRMS->setText(QString::number(pProblem->getCrossValidationRMS()));
       mpEditCVStdDeviation->setText(QString::number(pProblem->getCrossValidationSD()));
     }
   else
     {
       mpEditCVObjectiveValue->setText("");
       mpEditCVRMS->setText("");
       mpEditCVStdDeviation->setText("");
     }
   const unsigned C_INT32 & FunctionEvaluations = pProblem->getFunctionEvaluations();
   mpEditEvaluations->setText(QString::number(FunctionEvaluations));
   const C_FLOAT64 & ExecutionTime = pProblem->getExecutionTime();
   mpEditCPUTime->setText(QString::number(ExecutionTime));
   mpEditSpeed->setText(QString::number(FunctionEvaluations / ExecutionTime));
 }
The documentation for this class was generated from the following files:
CQFittingResultTab1.h
CQFittingResultTab1.cpp