COPASI API: CDataEntity Class Reference
CDataEntity Class Reference
#include <CDataEntity.h>
Public Member Functions
CDataEntity ()
CDataEntity (C_FLOAT64 t)
CDataEntity (const CDataEntity &src)
size_t getNumberOfElements ()
C_FLOAT64 getOrigValueForSpecies (std::string nodeKey)
C_FLOAT64 getTime ()
C_FLOAT64 getValueForSpecies (std::string nodeKey)
void putOrigValueForSpecies (std::string nodeKey, C_FLOAT64 value)
void putValueForSpecies (std::string nodeKey, C_FLOAT64 value)
Private Attributes
std::map< std::string, C_FLOAT64 > mOrigValueMap
std::map< std::string, C_FLOAT64 > mSpeciesValueMap
C_FLOAT64 mTime
Friends
std::ostream & operator<< (std::ostream &os, const CDataEntity &gn)
Detailed Description
Definition at line 31 of file CDataEntity.h.
Constructor & Destructor Documentation
CDataEntity::CDataEntity ()
Definition at line 27 of file CDataEntity.cpp.
References mTime.
 {
   mTime = 0.0;
 }
CDataEntity::CDataEntity (C_FLOAT64 t)
Definition at line 32 of file CDataEntity.cpp.
References mTime.
 {
   mTime = t;
 }
CDataEntity::CDataEntity (const CDataEntity & src)
Definition at line 37 of file CDataEntity.cpp.
                                                :
     mTime(src.mTime),
     mSpeciesValueMap(src.mSpeciesValueMap),
     mOrigValueMap(src.mOrigValueMap)
 {}
Member Function Documentation
size_t CDataEntity::getNumberOfElements () inline
Definition at line 48 of file CDataEntity.h.
References mSpeciesValueMap.
Referenced by CQLayoutMainWindow::insertValueTable().
 {return mSpeciesValueMap.size();}
C_FLOAT64 CDataEntity::getOrigValueForSpecies (std::string nodeKey)
Definition at line 70 of file CDataEntity.cpp.
References max, and mOrigValueMap.
Referenced by CQLayoutMainWindow::insertValueTable(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), CQGLNetworkPainter::rescaleNode(), CQGLNetworkPainter::showStep(), and CQLayoutMainWindow::updateValueTable().
 {
   std::map<std::string, C_FLOAT64>::iterator it;
   it = mOrigValueMap.find(nodeKey);
   if (it != mOrigValueMap.end())
     return (*it).second;
   else
     return - std::numeric_limits< C_FLOAT64 >::max();
 }
C_FLOAT64 CDataEntity::getTime () inline
Definition at line 49 of file CDataEntity.h.
References mTime.
 {return mTime;}
C_FLOAT64 CDataEntity::getValueForSpecies (std::string nodeKey)
Definition at line 58 of file CDataEntity.cpp.
References max, and mSpeciesValueMap.
Referenced by CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), and CQGLNetworkPainter::rescaleNode().
 {
   std::map<std::string, C_FLOAT64>::iterator it;
   it = mSpeciesValueMap.find(nodeKey);
   if (it != mSpeciesValueMap.end())
     return (*it).second;
   else
     return - std::numeric_limits< C_FLOAT64 >::max();
 }
void CDataEntity::putOrigValueForSpecies (std::string nodeKey, C_FLOAT64 value)
Definition at line 50 of file CDataEntity.cpp.
References mOrigValueMap.
Referenced by CQGLNetworkPainter::createDataSets().
 {
   mOrigValueMap.erase(nodeKey); // delete old value
   mOrigValueMap.insert(std::pair<std::string, C_FLOAT64>
                        (nodeKey, value));
 }
void CDataEntity::putValueForSpecies (std::string nodeKey, C_FLOAT64 value)
Definition at line 43 of file CDataEntity.cpp.
References mSpeciesValueMap.
Referenced by CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), CQGLNetworkPainter::rescaleNode(), CQGLNetworkPainter::setConstantNodeSize(), and CQGLNetworkPainter::setConstantNodeSizeForAllSteps().
 {
   mSpeciesValueMap.erase(nodeKey); // delete old value
   mSpeciesValueMap.insert(std::pair<std::string, C_FLOAT64>
                           (nodeKey, value));
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CDataEntity & gn) friend
Definition at line 81 of file CDataEntity.cpp.
 {
   os << "time: " << de.mTime << "  size: " << std::endl;
   std::map<std::string, C_FLOAT64>::const_iterator it1;
   std::map<std::string, C_FLOAT64>::const_iterator it2;
   for (it1 = de.mSpeciesValueMap.begin() ; it1 != de.mSpeciesValueMap.end() ; it1++)
     {
       it2 = de.mOrigValueMap.find((*it1).first);
       if (it2 != de.mOrigValueMap.end())
         os << (*it1).first << "  : " << (*it1).second << "  orig: " << (*it2).second << std::endl;
       else
         os << (*it1).first << "  : " << (*it1).second << "  orig: not found" << std::endl;
     }
   //for (int i=0;i<gn.mConnectedCurveIndices.size();i++)
   // os << gn.mConnectedCurveIndices[i] << std::endl;;
   return os;
 }
Member Data Documentation
std::map<std::string, C_FLOAT64> CDataEntity::mOrigValueMap private
Definition at line 36 of file CDataEntity.h.
Referenced by getOrigValueForSpecies(), operator<<(), and putOrigValueForSpecies().
std::map<std::string, C_FLOAT64> CDataEntity::mSpeciesValueMap private
Definition at line 35 of file CDataEntity.h.
Referenced by getNumberOfElements(), getValueForSpecies(), operator<<(), and putValueForSpecies().
C_FLOAT64 CDataEntity::mTime private
Definition at line 34 of file CDataEntity.h.
Referenced by CDataEntity(), getTime(), and operator<<().
The documentation for this class was generated from the following files:
CDataEntity.h
CDataEntity.cpp