COPASI API: CTrajectoryMethodDsaLsodar::CPartition Class Reference
CTrajectoryMethodDsaLsodar::CPartition Class Reference
Public Types
typedef std::multimap< size_t,
size_t > speciesToReactionsMap
Public Member Functions
CPartition ()
CPartition (const CPartition &src)
void determineStochasticSpecies ()
void intialize (std::vector< CReactionDependencies > &reactions, const speciesToReactionsMap &speciesToReactions, const C_FLOAT64 &lowerThreshold, const C_FLOAT64 &upperThreshold, const CState &state)
bool rePartition (const CState &state)
~CPartition ()
Public Attributes
CVector< CReactionDependencies * > mDeterministicReactions
bool mHasDeterministic
bool mHasStochastic
CVector< CReactionDependencies * > mStochasticReactions
CVector< bool > mStochasticSpecies
Private Attributes
size_t mFirstReactionSpeciesIndex
C_FLOAT64 mLowerThreshold
CVector< bool > mLowSpecies
CVector< size_t > mNumLowSpecies
size_t mNumReactionSpecies
speciesToReactionsMap mSpeciesToReactions
C_FLOAT64 mUpperThreshold
Detailed Description
Definition at line 139 of file CTrajectoryMethodDsaLsodar.h.
Member Typedef Documentation
typedef std::multimap< size_t, size_t > CTrajectoryMethodDsaLsodar::CPartition::speciesToReactionsMap
Definition at line 142 of file CTrajectoryMethodDsaLsodar.h.
Constructor & Destructor Documentation
CTrajectoryMethodDsaLsodar::CPartition::CPartition ()
Default constructor
Definition at line 87 of file CTrajectoryMethodDsaLsodar.cpp.
                                                 :
   mSpeciesToReactions(),
   mLowerThreshold(),
   mUpperThreshold(),
   mFirstReactionSpeciesIndex(C_INVALID_INDEX),
   mNumReactionSpecies(0),
   mStochasticReactions(0),
   mDeterministicReactions(0),
   mStochasticSpecies(0),
   mHasStochastic(false),
   mHasDeterministic(false),
   mNumLowSpecies(0),
   mLowSpecies(0)
 {}
CTrajectoryMethodDsaLsodar::CPartition::CPartition (const CPartition & src)
Copy constructor
Parameters
const CPartition & src
Definition at line 102 of file CTrajectoryMethodDsaLsodar.cpp.
                                                                                                 :
   mSpeciesToReactions(src.mSpeciesToReactions),
   mLowerThreshold(src.mLowerThreshold),
   mUpperThreshold(src.mUpperThreshold),
   mFirstReactionSpeciesIndex(C_INVALID_INDEX),
   mNumReactionSpecies(src.mNumReactionSpecies),
   mStochasticReactions(src.mStochasticReactions),
   mDeterministicReactions(src.mDeterministicReactions),
   mStochasticSpecies(src.mStochasticSpecies),
   mHasStochastic(src.mHasStochastic),
   mHasDeterministic(src.mHasDeterministic),
   mNumLowSpecies(src.mNumLowSpecies),
   mLowSpecies(src.mLowSpecies)
 {}
CTrajectoryMethodDsaLsodar::CPartition::~CPartition ()
Destructor
Definition at line 117 of file CTrajectoryMethodDsaLsodar.cpp.
 {}
Member Function Documentation
void CTrajectoryMethodDsaLsodar::CPartition::determineStochasticSpecies ()
Definition at line 295 of file CTrajectoryMethodDsaLsodar.cpp.
References CVectorCore< CType >::array(), CTrajectoryMethodDsaLsodar::mFirstReactionSpeciesIndex, and CTrajectoryMethodDsaLsodar::CReactionDependencies::mSpeciesIndex.
 {
   // All species which participate in stochastic reactions are treated stochastically
   CReactionDependencies **ppReaction = mStochasticReactions.array();
   CReactionDependencies **ppReactionEnd = ppReaction + mStochasticReactions.size();
   mStochasticSpecies = false;
   for (; ppReaction != ppReactionEnd; ++ppReaction)
     {
       if (*ppReaction != NULL)
         {
           size_t * pSpeciesIndex = (*ppReaction)->mSpeciesIndex.array();
           size_t * pSpeciesIndexEnd = pSpeciesIndex + (*ppReaction)->mSpeciesIndex.size();
           for (; pSpeciesIndex != pSpeciesIndexEnd; ++pSpeciesIndex)
             {
               mStochasticSpecies[*pSpeciesIndex - mFirstReactionSpeciesIndex] = true;
             }
         }
     }
 }
void CTrajectoryMethodDsaLsodar::CPartition::intialize (std::vector< CReactionDependencies > & reactions, const speciesToReactionsMap & speciesToReactions, const C_FLOAT64 & lowerThreshold, const C_FLOAT64 & upperThreshold, const CState & state)
Definition at line 120 of file CTrajectoryMethodDsaLsodar.cpp.
References CState::beginIndependent(), C_FLOAT64, and CTrajectoryMethodDsaLsodar::mFirstReactionSpeciesIndex.
Referenced by CTrajectoryMethodDsaLsodar::start().
 {
   mSpeciesToReactions = speciesToReactions;
   mLowerThreshold = lowerThreshold;
   mUpperThreshold = upperThreshold;
   mFirstReactionSpeciesIndex = mSpeciesToReactions.begin()->first;
   mNumReactionSpecies = mSpeciesToReactions.rbegin()->first - mFirstReactionSpeciesIndex + 1;
   mStochasticReactions.resize(reactions.size());
   mStochasticReactions = NULL;
   mDeterministicReactions.resize(reactions.size());
   mDeterministicReactions = NULL;
   mNumLowSpecies.resize(reactions.size());
   mNumLowSpecies = 0;
   mStochasticSpecies.resize(mNumReactionSpecies);
   mStochasticSpecies = false;
   mLowSpecies.resize(mNumReactionSpecies);
   mLowSpecies = false;
   mHasStochastic = false;
   mHasDeterministic = false;
   // Create the initial partition by first counting species with low particle number per reaction
   const C_FLOAT64 * pValue = state.beginIndependent() - 1 + mFirstReactionSpeciesIndex;
   const C_FLOAT64 * pValueEnd = pValue + mNumReactionSpecies;
   bool * pLowSpecies = mLowSpecies.array();
   C_FLOAT64 CriticalValue = (mLowerThreshold + mUpperThreshold) * 0.5;
   size_t Index = mFirstReactionSpeciesIndex;
   for (; pValue != pValueEnd; ++pValue, ++Index, ++pLowSpecies)
     {
       if (*pValue < CriticalValue)
         {
           *pLowSpecies = true;
           std::pair< speciesToReactionsMap::const_iterator, speciesToReactionsMap::const_iterator > Range
           = mSpeciesToReactions.equal_range(Index);
           for (; Range.first != Range.second; ++Range.first)
             {
               mNumLowSpecies[Range.first->second]++;
             }
         }
     }
   // Reactions for which the count of species with low numbers is non zero
   // are treated stochastically.
   const size_t * pLow = mNumLowSpecies.array();
   const size_t * pLowEnd = pLow + mNumLowSpecies.size();
   std::vector< CReactionDependencies >::iterator itReaction = reactions.begin();
   CReactionDependencies ** ppStochastic = mStochasticReactions.array();
   CReactionDependencies ** ppDeterministic = mDeterministicReactions.array();
   for (; pLow != pLowEnd; ++pLow, ++itReaction, ++ppStochastic, ++ppDeterministic)
     {
       if (*pLow != 0)
         {
           *ppStochastic = &(*itReaction);
           mHasStochastic = true;
         }
       else
         {
           *ppDeterministic = &(*itReaction);
           mHasDeterministic = true;
         }
     }
   determineStochasticSpecies();
 }
bool CTrajectoryMethodDsaLsodar::CPartition::rePartition (const CState & state)
Definition at line 200 of file CTrajectoryMethodDsaLsodar.cpp.
References CState::beginIndependent(), C_FLOAT64, and CTrajectoryMethodDsaLsodar::mFirstReactionSpeciesIndex.
Referenced by CTrajectoryMethodDsaLsodar::doSingleStep().
 {
   // Modify the partition if species values move beyond the threshold
   const C_FLOAT64 * pValue = state.beginIndependent() - 1 + mFirstReactionSpeciesIndex;
   const C_FLOAT64 * pValueEnd = pValue + mNumReactionSpecies;
   bool * pLowSpecies = mLowSpecies.array();
   bool PartitionChanged = false;
   size_t Index = 0;
   for (; pValue != pValueEnd; ++pValue, ++Index, ++pLowSpecies)
     {
       if (!*pLowSpecies && *pValue < mLowerThreshold)
         {
           *pLowSpecies = true;
           PartitionChanged = true;
           mStochasticSpecies[Index] = true;
           std::pair< speciesToReactionsMap::const_iterator, speciesToReactionsMap::const_iterator > Range
           = mSpeciesToReactions.equal_range(Index + mFirstReactionSpeciesIndex);
           for (; Range.first != Range.second; ++Range.first)
             {
               mNumLowSpecies[Range.first->second]++;
             }
         }
       else if (*pLowSpecies && *pValue > mUpperThreshold)
         {
           *pLowSpecies = false;
           PartitionChanged = true;
           mStochasticSpecies[Index] = true;
           std::pair< speciesToReactionsMap::const_iterator, speciesToReactionsMap::const_iterator > Range
           = mSpeciesToReactions.equal_range(Index);
           for (; Range.first != Range.second; ++Range.first)
             {
               mNumLowSpecies[Range.first->second]--;
             }
         }
     }
   if (!PartitionChanged)
     {
       return false;
     }
   PartitionChanged = false;
   // Reactions for which the count of species with low numbers is non zero
   // are treated stochastically.
   const size_t * pLow = mNumLowSpecies.array();
   const size_t * pLowEnd = pLow + mNumLowSpecies.size();
   CReactionDependencies ** ppStochastic = mStochasticReactions.array();
   CReactionDependencies ** ppDeterministic = mDeterministicReactions.array();
   mHasStochastic = false;
   mHasDeterministic = false;
   for (; pLow != pLowEnd; ++pLow, ++ppStochastic, ++ppDeterministic)
     {
       if (*pLow != 0)
         {
           mHasStochastic = true;
           if (*ppDeterministic != NULL)
             {
               PartitionChanged = true;
               *ppStochastic = *ppDeterministic;
               *ppDeterministic = NULL;
             }
         }
       else
         {
           mHasDeterministic = true;
           if (*ppStochastic != NULL)
             {
               PartitionChanged = true;
               *ppDeterministic = *ppStochastic;
               *ppStochastic = NULL;
             }
         }
     }
   if (PartitionChanged)
     {
       // determineStochasticSpecies();
     }
   return PartitionChanged;
 }
Member Data Documentation
CVector< CReactionDependencies * > CTrajectoryMethodDsaLsodar::CPartition::mDeterministicReactions
A vector containing pointers to stochastic reaction dependencies
Definition at line 207 of file CTrajectoryMethodDsaLsodar.h.
size_t CTrajectoryMethodDsaLsodar::CPartition::mFirstReactionSpeciesIndex private
The index of the first species determined by reactions in the state
Definition at line 191 of file CTrajectoryMethodDsaLsodar.h.
bool CTrajectoryMethodDsaLsodar::CPartition::mHasDeterministic
A Boolean flag indicating whether the system has deterministic reactions
Definition at line 222 of file CTrajectoryMethodDsaLsodar.h.
Referenced by CTrajectoryMethodDsaLsodar::doSingleStep().
bool CTrajectoryMethodDsaLsodar::CPartition::mHasStochastic
A Boolean flag indicating whether the system has stochastic reactions
Definition at line 217 of file CTrajectoryMethodDsaLsodar.h.
Referenced by CTrajectoryMethodDsaLsodar::doSingleStep().
C_FLOAT64 CTrajectoryMethodDsaLsodar::CPartition::mLowerThreshold private
The threshold for switching to stochastic treatment
Definition at line 181 of file CTrajectoryMethodDsaLsodar.h.
CVector< bool > CTrajectoryMethodDsaLsodar::CPartition::mLowSpecies private
A vector containing the current treatment of the species
Definition at line 233 of file CTrajectoryMethodDsaLsodar.h.
CVector< size_t > CTrajectoryMethodDsaLsodar::CPartition::mNumLowSpecies private
A vector containing the number of low species for each reaction
Definition at line 228 of file CTrajectoryMethodDsaLsodar.h.
size_t CTrajectoryMethodDsaLsodar::CPartition::mNumReactionSpecies private
The number of species determined by reactions
Definition at line 196 of file CTrajectoryMethodDsaLsodar.h.
speciesToReactionsMap CTrajectoryMethodDsaLsodar::CPartition::mSpeciesToReactions private
A map from a species index to the indexes of the reactions it participates in
Definition at line 176 of file CTrajectoryMethodDsaLsodar.h.
CVector< CReactionDependencies * > CTrajectoryMethodDsaLsodar::CPartition::mStochasticReactions
A vector containing pointers to stochastic reaction dependencies
Definition at line 202 of file CTrajectoryMethodDsaLsodar.h.
Referenced by CTrajectoryMethodDsaLsodar::calculatePropensities(), CTrajectoryMethodDsaLsodar::doSingleStep(), and CTrajectoryMethodDsaLsodar::fireReaction().
CVector< bool > CTrajectoryMethodDsaLsodar::CPartition::mStochasticSpecies
A vector indicating whether a species is treated stochastically or not.
Definition at line 212 of file CTrajectoryMethodDsaLsodar.h.
Referenced by CTrajectoryMethodDsaLsodar::evalF().
C_FLOAT64 CTrajectoryMethodDsaLsodar::CPartition::mUpperThreshold private
The threshold for switching to deterministic treatment
Definition at line 186 of file CTrajectoryMethodDsaLsodar.h.
The documentation for this class was generated from the following files:
CTrajectoryMethodDsaLsodar.h
CTrajectoryMethodDsaLsodar.cpp