COPASI API: CQNewMainWindow.cpp File Reference
CQNewMainWindow.cpp File Reference
#include <QtCore/QAbstractEventDispatcher>
#include <QtGui/QAction>
#include <QtGui/QActionGroup>
#include <QtGui/QCloseEvent>
#include <QtGui/QColor>
#include <QtGui/QColorDialog>
#include <QtGui/QComboBox>
#include <QtCore/QFileInfo>
#include <QtGui/QHBoxLayout>
#include <QtGui/QIcon>
#include <QtGui/QImage>
#include <QtGui/QLabel>
#include <QtGui/QPixmap>
#include <QtGui/QMenuBar>
#include <QtGui/QStackedWidget>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QVBoxLayout>
#include <QtCore/QTimer>
#include "CQGLLayoutPainter.h"
#include "CQGLLayoutViewer.h"
#include "CQNewMainWindow.h"
#include "CQPlayerControlWidget.h"
#include "CQScreenshotOptionsDialog.h"
#include "CQLayoutMainWindow.h"
#include "UI/CQMessageBox.h"
#include "UI/CopasiFileDialog.h"
#include <string.h>
#include "copasi/report/CCopasiRootContainer.h"
#include "copasi/CopasiDataModel/CCopasiDataModel.h"
#include "copasi/model/CModel.h"
#include "copasi/layout/CLayout.h"
#include "copasi/layout/CListOfLayouts.h"
#include "copasi/layout/CLDefaultStyles.h"
#include "copasi/elementaryFluxModes/CEFMTask.h"
#include "copasi/elementaryFluxModes/CEFMProblem.h"
#include "copasi/elementaryFluxModes/CFluxMode.h"
#include "copasi/model/CReaction.h"
#include "copasi/model/CChemEq.h"
#include "copasi/model/CChemEqElement.h"
#include "copasi/model/CMetab.h"
#include "copasi/layout/CLayoutEngine.h"
#include "copasi/layout/CLGlyphs.h"
#include "copasi/layout/CLBase.h"
#include "copasi/layout/CLCurve.h"
#include "copasi/report/CKeyFactory.h"
#include "layoutUI/CQLayoutThread.h"
#include "../UI/icons/photo.xpm"
#include "resourcesUI/CQIconResource.h"
#include "revert_curve.xpm"
#include "film_strip.xpm"
#include "graph.xpm"
#include "load_data.xpm"
#include <QtGui/QDockWidget>
#include "layout_start.xpm"
#include "layout_stop.xpm"
Functions
QRectF getBounds (const std::vector< CCopasiSpringLayout::UpdateAction > &updates)
Function Documentation
QRectF getBounds (const std::vector< CCopasiSpringLayout::UpdateAction > & updates)
Definition at line 1778 of file CQNewMainWindow.cpp.
References CCopasiSpringLayout::UpdateAction::COMPARTMENT_4V, CLGraphicalObject::getHeight(), CLGraphicalObject::getWidth(), CLGraphicalObject::getX(), CLGraphicalObject::getY(), CCopasiSpringLayout::UpdateAction::POSITION_2V, and CCopasiSpringLayout::UpdateAction::REACTION_2V.
 {
   QRectF result(1000, 1000, -1000, -1000);
   std::vector<CCopasiSpringLayout::UpdateAction>::const_iterator it, itEnd = updates.end();
   for (it = updates.begin(); it != itEnd; ++it)
     {
       switch (it->mAction)
         {
           case CCopasiSpringLayout::UpdateAction::COMPARTMENT_4V:
           {
             CLCompartmentGlyph* current = ((CLCompartmentGlyph*)(it->mpTarget));
             result.setLeft(qMin(result.left(), current->getX()));
             result.setTop(qMin(result.top(), current->getY()));
             result.setRight(qMax(result.right(), current->getX() + current->getWidth()));
             result.setBottom(qMax(result.bottom(), current->getY() + current->getHeight()));
           }
           break;
           case CCopasiSpringLayout::UpdateAction::POSITION_2V:
           {
             CLGraphicalObject* current = ((CLGraphicalObject*)(it->mpTarget));
             result.setLeft(qMin(result.left(), current->getX()));
             result.setTop(qMin(result.top(), current->getY()));
             result.setRight(qMax(result.right(), current->getX() + current->getWidth()));
             result.setBottom(qMax(result.bottom(), current->getY() + current->getHeight()));
           }
           break;
           case CCopasiSpringLayout::UpdateAction::REACTION_2V:
           {
             CLReactionGlyph* current = ((CLReactionGlyph*)(it->mpTarget));
             result.setLeft(qMin(result.left(), current->getX()));
             result.setTop(qMin(result.top(), current->getY()));
             result.setRight(qMax(result.right(), current->getX() + current->getWidth()));
             result.setBottom(qMax(result.bottom(), current->getY() + current->getHeight()));
           }
           break;
           default:
             break;
         };
     }
   return result;
 }