COPASI API: test000057 Class Reference
test000057 Class Reference
#include <test000057.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1006 ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1006)
CPPUNIT_TEST_SUITE (test000057)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000057.h.
Member Function Documentation
test000057::CPPUNIT_TEST (test_bug1006) private
test000057::CPPUNIT_TEST_SUITE (test000057) private
test000057::CPPUNIT_TEST_SUITE_END () private
void test000057::setUp ()
Definition at line 38 of file test000057.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000057::tearDown ()
Definition at line 46 of file test000057.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000057::test_bug1006 ()
Definition at line 51 of file test000057.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), CModelEntity::getSBMLId(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000057::MODEL_STRING));
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   const Model* pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getNumCompartments() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumSpecies() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumParameters() == 5);
   const Parameter* pParameter1 = pSBMLModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getConstant() == true);
   const Parameter* pParameter2 = pSBMLModel->getParameter(1);
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter2->getConstant() == true);
   const Parameter* pParameter3 = pSBMLModel->getParameter(2);
   CPPUNIT_ASSERT(pParameter3 != NULL);
   CPPUNIT_ASSERT(pParameter3->getConstant() == true);
   const Parameter* pParameter4 = pSBMLModel->getParameter(3);
   CPPUNIT_ASSERT(pParameter4 != NULL);
   CPPUNIT_ASSERT(pParameter4->getConstant() == true);
   const Parameter* pParameter5 = pSBMLModel->getParameter(4);
   CPPUNIT_ASSERT(pParameter5 != NULL);
   CPPUNIT_ASSERT(pParameter5->getConstant() == true);
   CPPUNIT_ASSERT(pSBMLModel->getNumInitialAssignments() == 5);
   const InitialAssignment* pIA = pSBMLModel->getInitialAssignment(0);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter1->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   const ASTNode* pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_TIMES);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   const ASTNode* pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 3.0) / 3.0) < 1e-15);
   const ASTNode* pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 4.0) / 4.0) < 1e-15);
   pIA = pSBMLModel->getInitialAssignment(1);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter2->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_PLUS);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 9.0) / 9.0) < 1e-15);
   pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 2.0) / 2.0) < 1e-15);
   pIA = pSBMLModel->getInitialAssignment(2);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter3->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_MINUS);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 8.0) / 8.0) < 1e-15);
   pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 4.0) / 4.0) < 1e-15);
   pIA = pSBMLModel->getInitialAssignment(3);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter4->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_DIVIDE);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 9.0) / 9.0) < 1e-15);
   pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 3.0) / 3.0) < 1e-15);
   pIA = pSBMLModel->getInitialAssignment(4);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter5->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_PLUS);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 6.0) / 6.0) < 1e-15);
   pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 1.0) / 1.0) < 1e-15);
   // delete some initial assignments
   // delete iniaitl assignments for model value1,model value4 and model value5
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 5);
   CModelValue *pMV1 = NULL, *pMV2 = NULL, *pMV3 = NULL, *pMV4 = NULL, *pMV5 = NULL;
   unsigned int i, iMax = pModel->getModelValues().size();
   for (i = 0; i < iMax; ++i)
     {
       CModelValue* pTmpMV = pModel->getModelValues()[i];
       if (pTmpMV->getSBMLId() == pParameter1->getId())
         {
           pMV1 = pTmpMV;
         }
       else if (pTmpMV->getSBMLId() == pParameter2->getId())
         {
           pMV2 = pTmpMV;
         }
       else if (pTmpMV->getSBMLId() == pParameter3->getId())
         {
           pMV3 = pTmpMV;
         }
       else if (pTmpMV->getSBMLId() == pParameter4->getId())
         {
           pMV4 = pTmpMV;
         }
       else if (pTmpMV->getSBMLId() == pParameter5->getId())
         {
           pMV5 = pTmpMV;
         }
     }
   CPPUNIT_ASSERT(pMV1 != NULL);
   CPPUNIT_ASSERT(pMV2 != NULL);
   CPPUNIT_ASSERT(pMV3 != NULL);
   CPPUNIT_ASSERT(pMV4 != NULL);
   CPPUNIT_ASSERT(pMV5 != NULL);
   pMV1->setInitialExpression("");
   pMV4->setInitialExpression("");
   pMV5->setInitialExpression("");
   // reexport the model to L2V3
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getNumCompartments() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumSpecies() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumParameters() == 5);
   pParameter1 = pSBMLModel->getParameter(0);
   CPPUNIT_ASSERT(pParameter1 != NULL);
   CPPUNIT_ASSERT(pParameter1->getConstant() == true);
   pParameter2 = pSBMLModel->getParameter(1);
   CPPUNIT_ASSERT(pParameter2 != NULL);
   CPPUNIT_ASSERT(pParameter2->getConstant() == true);
   pParameter3 = pSBMLModel->getParameter(2);
   CPPUNIT_ASSERT(pParameter3 != NULL);
   CPPUNIT_ASSERT(pParameter3->getConstant() == true);
   pParameter4 = pSBMLModel->getParameter(3);
   CPPUNIT_ASSERT(pParameter4 != NULL);
   CPPUNIT_ASSERT(pParameter4->getConstant() == true);
   pParameter5 = pSBMLModel->getParameter(4);
   CPPUNIT_ASSERT(pParameter5 != NULL);
   CPPUNIT_ASSERT(pParameter5->getConstant() == true);
   CPPUNIT_ASSERT(pSBMLModel->getNumInitialAssignments() == 2);
   pIA = pSBMLModel->getInitialAssignment(0);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter2->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_PLUS);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 9.0) / 9.0) < 1e-15);
   pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 2.0) / 2.0) < 1e-15);
   pIA = pSBMLModel->getInitialAssignment(1);
   CPPUNIT_ASSERT(pIA != NULL);
   CPPUNIT_ASSERT(pIA->getSymbol() == pParameter3->getId());
   CPPUNIT_ASSERT(pIA->isSetMath() == true);
   pMath = pIA->getMath();
   CPPUNIT_ASSERT(pMath != NULL);
   CPPUNIT_ASSERT(pMath->getType() == AST_MINUS);
   CPPUNIT_ASSERT(pMath->getNumChildren() == 2);
   pChild1 = pMath->getChild(0);
   CPPUNIT_ASSERT(pChild1 != NULL);
   CPPUNIT_ASSERT(pChild1->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild1->getReal() - 8.0) / 8.0) < 1e-15);
   pChild2 = pMath->getChild(1);
   CPPUNIT_ASSERT(pChild2 != NULL);
   CPPUNIT_ASSERT(pChild2->getType() == AST_REAL);
   CPPUNIT_ASSERT(fabs((pChild2->getReal() - 4.0) / 4.0) < 1e-15);
 }
Member Data Documentation
const char * test000057::MODEL_STRING static protected
Definition at line 31 of file test000057.h.
Referenced by test_bug1006().
CCopasiDataModel * test000057::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000057.h.
Referenced by setUp(), and test_bug1006().
The documentation for this class was generated from the following files:
test000057.h
test000057.cpp