COPASI API: CWriteConfig Class Reference
CWriteConfig Class Reference
#include <CWriteConfig.h>
Public Member Functions
CWriteConfig ()
CWriteConfig (const std::string &name, std::ios_base::openmode mode=std::ios_base::out)
C_INT32 fail ()
C_INT32 flush ()
void setDefaults ()
C_INT32 setVariable (const std::string &name, const std::string &type, const void *pout)
C_INT32 setVariable (const std::string &name, const std::string &type, const void *pout1, const void *pout2)
~CWriteConfig ()
Private Member Functions
C_INT32 commit ()
void writeVersion (void)
Private Attributes
std::stringstream mBuffer
C_INT32 mFail
std::string mFileName
unsigned C_INT32 mLineNumber
std::ios_base::openmode mOpenMode
Detailed Description
CWriteConfig class. A more elaborate class description.
New Class based on pmutils read functionality (C) Stefan Hoops 2001
Definition at line 25 of file CWriteConfig.h.
Constructor & Destructor Documentation
CWriteConfig::CWriteConfig (void)
Default consructor. This creates a configuration buffer without assigning a filename. It is currently useless.
Definition at line 30 of file CWriteConfig.cpp.
References mBuffer, mFail, mFileName, mLineNumber, and mOpenMode.
 {
   // initialize everything
   mFileName = "";
   mOpenMode = std::ios_base::out;
   mLineNumber = 0;
   mFail = 0;
   mBuffer.setf(std::ios_base::scientific);
   mBuffer.precision(16);
 }
CWriteConfig::CWriteConfig (const std::string & name, std::ios_base::openmode mode = std::ios_base::out)
Specified consructor. This opens the configuration file using the filename specified as the argument.
Parameters
name name of the confguration file.
mode output mode, defaults to creating a new file.
Definition at line 42 of file CWriteConfig.cpp.
References mBuffer, mFail, mFileName, mLineNumber, mOpenMode, and writeVersion().
 {
   // initialize everything
   mFileName = name;
   mOpenMode = mode;
   mLineNumber = 0;
   mFail = 0;
   mBuffer.setf(std::ios_base::scientific);
   mBuffer.precision(16);
   if (mOpenMode & std::ios_base::out)
     writeVersion();
 }
CWriteConfig::~CWriteConfig (void)
Destructor. The destructor calls the method flush().
Definition at line 57 of file CWriteConfig.cpp.
References commit().
 {
   commit();
 }
Member Function Documentation
C_INT32 CWriteConfig::commit (void) private
Commits all information to the configuration file. This method is called by the destructor.
Definition at line 75 of file CWriteConfig.cpp.
References fatalError, mBuffer, mFail, mFileName, and mOpenMode.
Referenced by flush(), and ~CWriteConfig().
 {
 #ifdef WIN32
   mOpenMode |= std::ios_base::binary;
 #endif
   std::ofstream ConfigFile(utf8ToLocale(mFileName).c_str(), mOpenMode);
   if (ConfigFile.fail())
     {
       fatalError();
       return mFail = 1;
     }
   ConfigFile << mBuffer.str();
   if (ConfigFile.fail())
     {
       fatalError();
       return mFail = 1;
     }
   mOpenMode |= std::ios_base::app;
   return mFail;
 }
C_INT32 CWriteConfig::fail ()
Returns the failure status.
Returns
mFail
See Also
mFail
Definition at line 104 of file CWriteConfig.cpp.
References mFail.
 {
   // return the failure state
   return mFail;
 }
C_INT32 CWriteConfig::flush (void)
Flush the output buffer to the configuration file.
Returns
mFail
See Also
mFail
Definition at line 62 of file CWriteConfig.cpp.
References commit(), fatalError, mBuffer, and mFail.
 {
   if (commit())
     {
       fatalError();
       return mFail;
     }
   mBuffer.str("");  // We need to reset the string buffer.
   return mFail;
 }
void CWriteConfig::setDefaults ()
Save various default values
Definition at line 101 of file CWriteConfig.cpp.
 {}
C_INT32 CWriteConfig::setVariable (const std::string & name, const std::string & type, const void * pout)
Writes a variable to the output file.
Parameters
name name of the variable to be written.
type type of the variable to be written.
*pout pointer to the location where the variable is stored.
Returns
mFail
See Also
mFail
Definition at line 110 of file CWriteConfig.cpp.
References C_FLOAT64, C_INT16, C_INT32, fatalError, mBuffer, mFail, and mLineNumber.
Referenced by writeVersion().
 {
   mBuffer << name;
   if (pout)
     {
       if (type != "multiline")
         mBuffer << "=";
       // Return the value depending on the type
       if (type == "string")
         {
           mBuffer << *(std::string *) pout;
         }
       else if (type == "C_FLOAT64")
         {
           mBuffer << *(C_FLOAT64 *) pout;
         }
       else if (type == "C_INT32")
         {
           mBuffer << *(C_INT32 *) pout;
         }
       else if (type == "C_INT16")
         {
           mBuffer << *(C_INT16 *) pout;
         }
       else if (type == "bool")
         {
           mBuffer << (*(bool *) pout) ? 1 : 0;
         }
       else if (type == "multiline")
         {
           mBuffer << std::endl;
           mBuffer << *(std::string *) pout << std::endl;
           mBuffer << "End" << name;
         }
       else
         {
           fatalError();
           mFail = 1; //Error
         }
     }
   mBuffer << std::endl;
   mLineNumber++;
   return mFail;
 }
C_INT32 CWriteConfig::setVariable (const std::string & name, const std::string & type, const void * pout1, const void * pout2)
Definition at line 161 of file CWriteConfig.cpp.
References C_INT32, fatalError, mBuffer, mFail, and mLineNumber.
 {
   mBuffer << name << "=";
   // Return the value depending on the type
   if (type == "node")
     {
       // pout1 and pout2 point to chars mType and mSubtype.
       // Therfore, we need this complicated cast.
       mBuffer << (C_INT32) (*(char *) pout1) << ","
       << (C_INT32) (*(char *) pout2)
       //  This will help to debug
       //  << "\t" << *(char *) pout1 << "," << *(char *) pout2
 ;
     }
   else
     {
       fatalError();
       mFail = 1; //Error
     }
   mBuffer << std::endl;
   mLineNumber++;
   return mFail;
 }
void CWriteConfig::writeVersion (void) private
Writes a version number to the file. This method is called by one of the constructors.
Definition at line 192 of file CWriteConfig.cpp.
References setVariable().
Referenced by CWriteConfig().
 {
   if (Copasi)
     setVariable("Version", "string", &Copasi->ProgramVersion.getVersion());
   else
     {
       std::string Version("4.0.0");
       setVariable("Version", "string", &Version);
     }
 }
Member Data Documentation
std::stringstream CWriteConfig::mBuffer private
Output file
Definition at line 108 of file CWriteConfig.h.
Referenced by commit(), CWriteConfig(), flush(), and setVariable().
C_INT32 CWriteConfig::mFail private
Failure status: 0 = no error !0 = error
Definition at line 125 of file CWriteConfig.h.
Referenced by commit(), CWriteConfig(), fail(), flush(), and setVariable().
std::string CWriteConfig::mFileName private
Name of the configuration file.
Definition at line 103 of file CWriteConfig.h.
Referenced by commit(), and CWriteConfig().
unsigned C_INT32 CWriteConfig::mLineNumber private
Current line number in the configuration file
Definition at line 113 of file CWriteConfig.h.
Referenced by CWriteConfig(), and setVariable().
std::ios_base::openmode CWriteConfig::mOpenMode private
Open mode
Definition at line 118 of file CWriteConfig.h.
Referenced by commit(), and CWriteConfig().
The documentation for this class was generated from the following files:
CWriteConfig.h
CWriteConfig.cpp