COPASI API: CLayout Class Reference
CLayout Class Reference
#include <CLayout.h>
Public Member Functions
void addCompartmentGlyph (CLCompartmentGlyph *glyph)
void addGeneralGlyph (CLGeneralGlyph *glyph)
void addLocalRenderInformation (CLLocalRenderInformation *pRenderInfo)
void addMetaboliteGlyph (CLMetabGlyph *glyph)
void addReactionGlyph (CLReactionGlyph *glyph)
void addTextGlyph (CLTextGlyph *glyph)
void calculateAndAssignBounds ()
CLBoundingBox calculateBoundingBox () const
CLayout (const std::string &name="Layout", const CCopasiContainer *pParent=NULL)
CLayout (const CLayout &src, const CCopasiContainer *pParent=NULL)
CLayout (const Layout &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
void exportToDotFile (std::ostream &os) const
void exportToSBML (Layout *layout, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs, const std::map< std::string, std::string > &globalKeyToIdMap) const
const CLDimensions & getDimensions () const
virtual const std::string & getKey () const
const CCopasiVector
< CLCompartmentGlyph > & getListOfCompartmentGlyphs () const
CCopasiVector
< CLCompartmentGlyph > & getListOfCompartmentGlyphs ()
const CCopasiVector
< CLGeneralGlyph > & getListOfGeneralGlyphs () const
CCopasiVector< CLGeneralGlyph > & getListOfGeneralGlyphs ()
const CCopasiVector
< CLLocalRenderInformation > & getListOfLocalRenderInformationObjects () const
CCopasiVector
< CLLocalRenderInformation > & getListOfLocalRenderInformationObjects ()
const CCopasiVector
< CLMetabGlyph > & getListOfMetaboliteGlyphs () const
CCopasiVector< CLMetabGlyph > & getListOfMetaboliteGlyphs ()
const CCopasiVector
< CLReactionGlyph > & getListOfReactionGlyphs () const
CCopasiVector< CLReactionGlyph > & getListOfReactionGlyphs ()
const CCopasiVector
< CLTextGlyph > & getListOfTextGlyphs () const
CCopasiVector< CLTextGlyph > & getListOfTextGlyphs ()
const CLLocalRenderInformation * getRenderInformation (size_t index) const
CLLocalRenderInformation * getRenderInformation (size_t index)
virtual void moveBy (const CLPoint &p)
void print (std::ostream *ostream) const
virtual void scale (const double &scaleFactor)
void setDimensions (const CLDimensions &d)
~CLayout ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Member Functions
void writeDotEdge (std::ostream &os, const std::string &id1, const std::string &id2, int t=0) const
void writeDotNode (std::ostream &os, const std::string &id, const std::string &label, int t=0) const
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
CLDimensions mDimensions
std::string mKey
CCopasiVector< CLCompartmentGlyph > mvCompartments
CCopasiVector< CLGeneralGlyph > mvGraphicalObjects
CCopasiVector< CLTextGlyph > mvLabels
CCopasiVector
< CLLocalRenderInformation > mvLocalRenderInformationObjects
CCopasiVector< CLMetabGlyph > mvMetabs
CCopasiVector< CLReactionGlyph > mvReactions
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Friends
std::ostream & operator<< (std::ostream &os, const CLayout &g)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
This class describes a reaction network layout. Its structure is exactly corresponding to the sbml layout extension
Definition at line 34 of file CLayout.h.
Constructor & Destructor Documentation
CLayout::CLayout (const std::string & name = "Layout", const CCopasiContainer * pParent = NULL)
Definition at line 38 of file CLayout.cpp.
   : CLBase(),
     CCopasiContainer(name, pParent, "Layout"),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Layout", this)),
     mDimensions(),
     mvCompartments("ListOfCompartmentGlyphs", this),
     mvMetabs("ListOfMetaboliteGlyphs", this),
     mvReactions("ListOfReactionGlyphs", this),
     mvLabels("ListOfTextGlyphs", this),
     mvGraphicalObjects("ListOfGraphicalObjects", this)
     , mvLocalRenderInformationObjects("ListOfLocalRenderInformationObjects", this)
 {}
CLayout::CLayout (const CLayout & src, const CCopasiContainer * pParent = NULL)
Definition at line 52 of file CLayout.cpp.
References CCopasiVector< T >::add(), CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CLTextGlyph::getGraphicalObjectKey(), CLGraphicalObject::getKey(), CCopasiObject::getKey(), CLReactionGlyph::getListOfMetabReferenceGlyphs(), CLGeneralGlyph::getListOfReferenceGlyphs(), CLGeneralGlyph::getListOfSubglyphs(), CLMetabReferenceGlyph::getMetabGlyphKey(), CLReferenceGlyph::getTargetGlyphKey(), mvCompartments, mvGraphicalObjects, mvLabels, mvMetabs, mvReactions, CLTextGlyph::setGraphicalObjectKey(), CLMetabReferenceGlyph::setMetabGlyphKey(), CLReferenceGlyph::setTargetGlyphKey(), and CCopasiVector< T >::size().
   : CLBase(src),
     CCopasiContainer(src, pParent),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Layout", this)),
     mDimensions(src.mDimensions),
     mvCompartments("ListOfCompartmentGlyphs", this),
     mvMetabs("ListOfMetaboliteGlyphs", this),
     mvReactions("ListOfReactionGlyphs", this),
     mvLabels("ListOfTextGlyphs", this),
     mvGraphicalObjects("ListOfGraphicalObjects", this)
     , mvLocalRenderInformationObjects(src.mvLocalRenderInformationObjects, this)
 {
   //TODO references from one glyph to another have to be reconstructed after
   //     copying. This applies to Labels and species reference glyphs
   std::map<std::string, std::string> forward;
   std::map<std::string, std::string> reverse;
   CCopasiVector<CLCompartmentGlyph>::const_iterator compIt = src.mvCompartments.begin();
   for (; compIt != src.mvCompartments.end(); ++compIt)
     {
       CLCompartmentGlyph *comp = new CLCompartmentGlyph(*(*compIt));
       mvCompartments.add(comp, true);
       forward[(*compIt)->getKey()] = comp->getKey();
       reverse[comp->getKey()] = (*compIt)->getKey();
     }
   CCopasiVector<CLMetabGlyph>::const_iterator metabIt = src.mvMetabs.begin();
   for (; metabIt != src.mvMetabs.end(); ++metabIt)
     {
       CLMetabGlyph *metab = new CLMetabGlyph(*(*metabIt));
       mvMetabs.add(metab, true);
       forward[(*metabIt)->getKey()] = metab->getKey();
       reverse[metab->getKey()] = (*metabIt)->getKey();
     }
   CCopasiVector<CLReactionGlyph>::const_iterator reactIt = src.mvReactions.begin();
   for (; reactIt != src.mvReactions.end(); ++reactIt)
     {
       CLReactionGlyph *r = new CLReactionGlyph(*(*reactIt));
       mvReactions.add(r, true);
       forward[(*reactIt)->getKey()] = r->getKey();
       reverse[r->getKey()] = (*reactIt)->getKey();
       for (size_t i = 0; i < r->getListOfMetabReferenceGlyphs().size(); ++i)
         {
           forward[(*reactIt)->getListOfMetabReferenceGlyphs()[i]->getKey()]
           = r->getListOfMetabReferenceGlyphs()[i]->getKey();
           reverse[r->getListOfMetabReferenceGlyphs()[i]->getKey()]
           = (*reactIt)->getListOfMetabReferenceGlyphs()[i]->getKey();
         }
     }
   CCopasiVector<CLTextGlyph>::const_iterator textIt = src.mvLabels.begin();
   for (; textIt != src.mvLabels.end(); ++textIt)
     {
       CLTextGlyph *text = new CLTextGlyph(*(*textIt));
       mvLabels.add(text, true);
       forward[(*textIt)->getKey()] = text->getKey();
       reverse[text->getKey()] = (*textIt)->getKey();
     }
   CCopasiVector<CLGeneralGlyph>::const_iterator generalIt = src.mvGraphicalObjects.begin();
   for (; generalIt != src.mvGraphicalObjects.end(); ++generalIt)
     {
       CLGeneralGlyph *general = new CLGeneralGlyph(*(*generalIt));
       mvGraphicalObjects.add(general, true);
       forward[(*generalIt)->getKey()] = general->getKey();
       reverse[general->getKey()] = (*generalIt)->getKey();
       for (size_t i = 0; i < general->getListOfReferenceGlyphs().size(); ++i)
         {
           forward[(*generalIt)->getListOfReferenceGlyphs()[i]->getKey()]
           = general->getListOfReferenceGlyphs()[i]->getKey();
           reverse[general->getListOfReferenceGlyphs()[i]->getKey()]
           = (*generalIt)->getListOfReferenceGlyphs()[i]->getKey();
         }
       for (size_t i = 0; i < general->getListOfSubglyphs().size(); ++i)
         {
           forward[(*generalIt)->getListOfSubglyphs()[i]->getKey()]
           = general->getListOfSubglyphs()[i]->getKey();
           reverse[general->getListOfSubglyphs()[i]->getKey()]
           = (*generalIt)->getListOfSubglyphs()[i]->getKey();
         }
     }
   {
     // by now we have collected all keys, now we need to replace them
     std::map<std::string, std::string>::const_iterator constIt;
     CCopasiVector<CLTextGlyph>::iterator textIt = mvLabels.begin();
     for (; textIt != mvLabels.end(); ++textIt)
       {
         CLTextGlyph *text = *textIt;
         const std::string& key = text->getGraphicalObjectKey();
         constIt = forward.find(key);
         if (constIt == forward.end())
           continue;
         text->setGraphicalObjectKey(constIt->second);
       }
     CCopasiVector<CLReactionGlyph>::iterator reactIt = mvReactions.begin();
     for (; reactIt != mvReactions.end(); ++reactIt)
       {
         CLReactionGlyph *r = *reactIt;
         CCopasiVector<CLMetabReferenceGlyph>::iterator refIt = r->getListOfMetabReferenceGlyphs().begin();
         for (; refIt != r->getListOfMetabReferenceGlyphs().end(); ++refIt)
           {
             CLMetabReferenceGlyph* current = *refIt;
             const std::string& key = current->getMetabGlyphKey();
             constIt = forward.find(key);
             if (constIt == forward.end())
               continue;
             current->setMetabGlyphKey(constIt->second);
           }
       }
     CCopasiVector<CLGeneralGlyph>::iterator generalIt = mvGraphicalObjects.begin();
     for (; generalIt != mvGraphicalObjects.end(); ++generalIt)
       {
         CLGeneralGlyph *g = *generalIt;
         CCopasiVector<CLReferenceGlyph>::iterator refIt = g->getListOfReferenceGlyphs().begin();
         for (; refIt != g->getListOfReferenceGlyphs().end(); ++refIt)
           {
             CLReferenceGlyph* current = *refIt;
             const std::string& key = current->getTargetGlyphKey();
             constIt = forward.find(key);
             if (constIt == forward.end())
               continue;
             current->setTargetGlyphKey(constIt->second);
           }
         //CCopasiVector<CLGraphicalObject>::iterator refIt = g->getListOfSubglyphs().begin();
         //for(;refIt != g->getListOfReferenceGlyphs().end(); ++refIt)
         //{
         //  CLGraphicalObject* current = *refIt;
         //  const std::string& key = current->getTargetGlyphKey();
         //  constIt = forward.find(key);
         //  if (constIt == forward.end())
         //    continue;
         //  current->setTargetGlyphKey(constIt->second);
         //}
       }
   }
 }
CLayout::CLayout (const Layout & sbml, std::map< std::string, std::string > & layoutmap, const CCopasiContainer * pParent = NULL)
constructor from libsbml object. Does not read the whole libsbml tree. Additional work is done in SBMLDocumentLoader
Definition at line 216 of file CLayout.cpp.
References mKey.
   : CLBase(sbml),
     CCopasiContainer(sbml.getId(), pParent, "Layout"),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Layout", this)),
     mDimensions(*sbml.getDimensions()),
     mvCompartments("ListOfCompartmentGlyphs", this),
     mvMetabs("ListOfMetaboliteGlyphs", this),
     mvReactions("ListOfReactionGlyphs", this),
     mvLabels("ListOfTextGlyphs", this),
     mvGraphicalObjects("ListOfGraphicalObjects", this)
     , mvLocalRenderInformationObjects("ListOfLocalRenderInformationObjects", this)
 {
   //add the copasi key to the map
   layoutmap[sbml.getId()] = mKey;
 }
CLayout::~CLayout ()
Definition at line 234 of file CLayout.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
void CLayout::addCompartmentGlyph (CLCompartmentGlyph * glyph)
add Glyph to layout. The layout takes ownership of the glyph.
Definition at line 239 of file CLayout.cpp.
References CCopasiVector< T >::add(), and mvCompartments.
Referenced by SBMLDocumentLoader::createLayout(), CCopasiSpringLayout::createLayout(), test000097::createModel(), and CCopasiXMLParser::CompartmentGlyphElement::start().
 {
   if (glyph)
     mvCompartments.add(glyph, true); //true means vector takes ownership
 }
void CLayout::addGeneralGlyph (CLGeneralGlyph * glyph)
add Glyph to layout. The layout takes ownership of the glyph.
Definition at line 263 of file CLayout.cpp.
References CCopasiVector< T >::add(), and mvGraphicalObjects.
Referenced by SBMLDocumentLoader::createLayout(), CCopasiSpringLayout::createLayout(), and CCopasiXMLParser::AdditionalGOElement::start().
 {
   if (glyph)
     mvGraphicalObjects.add(glyph, true); //true means vector takes ownership
 }
void CLayout::addLocalRenderInformation (CLLocalRenderInformation * pRenderInfo)
add local render information to layout. The layout takes ownership of the object.
Definition at line 646 of file CLayout.cpp.
References CCopasiVector< T >::add(), and mvLocalRenderInformationObjects.
Referenced by SBMLDocumentLoader::createLayout(), and CCopasiXMLParser::LocalRenderInformationElement::start().
 {
   if (pRenderInfo)
     {
       this->mvLocalRenderInformationObjects.add(pRenderInfo, true); //true means vector takes ownership
     }
 }
void CLayout::addMetaboliteGlyph (CLMetabGlyph * glyph)
add Glyph to layout. The layout takes ownership of the glyph.
Definition at line 245 of file CLayout.cpp.
References CCopasiVector< T >::add(), and mvMetabs.
Referenced by SBMLDocumentLoader::createLayout(), CCopasiSpringLayout::createLayout(), and CCopasiXMLParser::MetaboliteGlyphElement::start().
 {
   if (glyph)
     mvMetabs.add(glyph, true); //true means vector takes ownership
 }
void CLayout::addReactionGlyph (CLReactionGlyph * glyph)
add Glyph to layout. The layout takes ownership of the glyph.
Definition at line 251 of file CLayout.cpp.
References CCopasiVector< T >::add(), and mvReactions.
Referenced by SBMLDocumentLoader::createLayout(), CCopasiSpringLayout::createLayout(), and CCopasiXMLParser::ReactionGlyphElement::start().
 {
   if (glyph)
     mvReactions.add(glyph, true); //true means vector takes ownership
 }
void CLayout::addTextGlyph (CLTextGlyph * glyph)
add Glyph to layout. The layout takes ownership of the glyph.
Definition at line 257 of file CLayout.cpp.
References CCopasiVector< T >::add(), and mvLabels.
Referenced by SBMLDocumentLoader::createLayout(), CCopasiSpringLayout::createLayout(), and CCopasiXMLParser::TextGlyphElement::start().
 {
   if (glyph)
     mvLabels.add(glyph, true); //true means vector takes ownership
 }
void CLayout::calculateAndAssignBounds ()
Calculates the Bounding Box, moves the layout to the origin and assigns it to the layout.
Definition at line 955 of file CLayout.cpp.
References calculateBoundingBox(), CLBoundingBox::getDimensions(), CLBoundingBox::getPosition(), CLPoint::getX(), CLPoint::getY(), CLPoint::getZ(), moveBy(), and setDimensions().
Referenced by CCopasiSpringLayout::finalizeState().
 {
   CLBoundingBox bb = calculateBoundingBox();
   // move into the origin
   CLPoint differenceToOrigin(
     -bb.getPosition().getX(),
     -bb.getPosition().getY()
     , -bb.getPosition().getZ()
   );
   moveBy(differenceToOrigin);
   setDimensions(bb.getDimensions());
 }
CLBoundingBox CLayout::calculateBoundingBox () const
This methods calculates the bounding box of the layout. It traverses all layout objects and looks for the minimal and maximal x and y values that occur in the layout. These values are returned in the form of a bounding box where the minimal values are stored in the position and the maxima are given as the minimal values plus the corresponding dimension.
Definition at line 684 of file CLayout.cpp.
References CLCurve::calculateBoundingBox(), CLGraphicalObject::getBoundingBox(), CLGlyphWithCurve::getCurve(), CLBoundingBox::getDimensions(), CLDimensions::getHeight(), getListOfCompartmentGlyphs(), getListOfGeneralGlyphs(), getListOfMetaboliteGlyphs(), CLReactionGlyph::getListOfMetabReferenceGlyphs(), getListOfReactionGlyphs(), CLGeneralGlyph::getListOfReferenceGlyphs(), getListOfTextGlyphs(), CLCurve::getNumCurveSegments(), CLBoundingBox::getPosition(), CLDimensions::getWidth(), CLPoint::getX(), CLPoint::getY(), max, and CCopasiVector< T >::size().
Referenced by CQGLLayoutPainter::calculateAndAssignBounds(), calculateAndAssignBounds(), and CCopasiSpringLayout::createLayout().
 {
   double minX = std::numeric_limits<double>::max();
   double minY = minX;
   double maxX = -minX;
   double maxY = -minX;
   const CLGraphicalObject* pObject = NULL;
   const CLCurve* pCurve = NULL;
   const CLBoundingBox* pBB;
   const CLPoint* pP = NULL;
   const CLDimensions* pDim;
   size_t i, iMax = this->getListOfCompartmentGlyphs().size();
   double x, y, x2, y2;
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfCompartmentGlyphs()[i];
       pBB = &pObject->getBoundingBox();
       pP = &pBB->getPosition();
       x = pP->getX();
       y = pP->getY();
       pDim = &pBB->getDimensions();
       x2 = x + pDim->getWidth();
       y2 = y + pDim->getHeight();
       minX = (minX < x) ? minX : x;
       minY = (minY < y) ? minY : y;
       maxX = (maxX > x2) ? maxX : x2;
       maxY = (maxY > y2) ? maxY : y2;
     }
   iMax = this->getListOfMetaboliteGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfMetaboliteGlyphs()[i];
       pBB = &pObject->getBoundingBox();
       pP = &pBB->getPosition();
       x = pP->getX();
       y = pP->getY();
       pDim = &pBB->getDimensions();
       x2 = x + pDim->getWidth();
       y2 = y + pDim->getHeight();
       minX = (minX < x) ? minX : x;
       minY = (minY < y) ? minY : y;
       maxX = (maxX > x2) ? maxX : x2;
       maxY = (maxY > y2) ? maxY : y2;
     }
   iMax = this->getListOfTextGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfTextGlyphs()[i];
       pBB = &pObject->getBoundingBox();
       pP = &pBB->getPosition();
       x = pP->getX();
       y = pP->getY();
       pDim = &pBB->getDimensions();
       x2 = x + pDim->getWidth();
       y2 = y + pDim->getHeight();
       minX = (minX < x) ? minX : x;
       minY = (minY < y) ? minY : y;
       maxX = (maxX > x2) ? maxX : x2;
       maxY = (maxY > y2) ? maxY : y2;
     }
   size_t j, jMax;
   const CLGeneralGlyph* pGG = NULL;
   const CLReferenceGlyph* pRefG = NULL;
   iMax = this->getListOfGeneralGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pGG = this->getListOfGeneralGlyphs()[i];
       if (pGG->getCurve().getNumCurveSegments() > 0)
         {
           pCurve = &pGG->getCurve();
           CLBoundingBox bb = pCurve->calculateBoundingBox();
           pP = &bb.getPosition();
           x = pP->getX();
           y = pP->getY();
           pDim = &bb.getDimensions();
           x2 = x + pDim->getWidth();
           y2 = y + pDim->getHeight();
           minX = (minX < x) ? minX : x;
           minY = (minY < y) ? minY : y;
           maxX = (maxX > x2) ? maxX : x2;
           maxY = (maxY > y2) ? maxY : y2;
         }
       else
         {
           pBB = &pGG->getBoundingBox();
           pP = &pBB->getPosition();
           x = pP->getX();
           y = pP->getY();
           pDim = &pBB->getDimensions();
           x2 = x + pDim->getWidth();
           y2 = y + pDim->getHeight();
           minX = (minX < x) ? minX : x;
           minY = (minY < y) ? minY : y;
           maxX = (maxX > x2) ? maxX : x2;
           maxY = (maxY > y2) ? maxY : y2;
         }
       jMax = pGG->getListOfReferenceGlyphs().size();
       for (j = 0; j < jMax; ++j)
         {
           pRefG = pGG->getListOfReferenceGlyphs()[j];
           if (pRefG->getCurve().getNumCurveSegments() > 0)
             {
               pCurve = &pRefG->getCurve();
               CLBoundingBox bb = pCurve->calculateBoundingBox();
               pP = &bb.getPosition();
               x = pP->getX();
               y = pP->getY();
               pDim = &bb.getDimensions();
               x2 = x + pDim->getWidth();
               y2 = y + pDim->getHeight();
               minX = (minX < x) ? minX : x;
               minY = (minY < y) ? minY : y;
               maxX = (maxX > x2) ? maxX : x2;
               maxY = (maxY > y2) ? maxY : y2;
             }
           else
             {
               pBB = &pRefG->getBoundingBox();
               pP = &pBB->getPosition();
               x = pP->getX();
               y = pP->getY();
               pDim = &pBB->getDimensions();
               x2 = x + pDim->getWidth();
               y2 = y + pDim->getHeight();
               minX = (minX < x) ? minX : x;
               minY = (minY < y) ? minY : y;
               maxX = (maxX > x2) ? maxX : x2;
               maxY = (maxY > y2) ? maxY : y2;
             }
         }
     }
   const CLReactionGlyph* pRG = NULL;
   const CLMetabReferenceGlyph* pSRG = NULL;
   iMax = this->getListOfReactionGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pRG = this->getListOfReactionGlyphs()[i];
       if (pRG->getCurve().getNumCurveSegments() > 0)
         {
           pCurve = &pRG->getCurve();
           CLBoundingBox bb = pCurve->calculateBoundingBox();
           pP = &bb.getPosition();
           x = pP->getX();
           y = pP->getY();
           pDim = &bb.getDimensions();
           x2 = x + pDim->getWidth();
           y2 = y + pDim->getHeight();
           minX = (minX < x) ? minX : x;
           minY = (minY < y) ? minY : y;
           maxX = (maxX > x2) ? maxX : x2;
           maxY = (maxY > y2) ? maxY : y2;
         }
       else
         {
           pBB = &pRG->getBoundingBox();
           pP = &pBB->getPosition();
           x = pP->getX();
           y = pP->getY();
           pDim = &pBB->getDimensions();
           x2 = x + pDim->getWidth();
           y2 = y + pDim->getHeight();
           minX = (minX < x) ? minX : x;
           minY = (minY < y) ? minY : y;
           maxX = (maxX > x2) ? maxX : x2;
           maxY = (maxY > y2) ? maxY : y2;
         }
       jMax = pRG->getListOfMetabReferenceGlyphs().size();
       for (j = 0; j < jMax; ++j)
         {
           pSRG = pRG->getListOfMetabReferenceGlyphs()[j];
           if (pSRG->getCurve().getNumCurveSegments() > 0)
             {
               pCurve = &pSRG->getCurve();
               CLBoundingBox bb = pCurve->calculateBoundingBox();
               pP = &bb.getPosition();
               x = pP->getX();
               y = pP->getY();
               pDim = &bb.getDimensions();
               x2 = x + pDim->getWidth();
               y2 = y + pDim->getHeight();
               minX = (minX < x) ? minX : x;
               minY = (minY < y) ? minY : y;
               maxX = (maxX > x2) ? maxX : x2;
               maxY = (maxY > y2) ? maxY : y2;
             }
           else
             {
               pBB = &pSRG->getBoundingBox();
               pP = &pBB->getPosition();
               x = pP->getX();
               y = pP->getY();
               pDim = &pBB->getDimensions();
               x2 = x + pDim->getWidth();
               y2 = y + pDim->getHeight();
               minX = (minX < x) ? minX : x;
               minY = (minY < y) ? minY : y;
               maxX = (maxX > x2) ? maxX : x2;
               maxY = (maxY > y2) ? maxY : y2;
             }
         }
     }
   return CLBoundingBox(CLPoint(minX, minY), CLDimensions(maxX - minX, maxY - minY));
 }
void CLayout::exportToDotFile (std::ostream & os) const
Definition at line 331 of file CLayout.cpp.
References getKey(), CCopasiObject::getKey(), CLMetabReferenceGlyph::getMetabGlyphKey(), CLMetabReferenceGlyph::getRole(), mvMetabs, mvReactions, CLMetabReferenceGlyph::PRODUCT, CCopasiVector< T >::size(), CLMetabReferenceGlyph::SUBSTRATE, writeDotEdge(), and writeDotNode().
 {
   os << "digraph G {\n";
   //species glyphs
   size_t i, imax = mvMetabs.size();
   for (i = 0; i < imax; ++i)
     {
       writeDotNode(os, mvMetabs[i]->getKey(), mvMetabs[i]->getModelObjectDisplayName());
     }
   //reaction glyphs
   imax = mvReactions.size();
   for (i = 0; i < imax; ++i)
     {
       writeDotNode(os, mvReactions[i]->getKey() + "_S", "", 1);
       writeDotNode(os, mvReactions[i]->getKey() + "_P", "", 1);
       writeDotEdge(os, mvReactions[i]->getKey() + "_S", mvReactions[i]->getKey() + "_P", 1);
       size_t j, jmax = mvReactions[i]->getListOfMetabReferenceGlyphs().size();
       for (j = 0; j < jmax; ++j)
         {
           CLMetabReferenceGlyph* mrg = mvReactions[i]->getListOfMetabReferenceGlyphs()[j];
           if (mrg->getRole() == CLMetabReferenceGlyph::SUBSTRATE)
             writeDotEdge(os, mrg->getMetabGlyphKey(), mvReactions[i]->getKey() + "_S");
           else if (mrg->getRole() == CLMetabReferenceGlyph::PRODUCT)
             writeDotEdge(os, mvReactions[i]->getKey() + "_P", mrg->getMetabGlyphKey());
         }
     }
   os << "}" << std::endl;
 }
void CLayout::exportToSBML (Layout * layout, const std::map< const CCopasiObject *, SBase * > & copasimodelmap, std::map< std::string, const SBase * > & sbmlIDs, const std::map< std::string, std::string > & globalKeyToIdMap) const
This method writes the information of the copasi layout object into the corresponding sbml object
Definition at line 392 of file CLayout.cpp.
References SBMLDocumentLoader::convertLayoutObjectKeys(), CSBMLExporter::createUniqueId(), CLTextGlyph::exportReferenceToSBML(), CLMetabGlyph::exportToSBML(), CLCompartmentGlyph::exportToSBML(), CLTextGlyph::exportToSBML(), CLGeneralGlyph::exportToSBML(), CLReactionGlyph::exportToSBML(), getKey(), CLGraphicalObject::getKey(), CLGeneralGlyph::getListOfReferenceGlyphs(), CLDimensions::getSBMLDimensions(), mDimensions, mvCompartments, mvGraphicalObjects, mvLabels, mvLocalRenderInformationObjects, mvMetabs, mvReactions, and CCopasiVector< T >::size().
Referenced by CListOfLayouts::exportToSBML().
 {
   if (!layout) return;
   //Name and ID
   std::string id = CSBMLExporter::createUniqueId(sbmlIDs, "layout", true);
   layout->setId(id);
   sbmlIDs.insert(std::pair<const std::string, const SBase*>(id, layout));
   //we do not check if the layout is already present in the libsbml data
   //structures. This is no big deal since at the moment no software
   //relies on persistent IDs for layout elements.
   //Dimensions
   Dimensions tmpDim = mDimensions.getSBMLDimensions();
   layout->setDimensions(&tmpDim);
   //some of the following code is not used at the moment:  the COPASI model map
   //does not contain glyphs. Since this may change in the future I leave the code
   //below.
   // create a map from COPASI layout object to SBML objects. We do not put
   //the layout objects into the global map (copasimodelmap) but we need to have
   //access to all objects in the current layout since speciesReferenceGlyph and
   //textGlyph need to reference other graphical objects.
   std::map<const CLBase*, const SBase*> layoutmap;
   //Compartment glyphs
   size_t i, imax = mvCompartments.size();
   for (i = 0; i < imax; ++i)
     {
       CLCompartmentGlyph * tmp = mvCompartments[i];
       //check if the compartment glyph exists in the libsbml data
       std::map<const CCopasiObject*, SBase*>::const_iterator it;
       it = copasimodelmap.find(tmp);
       CompartmentGlyph * pCG;
       if (it == copasimodelmap.end()) //not found
         {
           pCG = layout->createCompartmentGlyph();
         }
       else
         {
           pCG = dynamic_cast<CompartmentGlyph*>(it->second);
         }
       layoutmap.insert(std::pair<const CLBase*, const SBase*>(tmp, pCG));
       tmp->exportToSBML(pCG, copasimodelmap, sbmlIDs);
     }
   //Species glyphs
   imax = mvMetabs.size();
   for (i = 0; i < imax; ++i)
     {
       CLMetabGlyph * tmp = mvMetabs[i];
       //check if the glyph exists in the libsbml data
       std::map<const CCopasiObject*, SBase*>::const_iterator it;
       it = copasimodelmap.find(tmp);
       SpeciesGlyph * pG;
       if (it == copasimodelmap.end()) //not found
         {
           pG = layout->createSpeciesGlyph();
         }
       else
         {
           pG = dynamic_cast<SpeciesGlyph*>(it->second);
         }
       layoutmap.insert(std::pair<const CLBase*, const SBase*>(tmp, pG));
       tmp->exportToSBML(pG, copasimodelmap, sbmlIDs);
     }
   //Reaction glyphs
   imax = mvReactions.size();
   for (i = 0; i < imax; ++i)
     {
       CLReactionGlyph * tmp = mvReactions[i];
       //check if the glyph exists in the libsbml data
       std::map<const CCopasiObject*, SBase*>::const_iterator it;
       it = copasimodelmap.find(tmp);
       ReactionGlyph * pG;
       if (it == copasimodelmap.end()) //not found
         {
           pG = layout->createReactionGlyph();
         }
       else
         {
           pG = dynamic_cast<ReactionGlyph*>(it->second);
         }
       layoutmap.insert(std::pair<const CLBase*, const SBase*>(tmp, pG));
       //we need to pass the layoutmap here for 2 reasons:
       //1. the metabreferenceglyphs need to be added
       //2. the metabreferenceglyphs need to resolve the reference to the metabglyph
       tmp->exportToSBML(pG, copasimodelmap, sbmlIDs, layoutmap);
     }
   //Text glyphs
   imax = mvLabels.size();
   for (i = 0; i < imax; ++i)
     {
       CLTextGlyph * tmp = mvLabels[i];
       //check if the glyph exists in the libsbml data
       std::map<const CCopasiObject*, SBase*>::const_iterator it;
       it = copasimodelmap.find(tmp);
       TextGlyph * pG;
       if (it == copasimodelmap.end()) //not found
         {
           pG = layout->createTextGlyph();
         }
       else
         {
           pG = dynamic_cast<TextGlyph*>(it->second);
         }
       layoutmap.insert(std::pair<const CLBase*, const SBase*>(tmp, pG));
       tmp->exportToSBML(pG, copasimodelmap, sbmlIDs);
     }
   //generic glyphs
   imax = mvGraphicalObjects.size();
   for (i = 0; i < imax; ++i)
     {
       CLGeneralGlyph * tmp = mvGraphicalObjects[i];
       //check if the glyph exists in the libsbml data
       std::map<const CCopasiObject*, SBase*>::const_iterator it;
       it = copasimodelmap.find(tmp);
       GraphicalObject * pG;
       if (it == copasimodelmap.end()) //not found
         {
 #if LIBSBML_VERSION >= 50800
           if (tmp->getListOfReferenceGlyphs().size() > 0)
             pG = layout->createGeneralGlyph();
           else
 #endif // LIBSBML_VERSION >= 50800
             pG = layout->createAdditionalGraphicalObject();
         }
       else
         {
           pG = dynamic_cast<GraphicalObject*>(it->second);
         }
       layoutmap.insert(std::pair<const CLBase*, const SBase*>(tmp, pG));
       tmp->exportToSBML(pG, copasimodelmap, sbmlIDs, layoutmap);
     }
   //now that we have all graphical objects in the layoutmap we can resolve the references
   //in the text glyphs
   imax = mvLabels.size();
   for (i = 0; i < imax; ++i)
     {
       const CLTextGlyph * tmp = mvLabels[i];
       //find the corresponding SBML object
       std::map<const CLBase*, const SBase*>::const_iterator it = layoutmap.find(tmp);
       if (it != layoutmap.end() && it->second && dynamic_cast<const TextGlyph*>(it->second))
         {
           tmp->exportReferenceToSBML(const_cast<TextGlyph*>(dynamic_cast<const TextGlyph*>(it->second)), layoutmap);
         }
     }
   // export the local render information
   imax = this->mvLocalRenderInformationObjects.size();
   LocalRenderInformation* pLRI = NULL;
   std::map<std::string, std::string> keyToIdMap;
   /*
   std::map<std::string,std::string> colorKeyToIdMap;
   std::map<std::string,std::string> gradientKeyToIdMap;
   std::map<std::string,std::string> lineEndingKeyToIdMap;
   std::map<std::string,std::map<std::string,std::string> > colorKeyToIdMapMap;
   std::map<std::string,std::map<std::string,std::string> > gradientKeyToIdMapMap;
   std::map<std::string,std::map<std::string,std::string> > lineEndingKeyToIdMapMap;
   */
   for (i = 0; i < imax; ++i)
     {
       //colorKeyToIdMap.clear();
       //gradientKeyToIdMap.clear();
       //lineEndingKeyToIdMap.clear();
       //pLRI=this->mvLocalRenderInformationObjects[i]->toSBML(colorKeyToIdMap,gradientKeyToIdMap,lineEndingKeyToIdMap);
       pLRI = this->mvLocalRenderInformationObjects[i]->toSBML(layout->getLevel(), layout->getVersion());
       keyToIdMap.insert(std::pair<std::string, std::string>(this->mvLocalRenderInformationObjects[i]->getKey(), pLRI->getId()));
       //colorKeyToIdMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pLRI->getId(),colorKeyToIdMap));
       //gradientKeyToIdMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pLRI->getId(),gradientKeyToIdMap));
       //lineEndingKeyToIdMapMap.insert(std::pair<std::string,std::map<std::string,std::string> >(pLRI->getId(),lineEndingKeyToIdMap));
       // fix the references to layout objects in id lists
       std::map<const CLBase*, const SBase*>::const_iterator layoutMapIt = layoutmap.begin(), layoutMapEndit = layoutmap.end();
       std::map<std::string, std::string> layoutObjectKeyToIdMap;
       const CLGraphicalObject* pGObject = NULL;
       while (layoutMapIt != layoutMapEndit)
         {
           pGObject = dynamic_cast<const CLGraphicalObject*>(layoutMapIt->first);
           if (pGObject != NULL)
             {
               layoutObjectKeyToIdMap.insert(std::pair<std::string, std::string>(pGObject->getKey(), layoutMapIt->second->getId()));
             }
           ++layoutMapIt;
         }
       size_t j, jMax = pLRI->getNumStyles();
       for (j = 0; j < jMax; ++j)
         {
           SBMLDocumentLoader::convertLayoutObjectKeys(*(pLRI->getStyle((unsigned int) j)), layoutObjectKeyToIdMap);
         }
       RenderLayoutPlugin* rlolPlugin = (RenderLayoutPlugin*) layout->getPlugin("render");
       if (rlolPlugin == NULL)
         {
           const std::string uri = (layout->getLevel() < 3 ? RenderExtension::getXmlnsL2() : RenderExtension::getXmlnsL3V1V1());
           layout->enablePackage(uri, "render", true);
           if (layout->getLevel() > 2)
             layout->getSBMLDocument()->setPackageRequired("render", false);
           rlolPlugin = (RenderLayoutPlugin*) layout->getPlugin("render");
         }
       if (rlolPlugin != NULL)
         rlolPlugin->getListOfLocalRenderInformation()->appendAndOwn(pLRI);
     }
 }
const CLDimensions& CLayout::getDimensions () const inline
Definition at line 76 of file CLayout.h.
References mDimensions.
Referenced by CQGLLayoutPainter::calculateAndAssignBounds(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::draw_layout(), CCopasiSpringLayout::randomize(), and CCopasiXML::saveLayoutList().
 {return mDimensions;};
virtual const std::string& CLayout::getKey () const inline virtual
Retrieves the key of the layout
Reimplemented from CCopasiObject.
Definition at line 71 of file CLayout.h.
References mKey.
Referenced by CQLayoutsWidget::createLayoutWindow(), exportToDotFile(), exportToSBML(), CCopasiXML::saveLayoutList(), CQLayoutsWidget::slotShowLayout(), and CQNewMainWindow::updateLayoutList().
   {return mKey;};
const CCopasiVector<CLCompartmentGlyph>& CLayout::getListOfCompartmentGlyphs () const inline
Definition at line 81 of file CLayout.h.
References mvCompartments.
Referenced by CLayoutState::applyTo(), calculateBoundingBox(), CLayoutState::CLayoutState(), CQGLNetworkPainter::createGraph(), CQLayoutScene::fillFromLayout(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CCopasiSpringLayout::initFromLayout(), moveBy(), CCopasiSpringLayout::randomize(), CCopasiXML::saveLayoutList(), CQNewMainWindow::slotCalculateDimensions(), CQNewMainWindow::slotRunRandomizeLayout(), CLayoutState::tagLayout(), and CLLayoutRenderer::update_associations().
   {return mvCompartments;};
CCopasiVector<CLCompartmentGlyph>& CLayout::getListOfCompartmentGlyphs () inline
Definition at line 84 of file CLayout.h.
References mvCompartments.
   {return mvCompartments;};
const CCopasiVector<CLGeneralGlyph>& CLayout::getListOfGeneralGlyphs () const inline
Definition at line 133 of file CLayout.h.
References mvGraphicalObjects.
Referenced by CLayoutState::applyTo(), calculateBoundingBox(), CLayoutState::CLayoutState(), CCopasiSpringLayout::createVariables(), CQLayoutScene::fillFromLayout(), CCopasiSpringLayout::finalizeState(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CCopasiSpringLayout::getPotential(), moveBy(), CCopasiXML::saveLayoutList(), CLayoutState::tagLayout(), and CLLayoutRenderer::update_associations().
   {return mvGraphicalObjects;};
CCopasiVector<CLGeneralGlyph>& CLayout::getListOfGeneralGlyphs () inline
Definition at line 136 of file CLayout.h.
References mvGraphicalObjects.
   {return mvGraphicalObjects;};
const CCopasiVector<CLLocalRenderInformation>& CLayout::getListOfLocalRenderInformationObjects () const inline
Returns a const reference to the list of local render information objects.
Definition at line 149 of file CLayout.h.
References mvLocalRenderInformationObjects.
Referenced by CLLayoutRenderer::change_style(), SBMLDocumentLoader::createLayout(), CQLayoutScene::initializeResolver(), CCopasiXML::saveLayoutList(), CQNewMainWindow::slotRenderInfoChanged(), CQLayoutView::slotRenderInformationChanged(), CCopasiXMLParser::LocalRenderInformationElement::start(), updateRenderInformationList(), and CQNewMainWindow::updateRenderInformationList().
   {return this->mvLocalRenderInformationObjects;};
CCopasiVector<CLLocalRenderInformation>& CLayout::getListOfLocalRenderInformationObjects () inline
Returns a reference to the list of local render information objects.
Definition at line 155 of file CLayout.h.
References mvLocalRenderInformationObjects.
   {return this->mvLocalRenderInformationObjects;};
const CCopasiVector<CLMetabGlyph>& CLayout::getListOfMetaboliteGlyphs () const inline
Definition at line 94 of file CLayout.h.
References mvMetabs.
Referenced by CLayoutState::applyTo(), calculateBoundingBox(), CLayoutState::CLayoutState(), CQGLNetworkPainter::createGraph(), CCopasiSpringLayout::createLayout(), CCopasiSpringLayout::createVariables(), CQLayoutScene::fillFromLayout(), getMetabGlyphForKey(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CCopasiSpringLayout::getPotential(), CCopasiSpringLayout::initFromLayout(), moveBy(), CCopasiSpringLayout::randomize(), CCopasiXML::saveLayoutList(), CQNewMainWindow::selectMetabolite(), CQNewMainWindow::slotCalculateDimensions(), CQNewMainWindow::slotRunRandomizeLayout(), CLayoutState::tagLayout(), and CLLayoutRenderer::update_associations().
   {return mvMetabs;};
CCopasiVector<CLMetabGlyph>& CLayout::getListOfMetaboliteGlyphs () inline
Definition at line 97 of file CLayout.h.
References mvMetabs.
   {return mvMetabs;};
const CCopasiVector<CLReactionGlyph>& CLayout::getListOfReactionGlyphs () const inline
Definition at line 107 of file CLayout.h.
References mvReactions.
Referenced by CLayoutState::applyTo(), calculateBoundingBox(), CLayoutState::CLayoutState(), CQGLNetworkPainter::createGraph(), CCopasiSpringLayout::createVariables(), CQLayoutScene::fillFromLayout(), CCopasiSpringLayout::finalizeState(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CCopasiSpringLayout::getPotential(), CCopasiSpringLayout::initFromLayout(), moveBy(), CCopasiSpringLayout::randomize(), CCopasiXML::saveLayoutList(), CQNewMainWindow::selectReaction(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), CLayoutState::tagLayout(), and CLLayoutRenderer::update_associations().
   {return mvReactions;};
CCopasiVector<CLReactionGlyph>& CLayout::getListOfReactionGlyphs () inline
Definition at line 110 of file CLayout.h.
References mvReactions.
   {return mvReactions;};
const CCopasiVector<CLTextGlyph>& CLayout::getListOfTextGlyphs () const inline
Definition at line 120 of file CLayout.h.
References mvLabels.
Referenced by CLayoutState::applyTo(), calculateBoundingBox(), CLayoutState::CLayoutState(), CQGLNetworkPainter::createGraph(), CQLayoutScene::fillFromLayout(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), getTextForItem(), CCopasiSpringLayout::initFromLayout(), moveBy(), placeTextGlyphs(), CCopasiXML::saveLayoutList(), CLayoutState::tagLayout(), and CLLayoutRenderer::update_associations().
   {return mvLabels;};
CCopasiVector<CLTextGlyph>& CLayout::getListOfTextGlyphs () inline
Definition at line 123 of file CLayout.h.
References mvLabels.
   {return mvLabels;};
const CLLocalRenderInformation * CLayout::getRenderInformation (size_t index) const
Returns a const pointer to the local render information with the given index or NULL if the index is invalid.
Definition at line 658 of file CLayout.cpp.
References mvLocalRenderInformationObjects, and CCopasiVector< T >::size().
Referenced by CQNewMainWindow::slotRenderInfoChanged(), and CQNewMainWindow::updateRenderInformationList().
 {
   if (index >= this->mvLocalRenderInformationObjects.size()) return NULL;
   return this->mvLocalRenderInformationObjects[index];
 }
CLLocalRenderInformation * CLayout::getRenderInformation (size_t index)
Returns a pointer to the local render information with the given index or NULL if the index is invalid.
Definition at line 669 of file CLayout.cpp.
References mvLocalRenderInformationObjects, and CCopasiVector< T >::size().
 {
   if (index >= this->mvLocalRenderInformationObjects.size()) return NULL;
   return this->mvLocalRenderInformationObjects[index];
 }
void CLayout::moveBy (const CLPoint & p) virtual
Reimplemented from CLBase.
Definition at line 909 of file CLayout.cpp.
References getListOfCompartmentGlyphs(), getListOfGeneralGlyphs(), getListOfMetaboliteGlyphs(), getListOfReactionGlyphs(), getListOfTextGlyphs(), CLPoint::isEmpty(), CLGraphicalObject::moveBy(), and CCopasiVector< T >::size().
Referenced by CQGLLayoutPainter::calculateAndAssignBounds(), and calculateAndAssignBounds().
 {
   if (p.isEmpty()) return;
   CLGraphicalObject* pObject = NULL;
   size_t i, iMax = this->getListOfCompartmentGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfCompartmentGlyphs()[i];
       pObject->moveBy(p);
     }
   iMax = this->getListOfMetaboliteGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfMetaboliteGlyphs()[i];
       pObject->moveBy(p);
     }
   iMax = this->getListOfReactionGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfReactionGlyphs()[i];
       pObject->moveBy(p);
     }
   iMax = this->getListOfTextGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfTextGlyphs()[i];
       pObject->moveBy(p);
     }
   iMax = this->getListOfGeneralGlyphs().size();
   for (i = 0; i < iMax; ++i)
     {
       pObject = this->getListOfGeneralGlyphs()[i];
       pObject->moveBy(p);
     }
 }
void CLayout::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 328 of file CLayout.cpp.
 {*os << *this;}
virtual void CLayout::scale (const double & scaleFactor) inline virtual
Definition at line 190 of file CLayout.h.
References mDimensions, and CLDimensions::scale().
 {this->mDimensions.scale(scaleFactor);}
void CLayout::setDimensions (const CLDimensions & d) inline
Definition at line 77 of file CLayout.h.
References mDimensions.
Referenced by calculateAndAssignBounds(), CCopasiSpringLayout::createLayout(), test000097::createModel(), and CCopasiXMLParser::LayoutElement::start().
 {mDimensions = d;};
void CLayout::writeDotEdge (std::ostream & os, const std::string & id1, const std::string & id2, int t = 0) const protected
Definition at line 380 of file CLayout.cpp.
Referenced by exportToDotFile().
 {
   std::string tmp;
   if (t == 1)
     tmp = " [len=0.2] ";
   os << id1 << " -> " << id2 << tmp << "\n"; //[label=\"" << label << "\"] \n";
 }
void CLayout::writeDotNode (std::ostream & os, const std::string & id, const std::string & label, int t = 0) const protected
Definition at line 368 of file CLayout.cpp.
Referenced by exportToDotFile().
 {
   std::string tmp;
   if (t == 1)
     tmp = " shape=point ";
   os << id << " [" << tmp << " label=\"" << label << "\"] \n";
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLayout & g) friend
insert operator
Definition at line 269 of file CLayout.cpp.
 {
   size_t i, imax;
   os << "Layout  \"" << l.getObjectName() << "\" " << l.mDimensions << "\n\n";
   imax = l.mvCompartments.size();
   if (imax)
     {
       os << "List of compartment glyphs: \n\n";
       for (i = 0; i < imax; ++i)
         os << *l.mvCompartments[i];
     }
   imax = l.mvMetabs.size();
   if (imax)
     {
       os << "\nList of species glyphs: \n\n";
       for (i = 0; i < imax; ++i)
         os << *l.mvMetabs[i];
     }
   imax = l.mvReactions.size();
   if (imax)
     {
       os << "\nList of reaction glyphs: \n\n";
       for (i = 0; i < imax; ++i)
         os << *l.mvReactions[i];
     }
   imax = l.mvLabels.size();
   if (imax)
     {
       os << "\nList of labels: \n\n";
       for (i = 0; i < imax; ++i)
         os << *l.mvLabels[i];
     }
   imax = l.mvGraphicalObjects.size();
   if (imax)
     {
       os << "\nList of graphical objects: \n\n";
       for (i = 0; i < imax; ++i)
         os << *l.mvGraphicalObjects[i];
     }
   return os;
 }
Member Data Documentation
CLDimensions CLayout::mDimensions protected
Definition at line 40 of file CLayout.h.
Referenced by exportToSBML(), getDimensions(), operator<<(), scale(), and setDimensions().
std::string CLayout::mKey protected
Definition at line 38 of file CLayout.h.
Referenced by CLayout(), getKey(), and ~CLayout().
CCopasiVector<CLCompartmentGlyph> CLayout::mvCompartments protected
Definition at line 42 of file CLayout.h.
Referenced by addCompartmentGlyph(), CLayout(), exportToSBML(), getListOfCompartmentGlyphs(), and operator<<().
CCopasiVector<CLGeneralGlyph> CLayout::mvGraphicalObjects protected
Definition at line 46 of file CLayout.h.
Referenced by addGeneralGlyph(), CLayout(), exportToSBML(), getListOfGeneralGlyphs(), and operator<<().
CCopasiVector<CLTextGlyph> CLayout::mvLabels protected
Definition at line 45 of file CLayout.h.
Referenced by addTextGlyph(), CLayout(), exportToSBML(), getListOfTextGlyphs(), and operator<<().
CCopasiVector<CLLocalRenderInformation> CLayout::mvLocalRenderInformationObjects protected
Definition at line 47 of file CLayout.h.
Referenced by addLocalRenderInformation(), exportToSBML(), getListOfLocalRenderInformationObjects(), and getRenderInformation().
CCopasiVector<CLMetabGlyph> CLayout::mvMetabs protected
Definition at line 43 of file CLayout.h.
Referenced by addMetaboliteGlyph(), CLayout(), exportToDotFile(), exportToSBML(), getListOfMetaboliteGlyphs(), and operator<<().
CCopasiVector<CLReactionGlyph> CLayout::mvReactions protected
Definition at line 44 of file CLayout.h.
Referenced by addReactionGlyph(), CLayout(), exportToDotFile(), exportToSBML(), getListOfReactionGlyphs(), and operator<<().
The documentation for this class was generated from the following files:
CLayout.h
CLayout.cpp