COPASI API: CScanProblem Class Reference
CScanProblem Class Reference
#include <CScanProblem.h>
Public Types
enum Type { SCAN_REPEAT = 0, SCAN_LINEAR, SCAN_RANDOM, SCAN_BREAK }
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CCopasiParameterGroup * addScanItem (CScanProblem::Type type, size_t steps=5, const CCopasiObject *obj=NULL)
void clearScanItems ()
CScanProblem (const CCopasiContainer *pParent=NULL)
CScanProblem (const CScanProblem &src, const CCopasiContainer *pParent=NULL)
void fixBuild81 ()
bool getContinueFromCurrentState () const
size_t getNumberOfScanItems () const
const bool & getOutputInSubtask () const
const CCopasiParameterGroup * getScanItem (size_t index) const
CCopasiParameterGroup * getScanItem (size_t index)
CCopasiTask::Type getSubtask () const
void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::NEXT)
bool removeScanItem (const size_t &index)
void setContinueFromCurrentState (bool aic)
void setOutputInSubtask (bool ois)
void setSubtask (CCopasiTask::Type type)
~CScanProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual bool initialize ()
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setModel (CModel *pModel)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CCopasiParameterGroup * createScanItem (CScanProblem::Type type, size_t steps=5, const CCopasiObject *obj=NULL)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Private Member Functions
void initializeParameter ()
Private Attributes
CCopasiParameterGroup * mpScanItems
Additional Inherited Members
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CScanProblem class.
Definition at line 30 of file CScanProblem.h.
Member Enumeration Documentation
enum CScanProblem::Type
Enumerator
SCAN_REPEAT
SCAN_LINEAR
SCAN_RANDOM
SCAN_BREAK
Definition at line 33 of file CScanProblem.h.
   {
     SCAN_REPEAT = 0,
     SCAN_LINEAR,
     SCAN_RANDOM,
     SCAN_BREAK
   };
Constructor & Destructor Documentation
CScanProblem::CScanProblem (const CCopasiContainer * pParent = NULL)
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
CScanProblem class. Default constructor.
Parameters
CModel * pModel
Definition at line 31 of file CScanProblem.cpp.
References initializeParameter().
                                                           :
   CCopasiProblem(CCopasiTask::scan, pParent),
   mpScanItems(NULL)
 {
   initializeParameter();
 }
CScanProblem::CScanProblem (const CScanProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CTrajectoryProblem & src CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CScanProblem & src
Definition at line 42 of file CScanProblem.cpp.
References initializeParameter().
                                                             :
   CCopasiProblem(src, pParent),
   mpScanItems(NULL)
 {
   initializeParameter();
 }
CScanProblem::~CScanProblem ()
Destructor.
Definition at line 53 of file CScanProblem.cpp.
 {}
Member Function Documentation
CCopasiParameterGroup * CScanProblem::addScanItem (CScanProblem::Type type, size_t steps = 5, const CCopasiObject * obj = NULL)
Definition at line 135 of file CScanProblem.cpp.
References CCopasiParameterGroup::addParameter(), createScanItem(), and mpScanItems.
Referenced by SEDMLImporter::importTasks(), and ScanWidget::saveTask().
 {
   CCopasiParameterGroup * pItem = createScanItem(type, steps, obj);
   mpScanItems->addParameter(pItem);
   return pItem;
 }
void CScanProblem::clearScanItems ()
Definition at line 184 of file CScanProblem.cpp.
References CCopasiParameterGroup::clear(), and mpScanItems.
 {
   mpScanItems->clear();
 }
CCopasiParameterGroup * CScanProblem::createScanItem (CScanProblem::Type type, size_t steps = 5, const CCopasiObject * obj = NULL) static
Definition at line 149 of file CScanProblem.cpp.
References CCopasiParameterGroup::addParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameterGroup::CCopasiParameterGroup(), CCopasiParameter::CN, CCopasiParameter::DOUBLE, CCopasiObject::getCN(), SCAN_BREAK, SCAN_LINEAR, SCAN_RANDOM, and CCopasiParameter::UINT.
Referenced by addScanItem(), and ScanWidget::slotAddItem().
 {
   CCopasiParameterGroup * tmp = new CCopasiParameterGroup("ScanItem");
   //create common parameters
   tmp->addParameter("Number of steps", CCopasiParameter::UINT, (unsigned C_INT32) steps);
   tmp->addParameter("Type", CCopasiParameter::UINT, (unsigned C_INT32) type);
   if (obj)
     tmp->addParameter("Object", CCopasiParameter::CN, obj->getCN());
   else
     tmp->addParameter("Object", CCopasiParameter::CN, CCopasiObjectName(""));
   //create specific parameters
   if ((type == SCAN_LINEAR) || (type == SCAN_RANDOM))
     {
       tmp->addParameter("Minimum", CCopasiParameter::DOUBLE, (C_FLOAT64) 0.0);
       tmp->addParameter("Maximum", CCopasiParameter::DOUBLE, (C_FLOAT64) 1.0);
       tmp->addParameter("log", CCopasiParameter::BOOL, false);
     }
   if (type == SCAN_RANDOM)
     {
       tmp->addParameter("Distribution type", CCopasiParameter::UINT, (unsigned C_INT32)0);
     }
   if (type == SCAN_BREAK)
     {
       tmp->addParameter("Report break", CCopasiParameter::UINT, (unsigned C_INT32)0);
       tmp->addParameter("Plot break", CCopasiParameter::UINT, (unsigned C_INT32)0);
     }
   return tmp;
 }
void CScanProblem::fixBuild81 ()
Fix files written with Version 4.12.81 and earlier, which wrote the exp(mean) and exp(std. deviation) for normal random distributions in the scan task.
Definition at line 189 of file CScanProblem.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), CCopasiParameter::GROUP, mpScanItems, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pUINT, SCAN_RANDOM, and CCopasiParameter::setValue().
Referenced by CScanTask::fixBuild81().
 {
   CCopasiParameterGroup::index_iterator it = mpScanItems->beginIndex();
   CCopasiParameterGroup::index_iterator end = mpScanItems->endIndex();
   for (; it != end; ++it)
     {
       if ((*it)->getType() != CCopasiParameter::GROUP)
         {
           continue;
         }
       CCopasiParameterGroup * pGroup = static_cast< CCopasiParameterGroup * >(*it);
       CCopasiParameter * pParam = pGroup->getParameter("Type");
       if (pParam == NULL || * (Type *) pParam->getValue().pUINT != SCAN_RANDOM)
         {
           continue;
         }
       // Check whether distribution type is set and not uniform
       pParam = pGroup->getParameter("Distribution type");
       if (pParam == NULL || * (Type *) pParam->getValue().pUINT == 0)
         {
           continue;
         }
       // Check whether log is set and true
       pParam = pGroup->getParameter("log");
       if (pParam == NULL || * pParam->getValue().pBOOL == false)
         {
           continue;
         }
       // We need to fix min and max
       pParam = pGroup->getParameter("Minimum");
       if (pParam != NULL)
         {
           pParam->setValue(log(*pParam->getValue().pDOUBLE));
         }
       pParam = pGroup->getParameter("Maximum");
       if (pParam != NULL)
         {
           pParam->setValue(log(*pParam->getValue().pDOUBLE));
         }
     }
   return;
 }
bool CScanProblem::getContinueFromCurrentState () const
Retrieve whether the subtask should continue with its last result.
Definition at line 94 of file CScanProblem.cpp.
References CCopasiParameter::getValue(), and CCopasiParameter::Value::pBOOL.
Referenced by CSEDMLExporter::createScanTask(), CScanMethod::init(), CScanTask::initSubtask(), CScanMethod::isValidProblem(), CScanWidgetTask::load(), and CScanWidgetTask::save().
 {return * getValue("Adjust initial conditions").pBOOL;}
size_t CScanProblem::getNumberOfScanItems () const
Definition at line 103 of file CScanProblem.cpp.
References mpScanItems, and CCopasiParameterGroup::size().
Referenced by CSEDMLExporter::createScanTask(), CScanMethod::init(), CScanMethod::isValidProblem(), ScanWidget::loadTask(), and ScanWidget::saveTask().
 {
   return mpScanItems->size();
 }
const bool & CScanProblem::getOutputInSubtask () const
Ask if output should be done after every step of the subtask.
Definition at line 84 of file CScanProblem.cpp.
References CCopasiParameter::getValue(), and CCopasiParameter::Value::pBOOL.
Referenced by CScanWidgetTask::load(), and CScanWidgetTask::save().
 {return * getValue("Output in subtask").pBOOL;}
const CCopasiParameterGroup * CScanProblem::getScanItem (size_t index) const
Definition at line 108 of file CScanProblem.cpp.
References CCopasiParameterGroup::getParameter(), CCopasiParameter::getType(), CCopasiParameter::GROUP, and mpScanItems.
Referenced by CSEDMLExporter::createScanTask(), CScanMethod::init(), CScanMethod::isValidProblem(), ScanWidget::loadTask(), and ScanWidget::saveTask().
 {
   CCopasiParameter* tmp = mpScanItems->getParameter(index);
   if (tmp->getType() != CCopasiParameter::GROUP)
     {
       // ERROR: not a parameter group!!!
       return NULL;
     }
   return (CCopasiParameterGroup*)tmp;
 }
CCopasiParameterGroup * CScanProblem::getScanItem (size_t index)
Definition at line 121 of file CScanProblem.cpp.
References CCopasiParameterGroup::getParameter(), CCopasiParameter::getType(), CCopasiParameter::GROUP, and mpScanItems.
 {
   CCopasiParameter* tmp = mpScanItems->getParameter(index);
   if (tmp->getType() != CCopasiParameter::GROUP)
     {
       // ERROR: not a parameter group!!!
       return NULL;
     }
   return (CCopasiParameterGroup*)tmp;
 }
CCopasiTask::Type CScanProblem::getSubtask () const
Get the type of the subtask.
Definition at line 74 of file CScanProblem.cpp.
References CCopasiParameter::getValue(), and CCopasiParameter::Value::pUINT.
Referenced by COutputAssistant::createPlot(), CSEDMLExporter::createScanTask(), CScanWidgetTask::load(), and CScanWidgetTask::save().
 {return *(CCopasiTask::Type *) getValue("Subtask").pUINT;}
void CScanProblem::initializeParameter () private
Initialize the method parameter
Definition at line 56 of file CScanProblem.cpp.
References CCopasiParameterGroup::addGroup(), CCopasiParameterGroup::addParameter(), CCopasiParameter::BOOL, C_INT32, CCopasiParameterGroup::getParameter(), mpScanItems, CCopasiTask::timeCourse, and CCopasiParameter::UINT.
Referenced by CScanProblem().
 {
   addParameter("Subtask", CCopasiParameter::UINT, (unsigned C_INT32) CCopasiTask::timeCourse);
   addGroup("ScanItems");
   mpScanItems = dynamic_cast<CCopasiParameterGroup*>(getParameter("ScanItems"));
   addParameter("Output in subtask", CCopasiParameter::BOOL, true);
   addParameter("Adjust initial conditions", CCopasiParameter::BOOL, false);
 }
void CScanProblem::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::NEXT)
Load a scan problem
Parameters
CReadConfig & configBuffer
"CReadConfig::Mode mode (Default: CReadConfig::NEXT)
Definition at line 99 of file CScanProblem.cpp.
 {}
bool CScanProblem::removeScanItem (const size_t & index)
Definition at line 143 of file CScanProblem.cpp.
References mpScanItems, and CCopasiParameterGroup::removeParameter().
Referenced by ScanWidget::saveTask().
 {
   return mpScanItems->removeParameter(index);
 }
void CScanProblem::setContinueFromCurrentState (bool aic)
Set whether the subtask should continue with its last result.
Definition at line 89 of file CScanProblem.cpp.
References CCopasiParameterGroup::setValue().
Referenced by SEDMLImporter::importTasks(), and CScanWidgetTask::save().
 {
   setValue("Adjust initial conditions", aic);
 }
void CScanProblem::setOutputInSubtask (bool ois)
Set if output should be done after every step of the subtask.
Definition at line 79 of file CScanProblem.cpp.
References CCopasiParameterGroup::setValue().
Referenced by SEDMLImporter::importTasks(), and CScanWidgetTask::save().
 {
   setValue("Output in subtask", ois);
 }
void CScanProblem::setSubtask (CCopasiTask::Type type)
Set the type of the subtask.
Definition at line 69 of file CScanProblem.cpp.
References C_INT32, and CCopasiParameterGroup::setValue().
Referenced by SEDMLImporter::importTasks(), and CScanWidgetTask::save().
 {
   setValue("Subtask", (unsigned C_INT32)type);
 }
Member Data Documentation
CCopasiParameterGroup* CScanProblem::mpScanItems private
This holds the scan items
Definition at line 46 of file CScanProblem.h.
Referenced by addScanItem(), clearScanItems(), fixBuild81(), getNumberOfScanItems(), getScanItem(), initializeParameter(), and removeScanItem().
The documentation for this class was generated from the following files:
CScanProblem.h
CScanProblem.cpp