COPASI API: CModification Class Reference
CModification Class Reference
#include <CModified.h>
Public Member Functions
CModification (const std::string &objectName, const CCopasiContainer *pParent=NULL)
CModification (const CRDFTriplet &triplet, const std::string &objectName="", const CCopasiContainer *pParent=NULL)
CModification (const CModification &src, const CCopasiContainer *pParent=NULL)
const std::string & getDate () const
virtual const std::string & getKey () const
const CRDFTriplet & getTriplet () const
void setDate (const std::string &date)
~CModification ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
std::string mKey
CRDFPredicate::Path mNodePath
CRDFTriplet mTriplet
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CModified: Stores Modification dates.
Definition at line 31 of file CModified.h.
Constructor & Destructor Documentation
CModification::CModification (const std::string & objectName, const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & objectName
const CCopasiContainer * pParent (default: NULL)
Definition at line 26 of file CModified.cpp.
                                                               :
     CCopasiContainer(objectName, pParent, "Modification"),
     mTriplet(),
     mNodePath(),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Modification", this))
 {}
CModification::CModification (const CRDFTriplet & triplet, const std::string & objectName = "", const CCopasiContainer * pParent = NULL)
Specific constructor
Parameters
const CRDFTriplet & triplet
const std::string & objectName (default: "")
const CCopasiContainer * pParent (default: NULL)
Definition at line 34 of file CModified.cpp.
References CRDFNode::getPath(), mNodePath, mTriplet, and CRDFTriplet::pObject.
                                                               :
     CCopasiContainer(objectName, pParent, "Modification"),
     mTriplet(triplet),
     mNodePath(),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Modification", this))
 {
   if (!mTriplet)
     return;
   mNodePath = mTriplet.pObject->getPath();
 }
CModification::CModification (const CModification & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CModification & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 48 of file CModified.cpp.
                                                               :
     CCopasiContainer(src, pParent),
     mTriplet(src.mTriplet),
     mNodePath(src.mNodePath),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Modification", this))
 {}
CModification::~CModification ()
Destructor
Definition at line 56 of file CModified.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
const std::string & CModification::getDate () const
Definition at line 70 of file CModified.cpp.
References CRDFPredicate::dcterms_W3CDTF, CRDFNode::getFieldValue(), mTriplet, and CRDFTriplet::pObject.
Referenced by test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000092::test_miriam_import_1(), and CSBMLExporter::updateMIRIAMAnnotation().
   {return mTriplet.pObject->getFieldValue(CRDFPredicate::dcterms_W3CDTF);}
const std::string & CModification::getKey () const virtual
Reimplemented from CCopasiObject.
Definition at line 64 of file CModified.cpp.
References mKey.
   {return mKey;}
const CRDFTriplet & CModification::getTriplet () const
Definition at line 61 of file CModified.cpp.
References mTriplet.
Referenced by CMIRIAMInfo::removeModification().
   {return mTriplet;}
void CModification::setDate (const std::string & date)
Definition at line 67 of file CModified.cpp.
References CRDFPredicate::dcterms_W3CDTF, mNodePath, mTriplet, CRDFTriplet::pObject, and CRDFNode::setFieldValue().
Referenced by CMIRIAMInfo::createModification().
 {mTriplet.pObject->setFieldValue(date, CRDFPredicate::dcterms_W3CDTF, mNodePath);}
Member Data Documentation
std::string CModification::mKey private
The key of the object needed for the copasi tables.
Definition at line 48 of file CModified.h.
Referenced by getKey(), and ~CModification().
CRDFPredicate::Path CModification::mNodePath private
The predicate path to the node.
Definition at line 43 of file CModified.h.
Referenced by CModification(), and setDate().
CRDFTriplet CModification::mTriplet private
Triplet in the RDF graph representing the reference.
Definition at line 38 of file CModified.h.
Referenced by CModification(), getDate(), getTriplet(), and setDate().
The documentation for this class was generated from the following files:
CModified.h
CModified.cpp