COPASI API: CRDFNode Class Reference
CRDFNode Class Reference
#include <CRDFNode.h>
Public Member Functions
CRDFTriplet addEdge (const CRDFPredicate &predicate, CRDFNode *pObject)
bool addTripletToGraph (const CRDFTriplet &triplet) const
CRDFNode (CRDFGraph &graph)
std::set< CRDFTriplet > getDescendantsWithPredicate (const CRDFPredicate &predicate) const
const std::string & getFieldValue (const CRDFPredicate::ePredicateType &predicate) const
const std::string & getId () const
CRDFObject & getObject ()
const CRDFObject & getObject () const
CRDFPredicate::Path getPath () const
const CRDFSubject & getSubject () const
bool hasAncestor (const CRDFNode *pNode) const
bool isBagNode () const
bool isBlankNode () const
bool isObjectNode () const
bool isReadOnly () const
bool isSubjectNode () const
void removeEdge (const CRDFPredicate &predicate, CRDFNode *pObject)
void removeTripletFromGraph (const CRDFTriplet &triplet) const
bool setFieldValue (const CMIRIAMResourceObject &value, const CRDFPredicate::ePredicateType &predicate, const CRDFPredicate::Path &nodePath)
bool setFieldValue (const std::string &value, const CRDFPredicate::ePredicateType &predicate, const CRDFPredicate::Path &nodePath)
void setId (const std::string &id)
void setObject (const CRDFObject &object)
void setSubject (const CRDFSubject &subject)
~CRDFNode ()
Private Member Functions
CRDFNode ()
CRDFNode (const CRDFNode &CRDFNode)
CRDFNode * createMissingAncestors (const CRDFPredicate::Path &nodePath, const CRDFPredicate::ePredicateType &predicate, CRDFPredicate::sAllowedLocation const *&pLocation)
CRDFNode * createMissingAncestors (const CRDFPredicate::Path &predicatePath, const size_t &level)
CRDFNode & operator= (const CRDFNode &rhs)
Private Attributes
CRDFGraph & mGraph
std::string mId
bool mIsBlankNode
CRDFObject * mpObject
CRDFSubject * mpSubject
Detailed Description
Definition at line 38 of file CRDFNode.h.
Constructor & Destructor Documentation
CRDFNode::CRDFNode () private
Default Constructor
CRDFNode::CRDFNode (const CRDFNode & CRDFNode) private
CRDFNode::CRDFNode (CRDFGraph & graph)
Specific Constructor
Parameters
CRDFGraph & graph
Definition at line 32 of file CRDFNode.cpp.
                                    :
     mGraph(graph),
     mId(""),
     mpSubject(NULL),
     mpObject(NULL),
     mIsBlankNode(false)
 {}
CRDFNode::~CRDFNode ()
Destructor
Definition at line 40 of file CRDFNode.cpp.
References mpObject, mpSubject, and pdelete.
 {
   pdelete(mpSubject);
   pdelete(mpObject);
 }
Member Function Documentation
CRDFTriplet CRDFNode::addEdge (const CRDFPredicate & predicate, CRDFNode * pObject)
Add a property edge to the node.
Parameters
const CRDFPredicate & edge
CRDFNode * pObject
Returns
CRDFTriplet triplet
Definition at line 321 of file CRDFNode.cpp.
References CRDFGraph::addTriplet(), addTripletToGraph(), CRDFGraph::getTriplets(), isBagNode(), mGraph, CRDFPredicate::rdf_li, CRDFPredicate::rdf_type, CRDFObject::RESOURCE, CRDFObject::setResource(), and CRDFObject::setType().
Referenced by CRDFGraphConverter::convert(), CRDFGraph::moveTriplet(), and CBiologicalDescription::setPredicate().
 {
   CRDFTriplet Failed;
   CRDFTriplet Triplet(this, predicate, pObject);
   // We do not want any duplicate triplets;
   if (mGraph.getTriplets().count(Triplet) > 0)
     return Failed;
   // If this is a bag node the only predicate allowed is rdf_li.
   if (isBagNode() && predicate != CRDFPredicate::rdf_li)
     return Failed;
   // If the predicate is rdf:li and this is not a bag node we bagify it.
   if (!isBagNode() && predicate == CRDFPredicate::rdf_li)
     {
       // Bagify the node.
       CRDFObject Object;
       Object.setType(CRDFObject::RESOURCE);
       Object.setResource("http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag", false);
       if (!mGraph.addTriplet(this->getSubject(), CRDFPredicate(CRDFPredicate::rdf_type), Object))
         return Failed;
     }
   // We now can safely insert any edge with the predicate rdf_li
   if (predicate == CRDFPredicate::rdf_li)
     {
       if (!addTripletToGraph(Triplet))
         return Failed;
       return Triplet;
     }
   if (!addTripletToGraph(Triplet))
     return Failed;
   return Triplet;
 }
bool CRDFNode::addTripletToGraph (const CRDFTriplet & triplet) const
This method is for internal use only. The method is declared public since friend declarations may not refer to public methods.
Parameters
const CRDFTriplet & triplet
Returns
bool success.
Definition at line 678 of file CRDFGraph.cpp.
References CRDFGraph::addTriplet(), and mGraph.
Referenced by addEdge().
 {
   return mGraph.addTriplet(triplet);
 }
CRDFNode * CRDFNode::createMissingAncestors (const CRDFPredicate::Path & nodePath, const CRDFPredicate::ePredicateType & predicate, CRDFPredicate::sAllowedLocation const *& pLocation) private
Definition at line 246 of file CRDFNode.cpp.
References C_INVALID_INDEX, CRDFPredicate::getAllowedLocationList(), CRDFPredicate::getSubPathIndex(), and isSubjectNode().
Referenced by setFieldValue().
 {
   pLocation = NULL;
   // If this is not a subject node we are not able to do anything.
   if (!isSubjectNode()) return NULL;
   // Determine the path leading to the field
   const CRDFPredicate::AllowedLocationList & Locations = CRDFPredicate::getAllowedLocationList(predicate);
   size_t i, imax = Locations.size();
   size_t SubPathIndex = C_INVALID_INDEX;
   for (i = 0; i < imax; i++)
     {
       // We ignore read only locations.
       if (Locations[i].ReadOnly)
         continue;
       SubPathIndex = CRDFPredicate::getSubPathIndex(Locations[i].Location, nodePath);
       if (SubPathIndex != C_INVALID_INDEX)
         break;
     }
   // The value can not be inserted
   if (SubPathIndex == C_INVALID_INDEX)
     return NULL;
   // Now we build each missing ancestor as a blank node.
   CRDFNode * pParent = createMissingAncestors(Locations[i].Location, SubPathIndex);
   if (pParent != NULL)
     pLocation = &Locations[i];
   return pParent;
 }
CRDFNode * CRDFNode::createMissingAncestors (const CRDFPredicate::Path & predicatePath, const size_t & level) private
Definition at line 285 of file CRDFNode.cpp.
References CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, CRDFGraph::generatedNodeId(), getDescendantsWithPredicate(), getSubject(), CRDFPredicate::getURI(), mGraph, CRDFTriplet::pObject, and CRDFObject::setType().
 {
   CRDFNode * pNode = this;
   size_t i, imax = predicatePath.size() - 1; // We only create the ancestors
   for (i = level; i < imax; i++)
     {
       std::set< CRDFTriplet > Triplets =
         getDescendantsWithPredicate(predicatePath[i]);
       // Check whether the predicate exists.
       if (Triplets.size() > 0)
         {
           pNode = Triplets.begin()->pObject;
         }
       else
         {
           CRDFObject object;
           object.setType(CRDFObject::BLANK_NODE);
           object.setBlankNodeId(mGraph.generatedNodeId());
           CRDFTriplet Triplet =
             mGraph.addTriplet(pNode->getSubject(), CRDFPredicate::getURI(predicatePath[i]), object);
           if (!Triplet)
             return NULL;
           else
             pNode = Triplet.pObject;
         }
     }
   return pNode;
 }
std::set< CRDFTriplet > CRDFNode::getDescendantsWithPredicate (const CRDFPredicate & predicate) const
Definition at line 398 of file CRDFNode.cpp.
References CRDFGraph::getPredicatePath(), CRDFGraph::getTriplets(), and mGraph.
Referenced by CRDFGraphConverter::convert(), createMissingAncestors(), CReference::CReference(), getFieldValue(), CMIRIAMInfo::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), CMIRIAMInfo::loadModifications(), CMIRIAMInfo::loadReferences(), setFieldValue(), CReference::setId(), CReference::setResource(), and CSBMLExporter::updateMIRIAMAnnotation().
 {
   std::set< CRDFTriplet > Triplets;
   CRDFPredicate::Path NodePath = mGraph.getPredicatePath(this);
   std::set< CRDFTriplet > Predicates = mGraph.getTriplets(predicate);
   std::set< CRDFTriplet >::const_iterator it = Predicates.begin();
   std::set< CRDFTriplet >::const_iterator end = Predicates.end();
   for (; it != end; ++it)
     if (it->pObject->hasAncestor(this))
       Triplets.insert(*it);
   return Triplets;
 }
const std::string & CRDFNode::getFieldValue (const CRDFPredicate::ePredicateType & predicate) const
Retrieve the string representation of the property predicate
Parameters
const CRDFPredicate::ePredicateType & predicate
Returns
const std::string & fieldValue
Definition at line 113 of file CRDFNode.cpp.
References CRDFObject::BLANK_NODE, CRDFObject::getBlankNodeID(), getDescendantsWithPredicate(), CRDFLiteral::getLexicalData(), CRDFObject::getLiteral(), CRDFObject::getResource(), CRDFObject::getType(), CRDFObject::LITERAL, and CRDFObject::RESOURCE.
Referenced by CMIRIAMInfo::getCreatedDT(), CModification::getDate(), CReference::getDescription(), CCreator::getEmail(), CCreator::getFamilyName(), CCreator::getGivenName(), and CCreator::getORG().
 {
   static std::string Empty = "";
   const std::set< CRDFTriplet > Triplets = getDescendantsWithPredicate(predicate);
   if (Triplets.size() > 0)
     {
       const CRDFObject & Object = Triplets.begin()->pObject->getObject();
       switch (Object.getType())
         {
           case CRDFObject::LITERAL:
             return Object.getLiteral().getLexicalData();
             break;
           case CRDFObject::RESOURCE:
             return Object.getResource();
             break;
           case CRDFObject::BLANK_NODE:
             return Object.getBlankNodeID();
             break;
         }
     }
   return Empty;
 }
const std::string & CRDFNode::getId () const
Retrieve the Id of the node
Returns
const std::string & id
Definition at line 49 of file CRDFNode.cpp.
References mId.
 {return mId;}
CRDFObject & CRDFNode::getObject ()
Retrieve the object data of the node. It is recommended to call isObjectNode before retrieving the object.
Returns
CRDFObject & object
Definition at line 94 of file CRDFNode.cpp.
References mpObject.
Referenced by CMIRIAMResourceObject::CMIRIAMResourceObject(), CRDFGraph::destroyUnreferencedNode(), operator<<(), setFieldValue(), CBiologicalDescription::setId(), CReference::setId(), CMIRIAMResourceObject::setNode(), CBiologicalDescription::setResource(), CReference::setResource(), and CQRDFTreeViewItem::setTriplet().
 {
   if (mpObject == NULL)
     mpObject = new CRDFObject;
   return *mpObject;
 }
const CRDFObject & CRDFNode::getObject () const
Retrieve the object data of the node. It is recommended to call isObjectNode before retrieving the object.
Returns
const CRDFObject & object
Definition at line 102 of file CRDFNode.cpp.
References mpObject.
 {
   if (mpObject == NULL)
     mpObject = new CRDFObject;
   return *mpObject;
 }
CRDFPredicate::Path CRDFNode::getPath () const
Retrieve a predicate path to the node.
Returns
CRDFPredicate::Path path
Definition at line 110 of file CRDFNode.cpp.
References CRDFGraph::getPredicatePath(), and mGraph.
Referenced by CCreator::CCreator(), CModification::CModification(), CRDFGraphConverter::convert(), CReference::CReference(), CMIRIAMInfo::load(), CMIRIAMInfo::loadBiologicalDescriptions(), CMIRIAMInfo::loadCreators(), CMIRIAMInfo::loadReferences(), and CMIRIAMInfo::setCreatedDT().
 {return mGraph.getPredicatePath(this);}
const CRDFSubject & CRDFNode::getSubject () const
Retrieve the subject data of the node. It is recommended to call isSubjectNode before retrieving the subject.
Returns
const CRDFSubject & subject
Definition at line 69 of file CRDFNode.cpp.
References mpSubject.
Referenced by CRDFGraphConverter::convert(), CMIRIAMInfo::createBiologicalDescription(), CMIRIAMInfo::createCreator(), createMissingAncestors(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), CRDFGraph::guessGraphRoot(), operator<<(), CMIRIAMInfo::setCreatedDT(), and setFieldValue().
 {
   if (mpSubject == NULL)
     mpSubject = new CRDFSubject;
   return *mpSubject;
 }
bool CRDFNode::hasAncestor (const CRDFNode * pNode) const
Check whether the given node is in the path, i.e., has the given node as an ancestor
Parameters
const CRDFNode * pNode
Returns
bool hasAncestor
Definition at line 442 of file CRDFNode.cpp.
References CRDFGraph::getParentSubjects(), and mGraph.
 {
   // We consider each node to be its own ancestor.
   if (pNode == this)
     return true;
   bool hasAncestor = false;
   std::set< const CRDFNode * > Parents = mGraph.getParentSubjects(this);
   std::set< const CRDFNode * >::const_iterator it = Parents.begin();
   std::set< const CRDFNode * >::const_iterator end = Parents.end();
   for (; it != end && !hasAncestor; ++it)
     hasAncestor = (*it)->hasAncestor(pNode);
   return hasAncestor;
 }
bool CRDFNode::isBagNode () const
Check whether this is a bag node
Returns
isBagNode
Definition at line 423 of file CRDFNode.cpp.
References CRDFGraph::getTriplets(), mGraph, and CRDFPredicate::rdf_type.
Referenced by addEdge(), CRDFGraphConverter::convert(), and CRDFGraph::removeEmptyNodes().
 {
   std::set< CRDFTriplet > Triplets = mGraph.getTriplets(this, CRDFPredicate::rdf_type);
   std::set< CRDFTriplet >::const_iterator it = Triplets.begin();
   std::set< CRDFTriplet >::const_iterator end = Triplets.end();
   for (; it != end; ++it)
     if (Triplets.begin()->pObject->getObject().getResource() == "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag")
       return true;
   return false;
 }
bool CRDFNode::isBlankNode () const
Check whether this is a blank node
Returns
bool isBlankNode
Definition at line 420 of file CRDFNode.cpp.
References mIsBlankNode.
 {return mIsBlankNode;}
bool CRDFNode::isObjectNode () const
Check whether this is a object node
Returns
bool isObjectNode
Definition at line 417 of file CRDFNode.cpp.
References mpObject.
 {return mpObject != NULL;}
bool CRDFNode::isReadOnly () const
Check whether the node is read only
Returns
bool isReadOnly
Definition at line 436 of file CRDFNode.cpp.
References CRDFGraph::getPredicatePath(), CRDFPredicate::isReadOnly(), and mGraph.
 {
   CRDFPredicate::Path NodePath = mGraph.getPredicatePath(this);
   return CRDFPredicate::isReadOnly(NodePath);
 }
bool CRDFNode::isSubjectNode () const
Check whether this is a subject node
Returns
bool isSubjectNode
Definition at line 414 of file CRDFNode.cpp.
References mpSubject.
Referenced by CRDFGraph::addTriplet(), createMissingAncestors(), and CRDFGraph::guessGraphRoot().
 {return mpSubject != NULL;}
CRDFNode& CRDFNode::operator= (const CRDFNode & rhs) private
void CRDFNode::removeEdge (const CRDFPredicate & predicate, CRDFNode * pObject)
Remove a property edge from the node.
Parameters
const CRDFPredicate & edge
CRDFNode * pObject
Returns
bool success
Definition at line 361 of file CRDFNode.cpp.
References CRDFGraph::getTriplets(), mGraph, CRDFPredicate::rdf_li, and removeTripletFromGraph().
Referenced by CBiologicalDescription::clearInvalidEntries(), CRDFGraphConverter::convert(), CRDFGraph::moveTriplet(), CRDFGraph::removeTriplet(), and CBiologicalDescription::setPredicate().
 {
   // Determine whether the predicate points to a bag node
   std::set< CRDFTriplet > Triplets = mGraph.getTriplets(this, predicate);
   // Debugging
   assert(Triplets.size() > 0);
   CRDFNode * pTarget = Triplets.begin()->pObject;
   if (pTarget->isBagNode() && pTarget != pObject)
     {
       pTarget->removeEdge(CRDFPredicate::rdf_li, pObject);
       Triplets = mGraph.getTriplets(pTarget, CRDFPredicate::rdf_li);
       switch (Triplets.size())
         {
           case 0:
             // If pTarget is an empty bag node we remove it.
             // Note, this will destroy pTarget, i.e., no need to unbag
             removeEdge(predicate, pTarget);
             break;
           default:
             // We have more than 1 rdf_li element left.
             break;
         }
       return;
     }
   removeTripletFromGraph(CRDFTriplet(this, predicate, pObject));
   return;
 }
void CRDFNode::removeTripletFromGraph (const CRDFTriplet & triplet) const
This method is for internal use only. The method is declared public since friend declarations may not refer to public methods.
Parameters
const CRDFTriplet & triplet
Definition at line 683 of file CRDFGraph.cpp.
References mGraph, and CRDFGraph::removeTriplet().
Referenced by removeEdge(), and setFieldValue().
 {
   mGraph.removeTriplet(triplet);
 }
bool CRDFNode::setFieldValue (const CMIRIAMResourceObject & value, const CRDFPredicate::ePredicateType & predicate, const CRDFPredicate::Path & nodePath)
Set the field value for the property predicate
Parameters
const CMIRIAMResource & value
const CRDFPredicate::ePredicateType & predicate
const CRDFPredicate::Path & nodePath
Returns
bool success
Definition at line 142 of file CRDFNode.cpp.
References CRDFGraph::addTriplet(), createMissingAncestors(), CMIRIAMResourceObject::getNode(), getSubject(), CMIRIAMResourceObject::getURI(), CRDFPredicate::getURI(), CMIRIAMResourceObject::isValid(), mGraph, CRDFObject::RESOURCE, setFieldValue(), and CRDFObject::setType().
Referenced by CReference::clearInvalidEntries(), CMIRIAMInfo::setCreatedDT(), CModification::setDate(), CReference::setDescription(), CCreator::setEmail(), CCreator::setFamilyName(), setFieldValue(), CCreator::setGivenName(), CReference::setId(), CCreator::setORG(), and CReference::setResource().
 {
   // If a node is associated with the resource we can just set the field value
   if (value.getNode() != NULL)
     return value.getNode()->setFieldValue(value.getURI(), predicate, nodePath);
   // We have no node and the value is invalid, i.e., nothing to do.
   if (!value.isValid())
     return true;
   // We need to create a node
   // We build each missing ancestor as a blank node.
   CRDFPredicate::sAllowedLocation const * pLocation = NULL;
   CRDFNode * pParent = createMissingAncestors(nodePath, predicate, pLocation);
   if (pParent == NULL) return false;
   // Create the missing object
   CRDFObject object;
   object.setType(CRDFObject::RESOURCE);
   object.setResource(value.getURI(), false);
   bool success = true;
   if (!mGraph.addTriplet(pParent->getSubject(), CRDFPredicate::getURI(predicate), object))
     success = false;
   return success;
 }
bool CRDFNode::setFieldValue (const std::string & value, const CRDFPredicate::ePredicateType & predicate, const CRDFPredicate::Path & nodePath)
Set the field value for the property predicate
Parameters
const std::string & value
const CRDFPredicate::ePredicateType & predicate
const CRDFPredicate::Path & nodePath
Returns
bool success
Definition at line 175 of file CRDFNode.cpp.
References CRDFGraph::addTriplet(), CRDFObject::BLANK_NODE, createMissingAncestors(), fatalError, CRDFGraph::generatedNodeId(), getDescendantsWithPredicate(), CRDFObject::getLiteral(), getObject(), getSubject(), CRDFObject::getType(), CRDFPredicate::getURI(), CRDFObject::LITERAL, mGraph, CRDFLiteral::PLAIN, CRDFTriplet::pObject, removeTripletFromGraph(), CRDFObject::RESOURCE, CRDFLiteral::setLexicalData(), CRDFObject::setResource(), CRDFLiteral::setType(), CRDFObject::setType(), and CRDFPredicate::sAllowedLocation::Type.
 {
   std::set< CRDFTriplet > Triplets =
     getDescendantsWithPredicate(predicate);
   CRDFNode * pObject = NULL;
   if (Triplets.size() > 0)
     pObject = Triplets.begin()->pObject;
   // Check whether the value is not empty.
   if (value != "")
     {
       // We do not have an object
       if (pObject == NULL)
         {
           // We build each missing ancestor as a blank node.
           CRDFPredicate::sAllowedLocation const * pLocation = NULL;
           CRDFNode * pParent = createMissingAncestors(nodePath, predicate, pLocation);
           if (pParent == NULL) return false;
           // Create the missing object
           CRDFObject object;
           object.setType(pLocation->Type);
           if (object.getType() == CRDFObject::BLANK_NODE)
             object.setBlankNodeId(mGraph.generatedNodeId());
           CRDFTriplet Triplet =
             mGraph.addTriplet(pParent->getSubject(), CRDFPredicate::getURI(predicate), object);
           if (!Triplet)
             return false;
           pObject = Triplet.pObject;
           // Debugging
           assert(pObject != NULL);
         }
       // Now we finally can save the information.
       CRDFObject & Object = pObject->getObject();
       switch (Object.getType())
         {
           case CRDFObject::LITERAL:
           {
             CRDFLiteral & Literal = Object.getLiteral();
             Literal.setType(CRDFLiteral::PLAIN);
             Literal.setLexicalData(value);
           }
           break;
           case CRDFObject::RESOURCE:
             Object.setResource(value, false);
             break;
           case CRDFObject::BLANK_NODE:
             fatalError();
             break;
         }
     }
   else if (pObject != NULL)
     removeTripletFromGraph(*Triplets.begin());
   return true;
 }
void CRDFNode::setId (const std::string & id)
Set the Id of the node
Parameters
const std::string & id
Definition at line 46 of file CRDFNode.cpp.
References mId.
 {mId = id;}
void CRDFNode::setObject (const CRDFObject & object)
Set the object data of the node
Parameters
const CRDFObject & object
Definition at line 77 of file CRDFNode.cpp.
References CRDFSubject::BLANK_NODE, CRDFObject::BLANK_NODE, CRDFObject::getBlankNodeID(), CRDFObject::getType(), mId, mIsBlankNode, mpObject, mpSubject, pdelete, CRDFSubject::setBlankNodeId(), and CRDFSubject::setType().
 {
   pdelete(mpObject);
   mpObject = new CRDFObject(object);
   if (mpObject->getType() == CRDFObject::BLANK_NODE)
     {
       mIsBlankNode = true;
       mId = mpObject->getBlankNodeID();
       pdelete(mpSubject);
       mpSubject = new CRDFSubject;
       mpSubject->setType(CRDFSubject::BLANK_NODE);
       mpSubject->setBlankNodeId(mId);
     }
 }
void CRDFNode::setSubject (const CRDFSubject & subject)
Set the subject data of the node
Parameters
const CRDFSubject & subject
Definition at line 52 of file CRDFNode.cpp.
References CRDFSubject::BLANK_NODE, CRDFObject::BLANK_NODE, CRDFSubject::getBlankNodeID(), CRDFSubject::getType(), mId, mIsBlankNode, mpObject, mpSubject, pdelete, CRDFObject::setBlankNodeId(), and CRDFObject::setType().
Referenced by CRDFGraph::addTriplet(), and CRDFGraph::createAboutNode().
 {
   pdelete(mpSubject);
   mpSubject = new CRDFSubject(subject);
   if (mpSubject->getType() == CRDFSubject::BLANK_NODE)
     {
       mIsBlankNode = true;
       mId = mpSubject->getBlankNodeID();
       pdelete(mpObject);
       mpObject = new CRDFObject;
       mpObject->setType(CRDFObject::BLANK_NODE);
       mpObject->setBlankNodeId(mId);
     }
 }
Member Data Documentation
CRDFGraph& CRDFNode::mGraph private
The graph in which the node is located.
Definition at line 231 of file CRDFNode.h.
Referenced by addEdge(), addTripletToGraph(), createMissingAncestors(), getDescendantsWithPredicate(), getPath(), hasAncestor(), isBagNode(), isReadOnly(), removeEdge(), removeTripletFromGraph(), and setFieldValue().
std::string CRDFNode::mId private
The Id of the node
Definition at line 236 of file CRDFNode.h.
Referenced by getId(), setId(), setObject(), and setSubject().
bool CRDFNode::mIsBlankNode private
Stores whether this is a blank node
Definition at line 251 of file CRDFNode.h.
Referenced by isBlankNode(), setObject(), and setSubject().
CRDFObject* CRDFNode::mpObject mutable private
A pointer to the object if of type OBJECT or BOTH
Definition at line 246 of file CRDFNode.h.
Referenced by getObject(), isObjectNode(), setObject(), setSubject(), and ~CRDFNode().
CRDFSubject* CRDFNode::mpSubject mutable private
A pointer to the subject if of type SUBJECT or BOTH
Definition at line 241 of file CRDFNode.h.
Referenced by getSubject(), isSubjectNode(), setObject(), setSubject(), and ~CRDFNode().
The documentation for this class was generated from the following files:
CRDFNode.h
CRDFGraph.cpp
CRDFNode.cpp