COPASI API: CSSAMethod Class Reference
CSSAMethod Class Reference
#include <CSSAMethod.h>
Public Member Functions
bool calculate ()
CSSAMethod (const CSSAMethod &src, const CCopasiContainer *pParent=NULL)
CSSAMethod (const CCopasiContainer *pParent=NULL)
bool initialize ()
TriLogic isMixingStable (int indexEC)
bool isReactionReversed (int index) const
bool process (CProcessReport *handler)
Public Member Functions inherited from CEFMAlgorithm
void calculateFluxModes ()
CEFMAlgorithm (const CEFMAlgorithm &src, const CCopasiContainer *pParent=NULL)
~CEFMAlgorithm ()
Public Member Functions inherited from CEFMMethod
CEFMMethod (const CEFMMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual ~CEFMMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Member Functions
bool buildExtremeCurrents ()
bool buildJacobian ()
bool buildKineticMatrix ()
bool buildStoichiometry ()
bool decomposeJacobian ()
template<class CType >
CMatrix< CType > diag (CVector< CType > vector)
bool testForMixingStability ()
Protected Member Functions inherited from CEFMAlgorithm
CEFMAlgorithm (const CCopasiContainer *pParent=NULL)
CEFMAlgorithm (const CCopasiMethod::SubType subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CEFMMethod
CEFMMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
std::vector< CVector< C_FLOAT64 > > mExtremeCurrents
std::vector< bool > mIsBackwardReaction
std::vector< TriLogic > mIsMixingStable
C_INT32 mNumReactions
CCopasiVectorNS< CReaction > mReactions
CMatrix< C_FLOAT64 > mStoichiometry
std::vector< std::vector
< C_FLOAT64 > > mStoiRows
std::vector< CMatrix< C_FLOAT64 > > mTransformedSubJacobians
CMatrix< C_FLOAT64 > mTransposedKineticMatrix
Protected Attributes inherited from CEFMAlgorithm
size_t mhSteps
std::vector< size_t > mIndexSet
unsigned C_INT32 mMaxStep
CTableauMatrix * mpCurrentTableau
CModel * mpModel
CTableauMatrix * mpNextTableau
size_t mReversible
unsigned C_INT32 mStep
unsigned C_INT32 mStepProcess
std::vector< std::vector
< C_FLOAT64 > > mStoi
Protected Attributes inherited from CEFMMethod
std::vector< CFluxMode > * mpFluxModes
std::vector< const CReaction * > * mpReorderedReactions
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Friends
CEFMMethod * CEFMMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CEFMMethod
static CEFMMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::EFMAlgorithm)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 28 of file CSSAMethod.h.
Constructor & Destructor Documentation
CSSAMethod::CSSAMethod (const CSSAMethod & src, const CCopasiContainer * pParent = NULL)
CSSAMethod class. Methods to conduct Stoichiometric Stability Analysis.- Copy constructor.
Parameters
const CSSAMethod & src
Definition at line 35 of file CSSAMethod.cpp.
                                                         :
   CEFMAlgorithm(src, pParent)
 {}
CSSAMethod::CSSAMethod (const CCopasiContainer * pParent = NULL)
Definition at line 40 of file CSSAMethod.cpp.
                                                        :
   CEFMAlgorithm(CCopasiMethod::stoichiometricStabilityAnalysis, pParent)
 {}
Member Function Documentation
bool CSSAMethod::buildExtremeCurrents () protected
Definition at line 418 of file CSSAMethod.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, C_INT32, CEFMAlgorithm::calculateFluxModes(), mExtremeCurrents, mNumReactions, CVector< CType >::resize(), and CVectorCore< CType >::size().
Referenced by calculate().
 {
   mExtremeCurrents.clear();
   calculateFluxModes();
   std::vector< CFluxMode > fluxmodes = getFluxModes();
   CVector< C_FLOAT64 > extremecurrent;
   extremecurrent.resize(mNumReactions);
   std::vector< CFluxMode >::iterator iter;
   for (iter = fluxmodes.begin(); iter != fluxmodes.end(); ++iter)
     {
       memset(extremecurrent.array(), 0, extremecurrent.size()*sizeof(C_FLOAT64));
       unsigned C_INT32 i;
       for (i = 0; i < iter->size(); ++i)
         {
           extremecurrent[iter->getReactionIndex(i)] = iter->getMultiplier(i);
         }
     }
   return true;
 }
bool CSSAMethod::buildJacobian () protected
bool CSSAMethod::buildKineticMatrix () protected
Definition at line 379 of file CSSAMethod.cpp.
References CMatrix< CType >::array(), CCopasiVector< T >::begin(), C_FLOAT64, C_INT64, CCopasiVector< T >::end(), CModel::getMetabolitesX(), CModel::getNumIndependentReactionMetabs(), mIsBackwardReaction, mNumReactions, CEFMAlgorithm::mpModel, mTransposedKineticMatrix, CMatrix< CType >::resize(), and CCopasiVector< T >::size().
Referenced by calculate().
 {
   if (!mpModel) return false;
   C_FLOAT64 num_metabolites = mpModel->getNumIndependentReactionMetabs();
   C_FLOAT64 num_reactions = mNumReactions;
   mTransposedKineticMatrix.resize((C_INT64)num_reactions, (C_INT64)num_metabolites);
   memset(mTransposedKineticMatrix.array(), 0, (int)(num_metabolites * num_reactions * sizeof(C_FLOAT64)));
   CCopasiVector< CMetab > & metabOrder = mpModel->getMetabolitesX();
   for (int ireac = 0; ireac < mIsBackwardReaction.size(); ++ireac)
     {
       CCopasiVector< CChemEqElement > substrates;
       if (mIsBackwardReaction[ireac])
         substrates = mReorderedReactions[ireac]->getChemEq().getProducts();
       else
         substrates = mReorderedReactions[ireac]->getChemEq().getSubstrates();
       for (int jsubst = 0; jsubst < substrates.size(); ++jsubst)
         {
           CCopasiVector< CMetab >::iterator found = find(metabOrder.begin(),
               metabOrder.end(),
               substrates[jsubst]->getMetabolite());
           if ((*found)->isDependent()) continue;
           int kmetab = std::distance(metabOrder.begin(), found);
           mTransposedKineticMatrix[ireac][kmetab] = substrates[jsubst]->getMultiplicity();
         }
     }
   return true;
 }
bool CSSAMethod::buildStoichiometry () protected
Definition at line 358 of file CSSAMethod.cpp.
References CMatrix< CType >::array(), C_FLOAT64, CEFMAlgorithm::mpModel, CEFMAlgorithm::mStoi, mStoichiometry, and CMatrix< CType >::resize().
Referenced by calculate().
 {
   if (!mpModel) return false;
   //rebuild the stoichiometric matrix with reversible reactions divided into two.
   // build the _transposed_ of stoichiometry, with expanded reversible reactions
   int numRows = mStoi[0].size();
   int numCols = mStoi.size();
   mStoichiometry.resize(numRows, numCols);
   memset(mStoichiometry.array(), 0, numRows * numCols * sizeof(C_FLOAT64));
   for (int i = 0; i < numRows; ++i)
     for (int j = 0; j < numCols; ++j)
       mStoichiometry(i, j) = mStoi[j][i];
   return true;
 }
bool CSSAMethod::calculate (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback. @ return success;
Reimplemented from CEFMAlgorithm.
Definition at line 152 of file CSSAMethod.cpp.
References buildExtremeCurrents(), buildKineticMatrix(), buildStoichiometry(), CProcessReport::finishItem(), initialize(), CEFMAlgorithm::mhSteps, CCopasiMethod::mpCallBack, CEFMAlgorithm::mpModel, and testForMixingStability().
 {
   if (!initialize())
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhSteps);
       return false;
     }
   if (!mpModel)
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhSteps);
       return false;
     }
   //initialize matrices for calculation;
   //  if (mpModel->compileIfNecessary(NULL))
   //    {
   buildStoichiometry();
   buildKineticMatrix();
   buildExtremeCurrents();
   //}
   //  else
   //    return false;
   if (!testForMixingStability())
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhSteps);
       return false;
     }
   if (mpCallBack)
     mpCallBack->finishItem(mhSteps);
   return true;
 }
bool CSSAMethod::decomposeJacobian () protected
Definition at line 313 of file CSSAMethod.cpp.
References CMatrix< CType >::array(), C_FLOAT64, C_INT, dgemm_(), diag(), mExtremeCurrents, mStoichiometry, mTransformedSubJacobians, mTransposedKineticMatrix, CMatrix< CType >::numCols(), CMatrix< CType >::numRows(), and CMatrix< CType >::resize().
Referenced by testForMixingStability().
 {
   mTransformedSubJacobians.clear();
   // parameters for the double matrix multiplication with dgemm_
   char cN = 'N';                         // don't transpose matrices
   C_INT m = mStoichiometry.numRows();    // the leading dimension of the Stoi.M. and of the resulting M.
   C_INT n = mStoichiometry.numCols();    // the dimensions of matrix diagE, also used as 'k'.
   C_FLOAT64 alpha = 1.;
   C_FLOAT64 beta = 0.;
   CMatrix< C_FLOAT64 > product;
   product.resize(m, m);
   std::vector< CVector<C_FLOAT64> >::iterator iter;
   for (iter = mExtremeCurrents.begin(); iter != mExtremeCurrents.end(); ++iter)
     {
       CMatrix<C_FLOAT64> diagE = diag(*iter);
       // compute N*Ei*kappa^T:
       // As the representation of the matrices in their arrays is in
       // transposed (mathematical) order, we compute kappa*Ei*N^T,
       // which corresponds to
       // (mTransposedKineticMatrix*diagE)*mStoichiometry
       C_FLOAT64 dummy[m * n];
       dgemm_(&cN, &cN,
              &m, &n, &n, &alpha,
              mTransposedKineticMatrix.array(), &m ,
              diagE.array(), &n,
              &beta, dummy, &m);
       dgemm_(&cN, &cN,
              &m, &m, &n, &alpha,
              dummy, &m,
              mStoichiometry.array(), &n,
              &beta, product.array(), &m);
       mTransformedSubJacobians.push_back(product);
     }
   return true;
 }
template<class CType > CMatrix<CType> CSSAMethod::diag (CVector< CType > vector) inline protected
Definition at line 103 of file CSSAMethod.h.
References CMatrix< CType >::array(), CMatrix< CType >::resize(), CVectorCore< CType >::size(), and CMatrix< CType >::size().
Referenced by decomposeJacobian().
     {
       CMatrix<CType> matrix;
       matrix.resize(vector.size(), vector.size());
       memset(matrix.array(), 0, matrix.size()*sizeof(CType));
       for (unsigned int i = 0; i < vector.size(); ++i)
         matrix(i, i) = vector[i];
       return matrix;
     }
bool CSSAMethod::initialize () virtual
Initialize arrays and pointer.
Returns
bool success
Reimplemented from CEFMAlgorithm.
Definition at line 46 of file CSSAMethod.cpp.
References CProcessReport::addItem(), C_INT32, CCopasiVector< T >::cleanup(), CCopasiProblem::getModel(), CCopasiObject::getObjectParent(), CCopasiTask::getProblem(), CModel::getReactions(), CModel::getRedStoi(), CEFMAlgorithm::mhSteps, mIsBackwardReaction, CEFMAlgorithm::mMaxStep, mNumReactions, CCopasiMethod::mpCallBack, CEFMAlgorithm::mpModel, mReactions, CEFMAlgorithm::mReversible, CEFMAlgorithm::mStep, CEFMAlgorithm::mStoi, pTask, and CCopasiParameter::UINT.
Referenced by calculate().
 {
   CEFMTask * pTask = dynamic_cast< CEFMTask *>(getObjectParent());
   if (pTask == NULL) return false;
   mpModel = pTask->getProblem()->getModel();
   if (mpModel == NULL) return false;
   mFluxModes.clear();
   mReactions.cleanup();
   /* ModelStoi is the transpose of the models stoichiometry matrix */
   const CTransposeView< CMatrix< C_FLOAT64 > > ModelStoi(mpModel->getRedStoi());
   unsigned C_INT32 row, numRows = ModelStoi.numRows();
   unsigned C_INT32 col, numCols = ModelStoi.numCols();
   /* Get the reactions from the model */
   /* Note: We have as many reactions as we have rows in ModelStoi */
   CCopasiVectorNS < CReaction > & Reaction = mpModel->getReactions();
   /* Reversible reaction counter */
   mReversible = 0;
   for (row = 0; row < numRows; row++)
     {
       if (Reaction[row]->isReversible())
         mReversible++;
     }
   unsigned C_INT32 numOrigRows = numRows;
   numRows += mReversible;
   mNumReactions = numRows;
   mReversible = 0;
   /* Size the stoichiometry matrix passed to the algorithm */
   mStoi.resize(numRows);
   std::vector< std::vector< C_FLOAT64 > >::iterator it = mStoi.begin();
   std::vector< std::vector< C_FLOAT64 > >::iterator end = mStoi.end();
   for (; it != end; ++it)
     it->resize(numCols);
   /* Vector to keep track of the rearrangements necessary to put the */
   /* reversible reactions to the top of stoichiometry matrix */
   mReorderedReactions.resize(numRows);
   mIsBackwardReaction.resize(numRows);
   unsigned C_INT32 Insert;
   unsigned C_INT32 InsertReversible = 0;
   unsigned C_INT32 InsertIrreversible = numRows - 1;
   /* Build the transpose of the stoichiometry matrix, */
   /* sort reversible reactions to the top, count them */
   /* and keep track of the rearrangement */
   //for (row = 0; row < numOrigRows; row++)
   for (row = 0; row < numOrigRows; row++)
     {
       if (Reaction[row]->isReversible())
         {
           Insert = InsertReversible++;
           mIsBackwardReaction[Insert] = true;
           mReversible++;
         }
       else
         {
           Insert = InsertIrreversible--;
           mIsBackwardReaction[Insert] = false;
         }
       mReorderedReactions[Insert] = Reaction[row];
       for (col = 0; col < numCols; col++)
         {
           mStoi[Insert][col] = ModelStoi(row, col);
           if (Reaction[row]->isReversible())
             mStoi[InsertReversible - 1][col] = - ModelStoi(row, col);
         }
     }
   mStep = 0;
   mMaxStep = numCols;
   if (mpCallBack)
     mhSteps =
       mpCallBack->addItem("Current Step",
                           CCopasiParameter::UINT,
                           & mStep,
                           & mMaxStep);
   return true;
 }
TriLogic CSSAMethod::isMixingStable (int indexEC)
Definition at line 195 of file CSSAMethod.cpp.
References mIsMixingStable.
 {return mIsMixingStable[indexEC];}
bool CSSAMethod::isReactionReversed (int index) const
Definition at line 199 of file CSSAMethod.cpp.
References mIsBackwardReaction.
Referenced by CEFMTask::getFluxModeDescription(), and CEFMTask::getReactionEquation().
 {return mIsBackwardReaction[index];}
bool CSSAMethod::process (CProcessReport * handler)
Definition at line 146 of file CSSAMethod.cpp.
 {
   return false;
 }
bool CSSAMethod::testForMixingStability () protected
Definition at line 203 of file CSSAMethod.cpp.
References C_FLOAT64, C_INT32, decomposeJacobian(), dsyev_(), mExtremeCurrents, mIsMixingStable, CEFMAlgorithm::mStoi, mTransformedSubJacobians, CVectorCore< CType >::size(), TriFalse, TriTrue, and TriUnspecified.
Referenced by calculate().
 {
   decomposeJacobian();
   C_INT32 numECs = mExtremeCurrents.size();
   C_INT32 ijmax = mTransformedSubJacobians[0].numRows();
   mIsMixingStable.clear();
   C_FLOAT64 outarray[ijmax * ijmax];
   memset(outarray, 0, ijmax * ijmax * sizeof(C_FLOAT64));
   for (int ecIndex = 0; ecIndex < numECs; ++ecIndex)
     {
       C_FLOAT64 *inarray = mTransformedSubJacobians[ecIndex].array();
       // add matrix and its extremeCurrent - upper triangle only
       for (int i = 0; i < ijmax; ++i)
         for (int j = i; j < ijmax; ++j)
           outarray[i + j * ijmax] = inarray[i + j * ijmax] + inarray[j + i * ijmax];
       // get the eigenvalues AND eigenvectors:
       // input to dsyev_()
       char jobz = 'V';
       char uplo = 'U';
       C_INT32 n = ijmax;
       C_FLOAT64 *A = outarray;
       C_INT32 lda = ijmax;
       C_INT32 lwork = 64 * ijmax;
       // dsyev_() output
       C_FLOAT64 eigenvalues[ijmax];
       C_FLOAT64 work[lwork];
       C_INT32 info;
       dsyev_(&jobz, &uplo, &n, A, &lda, eigenvalues, work, &lwork, &info);
       if (info)
         return false;  // maybe raise an exception here, to discriminate from the sane case
       CVector<C_FLOAT64> EC = mExtremeCurrents[ecIndex];
       // set the state to 'stable' (1 - stable; 0 - unknown; -1 - not mixing stable)
       TriLogic state = TriTrue;
       int partMetabs[ijmax];
       memset(&partMetabs, 0, ijmax * sizeof(int));
       for (int j = 0; j < EC.size(); ++j)
         {
           if (EC[j])
             {
               // if one reaction's kinetic function is not Mass Action Law,
               //  this method is not valid and we can say nothing definite
               //  about the stability of this EC.
               std::string type = mReorderedReactions[j]->getFunction()->getObjectName();
               if (type.find("Mass action") == std::string::npos &&
                   type.find("Constant flux") == std::string::npos)
                 {
                   state = TriUnspecified;
                   break;
                 }
               for (int i = 0; i < ijmax; ++i)
                 {
                   if (mStoi[j][i])
                     {
                       partMetabs[i] = 1;
                       break;
                     }
                 }
             }
         }
       if (state == TriTrue)
         {
           // eigenvalues are sorted in rising order, and if the last ev is
           //   not positive, we have still to look after zero evs.
           if (eigenvalues[ijmax - 1] > 0)
             state = TriFalse;
           else
             {
               int zeroes = 0;
               for (int i = 0; i < ijmax && state == 1; ++i)
                 {
                   // only count zero eigenvals if the eigenvector contains a reaction
                   //  that is participating in this extreme current.
                   if (eigenvalues[i] == 0)
                     {
                       for (int j = 0; j < ijmax; ++ j)
                         if (partMetabs[j] && outarray[i * ijmax + j])
                           if (++zeroes)
                             break;
                       if (zeroes == 2)
                         state = TriFalse;
                     }
                 }
             }
         }
       mIsMixingStable.push_back(state);
     }
   return true;
 }
Friends And Related Function Documentation
CEFMMethod* CEFMMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
std::vector< CVector<C_FLOAT64> > CSSAMethod::mExtremeCurrents protected
Definition at line 74 of file CSSAMethod.h.
Referenced by buildExtremeCurrents(), decomposeJacobian(), and testForMixingStability().
std::vector< bool > CSSAMethod::mIsBackwardReaction protected
Definition at line 62 of file CSSAMethod.h.
Referenced by buildKineticMatrix(), initialize(), and isReactionReversed().
std::vector< TriLogic > CSSAMethod::mIsMixingStable protected
Definition at line 79 of file CSSAMethod.h.
Referenced by isMixingStable(), and testForMixingStability().
C_INT32 CSSAMethod::mNumReactions protected
Definition at line 65 of file CSSAMethod.h.
Referenced by buildExtremeCurrents(), buildKineticMatrix(), and initialize().
CCopasiVectorNS< CReaction > CSSAMethod::mReactions protected
Definition at line 53 of file CSSAMethod.h.
Referenced by initialize().
CMatrix<C_FLOAT64> CSSAMethod::mStoichiometry protected
Definition at line 56 of file CSSAMethod.h.
Referenced by buildStoichiometry(), and decomposeJacobian().
std::vector< std::vector<C_FLOAT64> > CSSAMethod::mStoiRows protected
Definition at line 59 of file CSSAMethod.h.
std::vector< CMatrix<C_FLOAT64> > CSSAMethod::mTransformedSubJacobians protected
Definition at line 72 of file CSSAMethod.h.
Referenced by decomposeJacobian(), and testForMixingStability().
CMatrix<C_FLOAT64> CSSAMethod::mTransposedKineticMatrix protected
Definition at line 70 of file CSSAMethod.h.
Referenced by buildKineticMatrix(), and decomposeJacobian().
The documentation for this class was generated from the following files:
CSSAMethod.h
CSSAMethod.cpp