COPASI API: CCopasiException Class Reference
CCopasiException Class Reference
#include <CCopasiException.h>
Public Member Functions
CCopasiException (const CCopasiMessage &message)
const CCopasiMessage & getMessage () const
~CCopasiException ()
Private Member Functions
CCopasiException ()
Private Attributes
const CCopasiMessage mMessage
Detailed Description
CCopasiException class. A more elaborate class description.
Definition at line 30 of file CCopasiException.h.
Constructor & Destructor Documentation
CCopasiException::CCopasiException (void) private
Default consructor.
Definition at line 23 of file CCopasiException.cpp.
                                       :
     mMessage()
 {}
CCopasiException::CCopasiException (const CCopasiMessage & message)
Specific consructor. Creates a exception with a message.
Parameters
const CCopasiMessage & message
Definition at line 27 of file CCopasiException.cpp.
                                                                 :
     mMessage(message)
 {}
CCopasiException::~CCopasiException (void)
Destructor.
Definition at line 31 of file CCopasiException.cpp.
 {}
Member Function Documentation
const CCopasiMessage & CCopasiException::getMessage () const
Retrieves the Message associated with the exception
Returns
const CCopasiMessage & message
Definition at line 33 of file CCopasiException.cpp.
References mMessage.
Referenced by Arguments::handleCommandLine(), CModel::load(), main(), CLyapTask::process(), CTrajectoryTask::process(), CTSSATask::process(), CCrossSectionTask::process(), and CReaction::setScalingFactor().
   {return mMessage;}
Member Data Documentation
const CCopasiMessage CCopasiException::mMessage private
Definition at line 57 of file CCopasiException.h.
Referenced by getMessage().
The documentation for this class was generated from the following files:
CCopasiException.h
CCopasiException.cpp