COPASI API: CopasiFileDialog Class Reference
CopasiFileDialog Class Reference
#include <CopasiFileDialog.h>
Static Public Member Functions
static QString getOpenFileName (QWidget *parent=0, const char *name=0, const QString &startWith=QString::null, const QString &filter=QString::null, const QString &caption=QString::null, QString *pSelectedFilter=NULL, QFileDialog::Options options=0)
static QString getSaveFileName (QWidget *parent=0, const char *name=0, const QString &startWith=QString::null, const QString &filter=QString::null, const QString &caption=QString::null, QString *pSelectedFilter=NULL, QFileDialog::Options options=0)
static void openExampleDir ()
Static Private Member Functions
static QString StartWith (const QString &startWith)
Detailed Description
Definition at line 22 of file CopasiFileDialog.h.
Member Function Documentation
QString CopasiFileDialog::getOpenFileName (QWidget * parent = 0, const char * name = 0, const QString & startWith = QString::null, const QString & filter = QString::null, const QString & caption = QString::null, QString * pSelectedFilter = NULL, QFileDialog::Options options = 0) static
Definition at line 63 of file CopasiFileDialog.cpp.
References CDirEntry::dirName(), CCopasiRootContainer::getConfiguration(), CConfigurationFile::setWorkingDirectory(), StartWith(), and TO_UTF8.
Referenced by CQExperimentData::slotFileAdd(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotFunctionDBLoad(), and CopasiUI3Window::slotImportSBML().
 {
   QString newFilter = filter;
   if (filter.indexOf("(*)") < 0)
     newFilter += ";;Any File (*)";
   QString newFile = QFileDialog::getOpenFileName(parent,
                     caption,
                     StartWith(startWith),
                     newFilter,
                     pSelectedFilter,
                     options);
   if (newFile != "")
     CCopasiRootContainer::getConfiguration()->setWorkingDirectory(CDirEntry::dirName(TO_UTF8(newFile)));
   return newFile;
 }
QString CopasiFileDialog::getSaveFileName (QWidget * parent = 0, const char * name = 0, const QString & startWith = QString::null, const QString & filter = QString::null, const QString & caption = QString::null, QString * pSelectedFilter = NULL, QFileDialog::Options options = 0) static
Definition at line 90 of file CopasiFileDialog.cpp.
References CDirEntry::dirName(), CDirEntry::fileName(), FROM_UTF8, CCopasiRootContainer::getConfiguration(), CQMessageBox::information(), CConfigurationFile::setWorkingDirectory(), StartWith(), CDirEntry::suffix(), and TO_UTF8.
Referenced by CQSEDMLFileDialog::getSaveFileName(), CQSBMLFileDialog::getSaveFileName(), PlotWindow::printAsImage(), CQTSSAResultSubWidget::saveDataToFile(), CQBarChart::saveDataToFile(), CQLayoutMainWindow::saveImage(), CQLyapResultWidget::saveToFile(), CQSensResultWidget::saveToFile(), CQReportDefinitionSelect::slotBrowse(), CQParameterOverviewWidget::slotBtnSaveToFile(), CopasiUI3Window::slotCapture(), CopasiUI3Window::slotExportMathModel(), CopasiUI3Window::slotFileSaveAs(), CopasiUI3Window::slotFunctionDBSave(), CQDifferentialEquations::slotSave(), CQSteadyStateResult::slotSave(), CQTimeSeriesWidget::slotSave(), CQMoietiesTaskResult::slotSave(), CMCAResultSubwidget::slotSave(), CLNAResultSubwidget::slotSave(), CQOptimizationResult::slotSave(), CQEFMResultWidget::slotSave(), CQFittingResult::slotSave(), PlotWindow::slotSaveData(), CQExpressionMmlStackedWidget::slotSaveExpression(), and CQNewMainWindow::slotScreenshot().
 {
   QString newFile, newFilter = filter;
   bool fileValid;
   if (!pSelectedFilter)
     pSelectedFilter = new QString("");
   if (filter.indexOf("(*)") < 0)
     newFilter += ";;Any File (*)";
   do
     {
       fileValid = true;
       newFile = QFileDialog::getSaveFileName(parent,
                                              caption,
                                              StartWith(startWith),
                                              newFilter, pSelectedFilter,
                                              QFileDialog::DontConfirmOverwrite | options);
       if (newFile != "")
         CCopasiRootContainer::getConfiguration()->setWorkingDirectory(CDirEntry::dirName(TO_UTF8(newFile)));
       else
         return QString::null;
       if (pSelectedFilter->indexOf("(*)") >= 0)
         {
           QString fileName = FROM_UTF8(CDirEntry::fileName(TO_UTF8(newFile)));
           QString suffix = FROM_UTF8(CDirEntry::suffix(TO_UTF8(newFile)));
           if (!suffix.length())
             {
               fileValid = true;
             }
           else
             {
               QRegExp rx("\\.\\S{1,4}$");
               if (rx.indexIn(fileName) < 0)
                 {
                   CQMessageBox::information(NULL, "Save File Error",
                                             "Filename can have an extension 1 to 4 characters long.",
                                             QMessageBox::Ok, QMessageBox::Ok);
                   fileValid = false;
                   continue;
                 }
               QRegExp rxDigits("\\.\\d{1,4}$");
               if (rxDigits.indexIn(fileName) > 0)
                 {
                   CQMessageBox::information(NULL, "Save File Error",
                                             "All characters in the file extension cannot be digits.",
                                             QMessageBox::Ok, QMessageBox::Ok);
                   fileValid = false;
                   continue;
                 }
             }
         }
     }
   while (fileValid == false);
 #ifdef DEBUG_UI
 //  qDebug() << "user selected Filter = " << usersFilter;
   qDebug() << "user's Filter = " << *pSelectedFilter;
 //  qDebug() << "correct extension = " << correctExt;
 //  qDebug() << "filename = " << newFile;
 #endif
   return newFile;
 }
void CopasiFileDialog::openExampleDir () static
Definition at line 50 of file CopasiFileDialog.cpp.
References FROM_UTF8, CCopasiRootContainer::getConfiguration(), COptions::getValue(), CQMessageBox::information(), CDirEntry::isDir(), and CConfigurationFile::setWorkingDirectory().
Referenced by CopasiUI3Window::slotFileExamplesCopasiFiles(), and CopasiUI3Window::slotFileExamplesSBMLFiles().
 {
   std::string ExampleDir;
   COptions::getValue("ExampleDir", ExampleDir);
   if (CDirEntry::isDir(ExampleDir))
     CCopasiRootContainer::getConfiguration()->setWorkingDirectory(ExampleDir);
   else
     CQMessageBox::information(NULL, "Directory Not Found", FROM_UTF8(ExampleDir),
                               QMessageBox::Ok, QMessageBox::Ok);
 }
QString CopasiFileDialog::StartWith (const QString & startWith) static private
Definition at line 33 of file CopasiFileDialog.cpp.
References CDirEntry::dirName(), FROM_UTF8, CCopasiRootContainer::getConfiguration(), and TO_UTF8.
Referenced by getOpenFileName(), and getSaveFileName().
 {
   QString WorkingDirectory = FROM_UTF8(CCopasiRootContainer::getConfiguration()->getWorkingDirectory());
   if (startWith.isNull())
     {
       return WorkingDirectory;
     }
   else if (CDirEntry::dirName(TO_UTF8(startWith)) == "")
     {
       return WorkingDirectory + "/" + startWith;
     }
   return startWith;
 }
The documentation for this class was generated from the following files:
CopasiFileDialog.h
CopasiFileDialog.cpp