COPASI API: CLayoutInitializer Class Reference
CLayoutInitializer Class Reference
#include <CLayoutInitializer.h>
Static Protected Member Functions
static CLCompartmentGlyph * createCompartmentGlyph (const CCompartment *c)
static CLMetabGlyph * createMetabGlyph (const CMetab *m)
static CLReactionGlyph * createReactionGlyph (const CReaction *r, const std::map< std::string, std::string > &mm)
Detailed Description
This class contains (static) methods that initialize the layout data structure from a copasi model. A proper layout is not generated, this is rather a starting point for the layout algorithms
Definition at line 37 of file CLayoutInitializer.h.
Member Function Documentation
CLCompartmentGlyph * CLayoutInitializer::createCompartmentGlyph (const CCompartment * c) static protected
one layout element is created for every model element. This acts as a pseudo constructor for a CLayout.
Definition at line 69 of file CLayoutInitializer.cpp.
References CModelEntity::getKey(), and CLGraphicalObject::setModelObjectKey().
 {
   if (!c) return NULL;
   CLCompartmentGlyph* cg = new CLCompartmentGlyph();
   cg->setModelObjectKey(c->getKey());
   return cg;
 }
CLMetabGlyph * CLayoutInitializer::createMetabGlyph (const CMetab * m) static protected
Definition at line 79 of file CLayoutInitializer.cpp.
References CModelEntity::getKey(), and CLGraphicalObject::setModelObjectKey().
 {
   if (!m) return NULL;
   CLMetabGlyph* cg = new CLMetabGlyph();
   cg->setModelObjectKey(m->getKey());
   return cg;
 }
CLReactionGlyph * CLayoutInitializer::createReactionGlyph (const CReaction * r, const std::map< std::string, std::string > & mm) static protected
Definition at line 89 of file CLayoutInitializer.cpp.
References CLReactionGlyph::addMetabReferenceGlyph(), CReaction::getChemEq(), CReaction::getKey(), CChemEq::getModifiers(), CChemEq::getProducts(), CChemEq::getSubstrates(), CLMetabReferenceGlyph::MODIFIER, CLMetabReferenceGlyph::PRODUCT, CLMetabReferenceGlyph::setMetabGlyphKey(), CLGraphicalObject::setModelObjectKey(), CLMetabReferenceGlyph::setRole(), CCopasiVector< T >::size(), and CLMetabReferenceGlyph::SUBSTRATE.
 {
   if (!r) return NULL;
   CLReactionGlyph* rg = new CLReactionGlyph();
   rg->setModelObjectKey(r->getKey());
   const CChemEq & ce = r->getChemEq();
   size_t i, imax;
   //substrates
   imax = ce.getSubstrates().size();
   for (i = 0; i < imax; ++i)
     {
       //create metab reference glyph and add to reaction glyph
       CLMetabReferenceGlyph * tmpMRG = new CLMetabReferenceGlyph();
       tmpMRG->setRole(CLMetabReferenceGlyph::SUBSTRATE);
       rg->addMetabReferenceGlyph(tmpMRG);
       //get the metab key from the copasi reaction
       std::string metabKey = ce.getSubstrates()[i]->getMetaboliteKey();
       //set the corresponding metab glyph key
       const std::map<std::string, std::string>::const_iterator it = mm.find(metabKey);
       if (it != mm.end())
         tmpMRG->setMetabGlyphKey(it->second);
     }
   //products
   imax = ce.getProducts().size();
   for (i = 0; i < imax; ++i)
     {
       //create metab reference glyph and add to reaction glyph
       CLMetabReferenceGlyph * tmpMRG = new CLMetabReferenceGlyph();
       tmpMRG->setRole(CLMetabReferenceGlyph::PRODUCT);
       rg->addMetabReferenceGlyph(tmpMRG);
       //get the metab key from the copasi reaction
       std::string metabKey = ce.getProducts()[i]->getMetaboliteKey();
       //set the corresponding metab glyph key
       const std::map<std::string, std::string>::const_iterator it = mm.find(metabKey);
       if (it != mm.end())
         tmpMRG->setMetabGlyphKey(it->second);
     }
   //modifier
   imax = ce.getModifiers().size();
   for (i = 0; i < imax; ++i)
     {
       //create metab reference glyph and add to reaction glyph
       CLMetabReferenceGlyph * tmpMRG = new CLMetabReferenceGlyph();
       tmpMRG->setRole(CLMetabReferenceGlyph::MODIFIER);
       rg->addMetabReferenceGlyph(tmpMRG);
       //get the metab key from the copasi reaction
       std::string metabKey = ce.getModifiers()[i]->getMetaboliteKey();
       //set the corresponding metab glyph key
       const std::map<std::string, std::string>::const_iterator it = mm.find(metabKey);
       if (it != mm.end())
         tmpMRG->setMetabGlyphKey(it->second);
     }
   return rg;
 }
The documentation for this class was generated from the following files:
CLayoutInitializer.h
CLayoutInitializer.cpp