COPASI API: CPraxis.cpp File Reference
CPraxis.cpp File Reference
#include <cmath>
#include <stdio.h>
#include "copasi.h"
#include "CPraxis.h"
#include "randomGenerator/CRandom.h"
Macros
#define dmax(a1, a2) ((a1 > a2) ? a1 : a2)
#define dmin(a1, a2) ((a1 < a2) ? a1 : a2)
#define FALSE_ (0)
#define TRUE_ (1)
Functions
int maprnt_ (C_INT *, C_FLOAT64 *, C_INT *, C_INT *)
int sort_ (C_INT *, C_INT *, C_FLOAT64 *, C_FLOAT64 *)
int vcprnt_ (C_INT *, C_FLOAT64 *, C_INT *)
Variables
static C_INT c__0 = 0
static C_INT c__1 = 1
static C_INT c__2 = 2
static C_INT c__3 = 3
static C_INT c__4 = 4
static bool c_false = (0)
static bool c_true = (1)
Macro Definition Documentation
#define dmax (a1, a2) ((a1 > a2) ? a1 : a2)
Definition at line 45 of file CPraxis.cpp.
Referenced by CPraxis::min_().
#define dmin (a1, a2) ((a1 < a2) ? a1 : a2)
Definition at line 46 of file CPraxis.cpp.
Referenced by CPraxis::min_().
#define FALSE_ (0)
Definition at line 44 of file CPraxis.cpp.
Referenced by CPraxis::praxis_().
#define TRUE_ (1)
Definition at line 43 of file CPraxis.cpp.
Referenced by CPraxis::min_(), and CPraxis::praxis_().
Function Documentation
int maprnt_ (C_INT * , C_FLOAT64 * , C_INT * , C_INT *)
Definition at line 1910 of file CPraxis.cpp.
References C_INT.
Referenced by CPraxis::praxis_().
 {
 #ifdef XXXX
   /* System generated locals */
   C_INT v_dim1, v_offset, i__1, i__2;
   /* Local variables */
   C_INT i, j, low, upp;
   /* ...THE SUBROUTINE MAPRNT PRINTS THE COLUMNS OF THE NXN MATRIX V */
   /*   WITH A HEADING AS SPECIFIED BY OPTION. */
   /*   M IS THE ROW DIMENSION OF V AS DECLARED IN THE CALLING PROGRAM... */
   /* Parameter adjustments */
   v_dim1 = *m;
   v_offset = v_dim1 + 1;
   v -= v_offset;
   /* Function Body */
   low = 1;
   upp = 5;
   switch ((int)*option)
     {
       case 1: goto L1;
       case 2: goto L2;
     }
 L1:
   printf("HE NEW DIRECTIONS ARE:\n");
   goto L3;
 L2:
   printf("AND THE PRINCIPAL AXES:\n");
 L3:
   if (*n < upp)
     {
       upp = *n;
     }
   i__1 = *n;
   for (i = 1; i <= i__1; ++i)
     {
       /* L4: */
       printf("%3d", i);
       i__2 = upp;
       for (j = low; j <= i__2; ++j)
         {
           printf("  %12g", v[i*v_dim1 + j]);
         }
       printf("\n");
     }
   low += 5;
   if (*n < low)
     {
       return 0;
     }
   upp += 5;
   goto L3;
 #endif // XXXX
   return 0;
 } /* maprnt_ */
int sort_ (C_INT * m, C_INT * n, C_FLOAT64 * d__, C_FLOAT64 * v)
Definition at line 1644 of file CPraxis.cpp.
References C_FLOAT64, and C_INT.
Referenced by CPraxis::praxis_().
 {
   /* System generated locals */
   C_INT v_dim1, v_offset, i__1, i__2;
   /* Local variables */
   static C_INT i__, j, k;
   static C_FLOAT64 s;
   static C_INT ip1, nm1;
   /* ...SORTS THE ELEMENTS OF D(N) INTO DESCENDING ORDER AND MOVES THE */
   /*   CORRESPONDING COLUMNS OF V(N,N). */
   /*   M IS THE ROW DIMENSION OF V AS DECLARED IN THE CALLING PROGRAM. */
   /* Parameter adjustments */
   v_dim1 = *m;
   v_offset = v_dim1 + 1;
   v -= v_offset;
   --d__;
   /* Function Body */
   if (*n == 1)
     {
       return 0;
     }
   nm1 = *n - 1;
   i__1 = nm1;
   for (i__ = 1; i__ <= i__1; ++i__)
     {
       k = i__;
       s = d__[i__];
       ip1 = i__ + 1;
       i__2 = *n;
       for (j = ip1; j <= i__2; ++j)
         {
           if (d__[j] <= s)
             {
               goto L1;
             }
           k = j;
           s = d__[j];
 L1:
           ;
         }
       if (k <= i__)
         {
           goto L3;
         }
       d__[k] = d__[i__];
       d__[i__] = s;
       i__2 = *n;
       for (j = 1; j <= i__2; ++j)
         {
           s = v[j + i__ * v_dim1];
           v[j + i__ * v_dim1] = v[j + k * v_dim1];
           /* L2: */
           v[j + k * v_dim1] = s;
         }
 L3:
       ;
     }
   return 0;
 } /* sort_ */
int vcprnt_ (C_INT * option, C_FLOAT64 * v, C_INT * n)
Definition at line 1787 of file CPraxis.cpp.
References C_INT.
Referenced by CPraxis::praxis_().
 {
   /* System generated locals */
   C_INT i__1;
   /* Local variables */
   C_INT i;
   /* Parameter adjustments */
   --v;
   /* Function Body */
   switch ((int)*option)
     {
       case 1: goto L1;
       case 2: goto L2;
       case 3: goto L3;
       case 4: goto L4;
     }
 L1:
   printf("THE SECOND DIFFERENCE ARRAY D[*] IS :\n");
   i__1 = *n;
   for (i = 1; i <= i__1; ++i)
     {
       printf("%g\n", v[i]);
     }
   return 0;
 L2:
   printf("THE SCALE FACTORS ARE:\n");
   i__1 = *n;
   for (i = 1; i <= i__1; ++i)
     {
       printf("%g\n", v[i]);
     }
   return 0;
 L3:
   printf("THE APPROXIMATING QUADRATIC FORM HAS THE PRINCEPAL VALUES:\n");
   i__1 = *n;
   for (i = 1; i <= i__1; ++i)
     {
       printf("%g\n", v[i]);
     }
   return 0;
 L4:
   printf("x is:\n");
   i__1 = *n;
   for (i = 1; i <= i__1; ++i)
     {
       printf("%g\n", v[i]);
     }
   return 0;
 } /* vcprnt_ */
Variable Documentation
C_INT c__0 = 0 static
Definition at line 56 of file CPraxis.cpp.
Referenced by CPraxis::quad_().
C_INT c__1 = 1 static
Definition at line 50 of file CPraxis.cpp.
Referenced by CPraxis::praxis_().
C_INT c__2 = 2 static
Definition at line 51 of file CPraxis.cpp.
Referenced by CPraxis::praxis_(), and CPraxis::quad_().
C_INT c__3 = 3 static
Definition at line 55 of file CPraxis.cpp.
Referenced by CPraxis::praxis_().
C_INT c__4 = 4 static
Definition at line 53 of file CPraxis.cpp.
Referenced by CPraxis::praxis_().
bool c_false = (0) static
Definition at line 52 of file CPraxis.cpp.
Referenced by CPraxis::praxis_().
bool c_true = (1) static
Definition at line 54 of file CPraxis.cpp.
Referenced by CPraxis::praxis_(), and CPraxis::quad_().