COPASI API: CQFluxModeDM Class Reference
CQFluxModeDM Class Reference
#include <CQFluxModeDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQFluxModeDM (QObject *parent=0)
QVariant data (const QModelIndex &index, int role) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool isDefaultRow (const QModelIndex &i) const
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setTask (const CEFMTask *pTask)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
bool removeRow (int position)
Protected Member Functions
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Private Attributes
std::vector< CFluxMode >
::const_iterator mBeginModes
size_t mModesSize
const CEFMTask * mpTask
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 34 of file CQFluxModeDM.h.
Constructor & Destructor Documentation
CQFluxModeDM::CQFluxModeDM (QObject * parent = 0)
Definition at line 25 of file CQFluxModeDM.cpp.
                                          :
     CQBaseDataModel(parent),
     mpTask(NULL),
     mBeginModes(),
     mModesSize(0)
 {}
Member Function Documentation
int CQFluxModeDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 40 of file CQFluxModeDM.cpp.
References FluxModeDM_COLUMNS.
 {
   return FluxModeDM_COLUMNS;
 }
QVariant CQFluxModeDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 53 of file CQFluxModeDM.cpp.
References COL_REACTION_EQUATION, COL_REACTION_NAME, COL_REVERSIBILITY, COL_ROW_NUMBER, FROM_UTF8, CEFMTask::getFluxModeDescription(), CEFMTask::getReactionEquation(), mBeginModes, mpTask, and rowCount().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       std::vector< CFluxMode >::const_iterator itMode = mBeginModes + index.row();
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return QVariant(index.row() + 1);
             break;
           case COL_REVERSIBILITY:
             if (itMode->isReversible() == true)
               {
                 return QVariant(QString("Reversible"));
               }
             else
               {
                 return QVariant(QString("Irreversible"));
               }
             break;
           case COL_REACTION_NAME:
             return QVariant(QString(FROM_UTF8(mpTask->getFluxModeDescription(*itMode))));
             break;
           case COL_REACTION_EQUATION:
           {
             std::string reactionEq = "";
             std::string separator = "";
             CFluxMode::const_iterator itReaction = itMode->begin();
             CFluxMode::const_iterator endReaction = itMode->end();
             for (; itReaction != endReaction; ++itReaction)
               {
                 reactionEq += separator;
                 reactionEq += mpTask->getReactionEquation(itReaction);
                 separator = "\n";
               }
             return QVariant(QString(FROM_UTF8(reactionEq)));
           }
           break;
         }
     }
   return QVariant();
 }
Qt::ItemFlags CQFluxModeDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 45 of file CQFluxModeDM.cpp.
 {
   if (!index.isValid())
     return Qt::ItemIsEnabled;
   return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
 }
QVariant CQFluxModeDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 112 of file CQFluxModeDM.cpp.
References COL_REACTION_EQUATION, COL_REACTION_NAME, COL_REVERSIBILITY, and COL_ROW_NUMBER.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
             break;
           case COL_REVERSIBILITY:
             return QVariant(QString("Reversibility"));
             break;
           case COL_REACTION_NAME:
             return QVariant(QString("Reaction Name"));
             break;
           case COL_REACTION_EQUATION:
             return QVariant(QString("Reaction Equation"));
             break;
           default:
             return QVariant();
             break;
         }
     }
   //Vertical header
   return QString("%1").arg(section + 1);
 }
bool CQFluxModeDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 170 of file CQFluxModeDM.cpp.
 {
   return false;
 }
bool CQFluxModeDM::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 182 of file CQFluxModeDM.cpp.
 {
   return false;
 }
bool CQFluxModeDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 176 of file CQFluxModeDM.cpp.
 {
   return false;
 }
int CQFluxModeDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 32 of file CQFluxModeDM.cpp.
References mModesSize, and mpTask.
Referenced by data().
 {
   if (mpTask == NULL)
     return 0;
   return (int) mModesSize;
 }
bool CQFluxModeDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 163 of file CQFluxModeDM.cpp.
 {
   return false;
 }
void CQFluxModeDM::setTask (const CEFMTask * pTask)
Definition at line 148 of file CQFluxModeDM.cpp.
References CEFMTask::getFluxModes(), mBeginModes, mModesSize, mpTask, and pTask.
Referenced by CQEFMListWidget::loadResult().
 {
   mpTask = pTask;
   if (mpTask != NULL)
     {
       mBeginModes = mpTask->getFluxModes().begin();
       mModesSize = mpTask->getFluxModes().size();
     }
   else
     {
       mModesSize = 0;
     }
 }
Member Data Documentation
std::vector< CFluxMode >::const_iterator CQFluxModeDM::mBeginModes private
Definition at line 60 of file CQFluxModeDM.h.
Referenced by data(), and setTask().
size_t CQFluxModeDM::mModesSize private
Definition at line 61 of file CQFluxModeDM.h.
Referenced by rowCount(), and setTask().
const CEFMTask* CQFluxModeDM::mpTask private
Definition at line 59 of file CQFluxModeDM.h.
Referenced by data(), rowCount(), and setTask().
The documentation for this class was generated from the following files:
CQFluxModeDM.h
CQFluxModeDM.cpp