COPASI API: CODEExporterBM Class Reference
CODEExporterBM Class Reference
#include <CODEExporterBM.h>
Public Member Functions
CODEExporterBM ()
virtual bool exportSingleCompartment (const CCompartment *comp, std::string &expression, std::string &comments)
virtual bool exportSingleMetabolite (const CMetab *metab, std::string &expression, std::string &comments)
virtual bool exportSingleModelEntity (const CModelEntity *tmp, std::string &expression, std::string &comments)
virtual bool exportSingleModVal (const CModelValue *modval, std::string &expression, std::string &comments)
virtual bool exportSingleObject (std::ostringstream &which, const std::string &name, const std::string &expression, const std::string &comments)
virtual bool exportSingleODE (const CModelEntity *mentity, std::string &equation, std::string &comments)
virtual bool exportSingleParameter (const CCopasiParameter *param, std::string &expression, std::string &comments)
virtual bool exportTitleData (const CCopasiDataModel *pDataModel, std::ostream &os)
virtual std::string exportTitleString (const size_t tmp)
virtual std::string getDisplayExpressionString (CExpression *tmp)
virtual std::string getDisplayFunctionString (CFunction *func)
virtual std::string KineticFunction2ODEmember (const CReaction *reac)
std::string setConcentrationName (const std::string &objName)
std::string setODEName (const std::string &objName)
virtual void setReservedNames ()
std::string testName (const std::string &name)
virtual std::string translateObjectName (const std::string &realName)
virtual std::string translateTimeVariableName ()
Public Member Functions inherited from CODEExporter
void assembleSubTreeForMassAction (CEvaluationNode *newNode, CEvaluationNode *child1, CEvaluationNode *child2)
CODEExporter ()
virtual bool exportClosingData (const CModel *copasiModel, std::ostream &os)
virtual std::string exportClosingString (const size_t tmp)
bool exportCompartments (const CModel *copasiModel)
std::string exportExpression (const CExpression *pExpression, const CCopasiDataModel *pDataModel)
virtual bool exportKineticFunction (CReaction *reac)
virtual bool exportKineticFunctionGroup (const CModel *copasiModel)
virtual bool exportMetabolites (const CModel *copasiModel)
virtual bool exportMetabolitesConcentrations (const CModel *copasiModel)
bool exportModelEntityExpression (CCopasiObject *obj, const CCopasiDataModel *pDataModel)
bool exportModelValues (const CModel *copasiModel)
bool exportModelValuesExpressions (const CModel *copasiModel)
virtual std::string exportNumber (double number)
void exportObjectNodesFromModel (const CCopasiDataModel *pDataModel)
bool exportODEs (const CModel *copasiModel)
bool exportReacParamsAndFuncs (const CModel *copasiModel)
void exportSimulatedObject (CCopasiObject *obj, const CCopasiDataModel *pDataModel)
bool exportSingleFunction (const CFunction *func)
virtual bool exportSingleFunction (const CFunction *func, std::set< std::string > &isExported)
bool exportSingleFunction (CEvaluationNode *pNode, const CReaction *reac, size_t &index)
bool exportSingleFunction (CEvaluationNode *pNode, const std::string &key, size_t &index)
virtual bool exportTitleData (const CModel *copasiModel, std::ostream &os)
bool exportToStream (const CCopasiDataModel *pDataModel, std::ostream &os)
void findFunctionsCalls (const CEvaluationNode *pNode)
CCopasiObject * findObjectFromRefresh (const CCopasiObject *tmp, const Refresh *ref)
virtual std::string getSingleLineComment ()
virtual bool isEmptyString (std::string &str)
std::string isModelEntityExpressionODEExporterCompatible (CModelEntity *tmp, const CExpression *pExpression, const CCopasiDataModel *pDataModel)
void modifyTreeForMassAction (CFunction *tmpfunc)
virtual bool preprocess (const CModel *copasiModel)
virtual ~CODEExporter ()
Public Attributes
std::map< std::string, size_t > Frequancy
std::set< std::string > NameSet
Public Attributes inherited from CODEExporter
std::ostringstream assignment
std::map< std::string,
std::string > equations
std::ostringstream fixed
std::ostringstream functions
std::ostringstream headers
std::ostringstream initial
std::map< std::string,
std::string > NameMap
std::ostringstream ode
std::string timeKey
Additional Inherited Members
Public Types inherited from CODEExporter
enum Object {
INITIAL = 0, FIXED, ASSIGNMENT, HEADERS,
FUNCTIONS, ODEs
}
Protected Attributes inherited from CODEExporter
std::set< std::string > mExportedFunctions
Detailed Description
Definition at line 20 of file CODEExporterBM.h.
Constructor & Destructor Documentation
CODEExporterBM::CODEExporterBM ()
Constructor for the exporter.
Definition at line 54 of file CODEExporterBM.cpp.
 {}
Member Function Documentation
bool CODEExporterBM::exportSingleCompartment (const CCompartment * comp, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 279 of file CODEExporterBM.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CODEExporter::NameMap, and CModelEntity::ODE.
 {
   switch (comp->getStatus())
     {
       case CModelEntity::FIXED:
       {
         if (!exportSingleObject(fixed, NameMap[comp->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       {
         initial << "init ";
         if (!exportSingleObject(initial, NameMap[comp->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
         if (!exportSingleObject(assignment, NameMap[comp->getKey()], expression, comments))
           return false;
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterBM::exportSingleMetabolite (const CMetab * metab, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 218 of file CODEExporterBM.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CMetab::isDependent(), CODEExporter::NameMap, CModelEntity::ODE, and CModelEntity::REACTIONS.
 {
   std::string name;
   std::ostringstream smKey;
   smKey << "sm_" << metab->getKey();
   name = NameMap[smKey.str()];
   switch (metab->getStatus())
     {
       case CModelEntity::FIXED:
         if (!exportSingleObject(fixed, name, expression, comments))
           return false;
         break;
       case CModelEntity::REACTIONS:
       {
         if (metab->isDependent())
           {
             if (!exportSingleObject(assignment, name, expression, comments))
               return false;
           }
         else
           {
             initial << "init ";
             if (!exportSingleObject(initial, name, expression, comments))
               return false;
           }
         break;
       }
       case CModelEntity::ODE:
       {
         initial << "init ";
         if (!exportSingleObject(initial, name, expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
         if (!exportSingleObject(assignment, name, expression, comments))
           return false;
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterBM::exportSingleModelEntity (const CModelEntity * tmp, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 355 of file CODEExporterBM.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CODEExporter::NameMap, and CModelEntity::ODE.
 {
   std::string name;
   const CMetab* metab;
   metab = dynamic_cast< const CMetab * >(tmp);
   if (metab)
     {
       std::ostringstream smKey;
       smKey << "sm_" << metab->getKey();
       name = NameMap[smKey.str()];
     }
   else
     name = NameMap[tmp->getKey()];
   switch (tmp->getStatus())
     {
       case CModelEntity::FIXED:
       {
         if (!exportSingleObject(fixed, name, expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       {
         if (!exportSingleObject(initial, name, expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
         if (!exportSingleObject(assignment, name, expression, comments))
           return false;
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterBM::exportSingleModVal (const CModelValue * modval, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 317 of file CODEExporterBM.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CODEExporter::NameMap, and CModelEntity::ODE.
 {
   switch (modval->getStatus())
     {
       case CModelEntity::FIXED:
       {
         if (!exportSingleObject(fixed, NameMap[modval->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       {
         initial << "init ";
         if (!exportSingleObject(initial, NameMap[modval->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
         if (!exportSingleObject(assignment, NameMap[modval->getKey()], expression, comments))
           return false;
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterBM::exportSingleObject (std::ostringstream & which, const std::string & name, const std::string & expression, const std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 207 of file CODEExporterBM.cpp.
Referenced by exportSingleCompartment(), exportSingleMetabolite(), exportSingleModelEntity(), exportSingleModVal(), exportSingleODE(), and exportSingleParameter().
 {
   which << name << " = " << expression
         << '\t' << '\t' << "; " << comments << std::endl;
   return true;
 }
bool CODEExporterBM::exportSingleODE (const CModelEntity * mentity, std::string & equation, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 413 of file CODEExporterBM.cpp.
References exportSingleObject(), CModelEntity::getKey(), CODEExporter::NameMap, and CODEExporter::ode.
 {
   std::ostringstream odeKey;
   odeKey << "ode_" << mentity->getKey();
   if (!exportSingleObject(ode, NameMap[odeKey.str()], equation, comments)) return false;
   return true;
 }
bool CODEExporterBM::exportSingleParameter (const CCopasiParameter * param, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 406 of file CODEExporterBM.cpp.
References exportSingleObject(), CODEExporter::fixed, CCopasiParameter::getKey(), and CODEExporter::NameMap.
 {
   if (!exportSingleObject(fixed, NameMap[param->getKey()], expression, comments)) return false;
   return true;
 }
bool CODEExporterBM::exportTitleData (const CCopasiDataModel * pDataModel, std::ostream & os) virtual
Definition at line 56 of file CODEExporterBM.cpp.
References CTrajectoryProblem::getDuration(), CCopasiTask::getProblem(), and CTrajectoryProblem::getStepSize().
 {
   os << "METHOD stiff" << std::endl;
   os << std::endl;
   os << "STARTTIME = 0" << std::endl;
   const CTrajectoryTask * pTrajectory =
     dynamic_cast<const CTrajectoryTask *>((*const_cast<CCopasiDataModel*>(pDataModel)->getTaskList())["Time-Course"]);
   const CTrajectoryProblem * pTrajectoryProblem =
     dynamic_cast<const CTrajectoryProblem *>(pTrajectory->getProblem());
   os << "STOPTIME = " << pTrajectoryProblem->getDuration() << std::endl;
   os << "DT = " << pTrajectoryProblem->getStepSize() << std::endl;
   os << std::endl;
   return true;
 }
std::string CODEExporterBM::exportTitleString (const size_t tmp) virtual
Reimplemented from CODEExporter.
Definition at line 445 of file CODEExporterBM.cpp.
References CODEExporter::ASSIGNMENT, CODEExporter::FIXED, CODEExporter::FUNCTIONS, CODEExporter::HEADERS, CODEExporter::INITIAL, and CODEExporter::ODEs.
 {
   switch (tmp)
     {
       case INITIAL:
         return "{Initial values:}";
       case FIXED:
         return "{Fixed Model Entities: }";
       case ASSIGNMENT:
         return "{Assignment Model Entities: }";
       case FUNCTIONS:
         return "{Kinetics: }";
       case HEADERS:
         return " ";
       case ODEs:
         return "{Equations:}";
       default:
         return " ";
     }
 }
std::string CODEExporterBM::getDisplayExpressionString (CExpression * tmp) virtual
Reimplemented from CODEExporter.
Definition at line 431 of file CODEExporterBM.cpp.
References CEvaluationNode::buildBerkeleyMadonnaString(), and CEvaluationTree::getRoot().
 {
   std::string str1;
   str1 = tmp->getRoot()->buildBerkeleyMadonnaString();
   return str1;
 }
std::string CODEExporterBM::getDisplayFunctionString (CFunction * func) virtual
Reimplemented from CODEExporter.
Definition at line 424 of file CODEExporterBM.cpp.
References CEvaluationNode::buildBerkeleyMadonnaString(), and CEvaluationTree::getRoot().
 {
   std::string str1;
   str1 = func->getRoot()->buildBerkeleyMadonnaString();
   return str1;
 }
std::string CODEExporterBM::KineticFunction2ODEmember (const CReaction * reac) virtual
Reimplemented from CODEExporter.
Definition at line 438 of file CODEExporterBM.cpp.
References CReaction::getKey(), and CODEExporter::NameMap.
 {
   std::ostringstream localKey;
   localKey << reac->getKey() << "_root_func";
   return NameMap[localKey.str()];
 }
std::string CODEExporterBM::setConcentrationName (const std::string & objName) virtual
Reimplemented from CODEExporter.
Definition at line 197 of file CODEExporterBM.cpp.
 {
   return objName + "_c";
 }
std::string CODEExporterBM::setODEName (const std::string & objName) virtual
Reimplemented from CODEExporter.
Definition at line 202 of file CODEExporterBM.cpp.
 {
   return "d/dt(" + objName + ")";
 }
void CODEExporterBM::setReservedNames () virtual
Reimplemented from CODEExporter.
Definition at line 194 of file CODEExporterBM.cpp.
 {return;}  // TODO
std::string CODEExporterBM::testName (const std::string & name)
This method tests whether the given Berkeley Madonna name already assigned, put the new name (in cappital letters: all names can be upper or lower case) in the set of assigned names or modify the name
Definition at line 158 of file CODEExporterBM.cpp.
References Frequancy, and NameSet.
Referenced by translateObjectName().
 {
   std::locale C("C");
   char ch;
   std::ostringstream newname, tmp;
   size_t name_size = name.size();
   size_t i;
   for (i = 0; i < name_size; i++)
     {
       ch = name[i];
       if (std::isalpha(ch, C) && std::islower(ch, C))
         tmp << (char) toupper(ch);
       else
         tmp << ch;
     }
   if (NameSet.find(tmp.str()) == NameSet.end())
     {
       NameSet.insert(tmp.str());
       Frequancy[tmp.str()] = 0;
       return name;
     }
   else
     {
       Frequancy[tmp.str()]++;
       newname << name << "_" << Frequancy[tmp.str()];
       return testName(newname.str());
     }
 }
std::string CODEExporterBM::translateObjectName (const std::string & realName) virtual
This method adapt a Copasi name for Berkeley Madonna syntax: Names can not start with a number. Any other combination of letters and numbers is valid as is the underscore.
Reimplemented from CODEExporter.
Definition at line 82 of file CODEExporterBM.cpp.
References testName().
 {
   std::locale C("C");
   char ch;
   std::ostringstream tmpName;
   size_t realName_size = realName.size();
   size_t i;
   ch = realName[0];
   if (!std::isalpha(ch, C))
     {
       tmpName << "_";
       if (std::isdigit(ch, C)) tmpName << ch;
     }
   else tmpName << ch;
   for (i = 1; i < realName_size; i++)
     {
       ch = realName[i];
       if (std::isalpha(ch, C))
         {
           if (std::isspace(realName[i - 1], C) && std::islower(ch, C))
             tmpName << (char) toupper(ch);
           else
             tmpName << ch;
         }
       if (std::isdigit(ch, C)) tmpName << ch;
       if (std::ispunct(ch, C))
         switch (ch)
           {
             case '_':
               tmpName << ch;
               break;
             case '-':
               tmpName << "_";
               break;
             case '{':
               tmpName << "_";
               break;
             case '}':
               tmpName << "_";
               break;
             case '(':
               tmpName << "_";
               break;
             case ')':
               tmpName << "_";
               break;
             default:
               break;
           }
     }
   return testName(tmpName.str());
 }
std::string CODEExporterBM::translateTimeVariableName () virtual
Reimplemented from CODEExporter.
Definition at line 74 of file CODEExporterBM.cpp.
 {return "TIME";}
Member Data Documentation
std::map< std::string, size_t > CODEExporterBM::Frequancy
Definition at line 72 of file CODEExporterBM.h.
Referenced by testName().
std::set<std::string> CODEExporterBM::NameSet
Definition at line 73 of file CODEExporterBM.h.
Referenced by testName().
The documentation for this class was generated from the following files:
CODEExporterBM.h
CODEExporterBM.cpp