COPASI API: CQRenderConverter Class Reference
CQRenderConverter Class Reference
#include <CQRenderConverter.h>
Static Public Member Functions
static void applyStyle (QGraphicsTextItem *item, const CLBoundingBox *bounds, const CLGroup *style, const CLRenderResolver *resolver)
static void applyStyle (QGraphicsPathItem *item, const CLBoundingBox *bounds, const CLGroup *style, const CLRenderResolver *resolver, QGraphicsItemGroup *itemGroup)
static void applyStyle (QGraphicsItemGroup *item, const CLBoundingBox *bounds, const CLGroup *style, const CLRenderResolver *resolver)
static void fillGroupFromStyle (QGraphicsItemGroup *group, const CLBoundingBox *bounds, const CLStyle *style, const CLRenderResolver *resolver)
static void setBackground (QGraphicsScene *scene, const std::string &fill, const CLRenderResolver *resolver)
Detailed Description
Definition at line 20 of file CQRenderConverter.h.
Member Function Documentation
void CQRenderConverter::applyStyle (QGraphicsTextItem * item, const CLBoundingBox * bounds, const CLGroup * style, const CLRenderResolver * resolver) static
Definition at line 1083 of file CQRenderConverter.cpp.
References adjustPosition(), getColor(), getFont(), CLGraphicalPrimitive1D::getStroke(), and CLGraphicalPrimitive1D::isSetStroke().
Referenced by CQConnectionGraphicsItem::CQConnectionGraphicsItem(), and CQLabelGraphicsItem::CQLabelGraphicsItem().
 {
   if (resolver == NULL || style == NULL || bounds == NULL || item == NULL)
     return;
   if (style->isSetStroke())
     item->setDefaultTextColor(getColor(style->getStroke(), resolver));
   QSharedPointer<QFont> font = getFont(NULL, style, resolver, bounds);
   if (!font.isNull())
     {
       item->setFont(*font);
       adjustPosition(item, bounds, NULL, style);
     }
 }
void CQRenderConverter::applyStyle (QGraphicsPathItem * item, const CLBoundingBox * bounds, const CLGroup * style, const CLRenderResolver * resolver, QGraphicsItemGroup * itemGroup) static
Definition at line 1044 of file CQRenderConverter.cpp.
References addLineEndingToItem(), CLGroup::getEndHead(), CLRenderResolver::getLineEnding(), getPen(), CLGroup::getStartHead(), and CLGroup::isSetEndHead().
 {
   if (resolver == NULL || group == NULL || bounds == NULL || item == NULL)
     return;
   QSharedPointer<QPen> pen = getPen(NULL, group, resolver, bounds);
   item->setPen(*pen);
   if (item->path().elementCount() < 2)
     return;
   QPointF start = item->path().elementAt(0);
   QPointF second = item->path().elementAt(1);
   QPointF end = item->path().elementAt(item->path().elementCount() - 1);
   QPointF secondLast = item->path().elementAt(item->path().elementCount() - 2);
   if (group -> isSetStartHead())
     {
       const CLLineEnding *line = resolver->getLineEnding(group->getStartHead());
       addLineEndingToItem(item, line, group, resolver, start, second, itemGroup);
     }
   if (group->isSetEndHead())
     {
       const CLLineEnding *line = resolver->getLineEnding(group->getEndHead());
       addLineEndingToItem(item, line, group, resolver, end, secondLast, itemGroup);
     }
 }
void CQRenderConverter::applyStyle (QGraphicsItemGroup * item, const CLBoundingBox * bounds, const CLGroup * style, const CLRenderResolver * resolver) static
Definition at line 1073 of file CQRenderConverter.cpp.
 {
   if (resolver == NULL || style == NULL || bounds == NULL || group == NULL)
     return;
   for (int i = 0; i < group->childItems().size(); ++i)
     {
     }
 }
void CQRenderConverter::fillGroupFromStyle (QGraphicsItemGroup * group, const CLBoundingBox * bounds, const CLStyle * style, const CLRenderResolver * resolver) static
Definition at line 1101 of file CQRenderConverter.cpp.
References fillItemFromGroup(), and CLStyle::getGroup().
Referenced by CQConnectionGraphicsItem::CQConnectionGraphicsItem(), and CQStyledGraphicsItem::CQStyledGraphicsItem().
 {
   if (resolver == NULL || style == NULL || bounds == NULL || group == NULL)
     return;
   fillItemFromGroup(group, bounds, style->getGroup(), resolver);
 }
void CQRenderConverter::setBackground (QGraphicsScene * scene, const std::string & fill, const CLRenderResolver * resolver) static
Definition at line 1109 of file CQRenderConverter.cpp.
References getColor().
Referenced by CQLayoutScene::fillFromLayout().
 {
   if (resolver == NULL || scene == NULL) return;
   QBrush brush(getColor(fill, resolver));
   scene->setBackgroundBrush(brush);
 }
The documentation for this class was generated from the following files:
CQRenderConverter.h
CQRenderConverter.cpp