COPASI API: CQAnimationControls Class Reference
CQAnimationControls Class Reference
#include <CQAnimationControls.h>
Public Slots
void slotBack ()
void slotChangeInterval (int)
void slotForward ()
void slotShowStep (int)
void slotStepBack ()
void slotStepForward ()
void slotStop ()
void slotTogglePlayPause ()
Signals
void backward ()
void forward ()
void pause ()
void play ()
void showStep (int)
void step_backward ()
void step_forward ()
void stop ()
Public Member Functions
CQAnimationControls (QWidget *parent=NULL)
bool isPlaying () const
void setCurrentStep (size_t currentStep)
void setNumSteps (size_t numSteps)
virtual ~CQAnimationControls ()
Protected Member Functions
void createActions ()
void updateActions ()
void updateButtons ()
Protected Attributes
size_t mCurrentStep
size_t mNumSteps
QTimer * mpTimer
bool mShouldLoop
Detailed Description
Definition at line 15 of file CQAnimationControls.h.
Constructor & Destructor Documentation
CQAnimationControls::CQAnimationControls (QWidget * parent = NULL)
Definition at line 11 of file CQAnimationControls.cpp.
References CQIconResource::backward, CQIconResource::forward, CQIconResource::icon(), mNumSteps, mpTimer, CQIconResource::play, CQIconResource::skipBackward, CQIconResource::skipForward, slotStepForward(), and CQIconResource::stop.
   : QWidget(parent)
   , mNumSteps(100)
   , mCurrentStep(0)
   , mShouldLoop(true)
   , mpTimer(new QTimer(this))
 {
   setupUi(this);
   cmdBack->setIcon(CQIconResource::icon(CQIconResource::skipBackward));
   cmdForward->setIcon(CQIconResource::icon(CQIconResource::skipForward));
   cmdStepBack->setIcon(CQIconResource::icon(CQIconResource::backward));
   cmdStepForward->setIcon(CQIconResource::icon(CQIconResource::forward));
   cmdPlayPause->setIcon(CQIconResource::icon(CQIconResource::play));
   cmdStop->setIcon(CQIconResource::icon(CQIconResource::stop));
   mpTimer->setInterval(1000 / 10); // 10fps default
   lblDuration->setText(QString::number(mNumSteps));
   connect(mpTimer, SIGNAL(timeout()), this, SLOT(slotStepForward()));
 }
CQAnimationControls::~CQAnimationControls () virtual
Definition at line 72 of file CQAnimationControls.cpp.
 {
 }
Member Function Documentation
void CQAnimationControls::backward () signal
Referenced by slotBack().
void CQAnimationControls::createActions () protected
void CQAnimationControls::forward () signal
Referenced by slotForward().
bool CQAnimationControls::isPlaying () const
Definition at line 67 of file CQAnimationControls.cpp.
References mpTimer.
Referenced by slotTogglePlayPause().
 {
   return mpTimer->isActive();
 }
void CQAnimationControls::pause () signal
Referenced by slotTogglePlayPause().
void CQAnimationControls::play () signal
Referenced by slotTogglePlayPause().
void CQAnimationControls::setCurrentStep (size_t currentStep)
Definition at line 48 of file CQAnimationControls.cpp.
References mCurrentStep, mNumSteps, updateActions(), and updateButtons().
 {
   if (currentStep < mNumSteps)
     {
       mCurrentStep = currentStep;
     }
   else if (mNumSteps > 0)
     {
       mCurrentStep = mNumSteps - 1;
     }
   else
     {
       mCurrentStep = 0;
     }
   updateButtons();
   updateActions();
 }
void CQAnimationControls::setNumSteps (size_t numSteps)
Definition at line 38 of file CQAnimationControls.cpp.
References mNumSteps.
 {
   if (mNumSteps == numSteps) return;
   mNumSteps = numSteps;
   sldPosition->setMaximum(numSteps - 1);
   lblCurrent->setText(QString::number(sldPosition->minimum() + 1));
   lblDuration->setText(QString::number(numSteps));
 }
void CQAnimationControls::showStep (int) signal
Referenced by slotShowStep().
void CQAnimationControls::slotBack () slot
Definition at line 76 of file CQAnimationControls.cpp.
References backward().
 {
   emit backward();
   sldPosition->setValue(0);
 }
void CQAnimationControls::slotChangeInterval (int interval) slot
Definition at line 33 of file CQAnimationControls.cpp.
References mpTimer.
 {
   mpTimer->setInterval(interval);
 }
void CQAnimationControls::slotForward () slot
Definition at line 82 of file CQAnimationControls.cpp.
References forward(), and mNumSteps.
 {
   emit forward();
   sldPosition->setValue(mNumSteps - 1);
 }
void CQAnimationControls::slotShowStep (int step) slot
Definition at line 146 of file CQAnimationControls.cpp.
References mCurrentStep, showStep(), updateActions(), and updateButtons().
 {
   mCurrentStep = step;
   lblCurrent->setText(QString::number(step + 1));
   updateButtons();
   updateActions();
   emit showStep(step);
 }
void CQAnimationControls::slotStepBack () slot
Definition at line 106 of file CQAnimationControls.cpp.
References mCurrentStep, and step_backward().
 {
   emit step_backward();
   sldPosition->setValue(mCurrentStep < 2 ? 0 : --mCurrentStep);
 }
void CQAnimationControls::slotStepForward () slot
Definition at line 112 of file CQAnimationControls.cpp.
References mCurrentStep, mNumSteps, mShouldLoop, slotStop(), and step_forward().
Referenced by CQAnimationControls().
 {
   emit step_forward();
   int next;
   if (mCurrentStep >= mNumSteps - 1)
     {
       if (mShouldLoop)
         {
           next = 0;
         }
       else
         {
           slotStop();
           return;
         }
     }
   else
     {
       next = ++mCurrentStep;
     }
   sldPosition->setValue(next);
 }
void CQAnimationControls::slotStop () slot
Definition at line 138 of file CQAnimationControls.cpp.
References CQIconResource::icon(), mpTimer, CQIconResource::play, and stop().
Referenced by slotStepForward().
 {
   mpTimer->stop();
   cmdPlayPause->setIcon(CQIconResource::icon(CQIconResource::play));
   emit stop();
   sldPosition->setValue(0);
 }
void CQAnimationControls::slotTogglePlayPause () slot
Definition at line 88 of file CQAnimationControls.cpp.
References CQIconResource::icon(), isPlaying(), mpTimer, pause(), CQIconResource::pause, play(), and CQIconResource::play.
 {
   bool playing = isPlaying();
   if (playing)
     {
       mpTimer->stop();
       emit pause();
       cmdPlayPause->setIcon(CQIconResource::icon(CQIconResource::play));
     }
   else
     {
       mpTimer->start();
       emit play();
       cmdPlayPause->setIcon(CQIconResource::icon(CQIconResource::pause));
     }
 }
void CQAnimationControls::step_backward () signal
Referenced by slotStepBack().
void CQAnimationControls::step_forward () signal
Referenced by slotStepForward().
void CQAnimationControls::stop () signal
Referenced by slotStop().
void CQAnimationControls::updateActions () protected
Definition at line 158 of file CQAnimationControls.cpp.
Referenced by setCurrentStep(), and slotShowStep().
 {
 }
void CQAnimationControls::updateButtons () protected
Definition at line 155 of file CQAnimationControls.cpp.
Referenced by setCurrentStep(), and slotShowStep().
 {
 }
Member Data Documentation
size_t CQAnimationControls::mCurrentStep protected
Definition at line 48 of file CQAnimationControls.h.
Referenced by setCurrentStep(), slotShowStep(), slotStepBack(), and slotStepForward().
size_t CQAnimationControls::mNumSteps protected
Definition at line 47 of file CQAnimationControls.h.
Referenced by CQAnimationControls(), setCurrentStep(), setNumSteps(), slotForward(), and slotStepForward().
QTimer* CQAnimationControls::mpTimer protected
Definition at line 50 of file CQAnimationControls.h.
Referenced by CQAnimationControls(), isPlaying(), slotChangeInterval(), slotStop(), and slotTogglePlayPause().
bool CQAnimationControls::mShouldLoop protected
Definition at line 49 of file CQAnimationControls.h.
Referenced by slotStepForward().
The documentation for this class was generated from the following files:
CQAnimationControls.h
CQAnimationControls.cpp