COPASI API: CQSplashWidget Class Reference
CQSplashWidget Class Reference
#include <CQSplashWidget.h>
Public Member Functions
CQSplashWidget (QWidget *parent=0, const char *name=0)
~CQSplashWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
Private Slots
void slotViewLicense ()
Private Member Functions
void init ()
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions inherited from CopasiWidget
virtual bool enterProtected ()
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 21 of file CQSplashWidget.h.
Constructor & Destructor Documentation
CQSplashWidget::CQSplashWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 26 of file CQSplashWidget.cpp.
References image0_data, and init().
     : CopasiWidget(parent, name)
 {
   setupUi(this);
   mpPixmap->setObjectName(QString::fromUtf8("mpPixmap"));
   mpPixmap->setPixmap(QPixmap((const char**)image0_data));
   init();
 }
CQSplashWidget::~CQSplashWidget ()
Definition at line 40 of file CQSplashWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQSplashWidget::init () private
Definition at line 45 of file CQSplashWidget.cpp.
References FROM_UTF8, and CVersion::VERSION.
Referenced by CQSplashWidget().
 {
   mpLblVersion->setText(mpLblVersion->text().arg(FROM_UTF8(CVersion::VERSION.getVersion())));
   return;
 }
void CQSplashWidget::slotViewLicense () private slot
Definition at line 52 of file CQSplashWidget.cpp.
References FROM_UTF8, CCopasiRootContainer::getLicenseHTML(), and CVersion::VERSION.
 {
   QString FixedTitle = "COPASI ";
   FixedTitle += FROM_UTF8(CVersion::VERSION.getVersion());
   AboutDialog* aboutDialog = new AboutDialog(this, CCopasiRootContainer::getLicenseHTML(), 76, 30);
   aboutDialog->setWindowTitle(FixedTitle);
   aboutDialog->exec();
 }
The documentation for this class was generated from the following files:
CQSplashWidget.h
CQSplashWidget.cpp