COPASI API: CQLayoutsWidget.cpp File Reference
CQLayoutsWidget.cpp File Reference
#include "CQLayoutsWidget.h"
#include <iostream>
#include "CQMessageBox.h"
#include "CQLayoutsDM.h"
#include "CQSortFilterProxyModel.h"
#include "CQPushButtonDelegate.h"
#include "listviews.h"
#include "qtUtilities.h"
#include "resourcesUI/CQIconResource.h"
#include "copasi/layout/CLayout.h"
#include "copasi/layout/CListOfLayouts.h"
#include "copasi/model/CModel.h"
#include "copasi/report/CKeyFactory.h"
#include "copasi/CopasiDataModel/CCopasiDataModel.h"
#include <copasi/commandline/CConfigurationFile.h>
#include "report/CCopasiRootContainer.h"
#include "copasi/layoutUI/CQNewMainWindow.h"
#include <qlayout/CQAnimationWindow.h>
#include "copasi/layoutUI/CQAutolayoutWizard.h"
#include <copasi/UI/copasiui3window.h>
#include <sstream>
Functions
bool hasLayout (const CListOfLayouts &layouts, const std::string &name)
Function Documentation
bool hasLayout (const CListOfLayouts & layouts, const std::string & name)
Definition at line 218 of file CQLayoutsWidget.cpp.
References CCopasiObject::getObjectName(), and CCopasiVector< T >::size().
Referenced by CQLayoutsWidget::slotBtnNewClicked().
 {
   for (size_t i = 0; i < layouts.size(); ++i)
     {
       const CLayout *layout = layouts[i];
       const std::string &current = layout->getObjectName();
       if (current == name)
         return true;
     }
   return false;
 }