COPASI API: CQNotes Class Reference
CQNotes Class Reference
#include <CQNotes.h>
Public Member Functions
CQNotes (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQNotes ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
void slotBtnCopy ()
void slotOpenUrl (const QUrl &url)
void slotToggleMode ()
void slotValidateXML ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
Private Member Functions
void load ()
void save ()
Private Attributes
bool mChanged
bool mEditMode
std::string mKeyToCopy
CQValidatorXML * mpValidatorXML
QValidator::State mValidity
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 67 of file CQNotes.h.
Constructor & Destructor Documentation
CQNotes::CQNotes (QWidget * parent = 0, const char * name = 0)
Definition at line 132 of file CQNotes.cpp.
References CQIconResource::edit, CQIconResource::icon(), mEditMode, and mpValidatorXML.
                                                   :
   CopasiWidget(parent, name),
   mEditMode(false),
   mChanged(false),
   mpValidatorXML(NULL),
   mValidity(QValidator::Acceptable),
   mKeyToCopy("")
 {
   setupUi(this);
   mpValidatorXML = new CQValidatorXML(mpEdit);
   mEditMode = false;
   mpEdit->hide();
   mpWebView->show();
   mpBtnToggleEdit->setIcon(CQIconResource::icon(CQIconResource::edit));
   mpWebView->page()->setLinkDelegationPolicy(QWebPage::DelegateAllLinks);
 }
CQNotes::~CQNotes ()
Definition at line 153 of file CQNotes.cpp.
 {}
Member Function Documentation
bool CQNotes::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 219 of file CQNotes.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), load(), CopasiWidget::mKey, mKeyToCopy, CopasiWidget::mpObject, and save().
 {
   if (mKeyToCopy == "")
     {
       load();
     }
   else
     {
       mpObject = CCopasiRootContainer::getKeyFactory()->get(mKeyToCopy);
       load();
       mpObject = CCopasiRootContainer::getKeyFactory()->get(mKey);
       save();
       mKeyToCopy = "";
     }
   return true;
 }
bool CQNotes::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 199 of file CQNotes.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CopasiWidget::mKey, CopasiWidget::mpDataModel, CopasiWidget::mpObject, and save().
 {
   mpBtnToggleEdit->setFocus();
   mpObject = CCopasiRootContainer::getKeyFactory()->get(mKey);
   if (mpObject != NULL)
     {
       save();
     }
   else
     {
       mKey = "";
       mpDataModel = NULL;
     }
   return true;
 }
void CQNotes::load () private
Definition at line 289 of file CQNotes.cpp.
References CAnnotation::castObject(), FROM_UTF8, CReportDefinition::getComment(), CAnnotation::getNotes(), CQValidatorXML::isFreeText(), mChanged, mEditMode, CopasiWidget::mpObject, mpValidatorXML, mValidity, CQValidator< Type >::saved(), slotToggleMode(), and slotValidateXML().
Referenced by enterProtected(), slotToggleMode(), and update().
 {
   if (mpObject != NULL)
     {
       QString Notes;
       CAnnotation * pAnnotation = CAnnotation::castObject(mpObject);
       CReportDefinition * pReportDefinition = static_cast< CReportDefinition * >(mpObject);
       if (pAnnotation != NULL)
         {
           Notes = FROM_UTF8(pAnnotation->getNotes());
         }
       else if (pReportDefinition != NULL)
         {
           Notes = FROM_UTF8(pReportDefinition->getComment());
         }
       // The notes are UTF8 encoded however the html does not specify an encoding
       // thus Qt uses locale settings.
       mpWebView->setHtml(Notes);
       mpEdit->setPlainText(Notes);
       mpValidatorXML->saved();
       slotValidateXML();
       if (!mpValidatorXML->isFreeText() && mEditMode)
         {
           slotToggleMode();
         }
       mValidity = QValidator::Acceptable;
     }
   mChanged = false;
   return;
 }
void CQNotes::save () private
Definition at line 327 of file CQNotes.cpp.
References CAnnotation::castObject(), ListViews::CHANGE, CCopasiDataModel::changed(), FROM_UTF8, CReportDefinition::getComment(), CAnnotation::getNotes(), mChanged, CopasiWidget::mKey, ListViews::MODEL, CopasiWidget::mpDataModel, CopasiWidget::mpObject, mpValidatorXML, mValidity, CQValidatorXML::needsWrap(), CopasiWidget::protectedNotify(), CReportDefinition::setComment(), CAnnotation::setNotes(), and TO_UTF8.
Referenced by enterProtected(), leave(), and slotToggleMode().
 {
   if (mpObject != NULL &&
       mValidity == QValidator::Acceptable)
     {
       QString Notes;
       CAnnotation * pAnnotation = CAnnotation::castObject(mpObject);
       CReportDefinition * pReportDefinition = static_cast< CReportDefinition * >(mpObject);
       if (pAnnotation != NULL)
         {
           Notes = FROM_UTF8(pAnnotation->getNotes());
         }
       else if (pReportDefinition != NULL)
         {
           Notes = FROM_UTF8(pReportDefinition->getComment());
         }
       if (mpEdit->toPlainText() != Notes)
         {
           std::string PlainText = TO_UTF8(mpEdit->toPlainText());
           if (mpValidatorXML->needsWrap())
             {
               // We wrap the HTML in a body element if it does not contain a top level html or body element.
               PlainText = "<body xmlns=\"http://www.w3.org/1999/xhtml\">" + PlainText + "</body>";
             }
           if (pAnnotation != NULL)
             {
               pAnnotation->setNotes(PlainText);
             }
           else if (pReportDefinition != NULL)
             {
               pReportDefinition->setComment(PlainText);
             }
           mChanged = true;
         }
     }
   if (mChanged)
     {
       if (mpDataModel != NULL)
         {
           mpDataModel->changed();
         }
       protectedNotify(ListViews::MODEL, ListViews::CHANGE, mKey);
       mChanged = false;
     }
   return;
 }
void CQNotes::slotBtnCopy () protected slot
Definition at line 156 of file CQNotes.cpp.
References CopasiWidget::mKey, and mKeyToCopy.
 {
   mKeyToCopy = mKey;
 }
void CQNotes::slotOpenUrl (const QUrl & url) protected slot
Definition at line 383 of file CQNotes.cpp.
 {
   QDesktopServices::openUrl(url);
   return;
 }
void CQNotes::slotToggleMode () protected slot
Definition at line 237 of file CQNotes.cpp.
References CQIconResource::edit, CQIconResource::icon(), load(), mEditMode, CQIconResource::renderMarkup, and save().
Referenced by load().
 {
   mEditMode = !mEditMode;
   if (mEditMode)
     {
       mpWebView->hide();
       mpEdit->show();
       mpBtnToggleEdit->setIcon(CQIconResource::icon(CQIconResource::renderMarkup));
     }
   else
     {
       save();
       load();
       mpEdit->hide();
       mpWebView->show();
       mpBtnToggleEdit->setIcon(CQIconResource::icon(CQIconResource::edit));
     }
 }
void CQNotes::slotValidateXML () protected slot
Definition at line 258 of file CQNotes.cpp.
References CQIconResource::edit, CQIconResource::icon(), CQValidatorXML::isFreeText(), mEditMode, mpValidatorXML, mValidity, CQIconResource::renderMarkup, and CQValidatorXML::validate().
Referenced by load().
 {
   QString Input = mpEdit->toPlainText();
   int pos = 0;
   mValidity = mpValidatorXML->validate(Input, pos);
   if (mpValidatorXML->isFreeText())
     {
       mEditMode = true;
       mpBtnToggleEdit->hide();
     }
   else
     {
       mpBtnToggleEdit->show();
     }
   if (mEditMode)
     {
       mpWebView->hide();
       mpEdit->show();
       mpBtnToggleEdit->setIcon(CQIconResource::icon(CQIconResource::renderMarkup));
     }
   else
     {
       mpEdit->hide();
       mpWebView->show();
       mpBtnToggleEdit->setIcon(CQIconResource::icon(CQIconResource::edit));
     }
 }
bool CQNotes::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 162 of file CQNotes.cpp.
References ListViews::CHANGE, ListViews::DELETE, load(), mEditMode, CopasiWidget::mKey, ListViews::MODEL, and CopasiWidget::mpObject.
 {
   switch (action)
     {
       case ListViews::CHANGE:
         if (key == mKey)
           {
             load();
           }
         break;
       case ListViews::DELETE:
         if (key == mKey || objectType == ListViews::MODEL)
           {
             mpObject = NULL;
             mKey = "";
           }
         break;
       default:
         break;
     }
   if (objectType == ListViews::MODEL &&
       action == ListViews::DELETE)
     {
       mEditMode = false;
     }
   return true;
 }
Member Data Documentation
bool CQNotes::mChanged private
Definition at line 92 of file CQNotes.h.
Referenced by load(), and save().
bool CQNotes::mEditMode private
Definition at line 91 of file CQNotes.h.
Referenced by CQNotes(), load(), slotToggleMode(), slotValidateXML(), and update().
std::string CQNotes::mKeyToCopy private
Definition at line 96 of file CQNotes.h.
Referenced by enterProtected(), and slotBtnCopy().
CQValidatorXML* CQNotes::mpValidatorXML private
Definition at line 93 of file CQNotes.h.
Referenced by CQNotes(), load(), save(), and slotValidateXML().
QValidator::State CQNotes::mValidity private
Definition at line 94 of file CQNotes.h.
Referenced by load(), save(), and slotValidateXML().
The documentation for this class was generated from the following files:
CQNotes.h
CQNotes.cpp