COPASI API: CCopasiXMLParser::ReactionElement Class Reference
CCopasiXMLParser::ReactionElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ReactionElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ReactionElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Reaction = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
ListOfSubstrates, ListOfProducts, ListOfModifiers, ListOfConstants,
KineticLaw
}
Private Attributes
std::string mKey
KineticLawElement * mpKineticLawElement
ListOfConstantsElement * mpListOfConstantsElement
ListOfModifiersElement * mpListOfModifiersElement
ListOfProductsElement * mpListOfProductsElement
ListOfSubstratesElement * mpListOfSubstratesElement
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1123 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ReactionElement::Element private
Enum of invoked parsers
Enumerator
Reaction
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
ListOfSubstrates
ListOfProducts
ListOfModifiers
ListOfConstants
KineticLaw
Definition at line 1131 of file CCopasiXMLParser.h.
     {
       Reaction = 0,
       MiriamAnnotation,
       Comment,
       ListOfUnsupportedAnnotations,
       ListOfSubstrates,
       ListOfProducts,
       ListOfModifiers,
       ListOfConstants,
       KineticLaw
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ReactionElement::ReactionElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 3725 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpListOfSubstratesElement(NULL),
   mpListOfProductsElement(NULL),
   mpListOfModifiersElement(NULL),
   mpListOfConstantsElement(NULL),
   mpKineticLawElement(NULL)
 {}
CCopasiXMLParser::ReactionElement::~ReactionElement () virtual
Destructor
Definition at line 3735 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpListOfSubstratesElement);
   pdelete(mpListOfProductsElement);
   pdelete(mpListOfModifiersElement);
   pdelete(mpListOfConstantsElement);
   pdelete(mpKineticLawElement);
 }
Member Function Documentation
void CCopasiXMLParser::ReactionElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 3918 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CReaction::getKey(), CAnnotation::getUnsupportedAnnotations(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pReaction, CAnnotation::setMiriamAnnotation(), CAnnotation::setNotes(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Reaction:
         if (strcmp(pszName, "Reaction"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Reaction", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         mCommon.pReaction->setMiriamAnnotation(mCommon.CharacterData, mCommon.pReaction->getKey(), mKey);
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         mCommon.pReaction->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         mCommon.pReaction->getUnsupportedAnnotations() = mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case ListOfSubstrates:
         if (strcmp(pszName, "ListOfSubstrates"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfSubstrates", mParser.getCurrentLineNumber());
         break;
       case ListOfProducts:
         if (strcmp(pszName, "ListOfProducts"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfProducts", mParser.getCurrentLineNumber());
         break;
       case ListOfModifiers:
         if (strcmp(pszName, "ListOfModifiers"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfModifiers", mParser.getCurrentLineNumber());
         break;
       case ListOfConstants:
         if (strcmp(pszName, "ListOfConstants"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfConstants", mParser.getCurrentLineNumber());
         break;
       case KineticLaw:
         if (strcmp(pszName, "KineticLaw"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "KineticLaw", mParser.getCurrentLineNumber());
         break;
       case UNKNOWN_ELEMENT:
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   mCurrentElement = Reaction;
   return;
 }
void CCopasiXMLParser::ReactionElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 3744 of file CCopasiXMLParser.cpp.
References CCopasiVectorN< CType >::add(), CCopasiMessage::EXCEPTION, fatalError, CKeyFactory::get(), CModel::getReactions(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, SCopasiXMLParserCommon::pReaction, CReaction::setFast(), CCopasiObject::setObjectName(), CReaction::setReversible(), CReaction::setSBMLId(), and UNKNOWN_ELEMENT.
 {
   CCompartment * pCompartment;
   const char * Name;
   const char * Compartment; // Default Compartment_00
   const char * reversible;
   bool Reversible;
   const char * fast;
   bool Fast;
   const char * SBMLId;
   mCurrentElement = mLastKnownElement;
   mpCurrentHandler = NULL;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case Reaction:
             if (strcmp(pszName, "Reaction"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "Reaction", mParser.getCurrentLineNumber());
             mKey = mParser.getAttributeValue("key", papszAttrs);
             Name = mParser.getAttributeValue("name", papszAttrs);
             Compartment = mParser.getAttributeValue("compartment", papszAttrs,
                                                     "Compartment_00");
             reversible = mParser.getAttributeValue("reversible", papszAttrs);
             Reversible = mParser.toBool(reversible);
             fast = mParser.getAttributeValue("fast", papszAttrs, "false");
             Fast = mParser.toBool(fast);
             mCommon.pReaction = new CReaction();
             addFix(mKey, mCommon.pReaction);
             mCommon.pReaction->setObjectName(Name);
             mCommon.pReaction->setReversible(Reversible);
             mCommon.pReaction->setFast(Fast);
             SBMLId = mParser.getAttributeValue("sbmlid", papszAttrs, "");
             if (std::string(SBMLId) != std::string(""))
               {
                 mCommon.pReaction->setSBMLId(SBMLId);
               }
             if (strcmp(Compartment, "Compartment_00")) //TODO necessary?
               {
                 pCompartment =
                   dynamic_cast< CCompartment* >(mCommon.KeyMap.get(Compartment));
                 if (!pCompartment) fatalError();
                 //mCommon.pReaction->setCompartment(pCompartment);
               }
             mCommon.pModel->getReactions().add(mCommon.pReaction, true);
             mLastKnownElement = Reaction;
             return;
             break;
           case MiriamAnnotation:
             if (!strcmp(pszName, "MiriamAnnotation"))
               mpCurrentHandler = &mParser.mMiriamAnnotationElement;
             break;
           case Comment:
             if (!strcmp(pszName, "Comment"))
               {
                 mpCurrentHandler = &mParser.mCommentElement;
                 mLastKnownElement = mCurrentElement;
               }
             break;
           case ListOfUnsupportedAnnotations:
             if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
               mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             break;
           case ListOfSubstrates:
             if (!strcmp(pszName, "ListOfSubstrates"))
               {
                 /* If we do not have a function element handler we create one. */
                 if (!mpListOfSubstratesElement)
                   mpListOfSubstratesElement =
                     new ListOfSubstratesElement(mParser, mCommon);
                 mpCurrentHandler = mpListOfSubstratesElement;
               }
             break;
           case ListOfProducts:
             if (!strcmp(pszName, "ListOfProducts"))
               {
                 if (!mpListOfProductsElement)
                   mpListOfProductsElement =
                     new ListOfProductsElement(mParser, mCommon);
                 mpCurrentHandler = mpListOfProductsElement;
               }
             break;
           case ListOfModifiers:
             if (!strcmp(pszName, "ListOfModifiers"))
               {
                 if (!mpListOfModifiersElement)
                   mpListOfModifiersElement =
                     new ListOfModifiersElement(mParser, mCommon);
                 mpCurrentHandler = mpListOfModifiersElement;
               }
             break;
           case ListOfConstants:
             if (!strcmp(pszName, "ListOfConstants"))
               {
                 if (!mpListOfConstantsElement)
                   mpListOfConstantsElement =
                     new ListOfConstantsElement(mParser, mCommon);
                 mpCurrentHandler = mpListOfConstantsElement;
               }
             break;
           case KineticLaw:
             if (!strcmp(pszName, "KineticLaw"))
               {
                 if (!mpKineticLawElement)
                   mpKineticLawElement = new KineticLawElement(mParser, mCommon);
                 mpCurrentHandler = mpKineticLawElement;
               }
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::ReactionElement::mKey private
The key in the CopasiML gile
Definition at line 1172 of file CCopasiXMLParser.h.
KineticLawElement* CCopasiXMLParser::ReactionElement::mpKineticLawElement private
Pointer to ListOfConstantsElement element handler.
Definition at line 1167 of file CCopasiXMLParser.h.
ListOfConstantsElement* CCopasiXMLParser::ReactionElement::mpListOfConstantsElement private
Pointer to ListOfConstantsElement element handler.
Definition at line 1162 of file CCopasiXMLParser.h.
ListOfModifiersElement* CCopasiXMLParser::ReactionElement::mpListOfModifiersElement private
Pointer to ListOfModifiersElement element handler.
Definition at line 1157 of file CCopasiXMLParser.h.
ListOfProductsElement* CCopasiXMLParser::ReactionElement::mpListOfProductsElement private
Pointer to ListOfProductsElement element handler.
Definition at line 1152 of file CCopasiXMLParser.h.
ListOfSubstratesElement* CCopasiXMLParser::ReactionElement::mpListOfSubstratesElement private
Pointer to ListOfSubstratesElement element handler.
Definition at line 1147 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp