COPASI API: CQTaskMethodWidget Class Reference
CQTaskMethodWidget Class Reference
#include <CQTaskMethodWidget.h>
Public Member Functions
void clearHistory ()
CQTaskMethodWidget (QWidget *parent=0, Qt::WindowFlags f=0)
bool loadMethod ()
bool saveMethod ()
void setTask (CCopasiTask *pTask)
void setValidMethods (const unsigned int *validMethods)
void showMethodParameters (const bool &show)
virtual ~CQTaskMethodWidget ()
Protected Slots
void changeMethod (int)
Protected Member Functions
void addToHistory (CCopasiMethod *pMethod)
CCopasiMethod * getFromHistory (const CCopasiMethod::SubType &Type) const
void removeFromHistory (CCopasiMethod *pMethod)
void setActiveMethod (const CCopasiMethod::SubType &Type)
Protected Attributes
std::map
< CCopasiMethod::SubType,
CCopasiMethod * > mMethodHistory
CCopasiMethod * mpActiveMethod
CCopasiMethod * mpMethod
CCopasiTask * mpTask
bool mShowMethodParameters
bool mShowMethods
Detailed Description
Definition at line 16 of file CQTaskMethodWidget.h.
Constructor & Destructor Documentation
CQTaskMethodWidget::CQTaskMethodWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 15 of file CQTaskMethodWidget.cpp.
                                                                       :
   QWidget(parent, f),
   mpTask(NULL),
   mpMethod(NULL),
   mpActiveMethod(NULL),
   mMethodHistory(),
   mShowMethods(false),
   mShowMethodParameters(false)
 {
   setupUi(this);
   mpTableParameter->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTableParameter->horizontalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTableParameter->horizontalHeader()->hide();
   mpLblMethod->hide();
   mpBoxMethod->hide();
   mpLblParameter->hide();
   mpTableParameter->hide();
 }
CQTaskMethodWidget::~CQTaskMethodWidget () virtual
Definition at line 37 of file CQTaskMethodWidget.cpp.
References clearHistory().
 {
   clearHistory();
 }
Member Function Documentation
void CQTaskMethodWidget::addToHistory (CCopasiMethod * pMethod) protected
Definition at line 224 of file CQTaskMethodWidget.cpp.
References CCopasiMethod::getSubType(), and mMethodHistory.
Referenced by setActiveMethod().
 {
   if (pMethod == NULL)
     {
       return;
     }
   std::map< CCopasiMethod::SubType, CCopasiMethod * >::iterator found = mMethodHistory.find(pMethod->getSubType());
   if (found != mMethodHistory.end())
     {
       if (found->second != pMethod)
         {
           delete found->second;
           found->second = pMethod;
         }
       return;
     }
   mMethodHistory[pMethod->getSubType()] = pMethod;
 }
void CQTaskMethodWidget::changeMethod (int) protected slot
Definition at line 42 of file CQTaskMethodWidget.cpp.
References C_INT32, loadMethod(), mpActiveMethod, mpTask, mShowMethodParameters, setActiveMethod(), setParameterValue(), CCopasiParameterGroup::size(), CCopasiMethod::SubTypeName, TO_UTF8, toEnum(), and CCopasiMethod::unset.
Referenced by setValidMethods().
 {
   if (mpTask == NULL)
     return;
   // We update the active methods parameters
   if (mShowMethodParameters)
     {
       unsigned C_INT32 i;
       QString Value;
       for (i = 0; i < mpActiveMethod->size(); i++)
         {
           if (!mpTableParameter->item(i, 0))
             continue;
           Value = mpTableParameter->item(i, 0)->text();
           setParameterValue(mpActiveMethod, i, Value);
         }
     }
   CCopasiMethod::SubType Type =
     toEnum(TO_UTF8(mpBoxMethod->currentText()), CCopasiMethod::SubTypeName, CCopasiMethod::unset);
   setActiveMethod(Type);
   loadMethod();
   return;
 }
void CQTaskMethodWidget::clearHistory ()
Definition at line 289 of file CQTaskMethodWidget.cpp.
References mMethodHistory.
Referenced by TaskWidget::update(), and ~CQTaskMethodWidget().
 {
   std::map< CCopasiMethod::SubType, CCopasiMethod * >::iterator it = mMethodHistory.begin();
   std::map< CCopasiMethod::SubType, CCopasiMethod * >::iterator end = mMethodHistory.end();
   for (; it != end; ++it)
     {
       delete it->second;
     }
   mMethodHistory.clear();
 }
CCopasiMethod * CQTaskMethodWidget::getFromHistory (const CCopasiMethod::SubType & Type) const protected
Definition at line 262 of file CQTaskMethodWidget.cpp.
References mMethodHistory.
Referenced by setActiveMethod().
 {
   std::map< CCopasiMethod::SubType, CCopasiMethod * >::const_iterator found = mMethodHistory.find(Type);
   if (found != mMethodHistory.end())
     {
       return found->second;
     }
   return NULL;
 }
bool CQTaskMethodWidget::loadMethod ()
Definition at line 134 of file CQTaskMethodWidget.cpp.
References C_INT32, FROM_UTF8, CCopasiParameterGroup::getName(), getParameterValue(), CCopasiMethod::getSubType(), mpActiveMethod, mpTask, mShowMethodParameters, mShowMethods, CCopasiParameterGroup::size(), and CCopasiMethod::SubTypeName.
Referenced by changeMethod(), and TaskWidget::loadMethod().
 {
   if (!mpTask) return false;
   if (!mpActiveMethod) return false;
   if (mShowMethods)
     {
       mpBoxMethod->setCurrentIndex(mpBoxMethod->findText(FROM_UTF8(CCopasiMethod::SubTypeName[mpActiveMethod->getSubType()])));
     }
   if (mShowMethodParameters)
     {
       QString Value;
       mpTableParameter->setRowCount((int) mpActiveMethod->size());
       unsigned C_INT32 i;
       CCopasiParameter::Type Type;
       for (i = 0; i < mpActiveMethod->size(); i++)
         {
           // create item of the current row and give it a name
           mpTableParameter->setVerticalHeaderItem(i, new QTableWidgetItem());
           mpTableParameter->verticalHeaderItem(i)->setText(FROM_UTF8(mpActiveMethod->getName(i)));
           Value = getParameterValue(mpActiveMethod, i, &Type);
           QTableWidgetItem *pValueItem = new QTableWidgetItem();
           pValueItem->setData(Qt::EditRole, QVariant(Value));
           pValueItem->setTextAlignment(Qt::AlignRight);
           mpTableParameter->setItem(i, 0, pValueItem);
         }
     }
   mpTableParameter->resizeColumnsToContents();
   return true;
 }
void CQTaskMethodWidget::removeFromHistory (CCopasiMethod * pMethod) protected
Definition at line 247 of file CQTaskMethodWidget.cpp.
References CCopasiMethod::getSubType(), and mMethodHistory.
 {
   if (pMethod == NULL)
     {
       return;
     }
   std::map< CCopasiMethod::SubType, CCopasiMethod * >::iterator found = mMethodHistory.find(pMethod->getSubType());
   if (found != mMethodHistory.end())
     {
       mMethodHistory.erase(found);
     }
 }
bool CQTaskMethodWidget::saveMethod ()
Definition at line 174 of file CQTaskMethodWidget.cpp.
References C_INT32, CCopasiTask::getMethod(), getParameterValue(), CCopasiMethod::getSubType(), mpActiveMethod, mpMethod, mpTask, mShowMethodParameters, mShowMethods, CCopasiTask::setMethodType(), setParameterValue(), and CCopasiParameterGroup::size().
Referenced by TaskWidget::saveMethod().
 {
   if (!mpTask) return false;
   const CCopasiMethod * pMethod = mpTask->getMethod();
   if (!pMethod) return false;
   bool changed = false;
   if (mShowMethods)
     {
       if (pMethod->getSubType() != mpActiveMethod->getSubType())
         {
           mpTask->setMethodType(mpActiveMethod->getSubType());
           mpMethod = mpTask->getMethod();
           changed = true;
         }
     }
   if (mShowMethodParameters)
     {
       unsigned C_INT32 i;
       QString Value;
       CCopasiParameter::Type Type;
       for (i = 0; i < mpActiveMethod->size(); i++)
         {
           if (!mpTableParameter->item(i, 0))
             continue;
           Value = mpTableParameter->item(i, 0)->text();
           if (Value != getParameterValue(mpActiveMethod, i, &Type))
             {
               setParameterValue(mpActiveMethod, i, Value);
               changed = true;
             }
         }
     }
   if (changed)
     {
       *mpMethod = *mpActiveMethod;
     }
   return changed;
 }
void CQTaskMethodWidget::setActiveMethod (const CCopasiMethod::SubType & Type) protected
Definition at line 274 of file CQTaskMethodWidget.cpp.
References addToHistory(), CCopasiTask::createMethod(), getFromHistory(), mpActiveMethod, and mpTask.
Referenced by changeMethod(), and setTask().
 {
   mpActiveMethod = getFromHistory(Type);
   if (mpActiveMethod == NULL)
     {
       mpActiveMethod = mpTask->createMethod(Type);
       addToHistory(mpActiveMethod);
     }
   assert(mpActiveMethod != NULL);
   return;
 }
void CQTaskMethodWidget::setTask (CCopasiTask * pTask)
Definition at line 72 of file CQTaskMethodWidget.cpp.
References CCopasiTask::getMethod(), CCopasiMethod::getSubType(), mpActiveMethod, mpMethod, mpTask, pTask, and setActiveMethod().
Referenced by TaskWidget::loadMethod().
 {
   mpTask = pTask;
   if (mpTask != NULL)
     {
       mpMethod = mpTask->getMethod();
       if (mpMethod != NULL)
         {
           setActiveMethod(mpMethod->getSubType());
           *mpActiveMethod = *mpMethod;
         }
     }
   else
     {
       mpMethod = NULL;
       mpActiveMethod = NULL;
     }
 }
void CQTaskMethodWidget::setValidMethods (const unsigned int * validMethods)
Definition at line 93 of file CQTaskMethodWidget.cpp.
References C_INT32, changeMethod(), FROM_UTF8, mShowMethods, CCopasiMethod::SubTypeName, and CCopasiMethod::unset.
Referenced by CQFittingWidget::init(), CQTSSAWidget::init(), CQOptimizationWidget::init(), and CQTrajectoryWidget::init().
 {
   unsigned C_INT32 i;
   for (i = 0; validMethods[i] != CCopasiMethod::unset; i++)
     mpBoxMethod->insertItem(mpBoxMethod->count(), FROM_UTF8(CCopasiMethod::SubTypeName[validMethods[i]]));
   if (i > 0)
     {
       mShowMethods = true;
       mpLblMethod->show();
       mpBoxMethod->show();
       connect(mpBoxMethod, SIGNAL(activated(int)), this, SLOT(changeMethod(int)));
     }
   else
     {
       mShowMethods = false;
       mpLblMethod->hide();
       mpBoxMethod->hide();
       disconnect(mpBoxMethod, SIGNAL(activated(int)), this, SLOT(changeMethod(int)));
     }
 }
void CQTaskMethodWidget::showMethodParameters (const bool & show)
Definition at line 118 of file CQTaskMethodWidget.cpp.
References mShowMethodParameters.
Referenced by CQCrossSectionTaskWidget::init(), CQLyapWidget::init(), CQMCAWidget::init(), CQLNAWidget::init(), SensitivitiesWidget::init(), SteadyStateWidget::init(), CQFittingWidget::init(), CQOptimizationWidget::init(), CQTSSAWidget::init(), and CQTrajectoryWidget::init().
 {
   mShowMethodParameters = show;
   if (mShowMethodParameters)
     {
       mpLblParameter->show();
       mpTableParameter->show();
     }
   else
     {
       mpLblParameter->hide();
       mpTableParameter->hide();
     }
 }
Member Data Documentation
std::map< CCopasiMethod::SubType, CCopasiMethod * > CQTaskMethodWidget::mMethodHistory protected
Definition at line 51 of file CQTaskMethodWidget.h.
Referenced by addToHistory(), clearHistory(), getFromHistory(), and removeFromHistory().
CCopasiMethod* CQTaskMethodWidget::mpActiveMethod protected
Definition at line 50 of file CQTaskMethodWidget.h.
Referenced by changeMethod(), loadMethod(), saveMethod(), setActiveMethod(), and setTask().
CCopasiMethod* CQTaskMethodWidget::mpMethod protected
Definition at line 49 of file CQTaskMethodWidget.h.
Referenced by saveMethod(), and setTask().
CCopasiTask* CQTaskMethodWidget::mpTask protected
Definition at line 48 of file CQTaskMethodWidget.h.
Referenced by changeMethod(), loadMethod(), saveMethod(), setActiveMethod(), and setTask().
bool CQTaskMethodWidget::mShowMethodParameters protected
Definition at line 53 of file CQTaskMethodWidget.h.
Referenced by changeMethod(), loadMethod(), saveMethod(), and showMethodParameters().
bool CQTaskMethodWidget::mShowMethods protected
Definition at line 52 of file CQTaskMethodWidget.h.
Referenced by loadMethod(), saveMethod(), and setValidMethods().
The documentation for this class was generated from the following files:
CQTaskMethodWidget.h
CQTaskMethodWidget.cpp