COPASI API: MiriamWebServicesSoapBindingProxy Class Reference
MiriamWebServicesSoapBindingProxy Class Reference
#include <soapMiriamWebServicesSoapBindingProxy.h>
Public Member Functions
virtual int checkRegExp (std::string _identifier, std::string _datatype, std::string &_checkRegExpReturn)
Web service operation 'checkRegExp' (returns error code or SOAP_OK)
virtual int getDataResources (std::string _nickname, struct ns2__getDataResourcesResponse &_param_1)
Web service operation 'getDataResources' (returns error code or SOAP_OK)
virtual int getDataTypeDef (std::string _nickname, std::string &_getDataTypeDefReturn)
Web service operation 'getDataTypeDef' (returns error code or SOAP_OK)
virtual int getDataTypePattern (std::string _nickname, std::string &_getDataTypePatternReturn)
Web service operation 'getDataTypePattern' (returns error code or SOAP_OK)
virtual int getDataTypesId (struct ns2__getDataTypesIdResponse &_param_8)
Web service operation 'getDataTypesId' (returns error code or SOAP_OK)
virtual int getDataTypesName (struct ns2__getDataTypesNameResponse &_param_7)
Web service operation 'getDataTypesName' (returns error code or SOAP_OK)
virtual int getDataTypeSynonyms (std::string _name, struct ns2__getDataTypeSynonymsResponse &_param_5)
Web service operation 'getDataTypeSynonyms' (returns error code or SOAP_OK)
virtual int getDataTypeURI (std::string _name, std::string &_getDataTypeURIReturn)
Web service operation 'getDataTypeURI' (returns error code or SOAP_OK)
virtual int getDataTypeURIs (std::string _name, struct ns2__getDataTypeURIsResponse &_param_2)
Web service operation 'getDataTypeURIs' (returns error code or SOAP_OK)
virtual int getJavaLibraryVersion (std::string &getJavaLibraryVersionReturn)
Web service operation 'getJavaLibraryVersion' (returns error code or SOAP_OK)
virtual int getLocation (std::string _uri, std::string _resource, std::string &_getLocationReturn)
Web service operation 'getLocation' (returns error code or SOAP_OK)
virtual int getLocations (std::string _nickname, std::string _id, struct ns2__getLocationsResponse &_param_3)
Web service operation 'getLocations' (returns error code or SOAP_OK)
virtual int getLocations_ (std::string _nickname, std::string _id, struct ns2__getLocationsResponse_ &_param_4)
Web service operation 'getLocations' (returns error code or SOAP_OK)
virtual int getMiriamURI (std::string _uri, std::string &_getMiriamURIReturn)
Web service operation 'getMiriamURI' (returns error code or SOAP_OK)
virtual int getName (std::string _uri, std::string &_getNameReturn)
Web service operation 'getName' (returns error code or SOAP_OK)
virtual int getNames (std::string _uri, struct ns2__getNamesResponse &_param_6)
Web service operation 'getNames' (returns error code or SOAP_OK)
virtual int getOfficialDataTypeURI (std::string _uri, std::string &_getOfficialDataTypeURIReturn)
Web service operation 'getOfficialDataTypeURI' (returns error code or SOAP_OK)
virtual int getResourceInfo (std::string _id, std::string &_getResourceInfoReturn)
Web service operation 'getResourceInfo' (returns error code or SOAP_OK)
virtual int getResourceInstitution (std::string _id, std::string &_getResourceInstitutionReturn)
Web service operation 'getResourceInstitution' (returns error code or SOAP_OK)
virtual int getResourceLocation (std::string _id, std::string &_getResourceLocationReturn)
Web service operation 'getResourceLocation' (returns error code or SOAP_OK)
virtual int getServicesInfo (std::string &getServicesInfoReturn)
Web service operation 'getServicesInfo' (returns error code or SOAP_OK)
virtual int getServicesVersion (std::string &getServicesVersionReturn)
Web service operation 'getServicesVersion' (returns error code or SOAP_OK)
virtual int getURI (std::string _name, std::string _id, std::string &_getURIReturn)
Web service operation 'getURI' (returns error code or SOAP_OK)
virtual int isDeprecated (std::string _uri, std::string &_isDeprecatedReturn)
Web service operation 'isDeprecated' (returns error code or SOAP_OK)
MiriamWebServicesSoapBindingProxy ()
Constructor.
MiriamWebServicesSoapBindingProxy (const struct soap &)
Constructor with copy of another engine state.
MiriamWebServicesSoapBindingProxy (soap_mode iomode)
Constructor with engine input+output mode control.
MiriamWebServicesSoapBindingProxy (soap_mode imode, soap_mode omode)
Constructor with engine input and output mode control.
virtual void MiriamWebServicesSoapBindingProxy_init (soap_mode imode, soap_mode omode)
Initializer used by constructor.
virtual int soap_close_socket ()
Force close connection (normally automatic, except for send_X ops)
virtual const SOAP_ENV__Fault * soap_fault ()
Get SOAP Fault structure (NULL when absent)
virtual const char * soap_fault_detail ()
Get SOAP Fault detail as string (NULL when absent)
virtual const char * soap_fault_string ()
Get SOAP Fault string (NULL when absent)
virtual void soap_noheader ()
Disables and removes SOAP Header from message.
virtual void soap_print_fault (FILE *)
Print fault.
virtual char * soap_sprint_fault (char *buf, size_t len)
Put fault into buffer.
virtual void soap_stream_fault (std::ostream &)
Print fault to stream.
virtual ~MiriamWebServicesSoapBindingProxy ()
Destructor frees deserialized data.
Public Attributes
const char * soap_endpoint
Endpoint URL of service 'MiriamWebServicesSoapBindingProxy' (change as needed)
Public Attributes inherited from soap
int accept_flags
int accept_timeout
char * action
const char * actor
soap_wchar ahead
void * alist
short alloced
char arrayOffset [(1024)]
char arraySize [(1024)]
char arrayType [(1024)]
struct soap_attribute * attributes
char * authrealm
int bind_flags
void * bio
struct soap_blist * blist
short body
char buf [(65536)]
size_t bufidx
size_t buflen
const char * c14nexclude
const char * c14ninclude
void * c_locale
const char * cafile
const char * capath
short cdata
size_t chunkbuflen
size_t chunksize
struct soap_clist * clist
int connect_flags
int connect_timeout
const char * cookie_domain
int cookie_max
const char * cookie_path
struct soap_cookie * cookies
size_t count
const char * crlfile
void * ctx
void * d_stream
const char * dhfile
struct soap_dime dime
const char * dime_id_format
struct soap_dom_element * dom
const char * double_format
void(* dummy)()
short encoding
const char * encodingStyle
char endpoint [(1024)]
int errmode
int errnum
int error
int(* faccept)(struct soap *, int, struct sockaddr *, int *n)
struct SOAP_ENV__Fault * fault
int(* fclose)(struct soap *)
int(* fclosesocket)(struct soap *, int)
int(* fconnect)(struct soap *, const char *, const char *, int)
FILE * fdebug [(3)]
int(* fdel)(struct soap *)
size_t(* fdimeread)(struct soap *, void *, char *, size_t)
void(* fdimereadclose)(struct soap *, void *)
void *(* fdimereadopen)(struct soap *, void *, const char *, const char *, const char *)
int(* fdimewrite)(struct soap *, void *, const char *, size_t)
void(* fdimewriteclose)(struct soap *, void *)
void *(* fdimewriteopen)(struct soap *, const char *, const char *, const char *)
int(* fdisconnect)(struct soap *)
int(* fform)(struct soap *)
int(* fget)(struct soap *)
int(* fhead)(struct soap *)
int(* fheader)(struct soap *)
int(* fignore)(struct soap *, const char *)
const char * float_format
void *(* fmalloc)(struct soap *, size_t)
size_t(* fmimeread)(struct soap *, void *, char *, size_t)
void(* fmimereadclose)(struct soap *, void *)
void *(* fmimereadopen)(struct soap *, void *, const char *, const char *, const char *)
int(* fmimewrite)(struct soap *, void *, const char *, size_t)
void(* fmimewriteclose)(struct soap *, void *)
void *(* fmimewriteopen)(struct soap *, void *, const char *, const char *, const char *, enum soap_mime_encoding)
int(* fopen)(struct soap *, const char *, const char *, int)
int(* fparse)(struct soap *)
int(* fparsehdr)(struct soap *, const char *, const char *)
void *(* fplugin)(struct soap *, const char *)
int(* fpoll)(struct soap *)
int(* fpost)(struct soap *, const char *, const char *, int, const char *, const char *, size_t)
int(* fposthdr)(struct soap *, const char *, const char *)
int(* fpreparefinal)(struct soap *)
int(* fprepareinit)(struct soap *)
int(* fpreparerecv)(struct soap *, const char *, size_t)
int(* fpreparesend)(struct soap *, const char *, size_t)
int(* fput)(struct soap *)
size_t(* frecv)(struct soap *, char *, size_t)
int(* fresolve)(struct soap *, const char *, struct in_addr *inaddr)
int(* fresponse)(struct soap *, int, size_t)
int(* fsend)(struct soap *, const char *, size_t)
int(* fserveloop)(struct soap *)
void(* fseterror)(struct soap *, const char **c, const char **s)
int(* fshutdownsocket)(struct soap *, int, int)
void * fsslauth
void * fsslverify
struct SOAP_ENV__Header * header
char host [(1024)]
char href [(1024)]
const char * http_content
const char * http_version
char id [(1024)]
int idnum
struct soap_ilist * iht [(1999)]
soap_mode imode
unsigned long ip
char * ipv4_multicast_if
int ipv4_multicast_ttl
int ipv6_multicast_if
void * is
short keep_alive
const char * keyfile
char * labbuf
size_t labidx
size_t lablen
const char * lang
size_t length
unsigned int level
unsigned short linger_time
struct Namespace * local_namespaces
const char * logfile [(3)]
int master
unsigned int max_keep_alive
struct soap_mlist * mht [(1024)]
struct soap_mime mime
soap_mode mode
char msgbuf [1024]
short mustUnderstand
const struct Namespace * namespaces
struct soap_nlist * nlist
short ns
short null
soap_mode omode
void * os
short other
short part
char * passwd
const char * password
char path [(1024)]
struct soap_pblk * pblk
short peeked
struct sockaddr_in peer
size_t peerlen
struct soap_plist * pht [(1024)]
short pidx
struct soap_plugin * plugins
int port
short position
int positions [(16)]
char * prolog
const char * proxy_from
const char * proxy_host
const char * proxy_http_version
const char * proxy_passwd
int proxy_port
const char * proxy_userid
const char * randfile
int recv_timeout
int recvfd
short root
int send_timeout
int sendfd
void * session
char session_host [(1024)]
int session_port
int socket
int socket_flags
void * ssl
unsigned short ssl_flags
short state
int status
char tag [(1024)]
short tcp_keep_alive
unsigned int tcp_keep_cnt
unsigned int tcp_keep_idle
unsigned int tcp_keep_intvl
char tmpbuf [1024]
char type [(1024)]
void * user
char * userid
short version
struct soap_xlist * xlist
char * z_buf
size_t z_buflen
int32_t z_crc
unsigned short z_level
float z_ratio_in
float z_ratio_out
short zlib_in
short zlib_out
short zlib_state
Detailed Description
Definition at line 25 of file soapMiriamWebServicesSoapBindingProxy.h.
Constructor & Destructor Documentation
MiriamWebServicesSoapBindingProxy::MiriamWebServicesSoapBindingProxy ()
Constructor.
Definition at line 20 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References MiriamWebServicesSoapBindingProxy_init(), and SOAP_IO_DEFAULT.
 {
   MiriamWebServicesSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
 }
MiriamWebServicesSoapBindingProxy::MiriamWebServicesSoapBindingProxy (const struct soap & soap)
Constructor with copy of another engine state.
Definition at line 25 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::imode, MiriamWebServicesSoapBindingProxy_init(), soap::omode, and soap_copy_context().
 {
   soap_copy_context(this, &soap);
   MiriamWebServicesSoapBindingProxy_init(soap.imode, soap.omode);
 }
MiriamWebServicesSoapBindingProxy::MiriamWebServicesSoapBindingProxy (soap_mode iomode)
Constructor with engine input+output mode control.
Definition at line 31 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References MiriamWebServicesSoapBindingProxy_init().
 {
   MiriamWebServicesSoapBindingProxy_init(iomode, iomode);
 }
MiriamWebServicesSoapBindingProxy::MiriamWebServicesSoapBindingProxy (soap_mode imode, soap_mode omode)
Constructor with engine input and output mode control.
Definition at line 36 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References MiriamWebServicesSoapBindingProxy_init().
 {
   MiriamWebServicesSoapBindingProxy_init(imode, omode);
 }
MiriamWebServicesSoapBindingProxy::~MiriamWebServicesSoapBindingProxy () virtual
Destructor frees deserialized data.
Definition at line 60 of file soapMiriamWebServicesSoapBindingProxy.cpp.
 {}
Member Function Documentation
int MiriamWebServicesSoapBindingProxy::checkRegExp (std::string _identifier, std::string _datatype, std::string & _checkRegExpReturn) virtual
Web service operation 'checkRegExp' (returns error code or SOAP_OK)
Definition at line 1790 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__checkRegExpResponse::_checkRegExpReturn, ns2__checkRegExp::_datatype, ns2__checkRegExp::_identifier, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__checkRegExpResponse(), SOAP_IO_LENGTH, soap_put_ns2__checkRegExp(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__checkRegExp(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__checkRegExp soap_tmp_ns2__checkRegExp;
   struct ns2__checkRegExpResponse *soap_tmp_ns2__checkRegExpResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__checkRegExp._identifier = _identifier;
   soap_tmp_ns2__checkRegExp._datatype = _datatype;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__checkRegExp(soap, &soap_tmp_ns2__checkRegExp);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__checkRegExp(soap, &soap_tmp_ns2__checkRegExp, "ns2:checkRegExp", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__checkRegExp(soap, &soap_tmp_ns2__checkRegExp, "ns2:checkRegExp", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_checkRegExpReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_checkRegExpReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__checkRegExpResponse = soap_get_ns2__checkRegExpResponse(soap, NULL, "ns2:checkRegExpResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _checkRegExpReturn = soap_tmp_ns2__checkRegExpResponse->_checkRegExpReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataResources (std::string _nickname, struct ns2__getDataResourcesResponse & _param_1) virtual
Web service operation 'getDataResources' (returns error code or SOAP_OK)
Definition at line 329 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getDataResources::_nickname, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getDataResourcesResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataResourcesResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataResources(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataResources(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getDataResources soap_tmp_ns2__getDataResources;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getDataResources._nickname = _nickname;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataResources(soap, &soap_tmp_ns2__getDataResources);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataResources(soap, &soap_tmp_ns2__getDataResources, "ns2:getDataResources", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataResources(soap, &soap_tmp_ns2__getDataResources, "ns2:getDataResources", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_1)
     return soap_closesock(soap);
   soap_default_ns2__getDataResourcesResponse(soap, &_param_1);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getDataResourcesResponse(soap, &_param_1, "ns2:getDataResourcesResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypeDef (std::string _nickname, std::string & _getDataTypeDefReturn) virtual
Web service operation 'getDataTypeDef' (returns error code or SOAP_OK)
Definition at line 766 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getDataTypeDefResponse::_getDataTypeDefReturn, ns2__getDataTypeDef::_nickname, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypeDefResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypeDef(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypeDef(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getDataTypeDef soap_tmp_ns2__getDataTypeDef;
   struct ns2__getDataTypeDefResponse *soap_tmp_ns2__getDataTypeDefResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getDataTypeDef._nickname = _nickname;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypeDef(soap, &soap_tmp_ns2__getDataTypeDef);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypeDef(soap, &soap_tmp_ns2__getDataTypeDef, "ns2:getDataTypeDef", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypeDef(soap, &soap_tmp_ns2__getDataTypeDef, "ns2:getDataTypeDef", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getDataTypeDefReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getDataTypeDefReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getDataTypeDefResponse = soap_get_ns2__getDataTypeDefResponse(soap, NULL, "ns2:getDataTypeDefResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getDataTypeDefReturn = soap_tmp_ns2__getDataTypeDefResponse->_getDataTypeDefReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypePattern (std::string _nickname, std::string & _getDataTypePatternReturn) virtual
Web service operation 'getDataTypePattern' (returns error code or SOAP_OK)
Definition at line 1208 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getDataTypePatternResponse::_getDataTypePatternReturn, ns2__getDataTypePattern::_nickname, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypePatternResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypePattern(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypePattern(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
Referenced by CMIRIAMResources::updateMIRIAMResources().
 {
   struct soap *soap = this;
   struct ns2__getDataTypePattern soap_tmp_ns2__getDataTypePattern;
   struct ns2__getDataTypePatternResponse *soap_tmp_ns2__getDataTypePatternResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getDataTypePattern._nickname = _nickname;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypePattern(soap, &soap_tmp_ns2__getDataTypePattern);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypePattern(soap, &soap_tmp_ns2__getDataTypePattern, "ns2:getDataTypePattern", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypePattern(soap, &soap_tmp_ns2__getDataTypePattern, "ns2:getDataTypePattern", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getDataTypePatternReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getDataTypePatternReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getDataTypePatternResponse = soap_get_ns2__getDataTypePatternResponse(soap, NULL, "ns2:getDataTypePatternResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getDataTypePatternReturn = soap_tmp_ns2__getDataTypePatternResponse->_getDataTypePatternReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypesId (struct ns2__getDataTypesIdResponse & _param_8) virtual
Web service operation 'getDataTypesId' (returns error code or SOAP_OK)
Definition at line 1719 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getDataTypesIdResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypesIdResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypesId(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypesId(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getDataTypesId soap_tmp_ns2__getDataTypesId;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypesId(soap, &soap_tmp_ns2__getDataTypesId);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypesId(soap, &soap_tmp_ns2__getDataTypesId, "ns2:getDataTypesId", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypesId(soap, &soap_tmp_ns2__getDataTypesId, "ns2:getDataTypesId", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_8)
     return soap_closesock(soap);
   soap_default_ns2__getDataTypesIdResponse(soap, &_param_8);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getDataTypesIdResponse(soap, &_param_8, "ns2:getDataTypesIdResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypesName (struct ns2__getDataTypesNameResponse & _param_7) virtual
Web service operation 'getDataTypesName' (returns error code or SOAP_OK)
Definition at line 1648 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getDataTypesNameResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypesNameResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypesName(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypesName(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
Referenced by CMIRIAMResources::updateMIRIAMResources().
 {
   struct soap *soap = this;
   struct ns2__getDataTypesName soap_tmp_ns2__getDataTypesName;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypesName(soap, &soap_tmp_ns2__getDataTypesName);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypesName(soap, &soap_tmp_ns2__getDataTypesName, "ns2:getDataTypesName", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypesName(soap, &soap_tmp_ns2__getDataTypesName, "ns2:getDataTypesName", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_7)
     return soap_closesock(soap);
   soap_default_ns2__getDataTypesNameResponse(soap, &_param_7);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getDataTypesNameResponse(soap, &_param_7, "ns2:getDataTypesNameResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypeSynonyms (std::string _name, struct ns2__getDataTypeSynonymsResponse & _param_5) virtual
Web service operation 'getDataTypeSynonyms' (returns error code or SOAP_OK)
Definition at line 1504 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getDataTypeSynonyms::_name, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getDataTypeSynonymsResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypeSynonymsResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypeSynonyms(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypeSynonyms(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getDataTypeSynonyms soap_tmp_ns2__getDataTypeSynonyms;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getDataTypeSynonyms._name = _name;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypeSynonyms(soap, &soap_tmp_ns2__getDataTypeSynonyms);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypeSynonyms(soap, &soap_tmp_ns2__getDataTypeSynonyms, "ns2:getDataTypeSynonyms", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypeSynonyms(soap, &soap_tmp_ns2__getDataTypeSynonyms, "ns2:getDataTypeSynonyms", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_5)
     return soap_closesock(soap);
   soap_default_ns2__getDataTypeSynonymsResponse(soap, &_param_5);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getDataTypeSynonymsResponse(soap, &_param_5, "ns2:getDataTypeSynonymsResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypeURI (std::string _name, std::string & _getDataTypeURIReturn) virtual
Web service operation 'getDataTypeURI' (returns error code or SOAP_OK)
Definition at line 620 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getDataTypeURIResponse::_getDataTypeURIReturn, ns2__getDataTypeURI::_name, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypeURIResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypeURI(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypeURI(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
Referenced by CMIRIAMResources::updateMIRIAMResources().
 {
   struct soap *soap = this;
   struct ns2__getDataTypeURI soap_tmp_ns2__getDataTypeURI;
   struct ns2__getDataTypeURIResponse *soap_tmp_ns2__getDataTypeURIResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getDataTypeURI._name = _name;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypeURI(soap, &soap_tmp_ns2__getDataTypeURI);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypeURI(soap, &soap_tmp_ns2__getDataTypeURI, "ns2:getDataTypeURI", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypeURI(soap, &soap_tmp_ns2__getDataTypeURI, "ns2:getDataTypeURI", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getDataTypeURIReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getDataTypeURIReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getDataTypeURIResponse = soap_get_ns2__getDataTypeURIResponse(soap, NULL, "ns2:getDataTypeURIResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getDataTypeURIReturn = soap_tmp_ns2__getDataTypeURIResponse->_getDataTypeURIReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getDataTypeURIs (std::string _name, struct ns2__getDataTypeURIsResponse & _param_2) virtual
Web service operation 'getDataTypeURIs' (returns error code or SOAP_OK)
Definition at line 694 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getDataTypeURIs::_name, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getDataTypeURIsResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getDataTypeURIsResponse(), SOAP_IO_LENGTH, soap_put_ns2__getDataTypeURIs(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getDataTypeURIs(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
Referenced by CMIRIAMResources::updateMIRIAMResources().
 {
   struct soap *soap = this;
   struct ns2__getDataTypeURIs soap_tmp_ns2__getDataTypeURIs;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getDataTypeURIs._name = _name;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getDataTypeURIs(soap, &soap_tmp_ns2__getDataTypeURIs);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getDataTypeURIs(soap, &soap_tmp_ns2__getDataTypeURIs, "ns2:getDataTypeURIs", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getDataTypeURIs(soap, &soap_tmp_ns2__getDataTypeURIs, "ns2:getDataTypeURIs", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_2)
     return soap_closesock(soap);
   soap_default_ns2__getDataTypeURIsResponse(soap, &_param_2);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getDataTypeURIsResponse(soap, &_param_2, "ns2:getDataTypeURIsResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getJavaLibraryVersion (std::string & getJavaLibraryVersionReturn) virtual
Web service operation 'getJavaLibraryVersion' (returns error code or SOAP_OK)
Definition at line 547 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::encodingStyle, soap::error, ns2__getJavaLibraryVersionResponse::getJavaLibraryVersionReturn, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getJavaLibraryVersionResponse(), SOAP_IO_LENGTH, soap_put_ns2__getJavaLibraryVersion(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getJavaLibraryVersion(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getJavaLibraryVersion soap_tmp_ns2__getJavaLibraryVersion;
   struct ns2__getJavaLibraryVersionResponse *soap_tmp_ns2__getJavaLibraryVersionResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getJavaLibraryVersion(soap, &soap_tmp_ns2__getJavaLibraryVersion);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getJavaLibraryVersion(soap, &soap_tmp_ns2__getJavaLibraryVersion, "ns2:getJavaLibraryVersion", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getJavaLibraryVersion(soap, &soap_tmp_ns2__getJavaLibraryVersion, "ns2:getJavaLibraryVersion", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&getJavaLibraryVersionReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &getJavaLibraryVersionReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getJavaLibraryVersionResponse = soap_get_ns2__getJavaLibraryVersionResponse(soap, NULL, "ns2:getJavaLibraryVersionResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   getJavaLibraryVersionReturn = soap_tmp_ns2__getJavaLibraryVersionResponse->getJavaLibraryVersionReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getLocation (std::string _uri, std::string _resource, std::string & _getLocationReturn) virtual
Web service operation 'getLocation' (returns error code or SOAP_OK)
Definition at line 179 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getLocationResponse::_getLocationReturn, ns2__getLocation::_resource, ns2__getLocation::_uri, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getLocationResponse(), SOAP_IO_LENGTH, soap_put_ns2__getLocation(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getLocation(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getLocation soap_tmp_ns2__getLocation;
   struct ns2__getLocationResponse *soap_tmp_ns2__getLocationResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getLocation._uri = _uri;
   soap_tmp_ns2__getLocation._resource = _resource;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getLocation(soap, &soap_tmp_ns2__getLocation);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getLocation(soap, &soap_tmp_ns2__getLocation, "ns2:getLocation", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getLocation(soap, &soap_tmp_ns2__getLocation, "ns2:getLocation", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getLocationReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getLocationReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getLocationResponse = soap_get_ns2__getLocationResponse(soap, NULL, "ns2:getLocationResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getLocationReturn = soap_tmp_ns2__getLocationResponse->_getLocationReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getLocations (std::string _nickname, std::string _id, struct ns2__getLocationsResponse & _param_3) virtual
Web service operation 'getLocations' (returns error code or SOAP_OK)
Definition at line 840 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getLocations::_id, ns2__getLocations::_nickname, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getLocationsResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getLocationsResponse(), SOAP_IO_LENGTH, soap_put_ns2__getLocations(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getLocations(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getLocations soap_tmp_ns2__getLocations;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getLocations._nickname = _nickname;
   soap_tmp_ns2__getLocations._id = _id;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getLocations(soap, &soap_tmp_ns2__getLocations);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getLocations(soap, &soap_tmp_ns2__getLocations, "ns2:getLocations", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getLocations(soap, &soap_tmp_ns2__getLocations, "ns2:getLocations", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_3)
     return soap_closesock(soap);
   soap_default_ns2__getLocationsResponse(soap, &_param_3);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getLocationsResponse(soap, &_param_3, "ns2:getLocationsResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getLocations_ (std::string _nickname, std::string _id, struct ns2__getLocationsResponse_ & _param_4) virtual
Web service operation 'getLocations' (returns error code or SOAP_OK)
Definition at line 913 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getLocations_::_id, ns2__getLocations_::_nickname, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getLocationsResponse_(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getLocationsResponse_(), SOAP_IO_LENGTH, soap_put_ns2__getLocations_(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getLocations_(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getLocations_ soap_tmp_ns2__getLocations_;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getLocations_._nickname = _nickname;
   soap_tmp_ns2__getLocations_._id = _id;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getLocations_(soap, &soap_tmp_ns2__getLocations_);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getLocations_(soap, &soap_tmp_ns2__getLocations_, "ns2:getLocations", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getLocations_(soap, &soap_tmp_ns2__getLocations_, "ns2:getLocations", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_4)
     return soap_closesock(soap);
   soap_default_ns2__getLocationsResponse_(soap, &_param_4);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getLocationsResponse_(soap, &_param_4, "ns2:getLocationsResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getMiriamURI (std::string _uri, std::string & _getMiriamURIReturn) virtual
Web service operation 'getMiriamURI' (returns error code or SOAP_OK)
Definition at line 1134 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getMiriamURIResponse::_getMiriamURIReturn, ns2__getMiriamURI::_uri, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getMiriamURIResponse(), SOAP_IO_LENGTH, soap_put_ns2__getMiriamURI(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getMiriamURI(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getMiriamURI soap_tmp_ns2__getMiriamURI;
   struct ns2__getMiriamURIResponse *soap_tmp_ns2__getMiriamURIResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getMiriamURI._uri = _uri;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getMiriamURI(soap, &soap_tmp_ns2__getMiriamURI);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getMiriamURI(soap, &soap_tmp_ns2__getMiriamURI, "ns2:getMiriamURI", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getMiriamURI(soap, &soap_tmp_ns2__getMiriamURI, "ns2:getMiriamURI", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getMiriamURIReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getMiriamURIReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getMiriamURIResponse = soap_get_ns2__getMiriamURIResponse(soap, NULL, "ns2:getMiriamURIResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getMiriamURIReturn = soap_tmp_ns2__getMiriamURIResponse->_getMiriamURIReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getName (std::string _uri, std::string & _getNameReturn) virtual
Web service operation 'getName' (returns error code or SOAP_OK)
Definition at line 105 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getNameResponse::_getNameReturn, ns2__getName::_uri, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getNameResponse(), SOAP_IO_LENGTH, soap_put_ns2__getName(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getName(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getName soap_tmp_ns2__getName;
   struct ns2__getNameResponse *soap_tmp_ns2__getNameResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getName._uri = _uri;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getName(soap, &soap_tmp_ns2__getName);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getName(soap, &soap_tmp_ns2__getName, "ns2:getName", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getName(soap, &soap_tmp_ns2__getName, "ns2:getName", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getNameReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getNameReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getNameResponse = soap_get_ns2__getNameResponse(soap, NULL, "ns2:getNameResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getNameReturn = soap_tmp_ns2__getNameResponse->_getNameReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getNames (std::string _uri, struct ns2__getNamesResponse & _param_6) virtual
Web service operation 'getNames' (returns error code or SOAP_OK)
Definition at line 1576 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getNames::_uri, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_ns2__getNamesResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getNamesResponse(), SOAP_IO_LENGTH, soap_put_ns2__getNames(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getNames(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getNames soap_tmp_ns2__getNames;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getNames._uri = _uri;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getNames(soap, &soap_tmp_ns2__getNames);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getNames(soap, &soap_tmp_ns2__getNames, "ns2:getNames", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getNames(soap, &soap_tmp_ns2__getNames, "ns2:getNames", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_param_6)
     return soap_closesock(soap);
   soap_default_ns2__getNamesResponse(soap, &_param_6);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_get_ns2__getNamesResponse(soap, &_param_6, "ns2:getNamesResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getOfficialDataTypeURI (std::string _uri, std::string & _getOfficialDataTypeURIReturn) virtual
Web service operation 'getOfficialDataTypeURI' (returns error code or SOAP_OK)
Definition at line 1060 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getOfficialDataTypeURIResponse::_getOfficialDataTypeURIReturn, ns2__getOfficialDataTypeURI::_uri, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getOfficialDataTypeURIResponse(), SOAP_IO_LENGTH, soap_put_ns2__getOfficialDataTypeURI(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getOfficialDataTypeURI(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getOfficialDataTypeURI soap_tmp_ns2__getOfficialDataTypeURI;
   struct ns2__getOfficialDataTypeURIResponse *soap_tmp_ns2__getOfficialDataTypeURIResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getOfficialDataTypeURI._uri = _uri;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getOfficialDataTypeURI(soap, &soap_tmp_ns2__getOfficialDataTypeURI);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getOfficialDataTypeURI(soap, &soap_tmp_ns2__getOfficialDataTypeURI, "ns2:getOfficialDataTypeURI", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getOfficialDataTypeURI(soap, &soap_tmp_ns2__getOfficialDataTypeURI, "ns2:getOfficialDataTypeURI", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getOfficialDataTypeURIReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getOfficialDataTypeURIReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getOfficialDataTypeURIResponse = soap_get_ns2__getOfficialDataTypeURIResponse(soap, NULL, "ns2:getOfficialDataTypeURIResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getOfficialDataTypeURIReturn = soap_tmp_ns2__getOfficialDataTypeURIResponse->_getOfficialDataTypeURIReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getResourceInfo (std::string _id, std::string & _getResourceInfoReturn) virtual
Web service operation 'getResourceInfo' (returns error code or SOAP_OK)
Definition at line 1282 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getResourceInfoResponse::_getResourceInfoReturn, ns2__getResourceInfo::_id, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getResourceInfoResponse(), SOAP_IO_LENGTH, soap_put_ns2__getResourceInfo(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getResourceInfo(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getResourceInfo soap_tmp_ns2__getResourceInfo;
   struct ns2__getResourceInfoResponse *soap_tmp_ns2__getResourceInfoResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getResourceInfo._id = _id;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getResourceInfo(soap, &soap_tmp_ns2__getResourceInfo);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getResourceInfo(soap, &soap_tmp_ns2__getResourceInfo, "ns2:getResourceInfo", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getResourceInfo(soap, &soap_tmp_ns2__getResourceInfo, "ns2:getResourceInfo", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getResourceInfoReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getResourceInfoReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getResourceInfoResponse = soap_get_ns2__getResourceInfoResponse(soap, NULL, "ns2:getResourceInfoResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getResourceInfoReturn = soap_tmp_ns2__getResourceInfoResponse->_getResourceInfoReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getResourceInstitution (std::string _id, std::string & _getResourceInstitutionReturn) virtual
Web service operation 'getResourceInstitution' (returns error code or SOAP_OK)
Definition at line 1356 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getResourceInstitutionResponse::_getResourceInstitutionReturn, ns2__getResourceInstitution::_id, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getResourceInstitutionResponse(), SOAP_IO_LENGTH, soap_put_ns2__getResourceInstitution(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getResourceInstitution(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getResourceInstitution soap_tmp_ns2__getResourceInstitution;
   struct ns2__getResourceInstitutionResponse *soap_tmp_ns2__getResourceInstitutionResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getResourceInstitution._id = _id;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getResourceInstitution(soap, &soap_tmp_ns2__getResourceInstitution);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getResourceInstitution(soap, &soap_tmp_ns2__getResourceInstitution, "ns2:getResourceInstitution", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getResourceInstitution(soap, &soap_tmp_ns2__getResourceInstitution, "ns2:getResourceInstitution", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getResourceInstitutionReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getResourceInstitutionReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getResourceInstitutionResponse = soap_get_ns2__getResourceInstitutionResponse(soap, NULL, "ns2:getResourceInstitutionResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getResourceInstitutionReturn = soap_tmp_ns2__getResourceInstitutionResponse->_getResourceInstitutionReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getResourceLocation (std::string _id, std::string & _getResourceLocationReturn) virtual
Web service operation 'getResourceLocation' (returns error code or SOAP_OK)
Definition at line 1430 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getResourceLocationResponse::_getResourceLocationReturn, ns2__getResourceLocation::_id, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getResourceLocationResponse(), SOAP_IO_LENGTH, soap_put_ns2__getResourceLocation(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getResourceLocation(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getResourceLocation soap_tmp_ns2__getResourceLocation;
   struct ns2__getResourceLocationResponse *soap_tmp_ns2__getResourceLocationResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getResourceLocation._id = _id;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getResourceLocation(soap, &soap_tmp_ns2__getResourceLocation);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getResourceLocation(soap, &soap_tmp_ns2__getResourceLocation, "ns2:getResourceLocation", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getResourceLocation(soap, &soap_tmp_ns2__getResourceLocation, "ns2:getResourceLocation", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getResourceLocationReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getResourceLocationReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getResourceLocationResponse = soap_get_ns2__getResourceLocationResponse(soap, NULL, "ns2:getResourceLocationResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getResourceLocationReturn = soap_tmp_ns2__getResourceLocationResponse->_getResourceLocationReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getServicesInfo (std::string & getServicesInfoReturn) virtual
Web service operation 'getServicesInfo' (returns error code or SOAP_OK)
Definition at line 401 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::encodingStyle, soap::error, ns2__getServicesInfoResponse::getServicesInfoReturn, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getServicesInfoResponse(), SOAP_IO_LENGTH, soap_put_ns2__getServicesInfo(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getServicesInfo(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getServicesInfo soap_tmp_ns2__getServicesInfo;
   struct ns2__getServicesInfoResponse *soap_tmp_ns2__getServicesInfoResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getServicesInfo(soap, &soap_tmp_ns2__getServicesInfo);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getServicesInfo(soap, &soap_tmp_ns2__getServicesInfo, "ns2:getServicesInfo", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getServicesInfo(soap, &soap_tmp_ns2__getServicesInfo, "ns2:getServicesInfo", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&getServicesInfoReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &getServicesInfoReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getServicesInfoResponse = soap_get_ns2__getServicesInfoResponse(soap, NULL, "ns2:getServicesInfoResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   getServicesInfoReturn = soap_tmp_ns2__getServicesInfoResponse->getServicesInfoReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getServicesVersion (std::string & getServicesVersionReturn) virtual
Web service operation 'getServicesVersion' (returns error code or SOAP_OK)
Definition at line 474 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::encodingStyle, soap::error, ns2__getServicesVersionResponse::getServicesVersionReturn, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getServicesVersionResponse(), SOAP_IO_LENGTH, soap_put_ns2__getServicesVersion(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getServicesVersion(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getServicesVersion soap_tmp_ns2__getServicesVersion;
   struct ns2__getServicesVersionResponse *soap_tmp_ns2__getServicesVersionResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getServicesVersion(soap, &soap_tmp_ns2__getServicesVersion);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getServicesVersion(soap, &soap_tmp_ns2__getServicesVersion, "ns2:getServicesVersion", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getServicesVersion(soap, &soap_tmp_ns2__getServicesVersion, "ns2:getServicesVersion", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&getServicesVersionReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &getServicesVersionReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getServicesVersionResponse = soap_get_ns2__getServicesVersionResponse(soap, NULL, "ns2:getServicesVersionResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   getServicesVersionReturn = soap_tmp_ns2__getServicesVersionResponse->getServicesVersionReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::getURI (std::string _name, std::string _id, std::string & _getURIReturn) virtual
Web service operation 'getURI' (returns error code or SOAP_OK)
Definition at line 254 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__getURIResponse::_getURIReturn, ns2__getURI::_id, ns2__getURI::_name, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__getURIResponse(), SOAP_IO_LENGTH, soap_put_ns2__getURI(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__getURI(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__getURI soap_tmp_ns2__getURI;
   struct ns2__getURIResponse *soap_tmp_ns2__getURIResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__getURI._name = _name;
   soap_tmp_ns2__getURI._id = _id;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__getURI(soap, &soap_tmp_ns2__getURI);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__getURI(soap, &soap_tmp_ns2__getURI, "ns2:getURI", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__getURI(soap, &soap_tmp_ns2__getURI, "ns2:getURI", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_getURIReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_getURIReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__getURIResponse = soap_get_ns2__getURIResponse(soap, NULL, "ns2:getURIResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _getURIReturn = soap_tmp_ns2__getURIResponse->_getURIReturn;
   return soap_closesock(soap);
 }
int MiriamWebServicesSoapBindingProxy::isDeprecated (std::string _uri, std::string & _isDeprecatedReturn) virtual
Web service operation 'isDeprecated' (returns error code or SOAP_OK)
Definition at line 986 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References ns2__isDeprecatedResponse::_isDeprecatedReturn, ns2__isDeprecated::_uri, soap::encodingStyle, soap::error, soap::level, soap::mode, soap_begin(), soap_begin_count(), soap_begin_recv(), soap_body_begin_in(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_connect(), soap_default_std__string(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_endpoint, soap_envelope_begin_in(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns2__isDeprecatedResponse(), SOAP_IO_LENGTH, soap_put_ns2__isDeprecated(), soap_putheader(), soap_recv_fault(), soap_recv_header(), soap_serialize_ns2__isDeprecated(), soap_serializeheader(), and SOAP_TAG_MISMATCH.
 {
   struct soap *soap = this;
   struct ns2__isDeprecated soap_tmp_ns2__isDeprecated;
   struct ns2__isDeprecatedResponse *soap_tmp_ns2__isDeprecatedResponse;
   const char *soap_action = NULL;
   if (!soap_endpoint)
     soap_endpoint = "http://www.ebi.ac.uk/miriamws/main/MiriamWebServices";
   soap_action = "";
   soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
   soap_tmp_ns2__isDeprecated._uri = _uri;
   soap_begin(soap);
   soap_serializeheader(soap);
   soap_serialize_ns2__isDeprecated(soap, &soap_tmp_ns2__isDeprecated);
   if (soap_begin_count(soap))
     return soap->error;
   if (soap->mode & SOAP_IO_LENGTH)
     {
       if (soap_envelope_begin_out(soap)
           || soap_putheader(soap)
           || soap_body_begin_out(soap)
           || soap_put_ns2__isDeprecated(soap, &soap_tmp_ns2__isDeprecated, "ns2:isDeprecated", "")
           || soap_body_end_out(soap)
           || soap_envelope_end_out(soap))
         return soap->error;
     }
   if (soap_end_count(soap))
     return soap->error;
   if (soap_connect(soap, soap_endpoint, soap_action)
       || soap_envelope_begin_out(soap)
       || soap_putheader(soap)
       || soap_body_begin_out(soap)
       || soap_put_ns2__isDeprecated(soap, &soap_tmp_ns2__isDeprecated, "ns2:isDeprecated", "")
       || soap_body_end_out(soap)
       || soap_envelope_end_out(soap)
       || soap_end_send(soap))
     return soap_closesock(soap);
   if (!&_isDeprecatedReturn)
     return soap_closesock(soap);
   soap_default_std__string(soap, &_isDeprecatedReturn);
   if (soap_begin_recv(soap)
       || soap_envelope_begin_in(soap)
       || soap_recv_header(soap)
       || soap_body_begin_in(soap))
     return soap_closesock(soap);
   soap_tmp_ns2__isDeprecatedResponse = soap_get_ns2__isDeprecatedResponse(soap, NULL, "ns2:isDeprecatedResponse", "");
   if (soap->error)
     {
       if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
         return soap_recv_fault(soap);
       return soap_closesock(soap);
     }
   if (soap_body_end_in(soap)
       || soap_envelope_end_in(soap)
       || soap_end_recv(soap))
     return soap_closesock(soap);
   _isDeprecatedReturn = soap_tmp_ns2__isDeprecatedResponse->_isDeprecatedReturn;
   return soap_closesock(soap);
 }
void MiriamWebServicesSoapBindingProxy::MiriamWebServicesSoapBindingProxy_init (soap_mode imode, soap_mode omode) virtual
Initializer used by constructor.
Definition at line 41 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::namespaces, soap_endpoint, soap_imode, and soap_omode.
Referenced by MiriamWebServicesSoapBindingProxy().
 {
   soap_imode(this, imode);
   soap_omode(this, omode);
   soap_endpoint = NULL;
   static const struct Namespace namespaces[] =
   {
     {"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
     {"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
     {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
     {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
     {"ns2", "http://ws.miriam.ebi.ac.uk", NULL, NULL},
     {NULL, NULL, NULL, NULL}
   };
   if (!this->namespaces)
     this->namespaces = namespaces;
 }
int MiriamWebServicesSoapBindingProxy::soap_close_socket () virtual
Force close connection (normally automatic, except for send_X ops)
Definition at line 83 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap_closesock().
 {
   return soap_closesock(this);
 }
const SOAP_ENV__Fault * MiriamWebServicesSoapBindingProxy::soap_fault () virtual
Get SOAP Fault structure (NULL when absent)
Definition at line 68 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::fault.
 {
   return this->fault;
 }
const char * MiriamWebServicesSoapBindingProxy::soap_fault_detail () virtual
Get SOAP Fault detail as string (NULL when absent)
Definition at line 78 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap_faultdetail().
Referenced by CMIRIAMResources::updateMIRIAMResources().
 {
   return *soap_faultdetail(this);
 }
const char * MiriamWebServicesSoapBindingProxy::soap_fault_string () virtual
Get SOAP Fault string (NULL when absent)
Definition at line 73 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap_faultstring().
Referenced by CMIRIAMResources::updateMIRIAMResources().
 {
   return *soap_faultstring(this);
 }
void MiriamWebServicesSoapBindingProxy::soap_noheader () virtual
Disables and removes SOAP Header from message.
Definition at line 63 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap::header.
 {
   header = NULL;
 }
void MiriamWebServicesSoapBindingProxy::soap_print_fault (FILE * fd) virtual
Print fault.
Definition at line 88 of file soapMiriamWebServicesSoapBindingProxy.cpp.
 {
   ::soap_print_fault(this, fd);
 }
char * MiriamWebServicesSoapBindingProxy::soap_sprint_fault (char * buf, size_t len) virtual
Put fault into buffer.
Definition at line 99 of file soapMiriamWebServicesSoapBindingProxy.cpp.
References soap_sprint_fault().
 {
   return ::soap_sprint_fault(this, buf, len);
 }
void MiriamWebServicesSoapBindingProxy::soap_stream_fault (std::ostream & os) virtual
Print fault to stream.
Definition at line 94 of file soapMiriamWebServicesSoapBindingProxy.cpp.
 {
   ::soap_stream_fault(this, os);
 }
Member Data Documentation
const char* MiriamWebServicesSoapBindingProxy::soap_endpoint
Endpoint URL of service 'MiriamWebServicesSoapBindingProxy' (change as needed)
Definition at line 29 of file soapMiriamWebServicesSoapBindingProxy.h.
Referenced by checkRegExp(), getDataResources(), getDataTypeDef(), getDataTypePattern(), getDataTypesId(), getDataTypesName(), getDataTypeSynonyms(), getDataTypeURI(), getDataTypeURIs(), getJavaLibraryVersion(), getLocation(), getLocations(), getLocations_(), getMiriamURI(), getName(), getNames(), getOfficialDataTypeURI(), getResourceInfo(), getResourceInstitution(), getResourceLocation(), getServicesInfo(), getServicesVersion(), getURI(), isDeprecated(), and MiriamWebServicesSoapBindingProxy_init().
The documentation for this class was generated from the following files:
soapMiriamWebServicesSoapBindingProxy.h
soapMiriamWebServicesSoapBindingProxy.cpp