COPASI API: CRandom Class Reference
CRandom Class Reference
#include <CRandom.h>
Classes
struct ExpVars
struct PoissonVars
Public Types
enum Type { r250 = 0, mt19937, mt19937HR, unkown }
Public Member Functions
const unsigned C_INT32 & getModulus () const
virtual C_FLOAT64 getRandomCC ()
virtual C_FLOAT64 getRandomCO ()
virtual C_FLOAT64 getRandomExp ()
virtual C_FLOAT64 getRandomGamma (C_FLOAT64 shape, C_FLOAT64 scale)
virtual C_FLOAT64 getRandomNormal (const C_FLOAT64 &mean, const C_FLOAT64 &sd)
virtual C_FLOAT64 getRandomNormal01 ()
virtual C_FLOAT64 getRandomNormalLog (const C_FLOAT64 &mean, const C_FLOAT64 &sd)
virtual C_FLOAT64 getRandomNormalPositive (const C_FLOAT64 &mean, const C_FLOAT64 &sd)
virtual C_FLOAT64 getRandomOO ()
virtual C_FLOAT64 getRandomPoisson (const C_FLOAT64 &mean)
virtual C_INT32 getRandomS ()
virtual C_INT32 getRandomS (const C_INT32 &max)
virtual C_FLOAT64 getRandomStdGamma (C_FLOAT64 shape)
virtual unsigned C_INT32 getRandomU ()
virtual unsigned C_INT32 getRandomU (const unsigned C_INT32 &max)
const CRandom::Type & getType () const
virtual void initialize (unsigned C_INT32 seed=CRandom::getSystemSeed())
virtual ~CRandom ()
Static Public Member Functions
static CRandom * createGenerator (CRandom::Type type=CRandom::mt19937, unsigned C_INT32 seed=0)
static unsigned C_INT32 getSystemSeed ()
Static Public Attributes
static const std::string TypeName []
static const char * XMLType []
Protected Member Functions
CRandom ()
void setModulus (const unsigned C_INT32 &modulus)
Protected Attributes
C_FLOAT64 mFloat
unsigned C_INT32 mModulus
C_FLOAT64 mModulusInv
C_FLOAT64 mModulusInv1
C_INT32 mNumberS
unsigned C_INT32 mNumberU
CRandom::Type mType
Private Member Functions
C_FLOAT64 fsign (C_FLOAT64 num, C_FLOAT64 sign)
unsigned int & syscall (int arg1)
Private Attributes
ExpVars vare
PoissonVars varp
Detailed Description
Definition at line 20 of file CRandom.h.
Member Enumeration Documentation
enum CRandom::Type
Enumerator
r250
mt19937
mt19937HR
unkown
Definition at line 55 of file CRandom.h.
   {
     r250 = 0,
     mt19937,
     mt19937HR,
     unkown
   };
Constructor & Destructor Documentation
CRandom::CRandom () protected
Default/Named constructor. Seeds the random number generator with the given seed.
Definition at line 83 of file CRandom.cpp.
References CRandom::PoissonVars::a0, CRandom::PoissonVars::a1, CRandom::PoissonVars::a2, CRandom::PoissonVars::a3, CRandom::PoissonVars::a4, CRandom::PoissonVars::a5, CRandom::PoissonVars::a6, CRandom::PoissonVars::a7, CRandom::PoissonVars::fact, CRandom::PoissonVars::muold, CRandom::PoissonVars::muprev, CRandom::ExpVars::q, CRandom::ExpVars::q1, vare, and varp.
                 :
   mNumberU(0),
   mNumberS(0),
   mFloat(0.0),
   mType(CRandom::unkown),
   mModulus(1),
   mModulusInv(1.0),
   mModulusInv1(1.0)
 {
   varp.a0 = -0.5;
   varp.a1 = 0.3333333;
   varp.a2 = -0.2500068;
   varp.a3 = 0.2000118;
   varp.a4 = -0.1661269;
   varp.a5 = 0.1421878;
   varp.a6 = -0.1384794;
   varp.a7 = 0.125006;
   varp.muold = -1.0E37;
   varp.muprev = -1.0E37;
   varp.fact[0] = 1.0;
   varp.fact[1] = 1.0;
   varp.fact[2] = 2.0;
   varp.fact[3] = 6.0;
   varp.fact[4] = 24.0;
   varp.fact[5] = 120.0;
   varp.fact[6] = 720.0;
   varp.fact[7] = 5040.0;
   varp.fact[8] = 40320.0;
   varp.fact[9] = 362880.0;
   vare.q[0] = 0.6931472;
   vare.q[1] = 0.9333737;
   vare.q[2] = 0.9888778;
   vare.q[3] = 0.9984959;
   vare.q[4] = 0.9998293;
   vare.q[5] = 0.9999833;
   vare.q[6] = 0.9999986;
   vare.q[7] = 0.9999999;
   vare.q1 = vare.q;
 }
CRandom::~CRandom () virtual
The destructor.
Definition at line 125 of file CRandom.cpp.
 {}
Member Function Documentation
CRandom * CRandom::createGenerator (CRandom::Type type = CRandom::mt19937, unsigned C_INT32 seed = 0) static
Create a Generator. Note: the returned object has to be released after use with delete
Parameters
CRandom::Type type (default Mersenne Twister)
const C_INT32 & seed (default system generated seed)
Returns
CRandom * randomGenerator
Definition at line 49 of file CRandom.cpp.
References getSystemSeed(), mt19937, mt19937HR, mType, and r250.
Referenced by CEvaluationNodeFunction::CEvaluationNodeFunction(), CHybridMethod::CHybridMethod(), CHybridMethodLSODA::CHybridMethodLSODA(), CHybridMethodODE45::CHybridMethodODE45(), CPraxis::CPraxis(), CDirEntry::createTmpName(), CScanMethod::CScanMethod(), CStochMethod::CStochMethod(), CTauLeapMethod::CTauLeapMethod(), CTrajectoryMethodDsaLsodar::CTrajectoryMethodDsaLsodar(), COptItem::getRandomValue(), COptMethodEP::initialize(), CRandomSearch::initialize(), COptMethodDE::initialize(), COptMethodSRES::initialize(), COptMethodPS::initialize(), COptMethodGA::initialize(), COptMethodGASR::initialize(), COptMethodSA::initialize(), COptMethodCoranaWalk::initialize(), COptMethodSS::initialize(), main(), COptMethodEP2::optimise(), COptMethodHGASA::optimise(), and CCopasiSpringLayout::randomize().
 {
   CRandom * RandomGenerator = NULL;
   if (!seed)
     seed = getSystemSeed();
   switch (type)
     {
       case r250:
         RandomGenerator = new Cr250(seed);
         RandomGenerator->mType = type;
         break;
       case mt19937:
         RandomGenerator = new Cmt19937(seed);
         RandomGenerator->mType = type;
         break;
       case mt19937HR:
         RandomGenerator = new Cmt19937HR(seed);
         RandomGenerator->mType = type;
         break;
       default:
         RandomGenerator = new Cmt19937(seed);
         RandomGenerator->mType = type;
         break;
     }
   return RandomGenerator;
 }
C_FLOAT64 CRandom::fsign (C_FLOAT64 num, C_FLOAT64 sign) private
Definition at line 466 of file CRandom.cpp.
Referenced by getRandomPoisson().
 {
   if ((sign > 0.0f && num < 0.0f) || (sign < 0.0f && num > 0.0f))
     return - num;
   else return num;
 }
const unsigned C_INT32 & CRandom::getModulus () const
Retreive the method dependend modulus
Returns
const unsigned C_INT32 & modulus
Definition at line 127 of file CRandom.cpp.
References mModulus.
 {return mModulus;}
C_FLOAT64 CRandom::getRandomCC () virtual
Produces a uniformly distributed random number in 0 <= x <= 1.
Returns
C_FLOAT64 random
Reimplemented in Cmt19937HR, Cmt19937, and Cr250.
Definition at line 235 of file CRandom.cpp.
References getRandomU(), and mModulusInv.
Referenced by COptMethodSS::combination(), COptMethodPS::create(), COptMethodDE::creation(), COptMethodEP::creation(), COptMethodSRES::creation(), COptMethodGA::creation(), COptMethodGASR::creation(), COptMethodSS::creation(), CTauLeapMethod::doSingleStep(), getRandomExp(), getRandomPoisson(), COptItem::getRandomValue(), COptMethodPS::move(), COptMethodCoranaWalk::optimise(), COptMethodSA::optimise(), COptMethodEP2::optimise(), COptMethodHGASA::optimise(), CPraxis::praxis_(), CCopasiSpringLayout::randomize(), COptMethodSS::randomize(), randomlyPlaceGlyphInCompartmentGlyph(), randomlyPlaceGlyphInDimensions(), and CScanItemRandom::step().
 {
   return getRandomU() * mModulusInv;
 }
C_FLOAT64 CRandom::getRandomCO () virtual
Produces a uniformly distributed random number in 0 <= x < 1. Note: 0 < x <= 1 may be achieved by 1.0 - getRandomCO().
Returns
C_FLOAT64 random
Reimplemented in Cmt19937HR, Cmt19937, and Cr250.
Definition at line 245 of file CRandom.cpp.
References getRandomU(), and mModulusInv1.
Referenced by getRandomStdGamma(), COptMethodCoranaWalk::optimise(), and COptMethodSA::optimise().
 {
   return getRandomU() * mModulusInv1;
 }
C_FLOAT64 CRandom::getRandomExp () virtual
Definition at line 473 of file CRandom.cpp.
References CRandom::ExpVars::a, getRandomCC(), CRandom::ExpVars::i, CRandom::ExpVars::q, CRandom::ExpVars::q1, CRandom::ExpVars::sexpo, CRandom::ExpVars::u, CRandom::ExpVars::umin, CRandom::ExpVars::ustar, and vare.
Referenced by getRandomPoisson().
 {
   vare.a = 0.0;
   vare.u = getRandomCC();
   goto S30;
 S20:
   vare.a += *vare.q1;
 S30:
   vare.u += vare.u;
   if (vare.u < 1.0) goto S20;
   vare.u -= 1.0;
   if (vare.u > *vare.q1) goto S60;
   vare.sexpo = vare.a + vare.u;
   return vare.sexpo;
 S60:
   vare.i = 1;
   vare.ustar = getRandomCC();
   vare.umin = vare.ustar;
 S70:
   vare.ustar = getRandomCC();
   if (vare.ustar < vare.umin) vare.umin = vare.ustar;
   vare.i += 1;
   if (vare.u > *(vare.q + vare.i - 1)) goto S70;
   vare.sexpo = vare.a + vare.umin**vare.q1;
   return vare.sexpo;
 }
C_FLOAT64 CRandom::getRandomGamma (C_FLOAT64 shape, C_FLOAT64 scale) virtual
Definition at line 572 of file CRandom.cpp.
References getRandomStdGamma().
Referenced by CEvaluationNodeFunction::rgamma(), and CScanItemRandom::step().
 {
   return scale * getRandomStdGamma(shape);
 }
C_FLOAT64 CRandom::getRandomNormal (const C_FLOAT64 & mean, const C_FLOAT64 & sd) virtual
Produces a Normally distributed random number with Mean=mean and SD=sd
Parameters
const C_FLOAT64 & mean
const C_FLOAT64 & sd
Returns
C_FLOAT64 random
Definition at line 292 of file CRandom.cpp.
References getRandomNormal01().
Referenced by COptMethodPS::create(), COptMethodEP::creation(), COptMethodSRES::creation(), getRandomNormalPositive(), COptItem::getRandomValue(), COptMethodGA::mutate(), COptMethodGASR::mutate(), COptMethodDE::replicate(), and CEvaluationNodeFunction::rnormal().
 {return getRandomNormal01() * sd + mean;}
C_FLOAT64 CRandom::getRandomNormal01 () virtual
Produces a Normally distributed random number with mean=0 and SD=1
Returns
C_FLOAT64 random
Definition at line 261 of file CRandom.cpp.
References C_FLOAT64, and getRandomOO().
Referenced by getRandomNormal(), getRandomNormalLog(), getRandomPoisson(), getRandomStdGamma(), COptMethodEP::mutate(), COptMethodSRES::mutate(), and CScanItemRandom::step().
 {
   static bool HaveValue = true;
   static C_FLOAT64 SavedValue;
   C_FLOAT64 a, b, s;
   /* negate the flag */
   HaveValue = !HaveValue;
   /* return the stored number (if one is there) */
   if (HaveValue) return SavedValue;
   do
     {
       a = 2.0 * getRandomOO() - 1.0;
       b = 2.0 * getRandomOO() - 1.0;
       s = a * a + b * b;
     }
   while (s >= 1.0 || s == 0);
   s = sqrt(-2.0 * log(s) / s);
   // save one of the numbers for the next time
   SavedValue = s * a;
   // and return the other
   return s * b;
 }
C_FLOAT64 CRandom::getRandomNormalLog (const C_FLOAT64 & mean, const C_FLOAT64 & sd) virtual
Produces a Normally distributed random number with Mean=mean and SD=sd in Logarithmic scale
Returns
C_FLOAT64 random
Definition at line 310 of file CRandom.cpp.
References getRandomNormal01().
 {return mean * pow(10.0, getRandomNormal01() * sd);}
C_FLOAT64 CRandom::getRandomNormalPositive (const C_FLOAT64 & mean, const C_FLOAT64 & sd) virtual
Produces a Strictly Positive Normally distributed random number with Mean=mean and SD=sd
Parameters
const C_FLOAT64 & mean
const C_FLOAT64 & sd
Returns
C_FLOAT64 random
Definition at line 298 of file CRandom.cpp.
References C_FLOAT64, and getRandomNormal().
 {
   C_FLOAT64 x;
   while ((x = getRandomNormal(mean, sd)) < 0);
   return x;
 }
C_FLOAT64 CRandom::getRandomOO () virtual
Produces a uniformly distributed random number in 0 < x < 1.
Returns
C_FLOAT64 random
Reimplemented in Cmt19937HR, Cmt19937, and Cr250.
Definition at line 254 of file CRandom.cpp.
References getRandomU(), and mModulusInv1.
Referenced by CTrajAdaptiveSA::doSingleSSAStep(), CStochDirectMethod::doSingleStep(), CTrajectoryMethodDsaLsodar::doSingleStep(), CTrajAdaptiveSA::doSingleTauLeapStep(), CStochMethod::generateReactionIndex(), CStochMethod::generateReactionTime(), CHybridMethod::generateReactionTime(), CHybridMethodLSODA::generateReactionTime(), CHybridMethodODE45::generateReactionTime(), getRandomNormal01(), getRandomStdGamma(), CHybridMethodODE45::getReactionIndex4Hybrid(), CHybridMethodODE45::integrateDeterministicPart(), main(), CEvaluationNodeFunction::runiform(), COptMethodSRES::select(), and COptMethodGASR::select().
 {
   return (getRandomU() + .5) * mModulusInv1;
 }
C_FLOAT64 CRandom::getRandomPoisson (const C_FLOAT64 & mean) virtual
Produces a Poisson distributed random number with Mean=mean
Parameters
const C_FLOAT64 & mean
Returns
C_FLOAT64 random
Definition at line 314 of file CRandom.cpp.
References CRandom::PoissonVars::a0, CRandom::PoissonVars::a1, CRandom::PoissonVars::a2, CRandom::PoissonVars::a3, CRandom::PoissonVars::a4, CRandom::PoissonVars::a5, CRandom::PoissonVars::a6, CRandom::PoissonVars::a7, CRandom::PoissonVars::b1, CRandom::PoissonVars::b2, CRandom::PoissonVars::c, CRandom::PoissonVars::c0, CRandom::PoissonVars::c1, CRandom::PoissonVars::c2, CRandom::PoissonVars::c3, CRandom::PoissonVars::d, CRandom::PoissonVars::del, CRandom::PoissonVars::difmuk, CRandom::PoissonVars::e, CRandom::PoissonVars::fact, CRandom::PoissonVars::fk, fsign(), CRandom::PoissonVars::fx, CRandom::PoissonVars::fy, CRandom::PoissonVars::g, getRandomCC(), getRandomExp(), getRandomNormal01(), if(), CRandom::PoissonVars::ignpoi, CRandom::PoissonVars::j, CRandom::PoissonVars::k, CRandom::PoissonVars::kflag, CRandom::PoissonVars::l, CRandom::PoissonVars::ll, CRandom::PoissonVars::m, max, min, CRandom::PoissonVars::muold, CRandom::PoissonVars::muprev, CRandom::PoissonVars::omega, CRandom::PoissonVars::p, CRandom::PoissonVars::p0, CRandom::PoissonVars::pp, CRandom::PoissonVars::px, CRandom::PoissonVars::py, CRandom::PoissonVars::q, CRandom::PoissonVars::s, CRandom::PoissonVars::t, CRandom::PoissonVars::u, CRandom::PoissonVars::v, varp, CRandom::PoissonVars::x, and CRandom::PoissonVars::xx.
Referenced by CTauLeapMethod::doSingleStep(), CTrajAdaptiveSA::doSingleTauLeapStep(), CEvaluationNodeFunction::rpoisson(), and CScanItemRandom::step().
 {
   if (mu == varp.muprev) goto S10;
   if (mu < 10.0) goto S120;
   varp.muprev = mu;
   varp.s = sqrt(mu);
   varp.d = 6.0 * mu * mu;
   varp.ll = (long)(mu - 1.1484);
 S10:
   varp.g = mu + varp.s * getRandomNormal01();
   if (varp.g < 0.0) goto S20;
   varp.ignpoi = (long)(varp.g);
   if (varp.ignpoi >= varp.ll) return varp.ignpoi;
   varp.fk = (float)varp.ignpoi;
   varp.difmuk = mu - varp.fk;
   varp.u = getRandomCC();
   if (varp.d * varp.u >= varp.difmuk * varp.difmuk * varp.difmuk) return varp.ignpoi;
 S20:
   if (mu == varp.muold) goto S30;
   varp.muold = mu;
   varp.omega = 0.3989423 / varp.s;
   varp.b1 = 4.166667E-2 / mu;
   varp.b2 = 0.3 * varp.b1 * varp.b1;
   varp.c3 = 0.1428571 * varp.b1 * varp.b2;
   varp.c2 = varp.b2 - 15.0 * varp.c3;
   varp.c1 = varp.b1 - 6.0 * varp.b2 + 45.0 * varp.c3;
   varp.c0 = 1.0 - varp.b1 + 3.0 * varp.b2 - 15.0 * varp.c3;
   varp.c = 0.1069 / mu;
 S30:
   if (varp.g < 0.0) goto S50;
   varp.kflag = 0;
   goto S70;
 S40:
   if (varp.fy - varp.u * varp.fy <= varp.py * exp(varp.px - varp.fx)) return varp.ignpoi;
 S50:
   varp.e = getRandomExp();
   varp.u = getRandomCC();
   varp.u += (varp.u - 1.0);
   varp. t = 1.8 + fsign(varp.e, varp.u);
   if (varp.t <= -0.6744) goto S50;
   varp.ignpoi = (long)(mu + varp.s * varp.t);
   varp.fk = (float)varp.ignpoi;
   varp.difmuk = mu - varp.fk;
   varp.kflag = 1;
   goto S70;
 S60:
   if (varp.c * fabs(varp.u) > varp.py * exp(varp.px + varp.e) - varp.fy * exp(varp.fx + varp.e)) goto S50;
   return varp.ignpoi;
 S70:
   if (varp.ignpoi >= 10) goto S80;
   varp.px = -mu;
   varp.py = pow(mu, (double)varp.ignpoi) / *(varp.fact + varp.ignpoi);
   goto S110;
 S80:
   varp.del = 8.333333E-2 / varp.fk;
   varp.del -= (4.8 * varp.del * varp.del * varp.del);
   varp.v = varp.difmuk / varp.fk;
   if (fabs(varp.v) <= 0.25) goto S90;
   varp.px = varp.fk * log(1.0 + varp.v) - varp.difmuk - varp.del;
   goto S100;
 S90:
   varp.px = varp.fk * varp.v * varp.v * (((((((varp.a7 * varp.v + varp.a6) * varp.v + varp.a5) * varp.v\
                                           + varp.a4) * varp.v + varp.a3) * varp.v + varp.a2) * varp.v + varp.a1) * varp.v + varp.a0) - varp.del;
 S100:
   varp.py = 0.3989423 / sqrt(varp.fk);
 S110:
   varp.x = (0.5 - varp.difmuk) / varp.s;
   varp.xx = varp.x * varp.x;
   varp.fx = -0.5 * varp.xx;
   varp.fy = varp.omega * (((varp.c3 * varp.xx + varp.c2) * varp.xx + varp.c1) * varp.xx + varp.c0);
   if (varp.kflag <= 0) goto S40;
   goto S60;
 S120:
   varp.muprev = -1.0E37;
   if (mu == varp.muold) goto S130;
   if (mu >= 0.0) goto S125;
   // instead of quitting COPASI return a NaN
   return std::numeric_limits<double>::quiet_NaN();
 S125:
   varp.muold = mu;
   varp.m = std::max(1L, (long)(mu));
   varp.l = 0;
   varp.p = exp(-mu);
   varp.q = varp.p0 = varp.p;
 S130:
   varp.u = getRandomCC();
   varp.ignpoi = 0;
   if (varp.u <= varp.p0) return varp.ignpoi;
   if (varp.l == 0) goto S150;
   varp.j = 1;
   if (varp.u > 0.458) varp.j = std::min(varp.l, varp.m);
   for (varp.k = varp.j; varp.k <= varp.l; varp.k++)
     {
       if (varp.u <= *(varp.pp + varp.k - 1)) goto S180;
     }
   if (varp.l == 35) goto S130;
 S150:
   varp.l += 1;
   for (varp.k = varp.l; varp.k <= 35; varp.k++)
     {
       varp.p = varp.p * mu / (float)varp.k;
       varp.q += varp.p;
       *(varp.pp + varp.k - 1) = varp.q;
       if (varp.u <= varp.q) goto S170;
     }
   varp.l = 35;
   goto S130;
 S170:
   varp.l = varp.k;
 S180:
   varp.ignpoi = varp.k;
   return varp.ignpoi;
 }
C_INT32 CRandom::getRandomS () virtual
Get a random number in 0 <= n <= (Modulus & 0x7ffffff)
Returns
C_INT32 random
Reimplemented in Cmt19937, and Cr250.
Definition at line 184 of file CRandom.cpp.
References C_INT32, getRandomU(), min, and mModulus.
 {
   return getRandomU(std::min(mModulus, (unsigned C_INT32) 0x7ffffff));
   //  The method below only works for mModulus = 0xffffffff.
   //  return getRandomU() & 0x7ffffff;
 }
C_INT32 CRandom::getRandomS (const C_INT32 & max) virtual
Get a random number in 0 <= n <= max Note: max must be smaller than Modulus (no check for performance)
Parameters
const C_INT32 & max
Returns
C_INT32 random
Definition at line 217 of file CRandom.cpp.
References C_INT32, getRandomU(), and mModulus.
 {
   unsigned C_INT32 Max = max + 1;
   unsigned C_INT32 Limit = (mModulus / Max) * Max - 1;
   unsigned C_INT32 NumberU;
   do
     NumberU = getRandomU();
   while (NumberU >= Limit);
   return NumberU % Max;
 }
C_FLOAT64 CRandom::getRandomStdGamma (C_FLOAT64 shape) virtual
Definition at line 508 of file CRandom.cpp.
References C_FLOAT64, getRandomCO(), getRandomNormal01(), and getRandomOO().
Referenced by getRandomGamma().
 {
   if (a < 1.0)
     {
       C_FLOAT64 v1, v2, v3;
       C_FLOAT64 x, e;
       C_FLOAT64 v0 = M_E / (M_E + a);
       do
         {
           v1 = 1.0 - getRandomCO();
           v2 = 1.0 - getRandomCO();
           v3 = 1.0 - getRandomCO();
           if (v1 <= v0)
             {
               x = pow(v2, (1.0 / a));
               e = v3 *  pow(x, (a - 1.0));
             }
           else
             {
               x = 1 - log(v2);
               e = v3 * exp(-x);
             }
         }
       while (e > pow(x, (a - 1.0)) * exp(-x));
       return x;
     }
   else
     {
       C_FLOAT64 d, c, x, v, u;
       d = a - 1.0 / 3.0;
       c = 1.0 / sqrt(9.0 * d);
       while (true)
         {
           do
             {
               x = getRandomNormal01();
               v = 1.0 + c * x;
             }
           while (v <= 0.0);
           v = v * v * v;
           u = getRandomOO();
           if (u < 1.0 - 0.0331 * (x * x) * (x * x))
             {
               break;
             }
           if (log(u) < 0.5 * x * x + d * (1.0 - v + log(v)))
             {
               break;
             }
         }
       return (d * v);
     }
 }
unsigned C_INT32 CRandom::getRandomU () virtual
Get a random number in 0 <= n <= Modulus
Returns
unsigned C_INT32 random
Reimplemented in Cmt19937, and Cr250.
Definition at line 173 of file CRandom.cpp.
References fatalError, and mNumberU.
Referenced by CDirEntry::createTmpName(), COptMethodGA::crossover(), COptMethodGASR::crossover(), getRandomCC(), getRandomCO(), getRandomOO(), getRandomS(), getRandomU(), CPermutation::pick(), COptMethodDE::replicate(), COptMethodSRES::replicate(), COptMethodEP::select(), COptMethodGA::select(), and CPermutation::shuffle().
 {
   /* Every random number generator has to implement this. */
   fatalError();
   return mNumberU;
 }
unsigned C_INT32 CRandom::getRandomU (const unsigned C_INT32 & max) virtual
Get a random number in 0 <= n <= max Note: max must be smaller than Modulus (no check for performance)
Parameters
const unsigned C_INT32 & max
Returns
unsigned C_INT32 random
Definition at line 197 of file CRandom.cpp.
References C_INT32, getRandomU(), and mModulus.
 {
   unsigned C_INT32 Max = max + 1;
   unsigned C_INT32 Limit = (mModulus / Max) * Max - 1;
   unsigned C_INT32 NumberU;
   do
     NumberU = getRandomU();
   while (NumberU >= Limit);
   return NumberU % Max;
 }
unsigned C_INT32 CRandom::getSystemSeed () static
get a system dependend seed (hopefully random)
Definition at line 136 of file CRandom.cpp.
References C_INT32, CCopasiTimeVariable::getCurrentWallTime(), CCopasiTimeVariable::getMicroSeconds(), and syscall().
Referenced by createGenerator(), and CCopasiSpringLayout::randomize().
 {
   unsigned C_INT32 ThreadId = 0;
 #ifdef WIN32
   ThreadId = (unsigned C_INT32)(GetCurrentThreadId() & 0xffffffffUL);
 #elif defined(SYS_thread_selfid)
   ThreadId = (unsigned C_INT32)(::syscall(SYS_thread_selfid) & 0xffffffffUL);
 #elif defined(SYS_gettid)
   ThreadId = (unsigned C_INT32)(::syscall(SYS_gettid) & 0xffffffffUL);
 #elif defined(SYS_getthrid)
   ThreadId = (unsigned C_INT32)(syscall(SYS_getthrid) & 0xffffffffUL);
 #endif
   // Invert Byte order so that we do not have accidental cancellations since both time and thread id are incremented.
   ThreadId = (ThreadId & 0x000000ffUL) << 24 | (ThreadId & 0x0000ff00UL) << 8 |
              (ThreadId & 0x00ff0000UL) >> 8 | (ThreadId & 0xff000000UL) >> 24;
   unsigned C_INT32 Time = (unsigned C_INT32)(CCopasiTimeVariable::getCurrentWallTime().getMicroSeconds() & 0xffffffffUL);
   // We use XOR so that we do not favor set or unset bits.
   unsigned C_INT32 Seed = ThreadId ^ Time;
   return Seed;
 }
const CRandom::Type & CRandom::getType () const
Retreive the type of the generator
Returns
const CRandom::Type & type
Definition at line 126 of file CRandom.cpp.
References mType.
 {return mType;}
void CRandom::initialize (unsigned C_INT32 seed = CRandom::getSystemSeed()) virtual
Initialize or reinitialize the random number generator with the given seed.
Parameters
unsigned C_INT32 seed (default system seed)
Reimplemented in Cmt19937, and Cr250.
Definition at line 162 of file CRandom.cpp.
References fatalError.
Referenced by CHybridMethod::initMethod(), CHybridMethodODE45::initMethod(), CHybridMethodLSODA::initMethod(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), and CStochMethod::start().
 {
   /* Every random number generator has to implement this. */
   fatalError();
   return;
 }
void CRandom::setModulus (const unsigned C_INT32 & modulus) protected
Set the Modulus
Parameters
Definition at line 129 of file CRandom.cpp.
References mModulus, mModulusInv, and mModulusInv1.
Referenced by Cmt19937::Cmt19937(), and Cr250::Cr250().
 {
   mModulus = modulus;
   mModulusInv = 1.0 / mModulus;
   mModulusInv1 = 1.0 / (mModulus + 1.0);
 }
unsigned int& CRandom::syscall (int arg1) private
Referenced by getSystemSeed().
Member Data Documentation
C_FLOAT64 CRandom::mFloat protected
A 64-bit floating point random number.
Definition at line 88 of file CRandom.h.
Referenced by Cmt19937::genrand_res53(), Cmt19937HR::getRandomCC(), Cmt19937HR::getRandomCO(), and Cmt19937HR::getRandomOO().
unsigned C_INT32 CRandom::mModulus protected
Definition at line 98 of file CRandom.h.
Referenced by getModulus(), getRandomS(), getRandomU(), and setModulus().
C_FLOAT64 CRandom::mModulusInv protected
Definition at line 103 of file CRandom.h.
Referenced by Cr250::getRandomCC(), getRandomCC(), and setModulus().
C_FLOAT64 CRandom::mModulusInv1 protected
Definition at line 108 of file CRandom.h.
Referenced by getRandomCO(), Cr250::getRandomOO(), getRandomOO(), and setModulus().
C_INT32 CRandom::mNumberS protected
A signed 32-bit integer random number.
Definition at line 83 of file CRandom.h.
unsigned C_INT32 CRandom::mNumberU protected
A unsigned 32-bit integer random number.
Definition at line 78 of file CRandom.h.
Referenced by Cr250::dr250(), Cmt19937::getRandomCC(), Cmt19937::getRandomCO(), Cmt19937::getRandomOO(), Cmt19937::getRandomS(), Cmt19937::getRandomU(), getRandomU(), Cr250::r250(), and Cr250::r250n().
CRandom::Type CRandom::mType protected
The type of the generator
Definition at line 93 of file CRandom.h.
Referenced by createGenerator(), and getType().
const std::string CRandom::TypeName static
Initial value:
=
{
  "r250",
  "Mersenne Twister",
  "Mersenne Twister (HR)",
  ""
}
String literals for the GUI to display type names of random number generators known to COPASI.
Definition at line 67 of file CRandom.h.
ExpVars CRandom::vare private
Definition at line 113 of file CRandom.h.
Referenced by CRandom(), and getRandomExp().
PoissonVars CRandom::varp private
Definition at line 112 of file CRandom.h.
Referenced by CRandom(), and getRandomPoisson().
const char * CRandom::XMLType static
Initial value:
=
{
  "r250",
  "MersenneTwister",
  "MersenneTwisterHR",
  NULL
}
XML type names of random number generators known to COPASI.
Definition at line 72 of file CRandom.h.
The documentation for this class was generated from the following files:
CRandom.h
CRandom.cpp