COPASI API: CQScreenshotOptionsDialog Class Reference
CQScreenshotOptionsDialog Class Reference
#include <CQScreenshotOptionsDialog.h>
Public Types
enum FRAME_OPTION { UNSET, CURRENT_FRAME, ALL_FRAMES, USER_DEFINED_FRAMES }
Public Member Functions
CQScreenshotOptionsDialog (double layoutX, double layoutY, double layoutWidth, double layoutHeight, double currentX, double currentY, double currentWidth, double currentHeight, unsigned int imageWidth, unsigned int imageHeight, int lastFrame=-1, QWidget *pParent=NULL)
FRAME_OPTION getFrameOption () const
const std::set< size_t > & getFrameSet () const
double getHeight () const
unsigned int getImageHeight () const
unsigned int getImageWidth () const
double getWidth () const
double getX () const
double getY () const
bool isSetDrawSelectionDecoration () const
Protected Slots
virtual void accept ()
void slotDisplayButtonClicked (QAbstractButton *pButton)
void slotDrawSelectionToggled (bool v)
void slotFrameButtonClicked (QAbstractButton *pButton)
void slotFramesTextEdited (const QString &text)
void slotFramesTextEditingFinished ()
void slotHeightChanged (const QString &ht)
void slotImageHeightChanged (int h)
void slotImageWidthChanged (int w)
void slotWidthChanged (const QString &wt)
void slotXChanged (const QString &xt)
void slotYChanged (const QString &yt)
Protected Attributes
double mCurrentHeight
double mCurrentWidth
double mCurrentX
double mCurrentY
QColor mDefaultColor
bool mDrawSelectionDecorations
FRAME_OPTION mFrameOption
std::set< size_t > mFrames
bool mFramesEditHighlighted
double mHeight
QColor mHighlightColor
unsigned int mImageHeight
unsigned int mImageWidth
int mLastFrame
double mLayoutHeight
double mLayoutWidth
double mLayoutX
double mLayoutY
double mWidth
double mX
double mY
Detailed Description
Definition at line 17 of file CQScreenshotOptionsDialog.h.
Member Enumeration Documentation
enum CQScreenshotOptionsDialog::FRAME_OPTION
Enumerator
UNSET
CURRENT_FRAME
ALL_FRAMES
USER_DEFINED_FRAMES
Definition at line 22 of file CQScreenshotOptionsDialog.h.
   {
     UNSET,
     CURRENT_FRAME,
     ALL_FRAMES,
     USER_DEFINED_FRAMES
   };
Constructor & Destructor Documentation
CQScreenshotOptionsDialog::CQScreenshotOptionsDialog (double layoutX, double layoutY, double layoutWidth, double layoutHeight, double currentX, double currentY, double currentWidth, double currentHeight, unsigned int imageWidth, unsigned int imageHeight, int lastFrame = -1, QWidget * pParent = NULL)
Definition at line 18 of file CQScreenshotOptionsDialog.cpp.
References mCurrentHeight, mCurrentWidth, mCurrentX, mCurrentY, mDefaultColor, mHeight, mHighlightColor, mImageHeight, mImageWidth, mLastFrame, mLayoutHeight, mLayoutWidth, mLayoutX, mLayoutY, mWidth, mX, mY, slotDisplayButtonClicked(), slotDrawSelectionToggled(), slotFrameButtonClicked(), slotFramesTextEdited(), slotFramesTextEditingFinished(), slotHeightChanged(), slotImageHeightChanged(), slotImageWidthChanged(), slotWidthChanged(), slotXChanged(), and slotYChanged().
                                     :
   QDialog(pParent),
   mLayoutX(layoutX),
   mLayoutY(layoutY),
   mLayoutWidth(layoutWidth),
   mLayoutHeight(layoutHeight),
   mCurrentX(currentX),
   mCurrentY(currentY),
   mCurrentWidth(currentWidth),
   mCurrentHeight(currentHeight),
   mFrameOption(UNSET),
   mX(mCurrentX),
   mY(mCurrentY),
   mWidth(mCurrentWidth),
   mHeight(mCurrentHeight),
   mImageWidth(imageWidth),
   mImageHeight(imageHeight),
   mDrawSelectionDecorations(false),
   mLastFrame(lastFrame),
   mFramesEditHighlighted(false)
 {
   setupUi(this);
   QPalette palette = this->mpFramesEdit->palette();
   this->mDefaultColor = palette.color(this->mpFramesEdit->backgroundRole());
   this->mHighlightColor = QColor(224, 128, 128);
   // we disable the edit window after we get the background color
   // otherwise we save the background for the disabled state
   this->mpFramesEdit->setEnabled(false);
   // check if we need to display the frame options, if yes make them visible and enable them
   this->mpFramesWidget->setEnabled(this->mLastFrame > 0);
   this->mpFramesWidget->setVisible(this->mLastFrame > 0);
   //
   // hide the custom size options
   this->mpAdvancedWidget->setVisible(false);
   this->adjustSize();
   // set a validator on the frames input field
   CQFrameInputValidator* pFrameVal = new CQFrameInputValidator(this);
   this->mpFramesEdit->setValidator(pFrameVal);
   // create a button group for the frame option checkboxes
   QButtonGroup* pFrameButtonGroup = new QButtonGroup(this);
   pFrameButtonGroup->addButton(this->mpCurrentFrameButton);
   pFrameButtonGroup->addButton(this->mpAllFramesButton);
   pFrameButtonGroup->addButton(this->mpFramesButton);
   pFrameButtonGroup->setExclusive(true);
   connect(pFrameButtonGroup, SIGNAL(buttonClicked(QAbstractButton*)), this, SLOT(slotFrameButtonClicked(QAbstractButton*)));
   // create a button group for the display selection
   QButtonGroup* pDisplayButtonGroup = new QButtonGroup(this);
   pDisplayButtonGroup->addButton(this->mpCompleteButton);
   pDisplayButtonGroup->addButton(this->mpVisibleButton);
   pDisplayButtonGroup->addButton(this->mpCustomButton);
   pDisplayButtonGroup->setExclusive(true);
   connect(pDisplayButtonGroup, SIGNAL(buttonClicked(QAbstractButton*)), this, SLOT(slotDisplayButtonClicked(QAbstractButton*)));
   //
   // set validators on the input fields
   QDoubleValidator* pVal = new QDoubleValidator(this->mpXLineEdit);
   this->mpXLineEdit->setValidator(pVal);
   this->mpXLineEdit->setText(QString("%1").arg(this->mCurrentX));
   pVal = new QDoubleValidator(this->mpYLineEdit);
   this->mpYLineEdit->setValidator(pVal);
   this->mpXLineEdit->setText(QString("%1").arg(this->mCurrentY));
   pVal = new QDoubleValidator(this->mpWidthLineEdit);
   pVal->setBottom(0.0);
   this->mpWidthLineEdit->setValidator(pVal);
   this->mpWidthLineEdit->setText(QString("%1").arg(this->mCurrentWidth));
   pVal = new QDoubleValidator(this->mpHeightLineEdit);
   pVal->setBottom(0.0);
   this->mpHeightLineEdit->setValidator(pVal);
   this->mpHeightLineEdit->setText(QString("%1").arg(this->mCurrentHeight));
   // set the information labels text at the top
   std::ostringstream os;
   os << "visible area: " << this->mCurrentX << "," << this->mCurrentY;
   os << " " << this->mCurrentWidth << " x " << this->mCurrentHeight;
   this->visible_area_label->setText(QString(os.str().c_str()));
   os.str("");
   os << "layout area: " << this->mLayoutX << "," << this->mLayoutY;
   os << " " << this->mLayoutWidth << " x " << this->mLayoutHeight;
   this->layout_area_label->setText(QString(os.str().c_str()));
   // set the values of the input fields
   this->mpXLineEdit->setText(QString("%1").arg(this->mX));
   this->mpYLineEdit->setText(QString("%1").arg(this->mY));
   this->mpWidthLineEdit->setText(QString("%1").arg(this->mWidth));
   this->mpHeightLineEdit->setText(QString("%1").arg(this->mHeight));
   this->mpImageWidthSpinbox->setValue(this->mImageWidth);
   this->mpImageHeightSpinbox->setValue(this->mImageHeight);
   // check if the image width or the image height are 0, if so uncheck
   // and disable the aspect check box
   if (this->mImageWidth == 0 || this->mImageHeight == 0)
     {
       this->mpKeepImageAspectCheckbox->setChecked(false);
       this->mpKeepImageAspectCheckbox->setEnabled(false);
     }
   //
   // check if the mCurrentWidth or the mCurrentHeight are 0.0, if so
   // uncheck and disable the aspect check box
   if (this->mCurrentWidth == 0.0 || this->mCurrentHeight == 0.0)
     {
       this->mpKeepAreaAspectCheckbox->setChecked(false);
       this->mpKeepAreaAspectCheckbox->setEnabled(false);
     }
   connect(this->mpImageWidthSpinbox, SIGNAL(valueChanged(int)), this, SLOT(slotImageWidthChanged(int)));
   connect(this->mpImageHeightSpinbox, SIGNAL(valueChanged(int)), this, SLOT(slotImageHeightChanged(int)));
   connect(this->mpWidthLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotWidthChanged(const QString&)));
   connect(this->mpHeightLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotHeightChanged(const QString&)));
   connect(this->mpXLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotXChanged(const QString&)));
   connect(this->mpYLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotYChanged(const QString&)));
   connect(this->mpDrawSelectionCheckbox, SIGNAL(toggled(bool)), this, SLOT(slotDrawSelectionToggled(bool)));
   connect(this->mpFramesEdit, SIGNAL(textEdited(const QString&)), this, SLOT(slotFramesTextEdited(const QString&)));
   connect(this->mpFramesEdit, SIGNAL(editingFinished()), this, SLOT(slotFramesTextEditingFinished()));
 }
Member Function Documentation
void CQScreenshotOptionsDialog::accept () protected virtual slot
Definition at line 197 of file CQScreenshotOptionsDialog.cpp.
 {
   this->QDialog::accept();
 }
CQScreenshotOptionsDialog::FRAME_OPTION CQScreenshotOptionsDialog::getFrameOption () const
Returns which frames are to be exported. For a dialog that does not display the frames option, this will return UNSET. For dialogs with the frame option, possible values are CURRENT_FRAME, ALL_FRAMES, USER_DEFINED_FRAMES.
Definition at line 250 of file CQScreenshotOptionsDialog.cpp.
References mFrameOption.
Referenced by CQLayoutMainWindow::saveImage().
 {
   return this->mFrameOption;
 }
const std::set< size_t > & CQScreenshotOptionsDialog::getFrameSet () const
Returns the set of frames.
Definition at line 258 of file CQScreenshotOptionsDialog.cpp.
References mFrames.
Referenced by CQLayoutMainWindow::saveImage().
 {
   return this->mFrames;
 }
double CQScreenshotOptionsDialog::getHeight () const
Definition at line 166 of file CQScreenshotOptionsDialog.cpp.
References mHeight.
Referenced by CQLayoutMainWindow::saveImage(), and CQNewMainWindow::slotScreenshot().
 {
   return this->mHeight;
 }
unsigned int CQScreenshotOptionsDialog::getImageHeight () const
Definition at line 182 of file CQScreenshotOptionsDialog.cpp.
References mImageHeight.
Referenced by CQLayoutMainWindow::saveImage(), and CQNewMainWindow::slotScreenshot().
 {
   return this->mImageHeight;
 }
unsigned int CQScreenshotOptionsDialog::getImageWidth () const
Definition at line 174 of file CQScreenshotOptionsDialog.cpp.
References mImageWidth.
Referenced by CQLayoutMainWindow::saveImage(), and CQNewMainWindow::slotScreenshot().
 {
   return this->mImageWidth;
 }
double CQScreenshotOptionsDialog::getWidth () const
Definition at line 158 of file CQScreenshotOptionsDialog.cpp.
References mWidth.
Referenced by CQLayoutMainWindow::saveImage(), and CQNewMainWindow::slotScreenshot().
 {
   return this->mWidth;
 }
double CQScreenshotOptionsDialog::getX () const
Definition at line 142 of file CQScreenshotOptionsDialog.cpp.
References mX.
Referenced by CQLayoutMainWindow::saveImage(), and CQNewMainWindow::slotScreenshot().
 {
   return this->mX;
 }
double CQScreenshotOptionsDialog::getY () const
Definition at line 150 of file CQScreenshotOptionsDialog.cpp.
References mY.
Referenced by CQLayoutMainWindow::saveImage(), and CQNewMainWindow::slotScreenshot().
 {
   return this->mY;
 }
bool CQScreenshotOptionsDialog::isSetDrawSelectionDecoration () const
Definition at line 191 of file CQScreenshotOptionsDialog.cpp.
References mDrawSelectionDecorations.
Referenced by CQNewMainWindow::slotScreenshot().
 {
   return mDrawSelectionDecorations;
 }
void CQScreenshotOptionsDialog::slotDisplayButtonClicked (QAbstractButton * pButton) protected slot
Definition at line 203 of file CQScreenshotOptionsDialog.cpp.
References mCurrentHeight, mCurrentWidth, mCurrentX, mCurrentY, mHeight, mLayoutHeight, mLayoutWidth, mLayoutX, mLayoutY, mWidth, mX, and mY.
Referenced by CQScreenshotOptionsDialog().
 {
   if (pButton == this->mpCustomButton)
     {
       this->mpAdvancedWidget->setEnabled(true);
       this->mpAdvancedWidget->setVisible(true);
       this->adjustSize();
       // set mX and mY to the entries in the edit fields
       this->mX = this->mpXLineEdit->text().toDouble();
       this->mY = this->mpYLineEdit->text().toDouble();
       // set mWidth and mHeight to the entries in the edit fields
       this->mWidth = this->mpWidthLineEdit->text().toDouble();
       this->mHeight = this->mpHeightLineEdit->text().toDouble();
     }
   else
     {
       this->mpAdvancedWidget->setVisible(false);
       this->adjustSize();
       if (pButton == this->mpVisibleButton)
         {
           // set mX and mY to mCurrentX and mCurrentY
           this->mX = this->mCurrentX;
           this->mY = this->mCurrentY;
           // set mWidth and mHeight to mCurrentWidth and mCurrentHeight
           this->mWidth = this->mCurrentWidth;
           this->mHeight = this->mCurrentHeight;
         }
       else
         {
           // set mX and mY to mLayoutX and mLayoutY
           this->mX = this->mLayoutX;
           this->mY = this->mLayoutY;
           // set mWidth and mHeight to mLayoutWidth and mLayoutHeight
           this->mWidth = this->mLayoutWidth;
           this->mHeight = this->mLayoutHeight;
         }
     }
 }
void CQScreenshotOptionsDialog::slotDrawSelectionToggled (bool v) protected slot
Definition at line 416 of file CQScreenshotOptionsDialog.cpp.
References mDrawSelectionDecorations.
Referenced by CQScreenshotOptionsDialog().
 {
   this->mDrawSelectionDecorations = v;
 }
void CQScreenshotOptionsDialog::slotFrameButtonClicked (QAbstractButton * pButton) protected slot
Definition at line 264 of file CQScreenshotOptionsDialog.cpp.
References ALL_FRAMES, CURRENT_FRAME, mFrameOption, and USER_DEFINED_FRAMES.
Referenced by CQScreenshotOptionsDialog().
 {
   if (pButton == this->mpCurrentFrameButton)
     {
       this->mFrameOption = CQScreenshotOptionsDialog::CURRENT_FRAME;
       this->mpFramesEdit->setEnabled(false);
     }
   else if (pButton == this->mpAllFramesButton)
     {
       this->mFrameOption = CQScreenshotOptionsDialog::ALL_FRAMES;
       this->mpFramesEdit->setEnabled(false);
     }
   else if (pButton == this->mpFramesButton)
     {
       this->mFrameOption = CQScreenshotOptionsDialog::USER_DEFINED_FRAMES;
       this->mpFramesEdit->setEnabled(true);
     }
 }
void CQScreenshotOptionsDialog::slotFramesTextEdited (const QString & text) protected slot
Definition at line 422 of file CQScreenshotOptionsDialog.cpp.
References mDefaultColor, mFramesEditHighlighted, and mHighlightColor.
Referenced by CQScreenshotOptionsDialog().
 {
   if (this->mpFramesEdit->hasAcceptableInput() && this->mFramesEditHighlighted == true)
     {
       // set background to normal
       mpFramesEdit->setStyleSheet(QString(mpFramesEdit->metaObject()->className()) + " {background-color:" + mDefaultColor.name() + ";}");
       mFramesEditHighlighted = false;
     }
   else if (!this->mpFramesEdit->hasAcceptableInput() && this->mFramesEditHighlighted == false)
     {
       // set background to red
       mpFramesEdit->setStyleSheet(QString(mpFramesEdit->metaObject()->className()) + " {background-color:" + mHighlightColor.name() + ";}");
       mFramesEditHighlighted = true;
     }
 }
void CQScreenshotOptionsDialog::slotFramesTextEditingFinished () protected slot
Definition at line 439 of file CQScreenshotOptionsDialog.cpp.
References mFrames, and mLastFrame.
Referenced by CQScreenshotOptionsDialog().
 {
   QString yt = this->mpFramesEdit->text();
   // the [0-9] are used instead of \\d because I only want these digits and not any symbol of any alphabet that counts as a digit
   //const QString complete("^(\\s*[0-9]+\\s*(-\\s*(?:[0-9]+\\s*)?)?|\\s*-\\s*[0-9]+\\s*)(?:,(\\s*[0-9]+\\s*(?:-\\s*([0-9]+\\s*)?)?|\\s*-\\s*[0-9]+\\s*))*$");
   //QRegExp completeRegExp(complete);
   //completeRegExp.setPatternSyntax(QRegExp::RegExp2);
   const QString number("^[0-9]+$");
   QRegExp numberRegExp(number);
   numberRegExp.setPatternSyntax(QRegExp::RegExp2);
   const QString closed("^([0-9]+)\\s*-\\s*([0-9]+)$");
   QRegExp closedRegExp(closed);
   closedRegExp.setPatternSyntax(QRegExp::RegExp2);
   const QString start("^([0-9]+)\\s*-$");
   QRegExp startRegExp(start);
   startRegExp.setPatternSyntax(QRegExp::RegExp2);
   const QString end("^-\\s*([0-9]+)$");
   QRegExp endRegExp(end);
   endRegExp.setPatternSyntax(QRegExp::RegExp2);
   // split the input into groups and parse the groups
   //bool match = completeRegExp.exactMatch(yt);
   //assert(match == true);
   //if (!match) return;
   //QStringList l = completeRegExp.capturedTexts();
   QStringList l = yt.split(QString(","), QString::SkipEmptyParts);
   int i, iMax = l.size();
   assert(iMax != 0);
   this->mFrames.clear();
   QString s1, s2;
   for (i = 0; i < iMax; ++i)
     {
       s1 = l[i].trimmed();
       // check if it is a number, a closed range or one of
       // the two possible open ranges
       if (numberRegExp.exactMatch(s1))
         {
           QStringList l2 = numberRegExp.capturedTexts();
           assert(l2.size() == 1);
           if (l2.size() > 0)
             {
               unsigned int n = l2[0].toUInt();
               if (this->mLastFrame > 0 && n <= (unsigned int)this->mLastFrame)
                 {
                   this->mFrames.insert(n);
                 }
             }
         }
       else if (closedRegExp.exactMatch(s1))
         {
           QStringList l2 = closedRegExp.capturedTexts();
           assert(l2.size() == 3);
           if (l2.size() > 2)
             {
               unsigned int n1 = l2[1].toUInt();
               unsigned int n2 = l2[2].toUInt();
               assert(n1 <= n2);
               if (this->mLastFrame > 0 && n1 <= (unsigned int)this->mLastFrame)
                 {
                   n2 = (n2 > (unsigned int)this->mLastFrame) ? (unsigned int)this->mLastFrame : n2;
                   while (n1 <= n2)
                     {
                       this->mFrames.insert(n1);
                       ++n1;
                     }
                 }
             }
         }
       else if (startRegExp.exactMatch(s1))
         {
           QStringList l2 = startRegExp.capturedTexts();
           assert(l2.size() == 2);
           if (l2.size() > 1)
             {
               unsigned int n = l2[1].toUInt();
               if (this->mLastFrame > 0 && n <= (unsigned int)this->mLastFrame)
                 {
                   // add all number from n to this->mLastFrame
                   while (n <= (unsigned int)this->mLastFrame)
                     {
                       this->mFrames.insert(n);
                       ++n;
                     }
                 }
             }
         }
       else if (endRegExp.exactMatch(s1))
         {
           QStringList l2 = endRegExp.capturedTexts();
           assert(l2.size() == 2);
           if (l2.size() > 1)
             {
               unsigned int n = l2[1].toUInt();
               if (this->mLastFrame > 0 && n <= (unsigned int)this->mLastFrame)
                 {
                   // add all number from 1 to n
                   while (n != 0)
                     {
                       this->mFrames.insert(n);
                       --n;
                     }
                 }
             }
         }
       else
         {
           // it be an empty string
           this->mFrames.clear();
           return;
         }
     }
 }
void CQScreenshotOptionsDialog::slotHeightChanged (const QString & ht) protected slot
Definition at line 373 of file CQScreenshotOptionsDialog.cpp.
References mHeight, mWidth, and slotWidthChanged().
Referenced by CQScreenshotOptionsDialog(), and slotWidthChanged().
 {
   double newHeight = ht.toDouble();
   // is the keep aspect check box is set, we need to calculate the aspect first
   if (this->mpKeepAreaAspectCheckbox->isChecked())
     {
       double aspect = (double)this->mWidth / (double)this->mHeight;
       double w = newHeight * aspect;
       disconnect(this->mpWidthLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotWidthChanged(const QString&)));
       this->mpWidthLineEdit->setText(QString("%1").arg(w));
       this->mWidth = w;
       connect(this->mpWidthLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotWidthChanged(const QString&)));
     }
   // set the new width
   this->mHeight = newHeight;
   // if either the new width or new height is 0, we have to disable the aspect check box
   if ((this->mWidth == 0.0 || this->mHeight == 0.0) && (this->mpKeepAreaAspectCheckbox->isEnabled() || this->mpKeepAreaAspectCheckbox->isChecked()))
     {
       this->mpKeepAreaAspectCheckbox->setChecked(false);
       this->mpKeepAreaAspectCheckbox->setEnabled(false);
     }
   else if (this->mpKeepAreaAspectCheckbox->isEnabled() == false)
     {
       this->mpKeepAreaAspectCheckbox->setEnabled(true);
     }
 }
void CQScreenshotOptionsDialog::slotImageHeightChanged (int h) protected slot
Definition at line 313 of file CQScreenshotOptionsDialog.cpp.
References mImageHeight, mImageWidth, and slotImageWidthChanged().
Referenced by CQScreenshotOptionsDialog(), and slotImageWidthChanged().
 {
   // is the keep aspect check box is set, we need to calculate the aspect first
   if (this->mpKeepImageAspectCheckbox->isChecked())
     {
       double aspect = (double)this->mImageWidth / (double)this->mImageHeight;
       int w = (int)(round(h * aspect));
       disconnect(this->mpImageWidthSpinbox, SIGNAL(valueChanged(int)), this, SLOT(slotImageWidthChanged(int)));
       this->mpImageWidthSpinbox->setValue(w);
       this->mImageWidth = w;
       connect(this->mpImageWidthSpinbox, SIGNAL(valueChanged(int)), this, SLOT(slotImageWidthChanged(int)));
     }
   // set the new width
   this->mImageHeight = h;
   // if either the new width or new height is 0, we have to disable the aspect check box
   if ((this->mImageWidth == 0 || this->mImageHeight == 0) && (this->mpKeepImageAspectCheckbox->isEnabled() || this->mpKeepImageAspectCheckbox->isChecked()))
     {
       this->mpKeepImageAspectCheckbox->setChecked(false);
       this->mpKeepImageAspectCheckbox->setEnabled(false);
     }
   else if (this->mpKeepImageAspectCheckbox->isEnabled() == false)
     {
       this->mpKeepImageAspectCheckbox->setEnabled(true);
     }
 }
void CQScreenshotOptionsDialog::slotImageWidthChanged (int w) protected slot
Definition at line 284 of file CQScreenshotOptionsDialog.cpp.
References mImageHeight, mImageWidth, and slotImageHeightChanged().
Referenced by CQScreenshotOptionsDialog(), and slotImageHeightChanged().
 {
   // is the keep aspect check box is set, we need to calculate the aspect first
   if (this->mpKeepImageAspectCheckbox->isChecked())
     {
       double aspect = (double)this->mImageHeight / (double)this->mImageWidth;
       int h = (int)(round(w * aspect));
       disconnect(this->mpImageHeightSpinbox, SIGNAL(valueChanged(int)), this, SLOT(slotImageHeightChanged(int)));
       this->mpImageHeightSpinbox->setValue(h);
       this->mImageHeight = h;
       connect(this->mpImageHeightSpinbox, SIGNAL(valueChanged(int)), this, SLOT(slotImageHeightChanged(int)));
     }
   // set the new width
   this->mImageWidth = w;
   // if either the new width or new height is 0, we have to disable the aspect check box
   if ((this->mImageWidth == 0 || this->mImageHeight == 0) && (this->mpKeepImageAspectCheckbox->isEnabled() || this->mpKeepImageAspectCheckbox->isChecked()))
     {
       this->mpKeepImageAspectCheckbox->setChecked(false);
       this->mpKeepImageAspectCheckbox->setEnabled(false);
     }
   else if (this->mpKeepImageAspectCheckbox->isEnabled() == false)
     {
       this->mpKeepImageAspectCheckbox->setEnabled(true);
     }
 }
void CQScreenshotOptionsDialog::slotWidthChanged (const QString & wt) protected slot
Definition at line 342 of file CQScreenshotOptionsDialog.cpp.
References mHeight, mWidth, and slotHeightChanged().
Referenced by CQScreenshotOptionsDialog(), and slotHeightChanged().
 {
   double newWidth = wt.toDouble();
   // is the keep aspect check box is set, we need to calculate the aspect first
   if (this->mpKeepAreaAspectCheckbox->isChecked())
     {
       double aspect = (double)this->mHeight / (double)this->mWidth;
       double h = newWidth * aspect;
       disconnect(this->mpHeightLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotHeightChanged(const QString&)));
       this->mpHeightLineEdit->setText(QString("%1").arg(h));
       this->mHeight = h;
       connect(this->mpHeightLineEdit, SIGNAL(textChanged(const QString&)), this, SLOT(slotHeightChanged(const QString&)));
     }
   // set the new width
   this->mWidth = newWidth;
   // if either the new width or new height is 0, we have to disable the aspect check box
   if ((this->mWidth == 0.0 || this->mHeight == 0.0) && (this->mpKeepAreaAspectCheckbox->isEnabled() || this->mpKeepAreaAspectCheckbox->isChecked()))
     {
       this->mpKeepAreaAspectCheckbox->setChecked(false);
       this->mpKeepAreaAspectCheckbox->setEnabled(false);
     }
   else if (this->mpKeepAreaAspectCheckbox->isEnabled() == false)
     {
       this->mpKeepAreaAspectCheckbox->setEnabled(true);
     }
 }
void CQScreenshotOptionsDialog::slotXChanged (const QString & xt) protected slot
Definition at line 404 of file CQScreenshotOptionsDialog.cpp.
References mX.
Referenced by CQScreenshotOptionsDialog().
 {
   this->mX = xt.toDouble();
 }
void CQScreenshotOptionsDialog::slotYChanged (const QString & yt) protected slot
Definition at line 410 of file CQScreenshotOptionsDialog.cpp.
References mY.
Referenced by CQScreenshotOptionsDialog().
 {
   this->mY = yt.toDouble();
 }
Member Data Documentation
double CQScreenshotOptionsDialog::mCurrentHeight protected
Definition at line 48 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mCurrentWidth protected
Definition at line 46 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mCurrentX protected
Definition at line 42 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mCurrentY protected
Definition at line 44 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
QColor CQScreenshotOptionsDialog::mDefaultColor protected
Definition at line 73 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotFramesTextEdited().
bool CQScreenshotOptionsDialog::mDrawSelectionDecorations protected
Definition at line 66 of file CQScreenshotOptionsDialog.h.
Referenced by isSetDrawSelectionDecoration(), and slotDrawSelectionToggled().
FRAME_OPTION CQScreenshotOptionsDialog::mFrameOption protected
Definition at line 51 of file CQScreenshotOptionsDialog.h.
Referenced by getFrameOption(), and slotFrameButtonClicked().
std::set<size_t> CQScreenshotOptionsDialog::mFrames protected
Definition at line 54 of file CQScreenshotOptionsDialog.h.
Referenced by getFrameSet(), and slotFramesTextEditingFinished().
bool CQScreenshotOptionsDialog::mFramesEditHighlighted protected
Definition at line 75 of file CQScreenshotOptionsDialog.h.
Referenced by slotFramesTextEdited().
double CQScreenshotOptionsDialog::mHeight protected
Definition at line 60 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), getHeight(), slotDisplayButtonClicked(), slotHeightChanged(), and slotWidthChanged().
QColor CQScreenshotOptionsDialog::mHighlightColor protected
Definition at line 74 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotFramesTextEdited().
unsigned int CQScreenshotOptionsDialog::mImageHeight protected
Definition at line 63 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), getImageHeight(), slotImageHeightChanged(), and slotImageWidthChanged().
unsigned int CQScreenshotOptionsDialog::mImageWidth protected
Definition at line 62 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), getImageWidth(), slotImageHeightChanged(), and slotImageWidthChanged().
int CQScreenshotOptionsDialog::mLastFrame protected
Definition at line 69 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotFramesTextEditingFinished().
double CQScreenshotOptionsDialog::mLayoutHeight protected
Definition at line 40 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mLayoutWidth protected
Definition at line 38 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mLayoutX protected
Definition at line 34 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mLayoutY protected
Definition at line 36 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), and slotDisplayButtonClicked().
double CQScreenshotOptionsDialog::mWidth protected
Definition at line 59 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), getWidth(), slotDisplayButtonClicked(), slotHeightChanged(), and slotWidthChanged().
double CQScreenshotOptionsDialog::mX protected
Definition at line 57 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), getX(), slotDisplayButtonClicked(), and slotXChanged().
double CQScreenshotOptionsDialog::mY protected
Definition at line 58 of file CQScreenshotOptionsDialog.h.
Referenced by CQScreenshotOptionsDialog(), getY(), slotDisplayButtonClicked(), and slotYChanged().
The documentation for this class was generated from the following files:
CQScreenshotOptionsDialog.h
CQScreenshotOptionsDialog.cpp