COPASI API: CSensProblem.cpp File Reference
CSensProblem.cpp File Reference
#include <string>
#include <sstream>
#include "copasi.h"
#include "CSensProblem.h"
#include "CopasiDataModel/CCopasiDataModel.h"
Functions
std::ostream & operator<< (std::ostream &os, const CSensProblem &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CSensProblem & o)
Output stream operator. Prints description of the problem
Parameters
ostream & os
const Problem & A
Returns
ostream & os
Definition at line 612 of file CSensProblem.cpp.
References CSensProblem::getNumberOfVariables(), CCopasiObject::getObjectDataModel(), CSensProblem::getSubTaskType(), CSensProblem::getTargetFunctions(), CSensProblem::getVariables(), CSensItem::print(), and CSensProblem::SubTaskName.
 {
   os << "Function(s) to be derived:" << std::endl;
   const CCopasiDataModel* pDataModel = o.getObjectDataModel();
   assert(pDataModel != NULL);
   os << o.getTargetFunctions().print(pDataModel) << std::endl << std::endl;
   os << "Calculation to perform: "
      << CSensProblem::SubTaskName[o.getSubTaskType()] << std::endl << std::endl;
   size_t i, imax = o.getNumberOfVariables();
   for (i = 0; i < imax; ++i)
     {
       os << "Variable(s) for " << i + 1 << ". derivation:" << std::endl;
       os << o.getVariables(i).print(pDataModel) << std::endl << std::endl;
     }
   return os;
 }