COPASI API: ObjectBrowserWidget Class Reference
ObjectBrowserWidget Class Reference
#include <ObjectBrowserWidget.h>
Public Slots
virtual void clearClicked ()
virtual void commitClicked ()
virtual void listviewChecked (QTreeWidgetItem *, int)
virtual void toggleViewClicked ()
Public Member Functions
void clickToReverseCheck (ObjectBrowserItem *pCurrent)
void eXport (ObjectBrowserItem *pCurrent, std::vector< const CCopasiObject * > *outputVector)
CCopasiObject * getFieldCopasiObject (CCopasiContainer *pCurrent, const char *name)
void loadChild (ObjectBrowserItem *parent, const CCopasiContainer *copaParent, bool nField)
void loadData ()
void loadField (ObjectBrowserItem *parent, CCopasiVector< CCopasiObject > *copaParent)
void loadUI ()
ObjectBrowserWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0, int state=0)
int partition (int, int, int, ObjectBrowserItem **)
void quick_sort (int, int, ObjectBrowserItem **)
void removeDuplicate (ObjectList *objectItemList)
void selectObjects (std::vector< const CCopasiObject * > *pObjectVector)
void setCheck (ObjectBrowserItem *pCurrent)
void setCheckMark (ObjectBrowserItem *pCurrent)
void setOutputVector (std::vector< const CCopasiObject * > *pObjectVector)
void setUncheck (ObjectBrowserItem *pCurrent)
void swap (int, int, ObjectBrowserItem **)
void updateUI ()
virtual ~ObjectBrowserWidget ()
Public Attributes
QPushButton * clearButton
QPushButton * commitButton
QFrame * Line1
QGridLayout * ObjectBrowserLayout
ObjectList * objectItemList
QTextEdit * ObjectItemText
QTreeWidget * ObjectListView
ObjectList * refreshList
QSpacerItem * spacer
QPushButton * toggleViewButton
Private Member Functions
void cleanup ()
void selectObjects (ObjectBrowserItem *browserItem, const CCopasiObject *selectObject)
void updateSelectedItemsView ()
Private Attributes
pageIndex currentPage
std::vector< const
CCopasiObject * > * mOutputObjectVector
Detailed Description
Definition at line 50 of file ObjectBrowserWidget.h.
Constructor & Destructor Documentation
ObjectBrowserWidget::ObjectBrowserWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0, int state = 0)
Definition at line 59 of file ObjectBrowserWidget.cpp.
References clearButton, clearClicked(), commitButton, commitClicked(), currentPage, Line1, listviewChecked(), LISTVIEWPAGE, loadData(), ObjectBrowserLayout, objectItemList, ObjectItemText, ObjectListView, pObjectAll, pObjectNone, pObjectParts, refreshList, ObjectBrowserItem::resetKeySpace(), spacer, toggleViewButton, and toggleViewClicked().
   : QWidget(parent, fl),
     objectItemList(NULL),
     refreshList(NULL),
     ObjectBrowserLayout(NULL),
     clearButton(NULL),
     toggleViewButton(NULL),
     commitButton(NULL),
     ObjectListView(NULL),
     Line1(NULL),
     spacer(NULL),
     ObjectItemText(NULL),
     mOutputObjectVector(NULL),
     currentPage(LISTVIEWPAGE)
 {
   setObjectName(QString::fromUtf8(name));
   if (!name)
     setObjectName("ObjectBrowser");
   if (state == 0)
     ObjectBrowserLayout = new QGridLayout(this);
   else
     {
       ObjectBrowserLayout = new QGridLayout(this);
       ObjectBrowserLayout->setSpacing(6);
     }
   ObjectBrowserLayout->setObjectName(QString::fromUtf8("ObjectListView"));
   ObjectListView = new QTreeWidget(this);
   ObjectListView->setObjectName("");
   //  ObjectListView->addColumn(trUtf8("Object Browser"));
   QStringList strList;
   strList << trUtf8("Name") << trUtf8("Type");
   ObjectListView->setHeaderLabels(strList);
   //ObjectListView->header()->setClickEnabled(false, ObjectListView->header()->count() - 1);
   ObjectListView->setAcceptDrops(false);
   ObjectListView->setSortingEnabled(true);
   ObjectListView->sortByColumn(0, Qt::AscendingOrder);
   ObjectListView->header()->setResizeMode(QHeaderView::ResizeToContents);
   ObjectListView->setSelectionMode(QAbstractItemView::NoSelection);
   ObjectItemText = new QTextEdit(this);
   ObjectItemText->setObjectName("ObjectItemText");
   ObjectItemText ->hide();
   ObjectBrowserLayout->addWidget(ObjectListView, 0, 0, 0, 3);
   ObjectBrowserLayout->addWidget(ObjectItemText, 0, 0, 0, 3);
   if (state != 0)
     {
       Line1 = new QFrame(this);
       Line1->setObjectName("Line1");
       Line1->setFrameShape(QFrame::HLine);
       Line1->setFrameShadow(QFrame::Sunken);
       Line1->setFrameShape(QFrame::HLine);
       ObjectBrowserLayout->addWidget(Line1, 1, 1, 0, 3);
       clearButton = new QPushButton(this);
       clearButton->setObjectName("clearButton");
       clearButton->setText(trUtf8("Clear"));
       ObjectBrowserLayout->addWidget(clearButton, 2, 0);
       commitButton = new QPushButton(this);
       commitButton->setObjectName("commitButton");
       commitButton->setText(trUtf8("Commit"));
       ObjectBrowserLayout->addWidget(commitButton, 2, 3);
       toggleViewButton = new QPushButton(this);
       toggleViewButton->setObjectName("toggleViewButton");
       toggleViewButton->setText(trUtf8("Selected Items"));
       ObjectBrowserLayout->addWidget(toggleViewButton, 2, 2);
       spacer = new QSpacerItem(131, 31, QSizePolicy::Expanding, QSizePolicy::Minimum);
       ObjectBrowserLayout->addItem(spacer, 2, 1);
       // signals and slots connections
       connect(clearButton, SIGNAL(clicked()), this, SLOT(clearClicked()));
       connect(toggleViewButton, SIGNAL(clicked()), this, SLOT(toggleViewClicked()));
       connect(commitButton, SIGNAL(clicked()), this, SLOT(commitClicked()));
       // tab order
       setTabOrder(ObjectListView, clearButton);
       setTabOrder(clearButton, toggleViewButton);
       setTabOrder(toggleViewButton, commitButton);
     }
   connect(ObjectListView, SIGNAL(itemClicked(QTreeWidgetItem *, int)), this, SLOT(listviewChecked(QTreeWidgetItem*, int)));
   pObjectAll = new QPixmap((const char**)ptrObjectAll);
   pObjectNone = new QPixmap((const char**)ptrObjectNone);
   pObjectParts = new QPixmap((const char**)ptrObjectParts);
   objectItemList = new ObjectList();
   refreshList = new ObjectList();
   ObjectBrowserItem::resetKeySpace();
   loadData();
   currentPage = LISTVIEWPAGE;
 }
ObjectBrowserWidget::~ObjectBrowserWidget () virtual
Definition at line 161 of file ObjectBrowserWidget.cpp.
References cleanup().
 {
   cleanup();
 }
Member Function Documentation
void ObjectBrowserWidget::cleanup () private
Definition at line 166 of file ObjectBrowserWidget.cpp.
References objectItemList, and refreshList.
Referenced by ~ObjectBrowserWidget().
 {
   delete objectItemList;
   delete refreshList;
 }
void ObjectBrowserWidget::clearClicked () virtual slot
Definition at line 172 of file ObjectBrowserWidget.cpp.
References ObjectList::getRoot(), ObjectListItem::pItem, refreshList, setUncheck(), and updateUI().
Referenced by ObjectBrowserWidget(), and setOutputVector().
 {
   if (!refreshList->getRoot()) return;
   ObjectBrowserItem* root = static_cast< ObjectBrowserItem * >(refreshList->getRoot()->pItem);
   setUncheck(root);
   updateUI();
   //  qWarning("ObjectBrowser::clearClicked(): Not implemented yet!");
 }
void ObjectBrowserWidget::clickToReverseCheck (ObjectBrowserItem * pCurrent)
Definition at line 193 of file ObjectBrowserWidget.cpp.
References ALLCHECKED, ObjectList::insert(), ObjectBrowserItem::isChecked(), refreshList, ObjectBrowserItem::reverseChecked(), setCheck(), and setUncheck().
Referenced by listviewChecked().
 {
   refreshList->insert(pCurrent);
   ObjectBrowserItem* pTmp = pCurrent;
   while (pTmp->parent() != NULL)
     {
       pTmp = static_cast< ObjectBrowserItem * >(pTmp->parent());
       refreshList->insert(pTmp);
     }
   if (pCurrent->isChecked() == ALLCHECKED)
     {
       if (pCurrent->isChecked())
         pCurrent->reverseChecked();
       setUncheck(static_cast< ObjectBrowserItem * >(pCurrent->child(0)));
       return;
     }
   //else no check or partly checked
   if (!pCurrent->isChecked())
     pCurrent->reverseChecked();
   setCheck(static_cast< ObjectBrowserItem * >(pCurrent->child(0)));
   return;
 }
void ObjectBrowserWidget::commitClicked () virtual slot
Definition at line 332 of file ObjectBrowserWidget.cpp.
References eXport(), ObjectList::getRoot(), mOutputObjectVector, objectItemList, and ObjectListItem::pItem.
Referenced by CCopasiSelectionWidget::commit(), ObjectBrowserWidget(), ObjectBrowserDialog::okClicked(), CCopasiSelectionWidget::setExpertMode(), and CPlotSelectionDialog::slotOKButtonClicked().
 {
   ObjectBrowserItem* rootItem;
   rootItem = objectItemList->getRoot()->pItem;
   if (mOutputObjectVector) mOutputObjectVector->clear();
   eXport(rootItem, mOutputObjectVector);
   return;
 }
void ObjectBrowserWidget::eXport (ObjectBrowserItem * pCurrent, std::vector< const CCopasiObject * > * outputVector)
Definition at line 343 of file ObjectBrowserWidget.cpp.
References C_INT32, FIELDATTR, CCopasiObject::getCN(), ObjectBrowserItem::getObject(), ObjectBrowserItem::getType(), ObjectBrowserItem::isChecked(), ObjectBrowserItem::nextSibling(), and CBrowserObject::pCopasiObject.
Referenced by commitClicked(), and updateSelectedItemsView().
 {
   if (!outputVector) return;
   if (pCurrent->child(0))
     {
       ObjectBrowserItem* pChild = static_cast< ObjectBrowserItem * >(pCurrent->child(0));
       for (; pChild != NULL; pChild = static_cast< ObjectBrowserItem * >(pChild->nextSibling()))
         if (pChild->getType() != FIELDATTR)
           eXport(pChild, outputVector);
     }
   else //it has no child
     {
       if (pCurrent->isChecked() && (pCurrent->getType() != FIELDATTR))
         {
           if (pCurrent->getObject())
             {
               bool insertFlag = true;
               unsigned C_INT32 i = 0;
               for (; i < outputVector->size(); i++)
                 if (pCurrent->getObject()->pCopasiObject->getCN() == (*outputVector)[i]->getCN()) insertFlag = false;
               if (insertFlag)
                 outputVector->push_back(pCurrent->getObject()->pCopasiObject);
             }
         }
       // else skip current item
     }
 }
CCopasiObject * ObjectBrowserWidget::getFieldCopasiObject (CCopasiContainer * pCurrent, const char * name)
Definition at line 708 of file ObjectBrowserWidget.cpp.
References FROM_UTF8, and CCopasiContainer::getObjects().
Referenced by loadField().
 {
   const CCopasiContainer::objectMap * pObjectList = & pCurrent->getObjects();
   CCopasiContainer::objectMap::const_iterator it = pObjectList->begin();
   CCopasiContainer::objectMap::const_iterator end = pObjectList->end();
   //  CCopasiObject* pResult;
   while (it != end)
     {
       //      if (it->second->isContainer())
       //        {
       //          pResult = getFieldCopasiObject((CCopasiContainer *)it->second, name);
       //          if (pResult)
       //            return pResult;
       //}
       if (FROM_UTF8(it->second->getObjectName()) == name)
         return it->second;
       it++;
     }
   return NULL;
 }
void ObjectBrowserWidget::listviewChecked (QTreeWidgetItem * , int) virtual slot
Definition at line 182 of file ObjectBrowserWidget.cpp.
References clickToReverseCheck(), and updateUI().
Referenced by ObjectBrowserWidget().
 {
   //  if ((pCurrent == NULL)||((static_cast< ObjectBrowserItem * >(pCurrent))->getType() == FIELDATTR))
   if ((pCurrent == NULL) || (pCurrent->text(0) == "Select by attribute"))
     return;
   clickToReverseCheck(static_cast< ObjectBrowserItem * >(pCurrent));
   updateUI();
   //loadUI();
 }
void ObjectBrowserWidget::loadChild (ObjectBrowserItem * parent, const CCopasiContainer * copaParent, bool nField)
Definition at line 480 of file ObjectBrowserWidget.cpp.
References ObjectBrowserItem::attachKey(), CONTAINERATTR, FIELDATTR, FROM_UTF8, CCopasiObject::getObjectName(), CCopasiContainer::getObjects(), ObjectList::insert(), CCopasiObject::isContainer(), CCopasiObject::isVector(), ObjectList::len(), loadField(), OBJECTATTR, objectItemList, pdelete, ObjectList::pop(), ObjectBrowserItem::setObjectType(), and CCopasiVector< T >::size().
Referenced by loadData(), and loadField().
 {
   unsigned int i;
   ObjectBrowserItem* last = NULL;
   CCopasiObject* current = NULL;
   ObjectList* childStack = new ObjectList();
   const CCopasiContainer::objectMap * pObjectList = & copaParent->getObjects();
   CCopasiContainer::objectMap::const_iterator it = pObjectList->begin();
   CCopasiContainer::objectMap::const_iterator end = pObjectList->end();
   if ((copaParent->isVector()) && (nField))
     {
       if ((static_cast< const CCopasiVector < CCopasiObject > * >(copaParent)->size() >= 1) &&
           ((*static_cast< const CCopasiVector < CCopasiObject > * >(copaParent))[0]->isContainer()))
         {
           //add attribute list
           ObjectBrowserItem* fieldChild = new ObjectBrowserItem(parent, NULL, NULL, objectItemList);
           fieldChild->setObjectType(FIELDATTR);
           fieldChild->setText(0, "Select by attribute");
           //fieldChild->setSelectable(false);
           loadField(fieldChild, const_cast<CCopasiVector < CCopasiObject > *>(static_cast< const CCopasiVector < CCopasiObject > * >(copaParent)));
           fieldChild->attachKey();
           last = fieldChild;
         }
     }
   if (copaParent->isVector())
     {
       for (i = 0; i < static_cast< const CCopasiVector < CCopasiObject > * >(copaParent)->size(); i++)
         {
           current = (*static_cast< const CCopasiVector < CCopasiObject > * >(copaParent))[i];
           ObjectBrowserItem* currentItem = new ObjectBrowserItem(parent, last, current, objectItemList);
           last = currentItem;
           currentItem->setText(0, FROM_UTF8(current->getObjectName()));
           if (current->isContainer())
             {
               currentItem->setObjectType(CONTAINERATTR);
               currentItem->attachKey();
               if (current->isVector())
                 currentItem->setText(0, currentItem->text(0) + "[]");
               loadChild(currentItem, static_cast< CCopasiContainer * >(current), nField);
             }
           else
             {
               currentItem->setObjectType(OBJECTATTR);
               childStack->insert(currentItem);  //attach the key later
             }
         }
     }
   else
     {
       while (it != end)
         {
           current = it->second;
           // Skip all strings
           if (dynamic_cast<CCopasiStaticString *>(current))
             {
               it++;
               continue;
             }
           ObjectBrowserItem* currentItem = new ObjectBrowserItem(parent, last, current, objectItemList);
           last = currentItem;
           currentItem->setText(0, FROM_UTF8(current->getObjectName()));
           if (current->isContainer())
             {
               currentItem->setObjectType(CONTAINERATTR);
               currentItem->attachKey();
               if (current->isVector())
                 currentItem->setText(0, currentItem->text(0) + "[]");
               loadChild(currentItem, static_cast< CCopasiContainer * >(current), nField);
             }
           else
             {
               currentItem->setObjectType(OBJECTATTR);
               childStack->insert(currentItem);  //attach the key later
             }
           it++;
         }
     }
   ObjectBrowserItem* pCurrent;
   while (childStack->len() > 0)
     {
       pCurrent = childStack->pop();
       pCurrent->attachKey();
     }
   pdelete(childStack);
 }
void ObjectBrowserWidget::loadData ()
Definition at line 428 of file ObjectBrowserWidget.cpp.
References ObjectBrowserItem::attachKey(), CONTAINERATTR, CCopasiRootContainer::getRoot(), loadChild(), loadUI(), objectItemList, ObjectListView, removeDuplicate(), and ObjectBrowserItem::setObjectType().
Referenced by ObjectBrowserWidget().
 {
   const CCopasiContainer * root = CCopasiRootContainer::getRoot();
   ObjectBrowserItem * itemRoot = new ObjectBrowserItem(ObjectListView, NULL, root, objectItemList);
   itemRoot->attachKey();
   itemRoot->setObjectType(CONTAINERATTR);
   //  itemRoot->setText(0, FROM_UTF8(root->getObjectName()));
   itemRoot->setText(0, QString("COPASI"));
   itemRoot->setExpanded(true);
   loadChild(itemRoot, root, true);
   removeDuplicate(objectItemList);
   loadUI();
 }
void ObjectBrowserWidget::loadField (ObjectBrowserItem * parent, CCopasiVector< CCopasiObject > * copaParent)
Definition at line 584 of file ObjectBrowserWidget.cpp.
References ObjectBrowserItem::attachKey(), FIELDATTR, FROM_UTF8, getFieldCopasiObject(), CCopasiObject::getObjectName(), CCopasiObject::isContainer(), loadChild(), objectItemList, ObjectBrowserItem::setObjectType(), and CCopasiVector< T >::size().
Referenced by loadChild().
 {
   unsigned int i;
   ObjectBrowserItem* lastFieldItem = NULL;
   CCopasiObject* currentFieldObject = NULL;
   ObjectBrowserItem* lastObjectItem = NULL;
   CCopasiObject* currentObject = NULL;
   if ((copaParent->size() < 1) || (!(*copaParent)[0]->isContainer())) return; //empty list
   const CCopasiContainer::objectMap * pFieldList =
     &(static_cast< CCopasiContainer * >((*copaParent)[0])->getObjects());
   CCopasiContainer::objectMap::const_iterator fieldIt = pFieldList->begin();
   CCopasiContainer::objectMap::const_iterator fieldEnd = pFieldList->end();
   while (fieldIt != fieldEnd)
     {
       currentFieldObject = fieldIt->second;
       ObjectBrowserItem* currentFieldItem = new ObjectBrowserItem(parent, lastFieldItem, NULL, objectItemList);
       currentFieldItem->attachKey();
       currentFieldItem->setObjectType(FIELDATTR);
       currentFieldItem->setText(0, FROM_UTF8(currentFieldObject->getObjectName()));
       lastFieldItem = currentFieldItem;
       lastObjectItem = NULL;
       for (i = 0; i < copaParent->size(); i++)
         {
           CCopasiObject* pSubField;
           currentObject = (*static_cast< CCopasiVector < CCopasiObject > * >(copaParent))[i];
           if (currentObject->isContainer())
             pSubField =
               getFieldCopasiObject(static_cast< CCopasiContainer * >(currentObject),
                                    currentFieldObject->getObjectName().c_str());
           else
             {
               pSubField = NULL; // this shall be an exception error
             }
           ObjectBrowserItem* currentItem = new ObjectBrowserItem(currentFieldItem, lastObjectItem, pSubField, objectItemList);
           currentItem->setText(0, FROM_UTF8(currentObject->getObjectName()));
           //   if ((pSubField)&&(pSubField->isVector()))
           //            currentItem->setText(0, currentItem->text(0) + "[]");
           currentItem->setObjectType(FIELDATTR);
           currentItem->attachKey();
           if (pSubField)
             if (pSubField->isContainer()) //container field recursively to find all possible items
               {
                 loadChild(currentItem, static_cast< CCopasiContainer * >(pSubField), false); // wont show the attribute and field list
               }
           lastObjectItem = currentItem;
         }
       fieldIt++;
     }
 }
void ObjectBrowserWidget::loadUI ()
Definition at line 699 of file ObjectBrowserWidget.cpp.
References ObjectList::getRoot(), objectItemList, ObjectListItem::pItem, ObjectListItem::pNext, and setCheckMark().
Referenced by loadData().
 {
   ObjectListItem* pCurrent = objectItemList->getRoot();
   setCheckMark(pCurrent->pItem);
   for (; pCurrent != NULL; pCurrent = pCurrent->pNext)
     setCheckMark(pCurrent->pItem);
 }
int ObjectBrowserWidget::partition (int split_pos, int start_pos, int end_pos, ObjectBrowserItem ** quick_sort_array)
Definition at line 383 of file ObjectBrowserWidget.cpp.
References ObjectBrowserItem::getObject(), CBrowserObject::pCopasiObject, and swap().
Referenced by quick_sort().
 {
   const void * tmp = quick_sort_array[split_pos]->getObject()->pCopasiObject;
   if (split_pos != start_pos)
     swap(split_pos, start_pos, quick_sort_array);
   split_pos = start_pos;
   end_pos++;
   while (start_pos < end_pos)
     {
       while ((++start_pos < end_pos) && (quick_sort_array[start_pos]->getObject()->pCopasiObject <= tmp));
       while ((--end_pos > start_pos) && (quick_sort_array[end_pos]->getObject()->pCopasiObject > tmp));
       if (start_pos < end_pos)
         swap(start_pos, end_pos, quick_sort_array);
       else
         break;
     }
   start_pos--;
   if (split_pos != start_pos)
     swap(split_pos, start_pos, quick_sort_array);
   return start_pos;
 }
void ObjectBrowserWidget::quick_sort (int m, int n, ObjectBrowserItem ** quick_sort_array)
Definition at line 413 of file ObjectBrowserWidget.cpp.
References partition().
Referenced by removeDuplicate().
 {
   if (m < n)
     {
       int medium = (m + n) / 2;
       medium = partition(medium, m, n, quick_sort_array);
       if (m < medium - 1)
         quick_sort(m, medium - 1, quick_sort_array);
       if (medium + 1 < n)
         quick_sort(medium + 1, n, quick_sort_array);
     }
 }
void ObjectBrowserWidget::removeDuplicate (ObjectList * objectItemList)
Definition at line 442 of file ObjectBrowserWidget.cpp.
References ObjectBrowserItem::getObject(), ObjectList::getRoot(), ObjectList::insert(), ObjectList::len(), CBrowserObject::pCopasiObject, ObjectListItem::pItem, ObjectListItem::pNext, ObjectList::pop(), quick_sort(), CBrowserObject::referenceList, and ObjectBrowserItem::setBrowserObject().
Referenced by loadData().
 {
   int length = objectItemList->len();
   ObjectBrowserItem** bufferVector = new ObjectBrowserItem * [length];
   // copy out the list
   ObjectListItem* pCurrent = objectItemList->getRoot();
   for (int i = 0; i < length; i++)
     {
       bufferVector[i] = pCurrent->pItem;
       pCurrent = pCurrent->pNext;
     }
   // sort list according to CCopasiObject
   quick_sort(0, length - 1, bufferVector);
   int index;
   CBrowserObject* pBrowserObject = NULL;
   ObjectBrowserItem* pBrowserItem = NULL;
   for (index = 0; (index < length) && (!bufferVector[index]->getObject()->pCopasiObject); index++);
   pBrowserObject = bufferVector[index++]->getObject();
   for (; index < length; index++)
     {
       if (bufferVector[index]->getObject()->pCopasiObject == pBrowserObject->pCopasiObject) //duplicate point
         {
           pBrowserItem = bufferVector[index]->getObject()->referenceList->pop();
           pBrowserObject->referenceList->insert(pBrowserItem);
           pBrowserItem->setBrowserObject(pBrowserObject);
         }
       else
         pBrowserObject = bufferVector[index]->getObject();
     }
 }
void ObjectBrowserWidget::selectObjects (std::vector< const CCopasiObject * > * pObjectVector)
Definition at line 732 of file ObjectBrowserWidget.cpp.
References ObjectList::getRoot(), objectItemList, ObjectListItem::pItem, and updateUI().
Referenced by ObjectBrowserDialog::selectObjects(), selectObjects(), and setOutputVector().
 {
   unsigned int i;
   ObjectBrowserItem* rootItem;
   rootItem = objectItemList->getRoot()->pItem;
   for (i = 0; i < pObjectVector->size(); i++)
     {
       if ((*pObjectVector)[i]) selectObjects(rootItem, (*pObjectVector)[i]);
     }
   updateUI();
 }
void ObjectBrowserWidget::selectObjects (ObjectBrowserItem * browserItem, const CCopasiObject * selectObject) private
Definition at line 747 of file ObjectBrowserWidget.cpp.
References ALLCHECKED, FIELDATTR, ObjectBrowserItem::getObject(), ObjectBrowserItem::getType(), ObjectList::insert(), CBrowserObject::mChecked, ObjectBrowserItem::nextSibling(), CBrowserObject::pCopasiObject, refreshList, selectObjects(), and setCheck().
 {
   ObjectBrowserItem* pCurrent;
   pCurrent = browserItem;
   if (pCurrent->child(0))
     {
       ObjectBrowserItem* pChild = static_cast< ObjectBrowserItem * >(pCurrent->child(0));
       for (; pChild != NULL; pChild = static_cast< ObjectBrowserItem * >(pChild->nextSibling()))
         if (pChild->getType() != FIELDATTR)
           selectObjects(pChild, selectObject);
     }
   else
     {
       //it has no child
       if (pCurrent->getType() != FIELDATTR)
         {
           if (pCurrent->getObject() && (pCurrent->getObject()->pCopasiObject == selectObject))
             {
               refreshList->insert(pCurrent);
               ObjectBrowserItem* pTmp = pCurrent;
               while (pTmp->parent() != NULL)
                 {
                   pTmp = static_cast< ObjectBrowserItem * >(pTmp->parent());
                   refreshList->insert(pTmp);
                 }
               pCurrent->getObject()->mChecked = ALLCHECKED;
               setCheck(static_cast< ObjectBrowserItem * >(pCurrent->child(0)));
             }
           // else skip current item
         }
     }
 }
void ObjectBrowserWidget::setCheck (ObjectBrowserItem * pCurrent)
Definition at line 239 of file ObjectBrowserWidget.cpp.
References ObjectList::insert(), ObjectBrowserItem::isChecked(), ObjectBrowserItem::nextSibling(), refreshList, and ObjectBrowserItem::reverseChecked().
Referenced by clickToReverseCheck(), and selectObjects().
 {
   if (pCurrent == NULL)
     return;
   refreshList->insert(pCurrent);
   if (!pCurrent->isChecked())
     pCurrent->reverseChecked();
   if (pCurrent->child(0) != NULL)
     setCheck(static_cast< ObjectBrowserItem * >(pCurrent->child(0)));
   if (pCurrent->nextSibling() != NULL)
     setCheck(static_cast< ObjectBrowserItem * >(pCurrent->nextSibling()));
 }
void ObjectBrowserWidget::setCheckMark (ObjectBrowserItem * pCurrent)
Definition at line 677 of file ObjectBrowserWidget.cpp.
References ALLCHECKED, NOCHECKED, ObjectBrowserItem::nUserChecked(), PARTCHECKED, pObjectAll, pObjectNone, and pObjectParts.
Referenced by loadUI(), and updateUI().
 {
   if (pCurrent->text(0) == "Select by attribute")
     {
       pCurrent->setIcon(0, QIcon());
       return;
     }
   switch (pCurrent->nUserChecked())
     {
       case NOCHECKED:
         pCurrent->setIcon(0, QIcon(*pObjectNone));
         break;
       case ALLCHECKED:
         pCurrent->setIcon(0, QIcon(*pObjectAll));
         break;
       case PARTCHECKED:
         pCurrent->setIcon(0, QIcon(*pObjectParts));
         break;
     }
 }
void ObjectBrowserWidget::setOutputVector (std::vector< const CCopasiObject * > * pObjectVector)
Definition at line 324 of file ObjectBrowserWidget.cpp.
References clearClicked(), mOutputObjectVector, and selectObjects().
Referenced by CCopasiSelectionWidget::setExpertMode(), CCopasiSelectionWidget::setOutputVector(), and ObjectBrowserDialog::setOutputVector().
 {
   mOutputObjectVector = pObjectVector;
   this->clearClicked();
   if (mOutputObjectVector) selectObjects(mOutputObjectVector);
 }
void ObjectBrowserWidget::setUncheck (ObjectBrowserItem * pCurrent)
Definition at line 222 of file ObjectBrowserWidget.cpp.
References ObjectList::insert(), ObjectBrowserItem::isChecked(), ObjectBrowserItem::nextSibling(), refreshList, and ObjectBrowserItem::reverseChecked().
Referenced by clearClicked(), and clickToReverseCheck().
 {
   if (pCurrent == NULL)
     return;
   refreshList->insert(pCurrent);
   if (pCurrent->isChecked())
     pCurrent->reverseChecked();
   if (pCurrent->child(0) != NULL)
     setUncheck(static_cast< ObjectBrowserItem * >(pCurrent->child(0)));
   if (pCurrent->nextSibling() != NULL)
     setUncheck(static_cast< ObjectBrowserItem * >(pCurrent->nextSibling()));
 }
void ObjectBrowserWidget::swap (int first_pos, int second_pos, ObjectBrowserItem ** array)
Definition at line 376 of file ObjectBrowserWidget.cpp.
Referenced by partition().
 {
   ObjectBrowserItem* tmp = array[first_pos];
   array[first_pos] = array[second_pos];
   array[second_pos] = tmp;
 }
void ObjectBrowserWidget::toggleViewClicked () virtual slot
Definition at line 256 of file ObjectBrowserWidget.cpp.
References currentPage, LISTVIEWPAGE, ObjectItemText, ObjectListView, SELECTEDITEMPAGE, toggleViewButton, and updateSelectedItemsView().
Referenced by ObjectBrowserWidget(), and ObjectBrowserDialog::toggleViewClicked().
 {
   switch (currentPage)
     {
       case LISTVIEWPAGE:
         updateSelectedItemsView();
         currentPage = SELECTEDITEMPAGE;
         if (toggleViewButton) toggleViewButton->setText(trUtf8("Tree View"));
         ObjectListView->hide();
         ObjectItemText->show();
         break;
       case SELECTEDITEMPAGE:
         currentPage = LISTVIEWPAGE;
         if (toggleViewButton) toggleViewButton->setText(trUtf8("Selected Items"));
         ObjectListView->show();
         ObjectItemText->hide();
         break;
     }
 }
void ObjectBrowserWidget::updateSelectedItemsView () private
Definition at line 280 of file ObjectBrowserWidget.cpp.
References C_INT32, eXport(), FROM_UTF8, ObjectList::getRoot(), objectItemList, ObjectItemText, pdelete, and ObjectListItem::pItem.
Referenced by toggleViewClicked(), and updateUI().
 {
   std::vector< const CCopasiObject * > * outputVector;
   ObjectBrowserItem* rootItem;
   unsigned C_INT32 i;
   rootItem = objectItemList->getRoot()->pItem;
   outputVector = new std::vector< const CCopasiObject * >();
   eXport(rootItem, outputVector);
   //      CQMessageBox::information(this, "Output object list done!", "Selected CopasiObject list done!");
   //   ObjectListItem* pHead;
   ObjectItemText->clear();
   for (i = 0; i < outputVector->size(); i++)
     {
       //   if (double(i) / 2 == int(i / 2))
       //     ObjectItemText->setColor(red);
       //   else
       //     ObjectItemText->setColor(blue);
       if ((*outputVector)[i])
         {
           ObjectItemText->append(FROM_UTF8((*outputVector)[i]->getObjectDisplayName()));
           //ObjectItemText->insertParagraph(pHead->pItem->getObject()->pCopasiObject->getCN()., -1);
           //ObjectItemText->insertParagraph(FROM_UTF8((*outputVector)[i]->getObjectType()), -1);
         }
     }
   /*
   for (pHead = outputVector->getRoot(), i = 1; pHead != NULL; pHead = pHead->pNext)
   {
   if (double(i) / 2 == int(i / 2))
   ObjectItemText->setColor(red);
   else
   ObjectItemText->setColor(blue);
   if (pHead->pItem->getObject()->pCopasiObject)
   {
   //ObjectItemText->insertParagraph(pHead->pItem->getObject()->pCopasiObject->getCN()., -1);
   ObjectItemText->insertParagraph(pHead->pItem->getObject()->pCopasiObject->getObjectType()., -1);
   i++;
   }
   }
   */
   pdelete(outputVector);
 }
void ObjectBrowserWidget::updateUI ()
Definition at line 644 of file ObjectBrowserWidget.cpp.
References ObjectList::bucketPop(), ObjectList::createBucketIndex(), currentPage, ObjectList::destroyBucket(), ObjectBrowserItem::getKeySpace(), ObjectBrowserItem::getObject(), ObjectList::getRoot(), ObjectList::insertBucket(), ObjectListItem::pItem, ObjectListItem::pNext, CBrowserObject::referenceList, refreshList, SELECTEDITEMPAGE, setCheckMark(), and updateSelectedItemsView().
Referenced by clearClicked(), listviewChecked(), and selectObjects().
 {
   //refresh List stores all affected items,
   refreshList->createBucketIndex((int)ObjectBrowserItem::getKeySpace()); //construct index to do binary search
   for (ObjectListItem* pCurrent = refreshList->getRoot(); pCurrent != NULL; pCurrent = pCurrent->pNext)
     {
       ObjectListItem * pHead = pCurrent->pItem->getObject()->referenceList->getRoot();
       while (pHead != NULL)
         {
           ObjectBrowserItem * pCurrentLevel = pHead->pItem;
           if (pCurrent != pHead)
             for (; (pCurrentLevel != NULL); pCurrentLevel =
                    static_cast< ObjectBrowserItem * >(pCurrentLevel->parent()))
               refreshList->insertBucket(pCurrentLevel);
           pHead = pHead->pNext;
         }
     }
   int cursor = 0;
   for (ObjectBrowserItem* pUpdate = refreshList->bucketPop(cursor); pUpdate != NULL; pUpdate = refreshList->bucketPop(cursor))
     setCheckMark(pUpdate);
   refreshList->destroyBucket();
   if (currentPage == SELECTEDITEMPAGE) updateSelectedItemsView();
 }
Member Data Documentation
QPushButton* ObjectBrowserWidget::clearButton
Definition at line 62 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget().
QPushButton* ObjectBrowserWidget::commitButton
Definition at line 64 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget().
pageIndex ObjectBrowserWidget::currentPage private
Definition at line 99 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget(), toggleViewClicked(), and updateUI().
QFrame* ObjectBrowserWidget::Line1
Definition at line 66 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget().
std::vector< const CCopasiObject * >* ObjectBrowserWidget::mOutputObjectVector private
Definition at line 98 of file ObjectBrowserWidget.h.
Referenced by commitClicked(), and setOutputVector().
QGridLayout* ObjectBrowserWidget::ObjectBrowserLayout
Definition at line 61 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget().
ObjectList* ObjectBrowserWidget::objectItemList
Definition at line 58 of file ObjectBrowserWidget.h.
Referenced by cleanup(), commitClicked(), loadChild(), loadData(), loadField(), loadUI(), ObjectBrowserWidget(), selectObjects(), and updateSelectedItemsView().
QTextEdit* ObjectBrowserWidget::ObjectItemText
Definition at line 68 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget(), toggleViewClicked(), and updateSelectedItemsView().
QTreeWidget* ObjectBrowserWidget::ObjectListView
Definition at line 65 of file ObjectBrowserWidget.h.
Referenced by loadData(), ObjectBrowserWidget(), and toggleViewClicked().
ObjectList* ObjectBrowserWidget::refreshList
Definition at line 59 of file ObjectBrowserWidget.h.
Referenced by cleanup(), clearClicked(), clickToReverseCheck(), ObjectBrowserWidget(), selectObjects(), setCheck(), setUncheck(), and updateUI().
QSpacerItem* ObjectBrowserWidget::spacer
Definition at line 67 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget().
QPushButton* ObjectBrowserWidget::toggleViewButton
Definition at line 63 of file ObjectBrowserWidget.h.
Referenced by ObjectBrowserWidget(), and toggleViewClicked().
The documentation for this class was generated from the following files:
ObjectBrowserWidget.h
ObjectBrowserWidget.cpp