COPASI API: CQConnectionGraphicsItem Class Reference
CQConnectionGraphicsItem Class Reference
#include <CQConnectionGraphicsItem.h>
Public Member Functions
CQConnectionGraphicsItem (const CLGlyphWithCurve *glyph, const CLRenderResolver *resolver=NULL)
virtual ~CQConnectionGraphicsItem ()
Public Member Functions inherited from CQCopasiGraphicsItem
CQCopasiGraphicsItem (const CLRenderResolver *resolver, const CLStyle *style)
const CLRenderResolver * getResolver () const
const CLStyle * getStyle () const
void setResolver (const CLRenderResolver *resolver)
void setStyle (const CLStyle *style)
virtual ~CQCopasiGraphicsItem ()
Static Public Member Functions
static QSharedPointer
< QPainterPath > getPath (const CLCurve &curve)
Protected Member Functions
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option=new QStyleOptionGraphicsItem(), QWidget *widget=0)
Protected Attributes
bool mWasMoved
Protected Attributes inherited from CQCopasiGraphicsItem
const CLRenderResolver * mpResolver
const CLStyle * mpStyle
Detailed Description
Definition at line 18 of file CQConnectionGraphicsItem.h.
Constructor & Destructor Documentation
CQConnectionGraphicsItem::CQConnectionGraphicsItem (const CLGlyphWithCurve * glyph, const CLRenderResolver * resolver = NULL)
Definition at line 82 of file CQConnectionGraphicsItem.cpp.
References CQRenderConverter::applyStyle(), CCopasiVector< T >::begin(), COPASI_LAYOUT_KEY, CCopasiVector< T >::end(), CQRenderConverter::fillGroupFromStyle(), CLGraphicalObject::getBoundingBox(), CLGlyphWithCurve::getCurve(), CLStyle::getGroup(), CLGraphicalObject::getKey(), CLReactionGlyph::getListOfMetabReferenceGlyphs(), CLGeneralGlyph::getListOfReferenceGlyphs(), CLCurve::getNumCurveSegments(), getPath(), CQCopasiGraphicsItem::mpStyle, and CLRenderResolver::resolveStyle().
   : CQCopasiGraphicsItem(resolver, resolver != NULL ? resolver->resolveStyle(curveGlyph) : NULL)
   , mWasMoved(false)
 {
   setFlag(QGraphicsItem::ItemIsMovable);
   setFlag(QGraphicsItem::ItemSendsGeometryChanges);
   setData(COPASI_LAYOUT_KEY, QString(curveGlyph->getKey().c_str()));
   QSharedPointer<QPainterPath> path = getPath(curveGlyph->getCurve());
   QGraphicsPathItem* item;
   QGraphicsItemGroup* itemGroup;
   if (curveGlyph->getCurve().getNumCurveSegments() > 0)
     {
       item = new QGraphicsPathItem(*path);
       itemGroup = new QGraphicsItemGroup();
       itemGroup->addToGroup(item);
       if (mpStyle != NULL)
         CQRenderConverter::applyStyle(item, &curveGlyph->getBoundingBox(), mpStyle->getGroup(), resolver, itemGroup);
       addToGroup(itemGroup);
     }
   const CLReactionGlyph* reaction = dynamic_cast<const CLReactionGlyph*>(curveGlyph);
   if (reaction != NULL)
     {
       const CCopasiVector<CLMetabReferenceGlyph> & list = reaction->getListOfMetabReferenceGlyphs();
       for (CCopasiVector<CLMetabReferenceGlyph>::const_iterator it = list.begin(); it != list.end(); ++it)
         {
           const CLMetabReferenceGlyph* metab = *it;
           const CLStyle *style = resolver->resolveStyle(metab);
           if (metab->getCurve().getNumCurveSegments() > 0)
             {
               path = getPath(metab->getCurve());
               item = new QGraphicsPathItem(*path);
               itemGroup = new QGraphicsItemGroup();
               itemGroup->addToGroup(item);
               CQRenderConverter::applyStyle(item, &metab->getBoundingBox(), style == NULL ?
                                             mpStyle == NULL ? NULL :  mpStyle->getGroup()
                                               : style->getGroup(), resolver, itemGroup);
               addToGroup(itemGroup);
             }
         }
     }
   const CLGeneralGlyph* general = dynamic_cast<const CLGeneralGlyph*>(curveGlyph);
   if (general != NULL)
     {
       const CCopasiVector<CLReferenceGlyph> & list = general->getListOfReferenceGlyphs();
       for (CCopasiVector<CLReferenceGlyph>::const_iterator it = list.begin(); it != list.end(); ++it)
         {
           const CLReferenceGlyph* glyph = *it;
           const CLStyle *style = resolver->resolveStyle(glyph);
           if (glyph ->getCurve().getNumCurveSegments() > 0)
             {
               path = getPath(glyph ->getCurve());
               item = new QGraphicsPathItem(*path);
               itemGroup = new QGraphicsItemGroup();
               itemGroup->addToGroup(item);
               CQRenderConverter::applyStyle(item, &glyph ->getBoundingBox(), style == NULL ?
                                             mpStyle == NULL ? NULL :  mpStyle->getGroup()
                                               : style->getGroup(), resolver, itemGroup);
               addToGroup(itemGroup);
             }
         }
     }
   // add decorations on reactions
   itemGroup = new QGraphicsItemGroup();
   CQRenderConverter::fillGroupFromStyle(itemGroup, &curveGlyph->getBoundingBox(), mpStyle, resolver);
   if (itemGroup->childItems().size() > 0)
     addToGroup(itemGroup);
   else
     delete itemGroup;
 }
CQConnectionGraphicsItem::~CQConnectionGraphicsItem () virtual
Definition at line 166 of file CQConnectionGraphicsItem.cpp.
 {
 }
Member Function Documentation
QSharedPointer< QPainterPath > CQConnectionGraphicsItem::getPath (const CLCurve & curve) static
Definition at line 16 of file CQConnectionGraphicsItem.cpp.
References CLLineSegment::getBase1(), CLLineSegment::getBase2(), CLLineSegment::getEnd(), CLCurve::getNumCurveSegments(), CLCurve::getSegmentAt(), CLLineSegment::getStart(), CLPoint::getX(), CLPoint::getY(), and CLLineSegment::isBezier().
Referenced by CQConnectionGraphicsItem().
 {
   QSharedPointer<QPainterPath> result = QSharedPointer<QPainterPath>(new QPainterPath());
   for (size_t i = 0; i < curve.getNumCurveSegments(); ++i)
     {
       const CLLineSegment* segment = curve.getSegmentAt(i);
       QPainterPath path = QPainterPath(
                             QPointF(
                               segment->getStart().getX(),
                               segment->getStart().getY()));
       if (segment->isBezier())
         {
           path.cubicTo(
             segment->getBase1().getX(), segment->getBase1().getY(),
             segment->getBase2().getX(), segment->getBase2().getY(),
             segment->getEnd().getX(), segment->getEnd().getY()
           );
         }
       else
         {
           path.lineTo(segment->getEnd().getX(), segment->getEnd().getY());
         }
       result->addPath(path);
     }
   return result;
 }
QVariant CQConnectionGraphicsItem::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Definition at line 70 of file CQConnectionGraphicsItem.cpp.
References mWasMoved.
 {
   CQLayoutScene * currentScene = dynamic_cast<CQLayoutScene *>(scene());
   if (change == ItemPositionHasChanged && currentScene)
     {
       mWasMoved = true;
     }
   return QGraphicsItem::itemChange(change, value);
 }
void CQConnectionGraphicsItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 54 of file CQConnectionGraphicsItem.cpp.
References COPASI_LAYOUT_KEY, mWasMoved, and CQLayoutScene::updatePosition().
 {
   CQLayoutScene * currentScene = dynamic_cast<CQLayoutScene *>(scene());
   if (mWasMoved && currentScene)
     {
       QPointF currentPos = pos();
       currentScene->updatePosition(data(COPASI_LAYOUT_KEY).toString(), currentPos);
       mWasMoved = false;
     }
   else
     {
       QGraphicsItem::mouseReleaseEvent(event);
     }
 }
void CQConnectionGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option = new QStyleOptionGraphicsItem(), QWidget * widget = 0) protected virtual
Definition at line 47 of file CQConnectionGraphicsItem.cpp.
 {
   painter->save();
   QGraphicsItemGroup::paint(painter, option, widget);
   painter->restore();
 }
Member Data Documentation
bool CQConnectionGraphicsItem::mWasMoved protected
Definition at line 31 of file CQConnectionGraphicsItem.h.
Referenced by itemChange(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
CQConnectionGraphicsItem.h
CQConnectionGraphicsItem.cpp