COPASI API: CQPlotDM Class Reference
CQPlotDM Class Reference
#include <CQPlotDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQPlotDM (QObject *parent=0)
QVariant data (const QModelIndex &index, int role) const
Qt::ItemFlags flags (const QModelIndex &index) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
bool removeRows (QModelIndexList rows, const QModelIndex &index=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRow (int position)
Protected Member Functions
bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 30 of file CQPlotDM.h.
Constructor & Destructor Documentation
CQPlotDM::CQPlotDM (QObject * parent = 0)
Definition at line 22 of file CQPlotDM.cpp.
   : CQBaseDataModel(parent)
 {
 }
Member Function Documentation
int CQPlotDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 32 of file CQPlotDM.cpp.
References TOTAL_COLS_PLOTS.
Referenced by CQPlotsWidget::keyPressEvent().
 {
   return TOTAL_COLS_PLOTS;
 }
QVariant CQPlotDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 50 of file CQPlotDM.cpp.
References COL_ACTIVE_PLOTS, COL_CURVES_PLOTS, COL_NAME_PLOTS, COL_ROW_NUMBER, flags(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CPlotSpecification::getItems(), CCopasiObject::getObjectName(), CPlotSpecification::isActive(), CQBaseDataModel::isDefaultRow(), rowCount(), and CCopasiVector< T >::size().
Referenced by setData().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (index.column() > 0 && role == Qt::ForegroundRole && !(flags(index) & Qt::ItemIsEditable))
     return QColor(Qt::darkGray);
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       if (isDefaultRow(index))
         {
           switch (index.column())
             {
               case COL_ROW_NUMBER:
                 return QVariant(QString(""));
               case COL_NAME_PLOTS:
                 return QVariant(QString("New Plot"));
               case COL_ACTIVE_PLOTS:
                 if (role == Qt::DisplayRole)
                   return QVariant();
                 else
                   return QVariant(true);
               default:
                 return QVariant(QString(""));
             }
         }
       else
         {
           const CPlotSpecification *pPS = dynamic_cast<const CPlotSpecification*>((*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList()->operator[](index.row()));
           switch (index.column())
             {
               case COL_ROW_NUMBER:
                 return QVariant(index.row() + 1);
               case COL_NAME_PLOTS:
                 return QVariant(QString(FROM_UTF8(pPS->getObjectName())));
               case COL_CURVES_PLOTS:
                 return QVariant((unsigned int)pPS->getItems().size());
               case COL_ACTIVE_PLOTS:
                 if (role == Qt::DisplayRole)
                   return QVariant();
                 else
                   return QVariant(pPS->isActive());
             }
         }
     }
   else if (role == Qt::CheckStateRole && index.column() == COL_ACTIVE_PLOTS)
     return index.data(Qt::EditRole).toBool() ? QVariant(Qt::Checked) : QVariant(Qt::Unchecked);
   return QVariant();
 }
Qt::ItemFlags CQPlotDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 37 of file CQPlotDM.cpp.
References COL_ACTIVE_PLOTS, and COL_NAME_PLOTS.
Referenced by data().
 {
   if (!index.isValid())
     return Qt::ItemIsEnabled;
   if (index.column() == COL_NAME_PLOTS)
     return QAbstractItemModel::flags(index) | Qt::ItemIsEditable;
   else if (index.column() == COL_ACTIVE_PLOTS)
     return QAbstractItemModel::flags(index) | Qt::ItemIsSelectable | Qt::ItemIsUserCheckable;
   else
     return QAbstractItemModel::flags(index);
 }
QVariant CQPlotDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 112 of file CQPlotDM.cpp.
References COL_ACTIVE_PLOTS, COL_CURVES_PLOTS, COL_NAME_PLOTS, and COL_ROW_NUMBER.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
           case COL_NAME_PLOTS:
             return QVariant(QString("Name"));
           case COL_CURVES_PLOTS:
             return QVariant(QString("Nr. of Curves"));
           case COL_ACTIVE_PLOTS:
             return QVariant(QString("Active"));
           default:
             return QVariant();
         }
     }
   else
     return QString("%1").arg(section + 1);
 }
bool CQPlotDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 206 of file CQPlotDM.cpp.
References ListViews::ADD, COL_NAME_PLOTS, CQBaseDataModel::createNewName(), CCopasiRootContainer::getDatamodelList(), CQBaseDataModel::notifyGUI(), ListViews::PLOT, CPlotItem::plot2d, and TO_UTF8.
 {
   beginInsertRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       CPlotSpecification *pPS = (*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList()->createPlotSpec(TO_UTF8(createNewName("plot", COL_NAME_PLOTS)), CPlotItem::plot2d);
       emit notifyGUI(ListViews::PLOT, ListViews::ADD, pPS->CCopasiParameter::getKey());
     }
   endInsertRows();
   return true;
 }
bool CQPlotDM::removeRows (QModelIndexList rows, const QModelIndex & index = QModelIndex())
Definition at line 242 of file CQPlotDM.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getModel(), CCopasiDataModel::getPlotDefinitionList(), CQBaseDataModel::isDefaultRow(), and CQBaseDataModel::removeRow().
Referenced by CQPlotsWidget::deleteSelectedPlots().
 {
   if (rows.isEmpty())
     return false;
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (!pDataModel->getModel())
     return false;
 //Build the list of pointers to items to be deleted
 //before actually deleting any item.
   QList <CPlotSpecification *> pPSs;
   QModelIndexList::const_iterator i;
   CPlotSpecification * pPS = NULL;
   for (i = rows.begin(); i != rows.end(); ++i)
     {
       if (!isDefaultRow(*i) && pDataModel->getPlotDefinitionList()->operator[]((*i).row()))
         {
           pPS = pDataModel->getPlotDefinitionList()->operator[]((*i).row());
           pPSs.append(pPS);
         }
     }
   QList <CPlotSpecification *>::const_iterator j;
   for (j = pPSs.begin(); j != pPSs.end(); ++j)
     {
       pPS = *j;
       size_t delRow =
         pDataModel->getPlotDefinitionList()->CCopasiVector< CPlotSpecification >::getIndex(pPS);
       removeRow((int) delRow);
     }
   return true;
 }
bool CQPlotDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 221 of file CQPlotDM.cpp.
References ListViews::DELETE, CCopasiRootContainer::getDatamodelList(), CQBaseDataModel::notifyGUI(), and ListViews::PLOT.
 {
   if (rows <= 0)
     return true;
   beginRemoveRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       CPlotSpecification* pPS =
         (CPlotSpecification*)(*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList()->operator[](position);
       std::string deletedKey = pPS->CCopasiParameter::getKey();
       (*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList()->CCopasiVector< CPlotSpecification >::remove(position);
       emit notifyGUI(ListViews::PLOT, ListViews::DELETE, deletedKey);
     }
   endRemoveRows();
   return true;
 }
int CQPlotDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 28 of file CQPlotDM.cpp.
References CCopasiRootContainer::getDatamodelList().
Referenced by data(), and CQPlotsWidget::deleteSelectedPlots().
 {
   return (int)(*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList()->size() + 1;
 }
bool CQPlotDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 138 of file CQPlotDM.cpp.
References ListViews::CHANGE, COL_ACTIVE_PLOTS, COL_NAME_PLOTS, CQBaseDataModel::createNewName(), data(), CCopasiRootContainer::getDatamodelList(), CCopasiObject::getObjectName(), CQBaseDataModel::insertRow(), CPlotSpecification::isActive(), CQBaseDataModel::isDefaultRow(), CQBaseDataModel::notifyGUI(), ListViews::PLOT, CPlotSpecification::setActive(), CCopasiObject::setObjectName(), and TO_UTF8.
 {
   if (index.isValid() && role == Qt::EditRole)
     {
       bool changed = false;
       bool defaultRow = isDefaultRow(index);
       if (defaultRow)
         {
           if (index.data() != value)
             {
               insertRow();
               changed = true;
             }
           else
             return false;
         }
       CPlotSpecification *pPS = (CPlotSpecification*)(*CCopasiRootContainer::getDatamodelList())[0]->getPlotDefinitionList()->operator[](index.row());
       switch (index.column())
         {
           case COL_NAME_PLOTS:
             if (pPS->getObjectName() != TO_UTF8(value.toString()))
               {
                 pPS->setObjectName(TO_UTF8(value.toString()));
                 changed = true;
               }
             break;
           case COL_ACTIVE_PLOTS:
             if (pPS->isActive() != value.toBool())
               {
                 pPS->setActive(value.toBool());
                 changed = true;
               }
             break;
           default:
             break;
         }
       if (defaultRow && this->index(index.row(), COL_NAME_PLOTS).data().toString() == "plot")
         {
           pPS->setObjectName(TO_UTF8(createNewName("plot", COL_NAME_PLOTS)));
           changed = true;
         }
       if (changed)
         {
           emit dataChanged(index, index);
           emit notifyGUI(ListViews::PLOT, ListViews::CHANGE, pPS->CCopasiParameter::getKey());
         }
     }
   else if (role == Qt::CheckStateRole && index.column() == COL_ACTIVE_PLOTS)
     {
       QVariant data = value.toInt() == Qt::Checked ? QVariant(true) : QVariant(false);
       return setData(index, data, Qt::EditRole);
     }
   return true;
 }
The documentation for this class was generated from the following files:
CQPlotDM.h
CQPlotDM.cpp