COPASI API: CCopasiXMLParser::PolygonElement Class Reference
CCopasiXMLParser::PolygonElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
PolygonElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~PolygonElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Polygon = 0, ListOfElements }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4277 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::PolygonElement::Element private
Enumerator
Polygon
ListOfElements
Definition at line 4284 of file CCopasiXMLParser.h.
     {
       Polygon = 0,
       ListOfElements
     };
Constructor & Destructor Documentation
CCopasiXMLParser::PolygonElement::PolygonElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 11971 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::PolygonElement::~PolygonElement () virtual
Destructor
Definition at line 11976 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::PolygonElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 12090 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pListOfCurveElements, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Polygon:
         if (strcmp(pszName, "Polygon"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Polygon", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCommon.pListOfCurveElements = NULL;
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case ListOfElements:
         if (strcmp(pszName, "ListOfElements"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfElements", mParser.getCurrentLineNumber());
         //tell the handler where to continue
         mCurrentElement = Polygon;
         //no need to delete Handler (since it is the only one the destructor
         //will handle it)
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::PolygonElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 11981 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CLGraphicalPrimitive2D::EVENODD, CCopasiMessage::EXCEPTION, CLGroup::getElement(), CLPolygon::getListOfElements(), CLGroup::getNumElements(), CLGraphicalPrimitive2D::INHERIT, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive2D::NONZERO, CLGraphicalPrimitive1D::parseDashArray(), CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, SCopasiXMLParserCommon::pListOfCurveElements, CLGraphicalPrimitive2D::setFillColor(), CLGraphicalPrimitive2D::setFillRule(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), strToDouble(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * Stroke;
   const char * StrokeWidth;
   const char * StrokeDashArray;
   const char * Fill;
   const char * FillRule;
   CLPolygon* pPolygon = NULL;
   switch (mCurrentElement)
     {
       case Polygon:
         if (strcmp(pszName, "Polygon"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Polygon", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         Stroke = mParser.getAttributeValue("stroke", papszAttrs, false);
         StrokeWidth = mParser.getAttributeValue("stroke-width", papszAttrs, false);
         StrokeDashArray = mParser.getAttributeValue("stroke-dasharray", papszAttrs, false);
         Fill = mParser.getAttributeValue("fill", papszAttrs, false);
         FillRule = mParser.getAttributeValue("fill-rule", papszAttrs, false);
         pPolygon = new CLPolygon();
         if (Transform != NULL)
           {
             pPolygon->parseTransformation(Transform);
           }
         if (Stroke != NULL)
           {
             pPolygon->setStroke(Stroke);
           }
         if (StrokeWidth != NULL)
           {
             double width = strToDouble(StrokeWidth, NULL);
             pPolygon->setStrokeWidth(width);
           }
         if (StrokeDashArray != NULL)
           {
             pPolygon->parseDashArray(StrokeDashArray);
           }
         if (Fill != NULL)
           {
             pPolygon->setFillColor(Fill);
           }
         if (FillRule != NULL)
           {
             std::string f(FillRule);
             if (f == "nonzero")
               {
                 pPolygon->setFillRule(CLGraphicalPrimitive2D::NONZERO);
               }
             else if (f == "evenodd")
               {
                 pPolygon->setFillRule(CLGraphicalPrimitive2D::EVENODD);
               }
             else
               {
                 pPolygon->setFillRule(CLGraphicalPrimitive2D::INHERIT);
               }
           }
         mCommon.pGroup->addChildElement(pPolygon);
         // delete the polygon again since the addElement method made a copy
         delete pPolygon;
         pPolygon = dynamic_cast<CLPolygon*>(mCommon.pGroup->getElement(mCommon.pGroup->getNumElements() - 1));
         assert(pPolygon != NULL);
         mCommon.pListOfCurveElements = pPolygon->getListOfElements();
         break;
       case ListOfElements:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "ListOfElements"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "ListOfElements", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new ListOfCurveElementsElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp