COPASI API: CCopasiXMLParser::RadialGradientElement Class Reference
CCopasiXMLParser::RadialGradientElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
RadialGradientElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~RadialGradientElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { RadialGradient = 0, GradientStop }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3830 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::RadialGradientElement::Element private
Enumerator
RadialGradient
GradientStop
Definition at line 3837 of file CCopasiXMLParser.h.
     {
       RadialGradient = 0,
       GradientStop
     };
Constructor & Destructor Documentation
CCopasiXMLParser::RadialGradientElement::RadialGradientElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 11498 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::RadialGradientElement::~RadialGradientElement () virtual
Destructor
Definition at line 11503 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::RadialGradientElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 11629 of file CCopasiXMLParser.cpp.
References CLRenderInformationBase::addGradientDefinition(), CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pGradient, SCopasiXMLParserCommon::pRenderInformation, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case RadialGradient:
         if (strcmp(pszName, "RadialGradient"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "RadialGradient", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCommon.pRenderInformation->addGradientDefinition(mCommon.pGradient);
         // delete the gradient since the add method made a copy
         delete mCommon.pGradient;
         mCommon.pGradient = NULL;
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case GradientStop:
         if (strcmp(pszName, "Stop"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Stop", mParser.getCurrentLineNumber());
         //tell the handler where to continue
         mCurrentElement = RadialGradient;
         //no need to delete Handler (since it is the only one the destructor
         //will handle it)
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::RadialGradientElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 11508 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGradientBase::PAD, SCopasiXMLParserCommon::pGradient, CLGradientBase::REFLECT, CLGradientBase::REPEAT, CLRadialGradient::setCenter(), CLRadialGradient::setFocalPoint(), CLGradientBase::setId(), CLRadialGradient::setRadius(), CLGradientBase::setSpreadMethod(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * CX;
   const char * CY;
   const char * CZ;
   const char * R;
   const char * FX;
   const char * FY;
   const char * FZ;
   const char * ID;
   const char * SPREADMETHOD;
   CLRadialGradient* pRadialGradient = NULL;
   switch (mCurrentElement)
     {
       case RadialGradient:
         if (strcmp(pszName, "RadialGradient"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "RadialGradient", mParser.getCurrentLineNumber());
         CX = mParser.getAttributeValue("cx", papszAttrs, false);
         CY = mParser.getAttributeValue("cy", papszAttrs, false);
         CZ = mParser.getAttributeValue("cz", papszAttrs, false);
         FX = mParser.getAttributeValue("fx", papszAttrs, false);
         FY = mParser.getAttributeValue("fy", papszAttrs, false);
         FZ = mParser.getAttributeValue("fz", papszAttrs, false);
         R =  mParser.getAttributeValue("r", papszAttrs);
         ID = mParser.getAttributeValue("id", papszAttrs);
         SPREADMETHOD = mParser.getAttributeValue("spreadMethod", papszAttrs, "pad");
         pRadialGradient = new CLRadialGradient();
         pRadialGradient->setId(ID);
         if (CX == NULL)
           {
             CX = "50%";
           }
         if (CY == NULL)
           {
             CY = "50%";
           }
         if (CZ == NULL)
           {
             CZ = "50%";
           }
         pRadialGradient->setCenter(CLRelAbsVector(CX), CLRelAbsVector(CY), CLRelAbsVector(CZ));
         if (R == NULL)
           {
             R = "50%";
           }
         pRadialGradient->setRadius(CLRelAbsVector(R));
         if (FX == NULL)
           {
             FX = CX;
           }
         if (FY == NULL)
           {
             FY = CY;
           }
         if (FZ == NULL)
           {
             FZ = CZ;
           }
         pRadialGradient->setFocalPoint(CLRelAbsVector(FX), CLRelAbsVector(FY), CLRelAbsVector(FZ));
         if (!strcmp(SPREADMETHOD, "reflect"))
           {
             pRadialGradient->setSpreadMethod(CLGradientBase::REFLECT);
           }
         else if (!strcmp(SPREADMETHOD, "repeat"))
           {
             pRadialGradient->setSpreadMethod(CLGradientBase::REPEAT);
           }
         else
           {
             pRadialGradient->setSpreadMethod(CLGradientBase::PAD);
           }
         mCommon.pGradient = pRadialGradient;
         break;
       case GradientStop:
         //only one type of tags may occur here, so we can throw an exception.
         //No need to silently ignore unknown tags here.
         if (strcmp(pszName, "Stop"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Stop", mParser.getCurrentLineNumber());
         //only one type of tags may occur here, so if the handler exists
         //it must be the correct one
         if (!mpCurrentHandler)
           mpCurrentHandler = new GradientStopElement(mParser, mCommon);
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp