COPASI API: CScanWidgetScan Class Reference
CScanWidgetScan Class Reference
#include <CScanWidgetScan.h>
Public Member Functions
CScanWidgetScan (QWidget *parent=0)
CScanWidgetScan (const CScanWidgetScan &src, QWidget *parent=0)
void initFromObject (const CCopasiObject *obj)
virtual void load (const CCopasiParameterGroup *pItem)
virtual bool save (CCopasiParameterGroup *pItem) const
virtual ~CScanWidgetScan ()
Public Member Functions inherited from CScanItemData
CScanItemData (const CScanItemData &src)
const CScanProblem::Type & getType () const
virtual ~CScanItemData ()
Protected Slots
virtual void slotChooseObject ()
Protected Attributes
const CCopasiObject * mpObject
Protected Attributes inherited from CScanItemData
CCopasiParameterGroup * mpData
CScanProblem::Type mType
Private Member Functions
void init ()
Additional Inherited Members
Protected Member Functions inherited from CScanItemData
CScanItemData (const CScanProblem::Type &type)
Detailed Description
Definition at line 30 of file CScanWidgetScan.h.
Constructor & Destructor Documentation
CScanWidgetScan::CScanWidgetScan (QWidget * parent = 0)
Definition at line 37 of file CScanWidgetScan.cpp.
References CQIconResource::copasi, CQIconResource::icon(), and init().
                                                 :
     QWidget(parent),
     CScanItemData(CScanProblem::SCAN_LINEAR)
 {
   setupUi(this);
   buttonObject->setIcon(CQIconResource::icon(CQIconResource::copasi));
   init();
 }
CScanWidgetScan::CScanWidgetScan (const CScanWidgetScan & src, QWidget * parent = 0)
Definition at line 48 of file CScanWidgetScan.cpp.
References CQIconResource::copasi, CQIconResource::icon(), init(), load(), and CScanItemData::mpData.
                                                                               :
     QWidget(parent),
     CScanItemData(src)
 {
   setupUi(this);
   buttonObject->setIcon(CQIconResource::icon(CQIconResource::copasi));
   init();
   load(mpData);
 }
CScanWidgetScan::~CScanWidgetScan () virtual
Definition at line 63 of file CScanWidgetScan.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CScanWidgetScan::init () private
Definition at line 68 of file CScanWidgetScan.cpp.
References mpObject.
Referenced by CScanWidgetScan().
 {
   lineEditObject->setReadOnly(true);
   lineEditNumber->setValidator(new QIntValidator(lineEditNumber));
   lineEditMin->setValidator(new QDoubleValidator(lineEditMin));
   lineEditMax->setValidator(new QDoubleValidator(lineEditMax));
   mpObject = NULL;
 }
void CScanWidgetScan::initFromObject (const CCopasiObject * obj)
Definition at line 91 of file CScanWidgetScan.cpp.
References C_FLOAT64, FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiObject::getValuePointer(), CCopasiObject::isValueDbl(), and mpObject.
Referenced by ScanWidget::slotAddItem(), and slotChooseObject().
 {
   mpObject = obj;
   if (obj)
     {
       lineEditObject->setText(FROM_UTF8(obj->getObjectDisplayName()));
       if (obj->isValueDbl())
         {
           C_FLOAT64 value = *(C_FLOAT64*)obj->getValuePointer();
           lineEditNumber->setText("10");
           lineEditMin->setText(QString::number(value*0.5));
           lineEditMax->setText(QString::number(value*2));
         }
     }
   else
     {
       lineEditObject->setText("");
       lineEditNumber->setText("");
       lineEditMin->setText("");
       lineEditMax->setText("");
     }
 }
void CScanWidgetScan::load (const CCopasiParameterGroup * pItem) virtual
Implements CScanItemData.
Definition at line 117 of file CScanWidgetScan.cpp.
References C_FLOAT64, C_INT32, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDisplayName(), CCopasiParameterGroup::getValue(), CScanItemData::mpData, mpObject, CCopasiParameter::Value::pVOID, and CScanProblem::SCAN_LINEAR.
Referenced by CScanWidgetScan(), and ScanWidget::loadTask().
 {
   if (pItem == NULL) return;
   *mpData = *pItem;
   void * tmp;
   if (!(tmp = mpData->getValue("Type").pVOID)) return;
   CScanProblem::Type type = *(CScanProblem::Type*)tmp;
   if (type != CScanProblem::SCAN_LINEAR)
     return;
   if (!(tmp = mpData->getValue("Number of steps").pVOID)) return;
   lineEditNumber->setText(QString::number(*(C_INT32*)tmp));
   if (!(tmp = mpData->getValue("Object").pVOID)) return;
   std::string tmpString = *(std::string*)tmp;
   if (tmpString == "")
     mpObject = NULL;
   else
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
       assert(pDataModel != NULL);
       mpObject = pDataModel->getDataObject(tmpString);
     }
   if (mpObject)
     lineEditObject->setText(FROM_UTF8(mpObject->getObjectDisplayName()));
   else
     lineEditObject->setText("");
   if (!(tmp = mpData->getValue("Minimum").pVOID)) return;
   lineEditMin->setText(QString::number(*(C_FLOAT64*)tmp));
   if (!(tmp = mpData->getValue("Maximum").pVOID)) return;
   lineEditMax->setText(QString::number(*(C_FLOAT64*)tmp));
   if (!(tmp = mpData->getValue("log").pVOID)) return;
   checkBoxLog->setChecked(*(bool*)tmp);
   return;
 }
bool CScanWidgetScan::save (CCopasiParameterGroup * pItem) const virtual
Implements CScanItemData.
Definition at line 171 of file CScanWidgetScan.cpp.
References CCopasiObject::getCN(), CScanItemData::mpData, mpObject, and CCopasiParameterGroup::setValue().
 {
   mpData->setValue("Number of steps", lineEditNumber->text().toUInt());
   mpData->setValue("Minimum", lineEditMin->text().toDouble());
   mpData->setValue("Maximum", lineEditMax->text().toDouble());
   mpData->setValue("log", checkBoxLog->isChecked());
   if (mpObject != NULL)
     {
       mpData->setValue("Object", mpObject->getCN());
     }
   else
     {
       mpData->setValue("Object", std::string(""));
     }
   if (pItem != NULL)
     {
       if (*mpData == *pItem) return false;
       *pItem = *mpData;
       return true;
     }
   return false;
 }
void CScanWidgetScan::slotChooseObject () protected virtual slot
Definition at line 79 of file CScanWidgetScan.cpp.
References CCopasiSelectionDialog::getObjectSingle(), initFromObject(), CQSimpleSelectionTree::InitialTime, mpObject, and CQSimpleSelectionTree::Parameters.
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
                                             CQSimpleSelectionTree::InitialTime |
                                             CQSimpleSelectionTree::Parameters,
                                             mpObject);
   if (mpObject != pObject) // Object selection changed.
     initFromObject(pObject);
 }
Member Data Documentation
const CCopasiObject* CScanWidgetScan::mpObject protected
Definition at line 49 of file CScanWidgetScan.h.
Referenced by init(), initFromObject(), load(), save(), and slotChooseObject().
The documentation for this class was generated from the following files:
CScanWidgetScan.h
CScanWidgetScan.cpp