COPASI API: CCopasiXMLParser::ModelElement Class Reference
CCopasiXMLParser::ModelElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ModelElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ModelElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Model = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
InitialExpression, ListOfCompartments, ListOfMetabolites, ListOfModelValues,
ListOfReactions, ListOfEvents, ListOfModelParameterSets, StateTemplate,
InitialState
}
Private Attributes
std::string mKey
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1801 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ModelElement::Element private
Enum of invoked parsers
Enumerator
Model
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
InitialExpression
ListOfCompartments
ListOfMetabolites
ListOfModelValues
ListOfReactions
ListOfEvents
ListOfModelParameterSets
StateTemplate
InitialState
Definition at line 1809 of file CCopasiXMLParser.h.
     {
       Model = 0,
       MiriamAnnotation,
       Comment,
       ListOfUnsupportedAnnotations,
       InitialExpression,
       ListOfCompartments,
       ListOfMetabolites,
       ListOfModelValues,
       ListOfReactions,
       ListOfEvents,
       ListOfModelParameterSets,
       StateTemplate,
       InitialState
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ModelElement::ModelElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 1608 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ModelElement::~ModelElement () virtual
Destructor
Definition at line 1613 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::ModelElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 1834 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CModel::getKey(), CCopasiMessage::getLastMessage(), CAnnotation::getUnsupportedAnnotations(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, CModel::setCompileFlag(), CModelEntity::setInitialExpression(), CAnnotation::setMiriamAnnotation(), CAnnotation::setNotes(), CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Model:
         if (strcmp(pszName, "Model"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Model", mParser.getCurrentLineNumber());
         mCommon.pModel->setCompileFlag(true);
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         mCommon.pModel->setMiriamAnnotation(mCommon.CharacterData, mCommon.pModel->getKey(), mKey);
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         mCommon.pModel->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         mCommon.pModel->getUnsupportedAnnotations() = mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case InitialExpression:
         if (strcmp(pszName, "InitialExpression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialExpression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mCommon.pModel->setInitialExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         // Old CopasiML files have the incorrect order and the comment may appear after
         // the initial expression. Therefore, we reset to MiriamAnnotation.
         mCurrentElement = MiriamAnnotation;
         break;
       case ListOfCompartments:
         if (strcmp(pszName, "ListOfCompartments"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfCompartments", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         break;
       case ListOfMetabolites:
         if (strcmp(pszName, "ListOfMetabolites"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfMetabolites", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         break;
       case ListOfModelValues:
         if (strcmp(pszName, "ListOfModelValues"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfModelValues", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         break;
       case ListOfReactions:
         if (strcmp(pszName, "ListOfReactions"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfReactions", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         break;
       case ListOfEvents:
         if (strcmp(pszName, "ListOfEvents"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfEvents", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         break;
       case ListOfModelParameterSets:
         if (strcmp(pszName, "ListOfModelParameterSets"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfModelParameterSets", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         mCurrentElement = Model; // This is possibly the last element.
         break;
       case StateTemplate:
         if (strcmp(pszName, "StateTemplate"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "StateTemplate", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         break;
       case InitialState:
         if (strcmp(pszName, "InitialState"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialState", mParser.getCurrentLineNumber());
         deleteCurrentHandler();
         mCurrentElement = Model; // This is possibly the last element.
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         mCurrentElement = Model; // This is possibly the last element.
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ModelElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 1618 of file CCopasiXMLParser.cpp.
References CModel::AreaUnitNames, C_FLOAT64, CModel::deterministic, CCopasiMessage::EXCEPTION, CModel::getModelParameterSets(), CModel::LengthUnitNames, CModel::m, CModel::m2, CCopasiXMLParser::mCommon, MCXML, CModel::min, CModel::ml, CModel::mMol, CModel::ModelTypeNames, CExpatTemplate< CExpat >::mParser, CModel::OldMinute, CModel::OldXML, SCopasiXMLParserCommon::pDataModel, SCopasiXMLParserCommon::pModel, CModel::QuantityUnitNames, CModel::QuantityUnitOldXMLNames, CModel::s, CModel::setAreaUnit(), CModel::setAvogadro(), CModel::setLengthUnit(), CModel::setModelType(), CCopasiObject::setObjectName(), CModel::setQuantityUnit(), CModel::setTimeUnit(), CModel::setVolumeUnit(), CModel::TimeUnitNames, toEnum(), UNKNOWN_ELEMENT, and CModel::VolumeUnitNames.
 {
   const char * Name;
   const char * timeUnit;
   CModel::TimeUnit TimeUnit;
   const char * volumeUnit;
   CModel::VolumeUnit VolumeUnit;
   const char * areaUnit;
   CModel::AreaUnit AreaUnit;
   const char * lengthUnit;
   CModel::LengthUnit LengthUnit;
   const char * quantityUnit;
   CModel::QuantityUnit QuantityUnit;
   CModel::ModelType ModelType;
   C_FLOAT64 Avogadro;
   mpCurrentHandler = NULL;
   mCurrentElement++; /* We should always be on the next element */
   switch (mCurrentElement)
     {
       case Model:
         if (strcmp(pszName, "Model"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Model", mParser.getCurrentLineNumber());
         mKey = mParser.getAttributeValue("key", papszAttrs);
         Name = mParser.getAttributeValue("name", papszAttrs);
         timeUnit = mParser.getAttributeValue("timeUnit", papszAttrs);
         TimeUnit = toEnum(timeUnit, CModel::TimeUnitNames, CModel::OldMinute);
         if (TimeUnit == CModel::OldMinute)
           {
             if (strcmp(timeUnit, "m"))
               TimeUnit = CModel::s;
             else
               TimeUnit = CModel::min;
           }
         volumeUnit = mParser.getAttributeValue("volumeUnit", papszAttrs);
         VolumeUnit = toEnum(volumeUnit, CModel::VolumeUnitNames, CModel::ml);
         //the next 2 attributes are introduced in Build 31, they have a default for
         //reading older cps files
         areaUnit = mParser.getAttributeValue("areaUnit", papszAttrs, "m\xc2\xb2");
         AreaUnit = toEnum(areaUnit, CModel::AreaUnitNames, CModel::m2);
         lengthUnit = mParser.getAttributeValue("lengthUnit", papszAttrs, "m");
         LengthUnit = toEnum(lengthUnit, CModel::LengthUnitNames, CModel::m);
         quantityUnit = mParser.getAttributeValue("quantityUnit", papszAttrs);
         QuantityUnit = toEnum(quantityUnit, CModel::QuantityUnitNames, CModel::OldXML);
         if (QuantityUnit == CModel::OldXML)
           QuantityUnit = toEnum(quantityUnit, CModel::QuantityUnitOldXMLNames, CModel::mMol);
         ModelType = toEnum(mParser.getAttributeValue("type", papszAttrs, "deterministic"),
                            CModel::ModelTypeNames, CModel::deterministic);
         Avogadro = CCopasiXMLInterface::DBL(mParser.getAttributeValue("avogadroConstant", papszAttrs, "6.0221415e23"));
         if (!mCommon.pModel) mCommon.pModel = new CModel(mCommon.pDataModel);
         // We remove the default parameter set:
         mCommon.pModel->getModelParameterSets().CCopasiVector< CModelParameterSet >::remove((size_t) 0);
         addFix(mKey, mCommon.pModel);
         mCommon.pModel->setObjectName(Name);
         mCommon.pModel->setTimeUnit(TimeUnit);
         mCommon.pModel->setVolumeUnit(VolumeUnit);
         mCommon.pModel->setAreaUnit(AreaUnit);
         mCommon.pModel->setLengthUnit(LengthUnit);
         mCommon.pModel->setQuantityUnit(QuantityUnit);
         mCommon.pModel->setModelType(ModelType);
         mCommon.pModel->setAvogadro(Avogadro);
         return;
         break;
       case MiriamAnnotation:
         if (!strcmp(pszName, "MiriamAnnotation"))
           {
             mpCurrentHandler = &mParser.mMiriamAnnotationElement;
             mLastKnownElement = mCurrentElement;
           }
         break;
       case Comment:
         if (!strcmp(pszName, "Comment"))
           {
             mpCurrentHandler = &mParser.mCommentElement;
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfUnsupportedAnnotations:
         if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
           {
             mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             mLastKnownElement = mCurrentElement;
           }
         break;
       case InitialExpression:
         if (!strcmp(pszName, "InitialExpression"))
           {
             mpCurrentHandler = &mParser.mCharacterDataElement;
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfCompartments:
         if (!strcmp(pszName, "ListOfCompartments"))
           {
             mpCurrentHandler = new ListOfCompartmentsElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfMetabolites:
         if (!strcmp(pszName, "ListOfMetabolites"))
           {
             mpCurrentHandler = new ListOfMetabolitesElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfModelValues:
         if (!strcmp(pszName, "ListOfModelValues"))
           {
             mpCurrentHandler = new ListOfModelValuesElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfReactions:
         if (!strcmp(pszName, "ListOfReactions"))
           {
             mpCurrentHandler = new ListOfReactionsElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfEvents:
         if (!strcmp(pszName, "ListOfEvents"))
           {
             mpCurrentHandler = new ListOfEventsElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case ListOfModelParameterSets:
         if (!strcmp(pszName, "ListOfModelParameterSets"))
           {
             mpCurrentHandler = new ListOfModelParameterSetsElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case StateTemplate:
         if (!strcmp(pszName, "StateTemplate"))
           {
             mpCurrentHandler = new StateTemplateElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       case InitialState:
         if (!strcmp(pszName, "InitialState"))
           {
             mpCurrentHandler = new InitialStateElement(mParser, mCommon);
             mLastKnownElement = mCurrentElement;
           }
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler =  &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::ModelElement::mKey private
The key in the CopasiML file
Definition at line 1829 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp