COPASI API: CQCopasiApplication Class Reference
CQCopasiApplication Class Reference
#include <CQCopasiApplication.h>
Public Member Functions
CQCopasiApplication (int &argc, char **argv)
virtual bool event (QEvent *pEvent)
void setMainWindow (CopasiUI3Window *pMainWindow)
virtual ~CQCopasiApplication ()
Private Attributes
QString mFile
CopasiUI3Window * mpMainWindow
bool mStarting
Detailed Description
Definition at line 14 of file CQCopasiApplication.h.
Constructor & Destructor Documentation
CQCopasiApplication::CQCopasiApplication (int & argc, char ** argv)
Definition at line 39 of file CQCopasiApplication.cpp.
                                                                 :
   QApplication(argc, argv),
   mpMainWindow(NULL),
   mFile(),
   mStarting(true)
 {
 #if WIN32
   if (IsWindows8())
     setStyle(new QWindowsVistaStyle);
 #endif
 // Alter styles using Qt's CSS-like mechanism
   QString globalStyleSheet =
     "QLineEdit[readOnly=\"true\"] {\n"  // When readOnly
     "  color: gray;\n"                  // make text gray and
     "  border: false;\n"                // remove box border.
     "}\n";   //can add future items after this (move semicolon down)
   qApp->setStyleSheet(globalStyleSheet);
 }
CQCopasiApplication::~CQCopasiApplication () virtual
Definition at line 62 of file CQCopasiApplication.cpp.
 {
 }
Member Function Documentation
bool CQCopasiApplication::event (QEvent * pEvent) virtual
Definition at line 67 of file CQCopasiApplication.cpp.
References mFile, mpMainWindow, mStarting, and CopasiUI3Window::slotFileOpen().
 {
   switch (pEvent->type())
     {
       case QEvent::FileOpen:
         if (mStarting)
           {
             mFile = static_cast<QFileOpenEvent *>(pEvent)->file();
           }
         else
           {
             // need to take the new file, otherwise whenever the application
             // is open we will re-open the first file that was supposed to be
             // opened.
             mFile = static_cast<QFileOpenEvent *>(pEvent)->file();
             mpMainWindow->slotFileOpen(mFile);
           }
         pEvent->accept();
         return true;
         break;
       default:
         break;
     }
   return QApplication::event(pEvent);
 }
void CQCopasiApplication::setMainWindow (CopasiUI3Window * pMainWindow)
Definition at line 98 of file CQCopasiApplication.cpp.
References mFile, mpMainWindow, mStarting, and CopasiUI3Window::openInitialDocument().
Referenced by main().
 {
   mpMainWindow = pMainWindow;
   processEvents();
   mpMainWindow->openInitialDocument(mFile);
   mStarting = false;
 }
Member Data Documentation
QString CQCopasiApplication::mFile private
Definition at line 34 of file CQCopasiApplication.h.
Referenced by event(), and setMainWindow().
CopasiUI3Window* CQCopasiApplication::mpMainWindow private
Definition at line 32 of file CQCopasiApplication.h.
Referenced by event(), and setMainWindow().
bool CQCopasiApplication::mStarting private
Definition at line 36 of file CQCopasiApplication.h.
Referenced by event(), and setMainWindow().
The documentation for this class was generated from the following files:
CQCopasiApplication.h
CQCopasiApplication.cpp