COPASI API: CQValidatorDouble Class Reference
CQValidatorDouble Class Reference
#include <CQValidator.h>
Public Member Functions
CQValidatorDouble (QLineEdit *parent, const char *name=0)
void setRange (const C_FLOAT64 &lowerBound, const C_FLOAT64 &upperBound)
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QLineEdit >
CQValidator (QLineEdit *parent, QString(QLineEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Protected Attributes
QDoubleValidator * mpDoubleValidator
Protected Attributes inherited from CQValidator< QLineEdit >
QString mLastAccepted
QLineEdit * mpContainer
QString(QLineEdit::* mRetrieve)(void) const
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QLineEdit >
State setColor (const State &state) const
Detailed Description
Definition at line 144 of file CQValidator.h.
Constructor & Destructor Documentation
CQValidatorDouble::CQValidatorDouble (QLineEdit * parent, const char * name = 0)
Definition at line 66 of file CQValidator.cpp.
                                                                          :
   CQValidator< QLineEdit >(parent, &QLineEdit::text, name),
   mpDoubleValidator(new QDoubleValidator(-std::numeric_limits< C_FLOAT64 >::max(), std::numeric_limits< C_FLOAT64 >::max(), std::numeric_limits< C_FLOAT64 >::digits10, this))
 {}
Member Function Documentation
void CQValidatorDouble::setRange (const C_FLOAT64 & lowerBound, const C_FLOAT64 & upperBound)
Definition at line 80 of file CQValidator.cpp.
References mpDoubleValidator.
Referenced by CQCrossSectionTaskWidget::init(), CQTSSAWidget::init(), and CQTrajectoryWidget::init().
 {mpDoubleValidator->setRange(lowerBound, upperBound, std::numeric_limits< C_FLOAT64 >::digits10);}
QValidator::State CQValidatorDouble::validate (QString & input, int & pos) const virtual
Reimplemented from CQValidator< QLineEdit >.
Definition at line 71 of file CQValidator.cpp.
References mpDoubleValidator, and CQValidator< QLineEdit >::setColor().
 {
   if (mpDoubleValidator->validate(input, pos) == Acceptable)
     return CQValidator< QLineEdit >::validate(input, pos);
   setColor(Invalid);
   return Intermediate;
 }
Member Data Documentation
QDoubleValidator* CQValidatorDouble::mpDoubleValidator protected
Definition at line 156 of file CQValidator.h.
Referenced by setRange(), and validate().
The documentation for this class was generated from the following files:
CQValidator.h
CQValidator.cpp