COPASI API: CCopasiXMLParser::ReportInstanceElement Class Reference
CCopasiXMLParser::ReportInstanceElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ReportInstanceElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ReportInstanceElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Report = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2175 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ReportInstanceElement::Element private
Enum of invoked parsers
Enumerator
Report
Definition at line 2183 of file CCopasiXMLParser.h.
     {
       Report = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ReportInstanceElement::ReportInstanceElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 8747 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ReportInstanceElement::~ReportInstanceElement () virtual
Destructor
Definition at line 8752 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::ReportInstanceElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 8799 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Report:
         if (strcmp(pszName, "Report"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Report", mParser.getCurrentLineNumber());
         mCurrentElement = START_ELEMENT;
         mParser.popElementHandler();
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
 }
void CCopasiXMLParser::ReportInstanceElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 8755 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiTask::getReport(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentTask, CReport::setAppend(), CReport::setConfirmOverwrite(), CReport::setTarget(), SCopasiXMLParserCommon::taskReferenceMap, and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; // We should always be on the next element
   std::string target;
   bool append;
   bool confirmOverwrite;
   std::string reference;
   switch (mCurrentElement)
     {
       case Report:
         if (strcmp(pszName, "Report"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Report", mParser.getCurrentLineNumber());
         reference = mParser.getAttributeValue("reference", papszAttrs);
         target = mParser.getAttributeValue("target", papszAttrs);
         append = mParser.toBool(mParser.getAttributeValue("append", papszAttrs, "false"));
         mCommon.pCurrentTask->getReport().setAppend(append);
         confirmOverwrite = mParser.toBool(mParser.getAttributeValue("confirmOverwrite", papszAttrs, "false"));
         mCommon.pCurrentTask->getReport().setConfirmOverwrite(confirmOverwrite);
         mCommon.pCurrentTask->getReport().setTarget(target);
         if (mCommon.taskReferenceMap.find(reference) == mCommon.taskReferenceMap.end())
           {
             mCommon.taskReferenceMap[reference] = std::vector<CCopasiTask*>();
           }
         mCommon.taskReferenceMap[reference].push_back(mCommon.pCurrentTask);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp