COPASI API: CBitPatternTreeNode Class Reference
CBitPatternTreeNode Class Reference
#include <CBitPatternTreeNode.h>
Public Member Functions
CBitPatternTreeNode (const CBitPatternTreeNode &src)
CBitPatternTreeNode (const size_t &index, const std::vector< CStepMatrixColumn * > &patterns)
size_t getChildrenCount () const
const CBitPatternTreeNode * getSetChild () const
const CStepMatrixColumn * getStepMatrixColumn () const
const CBitPatternTreeNode * getUnsetChild () const
const CZeroSet & getZeroSet () const
bool hasSuperset (const CZeroSet &set) const
virtual ~CBitPatternTreeNode (void)
Private Member Functions
CBitPatternTreeNode ()
size_t nextAvailableIndex () const
void splitPatterns (const std::vector< CStepMatrixColumn * > &patterns)
Private Attributes
bool mIgnoreCheck
size_t mIndex
CBitPatternTreeNode * mpSetChild
CStepMatrixColumn * mpStepMatrixColumn
CBitPatternTreeNode * mpUnsetChild
CZeroSet * mpZeroSet
Detailed Description
Definition at line 24 of file CBitPatternTreeNode.h.
Constructor & Destructor Documentation
CBitPatternTreeNode::CBitPatternTreeNode (void) private
Definition at line 19 of file CBitPatternTreeNode.cpp.
Referenced by splitPatterns().
                                             :
     mIndex(0),
     mpZeroSet(NULL),
     mIgnoreCheck(false),
     mpUnsetChild(NULL),
     mpSetChild(NULL),
     mpStepMatrixColumn(NULL)
 {}
CBitPatternTreeNode::CBitPatternTreeNode (const CBitPatternTreeNode & src)
CBitPatternTreeNode::CBitPatternTreeNode (const size_t & index, const std::vector< CStepMatrixColumn * > & patterns)
Definition at line 28 of file CBitPatternTreeNode.cpp.
References CStepMatrixColumn::getZeroSet(), mpStepMatrixColumn, mpZeroSet, and splitPatterns().
                                                       :
     mIndex(index),
     mpZeroSet(NULL),
     mIgnoreCheck(false),
     mpUnsetChild(NULL),
     mpSetChild(NULL),
     mpStepMatrixColumn(NULL)
 {
   // Note: patterns may contain NULL pointers
   switch (patterns.size())
     {
       case 0:
         assert(false);
         break;
       case 1:
       {
         std::vector< CStepMatrixColumn * >::const_iterator it = patterns.begin();
         // This should never happen.
         assert(*it != NULL);
         mpZeroSet = new CZeroSet((*it)->getZeroSet());
         mpStepMatrixColumn = *it;
       }
       break;
       default:
       {
         std::vector< CStepMatrixColumn * >::const_iterator it = patterns.begin();
         std::vector< CStepMatrixColumn * >::const_iterator end = patterns.end();
         // This should never happen.
         for (; it != end; ++it)
           {
             if (*it != NULL)
               {
                 break;
               }
           }
         // This should never happen.
         assert(*it != NULL);
         CStepMatrixColumn * pFirstColumn = *it;
         mpZeroSet = new CZeroSet(pFirstColumn->getZeroSet());
         size_t Count = 1;
         for (++it; it != end; ++it)
           {
             if (*it != NULL)
               {
                 *mpZeroSet |= (*it)->getZeroSet();
                 Count++;
               }
           }
         if (Count != 1)
           {
             splitPatterns(patterns);
           }
         else
           {
             mpStepMatrixColumn = pFirstColumn;
           }
       }
       break;
     }
 }
CBitPatternTreeNode::~CBitPatternTreeNode (void) virtual
Definition at line 101 of file CBitPatternTreeNode.cpp.
References mpSetChild, mpUnsetChild, mpZeroSet, and pdelete.
 {
   pdelete(mpZeroSet);
   pdelete(mpUnsetChild);
   pdelete(mpSetChild);
 }
Member Function Documentation
size_t CBitPatternTreeNode::getChildrenCount () const
Definition at line 170 of file CBitPatternTreeNode.cpp.
References getChildrenCount(), mpSetChild, mpStepMatrixColumn, and mpUnsetChild.
Referenced by getChildrenCount(), and CBitPatternTree::size().
 {
   if (mpStepMatrixColumn != NULL)
     {
       return 1;
     }
   size_t Count = 0;
   if (mpUnsetChild != NULL)
     {
       Count = mpUnsetChild->getChildrenCount();
     }
   if (mpSetChild != NULL)
     {
       Count += mpSetChild->getChildrenCount();
     }
   return Count;
 }
const CBitPatternTreeNode* CBitPatternTreeNode::getSetChild () const inline
Definition at line 73 of file CBitPatternTreeNode.h.
References mpSetChild.
Referenced by CBitPatternTreeMethod::combine().
   {
     return mpSetChild;
   }
const CStepMatrixColumn * CBitPatternTreeNode::getStepMatrixColumn () const
Definition at line 108 of file CBitPatternTreeNode.cpp.
References mpStepMatrixColumn.
Referenced by CBitPatternTreeMethod::combine().
 {
   return mpStepMatrixColumn;
 }
const CBitPatternTreeNode* CBitPatternTreeNode::getUnsetChild () const inline
Definition at line 68 of file CBitPatternTreeNode.h.
References mpUnsetChild.
Referenced by CBitPatternTreeMethod::combine().
   {
     return mpUnsetChild;
   }
const CZeroSet& CBitPatternTreeNode::getZeroSet () const inline
Definition at line 63 of file CBitPatternTreeNode.h.
References mpZeroSet.
Referenced by CBitPatternTreeMethod::combine(), and splitPatterns().
   {
     return *mpZeroSet;
   }
bool CBitPatternTreeNode::hasSuperset (const CZeroSet & set) const inline
Definition at line 40 of file CBitPatternTreeNode.h.
References hasSuperset(), mIgnoreCheck, mpSetChild, mpStepMatrixColumn, mpUnsetChild, and mpZeroSet.
Referenced by hasSuperset(), and CBitPatternTree::isExtremeRay().
   {
     if (mIgnoreCheck || *mpZeroSet >= set)
       {
         if (mpStepMatrixColumn != NULL)
           {
             return true;
           }
         if (mpUnsetChild->hasSuperset(set))
           {
             return true;
           }
         if (mpSetChild->hasSuperset(set))
           {
             return true;
           }
       }
     return false;
   }
size_t CBitPatternTreeNode::nextAvailableIndex () const private
Definition at line 165 of file CBitPatternTreeNode.cpp.
References mIndex.
Referenced by splitPatterns().
 {
   return mIndex + 1;
 }
void CBitPatternTreeNode::splitPatterns (const std::vector< CStepMatrixColumn * > & patterns) private
Definition at line 113 of file CBitPatternTreeNode.cpp.
References CBitPatternTreeNode(), getZeroSet(), mIgnoreCheck, mIndex, mpSetChild, mpUnsetChild, mpZeroSet, and nextAvailableIndex().
Referenced by CBitPatternTreeNode().
 {
   size_t Index = mIndex;
   CZeroSet::CIndex Bit(mIndex);
   std::vector< CStepMatrixColumn * > SetPatterns;
   std::vector< CStepMatrixColumn * > UnsetPatterns;
   while (UnsetPatterns.empty() || SetPatterns.empty())
     {
       SetPatterns.clear();
       UnsetPatterns.clear();
       mIndex = Index;
       Bit = mIndex;
       std::vector< CStepMatrixColumn * >::const_iterator it = patterns.begin();
       std::vector< CStepMatrixColumn * >::const_iterator end = patterns.end();
       for (; it != end; ++it)
         {
           if (*it != NULL)
             {
               if ((*it)->getZeroSet().isSet(Bit))
                 {
                   SetPatterns.push_back((*it));
                 }
               else
                 {
                   UnsetPatterns.push_back((*it));
                 }
             }
         }
       Index = nextAvailableIndex();
     }
   mpUnsetChild = new CBitPatternTreeNode(Index, UnsetPatterns);
   if (mpUnsetChild->getZeroSet() == *mpZeroSet)
     {
       mpUnsetChild->mIgnoreCheck = true;
     }
   mpSetChild = new CBitPatternTreeNode(Index, SetPatterns);
   if (mpSetChild->getZeroSet() == *mpZeroSet)
     {
       mpSetChild->mIgnoreCheck = true;
     }
 }
Member Data Documentation
bool CBitPatternTreeNode::mIgnoreCheck private
Definition at line 91 of file CBitPatternTreeNode.h.
Referenced by hasSuperset(), and splitPatterns().
size_t CBitPatternTreeNode::mIndex private
Definition at line 87 of file CBitPatternTreeNode.h.
Referenced by nextAvailableIndex(), and splitPatterns().
CBitPatternTreeNode* CBitPatternTreeNode::mpSetChild private
Definition at line 95 of file CBitPatternTreeNode.h.
Referenced by getChildrenCount(), getSetChild(), hasSuperset(), splitPatterns(), and ~CBitPatternTreeNode().
CStepMatrixColumn* CBitPatternTreeNode::mpStepMatrixColumn private
Definition at line 97 of file CBitPatternTreeNode.h.
Referenced by CBitPatternTreeNode(), getChildrenCount(), getStepMatrixColumn(), and hasSuperset().
CBitPatternTreeNode* CBitPatternTreeNode::mpUnsetChild private
Definition at line 93 of file CBitPatternTreeNode.h.
Referenced by getChildrenCount(), getUnsetChild(), hasSuperset(), splitPatterns(), and ~CBitPatternTreeNode().
CZeroSet* CBitPatternTreeNode::mpZeroSet private
Definition at line 89 of file CBitPatternTreeNode.h.
Referenced by CBitPatternTreeNode(), getZeroSet(), hasSuperset(), splitPatterns(), and ~CBitPatternTreeNode().
The documentation for this class was generated from the following files:
CBitPatternTreeNode.h
CBitPatternTreeNode.cpp