COPASI API: ScrollZoomer Class Reference
ScrollZoomer Class Reference
#include <scrollzoomer.h>
Public Types
enum ScrollBarPosition { AttachedToScale, OppositeToScale }
Public Member Functions
QWidget * cornerWidget () const
virtual bool eventFilter (QObject *, QEvent *)
ScrollBar * horizontalScrollBar () const
Q3ScrollView::ScrollBarMode hScrollBarMode () const
ScrollBarPosition hScrollBarPosition () const
virtual void rescale ()
ScrollZoomer (QwtPlotCanvas *)
virtual void setCornerWidget (QWidget *)
void setHScrollBarMode (Q3ScrollView::ScrollBarMode)
void setHScrollBarPosition (ScrollBarPosition)
void setVScrollBarMode (Q3ScrollView::ScrollBarMode)
void setVScrollBarPosition (ScrollBarPosition)
ScrollBar * verticalScrollBar () const
Q3ScrollView::ScrollBarMode vScrollBarMode () const
ScrollBarPosition vScrollBarPosition () const
virtual ~ScrollZoomer ()
Public Member Functions inherited from LogPlotZoomer
LogPlotZoomer (QwtPlotCanvas *canvas)
Protected Member Functions
virtual void layoutScrollBars (const QRect &)
virtual ScrollBar * scrollBar (Qt::Orientation)
virtual void updateScrollBars ()
Protected Member Functions inherited from LogPlotZoomer
virtual QwtText trackerText (const QwtDoublePoint &pos) const
Private Slots
void scrollBarMoved (Qt::Orientation o, double min, double max)
Private Member Functions
bool needScrollBar (Qt::Orientation) const
int oppositeAxis (int) const
Private Attributes
QWidget * d_cornerWidget
ScrollData * d_hScrollData
ScrollData * d_vScrollData
Additional Inherited Members
Public Slots inherited from LogPlotZoomer
virtual void move (double x, double y)
Detailed Description
Definition at line 54 of file scrollzoomer.h.
Member Enumeration Documentation
enum ScrollZoomer::ScrollBarPosition
Enumerator
AttachedToScale
OppositeToScale
Definition at line 58 of file scrollzoomer.h.
   {
     AttachedToScale,
     OppositeToScale
   };
Constructor & Destructor Documentation
ScrollZoomer::ScrollZoomer (QwtPlotCanvas * canvas)
Definition at line 151 of file scrollzoomer.cpp.
References d_hScrollData, and d_vScrollData.
                                                :
   LogPlotZoomer(canvas),
   d_cornerWidget(NULL),
   d_hScrollData(NULL),
   d_vScrollData(NULL)
 {
   if (!canvas)
     return;
   d_hScrollData = new ScrollData;
   d_vScrollData = new ScrollData;
 }
ScrollZoomer::~ScrollZoomer () virtual
Definition at line 164 of file scrollzoomer.cpp.
References d_cornerWidget, d_hScrollData, and d_vScrollData.
 {
   delete d_cornerWidget;
   delete d_vScrollData;
   delete d_hScrollData;
 }
Member Function Documentation
QWidget * ScrollZoomer::cornerWidget () const
Definition at line 301 of file scrollzoomer.cpp.
References d_cornerWidget.
 {
   return d_cornerWidget;
 }
bool ScrollZoomer::eventFilter (QObject * o, QEvent * e) virtual
Definition at line 306 of file scrollzoomer.cpp.
References d_cornerWidget, d_hScrollData, d_vScrollData, layoutScrollBars(), and ScrollData::scrollBar.
 {
   if (o == canvas())
     {
       switch (e->type())
         {
           case QEvent::Resize:
           {
             const int fw = ((QwtPlotCanvas *)canvas())->frameWidth();
             QRect rect;
             rect.setSize(((QResizeEvent *)e)->size());
             rect.setRect(rect.x() + fw, rect.y() + fw,
                          rect.width() - 2 * fw, rect.height() - 2 * fw);
             layoutScrollBars(rect);
             break;
           }
           case QEvent::ChildRemoved:
           {
             const QObject *child = ((QChildEvent *)e)->child();
             if (child == d_cornerWidget)
               d_cornerWidget = NULL;
             else if (child == d_hScrollData->scrollBar)
               d_hScrollData->scrollBar = NULL;
             else if (child == d_vScrollData->scrollBar)
               d_vScrollData->scrollBar = NULL;
             break;
           }
           default:
             break;
         }
     }
   return QwtPlotZoomer::eventFilter(o, e);
 }
ScrollBar * ScrollZoomer::horizontalScrollBar () const
Definition at line 194 of file scrollzoomer.cpp.
References d_hScrollData, and ScrollData::scrollBar.
Referenced by layoutScrollBars(), and updateScrollBars().
 {
   return d_hScrollData->scrollBar;
 }
Q3ScrollView::ScrollBarMode ScrollZoomer::hScrollBarMode () const
Definition at line 231 of file scrollzoomer.cpp.
 {
   return d_hScrollData->mode;
 }
ScrollZoomer::ScrollBarPosition ScrollZoomer::hScrollBarPosition () const
Definition at line 268 of file scrollzoomer.cpp.
References d_hScrollData, and ScrollData::position.
Referenced by layoutScrollBars(), and updateScrollBars().
 {
   return d_hScrollData->position;
 }
void ScrollZoomer::layoutScrollBars (const QRect & rect) protected virtual
Definition at line 504 of file scrollzoomer.cpp.
References d_cornerWidget, ScrollBar::extent(), horizontalScrollBar(), hScrollBarPosition(), oppositeAxis(), OppositeToScale, verticalScrollBar(), and vScrollBarPosition().
Referenced by eventFilter(), and updateScrollBars().
 {
   int hPos = xAxis();
   if (hScrollBarPosition() == OppositeToScale)
     hPos = oppositeAxis(hPos);
   int vPos = yAxis();
   if (vScrollBarPosition() == OppositeToScale)
     vPos = oppositeAxis(vPos);
   ScrollBar *hScrollBar = horizontalScrollBar();
   ScrollBar *vScrollBar = verticalScrollBar();
   const int hdim = hScrollBar ? hScrollBar->extent() : 0;
   const int vdim = vScrollBar ? vScrollBar->extent() : 0;
   if (hScrollBar && hScrollBar->isVisible())
     {
       int x = rect.x();
       int y = (hPos == QwtPlot::xTop)
               ? rect.top() : rect.bottom() - hdim + 1;
       int w = rect.width();
       if (vScrollBar && vScrollBar->isVisible())
         {
           if (vPos == QwtPlot::yLeft)
             x += vdim;
           w -= vdim;
         }
       hScrollBar->setGeometry(x, y, w, hdim);
     }
   if (vScrollBar && vScrollBar->isVisible())
     {
       int pos = yAxis();
       if (vScrollBarPosition() == OppositeToScale)
         pos = oppositeAxis(pos);
       int x = (vPos == QwtPlot::yLeft)
               ? rect.left() : rect.right() - vdim + 1;
       int y = rect.y();
       int h = rect.height();
       if (hScrollBar && hScrollBar->isVisible())
         {
           if (hPos == QwtPlot::xTop)
             y += hdim;
           h -= hdim;
         }
       vScrollBar->setGeometry(x, y, vdim, h);
     }
   if (hScrollBar && hScrollBar->isVisible() &&
       vScrollBar && vScrollBar->isVisible())
     {
       if (d_cornerWidget)
         {
           QRect cornerRect(
             vScrollBar->pos().x(), hScrollBar->pos().y(),
             vdim, hdim);
           d_cornerWidget->setGeometry(cornerRect);
         }
     }
 }
bool ScrollZoomer::needScrollBar (Qt::Orientation o) const private
Definition at line 345 of file scrollzoomer.cpp.
References d_hScrollData, d_vScrollData, and ScrollData::mode.
Referenced by updateScrollBars().
 {
 #if QT_VERSION < 0x040000
   Q3ScrollView::ScrollBarMode mode;
 #else
   Qt::ScrollBarPolicy mode;
 #endif
   double zoomMin, zoomMax, baseMin, baseMax;
   if (o == Qt::Horizontal)
     {
       mode = d_hScrollData->mode;
       baseMin = zoomBase().left();
       baseMax = zoomBase().right();
       zoomMin = zoomRect().left();
       zoomMax = zoomRect().right();
     }
   else
     {
       mode = d_vScrollData->mode;
       baseMin = zoomBase().top();
       baseMax = zoomBase().bottom();
       zoomMin = zoomRect().top();
       zoomMax = zoomRect().bottom();
     }
   bool needed = false;
   switch (mode)
     {
 #if QT_VERSION < 0x040000
       case Q3ScrollView::AlwaysOn:
 #else
       case Qt::ScrollBarAlwaysOn:
 #endif
         needed = true;
         break;
 #if QT_VERSION < 0x040000
       case Q3ScrollView::AlwaysOff:
 #else
       case Qt::ScrollBarAlwaysOff:
 #endif
         needed = false;
         break;
       default:
       {
         if (baseMin < zoomMin || baseMax > zoomMax)
           needed = true;
         break;
       }
     }
   return needed;
 }
int ScrollZoomer::oppositeAxis (int axis) const private
Definition at line 587 of file scrollzoomer.cpp.
Referenced by layoutScrollBars(), and updateScrollBars().
 {
   switch (axis)
     {
       case QwtPlot::xBottom:
         return QwtPlot::xTop;
       case QwtPlot::xTop:
         return QwtPlot::xBottom;
       case QwtPlot::yLeft:
         return QwtPlot::yRight;
       case QwtPlot::yRight:
         return QwtPlot::yLeft;
       default:
         break;
     }
   return axis;
 }
void ScrollZoomer::rescale () virtual
Definition at line 171 of file scrollzoomer.cpp.
References updateScrollBars().
 {
   QwtPlotZoomer::rescale();
   updateScrollBars();
 }
ScrollBar * ScrollZoomer::scrollBar (Qt::Orientation o) protected virtual
Definition at line 177 of file scrollzoomer.cpp.
References d_hScrollData, d_vScrollData, if(), ScrollData::scrollBar, and scrollBarMoved().
Referenced by updateScrollBars().
 {
   ScrollBar *&sb = (o == Qt::Vertical)
                    ? d_vScrollData->scrollBar : d_hScrollData->scrollBar;
   if (sb == NULL)
     {
       sb = new ScrollBar(o, canvas());
       sb->hide();
       connect(sb,
               SIGNAL(valueChanged(Qt::Orientation, double, double)),
               SLOT(scrollBarMoved(Qt::Orientation, double, double)));
     }
   return sb;
 }
void ScrollZoomer::scrollBarMoved (Qt::Orientation o, double min, double max) private slot
Definition at line 577 of file scrollzoomer.cpp.
References LogPlotZoomer::move().
Referenced by scrollBar().
 {
   if (o == Qt::Horizontal)
     move(min, zoomRect().top());
   else
     move(zoomRect().left(), min);
   emit zoomed(zoomRect());
 }
void ScrollZoomer::setCornerWidget (QWidget * w) virtual
Definition at line 278 of file scrollzoomer.cpp.
References d_cornerWidget, and updateScrollBars().
 {
   if (w != d_cornerWidget)
     {
       if (canvas())
         {
           delete d_cornerWidget;
           d_cornerWidget = w;
           if (d_cornerWidget->parent() != canvas())
             {
 #if QT_VERSION < 0x040000
               d_cornerWidget->reparent(canvas(), QPoint(0, 0));
 #else
               d_cornerWidget->setParent(canvas());
 #endif
             }
           updateScrollBars();
         }
     }
 }
void ScrollZoomer::setHScrollBarMode (Q3ScrollView::ScrollBarMode mode)
Definition at line 205 of file scrollzoomer.cpp.
 {
   if (hScrollBarMode() != mode)
     {
       d_hScrollData->mode = mode;
       updateScrollBars();
     }
 }
void ScrollZoomer::setHScrollBarPosition (ScrollBarPosition pos)
Definition at line 250 of file scrollzoomer.cpp.
References d_hScrollData, ScrollData::position, and updateScrollBars().
 {
   if (d_hScrollData->position != pos)
     {
       d_hScrollData->position = pos;
       updateScrollBars();
     }
 }
void ScrollZoomer::setVScrollBarMode (Q3ScrollView::ScrollBarMode mode)
Definition at line 218 of file scrollzoomer.cpp.
 {
   if (vScrollBarMode() != mode)
     {
       d_vScrollData->mode = mode;
       updateScrollBars();
     }
 }
void ScrollZoomer::setVScrollBarPosition (ScrollBarPosition pos)
Definition at line 259 of file scrollzoomer.cpp.
References d_vScrollData, ScrollData::position, and updateScrollBars().
 {
   if (d_vScrollData->position != pos)
     {
       d_vScrollData->position = pos;
       updateScrollBars();
     }
 }
void ScrollZoomer::updateScrollBars () protected virtual
Definition at line 401 of file scrollzoomer.cpp.
References d_cornerWidget, ScrollBar::extent(), horizontalScrollBar(), hScrollBarPosition(), layoutScrollBars(), ScrollBar::moveSlider(), needScrollBar(), oppositeAxis(), OppositeToScale, scrollBar(), ScrollBar::setBase(), ScrollBar::setInverted(), ScrollBar::setLogScale(), verticalScrollBar(), and vScrollBarPosition().
Referenced by rescale(), setCornerWidget(), setHScrollBarPosition(), and setVScrollBarPosition().
 {
   if (!canvas())
     return;
   const int xAxis = QwtPlotZoomer::xAxis();
   const int yAxis = QwtPlotZoomer::yAxis();
   int xScrollBarAxis = xAxis;
   if (hScrollBarPosition() == OppositeToScale)
     xScrollBarAxis = oppositeAxis(xScrollBarAxis);
   int yScrollBarAxis = yAxis;
   if (vScrollBarPosition() == OppositeToScale)
     yScrollBarAxis = oppositeAxis(yScrollBarAxis);
   QwtPlotLayout *layout = plot()->plotLayout();
   bool showHScrollBar = needScrollBar(Qt::Horizontal);
   if (showHScrollBar)
     {
       ScrollBar *sb = scrollBar(Qt::Horizontal);
       sb->setPalette(plot()->palette());
       const QwtScaleEngine *se = plot()->axisScaleEngine(xAxis);
       sb->setInverted(se->testAttribute(QwtScaleEngine::Inverted));
       sb->setLogScale(dynamic_cast<const QwtLog10ScaleEngine*>(se));
       sb->setBase(zoomBase().left(), zoomBase().right());
       sb->moveSlider(zoomRect().left(), zoomRect().right());
       if (!sb->isVisibleTo(canvas()))
         {
           sb->show();
           layout->setCanvasMargin(layout->canvasMargin(xScrollBarAxis)
                                   + sb->extent(), xScrollBarAxis);
         }
     }
   else
     {
       if (horizontalScrollBar())
         {
           horizontalScrollBar()->hide();
           layout->setCanvasMargin(layout->canvasMargin(xScrollBarAxis)
                                   - horizontalScrollBar()->extent(), xScrollBarAxis);
         }
     }
   bool showVScrollBar = needScrollBar(Qt::Vertical);
   if (showVScrollBar)
     {
       ScrollBar *sb = scrollBar(Qt::Vertical);
       sb->setPalette(plot()->palette());
       const QwtScaleEngine *se = plot()->axisScaleEngine(yAxis);
       sb->setInverted(!(se->testAttribute(QwtScaleEngine::Inverted)));
       sb->setLogScale(dynamic_cast<const QwtLog10ScaleEngine*>(se));
       sb->setBase(zoomBase().top(), zoomBase().bottom());
       sb->moveSlider(zoomRect().top(), zoomRect().bottom());
       if (!sb->isVisibleTo(canvas()))
         {
           sb->show();
           layout->setCanvasMargin(layout->canvasMargin(yScrollBarAxis)
                                   + sb->extent(), yScrollBarAxis);
         }
     }
   else
     {
       if (verticalScrollBar())
         {
           verticalScrollBar()->hide();
           layout->setCanvasMargin(layout->canvasMargin(yScrollBarAxis)
                                   - verticalScrollBar()->extent(), yScrollBarAxis);
         }
     }
   if (showHScrollBar && showVScrollBar)
     {
       if (d_cornerWidget == NULL)
         {
           d_cornerWidget = new QWidget(canvas());
           d_cornerWidget->setPalette(plot()->palette());
         }
       d_cornerWidget->show();
     }
   else
     {
       if (d_cornerWidget)
         d_cornerWidget->hide();
     }
   layoutScrollBars(((QwtPlotCanvas *)canvas())->contentsRect());
 }
ScrollBar * ScrollZoomer::verticalScrollBar () const
Definition at line 199 of file scrollzoomer.cpp.
References d_vScrollData, and ScrollData::scrollBar.
Referenced by layoutScrollBars(), and updateScrollBars().
 {
   return d_vScrollData->scrollBar;
 }
Q3ScrollView::ScrollBarMode ScrollZoomer::vScrollBarMode () const
Definition at line 241 of file scrollzoomer.cpp.
 {
   return d_vScrollData->mode;
 }
ScrollZoomer::ScrollBarPosition ScrollZoomer::vScrollBarPosition () const
Definition at line 273 of file scrollzoomer.cpp.
References d_vScrollData, and ScrollData::position.
Referenced by layoutScrollBars(), and updateScrollBars().
 {
   return d_vScrollData->position;
 }
Member Data Documentation
QWidget* ScrollZoomer::d_cornerWidget private
Definition at line 109 of file scrollzoomer.h.
Referenced by cornerWidget(), eventFilter(), layoutScrollBars(), setCornerWidget(), updateScrollBars(), and ~ScrollZoomer().
ScrollData* ScrollZoomer::d_hScrollData private
Definition at line 111 of file scrollzoomer.h.
Referenced by eventFilter(), horizontalScrollBar(), hScrollBarPosition(), needScrollBar(), scrollBar(), ScrollZoomer(), setHScrollBarPosition(), and ~ScrollZoomer().
ScrollData* ScrollZoomer::d_vScrollData private
Definition at line 112 of file scrollzoomer.h.
Referenced by eventFilter(), needScrollBar(), scrollBar(), ScrollZoomer(), setVScrollBarPosition(), verticalScrollBar(), vScrollBarPosition(), and ~ScrollZoomer().
The documentation for this class was generated from the following files:
scrollzoomer.h
scrollzoomer.cpp