COPASI API: Bar Class Reference
Bar Class Reference
#include <qwt3dBars.h>
Public Member Functions
Bar ()
Bar (double rad, double showColumn=-1, double showRow=-1)
Qwt3D::Enrichment * clone () const
void configure (double rad, double showColumn, double showRow)
void draw (Qwt3D::Triple const &)
void drawBegin ()
void drawEnd ()
void drawZero ()
virtual ~Bar ()
Public Attributes
double mShowColumn
double mShowRow
Private Attributes
double diag_
double level_
double radius_
Detailed Description
Definition at line 23 of file qwt3dBars.h.
Constructor & Destructor Documentation
Bar::Bar ()
Definition at line 22 of file qwt3dBars.cpp.
References configure().
Referenced by clone().
 {
   configure(0, -1, -1);
 }
Bar::Bar (double rad, double showColumn = -1, double showRow = -1)
Definition at line 27 of file qwt3dBars.cpp.
References configure().
 {
   configure(rad, showColumn, showRow);
 }
Bar::~Bar () virtual
Definition at line 33 of file qwt3dBars.cpp.
 {}
Member Function Documentation
Qwt3D::Enrichment* Bar::clone () const inline
Definition at line 30 of file qwt3dBars.h.
References Bar().
 {return new Bar(*this);}
void Bar::configure (double rad, double showColumn, double showRow)
Definition at line 36 of file qwt3dBars.cpp.
References mShowColumn, mShowRow, and radius_.
Referenced by Bar().
 {
   plot = 0;
   radius_ = rad;
   mShowColumn = showColumn;
   mShowRow = showRow;
 }
void Bar::draw (Qwt3D::Triple const & pos)
Definition at line 56 of file qwt3dBars.cpp.
References diag_, mShowColumn, and mShowRow.
 {
   Qwt3D::GLStateBewarer sb(GL_LINE_SMOOTH, true);
   sb.turnOn();
   //an option to add further labels
   //  if ((pos.x == mShowColumn) || (pos.y == mShowRow))
   //  {
   //    Label3D lb;
   //    lb.draw(pos, diag_, diag_ * 2);
   //}
   // set the zero level
   GLdouble minz = 0; //plot->hull().minVertex.z;
   Qwt3D::RGBA mTo = (*plot->dataColor())(pos);
   Qwt3D::RGBA mFrom = (*plot->dataColor())(pos.x, pos.y, minz);
   glBegin(GL_QUADS);
   if (((int)(100 * pos.x) == (int)(100 * mShowColumn)) || ((int)(100 * pos.y) == (int)(100 * mShowRow)))
     glColor3d(0.71, 0.835, 1); //(1, 0, 0);
   else
     glColor4d(mTo.r, mTo.g, mTo.b, mTo.a);
   //glColor4d(mFrom.r, mFrom.g, mFrom.b, mFrom.a);
   glVertex3d(pos.x - diag_, pos.y - diag_, minz);
   glVertex3d(pos.x + diag_, pos.y - diag_, minz);
   glVertex3d(pos.x + diag_, pos.y + diag_, minz);
   glVertex3d(pos.x - diag_, pos.y + diag_, minz);
   if (((int)(100 * pos.x) == (int)(100 * mShowColumn)) || ((int)(100 * pos.y) == (int)(100 * mShowRow)))
     glColor3d(0.71, 0.835, 1); //(1, 0, 0);
   else
     glColor4d(mTo.r, mTo.g, mTo.b, mTo.a);
   glVertex3d(pos.x - diag_, pos.y - diag_, pos.z);
   glVertex3d(pos.x + diag_, pos.y - diag_, pos.z);
   glVertex3d(pos.x + diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y + diag_, pos.z);
   glColor4d(mFrom.r, mFrom.g, mFrom.b, mFrom.a);
   glVertex3d(pos.x - diag_, pos.y - diag_, minz);
   glVertex3d(pos.x + diag_, pos.y - diag_, minz);
   glColor4d(mTo.r, mTo.g, mTo.b, mTo.a);
   glVertex3d(pos.x + diag_, pos.y - diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y - diag_, pos.z);
   glColor4d(mFrom.r, mFrom.g, mFrom.b, mFrom.a);
   glVertex3d(pos.x - diag_, pos.y + diag_, minz);
   glVertex3d(pos.x + diag_, pos.y + diag_, minz);
   glColor4d(mTo.r, mTo.g, mTo.b, mTo.a);
   glVertex3d(pos.x + diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y + diag_, pos.z);
   glColor4d(mFrom.r, mFrom.g, mFrom.b, mFrom.a);
   glVertex3d(pos.x - diag_, pos.y - diag_, minz);
   glVertex3d(pos.x - diag_, pos.y + diag_, minz);
   glColor4d(mTo.r, mTo.g, mTo.b, mTo.a);
   glVertex3d(pos.x - diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y - diag_, pos.z);
   glColor4d(mFrom.r, mFrom.g, mFrom.b, mFrom.a);
   glVertex3d(pos.x + diag_, pos.y - diag_, minz);
   glVertex3d(pos.x + diag_, pos.y + diag_, minz);
   glColor4d(mTo.r, mTo.g, mTo.b, mTo.a);
   glVertex3d(pos.x + diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x + diag_, pos.y - diag_, pos.z);
   glEnd();
   glColor3d(0, 0, 0);
   glBegin(GL_LINES);
   glVertex3d(pos.x - diag_, pos.y - diag_, minz); glVertex3d(pos.x + diag_, pos.y - diag_, minz);
   glVertex3d(pos.x - diag_, pos.y - diag_, pos.z); glVertex3d(pos.x + diag_, pos.y - diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y + diag_, pos.z); glVertex3d(pos.x + diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y + diag_, minz); glVertex3d(pos.x + diag_, pos.y + diag_, minz);
   glVertex3d(pos.x - diag_, pos.y - diag_, minz); glVertex3d(pos.x - diag_, pos.y + diag_, minz);
   glVertex3d(pos.x + diag_, pos.y - diag_, minz); glVertex3d(pos.x + diag_, pos.y + diag_, minz);
   glVertex3d(pos.x + diag_, pos.y - diag_, pos.z); glVertex3d(pos.x + diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y - diag_, pos.z); glVertex3d(pos.x - diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y - diag_, minz); glVertex3d(pos.x - diag_, pos.y - diag_, pos.z);
   glVertex3d(pos.x + diag_, pos.y - diag_, minz); glVertex3d(pos.x + diag_, pos.y - diag_, pos.z);
   glVertex3d(pos.x + diag_, pos.y + diag_, minz); glVertex3d(pos.x + diag_, pos.y + diag_, pos.z);
   glVertex3d(pos.x - diag_, pos.y + diag_, minz); glVertex3d(pos.x - diag_, pos.y + diag_, pos.z);
   glEnd();
 }
void Bar::drawBegin ()
Definition at line 44 of file qwt3dBars.cpp.
References diag_, drawZero(), and radius_.
 {
   drawZero();
   diag_ = radius_;
   glLineWidth(0);
   glEnable(GL_POLYGON_OFFSET_FILL);
   glPolygonOffset(1, 1);
 }
void Bar::drawEnd ()
Definition at line 53 of file qwt3dBars.cpp.
 {}
void Bar::drawZero ()
Definition at line 145 of file qwt3dBars.cpp.
Referenced by drawBegin().
 {
   glColor3d(0, 0, 0);
   glBegin(GL_LINE_LOOP);
   glVertex3d(plot->hull().minVertex.x, plot->hull().minVertex.y, 0);
   glVertex3d(plot->hull().maxVertex.x, plot->hull().minVertex.y, 0);
   glVertex3d(plot->hull().maxVertex.x, plot->hull().maxVertex.y, 0);
   glVertex3d(plot->hull().minVertex.x, plot->hull().maxVertex.y, 0);
   glEnd();
 }
Member Data Documentation
double Bar::diag_ private
Definition at line 41 of file qwt3dBars.h.
Referenced by draw(), and drawBegin().
double Bar::level_ private
Definition at line 40 of file qwt3dBars.h.
double Bar::mShowColumn
Definition at line 37 of file qwt3dBars.h.
Referenced by configure(), and draw().
double Bar::mShowRow
Definition at line 38 of file qwt3dBars.h.
Referenced by configure(), and draw().
double Bar::radius_ private
Definition at line 40 of file qwt3dBars.h.
Referenced by configure(), and drawBegin().
The documentation for this class was generated from the following files:
qwt3dBars.h
qwt3dBars.cpp