COPASI API: CArrow Class Reference
CArrow Class Reference
#include <CArrow.h>
Public Member Functions
CArrow ()
CArrow (CLLineSegment l, C_FLOAT64 x, C_FLOAT64 y, C_FLOAT64 currentZoomFactor)
C_FLOAT64 getArrowLength ()
C_FLOAT64 getArrowWidth ()
CLPoint getEndOfLine ()
CLLineSegment getLine ()
CLPoint getPoint ()
CLPoint getStartOfLine ()
void scale (C_FLOAT64 zoomFactor)
void setLine (CLLineSegment l)
void setPoint (CLPoint p)
Private Member Functions
void scaleHeadSize (C_FLOAT64 zoomFactor)
void scalePosition (C_FLOAT64 zoomFactor)
Private Attributes
C_FLOAT64 arrowLength
C_FLOAT64 arrowWidth
CLPoint endPoint
CLLineSegment line
Detailed Description
Definition at line 29 of file CArrow.h.
Constructor & Destructor Documentation
CArrow::CArrow () inline
Definition at line 37 of file CArrow.h.
References arrowLength, arrowWidth, and endPoint.
 {endPoint = CLPoint(0.0, 0.0);arrowLength = 12.0; arrowWidth = 5.0;}
CArrow::CArrow (CLLineSegment l, C_FLOAT64 x, C_FLOAT64 y, C_FLOAT64 currentZoomFactor)
Definition at line 26 of file CArrow.cpp.
References arrowLength, arrowWidth, endPoint, line, and scaleHeadSize().
 {
   line = l;
   endPoint = CLPoint(x, y);
   arrowLength = 12.0;
   arrowWidth = 5.0;
   scaleHeadSize(currentZoomFactor);
 }
Member Function Documentation
C_FLOAT64 CArrow::getArrowLength () inline
Definition at line 47 of file CArrow.h.
References arrowLength.
 {return arrowLength;}
C_FLOAT64 CArrow::getArrowWidth () inline
Definition at line 46 of file CArrow.h.
References arrowWidth.
 {return arrowWidth;}
CLPoint CArrow::getEndOfLine () inline
Definition at line 41 of file CArrow.h.
References CLLineSegment::getEnd(), and line.
Referenced by CQGLNetworkPainter::drawArrow().
 {return line.getEnd();}
CLLineSegment CArrow::getLine () inline
Definition at line 42 of file CArrow.h.
References line.
 {return line;}
CLPoint CArrow::getPoint () inline
Definition at line 44 of file CArrow.h.
References endPoint.
 {return endPoint;}
CLPoint CArrow::getStartOfLine () inline
Definition at line 40 of file CArrow.h.
References CLLineSegment::getStart(), and line.
Referenced by CQGLNetworkPainter::drawArrow().
 {return line.getStart();}
void CArrow::scale (C_FLOAT64 zoomFactor)
Definition at line 36 of file CArrow.cpp.
References scaleHeadSize(), and scalePosition().
Referenced by CGraphCurve::scale().
 {
   this->scaleHeadSize(zoomFactor);
   this->scalePosition(zoomFactor);
 }
void CArrow::scaleHeadSize (C_FLOAT64 zoomFactor) private
Definition at line 49 of file CArrow.cpp.
References arrowLength, and arrowWidth.
Referenced by CArrow(), and scale().
 {
   this->arrowWidth *= zoomFactor;
   this->arrowLength *= zoomFactor;
 }
void CArrow::scalePosition (C_FLOAT64 zoomFactor) private
Definition at line 42 of file CArrow.cpp.
References endPoint, CLPoint::getX(), CLPoint::getY(), line, CLLineSegment::scale(), CLPoint::setX(), and CLPoint::setY().
Referenced by scale().
 {
   this->line.scale(zoomFactor);
   this->endPoint.setX(this->endPoint.getX() * zoomFactor);
   this->endPoint.setY(this->endPoint.getY() * zoomFactor);
 }
void CArrow::setLine (CLLineSegment l) inline
Definition at line 43 of file CArrow.h.
References line.
Referenced by CGraphCurve::invertOrderOfPoints().
 {line = l;}
void CArrow::setPoint (CLPoint p) inline
Definition at line 45 of file CArrow.h.
References endPoint.
Referenced by CGraphCurve::invertOrderOfPoints().
 {endPoint = p;}
Member Data Documentation
C_FLOAT64 CArrow::arrowLength private
Definition at line 34 of file CArrow.h.
Referenced by CArrow(), getArrowLength(), and scaleHeadSize().
C_FLOAT64 CArrow::arrowWidth private
Definition at line 35 of file CArrow.h.
Referenced by CArrow(), getArrowWidth(), and scaleHeadSize().
CLPoint CArrow::endPoint private
Definition at line 33 of file CArrow.h.
Referenced by CArrow(), getPoint(), scalePosition(), and setPoint().
CLLineSegment CArrow::line private
Definition at line 32 of file CArrow.h.
Referenced by CArrow(), getEndOfLine(), getLine(), getStartOfLine(), scalePosition(), and setLine().
The documentation for this class was generated from the following files:
CArrow.h
CArrow.cpp