COPASI API: test000101 Class Reference
test000101 Class Reference
#include <test000101.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1740 ()
Static Protected Member Functions
static void abort_handler (int)
Protected Attributes
CCopasiDataModel * pDataModel
Static Protected Attributes
static struct sigaction * pNewAct = new struct sigaction()
static struct sigaction * pOldAct = new struct sigaction()
static const char * SBML_STRING
Private Member Functions
CPPUNIT_TEST (test_bug1740)
CPPUNIT_TEST_SUITE (test000101)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 31 of file test000101.h.
Member Function Documentation
void test000101::abort_handler (int) static protected
Definition at line 30 of file test000101.cpp.
Referenced by setUp().
 {
   throw std::runtime_error("Received SIGSEGV signal.");
 }
test000101::CPPUNIT_TEST (test_bug1740) private
test000101::CPPUNIT_TEST_SUITE (test000101) private
test000101::CPPUNIT_TEST_SUITE_END () private
void test000101::setUp ()
Definition at line 39 of file test000101.cpp.
References abort_handler(), CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), pDataModel, pNewAct, and pOldAct.
 {
 #ifndef WIN32
   // set a new action handler for SIGABRT that throws an exception
   // instead of terminating the program. This is needed to handle failed assertions
   // in debug versions.
   pNewAct->sa_handler = &test000101::abort_handler;
   int x = sigaction(SIGSEGV, test000101::pNewAct, test000101::pOldAct);
   if (x != 0)
     {
       std::cerr << "Setting the signal handler failed." << std::endl;
     }
 #endif
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   pDataModel = CCopasiRootContainer::addDatamodel();
 }
void test000101::tearDown ()
Definition at line 59 of file test000101.cpp.
References CCopasiRootContainer::destroy(), and pOldAct.
 {
 #ifndef WIN32
   CCopasiRootContainer::destroy();
   // restore the old action handler
   int x = sigaction(SIGSEGV, test000101::pOldAct, NULL);
   if (x != 0)
     {
       std::cerr << "Resetting the signal handler failed." << std::endl;
     }
 #endif
 }
void test000101::test_bug1740 ()
Definition at line 76 of file test000101.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::importSBMLFromString(), pDataModel, and SBML_STRING.
 {
   pDataModel->importSBMLFromString(SBML_STRING);
   pDataModel->exportSBMLToString(NULL, 3, 1);
   try
     {
       // the second export crashes without a bug fix
       pDataModel->exportSBMLToString(NULL, 3, 1);
     }
   catch (const std::runtime_error& e)
     {
       CPPUNIT_ASSERT_MESSAGE("The second export to Level 3 Version 1 failed.", false);
     }
 }
Member Data Documentation
CCopasiDataModel* test000101::pDataModel protected
Definition at line 41 of file test000101.h.
Referenced by setUp(), and test_bug1740().
struct sigaction * test000101::pNewAct = new struct sigaction() static protected
Definition at line 43 of file test000101.h.
Referenced by setUp().
struct sigaction * test000101::pOldAct = new struct sigaction() static protected
Definition at line 44 of file test000101.h.
Referenced by setUp(), and tearDown().
const char * test000101::SBML_STRING static protected
Initial value:
= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                      "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version1/core\" level=\"3\" version=\"1\">\n"
                                      "  <model id=\"Module_1_RL2_1\" name=\"Module_1_RL2\">\n"
                                      "    <listOfReactions>\n"
                                      "      <reaction fast=\"false\" id=\"reaction_0\" name=\"reaction_0\" reversible=\"false\">\n"
                                      "      </reaction>\n"
                                      "    </listOfReactions>\n"
                                      "  </model>\n"
                                      "</sbml>\n"
Definition at line 39 of file test000101.h.
Referenced by test_bug1740().
The documentation for this class was generated from the following files:
test000101.h
test000101.cpp