COPASI API: CReportTable Class Reference
CReportTable Class Reference
#include <CReportBody.h>
Public Member Functions
void cleanup ()
CReportTable ()
std::vector< CCopasiObjectName > * getObjectNameVector ()
const std::string & getSeparator ()
bool printTitle ()
void setObjectNameVector (std::vector< CCopasiObjectName > *objectVector)
void setPrintTitle (bool printTitle)
void setSeparator (const std::string separator)
~CReportTable ()
Private Attributes
std::vector< CCopasiObjectName > * mpObjectNameVector
bool mPrintTitle
std::string mSeparator
Detailed Description
Definition at line 64 of file CReportBody.h.
Constructor & Destructor Documentation
CReportTable::CReportTable ()
Default constructor.
Definition at line 45 of file CReportBody.cpp.
                           :
     mpObjectNameVector(NULL),
     mSeparator(" "),
     mPrintTitle(true)
 {}
CReportTable::~CReportTable ()
Destructor.
Definition at line 51 of file CReportBody.cpp.
References cleanup().
 {cleanup();}
Member Function Documentation
void CReportTable::cleanup ()
cleanup
Definition at line 54 of file CReportBody.cpp.
References mpObjectNameVector, and pdelete.
Referenced by ~CReportTable().
 {
   // this pointer is created outsid
   pdelete(mpObjectNameVector);
 }
std::vector<CCopasiObjectName>* CReportTable::getObjectNameVector () inline
gets the Object tag of the Table tag
Definition at line 90 of file CReportBody.h.
References mpObjectNameVector.
     {
       return mpObjectNameVector;
     }
const std::string& CReportTable::getSeparator () inline
gets the Separator attribute of the Table tag
Definition at line 106 of file CReportBody.h.
References mSeparator.
     {
       return mSeparator;
     }
bool CReportTable::printTitle () inline
gets the printTitle of the Table tag
Definition at line 122 of file CReportBody.h.
References mPrintTitle.
Referenced by setPrintTitle().
     {
       return mPrintTitle;
     }
void CReportTable::setObjectNameVector (std::vector< CCopasiObjectName > * objectVector) inline
sets the Object tag of the Table tag
Definition at line 98 of file CReportBody.h.
References mpObjectNameVector.
     {
       mpObjectNameVector = objectVector;
     }
void CReportTable::setPrintTitle (bool printTitle) inline
sets the print Title of the Table tag
Definition at line 130 of file CReportBody.h.
References mPrintTitle, and printTitle().
     {
       mPrintTitle = printTitle;
     }
void CReportTable::setSeparator (const std::string separator) inline
sets the separator attribute of the Table tag
Definition at line 114 of file CReportBody.h.
References mSeparator.
     {
       mSeparator = separator;
     }
Member Data Documentation
std::vector<CCopasiObjectName>* CReportTable::mpObjectNameVector private
Definition at line 67 of file CReportBody.h.
Referenced by cleanup(), getObjectNameVector(), and setObjectNameVector().
bool CReportTable::mPrintTitle private
Definition at line 69 of file CReportBody.h.
Referenced by printTitle(), and setPrintTitle().
std::string CReportTable::mSeparator private
Definition at line 68 of file CReportBody.h.
Referenced by getSeparator(), and setSeparator().
The documentation for this class was generated from the following files:
CReportBody.h
CReportBody.cpp