COPASI API: CFitProblem.cpp File Reference
CFitProblem.cpp File Reference
#include <cmath>
#include "copasi.h"
#include "CFitProblem.h"
#include "CFitItem.h"
#include "CFitTask.h"
#include "CExperimentSet.h"
#include "CExperiment.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "model/CModel.h"
#include "model/CState.h"
#include "report/CCopasiObjectReference.h"
#include "report/CKeyFactory.h"
#include "steadystate/CSteadyStateTask.h"
#include "trajectory/CTrajectoryTask.h"
#include "trajectory/CTrajectoryProblem.h"
#include "utilities/CProcessReport.h"
#include "utilities/CCopasiException.h"
#include "utilities/CAnnotatedMatrix.h"
#include "lapack/blaswrap.h"
#include "lapack/lapackwrap.h"
Functions
void createParameterSetsForExperiment (CExperiment *pExp)
std::ostream & operator<< (std::ostream &os, const CFitProblem &o)
Function Documentation
void createParameterSetsForExperiment (CExperiment * pExp)
Utility function creating a parameter set for each experiment
Definition at line 807 of file CFitProblem.cpp.
References CCopasiVectorN< CType >::add(), C_INVALID_INDEX, CModelParameterSet::createFromModel(), CCopasiVectorN< CType >::getIndex(), CCopasiDataModel::getModel(), CModel::getModelParameterSets(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectName(), and UTCTimeStamp().
Referenced by CFitProblem::calculate().
 {
   if (pExp == NULL) return;
   CModel* model = pExp->getObjectDataModel()->getModel();
   std::string origname = "PE: "  + UTCTimeStamp() + " Exp: " + pExp->getObjectName();
   std::string name = origname;
   int count = 0;
   while (model->getModelParameterSets().getIndex(name) != C_INVALID_INDEX)
     {
       std::stringstream str; str << origname << " (" << ++count << ")";
       name = str.str();
     }
   CModelParameterSet* set = new CModelParameterSet(name);
   model->getModelParameterSets().add(set, true);
   set->createFromModel();
 }
std::ostream& operator<< (std::ostream & os, const CFitProblem & o)
Output stream operator
Parameters
ostream & os
const CFitProblem & A
Returns
ostream & os
Definition at line 1240 of file CFitProblem.cpp.
References CCopasiTask::getDescription(), COptProblem::mpConstraintItems, COptProblem::mpOptItems, CFitProblem::mpSteadyState, CFitProblem::mpTrajectory, and CCopasiTask::CDescription::print().
 {
   os << "Problem Description:" << std::endl;
   os << "Subtask: " << std::endl;
   if (o.mpSteadyState)
     o.mpSteadyState->getDescription().print(&os);
   if (o.mpTrajectory)
     o.mpTrajectory->getDescription().print(&os);
   if (!o.mpTrajectory && !o.mpSteadyState)
     os << "No Subtask specified.";
   os << std::endl;
   os << "List of Fitting Items:" << std::endl;
   std::vector< COptItem * >::const_iterator itItem =
     o.mpOptItems->begin();
   std::vector< COptItem * >::const_iterator endItem =
     o.mpOptItems->end();
   for (; itItem != endItem; ++itItem)
     os << "    " << *static_cast<CFitItem *>(*itItem) << std::endl;
   itItem = o.mpConstraintItems->begin();
   endItem = o.mpConstraintItems->end();
   for (; itItem != endItem; ++itItem)
     os << "    " << *static_cast<CFitItem *>(*itItem) << std::endl;
   return os;
 }