COPASI API: CQPlotColors Class Reference
CQPlotColors Class Reference
#include <CQPlotColors.h>
Static Public Member Functions
static QColor getColor (std::string colorstr, size_t colorindex)
Static Public Member Functions inherited from CPlotColors
static std::string getCopasiColorStr (size_t index)
static size_t getNumCopasiColors ()
Detailed Description
Definition at line 17 of file CQPlotColors.h.
Member Function Documentation
QColor CQPlotColors::getColor (std::string colorstr, size_t colorindex) static
Definition at line 18 of file CQPlotColors.cpp.
References CPlotColors::getCopasiColorStr().
Referenced by CopasiPlot::initFromSpec(), and Curve2DWidget::LoadFromCurveSpec().
 {
   if (colorstr == "auto")
     {
       return QColor(getCopasiColorStr(colorindex).c_str());
     }
   else
     {
       return QColor(colorstr.c_str());
     }
 }
The documentation for this class was generated from the following files:
CQPlotColors.h
CQPlotColors.cpp