COPASI API: CQExperimentSelection Class Reference
CQExperimentSelection Class Reference
#include <CQExperimentSelection.h>
Public Member Functions
CQExperimentSelection (QWidget *parent=0, const char *name=0, bool modal=false, Qt::WindowFlags fl=0)
virtual void load (QComboBox *pBox, const CExperimentSet *pExperimentSet)
~CQExperimentSelection ()
Protected Slots
void slotBtnAll ()
void slotBtnCancel ()
void slotBtnNone ()
void slotBtnOK ()
Protected Attributes
QComboBox * mpBox
Private Member Functions
void init ()
Detailed Description
Definition at line 25 of file CQExperimentSelection.h.
Constructor & Destructor Documentation
CQExperimentSelection::CQExperimentSelection (QWidget * parent = 0, const char * name = 0, bool modal = false, Qt::WindowFlags fl = 0)
Definition at line 32 of file CQExperimentSelection.cpp.
References init().
     : QDialog(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   setupUi(this);
   init();
 }
CQExperimentSelection::~CQExperimentSelection ()
Definition at line 45 of file CQExperimentSelection.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQExperimentSelection::init () private
Definition at line 125 of file CQExperimentSelection.cpp.
References mpBox.
Referenced by CQExperimentSelection().
 {
   mpBox = NULL;
 }
void CQExperimentSelection::load (QComboBox * pBox, const CExperimentSet * pExperimentSet) virtual
Definition at line 91 of file CQExperimentSelection.cpp.
References FROM_UTF8, CExperimentSet::getExperiment(), CExperimentSet::getExperimentCount(), CCopasiObject::getObjectName(), mpBox, and slotBtnAll().
Referenced by CQFittingItemWidget::slotCrossValidations(), and CQFittingItemWidget::slotExperiments().
 {
   mpBox = pBox;
   mpList->clear();
   QStringList Items;
   size_t i, imax = pExperimentSet->getExperimentCount();
   for (i = 0; i < imax; i++)
     {
       Items.append(FROM_UTF8(pExperimentSet->getExperiment(i)->getObjectName()));
     }
   mpList->addItems(Items);
   int j, jmax = mpBox->count();
   if (jmax == 0)
     {
       slotBtnAll();
       return;
     }
   for (j = 0; j < jmax; j++)
     {
       QList< QListWidgetItem * > Found = mpList->findItems(mpBox->itemText(j), Qt::MatchExactly);
       if (Found.size() > 0)
         {
           Found[0]->setSelected(true);
         }
     }
 }
void CQExperimentSelection::slotBtnAll () protected slot
Definition at line 81 of file CQExperimentSelection.cpp.
Referenced by load().
 {
   mpList->selectAll();
 }
void CQExperimentSelection::slotBtnCancel () protected slot
Definition at line 76 of file CQExperimentSelection.cpp.
 {
   reject();
 }
void CQExperimentSelection::slotBtnNone () protected slot
Definition at line 86 of file CQExperimentSelection.cpp.
 {
   mpList->clearSelection();
 }
void CQExperimentSelection::slotBtnOK () protected slot
Definition at line 50 of file CQExperimentSelection.cpp.
References mpBox.
 {
   mpBox->clear();
   if (mpList->selectedItems().count() != mpList->count())
     {
       QListWidgetItem * pItem;
       QStringList Items;
       int i, imax = mpList->count();
       for (i = 0; i != imax; ++i)
         {
           pItem = mpList->item(i);
           if (pItem->isSelected())
             {
               Items.append(pItem->text());
             }
         }
       mpBox->addItems(Items);
     }
   accept();
 }
Member Data Documentation
QComboBox* CQExperimentSelection::mpBox protected
Definition at line 36 of file CQExperimentSelection.h.
Referenced by init(), load(), and slotBtnOK().
The documentation for this class was generated from the following files:
CQExperimentSelection.h
CQExperimentSelection.cpp