COPASI API: CCopasiXMLParser::EventElement Class Reference
CCopasiXMLParser::EventElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
EventElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~EventElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Event = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
TriggerExpression, DelayExpression, ListOfAssignments
}
Private Attributes
std::string mKey
ListOfAssignmentsElement * mpListOfAssignmentsElementHandler
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1585 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::EventElement::Element private
Enum of invoked parsers
Enumerator
Event
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
TriggerExpression
DelayExpression
ListOfAssignments
Definition at line 1593 of file CCopasiXMLParser.h.
     {
       Event = 0,
       MiriamAnnotation,
       Comment,
       ListOfUnsupportedAnnotations,
       TriggerExpression,
       DelayExpression,
       ListOfAssignments
     };
Constructor & Destructor Documentation
CCopasiXMLParser::EventElement::EventElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 3181 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpListOfAssignmentsElementHandler(NULL)
 {}
CCopasiXMLParser::EventElement::~EventElement () virtual
Destructor
Definition at line 3187 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpListOfAssignmentsElementHandler);
 }
Member Function Documentation
void CCopasiXMLParser::EventElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 3315 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CEvent::getKey(), CCopasiMessage::getLastMessage(), CAnnotation::getUnsupportedAnnotations(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pEvent, CEvent::setDelayExpression(), CAnnotation::setMiriamAnnotation(), CAnnotation::setNotes(), CEvent::setTriggerExpression(), CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Event:
         if (strcmp(pszName, "Event"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Event", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         mCommon.pEvent->setMiriamAnnotation(mCommon.CharacterData, mCommon.pEvent->getKey(), mKey);
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         mCommon.pEvent->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         mCommon.pEvent->getUnsupportedAnnotations() = mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case TriggerExpression:
         if (strcmp(pszName, "TriggerExpression"))
           {
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "TriggerExpression", mParser.getCurrentLineNumber());
           }
         {
           size_t Size = CCopasiMessage::size();
           mCommon.pEvent->setTriggerExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             {
               CCopasiMessage msg = CCopasiMessage::getLastMessage();
             }
         }
         break;
       case DelayExpression:
         if (strcmp(pszName, "DelayExpression"))
           {
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "DelayExpression", mParser.getCurrentLineNumber());
           }
         {
           size_t Size = CCopasiMessage::size();
           mCommon.pEvent->setDelayExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             {
               CCopasiMessage msg = CCopasiMessage::getLastMessage();
             }
         }
         break;
       case ListOfAssignments:
         break;
       case UNKNOWN_ELEMENT:
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   mCurrentElement = Event;
   return;
 }
void CCopasiXMLParser::EventElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 3192 of file CCopasiXMLParser.cpp.
References CCopasiVectorN< CType >::add(), CCopasiMessage::EXCEPTION, CModel::getEvents(), CVersion::getVersionDevel(), SCopasiXMLParserCommon::mAssignments, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pEvent, SCopasiXMLParserCommon::pModel, SCopasiXMLParserCommon::pVersion, CEvent::setDelayAssignment(), CEvent::setFireAtInitialTime(), CCopasiObject::setObjectName(), CEvent::setPersistentTrigger(), and UNKNOWN_ELEMENT.
 {
   const char * Name;
   bool DelayAssignment;
   bool FireAtInitialTime;
   bool PersistentTrigger;
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case Event:
             if (strcmp(pszName, "Event"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "Event", mParser.getCurrentLineNumber());
             mKey = mParser.getAttributeValue("key", papszAttrs);
             Name = mParser.getAttributeValue("name", papszAttrs);
             DelayAssignment =
               mParser.toBool(mParser.getAttributeValue("delayAssignment", papszAttrs, false));
             FireAtInitialTime =
               mParser.toBool(mParser.getAttributeValue("fireAtInitialTime", papszAttrs, false));
             if (mCommon.pVersion->getVersionDevel() <= 90)
               {
                 PersistentTrigger = true;
               }
             else
               {
                 PersistentTrigger = mParser.toBool(mParser.getAttributeValue("persistentTrigger", papszAttrs, true));
               }
             mCommon.pEvent = new CEvent();
             addFix(mKey, mCommon.pEvent);
             mCommon.pEvent->setObjectName(Name);
             mCommon.pEvent->setDelayAssignment(DelayAssignment);
             mCommon.pEvent->setFireAtInitialTime(FireAtInitialTime);
             mCommon.pEvent->setPersistentTrigger(PersistentTrigger);
             mCommon.pModel->getEvents().add(mCommon. pEvent, true);
             mLastKnownElement = Event;
             return;
           case MiriamAnnotation:
             if (!strcmp(pszName, "MiriamAnnotation"))
               mpCurrentHandler = &mParser.mMiriamAnnotationElement;
             break;
           case Comment:
             if (!strcmp(pszName, "Comment"))
               mpCurrentHandler = &mParser.mCommentElement;
             break;
           case ListOfUnsupportedAnnotations:
             if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
               mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             break;
           case TriggerExpression:
             if (!strcmp(pszName, "TriggerExpression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           case DelayExpression:
             if (!strcmp(pszName, "DelayExpression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           case ListOfAssignments:
             if (!strcmp(pszName, "ListOfAssignments"))
               {
                 if (!mpListOfAssignmentsElementHandler)
                   {
                     mpListOfAssignmentsElementHandler =
                       new ListOfAssignmentsElement(mParser, mCommon);
                     mCommon.mAssignments.reserve(100);
                     mCommon.mAssignments.resize(0);
                   }
                 mpCurrentHandler = mpListOfAssignmentsElementHandler;
               }
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::EventElement::mKey private
The key in the CopasiML file
Definition at line 1607 of file CCopasiXMLParser.h.
ListOfAssignmentsElement* CCopasiXMLParser::EventElement::mpListOfAssignmentsElementHandler private
Definition at line 1609 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp