COPASI API: CODEExporterC.cpp File Reference
CODEExporterC.cpp File Reference
#include <sstream>
#include <locale>
#include <cmath>
#include "copasi.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "CODEExporterC.h"
#include "model/CModel.h"
#include "model/CMetab.h"
#include "model/CMetabNameInterface.h"
#include "utilities/CCopasiVector.h"
#include "model/CReaction.h"
#include "model/CMoiety.h"
#include "model/CChemEqElement.h"
#include "function/CExpression.h"
#include "function/CFunction.h"
#include "function/CFunctionDB.h"
#include "report/CKeyFactory.h"
#include "function/CEvaluationTree.h"
#include "function/CEvaluationNode.h"
#include "function/CEvaluationNodeObject.h"
#include "function/CEvaluationNodeOperator.h"
#include "function/CEvaluationNodeFunction.h"
#include "utilities/CCopasiTree.h"
#include "trajectory/CTrajectoryTask.h"
#include "trajectory/CTrajectoryProblem.h"
#include <sbml/util/util.h>
#include <iostream>
#include <fstream>
#include <ctype.h>
Functions
void printNameForKey (std::ostringstream &stream, CKeyFactory *kf, const std::string &key, const std::string prefix="")
bool startsWith (const std::string &str, const std::string &sub)
Function Documentation
void printNameForKey (std::ostringstream & stream, CKeyFactory * kf, const std::string & key, const std::string prefix = "")
Definition at line 76 of file CODEExporterC.cpp.
References CKeyFactory::get(), CCopasiObject::getObjectName(), and startsWith().
Referenced by CODEExporterC::exportTitleData().
 {
   CCopasiObject* obj = kf->get(key);
   if (obj != NULL)
     {
       stream << "\"" << prefix << obj->getObjectName() << "\", ";
     }
   else if (startsWith(key, "sm_"))
     {
       printNameForKey(stream, kf, key.substr(3), "");
     }
   else if (startsWith(key, "ode_"))
     {
       printNameForKey(stream, kf, key.substr(4), "ODE ");
     }
   else
     {
       stream << "\"" << prefix << key << "\", ";
     }
 }
bool startsWith (const std::string & str, const std::string & sub)
Definition at line 64 of file CODEExporterC.cpp.
Referenced by CODEExporterC::exportTitleData(), and printNameForKey().
 {
   if (str.length() < sub.length()) return false;
   if (sub.empty()) return true;
   for (size_t i = 0; i < sub.length(); ++i)
     if (str[i] != sub[i]) return false;
   return true;
 }