COPASI API: CSteadyStateMethod Class Reference
CSteadyStateMethod Class Reference
#include <CSteadyStateMethod.h>
Public Types
enum ReturnCode { notFound = 0, found, foundEquilibrium, foundNegative }
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CSteadyStateMethod (const CSteadyStateMethod &src, const CCopasiContainer *pParent=NULL)
void doJacobian (CMatrix< C_FLOAT64 > &jacobian, CMatrix< C_FLOAT64 > &jacobianX)
bool elevateChildren ()
std::string getMethodLog () const
C_FLOAT64 getStabilityResolution ()
virtual bool initialize (const CSteadyStateProblem *pProblem)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
CSteadyStateMethod::ReturnCode process (CState *pState, CMatrix< C_FLOAT64 > &jacobianX, CProcessReport *handler)
~CSteadyStateMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static CSteadyStateMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::Newton)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
bool allPositive ()
void calculateJacobianX (const C_FLOAT64 &oldMaxRate)
CSteadyStateMethod (CCopasiMethod::SubType subType, const CCopasiContainer *pParent=NULL)
void initializeParameter ()
bool isEquilibrium (const C_FLOAT64 &resolution) const
virtual
CSteadyStateMethod::ReturnCode processInternal ()
virtual
CSteadyStateMethod::ReturnCode returnProcess (bool steadyStateFound)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
std::ostringstream mMethodLog
C_FLOAT64 * mpDerivationFactor
C_FLOAT64 * mpDerivationResolution
CMatrix< C_FLOAT64 > * mpJacobianX
CModel * mpModel
CSteadyStateTask * mpParentTask
const CSteadyStateProblem * mpProblem
C_FLOAT64 * mpSSResolution
CState * mpSteadyState
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CSteadyStateMethod ()
Additional Inherited Members
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 43 of file CSteadyStateMethod.h.
Member Enumeration Documentation
enum CSteadyStateMethod::ReturnCode
Enumerator
notFound
found
foundEquilibrium
foundNegative
Definition at line 46 of file CSteadyStateMethod.h.
   {
     notFound = 0,
     found,
     foundEquilibrium,
     foundNegative
   };
Constructor & Destructor Documentation
CSteadyStateMethod::CSteadyStateMethod () private
Default constructor.
CSteadyStateMethod::CSteadyStateMethod (CCopasiMethod::SubType subType, const CCopasiContainer * pParent = NULL) protected
Specific constructor.
Parameters
CCopasiMethod::SubType subType
const CCopasiContainer * pParent (default: NULL)
Default constructor.
Definition at line 58 of file CSteadyStateMethod.cpp.
References CONSTRUCTOR_TRACE, and initializeParameter().
                                                                         :
   CCopasiMethod(CCopasiTask::steadyState, subType, pParent),
   mpProblem(NULL)
 {
   initializeParameter();
   CONSTRUCTOR_TRACE;
 }
CSteadyStateMethod::CSteadyStateMethod (const CSteadyStateMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CSteadyStateMethod & src
const CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CSteadyStateMethod & src
Definition at line 71 of file CSteadyStateMethod.cpp.
References CONSTRUCTOR_TRACE, and initializeParameter().
                                                                         :
   CCopasiMethod(src, pParent),
   mpProblem(src.mpProblem)
 {
   initializeParameter();
   CONSTRUCTOR_TRACE;
 }
CSteadyStateMethod::~CSteadyStateMethod ()
Destructor.
Definition at line 83 of file CSteadyStateMethod.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
bool CSteadyStateMethod::allPositive () protected
Check whether all values make physically sence, i.e., volumes and particle number are positive
Returns
bool allPositive
Definition at line 190 of file CSteadyStateMethod.cpp.
References CStateTemplate::beginIndependent(), CState::beginIndependent(), C_FLOAT64, CState::endDependent(), CModel::getQuantity2NumberFactor(), CModel::getState(), CModel::getStateTemplate(), mpDerivationResolution, mpModel, and CModel::updateSimulatedValues().
Referenced by CNewtonMethod::doIntegration(), CNewtonMethod::doNewtonStep(), and returnProcess().
 {
   // Assure that all values are updated.
   mpModel->updateSimulatedValues(true);
   CModelEntity *const* ppEntity = mpModel->getStateTemplate().beginIndependent();
   const C_FLOAT64 * pIt = mpModel->getState().beginIndependent();
   const C_FLOAT64 * pEnd = mpModel->getState().endDependent();
   // Skip Model quantities of type ODE
   for (; pIt != pEnd; ++pIt, ++ppEntity)
     if (dynamic_cast< const CCompartment *>(*ppEntity) != NULL ||
         dynamic_cast< const CMetab *>(*ppEntity) != NULL)
       break;
   // For all compartments of type ODE we check that the volume is positive
   for (; pIt != pEnd; ++pIt, ++ppEntity)
     {
       if (dynamic_cast< const CCompartment *>(*ppEntity) == NULL)
         break;
       if (*pIt < - *mpDerivationResolution)
         return false;
     }
   // We need to check that all metabolites have positive particle numbers
   // with respect to the given resolution.
   C_FLOAT64 ParticleResolution =
     - *mpDerivationResolution * mpModel->getQuantity2NumberFactor();
   for (; pIt != pEnd; ++pIt, ++ppEntity)
     {
       if (dynamic_cast< const CMetab *>(*ppEntity) == NULL)
         break;
       if (*pIt < ParticleResolution)
         return false;
     }
   // For all compartments of type ASSIGNMENT we check that the volume is positive
   for (; pIt != pEnd; ++pIt, ++ppEntity)
     {
       if (dynamic_cast< CCompartment *>(*ppEntity) == NULL)
         break;
       if (*pIt < - *mpDerivationResolution)
         return false;
     }
   return true;
 }
void CSteadyStateMethod::calculateJacobianX (const C_FLOAT64 & oldMaxRate) protected
Definition at line 285 of file CSteadyStateMethod.cpp.
References CModel::calculateJacobianX(), min, mpDerivationFactor, mpDerivationResolution, mpJacobianX, mpModel, mpSteadyState, CModel::setState(), and CModel::updateSimulatedValues().
Referenced by CNewtonMethod::doNewtonStep(), and CNewtonMethod::targetFunction().
 {
   mpModel->setState(*mpSteadyState);
   mpModel->updateSimulatedValues(true);
   mpModel->calculateJacobianX(*mpJacobianX,
                               std::min(*mpDerivationFactor, oldMaxRate),
                               *mpDerivationResolution);
 }
CSteadyStateMethod * CSteadyStateMethod::createMethod (CCopasiMethod::SubType subType = CCopasiMethod::Newton) static
Create a trajectory method. Note: the returned object has to be released after use with delete
CSteadyStateMethod class. This class describes the interface to all steady state methods. The various method like Newton have to be derived from this class.
Created for COPASI by Stefan Hoops 2002
Definition at line 37 of file CSteadyStateMethod.cpp.
References fatalError, CCopasiMethod::Newton, and CCopasiMethod::unset.
Referenced by CSteadyStateTask::createMethod().
 {
   CSteadyStateMethod * pMethod = NULL;
   switch (subType)
     {
       case unset:
       case Newton:
         pMethod = new CNewtonMethod();
         break;
       default:
         fatalError();
     }
   return pMethod;
 }
void CSteadyStateMethod::doJacobian (CMatrix< C_FLOAT64 > & jacobian, CMatrix< C_FLOAT64 > & jacobianX)
calls the CModel methods to calculate the jacobians (at the steady state). This trivial method is implemented in the method because it may need to know about some method parameters
Definition at line 267 of file CSteadyStateMethod.cpp.
References CModel::calculateJacobian(), CModel::calculateJacobianX(), mpDerivationResolution, mpModel, mpSteadyState, CModel::setState(), and CModel::updateSimulatedValues().
Referenced by CSteadyStateTask::process().
 {
   mpModel->setState(*mpSteadyState);
   mpModel->updateSimulatedValues(true);
   mpModel->calculateJacobian(jacobian, *mpDerivationResolution, *mpDerivationResolution);
   mpModel->calculateJacobianX(jacobianX, *mpDerivationResolution, *mpDerivationResolution);
 }
bool CSteadyStateMethod::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 111 of file CSteadyStateMethod.cpp.
References initializeParameter().
 {
   initializeParameter();
   return true;
 }
std::string CSteadyStateMethod::getMethodLog () const
Definition at line 294 of file CSteadyStateMethod.cpp.
References mMethodLog.
Referenced by StateSubwidget::loadAll().
 {
   return mMethodLog.str();
 }
C_FLOAT64 CSteadyStateMethod::getStabilityResolution ()
returns the resolution for stability analysis
Definition at line 277 of file CSteadyStateMethod.cpp.
References C_FLOAT64, CCopasiParameter::getValue(), and CCopasiParameter::Value::pUDOUBLE.
Referenced by CSteadyStateTask::process().
 {
   //C_FLOAT64* pTmp = (C_FLOAT64*)getValue("Stability Resolution").pUDOUBLE;
   C_FLOAT64* pTmp = (C_FLOAT64*)getValue("Resolution").pUDOUBLE;
   assert(pTmp);
   return *pTmp;
 }
bool CSteadyStateMethod::initialize (const CSteadyStateProblem * pProblem) virtual
Initialize the method must be called before process
Parameters
const CSteadyStateProblem * pProblem
Returns
bool success
Reimplemented in CNewtonMethod.
Definition at line 259 of file CSteadyStateMethod.cpp.
References CCopasiProblem::getModel(), mpModel, and mpProblem.
Referenced by CNewtonMethod::initialize(), and CSteadyStateTask::initialize().
 {
   mpProblem = pProblem;
   mpModel = mpProblem->getModel();
   return true;
 }
void CSteadyStateMethod::initializeParameter () protected
initialize parameters and handle parameters of old copasi files
Definition at line 86 of file CSteadyStateMethod.cpp.
References CCopasiParameterGroup::assertParameter(), C_FLOAT64, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValue(), mpDerivationFactor, mpDerivationResolution, mpSSResolution, CCopasiParameter::Value::pUDOUBLE, CCopasiParameterGroup::removeParameter(), CCopasiParameterGroup::setValue(), and CCopasiParameter::UDOUBLE.
Referenced by CSteadyStateMethod(), CNewtonMethod::elevateChildren(), and elevateChildren().
 {
   CCopasiParameter *pParm;
   assertParameter("Resolution", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0e-009);
   mpSSResolution = (C_FLOAT64*)getValue("Resolution").pUDOUBLE;
   mpDerivationResolution = (C_FLOAT64*)getValue("Resolution").pUDOUBLE;
   assertParameter("Derivation Factor", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0e-003);
   mpDerivationFactor = (C_FLOAT64*)getValue("Derivation Factor").pUDOUBLE;
   // Check whether we have a method with the old parameter names
   if ((pParm = getParameter("Newton.DerivationFactor")) != NULL)
     {
       setValue("Derivation Factor", *pParm->getValue().pUDOUBLE);
       removeParameter("Newton.DerivationFactor");
     }
   if ((pParm = getParameter("Newton.Resolution")) != NULL)
     {
       setValue("Resolution", *pParm->getValue().pUDOUBLE);
       removeParameter("Newton.Resolution");
     }
 }
bool CSteadyStateMethod::isEquilibrium (const C_FLOAT64 & resolution) const protected
Check whether the steady state is chemical equilibrium
Parameters
const C_FLOAT64 & resolution bool isEquilibrium
Definition at line 173 of file CSteadyStateMethod.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CCopasiProblem::getModel(), CModel::getReactions(), CModelEntity::getValue(), and mpProblem.
Referenced by returnProcess().
 {
   CCopasiVectorNS < CReaction >::const_iterator it =  mpProblem->getModel()->getReactions().begin();
   CCopasiVectorNS < CReaction >::const_iterator end =  mpProblem->getModel()->getReactions().end();
   for (; it != end; ++it)
     {
       const CCompartment * pCompartment = (*it)->getLargestCompartment();
       if (pCompartment != NULL &&
           (*it)->getFlux() / pCompartment->getValue() > resolution)
         return false; //TODO: smallest or largest ?
     }
   return true;
 }
bool CSteadyStateMethod::isValidProblem (const CCopasiProblem * pProblem) virtual
Check if the method is suitable for this problem
Returns
bool suitability of the method
Reimplemented from CCopasiMethod.
Reimplemented in CNewtonMethod.
Definition at line 243 of file CSteadyStateMethod.cpp.
References CCopasiMessage::EXCEPTION, and CCopasiMethod::isValidProblem().
Referenced by CNewtonMethod::isValidProblem().
 {
   if (!CCopasiMethod::isValidProblem(pProblem)) return false;
   const CSteadyStateProblem * pP = dynamic_cast<const CSteadyStateProblem *>(pProblem);
   if (!pP)
     {
       //not a TrajectoryProblem
       CCopasiMessage(CCopasiMessage::EXCEPTION, "Problem is not a steady state problem.");
       return false;
     }
   return true;
 }
CSteadyStateMethod::ReturnCode CSteadyStateMethod::process (CState * pState, CMatrix< C_FLOAT64 > & jacobianX, CProcessReport * handler)
This instructs the method to calculate a the steady state starting with the initialState given. The steady state is returned in the object pointed to by steadyState.
Parameters
CState * steadyState
CMatrix< C_FLOAT64 > & jacobianX
CProcessReport * handler
Returns
CSteadyStateMethod::ReturnCode returnCode
This instructs the method to calculate a the steady state starting with the initialState given. The steady state is returned in the object pointed to by steadyState.
Parameters
CState * steadyState
const CState * initialState
C_FLOAT64 * jacobian
CEigen * eigenValues
Returns
CSteadyStateMethod::ReturnCode returnCode
Definition at line 128 of file CSteadyStateMethod.cpp.
References CCopasiObject::getObjectParent(), CCopasiMethod::mpCallBack, mpJacobianX, mpParentTask, mpSteadyState, and processInternal().
Referenced by CSteadyStateTask::process().
 {
   mpParentTask = dynamic_cast<CSteadyStateTask *>(getObjectParent());
   assert(mpParentTask);
   mpSteadyState = pState;
   mpJacobianX = & jacobianX;
   mpCallBack = handler;
   return processInternal();
 }
CSteadyStateMethod::ReturnCode CSteadyStateMethod::processInternal () protected virtual
This instructs the method to calculate a the steady state starting with the initialState given. The steady state is returned in the object pointed to by steadyState.
Returns
CSteadyStateMethod::ReturnCode returnCode
This instructs the method to calculate a the steady state
Returns
CSteadyStateMethod::ReturnCode returnCode
Reimplemented in CNewtonMethod.
Definition at line 170 of file CSteadyStateMethod.cpp.
References notFound.
Referenced by process().
 {return CSteadyStateMethod::notFound;}
CSteadyStateMethod::ReturnCode CSteadyStateMethod::returnProcess (bool steadyStateFound) protected virtual
This function has to be called at the return of any implementation of the protected function process()
Returns
CSteadyStateMethod::ReturnCode returnCode
This function has to be called at the return of any implementation of the protected function process
Parameters
bool success
const C_FLOAT64 & factor
const C_FLOAT64 & resolution
Returns
CSteadyStateMethod::ReturnCode returnCode
Definition at line 151 of file CSteadyStateMethod.cpp.
References allPositive(), found, foundEquilibrium, foundNegative, isEquilibrium(), mpSSResolution, and notFound.
Referenced by CNewtonMethod::processInternal().
 {
   if (!steadyStateFound)
     return CSteadyStateMethod::notFound;
   if (!allPositive())
     return CSteadyStateMethod::foundNegative;
   if (isEquilibrium(*mpSSResolution))
     return CSteadyStateMethod::foundEquilibrium;
   return CSteadyStateMethod::found;
 }
Member Data Documentation
std::ostringstream CSteadyStateMethod::mMethodLog protected
Definition at line 95 of file CSteadyStateMethod.h.
Referenced by CNewtonMethod::doIntegration(), CNewtonMethod::doNewtonStep(), getMethodLog(), CNewtonMethod::processInternal(), and CNewtonMethod::processNewton().
C_FLOAT64* CSteadyStateMethod::mpDerivationFactor protected
The factor for numerical derivation
Definition at line 88 of file CSteadyStateMethod.h.
Referenced by calculateJacobianX(), and initializeParameter().
C_FLOAT64* CSteadyStateMethod::mpDerivationResolution protected
The resolution of the variable of numerical derivation
Definition at line 93 of file CSteadyStateMethod.h.
Referenced by allPositive(), calculateJacobianX(), doJacobian(), and initializeParameter().
CMatrix< C_FLOAT64 >* CSteadyStateMethod::mpJacobianX protected
The jacobian of the steadystate
Definition at line 78 of file CSteadyStateMethod.h.
Referenced by calculateJacobianX(), process(), and CNewtonMethod::solveJacobianXeqB().
CModel* CSteadyStateMethod::mpModel protected
A pointer to the model.
Definition at line 63 of file CSteadyStateMethod.h.
Referenced by allPositive(), CNewtonMethod::calculateDerivativesX(), calculateJacobianX(), CNewtonMethod::doIntegration(), doJacobian(), CNewtonMethod::initialize(), initialize(), CNewtonMethod::solveJacobianXeqB(), and CNewtonMethod::targetFunction().
CSteadyStateTask* CSteadyStateMethod::mpParentTask protected
A pointer to the task.
Definition at line 68 of file CSteadyStateMethod.h.
Referenced by process().
const CSteadyStateProblem* CSteadyStateMethod::mpProblem protected
A pointer to the problem.
Definition at line 58 of file CSteadyStateMethod.h.
Referenced by CNewtonMethod::initialize(), initialize(), and isEquilibrium().
C_FLOAT64* CSteadyStateMethod::mpSSResolution protected
The concentration rate that is considered zero
Definition at line 83 of file CSteadyStateMethod.h.
Referenced by CNewtonMethod::initialize(), initializeParameter(), CNewtonMethod::isSteadyState(), returnProcess(), and CNewtonMethod::targetFunction().
CState* CSteadyStateMethod::mpSteadyState protected
A pointer to the steady state
Definition at line 73 of file CSteadyStateMethod.h.
Referenced by CNewtonMethod::calculateDerivativesX(), calculateJacobianX(), CNewtonMethod::containsNaN(), CNewtonMethod::doIntegration(), doJacobian(), process(), CNewtonMethod::processInternal(), CNewtonMethod::solveJacobianXeqB(), and CNewtonMethod::targetFunction().
The documentation for this class was generated from the following files:
CSteadyStateMethod.h
CSteadyStateMethod.cpp