COPASI API: Cmt19937 Class Reference
Cmt19937 Class Reference
#include <Cmt19937.h>
Public Member Functions
C_FLOAT64 genrand_res53 ()
C_FLOAT64 getRandomCC ()
C_FLOAT64 getRandomCO ()
C_FLOAT64 getRandomOO ()
C_INT32 getRandomS ()
unsigned C_INT32 getRandomU ()
void init_by_array (unsigned C_INT32 init_key[], C_INT32 key_length)
void initialize (unsigned C_INT32 seed=CRandom::getSystemSeed())
~Cmt19937 ()
Public Member Functions inherited from CRandom
const unsigned C_INT32 & getModulus () const
virtual C_FLOAT64 getRandomExp ()
virtual C_FLOAT64 getRandomGamma (C_FLOAT64 shape, C_FLOAT64 scale)
virtual C_FLOAT64 getRandomNormal (const C_FLOAT64 &mean, const C_FLOAT64 &sd)
virtual C_FLOAT64 getRandomNormal01 ()
virtual C_FLOAT64 getRandomNormalLog (const C_FLOAT64 &mean, const C_FLOAT64 &sd)
virtual C_FLOAT64 getRandomNormalPositive (const C_FLOAT64 &mean, const C_FLOAT64 &sd)
virtual C_FLOAT64 getRandomPoisson (const C_FLOAT64 &mean)
virtual C_INT32 getRandomS (const C_INT32 &max)
virtual C_FLOAT64 getRandomStdGamma (C_FLOAT64 shape)
virtual unsigned C_INT32 getRandomU (const unsigned C_INT32 &max)
const CRandom::Type & getType () const
virtual ~CRandom ()
Protected Member Functions
Cmt19937 (unsigned C_INT32 seed)
void next_state ()
Protected Member Functions inherited from CRandom
CRandom ()
void setModulus (const unsigned C_INT32 &modulus)
Private Attributes
C_INT mLeft
unsigned C_INT32 * mNext
unsigned C_INT32 mState [624]
Friends
CRandom * CRandom::createGenerator (CRandom::Type type, unsigned C_INT32 seed)
Additional Inherited Members
Public Types inherited from CRandom
enum Type { r250 = 0, mt19937, mt19937HR, unkown }
Static Public Member Functions inherited from CRandom
static CRandom * createGenerator (CRandom::Type type=CRandom::mt19937, unsigned C_INT32 seed=0)
static unsigned C_INT32 getSystemSeed ()
Static Public Attributes inherited from CRandom
static const std::string TypeName []
static const char * XMLType []
Protected Attributes inherited from CRandom
C_FLOAT64 mFloat
unsigned C_INT32 mModulus
C_FLOAT64 mModulusInv
C_FLOAT64 mModulusInv1
C_INT32 mNumberS
unsigned C_INT32 mNumberU
CRandom::Type mType
Detailed Description
Definition at line 67 of file Cmt19937.h.
Constructor & Destructor Documentation
Cmt19937::Cmt19937 (unsigned C_INT32 seed) protected
Default/Named constructor. Seeds the random number generator with the given seed.
Parameters
C_INT32 seed
Definition at line 75 of file Cmt19937.cpp.
References initialize(), and CRandom::setModulus().
                                        :
     CRandom(),
     mLeft(1),
     mNext(NULL)
 {
   setModulus(0xffffffffUL);
   initialize(seed);
 }
Cmt19937::~Cmt19937 ()
The destructor.
Definition at line 84 of file Cmt19937.cpp.
 {}
Member Function Documentation
C_FLOAT64 Cmt19937::genrand_res53 ()
Definition at line 241 of file Cmt19937.cpp.
References C_INT32, getRandomU(), and CRandom::mFloat.
 {
   unsigned C_INT32 a = getRandomU() >> 5, b = getRandomU() >> 6;
   return mFloat = (a * 67108864.0 + b) * (1.0 / 9007199254740992.0);
 }
C_FLOAT64 Cmt19937::getRandomCC () virtual
Produces a uniformly distributed random number in 0 <= x <= 1.
Returns
C_FLOAT64 random
Reimplemented from CRandom.
Reimplemented in Cmt19937HR.
Definition at line 190 of file Cmt19937.cpp.
References C_FLOAT64, mLeft, mNext, CRandom::mNumberU, and next_state().
 {
   if (--mLeft == 0)
     next_state();
   mNumberU = *mNext++;
   /* Tempering */
   mNumberU ^= (mNumberU >> 11);
   mNumberU ^= (mNumberU << 7) & 0x9d2c5680UL;
   mNumberU ^= (mNumberU << 15) & 0xefc60000UL;
   mNumberU ^= (mNumberU >> 18);
   return ((C_FLOAT64) mNumberU) * (1.0 / 4294967295.0);
   /* divided by 2^32-1 */
 }
C_FLOAT64 Cmt19937::getRandomCO () virtual
Produces a uniformly distributed random number in 0 <= x < 1. Note: 0 < x <= 1 may be achieved by 1.0 - getRandomCO().
Returns
C_FLOAT64 random
Reimplemented from CRandom.
Reimplemented in Cmt19937HR.
Definition at line 207 of file Cmt19937.cpp.
References C_FLOAT64, mLeft, mNext, CRandom::mNumberU, and next_state().
 {
   if (--mLeft == 0)
     next_state();
   mNumberU = *mNext++;
   /* Tempering */
   mNumberU ^= (mNumberU >> 11);
   mNumberU ^= (mNumberU << 7) & 0x9d2c5680UL;
   mNumberU ^= (mNumberU << 15) & 0xefc60000UL;
   mNumberU ^= (mNumberU >> 18);
   return ((C_FLOAT64) mNumberU) * (1.0 / 4294967296.0);
   /* divided by 2^32 */
 }
C_FLOAT64 Cmt19937::getRandomOO () virtual
Produces a uniformly distributed random number in 0 < x < 1.
Returns
C_FLOAT64 random
Reimplemented from CRandom.
Reimplemented in Cmt19937HR.
Definition at line 224 of file Cmt19937.cpp.
References C_FLOAT64, mLeft, mNext, CRandom::mNumberU, and next_state().
 {
   if (--mLeft == 0)
     next_state();
   mNumberU = *mNext++;
   /* Tempering */
   mNumberU ^= (mNumberU >> 11);
   mNumberU ^= (mNumberU << 7) & 0x9d2c5680UL;
   mNumberU ^= (mNumberU << 15) & 0xefc60000UL;
   mNumberU ^= (mNumberU >> 18);
   return (((C_FLOAT64) mNumberU) + 0.5) * (1.0 / 4294967296.0);
   /* divided by 2^32 */
 }
C_INT32 Cmt19937::getRandomS () virtual
Get a random number in 0 <= n <= (Modulus & 0x7ffffff)
Returns
C_INT32 random
Reimplemented from CRandom.
Definition at line 174 of file Cmt19937.cpp.
References mLeft, mNext, CRandom::mNumberU, and next_state().
 {
   if (--mLeft == 0)
     next_state();
   mNumberU = *mNext++;
   /* Tempering */
   mNumberU ^= (mNumberU >> 11);
   mNumberU ^= (mNumberU << 7) & 0x9d2c5680UL;
   mNumberU ^= (mNumberU << 15) & 0xefc60000UL;
   mNumberU ^= (mNumberU >> 18);
   return mNumberU >> 1;
 }
unsigned C_INT32 Cmt19937::getRandomU () virtual
Get a random number in 0 <= n <= Modulus
Returns
unsigned C_INT32 random
Reimplemented from CRandom.
Definition at line 158 of file Cmt19937.cpp.
References mLeft, mNext, CRandom::mNumberU, and next_state().
Referenced by genrand_res53(), Cmt19937HR::getRandomCC(), Cmt19937HR::getRandomCO(), and Cmt19937HR::getRandomOO().
 {
   if (--mLeft == 0)
     next_state();
   mNumberU = *mNext++;
   /* Tempering */
   mNumberU ^= (mNumberU >> 11);
   mNumberU ^= (mNumberU << 7) & 0x9d2c5680UL;
   mNumberU ^= (mNumberU << 15) & 0xefc60000UL;
   mNumberU ^= (mNumberU >> 18);
   return mNumberU;
 }
void Cmt19937::init_by_array (unsigned C_INT32 init_key[], C_INT32 key_length)
Definition at line 106 of file Cmt19937.cpp.
References Cmt19937_N, initialize(), mLeft, and mState.
 {
   int i, j, k;
   initialize(19650218UL);
   i = 1;
   j = 0;
   k = (Cmt19937_N > key_length ? Cmt19937_N : key_length);
   for (; k; k--)
     {
       mState[i] = (mState[i] ^ ((mState[i - 1] ^ (mState[i - 1] >> 30)) * 1664525UL))
                   + init_key[j] + j; /* non linear */
       mState[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
       i++;
       j++;
       if (i >= Cmt19937_N)
       {mState[0] = mState[Cmt19937_N - 1]; i = 1;}
       if (j >= key_length)
         j = 0;
     }
   for (k = Cmt19937_N - 1; k; k--)
     {
       mState[i] = (mState[i] ^ ((mState[i - 1] ^ (mState[i - 1] >> 30)) * 1566083941UL))
                   - i; /* non linear */
       mState[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
       i++;
       if (i >= Cmt19937_N)
       {mState[0] = mState[Cmt19937_N - 1]; i = 1;}
     }
   mState[0] = 0x80000000UL; /* MSB is 1; assuring non-zero initial array */
   mLeft = 1;
 }
void Cmt19937::initialize (unsigned C_INT32 seed = CRandom::getSystemSeed()) virtual
Initialize or reinitialize the random number generator with the given seed.
Parameters
unsigned C_INT32 seed (default system seed)
Reimplemented from CRandom.
Definition at line 87 of file Cmt19937.cpp.
References Cmt19937_N, mLeft, and mState.
Referenced by Cmt19937(), and init_by_array().
 {
   int j;
   mState[0] = seed & 0xffffffffUL;
   for (j = 1; j < Cmt19937_N; j++)
     {
       mState[j] = (1812433253UL * (mState[j - 1] ^ (mState[j - 1] >> 30)) + j);
       /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
       /* In the previous versions, MSBs of the seed affect   */
       /* only MSBs of the array mState[].                        */
       /* 2002/01/09 modified by Makoto Matsumoto             */
       mState[j] &= 0xffffffffUL;  /* for >32 bit machines */
     }
   mLeft = 1;
 }
void Cmt19937::next_state () protected
Definition at line 140 of file Cmt19937.cpp.
References C_INT32, Cmt19937_M, Cmt19937_N, Cmt19937_TWIST, mLeft, mNext, and mState.
Referenced by getRandomCC(), getRandomCO(), getRandomOO(), getRandomS(), and getRandomU().
 {
   unsigned C_INT32 *p = mState;
   int j;
   mLeft = Cmt19937_N;
   mNext = mState;
   for (j = Cmt19937_N - Cmt19937_M + 1; --j; p++)
     *p = p[Cmt19937_M] ^ Cmt19937_TWIST(p[0], p[1]);
   for (j = Cmt19937_M; --j; p++)
     *p = p[Cmt19937_M - Cmt19937_N] ^ Cmt19937_TWIST(p[0], p[1]);
   *p = p[Cmt19937_M - Cmt19937_N] ^ Cmt19937_TWIST(p[0], mState[0]);
 }
Friends And Related Function Documentation
CRandom* CRandom::createGenerator (CRandom::Type type, unsigned C_INT32 seed) friend
Member Data Documentation
C_INT Cmt19937::mLeft private
Definition at line 76 of file Cmt19937.h.
Referenced by getRandomCC(), getRandomCO(), getRandomOO(), getRandomS(), getRandomU(), init_by_array(), initialize(), and next_state().
unsigned C_INT32* Cmt19937::mNext private
Definition at line 78 of file Cmt19937.h.
Referenced by getRandomCC(), getRandomCO(), getRandomOO(), getRandomS(), getRandomU(), and next_state().
unsigned C_INT32 Cmt19937::mState[624] private
Definition at line 74 of file Cmt19937.h.
Referenced by init_by_array(), initialize(), and next_state().
The documentation for this class was generated from the following files:
Cmt19937.h
Cmt19937.cpp