COPASI API: CMathEvent::CAssignment Class Reference
CMathEvent::CAssignment Class Reference
Public Member Functions
CAssignment (const CCopasiContainer *pParent=NULL)
CAssignment (const CAssignment &src, const CCopasiContainer *pParent=NULL)
bool compile (const CEventAssignment *pAssignment, std::vector< CCopasiContainer * > listOfContainer)
~CAssignment ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
CExpression mExpression
C_FLOAT64 * mpTarget
Friends
class CMathEvent
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 282 of file CMathEvent.h.
Constructor & Destructor Documentation
CMathEvent::CAssignment::CAssignment (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 1006 of file CMathEvent.cpp.
                                                                    :
   CCopasiContainer("MathEventAssignment", pParent),
   mpTarget(NULL),
   mExpression("Expression", this)
 {}
CMathEvent::CAssignment::CAssignment (const CAssignment & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CAssignment & src
"const CCopasiContainer * pParent (default: NULL)
Definition at line 1012 of file CMathEvent.cpp.
                                                                        :
   CCopasiContainer(src, pParent),
   mpTarget(src.mpTarget),
   mExpression(src.mExpression, this)
 {}
CMathEvent::CAssignment::~CAssignment ()
Destructor
Definition at line 1019 of file CMathEvent.cpp.
 {}
Member Function Documentation
bool CMathEvent::CAssignment::compile (const CEventAssignment * pAssignment, std::vector< CCopasiContainer * > listOfContainer)
Compile the root finder
Parameters
const CEventAssignment * pEvent
std::vector< CCopasiContainer * > listOfContainer
Definition at line 1022 of file CMathEvent.cpp.
References C_FLOAT64, CEventAssignment::getExpression(), CEventAssignment::getTargetObject(), CCopasiObject::getValuePointer(), and CCopasiObject::setDirectDependencies().
Referenced by CMathEvent::compile().
 {
   if (pAssignment == NULL)
     return false;
   bool success = true;
   mpTarget = NULL;
   if (pAssignment->getTargetObject() != NULL)
     {
       mpTarget = (C_FLOAT64 *) pAssignment->getTargetObject()->getValuePointer();
     }
   if (mpTarget == NULL)
     success = false;
   success &= mExpression.setInfix(pAssignment->getExpression());
   success &= mExpression.compile(listOfContainer);
   setDirectDependencies(mExpression.getDirectDependencies());
   return success;
 }
Friends And Related Function Documentation
friend class CMathEvent friend
Definition at line 284 of file CMathEvent.h.
Member Data Documentation
CExpression CMathEvent::CAssignment::mExpression private
Expression to calculate the new value.
Definition at line 325 of file CMathEvent.h.
C_FLOAT64* CMathEvent::CAssignment::mpTarget private
Pointer to the value to be modified by the assignment
Definition at line 320 of file CMathEvent.h.
The documentation for this class was generated from the following files:
CMathEvent.h
CMathEvent.cpp