COPASI API: CNormalFraction Class Reference
CNormalFraction Class Reference
#include <CNormalFraction.h>
Public Member Functions
bool cancel ()
bool checkDenominatorOne () const
bool checkForFractions () const
bool checkIsOne () const
bool checkIsZero () const
bool checkNumeratorOne () const
CNormalFraction ()
CNormalFraction (const CNormalFraction &src)
virtual CNormalBase * copy () const
bool expand (const CNormalLcm &lcm)
const CNormalLcm * findLcm () const
CNormalSum & getDenominator ()
const CNormalSum & getDenominator () const
CNormalSum & getNumerator ()
const CNormalSum & getNumerator () const
bool multiply (const C_FLOAT64 &number)
bool multiply (const CNormalItemPower &itemPower)
const CNormalSum * multiply (CNormalLcm lcm)
bool operator< (const CNormalFraction &src) const
CNormalFraction & operator= (const CNormalFraction &src)
bool operator== (const CNormalFraction &rhs) const
bool setDenominator (const CNormalSum &denominator)
bool setDenominatorOne ()
bool setNumerator (const CNormalSum &numerator)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalFraction ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Static Public Member Functions
static CNormalFraction * createUnitFraction ()
Private Attributes
CNormalSum * mpDenominator
CNormalSum * mpNumerator
Detailed Description
Definition at line 32 of file CNormalFraction.h.
Constructor & Destructor Documentation
CNormalFraction::CNormalFraction ()
Default constructor
Definition at line 47 of file CNormalFraction.cpp.
Referenced by copy(), and createUnitFraction().
 : CNormalBase(), mpNumerator(new CNormalSum()), mpDenominator(new CNormalSum()) {}
CNormalFraction::CNormalFraction (const CNormalFraction & src)
Copy contructor
Definition at line 52 of file CNormalFraction.cpp.
                                                           : CNormalBase(src),
     mpNumerator(new CNormalSum(*src.mpNumerator)),
     mpDenominator(new CNormalSum(*src.mpDenominator)) {}
CNormalFraction::~CNormalFraction () virtual
Dtor.
Definition at line 70 of file CNormalFraction.cpp.
References mpDenominator, and mpNumerator.
 {
   if (mpNumerator != NULL) delete mpNumerator;
   if (mpDenominator != NULL) delete mpDenominator;
 }
Member Function Documentation
bool CNormalFraction::cancel ()
Cancel common items of mpNumerator and mpDenominator.
Returns
true.
Definition at line 211 of file CNormalFraction.cpp.
References C_FLOAT64, CNormalSum::checkFactor(), checkForFractions(), CNormalSum::divide(), CNormalSum::getFractions(), CNormalSum::getProducts(), mpDenominator, mpNumerator, CNormalSum::multiply(), setDenominatorOne(), and setNumerator().
Referenced by createFraction(), and simplify().
 {
   if (mpNumerator->getProducts().size() != 0 || mpNumerator->getFractions().size() != 0 || mpDenominator->getProducts().size() != 0 || mpDenominator->getFractions().size() != 0)
     {
       if (*mpDenominator == *mpNumerator)
         {
           setDenominatorOne();
           setNumerator(*mpDenominator);
           return true;
         }
       if (mpDenominator->getProducts().size() != 0)
         {
           C_FLOAT64 factor = (*mpDenominator->getProducts().begin())->getFactor();
           if (fabs(factor) < 1.0E-100)
             return false;
           else
             {
               mpNumerator->multiply(1.0 / factor);  //factor != 0 as checked earlier
               mpDenominator->multiply(1.0 / factor);
             }
         }
       if (checkForFractions() == false)
         {
           if (mpDenominator->getProducts().size() != 0 && (*mpDenominator->getProducts().begin())->getItemPowers().size() != 0)
             {
               std::set<CNormalItemPower*, compareItemPowers >::const_iterator it = (*mpDenominator->getProducts().begin())->getItemPowers().begin();
               std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = (*mpDenominator->getProducts().begin())->getItemPowers().end();
               std::vector<CNormalItemPower*> tmpV;
               while (it != itEnd)
                 {//runs through all item powers in the first product of the denominator
                   C_FLOAT64 exp = mpNumerator->checkFactor(**it);
                   if (fabs(exp) >= 1.0E-100)
                     {
                       exp = mpDenominator->checkFactor(**it) < exp ? mpDenominator->checkFactor(**it) : exp;
                       if (fabs(exp) >= 1.0E-100)
{
                           CNormalItemPower* itemPower = new CNormalItemPower((*it)->getItem(), exp);
                           tmpV.push_back(itemPower);
                         }
                     }
                   ++it;
                 }
               std::vector<CNormalItemPower*>::iterator it2 = tmpV.begin();
               std::vector<CNormalItemPower*>::iterator itEnd2 = tmpV.end();
               while (it2 != itEnd2)
                 {
                   mpNumerator->divide(**it2);
                   mpDenominator->divide(**it2);
                   delete *it2;
                   ++it2;
                 }
             }
         }
     }
   return true;
 }
bool CNormalFraction::checkDenominatorOne () const
Check if the denominator of this fraction equals 1.
Returns
bool
Definition at line 124 of file CNormalFraction.cpp.
References CNormalSum::checkIsOne(), and mpDenominator.
Referenced by convertToCEvaluationNode(), CNormalProduct::getDenominator(), is_mass_action(), normalize_variable_names(), CNormalGeneralPower::toString(), and toString().
 {
   return this->mpDenominator->checkIsOne();
 }
bool CNormalFraction::checkForFractions () const
Check if this fraction contains further fractions.
Returns
bool.
Definition at line 184 of file CNormalFraction.cpp.
References CNormalSum::getFractions(), mpDenominator, and mpNumerator.
Referenced by cancel().
 {
   if (mpNumerator->getFractions().size() + mpDenominator->getFractions().size() == 0)
     return false;
   return true;
 }
bool CNormalFraction::checkIsOne () const
Definition at line 518 of file CNormalFraction.cpp.
References mpDenominator, and mpNumerator.
Referenced by CNormalGeneralPower::checkIsOne(), convertToCEvaluationNode(), and CNormalSum::simplify().
 {
   // the fraction is one if numerator and denominator are equal
   return ((*mpNumerator) == (*mpDenominator));
 }
bool CNormalFraction::checkIsZero () const
Definition at line 524 of file CNormalFraction.cpp.
References CNormalSum::checkIsZero(), and mpNumerator.
Referenced by CNormalGeneralPower::checkIsOne().
 {
   // the fraction is 0.0 if the numerator is 0.0
   return this->mpNumerator->checkIsZero();
 }
bool CNormalFraction::checkNumeratorOne () const
Check if the numerator of this fraction equals 1.
Returns
bool
Check if the denominator of this fraction equals 1.
Returns
bool
Definition at line 115 of file CNormalFraction.cpp.
References CNormalSum::checkIsOne(), and mpNumerator.
 {
   return this->mpNumerator->checkIsOne();
 }
CNormalBase * CNormalFraction::copy () const virtual
Implements CNormalBase.
Definition at line 434 of file CNormalFraction.cpp.
References CNormalFraction().
 {
   return new CNormalFraction(*this);
 }
CNormalFraction * CNormalFraction::createUnitFraction () static
Returns a fraction that is 1/1. It creates a new fraction and sets the numerator and the denominator to a unit sum.
Definition at line 530 of file CNormalFraction.cpp.
References CNormalFraction(), CNormalSum::createUnitSum(), mpDenominator, and mpNumerator.
Referenced by CNormalGeneralPower::createUnitGeneralPower(), CNormalGeneralPower::multiply(), CNormalSum::simplify(), and test_simplify::test_simplify_1().
 {
   CNormalFraction* pFraction = new CNormalFraction();
   delete pFraction->mpNumerator;
   delete pFraction->mpDenominator;
   pFraction->mpNumerator = CNormalSum::createUnitSum();
   pFraction->mpDenominator = CNormalSum::createUnitSum();
   return pFraction;
 }
bool CNormalFraction::expand (const CNormalLcm & lcm)
Expand this fraction by a lcm.
Returns
true.
Definition at line 196 of file CNormalFraction.cpp.
References CNormalSum::getSize(), mpDenominator, mpNumerator, and CNormalSum::multiply().
Referenced by simplify().
 {
   mpNumerator->multiply(lcm);
   mpDenominator->multiply(lcm);
   if (mpDenominator->getSize() == 0)
     return false;
   return true;
 }
const CNormalLcm * CNormalFraction::findLcm () const
Find lcm of denominators of respective fractions contained in this fraction.
Returns
pointer to lcm.
Definition at line 329 of file CNormalFraction.cpp.
References CNormalLcm::add(), CNormalSum::getFractions(), mpDenominator, and mpNumerator.
Referenced by simplify().
 {
   CNormalLcm* lcm = new CNormalLcm();
   std::set<CNormalFraction*>::const_iterator it;
   std::set<CNormalFraction*>::const_iterator itEnd = mpNumerator->getFractions().end();
   for (it = mpNumerator->getFractions().begin(); it != itEnd; ++it)
     {
       lcm->add((*it)->getDenominator());
     }
   std::set<CNormalFraction*>::const_iterator it2;
   std::set<CNormalFraction*>::const_iterator it2End = mpDenominator->getFractions().end();
   for (it2 = mpDenominator->getFractions().begin(); it2 != it2End; ++it2)
     {
       lcm->add((*it2)->getDenominator());
     }
   return lcm;
 }
CNormalSum & CNormalFraction::getDenominator ()
Retrieve the denominator of this fraction.
Returns
mpDenominator.
Definition at line 157 of file CNormalFraction.cpp.
References mpDenominator.
Referenced by convertToCEvaluationNode(), CNormalGeneralPower::multiply(), normalize_variable_names(), CNormalSum::simplify(), test_simplify::test_simplify_1(), and CNormalGeneralPower::toString().
 {
   return *mpDenominator;
 }
const CNormalSum & CNormalFraction::getDenominator () const
Retrieve the denominator of this fraction.
Returns
mpDenominator.
Definition at line 175 of file CNormalFraction.cpp.
References mpDenominator.
 {
   return *mpDenominator;
 }
CNormalSum & CNormalFraction::getNumerator ()
Retrieve the numerator of this fraction.
Returns
mpNumerator.
Definition at line 148 of file CNormalFraction.cpp.
References mpNumerator.
Referenced by CNormalSum::add(), convertToCEvaluationNode(), is_mass_action(), CNormalGeneralPower::multiply(), normalize_variable_names(), test_simplify::test_simplify_1(), and CNormalGeneralPower::toString().
 {
   return *mpNumerator;
 }
const CNormalSum & CNormalFraction::getNumerator () const
Retrieve the numerator of this fraction.
Returns
mpNumerator.
Definition at line 166 of file CNormalFraction.cpp.
References mpNumerator.
 {
   return *mpNumerator;
 }
bool CNormalFraction::multiply (const C_FLOAT64 & number)
Multiply this fraction with a number.
Returns
true.
Definition at line 282 of file CNormalFraction.cpp.
References CNormalSum::getSize(), mpNumerator, CNormalSum::multiply(), and setDenominatorOne().
 {
   mpNumerator->multiply(number);
   if (mpNumerator->getSize() == 0)
     setDenominatorOne();
   return true;
 }
bool CNormalFraction::multiply (const CNormalItemPower & itemPower)
Multiply a fraction with an itempower.
Returns
true.
Definition at line 296 of file CNormalFraction.cpp.
References C_FLOAT64, CNormalSum::checkFactor(), CNormalSum::divide(), CNormalItemPower::getExp(), CNormalItemPower::getItem(), mpDenominator, mpNumerator, and CNormalSum::multiply().
 {
   C_FLOAT64 exp = mpDenominator->checkFactor(itemPower);
   C_FLOAT64 tmpExp;
   if (fabs(exp) >= 1.0E-100)
     {
       CNormalItemPower* pTmp1 = new CNormalItemPower(itemPower.getItem(), exp);
       mpDenominator->divide(*pTmp1);
       delete pTmp1;
       if ((tmpExp = fabs(itemPower.getExp() - exp)) >= 1.0E-100)
         {
           // :TODO: Memory leak?
           CNormalItemPower * pTmp2 =
             new CNormalItemPower(itemPower.getItem(), tmpExp);
           mpNumerator->multiply(*pTmp2);
           delete pTmp2;
           return true;
         }
       return true;
     }
   else
     mpNumerator->multiply(itemPower);
   return true;
 }
const CNormalSum * CNormalFraction::multiply (CNormalLcm lcm)
Multiply this fraction by a lcm.
Returns
CNormalSum*, pointer to result of multiplication ie. a normal sum. This fraction is useless now.
Definition at line 357 of file CNormalFraction.cpp.
References CNormalSum::getFractions(), mpDenominator, mpNumerator, CNormalSum::multiply(), and CNormalLcm::remove().
 {
   if (mpDenominator->getFractions().size() != 0)
     {
       return NULL;
     }
   if (lcm.remove(*mpDenominator) == false)
     {
       return NULL;
     }
   mpNumerator->multiply(lcm);
   CNormalSum * sum = new CNormalSum(*mpNumerator);
   return sum;
 }
bool CNormalFraction::operator< (const CNormalFraction & src) const
smaller operator
Definition at line 439 of file CNormalFraction.cpp.
References mpDenominator, and mpNumerator.
 {
   bool result = false;
   if ((*this->mpNumerator) < (*src.mpNumerator))
     {
       result = true;
     }
   else if ((*this->mpNumerator) == (*src.mpNumerator))
     {
       if ((*this->mpDenominator) < (*src.mpDenominator))
         {
           result = true;
         }
     }
   return result;
 }
CNormalFraction & CNormalFraction::operator= (const CNormalFraction & src)
Assignment operator
Definition at line 59 of file CNormalFraction.cpp.
References mpDenominator, and mpNumerator.
 {
   if (this->mpNumerator != NULL) delete this->mpNumerator;
   if (this->mpDenominator != NULL) delete this->mpDenominator;
   this->mpNumerator = new CNormalSum(*src.mpNumerator);
   this->mpDenominator = new CNormalSum(*src.mpDenominator);
   return *this;
 }
bool CNormalFraction::operator== (const CNormalFraction & rhs) const
Definition at line 404 of file CNormalFraction.cpp.
References mpDenominator, and mpNumerator.
 {
   if ((*mpNumerator == *rhs.mpNumerator) && (*mpDenominator == *rhs.mpDenominator))
     return true;
   else
     return false;
 }
bool CNormalFraction::setDenominator (const CNormalSum & denominator)
Set denominator of this fraction.
Returns
true.
Definition at line 96 of file CNormalFraction.cpp.
References CNormalSum::getSize(), and mpDenominator.
Referenced by createFraction(), CNormalProduct::getDenominator(), setDenominatorOne(), CNormalProduct::setDenominatorsOne(), and CNormalSum::simplify().
 {
   if (mpDenominator != NULL)
     {
       delete mpDenominator;
     }
   mpDenominator = new CNormalSum(denominator);
   if (mpDenominator->getSize() == 0)
     return false;
   return true;
 }
bool CNormalFraction::setDenominatorOne ()
Set the denominator of this fraction equal 1.
Returns
true.
Definition at line 133 of file CNormalFraction.cpp.
References CNormalSum::add(), and setDenominator().
Referenced by cancel(), and multiply().
 {
   CNormalProduct* product = new CNormalProduct();
   CNormalSum* sum = new CNormalSum();
   sum->add(*product);
   delete product;
   setDenominator(*sum);
   delete sum;
   return true;
 }
bool CNormalFraction::setNumerator (const CNormalSum & numerator)
Set numerator of this fraction
Returns
true.
Definition at line 81 of file CNormalFraction.cpp.
References mpNumerator.
Referenced by cancel(), createFraction(), CNormalProduct::getDenominator(), CNormalGeneralPower::multiply(), and CNormalSum::simplify().
 {
   if (mpNumerator != NULL)
     {
       delete mpNumerator;
     }
   mpNumerator = new CNormalSum(numerator);
   return true;
 }
bool CNormalFraction::simplify () virtual
Check if numerator and denominator contain fractions, find lcm of respective denominators, expand this fraction by lcm and cancel.
Returns
true
Implements CNormalBase.
Definition at line 379 of file CNormalFraction.cpp.
References cancel(), expand(), findLcm(), CNormalSum::getFractions(), mpDenominator, mpNumerator, and CNormalSum::simplify().
Referenced by CNormalTranslation::normAndSimplify(), CNormalLogicalItem::simplify(), CNormalGeneralPower::simplify(), CNormalChoice::simplify(), CNormalFunction::simplify(), CNormalSum::simplify(), and test_simplify::test_simplify_1().
 {
   bool result = true;
   result = this->mpNumerator->simplify();
   if (result == true)
     {
       result = this->mpDenominator->simplify();
     }
   if (result == true)
     {
       if (mpNumerator->getFractions().size() + mpDenominator->getFractions().size() > 0)
         {
           // TODO  the following code does not work if there are fractions left.
           const CNormalLcm* lcm = findLcm();
           assert(expand(*lcm) == true);
           delete lcm;
         }
     }
   cancel();
   return result;
 }
std::string CNormalFraction::toString () const virtual
Implements CNormalBase.
Definition at line 418 of file CNormalFraction.cpp.
References checkDenominatorOne(), mpDenominator, and mpNumerator.
Referenced by CNormalTranslation::elementaryEliminationDivide(), CNormalTranslation::elementaryEliminationMinus(), CNormalTranslation::elementaryEliminationModulus(), CNormalTranslation::matchPowerBases(), CNormalTranslation::matchSummands(), CNormalTranslation::normAndSimplifyReptdly(), operator<<(), test_biomodels217_expression::test_term_num1(), and CNormalChoice::toString().
 {
   std::ostringstream os;
   if (this->checkDenominatorOne() == true)
     {
       os << *this->mpNumerator;
     }
   else
     {
       os << "(" << *this->mpNumerator << ")/(" << *this->mpDenominator << ")";
     }
   return os.str();
 }
Member Data Documentation
CNormalSum* CNormalFraction::mpDenominator private
Definition at line 39 of file CNormalFraction.h.
Referenced by cancel(), checkDenominatorOne(), checkForFractions(), checkIsOne(), createUnitFraction(), expand(), findLcm(), getDenominator(), multiply(), operator<(), operator=(), operator==(), setDenominator(), simplify(), toString(), and ~CNormalFraction().
CNormalSum* CNormalFraction::mpNumerator private
Enumeration of members
Definition at line 38 of file CNormalFraction.h.
Referenced by cancel(), checkForFractions(), checkIsOne(), checkIsZero(), checkNumeratorOne(), createUnitFraction(), expand(), findLcm(), getNumerator(), multiply(), operator<(), operator=(), operator==(), setNumerator(), simplify(), toString(), and ~CNormalFraction().
The documentation for this class was generated from the following files:
CNormalFraction.h
CNormalFraction.cpp