COPASI API: CCopasiXMLParser::ReportElement Class Reference
CCopasiXMLParser::ReportElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ReportElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ReportElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Report = 0, Comment, Header, Body,
Footer, Table
}
Private Attributes
BodyElement * mpBodyElement
FooterElement * mpFooterElement
HeaderElement * mpHeaderElement
TableElement * mpTableElement
bool otherFound
bool tableFound
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2756 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ReportElement::Element private
Report
Enumerator
Report
Comment
Header
Body
Footer
Table
Definition at line 2763 of file CCopasiXMLParser.h.
     {
       Report = 0,
       Comment,
       Header,
       Body,
       Footer,
       Table
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ReportElement::ReportElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 9509 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpHeaderElement(NULL),
   mpBodyElement(NULL),
   mpFooterElement(NULL),
   mpTableElement(NULL),
   tableFound(false),
   otherFound(false)
 {}
CCopasiXMLParser::ReportElement::~ReportElement () virtual
Destructor
Definition at line 9520 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpHeaderElement);
   pdelete(mpBodyElement);
   pdelete(mpFooterElement);
   pdelete(mpTableElement);
 }
Member Function Documentation
void CCopasiXMLParser::ReportElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 9690 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pReport, CReportDefinition::setComment(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "Report") &&
       (mCurrentElement == Comment ||
        mCurrentElement == Header ||
        mCurrentElement == Body))
     mCurrentElement = Report;
   switch (mCurrentElement)
     {
       case Report:
         if (strcmp(pszName, "Report"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Report", mParser.getCurrentLineNumber());
         mCurrentElement = START_ELEMENT;
         mParser.popElementHandler();
         // Tell the parent element we are done.
         mParser.onEndElement(pszName);
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         // check parameter type CCopasiStaticString
         mCommon.pReport->setComment(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case Header:
         if (strcmp(pszName, "Header"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Header", mParser.getCurrentLineNumber());
         break;
       case Body:
         if (strcmp(pszName, "Body"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Body", mParser.getCurrentLineNumber());
         break;
       case Footer:
         if (strcmp(pszName, "Footer"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Footer", mParser.getCurrentLineNumber());
         mCurrentElement = Report;
         break;
       case Table:
         if (strcmp(pszName, "Table"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Table", mParser.getCurrentLineNumber());
         mCurrentElement = Report;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
 }
void CCopasiXMLParser::ReportElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 9528 of file CCopasiXMLParser.cpp.
References CCopasiVectorN< CType >::add(), C_INVALID_INDEX, CCopasiMessage::EXCEPTION, fatalError, CCopasiVectorN< CType >::getIndex(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pReport, SCopasiXMLParserCommon::pReportList, CReportDefinition::setIsTable(), CCopasiObject::setObjectName(), CReportDefinition::setPrecision(), CReportDefinition::setSeparator(), CReportDefinition::setTaskType(), strToUnsignedInt(), toEnum(), UNKNOWN_ELEMENT, CCopasiTask::unset, and CCopasiTask::XMLType.
 {
   const char * Key;
   const char * Name;
   const char * Separator;
   const char * Precision;
   CCopasiTask::Type type;
   mCurrentElement++; /* We should always be on the next element */
   mpCurrentHandler = NULL;
   switch (mCurrentElement)
     {
       case Report:
         if (strcmp(pszName, "Report"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Report", mParser.getCurrentLineNumber());
         // We have not found anything yet.
         tableFound = false;
         otherFound = false;
         Key = mParser.getAttributeValue("key", papszAttrs);
         Name = mParser.getAttributeValue("name", papszAttrs);
         type = toEnum(mParser.getAttributeValue("taskType", papszAttrs),
                       CCopasiTask::XMLType, CCopasiTask::unset);
         Separator = mParser.getAttributeValue("separator", papszAttrs, "\t");
         Precision = mParser.getAttributeValue("precision", papszAttrs, "6");
         // create a new report
         mCommon.pReport = new CReportDefinition();
         mCommon.pReport->setTaskType(type);
         mCommon.pReport->setSeparator(CCopasiReportSeparator(Separator));
         mCommon.pReport->setPrecision(strToUnsignedInt(Precision));
         {
           // We need to make sure that the name is unique.
           std::string ValidName(Name);
           size_t Index = 1;
           while (mCommon.pReportList->getIndex(ValidName) != C_INVALID_INDEX)
             {
               std::ostringstream ValidNameStream;
               ValidNameStream << Name << " " << Index++;
               ValidName = ValidNameStream.str();
             }
           mCommon.pReport->setObjectName(ValidName);
         }
         /* We have a new report and add it to the list */
         mCommon.pReportList->add(mCommon.pReport, true);
         addFix(Key, mCommon.pReport);
         return;
         break;
       case Comment:
         if (!strcmp(pszName, "Comment"))
           {
             /* Push the Comment element handler on the stack and call it. */
             mpCurrentHandler = &mParser.mCommentElement;
           }
         break;
       case Header:
         if (!strcmp(pszName, "Header"))
           {
             /* If we do not have a Header element handler we create one. */
             if (tableFound) fatalError();
             otherFound = true;
             mCommon.pReport->setIsTable(false);
             if (!mpHeaderElement)
               mpHeaderElement = new HeaderElement(mParser, mCommon);
             /* Push the Header element handler on the stack and call it. */
             mpCurrentHandler = mpHeaderElement;
           }
         break;
       case Body:
         if (!strcmp(pszName, "Body"))
           {
             /* If we do not have a Body element handler we create one. */
             if (tableFound) fatalError();
             otherFound = true;
             mCommon.pReport->setIsTable(false);
             if (!mpBodyElement)
               mpBodyElement = new BodyElement(mParser, mCommon);
             /* Push the Body element handler on the stack and call it. */
             mpCurrentHandler = mpBodyElement;
           }
         break;
       case Footer:
         if (!strcmp(pszName, "Footer"))
           {
             /* If we do not have a Body element handler we create one. */
             if (tableFound) fatalError();
             otherFound = true;
             mCommon.pReport->setIsTable(false);
             if (!mpFooterElement)
               mpFooterElement = new FooterElement(mParser, mCommon);
             /* Push the Body element handler on the stack and call it. */
             mpCurrentHandler = mpFooterElement;
           }
         break;
       case Table:
         if (!strcmp(pszName, "Table"))
           {
             if (otherFound) fatalError();
             tableFound = true;
             mCommon.pReport->setIsTable(true);
             if (!mpTableElement)
               {
                 mpTableElement = new TableElement(mParser, mCommon);
               }
             mpCurrentHandler = mpTableElement;
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     {
       mParser.pushElementHandler(mpCurrentHandler);
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
BodyElement* CCopasiXMLParser::ReportElement::mpBodyElement private
Definition at line 2774 of file CCopasiXMLParser.h.
FooterElement* CCopasiXMLParser::ReportElement::mpFooterElement private
Definition at line 2775 of file CCopasiXMLParser.h.
HeaderElement* CCopasiXMLParser::ReportElement::mpHeaderElement private
Definition at line 2773 of file CCopasiXMLParser.h.
TableElement* CCopasiXMLParser::ReportElement::mpTableElement private
Definition at line 2776 of file CCopasiXMLParser.h.
bool CCopasiXMLParser::ReportElement::otherFound private
Definition at line 2779 of file CCopasiXMLParser.h.
bool CCopasiXMLParser::ReportElement::tableFound private
Definition at line 2778 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp