COPASI API: CQBrowserPaneDM::CNode Class Reference
CQBrowserPaneDM::CNode Class Reference
#include <CQBrowserPaneDM.h>
Public Member Functions
CNode (const size_t &id, const std::string &key, const QString &displayRole, CNode *pParent)
const QString & getDisplayRole () const
const size_t & getId () const
const std::string & getKey () const
int getRow () const
QString getSortRole () const
void setDisplayRole (const QString &displayRole)
void setKey (const std::string &key)
~CNode ()
Public Member Functions inherited from CCopasiNode< SData >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Private Member Functions
CNode ()
Friends
std::ostream & operator<< (std::ostream &os, const CNode &d)
Additional Inherited Members
Public Types inherited from CCopasiNode< SData >
typedef SData Data
Protected Member Functions inherited from CCopasiNode< SData >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CCopasiNode< SData >
Data mData
Detailed Description
Definition at line 41 of file CQBrowserPaneDM.h.
Constructor & Destructor Documentation
CQBrowserPaneDM::CNode::CNode () private
Definition at line 735 of file CQBrowserPaneDM.cpp.
                            :
   CCopasiNode< CQBrowserPaneDM::SData >()
 {}
CQBrowserPaneDM::CNode::CNode (const size_t & id, const std::string & key, const QString & displayRole, CNode * pParent)
Definition at line 739 of file CQBrowserPaneDM.cpp.
References CCopasiNode< _Data >::addChild(), and CCopasiNode< SData >::mData.
                                               :
   CCopasiNode< CQBrowserPaneDM::SData >(pParent)
 {
   mData.mId = id;
   mData.mKey = key;
   mData.mDisplayRole = displayRole;
   if (pParent != NULL)
     {
       pParent->addChild(this);
     }
 }
CQBrowserPaneDM::CNode::~CNode ()
Definition at line 755 of file CQBrowserPaneDM.cpp.
 {}
Member Function Documentation
const QString & CQBrowserPaneDM::CNode::getDisplayRole () const
Definition at line 768 of file CQBrowserPaneDM.cpp.
Referenced by CQBrowserPaneDM::data(), CQBrowserPaneDM::load(), and CQBrowserPaneDM::rename().
 {
   return mData.mDisplayRole;
 }
const size_t & CQBrowserPaneDM::CNode::getId () const
Definition at line 758 of file CQBrowserPaneDM.cpp.
Referenced by CQBrowserPaneDM::data(), and CQBrowserPaneDM::getIdFromIndex().
 {
   return mData.mId;
 }
const std::string & CQBrowserPaneDM::CNode::getKey () const
Definition at line 788 of file CQBrowserPaneDM.cpp.
Referenced by CQBrowserPaneDM::getKeyFromIndex().
 {
   return mData.mKey;
 }
int CQBrowserPaneDM::CNode::getRow () const
Definition at line 793 of file CQBrowserPaneDM.cpp.
References CCopasiNode< _Data >::getChild(), and CCopasiNode< _Data >::getSibling().
Referenced by CQBrowserPaneDM::index(), CQBrowserPaneDM::parent(), and CQBrowserPaneDM::remove().
 {
   int count = 0;
   const CCopasiNode< CQBrowserPaneDM::SData > * pParent = getParent();
   if (pParent == NULL)
     {
       return 0;
     }
   const CCopasiNode< CQBrowserPaneDM::SData > * pChild = pParent->getChild();
   while (pChild != NULL && pChild != this)
     {
       count++;
       pChild = pChild->getSibling();
     }
   return (pChild != NULL) ? count : -1;
 }
QString CQBrowserPaneDM::CNode::getSortRole () const
Definition at line 773 of file CQBrowserPaneDM.cpp.
References C_INVALID_INDEX.
Referenced by CQBrowserPaneDM::data().
 {
   if (mData.mId == C_INVALID_INDEX)
     {
       return mData.mDisplayRole;
     }
   return QString::number(mData.mId);
 }
void CQBrowserPaneDM::CNode::setDisplayRole (const QString & displayRole)
Definition at line 763 of file CQBrowserPaneDM.cpp.
Referenced by CQBrowserPaneDM::load(), and CQBrowserPaneDM::rename().
 {
   mData.mDisplayRole = displayRole;
 }
void CQBrowserPaneDM::CNode::setKey (const std::string & key)
Definition at line 783 of file CQBrowserPaneDM.cpp.
Referenced by CQBrowserPaneDM::load().
 {
   mData.mKey = key;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CNode & d) friend
Definition at line 815 of file CQBrowserPaneDM.cpp.
 {
   os << "CQBrowserPaneDM::CNode:" << std::endl;
   //os << "   mChemicalEquation:          " << d.getChemicalEquation() << std::endl;
   //os << "   mChemicalEquationConverted: " << d.getChemicalEquationConverted() << std::endl;
   os << "   mId:          " << n.mData.mId << std::endl;
   os << "   mKey:         " << n.mData.mKey << std::endl;
   os << "   mDisplayRole: " << TO_UTF8(n.mData.mDisplayRole) << std::endl;
   return os;
 }
The documentation for this class was generated from the following files:
CQBrowserPaneDM.h
CQBrowserPaneDM.cpp