COPASI API: CCopasiSpringLayout.cpp File Reference
CCopasiSpringLayout.cpp File Reference
#include <iostream>
#include <map>
#include <layout/CCopasiSpringLayout.h>
#include <layout/CLGlyphs.h>
#include <layout/CLReactionGlyph.h>
#include <layout/CLayout.h>
#include <model/CCompartment.h>
#include <model/CReaction.h>
#include <model/CMetab.h>
#include <randomGenerator/CRandom.h>
Classes
class CompartmentInfo
Functions
void placeTextGlyphs (CLayout *pLayout)
void randomlyPlaceGlyphInCompartmentGlyph (CLGraphicalObject *pGl, const CLGraphicalObject *pContainer, CRandom *pRandom)
void randomlyPlaceGlyphInDimensions (CLGraphicalObject *pGl, const CLDimensions *pContainer, CRandom *pRandom)
Function Documentation
void placeTextGlyphs (CLayout * pLayout)
Definition at line 885 of file CCopasiSpringLayout.cpp.
References CLTextGlyph::getGraphicalObject(), CLayout::getListOfTextGlyphs(), CLGraphicalObject::getX(), CLGraphicalObject::getY(), CLGraphicalObject::setPosition(), and CCopasiVector< T >::size().
Referenced by CCopasiSpringLayout::randomize().
 {
   size_t i;
   for (i = 0; i < pLayout->getListOfTextGlyphs().size(); ++i)
     {
       CLTextGlyph* pTG = pLayout->getListOfTextGlyphs()[i];
       CLGraphicalObject* pGO = pTG->getGraphicalObject();
       if (!pGO)
         continue;
       pTG->setPosition(CLPoint(pGO->getX() + 2, pGO->getY() + 2));
     }
 }
void randomlyPlaceGlyphInCompartmentGlyph (CLGraphicalObject * pGl, const CLGraphicalObject * pContainer, CRandom * pRandom)
Definition at line 869 of file CCopasiSpringLayout.cpp.
References CLGraphicalObject::getDimensions(), CLDimensions::getHeight(), CLGraphicalObject::getPosition(), CRandom::getRandomCC(), CLDimensions::getWidth(), CLPoint::getX(), CLPoint::getY(), and CLGraphicalObject::setPosition().
Referenced by CCopasiSpringLayout::randomize().
 {
   double x = pContainer->getPosition().getX()
              + pRandom->getRandomCC() * (pContainer->getDimensions().getWidth() - pGl->getDimensions().getWidth());
   double y = pContainer->getPosition().getY()
              + pRandom->getRandomCC() * (pContainer->getDimensions().getHeight() - pGl->getDimensions().getHeight());
   pGl->setPosition(CLPoint(x, y));
 }
void randomlyPlaceGlyphInDimensions (CLGraphicalObject * pGl, const CLDimensions * pContainer, CRandom * pRandom)
Definition at line 878 of file CCopasiSpringLayout.cpp.
References CLGraphicalObject::getDimensions(), CLDimensions::getHeight(), CRandom::getRandomCC(), CLDimensions::getWidth(), and CLGraphicalObject::setPosition().
Referenced by CCopasiSpringLayout::randomize().
 {
   double x = pRandom->getRandomCC() * (pContainer->getWidth() - pGl->getDimensions().getWidth());
   double y = pRandom->getRandomCC() * (pContainer->getHeight() - pGl->getDimensions().getHeight());
   pGl->setPosition(CLPoint(x, y));
 }