COPASI API: CCopasiParameterGroup Class Reference
CCopasiParameterGroup Class Reference
#include <CCopasiParameterGroup.h>
Public Types
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Member Functions
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiParameterGroup &o)
bool operator== (const CCopasiParameterGroup &lhs, const CCopasiParameterGroup &rhs)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CCopasiParameterGroup class. This class is used to describe parameters. This class is intended to be used with integration or optimization methods or reactions.
Created for COPASI by Stefan Hoops 2002
Definition at line 34 of file CCopasiParameterGroup.h.
Member Typedef Documentation
typedef parameterGroup::iterator CCopasiParameterGroup::index_iterator
Definition at line 38 of file CCopasiParameterGroup.h.
typedef CCopasiContainer::objectMap::iterator CCopasiParameterGroup::name_iterator
Definition at line 39 of file CCopasiParameterGroup.h.
typedef std::vector< CCopasiParameter * > CCopasiParameterGroup::parameterGroup
Definition at line 37 of file CCopasiParameterGroup.h.
Constructor & Destructor Documentation
CCopasiParameterGroup::CCopasiParameterGroup () protected
Default constructor
CCopasiParameterGroup class. This class is used to describe parameters. This class is intended to be used with integration or optimization methods or reactions.
Created for COPASI by Stefan Hoops 2002
Definition at line 32 of file CCopasiParameterGroup.cpp.
Referenced by addGroup(), addParameter(), CScanProblem::createScanItem(), operator=(), CMIRIAMResources::updateMIRIAMResources(), and CMIRIAMResources::updateMIRIAMResourcesFromFile().
                                             :
   CCopasiParameter("NoName", GROUP)
 {}
CCopasiParameterGroup::CCopasiParameterGroup (const CCopasiParameterGroup & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CCopasiParameterGroup & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 36 of file CCopasiParameterGroup.cpp.
                                      :
   CCopasiParameter(src, pParent)
 {
   *this = src;
 }
CCopasiParameterGroup::CCopasiParameterGroup (const std::string & name, const CCopasiContainer * pParent = NULL, const std::string & objectType = "ParameterGroup")
Specific constructor
Parameters
const string & name
const CCopasiContainer * pParent (default: NULL)
const std::string & objectType (default: "ParameterGroup")
Definition at line 43 of file CCopasiParameterGroup.cpp.
                                  :
   CCopasiParameter(name, CCopasiParameter::GROUP, NULL, pParent, objectType)
 {}
CCopasiParameterGroup::~CCopasiParameterGroup () virtual
Destructor
Definition at line 49 of file CCopasiParameterGroup.cpp.
References clear().
 {
   clear();
 }
Member Function Documentation
bool CCopasiParameterGroup::addGroup (const std::string & name)
Add a subgroup to the group
Parameters
const std::string & name
Returns
bool success
Definition at line 291 of file CCopasiParameterGroup.cpp.
References addParameter(), and CCopasiParameterGroup().
Referenced by CSensProblem::addVariables(), assertGroup(), CSensProblem::CSensProblem(), and CScanProblem::initializeParameter().
 {
   addParameter(new CCopasiParameterGroup(name));
   return true;
 }
bool CCopasiParameterGroup::addParameter (const CCopasiParameter & parameter)
Add a parameter
Parameters
const CCopasiParameter & parameter
Returns
bool success
Definition at line 239 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), CCopasiParameter::getType(), and CCopasiParameter::GROUP.
Referenced by CFitItem::addCrossValidation(), CMIRIAMResource::addDeprecatedURL(), CExperimentSet::addExperiment(), CFitItem::addExperiment(), CRecentFiles::addFile(), addGroup(), CMIRIAMResources::addMIRIAMResource(), COptProblem::addOptItem(), addParameter(), CScanProblem::addScanItem(), assertParameter(), CLNAProblem::CLNAProblem(), CMCAProblem::CMCAProblem(), COptMethodCoranaWalk::COptMethodCoranaWalk(), COptMethodDE::COptMethodDE(), COptMethodEP::COptMethodEP(), COptMethodEP2::COptMethodEP2(), COptMethodGA::COptMethodGA(), COptMethodGASR::COptMethodGASR(), COptMethodHGASA::COptMethodHGASA(), COptMethodHookeJeeves::COptMethodHookeJeeves(), COptMethodLevenbergMarquardt::COptMethodLevenbergMarquardt(), COptMethodNelderMead::COptMethodNelderMead(), COptMethodPraxis::COptMethodPraxis(), COptMethodPS::COptMethodPS(), COptMethodSA::COptMethodSA(), COptMethodSRES::COptMethodSRES(), COptMethodSS::COptMethodSS(), COptMethodSteepestDescent::COptMethodSteepestDescent(), CRandomSearch::CRandomSearch(), SBMLImporter::createCReactionFromReaction(), CSensProblem::createParametersInGroup(), CScanProblem::createScanItem(), CSensMethod::CSensMethod(), CSensProblem::CSensProblem(), CSteadyStateProblem::CSteadyStateProblem(), CScanProblem::initializeParameter(), CHybridMethodODE45::initializeParameter(), CHybridMethodLSODA::initializeParameter(), CReaction::initializeParameters(), operator=(), CQFittingItemWidget::save(), CMIRIAMResources::updateMIRIAMResources(), and CMIRIAMResources::updateMIRIAMResourcesFromFile().
 {
   if (parameter.getType() == CCopasiParameter::GROUP)
     {
       CCopasiParameterGroup * pGroup =
         new CCopasiParameterGroup(*dynamic_cast<const CCopasiParameterGroup *>(&parameter));
       addParameter(pGroup);
     }
   else
     {
       CCopasiParameter * pParameter = new CCopasiParameter(parameter);
       addParameter(pParameter);
     }
   return true;
 }
bool CCopasiParameterGroup::addParameter (const std::string & name, const CCopasiParameter::Type type)
Add a parameter to the group
Parameters
const std::string & name
const CCopasiParameter::Type type
Returns
bool success
Definition at line 276 of file CCopasiParameterGroup.cpp.
References addParameter(), CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), and CCopasiParameter::GROUP.
 {
   CCopasiParameter * pParameter;
   if (type == GROUP)
     pParameter = new CCopasiParameterGroup(name);
   else
     pParameter = new CCopasiParameter(name, type);
   addParameter(pParameter);
   return true;
 }
template<class CType > bool CCopasiParameterGroup::addParameter (const std::string & name, const CCopasiParameter::Type type, const CType & value) inline
Add a parameter to the group
Parameters
const std::string & name
const CCopasiParameter::Type type
const CType & value
Returns
bool success
Definition at line 138 of file CCopasiParameterGroup.h.
References addParameter(), CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), CCopasiParameter::GROUP, CCopasiParameter::isValidValue(), CCopasiParameter::mValue, CCopasiParameter::Value::pGROUP, and CCopasiParameter::setValue().
   {
     CCopasiParameter * pParameter;
     if (type == GROUP)
       {
         CCopasiParameterGroup *tmp = new CCopasiParameterGroup(name);
         if (!tmp->isValidValue(value))
           {
             delete tmp;
             return false;
           }
         parameterGroup *pGroup = tmp->mValue.pGROUP;
         tmp->mValue.pGROUP =
           static_cast<parameterGroup *>(const_cast<void *>((const void *) & value));
         pParameter = new CCopasiParameterGroup(*tmp);
         tmp->mValue.pGROUP = pGroup;
         delete tmp;
       }
     else
       {
         pParameter = new CCopasiParameter(name, type);
         if (!pParameter->isValidValue(value))
           {
             delete pParameter;
             return false;
           }
         pParameter->setValue(value);
       }
     addParameter(pParameter);
     return true;
   }
void CCopasiParameterGroup::addParameter (CCopasiParameter * pParameter)
Add a parameter
Parameters
CCopasiParameter * pParameter
Definition at line 256 of file CCopasiParameterGroup.cpp.
References CCopasiContainer::add(), CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
 {
   if (pParameter == NULL) return;
   CCopasiContainer::add(pParameter, true);
   mValue.pGROUP->push_back(pParameter);
 }
CCopasiParameterGroup * CCopasiParameterGroup::assertGroup (const std::string & name)
Assert that a group with the given name is present. If not the group is created as empty group.
Parameters
const std::string & name
Returns
CCopasiParameterGroup * pGroup
Definition at line 297 of file CCopasiParameterGroup.cpp.
References addGroup(), getGroup(), and removeParameter().
Referenced by CConfigurationFile::CXML::CXML(), CExperimentObjectMap::elevateChildren(), CRecentFiles::initializeParameter(), CMIRIAMResource::initializeParameter(), CFitItem::initializeParameter(), CConfigurationFile::initializeParameter(), CFitProblem::initializeParameter(), CMIRIAMResources::initializeParameter(), COptProblem::initializeParameter(), CExperiment::initializeParameter(), and CExperimentObjectMap::setNumCols().
 {
   CCopasiParameterGroup * pGrp = getGroup(name);
   if (pGrp) return pGrp;
   removeParameter(name);
   addGroup(name);
   return getGroup(name);
 }
template<class CType > CCopasiParameter* CCopasiParameterGroup::assertParameter (const std::string & name, const CCopasiParameter::Type type, const CType & defaultValue) inline
Assert that a parameter with the given name and type is present. If not the parameter is created with the default value.
Parameters
const std::string & name
const CCopasiParameter::Type type
const CType & Value
Returns
CCopasiParameter * pParameter
Definition at line 190 of file CCopasiParameterGroup.h.
References addParameter(), getParameter(), CCopasiParameter::getType(), and removeParameter().
Referenced by CFitProblem::elevateChildren(), CExperimentObjectMap::elevateChildren(), CTSSAMethod::initializeIntegrationsParameter(), CExperimentObjectMap::CDataColumn::initializeParameter(), CRecentFiles::initializeParameter(), CILDMMethod::initializeParameter(), CILDMModifiedMethod::initializeParameter(), CSteadyStateMethod::initializeParameter(), CMIRIAMResource::initializeParameter(), CLyapProblem::initializeParameter(), CNewtonMethod::initializeParameter(), CTrajectoryProblem::initializeParameter(), CTSSAProblem::initializeParameter(), CMCAMethod::initializeParameter(), CCrossSectionProblem::initializeParameter(), CCSPMethod::initializeParameter(), CStochDirectMethod::initializeParameter(), CTrajAdaptiveSA::initializeParameter(), CHybridMethodODE45::initializeParameter(), CTauLeapMethod::initializeParameter(), CLyapWolfMethod::initializeParameter(), CStochMethod::initializeParameter(), CConfigurationFile::initializeParameter(), COptItem::initializeParameter(), CFitProblem::initializeParameter(), CLsodaMethod::initializeParameter(), CMIRIAMResources::initializeParameter(), CCrossValidationSet::initializeParameter(), CTrajectoryMethodDsaLsodar::initializeParameter(), COptProblem::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodLSODA::initializeParameter(), CExperiment::initializeParameter(), CExperimentObjectMap::CDataColumn::setObjectCN(), CExperimentObjectMap::CDataColumn::setScale(), CPlotItem::setType(), and CCopasiXMLParser::TaskElement::start().
   {
     CCopasiParameter * pParm = getParameter(name);
     if (pParm && pParm->getType() == type) return pParm;
     if (pParm) removeParameter(name);
     addParameter(name, type, defaultValue);
     return getParameter(name);
   }
CCopasiParameterGroup::index_iterator CCopasiParameterGroup::beginIndex () const
Retrieve the begin of unsorted iterator Note: the swap function may be used to change the order
Returns
name_iterator begin
Definition at line 270 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by CRecentFiles::addFile(), CMIRIAMResources::createDisplayNameMap(), CMIRIAMResources::createURIMap(), CMIRIAMResources::elevateChildren(), CMIRIAMResourceObject::extractId(), CExperimentObjectMap::fixBuild55(), CScanProblem::fixBuild81(), CReaction::getDeletedObjects(), CReaction::initializeParameters(), CReaction::mustBeDeleted(), CopasiUI3Window::refreshRecentFileMenu(), CopasiUI3Window::refreshRecentSBMLFileMenu(), CExperimentSet::sort(), and swap().
 {return mValue.pGROUP->begin();}
CCopasiParameterGroup::name_iterator CCopasiParameterGroup::beginName () const
Retrieve the begin of an alphabetically sorted iterator
Returns
name_iterator begin
Definition at line 264 of file CCopasiParameterGroup.cpp.
References CCopasiContainer::getObjects().
Referenced by operator=().
 {return const_cast< CCopasiContainer::objectMap * >(&getObjects())->begin();}
void CCopasiParameterGroup::clear ()
Clear all parameters and subgroups
Definition at line 515 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, pdelete, and CCopasiParameter::Value::pGROUP.
Referenced by CScanProblem::clearScanItems(), CExperiment::elevateChildren(), CExperimentObjectMap::elevateChildren(), CQExperimentData::load(), CConfigurationFile::CXML::load(), CQSteadyStateResult::loadResult(), CQFittingItemWidget::loadSelection(), CExperiment::operator=(), CPlotItem::setType(), CCopasiXMLParser::ListOfConstantsElement::start(), and ~CCopasiParameterGroup().
 {
   if (mValue.pGROUP)
     {
       index_iterator it = mValue.pGROUP->begin();
       index_iterator end = mValue.pGROUP->end();
       for (; it != end; ++it) pdelete(*it);
       mValue.pGROUP->clear();
     }
 }
bool CCopasiParameterGroup::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented in CTSSAMethod, CTrajectoryMethodDsaLsodar, CLsodaMethod, CMIRIAMResources, CStochMethod, CExperimentObjectMap, CHybridMethodODE45, CLyapWolfMethod, CTrajAdaptiveSA, CStochDirectMethod, CHybridMethodLSODA, CExperiment, CTauLeapMethod, CSteadyStateMethod, CHybridMethod, CConfigurationFile, CNewtonMethod, CLNAMethod, CTSSAProblem, COptProblem, CExperimentObjectMap::CDataColumn, CLyapProblem, CEFMProblem, CFitItem, CExperimentSet, CMCAMethod, CTrajectoryProblem, CFitProblem, COscillationProblem, and COptMethodSS.
Definition at line 90 of file CCopasiParameterGroup.cpp.
Referenced by CCrossSectionTask::CCrossSectionTask(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), and CCopasiXMLParser::TaskElement::end().
 {return true;}
CCopasiParameterGroup::index_iterator CCopasiParameterGroup::endIndex () const
Retrieve the end of unsorted iterator Note: the swap function may be used to change the order
Returns
name_iterator end
Definition at line 273 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by CRecentFiles::addFile(), CMIRIAMResources::createDisplayNameMap(), CMIRIAMResources::createURIMap(), CMIRIAMResources::elevateChildren(), CMIRIAMResourceObject::extractId(), CExperimentObjectMap::fixBuild55(), CScanProblem::fixBuild81(), CReaction::getDeletedObjects(), CReaction::initializeParameters(), CReaction::mustBeDeleted(), CopasiUI3Window::refreshRecentFileMenu(), CopasiUI3Window::refreshRecentSBMLFileMenu(), CExperimentSet::sort(), and swap().
 {return mValue.pGROUP->end();}
CCopasiParameterGroup::name_iterator CCopasiParameterGroup::endName () const
Retrieve the end of an alphabetically sorted iterator
Returns
name_iterator end
Definition at line 267 of file CCopasiParameterGroup.cpp.
References CCopasiContainer::getObjects().
Referenced by operator=().
 {return const_cast< CCopasiContainer::objectMap * >(&getObjects())->end();}
CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const std::string & name)
Retrieve a subgroup from the group
Parameters
const std::string & name
Returns
CCopasiParameterGroup * group
Definition at line 383 of file CCopasiParameterGroup.cpp.
References getParameter().
Referenced by assertGroup(), CFitProblem::elevateChildren(), CConfigurationFile::elevateChildren(), CExperiment::elevateChildren(), CExperimentObjectMap::getDefaultScale(), CExperimentSet::getExperiment(), CMIRIAMResources::getMIRIAMResource(), CExperimentObjectMap::getName(), CExperimentObjectMap::getObjectCN(), CExperimentObjectMap::getRole(), CExperimentObjectMap::getScale(), CConfigurationFile::load(), CQFittingWidget::loadTask(), CQOptimizationWidget::loadTask(), CopasiUI3Window::refreshRecentFileMenu(), CopasiUI3Window::refreshRecentSBMLFileMenu(), CQFittingWidget::saveTask(), CExperimentObjectMap::setObjectCN(), CExperimentObjectMap::setRole(), CExperimentObjectMap::setScale(), CopasiUI3Window::slotOpenRecentFile(), and CopasiUI3Window::slotOpenRecentSBMLFile().
 {return dynamic_cast<CCopasiParameterGroup *>(getParameter(name));}
const CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const std::string & name) const
Retrieve a subgroup from the group
Parameters
const std::string & name
Returns
const CCopasiParameterGroup * group
Definition at line 386 of file CCopasiParameterGroup.cpp.
References getParameter().
 {return dynamic_cast<const CCopasiParameterGroup *>(getParameter(name));}
CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const size_t & index)
Retrieve a subgroup from the group
Parameters
const size_t & index
Returns
CCopasiParameterGroup * parameter
Definition at line 389 of file CCopasiParameterGroup.cpp.
References getParameter().
 {return dynamic_cast<CCopasiParameterGroup *>(getParameter(index));}
const CCopasiParameterGroup * CCopasiParameterGroup::getGroup (const size_t & index) const
Retrieve a subgroup from the group
Parameters
const size_t & index
Returns
const CCopasiParameterGroup * parameter
Definition at line 392 of file CCopasiParameterGroup.cpp.
References getParameter().
 {return dynamic_cast<const CCopasiParameterGroup *>(getParameter(index));}
size_t CCopasiParameterGroup::getIndex (const std::string & name) const
Retrieve the index of a parameter or subgroup with a given name
Parameters
const std::string & name
Returns
size_t index
Definition at line 528 of file CCopasiParameterGroup.cpp.
References C_INVALID_INDEX, CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by getParameterValue(), removeParameter(), and setParameterValue().
 {
   index_iterator it = mValue.pGROUP->begin();
   index_iterator end = mValue.pGROUP->end();
   for (size_t i = 0; it != end; ++it, ++i)
     if (name == (*it)->getObjectName()) return i;;
   return C_INVALID_INDEX;
 }
std::string CCopasiParameterGroup::getKey (const std::string & name) const
Retrieve the key of a parameter or subgroup
Parameters
const std::string & name
Returns
std::string key
Definition at line 457 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::getKey(), and getParameter().
Referenced by CCopasiXML::saveModel().
 {
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(name);
   if (pParameter) return pParameter->getKey();
   return "Not Found";
 }
std::string CCopasiParameterGroup::getKey (const size_t & index) const
Retrieve the key of a parameter or subgroup
Parameters
const size_t & index
Returns
std::string key
Definition at line 467 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::getKey(), and getParameter().
 {
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(index);
   if (pParameter) return pParameter->getKey();
   return "Not Found";
 }
const std::string & CCopasiParameterGroup::getName (const size_t & index) const virtual
Retrieve the name of a parameter or subgroup
Parameters
const size_t & index
Returns
std::string name
Reimplemented in CExperimentObjectMap.
Definition at line 477 of file CCopasiParameterGroup.cpp.
References CCopasiObject::getObjectName(), and getParameter().
Referenced by getParameterValue(), CQTaskMethodWidget::loadMethod(), CQMCAWidget::loadParameterTable(), CQLNAWidget::loadParameterTable(), CExperiment::read(), CExperiment::readColumnNames(), and CCopasiXML::saveModel().
 {
   static std::string Invalid("Invalid Index");
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(index);
   if (pParameter) return pParameter->getObjectName();
   return Invalid;
 }
const CObjectInterface * CCopasiParameterGroup::getObject (const CCopasiObjectName & cn) const virtual
Retrieve a descendant object by its CN.
Parameters
const CCopasiObjectName & cn
Returns
const CObjectInterface * pObject
Reimplemented from CCopasiContainer.
Definition at line 55 of file CCopasiParameterGroup.cpp.
References C_INVALID_INDEX, CCopasiContainer::getObject(), CCopasiObjectName::getObjectName(), CCopasiObjectName::getRemainder(), CCopasiParameter::mValue, CCopasiParameter::Value::pGROUP, and strToUnsignedInt().
Referenced by COutputAssistant::createDefaultOutput().
 {
   const CObjectInterface * pObjectInterface = CCopasiContainer::getObject(cn);
   if (pObjectInterface != NULL)
     {
       return pObjectInterface;
     }
   std::string UniqueName = cn.getObjectName();
   std::string::size_type pos = UniqueName.find_last_of('[');
   std::string Name = UniqueName.substr(0, pos);
   size_t Index = strToUnsignedInt(UniqueName.substr(pos + 1).c_str());
   size_t counter = C_INVALID_INDEX;
   index_iterator it = mValue.pGROUP->begin();
   index_iterator end = mValue.pGROUP->end();
   for (; it != end; ++it)
     {
       if ((*it)->getObjectName() == Name)
         {
           counter++;
           if (counter == Index)
             {
               return (*it)->getObject(cn.getRemainder());
             }
         }
     }
   return NULL;
 }
CCopasiParameter * CCopasiParameterGroup::getParameter (const std::string & name)
Retrieve a parameter or subgroup from the group
Parameters
const std::string & name
Returns
CCopasiParameter * parameter
Definition at line 343 of file CCopasiParameterGroup.cpp.
References CCopasiContainer::getObjects().
Referenced by CExperimentSet::addExperiment(), CSensProblem::addVariables(), assertParameter(), DataModelGUI::buildChangedObjects(), CModel::buildInitialRefreshSequence(), CModel::buildInitialSequence(), CSensProblem::changeVariables(), CModelAnalyzer::checkReaction(), CModel::convert2NonReversible(), CSEDMLExporter::createScanTask(), CSensProblem::CSensProblem(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), CFitProblem::elevateChildren(), CFitItem::elevateChildren(), COptProblem::elevateChildren(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::TaskElement::end(), CODEExporter::exportReacParamsAndFuncs(), CScanProblem::fixBuild81(), CPlotItem::getActivity(), CReactionInterface::getDeletedParameters(), getGroup(), getKey(), getName(), CScanProblem::getScanItem(), getType(), getValue(), CSensProblem::getVariables(), SEDMLImporter::importTasks(), CQPreferenceDialog::init(), CTrajectoryTask::initialize(), CTSSATask::initialize(), CCrossSectionTask::initialize(), CTSSAMethod::initializeIntegrationsParameter(), CExperimentObjectMap::CDataColumn::initializeParameter(), CSteadyStateMethod::initializeParameter(), CScanProblem::initializeParameter(), CNewtonMethod::initializeParameter(), CMCAMethod::initializeParameter(), CHybridMethodODE45::initializeParameter(), CLyapWolfMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CStochMethod::initializeParameter(), CLsodaMethod::initializeParameter(), CTrajectoryMethodDsaLsodar::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodLSODA::initializeParameter(), CExperiment::initializeParameter(), CReaction::initializeParameters(), CTrajectoryProblem::initObjects(), CTSSAProblem::initObjects(), CReaction::isLocalParameter(), CTrajectoryTask::load(), CReactionInterface::loadMappingAndValues(), SBMLImporter::sbmlId2CopasiCN(), CTrajectoryTask::setMethodType(), CCrossSectionTask::setMethodType(), CReaction::setParameterValue(), setValue(), CQPreferenceDialog::slotBtnOk(), CCopasiXMLParser::ConstantElement::start(), SteadyStateWidget::taskFinishedEvent(), test000058::test_bug1025_1(), test000058::test_bug1025_6(), test000087::test_simulate_reaction_flux_reference_1(), test000059::test_unique_id_10(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_4(), test000059::test_unique_id_7(), test000059::test_unique_id_9(), and CQExperimentDataValidator::validate().
 {
   std::pair < CCopasiContainer::objectMap::const_iterator,
       CCopasiContainer::objectMap::const_iterator > range =
         getObjects().equal_range(name);
   if (range.first == range.second) return NULL;
   return
     dynamic_cast<CCopasiParameter *>(const_cast< CCopasiObject * >(range.first->second));
 }
const CCopasiParameter * CCopasiParameterGroup::getParameter (const std::string & name) const
Retrieve a parameter or subgroup from the group
Parameters
const std::string & name
Returns
const CCopasiParameter * parameter
Definition at line 355 of file CCopasiParameterGroup.cpp.
References CCopasiContainer::getObjects().
 {
   std::pair < CCopasiContainer::objectMap::const_iterator,
       CCopasiContainer::objectMap::const_iterator > range =
         getObjects().equal_range(name);
   if (range.first == range.second) return NULL;
   return
     dynamic_cast<CCopasiParameter *>(range.first->second);
 }
CCopasiParameter * CCopasiParameterGroup::getParameter (const size_t & index)
Retrieve a parameter or subgroup from the group
Parameters
const size_t & index
Returns
CCopasiParameter * parameter
Definition at line 367 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, CCopasiParameter::Value::pGROUP, and size().
 {
   if (index < size())
     return *(mValue.pGROUP->begin() + index);
   return NULL;
 }
const CCopasiParameter * CCopasiParameterGroup::getParameter (const size_t & index) const
Retrieve a parameter or subgroup from the group
Parameters
const size_t & index
Returns
const CCopasiParameter * parameter
Definition at line 375 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, CCopasiParameter::Value::pGROUP, and size().
 {
   if (index < size())
     return *(mValue.pGROUP->begin() + index);
   return NULL;
 }
CCopasiParameter::Type CCopasiParameterGroup::getType (const std::string & name) const
Retrieve the type of a parameter or subgroup
Parameters
const std::string & name
Returns
CCopasiParameter::Type
Definition at line 437 of file CCopasiParameterGroup.cpp.
References getParameter(), CCopasiParameter::getType(), and CCopasiParameter::INVALID.
Referenced by getParameterValue(), and setParameterValue().
 {
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(name);
   if (pParameter) return pParameter->getType();
   return CCopasiParameter::INVALID;
 }
CCopasiParameter::Type CCopasiParameterGroup::getType (const size_t & index) const
Retrieve the type of a parameter or subgroup
Parameters
const size_t & index
Returns
CCopasiParameter::Type
Definition at line 447 of file CCopasiParameterGroup.cpp.
References getParameter(), CCopasiParameter::getType(), and CCopasiParameter::INVALID.
 {
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(index);
   if (pParameter) return pParameter->getType();
   return CCopasiParameter::INVALID;
 }
std::string CCopasiParameterGroup::getUniqueParameterName (const CCopasiParameter * pParameter) const
Retrieve a unique name for the given parameter
Parameters
const CCopasiParameter * pParameter
Returns
std::string uniqueParameterName
Definition at line 539 of file CCopasiParameterGroup.cpp.
References C_INVALID_INDEX, CCopasiObject::getObjectName(), CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by CCopasiParameter::getCN(), and CCopasiParameter::getObjectDisplayName().
 {
   size_t counter = C_INVALID_INDEX;
   size_t Index = C_INVALID_INDEX;
   std::string Name = pParameter->getObjectName();
   index_iterator it = mValue.pGROUP->begin();
   index_iterator end = mValue.pGROUP->end();
   for (; it != end; ++it)
     {
       if ((*it)->getObjectName() == Name)
         {
           counter++;
           if (*it == pParameter)
             {
               Index = counter;
             }
         }
     }
   if (counter == 0 || Index == C_INVALID_INDEX)
     {
       return Name;
     }
   std::stringstream UniqueName;
   UniqueName << Name << "[" << Index << "]";
   return UniqueName.str();
 }
const CCopasiParameter::Value & CCopasiParameterGroup::getValue (const std::string & name) const
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const std::string & name
Returns
const CCopasiParameter::Value & Value
Definition at line 395 of file CCopasiParameterGroup.cpp.
References fatalError, getParameter(), and CCopasiParameter::getValue().
Referenced by CFitItem::addCrossValidation(), CFitItem::addExperiment(), CSensProblem::copyParameterGroupToSensItem(), CScanItem::createScanItemFromParameterGroup(), CScanItem::CScanItem(), CScanItemLinear::CScanItemLinear(), CScanItemRandom::CScanItemRandom(), CFitProblem::elevateChildren(), CExperiment::elevateChildren(), CFitItem::getCrossValidation(), CFitItem::getCrossValidations(), CFitItem::getExperiment(), CFitItem::getExperiments(), getParameterValue(), CReaction::getParameterValue(), CScanTask::initSubtask(), CScanWidgetRepeat::load(), CScanWidgetRandom::load(), CScanWidgetScan::load(), Curve2DWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), ScanWidget::loadTask(), operator==(), CCopasiXML::saveModel(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), CopasiUI3Window::slotOpenRecentFile(), and CopasiUI3Window::slotOpenRecentSBMLFile().
 {
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(name);
   if (!pParameter)
     fatalError();
   return pParameter->getValue();
 }
const CCopasiParameter::Value & CCopasiParameterGroup::getValue (const size_t & index) const
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const size_t & index
Returns
const CCopasiParameter::Value & Value
Definition at line 406 of file CCopasiParameterGroup.cpp.
References fatalError, getParameter(), and CCopasiParameter::getValue().
 {
   CCopasiParameter * pParameter =
     const_cast< CCopasiParameterGroup * >(this)->getParameter(index);
   if (!pParameter)
     fatalError();
   return pParameter->getValue();
 }
CCopasiParameter::Value & CCopasiParameterGroup::getValue (const std::string & name)
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const std::string & name
Returns
CCopasiParameter::Value & Value
Definition at line 417 of file CCopasiParameterGroup.cpp.
References fatalError, getParameter(), and CCopasiParameter::getValue().
 {
   CCopasiParameter * pParameter = getParameter(name);
   if (!pParameter)
     fatalError();
   return pParameter->getValue();
 }
CCopasiParameter::Value & CCopasiParameterGroup::getValue (const size_t & index)
Retrieve a pointer to the value of a parameter or subgroup
Parameters
const size_t & index
Returns
CCopasiParameter::Value & Value
Definition at line 427 of file CCopasiParameterGroup.cpp.
References fatalError, getParameter(), and CCopasiParameter::getValue().
 {
   CCopasiParameter * pParameter = getParameter(index);
   if (!pParameter)
     fatalError();
   return pParameter->getValue();
 }
CCopasiParameterGroup & CCopasiParameterGroup::operator= (const CCopasiParameterGroup & rhs)
Assignment operator
Parameters
const CCopasiParameterGroup & rhs
Returns
CCopasiParameterGroup & lhs
Definition at line 92 of file CCopasiParameterGroup.cpp.
References addParameter(), beginName(), CCopasiParameter::CCopasiParameter(), CCopasiParameterGroup(), endName(), CCopasiObject::getObjectName(), CCopasiParameter::GROUP, removeParameter(), and CCopasiObject::setObjectName().
 {
   if (getObjectName() != rhs.getObjectName())
     setObjectName(rhs.getObjectName());
   name_iterator itRHS = rhs.beginName();
   name_iterator endRHS = rhs.endName();
   name_iterator itLHS = beginName();
   name_iterator endLHS = endName();
   std::vector< std::string > ToBeRemoved;
   std::vector< CCopasiParameter * > ToBeAdded;
   CCopasiParameter * pLHS;
   CCopasiParameter * pRHS;
   while (itRHS != endRHS && itLHS != endLHS)
     {
       // We only assign parameters
       if ((pRHS = dynamic_cast< CCopasiParameter * >(itRHS->second)) == NULL)
         {
           ++itRHS;
           continue;
         }
       // We only assign parameters
       if ((pLHS = dynamic_cast< CCopasiParameter * >(itLHS->second)) == NULL)
         {
           ++itLHS;
           continue;
         }
       const std::string & NameLHS = pLHS->getObjectName();
       const std::string & NameRHS = pRHS->getObjectName();
       // The LHS parameter is missing on the RHS thus we need to remove it
       if (NameLHS < NameRHS)
         {
           ToBeRemoved.push_back(NameLHS);
           ++itLHS;
           continue;
         }
       // The RHS parameter is missing on the LHS thus we need to add it
       if (NameLHS > NameRHS)
         {
           ToBeAdded.push_back(pRHS);
           ++itRHS;
           continue;
         }
       // The names are equal it suffices to use the assignment operator of the parameter
       *pLHS = *pRHS;
       ++itLHS;
       ++itRHS;
     }
   // All remaining parameters of the LHS need to be removed
   while (itLHS != endLHS)
     {
       // We only assign parameters
       if ((pLHS = dynamic_cast< CCopasiParameter * >(itLHS->second)) != NULL)
         ToBeRemoved.push_back(pLHS->getObjectName());
       ++itLHS;
     }
   // All remaining paramter of the RHS need to be added
   while (itRHS != endRHS)
     {
       // We only assign parameters
       if ((pRHS = dynamic_cast< CCopasiParameter * >(itRHS->second)) != NULL)
         ToBeAdded.push_back(pRHS);
       ++itRHS;
     }
   // We remove the parameters
   std::vector< std::string >::const_iterator itToBeRemoved = ToBeRemoved.begin();
   std::vector< std::string >::const_iterator endToBeRemoved = ToBeRemoved.end();
   for (; itToBeRemoved != endToBeRemoved; ++itToBeRemoved)
     this->removeParameter(*itToBeRemoved);
   // We add the missing parameters
   CCopasiParameter * pParameter;
   std::vector< CCopasiParameter * >::const_iterator itToBeAdded = ToBeAdded.begin();
   std::vector< CCopasiParameter * >::const_iterator endToBeAdded = ToBeAdded.end();
   for (; itToBeAdded != endToBeAdded; ++itToBeAdded)
     {
       if ((*itToBeAdded)->getType() == GROUP)
         pParameter = new CCopasiParameterGroup(* static_cast< CCopasiParameterGroup * >(*itToBeAdded));
       else
         pParameter = new CCopasiParameter(**itToBeAdded);
       addParameter(pParameter);
     }
   return *this;
 }
void CCopasiParameterGroup::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiParameter.
Reimplemented in COptProblem, CCopasiMethod, CCopasiProblem, CSensProblem, CCrossSectionProblem, CLNAProblem, CMCAProblem, CFitProblem, and COscillationProblem.
Definition at line 196 of file CCopasiParameterGroup.cpp.
Referenced by operator<<().
 {*ostream << *this;}
bool CCopasiParameterGroup::removeParameter (const std::string & name)
Remove a parameter or subgroup from the group
Parameters
const std::string & name
Returns
bool success
Definition at line 309 of file CCopasiParameterGroup.cpp.
References C_INVALID_INDEX, getIndex(), CCopasiParameter::mValue, pdelete, and CCopasiParameter::Value::pGROUP.
Referenced by assertGroup(), assertParameter(), COptMethodSS::elevateChildren(), CFitProblem::elevateChildren(), CFitItem::elevateChildren(), COptProblem::elevateChildren(), CTSSAProblem::elevateChildren(), CExperiment::elevateChildren(), CTSSAMethod::initializeIntegrationsParameter(), CSteadyStateMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CMCAMethod::initializeParameter(), CHybridMethodODE45::initializeParameter(), CTauLeapMethod::initializeParameter(), CLyapWolfMethod::initializeParameter(), CStochMethod::initializeParameter(), CFitProblem::initializeParameter(), CLsodaMethod::initializeParameter(), CTrajectoryMethodDsaLsodar::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodLSODA::initializeParameter(), CExperiment::initializeParameter(), CReaction::initializeParameters(), COptMethodLevenbergMarquardt::initObjects(), operator=(), CFitItem::removeCrossValidation(), CExperimentSet::removeExperiment(), CFitItem::removeExperiment(), COptProblem::removeOptItem(), CScanProblem::removeScanItem(), CSensProblem::removeVariables(), CQFittingItemWidget::save(), CExperimentObjectMap::CDataColumn::setObjectCN(), CExperimentObjectMap::CDataColumn::setScale(), and CQExperimentData::slotOK().
 {
   size_t index = getIndex(name);
   if (index != C_INVALID_INDEX)
     {
       index_iterator it =
         mValue.pGROUP->begin() + index;
       pdelete(*it);
       mValue.pGROUP->erase(it, it + 1);
       return true;
     }
   return false;
 }
bool CCopasiParameterGroup::removeParameter (const size_t & index)
Remove a parameter or subgroup from the group
Parameters
const size_t & index
Returns
bool success
Definition at line 327 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, pdelete, CCopasiParameter::Value::pGROUP, and size().
 {
   if (index < size())
     {
       index_iterator it =
         mValue.pGROUP->begin() + index;
       pdelete(*it);
       mValue.pGROUP->erase(it, it + 1);
       return true;
     }
   return false;
 }
template<class CType > bool CCopasiParameterGroup::setValue (const std::string & name, const CType & value) inline
Set the value of a parameter or subgroup.
Parameters
const std::string & name
const CType & value
Returns
bool success
Definition at line 361 of file CCopasiParameterGroup.h.
References getParameter(), and CCopasiParameter::setValue().
Referenced by CQPlotSubwidget::addHisto1DTab(), CSensProblem::copySensItemToParameterGroup(), COutputAssistant::createDefaultOutput(), COutputAssistant::createPlot(), CFitProblem::elevateChildren(), CCopasiXMLParser::TaskElement::end(), COptMethodDE::initialize(), COptMethodSRES::initialize(), COptMethodPS::initialize(), COptMethodGASR::initialize(), COptMethodSS::initialize(), CTSSAMethod::initializeIntegrationsParameter(), CSteadyStateMethod::initializeParameter(), CNewtonMethod::initializeParameter(), CMCAMethod::initializeParameter(), CHybridMethodODE45::initializeParameter(), CTauLeapMethod::initializeParameter(), CLyapWolfMethod::initializeParameter(), CStochMethod::initializeParameter(), CTrajectoryMethodDsaLsodar::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodLSODA::initializeParameter(), CHybridMethodODE45::initMethod(), CHybridMethodLSODA::initMethod(), CSteadyStateProblem::load(), CNewtonMethod::load(), CExperiment::operator=(), COptMethodSS::optimise(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CScanWidgetRepeat::save(), CScanWidgetRandom::save(), CScanWidgetScan::save(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), CScanProblem::setContinueFromCurrentState(), CSteadyStateProblem::setJacobianRequested(), CPlotSpecification::setLogX(), CPlotSpecification::setLogY(), CScanProblem::setOutputInSubtask(), setParameterValue(), CReaction::setParameterValue(), CSteadyStateProblem::setStabilityAnalysisRequested(), CLNAProblem::setSteadyStateRequested(), CMCAProblem::setSteadyStateRequested(), CScanProblem::setSubtask(), and TestOptimization().
   {
     CCopasiParameter * pParameter =
       const_cast< CCopasiParameterGroup * >(this)->getParameter(name);
     if (pParameter) return pParameter->setValue(value);
     return false;
   }
template<class CType > bool CCopasiParameterGroup::setValue (const size_t & index, const CType & value) inline
Set the value of a parameter or subgroup.
Parameters
const size_t & index
const CType & value
Returns
bool success
Definition at line 379 of file CCopasiParameterGroup.h.
References getParameter(), and CCopasiParameter::setValue().
   {
     CCopasiParameter * pParameter =
       const_cast< CCopasiParameterGroup * >(this)->getParameter(index);
     if (pParameter) return pParameter->setValue(value);
     return false;
   }
size_t CCopasiParameterGroup::size () const
The size of the parameter group @ return size_t size
Definition at line 512 of file CCopasiParameterGroup.cpp.
References CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
Referenced by CFitItem::addCrossValidation(), CFitItem::addExperiment(), CRecentFiles::addFile(), DataModelGUI::buildChangedObjects(), CModel::buildInitialRefreshSequence(), CModel::buildInitialSequence(), CQTaskMethodWidget::changeMethod(), CModelAnalyzer::checkReaction(), CExperimentObjectMap::compile(), CExperiment::elevateChildren(), CODEExporter::exportReacParamsAndFuncs(), CODEExporterC::exportTitleData(), CFitItem::getCrossValidation(), CFitItem::getCrossValidationCount(), CFitItem::getCrossValidations(), CFitItem::getExperiment(), CExperimentSet::getExperimentCount(), CFitItem::getExperimentCount(), CFitItem::getExperiments(), CMIRIAMResources::getMIRIAMResource(), CScanProblem::getNumberOfScanItems(), CSensProblem::getNumberOfVariables(), COptProblem::getOptItemSize(), getParameter(), getParameterValue(), CReaction::isLocalParameter(), CExperimentSet::keyToIndex(), CQFittingItemWidget::load(), CConfigurationFile::load(), CQTaskMethodWidget::loadMethod(), CQLNAWidget::loadParameterTable(), CQMCAWidget::loadParameterTable(), operator<<(), CQSimpleSelectionTree::populateTree(), CCSPMethod::printResult(), CExperiment::read(), removeParameter(), CSensProblem::removeVariables(), CQFittingItemWidget::save(), CQTaskMethodWidget::saveMethod(), CCopasiXML::saveModel(), CQLNAWidget::saveParameterTable(), CQMCAWidget::saveParameterTable(), setParameterValue(), CQEFMReactionDM::setTask(), CQFittingItemWidget::slotReset(), CExperiment::updateFittedPoints(), and CQMiriamWidget::updateResourcesList().
 {return mValue.pGROUP->size();}
bool CCopasiParameterGroup::swap (const size_t & iFrom, const size_t & iTo)
Swap two parameters Note: This has effect on the index_iterator and index access methods.
Parameters
const size_t & iFrom
const size_t & iTo
Returns
bool success
Definition at line 489 of file CCopasiParameterGroup.cpp.
References beginIndex().
Referenced by CExperimentSet::sort(), and COptProblem::swapOptItem().
 {
   index_iterator from = beginIndex() + iFrom;
   index_iterator to = beginIndex() + iTo;
   return swap(from, to);
 }
bool CCopasiParameterGroup::swap (index_iterator & from, index_iterator & to)
Swap two parameters Note: This has effect on the iterator and index access methods.
Parameters
index_iterator & from
index_iterator & to
Returns
bool success
Definition at line 498 of file CCopasiParameterGroup.cpp.
References beginIndex(), and endIndex().
 {
   if (from < beginIndex() || endIndex() <= from ||
       to < beginIndex() || endIndex() <= to)
     return false;
   CCopasiParameter *tmp = *from;
   *from = *to;
   *to = tmp;
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiParameterGroup & o) friend
Output stream operator
Parameters
ostream & os
const CCopasiParameterGroup & o
Returns
ostream & os
Definition at line 199 of file CCopasiParameterGroup.cpp.
 {
   os << "<<< Parameter Group: " << o.getObjectName() << std::endl;
   CCopasiParameterGroup::parameterGroup::const_iterator it =
     o.CCopasiParameter::getValue().pGROUP->begin();
   CCopasiParameterGroup::parameterGroup::const_iterator end =
     o.CCopasiParameter::getValue().pGROUP->end();
   for (; it != end; ++it)
     {
       (*it)->print(&os);
       os << std::endl;
     }
   os << ">>> Parameter Group: " << o.getObjectName() << std::endl;
   return os;
 }
bool operator== (const CCopasiParameterGroup & lhs, const CCopasiParameterGroup & rhs) friend
Comparison operator
Parameters
const CCopasiParameterGroup & lhs
const CCopasiParameterGroup & rhs
Returns
bool equal
Definition at line 218 of file CCopasiParameterGroup.cpp.
 {
   if (lhs.getObjectName() != rhs.getObjectName()) return false;
   if (lhs.mValue.pGROUP->size() != rhs.mValue.pGROUP->size()) return false;
   CCopasiParameterGroup::parameterGroup::const_iterator itLhs =
     lhs.mValue.pGROUP->begin();
   CCopasiParameterGroup::parameterGroup::const_iterator endLhs =
     lhs.mValue.pGROUP->end();
   CCopasiParameterGroup::parameterGroup::const_iterator itRhs =
     rhs.mValue.pGROUP->begin();
   for (; itLhs != endLhs; ++itLhs, ++itRhs)
     if (!(**itLhs == **itRhs)) return false;
   return true;
 }
The documentation for this class was generated from the following files:
CCopasiParameterGroup.h
CCopasiParameterGroup.cpp