COPASI API: CQStyledGraphicsItem Class Reference
CQStyledGraphicsItem Class Reference
#include <CQStyledGraphicsItem.h>
Public Member Functions
CQStyledGraphicsItem (const CLGraphicalObject *go, const CLRenderResolver *resolver=NULL)
virtual ~CQStyledGraphicsItem ()
Public Member Functions inherited from CQCopasiGraphicsItem
CQCopasiGraphicsItem (const CLRenderResolver *resolver, const CLStyle *style)
const CLRenderResolver * getResolver () const
const CLStyle * getStyle () const
void setResolver (const CLRenderResolver *resolver)
void setStyle (const CLStyle *style)
virtual ~CQCopasiGraphicsItem ()
Protected Member Functions
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Protected Attributes
bool mWasMoved
Protected Attributes inherited from CQCopasiGraphicsItem
const CLRenderResolver * mpResolver
const CLStyle * mpStyle
Detailed Description
Definition at line 17 of file CQStyledGraphicsItem.h.
Constructor & Destructor Documentation
CQStyledGraphicsItem::CQStyledGraphicsItem (const CLGraphicalObject * go, const CLRenderResolver * resolver = NULL)
Definition at line 15 of file CQStyledGraphicsItem.cpp.
References COPASI_LAYOUT_KEY, CQRenderConverter::fillGroupFromStyle(), CLGraphicalObject::getBoundingBox(), CLGraphicalObject::getKey(), CQCopasiGraphicsItem::mpResolver, and CQCopasiGraphicsItem::mpStyle.
   : CQCopasiGraphicsItem(resolver, resolver != NULL ? resolver->resolveStyle(go) : NULL)
   , mWasMoved(false)
 {
   setFlag(QGraphicsItem::ItemIsMovable);
   setFlag(QGraphicsItem::ItemIsSelectable);
   setFlag(QGraphicsItem::ItemSendsGeometryChanges);
   setData(COPASI_LAYOUT_KEY, QString(go->getKey().c_str()));
   CQRenderConverter::fillGroupFromStyle(this, &go->getBoundingBox(), mpStyle, mpResolver);
 }
CQStyledGraphicsItem::~CQStyledGraphicsItem () virtual
Definition at line 26 of file CQStyledGraphicsItem.cpp.
 {
 }
Member Function Documentation
QVariant CQStyledGraphicsItem::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Definition at line 46 of file CQStyledGraphicsItem.cpp.
References mWasMoved.
 {
   CQLayoutScene * currentScene = dynamic_cast<CQLayoutScene *>(scene());
   if (change == ItemPositionHasChanged && currentScene)
     {
       mWasMoved = true;
     }
   return QGraphicsItem::itemChange(change, value);
 }
void CQStyledGraphicsItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 30 of file CQStyledGraphicsItem.cpp.
References COPASI_LAYOUT_KEY, mWasMoved, and CQLayoutScene::updatePosition().
 {
   CQLayoutScene * currentScene = dynamic_cast<CQLayoutScene *>(scene());
   if (mWasMoved && currentScene)
     {
       QPointF currentPos = pos();
       currentScene->updatePosition(data(COPASI_LAYOUT_KEY).toString(), currentPos);
       mWasMoved = false;
     }
   else
     {
       QGraphicsItem::mouseReleaseEvent(event);
     }
 }
Member Data Documentation
bool CQStyledGraphicsItem::mWasMoved protected
Definition at line 27 of file CQStyledGraphicsItem.h.
Referenced by itemChange(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
CQStyledGraphicsItem.h
CQStyledGraphicsItem.cpp