COPASI API: CPlotColors Class Reference
CPlotColors Class Reference
#include <CPlotColors.h>
Static Public Member Functions
static std::string getCopasiColorStr (size_t index)
static size_t getNumCopasiColors ()
Detailed Description
Definition at line 26 of file CPlotColors.h.
Member Function Documentation
std::string CPlotColors::getCopasiColorStr (size_t index) static
Definition at line 17 of file CPlotColors.cpp.
Referenced by COutputAssistant::createDefaultOutput(), CQPlotColors::getColor(), and Curve2DWidget::LoadFromCurveSpec().
 {
   index = index % 6;
   switch (index)
     {
       case 0: return "#FF0000";
       case 1: return "#0000FF";
       case 2: return "#00E600";
       case 3: return "#00BEF0";
       case 4: return "#F000FF";
       case 5: return "#F0C800";
     }
   return "auto";
 }
size_t CPlotColors::getNumCopasiColors () static
Definition at line 36 of file CPlotColors.cpp.
Referenced by Curve2DWidget::LoadFromCurveSpec().
 {
   return 6;
 }
The documentation for this class was generated from the following files:
CPlotColors.h
CPlotColors.cpp