COPASI API: CCopasiParameter Class Reference
CCopasiParameter Class Reference
#include <CCopasiParameter.h>
Classes
union Value
Public Types
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
virtual void print (std::ostream *ostream) const
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Attributes
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CCopasiParameter ()
Value createValue (const Value &value)
void deleteValue ()
Private Attributes
CCopasiParameter::Type mType
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiParameter &o)
bool operator== (const CCopasiParameter &lhs, const CCopasiParameter &rhs)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CCopasiParameter class. This class is used to describe parameters. This class is intended to be used with integration or optimization methods or reactions.
Created for COPASI by Stefan Hoops 2002
Definition at line 35 of file CCopasiParameter.h.
Member Enumeration Documentation
enum CCopasiParameter::Type
Enumerator
DOUBLE
UDOUBLE
INT
UINT
BOOL
GROUP
STRING
CN
KEY
FILE
EXPRESSION
INVALID
Definition at line 39 of file CCopasiParameter.h.
   {
     DOUBLE = 0,
     UDOUBLE,
     INT,
     UINT,
     BOOL,
     GROUP,
     STRING,
     CN,
     KEY,
     FILE,
     EXPRESSION,
     INVALID
   };
Constructor & Destructor Documentation
CCopasiParameter::CCopasiParameter () private
Default constructor
Definition at line 65 of file CCopasiParameter.cpp.
References mValue, and CCopasiParameter::Value::pVOID.
Referenced by CCopasiParameterGroup::addParameter(), and CCopasiParameterGroup::operator=().
                                   :
   CCopasiContainer("NoName", NULL, "Parameter"),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Parameter", this)),
   mType(INVALID),
   mSize(0),
   mValue(),
   mpValueReference(NULL)
 {mValue.pVOID = NULL;}
CCopasiParameter::CCopasiParameter (const CCopasiParameter & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CCopasiParameter & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 74 of file CCopasiParameter.cpp.
References createValue(), and mValue.
                                                                     :
   CCopasiContainer(src, pParent),
   mKey(CCopasiRootContainer::getKeyFactory()->add(src.getObjectType(), this)),
   mType(src.mType),
   mSize(0),
   mValue(),
   mpValueReference(NULL)
 {
   createValue(src.mValue);
 }
CCopasiParameter::CCopasiParameter (const std::string & name, const Type & type, const void * pValue = NULL, const CCopasiContainer * pParent = NULL, const std::string & objectType = "Parameter")
Specific constructor
Parameters
const string & name
const CCopasiParameter::Type & type
const void * pValue (default: NULL)
const CCopasiContainer * pParent (default: NULL)
const std::string & objectType (default: "Parameter")
Definition at line 86 of file CCopasiParameter.cpp.
References createValue(), mValue, and CCopasiParameter::Value::pVOID.
                                                                 :
   CCopasiContainer(name, pParent, objectType,
                    CCopasiObject::Container |
                    ((type == DOUBLE || type == UDOUBLE) ? CCopasiObject::ValueDbl :
                     ((type == INT || type == UINT) ? CCopasiObject::ValueInt :
                      ((type == STRING || type == CN || type == KEY || type == FILE || type == EXPRESSION) ? CCopasiObject::ValueString :
                       (type == BOOL) ? CCopasiObject::ValueBool : 0)))),
   mKey(CCopasiRootContainer::getKeyFactory()->add(objectType, this)),
   mType(type),
   mSize(0),
   mValue(),
   mpValueReference(NULL)
 {
   CCopasiParameter::Value value;
   value.pVOID = const_cast<void *>(pValue);
   mValue = createValue(value);
 }
CCopasiParameter::~CCopasiParameter () virtual
Destructor
Definition at line 108 of file CCopasiParameter.cpp.
References deleteValue(), CCopasiRootContainer::getKeyFactory(), CCopasiRootContainer::getRoot(), mKey, and CKeyFactory::remove().
 {
   if (CCopasiRootContainer::getRoot())
     CCopasiRootContainer::getKeyFactory()->remove(mKey);
   deleteValue();
 }
Member Function Documentation
CCopasiParameter::Value CCopasiParameter::createValue (const Value & value) private
Create or copy the value
Parameters
const CCopasiParameter::Value & value
Returns
CCopasiParameter::Value Value
Definition at line 429 of file CCopasiParameter.cpp.
References CCopasiContainer::addObjectReference(), BOOL, C_FLOAT64, C_INT32, CN, DOUBLE, EXPRESSION, FILE, GROUP, INT, INVALID, KEY, mpValueReference, mSize, mType, mValue, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pGROUP, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUINT, CCopasiParameter::Value::pVOID, STRING, UDOUBLE, UINT, CCopasiObject::ValueBool, CCopasiObject::ValueDbl, CCopasiObject::ValueInt, and CCopasiObject::ValueString.
Referenced by CCopasiParameter(), and operator=().
 {
   switch (mType)
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         mValue.pDOUBLE = new C_FLOAT64;
         if (value.pDOUBLE) * mValue.pDOUBLE = * value.pDOUBLE;
         mSize = sizeof(C_FLOAT64);
         mpValueReference = addObjectReference("Value", * mValue.pDOUBLE, CCopasiObject::ValueDbl);
         break;
       case CCopasiParameter::INT:
         mValue.pINT = new C_INT32;
         if (value.pINT) * mValue.pINT = * value.pINT;
         mSize = sizeof(C_INT32);
         mpValueReference = addObjectReference("Value", * mValue.pINT, CCopasiObject::ValueInt);
         break;
       case CCopasiParameter::UINT:
         mValue.pUINT = new unsigned C_INT32;
         if (value.pUINT) * mValue.pUINT = * value.pUINT;
         mSize = sizeof(unsigned C_INT32);
         mpValueReference = addObjectReference("Value", * mValue.pUINT, CCopasiObject::ValueInt);
         break;
       case CCopasiParameter::BOOL:
         mValue.pBOOL = new bool;
         if (value.pBOOL) * mValue.pBOOL = * value.pBOOL;
         mSize = sizeof(bool);
         mpValueReference = addObjectReference("Value", * mValue.pBOOL, CCopasiObject::ValueBool);
         break;
       case CCopasiParameter::STRING:
       case CCopasiParameter::KEY:
       case CCopasiParameter::FILE:
       case CCopasiParameter::EXPRESSION:
         if (value.pSTRING)
           mValue.pSTRING = new std::string(* value.pSTRING);
         else
           mValue.pSTRING = new std::string;
         mSize = sizeof(std::string);
         mpValueReference = addObjectReference("Value", * mValue.pSTRING, CCopasiObject::ValueString);
         break;
       case CCopasiParameter::CN:
         if (value.pCN)
           mValue.pCN = new CRegisteredObjectName(* value.pCN);
         else
           mValue.pCN = new CRegisteredObjectName;
         mSize = sizeof(CRegisteredObjectName);
         mpValueReference = addObjectReference("Value", * mValue.pCN, CCopasiObject::ValueString);
         break;
       case CCopasiParameter::GROUP:
         mValue.pGROUP = new std::vector< CCopasiParameter * >;
         mSize = sizeof(std::vector< CCopasiParameter * >);
         break;
       case CCopasiParameter::INVALID:
         mValue.pVOID = NULL;
         mSize = 0;
         break;
     }
   return mValue;
 }
void CCopasiParameter::deleteValue () private
Delete the value
Definition at line 509 of file CCopasiParameter.cpp.
References BOOL, CN, DOUBLE, EXPRESSION, fatalError, FILE, GROUP, INT, INVALID, KEY, mType, mValue, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pGROUP, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUINT, CCopasiParameter::Value::pVOID, STRING, UDOUBLE, and UINT.
Referenced by operator=(), and ~CCopasiParameter().
 {
   if (mValue.pVOID == NULL) return;
   switch (mType)
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         delete mValue.pDOUBLE;
         break;
       case CCopasiParameter::INT:
         delete mValue.pINT;
         break;
       case CCopasiParameter::UINT:
         delete mValue.pUINT;
         break;
       case CCopasiParameter::BOOL:
         delete mValue.pBOOL;
         break;
       case CCopasiParameter::STRING:
       case CCopasiParameter::KEY:
       case CCopasiParameter::FILE:
       case CCopasiParameter::EXPRESSION:
         delete mValue.pSTRING;
         break;
       case CCopasiParameter::CN:
         delete mValue.pCN;
         break;
       case CCopasiParameter::GROUP:
         delete mValue.pGROUP;
         break;
       case CCopasiParameter::INVALID:
         break;
       default:
         fatalError();
         break;
     }
   mValue.pVOID = NULL;
   return;
 }
CCopasiObjectName CCopasiParameter::getCN () const virtual
Retrieve the CN of the math container The math container provides values for the numerical values of model objects. For the CN mechanism to work properly it has to pretend to be the model.
Returns
CCopasiObjectName
Reimplemented from CCopasiObject.
Definition at line 412 of file CCopasiParameter.cpp.
References CCopasiObjectName::escape(), CCopasiObject::getCN(), CCopasiObject::getObjectParent(), CCopasiObject::getObjectType(), and CCopasiParameterGroup::getUniqueParameterName().
Referenced by CFixLocalReactionParameters::changeModel(), CSBMLExporter::createKineticLaw(), CSensProblem::initDebugProblem(), CSensMethod::initialize(), CSBMLExporter::replace_local_parameters(), SBMLImporter::sbmlId2CopasiCN(), and CEvaluationNodeObject::toAST().
 {
   CCopasiContainer * pObjectParent = getObjectParent();
   CCopasiParameterGroup * pGroup;
   if (pObjectParent != NULL &&
       (pGroup = dynamic_cast< CCopasiParameterGroup * >(pObjectParent)) != NULL)
     {
       return pObjectParent->getCN() + "," + CCopasiObjectName::escape(getObjectType()) + "=" + CCopasiObjectName::escape(pGroup->getUniqueParameterName(this));
     }
   return CCopasiObject::getCN();
 }
const std::string & CCopasiParameter::getKey () const virtual
Return the key of this model
Returns
string key
Reimplemented from CCopasiObject.
Definition at line 239 of file CCopasiParameter.cpp.
References mKey.
Referenced by CModelAnalyzer::checkReaction(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::ParameterGroupElement::end(), CODEExporter::exportKineticFunction(), CODEExporterBM::exportSingleParameter(), CODEExporterXPPAUT::exportSingleParameter(), CODEExporterC::exportSingleParameter(), CStochMethod::getAffects(), CCopasiParameterGroup::getKey(), CReaction::initializeParameters(), CReaction::isLocalParameter(), CODEExporterC::KineticFunction2ODEmember(), CReaction::setParameterValue(), CCopasiXMLParser::SourceParameterElement::start(), CCopasiXMLParser::ParameterElement::start(), and CModelParameter::updateModel().
 {return mKey;}
std::string CCopasiParameter::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
Overload display name. Special treatment for reaction parameters to provide a shorter display.
Reimplemented from CCopasiObject.
Definition at line 560 of file CCopasiParameter.cpp.
References CCopasiObject::getObjectAncestor(), getObjectDisplayName(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), getType(), CCopasiParameterGroup::getUniqueParameterName(), and GROUP.
Referenced by CExperiment::compile(), getObjectDisplayName(), CFitProblem::printResult(), and CExperiment::printResult().
 {
   // if one of the ancestors is a reaction and the parameter is not a group
   // it is (hopefully) a kinetic parameter
   CCopasiObject* tmp = this->getObjectAncestor("Reaction");
   if (tmp && getType() != GROUP)
     {
       return tmp->getObjectDisplayName(regular, richtext) + "." + getObjectName();
     }
   CCopasiContainer * pObjectParent = getObjectParent();
   CCopasiParameterGroup * pGroup;
   if (pObjectParent != NULL &&
       (pGroup = dynamic_cast< CCopasiParameterGroup * >(pObjectParent)) != NULL)
     {
       std::string DisplayName = pGroup->getObjectDisplayName(regular, richtext);
       if (DisplayName.length() >= 2 &&
           (DisplayName.substr(DisplayName.length() - 2) == "[]"))
         {
           DisplayName.insert(DisplayName.length() - 1, pGroup->getUniqueParameterName(this));
         }
       else
         {
           if ((DisplayName.length() != 0) && (DisplayName[DisplayName.length() - 1] != '.'))
             {
               DisplayName += ".";
             }
           DisplayName += pGroup->getUniqueParameterName(this);
         }
       if (getType() == GROUP)
         {
           DisplayName += "[]";
         }
       return DisplayName;
     }
   return CCopasiObject::getObjectDisplayName(regular, richtext);
 }
const CCopasiParameter::Type & CCopasiParameter::getType (void) const
Retrieve the type of the parameter.
Returns
CCopasiParameter::Type & type
Definition at line 256 of file CCopasiParameter.cpp.
References mType.
Referenced by CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::assertParameter(), CQProgressItemBar::destroy(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::ParameterGroupElement::end(), CCopasiXMLParser::COPASIElement::end(), getObjectDisplayName(), CScanProblem::getScanItem(), CCopasiParameterGroup::getType(), CQProgressItemText::reset(), CQProgressItemBar::reset(), and CCopasiXMLInterface::saveParameter().
 {return mType;}
const CCopasiParameter::Value & CCopasiParameter::getValue () const
Retrieve the private value of the parameter.
Returns
const CCopasiParameter::Value & Value
Definition at line 247 of file CCopasiParameter.cpp.
References mValue.
Referenced by CLyapWolfMethod::calculate(), CHybridMethod::calculateAmu(), CFixLocalReactionParameters::changeModel(), CFunctionAnalyzer::constructCallParametersActualValues(), CSEDMLExporter::createScanTask(), CSensMethod::CSensMethod(), CSensProblem::CSensProblem(), CTrajectoryTask::CTrajectoryTask(), CTSSATask::CTSSATask(), CFitProblem::elevateChildren(), CFitItem::elevateChildren(), COptProblem::elevateChildren(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::TaskElement::end(), CCopasiXMLParser::COPASIElement::end(), CODEExporter::exportReacParamsAndFuncs(), CScanProblem::fixBuild81(), CPlotItem::getActivity(), CScanProblem::getContinueFromCurrentState(), CHybridMethodODE45::getDefaultAtol(), CHybridMethodLSODA::getDefaultAtol(), CScanProblem::getOutputInSubtask(), CSteadyStateMethod::getStabilityResolution(), CScanProblem::getSubtask(), CLNAProblem::getSubTask(), CMCAProblem::getSubTask(), CCopasiParameterGroup::getValue(), SEDMLImporter::importTasks(), CQPreferenceDialog::init(), CQProgressItemText::initFromProcessReportItem(), CQProgressItemBar::initFromProcessReportItem(), COptMethodEP::initialize(), COptMethodSteepestDescent::initialize(), CRandomSearch::initialize(), COptMethodDE::initialize(), COptMethodSRES::initialize(), COptMethodGA::initialize(), COptMethodPS::initialize(), COptMethodGASR::initialize(), COptMethodHookeJeeves::initialize(), COptMethodLevenbergMarquardt::initialize(), COptMethodNelderMead::initialize(), COptMethodSA::initialize(), COptMethodCoranaWalk::initialize(), COptMethodPraxis::initialize(), COptMethodSS::initialize(), CTSSATask::initialize(), CTrajectoryTask::initialize(), CNewtonMethod::initialize(), CCrossSectionTask::initialize(), CTSSAMethod::initializeIntegrationsParameter(), CExperimentObjectMap::CDataColumn::initializeParameter(), CRecentFiles::initializeParameter(), CSteadyStateMethod::initializeParameter(), CMIRIAMResource::initializeParameter(), CLyapProblem::initializeParameter(), CNewtonMethod::initializeParameter(), CTrajectoryProblem::initializeParameter(), CTSSAProblem::initializeParameter(), CMCAMethod::initializeParameter(), CCrossSectionProblem::initializeParameter(), CHybridMethodODE45::initializeParameter(), CLyapWolfMethod::initializeParameter(), CTauLeapMethod::initializeParameter(), CStochMethod::initializeParameter(), CConfigurationFile::initializeParameter(), COptItem::initializeParameter(), CFitProblem::initializeParameter(), CLsodaMethod::initializeParameter(), CMIRIAMResources::initializeParameter(), CCrossValidationSet::initializeParameter(), CTrajectoryMethodDsaLsodar::initializeParameter(), COptProblem::initializeParameter(), CHybridMethod::initializeParameter(), CHybridMethodLSODA::initializeParameter(), CExperiment::initializeParameter(), CHybridMethod::initMethod(), CHybridMethodODE45::initMethod(), CHybridMethodLSODA::initMethod(), CSteadyStateProblem::isJacobianRequested(), CPlotSpecification::isLogX(), CPlotSpecification::isLogY(), CSteadyStateProblem::isStabilityAnalysisRequested(), CLNAProblem::isSteadyStateRequested(), CMCAProblem::isSteadyStateRequested(), CNewtonMethod::isValidProblem(), CHybridMethod::isValidProblem(), CHybridMethodLSODA::isValidProblem(), CStochDirectMethod::isValidProblem(), CTrajAdaptiveSA::isValidProblem(), CLyapWolfMethod::isValidProblem(), CStochMethod::isValidProblem(), CTrajectoryMethodDsaLsodar::isValidProblem(), CSteadyStateProblem::load(), CTrajectoryTask::load(), CReactionInterface::loadMappingAndValues(), CExperiment::operator=(), COptMethodEP2::optimise(), COptMethodHGASA::optimise(), CHybridMethod::partitionSystem(), CHybridMethodLSODA::partitionSystem(), CCSPMethod::predifineAnnotation(), CModel::printParameterOverview(), CModelParameter::refreshFromModel(), CSBMLExporter::replace_local_parameters(), CCopasiXMLInterface::saveParameter(), CTrajectoryTask::setMethodType(), CCrossSectionTask::setMethodType(), CExperimentObjectMap::CDataColumn::setObjectCN(), CExperimentObjectMap::CDataColumn::setScale(), CPlotItem::setType(), CHybridMethod::setupPartition(), CHybridMethodLSODA::setupPartition(), CQPreferenceDialog::slotBtnOk(), CILDMMethod::start(), CILDMModifiedMethod::start(), CTauLeapMethod::start(), CStochDirectMethod::start(), CCSPMethod::start(), CLyapWolfMethod::start(), CTrajAdaptiveSA::start(), CStochMethod::start(), and SteadyStateWidget::taskFinishedEvent().
 {return mValue;}
CCopasiParameter::Value & CCopasiParameter::getValue ()
Retrieve the private value of the parameter.
Returns
CCopasiParameter::Value & Value
Definition at line 249 of file CCopasiParameter.cpp.
References mValue.
 {return mValue;}
void * CCopasiParameter::getValuePointer () const virtual
Retrieve a pointer to the value of the object
Reimplemented from CCopasiObject.
Definition at line 426 of file CCopasiParameter.cpp.
References mValue, and CCopasiParameter::Value::pVOID.
Referenced by CSensMethod::calculate_one_level(), CExperiment::compile(), CSensMethod::do_target_calculation(), and CSensMethod::scaling_variables().
 {return const_cast<void *>(mValue.pVOID);}
CCopasiObject * CCopasiParameter::getValueReference () const
Retrieve the object which represents the value of the parameter
Returns
CCopasiObject * pValueReference
Definition at line 251 of file CCopasiParameter.cpp.
References mpValueReference.
Referenced by CModel::buildInitialSequence(), CModel::convert2NonReversible(), CObjectLists::getListOfConstObjects(), CTrajectoryProblem::initObjects(), CTSSAProblem::initObjects(), CModel::removeLocalReactionParameter(), SBMLImporter::setInitialValues(), test000058::test_bug1025_1(), test000058::test_bug1025_6(), test000059::test_unique_id_10(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), test000059::test_unique_id_4(), test000059::test_unique_id_7(), and test000059::test_unique_id_9().
 {
   return mpValueReference;
 }
bool CCopasiParameter::isValidValue (const C_FLOAT64 & value) const
Check whether the value corresponds to the type
Parameters
const C_FLOAT64 & value
Returns
bool isValidValue
Definition at line 259 of file CCopasiParameter.cpp.
References DOUBLE, mType, and UDOUBLE.
Referenced by CCopasiParameterGroup::addParameter(), and setValue().
 {
   if ((mType != CCopasiParameter::DOUBLE &&
        mType != CCopasiParameter::UDOUBLE) ||
       (mType == CCopasiParameter::UDOUBLE &&
        value < 0.0)) return false;
   return true;
 }
bool CCopasiParameter::isValidValue (const C_INT32 & value) const
Check whether the value corresponds to the type
Parameters
const C_INT32 & value
Returns
bool isValidValue
Definition at line 269 of file CCopasiParameter.cpp.
References INT, and mType.
 {
   if (mType != CCopasiParameter::INT) return false;
   return true;
 }
bool CCopasiParameter::isValidValue (const unsigned C_INT32 & value) const
Check whether the value corresponds to the type
Parameters
const unsigned C_INT32 & value
Returns
bool isValidValue
Definition at line 276 of file CCopasiParameter.cpp.
References mType, and UINT.
 {
   if (mType != CCopasiParameter::UINT) return false;
   return true;
 }
bool CCopasiParameter::isValidValue (const bool & value) const
Check whether the value corresponds to the type
Parameters
const bool & value
Returns
bool isValidValue
bool CCopasiParameter::isValidValue (const std::string & value) const
Check whether the value corresponds to the type
Parameters
const std::string & value
Returns
bool isValidValue
Definition at line 290 of file CCopasiParameter.cpp.
References EXPRESSION, FILE, CKeyFactory::isValidKey(), KEY, mType, and STRING.
 {
   if (mType == CCopasiParameter::KEY)
     return CKeyFactory::isValidKey(value);
   if (mType != CCopasiParameter::STRING &&
       mType != CCopasiParameter::FILE &&
       mType != CCopasiParameter::EXPRESSION) return false;
   return true;
 }
bool CCopasiParameter::isValidValue (const CCopasiObjectName & value) const
Check whether the value corresponds to the type
Parameters
const CRegisteredObjectName & value
Returns
bool isValidValue
bool CCopasiParameter::isValidValue (const std::vector< CCopasiParameter * > & value) const
Check whether the value corresponds to the type
Parameters
const CCopasiParameterGroup::parameterGroup & value
Returns
bool isValidValue
CCopasiParameter & CCopasiParameter::operator= (const CCopasiParameter & rhs)
Assignment operator
Parameters
const CCopasiParameter & rhs
Returns
CCopasiParameter & lhs
Definition at line 116 of file CCopasiParameter.cpp.
References BOOL, CN, createValue(), deleteValue(), DOUBLE, EXPRESSION, FILE, CCopasiObject::getObjectName(), GROUP, INT, INVALID, KEY, mType, mValue, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pSTRING, CCopasiObject::setObjectName(), STRING, UDOUBLE, and UINT.
 {
   if (getObjectName() != rhs.getObjectName())
     setObjectName(rhs.getObjectName());
   switch (rhs.mType)
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         if (mType != DOUBLE &&
             mType != UDOUBLE)
           {
             deleteValue();
             mType = rhs.mType;
             createValue(rhs.mValue);
           }
         else
           {
             mType = rhs.mType;
             *mValue.pDOUBLE = *rhs.mValue.pDOUBLE;
           }
         break;
       case CCopasiParameter::INT:
       case CCopasiParameter::UINT:
         if (mType != INT &&
             mType != UINT)
           {
             deleteValue();
             mType = rhs.mType;
             createValue(rhs.mValue);
           }
         else
           {
             mType = rhs.mType;
             *mValue.pINT = *rhs.mValue.pINT;
           }
         break;
       case CCopasiParameter::BOOL:
         if (mType != BOOL)
           {
             deleteValue();
             mType = BOOL;
             createValue(rhs.mValue);
           }
         else
           {
             *mValue.pBOOL = *rhs.mValue.pBOOL;
           }
         break;
       case CCopasiParameter::STRING:
       case CCopasiParameter::KEY:
       case CCopasiParameter::FILE:
       case CCopasiParameter::EXPRESSION:
         if (mType != STRING &&
             mType != KEY &&
             mType != FILE &&
             mType != EXPRESSION)
           {
             deleteValue();
             mType = rhs.mType;
             createValue(rhs.mValue);
           }
         else
           {
             mType = rhs.mType;
             *mValue.pSTRING = *rhs.mValue.pSTRING;
           }
         break;
       case CCopasiParameter::CN:
         if (mType != CN)
           {
             deleteValue();
             mType = CN;
             createValue(rhs.mValue);
           }
         else
           {
             *mValue.pCN = *rhs.mValue.pCN;
           }
         break;
       case CCopasiParameter::GROUP:
         if (mType != GROUP)
           {
             deleteValue();
             mType = GROUP;
             createValue(rhs.mValue);
           }
         *static_cast<CCopasiParameterGroup *>(this) =
           *static_cast<const CCopasiParameterGroup *>(&rhs);
         break;
       case CCopasiParameter::INVALID:
         if (mType != INVALID)
           {
             deleteValue();
             mType = INVALID;
             createValue(rhs.mValue);
           }
         break;
     }
   return *this;
 }
void CCopasiParameter::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Reimplemented in CCopasiParameterGroup, COptProblem, CCopasiMethod, CCopasiProblem, CSensProblem, CCrossSectionProblem, CLNAProblem, CMCAProblem, CFitProblem, and COscillationProblem.
Definition at line 316 of file CCopasiParameter.cpp.
 {*ostream << *this;}
template<class CType > bool CCopasiParameter::setValue (const CType & value) inline
Set the value of the parameter
Parameters
const const CType & value
Returns
bool isValidValue
Definition at line 164 of file CCopasiParameter.h.
References isValidValue(), mValue, and CCopasiParameter::Value::pVOID.
Referenced by CCopasiParameterGroup::addParameter(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::ParameterTextElement::end(), CCopasiXMLParser::COPASIElement::end(), CScanProblem::fixBuild81(), CExperiment::initializeParameter(), SBMLImporter::sbmlId2CopasiCN(), CCopasiParameterGroup::setValue(), CQPreferenceDialog::slotBtnOk(), test000087::test_simulate_reaction_flux_reference_1(), and CModelParameter::updateModel().
   {
     if (!isValidValue(value)) return false;
     *(CType *) mValue.pVOID = value;
     return true;
   }
bool CCopasiParameter::setValue (const std::vector< CCopasiParameter * > & value)
Set the value of the parameter when the origin is a parameter group. This function is currently not implemented and creates a fatalError when called.
Parameters
const CCopasiParameter::parameterGroup& value
Returns
bool false
Definition at line 241 of file CCopasiParameter.cpp.
References fatalError.
 {
   fatalError();
   return false;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiParameter & o) friend
Output stream operator
Parameters
ostream & os
const CCopasiParameter & A
Returns
ostream & os
Definition at line 319 of file CCopasiParameter.cpp.
 {
   os << "    " << o.getObjectName() << ": ";
   switch (o.mType)
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         os << * o.mValue.pDOUBLE;
         break;
       case CCopasiParameter::INT:
         os << * o.mValue.pINT;
         break;
       case CCopasiParameter::UINT:
         os << * o.mValue.pUINT;
         break;
       case CCopasiParameter::BOOL:
         os << * o.mValue.pBOOL;
         break;
       case CCopasiParameter::STRING:
       case CCopasiParameter::KEY:
       case CCopasiParameter::FILE:
       case CCopasiParameter::EXPRESSION:
         os << * o.mValue.pSTRING;
         break;
       case CCopasiParameter::CN:
         os << * o.mValue.pCN;
         break;
       case CCopasiParameter::GROUP:
       case CCopasiParameter::INVALID:
         break;
     }
   return os;
 }
bool operator== (const CCopasiParameter & lhs, const CCopasiParameter & rhs) friend
Comparison operator
Parameters
const CCopasiParameter & lhs
const CCopasiParameter & rhs
Returns
bool equal
Definition at line 361 of file CCopasiParameter.cpp.
 {
   if (lhs.getObjectName() != rhs.getObjectName()) return false;
   if (lhs.mType != rhs.mType) return false;
   switch (lhs.mType)
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         return *lhs.mValue.pDOUBLE == *rhs.mValue.pDOUBLE;
         break;
       case CCopasiParameter::INT:
         return *lhs.mValue.pINT == *rhs.mValue.pINT;
         break;
       case CCopasiParameter::UINT:
         return *lhs.mValue.pUINT == *rhs.mValue.pUINT;
         break;
       case CCopasiParameter::BOOL:
         return *lhs.mValue.pBOOL == *rhs.mValue.pBOOL;
         break;
       case CCopasiParameter::STRING:
       case CCopasiParameter::KEY:
       case CCopasiParameter::FILE:
       case CCopasiParameter::EXPRESSION:
         return *lhs.mValue.pSTRING == *rhs.mValue.pSTRING;
         break;
       case CCopasiParameter::CN:
         return *lhs.mValue.pCN == *rhs.mValue.pCN;
         break;
       case CCopasiParameter::GROUP:
         return *static_cast<const CCopasiParameterGroup *>(&lhs) ==
                *static_cast<const CCopasiParameterGroup *>(&rhs);
         break;
       case CCopasiParameter::INVALID:
       default:
         return !memcmp(lhs.mValue.pVOID, rhs.mValue.pVOID, lhs.mSize);
         break;
     }
   return false;
 }
Member Data Documentation
std::string CCopasiParameter::mKey protected
The key of the parameter.
Definition at line 86 of file CCopasiParameter.h.
Referenced by getKey(), CExperiment::initializeParameter(), and ~CCopasiParameter().
CCopasiObject* CCopasiParameter::mpValueReference mutable protected
A pointer to the object reference for the value
Definition at line 108 of file CCopasiParameter.h.
Referenced by createValue(), and getValueReference().
size_t CCopasiParameter::mSize protected
The size allocated for the value of the parameter.
Definition at line 98 of file CCopasiParameter.h.
Referenced by createValue(), and operator==().
CCopasiParameter::Type CCopasiParameter::mType private
The type of the parameter
Definition at line 92 of file CCopasiParameter.h.
Referenced by createValue(), deleteValue(), getType(), isValidValue(), operator<<(), operator=(), and operator==().
Value CCopasiParameter::mValue protected
A pointer to the value of the parameter.
Definition at line 103 of file CCopasiParameter.h.
Referenced by CCopasiParameterGroup::addParameter(), CCopasiParameterGroup::beginIndex(), CCopasiParameter(), CCopasiParameterGroup::clear(), CProcessReportItem::CProcessReportItem(), createValue(), deleteValue(), CExperimentSet::elevateChildren(), CExperimentObjectMap::elevateChildren(), CCopasiParameterGroup::endIndex(), CCopasiParameterGroup::getIndex(), CExperimentObjectMap::getLastNotIgnoredColumn(), CCopasiParameterGroup::getObject(), CCopasiParameterGroup::getParameter(), CCopasiParameterGroup::getUniqueParameterName(), getValue(), getValuePointer(), operator<<(), operator=(), operator==(), CHybridMethod::partitionSystem(), CHybridMethodLSODA::partitionSystem(), CCopasiParameterGroup::removeParameter(), CExperimentObjectMap::setNumCols(), CHybridMethod::setupPartition(), CHybridMethodLSODA::setupPartition(), setValue(), CCopasiParameterGroup::size(), and CProcessReportItem::~CProcessReportItem().
const std::string CCopasiParameter::TypeName static
Initial value:
=
{
  "float",
  "unsigned float",
  "integer",
  "unsigned integer",
  "bool",
  "group",
  "string",
  "common name",
  "key",
  "file",
  "expression",
  ""
}
String literals for the GUI to display type names of parameters known to COPASI.
CCopasiParameter class. This class is used to describe method paramters. This class is intended to be used with integration or optimization methods.
Created for Copasi by Stefan Hoops 2002
Definition at line 75 of file CCopasiParameter.h.
const char * CCopasiParameter::XMLType static
Initial value:
=
{
  "float",
  "unsignedFloat",
  "integer",
  "unsignedInteger",
  "bool",
  "group",
  "string",
  "cn",
  "key",
  "file",
  "expression",
  NULL
}
XML type names of parameters known to COPASI.
Definition at line 80 of file CCopasiParameter.h.
Referenced by CCopasiXMLInterface::saveParameter(), CCopasiXMLParser::ParameterElement::start(), and CCopasiXMLParser::ParameterTextElement::start().
The documentation for this class was generated from the following files:
CCopasiParameter.h
CCopasiParameter.cpp