COPASI API: CRandomSearch Class Reference
CRandomSearch Class Reference
#include <CRandomSearch.h>
Public Member Functions
CRandomSearch (const CRandomSearch &src)
virtual bool optimise ()
virtual ~CRandomSearch ()
Public Member Functions inherited from COptMethod
COptMethod (const COptMethod &src, const CCopasiContainer *pParent=NULL)
bool isBounded (void)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (COptProblem *problem)
virtual ~COptMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
CRandomSearch ()
bool evaluate (const CVector< C_FLOAT64 > &individual)
size_t fittest ()
virtual bool initialize ()
void initObjects ()
Private Attributes
C_FLOAT64 mBestValue
unsigned C_INT32 mCurrentIteration
CVector< C_FLOAT64 > mIndividual
unsigned C_INT32 mIterations
CRandom * mpRandom
C_FLOAT64 mValue
size_t mVariableSize
Friends
COptMethod * COptMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from COptMethod
static COptMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::RandomSearch)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from COptMethod
virtual bool cleanup ()
COptMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from COptMethod
const bool mBounds
const std::vector< COptItem * > * mpOptContraints
const std::vector< COptItem * > * mpOptItem
COptProblem * mpOptProblem
COptTask * mpParentTask
const std::vector
< UpdateMethod * > * mpSetCalculateVariable
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 36 of file CRandomSearch.h.
Constructor & Destructor Documentation
CRandomSearch::CRandomSearch () private
Default Constructor
Definition at line 48 of file CRandomSearch.cpp.
References CCopasiParameterGroup::addParameter(), C_INT32, initObjects(), CRandom::mt19937, and CCopasiParameter::UINT.
                             :
     COptMethod(CCopasiTask::optimization, CCopasiMethod::RandomSearch)
 {
   addParameter("Number of Iterations", CCopasiParameter::UINT, (unsigned C_INT32) 100000);
   addParameter("Random Number Generator", CCopasiParameter::UINT, (unsigned C_INT32) CRandom::mt19937);
   addParameter("Seed", CCopasiParameter::UINT, (unsigned C_INT32) 0);
   initObjects();
 }
CRandomSearch::CRandomSearch (const CRandomSearch & src)
Copy Constructor
Parameters
const CRandomSearch & src
Definition at line 58 of file CRandomSearch.cpp.
References initObjects().
                                                      :
     COptMethod(src)
 {initObjects();}
CRandomSearch::~CRandomSearch () virtual
Destructor
Definition at line 65 of file CRandomSearch.cpp.
References COptMethod::cleanup().
 {//*** added similar to coptga
   cleanup();
 }
Member Function Documentation
bool CRandomSearch::evaluate (const CVector< C_FLOAT64 > & individual) private
Evaluate the fitness of one individual
Parameters
const CVector< C_FLOAT64 > & individual
Returns
bool continue
Definition at line 208 of file CRandomSearch.cpp.
References COptProblem::calculate(), COptProblem::checkFunctionalConstraints(), COptProblem::getCalculateValue(), COptMethod::mpOptProblem, and mValue.
Referenced by optimise().
 {
   bool Continue = true;
   // We do not need to check whether the parametric constraints are fulfilled
   // since the parameters are created within the bounds.
   // evaluate the fitness
   Continue = mpOptProblem->calculate();
   // check wheter the functional constraints are fulfilled
   if (!mpOptProblem->checkFunctionalConstraints())
     mValue = std::numeric_limits<C_FLOAT64>::infinity();
   else
     mValue = mpOptProblem->getCalculateValue();
   return Continue;
 }
size_t CRandomSearch::fittest () private
Find the best individual at this generation
Returns
size_t fittest
bool CRandomSearch::initialize () private virtual
Initialize arrays and pointer.
Returns
bool success
Optimizer Function Returns: true if properly initialized should return a boolean
Reimplemented from COptMethod.
Definition at line 80 of file CRandomSearch.cpp.
References COptMethod::cleanup(), CRandom::createGenerator(), CCopasiParameter::getValue(), COptMethod::initialize(), mBestValue, mIndividual, mIterations, COptMethod::mpOptItem, mpRandom, mVariableSize, CCopasiParameter::Value::pUINT, and CVector< CType >::resize().
Referenced by optimise().
 {
   cleanup();
   if (!COptMethod::initialize()) return false;
   mIterations = * getValue("Number of Iterations").pUINT;
   mpRandom = CRandom::createGenerator(* (CRandom::Type *) getValue("Random Number Generator").pUINT,
                                       * getValue("Seed").pUINT);
   mBestValue = std::numeric_limits<C_FLOAT64>::infinity();
   mVariableSize = mpOptItem->size();
   mIndividual.resize(mVariableSize);
   return true;
 }
void CRandomSearch::initObjects () private
Initialize contained objects.
Definition at line 70 of file CRandomSearch.cpp.
References CCopasiContainer::addObjectReference(), mCurrentIteration, and CCopasiObject::ValueInt.
Referenced by CRandomSearch().
 {
   addObjectReference("Current Iteration", mCurrentIteration, CCopasiObject::ValueInt);
 }
bool CRandomSearch::optimise (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback.
Optimizer Function Returns: nothing should return a boolean
Reimplemented from COptMethod.
Definition at line 104 of file CRandomSearch.cpp.
References C_FLOAT64, C_INT32, COptItem::checkConstraint(), COptItem::checkLowerBound(), COptItem::checkUpperBound(), COutputInterface::DURING, evaluate(), COptItem::getLowerBoundValue(), COptItem::getRandomValue(), COptItem::getStartValue(), COptItem::getUpperBoundValue(), initialize(), mBestValue, mCurrentIteration, min, mIndividual, mIterations, COptMethod::mpOptProblem, COptMethod::mpParentTask, mpRandom, mValue, mVariableSize, CCopasiTask::output(), and COptProblem::setSolution().
 {
   bool Continue = true;
   if (!initialize()) return false;
   unsigned C_INT32 j;
   // current value is the initial guess
   for (j = 0; j < mVariableSize; j++)
     {
       C_FLOAT64 & mut = mIndividual[j];
       COptItem & OptItem = *(*mpOptItem)[j];
       mut = OptItem.getStartValue();
       // force it to be within the bounds
       switch (OptItem.checkConstraint(mut))
         {
           case - 1:
             mut = *OptItem.getLowerBoundValue();
             break;
           case 1:
             mut = *OptItem.getUpperBoundValue();
             break;
         }
       // We need to set the value here so that further checks take
       // account of the value.
       (*(*mpSetCalculateVariable)[j])(mut);
     }
   Continue = evaluate(mIndividual);
   mBestValue = mValue;
   Continue = mpOptProblem->setSolution(mBestValue, mIndividual);
   // We found a new best value lets report it.
   //if (mpReport) mpReport->printBody();
   mpParentTask->output(COutputInterface::DURING);
   for (mCurrentIteration = 1; mCurrentIteration < mIterations && Continue; mCurrentIteration++)
     {
       for (j = 0; j < mVariableSize && Continue; j++)
         {
           // CALCULATE lower and upper bounds
           COptItem & OptItem = *(*mpOptItem)[j];
           C_FLOAT64 & mut = mIndividual[j];
           mut = OptItem.getRandomValue(mpRandom);
           // force it to be within the bounds
           switch (OptItem.checkConstraint(mut))
             {
               case - 1:
                 mut = *OptItem.getLowerBoundValue();
                 if (!OptItem.checkLowerBound(mut)) // Inequality
                   {
                     if (mut == 0.0)
                       mut = std::numeric_limits< C_FLOAT64 >::min();
                     else
                       mut += mut * std::numeric_limits< C_FLOAT64 >::epsilon();
                   }
                 break;
               case 1:
                 mut = *OptItem.getUpperBoundValue();
                 if (!OptItem.checkUpperBound(mut)) // Inequality
                   {
                     if (mut == 0.0)
                       mut = - std::numeric_limits< C_FLOAT64 >::min();
                     else
                       mut -= mut * std::numeric_limits< C_FLOAT64 >::epsilon();
                   }
                 break;
             }
           // We need to set the value here so that further checks take
           // account of the value.
           (*(*mpSetCalculateVariable)[j])(mut);
         }
       Continue = evaluate(mIndividual);
       // COMPARE
       if (mValue < mBestValue)
         {
           mBestValue = mValue;
           Continue = mpOptProblem->setSolution(mBestValue, mIndividual);
           // We found a new best value lets report it.
           //if (mpReport) mpReport->printBody();
           mpParentTask->output(COutputInterface::DURING);
         }
     }
   return true;
 }
Friends And Related Function Documentation
COptMethod* COptMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
C_FLOAT64 CRandomSearch::mBestValue private
The best value found so far.
Definition at line 104 of file CRandomSearch.h.
Referenced by initialize(), and optimise().
unsigned C_INT32 CRandomSearch::mCurrentIteration private
The current iteration
Definition at line 79 of file CRandomSearch.h.
Referenced by initObjects(), and optimise().
CVector<C_FLOAT64> CRandomSearch::mIndividual private
a vector of the number of individuals.
Definition at line 84 of file CRandomSearch.h.
Referenced by initialize(), and optimise().
unsigned C_INT32 CRandomSearch::mIterations private
number of iterations
Definition at line 74 of file CRandomSearch.h.
Referenced by initialize(), and optimise().
CRandom* CRandomSearch::mpRandom private
a pointer to the randomnumber generator.
Definition at line 94 of file CRandomSearch.h.
Referenced by initialize(), and optimise().
C_FLOAT64 CRandomSearch::mValue private
array of values of objective function f/ individuals
Definition at line 89 of file CRandomSearch.h.
Referenced by evaluate(), and optimise().
size_t CRandomSearch::mVariableSize private
*** Perhaps this is actually not needed ****number of parameters
Definition at line 99 of file CRandomSearch.h.
Referenced by initialize(), and optimise().
The documentation for this class was generated from the following files:
CRandomSearch.h
CRandomSearch.cpp