COPASI API: CLabel Class Reference
CLabel Class Reference
#include <CLabel.h>
Public Member Functions
void adaptToHeight (const double &h)
CLabel ()
CLabel (const CLTextGlyph &tg)
CLabel (const CLabel &l)
C_FLOAT64 getOrigHeight ()
C_FLOAT64 getOrigWidth ()
virtual std::string getText () const
virtual void scale (const double &scaleFactor)
void scalePosition (const double &hz)
Public Member Functions inherited from CLTextGlyph
void clearText ()
virtual CLGraphicalObject * clone () const
CLTextGlyph (const std::string &name="TextGlyph", const CCopasiContainer *pParent=NULL)
CLTextGlyph (const CLTextGlyph &src, const CCopasiContainer *pParent=NULL)
CLTextGlyph (const TextGlyph &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
void exportReferenceToSBML (TextGlyph *g, const std::map< const CLBase *, const SBase * > &layoutmap) const
virtual void exportToSBML (TextGlyph *g, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
CLGraphicalObject * getGraphicalObject () const
const std::string & getGraphicalObjectKey () const
bool isTextSet () const
CLTextGlyph & operator= (const CLTextGlyph &rhs)
void print (std::ostream *ostream) const
void setGraphicalObjectKey (const std::string &k)
void setText (const std::string &t)
Public Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const std::string &name="GraphicalObject", const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const CLGraphicalObject &src, const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
const CLBoundingBox & getBoundingBox () const
CLBoundingBox & getBoundingBox ()
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CCopasiObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
virtual void moveBy (const CLPoint &p)
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void print (std::ostream *ostream) const
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initOrigValues ()
Private Attributes
C_FLOAT64 orig_height
C_FLOAT64 orig_width
C_FLOAT64 orig_x
C_FLOAT64 orig_y
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CLTextGlyph
std::string mGraphicalObjectKey
bool mIsTextSet
std::string mText
Protected Attributes inherited from CLGraphicalObject
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 27 of file CLabel.h.
Constructor & Destructor Documentation
CLabel::CLabel ()
Definition at line 25 of file CLabel.cpp.
References initOrigValues().
     : CLTextGlyph()
 {
   initOrigValues();
 }
CLabel::CLabel (const CLTextGlyph & tg)
Definition at line 31 of file CLabel.cpp.
References initOrigValues().
     : CLTextGlyph(tg)
 {
   initOrigValues();
 }
CLabel::CLabel (const CLabel & l)
Definition at line 37 of file CLabel.cpp.
References initOrigValues().
     : CLTextGlyph(l)
 {
   initOrigValues();
 }
Member Function Documentation
void CLabel::adaptToHeight (const double & h)
Definition at line 62 of file CLabel.cpp.
References C_FLOAT64, CLBoundingBox::getDimensions(), CLDimensions::getHeight(), CLDimensions::getWidth(), CLGraphicalObject::mBBox, and CLBoundingBox::setDimensions().
 {
   C_FLOAT64 scaleFactor = h / mBBox.getDimensions().getHeight();
   C_FLOAT64 w = mBBox.getDimensions().getWidth() * scaleFactor;
   mBBox.setDimensions(CLDimensions(w, h));
 }
C_FLOAT64 CLabel::getOrigHeight () inline
Definition at line 43 of file CLabel.h.
References orig_height.
 {return this->orig_height;}
C_FLOAT64 CLabel::getOrigWidth () inline
Definition at line 44 of file CLabel.h.
References orig_width.
 {return this->orig_width;}
std::string CLabel::getText () const virtual
Since labels are not part of the model, we can't use the new method for getting the text but have to fall back to the old behavior. Hopefully I can get rid of this implementation sonner than later.
Reimplemented from CLTextGlyph.
Definition at line 80 of file CLabel.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectName(), CLTextGlyph::mIsTextSet, CLGraphicalObject::mModelObjectKey, and CLTextGlyph::mText.
 {
   if (mIsTextSet)
     {
       return mText;
     }
   else
     {
       CCopasiObject* pObject = CCopasiRootContainer::getKeyFactory()->get(this->mModelObjectKey);
       if (pObject)
         {
           return pObject->getObjectName();
         }
       else
         {
           return "unset";
         }
     }
 }
void CLabel::initOrigValues () private
Definition at line 43 of file CLabel.cpp.
References CLGraphicalObject::getHeight(), CLGraphicalObject::getWidth(), CLGraphicalObject::getX(), CLGraphicalObject::getY(), orig_height, orig_width, orig_x, and orig_y.
Referenced by CLabel().
 {
   orig_x = this->getX();
   orig_y = this->getY();
   orig_width = this->getWidth();
   orig_height = this->getHeight();
 }
void CLabel::scale (const double & scaleFactor) virtual
Definition at line 52 of file CLabel.cpp.
References orig_height, orig_width, orig_x, orig_y, CLGraphicalObject::setHeight(), CLGraphicalObject::setWidth(), CLGraphicalObject::setX(), and CLGraphicalObject::setY().
 {
   this->setX(this->orig_x * scaleFactor);
   this->setY(this->orig_y * scaleFactor);
   this->setWidth(this->orig_width * scaleFactor);
   this->setHeight(this->orig_height * scaleFactor);
 }
void CLabel::scalePosition (const double & hz)
Definition at line 69 of file CLabel.cpp.
References CLBoundingBox::getPosition(), CLPoint::getX(), CLPoint::getY(), CLGraphicalObject::mBBox, CLPoint::setX(), and CLPoint::setY().
 {
   this->mBBox.getPosition().setX(this->mBBox.getPosition().getX() * z);
   this->mBBox.getPosition().setY(this->mBBox.getPosition().getY() * z);
 }
Member Data Documentation
C_FLOAT64 CLabel::orig_height private
Definition at line 33 of file CLabel.h.
Referenced by getOrigHeight(), initOrigValues(), and scale().
C_FLOAT64 CLabel::orig_width private
Definition at line 32 of file CLabel.h.
Referenced by getOrigWidth(), initOrigValues(), and scale().
C_FLOAT64 CLabel::orig_x private
Definition at line 30 of file CLabel.h.
Referenced by initOrigValues(), and scale().
C_FLOAT64 CLabel::orig_y private
Definition at line 31 of file CLabel.h.
Referenced by initOrigValues(), and scale().
The documentation for this class was generated from the following files:
CLabel.h
CLabel.cpp