COPASI API: CSimSummaryInfo Class Reference
CSimSummaryInfo Class Reference
#include <CSimSummaryInfo.h>
Public Member Functions
CSimSummaryInfo ()
CSimSummaryInfo (size_t steps, size_t numReactants, C_FLOAT32 time)
C_FLOAT64 getMaxForSpecies (std::string ndKey)
C_FLOAT64 getMaxOverallConcentration ()
C_FLOAT64 getMinForSpecies (std::string ndKey)
C_FLOAT64 getMinOverallConcentration ()
size_t getNumberOfReactants ()
size_t getNumberOfSteps ()
C_FLOAT64 getTotalTime ()
void setMaxOverallConcentration (C_FLOAT64 max)
void storeMax (std::string ndKey, C_FLOAT64 maxR)
void storeMin (std::string ndKey, C_FLOAT64 minR)
Private Attributes
std::map< std::string, C_FLOAT64 > maxMap
std::map< std::string, C_FLOAT64 > minMap
C_FLOAT64 mMaxOverallConcentration
size_t mNumberOfReactants
size_t mNumberOfSteps
C_FLOAT64 mTotalTime
Friends
std::ostream & operator<< (std::ostream &os, const CSimSummaryInfo &inf)
Detailed Description
Definition at line 26 of file CSimSummaryInfo.h.
Constructor & Destructor Documentation
CSimSummaryInfo::CSimSummaryInfo ()
Definition at line 20 of file CSimSummaryInfo.cpp.
References mMaxOverallConcentration, mNumberOfReactants, mNumberOfSteps, and mTotalTime.
 {
   mNumberOfSteps = 0;
   mNumberOfReactants = 0;
   mTotalTime = 0.0;
   mMaxOverallConcentration = 0.0;
 }
CSimSummaryInfo::CSimSummaryInfo (size_t steps, size_t numReactants, C_FLOAT32 time)
Definition at line 28 of file CSimSummaryInfo.cpp.
References mMaxOverallConcentration, mNumberOfReactants, mNumberOfSteps, and mTotalTime.
 {
   mNumberOfSteps = steps;
   mNumberOfReactants = numReactants;
   mTotalTime = time;
   mMaxOverallConcentration = 0.0;
 }
Member Function Documentation
C_FLOAT64 CSimSummaryInfo::getMaxForSpecies (std::string ndKey)
Definition at line 48 of file CSimSummaryInfo.cpp.
References maxMap.
Referenced by CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), CQGLNetworkPainter::rescaleNode(), and CQGLNetworkPainter::showStep().
 {
   std::map<std::string, C_FLOAT64>::const_iterator iter = maxMap.find(ndKey);
   if (iter != maxMap.end())
     return (*iter).second;
   else
     return 0.0;
 }
C_FLOAT64 CSimSummaryInfo::getMaxOverallConcentration () inline
Definition at line 45 of file CSimSummaryInfo.h.
References mMaxOverallConcentration.
Referenced by CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), CQGLNetworkPainter::rescaleNode(), and CQGLNetworkPainter::showStep().
 {return this->mMaxOverallConcentration;}
C_FLOAT64 CSimSummaryInfo::getMinForSpecies (std::string ndKey)
Definition at line 58 of file CSimSummaryInfo.cpp.
References minMap.
Referenced by CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), CQGLNetworkPainter::rescaleNode(), and CQGLNetworkPainter::showStep().
 {
   std::map<std::string, C_FLOAT64>::const_iterator iter = minMap.find(ndKey);
   if (iter != minMap.end())
     return (*iter).second;
   else
     return 0.0;
 }
C_FLOAT64 CSimSummaryInfo::getMinOverallConcentration () inline
Definition at line 46 of file CSimSummaryInfo.h.
Referenced by CQGLNetworkPainter::createDataSets(), CQGLNetworkPainter::rescaleDataSets(), CQGLNetworkPainter::rescaleDataSetsWithNewMinMax(), CQGLNetworkPainter::rescaleNode(), and CQGLNetworkPainter::showStep().
 {return 0.0;}
size_t CSimSummaryInfo::getNumberOfReactants () inline
Definition at line 43 of file CSimSummaryInfo.h.
References mNumberOfReactants.
 {return this->mNumberOfReactants;}
size_t CSimSummaryInfo::getNumberOfSteps () inline
Definition at line 42 of file CSimSummaryInfo.h.
References mNumberOfSteps.
 {return this->mNumberOfSteps;}
C_FLOAT64 CSimSummaryInfo::getTotalTime () inline
Definition at line 41 of file CSimSummaryInfo.h.
References mTotalTime.
 {return this->mTotalTime;}
void CSimSummaryInfo::setMaxOverallConcentration (C_FLOAT64 max) inline
Definition at line 47 of file CSimSummaryInfo.h.
References max, and mMaxOverallConcentration.
Referenced by CQGLNetworkPainter::createDataSets().
 {this->mMaxOverallConcentration = max;}
void CSimSummaryInfo::storeMax (std::string ndKey, C_FLOAT64 maxR)
Definition at line 36 of file CSimSummaryInfo.cpp.
References maxMap.
Referenced by CQGLNetworkPainter::createDataSets().
 {
   maxMap.insert(std::pair<std::string, C_FLOAT64>
                 (ndKey, maxR));
 }
void CSimSummaryInfo::storeMin (std::string ndKey, C_FLOAT64 minR)
Definition at line 42 of file CSimSummaryInfo.cpp.
References minMap.
Referenced by CQGLNetworkPainter::createDataSets().
 {
   minMap.insert(std::pair<std::string, C_FLOAT64>
                 (ndKey, minR));
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CSimSummaryInfo & inf) friend
Definition at line 68 of file CSimSummaryInfo.cpp.
 {
   os << "number of steps: " << inf.mNumberOfSteps << std::endl;
   os << "number of reactants: " << inf.mNumberOfReactants << std::endl;
   os << "total time: " << inf.mTotalTime << std::endl;
   os << "maximum overall concentration: " << inf.mMaxOverallConcentration << std::endl;
   os << "range  of values for species: " << std::endl;
   std::map<std::string, C_FLOAT64>::const_iterator iter = inf.maxMap.begin();
   std::map<std::string, C_FLOAT64>::const_iterator iter2 = inf.minMap.begin();
   while ((iter != inf.maxMap.end()) && (iter2 != inf.minMap.end()))
     {
       os << " node: " << iter->first << " : [" << iter2->second;
       os << " - " << iter->second << "]" << std::endl;
       iter2++;
       iter++;
     }
   return os;
 }
Member Data Documentation
std::map<std::string, C_FLOAT64> CSimSummaryInfo::maxMap private
Definition at line 35 of file CSimSummaryInfo.h.
Referenced by getMaxForSpecies(), operator<<(), and storeMax().
std::map<std::string, C_FLOAT64> CSimSummaryInfo::minMap private
Definition at line 34 of file CSimSummaryInfo.h.
Referenced by getMinForSpecies(), operator<<(), and storeMin().
C_FLOAT64 CSimSummaryInfo::mMaxOverallConcentration private
Definition at line 32 of file CSimSummaryInfo.h.
Referenced by CSimSummaryInfo(), getMaxOverallConcentration(), operator<<(), and setMaxOverallConcentration().
size_t CSimSummaryInfo::mNumberOfReactants private
Definition at line 30 of file CSimSummaryInfo.h.
Referenced by CSimSummaryInfo(), getNumberOfReactants(), and operator<<().
size_t CSimSummaryInfo::mNumberOfSteps private
Definition at line 29 of file CSimSummaryInfo.h.
Referenced by CSimSummaryInfo(), getNumberOfSteps(), and operator<<().
C_FLOAT64 CSimSummaryInfo::mTotalTime private
Definition at line 31 of file CSimSummaryInfo.h.
Referenced by CSimSummaryInfo(), getTotalTime(), and operator<<().
The documentation for this class was generated from the following files:
CSimSummaryInfo.h
CSimSummaryInfo.cpp