COPASI API: CFunctionDB Class Reference
CFunctionDB Class Reference
#include <CFunctionDB.h>
Public Member Functions
bool add (CFunction *pFunction, const bool &adopt)
CFunction * addAndAdaptName (CFunction *pFunction)
bool appendDependentFunctions (std::set< const CCopasiObject * > candidates, std::set< const CCopasiObject * > &dependentFunctions) const
CFunctionDB (const std::string &name, const CCopasiContainer *pParent)
void cleanup ()
CFunction * findFunction (const std::string &functionName)
CFunction * findLoadFunction (const std::string &functionName)
std::string getFilename () const
std::vector< CFunction * > getUsedFunctions (const CModel *pModel) const
void initObjects ()
std::set< std::string > listDependentTrees (const std::string &name) const
bool load ()
bool load (const std::string &fileName)
C_INT32 load (CReadConfig &configbuffer)
CCopasiVectorN< CFunction > & loadedFunctions ()
bool removeFunction (size_t index)
bool removeFunction (const std::string &key)
bool save (const std::string &fileName)
void setFilename (const std::string &filename)
std::vector< CFunction * > suitableFunctions (const size_t noSubstrates, const size_t noProducts, const TriLogic reversibility)
virtual ~CFunctionDB ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
std::string mFilename
CCopasiVectorN< CFunction > mLoadedFunctions
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 35 of file CFunctionDB.h.
Constructor & Destructor Documentation
CFunctionDB::CFunctionDB (const std::string & name, const CCopasiContainer * pParent)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
CFunctionDB
Created for Copasi by Stefan Hoops (C) Stefan Hoops 2001
Definition at line 36 of file CFunctionDB.cpp.
References CONSTRUCTOR_TRACE, and initObjects().
                                                           :
   CCopasiContainer(name, pParent, "FunctionDB"),
   mFilename(),
   mLoadedFunctions("Functions", this)
 {
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CFunctionDB::~CFunctionDB () virtual
Destructor
Definition at line 46 of file CFunctionDB.cpp.
References cleanup(), and DESTRUCTOR_TRACE.
 {
   cleanup();
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
bool CFunctionDB::add (CFunction * pFunction, const bool & adopt)
Add the function to the database
Parameters
CFunction * pFunction
const bool & adopt (default = false)
Returns
bool success
Definition at line 254 of file CFunctionDB.cpp.
References CCopasiVectorN< CType >::add(), and mLoadedFunctions.
Referenced by addAndAdaptName(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCReactionFromReaction(), CQFunctionDM::insertRows(), CReaction::setFunctionFromExpressionTree(), FunctionWidget1::slotBtnNew(), and ReactionsWidget1::slotNewFunction().
 {return mLoadedFunctions.add(pFunction, adopt);}
CFunction * CFunctionDB::addAndAdaptName (CFunction * pFunction)
Add the function to the database, if necessary adapt the name so it is unique.
Definition at line 258 of file CFunctionDB.cpp.
References add(), C_INVALID_INDEX, CCopasiVectorN< CType >::getIndex(), CCopasiObject::getObjectName(), mLoadedFunctions, pdelete, and CCopasiObject::setObjectName().
Referenced by CModel::convert2NonReversible(), test000058::test_bug1025_10(), test000058::test_bug1025_5(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), and test000059::test_unique_id_21_2().
 {
   if (!pFunction) return NULL;
   std::string basename = pFunction->getObjectName();
   std::string name = basename;
   //CFunction* pFunc;
   //CCopasiVectorN<CEvaluationTree>& FunctionList
   //= this->loadedFunctions();
   int i = 0;
   size_t Index = C_INVALID_INDEX;
   while ((Index = mLoadedFunctions.getIndex(name)) != C_INVALID_INDEX)
     {
       // Check whether the new functions and the old are the same.
       if (*mLoadedFunctions[Index] == *pFunction)
         {
           pdelete(pFunction);
           return mLoadedFunctions[Index];
         }
       i++;
       std::ostringstream ss; ss << "[" << i << "]";
       name = basename + ss.str();
     }
   pFunction->setObjectName(name);
   this->add(pFunction, true);
   return pFunction;
 }
bool CFunctionDB::appendDependentFunctions (std::set< const CCopasiObject * > candidates, std::set< const CCopasiObject * > & dependentFunctions) const
Appends pointers to function, which are dependent on any of the candidates to the list dependentFunctions.
Parameters
std::set< const CCopasiObject * > candidates
std::set< const CCopasiObject * > & dependentFunctions
Returns
bool functionsAppended
Definition at line 396 of file CFunctionDB.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), and mLoadedFunctions.
Referenced by CQMessageBox::confirmDelete(), and FunctionWidget1::leave().
 {
   size_t Size = dependentFunctions.size();
   CCallParameters< C_FLOAT64 > CallParmeters;
   CCopasiVectorN< CFunction >::const_iterator it = mLoadedFunctions.begin();
   CCopasiVectorN< CFunction >::const_iterator end = mLoadedFunctions.end();
   for (; it != end; ++it)
     if (candidates.find(*it) == candidates.end() &&
         (*it)->CEvaluationTree::dependsOn(candidates))
       dependentFunctions.insert((*it));
   return Size < dependentFunctions.size();
 }
void CFunctionDB::cleanup ()
Definition at line 52 of file CFunctionDB.cpp.
References CCopasiVector< T >::cleanup(), and mLoadedFunctions.
Referenced by ~CFunctionDB().
 {mLoadedFunctions.cleanup();}
CFunction * CFunctionDB::findFunction (const std::string & functionName)
Delete the function functionName from the database
Parameters
const string &functionName
Returns
C_INT32 Fail Search for a function among the loaded functions. If no function is found NULL is returned
Parameters
const string &functionName
Returns
CFunction *
Definition at line 325 of file CFunctionDB.cpp.
References C_INVALID_INDEX, CCopasiVectorN< CType >::getIndex(), and mLoadedFunctions.
Referenced by CEvaluationNodeCall::calls(), CEvaluationNodeCall::compile(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createFunctionSetFromFunctionNames(), expand_function_call(), CODEExporterC::exportSingleFunction(), CODEExporter::exportSingleFunction(), SBMLImporter::findCorrespondingFunction(), SBMLImporter::findFunctionCalls(), CODEExporter::findFunctionsCalls(), CEvaluationNodeCall::getCalledTree(), SBMLImporter::isConstantFlux(), CODEExporter::modifyTreeForMassAction(), SBMLImporter::restoreFunctionDB(), CODEExporterC::setExportNameOfFunction(), CReaction::setFunctionFromExpressionTree(), CSBMLExporter::setFunctionSBMLIds(), suitableFunctions(), test000067::test_bug1060(), test_compare_utilities::test_copasi_function_expansion(), and CEvaluationNodeCall::toAST().
 {
   size_t index = mLoadedFunctions.getIndex(functionName);
   if (index != C_INVALID_INDEX)
     return mLoadedFunctions[index];
   else
     return NULL;
 }
CFunction * CFunctionDB::findLoadFunction (const std::string & functionName)
Search for a function among the loaded functions. If no function is found the database is searched and the apropriate function is loaded.
Parameters
const string &functionName
Returns
CFunction * function (NULL if function is not found)
Definition at line 335 of file CFunctionDB.cpp.
References CCopasiObject::getObjectName(), mLoadedFunctions, and CCopasiVector< T >::size().
Referenced by CReaction::setFunction(), CReactionInterface::setFunctionAndDoMapping(), and CReactionInterface::setFunctionWithEmptyMapping().
 {
   size_t i;
   for (i = 0; i < mLoadedFunctions.size(); i++)
     if (functionName == mLoadedFunctions[i]->getObjectName())
       return mLoadedFunctions[i];
   return NULL;
 }
std::string CFunctionDB::getFilename () const
Definition at line 156 of file CFunctionDB.cpp.
References mFilename.
 {return mFilename;}
std::vector< CFunction * > CFunctionDB::getUsedFunctions (const CModel * pModel) const
Retrieves a list of all functions used in the model
Returns
std::vector< CEvaluationTree * > usedFunctions
Definition at line 428 of file CFunctionDB.cpp.
References CModel::appendDependentModelObjects(), CCopasiVector< T >::begin(), CFunction::completeFunctionList(), CCopasiVector< T >::end(), and mLoadedFunctions.
Referenced by CCopasiXML::buildFunctionList().
 {
   std::vector< CFunction * > UsedFunctions;
   CCopasiVectorN < CFunction >::const_iterator it = mLoadedFunctions.begin();
   CCopasiVectorN < CFunction >::const_iterator end = mLoadedFunctions.end();
   for (; it != end; ++it)
     {
       std::set< const CCopasiObject * > Function;
       Function.insert(*it);
       std::set< const CCopasiObject * > Reactions;
       std::set< const CCopasiObject * > Metabolites;
       std::set< const CCopasiObject * > Values;
       std::set< const CCopasiObject * > Compartments;
       std::set< const CCopasiObject * > Events;
       pModel->appendDependentModelObjects(Function,
                                           Reactions, Metabolites, Compartments, Values, Events);
       if (Reactions.size() != 0)
         {
           UsedFunctions.push_back(*it);
           continue;
         }
       if (Metabolites.size() != 0)
         {
           UsedFunctions.push_back(*it);
           continue;
         }
       if (Values.size() != 0)
         {
           UsedFunctions.push_back(*it);
           continue;
         }
       if (Compartments.size() != 0)
         {
           UsedFunctions.push_back(*it);
           continue;
         }
       if (Events.size() != 0)
         {
           UsedFunctions.push_back(*it);
           continue;
         }
     }
   CFunction::completeFunctionList(UsedFunctions);
   return UsedFunctions;
 }
void CFunctionDB::initObjects ()
Definition at line 54 of file CFunctionDB.cpp.
References CCopasiContainer::addObjectReference(), and mFilename.
Referenced by CFunctionDB().
 {
   addObjectReference("File", mFilename);
 }
std::set< std::string > CFunctionDB::listDependentTrees (const std::string & name) const
Retrieve a list of evaluation trees depending on the tree with the given name.
Parameters
const std::string & name
Returns
std::set<std::string> list
Definition at line 414 of file CFunctionDB.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), and mLoadedFunctions.
 {
   std::set<std::string> List;
   CCopasiVectorN < CFunction >::const_iterator it = mLoadedFunctions.begin();
   CCopasiVectorN < CFunction >::const_iterator end = mLoadedFunctions.end();
   for (; it != end; ++it)
     if ((*it)->dependsOnTree(name))
       List.insert((*it)->getObjectName());
   return List;
 }
bool CFunctionDB::load ()
Definition at line 59 of file CFunctionDB.cpp.
References FunctionDBxml, CCopasiXML::load(), mLoadedFunctions, and CCopasiXML::setFunctionList().
Referenced by CCopasiRootContainer::initializeChildren(), and DataModelGUI::loadFunctionDB().
 {
   CCopasiXML XML;
   XML.setFunctionList(&mLoadedFunctions);
   std::stringstream DB;
   DB.str(FunctionDBxml);
   if (DB.fail())
     return false;
   if (!XML.load(DB, ""))
     return false;
   return true;
 }
bool CFunctionDB::load (const std::string & fileName)
Definition at line 76 of file CFunctionDB.cpp.
References CCopasiXML::load(), mLoadedFunctions, and CCopasiXML::setFunctionList().
 {
   CCopasiXML XML;
   XML.setFunctionList(&mLoadedFunctions);
   std::fstream str(fileName.c_str());
   if (str.fail())
     return false;
   if (!XML.load(str, ""))
     return false;
   return true;
 }
C_INT32 CFunctionDB::load (CReadConfig & configbuffer)
Loads an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
pconfigbuffer reference to a CReadConfig object.
Returns
mFail
Definition at line 98 of file CFunctionDB.cpp.
References CCopasiVectorN< CType >::add(), C_INT32, CEvaluationTree::compile(), fatalError, CEvaluationTree::Function, CCopasiMessage::getLastMessage(), CEvaluationTree::getType(), CReadConfig::getVariable(), CFunction::load(), CReadConfig::LOOP, CEvaluationTree::MassAction, MCCopasiVector, mLoadedFunctions, pdelete, CCopasiMessage::peekLastMessage(), CEvaluationTree::PreDefined, and CEvaluationTree::UserDefined.
 {
   CFunction Function;
   CFunction * pFunction = NULL;
   C_INT32 Size = 0;
   C_INT32 Fail = 0;
   configbuffer.getVariable("TotalUDKinetics", "C_INT32", &Size,
                            CReadConfig::LOOP);
   for (C_INT32 i = 0; i < Size; i++)
     {
       Function.load(configbuffer);
       switch (Function.getType())
         {
           case CEvaluationTree::Function:
             pFunction = new CFunction(Function);
             break;
           case CEvaluationTree::MassAction:
             pFunction = new CMassAction(Function);
             break;
           case CEvaluationTree::PreDefined:
           case CEvaluationTree::UserDefined:
             pFunction = new CKinFunction(Function,
                                          &configbuffer);
             break;
           default:
             fatalError();
             break;
         }
       pFunction->compile();
       if (!mLoadedFunctions.add(pFunction, true))
         {
           pdelete(pFunction);
           // We ignore:
           // CCopasiVector (2): Object '%s' allready exists.
           if ((MCCopasiVector + 2) != CCopasiMessage::peekLastMessage().getNumber())
             return Fail = 1;
           // Remove the ignored meesage.
           CCopasiMessage::getLastMessage();
         }
     }
   return Fail;
 }
CCopasiVectorN< CFunction > & CFunctionDB::loadedFunctions ()
Retrieves the vector of loaded functions.
Returns
"CCopasiVectorNS < CFunction > &" loadedFunctions
Definition at line 346 of file CFunctionDB.cpp.
References mLoadedFunctions.
Referenced by CSBMLExporter::collectIds(), CFunction::completeFunctionList(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), CQFunctionDM::data(), COptProblem::elevateChildren(), CQFunctionDM::isFunctionReadOnly(), CQBrowserPaneDM::load(), stress_test::normalizeFunctionDB(), CQFunctionDM::removeRows(), CCopasiDataModel::removeSBMLIdFromFunctions(), SBMLImporter::removeUnusedFunctions(), CQFunctionDM::rowCount(), CQFunctionDM::setData(), FunctionWidget1::slotBtnNew(), CQFunctionsWidget::slotDoubleClicked(), and ReactionsWidget1::slotNewFunction().
 {return mLoadedFunctions;}
bool CFunctionDB::removeFunction (size_t index)
Definition at line 291 of file CFunctionDB.cpp.
References CCopasiVector< T >::begin(), C_INVALID_INDEX, CCopasiVector< T >::end(), CCopasiRootContainer::getDatamodelList(), and mLoadedFunctions.
Referenced by removeFunction(), CQFunctionDM::removeRows(), SBMLImporter::restoreFunctionDB(), and FunctionWidget1::slotBtnDelete().
 {
   if (index == C_INVALID_INDEX) return false;
   // We need to delete all dependent objects in all data models.
   CCopasiVector< CCopasiDataModel >::iterator it = CCopasiRootContainer::getDatamodelList()->begin();
   CCopasiVector< CCopasiDataModel >::iterator end = CCopasiRootContainer::getDatamodelList()->end();
   std::set< const CCopasiObject * > DeletedObjects = mLoadedFunctions[index]->getDeletedObjects();
   for (; it != end; ++it)
     {
       (*it)->getModel()->removeDependentModelObjects(DeletedObjects);
     }
   mLoadedFunctions.CCopasiVector<CFunction>::remove(index);
   return true;
 }
bool CFunctionDB::removeFunction (const std::string & key)
Definition at line 311 of file CFunctionDB.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), mLoadedFunctions, and removeFunction().
 {
   CEvaluationTree* func = dynamic_cast< CEvaluationTree * >(CCopasiRootContainer::getKeyFactory()->get(key));
   if (!func) return false;
   size_t index =
     mLoadedFunctions.CCopasiVector<CFunction>::getIndex(func);
   if (index == C_INVALID_INDEX) return false;
   return removeFunction(index);
 }
bool CFunctionDB::save (const std::string & fileName)
Definition at line 91 of file CFunctionDB.cpp.
References mLoadedFunctions, and CCopasiXML::setFunctionList().
Referenced by DataModelGUI::saveFunctionDB().
 {
   CCopasiXML XML;
   XML.setFunctionList(&mLoadedFunctions);
   return XML.CCopasiXMLInterface::save(fileName, fileName);
 }
void CFunctionDB::setFilename (const std::string & filename)
Definition at line 153 of file CFunctionDB.cpp.
References mFilename.
 {mFilename = filename;}
std::vector< CFunction * > CFunctionDB::suitableFunctions (const size_t noSubstrates, const size_t noProducts, const TriLogic reversibility)
Retrieves the vector of functions that are suitable for a number of substrates, products and reversibility status. Note: The returns CCopasiVector has to be deleted after use!
Parameters
const size_t noSubstrates the number of substrates
const size_t noProducts the number of products
const TriLogic reversible the reversibility status
Returns
"std::vector<CFunction*> " suitableFunctions
Definition at line 350 of file CFunctionDB.cpp.
References fatalError, findFunction(), CFunction::isSuitable(), mLoadedFunctions, CCopasiVector< T >::size(), and TriTrue.
Referenced by SBMLImporter::findCorrespondingFunction(), and CReactionInterface::getListOfPossibleFunctions().
 {
   std::vector<CFunction*> ret;
   CFunction *pFunction;
   size_t i, imax = mLoadedFunctions.size();
   for (i = 0; i < imax; i++)
     {
       pFunction = dynamic_cast<CFunction *>(mLoadedFunctions[i]);
       if (!pFunction) continue;
       if (pFunction->isSuitable(noSubstrates, noProducts, reversibility))
         ret.push_back(pFunction);
     }
   //always add constant flux it is is missing
   if (reversibility == TriTrue)
     {
       if ((noSubstrates > 0) || (noProducts > 0)) //constant flux was not yet added
         {
           pFunction = dynamic_cast<CFunction*>(findFunction("Constant flux (reversible)"));
           if (!pFunction) fatalError();
           ret.push_back(pFunction);
         }
     }
   else //irreversible
     {
       if (noSubstrates > 0) //constant flux was not yet added
         {
           pFunction = dynamic_cast<CFunction*>(findFunction("Constant flux (irreversible)"));
           if (!pFunction) fatalError();
           ret.push_back(pFunction);
         }
     }
   return ret;
 }
Member Data Documentation
std::string CFunctionDB::mFilename private
Filename which contains the function database
Definition at line 42 of file CFunctionDB.h.
Referenced by getFilename(), initObjects(), and setFilename().
CCopasiVectorN< CFunction > CFunctionDB::mLoadedFunctions private
Vector of the currently loaded functions
Definition at line 47 of file CFunctionDB.h.
Referenced by add(), addAndAdaptName(), appendDependentFunctions(), cleanup(), findFunction(), findLoadFunction(), getUsedFunctions(), listDependentTrees(), load(), loadedFunctions(), removeFunction(), save(), and suitableFunctions().
The documentation for this class was generated from the following files:
CFunctionDB.h
CFunctionDB.cpp