COPASI API: CQExpressionMmlStackedWidget Class Reference
CQExpressionMmlStackedWidget Class Reference
#include <CQExpressionMmlStackedWidget.h>
Public Slots
void updateWidget ()
Signals
void signalCheckValidity (bool)
Public Member Functions
CQExpressionMmlStackedWidget (QWidget *parent=0)
QString getText ()
void setReadOnly (const bool &readOnly)
~CQExpressionMmlStackedWidget ()
Protected Slots
void slotGoExpressionWidget ()
void slotGoMmlWidget ()
Protected Member Functions
void init ()
Private Slots
void slotSaveExpression ()
Private Member Functions
void saveMML (const QString filename)
void savePNG (const QString filename)
void saveTeX (const QString filename)
Private Attributes
QString MMLStr
Detailed Description
Definition at line 18 of file CQExpressionMmlStackedWidget.h.
Constructor & Destructor Documentation
CQExpressionMmlStackedWidget::CQExpressionMmlStackedWidget (QWidget * parent = 0)
Definition at line 42 of file CQExpressionMmlStackedWidget.cpp.
References CQIconResource::copasi, CQIconResource::edit, CQIconResource::fileExport, CQIconResource::icon(), init(), and CQIconResource::renderMathML.
   : QStackedWidget(parent)
 {
   setupUi(this);
   mpBtnExpressionObject->setIcon(CQIconResource::icon(CQIconResource::copasi));
   mpBtnViewExpression->setIcon(CQIconResource::icon(CQIconResource::renderMathML));
   mpBtnEditExpression->setIcon(CQIconResource::icon(CQIconResource::edit));
   mpBtnSaveExpression->setIcon(CQIconResource::icon(CQIconResource::fileExport));
   mpMmlScrollView->setStyleSheet(QString(mpMmlScrollView->widget()->metaObject()->className()) + "{background-color:" + QColor(Qt::white).name() + ";}");
 #ifdef WIN32
   // on windows there ought to be a border around the MML widget
   // otherwise it is difficult to distinguish the formula from the rest of the
   // dialog
   mpMmlScrollView->setFrameShape(QFrame::Panel);
   mpMmlScrollView->setFrameStyle(QFrame::Panel | QFrame::Plain);
 #endif
   init();
 }
CQExpressionMmlStackedWidget::~CQExpressionMmlStackedWidget ()
Definition at line 68 of file CQExpressionMmlStackedWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
QString CQExpressionMmlStackedWidget::getText ()
Definition at line 147 of file CQExpressionMmlStackedWidget.cpp.
 {
   return mpExpressionWidget->toPlainText();
 }
void CQExpressionMmlStackedWidget::init () protected
Definition at line 152 of file CQExpressionMmlStackedWidget.cpp.
Referenced by CQExpressionMmlStackedWidget().
 {
 #ifdef DEBUG_UI
   qDebug() << "L" << __LINE__ << " on CQEMSW mpExpressionWidget->text() = " << mpExpressionWidget->text();
   qDebug() << "L" << __LINE__ << " on CQEMSW: activeWidget = " << currentIndex();
 #endif
 #ifndef HAVE_MML
   mpBtnViewExpression->hide();
 #endif // not HAVE_MML
 }
void CQExpressionMmlStackedWidget::saveMML (const QString filename) private
Definition at line 222 of file CQExpressionMmlStackedWidget.cpp.
References CLocaleString::fromUtf8(), and TO_UTF8.
Referenced by slotSaveExpression().
 {
   std::ofstream ofile;
   ofile.open(CLocaleString::fromUtf8(TO_UTF8(outfilename)).c_str(), std::ios::trunc);
   ofile << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << std::endl;
   ofile << "<!DOCTYPE math PUBLIC \"-//W3C//DTD MathML 2.0//EN\" \"http://www.w3.org/Math/DTD/mathml2/mathml2.dtd\">" << std::endl;
   ofile << "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">" << std::endl;
   mpExpressionWidget->writeMathML(ofile);
   ofile << "</math>" << std::endl;
   ofile.close();
 }
void CQExpressionMmlStackedWidget::savePNG (const QString filename) private
Definition at line 202 of file CQExpressionMmlStackedWidget.cpp.
References FROM_UTF8.
Referenced by slotSaveExpression().
 {
   std::ostringstream mml;
   mpExpressionWidget->writeMathML(mml);
   QtMmlDocument doc;
   doc.setBaseFontPointSize(20);
   doc.setFontName(QtMmlWidget::NormalFont, qApp->font().family());
   doc.setContent(FROM_UTF8(mml.str()));
   const QSize &size = doc.size();
   QPixmap pixmap(size.width(), size.height());
   QPainter painter(&pixmap);
   painter.setRenderHint(QPainter::Antialiasing);
   painter.setRenderHint(QPainter::SmoothPixmapTransform);
   painter.setRenderHint(QPainter::HighQualityAntialiasing);
   painter.fillRect(0, 0, size.width(), size.height(), Qt::white);
   doc.paint(&painter, QPoint(0, 0));
   pixmap.save(outfilename, "PNG");
 }
void CQExpressionMmlStackedWidget::saveTeX (const QString filename) private
Definition at line 238 of file CQExpressionMmlStackedWidget.cpp.
References CMathMLToTeX::convert(), FROM_UTF8, CLocaleString::fromUtf8(), and TO_UTF8.
Referenced by slotSaveExpression().
 {
   std::ostringstream mml;
   mpExpressionWidget->writeMathML(mml);
   QString latexStr(FROM_UTF8(mml.str()));
   CMathMLToTeX::convert(latexStr);
   std::ofstream ofile;
   ofile.open(CLocaleString::fromUtf8(TO_UTF8(outfilename)).c_str(), std::ios::trunc);
   ofile << TO_UTF8(latexStr);
   ofile.close();
 }
void CQExpressionMmlStackedWidget::setReadOnly (const bool & readOnly)
Definition at line 139 of file CQExpressionMmlStackedWidget.cpp.
 {
   if (readOnly)
     mpBtnEditExpression->hide();
   else
     mpBtnEditExpression->show();
 }
void CQExpressionMmlStackedWidget::signalCheckValidity (bool) signal
void CQExpressionMmlStackedWidget::slotGoExpressionWidget () protected slot
Definition at line 73 of file CQExpressionMmlStackedWidget.cpp.
 {
 #ifdef DEBUG_UI
   qDebug() << "- here on CQExpressionMmlStackedWidget::slotGoExpressionWidget() -";
   qDebug() << "L" << __LINE__ << " on CQEMSW mpExpressionWidget->text() = " << mpExpressionWidget->text();
 #endif
   setCurrentWidget(mpExpressionPage);
 #ifdef DEBUG_UI
   qDebug() << "L" << __LINE__ << " on CQEMSW mpExpressionWidget->text() = " << mpExpressionWidget->text();
   qDebug() << "L" << __LINE__ << " on CQEMSW: activeWidget NEW = " << currentIndex();
 #endif
 }
void CQExpressionMmlStackedWidget::slotGoMmlWidget () protected slot
Definition at line 88 of file CQExpressionMmlStackedWidget.cpp.
 {
 #ifdef DEBUG_UI
   qDebug() << "L" << __LINE__ << " on CQEMSW mpExpressionWidget->text() = " << mpExpressionWidget->text();
 #endif
   setCurrentWidget(mpMmlPage);
 #ifdef DEBUG_UI
   qDebug() << "L" << __LINE__ << " on CQEMSW mpExpressionWidget->text() = " << mpExpressionWidget->text();
   qDebug() << "L" << __LINE__ << " on CQEMSW: activeWidget NEW = " << currentIndex();
 #endif
 }
void CQExpressionMmlStackedWidget::slotSaveExpression () private slot
Definition at line 164 of file CQExpressionMmlStackedWidget.cpp.
References C_INT32, checkSelection(), CopasiFileDialog::getSaveFileName(), saveMML(), savePNG(), and saveTeX().
 {
   QString *filter = new QString;
   QString outfilename;
   C_INT32 Answer = QMessageBox::No;
   while (Answer == QMessageBox::No)
     {
       outfilename =
         CopasiFileDialog::getSaveFileName(this,
                                           "Save File Dialog",
                                           "untitled.mml",
                                           "MathML (*.mml);;TeX (*.tex);;PNG (*.png)",
 //                                          "Save Expression to Disk", new QString);
                                           "Save Expression to Disk", filter);
       if (outfilename.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(outfilename);
       if (Answer == QMessageBox::Cancel)
         return;
     }
 #ifdef DEBUG_UI
   qDebug() << "\non CQEMSW::slotSaveExpression -> filter = " << *filter << "\n";
 #endif
   if (filter->contains(".tex"))
     saveTeX(outfilename);
   else if (filter->contains(".png"))
     savePNG(outfilename);
   else
     saveMML(outfilename);
 }
void CQExpressionMmlStackedWidget::updateWidget () slot
Definition at line 102 of file CQExpressionMmlStackedWidget.cpp.
References FROM_UTF8.
 {
 #ifdef DEBUG_UI
   qDebug() << "- here on CQExpressionMmlStackedWidget::updateWidget() -";
 #endif
 #ifdef HAVE_MML
   std::ostringstream mml;
   std::vector<std::vector<std::string> > params;
 #ifdef DEBUG_UI
   qDebug() << "L" << __LINE__ << " on CQEMSW mpExpressionWidget->text() = " << mpExpressionWidget->text();
   qDebug() << "L" << __LINE__ << " on CQEMSW: activeWidget NEW = " << currentIndex();
 #endif
   if (mpExpressionWidget->toPlainText().isEmpty() || !mpExpressionWidget->isValid())
     setCurrentWidget(mpExpressionPage);
   else
     {
       mpExpressionWidget->writeMathML(mml);
 #ifdef DEBUG_UI
       qDebug() << "mml.str() = " << FROM_UTF8(mml.str());
 #endif
       setCurrentWidget(mpMmlPage);
       mpMmlScrollView->updateWidget(mml);
     }
 #endif /* HAVE_MML */
 #ifdef DEBUG_UI
   qDebug() << "L" << __LINE__ << " on CQEMSW: activeWidget = " << currentIndex();
 #endif
 }
Member Data Documentation
QString CQExpressionMmlStackedWidget::MMLStr private
Definition at line 45 of file CQExpressionMmlStackedWidget.h.
The documentation for this class was generated from the following files:
CQExpressionMmlStackedWidget.h
CQExpressionMmlStackedWidget.cpp