COPASI API: qtUtilities.cpp File Reference
qtUtilities.cpp File Reference
#include <QtCore/QString>
#include <QtCore/QFileInfo>
#include "copasi.h"
#include "qtUtilities.h"
#include "CQMessageBox.h"
#include "utilities/CCopasiParameterGroup.h"
#include "utilities/CDirEntry.h"
Functions
C_INT32 checkSelection (const QString &file)
QString getParameterValue (const CCopasiParameterGroup *group, const size_t &index, CCopasiParameter::Type *type)
QString getParameterValue (const CCopasiParameterGroup *group, const std::string &name, CCopasiParameter::Type *type)
bool setParameterValue (CCopasiParameterGroup *group, const size_t &index, const QString &value)
bool setParameterValue (CCopasiParameterGroup *group, const std::string &name, const QString &value)
void vectorOfStrings2QStringList (std::vector< std::string > vs, QStringList &qsl)
Function Documentation
C_INT32 checkSelection (const QString & file)
Checks whether the file exists. If the file exist the user is prompted whether to overwrite the file. The return value is one of QMessageBox::Yes, QMessageBox::No, or QMessageBox::Cancel. If the file does not exist QMessageBox::Yes is returned. param const QString & file
Returns
C_INT32 overwrite
Definition at line 179 of file qtUtilities.cpp.
References CQMessageBox::information(), CDirEntry::isWritable(), CQMessageBox::question(), and TO_UTF8.
Referenced by PlotWindow::printAsImage(), CQTSSAResultSubWidget::saveDataToFile(), CQBarChart::saveDataToFile(), CQLyapResultWidget::saveToFile(), CQSensResultWidget::saveToFile(), CQParameterOverviewWidget::slotBtnSaveToFile(), CopasiUI3Window::slotCapture(), CopasiUI3Window::slotExportMathModel(), CopasiUI3Window::slotExportSBML(), CopasiUI3Window::slotFileSaveAs(), CopasiUI3Window::slotFunctionDBSave(), CQDifferentialEquations::slotSave(), CQSteadyStateResult::slotSave(), CQTimeSeriesWidget::slotSave(), CQMoietiesTaskResult::slotSave(), CQOptimizationResult::slotSave(), CMCAResultSubwidget::slotSave(), CLNAResultSubwidget::slotSave(), CQFittingResult::slotSave(), CQEFMResultWidget::slotSave(), PlotWindow::slotSaveData(), and CQExpressionMmlStackedWidget::slotSaveExpression().
 {
 #ifdef DEBUG_UI
   qDebug() << "Filename on checkSelection = " << file;
 #endif
   if (QFileInfo(file).exists())
     {
       if (CDirEntry::isWritable(TO_UTF8(file)))
         return CQMessageBox::question(NULL, "File exists!",
                                       "Overwrite existing file " + file + "?",
                                       QMessageBox::Ok | QMessageBox::Cancel,
                                       QMessageBox::Cancel);
       else
         {
           CQMessageBox::information(NULL, "File read-only",
                                     "The file is read-only. Please select another file!",
                                     QMessageBox::Ok, QMessageBox::Ok);
           return QMessageBox::Cancel;
         }
     }
   else
     return QMessageBox::Ok;
 }
QString getParameterValue (const CCopasiParameterGroup * group, const size_t & index, CCopasiParameter::Type * type = NULL)
Retrieve a parameter from a parameter group and convert it to a QString.
Parameters
const CCopasiParameterGroup * group
const size_t & index
CCopasiParameter::Type * type (default: NULL)
Returns
QString value
Definition at line 28 of file qtUtilities.cpp.
References CCopasiParameter::BOOL, CCopasiParameter::CN, CCopasiParameter::DOUBLE, FROM_UTF8, CCopasiParameterGroup::getName(), CCopasiParameterGroup::getType(), CCopasiParameterGroup::getValue(), CCopasiParameter::GROUP, CCopasiParameter::INT, CCopasiParameter::INVALID, CCopasiParameter::KEY, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pKEY, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUINT, CCopasiParameterGroup::size(), CCopasiParameter::STRING, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by getParameterValue(), CScanWidgetRandom::load(), CQTaskMethodWidget::loadMethod(), CQLNAWidget::loadParameterTable(), CQMCAWidget::loadParameterTable(), CQTaskMethodWidget::saveMethod(), CQMCAWidget::saveParameterTable(), CQLNAWidget::saveParameterTable(), and setParameterValue().
 {
   if (index >= group->size())
     return QString::fromLatin1("INVALID");
   if (type) *type = group->getType(index);
   switch (group->getType(index))
     {
       case CCopasiParameter::DOUBLE:
         return QString::number(* group->getValue(index).pDOUBLE);
         break;
       case CCopasiParameter::UDOUBLE:
         return QString::number(* group->getValue(index).pDOUBLE);
         break;
       case CCopasiParameter::INT:
         return QString::number(* group->getValue(index).pINT);
         break;
       case CCopasiParameter::UINT:
         return QString::number(* group->getValue(index).pUINT);
         break;
       case CCopasiParameter::BOOL:
         return QString::number(* group->getValue(index).pBOOL);
         break;
       case CCopasiParameter::STRING:
         return
           FROM_UTF8(* group->getValue(index).pSTRING);
         break;
       case CCopasiParameter::KEY:
         return
           FROM_UTF8(* group->getValue(index).pKEY);
         break;
       case CCopasiParameter::CN:
         return
           FROM_UTF8(* group->getValue(index).pCN);
         break;
       case CCopasiParameter::GROUP:
         return FROM_UTF8((group->getName(index)));
         break;
       case CCopasiParameter::INVALID:
         return QString::fromUtf8("INVALID");
         break;
       default:
         break;
     }
   return QString::fromLatin1("INVALID");
 }
QString getParameterValue (const CCopasiParameterGroup * group, const std::string & name, CCopasiParameter::Type * type = NULL)
Retrieve a parameter from a parameter group and convert it to a QString.
Parameters
const CCopasiParameterGroup * group
const std::string & name
CCopasiParameter::Type * type (default: NULL)
Returns
QString value
Definition at line 89 of file qtUtilities.cpp.
References CCopasiParameterGroup::getIndex(), and getParameterValue().
 {return getParameterValue(group, group->getIndex(name), type);}
bool setParameterValue (CCopasiParameterGroup * group, const size_t & index, const QString & value)
Set a parameter of a parameter group from a value given as a QString. Success = true is returned when the set operation was succesful, i.e., value == getParameterValue.
Parameters
CCopasiParameterGroup * group
const size_t & index
const QString & value
Returns
bool success.
Definition at line 94 of file qtUtilities.cpp.
References CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::CN, CCopasiParameter::DOUBLE, getParameterValue(), CCopasiParameterGroup::getType(), CCopasiParameter::GROUP, CCopasiParameter::INT, CCopasiParameter::INVALID, CCopasiParameter::KEY, CCopasiParameterGroup::setValue(), CCopasiParameterGroup::size(), CCopasiParameter::STRING, TO_UTF8, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CQTaskMethodWidget::changeMethod(), CQTaskMethodWidget::saveMethod(), CQMCAWidget::saveParameterTable(), CQLNAWidget::saveParameterTable(), and setParameterValue().
 {
   if (index >= group->size())
     return false;
   if (getParameterValue(group, index) == value) return true;
   bool ok;
   C_FLOAT64 DOUBLE;
   C_INT32 INT;
   unsigned C_INT32 UINT;
   bool BOOL;
   std::string STRING;
   CCopasiObjectName CN;
   switch (group->getType(index))
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         DOUBLE = value.toDouble(&ok);
         if (!ok) return false;
         return group->setValue(index, DOUBLE);
         break;
       case CCopasiParameter::INT:
         INT = value.toInt(&ok);
         if (!ok) return false;
         return group->setValue(index, INT);
         break;
       case CCopasiParameter::UINT:
         UINT = value.toUInt(&ok);
         if (!ok) return false;
         return group->setValue(index, UINT);
         break;
       case CCopasiParameter::BOOL:;
         UINT = value.toUShort(&ok);
         if (!ok) return false;
         if (UINT == 1) BOOL = true;
         else if (UINT == 0) BOOL = false;
         else return false;
         return group->setValue(index, BOOL);
         break;
       case CCopasiParameter::STRING:
       case CCopasiParameter::KEY:
         STRING = TO_UTF8(value);
         return group->setValue(index, STRING);
         break;
       case CCopasiParameter::CN:
         CN = std::string(TO_UTF8(value));
         return group->setValue(index, CN);
         break;
       case CCopasiParameter::GROUP:
       case CCopasiParameter::INVALID:
         return false;
         break;
       default:
         break;
     }
   return false;
 }
bool setParameterValue (CCopasiParameterGroup * group, const std::string & name, const QString & value)
Set a parameter of a parameter group from a value given as a QString. Success = true is returned when the set operation was succesful, i.e., value == getParameterValue.
Parameters
CCopasiParameterGroup * group
const std::string & name
const QString & value
Returns
bool success.
Definition at line 174 of file qtUtilities.cpp.
References CCopasiParameterGroup::getIndex(), and setParameterValue().
 {return setParameterValue(group, group->getIndex(name), value);}
void vectorOfStrings2QStringList (std::vector< std::string > vs, QStringList & qsl)
This converts a std::vector<std::string> into a QStringList
Definition at line 205 of file qtUtilities.cpp.
References FROM_UTF8.
Referenced by ReactionsWidget1::FillWidgetFromRI(), CQArrayAnnotationsWidget::initSelectionTable(), and ParameterTable::updateTable().
 {
   qsl.clear();
   size_t i, imax = vs.size();
   for (i = 0; i < imax; ++i) qsl += FROM_UTF8(vs[i]);
 }