COPASI API: CMatrix< CType > Class Template Reference
CMatrix< CType > Class Template Reference
#include <CStepMatrix.h>
Public Types
typedef CType elementType
Public Member Functions
bool applyPivot (const CVector< size_t > &pivot)
virtual CType * array ()
virtual const CType * array () const
CMatrix (size_t rows=0, size_t cols=0)
CMatrix (const CMatrix< CType > &src)
virtual size_t numCols () const
virtual size_t numRows () const
virtual elementType & operator() (const size_t &row, const size_t &col)
virtual const elementType & operator() (const size_t &row, const size_t &col) const
virtual CMatrix< CType > & operator= (const CMatrix< CType > &rhs)
virtual CMatrix< CType > & operator= (const CType &value)
virtual CType * operator[] (size_t row)
virtual const CType * operator[] (size_t row) const
virtual void resize (size_t rows, size_t cols, const bool &copy=false)
virtual size_t size () const
virtual ~CMatrix ()
Protected Attributes
CType * mArray
size_t mCols
size_t mRows
Friends
std::ostream & operator<< (std::ostream &os, const CMatrix< CType > &A)
Detailed Description
template<class CType>
class CMatrix< CType >
Template class CMatrix < class CType > This template class is a simple matrix class allowing standard C-style and fortran style access to the elements. It also supplies an ostream operator.
Definition at line 21 of file CStepMatrix.h.
Member Typedef Documentation
template<class CType> typedef CType CMatrix< CType >::elementType
Definition at line 70 of file CMatrix.h.
Constructor & Destructor Documentation
template<class CType> CMatrix< CType >::CMatrix (size_t rows = 0, size_t cols = 0) inline
Default constructor
Parameters
size_t rows (default = 0)
size_t cols (default = 0)
Definition at line 96 of file CMatrix.h.
                                             :
     mRows(0),
     mCols(0),
     mArray(NULL)
   {
     resize(rows, cols);
   }
template<class CType> CMatrix< CType >::CMatrix (const CMatrix< CType > & src) inline
Copy constructor
Parameters
const CMatrix <CType> & src
Definition at line 108 of file CMatrix.h.
                                       :
     mRows(0),
     mCols(0),
     mArray(NULL)
   {
     resize(src.mRows, src.mCols);
     if (mRows && mCols)
       memcpy(mArray, src.mArray, mRows * mCols * sizeof(CType));
   }
template<class CType> virtual CMatrix< CType >::~CMatrix () inline virtual
Destructor.
Definition at line 122 of file CMatrix.h.
   {
     if (mArray)
       delete [] mArray;
   }
Member Function Documentation
template<class CType> bool CMatrix< CType >::applyPivot (const CVector< size_t > & pivot) inline
Reorder the rows according to the provided pivots
Parameters
const CVector<size_t> & pivot
Returns
bool success
Definition at line 351 of file CMatrix.h.
Referenced by CExperiment::read().
   {
     if (pivot.size() != mRows) return false;
     CVector< bool > Applied(mRows);
     Applied = false;
     CType *pTmp = new CType[mCols];
     size_t i;
     size_t to;
     size_t from;
     for (i = 0; i < mRows; i++)
       if (!Applied[i])
         {
           to = i;
           from = pivot[i];
           if (to != from)
             {
               memcpy(pTmp, mArray + i * mCols, mCols * sizeof(CType));
               while (from != i)
                 {
                   memcpy(mArray + to * mCols, mArray + from * mCols, mCols * sizeof(CType));
                   Applied[to] = true;
                   to = from;
                   from = pivot[to];
                 }
               memcpy(mArray + to * mCols, pTmp, mCols * sizeof(CType));
             }
           Applied[to] = true;
         }
     pdeletev(pTmp);
     return true;
   }
template<class CType> virtual CType* CMatrix< CType >::array () inline virtual
Retrieve the array of the matrix elements. This is suitable for interfacing with clapack routines.
Returns
CType * array
Definition at line 337 of file CMatrix.h.
Referenced by CLinkMatrix::applyColumnPivot(), CLinkMatrix::applyRowPivot(), CLinkMatrix::build(), CBitPatternTreeMethod::buildFluxModes(), CBitPatternMethod::buildFluxModes(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CSSAMethod::buildKineticMatrix(), CModel::buildMoieties(), CModel::buildStoi(), CSSAMethod::buildStoichiometry(), CEigen::calcEigenValues(), CFitProblem::calculate(), CLNAMethod::calculateCovarianceMatrixFull(), CLNAMethod::calculateCovarianceMatrixReduced(), CFitProblem::calculateCrossValidation(), CModel::calculateDerivatives(), CModel::calculateDerivativesX(), CModel::calculateElasticityMatrix(), CModel::calculateJacobian(), CModel::calculateJacobianX(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CMathModel::calculateRootDerivatives(), CMathModel::calculateRootJacobian(), CFitProblem::calculateStatistics(), CExperiment::calculateStatistics(), CMCAMethod::calculateUnscaledConcentrationCC(), CMCAMethod::calculateUnscaledElasticities(), CMCAMethod::calculateUnscaledFluxCC(), CMCAMethod::checkSummationTheorems(), CStepMatrix::CStepMatrix(), CSSAMethod::decomposeJacobian(), CSSAMethod::diag(), CLyapWolfMethod::evalF(), CExperiment::getErrorMeanSD(), CExperiment::getErrorSum(), CModel::handleUnusedMetabolites(), COptMethodLevenbergMarquardt::hessian(), CExperiment::initializeScalingMatrix(), CEFMMethod::isValidProblem(), CLinkMatrix::leftMultiply(), CSparseMatrix::operator const CMatrix< C_FLOAT64 >(), CSparseMatrix::operator=(), COptMethodLevenbergMarquardt::optimise(), CBitPatternMethod::performRankTest(), CQSimpleSelectionTree::populateTree(), CSteadyStateTask::process(), CLinkMatrix::rightMultiply(), CMCAMethod::scaleMCA(), CCSPMethod::sminverse(), and CNewtonMethod::solveJacobianXeqB().
 {return mArray;}
template<class CType> virtual const CType* CMatrix< CType >::array () const inline virtual
Retrieve the array of the matrix elements. This is suitable for interfacing with clapack routines.
Returns
const CType * array
Definition at line 344 of file CMatrix.h.
 {return mArray;}
template<class CType> virtual size_t CMatrix< CType >::numCols () const inline virtual
The number of columns of the matrix
Returns
size_t cols
Definition at line 144 of file CMatrix.h.
Referenced by CLinkMatrix::applyColumnPivot(), CLinkMatrix::applyRowPivot(), CLinkMatrix::build(), CBitPatternMethod::buildFluxModeMatrix(), CBitPatternTreeMethod::buildFluxModes(), CBitPatternMethod::buildFluxModes(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CModel::buildRedStoi(), CEigen::calcEigenValues(), CFitProblem::calculate(), CLNAMethod::calculateCovarianceMatrixReduced(), CFitProblem::calculateCrossValidation(), CModel::calculateElasticityMatrix(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CExperiment::calculateStatistics(), CMCAMethod::calculateUnscaledConcentrationCC(), CMCAMethod::calculateUnscaledFluxCC(), CMCAMethod::checkSummationTheorems(), CBitPatternMethod::combine(), CExperiment::compile(), CMCAMethod::createLinkMatrix(), CStepMatrix::CStepMatrix(), CSSAMethod::decomposeJacobian(), CExperiment::getErrorMeanSD(), CExperiment::getErrorSum(), CModel::handleUnusedMetabolites(), COptMethodLevenbergMarquardt::hessian(), CBitPatternMethod::initialize(), CBitPatternTreeMethod::initialize(), CExperiment::initializeScalingMatrix(), CEFMMethod::isValidProblem(), CLinkMatrix::leftMultiply(), LUfactor(), CLinkMatrixView::numCols(), CSparseMatrix::operator=(), CHybridMethod::outputDebug(), CHybridMethodODE45::outputDebug(), CHybridMethodLSODA::outputDebug(), CBitPatternMethod::performRankTest(), CExperiment::printResult(), CMCAMethod::resizeAllMatrices(), CLinkMatrix::rightMultiply(), CMCAMethod::scaleMCA(), CCSPMethod::setVectors(), CNewtonMethod::solveJacobianXeqB(), CExperiment::storeExtendedTimeSeriesData(), CExperiment::sumOfSquares(), CExperiment::sumOfSquaresStore(), CExperiment::updateFittedPointValues(), and CExperiment::updateFittedPointValuesFromExtendedTimeSeries().
 {return mCols;}
template<class CType> virtual size_t CMatrix< CType >::numRows () const inline virtual
The number of rows of the matrix.
Returns
size_t rows
Definition at line 138 of file CMatrix.h.
Referenced by CLinkMatrix::applyColumnPivot(), CLinkMatrix::applyRowPivot(), CLinkMatrix::build(), CBitPatternMethod::buildFluxModeMatrix(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CEigen::calcEigenValues(), CLNAMethod::calculateCovarianceMatrixReduced(), CHybridMethodLSODA::calculateDerivative(), CHybridMethod::calculateDerivative(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CExperiment::calculateStatistics(), CMCAMethod::calculateUnscaledConcentrationCC(), CMCAMethod::calculateUnscaledFluxCC(), CHybridMethod::checkModel(), CHybridMethodLSODA::checkModel(), CHybridMethodODE45::checkModel(), CMCAMethod::checkSummationTheorems(), CExperiment::compile(), CSSAMethod::decomposeJacobian(), CExperiment::getErrorMeanSD(), CExperiment::getErrorSum(), CModel::handleUnusedMetabolites(), CBitPatternMethod::initialize(), CExperiment::initializeScalingMatrix(), CLinkMatrix::leftMultiply(), LUfactor(), CLinkMatrixView::numRows(), CSparseMatrix::operator=(), CHybridMethod::outputDebug(), CHybridMethodODE45::outputDebug(), CHybridMethodLSODA::outputDebug(), CMCAMethod::resizeAllMatrices(), CLinkMatrix::rightMultiply(), CCSPMethod::setVectors(), CNewtonMethod::solveJacobianXeqB(), and CModel::suitableForStochasticSimulation().
 {return mRows;}
template<class CType> virtual elementType& CMatrix< CType >::operator() (const size_t & row, const size_t & col) inline virtual
Retrieve a matrix element using c-style indexing.
Parameters
const size_t & row
const size_t & col
Returns
const elementType & element
Definition at line 312 of file CMatrix.h.
   {
     assert(row < mRows && col < mCols);
     return *(mArray + row * mCols + col);
   }
template<class CType> virtual const elementType& CMatrix< CType >::operator() (const size_t & row, const size_t & col) const inline virtual
Retrieve a matrix element using c-style indexing.
Parameters
const size_t & row
const size_t & col
Returns
const elementType & element
Definition at line 325 of file CMatrix.h.
   {
     assert(row < mRows && col < mCols);
     return *(mArray + row * mCols + col);
   }
template<class CType> virtual CMatrix<CType>& CMatrix< CType >::operator= (const CMatrix< CType > & rhs) inline virtual
Assignment operator
Parameters
const CMatrix <CType> & rhs
Returns
CMatrix <CType> & lhs
Definition at line 222 of file CMatrix.h.
   {
     if (mRows != rhs.mRows || mCols != rhs.mCols)
       resize(rhs.mRows, rhs.mCols);
     memcpy(mArray, rhs.mArray, mRows * mCols * sizeof(CType));
     return *this;
   }
template<class CType> virtual CMatrix<CType>& CMatrix< CType >::operator= (const CType & value) inline virtual
Assignment operator
Parameters
const CType & value
Returns
CMatrix <CType> & lhs
Definition at line 237 of file CMatrix.h.
   {
     CType * pIt = mArray;
     CType * pEnd = pIt + mRows * mCols;
     for (; pIt != pEnd; ++pIt) *pIt = value;
     return *this;
   }
template<class CType> virtual CType* CMatrix< CType >::operator[] (size_t row) inline virtual
Retrieve a row of the matrix using c-style indexing
Parameters
size_t row
Returns
CType * row
Definition at line 295 of file CMatrix.h.
   {return mArray + row * mCols;}
template<class CType> virtual const CType* CMatrix< CType >::operator[] (size_t row) const inline virtual
Retrieve a row of the matrix using c-style indexing
Parameters
size_t row
Returns
const CType * row
Definition at line 303 of file CMatrix.h.
   {return mArray + row * mCols;}
template<class CType> virtual void CMatrix< CType >::resize (size_t rows, size_t cols, const bool & copy = false) inline virtual
Resize the matrix. The previous content is lost
Parameters
size_t rows
size_t cols
Definition at line 151 of file CMatrix.h.
Referenced by CCSPMethod::basisRefinement(), CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CSSAMethod::buildKineticMatrix(), CModel::buildRedStoi(), CModel::buildStoi(), CSSAMethod::buildStoichiometry(), CEigen::calcEigenValues(), CLNAMethod::calculateCovarianceMatrixFull(), CLNAMethod::calculateCovarianceMatrixReduced(), CModel::calculateJacobian(), CModel::calculateJacobianX(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CMathModel::calculateRootJacobian(), CFitProblem::calculateStatistics(), CMCAMethod::calculateUnscaledConcentrationCC(), CTimeSeries::clear(), CMatrix< CFitConstraint * >::CMatrix(), CTimeSeries::compile(), CMCAMethod::createLinkMatrix(), CCSPMethod::CSPImportanceIndex(), CCSPMethod::CSPParticipationIndex(), CCSPMethod::CSPradicalPointer(), CCSPMethod::cspstep(), CSSAMethod::decomposeJacobian(), CSSAMethod::diag(), CTimeSeries::increaseAllocation(), COptMethodPS::initialize(), COptMethodLevenbergMarquardt::initialize(), COptMethodNelderMead::initialize(), CFitProblem::initialize(), CSteadyStateTask::initialize(), CExperiment::initializeScalingMatrix(), CTSSAMethod::integrationMethodStart(), CLinkMatrix::leftMultiply(), CTSSAMethod::mat_anal_fast_space(), CTSSAMethod::mat_anal_mod(), CTSSAMethod::mat_anal_mod_space(), CILDMMethod::newton(), CILDMModifiedMethod::newton_new(), CSparseMatrix::operator const CMatrix< C_FLOAT64 >(), CMatrix< CFitConstraint * >::operator=(), CCSPMethod::predifineAnnotation(), CCSPMethod::printResult(), CExperiment::read(), CMCAMethod::resizeAllMatrices(), CLNAMethod::resizeAllMatrices(), CLinkMatrix::rightMultiply(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), CCSPMethod::sminverse(), CILDMMethod::start(), CILDMModifiedMethod::start(), CCSPMethod::start(), CLyapWolfMethod::start(), CILDMMethod::step(), CILDMModifiedMethod::step(), CCSPMethod::step(), CTSSAMethod::sylvester(), CSteadyStateTask::updateMatrices(), and CCSPMethod::yCorrection().
   {
     if (rows != mRows ||  cols != mCols)
       {
         size_t OldRows = mRows;
         size_t OldCols = mCols;
         CType * OldArray = mArray;
         mArray = NULL;
         if (rows != 0 && cols != 0)
           {
             try
               {
                 // We need to detect size_t overflow
                 if ((C_FLOAT64) rows * (C_FLOAT64) cols * (C_FLOAT64) sizeof(CType) >= (C_FLOAT64) std::numeric_limits< size_t >::max())
                   {
                     mArray = NULL;
                   }
                 else
                   {
                     mArray = new CType[rows * cols];
                   }
               }
             catch (...)
               {
                 mArray = NULL;
               }
             if (mArray == NULL)
               {
                 mRows = 0;
                 mCols = 0;
                 CCopasiMessage(CCopasiMessage::EXCEPTION, MCopasiBase + 1, rows * cols * sizeof(CType));
               }
             if (copy &&
                 mArray != NULL &&
                 OldArray != NULL)
               {
                 // We copy the top left matrix (min(rows, OldRows), min(cols, OldCols);
                 size_t CopiedRows = std::min(rows, OldRows);
                 size_t CopiedColumns = std::min(cols, OldCols);
                 CType * pOldRow = OldArray;
                 CType * pOldRowEnd = pOldRow +  CopiedRows * OldCols;
                 CType * pRow = mArray;
                 for (; pOldRow != pOldRowEnd; pOldRow += OldCols, pRow += cols)
                   {
                     memcpy(pRow, pOldRow, CopiedColumns * sizeof(CType));
                   }
               }
           }
         if (OldArray)
           {
             delete [] OldArray;
           }
       }
     mRows = rows;
     mCols = cols;
   }
template<class CType> virtual size_t CMatrix< CType >::size () const inline virtual
The number of elements stored in the matrix.
Returns
size_t size
Definition at line 132 of file CMatrix.h.
Referenced by CBitPatternMethod::buildKernelMatrix(), CBitPatternTreeMethod::buildKernelMatrix(), CEigen::calcEigenValues(), CLNAMethod::calculateCovarianceMatrixReduced(), CBitPatternMethod::CalculateKernel(), CBitPatternTreeMethod::CalculateKernel(), CMathModel::calculateRootJacobian(), CMCAMethod::calculateUnscaledElasticities(), CMCAMethod::checkSummationTheorems(), CStepMatrix::CStepMatrix(), CSSAMethod::diag(), CExperiment::initializeScalingMatrix(), CEFMMethod::isValidProblem(), CLinkMatrix::leftMultiply(), CSteadyStateTask::process(), CLinkMatrix::rightMultiply(), CNewtonMethod::solveJacobianXeqB(), and CILDMMethod::step().
 {return mRows * mCols;}
Friends And Related Function Documentation
template<class CType> std::ostream& operator<< (std::ostream & os, const CMatrix< CType > & A) friend
Output stream operator
Parameters
ostream & os
const CMatrix< CType > & A
Returns
ostream & os
Definition at line 809 of file CMatrix.h.
 {
   os << "Matrix(" << A.mRows << "x" << A.mCols << ")" << std::endl;
   size_t i, j;
   CType * tmp = A.mArray;
   for (i = 0; i < A.mRows; i++)
     {
       for (j = 0; j < A.mCols; j++)
         os << "\t" << *(tmp++);
       os << std::endl;
     }
   return os;
 }
Member Data Documentation
template<class CType> CType* CMatrix< CType >::mArray protected
The array storing the matrix elements
Definition at line 87 of file CMatrix.h.
Referenced by CMatrix< CFitConstraint * >::applyPivot(), CMatrix< CFitConstraint * >::array(), CMatrix< CFitConstraint * >::CMatrix(), CMatrix< CFitConstraint * >::operator()(), CMatrix< CFitConstraint * >::operator=(), CMatrix< CFitConstraint * >::operator[](), CMatrix< CFitConstraint * >::resize(), and CMatrix< CFitConstraint * >::~CMatrix().
template<class CType> size_t CMatrix< CType >::mCols protected
Number of columns in the matrix
Definition at line 82 of file CMatrix.h.
Referenced by CMatrix< CFitConstraint * >::applyPivot(), CMatrix< CFitConstraint * >::CMatrix(), CMatrix< CFitConstraint * >::numCols(), CMatrix< CFitConstraint * >::operator=(), CMatrix< CFitConstraint * >::operator[](), CMatrix< CFitConstraint * >::resize(), and CMatrix< CFitConstraint * >::size().
template<class CType> size_t CMatrix< CType >::mRows protected
Number of rows in the matrix.
Definition at line 77 of file CMatrix.h.
Referenced by CMatrix< CFitConstraint * >::applyPivot(), CMatrix< CFitConstraint * >::CMatrix(), CMatrix< CFitConstraint * >::numRows(), CMatrix< CFitConstraint * >::operator()(), CMatrix< CFitConstraint * >::operator=(), CMatrix< CFitConstraint * >::resize(), and CMatrix< CFitConstraint * >::size().
The documentation for this class was generated from the following files:
CStepMatrix.h
CMatrix.h