COPASI API: CNormalItem Class Reference
CNormalItem Class Reference
#include <CNormalItem.h>
Public Types
enum Type { CONSTANT, VARIABLE }
Public Member Functions
CNormalItem ()
CNormalItem (const std::string &name, const Type &type)
CNormalItem (const CNormalItem &src)
virtual CNormalBase * copy () const
const std::string getName () const
const Type & getType () const
bool operator< (const CNormalItem &rhs) const
CNormalItem & operator= (const CNormalItem &src)
bool operator== (const CNormalItem &rhs) const
bool setName (const std::string &name)
bool setType (const Type &type)
virtual bool simplify ()
virtual std::string toString () const
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Public Attributes
std::string mName
Type mType
Friends
std::ostream & operator<< (std::ostream &os, const CNormalItem &d)
Detailed Description
The class for items used in CNormal
Definition at line 22 of file CNormalItem.h.
Member Enumeration Documentation
enum CNormalItem::Type
Enumeration of possible item types.
Enumerator
CONSTANT
VARIABLE
Definition at line 28 of file CNormalItem.h.
     {
       CONSTANT,
       VARIABLE
     };
Constructor & Destructor Documentation
CNormalItem::CNormalItem ()
Default constructor
Definition at line 33 of file CNormalItem.cpp.
Referenced by copy().
                         : CNormalBase(), mName("no name")
 {}
CNormalItem::CNormalItem (const std::string & name, const Type & type)
Data constructor
Definition at line 39 of file CNormalItem.cpp.
                                                                : CNormalBase(), mName(name), mType(type)
 {}
CNormalItem::CNormalItem (const CNormalItem & src)
Copy contructor
Definition at line 45 of file CNormalItem.cpp.
                                               : CNormalBase(src), mName(src.mName), mType(src.mType)
 {}
Member Function Documentation
CNormalBase * CNormalItem::copy () const virtual
Implements CNormalBase.
Definition at line 127 of file CNormalItem.cpp.
References CNormalItem().
   {
     return new CNormalItem(*this);
   }
const std::string CNormalItem::getName () const
Retrieve the name of this item.
Returns
mName
Definition at line 82 of file CNormalItem.cpp.
References mName.
Referenced by CNormalChoice::checkConditionTree(), CNormalChoiceLogical::checkConditionTree(), contains_necessary_mass_action_elements(), convertToCEvaluationNode(), and normalize_variable_names().
   {
     return mName;
   }
const CNormalItem::Type & CNormalItem::getType () const
Retrieve the type of this item.
Returns
mType
Definition at line 91 of file CNormalItem.cpp.
References mType.
Referenced by CNormalChoice::checkConditionTree(), CNormalChoiceLogical::checkConditionTree(), contains_necessary_mass_action_elements(), convertToCEvaluationNode(), and normalize_variable_names().
   {
     return mType;
   }
bool CNormalItem::operator< (const CNormalItem & rhs) const
Examine inequality of two item.
Returns
bool.
Definition at line 107 of file CNormalItem.cpp.
References mName, and mType.
   {
     if (mType < rhs.mType)
       return true;
     if (rhs.mType < mType)
       return false;
     return (mName < rhs.mName);
   }
CNormalItem & CNormalItem::operator= (const CNormalItem & src)
Assignment operator
Definition at line 51 of file CNormalItem.cpp.
References mName, and mType.
 {
   this->mName = src.mName;
   this->mType = src.mType;
   return *this;
 }
bool CNormalItem::operator== (const CNormalItem & rhs) const
Examine equality of two items.
Returns
bool.
Definition at line 100 of file CNormalItem.cpp.
References mName, and mType.
   {return ((rhs.mName == mName) && (rhs.mType == mType));}
bool CNormalItem::setName (const std::string & name)
Set the name of this item
Returns
true.
Definition at line 62 of file CNormalItem.cpp.
References mName.
Referenced by normalize_variable_names(), and test_simplify::test_simplify_1().
 {
   mName = name;
   return true;
 }
bool CNormalItem::setType (const Type & type)
Set the type of this item.
Returns
true.
Definition at line 72 of file CNormalItem.cpp.
References mType.
Referenced by test_simplify::test_simplify_1().
 {
   mType = type;
   return true;
 }
virtual bool CNormalItem::simplify () inline virtual
Implements CNormalBase.
Definition at line 97 of file CNormalItem.h.
 {return true;};
std::string CNormalItem::toString () const virtual
Implements CNormalBase.
Definition at line 116 of file CNormalItem.cpp.
References mName.
Referenced by operator<<().
   {
     return this->mName;
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CNormalItem & d) friend
Definition at line 121 of file CNormalItem.cpp.
 {
   os << d.toString();
   return os;
 }
Member Data Documentation
std::string CNormalItem::mName
Definition at line 34 of file CNormalItem.h.
Referenced by getName(), operator<(), operator=(), operator==(), setName(), and toString().
Type CNormalItem::mType
Definition at line 35 of file CNormalItem.h.
Referenced by getType(), operator<(), operator=(), operator==(), and setType().
The documentation for this class was generated from the following files:
CNormalItem.h
CNormalItem.cpp