COPASI API: CZeroSet Class Reference
CZeroSet Class Reference
#include <CZeroSet.h>
Classes
class CIndex
Public Member Functions
CZeroSet (const size_t &index=0)
CZeroSet (const CZeroSet &src)
size_t getNumberOfBits () const
const size_t & getNumberOfSetBits () const
size_t getNumberOfUnsetBits () const
bool isExtremeRay (const std::vector< CStepMatrixColumn * > &columns) const
bool isSet (const CIndex &index) const
CZeroSet & operator&= (const CZeroSet &rhs)
bool operator== (const CZeroSet &rhs) const
bool operator>= (const CZeroSet &rhs) const
CZeroSet & operator|= (const CZeroSet &rhs)
void setBit (const CIndex &index)
void unsetBit (const CIndex &index)
~CZeroSet ()
Static Public Member Functions
static CZeroSet intersection (const CZeroSet &set1, const CZeroSet &set2)
Private Member Functions
size_t countSetBits (size_t bits)
Private Attributes
CVector< size_t > mBitSet
size_t mIgnoredBits
size_t mNumberSetBits
Friends
std::ostream & operator<< (std::ostream &, const CZeroSet &)
Detailed Description
Definition at line 30 of file CZeroSet.h.
Constructor & Destructor Documentation
CZeroSet::CZeroSet (const size_t & index = 0)
Definition at line 80 of file CZeroSet.cpp.
References C_INVALID_INDEX, and mBitSet.
                                      :
     mBitSet(size / (CHAR_BIT * sizeof(size_t)) + 1),
     mIgnoredBits(mBitSet.size() * CHAR_BIT * sizeof(size_t) - size),
     mNumberSetBits(size)
 {
   mBitSet = C_INVALID_INDEX;
 }
CZeroSet::CZeroSet (const CZeroSet & src)
Definition at line 88 of file CZeroSet.cpp.
                                       :
     mBitSet(src.mBitSet),
     mIgnoredBits(src.mIgnoredBits),
     mNumberSetBits(src.mNumberSetBits)
 {}
CZeroSet::~CZeroSet ()
Definition at line 94 of file CZeroSet.cpp.
 {}
Member Function Documentation
size_t CZeroSet::countSetBits (size_t bits) inline private
Definition at line 178 of file CZeroSet.h.
Referenced by operator&=(), and operator|=().
   {
     size_t numberOfBits = 0;
     for (size_t i = 0; i < CHAR_BIT * sizeof(size_t); ++i)
       {
         if ((bits >> i) & 1)
           {
             numberOfBits++;
           }
       }
     return numberOfBits;
   }
size_t CZeroSet::getNumberOfBits () const inline
Definition at line 95 of file CZeroSet.h.
References mBitSet, mIgnoredBits, and CVectorCore< CType >::size().
Referenced by CStepMatrixColumn::getAllUnsetBitIndexes(), and operator<<().
   {
     return mBitSet.size() * CHAR_BIT * sizeof(size_t) - mIgnoredBits;
   }
const size_t& CZeroSet::getNumberOfSetBits () const inline
Definition at line 85 of file CZeroSet.h.
References mNumberSetBits.
Referenced by CBitPatternTreeMethod::combine(), and CBitPatternMethod::combine().
   {
     return mNumberSetBits;
   }
size_t CZeroSet::getNumberOfUnsetBits () const inline
Definition at line 90 of file CZeroSet.h.
References mBitSet, mIgnoredBits, mNumberSetBits, and CVectorCore< CType >::size().
Referenced by CStepMatrix::getUnsetBitIndexes().
   {
     return mBitSet.size() * CHAR_BIT * sizeof(size_t) - mIgnoredBits - mNumberSetBits;
   }
static CZeroSet CZeroSet::intersection (const CZeroSet & set1, const CZeroSet & set2) inline static
Definition at line 137 of file CZeroSet.h.
Referenced by CBitPatternTreeMethod::combine(), and CBitPatternMethod::combine().
   {
     CZeroSet Intersection(set1);
     return Intersection &= set2;
   }
bool CZeroSet::isExtremeRay (const std::vector< CStepMatrixColumn * > & columns) const
Definition at line 97 of file CZeroSet.cpp.
Referenced by CBitPatternTreeMethod::combine(), and CBitPatternMethod::combine().
 {
   std::vector< CStepMatrixColumn * >::const_iterator it = columns.begin();
   std::vector< CStepMatrixColumn * >::const_iterator end = columns.end();
   for (; it != end; ++it)
     {
       if (*it != NULL &&
           (*it)->getZeroSet() >= *this)
         {
           return false;
         }
     }
   return true;
 }
bool CZeroSet::isSet (const CIndex & index) const inline
Definition at line 80 of file CZeroSet.h.
References CZeroSet::CIndex::mBit, mBitSet, and CZeroSet::CIndex::mIndex.
Referenced by CStepMatrixColumn::getAllUnsetBitIndexes(), CStepMatrix::getUnsetBitIndexes(), and operator<<().
   {
     return (mBitSet[index.mIndex] & index.mBit) > 0;
   }
CZeroSet& CZeroSet::operator&= (const CZeroSet & rhs) inline
Definition at line 118 of file CZeroSet.h.
References CVectorCore< CType >::array(), countSetBits(), mBitSet, mIgnoredBits, mNumberSetBits, and CVectorCore< CType >::size().
   {
     size_t * pIt = mBitSet.array();
     size_t * pEnd = pIt + mBitSet.size();
     const size_t * pRhs = rhs.mBitSet.array();
     mNumberSetBits = 0;
     for (; pIt != pEnd; ++pIt, ++pRhs)
       {
         *pIt &= *pRhs;
         mNumberSetBits += countSetBits(*pIt);
       }
     mNumberSetBits -= mIgnoredBits;
     return *this;
   }
bool CZeroSet::operator== (const CZeroSet & rhs) const inline
Definition at line 159 of file CZeroSet.h.
References CVectorCore< CType >::array(), mBitSet, mNumberSetBits, and CVectorCore< CType >::size().
   {
     if (mNumberSetBits != rhs.mNumberSetBits)
       return false;
     return memcmp(mBitSet.array(), rhs.mBitSet.array(),
                   mBitSet.size() * sizeof(size_t)) == 0;
   }
bool CZeroSet::operator>= (const CZeroSet & rhs) const inline
Definition at line 144 of file CZeroSet.h.
References CVectorCore< CType >::array(), mBitSet, and CVectorCore< CType >::size().
   {
     const size_t * pIt = mBitSet.array();
     const size_t * pEnd = pIt + mBitSet.size();
     const size_t * pRhs = rhs.mBitSet.array();
     for (; pIt != pEnd; ++pIt, ++pRhs)
       {
         if (*pIt != (*pIt | *pRhs))
           return false;
       }
     return true;
   }
CZeroSet& CZeroSet::operator|= (const CZeroSet & rhs) inline
Definition at line 100 of file CZeroSet.h.
References CVectorCore< CType >::array(), countSetBits(), mBitSet, mIgnoredBits, mNumberSetBits, and CVectorCore< CType >::size().
   {
     size_t * pIt = mBitSet.array();
     size_t * pEnd = pIt + mBitSet.size();
     const size_t * pRhs = rhs.mBitSet.array();
     mNumberSetBits = 0;
     for (; pIt != pEnd; ++pIt, ++pRhs)
       {
         *pIt |= *pRhs;
         mNumberSetBits += countSetBits(*pIt);
       }
     mNumberSetBits -= mIgnoredBits;
     return *this;
   }
void CZeroSet::setBit (const CIndex & index) inline
Definition at line 68 of file CZeroSet.h.
References CZeroSet::CIndex::mBit, mBitSet, CZeroSet::CIndex::mIndex, and mNumberSetBits.
   {
     mBitSet[index.mIndex] |= index.mBit;
     mNumberSetBits++;
   }
void CZeroSet::unsetBit (const CIndex & index) inline
Definition at line 74 of file CZeroSet.h.
References mBitSet, CZeroSet::CIndex::mIndex, CZeroSet::CIndex::mNotBit, and mNumberSetBits.
Referenced by CStepMatrixColumn::unsetBit().
   {
     mBitSet[index.mIndex] &= index.mNotBit;
     mNumberSetBits--;
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CZeroSet & set) friend
Definition at line 114 of file CZeroSet.cpp.
 {
   const size_t * pIt = set.mBitSet.array();
   const size_t * pEnd = pIt + set.mBitSet.size();
   size_t CurrentBit = 0;
   size_t LastBit = set.mBitSet.size() * CHAR_BIT * sizeof(size_t) - set.mIgnoredBits;
   os << ' ';
   for (; pIt != pEnd; ++pIt)
     {
       for (size_t i = 0;
            i < CHAR_BIT * sizeof(size_t) && CurrentBit < LastBit;
            ++i, ++CurrentBit)
         {
           if ((*pIt >> i) & 1)
             {
               os << 1;
             }
           else
             {
               os << 0;
             }
         }
       os << ' ';
     }
   os << " " << set.mNumberSetBits << std::endl;
   return os;
 }
Member Data Documentation
CVector<size_t> CZeroSet::mBitSet private
Definition at line 172 of file CZeroSet.h.
Referenced by CZeroSet(), getNumberOfBits(), getNumberOfUnsetBits(), isSet(), operator&=(), operator<<(), operator==(), operator>=(), operator|=(), setBit(), and unsetBit().
size_t CZeroSet::mIgnoredBits private
Definition at line 174 of file CZeroSet.h.
Referenced by getNumberOfBits(), getNumberOfUnsetBits(), operator&=(), operator<<(), and operator|=().
size_t CZeroSet::mNumberSetBits private
Definition at line 176 of file CZeroSet.h.
Referenced by getNumberOfSetBits(), getNumberOfUnsetBits(), operator&=(), operator<<(), operator==(), operator|=(), setBit(), and unsetBit().
The documentation for this class was generated from the following files:
CZeroSet.h
CZeroSet.cpp