COPASI API: CNormalProduct Class Reference
CNormalProduct Class Reference
#include <CNormalProduct.h>
Public Member Functions
bool checkSamePowerList (const CNormalProduct &rhs) const
CNormalProduct ()
CNormalProduct (const CNormalProduct &src)
virtual CNormalBase * copy () const
CNormalGeneralPower * getDenominator () const
const C_FLOAT64 & getFactor () const
const std::set
< CNormalItemPower
*, compareItemPowers > & getItemPowers () const
bool multiply (const C_FLOAT64 &number)
bool multiply (const CNormalItem &item)
bool multiply (const CNormalFunction &fun)
bool multiply (const CNormalChoice &choice)
bool multiply (const CNormalGeneralPower &pow)
bool multiply (const CNormalItemPower &itemPower)
bool multiply (const std::set< CNormalItemPower *, compareItemPowers > &itemPowers)
bool multiply (const CNormalProduct &product)
CNormalSum * multiply (const CNormalSum &sum)
const CNormalSum * multiply (const CNormalLcm &lcm)
bool operator< (const CNormalProduct &rhs) const
CNormalProduct & operator= (const CNormalProduct &src)
bool operator== (const CNormalProduct &rhs) const
bool remove (std::set< CNormalItemPower *, compareItemPowers >::iterator it)
bool remove (const CNormalItemPower &itemPower)
void setDenominatorsOne ()
bool setFactor (const C_FLOAT64 &number)
void setItemPowers (const std::set< CNormalItemPower *, compareItemPowers > &set)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalProduct ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Static Public Member Functions
static CNormalProduct * createUnitProduct ()
Private Attributes
C_FLOAT64 mFactor
std::set< CNormalItemPower
*, compareItemPowers > mItemPowers
Friends
std::ostream & operator<< (std::ostream &os, const CNormalProduct &d)
Detailed Description
The class for products used in CNormal
Definition at line 43 of file CNormalProduct.h.
Constructor & Destructor Documentation
CNormalProduct::CNormalProduct ()
Default constructor
Definition at line 54 of file CNormalProduct.cpp.
Referenced by copy(), createUnitProduct(), getDenominator(), and setDenominatorsOne().
                               : CNormalBase(), mFactor(1.0)
 {}
CNormalProduct::CNormalProduct (const CNormalProduct & src)
Copy contructor
Definition at line 60 of file CNormalProduct.cpp.
References mItemPowers.
                                                        : CNormalBase(src), mFactor(src.mFactor)
 {
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = src.mItemPowers.end();
   const CNormalItemPower* pSrcItemPower = NULL;
   CNormalItemPower* pDestItemPower = NULL;
   for (it = src.mItemPowers.begin(); it != itEnd; ++it)
     {
       pSrcItemPower = *it;
       pDestItemPower = new CNormalItemPower(*pSrcItemPower);
       bool result = this->mItemPowers.insert(pDestItemPower).second;
       assert(result == true);
     }
 }
CNormalProduct::~CNormalProduct () virtual
Destructor
Definition at line 94 of file CNormalProduct.cpp.
References mItemPowers.
 {
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     delete *it;
 }
Member Function Documentation
bool CNormalProduct::checkSamePowerList (const CNormalProduct & rhs) const
Definition at line 438 of file CNormalProduct.cpp.
References mItemPowers.
Referenced by operator==().
 {
   if (mItemPowers.size() != rhs.mItemPowers.size())
     return false;
   std::set< CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set< CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   std::set< CNormalItemPower*, compareItemPowers >::const_iterator it2;
   //std::set< CNormalItemPower*, compareItemPowers >::const_iterator it2End = rhs.mItemPowers.end();
   for (it = mItemPowers.begin(), it2 = rhs.mItemPowers.begin(); it != itEnd; ++it, ++it2)
     {
       if (!(**it == **it2))
         return false;
     }
   return true;
 }
CNormalBase * CNormalProduct::copy () const virtual
Implements CNormalBase.
Definition at line 507 of file CNormalProduct.cpp.
References CNormalProduct().
 {
   return new CNormalProduct(*this);
 }
CNormalProduct * CNormalProduct::createUnitProduct () static
Returns a product that is 1. In this case it only creates a new product instance with new.
Definition at line 746 of file CNormalProduct.cpp.
References CNormalProduct().
Referenced by CNormalSum::createUnitSum(), and CNormalSum::simplify().
 {
   return new CNormalProduct();
 }
CNormalGeneralPower * CNormalProduct::getDenominator () const
Definition at line 669 of file CNormalProduct.cpp.
References CNormalSum::add(), CNormalFraction::checkDenominatorOne(), CNormalProduct(), CNormalGeneralPower::getLeft(), CNormalGeneralPower::getType(), mItemPowers, CNormalGeneralPower::multiply(), CNormalGeneralPower::POWER, CNormalItemPower::POWER, pResult, CNormalFraction::setDenominator(), CNormalGeneralPower::setLeft(), CNormalFraction::setNumerator(), CNormalGeneralPower::setRight(), and CNormalGeneralPower::setType().
Referenced by CNormalSum::simplify().
 {
   // go though all items that are general powers and check for general items
   // of type power that have denominators in their base that differ from 1
   // from all those denominators create a common denoninator and return it
   // first we generate a general power that is 1
   CNormalGeneralPower* pResult = new CNormalGeneralPower();
   pResult->setType(CNormalGeneralPower::POWER);
   CNormalSum* pTmpSum = new CNormalSum();
   CNormalFraction* pTmpFrac = new CNormalFraction();
   CNormalProduct* pTmpProduct = new CNormalProduct();
   pTmpSum->add(*pTmpProduct);
   delete pTmpProduct;
   pTmpFrac->setNumerator(*pTmpSum);
   pTmpFrac->setDenominator(*pTmpSum);
   pResult->setLeft(*pTmpFrac);
   pResult->setRight(*pTmpFrac);
   delete pTmpFrac;
   std::set<CNormalItemPower*, compareItemPowers>::const_iterator it = this->mItemPowers.begin(), endit = this->mItemPowers.end();
   while (it != endit)
     {
       if ((*it)->getItemType() == CNormalItemPower::POWER)
         {
           CNormalGeneralPower* pTmpPow = dynamic_cast<CNormalGeneralPower*>(&(*it)->getItem());
           assert(pTmpPow != NULL);
           // only set the numerator to 1 if it is a power item and the
           // denominator is not 1
           if (pTmpPow->getType() == CNormalGeneralPower::POWER && !pTmpPow->getLeft().checkDenominatorOne())
             {
               // set the numerator to 1
               pTmpPow = new CNormalGeneralPower(*pTmpPow);
               pTmpPow->getLeft().setNumerator(*pTmpSum);
               pResult->multiply(*pTmpPow);
               delete pTmpPow;
             }
         }
       ++it;
     }
   delete pTmpSum;
   return pResult;
 }
const C_FLOAT64 & CNormalProduct::getFactor () const
Retrieve the factor of this product.
Returns
mFactor.
Definition at line 424 of file CNormalProduct.cpp.
References mFactor.
Referenced by CNormalSum::add(), convertToCEvaluationNode(), createSum(), multiply(), compareProducts::operator()(), CNormalSum::simplify(), test_biomodels217_expression::test_term_den1(), test_biomodels217_expression::test_term_den2(), test_biomodels217_expression::test_term_den3(), test_biomodels217_expression::test_term_den4(), test_biomodels217_expression::test_term_den5(), test_biomodels217_expression::test_term_den6(), test_biomodels217_expression::test_term_den7(), test_biomodels217_expression::test_term_num1(), test_biomodels217_expression::test_term_num2(), test_biomodels217_expression::test_term_num3(), test_biomodels217_expression::test_term_num4(), test_biomodels217_expression::test_term_num5(), test_biomodels217_expression::test_term_num6(), and test_biomodels217_expression::test_term_num7().
 {
   return mFactor;
 }
const std::set< CNormalItemPower *, compareItemPowers > & CNormalProduct::getItemPowers () const
Retrieve the set of itempowers of this product.
Returns
mItemPowers.
Definition at line 433 of file CNormalProduct.cpp.
References mItemPowers.
Referenced by CNormalLcm::add(), contains_necessary_mass_action_elements(), convertToCEvaluationNode(), multiply(), normalize_variable_names(), compareProducts::operator()(), CNormalLcm::remove(), CNormalSum::simplify(), test_biomodels217_expression::test_term_den1(), test_biomodels217_expression::test_term_den2(), test_biomodels217_expression::test_term_den3(), test_biomodels217_expression::test_term_den4(), test_biomodels217_expression::test_term_den5(), test_biomodels217_expression::test_term_den6(), test_biomodels217_expression::test_term_den7(), test_biomodels217_expression::test_term_num1(), test_biomodels217_expression::test_term_num2(), test_biomodels217_expression::test_term_num3(), test_biomodels217_expression::test_term_num4(), test_biomodels217_expression::test_term_num5(), test_biomodels217_expression::test_term_num6(), and test_biomodels217_expression::test_term_num7().
 {
   return mItemPowers;
 }
bool CNormalProduct::multiply (const C_FLOAT64 & number)
Multiply this product with a number.
Returns
true.
Definition at line 132 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
Referenced by createProduct(), CNormalGeneralPower::multiply(), multiply(), CNormalSum::simplify(), simplify(), and test_simplify::test_simplify_1().
 {
   mFactor = mFactor * number;
   if (fabs(mFactor) < 1.0E-100)
     {
       std::set<CNormalItemPower*, compareItemPowers>::iterator it = mItemPowers.begin(), endit = mItemPowers.end();
       while (it != endit)
         {
           delete *it;
           ++it;
         }
       mItemPowers.clear();
       //mPowers.clear();
     }
   return true;
 }
bool CNormalProduct::multiply (const CNormalItem & item)
Multiply an item to this product.
Returns
true.
Definition at line 235 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
 {
   if (fabs(mFactor) < 1.0E-100)
     return true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(item) == true)
         {
           (*it)->setExp((*it)->getExp() + 1.0);
           return true;
         }
     }
   CNormalItemPower* tmp = new CNormalItemPower(item, 1.0);
   mItemPowers.insert(tmp);
   return true;
 }
bool CNormalProduct::multiply (const CNormalFunction & fun)
Multiply a function to this product.
Returns
true.
Multiply an item to this product.
Returns
true.
Definition at line 209 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
 {
   if (fabs(mFactor) < 1.0E-100)
     return true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(fun) == true)
         {
           (*it)->setExp((*it)->getExp() + 1.0);
           return true;
         }
     }
   CNormalItemPower* tmp = new CNormalItemPower(fun, 1.0);
   mItemPowers.insert(tmp);
   return true;
 }
bool CNormalProduct::multiply (const CNormalChoice & choice)
Multiply a function to this product.
Returns
true.
Multiply an choice to this product.
Returns
true.
Definition at line 157 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
 {
   if (fabs(mFactor) < 1.0E-100)
     return true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(choice) == true)
         {
           (*it)->setExp((*it)->getExp() + 1.0);
           return true;
         }
     }
   CNormalItemPower* tmp = new CNormalItemPower(choice, 1.0);
   mItemPowers.insert(tmp);
   return true;
 }
bool CNormalProduct::multiply (const CNormalGeneralPower & pow)
Multiply a general power to this product.
Returns
true.
Multiply an item to this product.
Returns
true.
Definition at line 183 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
 {
   if (fabs(mFactor) < 1.0E-100)
     return true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(pow) == true)
         {
           (*it)->setExp((*it)->getExp() + 1.0);
           return true;
         }
     }
   CNormalItemPower* tmp = new CNormalItemPower(pow, 1.0);
   mItemPowers.insert(tmp);
   return true;
 }
bool CNormalProduct::multiply (const CNormalItemPower & itemPower)
Multiply an itempower to this product.
Returns
true.
Definition at line 261 of file CNormalProduct.cpp.
References CNormalItemPower::getExp(), CNormalItemPower::getItem(), mFactor, and mItemPowers.
 {
   if (fabs(mFactor) < 1.0E-100)
     return true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(itemPower.getItem()))
         {
           (*it)->setExp((*it)->getExp() + itemPower.getExp());
           return true;
         }
     }
   CNormalItemPower* tmp = new CNormalItemPower(itemPower);
   mItemPowers.insert(tmp);
   return true;
 }
bool CNormalProduct::multiply (const std::set< CNormalItemPower *, compareItemPowers > & itemPowers)
Multiply a list of itempowers to this product.
Returns
true.
Definition at line 287 of file CNormalProduct.cpp.
References mFactor, and multiply().
 {
   if (fabs(mFactor) < 1.0E-100)
     return true;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = itemPowers.end();
   for (it = itemPowers.begin(); it != itEnd; ++it)
     multiply(**it);
   return true;
 }
bool CNormalProduct::multiply (const CNormalProduct & product)
Multiply this product with another product.
Returns
true
Definition at line 352 of file CNormalProduct.cpp.
References getFactor(), getItemPowers(), mFactor, and multiply().
 {
   multiply(product.getFactor());
   if (fabs(mFactor) < 1.0E-100)
     return true;
   multiply(product.getItemPowers());
   return true;
 }
CNormalSum * CNormalProduct::multiply (const CNormalSum & sum)
Multiply this product with a sum NOT CONTAINING FRACTIONS!.
Returns
sum.
Definition at line 367 of file CNormalProduct.cpp.
References CNormalSum::add(), CNormalSum::getProducts(), and mFactor.
 {
   if (fabs(mFactor) < 1.0E-100)
     {
       CNormalSum* zeroSum = new CNormalSum();
       zeroSum->add(*this);
       return zeroSum;
     }
   CNormalSum* tmp = new CNormalSum(sum);
   CNormalSum* newsum = new CNormalSum();
   std::set<CNormalProduct*, compareProducts>::const_iterator it;
   std::set<CNormalProduct*, compareProducts>::const_iterator itEnd = tmp->getProducts().end();
   for (it = tmp->getProducts().begin(); it != itEnd; ++it)
     {
       (*it)->multiply(*this);
       newsum->add(**it);
     }
   delete tmp;
   return newsum;
 }
const CNormalSum * CNormalProduct::multiply (const CNormalLcm & lcm)
Multiply this product with a lcm.
Returns
true
Definition at line 395 of file CNormalProduct.cpp.
References CNormalSum::add(), CNormalLcm::getItemPowers(), CNormalLcm::getSums(), mFactor, and multiply().
 {
   if (fabs(mFactor) < 1.0E-100)
     {
       CNormalSum* zeroSum = new CNormalSum();
       zeroSum->add(*this);
       return zeroSum;
     }
   CNormalLcm* tmp = new CNormalLcm(lcm);
   multiply(tmp->getItemPowers());
   CNormalSum* sum = new CNormalSum();
   sum->add(*this);
   std::vector<CNormalSum*>::const_iterator it;
   std::vector<CNormalSum*>::const_iterator itEnd = tmp->getSums().end();
   for (it = tmp->getSums().begin(); it != itEnd; ++it)
     {
       sum->multiply(**it);
     }
   delete tmp;
   return sum;
 }
bool CNormalProduct::operator< (const CNormalProduct & rhs) const
Smaller operator
Definition at line 512 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
 {
   bool result = false;
   if (this->mFactor < rhs.mFactor)
     {
       result = true;
     }
   else if (this->mFactor == rhs.mFactor)
     {
       if (this->mItemPowers.size() < rhs.mItemPowers.size())
         {
           result = true;
         }
       else if (this->mItemPowers.size() == rhs.mItemPowers.size())
         {
           std::set<CNormalItemPower*, compareItemPowers >::const_iterator it = this->mItemPowers.begin(), endit = this->mItemPowers.end();
           std::set<CNormalItemPower*, compareItemPowers >::const_iterator it2 = rhs.mItemPowers.begin();
           compareItemPowers comp;
           while (result == false && it != endit)
             {
               if (comp(*it, *it2))
                 {
                   result = true;
                 }
               if (comp(*it2, *it))
                 {
                   break;
                 }
               ++it;
               ++it2;
             }
         }
     }
   return result;
 }
CNormalProduct & CNormalProduct::operator= (const CNormalProduct & src)
Assignment operator
Definition at line 79 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
 {
   mFactor = src.mFactor;
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set<CNormalItemPower*, compareItemPowers >::const_iterator itEnd = src.mItemPowers.end();
   for (it = src.mItemPowers.begin(); it != itEnd; ++it)
     mItemPowers.insert(new CNormalItemPower(**it));
   return *this;
 }
bool CNormalProduct::operator== (const CNormalProduct & rhs) const
Definition at line 457 of file CNormalProduct.cpp.
References checkSamePowerList(), and mFactor.
 {
   if (mFactor != rhs.mFactor)
     return false;
   if (checkSamePowerList(rhs))
     return true;
   return false;
 }
bool CNormalProduct::remove (std::set< CNormalItemPower *, compareItemPowers >::iterator it)
Remove an itempower from this product, provided it is a factor of it.
Returns
true.
Definition at line 305 of file CNormalProduct.cpp.
References mItemPowers.
 {
   delete(*it);
   mItemPowers.erase(it);
   return true;
 }
bool CNormalProduct::remove (const CNormalItemPower & itemPower)
Remove an itempower from this product, provided it is a factor of it. -used in multiplication with lcm-
Returns
true.
Definition at line 317 of file CNormalProduct.cpp.
References C_FLOAT64, CNormalItemPower::getExp(), CNormalItemPower::getItem(), and mItemPowers.
 {
   std::set <CNormalItemPower*, compareItemPowers >::iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::iterator itEnd = mItemPowers.end();
   for (it = mItemPowers.begin(); it != itEnd; ++it)
     {
       if ((*it)->getItem().areEqual(itemPower.getItem()))
         {
           C_FLOAT64 dif = (*it)->getExp() - itemPower.getExp();
           if (dif >= 1.0E-100)
             {
               (*it)->setExp(dif);
               return true;
             }
           if (fabs(dif) < 1.0E-100)
             {
               delete(*it);
               mItemPowers.erase(it);
               return true;
             }
           return false;
         }
     }
   return false;
 }
void CNormalProduct::setDenominatorsOne ()
Definition at line 716 of file CNormalProduct.cpp.
References CNormalSum::add(), CNormalProduct(), CNormalGeneralPower::getLeft(), CNormalGeneralPower::getType(), mItemPowers, CNormalGeneralPower::POWER, CNormalItemPower::POWER, and CNormalFraction::setDenominator().
Referenced by CNormalSum::simplify().
 {
   // goes through all items and sets the denominators of the bases of all
   // general power items of type power to one
   CNormalSum* pTmpSum = new CNormalSum();
   CNormalProduct* pTmpProduct = new CNormalProduct();
   pTmpSum->add(*pTmpProduct);
   delete pTmpProduct;
   std::set<CNormalItemPower*, compareItemPowers>::iterator it = this->mItemPowers.begin(), endit = this->mItemPowers.end();
   while (it != endit)
     {
       if ((*it)->getItemType() == CNormalItemPower::POWER)
         {
           CNormalGeneralPower* pGenPow = dynamic_cast<CNormalGeneralPower*>(&(*it)->getItem());
           assert(pGenPow != NULL);
           // only set the denominator to 1 if it is a power item
           if (pGenPow->getType() == CNormalGeneralPower::POWER)
             {
               pGenPow->getLeft().setDenominator(*pTmpSum);
             }
         }
       ++it;
     }
   delete pTmpSum;
 }
bool CNormalProduct::setFactor (const C_FLOAT64 & number)
Set the factor for this product.
Returns
true.
Definition at line 107 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
Referenced by createProduct(), and createSum().
 {
   mFactor = number;
   if (fabs(mFactor) < 1.0E-100)
     {
       std::set<CNormalItemPower*, compareItemPowers>::iterator it = mItemPowers.begin(), endit = mItemPowers.end();
       while (it != endit)
         {
           delete *it;
           ++it;
         }
       mItemPowers.clear();
       //mPowers.clear();
     }
   return true;
 }
void CNormalProduct::setItemPowers (const std::set< CNormalItemPower *, compareItemPowers > & set)
Sets the item powers of this product.
Definition at line 553 of file CNormalProduct.cpp.
References mItemPowers.
Referenced by normalize_variable_names().
 {
   std::set<CNormalItemPower*, compareItemPowers>::const_iterator it = this->mItemPowers.begin(), endit = this->mItemPowers.end();
   while (it != endit)
     {
       delete *it;
       ++it;
     }
   it = set.begin(), endit = set.end();
   this->mItemPowers.clear();
   while (it != endit)
     {
       this->mItemPowers.insert(new CNormalItemPower(**it));
       ++it;
     }
 }
bool CNormalProduct::simplify () virtual
Implements CNormalBase.
Definition at line 573 of file CNormalProduct.cpp.
References CNormalGeneralPower::checkIsOne(), mItemPowers, CNormalGeneralPower::multiply(), multiply(), CNormalGeneralPower::POWER, CNormalItemPower::POWER, CNormalItemPower::setExp(), CNormalItemPower::setItem(), and CNormalItemPower::simplify().
Referenced by CNormalSum::simplify(), and test_simplify::test_simplify_1().
 {
   bool result = true;
   // don't work on the items in the set directly
   // make a copy, otherwise the set will be messed up
   std::set<CNormalItemPower*, compareItemPowers> itemPowersCopy(this->mItemPowers);
   std::set<CNormalItemPower*, compareItemPowers>::iterator it = itemPowersCopy.begin(), endit = itemPowersCopy.end();
   CNormalItemPower* pTmpItemPower = NULL;
   this->mItemPowers.clear();
   while (it != endit && result == true)
     {
       pTmpItemPower = *it;
       result = pTmpItemPower->simplify();
       if (result)
         {
           this->multiply(*pTmpItemPower);
         }
       delete pTmpItemPower;
       ++it;
     }
   // we should combine all general power items of type power into
   // one large general power item which is again simplified
   // this we only do if the CNormalItemPower parent has an exponent of 1
   it = this->mItemPowers.begin();
   endit = this->mItemPowers.end();
   std::vector<CNormalItemPower*> tmpV;
   // create a unit CNormalItemPower with one unit CNormalGeneralPower
   // and an exponent of 1
   CNormalGeneralPower* pGeneralPower = NULL; //CNormalGeneralPower::createUnitGeneralPower();
   while (it != endit)
     {
       if ((*it)->getExp() == 1.0 && (*it)->getItemType() == CNormalItemPower::POWER &&
           dynamic_cast<CNormalGeneralPower*>(&(*it)->getItem())->getType() == CNormalGeneralPower::POWER
           &&
           dynamic_cast<CNormalGeneralPower*>(&(*it)->getItem())->getRight().checkIsOne()
          )
         {
           if (pGeneralPower)
             {
               pGeneralPower->multiply(*static_cast<CNormalGeneralPower*>(&(*it)->getItem()));
             }
           else
             {
               pGeneralPower = static_cast<CNormalGeneralPower*>(&(*it)->getItem());
               pGeneralPower = new CNormalGeneralPower(*pGeneralPower);
             }
           delete *it;
         }
       else
         {
           if ((*it)->getItemType() == CNormalItemPower::POWER &&
               dynamic_cast<CNormalGeneralPower*>(&(*it)->getItem())->getType() == CNormalGeneralPower::POWER &&
               dynamic_cast<CNormalGeneralPower*>(&(*it)->getItem())->getLeft().checkIsOne()
              )
             {
               delete *it;
             }
           else
             {
               tmpV.push_back(*it);
             }
         }
       ++ it;
     }
   if (pGeneralPower && !pGeneralPower->checkIsOne())
     {
       CNormalItemPower* pTmpItemPower = new CNormalItemPower();
       pTmpItemPower->setExp(1.0);
       pTmpItemPower->setItem(*pGeneralPower);
       tmpV.push_back(pTmpItemPower);
     }
   delete pGeneralPower;
   // clear the current set of items and add all the item in tmpV
   this->mItemPowers.clear();
   std::vector<CNormalItemPower*>::iterator vIt = tmpV.begin();
   std::vector<CNormalItemPower*>::iterator vEndIt = tmpV.end();
   while (vIt != vEndIt)
     {
       this->multiply(**vIt);
       delete *vIt;
       ++vIt;
     }
   return result;
 }
std::string CNormalProduct::toString () const virtual
Implements CNormalBase.
Definition at line 474 of file CNormalProduct.cpp.
References mFactor, and mItemPowers.
Referenced by operator<<().
 {
   std::ostringstream os;
   bool firstFactor = true;
   if ((fabs(this->mFactor - 1.0) >= 1.0E-100) || (this->mItemPowers.size() == 0))
     {
       if (this->mFactor < 0.0)
         os << "(" << this->mFactor << ")";
       else
         {
           os.precision(18);
           os << this->mFactor;
         }
       firstFactor = false;
     }
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator it;
   std::set <CNormalItemPower*, compareItemPowers >::const_iterator itEnd = this->mItemPowers.end();
   for (it = this->mItemPowers.begin(); it != itEnd; ++it)
     {
       if (firstFactor == false)
         os << " * ";
       os << **it;
       firstFactor = false;
     }
   return os.str();
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CNormalProduct & d) friend
Definition at line 468 of file CNormalProduct.cpp.
 {
   os << d.toString();
   return os;
 }
Member Data Documentation
C_FLOAT64 CNormalProduct::mFactor private
Enumeration of members
Definition at line 49 of file CNormalProduct.h.
Referenced by getFactor(), multiply(), operator<(), operator=(), operator==(), setFactor(), and toString().
std::set<CNormalItemPower*, compareItemPowers > CNormalProduct::mItemPowers private
Definition at line 50 of file CNormalProduct.h.
Referenced by checkSamePowerList(), CNormalProduct(), getDenominator(), getItemPowers(), multiply(), operator<(), operator=(), remove(), setDenominatorsOne(), setFactor(), setItemPowers(), simplify(), toString(), and ~CNormalProduct().
The documentation for this class was generated from the following files:
CNormalProduct.h
CNormalProduct.cpp