COPASI API: CTransposeView< Matrix > Class Template Reference
CTransposeView< Matrix > Class Template Reference
#include <CMatrix.h>
Public Types
typedef Matrix::elementType elementType
Public Member Functions
CTransposeView (const Matrix &A)
size_t numCols () const
size_t numRows () const
elementType operator() (const size_t &row, const size_t &col) const
~CTransposeView ()
Private Attributes
const Matrix & mA
Friends
std::ostream & operator<< (std::ostream &os, const CTransposeView< Matrix > &A)
Detailed Description
template<class Matrix>
class CTransposeView< Matrix >
Definition at line 35 of file CMatrix.h.
Member Typedef Documentation
template<class Matrix> typedef Matrix::elementType CTransposeView< Matrix >::elementType
Definition at line 753 of file CMatrix.h.
Constructor & Destructor Documentation
template<class Matrix> CTransposeView< Matrix >::CTransposeView (const Matrix & A) inline
Definition at line 759 of file CMatrix.h.
 : mA(A) {}
template<class Matrix> CTransposeView< Matrix >::~CTransposeView () inline
Definition at line 761 of file CMatrix.h.
 {}
Member Function Documentation
template<class Matrix> size_t CTransposeView< Matrix >::numCols () const inline
The number of columns of the matrix
Returns
size_t cols
Definition at line 773 of file CMatrix.h.
References CTransposeView< Matrix >::mA.
Referenced by operator<<().
 {return mA.numRows();}
template<class Matrix> size_t CTransposeView< Matrix >::numRows () const inline
The number of rows of the matrix.
Returns
size_t rows
Definition at line 767 of file CMatrix.h.
References CTransposeView< Matrix >::mA.
Referenced by CEFMAlgorithm::initialize(), and operator<<().
 {return mA.numCols();}
template<class Matrix> elementType CTransposeView< Matrix >::operator() (const size_t & row, const size_t & col) const inline
Retrieve a matrix element using the indexing style of the matrix.
Parameters
const size_t & row
const size_t & col
Returns
elementType element
Definition at line 781 of file CMatrix.h.
References CTransposeView< Matrix >::mA.
   {return mA(col, row);}
Friends And Related Function Documentation
template<class Matrix> std::ostream& operator<< (std::ostream & os, const CTransposeView< Matrix > & A) friend
Output stream operator
Parameters
ostream & os
const CTransposeView< Matrix > & A
Returns
ostream & os
Definition at line 904 of file CMatrix.h.
 {
   size_t i, imax = A.numRows();
   size_t j, jmax = A.numCols();
   os << "Matrix(" << imax << "x" << jmax << ")" << std::endl;
   for (i = 0; i < imax; i++)
     {
       for (j = 0; j < jmax; j++)
         os << "\t" << A(i, j);
       os << std::endl;
     }
   return os;
 }
Member Data Documentation
template<class Matrix> const Matrix& CTransposeView< Matrix >::mA private
Definition at line 756 of file CMatrix.h.
Referenced by CTransposeView< Matrix >::numCols(), CTransposeView< Matrix >::numRows(), and CTransposeView< Matrix >::operator()().
The documentation for this class was generated from the following file:
CMatrix.h