COPASI API: CMIRIAMResources Class Reference
CMIRIAMResources Class Reference
#include <CMIRIAMResource.h>
Public Member Functions
void addMIRIAMResource (CMIRIAMResource *pMIRIAMResource)
bool autoUpdateMIRIAMResources (CProcessReport *pProcessReport)
CMIRIAMResources (const std::string &name="MIRIAM Resources", const CCopasiContainer *pParent=NULL)
CMIRIAMResources (const CMIRIAMResources &src, const CCopasiContainer *pParent=NULL)
CMIRIAMResources (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
const unsigned C_INT32 & getMIRIAMLastUpdateDate () const
const CMIRIAMResource & getMIRIAMResource (const size_t index) const
size_t getMIRIAMResourceIndex (const std::string &URI) const
const CMIRIAMResources & getMIRIAMResources () const
const unsigned C_INT32 & getMIRIAMUpdateFrequency () const
size_t getResourceIndexFromDisplayName (const std::string &displayName) const
const CCopasiParameterGroup & getResourceList () const
void initializeParameter ()
void setMIRIAMUpdateFrequencyInDays (const size_t &days)
bool updateMIRIAMResources (CProcessReport *pProcessReport)
bool updateMIRIAMResourcesFromFile (CProcessReport *pProcessReport, const std::string &filename)
virtual ~CMIRIAMResources ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void createDisplayNameMap ()
void createURIMap ()
unsigned C_INT32 getActDateInSeconds ()
void setMIRIAMLastUpdateDate ()
Private Attributes
std::map< std::string, size_t > mDisplayName2Resource
unsigned C_INT32 * mpLastUpdateDate
CCopasiParameterGroup * mpMIRIAMResources
unsigned C_INT32 * mpUpdateFrequency
std::map< std::string, size_t > mURI2Resource
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 173 of file CMIRIAMResource.h.
Constructor & Destructor Documentation
CMIRIAMResources::CMIRIAMResources (const std::string & name = "MIRIAM Resources", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: MIRIAM Resources)
const CCopasiContainer * pParent (default: NULL)
Definition at line 29 of file CMIRIAMResource.cpp.
References initializeParameter().
                                                                      :
   CCopasiParameterGroup(name, pParent),
   mpLastUpdateDate(NULL),
   mpUpdateFrequency(NULL),
   mpMIRIAMResources(NULL)
 {initializeParameter();}
CMIRIAMResources::CMIRIAMResources (const CMIRIAMResources & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CMIRIAMResources & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 37 of file CMIRIAMResource.cpp.
References initializeParameter().
                                                                     :
   CCopasiParameterGroup(src, pParent),
   mpLastUpdateDate(NULL),
   mpUpdateFrequency(NULL),
   mpMIRIAMResources(NULL)
 {initializeParameter();}
CMIRIAMResources::CMIRIAMResources (const CCopasiParameterGroup & group, const CCopasiContainer * pParent = NULL)
Specific constructor
Parameters
const CCopasiParameterGroup & group
const CCopasiContainer * pParent (default: NULL)
Definition at line 45 of file CMIRIAMResource.cpp.
References initializeParameter().
                                                                     :
   CCopasiParameterGroup(group, pParent),
   mpLastUpdateDate(NULL),
   mpUpdateFrequency(NULL),
   mpMIRIAMResources(NULL)
 {initializeParameter();}
CMIRIAMResources::~CMIRIAMResources () virtual
Destructor
Definition at line 466 of file CMIRIAMResource.cpp.
 {}
Member Function Documentation
void CMIRIAMResources::addMIRIAMResource (CMIRIAMResource * pMIRIAMResource)
Add a MIRIAM Resource to the list of MIRIAM Resources
Parameters
CMIRIAMResource * pMIRIAMResource
Definition at line 67 of file CMIRIAMResource.cpp.
References CCopasiParameterGroup::addParameter(), and mpMIRIAMResources.
 {
   mpMIRIAMResources->addParameter(mimriamResource);
 }
bool CMIRIAMResources::autoUpdateMIRIAMResources (CProcessReport * pProcessReport)
Automatically update the resources when the last update is older than the current date minus the update interval.
Parameters
CProcessReport * pProcessReport
Returns
bool success
Definition at line 323 of file CMIRIAMResource.cpp.
References getActDateInSeconds(), mpLastUpdateDate, mpUpdateFrequency, and updateMIRIAMResources().
 {
   if ((*mpLastUpdateDate + *mpUpdateFrequency) <= getActDateInSeconds())
     {return updateMIRIAMResources(pProcessReport);}
   return false;
 }
void CMIRIAMResources::createDisplayNameMap () private
Initialize the display name to resource index map
Definition at line 344 of file CMIRIAMResource.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), CMIRIAMResource::getMIRIAMDisplayName(), getMIRIAMResource(), mDisplayName2Resource, and mpMIRIAMResources.
Referenced by initializeParameter(), updateMIRIAMResources(), and updateMIRIAMResourcesFromFile().
 {
   mDisplayName2Resource.clear();
   size_t Index = 0;
   CCopasiParameterGroup::index_iterator it = mpMIRIAMResources->beginIndex();
   CCopasiParameterGroup::index_iterator end = mpMIRIAMResources->endIndex();
   for (; it != end; ++it)
     {
       mDisplayName2Resource[getMIRIAMResource(Index).getMIRIAMDisplayName()] = Index;
       Index++;
     }
 }
void CMIRIAMResources::createURIMap () private
Initialize the URI to resource index map
Definition at line 360 of file CMIRIAMResource.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), CMIRIAMResource::getIdentifiersOrgURL(), CMIRIAMResource::getMIRIAMDeprecated(), CMIRIAMResource::getMIRIAMURI(), mpMIRIAMResources, and mURI2Resource.
Referenced by initializeParameter(), updateMIRIAMResources(), and updateMIRIAMResourcesFromFile().
 {
   mURI2Resource.clear();
   size_t Index = 0;
   CMIRIAMResource * pResource = NULL;
   CCopasiParameterGroup::index_iterator it = mpMIRIAMResources->beginIndex();
   CCopasiParameterGroup::index_iterator end = mpMIRIAMResources->endIndex();
   for (; it != end; ++it)
     {
       pResource = static_cast< CMIRIAMResource * >(*it);
       mURI2Resource[pResource->getMIRIAMURI() + ":"] = Index;
       mURI2Resource[pResource->getIdentifiersOrgURL() + "/"] = Index;
       const CCopasiParameterGroup * pDeprecated = &pResource->getMIRIAMDeprecated();
       CCopasiParameterGroup::index_iterator itDeprecated = pDeprecated->beginIndex();
       CCopasiParameterGroup::index_iterator endDeprecated = pDeprecated->endIndex();
       for (; itDeprecated != endDeprecated; ++itDeprecated)
         {
           std::string Deprecated = *(*itDeprecated)->getValue().pSTRING;
           //Deprecated URL style URIs do not use the ':' separator.
           if (Deprecated[Deprecated.length() - 1] != '/')
             {
               Deprecated += ":";
             }
           mURI2Resource[Deprecated] = Index;
         }
       Index++;
     }
 }
bool CMIRIAMResources::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 331 of file CMIRIAMResource.cpp.
References CCopasiParameterGroup::beginIndex(), CCopasiParameterGroup::endIndex(), and mpMIRIAMResources.
Referenced by initializeParameter(), updateMIRIAMResources(), and updateMIRIAMResourcesFromFile().
 {
   bool success = true;
   CCopasiParameterGroup::index_iterator it = mpMIRIAMResources->beginIndex();
   CCopasiParameterGroup::index_iterator end = mpMIRIAMResources->endIndex();
   for (; it != end; ++it)
     *it = elevate<CMIRIAMResource, CCopasiParameterGroup>(*it);
   return success;
 }
unsigned C_INT32 CMIRIAMResources::getActDateInSeconds () private
Retrieve the current date ins seconds
Definition at line 320 of file CMIRIAMResource.cpp.
References C_INT32.
Referenced by autoUpdateMIRIAMResources(), initializeParameter(), and setMIRIAMLastUpdateDate().
 {return (unsigned C_INT32) time(NULL);}
const unsigned C_INT32 & CMIRIAMResources::getMIRIAMLastUpdateDate () const
Retrieve the day the resources where last updated
Returns
const unsigned C_INT32 & lastUpdateDay
Definition at line 78 of file CMIRIAMResource.cpp.
References mpLastUpdateDate.
 {return * mpLastUpdateDate;}
const CMIRIAMResource & CMIRIAMResources::getMIRIAMResource (const size_t index) const
Retrieve the indexed resource
Parameters
const size_t index
Returns
const CMIRIAMResource & resource
Definition at line 397 of file CMIRIAMResource.cpp.
References CCopasiParameterGroup::getGroup(), CCopasiRootContainer::getUnknownMiriamResource(), mpMIRIAMResources, and CCopasiParameterGroup::size().
Referenced by createDisplayNameMap(), CMIRIAMResourceObject::extractId(), CMIRIAMResourceObject::getDisplayName(), CMIRIAMResourceObject::getIdentifiersOrgURL(), CMIRIAMResourceObject::getURI(), and CQMiriamWidget::updateResourcesList().
 {
   if (index >= mpMIRIAMResources->size())
     return CCopasiRootContainer::getUnknownMiriamResource();
   return * static_cast< CMIRIAMResource * >(mpMIRIAMResources->getGroup(index));
 }
size_t CMIRIAMResources::getMIRIAMResourceIndex (const std::string & URI) const
Retrieve the index of the resource with the given URI
Parameters
const std::string & URI
Returns
size_t index
Definition at line 405 of file CMIRIAMResource.cpp.
References C_INVALID_INDEX, and mURI2Resource.
Referenced by CMIRIAMResourceObject::getResource(), and CMIRIAMResourceObject::isValid().
 {
   size_t index = C_INVALID_INDEX;
   std::map< std::string , size_t >::const_iterator it = mURI2Resource.lower_bound(URI);
   std::map< std::string , size_t >::const_iterator end = mURI2Resource.upper_bound(URI);
   if (it == mURI2Resource.begin())
     return index;
   it--;
   for (; it != end; ++it)
     {
       // Check whether the URI base of the candidate matches.
       if (URI.compare(0, it->first.length(), it->first) == 0)
         {
           index =  it->second;
           break;
         }
     }
   return index;
 }
const CMIRIAMResources & CMIRIAMResources::getMIRIAMResources () const
Retrieve the list of MIRIAM Resources
Returns
CMIRIAMResources & MIRIAMResources
Definition at line 72 of file CMIRIAMResource.cpp.
 {return * this;}
const unsigned C_INT32 & CMIRIAMResources::getMIRIAMUpdateFrequency () const
Retrieve the of interval between updates
Returns
const unsigned C_INT32 & updateFrequency
Definition at line 81 of file CMIRIAMResource.cpp.
References mpUpdateFrequency.
 {return * mpUpdateFrequency;}
size_t CMIRIAMResources::getResourceIndexFromDisplayName (const std::string & displayName) const
Retrieve the index of the resource with the given display name
Parameters
const std::string & displayName
Returns
size_t index
Definition at line 430 of file CMIRIAMResource.cpp.
References C_INVALID_INDEX, and mDisplayName2Resource.
Referenced by CMIRIAMResourceObject::setDisplayName().
 {
   // Check if the display name is a know resource
   std::map< std::string, size_t>::const_iterator it =
     mDisplayName2Resource.find(displayName.c_str());
   // If we did not find the resource we set it to unknown
   if (it == mDisplayName2Resource.end())
     {
       // unknown is indicated by an invalid index.
       return C_INVALID_INDEX;
     }
   return it->second;
 }
const CCopasiParameterGroup & CMIRIAMResources::getResourceList () const
Retrieve the list of MIRIAM resource as a CCopasiParameterGroup
Returns
const CCopasiParameterGroup & resourceList
Definition at line 75 of file CMIRIAMResource.cpp.
References mpMIRIAMResources.
Referenced by CConfigurationFile::load(), and CQMiriamWidget::updateResourcesList().
 {return * mpMIRIAMResources;}
void CMIRIAMResources::initializeParameter ()
Allocates all group parameters and assures that they are properly initialized.
Definition at line 53 of file CMIRIAMResource.cpp.
References CCopasiParameterGroup::assertGroup(), CCopasiParameterGroup::assertParameter(), C_INT32, createDisplayNameMap(), createURIMap(), elevateChildren(), getActDateInSeconds(), CCopasiParameter::getValue(), mpLastUpdateDate, mpMIRIAMResources, mpUpdateFrequency, CCopasiParameter::Value::pUINT, and CCopasiParameter::UINT.
Referenced by CMIRIAMResources(), and CConfigurationFile::load().
 {
   mpLastUpdateDate = assertParameter("LastUpdateDate", CCopasiParameter::UINT,
                                      (unsigned C_INT32) getActDateInSeconds())->getValue().pUINT;
   mpUpdateFrequency = assertParameter("Frequency", CCopasiParameter::UINT,
                                       (unsigned C_INT32) 604800)->getValue().pUINT;
   mpMIRIAMResources = assertGroup("Resources");
   elevateChildren();
   createDisplayNameMap();
   createURIMap();
 }
void CMIRIAMResources::setMIRIAMLastUpdateDate () private
Set the last update date to the current time
Definition at line 314 of file CMIRIAMResource.cpp.
References getActDateInSeconds(), and mpLastUpdateDate.
Referenced by updateMIRIAMResources(), and updateMIRIAMResourcesFromFile().
 {*mpLastUpdateDate = getActDateInSeconds();}
void CMIRIAMResources::setMIRIAMUpdateFrequencyInDays (const size_t & days)
Set the days between updates
Parameters
const size_t & days
Definition at line 317 of file CMIRIAMResource.cpp.
References C_INT32, and mpUpdateFrequency.
 {*mpUpdateFrequency = (unsigned C_INT32)(days * 24 * 60 * 60);}
bool CMIRIAMResources::updateMIRIAMResources (CProcessReport * pProcessReport)
Update the MIRIAM resources
Parameters
CProcessReport * pProcessReport
Returns
bool success
Definition at line 206 of file CMIRIAMResource.cpp.
References ArrayOf_USCORExsd_USCOREstring::__ptr, ArrayOf_USCORExsd_USCOREstring::__size, ns2__getDataTypeURIsResponse::_getDataTypeURIsReturn, CMIRIAMResource::addDeprecatedURL(), CProcessReport::addItem(), CCopasiParameterGroup::addParameter(), C_INT32, CCopasiParameterGroup::CCopasiParameterGroup(), createDisplayNameMap(), createURIMap(), elevateChildren(), CCopasiMessage::ERROR, CProcessReport::finishItem(), MiriamWebServicesSoapBindingProxy::getDataTypePattern(), MiriamWebServicesSoapBindingProxy::getDataTypesName(), ns2__getDataTypesNameResponse::getDataTypesNameReturn, MiriamWebServicesSoapBindingProxy::getDataTypeURI(), MiriamWebServicesSoapBindingProxy::getDataTypeURIs(), MCAnnotation, mpMIRIAMResources, pdelete, CProcessReport::progressItem(), CMIRIAMResource::setMIRIAMCitation(), CMIRIAMResource::setMIRIAMDisplayName(), setMIRIAMLastUpdateDate(), CMIRIAMResource::setMIRIAMPattern(), CMIRIAMResource::setMIRIAMURI(), CProcessReport::setName(), MiriamWebServicesSoapBindingProxy::soap_fault_detail(), MiriamWebServicesSoapBindingProxy::soap_fault_string(), and SOAP_OK.
Referenced by autoUpdateMIRIAMResources().
 {
   if (pProcessReport)
     pProcessReport->setName("MIRIAM Resources Update...");
   bool success = true;
   MiriamWebServicesSoapBindingProxy * pProxy = new MiriamWebServicesSoapBindingProxy();
   CCopasiParameterGroup * pTmpCpyCMIRIAMResources = new CCopasiParameterGroup("Resources");
   CMIRIAMResource * pMIRIAMResource = NULL;
   std::string Name, URI, Deprecated, Pattern, IsDeprecated;
   int itNames = 0, itURIs = 0, sizeNames = 0, sizeURIs = 0;
   unsigned C_INT32 processStep = 0, processSteps;
   size_t hUpdateStep;
   struct ns2__getDataTypesNameResponse DataTypesName;
   if (pProxy->getDataTypesName(DataTypesName) == SOAP_OK)
     {
       sizeNames = DataTypesName.getDataTypesNameReturn->__size;
       processSteps = sizeNames + 2;
       hUpdateStep = pProcessReport->addItem("Update Process", processStep, &processSteps);
       if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
         return false;
       for (itNames = 0; itNames < sizeNames; itNames++)
         {
           struct ns2__getDataTypeURIsResponse DataTypeURIs;
           if (DataTypesName.getDataTypesNameReturn->__ptr[itNames] != "")
             Name = DataTypesName.getDataTypesNameReturn->__ptr[itNames];
           pMIRIAMResource = new CMIRIAMResource(Name, NULL);
           if ((pProxy->getDataTypeURI(Name, URI) == SOAP_OK)
               && (pProxy->getDataTypeURIs(Name, DataTypeURIs) == SOAP_OK)
               && (pProxy->getDataTypePattern(Name, Pattern) == SOAP_OK))
             {
               sizeURIs = DataTypeURIs._getDataTypeURIsReturn->__size;
               if (sizeURIs != 0)
                 {
                   for (itURIs = 0; itURIs < sizeURIs; itURIs++)
                     {
                       Deprecated = DataTypeURIs._getDataTypeURIsReturn->__ptr[itURIs];
                       if (Deprecated != URI)
                         pMIRIAMResource->addDeprecatedURL(Deprecated);
                     }
                 }
               pMIRIAMResource->setMIRIAMDisplayName(Name);
               pMIRIAMResource->setMIRIAMURI(URI);
               pMIRIAMResource->setMIRIAMPattern(Pattern);
               pMIRIAMResource->setMIRIAMCitation(URI == "urn:miriam:arxiv" ||
                                                  URI == "urn:miriam:doi" ||
                                                  URI == "urn:miriam:pubmed" ||
                                                  URI == "urn:miriam:isbn");
               pTmpCpyCMIRIAMResources->addParameter(pMIRIAMResource);
             }
           else
             success = false;
           processStep++;
           if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
             return false;
         }
       processStep++;
       if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
         return false;
     }
   else
     success = false;
   if (success)
     {
       // TODO add a resource for local objects, i.e., within the current model.
       setMIRIAMLastUpdateDate();
       *mpMIRIAMResources = *pTmpCpyCMIRIAMResources;
       elevateChildren();
       createDisplayNameMap();
       createURIMap();
     }
   else
     CCopasiMessage(CCopasiMessage::ERROR,
                    MCAnnotation + 3,
                    pProxy->soap_fault_string(),
                    pProxy->soap_fault_detail());
   pdelete(pTmpCpyCMIRIAMResources);
   processStep++;
   if (pProcessReport && !pProcessReport->progressItem(hUpdateStep)) return false;
   if (pProcessReport) pProcessReport->finishItem(hUpdateStep);
   pdelete(pProxy);
   return success;
 }
bool CMIRIAMResources::updateMIRIAMResourcesFromFile (CProcessReport * pProcessReport, const std::string & filename)
Update the MIRIAM resources using a local filename
Parameters
CProcessReport * pProcessReport
Returns
bool success
Definition at line 84 of file CMIRIAMResource.cpp.
References CMIRIAMResource::addDeprecatedURL(), CProcessReport::addItem(), CCopasiParameterGroup::addParameter(), C_INT32, CCopasiParameterGroup::CCopasiParameterGroup(), createDisplayNameMap(), createURIMap(), elevateChildren(), mpMIRIAMResources, pdelete, CProcessReport::progressItem(), CMIRIAMResource::setMIRIAMCitation(), CMIRIAMResource::setMIRIAMDisplayName(), setMIRIAMLastUpdateDate(), CMIRIAMResource::setMIRIAMPattern(), and CMIRIAMResource::setMIRIAMURI().
Referenced by DataModelGUI::miriamDownloadFinished().
 {
   bool success = true;
   CCopasiParameterGroup * pTmpCpyCMIRIAMResources = new CCopasiParameterGroup("Resources");
   CMIRIAMResource * pMIRIAMResource = NULL;
   std::string Name, URI, Deprecated, Pattern, IsDeprecated;
   int itNames = 0, itURIs = 0, sizeNames = 0, sizeURIs = 0;
   unsigned C_INT32 processStep = 0, processSteps = 1;
   size_t hUpdateStep;
   if (pProcessReport)
     hUpdateStep = pProcessReport->addItem("Parsing MIRIAM XML", processStep, &processSteps);
   // parse file into memory
   XMLInputStream stream(filename.c_str());
   if (stream.isError()) return false;
   XMLNode root(stream);
   ++processStep;
   if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
     return false;
   sizeNames = root.getNumChildren();
   processSteps = sizeNames + 2;
   if (pProcessReport)
     hUpdateStep = pProcessReport->addItem("Add Items", processStep, &processSteps);
   if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
     return false;
   // read all datatype elements
   for (itNames = 0; itNames < sizeNames; itNames++)
     {
       XMLNode dataType = root.getChild(itNames);
       // only parse dataType elements
       if (dataType.getName() != "datatype") continue;
       // extract name
       Name = dataType.getChild("name").getChild(0).getCharacters();
       pMIRIAMResource = new CMIRIAMResource(Name, NULL);
       XMLNode uris = dataType.getChild("uris");
       sizeURIs = uris.getNumChildren();
       // extract uri & deprecated uris
       URI.clear();
       if (sizeURIs != 0)
         {
           for (itURIs = 0; itURIs < sizeURIs; itURIs++)
             {
               XMLNode uri = uris.getChild(itURIs);
               if (URI.empty())
                 URI = uri.getChild(0).getCharacters();
               Deprecated = uri.getAttrValue("deprecated");
               if (Deprecated == "true")
                 pMIRIAMResource->addDeprecatedURL(uri.getChild(0).getCharacters());
             }
         }
       // set name
       pMIRIAMResource->setMIRIAMDisplayName(Name);
       if (URI.empty() || Name.empty())
         {
           // ignore invalid item
           delete pMIRIAMResource;
           continue;
         }
       pMIRIAMResource->setMIRIAMURI(URI);
       pMIRIAMResource->setMIRIAMPattern(dataType.getAttrValue("pattern"));
       pMIRIAMResource->setMIRIAMCitation(URI == "urn:miriam:arxiv" ||
                                          URI == "urn:miriam:doi" ||
                                          URI == "urn:miriam:pubmed" ||
                                          URI == "urn:miriam:isbn");
       pTmpCpyCMIRIAMResources->addParameter(pMIRIAMResource);
       processStep++;
       if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
         return false;
     }
   processStep++;
   if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
     return false;
   if (success)
     {
       // TODO add a resource for local objects, i.e., within the current model.
       setMIRIAMLastUpdateDate();
       *mpMIRIAMResources = *pTmpCpyCMIRIAMResources;
       elevateChildren();
       createDisplayNameMap();
       createURIMap();
     }
   pdelete(pTmpCpyCMIRIAMResources);
   processStep++;
   if (pProcessReport && !pProcessReport->progressItem(hUpdateStep))
     return false;
   return success;
 }
Member Data Documentation
std::map< std::string, size_t > CMIRIAMResources::mDisplayName2Resource private
A map from display name to resource index
Definition at line 340 of file CMIRIAMResource.h.
Referenced by createDisplayNameMap(), and getResourceIndexFromDisplayName().
unsigned C_INT32* CMIRIAMResources::mpLastUpdateDate private
A pointer to the last update date.
Definition at line 325 of file CMIRIAMResource.h.
Referenced by autoUpdateMIRIAMResources(), getMIRIAMLastUpdateDate(), initializeParameter(), and setMIRIAMLastUpdateDate().
CCopasiParameterGroup* CMIRIAMResources::mpMIRIAMResources private
A pointer to the group of MIRIAM resources
Definition at line 335 of file CMIRIAMResource.h.
Referenced by addMIRIAMResource(), createDisplayNameMap(), createURIMap(), elevateChildren(), getMIRIAMResource(), getResourceList(), initializeParameter(), updateMIRIAMResources(), and updateMIRIAMResourcesFromFile().
unsigned C_INT32* CMIRIAMResources::mpUpdateFrequency private
A pointer to the update interval.
Definition at line 330 of file CMIRIAMResource.h.
Referenced by autoUpdateMIRIAMResources(), getMIRIAMUpdateFrequency(), initializeParameter(), and setMIRIAMUpdateFrequencyInDays().
std::map< std::string, size_t > CMIRIAMResources::mURI2Resource private
A map from URI to resource index
Definition at line 345 of file CMIRIAMResource.h.
Referenced by createURIMap(), and getMIRIAMResourceIndex().
The documentation for this class was generated from the following files:
CMIRIAMResource.h
CMIRIAMResource.cpp