COPASI API: CLPoint Class Reference
CLPoint Class Reference
#include <CLBase.h>
Public Member Functions
CLPoint ()
CLPoint (const C_FLOAT64 &x, const C_FLOAT64 &y, const C_FLOAT64 &z=0.0)
CLPoint (const Point &p)
C_FLOAT64 dot (const CLPoint &rhs) const
Point getSBMLPoint () const
const C_FLOAT64 & getX () const
C_FLOAT64 & getX ()
const C_FLOAT64 & getY () const
C_FLOAT64 & getY ()
const C_FLOAT64 & getZ () const
C_FLOAT64 & getZ ()
bool isEmpty () const
virtual void moveBy (const CLPoint &p)
CLPoint operator* (const double &rhs) const
CLPoint operator+ (const CLPoint &rhs) const
CLPoint operator- (const CLPoint &rhs) const
bool operator< (const CLPoint &rhs) const
bool operator== (const CLPoint &rhs) const
void scale (const double &scaleFactor)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
void setZ (const C_FLOAT64 &z)
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
C_FLOAT64 mX
C_FLOAT64 mY
C_FLOAT64 mZ
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLPoint &p)
Detailed Description
This class describes a Point in a layout It is 2-dimensional at the moment
Definition at line 54 of file CLBase.h.
Constructor & Destructor Documentation
CLPoint::CLPoint () inline
Definition at line 63 of file CLBase.h.
Referenced by operator*(), operator+(), and operator-().
            :
     mX(0.0)
     , mY(0.0)
     , mZ(0.0)
   {};
CLPoint::CLPoint (const C_FLOAT64 & x, const C_FLOAT64 & y, const C_FLOAT64 & z = 0.0) inline
Definition at line 69 of file CLBase.h.
           :
     mX(x)
     , mY(y)
     , mZ(z)
   {};
CLPoint::CLPoint (const Point & p)
constructor from libsbml object
Definition at line 23 of file CLBase.cpp.
                                :
   mX(p.getXOffset())
   , mY(p.getYOffset())
   , mZ(p.getZOffset())
 {}
Member Function Documentation
C_FLOAT64 CLPoint::dot (const CLPoint & rhs) const inline
Definition at line 135 of file CLBase.h.
References mX, mY, and mZ.
Referenced by CCopasiSpringLayout::finalizeState().
   {
     return this->mX * rhs.mX + this->mY * rhs.mY
            + this->mZ * rhs.mZ
            ;
   };
Point CLPoint::getSBMLPoint () const
convert to sbml point
Definition at line 29 of file CLBase.cpp.
References mX, mY, and mZ.
 {
   Point p(new LayoutPkgNamespaces(), mX, mY, mZ);
   return p;
 }
const C_FLOAT64& CLPoint::getX () const inline
Definition at line 83 of file CLBase.h.
References mX.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), addToPath(), adjustPosition(), CCopasiSpringLayout::borderProjection(), CLLayoutRenderer::calculate_intersection(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateAndAssignBounds(), CQGLNetworkPainter::calculateAngle(), CLayout::calculateBoundingBox(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::checkCurve(), CLLayoutRenderer::convert_to_absolute(), CQLabelGraphicsItem::CQLabelGraphicsItem(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::distance(), CLLayoutRenderer::draw_cap(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_polygon(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), CQGLNetworkPainter::drawArrow(), CQGLNetworkPainter::drawEdge(), fillItemFromCurve(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), CCopasiSpringLayout::finalizeState(), CQGLNetworkPainter::fitToScreen(), CLBoundingBox::getCenter(), CLLayoutRenderer::getCurveBoundingBox(), getLinearGradient(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CQConnectionGraphicsItem::getPath(), getPath(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), getRadialGradient(), CLBoundingBox::getSBMLBoundingBox(), CLGraphicalObject::getX(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::map_arrow_head(), CQGLLayoutPainter::mouseMoveEvent(), CQGLLayoutPainter::mouseReleaseEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), moveToPoint(), randomlyPlaceGlyphInCompartmentGlyph(), CQLayoutMainWindow::saveImage(), CCopasiXML::savePosition(), CLabel::scalePosition(), CArrow::scalePosition(), CQGLNetworkPainter::setGraphSize(), CQGLNetworkPainter::setNodeSize(), CQGLViewport::slotHValueChanged(), CLLineEnding::toSBML(), CQGLViewport::updateScrollbars(), and CQGLNetworkPainter::zoom().
 {return mX;};
C_FLOAT64& CLPoint::getX () inline
Definition at line 87 of file CLBase.h.
References mX.
 {return mX;};
const C_FLOAT64& CLPoint::getY () const inline
Definition at line 84 of file CLBase.h.
References mY.
Referenced by CQGLNetworkPainter::adaptCurveForCircle(), CQGLNetworkPainter::adaptCurveForRectangles(), addToPath(), adjustPosition(), CCopasiSpringLayout::borderProjection(), CLLayoutRenderer::calculate_intersection(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateAndAssignBounds(), CQGLNetworkPainter::calculateAngle(), CLayout::calculateBoundingBox(), CLCurve::calculateBoundingBox(), CQGLNetworkPainter::checkCurve(), CLLayoutRenderer::convert_to_absolute(), CQLabelGraphicsItem::CQLabelGraphicsItem(), CQGLNetworkPainter::createGraph(), CLLayoutRenderer::distance(), CLLayoutRenderer::draw_cap(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_polygon(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), CQGLNetworkPainter::drawArrow(), CQGLNetworkPainter::drawEdge(), fillItemFromCurve(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), CCopasiSpringLayout::finalizeState(), CQGLNetworkPainter::fitToScreen(), CLBoundingBox::getCenter(), CLLayoutRenderer::getCurveBoundingBox(), getLinearGradient(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CQConnectionGraphicsItem::getPath(), getPath(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), getRadialGradient(), CLBoundingBox::getSBMLBoundingBox(), CLGraphicalObject::getY(), CGraphCurve::invertOrderOfPoints(), CLLayoutRenderer::is_curve_segment_visible(), CLLayoutRenderer::isSegmentHit(), CLLayoutRenderer::map_arrow_head(), CQGLLayoutPainter::mouseMoveEvent(), CQGLLayoutPainter::mouseReleaseEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), moveToPoint(), randomlyPlaceGlyphInCompartmentGlyph(), CQLayoutMainWindow::saveImage(), CCopasiXML::savePosition(), CLabel::scalePosition(), CArrow::scalePosition(), CQGLNetworkPainter::setGraphSize(), CQGLNetworkPainter::setNodeSize(), CQGLViewport::slotVValueChanged(), CLLineEnding::toSBML(), CQGLViewport::updateScrollbars(), and CQGLNetworkPainter::zoom().
 {return mY;};
C_FLOAT64& CLPoint::getY () inline
Definition at line 88 of file CLBase.h.
References mY.
 {return mY;};
const C_FLOAT64& CLPoint::getZ () const inline
Definition at line 85 of file CLBase.h.
References mZ.
Referenced by CLLayoutRenderer::calculate_intersection(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateAndAssignBounds(), CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::draw_cap(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_polygon(), CLLayoutRenderer::draw_text(), CLLayoutRenderer::is_curve_segment_visible(), and CLLayoutRenderer::map_arrow_head().
 {return mZ;};
C_FLOAT64& CLPoint::getZ () inline
Definition at line 89 of file CLBase.h.
References mZ.
 {return mZ;};
bool CLPoint::isEmpty () const inline
Definition at line 163 of file CLBase.h.
References mX, mY, and mZ.
Referenced by CLayout::moveBy().
   {
     return mX == 0
            && mY == 0
            && mZ == 0
            ;
   }
virtual void CLPoint::moveBy (const CLPoint & p) inline virtual
Reimplemented from CLBase.
Definition at line 120 of file CLBase.h.
References mX, mY, and mZ.
Referenced by CLCurve::moveBy(), and CLBoundingBox::moveBy().
   {
     mX += p.mX;
     mY += p.mY;
     mZ += p.mZ;
   };
CLPoint CLPoint::operator* (const double & rhs) const inline
Definition at line 127 of file CLBase.h.
References CLPoint(), mX, mY, and mZ.
   {
     return CLPoint(this->mX * rhs,
                    this->mY * rhs
                    , this->mZ * rhs
                   );
   };
CLPoint CLPoint::operator+ (const CLPoint & rhs) const inline
Definition at line 112 of file CLBase.h.
References CLPoint(), mX, mY, and mZ.
   {
     return CLPoint(this->mX + rhs.mX,
                    this->mY + rhs.mY
                    , this->mZ + rhs.mZ
                   );
   };
CLPoint CLPoint::operator- (const CLPoint & rhs) const inline
Definition at line 104 of file CLBase.h.
References CLPoint(), mX, mY, and mZ.
   {
     return CLPoint(this->mX - rhs.mX,
                    this->mY - rhs.mY
                    , this->mZ - rhs.mZ
                   );
   };
bool CLPoint::operator< (const CLPoint & rhs) const inline
Definition at line 143 of file CLBase.h.
References mX, mY, and mZ.
   {
     if (mX == rhs.mX)
       if (mY == rhs.mY)
         {
           return (mZ < rhs.mZ);
         }
       else
         {
           return (mY < rhs.mY);
         }
     else
       return (mX < rhs.mX);
   };
bool CLPoint::operator== (const CLPoint & rhs) const inline
Definition at line 97 of file CLBase.h.
References mX, mY, and mZ.
   {
     bool result = (mX == rhs.mX) && (mY == rhs.mY);
     result &= mZ == rhs.mZ;
     return result;
   };
void CLPoint::scale (const double & scaleFactor) inline
Definition at line 95 of file CLBase.h.
References mX, and mY.
Referenced by CCopasiSpringLayout::finalizeState(), CLLineSegment::scale(), and CLBoundingBox::scale().
 {mX *= scaleFactor; mY *= scaleFactor;}
void CLPoint::setX (const C_FLOAT64 & x) inline
Definition at line 91 of file CLBase.h.
References mX.
Referenced by CQGLNetworkPainter::checkCurve(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), CLLayoutRenderer::is_curve_segment_visible(), CQGLLayoutPainter::mouseMoveEvent(), CQGLLayoutPainter::mouseReleaseEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), CLabel::scalePosition(), CArrow::scalePosition(), CQGLNetworkPainter::setGraphSize(), and CLGraphicalObject::setX().
 {mX = x;};
void CLPoint::setY (const C_FLOAT64 & y) inline
Definition at line 92 of file CLBase.h.
References mY.
Referenced by CQGLNetworkPainter::checkCurve(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), CLLayoutRenderer::is_curve_segment_visible(), CQGLLayoutPainter::mouseMoveEvent(), CQGLLayoutPainter::mouseReleaseEvent(), CLLayoutRenderer::move_curve_object(), CLLayoutRenderer::move_graphical_object(), CLLayoutRenderer::move_reaction_glyph(), CLLayoutRenderer::move_species_glyph(), CLabel::scalePosition(), CArrow::scalePosition(), CQGLNetworkPainter::setGraphSize(), and CLGraphicalObject::setY().
 {mY = y;};
void CLPoint::setZ (const C_FLOAT64 & z) inline
Definition at line 93 of file CLBase.h.
References mZ.
Referenced by CLLayoutRenderer::is_curve_segment_visible().
 {mZ = z;};
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLPoint & p) friend
insert operator
Definition at line 68 of file CLBase.cpp.
 {
   os << "(x=" << p.mX << ", y=" << p.mY << ")";
   return os;
 }
Member Data Documentation
C_FLOAT64 CLPoint::mX protected
Definition at line 58 of file CLBase.h.
Referenced by dot(), getSBMLPoint(), getX(), isEmpty(), moveBy(), operator*(), operator+(), operator-(), operator<(), operator<<(), operator==(), scale(), and setX().
C_FLOAT64 CLPoint::mY protected
Definition at line 58 of file CLBase.h.
Referenced by dot(), getSBMLPoint(), getY(), isEmpty(), moveBy(), operator*(), operator+(), operator-(), operator<(), operator<<(), operator==(), scale(), and setY().
C_FLOAT64 CLPoint::mZ protected
Definition at line 59 of file CLBase.h.
Referenced by dot(), getSBMLPoint(), getZ(), isEmpty(), moveBy(), operator*(), operator+(), operator-(), operator<(), operator==(), and setZ().
The documentation for this class was generated from the following files:
CLBase.h
CLBase.cpp