COPASI API: CQSideCompoundWizardPage::CQListWidgetModelItem Class Reference
CQSideCompoundWizardPage::CQListWidgetModelItem Class Reference
#include <CQAutolayoutWizard.h>
Public Member Functions
CQListWidgetModelItem (const QString &text, const std::string &key)
const std::string & getKey () const
CCopasiObject * getObject () const
Protected Attributes
std::string mKey
Detailed Description
Definition at line 156 of file CQAutolayoutWizard.h.
Constructor & Destructor Documentation
CQSideCompoundWizardPage::CQListWidgetModelItem::CQListWidgetModelItem (const QString & text, const std::string & key)
Definition at line 591 of file CQAutolayoutWizard.cpp.
                                                                                                              :
   QListWidgetItem(text)
   , mKey(key)
 {
 }
Member Function Documentation
const std::string & CQSideCompoundWizardPage::CQListWidgetModelItem::getKey () const
Definition at line 598 of file CQAutolayoutWizard.cpp.
 {
   return this->mKey;
 }
CCopasiObject * CQSideCompoundWizardPage::CQListWidgetModelItem::getObject () const
Definition at line 603 of file CQAutolayoutWizard.cpp.
References CKeyFactory::get(), and CCopasiRootContainer::getKeyFactory().
Referenced by CQSideCompoundWizardPage::getSideCompounds(), CQSideCompoundWizardPage::slotAddButtonClicked(), and CQSideCompoundWizardPage::slotRemoveButtonClicked().
 {
   CCopasiObject* pObject = NULL;
   if (!this->mKey.empty())
     {
       pObject = CCopasiRootContainer::getKeyFactory()->get(this->mKey);
     }
   return pObject;
 }
Member Data Documentation
std::string CQSideCompoundWizardPage::CQListWidgetModelItem::mKey protected
Definition at line 169 of file CQAutolayoutWizard.h.
The documentation for this class was generated from the following files:
CQAutolayoutWizard.h
CQAutolayoutWizard.cpp