COPASI API: CSEDMLExporter.cpp File Reference
CSEDMLExporter.cpp File Reference
#include <sbml/math/FormulaParser.h>
#include <sedml/SedTypes.h>
#include <sbml/SBMLTypes.h>
#include "SEDMLUtils.h"
#include "sbml/CSBMLExporter.h"
#include "CSEDMLExporter.h"
#include "trajectory/CTrajectoryTask.h"
#include "trajectory/CTrajectoryProblem.h"
#include "scan/CScanTask.h"
#include "scan/CScanProblem.h"
#include "utilities/CCopasiException.h"
#include "utilities/CVersion.h"
#include "utilities/CCopasiMessage.h"
#include "utilities/CDirEntry.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "plot/COutputDefinitionVector.h"
#include "plot/CPlotSpecification.h"
#include "report/CReportDefinition.h"
#include "model/CModel.h"
#include "model/CCompartment.h"
#include "model/CModelValue.h"
#include "commandline/CLocaleString.h"
Functions
SedDataGenerator * createDataGenerator (SedDocument *mpSEDMLDocument, const std::string &sbmlId, const std::string &targetXPathString, const std::string &taskId, size_t i, size_t j)
std::string createUniqueModelFileName (const std::string &dir, const std::string &baseName, const std::string &extension=".xml")
Function Documentation
SedDataGenerator* createDataGenerator (SedDocument * mpSEDMLDocument, const std::string & sbmlId, const std::string & targetXPathString, const std::string & taskId, size_t i, size_t j)
Definition at line 387 of file CSEDMLExporter.cpp.
References SEDML_TIME_URN.
Referenced by CSEDMLExporter::createDataGenerators().
 {
   SedDataGenerator *pPDGen = mpSEDMLDocument->createDataGenerator();
   std::ostringstream idStrStream;
   idStrStream << sbmlId;
   idStrStream << "_";
   idStrStream << j + 1;
   pPDGen->setId(idStrStream.str());
   pPDGen->setName(sbmlId);
   SedVariable * pPVar = pPDGen->createVariable();
   std::ostringstream idVarStrStream;
   idVarStrStream << "p";
   idVarStrStream << i + 1;
   idVarStrStream << "_";
   idVarStrStream << pPDGen->getName();
   pPVar->setId(idVarStrStream.str());
   pPVar->setTaskReference(taskId);
   pPVar->setName(pPDGen->getName());
   pPDGen->setMath(SBML_parseFormula(pPVar->getId().c_str()));
   if (targetXPathString == SEDML_TIME_URN)
     {
       pPVar->setSymbol(targetXPathString);
     }
   else
     {
       pPVar->setTarget(targetXPathString);
     }
   return pPDGen;
 }
std::string createUniqueModelFileName (const std::string & dir, const std::string & baseName, const std::string & extension = ".xml")
Definition at line 71 of file CSEDMLExporter.cpp.
References CDirEntry::exist(), and CDirEntry::Separator.
Referenced by CSEDMLExporter::exportModelAndTasks().
 {
   int count = 1;
   std::string current = baseName + extension;
   while (CDirEntry::exist(dir + CDirEntry::Separator + current))
     {
       std::stringstream temp;
       temp << baseName << count << extension;
       current = temp.str();
       ++count;
     }
   return current;
 }