COPASI API: CQBaseDataModel Class Reference
CQBaseDataModel Class Reference abstract
#include <CQBaseDataModel.h>
Signals
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Public Member Functions
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
virtual QVariant data (const QModelIndex &index, int role) const =0
virtual Qt::ItemFlags flags (const QModelIndex &index) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const =0
bool insertRow ()
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRow (int position)
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)=0
Protected Member Functions
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())=0
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())=0
Detailed Description
Definition at line 28 of file CQBaseDataModel.h.
Constructor & Destructor Documentation
CQBaseDataModel::CQBaseDataModel (QObject * parent = 0)
Definition at line 22 of file CQBaseDataModel.cpp.
     : QAbstractTableModel(parent)
 {}
Member Function Documentation
bool CQBaseDataModel::clear () virtual
Reimplemented in CQLayoutsDM, and CQParameterSetsDM.
Definition at line 51 of file CQBaseDataModel.cpp.
References removeRows().
Referenced by CQPlotsWidget::slotBtnClearClicked(), CQReportsWidget::slotBtnClearClicked(), CQEventsWidget::slotBtnClearClicked(), CQReactionsWidget::slotBtnClearClicked(), CQCompartmentsWidget::slotBtnClearClicked(), CQFunctionsWidget::slotBtnClearClicked(), CQGlobalQuantitiesWidget::slotBtnClearClicked(), CQSpeciesWidget::slotBtnClearClicked(), and CQMiriamWidget::slotBtnClearClicked().
 {
   return removeRows(0, rowCount() - 1);
 }
QString CQBaseDataModel::createNewName (const QString name, const int nameCol)
Definition at line 68 of file CQBaseDataModel.cpp.
References C_INT32, and data().
Referenced by CQReportDM::insertRows(), CQPlotDM::insertRows(), CQFunctionDM::insertRows(), CQReactionDM::insertRows(), CQEventDM::insertRows(), CQGlobalQuantityDM::insertRows(), CQCompartmentDM::insertRows(), CQSpecieDM::insertRows(), CQReportDM::setData(), CQPlotDM::setData(), CQReactionDM::setData(), CQFunctionDM::setData(), CQEventDM::setData(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), and CQSpecieDM::setData().
 {
   QString nname = name;
   unsigned C_INT32 j, jmax = rowCount();
   for (unsigned C_INT32 i = 1;; ++i)
     {
       nname = name + "_" + QString::number(i);
       for (j = 0; j < jmax; ++j)
         if (index(j, nameCol).data() == nname) break;
       if (j == jmax) break;
     }
   return nname;
 }
virtual QVariant CQBaseDataModel::data (const QModelIndex & index, int role) const pure virtual
Implemented in CQSpecieDM, CQCompartmentDM, CQGlobalQuantityDM, CQEFMNetReactionDM, CQFluxModeDM, CQEFMSpeciesDM, CQEventDM, CQFunctionDM, CQReactionDM, CQCreatorDM, CQBiologicalDescriptionDM, CQReferenceDM, CQEFMReactionDM, CQPlotDM, CQModifiedDM, CQLayoutsDM, CQReportDM, CQTimeSeriesDM, and CQParameterSetsDM.
Referenced by createNewName().
Qt::ItemFlags CQBaseDataModel::flags (const QModelIndex & index) const virtual
Reimplemented in CQSpecieDM, CQCompartmentDM, CQGlobalQuantityDM, CQEFMNetReactionDM, CQFluxModeDM, CQEventDM, CQEFMSpeciesDM, CQFunctionDM, CQReactionDM, CQEFMReactionDM, CQPlotDM, CQLayoutsDM, CQReportDM, CQTimeSeriesDM, and CQParameterSetsDM.
Definition at line 27 of file CQBaseDataModel.cpp.
References COL_ROW_NUMBER.
 {
   if (!index.isValid())
     return Qt::ItemIsEnabled;
   if (index.column() == COL_ROW_NUMBER)
     return QAbstractItemModel::flags(index);
   else
     return QAbstractItemModel::flags(index) | Qt::ItemIsEditable;
 }
virtual QVariant CQBaseDataModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const pure virtual
Implemented in CQSpecieDM, CQCompartmentDM, CQGlobalQuantityDM, CQEFMNetReactionDM, CQEFMSpeciesDM, CQFluxModeDM, CQEventDM, CQFunctionDM, CQReactionDM, CQCreatorDM, CQBiologicalDescriptionDM, CQReferenceDM, CQEFMReactionDM, CQPlotDM, CQModifiedDM, CQLayoutsDM, CQReportDM, CQTimeSeriesDM, and CQParameterSetsDM.
bool CQBaseDataModel::insertRow ()
Definition at line 38 of file CQBaseDataModel.cpp.
References insertRows().
Referenced by CQModifiedDM::setData(), CQReportDM::setData(), CQBiologicalDescriptionDM::setData(), CQReferenceDM::setData(), CQPlotDM::setData(), CQCreatorDM::setData(), CQFunctionDM::setData(), CQReactionDM::setData(), CQEventDM::setData(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), CQParameterSetsWidget::slotBtnNewClicked(), CQPlotsWidget::slotBtnNewClicked(), CQReportsWidget::slotBtnNewClicked(), CQEventsWidget::slotBtnNewClicked(), CQReactionsWidget::slotBtnNewClicked(), CQCompartmentsWidget::slotBtnNewClicked(), CQFunctionsWidget::slotBtnNewClicked(), CQGlobalQuantitiesWidget::slotBtnNewClicked(), and CQSpeciesWidget::slotBtnNewClicked().
 {
   return insertRows(rowCount() - 1, 1);
 }
virtual bool CQBaseDataModel::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected pure virtual
Implemented in CQSpecieDM, CQCompartmentDM, CQGlobalQuantityDM, CQEFMNetReactionDM, CQFluxModeDM, CQEFMSpeciesDM, CQEFMReactionDM, CQEventDM, CQFunctionDM, CQReactionDM, CQCreatorDM, CQBiologicalDescriptionDM, CQReferenceDM, CQPlotDM, CQTimeSeriesDM, CQLayoutsDM, CQModifiedDM, CQReportDM, and CQParameterSetsDM.
Referenced by insertRow().
bool CQBaseDataModel::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented in CQEFMNetReactionDM, CQFluxModeDM, CQEFMSpeciesDM, CQEFMReactionDM, CQLayoutsDM, CQTimeSeriesDM, and CQParameterSetsDM.
Definition at line 56 of file CQBaseDataModel.cpp.
Referenced by CQSpinBoxDelegate::createEditor(), CQReportDM::data(), CQModifiedDM::data(), CQPlotDM::data(), CQReferenceDM::data(), CQBiologicalDescriptionDM::data(), CQCreatorDM::data(), CQFunctionDM::data(), CQReactionDM::data(), CQEventDM::data(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CQFunctionDM::flags(), CQSpecieDM::flags(), CQSortFilterProxyModel::lessThan(), removeRow(), CQReportDM::removeRows(), CQModifiedDM::removeRows(), CQPlotDM::removeRows(), CQBiologicalDescriptionDM::removeRows(), CQReferenceDM::removeRows(), CQCreatorDM::removeRows(), CQReactionDM::removeRows(), CQFunctionDM::removeRows(), CQEventDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), CQSpecieDM::removeRows(), CQReportDM::setData(), CQModifiedDM::setData(), CQPlotDM::setData(), CQReferenceDM::setData(), CQBiologicalDescriptionDM::setData(), CQCreatorDM::setData(), CQReactionDM::setData(), CQFunctionDM::setData(), CQEventDM::setData(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), CQPlotsWidget::slotDoubleClicked(), CQReactionsWidget::slotDoubleClicked(), CQReportsWidget::slotDoubleClicked(), CQEventsWidget::slotDoubleClicked(), CQFunctionsWidget::slotDoubleClicked(), CQCompartmentsWidget::slotDoubleClicked(), CQGlobalQuantitiesWidget::slotDoubleClicked(), CQSpeciesWidget::slotDoubleClicked(), CQPlotsWidget::updateDeleteBtns(), CQReportsWidget::updateDeleteBtns(), CQReactionsWidget::updateDeleteBtns(), CQEventsWidget::updateDeleteBtns(), CQCompartmentsWidget::updateDeleteBtns(), CQFunctionsWidget::updateDeleteBtns(), CQSpeciesWidget::updateDeleteBtns(), and CQGlobalQuantitiesWidget::updateDeleteBtns().
 {
   //Index has to be from this model and should be valid.
   if ((i.model() != this) ||
       !i.isValid())
     {
       return false;
     }
   return (i.row() == rowCount() - 1);
 }
void CQBaseDataModel::notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key = "") signal
Referenced by CQParameterSetsDM::insertRows(), CQReportDM::insertRows(), CQModifiedDM::insertRows(), CQLayoutsDM::insertRows(), CQReferenceDM::insertRows(), CQBiologicalDescriptionDM::insertRows(), CQPlotDM::insertRows(), CQCreatorDM::insertRows(), CQFunctionDM::insertRows(), CQReactionDM::insertRows(), CQEventDM::insertRows(), CQGlobalQuantityDM::insertRows(), CQCompartmentDM::insertRows(), CQSpecieDM::insertRows(), CQParameterSetsDM::removeRows(), CQReportDM::removeRows(), CQModifiedDM::removeRows(), CQReferenceDM::removeRows(), CQPlotDM::removeRows(), CQBiologicalDescriptionDM::removeRows(), CQCreatorDM::removeRows(), CQReactionDM::removeRows(), CQFunctionDM::removeRows(), CQLayoutsDM::removeRows(), CQEventDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), CQSpecieDM::removeRows(), CQModifiedDM::setData(), CQReportDM::setData(), CQBiologicalDescriptionDM::setData(), CQPlotDM::setData(), CQReferenceDM::setData(), CQCreatorDM::setData(), CQFunctionDM::setData(), CQReactionDM::setData(), CQEventDM::setData(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), and CQReactionDM::setEquation().
bool CQBaseDataModel::removeRow (int position)
Definition at line 43 of file CQBaseDataModel.cpp.
References isDefaultRow(), and removeRows().
Referenced by CQParameterSetsDM::removeRows(), CQModifiedDM::removeRows(), CQReportDM::removeRows(), CQLayoutsDM::removeRows(), CQPlotDM::removeRows(), CQReferenceDM::removeRows(), CQBiologicalDescriptionDM::removeRows(), CQCreatorDM::removeRows(), CQFunctionDM::removeRows(), CQReactionDM::removeRows(), CQEventDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), and CQSpecieDM::removeRows().
 {
   if (0 <= position && position < rowCount() && !isDefaultRow(index(position, 0)))
     return removeRows(position, 1);
   else
     return false;
 }
virtual bool CQBaseDataModel::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected pure virtual
Implemented in CQSpecieDM, CQCompartmentDM, CQGlobalQuantityDM, CQEFMNetReactionDM, CQFluxModeDM, CQEFMSpeciesDM, CQEFMReactionDM, CQEventDM, CQLayoutsDM, CQFunctionDM, CQReactionDM, CQCreatorDM, CQBiologicalDescriptionDM, CQReferenceDM, CQPlotDM, CQTimeSeriesDM, CQModifiedDM, CQReportDM, and CQParameterSetsDM.
Referenced by clear(), and removeRow().
virtual bool CQBaseDataModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) pure virtual
Implemented in CQSpecieDM, CQCompartmentDM, CQEFMNetReactionDM, CQFluxModeDM, CQGlobalQuantityDM, CQEFMSpeciesDM, CQEFMReactionDM, CQEventDM, CQFunctionDM, CQReactionDM, CQCreatorDM, CQBiologicalDescriptionDM, CQReferenceDM, CQPlotDM, CQModifiedDM, CQLayoutsDM, CQReportDM, CQTimeSeriesDM, and CQParameterSetsDM.
The documentation for this class was generated from the following files:
CQBaseDataModel.h
CQBaseDataModel.cpp