COPASI API: CQTaskHeaderWidget Class Reference
CQTaskHeaderWidget Class Reference
#include <CQTaskHeaderWidget.h>
Public Member Functions
CQTaskHeaderWidget (QWidget *parent=0, Qt::WindowFlags f=0)
void saved ()
bool setTaskName (const std::string &name)
virtual ~CQTaskHeaderWidget ()
Protected Slots
void slotExecutable ()
void slotUpdate ()
Protected Attributes
QColor mChangedColor
bool mExecutableChanged
QColor mSavedColor
bool mUpdateChanged
Detailed Description
Definition at line 23 of file CQTaskHeaderWidget.h.
Constructor & Destructor Documentation
CQTaskHeaderWidget::CQTaskHeaderWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 19 of file CQTaskHeaderWidget.cpp.
References mChangedColor, mExecutableChanged, mSavedColor, and mUpdateChanged.
                                                                       :
   QWidget(parent, f)
 {
   setupUi(this);
   mUpdateChanged = false;
   mExecutableChanged = false;
   int h, s, v;
   mSavedColor = palette().color(backgroundRole());
   mSavedColor.getHsv(&h, &s, &v);
   if (s < 20) s = 20;
   mChangedColor.setHsv(240, s, v);
 }
CQTaskHeaderWidget::~CQTaskHeaderWidget () virtual
Definition at line 37 of file CQTaskHeaderWidget.cpp.
 {
   // TODO Auto-generated destructor stub
 }
Member Function Documentation
void CQTaskHeaderWidget::saved ()
Definition at line 48 of file CQTaskHeaderWidget.cpp.
References mExecutableChanged, mSavedColor, and mUpdateChanged.
Referenced by TaskWidget::loadCommon(), and TaskWidget::saveCommon().
 {
   mUpdateChanged = false;
   mpUpdateModel->setStyleSheet(QString(mpUpdateModel->metaObject()->className()) + " {background-color:" + mSavedColor.name() + ";}");
   mExecutableChanged = false;
   mpBoxExecutable->setStyleSheet(QString(mpBoxExecutable->metaObject()->className()) + " {background-color:" + mSavedColor.name() + ";}");
 }
bool CQTaskHeaderWidget::setTaskName (const std::string & name)
Definition at line 42 of file CQTaskHeaderWidget.cpp.
References FROM_UTF8.
Referenced by CQEFMWidget::CQEFMWidget(), CQMoietiesTaskWidget::init(), CQCrossSectionTaskWidget::init(), CQOscillationTaskWidget::init(), CQLyapWidget::init(), CQLNAWidget::init(), CQMCAWidget::init(), SensitivitiesWidget::init(), SteadyStateWidget::init(), CQFittingWidget::init(), CQTSSAWidget::init(), CQOptimizationWidget::init(), CQTrajectoryWidget::init(), and ScanWidget::ScanWidget().
 {
   mpLblName->setText("<h2>" + FROM_UTF8(name) + "</h2>");
   return true;
 }
void CQTaskHeaderWidget::slotExecutable () protected slot
Definition at line 71 of file CQTaskHeaderWidget.cpp.
References mChangedColor, mExecutableChanged, and mSavedColor.
 {
   mExecutableChanged = !mExecutableChanged;
   if (mExecutableChanged)
     {
       mpBoxExecutable->setStyleSheet(QString(mpBoxExecutable->metaObject()->className()) + " {background-color:" + mChangedColor.name() + ";}");
     }
   else
     {
       mpBoxExecutable->setStyleSheet(QString(mpBoxExecutable->metaObject()->className()) + " {background-color:" + mSavedColor.name() + ";}");
     }
 }
void CQTaskHeaderWidget::slotUpdate () protected slot
Definition at line 57 of file CQTaskHeaderWidget.cpp.
References mChangedColor, mSavedColor, and mUpdateChanged.
 {
   mUpdateChanged = !mUpdateChanged;
   if (mUpdateChanged)
     {
       mpUpdateModel->setStyleSheet(QString(mpUpdateModel->metaObject()->className()) + " {background-color:" + mChangedColor.name() + ";}");
     }
   else
     {
       mpUpdateModel->setStyleSheet(QString(mpUpdateModel->metaObject()->className()) + " {background-color:" + mSavedColor.name() + ";}");
     }
 }
Member Data Documentation
QColor CQTaskHeaderWidget::mChangedColor protected
Definition at line 44 of file CQTaskHeaderWidget.h.
Referenced by CQTaskHeaderWidget(), slotExecutable(), and slotUpdate().
bool CQTaskHeaderWidget::mExecutableChanged protected
Definition at line 41 of file CQTaskHeaderWidget.h.
Referenced by CQTaskHeaderWidget(), saved(), and slotExecutable().
QColor CQTaskHeaderWidget::mSavedColor protected
Definition at line 43 of file CQTaskHeaderWidget.h.
Referenced by CQTaskHeaderWidget(), saved(), slotExecutable(), and slotUpdate().
bool CQTaskHeaderWidget::mUpdateChanged protected
Definition at line 42 of file CQTaskHeaderWidget.h.
Referenced by CQTaskHeaderWidget(), saved(), and slotUpdate().
The documentation for this class was generated from the following files:
CQTaskHeaderWidget.h
CQTaskHeaderWidget.cpp