COPASI API: soap_plugin Struct Reference
soap_plugin Struct Reference
#include <stdsoap2.h>
Public Attributes
void * data
int(* fcopy)(struct soap *soap, struct soap_plugin *dst, struct soap_plugin *src)
void(* fdelete)(struct soap *soap, struct soap_plugin *p)
const char * id
struct soap_plugin * next
Detailed Description
Definition at line 1878 of file stdsoap2.h.
Member Data Documentation
void* soap_plugin::data
Definition at line 1882 of file stdsoap2.h.
Referenced by fplugin(), and soap_register_plugin_arg().
int(* soap_plugin::fcopy)(struct soap *soap, struct soap_plugin *dst, struct soap_plugin *src)
Definition at line 1883 of file stdsoap2.h.
Referenced by soap_copy_context(), soap_done(), and soap_register_plugin_arg().
void(* soap_plugin::fdelete)(struct soap *soap, struct soap_plugin *p)
Definition at line 1884 of file stdsoap2.h.
Referenced by soap_done(), and soap_register_plugin_arg().
const char* soap_plugin::id
Definition at line 1881 of file stdsoap2.h.
Referenced by fplugin(), soap_copy_context(), soap_done(), and soap_register_plugin_arg().
struct soap_plugin* soap_plugin::next
Definition at line 1880 of file stdsoap2.h.
Referenced by fplugin(), soap_copy_context(), soap_done(), and soap_register_plugin_arg().
The documentation for this struct was generated from the following file:
stdsoap2.h