COPASI API: CStochNextReactionMethod Class Reference
CStochNextReactionMethod Class Reference
#include <CStochNextReactionMethod.h>
Public Member Functions
CStochNextReactionMethod ()
C_FLOAT64 doSingleStep (C_FLOAT64 time, C_FLOAT64 endTime)
Public Member Functions inherited from CStochMethod
CStochMethod (const CStochMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
virtual bool isValidProblem (const CCopasiProblem *pProblem)
virtual void start (const CState *initialState)
virtual Status step (const double &deltaT)
~CStochMethod ()
Public Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CTrajectoryMethod &src, const CCopasiContainer *pParent=NULL)
const CVector< C_INT > & getRoots () const
void setCurrentState (CState *currentState)
void setProblem (CTrajectoryProblem *problem)
virtual void stateChanged ()
~CTrajectoryMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initMethod (C_FLOAT64 start_time)
void setupPriorityQueue (C_FLOAT64 start_time=0)
void updatePriorityQueue (size_t reaction_index, C_FLOAT64 time)
Private Attributes
CIndexedPriorityQueue mPQ
Additional Inherited Members
Public Types inherited from CTrajectoryMethod
enum Status { FAILURE = -1, NORMAL = 0, ROOT = 1 }
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CTrajectoryMethod
static CTrajectoryMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::deterministic)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CStochMethod
C_INT32 calculateAmu (size_t reaction_index)
CStochMethod (const CCopasiContainer *pParent=NULL)
size_t generateReactionIndex ()
C_FLOAT64 generateReactionTime ()
C_FLOAT64 generateReactionTime (size_t reaction_index)
void setupDependencyGraphAndBalances ()
C_INT32 updatePropensities ()
C_INT32 updateSystemState (size_t reaction_index, const C_FLOAT64 &time)
Protected Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CCopasiMethod::SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Member Functions inherited from CStochMethod
static bool modelHasAssignments (const CModel *pModel)
Protected Attributes inherited from CStochMethod
C_FLOAT64 mA0
std::vector< C_FLOAT64 > mAmu
std::vector< C_FLOAT64 > mAmuOld
CDependencyGraph mDG
bool mDoCorrection
size_t mFirstMetabIndex
bool mHasAssignments
std::vector< std::vector
< CStochBalance > > mLocalBalances
std::vector< std::vector
< CStochBalance > > mLocalSubstrates
std::vector< C_INT64 > mNumbers
size_t mNumReactions
CModel * mpModel
CRandom * mpRandomGenerator
Protected Attributes inherited from CTrajectoryMethod
CState * mpCurrentState
CTrajectoryProblem * mpProblem
CVector< C_INT > mRoots
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 29 of file CStochNextReactionMethod.h.
Constructor & Destructor Documentation
CStochNextReactionMethod::CStochNextReactionMethod ()
Default constructor
Definition at line 23 of file CStochNextReactionMethod.cpp.
   : CStochMethod()
 {}
Member Function Documentation
C_FLOAT64 CStochNextReactionMethod::doSingleStep (C_FLOAT64 time, C_FLOAT64 endTime) virtual
Do one iteration of the simulation
Returns
Current simulation time or -1 if error.
Implements CStochMethod.
Definition at line 32 of file CStochNextReactionMethod.cpp.
References C_FLOAT64, CCopasiMessage::EXCEPTION, MCTrajectoryMethod, mPQ, CIndexedPriorityQueue::topIndex(), CIndexedPriorityQueue::topKey(), updatePriorityQueue(), and CStochMethod::updateSystemState().
 {
   C_FLOAT64 steptime = mPQ.topKey();
   // We need to throw an exception if mA0 is NaN
   if (isnan(steptime))
     {
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 27);
     }
   if (steptime >= endTime)
     {
       return endTime;
     }
   else
     {
       size_t reaction_index = mPQ.topIndex();
       updateSystemState(reaction_index, steptime);
       updatePriorityQueue(reaction_index, steptime);
       //printDebugInfo();
       return steptime;
     }
 }
void CStochNextReactionMethod::initMethod (C_FLOAT64 start_time) private virtual
Initialization.
Implements CStochMethod.
Definition at line 27 of file CStochNextReactionMethod.cpp.
References setupPriorityQueue().
 {
   setupPriorityQueue(start_time);
 }
void CStochNextReactionMethod::setupPriorityQueue (C_FLOAT64 start_time = 0) private
print internal information (for debugging) Set up the priority queue.
Parameters
start_time The time at which the simulation starts.
Definition at line 61 of file CStochNextReactionMethod.cpp.
References CIndexedPriorityQueue::buildHeap(), C_FLOAT64, CIndexedPriorityQueue::clear(), CStochMethod::generateReactionTime(), CModel::getReactions(), CStochMethod::mpModel, mPQ, CIndexedPriorityQueue::pushPair(), and CCopasiVector< T >::size().
Referenced by initMethod().
 {
   C_FLOAT64 time;
   mPQ.clear();
   for (size_t i = 0; i < mpModel->getReactions().size(); i++)
     {
       time = start_time + generateReactionTime(i);
       mPQ.pushPair(i, time);
     }
   mPQ.buildHeap();
 }
void CStochNextReactionMethod::updatePriorityQueue (size_t reaction_index, C_FLOAT64 time) private
Update the priority queue
Definition at line 76 of file CStochNextReactionMethod.cpp.
References C_FLOAT64, CStochMethod::generateReactionTime(), CDependencyGraph::getDependents(), CIndexedPriorityQueue::getKey(), CStochMethod::mAmu, CStochMethod::mAmuOld, CStochMethod::mDG, CStochMethod::mHasAssignments, CStochMethod::mNumReactions, mPQ, and CIndexedPriorityQueue::updateNode().
Referenced by doSingleStep().
 {
   //first the new time for the currently fired reaction
   C_FLOAT64 new_time = time + generateReactionTime(reaction_index);
   mPQ.updateNode(reaction_index, new_time);
   //now the updates for the other reactions (whose propensities may have changed)
   //if the model contains assignment we use a less efficient loop over all reactions since
   // we do not know the exact dependencies
   if (mHasAssignments)
     {
       size_t i;
       for (i = 0; i < mNumReactions; ++i)
         {
           if (i != reaction_index)
             {
               if (mAmu[i] == mAmuOld[i])
                 continue;
               C_FLOAT64 new_time;
               if (mAmuOld[i] > 0)
                 {
                   new_time = time + (mAmuOld[i] / mAmu[i]) * (mPQ.getKey(i) - time);
                 }
               else
                 {
                   new_time = time + generateReactionTime(i);
                 }
               mPQ.updateNode(i, new_time);
             }
         }
     }
   else
     {
       const std::set<size_t> & dep_nodes = mDG.getDependents(reaction_index);
       std::set<size_t>::const_iterator di;
       for (di = dep_nodes.begin(); di != dep_nodes.end(); ++di)
         {
           if (*di != reaction_index)
             {
               size_t index = *di;
               C_FLOAT64 new_time;
               if (mAmuOld[index] > 0)
                 {
                   new_time = time + (mAmuOld[index] / mAmu[index]) * (mPQ.getKey(index) - time);
                 }
               else
                 {
                   new_time = time + generateReactionTime(index);
                 }
               mPQ.updateNode(index, new_time);
             }
         }
     }
 }
Member Data Documentation
CIndexedPriorityQueue CStochNextReactionMethod::mPQ private
The set of putative reactions and associated times at which each reaction occurs. This is represented as a priority queue, indexed on the reaction time.
Definition at line 38 of file CStochNextReactionMethod.h.
Referenced by doSingleStep(), setupPriorityQueue(), and updatePriorityQueue().
The documentation for this class was generated from the following files:
CStochNextReactionMethod.h
CStochNextReactionMethod.cpp