COPASI API: ObjectList Class Reference
ObjectList Class Reference
#include <ObjectBrowserItem.h>
Public Member Functions
ObjectBrowserItem * bucketPop (int &cursor)
void createBucketIndex (int max)
void delDuplicate ()
void destroyBucket ()
ObjectListItem * getRoot ()
void insert (ObjectBrowserItem *pItem)
void insertBucket (ObjectBrowserItem *pItem)
int len ()
ObjectList ()
ObjectBrowserItem * pop ()
void sortList ()
bool sortListInsert (ObjectBrowserItem *pItem)
~ObjectList ()
Private Attributes
int index_length
int length
ObjectBrowserItem ** pointerList
bool * quickIndex
ObjectListItem * root
Detailed Description
Definition at line 157 of file ObjectBrowserItem.h.
Constructor & Destructor Documentation
ObjectList::ObjectList ()
Definition at line 225 of file ObjectBrowserItem.cpp.
                       :
   quickIndex(NULL),
   pointerList(NULL),
   index_length(0),
   root(NULL),
   length(0)
 {}
ObjectList::~ObjectList () inline
Definition at line 168 of file ObjectBrowserItem.h.
References index_length, length, pointerList, pop(), and quickIndex.
   {
     if (index_length != 0)
       {
         delete[] quickIndex;
         delete[] pointerList;
       }
     while (length > 0)
       pop();
   }
Member Function Documentation
ObjectBrowserItem * ObjectList::bucketPop (int & cursor)
Definition at line 407 of file ObjectBrowserItem.cpp.
References index_length, pointerList, and quickIndex.
Referenced by ObjectBrowserWidget::updateUI().
 {
   for (; cursor < index_length; cursor++)
     if (quickIndex[cursor])
       {
         cursor++;
         return pointerList[cursor - 1];
       }
   //nothing avaiable in list
   return NULL;
 }
void ObjectList::createBucketIndex (int max)
Definition at line 362 of file ObjectBrowserItem.cpp.
References getRoot(), index_length, ObjectBrowserItem::key(), KEYBASE, length, max, pdelete, ObjectListItem::pItem, ObjectListItem::pLast, ObjectListItem::pNext, pointerList, quickIndex, and root.
Referenced by ObjectBrowserWidget::updateUI().
 {
   index_length = max;
   quickIndex = new bool[max];
   pointerList = new ObjectBrowserItem * [max];
   int i = 0;
   for (; i < max; i++)
     quickIndex[i] = false;
   int tmpIndex;
   ObjectListItem* pDel;
   for (ObjectListItem* pHead = getRoot(); pHead != NULL;)
     {
       tmpIndex = pHead->pItem->key(0, 0).toInt() - KEYBASE;
       if (quickIndex[tmpIndex]) //delete
         {
           pDel = pHead;
           if (pHead->pLast) pHead->pLast->pNext = pHead->pNext; else root = pHead->pNext;
           if (pHead->pNext)
             pHead->pNext->pLast = pHead->pLast;
           pHead = pHead->pNext;
           pdelete(pDel);
           length--;
         }
       else //
         {
           quickIndex[tmpIndex] = true;
           pointerList[tmpIndex] = pHead->pItem;
           pHead = pHead->pNext;
         }
     }
 }
void ObjectList::delDuplicate ()
Definition at line 277 of file ObjectBrowserItem.cpp.
References getRoot(), ObjectBrowserItem::key(), length, pdelete, ObjectListItem::pItem, ObjectListItem::pLast, and ObjectListItem::pNext.
 {
   ObjectListItem* objectLast = getRoot();
   ObjectListItem* objectNext = (objectLast != NULL) ? objectLast->pNext : NULL;
   for (; objectNext != NULL; objectNext = objectNext->pNext)
     {
       if (objectLast->pItem->key(0, 0) == objectNext->pItem->key(0, 0)) //delete the current item
         {
           objectLast->pNext = objectNext->pNext;
           if (objectNext->pNext) objectNext->pNext->pLast = objectLast;
           pdelete(objectNext);
           length--;
           objectNext = objectLast;
         }
       else // objectLast.key<objectNext.Key
         objectLast = objectNext; //next step
     }
 }
void ObjectList::destroyBucket ()
Definition at line 420 of file ObjectBrowserItem.cpp.
References index_length, pointerList, pop(), and quickIndex.
Referenced by ObjectBrowserWidget::updateUI().
 {
   delete[] quickIndex;
   delete[] pointerList;
   for (ObjectBrowserItem* pHead = pop(); pHead != NULL; pHead = pop());
   index_length = 0;
 }
ObjectListItem * ObjectList::getRoot ()
Definition at line 255 of file ObjectBrowserItem.cpp.
References root.
Referenced by ObjectBrowserWidget::clearClicked(), ObjectBrowserWidget::commitClicked(), createBucketIndex(), delDuplicate(), ObjectBrowserWidget::loadUI(), ObjectBrowserWidget::removeDuplicate(), ObjectBrowserWidget::selectObjects(), sortList(), sortListInsert(), ObjectBrowserWidget::updateSelectedItemsView(), ObjectBrowserWidget::updateUI(), and CBrowserObject::~CBrowserObject().
 {
   return root;
 }
void ObjectList::insert (ObjectBrowserItem * pItem)
Definition at line 233 of file ObjectBrowserItem.cpp.
References length, ObjectListItem::pLast, ObjectListItem::pNext, and root.
Referenced by ObjectBrowserWidget::clickToReverseCheck(), ObjectBrowserWidget::loadChild(), ObjectBrowserItem::ObjectBrowserItem(), ObjectBrowserWidget::removeDuplicate(), ObjectBrowserWidget::selectObjects(), ObjectBrowserWidget::setCheck(), ObjectBrowserWidget::setUncheck(), and sortListInsert().
 {
   int i = 0;
   ObjectListItem* pNewItem = new ObjectListItem(pItem, NULL, NULL);
   if (length == 0)
     {
       root = pNewItem;
       length++;
       return;
     }
   ObjectListItem* pCurrent = root;
   for (; i < length - 1; i++)
     pCurrent = pCurrent->pNext;
   pCurrent->pNext = pNewItem;
   pNewItem->pLast = pCurrent;
   length++;
 }
void ObjectList::insertBucket (ObjectBrowserItem * pItem)
Definition at line 400 of file ObjectBrowserItem.cpp.
References ObjectBrowserItem::key(), KEYBASE, pointerList, and quickIndex.
Referenced by ObjectBrowserWidget::updateUI().
 {
   int tmpIndex = pItem->key(0, 0).toInt() - KEYBASE;
   quickIndex[tmpIndex] = true;
   pointerList[tmpIndex] = pItem;
 }
int ObjectList::len () inline
Definition at line 183 of file ObjectBrowserItem.h.
References length.
Referenced by ObjectBrowserWidget::loadChild(), ObjectBrowserWidget::removeDuplicate(), and sortList().
 {return length;};
ObjectBrowserItem * ObjectList::pop ()
Definition at line 260 of file ObjectBrowserItem.cpp.
References length, pdelete, ObjectListItem::pItem, ObjectListItem::pLast, ObjectListItem::pNext, and root.
Referenced by destroyBucket(), ObjectBrowserWidget::loadChild(), ObjectBrowserWidget::removeDuplicate(), and ~ObjectList().
 {
   if (length == 0) return NULL;
   ObjectBrowserItem* returnValue = root->pItem;
   ObjectListItem* delNode = root;
   root = root->pNext;
   if (root)
     root->pLast = NULL;
   length--;
   pdelete(delNode);
   return returnValue;
 }
void ObjectList::sortList ()
Definition at line 299 of file ObjectBrowserItem.cpp.
References getRoot(), ObjectBrowserItem::key(), len(), ObjectListItem::pItem, and ObjectListItem::pNext.
 {
   if (len() <= 1) //sorted
     return;
   ObjectListItem* pHead = getRoot();
   ObjectListItem* pTail = pHead->pNext;
   for (; pHead->pNext != NULL; pHead = pHead->pNext)
     {
       for (pTail = pHead->pNext; pTail != NULL; pTail = pTail->pNext)
         if (pHead->pItem->key(0, 0) > pTail->pItem->key(0, 0))
           {
             ObjectBrowserItem * pTmp = pHead->pItem;
             pHead->pItem = pTail->pItem;
             pTail->pItem = pTmp;
           }
     }
 }
bool ObjectList::sortListInsert (ObjectBrowserItem * pItem)
Definition at line 320 of file ObjectBrowserItem.cpp.
References getRoot(), insert(), ObjectBrowserItem::key(), length, ObjectListItem::pItem, ObjectListItem::pLast, ObjectListItem::pNext, and root.
 {
   if (getRoot() == NULL) //list is empty
     {
       ObjectListItem* pNewItem = new ObjectListItem(pItem, NULL, NULL);
       root = pNewItem;
       length++;
       return true;
     }
   if (pItem->key(0, 0) < getRoot()->pItem->key(0, 0)) //insert at the front
     {
       ObjectListItem* pNewItem = new ObjectListItem(pItem, root, NULL);
       root->pLast = pNewItem;
       root = pNewItem;
       length++;
       return true;
     }
   ObjectListItem* pHead = getRoot();
   for (; (pHead != NULL) && (pItem->key(0, 0) > pHead->pItem->key(0, 0)); pHead = pHead->pNext)
     ;
   if (pHead && (pHead->pItem->key(0, 0) == pItem->key(0, 0))) //duplicate key
     return false;
   //else insert
   if (pHead == NULL) //insert at the end of the list
     {
       insert(pItem);
       return true;
     }
   length++;
   ObjectListItem* pNewItem = new ObjectListItem(pItem, pHead, pHead->pLast);
   pHead->pLast = pNewItem;
   pNewItem->pLast->pNext = pNewItem;
   return true;
 }
Member Data Documentation
int ObjectList::index_length private
Definition at line 162 of file ObjectBrowserItem.h.
Referenced by bucketPop(), createBucketIndex(), destroyBucket(), and ~ObjectList().
int ObjectList::length private
Definition at line 164 of file ObjectBrowserItem.h.
Referenced by createBucketIndex(), delDuplicate(), insert(), len(), pop(), sortListInsert(), and ~ObjectList().
ObjectBrowserItem** ObjectList::pointerList private
Definition at line 161 of file ObjectBrowserItem.h.
Referenced by bucketPop(), createBucketIndex(), destroyBucket(), insertBucket(), and ~ObjectList().
bool* ObjectList::quickIndex private
Definition at line 160 of file ObjectBrowserItem.h.
Referenced by bucketPop(), createBucketIndex(), destroyBucket(), insertBucket(), and ~ObjectList().
ObjectListItem* ObjectList::root private
Definition at line 163 of file ObjectBrowserItem.h.
Referenced by createBucketIndex(), getRoot(), insert(), pop(), and sortListInsert().
The documentation for this class was generated from the following files:
ObjectBrowserItem.h
ObjectBrowserItem.cpp