COPASI API: COptTask Class Reference
COptTask Class Reference
#include <COptTask.h>
Public Member Functions
void cleanup ()
COptTask (const CCopasiTask::Type &type=CCopasiTask::optimization, const CCopasiContainer *pParent=NULL)
COptTask (const COptTask &src, const CCopasiContainer *pParent=NULL)
virtual CCopasiMethod * createMethod (const int &type) const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
virtual bool process (const bool &useInitialValues)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setMethodType (const int &type)
~COptTask ()
Public Member Functions inherited from CCopasiTask
CCopasiTask (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const Type &taskType, const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const CCopasiTask &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
CProcessReport * getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
Type getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual bool restore ()
virtual void separate (const COutputInterface::Activity &activity)
void setScheduled (const bool &scheduled)
void setType (const Type &type)
void setUpdateModel (const bool &updateModel)
virtual bool updateMatrices ()
virtual ~CCopasiTask ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const unsigned int ValidMethods []
Static Public Attributes inherited from CCopasiTask
static const std::string TypeName []
static const unsigned int ValidMethods []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01, STREAM = 0x02, FINISH = 0x04, REPORT = 0x10,
PLOT = 0x20, TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0, OUTPUT_BEFORE = INITIALIZE, OUTPUT_AFTER = FINISH, OUTPUT = REPORT | PLOT | STREAM,
OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH, OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH, ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
enum Type {
steadyState = 0, timeCourse, scan, fluxMode,
optimization, parameterFitting, mca, lyap,
tssAnalysis, sens, moieties, crosssection,
lna, unset
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiTask
static bool isValidMethod (const unsigned int &method, const unsigned int *validMethods)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
std::string mKey
unsigned C_INT32 mOutputCounter
CProcessReport * mpCallBack
CState * mpInitialState
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
Type mType
bool mUpdateModel
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 42 of file COptTask.h.
Constructor & Destructor Documentation
COptTask::COptTask (const CCopasiTask::Type & type = CCopasiTask::optimization, const CCopasiContainer * pParent = NULL)
default constructor
Parameters
const CCopasiTask::Type & type (default: optimization)
const CCopasiContainer * pParent (default: NULL)
Definition at line 63 of file COptTask.cpp.
References CCopasiContainer::add(), COptMethod::createMethod(), CCopasiTask::mpMethod, and CCopasiTask::mpProblem.
                                                     :
   CCopasiTask(type, pParent)
 {
   mpProblem = new COptProblem(type, this);
   mpMethod = COptMethod::createMethod();
   this->add(mpMethod, true);
   //  mpMethod->setObjectParent(this);
   ((COptMethod *) mpMethod)->setProblem((COptProblem *) mpProblem);
 }
COptTask::COptTask (const COptTask & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const COptTask & src
Definition at line 74 of file COptTask.cpp.
References CCopasiContainer::add(), COptMethod::createMethod(), CCopasiMethod::getSubType(), CCopasiTask::mpMethod, and CCopasiTask::mpProblem.
                                                     :
   CCopasiTask(src, pParent)
 {
   mpProblem = new COptProblem(*(COptProblem *) src.mpProblem, this);
   mpMethod = COptMethod::createMethod(src.mpMethod->getSubType());
   this->add(mpMethod, true);
   //  mpMethod->setObjectParent(this);
   ((COptMethod *) mpMethod)->setProblem((COptProblem *) mpProblem);
 }
COptTask::~COptTask ()
Destructor
Definition at line 85 of file COptTask.cpp.
References cleanup().
 {cleanup();}
Member Function Documentation
void COptTask::cleanup ()
cleanup()
Definition at line 88 of file COptTask.cpp.
Referenced by ~COptTask().
 {}
CCopasiMethod * COptTask::createMethod (const int & type) const virtual
Create a method of the specified type to solve the task. It is the duty of the caller to release the CCopasiMethod.
Parameters
const CCopasiMethod::SubType & type
Returns
CCopasiMethod *
Reimplemented from CCopasiTask.
Reimplemented in CFitTask.
Definition at line 171 of file COptTask.cpp.
References COptMethod::createMethod().
Referenced by setMethodType().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   return COptMethod::createMethod(Type);
 }
bool COptTask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
Reimplemented in CFitTask.
Definition at line 101 of file COptTask.cpp.
References COptProblem::initialize(), CCopasiTask::initialize(), COptProblem::initializeSubtaskBeforeOutput(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, and COptMethod::setProblem().
Referenced by CFitTask::initialize().
 {
   COptProblem * pProblem = dynamic_cast<COptProblem *>(mpProblem);
   COptMethod * pMethod = dynamic_cast<COptMethod *>(mpMethod);
   if (!pProblem || !pMethod) return false;
   //initialize reporting
   bool success = true;
   //do the part of the initialization of the subtask that needs to be
   //performed before the output is initialized. This is kind of a hack,
   //we need to find a more general solution for this
   if (!pProblem->initializeSubtaskBeforeOutput()) success = false;
   if (!CCopasiTask::initialize(of, pOutputHandler, pOstream)) success = false;
   //if (!mReport.open(pOstream)) success = false;
   //if (!mReport.compile()) success = false;
   if (!pProblem->initialize()) success = false;
   pMethod->setProblem(pProblem);
   //  if (!pMethod->initialize()) return false;
   return success;
 }
bool COptTask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
Reimplemented in CFitTask.
Definition at line 131 of file COptTask.cpp.
References COutputInterface::AFTER, COutputInterface::BEFORE, COptProblem::calculateStatistics(), CCopasiMethod::isValidProblem(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, COptMethod::optimise(), CCopasiTask::output(), COptProblem::randomizeStartValues(), COptProblem::rememberStartValues(), and COptProblem::resetEvaluations().
 {
   COptProblem * pProblem = dynamic_cast<COptProblem *>(mpProblem);
   COptMethod * pMethod = dynamic_cast<COptMethod *>(mpMethod);
   if (!pProblem || !pMethod) return false;
   mpMethod->isValidProblem(mpProblem);
   pProblem->randomizeStartValues();
   pProblem->rememberStartValues();
   if (useInitialValues) pProblem->resetEvaluations();
   output(COutputInterface::BEFORE);
   bool success = pMethod->optimise();
   pProblem->calculateStatistics();
   output(COutputInterface::AFTER);
   return success;
 }
bool COptTask::setCallBack (CProcessReport * pCallBack) virtual
Set the call back of the task
Parameters
CProcessReport * pCallBack
Returns
bool success
Reimplemented from CCopasiTask.
Reimplemented in CFitTask.
Definition at line 90 of file COptTask.cpp.
References CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiProblem::setCallBack(), CCopasiMethod::setCallBack(), and CCopasiTask::setCallBack().
 {
   bool success = CCopasiTask::setCallBack(pCallBack);
   if (!mpProblem->setCallBack(pCallBack)) success = false;
   if (!mpMethod->setCallBack(pCallBack)) success = false;
   return success;
 }
bool COptTask::setMethodType (const int & type) virtual
Set the method type applied to solve the task
Parameters
const CCopasiMethod::SubType & type
Returns
bool success
Reimplemented from CCopasiTask.
Reimplemented in CFitTask.
Definition at line 156 of file COptTask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiMethod::getSubType(), CCopasiTask::mpMethod, and pdelete.
Referenced by Arguments::prepareModel().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   if (mpMethod->getSubType() == Type) return true;
   pdelete(mpMethod);
   mpMethod = createMethod(Type);
   this->add(mpMethod, true);
   return true;
 }
Member Data Documentation
const unsigned int COptTask::ValidMethods static
Initial value:
=
{
  CCopasiMethod::Statistics,
  CCopasiMethod::DifferentialEvolution,
  CCopasiMethod::SRES,
  CCopasiMethod::EvolutionaryProgram,
  CCopasiMethod::GeneticAlgorithm,
  CCopasiMethod::GeneticAlgorithmSR,
  CCopasiMethod::HookeJeeves,
  CCopasiMethod::LevenbergMarquardt,
  CCopasiMethod::NelderMead,
  CCopasiMethod::ParticleSwarm,
  CCopasiMethod::Praxis,
  CCopasiMethod::RandomSearch,
  CCopasiMethod::ScatterSearch,
  CCopasiMethod::SimulatedAnnealing,
  CCopasiMethod::SteepestDescent,
  CCopasiMethod::TruncatedNewton,
  CCopasiMethod::unset
}
The methods which can be selected for performing this task.
COptTask class.
This class implements a optimization task which is comprised of a of a problem and a method.
Definition at line 50 of file COptTask.h.
Referenced by CQFittingWidget::init(), and CQOptimizationWidget::init().
The documentation for this class was generated from the following files:
COptTask.h
COptTask.cpp