COPASI API: CCopasiXMLParser::SBMLMapElement Class Reference
CCopasiXMLParser::SBMLMapElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
SBMLMapElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~SBMLMapElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { SBMLMap = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3708 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::SBMLMapElement::Element private
Enum of invoked parsers
Enumerator
SBMLMap
Definition at line 3716 of file CCopasiXMLParser.h.
     {
       SBMLMap = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::SBMLMapElement::SBMLMapElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 10884 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::SBMLMapElement::~SBMLMapElement () virtual
Destructor
Definition at line 10889 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::SBMLMapElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 10947 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case SBMLMap:
         if (strcmp(pszName, "SBMLMap"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "SBMLMap", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::SBMLMapElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 10894 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CKeyFactory::get(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CFunction::setSBMLId(), CModelEntity::setSBMLId(), CReaction::setSBMLId(), and UNKNOWN_ELEMENT.
 {
   const char * SBMLid;
   const char * COPASIkey;
   CCopasiObject * pObject;
   mCurrentElement++; /* We should always be on the next element */
   switch (mCurrentElement)
     {
       case SBMLMap:
         if (strcmp(pszName, "SBMLMap"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "SBMLMap", mParser.getCurrentLineNumber());
         SBMLid = mParser.getAttributeValue("SBMLid", papszAttrs);
         COPASIkey = mParser.getAttributeValue("COPASIkey", papszAttrs);
         if ((pObject = mCommon.KeyMap.get(COPASIkey)))
           {
             CFunction * pFunction;
             CCompartment* pCompartment;
             CMetab * pMetab;
             CModelValue * pModelValue;
             CReaction * pReaction;
             if ((pFunction = dynamic_cast<CFunction *>(pObject)))
               pFunction->setSBMLId(SBMLid);
             else if ((pCompartment = dynamic_cast<CCompartment *>(pObject)))
               pCompartment->setSBMLId(SBMLid);
             else if ((pMetab = dynamic_cast<CMetab *>(pObject)))
               pMetab->setSBMLId(SBMLid);
             else if ((pModelValue = dynamic_cast<CModelValue *>(pObject)))
               pModelValue->setSBMLId(SBMLid);
             else if ((pReaction = dynamic_cast<CReaction *>(pObject)))
               pReaction->setSBMLId(SBMLid);
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp