COPASI API: COptMethodHookeJeeves Class Reference
COptMethodHookeJeeves Class Reference
#include <COptMethodHookeJeeves.h>
Public Member Functions
COptMethodHookeJeeves (const COptMethodHookeJeeves &src, const CCopasiContainer *pParent=NULL)
virtual bool optimise ()
virtual ~COptMethodHookeJeeves ()
Public Member Functions inherited from COptMethod
COptMethod (const COptMethod &src, const CCopasiContainer *pParent=NULL)
bool isBounded (void)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (COptProblem *problem)
virtual ~COptMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
C_FLOAT64 bestNearby ()
virtual bool cleanup ()
COptMethodHookeJeeves (const CCopasiContainer *pParent=NULL)
bool evaluate ()
virtual bool initialize ()
void initObjects ()
Private Attributes
CVector< C_FLOAT64 > mBefore
C_FLOAT64 mBestValue
bool mContinue
CVector< C_FLOAT64 > mDelta
C_FLOAT64 mEvaluationValue
size_t mhIteration
CVector< C_FLOAT64 > mIndividual
unsigned C_INT32 mIteration
unsigned C_INT32 mIterationLimit
CVector< C_FLOAT64 > mNew
C_FLOAT64 mRho
C_FLOAT64 mTolerance
size_t mVariableSize
Friends
COptMethod * COptMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from COptMethod
static COptMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::RandomSearch)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from COptMethod
COptMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from COptMethod
const bool mBounds
const std::vector< COptItem * > * mpOptContraints
const std::vector< COptItem * > * mpOptItem
COptProblem * mpOptProblem
COptTask * mpParentTask
const std::vector
< UpdateMethod * > * mpSetCalculateVariable
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 30 of file COptMethodHookeJeeves.h.
Constructor & Destructor Documentation
COptMethodHookeJeeves::COptMethodHookeJeeves (const COptMethodHookeJeeves & src, const CCopasiContainer * pParent = NULL)
Copy Constructor
Parameters
const COptMethodHookeJeeves & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 51 of file COptMethodHookeJeeves.cpp.
References initObjects().
                                      :
     COptMethod(src, pParent)
 {
   initObjects();
 }
COptMethodHookeJeeves::~COptMethodHookeJeeves () virtual
Destructor
Definition at line 58 of file COptMethodHookeJeeves.cpp.
References cleanup().
 {cleanup();}
COptMethodHookeJeeves::COptMethodHookeJeeves (const CCopasiContainer * pParent = NULL) private
Default Constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 41 of file COptMethodHookeJeeves.cpp.
References CCopasiParameterGroup::addParameter(), C_FLOAT64, C_INT32, CCopasiParameter::DOUBLE, initObjects(), and CCopasiParameter::UINT.
                                                                             :
     COptMethod(CCopasiTask::optimization, CCopasiMethod::HookeJeeves, pParent)
 {
   addParameter("Iteration Limit", CCopasiParameter::UINT, (unsigned C_INT32) 50);
   addParameter("Tolerance", CCopasiParameter::DOUBLE, (C_FLOAT64) 1.e-005);
   addParameter("Rho", CCopasiParameter::DOUBLE, (C_FLOAT64) 0.2);
   initObjects();
 }
Member Function Documentation
C_FLOAT64 COptMethodHookeJeeves::bestNearby () private
Finds the best value in the neighborhood of mNew and updates mNew
Returns
C_FLOAT64 bestValue
Definition at line 293 of file COptMethodHookeJeeves.cpp.
References C_FLOAT64, COptItem::checkConstraint(), evaluate(), COptItem::getLowerBoundValue(), COptItem::getUpperBoundValue(), mBestValue, mDelta, mEvaluationValue, mIndividual, mNew, COptMethod::mpSetCalculateVariable, and mVariableSize.
Referenced by optimise().
 {
   C_FLOAT64 minf = mBestValue;
   size_t i;
   mIndividual = mNew;
   for (i = 0; i < mVariableSize; i++)
     (*(*mpSetCalculateVariable)[i])(mIndividual[i]);
   for (i = 0; i < mVariableSize; i++)
     {
       C_FLOAT64 & mut = mIndividual[i];
       COptItem & OptItem = *(*mpOptItem)[i];
       mut = mNew[i] + mDelta[i];
       // force it to be within the bounds
       switch (OptItem.checkConstraint(mut))
         {
           case - 1:
             mut = *OptItem.getLowerBoundValue();
             break;
           case 1:
             mut = *OptItem.getUpperBoundValue();
             break;
         }
       // We need to set the value here so that further checks take
       // account of the value.
       (*(*mpSetCalculateVariable)[i])(mut);
       if (!evaluate()) break;
       if (mEvaluationValue < minf)
         minf = mEvaluationValue;
       else
         {
           mDelta[i] = - mDelta[i];
           mut = mNew[i] + mDelta[i];
           // force it to be within the bounds
           switch (OptItem.checkConstraint(mut))
             {
               case - 1:
                 mut = *OptItem.getLowerBoundValue();
                 break;
               case 1:
                 mut = *OptItem.getUpperBoundValue();
                 break;
             }
           // We need to set the value here so that further checks take
           // account of the value.
           (*(*mpSetCalculateVariable)[i])(mut);
           if (!evaluate()) break;
           if (mEvaluationValue < minf)
             minf = mEvaluationValue;
           else
             {
               mut = mNew[i];
               (*(*mpSetCalculateVariable)[i])(mut);
             }
         }
     }
   mNew = mIndividual;
   return(minf);
 }
bool COptMethodHookeJeeves::cleanup () private virtual
Cleanup arrays and pointers.
Returns
bool success
Reimplemented from COptMethod.
Definition at line 263 of file COptMethodHookeJeeves.cpp.
Referenced by initialize(), optimise(), and ~COptMethodHookeJeeves().
 {
   return true;
 }
bool COptMethodHookeJeeves::evaluate () private
Evaluate the fitness of one individual
Returns
bool continue
Definition at line 268 of file COptMethodHookeJeeves.cpp.
References COptProblem::calculate(), COptProblem::checkFunctionalConstraints(), COptProblem::checkParametricConstraints(), COptProblem::getCalculateValue(), max, mContinue, mEvaluationValue, and COptMethod::mpOptProblem.
Referenced by bestNearby(), and optimise().
 {
   // We do not need to check whether the parametric constraints are fulfilled
   // since the parameters are created within the bounds.
   // evaluate the fitness
   if (!mpOptProblem->checkParametricConstraints())
     {
       mEvaluationValue = std::numeric_limits< C_FLOAT64 >::max();
       return mContinue;
     }
   mContinue &= mpOptProblem->calculate();
   // check whether the functional constraints are fulfilled
   if (!mpOptProblem->checkFunctionalConstraints())
     mEvaluationValue = std::numeric_limits<C_FLOAT64>::infinity();
   else
     // get the value of the objective function
     mEvaluationValue = mpOptProblem->getCalculateValue();
   return mContinue;
 }
bool COptMethodHookeJeeves::initialize () private virtual
Initialize arrays and pointer.
Returns
bool success
Reimplemented from COptMethod.
Definition at line 233 of file COptMethodHookeJeeves.cpp.
References CProcessReport::addItem(), cleanup(), CCopasiParameter::getValue(), COptMethod::initialize(), mBefore, mBestValue, mDelta, mhIteration, mIndividual, mIteration, mIterationLimit, mNew, CCopasiMethod::mpCallBack, COptMethod::mpOptItem, mRho, mTolerance, mVariableSize, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pUINT, and CVector< CType >::resize().
Referenced by optimise().
 {
   cleanup();
   if (!COptMethod::initialize()) return false;
   mIterationLimit = * getValue("Iteration Limit").pUINT;
   mTolerance = * getValue("Tolerance").pDOUBLE;
   mRho = * getValue("Rho").pDOUBLE;
   mIteration = 0;
   if (mpCallBack)
     mhIteration =
       mpCallBack->addItem("Current Iteration",
                           mIteration,
                           & mIterationLimit);
   mVariableSize = mpOptItem->size();
   mIndividual.resize(mVariableSize);
   mBefore.resize(mVariableSize);
   mNew.resize(mVariableSize);
   mDelta.resize(mVariableSize);
   mBestValue = std::numeric_limits<C_FLOAT64>::infinity();
   return true;
 }
void COptMethodHookeJeeves::initObjects () private
Initialize contained objects.
Definition at line 228 of file COptMethodHookeJeeves.cpp.
References CCopasiContainer::addObjectReference(), mIteration, and CCopasiObject::ValueInt.
Referenced by COptMethodHookeJeeves().
 {
   addObjectReference("Current Iteration", mIteration, CCopasiObject::ValueInt);
 }
bool COptMethodHookeJeeves::optimise (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback. @ return success;
Reimplemented from COptMethod.
Definition at line 61 of file COptMethodHookeJeeves.cpp.
References bestNearby(), C_FLOAT64, COptItem::checkConstraint(), cleanup(), COutputInterface::DURING, evaluate(), CProcessReport::finishItem(), COptItem::getLowerBoundValue(), COptItem::getStartValue(), COptItem::getUpperBoundValue(), initialize(), mBefore, mBestValue, mContinue, mDelta, mEvaluationValue, mhIteration, mIndividual, mIteration, mIterationLimit, mNew, CCopasiMethod::mpCallBack, COptMethod::mpOptProblem, COptMethod::mpParentTask, mRho, mTolerance, mVariableSize, CCopasiTask::output(), CProcessReport::progressItem(), and COptProblem::setSolution().
 {
   mContinue = true;
   if (!initialize())
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhIteration);
       return false;
     }
   C_FLOAT64 newf, steplength, tmp;
   bool Keep;
   size_t iadj;
   // initial point is first guess
   size_t i;
   // initialise the guess vector
   for (i = 0; i < mVariableSize; i++)
     {
       C_FLOAT64 & mut = mIndividual[i];
       COptItem & OptItem = *(*mpOptItem)[i];
       mut = OptItem.getStartValue();
       // force it to be within the bounds
       switch (OptItem.checkConstraint(mut))
         {
           case - 1:
             mut = *OptItem.getLowerBoundValue();
             break;
           case 1:
             mut = *OptItem.getUpperBoundValue();
             break;
         }
       // We need to set the value here so that further checks take
       // account of the value.
       (*(*mpSetCalculateVariable)[i])(mut);
     }
   mContinue &= evaluate();
   // The first value is also the best
   mBestValue = mEvaluationValue;
   mpOptProblem->setSolution(mBestValue, mIndividual);
   mpParentTask->output(COutputInterface::DURING);
   if (!mContinue)
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhIteration);
       cleanup();
       return true;
     }
   for (i = 0; i < mVariableSize; i++)
     {
       mNew[i] = mBefore[i] = mIndividual[i];
       mDelta[i] = fabs(mIndividual[i] * mRho);
       if (mDelta[i] == 0.0) mDelta[i] = mRho;
     }
   iadj = 0;
   steplength = mRho;
   newf = mBestValue;
   while ((mIteration < mIterationLimit) && (steplength > mTolerance) && mContinue)
     {
       // signal another iteration to Gepasi
       if (mpCallBack)
         mContinue &= mpCallBack->progressItem(mhIteration);
       mIteration++;
       iadj++;
       /* find best new point, one coord at a time */
       mNew = mBefore;
       newf = bestNearby();
       /* if we made some improvements, pursue that direction */
       Keep = true;
       while ((newf < mBestValue) && Keep && mContinue)
         {
           // We found a better value
           mBestValue = newf;
           mpOptProblem->setSolution(mBestValue, mNew);
           mpParentTask->output(COutputInterface::DURING);
           iadj = 0;
           for (i = 0; i < mVariableSize; i++)
             {
               C_FLOAT64 & mut = mNew[i];
               COptItem & OptItem = *(*mpOptItem)[i];
               /* firstly, arrange the sign of mDelta[] */
               if (mut <= mBefore[i])
                 mDelta[i] = - fabs(mDelta[i]);
               else
                 mDelta[i] = fabs(mDelta[i]);
               /* now, move further in this direction */
               tmp = mBefore[i];
               mBefore[i] = mut;
               mut = mut + mut - tmp;
               // force it to be within the bounds
               switch (OptItem.checkConstraint(mut))
                 {
                   case - 1:
                     mut = *OptItem.getLowerBoundValue();
                     break;
                   case 1:
                     mut = *OptItem.getUpperBoundValue();
                     break;
                 }
               // We need to set the value here so that further checks take
               // account of the value.
               (*(*mpSetCalculateVariable)[i])(mut);
             }
           newf = bestNearby();
           /* if the further (optimistic) move was bad.... */
           if (newf >= mBestValue) break;
           /* make sure that the differences between the new */
           /* and the old points are due to actual */
           /* displacements; beware of roundoff errors that */
           /* might cause newf < mBestValue */
           Keep = false;
           for (i = 0; i < mVariableSize; i++)
             if (fabs(mNew[i] - mBefore[i]) > (0.5 * fabs(mDelta[i])))
               {
                 Keep = true;
                 break;
               }
         }
       if ((steplength >= mTolerance) && (newf >= mBestValue))
         {
           steplength = steplength * mRho;
           for (i = 0; i < mVariableSize; i++)
             mDelta[i] *= mRho;
         }
     }
   if (mpCallBack)
     mpCallBack->finishItem(mhIteration);
   cleanup();
   return true;
 }
Friends And Related Function Documentation
COptMethod* COptMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
CVector< C_FLOAT64 > COptMethodHookeJeeves::mBefore private
The last individual
Definition at line 134 of file COptMethodHookeJeeves.h.
Referenced by initialize(), and optimise().
C_FLOAT64 COptMethodHookeJeeves::mBestValue private
The best value found so far
Definition at line 154 of file COptMethodHookeJeeves.h.
Referenced by bestNearby(), initialize(), and optimise().
bool COptMethodHookeJeeves::mContinue private
Flag indicating whether the computation shall continue
Definition at line 159 of file COptMethodHookeJeeves.h.
Referenced by evaluate(), and optimise().
CVector< C_FLOAT64 > COptMethodHookeJeeves::mDelta private
The step taken
Definition at line 144 of file COptMethodHookeJeeves.h.
Referenced by bestNearby(), initialize(), and optimise().
C_FLOAT64 COptMethodHookeJeeves::mEvaluationValue private
The value of the last evaluation.
Definition at line 149 of file COptMethodHookeJeeves.h.
Referenced by bestNearby(), evaluate(), and optimise().
size_t COptMethodHookeJeeves::mhIteration private
Handle to the process report item "Current Iteration"
Definition at line 119 of file COptMethodHookeJeeves.h.
Referenced by initialize(), and optimise().
CVector< C_FLOAT64 > COptMethodHookeJeeves::mIndividual private
The current individual
Definition at line 129 of file COptMethodHookeJeeves.h.
Referenced by bestNearby(), initialize(), and optimise().
unsigned C_INT32 COptMethodHookeJeeves::mIteration private
The number of iterations
Definition at line 114 of file COptMethodHookeJeeves.h.
Referenced by initialize(), initObjects(), and optimise().
unsigned C_INT32 COptMethodHookeJeeves::mIterationLimit private
The maximum number of iterations
Definition at line 99 of file COptMethodHookeJeeves.h.
Referenced by initialize(), and optimise().
CVector< C_FLOAT64 > COptMethodHookeJeeves::mNew private
The new individual
Definition at line 139 of file COptMethodHookeJeeves.h.
Referenced by bestNearby(), initialize(), and optimise().
C_FLOAT64 COptMethodHookeJeeves::mRho private
The length of steps taken
Definition at line 109 of file COptMethodHookeJeeves.h.
Referenced by initialize(), and optimise().
C_FLOAT64 COptMethodHookeJeeves::mTolerance private
The tolerance
Definition at line 104 of file COptMethodHookeJeeves.h.
Referenced by initialize(), and optimise().
size_t COptMethodHookeJeeves::mVariableSize private
number of parameters
Definition at line 124 of file COptMethodHookeJeeves.h.
Referenced by bestNearby(), initialize(), and optimise().
The documentation for this class was generated from the following files:
COptMethodHookeJeeves.h
COptMethodHookeJeeves.cpp