COPASI API: CQLayoutsDM Class Reference
CQLayoutsDM Class Reference
#include <CQLayoutsDM.h>
Public Member Functions
virtual bool clear ()
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQLayoutsDM (QObject *parent=0)
virtual QVariant data (const QModelIndex &index, int role) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
virtual bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRows (QModelIndexList rows, const QModelIndex &index=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setListOfLayouts (CListOfLayouts *pListOfLayouts)
virtual ~CQLayoutsDM ()
Public Member Functions inherited from CQBaseDataModel
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
bool removeRow (int position)
Protected Member Functions
virtual bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Private Attributes
CListOfLayouts * mpListOfLayouts
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 26 of file CQLayoutsDM.h.
Constructor & Destructor Documentation
CQLayoutsDM::CQLayoutsDM (QObject * parent = 0)
Definition at line 16 of file CQLayoutsDM.cpp.
                                         :
   CQBaseDataModel(parent),
   mpListOfLayouts(NULL)
 {}
CQLayoutsDM::~CQLayoutsDM () virtual
Definition at line 21 of file CQLayoutsDM.cpp.
 {}
Member Function Documentation
bool CQLayoutsDM::clear () virtual
Reimplemented from CQBaseDataModel.
Definition at line 31 of file CQLayoutsDM.cpp.
References removeRows(), and rowCount().
Referenced by CQLayoutsWidget::slotBtnClearClicked().
 {
   return removeRows(0, rowCount());
 }
int CQLayoutsDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 36 of file CQLayoutsDM.cpp.
References TOTAL_COLS.
 {
   return TOTAL_COLS;
 }
QVariant CQLayoutsDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 64 of file CQLayoutsDM.cpp.
References COL_NAME, COL_ROW_NUMBER, COL_SHOW, FROM_UTF8, mpListOfLayouts, and rowCount().
 {
   if (mpListOfLayouts == NULL) return QVariant();
   if (!index.isValid()) return QVariant();
   if (index.row() >= rowCount()) return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return QVariant(index.row() + 1);
             break;
           case COL_NAME:
             return QVariant(FROM_UTF8((*mpListOfLayouts)[index.row()]->getObjectName()));
             break;
           case COL_SHOW:
             return (role == Qt::EditRole) ? QVariant("Show") : QVariant();
             break;
         }
     }
   return QVariant();
 }
Qt::ItemFlags CQLayoutsDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 41 of file CQLayoutsDM.cpp.
References COL_NAME, COL_ROW_NUMBER, and COL_SHOW.
 {
   if (!index.isValid())
     return QAbstractItemModel::flags(index);
   switch (index.column())
     {
       case COL_ROW_NUMBER:
         return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
         break;
       case COL_NAME:
         return QAbstractItemModel::flags(index) & ~Qt::ItemIsEditable;
         break;
       case COL_SHOW:
         return QAbstractItemModel::flags(index) | Qt::ItemIsEditable | Qt::ItemIsEnabled;
         break;
     }
   return QAbstractItemModel::flags(index);
 }
QVariant CQLayoutsDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 93 of file CQLayoutsDM.cpp.
References COL_NAME, COL_ROW_NUMBER, and COL_SHOW.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
             break;
           case COL_NAME:
             return QVariant(QString("Name"));
             break;
           case COL_SHOW:
             return QVariant("Show");
             break;
           default:
             return QVariant();
             break;
         }
     }
   return QString("%1").arg(section + 1);
 }
bool CQLayoutsDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) virtual
Implements CQBaseDataModel.
Definition at line 163 of file CQLayoutsDM.cpp.
References ListViews::ADD, ListViews::LAYOUT, mpListOfLayouts, CQBaseDataModel::notifyGUI(), and CCopasiVector< T >::size().
Referenced by CQLayoutsWidget::slotBtnNewClicked().
 {
   if (mpListOfLayouts == NULL) return false;
   if (position + rows > (int) mpListOfLayouts->size())  return false;
   beginInsertRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       emit notifyGUI(ListViews::LAYOUT, ListViews::ADD, (*mpListOfLayouts)[position + row]->getKey());
     }
   endInsertRows();
   return true;
 }
bool CQLayoutsDM::isDefaultRow (const QModelIndex & i) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 158 of file CQLayoutsDM.cpp.
 {
   return false;
 }
bool CQLayoutsDM::removeRows (QModelIndexList rows, const QModelIndex & index = QModelIndex())
Definition at line 216 of file CQLayoutsDM.cpp.
References C_INVALID_INDEX, CQMessageBox::confirmDelete(), FROM_UTF8, CCopasiVector< T >::getIndex(), CCopasiObject::getObjectName(), mpListOfLayouts, and CQBaseDataModel::removeRow().
Referenced by clear(), and CQLayoutsWidget::deleteSelectedLayouts().
 {
   if (rows.isEmpty()) return false;
   if (mpListOfLayouts == NULL) return false;
   //  Build the list of pointers to items to be deleted
   //  before actually deleting any item.
   QList< CLayout * > Layouts;
   QModelIndexList::const_iterator i;
   for (i = rows.begin(); i != rows.end(); ++i)
     {
       Layouts.append((*mpListOfLayouts)[(*i).row()]);
     }
   QList< CLayout * >::const_iterator j;
   for (j = Layouts.begin(); j != Layouts.end(); ++j)
     {
       CLayout * pLayout = *j;
       size_t delRow = mpListOfLayouts->getIndex(pLayout);
       if (delRow != C_INVALID_INDEX)
         {
           QMessageBox::StandardButton choice =
             CQMessageBox::confirmDelete(NULL, "layout",
                                         FROM_UTF8(pLayout->getObjectName()),
                                         std::set< const CCopasiObject * >());
           if (choice == QMessageBox::Ok)
             removeRow((int) delRow);
         }
     }
   return true;
 }
bool CQLayoutsDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 181 of file CQLayoutsDM.cpp.
References CCopasiVector< T >::begin(), ListViews::DELETE, ListViews::LAYOUT, mpListOfLayouts, CQBaseDataModel::notifyGUI(), and pdelete.
 {
   if (rows <= 0) return true;
   if (mpListOfLayouts == NULL) return false;
   beginRemoveRows(QModelIndex(), position, position + rows - 1);
   std::vector< CLayout * > DeletedLayouts;
   DeletedLayouts.resize(rows);
   std::vector< CLayout * >::iterator itDeletedLayout;
   std::vector< CLayout * >::iterator endDeletedLayout = DeletedLayouts.end();
   CListOfLayouts::const_iterator itRow = mpListOfLayouts->begin() + position;
   for (itDeletedLayout = DeletedLayouts.begin(); itDeletedLayout != endDeletedLayout; ++itDeletedLayout, ++itRow)
     {
       *itDeletedLayout = *itRow;
     }
   for (itDeletedLayout = DeletedLayouts.begin(); itDeletedLayout != endDeletedLayout; ++itDeletedLayout)
     {
       std::string Key = (*itDeletedLayout)->getKey();
       pdelete(*itDeletedLayout);
       emit notifyGUI(ListViews::LAYOUT, ListViews::DELETE, Key);
     }
   endRemoveRows();
   return true;
 }
int CQLayoutsDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 24 of file CQLayoutsDM.cpp.
References mpListOfLayouts, and CCopasiVector< T >::size().
Referenced by clear(), data(), CQLayoutsWidget::deleteSelectedLayouts(), setData(), CQLayoutsWidget::showButtons(), and CQLayoutsWidget::slotDoubleClicked().
 {
   if (mpListOfLayouts == NULL) return 0;
   return (int) mpListOfLayouts->size();
 }
bool CQLayoutsDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 124 of file CQLayoutsDM.cpp.
References COL_NAME, COL_ROW_NUMBER, COL_SHOW, mpListOfLayouts, and rowCount().
 {
   if (mpListOfLayouts == NULL) return false;
   if (!index.isValid()) return false;
   if (index.row() >= rowCount()) return false;
   if (index.isValid() && role == Qt::EditRole)
     {
       switch (index.column())
         {
           case COL_ROW_NUMBER:
             return false;
             break;
           case COL_NAME:
             return false;
             break;
           case COL_SHOW:
             return true;
             break;
           default:
             return false;
             break;
         }
     }
   return true;
 }
void CQLayoutsDM::setListOfLayouts (CListOfLayouts * pListOfLayouts)
Definition at line 255 of file CQLayoutsDM.cpp.
References mpListOfLayouts.
Referenced by CQLayoutsWidget::enterProtected().
 {
   if (mpListOfLayouts != pListOfLayouts)
     {
       mpListOfLayouts = pListOfLayouts;
       reset();
     }
 }
Member Data Documentation
CListOfLayouts* CQLayoutsDM::mpListOfLayouts private
Definition at line 54 of file CQLayoutsDM.h.
Referenced by data(), insertRows(), removeRows(), rowCount(), setData(), and setListOfLayouts().
The documentation for this class was generated from the following files:
CQLayoutsDM.h
CQLayoutsDM.cpp