COPASI API: QFluxModeAnimation Class Reference
QFluxModeAnimation Class Reference
Public Member Functions
virtual void getScales (std::vector< qreal > &scales, int step)
virtual void initialize (const CCopasiDataModel &dataModel)
Public Member Functions inherited from CQCopasiAnimation
virtual void applyToScene (CQLayoutScene &scene, int step)
CQCopasiAnimation ()
std::vector
< CQEffectDescription * > & getEntries ()
virtual int getNumSteps ()
ScaleMode getScaleMode () const
virtual void removeFromScene (CQLayoutScene &scene)
void setScaleMode (ScaleMode mode)
virtual ~CQCopasiAnimation ()
Protected Attributes
std::map< size_t, std::string > indexMap
Protected Attributes inherited from CQCopasiAnimation
std::vector
< CQEffectDescription * > mEntries
ScaleMode mMode
int mNumSteps
const CCopasiDataModel * mpDataModel
Additional Inherited Members
Public Types inherited from CQCopasiAnimation
enum ScaleMode { Global, Individual }
Detailed Description
Animation, that displays one fluxmode per frame
Definition at line 84 of file CQAnimationWindow.cpp.
Member Function Documentation
virtual void QFluxModeAnimation::getScales (std::vector< qreal > & scales, int step) inline virtual
Reimplemented from CQCopasiAnimation.
Definition at line 115 of file CQAnimationWindow.cpp.
References CFluxMode::begin(), CFluxMode::end(), CEFMProblem::getFluxModes(), CCopasiTask::getProblem(), CEFMProblem::getReorderedReactions(), CCopasiDataModel::getTaskList(), CQCopasiAnimation::mEntries, CQCopasiAnimation::mNumSteps, and CQCopasiAnimation::mpDataModel.
   {
     if (mpDataModel == NULL) return;
     CEFMTask *task = dynamic_cast< CEFMTask * >((*mpDataModel->getTaskList())["Elementary Flux Modes"]);
     if (task == NULL) return;
     const CEFMProblem* problem = dynamic_cast<const CEFMProblem*>(task->getProblem());
     if (problem == NULL) return;
     const std::vector< CFluxMode >& fluxModes = problem->getFluxModes();
     mNumSteps = fluxModes.size();
     if (fluxModes.size() <= (size_t)step) return;
     const CFluxMode& mode = fluxModes[step];
     const std::vector< const CReaction * > &reordered = problem->getReorderedReactions();
     std::map<std::string, double> cnValueMap;
     CFluxMode::const_iterator modeIt = mode.begin();
     while (modeIt  != mode.end())
       {
         const size_t reactionIndex = (*modeIt).first;
         const double coefficient = (*modeIt).second;
         cnValueMap[reordered[reactionIndex]->getCN()] = qAbs(coefficient);
         ++modeIt;
       }
     for (size_t i = 0; i < mEntries.size(); ++i)
       scales.push_back(cnValueMap[mEntries[i]->getCN()]);
   }
virtual void QFluxModeAnimation::initialize (const CCopasiDataModel & dataModel) inline virtual
Implements CQCopasiAnimation.
Definition at line 87 of file CQAnimationWindow.cpp.
References CCopasiVector< T >::begin(), CQEffectDescription::Colorize, CCopasiVector< T >::end(), CEFMProblem::getFluxModes(), CCopasiDataModel::getModel(), CCopasiTask::getProblem(), CModel::getReactions(), CCopasiDataModel::getTaskList(), indexMap, CQCopasiAnimation::mEntries, CQCopasiAnimation::mNumSteps, and CQCopasiAnimation::mpDataModel.
   {
     mpDataModel = &dataModel;
     const CModel& model = *dataModel.getModel();
     const CCopasiVector< CReaction > & reactions = model.getReactions();
     CCopasiVector< CReaction >::const_iterator it = reactions.begin();
     size_t count = 0;
     while (it != reactions.end())
       {
         mEntries.push_back(new CQEffectDescription((*it)->getCN(), CQEffectDescription::Colorize, Qt::black, Qt::red));
         indexMap[count] = (*it)->getCN();
         ++it;
         ++count;
       }
     // initialize number of steps
     CEFMTask *task = dynamic_cast< CEFMTask * >((*mpDataModel->getTaskList())["Elementary Flux Modes"]);
     if (task == NULL) return;
     const CEFMProblem* problem = dynamic_cast<const CEFMProblem*>(task->getProblem());
     if (problem == NULL) return;
     const std::vector< CFluxMode >& fluxModes = problem->getFluxModes();
     mNumSteps = fluxModes.size();
   }
Member Data Documentation
std::map<size_t, std::string> QFluxModeAnimation::indexMap protected
Definition at line 152 of file CQAnimationWindow.cpp.
Referenced by initialize().
The documentation for this class was generated from the following file:
CQAnimationWindow.cpp