COPASI API: CQPlotsWidget Class Reference
CQPlotsWidget Class Reference
#include <CQPlotsWidget.h>
Public Member Functions
CQPlotsWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQPlotsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnActivateAllClicked ()
virtual void slotBtnClearClicked ()
virtual void slotBtnDeactivateAllClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
virtual void keyPressEvent (QKeyEvent *ev)
Private Member Functions
void deleteSelectedPlots ()
void updateDeleteBtns ()
Private Attributes
CQPlotDM * mpPlotDM
CQSortFilterProxyModel * mpProxyModel
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 21 of file CQPlotsWidget.h.
Constructor & Destructor Documentation
CQPlotsWidget::CQPlotsWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 32 of file CQPlotsWidget.cpp.
References COL_ROW_NUMBER, dataChanged(), CopasiWidget::mFramework, mpPlotDM, mpProxyModel, CopasiWidget::protectedNotify(), setFramework(), slotBtnActivateAllClicked(), slotBtnDeactivateAllClicked(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpPlotDM = new CQPlotDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpTblPlots->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblPlots->verticalHeader()->hide();
   mpTblPlots->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   setFramework(mFramework);
   // Connect the table widget
   connect(mpPlotDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpPlotDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
   connect(mpBtnActivateAll, SIGNAL(pressed()), this, SLOT(slotBtnActivateAllClicked()));
   connect(mpBtnDeactivateAll, SIGNAL(pressed()), this, SLOT(slotBtnDeactivateAllClicked()));
 }
CQPlotsWidget::~CQPlotsWidget ()
Definition at line 65 of file CQPlotsWidget.cpp.
References mpPlotDM, mpProxyModel, and pdelete.
 {
   pdelete(mpProxyModel);
   pdelete(mpPlotDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQPlotsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 226 of file CQPlotsWidget.cpp.
References CopasiWidget::mFramework, setFramework(), and updateDeleteBtns().
Referenced by CQPlotsWidget().
 {
   mpTblPlots->resizeColumnsToContents();
   setFramework(mFramework);
   updateDeleteBtns();
 }
void CQPlotsWidget::deleteSelectedPlots () private
Definition at line 120 of file CQPlotsWidget.cpp.
References mpPlotDM, mpProxyModel, CQPlotDM::removeRows(), and CQPlotDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblPlots->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpPlotDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpPlotDM->removeRows(mappedSelRows);
 }
bool CQPlotsWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 170 of file CQPlotsWidget.cpp.
References CopasiWidget::mFramework, mpPlotDM, mpProxyModel, setFramework(), slotSelectionChanged(), and updateDeleteBtns().
Referenced by update().
 {
   if (mpTblPlots->selectionModel() != NULL)
     {
       disconnect(mpTblPlots->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpProxyModel->setSourceModel(mpPlotDM);
   //Set Model for the TableView
   mpTblPlots->setModel(NULL);
   mpTblPlots->setModel(mpProxyModel);
   connect(mpTblPlots->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblPlots->resizeColumnsToContents();
   setFramework(mFramework);
   return true;
 }
void CQPlotsWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 260 of file CQPlotsWidget.cpp.
References CQPlotDM::columnCount(), mpPlotDM, mpProxyModel, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C &&
            (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblPlots->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpPlotDM->columnCount(); ++x)
             {
               if (!mpTblPlots->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpPlotDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQPlotsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 165 of file CQPlotsWidget.cpp.
 {
   return true;
 }
void CQPlotsWidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 301 of file CQPlotsWidget.cpp.
References CopasiWidget::setFramework().
Referenced by CQPlotsWidget(), dataChanged(), and enterProtected().
 {
   CopasiWidget::setFramework(framework);
 }
void CQPlotsWidget::slotBtnActivateAllClicked () protected virtual slot
Definition at line 72 of file CQPlotsWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getModel(), CCopasiDataModel::getPlotDefinitionList(), CPlotSpecification::setActive(), and CCopasiVector< T >::size().
Referenced by CQPlotsWidget().
 {
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (!pDataModel->getModel())
     return;
   for (size_t i = 0; i < pDataModel->getPlotDefinitionList()->size(); i++)
     {
       CPlotSpecification *pPS = static_cast<CPlotSpecification *>(pDataModel->getPlotDefinitionList()->operator[](i));
       pPS->setActive(true);
     }
   mpTblPlots->doItemsLayout();
 }
void CQPlotsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 141 of file CQPlotsWidget.cpp.
References CQBaseDataModel::clear(), mpPlotDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Plots?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpPlotDM->clear();
     }
   updateDeleteBtns();
 }
void CQPlotsWidget::slotBtnDeactivateAllClicked () protected virtual slot
Definition at line 89 of file CQPlotsWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getModel(), CCopasiDataModel::getPlotDefinitionList(), CPlotSpecification::setActive(), and CCopasiVector< T >::size().
Referenced by CQPlotsWidget().
 {
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (!pDataModel->getModel())
     return;
   for (size_t i = 0; i < pDataModel->getPlotDefinitionList()->size(); i++)
     {
       CPlotSpecification *pPS = static_cast<CPlotSpecification *>(pDataModel->getPlotDefinitionList()->operator[](i));
       pPS->setActive(false);
     }
   mpTblPlots->doItemsLayout();
 }
void CQPlotsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 112 of file CQPlotsWidget.cpp.
References deleteSelectedPlots(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblPlots->hasFocus())
     {deleteSelectedPlots();}
   updateDeleteBtns();
 }
void CQPlotsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 106 of file CQPlotsWidget.cpp.
References CQBaseDataModel::insertRow(), mpPlotDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpPlotDM->insertRow();
   updateDeleteBtns();
 }
void CQPlotsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 234 of file CQPlotsWidget.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CCopasiRootContainer::getDatamodelList(), CCopasiRootContainer::getKeyFactory(), CCopasiDataModel::getModel(), CCopasiDataModel::getPlotDefinitionList(), CQBaseDataModel::isDefaultRow(), CopasiWidget::mpListView, mpPlotDM, mpProxyModel, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpPlotDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   if (!pDataModel->getModel())
     return;
   CPlotSpecification *pPS = static_cast<CPlotSpecification *>(pDataModel->getPlotDefinitionList()->operator[](index.row()));
   const std::string key = static_cast<CCopasiParameter *>(pPS)->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQPlotsWidget::slotFilterChanged () protected virtual slot
Definition at line 295 of file CQPlotsWidget.cpp.
References mpProxyModel.
Referenced by CQPlotsWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Plot", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQPlotsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 220 of file CQPlotsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQPlotsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 155 of file CQPlotsWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQPlotsWidget::updateDeleteBtns () private
Definition at line 191 of file CQPlotsWidget.cpp.
References CQBaseDataModel::isDefaultRow(), mpPlotDM, and mpProxyModel.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblPlots->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpPlotDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
CQPlotDM* CQPlotsWidget::mpPlotDM private
Definition at line 34 of file CQPlotsWidget.h.
Referenced by CQPlotsWidget(), deleteSelectedPlots(), enterProtected(), keyPressEvent(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQPlotsWidget().
CQSortFilterProxyModel* CQPlotsWidget::mpProxyModel private
Definition at line 35 of file CQPlotsWidget.h.
Referenced by CQPlotsWidget(), deleteSelectedPlots(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQPlotsWidget().
The documentation for this class was generated from the following files:
CQPlotsWidget.h
CQPlotsWidget.cpp