COPASI API: test000077 Class Reference
test000077 Class Reference
#include <test000077.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_export_dimensionless ()
void test_import_dimensionless_1 ()
void test_import_dimensionless_2 ()
void test_import_dimensionless_3 ()
void test_import_dimensionless_4 ()
void test_import_dimensionless_5 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_dimensionless_1)
CPPUNIT_TEST (test_import_dimensionless_2)
CPPUNIT_TEST (test_import_dimensionless_3)
CPPUNIT_TEST (test_import_dimensionless_4)
CPPUNIT_TEST (test_import_dimensionless_5)
CPPUNIT_TEST (test_export_dimensionless)
CPPUNIT_TEST_SUITE (test000077)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 27 of file test000077.h.
Member Function Documentation
test000077::CPPUNIT_TEST (test_import_dimensionless_1) private
test000077::CPPUNIT_TEST (test_import_dimensionless_2) private
test000077::CPPUNIT_TEST (test_import_dimensionless_3) private
test000077::CPPUNIT_TEST (test_import_dimensionless_4) private
test000077::CPPUNIT_TEST (test_import_dimensionless_5) private
test000077::CPPUNIT_TEST (test_export_dimensionless) private
test000077::CPPUNIT_TEST_SUITE (test000077) private
test000077::CPPUNIT_TEST_SUITE_END () private
void test000077::setUp ()
Test the export of models with references to local parameters in expressions.
Definition at line 37 of file test000077.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000077::tearDown ()
Definition at line 45 of file test000077.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000077::test_export_dimensionless ()
Definition at line 189 of file test000077.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING6, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000077::MODEL_STRING6);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   std::string sbmlString;
   try
     {
       sbmlString = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       // fail if an uncaught exception occurs during export
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(!sbmlString.empty());
   // check if the exported SBML model has two parameters
   pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument != NULL);
   const Model* pModel = pDocument->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getListOfCompartments()->size() == 1);
   CPPUNIT_ASSERT(pModel->getListOfSpecies()->size() == 1);
   const UnitDefinition* pUDef = pModel->getUnitDefinition("time");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getListOfUnits()->size() == 1);
   const Unit* pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_DIMENSIONLESS);
   pUDef = pModel->getUnitDefinition("volume");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getListOfUnits()->size() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_DIMENSIONLESS);
   pUDef = pModel->getUnitDefinition("substance");
   CPPUNIT_ASSERT(pUDef != NULL);
   CPPUNIT_ASSERT(pUDef->getListOfUnits()->size() == 1);
   pUnit = pUDef->getUnit(0);
   CPPUNIT_ASSERT(pUnit != NULL);
   CPPUNIT_ASSERT(pUnit->getScale() == 0);
   CPPUNIT_ASSERT(fabs((pUnit->getMultiplier() - 1.0) / 1.0) < 1e-6);
   CPPUNIT_ASSERT(pUnit->getKind() == UNIT_KIND_DIMENSIONLESS);
 }
void test000077::test_import_dimensionless_1 ()
Definition at line 50 of file test000077.cpp.
References CModel::dimensionlessQuantity, CModel::dimensionlessTime, CModel::dimensionlessVolume, CCopasiDataModel::getModel(), CModel::getQuantityUnitEnum(), CModel::getTimeUnitEnum(), CModel::getVolumeUnitEnum(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000077::MODEL_STRING1));
     }
   catch (...)
     {
       // there should not be an exception
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->getModel()->getVolumeUnitEnum() == CModel::dimensionlessVolume);
   CPPUNIT_ASSERT(pDataModel->getModel()->getTimeUnitEnum() == CModel::dimensionlessTime);
   CPPUNIT_ASSERT(pDataModel->getModel()->getQuantityUnitEnum() == CModel::dimensionlessQuantity);
 }
void test000077::test_import_dimensionless_2 ()
Definition at line 70 of file test000077.cpp.
References CModel::dimensionlessQuantity, CModel::dimensionlessTime, CModel::dimensionlessVolume, CCopasiDataModel::getModel(), CModel::getQuantityUnitEnum(), CModel::getTimeUnitEnum(), CModel::getVolumeUnitEnum(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING2, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000077::MODEL_STRING2));
     }
   catch (...)
     {
       // there should not be an exception
       CPPUNIT_ASSERT(false);
     }
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   CPPUNIT_ASSERT(pDataModel->getModel()->getVolumeUnitEnum() == CModel::dimensionlessVolume);
   CPPUNIT_ASSERT(pDataModel->getModel()->getTimeUnitEnum() == CModel::dimensionlessTime);
   CPPUNIT_ASSERT(pDataModel->getModel()->getQuantityUnitEnum() == CModel::dimensionlessQuantity);
 }
void test000077::test_import_dimensionless_3 ()
Definition at line 90 of file test000077.cpp.
References CCopasiMessage::getLastMessage(), CCopasiMessage::getNumber(), CCopasiMessage::getText(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING3, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000077::MODEL_STRING3));
     }
   catch (...)
     {
       // there shouldn't be any reason for an exception
       CPPUNIT_ASSERT(false);
     }
   // check if a message MCSBML + 66 is on the message stack
   bool found = false;
   CCopasiMessage message;
   while (CCopasiMessage::size() > 0)
     {
       message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 66)
         {
           found = true;
           break;
         }
     }
   CPPUNIT_ASSERT(found == true);
   CPPUNIT_ASSERT(message.getText().find("volume") != std::string::npos);
 }
void test000077::test_import_dimensionless_4 ()
Definition at line 123 of file test000077.cpp.
References CCopasiMessage::getLastMessage(), CCopasiMessage::getNumber(), CCopasiMessage::getText(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING4, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000077::MODEL_STRING4));
     }
   catch (...)
     {
       // there shouldn't be any reason for an exception
       CPPUNIT_ASSERT(false);
     }
   // check if a message MCSBML + 66 is on the message stack
   bool found = false;
   CCopasiMessage message;
   while (CCopasiMessage::size() > 0)
     {
       message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 66)
         {
           found = true;
           break;
         }
     }
   CPPUNIT_ASSERT(found == true);
   CPPUNIT_ASSERT(message.getText().find("time") != std::string::npos);
 }
void test000077::test_import_dimensionless_5 ()
Definition at line 156 of file test000077.cpp.
References CCopasiMessage::getLastMessage(), CCopasiMessage::getNumber(), CCopasiMessage::getText(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING5, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000077::MODEL_STRING5));
     }
   catch (...)
     {
       // there shouldn't be any reason for an exception
       CPPUNIT_ASSERT(false);
     }
   // check if a message MCSBML + 66 is on the message stack
   bool found = false;
   CCopasiMessage message;
   while (CCopasiMessage::size() > 0)
     {
       message = CCopasiMessage::getLastMessage();
       if (message.getNumber() == MCSBML + 66)
         {
           found = true;
           break;
         }
     }
   CPPUNIT_ASSERT(found == true);
   CPPUNIT_ASSERT(message.getText().find("substance") != std::string::npos);
 }
Member Data Documentation
const char * test000077::MODEL_STRING1 static protected
Definition at line 51 of file test000077.h.
Referenced by test_import_dimensionless_1().
const char * test000077::MODEL_STRING2 static protected
Definition at line 52 of file test000077.h.
Referenced by test_import_dimensionless_2().
const char * test000077::MODEL_STRING3 static protected
Definition at line 53 of file test000077.h.
Referenced by test_import_dimensionless_3().
const char * test000077::MODEL_STRING4 static protected
Definition at line 54 of file test000077.h.
Referenced by test_import_dimensionless_4().
const char * test000077::MODEL_STRING5 static protected
Definition at line 55 of file test000077.h.
Referenced by test_import_dimensionless_5().
const char * test000077::MODEL_STRING6 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  "<!-- generated with COPASI 4.5.30 (Debug) (http://www.copasi.org) at 2009-01-27 14:56:07 UTC -->\n"
  "<COPASI xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.copasi.org/static/schema.xsd\" versionMajor=\"1\" versionMinor=\"0\" versionDevel=\"30\">\n"
  "  <Model key=\"Model_0\" name=\"test000077\" timeUnit=\"dimensionless\" volumeUnit=\"dimensionless\" quantityUnit=\"dimensionless\" type=\"deterministic\">\n"
  "    <Comment>\n"
  "      <html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\"font-size:13pt;font-family:Lucida Grande\">\n"
  "<p>Model to test export of dimensionless units.</p>\n"
  "</body></html>\n"
  "    </Comment>\n"
  "    <ListOfCompartments>\n"
  "      <Compartment key=\"Compartment_0\" name=\"compartment\" simulationType=\"fixed\">\n"
  "      </Compartment>\n"
  "    </ListOfCompartments>\n"
  "    <ListOfMetabolites>\n"
  "      <Metabolite key=\"Metabolite_0\" name=\"S\" simulationType=\"reactions\" compartment=\"Compartment_0\">\n"
  "      </Metabolite>\n"
  "    </ListOfMetabolites>\n"
  "    <StateTemplate>\n"
  "      <StateTemplateVariable objectReference=\"Model_0\"/>\n"
  "      <StateTemplateVariable objectReference=\"Metabolite_0\"/>\n"
  "      <StateTemplateVariable objectReference=\"Compartment_0\"/>\n"
  "    </StateTemplate>\n"
  "    <InitialState type=\"initialState\">\n"
  "      0 1 1\n"
  "    </InitialState>\n"
  "  </Model>\n"
  "</COPASI>\n"
Definition at line 56 of file test000077.h.
Referenced by test_export_dimensionless().
CCopasiDataModel * test000077::pCOPASIDATAMODEL = NULL static protected
Definition at line 50 of file test000077.h.
Referenced by setUp(), test_export_dimensionless(), test_import_dimensionless_1(), test_import_dimensionless_2(), test_import_dimensionless_3(), test_import_dimensionless_4(), and test_import_dimensionless_5().
The documentation for this class was generated from the following files:
test000077.h
test000077.cpp