COPASI API: test000104 Class Reference
test000104 Class Reference
#include <test000104.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1744 ()
Protected Attributes
CCopasiDataModel * pDataModel
Static Protected Attributes
static const char * SBML_STRING
Private Member Functions
CPPUNIT_TEST (test_bug1744)
CPPUNIT_TEST_SUITE (test000104)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 30 of file test000104.h.
Member Function Documentation
test000104::CPPUNIT_TEST (test_bug1744) private
test000104::CPPUNIT_TEST_SUITE (test000104) private
test000104::CPPUNIT_TEST_SUITE_END () private
void test000104::setUp ()
Definition at line 31 of file test000104.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pDataModel.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   pDataModel = CCopasiRootContainer::addDatamodel();
 }
void test000104::tearDown ()
Definition at line 38 of file test000104.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000104::test_bug1744 ()
Definition at line 45 of file test000104.cpp.
References CCopasiMessage::checkForMessage(), CCopasiDataModel::importSBMLFromString(), MCSBML, pDataModel, SBML_STRING, and CCopasiMessage::size().
 {
   try
     {
       bool result = pDataModel->importSBMLFromString(SBML_STRING);
       CPPUNIT_ASSERT(result == true);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("Importing the model string failed with an exception.", false);
     }
   // the actual test was if the import leads to a crash, the rest is just sugar coating
   // check the error messages
   // since there are 6 unit ids used on the model, but none of these is defined as
   // a unit definiton, we should have at least 6 warnings and one should be MCSBML + 66
   unsigned int i, iMax = CCopasiMessage::size();
   CPPUNIT_ASSERT(iMax >= 6);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 66) == true);
 }
Member Data Documentation
CCopasiDataModel* test000104::pDataModel protected
Definition at line 40 of file test000104.h.
Referenced by setUp(), and test_bug1744().
const char * test000104::SBML_STRING static protected
Initial value:
= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                      "<sbml xmlns=\"http://www.sbml.org/sbml/level3/version1/core\" xmlns:comp=\"http://www.sbml.org/sbml/level3/version1/comp/version1\" level=\"3\" version=\"1\" xmlns:html=\"http://www.w3.org/1999/xhtml\" xmlns:jigcell=\"http://www.sbml.org/2001/ns/jigcell\" xmlns:math=\"http://www.w3.org/1998/Math/MathML\">\n"
                                      "<comp:listOfModelDefinitions>\n"
                                      "</comp:listOfModelDefinitions>\n"
                                      "<model areaUnits=\"area\" extentUnits=\"substance\" id=\"Model_1\" lengthUnits=\"length\" metaid=\"COPASI1\" name=\"RootModel\" substanceUnits=\"substance\" timeUnits=\"time\" volumeUnits=\"volume\">\n"
                                      "  </model>\n"
                                      "</sbml>"
Definition at line 38 of file test000104.h.
Referenced by test_bug1744().
The documentation for this class was generated from the following files:
test000104.h
test000104.cpp