COPASI API: CQRDFTreeViewItem Class Reference
CQRDFTreeViewItem Class Reference
#include <CQRDFTreeViewItem.h>
Public Member Functions
CQRDFTreeViewItem (QTreeWidget *pParent, CQRDFTreeViewItem *pAfter=NULL)
CQRDFTreeViewItem (CQRDFTreeViewItem *pParent, CQRDFTreeViewItem *pAfter=NULL)
void setTriplet (const CRDFTriplet &triplet)
virtual ~CQRDFTreeViewItem ()
Private Attributes
CRDFTriplet mTriplet
Detailed Description
Definition at line 22 of file CQRDFTreeViewItem.h.
Constructor & Destructor Documentation
CQRDFTreeViewItem::CQRDFTreeViewItem (QTreeWidget * pParent, CQRDFTreeViewItem * pAfter = NULL)
Default Constructor
Parameters
QTreeWidget * pParent
CQRDFTreeViewItem * pAfter (default: NULL)
Definition at line 26 of file CQRDFTreeViewItem.cpp.
                                                                                      :
     QTreeWidgetItem(pParent, pAfter),
     mTriplet()
 {
   assert(pParent != NULL);
   setExpanded(true);
 }
CQRDFTreeViewItem::CQRDFTreeViewItem (CQRDFTreeViewItem * pParent, CQRDFTreeViewItem * pAfter = NULL)
Specific Constructor
Parameters
CQRDFTreeViewItem * pParent
CQRDFTreeViewItem * pAfter (default: NULL)
Definition at line 34 of file CQRDFTreeViewItem.cpp.
                                                                                            :
     QTreeWidgetItem(pParent, pAfter),
     mTriplet()
 {
   assert(pParent != NULL);
   setExpanded(true);
 }
CQRDFTreeViewItem::~CQRDFTreeViewItem () virtual
Destructor
Definition at line 42 of file CQRDFTreeViewItem.cpp.
 {}
Member Function Documentation
void CQRDFTreeViewItem::setTriplet (const CRDFTriplet & triplet)
Set the RDF triplet represented by this item
Parameters
const CRDFTriplet & triplet
Definition at line 45 of file CQRDFTreeViewItem.cpp.
References CRDFObject::BLANK_NODE, COL_OBJECT, COL_PREDICATE, COL_SUBJECT, FROM_UTF8, CRDFObject::getBlankNodeID(), CRDFLiteral::getLexicalData(), CRDFObject::getLiteral(), CRDFNode::getObject(), CRDFObject::getResource(), CRDFLiteral::getType(), CRDFObject::getType(), CRDFPredicate::getURI(), CRDFObject::LITERAL, mTriplet, CRDFLiteral::PLAIN, CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFObject::RESOURCE, and CRDFLiteral::TYPED.
Referenced by CQRDFTreeView::enterProtected().
 {
   mTriplet = triplet;
   // Set the predicate
   setText(COL_PREDICATE, FROM_UTF8(mTriplet.Predicate.getURI()));
   const CRDFObject & Object = mTriplet.pObject->getObject();
   switch (Object.getType())
     {
       case CRDFObject::LITERAL:
       {
         const CRDFLiteral & Literal = Object.getLiteral();
         switch (Literal.getType())
           {
             case CRDFLiteral::PLAIN:
             case CRDFLiteral::TYPED:
               setText(COL_OBJECT, FROM_UTF8(Literal.getLexicalData()));
               break;
           }
       }
       break;
       case CRDFObject::RESOURCE:
         setText(COL_OBJECT, FROM_UTF8(Object.getResource()));
         break;
       case CRDFObject::BLANK_NODE:
         if (mTriplet. Predicate.getURI() != "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject")
           setText(COL_SUBJECT, FROM_UTF8(Object.getBlankNodeID()));
         else
           setText(COL_OBJECT, FROM_UTF8(Object.getBlankNodeID()));
         break;
     }
 }
Member Data Documentation
CRDFTriplet CQRDFTreeViewItem::mTriplet private
The triplet represneted by this item.
Definition at line 56 of file CQRDFTreeViewItem.h.
Referenced by setTriplet().
The documentation for this class was generated from the following files:
CQRDFTreeViewItem.h
CQRDFTreeViewItem.cpp