COPASI API: CQEFMResultWidget Class Reference
CQEFMResultWidget Class Reference
#include <CQEFMResultWidget.h>
Public Member Functions
CQEFMResultWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool loadResult (const CCopasiTask *pTask)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQEFMResultWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotSave ()
Private Attributes
CQEFMNetReactionDM * mpNetReactionDM
CQSortFilterProxyModel * mpProxyModelNetReactions
CQSortFilterProxyModel * mpProxyModelReactions
CQSortFilterProxyModel * mpProxyModelSpecies
CQEFMReactionDM * mpReactionDM
CQEFMSpeciesDM * mpSpeciesDM
const CEFMTask * mpTask
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 34 of file CQEFMResultWidget.h.
Constructor & Destructor Documentation
CQEFMResultWidget::CQEFMResultWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 24 of file CQEFMResultWidget.cpp.
References COL_REACTION_NAME, COL_ROW_NUMBER, mpNetReactionDM, mpProxyModelNetReactions, mpProxyModelReactions, mpProxyModelSpecies, mpReactionDM, and mpSpeciesDM.
                                                                       :
   CopasiWidget(parent, name),
   mpTask(NULL),
   mpProxyModelReactions(NULL),
   mpReactionDM(NULL),
   mpProxyModelSpecies(NULL),
   mpSpeciesDM(NULL),
   mpProxyModelNetReactions(NULL),
   mpNetReactionDM(NULL)
 {
   setupUi(this);
   mpReactionMatrix->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   mpReactionMatrix->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpReactionMatrix->verticalHeader()->hide();
   //Create Source Data Model.
   mpReactionDM = new CQEFMReactionDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModelReactions = new CQSortFilterProxyModel();
   mpProxyModelReactions->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModelReactions->setFilterKeyColumn(COL_REACTION_NAME);
   mpProxyModelReactions->setSourceModel(mpReactionDM);
   //Set Model for the TableView
   mpReactionMatrix->setModel(NULL);
   mpReactionMatrix->setModel(mpProxyModelReactions);
   mpReactionMatrix->resizeColumnsToContents();
   mpSpeciesMatrix->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   mpSpeciesMatrix->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpSpeciesMatrix->verticalHeader()->hide();
   //Create Source Data Model.
   mpSpeciesDM = new CQEFMSpeciesDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModelSpecies = new CQSortFilterProxyModel();
   mpProxyModelSpecies->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModelSpecies->setFilterKeyColumn(COL_REACTION_NAME);
   mpProxyModelSpecies->setSourceModel(mpSpeciesDM);
   //Set Model for the TableView
   mpSpeciesMatrix->setModel(NULL);
   mpSpeciesMatrix->setModel(mpProxyModelSpecies);
   mpSpeciesMatrix->resizeColumnsToContents();
   mpNetReactions->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   mpNetReactions->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpNetReactions->verticalHeader()->hide();
   //Create Source Data Model.
   mpNetReactionDM = new CQEFMNetReactionDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModelNetReactions = new CQSortFilterProxyModel();
   mpProxyModelNetReactions->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModelNetReactions->setFilterKeyColumn(COL_REACTION_NAME);
   mpProxyModelNetReactions->setSourceModel(mpNetReactionDM);
   //Set Model for the TableView
   mpNetReactions->setModel(NULL);
   mpNetReactions->setModel(mpProxyModelNetReactions);
   mpNetReactions->resizeColumnsToContents();
 }
CQEFMResultWidget::~CQEFMResultWidget () virtual
Definition at line 94 of file CQEFMResultWidget.cpp.
References mpProxyModelNetReactions, mpProxyModelReactions, mpProxyModelSpecies, and pdelete.
 {
   pdelete(mpProxyModelNetReactions);
   pdelete(mpProxyModelReactions);
   pdelete(mpProxyModelSpecies);
 }
Member Function Documentation
bool CQEFMResultWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 138 of file CQEFMResultWidget.cpp.
 {
   return true;
 }
bool CQEFMResultWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 102 of file CQEFMResultWidget.cpp.
 {
   return true;
 }
bool CQEFMResultWidget::loadResult (const CCopasiTask * pTask) virtual
Definition at line 144 of file CQEFMResultWidget.cpp.
References CEFMTask::getFluxModes(), mpNetReactionDM, mpProxyModelNetReactions, mpProxyModelReactions, mpProxyModelSpecies, mpReactionDM, mpSpeciesDM, mpTask, pTask, CQEFMReactionDM::setTask(), CQEFMNetReactionDM::setTask(), and CQEFMSpeciesDM::setTask().
Referenced by CQEFMWidget::taskFinishedEvent(), and update().
 {
   mpTask = dynamic_cast<const CEFMTask *>(pTask);
   if (mpTask != NULL)
     {
       mpEditFluxModes->setText(QString::number(mpTask->getFluxModes().size()));
     }
   else
     {
       mpEditFluxModes->setText(QString::number(0));
     }
   bool success = true;
   success &= mpEFMListWidget->loadResult(mpTask);
   mpReactionDM->setTask(mpTask);
   mpProxyModelReactions->setSourceModel(mpReactionDM);
   //Set Model for the TableView
   mpReactionMatrix->setModel(NULL);
   mpReactionMatrix->setModel(mpProxyModelReactions);
   mpReactionMatrix->resizeColumnsToContents();
   mpSpeciesDM->setTask(mpTask);
   mpProxyModelSpecies->setSourceModel(mpSpeciesDM);
   //Set Model for the TableView
   mpSpeciesMatrix->setModel(NULL);
   mpSpeciesMatrix->setModel(mpProxyModelSpecies);
   mpSpeciesMatrix->resizeColumnsToContents();
   mpNetReactionDM->setTask(mpTask);
   mpProxyModelNetReactions->setSourceModel(mpNetReactionDM);
   //Set Model for the TableView
   mpNetReactions->setModel(NULL);
   mpNetReactions->setModel(mpProxyModelNetReactions);
   mpNetReactions->resizeColumnsToContents();
   return success;
 }
void CQEFMResultWidget::slotSave () private slot
Definition at line 190 of file CQEFMResultWidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CCopasiTask::getResult(), CopasiFileDialog::getSaveFileName(), mpTask, and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail())
     return;
   if (mpTask != NULL)
     file << mpTask->getResult();
   return;
 }
bool CQEFMResultWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 108 of file CQEFMResultWidget.cpp.
References ListViews::ADD, ListViews::DELETE, loadResult(), and ListViews::MODEL.
 {
   // We need to update the task when a new model is loaded.
   switch (objectType)
     {
       case ListViews::MODEL:
         switch (action)
           {
             case ListViews::ADD:
             case ListViews::DELETE:
               loadResult(NULL);
               break;
             default:
               break;
           }
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
CQEFMNetReactionDM* CQEFMResultWidget::mpNetReactionDM private
Definition at line 65 of file CQEFMResultWidget.h.
Referenced by CQEFMResultWidget(), and loadResult().
CQSortFilterProxyModel* CQEFMResultWidget::mpProxyModelNetReactions private
Definition at line 64 of file CQEFMResultWidget.h.
Referenced by CQEFMResultWidget(), loadResult(), and ~CQEFMResultWidget().
CQSortFilterProxyModel* CQEFMResultWidget::mpProxyModelReactions private
Definition at line 58 of file CQEFMResultWidget.h.
Referenced by CQEFMResultWidget(), loadResult(), and ~CQEFMResultWidget().
CQSortFilterProxyModel* CQEFMResultWidget::mpProxyModelSpecies private
Definition at line 61 of file CQEFMResultWidget.h.
Referenced by CQEFMResultWidget(), loadResult(), and ~CQEFMResultWidget().
CQEFMReactionDM* CQEFMResultWidget::mpReactionDM private
Definition at line 59 of file CQEFMResultWidget.h.
Referenced by CQEFMResultWidget(), and loadResult().
CQEFMSpeciesDM* CQEFMResultWidget::mpSpeciesDM private
Definition at line 62 of file CQEFMResultWidget.h.
Referenced by CQEFMResultWidget(), and loadResult().
const CEFMTask* CQEFMResultWidget::mpTask private
Definition at line 56 of file CQEFMResultWidget.h.
Referenced by loadResult(), and slotSave().
The documentation for this class was generated from the following files:
CQEFMResultWidget.h
CQEFMResultWidget.cpp