COPASI API: CCompartment Class Reference
CCompartment Class Reference
#include <CCompartment.h>
Public Member Functions
bool addMetabolite (CMetab *metabolite)
CCompartment (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CCompartment (const CCompartment &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
bool createMetabolite (const CMetab &metabolite)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual std::set< const
CCopasiObject * > getDeletedObjects () const
unsigned C_INT32 getDimensionality () const
CCopasiVectorNS< CMetab > & getMetabolites ()
const CCopasiVectorNS< CMetab > & getMetabolites () const
C_INT32 load (CReadConfig &configbuffer)
bool setDimensionality (unsigned C_INT32 dim)
virtual ~CCompartment ()
Public Member Functions inherited from CModelEntity
virtual void calculate ()
CModelEntity (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="ModelEntity", const unsigned C_INT32 &flag=CCopasiObject::Container|CCopasiObject::ValueDbl)
CModelEntity (const CModelEntity &src, const CCopasiContainer *pParent=NULL)
virtual bool compile ()
std::string getExpression () const
const CExpression * getExpressionPtr () const
CExpression * getExpressionPtr ()
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CExpression * getInitialExpressionPtr ()
const C_FLOAT64 & getInitialValue () const
CCopasiObject * getInitialValueReference () const
virtual const std::string & getKey () const
const C_FLOAT64 & getRate () const
CCopasiObject * getRateReference () const
const std::string & getSBMLId () const
const CModelEntity::Status & getStatus () const
const C_FLOAT64 & getValue () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isFixed () const
const bool & isUsed () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void refreshInitialValue ()
bool setExpression (const std::string &expression)
bool setExpressionPtr (CExpression *pExpression)
bool setInitialExpression (const std::string &expression)
bool setInitialExpressionPtr (CExpression *pExpression)
virtual void setInitialValue (const C_FLOAT64 &initialValue)
void setInitialValuePtr (C_FLOAT64 *pInitialValue)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setRate (const C_FLOAT64 &rate)
void setSBMLId (const std::string &id)
virtual void setStatus (const CModelEntity::Status &status)
void setUsed (const bool &used)
virtual void setValue (const C_FLOAT64 &value)
void setValuePtr (C_FLOAT64 *pValue)
~CModelEntity ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Protected Attributes
unsigned C_INT32 mDimensionality
Protected Attributes inherited from CModelEntity
CExpression * mpExpression
CExpression * mpInitialExpression
C_FLOAT64 * mpIValue
CCopasiObjectReference
< C_FLOAT64 > * mpIValueReference
CModel * mpModel
CCopasiObjectReference
< C_FLOAT64 > * mpRateReference
C_FLOAT64 * mpValue
CCopasiObjectReference
< C_FLOAT64 > * mpValueReference
C_FLOAT64 mRate
std::string mSBMLId
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Private Member Functions
void initObjects ()
Private Attributes
CCopasiVectorNS< CMetab > mMetabolites
Friends
std::ostream & operator<< (std::ostream &os, const CCompartment &d)
Additional Inherited Members
Public Types inherited from CModelEntity
enum Status {
FIXED = 0, ASSIGNMENT, REACTIONS, ODE,
TIME
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Static Public Attributes inherited from CModelEntity
static const std::string StatusName []
static const char * XMLStatus []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 37 of file CCompartment.h.
Constructor & Destructor Documentation
CCompartment::CCompartment (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor.
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 36 of file CCompartment.cpp.
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CModelEntity::FIXED, CCopasiRootContainer::getKeyFactory(), initObjects(), CAnnotation::mKey, CModelEntity::mpIValue, and CModelEntity::setStatus().
                                                             :
   CModelEntity(name, pParent, "Compartment"),
   mMetabolites("Metabolites", this),
   mDimensionality(3)
 {
   initObjects();
   mKey = CCopasiRootContainer::getKeyFactory()->add("Compartment", this);
   setStatus(FIXED);
   *mpIValue = 1.0;
   CONSTRUCTOR_TRACE;
 }
CCompartment::CCompartment (const CCompartment & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CCompartment & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 53 of file CCompartment.cpp.
References CKeyFactory::add(), CONSTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), initObjects(), and CAnnotation::mKey.
                                                             :
   CModelEntity(src, pParent),
   mMetabolites(src.mMetabolites, this),
   mDimensionality(src.mDimensionality)
 {
   mKey = CCopasiRootContainer::getKeyFactory()->add("Compartment", this);
   CONSTRUCTOR_TRACE;
   initObjects();
 }
CCompartment::~CCompartment () virtual
Destructor. The destructor does nothing.
Definition at line 64 of file CCompartment.cpp.
References DESTRUCTOR_TRACE, CCopasiRootContainer::getKeyFactory(), CAnnotation::mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
bool CCompartment::addMetabolite (CMetab * metabolite)
Adds a metabolite to the compartment. Only the concentration is taken from the metabolite, the number of particles is calculated according to the volume of the compartment
Parameters
CMetab * metabolite;
Returns
bool success
Definition at line 175 of file CCompartment.cpp.
References CCopasiVectorN< CType >::add(), CCopasiObject::getCN(), CCopasiObject::getObjectParent(), CRenameHandler::handle(), mMetabolites, and CCopasiObject::smpRenameHandler.
Referenced by createMetabolite(), CModelExpansion::replaceInMetab(), and CCopasiXMLParser::MetaboliteElement::start().
 {
   if (!pMetabolite) return false;
   std::string oldCN = pMetabolite->getCN();
   bool success = mMetabolites.add(pMetabolite, true);
   //if a metabolite is added to a compartment successfully the CN of
   //the metabolite is changed. This needs to be handled similarly to a
   //rename.
   if (success && smpRenameHandler && getObjectParent())
     {
       std::string newCN = pMetabolite->getCN();
       smpRenameHandler->handle(oldCN, newCN);
     }
   return success;
 }
void CCompartment::cleanup ()
Cleanup
Definition at line 123 of file CCompartment.cpp.
References CCopasiVector< T >::cleanup(), and mMetabolites.
 {mMetabolites.cleanup();}
bool CCompartment::createMetabolite (const CMetab & metabolite)
Adds a metabolite to the compartment. Only the concentration is taken from the metabolite, the number of particles is calculated according to the volume of the compartment
Parameters
const CMetab & metabolite;
Returns
bool success
Definition at line 165 of file CCompartment.cpp.
References addMetabolite().
 {
   CMetab * pMetab = new CMetab(metabolite);
   if (addMetabolite(pMetab)) return true;
   delete pMetab;
   return false;
 }
std::string CCompartment::getChildObjectUnits (const CCopasiObject * pObject) const virtual
Retrieve the units of the child object.
Returns
std::string units
Reimplemented from CCopasiContainer.
Definition at line 71 of file CCompartment.cpp.
References CModel::getAreaUnitsDisplayString(), CModel::getLengthUnitsDisplayString(), CModel::getTimeUnitsDisplayString(), CModel::getVolumeUnitsDisplayString(), mDimensionality, CModelEntity::mpIValueReference, CModelEntity::mpModel, CModelEntity::mpRateReference, and CModelEntity::mpValueReference.
Referenced by CMetab::getChildObjectUnits(), and CModelParameter::getUnit().
 {
   if (mpModel == NULL) return "";
   if (pObject == mpValueReference ||
       pObject == mpIValueReference)
     {
       switch (mDimensionality)
         {
           case 1:
             return mpModel->getLengthUnitsDisplayString();
             break;
           case 2:
             return mpModel->getAreaUnitsDisplayString();
             break;
           case 3:
             return mpModel->getVolumeUnitsDisplayString();
             break;
           default:
             return "";
             break;
         }
     }
   else if (pObject == mpRateReference)
     {
       std::string Unit = getChildObjectUnits(mpValueReference);
       std::string TimeUnit = mpModel->getTimeUnitsDisplayString();
       if (Unit == "")
         {
           if (TimeUnit == "")
             {
               return "";
             }
           return "1/" + TimeUnit;
         }
       if (TimeUnit == "")
         {
           return Unit;
         }
       return Unit + "/" + TimeUnit;
     }
   return "";
 }
std::set< const CCopasiObject * > CCompartment::getDeletedObjects () const virtual
Retrieve the list of deleted numeric child objects;
Returns
std::set< const CCopasiObject * > deletedObjects
Reimplemented from CModelEntity.
Definition at line 125 of file CCompartment.cpp.
References CModelEntity::getDeletedObjects().
Referenced by CModel::appendDependentModelObjects(), CModel::removeCompartment(), CQCompartmentDM::removeRows(), and CQCompartment::slotBtnDelete().
 {
   std::set< const CCopasiObject * > Deleted = CModelEntity::getDeletedObjects();
   // We must not add the metabolites as CModel::appendDependentMetabolites does that.
   return Deleted;
 }
unsigned C_INT32 CCompartment::getDimensionality () const
Get the dimensionality of the compartment
Definition at line 204 of file CCompartment.cpp.
References mDimensionality.
Referenced by CModelAdd::addCompartments(), CSBMLExporter::createCompartment(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createKineticLaw(), CSBMLExporter::createRule(), CModelExpansion::duplicateCompartment(), CSBMLExporter::exportEventAssignments(), SBMLImporter::importEvent(), SBMLImporter::importInitialAssignments(), SBMLImporter::importRuleForModelEntity(), CQCompartment::load(), CSBMLExporter::replaceSpeciesReferences(), CQCompartment::save(), and CCopasiXML::saveModel().
 {
   return mDimensionality;
 }
CCopasiVectorNS< CMetab > & CCompartment::getMetabolites ()
Retrieve the vector of contained metabolites
Returns
CCopasiVectorNS < CMetab > & metabolites
Definition at line 157 of file CCompartment.cpp.
References mMetabolites.
Referenced by CQCompartment::copy(), SBMLImporter::createCMetabFromSpecies(), CQSelectionWizardPage::fillTree(), CMetabNameInterface::getMetabolite(), CQCompartment::loadMetaboliteTable(), moveObject(), CModelExpansion::replaceInMetab(), CQExpandModelData::slotCompartmentActivated(), and CQCompartment::slotMetaboliteTableCurrentChanged().
 {return mMetabolites;}
const CCopasiVectorNS< CMetab > & CCompartment::getMetabolites () const
Retrieve the vector of contained metabolites
Returns
const CCopasiVectorNS < CMetab > & metabolites
Definition at line 160 of file CCompartment.cpp.
References mMetabolites.
 {return mMetabolites;}
void CCompartment::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 209 of file CCompartment.cpp.
References CModelEntity::mpIValueReference, CModelEntity::mpValueReference, and CCopasiObject::setObjectName().
Referenced by CCompartment().
 {
   mpIValueReference->setObjectName("InitialVolume");
   mpValueReference->setObjectName("Volume");
 }
C_INT32 CCompartment::load (CReadConfig & configbuffer)
Loads an object with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
pconfigbuffer reference to a CReadConfig object.
Returns
mFail
See Also
mFail
Definition at line 134 of file CCompartment.cpp.
References C_FLOAT64, C_INT32, CReadConfig::getVariable(), CReadConfig::SEARCH, CModelEntity::setInitialValue(), and CCopasiObject::setObjectName().
 {
   C_INT32 Fail = 0;
   std::string tmp;
   if ((Fail = configbuffer.getVariable("Compartment", "string",
                                        (void *) & tmp,
                                        CReadConfig::SEARCH)))
     return Fail;
   setObjectName(tmp);
   C_FLOAT64 tmpdbl;
   if ((Fail = configbuffer.getVariable("Volume", "C_FLOAT64",
                                        (void *) & tmpdbl)))
     return Fail;
   setInitialValue(tmpdbl);
   return Fail;
 }
bool CCompartment::setDimensionality (unsigned C_INT32 dim)
Set the dimensionality of the compartment. May be 0, 1, 2, or 3. If the value is not valid it will be ignored and the return value will be false
Definition at line 195 of file CCompartment.cpp.
References mDimensionality.
Referenced by CModelAdd::addCompartments(), SBMLImporter::createCCompartmentFromCompartment(), CModelExpansion::duplicateCompartment(), and CQCompartment::save().
 {
   if (dim > 3)
     return false;
   mDimensionality = dim;
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCompartment & d) friend
Friend declaration for ostream operator <<
Parameters
std::ostream & os
const CCompartment & d
Returns
std::ostream & os
Definition at line 215 of file CCompartment.cpp.
 {
   os << "++++CCompartment: " << d.getObjectName() << " mValue " << *d.mpValue;
   os << "    CCompartment.mMetabolites " << std::endl << d.mMetabolites;
   os << "----CCompartment " << std::endl;
   return os;
 }
Member Data Documentation
unsigned C_INT32 CCompartment::mDimensionality protected
The dimensionality of the compartment. Can be 0, 1, 2, or 3
Definition at line 155 of file CCompartment.h.
Referenced by getChildObjectUnits(), getDimensionality(), and setDimensionality().
CCopasiVectorNS< CMetab > CCompartment::mMetabolites private
Metabolites located in the compartment. 0..* <{CMetab}>
Definition at line 45 of file CCompartment.h.
Referenced by addMetabolite(), cleanup(), getMetabolites(), and operator<<().
The documentation for this class was generated from the following files:
CCompartment.h
CCompartment.cpp