COPASI API: CAnnotation Class Reference
CAnnotation Class Reference
#include <CAnnotation.h>
Public Types
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Public Member Functions
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
virtual const std::string & getKey () const
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Static Public Member Functions
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Protected Attributes
std::string mKey
Static Private Member Functions
static bool isValidXML (const std::string &xml)
Private Attributes
std::string mMiriamAnnotation
std::string mNotes
UnsupportedAnnotation mUnsupportedAnnotations
std::string mXMLId
Detailed Description
Definition at line 14 of file CAnnotation.h.
Member Typedef Documentation
typedef std::map< std::string, std::string > CAnnotation::UnsupportedAnnotation
Definition at line 17 of file CAnnotation.h.
Constructor & Destructor Documentation
CAnnotation::CAnnotation ()
Default constructor
Definition at line 81 of file CAnnotation.cpp.
                         :
   mKey(""),
   mNotes(),
   mMiriamAnnotation(),
   mXMLId(),
   mUnsupportedAnnotations()
 {}
CAnnotation::CAnnotation (const CAnnotation & src)
Copy constructor
Parameters
const CAnnotation & src
Definition at line 89 of file CAnnotation.cpp.
                                                :
   mKey(""),
   mNotes(src.mNotes),
   mMiriamAnnotation(src.mMiriamAnnotation),
   mXMLId(src.mXMLId),
   mUnsupportedAnnotations(src.mUnsupportedAnnotations)
 {}
CAnnotation::~CAnnotation () virtual
Destructor
Definition at line 97 of file CAnnotation.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
bool CAnnotation::addUnsupportedAnnotation (const std::string & name, const std::string & xml)
Add an unsupported annotation
Parameters
const std::string & name
const std::string & xml
Returns
bool success
Definition at line 211 of file CAnnotation.cpp.
References CCopasiMessage::ERROR, isValidXML(), MCAnnotation, and mUnsupportedAnnotations.
Referenced by SBMLImporter::importNotes().
 {
   // The name must not be empty
   if (name == "")
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 7);
       return false;
     }
   // The name must be unique
   if (mUnsupportedAnnotations.find(name) != mUnsupportedAnnotations.end())
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 6, name.c_str());
       return false;
     }
   // We need to check whether we have valid XML.
   if (!isValidXML(xml))
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 5, name.c_str());
       return false;
     }
   mUnsupportedAnnotations[name] = xml;
   return true;
 }
CAnnotation * CAnnotation::castObject (CCopasiObject * pObject) static
Definition at line 32 of file CAnnotation.cpp.
Referenced by CMIRIAMInfo::load(), CQNotes::load(), CMIRIAMInfo::save(), CQNotes::save(), and CQMiriamWidget::showEvent().
 {
   CModelEntity * pEntity = NULL;
   CEvent * pEvent = NULL;
   CReaction * pReaction = NULL;
   CFunction * pFunction = NULL;
   CModelParameterSet * pParameterSet = NULL;
   if ((pEntity = dynamic_cast< CModelEntity * >(pObject)) != NULL)
     return static_cast< CAnnotation * >(pEntity);
   if ((pEvent = dynamic_cast< CEvent * >(pObject)) != NULL)
     return static_cast< CAnnotation * >(pEvent);
   if ((pReaction = dynamic_cast< CReaction * >(pObject)) != NULL)
     return static_cast< CAnnotation * >(pReaction);
   if ((pParameterSet = dynamic_cast< CModelParameterSet * >(pObject)) != NULL)
     return static_cast< CAnnotation * >(pParameterSet);
   if ((pFunction = dynamic_cast< CFunction * >(pObject)) != NULL)
     return static_cast< CAnnotation * >(pFunction);
   return NULL;
 }
const CAnnotation * CAnnotation::castObject (const CCopasiObject * pObject) static
Definition at line 59 of file CAnnotation.cpp.
 {
   const CModelEntity * pEntity = NULL;
   const CEvent * pEvent = NULL;
   const CReaction * pReaction = NULL;
   const CFunction * pFunction = NULL;
   if ((pEntity = dynamic_cast< const CModelEntity * >(pObject)) != NULL)
     return static_cast< const CAnnotation * >(pEntity);
   if ((pEvent = dynamic_cast< const CEvent * >(pObject)) != NULL)
     return static_cast< const CAnnotation * >(pEvent);
   if ((pReaction = dynamic_cast< const CReaction * >(pObject)) != NULL)
     return static_cast< const CAnnotation * >(pReaction);
   if ((pFunction = dynamic_cast< const CFunction * >(pObject)) != NULL)
     return static_cast< const CAnnotation * >(pFunction);
   return NULL;
 }
const std::string & CAnnotation::getKey () const virtual
Retrieve the key
Returns
std::string key
Reimplemented in CModel, CEvent, CReaction, CModelEntity, CFunction, and CModelParameterSet.
Definition at line 103 of file CAnnotation.cpp.
References mKey.
Referenced by CFunction::getKey(), CModelEntity::getKey(), CReaction::getKey(), CEvent::getKey(), and CMIRIAMInfo::save().
 {
   return mKey;
 }
const std::string & CAnnotation::getMiriamAnnotation () const
Retrieve the RDF/XML representation of the MIRIAM annotation
Returns
const std::string & miriamAnnotation
Definition at line 117 of file CAnnotation.cpp.
References mMiriamAnnotation.
Referenced by CEvent::CEvent(), CFunction::CFunction(), CModelEntity::CModelEntity(), CReaction::CReaction(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CQRDFTreeView::enterProtected(), CMIRIAMInfo::load(), CCopasiXML::saveAnnotation(), CQMiriamWidget::showEvent(), test000092::test_miriam_export_8(), test000092::test_miriam_export_9(), test000092::test_miriam_import_1(), and CSBMLExporter::updateMIRIAMAnnotation().
 {return mMiriamAnnotation;}
const std::string & CAnnotation::getNotes () const
Retrieve the XHTML notes
Returns
const std::string & notes
Definition at line 124 of file CAnnotation.cpp.
References mNotes.
Referenced by CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CModel::initObjects(), CQNotes::load(), CQNotes::save(), CCopasiXML::saveAnnotation(), and CSBMLExporter::setSBMLNotes().
 {
   return mNotes;
 }
CAnnotation::UnsupportedAnnotation & CAnnotation::getUnsupportedAnnotations ()
Retrieve the unsupported annotations in xml format.
Returns
std::map< std::string, std::string > & unsupportedAnnotations
Definition at line 201 of file CAnnotation.cpp.
References mUnsupportedAnnotations.
Referenced by CCopasiXMLParser::ReactionElement::end(), CCopasiXMLParser::EventElement::end(), CCopasiXMLParser::ModelElement::end(), CCopasiXMLParser::FunctionElement::end(), CCopasiXML::saveAnnotation(), and CSBMLExporter::setSBMLNotes().
 {
   return mUnsupportedAnnotations;
 }
const CAnnotation::UnsupportedAnnotation & CAnnotation::getUnsupportedAnnotations () const
Definition at line 206 of file CAnnotation.cpp.
References mUnsupportedAnnotations.
 {
   return mUnsupportedAnnotations;
 }
bool CAnnotation::isValidXML (const std::string & xml) static private
Definition at line 275 of file CAnnotation.cpp.
References BUFFER_SIZE, CCopasiMessage::getLastMessage(), CExpatTemplate< CType >::parse(), and CCopasiMessage::size().
Referenced by addUnsupportedAnnotation(), and replaceUnsupportedAnnotation().
 {
   std::istringstream XML;
   XML.str(xml);
   XML.imbue(std::locale::classic());
   XML.precision(16);
   bool done = false;
   CVersion Version;
   CCopasiXMLParser Parser(Version);
   size_t Size = CCopasiMessage::size();
 #define BUFFER_SIZE 0xfffe
   char * pBuffer = new char[BUFFER_SIZE + 1];
   while (!done)
     {
       XML.get(pBuffer, BUFFER_SIZE, 0);
       if (XML.eof()) done = true;
       if (XML.fail() && !done)
         {
           done = true;
           return false;
         }
       if (!Parser.parse(pBuffer, -1, done))
         {
           done = true;
           return false;
         }
     }
   delete [] pBuffer;
 #undef BUFFER_SIZE
   // Remove error messages created by setExpression as this may fail
   // due to incomplete model specification at this time.
   while (CCopasiMessage::size() > Size)
     CCopasiMessage::getLastMessage();
   return true;
 }
bool CAnnotation::operator== (const CAnnotation & rhs) const
Comparison operator
Parameters
const CAnnotation & rhs
Returns
bool equal
Definition at line 129 of file CAnnotation.cpp.
References CRDFUtilities::fixLocalFileAboutReference(), mMiriamAnnotation, mNotes, and mXMLId.
 {
   if (mNotes != rhs.mNotes)
     return false;
   std::string Annotation = mMiriamAnnotation;
   CRDFUtilities::fixLocalFileAboutReference(Annotation, rhs.mXMLId, mXMLId);
   // We need to ignore white spaces when comparing.
   std::string::const_iterator it = Annotation.begin();
   std::string::const_iterator end = Annotation.end();
   std::string::const_iterator itRhs = rhs.mMiriamAnnotation.begin();
   std::string::const_iterator endRhs = rhs.mMiriamAnnotation.end();
   while (it != end && itRhs != endRhs)
     {
       if (*it == * itRhs)
         {
           ++it;
           ++itRhs;
           continue;
         }
       // Advance past white spaces
       while (it != end)
         {
           if (*it == '\x20' || *it == '\x09' || *it == '\x0d' || *it == '\x0a')
             {
               ++it;
               continue;
             }
           break;
         }
       // Advance past white spaces
       while (itRhs != endRhs)
         {
           if (*itRhs == '\x20' || *itRhs == '\x09' || *itRhs == '\x0d' || *itRhs == '\x0a')
             {
               ++itRhs;
               continue;
             }
           break;
         }
       if (it == end && itRhs == endRhs)
         {
           return true;
         }
       if (it == end || itRhs == endRhs)
         {
           return false;
         }
       if (*it != *itRhs)
         {
           return false;
         }
       ++it;
       ++itRhs;
     }
   return true;
 }
bool CAnnotation::removeUnsupportedAnnotation (const std::string & name)
Remove an unsupported annotation
Parameters
const std::string & name
Returns
bool success
Definition at line 260 of file CAnnotation.cpp.
References mUnsupportedAnnotations.
 {
   UnsupportedAnnotation::iterator it = mUnsupportedAnnotations.find(name);
   if (it == mUnsupportedAnnotations.end())
     {
       return false;
     }
   mUnsupportedAnnotations.erase(it);
   return true;
 }
bool CAnnotation::replaceUnsupportedAnnotation (const std::string & name, const std::string & xml)
Replace an unsupported annotation
Parameters
const std::string & name
const std::string & xml
Returns
bool success
Definition at line 239 of file CAnnotation.cpp.
References CCopasiMessage::ERROR, isValidXML(), MCAnnotation, and mUnsupportedAnnotations.
 {
   // We need to check whether we have valid XML.
   if (!isValidXML(xml))
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 5, name.c_str());
       return false;
     }
   // The annotation must exist
   if (mUnsupportedAnnotations.find(name) == mUnsupportedAnnotations.end())
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 8, name.c_str());
       return false;
     }
   mUnsupportedAnnotations[name] = xml;
   return true;
 }
void CAnnotation::setMiriamAnnotation (const std::string & miriamAnnotation, const std::string & newId, const std::string & oldId)
Set the RDF/XML representation of the MIRIAM annotation
Parameters
const std::string & miriamAnnotation
const std::string & newId
const std::string & oldId
Definition at line 108 of file CAnnotation.cpp.
References CRDFUtilities::fixLocalFileAboutReference(), mMiriamAnnotation, and mXMLId.
Referenced by CEvent::CEvent(), CFunction::CFunction(), CModelEntity::CModelEntity(), CReaction::CReaction(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::ModelParameterSetElement::end(), CCopasiXMLParser::ReactionElement::end(), CCopasiXMLParser::EventElement::end(), CCopasiXMLParser::ModelElement::end(), CCopasiXMLParser::FunctionElement::end(), SBMLImporter::importMIRIAM(), CMIRIAMInfo::save(), CQMiriamWidget::showEvent(), and test000092::test_miriam_export_7().
 {
   mMiriamAnnotation = miriamAnnotation;
   mXMLId = newId;
   CRDFUtilities::fixLocalFileAboutReference(mMiriamAnnotation, newId, oldId);
 }
void CAnnotation::setNotes (const std::string & notes)
Set the XHTML Notes
Parameters
const std::string & notes
Definition at line 120 of file CAnnotation.cpp.
References mNotes.
Referenced by CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::ReactionElement::end(), CCopasiXMLParser::EventElement::end(), CCopasiXMLParser::ModelElement::end(), CCopasiXMLParser::FunctionElement::end(), SBMLImporter::importNotes(), CModel::load(), and CQNotes::save().
 {
   mNotes = notes;
 }
Member Data Documentation
std::string CAnnotation::mKey protected
Key of the model entity. It is stored here, but constructed in the derived classes.
Definition at line 119 of file CAnnotation.h.
Referenced by CCompartment::CCompartment(), CEvent::CEvent(), CFunction::CFunction(), CMetab::CMetab(), CModelEntity::CModelEntity(), CMetab::compile(), CReaction::CReaction(), getKey(), CModel::getKey(), CModel::initObjects(), ~CAnnotation(), CCompartment::~CCompartment(), CEvent::~CEvent(), CFunction::~CFunction(), CMetab::~CMetab(), CModel::~CModel(), and CReaction::~CReaction().
std::string CAnnotation::mMiriamAnnotation private
MIRIAM compliant annotation in RDF/XML format
Definition at line 130 of file CAnnotation.h.
Referenced by getMiriamAnnotation(), operator==(), and setMiriamAnnotation().
std::string CAnnotation::mNotes private
Notes in XHTML format
Definition at line 125 of file CAnnotation.h.
Referenced by getNotes(), operator==(), and setNotes().
UnsupportedAnnotation CAnnotation::mUnsupportedAnnotations private
The annotations which are not supported by COPASI. Note, the name is enforced to be unique.
Definition at line 141 of file CAnnotation.h.
Referenced by addUnsupportedAnnotation(), getUnsupportedAnnotations(), removeUnsupportedAnnotation(), and replaceUnsupportedAnnotation().
std::string CAnnotation::mXMLId private
The XMLId used in the about statement
Definition at line 135 of file CAnnotation.h.
Referenced by operator==(), and setMiriamAnnotation().
The documentation for this class was generated from the following files:
CAnnotation.h
CAnnotation.cpp