COPASI API: CLNAResultSubwidget Class Reference
CLNAResultSubwidget Class Reference
#include <CLNAResultSubwidget.h>
Public Member Functions
virtual void clear ()
CLNAResultSubwidget (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
virtual void loadAll (const CLNAMethod *lnaMethod)
virtual void loadBMatrixReduced (const CLNAMethod *lnaMethod)
virtual void loadCovarianceMatrix (const CLNAMethod *lnaMethod)
virtual void loadCovarianceMatrixReduced (const CLNAMethod *lnaMethod)
~CLNAResultSubwidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
Protected Slots
virtual void slotSave ()
virtual void slotScaled ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual void init ()
Protected Member Functions inherited from CopasiWidget
virtual bool enterProtected ()
Private Attributes
const CLNAMethod * mLNAMethod
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 33 of file CLNAResultSubwidget.h.
Constructor & Destructor Documentation
CLNAResultSubwidget::CLNAResultSubwidget (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 38 of file CLNAResultSubwidget.cpp.
References init().
   : CopasiWidget(parent, name, fl)
 {
   setupUi(this);
   init();
 }
CLNAResultSubwidget::~CLNAResultSubwidget ()
Definition at line 49 of file CLNAResultSubwidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CLNAResultSubwidget::clear () virtual
Definition at line 243 of file CLNAResultSubwidget.cpp.
Referenced by init(), and loadAll().
 {
   mTopLabel->setText("No result available, please execute the LNA task.");
   mpArrayCovarianceMatrix->setArrayAnnotation(NULL);
   mpArrayCovarianceMatrixReduced->setArrayAnnotation(NULL);
   mpArrayBMatrixReduced->setArrayAnnotation(NULL);
   return;
 }
void CLNAResultSubwidget::init () protected virtual
Definition at line 54 of file CLNAResultSubwidget.cpp.
References clear(), and mLNAMethod.
Referenced by CLNAResultSubwidget().
 {
   /*
     mSaveButton->setEnabled(false);
     mSaveButton->hide();
   */
   mLNAMethod = NULL;
   clear();
 }
void CLNAResultSubwidget::loadAll (const CLNAMethod * lnaMethod) virtual
Definition at line 65 of file CLNAResultSubwidget.cpp.
References CLNAMethod::allNeg, clear(), CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, CLNAMethod::getEigenValueStatus(), CLNAMethod::getModel(), CLNAMethod::getSteadyStateStatus(), loadBMatrixReduced(), loadCovarianceMatrix(), loadCovarianceMatrixReduced(), mLNAMethod, CLNAMethod::nonNegEigenvaluesExist, and CSteadyStateMethod::notFound.
Referenced by CLNAResultWidget::loadFromBackend(), slotScaled(), and CLNAResultWidget::update().
 {
   mLNAMethod = lnaMethod;
   if (lnaMethod)
     {
       if (!lnaMethod->getModel())
         {
           clear();
           return;
         }
       if ((lnaMethod->getSteadyStateStatus() == CSteadyStateMethod::found) && (lnaMethod->getEigenValueStatus() == CLNAMethod::allNeg))
         {
           mTopLabel->setText("Steady State found.");
           this->loadCovarianceMatrix(lnaMethod);
           this->loadCovarianceMatrixReduced(lnaMethod);
           this->loadBMatrixReduced(lnaMethod);
           mTabWidget->setTabEnabled(0, true);
           mTabWidget->setTabEnabled(1, true);
           mTabWidget->setTabEnabled(2, true);
         }
       else if ((lnaMethod->getSteadyStateStatus() == CSteadyStateMethod::foundEquilibrium) && (lnaMethod->getEigenValueStatus() == CLNAMethod::allNeg))
         {
           mTopLabel->setText("Equilibrium steady state.");
           this->loadCovarianceMatrix(lnaMethod);
           this->loadCovarianceMatrixReduced(lnaMethod);
           this->loadBMatrixReduced(lnaMethod);
           mTabWidget->setTabEnabled(0, true);
           mTabWidget->setTabEnabled(1, true);
           mTabWidget->setTabEnabled(2, true);
         }
       else
         {
           if (lnaMethod->getSteadyStateStatus() == CSteadyStateMethod::foundNegative)
             {
               mTopLabel->setText("Invalid steady state (negative concentrations). No LNA calculated!");
             }
           else if (lnaMethod->getSteadyStateStatus() == CSteadyStateMethod::notFound)
             {
               mTopLabel->setText("No steady state found. No LNA calculated!");
             }
           else if (lnaMethod->getEigenValueStatus() == CLNAMethod::nonNegEigenvaluesExist)
             {
               mTopLabel->setText("The reduced system has non-negative Eigen values! No LNA calculated!");
             }
           /*
                 this->loadCovarianceMatrix(lnaMethod);
                 this->loadCovarianceMatrixReduced(lnaMethod);
                 this->loadBMatrixReduced(lnaMethod);
           */
           mpArrayCovarianceMatrix->setArrayAnnotation(NULL);
           mpArrayCovarianceMatrixReduced->setArrayAnnotation(NULL);
           mpArrayBMatrixReduced->setArrayAnnotation(NULL);
         }
     }
   else
     {
       clear();
       return;
     }
 }
void CLNAResultSubwidget::loadBMatrixReduced (const CLNAMethod * lnaMethod) virtual
Definition at line 178 of file CLNAResultSubwidget.cpp.
References CLNAMethod::getScaledBMatrixReducedAnn(), and CLNAMethod::getUnscaledBMatrixReducedAnn().
Referenced by loadAll().
 {
   const CArrayAnnotation * bMatrixReducedAnn;
   if (mComboScale->currentIndex() == 0)
     {
       bMatrixReducedAnn = lnaMethod->getScaledBMatrixReducedAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayBMatrixReduced->setColorCoding(tcs);
       mpArrayBMatrixReduced->setColorScalingAutomatic(true);
     }
   else
     {
       bMatrixReducedAnn = lnaMethod->getUnscaledBMatrixReducedAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayBMatrixReduced->setColorCoding(tcs);
       mpArrayBMatrixReduced->setColorScalingAutomatic(true);
     }
   mpArrayBMatrixReduced->setArrayAnnotation(bMatrixReducedAnn);
 }
void CLNAResultSubwidget::loadCovarianceMatrix (const CLNAMethod * lnaMethod) virtual
Definition at line 130 of file CLNAResultSubwidget.cpp.
References CLNAMethod::getScaledCovarianceMatrixAnn(), and CLNAMethod::getUnscaledCovarianceMatrixAnn().
Referenced by loadAll().
 {
   const CArrayAnnotation * covarianceMatrixAnn;
   if (mComboScale->currentIndex() == 0)
     {
       covarianceMatrixAnn = lnaMethod->getScaledCovarianceMatrixAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayCovarianceMatrix->setColorCoding(tcs);
       mpArrayCovarianceMatrix->setColorScalingAutomatic(true);
     }
   else
     {
       covarianceMatrixAnn = lnaMethod->getUnscaledCovarianceMatrixAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayCovarianceMatrix->setColorCoding(tcs);
       mpArrayCovarianceMatrix->setColorScalingAutomatic(true);
     }
   mpArrayCovarianceMatrix->setArrayAnnotation(covarianceMatrixAnn);
 }
void CLNAResultSubwidget::loadCovarianceMatrixReduced (const CLNAMethod * lnaMethod) virtual
Definition at line 154 of file CLNAResultSubwidget.cpp.
References CLNAMethod::getScaledCovarianceMatrixReducedAnn(), and CLNAMethod::getUnscaledCovarianceMatrixReducedAnn().
Referenced by loadAll().
 {
   const CArrayAnnotation * covarianceMatrixReducedAnn;
   if (mComboScale->currentIndex() == 0)
     {
       covarianceMatrixReducedAnn = lnaMethod->getScaledCovarianceMatrixReducedAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayCovarianceMatrixReduced->setColorCoding(tcs);
       mpArrayCovarianceMatrixReduced->setColorScalingAutomatic(true);
     }
   else
     {
       covarianceMatrixReducedAnn = lnaMethod->getUnscaledCovarianceMatrixReducedAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayCovarianceMatrixReduced->setColorCoding(tcs);
       mpArrayCovarianceMatrixReduced->setColorScalingAutomatic(true);
     }
   mpArrayCovarianceMatrixReduced->setArrayAnnotation(covarianceMatrixReducedAnn);
 }
void CLNAResultSubwidget::slotSave () protected virtual slot
Definition at line 202 of file CLNAResultSubwidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getResult(), CopasiFileDialog::getSaveFileName(), and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail())
     return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiTask* mpTask =
     dynamic_cast<CLNATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Linear Noise Approximation"]);
   if (mpTask != NULL)
     file << mpTask->getResult();
 //    mpTask->printResult(file);
   return;
 }
void CLNAResultSubwidget::slotScaled () protected virtual slot
Definition at line 238 of file CLNAResultSubwidget.cpp.
References loadAll(), and mLNAMethod.
 {
   loadAll(mLNAMethod);
 }
Member Data Documentation
const CLNAMethod* CLNAResultSubwidget::mLNAMethod private
Definition at line 57 of file CLNAResultSubwidget.h.
Referenced by init(), loadAll(), and slotScaled().
The documentation for this class was generated from the following files:
CLNAResultSubwidget.h
CLNAResultSubwidget.cpp