COPASI API: CMathMLToTeX Class Reference
CMathMLToTeX Class Reference
#include <CMathMLToTeX.h>
Public Member Functions
CMathMLToTeX ()
~CMathMLToTeX ()
Static Public Member Functions
static void convert (QString &text)
convert to TeX
static void mNode (QString &text)
normal equation node
static void mtableNode (QString &text)
converting <mtable> ... </mtable>
static void replaceLogicOperators (QString &text)
replace logic operators (eg. <=, <, >=, >, and, or)
static void replaceMathOperators (QString &text)
replace mathematical operators (eg. inf, log)
static void replaceOtherOperators (QString &text)
replace other operators (eg. .)
static void replaceTrigoOperators (QString &text)
replace trigonometrical operators (eg. inf, log)
Detailed Description
Definition at line 21 of file CMathMLToTeX.h.
Constructor & Destructor Documentation
CMathMLToTeX::CMathMLToTeX () inline
Definition at line 24 of file CMathMLToTeX.h.
 {};
CMathMLToTeX::~CMathMLToTeX () inline
Definition at line 25 of file CMathMLToTeX.h.
 {};
Member Function Documentation
void CMathMLToTeX::convert (QString & text) static
convert to TeX
Definition at line 148 of file CMathMLToTeX.cpp.
References mNode(), mtableNode(), replaceLogicOperators(), replaceMathOperators(), replaceOtherOperators(), and replaceTrigoOperators().
Referenced by CQExpressionMmlStackedWidget::saveTeX(), and CQDifferentialEquations::saveTeX().
 {
   replaceOtherOperators(text);
   replaceLogicOperators(text);
   replaceMathOperators(text);
   replaceTrigoOperators(text);
   if (text.contains("mtable"))
     mtableNode(text);
   else
     {
       if (text.count("<mtable>") > 1)
         {
           text = "The MathML contains <mtable> more than one. Needs more handling.";
           return;
         }
       mNode(text);
     }
 }
void CMathMLToTeX::mNode (QString & text) static
normal equation node
Definition at line 170 of file CMathMLToTeX.cpp.
References CStructureParser::getTeX().
Referenced by convert().
 {
   CStructureParser xmlParser(0);
   QXmlSimpleReader xmlReader;
   xmlReader.setContentHandler(&xmlParser);
   QXmlInputSource xmlSource;
   xmlSource.setData(text);
   xmlReader.parse(xmlSource);
   text = xmlParser.getTeX();
 }
void CMathMLToTeX::mtableNode (QString & text) static
converting <mtable> ... </mtable>
Definition at line 186 of file CMathMLToTeX.cpp.
References CStructureParser::getTeX().
Referenced by convert().
 {
   int sumCols = 0;
   if (text.contains("<mtr>"))
     {
       int posA = text.indexOf("<mtr>");
       int posB = text.indexOf("</mtr>");
       QString mtrText = text.mid(posA, posB - posA + 6);
       sumCols = mtrText.count("<mtd");
     }
   CStructureParser xmlParser(sumCols);
   QXmlSimpleReader xmlReader;
   xmlReader.setContentHandler(&xmlParser);
   QXmlInputSource xmlSource;
   xmlSource.setData(text);
   xmlReader.parse(xmlSource);
   text = xmlParser.getTeX();
 }
void CMathMLToTeX::replaceLogicOperators (QString & text) static
replace logic operators (eg. <=, <, >=, >, and, or)
Definition at line 29 of file CMathMLToTeX.cpp.
Referenced by convert().
 {
   text.replace("&gt;=", "\\ge");
   text.replace("&gt;", ">");
   text.replace("&lt;=", "\\le");
   text.replace("&lt;", "\\lt");
   text.replace("&NotEqual;", "\\ne");
   text.replace("and", "\\wedge");
   text.replace(" or ", "\\vee");
 }
void CMathMLToTeX::replaceMathOperators (QString & text) static
replace mathematical operators (eg. inf, log)
Definition at line 42 of file CMathMLToTeX.cpp.
Referenced by convert().
 {
   text.replace("log", "\\log");
   text.replace("ln", "\\ln");
   text.replace("&infin;", "\\infty");
   text.replace("&pi;", "\\pi");
   text.replace("%", "\\%");
 }
void CMathMLToTeX::replaceOtherOperators (QString & text) static
replace other operators (eg. .)
Definition at line 23 of file CMathMLToTeX.cpp.
Referenced by convert().
 {
   text.replace("&CenterDot;", "\\cdot");
 }
void CMathMLToTeX::replaceTrigoOperators (QString & text) static
replace trigonometrical operators (eg. inf, log)
Definition at line 52 of file CMathMLToTeX.cpp.
Referenced by convert().
 {
   // sin, sinh, asin, arcsinh
   text.replace("arcsinh", "arsoh");
   text.replace("arcsin", "arcso");
   text.replace("sinh", "sooh");
   if (text.length() == 3)  // exactly 'sin' word
     text.replace("sin", "\\sin");
   text.replace("sooh", "sinh");
   text.replace("sinh", "\\sinh");
   text.replace("arcso", "arcsin");
   text.replace("arcsin", "\\arcsin");
   text.replace("arsoh", "arcsinh");
   // cos, cosh, acos, arccosh
   text.replace("arccosh", "arcoh");
   text.replace("arccos", "arcce");
   text.replace("cosh", "cooh");
   if (text.length() == 3)  // exactly 'cos' word
     text.replace("cos", "\\cos");
   text.replace("cooh", "cosh");
   text.replace("cosh", "\\cosh");
   text.replace("arcce", "arccos");
   text.replace("arccos", "\\arccos");
   text.replace("arcoh", "arccosh");
   // tan, tanh, atan, arctanh
   text.replace("arctanh", "artoh");
   text.replace("arctan", "arcto");
   text.replace("tanh", "tooh");
   if (text.length() == 3)  // exactly 'tan' word
     text.replace("tan", "\\tan");
   text.replace("tooh", "tanh");
   text.replace("tanh", "\\tanh");
   text.replace("arcto", "arctan");
   text.replace("arctan", "\\arctan");
   text.replace("artoh", "arctanh");
   // sec, sech, arcsec, arcsech
   text.replace("arcsech", "arsoh");
   text.replace("arcsec", "arcso");
   text.replace("sech", "sooh");
   if (text.length() == 3)  // exactly 'sec' word
     text.replace("sec", "\\sec");
   text.replace("sooh", "sech");
   text.replace("arcso", "arcsec");
   text.replace("arsoh", "arcsech");
   // csc, csch, arccsc, arccsch
   text.replace("arccsch", "arcoh");
   text.replace("arccsc", "arcce");
   text.replace("csch", "cooh");
   if (text.length() == 3)  // exactly 'csc' word
     text.replace("csc", "\\csc");
   text.replace("cooh", "csch");
   text.replace("arcce", "arccsc");
   text.replace("arcoh", "arccsch");
   // cot, coth, arccot, arccoth
   text.replace("arccoth", "arctoh");
   text.replace("arccot", "arcto");
   text.replace("coth", "tooh");
   if (text.length() == 3)  // exactly 'cot' word
     text.replace("cot", "\\cot");
   text.replace("tooh", "coth");
   text.replace("coth", "\\coth");
   text.replace("arcto", "arccot");
   text.replace("arctoh", "arccoth");
 }
The documentation for this class was generated from the following files:
CMathMLToTeX.h
CMathMLToTeX.cpp