COPASI API: CLRenderCubicBezier Class Reference
CLRenderCubicBezier Class Reference
#include <CLRenderCubicBezier.h>
Public Member Functions
const CLRelAbsVector & basePoint1_X () const
CLRelAbsVector & basePoint1_X ()
const CLRelAbsVector & basePoint1_Y () const
CLRelAbsVector & basePoint1_Y ()
const CLRelAbsVector & basePoint1_Z () const
CLRelAbsVector & basePoint1_Z ()
const CLRelAbsVector & basePoint2_X () const
CLRelAbsVector & basePoint2_X ()
const CLRelAbsVector & basePoint2_Y () const
CLRelAbsVector & basePoint2_Y ()
const CLRelAbsVector & basePoint2_Z () const
CLRelAbsVector & basePoint2_Z ()
CLRenderCubicBezier ()
CLRenderCubicBezier (const CLRenderCubicBezier &orig)
CLRenderCubicBezier (const CLRelAbsVector &bp1_x, const CLRelAbsVector &bp1_y, const CLRelAbsVector &bp1_z, const CLRelAbsVector &bp2_x, const CLRelAbsVector &bp2_y, const CLRelAbsVector &bp2_z, const CLRelAbsVector &end_x, const CLRelAbsVector &end_y, const CLRelAbsVector &end_z)
CLRenderCubicBezier (const RenderCubicBezier &source)
virtual CLRenderCubicBezier & operator= (const CLRenderCubicBezier &orig)
void setBasePoint1 (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setBasePoint1_X (const CLRelAbsVector &v)
void setBasePoint1_Y (const CLRelAbsVector &v)
void setBasePoint1_Z (const CLRelAbsVector &v)
void setBasePoint2 (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setBasePoint2_X (const CLRelAbsVector &v)
void setBasePoint2_Y (const CLRelAbsVector &v)
void setBasePoint2_Z (const CLRelAbsVector &v)
virtual RenderPoint * toSBML (unsigned int level, unsigned int version) const
virtual ~CLRenderCubicBezier ()
Public Member Functions inherited from CLRenderPoint
virtual void addSBMLAttributes (RenderPoint *pPoint) const
CLRenderPoint ()
CLRenderPoint (const CLRenderPoint &orig)
CLRenderPoint (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
CLRenderPoint (const RenderPoint &source)
const CLRelAbsVector & getXOffset () const
CLRelAbsVector & getXOffset ()
const CLRelAbsVector & getYOffset () const
CLRelAbsVector & getYOffset ()
const CLRelAbsVector & getZOffset () const
CLRelAbsVector & getZOffset ()
void initDefaults ()
CLRenderPoint & operator= (const CLRenderPoint &orig)
bool operator== (const CLRenderPoint &left)
void setOffsets (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setX (const CLRelAbsVector &x)
void setXOffset (const CLRelAbsVector &x)
void setY (const CLRelAbsVector &y)
void setYOffset (const CLRelAbsVector &y)
void setZ (const CLRelAbsVector &z)
void setZOffset (const CLRelAbsVector &z)
const CLRelAbsVector & x () const
CLRelAbsVector & x ()
const CLRelAbsVector & y () const
CLRelAbsVector & y ()
const CLRelAbsVector & z () const
CLRelAbsVector & z ()
virtual ~CLRenderPoint ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
CLRelAbsVector mBasePoint1_X
CLRelAbsVector mBasePoint1_Y
CLRelAbsVector mBasePoint1_Z
CLRelAbsVector mBasePoint2_X
CLRelAbsVector mBasePoint2_Y
CLRelAbsVector mBasePoint2_Z
Protected Attributes inherited from CLRenderPoint
CLRelAbsVector mXOffset
CLRelAbsVector mYOffset
CLRelAbsVector mZOffset
Protected Attributes inherited from CLBase
std::string mTag
Detailed Description
Definition at line 24 of file CLRenderCubicBezier.h.
Constructor & Destructor Documentation
CLRenderCubicBezier::CLRenderCubicBezier ()
Creates a CubicBezier and returns the pointer.
Creates a CLRenderCubicBezier and returns the pointer.
Definition at line 16 of file CLRenderCubicBezier.cpp.
References mBasePoint1_X, mBasePoint1_Y, mBasePoint1_Z, mBasePoint2_X, mBasePoint2_Y, mBasePoint2_Z, CLRenderPoint::mXOffset, CLRenderPoint::mYOffset, and CLRenderPoint::mZOffset.
                                         : CLRenderPoint()
 {
   mBasePoint1_X = mXOffset;
   mBasePoint1_Y = mYOffset;
   mBasePoint1_Z = mZOffset;
   mBasePoint2_X = mXOffset;
   mBasePoint2_Y = mYOffset;
   mBasePoint2_Z = mZOffset;
 }
CLRenderCubicBezier::CLRenderCubicBezier (const CLRenderCubicBezier & orig)
Copy constructor.
Definition at line 42 of file CLRenderCubicBezier.cpp.
                                                                        :
   CLRenderPoint(orig),
   mBasePoint1_X(orig.mBasePoint1_X),
   mBasePoint1_Y(orig.mBasePoint1_Y),
   mBasePoint1_Z(orig.mBasePoint1_Z),
   mBasePoint2_X(orig.mBasePoint2_X),
   mBasePoint2_Y(orig.mBasePoint2_Y),
   mBasePoint2_Z(orig.mBasePoint2_Z)
 {
 }
CLRenderCubicBezier::CLRenderCubicBezier (const CLRelAbsVector & bp1_x, const CLRelAbsVector & bp1_y, const CLRelAbsVector & bp1_z, const CLRelAbsVector & bp2_x, const CLRelAbsVector & bp2_y, const CLRelAbsVector & bp2_z, const CLRelAbsVector & end_x, const CLRelAbsVector & end_y, const CLRelAbsVector & end_z)
Creates a CubicBezier with the given points and returns the pointer.
Definition at line 29 of file CLRenderCubicBezier.cpp.
                                                                                                                                                                                                                                                                                                            : CLRenderPoint(end_x, end_y, end_z),
   mBasePoint1_X(bp1_x),
   mBasePoint1_Y(bp1_y),
   mBasePoint1_Z(bp1_z),
   mBasePoint2_X(bp2_x),
   mBasePoint2_Y(bp2_y),
   mBasePoint2_Z(bp2_z)
 {
 }
CLRenderCubicBezier::CLRenderCubicBezier (const RenderCubicBezier & source)
Constructor to generate object from the corresponding SBML object.
Definition at line 56 of file CLRenderCubicBezier.cpp.
                                                                        :
   CLRenderPoint(source),
   mBasePoint1_X(source.basePoint1_X()),
   mBasePoint1_Y(source.basePoint1_Y()),
   mBasePoint1_Z(source.basePoint1_Z()),
   mBasePoint2_X(source.basePoint2_X()),
   mBasePoint2_Y(source.basePoint2_Y()),
   mBasePoint2_Z(source.basePoint2_Z())
 {
 }
CLRenderCubicBezier::~CLRenderCubicBezier () virtual
Destructor.
Definition at line 89 of file CLRenderCubicBezier.cpp.
 {
 }
Member Function Documentation
const CLRelAbsVector & CLRenderCubicBezier::basePoint1_X () const
Returns the x value of the first base point of the curve (the one closer to the starting point).
Definition at line 97 of file CLRenderCubicBezier.cpp.
References mBasePoint1_X.
Referenced by addToPath(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), and CCopasiXML::saveRenderPoint().
 {
   return this->mBasePoint1_X;
 }
CLRelAbsVector & CLRenderCubicBezier::basePoint1_X ()
Returns the x value of the first base point of the curve (the one closer to the starting point).
Definition at line 151 of file CLRenderCubicBezier.cpp.
References mBasePoint1_X.
 {
   return this->mBasePoint1_X;
 }
const CLRelAbsVector & CLRenderCubicBezier::basePoint1_Y () const
Returns the y value of the first base point of the curve (the one closer to the starting point).
Definition at line 106 of file CLRenderCubicBezier.cpp.
References mBasePoint1_Y.
Referenced by addToPath(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), and CCopasiXML::saveRenderPoint().
 {
   return this->mBasePoint1_Y;
 }
CLRelAbsVector & CLRenderCubicBezier::basePoint1_Y ()
Returns the y value of the first base point of the curve (the one closer to the starting point).
Definition at line 160 of file CLRenderCubicBezier.cpp.
References mBasePoint1_Y.
 {
   return this->mBasePoint1_Y;
 }
const CLRelAbsVector & CLRenderCubicBezier::basePoint1_Z () const
Returns the z value of the first base point of the curve (the one closer to the starting point).
Definition at line 115 of file CLRenderCubicBezier.cpp.
References mBasePoint1_Z.
Referenced by CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), and CCopasiXML::saveRenderPoint().
 {
   return this->mBasePoint1_Z;
 }
CLRelAbsVector & CLRenderCubicBezier::basePoint1_Z ()
Returns the z value of the first base point of the curve (the one closer to the starting point).
Definition at line 169 of file CLRenderCubicBezier.cpp.
References mBasePoint1_Z.
 {
   return this->mBasePoint1_Z;
 }
const CLRelAbsVector & CLRenderCubicBezier::basePoint2_X () const
Returns the x value of the second base point of the curve (the one closer to the end point).
Definition at line 124 of file CLRenderCubicBezier.cpp.
References mBasePoint2_X.
Referenced by addToPath(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), and CCopasiXML::saveRenderPoint().
 {
   return this->mBasePoint2_X;
 }
CLRelAbsVector & CLRenderCubicBezier::basePoint2_X ()
Returns the x value of the second base point of the curve (the one closer to the end point).
Definition at line 178 of file CLRenderCubicBezier.cpp.
References mBasePoint2_X.
 {
   return this->mBasePoint2_X;
 }
const CLRelAbsVector & CLRenderCubicBezier::basePoint2_Y () const
Returns the y value of the second base point of the curve (the one closer to the end point).
Definition at line 133 of file CLRenderCubicBezier.cpp.
References mBasePoint2_Y.
Referenced by addToPath(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), and CCopasiXML::saveRenderPoint().
 {
   return this->mBasePoint2_Y;
 }
CLRelAbsVector & CLRenderCubicBezier::basePoint2_Y ()
Returns the y value of the second base point of the curve (the one closer to the end point).
Definition at line 187 of file CLRenderCubicBezier.cpp.
References mBasePoint2_Y.
 {
   return this->mBasePoint2_Y;
 }
const CLRelAbsVector & CLRenderCubicBezier::basePoint2_Z () const
Returns the z value of the second base point of the curve (the one closer to the end point).
Definition at line 142 of file CLRenderCubicBezier.cpp.
References mBasePoint2_Z.
Referenced by CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), and CCopasiXML::saveRenderPoint().
 {
   return this->mBasePoint2_Z;
 }
CLRelAbsVector & CLRenderCubicBezier::basePoint2_Z ()
Returns the z value of the second base point of the curve (the one closer to the end point).
Definition at line 196 of file CLRenderCubicBezier.cpp.
References mBasePoint2_Z.
 {
   return this->mBasePoint2_Z;
 }
CLRenderCubicBezier & CLRenderCubicBezier::operator= (const CLRenderCubicBezier & orig) virtual
Assignment operator
Assignment operator.
Definition at line 70 of file CLRenderCubicBezier.cpp.
References mBasePoint1_X, mBasePoint1_Y, mBasePoint1_Z, mBasePoint2_X, mBasePoint2_Y, mBasePoint2_Z, and CLRenderPoint::operator=().
 {
   if (&orig != this)
     {
       this->CLRenderPoint::operator=(orig);
       mBasePoint1_X = orig.mBasePoint1_X;
       mBasePoint1_Y = orig.mBasePoint1_Y;
       mBasePoint1_Z = orig.mBasePoint1_Z;
       mBasePoint2_X = orig.mBasePoint2_X;
       mBasePoint2_Y = orig.mBasePoint2_Y;
       mBasePoint2_Z = orig.mBasePoint2_Z;
     }
   return *this;
 }
void CLRenderCubicBezier::setBasePoint1 (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Sets the first basepoint to the given values.
Definition at line 258 of file CLRenderCubicBezier.cpp.
References mBasePoint1_X, mBasePoint1_Y, mBasePoint1_Z, CLRenderPoint::x(), CLRenderPoint::y(), and CLRenderPoint::z().
 {
   this->mBasePoint1_X = x;
   this->mBasePoint1_Y = y;
   this->mBasePoint1_Z = z;
 }
void CLRenderCubicBezier::setBasePoint1_X (const CLRelAbsVector & v)
Sets the x value of the first base point of the curve (the one closer to the starting point).
Definition at line 205 of file CLRenderCubicBezier.cpp.
References mBasePoint1_X.
 {
   this->mBasePoint1_X = v;;
 }
void CLRenderCubicBezier::setBasePoint1_Y (const CLRelAbsVector & v)
Sets the y value of the first base point of the curve (the one closer to the starting point).
Definition at line 214 of file CLRenderCubicBezier.cpp.
References mBasePoint1_Y.
 {
   this->mBasePoint1_Y = v;
 }
void CLRenderCubicBezier::setBasePoint1_Z (const CLRelAbsVector & v)
Sets the z value of the first base point of the curve (the one closer to the starting point).
Definition at line 223 of file CLRenderCubicBezier.cpp.
References mBasePoint1_Z.
 {
   this->mBasePoint1_Z = v;
 }
void CLRenderCubicBezier::setBasePoint2 (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Sets the second basepoint to the given values.
Definition at line 268 of file CLRenderCubicBezier.cpp.
References mBasePoint2_X, mBasePoint2_Y, mBasePoint2_Z, CLRenderPoint::x(), CLRenderPoint::y(), and CLRenderPoint::z().
 {
   this->mBasePoint2_X = x;
   this->mBasePoint2_Y = y;
   this->mBasePoint2_Z = z;
 }
void CLRenderCubicBezier::setBasePoint2_X (const CLRelAbsVector & v)
Sets the x value of the second base point of the curve (the one closer to the end point).
Definition at line 232 of file CLRenderCubicBezier.cpp.
References mBasePoint2_X.
 {
   this->mBasePoint2_X = v;
 }
void CLRenderCubicBezier::setBasePoint2_Y (const CLRelAbsVector & v)
Sets the y value of the second base point of the curve (the one closer to the end point).
Definition at line 241 of file CLRenderCubicBezier.cpp.
References mBasePoint2_Y.
 {
   this->mBasePoint2_Y = v;
 }
void CLRenderCubicBezier::setBasePoint2_Z (const CLRelAbsVector & v)
Sets the z value of the second base point of the curve (the one closer to the end point).
Definition at line 250 of file CLRenderCubicBezier.cpp.
References mBasePoint2_Z.
 {
   this->mBasePoint2_Z = v;
 }
RenderPoint * CLRenderCubicBezier::toSBML (unsigned int level, unsigned int version) const virtual
Converts this object to the corresponding SBML object.
Reimplemented from CLRenderPoint.
Definition at line 278 of file CLRenderCubicBezier.cpp.
References CLRenderPoint::addSBMLAttributes(), mBasePoint1_X, mBasePoint1_Y, mBasePoint1_Z, mBasePoint2_X, mBasePoint2_Y, mBasePoint2_Z, and CLRelAbsVector::toSBML().
 {
   RenderCubicBezier* pCB = new RenderCubicBezier(level, version);
   this->addSBMLAttributes(pCB);
   RelAbsVector* pV1 = this->mBasePoint1_X.toSBML();
   RelAbsVector* pV2 = this->mBasePoint1_Y.toSBML();
   RelAbsVector* pV3 = this->mBasePoint1_Z.toSBML();
   pCB->setBasePoint1(*pV1, *pV2, *pV3);
   delete pV1;
   delete pV2;
   delete pV3;
   pV1 = this->mBasePoint2_X.toSBML();
   pV2 = this->mBasePoint2_Y.toSBML();
   pV3 = this->mBasePoint2_Z.toSBML();
   pCB->setBasePoint2(*pV1, *pV2, *pV3);
   delete pV1;
   delete pV2;
   delete pV3;
   return pCB;
 }
Member Data Documentation
CLRelAbsVector CLRenderCubicBezier::mBasePoint1_X protected
Definition at line 27 of file CLRenderCubicBezier.h.
Referenced by basePoint1_X(), CLRenderCubicBezier(), operator=(), setBasePoint1(), setBasePoint1_X(), and toSBML().
CLRelAbsVector CLRenderCubicBezier::mBasePoint1_Y protected
Definition at line 28 of file CLRenderCubicBezier.h.
Referenced by basePoint1_Y(), CLRenderCubicBezier(), operator=(), setBasePoint1(), setBasePoint1_Y(), and toSBML().
CLRelAbsVector CLRenderCubicBezier::mBasePoint1_Z protected
Definition at line 29 of file CLRenderCubicBezier.h.
Referenced by basePoint1_Z(), CLRenderCubicBezier(), operator=(), setBasePoint1(), setBasePoint1_Z(), and toSBML().
CLRelAbsVector CLRenderCubicBezier::mBasePoint2_X protected
Definition at line 30 of file CLRenderCubicBezier.h.
Referenced by basePoint2_X(), CLRenderCubicBezier(), operator=(), setBasePoint2(), setBasePoint2_X(), and toSBML().
CLRelAbsVector CLRenderCubicBezier::mBasePoint2_Y protected
Definition at line 31 of file CLRenderCubicBezier.h.
Referenced by basePoint2_Y(), CLRenderCubicBezier(), operator=(), setBasePoint2(), setBasePoint2_Y(), and toSBML().
CLRelAbsVector CLRenderCubicBezier::mBasePoint2_Z protected
Definition at line 32 of file CLRenderCubicBezier.h.
Referenced by basePoint2_Z(), CLRenderCubicBezier(), operator=(), setBasePoint2(), setBasePoint2_Z(), and toSBML().
The documentation for this class was generated from the following files:
CLRenderCubicBezier.h
CLRenderCubicBezier.cpp