COPASI API: CEvaluationParser_yacc.cpp File Reference
CEvaluationParser_yacc.cpp File Reference
#include "copasi.h"
#include "CEvaluationNode.h"
#include "CEvaluationLexer.h"
Classes
union yyalloc
Macros
#define YY_(Msgid) Msgid
#define YY_CEVALUATIONPARSER_CEVALUATIONPARSER_TAB_HPP_INCLUDED
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_INITIAL_VALUE(Value) /* Nothing. */
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YY_NULL 0
#define YY_REDUCE_PRINT(Rule)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YYABORT goto yyabortlab
#define YYACCEPT goto yyacceptlab
#define YYBACKUP(Token, Value)
#define YYBISON 1
#define YYBISON_VERSION "2.6.5"
#define yychar CEvaluationParserchar
#define yyclearin (yychar = YYEMPTY)
#define YYCOPY(Dst, Src, Count)
#define YYCOPY_NEEDED 1
#define yydebug CEvaluationParserdebug
#define YYDPRINTF(Args)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYERRCODE 256
#define yyerrok (yyerrstatus = 0)
#define yyerror CEvaluationParsererror
#define yyerror(__str)
#define YYERROR goto yyerrorlab
#define YYERROR_VERBOSE 0
#define YYFAIL goto yyerrlab
#define YYFINAL 29
#define YYFREE free
#define YYID(N) (N)
#define YYINITDEPTH 200
#define YYLAST 409
#define YYLEX yylex ()
#define yylval CEvaluationParserlval
#define yylval mpNode
#define YYMALLOC malloc
#define YYMAXDEPTH 10000
#define YYMAXUTOK 284
#define yynerrs CEvaluationParsernerrs
#define YYNNTS 8
#define YYNRULES 58
#define YYNSTATES 129
#define YYNTOKENS 30
#define YYPACT_NINF -48
#define yypact_value_is_default(Yystate) (!!((Yystate) == (-48)))
#define yyparse yyparse
#define yyparse CEvaluationParserBase::yyparse
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
#define YYPULL 1
#define YYPURE 0
#define YYPUSH 0
#define YYRECOVERING() (!!yyerrstatus)
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YYSIZE_T unsigned int
#define YYSKELETON_NAME "yacc.c"
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYSTACK_BYTES(N)
#define YYSTACK_FREE YYFREE
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYSTYPE CEvaluationNode *
#define YYTABLE_NINF -47
#define yytable_value_is_error(Yytable_value) YYID (0)
#define YYTERROR 1
#define YYTOKENTYPE
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYUNDEFTOK 2
#define YYUSE(E) ((void) (E))
Typedefs
typedef short int yytype_int16
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef unsigned char yytype_uint8
Enumerations
enum yytokentype {
TOKEN_NUMBER = 258, TOKEN_VARIABLE = 259, TOKEN_CALL = 260, TOKEN_FUNCTION = 261,
TOKEN_FUNCTION_2 = 262, TOKEN_SIGN = 263, TOKEN_OPERATOR_POWER = 264, TOKEN_OPERATOR_MULTIPLY = 265,
TOKEN_OPERATOR_MODULUS = 266, TOKEN_OPERATOR_PLUS = 267, TOKEN_LOGICAL_CHOICE = 268, TOKEN_LOGICAL_VALUE = 269,
TOKEN_LOGICAL_NOT = 270, TOKEN_LOGICAL_OR = 271, TOKEN_LOGICAL_XOR = 272, TOKEN_LOGICAL_AND = 273,
TOKEN_LOGICAL_EQ = 274, TOKEN_LOGICAL_NE = 275, TOKEN_LOGICAL_GT = 276, TOKEN_LOGICAL_GE = 277,
TOKEN_LOGICAL_LT = 278, TOKEN_LOGICAL_LE = 279, TOKEN_STRUCTURE_OPEN = 280, TOKEN_STRUCTURE_VECTOR_OPEN = 281,
TOKEN_STRUCTURE_COMMA = 282, TOKEN_STRUCTURE_CLOSE = 283, TOKEN_STRUCTURE_VECTOR_CLOSE = 284, TOKEN_NUMBER = 258,
TOKEN_MULTIPLY = 259, TOKEN_PLUS = 260, TOKEN_NAME = 261, TOKEN_BEGIN_PRODUCTS = 262,
TOKEN_BEGIN_MODIFIERS = 263, TOKEN_BEGIN_COMPARTMENT = 264, TOKEN_END_COMPARTMENT = 265
}
Functions
if (!yymsg) yymsg
void setBooleanRequired (CEvaluationNode *pNode, const bool &booleanRequired)
switch (yytype)
() void (yyvaluep))
static void yydestruct (yymsg, yytype, yyvaluep) const char *yymsg
Variables
int CEvaluationParserchar
CEvaluationNode * CEvaluationParserlval
int CEvaluationParsernerrs
CEvaluationNode * mpNode
static const yytype_int8 yycheck []
static const yytype_uint8 yydefact []
static const yytype_int8 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int8 yypgoto []
static const yytype_uint8 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint8 yystos []
static const yytype_int16 yytable []
static const yytype_uint8 yytranslate []
int yytype
CEvaluationNode ** yyvaluep
Macro Definition Documentation
#define YY_ (Msgid) Msgid
Definition at line 265 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YY_CEVALUATIONPARSER_CEVALUATIONPARSER_TAB_HPP_INCLUDED
Definition at line 138 of file CEvaluationParser_yacc.cpp.
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
Definition at line 1290 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
Definition at line 1291 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YY_INITIAL_VALUE (Value) /* Nothing. */
Definition at line 1294 of file CEvaluationParser_yacc.cpp.
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
Definition at line 805 of file CEvaluationParser_yacc.cpp.
#define YY_NULL 0
Definition at line 123 of file CEvaluationParser_yacc.cpp.
#define YY_REDUCE_PRINT (Rule)
Definition at line 982 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YY_STACK_PRINT (Bottom, Top)
Definition at line 981 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Definition at line 980 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYABORT goto yyabortlab
Definition at line 762 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYACCEPT goto yyacceptlab
Definition at line 761 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYBACKUP (Token, Value)
Value:
do                                                              \
    if (yychar == YYEMPTY)                                        \
      {\
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {\
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;              \
      }               \
  while (YYID (0))
Definition at line 782 of file CEvaluationParser_yacc.cpp.
#define YYBISON 1
Definition at line 58 of file CEvaluationParser_yacc.cpp.
#define YYBISON_VERSION "2.6.5"
Definition at line 61 of file CEvaluationParser_yacc.cpp.
#define yychar CEvaluationParserchar
Definition at line 79 of file CEvaluationParser_yacc.cpp.
#define yyclearin (yychar = YYEMPTY)
Definition at line 757 of file CEvaluationParser_yacc.cpp.
#define YYCOPY (Dst, Src, Count)
Value:
do                                        \
    {\
      YYSIZE_T yyi;                         \
      for (yyi = 0; yyi < (Count); yyi++)   \
        (Dst)[yyi] = (Src)[yyi];            \
    }                                       \
  while (YYID (0))
Definition at line 412 of file CEvaluationParser_yacc.cpp.
#define YYCOPY_NEEDED 1
Definition at line 384 of file CEvaluationParser_yacc.cpp.
#define yydebug CEvaluationParserdebug
Definition at line 80 of file CEvaluationParser_yacc.cpp.
#define YYDPRINTF (Args)
Definition at line 979 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYEMPTY (-2)
Definition at line 758 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYEOF 0
Definition at line 759 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYERRCODE 256
Definition at line 801 of file CEvaluationParser_yacc.cpp.
#define yyerrok (yyerrstatus = 0)
Definition at line 756 of file CEvaluationParser_yacc.cpp.
#define yyerror CEvaluationParsererror
Definition at line 97 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define yyerror (__str)
Value:
if (yychar != YYERRCODE) correctErrorPosition(); \
  CCopasiMessage(CCopasiMessage::ERROR, MCFunction + 1, mPosition)
Definition at line 97 of file CEvaluationParser_yacc.cpp.
#define YYERROR goto yyerrorlab
Definition at line 763 of file CEvaluationParser_yacc.cpp.
#define YYERROR_VERBOSE 0
Definition at line 132 of file CEvaluationParser_yacc.cpp.
#define YYFAIL goto yyerrlab
Definition at line 772 of file CEvaluationParser_yacc.cpp.
#define YYFINAL 29
Definition at line 425 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYFREE free
Definition at line 355 of file CEvaluationParser_yacc.cpp.
#define YYID (N) (N)
Definition at line 278 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYINITDEPTH 200
Definition at line 987 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYLAST 409
Definition at line 427 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYLEX yylex ()
Definition at line 812 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define yylval CEvaluationParserlval
Definition at line 92 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define yylval mpNode
Definition at line 92 of file CEvaluationParser_yacc.cpp.
#define YYMALLOC malloc
Definition at line 348 of file CEvaluationParser_yacc.cpp.
#define YYMAXDEPTH 10000
Definition at line 998 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYMAXUTOK 284
Definition at line 440 of file CEvaluationParser_yacc.cpp.
#define yynerrs CEvaluationParsernerrs
Definition at line 81 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYNNTS 8
Definition at line 432 of file CEvaluationParser_yacc.cpp.
#define YYNRULES 58
Definition at line 434 of file CEvaluationParser_yacc.cpp.
#define YYNSTATES 129
Definition at line 436 of file CEvaluationParser_yacc.cpp.
#define YYNTOKENS 30
Definition at line 430 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYPACT_NINF -48
Definition at line 613 of file CEvaluationParser_yacc.cpp.
#define yypact_value_is_default (Yystate) (!!((Yystate) == (-48)))
Definition at line 686 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define yyparse yyparse
Definition at line 106 of file CEvaluationParser_yacc.cpp.
#define yyparse CEvaluationParserBase::yyparse
Definition at line 106 of file CEvaluationParser_yacc.cpp.
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
Referenced by CEvaluationParserBase::yyparse().
#define YYPULL 1
Definition at line 73 of file CEvaluationParser_yacc.cpp.
#define YYPURE 0
Definition at line 67 of file CEvaluationParser_yacc.cpp.
#define YYPUSH 0
Definition at line 70 of file CEvaluationParser_yacc.cpp.
#define YYRECOVERING () (!!yyerrstatus)
Definition at line 780 of file CEvaluationParser_yacc.cpp.
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
Definition at line 255 of file CEvaluationParser_yacc.cpp.
#define YYSIZE_T unsigned int
Definition at line 251 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYSKELETON_NAME "yacc.c"
Definition at line 64 of file CEvaluationParser_yacc.cpp.
#define YYSTACK_ALLOC YYMALLOC
Definition at line 334 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Definition at line 337 of file CEvaluationParser_yacc.cpp.
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
   + YYSTACK_GAP_MAXIMUM)
Definition at line 380 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYSTACK_FREE YYFREE
Definition at line 335 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
Definition at line 376 of file CEvaluationParser_yacc.cpp.
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                  \
    {\
      YYSIZE_T yynewbytes;            \
      YYCOPY (&yyptr->Stack_alloc, Stack, yysize);      \
      Stack = &yyptr->Stack_alloc;          \
      yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
      yyptr += yynewbytes / sizeof (*yyptr);        \
    }                 \
  while (YYID (0))
Definition at line 391 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYSTYPE CEvaluationNode *
Definition at line 87 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYTABLE_NINF -47
Definition at line 640 of file CEvaluationParser_yacc.cpp.
#define yytable_value_is_error (Yytable_value) YYID (0)
Definition at line 689 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYTERROR 1
Definition at line 800 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYTOKENTYPE
Definition at line 149 of file CEvaluationParser_yacc.cpp.
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Definition at line 442 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationParserBase::yyparse().
#define YYUNDEFTOK 2
Definition at line 439 of file CEvaluationParser_yacc.cpp.
#define YYUSE (E) ((void) (E))
Definition at line 271 of file CEvaluationParser_yacc.cpp.
Typedef Documentation
typedef short int yytype_int16
Definition at line 238 of file CEvaluationParser_yacc.cpp.
typedef short int yytype_int8
Definition at line 226 of file CEvaluationParser_yacc.cpp.
typedef unsigned short int yytype_uint16
Definition at line 232 of file CEvaluationParser_yacc.cpp.
typedef unsigned char yytype_uint8
Definition at line 217 of file CEvaluationParser_yacc.cpp.
Enumeration Type Documentation
enum yytokentype
Enumerator
TOKEN_NUMBER
TOKEN_VARIABLE
TOKEN_CALL
TOKEN_FUNCTION
TOKEN_FUNCTION_2
TOKEN_SIGN
TOKEN_OPERATOR_POWER
TOKEN_OPERATOR_MULTIPLY
TOKEN_OPERATOR_MODULUS
TOKEN_OPERATOR_PLUS
TOKEN_LOGICAL_CHOICE
TOKEN_LOGICAL_VALUE
TOKEN_LOGICAL_NOT
TOKEN_LOGICAL_OR
TOKEN_LOGICAL_XOR
TOKEN_LOGICAL_AND
TOKEN_LOGICAL_EQ
TOKEN_LOGICAL_NE
TOKEN_LOGICAL_GT
TOKEN_LOGICAL_GE
TOKEN_LOGICAL_LT
TOKEN_LOGICAL_LE
TOKEN_STRUCTURE_OPEN
TOKEN_STRUCTURE_VECTOR_OPEN
TOKEN_STRUCTURE_COMMA
TOKEN_STRUCTURE_CLOSE
TOKEN_STRUCTURE_VECTOR_CLOSE
TOKEN_NUMBER
TOKEN_MULTIPLY
TOKEN_PLUS
TOKEN_NAME
TOKEN_BEGIN_PRODUCTS
TOKEN_BEGIN_MODIFIERS
TOKEN_BEGIN_COMPARTMENT
TOKEN_END_COMPARTMENT
Definition at line 152 of file CEvaluationParser_yacc.cpp.
 {
   TOKEN_NUMBER = 258,
   TOKEN_VARIABLE = 259,
   TOKEN_CALL = 260,
   TOKEN_FUNCTION = 261,
   TOKEN_FUNCTION_2 = 262,
   TOKEN_SIGN = 263,
   TOKEN_OPERATOR_POWER = 264,
   TOKEN_OPERATOR_MULTIPLY = 265,
   TOKEN_OPERATOR_MODULUS = 266,
   TOKEN_OPERATOR_PLUS = 267,
   TOKEN_LOGICAL_CHOICE = 268,
   TOKEN_LOGICAL_VALUE = 269,
   TOKEN_LOGICAL_NOT = 270,
   TOKEN_LOGICAL_OR = 271,
   TOKEN_LOGICAL_XOR = 272,
   TOKEN_LOGICAL_AND = 273,
   TOKEN_LOGICAL_EQ = 274,
   TOKEN_LOGICAL_NE = 275,
   TOKEN_LOGICAL_GT = 276,
   TOKEN_LOGICAL_GE = 277,
   TOKEN_LOGICAL_LT = 278,
   TOKEN_LOGICAL_LE = 279,
   TOKEN_STRUCTURE_OPEN = 280,
   TOKEN_STRUCTURE_VECTOR_OPEN = 281,
   TOKEN_STRUCTURE_COMMA = 282,
   TOKEN_STRUCTURE_CLOSE = 283,
   TOKEN_STRUCTURE_VECTOR_CLOSE = 284
 };
Function Documentation
if (! yymsg)
Referenced by SBMLImporter::createCMetabFromSpecies(), CSBMLunitInterface::debugOutput(), CSBMLunitInterface::determineUnits(), CInternalSolver::dintdy_(), CRDFPredicate::getPredicateFromURI(), CRandom::getRandomPoisson(), http_post(), CLSODAR::operator()(), CLSODA::operator()(), CSBMLunitInterface::outputStatistics(), CQFittingWidget::saveTask(), ScrollZoomer::scrollBar(), CQMergingData::slotBtnMerge(), CQExpandModelData::slotCompartmentActivated(), soap_begin_recv(), soap_begin_send(), soap_dealloc(), soap_end_recv(), soap_print_fault_location(), soap_putdime(), soap_resolve_attachment(), soap_response(), soap_try_connect_command(), CQMergingData::treeSelectionChanged(), CChemEqParser::yyunput(), and CEvaluationLexer::yyunput().
void setBooleanRequired (CEvaluationNode * pNode, const bool & booleanRequired)
Definition at line 108 of file CEvaluationParser_yacc.cpp.
References CEvaluationNode::CALL, CEvaluationNode::getType(), and CEvaluationNode::type().
Referenced by CEvaluationParserBase::yyparse().
 {
   if (CEvaluationNode::type(pNode->getType()) == CEvaluationNode::CALL)
     {
       static_cast<CEvaluationNodeCall *>(pNode)->setBooleanRequired(booleanRequired);
     }
 }
switch (yytype)
Definition at line 1278 of file CEvaluationParser_yacc.cpp.
Referenced by CInternalSolver::drchek_().
     {
       default:
         break;
     }
() void (yyvaluep)
Referenced by CCopasiXMLInterface::encode(), CLLayoutRenderer::initialize_gl_extension_functions(), CChemEqParser::LexerInput(), CEvaluationLexer::LexerInput(), CChemEqParser::LexerOutput(), CEvaluationLexer::LexerOutput(), soap_default_byte(), soap_default_int(), soap_default_ns2__checkRegExp(), soap_default_ns2__checkRegExpResponse(), soap_default_ns2__getDataResources(), soap_default_ns2__getDataResourcesResponse(), soap_default_ns2__getDataTypeDef(), soap_default_ns2__getDataTypeDefResponse(), soap_default_ns2__getDataTypePattern(), soap_default_ns2__getDataTypePatternResponse(), soap_default_ns2__getDataTypesId(), soap_default_ns2__getDataTypesIdResponse(), soap_default_ns2__getDataTypesName(), soap_default_ns2__getDataTypesNameResponse(), soap_default_ns2__getDataTypeSynonyms(), soap_default_ns2__getDataTypeSynonymsResponse(), soap_default_ns2__getDataTypeURI(), soap_default_ns2__getDataTypeURIResponse(), soap_default_ns2__getDataTypeURIs(), soap_default_ns2__getDataTypeURIsResponse(), soap_default_ns2__getJavaLibraryVersion(), soap_default_ns2__getJavaLibraryVersionResponse(), soap_default_ns2__getLocation(), soap_default_ns2__getLocationResponse(), soap_default_ns2__getLocations(), soap_default_ns2__getLocations_(), soap_default_ns2__getLocationsResponse(), soap_default_ns2__getLocationsResponse_(), soap_default_ns2__getMiriamURI(), soap_default_ns2__getMiriamURIResponse(), soap_default_ns2__getName(), soap_default_ns2__getNameResponse(), soap_default_ns2__getNames(), soap_default_ns2__getNamesResponse(), soap_default_ns2__getOfficialDataTypeURI(), soap_default_ns2__getOfficialDataTypeURIResponse(), soap_default_ns2__getResourceInfo(), soap_default_ns2__getResourceInfoResponse(), soap_default_ns2__getResourceInstitution(), soap_default_ns2__getResourceInstitutionResponse(), soap_default_ns2__getResourceLocation(), soap_default_ns2__getResourceLocationResponse(), soap_default_ns2__getServicesInfo(), soap_default_ns2__getServicesInfoResponse(), soap_default_ns2__getServicesVersion(), soap_default_ns2__getServicesVersionResponse(), soap_default_ns2__getURI(), soap_default_ns2__getURIResponse(), soap_default_ns2__isDeprecated(), soap_default_ns2__isDeprecatedResponse(), soap_default_SOAP_ENV__Code(), soap_default_SOAP_ENV__Detail(), soap_default_SOAP_ENV__Fault(), soap_default_SOAP_ENV__Header(), soap_default_SOAP_ENV__Reason(), soap_default_std__string(), soap_default_string(), soap_markelement(), soap_serialize_ns2__checkRegExp(), soap_serialize_ns2__checkRegExpResponse(), soap_serialize_ns2__getDataResources(), soap_serialize_ns2__getDataResourcesResponse(), soap_serialize_ns2__getDataTypeDef(), soap_serialize_ns2__getDataTypeDefResponse(), soap_serialize_ns2__getDataTypePattern(), soap_serialize_ns2__getDataTypePatternResponse(), soap_serialize_ns2__getDataTypesId(), soap_serialize_ns2__getDataTypesIdResponse(), soap_serialize_ns2__getDataTypesName(), soap_serialize_ns2__getDataTypesNameResponse(), soap_serialize_ns2__getDataTypeSynonyms(), soap_serialize_ns2__getDataTypeSynonymsResponse(), soap_serialize_ns2__getDataTypeURI(), soap_serialize_ns2__getDataTypeURIResponse(), soap_serialize_ns2__getDataTypeURIs(), soap_serialize_ns2__getDataTypeURIsResponse(), soap_serialize_ns2__getJavaLibraryVersion(), soap_serialize_ns2__getJavaLibraryVersionResponse(), soap_serialize_ns2__getLocation(), soap_serialize_ns2__getLocationResponse(), soap_serialize_ns2__getLocations(), soap_serialize_ns2__getLocations_(), soap_serialize_ns2__getLocationsResponse(), soap_serialize_ns2__getLocationsResponse_(), soap_serialize_ns2__getMiriamURI(), soap_serialize_ns2__getMiriamURIResponse(), soap_serialize_ns2__getName(), soap_serialize_ns2__getNameResponse(), soap_serialize_ns2__getNames(), soap_serialize_ns2__getNamesResponse(), soap_serialize_ns2__getOfficialDataTypeURI(), soap_serialize_ns2__getOfficialDataTypeURIResponse(), soap_serialize_ns2__getResourceInfo(), soap_serialize_ns2__getResourceInfoResponse(), soap_serialize_ns2__getResourceInstitution(), soap_serialize_ns2__getResourceInstitutionResponse(), soap_serialize_ns2__getResourceLocation(), soap_serialize_ns2__getResourceLocationResponse(), soap_serialize_ns2__getServicesInfo(), soap_serialize_ns2__getServicesInfoResponse(), soap_serialize_ns2__getServicesVersion(), soap_serialize_ns2__getServicesVersionResponse(), soap_serialize_ns2__getURI(), soap_serialize_ns2__getURIResponse(), soap_serialize_ns2__isDeprecated(), soap_serialize_ns2__isDeprecatedResponse(), soap_serialize_SOAP_ENV__Code(), soap_serialize_SOAP_ENV__Detail(), soap_serialize_SOAP_ENV__Fault(), soap_serialize_SOAP_ENV__Header(), soap_serialize_SOAP_ENV__Reason(), and soap_serialize_std__string().
static void yydestruct (yymsg , yytype , yyvaluep) const static
Referenced by CEvaluationParserBase::yyparse().
Variable Documentation
int CEvaluationParserchar
Definition at line 1287 of file CEvaluationParser_yacc.cpp.
CEvaluationNode* CEvaluationParserlval
int CEvaluationParsernerrs
Definition at line 1301 of file CEvaluationParser_yacc.cpp.
CEvaluationNode* mpNode
Definition at line 1298 of file CEvaluationParser_yacc.cpp.
Referenced by CEvaluationLexer::yylex().
const yytype_int8 yycheck[] static
Definition at line 692 of file CEvaluationParser_yacc.cpp.
const yytype_uint8 yydefact[] static
Initial value:
=
{
  0,     4,     5,    56,     0,     0,     0,     0,    17,     0,
  0,     0,     2,     3,    16,     0,    53,     0,     0,     0,
  0,    13,    16,     0,     0,    45,    16,     0,     0,     1,
  0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
  0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
  0,     0,     0,     0,     0,     0,     0,     0,     0,    16,
  10,    44,     9,     8,     7,     6,    20,    24,    28,    29,
  30,    31,    32,    16,    36,    16,    40,    16,    23,    16,
  27,    16,    33,    16,    37,    16,    41,    16,    21,    25,
  47,    49,    50,    57,    54,    58,    55,     0,    48,    11,
  0,     0,    16,     0,     0,    51,    52,     0,     0,     0,
  0,     0,     0,     0,    12,     0,     0,     0,     0,     0,
  0,     0,     0,     0,     0,    14,    18,    15,    19
}
Definition at line 588 of file CEvaluationParser_yacc.cpp.
const yytype_int8 yydefgoto[] static
Initial value:
=
{
  -1,    11,    24,    13,    52,    53,    22,    15
}
Definition at line 606 of file CEvaluationParser_yacc.cpp.
const yytype_int16 yypact[] static
Initial value:
=
{
  241,   -48,   -48,   -26,   -14,    -9,   254,     2,   -48,   241,
  241,    59,   333,   147,   175,   225,   -48,   254,   254,    42,
  254,    63,   -48,   241,   333,    74,     1,   261,   282,   -48,
  254,   254,   254,   254,   254,   254,   254,   254,   254,   254,
  241,   241,   241,   241,   241,   241,   241,   241,   241,   241,
  214,     3,    94,    31,    64,    -5,   241,   121,   343,   348,
  -48,   -48,    63,    63,   188,    23,   117,   117,   117,   117,
  117,   117,   217,    79,    19,   119,    74,   125,    80,   196,
  -48,     8,   217,   157,    19,   162,    74,   183,    80,   -48,
  -48,   117,   -48,   -48,   -48,   -48,   -48,   225,   -48,   -48,
  254,   360,   365,   241,   241,   117,   -48,   197,   254,   254,
  295,   377,   314,   382,   -48,    43,    53,   254,   241,   254,
  241,   265,   311,   285,   330,   -48,   -48,   -48,   -48
}
Definition at line 614 of file CEvaluationParser_yacc.cpp.
const yytype_int8 yypgoto[] static
Initial value:
=
{
  -48,   -48,    51,    68,   -47,   -48,     0,   -48
}
Definition at line 632 of file CEvaluationParser_yacc.cpp.
const yytype_uint8 yyr1[] static
Initial value:
=
{
  0,    30,    31,    31,    32,    32,    32,    32,    32,    32,
  32,    32,    32,    32,    32,    32,    32,    33,    33,    33,
  33,    33,    33,    33,    33,    33,    33,    33,    33,    33,
  33,    33,    33,    33,    33,    33,    33,    33,    33,    33,
  33,    33,    33,    33,    33,    33,    33,    34,    34,    35,
  35,    35,    35,    36,    36,    36,    37,    37,    37
}
Definition at line 564 of file CEvaluationParser_yacc.cpp.
const yytype_uint8 yyr2[] static
Initial value:
=
{
  0,     2,     1,     1,     1,     1,     3,     3,     3,     3,
  3,     4,     6,     2,     8,     8,     1,     1,     8,     8,
  3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
  3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
  3,     3,     3,     3,     3,     2,     2,     2,     2,     2,
  2,     3,     3,     2,     3,     3,     1,     3,     3
}
Definition at line 575 of file CEvaluationParser_yacc.cpp.
const yytype_uint8 yystos[] static
Initial value:
=
{
  0,     3,     4,     5,     6,     7,     8,    13,    14,    15,
  25,    31,    32,    33,    36,    37,    28,    25,    25,    13,
  25,    32,    36,    25,    32,    33,    36,    32,    33,     0,
  9,    10,    11,    12,    19,    20,    21,    22,    23,    24,
  16,    17,    18,    19,    20,    16,    17,    18,    19,    20,
  26,    32,    34,    35,    32,    32,    25,    32,    33,    36,
  28,    28,    32,    32,    32,    32,    32,    32,    32,    32,
  32,    32,    33,    36,    33,    36,    33,    36,    33,    36,
  33,    36,    33,    36,    33,    36,    33,    36,    33,    33,
  29,    32,    34,    27,    28,    27,    28,    27,    29,    28,
  27,    33,    36,    27,    27,    32,    34,    32,    27,    27,
  32,    33,    32,    33,    28,    32,    32,    27,    27,    27,
  27,    32,    33,    32,    33,    28,    28,    28,    28
}
Definition at line 739 of file CEvaluationParser_yacc.cpp.
const yytype_int16 yytable[] static
Definition at line 641 of file CEvaluationParser_yacc.cpp.
const yytype_uint8 yytranslate[] static
Definition at line 446 of file CEvaluationParser_yacc.cpp.
int yytype
Definition at line 1267 of file CEvaluationParser_yacc.cpp.
CEvaluationNode* * yyvaluep
Definition at line 1268 of file CEvaluationParser_yacc.cpp.