COPASI API: CConfigurationFile::CXML Class Reference
CConfigurationFile::CXML Class Reference
Public Member Functions
CXML ()
const CCopasiParameterGroup & getConfiguration () const
virtual bool load (std::istream &is, const std::string &relativeTo)
virtual bool save (std::ostream &os, const std::string &relativeTo)
void setConfiguration (const CCopasiParameterGroup &configuration)
~CXML ()
Public Member Functions inherited from CCopasiXMLInterface
CCopasiXMLInterface ()
bool load (const std::string &fileName, const std::string &relativeTo)
bool save (const std::string &fileName, const std::string &relativeTo)
virtual ~CCopasiXMLInterface ()
Private Attributes
CCopasiParameterGroup mConfiguration
Additional Inherited Members
Public Types inherited from CCopasiXMLInterface
enum EncodingType { none = 0, standard, attribute, character }
Static Public Member Functions inherited from CCopasiXMLInterface
static std::string encode (const std::string &str, const EncodingType &type=standard)
static std::string utf8 (const std::string &str)
Protected Member Functions inherited from CCopasiXMLInterface
bool endSaveElement (const std::string &name)
bool saveData (const std::string &data)
bool saveElement (const std::string &name, CXMLAttributeList &attributeList)
bool saveParameter (const CCopasiParameter &parameter)
bool saveParameterGroup (const std::vector< CCopasiParameter * > &group)
bool saveXhtml (const std::string &xhtml)
bool startSaveElement (const std::string &name)
bool startSaveElement (const std::string &name, CXMLAttributeList &attributeList)
Protected Attributes inherited from CCopasiXMLInterface
std::string mIndent
std::istream * mpIstream
std::ostream * mpOstream
std::string mPWD
Detailed Description
Class dealing with the loading and writing of the XML configuration file.
Definition at line 253 of file CConfigurationFile.h.
Constructor & Destructor Documentation
CConfigurationFile::CXML::CXML ()
Constructor
Definition at line 343 of file CConfigurationFile.cpp.
References CCopasiParameterGroup::assertGroup(), and mConfiguration.
                             :
   CCopasiXMLInterface(),
   mConfiguration("Configuration")
 {
   mConfiguration.assertGroup("Recent Files");
   mConfiguration.assertGroup("Recent SBML Files");
   mConfiguration.assertGroup("MIRIAM Resources");
   mConfiguration.assertGroup("Recent SEDML Files");
 }
CConfigurationFile::CXML::~CXML ()
Destructor
Definition at line 353 of file CConfigurationFile.cpp.
 {}
Member Function Documentation
const CCopasiParameterGroup & CConfigurationFile::CXML::getConfiguration () const
Retrieve the configuration contents
Returns
const CConfigurationFile & configuration
Definition at line 445 of file CConfigurationFile.cpp.
Referenced by CConfigurationFile::load().
 {return mConfiguration;}
bool CConfigurationFile::CXML::load (std::istream & is, const std::string & relativeTo) virtual
Load information from a given istream.
Parameters
std::istream & is
const std::string & relativeTo
Returns
bool success
Implements CCopasiXMLInterface.
Definition at line 381 of file CConfigurationFile.cpp.
References BUFFER_SIZE, CCopasiParameterGroup::clear(), CExpatTemplate< CType >::getCurrentColumnNumber(), CCopasiXMLParser::getCurrentGroup(), CExpatTemplate< CType >::getCurrentLineNumber(), CExpatTemplate< CType >::getErrorString(), COptions::getValue(), MCConfiguration, MCXML, CExpatTemplate< CType >::parse(), CCopasiMessage::RAW, CCopasiObject::setObjectName(), and CCopasiMessage::WARNING.
 {
   mPWD = relativeTo;
   is.imbue(std::locale::classic());
   is.precision(16);
   mpIstream = &is;
   bool success = true;
   bool done = false;
   CVersion Version;
   CCopasiXMLParser Parser(Version);
 #define BUFFER_SIZE 0xfffe
   char * pBuffer = new char[BUFFER_SIZE + 1];
   while (!done)
     {
       mpIstream->get(pBuffer, BUFFER_SIZE, 0);
       if (mpIstream->eof()) done = true;
       if (mpIstream->fail() && !done)
         {
           std::string ConfigFile;
           COptions::getValue("ConfigFile", ConfigFile);
           CCopasiMessage Message(CCopasiMessage::WARNING, MCConfiguration + 2, ConfigFile.c_str());
           done = true;
           success = false;
         }
       if (!Parser.parse(pBuffer, -1, done))
         {
           CCopasiMessage Message(CCopasiMessage::RAW, MCXML + 2,
                                  Parser.getCurrentLineNumber(),
                                  Parser.getCurrentColumnNumber(),
                                  Parser.getErrorString());
           done = true;
           success = false;
         }
     }
   delete [] pBuffer;
 #undef BUFFER_SIZE
   if (success && Parser.getCurrentGroup() != NULL)
     {
       mConfiguration = * Parser.getCurrentGroup();
       mConfiguration.setObjectName("Configuration");
       delete Parser.getCurrentGroup();
     }
   else
     mConfiguration.clear();
   return success;
 }
bool CConfigurationFile::CXML::save (std::ostream & os, const std::string & relativeTo) virtual
Save information to a given ostream.
Parameters
std::ostream & os
const std::string & relativeTo
Returns
bool success
Implements CCopasiXMLInterface.
Definition at line 356 of file CConfigurationFile.cpp.
References CVersion::getVersion(), UTCTimeStamp(), and CVersion::VERSION.
 {
   mPWD = relativeTo;
   os.imbue(std::locale::classic());
   os.precision(16);
   mpOstream = &os;
   *mpOstream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
              << std::endl;
   *mpOstream << "<!-- generated with COPASI "
              << CVersion::VERSION.getVersion()
              << " (http://www.copasi.org) at "
              << UTCTimeStamp()
              << " UTC -->"
              << std::endl;
   saveParameter(mConfiguration);
   return true;
 }
void CConfigurationFile::CXML::setConfiguration (const CCopasiParameterGroup & configuration)
Set the configuration contents
Parameters
const CConfigurationFile & configuration
Definition at line 442 of file CConfigurationFile.cpp.
Referenced by CConfigurationFile::save().
 {mConfiguration = configuration;}
Member Data Documentation
CCopasiParameterGroup CConfigurationFile::CXML::mConfiguration private
A pointer to the CCopasiParameterGroup containing the information
Definition at line 302 of file CConfigurationFile.h.
Referenced by CXML().
The documentation for this class was generated from the following files:
CConfigurationFile.h
CConfigurationFile.cpp