COPASI API: CQEventWidget1 Class Reference
CQEventWidget1 Class Reference
#include <CQEventWidget1.h>
Public Member Functions
CQEventWidget1 (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQEventWidget1 ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotActualizeAssignmentExpression (int index)
Slot to actualize the assignment expression widget of event assignment according to the target.
void slotAddTarget ()
void slotBtnCopy ()
void slotBtnDelete ()
void slotBtnNew ()
Slot to create a new event; activated whenever the New button is clicked.
void slotChooseDelay (int choice)
void slotDeleteTarget ()
void slotSelectObject ()
Slot to select an object from the existing ones -only- for target.
Private Member Functions
void init ()
bool loadFromEvent ()
void saveToEvent ()
void showDelayExpression (bool display)
Private Attributes
std::string mAssignmentKey
CCopasiVector< CEventAssignment > mAssignments
bool mChanged
size_t mCurrentTarget
QString mEAName
bool mExpressionDelayValid
bool mExpressionEAValid
bool mExpressionTriggerValid
std::string mKeyToCopy
CEvent * mpEvent
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 29 of file CQEventWidget1.h.
Constructor & Destructor Documentation
CQEventWidget1::CQEventWidget1 (QWidget * parent = 0, const char * name = 0)
Definition at line 38 of file CQEventWidget1.cpp.
References init().
                                                                  :
   CopasiWidget(parent, name),
   mKeyToCopy("")
 {
   setupUi(this);
   init();
 }
CQEventWidget1::~CQEventWidget1 ()
Definition at line 50 of file CQEventWidget1.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
bool CQEventWidget1::enterProtected () protected virtual
Function to interact with an object of class CEvent
Reimplemented from CopasiWidget.
Definition at line 415 of file CQEventWidget1.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), loadFromEvent(), mCurrentTarget, mKeyToCopy, mpEvent, CopasiWidget::mpListView, CopasiWidget::mpObject, and ListViews::switchToOtherWidget().
 {
   bool success = true;
   if (mKeyToCopy != "")
     {
       mpEvent = dynamic_cast<CEvent*>(CCopasiRootContainer::getKeyFactory()->get(mKeyToCopy));
       mKeyToCopy = "";
     }
   else
     {
       mpEvent = dynamic_cast<CEvent*>(mpObject);
     }
   mCurrentTarget = C_INVALID_INDEX;
   if (mpEvent)
     {
       success =  loadFromEvent();
     }
   mpEvent = dynamic_cast<CEvent*>(mpObject);
   if (!success)
     {
       mpListView->switchToOtherWidget(114, ""); //TODO
     }
   return success;
 }
void CQEventWidget1::init () private
Definition at line 105 of file CQEventWidget1.cpp.
References CQIconResource::copasi, CQIconResource::editAdd, CQIconResource::editDelete, CQIconResource::icon(), mExpressionDelayValid, mExpressionEAValid, mExpressionTriggerValid, showDelayExpression(), slotActualizeAssignmentExpression(), slotChooseDelay(), and CQExpressionWidget::TransientExpression.
Referenced by CQEventWidget1().
 {
   showDelayExpression(false);
   // SIGNAL-SLOT connections
   connect(mpComboBoxDelay, SIGNAL(currentIndexChanged(int)), this, SLOT(slotChooseDelay(int)));
   connect(mpLBTarget, SIGNAL(currentRowChanged(int)), this, SLOT(slotActualizeAssignmentExpression(int)));
 //  mpExpressionTrigger->mpExpressionWidget->setBoolean(true);
   mpExpressionTrigger->mpExpressionWidget->setBoolean(true);
   mExpressionDelayValid = true;
   mpExpressionDelay->mpExpressionWidget->setExpressionType(CQExpressionWidget::TransientExpression);
   mExpressionTriggerValid = false;
   //  mpExpressionTrigger->mpExpressionWidget->setExpressionType(CQSimpleSelectionTree::TRANSIENT_EXPRESSION);
   mExpressionEAValid = false;
   mpExpressionEA->mpExpressionWidget->setExpressionType(CQExpressionWidget::TransientExpression);
   // ----- correlated to GUI layout of the event assignment ----
   // hide the label and widget with respect to expression
   mpLabelEA->setEnabled(false);
   mpExpressionEA->setEnabled(false);
   // Set the icons for the buttons
   mpBtnSelectObject->setIcon(CQIconResource::icon(CQIconResource::copasi));
   mpBtnAddTarget->setIcon(CQIconResource::icon(CQIconResource::editAdd));
   mpBtnDeleteTarget->setIcon(CQIconResource::icon(CQIconResource::editDelete));
 }
bool CQEventWidget1::leave () virtual
The slot to be done before leaving the active event widget
Reimplemented from CopasiWidget.
Definition at line 447 of file CQEventWidget1.cpp.
References saveToEvent().
 {
   saveToEvent();
   return true;
 }
bool CQEventWidget1::loadFromEvent () private
Load all values with respect to a chosen saved event
Definition at line 178 of file CQEventWidget1.cpp.
References CCopasiVector< T >::add(), CCopasiVector< T >::begin(), C_INVALID_INDEX, CCopasiVector< T >::clear(), CCopasiVector< T >::end(), FROM_UTF8, CKeyFactory::get(), CEvent::getAssignments(), CEvent::getDelayAssignment(), CEvent::getDelayExpression(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDisplayName(), CEvent::getTriggerExpression(), mAssignments, mChanged, mCurrentTarget, mpEvent, CModelEntity::setExpression(), and CCopasiVector< T >::size().
Referenced by enterProtected().
 {
   if (mpEvent == NULL) return false;
   const CModel * pModel =
     dynamic_cast< const CModel * >(mpEvent->getObjectAncestor("Model"));
   if (pModel == NULL) return false;
   // *** Expression of Trigger
   mpExpressionTrigger->mpExpressionWidget->setExpression(mpEvent->getTriggerExpression());
   mpExpressionTrigger->updateWidget();    // bring into view mode
   // *** Expression of Delay
   mpExpressionDelay->mpExpressionWidget->setExpression(mpEvent->getDelayExpression());
   mpExpressionDelay->updateWidget();    // bring into view mode
   if (mpEvent->getDelayExpression() == "")
     {
       mpComboBoxDelay->setCurrentIndex(0); // Set Delay to "None"
     }
   else if (mpEvent->getDelayAssignment())
     {
       mpComboBoxDelay->setCurrentIndex(2); // Assignment only
     }
   else
     {
       mpComboBoxDelay->setCurrentIndex(1); // Calculation and Assignment
     }
   // copy assignment from event
   CCopasiVectorN< CEventAssignment >::const_iterator it = mpEvent->getAssignments().begin();
   CCopasiVectorN< CEventAssignment >::const_iterator end = mpEvent->getAssignments().end();
   mAssignments.clear();
   QStringList Targets;
   int ijk = 0;
   for (; it != end; ++it, ijk++)
     {
       const CModelEntity * pEntity =
         dynamic_cast< CModelEntity * >(CCopasiRootContainer::getKeyFactory()->get((*it)->getTargetKey()));
       if (pEntity != NULL)
         {
           Targets.append(FROM_UTF8(pEntity->getObjectDisplayName()));
           mAssignments.add(**it);
 #ifdef XXXX // Add type dependent information
           if (sObjectName == "Compartment")
             {
               sName = FROM_UTF8(CCopasiRootContainer::getKeyFactory()->get(it->first)->getObjectDisplayName() + ".Volume");
             }
           if (sObjectName == "Metabolite")
             {
               sName = FROM_UTF8("[" + CCopasiRootContainer::getKeyFactory()->get(it->first)->getObjectDisplayName() + "]");
             }
           if (sObjectName.contains("ModelValue"))
             {
               sName = FROM_UTF8(CCopasiRootContainer::getKeyFactory()->get(it->first)->getObjectDisplayName());
             }
 #endif // XXXX
         }
     }
   // fill the list box and the expression widget with correct assignments
   mpLBTarget->clear();
   mpLBTarget->insertItems(0, Targets);
   size_t NewTarget = mCurrentTarget;
   if (mCurrentTarget == C_INVALID_INDEX &&
       mAssignments.size() > 0)
     {
       NewTarget = 0;
     }
   mpLBTarget->setCurrentRow((int) NewTarget);
   mChanged = false;
   return true;
 }
void CQEventWidget1::saveToEvent () private
The slot to save all current values of the active event widget
Definition at line 268 of file CQEventWidget1.cpp.
References CCopasiVectorN< CType >::add(), CCopasiVector< T >::begin(), C_INVALID_INDEX, ListViews::CHANGE, CCopasiVector< T >::end(), ListViews::EVENT, CEvent::getAssignments(), CCopasiRootContainer::getDatamodelList(), CEvent::getDelayAssignment(), CEvent::getDelayExpression(), CCopasiVectorN< CType >::getIndex(), CCopasiObject::getObjectAncestor(), CEvent::getTriggerExpression(), mAssignments, mChanged, mCurrentTarget, CopasiWidget::mKey, mpEvent, CopasiWidget::protectedNotify(), CCopasiVectorN< CType >::remove(), CEvent::setDelayAssignment(), CEvent::setDelayExpression(), CEvent::setTriggerExpression(), and CCopasiVector< T >::size().
Referenced by leave(), and slotBtnNew().
 {
   if (mpEvent == NULL) return;
   const CModel * pModel =
     dynamic_cast< const CModel * >(mpEvent->getObjectAncestor("Model"));
   if (pModel == NULL) return;
   if (mpEvent->getTriggerExpression() != mpExpressionTrigger->mpExpressionWidget->getExpression())
     {
       mpEvent->setTriggerExpression(mpExpressionTrigger->mpExpressionWidget->getExpression());
       mChanged = true;
     }
   switch (mpComboBoxDelay->currentIndex())
     {
       case 0:
         mpEvent->setDelayExpression("");
         if (mpEvent->getDelayAssignment() != false)
           {
             mpEvent->setDelayAssignment(false);
             mChanged = true;
           }
         break;
       case 1:
         if (mpEvent->getDelayExpression() != mpExpressionDelay->mpExpressionWidget->getExpression())
           {
             mpEvent->setDelayExpression(mpExpressionDelay->mpExpressionWidget->getExpression());
             mChanged = true;
           }
         if (mpEvent->getDelayAssignment() != false)
           {
             mpEvent->setDelayAssignment(false);
             mChanged = true;
           }
         break;
       case 2:
         if (mpEvent->getDelayExpression() != mpExpressionDelay->mpExpressionWidget->getExpression())
           {
             mpEvent->setDelayExpression(mpExpressionDelay->mpExpressionWidget->getExpression());
             mChanged = true;
           }
         if (mpEvent->getDelayAssignment() != true)
           {
             mpEvent->setDelayAssignment(true);
             mChanged = true;
           }
         break;
     }
   // Save the event assignments
   // First we make sure that the current assignment is saved
   if (mCurrentTarget != C_INVALID_INDEX)
     {
       mAssignments[mCurrentTarget]->setExpression(mpExpressionEA->mpExpressionWidget->getExpression());
     }
   CCopasiVector< CEventAssignment >::const_iterator it = mAssignments.begin();
   CCopasiVector< CEventAssignment >::const_iterator end = mAssignments.end();
   CCopasiVectorN< CEventAssignment > & OldAssignments = mpEvent->getAssignments();
   size_t Found;
   // We first update all assignments.
   for (; it != end; ++it)
     {
       Found = OldAssignments.getIndex((*it)->getTargetKey());
       if (Found == C_INVALID_INDEX)
         {
           OldAssignments.add(**it);
           mChanged = true;
         }
       else if (OldAssignments[Found]->getExpression() != (*it)->getExpression())
         {
           OldAssignments[Found]->setExpression((*it)->getExpression());
           mChanged = true;
         }
     }
   // Find the deleted assignments and mark them.
   CCopasiVectorN< CEventAssignment >::const_iterator itOld = OldAssignments.begin();
   CCopasiVectorN< CEventAssignment >::const_iterator endOld = OldAssignments.end();
   size_t DeleteCount = 0;
   if (OldAssignments.size() > mAssignments.size())
     {
       DeleteCount = OldAssignments.size() - mAssignments.size();
     }
   std::vector< std::string > ToBeDeleted;
   for (; itOld != endOld && DeleteCount > 0; ++itOld)
     {
       const std::string & key = (*itOld)->getTargetKey();
       for (it = mAssignments.begin(); it != end; ++it)
         {
           if (key == (*it)->getTargetKey()) break;
         }
       if (it == end)
         {
           ToBeDeleted.push_back(key);
           DeleteCount--;
           mChanged = true;
         }
     }
   // Delete the assignments marked to be deleted.
   std::vector< std::string >::const_iterator itDelete = ToBeDeleted.begin();
   std::vector< std::string >::const_iterator endDelete = ToBeDeleted.end();
   for (; itDelete != endDelete; ++itDelete)
     {
       OldAssignments.remove(*itDelete);
     }
   if (mChanged)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed();
       protectedNotify(ListViews::EVENT, ListViews::CHANGE, mKey);
     }
   mChanged = false;
 }
void CQEventWidget1::showDelayExpression (bool show) private
Function to apply the Delay Expression Widget
Definition at line 519 of file CQEventWidget1.cpp.
Referenced by init(), and slotChooseDelay().
 {
   if (show)
     {
       mpLabelDelayExpression->show();
       mpExpressionDelay->show();
     }
   else
     {
       mpLabelDelayExpression->hide();
       mpExpressionDelay->hide();
     }
 }
void CQEventWidget1::slotActualizeAssignmentExpression (int index) private slot
Slot to actualize the assignment expression widget of event assignment according to the target.
Definition at line 480 of file CQEventWidget1.cpp.
References C_INVALID_INDEX, mAssignments, mCurrentTarget, and CCopasiVector< T >::size().
Referenced by init().
 {
   size_t NewTarget = (size_t) index;
   if (NewTarget != C_INVALID_INDEX &&
       NewTarget >= mAssignments.size())
     {
       NewTarget = mAssignments.size() - 1;
     }
   // Save the current assignment
   if (NewTarget != mCurrentTarget &&
       mCurrentTarget < mAssignments.size())
     {
       mAssignments[mCurrentTarget]->setExpression(mpExpressionEA->mpExpressionWidget->getExpression());
     }
   mCurrentTarget = NewTarget;
   if (mCurrentTarget == C_INVALID_INDEX) // no target anymore
     {
       // hide the label and widget with respect to expression
       mpLabelEA->setEnabled(false);
       mpExpressionEA->setEnabled(false);
       return;
     }
   else
     {
       // show the label and widget with respect to expression
       mpLabelEA->setEnabled(true);
       mpExpressionEA->setEnabled(true);
       mpExpressionEA->mpExpressionWidget->setExpression(mAssignments[mCurrentTarget]->getExpression());
       mpExpressionEA->updateWidget();
     }
 }
void CQEventWidget1::slotAddTarget () private slot
Slot to add a new target without object target nor its expression Impact only on the appearance.
Definition at line 139 of file CQEventWidget1.cpp.
References CCopasiVector< T >::add(), CQSimpleSelectionTree::EventTarget, FROM_UTF8, CModelEntity::getKey(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectParent(), CCopasiSelectionDialog::getObjectSingle(), mAssignments, and CCopasiVector< T >::size().
Referenced by slotSelectObject().
 {
   CQSimpleSelectionTree::ObjectClasses Classes =
     CQSimpleSelectionTree::EventTarget;
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this, Classes);
   if (pObject == NULL) return;
   const CModelEntity * pME = dynamic_cast< const CModelEntity * >(pObject->getObjectParent());
   if (pME == NULL) return;
   mAssignments.add(new CEventAssignment(pME->getKey()), true);
   mpLBTarget->addItem(FROM_UTF8(pME->getObjectDisplayName()));
   mpLBTarget->setCurrentRow((int)(mAssignments.size() - 1));
 }
void CQEventWidget1::slotBtnCopy () private slot
Definition at line 99 of file CQEventWidget1.cpp.
References CopasiWidget::mKey, and mKeyToCopy.
 {
   mKeyToCopy = mKey;
 }
void CQEventWidget1::slotBtnDelete () private slot
Slot to delete the active event widget
Definition at line 56 of file CQEventWidget1.cpp.
References ListViews::DELETE, ListViews::EVENT, CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getModel(), CopasiWidget::mKey, mpEvent, CopasiWidget::protectedNotify(), and CModel::removeEvent().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return;
   pDataModel->getModel()->removeEvent(mKey);
   mpEvent = NULL;
   protectedNotify(ListViews::EVENT, ListViews::DELETE, mKey);
 }
void CQEventWidget1::slotBtnNew () private slot
Slot to create a new event; activated whenever the New button is clicked.
Definition at line 74 of file CQEventWidget1.cpp.
References ListViews::ADD, C_INVALID_INDEX, ListViews::EVENT, CCopasiRootContainer::getDatamodelList(), CopasiWidget::mpListView, CopasiWidget::protectedNotify(), saveToEvent(), ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   // save the current setting values
   saveToEvent();
   // standard name
   std::string name = "event_1";
   // if the standard name already exists then creating the new event will fail
   // thus, a growing index will automatically be added to the standard name
   int i = 1;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   while (!(*CCopasiRootContainer::getDatamodelList())[0]->getModel()->createEvent(name))
     {
       i++;
       name = "event_";
       name += TO_UTF8(QString::number(i));
     }
   std::string key = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getEvents()[name]->getKey();
   protectedNotify(ListViews::EVENT, ListViews::ADD, key);
   mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQEventWidget1::slotChooseDelay (int choice) private slot
Definition at line 534 of file CQEventWidget1.cpp.
References showDelayExpression().
Referenced by init().
 {
   if (choice != 0) // Not "None"
     {
       showDelayExpression(true);
     }
   else
     {
       showDelayExpression(false);
     }
 }
void CQEventWidget1::slotDeleteTarget () private slot
Slot to remove the active target from the appearance Impact only on the appearance.
Definition at line 162 of file CQEventWidget1.cpp.
References mAssignments, mCurrentTarget, pdelete, CCopasiVector< T >::remove(), and CCopasiVector< T >::size().
 {
   if (mCurrentTarget > mAssignments.size() - 1 ||
       mAssignments.size() == 0) return;
   size_t ToBeDeleted = mCurrentTarget;
   QListWidgetItem * pItem = mpLBTarget->takeItem((int) ToBeDeleted);
   pdelete(pItem);
   mAssignments.remove(ToBeDeleted);
   mCurrentTarget = mpLBTarget->currentIndex().row();
 }
void CQEventWidget1::slotSelectObject () private slot
Slot to select an object from the existing ones -only- for target.
Definition at line 455 of file CQEventWidget1.cpp.
References C_INVALID_INDEX, CQSimpleSelectionTree::EventTarget, FROM_UTF8, CModelEntity::getKey(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectParent(), CCopasiSelectionDialog::getObjectSingle(), mAssignments, mCurrentTarget, and slotAddTarget().
 {
   if (mCurrentTarget == C_INVALID_INDEX)
     return slotAddTarget();
   CQSimpleSelectionTree::ObjectClasses Classes =
     CQSimpleSelectionTree::EventTarget;
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this, Classes);
   if (pObject == NULL) return;
   const CModelEntity * pME = dynamic_cast< const CModelEntity * >(pObject->getObjectParent());
   if (pME == NULL) return;
   if (mAssignments[mCurrentTarget]->setTargetKey(pME->getKey()))
     {
       // If the target key change was successful we need to update the label.
       mpLBTarget->item((int) mCurrentTarget)->setText(FROM_UTF8(pME->getObjectDisplayName()));
     }
 }
bool CQEventWidget1::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
The slot to update the active event widget
Reimplemented from CopasiWidget.
Definition at line 409 of file CQEventWidget1.cpp.
 {
   return true;
 }
Member Data Documentation
std::string CQEventWidget1::mAssignmentKey private
Definition at line 52 of file CQEventWidget1.h.
CCopasiVector< CEventAssignment > CQEventWidget1::mAssignments private
Definition at line 54 of file CQEventWidget1.h.
Referenced by loadFromEvent(), saveToEvent(), slotActualizeAssignmentExpression(), slotAddTarget(), slotDeleteTarget(), and slotSelectObject().
bool CQEventWidget1::mChanged private
Definition at line 50 of file CQEventWidget1.h.
Referenced by loadFromEvent(), and saveToEvent().
size_t CQEventWidget1::mCurrentTarget private
Definition at line 53 of file CQEventWidget1.h.
Referenced by enterProtected(), loadFromEvent(), saveToEvent(), slotActualizeAssignmentExpression(), slotDeleteTarget(), and slotSelectObject().
QString CQEventWidget1::mEAName private
Definition at line 49 of file CQEventWidget1.h.
bool CQEventWidget1::mExpressionDelayValid private
Definition at line 47 of file CQEventWidget1.h.
Referenced by init().
bool CQEventWidget1::mExpressionEAValid private
Definition at line 48 of file CQEventWidget1.h.
Referenced by init().
bool CQEventWidget1::mExpressionTriggerValid private
Definition at line 46 of file CQEventWidget1.h.
Referenced by init().
std::string CQEventWidget1::mKeyToCopy private
Definition at line 60 of file CQEventWidget1.h.
Referenced by enterProtected(), and slotBtnCopy().
CEvent* CQEventWidget1::mpEvent private
Definition at line 51 of file CQEventWidget1.h.
Referenced by enterProtected(), loadFromEvent(), saveToEvent(), and slotBtnDelete().
The documentation for this class was generated from the following files:
CQEventWidget1.h
CQEventWidget1.cpp