COPASI API: CQCompartmentDM Class Reference
CQCompartmentDM Class Reference
#include <CQCompartmentDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQCompartmentDM (QObject *parent=0)
virtual QVariant data (const QModelIndex &index, int role) const
virtual Qt::ItemFlags flags (const QModelIndex &index) const
const std::vector< unsigned
C_INT32 > & getItemToType ()
const QStringList & getTypes ()
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
bool removeRows (QModelIndexList rows, const QModelIndex &index=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
bool insertRow ()
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRow (int position)
Protected Member Functions
bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Protected Attributes
std::vector< unsigned C_INT32 > mItemToType
QStringList mTypes
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 35 of file CQCompartmentDM.h.
Constructor & Destructor Documentation
CQCompartmentDM::CQCompartmentDM (QObject * parent = 0)
Definition at line 26 of file CQCompartmentDM.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, FROM_UTF8, mItemToType, mTypes, CModelEntity::ODE, and CModelEntity::StatusName.
   : CQBaseDataModel(parent)
 {
   mTypes.push_back(FROM_UTF8(CModelEntity::StatusName[CModelEntity::FIXED]));
   mTypes.push_back(FROM_UTF8(CModelEntity::StatusName[CModelEntity::ASSIGNMENT]));
   mTypes.push_back(FROM_UTF8(CModelEntity::StatusName[CModelEntity::ODE]));
   mItemToType.push_back(CModelEntity::FIXED);
   mItemToType.push_back(CModelEntity::ASSIGNMENT);
   mItemToType.push_back(CModelEntity::ODE);
 }
Member Function Documentation
int CQCompartmentDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 53 of file CQCompartmentDM.cpp.
References TOTAL_COLS_COMPARTMENTS.
Referenced by CQCompartmentsWidget::keyPressEvent().
 {
   return TOTAL_COLS_COMPARTMENTS;
 }
QVariant CQCompartmentDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 76 of file CQCompartmentDM.cpp.
References COL_EXPRESSION_COMPARTMENTS, COL_IEXPRESSION_COMPARTMENTS, COL_IVOLUME, COL_NAME_COMPARTMENTS, COL_RATE_COMPARTMENTS, COL_ROW_NUMBER, COL_TYPE_COMPARTMENTS, COL_VOLUME, flags(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CExpression::getDisplayString(), CModelEntity::getExpressionPtr(), CModelEntity::getInitialExpressionPtr(), CModelEntity::getInitialValue(), CCopasiObject::getObjectName(), CModelEntity::getRate(), CModelEntity::getStatus(), CModelEntity::getValue(), CQBaseDataModel::isDefaultRow(), mItemToType, rowCount(), and CModelEntity::StatusName.
Referenced by flags(), and setData().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (index.column() > 0 && role == Qt::ForegroundRole && !(flags(index) & Qt::ItemIsEditable))
     return QColor(Qt::darkGray);
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       if (isDefaultRow(index))
         {
           switch (index.column())
             {
               case COL_ROW_NUMBER:
                 return QVariant(QString(""));
               case COL_NAME_COMPARTMENTS:
                 return QVariant(QString("New Compartment"));
               case COL_TYPE_COMPARTMENTS:
                 return QVariant(QString(FROM_UTF8(CModelEntity::StatusName[mItemToType[0]])));
               case COL_IVOLUME:
                 return QVariant(QString::number(1.0, 'g', 10));
               default:
                 return QVariant(QString(""));
             }
         }
       else
         {
           CCompartment *pComp = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getCompartments()[index.row()];
           const CExpression * pExpression = NULL;
           switch (index.column())
             {
               case COL_ROW_NUMBER:
                 return QVariant(index.row() + 1);
               case COL_NAME_COMPARTMENTS:
                 return QVariant(QString(FROM_UTF8(pComp->getObjectName())));
               case COL_TYPE_COMPARTMENTS:
                 return QVariant(QString(FROM_UTF8(CModelEntity::StatusName[pComp->getStatus()])));
               case COL_IVOLUME:
                 if (role == Qt::EditRole)
                   return QVariant(QString::number(pComp->getInitialValue(), 'g', 10));
                 else
                   return QVariant(pComp->getInitialValue());
               case COL_VOLUME:
                 return QVariant(pComp->getValue());
               case COL_RATE_COMPARTMENTS:
                 return QVariant(pComp->getRate());
               case COL_IEXPRESSION_COMPARTMENTS:
               {
                 pExpression = pComp->getInitialExpressionPtr();
                 if (pExpression != NULL)
                   return QVariant(QString(FROM_UTF8(pExpression->getDisplayString())));
                 else
                   return QVariant();
               }
               case COL_EXPRESSION_COMPARTMENTS:
               {
                 pExpression = pComp->getExpressionPtr();
                 if (pExpression != NULL)
                   return QVariant(QString(FROM_UTF8(pExpression->getDisplayString())));
                 else
                   return QVariant();
               }
             }
         }
     }
   return QVariant();
 }
Qt::ItemFlags CQCompartmentDM::flags (const QModelIndex & index) const virtual
Reimplemented from CQBaseDataModel.
Definition at line 58 of file CQCompartmentDM.cpp.
References CModelEntity::ASSIGNMENT, COL_IVOLUME, COL_NAME_COMPARTMENTS, COL_TYPE_COMPARTMENTS, data(), FROM_UTF8, and CModelEntity::StatusName.
Referenced by data().
 {
   if (!index.isValid())
     return Qt::ItemIsEnabled;
   if (index.column() == COL_NAME_COMPARTMENTS || index.column() == COL_TYPE_COMPARTMENTS)
     return QAbstractItemModel::flags(index) | Qt::ItemIsEditable;
   else if (index.column() == COL_IVOLUME)
     {
       if (this->index(index.row(), COL_TYPE_COMPARTMENTS).data() == QString(FROM_UTF8(CModelEntity::StatusName[CModelEntity::ASSIGNMENT])))
         return QAbstractItemModel::flags(index) & ~Qt::ItemIsEnabled;
       else
         return QAbstractItemModel::flags(index)  | Qt::ItemIsEditable | Qt::ItemIsEnabled;
     }
   else
     return QAbstractItemModel::flags(index);
 }
const std::vector< unsigned C_INT32 > & CQCompartmentDM::getItemToType ()
Definition at line 44 of file CQCompartmentDM.cpp.
References mItemToType.
 {
   return mItemToType;
 }
const QStringList & CQCompartmentDM::getTypes ()
Definition at line 39 of file CQCompartmentDM.cpp.
References mTypes.
Referenced by CQCompartmentsWidget::CQCompartmentsWidget().
 {
   return mTypes;
 }
QVariant CQCompartmentDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 164 of file CQCompartmentDM.cpp.
References COL_EXPRESSION_COMPARTMENTS, COL_IEXPRESSION_COMPARTMENTS, COL_IVOLUME, COL_NAME_COMPARTMENTS, COL_RATE_COMPARTMENTS, COL_ROW_NUMBER, COL_TYPE_COMPARTMENTS, COL_VOLUME, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CModel::getVolumeRateUnitsDisplayString(), and CModel::getVolumeUnitsDisplayString().
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       QString ValueUnits, RateUnits, ExpressionUnits;
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       const CModel * pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
       if (pModel)
         {
           ValueUnits = FROM_UTF8(pModel->getVolumeUnitsDisplayString());
           if (!ValueUnits.isEmpty())
             ValueUnits = "\n(" + ValueUnits + ")";
           RateUnits = FROM_UTF8(pModel->getVolumeRateUnitsDisplayString());
           if (!RateUnits.isEmpty())
             RateUnits = "\n(" + RateUnits + ")";
           if (!ValueUnits.isEmpty() && !RateUnits.isEmpty())
             {
               if (ValueUnits == RateUnits)
                 ExpressionUnits = ValueUnits;
               else
                 ExpressionUnits = "\n(" + FROM_UTF8(pModel->getVolumeUnitsDisplayString()) + " or " + FROM_UTF8(pModel->getVolumeRateUnitsDisplayString()) + ")";
             }
           else if (!ValueUnits.isEmpty())
             ExpressionUnits = "\n(" + FROM_UTF8(pModel->getVolumeUnitsDisplayString()) + " or 1)";
           else if (!RateUnits.isEmpty())
             ExpressionUnits = "\n(1 or " + FROM_UTF8(pModel->getVolumeRateUnitsDisplayString()) + ")";
         }
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
           case COL_NAME_COMPARTMENTS:
             return QVariant(QString("Name"));
           case COL_TYPE_COMPARTMENTS:
             return QVariant(QString("     Type     "));
           case COL_IVOLUME:
             return QVariant("Initial Volume" + ValueUnits);
           case COL_VOLUME:
             return QVariant("Volume" + ValueUnits);
           case COL_RATE_COMPARTMENTS:
             return QVariant("Rate" + RateUnits);
           case COL_IEXPRESSION_COMPARTMENTS:
             return QVariant("Initial Expression" + ValueUnits);
           case COL_EXPRESSION_COMPARTMENTS:
             return QVariant("Expression" + ExpressionUnits);
           default:
             return QVariant();
         }
     }
   else  //Vertical header
     return QString("%1").arg(section + 1);
 }
bool CQCompartmentDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 277 of file CQCompartmentDM.cpp.
References ListViews::ADD, COL_NAME_COMPARTMENTS, ListViews::COMPARTMENT, CQBaseDataModel::createNewName(), CCopasiRootContainer::getDatamodelList(), CModelEntity::getKey(), CQBaseDataModel::notifyGUI(), and TO_UTF8.
 {
   beginInsertRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       CCompartment * pComp = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->createCompartment(TO_UTF8(createNewName("compartment", COL_NAME_COMPARTMENTS)));
       emit notifyGUI(ListViews::COMPARTMENT, ListViews::ADD, pComp->getKey());
     }
   endInsertRows();
   return true;
 }
bool CQCompartmentDM::removeRows (QModelIndexList rows, const QModelIndex & index = QModelIndex())
Definition at line 327 of file CQCompartmentDM.cpp.
References C_INVALID_INDEX, CQMessageBox::confirmDelete(), FROM_UTF8, CModel::getCompartments(), CCopasiRootContainer::getDatamodelList(), CCompartment::getDeletedObjects(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CQBaseDataModel::isDefaultRow(), and CQBaseDataModel::removeRow().
Referenced by CQCompartmentsWidget::deleteSelectedCompartments().
 {
   if (rows.isEmpty())
     return false;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return false;
 //Build the list of pointers to items to be deleted
 //before actually deleting any item.
   QList <CCompartment *> pCompartments;
   QModelIndexList::const_iterator i;
   for (i = rows.begin(); i != rows.end(); ++i)
     {
       if (!isDefaultRow(*i) && pModel->getCompartments()[(*i).row()])
         pCompartments.append(pModel->getCompartments()[(*i).row()]);
     }
   QList <CCompartment *>::const_iterator j;
   for (j = pCompartments.begin(); j != pCompartments.end(); ++j)
     {
       CCompartment * pCompartment = *j;
       size_t delRow =
         pModel->getCompartments().CCopasiVector< CCompartment >::getIndex(pCompartment);
       if (delRow != C_INVALID_INDEX)
         {
           QMessageBox::StandardButton choice =
             CQMessageBox::confirmDelete(NULL, "compartment",
                                         FROM_UTF8(pCompartment->getObjectName()),
                                         pCompartment->getDeletedObjects());
           if (choice == QMessageBox::Ok)
             removeRow((int) delRow);
         }
     }
   return true;
 }
bool CQCompartmentDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 292 of file CQCompartmentDM.cpp.
References CCopasiVector< T >::begin(), ListViews::COMPARTMENT, ListViews::DELETE, CModel::getCompartments(), CCopasiRootContainer::getDatamodelList(), ListViews::METABOLITE, and CQBaseDataModel::notifyGUI().
 {
   if (rows <= 0)
     return true;
   beginRemoveRows(QModelIndex(), position, position + rows - 1);
   CModel * pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   std::vector< std::string > DeletedKeys;
   DeletedKeys.resize(rows);
   std::vector< std::string >::iterator itDeletedKey;
   std::vector< std::string >::iterator endDeletedKey = DeletedKeys.end();
   CCopasiVector< CCompartment >::const_iterator itRow = pModel->getCompartments().begin() + position;
   for (itDeletedKey = DeletedKeys.begin(); itDeletedKey != endDeletedKey; ++itDeletedKey, ++itRow)
     {
       *itDeletedKey = (*itRow)->getKey();
     }
   for (itDeletedKey = DeletedKeys.begin(); itDeletedKey != endDeletedKey; ++itDeletedKey)
     {
       (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->removeCompartment(*itDeletedKey);
       emit notifyGUI(ListViews::COMPARTMENT, ListViews::DELETE, *itDeletedKey);
       emit notifyGUI(ListViews::COMPARTMENT, ListViews::DELETE, "");
       emit notifyGUI(ListViews::METABOLITE, ListViews::DELETE, ""); //Refresh all as there may be dependencies.
     }
   endRemoveRows();
   return true;
 }
int CQCompartmentDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 49 of file CQCompartmentDM.cpp.
References CCopasiRootContainer::getDatamodelList().
Referenced by data(), and CQCompartmentsWidget::deleteSelectedCompartments().
 {
   return (int)(*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getCompartments().size() + 1;
 }
bool CQCompartmentDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 235 of file CQCompartmentDM.cpp.
References ListViews::CHANGE, COL_IVOLUME, COL_NAME_COMPARTMENTS, COL_TYPE_COMPARTMENTS, ListViews::COMPARTMENT, CQBaseDataModel::createNewName(), data(), FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CModelEntity::getKey(), CQBaseDataModel::insertRow(), CQBaseDataModel::isDefaultRow(), mItemToType, CQBaseDataModel::notifyGUI(), CModelEntity::setInitialValue(), CCopasiObject::setObjectName(), CModelEntity::setStatus(), CModelEntity::StatusName, and TO_UTF8.
 {
   if (index.isValid() && role == Qt::EditRole)
     {
       bool defaultRow = isDefaultRow(index);
       if (defaultRow)
         {
           if (index.column() == COL_TYPE_COMPARTMENTS)
             {
               if (index.data().toString() != QString(FROM_UTF8(CModelEntity::StatusName[mItemToType[value.toInt()]])))
                 insertRow();
               else
                 return false;
             }
           else if (index.data() != value)
             insertRow();
           else
             return false;
         }
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       CCompartment *pComp = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getCompartments()[index.row()];
       if (index.column() == COL_NAME_COMPARTMENTS)
         pComp->setObjectName(TO_UTF8(value.toString()));
       else if (index.column() == COL_TYPE_COMPARTMENTS)
         pComp->setStatus((CModelEntity::Status) mItemToType[value.toInt()]);
       else if (index.column() == COL_IVOLUME)
         pComp->setInitialValue(value.toDouble());
       if (defaultRow && this->index(index.row(), COL_NAME_COMPARTMENTS).data().toString() == "compartment")
         pComp->setObjectName(TO_UTF8(createNewName("compartment", COL_NAME_COMPARTMENTS)));
       emit dataChanged(index, index);
       emit notifyGUI(ListViews::COMPARTMENT, ListViews::CHANGE, pComp->getKey());
     }
   return true;
 }
Member Data Documentation
std::vector< unsigned C_INT32 > CQCompartmentDM::mItemToType protected
A vector mapping the item index to a model valu type
Definition at line 58 of file CQCompartmentDM.h.
Referenced by CQCompartmentDM(), data(), getItemToType(), and setData().
QStringList CQCompartmentDM::mTypes protected
Definition at line 54 of file CQCompartmentDM.h.
Referenced by CQCompartmentDM(), and getTypes().
The documentation for this class was generated from the following files:
CQCompartmentDM.h
CQCompartmentDM.cpp