COPASI API: main.cpp File Reference
CopasiUI/main.cpp File Reference
#include <stdexcept>
#include <locale.h>
#include <QtGui/QApplication>
#include "copasi.h"
#include "UI/CQCopasiApplication.h"
#include "UI/copasiui3window.h"
#include "UI/DataModelGUI.h"
#include "UI/CQMessageBox.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "function/CFunctionDB.h"
#include "function/CFunction.h"
#include "commandline/COptionParser.h"
#include "commandline/COptions.h"
Macros
#define COPASI_MAIN
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
#define COPASI_MAIN
Definition at line 20 of file CopasiUI/main.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 47 of file CopasiUI/main.cpp.
References CCopasiRootContainer::addDatamodel(), COptions::compareValue(), CopasiUI3Window::create(), CQMessageBox::critical(), CCopasiRootContainer::destroy(), FROM_UTF8, COptions::getValue(), CCopasiRootContainer::init(), pdelete, and CQCopasiApplication::setMainWindow().
 {
   // Fix for Issue 1377, if locale is not set to the default one, some
   // numbers will be displayed in the systems default locale:
   setlocale(LC_ALL, "C");
   // Fix of Issue with Text centering on OSX Mavericks
 #ifdef Q_OS_MACX
   if (QSysInfo::MacintoshVersion > QSysInfo::MV_10_8)
     {
       // fix Mac OS X 10.9 (mavericks) font issue
       // https://bugreports.qt-project.org/browse/QTBUG-32789
       QFont::insertSubstitution(".Lucida Grande UI", "Lucida Grande");
     }
 #endif
   CQCopasiApplication a(argc, argv);
   a.setAttribute(Qt::AA_DontShowIconsInMenus, false);
   Q_INIT_RESOURCE(copasi);
   // Parse the commandline options
   try
     {
       // Create the root container.
       CCopasiRootContainer::init(argc, argv, true);
     }
   catch (copasi::option_error & msg)
     {
       CQMessageBox::critical(NULL, "Initialization Error",
                              msg.what(),
                              QMessageBox::Ok , QMessageBox::Ok);
       return 1;
     }
 #ifdef Darwin
   std::string PluginDir;
   COptions::getValue("CopasiDir", PluginDir);
   PluginDir += "/Contents/plugins";
   QApplication::setLibraryPaths(QStringList(FROM_UTF8(PluginDir)));
 #endif // Darwin
   // Create the global data model.
   CCopasiRootContainer::addDatamodel();
   // Create the main application window.
   CopasiUI3Window *pWindow = CopasiUI3Window::create();
 #ifdef COPASI_SBW_INTEGRATION
   if (COptions::compareValue("SBWRegister", true))
     goto finish;
 #endif // COPASI_SBW_INTEGRATION
   if (pWindow != NULL)
     {
       a.setMainWindow(pWindow);
       a.exec();
     }
 finish:
   try // To suppress any access violations during destruction works only under Windows
     {
       pdelete(pWindow);
       CCopasiRootContainer::destroy();
     }
   catch (...)
     {}
   return 0;
 }