COPASI API: COptMethodGA Class Reference
COptMethodGA Class Reference
#include <COptMethodGA.h>
Public Member Functions
COptMethodGA (const COptMethodGA &src, const CCopasiContainer *pParent=NULL)
virtual bool optimise ()
virtual ~COptMethodGA ()
Public Member Functions inherited from COptMethod
COptMethod (const COptMethod &src, const CCopasiContainer *pParent=NULL)
bool isBounded (void)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (COptProblem *problem)
virtual ~COptMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
virtual bool cleanup ()
COptMethodGA (const CCopasiContainer *pParent=NULL)
bool creation (size_t first, size_t last=std::numeric_limits< size_t >::max())
bool crossover (const CVector< C_FLOAT64 > &parent1, const CVector< C_FLOAT64 > &parent2, CVector< C_FLOAT64 > &child1, CVector< C_FLOAT64 > &child2)
bool evaluate (const CVector< C_FLOAT64 > &individual)
size_t fittest ()
virtual bool initialize ()
void initObjects ()
bool mutate (CVector< C_FLOAT64 > &individual)
bool replicate ()
bool select ()
bool serializepop (size_t first, size_t last)
bool swap (size_t from, size_t to)
Private Attributes
size_t mBestIndex
C_FLOAT64 mBestValue
CVector< bool > mCrossOver
CVector< bool > mCrossOverFalse
C_FLOAT64 mEvaluationValue
unsigned C_INT32 mGeneration
unsigned C_INT32 mGenerations
size_t mhGenerations
std::vector< CVector
< C_FLOAT64 > * > mIndividual
CVector< size_t > mLosses
C_FLOAT64 mMutationVarians
CVector< size_t > mPivot
unsigned C_INT32 mPopulationSize
CPermutation * mpPermutation
CRandom * mpRandom
CVector< C_FLOAT64 > mValue
size_t mVariableSize
Friends
COptMethod * COptMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from COptMethod
static COptMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::RandomSearch)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from COptMethod
COptMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from COptMethod
const bool mBounds
const std::vector< COptItem * > * mpOptContraints
const std::vector< COptItem * > * mpOptItem
COptProblem * mpOptProblem
COptTask * mpParentTask
const std::vector
< UpdateMethod * > * mpSetCalculateVariable
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 29 of file COptMethodGA.h.
Constructor & Destructor Documentation
COptMethodGA::COptMethodGA (const COptMethodGA & src, const CCopasiContainer * pParent = NULL)
Copy Constructor
Parameters
const COptMethodGA & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 64 of file COptMethodGA.cpp.
References initObjects().
                                                             :
   COptMethod(src, pParent),
   mGenerations(0),
   mPopulationSize(0),
   mpRandom(NULL),
   mVariableSize(0),
   mIndividual(0),
   mCrossOverFalse(0),
   mCrossOver(0),
   mEvaluationValue(std::numeric_limits< C_FLOAT64 >::max()),
   mValue(0),
   mpPermutation(NULL),
   mLosses(0),
   mPivot(0),
   mMutationVarians(0.1),
   mBestValue(std::numeric_limits< C_FLOAT64 >::max()),
   mBestIndex(C_INVALID_INDEX),
   mGeneration(0)
 {initObjects();}
COptMethodGA::~COptMethodGA () virtual
Destructor
Definition at line 85 of file COptMethodGA.cpp.
References cleanup().
 {cleanup();}
COptMethodGA::COptMethodGA (const CCopasiContainer * pParent = NULL) private
Default Constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 36 of file COptMethodGA.cpp.
References CCopasiParameterGroup::addParameter(), C_INT32, initObjects(), CRandom::mt19937, and CCopasiParameter::UINT.
                                                           :
   COptMethod(CCopasiTask::optimization, CCopasiMethod::GeneticAlgorithm, pParent),
   mGenerations(0),
   mPopulationSize(0),
   mpRandom(NULL),
   mVariableSize(0),
   mIndividual(0),
   mCrossOverFalse(0),
   mCrossOver(0),
   mEvaluationValue(std::numeric_limits< C_FLOAT64 >::max()),
   mValue(0),
   mpPermutation(NULL),
   mLosses(0),
   mPivot(0),
   mMutationVarians(0.1),
   mBestValue(std::numeric_limits< C_FLOAT64 >::max()),
   mBestIndex(C_INVALID_INDEX),
   mGeneration(0)
 {
   addParameter("Number of Generations", CCopasiParameter::UINT, (unsigned C_INT32) 200);
   addParameter("Population Size", CCopasiParameter::UINT, (unsigned C_INT32) 20);
   addParameter("Random Number Generator", CCopasiParameter::UINT, (unsigned C_INT32) CRandom::mt19937);
   addParameter("Seed", CCopasiParameter::UINT, (unsigned C_INT32) 0);
   initObjects();
 }
Member Function Documentation
bool COptMethodGA::cleanup () private virtual
Cleanup arrays and pointers.
Returns
bool success
Reimplemented from COptMethod.
Definition at line 468 of file COptMethodGA.cpp.
References mIndividual, mpPermutation, mpRandom, and pdelete.
Referenced by initialize(), optimise(), and ~COptMethodGA().
 {
   size_t i;
   pdelete(mpRandom);
   pdelete(mpPermutation);
   for (i = 0; i < mIndividual.size(); i++)
     pdelete(mIndividual[i]);
   return true;
 }
bool COptMethodGA::creation (size_t first, size_t last = std::numeric_limits<size_t>::max()) private
Initialise the population
Parameters
size_t first
size_t last (default: population size)
Returns
bool continue
Definition at line 337 of file COptMethodGA.cpp.
References C_FLOAT64, COptItem::checkConstraint(), evaluate(), COptItem::getLowerBoundValue(), CRandom::getRandomCC(), COptItem::getUpperBoundValue(), max, mEvaluationValue, min, mIndividual, mPopulationSize, mpRandom, mValue, and mVariableSize.
Referenced by optimise().
 {
   size_t Last = std::min(last, (size_t) mPopulationSize);
   size_t i;
   size_t j;
   C_FLOAT64 mn;
   C_FLOAT64 mx;
   C_FLOAT64 la;
   bool Continue = true;
   for (i = first; i < Last && Continue; i++)
     {
       for (j = 0; j < mVariableSize; j++)
         {
           // calculate lower and upper bounds
           COptItem & OptItem = *(*mpOptItem)[j];
           mn = *OptItem.getLowerBoundValue();
           mx = *OptItem.getUpperBoundValue();
           C_FLOAT64 & mut = (*mIndividual[i])[j];
           try
             {
               // determine if linear or log scale
               if ((mn < 0.0) || (mx <= 0.0))
                 mut = mn + mpRandom->getRandomCC() * (mx - mn);
               else
                 {
                   la = log10(mx) - log10(std::max(mn, std::numeric_limits< C_FLOAT64 >::min()));
                   if (la < 1.8)
                     mut = mn + mpRandom->getRandomCC() * (mx - mn);
                   else
                     mut = pow(10.0, log10(std::max(mn, std::numeric_limits< C_FLOAT64 >::min())) + la * mpRandom->getRandomCC());
                 }
             }
           catch (...)
             {
               mut = (mx + mn) * 0.5;
             }
           // force it to be within the bounds
           switch (OptItem.checkConstraint(mut))
             {
               case - 1:
                 mut = *OptItem.getLowerBoundValue();
                 break;
               case 1:
                 mut = *OptItem.getUpperBoundValue();
                 break;
             }
           // We need to set the value here so that further checks take
           // account of the value.
           (*(*mpSetCalculateVariable)[j])(mut);
         }
       // calculate its fitness
       Continue &= evaluate(*mIndividual[i]);
       mValue[i] = mEvaluationValue;
     }
   return Continue;
 }
bool COptMethodGA::crossover (const CVector< C_FLOAT64 > & parent1, const CVector< C_FLOAT64 > & parent2, CVector< C_FLOAT64 > & child1, CVector< C_FLOAT64 > & child2) private
Parameters
const CVector< C_FLOAT64 > & parent1
const CVector< C_FLOAT64 > & parent2
CVector< C_FLOAT64 > & child1
CVector< C_FLOAT64 > & child2
Definition at line 159 of file COptMethodGA.cpp.
References C_INT32, CRandom::getRandomU(), mCrossOver, mCrossOverFalse, mpRandom, and mVariableSize.
Referenced by replicate().
 {
   size_t i, crp;
   size_t nCross = 0;
   mCrossOver = mCrossOverFalse;
   if (mVariableSize > 1)
     nCross = mpRandom->getRandomU((unsigned C_INT32)(mVariableSize / 2));
   if (nCross == 0)
     {
       // if less than 0 just copy parent to child
       child1 = parent1;
       child2 = parent2;
       return true;
     }
   // choose cross over points;
   // We do not mind if a crossover point gets drawn twice
   for (i = 0; i < nCross; i++)
     {
       crp = mpRandom->getRandomU((unsigned C_INT32)(mVariableSize - 1));
       mCrossOver[crp] = true;
     }
   const CVector< C_FLOAT64 > * pParent1 = & parent1;
   const CVector< C_FLOAT64 > * pParent2 = & parent2;
   const CVector< C_FLOAT64 > * pTmp;
   for (i = 0; i < mVariableSize; i++)
     {
       if (mCrossOver[i])
         {
           pTmp = pParent1;
           pParent1 = pParent2;
           pParent2 = pTmp;
         }
       child1[i] = (*pParent1)[i];
       child2[i] = (*pParent2)[i];
     }
   return true;
 }
bool COptMethodGA::evaluate (const CVector< C_FLOAT64 > & individual) private
Evaluate the fitness of one individual
Parameters
const CVector< C_FLOAT64 > & individual
Returns
bool continue
Definition at line 89 of file COptMethodGA.cpp.
References COptProblem::calculate(), COptProblem::checkFunctionalConstraints(), COptProblem::getCalculateValue(), mEvaluationValue, and COptMethod::mpOptProblem.
Referenced by creation(), optimise(), and replicate().
 {
   bool Continue = true;
   // We do not need to check whether the parametric constraints are fulfilled
   // since the parameters are created within the bounds.
   // evaluate the fitness
   Continue &= mpOptProblem->calculate();
   // check whether the functional constraints are fulfilled
   if (!mpOptProblem->checkFunctionalConstraints())
     mEvaluationValue = std::numeric_limits<C_FLOAT64>::infinity();
   else
     mEvaluationValue = mpOptProblem->getCalculateValue();
   return Continue;
 }
size_t COptMethodGA::fittest (void) private
Find the best individual at this generation
Returns
size_t fittest
Definition at line 283 of file COptMethodGA.cpp.
References C_FLOAT64, C_INVALID_INDEX, max, mLosses, mPopulationSize, and mValue.
Referenced by optimise().
 {
   size_t i, BestIndex = C_INVALID_INDEX;
   C_FLOAT64 BestValue = std::numeric_limits< C_FLOAT64 >::max();
   for (i = 0; i < mPopulationSize && !mLosses[i]; i++)
     if (mValue[i] < BestValue)
       {
         BestIndex = i;
         BestValue = mValue[i];
       }
   return BestIndex;
 }
bool COptMethodGA::initialize () private virtual
Initialize arrays and pointer.
Returns
bool success
Reimplemented from COptMethod.
Definition at line 413 of file COptMethodGA.cpp.
References CProcessReport::addItem(), cleanup(), CRandom::createGenerator(), CProcessReport::finishItem(), CCopasiParameter::getValue(), COptMethod::initialize(), mBestValue, mCrossOver, mCrossOverFalse, mGeneration, mGenerations, mhGenerations, mIndividual, mLosses, mMutationVarians, CCopasiMethod::mpCallBack, COptMethod::mpOptItem, mPopulationSize, mpPermutation, mpRandom, mValue, mVariableSize, CCopasiParameter::Value::pUINT, and CVector< CType >::resize().
Referenced by optimise().
 {
   cleanup();
   size_t i;
   if (!COptMethod::initialize())
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhGenerations);
       return false;
     }
   mGenerations = * getValue("Number of Generations").pUINT;
   mGeneration = 0;
   if (mpCallBack)
     mhGenerations =
       mpCallBack->addItem("Current Generation",
                           mGeneration,
                           & mGenerations);
   mGeneration++;
   mPopulationSize = * getValue("Population Size").pUINT;
   mpRandom =
     CRandom::createGenerator(* (CRandom::Type *) getValue("Random Number Generator").pUINT,
                              * getValue("Seed").pUINT);
   mVariableSize = mpOptItem->size();
   mIndividual.resize(2 * mPopulationSize);
   for (i = 0; i < 2 * mPopulationSize; i++)
     mIndividual[i] = new CVector< C_FLOAT64 >(mVariableSize);
   mCrossOverFalse.resize(mVariableSize);
   mCrossOverFalse = false;
   mCrossOver.resize(mVariableSize);
   mValue.resize(2 * mPopulationSize);
   mValue = std::numeric_limits<C_FLOAT64>::infinity();
   mBestValue = std::numeric_limits<C_FLOAT64>::infinity();
   mpPermutation = new CPermutation(mpRandom, mPopulationSize);
   mLosses.resize(2 * mPopulationSize);
   // Initialize the variance for mutations
   mMutationVarians = 0.1;
   return true;
 }
void COptMethodGA::initObjects () private
Initialize contained objects.
Definition at line 408 of file COptMethodGA.cpp.
References CCopasiContainer::addObjectReference(), mGeneration, and CCopasiObject::ValueInt.
Referenced by COptMethodGA().
 {
   addObjectReference("Current Generation", mGeneration, CCopasiObject::ValueInt);
 }
bool COptMethodGA::mutate (CVector< C_FLOAT64 > & individual) private
Mutate one individual
Parameters
CVector< C_FLOAT64 > & individual
Returns
bool success
Definition at line 126 of file COptMethodGA.cpp.
References C_FLOAT64, COptItem::checkConstraint(), COptItem::getLowerBoundValue(), CRandom::getRandomNormal(), COptItem::getUpperBoundValue(), mMutationVarians, mpRandom, and mVariableSize.
Referenced by replicate().
 {
   size_t j;
   // mutate the parameters
   for (j = 0; j < mVariableSize; j++)
     {
       COptItem & OptItem = *(*mpOptItem)[j];
       C_FLOAT64 & mut = individual[j];
       // calculate the mutatated parameter
       mut *= mpRandom->getRandomNormal(1, mMutationVarians);
       // force it to be within the bounds
       switch (OptItem.checkConstraint(mut))
         {
           case - 1:
             mut = *OptItem.getLowerBoundValue();
             break;
           case 1:
             mut = *OptItem.getUpperBoundValue();
             break;
         }
       // We need to set the value here so that further checks take
       // account of the value.
       (*(*mpSetCalculateVariable)[j])(mut);
     }
   return true;
 }
bool COptMethodGA::optimise (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback. @ return success;
Reimplemented from COptMethod.
Definition at line 481 of file COptMethodGA.cpp.
References C_FLOAT64, C_INVALID_INDEX, COptItem::checkConstraint(), cleanup(), creation(), COutputInterface::DURING, evaluate(), CProcessReport::finishItem(), fittest(), COptItem::getLowerBoundValue(), COptItem::getStartValue(), COptItem::getUpperBoundValue(), initialize(), mBestIndex, mBestValue, mEvaluationValue, mGeneration, mGenerations, mhGenerations, mIndividual, CCopasiMethod::mpCallBack, COptMethod::mpOptProblem, mPopulationSize, COptMethod::mpParentTask, mValue, mVariableSize, CCopasiTask::output(), CProcessReport::progressItem(), replicate(), select(), serializepop(), and COptProblem::setSolution().
 {
   bool Continue = true;
   if (!initialize())
     {
       // initialisation failed, we exit
       if (mpCallBack)
         mpCallBack->finishItem(mhGenerations);
       return false;
     }
   // Counters to determine whether the optimization process has stalled
   // They count the number of generations without advances.
   size_t Stalled, Stalled10, Stalled30, Stalled50;
   Stalled = Stalled10 = Stalled30 = Stalled50 = 0;
   size_t i;
   // initialise the population
   // first individual is the initial guess
   for (i = 0; i < mVariableSize; i++)
     {
       C_FLOAT64 & mut = (*mIndividual[0])[i];
       COptItem & OptItem = *(*mpOptItem)[i];
       mut = OptItem.getStartValue();
       // force it to be within the bounds
       switch (OptItem.checkConstraint(mut))
         {
           case - 1:
             mut = *OptItem.getLowerBoundValue();
             break;
           case 1:
             mut = *OptItem.getUpperBoundValue();
             break;
         }
       // We need to set the value here so that further checks take
       // account of the value.
       (*(*mpSetCalculateVariable)[i])(mut);
     }
   Continue &= evaluate(*mIndividual[0]);
   mValue[0] = mEvaluationValue;
   if (!isnan(mEvaluationValue))
     {
       // and store that value
       mBestValue = mValue[0];
       Continue &= mpOptProblem->setSolution(mBestValue, *mIndividual[0]);
       // We found a new best value lets report it.
       mpParentTask->output(COutputInterface::DURING);
     }
   // the others are random
   Continue &= creation(1, mPopulationSize);
 #ifdef DEBUG_OPT
   serializepop(0, mPopulationSize);
 #endif
   Continue &= select();
   mBestIndex = fittest();
   if (mBestIndex != C_INVALID_INDEX &&
       mValue[mBestIndex] < mBestValue)
     {
       // and store that value
       mBestValue = mValue[mBestIndex];
       Continue = mpOptProblem->setSolution(mBestValue, *mIndividual[mBestIndex]);
       // We found a new best value lets report it.
       mpParentTask->output(COutputInterface::DURING);
     }
   // test if the user wants to stop, and do so if needed
   if (!Continue)
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhGenerations);
       cleanup();
       return true;
     }
   // ITERATE FOR gener GENERATIONS
   for (mGeneration = 2;
        mGeneration <= mGenerations && Continue;
        mGeneration++, Stalled++, Stalled10++, Stalled30++, Stalled50++)
     {
       // perturb the population if we have stalled for a while
       if (Stalled > 50 && Stalled50 > 50)
         {
           Continue &= creation((size_t)(mPopulationSize / 2),
                                mPopulationSize);
           Stalled10 = Stalled30 = Stalled50 = 0;
         }
       else if (Stalled > 30 && Stalled30 > 30)
         {
           Continue &= creation((size_t)(mPopulationSize * 0.7),
                                mPopulationSize);
           Stalled10 = Stalled30 = 0;
         }
       else if (Stalled > 10 && Stalled10 > 10)
         {
           Continue &= creation((size_t)(mPopulationSize * 0.9),
                                mPopulationSize);
           Stalled10 = 0;
         }
       // replicate the individuals
       else
         Continue &= replicate();
       // select the most fit
       Continue &= select();
       // get the index of the fittest
       mBestIndex = fittest();
       if (mBestIndex != C_INVALID_INDEX &&
           mValue[mBestIndex] < mBestValue)
         {
     // reset the stalled counters, since we made progress this time
           Stalled = Stalled10 = Stalled30 = Stalled50 = 0;
     // keep best value
           mBestValue = mValue[mBestIndex];
           // pass the current best value upstream
     Continue &= mpOptProblem->setSolution(mBestValue, *mIndividual[mBestIndex]);
           // We found a new best value lets report it.
           mpParentTask->output(COutputInterface::DURING);
         }
       if (mpCallBack)
         Continue &= mpCallBack->progressItem(mhGenerations);
 #ifdef DEBUG_OPT
       serializepop(0, mPopulationSize);
 #endif
     }
   if (mpCallBack)
     mpCallBack->finishItem(mhGenerations);
   cleanup();
   return true;
 }
bool COptMethodGA::replicate (void) private
Replicate the individuals with crossover
Returns
bool continue
Definition at line 211 of file COptMethodGA.cpp.
References crossover(), evaluate(), mEvaluationValue, mIndividual, mPopulationSize, mpPermutation, mutate(), mValue, CPermutation::next(), and CPermutation::shuffle().
Referenced by optimise().
 {
   size_t i;
   bool Continue = true;
   // generate a random order for the parents
   mpPermutation->shuffle();
   // reproduce in consecutive pairs
   for (i = 0; i < mPopulationSize / 2; i++)
     crossover(*mIndividual[mpPermutation->next()],
               *mIndividual[mpPermutation->next()],
               *mIndividual[mPopulationSize + i * 2],
               *mIndividual[mPopulationSize + i * 2 + 1]);
   // check if there is one left over and just copy it
   if (mPopulationSize % 2 > 0)
     *mIndividual[2 * mPopulationSize - 1] = *mIndividual[mPopulationSize - 1];
   // mutate the offspring
   for (i = mPopulationSize; i < 2 * mPopulationSize && Continue; i++)
     {
       mutate(*mIndividual[i]);
       Continue &= evaluate(*mIndividual[i]);
       mValue[i] = mEvaluationValue;
     }
   return Continue;
 }
bool COptMethodGA::select () private
Select surviving population
Returns
bool success
Definition at line 242 of file COptMethodGA.cpp.
References applyPartialPivot(), CVectorCore< CType >::array(), C_INT32, CRandom::getRandomU(), mLosses, mPivot, mPopulationSize, mpRandom, mValue, partialSortWithPivot(), and swap().
Referenced by optimise().
 {
   size_t i, j, nopp, opp;
   size_t TotalPopulation = 2 * mPopulationSize;
   // tournament competition
   mLosses = 0; // Set all wins to 0.
   // compete with ~ 20% of the TotalPopulation
   nopp = std::max<size_t>(1, mPopulationSize / 5);
   // parents and offspring are all in competition
   for (i = 0; i < TotalPopulation; i++)
     for (j = 0; j < nopp; j++)
       {
         // get random opponent
         do
           {
             opp = mpRandom->getRandomU((unsigned C_INT32)(TotalPopulation - 1));
           }
         while (i == opp);
         if (mValue[i] < mValue[opp])
           mLosses[opp]++;
         else
           mLosses[i]++;
       }
   // selection of top mPopulationSize winners
   partialSortWithPivot(mLosses.array(),
                        mLosses.array() + mPopulationSize,
                        mLosses.array() + TotalPopulation,
                        mPivot);
   FSwapClass<COptMethodGA, size_t, bool> Swap(this, &COptMethodGA::swap);
   applyPartialPivot(mPivot, mPopulationSize, Swap);
   return true;
 }
bool COptMethodGA::serializepop (size_t first, size_t last) private
Serialize the population for debug
Parameters
size_t first
size_t last (default: population size)
Returns
bool success
Referenced by optimise().
bool COptMethodGA::swap (size_t from, size_t to) private
Swap individuals from and to
Parameters
size_t from
size_t to
Returns
bool success
Definition at line 108 of file COptMethodGA.cpp.
References C_FLOAT64, mIndividual, mLosses, and mValue.
Referenced by select().
 {
   CVector< C_FLOAT64 > * pTmp = mIndividual[to];
   mIndividual[to] = mIndividual[from];
   mIndividual[from] = pTmp;
   C_FLOAT64 dTmp = mValue[to];
   mValue[to] = mValue[from];
   mValue[from] = dTmp;
   size_t iTmp = mLosses[to];
   mLosses[to] = mLosses[from];
   mLosses[from] = iTmp;
   return true;
 }
Friends And Related Function Documentation
COptMethod* COptMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
size_t COptMethodGA::mBestIndex private
Definition at line 220 of file COptMethodGA.h.
Referenced by optimise().
C_FLOAT64 COptMethodGA::mBestValue private
Definition at line 219 of file COptMethodGA.h.
Referenced by initialize(), and optimise().
CVector< bool > COptMethodGA::mCrossOver private
Vector of crossover points.
Definition at line 187 of file COptMethodGA.h.
Referenced by crossover(), and initialize().
CVector< bool > COptMethodGA::mCrossOverFalse private
Vector used to initialize the crossover point to false
Definition at line 182 of file COptMethodGA.h.
Referenced by crossover(), and initialize().
C_FLOAT64 COptMethodGA::mEvaluationValue private
The value of the last evaluation.
Definition at line 192 of file COptMethodGA.h.
Referenced by creation(), evaluate(), optimise(), and replicate().
unsigned C_INT32 COptMethodGA::mGeneration private
Definition at line 221 of file COptMethodGA.h.
Referenced by initialize(), initObjects(), and optimise().
unsigned C_INT32 COptMethodGA::mGenerations private
number of generations
Definition at line 152 of file COptMethodGA.h.
Referenced by initialize(), and optimise().
size_t COptMethodGA::mhGenerations private
Handle to the process report item "Current Generation"
Definition at line 157 of file COptMethodGA.h.
Referenced by initialize(), and optimise().
std::vector< CVector < C_FLOAT64 > * > COptMethodGA::mIndividual private
for array of individuals w/ candidate values for the parameters
Definition at line 177 of file COptMethodGA.h.
Referenced by cleanup(), creation(), initialize(), optimise(), replicate(), and swap().
CVector< size_t > COptMethodGA::mLosses private
number of losses of each individual in the tournament
Definition at line 207 of file COptMethodGA.h.
Referenced by fittest(), initialize(), select(), and swap().
C_FLOAT64 COptMethodGA::mMutationVarians private
variance for mutations
Definition at line 217 of file COptMethodGA.h.
Referenced by initialize(), and mutate().
CVector<size_t> COptMethodGA::mPivot private
The pivot vector used for sorting
Definition at line 212 of file COptMethodGA.h.
Referenced by select().
unsigned C_INT32 COptMethodGA::mPopulationSize private
size of the population
Definition at line 162 of file COptMethodGA.h.
Referenced by creation(), fittest(), initialize(), optimise(), replicate(), and select().
CPermutation* COptMethodGA::mpPermutation private
A permutation of integers used to create the informants;
Definition at line 202 of file COptMethodGA.h.
Referenced by cleanup(), initialize(), and replicate().
CRandom* COptMethodGA::mpRandom private
a pointer to the randomnumber generator.
Definition at line 167 of file COptMethodGA.h.
Referenced by cleanup(), creation(), crossover(), initialize(), mutate(), and select().
CVector< C_FLOAT64 > COptMethodGA::mValue private
array of values of objective function f/ individuals
Definition at line 197 of file COptMethodGA.h.
Referenced by creation(), fittest(), initialize(), optimise(), replicate(), select(), and swap().
size_t COptMethodGA::mVariableSize private
number of parameters
Definition at line 172 of file COptMethodGA.h.
Referenced by creation(), crossover(), initialize(), mutate(), and optimise().
The documentation for this class was generated from the following files:
COptMethodGA.h
COptMethodGA.cpp