COPASI API: QTimeCourseAnimation Class Reference
QTimeCourseAnimation Class Reference
Public Member Functions
size_t getIndex (const CTimeSeries *series, const std::string &cn)
double getMax (const CTimeSeries *series, size_t index=C_INVALID_INDEX)
virtual void getScales (std::vector< qreal > &scales, int step)
double getValue (const CTimeSeries *series, const std::string &cn, int step)
virtual void initialize (const CCopasiDataModel &dataModel)
Public Member Functions inherited from CQCopasiAnimation
virtual void applyToScene (CQLayoutScene &scene, int step)
CQCopasiAnimation ()
std::vector
< CQEffectDescription * > & getEntries ()
virtual int getNumSteps ()
ScaleMode getScaleMode () const
virtual void removeFromScene (CQLayoutScene &scene)
void setScaleMode (ScaleMode mode)
virtual ~CQCopasiAnimation ()
Protected Attributes
std::map< std::string,
std::string > keyMap
Protected Attributes inherited from CQCopasiAnimation
std::vector
< CQEffectDescription * > mEntries
ScaleMode mMode
int mNumSteps
const CCopasiDataModel * mpDataModel
Additional Inherited Members
Public Types inherited from CQCopasiAnimation
enum ScaleMode { Global, Individual }
Detailed Description
Animation that displays the concentrations per time
Definition at line 160 of file CQAnimationWindow.cpp.
Member Function Documentation
size_t QTimeCourseAnimation::getIndex (const CTimeSeries * series, const std::string & cn) inline
Definition at line 189 of file CQAnimationWindow.cpp.
References C_INVALID_INDEX, CTimeSeries::getKey(), CTimeSeries::getNumVariables(), and keyMap.
Referenced by getScales(), and getValue().
   {
     const std::string& key = keyMap[cn];
     for (size_t i = 0; i < series->getNumVariables(); ++i)
       if (series->getKey(i) == key)
         return i;
     return C_INVALID_INDEX;
   }
double QTimeCourseAnimation::getMax (const CTimeSeries * series, size_t index = C_INVALID_INDEX) inline
Definition at line 163 of file CQAnimationWindow.cpp.
References C_INVALID_INDEX, CTimeSeries::getData(), CTimeSeries::getNumVariables(), CTimeSeries::getRecordedSteps(), and max.
Referenced by getScales().
   {
     double max = 0;
     if (index != C_INVALID_INDEX)
       {
         for (size_t i = 0; i < series->getRecordedSteps(); ++i)
           {
             max = qMax(max, series->getData(i, index));
           }
       }
     else
       {
         for (size_t i = 0; i < series->getRecordedSteps(); ++i)
           {
             for (size_t j = 0; j < series->getNumVariables(); ++j)
               {
                 max = qMax(max, series->getData(i, j));
               }
           }
       }
     return max;
   }
virtual void QTimeCourseAnimation::getScales (std::vector< qreal > & scales, int step) inline virtual
Reimplemented from CQCopasiAnimation.
Definition at line 205 of file CQAnimationWindow.cpp.
References getIndex(), getMax(), CTimeSeries::getRecordedSteps(), CCopasiDataModel::getTaskList(), CTrajectoryTask::getTimeSeries(), getValue(), CQCopasiAnimation::Global, CQCopasiAnimation::Individual, max, CQCopasiAnimation::mEntries, CQCopasiAnimation::mMode, CQCopasiAnimation::mNumSteps, and CQCopasiAnimation::mpDataModel.
   {
     if (mpDataModel == NULL) return;
     CTrajectoryTask *task = dynamic_cast< CTrajectoryTask * >((*mpDataModel->getTaskList())["Time-Course"]);
     if (task == NULL) return;
     const CTimeSeries* series = &task->getTimeSeries();
     if (series == NULL) return;
     mNumSteps = series->getRecordedSteps();
     if (series->getRecordedSteps() < (size_t)step)
       return;
     double max = mMode == CQCopasiAnimation::Global ? getMax(series) : 0;
     for (size_t i = 0; i < mEntries.size(); ++i)
       {
         if (mMode == CQCopasiAnimation::Individual)
           max  = getMax(series, getIndex(series, mEntries[i]->getCN()));
         double value = getValue(series, mEntries[i]->getCN(), step);
         scales.push_back(value / max);
       }
   }
double QTimeCourseAnimation::getValue (const CTimeSeries * series, const std::string & cn, int step) inline
Definition at line 200 of file CQAnimationWindow.cpp.
References CTimeSeries::getData(), and getIndex().
Referenced by getScales().
   {
     return series->getData(step, getIndex(series, cn));
   }
virtual void QTimeCourseAnimation::initialize (const CCopasiDataModel & dataModel) inline virtual
Implements CQCopasiAnimation.
Definition at line 234 of file CQAnimationWindow.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CTimeSeries::getRecordedSteps(), CCopasiDataModel::getTaskList(), CTrajectoryTask::getTimeSeries(), keyMap, CQCopasiAnimation::mEntries, CQCopasiAnimation::mNumSteps, CQCopasiAnimation::mpDataModel, and CQEffectDescription::Scale.
   {
     mpDataModel = &dataModel;
     const CModel& model = *dataModel.getModel();
     const CCopasiVector< CMetab > & metabs = model.getMetabolites();
     CCopasiVector< CMetab >::const_iterator it = metabs.begin();
     while (it != metabs.end())
       {
         mEntries.push_back(new CQEffectDescription((*it)->getCN(), CQEffectDescription::Scale));
         keyMap[(*it)->getCN()] = (*it)->getKey();
         ++it;
       }
     // initialize number of steps
     CTrajectoryTask *task = dynamic_cast< CTrajectoryTask * >((*mpDataModel->getTaskList())["Time-Course"]);
     if (task == NULL) return;
     const CTimeSeries* series = &task->getTimeSeries();
     if (series == NULL) return;
     mNumSteps = series->getRecordedSteps();
   }
Member Data Documentation
std::map<std::string, std::string> QTimeCourseAnimation::keyMap protected
Definition at line 260 of file CQAnimationWindow.cpp.
Referenced by getIndex(), and initialize().
The documentation for this class was generated from the following file:
CQAnimationWindow.cpp