COPASI API: ScrollBar Class Reference
ScrollBar Class Reference
#include <scrollbar.h>
Public Slots
virtual void moveSlider (double min, double max)
virtual void setBase (double min, double max)
Signals
void sliderMoved (Qt::Orientation, double, double)
void valueChanged (Qt::Orientation, double, double)
Public Member Functions
int extent () const
bool isInverted () const
bool isLogScale () const
double maxBaseValue () const
double maxSliderValue () const
double minBaseValue () const
double minSliderValue () const
ScrollBar (QWidget *parent=NULL)
ScrollBar (Qt::Orientation, QWidget *parent=NULL)
ScrollBar (double minBase, double maxBase, bool logscale, Qt::Orientation o, QWidget *parent=NULL)
void setInverted (bool)
void setLogScale (bool l)
Protected Member Functions
double mapFromTick (int) const
int mapToTick (double) const
void sliderRange (int value, double &min, double &max) const
Private Slots
void catchSliderMoved (int value)
void catchValueChanged (int value)
Private Member Functions
void init ()
Private Attributes
int d_baseTicks
bool d_inverted
double d_maxBase
double d_minBase
bool mLogScale
Detailed Description
Definition at line 28 of file scrollbar.h.
Constructor & Destructor Documentation
ScrollBar::ScrollBar (QWidget * parent = NULL)
Definition at line 31 of file scrollbar.cpp.
References init().
                                     :
   QScrollBar(parent),
   mLogScale(false)
 {
   init();
 }
ScrollBar::ScrollBar (Qt::Orientation o, QWidget * parent = NULL)
Definition at line 38 of file scrollbar.cpp.
References init().
                                      :
   QScrollBar(o, parent),
   mLogScale(false)
 {
   init();
 }
ScrollBar::ScrollBar (double minBase, double maxBase, bool logscale, Qt::Orientation o, QWidget * parent = NULL)
Definition at line 46 of file scrollbar.cpp.
References init(), moveSlider(), and setBase().
                                                       :
   QScrollBar(o, parent),
   mLogScale(logscale)
 {
   init();
   setBase(minBase, maxBase);
   moveSlider(minBase, maxBase);
 }
Member Function Documentation
void ScrollBar::catchSliderMoved (int value) private slot
Definition at line 211 of file scrollbar.cpp.
References max, min, sliderMoved(), and sliderRange().
Referenced by init().
 {
   double min, max;
   sliderRange(value, min, max);
   emit sliderMoved(orientation(), min, max);
 }
void ScrollBar::catchValueChanged (int value) private slot
Definition at line 204 of file scrollbar.cpp.
References max, min, sliderRange(), and valueChanged().
Referenced by init().
 {
   double min, max;
   sliderRange(value, min, max);
   emit valueChanged(orientation(), min, max);
 }
int ScrollBar::extent () const
Definition at line 218 of file scrollbar.cpp.
Referenced by ScrollZoomer::layoutScrollBars(), and ScrollZoomer::updateScrollBars().
 {
 #if QT_VERSION < 0x040000
   return style().pixelMetric(QStyle::PM_ScrollBarExtent, this);
 #else
   QStyleOptionSlider opt;
   opt.init(this);
   opt.subControls = QStyle::SC_None;
   opt.activeSubControls = QStyle::SC_None;
   opt.orientation = orientation();
   opt.minimum = minimum();
   opt.maximum = maximum();
   opt.sliderPosition = sliderPosition();
   opt.sliderValue = value();
   opt.singleStep = singleStep();
   opt.pageStep = pageStep();
   opt.upsideDown = invertedAppearance();
   if (orientation() == Qt::Horizontal)
     opt.state |= QStyle::State_Horizontal;
   return style()->pixelMetric(QStyle::PM_ScrollBarExtent, &opt, this);
 #endif
 }
void ScrollBar::init () private
Definition at line 56 of file scrollbar.cpp.
References catchSliderMoved(), catchValueChanged(), d_baseTicks, d_inverted, d_maxBase, d_minBase, moveSlider(), sliderMoved(), and valueChanged().
Referenced by ScrollBar().
 {
   d_inverted = orientation() == Qt::Vertical;
   d_baseTicks = 1000000;
   d_minBase = 0.0;
   d_maxBase = 1.0;
   moveSlider(d_minBase, d_maxBase);
   connect(this, SIGNAL(sliderMoved(int)), SLOT(catchSliderMoved(int)));
   connect(this, SIGNAL(valueChanged(int)), SLOT(catchValueChanged(int)));
 }
bool ScrollBar::isInverted () const
Definition at line 77 of file scrollbar.cpp.
References d_inverted.
Referenced by moveSlider(), and sliderRange().
 {
   return d_inverted;
 }
bool ScrollBar::isLogScale () const
Definition at line 248 of file scrollbar.cpp.
References mLogScale.
 {
   return mLogScale;
 }
double ScrollBar::mapFromTick (int tick) const protected
Definition at line 199 of file scrollbar.cpp.
References d_baseTicks, d_maxBase, and d_minBase.
Referenced by sliderRange().
 {
   return d_minBase + (d_maxBase - d_minBase) * tick / d_baseTicks;
 }
int ScrollBar::mapToTick (double v) const protected
Definition at line 194 of file scrollbar.cpp.
References d_baseTicks, d_maxBase, and d_minBase.
Referenced by moveSlider().
 {
   return (int)((v - d_minBase) / (d_maxBase - d_minBase) * d_baseTicks);
 }
double ScrollBar::maxBaseValue () const
Definition at line 153 of file scrollbar.cpp.
References d_maxBase, and mLogScale.
 {
   if (mLogScale)
     return exp(d_maxBase);
   else
     return d_maxBase;
 }
double ScrollBar::maxSliderValue () const
Definition at line 186 of file scrollbar.cpp.
References max, and sliderRange().
Referenced by setBase(), and setInverted().
 {
   double max, dummy;
   sliderRange(value(), dummy, max);
   return max;
 }
double ScrollBar::minBaseValue () const
Definition at line 145 of file scrollbar.cpp.
References d_minBase, and mLogScale.
 {
   if (mLogScale)
     return exp(d_minBase);
   else
     return d_minBase;
 }
double ScrollBar::minSliderValue () const
Definition at line 178 of file scrollbar.cpp.
References min, and sliderRange().
Referenced by setBase(), and setInverted().
 {
   double min, dummy;
   sliderRange(value(), min, dummy);
   return min;
 }
void ScrollBar::moveSlider (double min, double max) virtual slot
Definition at line 99 of file scrollbar.cpp.
References d_baseTicks, d_maxBase, d_minBase, isInverted(), mapToTick(), and mLogScale.
Referenced by init(), ScrollBar(), setBase(), setInverted(), and ScrollZoomer::updateScrollBars().
 {
   if (mLogScale)
     {
       min = log(min);
       max = log(max);
     }
   int sliderTicks;
   sliderTicks = qRound((max - min) /
                        (d_maxBase - d_minBase) * d_baseTicks);
   // setRange initiates a valueChanged of the scrollbars
   // in some situations. So we block
   // and unblock the signals.
   blockSignals(true);
   setRange(sliderTicks / 2, d_baseTicks - sliderTicks / 2);
   int steps = sliderTicks / 200;
   if (steps <= 0)
     steps = 1;
 #if QT_VERSION < 0x040000
   setSteps(steps, sliderTicks);
 #else
   setSingleStep(steps);
   setPageStep(sliderTicks);
 #endif
   int tick;
   tick = mapToTick(min + (max - min) / 2);
   if (isInverted())
     tick = d_baseTicks - tick;
 #if QT_VERSION < 0x040000
   directSetValue(tick);
   rangeChange();
 #else
   setSliderPosition(tick);
 #endif
   blockSignals(false);
 }
void ScrollBar::setBase (double min, double max) virtual slot
Definition at line 82 of file scrollbar.cpp.
References d_maxBase, d_minBase, max, maxSliderValue(), min, minSliderValue(), mLogScale, and moveSlider().
Referenced by ScrollBar(), and ScrollZoomer::updateScrollBars().
 {
   if (mLogScale)
     {
       min = log(min);
       max = log(max);
     }
   if (min != d_minBase || max != d_maxBase)
     {
       d_minBase = min;
       d_maxBase = max;
       moveSlider(minSliderValue(), maxSliderValue());
     }
 }
void ScrollBar::setInverted (bool inverted)
Definition at line 68 of file scrollbar.cpp.
References d_inverted, maxSliderValue(), minSliderValue(), and moveSlider().
Referenced by ScrollZoomer::updateScrollBars().
 {
   if (d_inverted != inverted)
     {
       d_inverted = inverted;
       moveSlider(minSliderValue(), maxSliderValue());
     }
 }
void ScrollBar::setLogScale (bool l)
Definition at line 243 of file scrollbar.cpp.
References mLogScale.
Referenced by ScrollZoomer::updateScrollBars().
 {
   mLogScale = l;
 }
void ScrollBar::sliderMoved (Qt::Orientation , double , double) signal
Referenced by catchSliderMoved(), and init().
void ScrollBar::sliderRange (int value, double & min, double & max) const protected
Definition at line 161 of file scrollbar.cpp.
References d_baseTicks, isInverted(), mapFromTick(), and mLogScale.
Referenced by catchSliderMoved(), catchValueChanged(), maxSliderValue(), and minSliderValue().
 {
   if (isInverted())
     value = d_baseTicks - value;
   const int visibleTicks = pageStep();
   min = mapFromTick(value - visibleTicks / 2);
   max = mapFromTick(value + visibleTicks / 2);
   if (mLogScale)
     {
       min = exp(min);
       max = exp(max);
     }
 }
void ScrollBar::valueChanged (Qt::Orientation , double , double) signal
Referenced by catchValueChanged(), and init().
Member Data Documentation
int ScrollBar::d_baseTicks private
Definition at line 75 of file scrollbar.h.
Referenced by init(), mapFromTick(), mapToTick(), moveSlider(), and sliderRange().
bool ScrollBar::d_inverted private
Definition at line 72 of file scrollbar.h.
Referenced by init(), isInverted(), and setInverted().
double ScrollBar::d_maxBase private
Definition at line 74 of file scrollbar.h.
Referenced by init(), mapFromTick(), mapToTick(), maxBaseValue(), moveSlider(), and setBase().
double ScrollBar::d_minBase private
Definition at line 73 of file scrollbar.h.
Referenced by init(), mapFromTick(), mapToTick(), minBaseValue(), moveSlider(), and setBase().
bool ScrollBar::mLogScale private
Definition at line 76 of file scrollbar.h.
Referenced by isLogScale(), maxBaseValue(), minBaseValue(), moveSlider(), setBase(), setLogScale(), and sliderRange().
The documentation for this class was generated from the following files:
scrollbar.h
scrollbar.cpp