COPASI API: CArrayAnnotation Class Reference
CArrayAnnotation Class Reference
#include <CAnnotatedMatrix.h>
Public Types
enum Mode {
OBJECTS, VECTOR, VECTOR_ON_THE_FLY, STRINGS,
NUMBERS
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
const CObjectInterface * addElementReference (CCopasiAbstractArray::index_type index) const
const CObjectInterface * addElementReference (C_INT32 u, C_INT32 v) const
const CObjectInterface * addElementReference (C_INT32 u) const
void appendElementReferences (std::set< const CCopasiObject * > &objects) const
CCopasiAbstractArray * array ()
const CCopasiAbstractArray * array () const
CArrayAnnotation (const std::string &name, const CCopasiContainer *pParent, CCopasiAbstractArray *array, const bool &adopt)
bool createAnnotationsCNFromCopasiVector (size_t d, const CCopasiContainer *v) const
void createNumbers (size_t d) const
size_t dimensionality () const
const std::vector
< CRegisteredObjectName > & getAnnotationsCN (size_t d) const
const std::vector< std::string > & getAnnotationsString (size_t d, bool display=true) const
Mode getDefaultMode () const
const std::string & getDescription () const
const std::string & getDimensionDescription (size_t d) const
Mode getMode (size_t d) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
bool isEmpty ()
virtual void print (std::ostream *ostream) const
void printRecursively (std::ostream &ostream, size_t level, CCopasiAbstractArray::index_type &index, const std::vector< std::vector< std::string > > &display) const
void reDimensionalize (size_t d)
void resize ()
void resizeOneDimension (size_t d)
void setAnnotationCN (size_t d, size_t i, const std::string cn)
void setAnnotationString (size_t d, size_t i, const std::string s)
void setArray (CCopasiAbstractArray *a)
void setCopasiVector (size_t d, const CCopasiContainer *v)
void setDescription (const std::string &s)
void setDimensionDescription (size_t d, const std::string &s)
void setMode (size_t d, Mode m)
void setMode (Mode m)
CCopasiAbstractArray::index_type size () const
virtual ~CArrayAnnotation ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
CArrayAnnotation ()
CArrayAnnotation (const CArrayAnnotation &)
CArrayAnnotation & operator= (const CArrayAnnotation &)
Private Attributes
std::vector< std::vector
< CRegisteredObjectName > > mAnnotationsCN
std::vector< std::vector
< std::string > > mAnnotationsString
std::vector< const
CCopasiContainer * > mCopasiVectors
Mode mDefaultMode
std::string mDescription
bool mDestructArray
std::vector< std::string > mDimensionDescriptions
std::vector< Mode > mModes
CCopasiAbstractArray * mpArray
Friends
std::ostream & operator<< (std::ostream &os, const CArrayAnnotation &o)
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
This class contains the annotations to a n-dimensional array. Annotations can be provided for the array as such, for each of the dimensions, and for each of the indices (rows, columns, ...)
Definition at line 44 of file CAnnotatedMatrix.h.
Member Enumeration Documentation
enum CArrayAnnotation::Mode
The annotation to an array can work in different modes. The mode for each dimension can be changed independently.
OBJECTS: The CNs for the rows, cols, ... of the array are given explicitly
VECTOR: A CCopasiVector is provided from which the CNs are generated at the time the vector is set
VECTOR_ON_THE_FLY: A CCopasiVector is provided, but the CNs are generated every time the annotations are retrieved (so that they are always up to date).
STRINGS: The annotations for the rows, cols, ... are given explicitly as strings.
NUMBERS: The rows, cols, ... of the array are only annotation with running numbers (starting with 0)-
Enumerator
OBJECTS
VECTOR
VECTOR_ON_THE_FLY
STRINGS
NUMBERS
Definition at line 66 of file CAnnotatedMatrix.h.
   {
     OBJECTS,
     VECTOR,
     VECTOR_ON_THE_FLY,
     STRINGS,
     NUMBERS
   };
Constructor & Destructor Documentation
CArrayAnnotation::CArrayAnnotation (const std::string & name, const CCopasiContainer * pParent, CCopasiAbstractArray * array, const bool & adopt)
Definition at line 36 of file CAnnotatedMatrix.cpp.
References mpArray, and resize().
     : CCopasiContainer(name, pParent, "Array" , CCopasiObject::Array),
     mpArray(array),
     mDestructArray(adopt),
     mDefaultMode(OBJECTS)
 {
   assert(mpArray);
   resize();
   //addObjectReference("Annotated Matrix", *this, CCopasiObject::ValueDbl);
 }
CArrayAnnotation::~CArrayAnnotation () virtual
Definition at line 52 of file CAnnotatedMatrix.cpp.
References mDestructArray, mpArray, and pdelete.
 {
   if (mDestructArray)
     pdelete(mpArray);
 }
CArrayAnnotation::CArrayAnnotation () private
CArrayAnnotation::CArrayAnnotation (const CArrayAnnotation &) private
Member Function Documentation
const CObjectInterface * CArrayAnnotation::addElementReference (CCopasiAbstractArray::index_type index) const
an object that will act as a reference to one element of an array will be created and inserted as a child of the array annotation. Basically most of the work will be done by getObject(). If the element already exists, the existing element will be returned.
Definition at line 251 of file CAnnotatedMatrix.cpp.
References getObject().
Referenced by addElementReference(), CCopasiSelectionDialog::chooseCellMatrix(), and CObjectLists::getListOfConstObjects().
 {
   //generate the index string
   std::string tmp;
   std::ostringstream indexString;
   size_t ii = 0;
   for (ii = 0; ii < index.size(); ++ii)
     {
       indexString << "[" << index[ii] << "]";
     }
   //handle zero-dimensional arrays
   if (index.size() == 0)
     indexString << "[.]";
   return this->getObject(indexString.str());
 }
const CObjectInterface * CArrayAnnotation::addElementReference (C_INT32 u, C_INT32 v) const
a convenience function for 2-dimensional arrays.
Definition at line 270 of file CAnnotatedMatrix.cpp.
References addElementReference().
 {
   CCopasiAbstractArray::index_type index;
   index.push_back(u);
   index.push_back(v);
   return addElementReference(index);
 }
const CObjectInterface * CArrayAnnotation::addElementReference (C_INT32 u) const
a convenience function for 1-dimensional arrays.
Definition at line 278 of file CAnnotatedMatrix.cpp.
References addElementReference().
 {
   CCopasiAbstractArray::index_type index;
   index.push_back(u);
   return addElementReference(index);
 }
void CArrayAnnotation::appendElementReferences (std::set< const CCopasiObject * > & objects) const
Appends all element references to the set of objects
Parameters
std::set< const CCopasiObject * > & objects
Definition at line 285 of file CAnnotatedMatrix.cpp.
References CCopasiContainer::mObjects.
Referenced by DataModelGUI::buildChangedObjects(), CModel::buildInitialRefreshSequence(), and CModel::buildInitialSequence().
 {
   objectMap::const_iterator it = mObjects.begin();
   objectMap::const_iterator end = mObjects.end();
   for (; it != end; ++it)
     if (dynamic_cast<const CArrayElementReference *>(it->second) != NULL)
       objects.insert(it->second);
   return;
 }
CCopasiAbstractArray* CArrayAnnotation::array () inline
Definition at line 122 of file CAnnotatedMatrix.h.
References mpArray.
Referenced by CQArrayAnnotationsWidget::fillBarChart(), CQArrayAnnotationsWidget::fillTable0(), CQArrayAnnotationsWidget::fillTable1(), CQArrayAnnotationsWidget::fillTableN(), CArrayElementReference::getValuePointer(), operator<<(), and printRecursively().
   {return mpArray;}
const CCopasiAbstractArray* CArrayAnnotation::array () const inline
Definition at line 125 of file CAnnotatedMatrix.h.
References mpArray.
   {return mpArray;}
bool CArrayAnnotation::createAnnotationsCNFromCopasiVector (size_t d, const CCopasiContainer * v) const
generate the list of CNs from the COPASI vector v. v needs to be a CCopasiVector (or derived from it)!
Definition at line 185 of file CAnnotatedMatrix.cpp.
References CCopasiAbstractArray::dimensionality(), CCopasiObject::isNameVector(), CCopasiObject::isVector(), mAnnotationsCN, mpArray, and CCopasiVector< T >::size().
Referenced by getAnnotationsCN(), getAnnotationsString(), and setCopasiVector().
 {
   if (!v) return false;
   if (!(v->isVector() || v->isNameVector())) return false;
   if (d >= mpArray->dimensionality()) return false;
   //now we know we have a vector. A CCopasiVector[N/S], hopefully, so that the following cast is valid:
   const CCopasiVector< CCopasiObject > * pVector =
     reinterpret_cast<const CCopasiVector< CCopasiObject > * >(v);
   mAnnotationsCN[d].resize(pVector->size());
   //if (pVector->size() < mAnnotations[d].size()) return false;
   size_t i;
   for (i = 0; i < mAnnotationsCN[d].size(); ++i)
     {
       if (!(*pVector)[i])
         return false;
       else
         mAnnotationsCN[d][i] = (*pVector)[i]->getCN();
     }
   return true;
 }
void CArrayAnnotation::createNumbers (size_t d) const
Definition at line 215 of file CAnnotatedMatrix.cpp.
Referenced by getAnnotationsString().
 {
   //TODO
 }
size_t CArrayAnnotation::dimensionality () const
Definition at line 79 of file CAnnotatedMatrix.cpp.
References mModes.
Referenced by CCopasiSelectionDialog::chooseCellMatrix(), CQArrayAnnotationsWidget::fillTable(), CObjectLists::getListOfConstObjects(), CArrayElementReference::getValuePointer(), CQArrayAnnotationsWidget::initSelectionTable(), isEmpty(), operator<<(), printRecursively(), CQMatrixDialog::setArray(), and CQArrayAnnotationsWidget::setArrayAnnotation().
 {
   return mModes.size();
 }
const std::vector< CRegisteredObjectName > & CArrayAnnotation::getAnnotationsCN (size_t d) const
returns the vector of CNs that correspond to the rows, columns, ... of the array. This method must not be called if the mode for the dimension d is STRINGS or NUMBERS
Definition at line 117 of file CAnnotatedMatrix.cpp.
References createAnnotationsCNFromCopasiVector(), mAnnotationsCN, mCopasiVectors, mModes, NUMBERS, STRINGS, and VECTOR_ON_THE_FLY.
 {
   assert(d < mModes.size());
   assert(mModes[d] != STRINGS);
   assert(mModes[d] != NUMBERS);
   if (mModes[d] == VECTOR_ON_THE_FLY)
     createAnnotationsCNFromCopasiVector(d, mCopasiVectors[d]);
   return mAnnotationsCN[d];
 }
const std::vector< std::string > & CArrayAnnotation::getAnnotationsString (size_t d, bool display = true) const
This returns strings that annotate the rows, columns, ... of the array. If the mode is OBJECTS, VECTOR, or VECTOR_ON_THE_FLY the display argument determines if the object name or the object display name is used. Note that this method returns a reference. The content that the reference points to may be changes by later calls to the getAnnotationsCN() method with the same value for d. Specifically if you use this method to obtain a reference to the list of display names and then call the method again to get the plain object names, the first reference will after that also point to the plain object names.
Definition at line 129 of file CAnnotatedMatrix.cpp.
References createAnnotationsCNFromCopasiVector(), createNumbers(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectName(), mAnnotationsCN, mAnnotationsString, mCopasiVectors, mModes, NUMBERS, OBJECTS, VECTOR, and VECTOR_ON_THE_FLY.
Referenced by CQArrayAnnotationsWidget::fillBarChart(), CQArrayAnnotationsWidget::fillTable1(), CQArrayAnnotationsWidget::fillTableN(), CQArrayAnnotationsWidget::initSelectionTable(), operator<<(), and CQMatrixDialog::setArray().
 {
   assert(d < mModes.size());
   //generate CNs (if necessary)
   if (mModes[d] == VECTOR_ON_THE_FLY)
     createAnnotationsCNFromCopasiVector(d, mCopasiVectors[d]);
   //generate DisplayNames
   if ((mModes[d] == VECTOR) || (mModes[d] == VECTOR_ON_THE_FLY) || (mModes[d] == OBJECTS))
     {
       size_t i, imax = mAnnotationsCN[d].size();
       mAnnotationsString[d].resize(imax);
       const CCopasiDataModel* pDataModel = getObjectDataModel();
       assert(pDataModel != NULL);
       for (i = 0; i < imax; ++i)
         {
           const CCopasiObject * obj = pDataModel->getDataObject(mAnnotationsCN[d][i]);
           if (obj)
             mAnnotationsString[d][i] =
               display ? obj->getObjectDisplayName() : obj->getObjectName();
           else
             mAnnotationsString[d][i] = "???";
         }
     }
   //generate Numbers
   if (mModes[d] == NUMBERS)
     createNumbers(d);
   // if the mode is STRINGS do nothing, mAnnotationsString is supposed to contain
   // the correct strings
   return mAnnotationsString[d];
 }
Mode CArrayAnnotation::getDefaultMode () const inline
Definition at line 143 of file CAnnotatedMatrix.h.
References mDefaultMode.
   {return mDefaultMode;};
const std::string & CArrayAnnotation::getDescription () const
Definition at line 179 of file CAnnotatedMatrix.cpp.
References mDescription.
Referenced by operator<<().
 {return mDescription;}
const std::string & CArrayAnnotation::getDimensionDescription (size_t d) const
Definition at line 167 of file CAnnotatedMatrix.cpp.
References mDimensionDescriptions.
Referenced by CQArrayAnnotationsWidget::initSelectionTable(), printRecursively(), CQMatrixDialog::setArray(), and CQArrayAnnotationsWidget::setArrayAnnotation().
 {
   assert(d < mDimensionDescriptions.size());
   return mDimensionDescriptions[d];
 }
Mode CArrayAnnotation::getMode (size_t d) const inline
Definition at line 140 of file CAnnotatedMatrix.h.
References mModes.
   {return mModes[d];};
const CObjectInterface * CArrayAnnotation::getObject (const CCopasiObjectName & cn) const virtual
Resolve a cn. Since this is an array, the CN can start with an index like "[2][3]". Since this is also a container, this is not necessarily the case.
Reimplemented from CCopasiContainer.
Definition at line 297 of file CAnnotatedMatrix.cpp.
References C_INT32, CCopasiObjectName::getElementName(), CCopasiContainer::getObject(), CCopasiObject::getObject(), CCopasiObjectName::getRemainder(), and CCopasiContainer::mObjects.
Referenced by addElementReference().
 {
   if (cn == "")
     {
       return this;
     }
   if (cn == "Property=DisplayName")
     {
       return CCopasiObject::getObject(cn);
     }
   //if there are no indices there could still be other children. This can be handled
   //by the container base class
   if (cn.getElementName(0, false) == "") //no indices
     return this->CCopasiContainer::getObject(cn);
   //so now we know we have indices. So we check if the array element reference
   //exists, if not we create it. Then getObject() of the element reference is called
   //with the remainder TODO
   /*
       //first get the array indices. At the moment only numerical indices...
       C_INT32 ii = 0;
       CCopasiArray::index_type index;
       while (cn.getElementName(ii, false) != "")
         {
           index.push_back(cn.getElementIndex(ii));
           ++ii;
         }
   */
   //first get the index string
   std::string tmp;
   std::string indexString;
   C_INT32 ii = 0;
   while ((tmp = cn.getElementName(ii, false)) != "")
     {
       indexString += "[" + tmp + "]";
       ++ii;
     }
   const CCopasiObject* pObject = NULL; //this will contain the element reference
   //if the reference object already exists, its name will be identical to the index
   std::pair< objectMap::const_iterator, objectMap::const_iterator > range =
     mObjects.equal_range(indexString);
   objectMap::const_iterator it = range.first;
   while (it != range.second && it->second->getObjectType() != "ElementReference") ++it;
   if (it == range.second) //not found
     {
       //create new element reference
       pObject = new CArrayElementReference(cn, this);
     }
   else
     {
       pObject = it->second;
     }
   if (pObject)
     return pObject->getObject(cn.getRemainder());
   else
     return NULL;
   /*
   if (index.size() != dimensionality())  //wrong number of indices for this array
     return NULL;
   size_t i;
   for (i = 0; i < dimensionality(); ++i)
     if (index[i] >= size()[i]) //out of range
       return NULL;
   */
   //TODO remove element children after resize
   //TODO check optimization expression widget...
 }
std::string CArrayAnnotation::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
generate a display name for the array annotation.
Reimplemented from CCopasiObject.
Definition at line 486 of file CAnnotatedMatrix.cpp.
References CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), and CCopasiObject::getObjectType().
 {
   std::string part;
   if (getObjectParent() && getObjectParent()->getObjectType() != "Model")
     part = getObjectParent()->getObjectDisplayName(regular, richtext) + ".";
   return part + getObjectName() + "[[]]";
 }
bool CArrayAnnotation::isEmpty ()
Check whether the size of array is greater than 0 for each dimension. Return true, if so. Otherwise, false.
Definition at line 467 of file CAnnotatedMatrix.cpp.
References dimensionality(), and size().
Referenced by CQSimpleSelectionTree::populateTree().
 {
   // either the dimension itself ...
   size_t dim = dimensionality();
   if (dim == 0) return false;
   // ... or the size of each dimension should be greater than zero.
   size_t idx = 0;
   for (idx = 0; idx < dim; idx++)
     {
       if (!size()[idx])
         return true;
     }
   return false;
 }
CArrayAnnotation& CArrayAnnotation::operator= (const CArrayAnnotation &) private
void CArrayAnnotation::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 379 of file CAnnotatedMatrix.cpp.
 {*ostream << *this;}
void CArrayAnnotation::printRecursively (std::ostream & ostream, size_t level, CCopasiAbstractArray::index_type & index, const std::vector< std::vector< std::string > > & display) const
Definition at line 384 of file CAnnotatedMatrix.cpp.
References array(), dimensionality(), getDimensionDescription(), size(), and SPC.
Referenced by operator<<().
 {
   size_t indent = 2 * (dimensionality() - 1 - level);
   if (level == 0) //only vector
     {
       ostream << SPC(indent) << "Rows: " << getDimensionDescription(level) << "\n";
       size_t imax = size()[0];
       for (index[0] = 0; index[0] < imax; ++index[0])
         ostream << SPC(indent) << display[0][index[0]] << "\t" << (*array())[index] << "\n";
     }
   else if (level == 1) //matrix
     {
       ostream << SPC(indent) << "Rows:    " << getDimensionDescription(level - 1) << "\n";
       ostream << SPC(indent) << "Columns: " << getDimensionDescription(level) << "\n";
       size_t imax = size()[0];
       size_t jmax = size()[1];
       ostream << SPC(indent);
       for (index[1] = 0; index[1] < jmax; ++index[1])
         ostream << "\t" << display[1][index[1]];
       ostream << "\n";
       for (index[0] = 0; index[0] < imax; ++index[0])
         {
           ostream << SPC(indent) << display[0][index[0]];
           for (index[1] = 0; index[1] < jmax; ++index[1])
             ostream << "\t" << (*array())[index];
           ostream << "\n";
         }
     }
   else //dimensionality > 2
     {
       size_t i, imax = size()[level];
       for (i = 0; i < imax; ++i)
         {
           ostream << SPC(indent) << getDimensionDescription(level) << ": " << display[level][i] << "\n";
           index[level] = i;
           printRecursively(ostream, level - 1, index, display);
         }
     }
 }
void CArrayAnnotation::reDimensionalize (size_t d)
resize the internal vectors according to the dimensionality of the array
Definition at line 221 of file CAnnotatedMatrix.cpp.
References mAnnotationsCN, mAnnotationsString, mCopasiVectors, mDefaultMode, mDimensionDescriptions, and mModes.
Referenced by resize().
 {
   mAnnotationsCN.resize(d);
   mAnnotationsString.resize(d);
   mDimensionDescriptions.resize(d);
   mCopasiVectors.resize(d);
   mModes.resize(d, mDefaultMode);
 }
void CArrayAnnotation::resize ()
adjust the dimensionality and size to that of the array
Definition at line 240 of file CAnnotatedMatrix.cpp.
References CCopasiAbstractArray::dimensionality(), mpArray, reDimensionalize(), and resizeOneDimension().
Referenced by CArrayAnnotation(), CFitProblem::initialize(), CSensMethod::initialize(), CSteadyStateTask::initialize(), CCSPMethod::predifineAnnotation(), CMCAMethod::resizeAllMatrices(), CLNAMethod::resizeAllMatrices(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), CCSPMethod::start(), CSteadyStateTask::updateMatrices(), and CModel::updateMatrixAnnotations().
 {
   assert(mpArray);
   reDimensionalize(mpArray->dimensionality());
   size_t i, imax = mpArray->dimensionality();
   for (i = 0; i < imax; ++i)
     resizeOneDimension(i);
 }
void CArrayAnnotation::resizeOneDimension (size_t d)
Definition at line 231 of file CAnnotatedMatrix.cpp.
References mAnnotationsCN, mAnnotationsString, mModes, mpArray, CCopasiAbstractArray::size(), and VECTOR.
Referenced by resize(), setAnnotationCN(), setAnnotationString(), and setMode().
 {
   if (mModes[d] != VECTOR)
     {
       mAnnotationsCN[d].resize(mpArray->size()[d]);
       mAnnotationsString[d].resize(mpArray->size()[d]);
     }
 }
void CArrayAnnotation::setAnnotationCN (size_t d, size_t i, const std::string cn)
Definition at line 95 of file CAnnotatedMatrix.cpp.
References mAnnotationsCN, mModes, OBJECTS, resizeOneDimension(), and size().
Referenced by CSensMethod::initialize(), CSteadyStateTask::initialize(), CSteadyStateTask::updateMatrices(), and CModel::updateMatrixAnnotations().
 {
   assert(d < mAnnotationsCN.size());
   assert(mModes[d] == OBJECTS);
   resizeOneDimension(d);
   assert(i < mAnnotationsCN[d].size());
   mAnnotationsCN[d][i] = cn;
 }
void CArrayAnnotation::setAnnotationString (size_t d, size_t i, const std::string s)
Definition at line 106 of file CAnnotatedMatrix.cpp.
References mAnnotationsString, mModes, resizeOneDimension(), size(), and STRINGS.
Referenced by CFitProblem::initialize(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), and CCSPMethod::setAnnotationM().
 {
   assert(d < mAnnotationsString.size());
   assert(mModes[d] == STRINGS);
   resizeOneDimension(d);
   assert(i < mAnnotationsString[d].size());
   mAnnotationsString[d][i] = s;
 }
void CArrayAnnotation::setArray (CCopasiAbstractArray * a)
let the ArrayAnnotation point to a different array. If you use this method without updating the annotations afterwards it is your responsibility to make sure the new array fits the existing annotation (in dimensionality and, if not in VECTOR_ON_THE_FLY mode, in size).
Definition at line 58 of file CAnnotatedMatrix.cpp.
References mpArray.
 {
   mpArray = a;
 }
void CArrayAnnotation::setCopasiVector (size_t d, const CCopasiContainer * v)
Associates a dimension d of the array with a CCopasiVector of CCopasiObjects. If the mode of the dimension d is VECTOR than the CNs of the objects in the vector are generated and stored immediately. If the mode is VECTOR_ON_THE_FLY the CNs are generated when getAnnotationsCN() or getAnnotationsString() is called.
Definition at line 84 of file CAnnotatedMatrix.cpp.
References createAnnotationsCNFromCopasiVector(), mCopasiVectors, mModes, VECTOR, and VECTOR_ON_THE_FLY.
Referenced by CModel::initObjects(), CCSPMethod::predifineAnnotation(), CMCAMethod::resizeAllMatrices(), CLNAMethod::resizeAllMatrices(), CILDMModifiedMethod::setAnnotationM(), CILDMMethod::setAnnotationM(), CCSPMethod::setAnnotationM(), and CCSPMethod::start().
 {
   assert(d < mCopasiVectors.size());
   assert((mModes[d] == VECTOR) || (mModes[d] == VECTOR_ON_THE_FLY));
   mCopasiVectors[d] = v;
   if (mModes[d] == VECTOR)
     createAnnotationsCNFromCopasiVector(d, mCopasiVectors[d]);
 }
void CArrayAnnotation::setDescription (const std::string & s)
Definition at line 182 of file CAnnotatedMatrix.cpp.
References mDescription.
Referenced by CILDMModifiedMethod::createAnnotationsM(), CILDMMethod::createAnnotationsM(), CCSPMethod::createAnnotationsM(), CLNAMethod::initObjects(), CMCAMethod::initObjects(), CSensProblem::initObjects(), CSteadyStateTask::initObjects(), and CModel::initObjects().
 {mDescription = s;}
void CArrayAnnotation::setDimensionDescription (size_t d, const std::string & s)
Definition at line 173 of file CAnnotatedMatrix.cpp.
References mDimensionDescriptions.
Referenced by CILDMModifiedMethod::createAnnotationsM(), CILDMMethod::createAnnotationsM(), CCSPMethod::createAnnotationsM(), CSensMethod::initialize(), CLNAMethod::initObjects(), CMCAMethod::initObjects(), CSteadyStateTask::initObjects(), and CModel::initObjects().
 {
   assert(d < mDimensionDescriptions.size());
   mDimensionDescriptions[d] = s;
 }
void CArrayAnnotation::setMode (size_t d, Mode m)
set the mode for the dimension d
Definition at line 63 of file CAnnotatedMatrix.cpp.
References mModes, and resizeOneDimension().
Referenced by CILDMModifiedMethod::createAnnotationsM(), CILDMMethod::createAnnotationsM(), CCSPMethod::createAnnotationsM(), CLNAMethod::initObjects(), CMCAMethod::initObjects(), CSensProblem::initObjects(), CSteadyStateTask::initObjects(), CModel::initObjects(), and setMode().
 {
   mModes[d] = m;
   resizeOneDimension(d);
 }
void CArrayAnnotation::setMode (Mode m)
set the mode for all dimensions, this also sets the default mode that is used when resizing the ArrayAnnotion to a larger dimensionality
Definition at line 69 of file CAnnotatedMatrix.cpp.
References mDefaultMode, mModes, and setMode().
 {
   mDefaultMode = m;
   size_t i;
   for (i = 0; i < mModes.size(); ++i)
     setMode(i, m);
 }
CCopasiAbstractArray::index_type CArrayAnnotation::size () const inline
Definition at line 148 of file CAnnotatedMatrix.h.
References mpArray, and CCopasiAbstractArray::size().
Referenced by CCopasiSelectionDialog::chooseCellMatrix(), CQArrayAnnotationsWidget::fillBarChart(), CQArrayAnnotationsWidget::fillTable1(), CQArrayAnnotationsWidget::fillTableN(), CObjectLists::getListOfConstObjects(), CArrayElementReference::getValuePointer(), isEmpty(), printRecursively(), setAnnotationCN(), setAnnotationString(), and CQMatrixDialog::setArray().
   {return mpArray->size();}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CArrayAnnotation & o) friend
Definition at line 438 of file CAnnotatedMatrix.cpp.
 {
   if (!o.array()) return os;
   //cache the display names
   std::vector<std::vector<std::string> > displaynames;
   size_t i;
   for (i = 0; i < o.dimensionality(); ++i)
     displaynames.push_back(o.getAnnotationsString(i));
   os << o.getObjectName() << std::endl;
   os << o.getDescription() << std::endl;
   CCopasiAbstractArray::index_type arraysize = o.array()->size();
   if (o.dimensionality() == 0)
     {
       //only one scalar value
       os << (*o.array())[arraysize] << std::endl;
     }
   else
     {
       o.printRecursively(os, o.dimensionality() - 1, arraysize, displaynames);
     }
   return os;
 }
Member Data Documentation
std::vector< std::vector<CRegisteredObjectName> > CArrayAnnotation::mAnnotationsCN mutable private
Definition at line 79 of file CAnnotatedMatrix.h.
Referenced by createAnnotationsCNFromCopasiVector(), getAnnotationsCN(), getAnnotationsString(), reDimensionalize(), resizeOneDimension(), and setAnnotationCN().
std::vector< std::vector<std::string> > CArrayAnnotation::mAnnotationsString mutable private
Definition at line 80 of file CAnnotatedMatrix.h.
Referenced by getAnnotationsString(), reDimensionalize(), resizeOneDimension(), and setAnnotationString().
std::vector< const CCopasiContainer * > CArrayAnnotation::mCopasiVectors private
Definition at line 83 of file CAnnotatedMatrix.h.
Referenced by getAnnotationsCN(), getAnnotationsString(), reDimensionalize(), and setCopasiVector().
Mode CArrayAnnotation::mDefaultMode private
This contains the default mode that is used if during a resize() the dimensionality is increased.
Definition at line 94 of file CAnnotatedMatrix.h.
Referenced by getDefaultMode(), reDimensionalize(), and setMode().
std::string CArrayAnnotation::mDescription private
Definition at line 96 of file CAnnotatedMatrix.h.
Referenced by getDescription(), and setDescription().
bool CArrayAnnotation::mDestructArray private
Definition at line 77 of file CAnnotatedMatrix.h.
Referenced by ~CArrayAnnotation().
std::vector< std::string > CArrayAnnotation::mDimensionDescriptions private
Definition at line 82 of file CAnnotatedMatrix.h.
Referenced by getDimensionDescription(), reDimensionalize(), and setDimensionDescription().
std::vector<Mode> CArrayAnnotation::mModes private
This contains the mode for the different dimensions
Definition at line 88 of file CAnnotatedMatrix.h.
Referenced by dimensionality(), getAnnotationsCN(), getAnnotationsString(), getMode(), reDimensionalize(), resizeOneDimension(), setAnnotationCN(), setAnnotationString(), setCopasiVector(), and setMode().
CCopasiAbstractArray* CArrayAnnotation::mpArray private
Definition at line 76 of file CAnnotatedMatrix.h.
Referenced by array(), CArrayAnnotation(), createAnnotationsCNFromCopasiVector(), resize(), resizeOneDimension(), setArray(), size(), and ~CArrayAnnotation().
The documentation for this class was generated from the following files:
CAnnotatedMatrix.h
CAnnotatedMatrix.cpp