COPASI API: CNormalLogicalItem Class Reference
CNormalLogicalItem Class Reference
#include <CNormalLogicalItem.h>
Public Types
enum Type {
TRUE, FALSE, EQ, NE,
LT, GT, GE, LE,
INVALID
}
Public Member Functions
CNormalLogicalItem ()
CNormalLogicalItem (const CNormalLogicalItem &src)
virtual CNormalBase * copy () const
CNormalFraction & getLeft ()
const CNormalFraction & getLeft () const
CNormalFraction & getRight ()
const CNormalFraction & getRight () const
Type getType () const
void negate ()
bool operator< (const CNormalLogicalItem &rhs) const
CNormalLogicalItem & operator= (const CNormalLogicalItem &src)
bool operator== (const CNormalLogicalItem &rhs) const
bool setLeft (const CNormalFraction &left)
bool setRight (const CNormalFraction &right)
void setType (Type type)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalLogicalItem ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Protected Attributes
CNormalFraction mLeft
CNormalFraction mRight
Type mType
Detailed Description
Definition at line 22 of file CNormalLogicalItem.h.
Member Enumeration Documentation
enum CNormalLogicalItem::Type
Enumerator
TRUE
FALSE
EQ
NE
LT
GT
GE
LE
INVALID
Definition at line 25 of file CNormalLogicalItem.h.
     {
       TRUE,
       FALSE,
       EQ,
       NE,
       LT,
       GT,
       GE,
       LE,
       INVALID
     };
Constructor & Destructor Documentation
CNormalLogicalItem::CNormalLogicalItem ()
Definition at line 24 of file CNormalLogicalItem.cpp.
Referenced by copy().
                                       : CNormalBase(), mType(CNormalLogicalItem::INVALID)
 {}
CNormalLogicalItem::CNormalLogicalItem (const CNormalLogicalItem & src)
Definition at line 27 of file CNormalLogicalItem.cpp.
                                                                    : CNormalBase(src), mType(src.mType), mLeft(src.mLeft), mRight(src.mRight)
 {}
CNormalLogicalItem::~CNormalLogicalItem () virtual
Definition at line 30 of file CNormalLogicalItem.cpp.
 {}
Member Function Documentation
CNormalBase * CNormalLogicalItem::copy () const virtual
Implements CNormalBase.
Definition at line 62 of file CNormalLogicalItem.cpp.
References CNormalLogicalItem().
   {
     return new CNormalLogicalItem(*this);
   }
CNormalFraction & CNormalLogicalItem::getLeft ()
Definition at line 126 of file CNormalLogicalItem.cpp.
References mLeft.
Referenced by convertToCEvaluationNode(), and normalize_variable_names().
 {
   return this->mLeft;
 }
const CNormalFraction & CNormalLogicalItem::getLeft () const
Definition at line 131 of file CNormalLogicalItem.cpp.
References mLeft.
   {
     return this->mLeft;
   }
CNormalFraction & CNormalLogicalItem::getRight ()
Definition at line 136 of file CNormalLogicalItem.cpp.
References mRight.
Referenced by convertToCEvaluationNode(), and normalize_variable_names().
 {
   return this->mRight;
 }
const CNormalFraction & CNormalLogicalItem::getRight () const
Definition at line 141 of file CNormalLogicalItem.cpp.
References mRight.
   {
     return this->mRight;
   }
CNormalLogicalItem::Type CNormalLogicalItem::getType () const
Definition at line 166 of file CNormalLogicalItem.cpp.
References mType.
Referenced by convertToCEvaluationNode(), CNormalLogical::eliminateNullItems(), and CNormalLogical::simplify().
   {
     return this->mType;
   }
void CNormalLogicalItem::negate ()
Definition at line 192 of file CNormalLogicalItem.cpp.
References EQ, FALSE, GE, GT, INVALID, LE, LT, mType, NE, and TRUE.
Referenced by CNormalLogical::eliminateNullItems(), CNormalLogical::generateCanonicalDNF(), and CNormalLogical::simplify().
 {
   switch (this->mType)
     {
     case TRUE:
       this->mType = FALSE;
       break;
     case FALSE:
       this->mType = TRUE;
       break;
     case EQ:
       this->mType = NE;
       break;
     case NE:
       this->mType = EQ;
       break;
     case GT:
       this->mType = LE;
       break;
     case LT:
       this->mType = GE;
       break;
     case LE:
       this->mType = GT;
       break;
     case GE:
       this->mType = LT;
       break;
     case INVALID:
       break;
     }
 }
bool CNormalLogicalItem::operator< (const CNormalLogicalItem & rhs) const
Definition at line 41 of file CNormalLogicalItem.cpp.
References mLeft, mRight, and mType.
   {
     bool result = false;
     if (this->mType < rhs.mType)
       {
         result = true;
       }
     else if (this->mType == rhs.mType)
       {
         if (this->mLeft == rhs.mLeft)
           {
             result = (this->mRight < rhs.mRight);
           }
         else
           {
             result = (this->mLeft < rhs.mLeft);
           }
       }
     return result;
   }
CNormalLogicalItem & CNormalLogicalItem::operator= (const CNormalLogicalItem & src)
Definition at line 33 of file CNormalLogicalItem.cpp.
References mLeft, mRight, and mType.
 {
   this->mType = src.mType;
   this->mLeft = src.mLeft;
   this->mRight = src.mRight;
   return *this;
 }
bool CNormalLogicalItem::operator== (const CNormalLogicalItem & rhs) const
Definition at line 225 of file CNormalLogicalItem.cpp.
References mLeft, mRight, and mType.
   {
     bool result = true;
     if (this->mType == rhs.mType)
       {
         result = (this->mLeft == rhs.mLeft);
         if (result)
           {
             result = (this->mRight == rhs.mRight);
           }
       }
     else
       {
         result = false;
       }
     return result;
   }
bool CNormalLogicalItem::setLeft (const CNormalFraction & left)
Definition at line 146 of file CNormalLogicalItem.cpp.
References FALSE, mLeft, mType, and TRUE.
Referenced by createLogicalItem().
 {
   bool result = false;
   if (this->mType != CNormalLogicalItem::TRUE && this->mType != CNormalLogicalItem::FALSE)
     {
       this->mLeft = left;
     }
   return result;
 }
bool CNormalLogicalItem::setRight (const CNormalFraction & right)
Definition at line 156 of file CNormalLogicalItem.cpp.
References FALSE, mRight, mType, and TRUE.
Referenced by createLogicalItem().
 {
   bool result = false;
   if (this->mType != CNormalLogicalItem::TRUE && this->mType != CNormalLogicalItem::FALSE)
     {
       this->mRight = right;
     }
   return result;
 }
void CNormalLogicalItem::setType (CNormalLogicalItem::Type type)
Definition at line 171 of file CNormalLogicalItem.cpp.
References FALSE, mLeft, mRight, mType, and TRUE.
Referenced by createLogicalItem(), CNormalLogical::eliminateNullItems(), and CNormalLogical::simplify().
 {
   switch (type)
     {
     case CNormalLogicalItem::TRUE:
     case CNormalLogicalItem::FALSE:
       this->mLeft = CNormalFraction();
       this->mRight = CNormalFraction();
       break;
     default:
       break;
     }
   this->mType = type;
 }
bool CNormalLogicalItem::simplify () virtual
Implements CNormalBase.
Definition at line 102 of file CNormalLogicalItem.cpp.
References GE, GT, LE, LT, mLeft, mRight, mType, and CNormalFraction::simplify().
Referenced by CNormalLogical::eliminateNullItems(), and CNormalLogical::generateCanonicalDNF().
 {
   bool result = true;
   if (this->mType == GT)
     {
       // replace by LT and switch mpLeft and mpRight
       this->mType = LT;
       CNormalFraction TMP = this->mLeft;
       this->mLeft = this->mRight;
       this->mRight = TMP;
     }
   else if (this->mType == GE)
     {
       // replace by LE and switch mpLeft and mpRight
       this->mType = LE;
       CNormalFraction TMP = this->mLeft;
       this->mLeft = this->mRight;
       this->mRight = TMP;
     }
   result &= this->mLeft.simplify();
   if (result) result &= this->mRight.simplify();
   return result;
 }
std::string CNormalLogicalItem::toString () const virtual
Implements CNormalBase.
Definition at line 67 of file CNormalLogicalItem.cpp.
References EQ, FALSE, GE, GT, INVALID, LE, LT, mLeft, mRight, mType, NE, and TRUE.
Referenced by operator<<().
   {
     std::ostringstream str;
     switch (this->mType)
       {
       case CNormalLogicalItem::TRUE:
         str << "TRUE";
         break;
       case CNormalLogicalItem::FALSE:
         str << "FALSE";
         break;
       case CNormalLogicalItem::EQ:
         str << "(" << this->mLeft << " == " << this->mRight << ")";
         break;
       case CNormalLogicalItem::NE:
         str << "(" << this->mLeft << " != " << this->mRight << ")";
         break;
       case CNormalLogicalItem::LT:
         str << "(" << this->mLeft << " < " << this->mRight << ")";
         break;
       case CNormalLogicalItem::GT:
         str << "(" << this->mLeft << " > " << this->mRight << ")";
         break;
       case CNormalLogicalItem::GE:
         str << "(" << this->mLeft << " >= " << this->mRight << ")";
         break;
       case CNormalLogicalItem::LE:
         str << "(" << this->mLeft << " <= " << this->mRight << ")";
         break;
       case INVALID:
         break;
       }
     return str.str();
   }
Member Data Documentation
CNormalFraction CNormalLogicalItem::mLeft protected
Definition at line 40 of file CNormalLogicalItem.h.
Referenced by getLeft(), operator<(), operator=(), operator==(), setLeft(), setType(), simplify(), and toString().
CNormalFraction CNormalLogicalItem::mRight protected
Definition at line 41 of file CNormalLogicalItem.h.
Referenced by getRight(), operator<(), operator=(), operator==(), setRight(), setType(), simplify(), and toString().
Type CNormalLogicalItem::mType protected
Definition at line 39 of file CNormalLogicalItem.h.
Referenced by getType(), negate(), operator<(), operator=(), operator==(), setLeft(), setRight(), setType(), simplify(), and toString().
The documentation for this class was generated from the following files:
CNormalLogicalItem.h
CNormalLogicalItem.cpp