COPASI API: test000022 Class Reference
test000022 Class Reference
#include <test000022.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_hasOnlySubstanceUnits ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_hasOnlySubstanceUnits)
CPPUNIT_TEST_SUITE (test000022)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000022.h.
Member Function Documentation
test000022::CPPUNIT_TEST (test_hasOnlySubstanceUnits) private
test000022::CPPUNIT_TEST_SUITE (test000022) private
test000022::CPPUNIT_TEST_SUITE_END () private
void test000022::setUp ()
Definition at line 36 of file test000022.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000022::tearDown ()
Definition at line 44 of file test000022.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000022::test_hasOnlySubstanceUnits ()
Definition at line 49 of file test000022.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, CChemEq::getCompartmentNumber(), CCopasiDataModel::getModel(), CChemEq::getModifiers(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CChemEq::getProducts(), CChemEq::getSubstrates(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, MODEL_STRING, CModel::number, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModelEntity::REACTIONS, CModel::s, and CCopasiVector< T >::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::number);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::REACTIONS);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::REACTIONS);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pModelValue->getExpressionPtr();
   // check the expression
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Concentration"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pA);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 2);
   const CReaction* pReaction1 = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction1 != NULL);
   CPPUNIT_ASSERT(pReaction1->isReversible() == false);
   // check the kinetic law
   const CFunction* pKineticFunction = pReaction1->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   const CMassAction* pMassAction = dynamic_cast<const CMassAction*>(pKineticFunction);
   CPPUNIT_ASSERT(pMassAction != NULL);
   const CChemEq* pChemEq = &pReaction1->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   const CChemEqElement* pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 0);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   const CReaction* pReaction2 = pModel->getReactions()[1];
   CPPUNIT_ASSERT(pReaction2 != NULL);
   CPPUNIT_ASSERT(pReaction2->isReversible() == false);
   // check the kinetic law
   pKineticFunction = pReaction2->getFunction();
   CPPUNIT_ASSERT(pKineticFunction != NULL);
   CPPUNIT_ASSERT(pKineticFunction->getObjectName() == std::string("Henri-Michaelis-Menten (irreversible)"));
   // check the function parameters one should be the reference to the substrate
   pChemEq = &pReaction2->getChemEq();
   CPPUNIT_ASSERT(pChemEq != NULL);
   CPPUNIT_ASSERT(pChemEq->getCompartmentNumber() == 1);
   CPPUNIT_ASSERT(pChemEq->getSubstrates().size() == 1);
   pElement = pChemEq->getSubstrates()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pA);
   CPPUNIT_ASSERT(pChemEq->getProducts().size() == 1);
   pElement = pChemEq->getProducts()[0];
   CPPUNIT_ASSERT(pElement != NULL);
   CPPUNIT_ASSERT(fabs(pElement->getMultiplicity() - 1.0) < 1e-3);
   CPPUNIT_ASSERT(pElement->getMetabolite() == pB);
   CPPUNIT_ASSERT(pChemEq->getModifiers().size() == 0);
   const std::vector<std::vector<std::string> > parameterMappings = pReaction2->getParameterMappings();
   CPPUNIT_ASSERT(parameterMappings.size() == 3);
   CPPUNIT_ASSERT(parameterMappings[0].size() == 1);
   const std::string parameterKey = parameterMappings[0][0];
   CPPUNIT_ASSERT(parameterKey == pA->getKey());
 }
Member Data Documentation
const char * test000022::MODEL_STRING static protected
Definition at line 31 of file test000022.h.
Referenced by test_hasOnlySubstanceUnits().
CCopasiDataModel * test000022::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000022.h.
Referenced by setUp(), and test_hasOnlySubstanceUnits().
The documentation for this class was generated from the following files:
test000022.h
test000022.cpp