COPASI API: utility.h File Reference
utility.h File Reference
#include <string>
#include <string.h>
#include <stdarg.h>
Macros
#define INITIALTEXTSIZE 1024
Functions
void FixSName (const std::string &original, std::string &fixed)
bool isNumber (const std::string &str)
std::string ISODateTime (tm *pTime)
std::string LocalTimeStamp ()
std::string nameToSbmlId (const std::string &name)
std::string pointerToString (const void *pVoid)
std::string quote (const std::string &name, const std::string &additionalEscapes="")
std::string StringPrint (const char *format,...)
bool stringReplace (std::string &str, const std::string &target, const std::string &replacement)
void * stringToPointer (const std::string str)
double strToDouble (const char *str, char const **pTail=NULL)
C_INT32 strToInt (const char *str, char const **pTail=NULL)
unsigned C_INT32 strToUnsignedInt (const char *str, char const **pTail=NULL)
template<class CType >
CType toEnum (const char *attribute, const char **enumNames, const CType &enumDefault)
template<class CType >
CType toEnum (const std::string &attribute, const std::string *enumNames, const CType &enumDefault)
std::string unQuote (const std::string &name)
std::string UTCTimeStamp ()
Macro Definition Documentation
#define INITIALTEXTSIZE 1024
Definition at line 23 of file utility.h.
Function Documentation
void FixSName (const std::string & original, std::string & fixed)
Definition at line 188 of file utility.cpp.
 {
   size_t i, len;
   // check reserved names
   if (original == "abs") {fixed = "_abs"; return;}
   if (original == "acos") {fixed = "_acos"; return;}
   if (original == "and") {fixed = "_and"; return;}
   if (original == "asin") {fixed = "_asin"; return;}
   if (original == "atan") {fixed = "_atan"; return;}
   if (original == "ceil") {fixed = "_ceil"; return;}
   if (original == "cos") {fixed = "_cos"; return;}
   if (original == "exp") {fixed = "_exp"; return;}
   if (original == "floor") {fixed = "_floor"; return;}
   if (original == "hilli") {fixed = "_hilli"; return;}
   if (original == "hillmmr") {fixed = "_hillmmr"; return;}
   if (original == "hillmr") {fixed = "_hillmr"; return;}
   if (original == "hillr") {fixed = "_hillr"; return;}
   if (original == "isouur") {fixed = "_isouur"; return;}
   if (original == "log") {fixed = "_log"; return;}
   if (original == "log10") {fixed = "_log10"; return;}
   if (original == "massi") {fixed = "_massi"; return;}
   if (original == "massr") {fixed = "_massr"; return;}
   if (original == "not") {fixed = "_not"; return;}
   if (original == "or") {fixed = "_or"; return;}
   if (original == "ordbbr") {fixed = "_ordbbr"; return;}
   if (original == "ordbur") {fixed = "_ordbur"; return;}
   if (original == "ordubr") {fixed = "_ordubr"; return;}
   if (original == "pow") {fixed = "_pow"; return;}
   if (original == "ppbr") {fixed = "_ppbr"; return;}
   if (original == "sin") {fixed = "_sin"; return;}
   if (original == "sqr") {fixed = "_sqr"; return;}
   if (original == "sqrt") {fixed = "_sqrt"; return;}
   if (original == "substance") {fixed = "_substance"; return;}
   if (original == "time") {fixed = "_time"; return;}
   if (original == "tan") {fixed = "_tan"; return;}
   if (original == "umai") {fixed = "_umai"; return;}
   if (original == "umar") {fixed = "_umar"; return;}
   if (original == "uai") {fixed = "_uai"; return;}
   if (original == "ualii") {fixed = "_ualii"; return;}
   if (original == "uar") {fixed = "_uar"; return;}
   if (original == "ucii") {fixed = "_ucii"; return;}
   if (original == "ucir") {fixed = "_ucir"; return;}
   if (original == "ucti") {fixed = "_ucti"; return;}
   if (original == "uctr") {fixed = "_uctr"; return;}
   if (original == "uhmi") {fixed = "_uhmi"; return;}
   if (original == "uhmr") {fixed = "_uhmr"; return;}
   if (original == "umi") {fixed = "_umi"; return;}
   if (original == "unii") {fixed = "_unii"; return;}
   if (original == "unir") {fixed = "_unir"; return;}
   if (original == "uuhr") {fixed = "_uuhr"; return;}
   if (original == "umr") {fixed = "_umr"; return;}
   if (original == "usii") {fixed = "_usii"; return;}
   if (original == "usir") {fixed = "_usir"; return;}
   if (original == "uuci") {fixed = "_uuci"; return;}
   if (original == "uucr") {fixed = "_uucr"; return;}
   if (original == "uui") {fixed = "_uui"; return;}
   if (original == "uur") {fixed = "_uur"; return;}
   if (original == "volume") {fixed = "_volume"; return;}
   if (original == "xor") {fixed = "_xor"; return;}
   len = original.length();
   // check rule for initial characters
   // if first not a letter...
   if (((original[0] < 'A') || (original[0] > 'z')) && (original[0] != '_'))
     {
       if ((original[0] >= '0') && (original[0] <= '9'))
         fixed = "_" + original;
       else
         {fixed = original; fixed [0] = '_';}
     }
   else
     fixed = original;
   len = fixed.length();
   for (i = 1; i < len; i++)
     if ((fixed [i] != '_') && ((fixed [i] < 'A') || (fixed [i] > 'z')) &&
         ((fixed [i] < '0') || (fixed [i] > '9')))
       fixed [i] = '_';
 }
bool isNumber (const std::string & str)
Check whether the given string represents a number
Parameters
const std::string & str
Returns
bool isNumber
Definition at line 75 of file utility.cpp.
References strToDouble().
Referenced by COptItem::compileLowerBound(), COptItem::compileUpperBound(), ConverterASTNode::ConverterASTNode(), CMetabNameInterface::getDisplayName(), CQFittingItemWidget::loadSelection(), CQFittingItemWidget::saveSelection(), COptItem::setLowerBound(), CQFittingItemWidget::setTableText(), COptItem::setUpperBound(), CQFittingItemWidget::slotCheckLowerInf(), CQFittingItemWidget::slotCheckUpperInf(), CQFittingItemWidget::slotLowerLostFocus(), CQFittingItemWidget::slotStartLostFocus(), CQFittingItemWidget::slotUpperLostFocus(), and CChemEqInterface::writeElement().
 {
   if (str.find_first_of("+-.0123456789")) return false;
   const char * Tail;
   strToDouble(str.c_str(), & Tail);
   if (*Tail) return false;
   return true;
 }
std::string ISODateTime (tm * pTime)
Returns the time pointed to by pTime in ISO format
Definition at line 31 of file utility.cpp.
Referenced by LocalTimeStamp(), and UTCTimeStamp().
 {
   char str[20];
   if (pTime)
     {
       sprintf(str, "%d-%.02d-%.02d %.02d:%.02d:%.02d",
               pTime->tm_year + 1900,
               pTime->tm_mon + 1,
               pTime->tm_mday,
               pTime->tm_hour,
               pTime->tm_min,
               pTime->tm_sec);
     }
   else
     {
       sprintf(str, "0000-00-00 00:00:00");
     }
   return (std::string) str;
 }
std::string LocalTimeStamp ()
Returns the current local time in ISO format
Definition at line 53 of file utility.cpp.
References ISODateTime().
Referenced by CCopasiMessage::handler().
 {
   time_t Time;
   time(&Time);
   tm *sTime = NULL;
   sTime = localtime(&Time);
   return ISODateTime(sTime);
 }
std::string nameToSbmlId (const std::string & name)
Convert a utf8 encoded name to a XmlId
Parameters
const std::string & name
Returns
std::string SbmlId
Definition at line 437 of file utility.cpp.
Referenced by CSBMLExporter::createUniqueId().
 {
   // We convert all non allowed characters to '_'
   // letter ::= a..z,A..Z
   // digit  ::= 0..9
   // idChar ::= letter | digit | _
   // SId    ::= (letter | _ ) idChar*
   std::ostringstream IdStream;
   std::string::const_iterator it = name.begin();
   std::string::const_iterator end = name.end();
   if ('0' <= *it && *it <= '9')
     {
       IdStream << '_';
     }
   for (; it != end; ++it)
     {
       // second, third or forth character of a multi-byte encoding
       if (0x80 == (*it & 0xc0))
         {
           continue;
         }
       if (('0' <= *it && *it <= '9') ||
           ('a' <= *it && *it <= 'z') ||
           ('A' <= *it && *it <= 'Z'))
         {
           IdStream << *it;
         }
       else
         {
           IdStream << '_';
         }
     }
   std::string Id = IdStream.str();
   if (Id[Id.length() - 1] != '_')
     {
       return Id;
     }
   return Id.substr(0, Id.length() - 1);
 }
std::string pointerToString (const void * pVoid)
Convert a void pointer to a string
Parameters
const void * pVoid
Returns
std::string str
Definition at line 423 of file utility.cpp.
References fatalError.
Referenced by CEvaluationNodeObject::CEvaluationNodeObject(), and CEvaluationNodeObject::setObjectValuePtr().
 {
   char String[19];
   int Printed = sprintf(String, "%p", pVoid);
   if (Printed < 0 || 18 < Printed)
     {
       fatalError();
     }
   return String;
 }
std::string quote (const std::string & name, const std::string & additionalEscapes = "")
Surround a name with quotes if the name contains a space or double quote else the name is returned unmodified. In the quoted name " and \ are escaped. The parameter additionalEscapes forces quotes around names containing any of the character in the parameter.
Parameters
const std::string & name
const std::string & additionalEscapes (default: "")
Returns
std::string quote
Definition at line 144 of file utility.cpp.
References toBeEscaped.
Referenced by CChemEqInterface::addModifier(), CEvaluationNodeCall::CEvaluationNodeCall(), CEvaluationNodeCall::getBerkeleyMadonnaString(), CEvaluationNodeCall::getCCodeString(), CEvaluationNodeCall::getData(), CMetabNameInterface::getDisplayName(), CEvaluationNodeCall::getDisplayString(), CEvaluationNodeCall::getInfix(), CEvaluationNodeCall::getMMLString(), CEvaluationNodeCall::getXPPString(), CEvaluationNodeCall::setData(), and CMetabNameInterface::splitDisplayName().
 {
   if (name.find_first_of(" \"" + additionalEscapes) == std::string::npos)
     return name;
 #define toBeEscaped "\\\""
   std::string Escaped(name);
   std::string::size_type pos = Escaped.find_first_of(toBeEscaped);
   while (pos != std::string::npos)
     {
       Escaped.insert(pos, "\\");
       pos += 2;
       pos = Escaped.find_first_of(toBeEscaped, pos);
     }
   return "\"" + Escaped + "\"";
 #undef toBeEscaped
 }
std::string StringPrint (const char * format, ...)
sprintf like function for strings
Parameters
const char * format sprintf like format string
...
Returns
"string"
Definition at line 87 of file utility.cpp.
References C_INT32, and INITIALTEXTSIZE.
Referenced by CExperimentSet::addExperiment(), CExperiment::elevateChildren(), CExperimentObjectMap::getDefaultScale(), CExperimentObjectMap::getName(), CExperimentObjectMap::getObjectCN(), CExperimentObjectMap::getRole(), CExperimentObjectMap::getScale(), CCopasiTimeVariable::LL2String(), CQExperimentData::load(), CReaction::loadOld(), CReaction::loadOneRole(), CExperimentObjectMap::setNumCols(), CExperimentObjectMap::setObjectCN(), CExperimentObjectMap::setRole(), CExperimentObjectMap::setScale(), CVersion::setString(), CQExperimentData::slotFileAdd(), and CCopasiXMLParser::ParameterDescriptionElement::start().
 {
   C_INT32 TextSize = INITIALTEXTSIZE;
   C_INT32 Printed = 0;
   char *Text = NULL;
   Text = new char[TextSize + 1];
   va_list Arguments; // = NULL;
   va_start(Arguments, format);
   Printed = vsnprintf(Text, TextSize + 1, format, Arguments);
   va_end(Arguments);
   while (Printed < 0 || TextSize < Printed)
     {
       delete [] Text;
       (Printed < 0) ? TextSize *= 2 : TextSize = Printed;
       Text = new char[TextSize + 1];
       va_list Arguments; // = NULL;
       va_start(Arguments, format);
       Printed = vsnprintf(Text, TextSize + 1, format, Arguments);
       va_end(Arguments);
     }
   std::string Result = Text;
   delete [] Text;
   return Result;
 }
bool stringReplace (std::string & str, const std::string & target, const std::string & replacement)
Replaces the all occurrences of target string in str with the replacement and returns true if the target string was replaced
Parameters
std::string & str
const std::string & target
const std::string & replacement
Returns
bool replaced
Definition at line 165 of file utility.cpp.
Referenced by CModel::convert2NonReversible().
 {
   bool replaced = false;
   std::string::size_type pos = str.find(target, 0);
   while (pos != std::string::npos)
     {
       replaced = true;
       str.replace(pos, target.length(), replacement, 0, std::string::npos);
       pos = str.find(target, 0);
     }
   return replaced;
 }
void* stringToPointer (const std::string str)
Convert a character sequence to a void pointer
Parameters
const std::string str
Returns
void * pVoid
Definition at line 414 of file utility.cpp.
Referenced by CEvaluationNodeObject::compile(), CMathExpression::compile(), and CMathExpression::copy().
 {
   void * pPointer;
   sscanf(str.c_str(), "%p", &pPointer);
   return pPointer;
 }
double strToDouble (const char * str, char const ** pTail = NULL)
Convert a character sequence to a double
Parameters
const char * str
char const ** pTail (default: NULL)
Returns
double
Definition at line 325 of file utility.cpp.
Referenced by CEvaluationNodeNumber::CEvaluationNodeNumber(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CReadConfig::getVariable(), isNumber(), CMiaseParser::newSimulation(), operator>>(), COptItem::setLowerBound(), COptItem::setUpperBound(), CCopasiXMLParser::RectangleElement::start(), CCopasiXMLParser::EllipseElement::start(), CCopasiXMLParser::TextElement::start(), CCopasiXMLParser::RenderCurveElement::start(), CCopasiXMLParser::PolygonElement::start(), CCopasiXMLParser::GroupElement::start(), test000087::test_simulate_reaction_flux_reference_1(), CEvaluationNodeNumber::toAST(), and CChemEqParserBase::yyparse().
 {
   double Value = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   if (pTail != NULL)
     {
       *pTail = str;
     }
   if (str == NULL || *str == 0x0)
     {
       return Value;
     }
   std::istringstream in;
   in.imbue(std::locale::classic());
   in.str(str);
   in >> Value;
   if (pTail != NULL && !isnan(Value))
     {
       *pTail = str + std::min< size_t >(in.tellg(), strlen(str));
     }
   return Value;
 }
C_INT32 strToInt (const char * str, char const ** pTail = NULL)
Convert a character sequence to a double
Parameters
const char * str
char const ** pTail (default: NULL)
Returns
C_INT32
Definition at line 354 of file utility.cpp.
References C_INT32.
Referenced by CCopasiXMLParser::ParameterElement::start(), and CCopasiXMLParser::COPASIElement::start().
 {
   C_INT32 Value = std::numeric_limits< C_INT32 >::quiet_NaN();
   if (pTail != NULL)
     {
       *pTail = str;
     }
   if (str == NULL || *str == 0x0)
     {
       return Value;
     }
   std::istringstream in;
   in.imbue(std::locale::classic());
   in.str(str);
   in >> Value;
   if (pTail != NULL && !isnan(Value))
     {
       *pTail = str + std::min< size_t >(in.tellg(), strlen(str));
     }
   return Value;
 }
unsigned C_INT32 strToUnsignedInt (const char * str, char const ** pTail = NULL)
Convert a character sequence to a double
Parameters
const char * str
char const ** pTail (default: NULL)
Returns
unsigned C_INT32
Definition at line 384 of file utility.cpp.
References C_INT32.
Referenced by CCopasiParameterGroup::getObject(), CCopasiXMLParser::CompartmentElement::start(), CCopasiXMLParser::ParameterElement::start(), CCopasiXMLParser::ReportElement::start(), CCopasiXMLParser::ParameterDescriptionElement::start(), and CCopasiXMLParser::SliderElement::start().
 {
   unsigned C_INT32 Value = std::numeric_limits< unsigned C_INT32 >::quiet_NaN();
   if (pTail != NULL)
     {
       *pTail = str;
     }
   if (str == NULL || *str == 0x0)
     {
       return Value;
     }
   std::istringstream in;
   in.imbue(std::locale::classic());
   in.str(str);
   in >> Value;
   if (pTail != NULL && !isnan(Value))
     {
       *pTail = str + std::min< size_t >(in.tellg(), strlen(str));
     }
   return Value;
 }
template<class CType > CType toEnum (const char * attribute, const char ** enumNames, const CType & enumDefault)
Convert an attribute to enum. If attribute is NULL or no matching name is found the parameter enumDefault is returned. Note: enumNames must be zero terminated.
Parameters
const char * attribute
const char ** enumNames
const CType & enumDefault
Returns
CType enum
Definition at line 107 of file utility.h.
Referenced by CQTaskMethodWidget::changeMethod(), CPlotItem::getActivity(), CQExperimentData::saveTable(), CModel::setAreaUnit(), CModel::setLengthUnit(), CModel::setQuantityUnit(), CModel::setTimeUnit(), CPlotItem::setType(), CModel::setVolumeUnit(), CCopasiXMLParser::ModelParameterElement::start(), CCopasiXMLParser::ModelParameterGroupElement::start(), CCopasiXMLParser::MetaboliteElement::start(), CCopasiXMLParser::CompartmentElement::start(), CCopasiXMLParser::ModelValueElement::start(), CCopasiXMLParser::ModelElement::start(), CCopasiXMLParser::PlotItemElement::start(), CCopasiXMLParser::PlotSpecificationElement::start(), CCopasiXMLParser::ParameterElement::start(), CCopasiXMLParser::ParameterTextElement::start(), CCopasiXMLParser::MethodElement::start(), CCopasiXMLParser::TaskElement::start(), CCopasiXMLParser::ReportElement::start(), CCopasiXMLParser::FunctionElement::start(), and CCopasiXMLParser::SliderElement::start().
 {
   if (!attribute) return enumDefault;
   for (int i = 0; *enumNames; i++, enumNames++)
     if (!strcmp(attribute, *enumNames)) return static_cast< CType >(i);
   return enumDefault;
 }
template<class CType > CType toEnum (const std::string & attribute, const std::string * enumNames, const CType & enumDefault)
Convert an attribute to enum. If attribute is "" or no matching name is found the parameter enumDefault is returned. Note: enumNames must be zero terminated.
Parameters
const std::string & attribute
const std::string * enumNames
const CType & enumDefault
Returns
CType enum
Definition at line 128 of file utility.h.
 {
   if (attribute == "") return enumDefault;
   for (int i = 0; *enumNames != ""; i++, enumNames++)
     if (attribute == *enumNames) return static_cast< CType >(i);
   return enumDefault;
 }
std::string unQuote (const std::string & name)
Unesacape a quoted name. If the name is surrounded by quotes these are removed and included escape sequences '.' are reduced to '.' else the name is returned unmodified.
Parameters
const std::string & name
Returns
std::string unQuote
Definition at line 120 of file utility.cpp.
Referenced by CEvaluationNodeCall::CEvaluationNodeCall(), CModel::findMetabByName(), CEvaluationNodeCall::getData(), CCopasiVectorN< CReportDefinition >::getIndex(), CEvaluationNodeCall::setData(), and CChemEqParser::yylex().
 {
   std::string Name = name;
   std::string::size_type len = Name.length();
   if (len > 1 && Name[0] == '"' && Name[len - 1] == '"')
     {
       // Remove surrounding double quotes.
       Name = Name.substr(1, len - 2);
       // Remove escape sequences.
       std::string::size_type pos = Name.find("\\");
       while (pos != std::string::npos)
         {
           Name.erase(pos, 1);
           pos++;
           pos = Name.find("\\", pos);
         }
     }
   return Name;
 }
std::string UTCTimeStamp ()
Returns the current time in ISO format
Definition at line 64 of file utility.cpp.
References ISODateTime().
Referenced by createParameterSetsForExperiment(), CCopasiXML::save(), and CConfigurationFile::CXML::save().
 {
   time_t Time;
   time(&Time);
   tm *sTime = NULL;
   sTime = gmtime(&Time);
   return ISODateTime(sTime);
 }