COPASI API: test000099 Class Reference
test000099 Class Reference
#include <test000099.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1675 ()
Protected Attributes
CCopasiDataModel * pDataModel
Static Protected Attributes
static const char * SBML_MODEL_BAD
static const char * SBML_MODEL_GOOD
Private Member Functions
CPPUNIT_TEST (test_bug1675)
CPPUNIT_TEST_SUITE (test000099)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 28 of file test000099.h.
Member Function Documentation
test000099::CPPUNIT_TEST (test_bug1675) private
test000099::CPPUNIT_TEST_SUITE (test000099) private
test000099::CPPUNIT_TEST_SUITE_END () private
void test000099::setUp ()
Definition at line 25 of file test000099.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pDataModel.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   pDataModel = CCopasiRootContainer::addDatamodel();
 }
void test000099::tearDown ()
Definition at line 32 of file test000099.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000099::test_bug1675 ()
Definition at line 39 of file test000099.cpp.
References CCopasiObject::getCN(), CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), CCopasiDataModel::ObjectFromName(), pDataModel, SBML_MODEL_BAD, and SBML_MODEL_GOOD.
 {
   CPPUNIT_ASSERT(pDataModel != NULL);
   CModel* pModel = NULL;
   std::vector< CCopasiContainer * > listOfContainer;
   // try to import the file which should lead to an exception
   try
     {
       pDataModel->importSBMLFromString(SBML_MODEL_BAD);
       // importing should lead to an exception, so we should never
       // reach this point
       assert(false);
     }
   catch (...)
     {
       CPPUNIT_ASSERT(pModel == NULL);
       const CModel * pModel2 =
         dynamic_cast< const CModel * >(pDataModel->ObjectFromName(listOfContainer, CCopasiObjectName("CN=Root,Model=my test model")));
       CPPUNIT_ASSERT(pModel2 == NULL);
     }
   // import the good model
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(SBML_MODEL_GOOD) == true);
     }
   catch (...)
     {
       // this should not lead to an exception
       assert(false);
     }
   // now check if we find the object for the model name
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   const CModel * pModel2 =
     dynamic_cast< const CModel * >(pDataModel->ObjectFromName(listOfContainer, pDataModel->getModel()->getCN()));
   CPPUNIT_ASSERT(pModel == pModel2);
 }
Member Data Documentation
CCopasiDataModel* test000099::pDataModel protected
Definition at line 41 of file test000099.h.
Referenced by setUp(), and test_bug1675().
const char * test000099::SBML_MODEL_BAD static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">\n"
  "  <model name=\"my test model\">\n"
  "    <listOfCompartments>\n"
  "      <compartment id=\"compartment_1\" size=\"1.0\"/>\n"
  "    </listOfCompartments>\n"
  "    <listOfSpecies>\n"
  "      <species id=\"species_1\" compartment=\"compartment_1\" initialConcentration=\"1.0\"/>\n"
  "      <species id=\"species_2\" compartment=\"compartment_1\" initialConcentration=\"1.0\"/>\n"
  "    </listOfSpecies>\n"
  "    <listOfReactions>\n"
  "      <reaction id=\"reaction_1\">\n"
  "        <listOfReactants>\n"
  "          <speciesReference species=\"species_1\"/>\n"
  "        </listOfReactants>\n"
  "        <kineticLaw>\n"
  "          <math xmlns=\"http://www.w3.org/1998/Math/MathML\">\n"
  "            <apply>\n"
  "              <times/>\n"
  "              <ci> species_1 </ci>\n"
  "              <ci> species_2 </ci>\n"
  "            </apply>\n"
  "          </math>\n"
  "        </kineticLaw>\n"
  "      </reaction>\n"
  "    </listOfReactions>\n"
  "  </model>\n"
  "</sbml>\n"
Definition at line 36 of file test000099.h.
Referenced by test_bug1675().
const char * test000099::SBML_MODEL_GOOD static protected
Definition at line 39 of file test000099.h.
Referenced by test_bug1675().
The documentation for this class was generated from the following files:
test000099.h
test000099.cpp