COPASI API: CLocaleString Class Reference
CLocaleString Class Reference
#include <CLocaleString.h>
Public Types
typedef char lchar
Public Member Functions
const lchar * c_str () const
CLocaleString ()
CLocaleString (const lchar *str)
CLocaleString (const CLocaleString &src)
CLocaleString & operator= (const CLocaleString &rhs)
CLocaleString & operator= (const lchar *str)
std::string toUtf8 () const
~CLocaleString ()
Static Public Member Functions
static CLocaleString fromUtf8 (const std::string &utf8)
Private Attributes
lchar * mpStr
Detailed Description
Definition at line 19 of file CLocaleString.h.
Member Typedef Documentation
typedef char CLocaleString::lchar
Definition at line 25 of file CLocaleString.h.
Constructor & Destructor Documentation
CLocaleString::CLocaleString ()
Definition at line 156 of file CLocaleString.cpp.
Referenced by fromUtf8().
                             :
   mpStr(NULL)
 {}
CLocaleString::CLocaleString (const lchar * str)
Definition at line 160 of file CLocaleString.cpp.
                                                           :
   mpStr((str != NULL) ? strdup(str) : NULL)
 {}
CLocaleString::CLocaleString (const CLocaleString & src)
Definition at line 164 of file CLocaleString.cpp.
                                                      :
   mpStr((src.mpStr != NULL) ? strdup(src.mpStr) : NULL)
 {}
CLocaleString::~CLocaleString ()
Definition at line 168 of file CLocaleString.cpp.
References mpStr.
 {
   if (mpStr != NULL)
     {
       free(mpStr);
       mpStr = NULL;
     }
 }
Member Function Documentation
const CLocaleString::lchar * CLocaleString::c_str () const
Definition at line 319 of file CLocaleString.cpp.
References mpStr.
 {
   return mpStr;
 }
CLocaleString CLocaleString::fromUtf8 (const std::string & utf8) static
Definition at line 50 of file CLocaleString.cpp.
References CLocaleString().
Referenced by CExperimentSet::compile(), CDirEntry::createDir(), CDirEntry::exist(), CCopasiDataModel::exportMathModel(), CSBMLExporter::exportModel(), CSEDMLExporter::exportModelAndTasks(), COptions::getEnvironmentVariable(), CExperiment::guessColumnNumber(), SEDMLImporter::importFirstSBMLModel(), CCopasiDataModel::importSBML(), CReadConfig::initFileBuffer(), CDirEntry::isDir(), CDirEntry::isFile(), CDirEntry::isReadable(), CDirEntry::isWritable(), CCopasiXMLInterface::load(), CCopasiDataModel::loadModel(), CDirEntry::move(), CReport::open(), CExperiment::readColumnNames(), SBMLImporter::readSBML(), SEDMLImporter::readSEDML(), CDirEntry::remove(), CDirEntry::removeFiles(), CTimeSeries::save(), CCopasiXMLInterface::save(), CopasiPlot::saveData(), CQTSSAResultSubWidget::saveDataToFile(), CQExpressionMmlStackedWidget::saveMML(), CQDifferentialEquations::saveMML(), CQExpressionMmlStackedWidget::saveTeX(), CQDifferentialEquations::saveTeX(), CQLyapResultWidget::saveToFile(), CQSensResultWidget::saveToFile(), CExperimentFileInfo::setFileName(), CQParameterOverviewWidget::slotBtnSaveToFile(), CQExperimentData::slotCheckNormalizeWeightsPerExperiment(), CQExperimentData::slotExperimentChanged(), CopasiUI3Window::slotFileSave(), CQSteadyStateResult::slotSave(), CQMoietiesTaskResult::slotSave(), CMCAResultSubwidget::slotSave(), CLNAResultSubwidget::slotSave(), CQOptimizationResult::slotSave(), CQFittingResult::slotSave(), CQEFMResultWidget::slotSave(), CQExperimentData::slotWeightMethod(), and CQExperimentData::updateScales().
 {
 #ifdef WIN32
   int size;
   size = MultiByteToWideChar(CP_UTF8, // code page
                              MB_ERR_INVALID_CHARS, // character-type options
                              utf8.c_str(), // address of string to map
                              -1, // NULL terminated
                              NULL, // address of wide-character buffer
                              0) + 1;               // size of buffer
   WCHAR * pWideChar = new WCHAR[size];
   MultiByteToWideChar(CP_UTF8, // code page
                       MB_ERR_INVALID_CHARS, // character-type options
                       utf8.c_str(), // address of string to map
                       -1, // NULL terminated
                       pWideChar, // address of wide-character buffer
                       size);                // size of buffer
   CLocaleString Locale(pWideChar);
   delete [] pWideChar;
   return Locale;
 #endif // WIN32
 #if (defined SunOS || defined Linux)
   static iconv_t Converter = NULL;
   if (Converter == NULL)
     {
       char From[] = "UTF-8";
       const char * To = findLocale();
       Converter = iconv_open(To, From);
     }
   if (Converter == (iconv_t)(-1))
     return CLocaleString(utf8.c_str());
   size_t Utf8Length = utf8.length();
   char * Utf8 = strdup(utf8.c_str());
 #if (defined COPASI_ICONV_CONST_CHAR) // non standard iconv declaration :(
   const char * pUtf8 = Utf8;
 #else
   char * pUtf8 = Utf8;
 #endif
   size_t LocaleLength = Utf8Length + 1;
   size_t SpaceLeft = Utf8Length;
   char * Locale = new char[LocaleLength];
   char * pLocale = Locale;
   while (Utf8Length)
     if ((size_t)(-1) ==
         iconv(Converter, &pUtf8, &Utf8Length, &pLocale, &SpaceLeft))
       {
         switch (errno)
           {
             case EILSEQ:
               pUtf8 = Utf8;
               LocaleLength = 0;
               break;
             case EINVAL:
               pLocale = Locale;
               Utf8Length = 0;
               break;
             case E2BIG:
               char * pTmp = Locale;
               size_t OldLength = LocaleLength;
               LocaleLength += 2 * Utf8Length;
               Locale = new char[LocaleLength];
               memcpy(Locale, pTmp,
                      sizeof(char) * (OldLength - SpaceLeft - 1));
               pLocale = Locale + OldLength - SpaceLeft - 1;
               SpaceLeft += 2 * Utf8Length;
               delete [] pTmp;
               break;
           }
         continue;
       }
   *pLocale = 0x00; // NULL terminate the string.
   CLocaleString Result(Locale);
   // Reset the Converter
   iconv(Converter, NULL, &Utf8Length, NULL, &LocaleLength);
   // Release memory
   free(Utf8);
   delete [] Locale;
   return Result;
 #endif // SunOS || Linux
 #ifdef Darwin
   return CLocaleString(utf8.c_str());
 #endif
 }
CLocaleString & CLocaleString::operator= (const CLocaleString & rhs)
Definition at line 177 of file CLocaleString.cpp.
References mpStr.
 {
   if (mpStr != NULL)
     {
       free(mpStr);
       mpStr = NULL;
     }
   mpStr = (rhs.mpStr != NULL) ? strdup(rhs.mpStr) : NULL;
   return *this;
 }
CLocaleString & CLocaleString::operator= (const lchar * str)
Definition at line 190 of file CLocaleString.cpp.
References mpStr.
 {
   if (mpStr != NULL)
     {
       free(mpStr);
       mpStr = NULL;
     }
   mpStr = (rhs != NULL) ? strdup(rhs) : NULL;
   return *this;
 }
std::string CLocaleString::toUtf8 () const
Definition at line 203 of file CLocaleString.cpp.
References mpStr.
Referenced by COptions::getCopasiDir(), COptions::getEnvironmentVariable(), COptions::getPWD(), COptions::init(), and CDirEntry::removeFiles().
 {
   if (mpStr == NULL)
     {
       return "";
     }
 #ifdef WIN32
   int size;
   size = WideCharToMultiByte(CP_UTF8, // code page
                              0, // performance and mapping flags
                              mpStr, // address of wide-character string
                              -1, // NULL terminated
                              NULL, // address of buffer for new string
                              0, // size of buffer
                              NULL, // address of default for unmappable characters
                              NULL) + 1; // address of flag set when default char used
   char * pUtf8 = new char[size];
   WideCharToMultiByte(CP_UTF8, // code page
                       0, // address of wide-character string
                       mpStr, // address of wide-character string
                       -1, // NULL terminated
                       pUtf8, // address of buffer for new string
                       size, // size of buffer
                       NULL, // address of default for unmappable characters
                       NULL);     // address of flag set when default char used
   std::string Utf8 = pUtf8;
   delete [] pUtf8;
   return Utf8;
 #endif // WIN32
 #if (defined SunOS || defined Linux)
   static iconv_t Converter = NULL;
   if (Converter == NULL)
     {
       char To[] = "UTF-8";
       const char * From = findLocale();
       Converter = iconv_open(To, From);
     }
   if (Converter == (iconv_t)(-1))
     return mpStr;
   size_t LocaleLength = strlen(mpStr);
   char * Locale = strdup(mpStr);
 #if (COPASI_ICONV_CONST_CHAR) // non standard iconv declaration :(
   const char * pLocale = Locale;
 #else
   char * pLocale = Locale;
 #endif
   size_t Utf8Length = LocaleLength + 1;
   size_t SpaceLeft = LocaleLength;
   char * Utf8 = new char[Utf8Length];
   char * pUtf8 = Utf8;
   while (LocaleLength)
     if ((size_t)(-1) ==
         iconv(Converter, &pLocale, &LocaleLength, &pUtf8, &SpaceLeft))
       {
         switch (errno)
           {
             case EILSEQ:
               pUtf8 = Utf8;
               LocaleLength = 0;
               break;
             case EINVAL:
               pUtf8 = Utf8;
               LocaleLength = 0;
               break;
             case E2BIG:
               char * pTmp = Utf8;
               size_t OldLength = Utf8Length;
               Utf8Length += 2 * LocaleLength;
               Utf8 = new char[Utf8Length];
               memcpy(Utf8, pTmp,
                      sizeof(char) * (OldLength - SpaceLeft - 1));
               pUtf8 = Utf8 + OldLength - SpaceLeft - 1;
               SpaceLeft += 2 * LocaleLength;
               delete [] pTmp;
               break;
           }
         continue;
       }
   *pUtf8 = 0x00; // NULL terminate the string.
   std::string Result = Utf8;
   // Reset the Converter
   iconv(Converter, NULL, &LocaleLength, NULL, &Utf8Length);
   // Release memory
   free(Locale);
   delete [] Utf8;
   return Result;
 #endif // SunOS || Linux
 #ifdef Darwin
   std::string Result = mpStr;
   return Result;
 #endif // Darwin
 }
Member Data Documentation
lchar* CLocaleString::mpStr private
Definition at line 49 of file CLocaleString.h.
Referenced by c_str(), operator=(), toUtf8(), and ~CLocaleString().
The documentation for this class was generated from the following files:
CLocaleString.h
CLocaleString.cpp