COPASI API: CCopasiObject Class Reference
CCopasiObject Class Reference
#include <CCopasiObject.h>
Public Types
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes
static CRenameHandler * smpRenameHandler = NULL
Private Types
typedef CCopasiObject referenceType
Private Attributes
DataObjectSet mDependencies
unsigned C_INT32 mObjectFlag
std::string mObjectName
std::string mObjectType
CCopasiStaticString * mpObjectDisplayName
CCopasiContainer * mpObjectParent
Refresh * mpRefresh
UpdateMethod * mpUpdateMethod
Static Private Attributes
static const C_FLOAT64 DummyValue = 0.0
static UpdateMethod mDefaultUpdateMethod
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiObject &o)
Detailed Description
Definition at line 216 of file CCopasiObject.h.
Member Typedef Documentation
typedef std::set< const CCopasiObject * > CCopasiObject::DataObjectSet
Definition at line 225 of file CCopasiObject.h.
typedef std::vector< Refresh * > CCopasiObject::DataUpdateSequence
Definition at line 226 of file CCopasiObject.h.
typedef CCopasiObject CCopasiObject::referenceType private
Definition at line 222 of file CCopasiObject.h.
Member Enumeration Documentation
enum CCopasiObject::Flag protected
Enumerator
Container
Vector
Matrix
NameVector
Reference
ValueBool
ValueInt
ValueInt64
ValueDbl
NonUniqueName
StaticString
ValueString
Separator
ModelEntity
Array
DataModel
Root
Gui
Definition at line 230 of file CCopasiObject.h.
   {
     Container = 0x1,
     Vector = 0x2,
     Matrix = 0x4,
     NameVector = 0x8,
     Reference = 0x10,
     ValueBool = 0x20,
     ValueInt = 0x40,
     ValueInt64 = 0x80,
     ValueDbl = 0x100,
     NonUniqueName = 0x200,
     StaticString = 0x400,
     ValueString = 0x800,
     Separator = 0x1000,
     ModelEntity = 0x2000,
     Array = 0x4000,
     DataModel = 0x8000,
     Root = 0x10000,
     Gui = 0x20000
   };
Constructor & Destructor Documentation
CCopasiObject::CCopasiObject () protected
Definition at line 48 of file CCopasiObject.cpp.
                             :
   CObjectInterface(),
   mObjectName("No Name"),
   mObjectType("Unknown Type"),
   mpObjectParent(NULL),
   mpObjectDisplayName(NULL),
   mObjectFlag(0),
   mpUpdateMethod(&this->mDefaultUpdateMethod),
   mpRefresh(NULL)
 {}
CCopasiObject::CCopasiObject (const std::string & name, const CCopasiContainer * pParent = NULL, const std::string & type = "CN", const unsigned C_INT32 & flag = 0) protected
Definition at line 59 of file CCopasiObject.cpp.
References CCopasiContainer::add(), isContainer(), and mpObjectParent.
                                                            :
   CObjectInterface(),
   mObjectName((name == "") ? "No Name" : name),
   mObjectType(type),
   mpObjectParent(const_cast<CCopasiContainer *>(pParent)),
   mpObjectDisplayName(NULL),
   mObjectFlag(flag),
   mpUpdateMethod(&this->mDefaultUpdateMethod),
   mpRefresh(NULL)
 {
   if (mpObjectParent != NULL)
     if (mpObjectParent->isContainer()) mpObjectParent->add(this);
 }
CCopasiObject::CCopasiObject (const CCopasiObject & src, const CCopasiContainer * pParent = NULL)
Definition at line 76 of file CCopasiObject.cpp.
References CCopasiContainer::add(), and mpObjectParent.
                                                               :
   CObjectInterface(),
   mObjectName(src.mObjectName),
   mObjectType(src.mObjectType),
   mpObjectParent(const_cast<CCopasiContainer *>(pParent)),
   mpObjectDisplayName(NULL),
   mObjectFlag(src.mObjectFlag),
   mpUpdateMethod(&this->mDefaultUpdateMethod),
   mpRefresh(NULL)
 {if (mpObjectParent != NULL) mpObjectParent->add(this);}
CCopasiObject::~CCopasiObject () virtual
Definition at line 88 of file CCopasiObject.cpp.
References mDefaultUpdateMethod, mpObjectDisplayName, mpObjectParent, mpRefresh, mpUpdateMethod, pdelete, and CCopasiContainer::remove().
 {
   if (mpObjectParent)
     mpObjectParent->remove(this);
   pdelete(mpObjectDisplayName);
   if (mpUpdateMethod != &mDefaultUpdateMethod)
     pdelete(mpUpdateMethod);
   pdelete(mpRefresh);
 }
Member Function Documentation
void CCopasiObject::addDirectDependency (const CCopasiObject * pObject)
Add a the object to the direct dependencies
Parameters
const CCopasiObject * pObject
Definition at line 309 of file CCopasiObject.cpp.
References mDependencies.
Referenced by CMoiety::add(), CModelEntity::compile(), COptItem::compile(), CEvent::compile(), CReaction::compile(), CModel::compile(), CEvaluationTree::compileNodes(), COptItem::compileUpperBound(), CMathTrigger::CRootFinder::initObjects(), CMoiety::initObjects(), CReaction::setFunction(), and CReaction::setFunctionFromExpressionTree().
 {
   mDependencies.insert(pObject);
   return;
 }
std::vector< Refresh * > CCopasiObject::buildUpdateSequence (const DataObjectSet & objects, const DataObjectSet & uptoDateObjects, const DataObjectSet & context = DataObjectSet()) static
Build the update sequence for the given list of objects. The resulting sequence takes the dependencies of the objects in consideration. If circular dependencies are detected an exception is thrown
Parameters
DataObjectSet & objects
const DataObjectSet & uptoDateObjects
const DataObjectSet & context (default: empty set)
Returns
std::vector< Refresh * > updateSequence
Definition at line 438 of file CCopasiObject.cpp.
References CCopasiMessage::EXCEPTION, getAllDependencies(), MCObject, and sortObjectsByDependency().
Referenced by CModel::buildApplyInitialValuesSequence(), CMathModel::buildDependendRefreshList(), CModel::buildNonSimulatedSequence(), CMathModel::buildRequiredRefreshList(), CModel::buildSimulatedSequence(), CExperiment::compile(), COutputHandler::compileRefresh(), CScanMethod::init(), CFitProblem::initialize(), COptProblem::initialize(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), and CTrajectoryMethodDsaLsodar::start().
 {
   CCopasiObject::DataObjectSet DependencySet;
   CCopasiObject::DataObjectSet VerifiedSet;
   CCopasiObject::DataObjectSet::const_iterator itSet;
   CCopasiObject::DataObjectSet::const_iterator endSet = objects.end();
   std::pair<CCopasiObject::DataObjectSet::iterator, bool> InsertedObject;
   assert(objects.count(NULL) == 0);
   // Check whether we have any circular dependencies
   for (itSet = objects.begin(); itSet != endSet; ++itSet)
     if ((*itSet)->hasCircularDependencies(DependencySet, VerifiedSet, context))
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCObject + 1, (*itSet)->getCN().c_str());
   // Build the complete set of dependencies
   for (itSet = objects.begin(); itSet != endSet; ++itSet)
     {
       // At least the object itself needs to be up to date.
       InsertedObject = DependencySet.insert(*itSet);
       // Add all its dependencies
       if (InsertedObject.second)
         (*itSet)->getAllDependencies(DependencySet, context);
     }
   // Remove all objects which do not have any refresh method as they will
   // be ignored anyway, i.e., no need to sort them.
   for (itSet = DependencySet.begin(), endSet = DependencySet.end(); itSet != endSet;)
     if ((*itSet)->getRefresh() == NULL ||
         ((dynamic_cast< const CParticleReference * >(*itSet) != NULL ||
           dynamic_cast< const CConcentrationReference * >(*itSet) != NULL) &&
          (*itSet)->getDirectDependencies(context).size() == 0))
       {
         const CCopasiObject * pObject = *itSet;
         ++itSet;
         DependencySet.erase(pObject);
       }
     else
       ++itSet;
   // Build the list of all up to date objects
   CCopasiObject::DataObjectSet UpToDateSet;
   for (itSet = uptoDateObjects.begin(), endSet = uptoDateObjects.end(); itSet != endSet; ++itSet)
     {
       // At least the object itself is up to date.
       InsertedObject = UpToDateSet.insert(*itSet);
       // Add all its dependencies too
       if (InsertedObject.second)
         (*itSet)->getAllDependencies(UpToDateSet, context);
     }
   // Now remove all objects in the dependency set which are up to date
   for (itSet = UpToDateSet.begin(), endSet = UpToDateSet.end(); itSet != endSet; ++itSet)
     DependencySet.erase(*itSet);
   // Create a properly sorted list.
   std::list< const CCopasiObject * > SortedList =
     sortObjectsByDependency(DependencySet.begin(), DependencySet.end(), context);
   std::list< const CCopasiObject * >::iterator itList;
   std::list< const CCopasiObject * >::iterator endList;
   // Build the vector of pointers to refresh methods
   Refresh * pRefresh;
   std::vector< Refresh * > UpdateVector;
   std::vector< Refresh * >::const_iterator itUpdate;
   std::vector< Refresh * >::const_iterator endUpdate;
   itList = SortedList.begin();
   endList = SortedList.end();
   for (; itList != endList; ++itList)
     {
       pRefresh = (*itList)->getRefresh();
       itUpdate = UpdateVector.begin();
       endUpdate = UpdateVector.end();
       while (itUpdate != endUpdate && !(*itUpdate)->isEqual(pRefresh)) ++itUpdate;
       if (itUpdate == endUpdate)
         UpdateVector.push_back(pRefresh);
     }
   return UpdateVector;
 }
void CCopasiObject::clearDirectDependencies ()
Clear the list of direct dependencies.
Definition at line 293 of file CCopasiObject.cpp.
References mDependencies.
Referenced by CMoiety::cleanup(), CEventAssignment::compile(), COptItem::compile(), CEvent::compile(), CMetab::compile(), CReaction::compile(), and CEvaluationTree::compileNodes().
 {
   mDependencies.clear();
 }
void CCopasiObject::clearRefresh ()
Definition at line 630 of file CCopasiObject.cpp.
References mpRefresh, and pdelete.
Referenced by CMetab::compile(), CReaction::compile(), CModelEntity::setStatus(), and CMetab::setStatus().
 {pdelete(mpRefresh);}
bool CCopasiObject::dependsOn (CCopasiObject::DataObjectSet candidates, const DataObjectSet & context = DataObjectSet()) const
Check whether the current object depends on any objects in the candidates.
Parameters
DataObjectSet candidates
const DataObjectSet & context (default: empty set)
Returns
bool dependsOn
Definition at line 388 of file CCopasiObject.cpp.
References hasCircularDependencies().
Referenced by CMathModel::buildDependendRefreshList(), CModel::buildSimulatedSequence(), and CHybridMethodODE45::setupMetab2React().
 {
   CCopasiObject::DataObjectSet verified;
   return hasCircularDependencies(candidates, verified, context);
 }
void CCopasiObject::getAllDependencies (CCopasiObject::DataObjectSet & dependencies, const DataObjectSet & context) const
If called with an empty set of dependencies it retrieves the complete list of all dependencies (including all indirect) of the current object. If called with a non empty set it will only add any dependency and all its dependencies to the list if the dependency is not already among the dependencies
Parameters
DataObjectSet & dependencies
const DataObjectSet & context
Definition at line 345 of file CCopasiObject.cpp.
References getDirectDependencies().
Referenced by buildUpdateSequence().
 {
   const CCopasiObject::DataObjectSet & DirectDependencies = getDirectDependencies(context);
   CCopasiObject::DataObjectSet::const_iterator it = DirectDependencies.begin();
   CCopasiObject::DataObjectSet::const_iterator end = DirectDependencies.end();
   std::pair<CCopasiObject::DataObjectSet::iterator, bool> Inserted;
   for (; it != end; ++it)
     {
       // Dual purpose insert
       Inserted = dependencies.insert(*it);
       // The direct dependency *it was among the dependencies
       // we assume also its dependencies have been added already.
       if (!Inserted.second) continue;
       // Add all the dependencies of the direct dependency *it.
       (*it)->getAllDependencies(dependencies, context);
     }
 }
CCopasiObjectName CCopasiObject::getCN () const virtual
Retrieve the CN of the object
Returns
CCopasiObjectName
Implements CObjectInterface.
Reimplemented in CCopasiParameter, CMathContainer, and CArrayElementReference.
Definition at line 103 of file CCopasiObject.cpp.
References CCopasiObjectName::escape(), getCN(), CCopasiVector< T >::getIndex(), isDataModel(), isNameVector(), isVector(), mObjectName, mObjectType, and mpObjectParent.
Referenced by CQPlotSubwidget::addCurve2D(), CQLayoutScene::addGlyph(), CCompartment::addMetabolite(), CReportDefinition::addTableElement(), addToInitialValueMap(), applyValueToModelParameter(), CQReportDefinition::btnSeparatorClicked(), CQReportDefinition::btnTextClicked(), CFixLocalReactionParameters::changeModel(), CTimeSeries::compile(), CEvaluationNodeCall::compile(), CMathObject::compileDependentMass(), CMathObject::compileFlux(), CMathObject::compileParticleFlux(), CMathObject::compilePropensity(), COutputHandler::compileRefresh(), CModel::convert2NonReversible(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), CQReportListItem::CQReportListItem(), SBMLImporter::createCReactionFromReaction(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), CMathObject::createExtensiveODERateExpression(), CModelParameterSet::createFromModel(), CExpression::createInitialExpression(), CMathObject::createIntensiveRateExpression(), CSBMLExporter::createKineticExpression(), CSBMLExporter::createMassActionExpression(), COutputAssistant::createPlot(), CScanProblem::createScanItem(), SBMLImporter::divideByObject(), CCopasiXMLParser::ListOfReportsElement::end(), CCopasiXMLParser::HeaderElement::end(), CCopasiXMLParser::BodyElement::end(), CCopasiXMLParser::FooterElement::end(), ObjectBrowserWidget::eXport(), CMathObject::getCN(), CArrayElementReference::getCN(), CMathContainer::getCN(), CCopasiParameter::getCN(), getCN(), getInitialCNForSBase(), CMathContainer::getObject(), CFitProblem::initialize(), CSteadyStateTask::initialize(), CModelMerging::mergeInExpression(), CSBMLExporter::multiplyByObject(), CCopasiDataModel::ObjectFromCN(), operator<<(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), SBMLImporter::renameMassActionParameters(), SBMLImporter::replace_time_with_initial_time(), CModelExpansion::replaceInExpression(), SBMLImporter::replaceObjectNames(), CSBMLExporter::replaceSpeciesReferences(), CScanWidgetRandom::save(), CScanWidgetScan::save(), CQReportDefinition::save(), SensitivitiesWidget::saveTask(), Curve2DWidget::SaveToCurveSpec(), HistoWidget::SaveToCurveSpec(), BandedGraphWidget::SaveToCurveSpec(), CQExperimentData::selectModelObject(), setObjectName(), CCrossSectionProblem::setSingleObjectCN(), CSlider::setSliderObject(), COptProblem::setSubtaskType(), CQFittingItemWidget::slotCheckLowerInf(), CQFittingItemWidget::slotCheckUpperInf(), CQFittingItemWidget::slotLowerEdit(), CQFittingItemWidget::slotUpperEdit(), test000099::test_bug1675(), test000087::test_simulate_reaction_flux_reference_1(), CModelExpansion::updateExpression(), CSteadyStateTask::updateMatrices(), and CReaction::variable2object().
 {
   CCopasiObjectName CN;
   // if the object has a parent and if the object is not a datamodel,
   // we add the name of the parent to the common name
   if (isDataModel())
     CN = (std::string) "CN=Root";
   else if (mpObjectParent)
     {
       std::stringstream tmp;
       tmp << mpObjectParent->getCN();
       if (mpObjectParent->isNameVector())
         tmp << "[" << CCopasiObjectName::escape(mObjectName) << "]";
       else if (mpObjectParent->isVector())
         tmp << "[" << static_cast<const CCopasiVector< CCopasiObject > *>(mpObjectParent)->getIndex(this) << "]";
       else
         tmp << "," << CCopasiObjectName::escape(mObjectType)
             << "=" << CCopasiObjectName::escape(mObjectName);
       CN = tmp.str();
     }
   else
     {
       CN = CCopasiObjectName::escape(mObjectType)
            + "=" + CCopasiObjectName::escape(mObjectName);
     }
   return CN;
 }
const CCopasiObject::DataObjectSet & CCopasiObject::getDirectDependencies (const DataObjectSet & context = DataObjectSet()) const virtual
Retrieve the list of direct dependencies
Parameters
const DataObjectSet & context (default empty set)
Returns
const DataObjectSet & directDependencies
Reimplemented in CParticleReference, and CConcentrationReference.
Definition at line 304 of file CCopasiObject.cpp.
References mDependencies.
Referenced by CModel::buildInitialRefreshSequence(), CEventAssignment::compile(), CModelEntity::compile(), CMetab::compile(), CMathEvent::compile(), CMetab::compileInitialValueDependencies(), CModel::convert2NonReversible(), CDotOutput::findObjectsWithUpdateMethod(), getAllDependencies(), CConcentrationReference::getDirectDependencies(), CParticleReference::getDirectDependencies(), CParticleReference::getPrerequisites(), hasCircularDependencies(), CMathContainer::hasDependencies(), CFitProblem::initialize(), COptProblem::initialize(), CReaction::setScalingFactor(), CModelEntity::setStatus(), CMetab::setStatus(), and CDotOutput::writeDotRecursively().
 {
   return mDependencies;
 }
const std::string & CCopasiObject::getKey () const virtual
Reimplemented in CModel, CCopasiTask, CLGroup, CMoiety, CLText, CLRenderInformationBase, CEvent, CLRectangle, CReportDefinition, CLEllipse, CLImage, CCopasiParameter, CFunctionParameter, CLRenderCurve, CLStyle, CLColorDefinition, CLGradientBase, CReaction, CLPolygon, CLLineEnding, CReference, CModelEntity, CLGradientStop, CCreator, CBiologicalDescription, CSlider, CModification, CMIRIAMInfo, CLGraphicalObject, CEventAssignment, CLayout, CFunction, CReportDefinitionVector, CModelParameterSet, and COutputDefinitionVector.
Definition at line 608 of file CCopasiObject.cpp.
Referenced by addToInitialValueMap(), SliderSettingsDialog::browseButtonPressed(), CQReportDefinition::btnDeleteReportClicked(), CModelAnalyzer::checkReaction(), CLayout::CLayout(), CQGLNetworkPainter::createGraph(), SliderDialog::createNewSlider(), SBMLImporter::doMapping(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::COPASIElement::end(), CODEExporter::exportExpression(), CODEExporter::exportKineticFunction(), CODEExporter::exportMetabolites(), CODEExporter::exportMetabolitesConcentrations(), CODEExporter::exportReacParamsAndFuncs(), CLayout::exportToDotFile(), SliderDialog::getCSlidersForObject(), CModelExpansion::ElementsMap::getDuplicateKey(), SBMLImporter::importEvent(), CQSpecieDM::insertRows(), CODEExporterC::KineticFunction2ODEmember(), CMIRIAMInfo::load(), CReaction::loadOneRole(), CModelMerging::mergeInExpression(), CODEExporterC::preprocess(), CODEExporter::preprocess(), CQParameterSetsDM::removeRows(), SBMLImporter::restoreFunctionDB(), CQFunctionDM::setData(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), ReactionsWidget1::slotBtnNew(), CQReactionsWidget::slotDoubleClicked(), CQEventsWidget::slotDoubleClicked(), CQCompartmentsWidget::slotDoubleClicked(), CQFunctionsWidget::slotDoubleClicked(), CQGlobalQuantitiesWidget::slotDoubleClicked(), CQSpeciesWidget::slotDoubleClicked(), CCopasiXMLParser::ParameterElement::start(), CCopasiXMLParser::SliderElement::start(), CQFittingWidget::taskFinishedEvent(), test000058::test_bug1025_6(), test000059::test_unique_id_13(), test000059::test_unique_id_15(), test000059::test_unique_id_16(), CLLayoutRenderer::update_associations(), CSBMLExporter::updateMIRIAMAnnotation(), CModelParameter::updateModel(), CReactionInterface::writeBackToReaction(), and CMMLOutput::writeDifferentialEquations().
 {
   static std::string DefaultKey("");
   return DefaultKey;
 }
const CObjectInterface * CCopasiObject::getObject (const CCopasiObjectName & cn) const virtual
Retrieve a descendant object by its CN.
Parameters
const CCopasiObjectName & cn
Returns
const CObjectInterface * pObject
Implements CObjectInterface.
Reimplemented in CCopasiVectorN< CType >, CCopasiVectorN< CReaction >, CCopasiVectorN< CEventAssignment >, CCopasiVectorN< CFunctionParameter >, CCopasiVectorN< CCopasiTask >, CCopasiVectorN< CPlotSpecification >, CCopasiVectorN< CCompartment >, CCopasiVectorN< CModelParameterSet >, CCopasiVectorN< CEvent >, CCopasiVectorN< CMetab >, CCopasiVectorN< CFunction >, CCopasiVectorN< CModelValue >, CCopasiVectorN< CReportDefinition >, CCopasiVector< T >, CCopasiVector< CLGlobalRenderInformation >, CCopasiVector< CModification >, CCopasiVector< CLMetabGlyph >, CCopasiVector< CLCompartmentGlyph >, CCopasiVector< CLReferenceGlyph >, CCopasiVector< CSlider >, CCopasiVector< CBiologicalDescription >, CCopasiVector< CLGlobalStyle >, CCopasiVector< CEventAssignment >, CCopasiVector< CReference >, CCopasiVector< CMathEvent::CAssignment >, CCopasiVector< CLayout >, CCopasiVector< CLGradientStop >, CCopasiVector< CLMetabReferenceGlyph >, CCopasiVector< CMoiety >, CCopasiVector< CType >, CCopasiVector< CChemEqElement >, CCopasiVector< CLColorDefinition >, CCopasiVector< CLReactionGlyph >, CCopasiVector< CEvent >, CCopasiVector< CMathEvent >, CCopasiVector< CLGradientBase >, CCopasiVector< CLLocalRenderInformation >, CCopasiVector< CMetab >, CCopasiVector< CPlotItem >, CCopasiVector< CCopasiDataModel >, CCopasiVector< CLLineEnding >, CCopasiVector< CFittingPoint >, CCopasiVector< CLTextGlyph >, CCopasiVector< CCopasiObject >, CCopasiVector< CMathTrigger::CRootFinder >, CCopasiVector< CLLocalStyle >, CCopasiVector< CCreator >, CCopasiVector< CLGraphicalObject >, CCopasiVector< CMetabOld >, CCopasiVector< CLGeneralGlyph >, CReaction, CArrayAnnotation, CMathContainer, CCopasiParameterGroup, and CCopasiContainer.
Definition at line 136 of file CCopasiObject.cpp.
References getObjectDisplayName(), and mpObjectDisplayName.
Referenced by CMathObject::getObject(), CCopasiContainer::getObject(), CArrayAnnotation::getObject(), CModelExpansion::replaceInExpression(), SEDMLUtils::resolveXPath(), and CModelExpansion::updateExpression().
 {
   if (cn == "")
     {
       return this;
     }
   if (cn == "Property=DisplayName")
     {
       if (mpObjectDisplayName == NULL)
         {
           mpObjectDisplayName = new CCopasiStaticString();
         }
       *mpObjectDisplayName = getObjectDisplayName();
       return mpObjectDisplayName;
     }
   return NULL;
 }
CCopasiContainer * CCopasiObject::getObjectAncestor (const std::string & type) const
Definition at line 279 of file CCopasiObject.cpp.
References getObjectParent(), and getObjectType().
Referenced by SliderSettingsDialog::browseButtonPressed(), CExperimentSet::calculateStatistics(), CFixLocalReactionParameters::changeModel(), CMetab::compile(), CMathEvent::compile(), CMetab::compileInitialValueDependencies(), CScanItem::CScanItem(), CFitProblem::elevateChildren(), CQSimpleSelectionTree::filter(), CReaction::getChildObjectUnits(), CArrayElementReference::getObjectDisplayName(), CReaction::getObjectDisplayName(), CEvent::getObjectDisplayName(), CMetab::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), COptProblem::getSubtaskType(), CMetab::initCompartment(), CMoiety::initConversionFactor(), CFitProblem::initialize(), COptProblem::initializeSubtaskBeforeOutput(), CModelEntity::initObjects(), CQCompartment::load(), CReaction::load(), CQEventWidget1::loadFromEvent(), CReaction::loadOneRole(), CReaction::object2variable(), CQEventWidget1::saveToEvent(), ReactionsWidget1::setFramework(), CModelParameterSet::setObjectParent(), CEventAssignment::setObjectParent(), CModelEntity::setObjectParent(), CEvent::setObjectParent(), CReaction::setScalingFactor(), COptProblem::setSubtaskType(), CSensMethod::setValue(), CQCompartment::slotTypeChanged(), CModelParameter::updateModel(), and ParameterTable::updateTable().
 {
   CCopasiContainer * p = getObjectParent();
   while (p)
     {
       if (p->getObjectType() == type) return p;
       p = p->getObjectParent();
     }
   return NULL;
 }
CCopasiDataModel * CCopasiObject::getObjectDataModel ()
Returns a pointer to the CCopasiDataModel the element belongs to. If there is no instance of CCopasiDataModel in the ancestor tree, NULL is returned.
Definition at line 666 of file CCopasiObject.cpp.
References getObjectParent(), and isDataModel().
Referenced by COptProblem::addOptItem(), CQPlotSubwidget::addPlot(), CQReportDefinition::btnCopyReportClicked(), CExperiment::calculateStatistics(), CSlider::compile(), CModelEntity::compile(), COptItem::compile(), CExperiment::compile(), CModelParameter::compile(), CExperimentObjectMap::compile(), CMetab::compile(), CModelParameterReactionParameter::compile(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CQPlotSubwidget::copyPlot(), CModelAdd::copyTriggerExpression(), createParameterSetsForExperiment(), CScanItem::CScanItem(), CFitProblem::elevateChildren(), CopasiWidget::enter(), CODEExporter::exportModelValuesExpressions(), CArrayAnnotation::getAnnotationsString(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CQExpressionWidget::getExpression(), CExperiment::getFileName(), CExpression::getNodeObject(), CMathContainer::getObject(), CFittingPoint::getObjectDisplayName(), COptItem::getStartValue(), CMCAProblem::getSubTask(), COptProblem::getSubtaskType(), SEDMLUtils::getXPathForObject(), CFitProblem::initialize(), CSensMethod::initialize(), CScanTask::initialize(), CNewtonMethod::initialize(), CCopasiTask::initialize(), CTSSAMethod::initializeIntegrationsParameter(), CLsodaMethod::initializeParameter(), COptProblem::initializeSubtaskBeforeOutput(), CScanTask::initSubtask(), SBMLImporter::isConstantFlux(), CSlider::isValid(), CSteadyStateProblem::load(), CTrajectoryProblem::load(), CModel::load(), CReaction::loadOneRole(), CQCrossSectionTaskWidget::loadTask(), CModelMerging::mergeInExpression(), CReaction::object2variable(), operator<<(), CQSimpleSelectionTree::populateTree(), CReportDefinition::preCompileTable(), CTSSAProblem::printResult(), CILDMModifiedMethod::printResult(), CMoietiesTask::process(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQFittingWidget::runTask(), COptItem::setObjectCN(), CSlider::setSliderObject(), CModelEntity::setStatus(), CMCAProblem::setSteadyStateRequested(), CLNAProblem::setSteadyStateRequested(), COptProblem::setSubtaskType(), CQFittingWidget::taskFinishedEvent(), CModelParameter::updateModel(), ParameterTable::updateTable(), and CDotOutput::writeDependencies().
 {
   CCopasiObject * pObject = this;
   while (pObject != NULL)
     {
       if (pObject->isDataModel())
         return static_cast<CCopasiDataModel *>(pObject);
       pObject = pObject->getObjectParent();
     }
   return NULL;
 }
const CCopasiDataModel * CCopasiObject::getObjectDataModel () const
Returns a const pointer to the CCopasiDataModel the element belongs to. If there is no instance of CCopasiDataModel in the ancestor tree, NULL is returned.
Definition at line 686 of file CCopasiObject.cpp.
References getObjectParent(), and isDataModel().
 {
   const CCopasiObject * pObject = this;
   while (pObject != NULL)
     {
       if (pObject->isDataModel())
         return static_cast<const CCopasiDataModel *>(pObject);
       pObject = pObject->getObjectParent();
     }
   return NULL;
 }
std::string CCopasiObject::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
Reimplemented in CCopasiParameter, CMetab, CArrayAnnotation, CEvent, CReaction, CArrayElementReference, CCopasiObjectReference< CType >, CCopasiObjectReference< C_FLOAT64 >, CCopasiReportSeparator, CCopasiStaticString, and CFittingPoint.
Definition at line 216 of file CCopasiObject.cpp.
References getObjectDisplayName(), getObjectName(), getObjectType(), isNameVector(), isReference(), isVector(), and mpObjectParent.
Referenced by CQPlotSubwidget::addCurve2D(), SliderSettingsDialog::browseButtonPressed(), Curve2DWidget::buttonPressedX(), HistoWidget::buttonPressedX(), BandedGraphWidget::buttonPressedX(), Curve2DWidget::buttonPressedY(), BandedGraphWidget::buttonPressedYone(), BandedGraphWidget::buttonPressedYtwo(), COptItem::compile(), CQReportListItem::CQReportListItem(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CPlotSpecification::createDefaultPlot(), CMMLOutput::createParameterMapping(), COutputAssistant::createPlot(), CQEventDM::data(), CQOptimizationResult::enterProtected(), CQFittingResult::enterProtected(), CQSelectionWizardPage::fillTree(), findObjectByDisplayName(), CArrayAnnotation::getAnnotationsString(), CEvaluationNodeObject::getDisplayString(), CMathMl::getMMLName(), getObject(), CFittingPoint::getObjectDisplayName(), CCopasiObjectReference< C_FLOAT64 >::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), CReaction::getObjectDisplayName(), COptItem::getObjectDisplayName(), CEvent::getObjectDisplayName(), CArrayAnnotation::getObjectDisplayName(), CMetab::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), getObjectDisplayName(), CSensItem::getSingleObjectDisplayName(), SEDMLUtils::getXPathForObject(), CScanWidgetRandom::initFromObject(), CScanWidgetScan::initFromObject(), CScanItem::isValidScanItem(), CScanWidgetRandom::load(), CScanWidgetScan::load(), Curve2DWidget::LoadFromCurveSpec(), BandedGraphWidget::LoadFromCurveSpec(), HistoWidget::LoadFromCurveSpec(), CQEventWidget1::loadFromEvent(), CQUpdatesWidget::loadObjectsTable(), CQUpdatesWidget::loadOneTable(), CQFittingItemWidget::loadSelection(), CQExperimentData::loadTable(), SensitivitiesWidget::loadTask(), operator<<(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQReportListItem::refreshText(), CQExperimentData::selectModelObject(), CQSimpleSelectionTree::selectObjects(), CQExpressionWidget::setExpression(), CQCrossSectionTaskWidget::setSingleObject(), SliderSettingsDialog::setSlider(), CQFittingItemWidget::setTableText(), CQSideCompoundWizardPage::slotAddButtonClicked(), CQEventWidget1::slotAddTarget(), SensitivitiesWidget::slotChooseSingleFunction(), SensitivitiesWidget::slotChooseSingleVariable(), SensitivitiesWidget::slotChooseSingleVariable2(), CQFittingItemWidget::slotLowerEdit(), CQSideCompoundWizardPage::slotRemoveButtonClicked(), CQEventWidget1::slotSelectObject(), CQExpressionWidget::slotSelectObject(), CQFittingItemWidget::slotUpperEdit(), CopasiSlider::updateLabel(), CMMLOutput::writeDifferentialEquations(), CDotOutput::writeEdge(), and CDotOutput::writeObjectNode().
 {
   std::string ret = "";
   if (mpObjectParent)
     {
       ret = mpObjectParent->getObjectDisplayName(regular, richtext);
       if (ret == "(CN)Root" ||
           ret == "ModelList[]" ||
           ret.substr(0, 7) == "(Model)")
         {
           ret = "";
         }
     }
   if (ret.length() >= 2)
     if ((ret.substr(ret.length() - 2) == "[]") && (!isReference()))
       {
         ret.insert(ret.length() - 1, getObjectName());
         if (isNameVector() || isVector() || getObjectType() == "ParameterGroup")
           ret += "[]";
         return ret;
       }
   if ((ret.length() != 0) && (ret[ret.length() - 1] != '.'))
     ret += ".";
   if (isNameVector() || isVector() || getObjectType() == "ParameterGroup")
     ret += getObjectName() + "[]";
   else if (isReference()
            || getObjectType() == "Parameter"
            || getObjectType() == getObjectName())
     ret += getObjectName();
   else
     ret += "(" + getObjectType() + ")" + getObjectName();
   return ret;
 }
const std::string & CCopasiObject::getObjectName () const
Definition at line 258 of file CCopasiObject.cpp.
References mObjectName.
Referenced by CCopasiContainer::add(), CFunctionDB::addAndAdaptName(), CModelAdd::addCompartments(), CModelAdd::addEvents(), CExperimentSet::addExperiment(), CModelAdd::addMetabolites(), CModelAdd::addModelValues(), CModelAdd::addReactions(), CReportDefinition::addTableElement(), addToInitialValueMap(), SBMLImporter::areEqualFunctions(), CQReportDefinition::btnCopyReportClicked(), CQReportDefinition::btnDeleteReportClicked(), CEvaluationTree::calls(), CCopasiContainer::CCopasiContainer(), CFixLocalReactionParameters::changeModel(), CSBMLExporter::checkForODESpeciesInNonfixedCompartment(), CSBMLExporter::checkForPiecewiseFunctions(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CFunctionAnalyzer::checkKineticFunction(), CModelAnalyzer::checkReaction(), CCopasiSelectionDialog::chooseCellMatrix(), CEventAssignment::compile(), CExperiment::compile(), CReaction::compile(), CMathObject::compileFlux(), CEvaluationTree::compileNodes(), CChemEqInterface::completeCompartments(), CReactionInterface::connectNonMetabolites(), CModel::convert2NonReversible(), CLRenderFlattener::convertGlobalToLocalStyle(), CMathExpression::convertToInitialExpression(), CQSpeciesDetail::copy(), ReactionsWidget1::copy(), CMathExpression::copy(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), FunctionWidget1::copyFunctionContentsToFunction(), CModelAdd::copyInitialExpression(), CQPlotSubwidget::copyPlot(), CModelAdd::copyTriggerExpression(), SBMLImporter::createCMetabFromSpecies(), CSBMLExporter::createCompartment(), SBMLImporter::createCReactionFromReaction(), CSEDMLExporter::createDataGenerators(), COutputAssistant::createDefaultOutput(), CSBMLExporter::createEvent(), SBMLImporter::createExpressionFromFunction(), CSBMLExporter::createFunctionDefinitions(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createKineticExpression(), CSBMLExporter::createKineticLaw(), CQLayoutsWidget::createLayoutWindow(), CModelExpansion::createLinearArray(), CFunction::createListOfParametersForMathML(), CSBMLExporter::createMetabolite(), CSBMLExporter::createParameter(), CMMLOutput::createParameterMapping(), CKinFunction::createParameters(), createParameterSetsForExperiment(), CSBMLExporter::createReaction(), CModelExpansion::createRectangularArray(), CSBMLExporter::createRule(), CSBMLExporter::createSBMLDocument(), CSEDMLExporter::createTimeCourseTask(), CCSPMethod::CSPOutput(), CQReportDM::data(), CQPlotDM::data(), CQFunctionDM::data(), CQReactionDM::data(), CQEventDM::data(), CQGlobalQuantityDM::data(), CQCompartmentDM::data(), CQSpecieDM::data(), CModelExpansion::duplicateCompartment(), CModelExpansion::duplicateEvent(), CModelExpansion::duplicateGlobalQuantity(), CModelExpansion::duplicateMetab(), CModelExpansion::duplicateReaction(), CExperimentObjectMap::elevateChildren(), CCopasiXMLParser::PlotItemElement::end(), CCopasiXMLParser::PlotSpecificationElement::end(), CCopasiXMLParser::ParameterGroupElement::end(), CCopasiXMLParser::ListOfFunctionsElement::end(), CCopasiXMLParser::ListOfParameterDescriptionsElement::end(), CQFittingResult::enterProtected(), expand_function_call(), CODEExporter::exportCompartments(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CODEExporter::exportKineticFunction(), CODEExporter::exportMetabolites(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportModelValues(), CODEExporter::exportReacParamsAndFuncs(), CODEExporter::exportSimulatedObject(), CODEExporterC::exportSingleFunction(), CODEExporter::exportSingleFunction(), CODEExporterC::exportTitleData(), CQMergingData::fillTree(), CQSimpleSelectionTree::filter(), SBMLImporter::findCorrespondingFunction(), SBMLImporter::findFunctionCalls(), CFunctionDB::findLoadFunction(), CModel::findMoiety(), CFunctionParameters::findParameterByName(), CArrayAnnotation::getAnnotationsString(), CReaction::getChildObjectUnits(), CModel::getChildObjectUnits(), CFitItem::getCrossValidations(), CEvaluationNodeCall::getData(), CReactionInterface::getDeletedParameters(), CParticleReference::getDirectDependencies(), CMetabNameInterface::getDisplayName(), CMathDependencyGraph::getDOTNodeId(), CFitItem::getExperiments(), CReactionInterface::getFunctionName(), ParameterTable::getListOfAllCompartmentNames(), ParameterTable::getListOfAllGlobalParameterNames(), CMathMl::getMMLName(), CLGraphicalObject::getModelObjectDisplayName(), CLGraphicalObject::getModelObjectName(), CModelParameterSet::getName(), CExperimentObjectMap::getName(), CModelParameter::getName(), CCopasiParameterGroup::getName(), CCopasiContainer::getObject(), CCopasiVectorReference< CType >::getObject(), CCopasiMatrixReference< CType >::getObject(), CReaction::getObject(), CCopasiObjectReference< C_FLOAT64 >::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), CReaction::getObjectDisplayName(), CEvent::getObjectDisplayName(), CArrayAnnotation::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), getObjectDisplayName(), CEventAssignment::getTargetKey(), Arguments::getTaskForName(), CLabel::getText(), CPlotItem::getTitle(), CCopasiParameterGroup::getUniqueParameterName(), Arguments::handleCommandLine(), hasLayout(), SBMLImporter::importFunctionDefinitions(), CQProgressItemText::initFromProcessReportItem(), CQProgressItemBar::initFromProcessReportItem(), CScanTask::initialize(), CCopasiTask::initialize(), CReaction::initializeParameters(), CFunction::initVariables(), CSBMLExporter::isEventAssignmentSBMLCompatible(), CSBMLExporter::isEventSBMLCompatible(), CQSimpleSelectionTree::isMetaboliteNameUnique(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CParticleReference::isPrerequisiteForContext(), CMetabNameInterface::isUnique(), CEFMMethod::isValidProblem(), FunctionWidget1::leave(), CQExperimentSelection::load(), CQTabWidget::load(), CQReportDefinition::load(), CQSpeciesDetail::load(), CQExpandModelData::load(), CMetab::load(), CMetabOld::load(), ObjectBrowserWidget::loadChild(), CQExperimentData::loadExperiment(), ObjectBrowserWidget::loadField(), CReactionInterface::loadMappingAndValues(), CQUpdatesWidget::loadObjectsTable(), CReaction::loadOld(), CReaction::loadOneRole(), CQSpeciesDetail::loadReactionTable(), CQReportDefinitionSelect::loadReportDefinitionVector(), CQFittingItemWidget::loadSelection(), FunctionWidget1::loadUsageTable(), main(), CModelMerging::mergeInExpression(), CODEExporter::modifyTreeForMassAction(), stress_test::normalizeAndSimplifyExpressions(), stress_test::normalizeFunctionDB(), operator<<(), CLGraphicalObject::operator=(), CCopasiParameterGroup::operator=(), CCopasiParameter::operator=(), CMetab::operator=(), CFunctionParameters::operator==(), operator==(), CHybridMethod::outputDebug(), CHybridMethodODE45::outputDebug(), CHybridMethodLSODA::outputDebug(), CQSimpleSelectionTree::populateTree(), CODEExporterC::preprocess(), CODEExporter::preprocess(), printNameForKey(), CModel::printParameterOverview(), CFitProblem::printResult(), CILDMModifiedMethod::printResult(), CCSPMethod::printResult(), CExperiment::printResult(), CExperiment::read(), CQParameterSetsDM::removeRows(), CQReportDM::removeRows(), CQLayoutsDM::removeRows(), CQFunctionDM::removeRows(), CQReactionDM::removeRows(), CQEventDM::removeRows(), CQGlobalQuantityDM::removeRows(), CQCompartmentDM::removeRows(), CQSpecieDM::removeRows(), SBMLImporter::removeUnusedFunctions(), CSBMLExporter::replace_local_parameters(), CModelExpansion::replaceInExpression(), CModelExpansion::replaceInMetab(), CSBMLExporter::replaceSpeciesReferences(), CSBMLExporter::restore_local_parameters(), CQTabWidget::save(), CQReportDefinition::save(), CQSpeciesDetail::save(), CQExperimentData::saveExperiment(), CCopasiXML::saveFunctionList(), CCopasiXML::saveLayoutList(), CCopasiXML::saveModel(), CCopasiXMLInterface::saveParameter(), CCopasiXML::savePlotList(), CCopasiXML::saveReportList(), CQFittingWidget::saveTask(), CCopasiXML::saveTaskList(), CQMatrixDialog::setArray(), CQPlotDM::setData(), CQFunctionDM::setData(), CQSpecieDM::setData(), CQLayoutView::setDataModel(), CODEExporterC::setExportNameOfFunction(), CReaction::setFunctionFromExpressionTree(), CSBMLExporter::setFunctionSBMLIds(), CChemEqElement::setMetabolite(), CReaction::setScalingFactor(), CSensMethod::setValue(), CModelMerging::simpleCall(), CQParameterOverviewWidget::slotBtnDelete(), FunctionWidget1::slotBtnDelete(), ReactionsWidget1::slotBtnDelete(), CQSpeciesDetail::slotBtnDelete(), CQCompartment::slotBtnDelete(), CQModelValue::slotBtnDelete(), CQExperimentData::slotCheckFrom(), CQExpandModelData::slotCompartmentActivated(), CQMoietiesTaskResult::slotCreateGlobalQuantity(), CQExperimentData::slotExperimentAdd(), ReactionsWidget1::slotNewFunction(), CQBrowserPaneDM::slotNotify(), CQExperimentData::slotOK(), CQSpeciesDetail::slotSwitchToReaction(), CCopasiXMLParser::SourceParameterElement::start(), CCopasiXMLParser::KineticLawElement::start(), test000058::test_bug1025_10(), test000058::test_bug1025_5(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000052::test_bug988(), test_compare_utilities::test_copasi_function_expansion(), test000047::test_delay(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000035::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000032::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000040::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000021::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000082::test_import_delayAssignment_1(), test000082::test_import_delayAssignment_2(), test000082::test_import_delayAssignment_3(), test000082::test_import_delayAssignment_4(), test000082::test_import_delayAssignment_5(), test000082::test_import_delayAssignment_6(), test000082::test_import_delayAssignment_7(), test000082::test_import_delayAssignment_8(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), test000087::test_import_reaction_flux_reference_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000087::test_simulate_reaction_flux_reference_1(), test000059::test_unique_id_17(), test000059::test_unique_id_18(), test000059::test_unique_id_19(), test000059::test_unique_id_20(), test000059::test_unique_id_21(), test000059::test_unique_id_21_2(), CEvaluationNodeObject::toAST(), CModelExpansion::updateExpression(), updateLayoutList(), CQNewMainWindow::updateLayoutList(), CModelParameter::updateModel(), validate(), CReactionInterface::writeBackToReaction(), CMMLOutput::writeDifferentialEquations(), CFunction::writeMathML(), and CMMLOutput::writeRHS().
 {return mObjectName;}
CCopasiContainer * CCopasiObject::getObjectParent () const
Definition at line 276 of file CCopasiObject.cpp.
References mpObjectParent.
Referenced by addInitialAssignmentsToModel(), CCompartment::addMetabolite(), CReportDefinition::addTableElement(), applyAttributeChange(), SBMLImporter::applyStoichiometricExpressions(), CMathDependencyNode::buildUpdateSequence(), CLyapWolfMethod::calculate(), CEFMAlgorithm::calculateFluxModes(), CSBMLExporter::checkForUnsupportedObjectReferences(), CMetab::CMetab(), CExpression::compile(), CMathObject::compileDependentMass(), CMathObject::compileFlux(), CMathObject::compileInitialValue(), CMathObject::compileParticleFlux(), CMathObject::compilePropensity(), CMathObject::compileRate(), CMathObject::compileTotalMass(), CMathObject::compileValue(), contains_necessary_mass_action_elements(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), CExpression::createInitialExpression(), SBMLImporter::doMapping(), CLLayoutRenderer::draw_layout(), elevate(), CCopasiXMLParser::GroupElement::end(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportSimulatedObject(), CModelExpansion::expressionContainsObject(), SliderDialog::fillSliderBox(), CQSimpleSelectionTree::filter(), CSBMLExporter::findModelEntityDependencies(), CArrayElementReference::getCN(), CCopasiParameter::getCN(), CModel::getCorrespondingTransientObject(), CExperimentObjectMap::CDataColumn::getDefaultScale(), CParticleReference::getDirectDependencies(), CMathDependencyGraph::getDOTNodeId(), CObjectLists::getListOfConstObjects(), CMathMl::getMMLName(), CCopasiVectorReference< CType >::getObject(), CCopasiMatrixReference< CType >::getObject(), CReaction::getObject(), getObjectAncestor(), getObjectDataModel(), CCopasiObjectReference< C_FLOAT64 >::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), CArrayAnnotation::getObjectDisplayName(), CCopasiParameter::getObjectDisplayName(), CParticleReference::getPrerequisites(), CArrayElementReference::getValuePointer(), CMathContainer::hasDependencies(), CLGraphicalObject::hasValidModelReference(), CSBMLExporter::hasVolumeAssignment(), CScanMethod::init(), CSSAMethod::initialize(), CFitMethod::initialize(), CEFMMethod::initialize(), CFitProblem::initialize(), CEFMAlgorithm::initialize(), COptProblem::initialize(), COptMethodSS::initialize(), CBitPatternMethod::initialize(), CBitPatternTreeMethod::initialize(), COptMethod::initialize(), SBMLImporter::isConstantFlux(), SBMLImporter::isMassActionExpression(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CParticleReference::isPrerequisiteForContext(), CModel::isStateVariable(), CScanMethod::loop(), CModelMerging::mergeInExpression(), CReaction::object2variable(), operator<<(), CLNAProblem::printResult(), CEFMProblem::printResult(), CMCAProblem::printResult(), CLyapProblem::printResult(), CSteadyStateMethod::process(), CSBMLExporter::replace_local_parameters(), CModelExpansion::replaceInExpression(), CSBMLExporter::replaceSpeciesReferences(), SEDMLUtils::resolveXPath(), SBMLImporter::setCorrectUsage(), CEventAssignment::setObjectParent(), CEvent::setObjectParent(), CQEventWidget1::slotAddTarget(), CQFittingItemWidget::slotReset(), CQEventWidget1::slotSelectObject(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000052::test_bug988(), test000047::test_delay(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000040::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000032::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000021::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000035::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000082::test_import_delayAssignment_1(), test000082::test_import_delayAssignment_2(), test000082::test_import_delayAssignment_3(), test000082::test_import_delayAssignment_4(), test000082::test_import_delayAssignment_5(), test000082::test_import_delayAssignment_6(), test000082::test_import_delayAssignment_7(), test000082::test_import_delayAssignment_8(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), test000087::test_import_reaction_flux_reference_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000087::test_simulate_reaction_flux_reference_1(), CEvaluationNodeObject::toAST(), CModelExpansion::updateExpression(), and CModelParameter::updateModel().
 {return mpObjectParent;}
const std::string & CCopasiObject::getObjectType () const
Definition at line 260 of file CCopasiObject.cpp.
References mObjectType.
Referenced by CEvent::CEvent(), CSBMLExporter::checkForUnsupportedFunctionCalls(), CSBMLExporter::checkForUnsupportedObjectReferences(), CModelEntity::CModelEntity(), CReaction::CReaction(), SBMLImporter::createCReactionFromReaction(), CSBMLExporter::createInitialAssignment(), CSBMLExporter::createRule(), SBMLImporter::doMapping(), CSBMLExporter::exportEventAssignments(), CODEExporter::exportExpression(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportSimulatedObject(), CCopasiParameter::getCN(), CMathMl::getMMLName(), CCopasiContainer::getObject(), CCopasiVector< CLGeneralGlyph >::getObject(), CCopasiVectorN< CReportDefinition >::getObject(), getObjectAncestor(), CCopasiReportSeparator::getObjectDisplayName(), CCopasiObjectReference< C_FLOAT64 >::getObjectDisplayName(), CArrayElementReference::getObjectDisplayName(), CArrayAnnotation::getObjectDisplayName(), getObjectDisplayName(), CSBMLExporter::hasVolumeAssignment(), SBMLImporter::importEvent(), CSBMLExporter::isEventAssignmentSBMLCompatible(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), operator<<(), CModelExpansion::replaceInExpression(), CQMergingData::slotBtnMerge(), CQMergingData::treeSelectionChanged(), and CModelExpansion::updateExpression().
 {return mObjectType;}
const CObjectInterface::ObjectSet & CCopasiObject::getPrerequisites () const virtual
Retrieve the prerequisites, i.e., the objects which need to be evaluated before this.
Returns
const CObjectInterface::ObjectSet & prerequisites
Implements CObjectInterface.
Reimplemented in CParticleReference, and CMathExpression.
Definition at line 321 of file CCopasiObject.cpp.
References mDependencies.
Referenced by isPrerequisiteForContext().
 {
   return * reinterpret_cast< const CObjectInterface::ObjectSet * >(&mDependencies);
 }
Refresh * CCopasiObject::getRefresh () const virtual
Definition at line 633 of file CCopasiObject.cpp.
References mpRefresh.
Referenced by CFitProblem::calculateStatistics(), COptProblem::calculateStatistics(), CQUpdatesWidget::fillRefreshsMapRecursively(), CModel::getUpdateSequence(), and CDotOutput::writeObjectNode().
 {return mpRefresh;}
std::string CCopasiObject::getUnits () const virtual
Retrieve the units of the object.
Returns
std::string units
Reimplemented in CCopasiContainer.
Definition at line 637 of file CCopasiObject.cpp.
References CCopasiContainer::getChildObjectUnits(), and mpObjectParent.
Referenced by CopasiPlot::setAxisUnits().
 {
   if (mpObjectParent != NULL)
     return mpObjectParent->getChildObjectUnits(this);
   return "";
 }
UpdateMethod * CCopasiObject::getUpdateMethod () const
Definition at line 624 of file CCopasiObject.cpp.
References mpUpdateMethod.
Referenced by COptItem::compile().
 {return mpUpdateMethod;}
const CCopasiObject * CCopasiObject::getValueObject () const virtual
Reimplemented in CMetab, CCopasiMatrixReference< CType >, CCopasiVectorReference< CType >, CModelEntity, CArrayElementReference, CCopasiObjectReference< CType >, CCopasiObjectReference< C_FLOAT64 >, and CCopasiContainer.
Definition at line 555 of file CCopasiObject.cpp.
Referenced by CEvaluationNodeObject::compile(), and CReaction::compile().
 {
   return NULL;
 }
void * CCopasiObject::getValuePointer () const virtual
Retrieve a pointer to the value of the object
Implements CObjectInterface.
Reimplemented in CCopasiParameter, CMetab, CCopasiMatrixReference< CType >, CCopasiVectorReference< CType >, CModelEntity, CCopasiTimer, CArrayElementReference, CCopasiObjectReference< CType >, and CCopasiObjectReference< C_FLOAT64 >.
Definition at line 550 of file CCopasiObject.cpp.
Referenced by CFunctionParameterMap::addCallParameter(), addToInitialValueMap(), CScanWidgetRandom::changeType(), COptItem::compile(), CopasiPlot::compile(), CMathEvent::CAssignment::compile(), CMathObject::compileInitialValue(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CSensMethod::do_variation(), CMathContainer::fetchInitialState(), CMathContainer::fetchState(), COptItem::getStartValue(), CCopasiContainer::getValueObject(), CScanWidgetRandom::initFromObject(), CScanWidgetScan::initFromObject(), CMathContainer::map(), CMathContainer::pushInitialState(), CMathContainer::pushState(), CFunctionParameterMap::setCallParameter(), CTauLeapMethod::start(), CStochDirectMethod::start(), CTrajAdaptiveSA::start(), CTrajectoryMethodDsaLsodar::start(), CScanItem::storeValue(), CSlider::sync(), and CModelParameter::updateModel().
 {
   return NULL;
 }
bool CCopasiObject::hasCircularDependencies (CCopasiObject::DataObjectSet & candidates, CCopasiObject::DataObjectSet & verified, const DataObjectSet & context) const
If called with an empty set it will check whether the current object and all its dependencies (including all indirect) form a circular dependency. If called with a non empty set it check whether the candidates plus the current object and all its dependencies form a circular dependency.
Parameters
DataObjectSet & dependencies
DataObjectSet & verified
const DataObjectSet & context
Returns
bool hasCircularDependencies
Definition at line 395 of file CCopasiObject.cpp.
References getDirectDependencies().
Referenced by CMetab::compileIsInitialConcentrationChangeAllowed(), and dependsOn().
 {
   bool hasCircularDependencies = false;
   if (verified.count(this) != 0)
     return hasCircularDependencies;
   const CCopasiObject::DataObjectSet & DirectDependencies = getDirectDependencies(context);
   CCopasiObject::DataObjectSet::const_iterator it = DirectDependencies.begin();
   CCopasiObject::DataObjectSet::const_iterator end = DirectDependencies.end();
   std::pair<CCopasiObject::DataObjectSet::iterator, bool> Inserted;
   // Dual purpose insert
   Inserted = candidates.insert(this);
   // Check whether the insert was successful, if not
   // the object "this" was among the candidates. Thus we have a detected
   // a circular dependency
   if (Inserted.second)
     {
       for (; it != end && !hasCircularDependencies; ++it)
         {
           hasCircularDependencies = (*it)->hasCircularDependencies(candidates, verified, context);
         }
       // Remove the inserted object this from the candidates to avoid any
       // side effects.
       candidates.erase(this);
     }
   else
     hasCircularDependencies = true;
   // The element has been checked and does not need to be checked again.
   verified.insert(this);
   return hasCircularDependencies;
 }
bool CCopasiObject::hasUpdateMethod () const
Definition at line 627 of file CCopasiObject.cpp.
References mDefaultUpdateMethod, and mpUpdateMethod.
Referenced by CDotOutput::writeDotRecursively(), and CDotOutput::writeObjectNode().
 {return mpUpdateMethod != &mDefaultUpdateMethod;}
bool CCopasiObject::isArray () const
Definition at line 599 of file CCopasiObject.cpp.
References Array, and mObjectFlag.
Referenced by CQSimpleSelectionTree::filter().
 {return (0 < (mObjectFlag & Array));}
bool CCopasiObject::isContainer () const
Comparison operator which can be used to sort objects based on their dependencies If the object *lhs is a dependency of *rhs and must be evaluated first the operator return true.
Parameters
const CCopasiObject * lhs
const CCopasiObject * rhs
Returns
bool isLess
Definition at line 560 of file CCopasiObject.cpp.
References Container, and mObjectFlag.
Referenced by CCopasiObject(), CQUpdatesWidget::fillRefreshsMapRecursively(), CODEExporter::findObjectFromRefresh(), ObjectBrowserWidget::loadChild(), ObjectBrowserWidget::loadField(), operator<<(), and CDotOutput::writeDotRecursively().
 {return (0 < (mObjectFlag & Container));}
bool CCopasiObject::isDataModel () const
Definition at line 602 of file CCopasiObject.cpp.
References DataModel, and mObjectFlag.
Referenced by getCN(), and getObjectDataModel().
 {return (0 < (mObjectFlag & DataModel));}
bool CCopasiObject::isMatrix () const
Definition at line 566 of file CCopasiObject.cpp.
References Matrix, and mObjectFlag.
Referenced by operator<<().
 {return (0 < (mObjectFlag & Matrix));}
bool CCopasiObject::isNameVector () const
Definition at line 569 of file CCopasiObject.cpp.
References mObjectFlag, and NameVector.
Referenced by CArrayAnnotation::createAnnotationsCNFromCopasiVector(), getCN(), getObjectDisplayName(), operator<<(), and setObjectName().
 {return (0 < (mObjectFlag & NameVector));}
bool CCopasiObject::isNonUniqueName () const
Definition at line 587 of file CCopasiObject.cpp.
References mObjectFlag, and NonUniqueName.
 {return (0 < (mObjectFlag & NonUniqueName));}
bool CCopasiObject::isPrerequisiteForContext (const CObjectInterface * pObject, const CMath::SimulationContextFlag & context, const CObjectInterface::ObjectSet & changedObjects) const virtual
Check whether a given object is a prerequisite for a context.
Parameters
const CObjectInterface * pObject
const CMath::SimulationContextFlag & context
const CObjectInterface::ObjectSet & changedObjects
Returns
bool isPrerequisiteForContext
Implements CObjectInterface.
Reimplemented in CParticleReference, CDependentNumberReference, CConcentrationReference, and CTotalNumberReference.
Definition at line 326 of file CCopasiObject.cpp.
References getPrerequisites().
 {
   // If the object is among the changed objects it does not depend on anything else.
   if (changedObjects.find(this) != changedObjects.end())
     return false;
 #ifdef COPASI_DEBUG
   const CObjectInterface::ObjectSet & Prerequisites = getPrerequisites();
   // This method should only be called for objects which are prerequisites.
   // We check for this only in debug mode.
   assert(Prerequisites.find(pObject) != Prerequisites.end());
 #endif // COPASI_DEBUG
   return true;
 }
bool CCopasiObject::isReference () const
Definition at line 572 of file CCopasiObject.cpp.
References mObjectFlag, and Reference.
Referenced by CSBMLExporter::checkForUnsupportedObjectReferences(), contains_necessary_mass_action_elements(), CModelAdd::copyDelayExpression(), CModelAdd::copyEventAssignmentExpression(), CModelAdd::copyExpression(), CModelAdd::copyInitialExpression(), CModelAdd::copyTriggerExpression(), SBMLImporter::doMapping(), CODEExporter::exportExpression(), CODEExporter::exportModelEntityExpression(), CODEExporter::exportSimulatedObject(), CSBMLExporter::findModelEntityDependencies(), getObjectDisplayName(), SBMLImporter::isConstantFlux(), SBMLImporter::isMassActionExpression(), CODEExporter::isModelEntityExpressionODEExporterCompatible(), CModelMerging::mergeInExpression(), operator<<(), CSBMLExporter::replaceSpeciesReferences(), test000093::test_bug1503_1(), test000093::test_bug1503_2(), test000052::test_bug988(), test000047::test_delay(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000032::test_hasOnlySubstanceUnits(), test000033::test_hasOnlySubstanceUnits(), test000034::test_hasOnlySubstanceUnits(), test000035::test_hasOnlySubstanceUnits(), test000038::test_hasOnlySubstanceUnits(), test000039::test_hasOnlySubstanceUnits(), test000036::test_hasOnlySubstanceUnits(), test000040::test_hasOnlySubstanceUnits(), test000041::test_hasOnlySubstanceUnits(), test000021::test_hasOnlySubstanceUnits(), test000042::test_hasOnlySubstanceUnits(), test000043::test_hasOnlySubstanceUnits(), test000022::test_hasOnlySubstanceUnits(), test000023::test_hasOnlySubstanceUnits(), test000037::test_hasOnlySubstanceUnits(), test000024::test_hasOnlySubstanceUnits(), test000025::test_hasOnlySubstanceUnits(), test000026::test_hasOnlySubstanceUnits(), test000027::test_hasOnlySubstanceUnits(), test000028::test_hasOnlySubstanceUnits(), test000029::test_hasOnlySubstanceUnits(), test000030::test_hasOnlySubstanceUnits(), test000031::test_hasOnlySubstanceUnits(), test000082::test_import_delayAssignment_1(), test000082::test_import_delayAssignment_2(), test000082::test_import_delayAssignment_3(), test000082::test_import_delayAssignment_4(), test000082::test_import_delayAssignment_5(), test000082::test_import_delayAssignment_6(), test000082::test_import_delayAssignment_7(), test000082::test_import_delayAssignment_8(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_event_assignment_expression_and_hasOnlySubstanceUnits_8(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), test000087::test_import_reaction_flux_reference_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_1(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_2(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_3(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_4(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_5(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_6(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_7(), test000064::test_import_rule_expression_and_hasOnlySubstanceUnits_8(), test000075::test_import_time_dependent_function_definition(), test000087::test_simulate_reaction_flux_reference_1(), and CEvaluationNodeObject::toAST().
 {return (0 < (mObjectFlag & Reference));}
bool CCopasiObject::isRoot () const
Definition at line 605 of file CCopasiObject.cpp.
References mObjectFlag, and Root.
Referenced by CCopasiContainer::getObject().
 {return (0 < (mObjectFlag & Root));}
bool CCopasiObject::isSeparator () const
Definition at line 596 of file CCopasiObject.cpp.
References mObjectFlag, and Separator.
 {return (0 < (mObjectFlag & Separator));}
bool CCopasiObject::isStaticString () const
Definition at line 590 of file CCopasiObject.cpp.
References mObjectFlag, and StaticString.
Referenced by CReaction::getObject(), and setObjectName().
 {return (0 < (mObjectFlag & StaticString));}
bool CCopasiObject::isValueBool () const
Definition at line 575 of file CCopasiObject.cpp.
References mObjectFlag, and ValueBool.
Referenced by CCopasiVectorReference< CType >::getObject(), CCopasiMatrixReference< CType >::getObject(), operator<<(), CopasiSlider::setValue(), CopasiSlider::updateValue(), and CSlider::writeToObject().
 {return (0 < (mObjectFlag & ValueBool));}
bool CCopasiObject::isValueDbl () const
Definition at line 584 of file CCopasiObject.cpp.
References mObjectFlag, and ValueDbl.
Referenced by CFunctionParameterMap::addCallParameter(), addToInitialValueMap(), SliderSettingsDialog::browseButtonPressed(), CEvaluationNodeObject::compile(), COptItem::compile(), CExperiment::compile(), CopasiPlot::compile(), CExperimentObjectMap::compile(), COptItem::compileLowerBound(), COptItem::compileUpperBound(), CScanItem::CScanItem(), CQSimpleSelectionTree::filter(), CCopasiVectorReference< CType >::getObject(), CCopasiMatrixReference< CType >::getObject(), CSensItem::getVariablesPointerList(), CScanWidgetRandom::initFromObject(), CScanWidgetScan::initFromObject(), operator<<(), CFunctionParameterMap::setCallParameter(), COptItem::setObjectCN(), CSlider::setSliderObject(), CopasiSlider::setValue(), CScanItem::storeValue(), CopasiSlider::updateValue(), and CSlider::writeToObject().
 {return (0 < (mObjectFlag & ValueDbl));}
bool CCopasiObject::isValueInt () const
Definition at line 578 of file CCopasiObject.cpp.
References mObjectFlag, and ValueInt.
Referenced by SliderSettingsDialog::browseButtonPressed(), CopasiPlot::compile(), CQSimpleSelectionTree::filter(), CCopasiVectorReference< CType >::getObject(), CCopasiMatrixReference< CType >::getObject(), operator<<(), CSlider::setSliderObject(), CopasiSlider::setValue(), CopasiSlider::updateValue(), and CSlider::writeToObject().
 {return (0 < (mObjectFlag & ValueInt));}
bool CCopasiObject::isValueInt64 () const
Definition at line 581 of file CCopasiObject.cpp.
References mObjectFlag, and ValueInt64.
Referenced by CQSimpleSelectionTree::filter().
 {return (0 < (mObjectFlag & ValueInt64));}
bool CCopasiObject::isValueString () const
Definition at line 593 of file CCopasiObject.cpp.
References mObjectFlag, and ValueString.
 {return (0 < (mObjectFlag & ValueString));}
bool CCopasiObject::isVector () const
Definition at line 563 of file CCopasiObject.cpp.
References mObjectFlag, and Vector.
Referenced by CArrayAnnotation::createAnnotationsCNFromCopasiVector(), getCN(), getObjectDisplayName(), ObjectBrowserWidget::loadChild(), and operator<<().
 {return (0 < (mObjectFlag & Vector));}
bool CCopasiObject::mustBeDeleted (const DataObjectSet & deletedObjects) const virtual
Check whether an object must be deleted because its prerequisites can no longer be fulfilled due to the given deleted objects
Parameters
const DataObjectSet & deletedObjects
Returns
bool mustBeDeleted
Reimplemented in CMetab, CEvent, CModelEntity, and CReaction.
Definition at line 369 of file CCopasiObject.cpp.
References mDependencies.
 {
   bool MustBeDeleted = false;
   DataObjectSet::const_iterator it = mDependencies.begin();
   DataObjectSet::const_iterator end = mDependencies.end();
   for (; it != end; ++it)
     {
       if (deletedObjects.find(*it) != deletedObjects.end())
         {
           MustBeDeleted = true;
           break;
         }
     }
   return MustBeDeleted;
 }
void CCopasiObject::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Implements CObjectInterface.
Reimplemented in CCopasiParameterGroup, CLReactionGlyph, COptProblem, CLGeneralGlyph, CEigen, CCopasiParameter, CArrayAnnotation, CLMetabReferenceGlyph, CCopasiVectorReference< CType >, CCopasiMethod, CLayout, CLTextGlyph, CCopasiProblem, CCopasiTask::CResult, CSteadyStateTask, CSensProblem, CCrossSectionProblem, CLGraphicalObject, CCopasiTask::CDescription, CLReferenceGlyph, CLNAProblem, CMCAProblem, CFitProblem, CSensTask, CLCompartmentGlyph, CCopasiTimer, CArrayElementReference, COscillationProblem, CCopasiObjectReference< CType >, CCopasiObjectReference< C_FLOAT64 >, CLMetabGlyph, CLGlyphWithCurve, and CCopasiStaticString.
Definition at line 101 of file CCopasiObject.cpp.
 {(*ostream) << (*this);}
void CCopasiObject::removeDirectDependency (const CCopasiObject * pObject)
Remove an object from the direct dependencies
Parameters
const CCopasiObject * pObject
Definition at line 315 of file CCopasiObject.cpp.
References mDependencies.
Referenced by CReaction::setFunction(), and CReaction::setFunctionFromExpressionTree().
 {
   mDependencies.erase(pObject);
   return;
 }
void CCopasiObject::setDirectDependencies (const DataObjectSet & directDependencies)
Set the direct dependencies
Parameters
const Set & directDependencies
Definition at line 298 of file CCopasiObject.cpp.
References mDependencies.
Referenced by CEventAssignment::compile(), CModelEntity::compile(), CMathEvent::CAssignment::compile(), CMetab::compile(), CReaction::compile(), CMetab::compileInitialValueDependencies(), CEvaluationTree::initObjects(), CReaction::setScalingFactor(), CModelEntity::setStatus(), and CMetab::setStatus().
 {
   mDependencies = directDependencies;
 }
bool CCopasiObject::setObjectName (const std::string & name)
Set the name of the object. Note: An attempt set the name to "" results in the name being set to "No Name".
Parameters
const std::string & name
Returns
success
Definition at line 158 of file CCopasiObject.cpp.
References CCopasiObjectName::escape(), getCN(), CCopasiContainer::getObject(), CRenameHandler::handle(), isNameVector(), isStaticString(), mObjectName, mpObjectParent, and smpRenameHandler.
Referenced by CFunctionDB::addAndAdaptName(), CExperimentSet::addExperiment(), CQReportDefinition::btnCopyReportClicked(), CCopasiMethod::CCopasiMethod(), CModelEntity::compile(), CMetab::compile(), CLRenderFlattener::convertGlobalToLocalStyle(), CMathExpression::convertToInitialExpression(), CQPlotSubwidget::copyPlot(), CPlotItem::CPlotItem(), SBMLImporter::createCFunctionFromFunctionDefinition(), SBMLImporter::createCModelFromSBMLDocument(), SBMLImporter::createCReactionFromReaction(), COutputDefinitionVector::createPlotSpec(), CReportDefinitionVector::createReportDefinition(), CFitProblem::elevateChildren(), CCompartment::initObjects(), CMetab::initObjects(), CModel::initObjects(), CCompartment::load(), CReaction::load(), CFunctionParameter::load(), CModel::load(), CFunction::load(), CConfigurationFile::CXML::load(), CMetab::load(), CMetabOld::load(), CCopasiStaticString::operator=(), CLGraphicalObject::operator=(), CCopasiParameterGroup::operator=(), CCopasiParameter::operator=(), CMetab::operator=(), SBMLImporter::renameMassActionParameters(), CModelExpansion::replaceInMetab(), CQTabWidget::save(), CQReportDefinition::save(), CQExperimentData::saveExperiment(), CQReportDM::setData(), CQPlotDM::setData(), CQFunctionDM::setData(), CQReactionDM::setData(), CQEventDM::setData(), CQGlobalQuantityDM::setData(), CQCompartmentDM::setData(), CQSpecieDM::setData(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CReaction::setFunctionFromExpressionTree(), CModelEntity::setInitialExpressionPtr(), CChemEqElement::setMetabolite(), CEvent::setPriorityExpressionPtr(), CModelEntity::setStatus(), CEventAssignment::setTargetKey(), CPlotItem::setTitle(), CEvent::setTriggerExpressionPtr(), CQParameterOverviewWidget::slotBtnCopy(), CQParameterOverviewWidget::slotBtnNew(), CQLayoutsWidget::slotBtnNewClicked(), CQParameterOverviewWidget::slotBtnSaveAs(), CFunction::splitFunction(), CCopasiXMLParser::ModelParameterSetElement::start(), CCopasiXMLParser::SourceParameterElement::start(), CCopasiXMLParser::ReactionElement::start(), CCopasiXMLParser::EventElement::start(), CCopasiXMLParser::ModelElement::start(), CCopasiXMLParser::PlotSpecificationElement::start(), CCopasiXMLParser::MethodElement::start(), CCopasiXMLParser::ReportElement::start(), CCopasiXMLParser::ParameterDescriptionElement::start(), CCopasiXMLParser::FunctionElement::start(), and CCopasiXMLParser::LayoutElement::start().
 {
   std::string Name = (name == "") ? "No Name" : name;
   if (!isStaticString())
     {
       // We need to ensure that the name does not include any whitespace character except ' ' (space),
       // i.e., we convert '\t' (tab), '\n' (newline) and '\r' (return) to ' ' (space).
       std::string::iterator it = Name.begin();
       std::string::iterator end = Name.end();
       for (; it != end; ++it)
         {
           switch (*it)
             {
               case '\t':
               case '\n':
               case '\r':
                 *it = ' ';
                 break;
               default:
                 break;
             }
         }
     }
   if (Name == mObjectName) return true;
   if (mpObjectParent &&
       mpObjectParent->isNameVector() &&
       mpObjectParent->getObject("[" + CCopasiObjectName::escape(Name) + "]"))
     return false;
   if (smpRenameHandler && mpObjectParent)
     {
       std::string oldCN = this->getCN();
       mObjectName = Name;
       std::string newCN = this->getCN();
       smpRenameHandler->handle(oldCN, newCN);
       //TODO performance considerations.
       //Right now after every rename the CNs are checked. In some cases
       //we may know that this is not necessary
     }
   else
     {mObjectName = Name;}
   if (mpObjectParent)
     {
       mpObjectParent->CCopasiContainer::remove(this);
       mpObjectParent->CCopasiContainer::add(this, false);
     }
   return true;
 }
bool CCopasiObject::setObjectParent (const CCopasiContainer * pParent) virtual
Reimplemented in CMetab, CMoiety, CEvent, CModelEntity, CReaction, CEventAssignment, and CModelParameterSet.
Definition at line 262 of file CCopasiObject.cpp.
References mpObjectParent, and CCopasiContainer::remove().
Referenced by CCopasiContainer::add(), CMathContainer::CMathContainer(), CCopasiDataModel::commonAfterLoad(), CQValidatorExpression::CQValidatorExpression(), CQValidatorFunction::CQValidatorFunction(), COptMethodSS::initialize(), CEvent::setDelayExpressionPtr(), CEventAssignment::setExpressionPtr(), CModelEntity::setExpressionPtr(), CModelEntity::setInitialExpressionPtr(), CModelParameterSet::setObjectParent(), CEventAssignment::setObjectParent(), CReaction::setObjectParent(), CModelEntity::setObjectParent(), CEvent::setObjectParent(), CMoiety::setObjectParent(), CEvent::setPriorityExpressionPtr(), and CEvent::setTriggerExpressionPtr().
 {
   if (pParent == mpObjectParent)
     return true;
   if (mpObjectParent != NULL &&
       pParent != NULL)
     mpObjectParent->remove(this);
   mpObjectParent = const_cast<CCopasiContainer *>(pParent);
   return true;
 }
void CCopasiObject::setObjectValue (const C_FLOAT64 & value)
Definition at line 615 of file CCopasiObject.cpp.
Referenced by CScanItem::restoreValue(), CopasiSlider::setValue(), CSensMethod::setValue(), CScanItemLinear::step(), CScanItemRandom::step(), CopasiSlider::updateValue(), and CSlider::writeToObject().
 {(*mpUpdateMethod)(value);}
void CCopasiObject::setObjectValue (const C_INT32 & value)
Definition at line 618 of file CCopasiObject.cpp.
 {(*mpUpdateMethod)(value);}
void CCopasiObject::setObjectValue (const bool & value)
Definition at line 621 of file CCopasiObject.cpp.
 {(*mpUpdateMethod)(value);}
template<class CType > void CCopasiObject::setRefresh (CType * pType, void(CType::*)(void) method) inline
Definition at line 544 of file CCopasiObject.h.
References Refresh::isEqual(), mpRefresh, and pdelete.
Referenced by CCopasiTimer::CCopasiTimer(), CMetab::compile(), CReaction::compile(), CMathTrigger::CRootFinder::initObjects(), CExpression::initObjects(), CMoiety::initObjects(), CModelEntity::initObjects(), CMetab::initObjects(), CReaction::initObjects(), CModelEntity::setStatus(), and CMetab::setStatus().
   {
     Refresh * pRefresh =
       new RefreshTemplate< CType >(pType, method);
     if (mpRefresh != NULL &&
         mpRefresh->isEqual(pRefresh))
       {
         delete pRefresh;
       }
     else
       {
         pdelete(mpRefresh);
         mpRefresh = pRefresh;
       }
     return;
   }
static void CCopasiObject::setRenameHandler (CRenameHandler * rh) inline static
Definition at line 568 of file CCopasiObject.h.
References smpRenameHandler.
Referenced by CCopasiDataModel::CCopasiDataModel(), and CCopasiDataModel::~CCopasiDataModel().
   {smpRenameHandler = rh;}
template<class CType > void CCopasiObject::setUpdateMethod (CType * pType, void(CType::*)(const C_FLOAT64 &) method) inline
Definition at line 501 of file CCopasiObject.h.
References mDefaultUpdateMethod, mpUpdateMethod, and pdelete.
Referenced by CCopasiObjectReference< CType >::CCopasiObjectReference(), CTrajectoryProblem::initObjects(), CTSSAProblem::initObjects(), and CModelEntity::initObjects().
   {
     if (mpUpdateMethod != &mDefaultUpdateMethod)
       pdelete(mpUpdateMethod);
     mpUpdateMethod =
       new SpecificUpdateMethod< CType, C_FLOAT64 >(pType, method);
     return;
   }
template<class CType > void CCopasiObject::setUpdateMethod (CType * pType, void(CType::*)(const C_INT32 &) method) inline
Definition at line 514 of file CCopasiObject.h.
References mDefaultUpdateMethod, mpUpdateMethod, and pdelete.
   {
     if (mpUpdateMethod != &mDefaultUpdateMethod)
       pdelete(mpUpdateMethod);
     mpUpdateMethod =
       new SpecificUpdateMethod< CType, C_INT32 >(pType, method);
     return;
   }
template<class CType > void CCopasiObject::setUpdateMethod (CType * pType, void(CType::*)(const bool &) method) inline
Definition at line 527 of file CCopasiObject.h.
References mDefaultUpdateMethod, mpUpdateMethod, and pdelete.
   {
     if (mpUpdateMethod != &mDefaultUpdateMethod)
       pdelete(mpUpdateMethod);
     mpUpdateMethod =
       new SpecificUpdateMethod< CType, bool >(pType, method);
     return;
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiObject & o) friend
Definition at line 645 of file CCopasiObject.cpp.
 {
   os << "Name:      " << o.getObjectDisplayName() << std::endl;
   os << "Type:      " << o.getObjectType() << std::endl;
   os << "Container: " << o.isContainer() << std::endl;
   os << "Vector:    " << o.isVector() << std::endl;
   os << "VectorN:   " << o.isNameVector() << std::endl;
   os << "Matrix:    " << o.isMatrix() << std::endl;
   os << "Reference: " << o.isReference() << std::endl;
   os << "Bool:      " << o.isValueBool() << std::endl;
   os << "Int:       " << o.isValueInt() << std::endl;
   os << "Dbl:       " << o.isValueDbl() << std::endl;
   return os;
 }
Member Data Documentation
const C_FLOAT64 CCopasiObject::DummyValue = 0.0 static private
Class CCopasiObject
This class is the base class for all global accessible objects in COPASI.
Copyright Stefan Hoops 2002
Definition at line 276 of file CCopasiObject.h.
UpdateMethod CCopasiObject::mDefaultUpdateMethod static private
Definition at line 278 of file CCopasiObject.h.
Referenced by hasUpdateMethod(), setUpdateMethod(), and ~CCopasiObject().
DataObjectSet CCopasiObject::mDependencies private
A list of all objects the object depends on directly, i.e, the objects which are used to calculate the object.
Definition at line 268 of file CCopasiObject.h.
Referenced by addDirectDependency(), clearDirectDependencies(), getDirectDependencies(), getPrerequisites(), mustBeDeleted(), removeDirectDependency(), and setDirectDependencies().
unsigned C_INT32 CCopasiObject::mObjectFlag private
Definition at line 261 of file CCopasiObject.h.
Referenced by isArray(), isContainer(), isDataModel(), isMatrix(), isNameVector(), isNonUniqueName(), isReference(), isRoot(), isSeparator(), isStaticString(), isValueBool(), isValueDbl(), isValueInt(), isValueInt64(), isValueString(), and isVector().
std::string CCopasiObject::mObjectName private
Definition at line 253 of file CCopasiObject.h.
Referenced by getCN(), getObjectName(), and setObjectName().
std::string CCopasiObject::mObjectType private
Definition at line 255 of file CCopasiObject.h.
Referenced by getCN(), and getObjectType().
CCopasiStaticString* CCopasiObject::mpObjectDisplayName mutable private
Definition at line 259 of file CCopasiObject.h.
Referenced by getObject(), and ~CCopasiObject().
CCopasiContainer* CCopasiObject::mpObjectParent private
Definition at line 257 of file CCopasiObject.h.
Referenced by CCopasiObject(), getCN(), getObjectDisplayName(), getObjectParent(), getUnits(), setObjectName(), setObjectParent(), and ~CCopasiObject().
Refresh* CCopasiObject::mpRefresh private
Definition at line 274 of file CCopasiObject.h.
Referenced by clearRefresh(), getRefresh(), setRefresh(), and ~CCopasiObject().
UpdateMethod* CCopasiObject::mpUpdateMethod private
Definition at line 272 of file CCopasiObject.h.
Referenced by getUpdateMethod(), hasUpdateMethod(), setUpdateMethod(), and ~CCopasiObject().
CRenameHandler * CCopasiObject::smpRenameHandler = NULL static protected
Definition at line 281 of file CCopasiObject.h.
Referenced by CCompartment::addMetabolite(), CModel::compile(), setObjectName(), and setRenameHandler().
The documentation for this class was generated from the following files:
CCopasiObject.h
CCopasiObject.cpp