COPASI API: CQAnimationSettingsEditor Class Reference
CQAnimationSettingsEditor Class Reference
#include <CQAnimationSettingsEditor.h>
Public Slots
void slotEffectAdded ()
void slotEffectRemoved ()
void slotScaleModeChanged ()
void slotSelectionChanged ()
Public Member Functions
CQAnimationSettingsEditor (QWidget *parent=0, Qt::WindowFlags f=0)
void initFrom (CQCopasiAnimation *other)
void saveChanges ()
void saveTo (CQCopasiAnimation *target)
virtual ~CQAnimationSettingsEditor ()
Protected Attributes
std::vector
< CQEffectDescription * > mEntries
QList< QListWidgetItem * > mLastSelection
Detailed Description
Definition at line 16 of file CQAnimationSettingsEditor.h.
Constructor & Destructor Documentation
CQAnimationSettingsEditor::CQAnimationSettingsEditor (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 10 of file CQAnimationSettingsEditor.cpp.
   : QDialog(parent, f)
 {
   setupUi(this);
 }
CQAnimationSettingsEditor::~CQAnimationSettingsEditor () virtual
Definition at line 16 of file CQAnimationSettingsEditor.cpp.
 {
 }
Member Function Documentation
void CQAnimationSettingsEditor::initFrom (CQCopasiAnimation * other)
Definition at line 60 of file CQAnimationSettingsEditor.cpp.
References CQEffectDescription::getCN(), CQCopasiAnimation::getEntries(), CQCopasiAnimation::getScaleMode(), CQCopasiAnimation::Global, and mEntries.
Referenced by CQAnimationWindow::slotEditSettings().
 {
   if (other->getScaleMode() == CQCopasiAnimation::Global)
     radGlobal->setChecked(true);
   else
     radIndividual->setChecked(true);
   std::vector<CQEffectDescription*> entries = other->getEntries();
   std::vector<CQEffectDescription*>::iterator it = entries.begin();
   mEntries.clear();
   while (it != entries.end())
     {
       CQEffectDescription* current = *it;
       QListWidgetItem* item = new QListWidgetItem(current->getCN().c_str());
       item->setData(Qt::UserRole, (int)mEntries.size());
       listWidget->addItem(item);
       mEntries.push_back(current);
       ++it;
     }
 }
void CQAnimationSettingsEditor::saveChanges ()
Definition at line 32 of file CQAnimationSettingsEditor.cpp.
References mEntries, and mLastSelection.
Referenced by saveTo(), and slotSelectionChanged().
 {
   // go through last selection to save changes
   for (int i = 0; i < mLastSelection.size(); ++i)
     {
       QListWidgetItem* current = mLastSelection[i];
       int index = current->data(Qt::UserRole).toInt();
       widget->saveTo(mEntries[index], mLastSelection.size() > 1);
     }
 }
void CQAnimationSettingsEditor::saveTo (CQCopasiAnimation * target)
Definition at line 84 of file CQAnimationSettingsEditor.cpp.
References CQCopasiAnimation::Global, CQCopasiAnimation::Individual, saveChanges(), and CQCopasiAnimation::setScaleMode().
Referenced by CQAnimationWindow::slotEditSettings().
 {
   saveChanges();
   if (radGlobal->isChecked())
     target->setScaleMode(CQCopasiAnimation::Global);
   else
     target->setScaleMode(CQCopasiAnimation::Individual);
 }
void CQAnimationSettingsEditor::slotEffectAdded () slot
Definition at line 24 of file CQAnimationSettingsEditor.cpp.
 {
 }
void CQAnimationSettingsEditor::slotEffectRemoved () slot
Definition at line 28 of file CQAnimationSettingsEditor.cpp.
 {
 }
void CQAnimationSettingsEditor::slotScaleModeChanged () slot
Definition at line 20 of file CQAnimationSettingsEditor.cpp.
 {
 }
void CQAnimationSettingsEditor::slotSelectionChanged () slot
Definition at line 43 of file CQAnimationSettingsEditor.cpp.
References mEntries, mLastSelection, and saveChanges().
 {
   saveChanges();
   // fill with new entries
   QList<QListWidgetItem*> selected = listWidget->selectedItems();
   for (int i = 0; i < selected.size(); ++i)
     {
       QListWidgetItem* current = selected[i];
       int index = current->data(Qt::UserRole).toInt();
       widget->initFrom(mEntries[index], selected.size() > 1);
     }
   mLastSelection = selected;
 }
Member Data Documentation
std::vector<CQEffectDescription*> CQAnimationSettingsEditor::mEntries protected
Definition at line 31 of file CQAnimationSettingsEditor.h.
Referenced by initFrom(), saveChanges(), and slotSelectionChanged().
QList<QListWidgetItem*> CQAnimationSettingsEditor::mLastSelection protected
Definition at line 32 of file CQAnimationSettingsEditor.h.
Referenced by saveChanges(), and slotSelectionChanged().
The documentation for this class was generated from the following files:
CQAnimationSettingsEditor.h
CQAnimationSettingsEditor.cpp