COPASI API: test000078 Class Reference
test000078 Class Reference
#include <test000078.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_l2v4_import_unordered_functions ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_l2v4_import_unordered_functions)
CPPUNIT_TEST_SUITE (test000078)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 26 of file test000078.h.
Member Function Documentation
test000078::CPPUNIT_TEST (test_l2v4_import_unordered_functions) private
test000078::CPPUNIT_TEST_SUITE (test000078) private
test000078::CPPUNIT_TEST_SUITE_END () private
void test000078::setUp ()
Definition at line 38 of file test000078.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000078::tearDown ()
Definition at line 46 of file test000078.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000078::test_l2v4_import_unordered_functions ()
Definition at line 51 of file test000078.cpp.
References CEvaluationNodeVariable::ANY, CModelEntity::ASSIGNMENT, CEvaluationNode::CALL, CEvaluationNodeOperator::DIVIDE, CEvaluationNodeNumber::DOUBLE, CModelEntity::FIXED, CEvaluationNodeCall::FUNCTION, CModel::getCompartments(), CEvaluationNodeCall::getData(), CCopasiNode< _Data >::getData(), CCopasiRootContainer::getFunctionList(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CModel::getModelValues(), CModel::getQuantityUnitEnum(), CModel::getReactions(), CEvaluationTree::getRoot(), CModel::getTimeUnitEnum(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CFunction::getVariables(), CModel::getVolumeUnitEnum(), CCopasiDataModel::importSBMLFromString(), CModel::l, CEvaluationNodeOperator::MINUS, MODEL_STRING1, CModel::Mol, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::NUMBER, CModelEntity::ODE, CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CEvaluationNodeOperator::PLUS, CModelEntity::REACTIONS, CModel::s, CFunctionParameters::size(), CCopasiVector< T >::size(), CEvaluationNode::subType(), CEvaluationNode::type(), CEvaluationTree::UserDefined, and CEvaluationNode::VARIABLE.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   try
     {
       CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
     }
   catch (...)
     {
       // there should not be any exceptions
       CPPUNIT_ASSERT(false);
     }
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::Mol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::l);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   // check if the function definitions were imported correctly
   CFunctionDB* pFunDB = CCopasiRootContainer::getFunctionList();
   const CEvaluationTree* pFun = pFunDB->findFunction("function_1");
   CPPUNIT_ASSERT(pFun != NULL);
   const CKinFunction* pKinFun = dynamic_cast<const CKinFunction*>(pFun);
   CPPUNIT_ASSERT(pKinFun != NULL);
   // 1 parameter called k
   // expression is 3.0 * k
   const CFunctionParameters* pFunParams = &pKinFun->getVariables();
   CPPUNIT_ASSERT(pFunParams != NULL);
   CPPUNIT_ASSERT(pFunParams->size() == 1);
   const CFunctionParameter* pFunParam = (*pFunParams)[0];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("k"));
   const CEvaluationNode* pRoot = pKinFun->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::MULTIPLY);
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 3.0) / 3.0) < 1e-6);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   const CEvaluationNodeVariable* pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("k"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild == NULL);
   pFun = pFunDB->findFunction("function_2");
   CPPUNIT_ASSERT(pFun != NULL);
   pKinFun = dynamic_cast<const CKinFunction*>(pFun);
   CPPUNIT_ASSERT(pKinFun != NULL);
   // 2 parameters called A and B
   // expression is A + B
   pFunParams = &pKinFun->getVariables();
   CPPUNIT_ASSERT(pFunParams != NULL);
   CPPUNIT_ASSERT(pFunParams->size() == 2);
   pFunParam = (*pFunParams)[0];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("A"));
   pFunParam = (*pFunParams)[1];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("B"));
   pRoot = pKinFun->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("B"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("A"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild == NULL);
   pFun = pFunDB->findFunction("function_3");
   CPPUNIT_ASSERT(pFun != NULL);
   pKinFun = dynamic_cast<const CKinFunction*>(pFun);
   CPPUNIT_ASSERT(pKinFun != NULL);
   // 2 parameters called k and C
   // expression is C - (k * 1.3)
   pFunParams = &pKinFun->getVariables();
   CPPUNIT_ASSERT(pFunParams != NULL);
   CPPUNIT_ASSERT(pFunParams->size() == 2);
   pFunParam = (*pFunParams)[0];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("k"));
   pFunParam = (*pFunParams)[1];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("C"));
   pRoot = pKinFun->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::MINUS);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("C"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("k"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 1.3) / 1.3) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pFun = pFunDB->findFunction("function_4");
   CPPUNIT_ASSERT(pFun != NULL);
   pKinFun = dynamic_cast<const CKinFunction*>(pFun);
   CPPUNIT_ASSERT(pKinFun != NULL);
   // 2 parameters called x and y
   // expression is function_2(x,y)/2.0
   pFunParams = &pKinFun->getVariables();
   CPPUNIT_ASSERT(pFunParams != NULL);
   CPPUNIT_ASSERT(pFunParams->size() == 2);
   pFunParam = (*pFunParams)[0];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("x"));
   pFunParam = (*pFunParams)[1];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("y"));
   pRoot = pKinFun->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::DIVIDE);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::CALL);
   CPPUNIT_ASSERT((CEvaluationNodeCall::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeCall::FUNCTION);
   const CEvaluationNodeCall* pCallNode = dynamic_cast<const CEvaluationNodeCall*>(pChild);
   CPPUNIT_ASSERT(pCallNode != NULL);
   CPPUNIT_ASSERT(pCallNode->getData() == std::string("function_2"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("x"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("y"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild()->getSibling());
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild == NULL);
   pFun = pFunDB->findFunction("function_5");
   CPPUNIT_ASSERT(pFun != NULL);
   pKinFun = dynamic_cast<const CKinFunction*>(pFun);
   CPPUNIT_ASSERT(pKinFun != NULL);
   // 3 parameters called a, b  and c
   // expression is function_3(c,a) + (function_1(b) - 5.23)
   pFunParams = &pKinFun->getVariables();
   CPPUNIT_ASSERT(pFunParams != NULL);
   CPPUNIT_ASSERT(pFunParams->size() == 3);
   pFunParam = (*pFunParams)[0];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("a"));
   pFunParam = (*pFunParams)[1];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("b"));
   pFunParam = (*pFunParams)[2];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("c"));
   pRoot = pKinFun->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::CALL);
   CPPUNIT_ASSERT((CEvaluationNodeCall::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeCall::FUNCTION);
   pCallNode = dynamic_cast<const CEvaluationNodeCall*>(pChild);
   CPPUNIT_ASSERT(pCallNode != NULL);
   CPPUNIT_ASSERT(pCallNode->getData() == std::string("function_3"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("c"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("a"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild()->getSibling());
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MINUS);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::CALL);
   CPPUNIT_ASSERT((CEvaluationNodeCall::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeCall::FUNCTION);
   pCallNode = dynamic_cast<const CEvaluationNodeCall*>(pChild);
   CPPUNIT_ASSERT(pCallNode != NULL);
   CPPUNIT_ASSERT(pCallNode->getData() == std::string("function_1"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("b"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild()->getSibling()->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::NUMBER);
   CPPUNIT_ASSERT((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeNumber::DOUBLE);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pChild);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 5.23) / 5.23) < 1e-6);
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   pFun = pFunDB->findFunction("function_6");
   CPPUNIT_ASSERT(pFun != NULL);
   pKinFun = dynamic_cast<const CKinFunction*>(pFun);
   CPPUNIT_ASSERT(pKinFun != NULL);
   // 3 parameters called k1, k2 and k3
   // expression is function_5(k1,k2,k3)
   pFunParams = &pKinFun->getVariables();
   CPPUNIT_ASSERT(pFunParams != NULL);
   CPPUNIT_ASSERT(pFunParams->size() == 3);
   pFunParam = (*pFunParams)[0];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("k1"));
   pFunParam = (*pFunParams)[1];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("k2"));
   pFunParam = (*pFunParams)[2];
   CPPUNIT_ASSERT(pFunParam != NULL);
   CPPUNIT_ASSERT(pFunParam->getObjectName() == std::string("k3"));
   pRoot = pKinFun->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::CALL);
   CPPUNIT_ASSERT((CEvaluationNodeCall::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeCall::FUNCTION);
   pCallNode = dynamic_cast<const CEvaluationNodeCall*>(pRoot);
   CPPUNIT_ASSERT(pCallNode != NULL);
   CPPUNIT_ASSERT(pCallNode->getData() == std::string("function_5"));
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("k1"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("k2"));
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   CPPUNIT_ASSERT((CEvaluationNodeVariable::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeVariable::ANY);
   pVarNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVarNode != NULL);
   CPPUNIT_ASSERT(pVarNode->getData() == std::string("k3"));
   CPPUNIT_ASSERT(pChild->getSibling() == NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 6);
   // check metabolites
   const CMetab* pMetab = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "A");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::REACTIONS);
   pMetab = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "B");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::REACTIONS);
   pMetab = pModel->getMetabolites()[2];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "C");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ASSIGNMENT);
   // check assignment
   const CEvaluationTree* pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_5");
   pMetab = pModel->getMetabolites()[3];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "D");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ODE);
   // check ode
   pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_2");
   pMetab = pModel->getMetabolites()[4];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "E");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ODE);
   // check ode
   pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_4");
   pMetab = pModel->getMetabolites()[5];
   CPPUNIT_ASSERT(pMetab != NULL);
   CPPUNIT_ASSERT(pMetab->getObjectName() == "F");
   CPPUNIT_ASSERT(pMetab->getStatus() == CModelEntity::ODE);
   // check ode
   pTree = pMetab->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_6");
   // check model values
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 3);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "K1");
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::ASSIGNMENT);
   // check assignment
   pTree = pModelValue->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_1");
   pModelValue = pModel->getModelValues()[1];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "K2");
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   pModelValue = pModel->getModelValues()[2];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "K3");
   // check assignment
   pTree = pModelValue->getExpressionPtr();
   CPPUNIT_ASSERT(pTree != NULL);
   pRoot = pTree->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot) != NULL);
   CPPUNIT_ASSERT(dynamic_cast<const CEvaluationNodeCall*>(pRoot)->getData() == "function_3");
   CPPUNIT_ASSERT(pModel->getReactions().size() == 6);
   // check reactions
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction1");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[1];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 2);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction2");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[2];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 1);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction3");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[3];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 0);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction4");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[4];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 2);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction5");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   pReaction = pModel->getReactions()[5];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 1);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == true);
   // check the kinetic law
   CPPUNIT_ASSERT(pReaction->getParameters().size() == 3);
   pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->getObjectName() == "Function for reaction6");
   pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
 }
Member Data Documentation
const char * test000078::MODEL_STRING1 static protected
Definition at line 33 of file test000078.h.
Referenced by test_l2v4_import_unordered_functions().
CCopasiDataModel * test000078::pCOPASIDATAMODEL = NULL static protected
Definition at line 34 of file test000078.h.
Referenced by setUp(), and test_l2v4_import_unordered_functions().
The documentation for this class was generated from the following files:
test000078.h
test000078.cpp