COPASI API: CCopasiXMLParser::MetaboliteElement Class Reference
CCopasiXMLParser::MetaboliteElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
MetaboliteElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~MetaboliteElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
Metabolite = 0, MiriamAnnotation, Comment, ListOfUnsupportedAnnotations,
Expression, InitialExpression
}
Private Attributes
std::string mKey
CMetab * mpMetabolite
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 1244 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::MetaboliteElement::Element private
Enum of invoked parsers
Enumerator
Metabolite
MiriamAnnotation
Comment
ListOfUnsupportedAnnotations
Expression
InitialExpression
Definition at line 1252 of file CCopasiXMLParser.h.
     {
       Metabolite = 0,
       MiriamAnnotation,
       Comment,
       ListOfUnsupportedAnnotations,
       Expression,
       InitialExpression
     };
Constructor & Destructor Documentation
CCopasiXMLParser::MetaboliteElement::MetaboliteElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 2526 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mpMetabolite(NULL)
 {}
CCopasiXMLParser::MetaboliteElement::~MetaboliteElement () virtual
Destructor
Definition at line 2532 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::MetaboliteElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 2652 of file CCopasiXMLParser.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Metabolite:
         if (strcmp(pszName, "Metabolite"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Metabolite", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case MiriamAnnotation:
         if (strcmp(pszName, "MiriamAnnotation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "MiriamAnnotation", mParser.getCurrentLineNumber());
         mpMetabolite->setMiriamAnnotation(mCommon.CharacterData, mpMetabolite->getKey(), mKey);
         mCommon.CharacterData = "";
         break;
       case Comment:
         if (strcmp(pszName, "Comment"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Comment", mParser.getCurrentLineNumber());
         mpMetabolite->setNotes(mCommon.CharacterData);
         mCommon.CharacterData = "";
         break;
       case ListOfUnsupportedAnnotations:
         if (strcmp(pszName, "ListOfUnsupportedAnnotations"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfUnsupportedAnnotations", mParser.getCurrentLineNumber());
         mpMetabolite->getUnsupportedAnnotations() = mParser.mListOfUnsupportedAnnotationsElement.getUnsupportedAnnotations();
         break;
       case Expression:
         if (strcmp(pszName, "Expression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Expression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpMetabolite->setExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case InitialExpression:
         if (strcmp(pszName, "InitialExpression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialExpression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mpMetabolite->setInitialExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         break;
       case UNKNOWN_ELEMENT:
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   mCurrentElement = Metabolite;
   return;
 }
void CCopasiXMLParser::MetaboliteElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 2535 of file CCopasiXMLParser.cpp.
References CCopasiVector< T >::add(), CCompartment::addMetabolite(), CCopasiMessage::EXCEPTION, fatalError, CKeyFactory::get(), CModel::getMetabolites(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pModel, CModelEntity::REACTIONS, toEnum(), UNKNOWN_ELEMENT, and CModelEntity::XMLStatus.
 {
   CCompartment * pCompartment = NULL;
   const char * Name;
   const char * simulationType;
   CModelEntity::Status SimulationType;
   const char reactions[] = "reactions";
   const char * Compartment;
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case Metabolite:
             if (strcmp(pszName, "Metabolite"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "Metabolite", mParser.getCurrentLineNumber());
             mKey = mParser.getAttributeValue("key", papszAttrs);
             Name = mParser.getAttributeValue("name", papszAttrs);
             simulationType = mParser.getAttributeValue("simulationType", papszAttrs, false);
             // We need to handle old files which used the attribute status.
             if (!simulationType)
               {
                 simulationType = mParser.getAttributeValue("status", papszAttrs, false);
                 if (!simulationType) // status and simulationType are both missing
                   simulationType = mParser.getAttributeValue("simulationType", papszAttrs);
                 else if (!strcmp(simulationType, "variable")) // reactions was named variable
                   simulationType = reactions;
               }
             SimulationType = toEnum(simulationType, CModelEntity::XMLStatus, CModelEntity::REACTIONS);
             Compartment = mParser.getAttributeValue("compartment", papszAttrs);
             mpMetabolite = new CMetab();
             addFix(mKey, mpMetabolite);
             mpMetabolite->setObjectName(Name);
             mpMetabolite->setStatus(SimulationType);
             pCompartment =
               dynamic_cast< CCompartment* >(mCommon.KeyMap.get(Compartment));
             if (!pCompartment) fatalError();
             pCompartment->addMetabolite(mpMetabolite);
             mCommon.pModel->getMetabolites().add(mpMetabolite);
             mLastKnownElement = mCurrentElement;
             return;
           case MiriamAnnotation:
             if (!strcmp(pszName, "MiriamAnnotation"))
               mpCurrentHandler = &mParser.mMiriamAnnotationElement;
             break;
           case Comment:
             if (!strcmp(pszName, "Comment"))
               {
                 mpCurrentHandler = &mParser.mCommentElement;
                 mLastKnownElement = mCurrentElement;
               }
             break;
           case ListOfUnsupportedAnnotations:
             if (!strcmp(pszName, "ListOfUnsupportedAnnotations"))
               mpCurrentHandler = &mParser.mListOfUnsupportedAnnotationsElement;
             break;
           case Expression:
             if (!strcmp(pszName, "Expression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           case InitialExpression:
             if (!strcmp(pszName, "InitialExpression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
std::string CCopasiXMLParser::MetaboliteElement::mKey private
The key in the CopasiML file
Definition at line 1298 of file CCopasiXMLParser.h.
CMetab* CCopasiXMLParser::MetaboliteElement::mpMetabolite private
A pointer to the current metabolite.
Definition at line 1293 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp