COPASI API: StateSubwidget Class Reference
StateSubwidget Class Reference
#include <StateSubwidget.h>
Public Member Functions
void clear ()
virtual bool loadAll (const CSteadyStateTask *pTask)
virtual void setFramework (int framework)
StateSubwidget (QWidget *parent=0, const char *name=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~StateSubwidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual void init ()
void loadCompartments ()
void loadJacobian ()
void loadMetabolites ()
void loadModelValues ()
void loadReactions ()
void showUnits ()
Protected Member Functions inherited from CopasiWidget
virtual bool enterProtected ()
Protected Attributes
CModel * mpModel
const CSteadyStateTask * mpTask
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 31 of file StateSubwidget.h.
Constructor & Destructor Documentation
StateSubwidget::StateSubwidget (QWidget * parent = 0, const char * name = 0)
Definition at line 44 of file StateSubwidget.cpp.
References init().
     : CopasiWidget(parent, name)
 {
   setupUi(this);
   init();
 }
StateSubwidget::~StateSubwidget ()
Definition at line 55 of file StateSubwidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void StateSubwidget::clear ()
Definition at line 364 of file StateSubwidget.cpp.
Referenced by loadAll(), and update().
 {
   topLabel->setText("No result available, please execute the steady-state task.");
   mpTblMetabolites->setRowCount(0);
   mpTblCompartments->setRowCount(0);
   mpTblModelValues->setRowCount(0);
   mpTblReactions->setRowCount(0);
   mpJacobianAnnotationWidget->setArrayAnnotation(NULL);
   mpJacobianXAnnotationWidget->setArrayAnnotation(NULL);
   tableEigenValues->setRowCount(0);
   tableEigenValuesX->setRowCount(0);
   stabilityTextEdit->setText("");
   protocolTextEdit->setText("");
 }
void StateSubwidget::init () protected virtual
Definition at line 60 of file StateSubwidget.cpp.
References CopasiWidget::mFramework, mpModel, mpTask, and setFramework().
Referenced by StateSubwidget().
 {
   topLabel->setText("");
   mpModel = NULL;
   mpTask = NULL;
   setFramework(mFramework);
 }
bool StateSubwidget::loadAll (const CSteadyStateTask * pTask) virtual
Definition at line 285 of file StateSubwidget.cpp.
References clear(), CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), CSteadyStateMethod::getMethodLog(), CCopasiTask::getProblem(), CSteadyStateTask::getResult(), CSteadyStateTask::getState(), CSteadyStateProblem::isJacobianRequested(), CSteadyStateProblem::isStabilityAnalysisRequested(), loadCompartments(), loadJacobian(), loadMetabolites(), loadModelValues(), loadReactions(), CopasiWidget::mFramework, mpModel, mpTask, CSteadyStateMethod::notFound, pTask, setFramework(), CModel::setState(), CModel::updateNonSimulatedValues(), and CModel::updateSimulatedValues().
 {
   mpTask = pTask;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   mpModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   if (mpTask == NULL || mpModel == NULL)
     {
       clear();
       return false;
     }
   CState * pState = const_cast<CState *>(mpTask->getState());
   mpModel->setState(*pState);
   mpModel->updateSimulatedValues(true);
   mpModel->updateNonSimulatedValues();
   if (mpTask->getResult() == CSteadyStateMethod::found)
     topLabel->setText("A steady state with given resolution was found.");
   else if (mpTask->getResult() == CSteadyStateMethod::notFound)
     topLabel->setText("No steady state with given resolution was found!");
   else if (mpTask->getResult() == CSteadyStateMethod::foundEquilibrium)
     topLabel->setText("An equilibrium steady state (zero fluxes) was found.");
   else if (mpTask->getResult() == CSteadyStateMethod::foundNegative)
     topLabel->setText("An invalid steady state (negative concentrations) was found.");
   else
     topLabel->setText("A steady state with given resolution couldn't be found.");
   setFramework(mFramework);
   loadMetabolites();
   loadCompartments();
   loadModelValues();
   loadReactions();
   const CSteadyStateProblem* pProblem =
     dynamic_cast<const CSteadyStateProblem *>(mpTask->getProblem());
   assert(pProblem);
   int Last = mpTabWidget->count() - 1;
   // enable/disable tab widgets
   // jacobian and stability
   if (pProblem->isJacobianRequested() ||
       pProblem->isStabilityAnalysisRequested())
     {
       mpTabWidget->setTabEnabled(Last - 3, true);
       mpTabWidget->setTabEnabled(Last - 2, true);
       mpTabWidget->setTabEnabled(Last - 1, true);
       loadJacobian();
     }
   else
     {
       mpTabWidget->setTabEnabled(Last - 3, false);
       mpTabWidget->setTabEnabled(Last - 2, false);
       mpTabWidget->setTabEnabled(Last - 1, false);
     }
   // protocol
   if (true)
     {
       mpTabWidget->setTabEnabled(Last, true);
       const CSteadyStateMethod * pMethod =
         dynamic_cast<const CSteadyStateMethod *>(mpTask->getMethod());
       assert(pMethod);
       protocolTextEdit->setText(FROM_UTF8(pMethod->getMethodLog()));
     }
   else
     {
       mpTabWidget->setTabEnabled(Last, false);
     }
   return true;
 }
void StateSubwidget::loadCompartments () protected
Definition at line 99 of file StateSubwidget.cpp.
References CCopasiVector< T >::begin(), C_INT32, CCopasiVector< T >::end(), FROM_UTF8, CModel::getCompartments(), mpModel, CModelEntity::ODE, CCopasiVector< T >::size(), and CModelEntity::StatusName.
Referenced by loadAll().
 {
   CCopasiVectorN< CCompartment >::const_iterator it = mpModel->getCompartments().begin();
   CCopasiVectorN< CCompartment >::const_iterator end = mpModel->getCompartments().end();
   C_INT32 i = 0;
   mpTblCompartments->setRowCount((int) mpModel->getCompartments().size());
   for (; it != end; ++it)
     if ((*it)->getStatus() == CModelEntity::ODE)
       {
         mpTblCompartments->setItem(i, 0, new QTableWidgetItem(FROM_UTF8((*it)->getObjectName())));
         mpTblCompartments->setItem(i, 1, new QTableWidgetItem(FROM_UTF8(CModelEntity::StatusName[(*it)->getStatus()])));
         mpTblCompartments->setItem(i, 2, new QTableWidgetItem(QString::number((*it)->getValue())));
         mpTblCompartments->setItem(i, 3, new QTableWidgetItem(QString::number((*it)->getRate())));
         i++;
       }
   mpTblCompartments->setRowCount(i);
   mpTblCompartments->resizeColumnsToContents();
   mpTblCompartments->resizeRowsToContents();
 }
void StateSubwidget::loadJacobian () protected
Definition at line 168 of file StateSubwidget.cpp.
References FROM_UTF8, CSteadyStateTask::getEigenValues(), CSteadyStateTask::getEigenValuesReduced(), CEigen::getI(), CSteadyStateTask::getJacobianAnnotated(), CSteadyStateTask::getJacobianXAnnotated(), CEigen::getR(), mpTask, and CVectorCore< CType >::size().
Referenced by loadAll().
 {
   const CArrayAnnotation * JacAnn = mpTask->getJacobianAnnotated();
   CColorScaleBiLog * tcs = new CColorScaleBiLog();
   mpJacobianAnnotationWidget->setColorCoding(tcs);
   mpJacobianAnnotationWidget->setColorScalingAutomatic(true);
   mpJacobianAnnotationWidget->setLegendEnabled(false);
   mpJacobianAnnotationWidget->setArrayAnnotation(JacAnn);
   //Eigenvalues...
   const CVector< C_FLOAT64 > & eigen_i = mpTask->getEigenValues().getI();
   const CVector< C_FLOAT64 > & eigen_r = mpTask->getEigenValues().getR();
   size_t i, imax = eigen_i.size();
   tableEigenValues->setRowCount((int) imax);
   for (i = 0; i < imax; ++i)
     {
       tableEigenValues->setItem((int) i, 0, new QTableWidgetItem(QString::number(eigen_r[i])));
       tableEigenValues->setItem((int) i, 1, new QTableWidgetItem(QString::number(eigen_i[i])));
     }
   tableEigenValues->resizeColumnsToContents();
   tableEigenValues->resizeRowsToContents();
   //JacobianX
   const CArrayAnnotation * JacXAnn = mpTask->getJacobianXAnnotated();
   tcs = new CColorScaleBiLog();
   mpJacobianXAnnotationWidget->setColorCoding(tcs);
   mpJacobianXAnnotationWidget->setColorScalingAutomatic(true);
   mpJacobianXAnnotationWidget->setLegendEnabled(false);
   mpJacobianXAnnotationWidget->setArrayAnnotation(JacXAnn);
   //Eigenvalues...
   const CVector< C_FLOAT64 > & eigen_iX = mpTask->getEigenValuesReduced().getI();
   const CVector< C_FLOAT64 > & eigen_rX = mpTask->getEigenValuesReduced().getR();
   imax = eigen_iX.size();
   tableEigenValuesX->setRowCount((int) imax);
   for (i = 0; i < imax; ++i)
     {
       tableEigenValuesX->setItem((int) i, 0, new QTableWidgetItem(QString::number(eigen_rX[i])));
       tableEigenValuesX->setItem((int) i, 1, new QTableWidgetItem(QString::number(eigen_iX[i])));
     }
   tableEigenValuesX->resizeColumnsToContents();
   tableEigenValuesX->resizeRowsToContents();
   //stability report
   stabilityTextEdit->setReadOnly(true);
   std::ostringstream ss;
   ss << mpTask->getEigenValuesReduced();
   stabilityTextEdit->setText(FROM_UTF8(ss.str()));
   return;
 }
void StateSubwidget::loadMetabolites () protected
Definition at line 70 of file StateSubwidget.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), FROM_UTF8, CMetabNameInterface::getDisplayName(), CModel::getMetabolites(), mpModel, CModelEntity::ODE, CModelEntity::REACTIONS, CCopasiVector< T >::size(), and CModelEntity::StatusName.
Referenced by loadAll().
 {
   // Fill the table
   CCopasiVectorN< CMetab >::const_iterator it = mpModel->getMetabolites().begin();
   CCopasiVectorN< CMetab >::const_iterator end = mpModel->getMetabolites().end();
   int i = 0;
   mpTblMetabolites->setRowCount((int) mpModel->getMetabolites().size());
   for (; it != end; ++it)
     if ((*it)->getStatus() == CModelEntity::ODE ||
         ((*it)->getStatus() == CModelEntity::REACTIONS && (*it)->isUsed()))
       {
         mpTblMetabolites->setItem(i, 0, new QTableWidgetItem(FROM_UTF8(CMetabNameInterface::getDisplayName(mpModel, **it, false))));
         mpTblMetabolites->setItem(i, 1, new QTableWidgetItem(FROM_UTF8(CModelEntity::StatusName[(*it)->getStatus()])));
         mpTblMetabolites->setItem(i, 2, new QTableWidgetItem(QString::number((*it)->getConcentration())));
         mpTblMetabolites->setItem(i, 3, new QTableWidgetItem(QString::number((*it)->getValue())));
         mpTblMetabolites->setItem(i, 4, new QTableWidgetItem(QString::number((*it)->getConcentrationRate())));
         mpTblMetabolites->setItem(i, 5, new QTableWidgetItem(QString::number((*it)->getRate())));
         mpTblMetabolites->setItem(i, 6, new QTableWidgetItem(QString::number((*it)->getTransitionTime())));
         i++;
       }
   mpTblMetabolites->setRowCount(i);
   mpTblMetabolites->resizeColumnsToContents();
   mpTblMetabolites->resizeRowsToContents();
 }
void StateSubwidget::loadModelValues () protected
Definition at line 145 of file StateSubwidget.cpp.
References CCopasiVector< T >::begin(), C_INT32, CCopasiVector< T >::end(), FROM_UTF8, CModel::getModelValues(), mpModel, CModelEntity::ODE, CCopasiVector< T >::size(), and CModelEntity::StatusName.
Referenced by loadAll().
 {
   CCopasiVectorN< CModelValue >::const_iterator it = mpModel->getModelValues().begin();
   CCopasiVectorN< CModelValue >::const_iterator end = mpModel->getModelValues().end();
   C_INT32 i = 0;
   mpTblModelValues->setRowCount((int) mpModel->getModelValues().size());
   for (; it != end; ++it)
     if ((*it)->getStatus() == CModelEntity::ODE)
       {
         mpTblModelValues->setItem(i, 0, new QTableWidgetItem(FROM_UTF8((*it)->getObjectName())));
         mpTblModelValues->setItem(i, 1, new QTableWidgetItem(FROM_UTF8(CModelEntity::StatusName[(*it)->getStatus()])));
         mpTblModelValues->setItem(i, 2, new QTableWidgetItem(QString::number((*it)->getValue())));
         mpTblModelValues->setItem(i, 3, new QTableWidgetItem(QString::number((*it)->getRate())));
         i++;
       }
   mpTblModelValues->setRowCount(i);
   mpTblModelValues->resizeColumnsToContents();
   mpTblModelValues->resizeRowsToContents();
 }
void StateSubwidget::loadReactions () protected
Definition at line 122 of file StateSubwidget.cpp.
References CCopasiVector< T >::begin(), C_INT32, CCopasiVector< T >::end(), FROM_UTF8, CChemEqInterface::getChemEqString(), CModel::getReactions(), mpModel, and CCopasiVector< T >::size().
Referenced by loadAll().
 {
   // Fill the table
   CCopasiVectorN< CReaction >::const_iterator it = mpModel->getReactions().begin();
   CCopasiVectorN< CReaction >::const_iterator end = mpModel->getReactions().end();
   C_INT32 i = 0;
   mpTblReactions->setRowCount((int) mpModel->getReactions().size());
   for (; it != end; ++it)
     {
       mpTblReactions->setItem(i, 0, new QTableWidgetItem(FROM_UTF8((*it)->getObjectName())));
       mpTblReactions->setItem(i, 1, new QTableWidgetItem(QString::number((*it)->getFlux())));
       mpTblReactions->setItem(i, 2, new QTableWidgetItem(QString::number((*it)->getParticleFlux())));
       mpTblReactions->setItem(i, 3, new QTableWidgetItem(FROM_UTF8(CChemEqInterface::getChemEqString(mpModel, **it, false))));
       i++;
     }
   mpTblReactions->resizeColumnsToContents();
   mpTblReactions->resizeRowsToContents();
 }
void StateSubwidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 383 of file StateSubwidget.cpp.
References CopasiWidget::mFramework, CopasiWidget::setFramework(), and showUnits().
Referenced by init(), and loadAll().
 {
   CopasiWidget::setFramework(framework);
   // TODO hide/show columns
   switch (mFramework)
     {
       case 0:
         mpTblMetabolites->showColumn(2);
         mpTblMetabolites->hideColumn(3);
         mpTblMetabolites->showColumn(4);
         mpTblMetabolites->hideColumn(5);
         mpTblReactions->showColumn(1);
         mpTblReactions->hideColumn(2);
         break;
       case 1:
         mpTblMetabolites->hideColumn(2);
         mpTblMetabolites->showColumn(3);
         mpTblMetabolites->hideColumn(4);
         mpTblMetabolites->showColumn(5);
         mpTblReactions->hideColumn(1);
         mpTblReactions->showColumn(2);
         break;
     }
   showUnits();
 }
void StateSubwidget::showUnits () protected
Definition at line 230 of file StateSubwidget.cpp.
References FROM_UTF8, CModel::getConcentrationRateUnitsDisplayString(), CModel::getConcentrationUnitsDisplayString(), CModel::getFrequencyUnitsDisplayString(), CModel::getQuantityRateUnitsDisplayString(), CModel::getTimeUnitsDisplayString(), CModel::getVolumeRateUnitsDisplayString(), CModel::getVolumeUnitsDisplayString(), and mpModel.
Referenced by setFramework(), and update().
 {
   if (mpModel == NULL)
     return;
   // Update the column titles
   QString TimeUnits = FROM_UTF8(mpModel->getTimeUnitsDisplayString());
   if (!TimeUnits.isEmpty())
     TimeUnits = "\n(" + TimeUnits + ")";
   QString FrequencyUnits = FROM_UTF8(mpModel->getFrequencyUnitsDisplayString());
   if (!FrequencyUnits.isEmpty())
     FrequencyUnits = "\n(" + FrequencyUnits + ")";
   QString ConcentrationUnits = FROM_UTF8(mpModel->getConcentrationUnitsDisplayString());
   if (!ConcentrationUnits.isEmpty())
     ConcentrationUnits = "\n(" + ConcentrationUnits + ")";
   QString ConcentrationRateUnits = FROM_UTF8(mpModel->getConcentrationRateUnitsDisplayString());
   if (!ConcentrationRateUnits.isEmpty())
     ConcentrationRateUnits = "\n(" + ConcentrationRateUnits + ")";
   QString VolumeUnits = FROM_UTF8(mpModel->getVolumeUnitsDisplayString());
   if (!VolumeUnits.isEmpty())
     VolumeUnits = "\n(" + VolumeUnits + ")";
   QString VolumeRateUnits = FROM_UTF8(mpModel->getVolumeRateUnitsDisplayString());
   if (!VolumeRateUnits.isEmpty())
     VolumeRateUnits = "\n(" + VolumeRateUnits + ")";
   QString QuantityRateUnits = FROM_UTF8(mpModel->getQuantityRateUnitsDisplayString());
   if (!QuantityRateUnits.isEmpty())
     QuantityRateUnits = "\n(" + QuantityRateUnits + ")";
   mpTblCompartments->horizontalHeaderItem(2)->setText("Volume" + VolumeUnits);
   mpTblCompartments->horizontalHeaderItem(3)->setText("Rate" + VolumeRateUnits);
   mpTblMetabolites->horizontalHeaderItem(2)->setText("Concentration" + ConcentrationUnits);
   mpTblMetabolites->horizontalHeaderItem(3)->setText("Particle Numbers");
   mpTblMetabolites->horizontalHeaderItem(4)->setText("Rate" + ConcentrationRateUnits);
   mpTblMetabolites->horizontalHeaderItem(5)->setText("Rate" + FrequencyUnits);
   mpTblMetabolites->horizontalHeaderItem(6)->setText("Transition Time" + TimeUnits);
   mpTblReactions->horizontalHeaderItem(1)->setText("Flux" + QuantityRateUnits);
   mpTblReactions->horizontalHeaderItem(2)->setText("Particle Flux" + FrequencyUnits);
 }
bool StateSubwidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 412 of file StateSubwidget.cpp.
References ListViews::ADD, ListViews::CHANGE, clear(), CCopasiRootContainer::getDatamodelList(), ListViews::MODEL, mpModel, mpTask, and showUnits().
 {
   switch (objectType)
     {
       case ListViews::MODEL:
         // For a new model we need to remove references to no longer existing metabolites
         switch (action)
           {
             case ListViews::ADD:
               assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
               mpModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
               clear();
               showUnits();
               mpTask = NULL;
               break;
             case ListViews::CHANGE:
               showUnits();
               break;
             default:
               break;
           }
         break;
       default:
         break;
     }
   return true;
 }
Member Data Documentation
CModel* StateSubwidget::mpModel protected
Definition at line 46 of file StateSubwidget.h.
Referenced by init(), loadAll(), loadCompartments(), loadMetabolites(), loadModelValues(), loadReactions(), showUnits(), and update().
const CSteadyStateTask* StateSubwidget::mpTask protected
Definition at line 45 of file StateSubwidget.h.
Referenced by init(), loadAll(), loadJacobian(), and update().
The documentation for this class was generated from the following files:
StateSubwidget.h
StateSubwidget.cpp