COPASI API: CQBaseWidget Class Reference
CQBaseWidget Class Reference abstract
#include <CQBaseWidget.h>
Public Member Functions
CQBaseWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
bool isSliderActive () const
int scaleFactor ()
void setSliderActive (const bool &active)
virtual void sliderMoved (int column, int row)=0
virtual ~CQBaseWidget ()
Protected Slots
void setSlider ()
Protected Attributes
int mScaleFactor
bool mSliderActive
Detailed Description
Definition at line 13 of file CQBaseWidget.h.
Constructor & Destructor Documentation
CQBaseWidget::CQBaseWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 29 of file CQBaseWidget.cpp.
References mSliderActive, setSlider(), and setSliderActive().
   : QWidget(parent, fl),
     mSliderActive(false),
     mScaleFactor(1000)
 {
   setupUi(this);
   setSliderActive(mSliderActive);
   connect(mpSliderRow, SIGNAL(valueChanged(int)), this, SLOT(setSlider()));
   connect(mpSliderColumn, SIGNAL(valueChanged(int)), this, SLOT(setSlider()));
 }
CQBaseWidget::~CQBaseWidget () virtual
Definition at line 45 of file CQBaseWidget.cpp.
 {}
Member Function Documentation
bool CQBaseWidget::isSliderActive () const
Definition at line 68 of file CQBaseWidget.cpp.
References mSliderActive.
 {
   return mSliderActive;
 }
int CQBaseWidget::scaleFactor ()
Definition at line 98 of file CQBaseWidget.cpp.
References mScaleFactor.
 {
   return mScaleFactor;
 }
void CQBaseWidget::setSlider () protected slot
Definition at line 73 of file CQBaseWidget.cpp.
References mScaleFactor, mSliderActive, and sliderMoved().
Referenced by CQBaseWidget().
 {
   if (!mSliderActive) return;
   int row = mpSliderRow->value();
   int col = mpSliderColumn->value();
 #ifdef DEBUG_UI
   qDebug() << "A CQBaseWidget::setSlider -> col = " << col << " - row = " << row;
 #endif
   sliderMoved(mpSliderColumn->value() / mScaleFactor, mpSliderRow->value() / mScaleFactor);
 #ifdef DEBUG_UI
   qDebug() << "B CQBaseWidget::setSlider -> col = " << col << " - row = " << row;
 #endif
   mpSliderRow->setValue(row);
   mpSliderColumn->setValue(col);
 #ifdef DEBUG_UI
   qDebug() << "C CQBaseWidget::setSlider -> col = " << mSliderActiveColumn->value() << " - row = " << mSliderActiveRow->value();
 #endif
 }
void CQBaseWidget::setSliderActive (const bool & active)
Definition at line 48 of file CQBaseWidget.cpp.
References mSliderActive.
Referenced by CQBaseWidget().
 {
   mSliderActive = active;
   if (mSliderActive)
     {
       mpLabelRow->show();
       mpSliderRow->show();
       mpLabelColumn->show();
       mpSliderColumn->show();
     }
   else
     {
       mpLabelRow->hide();
       mpSliderRow->hide();
       mpLabelColumn->hide();
       mpSliderColumn->hide();
     }
 }
virtual void CQBaseWidget::sliderMoved (int column, int row) pure virtual
Implemented in CQBarChart.
Referenced by setSlider().
Member Data Documentation
int CQBaseWidget::mScaleFactor protected
Definition at line 35 of file CQBaseWidget.h.
Referenced by scaleFactor(), and setSlider().
bool CQBaseWidget::mSliderActive protected
Definition at line 33 of file CQBaseWidget.h.
Referenced by CQBaseWidget(), CQBarChart::getColSliderPos(), CQBarChart::getRowSliderPos(), isSliderActive(), setSlider(), CQBarChart::setSlider(), setSliderActive(), and CQBarChart::sliderMoved().
The documentation for this class was generated from the following files:
CQBaseWidget.h
CQBaseWidget.cpp