COPASI API: CQTrajectoryWidget Class Reference
CQTrajectoryWidget Class Reference
#include <CQTrajectoryWidget.h>
Public Slots
void slotDuration ()
void slotIntervals ()
void slotIntervalSize ()
void slotOutputDelay (bool checked)
void updateIntervals ()
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Public Member Functions
CQTrajectoryWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQTrajectoryWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Member Functions
void checkTimeSeries ()
void destroy ()
void init ()
void showUnits ()
Private Attributes
CTrajectoryProblem * mpTrajectoryProblem
CQValidatorDouble * mpValidatorDelay
CQValidatorDouble * mpValidatorDuration
CQValidatorInt * mpValidatorIntervals
CQValidatorDouble * mpValidatorIntervalSize
Additional Inherited Members
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 34 of file CQTrajectoryWidget.h.
Constructor & Destructor Documentation
CQTrajectoryWidget::CQTrajectoryWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 39 of file CQTrajectoryWidget.cpp.
References init().
   : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQTrajectoryWidget::~CQTrajectoryWidget () virtual
Definition at line 50 of file CQTrajectoryWidget.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQTrajectoryWidget::checkTimeSeries () private
Definition at line 358 of file CQTrajectoryWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), and TSMAX.
Referenced by loadTask(), runTask(), slotDuration(), slotIntervals(), and slotIntervalSize().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   if (mpEditIntervals->text().toLong() * (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getStateTemplate().getNumVariable() > TSMAX)
     {
       mpCheckSave->setChecked(false);
       mpCheckSave->setEnabled(false);
     }
   else
     {
       mpCheckSave->setEnabled(true);
     }
 }
CCopasiMethod * CQTrajectoryWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 324 of file CQTrajectoryWidget.cpp.
References CTrajectoryMethod::createMethod().
 {
   return CTrajectoryMethod::createMethod(type);
 }
void CQTrajectoryWidget::destroy () private
Definition at line 88 of file CQTrajectoryWidget.cpp.
References mpTrajectoryProblem, and pdelete.
Referenced by ~CQTrajectoryWidget().
 {
   pdelete(mpTrajectoryProblem);
 }
void CQTrajectoryWidget::init () private
Definition at line 56 of file CQTrajectoryWidget.cpp.
References max, TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, mpTrajectoryProblem, mpValidatorDelay, mpValidatorDuration, mpValidatorIntervals, mpValidatorIntervalSize, CQValidatorDouble::setRange(), CQValidatorInt::setRange(), CQTaskHeaderWidget::setTaskName(), CQTaskMethodWidget::setValidMethods(), CQTaskMethodWidget::showMethodParameters(), slotOutputDelay(), and CTrajectoryTask::ValidMethods.
Referenced by CQTrajectoryWidget().
 {
   mpTrajectoryProblem = NULL;
   mpHeaderWidget->setTaskName("Time Course");
   verticalLayout->insertWidget(0, mpHeaderWidget);  // header
   // verticalLayout->insertSpacing(1, 14);       // space between header and body
   mpMethodWidget->setValidMethods(CTrajectoryTask::ValidMethods);
   mpMethodWidget->showMethodParameters(true);
   verticalLayout->addWidget(mpMethodWidget);
   verticalLayout->addWidget(mpBtnWidget);     // 'footer'
   slotOutputDelay(false);
   mpValidatorDuration = new CQValidatorDouble(mpEditDuration);
   mpEditDuration->setValidator(mpValidatorDuration);
   mpValidatorIntervalSize = new CQValidatorDouble(mpEditIntervalSize);
   mpValidatorIntervalSize->setRange(0, std::numeric_limits< double >::max());
   mpEditIntervalSize->setValidator(mpValidatorIntervalSize);
   mpValidatorIntervals = new CQValidatorInt(mpEditIntervals);
   mpValidatorIntervals->setRange(0, std::numeric_limits< int >::max());
   mpEditIntervals->setValidator(mpValidatorIntervals);
   mpValidatorDelay = new CQValidatorDouble(mpEditDelay);
   mpEditDelay->setValidator(mpValidatorDelay);
 }
bool CQTrajectoryWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 268 of file CQTrajectoryWidget.cpp.
References C_FLOAT64, checkTimeSeries(), CTrajectoryProblem::getContinueSimultaneousEvents(), CCopasiRootContainer::getDatamodelList(), CTrajectoryProblem::getDuration(), CTrajectoryProblem::getOutputEvent(), CTrajectoryProblem::getOutputStartTime(), CCopasiTask::getProblem(), CTrajectoryProblem::getStepNumber(), CTrajectoryProblem::getStepSize(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), min, TaskWidget::mpTask, mpTrajectoryProblem, mpValidatorDelay, mpValidatorDuration, mpValidatorIntervals, mpValidatorIntervalSize, pdelete, pTask, CQValidator< Type >::saved(), showUnits(), CTrajectoryProblem::timeSeriesRequested(), and updateIntervals().
 {
   CTrajectoryTask * pTask =
     dynamic_cast< CTrajectoryTask * >(mpTask);
   if (!pTask) return false;
   loadCommon();
   loadMethod();
   showUnits();
   CTrajectoryProblem* trajectoryproblem =
     dynamic_cast<CTrajectoryProblem *>(pTask->getProblem());
   assert(trajectoryproblem);
   pdelete(mpTrajectoryProblem);
   mpTrajectoryProblem = new CTrajectoryProblem(*trajectoryproblem);
   //numbers
   mpEditIntervalSize->setText(QString::number(trajectoryproblem->getStepSize()));
   mpEditIntervals->setText(QString::number(trajectoryproblem->getStepNumber()));
   mpEditDuration->setText(QString::number(trajectoryproblem->getDuration()));
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   C_FLOAT64 InitialTime = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getInitialTime();
   bool Delayed;
   if (trajectoryproblem->getStepSize() > 0.0)
     Delayed = (trajectoryproblem->getOutputStartTime() - InitialTime) > std::numeric_limits< C_FLOAT64 >::min();
   else
     Delayed = (InitialTime - trajectoryproblem->getOutputStartTime()) > std::numeric_limits< C_FLOAT64 >::min();
   mpCheckDelay->setChecked(Delayed);
   mpEditDelay->setEnabled(Delayed);
   mpEditDelay->setText(QString::number(trajectoryproblem->getOutputStartTime()));
   mpCheckOutputEvent->setChecked(trajectoryproblem->getOutputEvent());
   mpCheckContinueEvents->setChecked(trajectoryproblem->getContinueSimultaneousEvents());
   //store time series checkbox
   mpCheckSave->setChecked(trajectoryproblem->timeSeriesRequested());
   checkTimeSeries();
   updateIntervals();
   mpValidatorDuration->saved();
   mpValidatorIntervalSize->saved();
   mpValidatorIntervals->saved();
   mpValidatorDelay->saved();
   return true;
 }
bool CQTrajectoryWidget::runTask () virtual
Implements TaskWidget.
Definition at line 329 of file CQTrajectoryWidget.cpp.
References checkTimeSeries(), TaskWidget::commonBeforeRunTask(), and TaskWidget::commonRunTask().
Referenced by SliderDialog::runTimeCourse().
 {
   checkTimeSeries();
   if (!commonBeforeRunTask()) return false;
   bool success = true;
   if (!commonRunTask()) success = false;
   return success;
 }
bool CQTrajectoryWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 173 of file CQTrajectoryWidget.cpp.
References C_FLOAT64, CTrajectoryProblem::getContinueSimultaneousEvents(), CCopasiRootContainer::getDatamodelList(), CTrajectoryProblem::getDuration(), CTrajectoryProblem::getOutputEvent(), CTrajectoryProblem::getOutputStartTime(), CCopasiTask::getProblem(), CTrajectoryProblem::getStepNumber(), CTrajectoryProblem::getStepSize(), TaskWidget::mChanged, TaskWidget::mpTask, mpValidatorDelay, mpValidatorDuration, mpValidatorIntervals, mpValidatorIntervalSize, pTask, TaskWidget::saveCommon(), CQValidator< Type >::saved(), TaskWidget::saveMethod(), CTrajectoryProblem::setContinueSimultaneousEvents(), CTrajectoryProblem::setDuration(), CTrajectoryProblem::setOutputEvent(), CTrajectoryProblem::setOutputStartTime(), CTrajectoryProblem::setStepNumber(), CTrajectoryProblem::setStepSize(), CTrajectoryProblem::setTimeSeriesRequested(), and CTrajectoryProblem::timeSeriesRequested().
 {
   CTrajectoryTask * pTask =
     dynamic_cast< CTrajectoryTask * >(mpTask);
   if (!pTask) return false;
   saveCommon();
   saveMethod();
   CTrajectoryProblem* trajectoryproblem =
     dynamic_cast<CTrajectoryProblem *>(pTask->getProblem());
   assert(trajectoryproblem);
   //numbers
   if (mpEditIntervalSize->hasAcceptableInput() &&
       trajectoryproblem->getStepSize() != mpEditIntervalSize->text().toDouble())
     {
       trajectoryproblem->setStepSize(mpEditIntervalSize->text().toDouble());
       mChanged = true;
     }
   else if (mpEditIntervals->hasAcceptableInput() &&
            trajectoryproblem->getStepNumber() != mpEditIntervals->text().toULong())
     {
       trajectoryproblem->setStepNumber(mpEditIntervals->text().toLong());
       mChanged = true;
     }
   if (mpEditDuration->hasAcceptableInput() &&
       trajectoryproblem->getDuration() != mpEditDuration->text().toDouble())
     {
       trajectoryproblem->setDuration(mpEditDuration->text().toDouble());
       mChanged = true;
     }
   C_FLOAT64 StartTime = mpEditDelay->text().toDouble();
   if (mpCheckDelay->isChecked())
     {
       if (mpEditDelay->hasAcceptableInput() &&
           StartTime != trajectoryproblem->getOutputStartTime())
         {
           trajectoryproblem->setOutputStartTime(StartTime);
           mChanged = true;
         }
     }
   else
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       C_FLOAT64 InitialTime =
         (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getInitialTime();
       if (trajectoryproblem->getStepSize() > 0.0)
         {
           if (StartTime > InitialTime)
             {
               trajectoryproblem->setOutputStartTime(InitialTime);
               mChanged = true;
             }
         }
       else
         {
           if (StartTime < InitialTime)
             {
               trajectoryproblem->setOutputStartTime(InitialTime);
               mChanged = true;
             }
         }
     }
   if (trajectoryproblem->timeSeriesRequested() != mpCheckSave->isChecked())
     {
       trajectoryproblem->setTimeSeriesRequested(mpCheckSave->isChecked());
       mChanged = true;
     }
   if (trajectoryproblem->getOutputEvent() != mpCheckOutputEvent->isChecked())
     {
       trajectoryproblem->setOutputEvent(mpCheckOutputEvent->isChecked());
       mChanged = true;
     }
   if (trajectoryproblem->getContinueSimultaneousEvents() != mpCheckContinueEvents->isChecked())
     {
       trajectoryproblem->setContinueSimultaneousEvents(mpCheckContinueEvents->isChecked());
       mChanged = true;
     }
   mpValidatorDuration->saved();
   mpValidatorIntervalSize->saved();
   mpValidatorIntervals->saved();
   mpValidatorDelay->saved();
   return true;
 }
void CQTrajectoryWidget::showUnits () private
Definition at line 451 of file CQTrajectoryWidget.cpp.
References FROM_UTF8, CCopasiDataModel::getModel(), CModel::getTimeUnitsDisplayString(), and CopasiWidget::mpDataModel.
Referenced by loadTask(), and update().
 {
   const CModel * pModel = NULL;
   QString TimeUnits;
   if (mpDataModel != NULL &&
       (pModel = mpDataModel->getModel()) != NULL)
     {
       TimeUnits = " (" + FROM_UTF8(pModel->getTimeUnitsDisplayString()) + ")";
     }
   mpLblDuration->setText("Duration" + TimeUnits);
   mpLblIntervalSize->setText("Interval Size" + TimeUnits);
   mpCheckDelay->setText("Suppress Output Before" + TimeUnits);
   mpLblIntegrationInterval->setText("Integration Interval" + TimeUnits);
   mpLblOutputInterval->setText("Output Interval" + TimeUnits);
 }
void CQTrajectoryWidget::slotDuration () slot
Definition at line 93 of file CQTrajectoryWidget.cpp.
References checkTimeSeries(), FROM_UTF8, CCopasiMessage::getAllMessageText(), CTrajectoryProblem::getStepNumber(), CTrajectoryProblem::getStepSize(), CQMessageBox::information(), mpTrajectoryProblem, mpValidatorIntervals, mpValidatorIntervalSize, CQValidator< Type >::revalidate(), CTrajectoryProblem::setDuration(), and updateIntervals().
 {
   if (!mpEditDuration->hasAcceptableInput())
     return;
   try
     {
       mpTrajectoryProblem->setDuration(mpEditDuration->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
   mpEditIntervalSize->setText(QString::number(mpTrajectoryProblem->getStepSize()));
   mpValidatorIntervalSize->revalidate();
   mpEditIntervals->setText(QString::number(mpTrajectoryProblem->getStepNumber()));
   mpValidatorIntervals->revalidate();
   checkTimeSeries();
   updateIntervals();
 }
void CQTrajectoryWidget::slotIntervals () slot
Definition at line 144 of file CQTrajectoryWidget.cpp.
References checkTimeSeries(), FROM_UTF8, CCopasiMessage::getAllMessageText(), CTrajectoryProblem::getStepSize(), CQMessageBox::information(), mpTrajectoryProblem, mpValidatorIntervalSize, CQValidator< Type >::revalidate(), CTrajectoryProblem::setStepNumber(), and updateIntervals().
 {
   if (!mpEditIntervals->hasAcceptableInput())
     return;
   try
     {
       mpTrajectoryProblem->setStepNumber(mpEditIntervals->text().toULong());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
   mpEditIntervalSize->setText(QString::number(mpTrajectoryProblem->getStepSize()));
   mpValidatorIntervalSize->revalidate();
   checkTimeSeries();
   updateIntervals();
 }
void CQTrajectoryWidget::slotIntervalSize () slot
Definition at line 118 of file CQTrajectoryWidget.cpp.
References checkTimeSeries(), FROM_UTF8, CCopasiMessage::getAllMessageText(), CTrajectoryProblem::getStepNumber(), CTrajectoryProblem::getStepSize(), CQMessageBox::information(), mpTrajectoryProblem, mpValidatorIntervals, mpValidatorIntervalSize, CQValidator< Type >::revalidate(), CTrajectoryProblem::setStepSize(), and updateIntervals().
 {
   if (!mpEditIntervalSize->hasAcceptableInput())
     return;
   try
     {
       mpTrajectoryProblem->setStepSize(mpEditIntervalSize->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
   mpEditIntervalSize->setText(QString::number(mpTrajectoryProblem->getStepSize()));
   mpValidatorIntervalSize->revalidate();
   mpEditIntervals->setText(QString::number(mpTrajectoryProblem->getStepNumber()));
   mpValidatorIntervals->revalidate();
   checkTimeSeries();
   updateIntervals();
 }
void CQTrajectoryWidget::slotOutputDelay (bool checked) slot
Definition at line 167 of file CQTrajectoryWidget.cpp.
References updateIntervals().
Referenced by init().
 {
   mpEditDelay->setEnabled(checked);
   updateIntervals();
 }
bool CQTrajectoryWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 342 of file CQTrajectoryWidget.cpp.
References ListViews::findWidgetFromId(), CQTimeSeriesWidget::loadResult(), CopasiWidget::mpListView, TaskWidget::mpTask, and pResult.
 {
   bool success = true;
   // We need to load the result here as this is the only place where
   // we know that it is correct.
   CQTimeSeriesWidget * pResult =
     dynamic_cast< CQTimeSeriesWidget * >(mpListView->findWidgetFromId(231));
   if (pResult == NULL)
     return false;
   success &= pResult->loadResult(mpTask);
   return success;
 }
bool CQTrajectoryWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from TaskWidget.
Definition at line 431 of file CQTrajectoryWidget.cpp.
References ListViews::CHANGE, ListViews::MODEL, and showUnits().
 {
   switch (objectType)
     {
       case ListViews::MODEL:
         if (action == ListViews::CHANGE)
           {
             showUnits();
           }
         break;
       default:
         break;
     }
   return true;
 }
void CQTrajectoryWidget::updateIntervals () slot
Definition at line 373 of file CQTrajectoryWidget.cpp.
References C_FLOAT64, CCopasiRootContainer::getDatamodelList(), max, and min.
Referenced by loadTask(), slotDuration(), slotIntervals(), slotIntervalSize(), and slotOutputDelay().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   C_FLOAT64 InitialTime = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getInitialTime();
   C_FLOAT64 Duration = mpEditDuration->text().toDouble();
   C_FLOAT64 OutputStartTime = InitialTime;
   if (mpCheckDelay->isChecked())
     {
       if (!mpEditIntervalSize->hasAcceptableInput())
         return;
       OutputStartTime = mpEditDelay->text().toDouble();
     }
   mpEditIntegrationInterval->setText(QString::number(InitialTime) +
                                      " to " +
                                      QString::number(InitialTime + Duration));
   if (Duration > 0.0)
     {
       if (std::max(InitialTime, OutputStartTime) > InitialTime + Duration)
         mpEditOutputInterval->setText("empty");
       else if (InitialTime < OutputStartTime)
         {
           C_FLOAT64 StepSize = mpEditIntervalSize->text().toDouble();
           OutputStartTime = InitialTime + (ceil((OutputStartTime - InitialTime) / StepSize)) * StepSize;
           mpEditOutputInterval->setText(QString::number(OutputStartTime) +
                                         " to " +
                                         QString::number(InitialTime + Duration));
         }
       else
         {
           mpEditOutputInterval->setText(QString::number(InitialTime) +
                                         " to " +
                                         QString::number(InitialTime + Duration));
         }
     }
   else
     {
       if (std::min(InitialTime, OutputStartTime) < InitialTime + Duration)
         mpEditOutputInterval->setText("empty");
       else if (InitialTime > OutputStartTime)
         {
           C_FLOAT64 StepSize = mpEditIntervalSize->text().toDouble();
           OutputStartTime = InitialTime + (ceil((OutputStartTime - InitialTime) / StepSize)) * StepSize;
           mpEditOutputInterval->setText(QString::number(OutputStartTime) +
                                         " to " +
                                         QString::number(InitialTime + Duration));
         }
       else
         mpEditOutputInterval->setText(QString::number(InitialTime) +
                                       " to " +
                                       QString::number(InitialTime + Duration));
     }
 }
Member Data Documentation
CTrajectoryProblem* CQTrajectoryWidget::mpTrajectoryProblem private
Definition at line 65 of file CQTrajectoryWidget.h.
Referenced by destroy(), init(), loadTask(), slotDuration(), slotIntervals(), and slotIntervalSize().
CQValidatorDouble* CQTrajectoryWidget::mpValidatorDelay private
Definition at line 62 of file CQTrajectoryWidget.h.
Referenced by init(), loadTask(), and saveTask().
CQValidatorDouble* CQTrajectoryWidget::mpValidatorDuration private
Definition at line 64 of file CQTrajectoryWidget.h.
Referenced by init(), loadTask(), and saveTask().
CQValidatorInt* CQTrajectoryWidget::mpValidatorIntervals private
Definition at line 61 of file CQTrajectoryWidget.h.
Referenced by init(), loadTask(), saveTask(), slotDuration(), and slotIntervalSize().
CQValidatorDouble* CQTrajectoryWidget::mpValidatorIntervalSize private
Definition at line 63 of file CQTrajectoryWidget.h.
Referenced by init(), loadTask(), saveTask(), slotDuration(), slotIntervals(), and slotIntervalSize().
The documentation for this class was generated from the following files:
CQTrajectoryWidget.h
CQTrajectoryWidget.cpp