COPASI API: C2DPlotCurve Class Reference
C2DPlotCurve Class Reference
#include <CopasiPlot.h>
Public Member Functions
C2DPlotCurve (QMutex *pMutex, const CPlotItem::Type &type, const COutputInterface::Activity &activity, const QString &title)
const COutputInterface::Activity & getActivity () const
const C_FLOAT64 & getIncrement () const
const CPlotItem::Type & getType () const
void reallocatedData (const CVector< double > *pX, const CVector< double > *pY, const CVector< double > *pY2=0)
void setDataSize (const size_t &size)
void setIncrement (const C_FLOAT64 &increment)
Protected Member Functions
virtual void drawCurve (QPainter *painter, int style, const QwtScaleMap &xMap, const QwtScaleMap &yMap, int from, int to) const
virtual void drawSymbols (QPainter *painter, const QwtSymbol &symbol, const QwtScaleMap &xMap, const QwtScaleMap &yMap, int from, int to) const
void myDrawLines (QPainter *painter, const QwtScaleMap &xMap, const QwtScaleMap &yMap, int from, int to) const
Private Attributes
COutputInterface::Activity mActivity
CPlotItem::Type mCurveType
C_FLOAT64 mIncrement
QMutex * mpMutex
Detailed Description
Definition at line 164 of file CopasiPlot.h.
Constructor & Destructor Documentation
C2DPlotCurve::C2DPlotCurve (QMutex * pMutex, const CPlotItem::Type & type, const COutputInterface::Activity & activity, const QString & title) inline
Definition at line 167 of file CopasiPlot.h.
References mpMutex.
                                                                                 :
     QwtPlotCurve(title),
     mpMutex(pMutex),
     mCurveType(type),
     mIncrement(1.0),
     mActivity(activity)
   {
     assert(mpMutex != NULL);
   }
Member Function Documentation
void C2DPlotCurve::drawCurve (QPainter * painter, int style, const QwtScaleMap & xMap, const QwtScaleMap & yMap, int from, int to) const protected virtual
Definition at line 698 of file CopasiPlot.cpp.
References mpMutex, and myDrawLines().
 {
   QMutexLocker Locker(mpMutex);
   if (style == Lines)
     {
       myDrawLines(painter, xMap, yMap, from, to);
     }
   else
     {
       QwtPlotCurve::drawCurve(painter, style, xMap, yMap, from, to);
     }
 }
void C2DPlotCurve::drawSymbols (QPainter * painter, const QwtSymbol & symbol, const QwtScaleMap & xMap, const QwtScaleMap & yMap, int from, int to) const protected virtual
Definition at line 714 of file CopasiPlot.cpp.
 {
   int from2 = from;
   int to2;
   for (;;)
     {
       //find the next not-NaN point
       while (isnan(x(from2)) || isnan(y(from2)))
         {
           ++from2;
           if (from2 >= to)
             return;
         }
       //find the nex NaN point (or the end of data)
       to2 = from2;
       do
         {
           ++to2;
           if (to2 > to)
             break;
         }
       while (!(isnan(x(to2)) || isnan(y(to2))));
       --to2;
       QwtPlotCurve::drawSymbols(painter, symbol, xMap, yMap, from2, to2);
       //are we done?
       if (to2 >= to)
         return;
       //continue with the next data point
       from2 = to2 + 1;
     }
 }
const COutputInterface::Activity & C2DPlotCurve::getActivity () const
Definition at line 662 of file CopasiPlot.cpp.
References mActivity.
 {
   return mActivity;
 }
const C_FLOAT64 & C2DPlotCurve::getIncrement () const
Definition at line 652 of file CopasiPlot.cpp.
References mIncrement.
 {
   return mIncrement;
 }
const CPlotItem::Type & C2DPlotCurve::getType () const
Definition at line 657 of file CopasiPlot.cpp.
References mCurveType.
Referenced by CopasiPlot::initFromSpec().
 {
   return mCurveType;
 }
void C2DPlotCurve::myDrawLines (QPainter * painter, const QwtScaleMap & xMap, const QwtScaleMap & yMap, int from, int to) const protected
Definition at line 668 of file CopasiPlot.cpp.
Referenced by drawCurve().
 {
   int to2;
   do
     {
       int i;
       for (i = from; i <= to; ++i)
         if (isnan(x(i)) || isnan(y(i))) //NaN
           break;
       if (i == from)
         {
           ++from;
           continue;
         }
       to2 = i - 1;
       QwtPlotCurve::drawLines(painter, xMap, yMap, from, to2);
       from = to2 + 2;
     }
   while (from < to);
 }
void C2DPlotCurve::reallocatedData (const CVector< double > * pX, const CVector< double > * pY, const CVector< double > * pY2 = 0)
Definition at line 624 of file CopasiPlot.cpp.
References CPlotItem::bandedGraph, CPlotItem::curve2d, fatalError, CPlotItem::histoItem1d, and mCurveType.
 {
   switch (mCurveType)
     {
       case CPlotItem::curve2d:
         static_cast< C2DCurveData * >(&data())->reallocated(pX, pY);
         break;
       case CPlotItem::bandedGraph:
         static_cast< CBandedGraphData * >(&data())->reallocated(pX, pY, pY2);
         break;
       case CPlotItem::histoItem1d:
         static_cast< CHistoCurveData * >(&data())->reallocated(pX);
         break;
       default:
         fatalError();
         break;
     }
 }
void C2DPlotCurve::setDataSize (const size_t & size)
Definition at line 602 of file CopasiPlot.cpp.
References CPlotItem::bandedGraph, CPlotItem::curve2d, fatalError, CPlotItem::histoItem1d, and mCurveType.
 {
   switch (mCurveType)
     {
       case CPlotItem::curve2d:
         static_cast< C2DCurveData * >(&data())->setSize(size);
         break;
       case CPlotItem::bandedGraph:
         static_cast< CBandedGraphData * >(&data())->setSize(size);
         break;
       case CPlotItem::histoItem1d:
         static_cast< CHistoCurveData * >(&data())->setSize(size);
         break;
       default:
         fatalError();
         break;
     }
 }
void C2DPlotCurve::setIncrement (const C_FLOAT64 & increment)
Definition at line 647 of file CopasiPlot.cpp.
References mIncrement.
Referenced by CopasiPlot::initFromSpec().
 {
   mIncrement = increment;
 }
Member Data Documentation
COutputInterface::Activity C2DPlotCurve::mActivity private
Definition at line 212 of file CopasiPlot.h.
Referenced by getActivity().
CPlotItem::Type C2DPlotCurve::mCurveType private
Definition at line 208 of file CopasiPlot.h.
Referenced by getType(), reallocatedData(), and setDataSize().
C_FLOAT64 C2DPlotCurve::mIncrement private
Definition at line 210 of file CopasiPlot.h.
Referenced by getIncrement(), and setIncrement().
QMutex* C2DPlotCurve::mpMutex private
Definition at line 206 of file CopasiPlot.h.
Referenced by C2DPlotCurve(), and drawCurve().
The documentation for this class was generated from the following files:
CopasiPlot.h
CopasiPlot.cpp