COPASI API: CCopasiXMLParser::BoundingBoxElement Class Reference
CCopasiXMLParser::BoundingBoxElement Class Reference
Public Member Functions
BoundingBoxElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~BoundingBoxElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { BoundingBox = 0, Position, Dimensions }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4774 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::BoundingBoxElement::Element private
Enumerator
BoundingBox
Position
Dimensions
Definition at line 4781 of file CCopasiXMLParser.h.
     {
       BoundingBox = 0,
       Position,
       Dimensions
     };
Constructor & Destructor Documentation
CCopasiXMLParser::BoundingBoxElement::BoundingBoxElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 14475 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::BoundingBoxElement::~BoundingBoxElement () virtual
Destructor
Definition at line 14480 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::BoundingBoxElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 14538 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case BoundingBox:
         if (strcmp(pszName, "BoundingBox"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "BoundingBox", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       case Position:
         if (strcmp(pszName, "Position"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Position", mParser.getCurrentLineNumber());
         break;
       case Dimensions:
         if (strcmp(pszName, "Dimensions"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Dimensions", mParser.getCurrentLineNumber());
         mCurrentElement = BoundingBox;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::BoundingBoxElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 14485 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CLLineEnding::getBoundingBox(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pLineEnding, CLBoundingBox::setDimensions(), CLBoundingBox::setPosition(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   mpCurrentHandler = NULL;
   const char * X;
   const char * Y;
   const char * WIDTH;
   const char * HEIGHT;
   switch (mCurrentElement)
     {
       case BoundingBox:
         if (strcmp(pszName, "BoundingBox"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "BoundingBox", mParser.getCurrentLineNumber());
         break;
       case Position:
         if (!strcmp(pszName, "Position"))
           {
             X = mParser.getAttributeValue("x", papszAttrs);
             Y = mParser.getAttributeValue("y", papszAttrs);
             mCommon.pLineEnding->getBoundingBox()->setPosition(CLPoint(CCopasiXMLInterface::DBL(X), CCopasiXMLInterface::DBL(Y)));
           }
         break;
       case Dimensions:
         if (!strcmp(pszName, "Dimensions"))
           {
             WIDTH = mParser.getAttributeValue("width", papszAttrs);
             HEIGHT = mParser.getAttributeValue("height", papszAttrs);
             mCommon.pLineEnding->getBoundingBox()->setDimensions(CLDimensions(CCopasiXMLInterface::DBL(WIDTH), CCopasiXMLInterface::DBL(HEIGHT)));
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp