COPASI API: CCopasiXMLParser::GroupElement Class Reference
CCopasiXMLParser::GroupElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
GroupElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~GroupElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Group = 0, GroupChild }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4733 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::GroupElement::Element private
Enumerator
Group
GroupChild
Definition at line 4740 of file CCopasiXMLParser.h.
     {
       Group = 0,
       GroupChild
     };
Constructor & Destructor Documentation
CCopasiXMLParser::GroupElement::GroupElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 12597 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::GroupElement::~GroupElement () virtual
Destructor
Definition at line 12602 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpCurrentHandler);
 }
Member Function Documentation
void CCopasiXMLParser::GroupElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 12862 of file CCopasiXMLParser.cpp.
References CLText::ANCHOR_START, CLText::ANCHOR_TOP, CCopasiMessage::EXCEPTION, CCopasiObject::getObjectParent(), CLGroup::isSetEndHead(), CLGraphicalPrimitive2D::isSetFill(), CLGraphicalPrimitive2D::isSetFillRule(), CLGroup::isSetFontFamily(), CLGroup::isSetFontStyle(), CLGroup::isSetFontWeight(), CLGroup::isSetStartHead(), CLGraphicalPrimitive1D::isSetStroke(), CLGraphicalPrimitive1D::isSetStrokeWidth(), CLGroup::isSetTextAnchor(), CLGroup::isSetVTextAnchor(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive2D::NONZERO, SCopasiXMLParserCommon::pGroup, CLGroup::setEndHead(), CLGraphicalPrimitive2D::setFillColor(), CLGraphicalPrimitive2D::setFillRule(), CLGroup::setFontFamily(), CLGroup::setFontStyle(), CLGroup::setFontWeight(), CLGroup::setStartHead(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), CLGroup::setTextAnchor(), CLGroup::setVTextAnchor(), START_ELEMENT, CLText::STYLE_NORMAL, UNKNOWN_ELEMENT, and CLText::WEIGHT_NORMAL.
 {
   switch (mCurrentElement)
     {
       case Group:
       {
         if (strcmp(pszName, "Group"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Group", mParser.getCurrentLineNumber());
         assert(mCommon.pGroup != NULL);
         // if the group is part of another group, we have to set mCommon.pGroup
         // to that group, otherwise, we have to set it to NULL
         // a group is part of another group, if its grandFather is a group
         // (as group elements are stored in a separate vector)
         CCopasiContainer* parent = mCommon.pGroup->getObjectParent();
         CCopasiContainer* grandFather = (parent == NULL ? NULL : parent->getObjectParent());
         if (grandFather != NULL && dynamic_cast<CLGroup*>(grandFather) != NULL)
           {
             mCommon.pGroup = dynamic_cast<CLGroup*>(grandFather);
             //tell the handler where to continue
             mParser.popElementHandler();
             //reset handler
             mCurrentElement = Group;
             //call parent handler
             mParser.onEndElement(pszName);
             //no need to delete Handler (since it is the only one the destructor
             //will handle it)
             break;
           }
         else
           {
             if (dynamic_cast<CLStyle*>(parent) != NULL)
               {
                 // if this group is the child of a style, we should set some default values on attributes
                 // so that they are set explicitly
                 if (!mCommon.pGroup->isSetStroke())
                   {
                     mCommon.pGroup->setStroke("none");
                   }
                 if (!mCommon.pGroup->isSetStrokeWidth())
                   {
                     mCommon.pGroup->setStrokeWidth(0.0);
                   }
                 if (!mCommon.pGroup->isSetFill())
                   {
                     mCommon.pGroup->setFillColor("none");
                   }
                 if (!mCommon.pGroup->isSetFillRule())
                   {
                     mCommon.pGroup->setFillRule(CLGraphicalPrimitive2D::NONZERO);
                   }
                 if (!mCommon.pGroup->isSetFontFamily())
                   {
                     mCommon.pGroup->setFontFamily("sans-serif");
                   }
                 if (!mCommon.pGroup->isSetFontWeight())
                   {
                     mCommon.pGroup->setFontWeight(CLText::WEIGHT_NORMAL);
                   }
                 if (!mCommon.pGroup->isSetFontStyle())
                   {
                     mCommon.pGroup->setFontStyle(CLText::STYLE_NORMAL);
                   }
                 if (!mCommon.pGroup->isSetTextAnchor())
                   {
                     mCommon.pGroup->setTextAnchor(CLText::ANCHOR_START);
                   }
                 if (!mCommon.pGroup->isSetVTextAnchor())
                   {
                     mCommon.pGroup->setVTextAnchor(CLText::ANCHOR_TOP);
                   }
                 if (!mCommon.pGroup->isSetStartHead())
                   {
                     mCommon.pGroup->setStartHead("none");
                   }
                 if (!mCommon.pGroup->isSetEndHead())
                   {
                     mCommon.pGroup->setEndHead("none");
                   }
               }
             mCommon.pGroup = NULL;
           }
         mParser.popElementHandler();
         //reset handler
         mCurrentElement = START_ELEMENT;
         //call parent handler
         mParser.onEndElement(pszName);
         break;
       }
       case GroupChild:
         // a group can have many different children
         if (strcmp(pszName, "Curve")
             && strcmp(pszName, "Text")
             && strcmp(pszName, "Rectangle")
             && strcmp(pszName, "Polygon")
             && strcmp(pszName, "Ellipse")
             && strcmp(pszName, "Group")
             && strcmp(pszName, "Image")
            )
           {
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
           }
         //tell the handler where to continue
         mCurrentElement = Group;
         //no need to delete Handler (since it is the only one the destructor
         //will handle it)
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::GroupElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 12607 of file CCopasiXMLParser.cpp.
References CLGroup::addChildElement(), CLText::ANCHOR_BOTTOM, CLText::ANCHOR_END, CLText::ANCHOR_MIDDLE, CLText::ANCHOR_START, CLText::ANCHOR_TOP, CLGraphicalPrimitive2D::EVENODD, CCopasiMessage::EXCEPTION, CLGroup::getElement(), CLStyle::getGroup(), CLLineEnding::getGroup(), CLGroup::getNumElements(), CLGraphicalPrimitive2D::INHERIT, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CLGraphicalPrimitive2D::NONZERO, CLGraphicalPrimitive1D::parseDashArray(), CLTransformation2D::parseTransformation(), SCopasiXMLParserCommon::pGroup, SCopasiXMLParserCommon::pLineEnding, SCopasiXMLParserCommon::pStyle, CLGroup::setEndHead(), CLGraphicalPrimitive2D::setFillColor(), CLGraphicalPrimitive2D::setFillRule(), CLGroup::setFontFamily(), CLGroup::setFontSize(), CLGroup::setFontStyle(), CLGroup::setFontWeight(), CLStyle::setGroup(), CLLineEnding::setGroup(), CLGroup::setStartHead(), CLGraphicalPrimitive1D::setStroke(), CLGraphicalPrimitive1D::setStrokeWidth(), CLGroup::setTextAnchor(), CLGroup::setVTextAnchor(), strToDouble(), CLText::STYLE_ITALIC, CLText::STYLE_NORMAL, UNKNOWN_ELEMENT, CLText::WEIGHT_BOLD, and CLText::WEIGHT_NORMAL.
 {
   // TODO This will not work for groups, since the order of children is not fixed.
   mCurrentElement++; /* We should always be on the next element */
   const char * Transform;
   const char * Stroke;
   const char * StrokeWidth;
   const char * StrokeDashArray;
   const char * Fill;
   const char * FillRule;
   const char * FontFamily;
   const char * FontSize;
   const char * FontWeight;
   const char * FontStyle;
   const char * TextAnchor;
   const char * VTextAnchor;
   const char * StartHead;
   const char * EndHead;
   mpCurrentHandler = NULL;
   CLGroup* pGroup = NULL;
   switch (mCurrentElement)
     {
       case Group:
         if (strcmp(pszName, "Group"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Group", mParser.getCurrentLineNumber());
         Transform = mParser.getAttributeValue("transform", papszAttrs, false);
         Stroke = mParser.getAttributeValue("stroke", papszAttrs, false);
         StrokeWidth = mParser.getAttributeValue("stroke-width", papszAttrs, false);
         StrokeDashArray = mParser.getAttributeValue("stroke-dasharray", papszAttrs, false);
         Fill = mParser.getAttributeValue("fill", papszAttrs, false);
         FillRule = mParser.getAttributeValue("fill-rule", papszAttrs, false);
         FontFamily = mParser.getAttributeValue("font-family", papszAttrs, false);
         FontSize = mParser.getAttributeValue("font-size", papszAttrs, false);
         FontWeight = mParser.getAttributeValue("font-weight", papszAttrs, false);
         FontStyle = mParser.getAttributeValue("font-style", papszAttrs, false);
         TextAnchor = mParser.getAttributeValue("text-anchor", papszAttrs, false);
         VTextAnchor = mParser.getAttributeValue("vtext-anchor", papszAttrs, false);
         StartHead = mParser.getAttributeValue("startHead", papszAttrs, false);
         EndHead = mParser.getAttributeValue("endHead", papszAttrs, false);
         pGroup = new CLGroup();
         if (Transform != NULL)
           {
             pGroup->parseTransformation(Transform);
           }
         if (Stroke != NULL)
           {
             pGroup->setStroke(Stroke);
           }
         if (StrokeWidth != NULL)
           {
             double width = strToDouble(StrokeWidth, NULL);
             pGroup->setStrokeWidth(width);
           }
         if (StrokeDashArray != NULL)
           {
             pGroup->parseDashArray(StrokeDashArray);
           }
         if (Fill != NULL)
           {
             pGroup->setFillColor(Fill);
           }
         if (FillRule != NULL)
           {
             std::string f(FillRule);
             if (f == "nonzero")
               {
                 pGroup->setFillRule(CLGraphicalPrimitive2D::NONZERO);
               }
             else if (f == "evenodd")
               {
                 pGroup->setFillRule(CLGraphicalPrimitive2D::EVENODD);
               }
             else
               {
                 pGroup->setFillRule(CLGraphicalPrimitive2D::INHERIT);
               }
           }
         if (FontFamily != NULL)
           {
             pGroup->setFontFamily(FontFamily);
           }
         if (FontSize != NULL)
           {
             pGroup->setFontSize(CLRelAbsVector(FontSize));
           }
         if (FontStyle != NULL)
           {
             std::string s(FontStyle);
             if (s == "normal")
               {
                 pGroup->setFontStyle(CLText::STYLE_NORMAL);
               }
             else if (s == "italic")
               {
                 pGroup->setFontStyle(CLText::STYLE_ITALIC);
               }
           }
         if (FontWeight != NULL)
           {
             std::string s(FontWeight);
             if (s == "normal")
               {
                 pGroup->setFontWeight(CLText::WEIGHT_NORMAL);
               }
             else if (s == "bold")
               {
                 pGroup->setFontWeight(CLText::WEIGHT_BOLD);
               }
           }
         if (TextAnchor != NULL)
           {
             std::string s(TextAnchor);
             if (s == "start")
               {
                 pGroup->setTextAnchor(CLText::ANCHOR_START);
               }
             else if (s == "middle")
               {
                 pGroup->setTextAnchor(CLText::ANCHOR_MIDDLE);
               }
             else if (s == "end")
               {
                 pGroup->setTextAnchor(CLText::ANCHOR_END);
               }
           }
         if (VTextAnchor != NULL)
           {
             std::string s(VTextAnchor);
             if (s == "top")
               {
                 pGroup->setVTextAnchor(CLText::ANCHOR_TOP);
               }
             else if (s == "middle")
               {
                 pGroup->setVTextAnchor(CLText::ANCHOR_MIDDLE);
               }
             else if (s == "bottom")
               {
                 pGroup->setVTextAnchor(CLText::ANCHOR_BOTTOM);
               }
           }
         if (StartHead != NULL)
           {
             pGroup->setStartHead(StartHead);
           }
         if (EndHead != NULL)
           {
             pGroup->setEndHead(EndHead);
           }
         // now we have to check where to add the group
         // it could belong to another group,
         // a style or a line ending
         if (mCommon.pGroup != NULL)
           {
             mCommon.pGroup->addChildElement(pGroup);
             mCommon.pGroup = dynamic_cast<CLGroup*>(mCommon.pGroup->getElement(mCommon.pGroup->getNumElements() - 1));
           }
         else if (mCommon.pStyle != NULL)
           {
             mCommon.pStyle->setGroup(pGroup);
             mCommon.pGroup = mCommon.pStyle->getGroup();
           }
         else
           {
             assert(mCommon.pLineEnding != NULL);
             mCommon.pLineEnding->setGroup(pGroup);
             mCommon.pGroup = mCommon.pLineEnding->getGroup();
           }
         assert(mCommon.pGroup != NULL);
         // delete the group element again since the add/set methods made a copy
         delete pGroup;
         return;
         break;
         // a group can have many different children
       case GroupChild:
         // handle the possible children
         if (!strcmp(pszName, "Curve"))
           {
             mpCurrentHandler = new RenderCurveElement(mParser, mCommon);
           }
         else if (!strcmp(pszName, "Text"))
           {
             mpCurrentHandler = new TextElement(mParser, mCommon);
           }
         else if (!strcmp(pszName, "Rectangle"))
           {
             mpCurrentHandler = new RectangleElement(mParser, mCommon);
           }
         else if (!strcmp(pszName, "Polygon"))
           {
             mpCurrentHandler = new PolygonElement(mParser, mCommon);
           }
         else if (!strcmp(pszName, "Ellipse"))
           {
             mpCurrentHandler = new EllipseElement(mParser, mCommon);
           }
         else if (!strcmp(pszName, "Group"))
           {
             mpCurrentHandler = new GroupElement(mParser, mCommon);
           }
         else if (!strcmp(pszName, "Image"))
           {
             mpCurrentHandler = new ImageElement(mParser, mCommon);
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   if (mpCurrentHandler != NULL)
     {
       mParser.pushElementHandler(mpCurrentHandler);
     }
   mpCurrentHandler->start(pszName, papszAttrs);
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp