COPASI API: CFluxScore Class Reference
CFluxScore Class Reference
#include <CFluxScore.h>
Public Member Functions
CFluxScore ()
CFluxScore (const std::vector< C_FLOAT64 > &fluxModes)
bool operator< (const CFluxScore &rhs) const
~CFluxScore ()
Private Attributes
CVector< unsigned char > mScore
Friends
std::ostream & operator<< (std::ostream &os, const CFluxScore &A)
Detailed Description
CFluxScore class. Used to compare flux modes
Created for Copasi by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 28 of file CFluxScore.h.
Constructor & Destructor Documentation
CFluxScore::CFluxScore ()
Default constructor
CFluxScore class. Used to compare flux modes
Created for COPASI by Stefan Hoops 2002-05-08 (C) Stefan Hoops 2002
Definition at line 36 of file CFluxScore.cpp.
References CONSTRUCTOR_TRACE.
 {CONSTRUCTOR_TRACE;}
CFluxScore::CFluxScore (const std::vector< C_FLOAT64 > & fluxModes)
Specific constructor
Parameters
const vector < C_FLOAT64 > & fluxModes
Definition at line 38 of file CFluxScore.cpp.
References CVectorCore< CType >::array(), CONSTRUCTOR_TRACE, mScore, and CVector< CType >::resize().
 {
   CONSTRUCTOR_TRACE;
   unsigned char Remainder = fluxMode.size() % (CHAR_BIT * sizeof(unsigned char));
   size_t imax = fluxMode.size() / (CHAR_BIT * sizeof(unsigned char));
   unsigned char k, kmax = CHAR_BIT * sizeof(unsigned char);
   // Size the scoring vector.
   // Note we have to allocate an extra int if Remainder != 0
   mScore.resize(imax + (Remainder ? 1 : 0));
   std::vector < C_FLOAT64 >::const_iterator itMode = fluxMode.begin();
   unsigned char * pScore = mScore.array();
   unsigned char * pScoreEnd = pScore + imax;
   // Set the bits to 1 if the corresponding fluxMode coefficient is non zero.
   for (; pScore != pScoreEnd; ++pScore)
     {
       *pScore = 0;
       for (k = kmax; k > 0; ++itMode)
         {
           k--;
           if (*itMode != 0)
             (*pScore) |= (0x01 << k);
         }
     }
   // Do the same for the remaining fluxMode coefficients.
   if (Remainder)
     {
       k = kmax;
       kmax -= Remainder;
       *pScore = 0;
       for (; k > kmax; ++itMode)
         {
           k--;
           if (*itMode != 0)
             (*pScore) |= (0x01 << k);
         }
     }
 }
CFluxScore::~CFluxScore ()
Destructor();
Definition at line 85 of file CFluxScore.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
bool CFluxScore::operator< (const CFluxScore & rhs) const
Comparison operator deciding whether lhs has a smaller flux score than rhs
Parameters
const CFluxScore & lhs
const CFluxScore & rhs
Returns
"bool"
Definition at line 87 of file CFluxScore.cpp.
References CVectorCore< CType >::array(), mScore, and CVectorCore< CType >::size().
 {
   const unsigned char * pScoreLhs = mScore.array();
   const unsigned char * pScoreRhs = rhs.mScore.array();
   const unsigned char * pScoreEnd = pScoreLhs + mScore.size();
   for (; pScoreLhs != pScoreEnd; ++pScoreLhs, ++pScoreRhs)
     if (*pScoreLhs != (*pScoreLhs & *pScoreRhs))
       return false;
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CFluxScore & A) friend
Definition at line 100 of file CFluxScore.cpp.
 {
   const unsigned char * pScore = A.mScore.array();
   const unsigned char * pScoreEnd = pScore + A.mScore.size();
   unsigned char k, kmax = CHAR_BIT * sizeof(unsigned char);
   for (k = kmax; pScore != pScoreEnd; ++pScore)
     {
       k = kmax;
       while (k > 0)
         {
           k--;
           os << ((*pScore & (0x01 << k)) >> k);
         }
     }
   os << std::endl;
   return os;
 }
Member Data Documentation
CVector< unsigned char > CFluxScore::mScore private
The score of a flux mode
Definition at line 36 of file CFluxScore.h.
Referenced by CFluxScore(), operator<(), and operator<<().
The documentation for this class was generated from the following files:
CFluxScore.h
CFluxScore.cpp