COPASI API: SensWidgetComboBox Class Reference
SensWidgetComboBox Class Reference
#include <SensWidgetComboBox.h>
Public Member Functions
void fillFromList (const std::vector< CObjectLists::ListType > &list)
CObjectLists::ListType getCurrentObjectList () const
SensWidgetComboBox (QWidget *parent=0, const char *name=0)
bool setCurrentObjectList (CObjectLists::ListType lt)
Protected Attributes
std::vector
< CObjectLists::ListType > mIndexTable
Detailed Description
This class handles a combobox to choose from lists of object lists
Definition at line 36 of file SensWidgetComboBox.h.
Constructor & Destructor Documentation
SensWidgetComboBox::SensWidgetComboBox (QWidget * parent = 0, const char * name = 0)
Definition at line 33 of file SensWidgetComboBox.cpp.
   : QComboBox(parent)
 {
   setObjectName(QString::fromUtf8(name));
 }
Member Function Documentation
void SensWidgetComboBox::fillFromList (const std::vector< CObjectLists::ListType > & list)
this fills the combobox with a new list of entries. If the old current value is still allowed in the new list, it is set. Otherwise the box shows the first item.
Definition at line 39 of file SensWidgetComboBox.cpp.
References FROM_UTF8, getCurrentObjectList(), CObjectLists::ListTypeName, mIndexTable, and setCurrentObjectList().
 {
   //store old selection
   CObjectLists::ListType oldItem = getCurrentObjectList();
   mIndexTable = list;
   //fill combobox
   clear();
   std::vector<CObjectLists::ListType>::const_iterator it, itEnd = mIndexTable.end();
   for (it = mIndexTable.begin(); it != itEnd; ++it)
     insertItem(this->count(), FROM_UTF8(CObjectLists::ListTypeName[*it]));
   //restore old selection, if possible
   if (!setCurrentObjectList(oldItem))
     setCurrentIndex(0);
 }
CObjectLists::ListType SensWidgetComboBox::getCurrentObjectList () const
Definition at line 58 of file SensWidgetComboBox.cpp.
References CObjectLists::EMPTY_LIST, and mIndexTable.
Referenced by fillFromList(), and SensitivitiesWidget::updateLineeditEnable().
 {
   unsigned int index = currentIndex();
   if (index < mIndexTable.size())
     return mIndexTable[currentIndex()];
   else
     return CObjectLists::EMPTY_LIST;
 }
bool SensWidgetComboBox::setCurrentObjectList (CObjectLists::ListType lt)
set current selection (if possible). It returns true if the operation was successful.
Definition at line 68 of file SensWidgetComboBox.cpp.
References mIndexTable.
Referenced by fillFromList().
 {
   std::vector<CObjectLists::ListType>::const_iterator it;
   it = std::find(mIndexTable.begin(),
                  mIndexTable.end(),
                  lt);
   if (it == mIndexTable.end()) return false;
   setCurrentIndex(it - mIndexTable.begin());
   return true;
 }
Member Data Documentation
std::vector<CObjectLists::ListType> SensWidgetComboBox::mIndexTable protected
Definition at line 61 of file SensWidgetComboBox.h.
Referenced by fillFromList(), getCurrentObjectList(), and setCurrentObjectList().
The documentation for this class was generated from the following files:
SensWidgetComboBox.h
SensWidgetComboBox.cpp