COPASI API: CRDFGraph Class Reference
CRDFGraph Class Reference
#include <CRDFGraph.h>
Public Types
typedef std::set< CRDFTriplet >
::const_iterator const_iterator
typedef std::set< CRDFTriplet >
::iterator iterator
typedef std::multimap
< CRDFNode *, CRDFTriplet > Node2Triplet
typedef std::pair
< Node2Triplet::const_iterator,
Node2Triplet::const_iterator > Node2TripletConstRange
typedef std::pair
< Node2Triplet::iterator,
Node2Triplet::iterator > Node2TripletRange
typedef std::multimap
< CRDFPredicate, CRDFTriplet > Predicate2Triplet
typedef std::pair
< Predicate2Triplet::const_iterator,
Predicate2Triplet::const_iterator > Predicate2TripletConstRange
typedef std::pair
< Predicate2Triplet::iterator,
Predicate2Triplet::iterator > Predicate2TripletRange
Public Member Functions
bool addNameSpace (const std::string &prefix, const std::string &uri)
CRDFTriplet addTriplet (const CRDFSubject &subject, const CRDFPredicate &predicate, const CRDFObject &object)
void clean ()
CRDFGraph ()
CRDFNode * createAboutNode (const std::string &key)
void destroyUnreferencedNode (CRDFNode *pNode)
std::string generatedNodeId (const std::string &existingId="")
const CRDFNode * getAboutNode () const
const std::map< std::string,
CRDFNode * > & getBlankNodeMap () const
std::set< CRDFTriplet > getIncomingTriplets (const CRDFNode *pObject) const
const std::map< std::string,
CRDFNode * > & getLocalResourceNodeMap () const
const std::map< std::string,
std::string > & getNameSpaceMap () const
std::set< const CRDFNode * > getParentSubjects (const CRDFNode *pObject) const
CRDFPredicate::Path getPredicatePath (const CRDFNode *pNode)
const std::vector< CRDFNode * > & getRemoteResourceNodes () const
const std::set< CRDFTriplet > & getTriplets () const
std::set< CRDFTriplet > getTriplets (const CRDFPredicate &predicate, const bool &expandBag=true) const
std::set< CRDFTriplet > getTriplets (const CRDFNode *pSubject) const
std::set< CRDFTriplet > getTriplets (const CRDFNode *pSubject, const CRDFPredicate &predicate) const
bool guessGraphRoot (const std::string &about=" ")
CRDFTriplet moveTriplet (CRDFNode *pNewSubject, const CRDFTriplet &triplet)
void removeTriplet (CRDFNode *pSubject, const CRDFPredicate &predicate, CRDFNode *pObject)
void updateNamespaces ()
~CRDFGraph ()
Private Member Functions
bool addTriplet (const CRDFTriplet &triplet)
bool removeEmptyNodes ()
void removeTriplet (const CRDFTriplet &triplet)
Private Attributes
std::map< std::string, CRDFNode * > mBlankNodeId2Node
std::set< unsigned int > mGeneratedIds
std::map< std::string,
std::string > mIdMap
std::vector< CRDFNode * > mLiteralNodes
std::map< std::string, CRDFNode * > mLocalResource2Node
Node2Triplet mObject2Triplet
CRDFNode * mpAbout
Predicate2Triplet mPredicate2Triplet
std::map< std::string,
std::string > mPrefix2Namespace
std::vector< CRDFNode * > mRemoteResourceNodes
Node2Triplet mSubject2Triplet
std::set< CRDFTriplet > mTriplets
Friends
bool CRDFNode::addTripletToGraph (const CRDFTriplet &triplet) const
void CRDFNode::removeTripletFromGraph (const CRDFTriplet &triplet) const
Detailed Description
Definition at line 36 of file CRDFGraph.h.
Member Typedef Documentation
typedef std::set< CRDFTriplet >::const_iterator CRDFGraph::const_iterator
Definition at line 40 of file CRDFGraph.h.
typedef std::set< CRDFTriplet >::iterator CRDFGraph::iterator
Definition at line 39 of file CRDFGraph.h.
typedef std::multimap< CRDFNode *, CRDFTriplet > CRDFGraph::Node2Triplet
Definition at line 42 of file CRDFGraph.h.
typedef std::pair< Node2Triplet::const_iterator, Node2Triplet::const_iterator> CRDFGraph::Node2TripletConstRange
Definition at line 44 of file CRDFGraph.h.
typedef std::pair< Node2Triplet::iterator, Node2Triplet::iterator> CRDFGraph::Node2TripletRange
Definition at line 43 of file CRDFGraph.h.
typedef std::multimap< CRDFPredicate, CRDFTriplet > CRDFGraph::Predicate2Triplet
Definition at line 46 of file CRDFGraph.h.
typedef std::pair< Predicate2Triplet::const_iterator, Predicate2Triplet::const_iterator> CRDFGraph::Predicate2TripletConstRange
Definition at line 48 of file CRDFGraph.h.
typedef std::pair< Predicate2Triplet::iterator, Predicate2Triplet::iterator> CRDFGraph::Predicate2TripletRange
Definition at line 47 of file CRDFGraph.h.
Constructor & Destructor Documentation
CRDFGraph::CRDFGraph ()
Default Constructor
Definition at line 33 of file CRDFGraph.cpp.
                     :
   mpAbout(NULL),
   mPrefix2Namespace(),
   mBlankNodeId2Node(),
   mLocalResource2Node(),
   mRemoteResourceNodes(),
   mLiteralNodes(),
   mTriplets(),
   mSubject2Triplet(),
   mObject2Triplet(),
   mPredicate2Triplet(),
   mGeneratedIds(),
   mIdMap()
 {}
CRDFGraph::~CRDFGraph ()
Destructor
Definition at line 48 of file CRDFGraph.cpp.
References mBlankNodeId2Node, mLiteralNodes, mLocalResource2Node, mObject2Triplet, mPredicate2Triplet, mRemoteResourceNodes, mSubject2Triplet, mTriplets, and pdelete.
 {
   // We first clear the sets and maps
   // This is necessary since they refer to the nodes which are destroyed later.
   mTriplets.clear();
   mSubject2Triplet.clear();
   mObject2Triplet.clear();
   mPredicate2Triplet.clear();
   // Note: mpAbout is not explicitly destroyed since it is contained in the map
   // of resource nodes.
   std::map< std::string, CRDFNode * >::iterator itMap;
   std::map< std::string, CRDFNode * >::iterator endMap;
   for (itMap = mBlankNodeId2Node.begin(), endMap = mBlankNodeId2Node.end();
        itMap != endMap; ++itMap)
     pdelete(itMap->second);
   for (itMap = mLocalResource2Node.begin(), endMap = mLocalResource2Node.end();
        itMap != endMap; ++itMap)
     pdelete(itMap->second);
   std::vector< CRDFNode *>::iterator itVector;
   std::vector< CRDFNode *>::iterator endVector;
   for (itVector = mRemoteResourceNodes.begin(), endVector = mRemoteResourceNodes.end();
        itVector != endVector; ++itVector)
     pdelete(*itVector);
   for (itVector = mLiteralNodes.begin(), endVector = mLiteralNodes.end();
        itVector != endVector; ++itVector)
     pdelete(*itVector);
 }
Member Function Documentation
bool CRDFGraph::addNameSpace (const std::string & prefix, const std::string & uri)
Add a name space including prefix to the graph. It returns false if the prefix was already used with another namespace
Parameters
const std::string & prefix
const std::string & namespace
Returns
bool success;
Definition at line 128 of file CRDFGraph.cpp.
References CCopasiMessage::ERROR, MCAnnotation, and mPrefix2Namespace.
Referenced by updateNamespaces().
 {
   std::pair< std::map< std::string, std::string >::iterator, bool > inserted =
     mPrefix2Namespace.insert(std::pair< std::string, std::string >(prefix, uri));
   if (inserted.second || (inserted.first->second == uri))
     return true;
   CCopasiMessage(CCopasiMessage::ERROR, MCAnnotation + 2,
                  prefix.c_str(), inserted.first->second.c_str(), uri.c_str());
   return false;
 }
CRDFTriplet CRDFGraph::addTriplet (const CRDFSubject & subject, const CRDFPredicate & predicate, const CRDFObject & object)
Add a triplet to the graph
Parameters
const CRDFSubject & subject
const CRDFPredicate & predicate
const CRDFObject & object
Returns
CRDFTriplet triplet
Definition at line 141 of file CRDFGraph.cpp.
References CRDFSubject::BLANK_NODE, CRDFSubject::getBlankNodeID(), CRDFSubject::getResource(), CRDFSubject::getType(), CRDFSubject::isLocal(), CRDFNode::isSubjectNode(), mBlankNodeId2Node, mLocalResource2Node, mRemoteResourceNodes, CRDFSubject::RESOURCE, and CRDFNode::setSubject().
Referenced by CRDFNode::addEdge(), CRDFNode::addTripletToGraph(), CRDFGraphConverter::convert(), CMIRIAMInfo::createBiologicalDescription(), CMIRIAMInfo::createCreator(), CRDFNode::createMissingAncestors(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), CMIRIAMInfo::setCreatedDT(), and CRDFNode::setFieldValue().
 {
   // Find or create the subject node
   std::map< std::string, CRDFNode * >::iterator found;
   CRDFNode * pSubjectNode = NULL;
   switch (subject.getType())
     {
       case CRDFSubject::RESOURCE:
         if (subject.isLocal())
           {
             found = mLocalResource2Node.find(subject.getResource());
             if (found != mLocalResource2Node.end())
               {
                 pSubjectNode = found->second;
                 if (!pSubjectNode->isSubjectNode())
                   pSubjectNode->setSubject(subject);
               }
             else
               {
                 pSubjectNode = new CRDFNode(*this);
                 pSubjectNode->setSubject(subject);
                 mLocalResource2Node[subject.getResource()] = pSubjectNode;
               }
           }
         else
           {
             pSubjectNode = new CRDFNode(*this);
             pSubjectNode->setSubject(subject);
             mRemoteResourceNodes.push_back(pSubjectNode);
           }
         break;
       case CRDFSubject::BLANK_NODE:
         found = mBlankNodeId2Node.find(subject.getBlankNodeID());
         if (found != mBlankNodeId2Node.end())
           pSubjectNode = found->second;
         else
           {
             pSubjectNode = new CRDFNode(*this);
             pSubjectNode->setSubject(subject);
             mBlankNodeId2Node[subject.getBlankNodeID()] = pSubjectNode;
           }
         break;
     }
   // Find or create the object node
   CRDFNode * pObjectNode = NULL;
   switch (object.getType())
     {
       case CRDFObject::RESOURCE:
         if (object.isLocal())
           {
             found = mLocalResource2Node.find(object.getResource());
             if (found != mLocalResource2Node.end())
               {
                 pObjectNode = found->second;
                 if (!pObjectNode->isObjectNode())
                   pObjectNode->setObject(object);
               }
             else
               {
                 pObjectNode = new CRDFNode(*this);
                 pObjectNode->setObject(object);
                 mLocalResource2Node[object.getResource()] = pObjectNode;
               }
           }
         else
           {
             pObjectNode = new CRDFNode(*this);
             pObjectNode->setObject(object);
             mRemoteResourceNodes.push_back(pObjectNode);
           }
         break;
       case CRDFObject::BLANK_NODE:
         found = mBlankNodeId2Node.find(object.getBlankNodeID());
         if (found != mBlankNodeId2Node.end())
           pObjectNode = found->second;
         else
           {
             pObjectNode = new CRDFNode(*this);
             pObjectNode->setObject(object);
             mBlankNodeId2Node[object.getBlankNodeID()] = pObjectNode;
           }
         break;
       case CRDFObject::LITERAL:
         pObjectNode = new CRDFNode(*this);
         pObjectNode->setObject(object);
         mLiteralNodes.push_back(pObjectNode);
         break;
     }
   if (predicate == CRDFPredicate::rdf_predicate &&
       pObjectNode->getObject().getType() == CRDFObject::RESOURCE &&
       CRDFPredicate::getPredicateFromURI(pObjectNode->getObject().getResource()) == CRDFPredicate::rdf_li)
     pObjectNode->getObject().setResource(CRDFPredicate::getURI(CRDFPredicate::rdf_li), false);
   return pSubjectNode->addEdge(predicate, pObjectNode);
 }
bool CRDFGraph::addTriplet (const CRDFTriplet & triplet) private
Add a triplet to the graph. This method should only be used by CRDFNode
Parameters
const CRDFTriplet & triplet
Returns
bool success
Definition at line 258 of file CRDFGraph.cpp.
References mObject2Triplet, mPredicate2Triplet, mSubject2Triplet, mTriplets, CRDFTriplet::pObject, CRDFTriplet::Predicate, and CRDFTriplet::pSubject.
 {
   if (!triplet)
     return false;
   std::pair< std::set< CRDFTriplet >::iterator, bool> Insert = mTriplets.insert(triplet);
   if (Insert.second)
     {
       mSubject2Triplet.insert(std::pair< CRDFNode * const, CRDFTriplet >(triplet.pSubject, triplet));
       mObject2Triplet.insert(std::pair< CRDFNode * const, CRDFTriplet >(triplet.pObject, triplet));
       mPredicate2Triplet.insert(std::pair< const CRDFPredicate , CRDFTriplet >(triplet.Predicate, triplet));
       // DebugFile << "Inserted: " << triplet;
     }
   return true;
 }
void CRDFGraph::clean ()
Removes empty blank nodes . This should be called before CRDFWriter::xmlFromGraph
Definition at line 511 of file CRDFGraph.cpp.
References removeEmptyNodes().
Referenced by CMIRIAMInfo::save(), and CRDFGraphConverter::SBML2Copasi().
 {
   while (removeEmptyNodes()) {};
 }
CRDFNode * CRDFGraph::createAboutNode (const std::string & key)
If no about node exists a node is created with the attribute: rdf:about="#key
Parameters
const std::string & key
Returns
CRDFNode * pAbout
Definition at line 416 of file CRDFGraph.cpp.
References guessGraphRoot(), mLocalResource2Node, mpAbout, CRDFSubject::RESOURCE, CRDFSubject::setResource(), CRDFNode::setSubject(), and CRDFSubject::setType().
Referenced by CQRDFTreeView::enterProtected(), and CMIRIAMInfo::load().
 {
   std::string About = "#" + key;
   if (!guessGraphRoot(About))
     {
       CRDFSubject subject;
       mpAbout = new CRDFNode(*this);
       subject.setType(CRDFSubject::RESOURCE);
       subject.setResource(About, true);
       mpAbout->setSubject(subject);
       mLocalResource2Node[About] = mpAbout;
     }
   return mpAbout;
 }
void CRDFGraph::destroyUnreferencedNode (CRDFNode * pNode)
Destroy a CRDFNode
Parameters
CRDFNode * pNode
Definition at line 610 of file CRDFGraph.cpp.
References CRDFObject::BLANK_NODE, CRDFObject::getBlankNodeID(), CRDFNode::getObject(), CRDFObject::getResource(), CRDFObject::getType(), CRDFObject::isLocal(), CRDFObject::LITERAL, mBlankNodeId2Node, mLiteralNodes, mLocalResource2Node, mObject2Triplet, mRemoteResourceNodes, mSubject2Triplet, and CRDFObject::RESOURCE.
Referenced by removeEmptyNodes(), and removeTriplet().
 {
   // We only can remove nodes which are no longer objects.
   if (mObject2Triplet.count(pNode) > 0)
     return;
   // Remove all triplets where the node is subject
   std::pair< Node2Triplet::iterator, Node2Triplet::iterator> Range = mSubject2Triplet.equal_range(pNode);
   std::set< CRDFTriplet > RemoveTriplets;
   for (; Range.first != Range.second; ++Range.first)
     RemoveTriplets.insert(Range.first->second);
   std::set< CRDFTriplet >::const_iterator itTriplet = RemoveTriplets.begin();
   std::set< CRDFTriplet >::const_iterator endTriplet = RemoveTriplets.end();
   for (; itTriplet != endTriplet; ++itTriplet)
     itTriplet->pSubject->removeEdge(itTriplet->Predicate, itTriplet->pObject);
   // Remove the object from the appropriate container.
   switch (pNode->getObject().getType())
     {
       case CRDFObject::RESOURCE:
         if (pNode->getObject().isLocal())
           mLocalResource2Node.erase(pNode->getObject().getResource());
         else
           {
             // Check whether the pointer still exists mRemoteResourceNodes
             std::vector< CRDFNode * >::iterator it = mRemoteResourceNodes.begin();
             std::vector< CRDFNode * >::iterator end = mRemoteResourceNodes.end();
             for (; it != end; ++it)
               if (pNode == *it)
                 {
                   mRemoteResourceNodes.erase(it);
                   break;
                 }
           }
         break;
       case CRDFObject::BLANK_NODE:
         mBlankNodeId2Node.erase(pNode->getObject().getBlankNodeID());
         break;
       case CRDFObject::LITERAL:
       {
         // Check whether the pointer still exists in mLiteralNodes
         std::vector< CRDFNode * >::iterator it = mLiteralNodes.begin();
         std::vector< CRDFNode * >::iterator end = mLiteralNodes.end();
         for (; it != end; ++it)
           if (pNode == *it)
             {
               mLiteralNodes.erase(it);
               break;
             }
       }
       break;
     }
   // Finally delete the object
   delete pNode;
 }
std::string CRDFGraph::generatedNodeId (const std::string & existingId = "")
Generate a unique blank node id.
Parameters
const std::string & existingId (default: "")
Returns
std::string blankNodeId
Definition at line 380 of file CRDFGraph.cpp.
References mBlankNodeId2Node, mGeneratedIds, and mIdMap.
Referenced by CRDFGraphConverter::convert(), CMIRIAMInfo::createCreator(), CRDFNode::createMissingAncestors(), CMIRIAMInfo::createModification(), CMIRIAMInfo::createReference(), CMIRIAMInfo::setCreatedDT(), and CRDFNode::setFieldValue().
 {
   // If we have an existing Id we check whether we have already mapped it.
   if (existingId != "")
     {
       std::map< std::string, std::string >::const_iterator found = mIdMap.find(existingId);
       if (found != mIdMap.end())
         return found->second;
     }
   unsigned int Id = 0;
   if (mGeneratedIds.rbegin() != mGeneratedIds.rend())
     Id = *mGeneratedIds.rbegin();
   std::stringstream IdStream;
   IdStream << "CopasiId" << ++Id;
   while (mBlankNodeId2Node.count(IdStream.str()) != 0)
     {
       mGeneratedIds.insert(Id);
       IdStream.str("");
       IdStream << "CopasiId" << ++Id;
     }
   mGeneratedIds.insert(Id);
   // Remember the mapping for an existing Id
   if (existingId != "")
     mIdMap[existingId] = IdStream.str();
   return IdStream.str();
 }
const CRDFNode * CRDFGraph::getAboutNode () const
Retrieve the about/top node of the graph.
Returns
const CRDFNode * pAboutNode
Definition at line 82 of file CRDFGraph.cpp.
References mpAbout.
Referenced by CMIRIAMInfo::createBiologicalDescription(), CMIRIAMInfo::createCreator(), CMIRIAMInfo::createModification(), and CMIRIAMInfo::createReference().
 {return mpAbout;}
const std::map< std::string, CRDFNode * > & CRDFGraph::getBlankNodeMap () const
Retrieve the map of IDs to blank nodes
Returns
const std::map< std::string, CRDFNode * > & blankNodeMap
Definition at line 88 of file CRDFGraph.cpp.
References mBlankNodeId2Node.
 {return mBlankNodeId2Node;}
std::set< CRDFTriplet > CRDFGraph::getIncomingTriplets (const CRDFNode * pObject) const
Retrieve all triples pointing to the object
Parameters
const CRDFNode * pObject
Returns
std::set< CRDFTriplet > triplets
Definition at line 487 of file CRDFGraph.cpp.
References mObject2Triplet.
Referenced by removeEmptyNodes().
 {
   std::set< CRDFTriplet > Triplets;
   Node2TripletConstRange Range = mObject2Triplet.equal_range(const_cast< CRDFNode * >(pObject));
   for (; Range.first != Range.second; ++Range.first)
     Triplets.insert(Range.first->second);
   return Triplets;
 }
const std::map< std::string, CRDFNode * > & CRDFGraph::getLocalResourceNodeMap () const
Retrieve the map of URIs to local resource nodes
Returns
const std::map< std::string, CRDFNode * > & localResourceNodeMap
Definition at line 91 of file CRDFGraph.cpp.
References mLocalResource2Node.
 {return mLocalResource2Node;}
const std::map< std::string, std::string > & CRDFGraph::getNameSpaceMap () const
Retrieve the map of prefixes to namespaces
Returns
const std::map< std::string, std::string > & nameSpaceMap
Definition at line 85 of file CRDFGraph.cpp.
References mPrefix2Namespace.
Referenced by CRDFWriter::initNamespaces().
 {return mPrefix2Namespace;}
std::set< const CRDFNode * > CRDFGraph::getParentSubjects (const CRDFNode * pObject) const
Retrieve all parent subjects of the object
Parameters
const CRDFNode * pObject
Returns
std::set< const CRDFNode * > nodes
Definition at line 499 of file CRDFGraph.cpp.
References mObject2Triplet.
Referenced by CRDFNode::hasAncestor().
 {
   std::set< const CRDFNode * > Nodes;
   Node2TripletConstRange Range = mObject2Triplet.equal_range(const_cast< CRDFNode * >(pObject));
   for (; Range.first != Range.second; ++Range.first)
     Nodes.insert(Range.first->second.pSubject);
   return Nodes;
 }
CRDFPredicate::Path CRDFGraph::getPredicatePath (const CRDFNode * pNode)
Retrieve the predicate path to the ginve node.
Parameters
const CRDFNode * pNode
Returns
CRDFPredicate::Path
Definition at line 349 of file CRDFGraph.cpp.
References CRDFPredicate::about, mObject2Triplet, mpAbout, and CRDFPredicate::rdf_li.
Referenced by CRDFNode::getDescendantsWithPredicate(), CRDFNode::getPath(), and CRDFNode::isReadOnly().
 {
   CRDFPredicate::Path Path;
   CRDFNode * pCurrent = const_cast< CRDFNode * >(pNode);
   Node2TripletRange Range = mObject2Triplet.equal_range(pCurrent);
   std::set< const CRDFNode * > Visited;
   while ((Range.first != Range.second) &&
          pCurrent != mpAbout)
     {
       // We ignore rdf_li predicates
       if (Range.first->second.Predicate != CRDFPredicate::rdf_li)
         Path.insert(Path.begin(), Range.first->second.Predicate.getType());
       pCurrent = Range.first->second.pSubject;
       std::pair< std::set< const CRDFNode * >::iterator, bool > Inserted =
         Visited.insert(pCurrent);
       if (!Inserted.second)
         break;
       Range = mObject2Triplet.equal_range(pCurrent);
     }
   if (pCurrent == mpAbout)
     Path.insert(Path.begin(), CRDFPredicate::about);
   return Path;
 }
const std::vector< CRDFNode * > & CRDFGraph::getRemoteResourceNodes () const
Retrieve the vector of remote resource nodes
Returns
const std::vector< CRDFNode * > & remoteResourceNodes
Definition at line 94 of file CRDFGraph.cpp.
References mRemoteResourceNodes.
 {return mRemoteResourceNodes;}
const std::set< CRDFTriplet > & CRDFGraph::getTriplets () const
Retrieve all triplets.
Returns
const std::set< CRDFTriplet > & triplets
Definition at line 434 of file CRDFGraph.cpp.
References mTriplets.
Referenced by CRDFNode::addEdge(), CRDFGraphConverter::convert(), CQRDFTreeView::enterProtected(), CRDFNode::getDescendantsWithPredicate(), getTriplets(), CRDFNode::isBagNode(), CRDFNode::removeEdge(), and CRDFWriter::write().
 {return mTriplets;}
std::set< CRDFTriplet > CRDFGraph::getTriplets (const CRDFPredicate & predicate, const bool & expandBag = true) const
Retrieve all triplets with the specified predicate, this will collapse predicate.rdf:li to predicate.
Parameters
const CRDFPredicate & predicate
const bool & expandBag (default: true)
Returns
std::set< CRDFTriplet > triplets
Definition at line 437 of file CRDFGraph.cpp.
References getTriplets(), mPredicate2Triplet, and CRDFPredicate::rdf_li.
 {
   std::set< CRDFTriplet > Triplets;
   Predicate2TripletConstRange Range = mPredicate2Triplet.equal_range(predicate);
   for (; Range.first != Range.second; ++Range.first)
     if (expandBag &&
         Range.first->second.pObject->isBagNode())
       {
         std::set< CRDFTriplet > LiTriplets = getTriplets(Range.first->second.pObject, CRDFPredicate::rdf_li);
         std::set< CRDFTriplet >::const_iterator it = LiTriplets.begin();
         std::set< CRDFTriplet >::const_iterator end = LiTriplets.end();
         for (; it != end; ++it)
           Triplets.insert(CRDFTriplet(Range.first->second.pSubject, predicate, it->pObject));
       }
     else
       Triplets.insert(Range.first->second);
   return Triplets;
 }
std::set< CRDFTriplet > CRDFGraph::getTriplets (const CRDFNode * pSubject) const
Retrieve all triplets with the specified subject
Parameters
const CRDFNode * pSubject
Returns
std::set< CRDFTriplet > triplets
Definition at line 461 of file CRDFGraph.cpp.
References mSubject2Triplet.
 {
   std::set< CRDFTriplet > Triplets;
   Node2TripletConstRange Range = mSubject2Triplet.equal_range(const_cast< CRDFNode * >(pSubject));
   for (; Range.first != Range.second; ++Range.first)
     Triplets.insert(Range.first->second);
   return Triplets;
 }
std::set< CRDFTriplet > CRDFGraph::getTriplets (const CRDFNode * pSubject, const CRDFPredicate & predicate) const
Retrieve all triplets with the specified subject and predicate
Parameters
const CRDFNode * pSubject
const CRDFPredicate & predicate
Returns
std::set< CRDFTriplet > triplets
Definition at line 473 of file CRDFGraph.cpp.
References mPredicate2Triplet.
 {
   std::set< CRDFTriplet > Triplets;
   Predicate2TripletConstRange Range = mPredicate2Triplet.equal_range(predicate);
   for (; Range.first != Range.second; ++Range.first)
     if (Range.first->second.pSubject == pSubject)
       Triplets.insert(Range.first->second);
   return Triplets;
 }
bool CRDFGraph::guessGraphRoot (const std::string & about = " ")
Guess the graph root element. If a unique root element is found true is returned other wise falls
Parameters
const std::string & about (default: <space>)
Returns
bool success
Definition at line 97 of file CRDFGraph.cpp.
References CRDFSubject::getResource(), CRDFNode::getSubject(), CRDFSubject::getType(), CRDFSubject::isLocal(), CRDFNode::isSubjectNode(), mLocalResource2Node, mpAbout, and CRDFSubject::RESOURCE.
Referenced by createAboutNode(), and CRDFParser::parse().
 {
   mpAbout = NULL;
   CRDFNode * pNode;
   std::map< std::string, CRDFNode * >::iterator itMap = mLocalResource2Node.begin();
   std::map< std::string, CRDFNode * >::iterator endMap = mLocalResource2Node.end();
   for (; itMap != endMap; ++itMap)
     {
       pNode = itMap->second;
       if (pNode->isSubjectNode() &&
           pNode->getSubject().isLocal() &&
           pNode->getSubject().getType() == CRDFSubject::RESOURCE &&
           (about == " " ||
            pNode->getSubject().getResource() == about))
         {
           if (mpAbout != NULL)
             {
               mpAbout = NULL;
               break;
             }
           mpAbout = pNode;
         }
     }
   return mpAbout != NULL;
 }
CRDFTriplet CRDFGraph::moveTriplet (CRDFNode * pNewSubject, const CRDFTriplet & triplet)
Move a edge from one node to another
Parameters
CRDFNode * pNewSubject
CRDFNode * const CRDFTriplet & triplet
Returns
CRDFGraph::CRDFTriplet triplet
Definition at line 334 of file CRDFGraph.cpp.
References CRDFNode::addEdge(), CRDFTriplet::pObject, CRDFTriplet::Predicate, CRDFTriplet::pSubject, and CRDFNode::removeEdge().
Referenced by CRDFGraphConverter::convert().
 {
   CRDFTriplet Triplet = triplet;
   if (pNewSubject == NULL || !Triplet)
     return Triplet;
   // We first create the new triplet before we remove the old to avoid
   // destruction of the object/
   Triplet = pNewSubject->addEdge(triplet.Predicate, triplet.pObject);
   triplet.pSubject->removeEdge(triplet.Predicate, triplet.pObject);
   return Triplet;
 }
bool CRDFGraph::removeEmptyNodes () private
Removes all empty blank nodes. It returns true if a node was removed
Returns
bool haveRemoved
Definition at line 516 of file CRDFGraph.cpp.
References destroyUnreferencedNode(), getIncomingTriplets(), CRDFNode::isBagNode(), mBlankNodeId2Node, and mSubject2Triplet.
Referenced by clean().
 {
   CRDFNode * pNode;
   std::map< std::string, CRDFNode * >::iterator it = mBlankNodeId2Node.begin();
   std::map< std::string, CRDFNode * >::iterator end = mBlankNodeId2Node.end();
   std::set< CRDFNode * > ToBeRemoved;
   for (; it != end; ++it)
     {
       pNode = it->second;
       size_t Edges =
         mSubject2Triplet.count(pNode);
       if (Edges == 0 ||
           (pNode->isBagNode() && Edges == 1))
         ToBeRemoved.insert(pNode);
     }
   std::set< CRDFNode * >::iterator itRemove = ToBeRemoved.begin();
   std::set< CRDFNode * >::iterator endRemove = ToBeRemoved.end();
   for (; itRemove != endRemove; ++itRemove)
     {
       std::set< CRDFTriplet > Triplets = getIncomingTriplets(*itRemove);
       std::set< CRDFTriplet >::const_iterator itTriplet = Triplets.begin();
       std::set< CRDFTriplet >::const_iterator endTriplet = Triplets.end();
       if (itTriplet == endTriplet)
         destroyUnreferencedNode(*itRemove);
       for (; itTriplet != endTriplet; ++itTriplet)
         {
           itTriplet->pSubject->removeEdge(itTriplet->Predicate,
                                           itTriplet->pObject);
         }
     }
   return ToBeRemoved.size() > 0;
 }
void CRDFGraph::removeTriplet (CRDFNode * pSubject, const CRDFPredicate & predicate, CRDFNode * pObject)
Remove triplet from the graph. Please note, this will also remove all unreferenced local resources created by removing the edge.
Parameters
CRDFNode * pSubject
const CRDFPredicate & predicate
CRDFNode * pObject
Definition at line 277 of file CRDFGraph.cpp.
References CRDFNode::removeEdge().
Referenced by CRDFGraphConverter::convert(), CMIRIAMInfo::removeBiologicalDescription(), CMIRIAMInfo::removeCreator(), CMIRIAMInfo::removeModification(), CMIRIAMInfo::removeReference(), and CRDFNode::removeTripletFromGraph().
 {pSubject->removeEdge(predicate, pObject);}
void CRDFGraph::removeTriplet (const CRDFTriplet & triplet) private
Remove triplet from the graph. This method should only be used by CRDFNode Please note, this will also remove all unreferenced local resources created by removing the edge.
Parameters
const CRDFTriplet & triplet
Returns
bool success
Definition at line 282 of file CRDFGraph.cpp.
References destroyUnreferencedNode(), mObject2Triplet, mPredicate2Triplet, mSubject2Triplet, mTriplets, CRDFTriplet::pObject, CRDFTriplet::Predicate, and CRDFTriplet::pSubject.
 {
   if (!triplet)
     return;
   // DebugFile << "Removed: " << triplet;
   // Remove the triplet
   mTriplets.erase(triplet);
   // Remove its references
   // Subject2Triplets
   std::pair< Node2Triplet::iterator, Node2Triplet::iterator> Range = mSubject2Triplet.equal_range(triplet.pSubject);
   for (; Range.first != Range.second; ++Range.first)
     if (Range.first->second == triplet)
       {
         mSubject2Triplet.erase(Range.first);
         // We must stop or make sure that the iterator Range is still valid. Since
         // triplets are unique (we have at most one reference) we can stop.
         break;
       }
   Range = mObject2Triplet.equal_range(triplet.pObject);
   for (; Range.first != Range.second; ++Range.first)
     if (Range.first->second == triplet)
       {
         mObject2Triplet.erase(Range.first);
         // We must stop or make sure that the iterator Range is still valid. Since
         // triplets are unique (we have at most one reference) we can stop.
         break;
       }
   std::pair< Predicate2Triplet::iterator, Predicate2Triplet::iterator> RangeP = mPredicate2Triplet.equal_range(triplet.Predicate);
   for (; RangeP.first != RangeP.second; ++RangeP.first)
     if (RangeP.first->second == triplet)
       {
         mPredicate2Triplet.erase(RangeP.first);
         // We must stop or make sure that the iterator RangeP is still valid. Since
         // triplets are unique (we have at most one reference) we can stop.
         break;
       }
   destroyUnreferencedNode(triplet.pObject);
   return;
 }
void CRDFGraph::updateNamespaces ()
Removes all unused name spaces.
Definition at line 558 of file CRDFGraph.cpp.
References addNameSpace(), mPrefix2Namespace, and mTriplets.
Referenced by CMIRIAMInfo::save(), and CRDFGraphConverter::SBML2Copasi().
 {
   // We make sure that all namespaces COPASI uses are known.
   addNameSpace("CopasiMT", "http://www.copasi.org/RDF/MiriamTerms#");
   addNameSpace("dcterms", "http://purl.org/dc/terms/");
   addNameSpace("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
   addNameSpace("vCard", "http://www.w3.org/2001/vcard-rdf/3.0#");
   std::vector< bool > Used(mPrefix2Namespace.size(), false);
   std::vector< bool >::iterator itUsed;
   // We loop over all triplets
   const_iterator it = mTriplets.begin();
   const_iterator end = mTriplets.end();
   std::map< std::string, std::string >::iterator itNamespace;
   std::map< std::string, std::string >::iterator endNamespace = mPrefix2Namespace.end();
   for (; it != end; ++it)
     {
       for (itNamespace = mPrefix2Namespace.begin(), itUsed = Used.begin();
            itNamespace != endNamespace;
            ++itNamespace, ++itUsed)
         if (!*itUsed)
           {
             const std::string & Predicate = it->Predicate.getURI();
             if (Predicate.compare(0, itNamespace->second.length(), itNamespace->second) == 0)
               {
                 *itUsed = true;
                 break;
               }
           }
     }
   itNamespace = mPrefix2Namespace.begin();
   itUsed = Used.begin();
   std::vector< std::string > ToBeRemoved;
   for (itNamespace = mPrefix2Namespace.begin(), itUsed = Used.begin();
        itNamespace != endNamespace;
        ++itNamespace, ++itUsed)
     if (!*itUsed)
       ToBeRemoved.push_back(itNamespace->first);
   std::vector< std::string >::iterator itRemove = ToBeRemoved.begin();
   std::vector< std::string >::iterator endRemove = ToBeRemoved.end();
   for (; itRemove != endRemove; ++itRemove)
     mPrefix2Namespace.erase(*itRemove);
 }
Friends And Related Function Documentation
bool CRDFNode::addTripletToGraph (const CRDFTriplet & triplet) const friend
void CRDFNode::removeTripletFromGraph (const CRDFTriplet & triplet) const friend
Member Data Documentation
std::map< std::string, CRDFNode * > CRDFGraph::mBlankNodeId2Node private
A map of blank node ids to nodes of the graph.
Definition at line 268 of file CRDFGraph.h.
Referenced by addTriplet(), destroyUnreferencedNode(), generatedNodeId(), getBlankNodeMap(), removeEmptyNodes(), and ~CRDFGraph().
std::set< unsigned int > CRDFGraph::mGeneratedIds private
Memory for generated Ids
Definition at line 308 of file CRDFGraph.h.
Referenced by generatedNodeId().
std::map< std::string, std::string > CRDFGraph::mIdMap private
Mapping from existing Ids to newly created ones.
Definition at line 313 of file CRDFGraph.h.
Referenced by generatedNodeId().
std::vector< CRDFNode * > CRDFGraph::mLiteralNodes private
A vector of all literal nodes of the graph
Definition at line 283 of file CRDFGraph.h.
Referenced by destroyUnreferencedNode(), and ~CRDFGraph().
std::map< std::string, CRDFNode * > CRDFGraph::mLocalResource2Node private
A map of resource URIs to local resource nodes of the graph, i
Definition at line 273 of file CRDFGraph.h.
Referenced by addTriplet(), createAboutNode(), destroyUnreferencedNode(), getLocalResourceNodeMap(), guessGraphRoot(), and ~CRDFGraph().
Node2Triplet CRDFGraph::mObject2Triplet private
Definition at line 298 of file CRDFGraph.h.
Referenced by addTriplet(), destroyUnreferencedNode(), getIncomingTriplets(), getParentSubjects(), getPredicatePath(), removeTriplet(), and ~CRDFGraph().
CRDFNode* CRDFGraph::mpAbout private
The subject node this RDF graph is about
Definition at line 258 of file CRDFGraph.h.
Referenced by createAboutNode(), getAboutNode(), getPredicatePath(), and guessGraphRoot().
Predicate2Triplet CRDFGraph::mPredicate2Triplet private
Definition at line 303 of file CRDFGraph.h.
Referenced by addTriplet(), getTriplets(), removeTriplet(), and ~CRDFGraph().
std::map< std::string, std::string > CRDFGraph::mPrefix2Namespace private
A map of prefixes to namespaces
Definition at line 263 of file CRDFGraph.h.
Referenced by addNameSpace(), getNameSpaceMap(), and updateNamespaces().
std::vector< CRDFNode * > CRDFGraph::mRemoteResourceNodes private
A vector of all remote resource nodes of the graph
Definition at line 278 of file CRDFGraph.h.
Referenced by addTriplet(), destroyUnreferencedNode(), getRemoteResourceNodes(), and ~CRDFGraph().
Node2Triplet CRDFGraph::mSubject2Triplet private
Definition at line 293 of file CRDFGraph.h.
Referenced by addTriplet(), destroyUnreferencedNode(), getTriplets(), removeEmptyNodes(), removeTriplet(), and ~CRDFGraph().
std::set< CRDFTriplet > CRDFGraph::mTriplets private
All the triplets of the graph
Definition at line 288 of file CRDFGraph.h.
Referenced by addTriplet(), getTriplets(), removeTriplet(), updateNamespaces(), and ~CRDFGraph().
The documentation for this class was generated from the following files:
CRDFGraph.h
CRDFGraph.cpp