COPASI API: CFluxMode Class Reference
CFluxMode Class Reference
#include <CFluxMode.h>
Public Types
typedef std::map< size_t,
C_FLOAT64 >::const_iterator const_iterator
Public Member Functions
const_iterator begin () const
CFluxMode ()
CFluxMode (const CFluxMode &src)
CFluxMode (const std::map< size_t, C_FLOAT64 > &reactions, const bool &reversible)
CFluxMode (const CTableauLine *line)
const_iterator end () const
C_FLOAT64 getMultiplier (const size_t &index) const
bool isReversed (const CFluxMode &mode)
bool isReversible () const
size_t size () const
~CFluxMode ()
Private Attributes
std::map< size_t, C_FLOAT64 > mReactions
bool mReversible
Detailed Description
Definition at line 40 of file CFluxMode.h.
Member Typedef Documentation
typedef std::map< size_t, C_FLOAT64 >::const_iterator CFluxMode::const_iterator
Definition at line 43 of file CFluxMode.h.
Constructor & Destructor Documentation
CFluxMode::CFluxMode ()
Default constructor
CFluxMode class. Used to return the flux modes in human readable form
Created for Copasi by Stefan Hoops 2002-05-10 (C) Stefan Hoops 2002
Definition at line 37 of file CFluxMode.cpp.
References CONSTRUCTOR_TRACE.
 {CONSTRUCTOR_TRACE;}
CFluxMode::CFluxMode (const CFluxMode & src)
Copy constructor
Parameters
const CFluxMode & src
Definition at line 39 of file CFluxMode.cpp.
                                           :
     mReactions(src.mReactions),
     mReversible(src.mReversible)
 {}
CFluxMode::CFluxMode (const std::map< size_t, C_FLOAT64 > & reactions, const bool & reversible)
Specific constructor
Parameters
const std::map< size_t, C_FLOAT64 > & reactions
const bool & reversible
Definition at line 44 of file CFluxMode.cpp.
                                               :
     mReactions(reactions),
     mReversible(reversible)
 {}
CFluxMode::CFluxMode (const CTableauLine * line)
Specific constructor
Parameters
const CTableauLine & line
Definition at line 50 of file CFluxMode.cpp.
References CTableauLine::getFluxMode(), CTableauLine::isReversible(), mReactions, and mReversible.
 {
   const std::vector< C_FLOAT64 > & FluxMode = line->getFluxMode();
   size_t i, imax = FluxMode.size();
   std::pair< size_t, C_FLOAT64 > Entry;
   for (i = 0; i < imax; i++)
     if (FluxMode[i])
       {
         mReactions[i] = FluxMode[i];
       }
   mReversible = line->isReversible();
 }
CFluxMode::~CFluxMode ()
Destructor
Definition at line 66 of file CFluxMode.cpp.
 {}
Member Function Documentation
CFluxMode::const_iterator CFluxMode::begin () const
Retrieve the iterator to the first element of the flux mode
Returns
CFluxMode::const_iterator begin;
Definition at line 69 of file CFluxMode.cpp.
References mReactions.
Referenced by CQNewMainWindow::elementaryModeTriggeredSlot(), CEFMTask::getFluxModeDescription(), CEFMTask::getNetReactionData(), QFluxModeAnimation::getScales(), and CEFMTask::getSpeciesChanges().
 {
   return mReactions.begin();
 }
CFluxMode::const_iterator CFluxMode::end () const
Retrieve the iterator pointing beyond the last element of the flux mode
Returns
CFluxMode::const_iterator end;
Definition at line 74 of file CFluxMode.cpp.
References mReactions.
Referenced by CQNewMainWindow::elementaryModeTriggeredSlot(), CEFMTask::getFluxModeDescription(), CEFMTask::getNetReactionData(), QFluxModeAnimation::getScales(), and CEFMTask::getSpeciesChanges().
 {
   return mReactions.end();
 }
C_FLOAT64 CFluxMode::getMultiplier (const size_t & index) const
Retrieve the multiplier for the indexed reaction
Parameters
const size_t & index
Returns
C_FLOAT64 multiplier
Definition at line 111 of file CFluxMode.cpp.
References mReactions.
 {
   const_iterator it = mReactions.find(index);
   if (it != mReactions.end())
     return it->second;
   return 0.0;
 }
bool CFluxMode::isReversed (const CFluxMode & mode)
Determine whether the current mode is the reversed mode
Parameters
const CFluxMode &mode
Returns
bool isReversed
Definition at line 89 of file CFluxMode.cpp.
References mReactions, and size().
 {
   if (mode.size() != mReactions.size())
     {
       return false;
     }
   const_iterator itThis = mReactions.begin();
   const_iterator endThis = mReactions.end();
   const_iterator itMode = mode.mReactions.begin();
   for (; itThis != endThis; ++itThis, ++itMode)
     {
       if (itThis->first != itMode->first)
         {
           return false;
         }
     }
   return true;
 }
bool CFluxMode::isReversible () const
Check whether the mode is reversible
Returns
"bool" isReversible
Definition at line 79 of file CFluxMode.cpp.
References mReversible.
Referenced by CEFMTask::getNetReaction().
 {
   return mReversible;
 }
size_t CFluxMode::size () const
Retrieves the size of the mode
Returns
"size_t" size
Definition at line 84 of file CFluxMode.cpp.
References mReactions.
Referenced by isReversed().
 {
   return mReactions.size();
 }
Member Data Documentation
std::map< size_t, C_FLOAT64 > CFluxMode::mReactions private
Vector containing an index to a reaction and the multiplier for that reaction.
Definition at line 51 of file CFluxMode.h.
Referenced by begin(), CFluxMode(), end(), getMultiplier(), isReversed(), and size().
bool CFluxMode::mReversible private
Reversibility of the mode.
Definition at line 56 of file CFluxMode.h.
Referenced by CFluxMode(), and isReversible().
The documentation for this class was generated from the following files:
CFluxMode.h
CFluxMode.cpp