COPASI API: CQValidatorExpression Class Reference
CQValidatorExpression Class Reference
#include <CQExpressionWidget.h>
Public Member Functions
CQValidatorExpression (QTextEdit *parent, const char *name=0, bool isBoolean=false)
virtual CExpression * getExpression ()
void setBooleanRequired (bool booleanRequired)
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QTextEdit >
CQValidator (QTextEdit *parent, QString(QTextEdit::*retrieve)(void) const, const char *name=0)
virtual void force (const QString &input) const
virtual State revalidate ()
virtual void saved () const
Protected Attributes
CExpression mExpression
Protected Attributes inherited from CQValidator< QTextEdit >
QString mLastAccepted
QTextEdit * mpContainer
QString(QTextEdit::* mRetrieve)(void) const
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QTextEdit >
State setColor (const State &state) const
Detailed Description
The class for checking the validity of a given mathematical expression
Definition at line 55 of file CQExpressionWidget.h.
Constructor & Destructor Documentation
CQValidatorExpression::CQValidatorExpression (QTextEdit * parent, const char * name = 0, bool isBoolean = false)
Definition at line 80 of file CQExpressionWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), mExpression, CExpression::setIsBoolean(), and CCopasiObject::setObjectParent().
                                                                                                  :
   CQValidator< QTextEdit >(parent, &QTextEdit::toPlainText, name),
   mExpression()
 {
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   mExpression.setObjectParent(pDataModel);
   mExpression.setIsBoolean(isBoolean);
 }
Member Function Documentation
CExpression * CQValidatorExpression::getExpression () virtual
Function to get CExpression object
Definition at line 120 of file CQExpressionWidget.cpp.
References mExpression.
Referenced by CQExpressionWidget::writeMathML().
 {
   return &mExpression;
 }
void CQValidatorExpression::setBooleanRequired (bool booleanRequired)
Function to set whether boolean is required
Definition at line 125 of file CQExpressionWidget.cpp.
References mExpression, and CExpression::setIsBoolean().
Referenced by CQExpressionWidget::setBoolean().
 {
   mExpression.setIsBoolean(booleanRequired);
 }
QValidator::State CQValidatorExpression::validate (QString & input, int & pos) const virtual
Function to validate a string input
This function ensures that any characters on Expression Widget are validated to go to further processes.
Reimplemented from CQValidator< QTextEdit >.
Definition at line 95 of file CQExpressionWidget.cpp.
References CQExpressionWidget::getExpression(), mExpression, CQValidator< QTextEdit >::mpContainer, CQValidator< QTextEdit >::mRetrieve, CQValidator< QTextEdit >::setColor(), and CQValidator< Type >::validate().
 {
   // The input is the display version of the infix string.
   // We must first convert the display string to infix.
   CQExpressionWidget * pExpressionWidget =
     static_cast< CQExpressionWidget * >(parent());
   if (pExpressionWidget != NULL)
     {
       if (const_cast< CExpression * >(&mExpression)->setInfix(pExpressionWidget->getExpression()) &&
           const_cast< CExpression * >(&mExpression)->compile())
         {
           QString Input = (*mpContainer.*mRetrieve)();
           return CQValidator< QTextEdit >::validate(input, pos);
         }
     }
   setColor(Invalid);
   return Intermediate;
 }
Member Data Documentation
CExpression CQValidatorExpression::mExpression protected
Definition at line 76 of file CQExpressionWidget.h.
Referenced by CQValidatorExpression(), getExpression(), setBooleanRequired(), and validate().
The documentation for this class was generated from the following files:
CQExpressionWidget.h
CQExpressionWidget.cpp