COPASI API: Curve2DWidget Class Reference
Curve2DWidget Class Reference
#include <curve2dwidget.h>
Public Member Functions
Curve2DWidget (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
virtual bool LoadFromCurveSpec (const CPlotItem *curve)
virtual bool SaveToCurveSpec (CPlotItem *curve, const CPlotItem *original=NULL) const
virtual void setMultipleEditMode (bool mode)
~Curve2DWidget ()
Public Member Functions inherited from CQPlotEditWidget
CQPlotEditWidget (QWidget *parent=NULL, Qt::WindowFlags fl=0)
virtual void setModel (const CModel *model)
virtual ~CQPlotEditWidget ()
Protected Slots
virtual void buttonPressedX ()
virtual void buttonPressedY ()
virtual void typeChanged (int linetype)
Protected Attributes
const CCopasiObject * mpObjectX
const CCopasiObject * mpObjectY
Protected Attributes inherited from CQPlotEditWidget
const CModel * mpModel
Detailed Description
Definition at line 16 of file curve2dwidget.h.
Constructor & Destructor Documentation
Curve2DWidget::Curve2DWidget (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 24 of file curve2dwidget.cpp.
References CQIconResource::copasi, and CQIconResource::icon().
                                                                             :
   CQPlotEditWidget(parent, fl),
   mpObjectY(NULL),
   mpObjectX(NULL)
 {
   setupUi(this);
   mpBtnX->setIcon(CQIconResource::icon(CQIconResource::copasi));
   mpBtnY->setIcon(CQIconResource::icon(CQIconResource::copasi));
 }
Curve2DWidget::~Curve2DWidget ()
Definition at line 38 of file curve2dwidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void Curve2DWidget::buttonPressedX () protected virtual slot
Definition at line 277 of file curve2dwidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQPlotEditWidget::mpModel, mpObjectX, mpObjectY, and CQSimpleSelectionTree::NumericValues.
 {
   if (!mpModel) return;
   mpObjectX = CCopasiSelectionDialog::getObjectSingle(this,
               CQSimpleSelectionTree::NumericValues,
               mpObjectX);
   if (mpObjectX)
     {
       mpEditX->setText(FROM_UTF8(mpObjectX->getObjectDisplayName()));
       if (mpObjectY)
         mpEditTitle->setText(FROM_UTF8(mpObjectY->getObjectDisplayName()
                                        + "|"
                                        + mpObjectX->getObjectDisplayName()));
       //TODO update tab title
     }
   else
     mpEditX->setText("");
 }
void Curve2DWidget::buttonPressedY () protected virtual slot
Definition at line 300 of file curve2dwidget.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CQPlotEditWidget::mpModel, mpObjectX, mpObjectY, and CQSimpleSelectionTree::NumericValues.
 {
   if (!mpModel) return;
   mpObjectY = CCopasiSelectionDialog::getObjectSingle(this,
               CQSimpleSelectionTree::NumericValues,
               mpObjectY);
   if (mpObjectY)
     {
       mpEditY->setText(FROM_UTF8(mpObjectY->getObjectDisplayName()));
       if (mpObjectX)
         mpEditTitle->setText(FROM_UTF8(mpObjectY->getObjectDisplayName()
                                        + "|"
                                        + mpObjectX->getObjectDisplayName()));
       //TODO update tab title
     }
   else
     mpEditY->setText("");
 }
bool Curve2DWidget::LoadFromCurveSpec (const CPlotItem * curve) virtual
Implements CQPlotEditWidget.
Definition at line 43 of file curve2dwidget.cpp.
References COutputInterface::AFTER, COutputInterface::BEFORE, C_FLOAT64, C_INT32, CPlotItem::curve2d, COutputInterface::DURING, FROM_UTF8, CPlotItem::getActivity(), CPlotItem::getChannels(), CQPlotColors::getColor(), CPlotColors::getCopasiColorStr(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getDataObject(), CPlotColors::getNumCopasiColors(), CCopasiObject::getObjectDisplayName(), CPlotItem::getTitle(), CPlotItem::getType(), CCopasiParameterGroup::getValue(), mpObjectX, mpObjectY, CCopasiParameter::Value::pVOID, and typeChanged().
 {
   if (!curve)
     {
       // We need to reset the widget to defaults
       mpEditTitle->setText("");
       mpObjectX = NULL;
       mpEditX->setText("");
       mpObjectY = NULL;
       mpEditY->setText("");
       mpBoxType->setCurrentIndex(0);
       mpBoxLineSubType->setCurrentIndex(0);
       mpBoxColor->clear();
       mpCheckBefore->setChecked(false);
       mpCheckDuring->setChecked(true);
       mpCheckAfter->setChecked(false);
       return true;
     }
   if (curve->getType() != CPlotItem::curve2d) return false;
   //if (curve->getChannels().getSize != 2) return false;
   mpEditTitle->setText(FROM_UTF8(curve->getTitle()));
   //TODO: check if objects exist....
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   mpObjectX = mpObjectY = NULL;
   if (curve->getChannels().size() >= 1)
     mpObjectX = pDataModel->getDataObject(curve->getChannels()[0]);
   if (curve->getChannels().size() >= 2)
     mpObjectY = pDataModel->getDataObject(curve->getChannels()[1]);
   if (mpObjectX)
     mpEditX->setText(FROM_UTF8(mpObjectX->getObjectDisplayName()));
   if (mpObjectY)
     mpEditY->setText(FROM_UTF8(mpObjectY->getObjectDisplayName()));
   const void* tmp;
   //Type
   if (!(tmp = curve->getValue("Line type").pVOID)) return false;
   unsigned C_INT32 linetype = *(unsigned C_INT32*)tmp;
   mpBoxType->setCurrentIndex(linetype);
   typeChanged(linetype);
   //line subtype & width
   if (linetype == 0 || linetype == 3)
     {
       if (!(tmp = curve->getValue("Line subtype").pVOID)) return false;
       mpBoxLineSubType->setCurrentIndex(*(unsigned C_INT32*)tmp);
       //mpBoxWidth
       if (!(tmp = curve->getValue("Line width").pVOID)) return false;
       mpSpinBoxWidth->setValue(*(C_FLOAT64*)tmp);
     }
   // points
   if (linetype == 1)
     {
       if (!(tmp = curve->getValue("Line width").pVOID)) return false;
       mpSpinBoxWidth->setValue(*(C_FLOAT64*)tmp);
     }
   //symbol type
   if (linetype == 2 || linetype == 3)
     {
       if (!(tmp = curve->getValue("Symbol subtype").pVOID)) return false;
       mpBoxSymbolSubType->setCurrentIndex(*(unsigned C_INT32*)tmp);
     }
   //color TODO
   mpBoxColor->clear();
   mpBoxColor->addItem("auto");
   size_t i;
   for (i = 0; i < CQPlotColors::getNumCopasiColors(); ++i)
     {
       QColor color = CQPlotColors::getColor("auto", i);
       QPixmap pix(12, 12);
       QPainter painter(&pix);
       if (color.isValid())
         {
           painter.setPen(Qt::gray);
           painter.setBrush(QBrush(color));
           painter.drawRect(0, 0, 12, 12);
         }
       QIcon icon;
       icon.addPixmap(pix);
       mpBoxColor->addItem(icon, CQPlotColors::getCopasiColorStr(i).c_str());
     }
   if (!(tmp = curve->getValue("Color").pVOID)) return false;
   std::string colorstr = *(std::string*)tmp;
   int tmpindex;
   if ((tmpindex = mpBoxColor->findText(colorstr.c_str())) != -1)
     mpBoxColor->setCurrentIndex(tmpindex);
   else
     {
       QColor color = QColor(colorstr.c_str());
       QPixmap pix(12, 12);
       QPainter painter(&pix);
       if (color.isValid())
         {
           painter.setPen(Qt::gray);
           painter.setBrush(QBrush(color));
           painter.drawRect(0, 0, 12, 12);
         }
       QIcon icon;
       icon.addPixmap(pix);
       mpBoxColor->addItem(icon, colorstr.c_str());
       mpBoxColor->setCurrentIndex(mpBoxColor->count() - 1);
     }
   //channel
   mpCheckBefore->setChecked(curve->getActivity() & COutputInterface::BEFORE);
   mpCheckDuring->setChecked(curve->getActivity() & COutputInterface::DURING);
   mpCheckAfter->setChecked(curve->getActivity() & COutputInterface::AFTER);
   return true; //TODO
 }
bool Curve2DWidget::SaveToCurveSpec (CPlotItem * curve, const CPlotItem * original = NULL) const virtual
Implements CQPlotEditWidget.
Definition at line 189 of file curve2dwidget.cpp.
References COutputInterface::AFTER, COutputInterface::BEFORE, C_FLOAT64, C_INT32, CPlotItem::curve2d, COutputInterface::DURING, CPlotItem::getActivity(), CPlotItem::getChannels(), CCopasiObject::getCN(), CPlotItem::getTitle(), CPlotItem::getType(), CCopasiParameterGroup::getValue(), mpObjectX, mpObjectY, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUINT, CPlotItem::setActivity(), CPlotItem::setTitle(), CCopasiParameterGroup::setValue(), and TO_UTF8.
 {
   //if (!(mpObjectX && mpObjectY)) return false;
   //curve->setType(CPlotItem::curve2d);
   std::string title = TO_UTF8(mpEditTitle->text());
   unsigned C_INT32 lineType = (unsigned C_INT32)mpBoxType->currentIndex();
   unsigned C_INT32 lineSubType = (unsigned C_INT32)mpBoxLineSubType->currentIndex();
   unsigned C_INT32 symbolSubType = (unsigned C_INT32)mpBoxSymbolSubType->currentIndex();
   C_FLOAT64 lineWidth = (C_FLOAT64)mpSpinBoxWidth->value();
   std::string color = TO_UTF8(mpBoxColor->currentText());
   C_INT32 Activity = 0;
   if (mpCheckBefore->isChecked()) Activity += COutputInterface::BEFORE;
   if (mpCheckDuring->isChecked()) Activity += COutputInterface::DURING;
   if (mpCheckAfter->isChecked()) Activity += COutputInterface::AFTER;
   CCopasiObjectName xName = mpObjectX ? mpObjectX->getCN() : CCopasiObjectName("");
   CCopasiObjectName yName = mpObjectY ? mpObjectY->getCN() : CCopasiObjectName("");
   bool thingsChanged = false;
   if (original != NULL)
     {
       // compare whether things changed
       if (original->getTitle() != title)
         thingsChanged = true;
       if (thingsChanged || original->getType() != CPlotItem::curve2d)
         thingsChanged = true;
       if (thingsChanged || *original->getValue("Line type").pUINT != lineType)
         thingsChanged = true;
       if (thingsChanged || *original->getValue("Line subtype").pUINT != lineSubType)
         thingsChanged = true;
       if (thingsChanged || *original->getValue("Symbol subtype").pUINT != symbolSubType)
         thingsChanged = true;
       if (thingsChanged || *original->getValue("Line width").pDOUBLE != lineWidth)
         thingsChanged = true;
       if (thingsChanged || *original->getValue("Color").pSTRING != color)
         thingsChanged = true;
       if (thingsChanged || original->getActivity() != Activity)
         thingsChanged = true;
       if (thingsChanged || original->getChannels().size() != 2)
         thingsChanged = true;
       if (thingsChanged || original->getChannels()[0] != xName)
         thingsChanged = true;
       if (thingsChanged || original->getChannels()[1] != yName)
         thingsChanged = true;
     }
   else thingsChanged = true;
   if (!thingsChanged)
     return false;
   //title
   curve->setTitle(title);
   //channels
   curve->getChannels().clear();
   curve->getChannels().push_back(CPlotDataChannelSpec(xName));
   curve->getChannels().push_back(CPlotDataChannelSpec(yName));
   curve->setValue("Line type", lineType);
   curve->setValue("Line subtype", lineSubType);
   curve->setValue("Symbol subtype", symbolSubType);
   curve->setValue("Line width", lineWidth);
   //color
   curve->setValue("Color", color);
   curve->setActivity((COutputInterface::Activity) Activity);
   return true;
 }
void Curve2DWidget::setMultipleEditMode (bool mode) virtual
In multiple edit mode, we don't want to edit name & channels
Implements CQPlotEditWidget.
Definition at line 350 of file curve2dwidget.cpp.
 {
   mpEditTitle->setEnabled(!mode);
   mpEditX->setEnabled(!mode);
   mpEditY->setEnabled(!mode);
   mpBtnX->setEnabled(!mode);
   mpBtnY->setEnabled(!mode);
 }
void Curve2DWidget::typeChanged (int linetype) protected virtual slot
Definition at line 323 of file curve2dwidget.cpp.
Referenced by LoadFromCurveSpec().
 {
   if (linetype == 0 || linetype == 3 || linetype == 1)
     {
       mpBoxLineSubType->setEnabled(linetype != 1);
       mpSpinBoxWidth->setEnabled(true);
     }
   else
     {
       mpBoxLineSubType->setEnabled(linetype == 1);
       mpSpinBoxWidth->setEnabled(false);
     }
   //symbol type
   if (linetype == 2 || linetype == 3)
     {
       mpBoxSymbolSubType->setEnabled(true);
     }
   else
     {
       mpBoxSymbolSubType->setEnabled(false);
     }
 }
Member Data Documentation
const CCopasiObject* Curve2DWidget::mpObjectX protected
Definition at line 34 of file curve2dwidget.h.
Referenced by buttonPressedX(), buttonPressedY(), LoadFromCurveSpec(), and SaveToCurveSpec().
const CCopasiObject* Curve2DWidget::mpObjectY protected
Definition at line 33 of file curve2dwidget.h.
Referenced by buttonPressedX(), buttonPressedY(), LoadFromCurveSpec(), and SaveToCurveSpec().
The documentation for this class was generated from the following files:
curve2dwidget.h
curve2dwidget.cpp