COPASI API: test000061 Class Reference
test000061 Class Reference
#include <test000061.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug_1044 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug_1044)
CPPUNIT_TEST_SUITE (test000061)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
This test checks if the constant and boundaryCondition flags are set correctly when a FIXED metabolite is changed back to status REACTIONS.
Definition at line 31 of file test000061.h.
Member Function Documentation
test000061::CPPUNIT_TEST (test_bug_1044) private
test000061::CPPUNIT_TEST_SUITE (test000061) private
test000061::CPPUNIT_TEST_SUITE_END () private
void test000061::setUp ()
Definition at line 37 of file test000061.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000061::tearDown ()
Definition at line 45 of file test000061.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000061::test_bug_1044 ()
Definition at line 50 of file test000061.cpp.
References CModelEntity::ASSIGNMENT, CCopasiMessage::EXCEPTION, CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CModel::getModelValues(), CEvaluationNode::INVALID, load_cps_model_from_stream(), MCSBML, MODEL_STRING1, pCOPASIDATAMODEL, CCopasiMessage::size(), CCopasiVector< T >::size(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000061::MODEL_STRING1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   // check if the model has been loaded correctly
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getObjectName() == "A");
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::ASSIGNMENT);
   CPPUNIT_ASSERT(pModelValue->getExpressionPtr() != NULL);
   const CEvaluationNode* pRoot = pModelValue->getExpressionPtr()->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::INVALID);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   // export the model to SBML
   bool exception = false;
   try
     {
       CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 1).empty() == true);
     }
   catch (...)
     {
       exception = true;
     }
   CPPUNIT_ASSERT(exception == true);
   CPPUNIT_ASSERT(pDataModel->getCurrentSBMLDocument() == NULL);
   // check if the correct error message has been created.
   const CCopasiMessage& message = CCopasiMessage::getLastMessage();
   CPPUNIT_ASSERT(message.getNumber() == MCSBML + 70);
   CPPUNIT_ASSERT(message.getType() == CCopasiMessage::EXCEPTION);
   CPPUNIT_ASSERT(CCopasiMessage::size() == 0);
 }
Member Data Documentation
const char * test000061::MODEL_STRING1 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<!-- generated with COPASI 4.4.26 (Debug) (http://www.copasi.org) at 2008-06-09 07:46:05 UTC -->"
  "<COPASI xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"http://www.copasi.org/static/schema.xsd\" versionMajor=\"1\" versionMinor=\"0\" versionDevel=\"26\">"
  "  <Model key=\"Model_0\" name=\"Bug 1044\" timeUnit=\"s\" volumeUnit=\"ml\" quantityUnit=\"mmol\" type=\"deterministic\">"
  "    <Comment>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        "
  "      </body>"
  "    </Comment>"
  "    <ListOfModelValues>"
  "      <ModelValue key=\"ModelValue_0\" name=\"A\" simulationType=\"assignment\">"
  "      </ModelValue>"
  "    </ListOfModelValues>"
  "    <StateTemplate>"
  "      <StateTemplateVariable objectReference=\"Model_0\"/>"
  "      <StateTemplateVariable objectReference=\"ModelValue_0\"/>"
  "    </StateTemplate>"
  "    <InitialState type=\"initialState\">"
  "      0 0"
  "    </InitialState>"
  "  </Model>"
  "</COPASI>"
Definition at line 38 of file test000061.h.
Referenced by test_bug_1044().
CCopasiDataModel * test000061::pCOPASIDATAMODEL = NULL static protected
Definition at line 39 of file test000061.h.
Referenced by setUp(), and test_bug_1044().
The documentation for this class was generated from the following files:
test000061.h
test000061.cpp