COPASI API: CEvaluationNodeDepthFirstIterator Class Reference
CEvaluationNodeDepthFirstIterator Class Reference
#include <CNormalTranslation.h>
Public Member Functions
CEvaluationNodeDepthFirstIterator (CEvaluationNode *pRoot)
bool isValid () const
CEvaluationNode *& operator* ()
CEvaluationNodeDepthFirstIterator & operator++ ()
CEvaluationNode *& operator-> ()
CEvaluationNodeDepthFirstIterator & operator= (CEvaluationNode *pNode)
Protected Attributes
CEvaluationNode * mpNode
Detailed Description
Definition at line 402 of file CNormalTranslation.h.
Constructor & Destructor Documentation
CEvaluationNodeDepthFirstIterator::CEvaluationNodeDepthFirstIterator (CEvaluationNode * pRoot)
Definition at line 6352 of file CNormalTranslation.cpp.
References CCopasiNode< _Data >::getChild(), and mpNode.
                                                                                           :
     mpNode(pRoot)
 {
   while (this->mpNode && this->mpNode->getChild())
     {
       this->mpNode = static_cast<CEvaluationNode*>(this->mpNode->getChild());
     }
 }
Member Function Documentation
bool CEvaluationNodeDepthFirstIterator::isValid () const
Definition at line 6385 of file CNormalTranslation.cpp.
References mpNode.
Referenced by CNormalTranslation::has_duplicate_nodes(), CNormalTranslation::newCancel(), and CNormalTranslation::newEvaluateNumbers().
 {
   return mpNode != NULL;
 }
CEvaluationNode *& CEvaluationNodeDepthFirstIterator::operator* ()
Definition at line 6390 of file CNormalTranslation.cpp.
References mpNode.
 {
   return this->mpNode;
 }
CEvaluationNodeDepthFirstIterator & CEvaluationNodeDepthFirstIterator::operator++ ()
Definition at line 6361 of file CNormalTranslation.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getParent(), CCopasiNode< _Data >::getSibling(), and mpNode.
 {
   if (this->mpNode)
     {
       // go to the deepest child of the next sibling
       if (this->mpNode->getSibling() != NULL)
         {
           this->mpNode = static_cast<CEvaluationNode*>(this->mpNode->getSibling());
           while (this->mpNode->getChild() != NULL)
             {
               this->mpNode = static_cast<CEvaluationNode*>(this->mpNode->getChild());
             }
         }
       // go one up
       else
         {
           this->mpNode = static_cast<CEvaluationNode*>(this->mpNode->getParent());
         }
     }
   return *(this);
 }
CEvaluationNode *& CEvaluationNodeDepthFirstIterator::operator-> ()
Definition at line 6395 of file CNormalTranslation.cpp.
References mpNode.
 {
   return this->mpNode;
 }
CEvaluationNodeDepthFirstIterator & CEvaluationNodeDepthFirstIterator::operator= (CEvaluationNode * pNode)
Definition at line 6400 of file CNormalTranslation.cpp.
References mpNode.
 {
   this->mpNode = pNode;
   return *this;
 }
Member Data Documentation
CEvaluationNode* CEvaluationNodeDepthFirstIterator::mpNode protected
Definition at line 405 of file CNormalTranslation.h.
Referenced by CEvaluationNodeDepthFirstIterator(), isValid(), operator*(), operator++(), operator->(), and operator=().
The documentation for this class was generated from the following files:
CNormalTranslation.h
CNormalTranslation.cpp