COPASI API: CQTSSATimeScaleWidget Class Reference
CQTSSATimeScaleWidget Class Reference
#include <CQTSSATimeScaleWidget.h>
Public Slots
void changedInterval ()
Public Member Functions
void clearWidget ()
CQTSSATimeScaleWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
void paintTimeScale (CVector< C_FLOAT64 > vector)
~CQTSSATimeScaleWidget ()
Private Attributes
PaintWidget * mpPaintWidget
QSlider * mpSlider
QVBoxLayout * mpVLayout
Detailed Description
Definition at line 42 of file CQTSSATimeScaleWidget.h.
Constructor & Destructor Documentation
CQTSSATimeScaleWidget::CQTSSATimeScaleWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 24 of file CQTSSATimeScaleWidget.cpp.
References changedInterval(), mpPaintWidget, mpSlider, and mpVLayout.
   : QWidget(parent, fl)
 {
   setObjectName(QString::fromUtf8(name));
   if (!name)
     setObjectName("CQTSSATimeScaleWidget");
   mpVLayout = new QVBoxLayout(this);
   mpPaintWidget = new PaintWidget(this, "PaintWidget");
   mpPaintWidget->setMinimumHeight(200);
   mpSlider = new QSlider(Qt::Horizontal, this);
   mpSlider->setDisabled(true);
   mpVLayout->addWidget(mpPaintWidget);
   mpVLayout->addWidget(mpSlider);
   mpPaintWidget->setStyleSheet(QString(mpPaintWidget->metaObject()->className()) + " {background-color:" + QColor(Qt::white).name() + ";}");
   mpPaintWidget->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);
   mpSlider->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Minimum);
   mpSlider->setToolTip("move Slider to set focus on prefered time scale");  // <- helpful
   connect(mpSlider, SIGNAL(valueChanged(int)), this, SLOT(changedInterval()));
 }
CQTSSATimeScaleWidget::~CQTSSATimeScaleWidget ()
Definition at line 52 of file CQTSSATimeScaleWidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQTSSATimeScaleWidget::changedInterval () slot
Definition at line 77 of file CQTSSATimeScaleWidget.cpp.
References mpPaintWidget, mpSlider, PaintWidget::mVector, PaintWidget::paintTimeScale(), and CVectorCore< CType >::size().
Referenced by CQTSSATimeScaleWidget().
 {
   if (mpPaintWidget->mVector.size() == 0)
     return;
   mpPaintWidget->paintTimeScale(mpSlider->value());
 }
void CQTSSATimeScaleWidget::clearWidget ()
Definition at line 85 of file CQTSSATimeScaleWidget.cpp.
References PaintWidget::mClear, mpPaintWidget, and mpSlider.
 {
   mpPaintWidget->mClear = true;
   mpPaintWidget->repaint();
   mpSlider->setDisabled(true);
 }
void CQTSSATimeScaleWidget::paintTimeScale (CVector< C_FLOAT64 > vector)
Definition at line 57 of file CQTSSATimeScaleWidget.cpp.
References PaintWidget::mClear, mpPaintWidget, mpSlider, PaintWidget::mVector, PaintWidget::paintTimeScale(), and CVectorCore< CType >::size().
 {
   if (vector.size() > 0)
     {
       mpPaintWidget->mClear = false;
       mpSlider->setDisabled(false);
       if (vector.size() != mpPaintWidget->mVector.size())
         {
           mpSlider->setRange(0, (int)(vector.size() - 1));
           mpSlider->setValue(mpSlider->minimum());
         }
       mpPaintWidget->mVector = vector;
       mpPaintWidget->paintTimeScale(mpSlider->value());
       mpPaintWidget->repaint();
     }
 }
Member Data Documentation
PaintWidget* CQTSSATimeScaleWidget::mpPaintWidget private
Definition at line 58 of file CQTSSATimeScaleWidget.h.
Referenced by changedInterval(), clearWidget(), CQTSSATimeScaleWidget(), and paintTimeScale().
QSlider* CQTSSATimeScaleWidget::mpSlider private
Definition at line 59 of file CQTSSATimeScaleWidget.h.
Referenced by changedInterval(), clearWidget(), CQTSSATimeScaleWidget(), and paintTimeScale().
QVBoxLayout* CQTSSATimeScaleWidget::mpVLayout private
Definition at line 57 of file CQTSSATimeScaleWidget.h.
Referenced by CQTSSATimeScaleWidget().
The documentation for this class was generated from the following files:
CQTSSATimeScaleWidget.h
CQTSSATimeScaleWidget.cpp