COPASI API: CScanItem Class Reference
CScanItem Class Reference abstract
#include <CScanMethod.h>
Public Member Functions
size_t getNumSteps () const
const CCopasiObject * getObject () const
bool isFinished () const
virtual bool isNesting () const
virtual bool isValidScanItem (const bool &continueFromCurrentState)
void reset ()
void restoreValue () const
virtual void step ()=0
void storeValue ()
virtual ~CScanItem ()
Static Public Member Functions
static CScanItem * createScanItemFromParameterGroup (CCopasiParameterGroup *si, CRandom *rg, const bool &continueFromCurrentState)
Protected Member Functions
CScanItem (CCopasiParameterGroup *si, const bool &continueFromCurrentState)
Protected Attributes
bool mFlagFinished
size_t mIndex
bool mIsStateVariable
size_t mNumSteps
CCopasiObject * mpInitialObject
CCopasiObject * mpObject
C_FLOAT64 mStoreValue
Private Member Functions
CScanItem ()
Detailed Description
Definition at line 36 of file CScanMethod.h.
Constructor & Destructor Documentation
virtual CScanItem::~CScanItem () inline virtual
Definition at line 72 of file CScanMethod.h.
 {};
CScanItem::CScanItem (CCopasiParameterGroup * si, const bool & continueFromCurrentState) protected
Definition at line 83 of file CScanMethod.cpp.
References CModel::getCorrespondingTransientObject(), CCopasiDataModel::getDataObject(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDataModel(), CCopasiParameterGroup::getValue(), CModel::isStateVariable(), CCopasiObject::isValueDbl(), mIsStateVariable, mNumSteps, mpInitialObject, mpObject, CCopasiParameter::Value::pCN, and CCopasiParameter::Value::pUINT.
                                                            :
   mNumSteps(0),
   mpObject(NULL),
   mpInitialObject(NULL),
   mStoreValue(0.0),
   mIndex(0),
   mFlagFinished(false),
   mIsStateVariable(false)
 {
   assert(si != NULL);
   mNumSteps = * si->getValue("Number of steps").pUINT;
   std::string tmpString = * si->getValue("Object").pCN;
   CCopasiDataModel* pDataModel = si->getObjectDataModel();
   assert(pDataModel != NULL);
   CCopasiObject * tmpObject = pDataModel->getDataObject(tmpString);
   if (tmpObject == NULL || !tmpObject->isValueDbl())
     {
       return;
     }
   mpInitialObject = tmpObject;
   if (continueFromCurrentState)
     {
       // Determine whether the object is the initial value of a state variable;
       const CModel * pModel = static_cast< CModel * >(mpInitialObject->getObjectAncestor("Model"));
       if (pModel != NULL)
         {
           mIsStateVariable = pModel->isStateVariable(tmpObject);
           if (!mIsStateVariable)
             {
               // We need to find the object for the transient value if it exists so that we can update while continuing.
               mpObject = pModel->getCorrespondingTransientObject(tmpObject);
             }
         }
     }
   else
     {
       mpObject = mpInitialObject;
     }
 }
CScanItem::CScanItem () private
Definition at line 73 of file CScanMethod.cpp.
                     :
   mNumSteps(0),
   mpObject(NULL),
   mpInitialObject(NULL),
   mStoreValue(0.0),
   mIndex(0),
   mFlagFinished(false),
   mIsStateVariable(false)
 {}
Member Function Documentation
CScanItem * CScanItem::createScanItemFromParameterGroup (CCopasiParameterGroup * si, CRandom * rg, const bool & continueFromCurrentState) static
CScanMethod class. This class describes the Scan method
Created for COPASI by Rohan Luktuke 2002
Definition at line 48 of file CScanMethod.cpp.
References CCopasiParameterGroup::getValue(), CCopasiParameter::Value::pUINT, CScanProblem::SCAN_LINEAR, CScanProblem::SCAN_RANDOM, and CScanProblem::SCAN_REPEAT.
Referenced by CScanMethod::init(), and CScanMethod::isValidProblem().
 {
   if (!si) return NULL;
   CScanProblem::Type type = *(CScanProblem::Type*)(si->getValue("Type").pUINT);
   CScanItem* tmp = NULL;
   if (type == CScanProblem::SCAN_REPEAT)
     tmp = new CScanItemRepeat(si, continueFromCurrentState);
   if (type == CScanProblem::SCAN_LINEAR)
     tmp = new CScanItemLinear(si, continueFromCurrentState);
   if (type == CScanProblem::SCAN_RANDOM)
     tmp = new CScanItemRandom(si, rg, continueFromCurrentState);
   /*  if (type == CScanProblem::SCAN_BREAK)
       tmp = new CScanItemBreak(si, st);*/
   return tmp;
 }
size_t CScanItem::getNumSteps () const
Definition at line 131 of file CScanMethod.cpp.
References mNumSteps.
Referenced by CScanMethod::init().
 {return mNumSteps;};
const CCopasiObject * CScanItem::getObject () const
Retrieve the initial object which is scanned.
Returns
const CCopasiObject * object
Definition at line 176 of file CScanMethod.cpp.
References mpObject.
Referenced by CScanMethod::init().
 {
   return mpObject;
 }
bool CScanItem::isFinished () const
Definition at line 155 of file CScanMethod.cpp.
References mFlagFinished.
Referenced by CScanMethod::loop().
 {return mFlagFinished;};
virtual bool CScanItem::isNesting () const inline virtual
Reimplemented in CScanItemRandom.
Definition at line 70 of file CScanMethod.h.
Referenced by CScanMethod::loop().
 {return true;};
bool CScanItem::isValidScanItem (const bool & continueFromCurrentState) virtual
perform checks. This is used in the method::isValidProblem() method. It returns false for an invalid ScanItem and generates a CCopasiMessage
Parameters
const bool & continueFromCurrentState
Reimplemented in CScanItemLinear, and CScanItemRepeat.
Definition at line 157 of file CScanMethod.cpp.
References CCopasiMessage::ERROR, CCopasiObject::getObjectDisplayName(), MCScan, mIsStateVariable, mpInitialObject, mpObject, and CCopasiMessage::WARNING.
Referenced by CScanMethod::isValidProblem(), and CScanItemLinear::isValidScanItem().
 {
   if (continueFromCurrentState &&
       mIsStateVariable &&
       mpObject == NULL)
     {
       CCopasiMessage(CCopasiMessage::WARNING, MCScan + 1, mpInitialObject->getObjectDisplayName().c_str());
       return true;
     }
   if (mpInitialObject == NULL)
     {
       CCopasiMessage(CCopasiMessage::ERROR, "Invalid or missing scan parameter.");
       return false;
     }
   return true;
 }
void CScanItem::reset ()
Definition at line 148 of file CScanMethod.cpp.
References mFlagFinished, mIndex, and step().
Referenced by CScanMethod::loop().
 {
   mIndex = 0;
   mFlagFinished = false;
   this->step(); //purely virtual
 }
void CScanItem::restoreValue () const
Definition at line 133 of file CScanMethod.cpp.
References mpObject, mStoreValue, and CCopasiObject::setObjectValue().
 {
   if (mpObject)
     mpObject->setObjectValue(mStoreValue);
 };
virtual void CScanItem::step () pure virtual
Implemented in CScanItemRandom, CScanItemLinear, and CScanItemRepeat.
Referenced by CScanMethod::loop(), and reset().
void CScanItem::storeValue ()
Definition at line 139 of file CScanMethod.cpp.
References C_FLOAT64, CCopasiObject::getValuePointer(), CCopasiObject::isValueDbl(), mpObject, and mStoreValue.
 {
   if (mpObject)
     {
       assert(mpObject->isValueDbl());
       mStoreValue = * (C_FLOAT64 *) mpObject->getValuePointer();
     }
 };
Member Data Documentation
bool CScanItem::mFlagFinished protected
Definition at line 48 of file CScanMethod.h.
Referenced by isFinished(), reset(), CScanItemRepeat::step(), CScanItemLinear::step(), and CScanItemRandom::step().
size_t CScanItem::mIndex protected
Definition at line 46 of file CScanMethod.h.
Referenced by reset(), CScanItemRepeat::step(), CScanItemLinear::step(), and CScanItemRandom::step().
bool CScanItem::mIsStateVariable protected
Definition at line 50 of file CScanMethod.h.
Referenced by CScanItem(), and isValidScanItem().
size_t CScanItem::mNumSteps protected
Definition at line 39 of file CScanMethod.h.
Referenced by CScanItem(), CScanItemLinear::CScanItemLinear(), CScanItemRandom::CScanItemRandom(), CScanItemRepeat::CScanItemRepeat(), getNumSteps(), CScanItemRepeat::step(), CScanItemLinear::step(), and CScanItemRandom::step().
CCopasiObject* CScanItem::mpInitialObject protected
Definition at line 42 of file CScanMethod.h.
Referenced by CScanItem(), isValidScanItem(), CScanItemLinear::step(), and CScanItemRandom::step().
CCopasiObject* CScanItem::mpObject protected
Definition at line 41 of file CScanMethod.h.
Referenced by CScanItem(), getObject(), isValidScanItem(), restoreValue(), CScanItemLinear::step(), CScanItemRandom::step(), and storeValue().
C_FLOAT64 CScanItem::mStoreValue protected
Definition at line 44 of file CScanMethod.h.
Referenced by restoreValue(), and storeValue().
The documentation for this class was generated from the following files:
CScanMethod.h
CScanMethod.cpp