COPASI API: COptItem Class Reference
COptItem Class Reference
#include <COptItem.h>
Public Member Functions
virtual C_INT32 checkConstraint () const
C_INT32 checkConstraint (const C_FLOAT64 &value) const
bool checkLowerBound (const C_FLOAT64 &value) const
bool checkUpperBound (const C_FLOAT64 &value) const
virtual bool compile (const std::vector< CCopasiContainer * > listOfContainer=CCopasiContainer::EmptyList)
COptItem (const CCopasiContainer *pParent, const std::string &name="OptimizationItem")
COptItem (const COptItem &src, const CCopasiContainer *pParent=NULL)
COptItem (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
virtual C_FLOAT64 getConstraintViolation () const
const C_FLOAT64 & getLastStartValue () const
const std::string getLowerBound () const
const C_FLOAT64 * getLowerBoundValue () const
const CCopasiObject * getObject () const
const CCopasiObjectName getObjectCN () const
std::string getObjectDisplayName () const
virtual const C_FLOAT64 * getObjectValue () const
C_FLOAT64 getRandomValue (CRandom *pRandom=NULL)
const C_FLOAT64 & getStartValue () const
virtual UpdateMethod * getUpdateMethod () const
const std::string getUpperBound () const
const C_FLOAT64 * getUpperBoundValue () const
virtual bool isValid () const
void rememberStartValue ()
bool setLowerBound (const CCopasiObjectName &lowerBound)
bool setObjectCN (const CCopasiObjectName &objectCN)
bool setStartValue (const C_FLOAT64 &value)
bool setUpperBound (const CCopasiObjectName &upperBound)
virtual ~COptItem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static bool isValid (CCopasiParameterGroup &group)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Member Functions
COptItem ()
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
C_FLOAT64 mLastStartValue
C_FLOAT64 mLowerBound
const C_FLOAT64 * mpLowerBound
const CCopasiObject * mpLowerObject
UpdateMethod * mpMethod
const CCopasiObject * mpObject
const C_FLOAT64 * mpObjectValue
std::string * mpParmLowerBound
std::string * mpParmObjectCN
C_FLOAT64 * mpParmStartValue
std::string * mpParmUpperBound
const C_FLOAT64 * mpUpperBound
const CCopasiObject * mpUpperObject
C_FLOAT64 mUpperBound
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes
static CRandom * mpRandom = NULL
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Private Member Functions
bool compileLowerBound (const std::vector< CCopasiContainer * > &listOfContainer)
bool compileUpperBound (const std::vector< CCopasiContainer * > &listOfContainer)
void initializeParameter ()
Friends
std::ostream & operator<< (std::ostream &os, const COptItem &o)
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Detailed Description
Definition at line 29 of file COptItem.h.
Constructor & Destructor Documentation
COptItem::COptItem () protected
Default constructor
COptItem::COptItem (const CCopasiContainer * pParent, const std::string & name = "OptimizationItem")
Specific constructor
Parameters
const CCopasiContainer * pParent
const std::string & name (default: OptimizationItem)
Definition at line 39 of file COptItem.cpp.
References initializeParameter().
                                           :
   CCopasiParameterGroup(name, pParent),
   mpParmObjectCN(NULL),
   mpParmLowerBound(NULL),
   mpParmUpperBound(NULL),
   mpParmStartValue(NULL),
   mpObject(NULL),
   mpMethod(NULL),
   mpObjectValue(NULL),
   mpLowerObject(NULL),
   mpLowerBound(NULL),
   mLowerBound(0.0),
   mpUpperObject(NULL),
   mpUpperBound(NULL),
   mUpperBound(0.0),
   mLastStartValue(std::numeric_limits< C_FLOAT64 >::quiet_NaN())
 {initializeParameter();}
COptItem::COptItem (const COptItem & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const COptItem & src
const CCopasiContainer * pParent (default: src data model)
Definition at line 58 of file COptItem.cpp.
References initializeParameter().
                                                     :
   CCopasiParameterGroup(src, (pParent != NULL) ? pParent : src.getObjectDataModel()),
   mpParmObjectCN(NULL),
   mpParmLowerBound(NULL),
   mpParmUpperBound(NULL),
   mpParmStartValue(NULL),
   mpObject(NULL),
   mpMethod(NULL),
   mpObjectValue(NULL),
   mpLowerObject(NULL),
   mpLowerBound(NULL),
   mLowerBound(0.0),
   mpUpperObject(NULL),
   mpUpperBound(NULL),
   mUpperBound(0.0),
   mLastStartValue(src.mLastStartValue)
 {initializeParameter();}
COptItem::COptItem (const CCopasiParameterGroup & group, const CCopasiContainer * pParent = NULL)
Specific constructor used for reading COPASI files
Parameters
const CCopasiParameterGroup & group
const CCopasiContainer * pParent (default: group data model)
Definition at line 77 of file COptItem.cpp.
References initializeParameter().
                                                     :
   CCopasiParameterGroup(group, (pParent != NULL) ? pParent : group.getObjectDataModel()),
   mpParmObjectCN(NULL),
   mpParmLowerBound(NULL),
   mpParmUpperBound(NULL),
   mpParmStartValue(NULL),
   mpObject(NULL),
   mpMethod(NULL),
   mpObjectValue(NULL),
   mpLowerObject(NULL),
   mpLowerBound(NULL),
   mLowerBound(0.0),
   mpUpperObject(NULL),
   mpUpperBound(NULL),
   mUpperBound(0.0),
   mLastStartValue(std::numeric_limits< C_FLOAT64 >::quiet_NaN())
 {initializeParameter();}
COptItem::~COptItem () virtual
Destructor
Definition at line 96 of file COptItem.cpp.
 {}
Member Function Documentation
C_INT32 COptItem::checkConstraint () const virtual
This functions check whether the current value is within the limits of the optimization item.
Returns
C_INT32 result (-1: to small, 0: within boundaries, 1 to large)
Reimplemented in CFitConstraint, and CFitItem.
Definition at line 401 of file COptItem.cpp.
References mpLowerBound, mpObjectValue, and mpUpperBound.
Referenced by COptMethodHookeJeeves::bestNearby(), COptMethodSS::combination(), COptMethodPS::create(), COptMethodDE::creation(), COptMethodEP::creation(), COptMethodSRES::creation(), COptMethodGA::creation(), COptMethodSS::creation(), getConstraintViolation(), COptMethodPS::move(), COptMethodEP::mutate(), COptMethodGA::mutate(), COptMethodSRES::mutate(), COptMethodDE::optimise(), COptMethodGA::optimise(), COptMethodPS::optimise(), COptMethodHookeJeeves::optimise(), COptMethodCoranaWalk::optimise(), COptMethodSA::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodNelderMead::optimise(), COptMethodPraxis::optimise(), COptMethodTruncatedNewton::optimise(), COptMethodStatistics::optimise(), COptMethodSteepestDescent::optimise(), CRandomSearch::optimise(), COptMethodSS::randomize(), and COptMethodDE::replicate().
 {
   if (*mpLowerBound > *mpObjectValue) return - 1;
   if (*mpObjectValue > *mpUpperBound) return 1;
   return 0;
 }
C_INT32 COptItem::checkConstraint (const C_FLOAT64 & value) const
This functions check whether the value is within the limits of the optimization item.
Parameters
const C_FLOAT64 & value
Returns
C_INT32 result (-1: to small, 0: within boundaries, 1 to large)
Definition at line 426 of file COptItem.cpp.
References mpLowerBound, and mpUpperBound.
 {
   if (*mpLowerBound > value) return - 1;
   if (value > *mpUpperBound) return 1;
   return 0;
 }
bool COptItem::checkLowerBound (const C_FLOAT64 & value) const
Checks whether the value fulfills the lower bound constraint.
Parameters
const C_FLOAT64 & value
Returns
bool fulfills
Definition at line 435 of file COptItem.cpp.
References mpLowerBound.
Referenced by COptMethodEP::creation(), COptMethodSRES::creation(), and CRandomSearch::optimise().
 {return *mpLowerBound <= value;}
bool COptItem::checkUpperBound (const C_FLOAT64 & value) const
Checks whether the value fulfills the upper bound constraint.
Parameters
const C_FLOAT64 & value
Returns
bool fulfills
Definition at line 438 of file COptItem.cpp.
References mpUpperBound.
Referenced by COptMethodEP::creation(), COptMethodSRES::creation(), and CRandomSearch::optimise().
 {return value <= *mpUpperBound;}
bool COptItem::compile (const std::vector< CCopasiContainer * > listOfContainer = CCopasiContainer::EmptyList) virtual
Compile the optimization item. This function must be called before any of the check functions are called.
Parameters
const std::vector< CCopasiContainer * > listOfContainer
Returns
bool success
Reimplemented in CFitItem.
Definition at line 336 of file COptItem.cpp.
References CCopasiObject::addDirectDependency(), C_FLOAT64, CCopasiObject::clearDirectDependencies(), compileLowerBound(), compileUpperBound(), DoNothing, CCopasiMessage::ERROR, getObjectCN(), CCopasiObject::getObjectDataModel(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getUpdateMethod(), CCopasiObject::getValuePointer(), CCopasiObject::isValueDbl(), MCOptimization, mpLowerBound, mpLowerObject, mpMethod, mpObject, mpObjectValue, mpParmLowerBound, mpParmStartValue, mpParmUpperBound, mpUpperBound, mpUpperObject, and NaN.
Referenced by CFitItem::compile(), getObjectDisplayName(), and getRandomValue().
 {
   bool success = true;
   clearDirectDependencies();
   std::string Bound;
   mpMethod = &DoNothing;
   mpObjectValue = &NaN;
   if ((mpObject =
          getObjectDataModel()->ObjectFromName(listOfContainer,
              getObjectCN())) != NULL &&
       mpObject->isValueDbl())
     mpObjectValue = (C_FLOAT64 *) mpObject->getValuePointer();
   if (mpObjectValue == &NaN)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 1, getObjectCN().c_str());
       success = false;
     }
   else
     {
       addDirectDependency(mpObject);
       mpMethod = mpObject->getUpdateMethod();
     }
   if (compileLowerBound(listOfContainer))
     {
       if (mpLowerObject != NULL)
         {
           addDirectDependency(mpLowerObject);
         }
     }
   else
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 2, mpParmLowerBound->c_str());
       success = false;
     }
   if (compileUpperBound(listOfContainer))
     {
       if (mpUpperObject != NULL)
         {
           addDirectDependency(mpUpperObject);
         }
     }
   else
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 2, mpParmUpperBound->c_str());
       success = false;
     }
   if (!mpUpperObject && !mpLowerObject && *mpUpperBound < *mpLowerBound)
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 4, *mpLowerBound, *mpUpperBound, mpObject->getObjectDisplayName().c_str());
       success = false;
     }
   if (isnan(*mpParmStartValue))
     *mpParmStartValue = *mpObjectValue;
   return success;
 }
bool COptItem::compileLowerBound (const std::vector< CCopasiContainer * > & listOfContainer) private
Compile the lower bound to hold the value given by the bound
Parameters
const std::vector< CCopasiContainer * > & listOfContainer
Returns
bool success
Definition at line 444 of file COptItem.cpp.
References C_FLOAT64, CCopasiObject::getObjectDataModel(), CCopasiObject::getValuePointer(), isNumber(), CCopasiObject::isValueDbl(), max, mLowerBound, mpLowerBound, mpLowerObject, mpParmLowerBound, and strToDouble().
Referenced by compile(), and setLowerBound().
 {
   const CCopasiDataModel * pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   mpLowerObject = NULL;
   mpLowerBound = NULL;
   if (*mpParmLowerBound == "-inf")
     {
       mLowerBound = - std::numeric_limits< C_FLOAT64 >::max();
       mpLowerBound = &mLowerBound;
     }
   else if (isNumber(*mpParmLowerBound))
     {
       mLowerBound = strToDouble(mpParmLowerBound->c_str(), NULL);
       mpLowerBound = &mLowerBound;
     }
   else if ((mpLowerObject =
               getObjectDataModel()->ObjectFromName(listOfContainer,
                   *mpParmLowerBound)) != NULL &&
            mpLowerObject->isValueDbl())
     {
       mpLowerBound = (C_FLOAT64 *) mpLowerObject->getValuePointer();
     }
   return mpLowerBound != NULL;
 }
bool COptItem::compileUpperBound (const std::vector< CCopasiContainer * > & listOfContainer) private
Compile the upper bound to hold the value given by the bound
Parameters
const std::vector< CCopasiContainer * > & listOfContainer
Returns
bool success
Definition at line 474 of file COptItem.cpp.
References CCopasiObject::addDirectDependency(), C_FLOAT64, CCopasiObject::getObjectDataModel(), CCopasiObject::getValuePointer(), isNumber(), CCopasiObject::isValueDbl(), max, mpParmUpperBound, mpUpperBound, mpUpperObject, mUpperBound, and strToDouble().
Referenced by compile(), and setUpperBound().
 {
   const CCopasiDataModel * pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   mpUpperObject = NULL;
   mpUpperBound = NULL;
   if (*mpParmUpperBound == "inf")
     {
       mUpperBound = std::numeric_limits< C_FLOAT64 >::max();
       mpUpperBound = &mUpperBound;
     }
   else if (isNumber(*mpParmUpperBound))
     {
       mUpperBound = strToDouble(mpParmUpperBound->c_str(), NULL);
       mpUpperBound = &mUpperBound;
     }
   else if ((mpUpperObject =
               getObjectDataModel()->ObjectFromName(listOfContainer,
                   *mpParmUpperBound)) != NULL &&
            mpUpperObject->isValueDbl())
     {
       mpUpperBound = (C_FLOAT64 *) mpUpperObject->getValuePointer();
       addDirectDependency(mpUpperObject);
     }
   return mpUpperBound != NULL;
 }
C_FLOAT64 COptItem::getConstraintViolation () const virtual
Retrieve the magnitude of the constraint violation This is always a positive number
Returns
C_FLOAT64 constraintViolation;
Reimplemented in CFitConstraint, and CFitItem.
Definition at line 410 of file COptItem.cpp.
References checkConstraint(), mpLowerBound, mpObjectValue, and mpUpperBound.
 {
   switch (checkConstraint())
     {
       case - 1:
         return *mpLowerBound - *mpObjectValue;
         break;
       case 1:
         return *mpObjectValue - *mpUpperBound;
         break;
     }
   return 0.0;
 }
const C_FLOAT64 & COptItem::getLastStartValue () const
Retrieve the start value use in the last optimization.
Returns
const C_FLOAT64 & startValue
Definition at line 220 of file COptItem.cpp.
References mLastStartValue.
Referenced by CQFittingResult::enterProtected().
 {
   return mLastStartValue;
 }
const std::string COptItem::getLowerBound () const
Retrieve the lower bound.
Returns
const std::string lowerBound
Definition at line 164 of file COptItem.cpp.
References mpParmLowerBound.
Referenced by CQFittingResult::enterProtected(), isValid(), CQFittingItemWidget::loadSelection(), operator<<(), CQFittingItemWidget::setTableText(), and CFitItem::updateBounds().
 {return *mpParmLowerBound;}
const C_FLOAT64* COptItem::getLowerBoundValue () const inline
Retrieve the value of the lower bound.
Returns
const C_FLOAT64 * lowerBoundValue
Definition at line 191 of file COptItem.h.
References mpLowerBound.
Referenced by COptMethodHookeJeeves::bestNearby(), COptMethodSS::combination(), COptMethodPS::create(), COptMethodDE::creation(), COptMethodEP::creation(), COptMethodSRES::creation(), COptMethodGA::creation(), COptMethodGASR::creation(), COptMethodSS::creation(), CQFittingResult::enterProtected(), COptMethodSRES::initialize(), COptMethodPS::move(), COptMethodEP::mutate(), COptMethodGA::mutate(), COptMethodSRES::mutate(), COptMethodDE::optimise(), COptMethodGA::optimise(), COptMethodPS::optimise(), COptMethodHookeJeeves::optimise(), COptMethodNelderMead::optimise(), COptMethodCoranaWalk::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodSA::optimise(), COptMethodPraxis::optimise(), COptMethodTruncatedNewton::optimise(), COptMethodStatistics::optimise(), COptMethodSteepestDescent::optimise(), CRandomSearch::optimise(), COptMethodSS::randomize(), and COptMethodDE::replicate().
   {return mpLowerBound;}
const CCopasiObject * COptItem::getObject () const
Retrieve the item object. This may only be called after compile
Returns
const CCopasiObject *
Definition at line 128 of file COptItem.cpp.
References mpObject.
Referenced by CFitProblem::initialize().
 {return mpObject;}
const CCopasiObjectName COptItem::getObjectCN () const
Retrieve the object of the optimization item.
Returns
const CCopasiObjectName objectCN
Definition at line 131 of file COptItem.cpp.
References mpParmObjectCN.
Referenced by compile(), getStartValue(), isValid(), CQFittingItemWidget::load(), CQFittingItemWidget::loadSelection(), and CQFittingItemWidget::setTableText().
 {return *mpParmObjectCN;}
std::string COptItem::getObjectDisplayName () const
Retrieve the display name of the optimization item.
Returns
std::string displayName
Definition at line 134 of file COptItem.cpp.
References compile(), CCopasiObject::getObjectDisplayName(), and mpObject.
Referenced by CFitProblem::initialize().
 {
   if (!mpObject && !const_cast<COptItem *>(this)->compile())
     return "Invalid Optimization Item";
   return mpObject->getObjectDisplayName();
 }
const C_FLOAT64 * COptItem::getObjectValue () const virtual
Retrieve the value of the optimization object.
Returns
const C_FLOAT64 * objectValue
Reimplemented in CFitItem.
Definition at line 441 of file COptItem.cpp.
References mpObjectValue.
 {return mpObjectValue;}
C_FLOAT64 COptItem::getRandomValue (CRandom * pRandom = NULL)
Retrieve a random value in the interval (lower bound, upper bound). Optionally one may provide a random number generator to be used to create the random value.
Parameters
CRandom * pRandom (default: NULL)
Returns
C_FLOAT64 randomValue
Definition at line 230 of file COptItem.cpp.
References C_FLOAT64, compile(), CRandom::createGenerator(), CRandom::getRandomCC(), CRandom::getRandomNormal(), max, min, mpLowerBound, mpRandom, mpUpperBound, and NaN.
Referenced by CRandomSearch::optimise().
 {
   C_FLOAT64 RandomValue;
   if (mpLowerBound == NULL ||
       mpUpperBound == NULL) compile();
   if (mpLowerBound == NULL ||
       mpUpperBound == NULL)
     {
       RandomValue = NaN;
       return RandomValue;
     }
   if (pRandom == NULL)
     {
       if (mpRandom == NULL)
         mpRandom = CRandom::createGenerator();
       pRandom = mpRandom;
     }
   C_FLOAT64 mn = *mpLowerBound;
   C_FLOAT64 mx = *mpUpperBound;
   C_FLOAT64 la;
   try
     {
       // First determine the location of the interval
       // Secondly determine whether to distribute the parameter linearly or not
       // depending on the location and act upon it.
       if (0.0 <= mn) // the interval [mn, mx) is in [0, inf)
         {
           la = log10(mx) - log10(std::max(mn, std::numeric_limits< C_FLOAT64 >::min()));
           if (la < 1.8 || !(mn > 0.0)) // linear
             RandomValue = mn + pRandom->getRandomCC() * (mx - mn);
           else
             RandomValue = pow(10.0, log10(std::max(mn, std::numeric_limits< C_FLOAT64 >::min())) + la * pRandom->getRandomCC());
         }
       else if (mx > 0) // 0 is in the interval (mn, mx)
         {
           la = log10(mx) + log10(-mn);
           if (la < 3.6) // linear
             RandomValue = mn + pRandom->getRandomCC() * (mx - mn);
           else
             {
               C_FLOAT64 mean = (mx + mn) * 0.5;
               C_FLOAT64 sigma = std::min(std::numeric_limits< C_FLOAT64 >::max(), mx - mn) / 3.0;
               do
                 {
                   RandomValue = pRandom->getRandomNormal(mean, sigma);
                 }
               while ((RandomValue < mn) || (RandomValue > mx));
             }
         }
       else // the interval (mn, mx] is in (-inf, 0]
         {
           // Switch lower and upper bound and change sign, i.e.,
           // we can treat it similarly as location 1:
           mx = - *mpLowerBound;
           mn = - *mpUpperBound;
           la = log10(mx) - log10(std::max(mn, std::numeric_limits< C_FLOAT64 >::min()));
           if (la < 1.8 || !(mn > 0.0)) // linear
             RandomValue = - (mn + pRandom->getRandomCC() * (mx - mn));
           else
             RandomValue = - pow(10.0, log10(std::max(mn, std::numeric_limits< C_FLOAT64 >::min())) + la * pRandom->getRandomCC());
         }
     }
   catch (...)
     {
       RandomValue = (mx + mn) * 0.5;
     }
   return RandomValue;
 }
const C_FLOAT64 & COptItem::getStartValue () const
Retrieve the start value of the optimization object.
Returns
const C_FLOAT64 & startValue
Definition at line 199 of file COptItem.cpp.
References C_FLOAT64, CCopasiDataModel::getDataObject(), getObjectCN(), CCopasiObject::getObjectDataModel(), CCopasiObject::getValuePointer(), mpObjectValue, mpParmStartValue, and NaN.
Referenced by COptMethodEP::creation(), COptMethodSRES::creation(), COptMethodSS::creation(), CQFittingItemWidget::loadSelection(), operator<<(), COptMethodDE::optimise(), COptMethodGA::optimise(), COptMethodPS::optimise(), COptMethodHookeJeeves::optimise(), COptMethodCoranaWalk::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodNelderMead::optimise(), COptMethodSA::optimise(), COptMethodPraxis::optimise(), COptMethodTruncatedNewton::optimise(), COptMethodStatistics::optimise(), COptMethodSteepestDescent::optimise(), CRandomSearch::optimise(), rememberStartValue(), setLowerBound(), CQFittingItemWidget::setTableText(), and setUpperBound().
 {
   if (!isnan(*mpParmStartValue))
     return *mpParmStartValue;
   if (mpObjectValue == NULL)
     {
       const CCopasiDataModel* pDataModel = getObjectDataModel();
       assert(pDataModel != NULL);
       const CCopasiObject * pObject = pDataModel->getDataObject(getObjectCN());
       if (pObject != NULL &&
           pObject->getValuePointer() != NULL)
         return *(C_FLOAT64 *) pObject->getValuePointer();
       return NaN;
     }
   return *mpObjectValue;
 }
UpdateMethod * COptItem::getUpdateMethod () const virtual
Retrieve the update method
Returns
UpdateMethod * pUpdateMethod
Reimplemented in CFitItem.
Definition at line 313 of file COptItem.cpp.
References mpMethod.
 {return mpMethod;}
const std::string COptItem::getUpperBound () const
Retrieve the upper bound.
Returns
const std::string upperBound
Definition at line 189 of file COptItem.cpp.
References mpParmUpperBound.
Referenced by CQFittingResult::enterProtected(), isValid(), CQFittingItemWidget::loadSelection(), operator<<(), CQFittingItemWidget::setTableText(), and CFitItem::updateBounds().
 {return *mpParmUpperBound;}
const C_FLOAT64* COptItem::getUpperBoundValue () const inline
Retrieve the value of the upper bound.
Returns
const C_FLOAT64 * upperBoundValue
Definition at line 198 of file COptItem.h.
References mpUpperBound.
Referenced by COptMethodHookeJeeves::bestNearby(), COptMethodSS::combination(), COptMethodPS::create(), COptMethodDE::creation(), COptMethodEP::creation(), COptMethodSRES::creation(), COptMethodGA::creation(), COptMethodGASR::creation(), COptMethodSS::creation(), CQFittingResult::enterProtected(), COptMethodSRES::initialize(), COptMethodPS::move(), COptMethodEP::mutate(), COptMethodGA::mutate(), COptMethodSRES::mutate(), COptMethodDE::optimise(), COptMethodGA::optimise(), COptMethodPS::optimise(), COptMethodHookeJeeves::optimise(), COptMethodNelderMead::optimise(), COptMethodCoranaWalk::optimise(), COptMethodLevenbergMarquardt::optimise(), COptMethodSA::optimise(), COptMethodPraxis::optimise(), COptMethodTruncatedNewton::optimise(), COptMethodStatistics::optimise(), COptMethodSteepestDescent::optimise(), CRandomSearch::optimise(), COptMethodSS::randomize(), and COptMethodDE::replicate().
   {return mpUpperBound;}
void COptItem::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 99 of file COptItem.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::CN, CCopasiParameter::DOUBLE, CCopasiParameter::getValue(), mpParmLowerBound, mpParmObjectCN, mpParmStartValue, mpParmUpperBound, NaN, CCopasiParameter::Value::pCN, and CCopasiParameter::Value::pDOUBLE.
Referenced by COptItem().
 {
   mpParmObjectCN =
     assertParameter("ObjectCN", CCopasiParameter::CN, CCopasiObjectName(""))->getValue().pCN;
   mpParmLowerBound =
     assertParameter("LowerBound", CCopasiParameter::CN, CCopasiObjectName("1e-06"))->getValue().pCN;
   mpParmUpperBound =
     assertParameter("UpperBound", CCopasiParameter::CN, CCopasiObjectName("1e+06"))->getValue().pCN;
   mpParmStartValue =
     assertParameter("StartValue", CCopasiParameter::DOUBLE, NaN)->getValue().pDOUBLE;
 }
bool COptItem::isValid () const virtual
Check the validity of the optimization item.
Reimplemented in CFitItem.
Definition at line 316 of file COptItem.cpp.
References getLowerBound(), getObjectCN(), getUpperBound(), setLowerBound(), setObjectCN(), and setUpperBound().
Referenced by CFitItem::isValid(), and isValid().
 {
   COptItem *pTmp = const_cast<COptItem *>(this);
   if (!pTmp->setObjectCN(getObjectCN())) return false;
   if (!pTmp->setLowerBound(getLowerBound())) return false;
   if (!pTmp->setUpperBound(getUpperBound())) return false;
   return true;
 }
bool COptItem::isValid (CCopasiParameterGroup & group) static
Check whether the group describes a valid optimization item.
Returns
bool isValid
Definition at line 329 of file COptItem.cpp.
References isValid().
 {
   COptItem tmp(group);
   return tmp.isValid();
 }
void COptItem::rememberStartValue ()
Remember the current start value
Definition at line 225 of file COptItem.cpp.
References getStartValue(), and mLastStartValue.
 {
   mLastStartValue = getStartValue();
 }
bool COptItem::setLowerBound (const CCopasiObjectName & lowerBound)
Set the lower bound.
Parameters
const CCopasiObjectName & lowerBound
Returns
bool success
Definition at line 142 of file COptItem.cpp.
References C_FLOAT64, compileLowerBound(), CCopasiContainer::EmptyList, getStartValue(), isNumber(), mpParmLowerBound, and strToDouble().
Referenced by isValid(), and CQFittingItemWidget::saveSelection().
 {
   if (lowerBound[0] == '-' &&
       lowerBound[lowerBound.length() - 1] == '%' &&
       isNumber(lowerBound.substr(1, lowerBound.length() - 2)))
     {
       std::stringstream LowerBound;
       C_FLOAT64 StartValue = getStartValue();
       LowerBound << StartValue + fabs(StartValue) * strToDouble(lowerBound.c_str(), NULL) / 100.0;
       *mpParmLowerBound = LowerBound.str();
       return true;
     }
   else
     {
       *mpParmLowerBound = lowerBound;
     }
   return compileLowerBound(CCopasiContainer::EmptyList);
 }
bool COptItem::setObjectCN (const CCopasiObjectName & objectCN)
Set the object of the optimization item.
Parameters
const CCopasiObjectName & objectCN
Returns
bool success
Definition at line 111 of file COptItem.cpp.
References CCopasiMessage::ERROR, CCopasiDataModel::getDataObject(), CCopasiObject::getObjectDataModel(), CCopasiObject::isValueDbl(), MCOptimization, and mpParmObjectCN.
Referenced by COptProblem::addOptItem(), isValid(), and CQFittingItemWidget::slotParamEdit().
 {
   const CCopasiDataModel * pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   const CCopasiObject * pObject = pDataModel->getDataObject(objectCN);
   if (pObject == NULL || !pObject->isValueDbl())
     {
       CCopasiMessage(CCopasiMessage::ERROR, MCOptimization + 1, objectCN.c_str());
       return false;
     }
   *mpParmObjectCN = objectCN;
   return true;
 }
bool COptItem::setStartValue (const C_FLOAT64 & value)
Set the value start value.
Parameters
const C_FLOAT64 & startValue
Returns
bool success
Definition at line 192 of file COptItem.cpp.
References mpParmStartValue.
Referenced by CFitItem::elevateChildren(), and CQFittingItemWidget::saveSelection().
 {
   *mpParmStartValue = value;
   return true;
 }
bool COptItem::setUpperBound (const CCopasiObjectName & upperBound)
Set the upper bound.
Parameters
const CCopasiObjectName & upperBound
Returns
bool success
Definition at line 167 of file COptItem.cpp.
References C_FLOAT64, compileUpperBound(), CCopasiContainer::EmptyList, getStartValue(), isNumber(), mpParmUpperBound, and strToDouble().
Referenced by isValid(), and CQFittingItemWidget::saveSelection().
 {
   if (upperBound[0] == '+' &&
       upperBound[upperBound.length() - 1] == '%' &&
       isNumber(upperBound.substr(1, upperBound.length() - 2)))
     {
       std::stringstream UpperBound;
       C_FLOAT64 StartValue = getStartValue();
       UpperBound << StartValue + fabs(StartValue) * strToDouble(upperBound.c_str(), NULL) / 100.0;
       *mpParmUpperBound = UpperBound.str();
       return true;
     }
   else
     {
       *mpParmUpperBound = upperBound;
     }
   return compileUpperBound(CCopasiContainer::EmptyList);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const COptItem & o) friend
Output stream operator
Parameters
ostream & os
const COptItem & A
Returns
ostream & os
Definition at line 505 of file COptItem.cpp.
 {
   if (o.mpObject == NULL && !const_cast<COptItem *>(&o)->compile())
     return os << "Invalid Optimization Item";
   if (o.mpLowerObject)
     os << o.mpLowerObject->getObjectDisplayName();
   else
     os << o.getLowerBound();
   os << " <= ";
   os << o.mpObject->getObjectDisplayName();
   os << " <= ";
   if (o.mpUpperObject)
     os << o.mpUpperObject->getObjectDisplayName();
   else
     os << o.getUpperBound();
   os << "; Start Value = " << o.getStartValue();
   return os;
 }
Member Data Documentation
C_FLOAT64 COptItem::mLastStartValue protected
The start value use for last calculation
Definition at line 333 of file COptItem.h.
Referenced by getLastStartValue(), and rememberStartValue().
C_FLOAT64 COptItem::mLowerBound protected
The value of the lower bound (only if not on object)
Definition at line 313 of file COptItem.h.
Referenced by compileLowerBound().
const C_FLOAT64* COptItem::mpLowerBound protected
A pointer to the lower bound value
Definition at line 308 of file COptItem.h.
Referenced by CFitConstraint::calculateConstraintViolation(), CFitItem::checkConstraint(), checkConstraint(), checkLowerBound(), compile(), compileLowerBound(), CFitItem::getConstraintViolation(), getConstraintViolation(), getLowerBoundValue(), getRandomValue(), and CFitItem::updateBounds().
const CCopasiObject* COptItem::mpLowerObject protected
A pointer to the object for the lower bound
Definition at line 303 of file COptItem.h.
Referenced by compile(), compileLowerBound(), operator<<(), and CFitItem::updateBounds().
UpdateMethod* COptItem::mpMethod protected
A pointer to the object update method
Definition at line 293 of file COptItem.h.
Referenced by compile(), and getUpdateMethod().
const CCopasiObject* COptItem::mpObject protected
A pointer to the object
Definition at line 288 of file COptItem.h.
Referenced by compile(), getObject(), getObjectDisplayName(), and operator<<().
const C_FLOAT64* COptItem::mpObjectValue protected
A pointer to the object value
Definition at line 298 of file COptItem.h.
Referenced by CFitConstraint::calculateConstraintViolation(), checkConstraint(), compile(), getConstraintViolation(), getObjectValue(), and getStartValue().
std::string* COptItem::mpParmLowerBound protected
A pointer to the value of the CCopasiParameter holding the LowerBound
Definition at line 273 of file COptItem.h.
Referenced by compile(), compileLowerBound(), getLowerBound(), initializeParameter(), and setLowerBound().
std::string* COptItem::mpParmObjectCN protected
A pointer to the value of the CCopasiParameter holding the ObjectCN
Definition at line 268 of file COptItem.h.
Referenced by getObjectCN(), initializeParameter(), and setObjectCN().
C_FLOAT64* COptItem::mpParmStartValue protected
A pointer to the value of the CCopasiParameter holding the start value
Definition at line 283 of file COptItem.h.
Referenced by CFitItem::compile(), compile(), getStartValue(), initializeParameter(), and setStartValue().
std::string* COptItem::mpParmUpperBound protected
A pointer to the value of the CCopasiParameter holding the UpperBound
Definition at line 278 of file COptItem.h.
Referenced by compile(), compileUpperBound(), getUpperBound(), initializeParameter(), and setUpperBound().
CRandom * COptItem::mpRandom = NULL static protected
A pointer to the random number generator used in randomizeStartValue
Definition at line 338 of file COptItem.h.
Referenced by getRandomValue().
const C_FLOAT64* COptItem::mpUpperBound protected
A pointer to the upper bound value
Definition at line 323 of file COptItem.h.
Referenced by CFitConstraint::calculateConstraintViolation(), CFitItem::checkConstraint(), checkConstraint(), checkUpperBound(), compile(), compileUpperBound(), CFitItem::getConstraintViolation(), getConstraintViolation(), getRandomValue(), getUpperBoundValue(), and CFitItem::updateBounds().
const CCopasiObject* COptItem::mpUpperObject protected
A pointer to the object for the upper bound
Definition at line 318 of file COptItem.h.
Referenced by compile(), compileUpperBound(), operator<<(), and CFitItem::updateBounds().
C_FLOAT64 COptItem::mUpperBound protected
The value of the upper bound (only if not on object)
Definition at line 328 of file COptItem.h.
Referenced by compileUpperBound().
The documentation for this class was generated from the following files:
COptItem.h
COptItem.cpp