COPASI API: CLCompartmentGlyph Class Reference
CLCompartmentGlyph Class Reference
#include <CLGlyphs.h>
Public Member Functions
CLCompartmentGlyph (const std::string &name="CompartmentGlyph", const CCopasiContainer *pParent=NULL)
CLCompartmentGlyph (const CLCompartmentGlyph &src, const CCopasiContainer *pParent=NULL)
CLCompartmentGlyph (const CompartmentGlyph &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual CLGraphicalObject * clone () const
virtual void exportToSBML (CompartmentGlyph *cg, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
CLCompartmentGlyph & operator= (const CLCompartmentGlyph &rhs)
void print (std::ostream *ostream) const
Public Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const std::string &name="GraphicalObject", const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const CLGraphicalObject &src, const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
const CLBoundingBox & getBoundingBox () const
CLBoundingBox & getBoundingBox ()
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CCopasiObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
virtual void moveBy (const CLPoint &p)
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void print (std::ostream *ostream) const
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Friends
std::ostream & operator<< (std::ostream &os, const CLCompartmentGlyph &g)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CLGraphicalObject
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Graphical representation of a compartment
Definition at line 74 of file CLGlyphs.h.
Constructor & Destructor Documentation
CLCompartmentGlyph::CLCompartmentGlyph (const std::string & name = "CompartmentGlyph", const CCopasiContainer * pParent = NULL)
Definition at line 108 of file CLGlyphs.cpp.
Referenced by clone().
     : CLGraphicalObject(name, pParent)
 {}
CLCompartmentGlyph::CLCompartmentGlyph (const CLCompartmentGlyph & src, const CCopasiContainer * pParent = NULL)
Definition at line 113 of file CLGlyphs.cpp.
     : CLGraphicalObject(src, pParent)
 {}
CLCompartmentGlyph::CLCompartmentGlyph (const CompartmentGlyph & sbml, const std::map< std::string, std::string > & modelmap, std::map< std::string, std::string > & layoutmap, const CCopasiContainer * pParent = NULL)
constructor from libsbml object
Definition at line 118 of file CLGlyphs.cpp.
References CLGraphicalObject::setModelObjectKey().
     : CLGraphicalObject(sbml, layoutmap, pParent)
 {
   //get the copasi key corresponding to the sbml id for the compartment
   if (sbml.getCompartmentId() != "")
     {
       std::map<std::string, std::string>::const_iterator it = modelmap.find(sbml.getCompartmentId());
       if (it != modelmap.end())
         setModelObjectKey(it->second);
     }
 }
Member Function Documentation
virtual CLGraphicalObject* CLCompartmentGlyph::clone () const inline virtual
Reimplemented from CLGraphicalObject.
Definition at line 104 of file CLGlyphs.h.
References CLCompartmentGlyph().
 {return new CLCompartmentGlyph(*this, NULL);};
void CLCompartmentGlyph::exportToSBML (CompartmentGlyph * cg, const std::map< const CCopasiObject *, SBase * > & copasimodelmap, std::map< std::string, const SBase * > & sbmlIDs) const virtual
This method writes the information of the copasi layout object into the corresponding sbml object
Definition at line 145 of file CLGlyphs.cpp.
References CLGraphicalObject::exportToSBML(), and CLGraphicalObject::getModelObject().
Referenced by CLayout::exportToSBML(), and CLGeneralGlyph::exportToSBML().
 {
   if (!cg) return;
   //call the coresponding method of the base class
   CLGraphicalObject::exportToSBML(cg, copasimodelmap, sbmlIDs);
   //reference to model objects
   CCopasiObject* tmp = getModelObject();
   if (tmp)
     {
       std::map<const CCopasiObject*, SBase*>::const_iterator it = copasimodelmap.find(tmp);
       if (it != copasimodelmap.end())
         {
           if (it->second)
             cg->setCompartmentId(it->second->getId());
         }
     }
 }
CLCompartmentGlyph & CLCompartmentGlyph::operator= (const CLCompartmentGlyph & rhs)
assignment operator
Definition at line 134 of file CLGlyphs.cpp.
References CLGraphicalObject::operator=().
 {
   if (this == &rhs) return * this; //do nothing if lhs and rhs are the same
   CLGraphicalObject::operator=(rhs);
   //nothing to be done here
   return *this;
 }
void CLCompartmentGlyph::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 175 of file CLGlyphs.cpp.
 {*ostream << *this;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLCompartmentGlyph & g) friend
insert operator
Definition at line 169 of file CLGlyphs.cpp.
 {
   os << "CompartmentGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   return os;
 }
The documentation for this class was generated from the following files:
CLGlyphs.h
CLGlyphs.cpp