COPASI API: CQReportDefinitionSelect Class Reference
CQReportDefinitionSelect Class Reference
#include <CQReportDefinitionSelect.h>
Public Slots
int exec ()
Public Member Functions
void cleanup ()
CQReportDefinitionSelect (QWidget *parent=0, Qt::WindowFlags f=0)
void loadReportDefinitionVector ()
void setReport (CReport *newReport)
virtual ~CQReportDefinitionSelect ()
Protected Slots
void accept ()
void reject ()
void slotBrowse ()
void slotEdit ()
Private Attributes
ListViews * mpListView
CReport * mpReport
bool mShow
Detailed Description
Definition at line 24 of file CQReportDefinitionSelect.h.
Constructor & Destructor Documentation
CQReportDefinitionSelect::CQReportDefinitionSelect (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 22 of file CQReportDefinitionSelect.cpp.
References CQIconResource::edit, CQIconResource::fileOpen, and CQIconResource::icon().
                                                                                     :
     QDialog(parent, f),
     mpListView(static_cast< ListViews * >(parent)),
     mpReport(NULL),
     mShow(true)
 {
   setupUi(this);
   mpBtnEdit->setIcon(CQIconResource::icon(CQIconResource::edit));
   mpBtnBrowse->setIcon(CQIconResource::icon(CQIconResource::fileOpen));
 }
CQReportDefinitionSelect::~CQReportDefinitionSelect () virtual
Definition at line 35 of file CQReportDefinitionSelect.cpp.
References cleanup().
 {
   cleanup();
 }
Member Function Documentation
void CQReportDefinitionSelect::accept () protected slot
Definition at line 115 of file CQReportDefinitionSelect.cpp.
References C_INT32, cleanup(), CCopasiRootContainer::getDatamodelList(), mpReport, CReport::setAppend(), CReport::setConfirmOverwrite(), CReport::setReportDefinition(), CReport::setTarget(), and TO_UTF8.
Referenced by slotEdit().
 {
   if (!mpReport)
     //exception made here
     return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CReportDefinitionVector* pReportDefinitionVector = (*CCopasiRootContainer::getDatamodelList())[0]->getReportDefinitionList();
   C_INT32 row;
   row = mpComboDefinition->currentIndex();
   mpReport->setReportDefinition((*(pReportDefinitionVector))[row]);
   mpReport->setAppend(mpCheckAppend->isChecked());
   mpReport->setConfirmOverwrite(mpCheckConfirmOverwrite->isChecked());
   mpReport->setTarget(TO_UTF8(mpEditTarget->text()));
   cleanup();
   QDialog::done(QDialog::Accepted);
 }
void CQReportDefinitionSelect::cleanup ()
Definition at line 40 of file CQReportDefinitionSelect.cpp.
References mpReport.
Referenced by accept(), reject(), and ~CQReportDefinitionSelect().
 {
   mpReport = NULL;
 }
int CQReportDefinitionSelect::exec () slot
Definition at line 107 of file CQReportDefinitionSelect.cpp.
References mShow.
Referenced by TaskWidget::reportBtnClicked().
 {
   if (mShow)
     return QDialog::exec();
   else
     return QDialog::Accepted;
 }
void CQReportDefinitionSelect::loadReportDefinitionVector ()
Definition at line 50 of file CQReportDefinitionSelect.cpp.
References CReport::append(), C_INT32, ListViews::CHANGE, CReport::confirmOverwrite(), FROM_UTF8, ListViews::getDataModel(), CCopasiRootContainer::getDatamodelList(), CCopasiObject::getObjectName(), CReport::getReportDefinition(), CReport::getTarget(), mpListView, mpReport, DataModelGUI::notify(), CQMessageBox::question(), ListViews::REPORT, CReport::setAppend(), CReport::setConfirmOverwrite(), CReport::setReportDefinition(), CReport::setTarget(), CCopasiVector< T >::size(), slotEdit(), and TO_UTF8.
Referenced by TaskWidget::reportBtnClicked().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CReportDefinitionVector* pReportDefinitionVector = (*CCopasiRootContainer::getDatamodelList())[0]->getReportDefinitionList();
   unsigned C_INT32 i;
   for (i = 0; i < pReportDefinitionVector->size(); i++)
     mpComboDefinition->
     insertItem(mpComboDefinition->count(), FROM_UTF8((*(pReportDefinitionVector))[i]->getObjectName()));
   // if it is an empty list
   if (mpComboDefinition->count() == 0)
     {
       std::string name = "ReportDefinition_0";
       (*CCopasiRootContainer::getDatamodelList())[0]->getReportDefinitionList()->createReportDefinition(name, "");
       mpComboDefinition->insertItem(mpComboDefinition->count(), FROM_UTF8(name));
       mpComboDefinition->setCurrentIndex(1);
       mpReport->setReportDefinition((*(*CCopasiRootContainer::getDatamodelList())[0]->getReportDefinitionList())[0]); //first one report definition
       mpReport->setAppend(mpCheckAppend->isChecked());
       mpReport->setConfirmOverwrite(mpCheckConfirmOverwrite->isChecked());
       mpReport->setTarget(TO_UTF8(mpEditTarget->text()));
       mpListView->getDataModel()->notify(ListViews::REPORT, ListViews::CHANGE, ""); //notify Table Definition to
       if (CQMessageBox::question(NULL, "No Report Template Defined",
                                  "No report definition defined, COPASI has already created a new one for you.\n Do you want to switch to the GUI to edit it?",
                                  QMessageBox::Ok | QMessageBox::No, QMessageBox::Ok) == QMessageBox::Ok)
         slotEdit();
       return;
     }
   if (!mpReport->getReportDefinition())
     {
       C_INT32 row;
       row = mpComboDefinition->currentIndex();
       mpReport->setReportDefinition((*(pReportDefinitionVector))[row]);
       mpReport->setAppend(mpCheckAppend->isChecked());
       mpReport->setConfirmOverwrite(mpCheckConfirmOverwrite->isChecked());
       mpReport->setTarget(TO_UTF8(mpEditTarget->text()));
       return;
     }
   else
     {
       C_INT32 i;
       // no use to compare the last one
       for (i = mpComboDefinition->count() - 1; i >= 1; i--)
         if (mpComboDefinition->itemText(i) == FROM_UTF8(mpReport->getReportDefinition()->getObjectName()))
           break;
       mpComboDefinition->setCurrentIndex(i);
       mpCheckAppend->setChecked(mpReport->append());
       mpCheckConfirmOverwrite->setChecked(mpReport->confirmOverwrite());
       mpEditTarget->setText(FROM_UTF8(mpReport->getTarget()));
     }
 }
void CQReportDefinitionSelect::reject () protected slot
Definition at line 133 of file CQReportDefinitionSelect.cpp.
References cleanup().
 {
   cleanup();
   QDialog::done(QDialog::Rejected);
 }
void CQReportDefinitionSelect::setReport (CReport * newReport)
Definition at line 45 of file CQReportDefinitionSelect.cpp.
References mpReport.
Referenced by TaskWidget::reportBtnClicked().
 {
   mpReport = newReport;
 }
void CQReportDefinitionSelect::slotBrowse () protected slot
Definition at line 150 of file CQReportDefinitionSelect.cpp.
References CopasiFileDialog::getSaveFileName().
 {
   QString reportFile =
     CopasiFileDialog::getSaveFileName(this, "Save File Dialog", "untitled.txt", "TEXT Files (*.txt)",
                                       "Choose to create a new a file");
   if (!reportFile.isNull())
     {
       mpEditTarget->setText(reportFile);
     }
 }
void CQReportDefinitionSelect::slotEdit () protected slot
Definition at line 139 of file CQReportDefinitionSelect.cpp.
References accept(), C_INT32, C_INVALID_INDEX, CCopasiRootContainer::getDatamodelList(), mpListView, mShow, and ListViews::switchToOtherWidget().
Referenced by loadReportDefinitionVector().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CReportDefinitionVector* pReportDefinitionVector = (*CCopasiRootContainer::getDatamodelList())[0]->getReportDefinitionList();
   C_INT32 row;
   row = mpComboDefinition->currentIndex();
   mpListView->switchToOtherWidget(C_INVALID_INDEX, (*pReportDefinitionVector)[row]->getKey());
   accept(); // if shown then close
   mShow = false; // if not shown then close
 }
Member Data Documentation
ListViews* CQReportDefinitionSelect::mpListView private
Definition at line 49 of file CQReportDefinitionSelect.h.
Referenced by loadReportDefinitionVector(), and slotEdit().
CReport* CQReportDefinitionSelect::mpReport private
Definition at line 50 of file CQReportDefinitionSelect.h.
Referenced by accept(), cleanup(), loadReportDefinitionVector(), and setReport().
bool CQReportDefinitionSelect::mShow private
Definition at line 51 of file CQReportDefinitionSelect.h.
Referenced by exec(), and slotEdit().
The documentation for this class was generated from the following files:
CQReportDefinitionSelect.h
CQReportDefinitionSelect.cpp