COPASI API: CQDifferentialEquations Class Reference
CQDifferentialEquations Class Reference
#include <CQDifferentialEquations.h>
Public Slots
virtual void slotSave ()
virtual void slotUpdateWidget ()
Public Member Functions
CQDifferentialEquations (QWidget *parent=0, const char *name=0)
~CQDifferentialEquations ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
Protected Member Functions
virtual bool enterProtected ()
Protected Attributes
std::ostringstream mml
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Private Member Functions
void init ()
virtual void newFunction ()
virtual void saveMML (const QString filename)
virtual void savePNG (const QString filename)
virtual void saveTeX (const QString filename)
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 29 of file CQDifferentialEquations.h.
Constructor & Destructor Documentation
CQDifferentialEquations::CQDifferentialEquations (QWidget * parent = 0, const char * name = 0)
Definition at line 51 of file CQDifferentialEquations.cpp.
References init().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
 #ifdef WIN32
   // on windows there ought to be a border around the MML widget
   // otherwise it is difficult to distinguish the formula from the rest of the
   // dialog
   mpScrollView->setFrameShape(QFrame::Panel);
   mpScrollView->setFrameStyle(QFrame::Panel | QFrame::Plain);
 #endif
   init();
 }
CQDifferentialEquations::~CQDifferentialEquations ()
Definition at line 70 of file CQDifferentialEquations.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
bool CQDifferentialEquations::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 144 of file CQDifferentialEquations.cpp.
References slotUpdateWidget().
 {
   slotUpdateWidget();
   return true;
 }
void CQDifferentialEquations::init () private
Definition at line 75 of file CQDifferentialEquations.cpp.
Referenced by CQDifferentialEquations().
 {
   comboBoxFunctions->setCurrentIndex(1);
 }
void CQDifferentialEquations::newFunction () private virtual
Definition at line 150 of file CQDifferentialEquations.cpp.
 {}
void CQDifferentialEquations::saveMML (const QString filename) private virtual
Definition at line 80 of file CQDifferentialEquations.cpp.
References CLocaleString::fromUtf8(), mml, and TO_UTF8.
Referenced by slotSave().
 {
   std::ofstream ofile;
   ofile.open(CLocaleString::fromUtf8(TO_UTF8(outfilename)).c_str(), std::ios::trunc);
   ofile << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << std::endl;
   ofile << "<!DOCTYPE math PUBLIC \"-//W3C//DTD MathML 2.0//EN\" \"http://www.w3.org/Math/DTD/mathml2/mathml2.dtd\">" << std::endl;
   ofile << "<math xmlns=\"http://www.w3.org/1998/Math/MathML\">" << std::endl;
   ofile << mml.str();
   ofile << "</math>" << std::endl;
   ofile.close();
 }
void CQDifferentialEquations::savePNG (const QString filename) private virtual
Definition at line 169 of file CQDifferentialEquations.cpp.
References FROM_UTF8, and mml.
Referenced by slotSave().
 {
   QtMmlDocument doc;
   doc.setBaseFontPointSize(20);
   doc.setFontName(QtMmlWidget::NormalFont, qApp->font().family());
   doc.setContent(FROM_UTF8(mml.str()));
   const QSize &size = doc.size();
   QPixmap pixmap(size.width(), size.height());
   QPainter painter(&pixmap);
   painter.setRenderHint(QPainter::Antialiasing);
   painter.setRenderHint(QPainter::SmoothPixmapTransform);
   painter.setRenderHint(QPainter::HighQualityAntialiasing);
   painter.fillRect(0, 0, size.width(), size.height(), Qt::white);
   doc.paint(&painter, QPoint(0, 0));
   pixmap.save(outfilename, "PNG");
 }
void CQDifferentialEquations::saveTeX (const QString filename) private virtual
Definition at line 153 of file CQDifferentialEquations.cpp.
References CMathMLToTeX::convert(), FROM_UTF8, CLocaleString::fromUtf8(), mml, and TO_UTF8.
Referenced by slotSave().
 {
   QString latexStr(FROM_UTF8(mml.str()));
 #ifdef DEBUG_UI
   qDebug() << latexStr;
 #endif
   CMathMLToTeX::convert(latexStr);
   std::ofstream ofile;
   ofile.open(CLocaleString::fromUtf8(TO_UTF8(outfilename)).c_str(), std::ios::trunc);
   ofile << TO_UTF8(latexStr);
   ofile.close();
 }
void CQDifferentialEquations::slotSave () virtual slot
Definition at line 187 of file CQDifferentialEquations.cpp.
References C_INT32, checkSelection(), CopasiFileDialog::getSaveFileName(), saveMML(), savePNG(), and saveTeX().
 {
   QString outfilename;
   C_INT32 Answer = QMessageBox::No;
   while (Answer == QMessageBox::No)
     {
       outfilename =
         CopasiFileDialog::getSaveFileName(this,
                                           "Save File Dialog",
                                           "untitled.mml",
                                           "MathML (*.mml);;TeX (*.tex);;PNG (*.png)",
                                           "Save Formula to Disk", new QString);
       if (outfilename.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(outfilename);
       if (Answer == QMessageBox::Cancel)
         return;
     }
 #ifdef DEBUG_UI
   qDebug() << "outfilename = " << outfilename;
 #endif
   QApplication::setOverrideCursor(Qt::WaitCursor);
   if (outfilename.contains(".tex"))
     {
       saveTeX(outfilename);
     }
   else if (outfilename.contains(".png"))
     {
       savePNG(outfilename);
     }
   else
     {
       saveMML(outfilename);
     }
   QApplication::restoreOverrideCursor();
 }
void CQDifferentialEquations::slotUpdateWidget () virtual slot
Definition at line 96 of file CQDifferentialEquations.cpp.
References FROM_UTF8, CCopasiRootContainer::getDatamodelList(), mml, and CMMLOutput::writeDifferentialEquations().
Referenced by enterProtected().
 {
   bool hasContents = true;
   //std::ostringstream mml;
   mml.str("");
   bool expand, expandAll;
   switch (comboBoxFunctions->currentIndex())
     {
       case 0:
         expand = false;
         expandAll = false;
         break;
       case 1:
         expand = true;
         expandAll = false;
         break;
       default:
         expand = true;
         expandAll = true;
         break;
     };
   bool parameterAsNumbers = false;
   if (comboBoxParameters->currentIndex() == 0)
     parameterAsNumbers = true;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CMMLOutput::writeDifferentialEquations(mml, (*CCopasiRootContainer::getDatamodelList())[0]->getModel(), parameterAsNumbers, expand, expandAll);
   QWidget* tmp = dynamic_cast<QWidget*>(parent());
   if (tmp) tmp->setCursor(Qt::WaitCursor);
   mpMMLWidget->setContent(FROM_UTF8(mml.str()));
   mpMMLWidget->setBaseFontPointSize(qApp->font().pointSize());
   mpMMLWidget->setFontName(QtMmlWidget::NormalFont, qApp->font().family());
   mpMMLWidget->setFixedSize(mpMMLWidget->sizeHint().expandedTo(QSize(0, 0)));
   if (tmp) tmp->unsetCursor();
   mpSaveButton->setEnabled(hasContents);
 }
Member Data Documentation
std::ostringstream CQDifferentialEquations::mml protected
Definition at line 42 of file CQDifferentialEquations.h.
Referenced by saveMML(), savePNG(), saveTeX(), and slotUpdateWidget().
The documentation for this class was generated from the following files:
CQDifferentialEquations.h
CQDifferentialEquations.cpp