COPASI API: CMassAction Class Reference
CMassAction Class Reference
#include <CMassAction.h>
Public Member Functions
virtual const C_FLOAT64 & calcValue (const CCallParameters< C_FLOAT64 > &callParameters)
CMassAction (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CMassAction (const CFunction &src, const CCopasiContainer *pParent=NULL)
CMassAction (const TriLogic &reversible, const CCopasiContainer *pParent=NULL)
virtual bool compile ()
virtual bool dependsOn (const C_FLOAT64 *parameter, const CCallParameters< C_FLOAT64 > &callParameters) const
virtual bool setInfix (const std::string &infix)
virtual std::string writeMathML (const std::vector< std::vector< std::string > > &variables, bool expand=true, bool fullExpand=true) const
~CMassAction ()
Public Member Functions inherited from CFunction
bool addVariable (const std::string &name, CFunctionParameter::Role usage=CFunctionParameter::VARIABLE, const CFunctionParameter::DataType &type=CFunctionParameter::FLOAT64)
CFunction (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=Function)
CFunction (const CFunction &src, const CCopasiContainer *pParent=NULL)
CFunction * createCopy () const
void createListOfParametersForMathML (std::vector< std::vector< std::string > > &env)
const std::string & getKey () const
const std::string & getSBMLId () const
virtual size_t getVariableIndex (const std::string &name) const
CFunctionParameters & getVariables ()
const CFunctionParameters & getVariables () const
virtual const C_FLOAT64 & getVariableValue (const size_t &index) const
const TriLogic & isReversible () const
bool isSuitable (const size_t noSubstrates, const size_t noProducts, const TriLogic reversible)
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
bool operator== (const CFunction &rhs) const
virtual bool setInfix (const std::string &infix, bool compile)
void setReversible (const TriLogic &reversible)
void setSBMLId (const std::string &id)
std::pair< CFunction
*, CFunction * > splitFunction (const CEvaluationNode *node, const std::string &name1, const std::string &name2) const
virtual void writeMathML (std::ostream &out, size_t l=0) const
virtual ~CFunction ()
Public Member Functions inherited from CEvaluationTree
bool calls (std::set< std::string > &list) const
CEvaluationTree (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=Function)
CEvaluationTree (const CEvaluationTree &src, const CCopasiContainer *pParent=NULL)
bool dependsOnTree (const std::string &name) const
CCopasiObject::DataObjectSet getDeletedObjects () const
std::string::size_type getErrorPosition () const
const std::string & getInfix () const
const std::vector
< CEvaluationNode * > & getNodeList () const
CEvaluationNode * getRoot ()
const CEvaluationNode * getRoot () const
const CEvaluationTree::Type & getType () const
bool hasCircularDependency () const
bool hasDiscontinuity () const
bool isBoolean () const
bool isUsable () const
bool operator== (const CEvaluationTree &rhs) const
virtual bool setRoot (CEvaluationNode *pRootNode)
bool setTree (const ASTNode &pRootNode)
virtual ASTNode * toAST (const CCopasiDataModel *pDataModel) const
bool updateTree ()
virtual ~CEvaluationTree ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Static Public Attributes
static const char * Infix []
Static Public Attributes inherited from CEvaluationTree
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Additional Inherited Members
Public Types inherited from CEvaluationTree
enum Type {
Function = 0, MassAction, PreDefined, UserDefined,
Expression, MathExpression
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CFunction
static bool completeFunctionList (std::vector< CFunction * > &list, const size_t &added=0)
Static Public Member Functions inherited from CEvaluationTree
static CEvaluationTree * copy (const CEvaluationTree &src)
static CEvaluationTree * create (CEvaluationTree::Type type)
static CEvaluationNode * fromAST (const ASTNode *pASTNode)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CFunction
bool initVariables ()
Protected Member Functions inherited from CEvaluationTree
void buildCalculationSequence ()
void calculate ()
bool compileNodes ()
bool parse ()
void setType (const CEvaluationTree::Type &type)
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CEvaluationTree
std::vector< CEvaluationNode * > mCalculationSequence
std::string mInfix
std::vector< CEvaluationNode * > * mpNodeList
CEvaluationNode * mpRoot
CEvaluationTree::Type mType
bool mUsable
C_FLOAT64 mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CMassAction
Created for Copasi by Stefan Hoops (C) Stefan Hoops 2001
Definition at line 30 of file CMassAction.h.
Constructor & Destructor Documentation
CMassAction::CMassAction (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 38 of file CMassAction.cpp.
                                                           :
     CFunction(name, pParent, CEvaluationTree::MassAction)
 {}
CMassAction::CMassAction (const CFunction & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CFunction & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 43 of file CMassAction.cpp.
                                                           :
     CFunction(src, pParent)
 {}
CMassAction::CMassAction (const TriLogic & reversible, const CCopasiContainer * pParent = NULL)
Specified constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 48 of file CMassAction.cpp.
References CONSTRUCTOR_TRACE, CCopasiMessage::ERROR, Infix, MCMassAction, setInfix(), TriFalse, and TriTrue.
                                                           :
     CFunction((reversible == TriTrue) ?
               "Mass action (reversible)" :
               "Mass action (irreversible)",
               pParent,
               CFunction::MassAction)
 {
   CONSTRUCTOR_TRACE;
   if (reversible != TriFalse && reversible != TriTrue)
     CCopasiMessage(CCopasiMessage::ERROR, MCMassAction + 1);
   if (reversible == TriTrue)
     setInfix(Infix[0]);
   else
     setInfix(Infix[1]);
 }
CMassAction::~CMassAction ()
Destructor
Definition at line 67 of file CMassAction.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
const C_FLOAT64 & CMassAction::calcValue (const CCallParameters< C_FLOAT64 > & callParameters) virtual
Calculates the value of the function
Parameters
const CCallParameters<C_FLOAT64> & callParameters
Returns
const C_FLOAT64 & result
Reimplemented from CFunction.
Definition at line 69 of file CMassAction.cpp.
References CCallParameters< Type >::begin(), C_FLOAT64, CCallParameters< Type >::end(), CFunction::isReversible(), CEvaluationTree::mValue, and TriFalse.
 {
   CCallParameters<C_FLOAT64>::const_iterator pCallParameters = callParameters.begin();
   CCallParameters<C_FLOAT64>::const_iterator Factor = (pCallParameters + 1)->vector->begin();
   CCallParameters<C_FLOAT64>::const_iterator End = (pCallParameters + 1)->vector->end();
   mValue = 0.0;
   if (Factor != End)
     {
       mValue = *(pCallParameters + 0)->value   // k1
                * *(Factor++)->value;      // first substrate.
       while (Factor != End)
         mValue *= *(Factor++)->value;
     }
   if (isReversible() == TriFalse)
     return mValue;
   C_FLOAT64 Products = 0.0;
   Factor = (pCallParameters + 3)->vector->begin();
   End = (pCallParameters + 3)->vector->end();
   if (Factor != End)
     {
       Products = *(pCallParameters + 2)->value // k2
                  * *(Factor++)->value;    // first product.
       while (Factor != End)
         Products *= *(Factor++)->value;
     }
   return mValue -= Products;
 }
bool CMassAction::compile () virtual
Compile the evaluation tree.
Reimplemented from CEvaluationTree.
Definition at line 164 of file CMassAction.cpp.
References CEvaluationTree::mUsable.
 {
   mUsable = true;
   return true;
 }
bool CMassAction::dependsOn (const C_FLOAT64 * parameter, const CCallParameters< C_FLOAT64 > & callParameters) const virtual
Returns whether the function depends on the given parameter &param const void * parameter &param const CCallParameters<C_FLOAT64> & callParameters &param bool dependsOn
Reimplemented from CFunction.
Definition at line 107 of file CMassAction.cpp.
References CCallParameters< Type >::begin(), CCallParameters< Type >::end(), CFunction::isReversible(), and TriTrue.
 {
   if (parameter == callParameters[0].value) return true;
   CCallParameters<C_FLOAT64>::const_iterator it;
   CCallParameters<C_FLOAT64>::const_iterator end;
   it = callParameters[1].vector->begin();
   end = callParameters[1].vector->end();
   for (; it != end; it++) if (parameter == it->value) return true;
   if (isReversible() != TriTrue) return false;
   if (parameter == callParameters[2].value) return true;
   it = callParameters[3].vector->begin();
   end = callParameters[3].vector->end();
   for (; it != end; it++) if (parameter == it->value) return true;
   return false;
 }
bool CMassAction::setInfix (const std::string & infix) virtual
Set the infix description of the tree and compile it.
Parameters
const std::string & infix
Returns
bool success
Reimplemented from CFunction.
Definition at line 132 of file CMassAction.cpp.
References CFunctionParameters::add(), CFunctionParameters::cleanup(), CFunctionParameter::FLOAT64, CFunction::getVariables(), CFunction::isReversible(), CFunctionParameter::PARAMETER, CFunctionParameter::PRODUCT, CFunction::setInfix(), CFunction::setReversible(), CFunctionParameter::SUBSTRATE, TriFalse, TriTrue, and CFunctionParameter::VFLOAT64.
Referenced by CMassAction().
 {
   if (infix == "k1*PRODUCT<substrate_i>-k2*PRODUCT<product_j>")
     setReversible(TriTrue);
   else if (infix == "k1*PRODUCT<substrate_i>")
     setReversible(TriFalse);
   else
     return false;
   CFunction::setInfix(infix);
   getVariables().cleanup();
   getVariables().add("k1",
                      CFunctionParameter::FLOAT64,
                      CFunctionParameter::PARAMETER);
   getVariables().add("substrate",
                      CFunctionParameter::VFLOAT64,
                      CFunctionParameter::SUBSTRATE);
   if (isReversible() == TriTrue)
     {
       getVariables().add("k2",
                          CFunctionParameter::FLOAT64,
                          CFunctionParameter::PARAMETER);
       getVariables().add("product",
                          CFunctionParameter::VFLOAT64,
                          CFunctionParameter::PRODUCT);
     }
   return true;
 }
std::string CMassAction::writeMathML (const std::vector< std::vector< std::string > > & variables, bool expand = true, bool fullExpand = true) const virtual
Function to write the mathematical formula in format of MathML.
Parameters
std::ostream & out
const std::vector< std::vector< std::string > > & variables
bool expand = true
bool fullExpand
Returns
std::string
Reimplemented from CFunction.
Definition at line 173 of file CMassAction.cpp.
References CFunction::isReversible(), and TriTrue.
Referenced by CQExpressionWidget::writeMathML().
 {
   std::ostringstream out;
   bool rev = (isReversible() == TriTrue);
   if (rev)
     out << "<mfenced>" << std::endl;
   out << "<mrow>" << std::endl;
   out << variables[0][0] << std::endl;
   size_t i, imax = variables[1].size();
   for (i = 0; i < imax; ++i)
     {
       out << "<mo>&CenterDot;</mo>" << std::endl;
       out << variables[1][i] << std::endl;
     }
   if (rev)
     {
       out << "<mo>-</mo>" << std::endl;
       out << variables[2][0] << std::endl;
       size_t i, imax = variables[3].size();
       for (i = 0; i < imax; ++i)
         {
           out << "<mo>&CenterDot;</mo>" << std::endl;
           out << variables[3][i] << std::endl;
         }
     }
   out << "</mrow>" << std::endl;
   if (rev)
     out << "</mfenced>" << std::endl;
   return out.str();
 }
Member Data Documentation
const char * CMassAction::Infix static
Initial value:
=
  {"k1*PRODUCT<substrate_i>-k2*PRODUCT<product_j>", "k1*PRODUCT<substrate_i>"}
CMassAction
Created for COPASI by Stefan Hoops (C) Stefan Hoops 2001
Definition at line 34 of file CMassAction.h.
Referenced by CMassAction(), CQValidatorFunction::validate(), and CQExpressionWidget::writeMathML().
The documentation for this class was generated from the following files:
CMassAction.h
CMassAction.cpp