COPASI API: CArrayElementReference Class Reference
CArrayElementReference Class Reference
#include <CArrayElementReference.h>
Public Member Functions
CArrayElementReference (const std::string &index, const CCopasiContainer *pParent)
virtual CCopasiObjectName getCN () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
virtual void print (std::ostream *ostream) const
virtual ~CArrayElementReference ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
CArrayElementReference ()
CArrayElementReference (const CArrayElementReference &src)
void updateMethod (const CCopasiAbstractArray::data_type &value)
Private Attributes
CCopasiObjectName mIndex
Additional Inherited Members
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Class CArrayElementReference
This class is used to make an element of an array accessible as a CCopasiObject. Usually an object from this class will be a child of a CArrayAnnotation and will reference a single element of the array that the CArrayAnnotation points to.
Definition at line 29 of file CArrayElementReference.h.
Constructor & Destructor Documentation
CArrayElementReference::CArrayElementReference () private
make the default constructor unaccessible
CArrayElementReference::CArrayElementReference (const CArrayElementReference & src) private
make the copy constructor unaccessible
CArrayElementReference::CArrayElementReference (const std::string & index, const CCopasiContainer * pParent)
create an element reference with a given index. The index is passed as a string, e.g. "[3][2]" The object name will be the index string, the type is "ElementReference" pParent may not be NULL.
Definition at line 18 of file CArrayElementReference.cpp.
     : CCopasiObject(index, pParent, "ElementReference",
                     CCopasiObject::Reference |
                     CCopasiObject::NonUniqueName |
                     CCopasiObject::ValueDbl),
     //    mpReference(NULL),
     mIndex(index)
 {
   assert(pParent != NULL);
 }
virtual CArrayElementReference::~CArrayElementReference () inline virtual
Definition at line 66 of file CArrayElementReference.h.
 {}
Member Function Documentation
CCopasiObjectName CArrayElementReference::getCN () const virtual
Retrieve the CN of the object
Returns
CCopasiObjectName
Reimplemented from CCopasiObject.
Definition at line 89 of file CArrayElementReference.cpp.
References CCopasiObject::getCN(), CCopasiObject::getObjectParent(), and mIndex.
   {
     if (getObjectParent())
       return getObjectParent()->getCN() + mIndex;
     else
       return "Array" + mIndex;
   }
std::string CArrayElementReference::getObjectDisplayName (bool regular = true, bool richtext = false) const virtual
generate a display name.
Reimplemented from CCopasiObject.
Definition at line 69 of file CArrayElementReference.cpp.
References CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDisplayName(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiObject::getObjectType(), and mIndex.
   {
     if (getObjectParent())
       {
         //if the array has as task as ancestor, use the task (skip the problem/method)
         CCopasiContainer* pT = getObjectAncestor("Task");
         std::string part;
         if (pT)
           part = pT->getObjectDisplayName(regular, richtext) + ".";
         else if (getObjectParent()->getObjectParent() && getObjectParent()->getObjectParent()->getObjectType() != "Model")
           part = getObjectParent()->getObjectParent()->getObjectDisplayName(regular, richtext) + ".";
         //now part contains the display name of the task, or the parent of the parent
         return part + getObjectParent()->getObjectName() + mIndex;
       }
     else
       return "Array" + mIndex;
   }
virtual const CCopasiObject* CArrayElementReference::getValueObject () const inline virtual
Reimplemented from CCopasiObject.
Definition at line 74 of file CArrayElementReference.h.
 {return this;}
void * CArrayElementReference::getValuePointer () const virtual
returns a pointer to the numerical values of the array element this will be a *C_FLOAT64 for this class.
Reimplemented from CCopasiObject.
Definition at line 35 of file CArrayElementReference.cpp.
References CArrayAnnotation::array(), C_INT32, CArrayAnnotation::dimensionality(), CCopasiObjectName::getElementIndex(), CCopasiObjectName::getElementName(), CCopasiObject::getObjectParent(), mIndex, and CArrayAnnotation::size().
Referenced by print().
   {
     CArrayAnnotation * tmpAA = dynamic_cast<CArrayAnnotation*>(getObjectParent());
     if (!tmpAA) return NULL;
     //now get the array indices. At the moment only numerical indices...
     //this could be done in the constructor, actually
     unsigned C_INT32 ii = 0;
     CCopasiArray::index_type index;
     std::string tmpIndexString;
     while ((tmpIndexString = mIndex.getElementName(ii, false)) != "")
       {
         if (tmpIndexString == ".")
           break; //"." indicates 0-dimensional array. This means index should stay empty
         index.push_back(mIndex.getElementIndex(ii));
         ++ii;
       }
     if (index.size() != tmpAA->dimensionality())  //wrong number of indices for this array
       return NULL;
     for (ii = 0; ii < tmpAA->dimensionality(); ++ii)
       if (index[ii] >= tmpAA->size()[ii]) //out of range
         return NULL;
     return &(*tmpAA->array())[index];
     //TODO
     //TODO perhaps we should cache the pointer. This would mean we need to invalidate the pointer
     //if somthing with the array changes
     //return mpReference;
   }
void CArrayElementReference::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Definition at line 97 of file CArrayElementReference.cpp.
References getValuePointer().
   {
     //if (mpReference)
     //  (*ostream) << *mpReference;
     //TODO perhaps we should cache the
     CCopasiAbstractArray::data_type * tmp = (double*)getValuePointer();
     if (tmp)
       (*ostream) << *tmp;
   };
void CArrayElementReference::updateMethod (const CCopasiAbstractArray::data_type & value) private
this method does nothing at the moment!
Definition at line 29 of file CArrayElementReference.cpp.
 {
   //  if (mpReference)
   //    *mpReference = value;
 }
Member Data Documentation
CCopasiObjectName CArrayElementReference::mIndex private
this contains the index in string format, e.g. "[2][7]"
Definition at line 38 of file CArrayElementReference.h.
Referenced by getCN(), getObjectDisplayName(), and getValuePointer().
The documentation for this class was generated from the following files:
CArrayElementReference.h
CArrayElementReference.cpp