COPASI API: CCopasiObject.h File Reference
CCopasiObject.h File Reference
#include <string>
#include <iostream>
#include <vector>
#include <set>
#include <list>
#include "copasi/copasi.h"
#include "copasi/math/CMathEnum.h"
Classes
class CCopasiMatrixReference< CType >
class CCopasiObject
class CCopasiObjectReference< CType >
class CCopasiVectorReference< CType >
class CObjectInterface
class Refresh
class RefreshTemplate< CClass >
class SpecificUpdateMethod< CType, VType >
class UpdateMethod
Functions
template<class CType >
CCopasiMatrixReference< CType > * createMatrixReference (const std::string &name, const CCopasiContainer *pParent, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObjectReference< CType > * createReference (const std::string &name, const CCopasiContainer *pParent, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiVectorReference< CType > * createVectorReference (const std::string &name, const CCopasiContainer *pParent, CType &reference, const unsigned C_INT32 &flag=0)
template<typename ForwardAccessIterator >
std::list< const CCopasiObject * > sortObjectsByDependency (ForwardAccessIterator begin, ForwardAccessIterator end, const CCopasiObject::DataObjectSet &context)
Function Documentation
template<class CType > CCopasiMatrixReference< CType >* createMatrixReference (const std::string & name, const CCopasiContainer * pParent, CType & reference, const unsigned C_INT32 & flag = 0)
Definition at line 587 of file CCopasiObject.h.
Referenced by CCopasiContainer::addMatrixReference().
 {return new CCopasiMatrixReference< CType >(name, pParent, reference, flag);}
template<class CType > CCopasiObjectReference< CType >* createReference (const std::string & name, const CCopasiContainer * pParent, CType & reference, const unsigned C_INT32 & flag = 0)
Definition at line 573 of file CCopasiObject.h.
Referenced by CCopasiContainer::addObjectReference().
 {return new CCopasiObjectReference< CType >(name, pParent, reference, flag);}
template<class CType > CCopasiVectorReference< CType >* createVectorReference (const std::string & name, const CCopasiContainer * pParent, CType & reference, const unsigned C_INT32 & flag = 0)
Definition at line 580 of file CCopasiObject.h.
Referenced by CCopasiContainer::addVectorReference().
 {return new CCopasiVectorReference< CType >(name, pParent, reference, flag);}
template<typename ForwardAccessIterator > std::list< const CCopasiObject * > sortObjectsByDependency (ForwardAccessIterator begin, ForwardAccessIterator end, const CCopasiObject::DataObjectSet & context)
Sort the CCopasiObjects in the interval [begin, end) according to their dependencies
Parameters
ForwardAccessIterator begin
ForwardAccessIterator end
const DataObjectSet & context
Returns
std::list< const CCopasiObject * >
Definition at line 602 of file CCopasiObject.h.
Referenced by CModel::buildInitialRefreshSequence(), and CCopasiObject::buildUpdateSequence().
 {
   std::list< const CCopasiObject * > SortedList;
   std::list< const CCopasiObject * >::iterator itList;
   std::list< const CCopasiObject * >::iterator endList;
   CCopasiObject::DataObjectSet AllDependencies;
   std::list< CCopasiObject::DataObjectSet > DependencySet;
   std::list< CCopasiObject::DataObjectSet >::iterator itDependencies;
   for (; begin != end; ++begin)
     {
       AllDependencies.clear();
       (*begin)->getAllDependencies(AllDependencies, context);
       itList = SortedList.begin();
       endList = SortedList.end();
       itDependencies = DependencySet.begin();
       for (; itList != endList; ++itList, ++itDependencies)
         if (itDependencies->count(*begin)) break;
       SortedList.insert(itList, *begin);
       DependencySet.insert(itDependencies, AllDependencies);
     }
   return SortedList;
 }