COPASI API: CQRDFTreeView Class Reference
CQRDFTreeView Class Reference
#include <CQRDFTreeView.h>
Public Slots
virtual void clear ()
CQRDFTreeViewItem * find (const CRDFNode *pNode)
void insert (const CRDFNode *pNode, CQRDFTreeViewItem *pItem)
Public Member Functions
CQRDFTreeView (QWidget *parent=0, const char *name=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
virtual ~CQRDFTreeView ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Member Functions
void load ()
Private Attributes
std::map< const CRDFNode
*, CQRDFTreeViewItem * > mNode2Item
CRDFGraph * mpGraph
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 32 of file CQRDFTreeView.h.
Constructor & Destructor Documentation
CQRDFTreeView::CQRDFTreeView (QWidget * parent = 0, const char * name = 0)
Definition at line 36 of file CQRDFTreeView.cpp.
                                                               :
   CopasiWidget(parent, name),
   mNode2Item(),
   mpGraph(NULL)
 {
   setupUi(this);
 }
CQRDFTreeView::~CQRDFTreeView () virtual
Definition at line 44 of file CQRDFTreeView.cpp.
References clear().
 {
   clear();
 }
Member Function Documentation
void CQRDFTreeView::clear () virtual slot
Clear the listeview
Definition at line 165 of file CQRDFTreeView.cpp.
References mNode2Item, mpGraph, and pdelete.
Referenced by enterProtected(), and ~CQRDFTreeView().
 {
   mNode2Item.clear();
   pdelete(mpGraph);
   mpTreeWidget->clear();
 }
bool CQRDFTreeView::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 56 of file CQRDFTreeView.cpp.
References CRDFSubject::BLANK_NODE, clear(), CCopasiMessage::clearDeque(), COL_SUBJECT, CRDFGraph::createAboutNode(), find(), FROM_UTF8, CKeyFactory::get(), CCopasiMessage::getAllMessageText(), CRDFSubject::getBlankNodeID(), CCopasiRootContainer::getKeyFactory(), CAnnotation::getMiriamAnnotation(), CRDFSubject::getResource(), CRDFGraph::getTriplets(), CRDFSubject::getType(), CRDFParser::graphFromXml(), insert(), CopasiWidget::mKey, mpGraph, CRDFSubject::RESOURCE, CQRDFTreeViewItem::setTriplet(), CCopasiMessage::size(), and CQMessageBox::warning().
 {
   clear();
   CCopasiObject *pObject = dynamic_cast< CCopasiObject * >(CCopasiRootContainer::getKeyFactory()->get(mKey));
   if (pObject != NULL)
     {
       CModelEntity * pEntity = NULL;
       CEvent * pEvent = NULL;
       CReaction * pReaction = NULL;
       CFunction * pFunction = NULL;
       const std::string * pMiriamAnnotation = NULL;
       if ((pEntity = dynamic_cast< CModelEntity * >(pObject)) != NULL)
         pMiriamAnnotation = &pEntity->getMiriamAnnotation();
       else if ((pEvent = dynamic_cast< CEvent * >(pObject)) != NULL)
         pMiriamAnnotation = &pEvent->getMiriamAnnotation();
       else if ((pReaction = dynamic_cast< CReaction * >(pObject)) != NULL)
         pMiriamAnnotation = &pReaction->getMiriamAnnotation();
       else if ((pFunction = dynamic_cast< CFunction * >(pObject)) != NULL)
         pMiriamAnnotation = &pFunction->getMiriamAnnotation();
       if (pMiriamAnnotation && *pMiriamAnnotation != "")
         mpGraph = CRDFParser::graphFromXml(*pMiriamAnnotation);
     }
   CCopasiMessage::clearDeque();
   if (CCopasiMessage::size() != 0)
     {
       QString Message = FROM_UTF8(CCopasiMessage::getAllMessageText());
       CQMessageBox::warning(this, QString("RDF Warning"), Message,
                             QMessageBox::Ok, QMessageBox::Ok);
     }
   if (mpGraph == NULL)
     mpGraph = new CRDFGraph;
   // We make sure that we always have an about node.
   mpGraph->createAboutNode(mKey);
   // We iterate of all triplets
   std::set< CRDFTriplet >::const_iterator it = mpGraph->getTriplets().begin();
   std::set< CRDFTriplet >::const_iterator end = mpGraph->getTriplets().end();
   for (; it != end; ++it)
     {
       CQRDFTreeViewItem * pSubjectItem = find(it->pSubject);
       if (pSubjectItem == NULL)
         {
           pSubjectItem = new CQRDFTreeViewItem(mpTreeWidget, NULL);
           insert(it->pSubject, pSubjectItem);
           // Display the subject information
           const CRDFSubject & Subject = it->pSubject->getSubject();
           switch (Subject.getType())
             {
               case CRDFSubject::RESOURCE:
                 pSubjectItem->setText(COL_SUBJECT, FROM_UTF8(Subject.getResource()));
                 break;
               case CRDFSubject::BLANK_NODE:
                 pSubjectItem->setText(COL_SUBJECT, FROM_UTF8(Subject.getBlankNodeID()));
                 break;
             }
         }
       CQRDFTreeViewItem * pObjectItem = NULL;
       if (it->Predicate.getURI() == "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject")
         {
           pObjectItem = new CQRDFTreeViewItem(pSubjectItem, NULL);
           insert(it->pObject, pObjectItem);
         }
       else
         pObjectItem = find(it->pObject);
       if (pObjectItem == NULL)
         {
           pObjectItem = new CQRDFTreeViewItem(pSubjectItem, NULL);
           insert(it->pObject, pObjectItem);
         }
       else
         {
           QTreeWidgetItem * pParent = pObjectItem->parent();
           if (pParent == NULL)
             {
               mpTreeWidget->invisibleRootItem()->removeChild(pObjectItem);
               pSubjectItem->addChild(pObjectItem);
             }
           else
             {
               pParent->removeChild(pObjectItem);
               pSubjectItem->addChild(pObjectItem);
             }
         }
       pObjectItem->setTriplet(*it);
     }
   mpTreeWidget->setFocus();
   return true;
 }
CQRDFTreeViewItem * CQRDFTreeView::find (const CRDFNode * pNode) slot
Returns the list view item for node if it exists otherwise NULL.
Parameters
const CRDFNode * pSubject
Returns
CQRDFTreeViewItem * listViewItem
Definition at line 172 of file CQRDFTreeView.cpp.
References mNode2Item.
Referenced by enterProtected().
 {
   std::map< const CRDFNode *, CQRDFTreeViewItem * >::iterator it = mNode2Item.find(pNode);
   if (it != mNode2Item.end())
     return it->second;
   return NULL;
 }
void CQRDFTreeView::insert (const CRDFNode * pNode, CQRDFTreeViewItem * pItem) slot
Insert a map from a CRDFNode to a CRDFListView
Parameters
const CRDFNode * pSubject
CQRDFTreeViewItem * pItem
Definition at line 182 of file CQRDFTreeView.cpp.
References mNode2Item.
Referenced by enterProtected().
 {
   mNode2Item[pNode] = pItem;
 }
void CQRDFTreeView::load () private
bool CQRDFTreeView::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 49 of file CQRDFTreeView.cpp.
 {
   return true;
 }
Member Data Documentation
std::map< const CRDFNode *, CQRDFTreeViewItem * > CQRDFTreeView::mNode2Item private
A map to look up items associated with a node.
Definition at line 72 of file CQRDFTreeView.h.
Referenced by clear(), find(), and insert().
CRDFGraph* CQRDFTreeView::mpGraph private
The RDF Graph
Definition at line 77 of file CQRDFTreeView.h.
Referenced by clear(), and enterProtected().
The documentation for this class was generated from the following files:
CQRDFTreeView.h
CQRDFTreeView.cpp