COPASI API: CQNameSelectionDialog Class Reference
CQNameSelectionDialog Class Reference
#include <CQNameSelectionDialog.h>
Public Member Functions
CQNameSelectionDialog (QWidget *parent=0, Qt::WindowFlags f=0)
const QString & getSelection () const
void setSelectionList (const QStringList &selectionList)
virtual ~CQNameSelectionDialog ()
Protected Slots
virtual void accept ()
Private Attributes
QString mSelection
Detailed Description
Definition at line 15 of file CQNameSelectionDialog.h.
Constructor & Destructor Documentation
CQNameSelectionDialog::CQNameSelectionDialog (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 8 of file CQNameSelectionDialog.cpp.
                                                                              :
   QDialog(parent, f),
   mSelection()
 {
   setupUi(this);
 }
CQNameSelectionDialog::~CQNameSelectionDialog () virtual
Definition at line 16 of file CQNameSelectionDialog.cpp.
 {}
Member Function Documentation
void CQNameSelectionDialog::accept () protected virtual slot
Definition at line 30 of file CQNameSelectionDialog.cpp.
References mSelection.
 {
   mSelection = mpSelectionBox->currentText();
   QDialog::accept();
 }
const QString & CQNameSelectionDialog::getSelection () const
Definition at line 24 of file CQNameSelectionDialog.cpp.
References mSelection.
Referenced by CQParameterOverviewWidget::slotBtnNew(), and CQParameterOverviewWidget::slotBtnSaveAs().
 {
   return mSelection;
 }
void CQNameSelectionDialog::setSelectionList (const QStringList & selectionList)
Definition at line 19 of file CQNameSelectionDialog.cpp.
Referenced by CQSpeciesDetail::copy(), ReactionsWidget1::copy(), CQParameterOverviewWidget::slotBtnNew(), and CQParameterOverviewWidget::slotBtnSaveAs().
 {
   mpSelectionBox->addItems(selectionList);
 }
Member Data Documentation
QString CQNameSelectionDialog::mSelection private
Definition at line 30 of file CQNameSelectionDialog.h.
Referenced by accept(), and getSelection().
The documentation for this class was generated from the following files:
CQNameSelectionDialog.h
CQNameSelectionDialog.cpp