COPASI API: CCopasiXMLParser::TaskElement Class Reference
CCopasiXMLParser::TaskElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
TaskElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual ~TaskElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { Task = 0, Report, Problem, Method }
Private Attributes
MethodElement * mpMethodElement
ParameterGroupElement * mpProblemElement
ReportInstanceElement * mpReportElement
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2401 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::TaskElement::Element private
Enum of invoked parsers
Enumerator
Task
Report
Problem
Method
Definition at line 2409 of file CCopasiXMLParser.h.
     {
       Task = 0,
       Report,
       Problem,
       Method
     };
Constructor & Destructor Documentation
CCopasiXMLParser::TaskElement::TaskElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 8476 of file CCopasiXMLParser.cpp.
                                                                                                  :
   CXMLElementHandler < CCopasiXMLParser,
   SCopasiXMLParserCommon > (parser, common),
   mpReportElement(NULL),
   mpProblemElement(NULL),
   mpMethodElement(NULL)
 {}
CCopasiXMLParser::TaskElement::~TaskElement () virtual
Destructor
Definition at line 8484 of file CCopasiXMLParser.cpp.
References pdelete.
 {
   pdelete(mpReportElement);
   pdelete(mpProblemElement);
   pdelete(mpMethodElement);
 }
Member Function Documentation
void CCopasiXMLParser::TaskElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 8657 of file CCopasiXMLParser.cpp.
References CCopasiParameterGroup::elevateChildren(), CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiTask::getMethod(), CCopasiParameterGroup::getParameter(), CCopasiTask::getProblem(), CCopasiTask::getType(), CCopasiParameter::getValue(), CCopasiXMLParser::mCommon, MCXML, SCopasiXMLParserCommon::mKey2ObjectiveFunction, CExpatTemplate< CExpat >::mParser, CCopasiTask::optimization, SCopasiXMLParserCommon::pCurrentTask, pdelete, CCopasiParameter::Value::pSTRING, CCopasiContainer::remove(), CCopasiParameterGroup::setValue(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case Task:
         if (strcmp(pszName, "Task"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Task", mParser.getCurrentLineNumber());
         if (mCommon.pCurrentTask == NULL)
           CCopasiMessage::getLastMessage();
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         mParser.onEndElement(pszName);
         break;
       case Report:
         if (strcmp(pszName, "Report"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Report", mParser.getCurrentLineNumber());
         // do nothing, the pointer to the correct report definition can
         // only be set after the report definitions have been read.
         break;
       case Problem:
         if (strcmp(pszName, "Problem"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Problem", mParser.getCurrentLineNumber());
         // This is needed for old files containing the objective function as
         // part of the list of function definitions
         if (mCommon.pCurrentTask->getType() == CCopasiTask::optimization)
           {
             CCopasiProblem * pProblem = mCommon.pCurrentTask->getProblem();
             CCopasiParameter * pParameter = pProblem->getParameter("ObjectiveFunction");
             if (pParameter != NULL)
               {
                 if (mCommon.mKey2ObjectiveFunction.find(*pParameter->getValue().pSTRING) !=
                     mCommon.mKey2ObjectiveFunction.end())
                   {
                     std::string Infix = mCommon.mKey2ObjectiveFunction[*pParameter->getValue().pSTRING]->getInfix();
                     pProblem->setValue("ObjectiveExpression", Infix);
                   }
                 pProblem->remove(pParameter);
               }
             std::map< std::string, CExpression * >::iterator it = mCommon.mKey2ObjectiveFunction.begin();
             std::map< std::string, CExpression * >::iterator end = mCommon.mKey2ObjectiveFunction.end();
             for (; it != end; ++it)
               {
                 pdelete(it->second);
               }
             mCommon.mKey2ObjectiveFunction.clear();
           }
         mCommon.pCurrentTask->getProblem()->elevateChildren();
         break;
       case Method:
         if (strcmp(pszName, "Method"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "Method", mParser.getCurrentLineNumber());
         mCommon.pCurrentTask->getMethod()->elevateChildren();
         mCurrentElement = Task;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::TaskElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 8491 of file CCopasiXMLParser.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiTask::crosssection, CCopasiMessage::EXCEPTION, CCopasiTask::fluxMode, CCopasiTask::getProblem(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, CCopasiXMLParser::mCommon, MCXML, CCopasiTask::moieties, CExpatTemplate< CExpat >::mParser, CCopasiTask::optimization, CCopasiTask::parameterFitting, SCopasiXMLParserCommon::pCurrentTask, SCopasiXMLParserCommon::pModel, SCopasiXMLParserCommon::pTaskList, CCopasiMessage::RAW, CCopasiTask::scan, CCopasiTask::sens, CCopasiProblem::setModel(), CCopasiTask::setScheduled(), CCopasiTask::setUpdateModel(), CCopasiTask::steadyState, CCopasiParameter::STRING, CCopasiTask::timeCourse, toEnum(), CCopasiTask::tssAnalysis, UNKNOWN_ELEMENT, CCopasiTask::unset, and CCopasiTask::XMLType.
 {
   mCurrentElement++; /* We should always be on the next element */
   mpCurrentHandler = NULL;
   const char * Key;
   const char * type;
   CCopasiTask::Type Type;
   bool Scheduled = false;
   bool UpdateModel = false;
   switch (mCurrentElement)
     {
       case Task:
         if (strcmp(pszName, "Task"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "Task", mParser.getCurrentLineNumber());
         mCommon.pCurrentTask = NULL;
         Key = mParser.getAttributeValue("key", papszAttrs, false);
         type = mParser.getAttributeValue("type", papszAttrs);
         Type = toEnum(type, CCopasiTask::XMLType, CCopasiTask::unset);
         Scheduled = mParser.toBool(mParser.getAttributeValue("scheduled", papszAttrs, "false"));
         UpdateModel = mParser.toBool(mParser.getAttributeValue("updateModel", papszAttrs, "false"));
         // create a new CCopasiTask element depending on the type
         switch (Type)
           {
             case CCopasiTask::steadyState:
               mCommon.pCurrentTask = new CSteadyStateTask(mCommon.pTaskList);
               break;
             case CCopasiTask::timeCourse:
               mCommon.pCurrentTask = new CTrajectoryTask(mCommon.pTaskList);
               break;
             case CCopasiTask::scan:
               mCommon.pCurrentTask = new CScanTask(mCommon.pTaskList);
               break;
             case CCopasiTask::fluxMode:
               mCommon.pCurrentTask = new CEFMTask(mCommon.pTaskList);
               break;
             case CCopasiTask::optimization:
               mCommon.pCurrentTask = new COptTask(Type, mCommon.pTaskList);
               mCommon.pCurrentTask->getProblem()->assertParameter("Steady-State", CCopasiParameter::STRING, std::string(""));
               mCommon.pCurrentTask->getProblem()->assertParameter("Time-Course", CCopasiParameter::STRING, std::string(""));
               break;
             case CCopasiTask::parameterFitting:
               mCommon.pCurrentTask = new CFitTask(Type, mCommon.pTaskList);
               break;
             case CCopasiTask::mca:
               mCommon.pCurrentTask = new CMCATask(mCommon.pTaskList);
               break;
             case CCopasiTask::lna:
               mCommon.pCurrentTask = new CLNATask(mCommon.pTaskList);
               break;
             case CCopasiTask::lyap:
               mCommon.pCurrentTask = new CLyapTask(mCommon.pTaskList);
               break;
             case CCopasiTask::sens:
               mCommon.pCurrentTask = new CSensTask(mCommon.pTaskList);
               break;
             case CCopasiTask::tssAnalysis:
               mCommon.pCurrentTask = new CTSSATask(mCommon.pTaskList);
               break;
             case CCopasiTask::moieties:
               mCommon.pCurrentTask = new CMoietiesTask(Type, mCommon.pTaskList);
               break;
             case CCopasiTask::crosssection:
               mCommon.pCurrentTask = new CCrossSectionTask(mCommon.pTaskList);
               break;
             default:
               mParser.pushElementHandler(&mParser.mUnknownElement);
               mParser.onStartElement(pszName, papszAttrs);
               CCopasiMessage(CCopasiMessage::RAW, MCXML + 5,
                              type, mParser.getCurrentLineNumber());
               break;
           }
         if (mCommon.pCurrentTask != NULL)
           {
             mCommon.pCurrentTask->setScheduled(Scheduled);
             mCommon.pCurrentTask->setUpdateModel(UpdateModel);
             mCommon.pCurrentTask->getProblem()->setModel(mCommon.pModel);
             if (Key != NULL)
               {
                 addFix(Key, mCommon.pCurrentTask);
               }
           }
         return;
         break;
       case Report:
         if (!strcmp(pszName, "Report"))
           {
             if (!mpReportElement)
               {
                 mpReportElement = new ReportInstanceElement(mParser, mCommon);
               }
             mpCurrentHandler = mpReportElement;
           }
         break;
       case Problem:
         if (!strcmp(pszName, "Problem"))
           {
             if (!mpProblemElement)
               {
                 mpProblemElement = new ParameterGroupElement(mParser, mCommon);
               }
             mpProblemElement->setDerivedElement(mCommon.pCurrentTask->getProblem());
             mpCurrentHandler = mpProblemElement;
           }
         break;
       case Method:
         if (!strcmp(pszName, "Method"))
           {
             if (!mpMethodElement)
               {
                 mpMethodElement = new MethodElement(mParser, mCommon);
               }
             mpCurrentHandler = mpMethodElement;
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
MethodElement* CCopasiXMLParser::TaskElement::mpMethodElement private
Definition at line 2419 of file CCopasiXMLParser.h.
ParameterGroupElement* CCopasiXMLParser::TaskElement::mpProblemElement private
Definition at line 2418 of file CCopasiXMLParser.h.
ReportInstanceElement* CCopasiXMLParser::TaskElement::mpReportElement private
Definition at line 2417 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp