COPASI API: SCopasiXMLGUI Class Reference
SCopasiXMLGUI Class Reference
#include <CCopasiXMLInterface.h>
Public Member Functions
CCopasiVector< CSlider > * getSliderList ()
const CCopasiVector< CSlider > * getSliderList () const
SCopasiXMLGUI (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
~SCopasiXMLGUI ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CCopasiVector< CSlider > * mpSliderList
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
The class CCopasiXMLInterface specifies an interface to various XML formats related to COPASI relevant information. Derived classes have to implement the following two methods:
See Also
bool load(std::istream & is)
bool save(std::ostream & os)
Note: the responsibility to free allocated memory during load is handed to the user.
Definition at line 49 of file CCopasiXMLInterface.h.
Constructor & Destructor Documentation
SCopasiXMLGUI::SCopasiXMLGUI (const std::string & name, const CCopasiContainer * pParent = NULL, const std::string & type = "CN", const unsigned C_INT32 & flag = CCopasiObject::Container)
Constructor
CCopasiXMLInterface class. The class CCopasiXMLInterface is the interface to various XML document containing COPASI relevant information.
Created for COPASI by Stefan Hoops 2003
Definition at line 40 of file CCopasiXMLInterface.cpp.
   : CCopasiContainer(name, pParent, type, flag),
     mpSliderList(new CCopasiVector<CSlider>("SliderList", this))
 {}
SCopasiXMLGUI::~SCopasiXMLGUI ()
Constructor
Definition at line 48 of file CCopasiXMLInterface.cpp.
 {
 }
Member Function Documentation
CCopasiVector< CSlider > * SCopasiXMLGUI::getSliderList ()
Returns a pointer to the slider list.
Returns a pointer the the slider list.
Definition at line 55 of file CCopasiXMLInterface.cpp.
References mpSliderList.
Referenced by SliderDialog::addSlider(), SliderDialog::equivalentSliderExists(), SliderDialog::getCSlidersForObject(), CCopasiXML::saveGUI(), CCopasiXMLParser::ListOfSlidersElement::start(), and CCopasiXMLParser::SliderElement::start().
 {
   return this->mpSliderList;
 }
const CCopasiVector< CSlider > * SCopasiXMLGUI::getSliderList () const
Returns a const pointer to the slider list.
Definition at line 63 of file CCopasiXMLInterface.cpp.
References mpSliderList.
 {
   return this->mpSliderList;
 }
Member Data Documentation
CCopasiVector< CSlider >* SCopasiXMLGUI::mpSliderList protected
Pointer to a vector of sliders which has been loaded or is to be saved. The ownership is handed to the user.
Definition at line 82 of file CCopasiXMLInterface.h.
Referenced by getSliderList().
The documentation for this class was generated from the following files:
CCopasiXMLInterface.h
CCopasiXMLInterface.cpp