COPASI API: CQCurrentValueTable Class Reference
CQCurrentValueTable Class Reference
#include <CQCurrentValueTable.h>
Signals
void valueChanged (int row)
Public Member Functions
CQCurrentValueTable (QWidget *parent=0)
std::string getKeyForRow (int row) const
bool getValueForRow (int row) const
int numRows () const
void setNumCols (int columns)
void setNumRows (int rows)
void setRowInTable (int row, std::string key, std::string s, C_FLOAT64 val)
void updateRowInTable (int row, C_FLOAT64 val)
QHeaderView * verticalHeader ()
~CQCurrentValueTable ()
Protected Member Functions
void init ()
void setAllBoxesChecked (bool checked=true)
void setAllBoxesUnchecked ()
void setKeyIndex (std::string key, int row)
void setValue (int row, C_FLOAT64 val)
Protected Attributes
std::map< int, std::string > mIndexMap
QPushButton * mpCheckAllButton
QTableWidget * mpTable
QPushButton * mpUncheckAllButton
Private Slots
void slotCheckAllClicked ()
void slotUncheckAllClicked ()
void tableValueChanged (int row, int column)
Detailed Description
Definition at line 26 of file CQCurrentValueTable.h.
Constructor & Destructor Documentation
CQCurrentValueTable::CQCurrentValueTable (QWidget * parent = 0)
Definition at line 27 of file CQCurrentValueTable.cpp.
References init().
   : QWidget(parent)
 {
   init();
   this->show();
 }
CQCurrentValueTable::~CQCurrentValueTable ()
Definition at line 63 of file CQCurrentValueTable.cpp.
 {}
Member Function Documentation
std::string CQCurrentValueTable::getKeyForRow (int row) const
Definition at line 144 of file CQCurrentValueTable.cpp.
References mIndexMap.
Referenced by CQLayoutMainWindow::parameterTableValueChanged(), and setAllBoxesChecked().
 {
   std::string s = "";
   std::map<int, std::string>::const_iterator itIndexObj = this->mIndexMap.find(row);
   if (itIndexObj != this->mIndexMap.end())
     {
       s = (*itIndexObj).second;
     }
   return s;
 }
bool CQCurrentValueTable::getValueForRow (int row) const
Definition at line 158 of file CQCurrentValueTable.cpp.
References mpTable.
Referenced by CQLayoutMainWindow::parameterTableValueChanged().
 {
   QTableWidgetItem *pCell = this->mpTable->item(row, 0);
   assert(pCell != NULL);
   return pCell->checkState() == Qt::Checked;
 }
void CQCurrentValueTable::init () protected
Definition at line 34 of file CQCurrentValueTable.cpp.
References mpCheckAllButton, mpTable, mpUncheckAllButton, slotCheckAllClicked(), slotUncheckAllClicked(), tableValueChanged(), and verticalHeader().
Referenced by CQCurrentValueTable().
 {
   QVBoxLayout* pLayout = new QVBoxLayout(this);
   this->mpTable = new QTableWidget(this);
   pLayout->addWidget(this->mpTable);
   this->mpTable->setRowCount(1);
   this->mpTable->setColumnCount(2);
   // set default entry
   QHeaderView *header = this->mpTable->horizontalHeader();
   this->mpTable->setHorizontalHeaderLabels(QStringList() << "Metabolite" << "Concentration");
   header = this->verticalHeader();
   header->hide();
   QTableWidgetItem* pItem = new QTableWidgetItem("*** no time series load ***");
   this->mpTable->setItem(0, 0, pItem);
   pItem = new QTableWidgetItem("NaN");
   this->mpTable->setItem(0, 1, pItem);
   this->mpTable->item(0, 0)->setFlags(this->mpTable->item(0, 0)->flags() & ~Qt::ItemIsEditable);
   QHBoxLayout *hLayout = new QHBoxLayout();
   this->mpCheckAllButton = new QPushButton("Check all", this);
   this->mpUncheckAllButton = new QPushButton("Uncheck all", this);
   hLayout->addWidget(mpCheckAllButton);
   hLayout->addWidget(mpUncheckAllButton);
   pLayout->addLayout(hLayout);
   connect(this->mpTable, SIGNAL(cellChanged(int, int)), this, SLOT(tableValueChanged(int, int)));
   connect(this->mpCheckAllButton, SIGNAL(clicked()), this, SLOT(slotCheckAllClicked()));
   connect(this->mpUncheckAllButton, SIGNAL(clicked()), this, SLOT(slotUncheckAllClicked()));
   resize(QSize(202, 153).expandedTo(minimumSizeHint()));
 }
int CQCurrentValueTable::numRows () const
Definition at line 185 of file CQCurrentValueTable.cpp.
References mpTable.
Referenced by CQLayoutMainWindow::updateValueTable().
 {
   return this->mpTable->rowCount();
 }
void CQCurrentValueTable::setAllBoxesChecked (bool checked = true) protected
Definition at line 100 of file CQCurrentValueTable.cpp.
References CQLayoutMainWindow::addItemInAnimation(), getKeyForRow(), mpTable, and CQLayoutMainWindow::removeItemInAnimation().
Referenced by setAllBoxesUnchecked(), and slotCheckAllClicked().
 {
   int i;
   for (i = 0; i < this->mpTable->rowCount(); i++)
     {
       QTableWidgetItem *pCell = this->mpTable->item(i, 0);
       assert(pCell != NULL);
       if (pCell->flags() & Qt::ItemIsUserCheckable)
         {
           // is cell a QCheckTableItem?
           pCell->setCheckState(checked ? Qt::Checked : Qt::Unchecked);
           CQLayoutMainWindow * pTmp = dynamic_cast<CQLayoutMainWindow *>(parentWidget()->parentWidget()->parentWidget()->parentWidget());
           assert(pTmp);
           if (pTmp)
             {
               if (checked == true)
                 {
                   pTmp->addItemInAnimation(this->getKeyForRow(i));
                 }
               else
                 {
                   pTmp->removeItemInAnimation(this->getKeyForRow(i));
                 }
             }
         }
     }
 }
void CQCurrentValueTable::setAllBoxesUnchecked () protected
Definition at line 131 of file CQCurrentValueTable.cpp.
References setAllBoxesChecked().
Referenced by slotUncheckAllClicked().
 {
   this->setAllBoxesChecked(false);
 }
void CQCurrentValueTable::setKeyIndex (std::string key, int row) protected
Definition at line 137 of file CQCurrentValueTable.cpp.
References mIndexMap.
Referenced by setRowInTable().
 {
   this->mIndexMap.insert(std::pair<int, std::string>
                          (row,
                           key));
 }
void CQCurrentValueTable::setNumCols (int columns)
Definition at line 180 of file CQCurrentValueTable.cpp.
References mpTable.
Referenced by CQLayoutMainWindow::insertValueTable().
 {
   this->mpTable->setColumnCount(columns);
 }
void CQCurrentValueTable::setNumRows (int rows)
Definition at line 175 of file CQCurrentValueTable.cpp.
References mpTable.
Referenced by CQLayoutMainWindow::insertValueTable().
 {
   this->mpTable->setRowCount(rows);
 }
void CQCurrentValueTable::setRowInTable (int row, std::string key, std::string s, C_FLOAT64 val)
Definition at line 67 of file CQCurrentValueTable.cpp.
References FROM_UTF8, mpTable, and setKeyIndex().
Referenced by CQLayoutMainWindow::insertValueTable().
 {
   QTableWidgetItem * pCheckItem = new QTableWidgetItem(FROM_UTF8(s));
   // make the item a check item and make it non editable
   pCheckItem->setFlags((pCheckItem->flags() & ~Qt::ItemIsEditable) | Qt::ItemIsUserCheckable);
   this->mpTable->setItem(row, 0, pCheckItem);
   pCheckItem->setCheckState(Qt::Checked); // initially checked
   pCheckItem = new QTableWidgetItem(QString::number(val));
   this->mpTable->setItem(row, 1, pCheckItem);
   this->setKeyIndex(key, row); // remember which node key is in which row
 }
void CQCurrentValueTable::setValue (int row, C_FLOAT64 val) protected
Definition at line 95 of file CQCurrentValueTable.cpp.
References updateRowInTable().
 {
   this->updateRowInTable(row, val);
 }
void CQCurrentValueTable::slotCheckAllClicked () private slot
Definition at line 165 of file CQCurrentValueTable.cpp.
References setAllBoxesChecked().
Referenced by init().
 {
   this->setAllBoxesChecked();
 }
void CQCurrentValueTable::slotUncheckAllClicked () private slot
Definition at line 170 of file CQCurrentValueTable.cpp.
References setAllBoxesUnchecked().
Referenced by init().
 {
   this->setAllBoxesUnchecked();
 }
void CQCurrentValueTable::tableValueChanged (int row, int column) private slot
This slot is caled whenever a value in the table changes, i.e. whenever a species is activated or deactived by it's checkbox. This information is broadcasted by emitting another signal which contains the row number.
Definition at line 200 of file CQCurrentValueTable.cpp.
References valueChanged().
Referenced by init().
 {
   emit valueChanged(row);
 }
void CQCurrentValueTable::updateRowInTable (int row, C_FLOAT64 val)
Definition at line 80 of file CQCurrentValueTable.cpp.
References mpTable.
Referenced by setValue(), and CQLayoutMainWindow::updateValueTable().
 {
   if (this->mpTable->item(row, 1) == NULL)
     {
       this->mpTable->setItem(row, 1, new QTableWidgetItem(QString::number(val)));
     }
   else
     {
       this->mpTable->item(row, 1)->setText(QString::number(val));
     }
 }
void CQCurrentValueTable::valueChanged (int row) signal
Referenced by tableValueChanged().
QHeaderView * CQCurrentValueTable::verticalHeader ()
Definition at line 190 of file CQCurrentValueTable.cpp.
References mpTable.
Referenced by init().
 {
   return this->mpTable->verticalHeader();
 }
Member Data Documentation
std::map<int, std::string> CQCurrentValueTable::mIndexMap protected
Definition at line 32 of file CQCurrentValueTable.h.
Referenced by getKeyForRow(), and setKeyIndex().
QPushButton* CQCurrentValueTable::mpCheckAllButton protected
Definition at line 34 of file CQCurrentValueTable.h.
Referenced by init().
QTableWidget* CQCurrentValueTable::mpTable protected
Definition at line 33 of file CQCurrentValueTable.h.
Referenced by getValueForRow(), init(), numRows(), setAllBoxesChecked(), setNumCols(), setNumRows(), setRowInTable(), updateRowInTable(), and verticalHeader().
QPushButton* CQCurrentValueTable::mpUncheckAllButton protected
Definition at line 35 of file CQCurrentValueTable.h.
Referenced by init().
The documentation for this class was generated from the following files:
CQCurrentValueTable.h
CQCurrentValueTable.cpp