COPASI API: CCopasiXMLParser::ModelParameterElement Class Reference
CCopasiXMLParser::ModelParameterElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ModelParameterElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ModelParameterElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { ModelParameter = 0, InitialExpression }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 10 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ModelParameterElement::Element private
Enum of invoked parsers
Enumerator
ModelParameter
InitialExpression
Definition at line 18 of file CCopasiXMLParser.h.
 {
Constructor & Destructor Documentation
CCopasiXMLParser::ModelParameterElement::ModelParameterElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 502 of file ListOfModelParameterSets.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ModelParameterElement::~ModelParameterElement () virtual
Destructor
Definition at line 507 of file ListOfModelParameterSets.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::ModelParameterElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 604 of file ListOfModelParameterSets.cpp.
References SCopasiXMLParserCommon::CharacterData, CCopasiMessage::EXCEPTION, CCopasiMessage::getLastMessage(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentModelParameter, CModelParameter::setInitialExpression(), CCopasiMessage::size(), START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case ModelParameter:
         if (strcmp(pszName, "ModelParameter"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ModelParameter", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mLastKnownElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case InitialExpression:
         if (strcmp(pszName, "InitialExpression"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "InitialExpression", mParser.getCurrentLineNumber());
         {
           size_t Size = CCopasiMessage::size();
           mCommon.pCurrentModelParameter->setInitialExpression(mCommon.CharacterData);
           // Remove error messages created by setExpression as this may fail
           // due to incomplete model specification at this time.
           while (CCopasiMessage::size() > Size)
             CCopasiMessage::getLastMessage();
         }
         mCurrentElement = ModelParameter;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ModelParameterElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 510 of file ListOfModelParameterSets.cpp.
References C_FLOAT64, CModelParameter::Compartment, CCopasiMessage::EXCEPTION, CModelEntity::FIXED, CCopasiXMLParser::mCommon, MCXML, SCopasiXMLParserCommon::ModelParameterGroupStack, CExpatTemplate< CExpat >::mParser, CModelParameter::ParticleNumbers, SCopasiXMLParserCommon::pCurrentModelParameter, CModelParameter::ReactionParameter, CModelParameter::setCN(), CModelParameter::setSimulationType(), CModelParameter::setValue(), CModelParameter::Species, toEnum(), CModelParameter::TypeNames, CModelParameter::unknown, UNKNOWN_ELEMENT, and CModelEntity::XMLStatus.
 {
   const char * CN;
   const char * pValue;
   C_FLOAT64 Value = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
   const char * pType;
   CModelParameter::Type Type;
   const char * pSimulationType;
   CModelEntity::Status SimulationType;
   mpCurrentHandler = NULL;
   mCurrentElement = mLastKnownElement;
   while (mpCurrentHandler == NULL)
     {
       mCurrentElement++; /* We should always be on the next element */
       switch (mCurrentElement)
         {
           case ModelParameter:
             if (strcmp(pszName, "ModelParameter"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                              pszName, "ModelParameter", mParser.getCurrentLineNumber());
             mLastKnownElement = ModelParameter;
             // Element specific code.
             CN = mParser.getAttributeValue("cn", papszAttrs);
             pValue = mParser.getAttributeValue("value", papszAttrs);
             pType = mParser.getAttributeValue("type", papszAttrs);
             pSimulationType = mParser.getAttributeValue("simulationType", papszAttrs);
             if (pValue != NULL)
               {
                 Value = CCopasiXMLInterface::DBL(pValue);
               }
             Type = toEnum(pType, CModelParameter::TypeNames, CModelParameter::unknown);
             switch (Type)
               {
                 case CModelParameter::Species:
                   mCommon.pCurrentModelParameter = new CModelParameterSpecies(mCommon.ModelParameterGroupStack.top());
                   break;
                 case CModelParameter::Compartment:
                   mCommon.pCurrentModelParameter = new CModelParameterCompartment(mCommon.ModelParameterGroupStack.top());
                   break;
                 case CModelParameter::ReactionParameter:
                   mCommon.pCurrentModelParameter = new CModelParameterReactionParameter(mCommon.ModelParameterGroupStack.top());
                   break;
                 default:
                   mCommon.pCurrentModelParameter = new CModelParameter(mCommon.ModelParameterGroupStack.top(), Type);
                   break;
               }
             mCommon.pCurrentModelParameter->setCN(std::string(CN));
             SimulationType = toEnum(pSimulationType, CModelEntity::XMLStatus, CModelEntity::FIXED);
             mCommon.pCurrentModelParameter->setSimulationType(SimulationType);
             mCommon.pCurrentModelParameter->setValue(Value, CModelParameter::ParticleNumbers);
             return;
           case InitialExpression:
             if (!strcmp(pszName, "InitialExpression"))
               mpCurrentHandler = &mParser.mCharacterDataElement;
             break;
           default:
             mCurrentElement = UNKNOWN_ELEMENT;
             mpCurrentHandler = &mParser.mUnknownElement;
             break;
         }
     }
   mParser.pushElementHandler(mpCurrentHandler);
   if (mpCurrentHandler != &mParser.mUnknownElement)
     {
       mLastKnownElement = mCurrentElement;
     }
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
ListOfModelParameterSets.cpp