COPASI API: CLBoundingBox Class Reference
CLBoundingBox Class Reference
#include <CLBase.h>
Public Member Functions
CLBoundingBox ()
CLBoundingBox (const CLPoint &p, const CLDimensions &d)
CLBoundingBox (const BoundingBox &bb)
CLPoint getCenter () const
const CLDimensions & getDimensions () const
CLDimensions & getDimensions ()
const CLPoint & getPosition () const
CLPoint & getPosition ()
BoundingBox getSBMLBoundingBox () const
virtual void moveBy (const CLPoint &p)
void scale (const double &scaleFactor)
void setDimensions (const CLDimensions &d)
void setPosition (const CLPoint &p)
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
CLDimensions mDimensions
CLPoint mPosition
Protected Attributes inherited from CLBase
std::string mTag
Friends
std::ostream & operator<< (std::ostream &os, const CLBoundingBox &bb)
Detailed Description
This class describes a bounding box.
Definition at line 244 of file CLBase.h.
Constructor & Destructor Documentation
CLBoundingBox::CLBoundingBox () inline
Definition at line 254 of file CLBase.h.
     : mPosition(), mDimensions() {};
CLBoundingBox::CLBoundingBox (const CLPoint & p, const CLDimensions & d) inline
Definition at line 257 of file CLBase.h.
     : mPosition(p), mDimensions(d) {};
CLBoundingBox::CLBoundingBox (const BoundingBox & bb)
constructor from libsbml object
Definition at line 55 of file CLBase.cpp.
   : mPosition(*bb.getPosition()),
     mDimensions(*bb.getDimensions())
 {}
Member Function Documentation
CLPoint CLBoundingBox::getCenter () const inline
Definition at line 269 of file CLBase.h.
References CLDimensions::getHeight(), CLDimensions::getWidth(), CLPoint::getX(), CLPoint::getY(), mDimensions, and mPosition.
Referenced by CCopasiSpringLayout::borderProjection(), and CCopasiSpringLayout::finalizeState().
 {return CLPoint(mPosition.getX() + 0.5 * mDimensions.getWidth(), mPosition.getY() + 0.5 * mDimensions.getHeight());};
const CLDimensions& CLBoundingBox::getDimensions () const inline
Definition at line 266 of file CLBase.h.
References mDimensions.
Referenced by CLabel::adaptToHeight(), addToPath(), adjustPosition(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateAndAssignBounds(), CLayout::calculateBoundingBox(), CQGLNetworkPainter::checkCurve(), CLLayoutRenderer::convert_to_absolute(), CCopasiSpringLayout::createLayout(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_image(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_rectangle(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), CLGraphicalObject::getDimensions(), getFont(), CLGraphicalObject::getHeight(), getLinearGradient(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), getPath(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), getRadialGradient(), CLGraphicalObject::getWidth(), CLLayoutRenderer::map_arrow_head(), moveToPoint(), compareGraphicalObjectsBySize::operator()(), CCopasiXML::saveBoundingBox(), CLGraphicalObject::setHeight(), CLGraphicalObject::setWidth(), CLLineEnding::toSBML(), and CLLayoutRenderer::update_textures_and_colors().
 {return mDimensions;};
CLDimensions& CLBoundingBox::getDimensions () inline
Definition at line 270 of file CLBase.h.
References mDimensions.
 {return mDimensions;};
const CLPoint& CLBoundingBox::getPosition () const inline
Definition at line 265 of file CLBase.h.
References mPosition.
Referenced by addToPath(), adjustPosition(), CQGLLayoutPainter::calculateAndAssignBounds(), CLayout::calculateAndAssignBounds(), CLayout::calculateBoundingBox(), CQGLNetworkPainter::checkCurve(), CLLayoutRenderer::convert_to_absolute(), CQLabelGraphicsItem::CQLabelGraphicsItem(), CLLayoutRenderer::draw_datapoints(), CLLayoutRenderer::draw_ellipse(), CLLayoutRenderer::draw_group(), CLLayoutRenderer::draw_layout(), CLLayoutRenderer::draw_selection_box(), CLLayoutRenderer::draw_text(), fillItemFromEllipse(), fillItemFromImage(), fillItemFromRectangle(), fillItemFromText(), getLinearGradient(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), getPath(), CQGLNetworkPainter::getPointNearCircle(), CQGLNetworkPainter::getPointOnCircle(), CQGLNetworkPainter::getPointOnRectangle(), CLGraphicalObject::getPosition(), getRadialGradient(), CLGraphicalObject::getX(), CLGraphicalObject::getY(), CLLayoutRenderer::move_graphical_object(), moveToPoint(), CCopasiXML::saveBoundingBox(), CLabel::scalePosition(), CLGraphicalObject::setX(), CLGraphicalObject::setY(), and CLLineEnding::toSBML().
 {return mPosition;};
CLPoint& CLBoundingBox::getPosition () inline
Definition at line 268 of file CLBase.h.
References mPosition.
 {return mPosition;};
BoundingBox CLBoundingBox::getSBMLBoundingBox () const
convert to sbml bounding box
Definition at line 60 of file CLBase.cpp.
References CLDimensions::getHeight(), CLDimensions::getWidth(), CLPoint::getX(), CLPoint::getY(), mDimensions, and mPosition.
Referenced by CLGraphicalObject::exportToSBML().
 {
   return BoundingBox(new LayoutPkgNamespaces(), "", mPosition.getX(), mPosition.getY(),
                      mDimensions.getWidth(), mDimensions.getHeight());
 }
virtual void CLBoundingBox::moveBy (const CLPoint & p) inline virtual
Reimplemented from CLBase.
Definition at line 275 of file CLBase.h.
References CLPoint::moveBy(), and mPosition.
Referenced by CLGraphicalObject::moveBy().
   {
     mPosition.moveBy(p);
   };
void CLBoundingBox::scale (const double & scaleFactor) inline
Definition at line 285 of file CLBase.h.
References mDimensions, mPosition, CLPoint::scale(), and CLDimensions::scale().
Referenced by CGraphNode::scale().
 {mPosition.scale(scaleFactor); mDimensions.scale(scaleFactor);}
void CLBoundingBox::setDimensions (const CLDimensions & d) inline
Definition at line 273 of file CLBase.h.
References mDimensions.
Referenced by CLabel::adaptToHeight(), CLGraphicalObject::setDimensions(), and CCopasiXMLParser::BoundingBoxElement::start().
 {mDimensions = d;};
void CLBoundingBox::setPosition (const CLPoint & p) inline
Definition at line 272 of file CLBase.h.
References mPosition.
Referenced by CLLayoutRenderer::draw_layout(), CLGraphicalObject::setPosition(), and CCopasiXMLParser::BoundingBoxElement::start().
 {mPosition = p;};
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLBoundingBox & bb) friend
insert operator
Definition at line 80 of file CLBase.cpp.
 {
   os << "[" << bb.mPosition << bb.mDimensions << "]";
   return os;
 }
Member Data Documentation
CLDimensions CLBoundingBox::mDimensions protected
Definition at line 250 of file CLBase.h.
Referenced by getCenter(), getDimensions(), getSBMLBoundingBox(), operator<<(), scale(), and setDimensions().
CLPoint CLBoundingBox::mPosition protected
Definition at line 248 of file CLBase.h.
Referenced by getCenter(), getPosition(), getSBMLBoundingBox(), moveBy(), operator<<(), scale(), and setPosition().
The documentation for this class was generated from the following files:
CLBase.h
CLBase.cpp