COPASI API: CLsodaMethod Class Reference
CLsodaMethod Class Reference
#include <CLsodaMethod.h>
Classes
struct Data
Public Member Functions
CLsodaMethod (const CLsodaMethod &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
virtual void evalF (const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
virtual void evalJ (const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *ml, const C_INT *mu, C_FLOAT64 *pd, const C_INT *nRowPD)
virtual void evalR (const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *nr, C_FLOAT64 *r)
virtual void start (const CState *initialState)
virtual void stateChanged ()
virtual Status step (const double &deltaT)
~CLsodaMethod ()
Public Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CTrajectoryMethod &src, const CCopasiContainer *pParent=NULL)
const CVector< C_INT > & getRoots () const
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setCurrentState (CState *currentState)
void setProblem (CTrajectoryProblem *problem)
~CTrajectoryMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Member Functions
static void EvalF (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, C_FLOAT64 *ydot)
static void EvalJ (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *ml, const C_INT *mu, C_FLOAT64 *pd, const C_INT *nRowPD)
static void EvalR (const C_INT *n, const C_FLOAT64 *t, const C_FLOAT64 *y, const C_INT *nr, C_FLOAT64 *r)
Static Public Member Functions inherited from CTrajectoryMethod
static CTrajectoryMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::deterministic)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types
enum RootMasking { NONE = 0, ALL, DISCRETE }
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions
CLsodaMethod (const CCopasiMethod::SubType &subType=deterministic, const CCopasiContainer *pParent=NULL)
void destroyRootMask ()
Protected Member Functions inherited from CTrajectoryMethod
CTrajectoryMethod (const CCopasiMethod::SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes
C_INT mLsodaStatus
CState mMethodState
bool mNoODE
CModel * mpModel
bool * mpReducedModel
RootMasking mRootMasking
C_FLOAT64 mTime
Protected Attributes inherited from CTrajectoryMethod
CState * mpCurrentState
CTrajectoryProblem * mpProblem
CVector< C_INT > mRoots
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void createRootMask ()
void initializeParameter ()
void maskRoots (CVectorCore< C_FLOAT64 > &rootValues)
Status peekAhead ()
Private Attributes
CVector< C_FLOAT64 > mAtol
Data mData
CVector< bool > mDiscreteRoots
C_FLOAT64 mDummy
CVector< C_FLOAT64 > mDWork
std::ostringstream mErrorMsg
CVector< C_INT > mIWork
C_INT mJType
CLSODA mLSODA
CLSODAR mLSODAR
C_INT mNumRoots
C_FLOAT64 * mpAbsoluteTolerance
bool mPeekAheadMode
unsigned C_INT32 * mpMaxInternalSteps
C_FLOAT64 * mpRelativeTolerance
unsigned C_INT32 mRootCounter
CVector< bool > mRootMask
C_FLOAT64 mRtol
C_INT mState
C_FLOAT64 mTargetTime
C_FLOAT64 * mY
CVector< C_FLOAT64 > mYdot
Friends
CTrajectoryMethod * CTrajectoryMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CTrajectoryMethod
enum Status { FAILURE = -1, NORMAL = 0, ROOT = 1 }
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 28 of file CLsodaMethod.h.
Member Enumeration Documentation
enum CLsodaMethod::RootMasking protected
Enumerator
NONE
ALL
DISCRETE
Definition at line 42 of file CLsodaMethod.h.
   {
     NONE = 0,
     ALL,
     DISCRETE
   };
Constructor & Destructor Documentation
CLsodaMethod::CLsodaMethod (const CCopasiMethod::SubType & subType = deterministic, const CCopasiContainer * pParent = NULL) protected
Default constructor.
Parameters
const CCopasiMethod::SubType & subType (default: deterministic)
const CCopasiContainer * pParent (default: NULL)
Definition at line 25 of file CLsodaMethod.cpp.
References CLsodaMethod::Data::dim, initializeParameter(), mData, and CLsodaMethod::Data::pMethod.
                                                             :
   CTrajectoryMethod(subType, pParent),
   mMethodState(),
   mY(NULL),
   mRootMask(),
   mTargetTime(0.0),
   mRootCounter(0),
   mPeekAheadMode(false)
 {
   assert((void *) &mData == (void *) &mData.dim);
   mData.pMethod = this;
   initializeParameter();
 }
CLsodaMethod::CLsodaMethod (const CLsodaMethod & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CLsodaMethod & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 41 of file CLsodaMethod.cpp.
References CLsodaMethod::Data::dim, initializeParameter(), mData, and CLsodaMethod::Data::pMethod.
                                                             :
   CTrajectoryMethod(src, pParent),
   mMethodState(),
   mY(NULL),
   mRootMask(src.mRootMask),
   mTargetTime(src.mTargetTime),
   mRootCounter(src.mRootCounter),
   mPeekAheadMode(src.mPeekAheadMode)
 {
   assert((void *) &mData == (void *) &mData.dim);
   mData.pMethod = this;
   initializeParameter();
 }
CLsodaMethod::~CLsodaMethod ()
Destructor.
Definition at line 57 of file CLsodaMethod.cpp.
 {}
Member Function Documentation
void CLsodaMethod::createRootMask () private
Create a mask which hides all roots being constant and zero.
Definition at line 608 of file CLsodaMethod.cpp.
References ALL, CVectorCore< CType >::array(), C_FLOAT64, CModel::calculateRootDerivatives(), CModel::evaluateRoots(), min, mMethodState, mpAbsoluteTolerance, mpModel, mpReducedModel, mRootMask, mRootMasking, CTrajectoryMethod::mRoots, CVector< CType >::resize(), CModel::setState(), CVectorCore< CType >::size(), and CModel::updateSimulatedValues().
Referenced by step().
 {
   size_t NumRoots = mRoots.size();
   mRootMask.resize(NumRoots);
   CVector< C_FLOAT64 > RootValues;
   RootValues.resize(NumRoots);
   CVector< C_FLOAT64 > RootDerivatives;
   RootDerivatives.resize(NumRoots);
   mpModel->setState(mMethodState);
   if (*mpReducedModel)
     {
       mpModel->updateSimulatedValues(*mpReducedModel);
     }
   mpModel->evaluateRoots(RootValues, true);
   mpModel->calculateRootDerivatives(RootDerivatives);
   bool *pMask = mRootMask.array();
   bool *pMaskEnd = pMask + mRootMask.size();
   C_FLOAT64 * pRootValue = RootValues.array();
   C_FLOAT64 * pRootDerivative = RootDerivatives.array();
   for (; pMask != pMaskEnd; ++pMask, ++pRootValue, ++pRootDerivative)
     {
       *pMask = (fabs(*pRootDerivative) < *mpAbsoluteTolerance ||
                 fabs(*pRootValue) < 1e3 * std::numeric_limits< C_FLOAT64 >::min()) ? true : false;
     }
   mRootMasking = ALL;
 }
void CLsodaMethod::destroyRootMask () protected
Destroy the mask which hides all roots being constant and zero.
Definition at line 641 of file CLsodaMethod.cpp.
References mRootMask, mRootMasking, NONE, and CVector< CType >::resize().
Referenced by CTrajectoryMethodDsaLsodar::fireReaction(), start(), stateChanged(), and step().
 {
   mRootMask.resize(0);
   mRootMasking = NONE;
 }
bool CLsodaMethod::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Reimplemented in CTrajectoryMethodDsaLsodar.
Definition at line 150 of file CLsodaMethod.cpp.
References initializeParameter().
Referenced by CTrajectoryMethodDsaLsodar::elevateChildren().
 {
   initializeParameter();
   return true;
 }
void CLsodaMethod::EvalF (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) static
This evaluates the derivatives
Definition at line 528 of file CLsodaMethod.cpp.
References evalF(), and CLsodaMethod::Data::pMethod.
Referenced by step().
 {static_cast<Data *>((void *) n)->pMethod->evalF(t, y, ydot);}
void CLsodaMethod::evalF (const C_FLOAT64 * t, const C_FLOAT64 * y, C_FLOAT64 * ydot) virtual
Reimplemented in CTrajectoryMethodDsaLsodar.
Definition at line 531 of file CLsodaMethod.cpp.
References CModel::calculateDerivatives(), CModel::calculateDerivativesX(), mMethodState, mNoODE, mpModel, mpReducedModel, CModel::setState(), CState::setTime(), and CModel::updateSimulatedValues().
Referenced by EvalF(), and stateChanged().
 {
   // If we have no ODEs add a constant one.
   if (mNoODE)
     {
       *ydot = 1.0;
       return;
     }
   mMethodState.setTime(*t);
   mpModel->setState(mMethodState);
   mpModel->updateSimulatedValues(*mpReducedModel);
   if (*mpReducedModel)
     mpModel->calculateDerivativesX(ydot);
   else
     mpModel->calculateDerivatives(ydot);
   return;
 }
void CLsodaMethod::EvalJ (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * ml, const C_INT * mu, C_FLOAT64 * pd, const C_INT * nRowPD) static
This evaluates the Jacobian
Definition at line 582 of file CLsodaMethod.cpp.
References evalJ(), and CLsodaMethod::Data::pMethod.
Referenced by step().
 {static_cast<Data *>((void *) n)->pMethod->evalJ(t, y, ml, mu, pd, nRowPD);}
void CLsodaMethod::evalJ (const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * ml, const C_INT * mu, C_FLOAT64 * pd, const C_INT * nRowPD) virtual
Definition at line 587 of file CLsodaMethod.cpp.
Referenced by EvalJ().
 {
   // TODO Implement me.
 }
void CLsodaMethod::EvalR (const C_INT * n, const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * nr, C_FLOAT64 * r) static
This evaluates the roots
Definition at line 553 of file CLsodaMethod.cpp.
References evalR(), and CLsodaMethod::Data::pMethod.
Referenced by step().
 {static_cast<Data *>((void *) n)->pMethod->evalR(t, y, nr, r);}
void CLsodaMethod::evalR (const C_FLOAT64 * t, const C_FLOAT64 * y, const C_INT * nr, C_FLOAT64 * r) virtual
Reimplemented in CTrajectoryMethodDsaLsodar.
Definition at line 557 of file CLsodaMethod.cpp.
References C_INT, CModel::evaluateRoots(), maskRoots(), mMethodState, mpModel, mpReducedModel, mRootMasking, CTrajectoryMethod::mRoots, NONE, CModel::setState(), CState::setTime(), CVectorCore< CType >::size(), and CModel::updateSimulatedValues().
Referenced by EvalR().
 {
   assert(*nr == (C_INT) mRoots.size());
   mMethodState.setTime(*t);
   mpModel->setState(mMethodState);
   if (*mpReducedModel)
     {
       mpModel->updateSimulatedValues(*mpReducedModel);
     }
   CVectorCore< C_FLOAT64 > RootValues(*nr, r);
   mpModel->evaluateRoots(RootValues, true);
   if (mRootMasking != NONE)
     {
       maskRoots(RootValues);
     }
 };
void CLsodaMethod::initializeParameter () private
Initialize the method parameter
Definition at line 60 of file CLsodaMethod.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CModel::getCompartments(), CCopasiDataModel::getModel(), CCopasiObject::getObjectDataModel(), CCopasiParameterGroup::getParameter(), CModel::getQuantity2NumberFactor(), CCopasiParameter::getValue(), max, mpAbsoluteTolerance, mpMaxInternalSteps, mpReducedModel, mpRelativeTolerance, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CCopasiParameterGroup::removeParameter(), CCopasiVector< T >::size(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by CLsodaMethod(), and elevateChildren().
 {
   CCopasiParameter *pParm;
   mpReducedModel =
     assertParameter("Integrate Reduced Model", CCopasiParameter::BOOL, (bool) false)->getValue().pBOOL;
   mpRelativeTolerance =
     assertParameter("Relative Tolerance", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0e-6)->getValue().pUDOUBLE;
   mpAbsoluteTolerance =
     assertParameter("Absolute Tolerance", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.0e-12)->getValue().pUDOUBLE;
   mpMaxInternalSteps =
     assertParameter("Max Internal Steps", CCopasiParameter::UINT, (unsigned C_INT32) 10000)->getValue().pUINT;
   // Check whether we have a method with the old parameter names
   if ((pParm = getParameter("LSODA.RelativeTolerance")) != NULL)
     {
       *mpRelativeTolerance = *pParm->getValue().pUDOUBLE;
       removeParameter("LSODA.RelativeTolerance");
       if ((pParm = getParameter("LSODA.AbsoluteTolerance")) != NULL)
         {
           *mpAbsoluteTolerance = *pParm->getValue().pUDOUBLE;
           removeParameter("LSODA.AbsoluteTolerance");
         }
       if ((pParm = getParameter("LSODA.AdamsMaxOrder")) != NULL)
         {
           removeParameter("LSODA.AdamsMaxOrder");
         }
       if ((pParm = getParameter("LSODA.BDFMaxOrder")) != NULL)
         {
           removeParameter("LSODA.BDFMaxOrder");
         }
       if ((pParm = getParameter("LSODA.MaxStepsInternal")) != NULL)
         {
           *mpMaxInternalSteps = *pParm->getValue().pUINT;
           removeParameter("LSODA.MaxStepsInternal");
         }
     }
   // Check whether we have a method with "Use Default Absolute Tolerance"
   if ((pParm = getParameter("Use Default Absolute Tolerance")) != NULL)
     {
       C_FLOAT64 NewValue;
       if (*pParm->getValue().pBOOL)
         {
           // The default
           NewValue = 1.e-12;
         }
       else
         {
           C_FLOAT64 OldValue = *mpAbsoluteTolerance;
           CCopasiDataModel* pDataModel = getObjectDataModel();
           assert(pDataModel != NULL);
           CModel * pModel = pDataModel->getModel();
           if (pModel == NULL)
             // The default
             NewValue = 1.e-12;
           else
             {
               const CCopasiVectorNS< CCompartment > & Compartment = pModel->getCompartments();
               size_t i, imax;
               C_FLOAT64 Volume = std::numeric_limits< C_FLOAT64 >::max();
               for (i = 0, imax = Compartment.size(); i < imax; i++)
                 if (Compartment[i]->getValue() < Volume)
                   Volume = Compartment[i]->getValue();
               if (Volume == std::numeric_limits< C_FLOAT64 >::max())
                 // The default
                 NewValue = 1.e-12;
               else
                 // Invert the scaling as best as we can
                 NewValue = OldValue / (Volume * pModel->getQuantity2NumberFactor());
             }
         }
       *mpAbsoluteTolerance = NewValue;
       removeParameter("Use Default Absolute Tolerance");
     }
   // These parameters are no longer supported.
   removeParameter("Adams Max Order");
   removeParameter("BDF Max Order");
 }
void CLsodaMethod::maskRoots (CVectorCore< C_FLOAT64 > & rootValues) private
Mask roots which are constant and zero.
Parameters
CVectorCore< C_FLOAT64 > & rootValues
Definition at line 593 of file CLsodaMethod.cpp.
References CVectorCore< CType >::array(), C_FLOAT64, mRootMask, and CVectorCore< CType >::size().
Referenced by evalR().
 {
   const bool *pMask = mRootMask.array();
   const bool *pMaskEnd = pMask + mRootMask.size();
   C_FLOAT64 * pRoot = rootValues.array();
   for (; pMask != pMaskEnd; ++pMask, ++pRoot)
     {
       if (*pMask)
         {
           *pRoot = 1.0;
         }
     }
 }
CTrajectoryMethod::Status CLsodaMethod::peekAhead () private
Peek ahead to detect simultaneous roots.
Definition at line 647 of file CLsodaMethod.cpp.
References ALL, CVectorCore< CType >::array(), CState::beginIndependent(), C_FLOAT64, C_INT, CLsodaMethod::Data::dim, CTrajectoryMethod::FAILURE, CState::getTime(), mAtol, max, mData, mDWork, mIWork, mLSODAR, mMethodState, mpAbsoluteTolerance, mPeekAheadMode, mpRelativeTolerance, mRootMasking, CTrajectoryMethod::mRoots, mTargetTime, mTime, CTrajectoryMethod::NORMAL, CInternalSolver::resetState(), CTrajectoryMethod::ROOT, CInternalSolver::saveState(), CState::setTime(), CVectorCore< CType >::size(), and step().
Referenced by step().
 {
   // Save the current state
   mMethodState.setTime(mTime);
   CState StartState = mMethodState;
   CState ResetState = mMethodState;
   mLSODAR.saveState();
   CVector< C_FLOAT64 > ResetDWork = mDWork;
   CVector< C_INT > ResetIWork = mIWork;
   mPeekAheadMode = true;
   Status PeekAheadStatus = ROOT;
   CVector< C_INT > CombinedRoots = mRoots;
   C_FLOAT64 MaxPeekAheadTime = std::max(mTargetTime, mTime * (1.0 + 2.0 * *mpRelativeTolerance));
   while (mPeekAheadMode)
     {
       switch (step(MaxPeekAheadTime - mTime))
         {
           case ROOT:
           {
             // Check whether the new state is within the tolerances
             C_FLOAT64 * pOld = StartState.beginIndependent();
             C_FLOAT64 * pOldEnd = pOld + mData.dim;
             C_FLOAT64 * pNew = mMethodState.beginIndependent();
             C_FLOAT64 * pAtol = mAtol.array();
             for (; pOld != pOldEnd; ++pOld, ++pNew, ++pAtol)
               {
                 if ((2.0 * fabs(*pNew - *pOld) > (fabs(*pNew) + fabs(*pOld)) * *mpRelativeTolerance) &&
                     fabs(*pNew) > *pAtol &&
                     fabs(*pOld) > *pAtol)
                   {
                     break;
                   }
               }
             if (pOld != pOldEnd ||
                 (mTime > StartState.getTime() * (1.0 + *mpRelativeTolerance) &&
                  fabs(mTime) > *mpAbsoluteTolerance &&
                  fabs(StartState.getTime()) > *mpAbsoluteTolerance))
               {
                 mPeekAheadMode = false;
               }
             else
               {
                 ResetState = mMethodState;
                 mLSODAR.saveState();
                 ResetDWork = mDWork;
                 ResetIWork = mIWork;
                 // Combine all the roots
                 C_INT * pRoot = mRoots.array();
                 C_INT * pRootEnd = pRoot + mRoots.size();
                 C_INT * pCombinedRoot = CombinedRoots.array();
                 for (; pRoot != pRootEnd; ++pRoot, ++pCombinedRoot)
                   {
                     if (*pRoot > 0)
                       {
                         *pCombinedRoot = 1;
                       }
                   }
               }
           }
           break;
           case FAILURE:
             mPeekAheadMode = false;
             PeekAheadStatus = FAILURE;
             break;
           case NORMAL:
             if (mRootMasking != ALL)
               {
                 mPeekAheadMode = false;
               }
             break;
         }
     }
   // Reset the integrator to the saved state
   mMethodState = ResetState;
   mTime = mMethodState.getTime();
   mLSODAR.resetState();
   mDWork = ResetDWork;
   mIWork = ResetIWork;
   mPeekAheadMode = false;
   mRoots = CombinedRoots;
   return PeekAheadStatus;
 }
void CLsodaMethod::start (const CState * initialState) virtual
This instructs the method to prepare for integration starting with the initialState given.
Parameters
const CState * initialState
Reimplemented from CTrajectoryMethod.
Reimplemented in CTrajectoryMethodDsaLsodar.
Definition at line 448 of file CLsodaMethod.cpp.
References CVectorCore< CType >::array(), CState::beginIndependent(), C_INT, destroyRootMask(), CLsodaMethod::Data::dim, CCopasiProblem::getModel(), CModel::getNumDependentReactionMetabs(), CState::getNumIndependent(), CModel::getNumRoots(), CModel::getRootFinders(), CState::getTime(), CModel::initializeAtolVector(), mAtol, mData, mDiscreteRoots, mDummy, mDWork, mErrorMsg, mIWork, mJType, mLSODA, mLSODAR, mLsodaStatus, mMethodState, mNoODE, mNumRoots, mpAbsoluteTolerance, mPeekAheadMode, mpMaxInternalSteps, mpModel, CTrajectoryMethod::mpProblem, mpReducedModel, mpRelativeTolerance, mRootCounter, CTrajectoryMethod::mRoots, mRtol, mState, mTargetTime, mTime, mY, mYdot, CVector< CType >::resize(), and CInternalSolver::setOstream().
Referenced by CTrajectoryMethodDsaLsodar::start().
 {
   /* Retrieve the model to calculate */
   mpModel = mpProblem->getModel();
   /* Reset lsoda */
   mLsodaStatus = 1;
   mState = 1;
   mJType = 2;
   mErrorMsg.str("");
   /* Release previous state and make the initialState the current */
   mMethodState = *initialState;
   mTime = mMethodState.getTime();
   mTargetTime = mTime;
   mRootCounter = 0;
   mPeekAheadMode = false;
   mNumRoots = (C_INT) mpModel->getNumRoots();
   mRoots.resize(mNumRoots);
   destroyRootMask();
   if (*mpReducedModel)
     mData.dim = (C_INT) mMethodState.getNumIndependent();
   else
     mData.dim = (C_INT)(mMethodState.getNumIndependent() + mpModel->getNumDependentReactionMetabs());
   // When we have roots we need to add an artificial ODE dDummy/dt = 1
   if (mData.dim == 0 && mNumRoots != 0)
     {
       mData.dim = 1;
       mNoODE = true;
       mAtol.resize(1);
       mAtol[0] = *mpAbsoluteTolerance;
       mDummy = 0;
       mY = &mDummy;
     }
   else
     {
       mNoODE = false;
       mAtol = mpModel->initializeAtolVector(*mpAbsoluteTolerance, *mpReducedModel);
       mY = mMethodState.beginIndependent();
     }
   mYdot.resize(mData.dim);
   /* Configure lsoda(r) */
   mRtol = *mpRelativeTolerance;
   mDWork.resize(22 + mData.dim * std::max<C_INT>(16, mData.dim + 9) + 3 * mNumRoots);
   mDWork[4] = mDWork[5] = mDWork[6] = mDWork[7] = mDWork[8] = mDWork[9] = 0.0;
   mIWork.resize(20 + mData.dim);
   mIWork[4] = mIWork[6] = mIWork[9] = 0;
   mIWork[5] = *mpMaxInternalSteps;
   mIWork[7] = 12;
   mIWork[8] = 5;
   if (mNumRoots > 0)
     {
       mLSODAR.setOstream(mErrorMsg);
       mDiscreteRoots.resize(mNumRoots);
       CMathTrigger::CRootFinder * const* ppRootFinder = mpModel->getRootFinders().array();
       CMathTrigger::CRootFinder * const* ppRootFinderEnd = ppRootFinder + mNumRoots;
       bool * pDiscrete = mDiscreteRoots.array();
       for (; ppRootFinder != ppRootFinderEnd; ++ppRootFinder, ++pDiscrete)
         {
           *pDiscrete = (*ppRootFinder)->isDiscrete();
         }
     }
   else
     {
       mLSODA.setOstream(mErrorMsg);
     }
   return;
 }
void CLsodaMethod::stateChanged () virtual
Inform the trajectory method that the state has changed outside its control
Reimplemented from CTrajectoryMethod.
Reimplemented in CTrajectoryMethodDsaLsodar.
Definition at line 157 of file CLsodaMethod.cpp.
References CVectorCore< CType >::array(), CState::beginFixed(), CState::beginIndependent(), C_FLOAT64, destroyRootMask(), CLsodaMethod::Data::dim, CState::endFixed(), evalF(), CState::getTime(), mData, mLsodaStatus, mMethodState, mNoODE, CTrajectoryMethod::mpCurrentState, mPeekAheadMode, mTime, and mY.
Referenced by CTrajectoryMethodDsaLsodar::stateChanged().
 {
   if (!mNoODE && mLsodaStatus != 1)
     {
       // Compare the independent state variables
       // This an be done directly by comparing mMethodState and *mpCurrentState
       C_FLOAT64 *pMethod = mY;
       C_FLOAT64 *pMethodEnd = pMethod + mData.dim;
       C_FLOAT64 *pCurrent = mpCurrentState->beginIndependent();
       for (; pMethod != pMethodEnd; ++pMethod, ++pCurrent)
         {
           // We may need to use the absolute and relative tolerance
           if (*pMethod != *pCurrent)
             {
               mLsodaStatus = 1;
               break;
             }
         }
       // Bug 2106 It is not sufficient to check for the state variables we also need
       // to check for fixed values which are event targets.
       pMethod = mMethodState.beginFixed();
       pMethodEnd = mMethodState.endFixed();
       pCurrent = mpCurrentState->beginFixed();
       for (; pMethod != pMethodEnd; ++pMethod, ++pCurrent)
         {
           // We may need to use the absolute and relative tolerance
           if (*pMethod != *pCurrent)
             {
               mLsodaStatus = 1;
               break;
             }
         }
       if (mLsodaStatus != 1)
         {
           // Compare the rates of the independent state variables
           // we need to call evalF for mMethodState and *mpCurrentState and compare the returned rates.
           CVector< C_FLOAT64 > MethodRate(mData.dim);
           CVector< C_FLOAT64 > CurrentRate(mData.dim);
           evalF(&mTime, mY, MethodRate.array());
           mMethodState = *mpCurrentState;
           mTime = mMethodState.getTime();
           evalF(&mTime, mY, CurrentRate.array());
           pMethod = MethodRate.array();
           pMethodEnd = pMethod + mData.dim;
           pCurrent = CurrentRate.array();
           for (; pMethod != pMethodEnd; ++pMethod, ++pCurrent)
             {
               // We may need to use the absolute and relative tolerance
               if (*pMethod != *pCurrent)
                 {
                   mLsodaStatus = 1;
                   break;
                 }
             }
         }
     }
   mMethodState = *mpCurrentState;
   mTime = mMethodState.getTime();
   mPeekAheadMode = false;
   destroyRootMask();
 }
CTrajectoryMethod::Status CLsodaMethod::step (const double & deltaT) virtual
This instructs the method to calculate a time step of deltaT starting with the current state, i.e., the result of the previous step. The new state (after deltaT) is expected in the current state. The return value is the actual time step taken.
Parameters
const double & deltaT
Returns
Status status
Reimplemented from CTrajectoryMethod.
Reimplemented in CTrajectoryMethodDsaLsodar.
Definition at line 232 of file CLsodaMethod.cpp.
References ALL, CVectorCore< CType >::array(), C_FLOAT64, C_INT, createRootMask(), destroyRootMask(), CLsodaMethod::Data::dim, DISCRETE, EvalF(), EvalJ(), EvalR(), CCopasiMessage::EXCEPTION, CTrajectoryMethod::FAILURE, CState::getTime(), CState::isValid(), mAtol, MCTrajectoryMethod, mData, mDiscreteRoots, mDWork, mErrorMsg, mIWork, mJType, mLSODA, mLSODAR, mLsodaStatus, mMethodState, mNumRoots, CTrajectoryMethod::mpCurrentState, mPeekAheadMode, mpMaxInternalSteps, mRootCounter, mRootMask, mRootMasking, CTrajectoryMethod::mRoots, mRtol, mState, mTargetTime, mTime, mY, NONE, CTrajectoryMethod::NORMAL, peekAhead(), CTrajectoryMethod::ROOT, CState::setTime(), and CVectorCore< CType >::size().
Referenced by CTrajectoryMethodDsaLsodar::integrateDeterministicPart(), and peekAhead().
 {
   if (mData.dim == 0 && mNumRoots == 0) //just do nothing if there are no variables
     {
       mTime = mTime + deltaT;
       mMethodState.setTime(mTime);
       *mpCurrentState = mMethodState;
       return NORMAL;
     }
   C_FLOAT64 EndTime = mTime + deltaT;
   if (mTargetTime != EndTime)
     {
       // We have a new end time and reset the root counter.
       mTargetTime = EndTime;
       mRootCounter = 0;
     }
   else
     {
       // We are called with the same end time which means a root has previously been
       // found. We increase the root counter and check whether the limit is reached.
       mRootCounter++;
       if (mRootCounter > *mpMaxInternalSteps)
         {
           return FAILURE;
         }
     }
   C_INT ITOL = 2; // mRtol scalar, mAtol vector
   C_INT one = 1;
   C_INT DSize = (C_INT) mDWork.size();
   C_INT ISize = (C_INT) mIWork.size();
   // The return status of the integrator.
   Status Status = NORMAL;
   if (mRoots.size() > 0)
     {
       mLSODAR(&EvalF, //  1. evaluate F
               &mData.dim, //  2. number of variables
               mY, //  3. the array of current concentrations
               &mTime, //  4. the current time
               &EndTime, //  5. the final time
               &ITOL, //  6. error control
               &mRtol, //  7. relative tolerance array
               mAtol.array(), //  8. absolute tolerance array
               &mState, //  9. output by overshoot & interpolation
               &mLsodaStatus, // 10. the state control variable
               &one, // 11. further options (one)
               mDWork.array(), // 12. the double work array
               &DSize, // 13. the double work array size
               mIWork.array(), // 14. the int work array
               &ISize, // 15. the int work array size
               &EvalJ, // 16. evaluate J (not given)
               &mJType, // 17. type of j evaluation 2 internal full matrix
               &EvalR, // 18. evaluate constraint functions
               &mNumRoots, // 19. number of constraint functions g(i)
               mRoots.array()); // 20. integer array of length NG for output of root information
       // There exist situations where LSODAR reports status = 3, which are actually status = -33
       // Obviously the trivial case is where LSODAR did not advance at all, i.e, the start time
       // equals the current time. It may also happen that a very small steps has been taken in
       // we reset short before we reach the internal step limit.
       if (mLsodaStatus == 3 &&
           (mRootCounter > 0.99 * *mpMaxInternalSteps ||
            mTime == mpCurrentState->getTime()))
         {
           mLsodaStatus = -33;
           mRootCounter = 0;
         }
       switch (mLsodaStatus)
         {
           case -33:
             switch (mRootMasking)
               {
                 case NONE:
                 case DISCRETE:
                   // Reset the integrator to the state before the failed integration.
                   mMethodState = *mpCurrentState;
                   mTime = mMethodState.getTime();
                   mLsodaStatus = 1;
                   // Create a mask which hides all roots being constant and zero.
                   createRootMask();
                   break;
                 case ALL:
                   break;
               }
             break;
           case 3:
             // If mLsodaStatus == 3 we have found a root. This needs to be indicated to
             // the caller as it is not sufficient to rely on the fact that T < TOUT
             if (mLsodaStatus == 3)
               {
                 // It is sufficient to switch to 2. Eventual state changes due to events
                 // are indicated via the method stateChanged()
                 mLsodaStatus = 2;
                 Status = ROOT;
               }
             // To detect simultaneous roots we have to peek ahead, i.e., continue
             // integration until the state changes are larger that the relative
             if (!mPeekAheadMode)
               {
                 Status = peekAhead();
               }
             // The break statement is intentionally missing since we
             // have to continue to check the root masking state.
           default:
             switch (mRootMasking)
               {
                 case NONE:
                 case DISCRETE:
                   break;
                 case ALL:
                 {
                   const bool * pDiscrete = mDiscreteRoots.array();
                   bool * pMask = mRootMask.array();
                   bool * pMaskEnd = pMask + mNumRoots;
                   bool Destroy = true;
                   for (; pMask != pMaskEnd; ++pMask, ++pDiscrete)
                     {
                       if (*pMask)
{
                           if (*pDiscrete)
{
                               Destroy = false;
                             }
                           else
{
                               *pMask = false;
                             }
                         }
                     }
                   if (Destroy)
                     {
                       destroyRootMask();
                     }
                   else
                     {
                       mRootMasking = DISCRETE;
                     }
                   // We have to restart the integrator
                   mLsodaStatus = 1;
                 }
                 break;
               }
             break;
         }
     }
   else
     {
       mLSODA(&EvalF, //  1. evaluate F
              &mData.dim, //  2. number of variables
              mY, //  3. the array of current concentrations
              &mTime, //  4. the current time
              &EndTime, //  5. the final time
              &ITOL, //  6. error control
              &mRtol, //  7. relative tolerance array
              mAtol.array(), //  8. absolute tolerance array
              &mState, //  9. output by overshoot & interpolation
              &mLsodaStatus, // 10. the state control variable
              &one, // 11. further options (one)
              mDWork.array(), // 12. the double work array
              &DSize, // 13. the double work array size
              mIWork.array(), // 14. the int work array
              &ISize, // 15. the int work array size
              EvalJ, // 16. evaluate J (not given)
              &mJType);        // 17. the type of jacobian calculate (2)
     }
   // Why did we ignore this error?
   // if (mLsodaStatus == -1) mLsodaStatus = 2;
   mMethodState.setTime(mTime);
   if (!mPeekAheadMode)
     {
       *mpCurrentState = mMethodState;
     }
   if ((mLsodaStatus <= 0))
     {
       Status = FAILURE;
       mPeekAheadMode = false;
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 6, mErrorMsg.str().c_str());
     }
   if (!mMethodState.isValid())
     {
       Status = FAILURE;
       mPeekAheadMode = false;
       CCopasiMessage(CCopasiMessage::EXCEPTION, MCTrajectoryMethod + 25, mTime);
     }
   return Status;
 }
Friends And Related Function Documentation
CTrajectoryMethod* CTrajectoryMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
CVector< C_FLOAT64 > CLsodaMethod::mAtol private
A vector of absolute tolerances.
Definition at line 118 of file CLsodaMethod.h.
Referenced by peekAhead(), start(), and step().
Data CLsodaMethod::mData private
mData.dim is the dimension of the ODE system. mData.pMethod contains CLsodaMethod * this to be used in the static method EvalF
Definition at line 81 of file CLsodaMethod.h.
Referenced by CLsodaMethod(), peekAhead(), start(), stateChanged(), and step().
CVector< bool > CLsodaMethod::mDiscreteRoots private
A which indicates whether roots change only discretely.
Definition at line 180 of file CLsodaMethod.h.
Referenced by start(), and step().
C_FLOAT64 CLsodaMethod::mDummy private
A dummy variable if we do not have any ODEs
Definition at line 170 of file CLsodaMethod.h.
Referenced by start().
CVector< C_FLOAT64 > CLsodaMethod::mDWork private
LSODA C_FLOAT64 work area
Definition at line 143 of file CLsodaMethod.h.
Referenced by peekAhead(), start(), and step().
std::ostringstream CLsodaMethod::mErrorMsg private
Stream to capture LSODA error messages
Definition at line 123 of file CLsodaMethod.h.
Referenced by start(), and step().
CVector< C_INT > CLsodaMethod::mIWork private
LSODA C_INT work area
Definition at line 148 of file CLsodaMethod.h.
Referenced by peekAhead(), start(), and step().
C_INT CLsodaMethod::mJType private
The way LSODA calculates the jacobian
Definition at line 153 of file CLsodaMethod.h.
Referenced by start(), and step().
CLSODA CLsodaMethod::mLSODA private
The LSODA integrator
Definition at line 128 of file CLsodaMethod.h.
Referenced by start(), and step().
CLSODAR CLsodaMethod::mLSODAR private
The LSODA integrator
Definition at line 133 of file CLsodaMethod.h.
Referenced by peekAhead(), start(), and step().
C_INT CLsodaMethod::mLsodaStatus protected
LSODA state.
Definition at line 107 of file CLsodaMethod.h.
Referenced by CTrajectoryMethodDsaLsodar::fireReaction(), start(), stateChanged(), and step().
CState CLsodaMethod::mMethodState protected
A pointer to the current state in complete model view.
Definition at line 74 of file CLsodaMethod.h.
Referenced by CTrajectoryMethodDsaLsodar::calculatePropensities(), createRootMask(), CTrajectoryMethodDsaLsodar::doSingleStep(), evalF(), CTrajectoryMethodDsaLsodar::evalF(), evalR(), CTrajectoryMethodDsaLsodar::fireReaction(), CTrajectoryMethodDsaLsodar::integrateDeterministicPart(), peekAhead(), start(), CTrajectoryMethodDsaLsodar::start(), stateChanged(), CTrajectoryMethodDsaLsodar::stateChanged(), step(), and CTrajectoryMethodDsaLsodar::step().
bool CLsodaMethod::mNoODE protected
A Boolean value indication whether we have no ODEs
Definition at line 164 of file CLsodaMethod.h.
Referenced by evalF(), CTrajectoryMethodDsaLsodar::evalF(), start(), and stateChanged().
C_INT CLsodaMethod::mNumRoots private
Number of roots
Definition at line 96 of file CLsodaMethod.h.
Referenced by start(), and step().
C_FLOAT64* CLsodaMethod::mpAbsoluteTolerance private
A pointer to the value of "Absolute Tolerance"
Definition at line 63 of file CLsodaMethod.h.
Referenced by createRootMask(), initializeParameter(), peekAhead(), and start().
bool CLsodaMethod::mPeekAheadMode private
A Boolean indicating whether we are in peekAhead mode
Definition at line 204 of file CLsodaMethod.h.
Referenced by peekAhead(), start(), stateChanged(), and step().
unsigned C_INT32* CLsodaMethod::mpMaxInternalSteps private
A pointer to the value of "Max Internal Steps"
Definition at line 68 of file CLsodaMethod.h.
Referenced by initializeParameter(), start(), and step().
CModel* CLsodaMethod::mpModel protected
A pointer to the model
Definition at line 159 of file CLsodaMethod.h.
Referenced by CTrajectoryMethodDsaLsodar::calculatePropensities(), CTrajectoryMethodDsaLsodar::cleanup(), createRootMask(), CTrajectoryMethodDsaLsodar::doSingleStep(), evalF(), CTrajectoryMethodDsaLsodar::evalF(), evalR(), CTrajectoryMethodDsaLsodar::integrateDeterministicPart(), start(), and CTrajectoryMethodDsaLsodar::start().
bool* CLsodaMethod::mpReducedModel protected
A pointer to the value of "Integrate Reduced Model"
Definition at line 52 of file CLsodaMethod.h.
Referenced by createRootMask(), evalF(), CTrajectoryMethodDsaLsodar::evalF(), evalR(), initializeParameter(), CTrajectoryMethodDsaLsodar::integrateDeterministicPart(), and start().
C_FLOAT64* CLsodaMethod::mpRelativeTolerance private
A pointer to the value of "Relative Tolerance"
Definition at line 58 of file CLsodaMethod.h.
Referenced by initializeParameter(), peekAhead(), and start().
unsigned C_INT32 CLsodaMethod::mRootCounter private
Root counter to determine whether the internal step limit is exceeded.
Definition at line 199 of file CLsodaMethod.h.
Referenced by start(), and step().
CVector< bool > CLsodaMethod::mRootMask private
A mask which hides all roots being constant and zero.
Definition at line 175 of file CLsodaMethod.h.
Referenced by createRootMask(), destroyRootMask(), maskRoots(), and step().
RootMasking CLsodaMethod::mRootMasking protected
A Boolean flag indicating whether we should try masking roots
Definition at line 186 of file CLsodaMethod.h.
Referenced by createRootMask(), destroyRootMask(), evalR(), peekAhead(), and step().
C_FLOAT64 CLsodaMethod::mRtol private
Relative tolerance.
Definition at line 113 of file CLsodaMethod.h.
Referenced by start(), and step().
C_INT CLsodaMethod::mState private
The state of the integrator
Definition at line 138 of file CLsodaMethod.h.
Referenced by start(), and step().
C_FLOAT64 CLsodaMethod::mTargetTime private
Store the targeted end time to determine whether the internal step limit is exceeded.
Definition at line 193 of file CLsodaMethod.h.
Referenced by peekAhead(), start(), and step().
C_FLOAT64 CLsodaMethod::mTime protected
Current time.
Definition at line 102 of file CLsodaMethod.h.
Referenced by CTrajectoryMethodDsaLsodar::fireReaction(), peekAhead(), start(), stateChanged(), and step().
C_FLOAT64* CLsodaMethod::mY private
Pointer to the array with left hand side values.
Definition at line 86 of file CLsodaMethod.h.
Referenced by start(), stateChanged(), and step().
CVector< C_FLOAT64 > CLsodaMethod::mYdot private
Vector containing the derivatives after calling eval
Definition at line 91 of file CLsodaMethod.h.
Referenced by start().
The documentation for this class was generated from the following files:
CLsodaMethod.h
CLsodaMethod.cpp