COPASI API: CScanWidgetTask Class Reference
CScanWidgetTask Class Reference
#include <CScanWidgetTask.h>
Public Member Functions
CScanWidgetTask (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
virtual void load (const CScanProblem *pg)
virtual bool save (CScanProblem *pg) const
~CScanWidgetTask ()
Protected Attributes
const CModel * mpModel
CCopasiObject * mpObject
Private Slots
virtual void typeChanged (int n)
Private Member Functions
void init ()
Detailed Description
Definition at line 30 of file CScanWidgetTask.h.
Constructor & Destructor Documentation
CScanWidgetTask::CScanWidgetTask (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 32 of file CScanWidgetTask.cpp.
                                                                                   :
   QWidget(parent, f),
   mpObject(NULL),
   mpModel(NULL)
 {
   setObjectName(QString::fromUtf8(name));
   setupUi(this);
 }
CScanWidgetTask::~CScanWidgetTask ()
Definition at line 45 of file CScanWidgetTask.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CScanWidgetTask::init () private
Definition at line 50 of file CScanWidgetTask.cpp.
 {}
void CScanWidgetTask::load (const CScanProblem * pg) virtual
Definition at line 54 of file CScanWidgetTask.cpp.
References CCopasiTask::crosssection, CScanProblem::getContinueFromCurrentState(), CScanProblem::getOutputInSubtask(), CScanProblem::getSubtask(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, CCopasiTask::optimization, CCopasiTask::parameterFitting, CCopasiTask::sens, CCopasiTask::steadyState, CCopasiTask::timeCourse, and CCopasiTask::tssAnalysis.
Referenced by ScanWidget::loadTask().
 {
   CCopasiTask::Type type = pg->getSubtask();
   int n;
   switch (type)
     {
       case CCopasiTask::steadyState:
         n = 0;
         break;
       case CCopasiTask::timeCourse:
         n = 1;
         break;
       case CCopasiTask::mca:
         n = 2;
         break;
       case CCopasiTask::lyap:
         n = 3;
         break;
       case CCopasiTask::optimization:
         n = 4;
         break;
       case CCopasiTask::parameterFitting:
         n = 5;
         break;
       case CCopasiTask::sens:
         n = 6;
         break;
       case CCopasiTask::lna:
         n = 7;
         break;
       case CCopasiTask::crosssection:
         n = 8;
         break;
       case CCopasiTask::tssAnalysis:
         n = 9;
         break;
       default:
         n = 0;
         break;
     }
   comboType->setCurrentIndex(n);
   mpCheckContinue->setChecked(pg->getContinueFromCurrentState());
   checkOutput->setChecked(pg->getOutputInSubtask());
   return;
 }
bool CScanWidgetTask::save (CScanProblem * pg) const virtual
Definition at line 116 of file CScanWidgetTask.cpp.
References CCopasiTask::crosssection, CScanProblem::getContinueFromCurrentState(), CScanProblem::getOutputInSubtask(), CScanProblem::getSubtask(), CCopasiTask::lna, CCopasiTask::lyap, CCopasiTask::mca, CCopasiTask::optimization, CCopasiTask::parameterFitting, CCopasiTask::sens, CScanProblem::setContinueFromCurrentState(), CScanProblem::setOutputInSubtask(), CScanProblem::setSubtask(), CCopasiTask::steadyState, CCopasiTask::timeCourse, and CCopasiTask::tssAnalysis.
Referenced by ScanWidget::saveTask().
 {
   bool changed = false;
   int type = comboType->currentIndex();
   CCopasiTask::Type Type;
   switch (type)
     {
       case 0:
         Type = CCopasiTask::steadyState;
         break;
       case 1:
         Type = CCopasiTask::timeCourse;
         break;
       case 2:
         Type = CCopasiTask::mca;
         break;
       case 3:
         Type = CCopasiTask::lyap;
         break;
       case 4:
         Type = CCopasiTask::optimization;
         break;
       case 5:
         Type = CCopasiTask::parameterFitting;
         break;
       case 6:
         Type = CCopasiTask::sens;
         break;
       case 7:
         Type = CCopasiTask::lna;
         break;
       case 8:
         Type = CCopasiTask::crosssection;
         break;
       case 9:
         Type = CCopasiTask::tssAnalysis;
         break;
       default :
         Type = CCopasiTask::steadyState;
         break;
     }
   if (Type != pg->getSubtask())
     {
       pg->setSubtask(Type);
       changed = true;
     }
   if (pg->getContinueFromCurrentState() != mpCheckContinue->isChecked())
     {
       pg->setContinueFromCurrentState(mpCheckContinue->isChecked());
       changed = true;
     }
   if (pg->getOutputInSubtask() != checkOutput->isChecked())
     {
       pg->setOutputInSubtask(checkOutput->isChecked());
       changed = true;
     }
   return changed;
 }
void CScanWidgetTask::typeChanged (int n) private virtual slot
Definition at line 191 of file CScanWidgetTask.cpp.
 {
   switch (n)
     {
       case 1:
       case 8:
         checkOutput->setChecked(true);
         break;
       default:
         checkOutput->setChecked(false);
         break;
     }
 }
Member Data Documentation
const CModel* CScanWidgetTask::mpModel protected
Definition at line 43 of file CScanWidgetTask.h.
CCopasiObject* CScanWidgetTask::mpObject protected
Definition at line 42 of file CScanWidgetTask.h.
The documentation for this class was generated from the following files:
CScanWidgetTask.h
CScanWidgetTask.cpp