COPASI API: CCopasiMessage Class Reference
CCopasiMessage Class Reference
#include <CCopasiMessage.h>
Public Types
enum Type {
RAW = 0, TRACE = 1, COMMANDLINE = 2, WARNING = 3,
ERROR = 4, EXCEPTION = 5, RAW_FILTERED = 128, TRACE_FILTERED = 129,
COMMANDLINE_FILTERED = 130, WARNING_FILTERED = 131, ERROR_FILTERED = 132, EXCEPTION_FILTERED = 133
}
Public Member Functions
CCopasiMessage ()
CCopasiMessage (const CCopasiMessage &src)
CCopasiMessage (Type type, const char *format,...)
CCopasiMessage (Type type, size_t number,...)
const size_t & getNumber () const
const std::string & getText () const
const CCopasiMessage::Type & getType () const
CCopasiMessage & operator= (const CCopasiMessage &RHS)
~CCopasiMessage ()
Static Public Member Functions
static bool checkForMessage (const size_t &number)
static void clearDeque ()
static std::string getAllMessageText (const bool &chronological=true)
static CCopasiMessage getFirstMessage ()
static CCopasiMessage::Type getHighestSeverity ()
static CCopasiMessage getLastMessage ()
static const CCopasiMessage & peekFirstMessage ()
static const CCopasiMessage & peekLastMessage ()
static void setIsGUI (const bool &isGUI)
static size_t size ()
Private Member Functions
void handler (const bool &_throw=false)
void lineBreak ()
Private Attributes
size_t mNumber
std::string mText
CCopasiMessage::Type mType
Static Private Attributes
static bool IsGUI = false
static std::deque< CCopasiMessage > mMessageDeque
Detailed Description
Definition at line 78 of file CCopasiMessage.h.
Member Enumeration Documentation
enum CCopasiMessage::Type
Enumerator
RAW
TRACE
COMMANDLINE
WARNING
ERROR
EXCEPTION
RAW_FILTERED
TRACE_FILTERED
COMMANDLINE_FILTERED
WARNING_FILTERED
ERROR_FILTERED
EXCEPTION_FILTERED
Definition at line 81 of file CCopasiMessage.h.
   {
     RAW = 0,
     TRACE = 1,
     COMMANDLINE = 2,
     WARNING = 3,
     // In the case that ERROR is defined we have to remove its definition
     // temporarily.
 #ifdef ERROR
 # undef ERROR
 #endif
     ERROR = 4,
     EXCEPTION = 5,
     RAW_FILTERED = 128,
     TRACE_FILTERED = 129,
     COMMANDLINE_FILTERED = 130,
     WARNING_FILTERED = 131,
     ERROR_FILTERED = 132,
     EXCEPTION_FILTERED = 133
   };
Constructor & Destructor Documentation
CCopasiMessage::CCopasiMessage (void)
Default constructor. This creates a default error messages, which actually does nothing.
Definition at line 148 of file CCopasiMessage.cpp.
Referenced by getAllMessageText(), getFirstMessage(), getLastMessage(), peekFirstMessage(), and peekLastMessage().
                                   :
   mText(),
   mType(CCopasiMessage::RAW),
   mNumber(0)
 {}
CCopasiMessage::CCopasiMessage (const CCopasiMessage & src)
Copy constructor.
Parameters
const CCopasiMessage & src
Definition at line 154 of file CCopasiMessage.cpp.
                                                         :
   mText(src.mText),
   mType(src.mType),
   mNumber(src.mNumber)
 {}
CCopasiMessage::CCopasiMessage (CCopasiMessage::Type type, const char * format, ...)
Specified constructor. This creates a formated message.
Parameters
CCopasiMessage::Type type (RAW|TRACE|WARNING|ERROR)
const char * format (printf like format string)
... arguments like in printf
Definition at line 160 of file CCopasiMessage.cpp.
References C_INT32, handler(), INITIALTEXTSIZE, mNumber, mText, and mType.
 {
   C_INT32 TextSize = INITIALTEXTSIZE;
   C_INT32 Printed = 0;
   char *Text = NULL;
   Text = new char[TextSize + 1];
   va_list Arguments; // = NULL;
   va_start(Arguments, format);
   Printed = vsnprintf(Text, TextSize, format, Arguments);
   va_end(Arguments);
   while (Printed < 0 || TextSize < Printed)
     {
       delete [] Text;
       (Printed < 0) ? TextSize *= 2 : TextSize = Printed;
       Text = new char[TextSize + 1];
       va_list Arguments; // = NULL;
       va_start(Arguments, format);
       Printed = vsnprintf(Text, TextSize, format, Arguments);
       va_end(Arguments);
     }
   mText = Text;
   delete[] Text;
   mType = type;
   mNumber = 0;
   handler();
 }
CCopasiMessage::CCopasiMessage (CCopasiMessage::Type type, size_t number, ...)
Specified constructor. This creates a formated message.
Parameters
CCopasiMessage::Type type (RAW|TRACE|WARNING|ERROR)
size_t number (message number see message.h)
... arguments like in printf
Definition at line 195 of file CCopasiMessage.cpp.
References C_INT32, fatalError, handler(), INITIALTEXTSIZE, Messages, mNumber, mText, and mType.
 {
   C_INT32 i = 0;
   C_INT32 TextSize = INITIALTEXTSIZE;
   C_INT32 Printed = 0;
   while (Messages[i].No != number && Messages[i].Text)
     i++;
   if (!Messages[i].Text)
     fatalError();
   char *Text = NULL;
   Text = new char[TextSize + 1];
   va_list Arguments; // = NULL;
   va_start(Arguments, number);
   Printed = vsnprintf(Text, TextSize, Messages[i].Text, Arguments);
   va_end(Arguments);
   while (Printed < 0 || TextSize < Printed)
     {
       delete [] Text;
       (Printed < 0) ? TextSize *= 2 : TextSize = Printed;
       Text = new char[TextSize + 1];
       va_list Arguments; // = NULL;
       va_start(Arguments, number);
       Printed = vsnprintf(Text, TextSize, Messages[i].Text, Arguments);
       va_end(Arguments);
     }
   mText = Text;
   delete [] Text;
   mType = type;
   mNumber = number;
   handler();
 }
CCopasiMessage::~CCopasiMessage (void)
Destructor.
Definition at line 359 of file CCopasiMessage.cpp.
 {}
Member Function Documentation
bool CCopasiMessage::checkForMessage (const size_t & number) static
Check whether a message with the given number is in the dequeue
Parameters
const size_t & number
Returns
bool found
Definition at line 131 of file CCopasiMessage.cpp.
Referenced by main(), test000104::test_bug1744(), test000091::test_delay_in_kinetic_law(), test000091::test_delay_in_kinetic_law_local_parameter(), test000095::test_import_l3_event_1(), test000095::test_import_l3_event_2(), test000095::test_import_l3_event_3(), test000095::test_import_l3_event_4(), test000095::test_import_l3_event_5(), and validate().
 {
   std::deque< CCopasiMessage >::const_iterator it = mMessageDeque.begin();
   std::deque< CCopasiMessage >::const_iterator end = mMessageDeque.end();
   for (; it != end; ++it)
     if (it->getNumber() == number) return true;
   return false;
 }
void CCopasiMessage::clearDeque () static
This function clears the message stack.
Definition at line 108 of file CCopasiMessage.cpp.
Referenced by DataModelGUI::buildChangedObjects(), TaskWidget::commonAfterRunTask(), TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CQGLLayoutPainter::draw(), CQRDFTreeView::enterProtected(), CCopasiDataModel::exportMathModel(), CCopasiDataModel::exportSBML(), CCopasiDataModel::exportSBMLToString(), TaskWidget::finishTask(), CCopasiDataModel::importSBML(), CCopasiDataModel::importSBMLFromString(), CCopasiDataModel::loadModel(), CCopasiDataModel::saveModel(), CQMiriamWidget::showEvent(), CopasiUI3Window::slotConvertToIrreversible(), CQExperimentData::slotExperimentChanged(), CopasiUI3Window::slotExportMathModelFinished(), CopasiUI3Window::slotExportSBMLToStringFinished(), FunctionWidget1::slotFcnDescriptionChanged(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotFileSaveFinished(), CopasiUI3Window::slotImportSBMLFromStringFinished(), CopasiUI3Window::slotUpdateMIRIAM(), and CopasiUI3Window::slotUpdateMIRIAMFinished().
 {
   mMessageDeque.clear();
   return;
 }
std::string CCopasiMessage::getAllMessageText (const bool & chronological = true) static
Retrieve the text of all messages in the dequeue in chronological or reverse chronological order. If more than on message is in the dequeue the messages are separated by an empty line.
Returns
std::string messageTexts
Definition at line 93 of file CCopasiMessage.cpp.
References CCopasiMessage(), getFirstMessage(), getLastMessage(), and getText().
Referenced by TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CQGLLayoutPainter::draw(), CQRDFTreeView::enterProtected(), exportSBML(), CCopasiDataModel::exportSBML(), CCopasiDataModel::exportSBMLToString(), TaskWidget::finishTask(), Arguments::handleCommandLine(), CQFittingWidget::loadTask(), main(), CQMiriamWidget::showEvent(), CopasiUI3Window::slotConvertToIrreversible(), CQTSSAWidget::slotDuration(), CQTrajectoryWidget::slotDuration(), CQExperimentData::slotExperimentChanged(), CopasiUI3Window::slotExportMathModelFinished(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFileSaveFinished(), TaskWidget::slotFinishThread(), CQTSSAWidget::slotIntervals(), CQTrajectoryWidget::slotIntervals(), CQTSSAWidget::slotIntervalSize(), CQTrajectoryWidget::slotIntervalSize(), CQCrossSectionTaskWidget::slotOutputConvergence(), CQCrossSectionTaskWidget::slotOutputCrossings(), CQCrossSectionTaskWidget::slotOutputDelay(), CQCrossSectionTaskWidget::slotUpdateConvergence(), CQCrossSectionTaskWidget::slotUpdateCrossings(), and validate().
 {
   std::string Text = "";
   CCopasiMessage(*getMessage)() = chronological ? getFirstMessage : getLastMessage;
   while (!mMessageDeque.empty())
     {
       if (Text != "") Text += "\n";
       Text += getMessage().getText();
     }
   return Text;
 }
CCopasiMessage CCopasiMessage::getFirstMessage () static
This function retrieves the first message created in COPASI. Consecutive calls allow for the retrieval of all generated messages in chronological order. If no more messages are in the dequeue the message (MCCopasiMessage + 1, "Message (1): No more messages." is returned.
Returns
CCopasiMessage message
Definition at line 69 of file CCopasiMessage.cpp.
References CCopasiMessage(), MCCopasiMessage, and RAW.
Referenced by getAllMessageText().
 {
   if (mMessageDeque.empty())
     CCopasiMessage(CCopasiMessage::RAW,
                    MCCopasiMessage + 1);
   CCopasiMessage Message(mMessageDeque.front());
   mMessageDeque.pop_front();
   return Message;
 }
CCopasiMessage::Type CCopasiMessage::getHighestSeverity () static
Retrieve highest severity of the messages in the dequeue.
Returns
const CCopasiMessage::Type & highestSeverity
Definition at line 119 of file CCopasiMessage.cpp.
References RAW.
Referenced by TaskWidget::commonRunTask(), TaskWidget::finishTask(), CFitProblem::initialize(), CQMiriamWidget::showEvent(), and TaskWidget::slotFinishThread().
 {
   CCopasiMessage::Type HighestSeverity = RAW;
   std::deque< CCopasiMessage >::const_iterator it = mMessageDeque.begin();
   std::deque< CCopasiMessage >::const_iterator end = mMessageDeque.end();
   for (; it != end; ++it)
     if (it->getType() > HighestSeverity) HighestSeverity = it->getType();
   return HighestSeverity;
 }
CCopasiMessage CCopasiMessage::getLastMessage () static
This function retrieves the last message created in COPASI. Consecutive calls allow for the retrieval of all generated messages in reverse chronological order. If no more messages are in the dequeue the message (MCCopasiMessage + 1, "Message (1): No more messages." is returned.
Returns
CCopasiMessage message
Definition at line 81 of file CCopasiMessage.cpp.
References CCopasiMessage(), MCCopasiMessage, and RAW.
Referenced by DataModelGUI::buildChangedObjects(), CFitProblem::calculate(), COptProblem::calculate(), CFitProblem::calculateCrossValidation(), CopasiUI3Window::checkPendingMessages(), CCopasiDataModel::commonAfterLoad(), CExpression::createInitialExpression(), CCopasiXMLParser::ModelParameterElement::end(), CCopasiXMLParser::ListOfModelParameterSetsElement::end(), CCopasiXMLParser::MetaboliteElement::end(), CCopasiXMLParser::CompartmentElement::end(), CCopasiXMLParser::ModelValueElement::end(), CCopasiXMLParser::EventElement::end(), CCopasiXMLParser::AssignmentElement::end(), CCopasiXMLParser::ModelElement::end(), CCopasiXMLParser::TaskElement::end(), CCopasiXMLParser::COPASIElement::end(), getAllMessageText(), handler(), CFitProblem::initialize(), CAnnotation::isValidXML(), CFunctionDB::load(), CMoietiesTask::process(), CRDFGraphConverter::SBML2Copasi(), CopasiUI3Window::slotExportSBMLToStringFinished(), FunctionWidget1::slotFcnDescriptionChanged(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFileSaveFinished(), CopasiUI3Window::slotImportSBMLFinished(), CopasiUI3Window::slotImportSBMLFromStringFinished(), CopasiUI3Window::slotUpdateMIRIAMFinished(), test000061::test_bug_1044(), test000047::test_delay(), test000090::test_delay_in_function(), test000082::test_export_delayAssignment_2(), test000082::test_export_delayAssignment_4(), test000082::test_export_delayAssignment_6(), test000087::test_export_reaction_flux_reference_2(), test000088::test_import_assignment_without_expression(), test000086::test_import_compartment_units_1(), test000084::test_import_compartment_units_1(), test000085::test_import_compartment_units_1(), test000083::test_import_compartment_units_1(), test000086::test_import_compartment_units_10(), test000084::test_import_compartment_units_10(), test000085::test_import_compartment_units_10(), test000083::test_import_compartment_units_10(), test000086::test_import_compartment_units_11(), test000084::test_import_compartment_units_11(), test000085::test_import_compartment_units_11(), test000083::test_import_compartment_units_11(), test000084::test_import_compartment_units_12(), test000085::test_import_compartment_units_12(), test000083::test_import_compartment_units_12(), test000084::test_import_compartment_units_13(), test000085::test_import_compartment_units_13(), test000083::test_import_compartment_units_13(), test000083::test_import_compartment_units_14(), test000084::test_import_compartment_units_14(), test000085::test_import_compartment_units_14(), test000084::test_import_compartment_units_15(), test000085::test_import_compartment_units_15(), test000083::test_import_compartment_units_15(), test000084::test_import_compartment_units_16(), test000085::test_import_compartment_units_16(), test000083::test_import_compartment_units_16(), test000083::test_import_compartment_units_17(), test000084::test_import_compartment_units_17(), test000085::test_import_compartment_units_17(), test000085::test_import_compartment_units_18(), test000084::test_import_compartment_units_18(), test000083::test_import_compartment_units_18(), test000084::test_import_compartment_units_19(), test000085::test_import_compartment_units_19(), test000083::test_import_compartment_units_19(), test000086::test_import_compartment_units_2(), test000084::test_import_compartment_units_2(), test000085::test_import_compartment_units_2(), test000083::test_import_compartment_units_2(), test000083::test_import_compartment_units_20(), test000084::test_import_compartment_units_20(), test000085::test_import_compartment_units_20(), test000083::test_import_compartment_units_21(), test000084::test_import_compartment_units_21(), test000085::test_import_compartment_units_21(), test000086::test_import_compartment_units_3(), test000084::test_import_compartment_units_3(), test000085::test_import_compartment_units_3(), test000083::test_import_compartment_units_3(), test000086::test_import_compartment_units_4(), test000085::test_import_compartment_units_4(), test000084::test_import_compartment_units_4(), test000083::test_import_compartment_units_4(), test000086::test_import_compartment_units_5(), test000084::test_import_compartment_units_5(), test000085::test_import_compartment_units_5(), test000083::test_import_compartment_units_5(), test000086::test_import_compartment_units_6(), test000085::test_import_compartment_units_6(), test000083::test_import_compartment_units_6(), test000084::test_import_compartment_units_6(), test000086::test_import_compartment_units_7(), test000084::test_import_compartment_units_7(), test000083::test_import_compartment_units_7(), test000085::test_import_compartment_units_7(), test000086::test_import_compartment_units_8(), test000084::test_import_compartment_units_8(), test000083::test_import_compartment_units_8(), test000085::test_import_compartment_units_8(), test000086::test_import_compartment_units_9(), test000084::test_import_compartment_units_9(), test000083::test_import_compartment_units_9(), test000085::test_import_compartment_units_9(), test000077::test_import_dimensionless_3(), test000077::test_import_dimensionless_4(), test000077::test_import_dimensionless_5(), test000088::test_import_eventassignment_without_expression(), test000079::test_import_fast(), test000088::test_import_initialassignment_without_expression(), test000087::test_import_reaction_flux_reference_1(), test000087::test_import_reaction_flux_reference_3(), test000062::test_kineticlaw_without_math(), test000045::test_stoichiometricExpression(), test000044::test_stoichiometricExpression(), and test000046::test_stoichiometricExpression().
 {
   if (mMessageDeque.empty())
     CCopasiMessage(CCopasiMessage::RAW,
                    MCCopasiMessage + 1);
   CCopasiMessage Message(mMessageDeque.back());
   mMessageDeque.pop_back();
   return Message;
 }
const size_t & CCopasiMessage::getNumber (void) const
Retrieves the number of the message.
Returns
"const size_t &" mNumber
Definition at line 362 of file CCopasiMessage.cpp.
References mNumber.
Referenced by CopasiUI3Window::checkPendingMessages(), TaskWidget::commonRunTask(), CModel::load(), CReaction::setScalingFactor(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFileSaveFinished(), test000082::test_export_delayAssignment_2(), test000082::test_export_delayAssignment_4(), test000082::test_export_delayAssignment_6(), test000088::test_import_assignment_without_expression(), test000086::test_import_compartment_units_1(), test000084::test_import_compartment_units_1(), test000085::test_import_compartment_units_1(), test000083::test_import_compartment_units_1(), test000086::test_import_compartment_units_10(), test000085::test_import_compartment_units_10(), test000084::test_import_compartment_units_10(), test000083::test_import_compartment_units_10(), test000086::test_import_compartment_units_11(), test000085::test_import_compartment_units_11(), test000084::test_import_compartment_units_11(), test000083::test_import_compartment_units_11(), test000085::test_import_compartment_units_12(), test000084::test_import_compartment_units_12(), test000083::test_import_compartment_units_12(), test000085::test_import_compartment_units_13(), test000084::test_import_compartment_units_13(), test000083::test_import_compartment_units_13(), test000085::test_import_compartment_units_14(), test000084::test_import_compartment_units_14(), test000083::test_import_compartment_units_14(), test000085::test_import_compartment_units_15(), test000084::test_import_compartment_units_15(), test000083::test_import_compartment_units_15(), test000085::test_import_compartment_units_16(), test000084::test_import_compartment_units_16(), test000083::test_import_compartment_units_16(), test000085::test_import_compartment_units_17(), test000084::test_import_compartment_units_17(), test000083::test_import_compartment_units_17(), test000083::test_import_compartment_units_18(), test000085::test_import_compartment_units_18(), test000084::test_import_compartment_units_18(), test000083::test_import_compartment_units_19(), test000085::test_import_compartment_units_19(), test000084::test_import_compartment_units_19(), test000086::test_import_compartment_units_2(), test000083::test_import_compartment_units_2(), test000084::test_import_compartment_units_2(), test000085::test_import_compartment_units_2(), test000083::test_import_compartment_units_20(), test000085::test_import_compartment_units_20(), test000084::test_import_compartment_units_20(), test000083::test_import_compartment_units_21(), test000085::test_import_compartment_units_21(), test000084::test_import_compartment_units_21(), test000086::test_import_compartment_units_3(), test000083::test_import_compartment_units_3(), test000084::test_import_compartment_units_3(), test000085::test_import_compartment_units_3(), test000086::test_import_compartment_units_4(), test000084::test_import_compartment_units_4(), test000083::test_import_compartment_units_4(), test000085::test_import_compartment_units_4(), test000086::test_import_compartment_units_5(), test000085::test_import_compartment_units_5(), test000084::test_import_compartment_units_5(), test000083::test_import_compartment_units_5(), test000086::test_import_compartment_units_6(), test000084::test_import_compartment_units_6(), test000083::test_import_compartment_units_6(), test000085::test_import_compartment_units_6(), test000086::test_import_compartment_units_7(), test000085::test_import_compartment_units_7(), test000084::test_import_compartment_units_7(), test000083::test_import_compartment_units_7(), test000086::test_import_compartment_units_8(), test000085::test_import_compartment_units_8(), test000083::test_import_compartment_units_8(), test000084::test_import_compartment_units_8(), test000086::test_import_compartment_units_9(), test000083::test_import_compartment_units_9(), test000084::test_import_compartment_units_9(), test000085::test_import_compartment_units_9(), test000077::test_import_dimensionless_3(), test000077::test_import_dimensionless_4(), test000077::test_import_dimensionless_5(), test000088::test_import_eventassignment_without_expression(), test000079::test_import_fast(), test000088::test_import_initialassignment_without_expression(), test000087::test_import_reaction_flux_reference_1(), test000087::test_import_reaction_flux_reference_3(), and test000062::test_kineticlaw_without_math().
 {return mNumber;}
const std::string & CCopasiMessage::getText (void) const
Retrieves the text of the message.
Returns
"const string &" mMessage
Definition at line 360 of file CCopasiMessage.cpp.
References mText.
Referenced by CopasiUI3Window::checkPendingMessages(), SBMLImporter::createCModelFromSBMLDocument(), getAllMessageText(), SBMLImporter::importEvent(), SBMLImporter::importEvents(), SBMLImporter::importFunctionDefinitions(), SBMLImporter::importInitialAssignments(), main(), CopasiUI3Window::slotFileOpenFinished(), CopasiUI3Window::slotFileSaveFinished(), test000090::test_delay_in_function(), test000077::test_import_dimensionless_3(), test000077::test_import_dimensionless_4(), test000077::test_import_dimensionless_5(), and test000079::test_import_fast().
 {return mText;}
const CCopasiMessage::Type & CCopasiMessage::getType (void) const
Retrieves the type of the message.
Returns
"const CCopasiMessage::Type &" mType
Definition at line 361 of file CCopasiMessage.cpp.
References mType.
Referenced by CopasiUI3Window::checkPendingMessages(), SBMLImporter::importEvents(), SBMLImporter::importInitialAssignments(), CQFittingWidget::loadTask(), test000090::test_delay_in_function(), and test000062::test_kineticlaw_without_math().
 {return mType;}
void CCopasiMessage::handler (const bool & _throw = false) private
The actual constructor of a message.
Parameters
const bool & throw (default: false)
text message text
Definition at line 239 of file CCopasiMessage.cpp.
References COMMANDLINE, COMMANDLINE_FILTERED, COptions::compareValue(), ERROR, ERROR_FILTERED, EXCEPTION, EXCEPTION_FILTERED, getLastMessage(), IsGUI, lineBreak(), LocalTimeStamp(), MCCopasiMessage, mNumber, mText, mType, RAW, RAW_FILTERED, TRACE, TRACE_FILTERED, WARNING, and WARNING_FILTERED.
Referenced by CCopasiMessage().
 {
   std::string Text = mText;
   switch (mType)
     {
       case RAW:
         mText = "";
         break;
       case TRACE:
         mText = ">TRACE ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case WARNING:
         mText = ">WARNING ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case COMMANDLINE:
         if (IsGUI)
           {
             mText = ">WARNING ";
           }
         else
           {
             mText = ">ERROR ";
           }
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case ERROR:
         mText = ">ERROR ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case EXCEPTION:
         mText = ">EXCEPTION ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case RAW_FILTERED:
         mText = ">RAW(filtered) ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case TRACE_FILTERED:
         mText = ">TRACE(filtered) ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case COMMANDLINE_FILTERED:
         mText = ">COMMANDLINE(filtered) ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case WARNING_FILTERED:
         mText = ">WARNING(filtered) ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case ERROR_FILTERED:
         mText = ">ERROR(filtered) ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
       case EXCEPTION_FILTERED:
         mText = ">EXCEPTION(filtered) ";
         mText += LocalTimeStamp();
         mText += "<\n";
         break;
     }
   mText += Text;
   if (mType != RAW) lineBreak();
   // Remove the message: No more messages.
   if (mMessageDeque.size() == 1 &&
       mMessageDeque.back().getNumber() == MCCopasiMessage + 1)
     getLastMessage();
   mMessageDeque.push_back(*this);
   // All messages are printed to std::cerr
   if (COptions::compareValue("Verbose", true) &&
       mNumber != MCCopasiMessage + 1)
     {
       std::cerr << mText << std::endl;
 #ifdef COPASI_DEBUG_TRACE
       DebugFile << mText << std::endl;
 #endif // COPASI_DEBUG_TRACE
     }
   if (mType == EXCEPTION)
     throw CCopasiException(*this);
 }
void CCopasiMessage::lineBreak () private
Inserts line breaks in the message text.
Definition at line 364 of file CCopasiMessage.cpp.
References mText.
Referenced by handler().
 {
   std::string Search("\n");
   std::string Replace("\n  ");
   std::string::size_type pos = 0;
   while (true)
     {
       pos = mText.find(Search, pos);
       if (pos == std::string::npos)
         break;
       mText.replace(pos, Search.length(), Replace);
       pos += Replace.length();
     }
 }
CCopasiMessage & CCopasiMessage::operator= (const CCopasiMessage & RHS)
Assignment operator.
Definition at line 351 of file CCopasiMessage.cpp.
References mNumber, mText, and mType.
 {
   mText = RHS.mText;
   mType = RHS.mType;
   mNumber = RHS.mNumber;
   return *this;
 }
const CCopasiMessage & CCopasiMessage::peekFirstMessage () static
This function peeks at the first message created in COPASI. If no more messages are in the dequeue the message (MCCopasiMessage + 1, "Message (1): No more messages." is returned.
Returns
const CCopasiMessage & message
Definition at line 51 of file CCopasiMessage.cpp.
References CCopasiMessage(), MCCopasiMessage, and RAW.
 {
   if (mMessageDeque.empty())
     CCopasiMessage(CCopasiMessage::RAW,
                    MCCopasiMessage + 1);
   return mMessageDeque.front();
 }
const CCopasiMessage & CCopasiMessage::peekLastMessage () static
This function peeks at the last message created in COPASI. If no more messages are in the dequeue the message (MCCopasiMessage + 1, "Message (1): No more messages." is returned.
Returns
const CCopasiMessage & message
Definition at line 60 of file CCopasiMessage.cpp.
References CCopasiMessage(), MCCopasiMessage, and RAW.
Referenced by TaskWidget::commonRunTask(), SBMLImporter::createCModelFromSBMLDocument(), CQGLLayoutPainter::draw(), TaskWidget::finishTask(), SBMLImporter::importEvent(), SBMLImporter::importEvents(), SBMLImporter::importFunctionDefinitions(), SBMLImporter::importInitialAssignments(), CFitProblem::initialize(), CFunctionDB::load(), CQFittingWidget::loadTask(), CopasiUI3Window::slotExportMathModelFinished(), FunctionWidget1::slotFcnDescriptionChanged(), and CopasiUI3Window::slotFileSaveFinished().
 {
   if (mMessageDeque.empty())
     CCopasiMessage(CCopasiMessage::RAW,
                    MCCopasiMessage + 1);
   return mMessageDeque.back();
 }
void CCopasiMessage::setIsGUI (const bool & isGUI) static
Set whether the messages are created from COPASI as GUI or commandline. This method is called from CCopasiRootContainer::init and there should be no need to call it otherwise.
Parameters
const bool & isGUI
Definition at line 143 of file CCopasiMessage.cpp.
References IsGUI.
Referenced by CCopasiRootContainer::init().
 {
   IsGUI = isGUI;
 }
size_t CCopasiMessage::size () static
Retrieve the size of the dequeue
Returns
size_t size
Definition at line 114 of file CCopasiMessage.cpp.
Referenced by CCopasiDataModel::commonAfterLoad(), CExpression::createInitialExpression(), CCopasiXMLParser::ModelParameterElement::end(), CCopasiXMLParser::ListOfModelParameterSetsElement::end(), CCopasiXMLParser::MetaboliteElement::end(), CCopasiXMLParser::CompartmentElement::end(), CCopasiXMLParser::ModelValueElement::end(), CCopasiXMLParser::EventElement::end(), CCopasiXMLParser::AssignmentElement::end(), CCopasiXMLParser::ModelElement::end(), CQRDFTreeView::enterProtected(), CODEExporterXPPAUT::exportSingleLine(), CAnnotation::isValidXML(), CMoietiesTask::process(), CRDFGraphConverter::SBML2Copasi(), CQMiriamWidget::showEvent(), CQExperimentData::slotExperimentChanged(), TaskWidget::slotFinishThread(), test000089::test_bug1412(), test000104::test_bug1744(), test000061::test_bug_1044(), test000082::test_export_delayAssignment_2(), test000082::test_export_delayAssignment_4(), test000082::test_export_delayAssignment_6(), test000087::test_export_reaction_flux_reference_1(), test000087::test_export_reaction_flux_reference_2(), test000088::test_import_assignment_without_expression(), test000086::test_import_compartment_units_1(), test000085::test_import_compartment_units_1(), test000084::test_import_compartment_units_1(), test000083::test_import_compartment_units_1(), test000086::test_import_compartment_units_10(), test000083::test_import_compartment_units_10(), test000085::test_import_compartment_units_10(), test000084::test_import_compartment_units_10(), test000086::test_import_compartment_units_11(), test000083::test_import_compartment_units_11(), test000085::test_import_compartment_units_11(), test000084::test_import_compartment_units_11(), test000083::test_import_compartment_units_12(), test000085::test_import_compartment_units_12(), test000084::test_import_compartment_units_12(), test000083::test_import_compartment_units_13(), test000085::test_import_compartment_units_13(), test000084::test_import_compartment_units_13(), test000085::test_import_compartment_units_14(), test000083::test_import_compartment_units_14(), test000084::test_import_compartment_units_14(), test000083::test_import_compartment_units_15(), test000085::test_import_compartment_units_15(), test000084::test_import_compartment_units_15(), test000084::test_import_compartment_units_16(), test000083::test_import_compartment_units_16(), test000085::test_import_compartment_units_16(), test000084::test_import_compartment_units_17(), test000083::test_import_compartment_units_17(), test000085::test_import_compartment_units_17(), test000084::test_import_compartment_units_18(), test000083::test_import_compartment_units_18(), test000085::test_import_compartment_units_18(), test000084::test_import_compartment_units_19(), test000085::test_import_compartment_units_19(), test000083::test_import_compartment_units_19(), test000086::test_import_compartment_units_2(), test000085::test_import_compartment_units_2(), test000084::test_import_compartment_units_2(), test000083::test_import_compartment_units_2(), test000084::test_import_compartment_units_20(), test000083::test_import_compartment_units_20(), test000085::test_import_compartment_units_20(), test000084::test_import_compartment_units_21(), test000085::test_import_compartment_units_21(), test000083::test_import_compartment_units_21(), test000086::test_import_compartment_units_3(), test000085::test_import_compartment_units_3(), test000084::test_import_compartment_units_3(), test000083::test_import_compartment_units_3(), test000086::test_import_compartment_units_4(), test000085::test_import_compartment_units_4(), test000084::test_import_compartment_units_4(), test000083::test_import_compartment_units_4(), test000086::test_import_compartment_units_5(), test000084::test_import_compartment_units_5(), test000085::test_import_compartment_units_5(), test000083::test_import_compartment_units_5(), test000086::test_import_compartment_units_6(), test000085::test_import_compartment_units_6(), test000083::test_import_compartment_units_6(), test000084::test_import_compartment_units_6(), test000086::test_import_compartment_units_7(), test000083::test_import_compartment_units_7(), test000085::test_import_compartment_units_7(), test000084::test_import_compartment_units_7(), test000086::test_import_compartment_units_8(), test000084::test_import_compartment_units_8(), test000083::test_import_compartment_units_8(), test000085::test_import_compartment_units_8(), test000086::test_import_compartment_units_9(), test000083::test_import_compartment_units_9(), test000084::test_import_compartment_units_9(), test000085::test_import_compartment_units_9(), test000077::test_import_dimensionless_3(), test000077::test_import_dimensionless_4(), test000077::test_import_dimensionless_5(), test000088::test_import_eventassignment_without_expression(), test000079::test_import_fast(), test000088::test_import_initialassignment_without_expression(), test000087::test_import_reaction_flux_reference_1(), test000087::test_import_reaction_flux_reference_3(), and test000062::test_kineticlaw_without_math().
 {
   return mMessageDeque.size();
 }
Member Data Documentation
bool CCopasiMessage::IsGUI = false static private
A flag indicating whether the COPASI is running as commandline or GUI
Definition at line 132 of file CCopasiMessage.h.
Referenced by handler(), and setIsGUI().
std::deque< CCopasiMessage > CCopasiMessage::mMessageDeque static private
The stack of messages. Each message created with one of the specific constructors is automatically added to the stack.
Definition at line 125 of file CCopasiMessage.h.
size_t CCopasiMessage::mNumber private
Message Number
Definition at line 118 of file CCopasiMessage.h.
Referenced by CCopasiMessage(), getNumber(), handler(), and operator=().
std::string CCopasiMessage::mText private
Message text.
Definition at line 108 of file CCopasiMessage.h.
Referenced by CCopasiMessage(), getText(), handler(), lineBreak(), and operator=().
CCopasiMessage::Type CCopasiMessage::mType private
Message type.
Definition at line 113 of file CCopasiMessage.h.
Referenced by CCopasiMessage(), getType(), handler(), and operator=().
The documentation for this class was generated from the following files:
CCopasiMessage.h
CCopasiMessage.cpp