COPASI API: CEvaluationNodeOperator Class Reference
CEvaluationNodeOperator Class Reference
#include <CEvaluationNodeOperator.h>
Public Types
enum SubType {
INVALID = 0x00FFFFFF, POWER = 0x00000000, MULTIPLY = 0x00000001, DIVIDE = 0x00000002,
MODULUS = 0x00000003, PLUS = 0x00000004, MINUS = 0x00000005
}
Public Types inherited from CEvaluationNode
enum Type {
INVALID = 0xFF000000, NUMBER = 0x01000000, CONSTANT = 0x02000000, OPERATOR = 0x03000000,
OBJECT = 0x04000000, FUNCTION = 0x05000000, CALL = 0x06000000, STRUCTURE = 0x07000000,
CHOICE = 0x08000000, VARIABLE = 0x09000000, WHITESPACE = 0x0a000000, LOGICAL = 0x0b000000,
MV_FUNCTION = 0x0c000000, VECTOR = 0x0d000000, DELAY = 0x0e000000
}
Public Types inherited from CCopasiNode< std::string >
typedef std::string Data
Public Member Functions
virtual void calculate ()
CEvaluationNodeOperator (const SubType &subType, const Data &data)
CEvaluationNodeOperator (const CEvaluationNodeOperator &src)
virtual bool compile (const CEvaluationTree *pTree)
bool createModuloTree (const CEvaluationNodeOperator *pNode, ASTNode *pASTNode, const CCopasiDataModel *pDataModel) const
virtual std::string getBerkeleyMadonnaString (const std::vector< std::string > &children) const
virtual std::string getCCodeString (const std::vector< std::string > &children) const
virtual std::string getDisplayString (const std::vector< std::string > &children) const
virtual std::string getInfix (const std::vector< std::string > &children) const
CEvaluationNode * getLeft ()
const CEvaluationNode * getLeft () const
virtual std::string getMMLString (const std::vector< std::string > &children, bool expand, const std::vector< std::vector< std::string > > &variables) const
CEvaluationNode * getRight ()
const CEvaluationNode * getRight () const
virtual std::string getXPPString (const std::vector< std::string > &children) const
virtual CEvaluationNode * simplifyNode (const std::vector< CEvaluationNode * > &children) const
virtual ASTNode * toAST (const CCopasiDataModel *pDataModel) const
virtual ~CEvaluationNodeOperator ()
Public Member Functions inherited from CEvaluationNode
void addChildren (const std::vector< CEvaluationNode * > &children)
std::string buildBerkeleyMadonnaString () const
std::string buildCCodeString () const
std::string buildDisplayString () const
std::string buildInfix () const
std::string buildMMLString (bool expand, const std::vector< std::vector< std::string > > &variables) const
std::string buildXPPString () const
CEvaluationNode ()
CEvaluationNode (const CEvaluationNode &src)
CEvaluationNode * copyBranch () const
CEvaluationNode * copyNode (CEvaluationNode *child1, CEvaluationNode *child2) const
CEvaluationNode * copyNode (const std::vector< CEvaluationNode * > &children) const
const CEvaluationNode * findTopMinus (const std::vector< CFunctionAnalyzer::CValue > &callParameters) const
const Type & getType () const
const C_FLOAT64 & getValue () const
const C_FLOAT64 * getValuePointer () const
virtual bool isBoolean () const
virtual bool operator!= (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &right) const
bool operator< (const CEvaluationNode &rhs)
bool operator== (const CEvaluationNode &right) const
void printRecursively (std::ostream &os, int indent=0) const
void printRecursively () const
CEvaluationNode * splitBranch (const CEvaluationNode *splitnode, bool left) const
virtual ~CEvaluationNode ()
Public Member Functions inherited from CCopasiNode< std::string >
virtual bool addChild (CCopasiNode< Data > *pChild, CCopasiNode< Data > *pAfter=NULL)
bool addSibling (CCopasiNode< Data > *pSibling, CCopasiNode< Data > *pAfter=NULL)
CCopasiNode (CCopasiNode< Data > *pParent=NULL)
CCopasiNode (const CCopasiNode< Data > &src)
CCopasiNode (const Data &data, CCopasiNode< Data > *pParent=NULL)
bool deleteChildren ()
CCopasiNode< Data > * getChild ()
const CCopasiNode< Data > * getChild () const
CCopasiNode< Data > * getChild (const size_t &index)
const CCopasiNode< Data > * getChild (const size_t &index) const
virtual const Data & getData () const
CCopasiNode< Data > * getNext ()
const CCopasiNode< Data > * getNext () const
CCopasiNode< Data > * getNextNonChild ()
const CCopasiNode< Data > * getNextNonChild () const
size_t getNumChildren () const
CCopasiNode< Data > * getParent ()
const CCopasiNode< Data > * getParent () const
CCopasiNode< Data > * getSibling ()
const CCopasiNode< Data > * getSibling () const
virtual bool removeChild (CCopasiNode< Data > *pChild)
virtual bool setData (const Data &data)
virtual ~CCopasiNode ()
Static Public Member Functions
static CEvaluationNode * fromAST (const ASTNode *pASTNode, const std::vector< CEvaluationNode * > &children)
Static Public Member Functions inherited from CEvaluationNode
static CEvaluationNode * create (const Type &type, const Data &data)
static bool isKeyword (const std::string &str)
static Type subType (const Type &type)
static Type type (const Type &type)
Private Member Functions
CEvaluationNodeOperator ()
Private Attributes
CEvaluationNode * mpLeft
CEvaluationNode * mpRight
Additional Inherited Members
Protected Member Functions inherited from CEvaluationNode
CEvaluationNode (const Type &type, const Data &data)
Protected Member Functions inherited from CCopasiNode< std::string >
bool setChild (CCopasiNode< Data > *pChild)
bool setParent (CCopasiNode< Data > *pParent)
bool setSibling (CCopasiNode< Data > *pSibling)
Protected Attributes inherited from CEvaluationNode
class CEvaluationNode::CPrecedence mPrecedence
const C_FLOAT64 * mpValue
Type mType
C_FLOAT64 mValue
Protected Attributes inherited from CCopasiNode< std::string >
Data mData
Detailed Description
This is the class for nodes presenting operators used in an evaluation trees.
Definition at line 32 of file CEvaluationNodeOperator.h.
Member Enumeration Documentation
enum CEvaluationNodeOperator::SubType
Enumeration of possible node types.
Enumerator
INVALID
POWER
MULTIPLY
DIVIDE
MODULUS
PLUS
MINUS
Definition at line 38 of file CEvaluationNodeOperator.h.
   {
     INVALID = 0x00FFFFFF,
     POWER = 0x00000000,
     MULTIPLY = 0x00000001,
     DIVIDE = 0x00000002,
     MODULUS = 0x00000003,
     PLUS = 0x00000004,
     MINUS = 0x00000005
   };
Constructor & Destructor Documentation
CEvaluationNodeOperator::CEvaluationNodeOperator () private
Default constructor
Definition at line 21 of file CEvaluationNodeOperator.cpp.
Referenced by fromAST().
                                                 :
   CEvaluationNode(CEvaluationNode::INVALID, ""),
   mpLeft(NULL),
   mpRight(NULL)
 {}
CEvaluationNodeOperator::CEvaluationNodeOperator (const SubType & subType, const Data & data)
Default constructor
Parameters
const SubType & subType
const Data & data
Definition at line 27 of file CEvaluationNodeOperator.cpp.
References DIVIDE, MINUS, MODULUS, CEvaluationNode::mPrecedence, CEvaluationNode::mType, MULTIPLY, PLUS, POWER, PRECEDENCE_OPERATOR_DIVIDE, PRECEDENCE_OPERATOR_MINUS, PRECEDENCE_OPERATOR_MODULUS, PRECEDENCE_OPERATOR_MULTIPLY, PRECEDENCE_OPERATOR_PLUS, and PRECEDENCE_OPERATOR_POWER.
                       :
   CEvaluationNode((Type)(CEvaluationNode::OPERATOR | subType), data),
   mpLeft(NULL),
   mpRight(NULL)
 {
   switch (mType & 0x00FFFFFF)
     {
       case POWER:
         mPrecedence = PRECEDENCE_OPERATOR_POWER;
         break;
       case MULTIPLY:
         mPrecedence = PRECEDENCE_OPERATOR_MULTIPLY;
         break;
       case DIVIDE:
         mPrecedence = PRECEDENCE_OPERATOR_DIVIDE;
         break;
       case MODULUS:
         mPrecedence = PRECEDENCE_OPERATOR_MODULUS;
         break;
       case PLUS:
         mPrecedence = PRECEDENCE_OPERATOR_PLUS;
         break;
       case MINUS:
         mPrecedence = PRECEDENCE_OPERATOR_MINUS;
         break;
       default:
         break;
     }
 }
CEvaluationNodeOperator::CEvaluationNodeOperator (const CEvaluationNodeOperator & src)
Copy constructor
Parameters
const CEvaluationNodeOperator & src
Definition at line 64 of file CEvaluationNodeOperator.cpp.
                                                                                    :
   CEvaluationNode(src),
   mpLeft(NULL),
   mpRight(NULL)
 {}
CEvaluationNodeOperator::~CEvaluationNodeOperator () virtual
Destructor
Definition at line 70 of file CEvaluationNodeOperator.cpp.
 {}
Member Function Documentation
virtual void CEvaluationNodeOperator::calculate (void) inline virtual
Calculate the numerical result of the node. It is assumed that all child nodes are up to date.
Reimplemented from CEvaluationNode.
Definition at line 80 of file CEvaluationNodeOperator.h.
References C_FLOAT64, C_INT32, DIVIDE, CEvaluationNode::getValue(), MINUS, MODULUS, mpLeft, mpRight, CEvaluationNode::mType, MULTIPLY, CEvaluationNode::mValue, PLUS, and POWER.
   {
     switch (mType & 0x00FFFFFF)
       {
         case POWER:
           mValue = pow(mpLeft->getValue(), mpRight->getValue());
           break;
         case MULTIPLY:
           mValue = mpLeft->getValue() * mpRight->getValue();
           break;
         case DIVIDE:
           mValue = mpLeft->getValue() / mpRight->getValue();
           break;
         case MODULUS:
           if ((C_INT32) mpRight->getValue() == 0)
             mValue = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
           else
             mValue = (C_FLOAT64)(((C_INT32) mpLeft->getValue()) % ((C_INT32) mpRight->getValue()));
           break;
         case PLUS:
           mValue = mpLeft->getValue() + mpRight->getValue();
           break;
         case MINUS:
           mValue = mpLeft->getValue() - mpRight->getValue();
           break;
         default:
           break;
       }
   }
bool CEvaluationNodeOperator::compile (const CEvaluationTree * pTree) virtual
Compile a node;
Parameters
const CEvaluationTree * pTree
Returns
bool success;
Reimplemented from CEvaluationNode.
Definition at line 72 of file CEvaluationNodeOperator.cpp.
References CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), mpLeft, and mpRight.
Referenced by CDerive::deriveBranch(), getBerkeleyMadonnaString(), getCCodeString(), getDisplayString(), getInfix(), and getXPPString().
 {
   mpLeft = static_cast<CEvaluationNode *>(getChild());
   if (mpLeft == NULL) return false;
   mpRight = static_cast<CEvaluationNode *>(mpLeft->getSibling());
   if (mpRight == NULL) return false;
   return (mpRight->getSibling() == NULL); // We must have only two children
 }
bool CEvaluationNodeOperator::createModuloTree (const CEvaluationNodeOperator * pNode, ASTNode * pASTNode, const CCopasiDataModel * pDataModel) const
Convert our modulo to something SBML understands
Parameters
const CEvaluationNodeOperator* pNode the modulo operator node to be converted.
const ASTNode* pASTNode the root node for the SBML math expression
Returns
bool which is true on sucessfull conversion.
Definition at line 1302 of file CEvaluationNodeOperator.cpp.
References CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), MODULUS, CEvaluationNode::subType(), and CEvaluationNode::toAST().
Referenced by toAST().
 {
   bool result = false;
   if ((SubType)CEvaluationNode::subType(pNode->getType()) == MODULUS)
     {
       // the node has two children x and y
       const CEvaluationNode* x = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
       if (x != NULL)
         {
           const CEvaluationNode* y = dynamic_cast<const CEvaluationNode*>(x->getSibling());
           if (y != NULL)
             {
               // Frank noticed that this should actually be implemented as a
               // piecewise function because if one of the arguments is
               // negative, the definition is different
               pASTNode->setType(AST_FUNCTION_PIECEWISE);
               // the first child is the true branch
               // x%y -> x-ceil(x/y)*y
               ASTNode* pASTNodeTrue = new ASTNode();
               pASTNodeTrue->setType(AST_MINUS);
               ASTNode* tmpASTNode = new ASTNode(AST_DIVIDE);
               tmpASTNode->addChild(x->toAST(pDataModel));
               tmpASTNode->addChild(y->toAST(pDataModel));
               ASTNode* tmpASTNode2 = new ASTNode(AST_FUNCTION_CEILING);
               tmpASTNode2->addChild(tmpASTNode);
               tmpASTNode = new ASTNode(AST_TIMES);
               tmpASTNode->addChild(y->toAST(pDataModel));
               tmpASTNode->addChild(tmpASTNode2);
               pASTNodeTrue->addChild(x->toAST(pDataModel));
               pASTNodeTrue->addChild(tmpASTNode);
               pASTNode->addChild(pASTNodeTrue);
               // now comes the condition
               // if exactly one of the arguments to modulo is a negative number
               // we use the ceil branch, else we use the floor branch
               // x < 0 xor y < 0
               // xor
               ASTNode* pASTNodeCondition = new ASTNode();
               pASTNodeCondition->setType(AST_LOGICAL_XOR);
               // x < 0
               // <
               tmpASTNode = new ASTNode(AST_RELATIONAL_LT);
               // x
               tmpASTNode->addChild(x->toAST(pDataModel));
               // 0
               tmpASTNode2 = new ASTNode(AST_INTEGER);
               tmpASTNode2->setValue(0);
               tmpASTNode->addChild(tmpASTNode2);
               pASTNodeCondition->addChild(tmpASTNode);
               // y < 0
               // <
               tmpASTNode = new ASTNode(AST_RELATIONAL_LT);
               // y
               tmpASTNode->addChild(y->toAST(pDataModel));
               // 0
               tmpASTNode2 = new ASTNode(AST_INTEGER);
               tmpASTNode2->setValue(0);
               tmpASTNode->addChild(tmpASTNode2);
               pASTNodeCondition->addChild(tmpASTNode);
               pASTNode->addChild(pASTNodeCondition);
               // last is the false branch
               // x%y -> x-floor(x/y)*y
               ASTNode* pASTNodeFalse = new ASTNode();
               pASTNodeFalse->setType(AST_MINUS);
               tmpASTNode = new ASTNode(AST_DIVIDE);
               tmpASTNode->addChild(x->toAST(pDataModel));
               tmpASTNode->addChild(y->toAST(pDataModel));
               tmpASTNode2 = new ASTNode(AST_FUNCTION_FLOOR);
               tmpASTNode2->addChild(tmpASTNode);
               tmpASTNode = new ASTNode(AST_TIMES);
               tmpASTNode->addChild(y->toAST(pDataModel));
               tmpASTNode->addChild(tmpASTNode2);
               pASTNodeFalse->addChild(x->toAST(pDataModel));
               pASTNodeFalse->addChild(tmpASTNode);
               pASTNode->addChild(pASTNodeFalse);
               result = true;
             }
         }
     }
   return result;
 }
CEvaluationNode * CEvaluationNodeOperator::fromAST (const ASTNode * pASTNode, const std::vector< CEvaluationNode * > & children) static
Creates a new CEvaluationNodeCall from an ASTNode and the given children
Parameters
const ASTNode* pNode
const std::vector< CEvaluationNode * > & children
Returns
CEvaluationNode * pCretedNode
Definition at line 257 of file CEvaluationNodeOperator.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNodeOperator(), DIVIDE, CEvaluationNodeNumber::DOUBLE, CCopasiMessage::EXCEPTION, fatalError, INVALID, MCMathML, MINUS, CEvaluationNodeFunction::MINUS, MULTIPLY, PLUS, POWER, CEvaluationNode::subType(), and CEvaluationNode::type().
Referenced by CEvaluationTree::fromAST().
 {
   assert(pASTNode->getNumChildren() == children.size());
   size_t i = 0, iMax = children.size();
   int type = (int)pASTNode->getType();
   SubType subType;
   std::string data = "";
   switch (type)
     {
       case AST_PLUS:
         subType = PLUS;
         data = "+";
         break;
       case AST_MINUS:
         subType = MINUS;
         data = "-";
         break;
       case AST_TIMES:
         subType = MULTIPLY;
         data = "*";
         break;
       case AST_DIVIDE:
         subType = DIVIDE;
         data = "/";
         break;
       case AST_POWER:
       case AST_FUNCTION_POWER:
         subType = POWER;
         data = "^";
         break;
       default:
         subType = INVALID;
         fatalError();
         break;
     }
   CEvaluationNode* pNode = NULL;
   // handle "-" since it can be unary or binary
   if (type == AST_MINUS)
     {
       switch (iMax)
         {
           case 1:
             delete pNode;
             pNode = new CEvaluationNodeFunction(CEvaluationNodeFunction::MINUS, data);
             pNode->addChild(children[0]);
             break;
           case 2:
             pNode = new CEvaluationNodeOperator(subType, data);
             pNode->addChild(children[0]);
             pNode->addChild(children[1]);
             break;
           default:
             // error
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCMathML + 3);
             break;
         }
     }
   // handle binary operators (POWER,/)
   else if (type == AST_DIVIDE || type == AST_POWER || type == AST_FUNCTION_POWER)
     {
       switch (pASTNode->getNumChildren())
         {
           case 2:
             pNode = new CEvaluationNodeOperator(subType, data);
             pNode->addChild(children[0]);
             pNode->addChild(children[1]);
             break;
           default:
             // error
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCMathML + 4);
             break;
         }
     }
   // handle n-ary operators (+,*)
   else if (type == AST_PLUS || type == AST_TIMES)
     {
       switch (iMax)
         {
           case 0:
             if (type == AST_PLUS)
               {
                 pNode = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "0.0");
               }
             else
               {
                 pNode = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "1.0");
               }
             break;
           case 1:
             // replace the current node with its only child
             pNode = children[0];
             break;
           case 2:
           {
             pNode = new CEvaluationNodeOperator(subType, data);
             CEvaluationNode * pCurrent = pNode;
             // We have at least 2 children
             while (i < iMax - 1)
               {
                 // add the first value
                 pCurrent->addChild(children[i++]);
                 switch (iMax - i)
                   {
                     case 1:
                       // We have only 1 more child
                       pCurrent->addChild(children[i++]);
                       break;
                     default:
                       // We have at least 2 more children
                     {
                       // create a new node with the same operator
                       CEvaluationNode * pTmp = new CEvaluationNodeOperator(subType, data);
                       pCurrent->addChild(pTmp);
                       pCurrent = pTmp;
                     }
                     break;
                   }
               }
           }
           break;
         }
     }
   return pNode;
 }
std::string CEvaluationNodeOperator::getBerkeleyMadonnaString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in Berkeley Madonna format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 184 of file CEvaluationNodeOperator.cpp.
References compile(), CCopasiNode< std::string >::mData, mpLeft, and mpRight.
 {
   if (const_cast<CEvaluationNodeOperator *>(this)->compile(NULL))
     {
       std::string mdata = "";
       /* if ((SubType)CEvaluationNode::subType(this->getType()) == MODULUS)
       mdata = "@";
       else  */
       mdata = mData;
       Data DisplayString;
       if (*mpLeft < * (CEvaluationNode *)this)
         DisplayString = "(" + children[0] + ")";
       else
         DisplayString = children[0];
       DisplayString += mdata;
       if (!(*(CEvaluationNode *)this < *mpRight))
         DisplayString += "(" + children[1] + ")";
       else
         DisplayString += children[1];
       return DisplayString;
     }
   else
     return "@";
 }
std::string CEvaluationNodeOperator::getCCodeString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in C.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 136 of file CEvaluationNodeOperator.cpp.
References compile(), CEvaluationNode::getType(), CCopasiNode< std::string >::mData, MODULUS, mpLeft, mpRight, POWER, and CEvaluationNode::subType().
 {
   if (const_cast<CEvaluationNodeOperator *>(this)->compile(NULL))
     {
       Data DisplayString;
       SubType subType = (SubType)CEvaluationNode::subType(this->getType());
       if (subType == POWER)
         DisplayString = "pow(";
       if (subType == MODULUS)
         DisplayString = "(int)";
       if (*mpLeft < * (CEvaluationNode *)this)
         DisplayString += "(" + children[0] + ")";
       else
         DisplayString += children[0];
       switch (subType)
         {
           case POWER:
             DisplayString += ",";
             break;
           case MODULUS:
             DisplayString += "%(int)";
             break;
           default:
             DisplayString += mData;
             break;
         }
       if (!(*(CEvaluationNode *)this < *mpRight))
         DisplayString += "(" + children[1] + ")";
       else
         DisplayString += children[1];
       if (subType == POWER)
         DisplayString += ")";
       return DisplayString;
     }
   else
     return "@";
 }
std::string CEvaluationNodeOperator::getDisplayString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 111 of file CEvaluationNodeOperator.cpp.
References compile(), CCopasiNode< std::string >::mData, mpLeft, and mpRight.
 {
   if (const_cast<CEvaluationNodeOperator *>(this)->compile(NULL))
     {
       Data DisplayString;
       if (*mpLeft < * (CEvaluationNode *)this)
         DisplayString = "(" + children[0] + ")";
       else
         DisplayString = children[0];
       DisplayString += mData;
       if (!(*(CEvaluationNode *)this < *mpRight))
         DisplayString += "(" + children[1] + ")";
       else
         DisplayString += children[1];
       return DisplayString;
     }
   else
     return "@";
 }
std::string CEvaluationNodeOperator::getInfix (const std::vector< std::string > & children) const virtual
Retrieve the infix value of the node and its eventual child nodes.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 86 of file CEvaluationNodeOperator.cpp.
References compile(), CCopasiNode< std::string >::mData, mpLeft, and mpRight.
 {
   if (const_cast<CEvaluationNodeOperator *>(this)->compile(NULL))
     {
       Data Infix;
       if (*mpLeft < * (CEvaluationNode *)this)
         Infix = "(" + children[0] + ")";
       else
         Infix = children[0];
       Infix += mData;
       if (!(*(CEvaluationNode *)this < *mpRight))
         Infix += "(" + children[1] + ")";
       else
         Infix += children[1];
       return Infix;
     }
   else
     return "@";
 }
CEvaluationNode * CEvaluationNodeOperator::getLeft ()
Definition at line 1387 of file CEvaluationNodeOperator.cpp.
References mpLeft.
Referenced by CDerive::deriveBranch(), and CFindDimensions::findDimension().
 {return mpLeft;}
const CEvaluationNode * CEvaluationNodeOperator::getLeft () const
Definition at line 1389 of file CEvaluationNodeOperator.cpp.
References mpLeft.
 {return mpLeft;}
std::string CEvaluationNodeOperator::getMMLString (const std::vector< std::string > & children, bool expand, const std::vector< std::vector< std::string > > & variables) const virtual
Build the MathML string
Parameters
const std::vector< std::string > & children
bool expand = true
const std::vector< std::vector< std::string > > & variables
Returns
std::string MMLString
Reimplemented from CEvaluationNode.
Definition at line 1399 of file CEvaluationNodeOperator.cpp.
References CEvaluationNode::CALL, DIVIDE, CEvaluationNode::getType(), MINUS, MODULUS, mpLeft, mpRight, CEvaluationNode::mType, MULTIPLY, CEvaluationNode::OPERATOR, PLUS, and POWER.
 {
   std::ostringstream out;
   bool flag;
   switch (mType & 0x00FFFFFF)
     {
       case PLUS:
         out << "<mrow>" << std::endl;
         out << children[0];
         out << "<mo>" << "+" << "</mo>" << std::endl;
         out << children[1];
         out << "</mrow>" << std::endl;
         break;
       case MINUS:
         out << "<mrow>" << std::endl;
         out << children[0];
         out << "<mo>" << "-" << "</mo>" << std::endl;
         flag = ((mpRight->getType() == (CEvaluationNode::OPERATOR | PLUS))
                 || (mpRight->getType() == (CEvaluationNode::OPERATOR | MINUS))
                 || (((mpRight->getType() & 0xFF000000) == CEvaluationNode::CALL) && expand)
                );
         if (flag) out << "<mfenced>" << std::endl;
         out << children[1];
         if (flag) out << "</mfenced>" << std::endl; // ???
         out << "</mrow>" << std::endl;
         break;
       case MULTIPLY:
         out << "<mrow>" << std::endl;
         //do we need "()" ?
         flag = ((mpLeft->getType() == (CEvaluationNode::OPERATOR | PLUS))
                 || (mpLeft->getType() == (CEvaluationNode::OPERATOR | MINUS))
                 || (((mpLeft->getType() & 0xFF000000) == CEvaluationNode::CALL) && expand)
                );
         if (flag) out << "<mfenced>" << std::endl;
         out << children[0];
         if (flag) out << "</mfenced>" << std::endl;
         out << "<mo>" << "&CenterDot;" << "</mo>" << std::endl;
         flag = ((mpRight->getType() == (CEvaluationNode::OPERATOR | PLUS))
                 || (mpRight->getType() == (CEvaluationNode::OPERATOR | MINUS))
                 || (((mpRight->getType() & 0xFF000000) == CEvaluationNode::CALL) && expand)
                );
         if (flag) out << "<mfenced>" << std::endl;
         out << children[1];
         if (flag) out << "</mfenced>" << std::endl;
         out << "</mrow>" << std::endl;
         break;
       case DIVIDE:
         out << "<mfrac>" << std::endl;
         //out << "<mrow>" << std::endl;
         out << children[0];
         //out << "</mrow>" << std::endl;
         //out << "<mrow>" << std::endl;
         out << children[1];
         //out << "</mrow>" << std::endl;
         out << "</mfrac>" << std::endl;
         break;
       case POWER:
         out << "<msup>" << std::endl;
         //do we need "()" ?
         flag = ((mpLeft->getType() == (CEvaluationNode::OPERATOR | PLUS))
                 || (mpLeft->getType() == (CEvaluationNode::OPERATOR | MINUS))
                 || (mpLeft->getType() == (CEvaluationNode::OPERATOR | MULTIPLY))
                 || (mpLeft->getType() == (CEvaluationNode::OPERATOR | DIVIDE))
                 || (mpLeft->getType() == (CEvaluationNode::OPERATOR | POWER))
                 || (((mpLeft->getType() & 0xFF000000) == CEvaluationNode::CALL) && expand)
                );
         if (flag) out << "<mfenced>" << std::endl;
         out << children[0];
         if (flag) out << "</mfenced>" << std::endl;
         out << "<mrow>" << std::endl;
         out << children[1];
         out << "</mrow>" << std::endl;
         out << "</msup>" << std::endl;
         break;
       case MODULUS:
         out << "<mrow>" << std::endl;
         //do we need "()" ?
         flag = true;
         if (flag) out << "<mfenced>" << std::endl;
         out << children[0];
         if (flag) out << "</mfenced>" << std::endl;
         out << "<mo>" << "%" << "</mo>" << std::endl;
         flag = true;
         if (flag) out << "<mfenced>" << std::endl;
         out << children[1];
         if (flag) out << "</mfenced>" << std::endl;
         out << "</mrow>" << std::endl;
         break;
     }
   return out.str();
 }
CEvaluationNode * CEvaluationNodeOperator::getRight ()
Definition at line 1391 of file CEvaluationNodeOperator.cpp.
References mpRight.
Referenced by CDerive::deriveBranch(), and CFindDimensions::findDimension().
 {return mpRight;}
const CEvaluationNode * CEvaluationNodeOperator::getRight () const
Definition at line 1393 of file CEvaluationNodeOperator.cpp.
References mpRight.
 {return mpRight;}
std::string CEvaluationNodeOperator::getXPPString (const std::vector< std::string > & children) const virtual
Retrieve the display string of the node and its eventual child nodes in XPPAUT format.
Returns
const Data & value
Reimplemented from CEvaluationNode.
Definition at line 216 of file CEvaluationNodeOperator.cpp.
References compile(), CEvaluationNode::getType(), CCopasiNode< std::string >::mData, MODULUS, mpLeft, mpRight, and CEvaluationNode::subType().
 {
   if (const_cast<CEvaluationNodeOperator *>(this)->compile(NULL))
     {
       Data DisplayString;
       SubType subType = (SubType)CEvaluationNode::subType(this->getType());
       if (subType == MODULUS)
         DisplayString = "mod(";
       if (*mpLeft < * (CEvaluationNode *)this)
         DisplayString += "(" + children[0] + ")";
       else
         DisplayString += children[0];
       switch (subType)
         {
           case MODULUS:
             DisplayString += ",";
             break;
           default:
             DisplayString += mData;
             break;
         }
       if (!(*(CEvaluationNode *)this < *mpRight))
         DisplayString += "(" + children[1] + ")";
       else
         DisplayString += children[1];
       if (subType == MODULUS)
         DisplayString += ")";
       return DisplayString;
     }
   else
     return "@"; //TODO
 }
CEvaluationNode * CEvaluationNodeOperator::simplifyNode (const std::vector< CEvaluationNode * > & children) const virtual
Create a simplified node for an operatorNode with children from vector (if not exist, = NULL), and assign new children
Returns
CEvaluationNode* return a pointer to the simplified node;
Reimplemented from CEvaluationNode.
Definition at line 462 of file CEvaluationNodeOperator.cpp.
References CCopasiNode< _Data >::addChild(), CEvaluationNode::buildInfix(), CEvaluationNode::copyBranch(), CEvaluationNode::copyNode(), CEvaluationNode::create(), DIVIDE, CEvaluationNodeNumber::DOUBLE, CEvaluationNode::FUNCTION, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiNode< std::string >::getSibling(), CEvaluationNode::getType(), CEvaluationNode::getValue(), MINUS, CEvaluationNodeFunction::MINUS, CEvaluationNode::mType, MULTIPLY, CEvaluationNode::NUMBER, CEvaluationNode::OPERATOR, PLUS, POWER, CEvaluationNode::simplifyNode(), CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   assert(children.size() > 0);
   CEvaluationNode* child1 = children[0];
   CEvaluationNode* child2 = NULL;
   if (children.size() > 1)
     {
       child2 = children[1];
     }
   switch ((SubType) CEvaluationNode::subType(mType))
     {
       case POWER:
       {
         if (CEvaluationNode::type(child2->getType()) == NUMBER)
           {
             if (CEvaluationNode::type(child1->getType()) == NUMBER)
               {
                 // both children numbers ->calculate
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << pow(child1->getValue(), child2->getValue());
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child2->getValue() - 1.0) < 1.0E-100)
               {
                 // a^1 -> a
                 delete child2;
                 return child1;
               }
             if (fabs(child2->getValue()) < 1.0E-100)
               {
                 // a^0 -> 1
                 CEvaluationNode* newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "1.0");
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (child2->getValue() < 0.0)
               {
                 //negative float exponent ->write as fraction
                 CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
                 CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "1.0");
                 CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                 CEvaluationNode* grandchild1 = child1;
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << fabs(child2->getValue());
                 CEvaluationNode* grandchild2 = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 newnode->addChild(newchild1, NULL);
                 newnode->addChild(newchild2, newchild1);
                 newchild2->addChild(grandchild1, NULL);
                 newchild2->addChild(grandchild2, grandchild1);
                 delete child2;
                 return newnode;
               }
             if ((child1->getType() == (CEvaluationNode::Type)(FUNCTION | CEvaluationNodeFunction::MINUS))
                 && ((fabs(child2->getValue() - floor(child2->getValue())) < 1.0E-100) || (fabs(child2->getValue() - floor(child2->getValue()) - 1.0) < 1.0E-100)))
               {
                 // (-a)^n -> (-1)^n * a^n  for n int
                 // make negativity a property of product,
                 // easier to recognize a negative exponent.
                 int exp;
                 if (fabs(child2->getValue() - floor(child2->getValue())) < 1.0E-100)
                   exp = (int) floor(child2->getValue());
                 else
                   exp = (int) floor(child2->getValue()) + 1;
                 CEvaluationNode* newpower = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                 CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
                 newpower->addChild(newchild1, NULL);
                 newpower->addChild(child2, newchild1);
                 delete child1;
                 if (pow(-1.0, exp) == 1.0)
                   return newpower;
                 CEvaluationNode* newnode = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
                 newnode->addChild(newpower, NULL);
                 return newnode;
               }
           }
         if (child1->getData() == "^")
           {
             // (a^b)^c -> a^(b*c)
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
             CEvaluationNode* grandchild2 = child2;
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild2->addChild(grandchild1, NULL);
             newchild2->addChild(grandchild2, grandchild1);
             delete child1;
             return newnode;
           }
         /* disable this since negative exponents are actually generated
            during the simplification. the normalization should get rid of
            those.
         if (child2->getType() == (Type)(FUNCTION | CEvaluationNodeFunction::MINUS))
           {// a^(-b) -> 1/(a^b)
             // don't want negative exponents
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "1.0");
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode* grandchild1 = child1;
             CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild2->addChild(grandchild1, NULL);
             newchild2->addChild(grandchild2, grandchild1);
             delete child2;
             return newnode;
           }
         */
         if (child1->getData() == "*")
           {
             // (a*b)^c -> a^c * b^c
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode * grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode * grandchild2 = child2->copyBranch();
             CEvaluationNode * grandchild3 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
             CEvaluationNode * grandchild4 = child2;
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             newchild2->addChild(grandchild3, NULL);
             newchild2->addChild(grandchild4, grandchild3);
             delete child1;
             return newnode;
           }
         if (child1->getData() == "/")
           {
             // (a/b)^c -> a^c/b^c
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode * grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode * grandchild2 = child2->copyBranch();
             CEvaluationNode * grandchild3 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
             CEvaluationNode * grandchild4 = child2;
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             newchild2->addChild(grandchild3, NULL);
             newchild2->addChild(grandchild4, grandchild3);
             delete child1;
             return newnode;
           }
         /*
         if ((child1->getData() == "+") && (CEvaluationNode::type(child2->getType()) == NUMBER) && (child2->getValue() >= 1.0 + 1.0E-100))
           {// (a+b)^x -> (a+b) * (a+b)^(x-1)  for real x > 1
             // this is expanded step by step
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* newchild1 = child1->copyBranch();
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode * grandchild1 = child1;
             std::stringstream tmp;
             tmp.precision(18);
             tmp << child2->getValue() - 1.0;
             CEvaluationNode * grandchild2 = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild2->addChild(grandchild1, NULL);
             newchild2->addChild(grandchild2, grandchild1);
             delete child2;
             return newnode;
           }
           // don't do this during the simplification. This has to be done
           // during the normalization
         if (child2->getData() == "+")
           {// a^(b+c) -> a^b*a^c   minimize exponent
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
             CEvaluationNode * grandchild1 = child1->copyBranch();
             CEvaluationNode * grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
             CEvaluationNode * grandchild3 = child1;
             CEvaluationNode * grandchild4 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             newchild2->addChild(grandchild3, NULL);
             newchild2->addChild(grandchild4, grandchild3);
             delete child2;
             return newnode;
           }
           */
         CEvaluationNode *newnode = copyNode(child1, child2);
         return newnode;
       }
       case MULTIPLY:
       {
         if (CEvaluationNode::type(child1->getType()) == NUMBER)
           {
             if (CEvaluationNode::type(child2->getType()) == NUMBER)
               {
                 // both children numbers ->calculate
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << child1->getValue() * child2->getValue();
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child1->getValue()) < 1.0E-100)
               {
                 // 0*a -> 0
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "0.0");
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child1->getValue() - 1.0) < 1.0E-100)
               {
                 // 1*a -> a
                 delete child1;
                 return child2;
               }
             if (child1->getValue() < 0.0)
               {
                 // x*a -> -(|x|*a)  x < 0
                 //  make negativity a property of product,
                 // easier to recognize a negative exponent.
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
                 CEvaluationNode *newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << fabs(child1->getValue());
                 CEvaluationNode *grandchild1 = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 CEvaluationNode *grandchild2 = child2;
                 newnode->addChild(newchild1, NULL);
                 newchild1->addChild(grandchild1, NULL);
                 newchild1->addChild(grandchild2, grandchild1);
                 delete child1;
                 return newnode;
               }
           }
         if (CEvaluationNode::type(child2->getType()) == NUMBER)
           {
             // because of commutativity the same as before for child1.
             if (fabs(child2->getValue()) < 1.0E-100)
               {
                 // a*0 -> 0
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "0.0");
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child2->getValue() - 1.0) < 1.0E-100)
               {
                 // a*1 -> a
                 delete child2;
                 return child1;
               }
             if (child2->getValue() < 0.0)
               {
                 // a*x -> -(a*|x|)  for x < 0
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
                 CEvaluationNode *newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << fabs(child2->getValue());
                 CEvaluationNode *grandchild1 = child1;
                 CEvaluationNode *grandchild2 = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 newnode->addChild(newchild1, NULL);
                 newchild1->addChild(grandchild1, NULL);
                 newchild1->addChild(grandchild2, grandchild1);
                 delete child2;
                 return newnode;
               }
           }
         if (child1->getData() == "/")
           {
             if (child2->getData() == "/")
               {
                 // (a/b)*(c/d) -> (a*d)/(b*c)
                 // this rule is actually already executed by the following two rules, but more efficiently this way
                 CEvaluationNode * newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
                 CEvaluationNode * newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
                 CEvaluationNode * newchild2 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
                 CEvaluationNode * grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
                 CEvaluationNode * grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
                 CEvaluationNode * grandchild3 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
                 CEvaluationNode * grandchild4 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
                 newnode->addChild(newchild1, NULL);
                 newnode->addChild(newchild2, newchild1);
                 newchild1->addChild(grandchild1, NULL);
                 newchild1->addChild(grandchild2, grandchild1);
                 newchild2->addChild(grandchild3, NULL);
                 newchild2->addChild(grandchild4, grandchild3);
                 delete child1;
                 delete child2;
                 return newnode;
               }
             // (a/b) * c  ->  (a*c)/b
             CEvaluationNode * newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
             CEvaluationNode * newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode * newchild2 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
             CEvaluationNode * grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode * grandchild2 = child2;
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             delete child1;
             return newnode;
           }
         if (child2->getData() == "/")
           {
             // a * (b/c) -> (a*b)/c
             CEvaluationNode * newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
             CEvaluationNode * newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode * newchild2 = dynamic_cast<CEvaluationNode*>((child2->getChild())->getSibling())->copyBranch();
             CEvaluationNode * grandchild1 = child1;
             CEvaluationNode * grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             delete child2;
             return newnode;
           }
         if (CEvaluationNode::type(child1->getType()) == (Type)(FUNCTION | CEvaluationNodeFunction::MINUS))
           {
             // (-a) * b -> -(a*b)
             // make negativity a property of product
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode* grandchild2 = child2;
             newnode->addChild(newchild1, NULL);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             delete child1;
             return newnode;
           }
         if (CEvaluationNode::type(child2->getType()) == (Type)(FUNCTION | CEvaluationNodeFunction::MINUS))
           {
             // a*(-b) -> -(a*b)
             // make negativity a property of product,
             // easier to recognize a negative exponent.
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* grandchild1 = child1;
             CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
             newnode->addChild(newchild1, NULL);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             delete child2;
             return newnode;
           }
         if (child1->getData() == "+")
           {
             // expand (a+b)*c -> a*c + b*c
             CEvaluationNode * newnode = CEvaluationNode::create((Type)(OPERATOR | PLUS), "+");
             CEvaluationNode * newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode * newchild2 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode * grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode * grandchild2 = child2->copyBranch();
             CEvaluationNode * grandchild3 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
             CEvaluationNode * grandchild4 = child2;
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             newchild2->addChild(grandchild3, NULL);
             newchild2->addChild(grandchild4, grandchild3);
             delete child1;
             return newnode;
           }
         if (child2->getData() == "+")
           {
             // expand a*(b+c) -> a*b + a*c
             CEvaluationNode * newnode = CEvaluationNode::create((Type)(OPERATOR | PLUS), "+");
             CEvaluationNode * newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode * newchild2 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode * grandchild1 = child1->copyBranch();
             CEvaluationNode * grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
             CEvaluationNode * grandchild3 = child1;
             CEvaluationNode * grandchild4 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             newchild2->addChild(grandchild3, NULL);
             newchild2->addChild(grandchild4, grandchild3);
             delete child2;
             return newnode;
           }
         if (CEvaluationNode::type(child1->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(child1->getType())) == CEvaluationNodeOperator::POWER)
           {
             // A^n*A^l -> A^(n+l) this way exponents can be simplified
             // check if the second child is also a power item
             if (CEvaluationNode::type(child2->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(child2->getType())) == CEvaluationNodeOperator::POWER)
               {
                 if (dynamic_cast<const CEvaluationNode*>(child2->getChild())->buildInfix() == dynamic_cast<const CEvaluationNode*>(child1->getChild())->buildInfix())
                   {
                     CEvaluationNode* newNode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                     CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
                     newNode->addChild(newchild1);
                     CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | PLUS), "+");
                     CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
                     CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
                     // simplify newchild2
                     std::vector<CEvaluationNode*> children;
                     children.push_back(grandchild1);
                     children.push_back(grandchild2);
                     newNode->addChild(newchild2->simplifyNode(children));
                     // simplify the result again since a power node with an
                     // exponent of 1 or 0 could have been created.
                     delete child1;
                     children.clear();
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild())->copyBranch());
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild()->getSibling())->copyBranch());
                     child1 = newNode->simplifyNode(children);
                     delete newNode;
                     newNode = child1;
                     delete newchild2;
                     delete child2;
                     return newNode;
                   }
               }
             else
               {
                 // A^n * A -> A^(n+1)
                 // check if the second child is the same as the first child to
                 // the power operator
                 if (child2->buildInfix() == dynamic_cast<const CEvaluationNode*>(child1->getChild())->buildInfix())
                   {
                     CEvaluationNode* newNode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                     CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
                     newNode->addChild(newchild1);
                     CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | PLUS), "+");
                     CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
                     CEvaluationNode* grandchild2 = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "1.0");
                     // simplify newchild2
                     std::vector<CEvaluationNode*> children;
                     children.push_back(grandchild1);
                     children.push_back(grandchild2);
                     newNode->addChild(newchild2->simplifyNode(children));
                     // simplify the result again since a power node with an
                     // exponent of 1 or 0 could have been created.
                     delete child1;
                     children.clear();
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild())->copyBranch());
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild()->getSibling())->copyBranch());
                     child1 = newNode->simplifyNode(children);
                     delete newNode;
                     newNode = child1;
                     delete newchild2;
                     delete child2;
                     return newNode;
                   }
               }
           }
         else if (CEvaluationNode::type(child2->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(child2->getType())) == CEvaluationNodeOperator::POWER)
           {
             // A*A^n -> A^(n+1)
             // check if child 1 is the same as the first child to the power
             // operator
             if (child1->buildInfix() == dynamic_cast<const CEvaluationNode*>(child2->getChild())->buildInfix())
               {
                 CEvaluationNode* newNode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                 newNode->addChild(child1);
                 CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | PLUS), "+");
                 CEvaluationNode* grandchild1 = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "1.0");
                 CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
                 // simplify newchild2
                 std::vector<CEvaluationNode*> children;
                 children.push_back(grandchild1);
                 children.push_back(grandchild2);
                 newNode->addChild(newchild2->simplifyNode(children));
                 // simplify the result again since a power node with an
                 // exponent of 1 or 0 could have been created.
                 children.clear();
                 children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild())->copyBranch());
                 children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild()->getSibling())->copyBranch());
                 child1 = newNode->simplifyNode(children);
                 delete newNode;
                 newNode = child1;
                 delete newchild2;
                 delete child2;
                 return newNode;
               }
           }
         // default: copy
         CEvaluationNode *newnode = copyNode(child1, child2);
         return newnode;
       }
       case DIVIDE:
       {
         if (CEvaluationNode::type(child1->getType()) == NUMBER)
           {
             if (CEvaluationNode::type(child2->getType()) == NUMBER)
               {
                 // both children numbers ->calculate
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << child1->getValue() / child2->getValue();
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child1->getValue()) < 1.0E-100)
               {
                 // 0/a -> a
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "0.0");
                 delete child1;
                 delete child2;
                 return newnode;
               }
           }
         if (CEvaluationNode::type(child2->getType()) == NUMBER)
           {
             // a/0 -> false
             if (fabs(child2->getValue()) < 1.0E-100)
               return false;
             if (fabs(child2->getValue() - 1.0) < 1.0E-100)
               {
                 // a/1 -> a
                 delete child2;
                 return child1;
               }
           }
         if (child1->buildInfix() == child2->buildInfix())
           {
             // a/a -> 1
             CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "1.0");
             delete child1;
             delete child2;
             return newnode;
           }
         if (child1->getData() == "/")
           {
             if (child2->getData() == "/")
               {
                 // (a/b)/(c/d) -> (a*d)/(b*c)
                 // this rule is actually already executed by the following two rules, but more efficiently this way
                 CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
                 CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
                 CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
                 CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
                 CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
                 CEvaluationNode* grandchild3 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
                 CEvaluationNode* grandchild4 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
                 newnode->addChild(newchild1, NULL);
                 newnode->addChild(newchild2, newchild1);
                 newchild1->addChild(grandchild1, NULL);
                 newchild1->addChild(grandchild2, grandchild1);
                 newchild2->addChild(grandchild3, NULL);
                 newchild2->addChild(grandchild4, grandchild3);
                 delete child1;
                 delete child2;
                 return newnode;
               }
             // (a/b)/c -> a/(b*c)
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
             CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild())->copyBranch();
             CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
             CEvaluationNode* grandchild2 = child2;
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild2->addChild(grandchild1, NULL);
             newchild2->addChild(grandchild2, grandchild1);
             delete child1;
             return newnode;
           }
         if (child2->getData() == "/")
           {
             // a/(b/c) -> (a*c)/b
             CEvaluationNode* newnode = CEvaluationNode::create((Type)(OPERATOR | DIVIDE), "/");
             CEvaluationNode* newchild1 = CEvaluationNode::create((Type)(OPERATOR | MULTIPLY), "*");
             CEvaluationNode* newchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
             CEvaluationNode* grandchild1 = child1;
             CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
             newnode->addChild(newchild1, NULL);
             newnode->addChild(newchild2, newchild1);
             newchild1->addChild(grandchild1, NULL);
             newchild1->addChild(grandchild2, grandchild1);
             delete child2;
             return newnode;
           }
         if (CEvaluationNode::type(child1->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(child1->getType())) == CEvaluationNodeOperator::POWER)
           {
             // A^n / A^l -> A^(n-l)
             // check if the second child is also a power item
             if (CEvaluationNode::type(child2->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(child2->getType())) == CEvaluationNodeOperator::POWER)
               {
                 if (dynamic_cast<const CEvaluationNode*>(child2->getChild())->buildInfix() == dynamic_cast<const CEvaluationNode*>(child1->getChild())->buildInfix())
                   {
                     CEvaluationNode* newNode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                     CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
                     newNode->addChild(newchild1);
                     CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | MINUS), "-");
                     CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
                     CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
                     // simplify newchild2
                     std::vector<CEvaluationNode*> children;
                     children.push_back(grandchild1);
                     children.push_back(grandchild2);
                     newNode->addChild(newchild2->simplifyNode(children));
                     // simplify the result again since a power node with an
                     // exponent of 1 or 0 could have been created.
                     delete child1;
                     children.clear();
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild())->copyBranch());
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild()->getSibling())->copyBranch());
                     child1 = newNode->simplifyNode(children);
                     delete newNode;
                     newNode = child1;
                     delete newchild2;
                     delete child2;
                     return newNode;
                   }
               }
             else
               {
                 // A^n/A -> A^(n-1)
                 // check if the second child is the same as the first child to
                 // the power operator
                 if (child2->buildInfix() == dynamic_cast<const CEvaluationNode*>(child1->getChild())->buildInfix())
                   {
                     CEvaluationNode* newNode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                     CEvaluationNode* newchild1 = dynamic_cast<CEvaluationNode*>(child2->getChild())->copyBranch();
                     newNode->addChild(newchild1);
                     CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | MINUS), "-");
                     CEvaluationNode* grandchild1 = dynamic_cast<CEvaluationNode*>(child1->getChild()->getSibling())->copyBranch();
                     CEvaluationNode* grandchild2 = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "1.0");
                     // simplify newchild2
                     std::vector<CEvaluationNode*> children;
                     children.push_back(grandchild1);
                     children.push_back(grandchild2);
                     newNode->addChild(newchild2->simplifyNode(children));
                     // simplify the result again since a power node with an
                     // exponent of 1 or 0 could have been created.
                     delete child1;
                     children.clear();
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild())->copyBranch());
                     children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild()->getSibling())->copyBranch());
                     child1 = newNode->simplifyNode(children);
                     delete newNode;
                     newNode = child1;
                     delete newchild2;
                     delete child2;
                     return newNode;
                   }
               }
           }
         else if (CEvaluationNode::type(child2->getType()) == CEvaluationNode::OPERATOR && ((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(child2->getType())) == CEvaluationNodeOperator::POWER)
           {
             // A / A^n -> A^(1-n)
             // check if child 1 is the same as the first child to the power
             // operator
             if (child1->buildInfix() == dynamic_cast<const CEvaluationNode*>(child2->getChild())->buildInfix())
               {
                 CEvaluationNode* newNode = CEvaluationNode::create((Type)(OPERATOR | POWER), "^");
                 newNode->addChild(child1);
                 CEvaluationNode* newchild2 = CEvaluationNode::create((Type)(OPERATOR | MINUS), "-");
                 CEvaluationNode* grandchild1 = new CEvaluationNodeNumber(CEvaluationNodeNumber::DOUBLE, "1.0");
                 CEvaluationNode* grandchild2 = dynamic_cast<CEvaluationNode*>(child2->getChild()->getSibling())->copyBranch();
                 // simplify newchild2
                 std::vector<CEvaluationNode*> children;
                 children.push_back(grandchild1);
                 children.push_back(grandchild2);
                 newNode->addChild(newchild2->simplifyNode(children));
                 // simplify the result again since a power node with an
                 // exponent of 1 or 0 could have been created.
                 children.clear();
                 children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild())->copyBranch());
                 children.push_back(dynamic_cast<CEvaluationNode*>(newNode->getChild()->getSibling())->copyBranch());
                 child1 = newNode->simplifyNode(children);
                 delete newNode;
                 newNode = child1;
                 delete newchild2;
                 delete child2;
                 return newNode;
               }
           }
         // default: copy
         CEvaluationNode *newnode = copyNode(child1, child2);
         return newnode;
       }
       case PLUS:
       {
         if (CEvaluationNode::type(child1->getType()) == NUMBER)
           {
             if (CEvaluationNode::type(child2->getType()) == NUMBER)
               {
                 // both children numbers ->calculate
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << child1->getValue() + child2->getValue();
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child1->getValue()) < 1.0E-100)
               {
                 // 0 + a -> a
                 delete child1;
                 return child2;
               }
           }
         if ((CEvaluationNode::type(child2->getType()) == NUMBER) && (fabs(child2->getValue()) < 1.0E-100))
           {
             // a + 0 -> a
             delete child2;
             return child1;
           }
         if (((child1->getType() == (Type)(FUNCTION | CEvaluationNodeFunction::MINUS))
              && (dynamic_cast<CEvaluationNode*>(child1->getChild())->buildInfix() == child2->buildInfix()))
             ||
             ((child2->getType() == (Type)(FUNCTION | CEvaluationNodeFunction::MINUS))
              && (dynamic_cast<CEvaluationNode*>(child2->getChild())->buildInfix() == child1->buildInfix())))
           {
             // -(a) + a  and  a + (-a)  -> 0
             CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "0.0");
             delete child1;
             delete child2;
             return newnode;
           }
         // default: copy
         CEvaluationNode *newnode = copyNode(child1, child2);
         return newnode;
       }
       case MINUS:
       {
         if (CEvaluationNode::type(child1->getType()) == NUMBER)
           {
             if (CEvaluationNode::type(child2->getType()) == NUMBER)
               {
                 // both children numbers ->calculate
                 std::stringstream tmp;
                 tmp.precision(18);
                 tmp << child1->getValue() - child2->getValue();
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), tmp.str());
                 delete child1;
                 delete child2;
                 return newnode;
               }
             if (fabs(child1->getValue()) < 1.0E-100)
               {
                 // 0-a -> -(a)
                 CEvaluationNode *newnode = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
                 newnode->addChild(child2, NULL);
                 delete child1;
                 return newnode;
               }
           }
         if ((CEvaluationNode::type(child2->getType()) == NUMBER) && (fabs(child2->getValue()) < 1.0E-100))
           {
             // a-0 -> a
             delete child2;
             return child1;
           }
         if (child1->buildInfix() == child2->buildInfix())
           {
             // a-a -> 0
             CEvaluationNode *newnode = CEvaluationNode::create((Type)(NUMBER | CEvaluationNodeNumber::DOUBLE), "0.0");
             delete child1;
             delete child2;
             return newnode;
           }
         // default:  a - b  ->  a + (-b)
         CEvaluationNode *newnode = CEvaluationNode::create((Type)(OPERATOR | PLUS), "+");
         CEvaluationNode *newchild2 = CEvaluationNode::create((Type)(FUNCTION | CEvaluationNodeFunction::MINUS), "-");
         newnode->addChild(child1, NULL);
         newnode->addChild(newchild2, child1);
         newchild2->addChild(child2, NULL);
         return newnode;
       }
       default:       //case MODULUS
       {
         CEvaluationNode *newnode = copyNode(child1, child2);
         return newnode;
       }
     }
 }
ASTNode * CEvaluationNodeOperator::toAST (const CCopasiDataModel * pDataModel) const virtual
Create a new ASTNode corresponding to this OperatorNode.
Returns
ASTNode* return a pointer to the newly created node;
Reimplemented from CEvaluationNode.
Definition at line 404 of file CEvaluationNodeOperator.cpp.
References CCopasiNode< _Data >::addChild(), createModuloTree(), DIVIDE, CCopasiNode< std::string >::getChild(), CCopasiNode< _Data >::getSibling(), CEvaluationNode::getType(), INVALID, MINUS, MODULUS, MULTIPLY, PLUS, POWER, CEvaluationNode::subType(), and CEvaluationNode::toAST().
 {
   SubType subType = (SubType)CEvaluationNode::subType(this->getType());
   ASTNode* node = new ASTNode();
   switch (subType)
     {
       case POWER:
         node->setType(AST_POWER);
         break;
       case MULTIPLY:
         node->setType(AST_TIMES);
         break;
       case DIVIDE:
         node->setType(AST_DIVIDE);
         break;
       case MODULUS:
         // replace this with a more complex subtree
         CEvaluationNodeOperator::createModuloTree(this, node, pDataModel);
         break;
       case PLUS:
         node->setType(AST_PLUS);
         break;
       case MINUS:
         node->setType(AST_MINUS);
         break;
       case INVALID:
         break;
     }
   // for all but INVALID and MODULUS two children have to be converted
   if (subType != INVALID && subType != MODULUS)
     {
       const CEvaluationNode* child1 = dynamic_cast<const CEvaluationNode*>(this->getChild());
       const CEvaluationNode* child2 = dynamic_cast<const CEvaluationNode*>(child1->getSibling());
       node->addChild(child1->toAST(pDataModel));
       node->addChild(child2->toAST(pDataModel));
     }
   return node;
 }
Member Data Documentation
CEvaluationNode* CEvaluationNodeOperator::mpLeft private
Definition at line 205 of file CEvaluationNodeOperator.h.
Referenced by calculate(), compile(), getBerkeleyMadonnaString(), getCCodeString(), getDisplayString(), getInfix(), getLeft(), getMMLString(), and getXPPString().
CEvaluationNode* CEvaluationNodeOperator::mpRight private
Definition at line 207 of file CEvaluationNodeOperator.h.
Referenced by calculate(), compile(), getBerkeleyMadonnaString(), getCCodeString(), getDisplayString(), getInfix(), getMMLString(), getRight(), and getXPPString().
The documentation for this class was generated from the following files:
CEvaluationNodeOperator.h
CEvaluationNodeOperator.cpp