COPASI API: CQModelValue Class Reference
CQModelValue Class Reference
#include <CQModelValue.h>
Public Member Functions
CQModelValue (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQModelValue ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Private Slots
void slotBtnCopy ()
void slotBtnDelete ()
void slotBtnNew ()
Slot to create a new quantity; activated whenever the New button is clicked.
void slotExpressionValid (bool valid)
void slotInitialExpressionValid (bool valid)
void slotInitialTypeChanged (bool useInitialAssignment)
void slotTypeChanged (int type)
Private Member Functions
void destroy ()
void init ()
void load ()
void save ()
Private Attributes
bool mChanged
bool mExpressionValid
bool mInitialExpressionValid
std::vector< int > mItemToType
std::string mKeyToCopy
CModelValue * mpModelValue
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 28 of file CQModelValue.h.
Constructor & Destructor Documentation
CQModelValue::CQModelValue (QWidget * parent = 0, const char * name = 0)
Definition at line 32 of file CQModelValue.cpp.
References init().
   : CopasiWidget(parent, name),
     mKeyToCopy("")
 {
   setupUi(this);
   init();
 }
CQModelValue::~CQModelValue ()
Definition at line 44 of file CQModelValue.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQModelValue::destroy () private
Definition at line 201 of file CQModelValue.cpp.
Referenced by ~CQModelValue().
 {}
bool CQModelValue::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 267 of file CQModelValue.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), load(), mKeyToCopy, CopasiWidget::mpListView, mpModelValue, CopasiWidget::mpObject, and ListViews::switchToOtherWidget().
 {
   mpModelValue = NULL;
   if (mKeyToCopy != "")
     {
       mpModelValue = dynamic_cast<CModelValue *>(CCopasiRootContainer::getKeyFactory()->get(mKeyToCopy));
       mKeyToCopy = "";
     }
   else
     {
       mpModelValue = dynamic_cast<CModelValue *>(mpObject);
     }
   if (!mpModelValue)
     {
       mpListView->switchToOtherWidget(115, "");
       return false;
     }
   load();
   mpModelValue = dynamic_cast<CModelValue *>(mpObject);
   return true;
 }
void CQModelValue::init () private
Definition at line 184 of file CQModelValue.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, FROM_UTF8, CQExpressionWidget::InitialExpression, mExpressionValid, mInitialExpressionValid, mItemToType, CModelEntity::ODE, CModelEntity::StatusName, and CQExpressionWidget::TransientExpression.
Referenced by CQModelValue().
 {
   mpComboBoxType->insertItem(mpComboBoxType->count(), FROM_UTF8(CModelEntity::StatusName[CModelEntity::FIXED]));
   mpComboBoxType->insertItem(mpComboBoxType->count(), FROM_UTF8(CModelEntity::StatusName[CModelEntity::ASSIGNMENT]));
   mpComboBoxType->insertItem(mpComboBoxType->count(), FROM_UTF8(CModelEntity::StatusName[CModelEntity::ODE]));
   mItemToType.push_back(CModelEntity::FIXED);
   mItemToType.push_back(CModelEntity::ASSIGNMENT);
   mItemToType.push_back(CModelEntity::ODE);
   mExpressionValid = false;
   mpExpressionEMW->mpExpressionWidget->setExpressionType(CQExpressionWidget::TransientExpression);
   mInitialExpressionValid = false;
   mpInitialExpressionEMW->mpExpressionWidget->setExpressionType(CQExpressionWidget::InitialExpression);
 }
bool CQModelValue::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 248 of file CQModelValue.cpp.
References CModelEntity::FIXED, mItemToType, and save().
Referenced by slotBtnNew().
 {
   if ((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()] != CModelEntity::FIXED)
     {
       // -- Expression --
       mpExpressionEMW->updateWidget();
     }
   if (mpBoxUseInitialExpression->isChecked())
     {
       // -- Initial Expression --
       mpInitialExpressionEMW->updateWidget();
     }
   save();
   return true;
 }
void CQModelValue::load () private
Load any saved values to the screen
Definition at line 297 of file CQModelValue.cpp.
References CModelEntity::ASSIGNMENT, FROM_UTF8, CModelEntity::getExpression(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CModelEntity::getRate(), CModelEntity::getStatus(), CModelEntity::getValue(), mChanged, mpModelValue, slotTypeChanged(), and CModelEntity::StatusName.
Referenced by enterProtected(), and update().
 {
   if (mpModelValue == NULL) return;
   // Type
   mpComboBoxType->setCurrentIndex(mpComboBoxType->findText(FROM_UTF8(CModelEntity::StatusName[mpModelValue->getStatus()])));
   // Initial Value
   mpEditInitialValue->setText(QString::number(mpModelValue->getInitialValue(), 'g', 10));
   // Current Value
   mpEditCurrentValue->setText(QString::number(mpModelValue->getValue(), 'g', 10));
   // Rate
   mpEditRate->setText(QString::number(mpModelValue->getRate(), 'g', 10));
   // Expression
   mpExpressionEMW->mpExpressionWidget->setExpression(mpModelValue->getExpression());
   // Update Expression Widget
   mpExpressionEMW->updateWidget();
   // Initial Expression
   mpInitialExpressionEMW->mpExpressionWidget->setExpression(mpModelValue->getInitialExpression());
   // Update Initial Expression Widget
   mpInitialExpressionEMW->updateWidget();
   // Type dependent display of values
   slotTypeChanged(mpComboBoxType->currentIndex());
   // Use Initial Expression
   if (mpModelValue->getStatus() == CModelEntity::ASSIGNMENT ||
       mpModelValue->getInitialExpression() == "")
     {
       mpBoxUseInitialExpression->setChecked(false);
       //      slotInitialTypeChanged(false);
     }
   else
     {
       mpBoxUseInitialExpression->setChecked(true);
       //      slotInitialTypeChanged(true);
     }
   mChanged = false;
 }
void CQModelValue::save () private
Save any inputs and set them as initial setting values
Definition at line 347 of file CQModelValue.cpp.
References CModelEntity::ASSIGNMENT, ListViews::CHANGE, CCopasiRootContainer::getDatamodelList(), CModelEntity::getExpression(), CModelEntity::getInitialExpression(), CModelEntity::getInitialValue(), CModelEntity::getStatus(), mChanged, mItemToType, CopasiWidget::mKey, ListViews::MODELVALUE, mpModelValue, CopasiWidget::protectedNotify(), CModelEntity::setExpression(), CModelEntity::setInitialExpression(), CModelEntity::setInitialValue(), and CModelEntity::setStatus().
Referenced by leave().
 {
   if (mpModelValue == NULL) return;
   // set status
   if (mpModelValue->getStatus() != (CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()])
     {
       mpModelValue->setStatus((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()]);
       mChanged = true;
     }
   // set initial value
   if (QString::number(mpModelValue->getInitialValue(), 'g', 10) != mpEditInitialValue->text() &&
       mpModelValue->getStatus() != CModelEntity::ASSIGNMENT)
     {
       mpModelValue->setInitialValue(mpEditInitialValue->text().toDouble());
       mChanged = true;
     }
   // set expression
   if (mpModelValue->getExpression() != mpExpressionEMW->mpExpressionWidget->getExpression())
     {
       //      mpModelValue->setExpression(((CQExpressionWidget *)mpEditExpression->widget(0))->getExpression());
       mpModelValue->setExpression(mpExpressionEMW->mpExpressionWidget->getExpression());
       mChanged = true;
     }
   // set initial expression
   if ((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()] != CModelEntity::ASSIGNMENT)
     {
       if (mpBoxUseInitialExpression->isChecked() &&
           mpModelValue->getInitialExpression() != mpInitialExpressionEMW->mpExpressionWidget->getExpression())
         {
           mpModelValue->setInitialExpression(mpInitialExpressionEMW->mpExpressionWidget->getExpression());
           mChanged = true;
         }
       else if (!mpBoxUseInitialExpression->isChecked() &&
                mpModelValue->getInitialExpression() != "")
         {
           mpModelValue->setInitialExpression("");
           mChanged = true;
         }
     }
   if (mChanged)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       (*CCopasiRootContainer::getDatamodelList())[0]->changed();
       protectedNotify(ListViews::MODELVALUE, ListViews::CHANGE, mKey);
     }
   mChanged = false;
 }
void CQModelValue::slotBtnCopy () private slot
Definition at line 76 of file CQModelValue.cpp.
References CopasiWidget::mKey, and mKeyToCopy.
 {
   mKeyToCopy = mKey;
 }
void CQModelValue::slotBtnDelete () private slot
Definition at line 81 of file CQModelValue.cpp.
References CQMessageBox::confirmDelete(), ListViews::DELETE, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CModelEntity::getDeletedObjects(), CCopasiDataModel::getModel(), CCopasiObject::getObjectName(), CopasiWidget::mKey, ListViews::MODELVALUE, mpModelValue, CopasiWidget::protectedNotify(), and CModel::removeModelValue().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return;
   if (mpModelValue == NULL)
     return;
   QMessageBox::StandardButton choice =
     CQMessageBox::confirmDelete(this, "quantity",
                                 FROM_UTF8(mpModelValue->getObjectName()),
                                 mpModelValue->getDeletedObjects());
   switch (choice)
     {
       case QMessageBox::Ok:
       {
         pDataModel->getModel()->removeModelValue(mKey);
         mpModelValue = NULL;
 #undef DELETE
         protectedNotify(ListViews::MODELVALUE, ListViews::DELETE, mKey);
         protectedNotify(ListViews::MODELVALUE, ListViews::DELETE, "");//Refresh all as there may be dependencies.
         break;
       }
       default:
         break;
     }
 }
void CQModelValue::slotBtnNew () private slot
Slot to create a new quantity; activated whenever the New button is clicked.
Definition at line 51 of file CQModelValue.cpp.
References ListViews::ADD, C_INVALID_INDEX, CCopasiRootContainer::getDatamodelList(), CModelEntity::getKey(), leave(), ListViews::MODELVALUE, CopasiWidget::mpListView, mpModelValue, CopasiWidget::protectedNotify(), ListViews::switchToOtherWidget(), and TO_UTF8.
 {
   // save the current setting values
   leave();
   // standard name
   std::string name = "quantity_1";
   // if the standard name already exists then creating the new event will fail
   // thus, a growing index will automatically be added to the standard name
   int i = 1;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   while (!(mpModelValue = (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->createModelValue(name)))
     {
       i++;
       name = "quantity_";
       name += TO_UTF8(QString::number(i));
     }
   std::string key = mpModelValue->getKey();
   protectedNotify(ListViews::MODELVALUE, ListViews::ADD, key);
   mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQModelValue::slotExpressionValid (bool valid) private slot
This function is used in case of not FIXED type
Definition at line 174 of file CQModelValue.cpp.
References mExpressionValid.
 {
   mExpressionValid = valid;
 }
void CQModelValue::slotInitialExpressionValid (bool valid) private slot
Definition at line 179 of file CQModelValue.cpp.
References mInitialExpressionValid.
 {
   mInitialExpressionValid = valid;
 }
void CQModelValue::slotInitialTypeChanged (bool useInitialAssignment) private slot
If the initial expression is chosen to be used by checking the mpBoxUseInitialExpression check box being represented by the boolean parameter useInitialAssignment (true if checked; false otherwise), COPASI will show the Initial Expression Widget with its correct push buttons. Otherwise, the widget and its buttons will be hidden.
Definition at line 406 of file CQModelValue.cpp.
References CModelEntity::ASSIGNMENT, and mItemToType.
Referenced by slotTypeChanged().
 {
   if (useInitialAssignment)  // use Initial Expression (ie. the mpBoxUseInitialExpression is checked)
     {
       // show label, widget, and the correct buttons
       mpLblInitialExpression->show();  // show the label
       mpInitialExpressionEMW->show(); // show the widget
       // enable the option of use Initial Value
       mpEditInitialValue->setEnabled(false);
       // update the Initial Expression Widget
       mpInitialExpressionEMW->updateWidget();
     }
   else  // mpBoxUseInitialExpression is not checked
     {
       // hide label, widget, and all buttons
       mpLblInitialExpression->hide();
       mpInitialExpressionEMW->hide();
       // enable the option of use Initial Value
       mpEditInitialValue->setEnabled((CModelEntity::Status) mItemToType[mpComboBoxType->currentIndex()] != CModelEntity::ASSIGNMENT);
       // we don't need to update the Initial Expression Widget
     }
 }
void CQModelValue::slotTypeChanged (int type) private slot
If the simulation type is changed then COPASI will automatically adjust its appearance, especially correlating to the Expression Widget and its buttons.
Definition at line 121 of file CQModelValue.cpp.
References CModelEntity::ASSIGNMENT, CModelEntity::FIXED, mItemToType, CModelEntity::ODE, and slotInitialTypeChanged().
Referenced by load().
 {
   switch ((CModelEntity::Status) mItemToType[type])
     {
       case CModelEntity::FIXED:
         // hide label, widget, and all buttons
         mpLblExpression->hide();
         mpExpressionEMW->hide();
         // enable the option of use Initial Expression
         mpBoxUseInitialExpression->setEnabled(true);
         slotInitialTypeChanged(mpBoxUseInitialExpression->isChecked());
         // we don't need to update the expression widget as it is already hidden
         break;
       case CModelEntity::ASSIGNMENT:
         // show label, widget, and correct buttons
         mpLblExpression->show();   // show the label
         mpExpressionEMW->show();  // show the widget
         // disable the option of use Initial Expression
         mpBoxUseInitialExpression->setEnabled(false);
         slotInitialTypeChanged(false);
         // update the expression widget
         mpExpressionEMW->updateWidget();
         break;
       case CModelEntity::ODE:
         // show label, widget, and correct buttons
         mpLblExpression->show();   // show the label
         mpExpressionEMW->show();  // show the widget
         // enable the option of use Initial Expression
         mpBoxUseInitialExpression->setEnabled(true);
         slotInitialTypeChanged(mpBoxUseInitialExpression->isChecked());
         // update the expression widget
         mpExpressionEMW->updateWidget();
         break;
       default:
         break;
     }
 }
bool CQModelValue::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 204 of file CQModelValue.cpp.
References ListViews::ADD, ListViews::DELETE, load(), CopasiWidget::mIgnoreUpdates, CopasiWidget::mKey, ListViews::MODEL, ListViews::MODELVALUE, mpModelValue, CopasiWidget::mpObject, and ListViews::STATE.
 {
   switch (objectType)
     {
       case ListViews::MODEL:
         // For a new model we need to remove references to no longer existing metabolites
         if (action == ListViews::ADD)
           {
             mKey = "";
             mpObject = NULL;
             mpModelValue = NULL;
           }
         break;
       case ListViews::MODELVALUE:
         // If the currently displayed metabolite is deleted we need to remove its references.
         if (action == ListViews::DELETE && mKey == key)
           {
             mKey = "";
             mpObject = NULL;
             mpModelValue = NULL;
           }
         break;
       case ListViews::STATE:
         break;
       default:
         return true;
         break;
     }
   if (isVisible() && !mIgnoreUpdates)
     load();
   return true;
 }
Member Data Documentation
bool CQModelValue::mChanged private
Definition at line 47 of file CQModelValue.h.
Referenced by load(), and save().
bool CQModelValue::mExpressionValid private
Definition at line 48 of file CQModelValue.h.
Referenced by init(), and slotExpressionValid().
bool CQModelValue::mInitialExpressionValid private
Definition at line 49 of file CQModelValue.h.
Referenced by init(), and slotInitialExpressionValid().
std::vector< int > CQModelValue::mItemToType private
Definition at line 45 of file CQModelValue.h.
Referenced by init(), leave(), save(), slotInitialTypeChanged(), and slotTypeChanged().
std::string CQModelValue::mKeyToCopy private
Definition at line 55 of file CQModelValue.h.
Referenced by enterProtected(), and slotBtnCopy().
CModelValue* CQModelValue::mpModelValue private
Definition at line 46 of file CQModelValue.h.
Referenced by enterProtected(), load(), save(), slotBtnDelete(), slotBtnNew(), and update().
The documentation for this class was generated from the following files:
CQModelValue.h
CQModelValue.cpp