COPASI API: CModelParameterGroup Class Reference
CModelParameterGroup Class Reference
#include <CModelParameterGroup.h>
Public Types
typedef std::vector
< CModelParameter * >
::const_iterator const_iterator
typedef std::vector
< CModelParameter * >
::iterator iterator
Public Types inherited from CModelParameter
enum CompareResult {
Obsolete, Missing, Modified, Conflict,
Identical
}
enum Framework { Concentration = 0, ParticleNumbers }
enum Type {
Model, Compartment, Species, ModelValue,
ReactionParameter, Reaction, Group, Set,
unknown
}
Public Member Functions
CModelParameter * add (const CModelParameter::Type &type)
void add (CModelParameter *pModelParameter)
iterator begin ()
const_iterator begin () const
void clear ()
CModelParameterGroup (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::Group)
CModelParameterGroup (const CModelParameterGroup &src, CModelParameterGroup *pParent, const bool &createMissing)
virtual void compile ()
virtual const CompareResult & diff (const CModelParameter &other, const CModelParameter::Framework &framework, const bool &createMissing=false)
iterator end ()
const_iterator end () const
virtual const CModelParameter * getChild (const size_t &index) const
CModelParameter * getModelParameter (const std::string &cn) const
CModelParameter * getModelParameter (const std::string &name, const CModelParameter::Type &type) const
virtual size_t getNumChildren () const
virtual bool refreshFromModel (const bool &modifyExistence)
void remove (CModelParameter *pModelParameter)
void remove (const size_t &index)
size_t size () const
virtual bool updateModel ()
virtual ~CModelParameterGroup ()
Public Member Functions inherited from CModelParameter
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
const CCopasiObjectName & getCN () const
const CompareResult & getCompareResult () const
size_t getIndex () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
virtual std::string getName () const
CCopasiObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
const std::string getUnit (const Framework &framework) const
virtual const double & getValue (const Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
virtual void setCN (const CCopasiObjectName &cn)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const double &value, const Framework &framework)
virtual ~CModelParameter ()
Protected Member Functions
void assignGroupContent (const CModelParameterGroup &src, const bool &createMissing)
CModelParameter * copy (const CModelParameter &src, const bool &createMissing)
Private Attributes
std::vector< CModelParameter * > mModelParameters
Additional Inherited Members
Static Public Attributes inherited from CModelParameter
static const char * TypeNames []
Static Protected Member Functions inherited from CModelParameter
static std::string nameFromCN (const CCopasiObjectName &cn)
Protected Attributes inherited from CModelParameter
CRegisteredObjectName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CCopasiObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Detailed Description
Definition at line 17 of file CModelParameterGroup.h.
Member Typedef Documentation
typedef std::vector< CModelParameter * >::const_iterator CModelParameterGroup::const_iterator
Definition at line 21 of file CModelParameterGroup.h.
typedef std::vector< CModelParameter * >::iterator CModelParameterGroup::iterator
Definition at line 20 of file CModelParameterGroup.h.
Constructor & Destructor Documentation
CModelParameterGroup::CModelParameterGroup (CModelParameterGroup * pParent, const CModelParameter::Type & type = CModelParameter::Group)
Constructor
Parameters
CModelParameterGroup * pParent
const CModelParameter::Type & type (default: CModelParameter::Group)
Definition at line 11 of file CModelParameterGroup.cpp.
Referenced by add(), and copy().
                                                                                                           :
   CModelParameter(pParent, type),
   mModelParameters()
 {}
CModelParameterGroup::CModelParameterGroup (const CModelParameterGroup & src, CModelParameterGroup * pParent, const bool & createMissing)
Copy constructor
Parameters
const CModelParameterGroup & src
CModelParameterGroup * pParent
const bool & createMissing
Definition at line 16 of file CModelParameterGroup.cpp.
References assignGroupContent().
                                :
   CModelParameter(src, pParent),
   mModelParameters()
 {
   assignGroupContent(src, createMissing);
 }
CModelParameterGroup::~CModelParameterGroup () virtual
Destructor
Definition at line 26 of file CModelParameterGroup.cpp.
References clear().
 {
   clear();
 }
Member Function Documentation
CModelParameter * CModelParameterGroup::add (const CModelParameter::Type & type)
Add parameter of the given type to the group and return a pointer to it
Parameters
const CModelParameter::Type & type
Returns
CModelParameter * pParameter
Definition at line 95 of file CModelParameterGroup.cpp.
References CModelParameter::CModelParameter(), CModelParameterGroup(), CModelParameter::Compartment, CModelParameter::Group, CModelParameter::Model, CModelParameter::ModelValue, CModelParameter::Reaction, CModelParameter::ReactionParameter, and CModelParameter::Species.
Referenced by CModelParameterSet::createFromModel().
 {
   CModelParameter * pModelParameter = NULL;
   switch (type)
     {
       case Compartment:
         pModelParameter = new CModelParameterCompartment(this);
         break;
       case Species:
         pModelParameter = new CModelParameterSpecies(this);
         break;
       case ReactionParameter:
         pModelParameter = new CModelParameterReactionParameter(this, type);
         break;
       case Model:
       case ModelValue:
         pModelParameter = new CModelParameter(this, type);
         break;
       case Reaction:
       case Group:
         pModelParameter = new CModelParameterGroup(this, type);
         break;
       default:
         return pModelParameter;
         break;
     }
   add(pModelParameter);
   return pModelParameter;
 }
void CModelParameterGroup::add (CModelParameter * pModelParameter)
Add the given parameter to the group. Note, the parent of the parameter is not updated
Parameters
CModelParameter * pModelParameter
Definition at line 133 of file CModelParameterGroup.cpp.
References mModelParameters.
 {
   mModelParameters.push_back(pModelParameter);
 }
void CModelParameterGroup::assignGroupContent (const CModelParameterGroup & src, const bool & createMissing) protected
Assign the content of the source group to this, i.e., copy all contained parameters.
Parameters
const CModelParameterGroup & src
const bool & createMissing
Definition at line 31 of file CModelParameterGroup.cpp.
References begin(), clear(), copy(), end(), and CModelParameter::Missing.
Referenced by CModelParameterSet::assignSetContent(), and CModelParameterGroup().
 {
   clear();
   const_iterator itSrc = src.begin();
   const_iterator endSrc = src.end();
   for (; itSrc != endSrc; ++itSrc)
     {
       if (createMissing ||
           (*itSrc)->getCompareResult() != Missing)
         {
           copy(**itSrc, createMissing);
         }
     }
 }
CModelParameterGroup::iterator CModelParameterGroup::begin ()
Retrieve the iterator pointing to the first contained parameter.
Returns
iterator begin
Definition at line 169 of file CModelParameterGroup.cpp.
References mModelParameters.
Referenced by applyValueToParameterSet(), assignGroupContent(), CQParameterOverviewWidget::buildSelectionList(), clear(), compile(), diff(), CModelParameter::getIndex(), getModelParameter(), CQParameterOverviewDM::getRow(), CQParameterOverviewDM::index(), refreshFromModel(), remove(), CCopasiXML::saveModel(), and updateModel().
 {
   return mModelParameters.begin();
 }
CModelParameterGroup::const_iterator CModelParameterGroup::begin () const
Retrieve the const_iterator pointing to the first contained parameter.
Returns
const_iterator begin
Definition at line 179 of file CModelParameterGroup.cpp.
References mModelParameters.
 {
   return mModelParameters.begin();
 }
void CModelParameterGroup::clear ()
Clear the contained parameters and delete them.
Definition at line 202 of file CModelParameterGroup.cpp.
References begin(), end(), mModelParameters, and pdelete.
Referenced by assignGroupContent(), CModelParameterSet::createFromModel(), and ~CModelParameterGroup().
 {
   // Clear existing model parameters.
   iterator it = begin();
   iterator End = end();
   for (; it != End; ++it)
     {
       (*it)->setParent(NULL);
       pdelete(*it);
     }
   mModelParameters.clear();
 }
void CModelParameterGroup::compile () virtual
Compile the parameter
Reimplemented from CModelParameter.
Definition at line 189 of file CModelParameterGroup.cpp.
References begin(), CModelParameter::compile(), and end().
Referenced by CModelParameterSet::assignSetContent(), CModelParameterSet::CModelParameterSet(), CModelParameterSet::createFromModel(), CQParameterOverviewWidget::enterProtected(), and CModelParameterSet::updateModel().
 {
   CModelParameter::compile();
   iterator it = begin();
   iterator End = end();
   for (; it != End; ++it)
     {
       (*it)->compile();
     }
 }
CModelParameter * CModelParameterGroup::copy (const CModelParameter & src, const bool & createMissing) protected
Copy the existing parameter and add it to the group
Parameters
const CModelParameter & src
const bool & createMissing
Returns
CModelParameter * pCopy
Copy the existing parameter and add it to the group
Parameters
const CModelParameter & src
Returns
CModelParameter * pCopy
Definition at line 54 of file CModelParameterGroup.cpp.
References CModelParameter::CModelParameter(), CModelParameterGroup(), CModelParameter::Compartment, CModelParameter::getType(), CModelParameter::Group, mModelParameters, CModelParameter::Model, CModelParameter::ModelValue, CModelParameter::Reaction, CModelParameter::ReactionParameter, and CModelParameter::Species.
Referenced by assignGroupContent(), and diff().
 {
   CModelParameter * pCopy = NULL;
   switch (src.getType())
     {
       case Compartment:
         pCopy = new CModelParameterCompartment(*static_cast< const  CModelParameterCompartment * >(&src), this);
         break;
       case Species:
         pCopy = new CModelParameterSpecies(*static_cast< const CModelParameterSpecies * >(&src), this);
         break;
       case ReactionParameter:
         pCopy = new CModelParameterReactionParameter(*static_cast< const  CModelParameterReactionParameter * >(&src), this);
         break;
       case Model:
       case ModelValue:
         pCopy = new CModelParameter(src, this);
         break;
       case Reaction:
       case Group:
         pCopy = new CModelParameterGroup(*static_cast< const  CModelParameterGroup * >(&src), this, createMissing);
         break;
       default:
         break;
     }
   if (pCopy)
     {
       mModelParameters.push_back(pCopy);
     }
   return pCopy;
 }
const CModelParameter::CompareResult & CModelParameterGroup::diff (const CModelParameter & other, const CModelParameter::Framework & framework, const bool & createMissing = false) virtual
Compare the parameter to an other
Parameters
const CModelParameter & other
const CModelParameter::Framework & framework
const bool & createMissing = false
Reimplemented from CModelParameter.
Definition at line 218 of file CModelParameterGroup.cpp.
References begin(), copy(), end(), CModelParameter::getType(), CModelParameter::Group, CModelParameter::Identical, CModelParameter::mCompareResult, CModelParameter::Missing, CModelParameter::Modified, CModelParameter::Obsolete, CModelParameter::Reaction, CModelParameter::Set, and CModelParameter::setCompareResult().
Referenced by CModelParameterSet::compareWithModel(), and CQParameterOverviewWidget::leave().
 {
   // We can only work on reactions, groups or sets.
   assert(other.getType() == Reaction ||
          other.getType() == Group ||
          other.getType() == Set);
   if (mCompareResult == Missing ||
       mCompareResult == Obsolete)
     {
       return mCompareResult;
     }
   mCompareResult = Identical;
   const CModelParameterGroup * pOther = dynamic_cast< const CModelParameterGroup * >(&other);
   const_iterator itConst = pOther->begin();
   const_iterator endConst = pOther->end();
   std::map< CCopasiObjectName, CModelParameter * > Map;
   for (; itConst != endConst; ++itConst)
     {
       Map[(*itConst)->getCN()] = *itConst;
     }
   iterator itThis = begin();
   iterator endThis = end();
   for (; itThis != endThis; ++itThis)
     {
       std::map< CCopasiObjectName, CModelParameter * >::const_iterator itOther = Map.find((*itThis)->getCN());
       if (itOther == Map.end())
         {
           (*itThis)->setCompareResult(Obsolete);
           mCompareResult = Modified;
           continue;
         }
       if ((*itThis)->diff(*itOther->second, framework, createMissing) != Identical)
         {
           mCompareResult = Modified;
         }
       Map.erase(itOther->first);
     }
   if (createMissing)
     {
       std::map< CCopasiObjectName, CModelParameter * >::const_iterator itMissing = Map.begin();
       std::map< CCopasiObjectName, CModelParameter * >::const_iterator endMissing = Map.end();
       for (; itMissing != endMissing; ++itMissing)
         {
           CModelParameter * pMissing = copy(*itMissing->second, createMissing);
           if (pMissing != NULL)
             {
               pMissing->setCompareResult(Missing);
             }
           mCompareResult = Modified;
         }
     }
   else if (Map.size() > 0)
     {
       std::map< CCopasiObjectName, CModelParameter * >::const_iterator itMissing = Map.begin();
       std::map< CCopasiObjectName, CModelParameter * >::const_iterator endMissing = Map.end();
       for (; itMissing != endMissing; ++itMissing)
         {
           if (itMissing->second->getCompareResult() != CModelParameter::Missing)
             {
               mCompareResult = Modified;
               break;
             }
         }
     }
   return mCompareResult;
 }
CModelParameterGroup::iterator CModelParameterGroup::end ()
Retrieve the iterator pointing past the last contained parameter.
Returns
iterator end
Definition at line 174 of file CModelParameterGroup.cpp.
References mModelParameters.
Referenced by applyValueToParameterSet(), assignGroupContent(), CQParameterOverviewWidget::buildSelectionList(), clear(), compile(), diff(), CModelParameter::getIndex(), getModelParameter(), CQParameterOverviewDM::getRow(), refreshFromModel(), remove(), CCopasiXML::saveModel(), and updateModel().
 {
   return mModelParameters.end();
 }
CModelParameterGroup::const_iterator CModelParameterGroup::end () const
Retrieve the const_iterator pointing past the last contained parameter.
Returns
const_iterator end
Definition at line 184 of file CModelParameterGroup.cpp.
References mModelParameters.
 {
   return mModelParameters.end();
 }
const CModelParameter * CModelParameterGroup::getChild (const size_t & index) const virtual
Reimplemented from CModelParameter.
Definition at line 427 of file CModelParameterGroup.cpp.
References mModelParameters, and size().
 {
   if (index < size())
     {
       return mModelParameters[index];
     }
   return NULL;
 }
CModelParameter * CModelParameterGroup::getModelParameter (const std::string & cn) const
Retrieve a pointer to the parameter with the given CN
Parameters
const std::string & cn
Returns
CModelParameter * pModelParameter
Definition at line 370 of file CModelParameterGroup.cpp.
References begin(), end(), getModelParameter(), CModelParameter::Group, CModelParameter::Reaction, and CModelParameter::Set.
Referenced by CQParameterOverviewDM::assignmentData(), CQParameterOverviewWidget::buildSelectionList(), CModelParameterSpecies::compile(), CModelParameterReactionParameter::compile(), getModelParameter(), CModelParameter::refreshFromModel(), and CQParameterOverviewDM::setData().
 {
   CModelParameter * pModelParameter = NULL;
   const_iterator it = begin();
   const_iterator End = end();
   for (; it != End && pModelParameter == NULL; ++it)
     {
       if (cn == (*it)->getCN())
         {
           pModelParameter = *it;
         }
       else if ((*it)->getType() == CModelParameter::Reaction ||
                (*it)->getType() == CModelParameter::Group ||
                (*it)->getType() == CModelParameter::Set)
         {
           pModelParameter = static_cast< const CModelParameterGroup * >(*it)->getModelParameter(cn);
         }
     }
   return pModelParameter;
 }
CModelParameter * CModelParameterGroup::getModelParameter (const std::string & name, const CModelParameter::Type & type) const
Retrieve a pointer to the parameter with the given name and type
Parameters
const std::string & name
const CModelParameter::Type & type
Returns
CModelParameter * pModelParameter
Definition at line 394 of file CModelParameterGroup.cpp.
References begin(), end(), getModelParameter(), CModelParameter::Group, CModelParameter::Reaction, and CModelParameter::Set.
 {
   CModelParameter * pModelParameter = NULL;
   const_iterator it = begin();
   const_iterator End = end();
   for (; it != End && pModelParameter == NULL; ++it)
     {
       if (type == (*it)->getType() &&
           name == (*it)->getName())
         {
           pModelParameter = *it;
         }
       else if ((*it)->getType() == CModelParameter::Reaction ||
                (*it)->getType() == CModelParameter::Group ||
                (*it)->getType() == CModelParameter::Set)
         {
           pModelParameter = static_cast< const CModelParameterGroup * >(*it)->getModelParameter(name, type);
         }
     }
   return pModelParameter;
 }
size_t CModelParameterGroup::getNumChildren () const virtual
Reimplemented from CModelParameter.
Definition at line 421 of file CModelParameterGroup.cpp.
References size().
 {
   return size();
 }
bool CModelParameterGroup::refreshFromModel (const bool & modifyExistence) virtual
Refresh the parameter from the corresponding model object
Parameters
const bool & modifyExistence
Reimplemented from CModelParameter.
Definition at line 322 of file CModelParameterGroup.cpp.
References begin(), end(), CModelParameter::Identical, CModelParameter::mCompareResult, CModelParameter::Missing, and CModelParameter::Obsolete.
Referenced by CModel::refreshActiveParameterSet(), and CCopasiDataModel::saveModel().
 {
   bool success = true;
   if (modifyExistence)
     {
       if (mCompareResult == CModelParameter::Obsolete)
         {
           delete this;
           return true;
         }
       if (mCompareResult == CModelParameter::Missing)
         {
           mCompareResult = CModelParameter::Identical;
         }
     }
   iterator it = begin();
   iterator End = end();
   std::vector< CModelParameter * > ToBeDeleted;
   for (; it != End; ++it)
     {
       if (modifyExistence &&
           (*it)->getCompareResult() == CModelParameter::Obsolete)
         {
           ToBeDeleted.push_back(*it);
         }
       else
         {
           success &= (*it)->refreshFromModel(modifyExistence);
         }
     }
   std::vector< CModelParameter * >::iterator itDelete = ToBeDeleted.begin();
   std::vector< CModelParameter * >::iterator endDelete = ToBeDeleted.end();
   for (; itDelete != endDelete; ++itDelete)
     {
       success &= (*itDelete)->refreshFromModel(modifyExistence);
     }
   return success;
 }
void CModelParameterGroup::remove (CModelParameter * pModelParameter)
Remove the given parameter from the group. Note, the parameter is not deleted.
Parameters
CModelParameter * pModelParameter
Definition at line 138 of file CModelParameterGroup.cpp.
References begin(), end(), and mModelParameters.
Referenced by CModelParameter::~CModelParameter().
 {
   iterator it = begin();
   iterator End = end();
   for (; it != End; ++it)
     {
       if (*it == pModelParameter)
         {
           mModelParameters.erase(it);
           break;
         }
     }
 }
void CModelParameterGroup::remove (const size_t & index)
Remove the indexed parameter from the group and delete it
Parameters
const size_t & index
Definition at line 153 of file CModelParameterGroup.cpp.
References mModelParameters, and pdelete.
 {
   if (index < mModelParameters.size())
     {
       iterator it = mModelParameters.begin() + index;
       pdelete(*it);
       mModelParameters.erase(it);
     }
 }
size_t CModelParameterGroup::size () const
Retrieve the size of the group
Returns
size_t size
Definition at line 164 of file CModelParameterGroup.cpp.
References mModelParameters.
Referenced by getChild(), getNumChildren(), and CQParameterOverviewDM::index().
 {
   return mModelParameters.size();
 }
bool CModelParameterGroup::updateModel () virtual
Update the corresponding model object with the current parameter settings
Reimplemented from CModelParameter.
Reimplemented in CModelParameterSet.
Definition at line 306 of file CModelParameterGroup.cpp.
References begin(), and end().
Referenced by CModelParameterSet::updateModel().
 {
   bool success = true;
   iterator it = begin();
   iterator End = end();
   for (; it != End; ++it)
     {
       success &= (*it)->updateModel();
     }
   return success;
 }
Member Data Documentation
std::vector< CModelParameter * > CModelParameterGroup::mModelParameters private
A vector of pointer to the contained parameters.
Definition at line 179 of file CModelParameterGroup.h.
Referenced by add(), begin(), clear(), copy(), end(), getChild(), remove(), and size().
The documentation for this class was generated from the following files:
CModelParameterGroup.h
CModelParameterGroup.cpp