COPASI API: CMCAResultWidget Class Reference
CMCAResultWidget Class Reference
#include <CMCAResultWidget.h>
Public Member Functions
CMCAResultWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool leave ()
bool loadFromBackend ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CMCAResultWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
bool saveToBackend ()
Protected Attributes
CMCAResultSubwidget * mCentralWidget
QGridLayout * mWidgetLayout
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 24 of file CMCAResultWidget.h.
Constructor & Destructor Documentation
CMCAResultWidget::CMCAResultWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 32 of file CMCAResultWidget.cpp.
References mCentralWidget, and mWidgetLayout.
   : CopasiWidget(parent, name, fl)
 {
   if (!name)
     setObjectName("CMCAResultWidget");
   setWindowTitle(trUtf8("CMCAResultWidget"));
   mWidgetLayout = new QGridLayout(this);
   mWidgetLayout->setObjectName("Layout");
   mCentralWidget = new CMCAResultSubwidget(this, "CMCAResultSubwidget");
   mWidgetLayout->addWidget(mCentralWidget, 0, 0);
 }
CMCAResultWidget::~CMCAResultWidget ()
Definition at line 50 of file CMCAResultWidget.cpp.
 {}
Member Function Documentation
bool CMCAResultWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 87 of file CMCAResultWidget.cpp.
 {
   return true;
 }
bool CMCAResultWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 82 of file CMCAResultWidget.cpp.
 {
   return true;
 }
bool CMCAResultWidget::loadFromBackend ()
Definition at line 55 of file CMCAResultWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), CMCAResultSubwidget::loadAll(), mCentralWidget, and pTask.
Referenced by CQMCAWidget::taskFinishedEvent().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CMCATask * pTask =
     dynamic_cast<CMCATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Metabolic Control Analysis"]);
   if (!pTask) return false;
   mCentralWidget->loadAll(dynamic_cast<CMCAMethod*>(pTask->getMethod()));
   return true;
 }
bool CMCAResultWidget::saveToBackend () protected
Definition at line 67 of file CMCAResultWidget.cpp.
 {
   return true;
 }
bool CMCAResultWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 72 of file CMCAResultWidget.cpp.
References ListViews::ADD, CMCAResultSubwidget::loadAll(), mCentralWidget, and ListViews::MODEL.
 {
   if (objectType == ListViews::MODEL && action == ListViews::ADD)
     mCentralWidget->loadAll(NULL);
   return true;
 }
Member Data Documentation
CMCAResultSubwidget* CMCAResultWidget::mCentralWidget protected
Definition at line 44 of file CMCAResultWidget.h.
Referenced by CMCAResultWidget(), loadFromBackend(), and update().
QGridLayout* CMCAResultWidget::mWidgetLayout protected
Definition at line 42 of file CMCAResultWidget.h.
Referenced by CMCAResultWidget().
The documentation for this class was generated from the following files:
CMCAResultWidget.h
CMCAResultWidget.cpp