COPASI API: CQLayoutThread Class Reference
CQLayoutThread Class Reference
#include <CQLayoutThread.h>
Public Slots
void terminateLayout ()
Signals
void layoutFinished ()
void layoutStateChanged (QSharedPointer< CLayoutState > newState)
void layoutUpdated ()
Public Member Functions
CQLayoutThread (QWidget *parent)
void createSpringLayout (CLayout *layout, int numIntervals=1000, int updateWait=100)
void finalize ()
QDockWidget * getParameterWindow ()
bool pause ()
void randomizeLayout (CLayout *layout)
void resume ()
void stopLayout ()
virtual ~CQLayoutThread ()
Protected Member Functions
virtual void run ()
Protected Attributes
int mNumIterations
bool mPause
QWaitCondition mPauseCond
CCopasiSpringLayout * mpCurrent
CLayout * mpCurrentLayout
CQSpringLayoutParameterWindow * mpParameterWindow
bool mStopLayout
QMutex mSync
int mUpdateWait
Detailed Description
Definition at line 25 of file CQLayoutThread.h.
Constructor & Destructor Documentation
CQLayoutThread::CQLayoutThread (QWidget * parent)
Definition at line 20 of file CQLayoutThread.cpp.
References CopasiUI3Window::getMainWindow(), mpParameterWindow, and terminateLayout().
   : QThread(parent)
   , mpParameterWindow(NULL)
   , mpCurrentLayout(NULL)
   , mNumIterations(1000)
   , mUpdateWait(100)
   , mStopLayout(false)
   , mPause(false)
   , mpCurrent(NULL)
 {
   qRegisterMetaType<QSharedPointer<CLayoutState> >();
   mpParameterWindow = new CQSpringLayoutParameterWindow("Layout Parameters", parent);
   connect(CopasiUI3Window::getMainWindow(), SIGNAL(signalQuit()), this, SLOT(terminateLayout()), Qt::DirectConnection);
 }
CQLayoutThread::~CQLayoutThread () virtual
Definition at line 70 of file CQLayoutThread.cpp.
References mpCurrent, mpParameterWindow, and pdelete.
 {
   pdelete(mpCurrent);
   pdelete(mpParameterWindow);
 }
Member Function Documentation
void CQLayoutThread::createSpringLayout (CLayout * layout, int numIntervals = 1000, int updateWait = 100)
Run the layout algorithm on the given layout
Definition at line 88 of file CQLayoutThread.cpp.
References mNumIterations, mpCurrentLayout, and mUpdateWait.
Referenced by CQNewMainWindow::createSpringLayout(), and CQAnimationWindow::slotAutoLayout().
 {
   mpCurrentLayout = layout;
   mNumIterations = numIntervals;
   mUpdateWait = updateWait;
   start();
 }
void CQLayoutThread::finalize (void)
Definition at line 96 of file CQLayoutThread.cpp.
References CCopasiSpringLayout::finalizeState(), and mpCurrent.
Referenced by run().
 {
   if (mpCurrent == NULL) return;
   mpCurrent->finalizeState();
 }
QDockWidget * CQLayoutThread::getParameterWindow ()
Definition at line 65 of file CQLayoutThread.cpp.
References mpParameterWindow.
Referenced by CQNewMainWindow::CQNewMainWindow(), and CQAnimationWindow::init().
 {
   return mpParameterWindow;
 }
void CQLayoutThread::layoutFinished () signal
Referenced by run().
void CQLayoutThread::layoutStateChanged (QSharedPointer< CLayoutState > newState) signal
Referenced by randomizeLayout(), and run().
void CQLayoutThread::layoutUpdated () signal
Referenced by randomizeLayout(), and run().
bool CQLayoutThread::pause ()
Definition at line 53 of file CQLayoutThread.cpp.
References mPause, and mSync.
 {
   if (mSync.tryLock(30))
     {
       mPause = true;
       mSync.unlock();
       return true;
     }
   return false;
 }
void CQLayoutThread::randomizeLayout (CLayout * layout)
Definition at line 76 of file CQLayoutThread.cpp.
References CQSpringLayoutParameterWindow::getLayoutParameters(), layoutStateChanged(), layoutUpdated(), mpParameterWindow, and CCopasiSpringLayout::randomize().
Referenced by CQNewMainWindow::randomizeLayout(), and CQAnimationWindow::slotRandomizeLayout().
 {
   if (layout == NULL || mpParameterWindow == NULL)
     return;
   CCopasiSpringLayout l(layout, &mpParameterWindow->getLayoutParameters());
   l.randomize();
   emit layoutStateChanged(QSharedPointer<CLayoutState>(new CLayoutState(layout)));
   emit layoutUpdated();
 }
void CQLayoutThread::resume ()
Definition at line 45 of file CQLayoutThread.cpp.
References mPause, mPauseCond, and mSync.
 {
   mSync.lock();
   mPause = false;
   mSync.unlock();
   mPauseCond.wakeAll();
 }
void CQLayoutThread::run () protected virtual
Definition at line 109 of file CQLayoutThread.cpp.
References CCopasiSpringLayout::createVariables(), finalize(), CQSpringLayoutParameterWindow::getLayoutParameters(), layoutFinished(), layoutStateChanged(), layoutUpdated(), mNumIterations, mPause, mPauseCond, mpCurrent, mpCurrentLayout, mpParameterWindow, mStopLayout, mSync, mUpdateWait, and CLayoutEngine::step().
 {
   if (mpCurrentLayout == NULL)
     return;
   mStopLayout = false;
   if (mpCurrent != NULL)
     {
       delete mpCurrent;
       mpCurrent = NULL;
     }
   // create the spring layout
   mpCurrent = new CCopasiSpringLayout(mpCurrentLayout, &mpParameterWindow->getLayoutParameters());
   mpCurrent ->createVariables();
   CLayoutEngine le(mpCurrent, false);
   int i = 0;
   qint64 tick, last = 0;
   double pot, oldPot = -1.0;
   for (; (i < mNumIterations) && (mStopLayout) == false; ++i)
     {
       mSync.lock();
       if (mPause)
         mPauseCond.wait(&mSync);
       //test again, in case we should stop after the pause
       if (mStopLayout)
         {
           mSync.unlock();
           break;
         }
       pot = le.step();
       // no more working on the layout, release lock
       mSync.unlock();
       if (pot == 0.0 || fabs((pot - oldPot) / pot) < 1e-9)
         {
           break;
         }
       else
         {
           oldPot = pot;
         }
       tick = QDateTime::currentMSecsSinceEpoch();
       if (mUpdateWait != 0 && (tick - last > mUpdateWait))
         {
           last = tick;
           // calculate new curves and emit state
           finalize();
           emit layoutStateChanged(QSharedPointer<CLayoutState>(new CLayoutState(mpCurrentLayout)));
           emit layoutUpdated();
         }
     }
   // calculate new curves and emit state
   finalize();
   emit layoutStateChanged(QSharedPointer<CLayoutState>(new CLayoutState(mpCurrentLayout)));
   emit layoutUpdated();
   emit layoutFinished();
 }
void CQLayoutThread::stopLayout ()
Definition at line 103 of file CQLayoutThread.cpp.
References mPauseCond, and mStopLayout.
Referenced by CQAnimationWindow::closeEvent(), CQNewMainWindow::randomizeLayout(), CQAnimationWindow::slotAutoLayout(), CQAnimationWindow::slotRandomizeLayout(), CQNewMainWindow::slotStopClicked(), and CQAnimationWindow::toggleUI().
 {
   mStopLayout = true;
   mPauseCond.wakeAll();
 }
void CQLayoutThread::terminateLayout () slot
Definition at line 35 of file CQLayoutThread.cpp.
References mPauseCond, mStopLayout, and mSync.
Referenced by CQLayoutThread(), CQAnimationWindow::~CQAnimationWindow(), and CQNewMainWindow::~CQNewMainWindow().
 {
   mSync.lock();
   mStopLayout = true;
   mPauseCond.wakeAll();
   mSync.unlock();
   wait();
 }
Member Data Documentation
int CQLayoutThread::mNumIterations protected
Number of Iterations the layout algorithm will run
Definition at line 73 of file CQLayoutThread.h.
Referenced by createSpringLayout(), and run().
bool CQLayoutThread::mPause protected
Definition at line 88 of file CQLayoutThread.h.
Referenced by pause(), resume(), and run().
QWaitCondition CQLayoutThread::mPauseCond protected
Definition at line 87 of file CQLayoutThread.h.
Referenced by resume(), run(), stopLayout(), and terminateLayout().
CCopasiSpringLayout* CQLayoutThread::mpCurrent protected
Definition at line 89 of file CQLayoutThread.h.
Referenced by finalize(), run(), and ~CQLayoutThread().
CLayout* CQLayoutThread::mpCurrentLayout protected
The current layout
Definition at line 68 of file CQLayoutThread.h.
Referenced by createSpringLayout(), and run().
CQSpringLayoutParameterWindow* CQLayoutThread::mpParameterWindow protected
The parameter window
Definition at line 63 of file CQLayoutThread.h.
Referenced by CQLayoutThread(), getParameterWindow(), randomizeLayout(), run(), and ~CQLayoutThread().
bool CQLayoutThread::mStopLayout protected
boolean indicating whether the layout algorithm should stop
Definition at line 83 of file CQLayoutThread.h.
Referenced by run(), stopLayout(), and terminateLayout().
QMutex CQLayoutThread::mSync protected
Definition at line 86 of file CQLayoutThread.h.
Referenced by pause(), resume(), run(), and terminateLayout().
int CQLayoutThread::mUpdateWait protected
Number of msecs to wait between updates, use 0 to disable updates
Definition at line 78 of file CQLayoutThread.h.
Referenced by createSpringLayout(), and run().
The documentation for this class was generated from the following files:
CQLayoutThread.h
CQLayoutThread.cpp