COPASI API: CModelParameterSet Class Reference
CModelParameterSet Class Reference
#include <CModelParameterSet.h>
Public Member Functions
void assignSetContent (const CModelParameterSet &src, const bool &createMissing)
CModelParameterSet (const std::string &name, const CCopasiContainer *pParent=NULL)
CModelParameterSet (const CModelParameterSet &src, const CCopasiContainer *pParent, const bool &createMissing=false)
bool compareWithModel (const CModelParameter::Framework &framework)
void createFromModel ()
virtual const std::string & getKey () const
CModel * getModel () const
virtual std::string getName () const
bool isActive () const
bool saveToStream (std::ostream &os, const CModelParameter::Framework &framework, const std::string &mode, const std::string &separator)
void setModel (const CModel *pModel)
virtual bool setObjectParent (const CCopasiContainer *pParent)
virtual bool updateModel ()
virtual ~CModelParameterSet ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CModelParameterGroup
CModelParameter * add (const CModelParameter::Type &type)
void add (CModelParameter *pModelParameter)
iterator begin ()
const_iterator begin () const
void clear ()
CModelParameterGroup (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::Group)
CModelParameterGroup (const CModelParameterGroup &src, CModelParameterGroup *pParent, const bool &createMissing)
virtual void compile ()
virtual const CompareResult & diff (const CModelParameter &other, const CModelParameter::Framework &framework, const bool &createMissing=false)
iterator end ()
const_iterator end () const
virtual const CModelParameter * getChild (const size_t &index) const
CModelParameter * getModelParameter (const std::string &cn) const
CModelParameter * getModelParameter (const std::string &name, const CModelParameter::Type &type) const
virtual size_t getNumChildren () const
virtual bool refreshFromModel (const bool &modifyExistence)
void remove (CModelParameter *pModelParameter)
void remove (const size_t &index)
size_t size () const
virtual ~CModelParameterGroup ()
Public Member Functions inherited from CModelParameter
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
const CCopasiObjectName & getCN () const
const CompareResult & getCompareResult () const
size_t getIndex () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
CCopasiObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
const std::string getUnit (const Framework &framework) const
virtual const double & getValue (const Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
virtual void setCN (const CCopasiObjectName &cn)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const double &value, const Framework &framework)
virtual ~CModelParameter ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Private Attributes
std::string mKey
CModel * mpModel
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CModelParameterGroup
typedef std::vector
< CModelParameter * >
::const_iterator const_iterator
typedef std::vector
< CModelParameter * >
::iterator iterator
Public Types inherited from CModelParameter
enum CompareResult {
Obsolete, Missing, Modified, Conflict,
Identical
}
enum Framework { Concentration = 0, ParticleNumbers }
enum Type {
Model, Compartment, Species, ModelValue,
ReactionParameter, Reaction, Group, Set,
unknown
}
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Static Public Attributes inherited from CModelParameter
static const char * TypeNames []
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Member Functions inherited from CModelParameterGroup
void assignGroupContent (const CModelParameterGroup &src, const bool &createMissing)
CModelParameter * copy (const CModelParameter &src, const bool &createMissing)
Static Protected Member Functions inherited from CModelParameter
static std::string nameFromCN (const CCopasiObjectName &cn)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CModelParameter
CRegisteredObjectName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CCopasiObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Protected Attributes inherited from CAnnotation
std::string mKey
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 17 of file CModelParameterSet.h.
Constructor & Destructor Documentation
CModelParameterSet::CModelParameterSet (const std::string & name, const CCopasiContainer * pParent = NULL)
Constructor
Parameters
const std::string & name
const CCopasiContainer * pParent (default: NULL)
Definition at line 15 of file CModelParameterSet.cpp.
References setObjectParent().
                                                                         :
   CCopasiContainer(name, pParent, "ModelParameterSet"),
   CModelParameterGroup(NULL, CModelParameter::Set),
   CAnnotation(),
   mKey(CCopasiRootContainer::getKeyFactory()->add("ModelParameterSet", this)),
   mpModel(NULL)
 {
   setObjectParent(pParent);
 }
CModelParameterSet::CModelParameterSet (const CModelParameterSet & src, const CCopasiContainer * pParent, const bool & createMissing = false)
Copy constructor
Parameters
const CModelParameterSet & src
const CCopasiContainer * pParent
const bool & createMissing (default: false)
Definition at line 26 of file CModelParameterSet.cpp.
References CModelParameterGroup::compile(), getModel(), mpModel, and setObjectParent().
                                                                   :
   CCopasiContainer(src, pParent),
   CModelParameterGroup(src, NULL, createMissing),
   CAnnotation(src),
   mKey(CCopasiRootContainer::getKeyFactory()->add("ModelParameterSet", this)),
   mpModel(NULL)
 {
   setObjectParent(pParent);
   if (mpModel == NULL)
     {
       mpModel = src.getModel();
     }
   compile();
 }
CModelParameterSet::~CModelParameterSet () virtual
Destructor
Definition at line 46 of file CModelParameterSet.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
void CModelParameterSet::assignSetContent (const CModelParameterSet & src, const bool & createMissing)
Assign the content of the source set to this, i.e., copy all contained parameters and groups.
Parameters
const CModelParameterSet & src
const bool & createMissing
Definition at line 231 of file CModelParameterSet.cpp.
References CModelParameterGroup::assignGroupContent(), and CModelParameterGroup::compile().
Referenced by CCopasiXMLParser::ListOfModelParameterSetsElement::end(), CQParameterOverviewWidget::leave(), CQParameterOverviewWidget::slotBtnNew(), and CQParameterOverviewWidget::slotBtnSaveAs().
 {
   assignGroupContent(src, createMissing);
   compile();
 }
bool CModelParameterSet::compareWithModel (const CModelParameter::Framework & framework)
Compare the parameter set with the assigned model
Definition at line 185 of file CModelParameterSet.cpp.
References createFromModel(), CModelParameterGroup::diff(), CModelParameter::Identical, and mpModel.
Referenced by CQParameterOverviewWidget::enterProtected(), CQParameterOverviewWidget::setFramework(), and CQParameterOverviewWidget::slotResolve().
 {
   if (mpModel == NULL)
     {
       return false;
     }
   CModelParameterSet Tmp("Current", mpModel);
   Tmp.createFromModel();
   return (diff(Tmp, framework, true) == CModelParameter::Identical);
 }
void CModelParameterSet::createFromModel ()
Create the parameter set from the assigned model
Definition at line 75 of file CModelParameterSet.cpp.
References CModelParameterGroup::add(), CModelEntity::ASSIGNMENT, CCopasiVector< T >::begin(), CModelParameterGroup::clear(), CModelParameter::Compartment, CModelParameterGroup::compile(), CCopasiVector< T >::end(), fatalError, CModelEntity::FIXED, CKeyFactory::get(), CModelParameter::getCN(), CCopasiObject::getCN(), CModel::getCompartments(), CModel::getInitialTime(), CModelEntity::getInitialValue(), CModelEntity::getInitialValueReference(), CCopasiRootContainer::getKeyFactory(), CModel::getMetabolites(), CModel::getModelValues(), CModel::getReactions(), CModelParameter::Group, CModelParameter::Model, CModelParameter::ModelValue, mpModel, CModelParameter::ParticleNumbers, CModelParameter::Reaction, CModelParameter::ReactionParameter, CModelParameter::setCN(), CModelParameter::setInitialExpression(), CModelParameter::setSimulationType(), CModelParameter::setValue(), and CModelParameter::Species.
Referenced by CModel::applyActiveParameterSet(), compareWithModel(), CModel::compile(), and createParameterSetsForExperiment().
 {
   clear();
   if (mpModel == NULL)
     {
       return;
     }
   CModelParameter * pParameter;
   CModelParameterGroup * pGroup;
   // TODO CRITICAL Create the proper structure that fits the parameter overview in the GUI
   pGroup = static_cast< CModelParameterGroup *>(CModelParameterGroup::add(Group));
   pGroup->setCN(CCopasiStaticString("Initial Time").getCN());
   pParameter = pGroup->add(Model);
   pParameter->setCN(mpModel->getCN());
   pParameter->setValue(mpModel->getInitialTime(), ParticleNumbers);
   pGroup = static_cast< CModelParameterGroup *>(CModelParameterGroup::add(Group));
   pGroup->setCN(CCopasiStaticString("Initial Compartment Sizes").getCN());
   CCopasiVector< CCompartment >::const_iterator itCompartment = mpModel->getCompartments().begin();
   CCopasiVector< CCompartment >::const_iterator endCompartment = mpModel->getCompartments().end();
   for (; itCompartment != endCompartment; ++itCompartment)
     {
       pParameter = pGroup->add(Compartment);
       pParameter->setCN((*itCompartment)->getCN());
       pParameter->setSimulationType((*itCompartment)->getStatus());
       pParameter->setValue((*itCompartment)->getInitialValue(), ParticleNumbers);
       pParameter->setInitialExpression((*itCompartment)->getInitialExpression());
     }
   pGroup = static_cast< CModelParameterGroup *>(CModelParameterGroup::add(Group));
   pGroup->setCN(CCopasiStaticString("Initial Species Values").getCN());
   CCopasiVector< CMetab >::const_iterator itSpecies = mpModel->getMetabolites().begin();
   CCopasiVector< CMetab >::const_iterator endSpecies = mpModel->getMetabolites().end();
   for (; itSpecies != endSpecies; ++itSpecies)
     {
       pParameter = pGroup->add(Species);
       pParameter->setCN((*itSpecies)->getCN());
       pParameter->setSimulationType((*itSpecies)->getStatus());
       pParameter->setValue((*itSpecies)->getInitialValue(), ParticleNumbers);
       pParameter->setInitialExpression((*itSpecies)->getInitialExpression());
     }
   pGroup = static_cast< CModelParameterGroup *>(CModelParameterGroup::add(Group));
   pGroup->setCN(CCopasiStaticString("Initial Global Quantities").getCN());
   CCopasiVector< CModelValue >::const_iterator itModelValue = mpModel->getModelValues().begin();
   CCopasiVector< CModelValue >::const_iterator endModelValue = mpModel->getModelValues().end();
   for (; itModelValue != endModelValue; ++itModelValue)
     {
       pParameter = pGroup->add(ModelValue);
       pParameter->setCN((*itModelValue)->getCN());
       pParameter->setSimulationType((*itModelValue)->getStatus());
       pParameter->setValue((*itModelValue)->getInitialValue(), ParticleNumbers);
       pParameter->setInitialExpression((*itModelValue)->getInitialExpression());
     }
   pGroup = static_cast< CModelParameterGroup *>(CModelParameterGroup::add(Group));
   pGroup->setCN(CCopasiStaticString("Kinetic Parameters").getCN());
   CCopasiVector< CReaction >::const_iterator itReaction = mpModel->getReactions().begin();
   CCopasiVector< CReaction >::const_iterator endReaction = mpModel->getReactions().end();
   for (; itReaction != endReaction; ++itReaction)
     {
       CModelParameterGroup * pReaction = static_cast< CModelParameterGroup *>(pGroup->add(Reaction));
       pReaction->setCN((*itReaction)->getCN());
       CCopasiParameterGroup::index_iterator itParameter = (*itReaction)->getParameters().beginIndex();
       CCopasiParameterGroup::index_iterator endParameter = (*itReaction)->getParameters().endIndex();
       for (; itParameter != endParameter; ++itParameter)
         {
           pParameter = pReaction->add(ReactionParameter);
           pParameter->setCN((*itParameter)->getCN());
           // Check whether this refers to a global quantity.
           if ((*itReaction)->isLocalParameter((*itParameter)->getObjectName()))
             {
               pParameter->setSimulationType(CModelEntity::FIXED);
               pParameter->setValue(*(*itParameter)->getValue().pDOUBLE, ParticleNumbers);
             }
           else
             {
               pParameter->setSimulationType(CModelEntity::ASSIGNMENT);
               const std::vector<std::string> ModelValue = (*itReaction)->getParameterMapping((*itParameter)->getObjectName());
               if (ModelValue.size() != 1) fatalError();
               const CModelValue * pModelValue = static_cast< CModelValue * >(CCopasiRootContainer::getKeyFactory()->get(ModelValue[0]));
               if (pModelValue == NULL) fatalError();
               pParameter->setValue(pModelValue->getInitialValue(), ParticleNumbers);
               pParameter->setInitialExpression("<" + pModelValue->getInitialValueReference()->getCN() + ">");
             }
         }
     }
   compile();
 }
const std::string & CModelParameterSet::getKey () const virtual
Retrieve the unique key of the set.
Returns
const std::string & key
Reimplemented from CAnnotation.
Definition at line 52 of file CModelParameterSet.cpp.
References mKey.
Referenced by CModel::applyActiveParameterSet(), CCopasiXMLParser::ModelParameterSetElement::end(), isActive(), CQBrowserPaneDM::load(), CCopasiXML::saveModel(), CQParameterOverviewWidget::slotBtnCopy(), CQParameterOverviewWidget::slotBtnNew(), and CQParameterOverviewWidget::slotBtnSaveAs().
 {
   return mKey;
 }
CModel * CModelParameterSet::getModel () const
Retrieve the model the parameter set is storing values for
Returns
CModel * pModel
Definition at line 68 of file CModelParameterSet.cpp.
References mpModel.
Referenced by CModelParameterSet(), CModelParameter::getModel(), CModelParameterSpecies::getName(), CQParameterOverviewWidget::slotBtnCopy(), CQParameterOverviewWidget::slotBtnDelete(), CQParameterOverviewWidget::slotBtnNew(), and CQParameterOverviewWidget::slotBtnSaveAs().
 {
   assert(mpModel != NULL);
   return mpModel;
 }
std::string CModelParameterSet::getName () const virtual
Retrieve the name of the parameter set
Returns
std::string name
Reimplemented from CModelParameter.
Definition at line 199 of file CModelParameterSet.cpp.
References CCopasiObject::getObjectName().
 {
   return getObjectName();
 }
bool CModelParameterSet::isActive () const
Determine whether this is parameter set is currently active, i.e., it is synchronized with the model.
Returns
bool isActive
Definition at line 221 of file CModelParameterSet.cpp.
References getKey(), CModel::getModelParameterSet(), mKey, and mpModel.
Referenced by CQParameterOverviewWidget::enterProtected(), CQParameterOverviewWidget::leave(), CQParameterOverviewWidget::setFramework(), and CModelParameter::setValue().
 {
   if (mpModel == NULL)
     {
       return false;
     }
   return (mpModel->getModelParameterSet().getKey() == mKey);
 }
bool CModelParameterSet::saveToStream (std::ostream & os, const CModelParameter::Framework & framework, const std::string & mode, const std::string & separator)
Save the parameter set to a stream
Parameters
std::ostream & os
const CModelParameter::Framework & framework
const std::string & mode (report or table)
const std::string & separator
Definition at line 238 of file CModelParameterSet.cpp.
References CNodeIteratorMode::After, CNodeIteratorMode::Before, CNodeContextIterator< Node, int >::end(), CModelParameter::getName(), CModelParameter::getType(), CModelParameter::getUnit(), CModelParameter::getValue(), CModelParameter::Group, CNodeContextIterator< Node, int >::level(), CNodeContextIterator< Node, int >::next(), CModelParameter::Set, and CNodeContextIterator< Node, int >::setProcessingModes().
Referenced by CQParameterOverviewWidget::slotBtnSaveToFile().
 {
   bool success = true;
   CNodeIterator< const CModelParameter > itNode(this);
   if (mode == "report")
     {
       itNode.setProcessingModes(CNodeIteratorMode::Before);
       while (itNode.next() != itNode.end())
         {
           if (*itNode != NULL)
             {
               for (unsigned int i = 1; i < itNode.level(); i++)
                 {
                   os << separator;
                 }
               os << itNode->getName();
               for (unsigned int i = itNode.level(); i < 6; i++)
                 {
                   os << separator;
                 }
               if (itNode->getType() != Group &&
                   itNode->getType() != Set)
                 {
                   os << itNode->getValue(framework) << " " << itNode->getUnit(framework);
                 }
               os << std::endl;
             }
         }
     }
   else if (mode == "table")
     {
       itNode.setProcessingModes(CNodeIteratorMode::After);
       while (itNode.next() != itNode.end())
         {
           if (*itNode != NULL)
             {
               if (itNode->getType() != Group &&
                   itNode->getType() != Set)
                 {
                   os << itNode->getName() << " " << itNode->getUnit(framework) << separator;
                 }
             }
         }
       os << std::endl;
       itNode = CNodeIterator< const CModelParameter >(this);
       itNode.setProcessingModes(CNodeIteratorMode::After);
       while (itNode.next() != itNode.end())
         {
           if (*itNode != NULL)
             {
               if (itNode->getType() != Group &&
                   itNode->getType() != Set)
                 {
                   os << itNode->getValue(framework) << separator;
                 }
             }
         }
       os << std::endl;
     }
   else
     {
       success = false;
     }
   return success;
 }
void CModelParameterSet::setModel (const CModel * pModel)
Set the model the parameter set is storing values for
Parameters
const CModel * pModel
bool CModelParameterSet::setObjectParent (const CCopasiContainer * pParent) virtual
Set the object parent
Parameters
const CCopasiContainer * pParent
Returns
bool success
Reimplemented from CCopasiObject.
Definition at line 58 of file CModelParameterSet.cpp.
References CCopasiObject::getObjectAncestor(), mpModel, and CCopasiObject::setObjectParent().
Referenced by CModelParameterSet().
 {
   bool success = CCopasiObject::setObjectParent(pParent);
   mpModel = dynamic_cast< CModel * >(getObjectAncestor("Model"));
   return success;
 }
bool CModelParameterSet::updateModel () virtual
Update the corresponding model object with the current parameter settings
Reimplemented from CModelParameterGroup.
Definition at line 205 of file CModelParameterSet.cpp.
References CModelParameterGroup::compile(), mpModel, CModel::updateInitialValues(), and CModelParameterGroup::updateModel().
Referenced by CModel::applyActiveParameterSet(), CCopasiDataModel::commonAfterLoad(), CQParameterOverviewWidget::leave(), and CQParameterOverviewWidget::slotBtnNew().
 {
   if (mpModel == NULL)
     {
       return false;
     }
   compile();
   bool success = CModelParameterGroup::updateModel();
   mpModel->updateInitialValues();
   return success;
 }
Member Data Documentation
std::string CModelParameterSet::mKey private
The unique key of the set
Definition at line 121 of file CModelParameterSet.h.
Referenced by getKey(), isActive(), and ~CModelParameterSet().
CModel* CModelParameterSet::mpModel private
A pointer to the model the parameter set is storing values for
Definition at line 126 of file CModelParameterSet.h.
Referenced by CModelParameterSet(), compareWithModel(), createFromModel(), getModel(), isActive(), setObjectParent(), and updateModel().
The documentation for this class was generated from the following files:
CModelParameterSet.h
CModelParameterSet.cpp