COPASI API: test000060 Class Reference
test000060 Class Reference
#include <test000060.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug_1026 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug_1026)
CPPUNIT_TEST_SUITE (test000060)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
This test checks if the constant and boundaryCondition flags are set correctly when a FIXED metabolite is changed back to status REACTIONS.
Definition at line 31 of file test000060.h.
Member Function Documentation
test000060::CPPUNIT_TEST (test_bug_1026) private
test000060::CPPUNIT_TEST_SUITE (test000060) private
test000060::CPPUNIT_TEST_SUITE_END () private
void test000060::setUp ()
Definition at line 36 of file test000060.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000060::tearDown ()
Definition at line 44 of file test000060.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000060::test_bug_1026 ()
Definition at line 49 of file test000060.cpp.
References CModel::buildInitialRefreshSequence(), CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getCurrentSBMLDocument(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING1, pCOPASIDATAMODEL, CModelEntity::REACTIONS, and CCopasiVector< T >::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000060::MODEL_STRING1));
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   const Model* pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getNumFunctionDefinitions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pSBMLModel->getNumSpecies() == 1);
   CPPUNIT_ASSERT(pSBMLModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumParameters() == 0);
   // check if the species is constant and has boundaryCondition set to true
   const Species* pSpecies = pSBMLModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies != NULL);
   CPPUNIT_ASSERT(pSpecies->getConstant() == true);
   CPPUNIT_ASSERT(pSpecies->getBoundaryCondition() == true);
   // now change the status of the species in the underlying COPASI model
   CPPUNIT_ASSERT(pDataModel->getModel()->getMetabolites().size() == 1);
   CMetab* pMetab = pDataModel->getModel()->getMetabolites()[0];
   pMetab->setStatus(CModelEntity::REACTIONS);
   std::set<const CCopasiObject*> changedObjects;
   changedObjects.insert(pMetab);
   std::vector<Refresh*> refreshes = pDataModel->getModel()->buildInitialRefreshSequence(changedObjects);
   std::vector<Refresh*>::iterator refreshIt = refreshes.begin(), refreshEndit = refreshes.end();
   while (refreshIt != refreshEndit)
     {
       (**refreshIt++)();
     }
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 1).empty() == false);
   pDocument = pDataModel->getCurrentSBMLDocument();
   pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getNumFunctionDefinitions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pSBMLModel->getNumSpecies() == 1);
   CPPUNIT_ASSERT(pSBMLModel->getNumReactions() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumParameters() == 0);
   // check if the species is constant and has boundaryCondition set to false
   pSpecies = pSBMLModel->getSpecies(0);
   CPPUNIT_ASSERT(pSpecies != NULL);
   CPPUNIT_ASSERT(pSpecies->getConstant() == false);
   CPPUNIT_ASSERT(pSpecies->getBoundaryCondition() == false);
 }
Member Data Documentation
const char * test000060::MODEL_STRING1 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" metaid=\"_000000\" level=\"2\" version=\"1\">\n"
  "  <model metaid=\"_000001\" id=\"bug_1026\" name=\"bug_1026\">\n"
  "    <listOfCompartments>\n"
  "      <compartment metaid=\"_000005\" id=\"compartment_1\" name=\"compartment_1\" size=\"1e-16\">\n"
  "      </compartment>\n"
  "    </listOfCompartments>\n"
  "    <listOfSpecies>\n"
  "      <species metaid=\"_000006\" id=\"species_1\" name=\"species_1\" compartment=\"compartment_1\" initialAmount=\"1.0\" constant=\"true\" boundaryCondition=\"true\" />\n"
  "    </listOfSpecies>  \n"
  "  </model>\n"
  "</sbml>\n"
Definition at line 38 of file test000060.h.
Referenced by test_bug_1026().
CCopasiDataModel * test000060::pCOPASIDATAMODEL = NULL static protected
Definition at line 39 of file test000060.h.
Referenced by setUp(), and test_bug_1026().
The documentation for this class was generated from the following files:
test000060.h
test000060.cpp