COPASI API: CQTimeSeriesWidget.cpp File Reference
CQTimeSeriesWidget.cpp File Reference
#include "CQTimeSeriesWidget.h"
#include "CQTimeSeriesDM.h"
#include "CopasiFileDialog.h"
#include "CQMessageBox.h"
#include "qtUtilities.h"
#include "trajectory/CTrajectoryTask.h"
#include "crosssection/CCrossSectionTask.h"
Functions
const CTimeSeries * getTimeSeriesFromTask (const CCopasiTask *pTask)
Function Documentation
const CTimeSeries* getTimeSeriesFromTask (const CCopasiTask * pTask)
Definition at line 72 of file CQTimeSeriesWidget.cpp.
References CTrajectoryTask::getTimeSeries(), CCrossSectionTask::getTimeSeries(), and pTask.
Referenced by CQTimeSeriesWidget::loadResult().
 {
   const CTrajectoryTask *traj = dynamic_cast<const CTrajectoryTask *>(pTask);
   if (traj != NULL)
     return &traj->getTimeSeries();
   const CCrossSectionTask* cross = dynamic_cast<const CCrossSectionTask *>(pTask);
   if (cross != NULL)
     return &cross->getTimeSeries();
   return NULL;
 }