COPASI API: CAnnotatedMatrix.cpp File Reference
CAnnotatedMatrix.cpp File Reference
Implementation file of class CCopasiArray and CArrayAnnotation.
#include <sstream>
#include "CAnnotatedMatrix.h"
#include "CCopasiVector.h"
#include "report/CKeyFactory.h"
#include "report/CArrayElementReference.h"
#include "CopasiDataModel/CCopasiDataModel.h"
Macros
#define SPC(level) std::string(level, ' ')
Functions
std::ostream & operator<< (std::ostream &os, const CArrayAnnotation &o)
Detailed Description
Implementation file of class CCopasiArray and CArrayAnnotation.
Definition in file CAnnotatedMatrix.cpp.
Macro Definition Documentation
#define SPC (level) std::string(level, ' ')
Definition at line 382 of file CAnnotatedMatrix.cpp.
Referenced by CArrayAnnotation::printRecursively().
Function Documentation
std::ostream& operator<< (std::ostream & os, const CArrayAnnotation & o)
Definition at line 438 of file CAnnotatedMatrix.cpp.
References CArrayAnnotation::array(), CArrayAnnotation::dimensionality(), CArrayAnnotation::getAnnotationsString(), CArrayAnnotation::getDescription(), CCopasiObject::getObjectName(), CArrayAnnotation::printRecursively(), and CCopasiAbstractArray::size().
 {
   if (!o.array()) return os;
   //cache the display names
   std::vector<std::vector<std::string> > displaynames;
   size_t i;
   for (i = 0; i < o.dimensionality(); ++i)
     displaynames.push_back(o.getAnnotationsString(i));
   os << o.getObjectName() << std::endl;
   os << o.getDescription() << std::endl;
   CCopasiAbstractArray::index_type arraysize = o.array()->size();
   if (o.dimensionality() == 0)
     {
       //only one scalar value
       os << (*o.array())[arraysize] << std::endl;
     }
   else
     {
       o.printRecursively(os, o.dimensionality() - 1, arraysize, displaynames);
     }
   return os;
 }