COPASI API: CMCAProblem.cpp File Reference
CMCAProblem.cpp File Reference
#include <string>
#include "copasi.h"
#include "CMCAProblem.h"
#include "CMCATask.h"
#include "CSteadyStateTask.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "model/CModel.h"
#include "model/CState.h"
#include "report/CKeyFactory.h"
Functions
std::ostream & operator<< (std::ostream &os, const CMCAProblem &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CMCAProblem & o)
Output stream operator. Prints description of the problem incl. the subtask
Parameters
ostream & os
const CMCAProblem & A
Returns
ostream & os
Definition at line 185 of file CMCAProblem.cpp.
References CCopasiTask::getDescription(), CMCAProblem::getSubTask(), CMCAProblem::isSteadyStateRequested(), and CCopasiTask::CDescription::print().
 {
   os << "Problem Description:" << std::endl;
   //os << "Subtask: " << std::endl;
   if (o.isSteadyStateRequested())
     {
       os << "Calculation of a steady state is requested before the MCA." << std::endl << std::endl;
       if (o.getSubTask())
         {
           //os << "" << std::endl;
           o.getSubTask()->getDescription().print(&os);
         }
       else
         {
           os << "However an error occurred. Please report this as a bug." << std::endl;
         }
     }
   else
     {
       os << "MCA is performed on the current state (which is not necessarily a steady state)." << std::endl;
     }
   os << std::endl;
   return os;
 }