COPASI API: test000067 Class Reference
test000067 Class Reference
#include <test000067.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1060 ()
Static Protected Attributes
static const char * MODEL_STRING1
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_bug1060)
CPPUNIT_TEST_SUITE (test000067)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
This test is for Bug 1060.
Definition at line 29 of file test000067.h.
Member Function Documentation
test000067::CPPUNIT_TEST (test_bug1060) private
test000067::CPPUNIT_TEST_SUITE (test000067) private
test000067::CPPUNIT_TEST_SUITE_END () private
void test000067::setUp ()
Definition at line 41 of file test000067.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000067::tearDown ()
Definition at line 49 of file test000067.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000067::test_bug1060 ()
Definition at line 54 of file test000067.cpp.
References test000059::checkIfIdsUnique(), CCopasiDataModel::exportSBMLToString(), CFunctionDB::findFunction(), CCopasiDataModel::getCopasi2SBMLMap(), CCopasiDataModel::getCurrentSBMLDocument(), CCopasiRootContainer::getFunctionList(), CCopasiDataModel::getModel(), load_cps_model_from_stream(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   std::istringstream iss(test000067::MODEL_STRING1);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   CPPUNIT_ASSERT(pDataModel->getModel() != NULL);
   const SBMLDocument* pDocument = pDataModel->getCurrentSBMLDocument();
   CPPUNIT_ASSERT(pDocument == NULL);
   CPPUNIT_ASSERT(pDataModel->exportSBMLToString(NULL, 2, 3).empty() == false);
   pDocument = pDataModel->getCurrentSBMLDocument();
   const Model* pSBMLModel = pDocument->getModel();
   CPPUNIT_ASSERT(pSBMLModel != NULL);
   CPPUNIT_ASSERT(pSBMLModel->getNumFunctionDefinitions() == 3);
   CPPUNIT_ASSERT(pSBMLModel->getNumCompartments() == 1);
   CPPUNIT_ASSERT(pSBMLModel->getNumSpecies() == 3);
   CPPUNIT_ASSERT(pSBMLModel->getNumReactions() == 8);
   CPPUNIT_ASSERT(pSBMLModel->getNumRules() == 0);
   CPPUNIT_ASSERT(pSBMLModel->getNumParameters() == 0);
   CPPUNIT_ASSERT(test000059::checkIfIdsUnique(pSBMLModel) == true);
   // check if each reaction call the correct kinetic law
   CFunctionDB* pFunDB = CCopasiRootContainer::getFunctionList();
   CEvaluationTree* pModifiedMM = pFunDB->findFunction("Modified MM");
   CPPUNIT_ASSERT(pModifiedMM != NULL);
   CEvaluationTree* pModifiedCF = pFunDB->findFunction("modified constant flux");
   CPPUNIT_ASSERT(pModifiedCF != NULL);
   CEvaluationTree* pConstantFlux = pFunDB->findFunction("Constant flux (irreversible)");
   CPPUNIT_ASSERT(pConstantFlux != NULL);
   unsigned int i, iMax = pSBMLModel->getListOfReactions()->size();
   const Reaction* pReaction = NULL;
   const ASTNode* pRoot = NULL;
   const std::map<CCopasiObject*, SBase*>& copasi2sbmlmap = pDataModel->getCopasi2SBMLMap();
   std::map<CCopasiObject*, SBase*>::const_iterator mappos;
   for (i = 0; i < iMax; ++i)
     {
       pReaction = pSBMLModel->getReaction(i);
       CPPUNIT_ASSERT(pReaction != NULL);
       CPPUNIT_ASSERT(pReaction->getKineticLaw() != NULL);
       pRoot = pReaction->getKineticLaw()->getMath();
       CPPUNIT_ASSERT(pRoot != NULL);
       CPPUNIT_ASSERT(pRoot->getType() == AST_TIMES);
       if (pRoot->getChild(0)->getType() == AST_NAME && pRoot->getChild(0)->getName() == pSBMLModel->getCompartment(0)->getId())
         {
           pRoot = pRoot->getChild(1);
         }
       else
         {
           pRoot = pRoot->getChild(0);
         }
       if (pReaction->getName() == "y0Prod" || pReaction->getName() == "y1Prod" || pReaction->getName() == "xProdLin")
         {
           // uses modified constant flux
           CPPUNIT_ASSERT(pRoot->getType() == AST_FUNCTION);
           mappos = copasi2sbmlmap.find(pModifiedCF);
           CPPUNIT_ASSERT(mappos != copasi2sbmlmap.end());
           CPPUNIT_ASSERT(mappos->second != NULL);
           CPPUNIT_ASSERT(pRoot->getName() == mappos->second->getId());
         }
       else if (pReaction->getName() == "xDegMM")
         {
           // uses modifed MM
           CPPUNIT_ASSERT(pRoot->getType() == AST_FUNCTION);
           mappos = copasi2sbmlmap.find(pModifiedMM);
           CPPUNIT_ASSERT(mappos != copasi2sbmlmap.end());
           CPPUNIT_ASSERT(mappos->second != NULL);
           CPPUNIT_ASSERT(pRoot->getName() == mappos->second->getId());
         }
       else if (pReaction->getName() == "xProd")
         {
           // constant flux
           CPPUNIT_ASSERT(pRoot->getType() == AST_FUNCTION);
           mappos = copasi2sbmlmap.find(pConstantFlux);
           CPPUNIT_ASSERT(mappos != copasi2sbmlmap.end());
           CPPUNIT_ASSERT(mappos->second != NULL);
           CPPUNIT_ASSERT(pRoot->getName() == mappos->second->getId());
         }
       else
         {
           // must be mass action
           CPPUNIT_ASSERT(pRoot->getType() == AST_TIMES);
         }
     }
 }
Member Data Documentation
const char * test000067::MODEL_STRING1 static protected
Definition at line 36 of file test000067.h.
Referenced by test_bug1060().
CCopasiDataModel * test000067::pCOPASIDATAMODEL = NULL static protected
Definition at line 37 of file test000067.h.
Referenced by setUp(), and test_bug1060().
The documentation for this class was generated from the following files:
test000067.h
test000067.cpp