COPASI API: CCreator Class Reference
CCreator Class Reference
#include <CCreator.h>
Public Member Functions
CCreator (const std::string &objectName, const CCopasiContainer *pParent=NULL)
CCreator (const CRDFTriplet &triplet, const std::string &objectName="", const CCopasiContainer *pParent=NULL)
CCreator (const CCreator &src, const CCopasiContainer *pParent=NULL)
const std::string & getEmail () const
const std::string & getFamilyName () const
const std::string & getGivenName () const
virtual const std::string & getKey () const
const std::string & getORG () const
const CRDFTriplet & getTriplet () const
void setEmail (const std::string &Email)
void setFamilyName (const std::string &familyName)
void setGivenName (const std::string &givenName)
void setORG (const std::string &Orgname)
~CCreator ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
std::string mKey
CRDFPredicate::Path mNodePath
CRDFTriplet mTriplet
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CCreators: Stores author name, email and other (vCard) details.
Definition at line 35 of file CCreator.h.
Constructor & Destructor Documentation
CCreator::CCreator (const std::string & objectName, const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & objectName
const CCopasiContainer * pParent (default: NULL)
Definition at line 30 of file CCreator.cpp.
                                                     :
     CCopasiContainer(objectName, pParent, "Creator"),
     mTriplet(),
     mNodePath(),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Creator", this))
 {}
CCreator::CCreator (const CRDFTriplet & triplet, const std::string & objectName = "", const CCopasiContainer * pParent = NULL)
Specific constructor
Parameters
const CRDFTriplet & triplet
const std::string & objectName (default: "")
const CCopasiContainer * pParent (default: NULL)
Definition at line 38 of file CCreator.cpp.
References CRDFNode::getPath(), mNodePath, mTriplet, and CRDFTriplet::pObject.
                                                     :
     CCopasiContainer(objectName, pParent, "Creator"),
     mTriplet(triplet),
     mNodePath(),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Creator", this))
 {
   if (!mTriplet)
     return;
   mNodePath = mTriplet.pObject->getPath();
 }
CCreator::CCreator (const CCreator & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CCreator & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 52 of file CCreator.cpp.
                                                     :
     CCopasiContainer(src, pParent),
     mTriplet(src.mTriplet),
     mNodePath(src.mNodePath),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Creator", this))
 {}
CCreator::~CCreator ()
Destructor
Definition at line 60 of file CCreator.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
const std::string & CCreator::getEmail () const
Definition at line 77 of file CCreator.cpp.
References CRDFNode::getFieldValue(), mTriplet, CRDFTriplet::pObject, and CRDFPredicate::vcard_EMAIL.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
   {return mTriplet.pObject->getFieldValue(CRDFPredicate::vcard_EMAIL);}
const std::string & CCreator::getFamilyName () const
Add the given name to Last name to get the full Name.
Definition at line 71 of file CCreator.cpp.
References CRDFNode::getFieldValue(), mTriplet, CRDFTriplet::pObject, and CRDFPredicate::vcard_Family.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
   {return mTriplet.pObject->getFieldValue(CRDFPredicate::vcard_Family);}
const std::string & CCreator::getGivenName () const
Definition at line 74 of file CCreator.cpp.
References CRDFNode::getFieldValue(), mTriplet, CRDFTriplet::pObject, and CRDFPredicate::vcard_Given.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
   {return mTriplet.pObject->getFieldValue(CRDFPredicate::vcard_Given);}
const std::string & CCreator::getKey () const virtual
Reimplemented from CCopasiObject.
Definition at line 68 of file CCreator.cpp.
References mKey.
   {return mKey;}
const std::string & CCreator::getORG () const
Definition at line 80 of file CCreator.cpp.
References CRDFNode::getFieldValue(), mTriplet, CRDFTriplet::pObject, and CRDFPredicate::vcard_Orgname.
Referenced by CSBMLExporter::updateMIRIAMAnnotation().
   {return mTriplet.pObject->getFieldValue(CRDFPredicate::vcard_Orgname);}
const CRDFTriplet & CCreator::getTriplet () const
Definition at line 65 of file CCreator.cpp.
References mTriplet.
Referenced by CMIRIAMInfo::removeCreator().
   {return mTriplet;}
void CCreator::setEmail (const std::string & Email)
Definition at line 89 of file CCreator.cpp.
References mNodePath, mTriplet, CRDFTriplet::pObject, CRDFNode::setFieldValue(), and CRDFPredicate::vcard_EMAIL.
 {mTriplet.pObject->setFieldValue(Email, CRDFPredicate::vcard_EMAIL, mNodePath);}
void CCreator::setFamilyName (const std::string & familyName)
Definition at line 83 of file CCreator.cpp.
References mNodePath, mTriplet, CRDFTriplet::pObject, CRDFNode::setFieldValue(), and CRDFPredicate::vcard_Family.
 {mTriplet.pObject->setFieldValue(familyName, CRDFPredicate::vcard_Family, mNodePath);}
void CCreator::setGivenName (const std::string & givenName)
Definition at line 86 of file CCreator.cpp.
References mNodePath, mTriplet, CRDFTriplet::pObject, CRDFNode::setFieldValue(), and CRDFPredicate::vcard_Given.
 {mTriplet.pObject->setFieldValue(givenName, CRDFPredicate::vcard_Given, mNodePath);}
void CCreator::setORG (const std::string & Orgname)
Definition at line 92 of file CCreator.cpp.
References mNodePath, mTriplet, CRDFTriplet::pObject, CRDFNode::setFieldValue(), and CRDFPredicate::vcard_Orgname.
 {mTriplet.pObject->setFieldValue(Orgname, CRDFPredicate::vcard_Orgname, mNodePath);}
Member Data Documentation
std::string CCreator::mKey private
The key of the object needed for the COPASI tables.
Definition at line 52 of file CCreator.h.
Referenced by getKey(), and ~CCreator().
CRDFPredicate::Path CCreator::mNodePath private
The predicate path to the node.
Definition at line 47 of file CCreator.h.
Referenced by CCreator(), setEmail(), setFamilyName(), setGivenName(), and setORG().
CRDFTriplet CCreator::mTriplet private
Triplet in the RDF graph representing the reference.
Definition at line 42 of file CCreator.h.
Referenced by CCreator(), getEmail(), getFamilyName(), getGivenName(), getORG(), getTriplet(), setEmail(), setFamilyName(), setGivenName(), and setORG().
The documentation for this class was generated from the following files:
CCreator.h
CCreator.cpp