COPASI API: test000047 Class Reference
test000047 Class Reference
#include <test000047.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_delay ()
Static Protected Attributes
static const char * MODEL_STRING
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_delay)
CPPUNIT_TEST_SUITE (test000047)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 24 of file test000047.h.
Member Function Documentation
test000047::CPPUNIT_TEST (test_delay) private
test000047::CPPUNIT_TEST_SUITE (test000047) private
test000047::CPPUNIT_TEST_SUITE_END () private
void test000047::setUp ()
Definition at line 28 of file test000047.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000047::tearDown ()
Definition at line 36 of file test000047.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000047::test_delay ()
Definition at line 41 of file test000047.cpp.
References CModelEntity::ASSIGNMENT, CEvaluationNodeNumber::DOUBLE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CCopasiNode< _Data >::getSibling(), CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CModel::ml, CModel::mMol, MODEL_STRING, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CModel::s, CEvaluationNode::subType(), and CCopasiMessage::WARNING.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   const CMetab* pB = pModel->getMetabolites()[1];
   CPPUNIT_ASSERT(pB != NULL);
   CPPUNIT_ASSERT(pB->getStatus() == CModelEntity::FIXED);
   CMetab* pA = pModel->getMetabolites()[0];
   CPPUNIT_ASSERT(pA != NULL);
   CPPUNIT_ASSERT(pA->getStatus() == CModelEntity::ASSIGNMENT);
   const CExpression* pExpr = pA->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   const CEvaluationNodeDelay* pDelayNode = dynamic_cast<const CEvaluationNodeDelay*>(pNode);
   CPPUNIT_ASSERT(pDelayNode != NULL);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pDelayNode->getChild());
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Concentration"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pB);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pObjectNode->getSibling());
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(((CEvaluationNodeNumber::SubType)CEvaluationNode::subType(pNumberNode->getType())) == CEvaluationNodeNumber::DOUBLE);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 0.5) / 0.5) < 1e-3);
   CPPUNIT_ASSERT(pNumberNode->getSibling() == NULL);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModelValue->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   //CPPUNIT_ASSERT(CCopasiMessage::size() == 2);
   CCopasiMessage message = CCopasiMessage::getLastMessage();
   CPPUNIT_ASSERT(message.getType() == CCopasiMessage::WARNING);
   std::string s = message.getText();
   CPPUNIT_ASSERT(!s.empty());
   CPPUNIT_ASSERT(s.find(std::string("COPASI does not support time delays. Calculations on this model will most likely lead to unusable results.")) != std::string::npos);
   // right now, we don't care about the last message since it is a units
   // warning from libSBML
 }
Member Data Documentation
const char * test000047::MODEL_STRING static protected
Definition at line 31 of file test000047.h.
Referenced by test_delay().
CCopasiDataModel * test000047::pCOPASIDATAMODEL = NULL static protected
Definition at line 32 of file test000047.h.
Referenced by setUp(), and test_delay().
The documentation for this class was generated from the following files:
test000047.h
test000047.cpp