COPASI API: CQTSSAResultWidget Class Reference
CQTSSAResultWidget Class Reference
#include <CQTSSAResultWidget.h>
Public Member Functions
CQTSSAResultWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
CQTSSAResultSubWidget * getSubWidget ()
virtual bool leave ()
bool loadFromBackend ()
bool saveToBackend ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQTSSAResultWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual bool enterProtected ()
Protected Attributes
CQTSSAResultSubWidget * mCentralWidget
QGridLayout * mWidgetLayout
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 23 of file CQTSSAResultWidget.h.
Constructor & Destructor Documentation
CQTSSAResultWidget::CQTSSAResultWidget (QWidget * parent = 0, const char * name = 0, Qt::WFlags fl = 0)
Definition at line 38 of file CQTSSAResultWidget.cpp.
References mCentralWidget, and mWidgetLayout.
   : CopasiWidget(parent, name, fl)
 {
   if (!name)
     setObjectName("CQTSSAResultWidget");
   setWindowTitle(trUtf8("CQTSSAResultWidget"));
   mWidgetLayout = new QGridLayout(this);
   mWidgetLayout->setObjectName("Layout");
   mCentralWidget = new CQTSSAResultSubWidget(this);
   mCentralWidget->setObjectName("CQTSSAResultSubWidget");
   mWidgetLayout->addWidget(mCentralWidget, 0, 0);
   /*commitChanges = new QPushButton(this, "commitChanges");
   commitChanges->setText(trUtf8("Commit"));
   Layout5->addWidget(commitChanges);
   cancelChanges = new QPushButton(this, "cancelChanges");
   cancelChanges->setText(trUtf8("Revert"));
   Layout5->addWidget(cancelChanges);*/
   // signals and slots connections
   //connect(commitChanges, SIGNAL(clicked()), this, SLOT(slotBtnOKClicked()));
   //connect(cancelChanges, SIGNAL(clicked()), this, SLOT(slotBtnCancelClicked()));
 }
CQTSSAResultWidget::~CQTSSAResultWidget ()
Definition at line 69 of file CQTSSAResultWidget.cpp.
 {}
Member Function Documentation
bool CQTSSAResultWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 121 of file CQTSSAResultWidget.cpp.
References CQTSSAResultSubWidget::discardOldResults(), CTSSAMethod::getCurrentStep(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getMethod(), loadFromBackend(), and mCentralWidget.
 {
   pTask =
     dynamic_cast<CTSSATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time Scale Separation Analysis"]);
   pTSSILDM = dynamic_cast<CTSSAMethod*>(pTask->getMethod());
   if (!pTSSILDM->getCurrentStep())
     {
 #if 0
       mCentralWidget->setStepSelectionDisabled(true);
 #endif
       mCentralWidget->discardOldResults();
     }
 #if 0
   else
     mCentralWidget->setStepSelectionDisabled(false);
 #endif
   return loadFromBackend();
   /*objKey = key;
   CCompartment* comp = dynamic_cast< CCompartment * >(CCopasiRootContainer::getKeyFactory()->get(key));
   if (comp) return loadFromCompartment(comp);
   else return false;*/
 }
CQTSSAResultSubWidget* CQTSSAResultWidget::getSubWidget () inline
Definition at line 33 of file CQTSSAResultWidget.h.
References mCentralWidget.
Referenced by CQTSSAWidget::taskFinishedEvent().
 {return mCentralWidget;};
bool CQTSSAResultWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 115 of file CQTSSAResultWidget.cpp.
 {
   //return saveToCompartment();
   return true;
 }
bool CQTSSAResultWidget::loadFromBackend ()
Definition at line 72 of file CQTSSAResultWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), and mCentralWidget.
Referenced by enterProtected(), and CQTSSAWidget::taskFinishedEvent().
 {
 #if 0
   mCentralWidget->displayOptimizationTab(false);
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   mCentralWidget->table()->setTimeSeries(dynamic_cast<CTSSATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time Scale Separation Analysis"])->getTimeSeries());
 #endif
   return true;
 }
bool CQTSSAResultWidget::saveToBackend ()
Definition at line 84 of file CQTSSAResultWidget.cpp.
 {
   return true;
 }
bool CQTSSAResultWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 99 of file CQTSSAResultWidget.cpp.
References ListViews::ADD, mCentralWidget, and ListViews::MODEL.
 {
 #if 0
   if (objectType == ListViews::MODEL &&
       action == ListViews::ADD)
     mCentralWidget->table()->setTimeSeries(CTimeSeries());
 #endif
   return true;
 }
Member Data Documentation
CQTSSAResultSubWidget* CQTSSAResultWidget::mCentralWidget protected
Definition at line 46 of file CQTSSAResultWidget.h.
Referenced by CQTSSAResultWidget(), enterProtected(), getSubWidget(), loadFromBackend(), and update().
QGridLayout* CQTSSAResultWidget::mWidgetLayout protected
Definition at line 45 of file CQTSSAResultWidget.h.
Referenced by CQTSSAResultWidget().
The documentation for this class was generated from the following files:
CQTSSAResultWidget.h
CQTSSAResultWidget.cpp