COPASI API: CQTaskThread Class Reference
CQTaskThread Class Reference
#include <CQTaskThread.h>
Public Member Functions
CQTaskThread (TaskWidget *tw)
virtual void run ()
const bool & success () const
~CQTaskThread ()
Protected Attributes
TaskWidget * mpTaskWidget
bool mSuccess
Detailed Description
Definition at line 14 of file CQTaskThread.h.
Constructor & Destructor Documentation
CQTaskThread::CQTaskThread (TaskWidget * tw)
Definition at line 12 of file CQTaskThread.cpp.
                                         :
   QThread(),
   mpTaskWidget(tw),
   mSuccess(false)
 {}
CQTaskThread::~CQTaskThread ()
Definition at line 18 of file CQTaskThread.cpp.
 {
 }
Member Function Documentation
void CQTaskThread::run () virtual
Definition at line 22 of file CQTaskThread.cpp.
References TaskWidget::getTask(), mpTaskWidget, mSuccess, and CCopasiTask::process().
 {
   try
     {
       mSuccess = mpTaskWidget->getTask()->process(true);
     }
   catch (CCopasiException & /*Exception*/)
     {
       mSuccess = false;
     }
 }
const bool & CQTaskThread::success () const
Definition at line 34 of file CQTaskThread.cpp.
References mSuccess.
Referenced by TaskWidget::slotFinishThread().
 {
   return mSuccess;
 }
Member Data Documentation
TaskWidget* CQTaskThread::mpTaskWidget protected
Definition at line 27 of file CQTaskThread.h.
Referenced by run().
bool CQTaskThread::mSuccess protected
Definition at line 28 of file CQTaskThread.h.
Referenced by run(), and success().
The documentation for this class was generated from the following files:
CQTaskThread.h
CQTaskThread.cpp