COPASI API: CCopasiXMLParser::ListOfParameterDescriptionsElement Class Reference
CCopasiXMLParser::ListOfParameterDescriptionsElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
ListOfParameterDescriptionsElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~ListOfParameterDescriptionsElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { ListOfParameterDescriptions = 0, ParameterDescription }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2992 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::ListOfParameterDescriptionsElement::Element private
Enumerator
ListOfParameterDescriptions
ParameterDescription
Definition at line 2999 of file CCopasiXMLParser.h.
     {
       ListOfParameterDescriptions = 0,
       ParameterDescription
     };
Constructor & Destructor Documentation
CCopasiXMLParser::ListOfParameterDescriptionsElement::ListOfParameterDescriptionsElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 1338 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::ListOfParameterDescriptionsElement::~ListOfParameterDescriptionsElement () virtual
Destructor
Definition at line 1343 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::ListOfParameterDescriptionsElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 1393 of file CCopasiXMLParser.cpp.
References C_INVALID_INDEX, CCopasiMessage::EXCEPTION, CCopasiObject::getObjectName(), CFunction::getVariables(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pFunction, CFunctionParameters::remove(), CFunctionParameters::size(), START_ELEMENT, CFunctionParameter::TEMPORARY, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case ListOfParameterDescriptions:
         if (strcmp(pszName, "ListOfParameterDescriptions"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ListOfParameterDescriptions", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         // We need to remove all parameters which have been temporarily added to the list of variables
         {
           CFunction * pFunction = dynamic_cast<CFunction *>(mCommon.pFunction);
           if (pFunction)
             {
               CFunctionParameters & Variables = pFunction->getVariables();
               size_t i = Variables.size() - 1;
               for (; i != C_INVALID_INDEX && Variables[i]->getUsage() == CFunctionParameter::TEMPORARY; i--)
                 Variables.remove(Variables[i]->getObjectName());
             }
         }
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case ParameterDescription:
         if (strcmp(pszName, "ParameterDescription"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "ParameterDescription", mParser.getCurrentLineNumber());
         mCurrentElement = ListOfParameterDescriptions;
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::ListOfParameterDescriptionsElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 1348 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, SCopasiXMLParserCommon::mFunctionParameterKeyMap, CExpatTemplate< CExpat >::mParser, and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   switch (mCurrentElement)
     {
       case ListOfParameterDescriptions:
         mCommon.mFunctionParameterKeyMap.clear();
         if (strcmp(pszName, "ListOfParameterDescriptions"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "ListOfParameterDescriptions", mParser.getCurrentLineNumber());
         if (mpCurrentHandler) mpCurrentHandler->reset();
         break;
       case ParameterDescription:
         if (strcmp(pszName, "ParameterDescription"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "ParameterDescription", mParser.getCurrentLineNumber());
         /* If we do not have a ParameterDescription element handler we create one. */
         if (!mpCurrentHandler)
           mpCurrentHandler = new ParameterDescriptionElement(mParser, mCommon);
         /* Push the ParameterDescription element handler on the stack and call it. */
         mParser.pushElementHandler(mpCurrentHandler);
         mpCurrentHandler->start(pszName, papszAttrs);
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp