COPASI API: CCopasiXMLInterface Class Reference
CCopasiXMLInterface Class Reference abstract
#include <CCopasiXMLInterface.h>
Classes
class DBL
Public Types
enum EncodingType { none = 0, standard, attribute, character }
Public Member Functions
CCopasiXMLInterface ()
virtual bool load (std::istream &is, const std::string &relativeTo)=0
bool load (const std::string &fileName, const std::string &relativeTo)
virtual bool save (std::ostream &os, const std::string &relativeTo)=0
bool save (const std::string &fileName, const std::string &relativeTo)
virtual ~CCopasiXMLInterface ()
Static Public Member Functions
static std::string encode (const std::string &str, const EncodingType &type=standard)
static std::string utf8 (const std::string &str)
Protected Member Functions
bool endSaveElement (const std::string &name)
bool saveData (const std::string &data)
bool saveElement (const std::string &name, CXMLAttributeList &attributeList)
bool saveParameter (const CCopasiParameter &parameter)
bool saveParameterGroup (const std::vector< CCopasiParameter * > &group)
bool saveXhtml (const std::string &xhtml)
bool startSaveElement (const std::string &name)
bool startSaveElement (const std::string &name, CXMLAttributeList &attributeList)
Protected Attributes
std::string mIndent
std::istream * mpIstream
std::ostream * mpOstream
std::string mPWD
Detailed Description
Definition at line 85 of file CCopasiXMLInterface.h.
Member Enumeration Documentation
enum CCopasiXMLInterface::EncodingType
Enumeration of encoding type.
Enumerator
none
standard
attribute
character
Definition at line 91 of file CCopasiXMLInterface.h.
   {
     none = 0,
     standard,
     attribute,
     character
   };
Constructor & Destructor Documentation
CCopasiXMLInterface::CCopasiXMLInterface ()
Constructor.
Definition at line 271 of file CCopasiXMLInterface.cpp.
                                         :
   mpIstream(NULL),
   mpOstream(NULL),
   mIndent()
 {}
CCopasiXMLInterface::~CCopasiXMLInterface () virtual
Destructor.
Definition at line 277 of file CCopasiXMLInterface.cpp.
 {}
Member Function Documentation
std::string CCopasiXMLInterface::encode (const std::string & str, const EncodingType & type = standard) static
Encode a given string to a valid XML string
Parameters
const std::string & str
Returns
std::string encoded
Definition at line 158 of file CCopasiXMLInterface.cpp.
References attribute, character, encodeATTRIBUTE(), encodeCHARACTER(), encodeNONE(), encodeSTD(), none, standard, and void().
Referenced by CXMLAttributeList::add(), CCopasiXMLParser::UnsupportedAnnotationElement::end(), CCopasiXMLParser::MiriamAnnotationElement::end(), CMathMl::fixName(), CCopasiXMLParser::onCharacterData(), saveData(), CXMLAttributeList::set(), CXMLAttributeList::setValue(), CCopasiXMLParser::UnsupportedAnnotationElement::start(), CCopasiXMLParser::CommentElement::start(), and CCopasiXMLParser::MiriamAnnotationElement::start().
 {
   /* All COPASI std::strings and char are already UTF-8 encoded.*/
   std::string tmp = str;
   std::ostringstream xml;
   void (*encode)(const char & chr, std::ostringstream & xml) = encodeNONE;
   std::string::const_iterator it = str.begin();
   std::string::const_iterator end = str.end();
   switch (type)
     {
       case none:
         encode = encodeNONE;
         break;
       case standard:
         encode = encodeSTD;
         break;
       case attribute:
         encode = encodeATTRIBUTE;
         break;
       case character:
         encode = encodeCHARACTER;
         break;
     }
   for (; it != end; ++it)
     encode(*it, xml);
   return xml.str();
 }
bool CCopasiXMLInterface::endSaveElement (const std::string & name) protected
End saving an XML element to the ostream started by startSaveElement.
Parameters
const std::string & name
Returns
bool success
Definition at line 368 of file CCopasiXMLInterface.cpp.
References mIndent, and mpOstream.
Referenced by CCopasiXML::save(), CCopasiXML::saveAnnotation(), CCopasiXML::saveBoundingBox(), CCopasiXML::saveCurve(), CCopasiXML::saveCurveElements(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGlobalRenderInformation(), CCopasiXML::saveGlobalStyle(), CCopasiXML::saveGroupElement(), CCopasiXML::saveGUI(), CCopasiXML::saveLayoutList(), CCopasiXML::saveLinearGradient(), CCopasiXML::saveLineEnding(), CCopasiXML::saveListOfGlobalRenderInformation(), CCopasiXML::saveListOfLocalRenderInformation(), CCopasiXML::saveLocalRenderInformation(), CCopasiXML::saveLocalStyle(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), saveParameter(), CCopasiXML::savePlotList(), CCopasiXML::savePolygonElement(), CCopasiXML::saveRadialGradient(), CCopasiXML::saveRenderCurveElement(), CCopasiXML::saveRenderInformationDefinitionElements(), CCopasiXML::saveRenderTextElement(), CCopasiXML::saveReportList(), CCopasiXML::saveReportSection(), CCopasiXML::saveSBMLReference(), and CCopasiXML::saveTaskList().
 {
   mIndent = mIndent.substr(0, mIndent.length() - 2);
   *mpOstream << mIndent << "</" << name << ">" << std::endl;
   return true;
 }
virtual bool CCopasiXMLInterface::load (std::istream & is, const std::string & relativeTo) pure virtual
Load information from a given istream.
Parameters
std::istream & is
const std::string & relativeTo
Returns
bool success
Implemented in CConfigurationFile::CXML, and CCopasiXML.
Referenced by load().
bool CCopasiXMLInterface::load (const std::string & fileName, const std::string & relativeTo)
Load information from a file.
Parameters
const std::string & fileName
const std::string & relativeTo
Returns
bool success
Definition at line 279 of file CCopasiXMLInterface.cpp.
References CLocaleString::fromUtf8(), load(), and mPWD.
 {
   mPWD = relativeTo;
   std::ifstream is(CLocaleString::fromUtf8(fileName).c_str());
   if (is.fail()) return false;
   return load(is, relativeTo);
 }
virtual bool CCopasiXMLInterface::save (std::ostream & os, const std::string & relativeTo) pure virtual
Save information to a given ostream.
Parameters
std::ostream & os
const std::string & relativeTo
Returns
bool success
Implemented in CConfigurationFile::CXML, and CCopasiXML.
Referenced by save().
bool CCopasiXMLInterface::save (const std::string & fileName, const std::string & relativeTo)
Save information to a file.
Parameters
const std::string & fileName
const std::string & relativeTo
Returns
bool success
Definition at line 291 of file CCopasiXMLInterface.cpp.
References CLocaleString::fromUtf8(), mPWD, and save().
 {
   mPWD = relativeTo;
   std::ofstream os(CLocaleString::fromUtf8(fileName).c_str());
   if (os.fail()) return false;
   if (!save(os, relativeTo)) return false;
   return true;
 }
bool CCopasiXMLInterface::saveData (const std::string & data) protected
Save CDATA to the ostream
Parameters
const std::string & data
Returns
bool success
Definition at line 305 of file CCopasiXMLInterface.cpp.
References encode(), mIndent, and mpOstream.
Referenced by CCopasiXML::saveFunctionList(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), saveParameter(), CCopasiXML::saveRenderTextElement(), CCopasiXML::saveReportSection(), and saveXhtml().
 {
   *mpOstream << mIndent << CCopasiXMLInterface::encode(data) << std::endl;
   return true;
 }
bool CCopasiXMLInterface::saveElement (const std::string & name, CXMLAttributeList & attributeList) protected
Save an XML element to the ostream
Parameters
const std::string & name
CXMLAttributeList & attributeList
Returns
bool success
Definition at line 339 of file CCopasiXMLInterface.cpp.
References mIndent, and mpOstream.
Referenced by CCopasiXML::saveColorDefinition(), CCopasiXML::saveDimensions(), CCopasiXML::saveEllipseElement(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGradientStop(), CCopasiXML::saveGUI(), CCopasiXML::saveImageElement(), CCopasiXML::saveLayoutList(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), saveParameter(), CCopasiXML::savePlotList(), CCopasiXML::savePosition(), CCopasiXML::saveRectangleElement(), CCopasiXML::saveRenderPoint(), CCopasiXML::saveReportList(), CCopasiXML::saveReportSection(), CCopasiXML::saveSBMLReference(), and CCopasiXML::saveTaskList().
 {
   *mpOstream << mIndent << "<" << name;
   *mpOstream << attributeList;
   *mpOstream << "/>" << std::endl;
   return true;
 }
bool CCopasiXMLInterface::saveParameter (const CCopasiParameter & parameter) protected
Save a Parameter.
Parameters
const CCopasiParameter & parameter
Returns
bool success
Definition at line 376 of file CCopasiXMLInterface.cpp.
References CXMLAttributeList::add(), CCopasiParameter::BOOL, CCopasiParameter::CN, CCopasiParameter::DOUBLE, endSaveElement(), CCopasiParameter::EXPRESSION, CCopasiParameter::FILE, CDirEntry::fileName(), CCopasiObject::getObjectName(), CCopasiParameter::getType(), CCopasiParameter::getValue(), CCopasiParameter::GROUP, CCopasiParameter::INT, CCopasiParameter::INVALID, CDirEntry::isRelativePath(), CCopasiParameter::KEY, CDirEntry::makePathRelative(), mPWD, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pEXPRESSION, CCopasiParameter::Value::pFILE, CCopasiParameter::Value::pGROUP, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pKEY, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, saveData(), saveElement(), saveParameterGroup(), CXMLAttributeList::skip(), startSaveElement(), CCopasiParameter::STRING, CCopasiParameter::UDOUBLE, CCopasiParameter::UINT, and CCopasiParameter::XMLType.
Referenced by saveParameterGroup().
 {
   bool success = true;
   CXMLAttributeList Attributes;
   std::string File;
   Attributes.add("name", parameter.getObjectName());
   CCopasiParameter::Type Type = parameter.getType();
   Attributes.add("type", CCopasiParameter::XMLType[Type]);
   switch (parameter.getType())
     {
       case CCopasiParameter::DOUBLE:
         Attributes.add("value", * parameter.getValue().pDOUBLE);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::UDOUBLE:
         Attributes.add("value", * parameter.getValue().pUDOUBLE);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::INT:
         Attributes.add("value", * parameter.getValue().pINT);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::UINT:
         Attributes.add("value", * parameter.getValue().pUINT);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::BOOL:
         Attributes.add("value", * parameter.getValue().pBOOL);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::STRING:
         Attributes.add("value", * parameter.getValue().pSTRING);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::KEY:
         Attributes.add("value", * parameter.getValue().pKEY);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::FILE:
         File = * parameter.getValue().pFILE;
         if (!CDirEntry::isRelativePath(File) &&
             !CDirEntry::makePathRelative(File, mPWD))
           File = CDirEntry::fileName(File);
         Attributes.add("value", File);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::CN:
         Attributes.add("value", * parameter.getValue().pCN);
         if (!saveElement("Parameter", Attributes)) success = false;
         break;
       case CCopasiParameter::EXPRESSION:
         if (!startSaveElement("ParameterText", Attributes)) success = false;
         if (!saveData(*parameter.getValue().pEXPRESSION)) success = false;
         if (!endSaveElement("ParameterText")) success = false;
         break;
       case CCopasiParameter::GROUP:
         Attributes.skip(1);
         if (!startSaveElement("ParameterGroup", Attributes)) success = false;
         if (!saveParameterGroup(* parameter.getValue().pGROUP)) success = false;
         if (!endSaveElement("ParameterGroup")) success = false;
         break;
       case CCopasiParameter::INVALID:
       default:
         success = false;
         break;
     }
   return success;
 }
bool CCopasiXMLInterface::saveParameterGroup (const std::vector< CCopasiParameter * > & group) protected
Save a Parameter Group.
Parameters
const CCopasiParameterGroup::parameterGroup & group
Returns
bool success
Definition at line 489 of file CCopasiXMLInterface.cpp.
References saveParameter().
Referenced by saveParameter(), CCopasiXML::savePlotList(), and CCopasiXML::saveTaskList().
 {
   bool success = true;
   std::vector< CCopasiParameter * >::const_iterator it = group.begin();
   std::vector< CCopasiParameter * >::const_iterator end = group.end();
   for (; it != end; ++it)
     if (!saveParameter(**it)) success = false;
   return success;
 }
bool CCopasiXMLInterface::saveXhtml (const std::string & xhtml) protected
Save xhtml to the ostream
Parameters
const std::string & xhtml
Returns
bool success
Definition at line 312 of file CCopasiXMLInterface.cpp.
References mIndent, mpOstream, and saveData().
Referenced by CCopasiXML::saveAnnotation(), and CCopasiXML::saveReportList().
 {
   // if there is nothing to save bail
   if (xhtml.empty())
     return true;
   std::string::size_type start = xhtml.find_first_not_of("\x0a\x0d\t ");
   if (start != std::string::npos && xhtml[start] == '<')
     {
       std::string::size_type pos = xhtml.find('>');
       std::string FirstElement = xhtml.substr(0, pos);
       if (FirstElement.find("xmlns=\"http://www.w3.org/1999/xhtml\"") == std::string::npos
           && FirstElement.find("xmlns='http://www.w3.org/1999/xhtml'") == std::string::npos)
         FirstElement += " xmlns=\"http://www.w3.org/1999/xhtml\"";
       *mpOstream << mIndent << FirstElement << xhtml.substr(pos) << std::endl;
     }
   else
     {
       saveData(xhtml);
     }
   return true;
 }
bool CCopasiXMLInterface::startSaveElement (const std::string & name) protected
Start saving an XML element to the ostream. Call endSaveElement to conclude.
Parameters
const std::string & name
Returns
bool success
Definition at line 349 of file CCopasiXMLInterface.cpp.
References mIndent, and mpOstream.
Referenced by CCopasiXML::save(), CCopasiXML::saveAnnotation(), CCopasiXML::saveBoundingBox(), CCopasiXML::saveCurve(), CCopasiXML::saveCurveElements(), CCopasiXML::saveFunctionList(), CCopasiXML::saveGlobalRenderInformation(), CCopasiXML::saveGlobalStyle(), CCopasiXML::saveGroupElement(), CCopasiXML::saveGUI(), CCopasiXML::saveLayoutList(), CCopasiXML::saveLinearGradient(), CCopasiXML::saveLineEnding(), CCopasiXML::saveListOfGlobalRenderInformation(), CCopasiXML::saveListOfLocalRenderInformation(), CCopasiXML::saveLocalRenderInformation(), CCopasiXML::saveLocalStyle(), CCopasiXML::saveModel(), CCopasiXML::saveModelParameter(), saveParameter(), CCopasiXML::savePlotList(), CCopasiXML::savePolygonElement(), CCopasiXML::saveRadialGradient(), CCopasiXML::saveRenderCurveElement(), CCopasiXML::saveRenderInformationDefinitionElements(), CCopasiXML::saveRenderTextElement(), CCopasiXML::saveReportList(), CCopasiXML::saveReportSection(), CCopasiXML::saveSBMLReference(), and CCopasiXML::saveTaskList().
 {
   *mpOstream << mIndent << "<" << name << ">" << std::endl;
   mIndent += "  ";
   return true;
 }
bool CCopasiXMLInterface::startSaveElement (const std::string & name, CXMLAttributeList & attributeList) protected
Start saving an XML element to the ostream. Call endSaveElement to conclude.
Parameters
const std::string & name
CXMLAttributeList & attributeList
Returns
bool success
Definition at line 357 of file CCopasiXMLInterface.cpp.
References mIndent, and mpOstream.
 {
   *mpOstream << mIndent << "<" << name;
   *mpOstream << attributeList;
   *mpOstream << ">" << std::endl;
   mIndent += "  ";
   return true;
 }
std::string CCopasiXMLInterface::utf8 (const std::string & str) static
Encode a given string to a valid XML string
Parameters
const C_FLOAT64 & dbl
Returns
std::string encoded Encode a given string to a utf-8 string
Parameters
const std::string & str
Returns
std::string encoded
Definition at line 245 of file CCopasiXMLInterface.cpp.
Referenced by CMIRIAMResourceObject::unescapeId().
 {
   std::ostringstream utf8;
   /* Based on RFC 2279.
      Since every string within COPASI is treated as latin1 and input
      is only obtained through QT and Expat which will provide latin1
      encoded strings the below should suffice. */
   size_t i, imax;
   for (i = 0, imax = str.length(); i < imax; i++)
     {
       const unsigned char Char = str[i];
       if (Char < 0x80)
         utf8 << Char;
       else
         {
           utf8 << (unsigned char)(0xc0 + ((Char >> 6) & 0x03));
           utf8 << (unsigned char)(0x80 + (Char & 0x3f));
         }
     }
   return utf8.str();
 }
Member Data Documentation
std::string CCopasiXMLInterface::mIndent protected
Indent
Definition at line 133 of file CCopasiXMLInterface.h.
Referenced by endSaveElement(), saveData(), saveElement(), CCopasiXML::saveModel(), saveXhtml(), and startSaveElement().
std::istream* CCopasiXMLInterface::mpIstream protected
A pointer to the input stream
Definition at line 123 of file CCopasiXMLInterface.h.
Referenced by CCopasiXML::load().
std::ostream* CCopasiXMLInterface::mpOstream protected
A pointer to the output stream
Definition at line 128 of file CCopasiXMLInterface.h.
Referenced by endSaveElement(), CCopasiXML::save(), CCopasiXML::saveAnnotation(), saveData(), saveElement(), CCopasiXML::saveModel(), saveXhtml(), and startSaveElement().
std::string CCopasiXMLInterface::mPWD protected
The filename if available
Definition at line 138 of file CCopasiXMLInterface.h.
Referenced by CCopasiXML::load(), load(), CCopasiXML::save(), save(), saveParameter(), CCopasiXML::saveSBMLReference(), and CCopasiXML::saveTaskList().
The documentation for this class was generated from the following files:
CCopasiXMLInterface.h
CCopasiXMLInterface.cpp