COPASI API: CMCATask Class Reference
CMCATask Class Reference
#include <CMCATask.h>
Public Member Functions
CMCATask (const CCopasiContainer *pParent=NULL)
CMCATask (const CMCATask &src, const CCopasiContainer *pParent=NULL)
virtual CCopasiMethod * createMethod (const int &type) const
virtual bool initialize (const OutputFlag &of, COutputHandler *pOutputHandler, std::ostream *pOstream)
void load (CReadConfig &configBuffer)
void printResult (std::ostream *ostream) const
virtual bool process (const bool &useInitialValues)
virtual bool restore ()
virtual bool updateMatrices ()
virtual ~CMCATask ()
Public Member Functions inherited from CCopasiTask
CCopasiTask (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const Type &taskType, const CCopasiContainer *pParent=NULL, const std::string &type="Task")
CCopasiTask (const CCopasiTask &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
CProcessReport * getCallBack () const
const CDescription & getDescription () const
virtual const std::string & getKey () const
CCopasiMethod * getMethod ()
const CCopasiMethod * getMethod () const
COutputHandler * getOutputHandler () const
const OutputFlag & getOutputMode () const
CCopasiProblem * getProblem ()
const CCopasiProblem * getProblem () const
CReport & getReport ()
const CResult & getResult () const
CCopasiParameterGroup * getSliders ()
Type getType () const
const bool & isScheduled () const
const bool & isUpdateModel () const
virtual void output (const COutputInterface::Activity &activity)
virtual void separate (const COutputInterface::Activity &activity)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setMethodType (const int &type)
void setScheduled (const bool &scheduled)
void setType (const Type &type)
void setUpdateModel (const bool &updateModel)
virtual ~CCopasiTask ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void cleanup ()
Friends
std::ostream & operator<< (std::ostream &os, const CMCATask &A)
Additional Inherited Members
Public Types inherited from CCopasiTask
enum eOutputFlagBase {
INITIALIZE = 0x01, STREAM = 0x02, FINISH = 0x04, REPORT = 0x10,
PLOT = 0x20, TIME_SERIES = 0x40
}
enum OutputFlag {
NO_OUTPUT = 0, OUTPUT_BEFORE = INITIALIZE, OUTPUT_AFTER = FINISH, OUTPUT = REPORT | PLOT | STREAM,
OUTPUT_SE = REPORT | PLOT | INITIALIZE | STREAM | FINISH, OUTPUT_UI = REPORT | PLOT | TIME_SERIES | INITIALIZE | STREAM | FINISH, ONLY_TIME_SERIES = TIME_SERIES | INITIALIZE | STREAM | FINISH
}
enum Type {
steadyState = 0, timeCourse, scan, fluxMode,
optimization, parameterFitting, mca, lyap,
tssAnalysis, sens, moieties, crosssection,
lna, unset
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiTask
static bool isValidMethod (const unsigned int &method, const unsigned int *validMethods)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Public Attributes inherited from CCopasiTask
std::string Error
std::string Warning
Static Public Attributes inherited from CCopasiTask
static const std::string TypeName []
static const unsigned int ValidMethods []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiTask
CDescription mDescription
OutputFlag mDoOutput
std::string mKey
unsigned C_INT32 mOutputCounter
CProcessReport * mpCallBack
CState * mpInitialState
CCopasiMethod * mpMethod
COutputHandler * mpOutputHandler
CCopasiProblem * mpProblem
CCopasiParameterGroup * mpSliders
CReport mReport
CResult mResult
bool mScheduled
Type mType
bool mUpdateModel
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 46 of file CMCATask.h.
Constructor & Destructor Documentation
CMCATask::CMCATask (const CCopasiContainer * pParent = NULL)
A pointer to the found elasticities A pointer to the found flux control coefficients. A pointer to the found concentration control coefficients. Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 40 of file CMCATask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiMethod::mcaMethodReder, CCopasiTask::mpMethod, and CCopasiTask::mpProblem.
                                                   :
   CCopasiTask(CCopasiTask::mca, pParent)
 {
   mpProblem = new CMCAProblem(this);
   mpMethod = createMethod(CCopasiMethod::mcaMethodReder);
   this->add(mpMethod, true);
 }
CMCATask::CMCATask (const CMCATask & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CMCATask & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 49 of file CMCATask.cpp.
References CCopasiContainer::add(), createMethod(), CCopasiMethod::getSubType(), CCopasiTask::mpMethod, and CCopasiTask::mpProblem.
                                                     :
   CCopasiTask(src, pParent)
 {
   mpProblem =
     new CMCAProblem(*(CMCAProblem *) src.mpProblem, this);
   mpMethod = createMethod(src.mpMethod->getSubType());
   this->add(mpMethod, true);
 }
CMCATask::~CMCATask () virtual
Destructor
Definition at line 60 of file CMCATask.cpp.
 {}
Member Function Documentation
void CMCATask::cleanup () private
cleanup()
Definition at line 71 of file CMCATask.cpp.
 {}
CCopasiMethod * CMCATask::createMethod (const int & type) const virtual
Create a method of the specified type to solve the task. It is the duty of the caller to release the CCopasiMethod.
Parameters
const CCopasiMethod::SubType & type
Returns
CCopasiMethod *
Reimplemented from CCopasiTask.
Definition at line 64 of file CMCATask.cpp.
References CMCAMethod::createMethod().
Referenced by CMCATask().
 {
   CCopasiMethod::SubType Type = (CCopasiMethod::SubType) type;
   return CMCAMethod::createMethod(Type);
 }
bool CMCATask::initialize (const OutputFlag & of, COutputHandler * pOutputHandler, std::ostream * pOstream) virtual
Initialize the task. If an ostream is given this ostream is used instead of the target specified in the report. This allows nested tasks to share the same output device.
Parameters
const OutputFlag & of
COutputHandler * pOutputHandler
std::ostream * pOstream (default: NULL)
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 102 of file CMCATask.cpp.
References CModel::compileIfNecessary(), CCopasiProblem::getModel(), CReport::getStream(), CMCAProblem::getSubTask(), CSteadyStateTask::initialize(), CCopasiTask::initialize(), CCopasiMethod::isValidProblem(), CCopasiTask::mpCallBack, CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::mReport, CCopasiTask::NO_OUTPUT, and updateMatrices().
 {
   assert(mpProblem && mpMethod);
   CMCAProblem* pProblem =
     dynamic_cast<CMCAProblem *>(mpProblem);
   assert(pProblem);
   if (!mpMethod->isValidProblem(mpProblem)) return false;
   //we need to resize an initialize the result matrices before initializing the output
   if (!updateMatrices()) return false;
   bool success = true;
   //initialize reporting
   if (!CCopasiTask::initialize(of, pOutputHandler, pOstream)) success = false;
   if (!pProblem->getModel()->compileIfNecessary(mpCallBack)) success = false;
   CSteadyStateTask *pSubTask = pProblem->getSubTask();
   if (pSubTask)
     success = pSubTask->initialize(CCopasiTask::NO_OUTPUT, NULL, mReport.getStream());
   //success = pSubTask->initialize(of, mReport.getStream());
   return success;
 }
void CMCATask::load (CReadConfig & configBuffer)
Loads parameters for this solver with data coming from a CReadConfig object. (CReadConfig object reads an input stream)
Parameters
configbuffer reference to a CReadConfig object.
Definition at line 74 of file CMCATask.cpp.
References CReadConfig::getVariable(), CReadConfig::LOOP, CCopasiTask::mpMethod, CCopasiTask::mpProblem, and CCopasiTask::mScheduled.
 {
   configBuffer.getVariable("MCA", "bool", &mScheduled,
                            CReadConfig::LOOP);
   ((CMCAProblem *) mpProblem)->load(configBuffer);
   ((CMCAMethod *) mpMethod)->load(configBuffer);
 }
void CMCATask::printResult (std::ostream * ostream) const
This functionality is expected from the problem but has to be implemented here for the moment. This is called from the corresponding method of the problem
Definition at line 201 of file CMCATask.cpp.
References CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, CCopasiProblem::getModel(), CMCAMethod::getScaledConcentrationCCAnn(), CMCAMethod::getScaledElasticitiesAnn(), CMCAMethod::getScaledFluxCCAnn(), CMCAMethod::getSteadyStateStatus(), CMCAProblem::getSubTask(), CMCAMethod::getUnscaledConcentrationCCAnn(), CMCAMethod::getUnscaledElasticitiesAnn(), CMCAMethod::getUnscaledFluxCCAnn(), CMCAProblem::isSteadyStateRequested(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, CSteadyStateMethod::notFound, and CMCAMethod::setModel().
Referenced by CMCAProblem::printResult().
 {
   assert(mpProblem && mpMethod);
   CMCAProblem* pProblem =
     dynamic_cast<CMCAProblem *>(mpProblem);
   assert(pProblem);
   CMCAMethod* pMethod = dynamic_cast<CMCAMethod *>(mpMethod);
   assert(pMethod);
   pMethod->setModel(mpProblem->getModel());
   std::ostream & os = *ostream;
   bool showCCs = false; //show CCs?
   bool showSS = false; //show Steady State result?
   if (pProblem->isSteadyStateRequested())
     {
       if (pMethod->getSteadyStateStatus() == CSteadyStateMethod::found)
         {
           os << "A steady state was found. All coefficients are shown." << std::endl;
           showCCs = true;
           showSS = true;
         }
       if (pMethod->getSteadyStateStatus() == CSteadyStateMethod::foundEquilibrium)
         {
           os << "Found equilibrium steady state. Only elasticities available." << std::endl;
           showSS = true;
         }
       if (pMethod->getSteadyStateStatus() == CSteadyStateMethod::foundNegative)
         {
           os << "Invalid steady state found (negative concentrations)." << std::endl;
           showSS = true;
         }
       if (pMethod->getSteadyStateStatus() == CSteadyStateMethod::notFound)
         {
           os << "No steady state found. Only elasticities available." << std::endl;
         }
     }
   else
     {
       os << "Since no steady state calculation was requested only elasticities are shown." << std::endl;
     }
   os << std::endl;
   os << *pMethod->getUnscaledElasticitiesAnn() << std::endl;
   os << *pMethod->getScaledElasticitiesAnn() << std::endl;
   if (showCCs)
     {
       os << *pMethod->getUnscaledConcentrationCCAnn() << std::endl;
       os << *pMethod->getScaledConcentrationCCAnn() << std::endl;
       os << *pMethod->getUnscaledFluxCCAnn() << std::endl;
       os << *pMethod->getScaledFluxCCAnn() << std::endl;
     }
   if (showSS)
     {
       if (!pProblem->getSubTask())
         {
           os << "Problem with steady state calculation. Please report as bug!" << std::endl;
           return;
         }
       os << "Results of the steady state subtask (the state for which the MCA was performed):" << std::endl;
       os << *pProblem->getSubTask();
     }
 }
bool CMCATask::process (const bool & useInitialValues) virtual
Process the task with or without initializing to the initial state.
Parameters
const bool & useInitialValues
Returns
bool success
Reimplemented from CCopasiTask.
Definition at line 134 of file CMCATask.cpp.
References COutputInterface::AFTER, CModel::applyInitialValues(), COutputInterface::BEFORE, COutputInterface::DURING, CCopasiProblem::getModel(), CCopasiTask::mpCallBack, CCopasiTask::mpMethod, CCopasiTask::mpProblem, CCopasiTask::output(), CMCAMethod::process(), CSteadyStateTask::process(), CCopasiTask::setCallBack(), and CMCAMethod::setSteadyStateTask().
 {
   bool success = true;
   assert(mpMethod);
   CMCAMethod* pMethod = dynamic_cast<CMCAMethod *>(mpMethod);
   assert(pMethod);
   //  pMethod->setModel(mpProblem->getModel());
   CSteadyStateTask *pSubTask =
     dynamic_cast<CMCAProblem *>(mpProblem)->getSubTask();
   if (pSubTask)
     {
       pSubTask->setCallBack(mpCallBack);
       success &= pSubTask->process(useInitialValues);
       if (!success && useInitialValues)
         {
           mpProblem->getModel()->applyInitialValues();
         }
       pMethod->setSteadyStateTask(pSubTask);
     }
   else
     {
       pMethod->setSteadyStateTask(NULL);
       if (useInitialValues)
         {
           mpProblem->getModel()->applyInitialValues();
         }
     }
   CCopasiTask::output(COutputInterface::BEFORE);
   pMethod->process();
   CCopasiTask::output(COutputInterface::DURING);
   CCopasiTask::output(COutputInterface::AFTER);
   return success;
 }
bool CMCATask::restore () virtual
Perform neccessary cleaup procedures
Reimplemented from CCopasiTask.
Definition at line 179 of file CMCATask.cpp.
References CCopasiTask::mpProblem, CSteadyStateTask::restore(), and CCopasiTask::restore().
 {
   bool success = CCopasiTask::restore();
   CSteadyStateTask *pSubTask =
     dynamic_cast<CMCAProblem *>(mpProblem)->getSubTask();
   if (pSubTask)
     success &= pSubTask->restore();
   return success;
 }
bool CMCATask::updateMatrices () virtual
Resizes result matrices and updates array annotations for a specific task. This is used when we need to know about the data structures of a task result without actually performing the task, e.g. when selecting objects for output. For now we assume that this functionality is also performed when initialize() is called.
Reimplemented from CCopasiTask.
Definition at line 84 of file CMCATask.cpp.
References CCopasiProblem::getModel(), CCopasiMethod::isValidProblem(), CCopasiTask::mpMethod, CCopasiTask::mpProblem, CMCAMethod::resizeAllMatrices(), and CMCAMethod::setModel().
Referenced by initialize().
 {
   assert(mpProblem != NULL && mpMethod != NULL);
   assert(dynamic_cast<CMCAProblem *>(mpProblem) != NULL);
   if (!mpMethod->isValidProblem(mpProblem)) return false;
   CMCAMethod * pMethod = dynamic_cast<CMCAMethod*>(mpMethod);
   if (!pMethod) return false;
   pMethod->setModel(mpProblem->getModel());
   pMethod->resizeAllMatrices();
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CMCATask & A) friend
The documentation for this class was generated from the following files:
CMCATask.h
CMCATask.cpp