COPASI API: CLayoutState Class Reference
CLayoutState Class Reference
#include <CLayoutState.h>
Public Member Functions
void applyTo (CLayout *layout) const
CLayoutState (const CLayout *layout)
virtual ~CLayoutState ()
Static Public Member Functions
static void tagLayout (CLayout *layout)
Protected Types
typedef std::map< const
std::string, CLBoundingBox * > StringBoundMap
typedef std::map< const
std::string, CLCurve * > StringCurveMap
Protected Attributes
std::map< const std::string,
CLBoundingBox * > mAdditionalState
std::map< const std::string,
CLBoundingBox * > mCompartmentState
std::map< const std::string,
CLCurve * > mCurves
std::map< const std::string,
CLBoundingBox * > mReactionState
std::map< const std::string,
CLBoundingBox * > mSpeciesState
std::map< const std::string,
CLBoundingBox * > mTextState
Detailed Description
Definition at line 16 of file CLayoutState.h.
Member Typedef Documentation
typedef std::map<const std::string, CLBoundingBox*> CLayoutState::StringBoundMap protected
Definition at line 27 of file CLayoutState.h.
typedef std::map<const std::string, CLCurve*> CLayoutState::StringCurveMap protected
Definition at line 28 of file CLayoutState.h.
Constructor & Destructor Documentation
CLayoutState::CLayoutState (const CLayout * layout)
Definition at line 84 of file CLayoutState.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CLayout::getListOfCompartmentGlyphs(), CLayout::getListOfGeneralGlyphs(), CLayout::getListOfMetaboliteGlyphs(), CLayout::getListOfReactionGlyphs(), CLayout::getListOfTextGlyphs(), mAdditionalState, mCompartmentState, mCurves, mReactionState, mSpeciesState, and mTextState.
   : mAdditionalState()
   , mCompartmentState()
   , mReactionState()
   , mSpeciesState()
   , mTextState()
   , mCurves()
 {
   if (layout == NULL) return;
   const CCopasiVector<CLGeneralGlyph> & general = layout->getListOfGeneralGlyphs();
   CCopasiVector<CLGeneralGlyph>::const_iterator generalIt = general.begin();
   while (generalIt != general.end())
     {
       mAdditionalState[(*generalIt)->getTag()] = new CLBoundingBox((*generalIt)->getBoundingBox());
       ++generalIt;
     }
   const CCopasiVector<CLCompartmentGlyph> & comps = layout->getListOfCompartmentGlyphs();
   CCopasiVector<CLCompartmentGlyph>::const_iterator compIt = comps.begin();
   while (compIt != comps.end())
     {
       mCompartmentState[(*compIt)->getTag()] = new CLBoundingBox((*compIt)->getBoundingBox());
       ++compIt;
     }
   const CCopasiVector<CLReactionGlyph> & reactions = layout->getListOfReactionGlyphs();
   CCopasiVector<CLReactionGlyph>::const_iterator reactIt = reactions.begin();
   while (reactIt != reactions.end())
     {
       mReactionState[(*reactIt)->getTag()] = new CLBoundingBox((*reactIt)->getBoundingBox());
       mCurves[(*reactIt)->getTag()] = new CLCurve((*reactIt)->getCurve());
       CCopasiVector<CLMetabReferenceGlyph>::const_iterator refIt = (*reactIt)->getListOfMetabReferenceGlyphs().begin();
       for (; refIt != (*reactIt)->getListOfMetabReferenceGlyphs().end(); ++refIt)
         mCurves[(*refIt)->getTag()] = new CLCurve((*refIt)->getCurve());
       ++reactIt;
     }
   const CCopasiVector<CLMetabGlyph> & species = layout->getListOfMetaboliteGlyphs();
   CCopasiVector<CLMetabGlyph>::const_iterator speciesIt = species.begin();
   while (speciesIt != species.end())
     {
       mSpeciesState[(*speciesIt)->getTag()] = new CLBoundingBox((*speciesIt)->getBoundingBox());
       ++speciesIt;
     }
   const CCopasiVector<CLTextGlyph> & texts = layout->getListOfTextGlyphs();
   CCopasiVector<CLTextGlyph>::const_iterator textIt = texts.begin();
   while (textIt != texts .end())
     {
       mTextState[(*textIt)->getTag()] = new CLBoundingBox((*textIt)->getBoundingBox());
       ++textIt;
     }
 }
CLayoutState::~CLayoutState () virtual
Definition at line 148 of file CLayoutState.cpp.
References mAdditionalState, mCompartmentState, mCurves, mReactionState, mSpeciesState, and mTextState.
 {
   std::map<const std::string, CLBoundingBox*>::reverse_iterator it;
   for (it = mAdditionalState.rbegin(); it != mAdditionalState.rend(); ++it)
     {
       delete it->second;
     }
   for (it = mCompartmentState.rbegin(); it != mCompartmentState.rend(); ++it)
     {
       delete it->second;
     }
   for (it = mReactionState.rbegin(); it != mReactionState.rend(); ++it)
     {
       delete it->second;
     }
   for (it = mSpeciesState.rbegin(); it != mSpeciesState.rend(); ++it)
     {
       delete it->second;
     }
   for (it = mTextState.rbegin(); it != mTextState.rend(); ++it)
     {
       delete it->second;
     }
   std::map<const std::string, CLCurve*>::reverse_iterator curveIt;
   for (curveIt = mCurves.rbegin(); curveIt != mCurves.rend(); ++curveIt)
     {
       delete curveIt->second;
     }
 }
Member Function Documentation
void CLayoutState::applyTo (CLayout * layout) const
Definition at line 198 of file CLayoutState.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CLayout::getListOfCompartmentGlyphs(), CLayout::getListOfGeneralGlyphs(), CLayout::getListOfMetaboliteGlyphs(), CLayout::getListOfReactionGlyphs(), CLayout::getListOfTextGlyphs(), mAdditionalState, mCompartmentState, mCurves, mReactionState, mSpeciesState, mTextState, and STATE_SET_POSITIONS.
 {
   if (layout == NULL) return;
   CLayoutState current(layout);
   CCopasiVector<CLGeneralGlyph> & general = layout->getListOfGeneralGlyphs();
   CCopasiVector<CLGeneralGlyph>::iterator generalIt = general.begin();
   STATE_SET_POSITIONS(mAdditionalState, generalIt, general.end());
   CCopasiVector<CLCompartmentGlyph> & comps = layout->getListOfCompartmentGlyphs();
   CCopasiVector<CLCompartmentGlyph>::iterator compIt = comps.begin();
   STATE_SET_POSITIONS(mCompartmentState, compIt, comps.end());
   CCopasiVector<CLReactionGlyph> & reactions = layout->getListOfReactionGlyphs();
   CCopasiVector<CLReactionGlyph>::iterator reactIt = reactions.begin();
   STATE_SET_POSITIONS(mReactionState, reactIt, reactions.end());
   for (reactIt = reactions.begin(); reactIt != reactions.end(); ++reactIt)
     {
       const std::string& rkey = ((*reactIt)->getTag());
       StringCurveMap::const_iterator cIt = mCurves.find(rkey);
       if (cIt != mCurves.end())
         {
           CLCurve* current = cIt->second;
           (*reactIt)->setCurve(*current);
         }
       CCopasiVector<CLMetabReferenceGlyph>::iterator refIt = (*reactIt)->getListOfMetabReferenceGlyphs().begin();
       for (; refIt != (*reactIt)->getListOfMetabReferenceGlyphs().end(); ++refIt)
         {
           const std::string& key = ((*refIt)->getTag());
           cIt = mCurves.find(key);
           if (cIt == mCurves.end())
             continue;
           CLCurve* current = cIt->second;
           (*refIt)->setCurve(*current);
         }
     }
   CCopasiVector<CLMetabGlyph> & species = layout->getListOfMetaboliteGlyphs();
   CCopasiVector<CLMetabGlyph>::iterator speciesIt = species.begin();
   STATE_SET_POSITIONS(mSpeciesState, speciesIt, species.end());
   CCopasiVector<CLTextGlyph> & texts = layout->getListOfTextGlyphs();
   CCopasiVector<CLTextGlyph>::iterator textIt = texts .begin();
   STATE_SET_POSITIONS(mTextState, textIt, texts.end());
 }
void CLayoutState::tagLayout (CLayout * layout) static
Definition at line 17 of file CLayoutState.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CLayout::getListOfCompartmentGlyphs(), CLayout::getListOfGeneralGlyphs(), CLayout::getListOfMetaboliteGlyphs(), CLayout::getListOfReactionGlyphs(), CLayout::getListOfTextGlyphs(), and tagKey().
Referenced by CQNewMainWindow::createSpringLayout(), CQAnimationWindow::slotAutoLayout(), and CQAnimationWindow::slotRandomizeLayout().
 {
   if (layout == NULL) return;
   CCopasiVector<CLGeneralGlyph> & general = layout->getListOfGeneralGlyphs();
   CCopasiVector<CLGeneralGlyph>::iterator generalIt = general.begin();
   while (generalIt != general.end())
     {
       tagKey((*generalIt));
       CCopasiVector<CLReferenceGlyph>::iterator refIt = (*generalIt)->getListOfReferenceGlyphs().begin();
       for (; refIt != (*generalIt)->getListOfReferenceGlyphs().end(); ++refIt)
         tagKey(*refIt);
       CCopasiVector<CLGraphicalObject>::iterator subIt = (*generalIt)->getListOfSubglyphs().begin();
       for (; subIt  != (*generalIt)->getListOfSubglyphs().end(); ++subIt)
         tagKey(*subIt);
       ++generalIt;
     }
   CCopasiVector<CLCompartmentGlyph> & comps = layout->getListOfCompartmentGlyphs();
   CCopasiVector<CLCompartmentGlyph>::iterator compIt = comps.begin();
   while (compIt != comps.end())
     {
       tagKey((*compIt));
       ++compIt;
     }
   CCopasiVector<CLReactionGlyph> & reactions = layout->getListOfReactionGlyphs();
   CCopasiVector<CLReactionGlyph>::iterator reactIt = reactions.begin();
   while (reactIt != reactions.end())
     {
       tagKey((*reactIt));
       CCopasiVector<CLMetabReferenceGlyph>::iterator refIt = (*reactIt)->getListOfMetabReferenceGlyphs().begin();
       for (; refIt != (*reactIt)->getListOfMetabReferenceGlyphs().end(); ++refIt)
         tagKey(*refIt);
       ++reactIt;
     }
   CCopasiVector<CLMetabGlyph> & species = layout->getListOfMetaboliteGlyphs();
   CCopasiVector<CLMetabGlyph>::iterator speciesIt = species.begin();
   while (speciesIt != species.end())
     {
       tagKey((*speciesIt));
       ++speciesIt;
     }
   CCopasiVector<CLTextGlyph> & texts = layout->getListOfTextGlyphs();
   CCopasiVector<CLTextGlyph>::iterator textIt = texts .begin();
   while (textIt != texts .end())
     {
       tagKey((*textIt));
       ++textIt;
     }
 }
Member Data Documentation
std::map<const std::string, CLBoundingBox*> CLayoutState::mAdditionalState protected
Definition at line 29 of file CLayoutState.h.
Referenced by applyTo(), CLayoutState(), and ~CLayoutState().
std::map<const std::string, CLBoundingBox*> CLayoutState::mCompartmentState protected
Definition at line 30 of file CLayoutState.h.
Referenced by applyTo(), CLayoutState(), and ~CLayoutState().
std::map<const std::string, CLCurve*> CLayoutState::mCurves protected
Definition at line 34 of file CLayoutState.h.
Referenced by applyTo(), CLayoutState(), and ~CLayoutState().
std::map<const std::string, CLBoundingBox*> CLayoutState::mReactionState protected
Definition at line 31 of file CLayoutState.h.
Referenced by applyTo(), CLayoutState(), and ~CLayoutState().
std::map<const std::string, CLBoundingBox*> CLayoutState::mSpeciesState protected
Definition at line 32 of file CLayoutState.h.
Referenced by applyTo(), CLayoutState(), and ~CLayoutState().
std::map<const std::string, CLBoundingBox*> CLayoutState::mTextState protected
Definition at line 33 of file CLayoutState.h.
Referenced by applyTo(), CLayoutState(), and ~CLayoutState().
The documentation for this class was generated from the following files:
CLayoutState.h
CLayoutState.cpp