COPASI API: CCopasiXMLParser::COPASIElement Class Reference
CCopasiXMLParser::COPASIElement Class Reference
Public Member Functions
COPASIElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~COPASIElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
COPASI = 0, ListOfFunctions, Model, ListOfTasks,
ListOfReports, ListOfPlots, GUI, ListOfLayouts,
SBMLReference
}
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2812 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::COPASIElement::Element private
Enumerator
COPASI
ListOfFunctions
Model
ListOfTasks
ListOfReports
ListOfPlots
GUI
ListOfLayouts
SBMLReference
Definition at line 2819 of file CCopasiXMLParser.h.
     {
       COPASI = 0,
       ListOfFunctions,
       Model,
       ListOfTasks,
       ListOfReports,
       ListOfPlots,
       GUI,
       ListOfLayouts,
       SBMLReference
     };
Constructor & Destructor Documentation
CCopasiXMLParser::COPASIElement::COPASIElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 464 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::COPASIElement::~COPASIElement () virtual
Destructor
Definition at line 469 of file CCopasiXMLParser.cpp.
 {deleteCurrentHandler();}
Member Function Documentation
void CCopasiXMLParser::COPASIElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 592 of file CCopasiXMLParser.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), CCopasiVectorN< CType >::getIndex(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CCopasiMessage::getLastMessage(), CCopasiParameter::getType(), CCopasiParameter::getValue(), CCopasiParameter::KEY, SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, SCopasiXMLParserCommon::pFunctionList, SCopasiXMLParserCommon::pGUI, CCopasiParameter::Value::pKEY, CCopasiVectorN< CType >::remove(), CCopasiParameter::setValue(), START_ELEMENT, and SCopasiXMLParserCommon::UnmappedKeyParameters.
 {
   if (!strcmp(pszName, "COPASI"))
     {
       mCurrentElement = START_ELEMENT;
       // We need to handle the unmapped parameters of type key.
       std::vector< std::string >::iterator it = mCommon.UnmappedKeyParameters.begin();
       std::vector< std::string >::iterator end = mCommon.UnmappedKeyParameters.end();
       for (; it != end; ++it)
         {
           CCopasiParameter * pParameter =
             dynamic_cast< CCopasiParameter * >(CCopasiRootContainer::getKeyFactory()->get(*it));
           if (pParameter != NULL &&
               pParameter->getType() == CCopasiParameter::KEY)
             {
               CCopasiObject * pObject =
                 mCommon.KeyMap.get(*pParameter->getValue().pKEY);
               if (pObject != NULL)
                 pParameter->setValue(pObject->getKey());
               else
                 pParameter->setValue(std::string(""));
             }
         }
       // We need to remove the no longer needed expression "Objective Function" from the function list.
       if (mCommon.pFunctionList != NULL &&
           mCommon.pFunctionList->getIndex("Objective Function") != C_INVALID_INDEX)
         {
           mCommon.pFunctionList->remove("Objective Function");
         }
       return;
     }
   if (!strcmp(pszName, "ParameterGroup"))
     {
       mCurrentElement = START_ELEMENT;
     }
   else if (!strcmp(pszName, "GUI") && mCommon.pGUI == NULL)
     {
       CCopasiMessage::getLastMessage();
     }
   deleteCurrentHandler();
   //TODO why no case statement with error checking (like in other elements)?
   return;
 }
void CCopasiXMLParser::COPASIElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 471 of file CCopasiXMLParser.cpp.
References C_INT32, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pGUI, SCopasiXMLParserCommon::pVersion, CVersion::setVersion(), strToInt(), and CCopasiMessage::WARNING.
 {
   mCurrentElement++; /* We should always be on the next element */
   mpCurrentHandler = NULL;
   const char * versionMajor;
   C_INT32 VersionMajor;
   const char * versionMinor;
   C_INT32 VersionMinor;
   const char * versionDevel;
   C_INT32 VersionDevel;
   bool CopasiSourcesModified = true;
   switch (mCurrentElement)
     {
       case COPASI:
         if (!strcmp(pszName, "COPASI"))
           {
             versionMajor = mParser.getAttributeValue("versionMajor", papszAttrs, "0");
             VersionMajor = strToInt(versionMajor);
             versionMinor = mParser.getAttributeValue("versionMinor", papszAttrs, "0");
             VersionMinor = strToInt(versionMinor);
             versionDevel = mParser.getAttributeValue("versionDevel", papszAttrs, "0");
             VersionDevel = strToInt(versionDevel);
             CopasiSourcesModified = mParser.toBool(mParser.getAttributeValue("copasiSourcesModified", papszAttrs, "true"));
             mCommon.pVersion->setVersion(VersionMajor, VersionMinor, VersionDevel, CopasiSourcesModified);
             return;
           }
         // We may have a configuration file which starts with a parameter group
         else if (!strcmp(pszName, "ParameterGroup"))
           {
             mpCurrentHandler = new ParameterGroupElement(mParser, mCommon);
           }
         else
           {
             mpCurrentHandler = &mParser.mUnknownElement;
             CCopasiMessage(CCopasiMessage::WARNING, MCXML + 10,
                            pszName, "COPASI", mParser.getCurrentLineNumber());
           }
         break;
       case ListOfFunctions:
         if (!strcmp(pszName, "ListOfFunctions"))
           mpCurrentHandler = new ListOfFunctionsElement(mParser, mCommon);
         break;
       case Model:
         if (!strcmp(pszName, "Model"))
           mpCurrentHandler = new ModelElement(mParser, mCommon);
         break;
       case ListOfTasks:
         if (!strcmp(pszName, "ListOfTasks"))
           mpCurrentHandler = new ListOfTasksElement(mParser, mCommon);
         break;
       case ListOfReports:
         if (!strcmp(pszName, "ListOfReports"))
           mpCurrentHandler = new ListOfReportsElement(mParser, mCommon);
         break;
       case ListOfPlots:
         if (!strcmp(pszName, "ListOfPlots"))
           mpCurrentHandler = new ListOfPlotsElement(mParser, mCommon);
         break;
       case GUI:
         if (!strcmp(pszName, "GUI"))
           {
             if (mCommon.pGUI)
               mpCurrentHandler = new GUIElement(mParser, mCommon);
             else
               mpCurrentHandler = &mParser.mUnknownElement;
           }
         break;
       case ListOfLayouts:
         if (!strcmp(pszName, "ListOfLayouts"))
           mpCurrentHandler = new ListOfLayoutsElement(mParser, mCommon);
         break;
       case SBMLReference:
         if (!strcmp(pszName, "SBMLReference"))
           mpCurrentHandler = new SBMLReferenceElement(mParser, mCommon);
         break;
       default:
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp