COPASI API: CCopasiXMLParser::SourceParameterElement Class Reference
CCopasiXMLParser::SourceParameterElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
SourceParameterElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~SourceParameterElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { SourceParameter = 0 }
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 624 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::SourceParameterElement::Element private
Enum of invoked parsers
Enumerator
SourceParameter
Definition at line 632 of file CCopasiXMLParser.h.
     {
       SourceParameter = 0
     };
Constructor & Destructor Documentation
CCopasiXMLParser::SourceParameterElement::SourceParameterElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 5025 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::SourceParameterElement::~SourceParameterElement () virtual
Destructor
Definition at line 5030 of file CCopasiXMLParser.cpp.
 {
   deleteCurrentHandler();
 }
Member Function Documentation
void CCopasiXMLParser::SourceParameterElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 5085 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   switch (mCurrentElement)
     {
       case SourceParameter:
         if (strcmp(pszName, "SourceParameter"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                          pszName, "SourceParameter", mParser.getCurrentLineNumber());
         mParser.popElementHandler();
         mCurrentElement = START_ELEMENT;
         /* Tell the parent element we are done. */
         mParser.onEndElement(pszName);
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   return;
 }
void CCopasiXMLParser::SourceParameterElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 5035 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CKeyFactory::get(), CModelEntity::getKey(), CCopasiParameter::getKey(), CCopasiObject::getObjectName(), CFunctionParameter::getType(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pFunctionVariable, CFunctionParameterMap::pUnmappedObject, CCopasiObject::setObjectName(), SCopasiXMLParserCommon::SourceParameterKeys, UNKNOWN_ELEMENT, and CFunctionParameter::VINT32.
 {
   mCurrentElement++; /* We should always be on the next element */
   const char * Reference;
   CCopasiObject * pObject;
   CCopasiParameter * pParameter;
   CModelEntity * pME;
   switch (mCurrentElement)
     {
       case SourceParameter:
         if (strcmp(pszName, "SourceParameter"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "SourceParameter", mParser.getCurrentLineNumber());
         Reference =
           mParser.getAttributeValue("reference", papszAttrs);
         pObject = mCommon.KeyMap.get(Reference);
         if ((pParameter = dynamic_cast< CCopasiParameter * >(pObject)))
           {
             // We need to assure that the parameter name for variables which are not
             // of type vector match.
             if (mCommon.pFunctionVariable->getType() < CFunctionParameter::VINT32)
               pParameter->setObjectName(mCommon.pFunctionVariable->getObjectName());
             mCommon.SourceParameterKeys[mCommon.pFunctionVariable->getObjectName()].push_back(pParameter->getKey());
           }
         else if ((pME = dynamic_cast<CModelEntity*>(pObject)))
           mCommon.SourceParameterKeys[mCommon.pFunctionVariable->getObjectName()].push_back(pME->getKey());
         else
           mCommon.SourceParameterKeys[mCommon.pFunctionVariable->getObjectName()].push_back(CFunctionParameterMap::pUnmappedObject->getKey());
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp