COPASI API: CQReferenceDM Class Reference
CQReferenceDM Class Reference
#include <CQReferenceDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQReferenceDM (CMIRIAMInfo *MIRIAMInfo, QObject *parent=0)
QVariant data (const QModelIndex &index, int role) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
bool removeRows (QModelIndexList rows, const QModelIndex &index=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
virtual Qt::ItemFlags flags (const QModelIndex &index) const
bool insertRow ()
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRow (int position)
Protected Member Functions
bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Protected Attributes
CMIRIAMInfo * mpMIRIAMInfo
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 31 of file CQReferenceDM.h.
Constructor & Destructor Documentation
CQReferenceDM::CQReferenceDM (CMIRIAMInfo * MIRIAMInfo, QObject * parent = 0)
Definition at line 25 of file CQReferenceDM.cpp.
References mpMIRIAMInfo.
     : CQBaseDataModel(parent)
 {
   mpMIRIAMInfo = MIRIAMInfo;
 }
Member Function Documentation
int CQReferenceDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 36 of file CQReferenceDM.cpp.
References TOTAL_COLS_REFERENCES.
 {
   return TOTAL_COLS_REFERENCES;
 }
QVariant CQReferenceDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 41 of file CQReferenceDM.cpp.
References COL_DESCRIPTION, COL_ID_REFERENCE, COL_RESOURCE_REFERENCE, COL_ROW_NUMBER, FROM_UTF8, CMIRIAMInfo::getReferences(), CQBaseDataModel::isDefaultRow(), mpMIRIAMInfo, and rowCount().
Referenced by removeRows().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       if (isDefaultRow(index))
         {
           if (index.column() == COL_RESOURCE_REFERENCE)
             return QVariant(QString("-- select --"));
           else if (index.column() == COL_ROW_NUMBER)
             return QVariant(QString(""));
           else
             return QVariant(QString(""));
         }
       else
         {
           switch (index.column())
             {
               case COL_ROW_NUMBER:
                 return QVariant(index.row() + 1);
               case COL_RESOURCE_REFERENCE:
                 return QVariant(QString(FROM_UTF8(mpMIRIAMInfo->getReferences()[index.row()]->getResource())));
               case COL_ID_REFERENCE:
                 return QVariant(QString(FROM_UTF8(mpMIRIAMInfo->getReferences()[index.row()]->getId())));
               case COL_DESCRIPTION:
                 return QVariant(QString(FROM_UTF8(mpMIRIAMInfo->getReferences()[index.row()]->getDescription())));
             }
         }
     }
   return QVariant();
 }
QVariant CQReferenceDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 79 of file CQReferenceDM.cpp.
References COL_DESCRIPTION, COL_ID_REFERENCE, COL_RESOURCE_REFERENCE, and COL_ROW_NUMBER.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
           case COL_RESOURCE_REFERENCE:
             return QVariant(QString("  Resource  "));
           case COL_ID_REFERENCE:
             return QVariant(QString("ID   "));
           case COL_DESCRIPTION:
             return QVariant(QString("Description"));
           default:
             return QVariant();
         }
     }
   else
     return QString("%1").arg(section + 1);
 }
bool CQReferenceDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 139 of file CQReferenceDM.cpp.
References ListViews::ADD, CMIRIAMInfo::createReference(), ListViews::MIRIAM, mpMIRIAMInfo, and CQBaseDataModel::notifyGUI().
 {
   beginInsertRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       mpMIRIAMInfo->createReference("");
     }
   endInsertRows();
   emit notifyGUI(ListViews::MIRIAM, ListViews::ADD, "");
   return true;
 }
bool CQReferenceDM::removeRows (QModelIndexList rows, const QModelIndex & index = QModelIndex())
Definition at line 172 of file CQReferenceDM.cpp.
References C_INVALID_INDEX, COL_ID_REFERENCE, COL_RESOURCE_REFERENCE, data(), CMIRIAMInfo::getReferences(), CQBaseDataModel::isDefaultRow(), mpMIRIAMInfo, CQMessageBox::question(), and CQBaseDataModel::removeRow().
Referenced by CQMiriamWidget::deleteSelectedReferences().
 {
   if (rows.isEmpty())
     return false;
 //Build the list of pointers to items to be deleted
 //before actually deleting any item.
   QList <CReference *> pReferences;
   QModelIndexList::const_iterator i;
   for (i = rows.begin(); i != rows.end(); ++i)
     {
       if (!isDefaultRow(*i) && mpMIRIAMInfo->getReferences()[(*i).row()])
         pReferences.append(mpMIRIAMInfo->getReferences()[(*i).row()]);
     }
   bool retVal = false, askEveryItem = true;
   QMessageBox::StandardButton choice = QMessageBox::NoToAll;
   QList <CReference *>::const_iterator j;
   for (j = pReferences.begin(); j != pReferences.end(); ++j)
     {
       CReference * pReference = *j;
       size_t delRow =
         mpMIRIAMInfo->getReferences().CCopasiVector< CReference >::getIndex(pReference);
       if (delRow != C_INVALID_INDEX)
         {
           if (askEveryItem)
             {
               QString resource = data(this->index((int) delRow, COL_RESOURCE_REFERENCE), Qt::DisplayRole).toString();
               QString Id = data(this->index((int) delRow, COL_ID_REFERENCE), Qt::DisplayRole).toString();
               QString msg = "Do you want to delete Reference '";
               if (!resource.isNull())
                 {
                   msg.append(resource);
                 }
               if (!Id.isNull())
                 {
                   msg.append(":");
                   msg.append(Id);
                 }
               msg.append("'?");
               choice = CQMessageBox::question(NULL, tr("Confirm Delete"), msg,
                                               QMessageBox::Yes | QMessageBox::YesToAll | QMessageBox::No | QMessageBox::NoToAll,
                                               QMessageBox::No);
             }
           if (choice == QMessageBox::NoToAll)
             {return retVal;}
           else if (choice == QMessageBox::Yes)
             {retVal = removeRow((int) delRow);}
           else if (choice == QMessageBox::YesToAll)
             {
               askEveryItem = false;
               retVal = removeRow((int) delRow);
             }
         }
     }
   return true;
 }
bool CQReferenceDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 154 of file CQReferenceDM.cpp.
References ListViews::DELETE, ListViews::MIRIAM, mpMIRIAMInfo, CQBaseDataModel::notifyGUI(), and CMIRIAMInfo::removeReference().
 {
   if (rows <= 0)
     return true;
   beginRemoveRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       mpMIRIAMInfo->removeReference(position);
     }
   endRemoveRows();
   emit notifyGUI(ListViews::MIRIAM, ListViews::DELETE, "");
   return true;
 }
int CQReferenceDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 32 of file CQReferenceDM.cpp.
References CMIRIAMInfo::getReferences(), mpMIRIAMInfo, and CCopasiVector< T >::size().
Referenced by data().
 {
   return (int) mpMIRIAMInfo->getReferences().size() + 1;
 }
bool CQReferenceDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 105 of file CQReferenceDM.cpp.
References ListViews::CHANGE, COL_DESCRIPTION, COL_ID_REFERENCE, COL_RESOURCE_REFERENCE, CMIRIAMInfo::getReferences(), CQBaseDataModel::insertRow(), CQBaseDataModel::isDefaultRow(), ListViews::MIRIAM, mpMIRIAMInfo, CQBaseDataModel::notifyGUI(), and TO_UTF8.
 {
   if (index.isValid() && role == Qt::EditRole)
     {
       if (isDefaultRow(index))
         {
           if (index.data() != value)
             insertRow();
           else
             return false;
         }
       switch (index.column())
         {
           case COL_RESOURCE_REFERENCE:
             mpMIRIAMInfo->getReferences()[index.row()]->setResource(TO_UTF8(value.toString()));
             break;
           case COL_ID_REFERENCE:
             mpMIRIAMInfo->getReferences()[index.row()]->setId(TO_UTF8(value.toString()));
             break;
           case COL_DESCRIPTION:
             mpMIRIAMInfo->getReferences()[index.row()]->setDescription(TO_UTF8(value.toString()));
             break;
         }
       emit dataChanged(index, index);
       emit notifyGUI(ListViews::MIRIAM, ListViews::CHANGE, "");
       return true;
     }
   return false;
 }
Member Data Documentation
CMIRIAMInfo* CQReferenceDM::mpMIRIAMInfo protected
Definition at line 49 of file CQReferenceDM.h.
Referenced by CQReferenceDM(), data(), insertRows(), removeRows(), rowCount(), and setData().
The documentation for this class was generated from the following files:
CQReferenceDM.h
CQReferenceDM.cpp