COPASI API: CExperimentSet Class Reference
CExperimentSet Class Reference
#include <CExperimentSet.h>
Public Member Functions
CExperiment * addExperiment (const CExperiment &experiment)
bool calculateStatistics ()
CExperimentSet (const CCopasiContainer *pParent, const std::string &name="Experiment Set")
CExperimentSet (const CExperimentSet &src, const CCopasiContainer *pParent=NULL)
CExperimentSet (const CCopasiParameterGroup &group, const CCopasiContainer *pParent=NULL)
bool compile (const std::vector< CCopasiContainer * > listOfContainer=CCopasiContainer::EmptyList)
virtual bool elevateChildren ()
void fixBuild55 ()
size_t getDataPointCount () const
const CMatrix< C_FLOAT64 > & getDependentData (const size_t &index) const
const CVector< C_FLOAT64 > & getDependentErrorMean () const
const CVector< C_FLOAT64 > & getDependentErrorMeanSD () const
const CVector< C_FLOAT64 > & getDependentObjectiveValues () const
const CVector< CCopasiObject * > & getDependentObjects () const
const CVector< C_FLOAT64 > & getDependentRMS () const
CExperiment * getExperiment (const size_t &index)
const CExperiment * getExperiment (const size_t &index) const
CExperiment * getExperiment (const std::string &name)
const CExperiment * getExperiment (const std::string &name) const
size_t getExperimentCount () const
const CCopasiTask::Type & getExperimentType (const size_t &index) const
std::vector< std::string > getFileNames () const
const CMatrix< C_FLOAT64 > & getIndependentData (const size_t &index) const
const size_t & getValidValueCount () const
bool hasDataForTaskType (const CCopasiTask::Type &type) const
size_t keyToIndex (const std::string &key) const
void removeExperiment (const size_t &index)
void sort ()
virtual ~CExperimentSet ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
virtual void print (std::ostream *ostream) const
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void initializeParameter ()
Private Attributes
CVector< size_t > mDependentDataCount
CVector< C_FLOAT64 > mDependentErrorMean
CVector< C_FLOAT64 > mDependentErrorMeanSD
CVector< C_FLOAT64 > mDependentObjectiveValues
CVector< CCopasiObject * > mDependentObjects
CVector< C_FLOAT64 > mDependentRMS
size_t mNonExperiments
std::vector< CExperiment * > * mpExperiments
size_t mValidValueCount
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 26 of file CExperimentSet.h.
Constructor & Destructor Documentation
CExperimentSet::CExperimentSet (const CCopasiContainer * pParent, const std::string & name = "Experiment Set")
Default constructor
Parameters
const CCopasiContainer * pParent
const std::string & name (default: Experiment Set)
Definition at line 30 of file CExperimentSet.cpp.
References initializeParameter().
                                                       :
   CCopasiParameterGroup(name, pParent, "CExperimentSet"),
   mpExperiments(NULL),
   mNonExperiments(0),
   mDependentObjects(0),
   mDependentObjectiveValues(0),
   mDependentRMS(0),
   mDependentErrorMean(0),
   mDependentErrorMeanSD(0),
   mDependentDataCount(0),
   mValidValueCount(0)
 {initializeParameter();}
CExperimentSet::CExperimentSet (const CExperimentSet & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CExperimentSet & src
const CCopasiContainer * pParent (default: src data model)
Definition at line 44 of file CExperimentSet.cpp.
References initializeParameter().
                                                                 :
   CCopasiParameterGroup(src, static_cast< const CCopasiContainer * >((pParent != NULL) ? pParent : src.getObjectDataModel())),
   mpExperiments(NULL),
   mNonExperiments(0),
   mDependentObjects(0),
   mDependentObjectiveValues(0),
   mDependentRMS(0),
   mDependentErrorMean(0),
   mDependentErrorMeanSD(0),
   mDependentDataCount(0),
   mValidValueCount(0)
 {initializeParameter();}
CExperimentSet::CExperimentSet (const CCopasiParameterGroup & group, const CCopasiContainer * pParent = NULL)
Specific constructor used for reading COPASI files
Parameters
const CCopasiParameterGroup & group
const CCopasiContainer * pParent (default: group data model)
Definition at line 58 of file CExperimentSet.cpp.
References initializeParameter().
                                                                 :
   CCopasiParameterGroup(group, static_cast< const CCopasiContainer * >((pParent != NULL) ? pParent : group.getObjectDataModel())),
   mpExperiments(NULL),
   mNonExperiments(0),
   mDependentObjects(0),
   mDependentObjectiveValues(0),
   mDependentRMS(0),
   mDependentErrorMean(0),
   mDependentErrorMeanSD(0),
   mDependentDataCount(0),
   mValidValueCount(0)
 {initializeParameter();}
CExperimentSet::~CExperimentSet () virtual
Destructor
Definition at line 72 of file CExperimentSet.cpp.
 {}
Member Function Documentation
CExperiment * CExperimentSet::addExperiment (const CExperiment & experiment)
Add an experiment
Returns
CExperiment * experiment
Definition at line 327 of file CExperimentSet.cpp.
References CCopasiParameterGroup::addParameter(), CCopasiObject::getObjectName(), CCopasiParameterGroup::getParameter(), CCopasiObject::setObjectName(), sort(), and StringPrint().
Referenced by CQFittingWidget::saveTask(), CQExperimentData::slotExperimentAdd(), and CQExperimentData::slotOK().
 {
   // We need to make sure that the experiment name is unique.
   std::string name = experiment.getObjectName();
   int i = 0;
   while (getParameter(name))
     {
       i++;
       name = StringPrint("%s_%d", experiment.getObjectName().c_str(), i);
     }
   CExperiment * pExperiment = new CExperiment(experiment);
   pExperiment->setObjectName(name);
   addParameter(pExperiment);
   sort();
   return pExperiment;
 }
bool CExperimentSet::calculateStatistics ()
Calculate statistics across all experiments.
Returns
bool success
Definition at line 177 of file CExperimentSet.cpp.
References COutputInterface::AFTER, CVectorCore< CType >::array(), C_FLOAT64, CCopasiObject::getObjectAncestor(), max, mDependentDataCount, mDependentErrorMean, mDependentErrorMeanSD, mDependentObjectiveValues, mDependentObjects, mDependentRMS, mNonExperiments, mpExperiments, mValidValueCount, CCopasiTask::output(), CVector< CType >::resize(), CVectorCore< CType >::size(), and CCopasiTask::timeCourse.
Referenced by CFitProblem::calculateStatistics().
 {
   mDependentObjectiveValues.resize(mDependentObjects.size());
   mDependentObjectiveValues = 0.0;
   mDependentRMS.resize(mDependentObjects.size());
   mDependentRMS = 0.0;
   mDependentErrorMean.resize(mDependentObjects.size());
   mDependentErrorMean = 0.0;
   mDependentErrorMeanSD.resize(mDependentObjects.size());
   mDependentErrorMeanSD = 0.0;
   mDependentDataCount.resize(mDependentObjects.size());
   mDependentDataCount = 0;
   mValidValueCount = 0;
   // calculate the per experiment and per dependent value statistics.
   std::vector< CExperiment * >::iterator it = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::iterator end = mpExperiments->end();
   size_t i, Count;
   C_FLOAT64 Tmp;
   for (; it != end; ++it)
     {
       (*it)->calculateStatistics();
       CCopasiObject *const* ppObject = mDependentObjects.array();
       CCopasiObject *const* ppEnd = ppObject + mDependentObjects.size();
       for (i = 0; ppObject != ppEnd; ++ppObject, ++i)
         {
           Count = (*it)->getColumnValidValueCount(*ppObject);
           if (Count)
             {
               mDependentObjectiveValues[i] += (*it)->getObjectiveValue(*ppObject);
               Tmp = (*it)->getRMS(*ppObject);
               mDependentRMS[i] += Tmp * Tmp * Count;
               mDependentErrorMean[i] += (*it)->getErrorSum(*ppObject);
               mDependentDataCount[i] += Count;
               mValidValueCount += Count;
             }
         }
     }
   size_t imax = mDependentObjects.size();
   for (i = 0; i != imax; i++)
     {
       Count = mDependentDataCount[i];
       if (Count)
         {
           mDependentRMS[i] = sqrt(mDependentRMS[i] / Count);
           mDependentErrorMean[i] /= Count;
         }
       else
         {
           mDependentRMS[i] = std::numeric_limits<C_FLOAT64>::quiet_NaN();
           mDependentErrorMean[i] = std::numeric_limits<C_FLOAT64>::quiet_NaN();
         }
     }
   it = mpExperiments->begin() + mNonExperiments;
   // We need to loop again to calculate the std. deviation.
   for (; it != end; ++it)  //over experiments
     {
       CCopasiObject *const* ppObject = mDependentObjects.array();
       CCopasiObject *const* ppEnd = ppObject + mDependentObjects.size();
       for (i = 0; ppObject != ppEnd; ++ppObject, ++i)
         {
           Count = (*it)->getColumnValidValueCount(*ppObject);
           if (Count)
             mDependentErrorMeanSD[i] +=
               (*it)->getErrorMeanSD(*ppObject, mDependentErrorMean[i]);
         }
     }
   for (i = 0; i != imax; i++)
     {
       Count = mDependentDataCount[i];
       if (Count)
         mDependentErrorMeanSD[i] = sqrt(mDependentErrorMeanSD[i] / Count);
       else
         mDependentErrorMeanSD[i] = std::numeric_limits<C_FLOAT64>::quiet_NaN();
     }
   // This is the time to call the output handler to plot the fitted points.
   for (it = mpExperiments->begin() + mNonExperiments, imax = 0; it != end; ++it)
     imax = std::max(imax, (*it)->getDependentData().numRows());
   CCopasiTask * pParentTask = dynamic_cast< CCopasiTask *>(getObjectAncestor("Task"));
   assert(pParentTask != NULL);
   for (i = 0; i < imax; i++)
     {
       for (it = mpExperiments->begin() + mNonExperiments; it != end; ++it)
         (*it)->updateFittedPointValues(i, (*it)->getExperimentType() != CCopasiTask::timeCourse); //false means without simulated data
       pParentTask->output(COutputInterface::AFTER);
     }
   //now the extended time series
   for (it = mpExperiments->begin() + mNonExperiments, imax = 0; it != end; ++it)
     imax = std::max(imax, (*it)->extendedTimeSeriesSize());
   for (i = 0; i < imax; i++)
     {
       for (it = mpExperiments->begin() + mNonExperiments; it != end; ++it)
         {
           if ((*it)->getExperimentType() == CCopasiTask::timeCourse)
             {
               (*it)->updateFittedPointValuesFromExtendedTimeSeries(i);
             }
         }
       pParentTask->output(COutputInterface::AFTER);
     }
   return true;
 }
bool CExperimentSet::compile (const std::vector< CCopasiContainer * > listOfContainer = CCopasiContainer::EmptyList)
Compile the experiment set. This function must be called before any evaluations can be performed.
Parameters
const std::vector< CCopasiContainer * > listOfContainer
Returns
bool success
Definition at line 96 of file CExperimentSet.cpp.
References CVectorCore< CType >::array(), CCopasiMessage::ERROR, CLocaleString::fromUtf8(), MCFitting, mDependentDataCount, mDependentErrorMean, mDependentErrorMeanSD, mDependentObjectiveValues, mDependentObjects, mDependentRMS, mNonExperiments, mpExperiments, CVector< CType >::resize(), CVectorCore< CType >::size(), and sort().
Referenced by CFitProblem::initialize().
 {
   bool success = true;
   // First we need to sort the experiments so that we can make use of continued
   // file reading.
   sort();
   std::set< CCopasiObject * > DependentObjects;
   std::ifstream in;
   std::string CurrentFileName("");
   size_t CurrentLineNumber = 1;
   std::vector< CExperiment * >::iterator it = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::iterator end = mpExperiments->end();
   for (; it != end; ++it)
     {
       if (CurrentFileName != (*it)->getFileName())
         {
           CurrentFileName = (*it)->getFileName();
           CurrentLineNumber = 1;
           if (in.is_open())
             {
               in.close();
               in.clear();
             }
           in.open(CLocaleString::fromUtf8(CurrentFileName).c_str(), std::ios::binary);
           if (in.fail())
             {
               CCopasiMessage(CCopasiMessage::ERROR, MCFitting + 8, CurrentFileName.c_str());
               return false; // File can not be opened.
             }
         }
       if (!(*it)->read(in, CurrentLineNumber)) return false;
       if (!(*it)->compile(listOfContainer)) return false;
       const std::map< CCopasiObject *, size_t > & ExpDependentObjects
         = (*it)->getDependentObjects();
       std::map< CCopasiObject *, size_t >::const_iterator itObject
         = ExpDependentObjects.begin();
       std::map< CCopasiObject *, size_t >::const_iterator endObject
         = ExpDependentObjects.end();
       for (; itObject != endObject; ++itObject)
         DependentObjects.insert(itObject->first);
     }
   mDependentObjects.resize(DependentObjects.size());
   CCopasiObject ** ppInsert = mDependentObjects.array();
   std::set< CCopasiObject * >::const_iterator itObject = DependentObjects.begin();
   std::set< CCopasiObject * >::const_iterator endObject = DependentObjects.end();
   for (; itObject != endObject; ++itObject, ++ppInsert)
     *ppInsert = *itObject;
   // Allocation and initialization of statistical information
   mDependentObjectiveValues.resize(mDependentObjects.size());
   mDependentObjectiveValues = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   mDependentRMS.resize(mDependentObjects.size());
   mDependentRMS = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   mDependentErrorMean.resize(mDependentObjects.size());
   mDependentErrorMean = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   mDependentErrorMeanSD.resize(mDependentObjects.size());
   mDependentErrorMeanSD = std::numeric_limits<C_FLOAT64>::quiet_NaN();
   mDependentDataCount.resize(mDependentObjects.size());
   mDependentDataCount = std::numeric_limits<size_t>::quiet_NaN();
   return success;
 }
bool CExperimentSet::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 77 of file CExperimentSet.cpp.
References mpExperiments, CCopasiParameter::mValue, CCopasiParameter::Value::pGROUP, CCopasiParameter::Value::pVOID, and sort().
Referenced by initializeParameter(), and CCrossValidationSet::initializeParameter().
 {
   index_iterator it = mValue.pGROUP->begin();
   index_iterator end = mValue.pGROUP->end();
   for (; it != end; ++it)
     {
       if (dynamic_cast< CCopasiParameterGroup * >(*it) == NULL) continue;
       if (!elevate<CExperiment, CCopasiParameterGroup>(*it)) return false;
     }
   mpExperiments = static_cast<std::vector<CExperiment * > * >(mValue.pVOID);
   sort();
   return true;
 }
void CExperimentSet::fixBuild55 ()
Fix files written with Version 4.10.55, which wrote the square root of user defined weights for the parameter fitting task
Definition at line 466 of file CExperimentSet.cpp.
References mNonExperiments, and mpExperiments.
Referenced by CFitProblem::fixBuild55().
 {
   std::vector< CExperiment * >::iterator it = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::iterator end = mpExperiments->end();
   for (; it != end; ++it)
     {
       (*it)->fixBuild55();
     }
   return;
 }
size_t CExperimentSet::getDataPointCount () const
Retrieve the number of data points of all experiments combined.
Returns
size_t dataPointCount
Definition at line 449 of file CExperimentSet.cpp.
References mNonExperiments, and mpExperiments.
Referenced by CFitProblem::calculateCrossValidation(), CFitProblem::initialize(), and CFitProblem::setResidualsRequired().
 {
   size_t Count = 0;
   std::vector< CExperiment * >::iterator it = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::iterator end = mpExperiments->end();
   for (; it != end; ++it)
     Count += (*it)->getDependentData().numRows() * (*it)->getDependentData().numCols();
   return Count;
 }
const CMatrix< C_FLOAT64 > & CExperimentSet::getDependentData (const size_t & index) const
Retrieve the dependent data of the indexed experiment.
Parameters
const size_t & index,
Returns
const CMatrix< C_FLOAT64 > & dependentData
Definition at line 386 of file CExperimentSet.cpp.
References CExperiment::getDependentData(), and getExperiment().
 {return getExperiment(index)->getDependentData();}
const CVector< C_FLOAT64 > & CExperimentSet::getDependentErrorMean () const
Retrieve all dependent data error mean values.
Returns
const CVector< C_FLOAT64 > & dependentErrorMean
Definition at line 318 of file CExperimentSet.cpp.
References mDependentErrorMean.
Referenced by CQFittingResult::enterProtected().
 {return mDependentErrorMean;}
const CVector< C_FLOAT64 > & CExperimentSet::getDependentErrorMeanSD () const
Retrieve all dependent data error mean std. deviations.
Returns
const CVector< C_FLOAT64 > & dependentErrorMeanSD
Definition at line 321 of file CExperimentSet.cpp.
References mDependentErrorMeanSD.
Referenced by CQFittingResult::enterProtected().
 {return mDependentErrorMeanSD;}
const CVector< C_FLOAT64 > & CExperimentSet::getDependentObjectiveValues () const
Retrieve all dependent data objective values.
Returns
const CVector< C_FLOAT64 > & dependentObjectiveValues
Definition at line 312 of file CExperimentSet.cpp.
References mDependentObjectiveValues.
Referenced by CQFittingResult::enterProtected().
 {return mDependentObjectiveValues;}
const CVector< CCopasiObject * > & CExperimentSet::getDependentObjects () const
Retrieve the list of dependent data objects
Returns
const std::vector< CCopasiObject * > & dependentObjects
Definition at line 309 of file CExperimentSet.cpp.
References mDependentObjects.
Referenced by CQFittingResult::enterProtected().
 {return mDependentObjects;}
const CVector< C_FLOAT64 > & CExperimentSet::getDependentRMS () const
Retrieve all dependent data objective values.
Returns
const CVector< C_FLOAT64 > & dependentRMS
Definition at line 315 of file CExperimentSet.cpp.
References mDependentRMS.
Referenced by CQFittingResult::enterProtected().
 {return mDependentRMS;}
CExperiment * CExperimentSet::getExperiment (const size_t & index)
Retrieve the indexed experiment
Parameters
const size_t & index,
Returns
CExperiment * experiment
Definition at line 352 of file CExperimentSet.cpp.
References mNonExperiments, and mpExperiments.
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), COutputAssistant::createDefaultOutput(), CFitProblem::elevateChildren(), CQFittingResult::enterProtected(), getDependentData(), getExperimentType(), getIndependentData(), CFitProblem::initialize(), CQExperimentData::isLikePreviousExperiment(), keyToIndex(), CQExperimentSelection::load(), CQExperimentData::load(), CQExperimentData::loadExperiment(), CQFittingWidget::loadTask(), CFitProblem::printResult(), CQExperimentData::saveExperiment(), CQFittingWidget::saveTask(), CQExperimentData::slotCheckNormalizeWeightsPerExperiment(), CQExperimentData::slotCheckTo(), CQExperimentData::slotExperimentDelete(), CQExperimentData::slotFileDelete(), CQExperimentData::slotOK(), CQExperimentData::slotWeightMethod(), and CExperimentFileInfo::sync().
 {return (*mpExperiments)[index + mNonExperiments];}
const CExperiment * CExperimentSet::getExperiment (const size_t & index) const
Retrieve the indexed experiment
Parameters
const size_t & index,
Returns
const CExperiment * experiment
Definition at line 355 of file CExperimentSet.cpp.
References mNonExperiments, and mpExperiments.
 {return (*mpExperiments)[index + mNonExperiments];}
CExperiment * CExperimentSet::getExperiment (const std::string & name)
Retrieve the indexed experiment
Parameters
const std::string & name,
Returns
CExperiment * experiment
Definition at line 358 of file CExperimentSet.cpp.
References CCopasiParameterGroup::getGroup().
 {return static_cast<CExperiment *>(getGroup(name));}
const CExperiment * CExperimentSet::getExperiment (const std::string & name) const
Retrieve the indexed experiment
Parameters
const std::string & name,
Returns
const CExperiment * experiment
Definition at line 361 of file CExperimentSet.cpp.
References CCopasiParameterGroup::getGroup().
 {return static_cast<const CExperiment *>(getGroup(name));}
size_t CExperimentSet::getExperimentCount () const
Retrieve the number of the experiments in the set
Returns
size_t experimentCount
Definition at line 324 of file CExperimentSet.cpp.
References mNonExperiments, and CCopasiParameterGroup::size().
Referenced by CFitProblem::calculate(), CFitProblem::calculateCrossValidation(), COutputAssistant::createDefaultOutput(), CQFittingResult::enterProtected(), CFitProblem::initialize(), CQFittingResultTab1::load(), CQExperimentSelection::load(), CQExperimentData::load(), CQFittingWidget::loadTask(), CFitProblem::printResult(), CQFittingWidget::saveTask(), CQFittingItemWidget::setCrossValidationSet(), CFitProblem::setSolution(), CQExperimentData::slotFileDelete(), CQExperimentData::slotOK(), and CExperimentFileInfo::sync().
 {return size() - mNonExperiments;}
const CCopasiTask::Type & CExperimentSet::getExperimentType (const size_t & index) const
Retrieve the indexed experiment type
Parameters
const size_t & index,
Returns
const CCopasiTasK::Type & experimentType
Definition at line 380 of file CExperimentSet.cpp.
References getExperiment(), and CExperiment::getExperimentType().
 {return getExperiment(index)->getExperimentType();}
std::vector< std::string > CExperimentSet::getFileNames () const
Retrieve the list of file names
Returns
std::vector< std::string > fileNames
Definition at line 431 of file CExperimentSet.cpp.
References mNonExperiments, and mpExperiments.
Referenced by CQExperimentData::load().
 {
   std::vector< std::string > List;
   std::string currentFile = "";
   std::vector< CExperiment * >::iterator it = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::iterator end = mpExperiments->end();
   for (; it != end; ++it)
     if (currentFile != (*it)->getFileName())
       {
         currentFile = (*it)->getFileName();
         List.push_back(currentFile);
       }
   return List;
 }
const CMatrix< C_FLOAT64 > & CExperimentSet::getIndependentData (const size_t & index) const
Retrieve the independent data of the indexed experiment.
Parameters
const size_t & index,
Returns
const CMatrix< C_FLOAT64 > & independentData
Definition at line 383 of file CExperimentSet.cpp.
References getExperiment(), and CExperiment::getIndependentData().
 {return getExperiment(index)->getIndependentData();}
const size_t & CExperimentSet::getValidValueCount () const
Retrieve the count of valid data points of all experiments combined.
Returns
size_t count
Definition at line 461 of file CExperimentSet.cpp.
References mValidValueCount.
Referenced by CFitProblem::calculateStatistics().
 {
   return mValidValueCount;
 }
bool CExperimentSet::hasDataForTaskType (const CCopasiTask::Type & type) const
Check whether the set contains data for the the given task type
Parameters
const CCopasiTask::Type & type
Returns
bool hasDataForTaskType
Definition at line 364 of file CExperimentSet.cpp.
References mNonExperiments, and mpExperiments.
Referenced by CFitProblem::initialize().
 {
   std::vector< CExperiment * >::const_iterator it = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::const_iterator end = mpExperiments->end();
   for (; it != end; ++it)
     {
       if ((*it)->getExperimentType() == type)
         {
           return true;
         }
     }
   return false;
 }
void CExperimentSet::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 74 of file CExperimentSet.cpp.
References elevateChildren().
Referenced by CExperimentSet().
 {elevateChildren();}
size_t CExperimentSet::keyToIndex (const std::string & key) const
Convert an experiment key to an index
Parameters
const std::string & key
Returns
size_t index
Definition at line 389 of file CExperimentSet.cpp.
References C_INVALID_INDEX, CKeyFactory::get(), getExperiment(), CCopasiRootContainer::getKeyFactory(), and CCopasiParameterGroup::size().
Referenced by CFitProblem::initialize(), CQExperimentData::isLikePreviousExperiment(), CQExperimentData::loadExperiment(), CQExperimentData::saveExperiment(), CQExperimentData::slotCheckNormalizeWeightsPerExperiment(), CQExperimentData::slotCheckTo(), CQExperimentData::slotExperimentDelete(), and CQExperimentData::slotWeightMethod().
 {
   const CExperiment * pExp = dynamic_cast<const CExperiment *>(CCopasiRootContainer::getKeyFactory()->get(key));
   if (!pExp) return C_INVALID_INDEX;
   size_t i, imax = size();
   for (i = 0; i < imax; i++)
     if (pExp == getExperiment(i)) return i;
   return C_INVALID_INDEX;
 }
void CExperimentSet::removeExperiment (const size_t & index)
Remove an experiment from the set
Parameters
const size_t & index
Definition at line 349 of file CExperimentSet.cpp.
References mNonExperiments, and CCopasiParameterGroup::removeParameter().
Referenced by CQFittingWidget::saveTask(), CQExperimentData::slotExperimentDelete(), CQExperimentData::slotFileDelete(), and CQExperimentData::slotOK().
 {removeParameter(index + mNonExperiments);}
void CExperimentSet::sort ()
Sort the experiments in the set
Definition at line 403 of file CExperimentSet.cpp.
References CCopasiParameterGroup::beginIndex(), CExperiment::compare(), CCopasiParameterGroup::endIndex(), mNonExperiments, mpExperiments, and CCopasiParameterGroup::swap().
Referenced by addExperiment(), compile(), elevateChildren(), and CExperimentFileInfo::sync().
 {
   // First we make sure that all experiments are at the end of the group
   index_iterator it = beginIndex();
   index_iterator end = endIndex();
   index_iterator swapTarget = beginIndex();
   mNonExperiments = 0;
   for (; it != end; ++it)
     if (dynamic_cast< CExperiment * >(*it) == NULL)
       {
         if (it != swapTarget)
           swap(it, swapTarget);
         swapTarget++;
         mNonExperiments++;
       }
   // Now sort the experiments
   std::vector< CExperiment * >::iterator startSort = mpExperiments->begin() + mNonExperiments;
   std::vector< CExperiment * >::iterator endSort = mpExperiments->end();
   std::sort(startSort, endSort, &CExperiment::compare);
   return;
 }
Member Data Documentation
CVector< size_t > CExperimentSet::mDependentDataCount private
A list of the number of data points for each dependent object;
Definition at line 268 of file CExperimentSet.h.
Referenced by calculateStatistics(), and compile().
CVector< C_FLOAT64 > CExperimentSet::mDependentErrorMean private
A list of all dependent data error mean values;
Definition at line 258 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), and getDependentErrorMean().
CVector< C_FLOAT64 > CExperimentSet::mDependentErrorMeanSD private
A list of all dependent data error mean std. deviations;
Definition at line 263 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), and getDependentErrorMeanSD().
CVector< C_FLOAT64 > CExperimentSet::mDependentObjectiveValues private
A list of all dependent data objective values;
Definition at line 248 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), and getDependentObjectiveValues().
CVector< CCopasiObject * > CExperimentSet::mDependentObjects private
A set of all dependent data objects;
Definition at line 243 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), and getDependentObjects().
CVector< C_FLOAT64 > CExperimentSet::mDependentRMS private
A list of all dependent data objective values;
Definition at line 253 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), and getDependentRMS().
size_t CExperimentSet::mNonExperiments private
The number of parameters which are not of type CExperiment
Definition at line 238 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), fixBuild55(), getDataPointCount(), getExperiment(), getExperimentCount(), getFileNames(), hasDataForTaskType(), removeExperiment(), and sort().
std::vector< CExperiment * >* CExperimentSet::mpExperiments private
This is realized a CCopasiParameter type GROUP
Definition at line 233 of file CExperimentSet.h.
Referenced by calculateStatistics(), compile(), elevateChildren(), fixBuild55(), getDataPointCount(), getExperiment(), getFileNames(), hasDataForTaskType(), and sort().
size_t CExperimentSet::mValidValueCount private
The total count of valid data values.
Definition at line 273 of file CExperimentSet.h.
Referenced by calculateStatistics(), and getValidValueCount().
The documentation for this class was generated from the following files:
CExperimentSet.h
CExperimentSet.cpp