COPASI API: CQMathMatrixWidget Class Reference
CQMathMatrixWidget Class Reference
#include <CQMathMatrixWidget.h>
Public Member Functions
CQMathMatrixWidget (QWidget *parent=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQMathMatrixWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
void clearArrays ()
virtual bool enterProtected ()
void loadMatrices ()
Protected Attributes
QLabel * mLabelTitle
const CArrayAnnotation * mpArrayAnn1
const CArrayAnnotation * mpArrayAnn2
const CArrayAnnotation * mpArrayAnn3
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Additional Inherited Members
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 33 of file CQMathMatrixWidget.h.
Constructor & Destructor Documentation
CQMathMatrixWidget::CQMathMatrixWidget (QWidget * parent = 0)
Constructs a CQMathMatrixWidget which is a child of 'parent', with the name 'name' and widget flags set to 'f'.
Definition at line 37 of file CQMathMatrixWidget.cpp.
References CColorScaleSimple::setMinMax().
     : CopasiWidget(parent)
 {
   setupUi(this);
   CColorScaleSimple * tcs = new CColorScaleSimple();
   mpArrayWidget1->setColorCoding(tcs);
   tcs->setMinMax(-1.5, 1.5);
   mpArrayWidget1->setColorScalingAutomatic(false);
   tcs = new CColorScaleSimple();
   mpArrayWidget2->setColorCoding(tcs);
   tcs->setMinMax(-1.5, 1.5);
   mpArrayWidget2->setColorScalingAutomatic(false);
   tcs = new CColorScaleSimple();
   mpArrayWidget3->setColorCoding(tcs);
   tcs->setMinMax(-1.5, 1.5);
   mpArrayWidget3->setColorScalingAutomatic(false);
 }
CQMathMatrixWidget::~CQMathMatrixWidget ()
Definition at line 61 of file CQMathMatrixWidget.cpp.
 {}
Member Function Documentation
void CQMathMatrixWidget::clearArrays () protected
Definition at line 85 of file CQMathMatrixWidget.cpp.
Referenced by update().
 {
   mpArrayWidget1->setArrayAnnotation(NULL);
   mpArrayWidget2->setArrayAnnotation(NULL);
   mpArrayWidget3->setArrayAnnotation(NULL);
 }
bool CQMathMatrixWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 106 of file CQMathMatrixWidget.cpp.
References loadMatrices().
 {
   loadMatrices();
   return true;
 }
bool CQMathMatrixWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 101 of file CQMathMatrixWidget.cpp.
 {
   return true;
 }
void CQMathMatrixWidget::loadMatrices () protected
Definition at line 64 of file CQMathMatrixWidget.cpp.
References CCopasiRootContainer::getDatamodelList(), and CCopasiContainer::getObject().
Referenced by enterProtected().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   const CModel* pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   const CArrayAnnotation * tmp;
   tmp = dynamic_cast<const CArrayAnnotation *>
         (pModel->getObject(CCopasiObjectName("Array=Stoichiometry(ann)")));
   mpArrayWidget1->setArrayAnnotation(tmp);
   tmp = dynamic_cast<const CArrayAnnotation *>
         (pModel->getObject(CCopasiObjectName("Array=Reduced stoichiometry(ann)")));
   mpArrayWidget2->setArrayAnnotation(tmp);
   tmp = dynamic_cast<const CArrayAnnotation *>
         (pModel->getObject(CCopasiObjectName("Array=Link matrix(ann)")));
   mpArrayWidget3->setArrayAnnotation(tmp);
 }
bool CQMathMatrixWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 94 of file CQMathMatrixWidget.cpp.
References clearArrays().
 {
   clearArrays();
   return true;
 }
Member Data Documentation
QLabel* CQMathMatrixWidget::mLabelTitle protected
Definition at line 51 of file CQMathMatrixWidget.h.
const CArrayAnnotation* CQMathMatrixWidget::mpArrayAnn1 protected
Definition at line 53 of file CQMathMatrixWidget.h.
const CArrayAnnotation* CQMathMatrixWidget::mpArrayAnn2 protected
Definition at line 54 of file CQMathMatrixWidget.h.
const CArrayAnnotation* CQMathMatrixWidget::mpArrayAnn3 protected
Definition at line 55 of file CQMathMatrixWidget.h.
The documentation for this class was generated from the following files:
CQMathMatrixWidget.h
CQMathMatrixWidget.cpp