COPASI API: test000084 Class Reference
test000084 Class Reference
#include <test000084.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_import_compartment_units_1 ()
void test_import_compartment_units_10 ()
void test_import_compartment_units_11 ()
void test_import_compartment_units_12 ()
void test_import_compartment_units_13 ()
void test_import_compartment_units_14 ()
void test_import_compartment_units_15 ()
void test_import_compartment_units_16 ()
void test_import_compartment_units_17 ()
void test_import_compartment_units_18 ()
void test_import_compartment_units_19 ()
void test_import_compartment_units_2 ()
void test_import_compartment_units_20 ()
void test_import_compartment_units_21 ()
void test_import_compartment_units_3 ()
void test_import_compartment_units_4 ()
void test_import_compartment_units_5 ()
void test_import_compartment_units_6 ()
void test_import_compartment_units_7 ()
void test_import_compartment_units_8 ()
void test_import_compartment_units_9 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING10
static const char * MODEL_STRING11
static const char * MODEL_STRING12
static const char * MODEL_STRING13
static const char * MODEL_STRING14
static const char * MODEL_STRING15
static const char * MODEL_STRING16
static const char * MODEL_STRING17
static const char * MODEL_STRING18
static const char * MODEL_STRING19
static const char * MODEL_STRING2
static const char * MODEL_STRING20
static const char * MODEL_STRING21
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static const char * MODEL_STRING7
static const char * MODEL_STRING8
static const char * MODEL_STRING9
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_compartment_units_1)
CPPUNIT_TEST (test_import_compartment_units_2)
CPPUNIT_TEST (test_import_compartment_units_3)
CPPUNIT_TEST (test_import_compartment_units_4)
CPPUNIT_TEST (test_import_compartment_units_5)
CPPUNIT_TEST (test_import_compartment_units_6)
CPPUNIT_TEST (test_import_compartment_units_7)
CPPUNIT_TEST (test_import_compartment_units_8)
CPPUNIT_TEST (test_import_compartment_units_9)
CPPUNIT_TEST (test_import_compartment_units_10)
CPPUNIT_TEST (test_import_compartment_units_11)
CPPUNIT_TEST (test_import_compartment_units_12)
CPPUNIT_TEST (test_import_compartment_units_13)
CPPUNIT_TEST (test_import_compartment_units_14)
CPPUNIT_TEST (test_import_compartment_units_15)
CPPUNIT_TEST (test_import_compartment_units_16)
CPPUNIT_TEST (test_import_compartment_units_17)
CPPUNIT_TEST (test_import_compartment_units_18)
CPPUNIT_TEST (test_import_compartment_units_19)
CPPUNIT_TEST (test_import_compartment_units_20)
CPPUNIT_TEST (test_import_compartment_units_21)
CPPUNIT_TEST_SUITE (test000084)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 28 of file test000084.h.
Member Function Documentation
test000084::CPPUNIT_TEST (test_import_compartment_units_1) private
test000084::CPPUNIT_TEST (test_import_compartment_units_2) private
test000084::CPPUNIT_TEST (test_import_compartment_units_3) private
test000084::CPPUNIT_TEST (test_import_compartment_units_4) private
test000084::CPPUNIT_TEST (test_import_compartment_units_5) private
test000084::CPPUNIT_TEST (test_import_compartment_units_6) private
test000084::CPPUNIT_TEST (test_import_compartment_units_7) private
test000084::CPPUNIT_TEST (test_import_compartment_units_8) private
test000084::CPPUNIT_TEST (test_import_compartment_units_9) private
test000084::CPPUNIT_TEST (test_import_compartment_units_10) private
test000084::CPPUNIT_TEST (test_import_compartment_units_11) private
test000084::CPPUNIT_TEST (test_import_compartment_units_12) private
test000084::CPPUNIT_TEST (test_import_compartment_units_13) private
test000084::CPPUNIT_TEST (test_import_compartment_units_14) private
test000084::CPPUNIT_TEST (test_import_compartment_units_15) private
test000084::CPPUNIT_TEST (test_import_compartment_units_16) private
test000084::CPPUNIT_TEST (test_import_compartment_units_17) private
test000084::CPPUNIT_TEST (test_import_compartment_units_18) private
test000084::CPPUNIT_TEST (test_import_compartment_units_19) private
test000084::CPPUNIT_TEST (test_import_compartment_units_20) private
test000084::CPPUNIT_TEST (test_import_compartment_units_21) private
test000084::CPPUNIT_TEST_SUITE (test000084) private
test000084::CPPUNIT_TEST_SUITE_END () private
void test000084::setUp ()
Definition at line 36 of file test000084.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000084::tearDown ()
Definition at line 44 of file test000084.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000084::test_import_compartment_units_1 ()
Definition at line 49 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING1, CModel::nm2, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::nm2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // make sure there is no message about units not being consistent
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 24);
       // make sure all units were imported
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 55);
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 66);
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 79);
       ++i;
     }
 }
void test000084::test_import_compartment_units_10 ()
Definition at line 464 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING10, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING10));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_11 ()
Definition at line 516 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING11, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING11));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_12 ()
Definition at line 568 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING12, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING12));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_13 ()
Definition at line 620 of file test000084.cpp.
References CModel::dimensionlessArea, CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING13, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING13));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::dimensionlessArea);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // make sure there is no message about units not being consistent
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 24);
       // make sure all units were imported
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 55);
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 66);
       CPPUNIT_ASSERT(message.getNumber() != MCSBML + 79);
       ++i;
     }
 }
void test000084::test_import_compartment_units_14 ()
Definition at line 644 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING14, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING14));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_15 ()
Definition at line 696 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING15, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING15));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_16 ()
Definition at line 748 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING16, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING16));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_17 ()
Definition at line 800 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING17, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING17));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_18 ()
Definition at line 852 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING18, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING18));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 2);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_19 ()
Definition at line 904 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING19, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING19));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 2);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_2 ()
Definition at line 73 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING2, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   unsigned int i = 0, iMax = CCopasiMessage::size();
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // make sure there is a message about the unit not being recognized by
       // COPASI since the scale is off
       if (message.getNumber() == MCSBML + 66)
         {
           break;
         }
       ++i;
     }
   CPPUNIT_ASSERT(i != iMax);
 }
void test000084::test_import_compartment_units_20 ()
Definition at line 956 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING20, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING20));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 2);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 1);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_21 ()
Definition at line 1008 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING21, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING21));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 2);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 1);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_3 ()
Definition at line 100 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING3, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING3));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 1);
 }
void test000084::test_import_compartment_units_4 ()
Definition at line 152 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, CModel::mm2, MODEL_STRING4, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING4));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::mm2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_5 ()
Definition at line 204 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING5, CModel::nm2, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING5));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::nm2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_6 ()
Definition at line 256 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING6, CModel::nm2, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING6));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::nm2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 1);
 }
void test000084::test_import_compartment_units_7 ()
Definition at line 308 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), MCSBML, MODEL_STRING7, CModel::nm2, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING7));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::nm2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_8 ()
Definition at line 360 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING8, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING8));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found66 = 0;
   unsigned int found79 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 0);
   CPPUNIT_ASSERT(found66 == 0);
 }
void test000084::test_import_compartment_units_9 ()
Definition at line 412 of file test000084.cpp.
References CCopasiMessage::getLastMessage(), CCopasiDataModel::getModel(), CCopasiMessage::getNumber(), CCopasiDataModel::importSBMLFromString(), CModel::m2, MCSBML, MODEL_STRING9, pCOPASIDATAMODEL, and CCopasiMessage::size().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING9));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getAreaUnitEnum() == CModel::m2);
   // make sure there is no warning about inconsistent units
   unsigned int i = 0, iMax = CCopasiMessage::size();
   unsigned int found24 = 0;
   unsigned int found55 = 0;
   unsigned int found79 = 0;
   unsigned int found66 = 0;
   while (i < iMax)
     {
       CCopasiMessage message = CCopasiMessage::getLastMessage();
       // check for messages about inconsistent units
       if (message.getNumber() == MCSBML + 24)
         {
           ++found24;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 55)
         {
           ++found55;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 79)
         {
           ++found79;
         }
       // check for import errors
       if (message.getNumber() == MCSBML + 66)
         {
           ++found66;
         }
       ++i;
     }
   CPPUNIT_ASSERT(found55 == 0);
   CPPUNIT_ASSERT(found24 == 0);
   CPPUNIT_ASSERT(found79 == 1);
   CPPUNIT_ASSERT(found66 == 0);
 }
Member Data Documentation
const char * test000084::MODEL_STRING1 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with global area unit nm^2.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\" />"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 58 of file test000084.h.
Referenced by test_import_compartment_units_1().
const char * test000084::MODEL_STRING10 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a compartment with no units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  />"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 83 of file test000084.h.
Referenced by test_import_compartment_units_10().
const char * test000084::MODEL_STRING11 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with volume units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"volume\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 86 of file test000084.h.
Referenced by test_import_compartment_units_11().
const char * test000084::MODEL_STRING12 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with length units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"length\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 89 of file test000084.h.
Referenced by test_import_compartment_units_12().
const char * test000084::MODEL_STRING13 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with dimensionmess units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"dimensionless\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 92 of file test000084.h.
Referenced by test_import_compartment_units_13().
const char * test000084::MODEL_STRING14 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with m^3 units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"0\" exponent=\"3\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 95 of file test000084.h.
Referenced by test_import_compartment_units_14().
const char * test000084::MODEL_STRING15 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with m units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"0\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 98 of file test000084.h.
Referenced by test_import_compartment_units_15().
const char * test000084::MODEL_STRING16 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with mole units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"mole\" scale=\"0\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 101 of file test000084.h.
Referenced by test_import_compartment_units_16().
const char * test000084::MODEL_STRING17 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a 2D compartment with substance units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"substance\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 104 of file test000084.h.
Referenced by test_import_compartment_units_17().
const char * test000084::MODEL_STRING18 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and two compartments. One has no unit, the other uses area as the unit.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  />"
  "      <compartment id=\"compartment_2\" name=\"compartment_2\" size=\"1\" spatialDimensions=\"2\"  units=\"area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 107 of file test000084.h.
Referenced by test_import_compartment_units_18().
const char * test000084::MODEL_STRING19 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and two compartments. One has no unit, the other uses metre^2 as the unit.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  />"
  "      <compartment id=\"compartment_2\" name=\"compartment_2\" size=\"1\" spatialDimensions=\"2\"  units=\"area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 110 of file test000084.h.
Referenced by test_import_compartment_units_19().
const char * test000084::MODEL_STRING2 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with global area unit 10e-4* m^2 .</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-4\" exponent=\"2\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\" />"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 60 of file test000084.h.
Referenced by test_import_compartment_units_2().
const char * test000084::MODEL_STRING20 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and two compartments. One has no unit, the other uses nm^2 as the unit.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  />"
  "      <compartment id=\"compartment_2\" name=\"compartment_2\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 113 of file test000084.h.
Referenced by test_import_compartment_units_20().
const char * test000084::MODEL_STRING21 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and two compartments. One has nm^2 as the unit, the other one has no unit.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\" />"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "      <compartment id=\"compartment_2\" name=\"compartment_2\" size=\"1\" spatialDimensions=\"2\"  />"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 116 of file test000084.h.
Referenced by test_import_compartment_units_21().
const char * test000084::MODEL_STRING3 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with global area unit mole.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"area\">"
  "        <listOfUnits>"
  "          <unit kind=\"mole\" scale=\"0\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\" />"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 62 of file test000084.h.
Referenced by test_import_compartment_units_3().
const char * test000084::MODEL_STRING4 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with global area unit nm^2</p>"
  "        <p> and a compartment with mm^2 units</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-3\" exponent=\"2\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 65 of file test000084.h.
Referenced by test_import_compartment_units_4().
const char * test000084::MODEL_STRING5 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with global area unit nm^2</p>"
  "        <p>and a compartment with mole units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"mole\" scale=\"0\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 68 of file test000084.h.
Referenced by test_import_compartment_units_5().
const char * test000084::MODEL_STRING6 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with global area unit mole</p>"
  "        <p>and a compartment with nm^2 units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "      <unitDefinition id=\"area\">"
  "        <listOfUnits>"
  "          <unit kind=\"mole\" scale=\"0\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 71 of file test000084.h.
Referenced by test_import_compartment_units_6().
const char * test000084::MODEL_STRING7 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a compartment with nm^2 units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfUnitDefinitions>"
  "      <unitDefinition id=\"my_area\">"
  "        <listOfUnits>"
  "          <unit kind=\"metre\" scale=\"-9\" exponent=\"2\"/>"
  "        </listOfUnits>"
  "      </unitDefinition>"
  "    </listOfUnitDefinitions>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"my_area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 74 of file test000084.h.
Referenced by test_import_compartment_units_7().
const char * test000084::MODEL_STRING8 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a compartment with area units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"area\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 77 of file test000084.h.
Referenced by test_import_compartment_units_8().
const char * test000084::MODEL_STRING9 static protected
Initial value:
=
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  "<sbml xmlns=\"http://www.sbml.org/sbml/level2\" level=\"2\" version=\"1\">"
  "  <model id=\"Model_1\" name=\"New Model\">"
  "    <notes>"
  "      <body xmlns=\"http://www.w3.org/1999/xhtml\">"
  "        <p>L2V1 model with no global area unit</p>"
  "        <p>and a compartment with metre units.</p>"
  "      </body>"
  "    </notes>"
  "    <listOfCompartments>"
  "      <compartment id=\"compartment_1\" name=\"compartment\" size=\"1\" spatialDimensions=\"2\"  units=\"metre\"/>"
  "    </listOfCompartments>"
  "  </model>"
  "</sbml>"
Definition at line 80 of file test000084.h.
Referenced by test_import_compartment_units_9().
CCopasiDataModel * test000084::pCOPASIDATAMODEL = NULL static protected
Definition at line 118 of file test000084.h.
Referenced by setUp(), test_import_compartment_units_1(), test_import_compartment_units_10(), test_import_compartment_units_11(), test_import_compartment_units_12(), test_import_compartment_units_13(), test_import_compartment_units_14(), test_import_compartment_units_15(), test_import_compartment_units_16(), test_import_compartment_units_17(), test_import_compartment_units_18(), test_import_compartment_units_19(), test_import_compartment_units_2(), test_import_compartment_units_20(), test_import_compartment_units_21(), test_import_compartment_units_3(), test_import_compartment_units_4(), test_import_compartment_units_5(), test_import_compartment_units_6(), test_import_compartment_units_7(), test_import_compartment_units_8(), and test_import_compartment_units_9().
The documentation for this class was generated from the following files:
test000084.h
test000084.cpp