COPASI API: CLGraphicalObject Class Reference
CLGraphicalObject Class Reference
#include <CLGraphicalObject.h>
Public Member Functions
CLGraphicalObject (const std::string &name="GraphicalObject", const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const CLGraphicalObject &src, const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual CLGraphicalObject * clone () const
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
const CLBoundingBox & getBoundingBox () const
CLBoundingBox & getBoundingBox ()
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CCopasiObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
virtual void moveBy (const CLPoint &p)
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void print (std::ostream *ostream) const
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Friends
std::ostream & operator<< (std::ostream &os, const CLGraphicalObject &g)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
This is the base class for the layout objects in copasi. It is a CCopasiObject. It also has a key (which is used if one layout object refers to another one) It provides the mechanism for refering to a copasi model object by key. This needs to be specialized in the derived classes
Definition at line 33 of file CLGraphicalObject.h.
Constructor & Destructor Documentation
CLGraphicalObject::CLGraphicalObject (const std::string & name = "GraphicalObject", const CCopasiContainer * pParent = NULL)
Definition at line 27 of file CLGraphicalObject.cpp.
Referenced by clone().
   : CLBase(),
     CCopasiContainer(name, pParent, "LayoutElement"),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Layout", this)),
     mModelObjectKey(""),
     mObjectRole(""),
     mBBox()
 {};
CLGraphicalObject::CLGraphicalObject (const CLGraphicalObject & src, const CCopasiContainer * pParent = NULL)
Definition at line 37 of file CLGraphicalObject.cpp.
   : CLBase(src),
     CCopasiContainer(src, pParent),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Layout", this)),
     mModelObjectKey(src.mModelObjectKey),
     mObjectRole(src.mObjectRole),
     mBBox(src.mBBox)
 {};
CLGraphicalObject::CLGraphicalObject (const GraphicalObject & sbml, std::map< std::string, std::string > & layoutmap, const CCopasiContainer * pParent = NULL)
constructor from libsbml object
Definition at line 47 of file CLGraphicalObject.cpp.
References mKey, and mObjectRole.
   : CLBase(sbml),
     CCopasiContainer(sbml.getId(), pParent, "LayoutElement"),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Layout", this)),
     mModelObjectKey(""),
     mBBox(*sbml.getBoundingBox())
 {
   RenderGraphicalObjectPlugin* rgoPlugin = (RenderGraphicalObjectPlugin*) sbml.getPlugin("render");
   if (rgoPlugin != NULL)
     mObjectRole = rgoPlugin->getObjectRole();
   //add the copasi key to the map
   layoutmap[sbml.getId()] = mKey;
 };
CLGraphicalObject::~CLGraphicalObject ()
Definition at line 65 of file CLGraphicalObject.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
 }
Member Function Documentation
virtual CLGraphicalObject* CLGraphicalObject::clone () const inline virtual
Reimplemented in CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLTextGlyph, CLReferenceGlyph, CLCompartmentGlyph, and CLMetabGlyph.
Definition at line 82 of file CLGraphicalObject.h.
References CLGraphicalObject().
 {return new CLGraphicalObject(*this, NULL);};
void CLGraphicalObject::exportToSBML (GraphicalObject * sbmlobject, const std::map< const CCopasiObject *, SBase * > & copasimodelmap, std::map< std::string, const SBase * > & sbmlIDs) const virtual
This method writes the information of the copasi layout object into the corresponding sbml object
Definition at line 133 of file CLGraphicalObject.cpp.
References CSBMLExporter::createUniqueId(), CLBoundingBox::getSBMLBoundingBox(), mBBox, and mObjectRole.
Referenced by CLMetabGlyph::exportToSBML(), CLCompartmentGlyph::exportToSBML(), CLTextGlyph::exportToSBML(), CLMetabReferenceGlyph::exportToSBML(), CLGeneralGlyph::exportToSBML(), and CLReactionGlyph::exportToSBML().
 {
   if (!sbmlobject) return;
   //Name and ID
   std::string id = CSBMLExporter::createUniqueId(sbmlIDs, "layout_glyph", true);
   sbmlobject->setId(id);
   sbmlIDs.insert(std::pair<const std::string, const SBase*>(id, sbmlobject));
   //Bounding box
   BoundingBox tmpbox = mBBox.getSBMLBoundingBox();
   sbmlobject->setBoundingBox(&tmpbox);
   if (this->mObjectRole.find_first_not_of(" \t\r\n") != std::string::npos)
     {
       RenderGraphicalObjectPlugin* rgoPlugin = (RenderGraphicalObjectPlugin*) sbmlobject->getPlugin("render");
       if (rgoPlugin != NULL)
         rgoPlugin->setObjectRole(this->mObjectRole);
     }
 }
const CLBoundingBox& CLGraphicalObject::getBoundingBox () const inline
Definition at line 86 of file CLGraphicalObject.h.
References mBBox.
Referenced by CCopasiSpringLayout::borderProjection(), CLayout::calculateBoundingBox(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CQLabelGraphicsItem::CQLabelGraphicsItem(), CQStyledGraphicsItem::CQStyledGraphicsItem(), CLLayoutRenderer::draw_layout(), CCopasiSpringLayout::finalizeState(), CLLayoutRenderer::getObjectsAt(), CLLayoutRenderer::getObjectsInBoundingBox(), CLLayoutRenderer::move_graphical_object(), compareGraphicalObjectsBySize::operator()(), and CCopasiXML::saveLayoutList().
 {return mBBox;};
CLBoundingBox& CLGraphicalObject::getBoundingBox () inline
Definition at line 87 of file CLGraphicalObject.h.
References mBBox.
 {return mBBox;};
const CLDimensions& CLGraphicalObject::getDimensions () const inline
Definition at line 99 of file CLGraphicalObject.h.
References CLBoundingBox::getDimensions(), and mBBox.
Referenced by randomlyPlaceGlyphInCompartmentGlyph(), and randomlyPlaceGlyphInDimensions().
 {return mBBox.getDimensions();};
const C_FLOAT64& CLGraphicalObject::getHeight () const inline
Definition at line 105 of file CLGraphicalObject.h.
References CLBoundingBox::getDimensions(), CLDimensions::getHeight(), and mBBox.
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addReactionVariables(), CCopasiSpringLayout::borderProjection(), CQGLNetworkPainter::drawNode(), getBounds(), CLabel::initOrigValues(), CCopasiSpringLayout::potEdge(), CCopasiSpringLayout::potGeneralEdge(), CCopasiSpringLayout::potReactionCompartment(), CCopasiSpringLayout::potReactionReaction(), CCopasiSpringLayout::potSecondOrderEdge(), CCopasiSpringLayout::potSpeciesCompartment(), CCopasiSpringLayout::potSpeciesReaction(), and CCopasiSpringLayout::potSpeciesSpecies().
 {return mBBox.getDimensions().getHeight();};
virtual const std::string& CLGraphicalObject::getKey () const inline virtual
Retrieves the key of the layout object
Reimplemented from CCopasiObject.
Definition at line 79 of file CLGraphicalObject.h.
References mKey.
Referenced by CCompartmentGraphNode::CCompartmentGraphNode(), CLayout::CLayout(), CQConnectionGraphicsItem::CQConnectionGraphicsItem(), CQStyledGraphicsItem::CQStyledGraphicsItem(), CCopasiSpringLayout::createLayout(), CLayout::exportToSBML(), getTextForItem(), CLRenderResolver::resolveStyle(), CCopasiXML::saveLayoutList(), CCopasiXMLParser::MetaboliteReferenceGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), CCopasiXMLParser::LocalStyleElement::start(), tagKey(), and CLLayoutRenderer::update_associations().
   {return mKey;};
CCopasiObject * CLGraphicalObject::getModelObject () const
Definition at line 89 of file CLGraphicalObject.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), hasValidModelReference(), and mModelObjectKey.
Referenced by CQLayoutScene::addGlyph(), CCopasiSpringLayout::createLayout(), CLLayoutRenderer::draw_layout(), CLMetabGlyph::exportToSBML(), CLCompartmentGlyph::exportToSBML(), CLTextGlyph::exportToSBML(), CLGeneralGlyph::exportToSBML(), CLReactionGlyph::exportToSBML(), getModelObjectDisplayName(), getModelObjectName(), moveObject(), and CCopasiSpringLayout::randomize().
 {
   CCopasiObject* pObject = NULL;
   // as an additional safeguard, we check
   // if the object is in the same datamodel
   // This is not foolproof, but should work in most cases.
   if (this->hasValidModelReference())
     {
       pObject = CCopasiRootContainer::getKeyFactory()->get(mModelObjectKey);
     }
   return pObject;
 }
std::string CLGraphicalObject::getModelObjectDisplayName (bool regular = true, bool richtext = false) const
if the graphical object refers to a model object this method will return the display name of that object.
Definition at line 119 of file CLGraphicalObject.cpp.
References getModelObject(), and CCopasiObject::getObjectName().
Referenced by CLTextGlyph::getText(), and operator<<().
 {
   CCopasiObject * tmp = getModelObject();
   if (tmp)
     {
       return tmp->getObjectName();
     }
   else
     {
       return "";
     }
 }
const std::string& CLGraphicalObject::getModelObjectKey () const inline
Definition at line 108 of file CLGraphicalObject.h.
References mModelObjectKey.
Referenced by CCompartmentGraphNode::CCompartmentGraphNode(), CCopasiXML::saveLayoutList(), CLLayoutRenderer::setDeduceSpeciesReferenceRoles(), and CLLayoutRenderer::update_associations().
 {return mModelObjectKey;};
std::string CLGraphicalObject::getModelObjectName () const
if the graphical object refers to a model object this method will return the name of that object.
Definition at line 109 of file CLGraphicalObject.cpp.
References getModelObject(), and CCopasiObject::getObjectName().
 {
   CCopasiObject * tmp = getModelObject();
   if (tmp)
     return tmp->getObjectName();
   else
     return "";
 }
const std::string & CLGraphicalObject::getObjectRole () const
Method to read the object role of an object.
Definition at line 182 of file CLGraphicalObject.cpp.
References mObjectRole.
Referenced by CLRenderResolver::resolveStyle(), CCopasiXML::saveLayoutList(), and CLLayoutRenderer::setDeduceSpeciesReferenceRoles().
 {
   return this->mObjectRole;
 }
const CLPoint& CLGraphicalObject::getPosition () const inline
Definition at line 90 of file CLGraphicalObject.h.
References CLBoundingBox::getPosition(), and mBBox.
Referenced by CCopasiSpringLayout::finalizeState(), CCopasiSpringLayout::initFromLayout(), and randomlyPlaceGlyphInCompartmentGlyph().
 {return mBBox.getPosition();};
const C_FLOAT64& CLGraphicalObject::getWidth () const inline
Definition at line 102 of file CLGraphicalObject.h.
References CLBoundingBox::getDimensions(), CLDimensions::getWidth(), and mBBox.
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addReactionVariables(), CCopasiSpringLayout::borderProjection(), CQGLNetworkPainter::drawNode(), getBounds(), CLabel::initOrigValues(), CCopasiSpringLayout::potEdge(), CCopasiSpringLayout::potGeneralEdge(), CCopasiSpringLayout::potReactionCompartment(), CCopasiSpringLayout::potReactionReaction(), CCopasiSpringLayout::potSecondOrderEdge(), CCopasiSpringLayout::potSpeciesCompartment(), CCopasiSpringLayout::potSpeciesReaction(), and CCopasiSpringLayout::potSpeciesSpecies().
 {return mBBox.getDimensions().getWidth();};
const C_FLOAT64& CLGraphicalObject::getX () const inline
Definition at line 93 of file CLGraphicalObject.h.
References CLBoundingBox::getPosition(), CLPoint::getX(), and mBBox.
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addPositionVariables(), CCopasiSpringLayout::addReactionVariables(), CQGLNetworkPainter::drawNode(), getBounds(), CLabel::initOrigValues(), placeTextGlyphs(), CCopasiSpringLayout::potEdge(), CCopasiSpringLayout::potGeneralEdge(), CCopasiSpringLayout::potReactionCompartment(), CCopasiSpringLayout::potReactionReaction(), CCopasiSpringLayout::potSecondOrderEdge(), CCopasiSpringLayout::potSpeciesCompartment(), CCopasiSpringLayout::potSpeciesReaction(), and CCopasiSpringLayout::potSpeciesSpecies().
 {return mBBox.getPosition().getX();};
const C_FLOAT64& CLGraphicalObject::getY () const inline
Definition at line 96 of file CLGraphicalObject.h.
References CLBoundingBox::getPosition(), CLPoint::getY(), and mBBox.
Referenced by CCopasiSpringLayout::addCompartmentVariables(), CCopasiSpringLayout::addPositionVariables(), CCopasiSpringLayout::addReactionVariables(), CQGLNetworkPainter::drawNode(), getBounds(), CLabel::initOrigValues(), placeTextGlyphs(), CCopasiSpringLayout::potEdge(), CCopasiSpringLayout::potGeneralEdge(), CCopasiSpringLayout::potReactionCompartment(), CCopasiSpringLayout::potReactionReaction(), CCopasiSpringLayout::potSecondOrderEdge(), CCopasiSpringLayout::potSpeciesCompartment(), CCopasiSpringLayout::potSpeciesReaction(), and CCopasiSpringLayout::potSpeciesSpecies().
 {return mBBox.getPosition().getY();};
bool CLGraphicalObject::hasValidModelReference () const
This method is used for the export of several layout elements. Layout elements can reference model elements, but when a referenced model element is deleted, the layout is not infomred about this yet, so we end up with dangling references. If the key belongs to an object in the same datamodel, true is returned, else false is returned.
This method is used for the export of several layout elements. Layout elements can reference model elements, but when a referenced model element is deleted, the layout is not infomred about this yet, so we end up with dnagling references. In order to not write these dangling references to file, we check if the reference belongs to a valid object in the same datamodel. If not, we issue a warning. This warning is only issued once during a save process.
If the key belongs to an object in the same datamodel, true is returned, else false is returned.
Definition at line 198 of file CLGraphicalObject.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), CCopasiObject::getObjectParent(), and mModelObjectKey.
Referenced by getModelObject(), and CCopasiXML::saveLayoutList().
 {
   bool result = false;
   // check if the object for this key actually exists
   // TODO This is only a workaround because it is theoretically
   // TODO possible that the key no longer belongs to the same object it
   // TODO originally did.
   CCopasiObject* pObj = CCopasiRootContainer::getKeyFactory()->get(this->mModelObjectKey);
   if (pObj != NULL)
     {
       // check if the object actually belongs to the same
       // model as the text glyph
       const CCopasiDataModel* pDM1 = NULL;
       const CCopasiDataModel* pDM2 = NULL;
       const CCopasiContainer* pParent = pObj->getObjectParent();
       while (pParent != NULL)
         {
           pDM1 = dynamic_cast<const CCopasiDataModel*>(pParent);
           if (pDM1 != NULL)
             {
               break;
             }
           pParent = pParent->getObjectParent();
         }
       pParent = this->getObjectParent();
       while (pParent != NULL)
         {
           pDM2 = dynamic_cast<const CCopasiDataModel*>(pParent);
           if (pDM2 != NULL)
             {
               break;
             }
           pParent = pParent->getObjectParent();
         }
       //assert(pDM2 != NULL);
       if (pDM1 != NULL && pDM2 == NULL)
         {
           // if we have been able to resolve the model reference, but
           // don't have a datamodel parent, that is good enough
           return true;
         }
       if (pDM1 != NULL && pDM1 == pDM2)
         {
           result = true;
         }
     }
   return result;
 }
void CLGraphicalObject::moveBy (const CLPoint & p) virtual
Reimplemented from CLBase.
Reimplemented in CLReactionGlyph, CLGeneralGlyph, and CLGlyphWithCurve.
Definition at line 104 of file CLGraphicalObject.cpp.
References mBBox, and CLBoundingBox::moveBy().
Referenced by CLGlyphWithCurve::moveBy(), CLayout::moveBy(), and moveObject().
 {
   mBBox.moveBy(p);
 }
CLGraphicalObject & CLGraphicalObject::operator= (const CLGraphicalObject & rhs)
The assignment operator does not copy the key.
Definition at line 70 of file CLGraphicalObject.cpp.
References CCopasiObject::getObjectName(), mBBox, mModelObjectKey, mObjectRole, and CCopasiObject::setObjectName().
Referenced by CLMetabGlyph::operator=(), CLGlyphWithCurve::operator=(), CLCompartmentGlyph::operator=(), and CLTextGlyph::operator=().
 {
   if (this == &rhs) return * this; //do nothing if lhs and rhs are the same
   CLBase::operator=(rhs);
   //warning: in this place we should call the assignment operator of
   //CCopasiContainer (which does not exist).
   //We handle this explicitly instead.
   setObjectName(rhs.getObjectName());
   //object flag cannot be accessed, it is private.
   mModelObjectKey = rhs.mModelObjectKey;
   this->mObjectRole = rhs.mObjectRole;
   mBBox = rhs.mBBox;
   return *this;
 }
void CLGraphicalObject::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiObject.
Reimplemented in CLReactionGlyph, CLGeneralGlyph, CLMetabReferenceGlyph, CLReferenceGlyph, and CLGlyphWithCurve.
Definition at line 168 of file CLGraphicalObject.cpp.
 {*ostream << *this;}
void CLGraphicalObject::setBoundingBox (const CLBoundingBox & bb) inline
Definition at line 88 of file CLGraphicalObject.h.
References mBBox.
Referenced by test000097::createModel().
 {mBBox = bb;};
void CLGraphicalObject::setDimensions (const CLDimensions & d) inline
Definition at line 100 of file CLGraphicalObject.h.
References mBBox, and CLBoundingBox::setDimensions().
Referenced by CCopasiSpringLayout::createLayout().
 {mBBox.setDimensions(d);};
void CLGraphicalObject::setHeight (const C_FLOAT64 & h) inline
Definition at line 106 of file CLGraphicalObject.h.
References CLBoundingBox::getDimensions(), mBBox, and CLDimensions::setHeight().
Referenced by CLabel::scale(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::MetaboliteReferenceGlyphElement::start(), CCopasiXMLParser::ReactionGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), and CCopasiXMLParser::AdditionalGOElement::start().
 {mBBox.getDimensions().setHeight(h);};
void CLGraphicalObject::setModelObjectKey (const std::string & k) inline
Definition at line 110 of file CLGraphicalObject.h.
References mModelObjectKey.
Referenced by CLCompartmentGlyph::CLCompartmentGlyph(), CLGeneralGlyph::CLGeneralGlyph(), CLMetabGlyph::CLMetabGlyph(), CLMetabReferenceGlyph::CLMetabReferenceGlyph(), CLReactionGlyph::CLReactionGlyph(), CLTextGlyph::CLTextGlyph(), CLayoutInitializer::createCompartmentGlyph(), CCopasiSpringLayout::createLayout(), CLayoutInitializer::createMetabGlyph(), test000097::createModel(), CLayoutInitializer::createReactionGlyph(), CCopasiXML::saveLayoutList(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::ReactionGlyphElement::start(), and CCopasiXMLParser::TextGlyphElement::start().
 {mModelObjectKey = k;};
void CLGraphicalObject::setObjectRole (const std::string & role)
Method to set the role of a graphical object.
Definition at line 174 of file CLGraphicalObject.cpp.
References mObjectRole.
Referenced by CCopasiSpringLayout::createLayout(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::MetaboliteReferenceGlyphElement::start(), CCopasiXMLParser::ReactionGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), and CCopasiXMLParser::AdditionalGOElement::start().
 {
   this->mObjectRole = role;
 }
void CLGraphicalObject::setPosition (const CLPoint & p) inline
Definition at line 91 of file CLGraphicalObject.h.
References mBBox, and CLBoundingBox::setPosition().
Referenced by CCopasiSpringLayout::createLayout(), placeTextGlyphs(), CCopasiSpringLayout::randomize(), randomlyPlaceGlyphInCompartmentGlyph(), and randomlyPlaceGlyphInDimensions().
 {mBBox.setPosition(p);};
void CLGraphicalObject::setWidth (const C_FLOAT64 & w) inline
Definition at line 103 of file CLGraphicalObject.h.
References CLBoundingBox::getDimensions(), mBBox, and CLDimensions::setWidth().
Referenced by CLabel::scale(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::MetaboliteReferenceGlyphElement::start(), CCopasiXMLParser::ReactionGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), and CCopasiXMLParser::AdditionalGOElement::start().
 {mBBox.getDimensions().setWidth(w);};
void CLGraphicalObject::setX (const C_FLOAT64 & x) inline
Definition at line 94 of file CLGraphicalObject.h.
References CLBoundingBox::getPosition(), mBBox, and CLPoint::setX().
Referenced by CLabel::scale(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::MetaboliteReferenceGlyphElement::start(), CCopasiXMLParser::ReactionGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), and CCopasiXMLParser::AdditionalGOElement::start().
 {mBBox.getPosition().setX(x);};
void CLGraphicalObject::setY (const C_FLOAT64 & y) inline
Definition at line 97 of file CLGraphicalObject.h.
References CLBoundingBox::getPosition(), mBBox, and CLPoint::setY().
Referenced by CLabel::scale(), CCopasiXMLParser::CompartmentGlyphElement::start(), CCopasiXMLParser::MetaboliteGlyphElement::start(), CCopasiXMLParser::MetaboliteReferenceGlyphElement::start(), CCopasiXMLParser::ReactionGlyphElement::start(), CCopasiXMLParser::TextGlyphElement::start(), and CCopasiXMLParser::AdditionalGOElement::start().
 {mBBox.getPosition().setY(y);};
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLGraphicalObject & g) friend
insert operator
Definition at line 157 of file CLGraphicalObject.cpp.
 {
   os << "GraphicalObject \"" << g.getObjectName() << "\" " << g.mBBox << std::endl;
   std::string tmp = g.getModelObjectDisplayName();
   if (tmp != "")
     os << "  refers to " << tmp << std::endl;
   return os;
 }
Member Data Documentation
CLBoundingBox CLGraphicalObject::mBBox protected
Definition at line 52 of file CLGraphicalObject.h.
Referenced by CLabel::adaptToHeight(), exportToSBML(), getBoundingBox(), getDimensions(), getHeight(), getPosition(), getWidth(), getX(), getY(), moveBy(), operator<<(), operator=(), CGraphNode::scale(), CLabel::scalePosition(), setBoundingBox(), setDimensions(), setHeight(), setPosition(), setWidth(), setX(), and setY().
std::string CLGraphicalObject::mKey protected
The key of the layout object itself
Definition at line 40 of file CLGraphicalObject.h.
Referenced by CLGraphicalObject(), getKey(), and ~CLGraphicalObject().
std::string CLGraphicalObject::mModelObjectKey protected
The key of an object of the COPASI model. This is not used in this base class. It is provided as a service for the derived classes
Definition at line 47 of file CLGraphicalObject.h.
Referenced by getModelObject(), getModelObjectKey(), CLabel::getText(), hasValidModelReference(), operator=(), and setModelObjectKey().
std::string CLGraphicalObject::mObjectRole protected
Definition at line 50 of file CLGraphicalObject.h.
Referenced by CLGraphicalObject(), exportToSBML(), getObjectRole(), operator=(), and setObjectRole().
The documentation for this class was generated from the following files:
CLGraphicalObject.h
CLGraphicalObject.cpp