COPASI API: CQProgressItemBar Class Reference
CQProgressItemBar Class Reference
#include <CQProgressItemBar.h>
Public Member Functions
CQProgressItemBar (QWidget *parent=0, const char *name=0)
virtual bool initFromProcessReportItem (CProcessReportItem *pItem)
virtual bool process ()
virtual bool reset ()
~CQProgressItemBar ()
Public Member Functions inherited from CQProgressItem
CQProgressItem (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
~CQProgressItem ()
Private Member Functions
void destroy ()
void init ()
virtual void setValueFromDOUBLE ()
virtual void setValueFromINT ()
virtual void setValueFromUINT ()
Private Attributes
C_INT32 mCurrentValue
CCopasiParameter::Value mEnd
C_FLOAT64 mFactor
C_INT32 mLastSet
void(CQProgressItemBar::* mpSetValue)()
CCopasiParameter::Value mStart
CCopasiParameter::Value mValue
Additional Inherited Members
Protected Attributes inherited from CQProgressItem
CProcessReportItem * mpItem
Detailed Description
Definition at line 26 of file CQProgressItemBar.h.
Constructor & Destructor Documentation
CQProgressItemBar::CQProgressItemBar (QWidget * parent = 0, const char * name = 0)
Definition at line 27 of file CQProgressItemBar.cpp.
References init().
     : CQProgressItem(parent, name)
 {
   Ui::CQProgressItemBar::setupUi(this);
   init();
 }
CQProgressItemBar::~CQProgressItemBar ()
Definition at line 38 of file CQProgressItemBar.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQProgressItemBar::destroy () private
Definition at line 127 of file CQProgressItemBar.cpp.
References CCopasiParameter::DOUBLE, CCopasiParameter::getType(), CCopasiParameter::INT, CQProgressItem::mpItem, mStart, pdelete, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pUINT, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by initFromProcessReportItem(), and ~CQProgressItemBar().
 {
   if (mpItem == NULL) return;
   switch (mpItem->getType())
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         pdelete(mStart.pDOUBLE);
         break;
       case CCopasiParameter::INT:
         pdelete(mStart.pINT);
         break;
       case CCopasiParameter::UINT:
         pdelete(mStart.pUINT);
         break;
       default:
         break;
     }
 }
void CQProgressItemBar::init () private
Definition at line 151 of file CQProgressItemBar.cpp.
References CQProgressItem::mpItem, mStart, and CCopasiParameter::Value::pVOID.
Referenced by CQProgressItemBar().
 {
   mpItem = NULL;
   mStart.pVOID = NULL;
 }
bool CQProgressItemBar::initFromProcessReportItem (CProcessReportItem * pItem) virtual
Reimplemented from CQProgressItem.
Definition at line 45 of file CQProgressItemBar.cpp.
References destroy(), FROM_UTF8, CProcessReportItem::getEndValue(), CCopasiObject::getObjectName(), CCopasiParameter::getValue(), mEnd, mLastSet, CQProgressItem::mpItem, mStart, mValue, CCopasiParameter::Value::pVOID, and reset().
 {
   mpItem = pItem;
   mValue = mpItem->getValue();
   mEnd = mpItem->getEndValue();
   mItemName->setText(FROM_UTF8(mpItem->getObjectName()));
   mProgressBar->setMinimum(0);
   mProgressBar->setMaximum(100);
   mLastSet = -1; // indicates was never set;
   // needed so that reset() does allocation
   if (mStart.pVOID != NULL) destroy();
   return reset();
 }
bool CQProgressItemBar::process () virtual
Reimplemented from CQProgressItem.
Definition at line 63 of file CQProgressItemBar.cpp.
References mCurrentValue, mLastSet, and mpSetValue.
Referenced by reset().
 {
   (this->*mpSetValue)();
   if (mCurrentValue != mLastSet)
     {
       mProgressBar->setValue(mCurrentValue);
       mLastSet = mCurrentValue;
     }
   return true;
 }
bool CQProgressItemBar::reset () virtual
Reimplemented from CQProgressItem.
Definition at line 76 of file CQProgressItemBar.cpp.
References C_FLOAT64, C_INT32, CCopasiParameter::DOUBLE, CCopasiParameter::getType(), CCopasiParameter::INT, mEnd, mFactor, CQProgressItem::mpItem, mpSetValue, mStart, mValue, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pINT, process(), CCopasiParameter::Value::pUINT, setValueFromDOUBLE(), setValueFromINT(), setValueFromUINT(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by initFromProcessReportItem().
 {
   switch (mpItem->getType())
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         if (!mStart.pDOUBLE)
           mStart.pDOUBLE = new C_FLOAT64;
         * mStart.pDOUBLE = * mValue.pDOUBLE;
         mFactor = 100.0 / (* mEnd.pDOUBLE - * mStart.pDOUBLE);
         mpSetValue = & CQProgressItemBar::setValueFromDOUBLE;
         break;
       case CCopasiParameter::INT:
         if (!mStart.pINT)
           mStart.pINT = new C_INT32;
         * mStart.pINT = * mValue.pINT;
         mFactor = 100.0 / ((C_FLOAT64)(* mEnd.pINT - * mStart.pINT));
         mpSetValue = & CQProgressItemBar::setValueFromINT;
         break;
       case CCopasiParameter::UINT:
         if (!mStart.pUINT)
           mStart.pUINT = new unsigned C_INT32;
         * mStart.pUINT = * mValue.pUINT;
         mFactor = 100.0 / ((C_FLOAT64)(* mEnd.pUINT - * mStart.pUINT));
         mpSetValue = & CQProgressItemBar::setValueFromUINT;
         break;
       default:
         break;
     }
   return process();
 }
void CQProgressItemBar::setValueFromDOUBLE () private virtual
Definition at line 118 of file CQProgressItemBar.cpp.
References C_INT32, mCurrentValue, mFactor, mStart, mValue, and CCopasiParameter::Value::pDOUBLE.
Referenced by reset().
 {mCurrentValue = (C_INT32)(mFactor * (* mValue.pDOUBLE - * mStart.pDOUBLE));}
void CQProgressItemBar::setValueFromINT () private virtual
Definition at line 121 of file CQProgressItemBar.cpp.
References C_INT32, mCurrentValue, mFactor, mStart, mValue, and CCopasiParameter::Value::pINT.
Referenced by reset().
 {mCurrentValue = (C_INT32)(mFactor * (* mValue.pINT - * mStart.pINT));}
void CQProgressItemBar::setValueFromUINT () private virtual
Definition at line 124 of file CQProgressItemBar.cpp.
References C_INT32, mCurrentValue, mFactor, mStart, mValue, and CCopasiParameter::Value::pUINT.
Referenced by reset().
 {mCurrentValue = (C_INT32)(mFactor * (* mValue.pUINT - * mStart.pUINT));}
Member Data Documentation
C_INT32 CQProgressItemBar::mCurrentValue private
Definition at line 45 of file CQProgressItemBar.h.
Referenced by process(), setValueFromDOUBLE(), setValueFromINT(), and setValueFromUINT().
CCopasiParameter::Value CQProgressItemBar::mEnd private
Definition at line 41 of file CQProgressItemBar.h.
Referenced by initFromProcessReportItem(), and reset().
C_FLOAT64 CQProgressItemBar::mFactor private
Definition at line 40 of file CQProgressItemBar.h.
Referenced by reset(), setValueFromDOUBLE(), setValueFromINT(), and setValueFromUINT().
C_INT32 CQProgressItemBar::mLastSet private
Definition at line 44 of file CQProgressItemBar.h.
Referenced by initFromProcessReportItem(), and process().
void(CQProgressItemBar::* CQProgressItemBar::mpSetValue)() private
Definition at line 39 of file CQProgressItemBar.h.
Referenced by process(), and reset().
CCopasiParameter::Value CQProgressItemBar::mStart private
Definition at line 42 of file CQProgressItemBar.h.
Referenced by destroy(), init(), initFromProcessReportItem(), reset(), setValueFromDOUBLE(), setValueFromINT(), and setValueFromUINT().
CCopasiParameter::Value CQProgressItemBar::mValue private
Definition at line 43 of file CQProgressItemBar.h.
Referenced by initFromProcessReportItem(), reset(), setValueFromDOUBLE(), setValueFromINT(), and setValueFromUINT().
The documentation for this class was generated from the following files:
CQProgressItemBar.h
CQProgressItemBar.cpp