COPASI API: CNormalFunction Class Reference
CNormalFunction Class Reference
#include <CNormalFunction.h>
Public Types
enum Type {
LOG = 0, LOG10, EXP, SIN,
COS, TAN, SEC, CSC,
COT, SINH, COSH, TANH,
SECH, CSCH, COTH, ARCSIN,
ARCCOS, ARCTAN, ARCSEC, ARCCSC,
ARCCOT, ARCSINH, ARCCOSH, ARCTANH,
ARCSECH, ARCCSCH, ARCCOTH, SQRT,
ABS, FLOOR, CEIL, FACTORIAL,
INVALID
}
Public Member Functions
CNormalFunction ()
CNormalFunction (const CNormalFunction &src)
virtual CNormalBase * copy () const
CNormalFraction & getFraction ()
const CNormalFraction & getFraction () const
Type getType () const
bool operator< (const CNormalFunction &src) const
CNormalFunction & operator= (const CNormalFunction &src)
bool operator== (const CNormalFunction &src) const
void setFraction (const CNormalFraction &frac)
void setType (Type type)
virtual bool simplify ()
virtual std::string toString () const
virtual ~CNormalFunction ()
Public Member Functions inherited from CNormalBase
virtual bool areEqual (const CNormalBase &rhs) const
virtual ~CNormalBase ()
Static Public Attributes
static const char * NAMES []
Protected Attributes
CNormalFraction * mpFraction
Type mType
Detailed Description
Definition at line 28 of file CNormalFunction.h.
Member Enumeration Documentation
enum CNormalFunction::Type
Enumerator
LOG
LOG10
EXP
SIN
COS
TAN
SEC
CSC
COT
SINH
COSH
TANH
SECH
CSCH
COTH
ARCSIN
ARCCOS
ARCTAN
ARCSEC
ARCCSC
ARCCOT
ARCSINH
ARCCOSH
ARCTANH
ARCSECH
ARCCSCH
ARCCOTH
SQRT
ABS
FLOOR
CEIL
FACTORIAL
INVALID
Definition at line 31 of file CNormalFunction.h.
     {
       LOG = 0,
       LOG10,
       EXP,
       SIN,
       COS,
       TAN,
 #ifdef SEC
 # undef SEC
 #endif
       SEC,
       CSC,
       COT,
       SINH,
       COSH,
       TANH,
       SECH,
       CSCH,
       COTH,
       ARCSIN,
       ARCCOS,
       ARCTAN,
       ARCSEC,
       ARCCSC,
       ARCCOT,
       ARCSINH,
       ARCCOSH,
       ARCTANH,
       ARCSECH,
       ARCCSCH,
       ARCCOTH,
       SQRT,
       ABS,
       FLOOR,
       CEIL,
       FACTORIAL,
       INVALID
     };
Constructor & Destructor Documentation
CNormalFunction::CNormalFunction ()
Definition at line 65 of file CNormalFunction.cpp.
Referenced by copy().
                                 : CNormalBase(), mType(CNormalFunction::INVALID), mpFraction(NULL)
 {}
CNormalFunction::CNormalFunction (const CNormalFunction & src)
Definition at line 68 of file CNormalFunction.cpp.
                                                           : CNormalBase(src), mType(src.getType()), mpFraction(new CNormalFraction(src.getFraction()))
 {}
CNormalFunction::~CNormalFunction () virtual
Definition at line 71 of file CNormalFunction.cpp.
References mpFraction.
 {
   if (this->mpFraction != NULL) delete mpFraction;
 }
Member Function Documentation
CNormalBase * CNormalFunction::copy () const virtual
Implements CNormalBase.
Definition at line 152 of file CNormalFunction.cpp.
References CNormalFunction().
   {
     return new CNormalFunction(*this);
   }
CNormalFraction & CNormalFunction::getFraction ()
Definition at line 104 of file CNormalFunction.cpp.
References mpFraction.
Referenced by convertToCEvaluationNode(), normalize_variable_names(), and operator=().
 {
   return *mpFraction;
 }
const CNormalFraction & CNormalFunction::getFraction () const
Definition at line 109 of file CNormalFunction.cpp.
References mpFraction.
   {
     return *mpFraction;
   }
CNormalFunction::Type CNormalFunction::getType () const
Definition at line 94 of file CNormalFunction.cpp.
References mType.
Referenced by convertToCEvaluationNode(), and operator=().
   {
     return this->mType;
   }
bool CNormalFunction::operator< (const CNormalFunction & src) const
Definition at line 131 of file CNormalFunction.cpp.
References mpFraction, and mType.
   {
     bool result = false;
     if (this->mType < rhs.mType)
       {
         result = true;
       }
     else if (this->mType == rhs.mType)
       {
         result = (*this->mpFraction) < (*rhs.mpFraction);
       }
     return result;
   }
CNormalFunction & CNormalFunction::operator= (const CNormalFunction & src)
Definition at line 76 of file CNormalFunction.cpp.
References getFraction(), getType(), mpFraction, and mType.
 {
   if (this->mpFraction != NULL) delete this->mpFraction;
   this->mpFraction = new CNormalFraction(src.getFraction());
   this->mType = src.getType();
   return *this;
 }
bool CNormalFunction::operator== (const CNormalFunction & src) const
Definition at line 126 of file CNormalFunction.cpp.
References mpFraction, and mType.
   {
     return ((this->mType == rhs.mType) && (*this->mpFraction) == (*rhs.mpFraction));
   }
void CNormalFunction::setFraction (const CNormalFraction & frac)
Definition at line 114 of file CNormalFunction.cpp.
References mpFraction.
Referenced by createFunction().
 {
   if (this->mpFraction != NULL) delete this->mpFraction;
   this->mpFraction = new CNormalFraction(frac);
 }
void CNormalFunction::setType (CNormalFunction::Type type)
Definition at line 99 of file CNormalFunction.cpp.
References mType.
Referenced by createFunction().
 {
   this->mType = type;
 }
bool CNormalFunction::simplify () virtual
Implements CNormalBase.
Definition at line 145 of file CNormalFunction.cpp.
References mpFraction, and CNormalFraction::simplify().
 {
   bool result = true;
   if (this->mpFraction != NULL) result = this->mpFraction->simplify();
   return result;
 }
std::string CNormalFunction::toString () const virtual
Implements CNormalBase.
Definition at line 84 of file CNormalFunction.cpp.
References INVALID, mpFraction, mType, and NAMES.
Referenced by operator<<().
   {
     std::ostringstream s;
     if (this->mType != INVALID && this->mpFraction != NULL)
       {
         s << CNormalFunction::NAMES[this->mType] << "(" << *this->mpFraction << ")";
       }
     return s.str();
   }
Member Data Documentation
CNormalFraction* CNormalFunction::mpFraction protected
Definition at line 74 of file CNormalFunction.h.
Referenced by getFraction(), operator<(), operator=(), operator==(), setFraction(), simplify(), toString(), and ~CNormalFunction().
Type CNormalFunction::mType protected
Definition at line 72 of file CNormalFunction.h.
Referenced by getType(), operator<(), operator=(), operator==(), setType(), and toString().
const char * CNormalFunction::NAMES static
Definition at line 77 of file CNormalFunction.h.
Referenced by convertToCEvaluationNode(), and toString().
The documentation for this class was generated from the following files:
CNormalFunction.h
CNormalFunction.cpp