COPASI API: CCopasiAbstractArray Class Reference
CCopasiAbstractArray Class Reference abstract
#include <CCopasiArray.h>
Public Types
typedef C_FLOAT64 data_type
typedef std::vector< size_t > index_type
Public Member Functions
virtual size_t dimensionality () const =0
virtual data_type & operator[] (const index_type &index)=0
virtual const data_type & operator[] (const index_type &index) const =0
virtual const index_type & size () const =0
virtual ~CCopasiAbstractArray ()
Detailed Description
This abstract class defines the interface for an n-dimensional array of floats
Definition at line 31 of file CCopasiArray.h.
Member Typedef Documentation
typedef C_FLOAT64 CCopasiAbstractArray::data_type
Definition at line 35 of file CCopasiArray.h.
typedef std::vector<size_t> CCopasiAbstractArray::index_type
Definition at line 34 of file CCopasiArray.h.
Constructor & Destructor Documentation
virtual CCopasiAbstractArray::~CCopasiAbstractArray () inline virtual
Definition at line 39 of file CCopasiArray.h.
 {};
Member Function Documentation
virtual size_t CCopasiAbstractArray::dimensionality () const pure virtual
Implemented in CCopasiVectorInterface< VectorType >, CCopasiMatrixInterface< CMatrixType >, CCopasiMatrixInterface< CMatrix< C_FLOAT64 > >, and CCopasiArray.
Referenced by CArrayAnnotation::createAnnotationsCNFromCopasiVector(), and CArrayAnnotation::resize().
virtual data_type& CCopasiAbstractArray::operator[] (const index_type & index) pure virtual
Implemented in CCopasiVectorInterface< VectorType >, CCopasiMatrixInterface< CMatrixType >, CCopasiMatrixInterface< CMatrix< C_FLOAT64 > >, and CCopasiArray.
virtual const data_type& CCopasiAbstractArray::operator[] (const index_type & index) const pure virtual
Implemented in CCopasiVectorInterface< VectorType >, CCopasiMatrixInterface< CMatrixType >, CCopasiMatrixInterface< CMatrix< C_FLOAT64 > >, and CCopasiArray.
virtual const index_type& CCopasiAbstractArray::size () const pure virtual
Implemented in CCopasiVectorInterface< VectorType >, CCopasiMatrixInterface< CMatrixType >, CCopasiMatrixInterface< CMatrix< C_FLOAT64 > >, and CCopasiArray.
Referenced by operator<<(), CArrayAnnotation::resizeOneDimension(), and CArrayAnnotation::size().
The documentation for this class was generated from the following file:
CCopasiArray.h