COPASI API: test000095 Class Reference
test000095 Class Reference
#include <test000095.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_import_l3_event_1 ()
void test_import_l3_event_2 ()
void test_import_l3_event_3 ()
void test_import_l3_event_4 ()
void test_import_l3_event_5 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_l3_event_1)
CPPUNIT_TEST (test_import_l3_event_2)
CPPUNIT_TEST (test_import_l3_event_3)
CPPUNIT_TEST (test_import_l3_event_4)
CPPUNIT_TEST (test_import_l3_event_5)
CPPUNIT_TEST_SUITE (test000095)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 29 of file test000095.h.
Member Function Documentation
test000095::CPPUNIT_TEST (test_import_l3_event_1) private
test000095::CPPUNIT_TEST (test_import_l3_event_2) private
test000095::CPPUNIT_TEST (test_import_l3_event_3) private
test000095::CPPUNIT_TEST (test_import_l3_event_4) private
test000095::CPPUNIT_TEST (test_import_l3_event_5) private
test000095::CPPUNIT_TEST_SUITE (test000095) private
test000095::CPPUNIT_TEST_SUITE_END () private
void test000095::setUp ()
Definition at line 37 of file test000095.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000095::tearDown ()
Definition at line 45 of file test000095.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000095::test_import_l3_event_1 ()
Definition at line 50 of file test000095.cpp.
References CCopasiMessage::checkForMessage(), CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, MCSBML, MODEL_STRING1, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 0);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pModelValue->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT((fabs(pNumberNode->getValue() - 8.0) / 8.0) < 1e-9);
   // check that the message stack contains a warning about event priorities
   // MCSBML + 98
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 97) == false);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 98) == true);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 99) == false);
 }
void test000095::test_import_l3_event_2 ()
Definition at line 114 of file test000095.cpp.
References CCopasiMessage::checkForMessage(), CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, MCSBML, MODEL_STRING2, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 0);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pModelValue->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT((fabs(pNumberNode->getValue() - 8.0) / 8.0) < 1e-9);
   // check that the message stack contains a warning about initial values for triggers
   // MCSBML + 97
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 97) == true);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 98) == false);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 99) == false);
 }
void test000095::test_import_l3_event_3 ()
Definition at line 179 of file test000095.cpp.
References CCopasiMessage::checkForMessage(), CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, MCSBML, MODEL_STRING3, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING3));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 0);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pModelValue->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT((fabs(pNumberNode->getValue() - 8.0) / 8.0) < 1e-9);
   // check that the message stack contains a warning about event priorities
   // MCSBML + 98
   // check that the message stack contains a warning about initial values for triggers
   // MCSBML + 97
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 97) == true);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 98) == true);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 99) == false);
 }
void test000095::test_import_l3_event_4 ()
Definition at line 245 of file test000095.cpp.
References CCopasiMessage::checkForMessage(), CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, MCSBML, MODEL_STRING4, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING4));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 0);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pModelValue->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT((fabs(pNumberNode->getValue() - 8.0) / 8.0) < 1e-9);
   // check that the message stack contains a warning about non-persistent triggers
   // MCSBML + 99
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 97) == false);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 98) == false);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 99) == true);
 }
void test000095::test_import_l3_event_5 ()
Definition at line 309 of file test000095.cpp.
References CCopasiMessage::checkForMessage(), CCopasiNode< _Data >::getChild(), CCopasiDataModel::getModel(), CEvaluationNodeObject::getObjectCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), CEvaluationTree::getRoot(), CEvaluationNode::getType(), CEvaluationNode::getValue(), CEvaluationNodeLogical::GT, CCopasiDataModel::importSBMLFromString(), CCopasiObject::isReference(), CEvaluationNode::LOGICAL, MCSBML, MODEL_STRING5, CEvaluationNode::NUMBER, CEvaluationNode::OBJECT, CCopasiDataModel::ObjectFromName(), pCOPASIDATAMODEL, CEvaluationNode::subType(), and CEvaluationNode::type().
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING5));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 0);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 0);
   CPPUNIT_ASSERT(pModel->getModelValues().size() == 1);
   const CModelValue* pModelValue = pModel->getModelValues()[0];
   CPPUNIT_ASSERT(pModelValue != NULL);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   const CEvent* pEvent = pModel->getEvents()[0];
   CPPUNIT_ASSERT(pEvent != NULL);
   // check the trigger expression
   const CExpression* pExpr = pEvent->getTriggerExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   const CEvaluationNode* pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::LOGICAL);
   CPPUNIT_ASSERT((CEvaluationNodeLogical::SubType)CEvaluationNode::subType(pNode->getType()) == CEvaluationNodeLogical::GT);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getChild());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::OBJECT);
   const CEvaluationNodeObject* pObjectNode = dynamic_cast<const CEvaluationNodeObject*>(pNode);
   CPPUNIT_ASSERT(pObjectNode != NULL);
   CCopasiObjectName objectCN = pObjectNode->getObjectCN();
   CPPUNIT_ASSERT(!objectCN.empty());
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   const CCopasiObject* pObject = pCOPASIDATAMODEL->ObjectFromName(listOfContainers, objectCN);
   CPPUNIT_ASSERT(pObject != NULL);
   CPPUNIT_ASSERT(pObject->isReference() == true);
   CPPUNIT_ASSERT(pObject->getObjectName() == std::string("Time"));
   CPPUNIT_ASSERT(pObject->getObjectParent() == pModel);
   pNode = dynamic_cast<const CEvaluationNode*>(pNode->getSibling());
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   const CEvaluationNodeNumber* pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT(fabs((pNumberNode->getValue() - 2.0) / 2.0) < 1e-6);
   // check that there is a delay
   CPPUNIT_ASSERT(pEvent->getAssignments().size() == 1);
   // check the event assignment
   std::string key = pEvent->getAssignments()[0]->getTargetKey();
   CPPUNIT_ASSERT(key == pModelValue->getKey());
   pExpr = pEvent->getAssignments()[0]->getExpressionPtr();
   CPPUNIT_ASSERT(pExpr != NULL);
   pNode = pExpr->getRoot();
   CPPUNIT_ASSERT(pNode != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pNode->getType()) == CEvaluationNode::NUMBER);
   pNumberNode = dynamic_cast<const CEvaluationNodeNumber*>(pNode);
   CPPUNIT_ASSERT(pNumberNode != NULL);
   CPPUNIT_ASSERT((fabs(pNumberNode->getValue() - 8.0) / 8.0) < 1e-9);
   // check that there is no MCSBML + 97, MCSBML + 98 or MCSBML + 99  error message
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 97) == false);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 98) == false);
   CPPUNIT_ASSERT(CCopasiMessage::checkForMessage(MCSBML + 99) == false);
 }
Member Data Documentation
const char * test000095::MODEL_STRING1 static protected
Definition at line 43 of file test000095.h.
Referenced by test_import_l3_event_1().
const char * test000095::MODEL_STRING2 static protected
Definition at line 46 of file test000095.h.
Referenced by test_import_l3_event_2().
const char * test000095::MODEL_STRING3 static protected
Definition at line 49 of file test000095.h.
Referenced by test_import_l3_event_3().
const char * test000095::MODEL_STRING4 static protected
Definition at line 52 of file test000095.h.
Referenced by test_import_l3_event_4().
const char * test000095::MODEL_STRING5 static protected
Definition at line 55 of file test000095.h.
Referenced by test_import_l3_event_5().
CCopasiDataModel * test000095::pCOPASIDATAMODEL = NULL static protected
Definition at line 57 of file test000095.h.
Referenced by setUp(), test_import_l3_event_1(), test_import_l3_event_2(), test_import_l3_event_3(), test_import_l3_event_4(), and test_import_l3_event_5().
The documentation for this class was generated from the following files:
test000095.h
test000095.cpp