COPASI API: CCopasiPlotSelectionDialog Class Reference
CCopasiPlotSelectionDialog Class Reference
#include <CCopasiPlotSelectionDialog.h>
Public Member Functions
CCopasiPlotSelectionDialog (QWidget *parent=0, const char *name=0, bool modal=false, Qt::WFlags f=0)
void setModel (CModel *model, const CQSimpleSelectionTree::ObjectClasses &classes)
void setOutputVectors (std::vector< const CCopasiObject * > *outputVector1, std::vector< const CCopasiObject * > *outputVector2)
~CCopasiPlotSelectionDialog ()
Protected Slots
void slotCancelButtonClicked ()
void slotExpertCheckBoxToggled (bool checked)
void slotOKButtonClicked ()
Protected Member Functions
void setTabOrder ()
Protected Attributes
QHBoxLayout * mpButtonBox
QCheckBox * mpExpertCheckBox
QVBoxLayout * mpMainLayout
QSplitter * mpSplitter
QLabel * mpXAxisLabel
std::vector< const
CCopasiObject * > * mpXAxisOutputVector
QWidget * mpXAxisSelectionBox
CCopasiSelectionWidget * mpXAxisSelectionWidget
QLabel * mpYAxisLabel
std::vector< const
CCopasiObject * > * mpYAxisOutputVector
QWidget * mpYAxisSelectionBox
CCopasiSelectionWidget * mpYAxisSelectionWidget
Detailed Description
Definition at line 36 of file CCopasiPlotSelectionDialog.h.
Constructor & Destructor Documentation
CCopasiPlotSelectionDialog::CCopasiPlotSelectionDialog (QWidget * parent = 0, const char * name = 0, bool modal = false, Qt::WFlags f = 0)
Definition at line 34 of file CCopasiPlotSelectionDialog.cpp.
References mpButtonBox, mpExpertCheckBox, mpMainLayout, mpSplitter, mpXAxisLabel, mpXAxisOutputVector, mpXAxisSelectionBox, mpXAxisSelectionWidget, mpYAxisLabel, mpYAxisOutputVector, mpYAxisSelectionBox, mpYAxisSelectionWidget, CCopasiSelectionWidget::setOutputVector(), CCopasiSelectionWidget::setSingleSelection(), setTabOrder(), slotCancelButtonClicked(), slotExpertCheckBoxToggled(), and slotOKButtonClicked().
                                                                                                                :
   QDialog(parent, f)
   , mpExpertCheckBox(NULL)
   , mpXAxisSelectionWidget(NULL)
   , mpYAxisSelectionWidget(NULL)
   , mpSplitter(NULL)
   , mpButtonBox(NULL)
   , mpMainLayout(NULL)
   , mpXAxisLabel(NULL)
   , mpYAxisLabel(NULL)
   , mpXAxisSelectionBox(NULL)
   , mpYAxisSelectionBox(NULL)
   , mpXAxisOutputVector(NULL)
   , mpYAxisOutputVector(NULL)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   mpMainLayout = new QVBoxLayout(this);
   mpSplitter = new QSplitter(this);
   mpSplitter->setOrientation(Qt::Horizontal);
   mpMainLayout->addWidget(mpSplitter);
   mpButtonBox = new QHBoxLayout(this);
   mpMainLayout->addLayout(mpButtonBox);
   QDialogButtonBox* box = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, Qt::Horizontal, this);
   mpButtonBox->addWidget(box);
   mpExpertCheckBox = new QCheckBox(this);
   mpExpertCheckBox->setText("Expert Mode");
   mpExpertCheckBox->setChecked(false);
   mpButtonBox->addWidget(mpExpertCheckBox);
   mpXAxisSelectionBox = new QWidget(mpSplitter);
   QVBoxLayout *vBox1 = new QVBoxLayout(mpXAxisSelectionBox);
   mpXAxisSelectionBox->setLayout(vBox1);
   mpXAxisSelectionBox->layout()->setContentsMargins(5, 5, 5, 5);
   mpYAxisSelectionBox = new QWidget(mpSplitter);
   QVBoxLayout *vBox2 = new QVBoxLayout(mpYAxisSelectionBox);
   mpYAxisSelectionBox->setLayout(vBox2);
   mpYAxisSelectionBox->layout()->setContentsMargins(5, 5, 5, 5);
   mpXAxisLabel = new QLabel("X-Axis:", mpXAxisSelectionBox);
   mpXAxisLabel->setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Fixed);
   mpXAxisSelectionBox->layout()->addWidget(mpXAxisLabel);
   mpYAxisLabel = new QLabel("Y-Axis:", mpYAxisSelectionBox);
   mpYAxisLabel->setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Fixed);
   mpYAxisSelectionBox->layout()->addWidget(mpYAxisLabel);
   mpXAxisSelectionWidget = new CCopasiSelectionWidget(mpXAxisSelectionBox);
   mpXAxisSelectionWidget->setSingleSelection(true);
   mpXAxisSelectionWidget->setOutputVector(mpXAxisOutputVector);
   mpXAxisSelectionBox->layout()->addWidget(mpXAxisSelectionWidget);
   mpYAxisSelectionWidget = new CCopasiSelectionWidget(mpYAxisSelectionBox);
   mpYAxisSelectionWidget->setSingleSelection(false);
   mpYAxisSelectionWidget->setOutputVector(mpYAxisOutputVector);
   mpYAxisSelectionBox->layout()->addWidget(mpYAxisSelectionWidget);
   connect(box, SIGNAL(accepted()), this, SLOT(slotOKButtonClicked()));
   connect(box, SIGNAL(rejected()), this, SLOT(slotCancelButtonClicked()));
   connect(mpExpertCheckBox, SIGNAL(toggled(bool)), this, SLOT(slotExpertCheckBoxToggled(bool)));
   setTabOrder();
 }
CCopasiPlotSelectionDialog::~CCopasiPlotSelectionDialog ()
Definition at line 103 of file CCopasiPlotSelectionDialog.cpp.
 {}
Member Function Documentation
void CCopasiPlotSelectionDialog::setModel (CModel * model, const CQSimpleSelectionTree::ObjectClasses & classes)
Definition at line 171 of file CCopasiPlotSelectionDialog.cpp.
References mpXAxisSelectionWidget, mpYAxisSelectionWidget, and CCopasiSelectionWidget::populateTree().
Referenced by CQPlotSubwidget::addCurve2D().
 {
   this->mpXAxisSelectionWidget->populateTree(pModel, classes);
   this->mpYAxisSelectionWidget->populateTree(pModel, classes);
 }
void CCopasiPlotSelectionDialog::setOutputVectors (std::vector< const CCopasiObject * > * outputVector1, std::vector< const CCopasiObject * > * outputVector2)
Definition at line 162 of file CCopasiPlotSelectionDialog.cpp.
References mpXAxisOutputVector, mpXAxisSelectionWidget, mpYAxisOutputVector, mpYAxisSelectionWidget, and CCopasiSelectionWidget::setOutputVector().
Referenced by CQPlotSubwidget::addCurve2D().
 {
   this->mpXAxisOutputVector = outputVector1;
   this->mpXAxisSelectionWidget->setOutputVector(this->mpXAxisOutputVector);
   this->mpYAxisOutputVector = outputVector2;
   this->mpYAxisSelectionWidget->setOutputVector(this->mpYAxisOutputVector);
 }
void CCopasiPlotSelectionDialog::setTabOrder () protected
Definition at line 106 of file CCopasiPlotSelectionDialog.cpp.
References mpExpertCheckBox, mpXAxisSelectionWidget, and mpYAxisSelectionWidget.
Referenced by CCopasiPlotSelectionDialog().
 {
   QWidget::setTabOrder(this->mpExpertCheckBox, this->mpXAxisSelectionWidget);
   QWidget::setTabOrder(this->mpXAxisSelectionWidget, this->mpYAxisSelectionWidget);
   this->mpXAxisSelectionWidget->setFocus();
 }
void CCopasiPlotSelectionDialog::slotCancelButtonClicked () protected slot
Definition at line 151 of file CCopasiPlotSelectionDialog.cpp.
Referenced by CCopasiPlotSelectionDialog().
 {
   QDialog::done(QDialog::Rejected);
 }
void CCopasiPlotSelectionDialog::slotExpertCheckBoxToggled (bool checked) protected slot
Definition at line 156 of file CCopasiPlotSelectionDialog.cpp.
References mpXAxisSelectionWidget, mpYAxisSelectionWidget, and CCopasiSelectionWidget::setExpertMode().
Referenced by CCopasiPlotSelectionDialog().
 {
   this->mpXAxisSelectionWidget->setExpertMode(checked);
   this->mpYAxisSelectionWidget->setExpertMode(checked);
 }
void CCopasiPlotSelectionDialog::slotOKButtonClicked () protected slot
Definition at line 113 of file CCopasiPlotSelectionDialog.cpp.
References CCopasiSelectionWidget::commit(), FROM_UTF8, mpXAxisOutputVector, mpXAxisSelectionWidget, mpYAxisOutputVector, mpYAxisSelectionWidget, and CQMessageBox::question().
Referenced by CCopasiPlotSelectionDialog().
 {
   // fill the selection vectors
   this->mpXAxisSelectionWidget->commit();
   this->mpYAxisSelectionWidget->commit();
   std::string message = "";
   bool showWarning = false;
   if (this->mpXAxisOutputVector->empty())
     {
       message += "X Axis";
       showWarning = true;
     }
   if (this->mpYAxisOutputVector->empty())
     {
       if (showWarning)
         {
           message += " and ";
         }
       showWarning = true;
       message += "Y Axis";
     }
   if (showWarning)
     {
       message = "You did not select anything for the " + message + "!\nDo you want to proceed anyway?";
       if (CQMessageBox::question(this, "Empty Selection", FROM_UTF8(message), QMessageBox::Yes | QMessageBox::No, QMessageBox::Yes) == QMessageBox::No)
         {
           return;
         }
     }
   QDialog::done(QDialog::Accepted);
 }
Member Data Documentation
QHBoxLayout* CCopasiPlotSelectionDialog::mpButtonBox protected
Definition at line 61 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
QCheckBox* CCopasiPlotSelectionDialog::mpExpertCheckBox protected
Definition at line 57 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog(), and setTabOrder().
QVBoxLayout* CCopasiPlotSelectionDialog::mpMainLayout protected
Definition at line 62 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
QSplitter* CCopasiPlotSelectionDialog::mpSplitter protected
Definition at line 60 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
QLabel* CCopasiPlotSelectionDialog::mpXAxisLabel protected
Definition at line 63 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
std::vector< const CCopasiObject * >* CCopasiPlotSelectionDialog::mpXAxisOutputVector protected
Definition at line 67 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog(), setOutputVectors(), and slotOKButtonClicked().
QWidget* CCopasiPlotSelectionDialog::mpXAxisSelectionBox protected
Definition at line 65 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
CCopasiSelectionWidget* CCopasiPlotSelectionDialog::mpXAxisSelectionWidget protected
Definition at line 58 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog(), setModel(), setOutputVectors(), setTabOrder(), slotExpertCheckBoxToggled(), and slotOKButtonClicked().
QLabel* CCopasiPlotSelectionDialog::mpYAxisLabel protected
Definition at line 64 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
std::vector< const CCopasiObject * >* CCopasiPlotSelectionDialog::mpYAxisOutputVector protected
Definition at line 68 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog(), setOutputVectors(), and slotOKButtonClicked().
QWidget* CCopasiPlotSelectionDialog::mpYAxisSelectionBox protected
Definition at line 66 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog().
CCopasiSelectionWidget* CCopasiPlotSelectionDialog::mpYAxisSelectionWidget protected
Definition at line 59 of file CCopasiPlotSelectionDialog.h.
Referenced by CCopasiPlotSelectionDialog(), setModel(), setOutputVectors(), setTabOrder(), slotExpertCheckBoxToggled(), and slotOKButtonClicked().
The documentation for this class was generated from the following files:
CCopasiPlotSelectionDialog.h
CCopasiPlotSelectionDialog.cpp