COPASI API: SliderDialog Class Reference
SliderDialog Class Reference
#include <SliderDialog.h>
Public Member Functions
void addSlider (CSlider *slider)
void clear ()
virtual QMenu * getWindowMenu () const
bool isChanged () const
void reset ()
void setChanged (bool changed)
void setCurrentFolderId (size_t id)
void setFramework (int index)
void setParentWindow (CopasiUI3Window *pPW)
SliderDialog (QWidget *parent, const char *name=0, bool modal=false, Qt::WFlags fl=0)
virtual void updateAllSliders ()
virtual ~SliderDialog ()
Public Member Functions inherited from CWindowInterface
void addToMainWindow (CopasiUI3Window *window=NULL)
CWindowInterface (QWidget *parent=NULL, Qt::WindowFlags flags=NULL)
void removeFromMainWindow (CopasiUI3Window *window=NULL)
virtual void saveToFile (const QString &fileName) const
virtual ~CWindowInterface ()
Protected Slots
void createNewSlider ()
void deleteSlider (CopasiSlider *pSlider)
void editSlider (CopasiSlider *slider)
void editSlider ()
void removeSlider (CopasiSlider *slider)
void removeSlider ()
void resetValue ()
void runTask ()
void setDefault ()
void sliderPressed ()
void sliderReleased ()
void sliderValueChanged ()
Protected Member Functions
virtual void changeEvent (QEvent *)
void clearSliderBox ()
virtual void closeEvent (QCloseEvent *e)
virtual void contextMenuEvent (QContextMenuEvent *e)
void createSlidersForFolder (std::vector< QWidget * > &v)
void deleteInvalidSliders ()
const CCopasiObject * determineCorrectObjectForSlider (const CCopasiObject *pObject)
CSlider * equivalentSliderExists (CSlider *pCSlider)
virtual bool eventFilter (QObject *, QEvent *event)
void fillSliderBox ()
CopasiSlider * findCopasiSliderAtPosition (const QPoint &p)
CopasiSlider * findCopasiSliderForCSlider (CSlider *pCSlider)
CopasiSlider * getCopasiSliderForCSlider (std::vector< QWidget * > &v, CSlider *slider)
CSlider * getCSliderForCopasiSlider (std::vector< CSlider * > &v, QWidget *slider)
std::vector< CSlider * > * getCSlidersForCurrentFolderId ()
std::vector< CSlider * > * getCSlidersForObject (CCopasiObject *pObject, std::vector< CSlider * > *pVector) const
virtual CCopasiTask * getTaskForFolderId (size_t folderId)
void init ()
size_t mapFolderId2EntryId (size_t folderId) const
virtual void runCrossSectionTask ()
virtual void runLNATask ()
virtual void runMCATask ()
virtual void runOptimizationTask ()
virtual void runParameterEstimationTask ()
virtual void runScanTask ()
virtual void runSteadyStateTask ()
virtual void runTimeCourse ()
bool setCorrectSliderObject (CopasiSlider *pSlider)
void setCurrentSlider (CopasiSlider *pSlider)
virtual void showEvent (QShowEvent *pEvent)
bool sliderObjectChanged (CSlider *pSlider) const
Protected Attributes
bool mChanged
size_t mCurrentFolderId
int mFramework
QAction * mpaCreateNewSlider
QAction * mpaEditSlider
QAction * mpaRemoveSlider
QAction * mpaResetValue
QAction * mpaSetDefault
QMenu * mpContextMenu
CopasiSlider * mpCurrSlider
CopasiUI3Window * mpParentWindow
std::map< size_t, std::vector
< QWidget * > > mSliderMap
bool mSliderPressed
bool mSliderValueChanged
std::map< size_t, void(SliderDialog::*)() > mTaskMap
Static Protected Attributes
static size_t folderMappings [][2]
static size_t numMappings = 14
Detailed Description
Definition at line 44 of file SliderDialog.h.
Constructor & Destructor Documentation
SliderDialog::SliderDialog (QWidget * parent, const char * name = 0, bool modal = false, Qt::WFlags fl = 0)
Definition at line 76 of file SliderDialog.cpp.
References CWindowInterface::addToMainWindow(), C_INVALID_INDEX, CQIconResource::copasi, createNewSlider(), editSlider(), CQIconResource::icon(), init(), mpaCreateNewSlider, mpaEditSlider, mpaRemoveSlider, mpaResetValue, mpaSetDefault, mpContextMenu, mpParentWindow, mSliderMap, mTaskMap, removeSlider(), resetValue(), runCrossSectionTask(), runLNATask(), runMCATask(), runOptimizationTask(), runParameterEstimationTask(), runScanTask(), runSteadyStateTask(), runTask(), runTimeCourse(), setCurrentFolderId(), and setDefault().
                                                                                     :
   CWindowInterface(parent, fl),
   mpParentWindow(NULL),
   mpContextMenu(NULL),
   mpCurrSlider(NULL),
   mSliderMap(),
   mTaskMap(),
   mCurrentFolderId(0),
   mSliderValueChanged(false),
   mSliderPressed(false),
   mFramework(0),
   mChanged(false)
 {
 #ifndef Darwin
   setWindowIcon(CQIconResource::icon(CQIconResource::copasi));
 #endif // not Darwin
   setupUi(this);
   addToMainWindow(mpParentWindow);
   setObjectName(QString::fromUtf8(name));
   setWindowTitle("Slider Window");
   mpSliderBox->layout()->addItem(new QSpacerItem(0, 5, QSizePolicy::Minimum, QSizePolicy::Expanding));
   this->mpContextMenu = new QMenu(this);
   mpaCreateNewSlider = this->mpContextMenu->addAction("Add New Slider", this, SLOT(createNewSlider()));
   mpaRemoveSlider = this->mpContextMenu->addAction("Remove Slider", this, SLOT(removeSlider()));
   mpaEditSlider = this->mpContextMenu->addAction("Edit Slider", this, SLOT(editSlider()));
   mpaResetValue = this->mpContextMenu->addAction("Reset Value", this, SLOT(resetValue()));
   mpaSetDefault = this->mpContextMenu->addAction("Set new default value", this, SLOT(setDefault()));
   this->mSliderMap[C_INVALID_INDEX].push_back(new QLabel("<p>There are no sliders available for this task. If you select one of the tasks that supports sliders in the copasi object tree, this dialog will become active.</p>", mpSliderBox));
   this->mTaskMap[23] = &SliderDialog::runTimeCourse;
   this->mTaskMap[21] = &SliderDialog::runSteadyStateTask;
   this->mTaskMap[31] = &SliderDialog::runScanTask;
   this->mTaskMap[24] = &SliderDialog::runMCATask;
   this->mTaskMap[35] = &SliderDialog::runLNATask;
   this->mTaskMap[33] = &SliderDialog::runParameterEstimationTask;
   this->mTaskMap[32] = &SliderDialog::runOptimizationTask;
   this->mTaskMap[28] = &SliderDialog::runCrossSectionTask;
   connect(this->mpRunTaskButton, SIGNAL(clicked()), this, SLOT(runTask()));
   connect(this->mpNewSliderButton, SIGNAL(clicked()), this, SLOT(createNewSlider()));
   this->setCurrentFolderId(C_INVALID_INDEX);
   init();
 }
SliderDialog::~SliderDialog () virtual
Definition at line 371 of file SliderDialog.cpp.
References clear(), mpParentWindow, and CWindowInterface::removeFromMainWindow().
 {
   this->clear();
   removeFromMainWindow(mpParentWindow);
   delete mpRunTaskButton;
   delete mpAutoRunCheckBox;
   delete mpAutoModifyRangesCheckBox;
   delete mpSliderBox;
   delete mpScrollView;
 }
Member Function Documentation
void SliderDialog::addSlider (CSlider * slider)
Definition at line 408 of file SliderDialog.cpp.
References CCopasiVector< T >::add(), CSlider::compile(), editSlider(), equivalentSliderExists(), findCopasiSliderForCSlider(), CopasiUI3Window::getDataModel(), CCopasiRootContainer::getDatamodelList(), SCopasiXMLGUI::getSliderList(), mChanged, mCurrentFolderId, mpCurrSlider, mpParentWindow, mSliderMap, removeSlider(), setCorrectSliderObject(), setCurrentSlider(), sliderPressed(), sliderReleased(), sliderValueChanged(), and CopasiSlider::updateSliderData().
Referenced by createNewSlider(), and editSlider().
 {
   if (mpParentWindow == NULL)
     return;
   // check if there already is a slider for this  object
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   SCopasiXMLGUI* pGUI = (*CCopasiRootContainer::getDatamodelList())[0]->getGUI();
   assert(pGUI);
   if (!equivalentSliderExists(pSlider))
     {
       std::vector<CCopasiContainer*> listOfContainers;
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       listOfContainers.push_back((*CCopasiRootContainer::getDatamodelList())[0]->getModel());
       pSlider->compile(listOfContainers);
       pGUI->getSliderList()->add(pSlider, true);
     }
   CopasiSlider* tmp = findCopasiSliderForCSlider(pSlider);
   if (!tmp)
     {
       setCurrentSlider(new CopasiSlider(pSlider, mpParentWindow->getDataModel(), mpSliderBox));
       mpCurrSlider->installEventFilter(this);
       mpCurrSlider->setHidden(true);
       mpCurrSlider->updateSliderData();
       // make sure the slider points to the correct object
       // for the currently set framework
       this->setCorrectSliderObject(this->mpCurrSlider);
       mSliderMap[mCurrentFolderId].push_back(mpCurrSlider);
       QBoxLayout* layout = static_cast<QBoxLayout*>(mpSliderBox->layout());
       int childCount = layout->count() - 1;
       layout->insertWidget(childCount, mpCurrSlider);
       connect(mpCurrSlider, SIGNAL(valueChanged(double)), this , SLOT(sliderValueChanged()));
       connect(mpCurrSlider, SIGNAL(sliderReleased()), this, SLOT(sliderReleased()));
       connect(mpCurrSlider, SIGNAL(sliderPressed()), this, SLOT(sliderPressed()));
       connect(mpCurrSlider, SIGNAL(closeClicked(CopasiSlider*)), this, SLOT(removeSlider(CopasiSlider*)));
       connect(mpCurrSlider, SIGNAL(editClicked(CopasiSlider*)), this, SLOT(editSlider(CopasiSlider*)));
       mpCurrSlider->setHidden(false);
       mChanged = true;
     }
   else
     {
       mpCurrSlider = tmp;
     }
 }
void SliderDialog::changeEvent (QEvent * event) protected virtual
Definition at line 1074 of file SliderDialog.cpp.
References CopasiSlider::focusSlider(), and mpCurrSlider.
 {
   if (event->type() == QEvent::EnabledChange && isEnabled() && mpCurrSlider != NULL)
     {
       setFocus(Qt::OtherFocusReason);
       mpScrollView->setFocus(Qt::OtherFocusReason);
       mpSliderBox->setFocus(Qt::OtherFocusReason);
       mpCurrSlider->focusSlider();
     }
 }
void SliderDialog::clear ()
Deletes all exisiting sliders.
Definition at line 382 of file SliderDialog.cpp.
References clearSliderBox(), mSliderMap, and pdelete.
Referenced by reset(), and ~SliderDialog().
 {
   this->clearSliderBox();
   size_t j, maxWidgets;
   std::map< size_t, std::vector< QWidget* > >::iterator it = mSliderMap.begin();
   while (it != mSliderMap.end())
     {
       std::vector<QWidget*> v = it->second;
       maxWidgets = v.size();
       for (j = 0; j < maxWidgets; ++j)
         {
           pdelete(v[j]);
         }
       ++it;
     }
   this->mSliderMap.clear();
 }
void SliderDialog::clearSliderBox () protected
Definition at line 1043 of file SliderDialog.cpp.
References mCurrentFolderId, and mSliderMap.
Referenced by clear(), and setCurrentFolderId().
 {
   std::vector<QWidget*> v = mSliderMap[mCurrentFolderId];
   std::vector<QWidget*>::const_reverse_iterator it;
   for (it = v.rbegin(); it != v.rend(); ++it)
     {
       QWidget* widget = *it;
       widget->setHidden(true);
       mpSliderBox->layout()->removeWidget(widget);
     }
 }
void SliderDialog::closeEvent (QCloseEvent * e) protected virtual
Definition at line 867 of file SliderDialog.cpp.
References mpParentWindow, and CopasiUI3Window::slotShowSliders().
 {
   CWindowInterface::closeEvent(e);
   if (mpParentWindow)
     {
       mpParentWindow->slotShowSliders(false);
     }
 }
void SliderDialog::contextMenuEvent (QContextMenuEvent * e) protected virtual
Definition at line 126 of file SliderDialog.cpp.
References findCopasiSliderAtPosition(), mpaCreateNewSlider, mpaEditSlider, mpaRemoveSlider, mpContextMenu, and setCurrentSlider().
 {
   CopasiSlider* pSlider = findCopasiSliderAtPosition(e->pos());
   if (pSlider)
     {
       mpaCreateNewSlider->setEnabled(false);
       mpaRemoveSlider->setEnabled(true);
       mpaEditSlider->setEnabled(true);
       setCurrentSlider(pSlider);
     }
   else
     {
       mpaCreateNewSlider->setEnabled(true);
       mpaRemoveSlider->setEnabled(false);
       mpaEditSlider->setEnabled(false);
     }
   mpContextMenu->popup(e->globalPos());
 }
void SliderDialog::createNewSlider () protected slot
Definition at line 171 of file SliderDialog.cpp.
References addSlider(), CSlider::compile(), determineCorrectObjectForSlider(), equivalentSliderExists(), findCopasiSliderForCSlider(), getCSlidersForCurrentFolderId(), CCopasiRootContainer::getDatamodelList(), CCopasiObject::getKey(), CCopasiSelectionDialog::getObjectVector(), getTaskForFolderId(), CQMessageBox::information(), CQSimpleSelectionTree::InitialTime, mChanged, mCurrentFolderId, CQSimpleSelectionTree::Parameters, CSlider::resetRange(), CSlider::setAssociatedEntityKey(), CSlider::setSliderObject(), and CopasiSlider::updateSliderData().
Referenced by SliderDialog().
 {
   // allow the user to create more than one slider
   std::vector<const CCopasiObject*> objects = CCopasiSelectionDialog::getObjectVector(this,
       CQSimpleSelectionTree::InitialTime |
       CQSimpleSelectionTree::Parameters);
   std::vector<CSlider*>* pVector = getCSlidersForCurrentFolderId();
   std::vector<const CCopasiObject*>::const_iterator it = objects.begin(), endit = objects.end();
   bool yesToAll = false;
   bool noToAll = false;
   // create the sliders for all the selected objects
   // first we need the task object because we need it later to associate the
   // later with the correct task
   CCopasiObject* object = (CCopasiObject*)getTaskForFolderId(mCurrentFolderId);
   if (!object) return;
   CCopasiObject* pTmpObject = NULL;
   while (it != endit)
     {
       // create a new slider
       assert((*it) != NULL);
       pTmpObject = const_cast<CCopasiObject*>(determineCorrectObjectForSlider(*it));
       CSlider* pCSlider = new CSlider("slider", (*CCopasiRootContainer::getDatamodelList())[0]);
       if (pCSlider)
         {
           pCSlider->setSliderObject(pTmpObject);
           pCSlider->setAssociatedEntityKey(object->getKey());
           // check if a slider for that object already exists and if so, prompt
           // the user what to do
           CSlider* pEquivalentSlider = equivalentSliderExists(pCSlider);
           if (pEquivalentSlider != NULL)
             {
               CopasiSlider* pCopasiSlider = NULL;
               // if the user has specified yesToAll, we reset the ranges of all
               // duplicate sliders
               if (yesToAll)
                 {
                   pEquivalentSlider->resetRange();
                   // update the slider widget
                   pCopasiSlider = findCopasiSliderForCSlider(pEquivalentSlider);
                   assert(pCopasiSlider != NULL);
                   if (pCopasiSlider != NULL)
                     {
                       pCopasiSlider->updateSliderData();
                     }
                 }
               // if the user has not specified noToAll, we need to prompt
               else if (!noToAll)
                 {
                   QMessageBox::StandardButton result = CQMessageBox::information(NULL, "Slider Exists",
                                                        "A slider for this object already exists.\n\nDo you want to reset the range of the slider?",
                                                        QMessageBox::Yes | QMessageBox::No | QMessageBox::YesToAll | QMessageBox::NoToAll, QMessageBox::No);
                   // check the answer and maybe set some flags
                   switch (result)
                     {
                       case QMessageBox::YesToAll:
                         // set the flag
                         yesToAll = true;
                       case QMessageBox::Yes:
                         // reset the range
                         pEquivalentSlider->resetRange();
                         // update the slider widget
                         pCopasiSlider = findCopasiSliderForCSlider(pEquivalentSlider);
                         assert(pCopasiSlider != NULL);
                         if (pCopasiSlider != NULL)
{
                             pCopasiSlider->updateSliderData();
                           }
                         break;
                       case QMessageBox::NoToAll:
                         // set the flag
                         noToAll = true;
                         break;
                       case QMessageBox::No:
                         // do nothing else
                         break;
                       default:
                         // do nothing
                         break;
                     }
                 }
               delete pCSlider;
             }
           else
             {
               std::vector<CCopasiContainer*> listOfContainers;
               assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
               listOfContainers.push_back((*CCopasiRootContainer::getDatamodelList())[0]->getModel());
               pCSlider->compile(listOfContainers);
               pCSlider->resetRange();
               addSlider(pCSlider);
               mChanged = true;
             }
         }
       ++it;
     }
   delete pVector;
 }
void SliderDialog::createSlidersForFolder (std::vector< QWidget * > & v) protected
Definition at line 600 of file SliderDialog.cpp.
References C_INVALID_INDEX, deleteSlider(), editSlider(), getCopasiSliderForCSlider(), getCSliderForCopasiSlider(), getCSlidersForCurrentFolderId(), CopasiUI3Window::getDataModel(), CQMessageBox::information(), mChanged, mCurrentFolderId, mpCurrSlider, mpParentWindow, mSliderMap, removeSlider(), setCorrectSliderObject(), setCurrentSlider(), sliderPressed(), sliderReleased(), and sliderValueChanged().
Referenced by fillSliderBox().
 {
   if (mCurrentFolderId == C_INVALID_INDEX)
     return;
   std::vector<CSlider*>* pVector = getCSlidersForCurrentFolderId();
   std::vector<CSlider*>::const_iterator it;
   std::vector<QWidget*>::const_iterator wIt;
   // maybe other program parts have added or deleted some sliders
   assert(pVector);
   // add CopasiSlider for all CSliders that don't have one.
   bool issueWarning = false;
   for (it = pVector->begin(); it != pVector->end(); ++it)
     {
       //bool found = false;
       // check whether we have a slider
       CopasiSlider* pTmpSlider = getCopasiSliderForCSlider(v, *it);
       if (pTmpSlider != NULL) continue;
       // if not create one
       setCurrentSlider(new CopasiSlider(*it, mpParentWindow->getDataModel(), mpSliderBox));
       // make sure the slider points to the correct object
       // for the currently set framework
       this->setCorrectSliderObject(this->mpCurrSlider);
       connect(mpCurrSlider, SIGNAL(valueChanged(double)), this , SLOT(sliderValueChanged()));
       connect(mpCurrSlider, SIGNAL(sliderReleased()), this, SLOT(sliderReleased()));
       connect(mpCurrSlider, SIGNAL(sliderPressed()), this, SLOT(sliderPressed()));
       connect(mpCurrSlider, SIGNAL(closeClicked(CopasiSlider*)), this, SLOT(removeSlider(CopasiSlider*)));
       connect(mpCurrSlider, SIGNAL(editClicked(CopasiSlider*)), this, SLOT(editSlider(CopasiSlider*)));
       mpCurrSlider->installEventFilter(this);
       mpCurrSlider->setHidden(true);
       mSliderMap[mCurrentFolderId].push_back(mpCurrSlider);
     }
   // delete CopasiSliders which have no correponding CSlider
   for (wIt = v.begin(); wIt != v.end(); ++wIt)
     {
       bool found = getCSliderForCopasiSlider(*pVector, *wIt) != NULL;
       if (!found)
         {
           CopasiSlider* pTmpSlider = dynamic_cast<CopasiSlider*>(*wIt);
           assert(pTmpSlider);
           deleteSlider(pTmpSlider);
           mChanged = true;
         }
     }
   if (issueWarning)
     {
       CQMessageBox::information(NULL, "Invalid Slider",
                                 "One or more sliders are invalid and have been disabled!",
                                 QMessageBox::Ok, QMessageBox::NoButton);
     }
   delete pVector;
 }
void SliderDialog::deleteInvalidSliders () protected
Deletes all sliders for the current folder id that are no longer valid.
Definition at line 1268 of file SliderDialog.cpp.
References CQMessageBox::information(), CopasiSlider::isValid(), mCurrentFolderId, mSliderMap, and removeSlider().
Referenced by fillSliderBox(), and updateAllSliders().
 {
   std::vector<QWidget*> &v = mSliderMap[mCurrentFolderId];
   std::vector<QWidget*>::iterator wit = v.begin(), wendit = v.end();
   bool sliderDeleted = false;
   CopasiSlider* pCopasiSlider = NULL;
   while (wit != wendit)
     {
       pCopasiSlider = dynamic_cast<CopasiSlider*>(*wit);
       if (pCopasiSlider && !pCopasiSlider->isValid())
         {
           // we need to remove the slider
           this->removeSlider(pCopasiSlider);
           wit = v.erase(wit);
           wendit = v.end();
           sliderDeleted = true;
           continue;
         }
       ++wit;
     }
   if (sliderDeleted)
     {
       CQMessageBox::information(NULL, "Invalid Slider",
                                 "One or more sliders are invalid and have been deleted!",
                                 QMessageBox::Ok, QMessageBox::NoButton);
     }
 }
void SliderDialog::deleteSlider (CopasiSlider * pSlider) protected slot
Definition at line 312 of file SliderDialog.cpp.
References mChanged, mCurrentFolderId, mSliderMap, and pdelete.
Referenced by createSlidersForFolder(), and removeSlider().
 {
   if (pSlider)
     {
       std::vector<QWidget*>* v = &mSliderMap[mCurrentFolderId];
       std::vector<QWidget*>::iterator it = v->begin();
       std::vector<QWidget*>::iterator end = v->end();
       while (it != end)
         {
           if (*it == pSlider)
             {
               break;
             }
           ++it;
         }
       assert(it != end);
       v->erase(it);
       mpSliderBox->layout()->removeWidget(pSlider);
       pdelete(pSlider);
       mChanged = true;
     }
 }
const CCopasiObject * SliderDialog::determineCorrectObjectForSlider (const CCopasiObject * pObject) protected
Definition at line 1126 of file SliderDialog.cpp.
References CMetab::getInitialConcentrationReference(), CModelEntity::getInitialValueReference(), CMetab::isInitialConcentrationChangeAllowed(), mFramework, and pResult.
Referenced by createNewSlider(), and setCorrectSliderObject().
 {
   const CCopasiObject* pResult = NULL;
   if (pObject == NULL)
     {
       pResult = NULL;
     }
   else
     {
       CMetab* pMetab = dynamic_cast<CMetab*>((pObject)->getObjectParent());
       // we just assume the object is correct for the framework
       // this saves some additional test later on
       pResult = pObject;
       if (pMetab != NULL)
         {
           // now we have to check if the framework is the concentrations framework
           // and if we are actually allowed to change the concentration on a metabolite
           if (mFramework == 0)
             {
               // we are in the concentrations framework
               //
               // sometimes it is not allowed to change the concentration of a metabolite
               // because it would change the volume of the compartment
               if (pMetab->isInitialConcentrationChangeAllowed() && pObject == pMetab->getInitialValueReference())
                 {
                   // if the current object is for the concentration, we return a new object to the amount
                   pResult = pMetab->getInitialConcentrationReference();
                   assert(pResult != NULL);
                 }
             }
           else
             {
               // we are in the particle number framework
               // if the object is for the amount, we leave it, otherwise we
               // return a new object for the amount
               if (pObject == pMetab->getInitialConcentrationReference())
                 {
                   pResult = pMetab->getInitialValueReference();
                   assert(pResult != NULL);
                 }
             }
         }
     }
   return pResult;
 }
void SliderDialog::editSlider (CopasiSlider * slider) protected slot
Definition at line 990 of file SliderDialog.cpp.
References editSlider(), and setCurrentSlider().
 {
   setCurrentSlider(slider);
   editSlider();
 }
void SliderDialog::editSlider () protected slot
Definition at line 338 of file SliderDialog.cpp.
References addSlider(), CopasiSlider::getCSlider(), getCSlidersForCurrentFolderId(), CCopasiRootContainer::getDatamodelList(), SliderSettingsDialog::getSlider(), getTaskForFolderId(), mCurrentFolderId, mpCurrSlider, SliderSettingsDialog::setDefinedSliders(), SliderSettingsDialog::setModel(), SliderSettingsDialog::setSlider(), and CopasiSlider::updateSliderData().
Referenced by addSlider(), createSlidersForFolder(), editSlider(), and SliderDialog().
 {
   SliderSettingsDialog* pSettingsDialog = new SliderSettingsDialog(this);
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pSettingsDialog->setModel((*CCopasiRootContainer::getDatamodelList())[0]->getModel());
   // set the list of sliders that is already known
   CCopasiObject* object = (CCopasiObject*)getTaskForFolderId(mCurrentFolderId);
   if (!object) return;
   std::vector<CSlider*>* pVector = getCSlidersForCurrentFolderId();
   pSettingsDialog->setDefinedSliders(*pVector);
   //pSettingsDialog->disableObjectChoosing(true);
   pSettingsDialog->setSlider(mpCurrSlider->getCSlider());
   if (pSettingsDialog->exec() == QDialog::Accepted)
     {
       addSlider(pSettingsDialog->getSlider());
       mpCurrSlider->updateSliderData();
       /*
       if ((!mpCurrSlider->isEnabled()) && mpCurrSlider->getCSlider()->compile())
         {
           mpCurrSlider->setEnabled(true);
         }
         */
     }
   delete pSettingsDialog;
   delete pVector;
 }
CSlider * SliderDialog::equivalentSliderExists (CSlider * pCSlider) protected
Definition at line 456 of file SliderDialog.cpp.
References CSlider::getAssociatedEntityKey(), CCopasiRootContainer::getDatamodelList(), SCopasiXMLGUI::getSliderList(), CSlider::getSliderObject(), pResult, and CCopasiVector< T >::size().
Referenced by addSlider(), and createNewSlider().
 {
   CSlider* pResult = NULL;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   SCopasiXMLGUI* pGUI = (*CCopasiRootContainer::getDatamodelList())[0]->getGUI();
   assert(pGUI);
   size_t i, maxCount = pGUI->getSliderList()->size();
   for (i = 0; i < maxCount; ++i)
     {
       CSlider* pTmpSlider = (*(pGUI->getSliderList()))[i];
       if (pTmpSlider->getSliderObject() == pCSlider->getSliderObject() && pTmpSlider->getAssociatedEntityKey() == pCSlider->getAssociatedEntityKey())
         {
           pResult = pTmpSlider;
           break;
         }
     }
   return pResult;
 }
bool SliderDialog::eventFilter (QObject * , QEvent * event) protected virtual
Definition at line 1085 of file SliderDialog.cpp.
References findCopasiSliderAtPosition(), and setCurrentSlider().
 {
   QMouseEvent* pQME = dynamic_cast<QMouseEvent*>(event);
   if (pQME && pQME->type() == QEvent::MouseButtonPress && pQME->button() == Qt::LeftButton)
     {
       CopasiSlider* pSlider = findCopasiSliderAtPosition(mapFromGlobal(pQME->globalPos()));
       assert(pSlider);
       setCurrentSlider(pSlider);
     }
   return false;
 }
void SliderDialog::fillSliderBox () protected
Definition at line 662 of file SliderDialog.cpp.
References createSlidersForFolder(), deleteInvalidSliders(), CModelEntity::getInitialExpression(), CCopasiObject::getObjectParent(), mCurrentFolderId, mpCurrSlider, mpParentWindow, mSliderMap, CopasiSlider::object(), setCurrentSlider(), and CopasiSlider::updateSliderData().
Referenced by setCurrentFolderId().
 {
   if (mpParentWindow == NULL)
     return;
   this->deleteInvalidSliders();
   std::vector<QWidget*> v = mSliderMap[mCurrentFolderId];
   createSlidersForFolder(v);
   v = mSliderMap[mCurrentFolderId];
   size_t i, maxCount = v.size();
   for (i = maxCount; i != 0; --i)
     {
       QWidget* widget = v[i - 1];
       widget->setHidden(true);
       static_cast<QBoxLayout*>(mpSliderBox->layout())->insertWidget(0, widget);
       setCurrentSlider(dynamic_cast<CopasiSlider*>(widget));
       if (mpCurrSlider)
         {
           // check if the slider value is determined by an expression
           CModelEntity* pME = dynamic_cast<CModelEntity*>(this->mpCurrSlider->object()->getObjectParent());
           if (pME != NULL)
             {
               if (!pME->getInitialExpression().empty())
                 {
                   // we have to disable the slider widget and set a tooltip
                   // that explains why this slider is disabled
                   if (this->mpCurrSlider->isEnabled())
                     {
                       this->mpCurrSlider->setEnabled(false);
                       this->mpCurrSlider->setToolTip("This value is determined by an initial expression.");
                     }
                 }
               else
                 {
                   // if the slider is disabled, we have to enable it and delete the tooltip
                   if (!this->mpCurrSlider->isEnabled())
                     {
                       this->mpCurrSlider->setEnabled(true);
                       this->mpCurrSlider->setToolTip("");
                     }
                 }
             }
           mpCurrSlider->updateSliderData();
         }
       widget->setHidden(false);
     }
 }
CopasiSlider * SliderDialog::findCopasiSliderAtPosition (const QPoint & p) protected
Definition at line 157 of file SliderDialog.cpp.
Referenced by contextMenuEvent(), and eventFilter().
 {
   QWidget* pWidget = childAt(p);
   CopasiSlider* pSlider = NULL;
   while (pWidget && pWidget != this && !pSlider)
     {
       pSlider = dynamic_cast<CopasiSlider*>(pWidget);
       pWidget = (QWidget*)pWidget->parent();
     }
   return pSlider;
 }
CopasiSlider * SliderDialog::findCopasiSliderForCSlider (CSlider * pCSlider) protected
Definition at line 478 of file SliderDialog.cpp.
References CopasiSlider::getCSlider(), mCurrentFolderId, mSliderMap, and pResult.
Referenced by addSlider(), and createNewSlider().
 {
   CopasiSlider* pResult = NULL;
   std::vector<QWidget*> v = mSliderMap[mCurrentFolderId];
   size_t i, maxCount = v.size();
   CopasiSlider* pTmpSlider;
   for (i = 0; i < maxCount; ++i)
     {
       pTmpSlider = dynamic_cast<CopasiSlider*>(v[i]);
       if (!pTmpSlider) break;
       if (pTmpSlider->getCSlider() == pCSlider)
         {
           pResult = pTmpSlider;
           break;
         }
     }
   return pResult;
 }
CopasiSlider * SliderDialog::getCopasiSliderForCSlider (std::vector< QWidget * > & v, CSlider * slider) protected
Definition at line 581 of file SliderDialog.cpp.
References CopasiSlider::getCSlider().
Referenced by createSlidersForFolder().
 {
   std::vector<QWidget*>::const_iterator it;
   for (it = v.begin(); it != v.end(); ++it)
     {
       CopasiSlider* pTmpSlider = dynamic_cast<CopasiSlider*>(*it);
       if (!pTmpSlider) break;
       if (pTmpSlider->getCSlider() == slider)
         {
           return pTmpSlider;
         }
     }
   return NULL;
 }
CSlider * SliderDialog::getCSliderForCopasiSlider (std::vector< CSlider * > & v, QWidget * slider) protected
Definition at line 562 of file SliderDialog.cpp.
References CopasiSlider::getCSlider().
Referenced by createSlidersForFolder().
 {
   CopasiSlider* pTmpSlider = dynamic_cast<CopasiSlider*>(slider);
   if (!pTmpSlider) return NULL;
   std::vector<CSlider*>::const_iterator it;
   for (it = v.begin(); it != v.end(); ++it)
     {
       if (pTmpSlider->getCSlider() == *it)
         {
           return *it;
         }
     }
   return NULL;
 }
std::vector< CSlider * > * SliderDialog::getCSlidersForCurrentFolderId () protected
Definition at line 1056 of file SliderDialog.cpp.
References getCSlidersForObject(), getTaskForFolderId(), and mCurrentFolderId.
Referenced by createNewSlider(), createSlidersForFolder(), and editSlider().
 {
   CCopasiObject* object = (CCopasiObject*)getTaskForFolderId(mCurrentFolderId);
   if (!object) return NULL;
   std::vector<CSlider*>* pVector = new std::vector<CSlider*>();
   try
     {
       pVector = getCSlidersForObject(object, pVector);
     }
   catch (...) {}
   return pVector;
 }
std::vector< CSlider * > * SliderDialog::getCSlidersForObject (CCopasiObject * pObject, std::vector< CSlider * > * pVector) const protected
Definition at line 996 of file SliderDialog.cpp.
References CSlider::compile(), CSlider::getAssociatedEntityKey(), CCopasiRootContainer::getDatamodelList(), CCopasiDataModel::getGUI(), CModel::getKey(), CCopasiObject::getKey(), CCopasiDataModel::getModel(), SCopasiXMLGUI::getSliderList(), CQMessageBox::information(), CCopasiVector< T >::remove(), CCopasiVector< T >::size(), and sliderObjectChanged().
Referenced by getCSlidersForCurrentFolderId().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   SCopasiXMLGUI* pGUI = pDataModel->getGUI();
   assert(pGUI);
   bool sliderDeleted = false;
   CCopasiVector<CSlider>* pSliderList = pGUI->getSliderList();
   assert(pSliderList);
   // go through the list in reverse so that items can be deleted
   size_t i, iMax = pSliderList->size();
   bool issueWarning = false;
   for (i = iMax; i > 0; --i)
     {
       CSlider* pSlider = (*pSliderList)[i - 1];
       if (sliderObjectChanged(pSlider))
         {
           if (!sliderDeleted)
             {
               CQMessageBox::information(NULL, "Missing slider objects",
                                         "One or more objects that had sliders defined have been deleted. Sliders will therefore be deleted as well.",
                                         QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
             }
           pSliderList->remove(i - 1);
           sliderDeleted = true;
         }
       else
         {
           if (pSlider->getAssociatedEntityKey() == pDataModel->getModel()->getKey() || pSlider->getAssociatedEntityKey() == pObject->getKey())
             {
               if (!pSlider->compile())
                 {
                   issueWarning = true;
                 }
               pVector->insert(pVector->begin(), pSlider);
             }
         }
     }
   return pVector;
 }
CCopasiTask * SliderDialog::getTaskForFolderId (size_t folderId) protected virtual
Definition at line 877 of file SliderDialog.cpp.
References CCopasiRootContainer::getDatamodelList(), and mapFolderId2EntryId().
Referenced by createNewSlider(), editSlider(), and getCSlidersForCurrentFolderId().
 {
   folderId = mapFolderId2EntryId(folderId);
   CCopasiTask* task = NULL;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   switch (folderId)
     {
       case 21:
         task = dynamic_cast<CSteadyStateTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Steady-State"]);
         break;
       case 23:
         task = dynamic_cast<CTrajectoryTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time-Course"]);
         break;
       case 24:
         task = dynamic_cast<CMCATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Metabolic Control Analysis"]);
         break;
       case 31:
         task = dynamic_cast<CScanTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Scan"]);
         break;
       case 35:
         task = dynamic_cast<CLNATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Linear Noise Approximation"]);
         break;
       case 33:
         task = dynamic_cast<CFitTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Parameter Estimation"]);
         break;
       case 32:
         task = dynamic_cast<COptTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Optimization"]);
         break;
       case 28:
         task = dynamic_cast<CCrossSectionTask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Cross Section"]);
         break;
       default:
         task = NULL;
         break;
     }
   return task;
 }
QMenu * SliderDialog::getWindowMenu () const virtual
Implements CWindowInterface.
Definition at line 1325 of file SliderDialog.cpp.
 {
   return mpWindowMenu;
 }
void SliderDialog::init () protected
Definition at line 405 of file SliderDialog.cpp.
Referenced by SliderDialog().
 {}
bool SliderDialog::isChanged () const
Returns whether the slider dialog contains changes.
Definition at line 1315 of file SliderDialog.cpp.
References mChanged.
Referenced by CopasiUI3Window::importSBMLFromString(), CopasiUI3Window::newDoc(), CopasiUI3Window::slotFileOpen(), CopasiUI3Window::slotImportSBML(), and CopasiUI3Window::slotQuit().
 {
   return this->mChanged;
 }
size_t SliderDialog::mapFolderId2EntryId (size_t folderId) const protected
Definition at line 717 of file SliderDialog.cpp.
References C_INVALID_INDEX, folderMappings, and numMappings.
Referenced by getTaskForFolderId(), and setCurrentFolderId().
 {
   size_t id = C_INVALID_INDEX;
   size_t counter;
   for (counter = 0; counter < SliderDialog::numMappings; ++counter)
     {
       if (SliderDialog::folderMappings[counter][0] == folderId)
         {
           id = SliderDialog::folderMappings[counter][1];
           break;
         }
     }
   return id;
 }
void SliderDialog::removeSlider (CopasiSlider * slider) protected slot
Definition at line 984 of file SliderDialog.cpp.
References removeSlider(), and setCurrentSlider().
 {
   setCurrentSlider(slider);
   removeSlider();
 }
void SliderDialog::removeSlider () protected slot
Definition at line 288 of file SliderDialog.cpp.
References deleteSlider(), CopasiSlider::getCSlider(), CCopasiRootContainer::getDatamodelList(), mpCurrSlider, CCopasiVector< T >::remove(), and CCopasiVector< T >::size().
Referenced by addSlider(), createSlidersForFolder(), deleteInvalidSliders(), removeSlider(), and SliderDialog().
 {
   if (mpCurrSlider)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       CCopasiVector<CSlider>* pSliderList = (*CCopasiRootContainer::getDatamodelList())[0]->getGUI()->getSliderList();
       size_t i, maxCount = pSliderList->size();
       for (i = 0; i < maxCount; ++i)
         {
           CSlider* pTmpSlider = (*pSliderList)[i];
           if (pTmpSlider == mpCurrSlider->getCSlider())
             {
               pSliderList->remove(i);
               break;
             }
         }
       deleteSlider(mpCurrSlider);
       mpCurrSlider = NULL;
     }
 }
void SliderDialog::reset ()
Resets the SliderDialog to its initial state. It basically calls clear and readds the Label for the task widgets that don't support sliders.
Definition at line 1305 of file SliderDialog.cpp.
References C_INVALID_INDEX, clear(), and mSliderMap.
Referenced by CopasiUI3Window::newDoc(), CopasiUI3Window::slotFileOpen(), and CopasiUI3Window::slotImportSBML().
 {
   this->clear();
   assert(this->mSliderMap[C_INVALID_INDEX].size() == 0);
   this->mSliderMap[C_INVALID_INDEX].push_back(new QLabel("<p>There are no sliders available for this task.<br>If you select one of the tasks that supports<br>sliders in the copasi object tree, this dialog<br>will become active.</p>", NULL));
 }
void SliderDialog::resetValue () protected slot
Definition at line 1099 of file SliderDialog.cpp.
References mpCurrSlider, and CopasiSlider::resetValue().
Referenced by SliderDialog().
 {
   mpCurrSlider->resetValue();
 }
void SliderDialog::runCrossSectionTask () protected virtual
Definition at line 847 of file SliderDialog.cpp.
References CopasiWidget::enter(), ListViews::getCrossSectionWidget(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWidget(), mpParentWindow, and CQCrossSectionTaskWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getCrossSectionWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Cross Section"]->getKey());
       mpParentWindow->getMainWidget()->getCrossSectionWidget()->runTask();
     }
 }
void SliderDialog::runLNATask () protected virtual
Definition at line 827 of file SliderDialog.cpp.
References CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), ListViews::getLNAWidget(), CopasiUI3Window::getMainWidget(), mpParentWindow, and CQLNAWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getLNAWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Linear Noise Approximation"]->getKey());
       mpParentWindow->getMainWidget()->getLNAWidget()->runTask();
     }
 }
void SliderDialog::runMCATask () protected virtual
Definition at line 817 of file SliderDialog.cpp.
References CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWidget(), ListViews::getMCAWidget(), mpParentWindow, and CQMCAWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getMCAWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Metabolic Control Analysis"]->getKey());
       mpParentWindow->getMainWidget()->getMCAWidget()->runTask();
     }
 }
void SliderDialog::runOptimizationTask () protected virtual
Definition at line 857 of file SliderDialog.cpp.
References CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWidget(), ListViews::getOptimizationWidget(), mpParentWindow, and CQOptimizationWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getOptimizationWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Optimization"]->getKey());
       mpParentWindow->getMainWidget()->getOptimizationWidget()->runTask();
     }
 }
void SliderDialog::runParameterEstimationTask () protected virtual
Definition at line 837 of file SliderDialog.cpp.
References CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), ListViews::getFittingWidget(), CopasiUI3Window::getMainWidget(), mpParentWindow, and CQFittingWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getFittingWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Parameter Estimation"]->getKey());
       mpParentWindow->getMainWidget()->getFittingWidget()->runTask();
     }
 }
void SliderDialog::runScanTask () protected virtual
Definition at line 807 of file SliderDialog.cpp.
References CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWidget(), ListViews::getScanWidget(), mpParentWindow, and ScanWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getScanWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Scan"]->getKey());
       mpParentWindow->getMainWidget()->getScanWidget()->runTask();
     }
 }
void SliderDialog::runSteadyStateTask () protected virtual
Definition at line 799 of file SliderDialog.cpp.
References CopasiUI3Window::getMainWidget(), ListViews::getSteadyStateWidget(), mpParentWindow, and SteadyStateWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       mpParentWindow->getMainWidget()->getSteadyStateWidget()->runTask();
     }
 }
void SliderDialog::runTask () protected slot
Definition at line 734 of file SliderDialog.cpp.
References ListViews::findWidgetFromId(), CopasiUI3Window::getMainWidget(), TaskWidget::leave(), mCurrentFolderId, mpParentWindow, mTaskMap, and updateAllSliders().
Referenced by SliderDialog(), sliderReleased(), and sliderValueChanged().
 {
   if (mpParentWindow == NULL
       || !isEnabled()
       || !mpParentWindow->isEnabled()
       || mTaskMap.find(mCurrentFolderId) == mTaskMap.end())
     return;
   updateAllSliders();
   TaskWidget* pWidget = dynamic_cast<TaskWidget*>(mpParentWindow->getMainWidget()->findWidgetFromId(mCurrentFolderId));
   assert(pWidget != NULL);
   if (pWidget == NULL) return;
   // commit possible changes to the task widget before running the task
   pWidget->leave();
   // execute task
   ((this)->*(mTaskMap[mCurrentFolderId]))();
 }
void SliderDialog::runTimeCourse () protected virtual
Definition at line 789 of file SliderDialog.cpp.
References CopasiWidget::enter(), CCopasiRootContainer::getDatamodelList(), CopasiUI3Window::getMainWidget(), ListViews::getTrajectoryWidget(), mpParentWindow, and CQTrajectoryWidget::runTask().
Referenced by SliderDialog().
 {
   if (mpParentWindow)
     {
       assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
       mpParentWindow->getMainWidget()->getTrajectoryWidget()->enter((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time-Course"]->getKey());
       mpParentWindow->getMainWidget()->getTrajectoryWidget()->runTask();
     }
 }
void SliderDialog::setChanged (bool changed)
Sets the changed state of the SliderDialog.
Definition at line 1320 of file SliderDialog.cpp.
References mChanged.
Referenced by CopasiUI3Window::CopasiUI3Window(), CopasiUI3Window::newDoc(), and CopasiUI3Window::slotFileSaveFinished().
 {
   this->mChanged = changed;
 }
bool SliderDialog::setCorrectSliderObject (CopasiSlider * pSlider) protected
Takes a CopasiSlider object and checks if the associated model object fits the currently set framework. If not, the slider object and the values are adjusted.
On success, true is returned.
Definition at line 1230 of file SliderDialog.cpp.
References determineCorrectObjectForSlider(), CopasiSlider::maxValue(), CopasiSlider::minValue(), CopasiSlider::object(), CopasiSlider::setMaxValue(), CopasiSlider::setMinValue(), CopasiSlider::setObject(), and CopasiSlider::value().
Referenced by addSlider(), createSlidersForFolder(), and setFramework().
 {
   if (pSlider == NULL)
     return false;
   CCopasiObject *pObject = NULL, *pTmpObject = NULL;
   pObject = pSlider->object();
   if (pObject == NULL)
     return false;
   pTmpObject = const_cast<CCopasiObject*>(this->determineCorrectObjectForSlider(pObject));
   if (pTmpObject != pObject)
     {
       // we have to recalculate the range
       double oldMin = pSlider->minValue();
       double oldMax = pSlider->maxValue();
       double oldValue = pSlider->value();
       // we have to set the new object on the slider
       pSlider->setObject(pTmpObject);
       double newValue =  pSlider->value();
       double newMin = (oldMin / oldValue) * newValue;
       double newMax = (oldMax / oldValue) * newValue;
       pSlider->setMinValue(newMin);
       pSlider->setMaxValue(newMax);
     }
   return true;
 }
void SliderDialog::setCurrentFolderId (size_t id)
Definition at line 501 of file SliderDialog.cpp.
References C_INVALID_INDEX, clearSliderBox(), fillSliderBox(), mapFolderId2EntryId(), mCurrentFolderId, and mpParentWindow.
Referenced by CopasiUI3Window::CopasiUI3Window(), CopasiUI3Window::listViewsFolderChanged(), and SliderDialog().
 {
   id = mapFolderId2EntryId(id);
   if (id == mCurrentFolderId) return;
   if (id == C_INVALID_INDEX || !this->mpParentWindow->isEnabled())
     {
       setEnabled(false);
     }
   else
     {
       setEnabled(true);
     }
   clearSliderBox();
   mCurrentFolderId = id;
   // Set appropriate window title
   QString thisWindowTitle = "Sliders";
   switch (id)
     {
       case 23:
         thisWindowTitle = "Time Course " + thisWindowTitle;
         break;
       case 21:
         thisWindowTitle = "Steady-State " + thisWindowTitle;
         break;
       case 31:
         thisWindowTitle = "Parameter Scan " + thisWindowTitle;
         break;
       case 24:
         thisWindowTitle = "Metabolic Control Analysis " + thisWindowTitle;
         break;
       case 35:
         thisWindowTitle = "Linear Noise Approximation " + thisWindowTitle;
         break;
       case 33:
         thisWindowTitle = "Parameter Estimation " + thisWindowTitle;
         break;
       case 32:
         thisWindowTitle = "Optimization " + thisWindowTitle;
         break;
       case 28:
         thisWindowTitle = "Cross Section " + thisWindowTitle;
         break;
     }
   setWindowTitle(thisWindowTitle);
   fillSliderBox();
 }
void SliderDialog::setCurrentSlider (CopasiSlider * pSlider) protected
Definition at line 147 of file SliderDialog.cpp.
References CopasiSlider::focusSlider(), and mpCurrSlider.
Referenced by addSlider(), contextMenuEvent(), createSlidersForFolder(), editSlider(), eventFilter(), fillSliderBox(), removeSlider(), and sliderValueChanged().
 {
   mpCurrSlider = pSlider;
   if (mpCurrSlider && isVisible())
     {
       mpCurrSlider->focusSlider();
     }
 }
void SliderDialog::setDefault () protected slot
Definition at line 1104 of file SliderDialog.cpp.
References mpCurrSlider, CopasiSlider::setOriginalValue(), and CopasiSlider::value().
Referenced by SliderDialog().
 {
   mpCurrSlider->setOriginalValue(mpCurrSlider->value());
 }
void SliderDialog::setFramework (int index)
Definition at line 1179 of file SliderDialog.cpp.
References mFramework, mSliderMap, CopasiSlider::object(), and setCorrectSliderObject().
Referenced by CopasiUI3Window::slotFrameworkChanged().
 {
   mFramework = framework;
   bool changed = false;
   // we go through the sliders and check if the slider for species amount
   // or concentration are still appropriate for the framework that has been set
   std::map<size_t, std::vector<QWidget*> >::iterator it = this->mSliderMap.begin(), endit = this->mSliderMap.end();
   std::vector<QWidget*>::iterator it2, endit2;
   CopasiSlider* pSlider = NULL;
   while (it != endit)
     {
       it2 = it->second.begin();
       endit2 = it->second.end();
       while (it2 != endit2)
         {
           pSlider = dynamic_cast<CopasiSlider*>(*it2);
           if (pSlider != NULL)
             {
               const CCopasiObject* pTmpObj = pSlider->object();
               this->setCorrectSliderObject(pSlider);
               if (pSlider->object() != pTmpObj && !changed)
                 {
                   changed = true;
                 }
             }
           ++it2;
         }
       ++it;
     }
   // we don't care if the change was for the current
   // task, we just update if there was any change at all
   if (changed == true)
     {
       this->update();
     }
 }
void SliderDialog::setParentWindow (CopasiUI3Window * pPW)
Definition at line 1118 of file SliderDialog.cpp.
References mpParentWindow.
Referenced by CopasiUI3Window::CopasiUI3Window().
 {
   mpParentWindow = pPW;
 }
void SliderDialog::showEvent (QShowEvent * pEvent) protected virtual
Definition at line 1261 of file SliderDialog.cpp.
References updateAllSliders().
 {
   // make sure only valid sliders are shown
   updateAllSliders();
   this->CWindowInterface::showEvent(pEvent);
 }
bool SliderDialog::sliderObjectChanged (CSlider * pSlider) const protected
Definition at line 1109 of file SliderDialog.cpp.
References CSlider::compile(), and CCopasiRootContainer::getDatamodelList().
Referenced by getCSlidersForObject().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CModel* pModel = (*CCopasiRootContainer::getDatamodelList())[0]->getModel();
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(pModel);
   return !pSlider->compile(listOfContainers);
 }
void SliderDialog::sliderPressed () protected slot
Definition at line 784 of file SliderDialog.cpp.
References mSliderPressed.
Referenced by addSlider(), and createSlidersForFolder().
 {
   mSliderPressed = true;
 }
void SliderDialog::sliderReleased () protected slot
Definition at line 773 of file SliderDialog.cpp.
References mSliderPressed, mSliderValueChanged, and runTask().
Referenced by addSlider(), and createSlidersForFolder().
 {
   if (mSliderValueChanged && mpAutoRunCheckBox->isChecked())
     {
       mSliderValueChanged = false;
       runTask();
     }
   mSliderPressed = false;
 }
void SliderDialog::sliderValueChanged () protected slot
Definition at line 756 of file SliderDialog.cpp.
References CCopasiRootContainer::getConfiguration(), mpCurrSlider, mSliderPressed, mSliderValueChanged, runTask(), setCurrentSlider(), and CConfigurationFile::useAdvancedSliders().
Referenced by addSlider(), and createSlidersForFolder().
 {
   mSliderValueChanged = true;
   if ((!mSliderPressed) && mpAutoRunCheckBox->isChecked()
       && CCopasiRootContainer::getConfiguration()->useAdvancedSliders())
     {
       CopasiSlider* slider = dynamic_cast<CopasiSlider*>(sender());
       if (slider != NULL && slider != mpCurrSlider)
         setCurrentSlider(slider);
       mSliderValueChanged = false;
       runTask();
     }
 }
void SliderDialog::updateAllSliders () virtual
Definition at line 925 of file SliderDialog.cpp.
References C_INVALID_INDEX, deleteInvalidSliders(), CopasiUI3Window::getDataModel(), mCurrentFolderId, mpParentWindow, mSliderMap, DataModelGUI::refreshInitialValues(), CopasiSlider::updateSliderData(), and CopasiSlider::updateValue().
Referenced by CopasiUI3Window::disableSliders(), runTask(), and showEvent().
 {
   if (!isVisible())
     {
       return;
     }
   // this method might not always do what we want
   // e.g. if we change a volume via a slider, the initial amount/concentrations
   // of the species are updated automatically, but if there is a slider for the
   // automatically updated value and we changed that value as well together with
   // the volume, the change of amount/concentration is probably lost depending on
   // the order of the sliders
   // We need to do this in two rounds, first we set all the new values
   //
   // To solve this, I added a new argument to updateValue that determines if the call also updates the dependencies.
   // Here we do not let the updateValue call update the dependencies, but we take care of this ourselves
   // with a call to ListView::refreshInitialValues
   if (mCurrentFolderId == C_INVALID_INDEX) return;
   bool autoModify = mpAutoModifyRangesCheckBox->isChecked();
   this->deleteInvalidSliders();
   std::vector<QWidget*> v = mSliderMap[mCurrentFolderId];
   std::vector<QWidget*>::iterator wit = v.begin(), wendit = v.end();
   if (!v.empty())
     {
       // We make sure that all initial values of the model are up to date
       // before we update the sliders.
       if (mpParentWindow != NULL)
         mpParentWindow->getDataModel()->refreshInitialValues();
       // We go through the sliders and make sure that
       // that the  model values are updated.
       wit = v.begin();
       wendit = v.end();
       CopasiSlider* pCopasiSlider = NULL;
       while (wit != wendit)
         {
           pCopasiSlider = dynamic_cast<CopasiSlider*>(*wit);
           if (pCopasiSlider)
             {
               pCopasiSlider->updateValue(autoModify, false);
               pCopasiSlider->updateSliderData();
             }
           ++wit;
         }
       // We make sure that all dependent initial values of the model are up to date.
       // Please note that this is context sensitive, i.e., concentration and particle numbers
       // are dealt with correctly.
       if (mpParentWindow != NULL)
         mpParentWindow->getDataModel()->refreshInitialValues();
     }
 }
Member Data Documentation
size_t SliderDialog::folderMappings static protected
Initial value:
=
{
  {21, 21}, {211, 21}, {23, 23}, {231, 23}, {24, 24},
  {241, 24} , {31, 31}, {32, 32}, {321, 32}, {33, 33},
  {331, 33}, {35, 35}, {28, 28}, {281, 28}
}
Definition at line 104 of file SliderDialog.h.
Referenced by mapFolderId2EntryId().
bool SliderDialog::mChanged protected
Definition at line 177 of file SliderDialog.h.
Referenced by addSlider(), createNewSlider(), createSlidersForFolder(), deleteSlider(), isChanged(), and setChanged().
size_t SliderDialog::mCurrentFolderId protected
Definition at line 171 of file SliderDialog.h.
Referenced by addSlider(), clearSliderBox(), createNewSlider(), createSlidersForFolder(), deleteInvalidSliders(), deleteSlider(), editSlider(), fillSliderBox(), findCopasiSliderForCSlider(), getCSlidersForCurrentFolderId(), runTask(), setCurrentFolderId(), and updateAllSliders().
int SliderDialog::mFramework protected
Definition at line 174 of file SliderDialog.h.
Referenced by determineCorrectObjectForSlider(), and setFramework().
QAction* SliderDialog::mpaCreateNewSlider protected
Definition at line 163 of file SliderDialog.h.
Referenced by contextMenuEvent(), and SliderDialog().
QAction* SliderDialog::mpaEditSlider protected
Definition at line 165 of file SliderDialog.h.
Referenced by contextMenuEvent(), and SliderDialog().
QAction* SliderDialog::mpaRemoveSlider protected
Definition at line 164 of file SliderDialog.h.
Referenced by contextMenuEvent(), and SliderDialog().
QAction* SliderDialog::mpaResetValue protected
Definition at line 166 of file SliderDialog.h.
Referenced by SliderDialog().
QAction* SliderDialog::mpaSetDefault protected
Definition at line 167 of file SliderDialog.h.
Referenced by SliderDialog().
QMenu* SliderDialog::mpContextMenu protected
Definition at line 162 of file SliderDialog.h.
Referenced by contextMenuEvent(), and SliderDialog().
CopasiSlider* SliderDialog::mpCurrSlider protected
Definition at line 168 of file SliderDialog.h.
Referenced by addSlider(), changeEvent(), createSlidersForFolder(), editSlider(), fillSliderBox(), removeSlider(), resetValue(), setCurrentSlider(), setDefault(), and sliderValueChanged().
CopasiUI3Window* SliderDialog::mpParentWindow protected
Definition at line 161 of file SliderDialog.h.
Referenced by addSlider(), closeEvent(), createSlidersForFolder(), fillSliderBox(), runCrossSectionTask(), runLNATask(), runMCATask(), runOptimizationTask(), runParameterEstimationTask(), runScanTask(), runSteadyStateTask(), runTask(), runTimeCourse(), setCurrentFolderId(), setParentWindow(), SliderDialog(), updateAllSliders(), and ~SliderDialog().
std::map< size_t, std::vector< QWidget* > > SliderDialog::mSliderMap protected
Definition at line 169 of file SliderDialog.h.
Referenced by addSlider(), clear(), clearSliderBox(), createSlidersForFolder(), deleteInvalidSliders(), deleteSlider(), fillSliderBox(), findCopasiSliderForCSlider(), reset(), setFramework(), SliderDialog(), and updateAllSliders().
bool SliderDialog::mSliderPressed protected
Definition at line 173 of file SliderDialog.h.
Referenced by sliderPressed(), sliderReleased(), and sliderValueChanged().
bool SliderDialog::mSliderValueChanged protected
Definition at line 172 of file SliderDialog.h.
Referenced by sliderReleased(), and sliderValueChanged().
std::map< size_t, void(SliderDialog::*)() > SliderDialog::mTaskMap protected
Definition at line 170 of file SliderDialog.h.
Referenced by runTask(), and SliderDialog().
size_t SliderDialog::numMappings = 14 static protected
Definition at line 103 of file SliderDialog.h.
Referenced by mapFolderId2EntryId().
The documentation for this class was generated from the following files:
SliderDialog.h
SliderDialog.cpp