COPASI API: CLRenderPoint Class Reference
CLRenderPoint Class Reference
#include <CLRenderPoint.h>
Public Member Functions
virtual void addSBMLAttributes (RenderPoint *pPoint) const
CLRenderPoint ()
CLRenderPoint (const CLRenderPoint &orig)
CLRenderPoint (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
CLRenderPoint (const RenderPoint &source)
const CLRelAbsVector & getXOffset () const
CLRelAbsVector & getXOffset ()
const CLRelAbsVector & getYOffset () const
CLRelAbsVector & getYOffset ()
const CLRelAbsVector & getZOffset () const
CLRelAbsVector & getZOffset ()
void initDefaults ()
CLRenderPoint & operator= (const CLRenderPoint &orig)
bool operator== (const CLRenderPoint &left)
void setOffsets (const CLRelAbsVector &x, const CLRelAbsVector &y, const CLRelAbsVector &z=CLRelAbsVector(0.0, 0.0))
void setX (const CLRelAbsVector &x)
void setXOffset (const CLRelAbsVector &x)
void setY (const CLRelAbsVector &y)
void setYOffset (const CLRelAbsVector &y)
void setZ (const CLRelAbsVector &z)
void setZOffset (const CLRelAbsVector &z)
virtual RenderPoint * toSBML (unsigned int level, unsigned int version) const
const CLRelAbsVector & x () const
CLRelAbsVector & x ()
const CLRelAbsVector & y () const
CLRelAbsVector & y ()
const CLRelAbsVector & z () const
CLRelAbsVector & z ()
virtual ~CLRenderPoint ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Protected Attributes
CLRelAbsVector mXOffset
CLRelAbsVector mYOffset
CLRelAbsVector mZOffset
Protected Attributes inherited from CLBase
std::string mTag
Detailed Description
Definition at line 22 of file CLRenderPoint.h.
Constructor & Destructor Documentation
CLRenderPoint::CLRenderPoint ()
Creates a new point with x,y and z set to 0.0.
Definition at line 24 of file CLRenderPoint.cpp.
                              :
     CLBase(),
     mXOffset(CLRelAbsVector(0.0, 0.0)),
     mYOffset(CLRelAbsVector(0.0, 0.0)),
     mZOffset(CLRelAbsVector(0.0, 0.0))
 {
 }
CLRenderPoint::CLRenderPoint (const CLRenderPoint & orig)
Copy constructor.
Definition at line 35 of file CLRenderPoint.cpp.
                                                      :
     CLBase(orig),
     mXOffset(orig.mXOffset),
     mYOffset(orig.mYOffset),
     mZOffset(orig.mZOffset)
 {
 }
CLRenderPoint::CLRenderPoint (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Creates a new point with the given ccordinates.
Definition at line 70 of file CLRenderPoint.cpp.
                                                                                                       :
     CLBase()
     , mXOffset(x)
     , mYOffset(y)
     , mZOffset(z)
 {
 }
CLRenderPoint::CLRenderPoint (const RenderPoint & source)
Constructor to generate object from the corresponding SBML object.
Definition at line 46 of file CLRenderPoint.cpp.
                                                      :
     CLBase(),
     mXOffset(source.x()),
     mYOffset(source.y()),
     mZOffset(source.z())
 {
 }
CLRenderPoint::~CLRenderPoint () virtual
Destructor.
Definition at line 89 of file CLRenderPoint.cpp.
 {
 }
Member Function Documentation
void CLRenderPoint::addSBMLAttributes (RenderPoint * pPoint) const virtual
Adds the attributes for a render point object to the passed in. object.
Definition at line 288 of file CLRenderPoint.cpp.
References mXOffset, mYOffset, mZOffset, and CLRelAbsVector::toSBML().
Referenced by toSBML(), and CLRenderCubicBezier::toSBML().
 {
   RelAbsVector* pV1 = this->mXOffset.toSBML();
   RelAbsVector* pV2 = this->mYOffset.toSBML();
   RelAbsVector* pV3 = this->mZOffset.toSBML();
   pPoint->setCoordinates(*pV1, *pV2, *pV3);
   delete pV1;
   delete pV2;
   delete pV3;
 }
const CLRelAbsVector & CLRenderPoint::getXOffset () const
Returns the x offset.
Definition at line 162 of file CLRenderPoint.cpp.
References x().
Referenced by addToPath(), and moveToPoint().
 {
   return this->x();
 }
CLRelAbsVector & CLRenderPoint::getXOffset ()
Returns the x offset.
Definition at line 216 of file CLRenderPoint.cpp.
References x().
 {
   return this->x();
 }
const CLRelAbsVector & CLRenderPoint::getYOffset () const
Returns the y offset.
Definition at line 171 of file CLRenderPoint.cpp.
References y().
Referenced by addToPath(), and moveToPoint().
 {
   return this->y();
 }
CLRelAbsVector & CLRenderPoint::getYOffset ()
Returns the y offset.
Definition at line 225 of file CLRenderPoint.cpp.
References y().
 {
   return this->y();
 }
const CLRelAbsVector & CLRenderPoint::getZOffset () const
Returns the z offset.
Definition at line 180 of file CLRenderPoint.cpp.
References z().
 {
   return this->z();
 }
CLRelAbsVector & CLRenderPoint::getZOffset ()
Returns the z offset.
Definition at line 234 of file CLRenderPoint.cpp.
References z().
 {
   return this->z();
 }
void CLRenderPoint::initDefaults ()
Sets the Z offset to 0.0.
Definition at line 81 of file CLRenderPoint.cpp.
References setZOffset().
 {
   this->setZOffset(0.0);
 }
CLRenderPoint & CLRenderPoint::operator= (const CLRenderPoint & orig)
Assignment operator
Definition at line 54 of file CLRenderPoint.cpp.
References mXOffset, mYOffset, and mZOffset.
Referenced by CLRenderCubicBezier::operator=().
 {
   if (&orig != this)
     {
       this->CLBase::operator=(orig);
       this->mXOffset = orig.mXOffset;
       this->mYOffset = orig.mYOffset;
       this->mZOffset = orig.mZOffset;
     }
   return *this;
 }
bool CLRenderPoint::operator== (const CLRenderPoint & left)
Comparison operator.
Definition at line 269 of file CLRenderPoint.cpp.
References mXOffset, mYOffset, and mZOffset.
 {
   return (this->mXOffset == left.mXOffset && this->mYOffset == left.mYOffset && this->mZOffset == left.mZOffset);
 }
void CLRenderPoint::setOffsets (const CLRelAbsVector & x, const CLRelAbsVector & y, const CLRelAbsVector & z = CLRelAbsVector(0.0, 0.0))
Sets the coordinates to the given values.
Definition at line 97 of file CLRenderPoint.cpp.
References setXOffset(), setYOffset(), and setZOffset().
 {
   this->setXOffset(x);
   this->setYOffset(y);
   this->setZOffset(z);
 }
void CLRenderPoint::setX (const CLRelAbsVector & x)
Sets the x offset.
Definition at line 135 of file CLRenderPoint.cpp.
References mXOffset, and x().
Referenced by setXOffset().
 {
   this->mXOffset = x;
 }
void CLRenderPoint::setXOffset (const CLRelAbsVector & x)
Sets the x offset.
Definition at line 108 of file CLRenderPoint.cpp.
References setX().
Referenced by setOffsets().
 {
   this->setX(x);
 }
void CLRenderPoint::setY (const CLRelAbsVector & y)
Sets the y offset.
Definition at line 144 of file CLRenderPoint.cpp.
References mYOffset, and y().
Referenced by setYOffset().
 {
   this->mYOffset = y;
 }
void CLRenderPoint::setYOffset (const CLRelAbsVector & y)
Sets the y offset.
Definition at line 117 of file CLRenderPoint.cpp.
References setY().
Referenced by setOffsets().
 {
   this->setY(y);
 }
void CLRenderPoint::setZ (const CLRelAbsVector & z)
Sets the z offset.
Definition at line 153 of file CLRenderPoint.cpp.
References mZOffset, and z().
Referenced by setZOffset().
 {
   this->mZOffset = z;
 }
void CLRenderPoint::setZOffset (const CLRelAbsVector & z)
Sets the z offset.
Definition at line 126 of file CLRenderPoint.cpp.
References setZ().
Referenced by initDefaults(), and setOffsets().
 {
   this->setZ(z);
 }
RenderPoint * CLRenderPoint::toSBML (unsigned int level, unsigned int version) const virtual
Converts this object to the corresponding SBML object.
Reimplemented in CLRenderCubicBezier.
Definition at line 277 of file CLRenderPoint.cpp.
References addSBMLAttributes().
 {
   RenderPoint* pP = new RenderPoint(level, version);
   this->addSBMLAttributes(pP);
   return pP;
 }
const CLRelAbsVector & CLRenderPoint::x () const
Returns the x offset.
Definition at line 189 of file CLRenderPoint.cpp.
References mXOffset.
Referenced by CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), getXOffset(), CCopasiXML::saveRenderPoint(), CLRenderCubicBezier::setBasePoint1(), CLRenderCubicBezier::setBasePoint2(), and setX().
 {
   return this->mXOffset;
 }
CLRelAbsVector & CLRenderPoint::x ()
Returns the x offset.
Definition at line 243 of file CLRenderPoint.cpp.
References mXOffset.
 {
   return this->mXOffset;
 }
const CLRelAbsVector & CLRenderPoint::y () const
Returns the y offset.
Definition at line 198 of file CLRenderPoint.cpp.
References mYOffset.
Referenced by CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), getYOffset(), CCopasiXML::saveRenderPoint(), CLRenderCubicBezier::setBasePoint1(), CLRenderCubicBezier::setBasePoint2(), and setY().
 {
   return this->mYOffset;
 }
CLRelAbsVector & CLRenderPoint::y ()
Returns the y offset.
Definition at line 252 of file CLRenderPoint.cpp.
References mYOffset.
 {
   return this->mYOffset;
 }
const CLRelAbsVector & CLRenderPoint::z () const
Returns the z offset.
Definition at line 207 of file CLRenderPoint.cpp.
References mZOffset.
Referenced by CLLayoutRenderer::convert_to_absolute(), CLLayoutRenderer::draw_curve(), CLLayoutRenderer::draw_polygon(), getZOffset(), CCopasiXML::saveRenderPoint(), CLRenderCubicBezier::setBasePoint1(), CLRenderCubicBezier::setBasePoint2(), and setZ().
 {
   return this->mZOffset;
 }
CLRelAbsVector & CLRenderPoint::z ()
Returns the z offset.
Definition at line 261 of file CLRenderPoint.cpp.
References mZOffset.
 {
   return this->mZOffset;
 }
Member Data Documentation
CLRelAbsVector CLRenderPoint::mXOffset protected
Definition at line 26 of file CLRenderPoint.h.
Referenced by addSBMLAttributes(), CLRenderCubicBezier::CLRenderCubicBezier(), operator=(), operator==(), setX(), and x().
CLRelAbsVector CLRenderPoint::mYOffset protected
Definition at line 27 of file CLRenderPoint.h.
Referenced by addSBMLAttributes(), CLRenderCubicBezier::CLRenderCubicBezier(), operator=(), operator==(), setY(), and y().
CLRelAbsVector CLRenderPoint::mZOffset protected
Definition at line 28 of file CLRenderPoint.h.
Referenced by addSBMLAttributes(), CLRenderCubicBezier::CLRenderCubicBezier(), operator=(), operator==(), setZ(), and z().
The documentation for this class was generated from the following files:
CLRenderPoint.h
CLRenderPoint.cpp