COPASI API: CMCAResultSubwidget Class Reference
CMCAResultSubwidget Class Reference
#include <CMCAResultSubwidget.h>
Public Member Functions
virtual void clear ()
CMCAResultSubwidget (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
virtual void loadAll (const CMCAMethod *mcaMethod)
virtual void loadConcentrationCCs (const CMCAMethod *mcaMethod)
virtual void loadElasticities (const CMCAMethod *mcaMethod)
virtual void loadFluxCCs (const CMCAMethod *mcaMethod)
~CMCAResultSubwidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual bool leave ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
Protected Slots
virtual void slotSave ()
virtual void slotScaled ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual void init ()
Protected Member Functions inherited from CopasiWidget
virtual bool enterProtected ()
Private Attributes
const CMCAMethod * mMCAMethod
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 33 of file CMCAResultSubwidget.h.
Constructor & Destructor Documentation
CMCAResultSubwidget::CMCAResultSubwidget (QWidget * parent = 0, const char * name = 0, Qt::WindowFlags fl = 0)
Definition at line 47 of file CMCAResultSubwidget.cpp.
References init().
   : CopasiWidget(parent, name, fl)
 {
   setupUi(this);
   init();
 }
CMCAResultSubwidget::~CMCAResultSubwidget ()
Definition at line 58 of file CMCAResultSubwidget.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CMCAResultSubwidget::clear () virtual
Definition at line 314 of file CMCAResultSubwidget.cpp.
Referenced by init(), and loadAll().
 {
   mTopLabel->setText("No result available, please execute the MCA task.");
   //   mTableElasticities->setNumRows(0);
   //   mTableElasticities->setNumCols(0);
   //
   //   mTableCCC->setNumRows(0);
   //   mTableCCC->setNumCols(0);
   //
   //   mTableFCC->setNumRows(0);
   //   mTableFCC->setNumCols(0);
   mpArrayElasticities->setArrayAnnotation(NULL);
   mpArrayFCC->setArrayAnnotation(NULL);
   mpArrayCCC->setArrayAnnotation(NULL);
   return;
 }
void CMCAResultSubwidget::init () protected virtual
Definition at line 63 of file CMCAResultSubwidget.cpp.
References clear(), and mMCAMethod.
Referenced by CMCAResultSubwidget().
 {
   /*
     mSaveButton->setEnabled(false);
     mSaveButton->hide();
   */
   mMCAMethod = NULL;
   clear();
 }
void CMCAResultSubwidget::loadAll (const CMCAMethod * mcaMethod) virtual
Definition at line 74 of file CMCAResultSubwidget.cpp.
References clear(), CSteadyStateMethod::found, CSteadyStateMethod::foundEquilibrium, CSteadyStateMethod::foundNegative, CMCAMethod::getModel(), CMCAMethod::getSteadyStateStatus(), loadConcentrationCCs(), loadElasticities(), loadFluxCCs(), mMCAMethod, and CSteadyStateMethod::notFound.
Referenced by CMCAResultWidget::loadFromBackend(), slotScaled(), and CMCAResultWidget::update().
 {
   mMCAMethod = mcaMethod;
   if (mcaMethod)
     {
       if (!mcaMethod->getModel())
         {
           clear();
           return;
         }
       if (mcaMethod->getSteadyStateStatus() == CSteadyStateMethod::found)
         {
           mTopLabel->setText("Steady State found. All coefficients available.");
           this->loadElasticities(mcaMethod);
           this->loadConcentrationCCs(mcaMethod);
           this->loadFluxCCs(mcaMethod);
           mTabWidget->setTabEnabled(1, true);
           mTabWidget->setTabEnabled(2, true);
         }
       else
         {
           this->loadElasticities(mcaMethod);
           mTabWidget->setTabEnabled(1, false);
           mTabWidget->setTabEnabled(2, false);
           if (mcaMethod->getSteadyStateStatus() == CSteadyStateMethod::foundEquilibrium)
             mTopLabel->setText("Equilibrium steady state. Only elasticities available!");
           if (mcaMethod->getSteadyStateStatus() == CSteadyStateMethod::foundNegative)
             mTopLabel->setText("Invalid steady state (negative concentrations)!");
           if (mcaMethod->getSteadyStateStatus() == CSteadyStateMethod::notFound)
             mTopLabel->setText("No steady state found. Only elasticities available!");
         }
     }
   else
     {
       clear();
       return;
     }
 }
void CMCAResultSubwidget::loadConcentrationCCs (const CMCAMethod * mcaMethod) virtual
Definition at line 170 of file CMCAResultSubwidget.cpp.
References CMCAMethod::getScaledConcentrationCCAnn(), and CMCAMethod::getUnscaledConcentrationCCAnn().
Referenced by loadAll().
 {
   /*  const CModel* model = mcaMethod->getModel();
     assert(model);
     unsigned C_INT32 numRows, numCols;
     numRows = model->getNumVariableMetabs();
     numCols = model->getTotSteps();
     mTableCCC->setNumRows(numRows);
     mTableCCC->setNumCols(numCols);
     unsigned C_INT32 i, j;
     QHeader* header = mTableCCC->verticalHeader();
     for (i = 0; i < numRows;++i)
       {
         header->setLabel(i, FROM_UTF8(model->getMetabolitesX()[i]->getObjectName()));
       }
     header = mTableCCC->horizontalHeader();
     for (i = 0; i < numCols;++i)
       {
         header->setLabel(i, FROM_UTF8(model->getReactions()[i]->getObjectName()));
       }
     const CMatrix<C_FLOAT64> & CCCs = (mComboScale->currentIndex() == 0) ? mcaMethod->getScaledConcentrationCC() : mcaMethod->getUnscaledConcentrationCC();
     if (CCCs.numRows() == 0 || CCCs.numCols() == 0) return;
     for (i = 0; i < numRows;++i)
       {
         for (j = 0; j < numCols;++j)
           {
             mTableCCC->setText(i, j, QString::number(CCCs[i][j]));
           }
       }*/
   const CArrayAnnotation * CCCAnn;
   if (mComboScale->currentIndex() == 0)
     {
       CCCAnn = mcaMethod->getScaledConcentrationCCAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayCCC->setColorCoding(tcs);
       mpArrayCCC->setColorScalingAutomatic(true);
     }
   else
     {
       CCCAnn = mcaMethod->getUnscaledConcentrationCCAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayCCC->setColorCoding(tcs);
       mpArrayCCC->setColorScalingAutomatic(true);
     }
   mpArrayCCC->setArrayAnnotation(CCCAnn);
 }
void CMCAResultSubwidget::loadElasticities (const CMCAMethod * mcaMethod) virtual
Definition at line 118 of file CMCAResultSubwidget.cpp.
References CMCAMethod::getScaledElasticitiesAnn(), and CMCAMethod::getUnscaledElasticitiesAnn().
Referenced by loadAll().
 {
   //   const CModel* model = mcaMethod->getModel();
   //   assert(model);
   //   unsigned C_INT32 numRows, numCols;
   //   numRows = model->getTotSteps();
   //   numCols = model->getMetabolitesX().size();
   //   mTableElasticities->setNumRows(numRows);
   //   mTableElasticities->setNumCols(numCols);
   //   unsigned C_INT32 i, j;
   //   QHeader* header = mTableElasticities->verticalHeader();
   //   for (i = 0; i < numRows;++i)
   //     {
   //       header->setLabel(i, FROM_UTF8(model->getReactions()[i]->getObjectName()));
   //}
   //   header = mTableElasticities->horizontalHeader();
   //   for (i = 0; i < numCols;++i)
   //     {
   //       header->setLabel(i, FROM_UTF8(model->getMetabolitesX()[i]->getObjectName()));
   //}
   //   const CMatrix<C_FLOAT64> & elasticities = (mComboScale->currentIndex() == 0) ? mcaMethod->getScaledElasticities() : mcaMethod->getUnscaledElasticities();
   //   if (elasticities.numRows() == 0 || elasticities.numCols() == 0) return;
   //   for (i = 0; i < numRows;++i)
   //     {
   //       for (j = 0; j < numCols;++j)
   //         {
   //           mTableElasticities->setText(i, j, QString::number(elasticities[i][j]));
   //}
   //}
   const CArrayAnnotation * elasticitiesAnn;
   if (mComboScale->currentIndex() == 0)
     {
       elasticitiesAnn = mcaMethod->getScaledElasticitiesAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayElasticities->setColorCoding(tcs);
       mpArrayElasticities->setColorScalingAutomatic(true);
     }
   else
     {
       elasticitiesAnn = mcaMethod->getUnscaledElasticitiesAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayElasticities->setColorCoding(tcs);
       mpArrayElasticities->setColorScalingAutomatic(true);
     }
   mpArrayElasticities->setArrayAnnotation(elasticitiesAnn);
 }
void CMCAResultSubwidget::loadFluxCCs (const CMCAMethod * mcaMethod) virtual
Definition at line 221 of file CMCAResultSubwidget.cpp.
References CMCAMethod::getScaledFluxCCAnn(), and CMCAMethod::getUnscaledFluxCCAnn().
Referenced by loadAll().
 {
   /*  const CModel* model = mcaMethod->getModel();
     assert(model);
     unsigned C_INT32 numRows, numCols;
     numCols = numRows = model->getTotSteps();
     mTableFCC->setNumRows(numRows);
     mTableFCC->setNumCols(numCols);
     unsigned C_INT32 i, j;
     QHeader* header = mTableFCC->verticalHeader();
     for (i = 0; i < numRows;++i)
       {
         header->setLabel(i, FROM_UTF8(model->getReactions()[i]->getObjectName()));
       }
     header = mTableFCC->horizontalHeader();
     for (i = 0; i < numCols;++i)
       {
         header->setLabel(i, FROM_UTF8(model->getReactions()[i]->getObjectName()));
       }
     const CMatrix<C_FLOAT64> & FCCs = (mComboScale->currentIndex() == 0) ? mcaMethod->getScaledFluxCC() : mcaMethod->getUnscaledFluxCC();
     if (FCCs.numRows() == 0 || FCCs.numCols() == 0) return;
     for (i = 0; i < numRows;++i)
       {
         for (j = 0; j < numCols;++j)
           {
             mTableFCC->setText(i, j, QString::number(FCCs[i][j]));
           }
       }*/
   const CArrayAnnotation * FCCAnn;
   if (mComboScale->currentIndex() == 0)
     {
       FCCAnn = mcaMethod->getScaledFluxCCAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayFCC->setColorCoding(tcs);
       mpArrayFCC->setColorScalingAutomatic(true);
     }
   else
     {
       FCCAnn = mcaMethod->getUnscaledFluxCCAnn();
       CColorScaleBiLog * tcs = new CColorScaleBiLog();
       mpArrayFCC->setColorCoding(tcs);
       mpArrayFCC->setColorScalingAutomatic(true);
     }
   mpArrayFCC->setArrayAnnotation(FCCAnn);
 }
void CMCAResultSubwidget::slotSave () protected virtual slot
Definition at line 273 of file CMCAResultSubwidget.cpp.
References C_INT32, checkSelection(), CLocaleString::fromUtf8(), CCopasiRootContainer::getDatamodelList(), CCopasiTask::getResult(), CopasiFileDialog::getSaveFileName(), and TO_UTF8.
 {
   C_INT32 Answer = QMessageBox::No;
   QString fileName;
   while (Answer == QMessageBox::No)
     {
       fileName =
         CopasiFileDialog::getSaveFileName(this, "Save File Dialog",
                                           "untitled.txt", "TEXT Files (*.txt)", "Save to");
       if (fileName.isEmpty()) return;
       // Checks whether the file exists
       Answer = checkSelection(fileName);
       if (Answer == QMessageBox::Cancel) return;
     }
   std::ofstream file(CLocaleString::fromUtf8(TO_UTF8(fileName)).c_str());
   if (file.fail())
     return;
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiTask* mpTask =
     dynamic_cast<CMCATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Metabolic Control Analysis"]);
   if (mpTask != NULL)
     file << mpTask->getResult();
 //    mpTask->printResult(file);
   return;
 }
void CMCAResultSubwidget::slotScaled () protected virtual slot
Definition at line 309 of file CMCAResultSubwidget.cpp.
References loadAll(), and mMCAMethod.
 {
   loadAll(mMCAMethod);
 }
Member Data Documentation
const CMCAMethod* CMCAResultSubwidget::mMCAMethod private
Definition at line 57 of file CMCAResultSubwidget.h.
Referenced by init(), loadAll(), and slotScaled().
The documentation for this class was generated from the following files:
CMCAResultSubwidget.h
CMCAResultSubwidget.cpp