COPASI API: CLImageTexturizer Class Reference
CLImageTexturizer Class Reference abstract
#include <CLImageTexturizer.h>
Public Member Functions
virtual CLTextureSpec * operator() (const std::string &filename, const std::string &basedir)=0
Static Protected Member Functions
static std::string to_absolute_path (const std::string &filename, const std::string &basedir)
Detailed Description
Definition at line 21 of file CLImageTexturizer.h.
Member Function Documentation
virtual CLTextureSpec* CLImageTexturizer::operator() (const std::string & filename, const std::string & basedir) pure virtual
Implemented in CQQtImageTexturizer, and CLSimpleImageTexturizer.
std::string CLImageTexturizer::to_absolute_path (const std::string & filename, const std::string & basedir) static protected
Takes a filename and tries to find out if it is a relative or an absolute path. If the file can not be found either way, an empty string is returned.
Definition at line 22 of file CLImageTexturizer.cpp.
References CDirEntry::makePathAbsolute().
Referenced by CLSimpleImageTexturizer::create_texture_for_image(), and CQQtImageTexturizer::operator()().
 {
   // first convert to UTF8 because CDirEntry expects UTF8
   std::string Path = filename;
   CDirEntry::makePathAbsolute(Path, basedir);
   return Path;
 }
The documentation for this class was generated from the following files:
CLImageTexturizer.h
CLImageTexturizer.cpp