COPASI API: CLReferenceGlyph Class Reference
CLReferenceGlyph Class Reference
#include <CLReactionGlyph.h>
Public Member Functions
virtual CLGraphicalObject * clone () const
CLReferenceGlyph (const std::string &name="ReferenceGlyph", const CCopasiContainer *pParent=NULL)
CLReferenceGlyph (const CLReferenceGlyph &src, const CCopasiContainer *pParent=NULL)
const std::string & getRole () const
CLGraphicalObject * getTargetGlyph () const
const std::string & getTargetGlyphKey () const
CLReferenceGlyph & operator= (const CLReferenceGlyph &rhs)
void print (std::ostream *ostream) const
void setRole (const std::string &r)
void setTargetGlyphKey (const std::string &k)
Public Member Functions inherited from CLGlyphWithCurve
CLGlyphWithCurve (const std::string &name="ReferenceGlyph", const CCopasiContainer *pParent=NULL)
CLGlyphWithCurve (const CLGlyphWithCurve &src, const CCopasiContainer *pParent=NULL)
CLGlyphWithCurve (const GraphicalObject &sbml, const std::map< std::string, std::string > &modelmap, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
const CLCurve & getCurve () const
CLCurve & getCurve ()
virtual void moveBy (const CLPoint &p)
CLGlyphWithCurve & operator= (const CLGlyphWithCurve &rhs)
void setCurve (const CLCurve &c)
Public Member Functions inherited from CLGraphicalObject
CLGraphicalObject (const std::string &name="GraphicalObject", const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const CLGraphicalObject &src, const CCopasiContainer *pParent=NULL)
CLGraphicalObject (const GraphicalObject &sbml, std::map< std::string, std::string > &layoutmap, const CCopasiContainer *pParent=NULL)
virtual void exportToSBML (GraphicalObject *sbmlobject, const std::map< const CCopasiObject *, SBase * > &copasimodelmap, std::map< std::string, const SBase * > &sbmlIDs) const
const CLBoundingBox & getBoundingBox () const
CLBoundingBox & getBoundingBox ()
const CLDimensions & getDimensions () const
const C_FLOAT64 & getHeight () const
virtual const std::string & getKey () const
CCopasiObject * getModelObject () const
std::string getModelObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getModelObjectKey () const
std::string getModelObjectName () const
const std::string & getObjectRole () const
const CLPoint & getPosition () const
const C_FLOAT64 & getWidth () const
const C_FLOAT64 & getX () const
const C_FLOAT64 & getY () const
bool hasValidModelReference () const
CLGraphicalObject & operator= (const CLGraphicalObject &rhs)
void setBoundingBox (const CLBoundingBox &bb)
void setDimensions (const CLDimensions &d)
void setHeight (const C_FLOAT64 &h)
void setModelObjectKey (const std::string &k)
void setObjectRole (const std::string &role)
void setPosition (const CLPoint &p)
void setWidth (const C_FLOAT64 &w)
void setX (const C_FLOAT64 &x)
void setY (const C_FLOAT64 &y)
~CLGraphicalObject ()
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
std::string mGlyphKey
std::string mRole
Protected Attributes inherited from CLGlyphWithCurve
CLCurve mCurve
Protected Attributes inherited from CLGraphicalObject
CLBoundingBox mBBox
std::string mKey
std::string mModelObjectKey
std::string mObjectRole
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Friends
std::ostream & operator<< (std::ostream &os, const CLReferenceGlyph &g)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Graphical representation of a Link between different Glyphs. This correspondents to the sbml ReferenceGlyph.
Definition at line 75 of file CLReactionGlyph.h.
Constructor & Destructor Documentation
CLReferenceGlyph::CLReferenceGlyph (const std::string & name = "ReferenceGlyph", const CCopasiContainer * pParent = NULL)
Definition at line 107 of file CLReactionGlyph.cpp.
Referenced by clone().
   : CLGlyphWithCurve(name, pParent)
   , mGlyphKey()
   , mRole()
 {}
CLReferenceGlyph::CLReferenceGlyph (const CLReferenceGlyph & src, const CCopasiContainer * pParent = NULL)
Definition at line 114 of file CLReactionGlyph.cpp.
   : CLGlyphWithCurve(src, pParent)
   , mGlyphKey(src.mGlyphKey)
   , mRole(src.mRole)
 {}
Member Function Documentation
virtual CLGraphicalObject* CLReferenceGlyph::clone () const inline virtual
Reimplemented from CLGraphicalObject.
Definition at line 114 of file CLReactionGlyph.h.
References CLReferenceGlyph().
 {return new CLReferenceGlyph(*this, NULL);};
const std::string& CLReferenceGlyph::getRole () const inline
Definition at line 107 of file CLReactionGlyph.h.
References mRole.
Referenced by CLRenderResolver::resolveStyle().
 {return mRole;}
CLGraphicalObject * CLReferenceGlyph::getTargetGlyph () const
Definition at line 167 of file CLReactionGlyph.cpp.
References CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), and mGlyphKey.
Referenced by CCopasiSpringLayout::finalizeState(), operator<<(), and CCopasiSpringLayout::potGeneralEdge().
 {
   CCopasiObject* tmp = CCopasiRootContainer::getKeyFactory()->get(mGlyphKey);
   return dynamic_cast<CLMetabGlyph*>(tmp);
 }
const std::string& CLReferenceGlyph::getTargetGlyphKey () const inline
Definition at line 110 of file CLReactionGlyph.h.
References mGlyphKey.
Referenced by CLayout::CLayout().
 {return mGlyphKey;}
CLReferenceGlyph & CLReferenceGlyph::operator= (const CLReferenceGlyph & rhs)
assignment operator.
Definition at line 154 of file CLReactionGlyph.cpp.
References mGlyphKey, mRole, and CLGlyphWithCurve::operator=().
 {
   if (this == &rhs) return * this; //do nothing if lhs and rhs are the same
   CLGlyphWithCurve::operator=(rhs);
   //handle the specific glyph stuff:
   mGlyphKey = rhs.mGlyphKey;
   mRole = rhs.mRole;
   return *this;
 }
void CLReferenceGlyph::print (std::ostream * ostream) const virtual
This is the output method for any object. The default implementation provided with CCopasiObject uses the ostream operator<< of the object to print the object.To override this default behavior one needs to reimplement the virtual print function.
Parameters
std::ostream * ostream
Reimplemented from CLGlyphWithCurve.
Definition at line 225 of file CLReactionGlyph.cpp.
 {*ostream << *this;}
void CLReferenceGlyph::setRole (const std::string & r) inline
Definition at line 108 of file CLReactionGlyph.h.
References mRole.
Referenced by CCopasiSpringLayout::createLayout().
 {mRole = r;}
void CLReferenceGlyph::setTargetGlyphKey (const std::string & k) inline
Definition at line 112 of file CLReactionGlyph.h.
References mGlyphKey.
Referenced by CLayout::CLayout(), and CCopasiSpringLayout::createLayout().
 {mGlyphKey = k;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CLReferenceGlyph & g) friend
insert operator
Definition at line 210 of file CLReactionGlyph.cpp.
 {
   os << "    ReferenceGlyph: " << dynamic_cast<const CLGraphicalObject&>(g);
   const CLGraphicalObject* tmp = g.getTargetGlyph();
   if (tmp)
     os << "      refers to a Glyph that refers to "
        << tmp->getModelObjectDisplayName() << std::endl;
   os << g.mCurve; //TODO refer to base class?
   return os;
 }
Member Data Documentation
std::string CLReferenceGlyph::mGlyphKey protected
Key of a Glyph.
Definition at line 82 of file CLReactionGlyph.h.
Referenced by getTargetGlyph(), getTargetGlyphKey(), operator=(), and setTargetGlyphKey().
std::string CLReferenceGlyph::mRole protected
Definition at line 83 of file CLReactionGlyph.h.
Referenced by getRole(), operator=(), and setRole().
The documentation for this class was generated from the following files:
CLReactionGlyph.h
CLReactionGlyph.cpp