COPASI API: CModelValue Class Reference
CModelValue Class Reference
#include <CModelValue.h>
Public Member Functions
CModelValue (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CModelValue (const CModelValue &src, const CCopasiContainer *pParent=NULL)
~CModelValue ()
Public Member Functions inherited from CModelEntity
virtual void calculate ()
CModelEntity (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const std::string &type="ModelEntity", const unsigned C_INT32 &flag=CCopasiObject::Container|CCopasiObject::ValueDbl)
CModelEntity (const CModelEntity &src, const CCopasiContainer *pParent=NULL)
virtual bool compile ()
virtual std::set< const
CCopasiObject * > getDeletedObjects () const
std::string getExpression () const
const CExpression * getExpressionPtr () const
CExpression * getExpressionPtr ()
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CExpression * getInitialExpressionPtr ()
const C_FLOAT64 & getInitialValue () const
CCopasiObject * getInitialValueReference () const
virtual const std::string & getKey () const
const C_FLOAT64 & getRate () const
CCopasiObject * getRateReference () const
const std::string & getSBMLId () const
const CModelEntity::Status & getStatus () const
const C_FLOAT64 & getValue () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isFixed () const
const bool & isUsed () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void refreshInitialValue ()
bool setExpression (const std::string &expression)
bool setExpressionPtr (CExpression *pExpression)
bool setInitialExpression (const std::string &expression)
bool setInitialExpressionPtr (CExpression *pExpression)
virtual void setInitialValue (const C_FLOAT64 &initialValue)
void setInitialValuePtr (C_FLOAT64 *pInitialValue)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setRate (const C_FLOAT64 &rate)
void setSBMLId (const std::string &id)
virtual void setStatus (const CModelEntity::Status &status)
void setUsed (const bool &used)
virtual void setValue (const C_FLOAT64 &value)
void setValuePtr (C_FLOAT64 *pValue)
~CModelEntity ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Private Member Functions
void initObjects ()
Friends
std::ostream & operator<< (std::ostream &os, const CModelValue &d)
Additional Inherited Members
Public Types inherited from CModelEntity
enum Status {
FIXED = 0, ASSIGNMENT, REACTIONS, ODE,
TIME
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Static Public Attributes inherited from CModelEntity
static const std::string StatusName []
static const char * XMLStatus []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CModelEntity
CExpression * mpExpression
CExpression * mpInitialExpression
C_FLOAT64 * mpIValue
CCopasiObjectReference
< C_FLOAT64 > * mpIValueReference
CModel * mpModel
CCopasiObjectReference
< C_FLOAT64 > * mpRateReference
C_FLOAT64 * mpValue
CCopasiObjectReference
< C_FLOAT64 > * mpValueReference
C_FLOAT64 mRate
std::string mSBMLId
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CModelValue represents an entity in the model that has a value but is not a concentration (like species) or a volume (like compartments). It correspondents to global parameters in SBML
Definition at line 419 of file CModelValue.h.
Constructor & Destructor Documentation
CModelValue::CModelValue (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 650 of file CModelValue.cpp.
References CONSTRUCTOR_TRACE, and initObjects().
                                                           :
   CModelEntity(name, pParent, "ModelValue")
 {
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CModelValue::CModelValue (const CModelValue & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CModelValue & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 659 of file CModelValue.cpp.
References CONSTRUCTOR_TRACE, and initObjects().
                                                           :
   CModelEntity(src, pParent)
 {
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CModelValue::~CModelValue ()
Destructor.
Definition at line 667 of file CModelValue.cpp.
References DESTRUCTOR_TRACE.
 {
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
void CModelValue::initObjects () private
Initialize the contained CCopasiObjects
Definition at line 672 of file CModelValue.cpp.
Referenced by CModelValue().
 {}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CModelValue & d) friend
insert operator
Definition at line 675 of file CModelValue.cpp.
 {
   os << "    ++++CModelValue: " << d.getObjectName() << std::endl;
   os << "        mValue " << *d.mpValue << " mIValue " << *d.mpIValue << std::endl;
   os << "        mRate " << d.mRate << " mStatus " << d.getStatus() << std::endl;
   os << "    ----CModelValue " << std::endl;
   return os;
 }
The documentation for this class was generated from the following files:
CModelValue.h
CModelValue.cpp