COPASI API: CCopasiXMLParser::MetaboliteGlyphElement Class Reference
CCopasiXMLParser::MetaboliteGlyphElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
MetaboliteGlyphElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~MetaboliteGlyphElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { MetaboliteGlyph = 0, BoundingBox, Position, Dimensions }
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3362 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::MetaboliteGlyphElement::Element private
Enumerator
MetaboliteGlyph
BoundingBox
Position
Dimensions
Definition at line 3365 of file CCopasiXMLParser.h.
     {
       MetaboliteGlyph = 0,
       BoundingBox,
       Position,
       Dimensions
     };
Constructor & Destructor Documentation
CCopasiXMLParser::MetaboliteGlyphElement::MetaboliteGlyphElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Definition at line 6745 of file CCopasiXMLParser.cpp.
                                                                                                                        :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::MetaboliteGlyphElement::~MetaboliteGlyphElement () virtual
Definition at line 6750 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::MetaboliteGlyphElement::end (const XML_Char * pszName) virtual
Definition at line 6855 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "MetaboliteGlyph"))
     {
       mParser.popElementHandler();
       mCurrentElement = START_ELEMENT;
       /* Tell the parent element we are done. */
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case BoundingBox:
             break;
           case Position:
             break;
           case Dimensions:
             //tell the handler where to continue
             mCurrentElement = BoundingBox;
             break;
           case UNKNOWN_ELEMENT:
             mCurrentElement = MetaboliteGlyph;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::MetaboliteGlyphElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Definition at line 6753 of file CCopasiXMLParser.cpp.
References CLayout::addMetaboliteGlyph(), CCopasiMessage::EXCEPTION, CKeyFactory::get(), CModelEntity::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentLayout, SCopasiXMLParserCommon::pMetaboliteGlyph, CLGraphicalObject::setHeight(), CLGraphicalObject::setModelObjectKey(), CLGraphicalObject::setObjectRole(), CLGraphicalObject::setWidth(), CLGraphicalObject::setX(), CLGraphicalObject::setY(), UNKNOWN_ELEMENT, and CCopasiMessage::WARNING.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case MetaboliteGlyph:
         if (strcmp(pszName, "MetaboliteGlyph"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "MetaboliteGlyph", mParser.getCurrentLineNumber());
         {
           //workload
           const char * key;
           const char * name;
           const char * metabolite;
           key = mParser.getAttributeValue("key", papszAttrs);
           name = mParser.getAttributeValue("name", papszAttrs);
           metabolite = mParser.getAttributeValue("metabolite", papszAttrs, false);
           mCommon.pMetaboliteGlyph = new CLMetabGlyph(name);
           const char * objectRole = mParser.getAttributeValue("objectRole", papszAttrs, false);
           if (objectRole != NULL && objectRole[0] != 0)
             {
               mCommon.pMetaboliteGlyph->setObjectRole(objectRole);
             }
           if (metabolite && metabolite[0])
             {
               CMetab * pMetab = dynamic_cast< CMetab * >(mCommon.KeyMap.get(metabolite));
               if (!pMetab)
                 {
                   CCopasiMessage(CCopasiMessage::WARNING, MCXML + 19, "MetaboliteGlyph", key);
                 }
               else
                 {
                   mCommon.pMetaboliteGlyph->setModelObjectKey(pMetab->getKey());
                 }
             }
           mCommon.pCurrentLayout->addMetaboliteGlyph(mCommon.pMetaboliteGlyph);
           addFix(key, mCommon.pMetaboliteGlyph);
         }
         return;
         break;
       case BoundingBox:
         if (!strcmp(pszName, "BoundingBox"))
           return;
         break;
       case Position:
         if (!strcmp(pszName, "Position"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             mCommon.pMetaboliteGlyph->setX(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("y", papszAttrs);
             mCommon.pMetaboliteGlyph->setY(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Dimensions:
         if (!strcmp(pszName, "Dimensions"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("width", papszAttrs);
             mCommon.pMetaboliteGlyph->setWidth(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("height", papszAttrs);
             mCommon.pMetaboliteGlyph->setHeight(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::MetaboliteGlyphElement::mLineNumber private
Definition at line 3373 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp