COPASI API: CQLabelGraphicsItem Class Reference
CQLabelGraphicsItem Class Reference
#include <CQLabelGraphicsItem.h>
Public Member Functions
CQLabelGraphicsItem (const CLTextGlyph *textGlyph, const CLRenderResolver *resolver=NULL)
virtual ~CQLabelGraphicsItem ()
Public Member Functions inherited from CQCopasiGraphicsItem
CQCopasiGraphicsItem (const CLRenderResolver *resolver, const CLStyle *style)
const CLRenderResolver * getResolver () const
const CLStyle * getStyle () const
void setResolver (const CLRenderResolver *resolver)
void setStyle (const CLStyle *style)
virtual ~CQCopasiGraphicsItem ()
Additional Inherited Members
Protected Attributes inherited from CQCopasiGraphicsItem
const CLRenderResolver * mpResolver
const CLStyle * mpStyle
Detailed Description
Definition at line 14 of file CQLabelGraphicsItem.h.
Constructor & Destructor Documentation
CQLabelGraphicsItem::CQLabelGraphicsItem (const CLTextGlyph * textGlyph, const CLRenderResolver * resolver = NULL)
Definition at line 11 of file CQLabelGraphicsItem.cpp.
References CQRenderConverter::applyStyle(), CLGraphicalObject::getBoundingBox(), CLStyle::getGroup(), CLBoundingBox::getPosition(), CLPoint::getX(), CLPoint::getY(), CQCopasiGraphicsItem::mpResolver, and CQCopasiGraphicsItem::mpStyle.
   : QGraphicsTextItem(textGlyph->getText().c_str())
   , CQCopasiGraphicsItem(resolver, resolver != NULL ? resolver->resolveStyle(textGlyph) : NULL)
 {
   //setTextInteractionFlags(Qt::TextEditorInteraction);
   //setFlag(QGraphicsItem::ItemIsMovable);
   //setFlag(QGraphicsItem::ItemIsSelectable);
   setPos(textGlyph->getBoundingBox().getPosition().getX(),
          textGlyph->getBoundingBox().getPosition().getY());
   CQRenderConverter::applyStyle(this, &textGlyph->getBoundingBox(), mpStyle == NULL ? NULL : mpStyle->getGroup(), mpResolver);
 }
CQLabelGraphicsItem::~CQLabelGraphicsItem () virtual
Definition at line 25 of file CQLabelGraphicsItem.cpp.
 {
 }
The documentation for this class was generated from the following files:
CQLabelGraphicsItem.h
CQLabelGraphicsItem.cpp