COPASI API: SliderSettingsDialog Class Reference
SliderSettingsDialog Class Reference
#include <SliderSettingsDialog.h>
Signals
void sliderChanged (CSlider *slider)
Public Member Functions
virtual void disableObjectChoosing (bool disableChoosing)
virtual CSlider * getSlider ()
virtual void setDefinedSliders (std::vector< CSlider * > sliderVect)
virtual void setModel (CModel *model)
virtual void setSlider (CSlider *slider)
SliderSettingsDialog (QWidget *pParent=NULL)
virtual void updateSlider ()
virtual ~SliderSettingsDialog ()
Protected Types
enum CHANGETYPE {
NONE, OBJECT, MIN, MAX,
NUMTICKS, TICKSIZE, TICKFACTOR, ORIGVAL,
VALUE, LOGARITHMIC
}
Protected Slots
virtual void browseButtonPressed ()
virtual void cancelButtonPressed ()
virtual void extendedOptionsClicked ()
virtual void globalCheckBoxToggled ()
virtual void logCheckBoxToggled (bool on)
virtual void maxValueChanged ()
virtual void maxValueTextChanged ()
virtual void minorMajorFactorChanged ()
virtual void minorTickSizeChanged ()
virtual void minValueChanged ()
virtual void minValueTextChanged ()
virtual void numMinorTicksChanged ()
virtual void numTicksTextChanged ()
virtual void objectValueChanged ()
virtual void okButtonPressed ()
virtual void originalValueChanged ()
virtual void origValueTextChanged ()
virtual void tickFactorTextChanged ()
virtual void tickSizeTextChanged ()
virtual void valueTextChanged ()
Protected Member Functions
void hideOptionsControls ()
void init ()
void showOptionsControls ()
void updateInputFields ()
void updateInputFieldsValues ()
void updateInternalValues ()
Protected Attributes
CHANGETYPE mChanged
int mCurrentTaskId
std::vector< CSlider * > mDefinedSliders
double mMaxValue
unsigned int mMinorMajorFactor
double mMinorTickSize
double mMinValue
unsigned int mNumMinorTicks
double mOriginalValue
CModel * mpModel
CSlider * mpSlider
int mScaling
double mValue
Detailed Description
Definition at line 27 of file SliderSettingsDialog.h.
Member Enumeration Documentation
enum SliderSettingsDialog::CHANGETYPE protected
Enumerator
NONE
OBJECT
MIN
MAX
NUMTICKS
TICKSIZE
TICKFACTOR
ORIGVAL
VALUE
LOGARITHMIC
Definition at line 50 of file SliderSettingsDialog.h.
 {NONE, OBJECT, MIN, MAX, NUMTICKS, TICKSIZE, TICKFACTOR, ORIGVAL, VALUE, LOGARITHMIC};
Constructor & Destructor Documentation
SliderSettingsDialog::SliderSettingsDialog (QWidget * pParent = NULL)
Ctor.
Definition at line 31 of file SliderSettingsDialog.cpp.
References init().
                                                            :
   QDialog(pParent),
   mChanged(),
   mMinorTickSize(),
   mMaxValue(),
   mMinValue(),
   mValue(),
   mOriginalValue(),
   mMinorMajorFactor(),
   mNumMinorTicks(),
   mDefinedSliders(),
   mpSlider(NULL),
   mCurrentTaskId(),
   mpModel(NULL),
   mScaling()
 {
   setupUi(this);
   this->init();
 }
SliderSettingsDialog::~SliderSettingsDialog () virtual
Definition at line 51 of file SliderSettingsDialog.cpp.
 {
 }
Member Function Documentation
void SliderSettingsDialog::browseButtonPressed () protected virtual slot
Definition at line 369 of file SliderSettingsDialog.cpp.
References FROM_UTF8, CCopasiRootContainer::getDatamodelList(), CCopasiObject::getKey(), CCopasiObject::getObjectAncestor(), CCopasiObject::getObjectDisplayName(), CCopasiSelectionDialog::getObjectSingle(), CSlider::getSliderObject(), CQMessageBox::information(), CQSimpleSelectionTree::InitialTime, CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), mDefinedSliders, mpSlider, CQSimpleSelectionTree::Parameters, CSlider::resetRange(), CSlider::setAssociatedEntityKey(), setSlider(), CSlider::setSliderObject(), updateInputFields(), and updateInputFieldsValues().
 {
   const CCopasiObject * pObject =
     CCopasiSelectionDialog::getObjectSingle(this,
         CQSimpleSelectionTree::InitialTime |
         CQSimpleSelectionTree::Parameters);
   if (pObject)
     {
       if (!pObject->isValueDbl() && !pObject->isValueInt())
         {
           CQMessageBox::information(this, "Invalid Object",
                                     "You chose an object that does not correspond to an integer or float value. Please choose an object that corresponds to an integet or float value.",
                                     QMessageBox::Ok, QMessageBox::Ok);
           mpSlider = NULL;
           mpObjectNameLineEdit->setText("");
           return;
         }
       /* Determine the associated entity key */
       CCopasiContainer * pAncestor = pObject->getObjectAncestor("Task");
       if (!pAncestor) pAncestor = pObject->getObjectAncestor("Model");
       if (!pAncestor)
         {
           CQMessageBox::information(this, "Invalid Object",
                                     "You chose an object that cannot be used as a slider. Please choose an other object.",
                                     QMessageBox::Ok, QMessageBox::Ok);
           mpSlider = NULL;
           mpObjectNameLineEdit->setText("");
           return;
         }
       // We do not have a slider therefore we create one.
       if (mpSlider == NULL)
         {
           // temporarily add the slider the the first datamodel
           mpSlider = new CSlider("slider", (*CCopasiRootContainer::getDatamodelList())[0]);
           mpSlider->setSliderObject(const_cast< CCopasiObject * >(pObject));
           if (pAncestor)
             mpSlider->setAssociatedEntityKey(pAncestor->getKey());
           mpSlider->resetRange();
           updateInputFields();
           updateInputFieldsValues();
           mpObjectNameLineEdit->setText(FROM_UTF8(mpSlider->getSliderObject()->getObjectDisplayName()));
           return;
         }
       // If the object of an existing slider has not changed we have nothing to do
       if (mpSlider->getSliderObject() == pObject)
         return;
       // Check whether a slider with the object already exists
       size_t i, iMax = mDefinedSliders.size();
       for (i = 0; i < iMax; ++i)
         if (mDefinedSliders[i]->getSliderObject() == pObject)
           break;
       // A slider with the new object exists we switch to it.
       if (i != iMax)
         setSlider(mDefinedSliders[i]);
       else // We need to change the object an reinitialize the slider
         {
           mpSlider->setSliderObject(const_cast< CCopasiObject * >(pObject));
           if (pAncestor)
             mpSlider->setAssociatedEntityKey(pAncestor->getKey());
           mpSlider->resetRange();
           updateInputFields();
           updateInputFieldsValues();
         }
       mpObjectNameLineEdit->setText(FROM_UTF8(mpSlider->getSliderObject()->getObjectDisplayName()));
     }
 }
void SliderSettingsDialog::cancelButtonPressed () protected virtual slot
Definition at line 183 of file SliderSettingsDialog.cpp.
 {
   // close dialog, drop input
   close();
 }
void SliderSettingsDialog::disableObjectChoosing (bool disableChoosing) virtual
Definition at line 456 of file SliderSettingsDialog.cpp.
 {
   mpObjectBrowseButton->setHidden(disableChoosing);
 }
void SliderSettingsDialog::extendedOptionsClicked () protected virtual slot
Definition at line 486 of file SliderSettingsDialog.cpp.
References hideOptionsControls(), and showOptionsControls().
 {
   if (mpExtendedOptionsButton->text() == "Advanced >>")
     {
       mpExtendedOptionsButton->setText("Advanced <<");
       showOptionsControls();
       this->setFixedSize(minimumSizeHint());
     }
   else
     {
       mpExtendedOptionsButton->setText("Advanced >>");
       hideOptionsControls();
       int heightChange = mpOptionsGridLayout->geometry().height();
       QSize size = this->size() - QSize(0, heightChange);
       this->setFixedSize(size);
     }
 }
CSlider * SliderSettingsDialog::getSlider () virtual
Definition at line 55 of file SliderSettingsDialog.cpp.
References mpSlider.
Referenced by SliderDialog::editSlider().
 {
   return mpSlider;
 }
void SliderSettingsDialog::globalCheckBoxToggled () protected virtual slot
Definition at line 531 of file SliderSettingsDialog.cpp.
References updateInternalValues().
 {
   updateInternalValues();
 }
void SliderSettingsDialog::hideOptionsControls () protected
Definition at line 638 of file SliderSettingsDialog.cpp.
Referenced by extendedOptionsClicked(), and init().
 {
   mpNumMinorTicksLabel->hide();
   mpNumMinorTicksEdit->hide();
   mpMinorTickSizeLabel->hide();
   mpMinorTickSizeEdit->hide();
   mpMinorMajorFactorLabel->hide();
   mpMinorMajorFactorEdit->hide();
   mpOriginalValueLabel->hide();
   mpOriginalValueEdit->hide();
   mpObjectValueLabel->hide();
   mpObjectValueEdit->hide();
 }
void SliderSettingsDialog::init () protected
Definition at line 346 of file SliderSettingsDialog.cpp.
References CQIconResource::copasi, hideOptionsControls(), CQIconResource::icon(), CSlider::linear, mChanged, mpSlider, mScaling, NONE, and updateInputFields().
Referenced by SliderSettingsDialog().
 {
   mpSlider = NULL;
   mChanged = NONE;
   mScaling = CSlider::linear;
   mpObjectBrowseButton->setIcon(CQIconResource::icon(CQIconResource::copasi));
   mpExtendedOptionsButton->setText("Advanced >>");
   hideOptionsControls();
   this->setFixedSize(minimumSizeHint());
   mpObjectValueEdit->setValidator(new QDoubleValidator(this));
   mpOriginalValueEdit->setValidator(new QDoubleValidator(this));
   mpMinValueEdit->setValidator(new QDoubleValidator(this));
   mpMaxValueEdit->setValidator(new QDoubleValidator(this));
   mpMinorTickSizeEdit->setValidator(new QDoubleValidator(this));
   QIntValidator* v = new QIntValidator(this);
   v->setBottom(0);
   mpNumMinorTicksEdit->setValidator(v);
   v = new QIntValidator(this);
   v->setBottom(0);
   mpMinorMajorFactorEdit->setValidator(v);
   updateInputFields();
 }
void SliderSettingsDialog::logCheckBoxToggled (bool on) protected virtual slot
Definition at line 504 of file SliderSettingsDialog.cpp.
References CQMessageBox::information(), CSlider::linear, CSlider::logarithmic, LOGARITHMIC, mChanged, mMinValue, mScaling, and updateInternalValues().
 {
   updateInternalValues();
   mChanged = LOGARITHMIC;
   if (on)
     {
       // check if the minValue is 0.0 or negative if so, issue an error message and uncheck the checkbox again
       if (mMinValue <= 0.0)
         {
           CQMessageBox::information(this, "Incorrect min value",
                                     "For logarithmic sliders, the minimum value may not be 0.0 or negative. Please set the minimum value to some (possibly very small) positive number first.",
                                     QMessageBox::Ok, QMessageBox::Ok);
           mpLogCheckBox->setChecked(false);
           mScaling = CSlider::linear;
         }
       else
         {
           mScaling = CSlider::logarithmic;
         }
     }
   else
     {
       mScaling = CSlider::linear;
     }
 }
void SliderSettingsDialog::maxValueChanged () protected virtual slot
Definition at line 278 of file SliderSettingsDialog.cpp.
References mChanged, mMaxValue, mMinorTickSize, mMinValue, mNumMinorTicks, mOriginalValue, mValue, NONE, and CQMessageBox::question().
Referenced by updateInternalValues().
 {
   // check if it is larget then the current value
   // else set it to the current value
   double value = mpMaxValueEdit->text().toDouble();
   if (value < mOriginalValue)
     {
       if (CQMessageBox::question(this, "Default value out of range.",
                                  "The maximum value you set is smaller than the default value of the slider. The new default will be set to the maximum. Do you want to procceed?",
                                  QMessageBox::Ok | QMessageBox::Cancel, QMessageBox::Cancel) != QMessageBox::Ok)
         {
           mpMaxValueEdit->setText(QString::number(mMaxValue));
           mChanged = NONE;
           return;
         }
       mOriginalValue = value;
       mpOriginalValueEdit->setText(QString::number(mOriginalValue));
     }
   mMaxValue = value;
   if (mMinValue > mMaxValue)
     {
       mMinValue = mMaxValue;
       mpMinValueEdit->setText(QString::number(mMinValue));
     }
   if (mMaxValue < mValue)
     {
       mValue = mMaxValue;
       mpObjectValueEdit->setText(QString::number(mValue));
     }
   mMinorTickSize = (mMaxValue - mMinValue) / mNumMinorTicks;
   mpMinorTickSizeEdit->setText(QString::number(mMinorTickSize));
   mChanged = NONE;
 }
void SliderSettingsDialog::maxValueTextChanged () protected virtual slot
Definition at line 592 of file SliderSettingsDialog.cpp.
References MAX, and mChanged.
 {
   mChanged = MAX;
 }
void SliderSettingsDialog::minorMajorFactorChanged () protected virtual slot
Definition at line 339 of file SliderSettingsDialog.cpp.
References mChanged, mMinorMajorFactor, and NONE.
Referenced by updateInternalValues().
 {
   // get the value and set it in the current slider
   mMinorMajorFactor = mpMinorMajorFactorEdit->text().toUInt();
   mChanged = NONE;
 }
void SliderSettingsDialog::minorTickSizeChanged () protected virtual slot
Definition at line 189 of file SliderSettingsDialog.cpp.
References mChanged, mMaxValue, mMinorTickSize, mMinValue, mNumMinorTicks, and NONE.
Referenced by updateInternalValues().
 {
   // adjust numMinorTicks
   mMinorTickSize = mpMinorTickSizeEdit->text().toDouble();
   if (mMinorTickSize == 0.0)
     {
       mNumMinorTicks = 1;
     }
   else
     {
       mNumMinorTicks = (unsigned int)floor(((mMaxValue - mMinValue) / mMinorTickSize) + 0.5);
     }
   if (mNumMinorTicks == 0)
     {
       mNumMinorTicks = 1;
       mMinorTickSize = mMaxValue - mMinValue;
       mpMinorTickSizeEdit->setText(QString::number(mMinorTickSize));
     }
   mpNumMinorTicksEdit->setText(QString::number(mNumMinorTicks));
   mChanged = NONE;
 }
void SliderSettingsDialog::minValueChanged () protected virtual slot
Definition at line 230 of file SliderSettingsDialog.cpp.
References CQMessageBox::information(), CSlider::linear, mChanged, mMaxValue, mMinorTickSize, mMinValue, mNumMinorTicks, mOriginalValue, mScaling, mValue, NONE, and CQMessageBox::question().
Referenced by updateInternalValues().
 {
   // check if it is smaller than the current value
   // if not, set it to the current value
   double value = mpMinValueEdit->text().toDouble();
   if ((value > mOriginalValue) &&
       (CQMessageBox::question(this, "Default value out of range.",
                               "The minimum value you set is larger than the default value of the slider. The new default will be set to the minimum. Do you want to procceed?",
                               QMessageBox::Ok | QMessageBox::Cancel, QMessageBox::Cancel) != QMessageBox::Ok)
      )
     {
       mpMinValueEdit->setText(QString::number(mMinValue));
     }
   else
     {
       mOriginalValue = value;
       mpOriginalValueEdit->setText(QString::number(mOriginalValue));
       mMinValue = value;
       if (mMinValue > mMaxValue)
         {
           mMaxValue = mMinValue;
           mpMaxValueEdit->setText(QString::number(mMaxValue));
         }
       if (mMinValue > mValue)
         {
           mValue = mMinValue;
           mpObjectValueEdit->setText(QString::number(mValue));
         }
       mMinorTickSize = (mMaxValue - mMinValue) / mNumMinorTicks;
       mpMinorTickSizeEdit->setText(QString::number(mMinorTickSize));
       if (mMinValue <= 0.0 && mpLogCheckBox->isChecked())
         {
           CQMessageBox::information(this, "Incorrect min value",
                                     "For logarithmic sliders, the minimum value may not be 0.0 or negative. Please set the minimum value to some (possibly very small) positive number first.",
                                     QMessageBox::Ok, QMessageBox::Ok);
           mpLogCheckBox->setChecked(false);
           mScaling = CSlider::linear;
         }
     }
   mChanged = NONE;
 }
void SliderSettingsDialog::minValueTextChanged () protected virtual slot
Definition at line 587 of file SliderSettingsDialog.cpp.
References mChanged, and MIN.
 {
   mChanged = MIN;
 }
void SliderSettingsDialog::numMinorTicksChanged () protected virtual slot
Definition at line 214 of file SliderSettingsDialog.cpp.
References mChanged, mMaxValue, mMinorTickSize, mMinValue, mNumMinorTicks, and NONE.
Referenced by updateInputFieldsValues(), and updateInternalValues().
 {
   // adjust minorTickSize
   mNumMinorTicks = mpNumMinorTicksEdit->text().toUInt();
   if (mNumMinorTicks == 1)
     {
       mNumMinorTicks = 1;
       mpNumMinorTicksEdit->setText(QString::number(mNumMinorTicks));
     }
   mMinorTickSize = (mMaxValue - mMinValue) / mNumMinorTicks;
   mpMinorTickSizeEdit->setText(QString::number(mMinorTickSize));
   mChanged = NONE;
 }
void SliderSettingsDialog::numTicksTextChanged () protected virtual slot
Definition at line 597 of file SliderSettingsDialog.cpp.
References mChanged, and NUMTICKS.
 {
   mChanged = NUMTICKS;
 }
void SliderSettingsDialog::objectValueChanged () protected virtual slot
Definition at line 318 of file SliderSettingsDialog.cpp.
References mChanged, mMaxValue, mMinValue, mValue, and NONE.
Referenced by updateInternalValues().
 {
   // check if the value is within range, else set a new range
   // get the value and set it in the current slider
   mValue = mpObjectValueEdit->text().toDouble();
   if (mValue > mMaxValue)
     {
       mMaxValue = mValue;
       mpMaxValueEdit->setText(QString::number(mMaxValue));
     }
   if (mValue < mMinValue)
     {
       mMinValue = mValue;
       mpMinValueEdit->setText(QString::number(mMinValue));
     }
   mChanged = NONE;
 }
void SliderSettingsDialog::okButtonPressed () protected virtual slot
Definition at line 169 of file SliderSettingsDialog.cpp.
References updateSlider().
 {
   // disconnect all signal receivers from
   // the min and max value edit fields
   // otherwise, they would generate an
   // uneccesary focusLost signal
   disconnect(mpMinValueEdit, 0, 0, 0);
   disconnect(mpMaxValueEdit, 0, 0, 0);
   // only now change underlying slider
   updateSlider();
   // close dialog with positive feedback
   done(QDialog::Accepted);
 }
void SliderSettingsDialog::originalValueChanged () protected virtual slot
Definition at line 566 of file SliderSettingsDialog.cpp.
References mChanged, mMaxValue, mMinValue, mOriginalValue, and NONE.
Referenced by updateInternalValues().
 {
   // check if the value is within range, else set it to
   // set new values for the range
   mOriginalValue = mpOriginalValueEdit->text().toDouble();
   if (mOriginalValue > mMaxValue)
     {
       mMaxValue = mOriginalValue;
       mpMaxValueEdit->setText(QString::number(mMaxValue));
     }
   if (mOriginalValue < mMinValue)
     {
       mMinValue = mOriginalValue;
       mpMinValueEdit->setText(QString::number(mMinValue));
     }
   mChanged = NONE;
 }
void SliderSettingsDialog::origValueTextChanged () protected virtual slot
Definition at line 612 of file SliderSettingsDialog.cpp.
References mChanged, and ORIGVAL.
 {
   mChanged = ORIGVAL;
 }
void SliderSettingsDialog::setDefinedSliders (std::vector< CSlider * > sliderVect) virtual
Definition at line 100 of file SliderSettingsDialog.cpp.
References mDefinedSliders.
Referenced by SliderDialog::editSlider().
 {
   mDefinedSliders = sliderVect;
 }
void SliderSettingsDialog::setModel (CModel * model) virtual
Definition at line 451 of file SliderSettingsDialog.cpp.
References mpModel.
Referenced by SliderDialog::editSlider().
 {
   mpModel = model;
 }
void SliderSettingsDialog::setSlider (CSlider * slider) virtual
Definition at line 60 of file SliderSettingsDialog.cpp.
References FROM_UTF8, CCopasiObject::getObjectDisplayName(), CSlider::getSliderObject(), mDefinedSliders, mpSlider, updateInputFields(), and updateInputFieldsValues().
Referenced by browseButtonPressed(), and SliderDialog::editSlider().
 {
   size_t i;
   size_t iMax = mDefinedSliders.size();
   bool found = false;
   for (i = 0; i < iMax; ++i)
     {
       if (mDefinedSliders[i] == slider)
         {
           found = true;
           break;
         }
     }
   if (found)
     {
       mpSlider = slider;
       if (slider->getSliderObject())
         {
           mpObjectNameLineEdit->setText(FROM_UTF8(slider->getSliderObject()->getObjectDisplayName()));
         }
       else
         {
           mpObjectNameLineEdit->setText("Object not avalable!");
         }
       updateInputFields();
       updateInputFieldsValues();
     }
   else
     {
       mpSlider = NULL;
       mpObjectNameLineEdit->setText("NULL");
       mpObjectBrowseButton->show();
       updateInputFields();
     }
 }
void SliderSettingsDialog::showOptionsControls () protected
Definition at line 622 of file SliderSettingsDialog.cpp.
Referenced by extendedOptionsClicked().
 {
   mpNumMinorTicksLabel->show();
   mpNumMinorTicksEdit->show();
   mpMinorTickSizeLabel->show();
   mpMinorTickSizeEdit->show();
   mpMinorMajorFactorLabel->show();
   mpMinorMajorFactorEdit->show();
   mpOriginalValueLabel->show();
   mpOriginalValueEdit->show();
   mpObjectValueLabel->show();
   mpObjectValueEdit->show();
 }
void SliderSettingsDialog::sliderChanged (CSlider * slider) signal
void SliderSettingsDialog::tickFactorTextChanged () protected virtual slot
Definition at line 607 of file SliderSettingsDialog.cpp.
References mChanged, and TICKFACTOR.
 {
   mChanged = TICKFACTOR;
 }
void SliderSettingsDialog::tickSizeTextChanged () protected virtual slot
Definition at line 602 of file SliderSettingsDialog.cpp.
References mChanged, and TICKSIZE.
 {
   mChanged = TICKSIZE;
 }
void SliderSettingsDialog::updateInputFields () protected
Definition at line 140 of file SliderSettingsDialog.cpp.
References mpSlider.
Referenced by browseButtonPressed(), init(), and setSlider().
 {
   // if the current slider is NULL, disable all input fields
   if (mpSlider)
     {
       mpObjectNameLineEdit->setEnabled(false);
       mpMaxValueEdit->setEnabled(true);
       mpMinValueEdit->setEnabled(true);
       mpMinorMajorFactorEdit->setEnabled(true);
       mpMinorTickSizeEdit->setEnabled(true);
       mpNumMinorTicksEdit->setEnabled(true);
       mpObjectValueEdit->setEnabled(true);
       mpLogCheckBox->setEnabled(true);
       mpOriginalValueEdit->setEnabled(true);
     }
   else
     {
       mpObjectNameLineEdit->setEnabled(true);
       mpMaxValueEdit->setEnabled(false);
       mpMinValueEdit->setEnabled(false);
       mpMinorMajorFactorEdit->setEnabled(false);
       mpMinorTickSizeEdit->setEnabled(false);
       mpNumMinorTicksEdit->setEnabled(false);
       mpObjectValueEdit->setEnabled(false);
       mpOriginalValueEdit->setEnabled(false);
       mpLogCheckBox->setEnabled(false);
     }
 }
void SliderSettingsDialog::updateInputFieldsValues () protected
Definition at line 105 of file SliderSettingsDialog.cpp.
References CSlider::getMaxValue(), CSlider::getMinValue(), CSlider::getOriginalValue(), CSlider::getScaling(), CSlider::getSliderValue(), CSlider::getTickFactor(), CSlider::getTickNumber(), CSlider::logarithmic, mMaxValue, mMinorMajorFactor, mMinValue, mNumMinorTicks, mOriginalValue, mpSlider, mValue, and numMinorTicksChanged().
Referenced by browseButtonPressed(), and setSlider().
 {
   if (mpSlider)
     {
       mValue = mpSlider->getSliderValue();
       mpObjectValueEdit->setText(QString::number(mValue));
       mOriginalValue = mpSlider->getOriginalValue();
       mpOriginalValueEdit->setText(QString::number(mOriginalValue));
       mMinValue = mpSlider->getMinValue();
       mpMinValueEdit->setText(QString::number(mMinValue));
       mMaxValue = mpSlider->getMaxValue();
       mpMaxValueEdit->setText(QString::number(mMaxValue));
       mNumMinorTicks = mpSlider->getTickNumber();
       mpNumMinorTicksEdit->setText(QString::number(mNumMinorTicks));
       mMinorMajorFactor = mpSlider->getTickFactor();
       mpMinorMajorFactorEdit->setText(QString::number(mMinorMajorFactor));
       numMinorTicksChanged();
       if (mpSlider->getScaling() == CSlider::logarithmic)
         {
           mpLogCheckBox->setChecked(true);
         }
       else
         {
           mpLogCheckBox->setChecked(false);
         }
     }
 }
void SliderSettingsDialog::updateInternalValues () protected
Definition at line 536 of file SliderSettingsDialog.cpp.
References MAX, maxValueChanged(), mChanged, MIN, minorMajorFactorChanged(), minorTickSizeChanged(), minValueChanged(), numMinorTicksChanged(), NUMTICKS, objectValueChanged(), originalValueChanged(), ORIGVAL, TICKFACTOR, TICKSIZE, and VALUE.
Referenced by globalCheckBoxToggled(), logCheckBoxToggled(), and updateSlider().
 {
   switch (mChanged)
     {
       case VALUE:
         objectValueChanged();
         break;
       case ORIGVAL:
         originalValueChanged();
         break;
       case MIN:
         minValueChanged();
         break;
       case MAX:
         maxValueChanged();
         break;
       case TICKFACTOR:
         minorMajorFactorChanged();
         break;
       case TICKSIZE:
         minorTickSizeChanged();
         break;
       case NUMTICKS:
         numMinorTicksChanged();
         break;
       default:
         break;
     }
 }
void SliderSettingsDialog::updateSlider () virtual
Definition at line 461 of file SliderSettingsDialog.cpp.
References mMaxValue, mMinorMajorFactor, mMinValue, mNumMinorTicks, mOriginalValue, mpSlider, mScaling, mValue, CSlider::setMaxValue(), CSlider::setMinValue(), CSlider::setOriginalValue(), CSlider::setScaling(), CSlider::setSliderValue(), CSlider::setTickFactor(), CSlider::setTickNumber(), and updateInternalValues().
Referenced by okButtonPressed().
 {
   updateInternalValues();
   if (mpSlider)
     {
       if (mMinValue < mpSlider->getMaxValue())
         {
           mpSlider->setMinValue(mMinValue);
           mpSlider->setMaxValue(mMaxValue);
         }
       else
         {
           mpSlider->setMaxValue(mMaxValue);
           mpSlider->setMinValue(mMinValue);
         }
       mpSlider->setSliderValue(mValue);
       mpSlider->setTickNumber(mNumMinorTicks);
       mpSlider->setTickFactor(mMinorMajorFactor);
       mpSlider->setScaling((CSlider::Scale)mScaling);
       mpSlider->setOriginalValue(mOriginalValue);
     }
 }
void SliderSettingsDialog::valueTextChanged () protected virtual slot
Definition at line 617 of file SliderSettingsDialog.cpp.
References mChanged, and VALUE.
 {
   mChanged = VALUE;
 }
Member Data Documentation
CHANGETYPE SliderSettingsDialog::mChanged protected
Definition at line 51 of file SliderSettingsDialog.h.
Referenced by init(), logCheckBoxToggled(), maxValueChanged(), maxValueTextChanged(), minorMajorFactorChanged(), minorTickSizeChanged(), minValueChanged(), minValueTextChanged(), numMinorTicksChanged(), numTicksTextChanged(), objectValueChanged(), originalValueChanged(), origValueTextChanged(), tickFactorTextChanged(), tickSizeTextChanged(), updateInternalValues(), and valueTextChanged().
int SliderSettingsDialog::mCurrentTaskId protected
Definition at line 61 of file SliderSettingsDialog.h.
std::vector< CSlider* > SliderSettingsDialog::mDefinedSliders protected
Definition at line 59 of file SliderSettingsDialog.h.
Referenced by browseButtonPressed(), setDefinedSliders(), and setSlider().
double SliderSettingsDialog::mMaxValue protected
Definition at line 53 of file SliderSettingsDialog.h.
Referenced by maxValueChanged(), minorTickSizeChanged(), minValueChanged(), numMinorTicksChanged(), objectValueChanged(), originalValueChanged(), updateInputFieldsValues(), and updateSlider().
unsigned int SliderSettingsDialog::mMinorMajorFactor protected
Definition at line 57 of file SliderSettingsDialog.h.
Referenced by minorMajorFactorChanged(), updateInputFieldsValues(), and updateSlider().
double SliderSettingsDialog::mMinorTickSize protected
Definition at line 52 of file SliderSettingsDialog.h.
Referenced by maxValueChanged(), minorTickSizeChanged(), minValueChanged(), and numMinorTicksChanged().
double SliderSettingsDialog::mMinValue protected
Definition at line 54 of file SliderSettingsDialog.h.
Referenced by logCheckBoxToggled(), maxValueChanged(), minorTickSizeChanged(), minValueChanged(), numMinorTicksChanged(), objectValueChanged(), originalValueChanged(), updateInputFieldsValues(), and updateSlider().
unsigned int SliderSettingsDialog::mNumMinorTicks protected
Definition at line 58 of file SliderSettingsDialog.h.
Referenced by maxValueChanged(), minorTickSizeChanged(), minValueChanged(), numMinorTicksChanged(), updateInputFieldsValues(), and updateSlider().
double SliderSettingsDialog::mOriginalValue protected
Definition at line 56 of file SliderSettingsDialog.h.
Referenced by maxValueChanged(), minValueChanged(), originalValueChanged(), updateInputFieldsValues(), and updateSlider().
CModel* SliderSettingsDialog::mpModel protected
Definition at line 62 of file SliderSettingsDialog.h.
Referenced by setModel().
CSlider* SliderSettingsDialog::mpSlider protected
Definition at line 60 of file SliderSettingsDialog.h.
Referenced by browseButtonPressed(), getSlider(), init(), setSlider(), updateInputFields(), updateInputFieldsValues(), and updateSlider().
int SliderSettingsDialog::mScaling protected
Definition at line 63 of file SliderSettingsDialog.h.
Referenced by init(), logCheckBoxToggled(), minValueChanged(), and updateSlider().
double SliderSettingsDialog::mValue protected
Definition at line 55 of file SliderSettingsDialog.h.
Referenced by maxValueChanged(), minValueChanged(), objectValueChanged(), updateInputFieldsValues(), and updateSlider().
The documentation for this class was generated from the following files:
SliderSettingsDialog.h
SliderSettingsDialog.cpp