COPASI API: CQIconResource Class Reference
CQIconResource Class Reference
#include <CQIconResource.h>
Public Types
enum IconID {
bars = 0, captureImage, checkMark, copasi,
edit, editAdd, editCopy, editDelete,
fileAdd, fileExport, fileNew, fileOpen,
filePrint, fileSave, fileSaveas, isToS,
locked, miriam, moveDown, moveUp,
parameterConflict, parameterMissing, parameterModified, parameterObsolete,
playerKill, playerPause, playerStart, playerStop,
preferences, reactionModifier, reactionProduct, reactionSubstrate,
renderMarkup, renderMathML, separator, slider,
sToIs, table, tool, unlocked,
zoomOut, play, pause, stop,
backward, forward, skipBackward, skipForward,
roll, viewmagMinus, viewmagPlus, viewmag1,
viewmagfit, unknown, _size
}
Static Public Member Functions
static const QIcon & icon (const IconID &id)
Static Private Member Functions
static void init ()
Static Private Attributes
static QVector< QIcon > Icons
static bool needInit
Detailed Description
Definition at line 12 of file CQIconResource.h.
Member Enumeration Documentation
enum CQIconResource::IconID
Enumerator
bars
captureImage
checkMark
copasi
edit
editAdd
editCopy
editDelete
fileAdd
fileExport
fileNew
fileOpen
filePrint
fileSave
fileSaveas
isToS
locked
miriam
moveDown
moveUp
parameterConflict
parameterMissing
parameterModified
parameterObsolete
playerKill
playerPause
playerStart
playerStop
preferences
reactionModifier
reactionProduct
reactionSubstrate
renderMarkup
renderMathML
separator
slider
sToIs
table
tool
unlocked
zoomOut
play
pause
stop
backward
forward
skipBackward
skipForward
roll
viewmagMinus
viewmagPlus
viewmag1
viewmagfit
unknown
_size
Definition at line 15 of file CQIconResource.h.
   {
     bars = 0,
     captureImage,
     checkMark,
     copasi,
     edit,
     editAdd,
     editCopy,
     editDelete,
     fileAdd,
     fileExport,
     fileNew,
     fileOpen,
     filePrint,
     fileSave,
     fileSaveas,
     isToS,
     locked,
     miriam,
     moveDown,
     moveUp,
     parameterConflict,
     parameterMissing,
     parameterModified,
     parameterObsolete,
     playerKill,
     playerPause,
     playerStart,
     playerStop,
     preferences,
     reactionModifier,
     reactionProduct,
     reactionSubstrate,
     renderMarkup,
     renderMathML,
     separator,
     slider,
     sToIs,
     table,
     tool,
     unlocked,
     zoomOut,
     play,
     pause,
     stop,
     backward,
     forward,
     skipBackward,
     skipForward,
     roll,
     viewmagMinus,
     viewmagPlus,
     viewmag1,
     viewmagfit,
     // This is the default icon which is empty
     unknown,
     // This must be the last entry to automatically determine the size!
     _size
   };
Member Function Documentation
const QIcon & CQIconResource::icon (const IconID & id) static
Definition at line 90 of file CQIconResource.cpp.
References _size, Icons, init(), and unknown.
Referenced by BandedGraphWidget::BandedGraphWidget(), CopasiSlider::CopasiSlider(), CopasiUI3Window::CopasiUI3Window(), CQAnimationControls::CQAnimationControls(), CQCrossSectionTaskWidget::CQCrossSectionTaskWidget(), CQExpressionMmlStackedWidget::CQExpressionMmlStackedWidget(), CQFittingItemWidget::CQFittingItemWidget(), CQLayoutMainWindow::CQLayoutMainWindow(), CQLayoutsWidget::CQLayoutsWidget(), CQNewMainWindow::CQNewMainWindow(), CQNotes::CQNotes(), CQReportDefinitionSelect::CQReportDefinitionSelect(), CQLayoutView::createActions(), CQPlayerControlWidget::createActions(), CopasiUI3Window::createActions(), CQNewMainWindow::createActions(), CQArrayAnnotationsWidget::createBarChart(), createControl(), CScanWidgetRandom::CScanWidgetRandom(), CScanWidgetScan::CScanWidgetScan(), Curve2DWidget::Curve2DWidget(), CQParameterOverviewDM::diffData(), HistoWidget::HistoWidget(), CQMoietiesTaskResult::init(), CQAnimationWindow::init(), SensitivitiesWidget::init(), CQProgressDialog::init(), CUpDownSubwidget::init(), CQEventWidget1::init(), SliderSettingsDialog::init(), CQExperimentData::init(), PlotWindow::PlotWindow(), SliderDialog::SliderDialog(), CQPlayerControlWidget::slot_pause_clicked(), CQPlayerControlWidget::slot_play_clicked(), CQAnimationControls::slotStop(), CQAnimationWindow::slotStopLayout(), CQNotes::slotToggleMode(), CQAnimationControls::slotTogglePlayPause(), CQNotes::slotValidateXML(), CQArrayAnnotationsWidget::switchToBarChart(), CQArrayAnnotationsWidget::switchToTable(), CQAnimationWindow::toggleUI(), CQPlayerControlWidget::updateButtons(), and ParameterTable::updateTable().
 {
   init();
   if (id < _size)
     return Icons[id];
   return Icons[unknown];
 }
void CQIconResource::init () static private
Definition at line 24 of file CQIconResource.cpp.
References _size, backward, bars, captureImage, checkMark, copasi, edit, editAdd, editCopy, editDelete, fileAdd, fileExport, fileNew, fileOpen, filePrint, fileSave, fileSaveas, forward, Icons, isToS, locked, miriam, moveDown, moveUp, needInit, parameterConflict, parameterMissing, parameterModified, parameterObsolete, pause, play, playerKill, playerPause, playerStart, playerStop, preferences, reactionModifier, reactionProduct, reactionSubstrate, renderMarkup, renderMathML, roll, separator, skipBackward, skipForward, slider, sToIs, stop, table, tool, unlocked, viewmag1, viewmagfit, viewmagMinus, viewmagPlus, and zoomOut.
Referenced by icon().
 {
   if (!needInit) return;
   Q_INIT_RESOURCE(copasi);
   Icons.resize(_size);
   Icons[bars].addFile(QString::fromUtf8(":/images/bars.png"), QSize(), QIcon::Normal, QIcon::Off);
   Icons[captureImage].addFile(QString::fromUtf8(":/images/captureImage.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[copasi].addFile(QString::fromUtf8(":/images/copasi.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[checkMark].addFile(QString::fromUtf8(":/images/checkMark.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[edit].addFile(QString::fromUtf8(":/images/edit.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[editAdd].addFile(QString::fromUtf8(":/images/editAdd.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[editCopy].addFile(QString::fromUtf8(":/images/editCopy.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[editDelete].addFile(QString::fromUtf8(":/images/editDelete.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[fileAdd].addFile(QString::fromUtf8(":/images/fileAdd.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[fileExport].addFile(QString::fromUtf8(":/images/fileExport.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[fileNew].addFile(QString::fromUtf8(":/images/fileNew.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[fileOpen].addFile(QString::fromUtf8(":/images/fileOpen.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[filePrint].addFile(QString::fromUtf8(":/images/filePrint.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[fileSave].addFile(QString::fromUtf8(":/images/fileSave.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[fileSaveas].addFile(QString::fromUtf8(":/images/fileSaveas.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[isToS].addFile(QString::fromUtf8(":/images/isToS.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[locked].addFile(QString::fromUtf8(":/images/locked.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[miriam].addFile(QString::fromUtf8(":/images/miriam.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[moveDown].addFile(QString::fromUtf8(":/images/moveDown.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[moveUp].addFile(QString::fromUtf8(":/images/moveUp.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[parameterConflict].addFile(QString::fromUtf8(":/images/parameterConflict.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[parameterMissing].addFile(QString::fromUtf8(":/images/parameterMissing.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[parameterModified].addFile(QString::fromUtf8(":/images/parameterModified.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[parameterObsolete].addFile(QString::fromUtf8(":/images/parameterObsolete.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[playerKill].addFile(QString::fromUtf8(":/images/playerKill.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[playerPause].addFile(QString::fromUtf8(":/images/playerPause.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[playerStart].addFile(QString::fromUtf8(":/images/playerStart.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[playerStop].addFile(QString::fromUtf8(":/images/playerStop.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[preferences].addFile(QString::fromUtf8(":/images/preferences.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[reactionModifier].addFile(QString::fromUtf8(":/images/reactionModifier.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[reactionProduct].addFile(QString::fromUtf8(":/images/reactionProduct.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[reactionSubstrate].addFile(QString::fromUtf8(":/images/reactionSubstrate.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[renderMarkup].addFile(QString::fromUtf8(":/images/renderMarkup.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[renderMathML].addFile(QString::fromUtf8(":/images/renderMathML.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[separator].addFile(QString::fromUtf8(":/images/separator.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[slider].addFile(QString::fromUtf8(":/images/slider.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[sToIs].addFile(QString::fromUtf8(":/images/sToIs.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[table].addFile(QString::fromUtf8(":/images/table.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[tool].addFile(QString::fromUtf8(":/images/tool.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[unlocked].addFile(QString::fromUtf8(":/images/unlocked.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[zoomOut].addFile(QString::fromUtf8(":/images/zoomOut.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[play].addFile(QString::fromUtf8(":/images/media-playback-start.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[pause].addFile(QString::fromUtf8(":/images/media-playback-pause.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[stop].addFile(QString::fromUtf8(":/images/media-playback-stop.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[backward].addFile(QString::fromUtf8(":/images/media-seek-backward.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[forward].addFile(QString::fromUtf8(":/images/media-seek-forward.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[skipBackward].addFile(QString::fromUtf8(":/images/media-skip-backward.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[skipForward].addFile(QString::fromUtf8(":/images/media-skip-forward.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[roll].addFile(QString::fromUtf8(":/images/roll.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[viewmagMinus].addFile(QString::fromUtf8(":/images/viewmagMinus.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[viewmagPlus].addFile(QString::fromUtf8(":/images/viewmagPlus.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[viewmag1].addFile(QString::fromUtf8(":/images/viewmag1.png"), QSize(), QIcon::Normal, QIcon::On);
   Icons[viewmagfit].addFile(QString::fromUtf8(":/images/viewmagfit.png"), QSize(), QIcon::Normal, QIcon::On);
   needInit = false;
 }
Member Data Documentation
QVector< QIcon > CQIconResource::Icons static private
Definition at line 81 of file CQIconResource.h.
Referenced by icon(), and init().
bool CQIconResource::needInit static private
Definition at line 82 of file CQIconResource.h.
Referenced by init().
The documentation for this class was generated from the following files:
CQIconResource.h
CQIconResource.cpp