COPASI API: CCopasiSelectionDialog Class Reference
CCopasiSelectionDialog Class Reference
#include <CCopasiSelectionDialog.h>
Public Member Functions
CCopasiSelectionDialog (QWidget *parent=0, const char *name=0, bool modal=false)
void enableExpertMode (bool enable)
void setModel (const CModel *model, const CQSimpleSelectionTree::ObjectClasses &classes)
void setOutputVector (std::vector< const CCopasiObject * > *outputVector)
void setSingleSelection (bool singleSelectionMode)
~CCopasiSelectionDialog ()
Static Public Member Functions
static std::vector< const
CCopasiObject * > chooseCellMatrix (const CArrayAnnotation *pArrayAnnotation, bool single, bool value, std::string caption="")
static const CCopasiObject * getObjectSingle (QWidget *pParent, const CQSimpleSelectionTree::ObjectClasses &classes, const CCopasiObject *pCurrentObject=NULL)
static std::vector< const
CCopasiObject * > getObjectVector (QWidget *pParent, const CQSimpleSelectionTree::ObjectClasses &classes, const std::vector< const CCopasiObject * > *pCurrentSelection=NULL)
Protected Slots
void cancelButton_clicked ()
void modeButton_toggled (bool checked)
void okButton_clicked ()
Protected Attributes
bool mExpertMode
bool mExpertModeEnabled
QHBoxLayout * mpButtonBox
QVBoxLayout * mpMainLayout
QWidget * mpMainWidget
QCheckBox * mpModeCheckBox
std::vector< const
CCopasiObject * > * mpOutputVector
CCopasiSelectionWidget * mpSelectionWidget
std::vector< const
CCopasiObject * > * mpTmpVector
Detailed Description
Definition at line 33 of file CCopasiSelectionDialog.h.
Constructor & Destructor Documentation
CCopasiSelectionDialog::CCopasiSelectionDialog (QWidget * parent = 0, const char * name = 0, bool modal = false)
Definition at line 38 of file CCopasiSelectionDialog.cpp.
References cancelButton_clicked(), modeButton_toggled(), mpButtonBox, mpMainLayout, mpMainWidget, mpModeCheckBox, mpSelectionWidget, okButton_clicked(), and CCopasiSelectionWidget::setOutputVector().
Referenced by getObjectSingle(), and getObjectVector().
                                                                                                :
   QDialog(parent),
   mpModeCheckBox(NULL),
   mpButtonBox(NULL),
   mpMainWidget(NULL),
   mpMainLayout(NULL),
   mpTmpVector(new std::vector< const CCopasiObject * >()),
   mpOutputVector(NULL),
   mExpertMode(false),
   mExpertModeEnabled(true)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   setAttribute(Qt::WA_DeleteOnClose);
   mpMainLayout = new QVBoxLayout(this);
   mpSelectionWidget = new CCopasiSelectionWidget(this);
   mpMainLayout->addWidget(mpSelectionWidget);
   mpButtonBox = new QHBoxLayout();
   mpMainLayout->addLayout(mpButtonBox);
   QDialogButtonBox *box = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, Qt::Horizontal,  this);
   mpButtonBox->addWidget(box);
   mpModeCheckBox = new QCheckBox("expert mode", this);
   mpModeCheckBox->setObjectName("expertMode");
   mpModeCheckBox->setChecked(false);
   mpButtonBox->addWidget(mpModeCheckBox);
   // this->mpButtonBox->addSpacing(20);
   // this->mpButtonBox->addStretch();
   connect(box, SIGNAL(accepted()), this, SLOT(okButton_clicked()));
   connect(box, SIGNAL(rejected()), this, SLOT(cancelButton_clicked()));
   connect(this->mpModeCheckBox, SIGNAL(toggled(bool)), this, SLOT(modeButton_toggled(bool)));
   this->mpSelectionWidget->setOutputVector(NULL);
   this->setTabOrder(this->mpModeCheckBox, this->mpMainWidget);
 }
CCopasiSelectionDialog::~CCopasiSelectionDialog ()
Definition at line 80 of file CCopasiSelectionDialog.cpp.
References mpTmpVector.
 {
   delete mpTmpVector;
 }
Member Function Documentation
void CCopasiSelectionDialog::cancelButton_clicked () protected slot
Definition at line 103 of file CCopasiSelectionDialog.cpp.
Referenced by CCopasiSelectionDialog().
 {
   done(QDialog::Rejected);
 }
std::vector< const CCopasiObject * > CCopasiSelectionDialog::chooseCellMatrix (const CArrayAnnotation * pArrayAnnotation, bool single, bool value, std::string caption = "") static
single=true means only one object can be returned (in the first element of the return vector) when single=true and the dialog is canceled the return vector will have size=1 and contain the NULL pointer. when single=false and the dialog is canceled the return vector will be empty. value=true means only objects that have a value (i.e. arrayElementReferences) are allowed. otherwise also the whole array annotation may be returned.
Definition at line 230 of file CCopasiSelectionDialog.cpp.
References CArrayAnnotation::addElementReference(), CArrayAnnotation::dimensionality(), FROM_UTF8, CCopasiObject::getObjectName(), CQMatrixDialog::setArray(), CArrayAnnotation::size(), TO_UTF8, and CQMessageBox::warning().
Referenced by CQPlotSubwidget::addCurve2D(), getObjectSingle(), and getObjectVector().
 {
   std::vector< const CCopasiObject* > returnVector;
   if (single)
     {returnVector.resize(1); returnVector[0] = NULL;}
   else
     returnVector.resize(0);
   if (!pArrayAnnotation) return returnVector;
   //handle zero-dimensional array
   if (pArrayAnnotation->size().size() == 0)
     {
       CCopasiAbstractArray::index_type index;
       index.resize(0);
       returnVector.resize(1);
       returnVector[0] = static_cast< const CCopasiObject * >(pArrayAnnotation->addElementReference(index));
       return returnVector;
     }
   CQMatrixDialog * pDialog = new CQMatrixDialog();
   pDialog->setWindowTitle(tr(TO_UTF8(FROM_UTF8(caption) + "Cell Selection of " + FROM_UTF8(pArrayAnnotation->getObjectName()))));
   pDialog->setArray(pArrayAnnotation, single);
   int Result = pDialog->exec();
   if (Result == QDialog::Accepted)
     {
       CCopasiAbstractArray::index_type index;
       index.resize(pArrayAnnotation->dimensionality());
       if (index.size() > 2)
         CQMessageBox::warning(0, "Dimensionality Problem", "Need more handle for high dimension of array",
                               QMessageBox::Ok | QMessageBox::Default, QMessageBox::NoButton);
       if (single)
         {
           // single cell selection
           if (value)
             {
               index[0] = pDialog->mpCBRow->currentIndex();
               if (index.size() > 1)
                 index[1] = pDialog->mpCBColumn->currentIndex();
               returnVector[0] = static_cast< const CCopasiObject * >(pArrayAnnotation->addElementReference(index));
             }
           return returnVector;
         }
       // multi cell selection
       //if "All" is selected for both rows and columns, and an object with numerical value
       //is not requested, return the array annotation as such
       if (pDialog->mpCBRow->currentIndex() == 0 && pDialog->mpCBColumn->currentIndex() == 0
           && !value)
         {
           // whole matrix should be chosen -> the object itself will be returned
           returnVector.resize(1);
           returnVector[0] = (CCopasiObject *) pArrayAnnotation;
           return returnVector;
         }
       size_t minRows, maxRows, minCols, maxCols;
       size_t i, j;
       if (pDialog->mpCBRow->currentIndex())
         {
           // not ALL option
           minRows = pDialog->mpCBRow->currentIndex() - 1;
           maxRows = minRows + 1;
         }
       else
         {
           // ALL option
           minRows = 0;
           maxRows = pArrayAnnotation->size()[0];
         }
       if (index.size() == 2)
         {
           if (pDialog->mpCBColumn->currentIndex())
             {
               // not ALL option
               minCols = pDialog->mpCBColumn->currentIndex() - 1;
               maxCols = minCols + 1;
             }
           else
             {
               // ALL option
               minCols = 0;
               maxCols = pArrayAnnotation->size()[1];
             }
           for (i = minRows; i < maxRows; ++i)
             {
               for (j = minCols; j < maxCols; ++j)
                 {
                   returnVector.push_back(static_cast< const CCopasiObject * >(pArrayAnnotation->addElementReference((int) i, (int) j)));
                 }
             }
         }
       if (index.size() == 1)
         {
           for (i = minRows; i < maxRows; ++i)
             {
               returnVector.push_back(static_cast< const CCopasiObject * >(pArrayAnnotation->addElementReference((int) i)));
             }
         }
       return returnVector;
     }
   else
     {
       // Rejected case
       if (single)
         returnVector[0] = NULL;
       return returnVector;
     }
 }
void CCopasiSelectionDialog::enableExpertMode (bool enable)
Definition at line 118 of file CCopasiSelectionDialog.cpp.
References mExpertModeEnabled, and mpModeCheckBox.
 {
   if (enable == this->mExpertModeEnabled) return;
   this->mExpertModeEnabled = enable;
   if (!this->mExpertModeEnabled)
     {
       this->mpModeCheckBox->setChecked(false);
       this->mpModeCheckBox->hide();
     }
   else
     {
       this->mpModeCheckBox->show();
     }
 }
const CCopasiObject * CCopasiSelectionDialog::getObjectSingle (QWidget * pParent, const CQSimpleSelectionTree::ObjectClasses & classes, const CCopasiObject * pCurrentObject = NULL) static
Definition at line 136 of file CCopasiSelectionDialog.cpp.
References CCopasiSelectionDialog(), chooseCellMatrix(), CCopasiRootContainer::getDatamodelList(), setModel(), setOutputVector(), and setSingleSelection().
Referenced by SliderSettingsDialog::browseButtonPressed(), Curve2DWidget::buttonPressedX(), BandedGraphWidget::buttonPressedX(), Curve2DWidget::buttonPressedY(), BandedGraphWidget::buttonPressedYone(), BandedGraphWidget::buttonPressedYtwo(), CQExperimentData::selectModelObject(), CQEventWidget1::slotAddTarget(), CScanWidgetRandom::slotChooseObject(), CScanWidgetScan::slotChooseObject(), SensitivitiesWidget::slotChooseSingleFunction(), SensitivitiesWidget::slotChooseSingleVariable(), SensitivitiesWidget::slotChooseSingleVariable2(), CQCrossSectionTaskWidget::slotChooseVariable(), CQFittingItemWidget::slotLowerEdit(), CQFittingItemWidget::slotParamEdit(), CQEventWidget1::slotSelectObject(), CQExpressionWidget::slotSelectObject(), and CQFittingItemWidget::slotUpperEdit().
 {
   std::vector< const CCopasiObject * > Selection;
   if (pCurrentObject != NULL)
     Selection.push_back(pCurrentObject);
   CCopasiSelectionDialog * pDialog = new CCopasiSelectionDialog(parent);
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pDialog->setWindowTitle("Select Item");
   pDialog->setModel((*CCopasiRootContainer::getDatamodelList())[0]->getModel(), classes);
   pDialog->setSingleSelection(true);
   pDialog->setOutputVector(&Selection);
   int Result = pDialog->exec();
   if (Result == QDialog::Accepted && Selection.size() != 0)
     {
       const CCopasiObject *pObject = Selection[0];
       const CArrayAnnotation * pArray;
       // if the selected object is an array then select firstly one cell of it
       if ((pArray = dynamic_cast< const CArrayAnnotation * >(pObject)))
         {
           pObject = chooseCellMatrix(pArray, true, true)[0];
           if (!pObject) return NULL;
         }
       return pObject;
     }
   if (Result == QDialog::Rejected && pCurrentObject != NULL)
     return pCurrentObject;
   return NULL;
 }
std::vector< const CCopasiObject * > CCopasiSelectionDialog::getObjectVector (QWidget * pParent, const CQSimpleSelectionTree::ObjectClasses & classes, const std::vector< const CCopasiObject * > * pCurrentSelection = NULL) static
Definition at line 176 of file CCopasiSelectionDialog.cpp.
References CCopasiSelectionDialog(), chooseCellMatrix(), CCopasiRootContainer::getDatamodelList(), setModel(), setOutputVector(), and setSingleSelection().
Referenced by CQReportDefinition::btnItemClicked(), HistoWidget::buttonPressedX(), SliderDialog::createNewSlider(), ScanWidget::slotAddItem(), and CQFittingItemWidget::slotParamEdit().
 {
   std::vector< const CCopasiObject * > Selection;
   if (pCurrentSelection)
     Selection = *pCurrentSelection;
   CCopasiSelectionDialog * pDialog = new CCopasiSelectionDialog(parent);
   pDialog->setWindowTitle("Select Items");
   pDialog->setToolTip("Select multiple items by holding down the Ctrl or Shift (or equivalent) key.");
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pDialog->setModel((*CCopasiRootContainer::getDatamodelList())[0]->getModel(), classes);
   pDialog->setSingleSelection(false);
   pDialog->setOutputVector(&Selection);
   if (pDialog->exec() == QDialog::Rejected && pCurrentSelection)
     return *pCurrentSelection;
   else
     //    return Selection;
     {
       std::vector<const CCopasiObject *> newSelection;
       std::vector< const CCopasiObject * >::iterator itSelection = Selection.begin();
       for (; itSelection != Selection.end(); ++itSelection)
         {
           // if the current object is an array then select firstly one cell of it
           const CArrayAnnotation * pArray;
           if ((pArray = dynamic_cast< const CArrayAnnotation * >(*itSelection)))
             {
               // second parameter is false in order 'ALL' options on the matrix dialog to appear
               std::vector<const CCopasiObject *> tmp = chooseCellMatrix(pArray, false, true); //TODO value flag
               std::vector<const CCopasiObject *>::const_iterator tmpit, tmpitEnd = tmp.end();
               for (tmpit = tmp.begin(); tmpit != tmpitEnd; ++tmpit)
                 newSelection.push_back(*tmpit);
             }
           // otherwise, just put it into newSelection
           else
             {
               newSelection.push_back(*itSelection);
             }
         }
       return newSelection;
     }
   //  return Selection;
 }
void CCopasiSelectionDialog::modeButton_toggled (bool checked) protected slot
Definition at line 108 of file CCopasiSelectionDialog.cpp.
References mpSelectionWidget, and CCopasiSelectionWidget::setExpertMode().
Referenced by CCopasiSelectionDialog().
 {
   this->mpSelectionWidget->setExpertMode(checked);
 }
void CCopasiSelectionDialog::okButton_clicked () protected slot
Definition at line 96 of file CCopasiSelectionDialog.cpp.
References CCopasiSelectionWidget::commit(), and mpSelectionWidget.
Referenced by CCopasiSelectionDialog().
 {
   // fill outputVector
   this->mpSelectionWidget->commit();
   done(QDialog::Accepted);
 }
void CCopasiSelectionDialog::setModel (const CModel * model, const CQSimpleSelectionTree::ObjectClasses & classes)
Definition at line 85 of file CCopasiSelectionDialog.cpp.
References mpSelectionWidget, and CCopasiSelectionWidget::populateTree().
Referenced by getObjectSingle(), and getObjectVector().
 {
   this->mpSelectionWidget->populateTree(pModel, classes);
 }
void CCopasiSelectionDialog::setOutputVector (std::vector< const CCopasiObject * > * outputVector)
Definition at line 91 of file CCopasiSelectionDialog.cpp.
References mpSelectionWidget, and CCopasiSelectionWidget::setOutputVector().
Referenced by getObjectSingle(), and getObjectVector().
 {
   this->mpSelectionWidget->setOutputVector(outputVector);
 }
void CCopasiSelectionDialog::setSingleSelection (bool singleSelectionMode)
Definition at line 113 of file CCopasiSelectionDialog.cpp.
References mpSelectionWidget, and CCopasiSelectionWidget::setSingleSelection().
Referenced by getObjectSingle(), and getObjectVector().
 {
   this->mpSelectionWidget->setSingleSelection(singleSelectionMode);
 }
Member Data Documentation
bool CCopasiSelectionDialog::mExpertMode protected
Definition at line 45 of file CCopasiSelectionDialog.h.
bool CCopasiSelectionDialog::mExpertModeEnabled protected
Definition at line 46 of file CCopasiSelectionDialog.h.
Referenced by enableExpertMode().
QHBoxLayout* CCopasiSelectionDialog::mpButtonBox protected
Definition at line 39 of file CCopasiSelectionDialog.h.
Referenced by CCopasiSelectionDialog().
QVBoxLayout* CCopasiSelectionDialog::mpMainLayout protected
Definition at line 42 of file CCopasiSelectionDialog.h.
Referenced by CCopasiSelectionDialog().
QWidget* CCopasiSelectionDialog::mpMainWidget protected
Definition at line 40 of file CCopasiSelectionDialog.h.
Referenced by CCopasiSelectionDialog().
QCheckBox* CCopasiSelectionDialog::mpModeCheckBox protected
Definition at line 38 of file CCopasiSelectionDialog.h.
Referenced by CCopasiSelectionDialog(), and enableExpertMode().
std::vector<const CCopasiObject * >* CCopasiSelectionDialog::mpOutputVector protected
Definition at line 44 of file CCopasiSelectionDialog.h.
CCopasiSelectionWidget* CCopasiSelectionDialog::mpSelectionWidget protected
Definition at line 41 of file CCopasiSelectionDialog.h.
Referenced by CCopasiSelectionDialog(), modeButton_toggled(), okButton_clicked(), setModel(), setOutputVector(), and setSingleSelection().
std::vector<const CCopasiObject * >* CCopasiSelectionDialog::mpTmpVector protected
Definition at line 43 of file CCopasiSelectionDialog.h.
Referenced by ~CCopasiSelectionDialog().
The documentation for this class was generated from the following files:
CCopasiSelectionDialog.h
CCopasiSelectionDialog.cpp