COPASI API: QConservedSpeciesAnimation Class Reference
QConservedSpeciesAnimation Class Reference
Private Member Functions
virtual void getScales (std::vector< qreal > &scales, int step)
virtual void initialize (const CCopasiDataModel &dataModel)
Additional Inherited Members
Public Types inherited from CQCopasiAnimation
enum ScaleMode { Global, Individual }
Public Member Functions inherited from CQCopasiAnimation
virtual void applyToScene (CQLayoutScene &scene, int step)
CQCopasiAnimation ()
std::vector
< CQEffectDescription * > & getEntries ()
virtual int getNumSteps ()
ScaleMode getScaleMode () const
virtual void removeFromScene (CQLayoutScene &scene)
void setScaleMode (ScaleMode mode)
virtual ~CQCopasiAnimation ()
Protected Attributes inherited from CQCopasiAnimation
std::vector
< CQEffectDescription * > mEntries
ScaleMode mMode
int mNumSteps
const CCopasiDataModel * mpDataModel
Detailed Description
Definition at line 35 of file CQAnimationWindow.cpp.
Member Function Documentation
virtual void QConservedSpeciesAnimation::getScales (std::vector< qreal > & scales, int step) inline private virtual
Reimplemented from CQCopasiAnimation.
Definition at line 55 of file CQAnimationWindow.cpp.
References CMoiety::getEquation(), CCopasiDataModel::getModel(), CModel::getMoieties(), CQCopasiAnimation::mEntries, CQCopasiAnimation::mNumSteps, CQCopasiAnimation::mpDataModel, and CCopasiVector< T >::size().
   {
     if (mpDataModel == NULL) return;
     const CModel& model = *mpDataModel->getModel();
     const CCopasiVector< CMoiety > & moieties = model.getMoieties();
     mNumSteps = moieties.size();
     if (moieties.size() <= (size_t)step) return;
     const CMoiety* moiety = moieties[step];
     const std::vector<std::pair< C_FLOAT64, CMetab * > > &eqn = moiety->getEquation();
     std::map<std::string, double> cnValueMap;
     std::vector<std::pair< C_FLOAT64, CMetab * > >::const_iterator it = eqn.begin();
     while (it != eqn.end())
       {
         cnValueMap[(*it).second->getCN()] = (*it).first;
         ++it;
       }
     for (size_t i = 0; i < mEntries.size(); ++i)
       scales.push_back(cnValueMap[mEntries[i]->getCN()]);
   }
virtual void QConservedSpeciesAnimation::initialize (const CCopasiDataModel & dataModel) inline private virtual
Implements CQCopasiAnimation.
Definition at line 37 of file CQAnimationWindow.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CModel::getMoieties(), CQCopasiAnimation::mEntries, CQCopasiAnimation::mNumSteps, CQCopasiAnimation::mpDataModel, and CCopasiVector< T >::size().
   {
     mpDataModel = &dataModel;
     const CModel& model = *dataModel.getModel();
     const CCopasiVector< CMetab > & metabs = model.getMetabolites();
     CCopasiVector< CMetab >::const_iterator it = metabs.begin();
     while (it != metabs.end())
       {
         mEntries.push_back(new CQEffectDescription((*it)->getCN()));
         ++it;
       }
     // initialize number of steps
     const CCopasiVector< CMoiety > & moieties = model.getMoieties();
     mNumSteps = moieties.size();
   }
The documentation for this class was generated from the following file:
CQAnimationWindow.cpp