COPASI API: COptMethodNelderMead Class Reference
COptMethodNelderMead Class Reference
#include <COptMethodNelderMead.h>
Public Member Functions
COptMethodNelderMead (const COptMethodNelderMead &src, const CCopasiContainer *pParent=NULL)
virtual bool optimise ()
virtual ~COptMethodNelderMead ()
Public Member Functions inherited from COptMethod
COptMethod (const COptMethod &src, const CCopasiContainer *pParent=NULL)
bool isBounded (void)
virtual bool isValidProblem (const CCopasiProblem *pProblem)
void setProblem (COptProblem *problem)
virtual ~COptMethod ()
Public Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiMethod &src, const CCopasiContainer *pParent=NULL)
const CCopasiMethod::SubType & getSubType () const
const CCopasiTask::Type & getType () const
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CCopasiMethod ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
virtual bool elevateChildren ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
virtual bool cleanup ()
COptMethodNelderMead (const CCopasiContainer *pParent=NULL)
const C_FLOAT64 & evaluate ()
virtual bool initialize ()
void initObjects ()
Private Attributes
C_FLOAT64 mBestValue
CVector< C_FLOAT64 > mCentroid
bool mContinue
CVector< C_FLOAT64 > mCurrent
C_FLOAT64 mEvaluationValue
size_t mhIteration
unsigned C_INT32 mIteration
unsigned C_INT32 mIterationLimit
C_FLOAT64 mScale
CMatrix< C_FLOAT64 > mSimplex
CVector< C_FLOAT64 > mStep
C_FLOAT64 mTolerance
CVector< C_FLOAT64 > mValue
size_t mVariableSize
Friends
COptMethod * COptMethod::createMethod (CCopasiMethod::SubType subType)
Additional Inherited Members
Public Types inherited from CCopasiMethod
enum SubType {
unset = 0, RandomSearch, RandomSearchMaster, SimulatedAnnealing,
CoranaWalk, DifferentialEvolution, ScatterSearch, GeneticAlgorithm,
EvolutionaryProgram, SteepestDescent, HybridGASA, GeneticAlgorithmSR,
HookeJeeves, LevenbergMarquardt, NelderMead, SRES,
Statistics, ParticleSwarm, Praxis, TruncatedNewton,
Newton, deterministic, LSODAR, directMethod,
stochastic, tauLeap, adaptiveSA, hybrid,
hybridLSODA, hybridODE45, DsaLsodar, tssILDM,
tssILDMModified, tssCSP, mcaMethodReder, scanMethod,
lyapWolf, sensMethod, EFMAlgorithm, EFMBitPatternTreeAlgorithm,
EFMBitPatternAlgorithm, Householder, crossSectionMethod, linearNoiseApproximation
}
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from COptMethod
static COptMethod * createMethod (CCopasiMethod::SubType subType=CCopasiMethod::RandomSearch)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiMethod
static const std::string SubTypeName []
static const char * XMLSubType []
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from COptMethod
COptMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiMethod
CCopasiMethod (const CCopasiTask::Type &taskType, const SubType &subType, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from COptMethod
const bool mBounds
const std::vector< COptItem * > * mpOptContraints
const std::vector< COptItem * > * mpOptItem
COptProblem * mpOptProblem
COptTask * mpParentTask
const std::vector
< UpdateMethod * > * mpSetCalculateVariable
Protected Attributes inherited from CCopasiMethod
CProcessReport * mpCallBack
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 31 of file COptMethodNelderMead.h.
Constructor & Destructor Documentation
COptMethodNelderMead::COptMethodNelderMead (const COptMethodNelderMead & src, const CCopasiContainer * pParent = NULL)
Copy Constructor
Parameters
const COptMethodNelderMead & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 40 of file COptMethodNelderMead.cpp.
References initObjects().
                                      :
   COptMethod(src, pParent)
 {initObjects();}
COptMethodNelderMead::~COptMethodNelderMead () virtual
Destructor
Definition at line 45 of file COptMethodNelderMead.cpp.
References cleanup().
 {cleanup();}
COptMethodNelderMead::COptMethodNelderMead (const CCopasiContainer * pParent = NULL) private
Default Constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 30 of file COptMethodNelderMead.cpp.
References CCopasiParameterGroup::addParameter(), C_FLOAT64, C_INT32, initObjects(), CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
                                                                           :
   COptMethod(CCopasiTask::optimization, CCopasiMethod::NelderMead, pParent)
 {
   addParameter("Iteration Limit", CCopasiParameter::UINT, (unsigned C_INT32) 200);
   addParameter("Tolerance", CCopasiParameter::UDOUBLE, (C_FLOAT64) 1.e-005);
   addParameter("Scale", CCopasiParameter::UDOUBLE, (C_FLOAT64) 10.0);
   initObjects();
 }
Member Function Documentation
bool COptMethodNelderMead::cleanup () private virtual
Cleanup arrays and pointers.
Returns
bool success
Reimplemented from COptMethod.
Definition at line 607 of file COptMethodNelderMead.cpp.
Referenced by initialize(), and ~COptMethodNelderMead().
 {
   return true;
 }
const C_FLOAT64 & COptMethodNelderMead::evaluate () private
Evaluate the objective function
Returns
bool continue
Definition at line 612 of file COptMethodNelderMead.cpp.
References COptProblem::calculate(), COptProblem::checkFunctionalConstraints(), COptProblem::checkParametricConstraints(), COptProblem::getCalculateValue(), mBestValue, mContinue, mEvaluationValue, and COptMethod::mpOptProblem.
Referenced by optimise().
 {
   // We do not need to check whether the parametric constraints are fulfilled
   // since the parameters are created within the bounds.
   mContinue &= mpOptProblem->calculate();
   mEvaluationValue = mpOptProblem->getCalculateValue();
   // when we leave the either the parameter or functional domain
   // we penalize the objective value by forcing it to be larger
   // than the best value recorded so far.
   if (mEvaluationValue < mBestValue &&
       (!mpOptProblem->checkParametricConstraints() ||
        !mpOptProblem->checkFunctionalConstraints()))
     mEvaluationValue = mBestValue + mBestValue - mEvaluationValue;
   return mEvaluationValue;
 }
bool COptMethodNelderMead::initialize () private virtual
Initialize arrays and pointer.
Returns
bool success
Reimplemented from COptMethod.
Definition at line 631 of file COptMethodNelderMead.cpp.
References CProcessReport::addItem(), cleanup(), CCopasiParameter::getValue(), COptMethod::initialize(), mBestValue, mCentroid, mContinue, mCurrent, mhIteration, mIteration, mIterationLimit, CCopasiMethod::mpCallBack, COptMethod::mpOptItem, mScale, mSimplex, mStep, mTolerance, mValue, mVariableSize, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CMatrix< CType >::resize(), and CVector< CType >::resize().
Referenced by optimise().
 {
   cleanup();
   if (!COptMethod::initialize()) return false;
   mIterationLimit = * getValue("Iteration Limit").pUINT;
   mTolerance = * getValue("Tolerance").pUDOUBLE;
   mScale = * getValue("Scale").pUDOUBLE;
   mIteration = 0;
   if (mpCallBack)
     mhIteration =
       mpCallBack->addItem("Current Iteration",
                           mIteration,
                           & mIterationLimit);
   mVariableSize = mpOptItem->size();
   mSimplex.resize(mVariableSize, mVariableSize + 1);
   mValue.resize(mVariableSize + 1);
   mCentroid.resize(mVariableSize);
   mCurrent.resize(mVariableSize);
   mStep.resize(mVariableSize);
   mBestValue = std::numeric_limits<C_FLOAT64>::infinity();
   mContinue = true;
   return true;
 }
void COptMethodNelderMead::initObjects () private
Initialize contained objects.
Definition at line 48 of file COptMethodNelderMead.cpp.
References CCopasiContainer::addObjectReference(), mIteration, and CCopasiObject::ValueInt.
Referenced by COptMethodNelderMead().
 {
   addObjectReference("Current Iteration", mIteration, CCopasiObject::ValueInt);
 }
bool COptMethodNelderMead::optimise (void) virtual
Execute the optimization algorithm calling simulation routine when needed. It is noted that this procedure can give feedback of its progress by the callback function set with SetCallback. @ return success;
Reimplemented from COptMethod.
Definition at line 171 of file COptMethodNelderMead.cpp.
References C_FLOAT64, COptItem::checkConstraint(), COutputInterface::DURING, evaluate(), CProcessReport::finishItem(), COptItem::getLowerBoundValue(), COptProblem::getSolutionVariables(), COptItem::getStartValue(), COptItem::getUpperBoundValue(), initialize(), max, mBestValue, mCentroid, mContinue, mCurrent, mEvaluationValue, mhIteration, mIteration, mIterationLimit, CCopasiMethod::mpCallBack, COptMethod::mpOptProblem, COptMethod::mpParentTask, COptMethod::mpSetCalculateVariable, mScale, mSimplex, mStep, mTolerance, mValue, mVariableSize, CCopasiTask::output(), CProcessReport::progressItem(), and COptProblem::setSolution().
 {
   if (!initialize())
     {
       if (mpCallBack)
         mpCallBack->finishItem(mhIteration);
       return false;
     }
   // set tolerances for local minima test to zero
   C_FLOAT64 abstol, reltol;
   abstol = reltol = 0.0;
   // test convergence every iteration
   size_t konvge;
   konvge = 1;
   size_t iBest, iWorst;
   // double zero, half, one, delta;
   C_FLOAT64 ccoeff, rcoeff, ecoeff;
   /* ---- reflection, extension and contraction coefficients. ---- */
   /* parameters from Nelder and Mead */
   //rcoeff = 1.0;
   //ccoeff = 0.5;
   //ecoeff = 2.0;
   /* Parameters from Parkinson and Hutchinson */
   rcoeff = 2.0;
   ccoeff = 0.25;
   ecoeff = 2.5;
   C_FLOAT64 z, sum, ylo;
   C_FLOAT64 curmin, del, x, yhi;
   C_FLOAT64 small;
   C_FLOAT64 factor = 0.8;
   size_t jcount, np1, i, j;
   bool ok, reflok, extnok, contok, quit, found;  /* boolean variables */
   // initial point is first guess but we have to make sure that we
   // are within the parameter domain
   for (i = 0; i < mVariableSize; i++)
     {
       const COptItem & OptItem = *(*mpOptItem)[i];
       switch (OptItem.checkConstraint(OptItem.getStartValue()))
         {
           case - 1:
             mCurrent[i] = *OptItem.getLowerBoundValue();
             break;
           case 1:
             mCurrent[i] = *OptItem.getUpperBoundValue();
             break;
           case 0:
             mCurrent[i] = OptItem.getStartValue();
             break;
         }
       (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
       // set the magnitude of each parameter
       mStep[i] = (*OptItem.getUpperBoundValue() - *OptItem.getLowerBoundValue()) / mScale;
     }
   evaluate();
   if (!isnan(mEvaluationValue))
     {
       // and store that value
       mBestValue = mEvaluationValue;
       mContinue &= mpOptProblem->setSolution(mBestValue, mCurrent);
       // We found a new best value lets report it.
       mpParentTask->output(COutputInterface::DURING);
     }
   quit = false;
   found = false;
   np1 = mVariableSize + 1;
   del = 1.0;
 First:
   /* ---- Construct the initial simplex. ---- */
   for (i = 0; i < mVariableSize; ++i)
     mSimplex[i][mVariableSize] = mCurrent[i];
   mValue[mVariableSize] = mEvaluationValue;
   for (j = 0; j < mVariableSize && mContinue; ++j)
     {
       x = mCurrent[j];
       // -- move a little in one dimension only --
       mCurrent[j] += (mStep[j] * del);
       // Check constraint
       const COptItem & OptItem = *(*mpOptItem)[j];
       if (mCurrent[j] > *OptItem.getUpperBoundValue())
         mCurrent[j] = x - (mStep[j] * del);
       // Store the simplex corner
       for (i = 0; i < mVariableSize; ++i)
         mSimplex[i][j] = mCurrent[i];
       // Calculate the value for the corner
       (*(*mpSetCalculateVariable)[j])(mCurrent[j]);
       mValue[j] = evaluate();
       if (mEvaluationValue < mBestValue)
         {
           // and store that value
           mBestValue = mEvaluationValue;
           mContinue &= mpOptProblem->setSolution(mBestValue, mCurrent);
           // We found a new best value lets report it.
           mpParentTask->output(COutputInterface::DURING);
         }
       // Reset
       mCurrent[j] = x;
       (*(*mpSetCalculateVariable)[j])(mCurrent[j]);
     }
   /* ---- Simplex construction complete; now do some work. ---- */
   while (!found && !quit && mContinue)
     {
       /* ---- take some steps ---- */
       for (jcount = 1; jcount <= konvge; ++jcount)
         {
           /* ---- take a single step ---- */
           /* ---- find highest and lowest y values.  yhi (=y[iWorst]) indicates
              the vertex of the simplex to be replaced.   */
           ylo = mValue[0];
           yhi = ylo;
           iBest = 0;
           iWorst = 0;
           for (i = 1; i < np1; ++i)
             {
               if (mValue[i] < ylo)     /* -- find the lowest value of the objective  */
                 {
                   ylo = mValue[i];
                   iBest = i;
                 }
               if (mValue[i] > yhi)    /* -- find the highest value of the objective -- */
                 {
                   yhi = mValue[i];
                   iWorst = i;
                 }
             }
           /* ---- Calculate mCentroid, the centroid of the simplex vertices
              excepting that with the y value yhi. (largest objective value)  */
           for (i = 0; i < mVariableSize; ++i)
             {
               /* -- calculate the average in each dimension -- */
               z = 0.0;
               for (j = 0; j < np1; ++j)
                 z += mSimplex[i][j];
               z -= mSimplex[i][iWorst];
               mCentroid[i] = z / mVariableSize;
             }
           /* ---- reflection through the centroid. ---- */
           for (i = 0; i < mVariableSize; ++i)
             {
               mCurrent[i] = (1.0 + rcoeff) * mCentroid[i] - rcoeff * mSimplex[i][iWorst];
               (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
               // enforce_bounds(&pstar[i], i);  /* make sure it is inside */
             }
           evaluate();
           reflok = (mEvaluationValue < ylo);    /* -- 1 if we have moved downhill -- */
           if (reflok) /* then */
             {
               ylo = mEvaluationValue;
               for (i = 0; i < mVariableSize; ++i)
                 mSimplex[i][iWorst] = mCurrent[i];
               mValue[iWorst] = ylo;
               // and store that value
               if (mEvaluationValue < mBestValue)
                 {
                   mBestValue = mEvaluationValue;
                   mContinue &= mpOptProblem->setSolution(mBestValue, mCurrent);
                   // We found a new best value lets report it.
                   mpParentTask->output(COutputInterface::DURING);
                 }
               /* ---- successful reflection, so be bold and try extension */
               for (i = 0; i < mVariableSize; ++i)
                 {
                   mCurrent[i] = ecoeff * mCurrent[i] + (1.0 - ecoeff) * mCentroid[i];
                   (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
                   // enforce_bounds(&p2star[i], i);  /* make sure it is inside */
                 }
               evaluate();
               extnok = (mEvaluationValue < ylo);    /* -- 1 if we continue moved downhill -- */
               if (extnok)
                 {
                   /* ---- retain extension ---- */
                   ylo = mEvaluationValue;
                   for (i = 0; i < mVariableSize; ++i)
                     mSimplex[i][iWorst] = mCurrent[i];
                   mValue[iWorst] = ylo;
                   // and store that value
                   if (mEvaluationValue < mBestValue)
                     {
                       mBestValue = mEvaluationValue;
                       mContinue &= mpOptProblem->setSolution(mBestValue, mCurrent);
                       // We found a new best value lets report it.
                       mpParentTask->output(COutputInterface::DURING);
                     }
                 }
             }   /* successful reflection */
           else    /* if reflok then else */
             {
               /* ---- reflection has not been successful.  ystar is the function
                  value at the extended point.  now look at the other points
                  of the simplex ...
                  if there are none > ystar then contract to a point within the simplex
                  if there is one   > ystar then reduce the size of the extension
                  if there are many > ystar then retain the reflection as is.  */
               size_t L = 0;
               for (i = 0; i < np1; ++i)
                 if (mValue[i] > mEvaluationValue)
                   L++;
               if (L == 1) /* then */
                 {
                   /* ---- reflection was not successful but we can try reducing the
                      extension by contracting on the reflection side of the centroid.
                      Record the reflection for the contraction below. */
                   for (i = 0; i < mVariableSize; ++i)
                     mSimplex[i][iWorst] = mCurrent[i];
                   mValue[iWorst] = mEvaluationValue;
                 }
               if (L == 0 || L == 1) /* then */
                 {
                   /* L == 0 : there are no other points with higher objectives so
                      try a contraction on the y(iWorst) side of the centroid.
                      i.e. within the simplex.
                      L == 1 : there is one other point with a higher objective so
                      try a contraction on the reflection side of the centroid.  */
                   for (i = 0; i < mVariableSize; ++i)
                     {
                       mCurrent[i] = ccoeff * mSimplex[i][iWorst] + (1.0 - ccoeff) * mCentroid[i];
                       (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
                       // may not need to check boundaries since it is contraction
                       // enforce_bounds(&p2star[i], i);  /* make sure it is inside */
                     }
                   evaluate();
                   contok = (mEvaluationValue <= mValue[iWorst]);  /* -- 1 if we have not gone uphill -- */
                   if (contok) /* then */
                     {
                       /* ---- retain contraction ---- */
                       for (i = 0; i < mVariableSize; ++i)
                         mSimplex[i][iWorst] = mCurrent[i];
                       mValue[iWorst] = mEvaluationValue;
                     }
                   else
                     {
                       /* ---- contract whole simplex about a point within itself
                          but close to the current minimum. ---- */
                       for (j = 0; j < np1; ++j)
{
                           for (i = 0; i < mVariableSize; ++i)
{
                               mSimplex[i][j] = (mSimplex[i][j] + mSimplex[i][iBest]) * 0.5;
                               mCurrent[i] = mSimplex[i][j];
                               (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
                               //enforce_bounds(&xmin[i], i);  /* make sure it is inside */
                             }
                           mValue[j] = evaluate();
                           if (mEvaluationValue < mBestValue)
{
                               /* ---- retain extension ---- */
                               // and store that value
                               mBestValue = mEvaluationValue;
                               mContinue &= mpOptProblem->setSolution(mBestValue, mCurrent);
                               // We found a new best value lets report it.
                               mpParentTask->output(COutputInterface::DURING);
                             }
                         }
                     }  /* if (contok) */
                 }  /* contraction */
               else   /* if (L == 0) or (L == 1) then else */
                 {
                   /* ---- Retain the first reflection as there are many points in
                      the simplex that have higher objective values than
                      this new point.  A change is better than nothing. ---- */
                   for (i = 0; i < mVariableSize; ++i)
                     mSimplex[i][iWorst] = mCurrent[i];
                   mValue[iWorst] = mEvaluationValue;
                 }
             }   /* if Reflok then else .. */
         }   /* ---- procedure TakeAStep ----*/
       /* are we over the limit for number of function evaluations ? */
       //  quit = (icount > kcount);
       // are we above the iteration limit?
       ++mIteration;
       // signal another iteration
       if (mpCallBack)
         mContinue &= mpCallBack->progressItem(mhIteration);
       quit = (mIteration >= mIterationLimit);
       if (!quit) /* then */
         {
           /* ---- check to see if minimum reached.
             calculation of the variance must be done in the highest
             precision available. ---- */
           /* mean */
           sum = 0.0;
           curmin = 0.0;
           for (i = 0; i < np1; ++i)
             {
               sum += mValue[i];
               curmin += mValue[i] * mValue[i];
             }
           sum /= np1;
           curmin /= np1;
           /* ---- curmin is the variance of the n+1 Fnelmin values at the
              vertices.  If we haven't reached the minimum to the
              required accuracy then take a few more steps.    */
           found = (sqrt(curmin - sum * sum) < mTolerance);
         }
     }   /* while not found and not quit ... */
   /* **** bail out if necessary **** */
   if (quit || !mContinue) goto Finish;
   /* ---- Check around the currently selected point to see if it is a local minimum.  */
   small = fabs(mBestValue) * reltol + abstol;
   mCurrent = mpOptProblem->getSolutionVariables();
   for (i = 0; i < mVariableSize; ++i)
     (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
   for (i = 0; i < mVariableSize; ++i)
     {
       /* ---- check along each dimension ---- */
       C_FLOAT64 delta = mStep[i] * 1.0e-03;
       /* -- check along one direction -- */
       (*(*mpSetCalculateVariable)[i])(mCurrent[i] + delta);
       evaluate();
       if ((mEvaluationValue - mBestValue) < -small)
         break;
       /* -- now check the other way -- */
       (*(*mpSetCalculateVariable)[i])(mCurrent[i] - delta);
       evaluate();
       if ((mEvaluationValue - mBestValue) < -small)
         break;
       /* -- back to start -- */
       (*(*mpSetCalculateVariable)[i])(mCurrent[i]);
     }
   ok = (i == mVariableSize);
   /* ---- return on finding a local minimum to the desired accuracy. ---- */
   if (ok) /* then */
     {
       goto Finish;
     }
   /* ---- Reduce the size of the simplex and restart the procedure. ---- */
   found = 0;   /* -- we did not find a 1 minimum -- */
   del = std::max(del * factor, 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon());
   goto First;
 Finish:  /* end of procedure */
   if (mpCallBack)
     mpCallBack->finishItem(mhIteration);
   return true;
 }
Friends And Related Function Documentation
COptMethod* COptMethod::createMethod (CCopasiMethod::SubType subType) friend
Member Data Documentation
C_FLOAT64 COptMethodNelderMead::mBestValue private
The best value found so far
Definition at line 149 of file COptMethodNelderMead.h.
Referenced by evaluate(), initialize(), and optimise().
CVector<C_FLOAT64 > COptMethodNelderMead::mCentroid private
The centroid of the simplex
Definition at line 134 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
bool COptMethodNelderMead::mContinue private
Flag indicating whether the computation shall continue
Definition at line 159 of file COptMethodNelderMead.h.
Referenced by evaluate(), initialize(), and optimise().
CVector< C_FLOAT64 > COptMethodNelderMead::mCurrent private
The current solution guess
Definition at line 139 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
C_FLOAT64 COptMethodNelderMead::mEvaluationValue private
The result of a function evaluation
Definition at line 154 of file COptMethodNelderMead.h.
Referenced by evaluate(), and optimise().
size_t COptMethodNelderMead::mhIteration private
Handle to the process report item "Current Iteration"
Definition at line 114 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
unsigned C_INT32 COptMethodNelderMead::mIteration private
The number of iterations
Definition at line 109 of file COptMethodNelderMead.h.
Referenced by initialize(), initObjects(), and optimise().
unsigned C_INT32 COptMethodNelderMead::mIterationLimit private
The maximum number of iterations
Definition at line 94 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
C_FLOAT64 COptMethodNelderMead::mScale private
The scale
Definition at line 104 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
CMatrix< C_FLOAT64 > COptMethodNelderMead::mSimplex private
The simplex
Definition at line 124 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
CVector< C_FLOAT64 > COptMethodNelderMead::mStep private
The step taken
Definition at line 144 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
C_FLOAT64 COptMethodNelderMead::mTolerance private
The tolerance
Definition at line 99 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
CVector< C_FLOAT64 > COptMethodNelderMead::mValue private
Array of values of objective function for each corner of the simplex
Definition at line 129 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
size_t COptMethodNelderMead::mVariableSize private
number of parameters
Definition at line 119 of file COptMethodNelderMead.h.
Referenced by initialize(), and optimise().
The documentation for this class was generated from the following files:
COptMethodNelderMead.h
COptMethodNelderMead.cpp