COPASI API: CopasiSlider Class Reference
CopasiSlider Class Reference
#include <CopasiSlider.h>
Public Slots
void closeButtonClicked ()
void editButtonClicked ()
void qSliderPressed ()
void qSliderReleased ()
void sliderValueChanged (int value)
Signals
void closeClicked (CopasiSlider *slider)
void editClicked (CopasiSlider *slider)
void sliderPressed ()
void sliderReleased ()
void valueChanged (double)
Public Member Functions
CopasiSlider (CSlider *pSlider, DataModelGUI *pDM, QWidget *parent=0)
void focusSlider ()
CSlider * getCSlider () const
bool isValid () const
C_FLOAT64 maxValue () const
unsigned C_INT32 minorMajorFactor () const
C_FLOAT64 minorTickInterval () const
C_FLOAT64 minValue () const
unsigned C_INT32 numMinorTicks () const
CCopasiObject * object () const
C_FLOAT64 originalValue () const
void resetValue ()
void setMaxValue (C_FLOAT64 value)
void setMinorMajorFactor (unsigned C_INT32 factor)
void setMinValue (C_FLOAT64 value)
void setNumMinorTicks (unsigned C_INT32 numMinorTicks)
void setObject (CCopasiObject *object)
void setOriginalValue (C_FLOAT64 value)
void setType (CSlider::Type type)
void setValue (C_FLOAT64 value)
CSlider::Type type () const
void updateLabel ()
void updateSliderData ()
void updateValue (bool modifyRange, bool updateDependencies)
C_FLOAT64 value () const
virtual ~CopasiSlider ()
Protected Member Functions
int calculatePositionFromValue (C_FLOAT64 value)
C_FLOAT64 calculateValueFromPosition (int position)
Protected Attributes
QToolButton * mpCloseButton
CSlider * mpCSlider
DataModelGUI * mpDM
QToolButton * mpEditButton
QLabel * mpLabel
QSlider * mpQSlider
bool mValueOutOfRange
Detailed Description
Definition at line 34 of file CopasiSlider.h.
Constructor & Destructor Documentation
CopasiSlider::CopasiSlider (CSlider * pSlider, DataModelGUI * pDM, QWidget * parent = 0)
Definition at line 34 of file CopasiSlider.cpp.
References closeButtonClicked(), CSlider::compile(), CQIconResource::edit, editButtonClicked(), CQIconResource::editDelete, CQIconResource::icon(), mpCloseButton, mpCSlider, mpEditButton, mpLabel, mpQSlider, qSliderPressed(), qSliderReleased(), sliderPressed(), sliderReleased(), sliderValueChanged(), updateSliderData(), and valueChanged().
                                                                                :
   QFrame(parent),
   mpCSlider(pSlider),
   mpQSlider(NULL),
   mpLabel(NULL),
   mpCloseButton(NULL),
   mpEditButton(NULL),
   mValueOutOfRange(false),
   mpDM(pDM)
 {
   this->setLayout(new QHBoxLayout);
   this->setFrameShape(QFrame::Box);
   this->layout()->setContentsMargins(2, 2, 2, 2);
   //this->layout()->setSpacing(0);
   //this->layout()->setMargin(0);
   QFrame* pFrame = new QFrame(NULL);
   pFrame->setLayout(new QVBoxLayout);
   pFrame->layout()->setContentsMargins(2, 2, 2, 2);
   this->mpLabel = new QLabel(NULL);
   this->mpLabel->setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Fixed);
   pFrame->layout()->addWidget(this->mpLabel);
   this->mpQSlider = new QSlider(Qt::Horizontal);
   mpQSlider->setFocusPolicy(Qt::WheelFocus);
   this->mpQSlider->setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Fixed);
 #ifdef WIN32
   this->mpQSlider->setMinimumHeight(10);
 #endif
   pFrame->layout()->addWidget(this->mpQSlider);
   this->layout()->addWidget(pFrame);
   pFrame = new QFrame(NULL);
   pFrame->setLayout(new QVBoxLayout);
   pFrame->layout()->setContentsMargins(2, 2, 2, 2);
   this->mpCloseButton = new QToolButton(NULL);
   this->mpCloseButton->setIcon(CQIconResource::icon(CQIconResource::editDelete));
   pFrame->layout()->addWidget(this->mpCloseButton);
   this->mpEditButton = new QToolButton(NULL);
   this->mpEditButton->setIcon(CQIconResource::icon(CQIconResource::edit));
   pFrame->layout()->addWidget(this->mpEditButton);
   this->layout()->addWidget(pFrame);
   if (!this->mpCSlider->compile())
     {
       this->mpQSlider->setEnabled(false);
     }
   this->updateSliderData();
   this->mpCloseButton->setToolTip(tr("Remove Slider"));
   this->mpEditButton->setToolTip(tr("Edit Slider"));
   connect(this->mpQSlider, SIGNAL(valueChanged(int)), this, SLOT(sliderValueChanged(int)));
   connect(this->mpQSlider, SIGNAL(sliderReleased()), this, SLOT(qSliderReleased()));
   connect(this->mpQSlider, SIGNAL(sliderPressed()), this, SLOT(qSliderPressed()));
   connect(this->mpCloseButton, SIGNAL(clicked()), this, SLOT(closeButtonClicked()));
   connect(this->mpEditButton, SIGNAL(clicked()), this, SLOT(editButtonClicked()));
   setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Fixed);
   // We need to assure that the slider is compiled
   if (mpCSlider) mpCSlider->compile();
 }
CopasiSlider::~CopasiSlider () virtual
Definition at line 99 of file CopasiSlider.cpp.
 {}
Member Function Documentation
int CopasiSlider::calculatePositionFromValue (C_FLOAT64 value) protected
Definition at line 381 of file CopasiSlider.cpp.
References CSlider::getMaxValue(), CSlider::getMinValue(), CSlider::getScaling(), CSlider::getTickNumber(), CSlider::linear, CSlider::logarithmic, minorTickInterval(), and mpCSlider.
Referenced by setMaxValue(), setMinValue(), setNumMinorTicks(), setValue(), and updateSliderData().
 {
   int position;
   switch (this->mpCSlider->getScaling())
     {
       case CSlider::linear:
         position = (int)floor(((value - this->mpCSlider->getMinValue()) / this->minorTickInterval()) + 0.5);
         break;
       case CSlider::logarithmic:
         position = (int)floor((this->mpCSlider->getTickNumber() * (log10(value / this->mpCSlider->getMinValue()) / log10(this->mpCSlider->getMaxValue() / this->mpCSlider->getMinValue()))) + 0.5);
         break;
       default:
         position = 0;
     }
   return position;
 }
C_FLOAT64 CopasiSlider::calculateValueFromPosition (int position) protected
Definition at line 357 of file CopasiSlider.cpp.
References CSlider::getMaxValue(), CSlider::getMinValue(), CSlider::getScaling(), CSlider::getTickNumber(), CSlider::linear, CSlider::logarithmic, minorTickInterval(), mpCSlider, and value().
Referenced by sliderValueChanged().
 {
   double value;
   double exponent;
   switch (this->mpCSlider->getScaling())
     {
       case CSlider::linear:
         value = this->mpCSlider->getMinValue() + position * this->minorTickInterval();
         break;
       case CSlider::logarithmic:
         exponent = (((double)position) * log10(this->mpCSlider->getMaxValue() / this->mpCSlider->getMinValue())) / this->mpCSlider->getTickNumber();
         value = this->mpCSlider->getMinValue() * pow(10.0, exponent);
         break;
       default:
         value = 0.0;
         break;
     }
   return value;
 }
void CopasiSlider::closeButtonClicked () slot
Definition at line 342 of file CopasiSlider.cpp.
References closeClicked().
Referenced by CopasiSlider().
 {
   emit closeClicked(this);
 }
void CopasiSlider::closeClicked (CopasiSlider * slider) signal
Referenced by closeButtonClicked().
void CopasiSlider::editButtonClicked () slot
Definition at line 347 of file CopasiSlider.cpp.
References editClicked().
Referenced by CopasiSlider().
 {
   emit editClicked(this);
 }
void CopasiSlider::editClicked (CopasiSlider * slider) signal
Referenced by editButtonClicked().
void CopasiSlider::focusSlider ()
Definition at line 102 of file CopasiSlider.cpp.
References mpQSlider.
Referenced by SliderDialog::changeEvent(), and SliderDialog::setCurrentSlider().
 {
   if (mpQSlider == NULL) return;
   mpQSlider->setFocus(Qt::OtherFocusReason);
 }
CSlider * CopasiSlider::getCSlider () const
Definition at line 352 of file CopasiSlider.cpp.
References mpCSlider.
Referenced by SliderDialog::editSlider(), SliderDialog::findCopasiSliderForCSlider(), SliderDialog::getCopasiSliderForCSlider(), SliderDialog::getCSliderForCopasiSlider(), and SliderDialog::removeSlider().
 {
   return this->mpCSlider;
 }
bool CopasiSlider::isValid () const
Checks whether the slider is actually valid. This is mainly done by calling isValid on the underlying CSlider object.
Definition at line 420 of file CopasiSlider.cpp.
References CSlider::isValid(), and mpCSlider.
Referenced by SliderDialog::deleteInvalidSliders().
 {
   return (this->mpCSlider != NULL && this->mpCSlider->isValid());
 }
C_FLOAT64 CopasiSlider::maxValue () const
Definition at line 208 of file CopasiSlider.cpp.
References CSlider::getMaxValue(), and mpCSlider.
Referenced by SliderDialog::setCorrectSliderObject(), updateLabel(), and updateValue().
 {
   return this->mpCSlider->getMaxValue();
 }
unsigned C_INT32 CopasiSlider::minorMajorFactor () const
Definition at line 174 of file CopasiSlider.cpp.
References CSlider::getTickFactor(), and mpCSlider.
 {
   return this->mpCSlider->getTickFactor();
 }
C_FLOAT64 CopasiSlider::minorTickInterval () const
Definition at line 185 of file CopasiSlider.cpp.
References C_FLOAT64, CSlider::getMaxValue(), CSlider::getMinValue(), CSlider::getTickNumber(), and mpCSlider.
Referenced by calculatePositionFromValue(), and calculateValueFromPosition().
 {
   return (C_FLOAT64)(this->mpCSlider->getMaxValue() - this->mpCSlider->getMinValue()) / ((C_FLOAT64)this->mpCSlider->getTickNumber());
 }
C_FLOAT64 CopasiSlider::minValue () const
Definition at line 203 of file CopasiSlider.cpp.
References CSlider::getMinValue(), and mpCSlider.
Referenced by SliderDialog::setCorrectSliderObject(), updateLabel(), and updateValue().
 {
   return this->mpCSlider->getMinValue();
 }
unsigned C_INT32 CopasiSlider::numMinorTicks () const
Definition at line 198 of file CopasiSlider.cpp.
References CSlider::getTickNumber(), and mpCSlider.
 {
   return this->mpCSlider->getTickNumber();
 }
CCopasiObject * CopasiSlider::object () const
Definition at line 213 of file CopasiSlider.cpp.
References CSlider::getSliderObject(), and mpCSlider.
Referenced by SliderDialog::fillSliderBox(), SliderDialog::setCorrectSliderObject(), SliderDialog::setFramework(), setValue(), and updateValue().
 {
   return this->mpCSlider->getSliderObject();
 }
C_FLOAT64 CopasiSlider::originalValue () const
Definition at line 407 of file CopasiSlider.cpp.
References CSlider::getOriginalValue(), and mpCSlider.
Referenced by resetValue().
 {
   return this->mpCSlider->getOriginalValue();
 }
void CopasiSlider::qSliderPressed () slot
Definition at line 289 of file CopasiSlider.cpp.
References sliderPressed().
Referenced by CopasiSlider().
 {
   emit sliderPressed();
 }
void CopasiSlider::qSliderReleased () slot
Definition at line 284 of file CopasiSlider.cpp.
References sliderReleased().
Referenced by CopasiSlider().
 {
   emit sliderReleased();
 }
void CopasiSlider::resetValue ()
Definition at line 402 of file CopasiSlider.cpp.
References originalValue(), and setValue().
Referenced by SliderDialog::resetValue().
 {
   this->setValue(this->originalValue());
 }
void CopasiSlider::setMaxValue (C_FLOAT64 value)
Definition at line 224 of file CopasiSlider.cpp.
References calculatePositionFromValue(), CSlider::getSliderValue(), mpCSlider, mpQSlider, CSlider::setMaxValue(), and updateLabel().
Referenced by SliderDialog::setCorrectSliderObject().
 {
   this->mpCSlider->setMaxValue(value);
   this->mpQSlider->setValue(this->calculatePositionFromValue(this->mpCSlider->getSliderValue()));
   this->updateLabel();
 }
void CopasiSlider::setMinorMajorFactor (unsigned C_INT32 factor)
Definition at line 179 of file CopasiSlider.cpp.
References mpCSlider, mpQSlider, and CSlider::setTickFactor().
 {
   this->mpCSlider->setTickFactor(factor);
   this->mpQSlider->setPageStep(this->mpQSlider->singleStep()*factor);
 }
void CopasiSlider::setMinValue (C_FLOAT64 value)
Definition at line 233 of file CopasiSlider.cpp.
References calculatePositionFromValue(), CSlider::getSliderValue(), mpCSlider, mpQSlider, CSlider::setMinValue(), and updateLabel().
Referenced by SliderDialog::setCorrectSliderObject().
 {
   this->mpCSlider->setMinValue(value);
   this->mpQSlider->setValue(this->calculatePositionFromValue(this->mpCSlider->getSliderValue()));
   this->updateLabel();
 }
void CopasiSlider::setNumMinorTicks (unsigned C_INT32 numMinorTicks)
Definition at line 190 of file CopasiSlider.cpp.
References calculatePositionFromValue(), CSlider::getSliderValue(), mpCSlider, mpQSlider, and CSlider::setTickNumber().
 {
   this->mpCSlider->setTickNumber(numMinorTicks);
   // set maxValue and value of slider
   this->mpQSlider->setMaximum(numMinorTicks);
   this->mpQSlider->setValue(this->calculatePositionFromValue(this->mpCSlider->getSliderValue()));
 }
void CopasiSlider::setObject (CCopasiObject * object)
Definition at line 218 of file CopasiSlider.cpp.
References mpCSlider, CSlider::setSliderObject(), and updateSliderData().
Referenced by SliderDialog::setCorrectSliderObject().
 {
   this->mpCSlider->setSliderObject(object);
   this->updateSliderData();
 }
void CopasiSlider::setOriginalValue (C_FLOAT64 value)
Definition at line 412 of file CopasiSlider.cpp.
References mpCSlider, and CSlider::setOriginalValue().
Referenced by SliderDialog::setDefault().
 {
   this->mpCSlider->setOriginalValue(value);
 }
void CopasiSlider::setType (CSlider::Type type)
Definition at line 299 of file CopasiSlider.cpp.
References mpCSlider, and CSlider::setSliderType().
 {
   this->mpCSlider->setSliderType(type);
 }
void CopasiSlider::setValue (C_FLOAT64 value)
Definition at line 141 of file CopasiSlider.cpp.
References C_INT32, calculatePositionFromValue(), CSlider::getSliderValue(), CCopasiObject::isValueBool(), CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), mpCSlider, mpDM, mpQSlider, object(), DataModelGUI::refreshInitialValues(), CCopasiObject::setObjectValue(), CSlider::setSliderValue(), and updateLabel().
Referenced by resetValue().
 {
   // we set the value ourselves so that listviews can do the
   // update of the dependent values as well as taking the framework into
   // consideration
   // first we set the slider value without actually writing to the underlying object
   this->mpCSlider->setSliderValue(value, false);
   /* reget value in case it was outside range and got set to minValue or
    * maxValue */
   value = this->mpCSlider->getSliderValue();
   // now we handle writing to the object ourselves
   CCopasiObject* pObject = this->object();
   if (pObject == NULL) return;
   if (pObject->isValueDbl())
     pObject->setObjectValue(value);
   else if (pObject->isValueInt())
     pObject->setObjectValue((C_INT32) floor(value + 0.5));
   else if (pObject->isValueBool())
     pObject->setObjectValue(value != 0.0);
   // recalculate all other dependent values
   mpDM->refreshInitialValues();
   this->mpQSlider->setValue(this->calculatePositionFromValue(value));
   this->updateLabel();
 }
void CopasiSlider::sliderPressed () signal
Referenced by CopasiSlider(), and qSliderPressed().
void CopasiSlider::sliderReleased () signal
Referenced by CopasiSlider(), and qSliderReleased().
void CopasiSlider::sliderValueChanged (int value) slot
Definition at line 275 of file CopasiSlider.cpp.
References calculateValueFromPosition(), CSlider::getSliderValue(), mpCSlider, CSlider::setSliderValue(), updateLabel(), and valueChanged().
Referenced by CopasiSlider(), and updateSliderData().
 {
   this->mpCSlider->setSliderValue(this->calculateValueFromPosition(value), false);
   this->updateLabel();
   emit valueChanged(this->mpCSlider->getSliderValue());
 }
CSlider::Type CopasiSlider::type () const
Definition at line 294 of file CopasiSlider.cpp.
References CSlider::getSliderType(), and mpCSlider.
 {
   return this->mpCSlider->getSliderType();
 }
void CopasiSlider::updateLabel ()
Definition at line 242 of file CopasiSlider.cpp.
References FROM_UTF8, CSlider::getMaxValue(), CSlider::getMinValue(), CCopasiObject::getObjectDisplayName(), CSlider::getSliderObject(), CSlider::getSliderValue(), maxValue(), minValue(), mpCSlider, mpLabel, and mValueOutOfRange.
Referenced by setMaxValue(), setMinValue(), setValue(), sliderValueChanged(), and updateSliderData().
 {
   double minValue, maxValue, currValue;
   minValue = this->mpCSlider->getMinValue();
   maxValue = this->mpCSlider->getMaxValue();
   currValue = this->mpCSlider->getSliderValue();
   CCopasiObject* object = this->mpCSlider->getSliderObject();
   QString labelString = "";
   if (object)
     {
       labelString += FROM_UTF8(object->getObjectDisplayName(true, true));
       labelString += " : [";
       labelString += QString::number(minValue);
       labelString += "-";
       labelString += QString::number(maxValue);
       labelString += "] {";
       labelString += QString::number(currValue);
       labelString += "}";
       if (this->mValueOutOfRange)
         {
           labelString += " (Value out of range!)";
         }
     }
   else
     {
       labelString += "Object not available!";
     }
   this->mpLabel->setText(labelString);
 }
void CopasiSlider::updateSliderData ()
Definition at line 109 of file CopasiSlider.cpp.
References calculatePositionFromValue(), CSlider::getSliderObject(), CSlider::getSliderValue(), CSlider::getTickFactor(), CSlider::getTickNumber(), mpCSlider, mpQSlider, sliderValueChanged(), updateLabel(), and valueChanged().
Referenced by SliderDialog::addSlider(), CopasiSlider(), SliderDialog::createNewSlider(), SliderDialog::editSlider(), SliderDialog::fillSliderBox(), setObject(), and SliderDialog::updateAllSliders().
 {
   if (this->mpCSlider)
     {
       //mpCSlider->compile();
       this->mpQSlider->setMinimum(0);
       this->mpQSlider->setMaximum(this->mpCSlider->getTickNumber());
       this->mpQSlider->setTickInterval(1);
       this->mpQSlider->setSingleStep(1);
       this->mpQSlider->setPageStep(this->mpCSlider->getTickFactor());
       disconnect(this->mpQSlider, SIGNAL(valueChanged(int)), this, SLOT(sliderValueChanged(int)));
       this->mpQSlider->setValue(this->calculatePositionFromValue(this->mpCSlider->getSliderValue()));
       connect(this->mpQSlider, SIGNAL(valueChanged(int)), this, SLOT(sliderValueChanged(int)));
       this->updateLabel();
       if (this->mpQSlider->isEnabled() == false)
         {
           if (this->mpCSlider->getSliderObject() != NULL)
             {
               this->mpQSlider->setEnabled(true);
             }
         }
       this->update();
     }
 }
void CopasiSlider::updateValue (bool modifyRange, bool updateDependencies)
Definition at line 304 of file CopasiSlider.cpp.
References C_INT32, CSlider::getMaxValue(), CSlider::getMinValue(), CSlider::getSliderValue(), CCopasiObject::isValueBool(), CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), maxValue(), minValue(), mpCSlider, mpDM, mValueOutOfRange, object(), DataModelGUI::refreshInitialValues(), CSlider::resetRange(), CCopasiObject::setObjectValue(), and value().
Referenced by SliderDialog::updateAllSliders().
 {
   double value = this->mpCSlider->getSliderValue();
   double maxValue = this->mpCSlider->getMaxValue();
   double minValue = this->mpCSlider->getMinValue();
   if ((value > maxValue) || (value < minValue))
     {
       if (!modifyRange)
         {
           this->mValueOutOfRange = true;
         }
       else
         {
           this->mValueOutOfRange = false;
           this->mpCSlider->resetRange();
         }
     }
   // now we handle writing to the object ourselves
   CCopasiObject* pObject = this->object();
   if (pObject == NULL) return;
   if (pObject->isValueDbl())
     pObject->setObjectValue(value);
   else if (pObject->isValueInt())
     pObject->setObjectValue((C_INT32) floor(value + 0.5));
   else if (pObject->isValueBool())
     pObject->setObjectValue(value != 0.0);
   // recalculate all other dependent values
   if (updateDependencies)
     {
       mpDM->refreshInitialValues();
     }
 }
C_FLOAT64 CopasiSlider::value () const
Definition at line 136 of file CopasiSlider.cpp.
References CSlider::getSliderValue(), and mpCSlider.
Referenced by calculateValueFromPosition(), SliderDialog::setCorrectSliderObject(), SliderDialog::setDefault(), and updateValue().
 {
   return this->mpCSlider->getSliderValue();
 }
void CopasiSlider::valueChanged (double) signal
Referenced by CopasiSlider(), sliderValueChanged(), and updateSliderData().
Member Data Documentation
QToolButton* CopasiSlider::mpCloseButton protected
Definition at line 90 of file CopasiSlider.h.
Referenced by CopasiSlider().
CSlider* CopasiSlider::mpCSlider protected
Definition at line 87 of file CopasiSlider.h.
Referenced by calculatePositionFromValue(), calculateValueFromPosition(), CopasiSlider(), getCSlider(), isValid(), maxValue(), minorMajorFactor(), minorTickInterval(), minValue(), numMinorTicks(), object(), originalValue(), setMaxValue(), setMinorMajorFactor(), setMinValue(), setNumMinorTicks(), setObject(), setOriginalValue(), setType(), setValue(), sliderValueChanged(), type(), updateLabel(), updateSliderData(), updateValue(), and value().
DataModelGUI* CopasiSlider::mpDM protected
Definition at line 93 of file CopasiSlider.h.
Referenced by setValue(), and updateValue().
QToolButton* CopasiSlider::mpEditButton protected
Definition at line 91 of file CopasiSlider.h.
Referenced by CopasiSlider().
QLabel* CopasiSlider::mpLabel protected
Definition at line 89 of file CopasiSlider.h.
Referenced by CopasiSlider(), and updateLabel().
QSlider* CopasiSlider::mpQSlider protected
Definition at line 88 of file CopasiSlider.h.
Referenced by CopasiSlider(), focusSlider(), setMaxValue(), setMinorMajorFactor(), setMinValue(), setNumMinorTicks(), setValue(), and updateSliderData().
bool CopasiSlider::mValueOutOfRange protected
Definition at line 92 of file CopasiSlider.h.
Referenced by updateLabel(), and updateValue().
The documentation for this class was generated from the following files:
CopasiSlider.h
CopasiSlider.cpp