COPASI API: CSparseMatrixElement Class Reference
CSparseMatrixElement Class Reference
#include <CSparseMatrix.h>
Public Member Functions
const size_t & col () const
CSparseMatrixElement (CSparseMatrix &matrix, const size_t &rowIndex, const size_t &colIndex, const C_FLOAT64 &value)
operator const C_FLOAT64 & () const
const C_FLOAT64 & operator= (const C_FLOAT64 &value)
const size_t & row () const
~CSparseMatrixElement ()
Static Public Member Functions
static bool compareCol (const CSparseMatrixElement *pLhs, const CSparseMatrixElement *pRhs)
static bool compareRow (const CSparseMatrixElement *pLhs, const CSparseMatrixElement *pRhs)
Private Member Functions
CSparseMatrixElement ()
Private Attributes
const size_t & mCol
CSparseMatrix & mMatrix
const size_t & mRow
C_FLOAT64 mValue
Detailed Description
Definition at line 34 of file CSparseMatrix.h.
Constructor & Destructor Documentation
CSparseMatrixElement::CSparseMatrixElement () private
CSparseMatrixElement::CSparseMatrixElement (CSparseMatrix & matrix, const size_t & rowIndex, const size_t & colIndex, const C_FLOAT64 & value)
Definition at line 43 of file CSparseMatrix.cpp.
                             :
   mMatrix(matrix),
   mRow(row),
   mCol(col),
   mValue(value)
 {}
CSparseMatrixElement::~CSparseMatrixElement ()
Definition at line 53 of file CSparseMatrix.cpp.
 {}
Member Function Documentation
const size_t & CSparseMatrixElement::col () const
Definition at line 74 of file CSparseMatrix.cpp.
References mCol.
 {return mCol;}
bool CSparseMatrixElement::compareCol (const CSparseMatrixElement * pLhs, const CSparseMatrixElement * pRhs) static
Definition at line 39 of file CSparseMatrix.cpp.
References mCol.
Referenced by CSparseMatrix::insert(), CSparseMatrix::operator=(), and CSparseMatrix::remove().
 {return pLhs->mCol < pRhs->mCol;}
bool CSparseMatrixElement::compareRow (const CSparseMatrixElement * pLhs, const CSparseMatrixElement * pRhs) static
Definition at line 35 of file CSparseMatrix.cpp.
References mRow.
Referenced by CSparseMatrix::insert(), CSparseMatrix::operator()(), CSparseMatrix::operator=(), and CSparseMatrix::remove().
 {return pLhs->mRow < pRhs->mRow;}
CSparseMatrixElement::operator const C_FLOAT64 & () const
Definition at line 70 of file CSparseMatrix.cpp.
 {return mValue;}
const C_FLOAT64 & CSparseMatrixElement::operator= (const C_FLOAT64 & value)
Definition at line 56 of file CSparseMatrix.cpp.
References CSparseMatrix::getTreshold(), CSparseMatrix::insert(), mCol, mMatrix, mRow, mValue, and CSparseMatrix::remove().
 {
   if (fabs(value) < mMatrix.getTreshold() &&
       fabs(mValue) >= mMatrix.getTreshold())
     mMatrix.remove(mRow, mCol);
   else if (fabs(value) >= mMatrix.getTreshold() &&
            fabs(mValue) < mMatrix.getTreshold())
     mMatrix.insert(mRow, mCol, value);
   else
     mValue = value;
   return value;
 }
const size_t & CSparseMatrixElement::row () const
Definition at line 73 of file CSparseMatrix.cpp.
References mRow.
 {return mRow;}
Member Data Documentation
const size_t& CSparseMatrixElement::mCol private
Definition at line 63 of file CSparseMatrix.h.
Referenced by col(), compareCol(), and operator=().
CSparseMatrix& CSparseMatrixElement::mMatrix private
Definition at line 61 of file CSparseMatrix.h.
Referenced by operator=().
const size_t& CSparseMatrixElement::mRow private
Definition at line 62 of file CSparseMatrix.h.
Referenced by compareRow(), operator=(), and row().
C_FLOAT64 CSparseMatrixElement::mValue private
Definition at line 64 of file CSparseMatrix.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
CSparseMatrix.h
CSparseMatrix.cpp