COPASI API: CCopasiXMLParser::GlobalRenderInformationElement Class Reference
CCopasiXMLParser::GlobalRenderInformationElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
GlobalRenderInformationElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~GlobalRenderInformationElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
GlobalRenderInformation = 0, ListOfColorDefinitions, ListOfGradientDefinitions, ListOfLineEndings,
ListOfStyles
}
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 4689 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::GlobalRenderInformationElement::Element private
Enumerator
GlobalRenderInformation
ListOfColorDefinitions
ListOfGradientDefinitions
ListOfLineEndings
ListOfStyles
Definition at line 4696 of file CCopasiXMLParser.h.
     {
       GlobalRenderInformation = 0,
       ListOfColorDefinitions,
       ListOfGradientDefinitions,
       ListOfLineEndings,
       ListOfStyles
     };
Constructor & Destructor Documentation
CCopasiXMLParser::GlobalRenderInformationElement::GlobalRenderInformationElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 14133 of file CCopasiXMLParser.cpp.
                                     :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common)
 {}
CCopasiXMLParser::GlobalRenderInformationElement::~GlobalRenderInformationElement () virtual
Destructor
Definition at line 14138 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::GlobalRenderInformationElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 14235 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pRenderInformation, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "RenderInformation"))
     {
       mParser.popElementHandler();
       mCommon.pRenderInformation = NULL;
       //reset handler
       mCurrentElement = START_ELEMENT;
       //call parent handler
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case ListOfColorDefinitions:
             if (strcmp(pszName, "ListOfColorDefinitions"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                              pszName, "ListOfColorDefinitions", mParser.getCurrentLineNumber());
             deleteCurrentHandler();
             break;
           case ListOfGradientDefinitions:
             if (strcmp(pszName, "ListOfGradientDefinitions"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                              pszName, "ListOfGradientDefinitions", mParser.getCurrentLineNumber());
             deleteCurrentHandler();
             break;
           case ListOfLineEndings:
             if (strcmp(pszName, "ListOfLineEndings"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                              pszName, "ListOfLineEndings", mParser.getCurrentLineNumber());
             deleteCurrentHandler();
             break;
           case ListOfStyles:
             if (strcmp(pszName, "ListOfStyles"))
               CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                              pszName, "ListOfStyles", mParser.getCurrentLineNumber());
             deleteCurrentHandler();
             break;
           case UNKNOWN_ELEMENT:
             mCurrentElement = mLastKnownElement;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::GlobalRenderInformationElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 14141 of file CCopasiXMLParser.cpp.
References CListOfLayouts::addGlobalRenderInformation(), CCopasiMessage::EXCEPTION, CListOfLayouts::getListOfGlobalRenderInformationObjects(), CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pLayoutList, SCopasiXMLParserCommon::pRenderInformation, CLRenderInformationBase::setBackgroundColor(), CCopasiVector< T >::size(), and UNKNOWN_ELEMENT.
 {
   mCurrentElement++; /* We should always be on the next element */
   mpCurrentHandler = NULL;
   const char* background;
   switch (mCurrentElement)
     {
       case GlobalRenderInformation:
         if (strcmp(pszName, "RenderInformation"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "RenderInformation", mParser.getCurrentLineNumber());
         mCommon.pLayoutList->addGlobalRenderInformation(new CLGlobalRenderInformation());
         // delete the global render information again since the addGlobalRenderInformationObject method made a copy
         assert(mCommon.pLayoutList->getListOfGlobalRenderInformationObjects().size() > 0);
         mCommon.pRenderInformation = mCommon.pLayoutList->getListOfGlobalRenderInformationObjects()[mCommon.pLayoutList->getListOfGlobalRenderInformationObjects().size() - 1];
         background = mParser.getAttributeValue("backgroundColor", papszAttrs);
         assert(background != NULL);
         if (background != NULL)
           {
             mCommon.pRenderInformation->setBackgroundColor(background);
           }
         // we have to return here because otherwise the call
         // at the end will lead to an endless loop
         return;
         break;
       case ListOfColorDefinitions:
         if (!strcmp(pszName, "ListOfColorDefinitions"))
           {
             this->mLastKnownElement = ListOfColorDefinitions;
             mpCurrentHandler = new ListOfColorDefinitionsElement(mParser, mCommon);
           }
         break;
       case ListOfGradientDefinitions:
         if (!strcmp(pszName, "ListOfGradientDefinitions"))
           {
             this->mLastKnownElement = ListOfGradientDefinitions;
             mpCurrentHandler = new ListOfGradientDefinitionsElement(mParser, mCommon);
           }
         break;
       case ListOfLineEndings:
         if (!strcmp(pszName, "ListOfLineEndings"))
           {
             this->mLastKnownElement = ListOfLineEndings;
             mpCurrentHandler = new ListOfLineEndingsElement(mParser, mCommon);
           }
         break;
       case ListOfStyles:
         if (!strcmp(pszName, "ListOfStyles"))
           {
             this->mLastKnownElement = ListOfStyles;
             mpCurrentHandler = new ListOfGlobalStylesElement(mParser, mCommon);
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mParser.pushElementHandler(&mParser.mUnknownElement);
         mParser.onStartElement(pszName, papszAttrs);
         break;
     }
   // if we created a handler in this call, we add it to the stack
   if (this->mpCurrentHandler != NULL)
     {
       this->mParser.pushElementHandler(this->mpCurrentHandler);
     }
   // we call the current handler
   // if we created one, the new one will be called, otherwise
   // the one for ListOfLayouts should be the current one
   // and this method will be called again
   this->mParser.onStartElement(pszName, papszAttrs);
   return;
 }
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp