COPASI API: CStepMatrixColumn Class Reference
CStepMatrixColumn Class Reference
#include <CStepMatrixColumn.h>
Public Member Functions
void convert (const CZeroSet::CIndex &bit)
CStepMatrixColumn (const size_t &size=0)
CStepMatrixColumn (const CZeroSet &set, CStepMatrixColumn const *pPositive, CStepMatrixColumn const *pNegative)
void getAllUnsetBitIndexes (CVector< size_t > &indexes) const
const C_INT64 & getMultiplier () const
std::vector< C_INT64 > & getReaction ()
const CZeroSet & getZeroSet () const
void push_front (const C_INT64 &value)
void setIterator (CStepMatrixColumn **it)
void truncate ()
void unsetBit (const CZeroSet::CIndex &index)
~CStepMatrixColumn ()
Private Attributes
CStepMatrixColumn ** mIterator
std::vector< C_INT64 > mReaction
CZeroSet mZeroSet
Friends
std::ostream & operator<< (std::ostream &, const CStepMatrixColumn &)
Detailed Description
Definition at line 26 of file CStepMatrixColumn.h.
Constructor & Destructor Documentation
CStepMatrixColumn::CStepMatrixColumn (const size_t & size = 0)
Definition at line 28 of file CStepMatrixColumn.cpp.
                                                        :
     mZeroSet(size),
     mReaction(),
     mIterator(NULL)
 {}
CStepMatrixColumn::CStepMatrixColumn (const CZeroSet & set, CStepMatrixColumn const * pPositive, CStepMatrixColumn const * pNegative)
Definition at line 34 of file CStepMatrixColumn.cpp.
References abs64, C_INT64, CBitPatternTreeMethod::GCD(), getMultiplier(), and mReaction.
                                                                          :
     mZeroSet(set),
     mReaction(),
     mIterator(NULL)
 {
   C_INT64 PosMult = -pNegative->getMultiplier();
   C_INT64 NegMult = pPositive->getMultiplier();
   C_INT64 GCD1 = abs64(PosMult);
   C_INT64 GCD2 = abs64(NegMult);
   // Divide PosMult and NegMult by GCD(PosMult, NegMult);
   CBitPatternTreeMethod::GCD(GCD1, GCD2);
   if (GCD1 != 1)
     {
       PosMult /= GCD1;
       NegMult /= GCD1;
     }
   // -1 is used to identify the start of the GCD search.
   GCD1 = -1;
   mReaction.resize(pPositive->mReaction.size());
   std::vector< C_INT64 >::iterator it = mReaction.begin();
   std::vector< C_INT64 >::iterator end = mReaction.end();
   std::vector< C_INT64 >::const_iterator itPos = pPositive->mReaction.begin();
   std::vector< C_INT64 >::const_iterator itNeg = pNegative->mReaction.begin();
   for (; it != end; ++it, ++itPos, ++itNeg)
     {
       // TODO We need to check that we do not have numerical overflow
       *it = PosMult * *itPos + NegMult * *itNeg;
       if (*it == 0 || GCD1 == 1)
         {
           continue;
         }
       if (GCD1 == -1)
         {
           GCD1 = abs64(*it);
           continue;
         }
       GCD2 = abs64(*it);
       CBitPatternTreeMethod::GCD(GCD1, GCD2);
     }
   if (GCD1 > 1)
     {
       for (it = mReaction.begin(); it != end; ++it)
         {
           *it /= GCD1;
         }
     }
 }
CStepMatrixColumn::~CStepMatrixColumn ()
Definition at line 96 of file CStepMatrixColumn.cpp.
References mIterator.
 {
   assert(*mIterator = this);
   *mIterator = NULL;
 }
Member Function Documentation
void CStepMatrixColumn::convert (const CZeroSet::CIndex & bit)
void CStepMatrixColumn::getAllUnsetBitIndexes (CVector< size_t > & indexes) const
Definition at line 113 of file CStepMatrixColumn.cpp.
References CVectorCore< CType >::array(), CZeroSet::getNumberOfBits(), CZeroSet::isSet(), mReaction, mZeroSet, and CVector< CType >::resize().
Referenced by CStepMatrix::getAllUnsetBitIndexes().
 {
   size_t Size = mZeroSet.getNumberOfBits();
   indexes.resize(Size);
   size_t * pIndex = indexes.array();
   CZeroSet::CIndex Index;
   size_t i = 0;
   size_t imax = Size - mReaction.size();
   for (; i < imax; ++i, ++Index)
     {
       if (!mZeroSet.isSet(Index))
         {
           *pIndex = i;
           pIndex++;
         }
     }
   for (i = mReaction.size(); i > 0;)
     {
       --i;
       if (mReaction[i] != 0)
         {
           *pIndex = (mReaction.size() - i - 1) + imax;
           pIndex++;
         }
     }
   Size = pIndex - indexes.array();
   indexes.resize(Size, true);
   //DebugFile << *this << std::endl;
   //DebugFile << "@CSMC: " << indexes << std::endl;
 }
const C_INT64& CStepMatrixColumn::getMultiplier () const inline
Definition at line 50 of file CStepMatrixColumn.h.
References mReaction.
Referenced by CStepMatrixColumn().
   {
     return mReaction.back();
   }
std::vector< C_INT64 > & CStepMatrixColumn::getReaction ()
Definition at line 108 of file CStepMatrixColumn.cpp.
References mReaction.
 {
   return mReaction;
 }
const CZeroSet & CStepMatrixColumn::getZeroSet () const
Definition at line 103 of file CStepMatrixColumn.cpp.
References mZeroSet.
Referenced by CBitPatternTreeNode::CBitPatternTreeNode(), CBitPatternMethod::combine(), and CStepMatrix::getUnsetBitIndexes().
 {
   return mZeroSet;
 }
void CStepMatrixColumn::push_front (const C_INT64 & value)
Definition at line 150 of file CStepMatrixColumn.cpp.
References mReaction.
Referenced by CBitPatternMethod::buildFluxModeMatrix(), CStepMatrix::CStepMatrix(), and CBitPatternMethod::initialize().
 {
   mReaction.insert(mReaction.begin(), value);
 }
void CStepMatrixColumn::setIterator (CStepMatrixColumn ** it) inline
Definition at line 63 of file CStepMatrixColumn.h.
References mIterator.
Referenced by CStepMatrix::add().
   {
     mIterator = it;
   }
void CStepMatrixColumn::truncate ()
Definition at line 155 of file CStepMatrixColumn.cpp.
References mReaction.
 {
   mReaction.pop_back();
 }
void CStepMatrixColumn::unsetBit (const CZeroSet::CIndex & index) inline
Definition at line 45 of file CStepMatrixColumn.h.
References mZeroSet, and CZeroSet::unsetBit().
   {
     mZeroSet.unsetBit(index);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & , const CStepMatrixColumn &) friend
Definition at line 160 of file CStepMatrixColumn.cpp.
 {
   os << ' ';
   size_t Size = c.mZeroSet.getNumberOfBits();
   CZeroSet::CIndex Index;
   size_t i = 0;
   size_t imax = Size - c.mReaction.size();
   for (; i < imax; ++i, ++Index)
     {
       if (c.mZeroSet.isSet(Index))
         {
           os << "*\t";
         }
       else
         {
           os << ".\t";
         }
     }
   for (i = c.mReaction.size(); i > 0;)
     {
       --i;
       os << c.mReaction[i] << "\t";;
     }
   return os;
 }
Member Data Documentation
CStepMatrixColumn** CStepMatrixColumn::mIterator private
Definition at line 74 of file CStepMatrixColumn.h.
Referenced by setIterator(), and ~CStepMatrixColumn().
std::vector< C_INT64 > CStepMatrixColumn::mReaction private
Definition at line 72 of file CStepMatrixColumn.h.
Referenced by CStepMatrixColumn(), getAllUnsetBitIndexes(), getMultiplier(), getReaction(), operator<<(), push_front(), and truncate().
CZeroSet CStepMatrixColumn::mZeroSet private
Definition at line 70 of file CStepMatrixColumn.h.
Referenced by getAllUnsetBitIndexes(), getZeroSet(), operator<<(), and unsetBit().
The documentation for this class was generated from the following files:
CStepMatrixColumn.h
CStepMatrixColumn.cpp