COPASI API: CTrajectoryProblem Class Reference
CTrajectoryProblem Class Reference
#include <CTrajectoryProblem.h>
Public Member Functions
CTrajectoryProblem (const CCopasiContainer *pParent=NULL)
CTrajectoryProblem (const CTrajectoryProblem &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
const bool & getContinueSimultaneousEvents () const
const C_FLOAT64 & getDuration () const
const bool & getOutputEvent () const
const C_FLOAT64 & getOutputStartTime () const
const unsigned C_INT32 & getStepNumber () const
const C_FLOAT64 & getStepSize () const
void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::NEXT)
void setContinueSimultaneousEvents (const bool &continueSimultaneousEvents)
void setDuration (const C_FLOAT64 &duration)
void setOutputEvent (const bool &outputEvent)
void setOutputStartTime (const C_FLOAT64 &endTime)
void setStepNumber (const unsigned C_INT32 &stepNumber)
void setStepSize (const C_FLOAT64 &stepSize)
void setTimeSeriesRequested (bool flag)
bool timeSeriesRequested () const
~CTrajectoryProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual bool initialize ()
virtual void print (std::ostream *ostream) const
virtual void printResult (std::ostream *ostream) const
virtual bool restore (const bool &updateModel)
virtual bool setCallBack (CProcessReport *pCallBack)
virtual bool setModel (CModel *pModel)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
bool * mpContinueSimultaneousEvents
C_FLOAT64 * mpDuration
bool * mpOutputEvent
C_FLOAT64 * mpOutputStartTime
unsigned C_INT32 * mpStepNumber
C_FLOAT64 * mpStepSize
bool * mpTimeSeriesRequested
bool mStepNumberSetLast
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void initializeParameter ()
void initObjects ()
bool sync ()
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CTrajectoryProblem class. This class describes the trajectory problem, i.e., it allows to specify for example initial conditions and number of steps.
Created for Copasi by Stefan Hoops 2002
Definition at line 31 of file CTrajectoryProblem.h.
Constructor & Destructor Documentation
CTrajectoryProblem::CTrajectoryProblem (const CCopasiContainer * pParent = NULL)
Default constructor.
Parameters
const CCopasiContainer * pParent (default: NULL)
CTrajectoryProblem class. This class describes the trajectory problem, i.e., it allows to specify for example initial conditions and number of steps.
Created for COPASI by Stefan Hoops 2002 Default constructor.
Definition at line 37 of file CTrajectoryProblem.cpp.
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
                                                                       :
   CCopasiProblem(CCopasiTask::timeCourse, pParent),
   mpDuration(NULL),
   mpStepSize(NULL),
   mpStepNumber(NULL),
   mpTimeSeriesRequested(NULL),
   mpOutputStartTime(NULL),
   mpOutputEvent(NULL),
   mpContinueSimultaneousEvents(NULL),
   mStepNumberSetLast(true)
 {
   initializeParameter();
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CTrajectoryProblem::CTrajectoryProblem (const CTrajectoryProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CTrajectoryProblem & src CCopasiContainer * pParent (default: NULL)
Copy constructor.
Parameters
const CTrajectoryProblem & src
Definition at line 57 of file CTrajectoryProblem.cpp.
References CONSTRUCTOR_TRACE, initializeParameter(), and initObjects().
                                                                         :
   CCopasiProblem(src, pParent),
   mpDuration(NULL),
   mpStepSize(NULL),
   mpStepNumber(NULL),
   mpTimeSeriesRequested(NULL),
   mpOutputStartTime(NULL),
   mpOutputEvent(NULL),
   mpContinueSimultaneousEvents(NULL),
   mStepNumberSetLast(src.mStepNumberSetLast)
 {
   initializeParameter();
   initObjects();
   CONSTRUCTOR_TRACE;
 }
CTrajectoryProblem::~CTrajectoryProblem ()
Destructor.
Definition at line 77 of file CTrajectoryProblem.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
bool CTrajectoryProblem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 98 of file CTrajectoryProblem.cpp.
References C_FLOAT64, mpDuration, mpStepNumber, mpStepSize, and setDuration().
 {
   // If we have an old COPASI file "Duration" is not set
   // but we can fix that.
   if (*mpDuration == 1.0) // the default
     setDuration(*mpStepSize * (C_FLOAT64) *mpStepNumber);
   return true;
 }
const bool & CTrajectoryProblem::getContinueSimultaneousEvents () const
Retrieve whether to continue on simultaneous events.
Returns
const bool & continueSimultaneousEvents
Definition at line 210 of file CTrajectoryProblem.cpp.
References mpContinueSimultaneousEvents.
Referenced by CTrajectoryTask::initialize(), CQTrajectoryWidget::loadTask(), and CQTrajectoryWidget::saveTask().
 {
   return *mpContinueSimultaneousEvents;
 }
const C_FLOAT64 & CTrajectoryProblem::getDuration () const
Retrieve the end time.
Returns
"const C_FLOAT64 &" duration
Definition at line 178 of file CTrajectoryProblem.cpp.
References mpDuration.
Referenced by CODEExporterBM::exportTitleData(), CODEExporterXPPAUT::exportTitleData(), CTauLeapMethod::isValidProblem(), CHybridMethod::isValidProblem(), CHybridMethodODE45::isValidProblem(), CHybridMethodLSODA::isValidProblem(), CStochDirectMethod::isValidProblem(), CTrajAdaptiveSA::isValidProblem(), CStochMethod::isValidProblem(), CTrajectoryMethodDsaLsodar::isValidProblem(), CQTrajectoryWidget::loadTask(), CTrajectoryTask::process(), CCrossSectionTask::process(), and CQTrajectoryWidget::saveTask().
 {return *mpDuration;}
const bool & CTrajectoryProblem::getOutputEvent () const
Retrieve whether to do additional output for events.
Definition at line 202 of file CTrajectoryProblem.cpp.
References mpOutputEvent.
Referenced by CQTrajectoryWidget::loadTask(), CTrajectoryTask::processStep(), and CQTrajectoryWidget::saveTask().
 {return *mpOutputEvent;}
const C_FLOAT64 & CTrajectoryProblem::getOutputStartTime () const
Retrieve the end time.
Returns
"const C_FLOAT64 &" endTime
Definition at line 186 of file CTrajectoryProblem.cpp.
References mpOutputStartTime.
Referenced by CSEDMLExporter::createTimeCourseTask(), CODEExporter::exportExpression(), CQCrossSectionTaskWidget::loadTask(), CQTrajectoryWidget::loadTask(), CTrajectoryTask::process(), CCrossSectionTask::process(), CQTrajectoryWidget::saveTask(), and CQCrossSectionTaskWidget::updateValues().
 {return *mpOutputStartTime;}
const unsigned C_INT32 & CTrajectoryProblem::getStepNumber () const
Retrieve the number of time steps the trajectory method should integrate.
Returns
"const unsigned C_INT32 &" stepNumber
Definition at line 138 of file CTrajectoryProblem.cpp.
References mpStepNumber.
Referenced by CSEDMLExporter::createTimeCourseTask(), CTrajectoryTask::initialize(), CQTrajectoryWidget::loadTask(), CQTrajectoryWidget::saveTask(), CQTrajectoryWidget::slotDuration(), and CQTrajectoryWidget::slotIntervalSize().
 {return *mpStepNumber;}
const C_FLOAT64 & CTrajectoryProblem::getStepSize () const
Retrieve the size a integration step the trajectory method should do.
Returns
"const C_FLOAT64 &" stepSize
Definition at line 158 of file CTrajectoryProblem.cpp.
References mpStepSize.
Referenced by CSEDMLExporter::createTimeCourseTask(), CODEExporterBM::exportTitleData(), CODEExporterXPPAUT::exportTitleData(), CQTrajectoryWidget::loadTask(), CTrajectoryTask::process(), CQTrajectoryWidget::saveTask(), CQTrajectoryWidget::slotDuration(), CQTrajectoryWidget::slotIntervals(), and CQTrajectoryWidget::slotIntervalSize().
 {return *mpStepSize;}
void CTrajectoryProblem::initializeParameter () private
Initialize the method parameter
Definition at line 80 of file CTrajectoryProblem.cpp.
References CCopasiParameterGroup::assertParameter(), CCopasiParameter::BOOL, C_FLOAT64, C_INT32, CCopasiParameter::DOUBLE, CCopasiParameter::getValue(), mpContinueSimultaneousEvents, mpDuration, mpOutputEvent, mpOutputStartTime, mpStepNumber, mpStepSize, mpTimeSeriesRequested, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pUINT, and CCopasiParameter::UINT.
Referenced by CTrajectoryProblem().
 {
   mpStepNumber =
     assertParameter("StepNumber", CCopasiParameter::UINT, (unsigned C_INT32) 100)->getValue().pUINT;
   mpStepSize =
     assertParameter("StepSize", CCopasiParameter::DOUBLE, (C_FLOAT64) 0.01)->getValue().pDOUBLE;;
   mpDuration =
     assertParameter("Duration", CCopasiParameter::DOUBLE, (C_FLOAT64) 1.0)->getValue().pDOUBLE;;
   mpTimeSeriesRequested =
     assertParameter("TimeSeriesRequested", CCopasiParameter::BOOL, (bool) true)->getValue().pBOOL;
   mpOutputStartTime =
     assertParameter("OutputStartTime", CCopasiParameter::DOUBLE, (C_FLOAT64) 0.0)->getValue().pDOUBLE;
   mpOutputEvent =
     assertParameter("Output Event", CCopasiParameter::BOOL, (bool) false)->getValue().pBOOL;
   mpContinueSimultaneousEvents =
     assertParameter("Continue on Simultaneous Events", CCopasiParameter::BOOL, (bool) false)->getValue().pBOOL;
 }
void CTrajectoryProblem::initObjects () private
Definition at line 108 of file CTrajectoryProblem.cpp.
References C_INT32, CCopasiParameterGroup::getParameter(), CCopasiParameter::getValueReference(), setDuration(), setStepNumber(), setStepSize(), and CCopasiObject::setUpdateMethod().
Referenced by CTrajectoryProblem().
 {
   getParameter("StepNumber")->getValueReference()
   ->setUpdateMethod(this,
                     (void (CTrajectoryProblem::*)(const C_INT32 &)) &CTrajectoryProblem::setStepNumber);
   getParameter("StepSize")->getValueReference()
   ->setUpdateMethod(this, &CTrajectoryProblem::setStepSize);
   getParameter("Duration")->getValueReference()
   ->setUpdateMethod(this, &CTrajectoryProblem::setDuration);
 }
void CTrajectoryProblem::load (CReadConfig & configBuffer, CReadConfig::Mode mode = CReadConfig::NEXT)
Load a trajectory problem
Parameters
CReadConfig & configBuffer
"CReadConfig::Mode mode (Default: CReadConfig::NEXT)
Load a trajectory problem
Parameters
CReadConfig & configBuffer
Definition at line 219 of file CTrajectoryProblem.cpp.
References CCopasiDataModel::getModel(), CCopasiObject::getObjectDataModel(), CReadConfig::getVariable(), CReadConfig::getVersion(), CReadConfig::LOOP, mpDuration, CCopasiProblem::mpModel, mpStepNumber, mStepNumberSetLast, and sync().
 {
   if (configBuffer.getVersion() < "4.0")
     {
       CCopasiDataModel* pDataModel = getObjectDataModel();
       assert(pDataModel != NULL);
       mpModel = pDataModel->getModel();
       configBuffer.getVariable("EndTime", "C_FLOAT64",
                                mpDuration,
                                CReadConfig::LOOP);
       configBuffer.getVariable("Points", "C_INT32",
                                mpStepNumber);
       mStepNumberSetLast = true;
       sync();
     }
 }
void CTrajectoryProblem::setContinueSimultaneousEvents (const bool & continueSimultaneousEvents)
Set whether to continue on simultaneous events
Parameters
const bool & continueSimultaneousEvents
Definition at line 205 of file CTrajectoryProblem.cpp.
References mpContinueSimultaneousEvents.
Referenced by CQTrajectoryWidget::saveTask(), and SEDMLImporter::updateCopasiTaskForSimulation().
 {
   *mpContinueSimultaneousEvents = continueSimultaneousEvents;
 }
void CTrajectoryProblem::setDuration (const C_FLOAT64 & duration)
Set the end time.
Parameters
const C_FLOAT64 & duration bool success
Definition at line 166 of file CTrajectoryProblem.cpp.
References mpDuration, and sync().
Referenced by CNewtonMethod::doIntegration(), elevateChildren(), initObjects(), CQTrajectoryWidget::saveTask(), CQTrajectoryWidget::slotDuration(), test000087::test_simulate_reaction_flux_reference_1(), and SEDMLImporter::updateCopasiTaskForSimulation().
 {
   *mpDuration = duration;
   sync();
   return;
 }
void CTrajectoryProblem::setOutputEvent (const bool & outputEvent)
Set whether to output events in addition to the normal steps
Parameters
const bool & outputEvent
Definition at line 197 of file CTrajectoryProblem.cpp.
References mpOutputEvent.
Referenced by CQTrajectoryWidget::saveTask().
 {
   *mpOutputEvent = outputEvent;
 }
void CTrajectoryProblem::setOutputStartTime (const C_FLOAT64 & endTime)
Set the end time.
Parameters
const C_FLOAT64 & endTime
Definition at line 181 of file CTrajectoryProblem.cpp.
References mpOutputStartTime.
Referenced by CQCrossSectionTaskWidget::commitInput(), CQCrossSectionTaskWidget::saveTask(), CQTrajectoryWidget::saveTask(), CQCrossSectionTaskWidget::slotOutputDelay(), and SEDMLImporter::updateCopasiTaskForSimulation().
 {
   *mpOutputStartTime = startTime;
 }
void CTrajectoryProblem::setStepNumber (const unsigned C_INT32 & stepNumber)
Set the number of time steps the trajectory method should integrate.
Parameters
const unsigned C_INT32 & stepNumber bool success
Set the number of time steps the trajectory method should integrate.
Parameters
const unsigned C_INT32 & stepNumber
Definition at line 125 of file CTrajectoryProblem.cpp.
References mpStepNumber, mStepNumberSetLast, and sync().
Referenced by CNewtonMethod::doIntegration(), CNewtonMethod::initialize(), initObjects(), CQTrajectoryWidget::saveTask(), CQTrajectoryWidget::slotIntervals(), test000087::test_simulate_reaction_flux_reference_1(), and SEDMLImporter::updateCopasiTaskForSimulation().
 {
   *mpStepNumber = stepNumber;
   mStepNumberSetLast = true;
   sync();
   return;
 }
void CTrajectoryProblem::setStepSize (const C_FLOAT64 & stepSize)
Set the size a integration step the trajectory method should do.
Parameters
const C_FLOAT64 & stepSize bool success
Set the size a integration step the trajectory method should do.
Parameters
const C_FLOAT64 & stepSize
Definition at line 145 of file CTrajectoryProblem.cpp.
References mpStepSize, mStepNumberSetLast, and sync().
Referenced by initObjects(), CQTrajectoryWidget::saveTask(), and CQTrajectoryWidget::slotIntervalSize().
 {
   *mpStepSize = stepSize;
   mStepNumberSetLast = false;
   sync();
   return;
 }
void CTrajectoryProblem::setTimeSeriesRequested (bool flag)
Definition at line 189 of file CTrajectoryProblem.cpp.
References mpTimeSeriesRequested.
Referenced by CQTrajectoryWidget::saveTask(), and test000087::test_simulate_reaction_flux_reference_1().
 {
   *mpTimeSeriesRequested = flag;
 }
bool CTrajectoryProblem::sync () private
This function synchronizes step size and number
Returns
bool success
This function synchronizes step size and number
Definition at line 241 of file CTrajectoryProblem.cpp.
References C_FLOAT64, C_INT32, MCTrajectoryProblem, min, mpDuration, mpStepNumber, mpStepSize, mStepNumberSetLast, and CCopasiMessage::WARNING.
Referenced by load(), setDuration(), setStepNumber(), and setStepSize().
 {
   bool success = true;
   if (fabs(*mpDuration) < std::numeric_limits< C_FLOAT64 >::min())
     return success;
   C_FLOAT64 Tmp = *mpDuration;
   C_FLOAT64 StepSize = *mpStepSize;
   C_FLOAT64 StepNumber = (C_FLOAT64) * mpStepNumber;
   if (mStepNumberSetLast)
     {
       StepSize = Tmp / (C_FLOAT64) * mpStepNumber;
       /* Assure that the step size is not to small for machine accuracy */
       if (fabs(StepSize) < 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() * fabs(*mpDuration))
         {
           CCopasiMessage(CCopasiMessage::WARNING,
                          MCTrajectoryProblem + 3, StepSize);
           StepSize = 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() * fabs(*mpDuration);
           /* Assure that the step size has the appropriate sign. */
           StepSize = (Tmp < 0.0) ? - fabs(StepSize) : fabs(StepSize);
           StepNumber = fabs(ceil(Tmp / StepSize));
         }
     }
   else
     {
       if (fabs(StepSize) < 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() * fabs(*mpDuration))
         {
           CCopasiMessage(CCopasiMessage::WARNING,
                          MCTrajectoryProblem + 3, StepSize);
           StepSize = 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() * fabs(*mpDuration);
           /* Assure that the step size has the appropriate sign. */
           StepSize = (Tmp < 0.0) ? - fabs(StepSize) : fabs(StepSize);
         }
       StepNumber = fabs(ceil(Tmp / StepSize));
       /* Protect against overflow */
       if ((C_FLOAT64) ULONG_MAX < StepNumber)
         {
           CCopasiMessage(CCopasiMessage::WARNING,
                          MCTrajectoryProblem + 2, StepNumber);
           StepNumber = (C_FLOAT64) ULONG_MAX;
           StepSize = Tmp / StepNumber;
         }
       /* Assure that the step size has the appropriate sign. */
       StepSize = (Tmp < 0.0) ? - fabs(StepSize) : fabs(StepSize);
     }
   *mpStepSize = StepSize;
   *mpStepNumber = (unsigned C_INT32) StepNumber;
   return success;
 }
bool CTrajectoryProblem::timeSeriesRequested () const
Definition at line 194 of file CTrajectoryProblem.cpp.
References mpTimeSeriesRequested.
Referenced by CTrajectoryTask::initialize(), CQTrajectoryWidget::loadTask(), and CQTrajectoryWidget::saveTask().
 {return *mpTimeSeriesRequested;}
Member Data Documentation
bool* CTrajectoryProblem::mpContinueSimultaneousEvents protected
Pointer to parameter value indicating whether to continue when simultaneous events are encountered
Definition at line 206 of file CTrajectoryProblem.h.
Referenced by getContinueSimultaneousEvents(), initializeParameter(), and setContinueSimultaneousEvents().
C_FLOAT64* CTrajectoryProblem::mpDuration protected
Pointer to parameter value for duration.
Definition at line 173 of file CTrajectoryProblem.h.
Referenced by elevateChildren(), getDuration(), CCrossSectionProblem::getTimeLimit(), initializeParameter(), load(), setDuration(), CCrossSectionProblem::setTimeLimit(), and sync().
bool* CTrajectoryProblem::mpOutputEvent protected
Pointer to parameter value indicating whether events should be added to the output
Definition at line 200 of file CTrajectoryProblem.h.
Referenced by getOutputEvent(), initializeParameter(), and setOutputEvent().
C_FLOAT64* CTrajectoryProblem::mpOutputStartTime protected
Pointer to parameter value for output start time
Definition at line 194 of file CTrajectoryProblem.h.
Referenced by getOutputStartTime(), initializeParameter(), and setOutputStartTime().
unsigned C_INT32* CTrajectoryProblem::mpStepNumber protected
Pointer to parameter value for step number
Definition at line 183 of file CTrajectoryProblem.h.
Referenced by elevateChildren(), getStepNumber(), initializeParameter(), load(), setStepNumber(), and sync().
C_FLOAT64* CTrajectoryProblem::mpStepSize protected
Pointer to parameter value for step size.
Definition at line 178 of file CTrajectoryProblem.h.
Referenced by elevateChildren(), getStepSize(), initializeParameter(), setStepSize(), and sync().
bool* CTrajectoryProblem::mpTimeSeriesRequested protected
Pointer to parameter value indicating whether a time series needs to be stored in memory
Definition at line 189 of file CTrajectoryProblem.h.
Referenced by initializeParameter(), setTimeSeriesRequested(), and timeSeriesRequested().
bool CTrajectoryProblem::mStepNumberSetLast protected
Indicate whether the step number or step size was set last.
Definition at line 211 of file CTrajectoryProblem.h.
Referenced by load(), setStepNumber(), setStepSize(), and sync().
The documentation for this class was generated from the following files:
CTrajectoryProblem.h
CTrajectoryProblem.cpp