COPASI API: CReportDefinition Class Reference
CReportDefinition Class Reference
#include <CReportDefinition.h>
Public Member Functions
void cleanup ()
CReportDefinition (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CReportDefinition (const CReportDefinition &src, const CCopasiContainer *pParent=NULL)
std::vector
< CRegisteredObjectName > * getBodyAddr ()
const std::string & getComment () const
std::vector
< CRegisteredObjectName > * getFooterAddr ()
std::vector
< CRegisteredObjectName > * getHeaderAddr ()
virtual const std::string & getKey () const
const unsigned C_INT32 & getPrecision () const
const CCopasiReportSeparator & getSeparator () const
std::vector
< CRegisteredObjectName > * getTableAddr ()
const CCopasiTask::Type & getTaskType () const
bool getTitle () const
bool isTable () const
bool preCompileTable (const std::vector< CCopasiContainer * > &listOfContainer=CCopasiContainer::EmptyList)
void setComment (const std::string &comment)
void setIsTable (bool table)
void setPrecision (const unsigned C_INT32 &precision)
void setSeparator (const CCopasiReportSeparator &Separator)
bool setTaskType (const CCopasiTask::Type &taskType)
void setTitle (bool title)
~CReportDefinition ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Member Functions
void addTableElement (const CCopasiObject *pObject)
Private Attributes
std::vector
< CRegisteredObjectName > mBodyVector
bool mbTitle
std::string mComment
std::vector
< CRegisteredObjectName > mFooterVector
std::vector
< CRegisteredObjectName > mHeaderVector
std::string mKey
unsigned C_INT32 mPrecision
CCopasiReportSeparator mSeparator
bool mTable
std::vector
< CRegisteredObjectName > mTableVector
CCopasiTask::Type mTaskType
Additional Inherited Members
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 40 of file CReportDefinition.h.
Constructor & Destructor Documentation
CReportDefinition::CReportDefinition (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor.
CReportDefinition class. This class describes the Report Definition
Created for Copasi by Mudita Singhal
Definition at line 44 of file CReportDefinition.cpp.
                                                                       :
     CCopasiObject(name, pParent, "ReportDefinition"),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Report", this)),
     mComment(""),
     mTaskType(CCopasiTask::timeCourse),
     mSeparator("\t"),
     mTable(true),
     mbTitle(true),
     mPrecision(6)
 {}
CReportDefinition::CReportDefinition (const CReportDefinition & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Definition at line 56 of file CReportDefinition.cpp.
                                                                       :
     CCopasiObject(src, pParent),
     mKey(CCopasiRootContainer::getKeyFactory()->add("Report", this)),
     mComment(src.mComment),
     mTaskType(src.mTaskType),
     mSeparator(src.mSeparator),
     mTable(src.mTable),
     mbTitle(src.mbTitle),
     mPrecision(src.mPrecision),
     mHeaderVector(src.mHeaderVector),
     mBodyVector(src.mBodyVector),
     mFooterVector(src.mFooterVector),
     mTableVector(src.mTableVector)
 {}
CReportDefinition::~CReportDefinition ()
Destructor.
Definition at line 72 of file CReportDefinition.cpp.
References cleanup().
 {cleanup();}
Member Function Documentation
void CReportDefinition::addTableElement (const CCopasiObject * pObject) private
This adds header and body entries for one table element (including separator if necessary)
Parameters
const CCopasiObject * pObject
Definition at line 160 of file CReportDefinition.cpp.
References CCopasiObject::getCN(), CCopasiObject::getObjectName(), CCopasiObject::getObjectParent(), mBodyVector, mbTitle, mHeaderVector, and mSeparator.
Referenced by preCompileTable().
 {
   bool isFirst = false;
   if ((mHeaderVector.size() == 0) && (mBodyVector.size() == 0))
     isFirst = true;
   CCopasiObjectName SeparatorCN(mSeparator.getCN());
   CCopasiObjectName Title;
   if (!pObject) return;
   // Add separator
   if (!isFirst)
     {
       if (mbTitle)
         mHeaderVector.push_back(SeparatorCN);
       mBodyVector.push_back(SeparatorCN);
     }
   // Determine column title
   if (pObject->getObjectParent())
     {
       Title = pObject->getCN() + ",Property=DisplayName";
     }
   else
     Title =
       CCopasiStaticString(pObject->getObjectName()).getCN();
   if (mbTitle)
     mHeaderVector.push_back(Title);
   mBodyVector.push_back(pObject->getCN());
   return;
 }
void CReportDefinition::cleanup ()
cleanup
Definition at line 75 of file CReportDefinition.cpp.
References CCopasiRootContainer::getKeyFactory(), mBodyVector, mFooterVector, mHeaderVector, mKey, mTableVector, and CKeyFactory::remove().
Referenced by ~CReportDefinition().
 {
   CCopasiRootContainer::getKeyFactory()->remove(mKey);
   mHeaderVector.clear();
   mBodyVector.clear();
   mFooterVector.clear();
   mTableVector.clear();
 }
std::vector< CRegisteredObjectName > * CReportDefinition::getBodyAddr ()
gets the body in the report tag
Definition at line 115 of file CReportDefinition.cpp.
References mBodyVector.
Referenced by CCopasiDataModel::addReport(), CReport::compile(), CSEDMLExporter::createDataGenerators(), CCopasiXMLParser::BodyElement::end(), CQReportDefinition::load(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQReportDefinition::save(), CCopasiXML::saveReportList(), and test000087::test_simulate_reaction_flux_reference_1().
 {return &mBodyVector;}
const std::string& CReportDefinition::getComment () const inline
Returns the comments in the report tag
Definition at line 92 of file CReportDefinition.h.
References mComment.
Referenced by CQNotes::load(), CQNotes::save(), and CCopasiXML::saveReportList().
       {
         return mComment;
       }
std::vector< CRegisteredObjectName > * CReportDefinition::getFooterAddr ()
gets the footer in the report tag
Definition at line 121 of file CReportDefinition.cpp.
References mFooterVector.
Referenced by CCopasiDataModel::addReport(), CReport::compile(), CCopasiXMLParser::FooterElement::end(), CQReportDefinition::load(), CQReportDefinition::save(), and CCopasiXML::saveReportList().
 {return &mFooterVector;}
std::vector< CRegisteredObjectName > * CReportDefinition::getHeaderAddr ()
gets the header in the report tag
Definition at line 118 of file CReportDefinition.cpp.
References mHeaderVector.
Referenced by CCopasiDataModel::addReport(), CReport::compile(), CSEDMLExporter::createDataGenerators(), CCopasiXMLParser::HeaderElement::end(), CQReportDefinition::load(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQReportDefinition::save(), CCopasiXML::saveReportList(), and test000087::test_simulate_reaction_flux_reference_1().
 {return &mHeaderVector;}
const std::string & CReportDefinition::getKey () const virtual
Reimplemented from CCopasiObject.
Definition at line 157 of file CReportDefinition.cpp.
References mKey.
Referenced by CQReportDefinition::btnCopyReportClicked(), CQReportDefinition::btnNewReportClicked(), CQReportDM::insertRows(), CQReportDM::removeRows(), CCopasiXML::saveReportList(), CCopasiXML::saveTaskList(), and CQReportDM::setData().
 {return mKey;}
const unsigned C_INT32 & CReportDefinition::getPrecision () const
Retrieve the precsion for floating point numbers;
Returns
const unsigned C_INT32 & precision
Definition at line 154 of file CReportDefinition.cpp.
References mPrecision.
Referenced by CQReportDefinition::load(), CReport::open(), and CCopasiXML::saveReportList().
 {return mPrecision;}
const CCopasiReportSeparator & CReportDefinition::getSeparator () const
Definition at line 136 of file CReportDefinition.cpp.
References mSeparator.
Referenced by CSEDMLExporter::createDataGenerators(), CQReportDefinition::load(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CCopasiXML::saveReportList(), and test000087::test_simulate_reaction_flux_reference_1().
 {return mSeparator;}
std::vector< CRegisteredObjectName > * CReportDefinition::getTableAddr ()
gets the footer in the report tag
Definition at line 124 of file CReportDefinition.cpp.
References mTableVector.
Referenced by CSEDMLExporter::createDataGenerators(), COutputAssistant::createTable(), CCopasiXMLParser::TableElement::end(), CQReportDefinition::load(), CQReportDefinition::save(), and CCopasiXML::saveReportList().
 {return &mTableVector;}
const CCopasiTask::Type & CReportDefinition::getTaskType () const
Definition at line 130 of file CReportDefinition.cpp.
References mTaskType.
Referenced by CQReportDefinition::load(), and CCopasiXML::saveReportList().
 {return mTaskType;}
bool CReportDefinition::getTitle () const
Definition at line 139 of file CReportDefinition.cpp.
References mbTitle.
Referenced by CQReportDefinition::load(), and CCopasiXML::saveReportList().
 {return mbTitle;}
bool CReportDefinition::isTable () const
Definition at line 145 of file CReportDefinition.cpp.
References mTable.
Referenced by CReport::compile(), CSEDMLExporter::createDataGenerators(), CQReportDefinition::load(), and CCopasiXML::saveReportList().
 {return mTable;}
bool CReportDefinition::preCompileTable (const std::vector< CCopasiContainer * > & listOfContainer = CCopasiContainer::EmptyList)
Convert the table list into a header and body list.
Parameters
const std::vector< CCopasiContainer * > & listOfContainer (default: CCopasiContainer::EmptyList)
Returns
bool success
Definition at line 84 of file CReportDefinition.cpp.
References addTableElement(), CCopasiObject::getObjectDataModel(), mBodyVector, MCCopasiTask, mFooterVector, mHeaderVector, mTableVector, CCopasiDataModel::ObjectFromName(), and CCopasiMessage::WARNING.
Referenced by CQReportDefinition::btnAdvancedClicked(), and CReport::compile().
 {
   bool success = true;
   mHeaderVector.clear();
   mBodyVector.clear();
   mFooterVector.clear();
   std::vector<CRegisteredObjectName>::const_iterator it = mTableVector.begin();
   std::vector<CRegisteredObjectName>::const_iterator end = mTableVector.end();
   CCopasiDataModel* pDataModel = getObjectDataModel();
   CCopasiObject * pObject;
   for (; it != end; ++it)
     {
       pObject = pDataModel->ObjectFromName(listOfContainer, *it);
       if (pObject != NULL)
         {
           addTableElement(pObject);
         }
       else
         {
           CCopasiMessage(CCopasiMessage::WARNING, MCCopasiTask + 6, it->c_str());
         }
     }
   return success;
 }
void CReportDefinition::setComment (const std::string & comment) inline
sets the comments in the report tag
Definition at line 100 of file CReportDefinition.h.
References mComment.
Referenced by CCopasiDataModel::addReport(), CReportDefinitionVector::createReportDefinition(), CCopasiXMLParser::ReportElement::end(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), and CQNotes::save().
     {
       mComment = comment;
     }
void CReportDefinition::setIsTable (bool table)
Definition at line 148 of file CReportDefinition.cpp.
References mTable.
Referenced by CCopasiDataModel::addReport(), CQReportDefinition::btnAdvancedClicked(), COutputAssistant::createTable(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQReportDefinition::save(), CCopasiXMLParser::ReportElement::start(), and test000087::test_simulate_reaction_flux_reference_1().
 {mTable = table;}
void CReportDefinition::setPrecision (const unsigned C_INT32 & precision)
Set the precsion for floating point numbers;
Parameters
const unsigned C_INT32 & precision
Definition at line 151 of file CReportDefinition.cpp.
References mPrecision.
Referenced by CQReportDefinition::save(), and CCopasiXMLParser::ReportElement::start().
 {mPrecision = precision;}
void CReportDefinition::setSeparator (const CCopasiReportSeparator & Separator)
Definition at line 133 of file CReportDefinition.cpp.
References mSeparator, and CCopasiObject::Separator.
Referenced by CCopasiDataModel::addReport(), COutputAssistant::createTable(), SEDMLImporter::readListOfPlotsFromSedMLOutput(), CQReportDefinition::save(), CCopasiXMLParser::ReportElement::start(), and test000087::test_simulate_reaction_flux_reference_1().
 {mSeparator = Separator;}
bool CReportDefinition::setTaskType (const CCopasiTask::Type & taskType)
Definition at line 127 of file CReportDefinition.cpp.
References mTaskType.
Referenced by CCopasiDataModel::addReport(), COutputAssistant::createTable(), CQReportDefinition::save(), CCopasiXMLParser::ReportElement::start(), and test000087::test_simulate_reaction_flux_reference_1().
 {mTaskType = taskType; return true;}
void CReportDefinition::setTitle (bool title)
Definition at line 142 of file CReportDefinition.cpp.
References mbTitle.
Referenced by CCopasiDataModel::addReport(), CQReportDefinition::save(), and CCopasiXMLParser::TableElement::start().
 {mbTitle = title;}
Member Data Documentation
std::vector<CRegisteredObjectName> CReportDefinition::mBodyVector private
Definition at line 49 of file CReportDefinition.h.
Referenced by addTableElement(), cleanup(), getBodyAddr(), and preCompileTable().
bool CReportDefinition::mbTitle private
Definition at line 55 of file CReportDefinition.h.
Referenced by addTableElement(), getTitle(), and setTitle().
std::string CReportDefinition::mComment private
Definition at line 45 of file CReportDefinition.h.
Referenced by getComment(), and setComment().
std::vector<CRegisteredObjectName> CReportDefinition::mFooterVector private
Definition at line 50 of file CReportDefinition.h.
Referenced by cleanup(), getFooterAddr(), and preCompileTable().
std::vector<CRegisteredObjectName> CReportDefinition::mHeaderVector private
Definition at line 48 of file CReportDefinition.h.
Referenced by addTableElement(), cleanup(), getHeaderAddr(), and preCompileTable().
std::string CReportDefinition::mKey private
Definition at line 44 of file CReportDefinition.h.
Referenced by cleanup(), and getKey().
unsigned C_INT32 CReportDefinition::mPrecision private
Definition at line 56 of file CReportDefinition.h.
Referenced by getPrecision(), and setPrecision().
CCopasiReportSeparator CReportDefinition::mSeparator private
Definition at line 53 of file CReportDefinition.h.
Referenced by addTableElement(), getSeparator(), and setSeparator().
bool CReportDefinition::mTable private
Definition at line 54 of file CReportDefinition.h.
Referenced by isTable(), and setIsTable().
std::vector<CRegisteredObjectName> CReportDefinition::mTableVector private
Definition at line 51 of file CReportDefinition.h.
Referenced by cleanup(), getTableAddr(), and preCompileTable().
CCopasiTask::Type CReportDefinition::mTaskType private
Definition at line 46 of file CReportDefinition.h.
Referenced by getTaskType(), and setTaskType().
The documentation for this class was generated from the following files:
CReportDefinition.h
CReportDefinition.cpp