COPASI API: CQSpeciesWidget Class Reference
CQSpeciesWidget Class Reference
#include <CQSpeciesWidget.h>
Public Member Functions
CQSpeciesWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual void setFramework (int framework)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQSpeciesWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
virtual void keyPressEvent (QKeyEvent *ev)
void refreshCompartments ()
Private Member Functions
void deleteSelectedSpecies ()
void updateDeleteBtns ()
Private Attributes
QStringList mCompartments
CQComboDelegate * mpCompartmentDelegate
CQSortFilterProxyModel * mpProxyModel
CQSpecieDM * mpSpecieDM
CQIndexComboDelegate * mpTypeDelegate
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 30 of file CQSpeciesWidget.h.
Constructor & Destructor Documentation
CQSpeciesWidget::CQSpeciesWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 30 of file CQSpeciesWidget.cpp.
References COL_COMPARTMENT, COL_ROW_NUMBER, COL_TYPE_SPECIES, dataChanged(), CQSpecieDM::getTypes(), mCompartments, mpCompartmentDelegate, mpProxyModel, mpSpecieDM, mpTypeDelegate, CopasiWidget::protectedNotify(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpSpecieDM = new CQSpecieDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpProxyModel->setSourceModel(mpSpecieDM);
   mpTblSpecies->setModel(mpProxyModel);
   //Setting values for Compartment comboBox
   mpCompartmentDelegate = new CQComboDelegate(&mCompartments, this);
   mpTblSpecies->setItemDelegateForColumn(COL_COMPARTMENT, mpCompartmentDelegate);
   //Setting values for Types comboBox
   mpTypeDelegate = new CQIndexComboDelegate(&mpSpecieDM->getTypes(), this);
   mpTblSpecies->setItemDelegateForColumn(COL_TYPE_SPECIES, mpTypeDelegate);
   mpTblSpecies->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblSpecies->verticalHeader()->hide();
   mpTblSpecies->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   // Connect the table widget
   connect(mpSpecieDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpSpecieDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
 }
CQSpeciesWidget::~CQSpeciesWidget ()
Definition at line 70 of file CQSpeciesWidget.cpp.
References mpCompartmentDelegate, mpProxyModel, mpSpecieDM, mpTypeDelegate, and pdelete.
 {
   pdelete(mpCompartmentDelegate);
   pdelete(mpTypeDelegate);
   pdelete(mpProxyModel);
   pdelete(mpSpecieDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQSpeciesWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 201 of file CQSpeciesWidget.cpp.
References CopasiWidget::mFramework, refreshCompartments(), setFramework(), and updateDeleteBtns().
Referenced by CQSpeciesWidget().
 {
   mpTblSpecies->resizeColumnsToContents();
   setFramework(mFramework);
   refreshCompartments();
   updateDeleteBtns();
 }
void CQSpeciesWidget::deleteSelectedSpecies () private
Definition at line 93 of file CQSpeciesWidget.cpp.
References mpProxyModel, mpSpecieDM, CQSpecieDM::removeRows(), and CQSpecieDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblSpecies->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpSpecieDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpSpecieDM->removeRows(mappedSelRows);
 }
bool CQSpeciesWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 143 of file CQSpeciesWidget.cpp.
References CopasiWidget::mFramework, mpProxyModel, mpSpecieDM, refreshCompartments(), setFramework(), slotSelectionChanged(), and updateDeleteBtns().
Referenced by update().
 {
   if (mpTblSpecies->selectionModel() != NULL)
     {
       disconnect(mpTblSpecies->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpProxyModel->setSourceModel(mpSpecieDM);
   //Set Model for the TableView
   mpTblSpecies->setModel(NULL);
   mpTblSpecies->setModel(mpProxyModel);
   connect(mpTblSpecies->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblSpecies->resizeColumnsToContents();
   setFramework(mFramework);
   refreshCompartments();
   return true;
 }
void CQSpeciesWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 236 of file CQSpeciesWidget.cpp.
References CQSpecieDM::columnCount(), mpProxyModel, mpSpecieDM, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C && (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblSpecies->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpSpecieDM->columnCount(); ++x)
             {
               if (!mpTblSpecies->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpSpecieDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQSpeciesWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 138 of file CQSpeciesWidget.cpp.
 {
   return true;
 }
void CQSpeciesWidget::refreshCompartments () protected
Definition at line 308 of file CQSpeciesWidget.cpp.
References C_INT32, FROM_UTF8, CCopasiRootContainer::getDatamodelList(), mCompartments, and CCopasiVector< T >::size().
Referenced by dataChanged(), and enterProtected().
 {
   const CCopasiVector < CCompartment > & compartments =
     (*CCopasiRootContainer::getDatamodelList())[0]->getModel()->getCompartments();
   mCompartments.clear();
   for (unsigned C_INT32 jj = 0; jj < compartments.size(); jj++)
     mCompartments.push_back(FROM_UTF8(compartments[jj]->getObjectName()));
 }
void CQSpeciesWidget::setFramework (int framework) virtual
Reimplemented from CopasiWidget.
Definition at line 276 of file CQSpeciesWidget.cpp.
References COL_CONCENTRATION, COL_CRATE, COL_ICONCENTRATION, COL_INUMBER, COL_NRATE, COL_NUMBER, CopasiWidget::mFramework, mpSpecieDM, CQSpecieDM::setFlagConc(), and CopasiWidget::setFramework().
Referenced by dataChanged(), and enterProtected().
 {
   CopasiWidget::setFramework(framework);
   switch (mFramework)
     {
       case 0:
         mpTblSpecies->showColumn(COL_ICONCENTRATION);
         mpTblSpecies->showColumn(COL_CONCENTRATION);
         mpTblSpecies->showColumn(COL_CRATE);
         mpTblSpecies->hideColumn(COL_INUMBER);
         mpTblSpecies->hideColumn(COL_NUMBER);
         mpTblSpecies->hideColumn(COL_NRATE);
         mpSpecieDM->setFlagConc(true);
         break;
       case 1:
         mpTblSpecies->hideColumn(COL_ICONCENTRATION);
         mpTblSpecies->hideColumn(COL_CONCENTRATION);
         mpTblSpecies->hideColumn(COL_CRATE);
         mpTblSpecies->showColumn(COL_INUMBER);
         mpTblSpecies->showColumn(COL_NUMBER);
         mpTblSpecies->showColumn(COL_NRATE);
         mpSpecieDM->setFlagConc(false);
         break;
     }
 }
void CQSpeciesWidget::slotBtnClearClicked () protected virtual slot
Definition at line 114 of file CQSpeciesWidget.cpp.
References CQBaseDataModel::clear(), mpSpecieDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Species?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpSpecieDM->clear();
     }
   updateDeleteBtns();
 }
void CQSpeciesWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 85 of file CQSpeciesWidget.cpp.
References deleteSelectedSpecies(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblSpecies->hasFocus())
     {deleteSelectedSpecies();}
   updateDeleteBtns();
 }
void CQSpeciesWidget::slotBtnNewClicked () protected virtual slot
Definition at line 79 of file CQSpeciesWidget.cpp.
References CQBaseDataModel::insertRow(), mpSpecieDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpSpecieDM->insertRow();
   updateDeleteBtns();
 }
void CQSpeciesWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 210 of file CQSpeciesWidget.cpp.
References C_INVALID_INDEX, CCopasiRootContainer::getDatamodelList(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CModel::getMetabolites(), CCopasiDataModel::getModel(), CQBaseDataModel::isDefaultRow(), CopasiWidget::mpListView, mpProxyModel, mpSpecieDM, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpSpecieDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   CCopasiDataModel* pDataModel = (*CCopasiRootContainer::getDatamodelList())[0];
   assert(pDataModel != NULL);
   CModel * pModel = pDataModel->getModel();
   if (pModel == NULL)
     return;
   std::string key = pModel->getMetabolites()[index.row()]->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQSpeciesWidget::slotFilterChanged () protected virtual slot
Definition at line 270 of file CQSpeciesWidget.cpp.
References mpProxyModel.
Referenced by CQSpeciesWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Species", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQSpeciesWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 195 of file CQSpeciesWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQSpeciesWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 128 of file CQSpeciesWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQSpeciesWidget::updateDeleteBtns () private
Definition at line 166 of file CQSpeciesWidget.cpp.
References CQBaseDataModel::isDefaultRow(), mpProxyModel, and mpSpecieDM.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblSpecies->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpSpecieDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
QStringList CQSpeciesWidget::mCompartments private
Definition at line 45 of file CQSpeciesWidget.h.
Referenced by CQSpeciesWidget(), and refreshCompartments().
CQComboDelegate* CQSpeciesWidget::mpCompartmentDelegate private
Definition at line 46 of file CQSpeciesWidget.h.
Referenced by CQSpeciesWidget(), and ~CQSpeciesWidget().
CQSortFilterProxyModel* CQSpeciesWidget::mpProxyModel private
Definition at line 44 of file CQSpeciesWidget.h.
Referenced by CQSpeciesWidget(), deleteSelectedSpecies(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQSpeciesWidget().
CQSpecieDM* CQSpeciesWidget::mpSpecieDM private
Definition at line 43 of file CQSpeciesWidget.h.
Referenced by CQSpeciesWidget(), deleteSelectedSpecies(), enterProtected(), keyPressEvent(), setFramework(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQSpeciesWidget().
CQIndexComboDelegate* CQSpeciesWidget::mpTypeDelegate private
Definition at line 47 of file CQSpeciesWidget.h.
Referenced by CQSpeciesWidget(), and ~CQSpeciesWidget().
The documentation for this class was generated from the following files:
CQSpeciesWidget.h
CQSpeciesWidget.cpp