COPASI API: CLEllipse Class Reference
CLEllipse Class Reference
#include <CLEllipse.h>
Public Member Functions
CLEllipse (CCopasiContainer *pParent=NULL)
CLEllipse (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &r, CCopasiContainer *pParent=NULL)
CLEllipse (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &rx, const CLRelAbsVector &ry, CCopasiContainer *pParent=NULL)
CLEllipse (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &cz, const CLRelAbsVector &rx, const CLRelAbsVector &ry, CCopasiContainer *pParent=NULL)
CLEllipse (const CLEllipse &source, CCopasiContainer *pParent=NULL)
CLEllipse (const sbmlEllipse &source, CCopasiContainer *pParent=NULL)
const CLRelAbsVector & getCX () const
CLRelAbsVector & getCX ()
const CLRelAbsVector & getCY () const
CLRelAbsVector & getCY ()
const CLRelAbsVector & getCZ () const
CLRelAbsVector & getCZ ()
const std::string & getKey () const
const CLRelAbsVector & getRX () const
CLRelAbsVector & getRX ()
const CLRelAbsVector & getRY () const
CLRelAbsVector & getRY ()
void setCenter2D (const CLRelAbsVector &cx, const CLRelAbsVector &cy)
void setCenter3D (const CLRelAbsVector &cx, const CLRelAbsVector &cy, const CLRelAbsVector &cz)
void setCX (const CLRelAbsVector &cx)
void setCY (const CLRelAbsVector &cy)
void setCZ (const CLRelAbsVector &cz)
void setRadii (const CLRelAbsVector &rx, const CLRelAbsVector &ry)
void setRX (const CLRelAbsVector &rx)
void setRY (const CLRelAbsVector &ry)
sbmlEllipse * toSBML (unsigned int level, unsigned int version) const
~CLEllipse ()
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
virtual std::string getUnits () const
UpdateMethod * getUpdateMethod () const
virtual const CCopasiObject * getValueObject () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CLRelAbsVector mCX
CLRelAbsVector mCY
CLRelAbsVector mCZ
std::string mKey
CLRelAbsVector mRX
CLRelAbsVector mRY
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Private Member Functions
CLEllipse & operator= (const CLEllipse &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET, NONZERO, EVENODD, INHERIT }
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 26 of file CLEllipse.h.
Constructor & Destructor Documentation
CLEllipse::CLEllipse (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 27 of file CLEllipse.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and setRadii().
                                              :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Ellipse", pParent),
     mCX(0.0),
     mCY(0.0),
     mCZ(0.0),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Ellipse", this);
   setRadii(0.0, 0.0);
 }
CLEllipse::CLEllipse (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & r, CCopasiContainer * pParent = NULL)
Constructor with 2D center and radius.
Definition at line 42 of file CLEllipse.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and setRadii().
                                                                                                                           :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Ellipse", pParent),
     mCX(cx),
     mCY(cy),
     mCZ(0.0),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Ellipse", this);
   setRadii(r, r);
 }
CLEllipse::CLEllipse (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & rx, const CLRelAbsVector & ry, CCopasiContainer * pParent = NULL)
Constructor with 2D center and radii.
Definition at line 57 of file CLEllipse.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and setRadii().
                                                                                                                                                      :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Ellipse", pParent),
     mCX(cx),
     mCY(cy),
     mCZ(CLRelAbsVector(0.0, 50.0)),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Ellipse", this);
   setRadii(rx, ry);
 }
CLEllipse::CLEllipse (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & cz, const CLRelAbsVector & rx, const CLRelAbsVector & ry, CCopasiContainer * pParent = NULL)
Constructor with 3D center and radii.
Definition at line 72 of file CLEllipse.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and setRadii().
                                                                                                                                                                                :
     CLGraphicalPrimitive2D(),
     CCopasiObject("Ellipse", pParent),
     mCX(cx),
     mCY(cy),
     mCZ(cz),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Ellipse", this);
   setRadii(rx, ry);
 }
CLEllipse::CLEllipse (const CLEllipse & source, CCopasiContainer * pParent = NULL)
Copy Constructor
Definition at line 87 of file CLEllipse.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                                       :
     CLGraphicalPrimitive2D(source),
     CCopasiObject(source, pParent),
     mCX(source.mCX),
     mCY(source.mCY),
     mCZ(source.mCZ),
     mRX(source.mRX),
     mRY(source.mRY),
     mKey("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("Ellipse", this);
 }
CLEllipse::CLEllipse (const sbmlEllipse & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
CLEllipse::~CLEllipse ()
Destructor.
Destructor
Definition at line 119 of file CLEllipse.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {
   CCopasiRootContainer::getKeyFactory()->remove(this->mKey);
 }
Member Function Documentation
const CLRelAbsVector & CLEllipse::getCX () const
Returns the x component of the center.
Definition at line 127 of file CLEllipse.cpp.
References mCX.
Referenced by CLLayoutRenderer::draw_ellipse(), fillItemFromEllipse(), getPath(), CCopasiXML::saveEllipseElement(), and toSBML().
 {
   return this->mCX;
 }
CLRelAbsVector & CLEllipse::getCX ()
Returns the x component of the center.
Definition at line 167 of file CLEllipse.cpp.
References mCX.
 {
   return this->mCX;
 }
const CLRelAbsVector & CLEllipse::getCY () const
Returns the y component of the center.
Definition at line 135 of file CLEllipse.cpp.
References mCY.
Referenced by CLLayoutRenderer::draw_ellipse(), fillItemFromEllipse(), getPath(), CCopasiXML::saveEllipseElement(), and toSBML().
 {
   return this->mCY;
 }
CLRelAbsVector & CLEllipse::getCY ()
Returns the y component of the center.
Definition at line 175 of file CLEllipse.cpp.
References mCY.
 {
   return this->mCY;
 }
const CLRelAbsVector & CLEllipse::getCZ () const
Returns the z component of the center.
Definition at line 143 of file CLEllipse.cpp.
References mCZ.
Referenced by CLLayoutRenderer::draw_ellipse(), CCopasiXML::saveEllipseElement(), and toSBML().
 {
   return this->mCZ;
 }
CLRelAbsVector & CLEllipse::getCZ ()
Returns the z component of the center.
Definition at line 183 of file CLEllipse.cpp.
References mCZ.
 {
   return this->mCZ;
 }
const std::string & CLEllipse::getKey () const virtual
Returns the key string of the object.
Returns the key of the render information
Reimplemented from CCopasiObject.
Definition at line 276 of file CLEllipse.cpp.
References mKey.
 {
   return this->mKey;
 }
const CLRelAbsVector & CLEllipse::getRX () const
Returns the radius along the x axis.
Definition at line 151 of file CLEllipse.cpp.
References mRX.
Referenced by CLLayoutRenderer::draw_ellipse(), fillItemFromEllipse(), getPath(), CCopasiXML::saveEllipseElement(), and toSBML().
 {
   return this->mRX;
 }
CLRelAbsVector & CLEllipse::getRX ()
Returns the radius along the x axis.
Definition at line 191 of file CLEllipse.cpp.
References mRX.
 {
   return this->mRX;
 }
const CLRelAbsVector & CLEllipse::getRY () const
Returns the radius along the y axis.
Definition at line 159 of file CLEllipse.cpp.
References mRY.
Referenced by CLLayoutRenderer::draw_ellipse(), fillItemFromEllipse(), getPath(), CCopasiXML::saveEllipseElement(), and toSBML().
 {
   return this->mRY;
 }
CLRelAbsVector & CLEllipse::getRY ()
Returns the radius along the y axis.
Definition at line 199 of file CLEllipse.cpp.
References mRY.
 {
   return this->mRY;
 }
CLEllipse& CLEllipse::operator= (const CLEllipse & source) private
void CLEllipse::setCenter2D (const CLRelAbsVector & cx, const CLRelAbsVector & cy)
Sets the 2D center.
Definition at line 247 of file CLEllipse.cpp.
References mCX, mCY, and mCZ.
 {
   this->mCX = cx;
   this->mCY = cy;
   this->mCZ = CLRelAbsVector(0.0, 50.0);
 }
void CLEllipse::setCenter3D (const CLRelAbsVector & cx, const CLRelAbsVector & cy, const CLRelAbsVector & cz)
Sets the 3D center.
Definition at line 257 of file CLEllipse.cpp.
References mCX, mCY, and mCZ.
Referenced by CCopasiXMLParser::EllipseElement::start().
 {
   this->mCX = cx;
   this->mCY = cy;
   this->mCZ = cz;
 }
void CLEllipse::setCX (const CLRelAbsVector & cx)
Sets the x component of the center.
Definition at line 207 of file CLEllipse.cpp.
References mCX.
 {
   this->mCX = cx;
 }
void CLEllipse::setCY (const CLRelAbsVector & cy)
Sets the y component of the center.
Definition at line 215 of file CLEllipse.cpp.
References mCY.
 {
   this->mCY = cy;
 }
void CLEllipse::setCZ (const CLRelAbsVector & cz)
Sets the z component of the center.
Definition at line 223 of file CLEllipse.cpp.
References mCZ.
 {
   this->mCZ = cz;
 }
void CLEllipse::setRadii (const CLRelAbsVector & rx, const CLRelAbsVector & ry)
Sets the radii.
Definition at line 267 of file CLEllipse.cpp.
References mRX, and mRY.
Referenced by CLEllipse(), and CCopasiXMLParser::EllipseElement::start().
 {
   this->mRX = rx;
   this->mRY = ry;
 }
void CLEllipse::setRX (const CLRelAbsVector & rx)
Sets the radius along the x axis.
Definition at line 231 of file CLEllipse.cpp.
References mRX.
 {
   this->mRX = rx;
 }
void CLEllipse::setRY (const CLRelAbsVector & ry)
Sets the radius along the y axis.
Definition at line 239 of file CLEllipse.cpp.
References mRY.
 {
   this->mRY = ry;
 }
Ellipse * CLEllipse::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
Definition at line 284 of file CLEllipse.cpp.
References CLGraphicalPrimitive2D::addSBMLAttributes(), getCX(), getCY(), getCZ(), getRX(), getRY(), and CLRelAbsVector::toSBML().
 {
   Ellipse* pE = new Ellipse(level, version);
   this->addSBMLAttributes(pE);
   RelAbsVector* pV = this->getCX().toSBML();
   pE->setCX(*pV);
   delete pV;
   pV = this->getCY().toSBML();
   pE->setCY(*pV);
   delete pV;
   pV = this->getCZ().toSBML();
   pE->setCZ(*pV);
   delete pV;
   pV = this->getRX().toSBML();
   pE->setRX(*pV);
   delete pV;
   pV = this->getRY().toSBML();
   pE->setRY(*pV);
   delete pV;
   return pE;
 }
Member Data Documentation
CLRelAbsVector CLEllipse::mCX protected
Definition at line 33 of file CLEllipse.h.
Referenced by getCX(), setCenter2D(), setCenter3D(), and setCX().
CLRelAbsVector CLEllipse::mCY protected
Definition at line 34 of file CLEllipse.h.
Referenced by getCY(), setCenter2D(), setCenter3D(), and setCY().
CLRelAbsVector CLEllipse::mCZ protected
Definition at line 35 of file CLEllipse.h.
Referenced by getCZ(), setCenter2D(), setCenter3D(), and setCZ().
std::string CLEllipse::mKey protected
key for the object.
Definition at line 42 of file CLEllipse.h.
Referenced by CLEllipse(), getKey(), and ~CLEllipse().
CLRelAbsVector CLEllipse::mRX protected
Definition at line 36 of file CLEllipse.h.
Referenced by getRX(), setRadii(), and setRX().
CLRelAbsVector CLEllipse::mRY protected
Definition at line 37 of file CLEllipse.h.
Referenced by getRY(), setRadii(), and setRY().
The documentation for this class was generated from the following files:
CLEllipse.h
CLEllipse.cpp