COPASI API: CModelParameterSpecies Class Reference
CModelParameterSpecies Class Reference
#include <CModelParameter.h>
Public Member Functions
CModelParameterSpecies (CModelParameterGroup *pParent, const CModelParameter::Type &type=CModelParameter::Species)
CModelParameterSpecies (const CModelParameterSpecies &src, CModelParameterGroup *pParent)
virtual void compile ()
virtual std::string getName () const
virtual const C_FLOAT64 & getValue (const Framework &framework) const
virtual void setCN (const CCopasiObjectName &cn)
virtual void setValue (const C_FLOAT64 &value, const Framework &framework)
virtual ~CModelParameterSpecies ()
Public Member Functions inherited from CModelParameter
CModelParameter (CModelParameterGroup *pParent, const CModelParameter::Type &type)
CModelParameter (const CModelParameter &src, CModelParameterGroup *pParent)
virtual const CompareResult & diff (const CModelParameter &other, const CModelParameter::Framework &framework=ParticleNumbers, const bool &createMissing=false)
virtual const CModelParameter * getChild (const size_t &index) const
const CCopasiObjectName & getCN () const
const CompareResult & getCompareResult () const
size_t getIndex () const
std::string getInitialExpression () const
const CExpression * getInitialExpressionPtr () const
CModel * getModel () const
virtual size_t getNumChildren () const
CCopasiObject * getObject () const
CModelParameterGroup * getParent () const
CModelParameterSet * getSet () const
const CModelEntity::Status & getSimulationType () const
const Type & getType () const
const std::string getUnit (const Framework &framework) const
bool isInitialExpressionValid () const
bool isReadOnly () const
virtual bool refreshFromModel (const bool &modifyExistence)
void setCompareResult (const CompareResult &compareResult)
void setInitialExpression (const std::string &initialExpression)
void setParent (CModelParameterGroup *pParent)
bool setSimulationType (const CModelEntity::Status &simulationType)
virtual void setValue (const double &value, const Framework &framework)
virtual bool updateModel ()
virtual ~CModelParameter ()
Private Member Functions
friend CModelParameterCompartment::~CModelParameterCompartment ()
CCopasiObjectName getCompartmentCN () const
Private Attributes
CRegisteredObjectName mCompartmentCN
C_FLOAT64 mConcentration
CModelParameterCompartment * mpCompartment
Additional Inherited Members
Public Types inherited from CModelParameter
enum CompareResult {
Obsolete, Missing, Modified, Conflict,
Identical
}
enum Framework { Concentration = 0, ParticleNumbers }
enum Type {
Model, Compartment, Species, ModelValue,
ReactionParameter, Reaction, Group, Set,
unknown
}
Static Public Attributes inherited from CModelParameter
static const char * TypeNames []
Static Protected Member Functions inherited from CModelParameter
static std::string nameFromCN (const CCopasiObjectName &cn)
Protected Attributes inherited from CModelParameter
CRegisteredObjectName mCN
CompareResult mCompareResult
bool mIsInitialExpressionValid
CExpression * mpInitialExpression
CCopasiObject * mpObject
CModelParameterGroup * mpParent
CModelEntity::Status mSimulationType
Type mType
double mValue
Detailed Description
Definition at line 353 of file CModelParameter.h.
Constructor & Destructor Documentation
CModelParameterSpecies::CModelParameterCompartment::~CModelParameterCompartment () private
CModelParameterSpecies::CModelParameterSpecies (CModelParameterGroup * pParent, const CModelParameter::Type & type = CModelParameter::Species)
Constructor
Definition at line 737 of file CModelParameter.cpp.
                                                                                                               :
   CModelParameter(pParent, type),
   mCompartmentCN(),
   mpCompartment(NULL),
   mConcentration(std::numeric_limits< C_FLOAT64 >::quiet_NaN())
 {}
CModelParameterSpecies::CModelParameterSpecies (const CModelParameterSpecies & src, CModelParameterGroup * pParent)
Copy constructor
Definition at line 744 of file CModelParameter.cpp.
                                                                                                                 :
   CModelParameter(src, pParent),
   mCompartmentCN(src.mCompartmentCN),
   mpCompartment(NULL),
   mConcentration(src.mConcentration)
 {}
CModelParameterSpecies::~CModelParameterSpecies () virtual
Destructor
Definition at line 752 of file CModelParameter.cpp.
References mpCompartment, and CModelParameterCompartment::removeSpecies().
 {
   if (mpCompartment != NULL)
     {
       mpCompartment->removeSpecies(this);
     }
 }
Member Function Documentation
void CModelParameterSpecies::compile () virtual
Compile the parameter
Reimplemented from CModelParameter.
Definition at line 774 of file CModelParameter.cpp.
References CModelParameterCompartment::addSpecies(), CModelParameter::compile(), CModelParameterGroup::getModelParameter(), CModelParameter::getSet(), mCompartmentCN, mpCompartment, CModelParameter::mValue, CModelParameter::ParticleNumbers, and setValue().
 {
   CModelParameter::compile();
   mpCompartment = static_cast< CModelParameterCompartment * >(getSet()->getModelParameter(mCompartmentCN));
   if (mpCompartment != NULL)
     {
       mpCompartment->addSpecies(this);
     }
   // Update the concentration if possible
   setValue(mValue, ParticleNumbers);
 }
CCopasiObjectName CModelParameterSpecies::getCompartmentCN () const private
Retrieve the CN of the compartment the species is contained in.
Returns
CCopasiObjectName compartmentCN
Definition at line 857 of file CModelParameter.cpp.
References mCompartmentCN.
 {
   return mCompartmentCN;
 }
std::string CModelParameterSpecies::getName () const virtual
Retrieve the name.
Returns
std::string name
Reimplemented from CModelParameter.
Definition at line 761 of file CModelParameter.cpp.
References CMetabNameInterface::getDisplayName(), CModelParameterSet::getModel(), CModelParameter::getSet(), CModelParameter::mCN, mCompartmentCN, CModelParameter::mpObject, and CModelParameter::nameFromCN().
 {
   CModel * pModel = getSet()->getModel();
   if (mpObject != NULL)
     {
       return CMetabNameInterface::getDisplayName(pModel, *static_cast< CMetab * >(mpObject), false);
     }
   return nameFromCN(mCN) + '{' + nameFromCN(mCompartmentCN) + '}';
 }
const C_FLOAT64 & CModelParameterSpecies::getValue (const Framework & framework) const virtual
Retrieve the value of the parameter based on the current framework
Parameters
const Framework & framework
Returns
const double & value
Reimplemented from CModelParameter.
Definition at line 847 of file CModelParameter.cpp.
References CModelParameter::Concentration, mConcentration, and CModelParameter::mValue.
 {
   if (framework == Concentration)
     {
       return mConcentration;
     }
   return mValue;
 }
void CModelParameterSpecies::setCN (const CCopasiObjectName & cn) virtual
Set the CN of the object represented by the parameter
Parameters
const CCopasiObjectName & cn
Reimplemented from CModelParameter.
Definition at line 790 of file CModelParameter.cpp.
References CCopasiObjectName::getPrimary(), CCopasiObjectName::getRemainder(), CModelParameter::mCN, mCompartmentCN, and CModelParameter::setCN().
 {
   CModelParameter::setCN(cn);
   // Determine the CN for the compartment.
   // "CN=Root,Model=New Model,Vector=Compartments[compartment],Vector=Metabolites[A]"
   CCopasiObjectName Tmp = mCN;
   std::string Separator = "";
   for (; Tmp != ""; Tmp = Tmp.getRemainder())
     {
       CCopasiObjectName Primary = Tmp.getPrimary();
       mCompartmentCN += Separator + Primary;
       Separator = ",";
       if (Primary.getObjectType() == "Vector" &&
           Primary.getObjectName() == "Compartments")
         {
           break;
         }
     }
 }
void CModelParameterSpecies::setValue (const C_FLOAT64 & value, const Framework & framework) virtual
Set the value of the parameter based on the current framework
Parameters
const double & value
const Framework & framework
Definition at line 814 of file CModelParameter.cpp.
References CModelParameter::Concentration, CModelParameter::getModel(), CModel::getNumber2QuantityFactor(), CModel::getQuantity2NumberFactor(), CModelParameter::getValue(), mConcentration, mpCompartment, CModelParameter::mValue, and CModelParameter::ParticleNumbers.
Referenced by compile().
 {
   CModel * pModel = getModel();
   if (framework == Concentration)
     {
       mConcentration = value;
       if (mpCompartment != NULL && pModel != NULL)
         {
           mValue = mConcentration * mpCompartment->getValue(ParticleNumbers) * pModel->getQuantity2NumberFactor();
         }
       else
         {
           mValue = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
         }
     }
   else
     {
       mValue = value;
       if (mpCompartment != NULL && pModel != NULL)
         {
           mConcentration = mValue / mpCompartment->getValue(ParticleNumbers) * pModel->getNumber2QuantityFactor();
         }
       else
         {
           mConcentration = std::numeric_limits< C_FLOAT64 >::quiet_NaN();
         }
     }
 }
Member Data Documentation
CRegisteredObjectName CModelParameterSpecies::mCompartmentCN private
The CN of the compartment the species is contained in.
Definition at line 415 of file CModelParameter.h.
Referenced by compile(), getCompartmentCN(), getName(), and setCN().
C_FLOAT64 CModelParameterSpecies::mConcentration private
The concentration value of the species.
Definition at line 425 of file CModelParameter.h.
Referenced by getValue(), and setValue().
CModelParameterCompartment* CModelParameterSpecies::mpCompartment private
A pointer to the parameter representing the compartment the species is contained in.
Definition at line 420 of file CModelParameter.h.
Referenced by compile(), setValue(), and ~CModelParameterSpecies().
The documentation for this class was generated from the following files:
CModelParameter.h
CModelParameter.cpp