COPASI API: CQTSSAWidget Class Reference
CQTSSAWidget Class Reference
#include <CQTSSAWidget.h>
Public Slots
void slotDuration ()
void slotIntervals ()
void slotIntervalSize ()
Public Slots inherited from TaskWidget
void adjustTable ()
void slotFinishThread ()
Public Member Functions
CQTSSAWidget (QWidget *parent=0, const char *name=0)
virtual bool runTask ()
~CQTSSAWidget ()
Public Member Functions inherited from TaskWidget
CCopasiTask * getTask ()
virtual bool leave ()
TaskWidget (QWidget *parent=0, const char *name=0, Qt::WFlags fl=0)
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~TaskWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Member Functions
virtual CCopasiMethod * createMethod (const CCopasiMethod::SubType &type)
virtual bool loadTask ()
virtual bool saveTask ()
virtual bool taskFinishedEvent ()
Protected Member Functions inherited from TaskWidget
bool commonAfterRunTask ()
bool commonBeforeRunTask ()
bool commonRunTask ()
virtual bool enterProtected ()
void finishTask ()
bool loadCommon ()
bool loadMethod ()
bool saveCommon ()
bool saveMethod ()
Private Member Functions
void destroy ()
void init ()
Private Attributes
CTSSAProblem * mpTSSAProblem
CQValidatorDouble * mpValidatorDelay
CQValidatorDouble * mpValidatorDuration
CQValidatorInt * mpValidatorIntervals
CQValidatorDouble * mpValidatorIntervalSize
Additional Inherited Members
Protected Slots inherited from TaskWidget
void assistantBtnClicked ()
void reportBtnClicked ()
void revertBtnClicked ()
void runBtnClicked ()
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Attributes inherited from TaskWidget
bool mChanged
CQTaskBtnWidget * mpBtnWidget
CQTaskHeaderWidget * mpHeaderWidget
CCopasiMethod * mpMethod
QGridLayout * mpMethodLayout
CQTaskMethodWidget * mpMethodWidget
CProgressBar * mProgressBar
QSpacerItem * mpSpacer1
QSpacerItem * mpSpacer2
CCopasiTask * mpTask
CQTaskThread * mpTaskThread
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 32 of file CQTSSAWidget.h.
Constructor & Destructor Documentation
CQTSSAWidget::CQTSSAWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 47 of file CQTSSAWidget.cpp.
References init().
     : TaskWidget(parent, name)
 {
   setupUi(this);
   init();
 }
CQTSSAWidget::~CQTSSAWidget ()
Definition at line 58 of file CQTSSAWidget.cpp.
References destroy().
 {
   destroy();
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
CCopasiMethod * CQTSSAWidget::createMethod (const CCopasiMethod::SubType & type) protected virtual
Implements TaskWidget.
Definition at line 226 of file CQTSSAWidget.cpp.
References CTSSAMethod::createMethod().
 {
   return CTSSAMethod::createMethod(type);
 }
void CQTSSAWidget::destroy () private
Definition at line 98 of file CQTSSAWidget.cpp.
References mpTSSAProblem, and pdelete.
Referenced by ~CQTSSAWidget().
 {
   pdelete(mpTSSAProblem);
 }
void CQTSSAWidget::init () private
Definition at line 75 of file CQTSSAWidget.cpp.
References max, TaskWidget::mpBtnWidget, TaskWidget::mpHeaderWidget, TaskWidget::mpMethodWidget, mpTSSAProblem, mpValidatorDuration, mpValidatorIntervalSize, CQValidatorDouble::setRange(), CQTaskHeaderWidget::setTaskName(), CQTaskMethodWidget::setValidMethods(), CQTaskMethodWidget::showMethodParameters(), and CTSSATask::ValidMethods.
Referenced by CQTSSAWidget().
 {
   mpTSSAProblem = NULL;
   mpHeaderWidget->setTaskName("Time Scale Separation Analysis");
   vboxLayout->insertWidget(0, mpHeaderWidget);  // header
   // vboxLayout->insertSpacing(1, 14);       // space between header and body
   mpMethodWidget->setValidMethods(CTSSATask::ValidMethods);
   mpMethodWidget->showMethodParameters(true);
   vboxLayout->addWidget(mpMethodWidget);
   vboxLayout->addWidget(mpBtnWidget);     // 'footer'
   mpValidatorDuration = new CQValidatorDouble(mpEditDuration);
   mpEditDuration->setValidator(mpValidatorDuration);
   mpValidatorIntervalSize = new CQValidatorDouble(mpEditIntervalSize);
   mpValidatorIntervalSize->setRange(0, std::numeric_limits< C_FLOAT64 >::max());
   mpEditIntervalSize->setValidator(mpValidatorIntervalSize);
 }
bool CQTSSAWidget::loadTask () protected virtual
Implements TaskWidget.
Definition at line 197 of file CQTSSAWidget.cpp.
References CTSSAProblem::getDuration(), CCopasiTask::getProblem(), CTSSAProblem::getStepNumber(), CTSSAProblem::getStepSize(), TaskWidget::loadCommon(), TaskWidget::loadMethod(), TaskWidget::mpTask, mpTSSAProblem, mpValidatorDuration, mpValidatorIntervalSize, pdelete, pTask, and CQValidator< Type >::saved().
 {
   CTSSATask * pTask =
     dynamic_cast< CTSSATask * >(mpTask);
   if (!pTask) return false;
   loadCommon();
   loadMethod();
   CTSSAProblem* tssaproblem =
     dynamic_cast<CTSSAProblem *>(pTask->getProblem());
   assert(tssaproblem);
   pdelete(mpTSSAProblem);
   mpTSSAProblem = new CTSSAProblem(*tssaproblem);
   //numbers
   mpEditIntervalSize->setText(QString::number(tssaproblem->getStepSize()));
   mpEditIntervals->setText(QString::number(tssaproblem->getStepNumber()));
   mpEditDuration->setText(QString::number(tssaproblem->getDuration()));
   mpValidatorDuration->saved();
   mpValidatorIntervalSize->saved();
   return true;
 }
bool CQTSSAWidget::runTask () virtual
Implements TaskWidget.
Definition at line 231 of file CQTSSAWidget.cpp.
References TaskWidget::commonBeforeRunTask(), TaskWidget::commonRunTask(), CTSSAMethod::emptyVectors(), CCopasiRootContainer::getDatamodelList(), and CCopasiTask::getMethod().
 {
   assert(CCopasiRootContainer::getDatamodelList()->size() > 0);
   pCTSSATask =
     dynamic_cast<CTSSATask *>((*(*CCopasiRootContainer::getDatamodelList())[0]->getTaskList())["Time Scale Separation Analysis"]);
   if (!pCTSSATask) return false;
   pTSSMethod = dynamic_cast<CTSSAMethod*>(pCTSSATask->getMethod());
   if (!pTSSMethod)
     pTSSMethod->emptyVectors();
   if (!commonBeforeRunTask()) return false;
   bool success = true;
   if (!commonRunTask()) success = false;
   return success;
 }
bool CQTSSAWidget::saveTask () protected virtual
Implements TaskWidget.
Definition at line 158 of file CQTSSAWidget.cpp.
References CTSSAProblem::getDuration(), CCopasiTask::getProblem(), CTSSAProblem::getStepNumber(), CTSSAProblem::getStepSize(), TaskWidget::mChanged, TaskWidget::mpTask, mpValidatorDuration, mpValidatorIntervalSize, pTask, TaskWidget::saveCommon(), CQValidator< Type >::saved(), TaskWidget::saveMethod(), CTSSAProblem::setDuration(), CTSSAProblem::setStepNumber(), and CTSSAProblem::setStepSize().
 {
   CTSSATask * pTask =
     dynamic_cast< CTSSATask * >(mpTask);
   if (!pTask) return false;
   saveCommon();
   saveMethod();
   CTSSAProblem* tssaproblem =
     dynamic_cast<CTSSAProblem *>(pTask->getProblem());
   assert(tssaproblem);
   //numbers
   if (tssaproblem->getStepSize() != mpEditIntervalSize->text().toDouble())
     {
       tssaproblem->setStepSize(mpEditIntervalSize->text().toDouble());
       mChanged = true;
     }
   else if (tssaproblem->getStepNumber() != mpEditIntervals->text().toULong())
     {
       tssaproblem->setStepNumber(mpEditIntervals->text().toLong());
       mChanged = true;
     }
   if (tssaproblem->getDuration() != mpEditDuration->text().toDouble())
     {
       tssaproblem->setDuration(mpEditDuration->text().toDouble());
       mChanged = true;
     }
   mpValidatorDuration->saved();
   mpValidatorIntervalSize->saved();
   return true;
 }
void CQTSSAWidget::slotDuration () slot
Definition at line 103 of file CQTSSAWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CTSSAProblem::getStepNumber(), CTSSAProblem::getStepSize(), CQMessageBox::information(), mpTSSAProblem, mpValidatorIntervalSize, CQValidator< Type >::revalidate(), and CTSSAProblem::setDuration().
 {
   try
     {
       mpTSSAProblem->setDuration(mpEditDuration->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
   mpEditIntervalSize->setText(QString::number(mpTSSAProblem->getStepSize()));
   mpValidatorIntervalSize->revalidate();
   mpEditIntervals->setText(QString::number(mpTSSAProblem->getStepNumber()));
 }
void CQTSSAWidget::slotIntervals () slot
Definition at line 141 of file CQTSSAWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CTSSAProblem::getStepSize(), CQMessageBox::information(), mpTSSAProblem, mpValidatorIntervalSize, CQValidator< Type >::revalidate(), and CTSSAProblem::setStepNumber().
 {
   try
     {
       mpTSSAProblem->setStepNumber(mpEditIntervals->text().toULong());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
   mpEditIntervalSize->setText(QString::number(mpTSSAProblem->getStepSize()));
   mpValidatorIntervalSize->revalidate();
 }
void CQTSSAWidget::slotIntervalSize () slot
Definition at line 122 of file CQTSSAWidget.cpp.
References FROM_UTF8, CCopasiMessage::getAllMessageText(), CTSSAProblem::getStepNumber(), CTSSAProblem::getStepSize(), CQMessageBox::information(), mpTSSAProblem, mpValidatorIntervalSize, CQValidator< Type >::revalidate(), and CTSSAProblem::setStepSize().
 {
   try
     {
       mpTSSAProblem->setStepSize(mpEditIntervalSize->text().toDouble());
     }
   catch (...)
     {
       CQMessageBox::information(this, QString("Information"),
                                 FROM_UTF8(CCopasiMessage::getAllMessageText()),
                                 QMessageBox::Ok, QMessageBox::Ok);
     }
   mpEditIntervalSize->setText(QString::number(mpTSSAProblem->getStepSize()));
   mpValidatorIntervalSize->revalidate();
   mpEditIntervals->setText(QString::number(mpTSSAProblem->getStepNumber()));
 }
bool CQTSSAWidget::taskFinishedEvent () protected virtual
Reimplemented from TaskWidget.
Definition at line 253 of file CQTSSAWidget.cpp.
References CQTSSAResultSubWidget::discardOldResults(), CQTSSAResultSubWidget::displayResult(), ListViews::findWidgetFromId(), CQTSSAResultWidget::getSubWidget(), CQTSSAResultWidget::loadFromBackend(), CopasiWidget::mpListView, pResult, and ListViews::switchToOtherWidget().
 {
   bool success = true;
   // We need to load the result here as this is the only place where
   // we know that it is correct.
   CQTSSAResultWidget * pResult =
     dynamic_cast< CQTSSAResultWidget * >(mpListView->findWidgetFromId(271));
   if (pResult == NULL)
     {
       return false;
     }
   success &= pResult->loadFromBackend();
   pTSSResultSubWidget = pResult->getSubWidget();
   if (!pTSSResultSubWidget)
     return false;
   pTSSResultSubWidget->discardOldResults();
   if (success)
     {
       pTSSResultSubWidget->displayResult();
       mpListView->switchToOtherWidget(271, ""); //change to the results window
     }
   return success;
 }
Member Data Documentation
CTSSAProblem* CQTSSAWidget::mpTSSAProblem private
Definition at line 57 of file CQTSSAWidget.h.
Referenced by destroy(), init(), loadTask(), slotDuration(), slotIntervals(), and slotIntervalSize().
CQValidatorDouble* CQTSSAWidget::mpValidatorDelay private
Definition at line 60 of file CQTSSAWidget.h.
CQValidatorDouble* CQTSSAWidget::mpValidatorDuration private
Definition at line 58 of file CQTSSAWidget.h.
Referenced by init(), loadTask(), and saveTask().
CQValidatorInt* CQTSSAWidget::mpValidatorIntervals private
Definition at line 61 of file CQTSSAWidget.h.
CQValidatorDouble* CQTSSAWidget::mpValidatorIntervalSize private
Definition at line 59 of file CQTSSAWidget.h.
Referenced by init(), loadTask(), saveTask(), slotDuration(), slotIntervals(), and slotIntervalSize().
The documentation for this class was generated from the following files:
CQTSSAWidget.h
CQTSSAWidget.cpp