COPASI API: ObjectBrowserDialog Class Reference
ObjectBrowserDialog Class Reference
#include <ObjectBrowserDialog.h>
Public Slots
void cancelClicked ()
void okClicked ()
void toggleViewClicked ()
Public Member Functions
ObjectBrowserDialog (QWidget *parent=0, const char *name=0, bool modal=true, int state=0)
void selectObjects (std::vector< const CCopasiObject * > *pObjectVector)
void setOutputVector (std::vector< const CCopasiObject * > *pObjectVector)
virtual ~ObjectBrowserDialog ()
Protected Attributes
QPushButton * cancelButton
QPushButton * clearButton
QFrame * Line1
QGridLayout * ObjectBrowserDialogLayout
ObjectBrowserWidget * objectBrowserWidget
QPushButton * okButton
QSpacerItem * spacer
QPushButton * toggleViewButton
Detailed Description
Definition at line 32 of file ObjectBrowserDialog.h.
Constructor & Destructor Documentation
ObjectBrowserDialog::ObjectBrowserDialog (QWidget * parent = 0, const char * name = 0, bool modal = true, int state = 0)
Definition at line 32 of file ObjectBrowserDialog.cpp.
References cancelButton, cancelClicked(), clearButton, Line1, ObjectBrowserDialogLayout, objectBrowserWidget, okButton, okClicked(), toggleViewButton, and toggleViewClicked().
   : QDialog(parent),
     clearButton(NULL),
     toggleViewButton(NULL),
     cancelButton(NULL),
     okButton(NULL),
     Line1(NULL),
     spacer(NULL),
     objectBrowserWidget(NULL),
     ObjectBrowserDialogLayout(NULL)
 {
   setObjectName(QString::fromUtf8(name));
   setModal(modal);
   setAttribute(Qt::WA_DeleteOnClose);
   ObjectBrowserDialogLayout = new QGridLayout(this);
   ObjectBrowserDialogLayout->setMargin(11);
   ObjectBrowserDialogLayout->setSpacing(6);
   ObjectBrowserDialogLayout->setObjectName(QString::fromUtf8("ObjectBrowserDialogLayout"));
   objectBrowserWidget = new ObjectBrowserWidget(this);
   ObjectBrowserDialogLayout->addWidget(objectBrowserWidget, 0, 0, 1, 2);
   Line1 = new QFrame(this);
   Line1->setObjectName("Line1");
   Line1->setFrameShape(QFrame::HLine);
   Line1->setFrameShadow(QFrame::Sunken);
   Line1->setFrameShape(QFrame::HLine);
   ObjectBrowserDialogLayout->addWidget(Line1, 1, 0, 1, 2);
   if (state == 0)
     {
       clearButton = new QPushButton(this);
       clearButton->setObjectName("clearButton");
       clearButton->setText("Clear");
       toggleViewButton = new QPushButton(this);
       toggleViewButton->setObjectName("toggleViewButton");
       toggleViewButton->setText("Selected Items");
       cancelButton = new QPushButton(this);
       cancelButton->setObjectName("cancelButton");
       cancelButton->setText("Cancel");
       okButton = new QPushButton(this);
       okButton->setObjectName("okButton");
       okButton->setText("OK");
       okButton->setDefault(true);
       okButton->setAutoDefault(true);
       connect(clearButton, SIGNAL(clicked()), objectBrowserWidget, SLOT(clearClicked()));
       connect(toggleViewButton, SIGNAL(clicked()), this, SLOT(toggleViewClicked()));
       connect(cancelButton, SIGNAL(clicked()), this, SLOT(cancelClicked()));
       connect(okButton, SIGNAL(clicked()), this, SLOT(okClicked()));
       ObjectBrowserDialogLayout->addWidget(clearButton, 2, 0);
       ObjectBrowserDialogLayout->addWidget(toggleViewButton, 2, 1);
       ObjectBrowserDialogLayout->addWidget(cancelButton, 2, 2);
       ObjectBrowserDialogLayout->addWidget(okButton, 2, 3);
       setTabOrder(okButton, clearButton);
       setTabOrder(clearButton, toggleViewButton);
       setTabOrder(toggleViewButton, cancelButton);
       setTabOrder(cancelButton, objectBrowserWidget);
     }
   else
     {
       okButton = new QPushButton(this);
       okButton->setObjectName("okButton");
       okButton->setText("Close");
       okButton->setDefault(true);
       okButton->setAutoDefault(true);
       ObjectBrowserDialogLayout->addWidget(okButton, 2, 1, 1, 1);
       connect(okButton, SIGNAL(clicked()), this, SLOT(okClicked()));
       setTabOrder(okButton, objectBrowserWidget);
     }
   if (!name)
     setObjectName("ObjectBrowser");
   resize(420, 460);
   setWindowTitle(trUtf8("Object Browser"));
 }
ObjectBrowserDialog::~ObjectBrowserDialog () virtual
Definition at line 117 of file ObjectBrowserDialog.cpp.
 {}
Member Function Documentation
void ObjectBrowserDialog::cancelClicked () slot
Definition at line 125 of file ObjectBrowserDialog.cpp.
Referenced by ObjectBrowserDialog().
 {
   close();
 }
void ObjectBrowserDialog::okClicked () slot
Definition at line 130 of file ObjectBrowserDialog.cpp.
References ObjectBrowserWidget::commitClicked(), and objectBrowserWidget.
Referenced by ObjectBrowserDialog().
 {
   objectBrowserWidget->commitClicked();
   done(QDialog::Accepted);
 }
void ObjectBrowserDialog::selectObjects (std::vector< const CCopasiObject * > * pObjectVector)
Definition at line 146 of file ObjectBrowserDialog.cpp.
References objectBrowserWidget, and ObjectBrowserWidget::selectObjects().
 {
   if (objectBrowserWidget) objectBrowserWidget->selectObjects(pObjectVector);
 }
void ObjectBrowserDialog::setOutputVector (std::vector< const CCopasiObject * > * pObjectVector)
Definition at line 120 of file ObjectBrowserDialog.cpp.
References objectBrowserWidget, and ObjectBrowserWidget::setOutputVector().
 {
   if (objectBrowserWidget) objectBrowserWidget->setOutputVector(pObjectVector);
 }
void ObjectBrowserDialog::toggleViewClicked () slot
Definition at line 136 of file ObjectBrowserDialog.cpp.
References objectBrowserWidget, toggleViewButton, and ObjectBrowserWidget::toggleViewClicked().
Referenced by ObjectBrowserDialog().
 {
   if (toggleViewButton->text() == "Selected Items")
     toggleViewButton->setText("Tree View");
   else
     toggleViewButton->setText("Selected Items");
   objectBrowserWidget->toggleViewClicked();
 }
Member Data Documentation
QPushButton* ObjectBrowserDialog::cancelButton protected
Definition at line 46 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog().
QPushButton* ObjectBrowserDialog::clearButton protected
Definition at line 44 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog().
QFrame* ObjectBrowserDialog::Line1 protected
Definition at line 48 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog().
QGridLayout* ObjectBrowserDialog::ObjectBrowserDialogLayout protected
Definition at line 51 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog().
ObjectBrowserWidget* ObjectBrowserDialog::objectBrowserWidget protected
Definition at line 50 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog(), okClicked(), selectObjects(), setOutputVector(), and toggleViewClicked().
QPushButton* ObjectBrowserDialog::okButton protected
Definition at line 47 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog().
QSpacerItem* ObjectBrowserDialog::spacer protected
Definition at line 49 of file ObjectBrowserDialog.h.
QPushButton* ObjectBrowserDialog::toggleViewButton protected
Definition at line 45 of file ObjectBrowserDialog.h.
Referenced by ObjectBrowserDialog(), and toggleViewClicked().
The documentation for this class was generated from the following files:
ObjectBrowserDialog.h
ObjectBrowserDialog.cpp