COPASI API: CSBMLunitInformation Class Reference
CSBMLunitInformation Class Reference
#include <CSBMLunit.h>
Public Types
enum INFO {
UNKNOWN = 0, DEFAULT, GLOBAL, PROVIDED,
DERIVED
}
this enum encodes the status of a units information
Public Member Functions
CSBMLunitInformation (unsigned int sbmlLevel, unsigned int sbmlVersion)
Default constructor.
CSBMLunitInformation (unsigned int sbmlLevel, unsigned int sbmlVersion, INFO info, bool conflict=false)
CSBMLunitInformation (const CSBMLunit &u, INFO info, bool conflict=false)
CSBMLunitInformation (const UnitDefinition *ud, INFO info, bool conflict=false)
virtual std::string getDisplayString () const
INFO getInfo () const
get the status information
bool isConflict () const
retrieve the conflict flag
void setConflict (bool c)
set the conflict flag
void setInfo (INFO info)
set the status information
Public Member Functions inherited from CSBMLunit
void applyExponent (double exp)
apply numeric exponent to the unit.
void applyExponent (const std::string &id, size_t frame)
apply symbolic exponent to the unit
void applyInverseExponent (const std::string &id, size_t frame)
apply inverse of symbolic exponent to the unit
CSBMLunit (unsigned int sbmlLevel, unsigned int sbmlVersion)
Default constructor.
CSBMLunit (const CSBMLunit &src)
Copy constructor.
CSBMLunit (const UnitDefinition *ud)
Constructor from libsbml units.
UnitDefinition & getSBMLUnitDefinition ()
const UnitDefinition & getSBMLUnitDefinition () const
int getSymbolicExpExp () const
const std::string & getSymbolicExponent () const
void invert ()
bool isDimensionless () const
bool multiply (const CSBMLunit &unit)
virtual ~CSBMLunit ()
Static Public Member Functions
static bool isEqual (const CSBMLunitInformation &unit1, const CSBMLunitInformation &unit2)
Static Public Member Functions inherited from CSBMLunit
static bool isEqual (const CSBMLunit &unit1, const CSBMLunit &unit2)
Private Attributes
bool mConflict
indicated whether a conflict occurred while trying to determine the unit.
INFO mInfo
Detailed Description
This class contains one unit definition plus some meta information, e.g. whether the unit was provided or calculated, if it is unknown or if there is a conflict.
Definition at line 99 of file CSBMLunit.h.
Member Enumeration Documentation
enum CSBMLunitInformation::INFO
this enum encodes the status of a units information
Enumerator
UNKNOWN
the units is unknown
DEFAULT
the units is determined from the sbml defaults
GLOBAL
the units is determined from the model-wide definitions
PROVIDED
the units if provided for a specific object explicitly
DERIVED
the units was determined by reasoning
Definition at line 103 of file CSBMLunit.h.
   {
     /// the units is unknown
     UNKNOWN = 0,
     /// the units is determined from the sbml defaults
     DEFAULT,
     /// the units is determined from the model-wide definitions
     GLOBAL,
     ///the units if provided for a specific object explicitly
     PROVIDED,
     ///the units was determined by reasoning
     DERIVED
   };
Constructor & Destructor Documentation
CSBMLunitInformation::CSBMLunitInformation (unsigned int sbmlLevel, unsigned int sbmlVersion)
Default constructor.
Definition at line 182 of file CSBMLunit.cpp.
     : CSBMLunit(sbmlLevel, sbmlVersion),
     mInfo(UNKNOWN),
     mConflict(false)
 {
 }
CSBMLunitInformation::CSBMLunitInformation (unsigned int sbmlLevel, unsigned int sbmlVersion, INFO info, bool conflict = false)
Definition at line 189 of file CSBMLunit.cpp.
     : CSBMLunit(sbmlLevel, sbmlVersion),
     mInfo(info),
     mConflict(conflict)
 {
 }
CSBMLunitInformation::CSBMLunitInformation (const CSBMLunit & u, INFO info, bool conflict = false)
Definition at line 196 of file CSBMLunit.cpp.
     : CSBMLunit(u),
     mInfo(info),
     mConflict(conflict)
 {
 }
CSBMLunitInformation::CSBMLunitInformation (const UnitDefinition * ud, INFO info, bool conflict = false)
Definition at line 203 of file CSBMLunit.cpp.
     : CSBMLunit(ud),
     mInfo(info),
     mConflict(conflict)
 {
 }
Member Function Documentation
std::string CSBMLunitInformation::getDisplayString () const virtual
Reimplemented from CSBMLunit.
Definition at line 210 of file CSBMLunit.cpp.
References DEFAULT, DERIVED, CSBMLunit::getDisplayString(), GLOBAL, mConflict, mInfo, PROVIDED, and UNKNOWN.
Referenced by CSBMLunitInterface::debugOutput(), and CSBMLunitInterface::determineUnits().
 {
   std::string sss;
   switch (mInfo)
     {
       case UNKNOWN:
         sss += "unknown";
         break;
       case DEFAULT:
         sss += "default:  " + CSBMLunit::getDisplayString();
         break;
       case GLOBAL:
         sss += "global:  " + CSBMLunit::getDisplayString();
         break;
       case PROVIDED:
         sss += "provided:  " + CSBMLunit::getDisplayString();
         break;
       case DERIVED:
         sss += "derived:  " + CSBMLunit::getDisplayString();
         break;
     };
   if (mConflict)
     sss  += "!!!Conflict!!!";
   return sss;
 }
INFO CSBMLunitInformation::getInfo () const inline
get the status information
Definition at line 130 of file CSBMLunit.h.
References mInfo.
Referenced by Expression2PresentationMMLUnits::getMathML(), CSBMLunitInterface::handleOneExpression(), CSBMLunitInterface::handleTerminalNode(), CSBMLunitInterface::initializeFromSBMLModel(), CSBMLunitInterface::recursionDivide(), CSBMLunitInterface::recursionEqual(), CSBMLunitInterface::recursionPiecewise(), CSBMLunitInterface::recursionPower(), CSBMLunitInterface::recursionTimes(), and CSBMLunitInterface::writeBackToModel().
 {return mInfo;};
bool CSBMLunitInformation::isConflict () const inline
retrieve the conflict flag
Definition at line 136 of file CSBMLunit.h.
References mConflict.
Referenced by Expression2PresentationMMLUnits::getMathML(), and CSBMLunitInterface::handleTerminalNode().
 {return mConflict;};
bool CSBMLunitInformation::isEqual (const CSBMLunitInformation & unit1, const CSBMLunitInformation & unit2) static
Definition at line 240 of file CSBMLunit.cpp.
References CSBMLunit::isEqual(), mConflict, and mInfo.
Referenced by Expression2PresentationMMLUnits::writeMathMLName().
 {
   if (unit1.mInfo == unit2.mInfo && unit1.mConflict == unit2.mConflict)
     return CSBMLunit::isEqual(unit1, unit2);
   else
     return false;
 }
void CSBMLunitInformation::setConflict (bool c) inline
set the conflict flag
Definition at line 133 of file CSBMLunit.h.
References mConflict.
Referenced by CSBMLunitInterface::handleTerminalNode().
 {mConflict = c;};
void CSBMLunitInformation::setInfo (INFO info) inline
set the status information
Definition at line 127 of file CSBMLunit.h.
References mInfo.
Referenced by CSBMLunitInterface::handleTerminalNode(), CSBMLunitInterface::initializeFromSBMLModel(), CSBMLunitInterface::recursion(), CSBMLunitInterface::recursionDivide(), CSBMLunitInterface::recursionPower(), and CSBMLunitInterface::recursionTimes().
 {mInfo = info;};
Member Data Documentation
bool CSBMLunitInformation::mConflict private
indicated whether a conflict occurred while trying to determine the unit.
Definition at line 146 of file CSBMLunit.h.
Referenced by getDisplayString(), isConflict(), isEqual(), and setConflict().
INFO CSBMLunitInformation::mInfo private
Definition at line 143 of file CSBMLunit.h.
Referenced by getDisplayString(), getInfo(), isEqual(), and setInfo().
The documentation for this class was generated from the following files:
CSBMLunit.h
CSBMLunit.cpp