COPASI API: CLDefaultStyles.h File Reference
CLDefaultStyles.h File Reference
#include "copasi/copasi.h"
#include "copasi/utilities/CCopasiVector.h"
#include "copasi/layout/CLGlobalRenderInformation.h"
Functions
CLGlobalRenderInformation * getDefaultStyle (size_t index)
CCopasiVector
< CLGlobalRenderInformation > * getDefaultStyles ()
size_t getNumDefaultStyles ()
CCopasiVector
< CLGlobalRenderInformation > * loadDefaultStyles ()
Variables
CCopasiVector
< CLGlobalRenderInformation > * DEFAULT_STYLES
Function Documentation
CLGlobalRenderInformation* getDefaultStyle (size_t index)
This method returns the default render information object with the requested index. If the index isinvalid, NULL is returned.
Definition at line 824 of file CLDefaultStyles.cpp.
References loadDefaultStyles(), and pResult.
Referenced by CQNewMainWindow::addDefaultRenderInfoItemsToList(), CSBMLExporter::exportModelToString(), CQLayoutScene::initializeResolver(), CQNewMainWindow::slotRenderInfoChanged(), CQLayoutView::slotRenderInformationChanged(), CQNewMainWindow::updateRenderer(), updateRenderInformationList(), and CQNewMainWindow::updateRenderInformationList().
 {
   if (!DEFAULT_STYLES)
     {
       DEFAULT_STYLES = loadDefaultStyles();
     }
   CLGlobalRenderInformation* pResult = NULL;
   if (DEFAULT_STYLES != NULL && index < DEFAULT_STYLES->size())
     {
       pResult = static_cast<CLGlobalRenderInformation*>((*DEFAULT_STYLES)[index]);
     }
   return pResult;
 }
CCopasiVector<CLGlobalRenderInformation>* getDefaultStyles ()
This method returns a global render information list that contains the default styles which are built into the renderer.
Definition at line 790 of file CLDefaultStyles.cpp.
References DEFAULT_STYLES, and loadDefaultStyles().
 {
   if (!DEFAULT_STYLES)
     {
       DEFAULT_STYLES = loadDefaultStyles();
     }
   return DEFAULT_STYLES;
 }
size_t getNumDefaultStyles ()
This method returns the number of global styles.
Definition at line 803 of file CLDefaultStyles.cpp.
References loadDefaultStyles(), and CCopasiVector< T >::size().
Referenced by CQNewMainWindow::addDefaultRenderInfoItemsToList(), CSBMLExporter::exportModelToString(), CQLayoutView::slotRenderInformationChanged(), updateRenderInformationList(), and CQNewMainWindow::updateRenderInformationList().
 {
   size_t result = 0;
   if (!DEFAULT_STYLES)
     {
       DEFAULT_STYLES = loadDefaultStyles();
     }
   if (DEFAULT_STYLES != NULL)
     {
       result = DEFAULT_STYLES->size();
     }
   return result;
 }
CCopasiVector<CLGlobalRenderInformation>* loadDefaultStyles ()
This method is used to initialize the default styles. Normally this does not need to be called since it is called automatically. The method returns a point to a ListOfGlobalRenderInformation object. The caller is responsible for freeing the memory associated with the list.
Definition at line 841 of file CLDefaultStyles.cpp.
References CCopasiVector< T >::add(), DEFAULT_STYLES, DEFAULT_STYLES_STRING, and pResult.
Referenced by CQNewMainWindow::CQNewMainWindow(), getDefaultStyle(), getDefaultStyles(), and getNumDefaultStyles().
 {
   // try to initialize the default styles
   if (DEFAULT_STYLES != NULL)
     {
       delete DEFAULT_STYLES;
     }
   XMLInputStream stream(DEFAULT_STYLES_STRING, false);
   ListOfGlobalRenderInformation* pRI = new ListOfGlobalRenderInformation();
   pRI->parseXML(XMLNode(stream));
   // convert the SBML objects to COPASI objects
   size_t i, iMax = pRI->size();
   CCopasiVector<CLGlobalRenderInformation>* pResult = new CCopasiVector<CLGlobalRenderInformation>;
   for (i = 0; i < iMax; ++i)
     {
       pResult->add(new CLGlobalRenderInformation(*static_cast<const GlobalRenderInformation*>(pRI->get((unsigned int) i))), true);
     }
   delete pRI;
   return pResult;
 }
Variable Documentation
CCopasiVector<CLGlobalRenderInformation>* DEFAULT_STYLES
A pointer to the list of default styles.
Definition at line 22 of file CLDefaultStyles.cpp.