COPASI API: CQValidatorBound Class Reference
CQValidatorBound Class Reference
#include <CQValidator.h>
Public Member Functions
CQValidatorBound (QLineEdit *parent, const QString &sign)
virtual void force (const QString &input) const
virtual State validate (QString &input, int &pos) const
Public Member Functions inherited from CQValidator< QLineEdit >
CQValidator (QLineEdit *parent, QString(QLineEdit::*retrieve)(void) const, const char *name=0)
virtual State revalidate ()
virtual void saved () const
Protected Attributes
QDoubleValidator * mpDoubleValidator
QString mSign
QString mValidBound
Protected Attributes inherited from CQValidator< QLineEdit >
QString mLastAccepted
QLineEdit * mpContainer
QString(QLineEdit::* mRetrieve)(void) const
Additional Inherited Members
Protected Member Functions inherited from CQValidator< QLineEdit >
State setColor (const State &state) const
Detailed Description
Definition at line 125 of file CQValidator.h.
Constructor & Destructor Documentation
CQValidatorBound::CQValidatorBound (QLineEdit * parent, const QString & sign)
Definition at line 34 of file CQValidator.cpp.
                                                                           :
   CQValidator< QLineEdit >(parent, &QLineEdit::text, NULL),
   mpDoubleValidator(new QDoubleValidator(-std::numeric_limits< C_FLOAT64 >::max(), std::numeric_limits< C_FLOAT64 >::max(), std::numeric_limits< C_FLOAT64 >::digits10, this)),
   mSign(sign),
   mValidBound("\t") // It is not possible to insert a tab.
 {}
Member Function Documentation
void CQValidatorBound::force (const QString & input) const virtual
Reimplemented from CQValidator< QLineEdit >.
Definition at line 59 of file CQValidator.cpp.
References CQValidator< Type >::force(), and mValidBound.
Referenced by CQFittingItemWidget::slotLowerEdit(), CQFittingItemWidget::slotUpperEdit(), and validate().
 {
   const_cast<CQValidatorBound *>(this)->mValidBound = input;
   CQValidator< QLineEdit >::force(input);
 }
QValidator::State CQValidatorBound::validate (QString & input, int & pos) const virtual
Reimplemented from CQValidator< QLineEdit >.
Definition at line 41 of file CQValidator.cpp.
References force(), mpDoubleValidator, mSign, mValidBound, and CQValidator< QLineEdit >::setColor().
 {
   QString Input;
   if (input == mValidBound ||
       mpDoubleValidator->validate(input, pos) == Acceptable ||
       (input.startsWith(mSign) &&
        input.endsWith("%") &&
        mpDoubleValidator->validate(Input = input.mid(1, input.length() - 2), pos)))
     {
       force(input);
       return Acceptable;
     }
   setColor(Invalid);
   return Intermediate;
 }
Member Data Documentation
QDoubleValidator* CQValidatorBound::mpDoubleValidator protected
Definition at line 137 of file CQValidator.h.
Referenced by validate().
QString CQValidatorBound::mSign protected
Definition at line 139 of file CQValidator.h.
Referenced by validate().
QString CQValidatorBound::mValidBound protected
Definition at line 141 of file CQValidator.h.
Referenced by force(), and validate().
The documentation for this class was generated from the following files:
CQValidator.h
CQValidator.cpp