COPASI API: test000103 Class Reference
test000103 Class Reference
#include <test000103.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1743_l2 ()
void test_bug1743_l3 ()
Protected Attributes
CCopasiDataModel * pDataModel
Static Protected Attributes
static const char * SBML_STRING
Private Member Functions
CPPUNIT_TEST (test_bug1743_l2)
CPPUNIT_TEST (test_bug1743_l3)
CPPUNIT_TEST_SUITE (test000103)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 28 of file test000103.h.
Member Function Documentation
test000103::CPPUNIT_TEST (test_bug1743_l2) private
test000103::CPPUNIT_TEST (test_bug1743_l3) private
test000103::CPPUNIT_TEST_SUITE (test000103) private
test000103::CPPUNIT_TEST_SUITE_END () private
void test000103::setUp ()
Definition at line 17 of file test000103.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pDataModel.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   pDataModel = CCopasiRootContainer::addDatamodel();
 }
void test000103::tearDown ()
Definition at line 24 of file test000103.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000103::test_bug1743_l2 ()
Definition at line 29 of file test000103.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getModel(), CModelEntity::getSBMLId(), CCopasiDataModel::importSBMLFromString(), CCopasiDataModel::newModel(), pDataModel, and CModelEntity::setSBMLId().
 {
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   std::string id("MyTestModel");
   pModel->setSBMLId(id);
   CPPUNIT_ASSERT(pModel->getSBMLId() == id);
   // export to l2v4
   std::string model_string = pDataModel->exportSBMLToString(NULL, 2, 4);
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getSBMLId() == id);
   pDataModel->newModel(NULL, true);
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getSBMLId() != id);
   try
     {
       bool result = pDataModel->importSBMLFromString(model_string);
       CPPUNIT_ASSERT(result == true);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("Exception while importing the exported model string.", false);
     }
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getSBMLId() == id);
 }
void test000103::test_bug1743_l3 ()
Definition at line 61 of file test000103.cpp.
References CCopasiDataModel::exportSBMLToString(), CCopasiDataModel::getModel(), CModelEntity::getSBMLId(), CCopasiDataModel::importSBMLFromString(), CCopasiDataModel::newModel(), pDataModel, and CModelEntity::setSBMLId().
 {
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   std::string id("MyTestModel");
   pModel->setSBMLId(id);
   CPPUNIT_ASSERT(pModel->getSBMLId() == id);
   // export to l3v1
   std::string model_string = pDataModel->exportSBMLToString(NULL, 3, 1);
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getSBMLId() == id);
   pDataModel->newModel(NULL, true);
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getSBMLId() != id);
   try
     {
       bool result = pDataModel->importSBMLFromString(model_string);
       CPPUNIT_ASSERT(result == true);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("Exception while importing the exported model string.", false);
     }
   pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getSBMLId() == id);
 }
Member Data Documentation
CCopasiDataModel* test000103::pDataModel protected
Definition at line 39 of file test000103.h.
Referenced by setUp(), test_bug1743_l2(), and test_bug1743_l3().
const char* test000103::SBML_STRING static protected
Definition at line 37 of file test000103.h.
The documentation for this class was generated from the following files:
test000103.h
test000103.cpp