COPASI API: CCopasiTree< _Node > Class Template Reference
CCopasiTree< _Node > Class Template Reference
#include <CCopasiTree.h>
Classes
class const_iterator
class iterator
Public Types
typedef _Node Node
Public Member Functions
bool attachNode (_Node *pNode, _Node *pParent=NULL, _Node *pAfterChild=NULL)
iterator begin () const
CCopasiTree ()
bool detachNode (_Node *pNode)
iterator end () const
_Node::Data getData () const
_Node * getRoot ()
bool moveNode (_Node *pNode, _Node *pParent=NULL, _Node *pAfterChild=NULL)
bool removeNode (_Node *pNode)
~CCopasiTree ()
Private Attributes
std::set< _Node * > mList
_Node * mpRoot
Friends
std::ostream & operator<< (std::ostream &os, const CCopasiTree< _Node > &A)
Detailed Description
template<class _Node>
class CCopasiTree< _Node >
CCopasiTree class. The template class CCopasiTree describes a tree of Nodes.
Created for COPASI by Stefan Hoops 2003
The template class CCopasiTree takes as template argument a class derived from the class CCopasiNode. It allows the construction of a tree with four simple methods. It assures that each node in the tree is unique.
In addition it provides a forward iterator useful to traverse the tree.
Note: The tree takes ownership of all nodes. Therefore, you must not use pointers to automatically created nodes in the attachNode() Function unless you use the detach node function prior to the destruction of the tree.
Definition at line 37 of file CCopasiTree.h.
Member Typedef Documentation
template<class _Node> typedef _Node CCopasiTree< _Node >::Node
Definition at line 59 of file CCopasiTree.h.
Constructor & Destructor Documentation
template<class _Node> CCopasiTree< _Node >::CCopasiTree () inline
Default constructor
Definition at line 250 of file CCopasiTree.h.
References CCopasiTree< _Node >::mList, and CCopasiTree< _Node >::mpRoot.
                :
       mpRoot(new _Node),
       mList()
   {mList.insert(mpRoot);}
template<class _Node> CCopasiTree< _Node >::~CCopasiTree () inline
Destructor
Definition at line 258 of file CCopasiTree.h.
References CCopasiTree< _Node >::mpRoot, and pdelete.
 {pdelete(mpRoot);}
Member Function Documentation
template<class _Node> bool CCopasiTree< _Node >::attachNode (_Node * pNode, _Node * pParent = NULL, _Node * pAfterChild = NULL) inline
Attach a Node to the tree Note: If pAfterChild == pParent then the child will be inserted as the first child
Parameters
Node * pNode
Node * pParent (default: NULL equivalent to the root of the tree)
Node * pAfterChild (default: NULL at the end of the children)
Returns
bool Success
Definition at line 293 of file CCopasiTree.h.
References CCopasiTree< _Node >::end(), CCopasiTree< _Node >::mList, and CCopasiTree< _Node >::mpRoot.
Referenced by CCopasiTree< _Node >::moveNode().
   {
     bool Success = true;
     if (mList.count(pNode))
       return false;                     // Node already in tree.
     if (pAfterChild && !mList.count(pAfterChild))
       return false;                     // Invalid insertion point.
     if (pParent)
       {
         if (mList.count(pParent))
           Success = pParent->addChild(pNode, pAfterChild);
         else
           Success = false;                 // Invalid parent.
       }
     else
       Success = mpRoot->addChild(pNode, pAfterChild);
     if (Success)
       {
         iterator it = pNode;
         iterator end = (_Node *) it->getNextNonChild();
         for (; it != end; ++it)
           mList.insert(&*it);
       }
     return Success;
   }
template<class _Node> iterator CCopasiTree< _Node >::begin () const inline
Retrieve an iterator pointing to the beginning of the tree
Returns
iterator begin
Definition at line 264 of file CCopasiTree.h.
References CCopasiTree< _Node >::mpRoot.
Referenced by operator<<().
 {return iterator(mpRoot);}
template<class _Node> bool CCopasiTree< _Node >::detachNode (_Node * pNode) inline
Detach node. Node: After detachment of a node the tree no longer has the ownership.
Parameters
Node * pNode
Returns
bool Success
Definition at line 370 of file CCopasiTree.h.
References CCopasiTree< _Node >::end(), CCopasiTree< _Node >::mList, and CCopasiTree< _Node >::mpRoot.
Referenced by CCopasiTree< _Node >::moveNode().
   {
     if (!pNode) return false;          // Nothing to do.
     if (pNode == mpRoot) return false; // Root must not be detached
     iterator it = pNode;
     iterator end = (_Node *) it->getNextNonChild();
     for (; it != end; ++it)
       mList.erase(&*it);
     return pNode->getParent()->removeChild(pNode);
   }
template<class _Node> iterator CCopasiTree< _Node >::end () const inline
Retrieve an iterator pointing beyond the end of the tree
Returns
iterator end
Definition at line 270 of file CCopasiTree.h.
Referenced by CCopasiTree< _Node >::attachNode(), CCopasiTree< _Node >::detachNode(), operator<<(), and CCopasiTree< _Node >::removeNode().
 {return iterator(NULL);}
template<class _Node> _Node::Data CCopasiTree< _Node >::getData () const inline
Retrieve the data of the Tree.
Returns
Data data
Definition at line 282 of file CCopasiTree.h.
References CCopasiTree< _Node >::mpRoot.
 {return mpRoot->getData();}
template<class _Node> _Node* CCopasiTree< _Node >::getRoot () inline
Retrieve the root node of the tree
Returns
Node * root
Definition at line 276 of file CCopasiTree.h.
References CCopasiTree< _Node >::mpRoot.
 {return mpRoot;}
template<class _Node> bool CCopasiTree< _Node >::moveNode (_Node * pNode, _Node * pParent = NULL, _Node * pAfterChild = NULL) inline
Move a given node from its current place in the tree to the one specified by pParent and pAfterChild. The insertion behavior is similar to addChild().
Parameters
Node * pNode
Node * pParent (default: NULL equivalent to the root of the tree)
Node * pAfterChild (default: NULL at the end of the children)
Returns
bool Success
Definition at line 358 of file CCopasiTree.h.
References CCopasiTree< _Node >::attachNode(), and CCopasiTree< _Node >::detachNode().
   {
     detachNode(pNode);
     return attachNode(pNode, pParent, pAfterChild);
   }
template<class _Node> bool CCopasiTree< _Node >::removeNode (_Node * pNode) inline
Remove the given node of the tree
Parameters
Node * pNode
Returns
bool Success
Definition at line 332 of file CCopasiTree.h.
References CCopasiTree< _Node >::end(), CCopasiTree< _Node >::mList, and CCopasiTree< _Node >::mpRoot.
   {
     if (!pNode) return false;          // Nothing to remove.
     if (pNode == mpRoot) return false; // Root must not be removed.
     iterator it = pNode;
     iterator end = (_Node *) it->getNextNonChild();
     for (; it != end; ++it)
       mList.erase(&*it);
     delete pNode;
     return true;
   }
Friends And Related Function Documentation
template<class _Node> std::ostream& operator<< (std::ostream & os, const CCopasiTree< _Node > & A) friend
Definition at line 395 of file CCopasiTree.h.
 {
   typename CCopasiTree< _Node >::iterator it = A.begin();
   typename CCopasiTree< _Node >::iterator end = A.end();
   for (; it != end && &*it != NULL; ++it)
     os << &*it << ": parent: " << it->getParent()
     << ", child: " << it->getChild()
     << ", sibling: " << it->getSibling() << std::endl;
   os << std::endl;
   return os;
 }
Member Data Documentation
template<class _Node> std::set<_Node *> CCopasiTree< _Node >::mList private
The list of all nodes. This is used to keep the tree consistent by avoiding multiple inserts of the same node.
Definition at line 72 of file CCopasiTree.h.
Referenced by CCopasiTree< _Node >::attachNode(), CCopasiTree< _Node >::CCopasiTree(), CCopasiTree< _Node >::detachNode(), and CCopasiTree< _Node >::removeNode().
template<class _Node> _Node* CCopasiTree< _Node >::mpRoot private
The root of the tree
Definition at line 66 of file CCopasiTree.h.
Referenced by CCopasiTree< _Node >::attachNode(), CCopasiTree< _Node >::begin(), CCopasiTree< _Node >::CCopasiTree(), CCopasiTree< _Node >::detachNode(), CCopasiTree< _Node >::getData(), CCopasiTree< _Node >::getRoot(), CCopasiTree< _Node >::removeNode(), and CCopasiTree< _Node >::~CCopasiTree().
The documentation for this class was generated from the following file:
CCopasiTree.h