COPASI API: ObjectBrowserItem Class Reference
ObjectBrowserItem Class Reference
#include <ObjectBrowserItem.h>
Public Member Functions
void attachKey ()
CBrowserObject * getObject ()
objectType getType ()
bool isChecked () const
virtual QString key (int C_UNUSED(column), bool C_UNUSED(ascending)) const
QTreeWidgetItem * nextSibling ()
int nUserChecked ()
ObjectBrowserItem (QTreeWidget *parent=NULL, ObjectBrowserItem *after=NULL, const CCopasiObject *mObject=NULL, ObjectList *pList=NULL)
ObjectBrowserItem (ObjectBrowserItem *parent, ObjectBrowserItem *after=NULL, const CCopasiObject *mObject=NULL, ObjectList *pList=NULL)
void reverseChecked ()
void setBrowserObject (CBrowserObject *updateObject)
void setObjectType (objectType newType)
virtual ~ObjectBrowserItem ()
Static Public Member Functions
static long getKeySpace ()
static void resetKeySpace ()
Private Attributes
QString mKey
objectType mType
CBrowserObject * pBrowserObject
Static Private Attributes
static long KeySpace = 0
Detailed Description
Definition at line 76 of file ObjectBrowserItem.h.
Constructor & Destructor Documentation
ObjectBrowserItem::ObjectBrowserItem (QTreeWidget * parent = NULL, ObjectBrowserItem * after = NULL, const CCopasiObject * mObject = NULL, ObjectList * pList = NULL)
Constructs a new ObjectBrowserItem
Definition at line 64 of file ObjectBrowserItem.cpp.
References ObjectList::insert(), CBrowserObject::mChecked, mKey, pBrowserObject, CBrowserObject::pCopasiObject, and CBrowserObject::referenceList.
   : QTreeWidgetItem(parent, after)
 {
   if (mObject != NULL)
     {
       /* To change
       ObjectListItem* pTmp = pList->getRoot();
       while (pTmp != NULL)
         {
           if (pTmp->pItem->getObject()->pCopasiObject == mObject) // already be pointed in the list
             break;
           pTmp = pTmp->pNext;
         }
       if (pTmp && pTmp->pItem->getObject()->pCopasiObject == mObject) //exist already in list
         {
           pBrowserObject = pTmp->pItem->getObject();
           pBrowserObject->referenceList->insert(this);
         }
       else
          To change */
       {
         CBrowserObject* newBrowserObject = new CBrowserObject();
         newBrowserObject->pCopasiObject = mObject;
         newBrowserObject->mChecked = false;
         pBrowserObject = newBrowserObject;
         pBrowserObject->referenceList->insert(this);
       }
     }
   else //this is not an ending node
     {
       CBrowserObject* newBrowserObject = new CBrowserObject();
       newBrowserObject->pCopasiObject = mObject;
       newBrowserObject->mChecked = false;
       pBrowserObject = newBrowserObject;
       pBrowserObject->referenceList->insert(this);
     }
   if (pList)
     pList->insert(this);
   mKey = " ";
 }
ObjectBrowserItem::ObjectBrowserItem (ObjectBrowserItem * parent, ObjectBrowserItem * after = NULL, const CCopasiObject * mObject = NULL, ObjectList * pList = NULL)
Definition at line 107 of file ObjectBrowserItem.cpp.
References ObjectList::insert(), CBrowserObject::mChecked, mKey, pBrowserObject, CBrowserObject::pCopasiObject, and CBrowserObject::referenceList.
   : QTreeWidgetItem(parent, after)
 {
   if (mObject != NULL)
     {
       /* To change
       ObjectListItem* pTmp = pList->getRoot();
       while (pTmp != NULL)
         {
           if (pTmp->pItem->getObject()->pCopasiObject == mObject)
             break;
           pTmp = pTmp->pNext;
         }
       if (pTmp && pTmp->pItem->getObject()->pCopasiObject == mObject) //exist already in list
         {
           pBrowserObject = pTmp->pItem->getObject();
           pBrowserObject->referenceList->insert(this);
         }
       else
          To change */
       {
         CBrowserObject* newBrowserObject = new CBrowserObject();
         newBrowserObject->pCopasiObject = mObject;
         newBrowserObject->mChecked = false;
         pBrowserObject = newBrowserObject;
         pBrowserObject->referenceList->insert(this);
       }
     }
   else //this is not an ending node
     {
       CBrowserObject* newBrowserObject = new CBrowserObject();
       newBrowserObject->pCopasiObject = mObject;
       newBrowserObject->mChecked = false;
       pBrowserObject = newBrowserObject;
       pBrowserObject->referenceList->insert(this);
     }
   if (pList)
     pList->insert(this);
   mKey = " ";
 }
virtual ObjectBrowserItem::~ObjectBrowserItem () inline virtual
Definition at line 107 of file ObjectBrowserItem.h.
References pBrowserObject, and pdelete.
   {
     //      if (getType() != FIELDATTR) //To avoid cross reference/multi deletion
     pdelete(pBrowserObject);
   }
Member Function Documentation
void ObjectBrowserItem::attachKey ()
Definition at line 150 of file ObjectBrowserItem.cpp.
References KeySpace, and mKey.
Referenced by ObjectBrowserWidget::loadChild(), ObjectBrowserWidget::loadData(), and ObjectBrowserWidget::loadField().
 {
   mKey = QString::number(KeySpace++);
 }
static long ObjectBrowserItem::getKeySpace () inline static
Definition at line 90 of file ObjectBrowserItem.h.
References KeySpace.
Referenced by ObjectBrowserWidget::updateUI().
   {
     return KeySpace;
   }
CBrowserObject* ObjectBrowserItem::getObject () inline
Definition at line 95 of file ObjectBrowserItem.h.
References pBrowserObject.
Referenced by ObjectBrowserWidget::eXport(), ObjectBrowserWidget::partition(), ObjectBrowserWidget::removeDuplicate(), ObjectBrowserWidget::selectObjects(), and ObjectBrowserWidget::updateUI().
   {
     return pBrowserObject;
   }
objectType ObjectBrowserItem::getType () inline
Definition at line 128 of file ObjectBrowserItem.h.
References mType.
Referenced by ObjectBrowserWidget::eXport(), and ObjectBrowserWidget::selectObjects().
   {
     return mType;
   }
bool ObjectBrowserItem::isChecked () const
Definition at line 200 of file ObjectBrowserItem.cpp.
References CBrowserObject::mChecked, and pBrowserObject.
Referenced by ObjectBrowserWidget::clickToReverseCheck(), ObjectBrowserWidget::eXport(), nUserChecked(), ObjectBrowserWidget::setCheck(), and ObjectBrowserWidget::setUncheck().
 {
   return pBrowserObject->mChecked;
 }
virtual QString ObjectBrowserItem::key (int C_UNUSEDcolumn, bool C_UNUSEDascending) const inline virtual
Definition at line 100 of file ObjectBrowserItem.h.
References mKey.
Referenced by ObjectList::createBucketIndex(), ObjectList::delDuplicate(), ObjectList::insertBucket(), ObjectList::sortList(), and ObjectList::sortListInsert().
   {
     return mKey;
   }
QTreeWidgetItem * ObjectBrowserItem::nextSibling ()
Definition at line 210 of file ObjectBrowserItem.cpp.
Referenced by ObjectBrowserWidget::eXport(), nUserChecked(), ObjectBrowserWidget::selectObjects(), ObjectBrowserWidget::setCheck(), and ObjectBrowserWidget::setUncheck().
 {
   if (this->parent() == NULL)
     return NULL;
   else
     {
       int indexOfThisChild = this->parent()->indexOfChild(this);
       if (this->parent()->child(indexOfThisChild + 1))
         return this->parent()->child(indexOfThisChild + 1);
     }
   return NULL;
 }
int ObjectBrowserItem::nUserChecked ()
Definition at line 155 of file ObjectBrowserItem.cpp.
References ALLCHECKED, isChecked(), nextSibling(), NOCHECKED, nUserChecked(), and PARTCHECKED.
Referenced by nUserChecked(), and ObjectBrowserWidget::setCheckMark().
 {
   int condition;
   if (child(0))
     {
       ObjectBrowserItem* pChild = (ObjectBrowserItem *)child(0);
       condition = pChild->nUserChecked();
       for (; pChild != NULL; pChild = (ObjectBrowserItem *)pChild->nextSibling())
         {
           switch (pChild->nUserChecked())
             {
               case ALLCHECKED:
                 if (condition == NOCHECKED)
                   condition = PARTCHECKED;
                 break;
               case PARTCHECKED:
                 if (condition == NOCHECKED || condition == ALLCHECKED)
                   condition = PARTCHECKED;
                 break;
               case NOCHECKED:
                 if (condition == ALLCHECKED)
                   condition = PARTCHECKED;
                 break;
             }
         }
     }
   else //it has no child
     {
       if (isChecked())
         condition = ALLCHECKED;
       else
         condition = NOCHECKED;
     }
   return condition;
 }
static void ObjectBrowserItem::resetKeySpace () inline static
Definition at line 85 of file ObjectBrowserItem.h.
References KEYBASE, and KeySpace.
Referenced by ObjectBrowserWidget::ObjectBrowserWidget().
   {
     KeySpace = KEYBASE;
   }
void ObjectBrowserItem::reverseChecked ()
Definition at line 205 of file ObjectBrowserItem.cpp.
References CBrowserObject::mChecked, and pBrowserObject.
Referenced by ObjectBrowserWidget::clickToReverseCheck(), ObjectBrowserWidget::setCheck(), and ObjectBrowserWidget::setUncheck().
 {
   pBrowserObject->mChecked = !pBrowserObject->mChecked;
 }
void ObjectBrowserItem::setBrowserObject (CBrowserObject * updateObject) inline
Definition at line 123 of file ObjectBrowserItem.h.
References pBrowserObject.
Referenced by ObjectBrowserWidget::removeDuplicate(), and CBrowserObject::~CBrowserObject().
   {
     pBrowserObject = updateObject;
   }
void ObjectBrowserItem::setObjectType (objectType newType) inline
Definition at line 118 of file ObjectBrowserItem.h.
References mType.
Referenced by ObjectBrowserWidget::loadChild(), ObjectBrowserWidget::loadData(), and ObjectBrowserWidget::loadField().
   {
     mType = newType;
   }
Member Data Documentation
long ObjectBrowserItem::KeySpace = 0 static private
Definition at line 79 of file ObjectBrowserItem.h.
Referenced by attachKey(), getKeySpace(), and resetKeySpace().
QString ObjectBrowserItem::mKey private
Definition at line 82 of file ObjectBrowserItem.h.
Referenced by attachKey(), key(), and ObjectBrowserItem().
objectType ObjectBrowserItem::mType private
Definition at line 81 of file ObjectBrowserItem.h.
Referenced by getType(), and setObjectType().
CBrowserObject* ObjectBrowserItem::pBrowserObject private
Definition at line 80 of file ObjectBrowserItem.h.
Referenced by getObject(), isChecked(), ObjectBrowserItem(), reverseChecked(), setBrowserObject(), and ~ObjectBrowserItem().
The documentation for this class was generated from the following files:
ObjectBrowserItem.h
ObjectBrowserItem.cpp