COPASI API: CLLineEnding Class Reference
CLLineEnding Class Reference
#include <CLLineEnding.h>
Public Member Functions
CLLineEnding (CCopasiContainer *pParent=NULL)
CLLineEnding (const CLLineEnding &source, CCopasiContainer *pParent=NULL)
CLLineEnding (const LineEnding &source, CCopasiContainer *pParent=NULL)
CLBoundingBox * getBoundingBox ()
const CLBoundingBox * getBoundingBox () const
const CLGroup * getGroup () const
CLGroup * getGroup ()
const std::string & getId () const
bool getIsEnabledRotationalMapping () const
const std::string & getKey () const
void setBoundingBox (const CLBoundingBox *box)
void setEnableRotationalMapping (bool enable)
void setGroup (const CLGroup *group)
void setId (const std::string &id)
LineEnding * toSBML (unsigned int level, unsigned int version) const
Public Member Functions inherited from CLGraphicalPrimitive2D
virtual void addSBMLAttributes (GraphicalPrimitive2D *pPrimitive) const
CLGraphicalPrimitive2D ()
CLGraphicalPrimitive2D (const GraphicalPrimitive2D &source)
const std::string & getFillColor () const
FILL_RULE getFillRule () const
bool isSetFill () const
bool isSetFillRule () const
void setFillColor (const std::string &color)
void setFillRule (FILL_RULE rule)
Public Member Functions inherited from CLGraphicalPrimitive1D
virtual void addSBMLAttributes (GraphicalPrimitive1D *pPrimitive) const
CLGraphicalPrimitive1D ()
CLGraphicalPrimitive1D (const GraphicalPrimitive1D &source)
const std::vector< unsigned int > & getDashArray () const
const std::string & getStroke () const
double getStrokeWidth () const
bool isSetDashArray () const
bool isSetStroke () const
bool isSetStrokeWidth () const
void parseDashArray (const std::string &s)
void setDashArray (const std::vector< unsigned int > &array)
void setStroke (const std::string &key)
void setStrokeWidth (double width)
Public Member Functions inherited from CLTransformation2D
CLTransformation2D ()
CLTransformation2D (const double m[6])
CLTransformation2D (const Transformation2D &source)
std::string get2DTransformationString () const
const double * getMatrix2D () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
void setMatrix2D (const double m[6])
Public Member Functions inherited from CLTransformation
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
CLBoundingBox mBoundingBox
bool mEnableRotationalMapping
std::string mId
std::string mKey
CLGroup * mpGroup
Protected Attributes inherited from CLGraphicalPrimitive2D
std::string mFill
FILL_RULE mFillRule
Protected Attributes inherited from CLGraphicalPrimitive1D
std::string mStroke
std::vector< unsigned int > mStrokeDashArray
double mStrokeWidth
Protected Attributes inherited from CLTransformation2D
double mMatrix2D [6]
Protected Attributes inherited from CLTransformation
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
CLLineEnding & operator= (const CLLineEnding &source)
Additional Inherited Members
Public Types inherited from CLGraphicalPrimitive2D
enum FILL_RULE { UNSET, NONZERO, EVENODD, INHERIT }
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CLTransformation2D
static const double * getIdentityMatrix2D ()
Static Public Member Functions inherited from CLTransformation
static const double * getIdentityMatrix ()
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CLTransformation2D
static const double IDENTITY2D [6] = {1.0, 0.0, 0.0, 1.0, 0.0, 0.0}
Static Public Attributes inherited from CLTransformation
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CLTransformation2D
virtual void addSBMLAttributes (Transformation2D *pTransformation) const
void updateMatrix2D ()
void updateMatrix3D ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 26 of file CLLineEnding.h.
Constructor & Destructor Documentation
CLLineEnding::CLLineEnding (CCopasiContainer * pParent = NULL)
Constructor.
Definition at line 22 of file CLLineEnding.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                    :
   CLGraphicalPrimitive2D(),
   CCopasiContainer("LineEnding", pParent),
   mEnableRotationalMapping(false),
   mpGroup(NULL),
   mKey(""),
   mId("")
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("LineEnding", this);
 }
CLLineEnding::CLLineEnding (const CLLineEnding & source, CCopasiContainer * pParent = NULL)
Copy Constructor.
Definition at line 36 of file CLLineEnding.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), mKey, and mpGroup.
                                                                                :
   CLGraphicalPrimitive2D(source),
   CCopasiContainer(source, pParent),
   mEnableRotationalMapping(source.mEnableRotationalMapping),
   mBoundingBox(source.mBoundingBox),
   mpGroup(NULL),
   mKey(""),
   mId(source.mId)
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("LineEnding", this);
   if (source.mpGroup != NULL)
     {
       this->mpGroup = new CLGroup(*source.mpGroup, this);
     }
 }
CLLineEnding::CLLineEnding (const LineEnding & source, CCopasiContainer * pParent = NULL)
Constructor to generate object from the corresponding SBML object.
Definition at line 56 of file CLLineEnding.cpp.
References CKeyFactory::add(), CCopasiRootContainer::getKeyFactory(), and mKey.
                                                                              :
   CLGraphicalPrimitive2D(source),
   CCopasiContainer("LineEnding", pParent),
   mEnableRotationalMapping(source.getIsEnabledRotationalMapping()),
   mBoundingBox(*source.getBoundingBox()),
   mpGroup(new CLGroup(*source.getGroup(), this)),
   mKey(""),
   mId(source.getId())
 {
   this->mKey = CCopasiRootContainer::getKeyFactory()->add("LineEnding", this);
 }
Member Function Documentation
CLBoundingBox * CLLineEnding::getBoundingBox ()
Returns the bounding box.
Definition at line 95 of file CLLineEnding.cpp.
References mBoundingBox.
Referenced by addLineEndingToItem(), CLLayoutRenderer::map_arrow_head(), CCopasiXML::saveLineEnding(), CCopasiXMLParser::BoundingBoxElement::start(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return &this->mBoundingBox;
 }
const CLBoundingBox * CLLineEnding::getBoundingBox () const
Returns the bounding box.
Definition at line 103 of file CLLineEnding.cpp.
References mBoundingBox.
 {
   return &this->mBoundingBox;
 }
const CLGroup * CLLineEnding::getGroup () const
Returns the group object.
Definition at line 135 of file CLLineEnding.cpp.
References mpGroup.
Referenced by addLineEndingToItem(), fillItemFromRenderCurve(), CLLayoutRenderer::map_arrow_head(), CCopasiXML::saveLineEnding(), CCopasiXMLParser::GroupElement::start(), and CLLayoutRenderer::update_textures_and_colors().
 {
   return this->mpGroup;
 }
CLGroup * CLLineEnding::getGroup ()
Returns the group object.
Definition at line 127 of file CLLineEnding.cpp.
References mpGroup.
 {
   return this->mpGroup;
 }
const std::string & CLLineEnding::getId () const
Returns the id of the object.
Definition at line 151 of file CLLineEnding.cpp.
References mId.
Referenced by CLRenderResolver::fill_base_maps(), CLRenderFlattener::flatten(), and CCopasiXML::saveLineEnding().
 {
   return this->mId;
 }
bool CLLineEnding::getIsEnabledRotationalMapping () const
Returns whether rotational mapping is enabled or not.
Definition at line 79 of file CLLineEnding.cpp.
References mEnableRotationalMapping.
Referenced by applyRotationalMapping(), CLLayoutRenderer::map_arrow_head(), and CCopasiXML::saveLineEnding().
 {
   return this->mEnableRotationalMapping;
 }
const std::string & CLLineEnding::getKey () const virtual
Returns the key string for the line ending.
Reimplemented from CCopasiObject.
Definition at line 143 of file CLLineEnding.cpp.
References mKey.
 {
   return this->mKey;
 }
CLLineEnding& CLLineEnding::operator= (const CLLineEnding & source) private
void CLLineEnding::setBoundingBox (const CLBoundingBox * box)
Sets the bounding box.
Definition at line 87 of file CLLineEnding.cpp.
References mBoundingBox.
 {
   this->mBoundingBox = *box;
 }
void CLLineEnding::setEnableRotationalMapping (bool enable)
Sets whether rotational mapping is to be done or not.
Definition at line 71 of file CLLineEnding.cpp.
References mEnableRotationalMapping.
Referenced by CCopasiXMLParser::LineEndingElement::start().
 {
   this->mEnableRotationalMapping = enable;
 }
void CLLineEnding::setGroup (const CLGroup * pGroup)
Sets the group.
Definition at line 111 of file CLLineEnding.cpp.
References mpGroup.
Referenced by CCopasiXMLParser::GroupElement::start().
 {
   if (pGroup)
     {
       if (this->mpGroup != NULL)
         {
           delete this->mpGroup;
         }
       this->mpGroup = new CLGroup(*pGroup, this);
     }
 }
void CLLineEnding::setId (const std::string & id)
Sets the id of the object.
Definition at line 159 of file CLLineEnding.cpp.
References mId.
Referenced by CCopasiXMLParser::LineEndingElement::start().
 {
   this->mId = id;
 }
LineEnding * CLLineEnding::toSBML (unsigned int level, unsigned int version) const
Converts this object to the corresponding SBML object.
Definition at line 167 of file CLLineEnding.cpp.
References CLGraphicalPrimitive2D::addSBMLAttributes(), CLBoundingBox::getDimensions(), CLDimensions::getHeight(), CLBoundingBox::getPosition(), CLDimensions::getWidth(), CLPoint::getX(), CLPoint::getY(), mBoundingBox, mEnableRotationalMapping, mId, mpGroup, and CLGroup::toSBML().
Referenced by CLRenderInformationBase::addSBMLAttributes().
 {
   LineEnding* pLE = new LineEnding(level, version);
   this->addSBMLAttributes(pLE);
   pLE->setId(this->mId);
   pLE->setEnableRotationalMapping(this->mEnableRotationalMapping);
   BoundingBox bb(level, version);
   bb.setId("bb");
   Point p(new LayoutPkgNamespaces(),
           this->mBoundingBox.getPosition().getX(),
           this->mBoundingBox.getPosition().getY());
   bb.setPosition(&p);
   Dimensions d(new LayoutPkgNamespaces(),
                this->mBoundingBox.getDimensions().getWidth(),
                this->mBoundingBox.getDimensions().getHeight());
   bb.setDimensions(&d);
   pLE->setBoundingBox(&bb);
   const RenderGroup* pG = this->mpGroup->toSBML(level, version);
   pLE->setGroup(pG);
   delete pG;
   return pLE;
 }
Member Data Documentation
CLBoundingBox CLLineEnding::mBoundingBox protected
Definition at line 34 of file CLLineEnding.h.
Referenced by getBoundingBox(), setBoundingBox(), and toSBML().
bool CLLineEnding::mEnableRotationalMapping protected
Definition at line 33 of file CLLineEnding.h.
Referenced by getIsEnabledRotationalMapping(), setEnableRotationalMapping(), and toSBML().
std::string CLLineEnding::mId protected
The line ending needs an id in addition to the key. The id corresponds to the id in the SBML render extension and it does not have to be globally unique. As a matter of fact, it is sometimes needed that line ending of different render information have the same id.
Definition at line 48 of file CLLineEnding.h.
Referenced by getId(), setId(), and toSBML().
std::string CLLineEnding::mKey protected
key string for the object.
Definition at line 40 of file CLLineEnding.h.
Referenced by CLLineEnding(), and getKey().
CLGroup* CLLineEnding::mpGroup protected
Definition at line 35 of file CLLineEnding.h.
Referenced by CLLineEnding(), getGroup(), setGroup(), and toSBML().
The documentation for this class was generated from the following files:
CLLineEnding.h
CLLineEnding.cpp