COPASI API: CRDFSubject.cpp File Reference
CRDFSubject.cpp File Reference
#include "copasi.h"
#include "CRDFSubject.h"
Functions
std::ostream & operator<< (std::ostream &os, const CRDFSubject &subject)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CRDFSubject & subject)
Definition at line 102 of file CRDFSubject.cpp.
References CRDFSubject::BLANK_NODE, CRDFSubject::getBlankNodeID(), CRDFSubject::getResource(), CRDFSubject::getType(), and CRDFSubject::RESOURCE.
 {
   switch (subject.getType())
     {
     case CRDFSubject::BLANK_NODE:
       os << subject.getBlankNodeID();
       break;
     case CRDFSubject::RESOURCE:
       os << subject.getResource();
       break;
     }
   return os;
 }