COPASI API: CCopasiXMLParser::CompartmentGlyphElement Class Reference
CCopasiXMLParser::CompartmentGlyphElement Class Reference
Public Member Functions
CompartmentGlyphElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *pszName)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~CompartmentGlyphElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element { CompartmentGlyph = 0, BoundingBox, Position, Dimensions }
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 3316 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::CompartmentGlyphElement::Element private
Enumerator
CompartmentGlyph
BoundingBox
Position
Dimensions
Definition at line 3319 of file CCopasiXMLParser.h.
     {
       CompartmentGlyph = 0,
       BoundingBox,
       Position,
       Dimensions
     };
Constructor & Destructor Documentation
CCopasiXMLParser::CompartmentGlyphElement::CompartmentGlyphElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Definition at line 6495 of file CCopasiXMLParser.cpp.
                                                                                                                          :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::CompartmentGlyphElement::~CompartmentGlyphElement () virtual
Definition at line 6500 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::CompartmentGlyphElement::end (const XML_Char * pszName) virtual
Definition at line 6605 of file CCopasiXMLParser.cpp.
References CCopasiMessage::EXCEPTION, MCXML, CExpatTemplate< CExpat >::mParser, START_ELEMENT, and UNKNOWN_ELEMENT.
 {
   if (!strcmp(pszName, "CompartmentGlyph"))
     {
       mParser.popElementHandler();
       mCurrentElement = START_ELEMENT;
       /* Tell the parent element we are done. */
       mParser.onEndElement(pszName);
     }
   else
     {
       switch (mCurrentElement)
         {
           case BoundingBox:
             break;
           case Position:
             break;
           case Dimensions:
             //tell the handler where to continue
             mCurrentElement = BoundingBox;
             break;
           case UNKNOWN_ELEMENT:
             mCurrentElement = CompartmentGlyph;
             break;
           default:
             CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                            pszName, "???", mParser.getCurrentLineNumber());
             break;
         }
     }
   return;
 }
void CCopasiXMLParser::CompartmentGlyphElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Definition at line 6503 of file CCopasiXMLParser.cpp.
References CLayout::addCompartmentGlyph(), CCopasiMessage::EXCEPTION, CKeyFactory::get(), CModelEntity::getKey(), SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCompartmentGlyph, SCopasiXMLParserCommon::pCurrentLayout, CLGraphicalObject::setHeight(), CLGraphicalObject::setModelObjectKey(), CLGraphicalObject::setObjectRole(), CLGraphicalObject::setWidth(), CLGraphicalObject::setX(), CLGraphicalObject::setY(), UNKNOWN_ELEMENT, and CCopasiMessage::WARNING.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   switch (mCurrentElement)
     {
       case CompartmentGlyph:
         if (strcmp(pszName, "CompartmentGlyph"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "CompartmentGlyph", mParser.getCurrentLineNumber());
         {
           //workload
           const char * key;
           const char * name;
           const char * compartment;
           key = mParser.getAttributeValue("key", papszAttrs);
           name = mParser.getAttributeValue("name", papszAttrs);
           compartment = mParser.getAttributeValue("compartment", papszAttrs);
           mCommon.pCompartmentGlyph = new CLCompartmentGlyph(name);
           const char * objectRole = mParser.getAttributeValue("objectRole", papszAttrs, false);
           if (objectRole != NULL && objectRole[0] != 0)
             {
               mCommon.pCompartmentGlyph->setObjectRole(objectRole);
             }
           if (compartment && compartment[0])
             {
               CCompartment * pComp = dynamic_cast< CCompartment * >(mCommon.KeyMap.get(compartment));
               if (!pComp)
                 {
                   CCopasiMessage(CCopasiMessage::WARNING, MCXML + 19 , "CompartmentGlyph", key);
                 }
               else
                 {
                   mCommon.pCompartmentGlyph->setModelObjectKey(pComp->getKey());
                 }
             }
           mCommon.pCurrentLayout->addCompartmentGlyph(mCommon.pCompartmentGlyph);
           addFix(key, mCommon.pCompartmentGlyph);
         }
         return;
         break;
       case BoundingBox:
         if (!strcmp(pszName, "BoundingBox"))
           return;
         break;
       case Position:
         if (!strcmp(pszName, "Position"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("x", papszAttrs);
             mCommon.pCompartmentGlyph->setX(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("y", papszAttrs);
             mCommon.pCompartmentGlyph->setY(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       case Dimensions:
         if (!strcmp(pszName, "Dimensions"))
           {
             //workload
             const char * attr;
             attr = mParser.getAttributeValue("width", papszAttrs);
             mCommon.pCompartmentGlyph->setWidth(CCopasiXMLInterface::DBL(attr));
             attr = mParser.getAttributeValue("height", papszAttrs);
             mCommon.pCompartmentGlyph->setHeight(CCopasiXMLInterface::DBL(attr));
             return;
           }
         break;
       default:
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::CompartmentGlyphElement::mLineNumber private
Definition at line 3327 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp