COPASI API: CScanItemRandom Class Reference
CScanItemRandom Class Reference
#include <CScanMethod.h>
Public Member Functions
CScanItemRandom (CCopasiParameterGroup *si, CRandom *rg, const bool &continueFromCurrentState)
virtual bool isNesting () const
virtual void step ()
virtual ~CScanItemRandom ()
Public Member Functions inherited from CScanItem
size_t getNumSteps () const
const CCopasiObject * getObject () const
bool isFinished () const
virtual bool isValidScanItem (const bool &continueFromCurrentState)
void reset ()
void restoreValue () const
void storeValue ()
virtual ~CScanItem ()
Private Attributes
C_FLOAT64 mFaktor
bool mLog
C_FLOAT64 mMax
C_FLOAT64 mMin
unsigned C_INT32 mRandomType
CRandom * mRg
Additional Inherited Members
Static Public Member Functions inherited from CScanItem
static CScanItem * createScanItemFromParameterGroup (CCopasiParameterGroup *si, CRandom *rg, const bool &continueFromCurrentState)
Protected Member Functions inherited from CScanItem
CScanItem (CCopasiParameterGroup *si, const bool &continueFromCurrentState)
Protected Attributes inherited from CScanItem
bool mFlagFinished
size_t mIndex
bool mIsStateVariable
size_t mNumSteps
CCopasiObject * mpInitialObject
CCopasiObject * mpObject
C_FLOAT64 mStoreValue
Detailed Description
Definition at line 128 of file CScanMethod.h.
Constructor & Destructor Documentation
CScanItemRandom::CScanItemRandom (CCopasiParameterGroup * si, CRandom * rg, const bool & continueFromCurrentState)
Definition at line 267 of file CScanMethod.cpp.
References CCopasiParameterGroup::getValue(), mFaktor, mLog, mMax, mMin, CScanItem::mNumSteps, mRandomType, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pDOUBLE, and CCopasiParameter::Value::pUINT.
                                                                        :
   CScanItem(si, continueFromCurrentState),
   mRg(rg),
   mRandomType(0),
   mLog(false)
 {
   mRandomType = * si->getValue("Distribution type").pUINT;
   mLog = * si->getValue("log").pBOOL;
   mMin = * si->getValue("Minimum").pDOUBLE;
   mMax = * si->getValue("Maximum").pDOUBLE;
   if (mLog && mRandomType == 0)
     {
       mMin = log(mMin);
       mMax = log(mMax);
     }
   mNumSteps = 0;
   mFaktor = (mMax - mMin);
 }
virtual CScanItemRandom::~CScanItemRandom () inline virtual
Definition at line 137 of file CScanMethod.h.
 {};
Member Function Documentation
virtual bool CScanItemRandom::isNesting () const inline virtual
Reimplemented from CScanItem.
Definition at line 140 of file CScanMethod.h.
 {return false;};
void CScanItemRandom::step () virtual
Implements CScanItem.
Definition at line 290 of file CScanMethod.cpp.
References C_FLOAT64, CRandom::getRandomCC(), CRandom::getRandomGamma(), CRandom::getRandomNormal01(), CRandom::getRandomPoisson(), mFaktor, CScanItem::mFlagFinished, CScanItem::mIndex, mLog, mMax, mMin, CScanItem::mNumSteps, CScanItem::mpInitialObject, CScanItem::mpObject, mRandomType, mRg, CCopasiObject::setObjectValue(), and CCopasiMessage::WARNING.
 {
   C_FLOAT64 Value;
   //the index
   if (mIndex > mNumSteps)
     mFlagFinished = true;
   else
     {
       C_FLOAT64 tmpF;
       switch (mRandomType)
         {
           case 0: // uniform
             Value = mMin + mRg->getRandomCC() * mFaktor;
             if (mLog)
               Value = exp(Value);
             break;
           case 1: // normal
             tmpF = mRg->getRandomNormal01();
             Value = mMin + tmpF * mMax;
             if (mLog)
               Value = exp(Value);
             break;
           case 2: // poisson
             if (mMin < 0)
               CCopasiMessage(CCopasiMessage::WARNING, "Invalid ScanItem: Requested Poisson random variable for negative argument: %lf", mMin);
             Value = mRg->getRandomPoisson(mMin);
             break;
           case 3: // gamma
             Value = mRg->getRandomGamma(mMin, mMax);
             if (mLog)
               Value = exp(Value);
             break;
         }
     }
   if (mpObject) mpObject->setObjectValue(Value);
   if (mpInitialObject) mpInitialObject->setObjectValue(Value);
   ++mIndex;
 }
Member Data Documentation
C_FLOAT64 CScanItemRandom::mFaktor private
Definition at line 131 of file CScanMethod.h.
Referenced by CScanItemRandom(), and step().
bool CScanItemRandom::mLog private
Definition at line 134 of file CScanMethod.h.
Referenced by CScanItemRandom(), and step().
C_FLOAT64 CScanItemRandom::mMax private
Definition at line 131 of file CScanMethod.h.
Referenced by CScanItemRandom(), and step().
C_FLOAT64 CScanItemRandom::mMin private
Definition at line 131 of file CScanMethod.h.
Referenced by CScanItemRandom(), and step().
unsigned C_INT32 CScanItemRandom::mRandomType private
Definition at line 133 of file CScanMethod.h.
Referenced by CScanItemRandom(), and step().
CRandom* CScanItemRandom::mRg private
Definition at line 132 of file CScanMethod.h.
Referenced by step().
The documentation for this class was generated from the following files:
CScanMethod.h
CScanMethod.cpp