COPASI API: test000100 Class Reference
test000100 Class Reference
#include <test000100.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_bug1692_1 ()
void test_bug1692_2 ()
Protected Attributes
CCopasiDataModel * pDataModel
Static Protected Attributes
static const char * CPS_STRING
Private Member Functions
CPPUNIT_TEST (test_bug1692_1)
CPPUNIT_TEST (test_bug1692_2)
CPPUNIT_TEST_SUITE (test000100)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 29 of file test000100.h.
Member Function Documentation
test000100::CPPUNIT_TEST (test_bug1692_1) private
test000100::CPPUNIT_TEST (test_bug1692_2) private
test000100::CPPUNIT_TEST_SUITE (test000100) private
test000100::CPPUNIT_TEST_SUITE_END () private
void test000100::setUp ()
Definition at line 42 of file test000100.cpp.
References abort_handler(), CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), pDataModel, pNewAct, and pOldAct.
 {
 #ifndef WIN32
   // set a new action handler for SIGABRT that throws an exception
   // instead of terminating the program. This is needed to handle failed assertions
   // in debug versions.
   pNewAct = new struct sigaction();
   pNewAct->sa_handler = &abort_handler;
   pOldAct = new struct sigaction();
   int x = sigaction(SIGABRT, pNewAct, pOldAct);
   if (x != 0)
     {
       std::cerr << "Setting the signal handler failed." << std::endl;
     }
 #endif
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   pDataModel = CCopasiRootContainer::addDatamodel();
 }
void test000100::tearDown ()
Definition at line 64 of file test000100.cpp.
References CCopasiRootContainer::destroy(), and pOldAct.
 {
   CCopasiRootContainer::destroy();
 #ifndef WIN32
   // restore the old action handler
   int x = sigaction(SIGABRT, pOldAct, NULL);
   if (x != 0)
     {
       std::cerr << "Resetting the signal handler failed." << std::endl;
     }
 #endif
 }
void test000100::test_bug1692_1 ()
Definition at line 81 of file test000100.cpp.
References CPS_STRING, CCopasiDataModel::exportSBMLToString(), load_cps_model_from_stream(), and pDataModel.
 {
   CPPUNIT_ASSERT(pDataModel != NULL);
   std::istringstream iss(test000100::CPS_STRING);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   std::string s;
   try
     {
       s = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("The first export to Level 2 Version 1 failed.", false);
     }
   try
     {
       s = pDataModel->exportSBMLToString(NULL, 3, 1);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("The second export to Level 3 Version 1 failed.", false);
     }
 }
void test000100::test_bug1692_2 ()
Definition at line 109 of file test000100.cpp.
References CPS_STRING, CCopasiDataModel::exportSBMLToString(), load_cps_model_from_stream(), and pDataModel.
 {
   CPPUNIT_ASSERT(pDataModel != NULL);
   std::istringstream iss(test000100::CPS_STRING);
   CPPUNIT_ASSERT(load_cps_model_from_stream(iss, *pDataModel) == true);
   std::string s;
   try
     {
       s = pDataModel->exportSBMLToString(NULL, 3, 1);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("The first export to Level 3 Version 1 failed.", false);
     }
   try
     {
       s = pDataModel->exportSBMLToString(NULL, 2, 1);
     }
   catch (...)
     {
       CPPUNIT_ASSERT_MESSAGE("The second export to Level 2 Version 1 failed.", false);
     }
 }
Member Data Documentation
const char * test000100::CPS_STRING static protected
Definition at line 40 of file test000100.h.
Referenced by test_bug1692_1(), and test_bug1692_2().
CCopasiDataModel* test000100::pDataModel protected
Definition at line 42 of file test000100.h.
Referenced by setUp(), test_bug1692_1(), and test_bug1692_2().
The documentation for this class was generated from the following files:
test000100.h
test000100.cpp