COPASI API: CQLayoutView Class Reference
CQLayoutView Class Reference
#include <CQLayoutView.h>
Public Slots
void slotFitOnScreen ()
void slotLayoutChanged (int)
void slotRenderInformationChanged (int)
void slotResetZoom ()
void slotSaveToFile (const QString &fileName)
void slotZoomIn ()
void slotZoomOut ()
Public Member Functions
CQLayoutView (QWidget *parent=NULL)
CQLayoutView (CQLayoutScene *scene)
void fillSelectionToolBar (QToolBar *toolBar)
void fillZoomMenu (QMenu *menu)
void fillZoomTooBar (QToolBar *toolBar)
CCopasiDataModel * getDataModel ()
void setDataModel (CCopasiDataModel *dataModel, CLayout *layout=NULL)
virtual ~CQLayoutView ()
Protected Member Functions
void wheelEvent (QWheelEvent *event)
Protected Attributes
bool mIgnoreEvents
QAction * mpActFitOnScreen
QAction * mpActResetZoom
QAction * mpActZoomIn
QAction * mpActZoomOut
CCopasiDataModel * mpDataModel
QComboBox * mpLayoutDropdown
QComboBox * mpRenderDropdown
double mScaleFactor
Private Member Functions
void createActions ()
Detailed Description
Definition at line 19 of file CQLayoutView.h.
Constructor & Destructor Documentation
CQLayoutView::CQLayoutView (QWidget * parent = NULL)
Definition at line 219 of file CQLayoutView.cpp.
References createActions().
   : QGraphicsView(parent)
   , mScaleFactor(1.15)
   , mIgnoreEvents(false)
 {
   setDragMode(QGraphicsView::ScrollHandDrag);
   createActions();
 }
CQLayoutView::CQLayoutView (CQLayoutScene * scene)
Definition at line 240 of file CQLayoutView.cpp.
References createActions().
   : QGraphicsView(scene)
   , mScaleFactor(1.15)
   , mIgnoreEvents(false)
 {
   setDragMode(QGraphicsView::ScrollHandDrag);
   createActions();
 }
CQLayoutView::~CQLayoutView () virtual
Definition at line 26 of file CQLayoutView.cpp.
 {
 }
Member Function Documentation
void CQLayoutView::createActions () private
Definition at line 270 of file CQLayoutView.cpp.
References CQIconResource::icon(), mpActFitOnScreen, mpActResetZoom, mpActZoomIn, mpActZoomOut, mpLayoutDropdown, mpRenderDropdown, slotFitOnScreen(), slotLayoutChanged(), slotRenderInformationChanged(), slotResetZoom(), slotZoomIn(), slotZoomOut(), CQIconResource::viewmag1, CQIconResource::viewmagfit, CQIconResource::viewmagMinus, and CQIconResource::viewmagPlus.
Referenced by CQLayoutView().
 {
   mpActFitOnScreen = new QAction(tr("Fit On Screen"), this);
   mpActFitOnScreen->setShortcut(QKeySequence::fromString("F5"));
   mpActFitOnScreen->setIcon(CQIconResource::icon(CQIconResource::viewmagfit));
   connect(mpActFitOnScreen, SIGNAL(triggered()), this, SLOT(slotFitOnScreen()));
   addAction(mpActFitOnScreen);
   mpActResetZoom = new QAction(tr("Reset Zoom"), this);
   mpActResetZoom->setIcon(CQIconResource::icon(CQIconResource::viewmag1));
   connect(mpActResetZoom, SIGNAL(triggered()), this, SLOT(slotResetZoom()));
   addAction(mpActResetZoom);
   mpActZoomIn = new QAction(tr("Zoom In"), this);
   mpActZoomIn->setIcon(CQIconResource::icon(CQIconResource::viewmagPlus));
   mpActZoomIn->setShortcut(QKeySequence::ZoomIn);
   connect(mpActZoomIn, SIGNAL(triggered()), this, SLOT(slotZoomIn()));
   addAction(mpActZoomIn);
   mpActZoomOut = new QAction(tr("Zoom Out"), this);
   mpActZoomOut->setIcon(CQIconResource::icon(CQIconResource::viewmagMinus));
   mpActZoomOut->setShortcut(QKeySequence::ZoomOut);
   connect(mpActZoomOut, SIGNAL(triggered()), this, SLOT(slotZoomOut()));
   addAction(mpActZoomOut);
   mpLayoutDropdown = new QComboBox;
   mpLayoutDropdown->setSizeAdjustPolicy(QComboBox::AdjustToContentsOnFirstShow);
   mpRenderDropdown = new QComboBox;
   mpRenderDropdown->setSizeAdjustPolicy(QComboBox::AdjustToContentsOnFirstShow);
   connect(mpLayoutDropdown, SIGNAL(currentIndexChanged(int)), this, SLOT(slotLayoutChanged(int)));
   connect(mpRenderDropdown, SIGNAL(currentIndexChanged(int)), this, SLOT(slotRenderInformationChanged(int)));
   setInteractive(true);
   setRenderHints(QPainter::Antialiasing);
 }
void CQLayoutView::fillSelectionToolBar (QToolBar * toolBar)
Definition at line 308 of file CQLayoutView.cpp.
References mpLayoutDropdown, and mpRenderDropdown.
 {
   QFrame* pFrame1 = new QFrame;
   QHBoxLayout* pLayout = new QHBoxLayout;
   pLayout->setSpacing(3);
   pFrame1->setLayout(pLayout);
   QLabel* pLabel = new QLabel(tr("Layout:"));
   pLayout->addWidget(pLabel);
   pLayout->addWidget(mpLayoutDropdown);
   QFrame* pFrame2 = new QFrame;
   pLayout = new QHBoxLayout;
   pLayout->setSpacing(3);
   pFrame2->setLayout(pLayout);
   QLabel* mpRenderLabel = new QLabel(tr("Render Information:"));
   pLayout->addWidget(mpRenderLabel);
   pLayout->addWidget(mpRenderDropdown);
   toolBar->addWidget(pFrame1);
   toolBar->addWidget(pFrame2);
 }
void CQLayoutView::fillZoomMenu (QMenu * menu)
Definition at line 250 of file CQLayoutView.cpp.
References mpActFitOnScreen, mpActResetZoom, mpActZoomIn, and mpActZoomOut.
 {
   if (menu == NULL) return;
   menu->addAction(mpActFitOnScreen);
   menu->addAction(mpActZoomIn);
   menu->addAction(mpActZoomOut);
   menu->addAction(mpActResetZoom);
 }
void CQLayoutView::fillZoomTooBar (QToolBar * toolBar)
Definition at line 260 of file CQLayoutView.cpp.
References mpActFitOnScreen, mpActResetZoom, mpActZoomIn, and mpActZoomOut.
 {
   if (toolBar == NULL) return;
   toolBar->addAction(mpActFitOnScreen);
   toolBar->addAction(mpActZoomIn);
   toolBar->addAction(mpActZoomOut);
   toolBar->addAction(mpActResetZoom);
 }
CCopasiDataModel * CQLayoutView::getDataModel ()
Definition at line 354 of file CQLayoutView.cpp.
References mpDataModel.
 {
   return mpDataModel;
 }
void CQLayoutView::setDataModel (CCopasiDataModel * dataModel, CLayout * layout = NULL)
Definition at line 359 of file CQLayoutView.cpp.
References CCopasiObject::getObjectName(), mpDataModel, mpLayoutDropdown, mpRenderDropdown, updateLayoutList(), and updateRenderInformationList().
 {
   mpDataModel = dataModel;
   updateLayoutList(mpLayoutDropdown, dataModel);
   if (layout != NULL)
     mpLayoutDropdown->setCurrentIndex(mpLayoutDropdown->findText(layout->getObjectName().c_str()));
   updateRenderInformationList(mpRenderDropdown, dataModel, layout);
 }
void CQLayoutView::slotFitOnScreen () slot
Definition at line 330 of file CQLayoutView.cpp.
Referenced by createActions().
 {
   setTransformationAnchor(QGraphicsView::AnchorUnderMouse);
   fitInView(scene()->itemsBoundingRect(), Qt::KeepAspectRatio);
   update();
 }
void CQLayoutView::slotLayoutChanged (int index) slot
Definition at line 188 of file CQLayoutView.cpp.
References CQLayoutScene::getCurrentLayout(), CLRenderInformationBase::getKey(), CCopasiDataModel::getListOfLayouts(), CLRenderInformationBase::getName(), mIgnoreEvents, mpDataModel, mpRenderDropdown, CQLayoutScene::recreate(), CQLayoutScene::setLayout(), and updateRenderInformationList().
Referenced by createActions().
 {
   if (mIgnoreEvents || index < 0) return;
   if (mpDataModel == NULL) return;
   CQLayoutScene* current = dynamic_cast<CQLayoutScene*>(scene());
   if (current == NULL) return;
   CLayout* layout  = (*mpDataModel->getListOfLayouts())[index];
   if (layout == NULL || layout == current->getCurrentLayout()) return;
   mIgnoreEvents = true;
   // update the corresponding render information list
   CLRenderInformationBase* render = updateRenderInformationList(mpRenderDropdown, mpDataModel, layout);
   if (render != NULL)
     {
       if (render->getName().empty())
         mpRenderDropdown->setCurrentIndex(mpRenderDropdown->findText(render->getKey().c_str()));
       else
         mpRenderDropdown->setCurrentIndex(mpRenderDropdown->findText(render->getName().c_str()));
     }
   mIgnoreEvents  = false;
   current->setLayout(layout, mpDataModel, render);
   current->recreate();
 }
void CQLayoutView::slotRenderInformationChanged (int index) slot
Definition at line 149 of file CQLayoutView.cpp.
References CQLayoutScene::getCurrentLayout(), getDefaultStyle(), CListOfLayouts::getListOfGlobalRenderInformationObjects(), CCopasiDataModel::getListOfLayouts(), CLayout::getListOfLocalRenderInformationObjects(), getNumDefaultStyles(), mIgnoreEvents, mpDataModel, CQLayoutScene::recreate(), CQLayoutScene::setRenderInformation(), and CCopasiVector< T >::size().
Referenced by createActions().
 {
   if (mIgnoreEvents || index < 0) return;
   if (mpDataModel == NULL) return;
   CQLayoutScene* current = dynamic_cast<CQLayoutScene*>(scene());
   if (current == NULL || current->getCurrentLayout() == NULL) return;
   CLRenderInformationBase* render  = NULL;
   int numLocal = current->getCurrentLayout()->getListOfLocalRenderInformationObjects().size();
   if (numLocal > index)
     {
       render  = current->getCurrentLayout()->getListOfLocalRenderInformationObjects()[index];
     }
   int numGlobal = mpDataModel->getListOfLayouts()->getListOfGlobalRenderInformationObjects().size();
   if (render == NULL && numLocal + numGlobal > index)
     {
       render = mpDataModel->getListOfLayouts()->getListOfGlobalRenderInformationObjects()[index - numLocal];
     }
   size_t numDefault = getNumDefaultStyles();
   if (render == NULL && numLocal + numGlobal + numDefault > (size_t)index)
     {
       render = getDefaultStyle(index - numGlobal - numLocal);
     }
   if (render == NULL)
     return;
   current->setRenderInformation(mpDataModel, render);
   current->recreate();
 }
void CQLayoutView::slotResetZoom () slot
Definition at line 336 of file CQLayoutView.cpp.
Referenced by createActions().
 {
   setTransformationAnchor(QGraphicsView::AnchorUnderMouse);
   resetMatrix();
   ensureVisible(scene()->itemsBoundingRect());
   update();
 }
void CQLayoutView::slotSaveToFile (const QString & fileName) slot
Definition at line 228 of file CQLayoutView.cpp.
References CQLayoutScene::saveToFile().
 {
   CQLayoutScene* layoutScene =  dynamic_cast<CQLayoutScene*>(scene());
   if (layoutScene == NULL) return;
   layoutScene->saveToFile(
     fileName.toStdString(),
     QFileInfo(fileName).suffix().toStdString()
   );
 }
void CQLayoutView::slotZoomIn () slot
Definition at line 343 of file CQLayoutView.cpp.
References mScaleFactor.
Referenced by createActions(), and wheelEvent().
 {
   setTransformationAnchor(QGraphicsView::AnchorUnderMouse);
   scale(mScaleFactor, mScaleFactor);
 }
void CQLayoutView::slotZoomOut () slot
Definition at line 348 of file CQLayoutView.cpp.
References mScaleFactor.
Referenced by createActions(), and wheelEvent().
 {
   setTransformationAnchor(QGraphicsView::AnchorUnderMouse);
   scale(1.0 / mScaleFactor, 1.0 / mScaleFactor);
 }
void CQLayoutView::wheelEvent (QWheelEvent * event) protected
Definition at line 371 of file CQLayoutView.cpp.
References slotZoomIn(), and slotZoomOut().
 {
   if (QApplication::keyboardModifiers() == Qt::ControlModifier ||
       QApplication::keyboardModifiers() == Qt::MetaModifier ||
       QApplication::keyboardModifiers() == Qt::ShiftModifier)
     {
       if (event->delta() > 0)
         {
           // Zoom in
           slotZoomIn();
         }
       else
         {
           // Zooming out
           slotZoomOut();
         }
     }
   else
     {
       QGraphicsView::wheelEvent(event);
     }
 }
Member Data Documentation
bool CQLayoutView::mIgnoreEvents protected
Definition at line 51 of file CQLayoutView.h.
Referenced by slotLayoutChanged(), and slotRenderInformationChanged().
QAction* CQLayoutView::mpActFitOnScreen protected
Definition at line 46 of file CQLayoutView.h.
Referenced by createActions(), fillZoomMenu(), and fillZoomTooBar().
QAction* CQLayoutView::mpActResetZoom protected
Definition at line 47 of file CQLayoutView.h.
Referenced by createActions(), fillZoomMenu(), and fillZoomTooBar().
QAction* CQLayoutView::mpActZoomIn protected
Definition at line 44 of file CQLayoutView.h.
Referenced by createActions(), fillZoomMenu(), and fillZoomTooBar().
QAction* CQLayoutView::mpActZoomOut protected
Definition at line 45 of file CQLayoutView.h.
Referenced by createActions(), fillZoomMenu(), and fillZoomTooBar().
CCopasiDataModel* CQLayoutView::mpDataModel protected
Definition at line 52 of file CQLayoutView.h.
Referenced by getDataModel(), setDataModel(), slotLayoutChanged(), and slotRenderInformationChanged().
QComboBox* CQLayoutView::mpLayoutDropdown protected
Definition at line 49 of file CQLayoutView.h.
Referenced by createActions(), fillSelectionToolBar(), and setDataModel().
QComboBox* CQLayoutView::mpRenderDropdown protected
Definition at line 50 of file CQLayoutView.h.
Referenced by createActions(), fillSelectionToolBar(), setDataModel(), and slotLayoutChanged().
double CQLayoutView::mScaleFactor protected
Definition at line 48 of file CQLayoutView.h.
Referenced by slotZoomIn(), and slotZoomOut().
The documentation for this class was generated from the following files:
CQLayoutView.h
CQLayoutView.cpp