COPASI API: CEFMProblem Class Reference
CEFMProblem Class Reference
#include <CEFMProblem.h>
Public Member Functions
CEFMProblem (const CCopasiContainer *pParent=NULL)
CEFMProblem (const CEFMProblem &src, const CCopasiContainer *pParent=NULL)
virtual bool elevateChildren ()
const std::vector< CFluxMode > & getFluxModes () const
std::vector< CFluxMode > & getFluxModes ()
const std::vector< const
CReaction * > & getReorderedReactions () const
std::vector< const CReaction * > & getReorderedReactions ()
virtual bool initialize ()
virtual void printResult (std::ostream *ostream) const
virtual bool setCallBack (CProcessReport *pCallBack)
virtual ~CEFMProblem ()
Public Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiProblem &src, const CCopasiContainer *pParent=NULL)
CModel * getModel () const
const CCopasiTask::Type & getType () const
virtual void print (std::ostream *ostream) const
virtual bool restore (const bool &updateModel)
virtual bool setModel (CModel *pModel)
virtual ~CCopasiProblem ()
Public Member Functions inherited from CCopasiParameterGroup
bool addGroup (const std::string &name)
bool addParameter (const CCopasiParameter &parameter)
bool addParameter (const std::string &name, const CCopasiParameter::Type type)
template<class CType >
bool addParameter (const std::string &name, const CCopasiParameter::Type type, const CType &value)
void addParameter (CCopasiParameter *pParameter)
CCopasiParameterGroup * assertGroup (const std::string &name)
template<class CType >
CCopasiParameter * assertParameter (const std::string &name, const CCopasiParameter::Type type, const CType &defaultValue)
index_iterator beginIndex () const
name_iterator beginName () const
CCopasiParameterGroup (const CCopasiParameterGroup &src, const CCopasiContainer *pParent=NULL)
CCopasiParameterGroup (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &objectType="ParameterGroup")
void clear ()
index_iterator endIndex () const
name_iterator endName () const
CCopasiParameterGroup * getGroup (const std::string &name)
const CCopasiParameterGroup * getGroup (const std::string &name) const
CCopasiParameterGroup * getGroup (const size_t &index)
const CCopasiParameterGroup * getGroup (const size_t &index) const
size_t getIndex (const std::string &name) const
std::string getKey (const std::string &name) const
std::string getKey (const size_t &index) const
virtual const std::string & getName (const size_t &index) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
CCopasiParameter * getParameter (const std::string &name)
const CCopasiParameter * getParameter (const std::string &name) const
CCopasiParameter * getParameter (const size_t &index)
const CCopasiParameter * getParameter (const size_t &index) const
CCopasiParameter::Type getType (const std::string &name) const
CCopasiParameter::Type getType (const size_t &index) const
std::string getUniqueParameterName (const CCopasiParameter *pParameter) const
const CCopasiParameter::Value & getValue (const std::string &name) const
const CCopasiParameter::Value & getValue (const size_t &index) const
CCopasiParameter::Value & getValue (const std::string &name)
CCopasiParameter::Value & getValue (const size_t &index)
CCopasiParameterGroup & operator= (const CCopasiParameterGroup &rhs)
bool removeParameter (const std::string &name)
bool removeParameter (const size_t &index)
template<class CType >
bool setValue (const std::string &name, const CType &value)
template<class CType >
bool setValue (const size_t &index, const CType &value)
size_t size () const
bool swap (const size_t &iFrom, const size_t &iTo)
bool swap (index_iterator &from, index_iterator &to)
virtual ~CCopasiParameterGroup ()
Public Member Functions inherited from CCopasiParameter
CCopasiParameter (const CCopasiParameter &src, const CCopasiContainer *pParent=NULL)
CCopasiParameter (const std::string &name, const Type &type, const void *pValue=NULL, const CCopasiContainer *pParent=NULL, const std::string &objectType="Parameter")
virtual CCopasiObjectName getCN () const
virtual const std::string & getKey () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const CCopasiParameter::Type & getType () const
const Value & getValue () const
Value & getValue ()
virtual void * getValuePointer () const
CCopasiObject * getValueReference () const
bool isValidValue (const C_FLOAT64 &value) const
bool isValidValue (const C_INT32 &value) const
bool isValidValue (const unsigned C_INT32 &value) const
bool isValidValue (const bool &value) const
bool isValidValue (const std::string &value) const
bool isValidValue (const CCopasiObjectName &value) const
bool isValidValue (const std::vector< CCopasiParameter * > &value) const
CCopasiParameter & operator= (const CCopasiParameter &rhs)
template<class CType >
bool setValue (const CType &value)
bool setValue (const std::vector< CCopasiParameter * > &value)
virtual ~CCopasiParameter ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Protected Attributes
std::vector< CFluxMode > mFluxModes
std::vector< const CReaction * > mReorderedReactions
Protected Attributes inherited from CCopasiProblem
CProcessReport * mpCallBack
CModel * mpModel
CReport * mpReport
Protected Attributes inherited from CCopasiParameter
std::string mKey
CCopasiObject * mpValueReference
size_t mSize
Value mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Private Member Functions
void initializeParameter ()
void initObjects ()
Additional Inherited Members
Public Types inherited from CCopasiParameterGroup
typedef parameterGroup::iterator index_iterator
typedef
CCopasiContainer::objectMap::iterator name_iterator
typedef std::vector
< CCopasiParameter * > parameterGroup
Public Types inherited from CCopasiParameter
enum Type {
DOUBLE = 0, UDOUBLE, INT, UINT,
BOOL, GROUP, STRING, CN,
KEY, FILE, EXPRESSION, INVALID
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiParameter
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiProblem
CCopasiProblem (const CCopasiTask::Type &type, const CCopasiContainer *pParent=NULL)
Protected Member Functions inherited from CCopasiParameterGroup
CCopasiParameterGroup ()
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 38 of file CEFMProblem.h.
Constructor & Destructor Documentation
CEFMProblem::CEFMProblem (const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const CCopasiContainer * pParent (default: NULL)
Definition at line 35 of file CEFMProblem.cpp.
References initializeParameter(), and initObjects().
                                                         :
     CCopasiProblem(CCopasiTask::optimization, pParent),
     mFluxModes(),
     mReorderedReactions()
 {
   initializeParameter();
   initObjects();
 }
CEFMProblem::CEFMProblem (const CEFMProblem & src, const CCopasiContainer * pParent = NULL)
Copy constructor.
Parameters
const CEFMProblem & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 45 of file CEFMProblem.cpp.
References initializeParameter(), and initObjects().
                                                           :
     CCopasiProblem(src, pParent),
     mFluxModes(src.mFluxModes),
     mReorderedReactions(src.mReorderedReactions)
 {
   initializeParameter();
   initObjects();
 }
CEFMProblem::~CEFMProblem () virtual
Destructor
Definition at line 56 of file CEFMProblem.cpp.
 {}
Member Function Documentation
bool CEFMProblem::elevateChildren () virtual
This methods must be called to elevate subgroups to derived objects. The default implementation does nothing.
Returns
bool success
Reimplemented from CCopasiParameterGroup.
Definition at line 62 of file CEFMProblem.cpp.
Referenced by initializeParameter().
 {return true;}
const std::vector< CFluxMode > & CEFMProblem::getFluxModes () const
Return the flux modes after a successful analysis.
Returns
const std::vector< CFluxMode > & fluxModes
Definition at line 80 of file CEFMProblem.cpp.
References mFluxModes.
Referenced by CQNewMainWindow::checkForElementaryModesSlot(), QFluxModeAnimation::getScales(), CEFMMethod::initialize(), and QFluxModeAnimation::initialize().
 {return mFluxModes;}
std::vector< CFluxMode > & CEFMProblem::getFluxModes ()
Return the flux modes after a successful analysis.
Returns
std::vector< CFluxMode > & fluxModes
Definition at line 83 of file CEFMProblem.cpp.
References mFluxModes.
 {return mFluxModes;}
const std::vector< const CReaction * > & CEFMProblem::getReorderedReactions () const
Return the reactions in the order they are used in the flux modes
Returns
const std::vector< const CReaction * > & reorderedReactions
Definition at line 86 of file CEFMProblem.cpp.
References mReorderedReactions.
Referenced by CEFMTask::getReactionEquation(), QFluxModeAnimation::getScales(), and CEFMMethod::initialize().
 {return mReorderedReactions;}
std::vector< const CReaction * > & CEFMProblem::getReorderedReactions ()
Return the reactions in the order they are used in the flux modes
Returns
std::vector< const CReaction * > & reorderedReactions
Definition at line 89 of file CEFMProblem.cpp.
References mReorderedReactions.
 {return mReorderedReactions;}
bool CEFMProblem::initialize () virtual
Do all necessary initialization so that calls to calculate will be successful. This is called once from CCopasiTask::process()
Returns
bool success
Reimplemented from CCopasiProblem.
Definition at line 75 of file CEFMProblem.cpp.
References CCopasiProblem::initialize().
 {
   return CCopasiProblem::initialize();
 }
void CEFMProblem::initializeParameter () private
Allocates all group parameters and assures that they are properly initialized.
Definition at line 59 of file CEFMProblem.cpp.
References elevateChildren().
Referenced by CEFMProblem().
 {elevateChildren();}
void CEFMProblem::initObjects () private
Definition at line 72 of file CEFMProblem.cpp.
Referenced by CEFMProblem().
 {}
void CEFMProblem::printResult (std::ostream * ostream) const virtual
This is the output method for any result of a problem. The default implementation provided with CCopasiProblem. Does only print "Not implemented." To override this default behavior one needs to reimplement the virtual printResult function.
Parameters
std::ostream * ostream
Reimplemented from CCopasiProblem.
Definition at line 92 of file CEFMProblem.cpp.
References CCopasiVector< T >::begin(), C_INT32, CCopasiVector< T >::end(), CMetabNameInterface::getDisplayName(), CEFMTask::getFluxModeDescription(), CEFMTask::getFluxModes(), CEFMTask::getInternalSpecies(), CModel::getMetabolites(), CEFMTask::getNetReaction(), CCopasiObject::getObjectParent(), CEFMTask::getReactionEquation(), CEFMTask::getSpeciesChanges(), CCopasiProblem::mpModel, mReorderedReactions, and pTask.
 {
   CEFMTask * pTask = dynamic_cast< CEFMTask * >(getObjectParent());
   if (pTask)
     {
       const std::vector< CFluxMode > & FluxModes = pTask->getFluxModes();
       // List
       *ostream << "\tNumber of Modes:\t" << FluxModes.size() << std::endl;
       // Column header
       *ostream << "#\t\tReactions\tEquations" << std::endl;
       std::vector< CFluxMode >::const_iterator itMode = FluxModes.begin();
       std::vector< CFluxMode >::const_iterator endMode = FluxModes.end();
       unsigned C_INT32 j;
       for (j = 0; itMode != endMode; ++itMode, j++)
         {
           *ostream << j + 1;
           if (itMode->isReversible() == true)
             *ostream << "\tReversible";
           else
             *ostream << "\tIrreversible";
           std::string Description = pTask->getFluxModeDescription(*itMode);
           CFluxMode::const_iterator itReaction = itMode->begin();
           CFluxMode::const_iterator endReaction = itMode->end();
           std::string::size_type start = 0;
           std::string::size_type end = 0;
           for (; itReaction != endReaction; ++itReaction)
             {
               if (itReaction != itMode->begin())
                 *ostream << "\t";
               end = Description.find("\n", start);
               *ostream << "\t" << Description.substr(start, end - start);
               start = end + 1;
               *ostream << "\t" << pTask->getReactionEquation(itReaction) << std::endl;
             }
         }
       *ostream << std::endl;
       // Net Reactions
       // Column header
       *ostream << "#\tNet Reaction\tInternal Species" << std::endl;
       itMode = FluxModes.begin();
       for (j = 0; itMode != endMode; ++itMode, j++)
         {
           *ostream << j + 1;
           *ostream << "\t" << pTask->getNetReaction(*itMode);
           *ostream << "\t" << pTask->getInternalSpecies(*itMode) << std::endl;
         }
       *ostream << std::endl;
       // EFM vs Reaction
       std::vector< const CReaction * >::const_iterator itReaction = mReorderedReactions.begin();
       std::vector< const CReaction * >::const_iterator endReaction = mReorderedReactions.end();
       // Column header
       *ostream << "#";
       for (; itReaction != endReaction; ++itReaction)
         {
           *ostream << "\t" << (*itReaction)->getObjectName();
         }
       *ostream << std::endl;
       itMode = FluxModes.begin();
       size_t k;
       for (j = 0; itMode != endMode; ++itMode, j++)
         {
           itReaction = mReorderedReactions.begin();
           *ostream << j + 1;
           for (k = 0; itReaction != endReaction; ++itReaction, k++)
             {
               *ostream << "\t" << itMode->getMultiplier(k);
             }
           *ostream << std::endl;
         }
       *ostream << std::endl;
       if (mpModel == NULL) return;
       // EFM vs Species
       std::vector< CMetab * >::const_iterator itSpecies = mpModel->getMetabolites().begin();
       std::vector< CMetab * >::const_iterator endSpecies = mpModel->getMetabolites().end();
       // Column header
       *ostream << "#";
       for (; itSpecies != endSpecies; ++itSpecies)
         {
           *ostream << "\t" << CMetabNameInterface::getDisplayName(mpModel, **itSpecies, false);
         }
       *ostream << std::endl;
       itMode = FluxModes.begin();
       for (j = 0; itMode != endMode; ++itMode, j++)
         {
           itSpecies = mpModel->getMetabolites().begin();
           *ostream << j + 1;
           for (; itSpecies != endSpecies; ++itSpecies)
             {
               std::pair< C_FLOAT64, C_FLOAT64 > Changes =
                 pTask->getSpeciesChanges(*itMode, **itSpecies);
               *ostream << "\t";
               if (Changes.first > 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon() ||
                   Changes.second > 100.0 * std::numeric_limits< C_FLOAT64 >::epsilon())
                 {
                   *ostream << "-" << Changes.first << " | +" << Changes.second;
                 }
             }
           *ostream << std::endl;
         }
       *ostream << std::endl;
     }
 }
bool CEFMProblem::setCallBack (CProcessReport * pCallBack) virtual
Set the call back of the problem
Parameters
CProcessReport * pCallBack
Returns
bool success
Reimplemented from CCopasiProblem.
Definition at line 65 of file CEFMProblem.cpp.
References CCopasiProblem::setCallBack().
 {
   CCopasiProblem::setCallBack(pCallBack);
   return true;
 }
Member Data Documentation
std::vector< CFluxMode > CEFMProblem::mFluxModes protected
The resulting elementary flux modes
Definition at line 130 of file CEFMProblem.h.
Referenced by getFluxModes().
std::vector< const CReaction * > CEFMProblem::mReorderedReactions protected
Reactions in the order used in the analysis
Definition at line 135 of file CEFMProblem.h.
Referenced by getReorderedReactions(), and printResult().
The documentation for this class was generated from the following files:
CEFMProblem.h
CEFMProblem.cpp