COPASI API: CKinFunction Class Reference
CKinFunction Class Reference
#include <CKinFunction.h>
Public Member Functions
CKinFunction (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CKinFunction (const CFunction &src, CReadConfig *configBuffer=NULL, const CCopasiContainer *pParent=NULL)
CKinFunction (const CKinFunction &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
std::vector< CNodeK * > & getNodes ()
~CKinFunction ()
Public Member Functions inherited from CFunction
bool addVariable (const std::string &name, CFunctionParameter::Role usage=CFunctionParameter::VARIABLE, const CFunctionParameter::DataType &type=CFunctionParameter::FLOAT64)
virtual const C_FLOAT64 & calcValue (const CCallParameters< C_FLOAT64 > &callParameters)
CFunction (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=Function)
CFunction (const CFunction &src, const CCopasiContainer *pParent=NULL)
CFunction * createCopy () const
void createListOfParametersForMathML (std::vector< std::vector< std::string > > &env)
virtual bool dependsOn (const C_FLOAT64 *parameter, const CCallParameters< C_FLOAT64 > &callParameters) const
const std::string & getKey () const
const std::string & getSBMLId () const
virtual size_t getVariableIndex (const std::string &name) const
CFunctionParameters & getVariables ()
const CFunctionParameters & getVariables () const
virtual const C_FLOAT64 & getVariableValue (const size_t &index) const
const TriLogic & isReversible () const
bool isSuitable (const size_t noSubstrates, const size_t noProducts, const TriLogic reversible)
virtual void load (CReadConfig &configBuffer, CReadConfig::Mode mode=CReadConfig::SEARCH)
bool operator== (const CFunction &rhs) const
virtual bool setInfix (const std::string &infix)
virtual bool setInfix (const std::string &infix, bool compile)
void setReversible (const TriLogic &reversible)
void setSBMLId (const std::string &id)
std::pair< CFunction
*, CFunction * > splitFunction (const CEvaluationNode *node, const std::string &name1, const std::string &name2) const
virtual void writeMathML (std::ostream &out, size_t l=0) const
virtual std::string writeMathML (const std::vector< std::vector< std::string > > &variables, bool expand=true, bool fullExpand=true) const
virtual ~CFunction ()
Public Member Functions inherited from CEvaluationTree
bool calls (std::set< std::string > &list) const
CEvaluationTree (const std::string &name="NoName", const CCopasiContainer *pParent=NULL, const Type &type=Function)
CEvaluationTree (const CEvaluationTree &src, const CCopasiContainer *pParent=NULL)
virtual bool compile ()
bool dependsOnTree (const std::string &name) const
CCopasiObject::DataObjectSet getDeletedObjects () const
std::string::size_type getErrorPosition () const
const std::string & getInfix () const
const std::vector
< CEvaluationNode * > & getNodeList () const
CEvaluationNode * getRoot ()
const CEvaluationNode * getRoot () const
const CEvaluationTree::Type & getType () const
bool hasCircularDependency () const
bool hasDiscontinuity () const
bool isBoolean () const
bool isUsable () const
bool operator== (const CEvaluationTree &rhs) const
virtual bool setRoot (CEvaluationNode *pRootNode)
bool setTree (const ASTNode &pRootNode)
virtual ASTNode * toAST (const CCopasiDataModel *pDataModel) const
bool updateTree ()
virtual ~CEvaluationTree ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Public Member Functions inherited from CAnnotation
bool addUnsupportedAnnotation (const std::string &name, const std::string &xml)
CAnnotation ()
CAnnotation (const CAnnotation &src)
const std::string & getMiriamAnnotation () const
const std::string & getNotes () const
UnsupportedAnnotation & getUnsupportedAnnotations ()
const UnsupportedAnnotation & getUnsupportedAnnotations () const
bool operator== (const CAnnotation &rhs) const
bool removeUnsupportedAnnotation (const std::string &name)
bool replaceUnsupportedAnnotation (const std::string &name, const std::string &xml)
void setMiriamAnnotation (const std::string &miriamAnnotation, const std::string &newId, const std::string &oldId)
void setNotes (const std::string &notes)
virtual ~CAnnotation ()
Private Member Functions
void cleanupNodes ()
void createParameters ()
Private Attributes
unsigned C_INT32 mNidx
std::vector< CNodeK * > mNodes
std::vector< CCopasiObject * > ObjList
Additional Inherited Members
Public Types inherited from CEvaluationTree
enum Type {
Function = 0, MassAction, PreDefined, UserDefined,
Expression, MathExpression
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Types inherited from CAnnotation
typedef std::map< std::string,
std::string > UnsupportedAnnotation
Static Public Member Functions inherited from CFunction
static bool completeFunctionList (std::vector< CFunction * > &list, const size_t &added=0)
Static Public Member Functions inherited from CEvaluationTree
static CEvaluationTree * copy (const CEvaluationTree &src)
static CEvaluationTree * create (CEvaluationTree::Type type)
static CEvaluationNode * fromAST (const ASTNode *pASTNode)
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Member Functions inherited from CAnnotation
static CAnnotation * castObject (CCopasiObject *pObject)
static const CAnnotation * castObject (const CCopasiObject *pObject)
Static Public Attributes inherited from CEvaluationTree
static const std::string TypeName []
static const char * XMLType []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CFunction
bool initVariables ()
Protected Member Functions inherited from CEvaluationTree
void buildCalculationSequence ()
void calculate ()
bool compileNodes ()
bool parse ()
void setType (const CEvaluationTree::Type &type)
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CEvaluationTree
std::vector< CEvaluationNode * > mCalculationSequence
std::string mInfix
std::vector< CEvaluationNode * > * mpNodeList
CEvaluationNode * mpRoot
CEvaluationTree::Type mType
bool mUsable
C_FLOAT64 mValue
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Protected Attributes inherited from CAnnotation
std::string mKey
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 37 of file CKinFunction.h.
Constructor & Destructor Documentation
CKinFunction::CKinFunction (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 38 of file CKinFunction.cpp.
References CONSTRUCTOR_TRACE.
                                                             :
     CFunction(name, pParent, CFunction::UserDefined)
 {
   CONSTRUCTOR_TRACE;
 }
CKinFunction::CKinFunction (const CFunction & src, CReadConfig * configBuffer = NULL, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CFunction & src
CReadConfig * configBuffer (Default = NULL)
const CCopasiContainer * pParent (default: NULL)
Definition at line 45 of file CKinFunction.cpp.
References C_INT32, cleanupNodes(), CONSTRUCTOR_TRACE, createParameters(), CReadConfig::getVariable(), and mNodes.
                                                             :
     CFunction(src, pParent)
 {
   CONSTRUCTOR_TRACE;
   if (configBuffer)
     {
       C_INT32 i, Size;
       configBuffer->getVariable("Nodes", "C_INT32", &Size);
       mNodes.resize(Size);
       for (i = 0; i < Size; i++)
         {
           mNodes[i] = new CNodeK;
           mNodes[i]->load(*configBuffer);
         }
       createParameters();
       cleanupNodes();
     }
   //  compile();
 }
CKinFunction::CKinFunction (const CKinFunction & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CKinFunction & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 72 of file CKinFunction.cpp.
References CONSTRUCTOR_TRACE.
                                                             :
     CFunction(src, pParent)
 {
   CONSTRUCTOR_TRACE;
   //compile();
 }
CKinFunction::~CKinFunction ()
Destructor
Definition at line 80 of file CKinFunction.cpp.
References cleanup(), DESTRUCTOR_TRACE, and ObjList.
 {
   /*  int i;
     for (i=0; i<ObjList.size(); i++)
      ObjList[i] = NULL;
   */
   ObjList.clear();
   cleanup();
   DESTRUCTOR_TRACE;
 }
Member Function Documentation
void CKinFunction::cleanup ()
Cleanup
Definition at line 91 of file CKinFunction.cpp.
References cleanupNodes().
Referenced by ~CKinFunction().
 {
   cleanupNodes();
 }
void CKinFunction::cleanupNodes () private
Cleanup nodes
Definition at line 248 of file CKinFunction.cpp.
References mNodes.
Referenced by CKinFunction(), and cleanup().
 {
   size_t i, imax = mNodes.size();
   for (i = 0; i < imax; i++)
     if (mNodes[i]) delete mNodes[i];
   mNodes.clear();
   return;
 }
void CKinFunction::createParameters () private
This function indentify the object from name This connects the nodes to build the binary function tree This function is part of the algorithm that builds the binary tree. The expression to the right of the current node (mNidx) is parsed until an operand with a left priority <= the argument (right priority) is encounterd. The pointer to the top node of the parsed expression is returned.
Parameters
C_INT16 priority
Returns
CNodeK * This function is part of the algorithm that builds the binary tree. It returns a pointer to next primary node. Here next is with repect to the internal counter mNidx. If the node is a dead end, i.e., any contant a pointer the node is returned. If then node is '(' the expression between the node and the matching ')' is parsed and a pointer to the resulting top node is returned. If the node is a function or a unary minus the argument is parsed and a pointer to the function node is returned.
CNodeK * This function creates the parameter description for older file versions
Definition at line 97 of file CKinFunction.cpp.
References CFunctionParameters::add(), CCopasiVectorN< CType >::add(), CEvaluationNode::buildInfix(), C_INVALID_INDEX, CFunctionParameters::cleanup(), CCopasiVector< T >::cleanup(), CEvaluationNode::CONSTANT, fatalError, CFunctionParameter::FLOAT64, CCopasiVectorN< CType >::getIndex(), CCopasiObject::getObjectName(), CEvaluationTree::getType(), CFunction::getVariables(), mNodes, CFunctionParameter::MODIFIER, CEvaluationTree::mpNodeList, CEvaluationTree::mpRoot, N_IDENTIFIER, N_KCONSTANT, N_MODIFIER, N_NOP, N_PRODUCT, N_SUBSTRATE, N_VOLUME, CFunctionParameter::PARAMETER, pdelete, CFunctionParameter::PRODUCT, CFunction::setInfix(), CFunctionParameter::setType(), CFunctionParameter::setUsage(), CCopasiVector< T >::size(), CFunctionParameter::SUBSTRATE, and CFunctionParameter::VOLUME.
Referenced by CKinFunction().
 {
   CCopasiVectorN < CFunctionParameter > Substrates;
   CCopasiVectorN < CFunctionParameter > Products;
   CCopasiVectorN < CFunctionParameter > Modifiers;
   CCopasiVectorN < CFunctionParameter > Parameters;
   CCopasiVectorN < CFunctionParameter > Volumes;
   size_t i, imax = mNodes.size();
   CFunctionParameter *pParameter;
   for (i = 0; i < imax; i++)
     {
       if (mNodes[i]->getType() == N_IDENTIFIER)
         {
           // We need to check that we have no reserved name.
           const char *Reserved[] =
             {"pi", "exponentiale", "true", "false", "infinity", "nan",
              "PI", "EXPONENTIALE", "TRUE", "FALSE", "INFINITY", "NAN"
             };
           std::string Name = mNodes[i]->getName();
           size_t j, jmax = 12;
           for (j = 0; j < jmax; j++)
             if (Name == Reserved[j]) break;
           if (j != jmax)
             {
               // It is save to prepend the identifyer with '_' since this is not allowed in
               // Gepasi but within COPASI.
               std::string OldName = Name;
               Name = "_" + Name;
               // We have to replace the corresponding CEvaluationNodes to reflect the change.
               std::vector< CEvaluationNode * >::iterator it = mpNodeList->begin();
               std::vector< CEvaluationNode * >::iterator end = mpNodeList->end();
               for (; it != end; ++it)
                 if (((*it)->getType() & 0xFF000000) == CEvaluationNode::CONSTANT &&
                     (*it)->getData() == OldName)
                   (*it)->setData(Name);
               // The Infix has changed we need to update it.
               setInfix(mpRoot->buildInfix());
             }
           pParameter = new CFunctionParameter(Name);
           pParameter->setType(CFunctionParameter::FLOAT64);
           switch (mNodes[i]->getSubtype())
             {
               case N_SUBSTRATE:
                 pParameter->setUsage(CFunctionParameter::SUBSTRATE);
                 if (Substrates.getIndex(pParameter->getObjectName()) == C_INVALID_INDEX)
                   Substrates.add(pParameter, false);
                 else
                   pdelete(pParameter);
                 break;
               case N_PRODUCT:
                 pParameter->setUsage(CFunctionParameter::PRODUCT);
                 if (Products.getIndex(pParameter->getObjectName()) == C_INVALID_INDEX)
                   Products.add(pParameter, false);
                 else
                   pdelete(pParameter);
                 break;
               case N_MODIFIER:
                 pParameter->setUsage(CFunctionParameter::MODIFIER);
                 if (Modifiers.getIndex(pParameter->getObjectName()) == C_INVALID_INDEX)
                   Modifiers.add(pParameter, false);
                 else
                   pdelete(pParameter);
                 break;
               case N_KCONSTANT:
               case N_NOP:
                 pParameter->setUsage(CFunctionParameter::PARAMETER);
                 if (Parameters.getIndex(pParameter->getObjectName()) == C_INVALID_INDEX)
                   Parameters.add(pParameter, false);
                 else
                   pdelete(pParameter);
                 break;
               case N_VOLUME:
                 pParameter->setUsage(CFunctionParameter::VOLUME);
                 if (Volumes.getIndex(pParameter->getObjectName()) == C_INVALID_INDEX)
                   Volumes.add(pParameter, false);
                 else
                   pdelete(pParameter);
                 break;
               default:
                 pdelete(pParameter);
                 fatalError();
             }
         }
     }
   getVariables().cleanup();
   imax = Substrates.size();
   for (i = 0; i < imax; i++)
     getVariables().add(Substrates[i], true);
   Substrates.cleanup();
   imax = Products.size();
   for (i = 0; i < imax; i++)
     getVariables().add(Products[i], true);
   Products.cleanup();
   imax = Modifiers.size();
   for (i = 0; i < imax; i++)
     getVariables().add(Modifiers[i], true);
   Modifiers.cleanup();
   imax = Parameters.size();
   for (i = 0; i < imax; i++)
     getVariables().add(Parameters[i], true);
   Parameters.cleanup();
   imax = Volumes.size();
   for (i = 0; i < imax; i++)
     getVariables().add(Volumes[i], true);
   Volumes.cleanup();
 }
std::vector< CNodeK * > & CKinFunction::getNodes ()
Retreives the nodes of the function
Definition at line 246 of file CKinFunction.cpp.
References mNodes.
 {return mNodes;}
Member Data Documentation
unsigned C_INT32 CKinFunction::mNidx private
Internal variable
Definition at line 52 of file CKinFunction.h.
std::vector< CNodeK * > CKinFunction::mNodes private
The vector of nodes of the binary tree of the function 0..* <{CNodeK}>
Definition at line 46 of file CKinFunction.h.
Referenced by CKinFunction(), cleanupNodes(), createParameters(), and getNodes().
std::vector<CCopasiObject*> CKinFunction::ObjList private
Definition at line 48 of file CKinFunction.h.
Referenced by ~CKinFunction().
The documentation for this class was generated from the following files:
CKinFunction.h
CKinFunction.cpp