COPASI API: CLTransformation Class Reference
CLTransformation Class Reference
#include <CLTransformation.h>
Public Member Functions
CLTransformation ()
CLTransformation (const double matrix[12])
std::string get3DTransformationString () const
virtual const double * getMatrix () const
bool is2DTransformation () const
bool isIdentityMatrix () const
bool isSetMatrix () const
virtual void parseTransformation (const std::string &transformationString)
void setMatrix (const double m[12])
Public Member Functions inherited from CLBase
CLBase ()
CLBase (const CLBase &b)
CLBase (const SBase &)
const std::string & getTag () const
bool hasTag () const
virtual void moveBy (const CLPoint &)
void setTag (const std::string &tag)
virtual ~CLBase ()
Static Public Member Functions
static const double * getIdentityMatrix ()
Static Public Attributes
static const double IDENTITY3D [12] = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0}
Protected Attributes
double mMatrix [12]
Protected Attributes inherited from CLBase
std::string mTag
Detailed Description
Definition at line 23 of file CLTransformation.h.
Constructor & Destructor Documentation
CLTransformation::CLTransformation ()
Default constructor. All matrix elements are set to NaN
Definition at line 28 of file CLTransformation.cpp.
References mMatrix.
                                   : CLBase()
 {
   unsigned int i;
   for (i = 0; i < 12; ++i)
     {
       mMatrix[i] = std::numeric_limits<double>::quiet_NaN();
     }
 }
CLTransformation::CLTransformation (const double matrix[12])
Constructor with values for the matrix.
Constructor with id and values for the matrix.
Definition at line 41 of file CLTransformation.cpp.
References mMatrix.
                                                          : CLBase()
 {
   unsigned int i;
   for (i = 0; i < 12; ++i)
     {
       mMatrix[i] = matrix[i];
     }
 }
Member Function Documentation
std::string CLTransformation::get3DTransformationString () const
Returns a string to represent the 3D transformation.
Definition at line 125 of file CLTransformation.cpp.
References mMatrix.
Referenced by CCopasiXML::saveTransformationAttributes().
 {
   // transform the matrix to a string
   std::ostringstream os;
   unsigned int i;
   os << mMatrix[0];
   for (i = 1; i < 12; ++i)
     {
       os << "," << mMatrix[i];
     }
   return os.str();
 }
const double * CLTransformation::getIdentityMatrix () static
Returns the 3D identity matrix. The matrix contains 12 values.
Definition at line 77 of file CLTransformation.cpp.
References IDENTITY3D.
Referenced by CLGroupAttributes::CLGroupAttributes(), and CLLayoutRenderer::draw_curve().
 {
   return IDENTITY3D;
 }
const double * CLTransformation::getMatrix () const virtual
Returns the matrix.
Returns the matrix. The matrix contains 12 values.
Definition at line 68 of file CLTransformation.cpp.
References mMatrix.
Referenced by CLLayoutRenderer::extract_transformation_attributes().
 {
   return mMatrix;
 }
bool CLTransformation::is2DTransformation () const
Checks if the transformation is a 2D transformation, i.e. we have to check some of the values.
Definition at line 112 of file CLTransformation.cpp.
References mMatrix.
Referenced by CCopasiXML::saveTransformationAttributes().
 {
   return mMatrix[2] == 0.0 &&
          mMatrix[5] == 0.0 &&
          mMatrix[6] == 0.0 &&
          mMatrix[7] == 0.0 &&
          mMatrix[8] == 1.0 &&
          mMatrix[11] == 0.0;
 }
bool CLTransformation::isIdentityMatrix () const
Returns true if the matrix is the identity matrix.
Definition at line 103 of file CLTransformation.cpp.
References IDENTITY3D, and mMatrix.
Referenced by CCopasiXML::saveTransformationAttributes().
 {
   return !memcmp(mMatrix, CLTransformation::IDENTITY3D, sizeof(double)*12);
 }
bool CLTransformation::isSetMatrix () const
Returns true if the matrix has been set or false otherwise.
Definition at line 87 of file CLTransformation.cpp.
References mMatrix.
Referenced by CLLayoutRenderer::extract_transformation_attributes(), CCopasiXML::saveTransformationAttributes(), and transform().
 {
   bool result = true;
   unsigned int i;
   for (i = 0; result && i < 12; ++i)
     {
       result = (mMatrix[i] == mMatrix[i]);
     }
   return result;
 }
void CLTransformation::parseTransformation (const std::string & transformationString) virtual
Sets the transformation matrix from the given string. The string has to contain 12 numerical values seperated by ",". Otherwise the matrix is set to the identity matrix.
Reimplemented in CLTransformation2D.
Definition at line 145 of file CLTransformation.cpp.
References IDENTITY3D, mMatrix, and setMatrix().
Referenced by CLTransformation2D::parseTransformation().
 {
   // the string should contain a list of 6 komma seperated numbers
   // if it doesn't, we try to set the 3D matrix
   bool result = true;
   std::string delimiter = ",";
   std::size_t lastPos = transformationString.find_first_not_of(delimiter);
   std::size_t pos;
   unsigned int index = 0;
   while (lastPos != std::string::npos)
     {
       if (index > 11)
         {
           result = false;
           break;
         }
       pos = transformationString.find_first_of(delimiter, lastPos);
       double value = strtod(transformationString.substr(lastPos, pos - lastPos).c_str(), NULL);
       mMatrix[index] = value;
       index++;
       lastPos = transformationString.find_first_not_of(delimiter, pos);
     }
   if (!result || index != 12)
     {
       this->setMatrix(CLTransformation::IDENTITY3D);
     }
 }
void CLTransformation::setMatrix (const double m[12])
Sets the matrix.
Definition at line 54 of file CLTransformation.cpp.
References mMatrix.
Referenced by parseTransformation(), and CLTransformation2D::setMatrix().
 {
   unsigned int i;
   for (i = 0; i < 12; ++i)
     {
       mMatrix[i] = m[i];
     }
 }
Member Data Documentation
const double CLTransformation::IDENTITY3D = {1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0} static
Definition at line 29 of file CLTransformation.h.
Referenced by CLTransformation2D::CLTransformation2D(), getIdentityMatrix(), isIdentityMatrix(), and parseTransformation().
double CLTransformation::mMatrix[12] protected
Definition at line 26 of file CLTransformation.h.
Referenced by CLTransformation(), CLTransformation2D::CLTransformation2D(), get3DTransformationString(), getMatrix(), is2DTransformation(), isIdentityMatrix(), isSetMatrix(), parseTransformation(), setMatrix(), CLTransformation2D::updateMatrix2D(), and CLTransformation2D::updateMatrix3D().
The documentation for this class was generated from the following files:
CLTransformation.h
CLTransformation.cpp