COPASI API: CQProgressItemText Class Reference
CQProgressItemText Class Reference
#include <CQProgressItemText.h>
Public Member Functions
CQProgressItemText (QWidget *parent=0, const char *name=0)
virtual bool initFromProcessReportItem (CProcessReportItem *pItem)
virtual bool process ()
virtual bool reset ()
~CQProgressItemText ()
Public Member Functions inherited from CQProgressItem
CQProgressItem (QWidget *parent=0, const char *name=0, Qt::WindowFlags fl=0)
~CQProgressItem ()
Private Member Functions
virtual void setValueFromDOUBLE ()
virtual void setValueFromINT ()
virtual void setValueFromSTRING ()
virtual void setValueFromUINT ()
Private Attributes
CCopasiParameter::Value mParameterValue
void(CQProgressItemText::* mpSetValue)()
Additional Inherited Members
Protected Attributes inherited from CQProgressItem
CProcessReportItem * mpItem
Detailed Description
Definition at line 24 of file CQProgressItemText.h.
Constructor & Destructor Documentation
CQProgressItemText::CQProgressItemText (QWidget * parent = 0, const char * name = 0)
Definition at line 26 of file CQProgressItemText.cpp.
     : CQProgressItem(parent, name)
 {
   Ui::CQProgressItemText::setupUi(this);
 }
CQProgressItemText::~CQProgressItemText ()
Definition at line 35 of file CQProgressItemText.cpp.
 {
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
bool CQProgressItemText::initFromProcessReportItem (CProcessReportItem * pItem) virtual
Reimplemented from CQProgressItem.
Definition at line 40 of file CQProgressItemText.cpp.
References FROM_UTF8, CCopasiObject::getObjectName(), CCopasiParameter::getValue(), mParameterValue, CQProgressItem::mpItem, and reset().
 {
   mpItem = pItem;
   mParameterValue = mpItem->getValue();
   mItemName->setText(FROM_UTF8(mpItem->getObjectName()));
   this->show();
   return reset();
 }
bool CQProgressItemText::process () virtual
Reimplemented from CQProgressItem.
Definition at line 52 of file CQProgressItemText.cpp.
References mpSetValue.
Referenced by reset().
 {
   (this->*mpSetValue)();
   return true;
 }
bool CQProgressItemText::reset () virtual
Reimplemented from CQProgressItem.
Definition at line 58 of file CQProgressItemText.cpp.
References CCopasiParameter::DOUBLE, CCopasiParameter::getType(), CCopasiParameter::INT, CQProgressItem::mpItem, mpSetValue, process(), setValueFromDOUBLE(), setValueFromINT(), setValueFromSTRING(), setValueFromUINT(), CCopasiParameter::STRING, CCopasiParameter::UDOUBLE, and CCopasiParameter::UINT.
Referenced by initFromProcessReportItem().
 {
   switch (mpItem->getType())
     {
       case CCopasiParameter::DOUBLE:
       case CCopasiParameter::UDOUBLE:
         mpSetValue = & CQProgressItemText::setValueFromDOUBLE;
         break;
       case CCopasiParameter::INT:
         mpSetValue = & CQProgressItemText::setValueFromINT;
         break;
       case CCopasiParameter::UINT:
         mpSetValue = & CQProgressItemText::setValueFromUINT;
         break;
       case CCopasiParameter::STRING:
         mpSetValue = & CQProgressItemText::setValueFromSTRING;
         break;
       default:
         return false;
         break;
     }
   return process();
 }
void CQProgressItemText::setValueFromDOUBLE () private virtual
Definition at line 87 of file CQProgressItemText.cpp.
References mParameterValue, and CCopasiParameter::Value::pDOUBLE.
Referenced by reset().
 {
   mValue->setText(QString::number(* mParameterValue.pDOUBLE));
 }
void CQProgressItemText::setValueFromINT () private virtual
Definition at line 92 of file CQProgressItemText.cpp.
References mParameterValue, and CCopasiParameter::Value::pINT.
Referenced by reset().
 {
   mValue->setText(QString::number(* mParameterValue.pINT));
 }
void CQProgressItemText::setValueFromSTRING () private virtual
Definition at line 102 of file CQProgressItemText.cpp.
References FROM_UTF8, mParameterValue, and CCopasiParameter::Value::pSTRING.
Referenced by reset().
 {
   mValue->setText(FROM_UTF8(* mParameterValue.pSTRING));
 }
void CQProgressItemText::setValueFromUINT () private virtual
Definition at line 97 of file CQProgressItemText.cpp.
References mParameterValue, and CCopasiParameter::Value::pUINT.
Referenced by reset().
 {
   mValue->setText(QString::number(* mParameterValue.pUINT));
 }
Member Data Documentation
CCopasiParameter::Value CQProgressItemText::mParameterValue private
Definition at line 38 of file CQProgressItemText.h.
Referenced by initFromProcessReportItem(), setValueFromDOUBLE(), setValueFromINT(), setValueFromSTRING(), and setValueFromUINT().
void(CQProgressItemText::* CQProgressItemText::mpSetValue)() private
Definition at line 37 of file CQProgressItemText.h.
Referenced by process(), and reset().
The documentation for this class was generated from the following files:
CQProgressItemText.h
CQProgressItemText.cpp