COPASI API: CQEffectDescription Class Reference
CQEffectDescription Class Reference
#include <CQEffectDescription.h>
Public Types
enum Mode { DropShadow, Colorize, Scale }
Public Member Functions
void applyToScene (CQLayoutScene &scene, qreal t)
CQEffectDescription (const std::string &cn, qreal startScale, qreal endScale)
CQEffectDescription (const std::string &cn, Mode mode=Colorize, const QColor &startColor=Qt::white, const QColor &endColor=Qt::red)
const std::string & getCN () const
const QColor & getEndColor () const
Mode getMode () const
qreal getScaleEnd () const
qreal getScaleStart () const
const QColor & getStartColor () const
virtual void removeFromScene (CQLayoutScene &scene)
void setCN (const std::string &cn)
void setEndColor (const QColor &color)
void setMode (Mode mode)
void setScaleEnd (qreal scale)
void setScaleStart (qreal scale)
void setStartColor (const QColor &color)
virtual ~CQEffectDescription ()
Protected Attributes
std::string mCN
QColor mEndColor
Mode mMode
qreal mScaleEnd
qreal mScaleStart
QColor mStartColor
Detailed Description
Definition at line 14 of file CQEffectDescription.h.
Member Enumeration Documentation
enum CQEffectDescription::Mode
Enumerator
DropShadow
Colorize
Scale
Definition at line 17 of file CQEffectDescription.h.
   {
     DropShadow,
     Colorize,
     Scale
   };
Constructor & Destructor Documentation
CQEffectDescription::CQEffectDescription (const std::string & cn, qreal startScale, qreal endScale)
Definition at line 49 of file CQEffectDescription.cpp.
   : mCN(cn)
   , mStartColor(Qt::white)
   , mEndColor(Qt::red)
   , mScaleStart(startScale)
   , mScaleEnd(endScale)
   , mMode(Scale)
 {
 }
CQEffectDescription::CQEffectDescription (const std::string & cn, Mode mode = Colorize, const QColor & startColor = Qt::white, const QColor & endColor = Qt::red)
Definition at line 39 of file CQEffectDescription.cpp.
   : mCN(cn)
   , mStartColor(startColor)
   , mEndColor(endColor)
   , mScaleStart(0.5)
   , mScaleEnd(2.0)
   , mMode(mode)
 {
 }
CQEffectDescription::~CQEffectDescription () virtual
Definition at line 59 of file CQEffectDescription.cpp.
 {
 }
Member Function Documentation
void CQEffectDescription::applyToScene (CQLayoutScene & scene, qreal t)
Definition at line 112 of file CQEffectDescription.cpp.
References Colorize, DropShadow, CQLayoutScene::getItemFor(), interpolate(), linear(), mCN, mEndColor, mMode, mScaleEnd, mScaleStart, mStartColor, Scale, and CQCopasiEffect::setScale().
 {
   QGraphicsItem *item = scene.getItemFor(mCN);
   if (item == NULL)
     return;
   switch (mMode)
     {
       default:
       case DropShadow:
       {
         QGraphicsDropShadowEffect* effect = new QGraphicsDropShadowEffect(&scene);
         effect->setColor(interpolate(mStartColor, mEndColor, t));
         effect->setBlurRadius(25);
         effect->setEnabled(true);
         effect->setOffset(0);
         item->setGraphicsEffect(effect);
       }
       break;
       case Colorize:
       {
         QGraphicsColorizeEffect* effect = new QGraphicsColorizeEffect(&scene);
         effect->setColor(interpolate(mStartColor, mEndColor, t));
         effect->setStrength(1);
         effect->setEnabled(true);
         item->setGraphicsEffect(effect);
       }
       break;
       case Scale:
       {
         CQCopasiEffect* effect = new CQCopasiEffect();
         effect->setScale(linear(mScaleStart, mScaleEnd, t));
         effect->setEnabled(true);
         item->setGraphicsEffect(effect);
       }
       break;
     }
 }
const std::string & CQEffectDescription::getCN () const
Definition at line 63 of file CQEffectDescription.cpp.
References mCN.
Referenced by CQEffectDescriptionEdit::initFrom(), and CQAnimationSettingsEditor::initFrom().
 {
   return mCN;
 }
const QColor & CQEffectDescription::getEndColor () const
Definition at line 73 of file CQEffectDescription.cpp.
References mEndColor.
Referenced by CQEffectDescriptionEdit::initFrom().
 {
   return mEndColor;
 }
CQEffectDescription::Mode CQEffectDescription::getMode () const
Definition at line 88 of file CQEffectDescription.cpp.
References mMode.
Referenced by CQEffectDescriptionEdit::initFrom().
 {
   return mMode;
 }
qreal CQEffectDescription::getScaleEnd () const
Definition at line 83 of file CQEffectDescription.cpp.
References mScaleEnd.
Referenced by CQEffectDescriptionEdit::initFrom().
 {
   return mScaleEnd;
 }
qreal CQEffectDescription::getScaleStart () const
Definition at line 78 of file CQEffectDescription.cpp.
References mScaleStart.
Referenced by CQEffectDescriptionEdit::initFrom().
 {
   return mScaleStart;
 }
const QColor & CQEffectDescription::getStartColor () const
Definition at line 68 of file CQEffectDescription.cpp.
References mStartColor.
Referenced by CQEffectDescriptionEdit::initFrom().
 {
   return mStartColor;
 }
void CQEffectDescription::removeFromScene (CQLayoutScene & scene) virtual
Definition at line 97 of file CQEffectDescription.cpp.
References CQLayoutScene::getItemFor(), and mCN.
 {
   QGraphicsItem *item = scene.getItemFor(mCN);
   if (item == NULL)
     return;
   QGraphicsEffect* effect = item->graphicsEffect();
   if (effect == NULL)
     return;
   effect->setEnabled(false);
 }
void CQEffectDescription::setCN (const std::string & cn)
Definition at line 154 of file CQEffectDescription.cpp.
References mCN.
 {
   mCN = cn;
 }
void CQEffectDescription::setEndColor (const QColor & color)
Definition at line 164 of file CQEffectDescription.cpp.
References mEndColor.
Referenced by CQEffectDescriptionEdit::saveTo(), and CQEffectDescriptionEdit::toDescription().
 {
   mEndColor = color;
 }
void CQEffectDescription::setMode (CQEffectDescription::Mode mode)
Definition at line 92 of file CQEffectDescription.cpp.
References mMode.
Referenced by CQEffectDescriptionEdit::saveTo(), and CQEffectDescriptionEdit::toDescription().
 {
   mMode = mode;
 }
void CQEffectDescription::setScaleEnd (qreal scale)
Definition at line 174 of file CQEffectDescription.cpp.
References mScaleEnd.
Referenced by CQEffectDescriptionEdit::saveTo(), and CQEffectDescriptionEdit::toDescription().
 {
   mScaleEnd = scale;
 }
void CQEffectDescription::setScaleStart (qreal scale)
Definition at line 169 of file CQEffectDescription.cpp.
References mScaleStart.
Referenced by CQEffectDescriptionEdit::saveTo(), and CQEffectDescriptionEdit::toDescription().
 {
   mScaleStart = scale;
 }
void CQEffectDescription::setStartColor (const QColor & color)
Definition at line 159 of file CQEffectDescription.cpp.
References mStartColor.
Referenced by CQEffectDescriptionEdit::saveTo(), and CQEffectDescriptionEdit::toDescription().
 {
   mStartColor = color;
 }
Member Data Documentation
std::string CQEffectDescription::mCN protected
Definition at line 51 of file CQEffectDescription.h.
Referenced by applyToScene(), getCN(), removeFromScene(), and setCN().
QColor CQEffectDescription::mEndColor protected
Definition at line 53 of file CQEffectDescription.h.
Referenced by applyToScene(), getEndColor(), and setEndColor().
Mode CQEffectDescription::mMode protected
Definition at line 56 of file CQEffectDescription.h.
Referenced by applyToScene(), getMode(), and setMode().
qreal CQEffectDescription::mScaleEnd protected
Definition at line 55 of file CQEffectDescription.h.
Referenced by applyToScene(), getScaleEnd(), and setScaleEnd().
qreal CQEffectDescription::mScaleStart protected
Definition at line 54 of file CQEffectDescription.h.
Referenced by applyToScene(), getScaleStart(), and setScaleStart().
QColor CQEffectDescription::mStartColor protected
Definition at line 52 of file CQEffectDescription.h.
Referenced by applyToScene(), getStartColor(), and setStartColor().
The documentation for this class was generated from the following files:
CQEffectDescription.h
CQEffectDescription.cpp