COPASI API: CQBiologicalDescriptionDM Class Reference
CQBiologicalDescriptionDM Class Reference
#include <CQBiologicalDescriptionDM.h>
Public Member Functions
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const
CQBiologicalDescriptionDM (CMIRIAMInfo *MIRIAMInfo, QObject *parent=0)
QVariant data (const QModelIndex &index, int role) const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
bool removeRows (QModelIndexList rows, const QModelIndex &index=QModelIndex())
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Public Member Functions inherited from CQBaseDataModel
virtual bool clear ()
CQBaseDataModel (QObject *parent=0)
QString createNewName (const QString name, const int nameCol)
virtual Qt::ItemFlags flags (const QModelIndex &index) const
bool insertRow ()
virtual bool isDefaultRow (const QModelIndex &i) const
bool removeRow (int position)
Protected Member Functions
bool insertRows (int position, int rows, const QModelIndex &index=QModelIndex())
bool removeRows (int position, int rows, const QModelIndex &index=QModelIndex())
Protected Attributes
CMIRIAMInfo * mpMIRIAMInfo
Additional Inherited Members
Signals inherited from CQBaseDataModel
void notifyGUI (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Detailed Description
Definition at line 31 of file CQBiologicalDescriptionDM.h.
Constructor & Destructor Documentation
CQBiologicalDescriptionDM::CQBiologicalDescriptionDM (CMIRIAMInfo * MIRIAMInfo, QObject * parent = 0)
Definition at line 26 of file CQBiologicalDescriptionDM.cpp.
References mpMIRIAMInfo.
     : CQBaseDataModel(parent)
 {
   mpMIRIAMInfo = MIRIAMInfo;
 }
Member Function Documentation
int CQBiologicalDescriptionDM::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 37 of file CQBiologicalDescriptionDM.cpp.
References TOTAL_COLS_BIOLOGICAL_DESCRIPTIONS.
 {
   return TOTAL_COLS_BIOLOGICAL_DESCRIPTIONS;
 }
QVariant CQBiologicalDescriptionDM::data (const QModelIndex & index, int role) const virtual
Implements CQBaseDataModel.
Definition at line 42 of file CQBiologicalDescriptionDM.cpp.
References COL_ID_BD, COL_RELATIONSHIP, COL_RESOURCE_BD, COL_ROW_NUMBER, FROM_UTF8, CMIRIAMInfo::getBiologicalDescriptions(), CQBaseDataModel::isDefaultRow(), mpMIRIAMInfo, and rowCount().
Referenced by removeRows().
 {
   if (!index.isValid())
     return QVariant();
   if (index.row() >= rowCount())
     return QVariant();
   if (role == Qt::DisplayRole || role == Qt::EditRole)
     {
       if (isDefaultRow(index))
         {
           if (index.column() == COL_RELATIONSHIP || index.column() == COL_RESOURCE_BD)
             return QVariant(QString("-- select --"));
           else if (index.column() == COL_ROW_NUMBER)
             return QVariant(QString(""));
           else
             return QVariant(QString(""));
         }
       else
         {
           switch (index.column())
             {
               case COL_ROW_NUMBER:
                 return QVariant(index.row() + 1);
               case COL_RELATIONSHIP:
                 return QVariant(QString(FROM_UTF8(mpMIRIAMInfo->getBiologicalDescriptions()[index.row()]->getPredicate())));
               case COL_RESOURCE_BD:
                 return QVariant(QString(FROM_UTF8(mpMIRIAMInfo->getBiologicalDescriptions()[index.row()]->getResource())));
               case COL_ID_BD:
                 return QVariant(QString(FROM_UTF8(mpMIRIAMInfo->getBiologicalDescriptions()[index.row()]->getId())));
             }
         }
     }
   return QVariant();
 }
QVariant CQBiologicalDescriptionDM::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Implements CQBaseDataModel.
Definition at line 80 of file CQBiologicalDescriptionDM.cpp.
References COL_ID_BD, COL_RELATIONSHIP, COL_RESOURCE_BD, and COL_ROW_NUMBER.
 {
   if (role != Qt::DisplayRole)
     return QVariant();
   if (orientation == Qt::Horizontal)
     {
       switch (section)
         {
           case COL_ROW_NUMBER:
             return QVariant(QString("#"));
           case COL_RELATIONSHIP:
             return QVariant(QString("Relationship"));
           case COL_RESOURCE_BD:
             return QVariant(QString("                 Resource                 "));
           case COL_ID_BD:
             return QVariant(QString("ID"));
           default:
             return QVariant();
         }
     }
   else
     return QString("%1").arg(section + 1);
 }
bool CQBiologicalDescriptionDM::insertRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 140 of file CQBiologicalDescriptionDM.cpp.
References ListViews::ADD, CMIRIAMInfo::createBiologicalDescription(), ListViews::MIRIAM, mpMIRIAMInfo, and CQBaseDataModel::notifyGUI().
 {
   beginInsertRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       mpMIRIAMInfo->createBiologicalDescription();
     }
   endInsertRows();
   emit notifyGUI(ListViews::MIRIAM, ListViews::ADD, "");
   return true;
 }
bool CQBiologicalDescriptionDM::removeRows (QModelIndexList rows, const QModelIndex & index = QModelIndex())
Definition at line 172 of file CQBiologicalDescriptionDM.cpp.
References C_INVALID_INDEX, COL_ID_BD, COL_RESOURCE_BD, data(), CMIRIAMInfo::getBiologicalDescriptions(), CQBaseDataModel::isDefaultRow(), mpMIRIAMInfo, CQMessageBox::question(), and CQBaseDataModel::removeRow().
Referenced by CQMiriamWidget::deleteSelectedBiologicalDescriptions().
 {
   if (rows.isEmpty())
     return false;
 //Build the list of pointers to items to be deleted
 //before actually deleting any item.
   QList <CBiologicalDescription *> pBiologicalDescriptions;
   QModelIndexList::const_iterator i;
   for (i = rows.begin(); i != rows.end(); ++i)
     {
       if (!isDefaultRow(*i) && mpMIRIAMInfo->getBiologicalDescriptions()[(*i).row()])
         pBiologicalDescriptions.append(mpMIRIAMInfo->getBiologicalDescriptions()[(*i).row()]);
     }
   bool retVal = false, askEveryItem = true;
   QMessageBox::StandardButton choice = QMessageBox::NoToAll;
   QList <CBiologicalDescription *>::const_iterator j;
   for (j = pBiologicalDescriptions.begin(); j != pBiologicalDescriptions.end(); ++j)
     {
       CBiologicalDescription * pBiologicalDescription = *j;
       size_t delRow =
         mpMIRIAMInfo->getBiologicalDescriptions().CCopasiVector< CBiologicalDescription >::getIndex(pBiologicalDescription);
       if (delRow != C_INVALID_INDEX)
         {
           if (askEveryItem)
             {
               QString resource = data(this->index((int) delRow, COL_RESOURCE_BD), Qt::DisplayRole).toString();
               QString Id = data(this->index((int) delRow, COL_ID_BD), Qt::DisplayRole).toString();
               QString msg = "Do you want to delete Description '";
               if (!resource.isNull())
                 {
                   msg.append(resource);
                 }
               if (!Id.isNull())
                 {
                   msg.append(":");
                   msg.append(Id);
                 }
               msg.append("'?");
               choice = CQMessageBox::question(NULL, tr("Confirm Delete"), msg,
                                               QMessageBox::Yes | QMessageBox::YesToAll | QMessageBox::No | QMessageBox::NoToAll,
                                               QMessageBox::No);
             }
           if (choice == QMessageBox::NoToAll)
             {return retVal;}
           else if (choice == QMessageBox::Yes)
             {retVal = removeRow((int) delRow);}
           else if (choice == QMessageBox::YesToAll)
             {
               askEveryItem = false;
               retVal = removeRow((int) delRow);
             }
         }
     }
   return true;
 }
bool CQBiologicalDescriptionDM::removeRows (int position, int rows, const QModelIndex & index = QModelIndex()) protected virtual
Implements CQBaseDataModel.
Definition at line 154 of file CQBiologicalDescriptionDM.cpp.
References ListViews::DELETE, ListViews::MIRIAM, mpMIRIAMInfo, CQBaseDataModel::notifyGUI(), and CMIRIAMInfo::removeBiologicalDescription().
 {
   if (rows <= 0)
     return true;
   beginRemoveRows(QModelIndex(), position, position + rows - 1);
   for (int row = 0; row < rows; ++row)
     {
       mpMIRIAMInfo->removeBiologicalDescription(position);
     }
   endRemoveRows();
   emit notifyGUI(ListViews::MIRIAM, ListViews::DELETE, "");
   return true;
 }
int CQBiologicalDescriptionDM::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Definition at line 33 of file CQBiologicalDescriptionDM.cpp.
References CMIRIAMInfo::getBiologicalDescriptions(), mpMIRIAMInfo, and CCopasiVector< T >::size().
Referenced by data().
 {
   return (int) mpMIRIAMInfo->getBiologicalDescriptions().size() + 1;
 }
bool CQBiologicalDescriptionDM::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Implements CQBaseDataModel.
Definition at line 106 of file CQBiologicalDescriptionDM.cpp.
References ListViews::CHANGE, COL_ID_BD, COL_RELATIONSHIP, COL_RESOURCE_BD, CMIRIAMInfo::getBiologicalDescriptions(), CQBaseDataModel::insertRow(), CQBaseDataModel::isDefaultRow(), ListViews::MIRIAM, mpMIRIAMInfo, CQBaseDataModel::notifyGUI(), and TO_UTF8.
 {
   if (index.isValid() && role == Qt::EditRole)
     {
       if (isDefaultRow(index))
         {
           if (index.data() != value)
             insertRow();
           else
             return false;
         }
       switch (index.column())
         {
           case COL_RELATIONSHIP:
             mpMIRIAMInfo->getBiologicalDescriptions()[index.row()]->setPredicate(TO_UTF8(value.toString()));
             break;
           case COL_RESOURCE_BD:
             mpMIRIAMInfo->getBiologicalDescriptions()[index.row()]->setResource(TO_UTF8(value.toString()));
             break;
           case COL_ID_BD:
             mpMIRIAMInfo->getBiologicalDescriptions()[index.row()]->setId(TO_UTF8(value.toString()));
             break;
         }
       emit dataChanged(index, index);
       emit notifyGUI(ListViews::MIRIAM, ListViews::CHANGE, "");
       return true;
     }
   return false;
 }
Member Data Documentation
CMIRIAMInfo* CQBiologicalDescriptionDM::mpMIRIAMInfo protected
Definition at line 49 of file CQBiologicalDescriptionDM.h.
Referenced by CQBiologicalDescriptionDM(), data(), insertRows(), removeRows(), rowCount(), and setData().
The documentation for this class was generated from the following files:
CQBiologicalDescriptionDM.h
CQBiologicalDescriptionDM.cpp