COPASI API: test000063 Class Reference
test000063 Class Reference
#include <test000063.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_events_1 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING10
static const char * MODEL_STRING11
static const char * MODEL_STRING12
static const char * MODEL_STRING13
static const char * MODEL_STRING14
static const char * MODEL_STRING15
static const char * MODEL_STRING16
static const char * MODEL_STRING17
static const char * MODEL_STRING2
static const char * MODEL_STRING3
static const char * MODEL_STRING4
static const char * MODEL_STRING5
static const char * MODEL_STRING6
static const char * MODEL_STRING7
static const char * MODEL_STRING8
static const char * MODEL_STRING9
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_events_1)
CPPUNIT_TEST_SUITE (test000063)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
This test check if a kinetic law without math element is imported with the correct warning.
Definition at line 30 of file test000063.h.
Member Function Documentation
test000063::CPPUNIT_TEST (test_events_1) private
test000063::CPPUNIT_TEST_SUITE (test000063) private
test000063::CPPUNIT_TEST_SUITE_END () private
void test000063::setUp ()
Definition at line 39 of file test000063.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000063::tearDown ()
Definition at line 47 of file test000063.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000063::test_events_1 ()
Definition at line 52 of file test000063.cpp.
References CCopasiDataModel::getModel(), CCopasiDataModel::importSBMLFromString(), MODEL_STRING1, and pCOPASIDATAMODEL.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(test000063::MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 2);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 0);
   CPPUNIT_ASSERT(pModel->getEvents().size() == 1);
   // run a simulation for 4 seconds and check the values of both species at 1
   // second and at 3 seconds
 }
Member Data Documentation
const char * test000063::MODEL_STRING1 static protected
Simple model with two species. One is determined by an assignment, the other is set in an event assignment.
Definition at line 37 of file test000063.h.
Referenced by test_events_1().
const char * test000063::MODEL_STRING10 static protected
Simple model with two species. Two events trigger at the same time. Each modifies one of the species and references the other species.
Definition at line 46 of file test000063.h.
const char * test000063::MODEL_STRING11 static protected
Simple model with two species. Two events. One triggers at a certain time and modifies one species. This modification triggers the second event at the same time. Although both events trigger at the same point in time, the result should be different from the model above.
Definition at line 47 of file test000063.h.
const char * test000063::MODEL_STRING12 static protected
Simple model with two species. One is determined by an assignment, the other is set in an event assignment. The event has a delay.
Definition at line 48 of file test000063.h.
const char * test000063::MODEL_STRING13 static protected
Simple model with two species. Two events trigger at the same time. Each modifies one of the species and references the other species. Both events use the same delay.
Definition at line 49 of file test000063.h.
const char * test000063::MODEL_STRING14 static protected
Simple model with two species. Two events. One triggers at a certain time and modifies one species. This modification triggers the second event at the same time. Although both events trigger at the same point in time, the result should be different from the model above. Both event use the same delay
Definition at line 50 of file test000063.h.
const char * test000063::MODEL_STRING15 static protected
Simple model with two species. Two events trigger at the same time. Each modifies one of the species and references the other species. Both events use different delays.
Definition at line 51 of file test000063.h.
const char * test000063::MODEL_STRING16 static protected
Simple model with two species. Two events. One triggers at a certain time and modifies one species. This modification triggers the second event at the same time. Although both events trigger at the same point in time, the result should be different from the model above. Both event use different delays.
Definition at line 52 of file test000063.h.
const char * test000063::MODEL_STRING17 static protected
Simple model with two species. One is determined by an ode , the other is set in an event assignment. The delay in the event has to be calculated from the trigger time.
Definition at line 53 of file test000063.h.
const char * test000063::MODEL_STRING2 static protected
Simple model with two species. One is determined by an ode , the other is set in an event assignment.
Definition at line 38 of file test000063.h.
const char * test000063::MODEL_STRING3 static protected
Simple model with two species. The compartment volume is determined by a rate rule. The second species is set by an event that is dependent on the compartment volume.
Definition at line 39 of file test000063.h.
const char * test000063::MODEL_STRING4 static protected
Simple model with two species and a parameter. The parameter is determined by an ode rule. The second species is set by an event that is dependent on the parameter volume.
Definition at line 40 of file test000063.h.
const char * test000063::MODEL_STRING5 static protected
Simple model with two species and two reactions. The second species is set by an event that is dependent on the reaction rate of the second reaction.
Definition at line 41 of file test000063.h.
const char * test000063::MODEL_STRING6 static protected
Simple model with two species and two reactions. The second species is set by an event that is dependent on the reaction rate of the second reaction. The second species is also set by a second time dependent event.
Definition at line 42 of file test000063.h.
const char * test000063::MODEL_STRING7 static protected
Simple model with two species. One species is determined by a rate rule, the other is set by an event that is determined by the first species. The assignment expression references the species itself.
Definition at line 43 of file test000063.h.
const char * test000063::MODEL_STRING8 static protected
Simple model with two species. Both species are set by event assignments. The event is supposed to fire every three seconds from second 2. This is achieved by simulating the modulo function. This model is solely made of events.
Definition at line 44 of file test000063.h.
const char * test000063::MODEL_STRING9 static protected
Simple model with two species. This model represents an event endlessloop. There are three events, the first one triggers when time is greater 1 second and it modifies species_1. The second event is triggered if species_1 becomes larger than species_2 and it enlarges species_2. And the third triggers when species_2 becomes larger than species_1 and enlarger species_1.
Definition at line 45 of file test000063.h.
CCopasiDataModel * test000063::pCOPASIDATAMODEL = NULL static protected
Definition at line 54 of file test000063.h.
Referenced by setUp(), and test_events_1().
The documentation for this class was generated from the following files:
test000063.h
test000063.cpp