COPASI API: CDotOutput Class Reference
CDotOutput Class Reference
#include <CDotOutput.h>
Classes
class ObjectData
Public Member Functions
CDotOutput ()
void setOnlyAlgebraicDependencies (bool b)
void setSkipDependenciesOnCompartments (bool b)
void simpleCall (const CModel *pModel)
void writeDependencies (std::ostream &os, const CModel *pModel, const CCopasiObject *rootNode=NULL)
Protected Member Functions
void findObjectsWithUpdateMethod (const CCopasiObject *obj, std::set< const CCopasiObject * > &objectSet, size_t recursion=0) const
ObjectData * getObjectDataFromRefresh (const Refresh *ref)
void updateObjectNodesFromModel (const CModel *model)
void writeDotRecursively (const CCopasiObject *obj, std::ostream &os)
void writeEdge (std::ostream &os, const CCopasiObject *ptr1, const CCopasiObject *ptr2, bool indirect=false)
void writeObjectNode (std::ostream &os, const CCopasiObject *ptr, const ObjectData &od) const
Protected Attributes
std::map< const CCopasiObject
*, ObjectData > mObjects
bool mOnlyAlgebraicDependencies
bool mSkipCompartments
Detailed Description
Definition at line 34 of file CDotOutput.h.
Constructor & Destructor Documentation
CDotOutput::CDotOutput ()
Definition at line 39 of file CDotOutput.cpp.
     : mSkipCompartments(false),
     mOnlyAlgebraicDependencies(false)
 {}
Member Function Documentation
void CDotOutput::findObjectsWithUpdateMethod (const CCopasiObject * obj, std::set< const CCopasiObject * > & objectSet, size_t recursion = 0) const protected
Definition at line 74 of file CDotOutput.cpp.
References CCopasiObject::getDirectDependencies().
Referenced by writeDotRecursively().
 {
   if (!obj) return;
   if (recursion > 10) return; //limit recursion
   //it is assumed  *obj has no UpdateMethod
   std::set< const CCopasiObject * >::const_iterator it, itEnd = obj->getDirectDependencies().end();
   for (it = obj->getDirectDependencies().begin(); it != itEnd; ++it)
     {
       if ((*it)->hasUpdateMethod())
         objectSet.insert(*it);
       else
         findObjectsWithUpdateMethod(*it, objectSet, recursion + 1);
     }
 }
CDotOutput::ObjectData * CDotOutput::getObjectDataFromRefresh (const Refresh * ref) protected
Definition at line 250 of file CDotOutput.cpp.
References mObjects.
Referenced by updateObjectNodesFromModel().
 {
   std::map <const CCopasiObject*, ObjectData>::iterator it, itEnd = mObjects.end();
   for (it = mObjects.begin(); it != itEnd; ++it)
     {
       if (it->first->getRefresh() == ref) return &it->second;
     }
   return NULL;
 }
void CDotOutput::setOnlyAlgebraicDependencies (bool b) inline
Definition at line 44 of file CDotOutput.h.
References mOnlyAlgebraicDependencies.
Referenced by simpleCall().
 {mOnlyAlgebraicDependencies = b;};
void CDotOutput::setSkipDependenciesOnCompartments (bool b) inline
Definition at line 43 of file CDotOutput.h.
References mSkipCompartments.
Referenced by simpleCall().
 {mSkipCompartments = b;};
void CDotOutput::simpleCall (const CModel * pModel)
Definition at line 262 of file CDotOutput.cpp.
References setOnlyAlgebraicDependencies(), setSkipDependenciesOnCompartments(), and writeDependencies().
 {
   std::ofstream os;
   os.open("CopasiDependencies.dot", std::ios::out);
   setSkipDependenciesOnCompartments(true);
   setOnlyAlgebraicDependencies(true);
   writeDependencies(os, pModel);
   os.close();
 }
void CDotOutput::updateObjectNodesFromModel (const CModel * model) protected
Definition at line 204 of file CDotOutput.cpp.
References CModel::getListOfConstantRefreshes(), CModel::getListOfNonSimulatedRefreshes(), CModel::getListOfSimulatedRefreshes(), getObjectDataFromRefresh(), CModel::getUptoDateObjects(), CDotOutput::ObjectData::mConstantRefreshesIndex, CDotOutput::ObjectData::mNonSimulatedRefreshesIndex, mObjects, and CDotOutput::ObjectData::mSimulatedRefreshesIndex.
Referenced by writeDependencies().
 {
   const std::set< const CCopasiObject * > & objectSet = model->getUptoDateObjects();
   std::set< const CCopasiObject * >::const_iterator it, itEnd = objectSet.end();
   for (it = objectSet.begin(); it != itEnd; ++it)
     {
       mObjects[*it].mInUpToDateList = true;
     }
   size_t i, imax;
   imax = model->getListOfSimulatedRefreshes().size();
   for (i = 0; i < imax; ++i)
     {
       ObjectData * pOD = getObjectDataFromRefresh(model->getListOfSimulatedRefreshes()[i]);
       if (pOD) pOD->mSimulatedRefreshesIndex = i;
     }
   imax = model->getListOfNonSimulatedRefreshes().size();
   for (i = 0; i < imax; ++i)
     {
       ObjectData * pOD = getObjectDataFromRefresh(model->getListOfNonSimulatedRefreshes()[i]);
       if (pOD) pOD->mNonSimulatedRefreshesIndex = i;
     }
   imax = model->getListOfConstantRefreshes().size();
   for (i = 0; i < imax; ++i)
     {
       ObjectData * pOD = getObjectDataFromRefresh(model->getListOfConstantRefreshes()[i]);
       if (pOD) pOD->mConstantRefreshesIndex = i;
     }
   /*   const std::vector< Refresh * > getListOfSimulatedRefreshes() const; //mSimulatedRefreshes;
      const std::vector< Refresh * > getListOfConstantRefreshes() const; //mConstantRefreshes;
      const std::vector< Refresh * > getListOfNonSimulatedRefreshes() const; //mNonSimulatedRefreshes;
   */
 }
void CDotOutput::writeDependencies (std::ostream & os, const CModel * pModel, const CCopasiObject * rootNode = NULL)
Definition at line 44 of file CDotOutput.cpp.
References CCopasiObject::getObjectDataModel(), mObjects, updateObjectNodesFromModel(), writeDotRecursively(), and writeObjectNode().
Referenced by simpleCall().
 {
   const CCopasiObject * obj;
   if (rootNode)
     obj = rootNode;
   else
     obj = pModel->getObjectDataModel();
   mObjects.clear();
   os << "digraph G {\n";
   //edges
   writeDotRecursively(obj, os);
   //this is done after the edges since it requires all relevant object to be in the mObjects map
   updateObjectNodesFromModel(pModel);
   //nodes
   std::map<const CCopasiObject*, ObjectData>::const_iterator it, itEnd = mObjects.end();
   for (it = mObjects.begin(); it != itEnd; ++it)
     {
       writeObjectNode(os, it->first, it->second);
     }
   os << "}" << std::endl;
 }
void CDotOutput::writeDotRecursively (const CCopasiObject * obj, std::ostream & os) protected
Definition at line 93 of file CDotOutput.cpp.
References findObjectsWithUpdateMethod(), CCopasiObject::getDirectDependencies(), CCopasiContainer::getObjects(), CCopasiObject::hasUpdateMethod(), CCopasiObject::isContainer(), mOnlyAlgebraicDependencies, mSkipCompartments, and writeEdge().
Referenced by writeDependencies().
 {
   if ((!mOnlyAlgebraicDependencies) || obj->hasUpdateMethod())
     {
       std::set< const CCopasiObject * >::const_iterator it, itEnd = obj->getDirectDependencies().end();
       for (it = obj->getDirectDependencies().begin(); it != itEnd; ++it)
         {
           //skip deps on compartments
           if (mSkipCompartments)
             if ((*it)->getObjectParent() && ((*it)->getObjectParent()->getObjectType() == "Compartment"
                                              || (*it)->getObjectType() == "Compartment")) continue;
           if (mOnlyAlgebraicDependencies)
             {
               if ((*it)->hasUpdateMethod())
                 {
                   writeEdge(os, obj, *it);
                 }
               else
                 {//find indirect dependencies
                   std::set<const CCopasiObject* > tmpObjectSet;
                   findObjectsWithUpdateMethod(*it, tmpObjectSet);
                   std::set<const CCopasiObject* >::const_iterator tmpIt, tmpItEnd = tmpObjectSet.end();
                   for (tmpIt = tmpObjectSet.begin(); tmpIt != tmpItEnd; ++tmpIt)
                     writeEdge(os, obj, *tmpIt, true); //
                 }
             }
           else
             {
               writeEdge(os, obj, *it);
             }
         }
     }
   //recursion
   if (obj->isContainer())
     {
       CCopasiContainer* container;
       container = (CCopasiContainer*)obj;
       CCopasiContainer::objectMap::const_iterator it = container->getObjects().begin();
       for (; it != container->getObjects().end(); ++it)
         {
           //the next line skips name references...
           if (it->second->getObjectName() == "Name") continue;
           if (it->second->getObjectType() == "Function") continue;
           //skip if the contained object is not owned by this container
           if (it->second->getObjectParent() != container) continue;
           writeDotRecursively(it->second, os);
         }
       //return;
     }
 }
void CDotOutput::writeEdge (std::ostream & os, const CCopasiObject * ptr1, const CCopasiObject * ptr2, bool indirect = false) protected
Definition at line 189 of file CDotOutput.cpp.
References CCopasiObject::getObjectDisplayName(), and mObjects.
Referenced by writeDotRecursively().
 {
   assert(ptr1);
   assert(ptr2);
   mObjects[ptr1];
   mObjects[ptr2];
   os << "\"" << ptr1->getObjectDisplayName() << "\" -> \"" << ptr2->getObjectDisplayName() << "\"";
   if (indirect) os << " [color=blue]";
   os << "\n";
 }
void CDotOutput::writeObjectNode (std::ostream & os, const CCopasiObject * ptr, const ObjectData & od) const protected
Definition at line 155 of file CDotOutput.cpp.
References C_INVALID_INDEX, CCopasiObject::getObjectDisplayName(), CCopasiObject::getRefresh(), CCopasiObject::hasUpdateMethod(), CDotOutput::ObjectData::mConstantRefreshesIndex, CDotOutput::ObjectData::mInUpToDateList, CDotOutput::ObjectData::mNonSimulatedRefreshesIndex, and CDotOutput::ObjectData::mSimulatedRefreshesIndex.
Referenced by writeDependencies().
 {
   os << "//" << std::endl;
   bool flagUM = ptr->hasUpdateMethod();
   bool flagRM = ptr->getRefresh() != NULL;
   bool flagInUpToDateList = od.mInUpToDateList;
   std::ostringstream oss;
   if (od.mSimulatedRefreshesIndex != C_INVALID_INDEX)
     oss << "SR=" << od.mSimulatedRefreshesIndex << " ";
   if (od.mNonSimulatedRefreshesIndex != C_INVALID_INDEX)
     oss << "NSR=" << od.mNonSimulatedRefreshesIndex << " ";
   if (od.mConstantRefreshesIndex != C_INVALID_INDEX)
     oss << "CR=" << od.mConstantRefreshesIndex << " ";
   os << "\"" << ptr->getObjectDisplayName() << "\" [shape=plaintext, color=blue, " << std::endl;
   os << "label=<\n";
   os << "<TABLE CELLSPACING=\"0\">\n";
   os << "  <TR><TD COLSPAN=\"4\">" << ptr->getObjectDisplayName() << "</TD></TR>\n";
   os << "  <TR>\n";
   os << "    <TD " << (flagUM ? "BGCOLOR=\"red\"" : " ") << "><FONT POINT-SIZE=\"7.0\">UM</FONT>" << "" << "</TD>\n";
   os << "    <TD " << (flagRM ? "BGCOLOR=\"green\"" : " ") << "><FONT POINT-SIZE=\"7.0\">RM</FONT>" << "" << "</TD>\n";
   os << "    <TD " << (flagInUpToDateList ? "BGCOLOR=\"blue\"" : " ") << "><FONT POINT-SIZE=\"7.0\">UtD</FONT>" << "" << "</TD>\n";
   os << "    <TD><FONT POINT-SIZE=\"7.0\">" << oss.str() << " </FONT></TD>\n";
   os << "  </TR>\n";
   os << "</TABLE>\n";
   os << "\n";
   os << ">];\n";
 }
Member Data Documentation
std::map<const CCopasiObject*, ObjectData> CDotOutput::mObjects protected
Definition at line 77 of file CDotOutput.h.
Referenced by getObjectDataFromRefresh(), updateObjectNodesFromModel(), writeDependencies(), and writeEdge().
bool CDotOutput::mOnlyAlgebraicDependencies protected
Definition at line 75 of file CDotOutput.h.
Referenced by setOnlyAlgebraicDependencies(), and writeDotRecursively().
bool CDotOutput::mSkipCompartments protected
Definition at line 74 of file CDotOutput.h.
Referenced by setSkipDependenciesOnCompartments(), and writeDotRecursively().
The documentation for this class was generated from the following files:
CDotOutput.h
CDotOutput.cpp