COPASI API: CCopasiParameterGroup.cpp File Reference
CCopasiParameterGroup.cpp File Reference
#include <sstream>
#include "copasi.h"
#include "CCopasiParameterGroup.h"
#include "CCopasiMessage.h"
#include "utilities/utility.h"
Functions
std::ostream & operator<< (std::ostream &os, const CCopasiParameterGroup &o)
bool operator== (const CCopasiParameterGroup &lhs, const CCopasiParameterGroup &rhs)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CCopasiParameterGroup & o)
Output stream operator
Parameters
ostream & os
const CCopasiParameterGroup & o
Returns
ostream & os
Definition at line 199 of file CCopasiParameterGroup.cpp.
References CCopasiObject::getObjectName(), and CCopasiParameterGroup::print().
 {
   os << "<<< Parameter Group: " << o.getObjectName() << std::endl;
   CCopasiParameterGroup::parameterGroup::const_iterator it =
     o.CCopasiParameter::getValue().pGROUP->begin();
   CCopasiParameterGroup::parameterGroup::const_iterator end =
     o.CCopasiParameter::getValue().pGROUP->end();
   for (; it != end; ++it)
     {
       (*it)->print(&os);
       os << std::endl;
     }
   os << ">>> Parameter Group: " << o.getObjectName() << std::endl;
   return os;
 }
bool operator== (const CCopasiParameterGroup & lhs, const CCopasiParameterGroup & rhs)
Comparison operator
Parameters
const CCopasiParameterGroup & lhs
const CCopasiParameterGroup & rhs
Returns
bool equal
Definition at line 218 of file CCopasiParameterGroup.cpp.
References CCopasiObject::getObjectName(), CCopasiParameter::mValue, and CCopasiParameter::Value::pGROUP.
 {
   if (lhs.getObjectName() != rhs.getObjectName()) return false;
   if (lhs.mValue.pGROUP->size() != rhs.mValue.pGROUP->size()) return false;
   CCopasiParameterGroup::parameterGroup::const_iterator itLhs =
     lhs.mValue.pGROUP->begin();
   CCopasiParameterGroup::parameterGroup::const_iterator endLhs =
     lhs.mValue.pGROUP->end();
   CCopasiParameterGroup::parameterGroup::const_iterator itRhs =
     rhs.mValue.pGROUP->begin();
   for (; itLhs != endLhs; ++itLhs, ++itRhs)
     if (!(**itLhs == **itRhs)) return false;
   return true;
 }