COPASI API: CMathObject.h File Reference
CMathObject.h File Reference
#include <set>
#include <map>
#include "copasi/report/CCopasiObject.h"
#include "copasi/math/CMathEnum.h"
Classes
class CMathObject
Functions
std::ostream & operator<< (std::ostream &os, const CMathObject &o)
Function Documentation
std::ostream& operator<< (std::ostream & os, const CMathObject & o)
Definition at line 1229 of file CMathObject.cpp.
References CMath::Analysis, CMath::Assignment, CEvaluationNode::buildInfix(), CMath::Compartment, CMath::Conversion, CMath::Dependent, CMath::DependentMass, CMath::Discontinuous, CMath::EntityTypeUndefined, CMath::Event, CMath::EventAssignment, CMath::EventDelay, CMath::EventPriority, CMath::EventRoot, CMath::EventRootState, CMath::EventTarget, CMath::EventTrigger, CMath::Fixed, CMath::Flux, CMathObject::getCN(), CCopasiObject::getCN(), CEvaluationTree::getRoot(), CMath::GlobalQuantity, CMath::Independent, CMath::LocalReactionParameter, CMathObject::mEntityType, CMathObject::mIsInitialValue, CMathObject::mIsIntensiveProperty, CMath::Model, CMath::Moiety, CMathObject::mpDataObject, CMathObject::mpExpression, CMathObject::mpIntensiveProperty, CMathObject::mpValue, CMathObject::mSimulationType, CMathObject::mValueType, CMath::ODE, CMath::ParticleFlux, CMath::Propensity, CMath::Rate, CMath::Reaction, CMath::SimulationTypeUndefined, CMath::Species, CMath::StoichiometricCoefficients, CMath::Time, CMath::TotalMass, CMath::Value, and CMath::ValueTypeUndefined.
 {
   if (o.mpDataObject != NULL)
     {
       os << o.mpDataObject->getCN() << std::endl;
     }
   else
     {
       os << "Data Object = NULL" << std::endl;
     }
   os << "  Pointer:               " << &o << std::endl;
   os << "  Value Type:            ";
   switch (o.mValueType)
     {
       case CMath::ValueTypeUndefined:
         os << "ValueTypeUndefined" << std::endl;
         break;
       case CMath::Value:
         os << "Value" << std::endl;
         break;
       case CMath::Rate:
         os << "ValueRate" << std::endl;
         break;
       case CMath::ParticleFlux:
         os << "ParticleFlux" << std::endl;
         break;
       case CMath::Flux:
         os << "Flux" << std::endl;
         break;
       case CMath::Propensity:
         os << "Propensity" << std::endl;
         break;
       case CMath::TotalMass:
         os << "TotalMass" << std::endl;
         break;
       case CMath::DependentMass:
         os << "DependentMass" << std::endl;
         break;
       case CMath::Discontinuous:
         os << "Discontinuous" << std::endl;
         break;
       case CMath::EventDelay:
         os << "EventDelay" << std::endl;
         break;
       case CMath::EventPriority:
         os << "EventPriority" << std::endl;
         break;
       case CMath::EventAssignment:
         os << "EventAssignment" << std::endl;
         break;
       case CMath::EventTrigger:
         os << "EventTrigger" << std::endl;
         break;
       case CMath::EventRoot:
         os << "EventRoot" << std::endl;
         break;
       case CMath::EventRootState:
         os << "EventRootState" << std::endl;
         break;
     }
   os << "  Simulation Type:       ";
   switch (o.mSimulationType)
     {
       case CMath::SimulationTypeUndefined:
         os << "SimulationTypeUndefined" << std::endl;
         break;
       case CMath::Fixed:
         os << "Fixed" << std::endl;
         break;
       case CMath::EventTarget:
         os << "EventTarget" << std::endl;
         break;
       case CMath::Time:
         os << "Time" << std::endl;
         break;
       case CMath::ODE:
         os << "ODE" << std::endl;
         break;
       case CMath::Independent:
         os << "Independent" << std::endl;
         break;
       case CMath::Dependent:
         os << "Dependent" << std::endl;
         break;
       case CMath::Assignment:
         os << "Assignment" << std::endl;
         break;
       case CMath::Conversion:
         os << "Conversion" << std::endl;
         break;
     };
   os << "  Entity Type:           ";
   switch (o.mEntityType)
     {
       case CMath::EntityTypeUndefined:
         os << "EntityTypeUndefined" << std::endl;
         break;
       case CMath::Model:
         os << "Model" << std::endl;
         break;
       case CMath::Analysis:
         os << "Analysis" << std::endl;
         break;
       case CMath::GlobalQuantity:
         os << "GlobalQuantity" << std::endl;
         break;
       case CMath::Compartment:
         os << "Compartment" << std::endl;
         break;
       case CMath::Species:
         os << "Species" << std::endl;
         break;
       case CMath::LocalReactionParameter:
         os << "LocalReactionParameter" << std::endl;
         break;
       case CMath::StoichiometricCoefficients:
         os << "StoichiometricCoefficients" << std::endl;
         break;
       case CMath::Reaction:
         os << "Reaction" << std::endl;
         break;
       case CMath::Moiety:
         os << "Moiety" << std::endl;
         break;
       case CMath::Event:
         os << "Event" << std::endl;
         break;
     };
   os << "  Is Intensive Property: " << (o.mIsIntensiveProperty ? "true" : "false") << std::endl;
   os << "  Is Initial Value:      " << (o.mIsInitialValue ? "true" : "false") << std::endl;
   os << "  Intensive Property:    ";
   if (o.mpIntensiveProperty != NULL)
     {
       os << o.mpIntensiveProperty->getCN() << std::endl;
     }
   else
     {
       os << "NULL" << std::endl;
     }
   os << "  Value:                 " << *o.mpValue << " (" << o.mpValue << ")" << std::endl;
   os << "  Expression:            ";
   if (o.mpExpression != NULL)
     {
       os << o.mpExpression->getRoot()->buildInfix() << std::endl;
     }
   else
     {
       os << "NULL" << std::endl;
     }
   // CObjectInterface::ObjectSet mPrerequisites;
   return os;
 }