COPASI API: CQFunctionsWidget Class Reference
CQFunctionsWidget Class Reference
#include <CQFunctionsWidget.h>
Public Member Functions
CQFunctionsWidget (QWidget *parent=0, const char *name=0)
virtual bool leave ()
virtual bool update (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key)
~CQFunctionsWidget ()
Public Member Functions inherited from CopasiWidget
CopasiWidget (QWidget *parent=0, const char *name=0, Qt::WFlags f=0)
bool enter (const std::string &key)
CCopasiDataModel * getDataModel ()
bool getIgnoreUpdates ()
virtual void setFramework (int framework)
void setIgnoreUpdates (bool v)
Protected Slots
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
virtual void slotBtnClearClicked ()
virtual void slotBtnDeleteClicked ()
virtual void slotBtnNewClicked ()
virtual void slotDoubleClicked (const QModelIndex proxyIndex)
virtual void slotFilterChanged ()
virtual void slotSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Protected Slots inherited from CopasiWidget
virtual bool protectedNotify (ListViews::ObjectType objectType, ListViews::Action action, const std::string &key="")
Protected Member Functions
virtual bool enterProtected ()
virtual void keyPressEvent (QKeyEvent *ev)
Private Member Functions
void deleteSelectedFunctions ()
void updateDeleteBtns ()
Private Attributes
CQFunctionDM * mpFunctionDM
CQSortFilterProxyModel * mpProxyModel
Additional Inherited Members
Protected Attributes inherited from CopasiWidget
int mFramework
bool mIgnoreUpdates
std::string mKey
CCopasiDataModel * mpDataModel
ListViews * mpListView
CCopasiObject * mpObject
Detailed Description
Definition at line 29 of file CQFunctionsWidget.h.
Constructor & Destructor Documentation
CQFunctionsWidget::CQFunctionsWidget (QWidget * parent = 0, const char * name = 0)
Definition at line 31 of file CQFunctionsWidget.cpp.
References COL_ROW_NUMBER, dataChanged(), mpFunctionDM, mpProxyModel, CopasiWidget::protectedNotify(), and slotFilterChanged().
   : CopasiWidget(parent, name)
 {
   setupUi(this);
   //Create Source Data Model.
   mpFunctionDM = new CQFunctionDM(this);
   //Create the Proxy Model for sorting/filtering and set its properties.
   mpProxyModel = new CQSortFilterProxyModel();
   mpProxyModel->setSortCaseSensitivity(Qt::CaseInsensitive);
   mpProxyModel->setFilterKeyColumn(-1);
   mpTblFunctions->verticalHeader()->setResizeMode(QHeaderView::ResizeToContents);
   mpTblFunctions->verticalHeader()->hide();
   mpTblFunctions->sortByColumn(COL_ROW_NUMBER, Qt::AscendingOrder);
   // Connect the table widget
   connect(mpFunctionDM, SIGNAL(notifyGUI(ListViews::ObjectType, ListViews::Action, const std::string)),
           this, SLOT(protectedNotify(ListViews::ObjectType, ListViews::Action, const std::string)));
   connect(mpFunctionDM, SIGNAL(dataChanged(const QModelIndex&, const QModelIndex&)),
           this, SLOT(dataChanged(const QModelIndex&, const QModelIndex&)));
   connect(mpLEFilter, SIGNAL(textChanged(const QString &)),
           this, SLOT(slotFilterChanged()));
 }
CQFunctionsWidget::~CQFunctionsWidget ()
Definition at line 60 of file CQFunctionsWidget.cpp.
References mpFunctionDM, mpProxyModel, and pdelete.
 {
   pdelete(mpProxyModel);
   pdelete(mpFunctionDM);
   // no need to delete child widgets, Qt does it all for us
 }
Member Function Documentation
void CQFunctionsWidget::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
Definition at line 186 of file CQFunctionsWidget.cpp.
References updateDeleteBtns().
Referenced by CQFunctionsWidget().
 {
   mpTblFunctions->resizeColumnsToContents();
   updateDeleteBtns();
 }
void CQFunctionsWidget::deleteSelectedFunctions () private
Definition at line 81 of file CQFunctionsWidget.cpp.
References mpFunctionDM, mpProxyModel, CQFunctionDM::removeRows(), and CQFunctionDM::rowCount().
Referenced by slotBtnDeleteClicked().
 {
   const QItemSelectionModel * pSelectionModel = mpTblFunctions->selectionModel();
   QModelIndexList mappedSelRows;
   size_t i, imax = mpFunctionDM->rowCount();
   for (i = 0; i < imax; i++)
     {
       if (pSelectionModel->isRowSelected((int) i, QModelIndex()))
         {
           mappedSelRows.append(mpProxyModel->mapToSource(mpProxyModel->index((int) i, 0)));
         }
     }
   if (mappedSelRows.empty())
     {return;}
   mpFunctionDM->removeRows(mappedSelRows);
 }
bool CQFunctionsWidget::enterProtected () protected virtual
Reimplemented from CopasiWidget.
Definition at line 131 of file CQFunctionsWidget.cpp.
References mpFunctionDM, mpProxyModel, slotSelectionChanged(), and updateDeleteBtns().
Referenced by update().
 {
   if (mpTblFunctions->selectionModel() != NULL)
     {
       disconnect(mpTblFunctions->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
                  this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
     }
   mpProxyModel->setSourceModel(mpFunctionDM);
   //Set Model for the TableView
   mpTblFunctions->setModel(NULL);
   mpTblFunctions->setModel(mpProxyModel);
   connect(mpTblFunctions->selectionModel(), SIGNAL(selectionChanged(const QItemSelection&, const QItemSelection&)),
           this, SLOT(slotSelectionChanged(const QItemSelection&, const QItemSelection&)));
   updateDeleteBtns();
   mpTblFunctions->resizeColumnsToContents();
   return true;
 }
void CQFunctionsWidget::keyPressEvent (QKeyEvent * ev) protected virtual
Definition at line 211 of file CQFunctionsWidget.cpp.
References CQFunctionDM::columnCount(), mpFunctionDM, mpProxyModel, and slotBtnDeleteClicked().
 {
   if (ev->key() == Qt::Key_Delete)
     slotBtnDeleteClicked();
   else if (ev->key() == Qt::Key_C && (ev->modifiers() & Qt::ControlModifier))
     {
       QModelIndexList selRows = mpTblFunctions->selectionModel()->selectedRows(0);
       if (selRows.empty())
         {return;}
       QString str;
       QModelIndexList::const_iterator i;
       for (i = selRows.begin(); i != selRows.end(); ++i)
         {
           for (int x = 0; x < mpFunctionDM->columnCount(); ++x)
             {
               if (!mpTblFunctions->isColumnHidden(x))
                 {
                   if (!str.isEmpty())
                     str += "\t";
                   str += mpFunctionDM->index(mpProxyModel->mapToSource(*i).row(), x).data().toString();
                 }
             }
           str += "\n";
         }
       QApplication::clipboard()->setText(str);
     }
 }
bool CQFunctionsWidget::leave () virtual
Reimplemented from CopasiWidget.
Definition at line 126 of file CQFunctionsWidget.cpp.
 {
   return true;
 }
void CQFunctionsWidget::slotBtnClearClicked () protected virtual slot
Definition at line 102 of file CQFunctionsWidget.cpp.
References CQBaseDataModel::clear(), mpFunctionDM, CQMessageBox::question(), and updateDeleteBtns().
 {
   int ret = CQMessageBox::question(this, tr("Confirm Delete"), "Delete all Functions?",
                                    QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
   if (ret == QMessageBox::Yes)
     {
       mpFunctionDM->clear();
     }
   updateDeleteBtns();
 }
void CQFunctionsWidget::slotBtnDeleteClicked () protected virtual slot
Definition at line 73 of file CQFunctionsWidget.cpp.
References deleteSelectedFunctions(), and updateDeleteBtns().
Referenced by keyPressEvent().
 {
   if (mpTblFunctions->hasFocus())
     {deleteSelectedFunctions();}
   updateDeleteBtns();
 }
void CQFunctionsWidget::slotBtnNewClicked () protected virtual slot
Definition at line 67 of file CQFunctionsWidget.cpp.
References CQBaseDataModel::insertRow(), mpFunctionDM, and updateDeleteBtns().
Referenced by slotDoubleClicked().
 {
   mpFunctionDM->insertRow();
   updateDeleteBtns();
 }
void CQFunctionsWidget::slotDoubleClicked (const QModelIndex proxyIndex) protected virtual slot
Definition at line 193 of file CQFunctionsWidget.cpp.
References C_INVALID_INDEX, CCopasiRootContainer::getFunctionList(), CCopasiObject::getKey(), CCopasiRootContainer::getKeyFactory(), CQBaseDataModel::isDefaultRow(), CFunctionDB::loadedFunctions(), mpFunctionDM, CopasiWidget::mpListView, mpProxyModel, slotBtnNewClicked(), and ListViews::switchToOtherWidget().
 {
   QModelIndex index = mpProxyModel->mapToSource(proxyIndex);
   if (index.row() < 0)
     return;
   if (mpFunctionDM->isDefaultRow(index))
     {
       slotBtnNewClicked();
     }
   std::string key = CCopasiRootContainer::getFunctionList()->loadedFunctions()[index.row()]->getKey();
   if (CCopasiRootContainer::getKeyFactory()->get(key))
     mpListView->switchToOtherWidget(C_INVALID_INDEX, key);
 }
void CQFunctionsWidget::slotFilterChanged () protected virtual slot
Definition at line 245 of file CQFunctionsWidget.cpp.
References mpProxyModel.
Referenced by CQFunctionsWidget().
 {
   QRegExp regExp(mpLEFilter->text() + "|New Function", Qt::CaseInsensitive, QRegExp::RegExp);
   mpProxyModel->setFilterRegExp(regExp);
 }
void CQFunctionsWidget::slotSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
Definition at line 180 of file CQFunctionsWidget.cpp.
References updateDeleteBtns().
Referenced by enterProtected().
 {
   updateDeleteBtns();
 }
bool CQFunctionsWidget::update (ListViews::ObjectType objectType, ListViews::Action action, const std::string & key) virtual
Reimplemented from CopasiWidget.
Definition at line 116 of file CQFunctionsWidget.cpp.
References enterProtected(), and CopasiWidget::mIgnoreUpdates.
 {
   if (!mIgnoreUpdates)
     {
       enterProtected();
     }
   return true;
 }
void CQFunctionsWidget::updateDeleteBtns () private
Definition at line 151 of file CQFunctionsWidget.cpp.
References CQBaseDataModel::isDefaultRow(), mpFunctionDM, and mpProxyModel.
Referenced by dataChanged(), enterProtected(), slotBtnClearClicked(), slotBtnDeleteClicked(), slotBtnNewClicked(), and slotSelectionChanged().
 {
   bool selected = false;
   QModelIndexList selRows = mpTblFunctions->selectionModel()->selectedRows();
   if (selRows.size() == 0)
     selected = false;
   else
     {
       if (selRows.size() == 1)
         {
           if (mpFunctionDM->isDefaultRow(mpProxyModel->mapToSource(selRows[0])))
             selected = false;
           else
             selected = true;
         }
       else
         selected = true;
     }
   mpBtnDelete->setEnabled(selected);
   if (mpProxyModel->rowCount() - 1)
     mpBtnClear->setEnabled(true);
   else
     mpBtnClear->setEnabled(false);
 }
Member Data Documentation
CQFunctionDM* CQFunctionsWidget::mpFunctionDM private
Definition at line 44 of file CQFunctionsWidget.h.
Referenced by CQFunctionsWidget(), deleteSelectedFunctions(), enterProtected(), keyPressEvent(), slotBtnClearClicked(), slotBtnNewClicked(), slotDoubleClicked(), updateDeleteBtns(), and ~CQFunctionsWidget().
CQSortFilterProxyModel* CQFunctionsWidget::mpProxyModel private
Definition at line 45 of file CQFunctionsWidget.h.
Referenced by CQFunctionsWidget(), deleteSelectedFunctions(), enterProtected(), keyPressEvent(), slotDoubleClicked(), slotFilterChanged(), updateDeleteBtns(), and ~CQFunctionsWidget().
The documentation for this class was generated from the following files:
CQFunctionsWidget.h
CQFunctionsWidget.cpp