COPASI API: CFunctionParameters Class Reference
CFunctionParameters Class Reference
#include <CFunctionParameters.h>
Public Member Functions
void add (const CFunctionParameter &parameter)
bool add (CFunctionParameter *parameter, const bool &adopt=false)
bool add (const std::string &name, const CFunctionParameter::DataType &type, CFunctionParameter::Role usage)
CFunctionParameters (const std::string &name="NoName", const CCopasiContainer *pParent=NULL)
CFunctionParameters (const CFunctionParameters &src, const CCopasiContainer *pParent=NULL)
void cleanup ()
size_t findParameterByName (const std::string &name, CFunctionParameter::DataType &dataType) const
size_t getNumberOfParametersByUsage (CFunctionParameter::Role usage) const
const CFunctionParameter * getParameterByUsage (CFunctionParameter::Role usage, size_t &pos) const
bool isVector (CFunctionParameter::Role role) const
CFunctionParameters & operator= (const CFunctionParameters &src)
bool operator== (const CFunctionParameters &rhs) const
CFunctionParameter * operator[] (size_t index)
const CFunctionParameter * operator[] (size_t index) const
CFunctionParameter * operator[] (const std::string &name)
const CFunctionParameter * operator[] (const std::string &name) const
void remove (const std::string &name)
size_t size () const
void swap (const size_t &from, const size_t &to)
~CFunctionParameters ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
virtual const std::string & getKey () const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Private Attributes
CCopasiVectorNS
< CFunctionParameter > mParameters
Friends
std::ostream & operator<< (std::ostream &os, const CFunctionParameters &d)
Additional Inherited Members
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
CFunctionParameters
Created for COPASI by Stefan Hoops (C) Stefan Hoops 2001
Definition at line 30 of file CFunctionParameters.h.
Constructor & Destructor Documentation
CFunctionParameters::CFunctionParameters (const std::string & name = "NoName", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
CFunctionParameters
Created for Copasi by Stefan Hoops (C) Stefan Hoops 2001
Definition at line 29 of file CFunctionParameters.cpp.
References CONSTRUCTOR_TRACE.
                                      :
     CCopasiContainer(name, pParent, "Variable Description"),
     mParameters("Variables", this)
 {CONSTRUCTOR_TRACE;}
CFunctionParameters::CFunctionParameters (const CFunctionParameters & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CFunctionParameters & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 35 of file CFunctionParameters.cpp.
References CONSTRUCTOR_TRACE.
                                      :
     CCopasiContainer(src, pParent),
     mParameters(src.mParameters, this)
 {CONSTRUCTOR_TRACE;}
CFunctionParameters::~CFunctionParameters ()
Destructor
Definition at line 41 of file CFunctionParameters.cpp.
References DESTRUCTOR_TRACE.
 {DESTRUCTOR_TRACE;}
Member Function Documentation
void CFunctionParameters::add (const CFunctionParameter & parameter)
Add a parameter to the parameter list
Parameters
const CFunctionParameter & parameter
Definition at line 54 of file CFunctionParameters.cpp.
References CCopasiVectorN< CType >::add(), and mParameters.
Referenced by CFunction::addVariable(), FunctionWidget1::copyFunctionContentsToFunction(), CKinFunction::createParameters(), CFunction::initVariables(), CMassAction::setInfix(), and CCopasiXMLParser::ParameterDescriptionElement::start().
 {
   mParameters.add(parameter);
 }
bool CFunctionParameters::add (CFunctionParameter * parameter, const bool & adopt = false)
Add a parameter to the parameter list
Parameters
CFunctionParameter * parameter
const bool & adopt (Default: false)
Returns
bool success
Definition at line 59 of file CFunctionParameters.cpp.
References CCopasiVectorN< CType >::add(), and mParameters.
 {
   mParameters.add(parameter, adopt);
   return true;
 }
bool CFunctionParameters::add (const std::string & name, const CFunctionParameter::DataType & type, CFunctionParameter::Role usage)
Add a parameter to the parameter list
Parameters
"const string & name
const CFunctionParameter::DataType & type
const string & usage
Returns
bool success
Definition at line 67 of file CFunctionParameters.cpp.
References CCopasiVectorN< CType >::add(), C_INVALID_INDEX, CCopasiVectorN< CType >::getIndex(), and mParameters.
 {
   size_t Index = mParameters.getIndex(name);
   if (Index != C_INVALID_INDEX)
     return false;
   CFunctionParameter *parameter =
     new CFunctionParameter(name, type, usage);
   mParameters.add(parameter, true);
   return true;
 }
void CFunctionParameters::cleanup ()
Cleanup
Definition at line 43 of file CFunctionParameters.cpp.
References CCopasiVector< T >::cleanup(), and mParameters.
Referenced by CKinFunction::createParameters(), and CMassAction::setInfix().
 {
   mParameters.cleanup();
 }
size_t CFunctionParameters::findParameterByName (const std::string & name, CFunctionParameter::DataType & dataType) const
find a parameter by its name and return its index
Definition at line 136 of file CFunctionParameters.cpp.
References C_INVALID_INDEX, CCopasiObject::getObjectName(), mParameters, and CCopasiVector< T >::size().
Referenced by FunctionWidget1::copyFunctionContentsToFunction(), CFunctionParameterMap::findParameterByName(), CFunction::getVariableIndex(), CFunction::initVariables(), CCopasiXMLParser::ParameterDescriptionElement::start(), and CReaction::variable2object().
 {
   //std::string VectorName = name.substr(0, name.find_last_of('_'));
   std::string Name;
   size_t i, imax = mParameters.size();
   for (i = 0; i < imax; i++)
     {
       Name = mParameters[i]->getObjectName();
       if (Name == name)
         {
           dataType = mParameters[i]->getType();
           return i;
         }
     }
   return C_INVALID_INDEX;
 }
size_t CFunctionParameters::getNumberOfParametersByUsage (CFunctionParameter::Role usage) const
gets the number of Parameters with a specific usage
Definition at line 125 of file CFunctionParameters.cpp.
References mParameters, and CCopasiVector< T >::size().
Referenced by CFunctionAnalyzer::checkKineticFunction(), CReactionInterface::connectFromScratch(), CReaction::initializeParameters(), CReactionInterface::isLocked(), CFunction::isSuitable(), CReaction::loadOld(), CReaction::loadOneRole(), FunctionWidget1::loadUsageTable(), and CReactionInterface::setMapping().
 {
   size_t i, imax = mParameters.size();
   size_t count = 0;
   for (i = 0; i < imax; i++)
     if (mParameters[i]->getUsage() == usage) ++count;
   return count;
 }
const CFunctionParameter * CFunctionParameters::getParameterByUsage (CFunctionParameter::Role usage, size_t & pos) const
Retrieves the first parameter with the specified usage after pos In a normal situation pos is set to 0 for the first call. It is increment by the method to allow subsequent searches to start after the last found item. This is usefull if several parameters with the same usage exist.
Parameters
const string & usage
size_t & pos (first call should be with 0)
Returns
"CFunctionParameter &" usageRange
Definition at line 106 of file CFunctionParameters.cpp.
References MCFunctionParameters, mParameters, CFunctionParameter::RoleNameDisplay, CCopasiVector< T >::size(), and CCopasiMessage::WARNING.
Referenced by CReactionInterface::connectFromScratch(), CReaction::initializeParameters(), CReactionInterface::isLocked(), CReaction::loadOld(), CReaction::loadOneRole(), and CReactionInterface::setMapping().
 {
   size_t i, imax = mParameters.size();
   for (i = pos; i < imax; i++)
     if (mParameters[i]->getUsage() == usage)
       {
         pos = i + 1;
         return mParameters[i];
       }
   CCopasiMessage(CCopasiMessage::WARNING,
                  MCFunctionParameters + 2,
                  CFunctionParameter::RoleNameDisplay[usage].c_str(), pos);
   return NULL;
 }
bool CFunctionParameters::isVector (CFunctionParameter::Role role) const
tells whether there is a parameter with vector type and the given role (if there is one it is assumed it is the only one with this role)
Definition at line 157 of file CFunctionParameters.cpp.
References mParameters, CCopasiVector< T >::size(), and CFunctionParameter::VINT32.
Referenced by CFunction::isSuitable(), CReaction::loadOneRole(), and FunctionWidget1::loadUsageTable().
 {
   size_t i, imax = mParameters.size();
   for (i = 0; i < imax; i++)
     if (mParameters[i]->getUsage() == role)
       return mParameters[i]->getType() >= CFunctionParameter::VINT32;
   //this assumes that if a parameter is not a vector then there
   //will not be a vector parameter with the same role.
   return false;
 }
CFunctionParameters & CFunctionParameters::operator= (const CFunctionParameters & src)
Assignment operator. Performs deep copy.
Definition at line 48 of file CFunctionParameters.cpp.
References CCopasiVector< T >::deepCopy(), and mParameters.
 {
   mParameters.deepCopy(src.mParameters);
   return *this;
 }
bool CFunctionParameters::operator== (const CFunctionParameters & rhs) const
Definition at line 170 of file CFunctionParameters.cpp.
References CCopasiObject::getObjectName(), mParameters, CFunctionParameter::PARAMETER, size(), and CFunctionParameter::VARIABLE.
 {
   if (size() != rhs.size()) return false;
   CFunctionParameter::Role lhsRole, rhsRole;
   size_t i, imax = size();
   for (i = 0; i < imax; ++i)
     {
       if (mParameters[i]->getObjectName() != rhs.mParameters[i]->getObjectName()) return false;
       if (mParameters[i]->getType() != rhs.mParameters[i]->getType()) return false;
       lhsRole = mParameters[i]->getUsage();
       rhsRole = rhs.mParameters[i]->getUsage();
       // We do not destinguish between PARAMETER and VARIABLE
       if ((lhsRole == CFunctionParameter::PARAMETER || lhsRole == CFunctionParameter::VARIABLE) &&
           (rhsRole == CFunctionParameter::PARAMETER || rhsRole == CFunctionParameter::VARIABLE))
         continue;
       if (lhsRole != rhsRole) return false;
     }
   return true;
 }
CFunctionParameter * CFunctionParameters::operator[] (size_t index)
Definition at line 88 of file CFunctionParameters.cpp.
References mParameters.
 {return mParameters[index];}
const CFunctionParameter * CFunctionParameters::operator[] (size_t index) const
Definition at line 91 of file CFunctionParameters.cpp.
References mParameters.
 {return mParameters[index];}
CFunctionParameter * CFunctionParameters::operator[] (const std::string & name)
Definition at line 94 of file CFunctionParameters.cpp.
References mParameters.
 {return mParameters[name];}
const CFunctionParameter * CFunctionParameters::operator[] (const std::string & name) const
Definition at line 97 of file CFunctionParameters.cpp.
References mParameters.
 {return mParameters[name];}
void CFunctionParameters::remove (const std::string & name)
Remove a parameter from the parameter list
Parameters
const CFunctionParameter & parameter
Definition at line 83 of file CFunctionParameters.cpp.
References mParameters, and CCopasiVectorN< CType >::remove().
Referenced by FunctionWidget1::copyFunctionContentsToFunction(), CCopasiXMLParser::ListOfParameterDescriptionsElement::end(), and CFunction::initVariables().
 {
   mParameters.remove(name);
 }
size_t CFunctionParameters::size () const
number of parameters
Definition at line 100 of file CFunctionParameters.cpp.
References mParameters, and CCopasiVector< T >::size().
Referenced by CModelAdd::addReactions(), SBMLImporter::areEqualFunctions(), CFunctionParameterMap::CFunctionParameterMap(), CFunctionParameterMap::checkCallParameters(), CFunctionAnalyzer::checkKineticFunction(), CModelAnalyzer::checkReaction(), CFunctionParameterMap::clearCallParameters(), CReaction::compile(), CFunctionAnalyzer::constructCallParameters(), CFunctionAnalyzer::constructCallParametersActualValues(), CModel::convert2NonReversible(), FunctionWidget1::copyFunctionContentsToFunction(), CReactionInterface::copyMapping(), SBMLImporter::createCReactionFromReaction(), SBMLImporter::createExpressionFromFunction(), CSBMLExporter::createFunctionDefinition(), CSBMLExporter::createKineticExpression(), CSBMLExporter::createKineticLaw(), CFunction::createListOfParametersForMathML(), CMMLOutput::createParameterMapping(), SBMLImporter::doMapping(), CModelExpansion::duplicateReaction(), CCopasiXMLParser::ListOfParameterDescriptionsElement::end(), CFunctionAnalyzer::evaluateNode(), expand_function_call(), CODEExporterC::exportSingleFunction(), SBMLImporter::findCorrespondingFunction(), CFindDimensions::findDimensions(), CReactionInterface::getDeletedParameters(), CObjectLists::getListOfConstObjects(), CFunctionParameterMap::initCallParameters(), CReaction::initializeMetaboliteKeyMap(), CFunction::initVariables(), CODEExporterC::KineticFunction2ODEmember(), FunctionWidget1::loadParameterTable(), CModelMerging::mergeMetabolites(), operator==(), CModel::printParameterOverview(), CModelExpansion::replaceInReaction(), CCopasiXML::saveFunctionList(), CCopasiXML::saveModel(), CFindDimensions::setupDimensions(), CReactionInterface::size(), CFunction::splitFunction(), CCopasiXMLParser::ParameterDescriptionElement::start(), test_compare_utilities::test_copasi_function_expansion(), test000078::test_l2v4_import_unordered_functions(), CEvaluationNodeCall::verifyParameters(), and CFunction::writeMathML().
 {return mParameters.size();}
void CFunctionParameters::swap (const size_t & from, const size_t & to)
Swap parameters
Parameters
const size_t & from
const size_t & to
Definition at line 102 of file CFunctionParameters.cpp.
References mParameters, and CCopasiVector< T >::swap().
Referenced by CCopasiXMLParser::ParameterDescriptionElement::start().
 {mParameters.swap(from, to);}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const CFunctionParameters & d) friend
insert operator
Definition at line 198 of file CFunctionParameters.cpp.
 {
   //os << "++++CFunctionParameters: " << std::endl;
   //os << "    CFunctionParameters.mParameters " << std::endl << d.mParameters;
   //os << "----CFunctionParameters " << std::endl;
   size_t i, imax = d.mParameters.size();
   for (i = 0; i < imax; ++i)
     {
       if (0 == i)
         os << "  (";
       else
         os << "    ";
       os << *d.mParameters[i];
       if (imax - 1 == i)
         os << ")\n";
       else
         os << ",\n";
     }
   return os;
 }
Member Data Documentation
CCopasiVectorNS< CFunctionParameter > CFunctionParameters::mParameters private
A vector of parameters 0..* <{CFunctionParameter}>
Definition at line 40 of file CFunctionParameters.h.
Referenced by add(), cleanup(), findParameterByName(), getNumberOfParametersByUsage(), getParameterByUsage(), isVector(), operator<<(), operator=(), operator==(), operator[](), remove(), size(), and swap().
The documentation for this class was generated from the following files:
CFunctionParameters.h
CFunctionParameters.cpp