COPASI API: CCopasiXMLParser::PlotSpecificationElement Class Reference
CCopasiXMLParser::PlotSpecificationElement Class Reference
Public Member Functions
virtual void end (const XML_Char *pszName)
PlotSpecificationElement (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void start (const XML_Char *pszName, const XML_Char **papszAttrs)
virtual ~PlotSpecificationElement ()
Public Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
CXMLElementHandler (CCopasiXMLParser &parser, SCopasiXMLParserCommon &common)
virtual void end (const XML_Char *C_UNUSED(pszName))
virtual void reset ()
virtual void start (const XML_Char *C_UNUSED(pszName), const XML_Char **C_UNUSED(papszAttrs))
virtual ~CXMLElementHandler ()
Private Types
enum Element {
PlotSpecification = 0, Parameter, ParameterGroup, ListOfChannels,
ListOfPlotItems
}
Private Attributes
size_t mLineNumber
Additional Inherited Members
Protected Member Functions inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
void addFix (const std::string &key, CCopasiObject *pObject)
void deleteCurrentHandler ()
Protected Attributes inherited from CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >
SCopasiXMLParserCommon & mCommon
C_INT32 mCurrentElement
C_INT32 mLastKnownElement
CCopasiXMLParser & mParser
CXMLElementHandler * mpCurrentHandler
Detailed Description
Definition at line 2044 of file CCopasiXMLParser.h.
Member Enumeration Documentation
enum CCopasiXMLParser::PlotSpecificationElement::Element private
Enumerator
PlotSpecification
Parameter
ParameterGroup
ListOfChannels
ListOfPlotItems
Definition at line 2051 of file CCopasiXMLParser.h.
     {
       PlotSpecification = 0,
       Parameter,
       ParameterGroup,
       ListOfChannels,
       ListOfPlotItems
     };
Constructor & Destructor Documentation
CCopasiXMLParser::PlotSpecificationElement::PlotSpecificationElement (CCopasiXMLParser & parser, SCopasiXMLParserCommon & common)
Constructor
Definition at line 6011 of file CCopasiXMLParser.cpp.
                                                                                                                            :
   CXMLElementHandler< CCopasiXMLParser, SCopasiXMLParserCommon >(parser, common),
   mLineNumber(0)
 {}
CCopasiXMLParser::PlotSpecificationElement::~PlotSpecificationElement () virtual
Destructor
Definition at line 6016 of file CCopasiXMLParser.cpp.
 {}
Member Function Documentation
void CCopasiXMLParser::PlotSpecificationElement::end (const XML_Char * pszName) virtual
End element handler
Parameters
const XML_Char *pszName
Definition at line 6117 of file CCopasiXMLParser.cpp.
References CCopasiParameter::BOOL, CCopasiParameter::CN, CCopasiParameter::DOUBLE, CCopasiMessage::EXCEPTION, CCopasiParameter::EXPRESSION, fatalError, CCopasiParameter::FILE, CKeyFactory::get(), CCopasiParameter::getKey(), CCopasiObject::getKey(), CCopasiObject::getObjectName(), CCopasiParameterGroup::getParameter(), CCopasiParameter::getType(), CCopasiParameter::getValue(), CCopasiParameter::GROUP, CCopasiParameter::INT, CCopasiParameter::INVALID, CCopasiParameter::KEY, SCopasiXMLParserCommon::KeyMap, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, CCopasiParameter::Value::pBOOL, CCopasiParameter::Value::pCN, SCopasiXMLParserCommon::pCurrentParameter, SCopasiXMLParserCommon::pCurrentPlot, pdelete, CCopasiParameter::Value::pDOUBLE, CCopasiParameter::Value::pFILE, CCopasiParameter::Value::pINT, CCopasiParameter::Value::pKEY, CCopasiParameter::Value::pSTRING, CCopasiParameter::Value::pUDOUBLE, CCopasiParameter::Value::pUINT, CCopasiMessage::RAW, CCopasiParameter::setValue(), START_ELEMENT, CCopasiParameter::STRING, CCopasiParameter::UDOUBLE, CCopasiParameter::UINT, UNKNOWN_ELEMENT, and SCopasiXMLParserCommon::UnmappedKeyParameters.
 {
   CCopasiParameter* p;
   switch (mCurrentElement)
     {
       case PlotSpecification:
         if (!strcmp(pszName, "PlotSpecification"))
           {
             mParser.popElementHandler();
             mCurrentElement = START_ELEMENT;
             mParser.onEndElement(pszName);
           }
         break;
       case Parameter:
         if (!strcmp(pszName, "Parameter"))
           {
             p = mCommon.pCurrentPlot->getParameter(mCommon.pCurrentParameter->getObjectName());
             if (p)
               {
                 switch (p->getType())
                   {
                     case CCopasiParameter::INT:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pINT);
                       break;
                     case CCopasiParameter::UINT:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pUINT);
                       break;
                     case CCopasiParameter::DOUBLE:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pDOUBLE);
                       break;
                     case CCopasiParameter::UDOUBLE:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pUDOUBLE);
                       break;
                     case CCopasiParameter::BOOL:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pBOOL);
                       break;
                     case CCopasiParameter::STRING:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pSTRING);
                       break;
                     case CCopasiParameter::KEY:
                     {
                       CCopasiObject * pObject =
                         mCommon.KeyMap.get(* mCommon.pCurrentParameter->getValue().pKEY);
                       if (pObject)
                         p->setValue(pObject->getKey());
                       else
{
                           p->setValue(*mCommon.pCurrentParameter->getValue().pKEY);
                           mCommon.UnmappedKeyParameters.push_back(p->getKey());
                         }
                     }
                     break;
                     case CCopasiParameter::FILE:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pFILE);
                       break;
                     case CCopasiParameter::CN:
                       p->setValue(* mCommon.pCurrentParameter->getValue().pCN);
                       break;
                     case CCopasiParameter::EXPRESSION:
                     case CCopasiParameter::GROUP:
                     case CCopasiParameter::INVALID:
                       break;
                     default:
                       fatalError();
                       break;
                   }
               }
             else
               {
                 CCopasiMessage(CCopasiMessage::RAW, MCXML + 4,
                                mCommon.pCurrentParameter->getObjectName().c_str(),
                                mLineNumber);
               }
             pdelete(mCommon.pCurrentParameter);
             mCurrentElement = PlotSpecification;
           }
         break;
       case ParameterGroup:
         if (strcmp(pszName, "ParameterGroup"))
           {
             p = mCommon.pCurrentPlot->getParameter(mCommon.pCurrentParameter->getObjectName());
             if (p)
               {
                 switch (p->getType())
                   {
                     case CCopasiParameter::GROUP:
                       *(CCopasiParameterGroup *) p =
                         * (CCopasiParameterGroup *) mCommon.pCurrentParameter;
                       break;
                     case CCopasiParameter::INT:
                     case CCopasiParameter::UINT:
                     case CCopasiParameter::DOUBLE:
                     case CCopasiParameter::UDOUBLE:
                     case CCopasiParameter::BOOL:
                     case CCopasiParameter::STRING:
                     case CCopasiParameter::CN:
                     case CCopasiParameter::KEY:
                     case CCopasiParameter::FILE:
                     case CCopasiParameter::EXPRESSION:
                     case CCopasiParameter::INVALID:
                       break;
                     default:
                       fatalError();
                       break;
                   }
               }
             else
               {
                 CCopasiMessage(CCopasiMessage::RAW, MCXML + 4,
                                mCommon.pCurrentParameter->getObjectName().c_str(),
                                mLineNumber);
               }
             pdelete(mCommon.pCurrentParameter);
             mCurrentElement = PlotSpecification;
           }
         break;
       case ListOfChannels:
         if (!strcmp(pszName, "ListOfChannels"))
           {
             mCurrentElement = PlotSpecification;
           }
         break;
       case ListOfPlotItems:
         if (!strcmp(pszName, "ListOfPlotItems"))
           {
             mCurrentElement = PlotSpecification;
           }
         break;
       case UNKNOWN_ELEMENT:
         mCurrentElement = mLastKnownElement;
         break;
       default:
         CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 11,
                        pszName, "???", mParser.getCurrentLineNumber());
         break;
     }
   deleteCurrentHandler();
   return;
 }
void CCopasiXMLParser::PlotSpecificationElement::start (const XML_Char * pszName, const XML_Char ** papszAttrs) virtual
Start element handler
Parameters
const XML_Char *pszName
const XML_Char **papszAttrs
Definition at line 6019 of file CCopasiXMLParser.cpp.
References CPlotItem::curve2d, CCopasiMessage::EXCEPTION, CCopasiXMLParser::mCommon, MCXML, CExpatTemplate< CExpat >::mParser, SCopasiXMLParserCommon::pCurrentPlot, SCopasiXMLParserCommon::pCurrentPlotItem, CPlotSpecification::setActive(), CCopasiObject::setObjectName(), CPlotItem::setType(), toEnum(), UNKNOWN_ELEMENT, and CPlotItem::XMLType.
 {
   mCurrentElement++; /* We should always be on hte next element */
   mpCurrentHandler = NULL;
   mLineNumber = (size_t) - 1;
   const char * name;
   const char * sType;
   const char * active;
   switch (mCurrentElement)
     {
       case PlotSpecification:
         if (strcmp(pszName, "PlotSpecification"))
           CCopasiMessage(CCopasiMessage::EXCEPTION, MCXML + 10,
                          pszName, "PlotSpecification", mParser.getCurrentLineNumber());
         // create a new CPlotSpecification element depending on the type
         mCommon.pCurrentPlot = new CPlotSpecification();
         mCommon.pCurrentPlotItem = mCommon.pCurrentPlot;
         name = mParser.getAttributeValue("name", papszAttrs);
         mCommon.pCurrentPlot->setObjectName(name);
         sType = mParser.getAttributeValue("type", papszAttrs);
         mCommon.pCurrentPlot->setType(toEnum(sType, CPlotItem::XMLType, CPlotItem::curve2d));
         active = mParser.getAttributeValue("active", papszAttrs, "true");
         mCommon.pCurrentPlot->setActive(mParser.toBool(active));
         return;
         break;
       case Parameter:
         if (!strcmp(pszName, "Parameter"))
           {
             mLineNumber = mParser.getCurrentLineNumber();
             if (!mpCurrentHandler)
               {
                 mpCurrentHandler = new ParameterElement(mParser, mCommon);
               }
           }
         break;
       case ParameterGroup:
         if (!strcmp(pszName, "ParameterGroup"))
           {
             mLineNumber = mParser.getCurrentLineNumber();
             if (!mpCurrentHandler)
               {
                 mpCurrentHandler = new ParameterGroupElement(mParser, mCommon);
               }
           }
         break;
       case ListOfChannels:
         if (!strcmp(pszName, "ListOfChannels"))
           {
             if (!mpCurrentHandler)
               {
                 mpCurrentHandler = new ListOfChannelsElement(mParser, mCommon);
               }
           }
         break;
       case ListOfPlotItems:
         if (!strcmp(pszName, "ListOfPlotItems"))
           {
             if (!mpCurrentHandler)
               {
                 mpCurrentHandler = new ListOfPlotItemsElement(mParser, mCommon);
               }
           }
         break;
       default:
         mLastKnownElement = mCurrentElement - 1;
         mCurrentElement = UNKNOWN_ELEMENT;
         mpCurrentHandler = &mParser.mUnknownElement;
         break;
     }
   if (mpCurrentHandler)
     mParser.pushElementHandler(mpCurrentHandler);
   mParser.onStartElement(pszName, papszAttrs);
   return;
 }
Member Data Documentation
size_t CCopasiXMLParser::PlotSpecificationElement::mLineNumber private
The line number the unknown parameter was encountered.
Definition at line 2063 of file CCopasiXMLParser.h.
The documentation for this class was generated from the following files:
CCopasiXMLParser.h
CCopasiXMLParser.cpp