COPASI API: CSlider Class Reference
CSlider Class Reference
#include <CSlider.h>
Public Types
enum Scale { linear = 0, logarithmic, undefinedScale }
enum Type {
Float = 0, UnsignedFloat, Integer, UnsignedInteger,
Undefined
}
Public Types inherited from CCopasiContainer
typedef std::multimap
< std::string, CCopasiObject * > objectMap
Public Types inherited from CCopasiObject
typedef std::set< const
CCopasiObject * > DataObjectSet
typedef std::vector< Refresh * > DataUpdateSequence
Public Types inherited from CObjectInterface
typedef std::set< const
CObjectInterface * > ObjectSet
typedef std::vector
< CObjectInterface * > UpdateSequence
Public Member Functions
bool compile (const std::vector< CCopasiContainer * > &listOfContainer=CCopasiContainer::EmptyList)
Scale convertScaleNameToScale (const char *scaleName)
const char * convertScaleToScaleName (Scale scale)
CSlider (const std::string &name="Slider", const CCopasiContainer *pParent=NULL)
CSlider (const CSlider &src, const CCopasiContainer *pParent=NULL)
const std::string & getAssociatedEntityKey () const
const std::string & getKey () const
const C_FLOAT64 & getMaxValue () const
const C_FLOAT64 & getMinValue () const
const C_FLOAT64 & getOriginalValue () const
Scale getScaling () const
CCopasiObject * getSliderObject ()
const std::string & getSliderObjectCN () const
CSlider::Type getSliderType () const
const C_FLOAT64 & getSliderValue () const
bool getSynced () const
unsigned C_INT32 getTickFactor () const
unsigned C_INT32 getTickNumber () const
bool isValid () const
void resetRange ()
void resetValue ()
bool setAssociatedEntityKey (const std::string &associatedEntityKey)
bool setMaxValue (const C_FLOAT64 maxValue)
bool setMinValue (const C_FLOAT64 minValue)
bool setOriginalValue (const C_FLOAT64 value)
bool setScaling (Scale scaling)
bool setSliderObject (CCopasiObject *pObject)
bool setSliderObject (const CCopasiObjectName &objectCN)
bool setSliderType (const CSlider::Type type)
bool setSliderValue (const C_FLOAT64 value, const bool &writeToObject=true)
void setSynced (bool synced)
bool setTickFactor (const unsigned C_INT32 tickFactor)
bool setTickNumber (const unsigned C_INT32 tickNumber)
void sync ()
void writeToObject ()
~CSlider ()
Public Member Functions inherited from CCopasiContainer
virtual bool add (CCopasiObject *pObject, const bool &adopt=true)
CCopasiContainer (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=CCopasiObject::Container)
CCopasiContainer (const CCopasiContainer &src, const CCopasiContainer *pParent=NULL)
virtual std::string getChildObjectUnits (const CCopasiObject *pObject) const
virtual const CObjectInterface * getObject (const CCopasiObjectName &cn) const
virtual const objectMap & getObjects () const
virtual std::string getUnits () const
virtual const CCopasiObject * getValueObject () const
virtual bool remove (CCopasiObject *pObject)
virtual ~CCopasiContainer ()
Public Member Functions inherited from CCopasiObject
void addDirectDependency (const CCopasiObject *pObject)
CCopasiObject (const CCopasiObject &src, const CCopasiContainer *pParent=NULL)
void clearDirectDependencies ()
void clearRefresh ()
bool dependsOn (DataObjectSet candidates, const DataObjectSet &context=DataObjectSet()) const
void getAllDependencies (DataObjectSet &dependencies, const DataObjectSet &context) const
virtual CCopasiObjectName getCN () const
virtual const DataObjectSet & getDirectDependencies (const DataObjectSet &context=DataObjectSet()) const
CCopasiContainer * getObjectAncestor (const std::string &type) const
CCopasiDataModel * getObjectDataModel ()
const CCopasiDataModel * getObjectDataModel () const
virtual std::string getObjectDisplayName (bool regular=true, bool richtext=false) const
const std::string & getObjectName () const
CCopasiContainer * getObjectParent () const
const std::string & getObjectType () const
virtual const
CObjectInterface::ObjectSet & getPrerequisites () const
virtual Refresh * getRefresh () const
UpdateMethod * getUpdateMethod () const
virtual void * getValuePointer () const
bool hasCircularDependencies (DataObjectSet &candidates, DataObjectSet &verified, const DataObjectSet &context) const
bool hasUpdateMethod () const
bool isArray () const
bool isContainer () const
bool isDataModel () const
bool isMatrix () const
bool isNameVector () const
bool isNonUniqueName () const
virtual bool isPrerequisiteForContext (const CObjectInterface *pObject, const CMath::SimulationContextFlag &context, const CObjectInterface::ObjectSet &changedObjects) const
bool isReference () const
bool isRoot () const
bool isSeparator () const
bool isStaticString () const
bool isValueBool () const
bool isValueDbl () const
bool isValueInt () const
bool isValueInt64 () const
bool isValueString () const
bool isVector () const
virtual bool mustBeDeleted (const DataObjectSet &deletedObjects) const
virtual void print (std::ostream *ostream) const
void removeDirectDependency (const CCopasiObject *pObject)
void setDirectDependencies (const DataObjectSet &directDependencies)
bool setObjectName (const std::string &name)
virtual bool setObjectParent (const CCopasiContainer *pParent)
void setObjectValue (const C_FLOAT64 &value)
void setObjectValue (const C_INT32 &value)
void setObjectValue (const bool &value)
template<class CType >
void setRefresh (CType *pType, void(CType::*method)(void))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_FLOAT64 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const C_INT32 &))
template<class CType >
void setUpdateMethod (CType *pType, void(CType::*method)(const bool &))
virtual ~CCopasiObject ()
Public Member Functions inherited from CObjectInterface
CObjectInterface ()
virtual ~CObjectInterface ()
Static Public Attributes
static const char * ScaleName []
static const char * TypeName []
Static Public Attributes inherited from CCopasiContainer
static const std::vector
< CCopasiContainer * > EmptyList
Private Attributes
std::string mAssociatedEntityKey
CRegisteredObjectName mCN
std::vector< Refresh * > mInitialRefreshes
std::string mKey
C_FLOAT64 mMaxValue
C_FLOAT64 mMinValue
C_FLOAT64 mOriginalValue
CCopasiObject * mpSliderObject
Scale mScaling
Type mSliderType
bool mSync
unsigned C_INT32 mTickFactor
unsigned C_INT32 mTickNumber
C_FLOAT64 mValue
Additional Inherited Members
Static Public Member Functions inherited from CCopasiObject
static std::vector< Refresh * > buildUpdateSequence (const DataObjectSet &objects, const DataObjectSet &uptoDateObjects, const DataObjectSet &context=DataObjectSet())
static void setRenameHandler (CRenameHandler *rh)
Protected Types inherited from CCopasiObject
enum Flag {
Container = 0x1, Vector = 0x2, Matrix = 0x4, NameVector = 0x8,
Reference = 0x10, ValueBool = 0x20, ValueInt = 0x40, ValueInt64 = 0x80,
ValueDbl = 0x100, NonUniqueName = 0x200, StaticString = 0x400, ValueString = 0x800,
Separator = 0x1000, ModelEntity = 0x2000, Array = 0x4000, DataModel = 0x8000,
Root = 0x10000, Gui = 0x20000
}
Protected Member Functions inherited from CCopasiContainer
template<class CType >
CCopasiObject * addMatrixReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addObjectReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
template<class CType >
CCopasiObject * addVectorReference (const std::string &name, CType &reference, const unsigned C_INT32 &flag=0)
void initObjects ()
Protected Member Functions inherited from CCopasiObject
CCopasiObject ()
CCopasiObject (const std::string &name, const CCopasiContainer *pParent=NULL, const std::string &type="CN", const unsigned C_INT32 &flag=0)
Protected Attributes inherited from CCopasiContainer
objectMap mObjects
Static Protected Attributes inherited from CCopasiObject
static CRenameHandler * smpRenameHandler = NULL
Detailed Description
Definition at line 29 of file CSlider.h.
Member Enumeration Documentation
enum CSlider::Scale
Enum of valid scales
Enumerator
linear
logarithmic
undefinedScale
Definition at line 40 of file CSlider.h.
 {linear = 0, logarithmic, undefinedScale};
enum CSlider::Type
Enum of valid quantitye units
Enumerator
Float
UnsignedFloat
Integer
UnsignedInteger
Undefined
Definition at line 35 of file CSlider.h.
 {Float = 0, UnsignedFloat, Integer, UnsignedInteger, Undefined};
Constructor & Destructor Documentation
CSlider::CSlider (const std::string & name = "Slider", const CCopasiContainer * pParent = NULL)
Default constructor
Parameters
const std::string & name (default: "NoName")
const CCopasiContainer * pParent (default: NULL)
Definition at line 30 of file CSlider.cpp.
                                                   :
   CCopasiContainer(name, pParent, "Slider"),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Slider", this)),
   mAssociatedEntityKey(),
   mpSliderObject(NULL),
   mSliderType(Float),
   mValue(0.0),
   mMinValue(0),
   mMaxValue(0),
   mTickNumber(1000),
   mTickFactor(100),
   mSync(true),
   mScaling(CSlider::linear),
   mCN(),
   mInitialRefreshes()
 {}
CSlider::CSlider (const CSlider & src, const CCopasiContainer * pParent = NULL)
Copy constructor
Parameters
const CSlider & src
const CCopasiContainer * pParent (default: NULL)
Definition at line 48 of file CSlider.cpp.
                                                   :
   CCopasiContainer(src, pParent),
   mKey(CCopasiRootContainer::getKeyFactory()->add("Slider", this)),
   mAssociatedEntityKey(src.mAssociatedEntityKey),
   mpSliderObject(src.mpSliderObject),
   mSliderType(src.mSliderType),
   mValue(src.mValue),
   mMinValue(src.mMinValue),
   mMaxValue(src.mMaxValue),
   mTickNumber(src.mTickNumber),
   mTickFactor(src.mTickFactor),
   mSync(src.mSync),
   mScaling(src.mScaling),
   mCN(src.mCN),
   mInitialRefreshes(src.mInitialRefreshes)
 {}
CSlider::~CSlider ()
Destructor.
Definition at line 66 of file CSlider.cpp.
References CCopasiRootContainer::getKeyFactory(), mKey, and CKeyFactory::remove().
 {CCopasiRootContainer::getKeyFactory()->remove(mKey);}
Member Function Documentation
bool CSlider::compile (const std::vector< CCopasiContainer * > & listOfContainer = CCopasiContainer::EmptyList)
Compile, i.e., find the objects pointed to by the CN.
Parameters
const std::vector< CCopasiContainer * > & listOfContainer (default: CCopasiContainer::EmptyList)
Returns
bool success
Definition at line 69 of file CSlider.cpp.
References CCopasiObject::getObjectDataModel(), mCN, mpSliderObject, mSync, setSliderObject(), and sync().
Referenced by SliderDialog::addSlider(), CopasiSlider::CopasiSlider(), SliderDialog::createNewSlider(), SliderDialog::getCSlidersForObject(), and SliderDialog::sliderObjectChanged().
 {
   if (getObjectDataModel() == NULL) return false;
   //setSliderObject(CCopasiContainer::ObjectFromName(listOfContainer, getObjectName()));
   setSliderObject(getObjectDataModel()->ObjectFromName(listOfContainer, mCN));
   if (this->mSync) this->sync();
   return (mpSliderObject != NULL);
 }
CSlider::Scale CSlider::convertScaleNameToScale (const char * scaleName)
Converts the scaling name to the corresponding enum.
Returns
CSlider::Scale
Definition at line 380 of file CSlider.cpp.
References linear, logarithmic, and undefinedScale.
Referenced by CCopasiXMLParser::SliderElement::start().
 {
   if (!strncmp("linear", scaleName, 7))
     {
       return CSlider::linear;
     }
   else if (!strncmp("logarithmic", scaleName, 12))
     {
       return CSlider::logarithmic;
     }
   else
     {
       return CSlider::undefinedScale;
     }
 }
const char * CSlider::convertScaleToScaleName (Scale scale)
Converts the scaling name to the corresponding enum.
Returns
const char* scaleName
Definition at line 396 of file CSlider.cpp.
References ScaleName, and undefinedScale.
Referenced by CCopasiXML::saveGUI().
 {
   if (scale < 0 || scale > CSlider::undefinedScale) return ScaleName[undefinedScale];
   return ScaleName[scale];
 }
const std::string & CSlider::getAssociatedEntityKey () const
Retrieve the key of the associated entity.
Returns
const std::string & associatedEntityKey
Definition at line 101 of file CSlider.cpp.
References mAssociatedEntityKey.
Referenced by SliderDialog::equivalentSliderExists(), SliderDialog::getCSlidersForObject(), and CCopasiXML::saveGUI().
 {return mAssociatedEntityKey;}
const std::string & CSlider::getKey () const virtual
Retrieve the key
Returns
const std::string & key
Reimplemented from CCopasiObject.
Definition at line 91 of file CSlider.cpp.
References mKey.
Referenced by CCopasiXML::saveGUI().
 {return mKey;}
const C_FLOAT64 & CSlider::getMaxValue () const
Retrieve the slider maximum value.
Returns
const C_FLOAT64 & maxValue
Definition at line 348 of file CSlider.cpp.
References mMaxValue.
Referenced by CopasiSlider::calculatePositionFromValue(), CopasiSlider::calculateValueFromPosition(), CopasiSlider::maxValue(), CopasiSlider::minorTickInterval(), CCopasiXML::saveGUI(), SliderSettingsDialog::updateInputFieldsValues(), CopasiSlider::updateLabel(), and CopasiSlider::updateValue().
 {return mMaxValue;}
const C_FLOAT64 & CSlider::getMinValue () const
Retrieve the slider minimum value.
Returns
const C_FLOAT64 minValue
Definition at line 320 of file CSlider.cpp.
References mMinValue.
Referenced by CopasiSlider::calculatePositionFromValue(), CopasiSlider::calculateValueFromPosition(), CopasiSlider::minorTickInterval(), CopasiSlider::minValue(), CCopasiXML::saveGUI(), SliderSettingsDialog::updateInputFieldsValues(), CopasiSlider::updateLabel(), and CopasiSlider::updateValue().
 {return mMinValue;}
const C_FLOAT64 & CSlider::getOriginalValue () const
Retrieve the original slider Value.
Returns
const C_FLOAT64 Value
Definition at line 285 of file CSlider.cpp.
References mOriginalValue.
Referenced by CopasiSlider::originalValue(), and SliderSettingsDialog::updateInputFieldsValues().
 {
   return this->mOriginalValue;
 }
CSlider::Scale CSlider::getScaling () const
Retrieve the scaling of the slider.
Returns
Scale scaling
Definition at line 369 of file CSlider.cpp.
References mScaling.
Referenced by CopasiSlider::calculatePositionFromValue(), CopasiSlider::calculateValueFromPosition(), CCopasiXML::saveGUI(), and SliderSettingsDialog::updateInputFieldsValues().
 {
   return this->mScaling;
 }
CCopasiObject * CSlider::getSliderObject ()
Retrieve the slider object.
Returns
CCopasiObject * pObject
Definition at line 176 of file CSlider.cpp.
References mpSliderObject.
Referenced by SliderSettingsDialog::browseButtonPressed(), SliderDialog::equivalentSliderExists(), CopasiSlider::object(), SliderSettingsDialog::setSlider(), CopasiSlider::updateLabel(), and CopasiSlider::updateSliderData().
 {return mpSliderObject;}
const std::string & CSlider::getSliderObjectCN () const
Retrieve the slider object CN.
Returns
const std::string & sliderObjectCN
Definition at line 179 of file CSlider.cpp.
References mCN.
Referenced by CCopasiXML::saveGUI().
 {return mCN; /*getObjectName();*/}
CSlider::Type CSlider::getSliderType () const
Retrieve the slider type.
Returns
const CSlider::Type type
Definition at line 188 of file CSlider.cpp.
References mSliderType.
Referenced by CCopasiXML::saveGUI(), and CopasiSlider::type().
 {return mSliderType;}
const C_FLOAT64 & CSlider::getSliderValue () const
Retrieve the slider Value.
Returns
const C_FLOAT64 Value
Definition at line 290 of file CSlider.cpp.
References mValue.
Referenced by resetRange(), CCopasiXML::saveGUI(), CopasiSlider::setMaxValue(), setMaxValue(), CopasiSlider::setMinValue(), setMinValue(), CopasiSlider::setNumMinorTicks(), setSliderObject(), CopasiSlider::setValue(), CopasiSlider::sliderValueChanged(), SliderSettingsDialog::updateInputFieldsValues(), CopasiSlider::updateLabel(), CopasiSlider::updateSliderData(), CopasiSlider::updateValue(), and CopasiSlider::value().
 {
   return this->mValue;
 }
bool CSlider::getSynced () const
Returns wether the value is to be kept in sync the the objects value.
Returns
bool isSynced.
Definition at line 86 of file CSlider.cpp.
References mSync.
 {
   return this->mSync;
 }
unsigned C_INT32 CSlider::getTickFactor () const
Retrieve the tick factor.
Returns
const unsigned C_INT32 & tickFactor
Definition at line 366 of file CSlider.cpp.
References mTickFactor.
Referenced by CopasiSlider::minorMajorFactor(), CCopasiXML::saveGUI(), SliderSettingsDialog::updateInputFieldsValues(), and CopasiSlider::updateSliderData().
 {return mTickFactor;}
unsigned C_INT32 CSlider::getTickNumber () const
Retrieve the tick number.
Returns
const unsigned C_INT32 & tickNumber
Definition at line 357 of file CSlider.cpp.
References mTickNumber.
Referenced by CopasiSlider::calculatePositionFromValue(), CopasiSlider::calculateValueFromPosition(), CopasiSlider::minorTickInterval(), CopasiSlider::numMinorTicks(), CCopasiXML::saveGUI(), SliderSettingsDialog::updateInputFieldsValues(), and CopasiSlider::updateSliderData().
 {return mTickNumber;}
bool CSlider::isValid () const
Checks whether the object the slider points to actually exists. Returns true if it does.
Definition at line 408 of file CSlider.cpp.
References CCopasiDataModel::getModel(), CCopasiObject::getObjectDataModel(), mCN, mpSliderObject, and CCopasiDataModel::ObjectFromName().
Referenced by CopasiSlider::isValid().
 {
   bool result = false;
   // check which object if any belongs to the CN and if it is the same as
   // the pointer currently stored in the slider
   assert(getObjectDataModel() != NULL);
   const CModel* pModel = getObjectDataModel()->getModel();
   assert(pModel != NULL);
   std::vector<CCopasiContainer*> listOfContainers;
   listOfContainers.push_back(const_cast<CModel*>(pModel));
   const CCopasiObject* pObject = getObjectDataModel()->ObjectFromName(listOfContainers, this->mCN);
   result = (pObject != NULL && pObject == this->mpSliderObject);
   return result;
 }
void CSlider::resetRange ()
Reset the minimum and maximum value to defaults. For the minimum this is half the current value. For the maximum this is twice the current value.
Definition at line 159 of file CSlider.cpp.
References C_FLOAT64, getSliderValue(), mMaxValue, mMinValue, mSliderType, and Undefined.
Referenced by SliderSettingsDialog::browseButtonPressed(), SliderDialog::createNewSlider(), and CopasiSlider::updateValue().
 {
   if (this->mSliderType != Undefined)
     {
       C_FLOAT64 value = this->getSliderValue();
       this->mMinValue = value / 2.0;
       this->mMaxValue = value == 0 ? 1.0 :  value * 2.0;
     }
 }
void CSlider::resetValue ()
Sets the value of the slider back to it's original value.
Definition at line 154 of file CSlider.cpp.
References mOriginalValue, and setSliderValue().
 {
   this->setSliderValue(this->mOriginalValue);
 }
bool CSlider::setAssociatedEntityKey (const std::string & associatedEntityKey)
Set the key of the associated entity
Parameters
const std::string & associatedEntityKey
Returns
bool succes
Definition at line 94 of file CSlider.cpp.
References CCopasiRootContainer::getKeyFactory(), and mAssociatedEntityKey.
Referenced by SliderSettingsDialog::browseButtonPressed(), SliderDialog::createNewSlider(), and CCopasiXMLParser::SliderElement::start().
 {
   mAssociatedEntityKey = associatedEntityKey;
   return (CCopasiRootContainer::getKeyFactory()->get(associatedEntityKey) != NULL);
 }
bool CSlider::setMaxValue (const C_FLOAT64 maxValue)
Set the slider maximum value.
Parameters
const C_FLOAT64 maxValue
Returns
bool succes
Definition at line 323 of file CSlider.cpp.
References getSliderValue(), mMaxValue, mMinValue, mpSliderObject, mSliderType, mValue, Undefined, and writeToObject().
Referenced by CopasiSlider::setMaxValue(), CCopasiXMLParser::SliderElement::start(), and SliderSettingsDialog::updateSlider().
 {
   if (mSliderType != Undefined)
     {
       mMaxValue = maxValue;
       if (mMaxValue < mMinValue)
         {
           mMinValue = mMaxValue;
         }
       if (mpSliderObject && getSliderValue() > mMaxValue)
         {
           this->mValue = this->mMaxValue;
           this->writeToObject();
         }
       return true;
     }
   else
     {
       return false;
     }
 }
bool CSlider::setMinValue (const C_FLOAT64 minValue)
Set the slider minimum value.
Parameters
const C_FLOAT64 minValue
Returns
bool succes
Definition at line 295 of file CSlider.cpp.
References getSliderValue(), mMaxValue, mMinValue, mpSliderObject, mSliderType, mValue, Undefined, and writeToObject().
Referenced by CopasiSlider::setMinValue(), CCopasiXMLParser::SliderElement::start(), and SliderSettingsDialog::updateSlider().
 {
   if (mSliderType != Undefined)
     {
       mMinValue = minValue;
       if (mMaxValue < mMinValue)
         {
           mMaxValue = mMinValue;
         }
       if (mpSliderObject && getSliderValue() < mMinValue)
         {
           this->mValue = this->mMinValue;
           this->writeToObject();
         }
       return true;
     }
   else
     {
       return false;
     }
 }
bool CSlider::setOriginalValue (const C_FLOAT64 value)
Set the sliders original value.
Parameters
const C_FLOAT64 Value
const bool & writeToObject (Default: true)
Returns
bool succes
Definition at line 191 of file CSlider.cpp.
References mMaxValue, mMinValue, mOriginalValue, mSliderType, and Undefined.
Referenced by CopasiSlider::setOriginalValue(), and SliderSettingsDialog::updateSlider().
 {
   if (mSliderType != Undefined)
     {
       mOriginalValue = value;
       if (mOriginalValue < this->mMinValue)
         {
           mOriginalValue = this->mMinValue;
         }
       if (mOriginalValue > this->mMaxValue)
         {
           mOriginalValue = this->mMaxValue;
         }
       return true;
     }
   else
     {
       return false;
     }
 }
bool CSlider::setScaling (CSlider::Scale scaling)
Set the scaling for the CSlider.
Definition at line 374 of file CSlider.cpp.
References mScaling.
Referenced by CCopasiXMLParser::SliderElement::start(), and SliderSettingsDialog::updateSlider().
 {
   this->mScaling = scaling;
   return true;
 }
bool CSlider::setSliderObject (CCopasiObject * pObject)
Set the slider object.
Parameters
CCopasiObject * pObject
Returns
bool succes
Definition at line 104 of file CSlider.cpp.
References CModel::buildInitialRefreshSequence(), C_FLOAT64, Float, CCopasiObject::getCN(), CCopasiDataModel::getModel(), CCopasiObject::getObjectDataModel(), getSliderValue(), Integer, CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), mCN, mInitialRefreshes, mMaxValue, mMinValue, mOriginalValue, mpSliderObject, mSync, setSliderType(), sync(), and Undefined.
Referenced by SliderSettingsDialog::browseButtonPressed(), compile(), SliderDialog::createNewSlider(), CopasiSlider::setObject(), and CCopasiXMLParser::SliderElement::start().
 {
   mpSliderObject = pObject;
   if (!pObject)
     {
       mInitialRefreshes.clear();
       return false;
     }
   mCN = pObject->getCN();
   std::set< const CCopasiObject * > ChangedObjects;
   ChangedObjects.insert(pObject);
   CCopasiDataModel* pDataModel = getObjectDataModel();
   assert(pDataModel != NULL);
   mInitialRefreshes = pDataModel->getModel()->buildInitialRefreshSequence(ChangedObjects);
   if (mpSliderObject->isValueInt())
     {
       this->setSliderType(Integer);
     }
   else if (mpSliderObject->isValueDbl())
     {
       this->setSliderType(Float);
     }
   else
     {
       this->setSliderType(Undefined);
     }
   if (this->mSync) this->sync();
   C_FLOAT64 value = this->getSliderValue();
   this->mOriginalValue = value;
   if (this->mMinValue > value)
     {
       this->mMinValue = value;
     }
   if (this->mMaxValue < value)
     {
       this->mMaxValue = value;
     }
   return true;
 }
bool CSlider::setSliderObject (const CCopasiObjectName & objectCN)
Set the slider object.
Parameters
const CCopasiObjectName & objectCN
Returns
bool succes
Definition at line 169 of file CSlider.cpp.
References mCN.
 {
   //return setObjectName(objectCN);
   mCN = objectCN;
   return true;
 }
bool CSlider::setSliderType (const CSlider::Type type)
Set the slider type.
Parameters
const CSlider::Type type
Returns
bool succes
Definition at line 182 of file CSlider.cpp.
References mSliderType.
Referenced by setSliderObject(), CopasiSlider::setType(), and CCopasiXMLParser::SliderElement::start().
 {
   mSliderType = type;
   return true;
 }
bool CSlider::setSliderValue (const C_FLOAT64 value, const bool & writeToObject = true)
Set the slider value.
Parameters
const C_FLOAT64 Value
const bool & writeToObject (Default: true)
Returns
bool succes
Definition at line 215 of file CSlider.cpp.
References mMaxValue, mMinValue, mSliderType, mSync, mValue, Undefined, and writeToObject().
Referenced by resetValue(), CopasiSlider::setValue(), CopasiSlider::sliderValueChanged(), CCopasiXMLParser::SliderElement::start(), and SliderSettingsDialog::updateSlider().
 {
   if (mSliderType != Undefined)
     {
       mValue = value;
       if (mValue < this->mMinValue)
         {
           mValue = this->mMinValue;
         }
       if (mValue > this->mMaxValue)
         {
           mValue = this->mMaxValue;
         }
       if (this->mSync && writeToObject)
         {
           this->writeToObject();
         }
       return true;
     }
   else
     {
       return false;
     }
 }
void CSlider::setSynced (bool synced)
Sets wether the value is to be kept in sync the the objects value.
Definition at line 81 of file CSlider.cpp.
References mSync.
 {
   this->mSync = synced;
 }
bool CSlider::setTickFactor (const unsigned C_INT32 tickFactor)
Set the tick factor.
Parameters
const unsigned C_INT32 & tickFactor
Returns
bool succes
Definition at line 360 of file CSlider.cpp.
References mTickFactor.
Referenced by CopasiSlider::setMinorMajorFactor(), CCopasiXMLParser::SliderElement::start(), and SliderSettingsDialog::updateSlider().
 {
   mTickFactor = tickFactor;
   return true;
 }
bool CSlider::setTickNumber (const unsigned C_INT32 tickNumber)
Set the tick number.
Parameters
const unsigned C_INT32 & tickNumber
Returns
bool succes
Definition at line 351 of file CSlider.cpp.
References mTickNumber.
Referenced by CopasiSlider::setNumMinorTicks(), CCopasiXMLParser::SliderElement::start(), and SliderSettingsDialog::updateSlider().
 {
   mTickNumber = tickNumber;
   return true;
 }
void CSlider::sync ()
Set the CSliders value to the value of the underlying object.
Definition at line 245 of file CSlider.cpp.
References C_FLOAT64, C_INT32, Float, CCopasiObject::getValuePointer(), Integer, mpSliderObject, mSliderType, mValue, UnsignedFloat, and UnsignedInteger.
Referenced by compile(), and setSliderObject().
 {
   if (!this->mpSliderObject) return;
   if (mSliderType == CSlider::Integer || mSliderType == CSlider::UnsignedInteger)
     {
       C_INT32* reference =
         (C_INT32*)(((CCopasiObjectReference<C_INT32>*)mpSliderObject)->getValuePointer());
       mValue = *reference;
     }
   else if (mSliderType == CSlider::Float || mSliderType == CSlider::UnsignedFloat)
     {
       C_FLOAT64* reference =
         (C_FLOAT64*)(((CCopasiObjectReference<C_FLOAT64>*)mpSliderObject)->getValuePointer());
       mValue = *reference;
     }
 }
void CSlider::writeToObject ()
Set the objects value to the value stored in CSlider.
Definition at line 265 of file CSlider.cpp.
References C_INT32, CCopasiObject::isValueBool(), CCopasiObject::isValueDbl(), CCopasiObject::isValueInt(), mInitialRefreshes, mpSliderObject, mValue, and CCopasiObject::setObjectValue().
Referenced by setMaxValue(), setMinValue(), and setSliderValue().
 {
   if (!mpSliderObject) return;
   if (mpSliderObject->isValueDbl())
     mpSliderObject->setObjectValue(mValue);
   else if (mpSliderObject->isValueInt())
     mpSliderObject->setObjectValue((C_INT32) floor(mValue + 0.5));
   else if (mpSliderObject->isValueBool())
     mpSliderObject->setObjectValue(mValue != 0.0);
   std::vector< Refresh * >::iterator it = mInitialRefreshes.begin();
   std::vector< Refresh * >::iterator end = mInitialRefreshes.end();
   for (; it != end; ++it)
     (**it)();
   return;
 }
Member Data Documentation
std::string CSlider::mAssociatedEntityKey private
The key of the associated entity of the slider's object.
Definition at line 296 of file CSlider.h.
Referenced by getAssociatedEntityKey(), and setAssociatedEntityKey().
CRegisteredObjectName CSlider::mCN private
The CN of the object that the slider modifies.
Definition at line 351 of file CSlider.h.
Referenced by compile(), getSliderObjectCN(), isValid(), and setSliderObject().
std::vector< Refresh * > CSlider::mInitialRefreshes private
The sequnece of methods to update initial values depending on this sliders object.
Definition at line 357 of file CSlider.h.
Referenced by setSliderObject(), and writeToObject().
std::string CSlider::mKey private
The key of the slider.
Definition at line 291 of file CSlider.h.
Referenced by getKey(), and ~CSlider().
C_FLOAT64 CSlider::mMaxValue private
The maximum value of the slider
Definition at line 326 of file CSlider.h.
Referenced by getMaxValue(), resetRange(), setMaxValue(), setMinValue(), setOriginalValue(), setSliderObject(), and setSliderValue().
C_FLOAT64 CSlider::mMinValue private
The minimun value of the slider
Definition at line 321 of file CSlider.h.
Referenced by getMinValue(), resetRange(), setMaxValue(), setMinValue(), setOriginalValue(), setSliderObject(), and setSliderValue().
C_FLOAT64 CSlider::mOriginalValue private
The original value of the slider-
Definition at line 316 of file CSlider.h.
Referenced by getOriginalValue(), resetValue(), setOriginalValue(), and setSliderObject().
CCopasiObject* CSlider::mpSliderObject private
The slider object pointing to the slider's object afteer compile.
Definition at line 301 of file CSlider.h.
Referenced by compile(), getSliderObject(), isValid(), setMaxValue(), setMinValue(), setSliderObject(), sync(), and writeToObject().
Scale CSlider::mScaling private
The scaling of the slider.
Definition at line 346 of file CSlider.h.
Referenced by getScaling(), and setScaling().
Type CSlider::mSliderType private
The value type of the slider's object.
Definition at line 306 of file CSlider.h.
Referenced by getSliderType(), resetRange(), setMaxValue(), setMinValue(), setOriginalValue(), setSliderType(), setSliderValue(), and sync().
bool CSlider::mSync private
Wether the CSlider's value is always in sync with its object's value.
Definition at line 341 of file CSlider.h.
Referenced by compile(), getSynced(), setSliderObject(), setSliderValue(), and setSynced().
unsigned C_INT32 CSlider::mTickFactor private
The factor between minor and major ticks.
Definition at line 336 of file CSlider.h.
Referenced by getTickFactor(), and setTickFactor().
unsigned C_INT32 CSlider::mTickNumber private
The number of ticks the slider is divided into.
Definition at line 331 of file CSlider.h.
Referenced by getTickNumber(), and setTickNumber().
C_FLOAT64 CSlider::mValue private
The value of the slider-
Definition at line 311 of file CSlider.h.
Referenced by getSliderValue(), setMaxValue(), setMinValue(), setSliderValue(), sync(), and writeToObject().
const char * CSlider::ScaleName static
Initial value:
=
{"linear", "logarithmic", "undefined", NULL}
String representation of valid scalings
Definition at line 50 of file CSlider.h.
Referenced by convertScaleToScaleName().
const char * CSlider::TypeName static
Initial value:
=
{"float", "unsignedFloat", "integer", "unsignedInteger", "Undefined", NULL}
String representation of valid quantity units
Definition at line 45 of file CSlider.h.
Referenced by CCopasiXML::saveGUI(), and CCopasiXMLParser::SliderElement::start().
The documentation for this class was generated from the following files:
CSlider.h
CSlider.cpp