COPASI API: FontChooser Class Reference
FontChooser Class Reference
#include <FontChooser.h>
Public Member Functions
FontChooser (QWidget *parent=0, bool modal=false, Qt::WindowFlags fl=0)
Private Slots
void cancel ()
void changeFontSize ()
Detailed Description
Definition at line 15 of file FontChooser.h.
Constructor & Destructor Documentation
FontChooser::FontChooser (QWidget * parent = 0, bool modal = false, Qt::WindowFlags fl = 0)
Definition at line 20 of file FontChooser.cpp.
References C_INT32, CQLayoutMainWindow::getFontSize(), and CQGLNetworkPainter::getFontSize().
   : QDialog(parent, fl)
 {
   setupUi(this);
   this->setModal(modal);
   QString className = QString(parentWidget()->metaObject()->className());
   if (className == "CQLayoutMainWindow")
     {
       CQLayoutMainWindow * tmp = dynamic_cast<CQLayoutMainWindow *>(parentWidget());
       assert(tmp);
       if (tmp)
         {
           C_INT32 currentFontSize = (C_INT32)(tmp->getFontSize());
           spinBox1->setValue(currentFontSize);
         }
     }
   else if (className == "CQGLNetworkPainter")
     {
       CQGLNetworkPainter * tmp = dynamic_cast<CQGLNetworkPainter *>(parentWidget());
       assert(tmp);
       if (tmp)
         {
           C_INT32 currentFontSize = (C_INT32)(tmp->getFontSize());
           spinBox1->setValue(currentFontSize);
         }
     }
 }
Member Function Documentation
void FontChooser::cancel () private slot
Definition at line 74 of file FontChooser.cpp.
 {
   close();
 }
void FontChooser::changeFontSize () private slot
Definition at line 51 of file FontChooser.cpp.
References C_INT32, CQLayoutMainWindow::setFontSizeForLabels(), and CQGLNetworkPainter::setFontSizeForLabels().
 {
   QString className = QString(parentWidget()->metaObject()->className());
   C_INT32 val = spinBox1->value();
   if (className == "CQLayoutMainWindow")
     {
       CQLayoutMainWindow * tmp = dynamic_cast<CQLayoutMainWindow *>(parentWidget());
       assert(tmp);
       if (tmp)
         tmp->setFontSizeForLabels(val);
     }
   else if (className == "CQGLNetworkPainter") // check for another possible parent window
     {
       CQGLNetworkPainter * tmp = dynamic_cast<CQGLNetworkPainter *>(parentWidget());
       assert(tmp);
       if (tmp)
         tmp->setFontSizeForLabels((unsigned int) val);
     }
 }
The documentation for this class was generated from the following files:
FontChooser.h
FontChooser.cpp