COPASI API: CODEExporterXPPAUT Class Reference
CODEExporterXPPAUT Class Reference
#include <CODEExporterXPPAUT.h>
Public Member Functions
CODEExporterXPPAUT ()
bool exportClosingData (const CModel *copasiModel, std::ostream &os)
virtual bool exportSingleCompartment (const CCompartment *comp, std::string &expression, std::string &comments)
void exportSingleLine (const std::string &line, std::ostringstream &which)
virtual bool exportSingleMetabolite (const CMetab *metab, std::string &expression, std::string &comments)
virtual bool exportSingleModelEntity (const CModelEntity *tmp, std::string &expression, std::string &comments)
virtual bool exportSingleModVal (const CModelValue *modval, std::string &expression, std::string &comments)
virtual bool exportSingleObject (std::ostringstream &which, const std::string &name, const std::string &expression, const std::string &comments)
virtual bool exportSingleODE (const CModelEntity *mentity, std::string &equation, std::string &comments)
virtual bool exportSingleParameter (const CCopasiParameter *param, std::string &expression, std::string &comments)
virtual bool exportTitleData (const CCopasiDataModel *pDataModel, std::ostream &os)
virtual std::string exportTitleString (const size_t tmp)
virtual std::string getDisplayExpressionString (CExpression *tmp)
virtual std::string getDisplayFunctionString (CFunction *func)
virtual std::string KineticFunction2ODEmember (const CReaction *reac)
std::string setConcentrationName (const std::string &objName)
std::string setODEName (const std::string &objName)
virtual void setReservedNames ()
std::string testName (const std::string &name)
virtual std::string translateObjectName (const std::string &realName)
virtual std::string translateTimeVariableName ()
Public Member Functions inherited from CODEExporter
void assembleSubTreeForMassAction (CEvaluationNode *newNode, CEvaluationNode *child1, CEvaluationNode *child2)
CODEExporter ()
virtual std::string exportClosingString (const size_t tmp)
bool exportCompartments (const CModel *copasiModel)
std::string exportExpression (const CExpression *pExpression, const CCopasiDataModel *pDataModel)
virtual bool exportKineticFunction (CReaction *reac)
virtual bool exportKineticFunctionGroup (const CModel *copasiModel)
virtual bool exportMetabolites (const CModel *copasiModel)
virtual bool exportMetabolitesConcentrations (const CModel *copasiModel)
bool exportModelEntityExpression (CCopasiObject *obj, const CCopasiDataModel *pDataModel)
bool exportModelValues (const CModel *copasiModel)
bool exportModelValuesExpressions (const CModel *copasiModel)
virtual std::string exportNumber (double number)
void exportObjectNodesFromModel (const CCopasiDataModel *pDataModel)
bool exportODEs (const CModel *copasiModel)
bool exportReacParamsAndFuncs (const CModel *copasiModel)
void exportSimulatedObject (CCopasiObject *obj, const CCopasiDataModel *pDataModel)
bool exportSingleFunction (const CFunction *func)
virtual bool exportSingleFunction (const CFunction *func, std::set< std::string > &isExported)
bool exportSingleFunction (CEvaluationNode *pNode, const CReaction *reac, size_t &index)
bool exportSingleFunction (CEvaluationNode *pNode, const std::string &key, size_t &index)
virtual bool exportTitleData (const CModel *copasiModel, std::ostream &os)
bool exportToStream (const CCopasiDataModel *pDataModel, std::ostream &os)
void findFunctionsCalls (const CEvaluationNode *pNode)
CCopasiObject * findObjectFromRefresh (const CCopasiObject *tmp, const Refresh *ref)
virtual std::string getSingleLineComment ()
virtual bool isEmptyString (std::string &str)
std::string isModelEntityExpressionODEExporterCompatible (CModelEntity *tmp, const CExpression *pExpression, const CCopasiDataModel *pDataModel)
void modifyTreeForMassAction (CFunction *tmpfunc)
virtual bool preprocess (const CModel *copasiModel)
virtual ~CODEExporter ()
Public Attributes
std::map< std::string,
unsigned C_INT32 > Frequancy
std::set< std::string > NameSet
Public Attributes inherited from CODEExporter
std::ostringstream assignment
std::map< std::string,
std::string > equations
std::ostringstream fixed
std::ostringstream functions
std::ostringstream headers
std::ostringstream initial
std::map< std::string,
std::string > NameMap
std::ostringstream ode
std::string timeKey
Additional Inherited Members
Public Types inherited from CODEExporter
enum Object {
INITIAL = 0, FIXED, ASSIGNMENT, HEADERS,
FUNCTIONS, ODEs
}
Protected Attributes inherited from CODEExporter
std::set< std::string > mExportedFunctions
Detailed Description
Definition at line 22 of file CODEExporterXPPAUT.h.
Constructor & Destructor Documentation
CODEExporterXPPAUT::CODEExporterXPPAUT ()
Constructor for the exporter.
Definition at line 54 of file CODEExporterXPPAUT.cpp.
 {}
Member Function Documentation
bool CODEExporterXPPAUT::exportClosingData (const CModel * copasiModel, std::ostream & os) virtual
Reimplemented from CODEExporter.
Definition at line 624 of file CODEExporterXPPAUT.cpp.
 {
   os << "done" << std::endl;
   return true;
 }
bool CODEExporterXPPAUT::exportSingleCompartment (const CCompartment * comp, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 398 of file CODEExporterXPPAUT.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CODEExporter::NameMap, and CModelEntity::ODE.
 {
   switch (comp->getStatus())
     {
       case CModelEntity::FIXED:
       {
         fixed << "#" << comments << std::endl;
         fixed << "param ";
         if (!exportSingleObject(fixed, NameMap[comp->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       {
         initial << "#" << comments << std::endl;
         initial << "init ";
         if (!exportSingleObject(initial, NameMap[comp->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
 #if 0
         assignment << "#" << comments << std::endl;
         if (!exportSingleObject(assignment, NameMap[comp->getKey()], expression, comments))
           return false;
 #endif
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
void CODEExporterXPPAUT::exportSingleLine (const std::string & line, std::ostringstream & which)
Definition at line 261 of file CODEExporterXPPAUT.cpp.
References MCODEExporter, CCopasiMessage::size(), and CCopasiMessage::WARNING.
Referenced by exportSingleObject().
 {
   std::locale C("C");
   size_t limit = 256, total = 1000;
   //size_t limit = 10, total = 15;
   if (line.size() > total)
     CCopasiMessage(CCopasiMessage::WARNING, MCODEExporter + 1);
   if (line.size() > limit)
     {
       size_t i, pos0, pos, end = line.size();
       pos0 = 0;
       pos = limit - 1;
       while (pos < end)
         {
           std::string part;
           char ch;
           ch = line[pos];
           while (std::isalnum(ch, C) || ch == '_' || ch == ')')
             {
               pos--;
               ch = line[pos];
             }
           for (i = pos0; i < pos; i++)
             {
               part += line[i];
             }
           part += " \\";
           which << part.c_str() << std::endl;
           pos0 = pos;
           pos += limit;
         }
       if (pos > end)
         {
           std::string part;
           for (i = pos0; i < end; i++)
             {
               part += line[i];
             }
           which << part.c_str() << std::endl;
         }
     }
   else
     which << line << std::endl;
   return;
 }
bool CODEExporterXPPAUT::exportSingleMetabolite (const CMetab * metab, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 337 of file CODEExporterXPPAUT.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CMetab::isDependent(), CODEExporter::NameMap, CModelEntity::ODE, and CModelEntity::REACTIONS.
 {
   std::string name;
   std::ostringstream smKey;
   smKey << "sm_" << metab->getKey();
   name = NameMap[smKey.str()];
   switch (metab->getStatus())
     {
       case CModelEntity::FIXED:
       {
         fixed << "#" << comments << std::endl;
         fixed << "param ";
         if (!exportSingleObject(fixed, name, expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       case CModelEntity::REACTIONS:
       {
         if (!metab->isDependent())
           {
             initial << "#" << comments << std::endl;
             initial << "init ";
             if (!exportSingleObject(initial, name, expression, comments))
               return false;
           }
         else
           {
             assignment << "#" << comments << std::endl;
             if (!exportSingleObject(assignment, name, expression, comments))
               return false;
           }
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
         assignment << "#" << comments << std::endl;
         if (!exportSingleObject(assignment, name, expression, comments))
           return false;
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterXPPAUT::exportSingleModelEntity (const CModelEntity * tmp, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 492 of file CODEExporterXPPAUT.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CODEExporter::NameMap, and CModelEntity::ODE.
 {
   std::string name;
   const CMetab* metab;
   metab = dynamic_cast< const CMetab * >(tmp);
   if (metab)
     {
       std::ostringstream smKey;
       smKey << "sm_" << metab->getKey();
       name = NameMap[smKey.str()];
     }
   else
     name = NameMap[tmp->getKey()];
   switch (tmp->getStatus())
     {
       case CModelEntity::FIXED:
       {
         fixed << "#" << comments << std::endl;
         fixed << "param ";
         if (!exportSingleObject(fixed, name, expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       {
         initial << "#" << comments << std::endl;
         initial << "init ";
         if (!exportSingleObject(initial, name, expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
         assignment << "#" << comments << std::endl;
         if (!exportSingleObject(assignment, name, expression, comments))
           return false;
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterXPPAUT::exportSingleModVal (const CModelValue * modval, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 445 of file CODEExporterXPPAUT.cpp.
References CModelEntity::ASSIGNMENT, CODEExporter::assignment, exportSingleObject(), CModelEntity::FIXED, CODEExporter::fixed, CModelEntity::getKey(), CModelEntity::getStatus(), CODEExporter::initial, CODEExporter::NameMap, and CModelEntity::ODE.
 {
   switch (modval->getStatus())
     {
       case CModelEntity::FIXED:
       {
         fixed << "#" << comments << std::endl;
         fixed << "param ";
         if (!exportSingleObject(fixed, NameMap[modval->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ODE:
       {
         initial << "#" << comments << std::endl;
         initial << "init ";
         if (!exportSingleObject(initial, NameMap[modval->getKey()], expression, comments))
           return false;
         break;
       }
       case CModelEntity::ASSIGNMENT:
       {
 #if 0
         assignment << "#" << comments << std::endl;
         if (!exportSingleObject(assignment, NameMap[modval->getKey()], expression, comments))
           return false;
 #endif
         break;
       }
       default:
         return false;
         break;
     }
   return true;
 }
bool CODEExporterXPPAUT::exportSingleObject (std::ostringstream & which, const std::string & name, const std::string & expression, const std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 324 of file CODEExporterXPPAUT.cpp.
References exportSingleLine().
Referenced by exportSingleCompartment(), exportSingleMetabolite(), exportSingleModelEntity(), exportSingleModVal(), exportSingleODE(), and exportSingleParameter().
 {
   std::ostringstream line;
   line << name << "=" << expression;
   exportSingleLine(line.str(), which);
   return true;
 }
bool CODEExporterXPPAUT::exportSingleODE (const CModelEntity * mentity, std::string & equation, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 584 of file CODEExporterXPPAUT.cpp.
References exportSingleObject(), CModelEntity::getKey(), CODEExporter::isEmptyString(), CODEExporter::NameMap, and CODEExporter::ode.
 {
   std::ostringstream odeKey;
   if (!isEmptyString(comments)) ode << "#" << comments << std::endl;
   odeKey << "ode_" << mentity->getKey();
   if (!exportSingleObject(ode, NameMap[odeKey.str()], equation, comments)) return false;
   return true;
 }
bool CODEExporterXPPAUT::exportSingleParameter (const CCopasiParameter * param, std::string & expression, std::string & comments) virtual
Reimplemented from CODEExporter.
Definition at line 550 of file CODEExporterXPPAUT.cpp.
References exportSingleObject(), CODEExporter::fixed, CCopasiParameter::getKey(), and CODEExporter::NameMap.
 {
   fixed << "#" << comments << std::endl;
   fixed << "param ";
   if (!exportSingleObject(fixed, NameMap[param->getKey()], expression, comments)) return false;
   return true;
 }
bool CODEExporterXPPAUT::exportTitleData (const CCopasiDataModel * pDataModel, std::ostream & os) virtual
Definition at line 57 of file CODEExporterXPPAUT.cpp.
References CTrajectoryProblem::getDuration(), CCopasiTask::getProblem(), and CTrajectoryProblem::getStepSize().
 {
   os << "@ t0=0,";  //TODO
   const CTrajectoryTask * pTrajectory =
     dynamic_cast<const CTrajectoryTask *>((*const_cast<CCopasiDataModel*>(pDataModel)->getTaskList())["Time-Course"]);
   const CTrajectoryProblem * pTrajectoryProblem =
     dynamic_cast<const CTrajectoryProblem *>(pTrajectory->getProblem());
   os << "total=" << pTrajectoryProblem->getDuration() << ",";
   os << "dt=" << pTrajectoryProblem->getStepSize()
      << ",METH=stiff" << std::endl; //gear is the only method with automatic step size
   return true;
 }
std::string CODEExporterXPPAUT::exportTitleString (const size_t tmp) virtual
Reimplemented from CODEExporter.
Definition at line 597 of file CODEExporterXPPAUT.cpp.
References CODEExporter::ASSIGNMENT, CODEExporter::FIXED, CODEExporter::FUNCTIONS, CODEExporter::HEADERS, CODEExporter::INITIAL, and CODEExporter::ODEs.
 {
   switch (tmp)
     {
       case INITIAL:
         return "# Initial values:";
       case FIXED:
         return "# Fixed Model Entities:";
       case ASSIGNMENT:
         return "# Assignment Model Entities:";
       case FUNCTIONS:
         return "#Kinetics:  ";
       case HEADERS:
         return " ";
       case ODEs:
         return "# Equations:";
       default:
         return " ";
     }
 }
std::string CODEExporterXPPAUT::getDisplayExpressionString (CExpression * tmp) virtual
Reimplemented from CODEExporter.
Definition at line 568 of file CODEExporterXPPAUT.cpp.
References CEvaluationNode::buildXPPString(), and CEvaluationTree::getRoot().
 {
   std::string str1;
   str1 = tmp->getRoot()->buildXPPString();
   return str1;
 }
std::string CODEExporterXPPAUT::getDisplayFunctionString (CFunction * func) virtual
Reimplemented from CODEExporter.
Definition at line 561 of file CODEExporterXPPAUT.cpp.
References CEvaluationNode::buildXPPString(), and CEvaluationTree::getRoot().
 {
   std::string str1;
   str1 = func->getRoot()->buildXPPString();
   return str1;
 }
std::string CODEExporterXPPAUT::KineticFunction2ODEmember (const CReaction * reac) virtual
Reimplemented from CODEExporter.
Definition at line 575 of file CODEExporterXPPAUT.cpp.
References CReaction::getKey(), and CODEExporter::NameMap.
 {
   std::ostringstream localKey;
   localKey << reac->getKey() << "_root_func";
   return NameMap[localKey.str()];
 }
std::string CODEExporterXPPAUT::setConcentrationName (const std::string & objName) virtual
Reimplemented from CODEExporter.
Definition at line 251 of file CODEExporterXPPAUT.cpp.
 {
   return objName + "_c";
 }
std::string CODEExporterXPPAUT::setODEName (const std::string & objName) virtual
Reimplemented from CODEExporter.
Definition at line 246 of file CODEExporterXPPAUT.cpp.
 {
   return "d" + objName + "/dt";
 }
void CODEExporterXPPAUT::setReservedNames () virtual
Reimplemented from CODEExporter.
Definition at line 224 of file CODEExporterXPPAUT.cpp.
References Frequancy, and NameSet.
 {
   size_t i;
   const std::string reserved[45] =
   {
     "SIN", "COS", "TAN", "ATAN", "ATAN2", "SINH", "EXP", "DELAY", "LN", "LOG10",
     "LOG", "T", "PI", "IF", "THEN", "ELSE", "ASIN", "ACOS", "HEAV", "SIGN",
     "CEIL", "FLR", "RAN", "ABS", "MAX", "MIN", "NORMAL", "BESSELJ", "BESSELY", "ERF",
     "ERFS", "ARG1", "ARG2", "ARG2", "ARG4", "ARG5", "ARG6", "ARG7", "ARG8", "ARG9",
     "SHIFT", "NOT", "INT", "SUM", "OF"
   };
   for (i = 0; i < 45; i++)
     {
       NameSet.insert(reserved[i]);
       Frequancy[reserved[i]] = 0;
     }
   return;
 }
std::string CODEExporterXPPAUT::testName (const std::string & name)
This method tests whether the given XPPAUT name already assigned, put the new name (in cappital letters: all names can be upper or lower case) in the set of assigned names or modify the name
Definition at line 162 of file CODEExporterXPPAUT.cpp.
References CCopasiMessage::ERROR, fatalError, Frequancy, and NameSet.
Referenced by translateObjectName().
 {
   std::locale C("C");
   char ch;
   std::ostringstream newname, tmp;
   size_t name_size = name.size();
   size_t i;
   for (i = 0; i < name_size; i++)
     {
       ch = name[i];
       if (std::isalpha(ch, C) && std::islower(ch, C))
         tmp << (char) toupper(ch);
       else
         tmp << ch;
     }
   if (NameSet.find(tmp.str()) == NameSet.end())
     {
       NameSet.insert(tmp.str());
       Frequancy[tmp.str()] = 0;
       return name;
     }
   else
     {
       std::string ecount;
       std::ostringstream tmpecount;
       std::ostringstream tmpname;
       size_t ecount_size, tmpname_size;
       Frequancy[tmp.str()]++;
       tmpecount << Frequancy[tmp.str()];
       ecount = tmpecount.str();
       ecount_size = ecount.size();
       if (ecount_size > 6)
         {
           CCopasiMessage(CCopasiMessage::ERROR, "too many repeated names to modify to XPP syntax"); //TODO
           fatalError();
         }
       tmpname_size = name_size + ecount_size;
       if (tmpname_size > 7)
         {
           for (i = 0; i < (7 - ecount_size); i++)
             tmpname << name[i];
         }
       else
         tmpname << name << ecount;
       return testName(tmpname.str());
     }
 }
std::string CODEExporterXPPAUT::translateObjectName (const std::string & realName) virtual
This method adapt a Copasi name for XPPAUT syntax: all XPPAUT names can have up to 9 letters each. Names can not start with a number. Any other combination of letters and numbers is valid as is the underscore.
Reimplemented from CODEExporter.
Definition at line 80 of file CODEExporterXPPAUT.cpp.
References testName().
 {
   std::locale C("C");
   char ch;
   std::string newName;
   std::ostringstream tmpName;
   size_t realName_size = realName.size();
   size_t i;
   ch = realName[0];
   if (!std::isalpha(ch, C))
     {
       tmpName << "_";
       if (std::isdigit(ch, C)) tmpName << ch;
     }
   else tmpName << ch;
   for (i = 1; i < realName_size; i++)
     {
       ch = realName[i];
       if (std::isalpha(ch, C))
         {
           if (std::isspace(realName[i - 1], C) && std::islower(ch, C))
             tmpName << (char) toupper(ch);
           else
             tmpName << ch;
         }
       if (std::isdigit(ch, C)) tmpName << ch;
       if (std::ispunct(ch, C))
         switch (ch)
           {
             case '_':
               tmpName << ch;
               break;
             case '-':
               tmpName << "_";
               break;
             case '{':
               tmpName << "_";
               break;
             case '}':
               tmpName << "_";
               break;
             default:
               break;
           }
     }
   newName = tmpName.str();
   size_t newName_size = newName.size();
   if (newName_size > 7)
     {
       std::ostringstream cutName;
       for (i = 0; i < 7; i++)
         cutName << newName[i];
       newName = cutName.str();
     }
   return testName(newName);
 }
std::string CODEExporterXPPAUT::translateTimeVariableName () virtual
Reimplemented from CODEExporter.
Definition at line 72 of file CODEExporterXPPAUT.cpp.
 {return "t";}
Member Data Documentation
std::map< std::string, unsigned C_INT32 > CODEExporterXPPAUT::Frequancy
Definition at line 78 of file CODEExporterXPPAUT.h.
Referenced by setReservedNames(), and testName().
std::set<std::string> CODEExporterXPPAUT::NameSet
Definition at line 79 of file CODEExporterXPPAUT.h.
Referenced by setReservedNames(), and testName().
The documentation for this class was generated from the following files:
CODEExporterXPPAUT.h
CODEExporterXPPAUT.cpp