COPASI API: test000065 Class Reference
test000065 Class Reference
#include <test000065.h>
Public Member Functions
void setUp ()
void tearDown ()
void test_import_reaction_with_unsuitable_kinetic_1 ()
void test_import_reaction_with_unsuitable_kinetic_2 ()
Static Protected Attributes
static const char * MODEL_STRING1
static const char * MODEL_STRING2
static CCopasiDataModel * pCOPASIDATAMODEL = NULL
Private Member Functions
CPPUNIT_TEST (test_import_reaction_with_unsuitable_kinetic_1)
CPPUNIT_TEST (test_import_reaction_with_unsuitable_kinetic_2)
CPPUNIT_TEST_SUITE (test000065)
CPPUNIT_TEST_SUITE_END ()
Detailed Description
Definition at line 26 of file test000065.h.
Member Function Documentation
test000065::CPPUNIT_TEST (test_import_reaction_with_unsuitable_kinetic_1) private
test000065::CPPUNIT_TEST (test_import_reaction_with_unsuitable_kinetic_2) private
test000065::CPPUNIT_TEST_SUITE (test000065) private
test000065::CPPUNIT_TEST_SUITE_END () private
void test000065::setUp ()
Definition at line 44 of file test000065.cpp.
References CCopasiRootContainer::addDatamodel(), CCopasiRootContainer::init(), and pCOPASIDATAMODEL.
 {
   // Create the root container.
   CCopasiRootContainer::init(0, NULL, false);
   // Create the global data model.
   pCOPASIDATAMODEL = CCopasiRootContainer::addDatamodel();
 }
void test000065::tearDown ()
Definition at line 52 of file test000065.cpp.
References CCopasiRootContainer::destroy().
 {
   CCopasiRootContainer::destroy();
 }
void test000065::test_import_reaction_with_unsuitable_kinetic_1 ()
Definition at line 57 of file test000065.cpp.
References CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiDataModel::getModel(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING1, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CEvaluationNodeOperator::PLUS, CModel::s, CEvaluationNode::subType(), TriUnspecified, CEvaluationNode::type(), CEvaluationTree::UserDefined, and CEvaluationNode::VARIABLE.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING1));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 4);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 2);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 2);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == false);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->isReversible() == TriUnspecified);
   // just to be sure also check the tree
   const CEvaluationNode* pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::DIVIDE);
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   const CEvaluationNodeVariable* pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getData() == "Vmax");
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   // can't check the variable name here since  I don't know what name has been
   // created for it
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getData() == "Km");
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   // can't check the variable name here since  I don't know what name has been
   // created for it
 }
void test000065::test_import_reaction_with_unsuitable_kinetic_2 ()
Definition at line 123 of file test000065.cpp.
References CEvaluationNodeOperator::DIVIDE, CModelEntity::FIXED, CCopasiNode< _Data >::getChild(), CCopasiNode< _Data >::getData(), CCopasiDataModel::getModel(), CEvaluationNode::getType(), CCopasiDataModel::importSBMLFromString(), CModel::ml, CModel::mMol, MODEL_STRING2, CEvaluationNodeOperator::MULTIPLY, CEvaluationNode::OPERATOR, pCOPASIDATAMODEL, CEvaluationNodeOperator::PLUS, CModel::s, CEvaluationNode::subType(), TriUnspecified, CEvaluationNode::type(), CEvaluationTree::UserDefined, and CEvaluationNode::VARIABLE.
 {
   CCopasiDataModel* pDataModel = pCOPASIDATAMODEL;
   CPPUNIT_ASSERT(pDataModel->importSBMLFromString(MODEL_STRING2));
   CModel* pModel = pDataModel->getModel();
   CPPUNIT_ASSERT(pModel != NULL);
   CPPUNIT_ASSERT(pModel->getQuantityUnitEnum() == CModel::mMol);
   CPPUNIT_ASSERT(pModel->getVolumeUnitEnum() == CModel::ml);
   CPPUNIT_ASSERT(pModel->getTimeUnitEnum() == CModel::s);
   CPPUNIT_ASSERT(pModel->getCompartments().size() == 1);
   const CCompartment* pCompartment = pModel->getCompartments()[0];
   CPPUNIT_ASSERT(pCompartment != NULL);
   CPPUNIT_ASSERT(pCompartment->getStatus() == CModelEntity::FIXED);
   CPPUNIT_ASSERT(pModel->getMetabolites().size() == 4);
   CPPUNIT_ASSERT(pModel->getReactions().size() == 1);
   const CReaction* pReaction = pModel->getReactions()[0];
   CPPUNIT_ASSERT(pReaction != NULL);
   CPPUNIT_ASSERT(pReaction->getChemEq().getSubstrates().size() == 2);
   CPPUNIT_ASSERT(pReaction->getChemEq().getProducts().size() == 2);
   CPPUNIT_ASSERT(pReaction->getChemEq().getModifiers().size() == 0);
   CPPUNIT_ASSERT(pReaction->isReversible() == false);
   const CFunction* pFunction = pReaction->getFunction();
   CPPUNIT_ASSERT(pFunction != NULL);
   CPPUNIT_ASSERT(pFunction->getType() == CEvaluationTree::UserDefined);
   CPPUNIT_ASSERT(pFunction->isReversible() == TriUnspecified);
   // just to be sure also check the tree
   const CEvaluationNode* pRoot = pFunction->getRoot();
   CPPUNIT_ASSERT(pRoot != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pRoot->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pRoot->getType()) == CEvaluationNodeOperator::DIVIDE);
   const CEvaluationNode* pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::MULTIPLY);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   const CEvaluationNodeVariable* pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getData() == "Vmax");
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   // can't check the variable name here since  I don't know what name has been
   // created for it
   pChild = dynamic_cast<const CEvaluationNode*>(pRoot->getChild()->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::OPERATOR);
   CPPUNIT_ASSERT((CEvaluationNodeOperator::SubType)CEvaluationNode::subType(pChild->getType()) == CEvaluationNodeOperator::PLUS);
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getChild());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   CPPUNIT_ASSERT(pVariableNode->getData() == "Km");
   pChild = dynamic_cast<const CEvaluationNode*>(pChild->getSibling());
   CPPUNIT_ASSERT(pChild != NULL);
   CPPUNIT_ASSERT(CEvaluationNode::type(pChild->getType()) == CEvaluationNode::VARIABLE);
   pVariableNode = dynamic_cast<const CEvaluationNodeVariable*>(pChild);
   CPPUNIT_ASSERT(pVariableNode != NULL);
   // can't check the variable name here since  I don't know what name has been
   // created for it
 }
Member Data Documentation
const char * test000065::MODEL_STRING1 static protected
Definition at line 34 of file test000065.h.
Referenced by test_import_reaction_with_unsuitable_kinetic_1().
const char * test000065::MODEL_STRING2 static protected
Definition at line 35 of file test000065.h.
Referenced by test_import_reaction_with_unsuitable_kinetic_2().
CCopasiDataModel * test000065::pCOPASIDATAMODEL = NULL static protected
These tests are supposed to make sure that assignments on a species with the hasOnlySubstanceUnits flag set are exported correctly. It tests rules and event assignments with and without the flag set.
Definition at line 36 of file test000065.h.
Referenced by setUp(), test_import_reaction_with_unsuitable_kinetic_1(), and test_import_reaction_with_unsuitable_kinetic_2().
The documentation for this class was generated from the following files:
test000065.h
test000065.cpp