COPASI API: CQLayoutScene Class Reference
CQLayoutScene Class Reference
#include <CQLayoutScene.h>
Public Slots
void recreate ()
Signals
void recreateNeeded ()
Public Member Functions
CQLayoutScene (CLayout *layout, CCopasiDataModel *model=NULL, CLRenderInformationBase *renderInformation=NULL)
const CLayout * getCurrentLayout () const
CLayout * getCurrentLayout ()
const CLRenderInformationBase * getCurrentRenderInfo () const
QGraphicsItem * getItemFor (const std::string &cn)
const CLRenderResolver * getResolver () const
void saveToFile (const std::string &fileName, const std::string &fileType="pdf")
void setLayout (CLayout *layout, CCopasiDataModel *model=NULL, CLRenderInformationBase *renderInformation=NULL)
void setRenderInformation (CCopasiDataModel *model, CLRenderInformationBase *renderInformation)
void setResolver (CLRenderResolver *resolver)
void updatePosition (const QString &key, const QPointF &newPos)
virtual ~CQLayoutScene ()
Protected Member Functions
void initializeResolver (CCopasiDataModel *model, CLRenderInformationBase *renderInformation)
Private Member Functions
void addGlyph (const CLGraphicalObject *go)
void fillFromLayout (const CLayout *layout)
Private Attributes
std::map< std::string,
QGraphicsItem * > mItems
CLayout * mpLayout
CLRenderInformationBase * mpRender
QSharedPointer< CLRenderResolver > mpResolver
Detailed Description
Definition at line 22 of file CQLayoutScene.h.
Constructor & Destructor Documentation
CQLayoutScene::CQLayoutScene (CLayout * layout, CCopasiDataModel * model = NULL, CLRenderInformationBase * renderInformation = NULL)
Definition at line 37 of file CQLayoutScene.cpp.
References initializeResolver(), recreate(), and recreateNeeded().
   : QGraphicsScene()
   , mpLayout(layout)
   , mpRender(renderInformation)
   , mpResolver(NULL)
 {
   initializeResolver(model, renderInformation);
   connect(this, SIGNAL(recreateNeeded()), this, SLOT(recreate()), Qt::QueuedConnection);
 }
CQLayoutScene::~CQLayoutScene () virtual
Definition at line 137 of file CQLayoutScene.cpp.
 {
 }
Member Function Documentation
void CQLayoutScene::addGlyph (const CLGraphicalObject * go) private
Definition at line 147 of file CQLayoutScene.cpp.
References CCopasiVector< T >::begin(), COPASI_OBJECT_CN, CCopasiVector< T >::end(), CCopasiObject::getCN(), CLGlyphWithCurve::getCurve(), CLGeneralGlyph::getListOfSubglyphs(), CLGraphicalObject::getModelObject(), CLCurve::getNumCurveSegments(), mItems, and mpResolver.
Referenced by fillFromLayout().
 {
   if (go == NULL) return;
   const CLGlyphWithCurve* curveGlyph = dynamic_cast<const CLGlyphWithCurve*>(go);
   const CLReactionGlyph* reaction = dynamic_cast<const CLReactionGlyph*>(go);
   const CLTextGlyph* text = dynamic_cast<const CLTextGlyph*>(go);
   const CLGeneralGlyph* general = dynamic_cast<const CLGeneralGlyph*>(go);
   QGraphicsItem *item = NULL;
   if (curveGlyph != NULL)
     {
       if (curveGlyph->getCurve().getNumCurveSegments() > 0 || reaction != NULL || general != NULL)
         item = new CQConnectionGraphicsItem(curveGlyph,
                                             mpResolver == NULL ? NULL : mpResolver.data());
     }
   else if (text != NULL)
     {
       item = new CQLabelGraphicsItem(text, mpResolver == NULL ? NULL : mpResolver.data());
     }
   else
     {
       item = new CQStyledGraphicsItem(go, mpResolver == NULL ? NULL : mpResolver.data());
     }
   if (item != NULL)
     {
       CCopasiObject* obj = go->getModelObject();
       if (obj != NULL && text == NULL)
         {
           item->setData(COPASI_OBJECT_CN, QString(obj->getCN().c_str()));
           mItems[obj->getCN()] = item;
         }
       addItem(item);
     }
   if (general != NULL)
     {
       const CCopasiVector<CLGraphicalObject> & subGlyphs = general->getListOfSubglyphs();
       CCopasiVector<CLGraphicalObject>::const_iterator it = subGlyphs.begin();
       while (it != subGlyphs.end())
         {
           addGlyph(*it);
           ++it;
         }
     }
 }
void CQLayoutScene::fillFromLayout (const CLayout * layout) private
Definition at line 203 of file CQLayoutScene.cpp.
References addGlyph(), CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CLRenderInformationBase::getBackgroundColor(), CLayout::getListOfCompartmentGlyphs(), CLayout::getListOfGeneralGlyphs(), CLayout::getListOfMetaboliteGlyphs(), CLayout::getListOfReactionGlyphs(), CLayout::getListOfTextGlyphs(), mItems, mpRender, mpResolver, and CQRenderConverter::setBackground().
Referenced by recreate().
 {
   if (layout == NULL) return;
   clear();
   mItems.clear();
   if (mpRender != NULL && mpResolver != NULL)
     {
       CQRenderConverter::setBackground(this, mpRender->getBackgroundColor(), mpResolver.data());
     }
   const CCopasiVector<CLCompartmentGlyph> & comps = layout->getListOfCompartmentGlyphs();
   CCopasiVector<CLCompartmentGlyph>::const_iterator itComp = comps.begin();
   while (itComp != comps.end())
     {
       addGlyph(*itComp);
       ++itComp;
     }
   const CCopasiVector<CLReactionGlyph> & reactions = layout->getListOfReactionGlyphs();
   CCopasiVector<CLReactionGlyph>::const_iterator itReactions = reactions.begin();
   while (itReactions != reactions.end())
     {
       addGlyph(*itReactions);
       ++itReactions;
     }
   const CCopasiVector<CLMetabGlyph> & species = layout->getListOfMetaboliteGlyphs();
   CCopasiVector<CLMetabGlyph>::const_iterator itSpecies = species.begin();
   while (itSpecies != species.end())
     {
       addGlyph(*itSpecies);
       ++itSpecies;
     }
   const CCopasiVector<CLTextGlyph> & texts = layout->getListOfTextGlyphs();
   CCopasiVector<CLTextGlyph>::const_iterator itTexts = texts.begin();
   while (itTexts != texts.end())
     {
       addGlyph(*itTexts);
       ++itTexts;
     }
   const CCopasiVector<CLGeneralGlyph> & list = layout->getListOfGeneralGlyphs();
   CCopasiVector<CLGeneralGlyph>::const_iterator itList = list.begin();
   while (itList != list.end())
     {
       addGlyph(*itList);
       ++itList;
     }
 }
const CLayout * CQLayoutScene::getCurrentLayout () const
Definition at line 58 of file CQLayoutScene.cpp.
References mpLayout.
Referenced by CQAnimationWindow::setScene(), CQAnimationWindow::slotAutoLayout(), CQLayoutView::slotLayoutChanged(), CQAnimationWindow::slotLayoutStateChanged(), CQAnimationWindow::slotRandomizeLayout(), and CQLayoutView::slotRenderInformationChanged().
 {
   return mpLayout;
 }
CLayout * CQLayoutScene::getCurrentLayout ()
Definition at line 63 of file CQLayoutScene.cpp.
References mpLayout.
 {
   return mpLayout;
 }
const CLRenderInformationBase * CQLayoutScene::getCurrentRenderInfo () const
Definition at line 68 of file CQLayoutScene.cpp.
References mpRender.
 {
   return mpRender;
 }
QGraphicsItem * CQLayoutScene::getItemFor (const std::string & cn)
Definition at line 198 of file CQLayoutScene.cpp.
References mItems.
Referenced by CQEffectDescription::applyToScene(), and CQEffectDescription::removeFromScene().
 {
   return mItems[cn];
 }
const CLRenderResolver * CQLayoutScene::getResolver () const
Definition at line 132 of file CQLayoutScene.cpp.
References mpResolver.
 {
   return mpResolver.data();
 }
void CQLayoutScene::initializeResolver (CCopasiDataModel * model, CLRenderInformationBase * renderInformation) protected
Definition at line 99 of file CQLayoutScene.cpp.
References getDefaultStyle(), CListOfLayouts::getListOfGlobalRenderInformationObjects(), CCopasiDataModel::getListOfLayouts(), CLayout::getListOfLocalRenderInformationObjects(), mpLayout, mpRender, mpResolver, and CCopasiVector< T >::size().
Referenced by CQLayoutScene(), and setRenderInformation().
 {
   if (model == NULL)
     return;
   if (renderInformation == NULL)
     {
       if (mpLayout != NULL && mpLayout->getListOfLocalRenderInformationObjects().size() > 0)
         mpRender = mpLayout->getListOfLocalRenderInformationObjects()[0];
       else if (model->getListOfLayouts()->getListOfGlobalRenderInformationObjects().size() > 0)
         mpRender = model->getListOfLayouts()->getListOfGlobalRenderInformationObjects()[0];
       else
         mpRender = getDefaultStyle(0);
     }
   else
     mpRender = renderInformation;
   if (mpLayout == NULL || mpRender == NULL)
     return;
   CLLocalRenderInformation* local = dynamic_cast<CLLocalRenderInformation*>(mpRender);
   if (local != NULL)
     mpResolver = QSharedPointer<CLRenderResolver>(new CLRenderResolver(*local, mpLayout->getListOfLocalRenderInformationObjects(),   model->getListOfLayouts()->getListOfGlobalRenderInformationObjects()));
   else
     mpResolver = QSharedPointer<CLRenderResolver>(new CLRenderResolver(*dynamic_cast<CLGlobalRenderInformation*>(mpRender), model->getListOfLayouts()->getListOfGlobalRenderInformationObjects()));
 }
void CQLayoutScene::recreate () slot
Definition at line 141 of file CQLayoutScene.cpp.
References fillFromLayout(), and mpLayout.
Referenced by CQLayoutScene(), Arguments::handleCommandLine(), CQAnimationWindow::setScene(), CQLayoutView::slotLayoutChanged(), CQAnimationWindow::slotLayoutStateChanged(), and CQLayoutView::slotRenderInformationChanged().
 {
   fillFromLayout(mpLayout);
   invalidate();
 }
void CQLayoutScene::recreateNeeded () signal
Referenced by CQLayoutScene(), and updatePosition().
void CQLayoutScene::saveToFile (const std::string & fileName, const std::string & fileType = "pdf")
Definition at line 73 of file CQLayoutScene.cpp.
Referenced by Arguments::handleCommandLine(), and CQLayoutView::slotSaveToFile().
 {
   if (fileType == "pdf")
     {
       QPrinter printer(QPrinter::HighResolution);
       printer.setOutputFormat(QPrinter::PdfFormat);
       printer.setOutputFileName(fileName.c_str());
       QPainter painter(&printer);
       painter.setRenderHints(
         QPainter::Antialiasing | QPainter::HighQualityAntialiasing | QPainter::SmoothPixmapTransform);
       render(&painter, QRect(), itemsBoundingRect());
       painter.end();
     }
   else
     {
       const int scale = 2;
       QImage image(QSize(width()*scale, height()*scale), QImage::Format_ARGB32);
       QPainter painter(&image);
       painter.setRenderHints(
         QPainter::Antialiasing | QPainter::HighQualityAntialiasing | QPainter::SmoothPixmapTransform);
       render(&painter, image.rect(), itemsBoundingRect());
       painter.end();
       image.save(fileName.c_str(), fileType.c_str());
     }
 }
void CQLayoutScene::setLayout (CLayout * layout, CCopasiDataModel * model = NULL, CLRenderInformationBase * renderInformation = NULL)
Definition at line 47 of file CQLayoutScene.cpp.
References mpLayout, and setRenderInformation().
Referenced by CQLayoutView::slotLayoutChanged().
 {
   mpLayout = layout;
   setRenderInformation(model, renderInformation);
 }
void CQLayoutScene::setRenderInformation (CCopasiDataModel * model, CLRenderInformationBase * renderInformation)
Definition at line 53 of file CQLayoutScene.cpp.
References initializeResolver().
Referenced by setLayout(), and CQLayoutView::slotRenderInformationChanged().
 {
   initializeResolver(model, renderInformation);
 }
void CQLayoutScene::setResolver (CLRenderResolver * resolver)
Definition at line 127 of file CQLayoutScene.cpp.
References mpResolver.
 {
   mpResolver = QSharedPointer<CLRenderResolver>(resolver);
 }
void CQLayoutScene::updatePosition (const QString & key, const QPointF & newPos)
Definition at line 335 of file CQLayoutScene.cpp.
References CCopasiSpringLayout::finalizeState(), CKeyFactory::get(), CCopasiRootContainer::getKeyFactory(), moveObject(), mpLayout, and recreateNeeded().
Referenced by CQStyledGraphicsItem::mouseReleaseEvent(), and CQConnectionGraphicsItem::mouseReleaseEvent().
 {
   CKeyFactory* kf = CCopasiRootContainer::getKeyFactory();
   if (kf == NULL) return;
   CLGraphicalObject* obj = dynamic_cast<CLGraphicalObject*>(kf->get(key.toStdString()));
   if (obj == NULL) return;
   CLPoint delta(newPos.x(), newPos.y());
   moveObject(obj, delta, mpLayout);
   // restore lines
   CCopasiSpringLayout::Parameters p;
   CCopasiSpringLayout l(mpLayout, &p);
   l.finalizeState();
   emit recreateNeeded();
 }
Member Data Documentation
std::map< std::string, QGraphicsItem*> CQLayoutScene::mItems private
Definition at line 52 of file CQLayoutScene.h.
Referenced by addGlyph(), fillFromLayout(), and getItemFor().
CLayout* CQLayoutScene::mpLayout private
Definition at line 48 of file CQLayoutScene.h.
Referenced by getCurrentLayout(), initializeResolver(), recreate(), setLayout(), and updatePosition().
CLRenderInformationBase* CQLayoutScene::mpRender private
Definition at line 49 of file CQLayoutScene.h.
Referenced by fillFromLayout(), getCurrentRenderInfo(), and initializeResolver().
QSharedPointer<CLRenderResolver> CQLayoutScene::mpResolver private
Definition at line 50 of file CQLayoutScene.h.
Referenced by addGlyph(), fillFromLayout(), getResolver(), initializeResolver(), and setResolver().
The documentation for this class was generated from the following files:
CQLayoutScene.h
CQLayoutScene.cpp