COPASI API: CODEExporter.cpp File Reference
CODEExporter.cpp File Reference
#include <locale>
#include <cmath>
#include <iostream>
#include <fstream>
#include <sstream>
#include <ctype.h>
#include "copasi.h"
#include "CopasiDataModel/CCopasiDataModel.h"
#include "report/CCopasiRootContainer.h"
#include "CODEExporter.h"
#include "model/CModel.h"
#include "model/CMetab.h"
#include "model/CMetabNameInterface.h"
#include "utilities/CCopasiVector.h"
#include "model/CReaction.h"
#include "model/CMoiety.h"
#include "model/CChemEqElement.h"
#include "function/CFunction.h"
#include "function/CExpression.h"
#include "function/CFunctionDB.h"
#include "report/CKeyFactory.h"
#include "function/CEvaluationTree.h"
#include "function/CEvaluationNode.h"
#include "function/CEvaluationNodeObject.h"
#include "function/CEvaluationNodeOperator.h"
#include "function/CEvaluationNodeFunction.h"
#include "utilities/CCopasiTree.h"
#include "utilities/CCopasiMessage.h"
#include "commandline/CLocaleString.h"
#include "trajectory/CTrajectoryTask.h"
#include "trajectory/CTrajectoryProblem.h"
Functions
std::string getQuantityParameterOrValue (const std::map< std::string, std::string > &map, const CCopasiDataModel *pDataModel)
size_t getReactionIndex (const CCopasiVector< CReaction > &reacs, const CReaction *react)
Function Documentation
std::string getQuantityParameterOrValue (const std::map< std::string, std::string > & map, const CCopasiDataModel * pDataModel)
Definition at line 539 of file CODEExporter.cpp.
References CCopasiVector< T >::begin(), CCopasiVector< T >::end(), CCopasiDataModel::getModel(), CModel::getModelValues(), and CModel::getQuantity2NumberFactor().
Referenced by CODEExporter::exportExpression().
 {
   double val = pDataModel->getModel()->getQuantity2NumberFactor();
   const CCopasiVectorN< CModelValue >& vals = pDataModel->getModel()->getModelValues();
   CCopasiVectorN< CModelValue >::const_iterator it = vals.begin();
   for (; it != vals.end(); ++it)
     {
       std::map< std::string, std::string >::const_iterator key = map.find((*it)->getKey());
       if ((*it)->getInitialValue() == val && key != map.end())
         return key->second;
     }
   std::ostringstream str;
   str << val;
   return str.str();
 }
size_t getReactionIndex (const CCopasiVector< CReaction > & reacs, const CReaction * react)
Definition at line 528 of file CODEExporter.cpp.
References C_INVALID_INDEX, and CCopasiVector< T >::size().
Referenced by CODEExporter::exportExpression(), and CEFMTask::getFluxModeDescription().
 {
   for (size_t i = 0; i < reacs.size(); ++i)
     {
       if (reacs[i] == react)
         return i;
     }
   return C_INVALID_INDEX;
 }