COPASI API: CTableRow Class Reference
CTableRow Class Reference
#include <CTableCell.h>
Public Member Functions
CTableRow (const size_t &size=0, const char &separator= '\t')
CTableRow (const CTableRow &src)
const std::vector< CTableCell > & getCells () const
const size_t & getLastFilledCell () const
size_t guessColumnNumber (std::istream &is, const bool &rewind)
const bool & isEmpty () const
bool resize (const size_t &size)
size_t size () const
~CTableRow ()
Private Member Functions
std::istream & readLine (std::istream &is)
Private Attributes
std::vector< CTableCell > mCells
bool mIsEmpty
size_t mLastFilledCell
char mSeparator
Friends
std::istream & operator>> (std::istream &is, CTableRow &cell)
Detailed Description
Definition at line 109 of file CTableCell.h.
Constructor & Destructor Documentation
CTableRow::CTableRow (const size_t & size = 0, const char & separator = '\t')
Default constructor
Parameters
const unisgned C_INT32 & size (default: 0)
const char & separator (default: '')
Definition at line 124 of file CTableCell.cpp.
References resize().
                                             :
   mCells(0),
   mSeparator(separator),
   mIsEmpty(true),
   mLastFilledCell(C_INVALID_INDEX)
 {resize(size);}
CTableRow::CTableRow (const CTableRow & src)
Copy constructor
Parameters
const CTableRow & src
Definition at line 132 of file CTableCell.cpp.
                                          :
   mCells(src.mCells),
   mSeparator(src.mSeparator),
   mIsEmpty(src.mIsEmpty),
   mLastFilledCell(C_INVALID_INDEX)
 {}
CTableRow::~CTableRow ()
Destructor
Definition at line 139 of file CTableCell.cpp.
 {}
Member Function Documentation
const std::vector< CTableCell > & CTableRow::getCells () const
Retrieve the cells.
Returns
const std::vector< CTableCell > & cells
Definition at line 141 of file CTableCell.cpp.
References mCells.
Referenced by CExperiment::read(), and CExperiment::readColumnNames().
 {return mCells;}
const size_t & CTableRow::getLastFilledCell () const
Retrieve the index of the last non empty cell in the last read operation. size_t & lastFilledCell
Definition at line 160 of file CTableCell.cpp.
References mLastFilledCell.
 {return mLastFilledCell;}
size_t CTableRow::guessColumnNumber (std::istream & is, const bool & rewind)
Try to guess the number of columns in the current line
Parameters
std::istream &is
const bool & rewind
Returns
size_t numColumns
Definition at line 163 of file CTableCell.cpp.
References C_INVALID_INDEX, isEmpty(), and mCells.
Referenced by CExperiment::guessColumnNumber().
 {
   std::istream::pos_type pos;
   if (rewind) pos = is.tellg();
   is >> *this;
   if (rewind) is.seekg(pos);
   size_t count;
   for (count = mCells.size() - 1; count != C_INVALID_INDEX; count--)
     if (!mCells[count].isEmpty()) break;
   return count + 1;
 }
const bool & CTableRow::isEmpty () const
Check whether row contains any cells with data A row is considered empty when it all cells are empty.
Definition at line 182 of file CTableCell.cpp.
References mIsEmpty.
Referenced by guessColumnNumber().
 {return mIsEmpty;}
std::istream & CTableRow::readLine (std::istream & is) private
Fill the row with data from the inpute stream until End_Of_Line is encountered and advance the stream accordingly.
Parameters
std::istream & is
Returns
std::istream & is
Definition at line 184 of file CTableCell.cpp.
References C_INT, C_INVALID_INDEX, mCells, mIsEmpty, mLastFilledCell, and mSeparator.
Referenced by operator>>().
 {
   // Clear the line;
   std::stringstream line;
   char c;
   for (is.get(c); c != 0x0a && c != 0x0d; is.get(c))
     {
       if (is.fail() || is.eof()) break;
       line.put(c);
     }
   // Eat additional line break characters appearing on DOS and Mac text format;
   if ((c == 0x0d && is.peek() == 0x0a) || // DOS
       (c == 0x0a && is.peek() == 0x0d))   // Mac
     is.ignore(1);
   mIsEmpty = true;
   mLastFilledCell = C_INVALID_INDEX;
   std::vector< CTableCell >::iterator it = mCells.begin();
   std::vector< CTableCell >::iterator end = mCells.end();
   unsigned C_INT count;
   for (count = 0; it != end && !line.fail(); ++it, ++count)
     {
       line >> *it;
       if (!it->isEmpty())
         {
           mIsEmpty = false;
           mLastFilledCell = count;
         }
     }
   bool Finished = false;
   if (it == end)
     Finished = true;
   CTableCell Unread(mSeparator);
   while (!line.fail() && !line.eof())
     {
       mCells.push_back(Unread);
       line >> mCells.back();
       if (!mCells.back().isEmpty())
         {
           mIsEmpty = false;
           mLastFilledCell = count;
         }
       count++;
     }
   if (!Finished)
     {
       // Missing columns are filled with default
       for (; it != end; ++it)
         *it = Unread;
     }
   return is;
 }
bool CTableRow::resize (const size_t & size)
Resize
Parameters
const size_t & size
Returns
bool success
Definition at line 144 of file CTableCell.cpp.
References mCells, and mSeparator.
Referenced by CTableRow().
 {
   mCells.resize(size);
   std::vector< CTableCell >::iterator it = mCells.begin();
   std::vector< CTableCell >::iterator end = mCells.end();
   for (; it != end; ++it)
     it->setSeparator(mSeparator);
   return true;
 }
size_t CTableRow::size () const
Retrieve the size of the row
Returns
const size_t size
Definition at line 157 of file CTableCell.cpp.
References mCells.
 {return mCells.size();}
Friends And Related Function Documentation
std::istream& operator>> (std::istream & is, CTableRow & cell) friend
Formated stream input operator
Parameters
CTableRow & cell
Returns
std::istream &
Definition at line 253 of file CTableCell.cpp.
 {return row.readLine(is);}
Member Data Documentation
std::vector< CTableCell > CTableRow::mCells private
Definition at line 193 of file CTableCell.h.
Referenced by getCells(), guessColumnNumber(), readLine(), resize(), and size().
bool CTableRow::mIsEmpty private
Definition at line 197 of file CTableCell.h.
Referenced by isEmpty(), and readLine().
size_t CTableRow::mLastFilledCell private
Definition at line 199 of file CTableCell.h.
Referenced by getLastFilledCell(), and readLine().
char CTableRow::mSeparator private
Definition at line 195 of file CTableCell.h.
Referenced by readLine(), and resize().
The documentation for this class was generated from the following files:
CTableCell.h
CTableCell.cpp